### ISSUE TITLE
[gatsby-plugin-netlify] depracated webpack-assets-manifest causing errors during build

### ISSUE THREAD

**Issue by talohana** [gatsbyjs/gatsby#29974]
## Description

I am upgrading to gatsby v3 and I am using `gatsby-plugin-netlify`, during build time I get the following errors:

> ERROR
>
> (node:17164) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.> getCompilationHooks(compilation).loader
> (Use `node --trace-deprecation ...` to show where the warning was created)
>
> ERROR
>
> (node:17164) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
> BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
> Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
> Make sure to select an appropriate stage from Compilation.PROCESS*ASSETS_STAGE*\*.

I have drilled down a bit and found that cause of the problem was [a deprecated `webpack-assets-manifest` dependency](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-netlify/package.json#L20).

`webpack-assets-manifest` is compatible with webpack v5 as described [here](https://github.com/webdeveric/webpack-assets-manifest#new-in-version-5)

### Steps to reproduce

- Create a project with gatsby v3
- Add `gatsby-plugin-netlify`
- run `npm run build`

### Environment
<details>

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.81)
  npmPackages:
    gatsby: ^3.0.1 => 3.0.1 
    gatsby-plugin-google-analytics: ^3.0.0 => 3.0.0 
    gatsby-plugin-image: ^1.0.0 => 1.0.0 
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0 
    gatsby-plugin-mdx: ^2.0.0 => 2.0.0 
    gatsby-plugin-netlify: ^3.0.0 => 3.0.0 
    gatsby-plugin-offline: ^4.0.0 => 4.0.0 
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0 
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5 
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0 
    gatsby-plugin-sitemap: ^3.0.0 => 3.0.0 
    gatsby-plugin-styled-components: ^4.0.0 => 4.0.0 
    gatsby-remark-autolink-headers: ^3.0.0 => 3.0.0 
    gatsby-remark-copy-linked-files: ^3.0.0 => 3.0.0 
    gatsby-remark-embedder: ^4.1.0 => 4.1.0 
    gatsby-remark-images: ^4.0.0 => 4.0.0 
    gatsby-remark-prismjs: ^4.0.0 => 4.0.0 
    gatsby-source-filesystem: ^3.0.0 => 3.0.0 
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0 
</details>

I would be happy to submit a PR if needed 🚀

**Comment by pieh** [comment]
Hey @talohana - PR with upgrade would be most welcome! I can't tell from release notes of `webpack-assets-manifest` is this is just matter of upgrading or there will be any additional changes needed 🤔

**Comment by talohana** [comment]
Working on it right now. I'm stumbling an error while running `yarn upgrade webpack-plugin-manifest --latest`:
> error An unexpected error occurred: "expected workspace package to exist for "retext"".

There is a whole discussion about it here https://github.com/yarnpkg/yarn/issues/7807, which the solutions are:
- [Re-create yarn.lock](https://github.com/yarnpkg/yarn/issues/7807#issuecomment-594636027)
- [Downgrade yarn to 1.18.0](https://github.com/yarnpkg/yarn/issues/7807#issuecomment-588632848)

Seems a bit hacky, has anyone else encountered this before?

**Comment by spencersmb** [comment]
+1 for this issue. I just migrated to Gatsby v3 and updated all my plugins - one of which is the gatsby-plugin-netlify and am also seeing this issue when running the build command. I'm assuming it will get fixed by their team but wondering if there is anything we need to do in the mean time?

Thanks for writing this up @talohana
Spencer

**Comment by kimbaudi** [comment]
> I can't tell from release notes of webpack-assets-manifest is this is just matter of upgrading or there will be any additional changes needed

@pieh - upgrading to webpack-assets-manifest ^4.0.0 seems fine, but upgrading to ^5.0.0 throws error. After running `yarn jest gatsby-plugin-netlify`, I get a failed test w/ error message: `TypeError: Cannot read property 'RawSource' of undefined. (see [diff here](https://github.com/webdeveric/webpack-assets-manifest/compare/v4.0.0...v5.0.0#diff-4339a2cb62d011e3ce1c22332151f37cb37f17a2d9576010520118eef67e9613R17))

> Working on it right now. I'm stumbling an error while running `yarn upgrade webpack-plugin-manifest --latest`

@talohana - you should just be able to run `yarn remove webpack-assets-manifest` and `yarn add webpack-assets-manifest` to update `webpack-assets-manifest` to the latest v5.0.1. This should update the package.json file under `gatsby-plugin-netlify` folder and update `yarn.lock` file in root of `gatsby` repo.

**Comment by talohana** [comment]
> > I can't tell from release notes of webpack-assets-manifest is this is just matter of upgrading or there will be any additional changes needed
> 
> @pieh - upgrading to webpack-assets-manifest ^4.0.0 seems fine, but upgrading to ^5.0.0 throws error. After running `yarn jest gatsby-plugin-netlify`, I get a failed test w/ error message: `TypeError: Cannot read property 'RawSource' of undefined. (see [diff here](https://github.com/webdeveric/webpack-assets-manifest/compare/v4.0.0...v5.0.0#diff-4339a2cb62d011e3ce1c22332151f37cb37f17a2d9576010520118eef67e9613R17))
> 
> > Working on it right now. I'm stumbling an error while running `yarn upgrade webpack-plugin-manifest --latest`
> 
> @talohana - you should just be able to run `yarn remove webpack-assets-manifest` and `yarn add webpack-assets-manifest` to update `webpack-assets-manifest` to the latest v5.0.1. This should update the package.json file under `gatsby-plugin-netlify` folder and update `yarn.lock` file in root of `gatsby` repo.

I can remove the dependency, but re-adding it raises the same error

**Comment by kimbaudi** [comment]
@talohana - that is strange. I'm able to:

```shell
cd packages/gatsby-plugin-manifest
yarn remove webpack-assets-manifest
yarn add webpack-assets-manifest
```

in order to upgrade `webpack-assets-manifest`

**Comment by kalwalt** [comment]
Not sure if it is related but i have a similar issue. I'm migrating from gatsby v2.0 to v3.0 in my project  **gatsby-starter-i18n-bulma** related PR: /https://github.com/kalwalt/gatsby-starter-i18n-bulma/pull/139.
I have the gatsby-plugin-netlify too in my dependencies and i get this error:
```
6:39:21 PM: error (node:1852) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
6:39:49 PM: error (node:1852) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
6:39:49 PM: BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
6:39:49 PM: 	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
6:39:49 PM: 	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.

```
you can look at the log [here](https://app.netlify.com/sites/gatsby-starter-i18n-bulma/deploys/60465fe8401c380007c56e4c)
I will try to upgrade `webpack-assets-manifest` as suggested by @kimbaudi

**Comment by kalwalt** [comment]
@kimbaudi the solution you provided 
```
cd packages/gatsby-plugin-manifest
yarn remove webpack-assets-manifest
yarn add webpack-assets-manifest
```
doesn't work for me. First, webpack-asset-manifest is installed in `node_modules `and not in the `gatsby-plugin-netlify/node_modules`, second, because there isn't a yarn.lock file i need to run yarn install but not sure if it can work.

**Comment by joelvarty** [comment]
Same problem here in this repo https://github.com/agility/agility-website-gatsby/pull/50 

*package.json:*
"gatsby": "^3.0.4",
"gatsby-plugin-netlify": "^3.0.0",


*build error*
```
22:14:08 PM:
ERROR (node:2597) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader

22:14:19 PM:
ERROR (node:2597) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.

22:14:19 PM:
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.

22:14:19 PM:
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
```

**Comment by kimbaudi** [comment]
@kalwalt - i'm talking about updating `gatsby-plugin-netlify` dependency on `webpack-assets-manifest` from current version `3.1.1` (which is causing the error) to a more recent version. unfortunately, i'm really busy right now so I won't be making any PR for this plugin. I just disable it for now.

**Comment by kalwalt** [comment]
@kimbaudi i see my error. Watching the PR https://github.com/gatsbyjs/gatsby/pull/30217 by @pedrolamas, sound interesting, i will test this last if i can. 😃

**Comment by kimbaudi** [comment]
I don't think the PR is going to get accepted. Updating to the latest `webpack-asset-manifest` v5 caused errors during testing (`yarn jest gatsby-plugin-netlify`).

**Comment by pedrolamas** [comment]
@kimbaudi tests are passing fine for me... am I missing something here?

**Comment by talohana** [comment]
For me tests are passing locally, but when I try to build my site (after `npm link`ing) I get the following error:

> ERROR #98123  WEBPACK
>
> Generating SSR bundle failed
>
> The 'compilation' argument must be an instance of Compilation

**Comment by kimbaudi** [comment]
@pedrolamas - I just tested after upgrading `gatsby-plugin-netlify` to `"webpack-assets-manifest": "^5.0.1"` on my Windows 10 machine, and one of the tests are failing:

![not-working](https://user-images.githubusercontent.com/1864092/111073750-1c08c200-849d-11eb-8359-6e3b19ed6e8d.png)

**Comment by kimbaudi** [comment]
@pedrolamas - I tested again and the tests are passing. My mistake.

**Comment by pedrolamas** [comment]
@talohana indeed, I too am seeing the same error from `yarn link`ing... Back to the drawing board I guess... 😕

**Comment by pedrolamas** [comment]
@talohana I now know what is the problem and that is with how `yarn link` (and probably `npm link`) work, not with the upgrade per si...

I noticed that even after updating the "webpack-assets-manifest" dependency and linking the file to the main project, it was still using the wrong version of the dependency as the `link` process doesn't actually update the dependencies, it just points to the folder contents.

In my case, using [yalc](https://github.com/wclr/yalc) to do the linking and local tests did the trick and I now see the build passing without any errors.

![image](https://user-images.githubusercontent.com/85504/111164722-3d99a480-8596-11eb-9d27-1ad341f4bf85.png)

As such, and unless someone finds any other problem, I consider the PR worth to merge as it is right  now!

**Comment by pieh** [comment]
I'm on the PR review right now, just trying to get to the bottom of failing type check there, but from manual testing it seemed to be working just all right

**Comment by pieh** [comment]
For folks that want workaround right now - if you use `yarn` you can add:
```
"resolutions": {
  "webpack-assets-manifest": "5.0.1"
}
```
to your package.json to force yarn to install that instead of what plugin has specified right now (unfortunaly there is no reliable equivalent workaround in npm)

**Comment by dsebastien** [comment]
I've tried the above workaround without success, unfortunately.

**Comment by panzacoder** [comment]
After much upgrading and cleaning, this worked for me: 
https://github.com/gatsbyjs/gatsby/issues/33969#issuecomment-969943605
