### ISSUE TITLE
OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by shtelzerartem** [gatsbyjs/gatsby#29993]
## Description

After migration to Gatsby 3, I'm experiencing this deprecation warning, but cannot find, which module is causing it.

```markdown
verbose Transition to "runningQueries" > "calculatingDirtyQueries"
verbose Transition to "runningQueries" > "runningStaticQueries"
verbose Transition to "runningQueries" > "runningPageQueries"

 ERROR 

(node:28688) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

success run page queries - 0.867s - 2/2 2.31/s
verbose Transition to "runningQueries" > "waitingForJobs"
verbose Transition to "runningQueries" > "done"
verbose Transition to "startingDevServers"
```

### Environment

```
  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.1 - /c/Users/Artem Shteltser/AppData/Local/Programs/Python/Python39/python
  Browsers:
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gatsby: ^3.0.1 => 3.0.1
    gatsby-plugin-emotion: ^6.0.0 => 6.0.0
    gatsby-plugin-env-variables: ^2.0.0 => 2.0.0
    gatsby-plugin-eslint: ^3.0.0 => 3.0.0
    gatsby-plugin-google-fonts-v2: ^0.0.6 => 0.0.6
    gatsby-plugin-image: ^1.0.0 => 1.0.0
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0
    gatsby-plugin-module-resolver: ^1.0.3 => 1.0.3
    gatsby-plugin-offline: ^4.0.0 => 4.0.0
    gatsby-plugin-portal: ^1.0.7 => 1.0.7
    gatsby-plugin-postcss: ^4.0.0 => 4.0.0
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0
    gatsby-plugin-sitemap: ^3.0.0 => 3.0.0
    gatsby-source-filesystem: ^3.0.0 => 3.0.0
    gatsby-source-graphql: ^3.0.0 => 3.0.0
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0
```

**Comment by shtelzerartem** [comment]
Probably, similar issue as described here #25427 but on v3.

**Comment by pieh** [comment]
`NODE_OPTIONS=--trace-deprecation gatsby develop` should print stack trace that should help narrowing it down

**Comment by shtelzerartem** [comment]
@pieh here is the full log:

```
 ERROR 

(node:22460) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
    at module.exports (C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\timed-out\index.js:9:17)  
    at EventEmitter.<anonymous>
(C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\got\index.js:244:5)
    at Object.onceWrapper (events.js:300:26)
    at EventEmitter.emit (events.js:210:5)
    at makeRequest
(C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\cacheable-request\src\index.js:94:9)
    at C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\cacheable-request\src\index.js:104:14     
    at runNextTicks (internal/process/task_queues.js:58:5)
    at processImmediate (internal/timers.js:412:9)
```

**Comment by creotip** [comment]
Have the same errors

**Comment by wardpeet** [comment]
@shtelzerartem `yarn why timed-out` should give you the package that uses timed-out, that's the culprit.

**Comment by itsmeow** [comment]
```
yarn why v1.22.4
[1/4] Why do we have the module "timed-out"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "timed-out@4.0.1"
info Reasons this module exists
   - "got" depends on it
   - Hoisted from "got#timed-out"
   - Hoisted from "gatsby-plugin-sharp#imagemin-mozjpeg#mozjpeg#bin-build#download#got#timed-out"
info Disk size without dependencies: "16KB"
info Disk size with unique dependencies: "16KB"
info Disk size with transitive dependencies: "16KB"
info Number of shared dependencies: 0
Done in 0.88s.
```

**Comment by itsmeow** [comment]
```
npm list timed-out
itsmeow.dev@1.0.0 C:\Users\itsmeow\Desktop\Development\js\itsmeow.dev
+-- UNMET DEPENDENCY gatsby@3.0.3
| `-- UNMET DEPENDENCY got@8.3.2
|   `-- UNMET DEPENDENCY timed-out@4.0.1
`-- UNMET DEPENDENCY gatsby-plugin-sharp@3.0.0
  `-- UNMET DEPENDENCY imagemin-mozjpeg@9.0.0
    `-- UNMET DEPENDENCY mozjpeg@7.0.0
      `-- UNMET DEPENDENCY bin-build@3.0.0
        `-- UNMET DEPENDENCY download@6.2.5
          `-- UNMET DEPENDENCY got@7.1.0
            `-- UNMET DEPENDENCY timed-out@4.0.1
```
Looks like old `got` versions, `timed-out` has been removed in newer versions of `got`. Not sure how this could be solved. This only started happening after I added some remote file nodes for sharp [as shown in this guide](https://www.gatsbyjs.com/docs/how-to/images-and-media/preprocessing-external-images/).

**Comment by shtelzerartem** [comment]
@wardpeet I have the same outputs as @itsmeow 
So yeah, it's related to **got**.

**Comment by shtelzerartem** [comment]
@wardpeet  @pieh any comments on this issue?

**Comment by Daviidxo** [comment]
As a workaround I did the following:

1. `yarn upgrade`
2. `yarn add gatsby-plugin-sharp@3.1.0`
3. `yarn add gatsby-source-filesystem@3.0.0`

Until this issue is fixed I locked this two plugin's version and now the error disappeared.

**Comment by shaurov** [comment]
**having the same issue here...!**

```
Fetching Google Sheet [Function] 1ZGdsv0kXpAZQB0XM4APP9WX0iQUYqEq3Wjjp8fXnko8

 ERROR

(node:17740) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
```

**i have also tried with migrated to...**

```
  "gatsby-plugin-manifest": "^3.2.0",
  "gatsby-plugin-sharp": "3.1.0",
  "gatsby-source-filesystem": "3.0.0",
```

**but that doesn't work for me.**

**my gatsby-node.js file:**

```
const { createRemoteFileNode } = require(`gatsby-source-filesystem`)

exports.onCreateNode = async (
  {
    actions: { createNode },
    node,
    createContentDigest,
    store,
    cache,
    reporter,
  },
  { nodeName = `localFile` }
) => {
  if (
    node.internal.type === `googleMenuSheet` &&
    node.itemCategoryImage !== null
  ) {
    const fileNode = await createRemoteFileNode({
      url: node.itemCategoryImage,
      store,
      cache,
      createNode,
      createNodeId: createContentDigest,
      reporter,
    })

    if (fileNode) {
      const fileNodeLink = `${nodeName}___NODE`
      node[fileNodeLink] = fileNode.id
    }
  }
}

```

**Comment by adrianopulz** [comment]
The same issue here. The gatsby-plugin-sharp > Got > Time-Out is using the **_headers** deprecated method. The @Daviidxo solution is working for me until having a better solution.

**Comment by shaurov** [comment]
@KyleAMathews have some comments about this issue. thank you

**Comment by shaurov** [comment]
**dear friends, raising the version of got solves the issue for me.**

`yarn add got@latest`

**thanks to this blog...**
https://kikunantoka.com/2021/03/15--migrate-from-gatsby-v2-to-gatsby-v3/

**Comment by shaurov** [comment]
**dear friends, raising the version of got solves the issue for me.**

`yarn add got@latest`

**thanks to this blog...**
https://kikunantoka.com/2021/03/15--migrate-from-gatsby-v2-to-gatsby-v3/

**Comment by sallakos** [comment]
This issue still persists with everything up to date.

**Comment by LinnJS** [comment]
Getting the same error when upgraded 

![image](https://user-images.githubusercontent.com/23741323/122827695-afc70700-d2b2-11eb-9fdd-7e60795a4b78.png)

**Comment by spiraljacobs** [comment]
Also getting this issue.  Still showing up with latest versions of everything.

**Comment by Minneanimal** [comment]
I ran into this issue while following the Gatsby v3 tutorial. Installing the latest got package also resolved the issue for me.

**Comment by ThomasLaukkanen** [comment]
> **dear friends, raising the version of got solves the issue for me.**
> 
> `yarn add got@latest`
> 
> **thanks to this blog...**
> https://kikunantoka.com/2021/03/15--migrate-from-gatsby-v2-to-gatsby-v3/

This worked for me with this error: [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
 **Thank you so much!**

**Comment by Vacilando** [comment]
`npm install got@latest` indeed fixes the problem but it's not a clean solution. 
"got" has to be upgraded in the plugin where it is defined as dependency.

**Comment by jackzhujie** [comment]
> `NODE_OPTIONS=--trace-deprecation gatsby develop` should print stack trace that should help narrowing it down

i add the Environment variable in run app after, the error show in log4js  package.
