### ISSUE TITLE
In development mode page loads styles not related to current page

### ISSUE THREAD

**Issue by llamerr** [gatsbyjs/gatsby#30004]
## Description

I have "theme.scss" style which contains some color, grid sizes and other common styles. I do `@import "theme"` from other components I use those grid vars in, so I load theme in every component scss file. After page is loaded, I see in component styles, that it duplicates global styles from all other pages that load it. Since it does not reproduce on build, I suppose that's a bug?

![localhost:8000:404: 2021-03-04 18-35-50](https://user-images.githubusercontent.com/1281970/109997624-0d8e0e00-7d19-11eb-8f89-ac234d0880ab.png)
<img width="1309" alt="localhost:9000:404: 2021-03-04 18-35-12" src="https://user-images.githubusercontent.com/1281970/109997635-11ba2b80-7d19-11eb-91e1-3f8a5ceb0ad6.png">

On real project it lead to something like this:
<img width="283" alt="localhost:8000:404: 2021-03-04 18-47-09" src="https://user-images.githubusercontent.com/1281970/109999093-8a6db780-7d1a-11eb-9450-841e4e180429.png">

After thinking on it - maybe I'm doing something wrong, since **after I moved everything into separate files, which only have sass variables and not generated styles, all duplication disappeared**, but since results in development and production modes are different I'm not sure.

### Steps to reproduce

https://github.com/llamerr/gatsby-bug

### Expected result

Only show styles related to current page

### Actual result

Showing styles related to all pages

### Environment

➜  gatsby-bug git:(main) ✗ gatsby info --clipboard

  System:
    OS: macOS 11.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.0 - ~/.nvm/versions/node/v14.15.3/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 88.0.4324.192
    Firefox: 86.0
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.0.1 => 3.0.1
    gatsby-plugin-sass: ^4.0.0 => 4.0.0
  npmGlobalPackages:
    gatsby-cli: 3.0.0

**Comment by llamerr** [comment]
Also I think this started to appear only recently, like in last 3 weeks (noticed that after I switched back to project I was not working on and did `npm i` again? though I tried to reproduce on older commits with `npm ci` and it still was happening)

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

Are you only seeing this on `gatsby@3` and `gatsby-plugin-sass@4` or also `gatsby@2` and `gatsby-plugin-sass@3`?

Can you also please clarify this paragraph?

> After thinking on it - maybe I'm doing something wrong, since after I moved everything into separate files, which only have sass variables and not generated styles, all duplication disappeared, but since results in development and production modes are different I'm not sure.

For normal CSS files we don't do split-chunking for CSS and load all CSS on all pages.

**Comment by llamerr** [comment]
> Hi, thanks for the issue!
> 
> Are you only seeing this on `gatsby@3` and `gatsby-plugin-sass@4` or also `gatsby@2` and `gatsby-plugin-sass@3`?

Yes, it also happens on older versions, I first discovered it on gatsby ~2.29.3 and gatsby-plugin-sass ~2.8.0, then tried to upgrade.
 
> Can you also please clarify this paragraph?
> 
> > After thinking on it - maybe I'm doing something wrong, since after I moved everything into separate files, which only have sass variables and not generated styles, all duplication disappeared, but since results in development and production modes are different I'm not sure.
> 
> For normal CSS files we don't do split-chunking for CSS and load all CSS on all pages.

I mean that when I do import of local styles, only used styles are imported (at least I think so?), and unused are not imported, but for my case I was generating css which probably was treated as global css, so maybe that's the problem?

> So far I onily saw same styles repeating - does the difference ever result in not consistent actual styling?

Well, it does not, but future development was literally impossible - it took chrome 4 seconds or so to show node styles after I switched nodes in elements panel, and when I tried to track some styles I needed to scroll down pages of same style repeated, so it was actually easier to find and fix the problem than ignoring the issue

**Comment by llamerr** [comment]
Still an issue afaik

ср, 31 мар. 2021 г., 3:05 github-actions[bot] ***@***.***>:
