### ISSUE TITLE
hot reload not working for lowercased components (Gatsby 3)

### ISSUE THREAD

**Issue by fczuardi** [gatsbyjs/gatsby#30008]
Not sure if this is a duplicate of https://github.com/gatsbyjs/gatsby/issues/29952 or not, but it is very reproducible on Ubuntu 20.04 and Chrome.

#### Steps to reproduce:

- with node v14.16.0 and yarn 1.22.10 install gatsby-cli globally
  -  `yarn global add gatsby-cli@latest`
- create a blank gatsby project using the hellow-world starter
  - `gatsby new my-hello-world-starter https://github.com/gatsbyjs/gatsby-starter-hello-world`
- enter the src/pages folder and create a second page
  - `cd my-hello-world-starter/src/pages && cp index.js foo.js`
- start the development server
  - `cd ../..` `gatsby develop`
- open `http://localhost:8000/foo` on the web browser (Chromium 89.0.4389)
- edit the `src/pages/foo.js` page changing the text and save the file

#### Expected result:

The page rebuild and the web browser updates to display the new text.

#### Actual result:
 
The same unedited text is displayed

For the `/src/pages/index.js` the changes are reflected as expected.

**Comment by fczuardi** [comment]
on further testing, we could reproduce less the issue when the `export default function` is named with a word starting with capital letter....

**Comment by pieh** [comment]
> on further testing, we could reproduce less the issue when the export default function is named with a word starting with capital letter....

Ah, right - this is related to https://github.com/facebook/react/issues/17142 . We will see if we can implement some kind of warning for this (we already do have warning when export is unnamed or when there are multiple exports, but seems like we do miss case when component is named but doesn't start with capital letter.
