### ISSUE TITLE
Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by Rirg94** [gatsbyjs/gatsby#30030]
## Description

When I run `gatsby-develop` the following error shows up using `gatsby-plugin-image`:

![CleanShot 2021-03-05 at 13 51 21@2x](https://user-images.githubusercontent.com/41655800/110105830-ed625b80-7db9-11eb-8b84-77d573c01ac0.jpg)

### Steps to reproduce

Use the plugin with `gatsby-source-wordpress` and query images like :
`localFile {
      childImageSharp {
           gatsbyImageData(layout: FULL_WIDTH)
      }
    }`
    
How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result
It should build correctly.

### Actual result
`gatsby build` doesn't run, `gatsby develop` throws the error but at least runs and I can see the page.

### Environment
![image](https://user-images.githubusercontent.com/41655800/110106303-94df8e00-7dba-11eb-8d76-6f79c683f702.png)

**Comment by LekoArts** [comment]
Thank you for opening this!

`gatsby-source-wordpress` currently doesn't support the new `gatsby-plugin-image` yet. Please use the old `gatsby-image` for now!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by Rirg94** [comment]
Hey @LekoArts . Thanks for the info! I didn't know that, and the error was actually using a variable for `<StaticImage />`. Once I removed it, it worked just fine, so looks like `gatsby-source-wordpress` works with `gatsby-plugin-image`. Is there a reason why it shouldn't? 
You can check the website where I'm using it -> dev.weareshellshock.com

Thanks!

**Comment by LekoArts** [comment]
Ah, I was referring to a potential use of CDN images from WordPress. But using `localFile` is working, yeah. Glad you were able to solve it!
