### ISSUE TITLE
[Gatsby v3] CSS Modules - Default exports from dependency lib cause broken build

### ISSUE THREAD

**Issue by rogervera** [gatsbyjs/gatsby#30040]
## Description

1. **Spike**: Following the migration build, I'm certain this is caused from [css-modules-are-imported-as-es-modules](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#css-modules-are-imported-as-es-modules).

2. **Problem**: When importing from an external component lib that uses default exports for `scss`, we see the warning
```javascript
warn Attempted import error: './styles/FormError.module.scss' does not contain a default export (imported as 'styles').
```

3. **Question**: **Do we have to wait until our libs that are using default exports like** [`import styles from './styles.module.scss';`](https://github.com/Codecademy/client-modules/blob/546c453575b41c4891e0781a217a05f381f25aac/packages/gamut/src/SkipToContent/index.tsx#L5) **are updated to use** `named export`**, or is there a work around until then?**

### Steps to reproduce
1. Clone https://github.com/rogervera/gatsby-v3-default-export-bug-repro
2. `gatsby develop`
3. See errors on root page.

### Expected result

Auto resolve any runtime errors on `import errors` from dependency packages? 
Not sure what is possible or ideal...

### Actual result

<img width="350" alt="Screen Shot 2021-03-04 at 5 17 13 PM" src="https://user-images.githubusercontent.com/17210163/110128748-2805cd00-7d95-11eb-96d2-4669f17f03e3.png">

### Bug Repro Env
```
  System:
    OS: macOS 11.2.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.16.0 - ~/.nvm/versions/node/v12.16.0/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 88.0.4324.192
    Firefox: 86.0
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.0.1 => 3.0.2
    gatsby-plugin-sass: ^4.0.1 => 4.0.1
  npmGlobalPackages:
    gatsby: 3.0.2
```

## Actual Env
```
  System:
    OS: macOS 11.2.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.16.0 - ~/.nvm/versions/node/v12.16.0/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 88.0.4324.192
    Firefox: 86.0
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.0.0 => 3.0.1
    gatsby-image: ^2.2.34 => 2.11.0
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5
    gatsby-plugin-asset-path: ^3.0.3 => 3.0.3
    gatsby-plugin-canonical-urls: ^3.0.0 => 3.0.0
    gatsby-plugin-emotion: ^6.0.0 => 6.0.0
    gatsby-plugin-newrelic: ^1.0.3 => 1.0.5
    gatsby-plugin-offline: ^4.0.0 => 4.0.0
    gatsby-plugin-postcss: ^4.0.0 => 4.0.0
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0
    gatsby-plugin-resolve-src: ^2.1.0 => 2.1.0
    gatsby-plugin-sass: ^4.0.0 => 4.0.0
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0
    gatsby-plugin-sitemap: ^3.0.0 => 3.0.0
    gatsby-plugin-tsconfig-paths: ^1.0.2 => 1.0.2
    gatsby-plugin-tslint: 0.0.2 => 0.0.2
    gatsby-plugin-typescript: ^3.0.0 => 3.0.0
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-contentful: ^5.0.0 => 5.0.0
    gatsby-source-filesystem: ^3.0.0 => 3.0.0
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0
  npmGlobalPackages:
    gatsby: 3.0.2
```

**Comment by danielthelobster** [comment]
We are seeing the same issue over here today. I think reverting to v3.0.0 is a temporary fix for us.

**Comment by alexgonch** [comment]
Running into the same problem. Downgrading gatsby to v3.0.0 does not solve it for us.
