### ISSUE TITLE
Gatsby ^3.0 doesn't display correct compilation error

### ISSUE THREAD

**Issue by anisg** [gatsbyjs/gatsby#30046]
### Steps to reproduce

- create a new gatsby project ^3.0
- add `throw "ERROR";` at index.js page (outside react components, just after imports for instance)

### Expected result

Gatsby should display the error message `"ERROR"` and locate the line in the code

### Actual result

Gatsby displays the following error:
`Error in function EnsureResources.render in ./.cache/ensure-resources.js:86`

### Environment

  System:
    OS: macOS 11.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.8.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.72
    Edge: 89.0.774.45
    Safari: 14.0.3
  npmPackages:
    gatsby: 3.0.0 => 3.0.0
    gatsby-plugin-crisp-chat: ^3.2.2 => 3.2.2
    gatsby-plugin-google-analytics: ^3.0.0 => 3.0.0
    gatsby-plugin-gtag: ^1.0.13 => 1.0.13
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0
    gatsby-plugin-material-ui: ^2.1.10 => 2.1.10
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0
    gatsby-plugin-webpack-size: ^1.0.0 => 1.0.0
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0

**Comment by bradlocking** [comment]
Got the same issue here with a few client only paths which were otherwise fully functional on v2 before the upgrade. 

What's also interesting is that these pages cannot be routed directly, and the page refreshes before attempting to load the content, when I am then faced with the same EnsureResources.render error.

**Comment by shennan** [comment]
I'm also getting the same error here and not quite sure where to start in debugging. I've reproduced the error in this repository:

https://github.com/shennan/repro-gatsby-ensure-resources-error

The repository is attempting to use [Redoc](https://github.com/Redocly/redoc), which is causing the error. But it's impossible to locate the source of the issue. This issue does not occur in Gatsby 2.X.

As you can see it's a pretty unhelpful error:

<img width="885" alt="Screenshot 2021-03-08 at 10 38 08" src="https://user-images.githubusercontent.com/1840398/110310419-6fd95e00-7ffa-11eb-8dae-805c97730b09.png">

Have attempted a `gatsby clean` as per suggestion and no dice.

**Comment by jamespfarrell** [comment]
Same here, this is driving me crazy, there's something seriously wrong here

**Comment by bradlocking** [comment]
> Same here, this is driving me crazy, there's something seriously wrong here. Back to Gatsby 2, and start reading about NextJS.

@jamespfarrell - There's a fix in flight at the moment, which looks promising. Don't give up hope just yet
