### ISSUE TITLE
gatsby-plugin-image presentation width/height missed in markup

### ISSUE THREAD

**Issue by luciobenini** [gatsbyjs/gatsby#30054]
## Description

From lighthouse report:

> Image elements do not have explicit width and height
> Set an explicit width and height on image elements to reduce layout shifts and improve CLS.

### Steps to reproduce

I'm using **GatsbyImage** compontent.

### Expected result

`<img alt="" role="presentation" aria-hidden="true" height="440" width="640" src="data:image/svg+xml;charset=utf-8,%3Csvg height='440' width='640' xmlns='http://www.w3.org/2000/svg' version='1.1'%3E%3C/svg%3E" style="max-width: 100%; display: block; position: static;">`

### Actual result

`<img alt="" role="presentation" aria-hidden="true" src="data:image/svg+xml;charset=utf-8,%3Csvg height='440' width='640' xmlns='http://www.w3.org/2000/svg' version='1.1'%3E%3C/svg%3E" style="max-width: 100%; display: block; position: static;">`

### Environment

>   System:
>     OS: Windows 10 10.0.19042
>     CPU: (8) x64 Intel(R) Xeon(R) W-2225 CPU @ 4.10GHz
>   Binaries:
>     Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
>     Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
>     npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
>   Browsers:
>     Chrome: 88.0.4324.190
>     Edge: Spartan (44.19041.423.0), Chromium (89.0.774.45)
>   npmPackages:
>     gatsby: ^3.0.3 => 3.0.3
>     gatsby-plugin-emotion: ^6.0.0 => 6.0.0
>     gatsby-plugin-feed: ^3.0.0 => 3.0.0
>     gatsby-plugin-gdpr-cookies: ^1.0.14 => 1.0.14
>     gatsby-plugin-image: ^1.0.0 => 1.0.0
>     gatsby-plugin-manifest: ^3.0.0 => 3.0.0
>     gatsby-plugin-mdx: ^2.0.0 => 2.0.0
>     gatsby-plugin-page-progress: ^2.1.1 => 2.1.1
>     gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0
>     gatsby-plugin-sass: ^4.0.2 => 4.0.2
>     gatsby-plugin-sharp: ^3.0.0 => 3.0.0
>     gatsby-plugin-sitemap: ^3.0.0 => 3.0.0
>     gatsby-source-graphcms: ^2.3.0 => 2.3.0
>     gatsby-transformer-sharp: ^3.0.0 => 3.0.0
>   npmGlobalPackages:
>     gatsby-cli: 3.0.0

**Comment by ascorbic** [comment]
Hi. That's not the image you can see. It's an SVG used to preserve aspect ratio, and is sized with CSS. Despite the warning, it has no effect on CLS or Lighthouse score.
