### ISSUE TITLE
Graph queries do not work from components with Dynamic Parameter

### ISSUE THREAD

**Issue by creativegeniusod** [gatsbyjs/gatsby#3005]
I’m trying to run a `GraphQL` query with variables, this works fine in the query editor (`/___graphql`), but I'm unable to get this working outside a `pageQuery`.

The intention of the query is to lookup pages bases on the arguments of a function (so not to create the actual page, but to feed a section of the page), to create for example dynamic menu’s such a for a footer section.

I’m able to run this query with static values but when I replace the static values with a variable as in the query below the query fails. 

```
query FooterQuery($menu: String!, $tag: String!, $limit: Int!) {
  allMarkdownRemark(filter: {frontmatter: {menu: {in: [$menu]}, tags: {in: [$tag]}}}, sort: {fields: [frontmatter___weight], order: ASC}, limit: $limit) {
    edges {
      node {
        excerpt
        fields {
          slug
          langKey
        }
        frontmatter {
          title
        }
      }
    }
  }
}
```

I the main question is how to set variables for a query outside context of a page.

**Comment by KyleAMathews** [comment]
Check out `<StaticQuery>` in v2!

**Comment by jackbravo** [comment]
In the [docs](https://www.gatsbyjs.org/docs/static-query/#how-staticquery-differs-from-page-query) it says `StaticQuery does not accept variables (hence the name “static”), but can be used in any component, including pages.` So the question remains on how to set variables for a query outside the context of a page. Or am I missing something?
