### ISSUE TITLE
plugin directory is showing removed npm packages

### ISSUE THREAD

**Issue by moonmeister** [gatsbyjs/gatsby#30058]
`gatsby-plugin-ackee` was published to NPM by mistake and replaced by `gatsby-plugin-ackee-tracker`. `gatsby-plugin-ackee` is no longer available on NPM but some how still being published into the gatsby plugin directory @ https://www.gatsbyjs.com/plugins/gatsby-plugin-ackee. 

The original issue is here https://github.com/Burnsy/gatsby-plugin-ackee-tracker/issues/69 for this package. I wouldn't be surprised if this wasn't the only case of this happening.

**Comment by LekoArts** [comment]
Hi, thanks for the issue! We're depending on Algolia's npm search there, so it's out of our control. See: https://github.com/algolia/npm-search/issues/556

I've created https://github.com/algolia/npm-search/issues/586 to track this :)
