### ISSUE TITLE
gatsby-plugin-preact with Gatsby 3 incorrectly renders "<meta http-equiv>"

### ISSUE THREAD

**Issue by Eyas** [gatsbyjs/gatsby#30064]
## Description

Gatsby 2 (with and without preact), and Gatsby 3 (without preact) all correctly generate:

```html
<meta http-equiv="x-ua-compatible" content="ie=edge">
```

in the head, but Gatsby 3 with Preact (and preact plugin 5.0) instead generate:

```html
<meta httpequiv="x-ua-compatible" content="ie=edge">
```

note `httpequiv` instead of `http-equiv`.

### Steps to reproduce

Minimal repro:

1. `npm init gatsby` with basic settings
2. `npm install gatsby-plugin-preact preact preact-render-to-string`
3. Add `"gatsby-plugin-preact"` to gatsby-config.js

### Expected result

Continue to see `<meta http-equiv` in head.

### Actual result

Output changes to `<meta httpequiv` instead.

### Environment
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (20) x64 Intel(R) Core(TM) i9-10900KF CPU @ 3.70GHz
  Binaries:
    Node: 15.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.6.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.0
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.45)
  npmPackages:
    gatsby: ^3.0.1 => 3.0.3 
    gatsby-plugin-google-analytics: ^3.0.0 => 3.0.0 
    gatsby-plugin-image: ^1.0.0 => 1.0.0 
    gatsby-plugin-mdx: ^2.0.0 => 2.0.0 
    gatsby-plugin-preact: ^5.0.0 => 5.0.0 
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0 
    gatsby-plugin-sass: ^4.0.2 => 4.0.2 
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0 
    gatsby-plugin-sitemap: ^3.0.0 => 3.0.0 
    gatsby-source-filesystem: ^3.0.0 => 3.0.0 
    gatsby-transformer-remark: ^3.0.0 => 3.0.0 
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0 
  npmGlobalPackages:
    gatsby-cli: 3.0.0
```

But this happens on netlify as well.

**Comment by Eyas** [comment]
Minimal repro: https://github.com/Eyas/gatsby-3-preact-bug-minimal-repro

**Comment by Eyas** [comment]
FWIW this breaks AMP validation on Gatsby v3 preact sites (AMP requires only known tags to be set on `meta`, and `httpequiv` is invalid (only `http-equiv` is valid).

**Comment by Eyas** [comment]
Tagging @wardpeet as the resident preact expert, do you know what's going on?

**Comment by wardpeet** [comment]
Sorry, I'm pretty sure it's a preact bug, let me have a look.

**Comment by hexyas** [comment]
I'm running into this as well. The W3C HTML validator doesn't like the `httpEquiv` attribute:

![Screen Shot 2021-04-08 at 2 40 23 AM](https://user-images.githubusercontent.com/49214777/114004716-cad9bd00-9813-11eb-92bc-ee3e96e72283.png)
`Error: Attribute httpequiv not allowed on element meta at this point.`

Looking at https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/default-html.js, `httpEquiv` is hardcoded into the base file. The file must go through more processing during build because without the Preact plugin, it correctly becomes `http-equiv` in the `default-html.js` in the `.cache` folder.

I'm curious to know what the reason to hardcode `httpEquiv` instead of `http-equiv` is. Perhaps changing that is one way to solve this. That said, it's also worth exploring why the Preact plugin interferes with the build process of `default-html.js`.

**Comment by hexyas** [comment]
If anyone needs a workaround, follow https://www.gatsbyjs.com/docs/custom-html/ to change the `<head>` in your custom `html.js`. Hopefully we'll get a fix soon since the docs recommended to avoid changing that file.

**Comment by LekoArts** [comment]
React expects the DOM elements in PascalCase so the default-html.js file is correct: https://reactjs.org/docs/dom-elements.html#all-supported-html-attributes

So changing that is not the correct way to solve it but as @wardpeet said it's most probably a bug in Preact.

**Comment by marciolima-praycom** [comment]
Any updates on this issue? It doesn't happen with previous versions of Gatsby/plugin/preact.

**Comment by davidgallego** [comment]
Also happens with svg tag namespace properties, for example xmlnsXlink is rendered as xmlnsxlink instead of xmlns:xlink.

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
