### ISSUE TITLE
querystring with dots returns 404 on develop mode

### ISSUE THREAD

**Issue by eladams** [gatsbyjs/gatsby#3008]
Running `gatsby develop` and trying to access: 
`http://localhost:8000/select-location?lat=31.4217965&lng=34.59296380000001`
returns 404.
removing the querystring dots (`.`) loads the page.
any thoughts?
BTW opening this href by clicking a gatsby-link works.

**Comment by calcsam** [comment]
Discussed at https://github.com/gatsbyjs/gatsby/issues/1655
