### ISSUE TITLE
[gatsby-plugin-image] Blurred placeholder does not respect attention cropping

### ISSUE THREAD

**Issue by maximeg** [gatsbyjs/gatsby#30096]
## Description

I have a static image:

```
<StaticImage
  alt="My alt"
  aspectRatio={360 / 288}
  formats={["auto", "webp", "avif"]}
  layout="constrained"
  width={640}
  placeholder="blurred"
  src="./my-image.jpg"
/>
```

having, by default, `transformOptions={{fit: "cover", cropFocus: "attention"}}`.

The generated blurred placeholder image does not have the same cropping as the final image.

One can see that the wheel is not as the same place.
![image](https://user-images.githubusercontent.com/252162/110314452-23951a80-8008-11eb-9e5a-0d893d79b0a6.png)
![image](https://user-images.githubusercontent.com/252162/110314485-314aa000-8008-11eb-80a2-f20afbdf0beb.png)

I tried the entropy, but it leads to a different cropping for the final image, and the placeholder one's is still not the same.

### Steps to reproduce

Take this picture: 
![image](https://user-images.githubusercontent.com/252162/110314680-766ed200-8008-11eb-90a3-bbcfde490d37.png)

Use it with a small size and an aspect ratio of `1` to emphasize the issue:

```
<StaticImage
  alt="My alt"
  aspectRatio={1}
  layout="constrained"
  width={300}
  placeholder="blurred"
  src="./my-image.jpg"
  transformOptions={{fit: "cover", cropFocus: "attention"}}
/>
```
### Expected result

Wheel should be aligned ;)

The plugin should apply the cropping, then generate the placeholder (wheither it's blurred, traced svg...)

### Actual result

Wheel are not aligned.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here:

```
 System:
    OS: macOS 11.2.1
    CPU: (8) arm64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.11.0 - /var/folders/fc/fqf9t2nn1wb4fy216v7jkdyw0000gn/T/yarn--1615202496627-0.34340404333252783/node
    Yarn: 1.22.10 - /var/folders/fc/fqf9t2nn1wb4fy216v7jkdyw0000gn/T/yarn--1615202496627-0.34340404333252783/yarn
    npm: 7.6.0 - /opt/homebrew/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 88.0.4324.192
    Safari: 14.0.3
  npmPackages:
    gatsby: 3.0.3 => 3.0.3
    gatsby-plugin-canonical-urls: 3.0.0 => 3.0.0
    gatsby-plugin-catch-links: 3.0.0 => 3.0.0
    gatsby-plugin-eslint: 3.0.0 => 3.0.0
    gatsby-plugin-image: 1.0.0 => 1.0.0
    gatsby-plugin-react-helmet: 4.0.0 => 4.0.0
    gatsby-plugin-react-svg: 3.0.0 => 3.0.0
    gatsby-plugin-sass: 4.0.2 => 4.0.2
    gatsby-plugin-sharp: 3.0.0 => 3.0.0
    gatsby-plugin-sitemap: 3.0.0 => 3.0.0
    gatsby-plugin-typescript: 3.0.0 => 3.0.0
    gatsby-source-filesystem: 3.0.0 => 3.0.0
    gatsby-transformer-remark: 3.0.0 => 3.0.0
    gatsby-transformer-sharp: 3.0.0 => 3.0.0
```

Tell me if I can be of any help.

**Comment by marcelscruz** [comment]
It may be caused by the issue mentioned above: my final images are also not being centred as they used to be.

previous, using `gatsby-image`
<img src="https://user-images.githubusercontent.com/12413903/110329147-ff7f0c80-7ffa-11eb-85a6-63875e949aef.png" width="300px" />

current, using `gatsby-plugin-image`
<img src="https://user-images.githubusercontent.com/12413903/110329396-4a008900-7ffb-11eb-978f-bd247b7fe98e.png" width="300px" />

Also, the outer `div` has an extra spacing on the bottom (visible with the red background I added), which I don't seem to understand the cause nor get rid of. Obs: the white spacing on the right side belongs to the image itself.

`object-position: center;` and `object-fit: cover;` are properly applied.

**Comment by ascorbic** [comment]
This seems to be happening because running the attention algorithm on the 20px image yields a different result from the larger image. The way around this would be to use the main output image as the source for the placeholder, rather than the input image as we do now.

@marcelscruz That is a different issue

**Comment by Oliweer** [comment]
@ascorbic 
Changing the resolution from the default 20px doesn't seem to work at all.
`blurredOptions={{ width: 200 }}`

**Comment by lezan** [comment]
> 
> Also, the outer `div` has an extra spacing on the bottom (visible with the red background I added), which I don't seem to understand the cause nor get rid of. Obs: the white spacing on the right side belongs to the image itself.
> 

I am experience the same issue and to get rid of it (as workaround) I removed `inline-block` from `.gatsby-image-wrapper-constrained`, but I am looking for a solution. Did you already flag it somewhere?

> 
> @marcelscruz That is a different issue
>

Is it reported somewhere?

Thanks!

**Comment by marcelscruz** [comment]
@lezan 

No, I didn't find any solution nor any mention of it anywhere. For the time being, I'm keeping the legacy `gatsby-image` plugin in place.

**Comment by ascorbic** [comment]
Can you open a separate issue for the padding problem, as it's unrelated to this.

**Comment by maximeg** [comment]
Not stale :)

**Comment by F1ow** [comment]
Facing the same issue when using `<GatsbyImage image={image} objectFit="contain" />`. It seems that `object-fit: contain;` is not applied to the placeholder image.

https://github.com/F1ow/gatsby-plugin-image-object-fit-issue

**Comment by ascorbic** [comment]
@F1ow Could you open a deparate issue for that please

**Comment by F1ow** [comment]
#30841

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
