### ISSUE TITLE
TimeoutError: Timeout awaiting 'request' for 30000ms

### ISSUE THREAD

**Issue by ramojej** [gatsbyjs/gatsby#30121]
## Description

After upgrading to Gatsby v3, gatsby-source-wordpress v5, and all other dependencies that need upgrading I'm now always having this error when downloading media item. It's always a different media every time. 

### Steps to reproduce

Clone the gatsby-starter-default theme and download latest version of gatsby-source-wordpress.

You can clone this repo for minimal reproduction: https://github.com/ramojej/dilate-gatsby-wp-starter

then run gatsby-develop

### Expected result

It will run like it used to before.

### Actual result

Failing to process media items.

### Environment

  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    npm: 6.12.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.82
    Safari: 13.0.4
  npmPackages:
    gatsby: ^3.0.3 => 3.0.3 
    gatsby-background-image: ^1.3.1 => 1.3.1 
    gatsby-image: ^2.10.0 => 2.10.0 
    gatsby-omni-font-loader: ^1.3.0 => 1.3.0 
    gatsby-plugin-anchor-links: ^1.2.0 => 1.2.0 
    gatsby-plugin-apollo: ^3.0.2 => 3.0.2 
    gatsby-plugin-image: ^1.0.0 => 1.0.0 
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0 
    gatsby-plugin-offline: ^4.0.0 => 4.0.0 
    gatsby-plugin-postcss: ^4.0.0 => 4.0.0 
    gatsby-plugin-preact: ^5.0.0 => 5.0.0 
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-scroll-reveal: 0.0.7 => 0.0.7 
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0 
    gatsby-source-filesystem: ^3.0.0 => 3.0.0 
    gatsby-source-wordpress: ^5.0.0 => 5.0.0 
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0 
  npmGlobalPackages:
    gatsby-cli: 3.0.0

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

To make the process of resolving problems quicker for both sides we need you to fill out the issue template and give us a minimal reproduction:

```md
<!--
  Please fill out each section below, otherwise, your issue will be closed. This info allows Gatsby maintainers to diagnose (and fix!) your issue as quickly as possible.

  Useful Links:
  - Documentation: https://www.gatsbyjs.com/docs/
  - How to File an Issue: https://www.gatsbyjs.com/contributing/how-to-file-an-issue/

  Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
-->

## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
```

**Comment by TylerBarnes** [comment]
Hi @ramojej, I pulled down your reproduction and ran `nom I && gatsby develop` and it built fine. Can you share what kinds of errors you're running into?

**Comment by TylerBarnes** [comment]
Also can you share the output when you run `gatsby info` in the directory of the site you're having the issue with? And is this a problem locally on your machine or is it an issue that happens in your CI/build service?

**Comment by arnespremberg** [comment]
Hi @TylerBarnes I'm currently facing the same issue.
I suspect this is because I can't set the timeout time for `MediaItem`.

I have a huge WordPress backend with many large images.

See my plugin configuration here:
```
    {
      resolve: "gatsby-source-wordpress",
      options: {
        url: process.env.WPGRAPHQL_URL,
        verbose: true,
        schema: {
          timeout: 300000,
          requestConcurrency: 1,
          perPage: 10,
        },
        type: {
          MediaItem: {
            localFile: {
              // maxFileSizeBytes: 10485, // 10Mb
              requestConcurrency: 1,
            },
          },
        },
      },
    },
```

Please find my `gatsby info` log below:

```
System:
    OS: macOS 11.1
    CPU: (8) x64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.10.0 - /var/folders/ms/yl7kj4zd59s67s4grgfzwxkw0000gn/T/yarn--1616610286930-0.13927354575233508/node
    Yarn: 1.22.10 - /var/folders/ms/yl7kj4zd59s67s4grgfzwxkw0000gn/T/yarn--1616610286930-0.13927354575233508/yarn
    npm: 7.5.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 85.0.2
    Safari: 14.0.2
  npmPackages:
    gatsby: ^3.0.0 => 3.1.0
    gatsby-image: ^3.1.0 => 3.1.0
    gatsby-plugin-create-client-paths: ^3.1.0 => 3.1.0
    gatsby-plugin-google-analytics: ^3.1.0 => 3.1.0
    gatsby-plugin-google-gtag: ^3.1.0 => 3.1.0
    gatsby-plugin-google-tagmanager: ^3.1.0 => 3.1.0
    gatsby-plugin-layout: ^2.1.0 => 2.1.0
    gatsby-plugin-manifest: ^3.1.0 => 3.1.0
    gatsby-plugin-offline: ^4.1.0 => 4.1.0
    gatsby-plugin-react-helmet: ^4.1.0 => 4.1.0
    gatsby-plugin-sass: ^4.1.0 => 4.1.0
    gatsby-plugin-sharp: ^3.1.0 => 3.1.0
    gatsby-plugin-styled-components: ^4.1.0 => 4.1.0
    gatsby-plugin-transition-link: ^1.18.0 => 1.20.5
    gatsby-source-filesystem: ^3.1.0 => 3.1.0
    gatsby-source-graphql-universal: 3.4.0 => 3.4.0
    gatsby-source-wordpress: ^5.1.0 => 5.1.0
    gatsby-transformer-sharp: ^3.1.0 => 3.1.0

```

The logged error looks as follows:

```
RequestError: Timeout awaiting 'request' for 30000ms
    at ClientRequest.<anonymous> (/Users/arnespremberg/Dropbox/Websites/AHOY/code/new/frontend/node_modules/gatsby-source-wordpress/node_modules/got/dist/source/core/index.js:956:65)
    at Object.onceWrapper (node:events:485:26)
    at ClientRequest.emit (node:events:390:22)
    at ClientRequest.origin.emit (/Users/arnespremberg/Dropbox/Websites/AHOY/code/new/frontend/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at Socket.socketErrorListener (node:_http_client:462:9)
    at Socket.emit (node:events:378:20)
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
    at Timeout.timeoutHandler [as _onTimeout] (/Users/arnespremberg/Dropbox/Websites/AHOY/code/new/frontend/node_modules/gatsby-source-wordpress/node_modules/got/dist/source/core/utils/timed-out.js:36:25)
    at listOnTimeout (node:internal/timers:559:11)
    at processTimers (node:internal/timers:500:7) {
  name: 'TimeoutError',
  code: 'ETIMEDOUT',
  timings: {
    start: 1616610231977,
    socket: 1616610231977,
    lookup: 1616610231980,
    connect: 1616610232296,
    secureConnect: undefined,
    upload: 1616610232296,
    response: 1616610233145,
    end: undefined,
    error: 1616610261987,
    abort: 1616610261989,
    phases: {
      wait: 0,
      dns: 3,
      tcp: 316,
      tls: undefined,
      request: 0,
      firstByte: 849,
      download: undefined,
      total: 30012
    }
  },
  event: 'request'
}
```

I hope this helps. Really grateful for any hint how I may solve the issue.

**Comment by arnespremberg** [comment]
I can get it to load some images by limiting the maximum local file size.

**Comment by TylerBarnes** [comment]
@arnespremberg can you try updating all gatsby-* packages to see if this is still an issue? It looks like you're on an old version of gatsby-source-wordpress and a similar issue has been fixed on latest (but it requires updating all gatsby-* packages too).

**Comment by HriBB** [comment]
@TylerBarnes I am getting the same error on localhost with all the latest gatsby-* packages. Sometimes it works, but most of the time it throws a TimeoutError.

**Comment by arnespremberg** [comment]
I can confirm - still getting the error. Is there a new setting I can set somewhere?

**Comment by HriBB** [comment]
@arnespremberg try lowering `requestConcurrency` for `MediaItem > localFile`. I think it depend on your internet connection speed. 
```js
{
  resolve: `gatsby-source-wordpress`,
  options: {
    url: process.env.WPGRAPHQL_URL || `http://aokranj.local/graphql`,
    verbose: true,
    develop: {
      hardCacheMediaFiles: true,
      hardCacheData: true,
    },
    debug: {
      graphql: {
        writeQueriesToDisk: true,
      },
    },
    html: {
      useGatsbyImage: true,
      createStaticFiles: true,
      imageMaxWidth: 1024,
      fallbackImageMaxWidth: 1024,
    },
    schema: {
      perPage: 50,
      timeout: 900000,
      requestConcurrency: 5,
      previewRequestConcurrency: 2,
    },
    type: {
      __all: {
        limit: 50,
      },
      Menu: {
        limit: 9999,
      },
      MenuItem: {
        limit: 9999,
      },
      Page: {
        limit: 9999,
      },
      MediaItem: {
        localFile: {
          requestConcurrency: 15,
        },
      },
    },
  },
},
```

**Comment by arnespremberg** [comment]
Hi @HriBB thanks for the notice - in fact I had the requestConcurrency lowered to one but still was facing the issue, as there are some images as large as 20MB and the server was not really what you call performant. We moved servers and no have a perfectly stable pipeline at a requestConcurrency of 10...

**Comment by HriBB** [comment]
Playing around inside `node_modules/gatsby-source-wordpress/dist`, I can improve my development build by: 

1. Raising  the `CONNECTION_TIMEOUT` inside `steps/source-nodes/create-nodes/create-remote-file-node/index.js`

```js
const CONNECTION_TIMEOUT = 90000;
```

2. Raising the `createMediaItemNode` `fetchTimeout` inside `steps/source-nodes/fetch-nodes/fetch-referenced-media-items.js`

```js
const fetchTimeout = setTimeout(() => {
  helpers.reporter.log((0, _formatLogMessage.formatLogMessage)(`Fetching ${node.mediaItemUrl} is taking a long time time (longer than 60 seconds). This file is ${(0, _filesize.default)(node.fileSize)}`));
}, 60000);
```

Maybe we can put these into plugin options?

With all the latest `gatsby-*@next`, the development build still fails, and I have to run it multiple times, until all media files are cached.

**Comment by rroslaniec** [comment]
`gatsby-plugin-strapi` also is affected by timeouts. I temporary solved my problems by adding just env's in script, e.g.:
`    "build": "GATSBY_CONNECTION_TIMEOUT=600000 NODE_ENV=production gatsby build",`

**Comment by TylerBarnes** [comment]
@HriBB for point 2 that timeout only logs out the message there so it shouldn't effect the build much. For point 1 I definitely agree. We're planning on refactoring to use the Gatsby core createRemoteFileNode helper instead of the forked one in the WP plugin but we haven't had time to get to it just yet.

**Comment by iamkratos** [comment]
@TylerBarnes is there any update on this? Still experiencing this issue with the latest release.

It looks like it only happens with weaker host setups. Most of my WPEngine hosted WP Headless sites never experience this issue, but whenever I use a shared Bluehost WP instance, the error is inevitable. Let me know what you think

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
