### ISSUE TITLE
Creating a new gatsby site from starter hangs

### ISSUE THREAD

**Issue by kildareflare** [gatsbyjs/gatsby#3013]
Trying to create a new gatsby site:

```gatsby new layout-test```

installation hangs after this message
>info Creating new site from git: git://github.com/gatsbyjs/gatsby-starter-default.git

I've tried updating gatsby to latest (1.1.20) it was (1.1.11) and same error.

No directory or any files created.

Also tried using started other than the default, but to no avail.

I'll simply clone a repo for now.

**Comment by KyleAMathews** [comment]
All the gatsby new command does is spawn a git clone so not sure why you're having problems.

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/init-starter.js

**Comment by benjaminhoffman** [comment]
just ran it.  works great for me!
```
➜  gatsby new layout-test
2017-11-25T12:47:49-0600 <log> init-starter.js:107 (clone) Cloning git repo git://github.com/gatsbyjs/gatsby-starter-default.git to layout-test...
2017-11-25T12:47:56-0600 <log> init-starter.js:114 () Created starter directory layout
2017-11-25T12:47:56-0600 <log> init-starter.js:44 (install) Installing packages...
yarn install v1.1.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 41.30s.
```

**Comment by strix25** [comment]
I have same issue as @kildareflare :\

**Comment by KyleAMathews** [comment]
@kildareflare @strix25 try making sure you're on the latest gatsby-cli — `npm install -g gatsby-cli@latest`

**Comment by rppld** [comment]
Same. Installing all the dependencies hangs after a while after creating a new project with `$ gatsby new [projectname]`. Versions I'm using:

- gatsby-cli: 1.1.28
- Node: 9.4.0
- npm: 5.6.0

**Comment by abhinavjonnada82** [comment]
All this can be solved........... By two simple steps actually three:
1.) Open GIT BASH
2.) Type the command: gatsby new gatsby-site https://github.com/gatsbyjs/gatsby-starter-hello-world...
3.) And from your TERMINAL type gatsby develop

**Comment by BillyWM** [comment]
Had this problem on an older version months ago. Still have it on latest. (double-checked `gatsby-cli -v` that, yes, I am on 1.1.50). Once in a while it goes, but usually it hangs

Good to know it isn't doing any magic though and we can just `git clone` and `yarn install`. Not having any connectivity problems. Not sure why that is more reliable.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
