### ISSUE TITLE
gatsby-image-plugin throws EnsureResources error when using createPages API

### ISSUE THREAD

**Issue by crutchcorn** [gatsbyjs/gatsby#30147]
## Description

I run a blog that's built on top of Gatsby. Our [initial Gatsby 3 migration](https://github.com/unicorn-utterances/unicorn-utterances/pull/265) went down without too much trouble. (we're having some issues with specific images loading in build, but we're still investigating that)

However, when we went to migrate to `gatsby-image-plugin` instead of `gatsby-image`, we ran into issues. Our pages that are built using `pageName.tsx` and default exports build just fine, but for the pages we're using `gatsby-node.js` and `createPages`, we hit the following errors:

```
Error in function EnsureResources.render in ./.cache/ensure-resources.js:86
EnsureResources was not able to find resources for path: "/" This typically means that an issue occurred building components for that path. Run `gatsby clean` to remove any cached elements.
```

This is the following we're using 

### Steps to reproduce

- Clone our repo at this commit:
https://github.com/unicorn-utterances/unicorn-utterances/tree/b0ef2fe122f19c805bd7e7bcd93e41d8b6619d45

- Open `localhost:8000/`, see error (route uses `createPages`)
- Open `localhost:8000/about`, see no error (not using `createPages`)

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```
​C:\Users\crutchcorn\git\UnicornUtter\unicorn-utterances [images ≡]
λ  yarn gatsby info --clipboard
yarn run v1.22.5
$ C:\Users\crutchcorn\git\UnicornUtter\unicorn-utterances\node_modules\.bin\gatsby info --clipboard

  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 1600 Six-Core Processor
  Binaries:
    Node: 12.16.1 - C:\Users\CRUTCH~1\AppData\Local\Temp\yarn--1615323931193-0.12676928870208415\node.CMD
    Yarn: 1.22.5 - C:\Users\CRUTCH~1\AppData\Local\Temp\yarn--1615323931193-0.12676928870208415\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.3 - /c/Program Files (x86)/Python38-32/python
  Browsers:
    Chrome: 88.0.4324.190
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.45)
  npmPackages:
    gatsby: ^3.0.4 => 3.0.4
    gatsby-image: ^3.0.0 => 3.0.0
    gatsby-plugin-feed: ^3.0.0 => 3.0.0
    gatsby-plugin-google-analytics: ^3.0.0 => 3.0.0
    gatsby-plugin-image: ^1.0.0 => 1.0.0
    gatsby-plugin-lunr: ^1.5.2 => 1.5.2
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0
    gatsby-plugin-offline: ^4.0.0 => 4.0.0
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5
    gatsby-plugin-sass: ^4.0.2 => 4.0.2
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0
    gatsby-plugin-sitemap: ^3.0.0 => 3.0.0
    gatsby-plugin-typescript: ^3.0.0 => 3.0.0
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-remark-autolink-headers: ^3.0.0 => 3.0.0
    gatsby-remark-copy-linked-files: ^3.0.0 => 3.0.0
    gatsby-remark-external-links: 0.0.4 => 0.0.4
    gatsby-remark-images: ^4.0.0 => 4.0.0
    gatsby-remark-images-medium-zoom: ^1.7.0 => 1.7.0
    gatsby-remark-prismjs: ^4.0.0 => 4.0.0
    gatsby-remark-responsive-iframe: ^3.0.0 => 3.0.0
    gatsby-remark-series: ^1.0.3 => 1.0.3
    gatsby-remark-video: ^1.2.5 => 1.2.5
    gatsby-source-filesystem: ^3.0.0 => 3.0.0
    gatsby-transformer-json: ^3.0.0 => 3.0.0
    gatsby-transformer-remark: ^3.0.0 => 3.0.0
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0
  npmGlobalPackages:
    gatsby-remark-code-repls: 3.7.0-next.0
```

**Comment by miguelt1** [comment]
I'm having the same problem

**Comment by miguelt1** [comment]
I solved this now by running gatsby build that told me the specific error

**Comment by crutchcorn** [comment]
@miguelt1 I don't seem to get an error when running `gatsby build`

**Comment by bradlocking** [comment]
Same issue here. Looks inconsistent for me, some pages made using `createPage` work fine, whereas others do not. Haven't tried `gatsby build` yet

**Comment by shendriksza** [comment]
Exactly the same here. Migration to Gatsby V3 was fine, migrating to gatsby-plugin-image gives the "EnsureResources" error when running Gatsby develop. Gatsby build seems kind of to work, but also inconsistently

**Comment by bradlocking** [comment]
> Exactly the same here. Migration to Gatsby V3 was fine, migrating to gatsby-plugin-image gives the "EnsureResources" error when running Gatsby develop. Gatsby build seems kind of to work, but also inconsistently

@shendriksza issue persists with or without `gatsby-plugin-image` for me, and on `development` and `production` environments

**Comment by andreydrozd-smfe** [comment]
I have this issue, but it's not because of `gatsby-plugin-image`, it's just part of the migration. Building the project works, but when I try to run it locally it fails. 

What's weird is that http://localhost:8000/___graphql works and the page briefly flashes before I get the error message. The pages are clearly building; it's like Gatsby is looking in the wrong place or the source plugin I use for this project (gatsby-source-prismic) is putting them in the wrong place...

What's even more weird is that my repo was chosen to test a new feature flag - DEV_SSR - and when I turn it off, I don't get the brief page flash before the error message, it goes straight to the error message.

**Comment by stephan-swiftcom** [comment]
On Gatsby v3.1 the error reporting is much better. We noticed the string handling library "Voca" was throwing exceptions and after removing it from our codebase the site finally compiles wiithout throwing the EnsureResources error.

Why or how this happens I'm not sure, but hopefully it helps someone

**Comment by andreydrozd-smfe** [comment]
> I have this issue, but it's not because of `gatsby-plugin-image`, it's just part of the migration. Building the project works, but when I try to run it locally it fails.
> 
> What's weird is that http://localhost:8000/___graphql works and the page briefly flashes before I get the error message. The pages are clearly building; it's like Gatsby is looking in the wrong place or the source plugin I use for this project (gatsby-source-prismic) is putting them in the wrong place...
> 
> What's even more weird is that my repo was chosen to test a new feature flag - DEV_SSR - and when I turn it off, I don't get the brief page flash before the error message, it goes straight to the error message.

I tried again with Gatsby 3.1 and it worked this time. Just some manageable missing Webpack polyfills errors remained.

**Comment by stephan-swiftcom** [comment]
> > I have this issue, but it's not because of `gatsby-plugin-image`, it's just part of the migration. Building the project works, but when I try to run it locally it fails.
> > What's weird is that http://localhost:8000/___graphql works and the page briefly flashes before I get the error message. The pages are clearly building; it's like Gatsby is looking in the wrong place or the source plugin I use for this project (gatsby-source-prismic) is putting them in the wrong place...
> > What's even more weird is that my repo was chosen to test a new feature flag - DEV_SSR - and when I turn it off, I don't get the brief page flash before the error message, it goes straight to the error message.
> 
> I tried again with Gatsby 3.1 and it worked this time. Just some manageable missing Webpack polyfills errors remained.

Could you elaborate on the Webpack polyfills that you managed to fix?

I have identified another library (**reaptcha**) also refusing to work with Gatsby v3.1, throwing the EnsureResources error. I managed to confirm that both **reaptcha** as well as **voca** specifically throw a **global is not defined** exception when you manage to identify the error. Seems to me Gatsby ends up showing the EnsureResources error when a library throws an exception while being imported

**Comment by andreydrozd-smfe** [comment]
> > > I have this issue, but it's not because of `gatsby-plugin-image`, it's just part of the migration. Building the project works, but when I try to run it locally it fails.
> > > What's weird is that http://localhost:8000/___graphql works and the page briefly flashes before I get the error message. The pages are clearly building; it's like Gatsby is looking in the wrong place or the source plugin I use for this project (gatsby-source-prismic) is putting them in the wrong place...
> > > What's even more weird is that my repo was chosen to test a new feature flag - DEV_SSR - and when I turn it off, I don't get the brief page flash before the error message, it goes straight to the error message.
> > 
> > 
> > I tried again with Gatsby 3.1 and it worked this time. Just some manageable missing Webpack polyfills errors remained.
> 
> Could you elaborate on the Webpack polyfills that you managed to fix?
> 
> I have identified another library (**reaptcha**) also refusing to work with Gatsby v3.1, throwing the EnsureResources error. I managed to confirm that both **reaptcha** as well as **voca** specifically throw a **global is not defined** exception when you manage to identify the error. Seems to me Gatsby ends up showing the EnsureResources error when a library throws an exception while being imported

I needed stream and vm. I also ended up installing babel-preset-gatsby and the cli was complaining that was missing.

```
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    resolve: {
      fallback: {
        stream: require.resolve('stream-browserify'),
        vm: require.resolve('vm-browserify'),
      },
    },
  });
};
```
