### ISSUE TITLE
warn Deprecation warning: `@nodeInterface` extension is deprecated

### ISSUE THREAD

**Issue by shameer-rahman** [gatsbyjs/gatsby#30159]
I'm trying to migrate to gatsby v3, I'm getting the following warning when run gatsby develop

warn Deprecation warning: `@nodeInterface` extension is deprecated and will be removed in Gatsby v4. Use interface inheritance instead.
To upgrade replace the old format:
  interface `ContentfulEntry` @nodeInterface
with the new one (in `createTypes` action of schema customization API):
  interface `ContentfulEntry` implements Node
Read more about schema customization here:
https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization/

the warning seems to be related to gatsby-source-contentful.

**Comment by pieh** [comment]
Hey @shameer-rahman - seems like https://github.com/gatsbyjs/gatsby/pull/29675 is looking to solve deprecations just wasn't merged and published yet

**Comment by vladar** [comment]
I think this is fixed and published now in `gatsby-source-contentful@5.0.3`
