### ISSUE TITLE
[gatsby-plugin-image] StaticImage wont work with emotion styledComponent

### ISSUE THREAD

**Issue by ahmadkhalaf1** [gatsbyjs/gatsby#30165]
Hello , i am trying to use StaticImage with styledComponent but the image wont show up ,
this is my code
```
const StlyedImg = styled(StaticImage)`
  position: absolute;
  top: -4rem;
  width: 200px;
  height: 140px;
  margin: 0 0 0 -7.5rem;
  padding: 0;
  display: block;
  left: 50%;
  transform: rotate(180deg);
  overflow: unset;
`;
```
```
<StlyedImg src="../images/flower_06_reminder.png" alt="flower" width={200} height={140} />
```

however loading the image outside of styledComponent will render just fine.

**Comment by LekoArts** [comment]
Closing in favor of https://github.com/gatsbyjs/gatsby/discussions/30164

Please don’t create duplicates

**Comment by ahmadkhalaf1** [comment]
> Closing in favor of #30164
> 
> Please don’t create duplicates

i cant see a duplicate issue ? the number u mentioned is taking me to this issue ... 
can u please check? i still have this issue at production and i need to fix it asap
