### ISSUE TITLE
Weird errors when tsconfig file has syntax error

### ISSUE THREAD

**Issue by pie6k** [gatsbyjs/gatsby#3016]
I'm using gatsby with typescript. I had syntax error in tsconfig.json file:

```
{
  "compilerOptions": {
    "outDir": "./dist/",
    "rootDir": "./src",
    "baseUrl": "./src",
    "sourceMap": true,
    "noImplicitAny": true,
    "allowSyntheticDefaultImports": true,, <<<--- 2 commas here instead of 1!!!!!
    "module": "commonjs",
    "target": "esnext",
    "jsx": "react",
    "noUnusedLocals": true,
    "lib": ["dom", "es2015", "es2017"]
  },
  "include": ["./src/**/*"]
}
```

Error I had because of that:

`Module build failed: (8,42): error TS1136: Property assignment expected.`

![image](https://user-images.githubusercontent.com/7311462/33206251-e4ed2b3e-d109-11e7-847c-f5e05675deba.png)

Took me quite a while and some headache before I found out it was related to json syntax. 

Removing comma solved issue.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
