### ISSUE TITLE
[gatsby-plugin-sharp] Image can't be loaded after adding duotone transformOption

### ISSUE THREAD

**Issue by alandickinson** [gatsbyjs/gatsby#30171]
## Description

I've just updated to Gatsby v3 and have been updating my graphql queries. After adding a duotone effect in the `transformOptions` section of my graphql image sharp query, the image no longer loads. Without the duotone option the image is processed and loads correctly.

### Steps to reproduce

This query will only show the tracedSVG, not the final duotoned image:
```graphql

query {
    portraitImage: file(relativePath: {regex: "/portrait_front/"}) {
      childImageSharp {
        gatsbyImageData(
          layout: FULL_WIDTH,
          placeholder: TRACED_SVG,
          tracedSVGOptions: { background: "#8CFFE6", color: "#A6A8AF", turdSize: 0 },
          transformOptions: { duotone: { highlight: "#19FFCD", shadow: "#4E535F", opacity: 80 }}
        )
      }
    }
}
```

### Environment

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 7.6.1 - ~/.nvm/versions/node/v12.21.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Safari: 14.0.2
  npmPackages:
    gatsby: ^3.0.3 => 3.0.3 
    gatsby-image: 3.0.0 => 3.0.0 
    gatsby-link: 3.0.1 => 3.0.1 
    gatsby-plugin-google-analytics: 3.0.0 => 3.0.0 
    gatsby-plugin-image: ^1.0.0 => 1.0.0 
    gatsby-plugin-react-helmet: 4.0.0 => 4.0.0 
    gatsby-plugin-sharp: 3.0.0 => 3.0.0 
    gatsby-plugin-styled-components: 4.0.0 => 4.0.0 
    gatsby-source-filesystem: 3.0.0 => 3.0.0 
    gatsby-transformer-sharp: 3.0.0 => 3.0.0

**Comment by ascorbic** [comment]
Can you confirm whether the image is being created at all? Inspect the image and look for the `src`. Also check the results of the query in GraphiQL
