### ISSUE TITLE
TypeError: Cannot read property 'Title' of undefined

### ISSUE THREAD

**Issue by jordan-miguel** [gatsbyjs/gatsby#30180]
## Issue

I can't successfully render my queried data inside of my component.

### Steps to reproduce

1. I test my graphQL query that will be used to pull in data from my CMS (_sanity_)
2. I attempt to render this in my component
3. I run `gatsby develop`
4. I can see `TypeError: Cannot read property 'Title' of undefined` error on my browser

I am using [these docs ](https://www.gatsbyjs.com/docs/recipes/querying-data/)as a reference.

### Code 

```
export const query = graphql`
  query {
    allSanityPosts {
      edges {
        node {
          Title
        }
      }
    }
  }
`;

const singlePost = ({ data }) => (
    <Layout>
        <Header />
        <div>
        <h1>{data.post.Title}</h1>
        </div>
    </Layout>
)

export default singlePost
```

### Error

![Screenshot 2021-03-10 at 23 27 50](https://user-images.githubusercontent.com/14114089/110711925-425a0380-81f8-11eb-9231-2baf09a2bf37.png)

**Comment by KyleAMathews** [comment]
Does the query work in graphiql?

**Comment by jordan-miguel** [comment]
Yes it does :) 

<img width="1211" alt="Screenshot 2021-03-11 at 00 02 54" src="https://user-images.githubusercontent.com/14114089/110715433-260c9580-81fd-11eb-97ec-881c786e537a.png">
