### ISSUE TITLE
Gatsby v3: Refresh misses first bundle rebuild after `gatsby develop`

### ISSUE THREAD

**Issue by kelvindecosta** [gatsbyjs/gatsby#30183]
## Overview

The Refresh mechanism is not detecting the first change.

Moreover, it stops working with `preact`.

> Note, a "change" refers to changing file contents and triggering a rebuild.

## Reproduction

I used the default starter and installed `gatsby-plugin-preact` with its required dependencies.

### With `react` (default)

Here are the steps I took, using `yarn` as my package manager and Chrome as my browser:

- Install the default starter:

  ```bash
  git clone https://github.com/gatsbyjs/gatsby-starter-default.git gatsbyv3-refresh-test && cd gatsbyv3-refresh-test
  ```

- Install dependencies:

  ```bash
  rm package-lock.json # Optional (since I am using yarn)
  yarn
  ```

### With `preact`

These are the additional steps I took to use `preact`:

- Install `gatsby-plugin-preact`:

  ```bash
  yarn add gatsby-plugin-preact preact preact-render-to-string
  ```

  Add `gatsby-plugin-preact` to the list of `plugins` in `gatsby-config.js`.

## Behaviour

Here are a few steps I followed to test the behavior:

- Start the dev server:

  ```bash
  gatsby develop
  ```

- Visit the [development server](http://localhost:8000)
- Make a change to the `IndexPage` component.

### With `react` (default)

**The first change doesn't seem to trigger a refresh**.

To notice the first file change, another rebuild must be triggered to trigger a refresh (technically a change but with the files staying untouched).

All subsequent changes seem to properly trigger a refresh.

### With `preact`

Just as in the previous case, the first change doesn't seem to trigger a refresh.
There is however, another issue:

**A manual reload is required for the browser to display changes**.

In the previous case, the browser console showed a few `[HMR]` messages whenever changes were detected.
Now, no such messages are logged.

( `preact` part of the issue split into separate issue handling just preact part of this report - https://github.com/gatsbyjs/gatsby/issues/30190 )

## Environment

<details>

<summary>

Running `gatsby info` on reproduction:

</summary>

```

  System:
    OS: Linux 5.4 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.4/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Languages:
    Python: 3.9.1 - /usr/bin/python
  npmPackages:
    gatsby: ^3.0.1 => 3.0.1
    gatsby-plugin-gatsby-cloud: ^2.0.0 => 2.0.0
    gatsby-plugin-image: ^1.0.0 => 1.0.0
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0
    gatsby-plugin-offline: ^4.0.0 => 4.0.0
    gatsby-plugin-preact: ^5.0.0 => 5.0.0
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0
    gatsby-source-filesystem: ^3.0.0 => 3.0.0
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0
  npmGlobalPackages:
    gatsby-cli: 2.19.1

```

</details>

## Related (maybe?)

I _vaguely remember_ when I could preemptively navigate to http://localhost:8000 (or maybe it was `:9000`)
_before the development bundle was built_.
The browser would automatically reload the page.

## Conclusion

The refreshing mechanism of the development server doesn't seem to work perfectly as it did before migrating to v3.
The first file changes are never refreshed.

Using `gatsby-plugin-preact` requires an additional step of manually reloading each change, which means refresh is not working.

Any help is greatly appreciated, thanks!

**Comment by pieh** [comment]
Thanks for report @kelvindecosta , I was able to repro both issues:
 - first save after starting `gatsby develop` not actually updating
 - having to manually refresh when using preact

I will split this issue into 2 separate ones to be able to easier track them individually. I moved `preact` to https://github.com/gatsbyjs/gatsby/issues/30190 and will use this issue for first save problem

**Comment by kelvindecosta** [comment]
That sounds good, @pieh !
Thank you for the response!
