### ISSUE TITLE
gatsby new projectName doesn't include react-helmet

### ISSUE THREAD

**Issue by IljaDaderko** [gatsbyjs/gatsby#3019]
So I was playing around with new project and decided to build it to test if everything is ok, got an error that `react-helmet` couldn't be found in `gatsby-plugin-react-helmet` installing it as separate package solved the issue.

Hence my suggestion, if `gatsby-plugin-react-helmet` is included as default, should `react-helmet` also be? If so let me know and I'll submit quick pr to fix this 👍

**Comment by calcsam** [comment]
Can you copy-paste the error message?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
