### ISSUE TITLE
"gatsby develop" Hot Reloading opens browser tab multiple times

### ISSUE THREAD

**Issue by LeKoArts** [gatsbyjs/gatsby#3020]
Hi,

I normally modify the "scripts" in the package.json to ``gatsby develop -o`` to save some time. With the latest Gatsby version some weird behavior occurred. Initially it opens my browser tab as always but when I edit my markdown files for example it opens up a new browser tab on every save instead of hot reloading the old one.

Right now I have to remove the ``-o`` to have Gatsby working as intended.

**Comment by LeKoArts** [comment]
@KyleAMathews Still relevant :/

**Comment by kennedyrose** [comment]
I am experiencing this as well. I'm using the latest Gatsby version (1.9.128), with Chrome on Mac.

**Comment by KyleAMathews** [comment]
The latest gatsby should have this fixed — leave a comment if otherwise!

**Comment by Lc0rE** [comment]
I'm experiencing this issue on Windows. Even invoking the dev server with the `gatbsy develop -H localhost` is working for me.
I can't see an opening tab when I start the server and, of course, there is no Hot Reloading.
Curious thing: when I stop the server from the terminal, I can see this message in the browser console:

```
[HMR] connected process-update.js:41 
[HMR] Checking for updates on the server...
```

Should I try something else?
