### ISSUE TITLE
Unhandled Runtime Error - "Error in function Module.<module>"

### ISSUE THREAD

**Issue by olegkorol** [gatsbyjs/gatsby#30214]
## Description

I've just migrated to Gatsby v3 and am getting an "Unhandled Runtime Error".

### Steps to reproduce

Upgrade Gatsby and all related dependencies:

```
See installed versions below.
```

Run `gatsby develop -o` (as `yarn start`). Everything should look fine here.

Go to the browser and the error should be seen.

**NOTE: this happens with all components, not just "SEO".**

### Expected result

The app should work as it did with Gatsby v2. The component `SEO` (and others) should be loaded correctly.

This is how the component is exported/imported (pseudo-code):

```
// file structure
src
  components
    common
      SEO
        index.jsx <-- `export const SEO = () => {return (<Helmet>...</Helmet>)}`
    index.js <-- `export * from './SEO';`
```

```
// import inside pages/index.js

import { Layout, SEO } from '@components/common';

const Index = () => (
  <Layout>
    <SEO />
    // ...
  </Layout>
);

export default Index;
```

### Actual result

The develop build runs successfully, error-free, but in the browser the following error appears:

```
Unhandled Runtime Error

One unhandled runtime error found in your files. See the list below to fix it:
Error in function Module.SEO in ./src/components/common/index.js:
Cannot read property 'SEO' of undefined
```

### Environment

```
  System:
    OS: macOS 11.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.5.0/bin/yarn
    npm: 7.5.4 - ~/.nvm/versions/node/v14.5.0/bin/npm
  Languages:
    Python: 3.8.1 - /Users/user/.pyenv/shims/python
  Browsers:
    Chrome: 89.0.4389.82
    Safari: 14.0.1
  npmPackages:
    gatsby: ^3.0.4 => 3.0.4 
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5 
    gatsby-plugin-canonical-urls: ^3.0.0 => 3.0.0 
    gatsby-plugin-create-client-paths: ^3.0.0 => 3.0.0 
    gatsby-plugin-favicon: ^3.1.6 => 3.1.6 
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0 
    gatsby-plugin-nprogress: ^3.0.0 => 3.0.0 
    gatsby-plugin-offline: ^4.0.0 => 4.0.0 
    gatsby-plugin-postcss: ^4.0.0 => 4.0.0 
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0 
    gatsby-plugin-sharp: ^3.0.1 => 3.0.1 
    gatsby-plugin-sitemap: ^3.0.0 => 3.0.0 
    gatsby-plugin-styled-components: ^4.0.0 => 4.0.0 
    gatsby-source-filesystem: ^3.0.0 => 3.0.0 
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0 
  npmGlobalPackages:
    gatsby-cli: 2.19.2
```

**Comment by vladar** [comment]
Hi @olegkorol !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by olegkorol** [comment]
Thanks for the quick reply, @vladar!

The issue here seems to be that I am using `styled-components` together with TailwindCSS (`tailwind.macro`).

Styled components work just fine (although `gatsby-plugin-styled-components` says that Gatsby v3 is not supported yet):

```javascript
// components/common/Button/index.js
import styled from 'styled-components';

export const Button = styled.button`
  color: red;
`;

// pages/index.js
import React from 'react';
import { Button } from '@components/common';

const Index = () => (
    <Button>It works</Button>
);

export default Index;
```

But if Tailwind is added to the mix, namely `tailwind.macro`, then the error described in this issue appears:

```javascript
// components/common/ButtonT/index.js
import styled from 'styled-components';
import tw from 'tailwind.macro'; // <--

export const ButtonT = styled.button`
  ${tw`bg-blue-500`} // <--
`;

// pages/index.js
import React from 'react';
import { ButtonT } from '@components/common';

const Index = () => (
    <ButtonT>It does not work</ButtonT>
);

export default Index;
```

So apparently Gatsby is not the issue here, at least directly. I will keep looking for the root cause :/

**Comment by olegkorol** [comment]
I just ended up using [`twin.macro`](https://github.com/ben-rogerson/twin.examples/tree/master/gatsby-styled-components) instead of `tailwind.macro`.
