### ISSUE TITLE
TypeScript files are not minified during build (gatsby-plugin-typescript)

### ISSUE THREAD

**Issue by tomazy** [gatsbyjs/gatsby#3022]
When running `npm run build` all typescript files are converted into non-minified javascript files in the `public` folder. 

Example based on **Gatsby default starter**: https://github.com/tomazy/gatsby-site-typescript-issue (see the `public` folder)

Environment:
* gatsby@1.9.119
* node v8.2.1
* macOS Sierra 10.12.6

`gatsby-config.js`
```js
module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-typescript`,
  ],

```

`package.json`
```json
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "@types/node": "8.0.53",
    "@types/prop-types": "15.5.2",
    "@types/react": "16.0.25",
    "@types/react-dom": "16.0.3",
    "@types/react-helmet": "5.0.3",
    "@types/react-router-dom": "4.2.2",
    "gatsby": "^1.9.119",
    "gatsby-link": "^1.6.28",
    "gatsby-plugin-react-helmet": "^1.0.8",
    "gatsby-plugin-typescript": "1.4.10"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "main": "n/a",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --trailing-comma es5 --no-semi --single-quote --write \"src/**/*.js\"",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "prettier": "^1.8.2"
  }
}
```

**Comment by mattferderer** [comment]
Check out https://github.com/gatsbyjs/gatsby/pull/3369

**Comment by jurosh** [comment]
After update to `gatsby@1.9.175` minification works for me fine. So yea, looks like fixes in #3369 helped.

**Comment by tomazy** [comment]
I've just tried with the above mentioned project.
I upgraded all the packages first (`yarn upgrade`).
Then I ran `npm run build` and I got following error:

```
error Generating JavaScript bundles failed


  Error: component---src-layouts-index-tsx-f35f261d51b686413c6f.js from UglifyJs
  SyntaxError: Unexpected token: punc ()) [./src/layouts/index.tsx:8,21]
```

**Comment by jurosh** [comment]
Hm.. it might have something with configuration of tsconfig...

For me it's working fine with:
```
"module": "commonjs",
"target": "esnext",
```

**Comment by tomazy** [comment]
My fault - I updated gatsby but not gatsby-plugin-typescript.

Confirming that it works as expected with 
- gatsby 1.9.175
- gatsby-plugin-typescript 1.4.15
