### ISSUE TITLE
read ECONNRESET Yoga-layout-prebuilt + fast reload not working

### ISSUE THREAD

**Issue by Kevsonschouten** [gatsbyjs/gatsby#30227]
## Description

When starting with a minimal starter V3 after altering content (e.g. Hello World --> Hello world 2). 
Fast reload is not working and after restarting Gatsby Develop I get a warning:

```
C:\Users\Kevin Schouten\AppData\Roaming\npm\node_modules\gatsby-cli\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^
        
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

### Steps to reproduce

1. Downloading the V3 starter https://www.gatsbyjs.com/starters/gatsbyjs/gatsby-starter-hello-world/
2. Run Gatsby Develop --> works
3. Edit index.js
4. Hot reload does not work
5. Quit Gatsby Develop
6. Rerun Gatsby Develop

### Expected result

Fast Reload + Gatsby Develop without any errors because no alterations have been done, except within the index.js.

### Actual result

No Fast Reload + Error on Gatsby Develop.

### Environment

  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.6.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 88.0.4324.190
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.50)
  npmPackages:
    gatsby: ^3.0.4 => 3.0.4

**Comment by srajgure** [comment]
@Kevsonschouten I could not reproduce this issue. Everything is working fine for me. I would suggest you to check your dependencies or refer to some previous issue like #13918

**Comment by Kevsonschouten** [comment]
Updating npm seems to have fixed the reload issue.

Regarding the ECONNRESET I'm still not sure.

Changing gatsby Develop -- port 4000 (or any other) rebuilds correctly.

My dependencies:

`{
  "name": "gatsby-starter-hello-world",
  "private": true,
  "description": "A simplified bare-bones starter for Gatsby",
  "version": "0.1.0",
  "license": "0BSD",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write \"**/*.{js,jsx,ts,tsx,json,md}\"",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "clean": "gatsby clean",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\" && exit 1"
  },
  "dependencies": {
    "gatsby": "^3.0.4",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  },
  "devDependencies": {
    "prettier": "2.2.1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-hello-world"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  }
}
`

**Comment by LekoArts** [comment]
Did you also install the Gatsby CLI with `--legacy-peer-deps` flag? And can you give a reproduction for the ECONNRESET issue?

**Comment by Kevsonschouten** [comment]
Hi LekoArts,

I've also done npm i -g gatsby-cli --legacy-peer-deps but that keeps giving me the same error if I follow the steps above.

All I do is:

`gatsby new gatsby-starter-hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world`

Then run Gatsby develop within te project --> Works.
Then ctrl + c to stop the process (e.g. I want to restart).
Then run Gatsby develop again and I get the ECONNREST issue.

Closing either the tab, or refresh the tab - or changing port before the next gatsby develop comand, gives no errors.

P.s: Running the same project on my Mac all works.
