### ISSUE TITLE
Gatsby 3 build does not include or execute javascript

### ISSUE THREAD

**Issue by minimit** [gatsbyjs/gatsby#30238]
## Description

When using `gatsby build` no javascript work on the page.

### Steps to reproduce

In `src\gatsby\components\layout.js`.

```
if (typeof window !== 'undefined') {
    require('myscript')
}

export default class Layout extends React.Component {
  componentDidMount() {
    console.log('test')
```

### Expected result

`console.log` and `myscript` should execute

### Actual result

No console messages

### Environment

```
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
  Binaries:
    Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15
  Browsers:
    Chrome: 89.0.4389.82
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.50)
  npmPackages:
    gatsby: ^3.0.4 => 3.0.4
    gatsby-plugin-catch-links: ^3.0.0 => 3.0.0
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0
    gatsby-plugin-module-resolver: ^1.0.3 => 1.0.3
    gatsby-plugin-page-creator: ^3.0.0 => 3.0.0
    gatsby-plugin-postcss: ^4.0.0 => 4.0.0
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0
    gatsby-plugin-sitemap: ^3.0.0 => 3.0.0
    gatsby-remark-classes: ^1.0.0 => 1.0.0
    gatsby-remark-component: ^1.1.3 => 1.1.3
    gatsby-remark-custom-blocks: ^3.0.0 => 3.0.0
    gatsby-remark-external-links: ^0.0.4 => 0.0.4
    gatsby-source-contentful: 5.0.3 => 5.0.3
    gatsby-source-filesystem: ^3.0.0 => 3.0.0
    gatsby-source-prismic: ^3.3.4 => 3.3.4
    gatsby-transformer-remark: ^3.0.0 => 3.0.0
  npmGlobalPackages:
    gatsby-dev-cli: 2.7.23
    gatsby: 2.25.3
```

**Comment by KyleAMathews** [comment]
Just to double check, you use that layout in a page component?

**Comment by minimit** [comment]
> Just to double check, you use that layout in a page component?

Yes sure, in most of the pages

**Comment by matthewkwong2** [comment]
Same issue on Gatsby v3. The issue happens after I have upgraded the packages (i.e. running `npm update --legacy-peer-deps`) It seems that one of the dependency causes the issue. 

Might be webpack, but not sure.

**Comment by matthewkwong2** [comment]
Yep, it is Webpack. Apparently, 5.25.0 causes the problem. Downgrade it to 5.24.4 works around the problem for now.
https://github.com/webpack/webpack/issues/12880

**Comment by minimit** [comment]
I tried using the same version of webpack of gatsby but the problem still persist

`    "webpack": "^5.16.0",`

**Comment by DDeme** [comment]
I have the same issue. After migrating to V3 js stopped working.

**Comment by sokra** [comment]
Sorry that's a webpack bug. Bugfix incoming...

**Comment by sokra** [comment]
fixes by https://github.com/webpack/webpack/releases/tag/v5.25.1

**Comment by klittlepage** [comment]
Confirmed that upgrading `webpack` to `5.25.1` or downgrading to `5.24.4` resolves the issue. For folks who need a quick workaround, add the following to your `package.json`:

```json
  "resolutions": {
    "webpack": "5.25.1"
  },
```

**Comment by LekoArts** [comment]
Thanks @sokra for fixing this so quickly, much appreciated!

The `resolutions` workaround isn't needed anymore with this, make sure that this version is installed when installing Gatsby. If you're on `5.25.0` nuking node_modules and lock files and re-install will do the trick, too.

**Comment by sokra** [comment]
> nuking node_modules and lock files and re-install will do the trick, too.

If you want to play more safe, it should be enough to only remove the `webpack` lines from the lockfile. Or run `yarn upgrade webpack`.
