### ISSUE TITLE
Gatsby sitemap includes error (404) pages

### ISSUE THREAD

**Issue by jurosh** [gatsbyjs/gatsby#3024]
Sitemap generated by sitemap plugin contains 404 pages.

```
<url> <loc>https://domain/404/</loc> <changefreq>daily</changefreq> <priority>0.7</priority> </url>
<url> <loc>https://domain/404.html</loc> <changefreq>daily</changefreq> <priority>0.7</priority> </url>
```

It contains custom page and also default location of 404 page.

**Expected behavior:**

Sitemap shouldn't contain error pages.

**Details:**

```
"gatsby-plugin-sitemap": "1.2.5",
"gatsby": "1.9.108"
```

**Comment by calcsam** [comment]
If you'd like to overwrite the default query to exclude 404 pages, you can include that as an option in your plugin config.

The default query is below: https://github.com/gatsbyjs/gatsby/blob/524ff171cd890b79ce9535d6dc10550c70365d33/packages/gatsby-plugin-sitemap/src/internals.js#L16-L35

Even better: submit a PR that implements an `excludes` option for this plugin.

**Comment by KyleAMathews** [comment]
Actually let's just update the default query to auto exclude the 404 page. @jurosh could your PR a fix?

**Comment by jurosh** [comment]
Will look into that.. I am quite busy right now, so give me few days :)

**Comment by jurosh** [comment]
PR submitted! :blush:

**Comment by jurosh** [comment]
As of `gatsby-plugin-sitemap@1.2.9` there are no 404 pages, closing 😎

**Comment by KyleAMathews** [comment]
👊 thanks!
