### ISSUE TITLE
Failed to fetch sw.js - service worker error

### ISSUE THREAD

**Issue by andrelandgraf** [gatsbyjs/gatsby#30250]
I hope this is not a duplicate. I would really appreciate your support on this!

## Description

On development, I receive the following warning on Chrome (Version 89.0.4389.82 (Official Build) (x86_64)):

```
[Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
```

On production (Netlify), I then receive the following warnings and error:

Warning:
```
The FetchEvent for "https://my-page.com/" resulted in a network error response: the promise was rejected.
```
Error:
```
Uncaught (in promise) TypeError: Failed to fetch sw.js:1
```
Warning:
```
Site cannot be installed: Page does not work offline. Starting in Chrome 93, the installability criteria is changing, and this site will not be installable. See https://goo.gle/improved-pwa-offline-detection for more information.
```

I updated my Gatsby site to Gatsby v3 and migrated to gatsby-plugin-image. I also updated all other plugins to latest and use node v12 but I still receive the same error.

It is probably an issue with gatsby-offline or gatsby-manifest, I think?

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

- demo app on Gatsby v2 that has this error: 
    - see errors in chrome: https://demo.andre-landgraf.cool/
    - the code can be found here: https://github.com/andrelandgraf/gatsby-x
- demo app on Gatsby v3 that has this error:
     - see errors in chrome: https://andre-landgraf.cool/
     - the code can be found here: https://github.com/andrelandgraf/andrelandgraf

Both sites are public on GitHub and especially my portfolio page is super small. If you still want me to create a smaller project, please let me know and I will set up a skeleton app.

### Expected result

What should happen?

PWA should work as expected on Chrome.

### Actual result

What happened.

Chrome throws service worker error and warnings.

### Environment

Clipboard of the v3 Gatby page I was referring to above:

```
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    npm: 7.6.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.90
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.0.1 => 3.0.1
    gatsby-plugin-image: ^1.0.0 => 1.0.0
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0
    gatsby-plugin-offline: ^4.0.0 => 4.0.0
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0
    gatsby-plugin-sitemap: ^3.0.0 => 3.0.0
    gatsby-plugin-styled-components: ^4.0.0 => 4.0.0
    gatsby-source-filesystem: ^3.0.0 => 3.0.0
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0
```

**Comment by brandonwkipp** [comment]
It looks like Chrome is rolling out some [changes to its PWA installation criteria](https://developer.chrome.com/blog/improved-pwa-offline-detection/) and will go live sometime this month.

**Comment by derykmarl** [comment]
Yes this sounds like what I'm getting.

`The FetchEvent for "https://example.com/" resulted in a network error response: the promise was rejected.
Promise.then (async)
(anonymous) @ Router.mjs:60
sw.js:1 Uncaught (in promise) TypeError: Failed to fetch
(index):1 Site cannot be installed: Page does not work offline. Starting in Chrome 93, the installability criteria is changing, and this site will not be installable. See https://goo.gle/improved-pwa-offline-detection for more information.`

I have tried adding '/' to precachePages in the hopes that might help, but it makes no difference.

**Comment by derykmarl** [comment]
I don't know if it's the 'correct' thing to do, but the following globPatterns workaround mentioned in #24225 worked for me:

```
    {
      resolve: `gatsby-plugin-offline`,
      options: {
        workboxConfig: {
          globPatterns: ['*.html']
        }
      }
    },
```

**Comment by acarnwath** [comment]
That workaround does not appear to be working for me; I have that in place (that was my answer on the other issue) and am still experiencing the issue.

**Comment by andrelandgraf** [comment]
It seems to be fixed. I am not aware that I updated my gatsby version but I do not see the error in the console anymore. Instead I get the following message: `installingWorker ServiceWorker`

**Comment by acarnwath** [comment]
Same here - it may have corresponded to the update to Chrome 90, but I didn't test it in a very controlled way. I know I saw the message in version 89, and didn't push any updates to the site between.
