### ISSUE TITLE
Gastby V3 Webpack configuration error

### ISSUE THREAD

**Issue by LiamDotPro** [gatsbyjs/gatsby#30289]
## Description

When upgrading to v3 I can no longer start my project due to a webpack error.

```
  ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
   - configuration.module.rules[11] should be one of these:
     ["..." | object { compiler?, dependency?, descriptionData?, enforce?, exclude?, generator?, include?, issuer?, issuerLayer?, layer?, loader?, mimetype?, oneOf?, options?, parser?, realResource?, resolve?, resource?
  , resourceFragment?, resourceQuery?, rules?, sideEffects?, test?, type?, use? }, ...]
     -> A rule.
     Details:
      * configuration.module.rules[10].issuer has an unknown property 'test'. These properties are valid:
        object { and?, not?, or? }
      * configuration.module.rules[11].issuer has an unknown property 'test'. These properties are valid:
        object { and?, not?, or? }
   - configuration.node has an unknown property 'path'. These properties are valid:
     object { __dirname?, __filename?, global? }
     -> Options object for node compatibility features.
```

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

I upgraded my dependancies and followed the migration guide.

### Expected result

Develop runs normally.

### Actual result

I get a webpack error

### Environment

 System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.20.1 - ~/.nvm/versions/node/v12.20.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.20.1/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v12.20.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.90
    Edge: 89.0.774.54
    Firefox: 86.0.1
    Safari: 13.1.3
  npmPackages:
    gatsby: ^3.0.4 => 3.1.0
    gatsby-image: ^3.1.0 => 3.1.0
    gatsby-plugin-eslint: ^2.0.8 => 2.0.8
    gatsby-plugin-image: ^1.1.0 => 1.1.0
    gatsby-plugin-manifest: ^3.1.0 => 3.1.0
    gatsby-plugin-offline: ^4.1.0 => 4.1.0
    gatsby-plugin-react-helmet: ^4.1.0 => 4.1.0
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-sass: ^4.1.0 => 4.1.0
    gatsby-plugin-sharp: ^3.1.0 => 3.1.0
    gatsby-plugin-styled-components: ^4.1.0 => 4.1.0
    gatsby-plugin-svgr: ^2.1.0 => 2.1.0
    gatsby-source-filesystem: ^3.1.0 => 3.1.0
    gatsby-source-graphql: ^3.1.0 => 3.1.0
    gatsby-source-prismic: ^3.3.4 => 3.3.4
    gatsby-theme-i18n-react-intl: ^1.0.4 => 1.0.4
    gatsby-transformer-sharp: ^3.1.0 => 3.1.0

**Comment by LiamDotPro** [comment]
closing as error is related to  "@svgr/webpack": "^5.5.0",

**Comment by IfeoluwaDavid** [comment]
I'm currently facing the same issue.
Any advice on how to migrate to Gatsby v3 despite the issues with `@svgr/webpack`?
I figured `@gatsby-plugin-svgr` also uses `@svgr/webpack` as a peer dependency.

**Comment by barbalex** [comment]
I have the same issue. But do not have any svgr related plugin.

How can I find out what plugin to blame?

**Comment by quansenB** [comment]
try using `"gatsby-plugin-svgr": "^3.0.0-beta.0",`

Solved it in my case.
