### ISSUE TITLE
[gatsby-remark-images] Upgrading gatsby-remark-images from 4.0.0 to 4.1.0 locks up `source and transform nodes` step with `lessBabel` option set

### ISSUE THREAD

**Issue by epbarger** [gatsbyjs/gatsby#30295]
## Description

On a Gatsby 3.0 site (untested with 2.0) with MDX, upgrading `gatsby-remark-images` from `4.0.0` to `4.1.0` cause the `source and transform nodes` step to never complete when the `lessBabel` option is set. The `lessBabel` option changes the length of the `source and transform nodes` step for us from 120 seconds to ~20 seconds, so turning this off is not very attractive

Thanks in advance for any help solving this!

### Steps to reproduce

Reproduced here - https://github.com/epbarger/gatsby-mdx-speed-testing. If you downgrade to `4.0.0` you'll see it develops/builds, but on `4.1.0` it will not.

From what I can tell to reproduce you just need to use `gatsby-plugin-mdx` with `gatsby-remark-images` version `4.1.0`, and set the `lessBabel: true` option.

### Expected result

`source and transform nodes` should complete in a sane amount of time like it used to

### Actual result

`source and transform nodes` hangs forever, or at least the 6 hours github actions is willing to wait ;)

### Environment

from reproduction - https://github.com/epbarger/gatsby-mdx-speed-testing

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.4/bin/yarn
    npm: 7.6.3 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.82
    Firefox: 86.0
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.1.0 => 3.1.0 
    gatsby-image: ^2.11.0 => 2.11.0 
    gatsby-plugin-manifest: ^3.0.0 => 3.1.0 
    gatsby-plugin-mdx: ^2.0.1 => 2.1.0 
    gatsby-plugin-react-helmet: ^3.10.0 => 3.10.0 
    gatsby-plugin-sharp: ^3.0.1 => 3.1.0 
    gatsby-remark-images: 4.1.0 => 4.1.0 
    gatsby-source-filesystem: ^3.0.0 => 3.1.0 
    gatsby-transformer-sharp: ^3.0.0 => 3.1.0 
  npmGlobalPackages:
    gatsby-cli: 2.17.0
```

**Comment by nitzanvolman** [comment]
I can confirm this happens, downgrading fixes the issue.
