### ISSUE TITLE
gatsby-source-wordpress: Search and replace for links

### ISSUE THREAD

**Issue by philmuze** [gatsbyjs/gatsby#30309]
Hi guys, really great work with this new version of the plugin. This pairing with the wpgraphl-plugin is awesome. I'm currently working on a migration to v4 for my project. One thing I used there a lot was the search and replace functionality for links - see [here](https://github.com/gatsbyjs/gatsby/pull/3498/files/cfe0d9d48fc5f29053e91b80c1e20e6c2f62924f). Do you have any plans to integrate this also to the version v4?

**Comment by TylerBarnes** [comment]
Ah, forgot to close this issue! This feature was added in https://github.com/gatsbyjs/gatsby/pull/31091. Thanks @philmuze !
