### ISSUE TITLE
gatsby-source-wordpress: MenuItem.link doesn't update when the linked node uri changes

### ISSUE THREAD

**Issue by henrikwirth** [gatsbyjs/gatsby#30307]
When I changed the structure of the pages, by making some of them child pages to others, the Menu where those pages were used wouldn't update until cache is cleared.

So somehow when changing pages, the Menu cache data should be invalidated, if this page was referenced in any Menu.

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
