### ISSUE TITLE
gatsby-source-wordpress: Error when fetching medias with v5.0.0 and gatsby-plugin-subfont

### ISSUE THREAD

**Issue by PSalaun** [gatsbyjs/gatsby#30300]
Hello!
Since I’ve updated gatsby and gatsby-source-wordpress-experimental to latest version, I cannot fetch medias from WP if the [`gatsby-source-subfont`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-subfont)  plugin is active (v2.2.5 or 2.5.0). This error message is repeated during the `Downloading remote files` cycle:
```node
error RequestError: connect ECONNREFUSED 127.0.0.1:443
    at ClientRequest.<anonymous> (/Users/[...]/node_modules/gatsby-source-wordpress-experimental/node_modules/got/dist/source/core/index.js:953:111)
    at Object.onceWrapper (events.js:313:26)
    at ClientRequest.emit (events.js:228:7)
    at ClientRequest.origin.emit (/Users/[...]/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  name: 'RequestError',
  code: 'ECONNREFUSED',
  timings: {
    start: 1607544364578,
    socket: 1607544364578,
    lookup: 1607544364579,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1607544364580,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 1,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 2
    }
  }
}
```

I can reproduce on the [example repo](https://github.com/gatsbyjs/gatsby-starter-wordpress-blog). It works with wordpress-experimental 3.0.0 but if I update to 5.0.0 (and use another WP url because the demo one isn’t up to date), it breaks the same way.

```js
// gatsby-config.js
{
        resolve: 'gatsby-plugin-subfont',
        options: {
          fallbacks: true,
          fontDisplay: 'swap',
          inlineCss: true,
          inlineFonts: true,
          silent: true,
          inputFiles: ['public/index.html'],
        },
},
```

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
