### ISSUE TITLE
gatsby-source-wordpress: Abstract type error when an ACF field is named "type"

### ISSUE THREAD

**Issue by ardiewen** [gatsbyjs/gatsby#30310]
It appears for most of my use cases, ACF works perfectly fine, even in advanced implementations using Flexible Content (and even nested Flexible Content!).

However, when one of my nested Flexible Content layouts has a field named `type`, it returns the following error:

```
"Abstract type WpPage_Pagefields_PageContent_TwoColumnContent_LeftColumn_ContentBuilder must resolve to an Object type at runtime for field WpPage_Pagefields_PageContent_TwoColumnContent_LeftColumn.contentBuilder with value 

{
	 __typename: \"Page_Pagefields_PageContent_TwoColumnContent_LeftColumn_ContentBuilder_Video\", 
	embedCode: \"<iframe width=\\\"560\\\" height=\\\"315\\\" src=\\\"...\\\" frameborder=\\\"0\\\" allow=\\\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\\\" allowfullscreen></iframe>\", 
	fieldGroupName: \"page_Pagefields_PageContent_TwoColumnContent_LeftColumn_ContentBuilder_Video\", 
	type: \"external\",
}, 


received \"undefined\". 


Either the WpPage_Pagefields_PageContent_TwoColumnContent_LeftColumn_ContentBuilder type should provide a \"resolveType\" function or each possible type should provide an \"isTypeOf\" function."
```

Renaming this field to `kind` for example, resolves this issue.

Note that I noticed this issue when testing migration from `gatsby-source-graphql` to `gatsby-source-wordpress-experimental`. This issue does not occur using the `gatsby-source-graphql` plugin.

**Comment by TylerBarnes** [comment]
I have a canary with a solution here `gatsby-source-wordpress@5.2.0-alpha-wordpress.34+e45fa4b460`
