### ISSUE TITLE
gatsby-source-wordpress: Disable Preview Optimization not working

### ISSUE THREAD

**Issue by luisduenas** [gatsbyjs/gatsby#30312]
I'm trying to disable `Preview Optimization` to fetch all the available nodes but it's not working, I'm following what the docs says [here](https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/features/preview.md#built-in-preview-plugin-options-preset)

this is my plugin config
```
  {
      resolve: `gatsby-source-wordpress-experimental`,
      options: {
        schema: {
          queryDepth: 5,
          typePrefix: `Wp`,
          timeout: 300000,
        },
        develop: {
          nodeUpdateInterval: 3000,
        },
        debug: {
          graphql: {
            showQueryOnError: true,
            showQueryVarsOnError: false,
            copyQueryOnError: true,
            panicOnError: false,
            // a critical error is a WPGraphQL query that returns an error and response data. Currently WPGQL will error if we try to access private posts so if this is false it returns a lot of irrelevant errors.
            onlyReportCriticalErrors: true,
          },
        },
        html: {
          useGatsbyImage: true,
        },
        url: process.env.WPGRAPHQL_URL,
        presets: null,
        verbose: true,
        type: {
          MediaItem: {
            lazyNodes: true,
            localFile: {
              requestConcurrency: 1,
            },
          },
        },
      },
    },
```
And this is my terminal output
![image](https://user-images.githubusercontent.com/16164843/103231657-2d561f80-48ed-11eb-96ec-8ec48a806193.png)

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
