### ISSUE TITLE
gatsby-source-wordpress: Fetching images on build time hangs at source and transform nodes specifically for SVG's

### ISSUE THREAD

**Issue by Fabiantjoeaon** [gatsbyjs/gatsby#30313]
Hi,

I've seen similar (closed) issues here regarding this issue, but I think my problem is a bit different.

My development build freezes during the step: `source and transform nodes`:

```
success  gatsby-source-wordpress  writing GraphQL queries to disk at ./WordPress/GraphQL/ - 0.179s
success  gatsby-source-wordpress  ingest WPGraphQL schema - 2.395s
success createSchemaCustomization - 5.052s
success  gatsby-source-wordpress  fetch root fields - 0.302s
success  gatsby-source-wordpress  Post - 0.321s - fetched 0
success  gatsby-source-wordpress  PostFormat - 0.374s - fetched 0
success  gatsby-source-wordpress  Comment - 0.390s - fetched 0
success  gatsby-source-wordpress  ContentType - 0.408s - fetched 3
success  gatsby-source-wordpress  Tag - 0.423s - fetched 0
success  gatsby-source-wordpress  Category - 0.494s - fetched 5
success  gatsby-source-wordpress  Menu - 0.494s - fetched 4
success  gatsby-source-wordpress  Page - 0.630s - fetched 8
success  gatsby-source-wordpress  MenuItem - 0.767s - fetched 16
success  gatsby-source-wordpress  UserRole - 0.276s - fetched 0
success  gatsby-source-wordpress  Taxonomy - 0.282s - fetched 3
success  gatsby-source-wordpress  User - 0.286s - fetched 1
⠂  gatsby-source-wordpress  MediaItem - fetched 1 id:" gatsby-source-wordpress  MediaItem"^C
not finished source and transform nodes - 57.613s
not finished  gatsby-source-wordpress  fetching nodes - 57.563s - 41 total
not finished  gatsby-source-wordpress  creating nodes - 56.505s
not finished  gatsby-source-wordpress  MediaItem - 56.505s - fetched 1
not finished Downloading remote files - 56.113s
```

But sometimes it freezes here:

```
⠄  gatsby-source-wordpress  fetching nodes - 43 total id:" gatsby-source-wordpress  fetching nodes"
```

I don't get an error whatsoever, it just keeps on hanging at this stage. 
I've tried different configs with `hardCache` and `useGatsbyImage`, and setting `GATSBY_CONCURRENT_DOWNLOAD` to 10 or lower, but with no success.

I've found out that this **only** happens for SVG files. Whenever I use lots of big images as JPEG/PNG, it builds just fine! Whenever I add a single SVG file to my site, this happens.
Removing all of my plugins except `gatsby-source-wordpress-experimental` doesn't do the trick either..

Should I be handling SVG's differently?

TIA!

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
