### ISSUE TITLE
gatsby-image <noscript> support

### ISSUE THREAD

**Issue by zionis137** [gatsbyjs/gatsby#3031]
- **current behaviour**
When deactivating JavaScript `gatsby-image` is not replacing the placeholder-image. So the grey-box or traced-SVG stays there. 
Demo (go to Dev-Tools and deactivate JS): https://using-gatsby-image.gatsbyjs.org/

- **expected behaviour**
no-script users are getting a normal image (without any effekts/lazy loading). Optimally `srcset` would be used, otherwise they just get a large image.

**Comment by fk** [comment]
Hi @zionis137! There's a duplicate of this issue in #3109 (and a PR already, #3122 🎉 ).
