### ISSUE TITLE
gatsby-source-wordpress: GraphQL process stops on this query

### ISSUE THREAD

**Issue by emaildano** [gatsbyjs/gatsby#30316]
My builds sometimes work and sometimes fail with no changes to my code but I think this is related or the cause.

I've rewritten this query to be somewhat generic. The area to focus in on is the wpParent part. Any query I have with that kills the GraphQL process immediately. The returned error code is below as well.

```
query ParentPageQuery {
  allWpCustomPostType(limit: 4, filter: {wpParent: {node: {slug: {eq: "parent-slug-name"}}}}) {
    nodes {
      title
    }
  }
}
```

```
ERROR 
Cannot read property 'typeInfo' of undefined
TypeError: Cannot read property 'typeInfo' of   undefined
```

The only way I see around this is to avoid using any wpParent mentions in my queries. I checked the other issues and this isn't mentioned yet so it may be a new one.

**Comment by kennethormandy** [comment]
For what it’s worth, I came across this same message, and `gatsby clean` with no other changes fixed it for me too.

I was querying a menu, where I was querying a `connectedNode`, and had added a new type of node to the menu. Before, all were Custom Post Types, and now there were both Custom Post Types and Pages. It also seemed like a cache issue to me, though, and `gatsby clean` fixed it.

**Comment by jacksellwood** [comment]
Hey there, we're interested in debugging this and finding a solution! Could you email wordpress@gatsbyjs.com with a login to a development copy of your WordPress install? Additionally, please add this site to Gatsby Cloud and include a link to the it in your email. This will help us debug more quickly. Thanks!
