### ISSUE TITLE
Theme shadowing in monorepo not working after upgrade to Gatsby 3

### ISSUE THREAD

**Issue by mjameswh** [gatsbyjs/gatsby#30335]
## Description

I have a monorepo project containing a Gatsby theme and an associated Gatsby site. The site shadows some files from the theme, as described in [Shadowing in Gatsby Theme](https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/shadowing/#extending-shadowed-files).

In Gatsby 2, the replacement component is indeed being displayed. However, after upgrading to Gastby 3, the original component is instead being rendered (that is, shadowing is not happening there).

### Steps to reproduce

See minimal example here: https://github.com/mjameswh/issue-gatsby3-monorepo-themeshadowing.

In that repo's history, the first commit is linked to Gatsby 2.23.12. Running from that commit, we can see that the replacement component is being rendered (in green); note that the original component is also being rendered (in red), since the replacement component imports and invoke the original component (this is expected).

In the second commit of that repo's history, Gatsby has been upgraded to 3.2.0-next-0 (note that result is the same with Gatsby 3.0.0). Running from that commit, we can see that only the original component is being rendered (in red).

I also tried using a pnpm workspace instead of yarn workspace (third commit in repo), but shadowing still doesn't work.

### Expected result

In Gatsby 2, the index page of the previous repo gives the following result:

<img width="266" alt="Result in Gatsby 2" src="https://user-images.githubusercontent.com/6412169/111644521-4d073080-87d6-11eb-8eda-bb757dcae73e.png">

### Actual result

In Gatsby 3, the result is instead:

<img width="265" alt="Result in Gatsby 3" src="https://user-images.githubusercontent.com/6412169/111644667-6dcf8600-87d6-11eb-966e-bf359930ce67.png">

### Environment

```
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Shell: 5.0.18 - /usr/local/bin/bash
  Binaries:
    Node: 14.8.0 - ~/.nvm/versions/node/v14.8.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v14.8.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 86.0
    Safari: 14.0.2
  npmPackages:
    gatsby: ^3.2.0-next.0 => 3.2.0-next.0 
    gatsby-legacy-polyfills: ^1.1.0 => 1.1.0 
    gatsby-link: ^3.1.0 => 3.1.0 
    gatsby-react-router-scroll: ^4.1.0 => 4.1.0 
    gatsby-theme-example: ^1.0.0 => 1.0.0 
```

**Comment by mjameswh** [comment]
Here are some (hopefully pertinent) information I have gathered while investigating this issue...

If I set a breakpoint in [`webpack-theme-component-shadowing`](https://github.com/gatsbyjs/gatsby/blob/85b642064113b1f6de94dd10cb21cef701d83539/packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js#L34), I capture the following sequence of requested path in relation with `SomeComponent`:

```
In Gatsby 2
===========

# In the followings, request.context = ...site-example/src/pages/index.js
/tuncated/project/packages/site-example/node_modules/gatsby-theme-example/src/components/SomeComponent
/tuncated/project/node_modules/gatsby-theme-example/src/components/SomeComponent
/tuncated/project/packages/gatsby-theme-example/src/components/SomeComponent
/tuncated/project/packages/gatsby-theme-example/src/components/SomeComponent

# ... then four more requests, with request.context = .../site-example/src/gatsby-theme-example/components/SomeComponent.js


In Gatsby 3
===========

# In the following, request.context = ...site-example/src/pages/index.js
/truncated/project/node_modules/gatsby-theme-example/src/components/SomeComponent
```

Note that, in both versions, `themeDir` for `gatsby-theme-example` is `/tuncated/project/packages/gatsby-theme-example` (that is the path to the actual package directory, rather than the path going through a symlink in `node_modules`).

Consequently, in Gatsby v2, `getMatchingThemesForPath()` will return nothing on the first and second query, but will return the identify the theme on the third request. However, in Gatsby 3, there is only one call, and `requestPath` on that call does not match the expected path, so the theme is never recognized.

This indicates that this regression is likely caused by a change introduced in Webpack 5...

**Comment by mjameswh** [comment]
Ok, I'm getting more of it...

The root of this issue is a change in Webpack's `enhanced-resolve`, which setup a pipeline of plugins linked by _hooks_. That pipeline determines how imports are resolved. One of these plugin is the `SymlinkPlugin`, which replace symlinks in a requested path by their canonical equivalent.

In Webpack 4, `enhanced-resolve` would setup `SymlinkPlugin` to be run on hook `file`, and to then execute hook `relative` afterward if a symlink was indeed found. Note that `relative` is a more earlier step in the chain, so `SymlinkPlugin` is essentially jumping back to an earlier step. [See here.](https://github.com/webpack/enhanced-resolve/blob/2dfe18a50fb669014e2189371ad7096608054d63/lib/ResolverFactory.js#L329)

But at [some point](https://github.com/webpack/enhanced-resolve/commit/c6b3399dedc5be240816f79703a0e8bfd3d240d8) on the road to Webpack 5, `enhanced-resolve` was modified to have `SymlinkPlugin` run on hook `existing-file` (that by itself is not a problem), and to execute hook `existing-file` if a symlink was indeed found (so no loop back, and that is our problem).

The problem here is that Gatsby's `webpack-theme-component-shadowing` currently register for hook `relative`, but given the new configuration in Webpack 5, that hook is no longer called _after_ resolution of symlinks.

So what should be done with this? I see three options:

1. Consider this is a bug in Webpack 5, file an issue and submit a pull request there, and hope they will agree pulling it.
2. Modify `webpack-theme-component-shadowing` to listen for another hook, either `existing-file` or `resolved`... But they are at the very end of the processing chain, which means that there might be some particular difficulties in handling events at that point.
3. Modify `webpack-theme-component-shadowing`'s algorithm to not depend on symlinks resolution.

Note that symlink resolution is disabled when using Yarn PnP, so even though they might be easier on the short term, solutions 1 and 2 may turn out to have little future.

I'm stalled here. I can help implementing a solution, but I think that some guidance from a core developer would be appropriate before I start working on either of the above strategy.

**Comment by axe312ger** [comment]
Thank you for your work! Can confirm that shadowing behaves different in v3. 

I have a lerna repo with multiple themes as well.

**Comment by axe312ger** [comment]
Still broken :(
