### ISSUE TITLE
warn Attempted import error: './Layout.module.less' does not contain a default export (imported as 'styles').

### ISSUE THREAD

**Issue by talentAN** [gatsbyjs/gatsby#30332]
I've config gatsby-plugin-less correctly,  here's the code.
`
import React from 'react';
import styles from './Layout.module.less';

const Layout = ({ children }) => {
  console.info(styles);
  return <div className={styles.layout}>{children}</div>;
};

export default Layout;
`

**Comment by amantiwari1** [comment]
try this
```js
import React from 'react';
import styles from './Layout.module.less';

const Layout = ({ children }) => {
console.info(styles);
return ( <> {children} </> )

};
export default Layout;
```

and 
 you could add `default export  styles` in the `./Layout.module.less`

if not works
   send code in `./Layout.module.less`
