### ISSUE TITLE
Problem when importing files

### ISSUE THREAD

**Issue by metehus** [gatsbyjs/gatsby#30354]
## Description

I'm receiving an error when importing an image file, even that it's correct.

The Code:
```js
...
import duotoneImage from '../assets/examples/duotone.jpg'
import gridImage from '../assets/examples/grid.jpg'
...
```

The error:
```
Generating development JavaScript bundle failed

Can't resolve '../assets/examples/grid.jpg' in '/mnt/d/Projects/Musicorum/web/src/pages'

If you're trying to use a package make sure that '../assets/examples/grid.jpg' is installed. If you're trying to use a local file
make sure that the path is correct.

File: src/pages/index.js

failed Re-building development bundle - 0.614s
```
This is my current structure:

![image](https://user-images.githubusercontent.com/22124518/111834169-f7b04980-88d1-11eb-9737-531a679370ba.png)

What i can't understand is that this is happening to this single file. If i change [this line](https://github.com/musicorum-app/web/blob/update/src/pages/index.js#L9) using the other file(`duotone.jpg`), like below, it works fine.
```js
import gridImage from '../assets/examples/duotone.jpg'
```

I also tried to change the `grid.jpg` file name, on the system and on the code, but no success either.

### Steps to reproduce

I'm not sure about what is currently causing this, but [here is the current file](https://github.com/musicorum-app/web/blob/update/src/pages/index.js).

### Expected result

It was expected to work as indeed, with the image actually being correct.

### Actual result

The `gatsby develop` command return an error, as specified on _Description_.

### Environment

```
  System:
    OS: Linux 4.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 15.3.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 7.6.0 - /usr/bin/npm
  npmGlobalPackages:
    gatsby-cli: 2.18.0
```

_P.S._: I'm using Windows WSL

**Comment by LekoArts** [comment]
Hi!

Can you please make sure that the JPEG file is not corrupted, e.g. with https://github.com/tjko/jpeginfo -- also try to recreate it. At first glance this doesn't seem like a Gatsby bug but a file that webpack can't use.
