### ISSUE TITLE
`sourceNodes` is called before all source plugins have finished creating nodes

### ISSUE THREAD

**Issue by kimbaudi** [gatsbyjs/gatsby#30359]
## `sourceNodes` is called before all source plugins have finished creating nodes

Looking at the [Gatsby Node API doc on sourceNodes](https://www.gatsbyjs.com/docs/reference/config-files/gatsby-node/#sourceNodes), it says:

> If you define this hook in `gatsby-node.js` it will be called exactly once after all of your source plugins have finished creating nodes.

However, `sourceNodes` is called before `gatsby-transformer-json` has finished creating my `TopicJson` nodes. I am sourcing `topic.json` file using `gatsby-transformer-json` and `gatsby-source-filesystem` into `TopicJson` node.

`topic.json`:

```json
[
  {
    "name": "gatsby"
  },
  {
    "name": "react"
  }
]
```

`gatsby-config.js`

```js
const path = require(`path`)

module.exports = {
  siteMetadata: {
    title: `Title`,
    description: `description`,
  },
  plugins: [
    `gatsby-transformer-json`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `zabba`,
        path: path.resolve(__dirname, `./src/data/`),
      },
    },
  ],
}
```

I define `sourceNodes` hook in `gatsby-node.js`

```js
exports.sourceNodes = ({ getNodes }) => {
  const topics = getNodes().filter((node) => node.internal.type === 'TopicJson')
  console.log(topics)
}
```

But `console.log(topics)` returns empty array `[]`.

The way I workaround this issue is to update `gatsby-config.js` to basically resolve `topic.json` **twice** using `gatsby-source-filesystem`, but using different name for `sourceInstanceName`:

`gatsby-config.js` workaround resolving `topic.json` twice:

```js
const path = require(`path`)

module.exports = {
  siteMetadata: {
    title: `Title`,
    description: `description`,
  },
  plugins: [
    `gatsby-transformer-json`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `zabba`,
        path: path.resolve(__dirname, `./src/data/`),
      },
    },
    // need to add this so TopicJson node is available in sourceNodes hook
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `abba`,
        path: path.resolve(__dirname, `./src/data/`),
      },
    },
  ],
}

```

now, `console.log(topics)` returns:

```shell
[
  {
    name: 'gatsby',
    id: '25758d1b-ca53-5591-8ed1-8c9f90f356c9',
    children: [],
    parent: '89ff1247-3973-5f17-8ce1-ad5eece36dac',
    internal: {
      contentDigest: '1b32b25e7e5958c5dd5d4101ca01604a',
      type: 'TopicJson',
      counter: 27,
      owner: 'gatsby-transformer-json'
    }
  },
  {
    name: 'react',
    id: '70e08266-8a41-5388-9737-6bd4af968efa',
    children: [],
    parent: '89ff1247-3973-5f17-8ce1-ad5eece36dac',
    internal: {
      contentDigest: '0b64a87339604a17fc57c20904d39a25',
      type: 'TopicJson',
      counter: 28,
      owner: 'gatsby-transformer-json'
    }
  }
]
```

`sourceNodes` hook should be called after `gatsby-transformer-json` finishes creating my `TopicJson` nodes so I can access it using `getNodes` (without me having to resolve my `topic.json` datasource twice using different sourceIntanceName values)

### Steps to reproduce

I've created a minimal reproduction at https://github.com/kimbaudi/gatsby-sourcenode-calledbefore

### Expected result

calling `sourceNodes` hook should be called after source plugins have finished creating nodes. 

### Actual result

`sourceNodes` hook is called before  `gatsby-transformer-json` finishes creating my `TopicJson` nodes.

### Environment

not relevant

**Comment by kimbaudi** [comment]
Also, if I change `gatsby-node.js` to the following:

```js
exports.sourceNodes = ({ getNodes }) => {
  console.log(`sourceNodes ${getNodes().map((node) => node.internal.type)}`)
}

exports.onCreateNode = ({ node }) => {
  console.log(`onCreateNode ${node.internal.type}`)
}
```

I get the following output:

```raw
success onPreBootstrap - 0.018s
success createSchemaCustomization - 0.002s
onCreateNode SitePage       
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode Site
onCreateNode SiteBuildMetadata
onCreateNode Directory
sourceNodes SitePage,SitePlugin,SitePlugin,SitePlugin,SitePlugin,SitePlugin,SitePlugin,SitePlugin,SitePlugin,SitePlugin,SitePlugin,SitePlugin,SitePlugin,SitePlugin,SitePlugin,SitePlugin,SitePlugin,SitePlugin,SitePlugin,SitePlugin,Site,SiteBuildMetadata,Directory,File
onCreateNode TopicJson
onCreateNode TopicJson
onCreateNode File
success Checking for changed pages - 0.002s
success source and transform nodes - 0.163s
success building schema - 0.449s
info Total nodes: 26, SitePage nodes: 1 (use --verbose for breakdown)
success createPages - 0.004s
success Checking for changed pages - 0.001s
onCreateNode SitePage
success createPagesStatefully - 0.045s
success update schema - 0.046s
success write out redirect data - 0.003s
success onPostBootstrap - 0.003s
```

which means `sourceNodes` is being called before all nodes are created. I was expecting `sourceNodes` to be called after all `onCreateNode` calls since the docs says `sourceNodes` _"will be called exactly once after all of your source plugins have finished creating nodes."_

---

[sourceNodes](https://www.gatsbyjs.com/docs/reference/config-files/gatsby-node/#sourceNodes)

> Extension point to tell plugins to source nodes. This API is called during the Gatsby bootstrap sequence. Source plugins use this hook to create nodes. This API is called exactly once per plugin (and once for your site’s gatsby-config.js file). If you define this hook in gatsby-node.js it will be called exactly once after all of your source plugins have finished creating nodes.

**Comment by kimbaudi** [comment]
Based on my observations, I think `sourceNodes` is an unreliable place to check for nodes created from source plugins like `gatsby-source-filesystem`. I was expecting `File` node and `TopicJson` nodes to be created from using `gatsby-source-filesystem` and `gatsby-transformer-json` before hooking into `sourceNodes`, but `File` and `TopicJson` nodes get created immediately after `sourceNodes`. 

`gatsby-config.js`

```js
const path = require(`path`)

module.exports = {
  plugins: [
    `gatsby-transformer-json`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `data`,
        path: path.resolve(__dirname, `./src/data/`),
      },
    },
  ],
}
```

Here is another output of console.log. Note that `sourceNodes` gets logged before `onCreateNode TopicJson` and `onCreateNode File`

```raw
onPreBootstrap
onCreateNode SitePage /dev-404-page/
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode SitePlugin
onCreateNode Site
onCreateNode SiteBuildMetadata
onCreateNode Directory
sourceNodes
onCreateNode TopicJson
onCreateNode TopicJson
onCreateNode File
createPages
onCreateNode SitePage /dev-404-page/
onCreatePage
onPostBootstrap
````

Here is the `gatsby-node.js` I used to console.log the output above:

```js
exports.onPreBootstrap = ({ reporter }) => reporter.warn('onPreBootstrap')

exports.onCreateNode = ({ reporter, node }) => {
  if (node.internal.type === 'SitePage') {
    reporter.warn(`onCreateNode ${node.internal.type} ${node.path}`)
  } else {
    reporter.warn(`onCreateNode ${node.internal.type}`)
  }
}

exports.sourceNodes = ({ reporter }) => reporter.warn('sourceNodes')

exports.createPages = ({ reporter }) => reporter.warn('createPages')

exports.onCreatePage = ({ reporter }) => reporter.warn('onCreatePage')

exports.onPostBootstrap = ({ reporter }) => reporter.warn('onPostBootstrap')
```

The strange thing is that I can modify `gatsby-config.js` by duplicating `gatsby-source-filesystem` with a different name to get `File` and `TopicJson` nodes in `sourceNodes`:

modified `gatsby-config.js` so that `sourceNodes` has access to `File` and `TopicJson` nodes

```js
const path = require(`path`)

module.exports = {
  plugins: [
    `gatsby-transformer-json`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `data`,
        path: path.resolve(__dirname, `./src/data/`),
      },
    },
    // need to duplicate filesystem source
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `data2`, // must be different name (not data)
        path: path.resolve(__dirname, `./src/data/`),
      },
    },
  ],
}
```

I guess `sourceNodes` is where nodes are usually created using `actions.createNode`, but not very reliable for getting created nodes using `getNodes`.

**Comment by KyleAMathews** [comment]
Generally speaking, there's not safe point to get all nodes as e.g. in development, source plugins can/will keep updating nodes based on changes to e.g. files they're watching or remote sources. If you want to do custom merging/transformations/etc. we suggest you create a custom type/field in the graphql layer https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization/

**Comment by KyleAMathews** [comment]
That being said, I'm surprised that `onCreateNode` is being called after `sourceNodes`
