### ISSUE TITLE
cannot test on virtual machine

### ISSUE THREAD

**Issue by jjbully** [gatsbyjs/gatsby#30350]
## Description

it cannot be tested on virtual machine while on mac parallel on port 8000 or 3000, while there is no problem on create-react-app on localhost:3000

### Steps to reproduce

follow this instruction to get the localhost working on parallel on mac
[https://paulpark.io/accessing-mac-localhost-from-parallels-windows-10/](https://paulpark.io/accessing-mac-localhost-from-parallels-windows-10/)

run `gatsby develop`

install this one parallel [https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/]

clone and run the this starter [https://github.com/gatsbyjs/gatsby-starter-hello-world]

open browser in parallel and use localmac:8000

### Expected result

What should happen?

can access the developed site

### Actual result

nothing shown and nothing is connected (while it works on create-react-app on localmac:3000 on paralell)

error message on chrome
"localmac refused to connect"

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.90
    Edge: 86.0.622.43
    Firefox: 85.0.2
    Safari: 14.0.1
  npmPackages:
    gatsby: ^3.0.1 => 3.0.1
  npmGlobalPackages:
    gatsby-cli: 2.14.0

**Comment by ascorbic** [comment]
Hi. Try running `gatsby develop -H 0.0.0.0`. That will make it listen on all interfaces.

**Comment by jjbully** [comment]
thank you, it works
