### ISSUE TITLE
gatsby-plugin-mdx: TOC broken with custom IDs

### ISSUE THREAD

**Issue by CodeAndWeb** [gatsbyjs/gatsby#30361]
## Description

I use `gatsby-remark-autolink-headers` with `enableCustomId: true` to
create headers with custom link targets:

    # Header {#header}
    ## SubHeader {#subheader}

The result is that the html code is produced as it should be: `{#header}` is removed,
the `id` is applied to the `<h1>`:

    <h1 id="header" style="position: relative;">
        <a href="#header" aria-label="header permalink" class="anchor before"></a>
        Header
    </h1>

BUT: The TOC is not using new IDs and headers:

```graphql
query MyQuery {
  allMdx {
    nodes {
      tableOfContents
    }
  }
}
```

```
{
  "data": {
    "allMdx": {
      "nodes": [
        {
          "tableOfContents": {
            "items": [
              {
                "url": "#header-header",                 <----- should be "#header"
                "title": "Header {#header}",             <----- should be "Header"
                "items": [
                  {
                    "url": "#subheader-subheader",       <----- should be "#subheader"
                    "title": "SubHeader {#subheader}"    <----- should be "SubHeader"
                  }
                ]
              }
            ]
          }
        }
      ]
    }
  },
  "extensions": {}
}
```
### Steps to reproduce

https://github.com/CodeAndWeb/gatsby-mdx-autoheader-bug

### Environment

  System:
    OS: macOS 11.2.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.21.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 86.0.1
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.0.1 => 3.0.1
    gatsby-plugin-mdx: ^2.1.0 => 2.1.0
    gatsby-remark-autolink-headers: ^3.1.0 => 3.1.0
    gatsby-source-filesystem: ^3.1.0 => 3.1.0

**Comment by CodeAndWeb** [comment]
Dear bot - I don't know why somebody told you to clean up items... but it seems that the one who set you up forgot to tell you how to distinguish between open items that have to be fixed (but nobody seems to care about them) and other stuff that you can close.

This is something that has to be fixed and is not to be closed.

**Comment by CodeAndWeb** [comment]
No. Not stale.
Needs to be fixed.

Is anybody ever looking at this issue?

**Comment by CodeAndWeb** [comment]
Updates?

**Comment by CodeAndWeb** [comment]
This is still an issue....

**Comment by LukeShu** [comment]
not stale

**Comment by LukeShu** [comment]
There seem to be 2 pieces to this.
Background: The TOC is generated from the `mdast` returned from `genMDX` in `utils/gen-mdx.js`.  That `genMDX` function returns both the MDX `mdast` and a processed HTML `body` (as well as a few other things).  For whatever reason, it actually instantiates 2 separate MDX compilers, one to spit out the AST and one to spit out the HTML.

So, the 2 pieces of the issue are:
1. The MDX compiler instance used to spit out the AST doesn't have `gatsbyRemarkPlugins` applied to it, just the vanilla `remarkPlugins`.
2. The `mdast` returned is the raw parse (`compiler.parse(file)`), before any transformer plugins have had a chance to run on it (`compiler.run(compiler.parse(file))`).
