### ISSUE TITLE
Automatic JSX runtime needs to be configured twice

### ISSUE THREAD

**Issue by aaronadamsCA** [gatsbyjs/gatsby#30373]
I've created an example monorepo that contains Gatsby sites and components in separate packages, and uses the new automatic JSX transform in React 17.

In Gatsby v3, I seem to need to configure the JSX transform automatic runtime twice, in `gatsby-node.js` and `.babelrc.js`. This seems incorrect.

### Steps to reproduce

Minimal reproduction: https://github.com/aaronadamsCA/gatsby-example-monorepo/tree/component-library/sites/theme-ui-example

If I remove the configuration in `gatsby-node.js`, building static HTML fails with `WebpackError: ReferenceError: React is not defined`:

<details>

```
$ gatsby build
success open and validate gatsby-configs - 0.045s
warn Plugin gatsby-plugin-tsconfig-paths is not compatible with your gatsby version 3.1.1 - It requires gatsby@~2.x.x
success load plugins - 0.139s
success onPreInit - 0.037s
success initialize cache - 0.010s
success copy gatsby files - 0.260s
success onPreBootstrap - 0.039s
success createSchemaCustomization - 0.011s
success Checking for changed pages - 0.002s
success source and transform nodes - 0.138s
success building schema - 0.432s
info Total nodes: 25, SitePage nodes: 1 (use --verbose for breakdown)
success createPages - 0.003s
success Checking for changed pages - 0.001s
success createPagesStatefully - 0.109s
success update schema - 0.120s
success onPreExtractQueries - 0.002s
success extract queries from components - 0.131s
success write out redirect data - 0.002s
success onPostBootstrap - 0.007s
info bootstrap finished - 5.000s
success run static queries - 0.050s - 1/1 19.91/s
success run page queries - 0.022s - 4/4 181.94/s
success write out requires - 0.021s
success Building production JavaScript and CSS bundles - 16.162s
success Rewriting compilation hashes - 0.004s
success Building HTML renderer - 4.812s
failed Building static HTML for pages - 0.266s

 ERROR #95313 

Building static HTML failed for path "/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


  4 |
  5 | export const Link: FC<{ to: string }> = (props) => (
> 6 |   <ThemedLink as={AsLink} variant="default" {...props} />
    |   ^
  7 | );
  8 |
  9 | const AsLink: FC<{ to: string }> = (props) => (


  WebpackError: ReferenceError: React is not defined
  
  - link.tsx:6 
    theme-ui-example/packages/components/src/link/link.tsx:6:3
  
  - extends.js:3 
    [theme-ui-example]/[@babel]/runtime/helpers/esm/extends.js:3:1
  
  - extends.js:9 
    [theme-ui-example]/[@babel]/runtime/helpers/esm/extends.js:9:1
  
  - extends.js:8 
    [theme-ui-example]/[@babel]/runtime/helpers/esm/extends.js:8:1
  
  - static-entry.js:263 
    theme-ui-example/.cache/static-entry.js:263:20
  


error Command failed with exit code 1.
```

</details>

If I remove the configuration in `babelrc.json`, ESLint fails to parse JavaScript files with `Parsing error: Support for the experimental syntax 'jsx' isn't currently enabled`. TypeScript files seem to be unaffected.

I would expect Gatsby and ESLint to be using the same Babel configuration.

### Notes

I created this example repository because I've found it very challenging to migrate my existing (private) Gatsby v2 monorepo to Gatsby v3. It uses mixed JS and TS, and everything works using `actions.setBabelPlugin` in `gatsby-node.js`.

In v3, since [`babel-preset-gatsby` now accepts `reactImportSource` which is passed to the underlying `@babel/preset-react` `importSource` field](https://www.gatsbyjs.com/docs/reference/release-notes/v3.0/#babel-preset-gatsby), I expected this to replace `actions.setBabelPlugin` in v3. It seems this may only be true for TypeScript components, and that JavaScript components still require the old-style Webpack configuration.

### Environment

```
  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 14.16.0 - /tmp/yarn--1616344297767-0.7405160842411349/node
    Yarn: 1.22.5 - /tmp/yarn--1616344297767-0.7405160842411349/yarn
    npm: 6.14.11 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
```

**Comment by aaronadamsCA** [comment]
I've updated this issue a couple of times with new findings.

So far:

- Don't remove the `"."` from `"babelrcRoots": [".", "packages/*", "sites/*"]`. My reading of the Babel docs says this shouldn't matter, since I don't have a `.babelrc.json` in the root. But when I remove it, I get errors.
- I think some of the difference in behaviour might be down to JS vs. TS files.

**Comment by aaronadamsCA** [comment]
Not stale

**Comment by aaronadamsCA** [comment]
Not stale!

**Comment by aaronadamsCA** [comment]
Not stale

**Comment by aaronadamsCA** [comment]
Not stale 🙃

**Comment by alexjsdev** [comment]
Did you figure anything out related to this? I feel like I'm having the same issue right now trying to upgrade gatsby to v3 from v2 within a monorepo setup as well. I'm getting `[BABEL]: Cannot find module '@babel/plugin-transform-react-jsx-source'` which I'd expect it not to be using since I configured babel in the gatsby site root to this config: 
`[
		  "babel-preset-gatsby",
		  {
			 "reactRuntime": "automatic",
			 "reactImportSource": "@emotion/react"
		  }
]`

can't figure this one out...

**Comment by aaronadamsCA** [comment]
@alexjsdev Here are the files from our current working JSX + TSX setup. I think these are all the key bits, but I could be wrong.

At this point I'm unsure which parts make the automatic runtime work in JSX vs. TSX vs. ESLint, so I'll just show everything and hope something helps you.

### Root settings

`/babel.config.json`

```json
{
  "babelrcRoots": [".", "packages/*"]
}
```

`/.eslintrc.cjs`

```js
module.exports = {
  root: true,
  parser: "@babel/eslint-parser",
  extends: [
    "eslint:recommended",
    "plugin:react/recommended",
    "prettier", // Disables conflicting rules in above configs
    "plugin:react-hooks/recommended",
    "plugin:eslint-comments/recommended",
    "plugin:import/recommended",
    "plugin:jsx-a11y/strict",
  ],
  parserOptions: {
    sourceType: "module",
  },
  env: {
    browser: true,
    es2020: true,
    node: true,
  },
  plugins: ["filename-rules", "simple-import-sort"],
  // rules: { redacted },
  overrides: [
    {
      // Lint all files with any of these valid extensions
      files: ["*.cjs", "*.js", "*.jsx", "*.mjs", "*.ts", "*.tsx"],
    },
    {
      files: ["packages/*/gatsby-browser.js"],
      env: {
        browser: true,
      },
      globals: {
        ___loader: false,
        ___emitter: false,
      },
    },
    {
      files: ["*.ts", "*.tsx"],
      extends: [
        "plugin:@typescript-eslint/recommended",
        "plugin:import/typescript",
      ],
      plugins: ["eslint-plugin-tsdoc"],
      // rules: { redacted },
    },
  ],
  settings: {
    react: {
      version: "detect",
    },
    "import/resolver": {
      node: {
        extensions: [".js", ".jsx", ".ts", ".tsx"],
      },
      alias: [["@reach/router", "@gatsbyjs/reach-router"]],
    },
  },
};
```

`/tsconfig.json`

```json
{
  "compilerOptions": {
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "incremental": true,
    "jsx": "preserve",
    "moduleResolution": "node",
    "noEmit": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "target": "ES2020"
  }
}
```

### Package settings

`/packages/*/.babelrc.json`

```json
{
  "presets": [
    [
      "babel-preset-gatsby",
      {
        "reactImportSource": "theme-ui",
        "reactRuntime": "automatic"
      }
    ]
  ]
}
```

`/packages/*/.eslintrc`

```
(empty file)
```

`/packages/*/gatsby-node.js`

```js
exports.onCreateBabelConfig = ({ actions }) => {
  actions.setBabelPlugin({
    name: "@babel/plugin-transform-react-jsx",
    options: {
      runtime: "automatic",
      importSource: "theme-ui",
    },
  });
};
```

`/packages/*/tsconfig.json`

```json
{
  "extends": "../../tsconfig.json",
  "include": ["./src/**/*"]
}
```
