### ISSUE TITLE
Gatsby Cloud System limit for number of file watchers

### ISSUE THREAD

**Issue by tnorlund** [gatsbyjs/gatsby#30372]
## Description

I've recently upgraded from v2 to v3.1. When I build using Gatsby Cloud, I get an error using styled icons.

'Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch `/usr/src/app/www/node_modules/@styled-icons/simple-icons/Geocaching`'

Not sure if this is the right repo to report this in.

**Comment by LekoArts** [comment]
For Gatsby Cloud support please reach out here: https://www.gatsbyjs.com/support/
