### ISSUE TITLE
Gatsby v3 / Theme UI 0.6 - Not Hot Reloading 

### ISSUE THREAD

**Issue by PaulieScanlon** [gatsbyjs/gatsby#30387]
Hi team, i've opened an issue on the theme-ui repo relating to hot reloads not firing when changes are made to a theme-ui theme object. Not sure if it's related to Gatsby or Theme UI or something else. Details in the issue below.

Ty in advance, you're all legends... keep up the good work! 

  Useful Links:
  - https://github.com/system-ui/theme-ui/issues/1595

**Comment by ehowey** [comment]
Just hopping in to confirm that I am seeing this same behaviour.

**Comment by PaulieScanlon** [comment]
I haven't tested this myself yet but word on the street is upgrading to Gatsby 3.2 fixes this bug.

**Comment by ehowey** [comment]
Hey Paul - I did some more testing. So I am seeing hot reloading inside components with the `sx` prop, but not seeing hot reloading from changes in the theme specification file.  A bit odd but I think it has to do with the scope and where the ThemeProvider is in the Gatsby stack of providers and components.

**Comment by PaulieScanlon** [comment]
@ehowey Hey mate thats interesting. I still haven't gotten around to investigating this yet. But that's good to know. I'll circle back here if I unearth anything further! 🕺

**Comment by LekoArts** [comment]
We've found the issue and a PR both to our repo and Theme UI's is under its way :)

**Comment by PaulieScanlon** [comment]
Lovely stuff! Thanks for looking into this! Great job!

**Comment by ehowey** [comment]
Thank you!

**Comment by PaulieScanlon** [comment]
Amazing! Thank you @LekoArts

**Comment by LekoArts** [comment]
Published in `gatsby@3.4.0-next.3`

**Comment by LekoArts** [comment]
Release in Theme UI: https://github.com/system-ui/theme-ui/pull/1659#issuecomment-822500195
