### ISSUE TITLE
there are unknown plugin options for "gatsby-source-wordpress": type.MediaItem.excludeFieldNames

### ISSUE THREAD

**Issue by erick-go** [gatsbyjs/gatsby#30399]
## Description
`Warning: there are unknown plugin options for "gatsby-source-wordpress": type.MediaItem.excludeFieldNames
Please open an issue at ghub.io/gatsby-source-wordpress if you believe this option is valid.`

Describe the issue that you're seeing.
I'm trying to make the MediaItem query as small as possible using `type: { MediaItem: { excludeFieldNames: [] } }`.
On a local `gatsby build` this works like it should, but Gatsby Cloud returned this message. 

### Steps to reproduce

add the following to your type object in gatsby-config and run a remote build.
```          MediaItem: {
            excludeFieldNames: [
              `ancestors`,
              `author`,
              `authorDatabaseId`,
              `authorId`,
              `caption`,
              `children`,
              `commentCount`,
              `commentStatus`,
              `comments`,
              `contentType`,
              `date`,
              `dateGmt`,
              `desiredSlug`,
              `enclosure`,
              `fileSize`,
              `guid`,
              `lastEditedBy`,
              `mediaDetails`,
              `mediaType`,
              `mimeType`,
              `modified`,
              `modifiedGmt`,
              `parent`,
              `parentDatabaseId`,
              `parentId`,
              `seo`,
              `sizes`,
              `status`,
              `template`,
            ],
```

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

No warning in the console and a reduced query. tbh, I'm not sure how to check if the generated query is not reduced or not.

```
  System:
    OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 15.8.0 - ~/.nvm/versions/node/v15.8.0/bin/node
    npm: 7.5.4 - ~/.nvm/versions/node/v15.8.0/bin/npm
  Browsers:
    Chrome: 88.0.4324.150
    Firefox: 86.0
  npmPackages:
    gatsby: ^3.1.1 => 3.1.1 
    gatsby-cli: ^3.1.0 => 3.1.0 
    gatsby-plugin-advanced-sitemap: ^1.5.6 => 1.6.0 
    gatsby-plugin-algolia: ^0.17.0 => 0.17.0 
    gatsby-plugin-algolia-search: ^0.5.7 => 0.5.7 
    gatsby-plugin-eslint: ^3.0.0 => 3.0.0 
    gatsby-plugin-gdpr-cookies: ^1.0.10 => 1.0.14 
    gatsby-plugin-google-adsense: ^1.1.3 => 1.1.3 
    gatsby-plugin-google-fonts-v2: 0.0.6 => 0.0.6 
    gatsby-plugin-google-tagmanager: ^3.1.0 => 3.1.0 
    gatsby-plugin-image: ^1.1.1 => 1.1.1 
    gatsby-plugin-manifest: ^3.1.0 => 3.1.0 
    gatsby-plugin-meta-redirect: ^1.1.1 => 1.1.1 
    gatsby-plugin-netlify: ^3.1.0 => 3.1.0 
    gatsby-plugin-offline: ^4.1.0 => 4.1.0 
    gatsby-plugin-preconnect: ^1.1.54 => 1.2.0 
    gatsby-plugin-prettier-eslint: ^1.0.4 => 1.0.4 
    gatsby-plugin-react-helmet: ^4.1.0 => 4.1.0 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-sass: ^4.1.0 => 4.1.0 
    gatsby-plugin-sharp: ^3.1.1 => 3.1.1 
    gatsby-plugin-smoothscroll: ^1.2.0 => 1.2.0 
    gatsby-plugin-styled-components: ^4.1.0 => 4.1.0 
    gatsby-plugin-stylelint: ^3.2.0 => 3.2.0 
    gatsby-source-filesystem: ^3.1.0 => 3.1.0 
    gatsby-source-graphql: ^3.1.0 => 3.1.0 
    gatsby-source-wordpress: ^5.1.0 => 5.1.0 
    gatsby-telemetry: ^2.1.0 => 2.1.0 
    gatsby-transformer-sharp: ^3.1.0 => 3.1.0 
  npmGlobalPackages:
    gatsby-cli: 3.1.0
```

**Comment by TylerBarnes** [comment]
Hi @erick-go , thanks for opening this issue. Can you share your Gatsby Cloud site dashboard URL or otherwise a reproduction repo?

**Comment by erick-go** [comment]
https://www.gatsbyjs.com/dashboard/a05a6e28-9f60-4904-bb69-a16145d09e17/sites/bdbddfbe-74b1-4aec-b7f7-f1393922646d

I've also given you acces to my repo

Let me know if you need anything else

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!

**Comment by TylerBarnes** [comment]
Fixed via https://github.com/gatsbyjs/gatsby/pull/37062
