### ISSUE TITLE
[gatsby-plugin-image]: Image Regex Breaking Shopify Src URLs

### ISSUE THREAD

**Issue by iamkratos** [gatsbyjs/gatsby#30427]
I've got a Shopify integration setup with with the newest Gatsby Shopify package. When I try to load my product images on my collection pages, all of the Shopify cdn urls are appending undefined as a param, and image urls are being broken. It looks like a regex in Gatsby Plugin Image is distorting the url, as the url goes from 

```
 "originalSrc": https://cdn.shopify.com/s/files/1/2119/7099/products/Full_Color_Queen_-_Front.jpg?v=1615842257"
```

to

https://cdn.shopify_250x375_crop_center.com/s/files/1/2119/7099/products/Full_Color_Queen_-_Front.jpg?undefined

Would appreciate any suggestions on resolving this 🙏

**Comment by LekoArts** [comment]
Please create an issue at https://github.com/gatsbyjs/gatsby-source-shopify-experimental/issues. Thanks!
