### ISSUE TITLE
[gatsby-plugin-image@1.2.0-next.1] Images not rendering in certain browsers

### ISSUE THREAD

**Issue by rossneilson** [gatsbyjs/gatsby#30423]
## Description

I updated to gatsby-plugin-image 1.2.0-next.1 due to a bug when replacing images in the current stable version fixed in PR #30221. This fixed the issue I had previously but this version seems to have another issue. 

Unfortunately it seems there is a bug where images are not rendered in certain browsers.

Seems to work in brave (89.0.4389.72) and firefox developer edition (87.0b9) but not chrome (91.0.4449.6) or safari (14.0.3).

Also it seems fine on all browsers in develop but when building and serving the issue occurs.

### Steps to reproduce

1. Create gatsby project
`gatsby new gatsby-starter-default https://github.com/gatsbyjs/gatsby-starter-default`
2. Update gatsby-plugin-image to 1.2.0-next.1
`"gatsby-plugin-image": "1.2.0-next.1"`
3. Run gatsby build
4. Run gatsby serve

### Expected result

Spaceman image should be loaded on all browsers

### Actual result

Spaceman does not get rendered

![Chrome example](https://user-images.githubusercontent.com/39137239/112160295-ede45a00-8be1-11eb-94d0-2e74fa597547.png)

However is downloaded in network tab

![Network tab](https://user-images.githubusercontent.com/39137239/112160454-15d3bd80-8be2-11eb-93bd-aad8ba259d41.png)

### Environment

`System:
    OS: macOS 11.2.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    npm: 6.14.11 - /usr/local/bin/npm
  Languages:
    Python: 3.9.2
  Browsers:
    Chrome: 91.0.4449.6
    Firefox: 62.0.2
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.1.1 => 3.1.1
    gatsby-plugin-gatsby-cloud: ^2.1.0 => 2.1.0
    gatsby-plugin-image: 1.2.0-next.1 => 1.2.0-next.1
    gatsby-plugin-manifest: ^3.1.0 => 3.1.0
    gatsby-plugin-offline: ^4.1.0 => 4.1.0
    gatsby-plugin-react-helmet: ^4.1.0 => 4.1.0
    gatsby-plugin-sharp: ^3.1.1 => 3.1.1
    gatsby-source-filesystem: ^3.1.0 => 3.1.0
    gatsby-transformer-sharp: ^3.1.0 => 3.1.0
  npmGlobalPackages:
    gatsby: 2.20.35`

**Comment by ascorbic** [comment]
Hi @rossneilson 
Thanks for the report. I can't reproduce this in Chrome 89 (which will be why this wasn't caught by Cypress tests) but can in Safari. I'll look at this today. Can you try it in Chrome stable and see if you can reproduce it there too?

**Comment by rossneilson** [comment]
Sure, looks like it works fine in chrome 89 which would explain why it works in brave (chromium 89).
Also, it seems to be working in chrome canary 91.0.4459.0
So it may only be safari (desktop+ios) that has this issue.
I have gatsby-plugin-image version 1.1.1 deployed elsewhere also and it works fine on all browsers.

**Comment by ascorbic** [comment]
The problem is related to lazy loading, so that would make sense as Safari doesn't support native lazy loading so we roll our own using IntersectionObserver
