### ISSUE TITLE
Generated site with 100 000 pages with data from BD and after delete old and add new 2000 rows in BD, make rebuild but in dir public have 100 000 + pages

### ISSUE THREAD

**Issue by nuxtdev** [gatsbyjs/gatsby#30433]
## Description
Generated site with 100 000 pages with data from BD and after delete old and add new 2000 rows in BD, make rebuild (GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true gatsby build --log-pages
),  but in dir public have 100 000 + pages not only current 2000.

And 1 minute is long for one page from 2000 rows in BD. 

It work not how is neeed.

Need to store all pages where an row from bd is used and after to indicate whar row is updated (in code when make an api call to update db row). And after to recreate that pages (not to read all pages into graphql and chekc for modification, how I supposed it now work)!!!

And that page need to put in some list and to make one per time (or in paralel), not 1000 in same time like in nuxt SSR+swr cache, because it not found cache and make new page and when cache will be ready 1000 or more request try to make html for page, and server go down. 

Is a bool shit all that SSR/SSG! 
Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

success open and validate gatsby-configs - 0.154s
success load plugins - 1.705s
success onPreInit - 0.128s
success initialize cache - 0.016s
success copy gatsby files - 0.345s
success onPreBootstrap - 0.041s
success createSchemaCustomization - 0.024s
success Checking for changed pages - 0.003s
success source and transform nodes - 1.921s
success building schema - 1.161s
info Total nodes: 2221, SitePage nodes: 1 (use --verbose for breakdown)
success createPages - 0.007s
success Checking for changed pages - 0.002s
success createPagesStatefully - 7.171s
success Cleaning up stale page-data - 7.952s
success update schema - 0.290s
success onPreExtractQueries - 0.003s
success extract queries from components - 3.860s
success write out redirect data - 0.008s
success Build manifest and related icons - 0.271s
success onPostBootstrap - 0.286s
info bootstrap finished - 34.134s
success run page queries - 0.194s - 2/2 10.33/s
success write out requires - 0.061s
success Building production JavaScript and CSS bundles - 18.801s
success Building HTML renderer - 3.790s
success Building static HTML for pages - 0.401s - 2/2 4.99/s
success onPostBuild - 0.003s
info Done building in 58.28607526 sec
info Built pages:
Updated page: /
Updated page: /mysql-product-113438/

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by LekoArts** [comment]
Sorry, but I don’t understand what you are trying to tell us. Please use your existing discussion for that: https://github.com/gatsbyjs/gatsby/discussions/30381
