### ISSUE TITLE
How to use "useStaticQuery" in gatsby-ssr.js?

### ISSUE THREAD

**Issue by crazydev901** [gatsbyjs/gatsby#30458]
Hi,

I tried using graphql query in gatsby-ssr.js. but I'm getting an error. Below is the error message..
> Generating SSR bundle failed
Can't resolve 'public/page-data/sq/d/2150987292.json' in '/home/xxx/0Project/ask-p2/gatsby-emulsify'
If you're trying to use a package make sure that 'public/page-data/sq/d/2150987292.json' is installed. If you're trying to use a local file make sure that the path is correct.
My code in `gatsby-ssr.js`.
```
export const replaceRenderer = () => {
  const data = useStaticQuery(graphql`
    query {
      site {
        siteMetadata {
          title
        }
      }
    }
  `);
  const myHTML = renderToString(<h1>{data.siteMetadata.site.title}</h1>);
  console.log(myHTML);
}
```

**Comment by crazydev901** [comment]
Hi @LekoArts, is there any solution for the issue?

**Comment by LekoArts** [comment]
GitHub seems to have issues with porting this issue over to Discussion. For questions please create a discussion here: https://github.com/gatsbyjs/gatsby/discussions/categories/help
Thanks

**Comment by crazydev901** [comment]
> GitHub seems to have issues with porting this issue over to Discussion. For questions please create a discussion here: https://github.com/gatsbyjs/gatsby/discussions/categories/help
> Thanks

Thanks

**Comment by crazydev901** [comment]
I opened a new discussion - https://github.com/gatsbyjs/gatsby/discussions/30465
