### ISSUE TITLE
Error: Cannot find module 'nan' when run "gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world"

### ISSUE THREAD

**Issue by shrekuu** [gatsbyjs/gatsby#30452]
## Description

I just ran `npm install -g gatsby-cli`, then I run
`gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world`

It shows: 

![image](https://user-images.githubusercontent.com/3136026/112455444-afdb6780-8d94-11eb-9318-80ba62a921c7.png)

However it did not stop. It ended successfully like this:

![image](https://user-images.githubusercontent.com/3136026/112455786-0183f200-8d95-11eb-979a-5b6310ca7291.png)

### Steps to reproduce

Run `npm install -g gatsby-cli`
then run `gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world`

### Expected result

Run without error.

### Actual result

Has error.

### Environment

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.0/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmGlobalPackages:
    gatsby-cli: 3.1.0

**Comment by LekoArts** [comment]
I followed your reproduction steps and unfortunately I don't see this behavior. Please make sure that you installed [node-gyp](https://github.com/nodejs/node-gyp) correctly. The only other issues I could find quickly were:

- https://github.com/fsevents/fsevents/issues/320
- https://github.com/Tzahi12345/YoutubeDL-Material/issues/127

They use `chokidar` on version `^2.1.8` which uses the v1 of fsevents.

Can you try changing your default package manager to yarn and try it again?
https://www.gatsbyjs.com/docs/reference/gatsby-cli/#how-to-change-your-default-package-manager-for-your-next-project

**Comment by shrekuu** [comment]
@LekoArts Yay! I swithed to yarn it worked without error. I do prefer yarn. I think it would be great to install 'nan' locally if it is not available in users system. :D  Thanks.
