### ISSUE TITLE
Automatic file validation for components in src/pages

### ISSUE THREAD

**Issue by calcsam** [gatsbyjs/gatsby#3045]
Add regex validation to make sure files in `src/pages` export React components. Throw error otherwise. Programmatically enforce language in the docs: https://github.com/gatsbyjs/gatsby/pull/3011

A cheap way of doing this is to make sure files contain at least two statements:

(1) an uppercase `React`
(2) `export default` or `module.exports`

**Comment by benjaminhoffman** [comment]
I believe they can export a string too and still be valid.

**Comment by ppatel221** [comment]
Hey if no one is assigned to this, can I take over?

**Comment by benjaminhoffman** [comment]
@ppatel221 sure go ahead!  be sure to update this issue and/or reference it in your PR as you make progress

**Comment by calcsam** [comment]
thanks @ppatel221!

**Comment by salmanmanekia** [comment]
@calcsam : If @ppatel221 isnt planning to do this, I would like to give it a shot

**Comment by salmanmanekia** [comment]
Thanks @benjaminhoffman. I will start with this. In the meanwhile can you please explain what do you meant by 

> 'I believe they can export a string too and still be valid.'

**Comment by benjaminhoffman** [comment]
My apologies, I may have been mistaken.  The official error I get is `A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.`

So I guess you want to check for either a react element or `null`.

@calcsam may know where to start looking to fix this.

**Comment by salmanmanekia** [comment]
Closed with [#3881](https://github.com/gatsbyjs/gatsby/pull/3881) and [#3949](https://github.com/gatsbyjs/gatsby/pull/3949)
