### ISSUE TITLE
gatsby-example-using-remark example is broken for TypeScript users

### ISSUE THREAD

**Issue by rossng** [gatsbyjs/gatsby#30475]
## Summary

I wanted to swap out components in my Markdown with custom ones. I was happy to see that there was already an example (in the `gatsby/examples/using-remark/` dir, also hosted at https://using-remark.gatsbyjs.org/custom-components/)

However, I quickly discovered that the following suggested snippet makes the TypeScript compiler very unhappy.

```
const renderAst = new rehypeReact({
  createElement: React.createElement,
  components: { "interactive-counter": Counter },
}).Compiler
```

After a bit of googling, I came across [this issue](https://github.com/rehypejs/rehype-react/issues/24) on the `rehype-react` repo. A quote from the library's author:

> Closing this because they are suggesting weird things and it’s not something we should fix.

Another user then goes on to suggest an alternative formulation of the code (which I have tested, and works).

### Motivation

TypeScript users who follow this official article will end up with something broken. I assume this is a fairly common use case, too.

## Steps to resolve this issue

Lift the suggested code from the issue linked above and use it in the Gatsby documentation.

**Comment by LekoArts** [comment]
The example is from 2018 so it's very possible that it's outdated at this point. A PR updating it is appreciated!

**Comment by nategiraudeau** [comment]
Can I work on this issue?

**Comment by rossng** [comment]
I'm too busy to write a PR atm, so go ahead!

**Comment by nategiraudeau** [comment]
Thanks.

**Comment by kartikPatidar** [comment]
Has the issue resolved with this PR.

**Comment by rossng** [comment]
I haven't directly tested, but it should be good now.

**Comment by kartikPatidar** [comment]
Great, Can you point we to some another issue to which I can contribute. I am just beginning with open source
