### ISSUE TITLE
[gatsby-transformer-javascript-frontmatter] gastby develop generates linter warning when defining a frontmatter

### ISSUE THREAD

**Issue by dotboris** [gatsbyjs/gatsby#30488]
## Description

When using `gatsby-transformer-javascript-frontmatter` to define a `frontmatter` pages in `src/pages/`, I get a linter warning when I run `gatsby develop`.

The warning in question is:

```
warn
/Users/dotboris/code/bugs/gatsby-js-frontmatter-lint-warning/src/pages/index.jsx
  4:1  warning  In page templates only a default export of a valid React component and the named export of a page query
 is allowed.
        All other named exports will cause Fast Refresh to not preserve local component state and do a full refresh.

        Please move your other named exports to another file. Also make sure that you only export page queries that use
 the "graphql" tag from "gatsby".
  limited-exports-page-templates

✖ 1 problem (0 errors, 1 warning)
```

This warning happens on pages where I define a frontmatter like so:

```js
export const frontmatter = { ... }
```

This warning makes sense if I'm not using `gatsby-transformer-javascript-frontmatter`. But since I am using this plugin, exporting a frontmatter is allowed and this warning makes no sense.

There are really two problems with this warning:

1.  It's super noisy. It's pretty big and it clutters the logs of my dev server.
2. It's going to incite developers in my project to start ignoring such warnings and eventually all warnings.

### Steps to reproduce

Minimal Reproduction:

- Github Repo: https://github.com/pmctire/bug-gatsby-js-frontmatter-linter-warning
- CodeSandbox: https://codesandbox.io/s/bug-gatsby-js-frontmatter-linter-warning-y02nj?file=/src/pages/index.jsx

Steps to reproduce:

1. Clone the repo or open the code sandbox
2. Install dependencies with `yarn`
3. Start the dev server with `yarn start`
4. Watch the console logs

### Expected result

I expect to see no warnings

### Actual result

I see the warning described above

### Environment

```
  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.12.0 - /var/folders/jq/mvhsh48s765_3m91z7p956fr0000gp/T/yarn--1616761874736-0.19342711233505283/node
    Yarn: 1.22.10 - /var/folders/jq/mvhsh48s765_3m91z7p956fr0000gp/T/yarn--1616761874736-0.19342711233505283/yarn
    npm: 7.6.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 87.0
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.1.2 => 3.1.2 
    gatsby-source-filesystem: ^3.1.0 => 3.1.0 
    gatsby-transformer-javascript-frontmatter: ^3.1.0 => 3.1.0 
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

Showing the warning here is working as intended and thus it's not a bug. As written on [Fast Refresh documentation](https://www.gatsbyjs.com/docs/reference/local-development/fast-refresh/):

> The file you’re editing might have other exports in addition to a React component. Gatsby includes an ESLint rule by default to warn against this pattern in pages: Page templates must only export one default export (the page) and query as a named export.

You can use a custom ESLint configuration if you don't want to use the default rules: https://www.gatsbyjs.com/docs/how-to/custom-configuration/eslint/

**Comment by dotboris** [comment]
I see so Fast Refresh won't work. That's fair enough.

This seems like a fairly significant caveat for `gatsby-transformer-javascript-frontmatter`. I think that it's documentation should clearly explain this caveat and explain how to silence this warning.

Speaking on silencing this warning, the documentation you linked to for the eslint configuration seems to be incorrect. In https://www.gatsbyjs.com/docs/how-to/custom-configuration/eslint/#disabling-eslint, it says:

> Creating an empty .eslintrc file at the root of your project will disable ESLint for your site. The empty file will disable the built-in eslint-loader because Gatsby assumes once you have an ESLint file you are in charge of linting.

I've tried creating an empty `.eslintrc` file in my minimal reproduction and the warning is still present.

With this my problem is still present. I still get this warning and I can't seem to turn it off.

**Comment by dotboris** [comment]
I've re-read the warning message and I'm starting to think that it can be improved. It says:

> In page templates only a default export of a valid React component and the named export of a page query is allowed.
>
> All other named exports will cause Fast Refresh to not preserve local component state and do a full refresh.
>
> Please move your other named exports to another file. Also make sure that you only export page queries that use the "graphql" tag from "gatsby".

It really says two things:

1. Fast Refresh will not work
2. Only the default export & page query export are allowed

The first point about Fast Refresh seems right to me. The second point about only those two exports being allowed doesn't really ring 100% true to me. In the context of `gatsby-transformer-javascript-frontmatter` is definitely "allowed".

I think that in general the phrasing about exports being "allowed" or not can be confusing. Perhaps this warning should be worded around the fact that Fast Refresh won't work. Instead of saying that only those two exports are allowed, it should perhaps say that Fast Refresh won't work if you have exports other than those two.
