### ISSUE TITLE
[examples/no-trailing-slashes] Throws in cache-dir/loader.js

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#3048]
Stumbled upon this in relation to a question on Twitter (https://twitter.com/benhoffman_/status/934497974553595909) – https://no-trailing-slashes.gatsbyjs.org/:

![image](https://user-images.githubusercontent.com/21834/33294523-4e6c6272-d3d1-11e7-9e3f-16d1754f8b24.png)

**Comment by mukealicious** [comment]
This is also happening on https://using-gatsby-image.gatsbyjs.org/

<img width="954" alt="screen shot 2017-11-27 at 3 30 16 pm" src="https://user-images.githubusercontent.com/1085841/33294977-ed501b08-d387-11e7-8b93-05c356de3afb.png">

**Comment by KyleAMathews** [comment]
Our runtime broke earlier — fixed it in https://github.com/gatsbyjs/gatsby/pull/3049
