### ISSUE TITLE
[gatsby-plugin-mdx] timeToRead returns NaN if wordCount in Mdx component is 0

### ISSUE THREAD

**Issue by JobenM** [gatsbyjs/gatsby#30490]
## Description
It's possible to have an mdx components without words for example we sometimes have embedded videos/ youtube.

So in this use case the `getCounts` function returns `words` property of `undefined` because the AST visitor never hits a word/paragraph. Thus the calculation for `timeToRead` (`Math.round(words / avgWPM)`) returns `NaN`. 

I propose we fallback to `0` for these properties returned in `getCounts` and then `timeToRead` can default to `1`.  

### Potential Fix
https://github.com/gatsbyjs/gatsby/pull/30489

**Comment by vladar** [comment]
Thank you for the report and PR! 👍 I am closing this issue now that the PR is merged.
