### ISSUE TITLE
exporting onRenderBody function from gatsby-browser.js results in error

### ISSUE THREAD

**Issue by smashercosmo** [gatsbyjs/gatsby#30500]
## Description

I'm getting the following error, when trying to use onRenderBody function

```
Your local gatsby-browser.js is using the API "onRenderBody" which is not a known API
```

### Steps to reproduce

try to export onRenderBody function from gatsby-browser.js and run the app

### Expected result

There shouldn't be an error, because it's a valid API

### Environment

```
  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.21.0 - /usr/local/opt/node@12/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/opt/node@12/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 78.8.0
    Safari: 14.0.3
  npmPackages:
    gatsby: 3.1.2 => 3.1.2
    gatsby-plugin-image: 1.1.2 => 1.1.2
    gatsby-plugin-manifest: 3.1.0 => 3.1.0
    gatsby-plugin-netlify-cms: 5.1.0 => 5.1.0
    gatsby-plugin-postcss: 4.1.0 => 4.1.0
    gatsby-plugin-react-helmet: 4.1.0 => 4.1.0
    gatsby-plugin-sharp: 3.1.2 => 3.1.2
    gatsby-plugin-sitemap: 3.1.0 => 3.1.0
    gatsby-plugin-svgr: 3.0.0-beta.0 => 3.0.0-beta.0
    gatsby-plugin-typescript: 3.1.0 => 3.1.0
    gatsby-source-filesystem: 3.1.0 => 3.1.0
    gatsby-transformer-json: 3.1.0 => 3.1.0
    gatsby-transformer-remark: 3.1.0 => 3.1.0
    gatsby-transformer-sharp: 3.1.0 => 3.1.0
    gatsby-transformer-yaml: 3.1.0 => 3.1.0
```

**Comment by vladar** [comment]
Thank you for opening this, @smashercosmo 

The `onRenderBody` API is only available in `gatsby-ssr.js`. It is not meant to be available in `gatsby-browser.js`. If you need to apply identical logic in both SSR and browser - use `wrapPageElement` or `wrapRootElement `.

See docs here: https://www.gatsbyjs.com/docs/reference/config-files/gatsby-ssr/

We're marking this issue as answered and closing it for now but please feel free to comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by smashercosmo** [comment]
Alright, thx for the explanation. For some reason I thought that client and server logic should always be duplicated.
