### ISSUE TITLE
[gatsby-plugin-image] Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by blackcater** [gatsbyjs/gatsby#30516]
## Description

I followed official tutorial, use `gatsby-plugin-image` for my own project.

### Steps to reproduce

```
git clone git@github.com:blackcater-labs/unisite.git --depth 1 unisite
cd unisite
git checkout bug-report/gatsby-1
yarn install
cd packages/unisite-utils && yarn run build && cd ../../
yarn dev:example:blog
```

> I used china NPM mirror instead of official NPM mirror. You may need change `.npmrc` and `.yarnrc` to use official NPM mirror.

### Expected result

What should happen?

### Actual result

![image](https://user-images.githubusercontent.com/9465551/112756464-deb54000-9017-11eb-88c5-57f75d7ba9ac.png)

### Environment

```
  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /var/folders/9k/7bn8m_0n1bn2sm9tzsmgt53w0000gn/T/yarn--1616943012841-0.1355411957722814/node
    Yarn: 1.22.10 - /var/folders/9k/7bn8m_0n1bn2sm9tzsmgt53w0000gn/T/yarn--1616943012841-0.1355411957722814/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.90
    Safari: 14.0.3
```

**Comment by maartenba** [comment]
+1

**Comment by ascorbic** [comment]
Hi. The error here is that babel is for some reason not transpiling the gatsby-browser file, which contains JSX. I tried to run your repro, but there seem to be issues with the monorepo: it can't find node_modules/@unisite/utils/lib/index.js

**Comment by blackcater** [comment]
> Hi. The error here is that babel is for some reason not transpiling the gatsby-browser file, which contains JSX. I tried to run your repro, but there seem to be issues with the monorepo: it can't find node_modules/@unisite/utils/lib/index.js

I'm sorry, it's my fault. I forgot a step before running app.

```
git clone git@github.com:blackcater-labs/unisite.git --depth 1 unisite
cd unisite
git checkout bug-report/gatsby-1
yarn install
cd packages/unisite-utils && yarn run build && cd ../../
yarn dev:example:blog
```

Please try again.

**Comment by blackcater** [comment]
I fixed this problem by using `gatsby-plugin-compile-es6-packages`.

```js
// gatsby-config.js
module.exports = (options) => {
	// ...
	return {
		// ...
		plugins: [
			// ...
			{
	          resolve: "gatsby-plugin-compile-es6-packages",
	          options: {
	            modules: ["gatsby-plugin-image"],
	          },
	        },
			// ...
		]
		// ...
	};
};
```
