### ISSUE TITLE
Question: Cache API Requests

### ISSUE THREAD

**Issue by marcobiedermann** [gatsbyjs/gatsby#3051]
Is there a way to cache external API requests and and make a call every XX minutes / hours / days?
Most APIs have a request limit so a better approach would be to fetch external data, store it in DB / file system and read from that. Via timer or cronjob the store should be updated.

**Comment by calcsam** [comment]
We think that's super important! In Gatsby already does this. It fetches all data necessary at build-time. The diagram on 
https://www.gatsbyjs.org/ illustrates this a bit. 

Of course, your underlying data, whether it lives in a CMS or wherever, may change over time. If you control the data source, you can use webhooks to trigger a re-build whenever data changes. If you don't, you can trigger periodic rebuilds to pull in new data.

![image](https://user-images.githubusercontent.com/4388699/33351906-ea90a15c-d45a-11e7-82b8-626a44a28de2.png)

**Comment by marcobiedermann** [comment]
@calcsam Ah, thank you. Cool, I will give it a try!
