### ISSUE TITLE
[gatsby-source-contentful] gatsby-plugin-image should be a peerDep

### ISSUE THREAD

**Issue by slk333** [gatsbyjs/gatsby#30519]
Hello!

On this documentation page:
https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-contentful#using-the-new-gatsby-image-plugin

The documentation currently states: 

> 1. Install the plugins:
> `npm install gatsby-plugin-image gatsby-plugin-sharp`

But `gatsby-plugin-image` is already a dependency of `gatsby-source-contentful`, and it works fine without the redundant install.

I didn't open a Pull Request because I'm not sure if this is intended or not.

Thanks

**Comment by LekoArts** [comment]
Hey, thanks for the issue! The docs are correct here, `gatsby-plugin-image` should be installed as it really should be a peerDependency not a direct dependency.

**Comment by axe312ger** [comment]
Good find, thats outdated. Readme should not contain the install for gatsby-plugin-sharp

**Comment by axe312ger** [comment]
@LekoArts no, we need it as a dependency in the plugin.

**Comment by LekoArts** [comment]
Why is that? @ascorbic documented it differently: https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/adding-gatsby-image-support/#other-considerations

**Comment by axe312ger** [comment]
It was required when implementing gatsby-plugin-image. Now it is not anymore ¯\_(ツ)_/¯ 

So yeah, can become a peer dep. Checked the code, all requires should check if the plugin is actually installed

**Comment by ascorbic** [comment]
@axe312ger The docs are correct: it should be a peerDependency and a devDependency.

**Comment by axe312ger** [comment]
@ascorbic  both? 🤔

**Comment by ascorbic** [comment]
You can probably skip the devDependency, as you're in the monorepo, but it's for whiel you're developing.

**Comment by axe312ger** [comment]
PR incoming
