### ISSUE TITLE
Error in function useStaticQuery

### ISSUE THREAD

**Issue by imckain** [gatsbyjs/gatsby#30518]
This issue randomly popped up:

`Error in function useStaticQuery in ./.cache/gatsby-browser-entry.js:77`

The error description:
"The result of this StaticQuery could not be fetched. This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues"

Refresh does not work.
Removing node_modules and reinstall does not work.

Seems like this an ongoing problem, and every thread on it is closed from what I've seen. I received no response when I commented on another closed thread about this issue.

**Comment by minimit** [comment]
Have you moved gatsby outside the `/src` folder? to me it gives error when I try it

**Comment by imckain** [comment]
Placing "Layout" in my /src worked. Thanks, minimit!

**Comment by lihsai0** [comment]
Same Issue.

I found changing `/.cache/gatsby-browser-entry.js` is helpful.

The changing is just add a space and delete it, then save the file.

I think I have all components in `/src`.

<img src="https://user-images.githubusercontent.com/17806506/113262786-96419f00-9303-11eb-9085-aa6dfb728c5c.png" alt="image" width="260" />
