### ISSUE TITLE
Update Tailwind install guide

### ISSUE THREAD

**Issue by AntonNiklasson** [gatsbyjs/gatsby#30537]
## Summary

I was going through the [Tailwind setup guide](https://www.gatsbyjs.com/docs/how-to/styling/tailwind-css/) and realised there's a few key things missing. Commands listed differes slightly from [Tailwind's own guide for integrating it with Gatsby](https://tailwindcss.com/docs/guides/gatsby).

Looks like `autoprefixer` is required for `npx tailwindcss init` to succeed.

I'm open for PR'ing this if it looks like something that should be fixed.

**Comment by LekoArts** [comment]
Sure, @AntonNiklasson go ahead with a PR aligning our docs to their docs :)

**Comment by AntonNiklasson** [comment]
Cool, I'll get on this during the wekk.
