### ISSUE TITLE
Fix code snippets on GraphQL Query Options Reference page

### ISSUE THREAD

**Issue by aminahbl** [gatsbyjs/gatsby#30540]
## Summary

All code snippets on the [GraphQL Query Options Reference page](https://www.gatsbyjs.com/docs/graphql-reference/) fail to load with the error:

```
failed to get pod ip for sitehostname: graphql-reference-1124782374.gtsb.io nil
```

![image](https://user-images.githubusercontent.com/74622040/112857698-06081d80-90a9-11eb-8480-16ab6290d8c6.png)

### Motivation

This should be fixed because graphql queries are pretty central to Gatsby sites and example code can be invaluable to those trying to learn what they need to, or can do.

## Steps to resolve this issue

It's hard to pin point exactly what's needed to resolve the issue, but as a start point I'd suggest looking at updating the iframe src links in https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/graphql-reference.md

**Comment by aminahbl** [comment]
As an extension of this, a similar problem is found at https://www.gatsbyjs.com/docs/graphql-reference/#dates with the error:

```
graphql-reference-1124782374.gtsb.io unexpectedly closed the connection.
```

**Comment by LekoArts** [comment]
Thanks, the issue has been resolved (try a hard refresh if it still doesn't work).
