### ISSUE TITLE
Possibility to delay page queries or run them sequentially?

### ISSUE THREAD

**Issue by kingkero** [gatsbyjs/gatsby#30574]
## Description

Sorry for abusing an issue, [but this discussion thread has gotten 0 answers yet](https://github.com/gatsbyjs/gatsby/discussions/30410):

> I have also [posted the question on StackOverflow](https://stackoverflow.com/questions/66750023/specify-page-query-execution-wait-between-them-in-gatsbyjs), the main question is:
> 
> Can we delay page queries or run them sequentially?
> 
> Background: We recently switched to [`gatsby-source-shopify-experimental`](https://github.com/gatsbyjs/gatsby-source-shopify-experimental), which uses Shopify's "Admin API" that has a [rate limit](https://shopify.dev/concepts/about-apis/rate-limits#graphql-admin-api-rate-limits).
> 
> Initially I've had most queries in _gatsby-node.js_ where I could just add sleep between calls and so far it was fine. But I found out that some more frequent changing data did not change on each build, presumably due to more heavy caching in the file. Then I switched to just querying the `id` in the _gatsby-node.js_ and run the more complex queries as page queries. However now, as they all run in parallel and I have no control, Gatsby Cloud often complains "Query takes too long", presumably due to the rate limit of the API and Gatsby making complex calls in parallel.
> 
> I presume that this could be solved by having the page queries run sequentially, preferrably I'd also add a short delay between them (1-2s).
> 
> I do know that this is quite localized and specific, however I presume that if more and more people use the new source plugin which has the new rate limit (current source shopify plugin uses Storefront API that has a different rate limit).

### Steps to reproduce

Actual query is

```
  query Product($id: String!, $nameRegExp: String!) {
    collection: shopifyCollection(id: { eq: $id }) {
      title
      description
      metafields {
        namespace
        key
        value
      }
      products {
        title
        variants {
          title
          price
          shopifyId
          availableForSale
          selectedOptions {
            name
            value
          }
          image {
            localFile {
              childImageSharp {
                gatsbyImageData(layout: FULL_WIDTH, placeholder: TRACED_SVG)
              }
            }
          }
        }
      }
    }
    accessories: allShopifyProduct(filter: { tags: { regex: $nameRegExp } }) {
      items: nodes {
        ...SingleAccessory
      }
    }
  }
```

Where `id` is a shopify ID, and `nameRegExp` is the result of `new RegExp(name, 'i').toString()`, while `name` is something like `Awesome Product`.

### Expected result

The API should not be hit with too many requests.

### Actual result

The API calls get slow / might even break.

### Environment

  System:
    OS: Linux 5.11 Arch Linux
    CPU: (8) x64 Intel(R) Xeon(R) CPU E3-1271 v3 @ 3.60GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.16.0 - /tmp/yarn--1617121512700-0.5809912538807589/node
    Yarn: 1.22.10 - /tmp/yarn--1617121512700-0.5809912538807589/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Languages:
    Python: 3.9.2 - /usr/bin/python
  Browsers:
    Firefox: 87.0
  npmPackages:
    gatsby: ^3.1.2 => 3.1.2 
    gatsby-background-image: ^1.5.0 => 1.5.0 
    gatsby-image: ^3.1.0 => 3.1.0 
    gatsby-plugin-gatsby-cloud: ^2.1.0 => 2.1.0 
    gatsby-plugin-google-tagmanager: ^3.1.0 => 3.1.0 
    gatsby-plugin-image: ^1.1.2 => 1.1.2 
    gatsby-plugin-layout: ^2.1.0 => 2.1.0 
    gatsby-plugin-manifest: ^3.1.0 => 3.1.0 
    gatsby-plugin-react-axe: ^0.5.0 => 0.5.0 
    gatsby-plugin-react-helmet: ^4.1.0 => 4.1.0 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-sharp: ^3.1.2 => 3.1.2 
    gatsby-plugin-styled-components: ^4.1.0 => 4.1.0 
    gatsby-remark-images: ^4.1.1 => 4.1.1 
    gatsby-remark-smartypants: ^3.1.0 => 3.1.0 
    gatsby-source-filesystem: ^3.1.0 => 3.1.0 
    gatsby-source-shopify-experimental-cachebust: kingkero/gatsby-source-shopify-experimental#cachebust => 1.12.6 
    gatsby-transformer-remark: ^3.1.0 => 3.1.0 
    gatsby-transformer-sharp: ^3.1.0 => 3.1.0 
  npmGlobalPackages:
    gatsby-cli: 2.19.1

**Comment by KyleAMathews** [comment]
hey — sorry to redirect you again but could you reopen this in https://github.com/gatsbyjs/gatsby-source-shopify-experimental/. Hitting rate limits would be something the source plugin needs to solve not Gatsby in general.
