### ISSUE TITLE
'Text content did not match' warning in Dev404Page with DEV_SSR or FAST_DEV flag enabled

### ISSUE THREAD

**Issue by kimbaudi** [gatsbyjs/gatsby#30575]
## rehydration issue in Dev404Page w/ DEV_SSR or FAST_DEV flag enabled throws 'Text content did not match' warning

If I enable DEV_SSR or FAST_DEV in develop and go to a non-existing page. I get this warning:

> Warning: Text content did not match. Server: "/dev-404-page/" Client: "/nowhere"

![Untitled](https://user-images.githubusercontent.com/1864092/113011598-cc79f580-912e-11eb-84b7-1be428297793.png)

The issue is that the server rendered text is `There's not a page yet at /dev-404-page/` and the client rendered text is `There's not a page yet at /nowhere` so obviously the text content did not match.

Looking into Gatsby's internals https://github.com/gatsbyjs/gatsby/blob/a55ffeb955b3a329190c605e0101ee6cdac83e21/packages/gatsby/src/internal-plugins/dev-404-page/raw_dev-404-page.js#L97

I can see that the it is rendering `location.pathname`

```jsx
  render() {
    const { pathname } = this.props.location

    return (
      <div>
        <h1>Gatsby.js development 404 page</h1>
        <p>
          {`There's not a page yet at `}
          <code>{pathname}</code>
        </p>
    )
```

It seems with `DEV_SSR` and/or `FAST_DEV` flags set to `true`, `location.pathname` initially has a value of `/dev-404-page/` and then has a value of `/nowhere`. 

To me, this indicates a rehydration issue with `Dev404Page` component. I think this can probably be fixed using a solution like https://www.joshwcomeau.com/react/the-perils-of-rehydration/#the-solution. I think I found a bug.

### Steps to reproduce

1. enable DEV_SSR and/or FAST_DEV in `gatsby-config.js`
2. run `gatsby develop`
3. navigate to a non-existent page

I've created a minimal repo at https://github.com/kimbaudi/dev404page-ssr-issue

### Expected result

What should happen?

navigating to non-existent page with DEV_SSR or FAST_DEV flags enabled shouldn't cause 'Text content did not match' warning

### Actual result

What happened.

navigating to non-existent page with DEV_SSR or FAST_DEV flags enabled causes 'Text content did not match' warning

### Environment

```raw
  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.7.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.63)
  npmPackages:
    gatsby: ^3.1.2 => 3.1.3
  npmGlobalPackages:
    gatsby-cli: 3.1.0
```

**Comment by kimbaudi** [comment]
Linking to SSR in Develop discussion: https://github.com/gatsbyjs/gatsby/discussions/28138#discussioncomment-548682

**Comment by KyleAMathews** [comment]
hey! This is a bug. Would you like to submit a PR with a solution like Josh suggests?

**Comment by kimbaudi** [comment]
Sure! I'll work on it shortly and submit a PR 😄

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by LekoArts** [comment]
I'll close this in favor of the discussion: https://github.com/gatsbyjs/gatsby/discussions/28138#discussioncomment-548682

For flags/experiments the umbrella discussion is the single place of information (bug reports/feature requests/comments).
