### ISSUE TITLE
actions.createNode sometimes doesn't return a promise

### ISSUE THREAD

**Issue by halkeye** [gatsbyjs/gatsby#30578]
## Description

The docs (https://www.gatsbyjs.com/docs/reference/config-files/actions/#createNode) say that it returns a promise though sometimes I'm finding its not. My latest debugging says its returning undefined, which leads me to believe its https://github.com/gatsbyjs/gatsby/blob/ecd4e4e7c619b9ec83f661d2606f5aeead9f85ea/packages/gatsby/src/redux/actions/public.js#L802

### Steps to reproduce

So far havn't gotten a consistent use case

~but code is https://github.com/jenkins-infra/plugin-site/blob/1d1fc73dd7147d9f94b63fdb2847b7edf7d470d5/plugins/gatsby-source-jenkinsplugins/utils.js#L119-L129~ Nope, put some debugging statements in there, and returning undefined doesn't fail to return a promise

I *think* it might be because I'm setting contentDigest to just the unique name, and not the actual digest. Is it returning undefined when createNode doesn't need to do anything?

### Expected result

Promise is returned (or docs updated to say it sometimes doesn't return one)

### Actual result

non promise is returned so can't be then'd

### Environment

```
  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Xeon(R) CPU           L5410  @ 2.33GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.9.0 - ~/.asdf/installs/nodejs/14.9.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.8 - ~/.asdf/installs/nodejs/14.9.0/bin/npm
  Languages:
    Python: 3.8.0 - /home/halkeye/.asdf/shims/python
  Browsers:
    Chrome: 88.0.4324.182
  npmPackages:
    gatsby: ^3.1.2 => 3.1.2
    gatsby-cli: ^3.1.0 => 3.1.0
    gatsby-plugin-algolia: ^0.17.0 => 0.17.0
    gatsby-plugin-canonical-urls: ^3.1.0 => 3.1.0
    gatsby-plugin-image: ^1.1.2 => 1.1.2
    gatsby-plugin-nprogress: ^3.1.0 => 3.1.0
    gatsby-plugin-postcss: ^4.1.0 => 4.1.0
    gatsby-plugin-react-helmet: ^4.1.0 => 4.1.0
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5
    gatsby-plugin-sharp: ^3.1.2 => 3.1.2
    gatsby-plugin-sitemap: ^3.1.0 => 3.1.0
    gatsby-source-custom-api: ^2.1.4 => 2.1.4
    gatsby-source-filesystem: ^3.1.0 => 3.1.0
    gatsby-transformer-sharp: ^3.1.0 => 3.1.0
```

**Comment by LekoArts** [comment]
Can you please show how you use `createNode`? You shouldn't need to await/then the `createNode` action, see: https://www.gatsbyjs.com/docs/creating-a-source-plugin/#sourcing-data-and-creating-nodes

**Comment by halkeye** [comment]
"see $largedocument"
Is createNode supposed to be sync call then?

As for how i'm calling it, currently its https://github.com/jenkins-infra/plugin-site/blob/1d1fc73dd7147d9f94b63fdb2847b7edf7d470d5/plugins/gatsby-source-jenkinsplugins/utils.js#L119-L129 but i'm working on refactoring. We originally had issues where loops were running too fast so we wanted to make sure everything was batched in groups of 100 entries, then awaited all the promises, then continued. Over time we added more and more things that we wanted to wait, so the promise chain got bigger. I've updated the code to shove all the promises into an array and wait for them all then goto the next segment. 

I did sorta narrow it down to that the the call to createNode will return a non promise if i provide .. well i think its new data but the content digest doesn't update. Or when i provide the exact same data. 

At the end of the loop i now `await Promise.all(promises.filter(Boolean))` and just make sure everything i wait for is a promise. It functions, but as i said, either the docs need updating or the code needs fixing.

**Comment by LekoArts** [comment]
I've linked to the "Sourcing data and creating nodes" heading :)

Ok, so we unpacked this a little bit and came to two conclusions:

1) The docs are correct and `createNode` returns a promise. However, they are confusing as awaiting it isn't necessary unless you use it inside the `createResolvers` API. You only ever need to await it if you download & create images, e.g. https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization/#feeding-remote-images-into-gatsby-image. Since you use the `sourceNodes` API there shouldn't be a need to await `createNode`. So we'll update the description of the return type
2) We should not return `undefined` but a "pre-resolved promise" so that the return type stays consistent

As for why it returns `undefined`:

When a node is only "touched" and not (re-)created. A node is touched when it already exists and nothing really changed -- then the node is "touched" so that it's not garbage collected.

You should create the `contentDigest` with the complete content of your node, not only the title. This way the garbage collection will work correctly.

**Comment by halkeye** [comment]
> You should create the `contentDigest` with the complete content of your node, not only the title. This way the garbage collection will work correctly.

yea I don't know why I didn't do it before. Its fixed on a local branch

> We should not return `undefined` but a "pre-resolved promise" so that the return type stays consistent

yea absolutely. I couldn't figure out where that was being returned so couldn't make a PR, so 👍 from me, that'll solve the issue.

**Comment by alvis** [comment]
I'd say returning a promise throughout is a better developer experience. Also, it's essential for those using `.then` syntax rather than `await`.

**Comment by halkeye** [comment]
> I'd say returning a promise throughout is a better developer experience. 

Why? Its not async work, it doesn't need to be a promise, but that also assumes that all the endpoints it calls are also not async.

> Also, it's essential for those using `.then` syntax rather than `await`. 
Both equally need a promise, you can't await on anything other than a promise

**Comment by alvis** [comment]
No! It's unresolved issue!
