### ISSUE TITLE
  WebpackError:ReferenceError: window is not defined styled components

### ISSUE THREAD

**Issue by dharanchit** [gatsbyjs/gatsby#30576]
locally production build is working as expected but while depolying the build is failing.
<img width="555" alt="Screenshot 2021-03-30 at 11 09 49 PM" src="https://user-images.githubusercontent.com/68214632/113032054-08ec3680-91ad-11eb-8118-aa03ae3d80ec.png">
Earlier styled components wasnt causing any issue. How do i fix this
Styled-components version 5.2.1

**Comment by jim-r-martin** [comment]
Just started seeing this same issue as well.

**Comment by tillhainbach** [comment]
I have the same issue even on local builds (`npm run build`) and fresh new Gatsby starters.

seems like for some reason the plugin is not compatible with style-components 5.2.2.

Steps to reproduce this error: 

```sh
gatsby new test-plugin-styled-component-build-error

cd test-plugin-styled-component-build-error

npm install gatsby-plugin-styled-components styled-components babel-plugin-styled-com    ponents

# add 'gatsby-plugin-styled-components' to gatsby-config.js

npm run build
```

**Comment by tillhainbach** [comment]
So it seems that in `styled-components@5.2.2` they expect a global `window` object to be present when `getNonce` is called [see commit](https://github.com/styled-components/styled-components/compare/v5.2.1...v5.2.2#diff-ebb57143a61517ec769ecda7c1fd903332e95c817bb128053a21017dfc5464d7).  `getNonce` is called by `ServerStyleSheet` [called here](https://github.com/gatsbyjs/gatsby/blob/gatsby-plugin-styled-components%404.2.0/packages/gatsby-plugin-styled-components/src/gatsby-ssr.js#L8) [and here](https://github.com/styled-components/styled-components/blob/28b4c28f1ebd1ea5a34717df2fe49634461285b1/packages/styled-components/src/models/ServerStyleSheet.js#L28).

So, my guess, if this plugin relied on `typepf __webpack_nonce__ !== 'undefined'` it should export `var window = { __webpack_nonce__: 'undefined' }`...

**Comment by dharanchit** [comment]
Resolved the issue by setting styled components version to 5.2.1 in package.jsom

**Comment by JackQ1** [comment]
Rollback "styled-components" to 5.2.1

**Comment by ADMARIl** [comment]
Confirming what has been said above and the bug is reproducible and rollback to 5.2.1 fixes it. [There is a similar issue](https://github.com/styled-components/styled-components/issues/3444) in the styled-components repo

**Comment by noahschumacher** [comment]
Gatsby 5.2.3 resolves the issue as well.
