### ISSUE TITLE
2.21.10 & 2.25.0 Error: The result of this StaticQuery could not be fetched.

### ISSUE THREAD

**Issue by edcylau** [gatsbyjs/gatsby#30582]
Hi I am using the gatsby starter gatsby-contentful-portfolio which originally using gatsby 2.21.10 until **I have encountered this error in the browser only, when the website is redirected from google or other search engine. The direct link to the website works normal without any issue.** I have looked over other tickets and update to 2.25.0 but still encounter the same error.

< ERROR message>
Error: The result of this StaticQuery could not be fetched.

This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues
    at d (gatsby-browser-entry.js:77)
    at s (96f1d2690bbf5f69cf9646faa21d71f647399e47-fc488cb0ef31bfe0db02.js:2)
    at Ki (react-dom.production.min.js:153)
    at vo (react-dom.production.min.js:261)
    at cu (react-dom.production.min.js:246)
    at ou (react-dom.production.min.js:246)
    at Zo (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Ql (react-dom.production.min.js:122)
Za @ react-dom.production.min.js:209

<Package.json>
"dependencies": {
    "@contentful/rich-text-plain-text-renderer": "^14.1.2",
    "@contentful/rich-text-react-renderer": "^14.1.2",
    "@contentful/rich-text-types": "^14.1.2",
    "@fullpage/react-fullpage": "^0.1.18",
    "classnames": "^2.2.6",
    "dotenv": "^8.2.0",
    "framer-motion": "^1.10.3",
    "gatsby": "^2.25.0",
    "gatsby-background-image": "^1.2.0",
    "gatsby-image": "^2.4.0",
    "gatsby-plugin-baidu-analytics": "^2.2.0",
    "gatsby-plugin-google-tagmanager": "^2.11.0",
    "gatsby-plugin-i18n": "^1.0.1",
    "gatsby-plugin-mailchimp": "^5.1.2",
    "gatsby-plugin-manifest": "^2.4.1",
    "gatsby-plugin-postcss": "^3.1.0",
    "gatsby-plugin-react-helmet": "^3.3.0",
    "gatsby-plugin-robots-txt": "^1.5.5",
    "gatsby-plugin-sharp": "^2.6.0",
    "gatsby-source-contentful": "^2.3.1",
    "gatsby-source-filesystem": "^2.3.0",
    "gatsby-transformer-remark": "^2.12.0",
    "gatsby-transformer-sharp": "^2.5.0",
    "gsap": "^3.5.1",
    "intersection-observer": "^0.11.0",
    "prop-types": "^15.7.2",
    "react": "^16.13.1",
    "react-device-detect": "^1.15.0",
    "react-dom": "^16.13.1",
    "react-helmet": "^5.2.1",
    "react-icons": "^3.10.0",
    "react-id-swiper": "^3.0.0",
    "react-truncate": "^2.4.0",
    "reactjs-popup": "^2.0.4",
    "sharp": "^0.26.3",
    "smooth-scroll": "^16.1.3",
    "stylelint-config-recommended": "^3.0.0",
    "swiper": "5.4.5",
    "tailwindcss-border-gradients": "^2.0.3",
    "three": "^0.122.0",
    "typeface-inter": "^3.12.0"
  },

**Comment by LekoArts** [comment]
Please refer to https://github.com/gatsbyjs/gatsby/issues/26563 or our documentation about caching: https://www.gatsbyjs.com/docs/caching/#page-data
