### ISSUE TITLE
[gatsby-image / gatsby-plugin-image] Image not showing on first load when arriving via gatsby-link

### ISSUE THREAD

**Issue by stiwwelll** [gatsbyjs/gatsby#30584]
## Description

Whenever I follow a link via <Link to='/foo'/> my images wrapped in a <Img/> tag aren't being displayed on first load. As soon as I hit refresh, the image shows. For some reason, the `<img/>`'s opacity is set to 0 and doesn't change.

First load:
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/13048811/113108273-1af9c380-9205-11eb-8ee3-4e6de150d0a3.png">

After refresh:
<img width="1364" alt="image" src="https://user-images.githubusercontent.com/13048811/113108474-53010680-9205-11eb-8272-6c5f18a4abd4.png">

I've tried solving the issue by implementing `gatsby-plugin-image` but there it's the same behavior.

### Steps to reproduce

Use a <Link /> helper that redirects to a page where you have an

### Expected result

The image should be displayed on the first load

### Actual result

The image is available in the DOM, but not being displayed since `opacity` is stuck at 0

### Environment

```
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.3 - ~/.asdf/installs/nodejs/14.15.3/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.9 - ~/.asdf/installs/nodejs/14.15.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 87.0
    Safari: 14.0.1
  npmPackages:
    gatsby: ^3.0.3 => 3.1.3
    gatsby-background-image: ^1.4.1 => 1.5.0
    gatsby-image: ^3.0.0 => 3.1.0
    gatsby-plugin-google-analytics: ^3.1.0 => 3.1.0
    gatsby-plugin-manifest: ^3.0.0 => 3.1.0
    gatsby-plugin-offline: ^4.0.0 => 4.1.0
    gatsby-plugin-polyfill-io: ^1.1.0 => 1.1.0
    gatsby-plugin-postcss: ^4.0.0 => 4.1.0
    gatsby-plugin-react-helmet: ^4.0.0 => 4.1.0
    gatsby-plugin-sass: ^4.0.2 => 4.1.0
    gatsby-plugin-sharp: ^3.0.0 => 3.1.3
    gatsby-plugin-sitemap: ^3.0.0 => 3.1.0
    gatsby-plugin-typography: ^3.0.0 => 3.1.0
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-remark-copy-linked-files: ^3.0.0 => 3.1.0
    gatsby-remark-images: ^4.0.0 => 4.1.1
    gatsby-remark-prismjs: ^4.0.0 => 4.1.0
    gatsby-remark-responsive-iframe: ^3.0.0 => 3.1.0
    gatsby-remark-smartypants: ^3.0.0 => 3.1.0
    gatsby-source-filesystem: ^3.0.0 => 3.1.0
    gatsby-source-sanity: ^6.0.5 => 7.0.0
    gatsby-transformer-remark: ^3.0.0 => 3.1.0
    gatsby-transformer-sharp: ^3.0.0 => 3.1.0
    gatsby-transformer-yaml: ^3.0.0 => 3.1.0
  npmGlobalPackages:
    gatsby-cli: 3.1.0
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by stiwwelll** [comment]
Hey @LekoArts . Thanks a lot for picking this up. I've solved it myself in the meantime by using [gatsby-plugin-sanity-image](https://github.com/coreyward/gatsby-plugin-sanity-image)

**Comment by KyleAMathews** [comment]
Something for people to double-check — `gatsby-plugin-image` is now a proper plugin so _must_ be added to your gatsby-config.js — it's a bit confusing as it'll seem to work mostly without it added but it seems lazy-loading bugs like this do occur w/o in your config as of the image code isn't loaded into the browser.
