### ISSUE TITLE
Traced SVG too large in size in V3 compared to V2

### ISSUE THREAD

**Issue by thandaanda** [gatsbyjs/gatsby#30598]
Hi Team,

Traced SVGs created using StaticImage and GatsbyImage are too large in size in V3 compared to traced SVGs created in V2.

## Description

Traced SVGs in V3 increases the page-data.json size. Earlier I thought it was only issue with GatsbyImage but I was able to reproduce the same with StaticImage.

### Steps to reproduce

I have created minimal repo which will easily give you the idea of difference in traced SVG size:

Gatsby V3 repo
https://github.com/thandaanda/gatsby-v3-image

Gatsby V2 repo
https://github.com/thandaanda/gatsby-v2-image

Inside both repos, at (src/images/), you would be able to see resultant SVGs.

### Expected result

What should happen?

Traced SVGs should remain low on size.

### V3 repo

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.3 - /c/Program Files/Python37/python
  Browsers:
    Chrome: 89.0.4389.90
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gatsby: ^3.1.2 => 3.1.2 
    gatsby-plugin-gatsby-cloud: ^2.1.0 => 2.1.0 
    gatsby-plugin-image: ^1.1.2 => 1.1.2 
    gatsby-plugin-manifest: ^3.1.0 => 3.1.0 
    gatsby-plugin-offline: ^4.1.0 => 4.1.0 
    gatsby-plugin-react-helmet: ^4.1.0 => 4.1.0 
    gatsby-plugin-sharp: ^3.1.2 => 3.1.2 
    gatsby-source-filesystem: ^3.1.0 => 3.1.0 
    gatsby-transformer-sharp: ^3.1.0 => 3.1.0 
  npmGlobalPackages:
    gatsby-cli: 3.0.0

### V2 repo

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.3 - /c/Program Files/Python37/python
  Browsers:
    Chrome: 89.0.4389.90
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gatsby: ^2.32.8 => 2.32.8 
    gatsby-image: ^2.11.0 => 2.11.0 
    gatsby-plugin-gatsby-cloud: ^1.0.2 => 1.0.2 
    gatsby-plugin-manifest: ^2.12.1 => 2.12.1 
    gatsby-plugin-offline: ^3.10.2 => 3.10.2 
    gatsby-plugin-react-helmet: ^3.10.0 => 3.10.0 
    gatsby-plugin-sharp: ^2.14.3 => 2.14.3 
    gatsby-source-filesystem: ^2.11.1 => 2.11.1 
    gatsby-transformer-sharp: ^2.12.0 => 2.12.0 
  npmGlobalPackages:
    gatsby-cli: 3.0.0

**Comment by thandaanda** [comment]
On further investigation, underlying temp image created before `potrace` runs are different in sizes.

Plugin: `gatsby-plugin-sharp`
Filename: `trace-svg.js`
Function name: `memoizedPrepareTraceSVGInputFile`

On V2, temp image size is - 13 KB
On V3, temp image size is - 193 KB

V2 JSON:
```
{
  "maxWidth": 1200,
  "grayscale": false,
  "jpegProgressive": true,
  "pngCompressionSpeed": 4,
  "duotone": false,
  "traceSVG": false,
  "toFormat": "jpg",
  "toFormatBase64": "",
  "cropFocus": 17,
  "fit": "cover",
  "background": "rgba(0,0,0,1)",
  "rotate": 0,
  "trim": false,
  "sizes": "",
  "srcSetBreakpoints": [],
  "pathPrefix": "",
  "quality": 50,
  "jpegQuality": null,
  "pngQuality": null,
  "webpQuality": null,
  "pngCompressionLevel": 9,
  "base64": true,
  "sizeByPixelDensity": false,
  "base64Width": 20,
  "width": 400
}
```


V3 JSON

```
{
  "layout": "fullWidth",
  "placeholder": "tracedSVG",
  "formats": [
    "",
    "webp"
  ],
  "breakpoints": [
    750,
    1080,
    1366,
    1920
  ],
  "width": 1920,
  "quality": 50,
  "jpegQuality": null,
  "pngQuality": null,
  "webpQuality": null,
  "jpegProgressive": true,
  "pngCompressionLevel": 9,
  "pngCompressionSpeed": 4,
  "base64": true,
  "grayscale": false,
  "duotone": false,
  "pathPrefix": "",
  "toFormat": "jpg",
  "toFormatBase64": "",
  "sizeByPixelDensity": false,
  "rotate": 0,
  "base64Width": 20,
  "maxWidth": 800
}
```

**Comment by thandaanda** [comment]
Please let me know if I have to provide any extra steps to reproduce this.

**Comment by rroslaniec** [comment]
In my business site I moved to blurred placeholder in case of this issue. I got many pictures (more than 20) on one site. With tracedSVG page-data.json was 4,8mb, with blurred - 28,1kb

**Comment by byronlanehill** [comment]
I am also having this issue. I have a website using Traced SVGs on the product page (about 20 images per product on average, 65 products) and we can't even get a build to pass on Netlify becuase it times out after 30 mins. The only change made to make the build go from ~10 mins without cache to >30 without cache was adding Traced SVGs. Are there any settings to make the files smaller and rendering faster?

**Comment by graysonhicks** [comment]
Gatsby 3.13 uses a new version of `sharp`, I wonder if that has improved this at all.

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
