### ISSUE TITLE
During production build the location object doesn't include pathPrefix if any

### ISSUE THREAD

**Issue by nadiia** [gatsbyjs/gatsby#3059]
Issue: A `location` object passed to a layout component doesn't include pathPrefix in it's `pathname` during the production build, `gatsby build --prefix-paths`, when there is a `pathPrefix` defined. 

Expected: The `location.pathname` includes `pathPrefix` and consistent in a production build and in a browser.

**Comment by KyleAMathews** [comment]
Oh hmmm you're right — would you like to put together a PR fixing this?

https://github.com/gatsbyjs/gatsby/blob/19e18a6e5a30b5147b57eb772fe776e9d3553a0c/packages/gatsby/cache-dir/static-entry.js#L88

https://www.gatsbyjs.org/docs/how-to-contribute/#contributing

We're using pathPrefix elsewhere in that file https://github.com/gatsbyjs/gatsby/blob/19e18a6e5a30b5147b57eb772fe776e9d3553a0c/packages/gatsby/cache-dir/static-entry.js#L43

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
