### ISSUE TITLE
Styles with id="gatsby-global-css" should be last included in the DOM in production

### ISSUE THREAD

**Issue by 7iomka** [gatsbyjs/gatsby#30608]
## Description

In development all my global styles & scss modules have greatest order over native gatsby styles from vendor plugins.
For example I use `gatsby-plugin-image` and that have own styles like `.gatsby-image-wrapper`

### Steps to reproduce

```jsx
import { StaticImage } from 'gatsby-plugin-image';
import * as styles from './file.modules.scss';
// ...

<StaticImage
      className={styles.imgLeft}
      placeholder="blurred"
      src="../../../assets/img/BooksSection/book.png"
      alt=""
    />
```

```scss
.imgLeft {
    position: absolute;
}
```

### Expected result
In development: Rendered layout have two classNames: `gatsby-image-wrapper` and `imgLeft` (from module) and that from module have greatest order, so image have absolute position

### Actual result

In production: `gatsby-image-wrapper` className has greatest order over `imgLeft` (from module) because it included AFTER all generated css stuff:
![Снимок экрана 2021-04-01 в 03 13 32](https://user-images.githubusercontent.com/18473137/113226246-5e514200-9298-11eb-952c-29f822322dab.png)

### Environment

  System:
    OS: macOS 10.15.7
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - ~/.npm-global/bin/yarn
    npm: 6.14.8 - ~/.npm-global/bin/npm
  Languages:
    Python: 3.8.3 - /Users/7iomka/anaconda3/bin/python
  Browsers:
    Chrome: 90.0.4430.51
    Firefox: 88.0
    Safari: 14.0
  npmPackages:
    gatsby: ^3.1.2 => 3.1.2
    gatsby-plugin-eslint: ^3.0.0 => 3.0.0
    gatsby-plugin-image: ^1.1.2 => 1.1.2
    gatsby-plugin-manifest: ^3.1.0 => 3.1.0
    gatsby-plugin-offline: ^4.1.0 => 4.1.0
    gatsby-plugin-purgecss: ^6.0.0 => 6.0.0
    gatsby-plugin-react-helmet: ^4.1.0 => 4.1.0
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-sass: ^4.1.0 => 4.1.0
    gatsby-plugin-sass-resources: ^2.0.0 => 2.0.0
    gatsby-plugin-sharp: ^3.1.2 => 3.1.2
    gatsby-source-filesystem: ^3.1.0 => 3.1.0
    gatsby-transformer-sharp: ^3.1.0 => 3.1.0
  npmGlobalPackages:
    gatsby-cli: 3.1.0

**Comment by ascorbic** [comment]
Relying on the order in this situation is always going to be fragile. Your best bet is to increase the specificity of the imgLeft class, either by adding an extra class or an id. Something like `:global(.gatsby-image-wrapper).imgLeft { ...` might work. Failing that, there's always `!important`

**Comment by javialon26** [comment]
I have the same problem. @leoselig I agree with you, the bug here is the different orders of the imports. In development and production, the order must be the same.

**Comment by leoselig** [comment]
not stale
