### ISSUE TITLE
File node failed to restore from cache. 

### ISSUE THREAD

**Issue by james-wfaa** [gatsbyjs/gatsby#30623]
## Description

Saw this message in Gatsby Cloud build:

gatsby-source-wordpress  File node failed to restore from cache. This is a bug in gatsby-source-wordpress. Please open an issue so we can help you out :)

### Steps to reproduce
https://www.gatsbyjs.com/dashboard/b2f73b3f-f6ef-4ea0-8af1-acc8ed20d662/sites/cc6bd5dd-6d1f-4920-950e-b3830bc4036e/builds/14c60af3-6ca3-4c85-829f-3dfcecc62956/details

I'm not sure exactly what is causing this but we have been having a bunch of issues with images in content 404ing. I imported a bunch of pages onto our site yesterday, and many of them ended up having bad file paths in them... I have 
production: {
          allow404Images: true,
        },

but it was still causing builds to timeout after like 90 minutes or so. I set most of those pages to draft status and the site has been building again, but there still seem to be some intermittent issues causing builds to fail. 

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    npm: 7.6.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 86.0.1
    Safari: 14.0.3
  npmPackages:
    gatsby: ^2.32.8 => 2.32.8 
    gatsby-background-image: ^1.4.1 => 1.4.1 
    gatsby-cli: ^2.19.2 => 2.19.2 
    gatsby-gravityforms-component: ^3.1.0 => 3.1.0 
    gatsby-image: ^2.11.0 => 2.11.0 
    gatsby-omni-font-loader: ^1.3.0 => 1.3.0 
    gatsby-plugin-algolia: ^0.16.3 => 0.16.3 
    gatsby-plugin-chakra-ui: ^0.1.4 => 0.1.4 
    gatsby-plugin-manifest: ^2.12.1 => 2.12.1 
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0 
    gatsby-plugin-offline: ^3.10.2 => 3.10.2 
    gatsby-plugin-react-helmet: ^3.10.0 => 3.10.0 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-sharp: ^2.14.3 => 2.14.3 
    gatsby-plugin-styled-components: ^3.10.0 => 3.10.0 
    gatsby-plugin-zendesk-configurable-chat: ^1.0.1 => 1.0.1 
    gatsby-source-filesystem: ^2.11.1 => 2.11.1 
    gatsby-source-graphql: ^2.14.0 => 2.14.0 
    gatsby-source-gravityforms: ^1.0.17 => 1.0.17 
    gatsby-source-wordpress: ^4.0.0 => 4.0.0 
    gatsby-transformer-sharp: ^2.12.0 => 2.12.0 
  npmGlobalPackages:
    gatsby-cli: 3.1.0

**Comment by veryspry** [comment]
Thanks for filing this issue and sorry for the delay, we've been busy :sweat_smile: 

Could you try updating `gatsby-source-wordpress`, `wpgatsby` and any other gatsby packages in your site's `package.json` (i.e. any package beginning with `gatsby-*`) and let us know if this problem persists after that?

It's likely that this issue has already been fixed in a recent wordpress source plugin or wp gatsby release and it is also worth noting that any of these updates will also rely on the latest Gatsby core updates well.
