### ISSUE TITLE
using dotenv in gatsby-config.js causes unsafe builtin method warning in gatsby 3.2.0

### ISSUE THREAD

**Issue by sherakama** [gatsbyjs/gatsby#30634]
## Description

Following the documentation on: https://www.gatsbyjs.com/docs/how-to/local-development/environment-variables/#server-side-nodejs

Using the snippet for using `dotenv` is causing the following build error

```
warn Unsafe builtin method was used, future builds will need to rebuild all pages
warn WebpackError: Unsafe builtin usage fs.readFileSync
    at abc/node_modules/dotenv/lib/main.js:96:1
    at abc/gatsby-config.js:3:1
```

### Steps to reproduce

Spin up a new 3.2.0 gatsby site
add dotenv snippet to gatsby-config.js as described in the documentation 
set up your environment var files
run `gatbsy build` 
See error

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

Build should happen with no errors and incremental builds happen.

### Actual result

Build outputs warning and rebuilds all pages each time.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
```
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 15.3.0 - ~/.nvm/versions/node/v15.3.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 7.6.1 - ~/.nvm/versions/node/v15.3.0/bin/npm
  Languages:
    Python: 3.7.6 - /usr/local/opt/python/libexec/bin/python
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 86.0.1
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.2.0 => 3.2.1 
    gatsby-plugin-anchor-links: ^1.2.0 => 1.2.1 
    gatsby-plugin-config: ^1.0.7 => 1.0.7 
    gatsby-plugin-manifest: ^3.2.0 => 3.2.0 
    gatsby-plugin-postcss: ^4.2.0 => 4.2.0 
    gatsby-plugin-react-helmet: ^4.2.0 => 4.2.0 
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5 
    gatsby-plugin-sitemap: ^3.2.0 => 3.2.0 
    gatsby-source-storyblok: ^2.0.0 => 2.0.0 
```

**Comment by LekoArts** [comment]
Hi!

I tried it in a project and it works fine:

![image](https://user-images.githubusercontent.com/16143594/113695343-091a9380-96d1-11eb-8789-f4dd70a87c07.png)

I don't see the warning when running `gatsby build`:

![image](https://user-images.githubusercontent.com/16143594/113695439-251e3500-96d1-11eb-8962-1d86e00c730e.png)

Please provide a [minimal reproduction][reproduction] and we'll be able to take another look.

[reproduction]: https://gatsby.dev/reproduction

**Comment by sherakama** [comment]
For what is it worth, I was having troubles with the `path` option and including a toggle between the dev/prod files. I don't seem to be able to reproduce this in a clean 3.x install so my issue must be in my stuff and my previous test. I'll continue to investigate and open a new issue if I can solidify the error. Sorry for "passing the buck" and thank you for the triage. 

```
const activeEnv = process.env.GATSBY_ACTIVE_ENV || process.env.NODE_ENV || "development"

console.log(`Using environment config: '${activeEnv}'`)

require("dotenv").config({
  path: `.env.${activeEnv}`,
})
```

**Comment by sherakama** [comment]
Found my error.

This warning cropped up when I imported the `gatsby-config.js` from a `page/test-page.js`. It was caused by the HTML build step and rightly so. I'll have to look for a different way to get those settings out of the config file for use.

**Comment by LekoArts** [comment]
You can put the information inside the `siteMetadata` and then query it.

```js
// in gatsby-config.js
module.exports = {
  siteMetadata: {
    your: 'info-here'
  }
}
```

**Comment by heyayush** [comment]
I faced this error as well and the reason was that dotenv was missing from dependencies in package.json
