### ISSUE TITLE
[gatsby-source-contentful] Error at fresh installment

### ISSUE THREAD

**Issue by cpannwitz** [gatsbyjs/gatsby#3064]
Hey. I'm currently trying to setup a basic gatsby site with the contentful-source-plugin.
Last week everything went pretty great, until that moment I had to show off my results and - bam - the whole thing went down in 5 minutes. I had no success in recreating and debugging.

Specifically gatsby-source-contentful errors out with the following:
`entryItemFields[foreignReference.name].push is not a function`

**Preconditions:**
node -v: `8.9.1`
gatsby-cli -v: `1.1.24`
gatsby-cource-contentful version: tried everyone from `1.3.20` to `1.3.28` 

**Steps to reproduce:**
1. npm i -g gatsby-cli
2. gatsby new testdir && cd testdir 
3. yarn add gatsby-source-contentful -S
4. Editing gatsby-config.js 
```
plugins: [
    {
      resolve: `gatsby-source-contentful`,
      options: {
        spaceId: `MY_CORRECT_SPACEID`,
        accessToken: `MY_CORRECT_ACCESS_TOKEN`,
      },
    },
    `gatsby-plugin-react-helmet`
  ],
```
5. (optionally) Editing gatsby-node.js and inserting/editing code from [example gatsby-contentful-site](https://github.com/gatsbyjs/gatsby/blob/master/examples/using-contentful/gatsby-node.js)

Thanks for any help!

**Comment by cpannwitz** [comment]
Seems to be related with Contentful itself.
Creating a new workspace without any content doesn't throw.

My Contentful content type structure: 
![https://preview.ibb.co/mTg4kG/Bildschirmfoto_2017_11_29_um_11_39_05.png](https://preview.ibb.co/mTg4kG/Bildschirmfoto_2017_11_29_um_11_39_05.png)

None of these fields are empty, no other Locale is enabled than the default (German).

**Comment by KyleAMathews** [comment]
This sounds like a genuine bug — would you like to put together a PR for this?

**Comment by cpannwitz** [comment]
I can try to find out, whats the problem, but I'm not sure if I know enough about this specific plugin or gatsby's way of handling data. So, can't promise anything 🤷‍♂️

**Comment by KyleAMathews** [comment]
Ok :-)

Start by adding console.logs around where the error is happening in the plugin — that's what I do to understand what type of data is triggering the error and how to handle it.

**Comment by Garbonauta** [comment]
I am encountering this issue as well. It seems to be tied to references. As cpannwitz described, the issue resolves itself when removing the references from the content altogether. It does not need to be removed from the content model. Note, in my case the reference was a "One Reference," and like cpannwitz, the reference was populated. 

Attaching my log.
[gatsby-reference-failure.log](https://github.com/gatsbyjs/gatsby/files/1529514/gatsby-reference-failure.log)

**Comment by cpannwitz** [comment]
I experienced the same, @Garbonauta .
At first, there was no error. Seems like contentful and/or the source-plugin needs some time to update the queried data.
Also I experienced - like you - that there was no way back, when the `References` field was introduced to the content model. It errors out afterwards, no matter what you change clientside or at contentful.

I tend to think, it has something to do with the "subscription" to data of the source-plugin to contentful. (as far as I know, you can simply query data from contentful, but also "subscribe" to it - api-wise)

**Comment by Garbonauta** [comment]
@cpannwitz I fully agree. I was able to circumvent the issue for about a day. I had to redo the Content models and content to get it to work. Luckily, I am at testing so this is no big deal. However, once I had the need to edit the content. The issue appeared again.

Like you I noticed the following:
- References are dropped altogether. For my edited contents the references were null. Untouched elements remained pristine. Note, gatsby did launch and did not error out on compile time
- The issue with compile time occurred when I deleted those invalid elements. It is like they are negotiating on the deleted element. I would have to recreate the deleted element for gatsby to compile.

At this point, I would like to know what do we do from here? What is the next step and I'll take it.

**Comment by mrtannerjones** [comment]
Same issue - references were the cause of the problem for me as well.

**Comment by Garbonauta** [comment]
I think I may be on the right track as to what is happening. It appears the plugin, gatsby-source-contentful, is pulling the right information from contentful. Note, I still have reason to suspect it is not forming data correctly.

I think what is happening, is that for example:
If you delete a piece of content in contentful. The data pulled from contentful does not match what is in Gatsby's redux store, cached in .cache/redux-state.json. Gatsby appears to use this cache file to compare expected information so it does not build the entire store every time you run gatsby develop. Thus, since the store data and pulled contentful data do not much, Gatsby crashes at compile time as it expects elements which are missing.
A quick fix for this is deleting the redux-state.json cache and rerunning gatsby. A new redux store is created and compilation appears to complete for the most part.

Now, I do not think this is the entire issue, I was still encountering problems where the recreated redux store did not include the missing reference types. Causing my code to crash at **runtime**. However, the issue appears to have fixed itself, not sure how, as I was doing some senseless manipulating of the redux-state.json file.

For now, everything is working for me. I do expect the issue to reappear as I am still changing content models and the content itself in contentful. I will continue to take a look and see what I can find.

**Comment by tomjowitt** [comment]
I also have this issue but it occurs at build time. Like other issues in this thread, it occurs when using contentful references and `createPages` in gatsby-node.js.

`Fetch Contentful data: 3785.866ms
error Plugin gatsby-source-contentful returned an error

  TypeError: entryItemFields[foreignReference.name].push is not a function
  
  - normalize.js:291 
    [site]/[gatsby-source-contentful]/normalize.js:291:52
  
  - Array.forEach
  
  - normalize.js:288 
    [site]/[gatsby-source-contentful]/normalize.js:288:27
  
  - Array.map
  
  - normalize.js:243 
    [site]/[gatsby-source-contentful]/normalize.js:243:30
  
  - Array.forEach
  
  - normalize.js:226 Object.exports.createContentTypeNodes
    [site]/[gatsby-source-contentful]/normalize.js:226:11
  
  - gatsby-node.js:179 
    [site]/[gatsby-source-contentful]/gatsby-node.js:179:25
  
  - Array.forEach
  
  - gatsby-node.js:178 _callee$
    [site]/[gatsby-source-contentful]/gatsby-node.js:178:30
`

**Comment by captainsask** [comment]
Just wondering if there had been any updates on this issue. I'm seeing the same thing as soon as I added references into my contentful data. It seems to be happening on build or develop. I tried using the previous method of deleting the redux-state.json in cache then rerunning but it doesn't seem to make a difference.

**Comment by pr1ntr** [comment]
Not sure if this helps but this happens to me when I have the following schema:

BUTTON
    toPage: PAGE


PAGE
    components: BUTTON


if Button has a page reference (any page, even ones that don't have it as a component) it will throw.

**Comment by Dakuan** [comment]
I'm also running into this

**Comment by ankesh7** [comment]
Same

**Comment by nugoo1** [comment]
Same.. It just stopped working after my latest commit. This keeps happening to every project when I work on it for too long. Does gatsby have issues with bigger builds? Seems like it ...!

**Comment by jshli** [comment]
I'm also running into this issue! I'm using a one-to-one reference, and as @cpannwitz mentions, as soon as I add a reference, it breaks - removing it removes the error. Cleaning out the cache doesn't appear to really have an effect.
The weird thing is it's inconsistent. It was breaking for me in development mode, and I just kept fiddling around with it all afternoon and suddenly, it just started working again (even though I'd done nothing of note), but when Netlify tries to build it, it breaks with the same error.

**Comment by Polyhistor** [comment]
Running into issues. definitely arising from the references

**Comment by nugoo1** [comment]
Hey, I has some issues and managed to fix them. I will update on this thread when I get home, no aceeas to code base atm..! Basically u have to import something to gatsby.config and if you're using any env variables, ads a GATSBY_ prefix to your environment variables

**Comment by nugoo1** [comment]
Add this to the top of gatsby-config.js

**Comment by nugoo1** [comment]
Add this to the top of gatsby-config.js

`require("dotenv").config({
  path: `.env.${process.env.NODE_ENV}`,
})
`

And this is how my gatsby-node.js looks:

`const path = require('path')

module.exports.createPages = async ({ graphql, actions }) => {
  const { createPage } = actions
  const blogTemplate = path.resolve("./src/templates/blog.js")
  const res = await graphql(`
    query {
      allContentfulBlogPost {
        edges {
          node {
            slug
          }
        }
      }
    }
  `)

  res.data.allContentfulBlogPost.edges.forEach(edge => {
    createPage({
      component: blogTemplate,
      path: `/blog/${edge.node.slug}`,
      context: {
        slug: edge.node.slug,
      },
    })
  })
}
`
My template for event page:

`
import React from "react"
import { graphql } from "gatsby"
import { documentToReactComponents } from "@contentful/rich-text-react-renderer"
import Img from "gatsby-image/withIEPolyfill"

export const query = graphql`
  query($slug: String!) {
    contentfulBlogPost(slug: { eq: $slug }) {
      title
      created(formatString: "dddd, MMMM Do YYYY")
      text {
        json
      }
      featuredImage {
        fluid(maxWidth: 600, maxHeight: 600) {
          aspectRatio
          src
          srcSet
          sizes
        }
      }
    }
    file(relativePath: { eq: "blog-post.jpg" }) {
      childImageSharp {
        fluid(maxWidth: 1920, quality: 100) {
          ...GatsbyImageSharpFluid
        }
      }
    }
  }
`

const Blog = props => {
  const options = {
    renderNode: {
      "embedded-asset-block": () => {
        return (
          <img
            alt={"alt"}
            src={props.data.contentfulBlogPost.featuredImage.fluid.src}
          />
        )
      },
    },
  }
  return (
    <Layout>
      <Slider
        sliderImage={props.data.file.childImageSharp.fluid}
        sliderTitle="Bloggin'"
        sliderSubtitle={props.data.contentfulBlogPost.title}        
        objectPosition="12% 50%"
      />
      <Heading 
          title={props.data.contentfulBlogPost.title}
          description={props.data.contentfulBlogPost.created}
      />
      <Img fluid={props.data.contentfulBlogPost.featuredImage.fluid} style={{margin:"0 auto", maxWidth:"80%", height:"100%", maxHeight:"50vh"}} objectFit="contain"/>
      <div className="blogTemplate">
        {documentToReactComponents(
          props.data.contentfulBlogPost.text.json,
          options
        )}
      </div>
      <Footer />
    </Layout>
  )
}

export default Blog

`

Good luck..

**Comment by wardpeet** [comment]
Can you check if `gatsby-source-contentful@2.1.35` fixed this issue. @frodd might think his fix could be related.

**Comment by ryudice** [comment]
Hi, I was having this issue and it was a circular reference, I disabled one side of the circular reference and it went away. You dont necesarrily have to remove it but you can just disable it in the response.

**Comment by omonk** [comment]
@wardpeet Thanks for that comment, that has fixed my issue. 

I did a bit of debugging but the source code for this plugin is quite complex to get into so I didn't get too far, enough to understand that there is some sort of issue going on with working out referencing.

We're now seeing errors about mismatched typings, everything builds fine in netlify but wondering if there is any advice on whether or not we should be actively trying to fix this:

```
warn There are conflicting field types in your data.
If you have explicitly defined a type for those fields, you can safely ignore this warning message.
Otherwise, Gatsby will omit those fields from the GraphQL schema.

If you know all field types in advance, the best strategy is to explicitly define them with the `createTypes` action,
and skip inference with the `@dontInfer` directive.
See https://www.gatsbyjs.org/docs/actions/#createTypes
ContentfulSpeciality.service___NODE:
 - type: [string]
   value: [ '01316be6-eee1-57ce-a626-e8c96379bc38' ]
 - type: string
   value: 'fbe50845-a07b-5c16-9d2c-1e9c482b7f65'
```

**Comment by aprilmintacpineda** [comment]
I'm having this problem on a fresh install of gatsby, I chose to add `gatsby-source-contentful` from the project initialization. I got version 8.12.0
