### ISSUE TITLE
problem on sorting with graphql

### ISSUE THREAD

**Issue by pinaudnico** [gatsbyjs/gatsby#3065]
I try something like this: 
allImageSharp (sort: {fields:id}){
  edges {
    node {
      sizes {
        src
        originalImg
        originalName
      }
    }
  }
}

it works on the graphiQL web window but when I put it in my gatsby it says 
GraphQLError: Argument "sort" has invalid value {fields: "id"}.
In field "fields": Expected type "ImageSharpConnectionSortByFieldsEnum", found "id".

Any ideas ? Thanks.

**Comment by pinaudnico** [comment]
Ok I've found it : 
allImageSharp (sort: {fields: [id]})
Enjoy...

**Comment by kristojorg** [comment]
Thank uuuuuuuu @pinaudnico

**Comment by dardub** [comment]
Is this documented anywhere? I couldn't find it even with the new docs search. :)

**Comment by pinaudnico** [comment]
I've found it experimenting...
