### ISSUE TITLE
Scroll position always gets restored

### ISSUE THREAD

**Issue by KonstantinSchuette** [gatsbyjs/gatsby#30667]
## Description

I want that, if I scroll down on my page, press reload, I get navigated back to the top of the page.

### Steps to reproduce

Repo: https://github.com/KonstantinSchuette/gatsby-scroll--reload-bug

gatsby-browser.js
```
export const shouldUpdateScroll = () => {
  window.scrollTo(0, 0)
  return [0, 0]
}
```

1. Clone and execute `gatsby develop`
2. Scroll down
3. Reload the page

### Expected result

After reloading the page the scroll position should be `X: 0, Y:0`

### Actual result

It always scrolls to the position before the reload

### Environment
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.68)
  npmPackages:
    gatsby: ^3.2.1 => 3.2.1 
  npmGlobalPackages:
    gatsby-cli: 3.2.0
```

**Comment by KyleAMathews** [comment]
This API is only called on client side navigation. Browsers control the scroll position on refresh. To control that, see this discussion https://stackoverflow.com/questions/3664381/force-page-scroll-position-to-top-at-page-refresh-in-html
