### ISSUE TITLE
[gatsby-plugin-image] onLoad prop

### ISSUE THREAD

**Issue by fcisio** [gatsbyjs/gatsby#30661]
## Summary

I was testing out `gatsby-plugin-image` and needed to do something `on load`.
I couldn't find the prop in the docs, but knew it existed on the previous `gatsyb-image`. I tried to use it on this plugin and it worked.

It should be added to the docs.

**Comment by LekoArts** [comment]
Hi!

At https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-plugin-image/#shared-props it says:

> The following props can be passed to both GatsbyImage and StaticImage. You may also use any valid <img> tag props, which are forwarded to the underlying <img> element.

As for React `onLoad` is a valid `<img />` tag so I think that should be covered. Thanks!
