### ISSUE TITLE
[gatsby-plugin-image] styles working for develop, but not for build

### ISSUE THREAD

**Issue by meganesu** [gatsbyjs/gatsby#30663]
## Description

I'm upgrading my site to use v3 and `gatsby-plugin-image`. I have an image in the header of my site that I want to render on large breakpoints but hide on smaller breakpoints.

### Steps to reproduce

1. Clone the [minimal reproduction repo](https://github.com/meganesu/repro-hidden-image-bug).
2. Confirm that the behavior works as expected for the develop server.
    - Run `gatsby develop` and open `localhost:8000`.
    - Resize your browser window to be less than 1400px wide. The Gatsby logo image in the header should disappear.
    - Resize your browser window to be more than 1400px wide. The Gatsby logo image should be visible in the header.
3. Confirm that the behavior doesn't work for the prod server.
    - Run `gatsby build && gatsby serve` and open `localhost:9000`. 
    - The Gatsby logo image will always display, even if you resize your browser window to be less than 1400px wide.

### Expected result

The styles for the Gatsby logo image should be consistent across `gatsby develop` and `gatsby build`.

### Actual result

The image styles work for `gatsby develop` but do not work for `gatsby build`.

Develop:

![The Gatsby image logo only shows for breakpoints larger than 1400px.](https://user-images.githubusercontent.com/3609989/113470646-0a676a00-940c-11eb-8768-8826a7f71052.gif)

Build:

![The Gatsby image logo shows for all breakpoint widths.](https://user-images.githubusercontent.com/3609989/113470640-04718900-940c-11eb-8af7-c0812f3be5ea.gif)

### Environment

```
  System:
    OS: macOS 11.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.4 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 87.0
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.2.1 => 3.2.1
    gatsby-plugin-image: ^1.2.0 => 1.2.0
    gatsby-plugin-sharp: ^3.2.0 => 3.2.0
    gatsby-source-filesystem: ^3.2.0 => 3.2.0
  npmGlobalPackages:
    gatsby-cli: 2.17.0
```

**Comment by ascorbic** [comment]
Hey! This is because the `gatsby-image-wrapper-constrained` class sets the display to inline-block. When I run it locally it fails for both develop and build. I'm guessing the ordering of classes is non-deterministic? Anyway, you can fix it by increasing the specificity of the selector. One way to do that with the CSS module is to add a reference to the gatsby-image-wrapper-constrained class too:

```css
:global(.gatsby-image-wrapper-constrained).image {
  display: none;
  width: 30px;
}

@media (min-width: 1400px) {
  :global(.gatsby-image-wrapper-constrained).image {
    display: block;
  }
}

```

**Comment by meganesu** [comment]
Hooray, that fixed it! Thanks @ascorbic! 👏
