### ISSUE TITLE
onLoad prop removed from html.js - works in other files

### ISSUE THREAD

**Issue by Primajin** [gatsbyjs/gatsby#30686]
## Description

When I use the `onLoad` prop in my central `html.js` file it is being removed, while in other files it works as expected.

### Steps to reproduce

Add a html.js file and add an element with onLoad attribute - for example a `<link onLoad="stuff">`

https://github.com/Primajin/gatsby-bug-onload/commit/9658ec939cf7a42787e67f760ce10e599fdb5e0b

![image](https://user-images.githubusercontent.com/1742115/113567791-8ed60a80-960f-11eb-88eb-4c7ccafd471d.png)
![image](https://user-images.githubusercontent.com/1742115/113567818-9a293600-960f-11eb-8f19-6ebb94672a94.png)

### Expected result

The element is rendered with the onLoad attribute.

### Actual result

The element is rendered without the onLoad attribute.

### Environment

```
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 AMD FX-8370 Eight-Core Processor
  Binaries:
    Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.3
  Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.19041.906.0), Chromium (89.0.774.68), ChromiumDev (--> [posh-monokai] Black       DarkBlue    DarkGreen
DarkCyan    DarkRed     DarkMagenta DarkYellow  Gray
--> [posh-monokai] DarkGray    Blue        Green       Cyan        Red         Magenta     Yellow      White)
  npmPackages:
    gatsby: ^3.2.1 => 3.2.1
```

**Comment by Primajin** [comment]
For example when I use [helm](https://github.com/nfl/react-helmet) I can push a link element with an unload attribute to the header with no problem

**Comment by LekoArts** [comment]
I think this is the same as: https://github.com/vercel/next.js/issues/12984

Especially relevant:

> onload is handled by React so I assume it's read as if it's a React event handler.

Also, as laid out in https://www.gatsbyjs.com/docs/custom-html/

> Customizing html.js is a workaround solution for when the use of the appropriate APIs is not available in gatsby-ssr.js. Consider using onRenderBody or onPreRenderHTML instead of the method above.

So I'd recommend using `setHeadComponents` to add your Stylesheets. A popular plugin is also doing this: https://github.com/codeAdrian/gatsby-omni-font-loader/blob/main/components/AsyncFonts.tsx

**Comment by Primajin** [comment]
Ahh thanks @LekoArts I'll try out the plugin - that looks promising. I'm very new to Gatsby so I didn't knew about `setHeadComponents` with gatsby-ssr.js - maybe it's worth making this removal behaviour more clear in the docs though - as it happens silently and thus it's unexpected.

**Comment by wybitnygracz** [comment]
> Customizing html.js is a workaround solution for when the use of the appropriate APIs is not available in gatsby-ssr.js. Consider using onRenderBody or onPreRenderHTML instead of the method above.

I tried this way, but then also "onload" is removed. 

```
 let hc = getHeadComponents();

    hc.forEach(el => {
        if (el.type === "style") {
            el.type = "link";
            el.props["href"] = el.props["data-href"];
            el.props["rel"] = "preload";
            el.props["as"] = "style";
            el.props["onload"]="this.onload=null;this.rel='stylesheet';"
            el.props['ANY_OTHER_TAG'] = 'works as expected'; 
        }
    })
```

**Comment by waldemar-krumrick** [comment]
A few days ago I was facing this issue. So, what if you really need to define the onload style attribute on html.js? You can do it this way:
1) Implement a temporal attribute name (a unique reserved name across your site) on **gatsby-ssr.js**. 
    So, instead of adding an attribute labeled "onload" just use "_force_onload_html_attribute".
    You can do the same with the value for this attribute. Instead of the javascript itself, you can add the value as "_force_onload_html_attribute_value". 

   CODE: 
  
```javascript
exports.onPreRenderHTML = ({ getHeadComponents, replaceHeadComponents }) => {     `
    getHeadComponents().forEach(el => 
    {
        if (el.type === 'style' && el.props['data-href']) 
        {
            el.type = 'link'
            el.props['href'] = el.props['data-href']
            el.props['rel'] = 'stylesheet'
            el.props['type'] = 'text/css'
            el.props['media'] = "print"
            el.props['_force_onload_html_attribute'] = "_force_onload_html_attribute_value"
            delete el.props['data-href']
            delete el.props['dangerouslySetInnerHTML']
        }
    })
}
``` 


2) Now the trick, is to look for every .html generated as part of the build and replacing those 2 reserved words with the values you want to. The place where we can implement this is on the **gatsby-node.js** using the **onPostBuild** API.

```javascript
//auxiliary function to find HTML files recursively.
const walk = (dir, filterExtension) => {
	try {
	  let results = [];
	  const list = fs.readdirSync(dir);
	  list.forEach(file => {
		file = path.join(dir, file);
		const stat = fs.statSync(file);
		if (stat && stat.isDirectory()) {
		  // Recurse into subdir
		  results = [...results, ...walk(file, filterExtension)];
		} else {
		  // Is an Html file.
		  if (file.endsWith(filterExtension)) {
			results.push(file);
		  }
		}
	  });
	  return results;
	} catch (error) {
	  console.error(`Error...`, error);
	}
  };
  
// this functions will replace the two temporal html attribute and value to the actual value.
  const edit = filePath => {
	const oldContent = fs.readFileSync(filePath, {encoding: 'utf8'});
	const regex = /_force_onload_html_attribute/;
	const replaceVal = 'onload';
	const newContent = oldContent.replace(regex, replaceVal);

	const regex2 = /_force_onload_html_attribute_value/;
	const replaceVal2 = "this.media='all'; this.onload = null"
	const newContent2 = newContent.replace(regex2, replaceVal2);
	fs.writeFileSync(filePath, newContent2, {encoding: 'utf-8'});
	console.log(`Edited file: ${filePath}`);
  };

// onPostBuild API
exports.onPostBuild = async ({_,reporter},  pluginOptions) => 
{
			const public_dir = `${__dirname}/public`	
			const filePaths = walk(public_dir, '.html');
			filePaths.forEach(filePath => edit(filePath));
}
``` 

Then, the final result in the HTML is something like:
```html
<link data-identity="gatsby-global-css" href="/styles.830f820405b440b0141f.css" rel="stylesheet" type="text/css" media="print" onload="this.media='all'; this.onload = null"/>
```
