### ISSUE TITLE
Web worker fails with "ReferenceError: window is not defined"

### ISSUE THREAD

**Issue by Macil** [gatsbyjs/gatsby#30687]
## Description

If you try to instantiate a web worker through the [webpack 5 standard way](https://webpack.js.org/blog/2020-10-10-webpack-5-release/), then it fails with the error "ReferenceError: window is not defined" when using gatsby in develop mode. (It works fine when you've made a production build with `gatsby build` though.)

### Steps to reproduce

Reproduction case: https://github.com/Macil/gatsby-webpack5-bug-repro, run `yarn develop`, and then go to http://localhost:8000/worker/.

For convenience, the code of [src/pages/worker.js](https://github.com/Macil/gatsby-webpack5-bug-repro/blob/main/src/pages/worker.js):

```js
import React, { useEffect } from "react"

export default function WorkerDemo() {
  useEffect(() => {
    const worker = new Worker(new URL("../workerEntry.js", import.meta.url))

    return () => {
      worker.terminate()
    }
  })

  return (
    <div>
      Web worker demo page. The console should show "hello from web worker!" if
      the worker loaded correctly.
    </div>
  )
}
```

and the code of [src/workerEntry.js](https://github.com/Macil/gatsby-webpack5-bug-repro/blob/main/src/workerEntry.js):

```js
console.log("hello from web worker!")
```

### Expected result

"hello from web worker!" should show up in the browser's console.

### Actual result

```
ReferenceError: window is not defined src_workerEntry_js.js line 39 > eval:10:1
    <anonymous> fast-refresh-module.js:10
    js src_workerEntry_js.js:39
    factory src_workerEntry_js.js:524
    __webpack_require__ src_workerEntry_js.js:90
    fn src_workerEntry_js.js:205
    <anonymous> workerEntry.js:2
    js src_workerEntry_js.js:28
    factory src_workerEntry_js.js:524
    __webpack_require__ src_workerEntry_js.js:90
    <anonymous> src_workerEntry_js.js:1138
    <anonymous> src_workerEntry_js.js:1140
```

The exception happens at `window._gatsbyEvents = window._gatsbyEvents || [];` inside of fast-refresh-module.js. It seems to me like `globalThis` or `global` should be used instead of `window`.

### Environment

```
  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i7-7Y75 CPU @ 1.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.12.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 89.0.4389.114
    Edge: 89.0.774.68
    Firefox: 87.0
    Safari: 14.0.2
  npmPackages:
    gatsby: ^3.2.1 => 3.2.1 
```

**Comment by nestarz** [comment]
Hi @Macil Did you find any hot fix regarding this issue ?

**Comment by BayanBennett** [comment]
@nestarz did you find a fix? I'm also trying to narrow down the problem.

**Comment by nemophrost** [comment]
@Macil @nestarz @BayanBennett Created a PR that fixes this ☝️ - Just need to get it merged in :)
