### ISSUE TITLE
Dynamically fetch data from a blog with GraphQL

### ISSUE THREAD

**Issue by ivorpad** [gatsbyjs/gatsby#3068]
Since GraphQL queries are run at build time, how do I dynamically load data from a blog? I'm using [gatsby-source-wordpress](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-wordpress).

Everytime I create a new post I have to stop the server and start it again.

Thanks.

**Comment by ivorpad** [comment]
Closing per https://github.com/gatsbyjs/gatsby/pull/3054

**Comment by bjrn** [comment]
Hi @ivorpad, there's a related discussion here: https://github.com/gatsbyjs/gatsby/issues/2847 and a pull request for adding an endpoint for refreshing external data: https://github.com/gatsbyjs/gatsby/pull/3054 - might solve your use case too?

**Comment by ivorpad** [comment]
Hi @bjrn,

Thanks and yes, I closed the issue a few minutes ago.

**Comment by krsjoseph** [comment]
How does this work in production? Do I rebuild and deploy every time a new post is added? @ivorpad

**Comment by ivorpad** [comment]
@krsjoseph Check this PR https://github.com/gatsbyjs/gatsby/pull/3293 I haven't test it, though.
