### ISSUE TITLE
Gatsby depends on gatsby-link implicitly

### ISSUE THREAD

**Issue by nickmccurdy** [gatsbyjs/gatsby#3069]
I'm new to Gatsby and experimenting with migrating a single page site to it. Because I only need a single page I have no need for `gatsby-link`. However, after removing the package (which was included by the default `gatsby new` starter) I get the following error:

```
 ERROR  Failed to compile with 1 errors          9:21:45 AM

This dependency was not found:

* gatsby-link in ./.cache/dev-404-page.js

To install it, you can run: npm install --save gatsby-link
```

It's clear to me that Gatsby's internal development 404 page relies on `gatsby-link` so I should keep it in my own `package.json`. However, I found it surprising that `gatsby-link` isn't just included in the `gatsby` package because it seems that every single Gatsby project will use this in development. Alternatively, `gatsby-link` could be listed as a `peerDependency` in `package.json`, giving users a hint to include it manually, or the 404 page could be rewritten to not use the plugin. Another idea is that this could be an internal plugin with the `Link` component exported somewhere in the `gatsby` module or a submodule like `gatsby/link`, leading to a similar developer experience but without the extra npm package.

To be clear, I'm specifically referring to the cyclical dependency between the `gatsby` and `gatsby-link` packages and the developer experience around using the `gatsby` package without any dependent packages. I'm not necessarily suggesting that Gatsby should force users to use `gatsby-link` by default, I like that this functionality is more explicitly provided in a separate package.

**Comment by KyleAMathews** [comment]
Agreed — it should have always been part of `gatsby`. As part of v2 we'll be combining the two.

**Comment by nickmccurdy** [comment]
Awesome, thanks! Do you think it would make sense to add it as a `peerDependency` (or at least document that `gatsby-link` should be installed) in a release before 2?

**Comment by KyleAMathews** [comment]
Also you really need to use Gatsby's special Link component as it has some of the logic needed to make Gatsby work e.g. waiting for code splits to load.

**Comment by KyleAMathews** [comment]
>Do you think it would make sense to add it as a peerDependency (or at least document that gatsby-link should be installed) in a release before 2?

Yeah, a PR documenting this somewhere would be great!

**Comment by nickmccurdy** [comment]
I added a peer dependency in #3096
