### ISSUE TITLE
gatsby-plugin-image missing fadeIn option

### ISSUE THREAD

**Issue by lnikell** [gatsbyjs/gatsby#30690]
## Description

We migrate from Gatsby v2 to v3, unfortunately, there are some issues that are coming along the way. Lighthouse will penalize your website if it has animation on images in the hero section especially, so in v2 we used fadeIn={false} to have better scores. However in v3 with `gatsby-plugin-image` it is not possible and the only way of overriding it is ugly CSS !important styles.

It would be nice to have that option in v3 to so it makes the migration process smoother and will result in better performance scores.

**Comment by kelvindecosta** [comment]
Hello!

The [`placeholder`](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-plugin-image#placeholder) option when set to `"none"` fades the images in once they are loaded, without any layout shift.

I think it might help with the migration and performance scores.

**Comment by lnikell** [comment]
Hi @kelvindecosta, placeholder NONE does not remove fade in animations. There is no issues with layout shifting, animation affects on LCP.
