### ISSUE TITLE
gatsby-plugin-netlify-cms installs html-webpack-plugin in its own node_modules and html-webpack-tags-plugin on parent node_modules - html-webpack-plugin cant be found

### ISSUE THREAD

**Issue by stevemarksd** [gatsbyjs/gatsby#30712]
## Description

gatsby-plugin-netlify-cms installs html-webpack-plugin in its own node_modules and html-webpack-tags-plugin on parent node_modules - html-webpack-plugin cant be found

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by LekoArts** [comment]
Please fill out each section of the bug report issue template (including a minimal reproduction) when creating an issue. We can't help with such reports. Thanks!
