### ISSUE TITLE
image resource does not show in public after gatsby build. local display of html /public/

### ISSUE THREAD

**Issue by johnda98** [gatsbyjs/gatsby#30716]
ubuntu 1804.. something to do with /public/ after the build.. the develop is fine ,, the image shows. - 100% same as gatsby starter project..  can't describe much more as confidential content

here is original post that was moved to discussion .. and its not getting any attention - thanks in advance guys

https://github.com/gatsbyjs/gatsby/discussions/30665

I open image in new tab (from local or ipfs deploy) and it can't find it .. odd extension  file:///static/3298bb306e4aec65630d1f5f44b958c5/6968c/hbarfutures2.avif

it is fine of course in localhost when in gatsby develop.. image show fine then

**Comment by LekoArts** [comment]
Please use your discussion (https://github.com/gatsbyjs/gatsby/discussions/30665) as this is most likely an issue with your deployment and not Gatsby
