### ISSUE TITLE
gatsby-source-wordpress crashes on data update

### ISSUE THREAD

**Issue by lnikell** [gatsbyjs/gatsby#30722]
## Description

`gatsby-source-wordpress@5.2.1` Crashes on every data update in WordPress when it tries to pull the new content with the following error:

![image](https://user-images.githubusercontent.com/2697570/113735894-f28a3180-96fc-11eb-8dd4-d0cf89f4149c.png)

This does not happen if I install v5.3.0-next.1 but with gatsby's monorepo setup, and a weird changelog where I can't find v5.2.1 at all, it's hard for me to say if v5.3.0-next.1 is newer or older.

Anyway, it would be nice to have it fixed as soon as possible in the release.

**Comment by shansmith01** [comment]
Thanks for reporting. I have the same bug using gatsby-source-wordpress@5.2.1 as well. Can give access to a repo if required

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

To make the process of resolving problems quicker for both sides we need you to fill out the issue template and give us a minimal reproduction:

```md
<!--
  Please fill out each section below, otherwise, your issue will be closed. This info allows Gatsby maintainers to diagnose (and fix!) your issue as quickly as possible.

  Useful Links:
  - Documentation: https://www.gatsbyjs.com/docs/
  - How to File an Issue: https://www.gatsbyjs.com/contributing/how-to-file-an-issue/

  Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
-->

## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
```

**Comment by jacksellwood** [comment]
Fixed in https://github.com/gatsbyjs/gatsby/pull/30759

**Comment by lnikell** [comment]
Great, thank you for the update @jacksellwood and @LekoArts!
