### ISSUE TITLE
Parse all the metadata in the front matter

### ISSUE THREAD

**Issue by alvinsight** [gatsbyjs/gatsby#3072]
Hi Gatsby Team,
Thank you for your great work on the project, loving it so far!

I was wondering if it would be possible to parse all the data in the front matter as opposed to only the few that are pre-supported, like `title`, `date`, etc.
Ideally a front matter like this:
```
---
path: "/hello-world"
date: "12-07-2017"
title: "Hello World"
xyz: "xyz"
---
```
Would give us a node with an `xyz` property too, the readme of the transformer currently says:
>"All frontmatter fields are converted into GraphQL fields."

which doesn't seem to be true?

I'm happy to have a go at implementing this myself, with a bit of guidance as I'm not sure where that logic is, e.g: is it in Remark itself, or the transformer?

Thanks again,

**Comment by KyleAMathews** [comment]
It does parse everything in the frontmatter! You can see here we add all data from the markdown file including all the frontmatter https://github.com/gatsbyjs/gatsby/blob/fcd3f379f8a200f61e3d7b17d48c3262b9fccd94/packages/gatsby-transformer-remark/src/on-node-create.js#L53

There must be something else wrong e.g. new fields aren't added to the GraphQL schema unless you restart `gatsby develop`.
