### ISSUE TITLE
(DEV_SSR): Querying the actual 404 page in development returns a status of `200` not `404`

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#30730]
DEV_SSR returns the correct status code for 404 pages other than the actual 404 page (`/404/`). We can add a check when serving the page for this scenario and set the right status code.

**Comment by LekoArts** [comment]
I'll close this in favor of the discussion since we agreed to use umbrella discussions for all bug reports/feature requests/comments (like the new image component, too). The comment is here now: https://github.com/gatsbyjs/gatsby/discussions/28138#discussioncomment-583196

**Comment by colinrim** [comment]
Same issue here, upgrading from Gatsby v4 to v5 doesn't fix the issue.
Furthermore, the 404 page is also being listed within sitemap (Netlify plugin).
