### ISSUE TITLE
DEV_SSR true does not seem to work with no trailing slashes

### ISSUE THREAD

**Issue by iDVB** [gatsbyjs/gatsby#30750]
## Description
The new `DEV_SSR: true` flag does not seem to work properly when testing without trailing slashes.

Using DEV_SSR it seems that gatsby links cannot properly determine [isCurrent](https://github.com/gatsbyjs/reach-router/blob/71cf00357c9f7305d4aefa09658512c8fe6f691a/src/index.js#L409)  the same way between the **client** and **server** if you **do not** have a trailing slash. This is causing the mismatch only in the DEV_SSR environment. 

During a production `build` SSR **IS** able to report on `isCurrent` and the client and server code indeed match.

We are (have been for a few years) using the [gatsby-plugin-remove-trailing-slashes](https://www.gatsbyjs.com/plugins/gatsby-plugin-remove-trailing-slashes/) plugin.

### Steps to reproduce
1. Clone [this reproduction repo](https://github.com/iDVB/gatsby_ssrflag)
2. `yarn install`
3. `yarn start`
4. browse to `http://localhost:8000/test` (no trailing slash)
5. Hard/Full reload the page at least once. (this triggers SSR)
6. View the following error in the console....
![image](https://user-images.githubusercontent.com/189506/113937011-8f64d180-97c6-11eb-8cc6-455ab5b2f36a.png)

If you wish to further test...
1.  Implement the [gatsby-plugin-remove-trailing-slashes](https://www.gatsbyjs.com/plugins/gatsby-plugin-remove-trailing-slashes/)
2. `yarn build && yarn serve`
3. Browse to `http://localhost:9000/test` (no trailing slash)
3. Compare **Server** vs **Client** for that Gatsby Link and notice that they both match.

### Expected result
That with `DEV_SSR: true` it should NOT error/warning about this as it will not be an issue in `build`.
It seems that DEV_SSR will need to properly be able to detect location in order for this to work.

### Actual result
With `DEV_SSR: true` it is not properly reporting location during SSR only.

### Environment

```
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.1/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 84.0
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.1.2 => 3.2.1 
    gatsby-plugin-gatsby-cloud: ^2.1.0 => 2.2.0 
    gatsby-plugin-image: ^1.1.2 => 1.2.1 
    gatsby-plugin-manifest: ^3.1.0 => 3.2.0 
    gatsby-plugin-offline: ^4.1.0 => 4.2.0 
    gatsby-plugin-react-helmet: ^4.1.0 => 4.2.0 
    gatsby-plugin-sharp: ^3.1.2 => 3.2.1 
    gatsby-source-filesystem: ^3.1.0 => 3.2.0 
    gatsby-transformer-sharp: ^3.1.0 => 3.2.0 
  npmGlobalPackages:
    gatsby-cli: 3.2.0
```

**Comment by LekoArts** [comment]
Hi! Please report your issue in the umbrella discussion as this is the single place for bug reports/feature requests/discussion about that flag/experiment: https://github.com/gatsbyjs/gatsby/discussions/28138
Thanks!
