### ISSUE TITLE
Docs: broken link on page about notes theme

### ISSUE THREAD

**Issue by gamtiq** [gatsbyjs/gatsby#30763]
## Summary

[On the page about notes theme](https://www.gatsbyjs.com/plugins/gatsby-theme-notes/) there is `View plugin on GitHub` link that opens GitHub's 404 page.

I suppose instead the link should point to https://github.com/gatsbyjs/themes/tree/master/packages/gatsby-theme-notes

**Comment by LekoArts** [comment]
Thanks for the issue! This is something that needs to be handled in https://github.com/gatsbyjs/themes which I'll do soonish
