### ISSUE TITLE
gatsby-plugin-image ignores image resolution when setting max width

### ISSUE THREAD

**Issue by CodeAndWeb** [gatsbyjs/gatsby#30777]
## Description

This is a retina (high-dpi) screenshot taken on macOS. It is logical 481 pixels (982 physical pixels) wide and should be rendered with a maxWidth of 481.

There's currently no

### Expected result

I expect the image to be rendered with the correct maximum width of 481:

<img width="481" alt="screeshot@2x" src="https://user-images.githubusercontent.com/716009/114138605-29836180-990e-11eb-9975-3b59ace08209.png">

### Actual result

The image is rendered with a maximum width of 982 which looks like this:

<img width="982" alt="screeshot@2x" src="https://user-images.githubusercontent.com/716009/114138605-29836180-990e-11eb-9975-3b59ace08209.png">

### Steps to reproduce

Use this image with `<StaticImage>` or  `<GatsbyImage>` - the max-width is set to 982 which makes the image twice as big as it should be:

<img width="481" alt="screeshot@2x" src="https://user-images.githubusercontent.com/716009/114138459-f50fa580-990d-11eb-83ad-b14e3c94a2c6.png">

## Possible solutions

The image resolution is contained in the .png images - but I doubt that it would be a good idea to rely on it. E.g. this screenshot is 144x144.

I'd prefer a solution where the scale factor is part of the image name (like macOS/iOS are doing it) - e.g. screenshot@2x.png - this would also give the option to use art-direction for other lower resolutions by providing an screenshot.png or a screenshot@3x.png ...

### Environment

  System:
    OS: macOS 11.2.3
  Binaries:
    Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.21.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 87.0
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.2.0 => 3.2.0
    gatsby-cli: ^3.2.0 => 3.2.0
    gatsby-image: ^3.2.0 => 3.2.0
    gatsby-link: ^3.2.0 => 3.2.0
    gatsby-plugin-canonical-urls: ^3.2.0 => 3.2.0
    gatsby-plugin-image: ^1.2.0 => 1.2.0
    gatsby-plugin-manifest: ^3.2.0 => 3.2.0
    gatsby-plugin-mdx: ^2.2.0 => 2.2.0
   ...

**Comment by ascorbic** [comment]
Closing in favour of #30744
