### ISSUE TITLE
Upgrade to sharp v0.28.0

### ISSUE THREAD

**Issue by stephenlprice** [gatsbyjs/gatsby#30807]
## Description

When installing gatsby-plugin-image, as well as other dependencies as required by the [updated guide](https://www.gatsbyjs.com/docs/how-to/images-and-media/using-gatsby-plugin-image) for images on a Mac computer running the new Apple M1 chips I get the following error:

Command:
```bash
npm install gatsby-plugin-image gatsby-plugin-sharp gatsby-source-filesystem gatsby-transformer-sharp
```
Note: the error also happens when installing `gatsby-plugin-image` on its own. It also errors out even when adding `arch -x86_64`.
```bash
arch -x86_64 npm install gatsby-plugin-image
```

Error:
```bash
ERR! sharp Prebuilt libvips 8.10.5 binaries are not yet available for darwin-arm64v8
```

### Steps to reproduce

A sample repository is not necessary to reproduce this issue, all that is needed is a machine running an Apple M1 chip where you will attempt to install this plugin and/or dependencies. In any case, you can test this with this [sample repo](https://github.com/API-Guild/greenlight).

### Expected result

Users on Apple M1 chips can install this plugin (which is widely used across the Gatsby ecosystem causing starters and other plugins to fail).

sharp advises upgrading to v0.28.0: https://github.com/lovell/sharp/issues/2460#issuecomment-811046375

What should happen?

### packages are installed successfully

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

System:
    OS: macOS 11.2.2
    CPU: (8) arm64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.9.0 - ~/.nvm/versions/node/v15.9.0/bin/node
    npm: 7.5.3 - ~/.nvm/versions/node/v15.9.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.2.1 => 3.2.1
    gatsby-plugin-purgecss: ^6.0.0 => 6.0.0
    gatsby-plugin-sass: ^4.2.0 => 4.2.0
  npmGlobalPackages:
    gatsby-cli: 3.2.0

**Comment by LekoArts** [comment]
Please see: https://github.com/gatsbyjs/gatsby/issues/30739#issuecomment-814998089

**Comment by stephenlprice** [comment]
vielen Dank!
