### ISSUE TITLE
[gatsby-transformer-yaml] README.md differs from reality

### ISSUE THREAD

**Issue by Charon77** [gatsbyjs/gatsby#3081]
This issue refers to [gatsby-transformer-yaml README.md](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-yaml/README.md).
I'm using gatsby-transformer-yaml 1.5.12.

__Summary:__
I believe README.md is not accurate or does not represent the current version thus needs to be updated.

__Highlights:__
- allLettersYaml instead of allLetters
- `type` is inside `internal` and does not reside alongside `value`

-----------------------

## Issue 1. -Yaml ending.

The readme says:
...
Then the following three nodes would be created.
```js
;[
  {
    value: "a",
    type: "Letters",
  },
  {
    value: "b",
    type: "Letters",
  },
  {
    value: "c",
    type: "Letters",
  },
]
```

However, after running gatsby with this directory structure:
```
src
\-- data
      \-- letters
           \-- letters.yml
```

I only have this node:
```
allLettersYaml
```
as opposed to

```
allLetters
```

as stated in the README. I don't knkow where the `Yaml` ending comes from.

## Issue 2. - `type` does not exist

The Readme says:

```js
;[
  {
    value: "a",
    type: "Letters",
  },
  {
    value: "b",
    type: "Letters",
  },
  {
    value: "c",
    type: "Letters",
  },
]
```

However, running allLettersYaml through GraphQL:

```
allLettersYaml {
  edges {
      node {
        value
        type
      }
  }
}
```
Doesn't work, because there is no `type` field. Looking up the source code reveals that this happens because `type` is inside `internal`.

But, this works:
```
allLettersYaml {
  edges {
      node {
        value
        internal {
          type
        }
      }
  }
}
```

## Conclusion
I believe the Readme needs updating, but it could also be that I'm wrong, maybe I use the wrong version or interpreted the Readme wrongly. If I'm right and indeed the Readme needs updating, I'd like to give PR.

Thank you.

**Comment by DamnedScholar** [comment]
I'm having all of the same problems, except that I can't even get `value` out of my YAML nodes (image below). The readme definitely needs to be updated to the correct information. I used `npm install gatsby-transformer-yaml` yesterday, so I know for sure that I have `1.5.12`.

![image](https://user-images.githubusercontent.com/4084322/33467261-d7b4a3de-d618-11e7-848f-ac55d363b70a.png)

**Comment by KyleAMathews** [comment]
@DamnedScholar does your yaml file have a field named "value"?

@Charon77 you're right! Would you like to PR a fix?

**Comment by DamnedScholar** [comment]
@KyleAMathews Ah-ha! I see now. That was my fault, of course, but I was having trouble finding `allMenuYaml` in the first place (just like OP did, for the same reasons), so I guess it seemed like it must be attached to the same thing. Thanks for the reality check.

**Comment by Charon77** [comment]
@KyleAMathews Sure thing!
I'll probably rewrite some parts of the readme as well. I'll be working on this for the next couple of days.
@DamnedScholar 
I had that problem because one of these:
1. I forgot to add `gatsby-source-filesystem`
2. Forgot pointing `gatsby-source-filesystem` to the right folder / file
3. Have no yaml file

among other things.

**Comment by Charon77** [comment]
PR in #3154
