### ISSUE TITLE
[gatsby-remark-copy-linked-files] does not move images path in frontmatter.

### ISSUE THREAD

**Issue by haysclark** [gatsbyjs/gatsby#3082]
I'm trying to put an image path into the frontmatter data in my Markdown post. If the image is included in frontmatter the posts with have a jumbotron image under the title.

[Project example of original issue](https://github.com/haysclark/gatsby-starter-blog/tree/dd56751f8eb7f55bf7f856bbb1bf67aa583d1b31)

In this demo, I include a relative URL in the blog post's frontmatter object, which is correctly consumed by Remark; however, the image itself is not moved resulting in a broken image downstream. If I try to use Markdown formatting in the frontmatter blob then Remark will error, resulting in a _null_ value in GraphQL.

```
---
title: Hello World
date: "2015-05-01T22:12:03.284Z"
path: "/hello-world/"
author: Mr Bean
image: ./demo.png <-- this image is NOT moved
image2: ![png](./demo.png) <-- is parsed to 'null' by Remark
---

This is my first post on my new fake blog! How exciting!

...

![Chinese Salty Egg](./salty_egg.jpg) <-- image is processed
```

**Comment by markmichon** [comment]
As far as I know the plugin only moves files in the markdown content itself. The frontmatter isn't part of the markdown AST, so it never sees anything in there.

**Comment by KyleAMathews** [comment]
Yup — frontmatter is supposed to be yaml so markdown won't be parsed there and images won't be moved either.

You need to write a GraphQL query to access the files you link to from the frontmatter.

**Comment by haysclark** [comment]
@markmichon Thanks for clarifying! I did a Google search of `Markdown AST` and that REALLY helped me understand what was going on inside this plug-in. [Link](https://github.com/textlint/textlint/tree/master/packages/markdown-to-ast)

**Comment by haysclark** [comment]
@KyleAMathews Thanks for your help today! 

Here is my solution, in case it helps others, and my conversation with Kyle from [Discord](https://discord.gg/0ZcbPKXt5bVoxkfV).

> kylemathews
> @haysclark check out the source for https://using-gatsby-image.gatsbyjs.org/ for how to handle querying and displaying images

After looking at the _gatsby-image_ I saw that my `fontmatter.image` object had a `childImageSharp` property which I could use with the image library. 

### Steps:
- add _gatsby-image_ to my project 
- import the library into my js file.
- update my GraphQL query to have _gatsby-image_ process the result.
- update my render code to use the _gatsby-image_ component.

### Updated GraphQL query
```
export const pageQuery = graphql`
  query BlogPostBySlug($slug: String!) {
    site {
      siteMetadata {
        title
        author
      }
    }
    markdownRemark(fields: { slug: { eq: $slug } }) {
      id
      html
      frontmatter {
        title
        date(formatString: "MMMM DD, YYYY")
        image {
          childImageSharp {
            sizes(maxWidth: 700) {
              ...GatsbyImageSharpSizes_noBase64
            }
          }
        }
      }
    }
  }
`
```
### Updated rendering code
```
import Img from 'gatsby-image'

// ...
<Img sizes={post.frontmatter.image.childImageSharp.sizes} />
// ...
```

I have also updated my demo as well with the fix.
