### ISSUE TITLE
useStaticQuery is returning correct data on initial component render but then instantly emptying the node array and returning empty array on subsequent renders.

### ISSUE THREAD

**Issue by mrbjjackson** [gatsbyjs/gatsby#30833]
## Description

Hi, I noticed that my useStaticData hook was returning data as expected on my initial page render, but then on subsequent rerenders the data it returns was not there.

I've been digging into what's going on using various `console.log`s and I'm seeing some strange behaviour.

### Steps to reproduce

Here is the relevant code in my component that reveals my issue: 

```
  let data = useStaticQuery(graphql`
  query ActivityDataQuerysNew {
    allWpActivity {
      nodes {
        title
        link
      }
    }
  }
  `)
  
  const dataNodesCopy = [...data.allWpActivity.nodes]
```

And from the console I'm seeing:

data is 
```
data: { 
   allWpActivity: {
      nodes: Array(0)
   }
}
```

dataNodesCopy is 
```
dataNodesCopy: [
   { 
     title: 'Item 1',
     link: '/item1link
   },
   { 
     title: 'Item 2',
     link: '/item2link
   },
   etc...
]
```

### Expected result

I expect the value of data return from `useStaticQuery` to persist, even on rerenders of the component.

### Actual result

As you can see, if I log `data`, `data.allWpActivity.nodes` is an empty array, but if I directly view `data.allWpActivity.nodes` it is returning the items I expect to see (but only on the initial render, on the second render even my `dataNodeCopy` will return an empty array).

If feels as though useStaticQuery is loading the data and then immediately clearing the contents of `data.allWpActivity.nodes` . Could that be happening? Any ideas why that might be or things I can try?

Thanks in advance.
B

### Environment

  System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.11.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 87.0
    Safari: 12.1.1
  npmPackages:
    gatsby: ^3.2.1 => 3.2.1 
    gatsby-plugin-anchor-links: ^1.2.1 => 1.2.1 
    gatsby-plugin-gatsby-cloud: ^2.2.0 => 2.2.0 
    gatsby-plugin-google-gtag: ^3.2.0 => 3.2.0 
    gatsby-plugin-image: ^1.2.0 => 1.2.1 
    gatsby-plugin-manifest: ^3.2.0 => 3.2.0 
    gatsby-plugin-offline: ^4.2.0 => 4.2.0 
    gatsby-plugin-react-helmet: ^4.2.0 => 4.2.0 
    gatsby-plugin-sass: ^4.2.0 => 4.2.0 
    gatsby-plugin-sharp: ^3.2.0 => 3.2.1 
    gatsby-source-filesystem: ^3.2.0 => 3.2.0 
    gatsby-source-google-calendar: ^1.1.1 => 1.1.1 
    gatsby-source-wordpress: ^5.2.1 => 5.2.2 
    gatsby-transformer-sharp: ^3.2.0 => 3.2.0 
  npmGlobalPackages:
    gatsby-cli: 3.2.0

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by mrbjjackson** [comment]
Hi @LekoArts , thanks for the reply.
I will do this as soon as I have time.
Thanks

**Comment by jaymdq** [comment]
Having the same issue over here

**Comment by mrbjjackson** [comment]
@jaymdq I'm currently trying to build a minimal reproduction but I'm struggling to reproduce the error on a stripped back version of my site. I wonder if you can help.
Can you give any more information about the issue you're seeing?

**Comment by mrbjjackson** [comment]
I'm embarrassed to say that after debugging it seems that this issue was caused by my misunderstanding of how array.splice() works.

Further down the component I was using `const allActivities = data.allWpActivity.nodes.splice(0, 50)` . I didn't realise this would mutate the `data` object.

**Comment by LekoArts** [comment]
Happens to everyone 😊 Thanks for posting your solution to the problem here and glad it's working now!

**Comment by lqze** [comment]
@mrbjjackson Thanks for actually raising this issue, because I ran into the exact same thing and was tearing my hair out.

**Comment by lqze** [comment]
> I'm embarrassed to say that after debugging it seems that this issue was caused by my misunderstanding of how array.slice() works.
> 
> Further down the component I was using `const allActivities = data.allWpActivity.nodes.slice(0, 50)` . I didn't realise this would mutate the `data` object.

Are you sure you weren't using `splice()` here?
