### ISSUE TITLE
[gatsby-source-wordpress] ACF post object with global product attributes cause "Missing onError handler for invocation 'building-schema'

### ISSUE THREAD

**Issue by ardiewen** [gatsbyjs/gatsby#30849]
## Description

We have a functioning production ecommerce site that runs:

- `gatsby@2.31.x`
- `gatsby-source-wordpress@4.0.1`

Coupled with a backend that's running:

- wordpress 5.7
- `wp-gatsby 1.0.8`
- `wp-graphql 1.3.5`
- `wp-graphql-acf 0.4.1`
- `wp-graphql-woocommerce 0.8.1`

Upon testing an upgrade to `gatsby@3.2.1` and `gatsby-source-wordpress@5.2.3` we get the following error:

```
 ERROR 

Missing onError handler for invocation 'building-schema', error was 'RangeError: Maximum call stack size exceeded'. Stacktrace was 'RangeError: Maximum call stack size exceeded
    at inspect (/Users/ardiewen/Projects/gatsby-v3-pa-bug/node_modules/graphql-compose/lib/utils/misc.js:102:165)
    at /Users/ardiewen/Projects/gatsby-v3-pa-bug/node_modules/graphql-compose/lib/utils/misc.js:93:59
    at Array.map (<anonymous>)
    at inspectObject (/Users/ardiewen/Projects/gatsby-v3-pa-bug/node_modules/graphql-compose/lib/utils/misc.js:93:41)
    at inspect (/Users/ardiewen/Projects/gatsby-v3-pa-bug/node_modules/graphql-compose/lib/utils/misc.js:102:165)
    at /Users/ardiewen/Projects/gatsby-v3-pa-bug/node_modules/graphql-compose/lib/utils/misc.js:93:59
    at Array.map (<anonymous>)
    at inspectObject (/Users/ardiewen/Projects/gatsby-v3-pa-bug/node_modules/graphql-compose/lib/utils/misc.js:93:41)
    at inspect (/Users/ardiewen/Projects/gatsby-v3-pa-bug/node_modules/graphql-compose/lib/utils/misc.js:102:165)
    at /Users/ardiewen/Projects/gatsby-v3-pa-bug/node_modules/graphql-compose/lib/utils/misc.js:93:59
    at Array.map (<anonymous>)
    at inspectObject (/Users/ardiewen/Projects/gatsby-v3-pa-bug/node_modules/graphql-compose/lib/utils/misc.js:93:41)
    at inspect (/Users/ardiewen/Projects/gatsby-v3-pa-bug/node_modules/graphql-compose/lib/utils/misc.js:102:165)
    at /Users/ardiewen/Projects/gatsby-v3-pa-bug/node_modules/graphql-compose/lib/utils/misc.js:93:59
    at Array.map (<anonymous>)
    at inspectObject (/Users/ardiewen/Projects/gatsby-v3-pa-bug/node_modules/graphql-compose/lib/utils/misc.js:93:41)'

⠼ building schema
```

It appears to be some combination of ACF -> Post Object Field -> Product with Global Attribute is causing some schema recursion which didn't occur in `gatsby 2.x / source plugin 4.x`?

Removing all [global product attributes](https://docs.woocommerce.com/document/managing-product-taxonomies/#set-global-attributes) resolves the issue.

Removing the post object ACF field also resolves the issue.

However, having both together causes the issue.

### Steps to reproduce

1. Minimal front end reproduction [here](https://github.com/ardiewen/gatsby-v3-pa-bug), rename `.env.development.sample` to `.env.development` and replace `GATSBY_GRAPHQL_URL`

2. Minimal backend reproduction can be created locally as follows:

   - clean wordpress 5.7 install
   - install classic editor from the marketplace (disables potential gutenberg conflicts with ACF)
   - install woocommerce 5.1.0 from marketplace
   - install wp-gatsby 1.0.8 from marketplace
   - install wp-graphql 1.3.5 from marketplace
   - install wp-graphql-acf 0.4.1 from [here](https://github.com/wp-graphql/wp-graphql-acf/releases/tag/v0.4.1)
   - install wp-graphql-woocommerce 0.8.1 from [here](https://github.com/wp-graphql/wp-graphql-woocommerce/releases/tag/v0.8.1)

Backend steps:

   1. Create a custom field group attached to any post type, in my case I just attached it to `page`
   
<img width="1183" alt="Screen Shot 2021-04-13 at 9 45 17 AM" src="https://user-images.githubusercontent.com/39966887/114563255-43d67b80-9c3d-11eb-86f4-64a5dfeb3864.png">
<img width="1154" alt="Screen Shot 2021-04-13 at 9 45 41 AM" src="https://user-images.githubusercontent.com/39966887/114563338-53ee5b00-9c3d-11eb-9ee9-e60b30449d09.png">

   
   2. Create a `post object` field in that field group, and filter the post types to `Product` only

<img width="1185" alt="Screen Shot 2021-04-13 at 9 44 58 AM" src="https://user-images.githubusercontent.com/39966887/114563511-754f4700-9c3d-11eb-8b78-c0dc1431e897.png">

   3. create a global product attribute as described [here](https://docs.woocommerce.com/document/managing-product-taxonomies/#set-global-attributes)
   4. create a simple product
   5. attach the global product attribute to the simple product
   

3. Run gatsby develop from the minimal front end repo

### Expected result

In Gatsby 2.x, this configuration worked fine, and didn't generate any errors.

In Wordpress's GraphQL IDE, the schema is fine, and equivalent queries work as well.

### Actual result

'gatsby-develop' hangs on building-schema with the error described above.

### Environment

  System:
    OS: macOS 11.2.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.9 - ~/.nvm/versions/node/v14.15.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 86.0
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.2.1 => 3.2.1
    gatsby-plugin-sharp: ^3.2.1 => 3.2.1
    gatsby-plugin-styled-components: ^4.2.0 => 4.2.0
    gatsby-source-wordpress: ^5.2.3 => 5.2.3
    gatsby-transformer-sharp: ^3.2.0 => 3.2.0

**Comment by ardiewen** [comment]
To expedite troubleshooting, I'm also happy to export my minimal repro backend (via LocalWP export) if that would be useful. Please tag me in a comment and I can send a wetransfer or equivalent download link.

**Comment by TylerBarnes** [comment]
Thanks @ardiewen ! Can you email it to wordpress@gatsbyjs.com?

**Comment by ardiewen** [comment]
> Thanks @ardiewen ! Can you email it to [wordpress@gatsbyjs.com](mailto:wordpress@gatsbyjs.com) with a link to the wetransfer and a link to this issue?

I sent a wetransfer for the LocalWP export (~40mb) to that email. Ping me on slack if you didn't receive it.

**Comment by ardiewen** [comment]
> Hiya!
> 
> This issue has gone quiet. Spooky quiet. 👻
> 
> We get a lot of issues, so we currently close issues after 60 days of inactivity. It’s been at least 20 days since the last update here.
> If we missed this issue or if you want to keep it open, please reply here.
> As a friendly reminder: the best way to see this issue, or any other, fixed is to open a Pull Request. Check out [gatsby.dev/contribute](https://www.gatsbyjs.org/contributing/how-to-contribute/) for more information about opening PRs, triaging issues, and contributing!
> 
> Thanks for being a part of the Gatsby community! 💪💜

not stale

**Comment by hellopath** [comment]
Hi @ardiewen did you manage to find another solution on that? I have exactly the same issue.
Thank you!

**Comment by ardiewen** [comment]
> Hi @ardiewen did you manage to find another solution on that? I have exactly the same issue.
> 
> Thank you!

Unfortunately not. One possible workaround is to swap from using global product attributes to product taxonomy, but that may not work for your use case.

**Comment by hellopath** [comment]
> > Hi @ardiewen did you manage to find another solution on that? I have exactly the same issue.
> > Thank you!
> 
> Unfortunately not. One possible workaround is to swap from using global product attributes to product taxonomy, but that may not work for your use case.

Thank your for the taxonomy idea @ardiewen. It's definitely a workaround for my case.

**Comment by keeko20** [comment]
this is also happening to me after updating to v3 - gatsby@3.8.1 with the latest gatsby-source-wordpress@5.8.0

but if v2 - gatsby@2.32.13 with the latest gatsby-source-wordpress@5.8.0 works fine!

**Comment by chrislemmer** [comment]
In the latest version of Gatsby, 3.16, this is still happening. Exactly the same issue.

Any updates on the issue?

**Comment by craigwilcox** [comment]
It seems this issue is still a problem. We're able to get the `building-schema` to work if we take out `ACF Post Object` queries and components. However, these are very helpful for WordPress admins, as they can search for products in the ACF input field instead of having to find the slug as a workaround. 

Has there been any progress on it?

Thanks,
Craig

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!

**Comment by naeluh** [comment]
I just want to leave this message for folks that are experiencing this error you can update to any version of Gatsby but I found that for this to work you cannot go past Version 1.12.0 of WP GraphQL if you update past this version you will get this error if you use the field type post object. So something that was added in the newer version is breaking this field.
