### ISSUE TITLE
WP Plugin access ACF Flexible Content data

### ISSUE THREAD

**Issue by craig-doyle-uk** [gatsbyjs/gatsby#3084]
I am using the Wordpress plugin and having trouble working out how to use the results of one query to create another dynamic query which effectively loops over the returned array.

As I am using ACF Flexible Content in wordpress, I'm unable to know the structure of the data prior to making the first query. The first query (children) returns an array of the __typenames and IDs of the flexible layouts that have been used in the CMS, I then need to do a second query that would use the returned type and ID to pull each individual flexible content layout. This is where I run in to a brick wall! 

How do I loop through the array of IDs and  __typenames to make query to get all of the fields listed within the ACF Flexible content on a page? If I use `acf` instead of `children` inside of the query I only have access to the types and not the IDs but still not the fields that I need in the front end such as title, subtitle, image etc..

    query homeQuery {
      wordpressPage(title: {eq: "About"}) {
        children {
          id
          __typename
         }
      }
    }

returns : 

    {
      "data": {
        "wordpressPage": {
          "children": [
          {
            "id": "4d2dac46-889e-593b-a00b-4a5ccaa87dfa0componentsWordPressAcf_hero",
            "__typename": "WordPressAcf_hero"
          },
          {
            "id": "4d2dac46-889e-593b-a00b-4a5ccaa87dfa1componentsWordPressAcf_body_copy",
            "__typename": "WordPressAcf_body_copy"
          },
          {
            "id": "4d2dac46-889e-593b-a00b-4a5ccaa87dfa2componentsWordPressAcf_image_and_copy",
            "__typename": "WordPressAcf_image_and_copy"
          },
          {
           "id": "4d2dac46-889e-593b-a00b-4a5ccaa87dfa3componentsWordPressAcf_image_and_copy",
           "__typename": "WordPressAcf_image_and_copy"
          },
          {
            "id": "4d2dac46-889e-593b-a00b-4a5ccaa87dfa4componentsWordPressAcf_member",
            "__typename": "WordPressAcf_member"
          }
          ]
        }
      }
    }

Once I have the above data I could do the following kind of query: 

    wordPressAcfHero(id : { eq : "4d2dac46-889e-593b-a00b-4a5ccaa87dfa0componentsWordPressAcf_hero"}) {
      title
      subtitle
    }

But I don't know how to get the data from the top query in to a loop that can do the last query- appreciate any help that anybody can give! Thanks in advance!

**Comment by pieh** [comment]
try this:
```
query homeQuery {
  wordpressPage(title: {eq: "About"}) {
    children {
      __typename
      ... on WordPressAcf_hero {
        title
        subtitle
      }
    }
  }
}
```
and add rest of your types like this (you can do same thing when accessing via `acf` field)

those are called [inline fragments](http://graphql.org/learn/queries/#inline-fragments)

**Comment by craig-doyle-uk** [comment]
@pieh Thanks SO MUCH! I have been trying to find a solution to this since yesterday lunchtime! I knew there must be an elegant way of doing it but wasn't sure exactly what question I needed to ask in order to find the answer.

**Comment by flmuel** [comment]
haha had the same problem! :D thank you (Y)

**Comment by interactiveRob** [comment]
@pieh 
Just wanted to mention that in my case the children object comes back empty and that __typename does not yield anything useful for my ACF fields. In my case below, the Flexible Content field is called popup_contents. Perhaps something in the ACF to REST API plugin has changed?

Looks like this acf_fc_layout field may be the replacement I need.

The Query
```
query staticFrontPage($frontpage_id: Int = 5) {
  wordpressPage(wordpress_id: {eq: $frontpage_id}) {
    children {
      __typename
    }
    acf {
      blue_wave_section {
        popup_contents {
          __typename
          acf_fc_layout
        }
      }
    }
  }
}
```

Returns: 
```
{  
  "data":{  
    "wordpressPage":{  
      "children":[],
      "acf":{  
        "blue_wave_section":{  
          "popup_contents":[  
            {  
              "__typename":"popupContents_2",
              "acf_fc_layout":"image_popup"
            },
            {  
              "__typename":"popupContents_2",
              "acf_fc_layout":"html_popup"
            }
          ]
        }
      }
    }
  }
}
```
