### ISSUE TITLE
Question: What is the best way to separate pages and posts by directory?

### ISSUE THREAD

**Issue by ataylorme** [gatsbyjs/gatsby#3085]
Howdy,
I'm building a personal site and would like to have two types of content, pages (about, contact, etc.) and blog posts.

I'd like to query these separately to easily get things like the latest blog posts for display on the home page. Additionally I'd like for items in`src/pages` to be pages and `src/posts` to be posts.

I've read through some other issues and am currently doing this by running the following in `gatsby-config.js`

```js
	{
   resolve:`gatsby-source-filesystem`,
   options:{
      path:`${__dirname}/src/pages`,
      name:"pages",

   },

}{
   resolve:`gatsby-source-filesystem`,
   options:{
      path:`${__dirname}/src/posts`,
      name:"posts",

   },

}
```

Then in `gatsby-node.js` I am running this:
```js
{
    allFile(filter: {
        internal: {
            mediaType: {
                eq: "text/markdown"
            }
        },
    }) {
        edges {
            node {
                sourceInstanceName
                childMarkdownRemark {
                    frontmatter {
                        path
                    }
                }
            }
        }
    }
}
```

Finally in the `page.js` template I am running:
```js
query PagesByPath($path: String!) {

    site {
        siteMetadata {
            title
            author
        }
    }
    markdownRemark(frontmatter: {
        path: {
            eq: $path
        }
    }) {
        html
        frontmatter {
            title
            path
            slug
        }
    }
}
```

While this works it seems hacky. Is there a better way to have this separation of content type by source directory?

**Comment by ataylorme** [comment]
I'm wondering if something like this will work:
```
{
  allMarkdownRemark(filter: {
				fileAbsolutePath: {
        regex: "/src\/content\/post/"
        }
			  })  {
    edges {
      node {
        id
        fileAbsolutePath
        frontmatter { 
          title
          path
        }
      }
    }
  }
}
```

then I can have `src/content/pages` and `src/content/posts` being able to query them separately.

**Comment by KyleAMathews** [comment]
Yeah, generally people use regex/glob to filter by path e.g. https://github.com/gatsbyjs/gatsby/blob/4bc96cf82cee87f8e2d90a08a3db99ad96783ffd/www/src/pages/blog/index.js#L104

**Comment by ataylorme** [comment]
Great, thanks for confirming!
