### ISSUE TITLE
PDF is not opening on published site

### ISSUE THREAD

**Issue by ziyafenn** [gatsbyjs/gatsby#3086]
Hi guys! So i imported few JPG's and one pdf file into my .js file.
On local server during `develop` and `serve` everything works great. Once i push my website to surge, all images showing up except link (a href) to my PDF. It's just can't find it.

Any ideas?

Thanks!

**Comment by ziyafenn** [comment]
UPD.

I tried to add PDF into /static folder as well, as it described [here](https://www.gatsbyjs.org/docs/adding-images-fonts-files/), same problem.

**Comment by shoemakerdr** [comment]
Could you post the component code for the link tag to give a better idea of what happened?

**Comment by HaoZeke** [comment]
Not relevant, also surge.sh does not support .pdf files as described [here](https://github.com/sintaxi/surge/issues/257)

**Comment by ziyafenn** [comment]
Thanks

**Comment by LuisPaGarcia** [comment]
To add some static content, you need to create a `static` folder on the root of your project.

Then to use it:

```jsx
import { withPrefix } from 'gatsby'

render() {
  // Note: this is an escape hatch and should be used sparingly!
  // Normally they recommend using `import` for getting asset URLs
  // as described in the “Adding Images, Fonts, and Files” page.
  return (
<a
  rel="noopener noreferrer"
  href={withPrefix('/my_pdf.pdf')}
  target="_blank"> Click to see my pdf
</a>
)
}
```

**Comment by shezvar** [comment]
Surge does not allow hosting for PDF file due to users abusive it. Some people started using it to host files and whatever of sizes in Gigabytes. So, on default, you can't host PDF files.

https://github.com/sintaxi/surge/issues/257
