### ISSUE TITLE
upgrading to gatsby-remark-katex v5.0.0 and/or gatsby-transformer-remark v4.0.0 breaks katex math equation

### ISSUE THREAD

**Issue by kimbaudi** [gatsbyjs/gatsby#30865]
## upgrading to gatsby-remark-katex v5.0.0 and/or gatsby-transformer-remark v4.0.0 breaks katex math equation

When I use gatsby-remark-katex v4.2.0 and gatsby-transformer-remark v3.2.0, katex math equations are working correctly

![aaaa](https://user-images.githubusercontent.com/1864092/114656510-145a5a00-9ca3-11eb-8eb4-021a5442da05.png)

But when I update to the latest gatsby-remark-katex v5.0.0 and gatsby-transformer-remark v4.0.0, katex math equations no longer work

![bbb](https://user-images.githubusercontent.com/1864092/114656546-276d2a00-9ca3-11eb-9c58-435c3ed44ee6.png)

### Steps to reproduce

I've created a minimal repo at https://github.com/kimbaudi/gatsby-remark-katex-issue. If you `yarn install && yarn start`, it will work. But if you update to the latest gatsby-remark-katex v5.0.0 and gatsby-transformer-remark v4.0.0, it will no longer work.

### Expected result

What should happen?

updating to the latest gatsby-remark-katex v5.0.0 and gatsby-transformer-remark v4.0.0 should not break katex math equation

### Actual result

What happened.

updating to the latest gatsby-remark-katex v5.0.0 and gatsby-transformer-remark v4.0.0 breaks katex math equation

### Environment

  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz 
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE      
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD        
    npm: 7.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.128
    Edge: Spartan (44.19041.906.0), Chromium (89.0.774.76)
  npmPackages:
    gatsby: ^3.3.0 => 3.3.0
    gatsby-remark-katex: ^4.2.0 => 5.0.0
    gatsby-source-filesystem: ^3.3.0 => 3.3.0
    gatsby-transformer-remark: ^3.2.0 => 4.0.0
  npmGlobalPackages:
    gatsby-cli: 3.2.0

**Comment by hendra-go** [comment]
Hello,
I also faced this problem.

I also found solution that work for my use case, even though no so elegant.
with the help of `unified` and `rehype-parse`

i changed gatsby-remark-katex from this:
```
const visit = require(`unist-util-visit`)
const katex = require(`katex`)
const remarkMath = require(`remark-math`)

module.exports = ({ markdownAST }, pluginOptions = {}) => {
  visit(markdownAST, `inlineMath`, node => {
    node.type = `html`
    node.value = katex.renderToString(node.value, {
      displayMode: false,
      ...pluginOptions,
    })
  })

  visit(markdownAST, `math`, node => {
    node.type = `html`
    node.value = katex.renderToString(node.value, {
      displayMode: true,
      ...pluginOptions,
    })
  })
}

module.exports.setParserPlugins = () => [remarkMath]
```

to this:
```
const visit = require(`unist-util-visit`)
const katex = require(`katex`)
const remarkMath = require(`remark-math`)
const unified = require("unified")
const parse = require(`rehype-parse`)

module.exports = ({ markdownAST }, pluginOptions = {}) => {
	const parseHtml = unified().use(parse, { fragment: true, position: false })

  visit(markdownAST, `inlineMath`, node => {
		const renderedKatexString = katex.renderToString(node.value, {
			displayMode: false,
			...pluginOptions,
		})
    node.data.hChildren = parseHtml.parse(renderedKatexString).children
  })

  visit(markdownAST, `math`, node => {
		const renderedKatexString = katex.renderToString(node.value, {
			displayMode: false,
			...pluginOptions,
		})
    node.data.hChildren = parseHtml.parse(renderedKatexString).children
  })
}

module.exports.setParserPlugins = () => [remarkMath]
```

**Comment by kimbaudi** [comment]
@hendra-go sorry for the late response. I finally got a chance to try your solution of modifying `gatsby-remark-katex` plugin so it uses `unified` and `rehype-parse` and the math equations works on my minimal repo: https://github.com/kimbaudi/gatsby-remark-katex-issue

![works](https://user-images.githubusercontent.com/1864092/116278269-3213ce80-a73b-11eb-817d-5efb833b3f49.png)

The reason for katex math equations breaking after upgrading to the latest `gatsby-remark-plugin` v5.0.0 is because the plugin now uses the latest `remark-math` v4.0.0 whereas prior versions (i.e., `gatsby-remark-plugin` v4.2.0 or less) was using `remark-math` v1.0.6.

**Comment by kimbaudi** [comment]
So the changes to `gatsby-remark-katex` suggested by @hendra-go will fix breaking math equations for anyone using `gatsby-transformer-remark` v4.0.0 or greater and `gatsby-remark-katex` v5.0.0 or greater. However, the suggested fix would also break katex math equations for anyone using `gatsby-transformer-remark` v3.2.0 or less and `gatsby-remark-katex` v4.2.0 or less.

**Comment by kimbaudi** [comment]
`gatsby-remark-katex` v5.0.0 or greater needs to be updated using `unified` and `rehype-parse` as suggested by @hendra-go since its now using `remark-math` v4.0.0.

**Comment by kimbaudi** [comment]
After following the suggestion, I noticed that the html is rendered a bit different than before. For the equations above, here is the previous html render:

```html
<p>Math Equations in Inline Mode</p>
<p>
  <span class="katex">...</span>
</p>
<p>Math Equations in Display Mode</p>
<span class="katex-display">
  <span class="katex">...</span>
</span>
```

And here is the html render after the suggested fix:

```html
<p>Math Equations in Inline Mode</p>
<p>
  <span class="math math-inline">
    <span class="katex">...</span>
  </span>
</p>
<p>Math Equations in Display Mode</p>
<div class="math math-display">
  <span class="katex">...</span>
</div>
```

so if you use `katex.css`, you might have to adjust css to handle this new html render

**Comment by kimbaudi** [comment]
@hendra-go your solution works, but I found a minor typo. you need to make sure to set `displayMode` to `true` for `math` nodes. Otherwise, it will display inline since `katex-display` class won't be added.

change this:

```js
  visit(markdownAST, `math`, node => {
    const renderedKatexString = katex.renderToString(node.value, {
      displayMode: false,
      ...pluginOptions,
    })
    node.data.hChildren = parseHtml.parse(renderedKatexString).children
  })
```

to

```js
  visit(markdownAST, `math`, node => {
    const renderedKatexString = katex.renderToString(node.value, {
      displayMode: true,
      ...pluginOptions,
    })
    node.data.hChildren = parseHtml.parse(renderedKatexString).children
  })
```

**Comment by kimbaudi** [comment]
So this issue is resolved for me by using a local plugin (literally copy/paste from `gatsby-remark-katex` plugin) that uses `unified` and `rehype-parse` as suggested by @hendra-go. You can check out the latest commit on my minimal repo: https://github.com/kimbaudi/gatsby-remark-katex-issue

![image](https://user-images.githubusercontent.com/1864092/116594730-64f2c980-a8d7-11eb-8c35-1c5bccd99fc6.png)

Since the issue is resolved for me, I can close this. But I would rather much keep it open until it is actually fixed in `gatsby-remark-katex` plugin.

**Comment by kimbaudi** [comment]
I've deleted my minimal repo and added a zip

[gatsby-remark-katex-issue-main.zip](https://github.com/gatsbyjs/gatsby/files/6417404/gatsby-remark-katex-issue-main.zip)

**Comment by amitash** [comment]
@kimbaudi can you submit a PR so that the changes can be merged?

**Comment by BurkovBA** [comment]
@LekoArts @amitash Ok, seems like I'm the most interested guy in getting this one fixed and have more spare time than the others.

I tried the solution by @kimbaudi as a **local** plugin, and it worked (see: https://github.com/gatsbyjs/gatsby/issues/31427).

But when I try to apply the same changes directly in the plugin code, distributed with `node_modules`, it would crash. I don't get, why the same code works in a local plugin, but not in a `node_modules`-distributed plugin? 

Other than that I'm ready to submit @kimbaudi's code as a PR.

**Comment by vladar** [comment]
@BurkovBA can you submit your PR and provide a link to a reproduction where we could test it (and also investigate why it crashes)? I will take a look.

**Comment by BurkovBA** [comment]
@vladar Ok, so I created a PR, in unit-tests this code generated a much different HAST snapshot, than it used to generate with a previous version. Previously it used to render the whole formula as [a single html node](https://github.com/gatsbyjs/gatsby/pull/31596/commits/62eb2f861de117009742cc31c929305c242f25cd#diff-bc5077a45d77387c2456423288d7d90a2e204a6b7c5375302ff23ac98628e366). Now it unpacks it into [a whole subtree](https://github.com/gatsbyjs/gatsby/pull/31596/commits/62eb2f861de117009742cc31c929305c242f25cd#diff-165fa951d0dc902d2adae6ba5580396f80b35efda3e7abffb9a8d2ca50ecd86f). However the new AST looks reasonable to me.

To really test it in production I'll create a scoped package out of it and try testing against my personal blog to see, if it works. Will report the result. If you can suggest a better way of testing, please do so.

**Comment by BurkovBA** [comment]
Ok, so I published the version, submitted as this PR, as a scoped npm package @burkov/gatsby-remark-katex.

After that I replaced the stock gatsby-remark-katex with it in [my blog's](https://github.com/BurkovBA/BurkovBA.github.io) `package.json` and `gatsby-config.js`:

`package.json`:
```diff
diff --git a/package.json b/package.json
index d96527c..a382091 100644
--- a/package.json
+++ b/package.json
@@ -8,6 +8,7 @@
     "url": "https://github.com/BurkovBA/BurkovBA.github.io/issues"
   },
   "dependencies": {
+    "@burkov/gatsby-remark-katex": "^5.4.1-next.0",
     "babel-eslint": "^10.1.0",
     "gatsby": "^3.4.2",
     "gatsby-plugin-feed": "^3.4.0",
@@ -23,14 +24,12 @@
     "gatsby-remark-copy-linked-files": "^4.1.0",
     "gatsby-remark-embed-gist": "^1.2.1",
     "gatsby-remark-images": "^5.1.0",
-    "gatsby-remark-katex": "^5.1.0",
     "gatsby-remark-prismjs": "^5.1.0",
     "gatsby-remark-responsive-iframe": "^4.1.0",
     "gatsby-remark-smartypants": "^4.1.0",
     "gatsby-source-filesystem": "^3.4.0",
     "gatsby-transformer-remark": "^4.1.0",
     "gatsby-transformer-sharp": "^3.4.0",
-    "katex": "^0.12.0",
     "lodash": "^4.17.11",
     "postcss": "^8.2.14",
     "prismjs": "^1.16.0",
```


`gatsby-config.js`:
```diff
diff --git a/gatsby-config.js b/gatsby-config.js
--- a/gatsby-config.js
+++ b/gatsby-config.js
@@ -54,7 +54,7 @@ module.exports = {
           `gatsby-remark-copy-linked-files`,
           `gatsby-remark-smartypants`,
           {
-            resolve: `gatsby-remark-katex`,
+            resolve: `@burkov/gatsby-remark-katex`,

```

And said `gatsby develop`. This works:

<img width="1307" alt="Screenshot 2021-05-26 at 18 24 42" src="https://user-images.githubusercontent.com/7602655/119687260-b8f9bb00-be4f-11eb-992b-4d16fa55c2da.png">

**Comment by kimbaudi** [comment]
Hey @BurkovBA thanks for taking on this PR.

**Comment by kimbaudi** [comment]
@amitash - I couldn't take on this PR because I felt it needed a better unit test, but didn't feel confident to create one. If this package had a good unit test prior to upgrading to remark 13 and remark-math 4, then we could have caught this bug prior to release and avoided this situation. I guess what I'm saying is this package needs a good unit test. Especially since the previous unit test wasn't able to detect this bug prior to release.
