### ISSUE TITLE
WPGraphiQL and gatsby-source-wordpress return different values for same ACF field

### ISSUE THREAD

**Issue by dbogod** [gatsbyjs/gatsby#30878]
## Description

Using `gatsby-source-wordpress` and WPGraphQL for Advanced Custom Fields, I get null returned for queries that return values in WPGraphiQL.

### Steps to reproduce

In Wordpress 5.7 with the following plugins:
- Advanced Custom Fields Pro 5.9.5
- WP GraphQL 1.3.5
- WP Gatsby 1.0.8
- WPGraphQL for Advanced Custom Fields 0.4.1

**ADD NEW ACF FIELD, EXPOSE IT TO GRAPHQL**

- Using ACF, create a new field group
- Add a text field and give it an id of _bar_
- For the location setting, specify _Page Type IS NOT EQUAL TO Front Page_
- Ensure _Show in GraphiQL_ is set to _Yes_, and give the field group a name of _foo_
- Save (aka 'update')
- Go to a page that is not the front page, find the field, enter any value and save.

**QUERY IN WP**

- Still in Wordpress, open GraphiQL IDE and query this:

```
query MyQuery {
  pages {
    nodes {
      foo {
        bar
      }
    }
  }
}
```

**QUERY IN GATSBY**

- In your `gatsby-source-wordpress` starter site, point the `gatsby-config` to the right URL for your WP site.
- `gatsby develop`
- Go to your localhost GraphiQL and, using the Explorer, query this:

```
query MyQuery {
  allWpPage {
    nodes {
      foo {
        bar
      }
    }
  }
}
```

### Expected result

Both queries return the same value for `bar`

### Actual result

The WP GraphiQL IDE returns the correct value for `bar`
The Gatsby localhost GraphiQL returns `null` for `foo`

### Environment

  System:
    OS: Windows 10 10.0.18362
    CPU: (16) x64 AMD Ryzen 7 PRO 4750U with Radeon Graphics
  Binaries:
    Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gatsby: ^2.30.1 => 2.32.12 
    gatsby-image: ^2.9.0 => 2.11.0 
    gatsby-plugin-manifest: ^2.10.0 => 2.12.1 
    gatsby-plugin-offline: ^3.8.0 => 3.10.2 
    gatsby-plugin-react-helmet: ^3.8.0 => 3.10.0 
    gatsby-plugin-sharp: ^2.12.0 => 2.14.3 
    gatsby-source-filesystem: ^2.9.0 => 2.11.1 
    gatsby-source-wordpress: ^4.0.0 => 4.0.6 
    gatsby-transformer-sharp: ^2.9.0 => 2.12.1 
  npmGlobalPackages:
    gatsby-cli: 3.3.0

**Comment by TylerBarnes** [comment]
Hi @dbogod , I tried to reproduce with your steps but just setting the page type to not the homepage makes it not show up in the WPGraphQL schema for me (on the WP side). Can you provide a reproduction `/graphql` URL?

Thanks

**Comment by TylerBarnes** [comment]
<img width="791" alt="Screen Shot 2021-04-14 at 6 11 47 PM" src="https://user-images.githubusercontent.com/14190743/114799624-e9c4db80-9d4c-11eb-8352-dfd800681eec.png">
<img width="826" alt="Screen Shot 2021-04-14 at 6 11 53 PM" src="https://user-images.githubusercontent.com/14190743/114799631-ed586280-9d4c-11eb-85dd-bd79e357f6b1.png">
<img width="1090" alt="Screen Shot 2021-04-14 at 6 11 28 PM" src="https://user-images.githubusercontent.com/14190743/114799636-f1848000-9d4c-11eb-9b65-de421acf223a.png">

**Comment by TylerBarnes** [comment]
btw @jasonbahl is currently working on a new ACF for WPGraphQL feature that will make it easier to use location rules and add fields to the schema in a reliable and easy to understand way. See https://github.com/wp-graphql/wp-graphql-acf/pull/229 for more info

**Comment by BrandonYuen** [comment]
I'm having a similar issue with an ACF "File" field. It shows correctly in the GraphiQL IDE from Wordpress but not in the localhost GraphIQL.

What is strange is that it will **temporarily** work when deleting the video file from the media library and adding a new video file. First I thought it was a caching problem, but `gatsby clean` does not fix this problem. After some time the local graphiql just starts showing `{video: null}`. Not sure where the problem starts... `gatsby-source-wordpress`, `WPGraphiQL` ,`WPGraphQL for Advanced Custom Fields` or `WP Gatsby`?.

Endpoint is: http://45.63.12.46/sites/ecu-wp/graphql

**Wordpress GraphiQL IDE**

Query:
```
query MyQuery {
  pages {
    nodes {
      header {
        video {
          mediaItemUrl
          mimeType
        }
      }
    }
  }
}

```

Returns
``` json
{
  "data": {
    "pages": {
      "nodes": [
        {
          "header": {
            "video": {
              "mediaItemUrl": "http://45.63.12.46/sites/ecu-wp/wp-content/uploads/2021/04/ecu_vid.mp4",
              "mimeType": "video/mp4"
            }
          }
        }
      ]
    }
  },
  "extensions": {
    "debug": [
      {
        "type": "DEBUG_LOGS_INACTIVE",
        "message": "GraphQL Debug logging is not active. To see debug logs, GRAPHQL_DEBUG must be enabled."
      }
    ]
  }
}
```

**Localhost GraphiQL**

Query
```
query MyQuery {
  pages {
    nodes {
      title
      header {
        video {
          mediaItemUrl
          mimeType
        }
      }
    }
  }
}

```

Returns:
``` json
{
  "data": {
    "allWpPage": {
      "nodes": [
        {
          "header": {
            "video": null
          }
        }
      ]
    }
  },
  "extensions": {}
}
```

**Versions**
package.json
```
  "dependencies": {
    "babel-plugin-styled-components": "^1.12.0",
    "dotenv": "^8.2.0",
    "gatsby": "^3.3.0",
    "gatsby-plugin-image": "^1.3.0",
    "gatsby-plugin-manifest": "^3.2.0",
    "gatsby-plugin-react-helmet": "^4.2.0",
    "gatsby-plugin-sharp": "^3.2.1",
    "gatsby-plugin-styled-components": "^4.2.0",
    "gatsby-source-wordpress": "^5.2.3",
    "gatsby-transformer-sharp": "^3.2.0",
    "html-react-parser": "^1.2.4",
    "polished": "^4.1.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "styled-components": "^5.2.3",
    "typeface-merriweather": "^1.1.13",
    "typeface-montserrat": "^1.1.13"
  },
```

Wordpress Plugins
```
Advanced Custom Fields PRO: 5.7.13
WP Gatsby: 1.0.8
WPGraphQL: 1.3.5
WPGraphQL for Advanced Custom Fields: 0.4.1
```

**Comment by dbogod** [comment]
@TylerBarnes 

Endpoint: https://bogod.dev

Thanks for looking into this. You're right, that location rule I specified does indeed not show in WP GraphiQL. I must have tried so many location permutations I got turned around and confused! These queries use _Page_ rather than _Page Type_ Here's what I should have said (using About and Contact page as examples here, they're just names):

_Page IS EQUAL TO About_: 
✅ WP GraphiQL
❌ Gatsby GraphiQL: `foo` is null

_Page IS EQUAL TO About_ **and**  _Page IS EQUAL TO Contact_:
✅ WP GraphiQL
❌ Gatsby GraphiQL: `foo` is null

_Page IS NOT EQUAL TO About_: 
❌ WP GraphiQL: `foo` does not appear in schema
❌ Gatsby GraphiQL: `foo` does not appear in schema

 Re that pending feature, that sounds like the ticket.

**Comment by TylerBarnes** [comment]
@dbogod I'm not able to reproduce with your endpoint, If I point a Gatsby site at your WP instance the queries return the same data:

<img width="2560" alt="Screen Shot 2021-04-15 at 10 51 23 AM" src="https://user-images.githubusercontent.com/14190743/114915550-8b453f00-9dd8-11eb-9851-1103631dd1e2.png">

I tried reproducing this in my local test site and it's working as expected for clean builds as well as data updates.

Are you able to share a reproduction repo I can take a look at?

**Comment by dbogod** [comment]
@TylerBarnes 

I don't know how or why, but it's working fine now, just as you've said. This is bizarre. I _know_ it wasn't working.. WP updated in the last 24hrs so maybe that has something to do with it? 

Whatever the reason, I'm happy as long as it works! Apologies for the time you have spent on this, although I certainly appreciate it.

Regards
Daniel
