### ISSUE TITLE
gatsby-plugin-styled-components not working in Gatsby 3 when using an external styled-components lib

### ISSUE THREAD

**Issue by iDVB** [gatsbyjs/gatsby#30874]
## Description
Also [mentioned here](https://github.com/styled-components/styled-components/issues/3321#issuecomment-817431012). 

### Steps to reproduce
First, please be patient with there being no reproduction example. We've been working on this issue solely for 3-4 days and since our internal styled-components lib is part of the equation, we can't publicly share it. Very happy to work out something for a core member.

We just made the switch to Gatsby 3 and we're even getting this now on `styled-components v5.2.0` (previously in G2 this was also causing the issue [mentioned here](https://github.com/styled-components/styled-components/issues/3321).)
It seems to only happen in `yarn build` and not `yarn start`. 

We're also developing with our own component lib and when we `yarn link` that component (which uses styled-components as a peer dep) it also **works**.

I'm going to continue to downgrade various components in hopes that we find another one that is also leading to the isssue.  However, we're pretty in the dark here as to what is causing it.

Found out a bit more info on what is happening but still not solution.
It appears the output for CLIENT and SERVER(Gatsby3 SSR) do not match.
Looking at this image you can see that not only that, but some of the styles are moved up to its parent?!

![image](https://user-images.githubusercontent.com/189506/114445989-b9d7d580-9b9e-11eb-8271-1b54504661c1.png)

There is also some very odd extra styles being injected in SSR...

![image](https://user-images.githubusercontent.com/189506/114446254-06231580-9b9f-11eb-806a-aeaf0ed8e3c7.png)

I'm trying to figure out how to put together a reproduction example, but I think the issue has something to do with using a custom UI library module in your application where the lib and your app both use `styled-components`.

**UPDATE**
More testing turned up something VERY odd. 

1. I've `ybs` (eg. `yarn build && yarn serve`) and opened in Chrome Incognito
2. I've then clicked around the side and everything looks normal.
3. Then I click on a link to a page I know to be 404. I intensionally, for this test, do NOT have a custom 404 page. so I get an error like this...
![image](https://user-images.githubusercontent.com/189506/114728298-fa556180-9d0c-11eb-8dca-4ccdeceaf80a.png)

4. I then hit the back button and this component is **NOT WORKING**.
7. What I'm comparing in the following is the same page when it **WORKS** and **NOT WORKING**.

![image](https://user-images.githubusercontent.com/189506/114729193-c3338000-9d0d-11eb-90fa-635a7380da11.png)

WEIRD PART: Even though this is a completely different module and between this case and the one I [last posted about](https://github.com/styled-components/styled-components/issues/3321#issuecomment-817431012) they **both** use the same styled hash `kiRdWm`. In the first example above it was IN the SSR. In this example here, the code is NOT in SSR, as the component is only conditionally injected. 

We're having a really tough time reproducing this in a small example that we can share since this uses our internal styled-components lib that we can't really make public.

### Expected result
Component styles should be maintained at all times.

### Actual result
Styles are NOT being maintained. Sometimes between SSR and Client, but also it seems this is happening even on the same component and just in Client depending on clicking around.

### Environment

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.1/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 84.0
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.2.1 => 3.2.1 
    gatsby-cli: ^3.1.0 => 3.2.0 
    gatsby-plugin-feed: ^3.1.0 => 3.2.0 
    gatsby-plugin-google-gtag: ^3.1.0 => 3.2.0 
    gatsby-plugin-image: ^1.2.1 => 1.2.1 
    gatsby-plugin-manifest: ^3.1.0 => 3.2.0 
    gatsby-plugin-material-ui: ^3.0.1 => 3.0.1 
    gatsby-plugin-no-javascript: ^2.0.5 => 2.0.5 
    gatsby-plugin-react-helmet: ^4.1.0 => 4.2.0 
    gatsby-plugin-remove-trailing-slashes: ^3.1.0 => 3.2.0 
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5 
    gatsby-plugin-sharp: ^3.2.1 => 3.2.1 
    gatsby-plugin-sitemap: ^3.1.0 => 3.2.0 
    gatsby-plugin-styled-components: ^3.1.18 => 3.10.0 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.21 => 1.1.21 
    gatsby-source-filesystem: ^3.1.0 => 3.2.0 
    gatsby-transformer-sharp: ^3.1.0 => 3.2.0 
  npmGlobalPackages:
    gatsby-cli: 3.2.0

**Comment by KyleAMathews** [comment]
It might be worth opening this in the styled-components repo as this is probably something they'll have the most context on.

**Comment by iDVB** [comment]
@KyleAMathews [Did as well](https://github.com/styled-components/styled-components/issues/3321#issuecomment-817431012) but still does seem to at least impact the new `DEV_SSR` in Gatsby since things WORK there but FAIL in build. 
Should the two environments not be consistent?

UPDATE -
We now have a reproduction repo(s) for someone to look at should be wish.

Repo Steps:
1. `git clone git@github.com:iDVB/gatsby3_site_issue.git`
2. `yarn install`
3. `yarn build && yarn serve`
4. Browse to `http://localhost/` (Notice cookie banner at bottom looks like this, as expected)
![image](https://user-images.githubusercontent.com/189506/114792961-593fc880-9d57-11eb-8052-cd54f717161d.png)

5. Click `Go to Page 2` link. (Notice the cookie banner looks fine again)
6. Now on this page, hard refresh. 
7. This should now BREAK the cookie banner and it should look like this...
![image](https://user-images.githubusercontent.com/189506/114792994-6d83c580-9d57-11eb-8cb2-f6ec25e0934c.png)


* - Note - Here is the sample styled-components lib repo ([react-components](https://github.com/iDVB/react-components)) if you want to play in that as well.

**Comment by LekoArts** [comment]
> Also, gatsby-plugin-styled-components is maintained under this repo and that plugin doesn't seem to be doing what its job is. consistently hashed component classNames between environments (a must for server-side rendering)

The plugin is merely a light wrapper around packages from `styled-components` so there's nothing special that the plugin is doing.

I don't think this is an issue specifically with Gatsby and it should be handled inside the issue you linked -- people there also see it when not using Gatsby.

> We just made the switch to Gatsby 3 and we're even getting this now on styled-components v5.2.0 (previously in G2 this was also causing the issue mentioned here.)

This probably happened because you upgraded all the dependencies and the dependencies of styled-components (that were locked with a lock file) got semver bumped to the latest version.

The repo you linked also uses `material-ui` so it's not really a minimal reproduction about `styled-components` either :/

**Comment by iDVB** [comment]
Thanks @LekoArts, I'll continue to track under `styled-components`. It's been difficult to setup a minimal reproduction since the issue has "something" to do with the amount or order of styles and html nodes. Each time I try to peel a bit more off here, it fixes the issue. But it doesn't matter what I peel off, so it's not specific to a single component now. 

I've placed the ticket here for two reasons:
1) This is an issue since Gatsby 3 that so far doesn't seem to have a work around and is completely gating us from upgrading to G3. 
2) It does point to some potential inconsistencies in the way DEV_SSR vs build SSR. Since this issue does not appear in DEV_SSR and does appear when you build. I thought the whole point of DEV_SSR was to have a consistent experience with build in order to detect issues sooner. It appears this could be due to a [larger issue with DEV_SSR](https://github.com/gatsbyjs/gatsby/discussions/28138#discussioncomment-584665)

**Comment by iDVB** [comment]
**FIXED**
We managed to find a fix to [our issue](https://github.com/styled-components/styled-components/issues/3321#issuecomment-819915948). It appears this issue has already been identified in [another issue](https://github.com/styled-components/babel-plugin-styled-components/issues/280) on `babel-plugin-styled-components`.

**Comment by KyleAMathews** [comment]
Glad you found a solution!
