### ISSUE TITLE
'gatsby develop' overrides the main html file

### ISSUE THREAD

**Issue by lrn2prgrm** [gatsbyjs/gatsby#3087]
Hi I know that we can use helmet to handle the header but I really need to customize the main html file.

When the css file is directly set on the header I can pre render some loading state, if i use helmet it takes longer to load.

I just want to know if you could remove this override or at least make it configurable in some way.

**Comment by KyleAMathews** [comment]
Use gatsby-plugin-react-helmet as it inserts then data from react-helmet is inserted in the html head at build time.
