### ISSUE TITLE
[gatsby-source-wordpress] fails to source pages when using custom schema fields.

### ISSUE THREAD

**Issue by ashhitch** [gatsbyjs/gatsby#30890]
## Description

WordPress source plugin fails to find nodes if you have a custom field of the same type in the schema.

This is because the source plugin is searching for the single node entry point into WPGraphQL and it's finding the custom field and thinking that’s where all nodes of that type are. 

This causes incremental and previews build to not find the updates, both locally and on Gatsby Cloud.

### Steps to reproduce 
For example if in WPGraphQL  if you add a new field like this:

```graphql
register_graphql_field( 'RootQuery', 'homepage', [
		'type' => 'Page',
		'description' => __( 'Returns the homepage', 'wp-graphql-homepage' ),
		'resolve' => function($item, array $args, AppContext $context) {
      $page_on_front = get_option( 'page_on_front', 0 );
      
    if ($page_on_front == 0 ) {
        return null;
      }

	return  DataSource::resolve_post_object( $page_on_front, $context );
		},
	]);

```

And then publish a content change in WordPress

### Expected result
Source changed pages

### Actual result 
The build will not be able to find any Pages but will find other post types.

### Enviroment

  System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.128
    Safari: 14.0.2
  npmPackages:
    gatsby: ^3.3.0 => 3.3.0 
    gatsby-cli: ^3.3.0 => 3.3.0 
    gatsby-image: ^3.3.0 => 3.3.0 
    gatsby-omni-font-loader: ^1.3.0 => 1.3.0 
    gatsby-plugin-catch-links: ^3.3.0 => 3.3.0 
    gatsby-plugin-create-client-paths: ^3.3.0 => 3.3.0 
    gatsby-plugin-google-analytics: ^3.3.0 => 3.3.0 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-image: ^1.3.0 => 1.3.0 
    gatsby-plugin-loadable-components-ssr: ^2.1.0 => 2.1.0 
    gatsby-plugin-manifest: ^3.3.0 => 3.3.0 
    gatsby-plugin-netlify: ^3.3.0 => 3.3.0 
    gatsby-plugin-offline: ^4.3.0 => 4.3.0 
    gatsby-plugin-react-helmet: ^4.3.0 => 4.3.0 
    gatsby-plugin-react-svg: ^3.0.1 => 3.0.1 
    gatsby-plugin-recaptcha: ^1.0.5 => 1.0.5 
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5 
    gatsby-plugin-sass: ^4.3.0 => 4.3.0 
    gatsby-plugin-sharp: ^3.3.0 => 3.3.0 
    gatsby-plugin-sitemap: ^3.3.0 => 3.3.0 
    gatsby-plugin-styled-components: ^4.3.0 => 4.3.0 
    gatsby-plugin-typescript: ^3.3.0 => 3.3.0 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.21 => 1.1.21 
    gatsby-plugin-wpgraphql-seo: ^1.1.4 => 1.1.4 
    gatsby-source-filesystem: ^3.3.0 => 3.3.0 
    gatsby-source-wordpress: ^5.3.0 => 5.3.0 
    gatsby-transformer-sharp: ^3.3.0 => 3.3.0 

_This was confirmed by @TylerBarnes while very kindly helping me get around this._

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
