### ISSUE TITLE
data not showing up from GraphQL query

### ISSUE THREAD

**Issue by ataylorme** [gatsbyjs/gatsby#3089]
I'm attempting to use `gatsby-image` to pull in a single hero image inside of a component. My graphql query is following the instructions from the [`gatsby-image` README](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-image) with the `$hero` variable coming from frontmatter via `context` in `createPage`.

```
export default ({ data }) => {
  return (
    <div className="heroImg">
	<Img sizes={data.file.childImageSharp.sizes} />
    </div>
  )
}

export const query = graphql`
query heroImageQuery($hero: String!) {
  file(relativePath: { eq: $hero }) {
	childImageSharp {
	  sizes(maxHeight: 350) {
		...GatsbyImageSharpSizes_withWebp_tracedSVG
	  }
	}
  }
}
`
```

The issue is that `data` is undefined. Not sure what I'm doing wrong here. If I run the query directly in GraphiQL with the image path hard coded from the value in `$hero` it works fine. 

```
query heroImageQuery {
  file(relativePath: { eq: "images/heroes/portland-or-sign.jpg" }) {
	childImageSharp {
	  sizes(maxHeight: 350) {
		src
	  }
	}
  }
}
```

**Comment by ataylorme** [comment]
I tried hard-coding a known good query in my component as well (see below) but `data` is still undefined.

```
query heroImageQuery{
  file(relativePath: { regex: "/portland-or-sign.jpg/" }) {
	childImageSharp {
	  sizes(maxHeight: 350) {
		...GatsbyImageSharpSizes_withWebp_tracedSVG
	  }
	}
  }
}
```

**Comment by ataylorme** [comment]
@KyleAMathews I was able to run my graphql query in the template defined with `component` in `createPage` when then pass the data down via props to components. Is this the right approach? Just want to be sure I'm doing things properly.

**Comment by KyleAMathews** [comment]
Yup!

**Comment by melissamcewen** [comment]
@ataylorme how did you fix this? I'm running into the same problem

**Comment by melissamcewen** [comment]
ooo you can't run the graphgl query in a component I guess?

**Comment by ataylorme** [comment]
@melissamcewen I ended up [running the graphQL query in the template](https://github.com/ataylorme/ataylor.me/blob/76fe868c7b952bf9637e637d0d6db951690a51f8/src/templates/default.js#L70:L76) and [passing the result down to my component via props](https://github.com/ataylorme/ataylor.me/blob/76fe868c7b952bf9637e637d0d6db951690a51f8/src/templates/default.js#L26
) so [the component could use the data](https://github.com/ataylorme/ataylor.me/blob/76fe868c7b952bf9637e637d0d6db951690a51f8/src/components/HeroImage/index.js#L7). Hope that helps.
