### ISSUE TITLE
gatsby-plugin-image no "fadeIn" prop option

### ISSUE THREAD

**Issue by AnatoliyKowalev** [gatsbyjs/gatsby#30897]
We migrated to gatsby-plugin-image from gatsby-image and found out that if we set placeholder to NONE there is some extra fadein animation which makes smooth appearance. Previously we could disable any images appearance in "gatsby-image" by fadein={false}, but in  "gatsby-plugin-image" it's unreal, there is no prop option for that. It's a problem because it loads two same images one of them used for animation but it double work for the network.

**Comment by LekoArts** [comment]
Please comment on https://github.com/gatsbyjs/gatsby/discussions/30699 - thanks!
