### ISSUE TITLE
Incompatible graphql version provided by gatsby and gatsby-recipes

### ISSUE THREAD

**Issue by klittlepage** [gatsbyjs/gatsby#30913]
## Description

The `gatsby` and `gatsby-recipes` packages require `express-graphql` with a version range constraint of `^0.9.0`; they also require `graphql` with a constraint of `^15.4.0`.

The only version of `express-graphql` satisfying that range constraint is `0.9.0`, which has a peer dependency on `^14.4.1`. As such, there's an irreconcilable version conflict.

Migrating to `express-graphql `0.10.0` or more recent would fix this.

### Steps to reproduce

Create a new `gatsby 3.x` project.

### Expected result

No version conflict.

### Actual result

A version conflict:

```shell
❯ yarn install
➤ YN0000: ┌ Resolution step
➤ YN0060: │ gatsby-recipes@npm:0.14.0 provides graphql (p6791f) with version 15.5.0, which doesn't satisfy what express-graphql requests
➤ YN0060: │ gatsby@npm:3.3.0 [16a18] provides graphql (p88b97) with version 15.5.0, which doesn't satisfy what express-graphql requests

❯ yarn explain peer-requirements p6791f
➤ YN0000: gatsby-recipes@npm:0.14.0 provides graphql@npm:15.5.0 with version 15.5.0, which doesn't satisfy the following requirements:

➤ YN0000: express-graphql@npm:0.9.0 [3808c] → ^14.4.1 ✘

❯ yarn explain peer-requirements p88b97
➤ YN0000: gatsby@npm:3.3.0 [16a18] provides graphql@npm:15.5.0 with version 15.5.0, which doesn't satisfy the following requirements:

➤ YN0000: express-graphql@npm:0.9.0 [3808c] → ^14.4.1 ✘
```

### Environment

```shell
❯ gatsby info --clipboard

  System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.11.0 - /usr/local/bin/node
    Yarn: 2.4.1 - /usr/local/bin/yarn
    npm: 7.6.0 - /usr/local/bin/npm
  Languages:
    Python: 3.8.5 - /Users/klittlepage/opt/miniconda3/bin/python
  Browsers:
    Chrome: 89.0.4389.128
    Firefox: 87.0
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.3.0 => 3.3.0
    gatsby-plugin-image: ^1.3.0 => 1.3.0
    gatsby-plugin-manifest: ^3.3.0 => 3.3.0
    gatsby-plugin-react-helmet: ^4.3.0 => 4.3.0
    gatsby-plugin-sass: ^4.3.0 => 4.3.0
    gatsby-plugin-sharp: ^3.3.0 => 3.3.0
    gatsby-plugin-typescript: ^3.3.0 => 3.3.0
    gatsby-source-filesystem: ^3.3.0 => 3.3.0
    gatsby-transformer-sharp: ^3.3.0 => 3.3.0
```

**Comment by LekoArts** [comment]
Thanks for the issue! Seems like an issue only happening on yarn 2. We'd be happy to review a PR upgrading the dependencies (with an investigation if any breaking changes would affect us)

**Comment by jamesaucode** [comment]
Happy to take a look at this. Also it seems like bumping to `express-graphql: v0.10` will not resolve the issue as v0.10 uses `graphql 15.2` ? Might need to bump it up to at least 0.11. I can do some investigation to see if will be breaking.

**Comment by pranavn35** [comment]
Try installing a lower version of the npm package.
See https://v8.dev/blog/math-random for details.
