### ISSUE TITLE
Problem building blog on Netlify

### ISSUE THREAD

**Issue by arsmth** [gatsbyjs/gatsby#3091]
My site builds and works fine locally but Netlify build from repo fails. Am I doing something wrong?

`7:06:32 PM: success Building CSS — 7.214 s
7:06:49 PM: success Building production JavaScript bundles — 17.286 s
7:06:54 PM: 
7:06:54 PM: error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND
7:06:54 PM: 
  89 | 
  90 | export default function Blog({data}) {
> 91 |   const { edges: posts } = data.allMarkdownRemark
     |                                 ^
  92 |   return (
  93 |     <div>
  94 |       {/* <BackLinkContainer>

  WebpackError: Cannot read property 'allMarkdownRemark' of undefined
  
  - index.js:91 Blog
    src/pages/blog/index.js:91:33
  
  - ReactCompositeComponent.js:306 ReactCompositeComponentWrapper._constructComp    onentWithoutOwner
    ~/react-dom/lib/ReactCompositeComponent.js:306:1
  
  - ReactCompositeComponent.js:282 ReactCompositeComponentWrapper._constructComp    onent
    ~/react-dom/lib/ReactCompositeComponent.js:282:1
  
  - ReactCompositeComponent.js:185 ReactCompositeComponentWrapper.mountComponent    ~/react-dom/lib/ReactCompositeComponent.js:185:1
  
  - ReactReconciler.js:43 Object.mountComponent
    ~/react-dom/lib/ReactReconciler.js:43:1
  
  - ReactMultiChild.js:234 ReactDOMComponent.mountChildren
    ~/react-dom/lib/ReactMultiChild.js:234:1
  
  - ReactDOMComponent.js:657 ReactDOMComponent._createContentMarkup
    ~/react-dom/lib/ReactDOMComponent.js:657:1
  
  - ReactDOMComponent.js:524 ReactDOMComponent.mountComponent
    ~/react-dom/lib/ReactDOMComponent.js:524:1
  
  - ReactReconciler.js:43 Object.mountComponent
    ~/react-dom/lib/ReactReconciler.js:43:1
  
  - ReactCompositeComponent.js:368 ReactCompositeComponentWrapper.performInitial    Mount
    ~/react-dom/lib/ReactCompositeComponent.js:368:1
  
7:06:54 PM: Cached NPM modules
7:06:54 PM: Saved Cache Directory
7:06:56 PM: Build complete: exit code: 1
7:06:56 PM: Cleaning up docker container
7:06:57 PM: Error running command: Build script returned non-zero exit code: 1
7:06:57 PM: An error occurred while building the site, skipping the deploy and cache refresh.
7:06:57 PM: Build script returned non-zero exit code: 1
7:07:00 PM: Finished processing build request in 2m20.808351633s`

**Comment by KyleAMathews** [comment]
Try building your site on a Linux vm. Problems often crop up when you move to linux from Windows or Mac.

**Comment by rshah03** [comment]
@KyleAMathews I seem to be having a similar issue with my site. I don't get any errors locally or on the production build via Netlify, but the route to my blog page just takes me back to my index path ("/") in production, while changing the URL to "www.mysite.com/blog" after clicking the link. It works fine locally. I've tested several linking methods on multiple browsers.

**Comment by wangsongiam** [comment]
Looks similar to my case #2830

**Comment by MaralS** [comment]
It's also similar to my issue #3425

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
