### ISSUE TITLE
Configuration flag interdependencies (unexpected activation of DEV_SSR)

### ISSUE THREAD

**Issue by coreyward** [gatsbyjs/gatsby#30950]
## Description

Using the following configuration in `v2.32.12` or `v3.2.1` results in `DEV_SSR` being enabled unexpectedly and without a warning that one of the other flags might require DEV_SSR:

```js
module.exports = {
  flags: {
    DEV_SSR: false,
    FAST_DEV: true,
    PARALLEL_SOURCING: true,
  },
}
```

Here's a reproduction using `gatsby new` with no starter and the flags set in `gatsby-config.js`. Running `gatsby develop` in the root of this repo results in the following build output:

> info The following flags are active:
> - FAST_DEV · Enable all experiments aimed at improving develop server start time
> - PARALLEL_SOURCING · EXPERIMENTAL · (Umbrella Issue (https://gatsby.dev/parallel-sourcing-feedback)) ·
> Run all source plugins at the same time instead of serially. For sites with multiple source plugins,
> this can speedup sourcing and transforming considerably.
> - DEV_SSR · (Umbrella Issue (https://gatsby.dev/dev-ssr-feedback)) · Server Side Render (SSR) pages on
> full reloads during develop. Helps you detect SSR bugs and fix them without needing to do full builds.
> - PRESERVE_FILE_DOWNLOAD_CACHE · (Umbrella Issue (https://gatsby.dev/cache-clearing-feedback)) · Don't
> delete the downloaded files cache when changing gatsby-node.js & gatsby-config.js files.
> - PRESERVE_WEBPACK_CACHE · (Umbrella Issue (https://gatsby.dev/cache-clearing-feedback)) · Don't delete
> webpack's cache when changing gatsby-node.js & gatsby-config.js files.

### Expected result

I'd expect SSR in development to be disabled or for there to be a descriptive error thrown conveying that one of the other flags requires DEV_SSR to be enabled.

### Actual result

DEV_SSR is activated and shown to be active via the `develop` command output as though the flag was not ever configured

### Environment

> gatsby: ^2.32.12 => 2.32.12

or

> gatsby: ^3.2.1 => 3.2.1

**Comment by KyleAMathews** [comment]
FAST_DEV is a "meta flag" that includes DEV_SSR — there's a bug where that's overriding your `DEV_SSR: false`. We'll fix that. In the meantime though, if you remove `FAST_DEV` & manually add the other flags you want, then `DEV_SSR: false` will work again as expected.

BTW, did you see troubles w/ DEV_SSR? Would love to see them put into the discussion — https://github.com/gatsbyjs/gatsby/discussions/28138

**Comment by coreyward** [comment]
Thanks @KyleAMathews. Re: DEV_SSR issues — mostly just that it's much slower and crashes the development server on some errors. It also seems to exacerbate issues that seem cache-oriented in nature. I don't have the bandwidth to detail or investigate these issues, hence not sharing them in the discussion.

**Comment by KyleAMathews** [comment]
Which part is slower? Normal hot reloading or doing a full refresh?

**Comment by coreyward** [comment]
@KyleAMathews I haven't measured, but it feels like first page loads and hot reloading are both considerably slower.
