### ISSUE TITLE
Google Web Cache redirection

### ISSUE THREAD

**Issue by yES-iAM** [gatsbyjs/gatsby#30958]
## Description

When we check last two days of google web cache page of **websites made in gatsbyjs**, it will redirect to current URL page.
Maybe it is happing because of @reach/router package used by gatsbyjs for location changing.

If disable JavaScript from browser, than this issue will not accrue. 

https://user-images.githubusercontent.com/64223403/115393071-e921be80-a1fe-11eb-87c0-b76b3df32624.mp4

### Steps to reproduce

Visit below google web cache URL:-
[cache:https://www.gatsbyjs.com/](cache:https://www.gatsbyjs.com/)

### Expected result

It must show cache information of page.

### Actual result

Redirecting to current page.

### Environment

  System:
    OS: Windows 10 10.0.19042
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.128
    Edge: Spartan (44.19041.906.0), Chromium (89.0.774.77)
  npmPackages:
    gatsby: ^2.32.12 => 2.32.12 
    gatsby-omni-font-loader: ^1.3.0 => 1.3.0 
    gatsby-plugin-build-date: ^1.0.0 => 1.0.0 
    gatsby-plugin-express: ^1.1.6 => 1.1.6 
    gatsby-plugin-manifest: ^2.0.29 => 2.12.1 
    gatsby-plugin-preact: ^4.0.16 => 4.7.0 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.10.0 
    gatsby-plugin-sass: ^2.0.11 => 2.8.0 
    gatsby-plugin-sharp: ^2.7.1 => 2.14.3 
    gatsby-plugin-sitemap: ^2.10.0 => 2.12.0 
    gatsby-plugin-split-css: ^1.0.2 => 1.0.2 
    gatsby-plugin-styled-components: ^3.4.0 => 3.10.0 
    gatsby-source-filesystem: ^2.0.33 => 2.11.1 
    gatsby-transformer-sharp: ^2.1.18 => 2.12.1 
  npmGlobalPackages:
    gatsby-cli: 3.3.0

**Comment by vladar** [comment]
I can confirm the behavior but not sure if we should qualify this as a bug. We redirect explicitly because the expected page path doesn't match the actual browser location:

https://github.com/gatsbyjs/gatsby/blob/d036f9213ef96eb9581dea3e2e3409ba9bba0e72/packages/gatsby/cache-dir/production-app.js#L131-L151

Not sure if there is a good reason to add special cases when the page is loaded from a different domain. CC @wardpeet

**Comment by Frostbourn** [comment]
Any news on that?
