### ISSUE TITLE
[gatsby-config.js] Documentation needed

### ISSUE THREAD

**Issue by Charon77** [gatsbyjs/gatsby#3095]
Following #2032, We need to have docs for `gatsby-config.js`.

It seems Joi is used for validating the schema and the spec can be derived from [here][joi].

[joi]:
https://github.com/gatsbyjs/gatsby/blob/e9bb320ef7ac5d36e1a6ff9898c0a2fbc2c58c17/packages/gatsby/src/joi-schemas/joi.js

**Comment by calcsam** [comment]
Yes, this should be a new page living under "Reference" in the docs. Want to add this documentation @Charon77?

**Comment by Charon77** [comment]
Sure thing @calcsam 
By the way, how to make the pages appear in the left sidebar? Is there a guide on how to add to the gatsby reference?

**Comment by fk** [comment]
Hey @Charon77! Add your new Markdown document here: https://github.com/gatsbyjs/gatsby/tree/master/docs/docs, then link it there: https://github.com/gatsbyjs/gatsby/blob/38a865f7b5b25bbdedd51f2d0f6d8e45378e07e3/www/src/pages/docs/doc-links.yaml#L59-L72

**Comment by amberleyromo** [comment]
Hey @Charon77, are you still adding these docs?

**Comment by Charon77** [comment]
@amberleyromo honestly I hadn't got the time to even start. Feel free to take over 😄
I'll add stuffs if I can.

**Comment by KyleAMathews** [comment]
@amberleyromo's PR adding docs are in! Thanks!
