### ISSUE TITLE
gatsby-plugin-sitemap readme typo

### ISSUE THREAD

**Issue by alfredosalzillo** [gatsbyjs/gatsby#30957]
## Summary

[gatsby-plugin-sitemap](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sitemap) readme contains a typo.
The `exclude` options should be `excludes`.

**Comment by LekoArts** [comment]
Fixed in https://github.com/gatsbyjs/gatsby/commit/2429327d10f9124e4cb0dd0e80001cc5dbbae50b - thanks!
