### ISSUE TITLE
page data JSON bundled in JS 

### ISSUE THREAD

**Issue by GreatState** [gatsbyjs/gatsby#30963]
## Description

When records hit 150 (pages) then page-data.json is bundled into one of the main bundles

![image](https://user-images.githubusercontent.com/35596657/115424859-fd61bd80-a1f6-11eb-8cc7-c2f938451cad.png)

This seems strange to me as these files are route dependent and only need to be loaded per route

### Environment

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.128
    Firefox: 87.0
    Safari: 14.0.3
  npmPackages:
    gatsby: 2.24.7 => 2.24.7 
    gatsby-image: ^2.3.4 => 2.4.21 
    gatsby-plugin-algolia: ^0.5.0 => 0.5.0 
    gatsby-plugin-google-tagmanager: ^2.2.3 => 2.3.16 
    gatsby-plugin-manifest: ^2.3.5 => 2.4.35 
    gatsby-plugin-offline: ^3.1.4 => 3.2.33 
    gatsby-plugin-react-axe: ^0.2.2 => 0.2.2 
    gatsby-plugin-react-helmet: ^3.2.4 => 3.3.14 
    gatsby-plugin-remote-images: ^1.0.7 => 1.0.7 
    gatsby-plugin-scss-typescript: ^4.0.10 => 4.0.13 
    gatsby-plugin-sharp: ^2.5.6 => 2.6.42 
    gatsby-plugin-sitemap: ^2.3.5 => 2.4.17 
    gatsby-plugin-typescript: ^2.3.3 => 2.4.22 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.22 => 1.1.22 
    gatsby-transformer-sharp: ^2.4.6 => 2.5.18 
  npmGlobalPackages:
    gatsby-cli: 2.12.82

**Comment by GreatState** [comment]
Think i've found the issue. the npm Ci build (where this is happening)  is using gatsby 2.20.26. Inside the page template it's doing a load static graphql queries. Looks like its bundling the json into the js build. 

if running yarn which has gatsby pinned at 2.24.80 it doesn't bundle

**Comment by herecydev** [comment]
I haven't looked at the webpack config in a while but as a guess it might be only splitting if it's over a certain size. That's actually deseriable as less network requests

**Comment by LekoArts** [comment]
Hi!

Thanks for the issue! We'll need a [minimal reproduction][reproduction] for this on the latest version of Gatsby (v3.x). We currently only accept critical security fixes for Gatsby v2 so if it turns out that the behavior itself is not working as intended in Gatsby v3 we'll consider it as a bug, otherwise as a "won't fix".

The versions you're using there are 7-9 months old.

[reproduction]: https://gatsby.dev/reproduction

**Comment by GreatState** [comment]
I think it maybe due to this issue: https://github.com/gatsbyjs/gatsby/pull/24805

looks like the page template is making static queries which is then being bundled in the main JS.

**Comment by GreatState** [comment]
This is a codebase we have been asked to review rather than building ourselves

**Comment by GreatState** [comment]
out of interest is it easy to update to gatsby 3? i assumed i'd have to look at all the other dependancies and it perhaps included breaking changes

**Comment by LekoArts** [comment]
Thanks for clearing that up!

You can find the migration guide here: https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/

From what we've seen the complexity of an upgrade mapped to how much you used webpack as with the move to webpack 5 there were some bigger changes. The `gatsby-` plugins we maintain here in our monorepo are all compatible with Gatsby v3, you'd need to check third-party plugins and packages if they are compatible with Gatsby v3, webpack 5 and React 17.
