### ISSUE TITLE
gatsby-source-wordpress: cannot fetch node more than limit on woocommerce products

### ISSUE THREAD

**Issue by harunalrashyid** [gatsbyjs/gatsby#30990]
## Description

Cannot get fetch node more than schema default limit woocommerce product 
both on development and production,  even using options.schema.perPage 

### Steps to reproduce
1. Set the option schema into 1000

![image](https://user-images.githubusercontent.com/43124304/115612717-c46c3a80-a315-11eb-8e2a-f2cb7b5c61ad.png)

2. Run `yarn develop or gatsby develop`

3. Query on graphql IDE http://localhost:8000/___graphql <br><br>The first schema comes from plugin [gatbsy-source-woocommere](https://www.gatsbyjs.com/plugins/@pasdo501/gatsby-source-woocommerce/)<br>and the second schema from plugin [gatbsy-source-wordpress](https://www.gatsbyjs.com/plugins/gatsby-source-wordpress/)

![image](https://user-images.githubusercontent.com/43124304/115611794-bf5abb80-a314-11eb-8a7a-d810493ff199.png)

### Expected result

The total count should 130, since the woocommerce product are 130 at the currently i'm writing this issue

### Actual result

The total count show only 100 on plugin gatbsy-source-woocommerce.

### Environment

<pre><code>
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-2435M CPU @ 2.40GHz
    Shell: 3.2.57 - /bin/bash

  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.10.0 - /usr/local/bin/npm

  Languages:
    Python: 2.7.16 - /usr/bin/python

  Browsers:
    Chrome: 89.0.4389.128
    Firefox: 87.0
    Safari: 13.1.2

  npmPackages:
    gatsby: ^2.27.2 => 2.32.12
    gatsby-image: ^2.2.39 => 2.7.0
    gatsby-link: ^2.7.0 => 2.7.0
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5
    gatsby-plugin-google-analytics: ^2.1.35 => 2.7.0
    gatsby-plugin-htaccess: ^1.4.0 => 1.4.0
    gatsby-plugin-manifest: ^2.2.39 => 2.8.0
    gatsby-plugin-no-sourcemaps: ^2.6.0 => 2.6.0
    gatsby-plugin-nodejs: ^0.7.0 => 0.7.0
    gatsby-plugin-offline: ^3.0.32 => 3.6.0
    gatsby-plugin-react-helmet: ^3.1.21 => 3.6.0
    gatsby-plugin-react-leaflet: ^3.0.0 => 3.0.0
    gatsby-plugin-sass: ^2.7.0 => 2.7.0
    gatsby-plugin-sharp: ^2.4.3 => 2.10.0
    gatsby-source-filesystem: ^2.1.46 => 2.7.0
    gatsby-source-graphql: ^2.1.33 => 2.10.0
    gatsby-source-wordpress: ^4.0.1 => 4.0.1
    gatsby-transformer-sharp: ^2.3.13 => 2.8.0
</code></pre>

**Comment by harunalrashyid** [comment]
I think i know the reason, it's default maximum wp-graphql on wordpress server and 
we must increase the limit based on this issue
https://github.com/wp-graphql/wp-graphql/issues/261

after i'm increase the limit on wordpress, it's fetch node as expected.

**Comment by veryspry** [comment]
Closing this since it looks like you found a solution!
