### ISSUE TITLE
[gatsby-plugin-manifest] crashes with latest Gatsby 3.3.1 wrt sharp

### ISSUE THREAD

**Issue by logemann** [gatsbyjs/gatsby#31004]
## Description

For some reason after removing and adding gatsby-plugin-manifest, i cant gatsby to start anynmore because of sharp problems.

```
objc[60142]: Class GNotificationCenterDelegate is implemented in both /Users/ml/development/projects/gatsby/der-mercedes-abgasskandal/node_modules/gatsby-plugin-manifest/node_modules/sharp/vendor/8.10.6/lib/libvips-cpp.42.dylib (0x10d7dfeb0) and /Users/ml/development/projects/gatsby/der-mercedes-abgasskandal/node_modules/sharp/vendor/8.10.5/lib/libvips.42.dylib (0x10f4acce0).
...
success onPreExtractQueries - 0.001s
⠸ extract queries from components
**
ERROR:/Users/runner/work/sharp/sharp/vendor/8.10.5/include/vips/VImage8.h:125:vips::VObject &vips::VObject::operator=(const vips::VObject &): assertion failed: (!a.vobject || VIPS_IS_OBJECT( a.vobject ))
Bail out! ERROR:/Users/runner/work/sharp/sharp/vendor/8.10.5/include/vips/VImage8.h:125:vips::VObject &vips::VObject::operator=(const vips::VObject &): assertion failed: (!a.vobject || VIPS_IS_OBJECT( a.vobject ))
**
ERROR:/Users/runner/work/sharp/sharp/vendor/8.10.5/include/vips/VImage8.h:125:vips::VObject &vips::VObject::operator=(const vips::VObject &): assertion failed: (!a.vobject || VIPS_IS_OBJECT( a.vobject ))
Bail out! ERROR:/Users/runner/work/sharp/sharp/vendor/8.10.5/include/vips/VImage8.h:125:vips::VObject &vips::VObject::operator=(const vips::VObject &): assertion failed: (!a.vobject || VIPS_IS_OBJECT( a.vobject ))
**
ERROR:/Users/runner/work/sharp/sharp/vendor/8.10.5/include/vips/VImage8.h:125:vips::VObject &vips::VObject::operator=(const vips::VObject &): assertion failed: (!a.vobject || VIPS_IS_OBJECT( a.vobject ))
Bail out! ERROR:/Users/runner/work/sharp/sharp/vendor/8.10.5/include/vips/VImage8.h:125:vips::VObject &vips::VObject::operator=(const vips::VObject &): assertion failed: (!a.vobject || VIPS
not finished extract queries from components - 1.008s

error Command failed with signal "SIGABRT".
```

I also dont know what this path "/Users/runner/work/sharp/sharp/vendor/8.10.5/include/vips/VImage8.h" means... there is no such folder/file on my mac. 

### Steps to reproduce

used the Gatsby v3 Starter for get up and running and everything looked fine. Then i re-added (gatsby-plugin-shart) and now i get those errors on startup. Can only solve it by completely removing the plugin.

### Expected result

Startup of my project.

### Actual result

see above.

### Environment

  System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.8.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.5.0 - /usr/local/bin/npm
  Languages:
    Python: 3.9.0 - /Users/ml/.pyenv/shims/python
  Browsers:
    Chrome: 89.0.4389.128
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.3.1 => 3.3.1
    gatsby-plugin-gatsby-cloud: ^2.2.0 => 2.2.0
    gatsby-plugin-image: ^1.2.1 => 1.2.1
    gatsby-plugin-manifest: ^3.3.0 => 3.3.0
    gatsby-plugin-netlify: ^3.3.0 => 3.3.0
    gatsby-plugin-offline: ^4.2.0 => 4.2.0
    gatsby-plugin-postcss: ^4.3.0 => 4.3.0
    gatsby-plugin-react-helmet: ^4.2.0 => 4.2.0
    gatsby-plugin-robots-txt: ^1.5.6 => 1.5.6
    gatsby-plugin-sharp: ^3.2.1 => 3.2.1
    gatsby-source-filesystem: ^3.2.0 => 3.2.0
    gatsby-transformer-sharp: ^3.2.0 => 3.2.0
  npmGlobalPackages:
    gatsby-cli: 2.12.110

**Comment by logemann** [comment]
Deleted everything in my project regarding NPM/Yarn and now it works. Weird.

**Comment by Isaac-Tait** [comment]
I am getting the same error after trying to upgrade to Gatsby v.3 

@logemann When you said "Deleted everything in my project regarding NPM..." What exactly did you delete? Just the `package-lock.json` & `node_modules` am I missing anything else?

**Comment by Isaac-Tait** [comment]
For anyone coming here in the future I ran the following commands and it cleared up the error.

```
rm -rf node_modules
npm install
```

**Comment by Ianpig** [comment]
I got same problem. It randomly happened. 
I can run gatsby clean and gatsby build or gatsby develop to fix it. But sometime it didn't work. 
The only way to fix that is rm rf node_modules/...

- gatsby info
 ```
 System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.3.0 -
~/.nvm/versions/node/v16.3.0/bin/node
    Yarn: 1.22.19 -
~/.nvm/versions/node/v16.3.0/bin/yarn
    npm: 7.15.1 -
~/.nvm/versions/node/v16.3.0/bin/npm
  Languages:
    Python: 3.7.10 - /Users/ian/.pyenv/shims/python
  Browsers:
    Chrome: 103.0.5060.134
    Safari: 15.5
  npmPackages:
    gatsby: ^4.19.2 => 4.19.2
    gatsby-image: ^3.11.0 => 3.11.0
    gatsby-plugin-google-analytics: ^4.18.0 =>
4.19.0
    gatsby-plugin-image: ^2.19.0 => 2.19.0
    gatsby-plugin-manifest: ^4.19.0 => 4.19.0
    gatsby-plugin-postcss: ^5.18.0 => 5.19.0
    gatsby-plugin-react-helmet: ^5.19.0 => 5.19.0
    gatsby-plugin-sharp: ^4.19.0 => 4.19.0
    gatsby-plugin-sitemap: ^5.18.1 => 5.19.0
    gatsby-remark-copy-linked-files: ^5.19.0 =>
5.19.0
    gatsby-remark-images: ^6.19.0 => 6.19.0
    gatsby-remark-prismjs: ^6.19.0 => 6.19.0
    gatsby-remark-responsive-iframe: ^5.19.0 =>
5.19.0
    gatsby-remark-smartypants: ^5.19.0 => 5.19.0
    gatsby-source-filesystem: ^4.19.0 => 4.19.0
    gatsby-transformer-remark: ^5.18.1 => 5.19.0
    gatsby-transformer-sharp: ^4.19.0 => 4.19.0
 ```
