### ISSUE TITLE
PRESERVE_FILE_DOWNLOAD_CACHE doesn't appear to work on Windows

### ISSUE THREAD

**Issue by nrandell** [gatsbyjs/gatsby#31015]
## Description

I've set the PRESERVE_FILE_DOWNLOAD_CACHE flag, but it still deletes the gatsby-source-filesystem directory.

### Steps to reproduce

Set the `PRESERVE_FILE_DOWNLOAD_CACHE` in `gatsby-config.js`
Run `gatsby develop`
Modify `gatsby-node.js`
Re-run `gatsby develop`
Interrupt the build just after it says `initialize cache`

Check the `.cache\caches\gatsby-source-filesystem` - it should still be there and fully populated.

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

The `gatsby-source-filesystem` folder should still exist and be populated. 
Also a modification of gatsby-node.js should not take very long to build as no assets need to be downloaded.

### Actual result

The folder has been deleted and depending on when you interrupt, just being repopulated.
The build also takes some time as it downloads the assets again.

### Environment

  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 PRO 4750G with Radeon Graphics
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.9
  Browsers:
    Edge: Spartan (44.19041.906.0), Chromium (90.0.818.42), ChromiumDev (User home =
'C:\Users\nickr\AppData\Local\IISExpress'
IIS USER HOME configured)
  npmPackages:
    gatsby: ^3.3.1 => 3.3.1
    gatsby-plugin-gatsby-cloud: ^2.3.0 => 2.3.0
    gatsby-plugin-image: ^1.3.1 => 1.3.1
    gatsby-plugin-manifest: ^3.3.0 => 3.3.0
    gatsby-plugin-postcss: ^4.3.0 => 4.3.0
    gatsby-plugin-react-helmet: ^4.3.0 => 4.3.0
    gatsby-plugin-sharp: ^3.3.1 => 3.3.1
    gatsby-source-filesystem: ^3.3.0 => 3.3.0
    gatsby-transformer-sharp: ^3.3.0 => 3.3.0
  npmGlobalPackages:
    gatsby-cli: 3.3.0
    gatsby-plugin-generate-typings: 0.9.9
    gatsby-source-graphcms: 2.0.0
    gatsby-transformer-extracted-svg: 1.0.1

## Possible fix
I've managed to get it to work better by modifying 'services/initialise.js' and added the line
`deleteGlobs.push(`!${cacheDirectory}/caches`);` (line 389) when preserving the file download cache.

**Comment by LekoArts** [comment]
Hi, thanks for the issue! For flags & experiments we use Discussion to collect feedback (the CLI output also links to this). Please post your issue here: https://github.com/gatsbyjs/gatsby/discussions/28331

Thanks!
