### ISSUE TITLE
[gatsby-react-router-scroll] useScrollRestoration doesn't work with wrapPageElement

### ISSUE THREAD

**Issue by mohatt** [gatsbyjs/gatsby#31012]
## Description

`useScrollRestoration` hook doesn't work as expected when used in a Layout component that doesn't get re-mounted on route change (using `wrapPageElement`). This is due to the fact that the effect that restores the element scroll position is only run once when the component mounts due to the empty dependencies array `[]`.

https://github.com/gatsbyjs/gatsby/blob/4c0916b25b3b1c8758ff33f877f4b588b491ffc7/packages/gatsby-react-router-scroll/src/use-scroll-restoration.ts#L17-L22

Adding `location` or `location.key` to the effect dependencies should fix the issue. See #31013

### Steps to reproduce

https://codesandbox.io/s/proud-leftpad-cy7h6

### Expected result

Element scroll position should be restored.

### Actual result

Element scroll position doesn't get restored.

### Environment

```
  System:
    OS: Linux 5.4 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.1/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    gatsby: ^3.3.1 => 3.3.1
```

**Comment by vladar** [comment]
Should be fixed via https://github.com/gatsbyjs/gatsby/pull/26861
