### ISSUE TITLE
[gatsby-recipes] Remove duplicate Babel install

### ISSUE THREAD

**Issue by aaronadamsCA** [gatsbyjs/gatsby#31023]
The package `remark-mdxjs` is deprecated and no longer being published:

https://github.com/mdx-js/mdx/tree/main/packages/remark-mdxjs

According to its README its behaviour is now included in `remark-mdx`.

`remark-mdxjs` had an unranged outdated `@babel/core` dependency. The result is an entire second Babel install when installing Gatsby.

I think these lines should all be safely removable:

https://github.com/gatsbyjs/gatsby/blob/df3f184ee9ea1367726bd52dc4b6f130b8fa2c59/packages/gatsby/package.json#L241
https://github.com/gatsbyjs/gatsby/blob/df3f184ee9ea1367726bd52dc4b6f130b8fa2c59/packages/gatsby-recipes/package.json#L53
https://github.com/gatsbyjs/gatsby/blob/df3f184ee9ea1367726bd52dc4b6f130b8fa2c59/packages/gatsby-recipes/package.json#L122
https://github.com/gatsbyjs/gatsby/blob/54d4721462b9303fed723fdcb15ac5d72e103778/packages/gatsby-recipes/src/parser/index.js#L3
https://github.com/gatsbyjs/gatsby/blob/54d4721462b9303fed723fdcb15ac5d72e103778/packages/gatsby-recipes/src/parser/index.js#L54

There are probably other references to the package to clean up as well.

**Comment by vladar** [comment]
Thanks for the suggestion @aaronadamsCA Are you up to opening a PR with this change?

**Comment by jithenshriyan** [comment]
I'd be able to find the references and remove and replace the dependency. Let me know if I could work on this if you both prefer. Thanks!

**Comment by jithenshriyan** [comment]
Hi, I had some time tonight and went ahead and completed the issue. Hope it saves you time from doing it yourself.

Just submitted a PR for review. Thanks!

**Comment by LekoArts** [comment]
The opened PR is invalid now (as the fork was deleted) so we're still open to PRs!

**Comment by aaronadamsCA** [comment]
Retitled to clarify why this should be done. Seems the existing PR is dead, so @LekoArts I can try picking this up myself.

**Comment by LekoArts** [comment]
Cool!

**Comment by aaronadamsCA** [comment]
Not stale.

I think #32377 should be fine despite the failing tests, since I'm pretty sure that's just intermittent failure (likely because Yarn v1 is broken/dead and rarely builds a valid dependency tree). But if anyone else sees anything to add, please comment!

**Comment by amitsin6h** [comment]
taking up on this issue

**Comment by aaronadamsCA** [comment]
Happy to update the PR if someone can commit to review and merge before it goes stale again :)

**Comment by aaronadamsCA** [comment]
@LekoArts / @vladar , could you reopen?

Happy to redo the PR anytime, but last time it just sat there unreviewed until it was stale, so I'd like to know it'll get merged before I take the time again :)

**Comment by aaronadamsCA** [comment]
Yes, absolutely. Thanks for confirming, then! Let me know if there's anything I could do to help with that initiative.
