### ISSUE TITLE
Routes to other pages not working in production only

### ISSUE THREAD

**Issue by rshah03** [gatsbyjs/gatsby#3104]
None of my links from my index route ("/") are working in production. They all reload the index page but the URL changes to reflect that the page has been navigated to. 

I.e. if I click a button to take me to my blog page, the url will change to "www.mysite.com/blog" but the home page just reloads. 

I have tried using <Button> with href, and Link via gatsby-link. Neither of which seem to make a difference.

The weird part is that external links placed in the navbar within the `index.js` file in the Layouts folder work fine. 

I haven't made any changes to the site for over a month, when it was working completely fine. Everything works as intended in development. And there are no errors in dev OR production. 

Any idea as to how I might solve this? I need to fix this ASAP. Any help is appreciated! Thanks.

**Comment by KyleAMathews** [comment]
You need to use `<Link />` from gatsby-link.

Beyond that, it's hard to tell what might be wrong. Is there console errors?

**Comment by rshah03** [comment]
@KyleAMathews I do use that, but they still don't seem to work. No console errors. The Netlify deployment console ends with complete success, and it's the same on my local machine. 

I haven't changed anything as far as the underlying code, which was working fine last time I checked (a few weeks ago). Was there a recent update pushed to gatsby? Maybe I need to update? 

These are my dependencies: 
[

     "gatsby": "^1.8.12",
     "gatsby-link": "^1.6.8",
     "gatsby-plugin-react-helmet": "^1.0.3",
     "gatsby-plugin-sass": "^1.0.4",
     "gatsby-source-filesystem": "^1.4.6",
     "gatsby-transformer-remark": "^1.7.5",
     "react-bootstrap": "^0.31.3",
     "semantic-ui-react": "^0.73.
]

**Comment by rshah03** [comment]
I have reverted to a deploy from September 28th through the Netlify CMS. Everything works fine here. Any commits I make now will break it. Even if all I do is erase an empty line from a one file and only that one file, the links stop working. 

I effectively cannot work on the site until this is resolved. Has anyone come across any potential solution?

**Comment by KyleAMathews** [comment]
This isn't normal behavior — can you try to replicate the behavior you're seeing starting with a fresh site from running `gatsby new`?

**Comment by KyleAMathews** [comment]
also try upgrading all packages to the latest.

**Comment by rshah03** [comment]
Okay, so I updated all of my packages via`npm update --save [package name]` to their most recent optimal versions, created a copy of the site in a new github repo, and deployed it via Netlify. No errors in develop or production, but the issue persists.

When you say `gatsby new` do you mean to start from scratch?

**Comment by Swizec** [comment]
I'm experiencing a similar issue. In my case clicking on a `<Link />` changes the URL, but not the rendered page. If you reload on the new URL, it first renders the correct page, then re-renders with the index page.

![bug](https://user-images.githubusercontent.com/56883/33589826-26f27eac-d949-11e7-9e0f-4bb5f72baa0a.gif)

I upgraded to the latest packages 2 days ago. Gatsby version 1.9.127

**Comment by rshah03** [comment]
@Swizec Are you buy any chance hosting your site via Netlify?

**Comment by KyleAMathews** [comment]
Any console errors that you're seeing?

**Comment by Swizec** [comment]
No console errors

**Comment by KyleAMathews** [comment]
Can one of you start with an empty site and slowly add in new pages or code until you can replicate the problem? Or isolate the release in which the problem started? Or check if any of the example sites illustrate the problem? I'd love to look at this but need a way to reproduce the problem.

**Comment by rshah03** [comment]
Although I don't have time to create from scratch at the moment, I will go ahead and check the example sites to see if I can find the problems. I've been speaking with support staff over at Netlify to make sure the issue isn't from their hosting service(s). 

Once I have some free time, I'll start to recreate my site from scratch and see if I can replicate the issue, if it's still needed at that time. 

If @Swizec is indeed hosting via Netlify, I'm almost certain that the issue lies within Netlify's servers. Maybe replicas are lagging on their backend.

**Comment by Swizec** [comment]
> If @Swizec is indeed hosting via Netlify, I'm almost certain that the issue lies within Netlify's servers. Maybe replicas are lagging on their backend.

I'm hosting via zeit.co

I can try to replicate in a from-scratch environment in a couple days.

**Comment by KyleAMathews** [comment]
Played around with @Swizec's site and found that building locally with a `pathPrefix` in the `gatsby-config.js` is what was breaking things. Commented that out and things worked as expected.

Not sure when or where this started happening. Found it by adding console.log to find-page.js and seeing that pathPrefix was being passed in.

**Comment by KyleAMathews** [comment]
@rshah03 do you have a `pathPrefix` by chance in your gatsby-config.js?

**Comment by m-allanson** [comment]
Could this be related to #2551 ?

**Comment by rshah03** [comment]
FIxed. Removed `pathPrefix` from my `gatsby-config.js` file and everything is working again. Thanks @KyleAMathews! I think the #2551 nails it. 

Alternatively, I could build with the --prefix-paths flag if I wanted to keep that variable. 

Is there a way to resolve #2551?

**Comment by m-allanson** [comment]
@rshah03 A fix for #2551 should be live in Gatsby v1.9.149 now.

**Comment by m-allanson** [comment]
@KyleAMathews I saw you just closed #2740, this can probably be closed too?

**Comment by KyleAMathews** [comment]
Yup!

**Comment by m2mathew** [comment]
@msal4 I suggest opening a new issue to get more eyeballs on it. Seems like their work in January cleared up this issue for this one specific circumstance.

**Comment by msal4** [comment]
@m2mathew It seems like the issue resolved itself.. very odd!

**Comment by mustofa-binary** [comment]
When I click the same route as the rendered page, it's not navigating to the page (go to the top of the page). it happens only in deployed page.  is this related issue to this, or should I open a new issue?.

**Comment by kaisanjay** [comment]
I am also facing the same issue when deploying my site to s3 the links are not working. there is no error on console.

**Comment by brandondorner** [comment]
I am experiencing the same issue as @kaisanjay and @mustofa-binary 
I am not using pathPrefix and everything works fine while in gatsby develop, but once I build it starts to slightly fail.
It works as intended for the most part until I click the link for the same page that is rendered

**Comment by regulus33** [comment]
same here as @brandondorner I'm using aws Amplify, could it be something related to the way aws handles the build process?

**Comment by regulus33** [comment]
ah nevermind, looks like this is my issue https://github.com/aws-amplify/amplify-console/issues/991

**Comment by drydenwilliams** [comment]
I'm getting this on `https://ecoping.earth/blog/dezeens-website-carbon-emissions/` it redirects back to the homepage only on production. Similar setup to @kaisanjay on this one. @KyleAMathews is there any more information on this?

**Comment by MsPseudolus** [comment]
@drydenwilliams Hey there! Since the original issue is closed, could you do us a favor and start a new issue for this? Thank you!

**Comment by greatgumz** [comment]
@MsPseudolus was there ever a solve for this? or an issue I can track? I'm having the same problem as @drydenwilliams

**Comment by MsPseudolus** [comment]
@greatgumz I don't think @drydenwilliams  has created a new issue yet.

**Comment by zire** [comment]
Is there a solution for this? I still have the same issue, in 2022

I want to load this page [https://js6yw-cyaaa-aaaag-aaa5q-cai.ic0.app/start](https://js6yw-cyaaa-aaaag-aaa5q-cai.ic0.app/start). When you click on its URL to open, or paste the URL in Chrome directly, it will not open the referenced page but switch to the default [https://js6yw-cyaaa-aaaag-aaa5q-cai.ic0.app/](https://js6yw-cyaaa-aaaag-aaa5q-cai.ic0.app/). However, this `start` page has indeed been uploaded. It's in the `public` folder; I can see this page is uploaded when deploying files to the Internet Computer's canister; and this page can be visited by clicking `Article` on the top menu bar, then `Start`. @[ninegua](https://github.com/ninegua), who is from the team that built the Internet Computer (IC), confirmed that this issue has nothing to do with IC deployment. So this is the same old Gatsby issue that you guys have been discussing since 2017.

I don't use `pathPrefix` in my `gatsby-config.js`. This solution by @KyleAMathews doesn't solve my problem.

I'm on `Gatsby 4.6.2`.
