### ISSUE TITLE
using react components

### ISSUE THREAD

**Issue by danny-waite** [gatsbyjs/gatsby#3105]
guys, great project, a newb question, couldn't find the answer after initial search/testing.

Can I make use of regular react components, for example, something like fullpage-react, to provide dynamic functionality rather than having the output static generated?

**Comment by Swizec** [comment]
From what I can tell, the frontend is still running React so you can do whatever you want in the browser. I use it in a couple of my projects to add dynamic functionality and responding to click events and such.

You can also see that the React devtools pickup on your site being made in React. I think that proves it's all still there :)

**Comment by calcsam** [comment]
Yep! Anything normal React components can do, Gatsby can do using them. Just try plugging a fullpage-react sample component into one of the Gatsby starters (eg the Hello World starter: https://github.com/gatsbyjs/gatsby-starter-hello-world/blob/master/src/pages/index.js) if you want to see how i

**Comment by danny-waite** [comment]
thanks guys, yeah that worked, not exactly sure why my previous test didn't, but onwards...
