### ISSUE TITLE
Documentation issues: GatsbyImage is not defined 

### ISSUE THREAD

**Issue by thevangelist** [gatsbyjs/gatsby#31075]
## Description

Code example in https://www.gatsbyjs.com/plugins/gatsby-background-image/#gatsby-3--gatsby-plugin-image is not working:

```GatsbyImage is not defined react/jsx-no-undef```

### Steps to reproduce

1. Copy code
2. Use in your app

### Expected result

1. Copy code
2. It works

Gatsby images should be easy to use.

### Actual result

Gatsby images are a nightmare to use.

### Environment

Doesn't matter, as it's undefined.

**Comment by LekoArts** [comment]
This community plugin is maintained here: https://github.com/timhagn/gatsby-background-image
Please open an issue there. Thanks!
