### ISSUE TITLE
How to build without minifying HTML

### ISSUE THREAD

**Issue by BrunoBernardino** [gatsbyjs/gatsby#3107]
I'm having [this problem](https://reactjs.org/docs/error-decoder.html?invariant=32&args[]=2) which is mentioned [here in the docs](https://www.gatsbyjs.org/docs/deploy-gatsby/#dont-minify-html), but there's no explanation on _how_ to do that (building without minifying the HTML).

**Comment by dbrookes** [comment]
This is a setting on your production environment not Gatsby - the docs are saying to disable HTML minification on your CDN or web server you have deployed the site to.

For example, if you use Cloudflare you should disable HTML under Speed -> Auto Minify as it'll strip out HTML comments as part of the minification and break React.

**Comment by BrunoBernardino** [comment]
@dbrookes THANK YOU! That totally explains why I was so baffled to not finding any webpack setting to override. I completely forgot Cloudflare was doing that. Disabling it fixed the problem.
