### ISSUE TITLE
bundle failed trying to import fully specified paths 

### ISSUE THREAD

**Issue by Josehower** [gatsbyjs/gatsby#31077]
## Description

When using fully specified paths in imports
e.g
export { quiz as jsFunctions } from './js-functions.js';

gatsby send this error message

![image](https://user-images.githubusercontent.com/61600906/116280455-f9024b00-a788-11eb-8762-d8ecbdf215bd.png)

### Steps to reproduce

1. add `type: module` to package.json
2. create an import with  fully specified paths
3. try to run the gatsby site

### Expected result

Gatsby should allow imports with .js extention

### Actual result

Gatsby fail trying to generate JavaScript bundle

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

$ yarn gatsby info --clipboard
yarn run v1.22.5
$ D:\upleveled-softwork\courses\node_modules\.bin\gatsby info --clipboard

  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
  Binaries:
    Node: 16.0.0 - ~\AppData\Local\Temp\yarn--1619542324765-0.4257021548777624\node.CMD
    Yarn: 1.22.5 - ~\AppData\Local\Temp\yarn--1619542324765-0.4257021548777624\yarn.CMD
    npm: 7.10.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 90.0.4430.93
    Edge: Spartan (44.19041.906.0), Chromium (90.0.818.46)

✨  Done in 4.44s.

**Comment by wardpeet** [comment]
Hi @Josehower!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

We have tried the example above and we couldn't see the above error.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by karlhorky** [comment]
@wardpeet in trying to help José a bit just now, I thought it was maybe related to your PR over here: https://github.com/gatsbyjs/gatsby/pull/29576#issuecomment-827504491

**Comment by karlhorky** [comment]
I guess there may still be an issue with TypeScript (.tsx and .ts files) though, which may be the missing detail here.

**Comment by wardpeet** [comment]
🤔 maybe. Packages should not export ts or tsx files. I would love some kind of reproduction :)

**Comment by karlhorky** [comment]
Yep, José is working on one now, should be here soon :)

**Comment by Josehower** [comment]
https://codesandbox.io/s/serene-leaf-2vivd?file=/src/components/layout.tsx

here you have the link for an Out of the box gatsby sandbox with minimal changes
the changes done:

- the extension from .js to .tsx in the entry point and the Layout component
- add .js extention to import inside of index.tsx 

![image](https://user-images.githubusercontent.com/61600906/116390184-146b6580-a81e-11eb-85bd-828ab873310d.png)

![image](https://user-images.githubusercontent.com/61600906/116390237-20efbe00-a81e-11eb-96c7-4a9d24f2a295.png)

**Comment by karlhorky** [comment]
To be clear what we're trying to do:

1. We are using ESM via `"type": "module"` in `package.json`
2. We are using fully-specified import paths (with `.js` extension)
3. We are using TypeScript via `babel-loader` (via `babel-preset-gatsby`)

With regular TypeScript, this works, and is recommended: https://github.com/microsoft/TypeScript/issues/41887#issuecomment-741968855

> This is the intended behavior; because TypeScript doesn't modify JavaScript code you write, the import path you write should be the one you want to appear in the output `.js` file

With Gatsby TypeScript, it doesn't work.

Edit: Upon further reflection, this seems like a bug in webpack's module resolution algorithm (or in `babel-loader` and `ts-loader`)

@Josehower will create issues over there.

**Comment by karlhorky** [comment]
To be clear what we're trying to do:

1. We are using ESM via `"type": "module"` in `package.json`
2. We are using fully-specified import paths (with `.js` extension)
3. We are using TypeScript via `babel-loader` (via `babel-preset-gatsby`)

With regular TypeScript, this works, and is recommended: https://github.com/microsoft/TypeScript/issues/41887#issuecomment-741968855

> This is the intended behavior; because TypeScript doesn't modify JavaScript code you write, the import path you write should be the one you want to appear in the output `.js` file

With Gatsby TypeScript, it doesn't work.

Edit: Upon further reflection, this seems like a bug in webpack's module resolution algorithm (or in `babel-loader` and `ts-loader`)

@Josehower will create issues over there.
