### ISSUE TITLE
Missing onError handler for invocation 'building-schema': Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ 

### ISSUE THREAD

**Issue by olwe0002** [gatsbyjs/gatsby#31086]
## Description

Dynamic page queries are resulting in current version to new "typeBuilder"-type in gatsby/dist/schema/schema.js, and later on fail through assertValidName() in checkIsAllowedTypeName() because of its name. In the previous version, this type did not exist and therefore did not fail. I guess this type its not needed or at least the created type name is wrong.

### Steps to reproduce

File with name "{StrapiBlogPost.slug}.js" is existing with this query:

```
export const query = graphql`
  query BlogPostQuery($slug: String!) {
    strapiBlogPost(slug: { eq: $slug }) {
      some_fields_here
    }
  }`
```

run with yarn develop or build

### Expected result

the build should work

### Actual result

```
success source and transform nodes - 7.159s

 ERROR 

Missing onError handler for invocation 'building-schema', error was 'Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "StrapiBlog-post" does not.'. Stacktrace was 'GraphQLError: Names
must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "StrapiBlog-post" does not.
    at isValidNameError (./frontend/node_modules/graphql/utilities/assertValidName.js:42:12)
    at assertValidName (./frontend/node_modules/graphql/utilities/assertValidName.js:21:15)
    at checkIsAllowedTypeName (./frontend/node_modules/gatsby/src/schema/schema.js:608:3)
    at forEach (./frontend/node_modules/gatsby/src/schema/schema.js:313:9)
    at Array.forEach (<anonymous>)
    at addTypes (./frontend/node_modules/gatsby/src/schema/schema.js:275:9)
    at updateSchemaComposer (./frontend/node_modules/gatsby/src/schema/schema.js:162:9)
    at buildSchema (./frontend/node_modules/gatsby/src/schema/schema.js:64:9)
    at build (./frontend/node_modules/gatsby/src/schema/index.js:105:24)
    at buildSchema (./frontend/node_modules/gatsby/src/services/build-schema.ts:19:3)'
```

the error raises because of a new type which is checked in [this](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/schema.js#L313) line that its name is valid. a console.log in the previous version right before this line did show that the type for the query was not existing.

### Environment

  System:
    OS: Linux 5.4 Linux Mint 20 (Ulyana)
    CPU: (12) x64 AMD Ryzen 5 2600X Six-Core Processor
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.4/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 88.0
  npmPackages:
    gatsby: ^3.0.4 => 3.4.0
    gatsby-background-image: ^1.4.1 => 1.5.2
    gatsby-image: ^3.0.0 => 3.4.0
    gatsby-link: ^3.0.1 => 3.4.0
    gatsby-plugin-gdpr-cookies: ^1.0.14 => 1.0.14
    gatsby-plugin-image: ^1.1.2 => 1.4.0
    gatsby-plugin-manifest: ^3.0.0 => 3.4.0
    gatsby-plugin-offline: ^4.0.0 => 4.4.0
    gatsby-plugin-react-helmet: ^4.0.0 => 4.4.0
    gatsby-plugin-sentry: ^1.0.1 => 1.0.1
    gatsby-plugin-sharp: ^3.0.0 => 3.4.0
    gatsby-source-filesystem: ^3.0.0 => 3.4.0
    gatsby-source-strapi: ^1.0.0-alpha.0 => 1.0.0-alpha.1
    gatsby-source-strapi-plugin-navigation: ^1.2.7 => 1.2.7
    gatsby-transformer-sharp: ^3.0.0 => 3.4.0

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

At the moment I suspect this is an issue with Strapi and how it generates the type names but if you can reproduce this with a minimal example we can have another look

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by olwe0002** [comment]
Hi @LekoArts,

I found out that its related to the new version of the gatsby-source-strapi plugin, not to Gatsby itself. To be more exact, to [this](
https://github.com/strapi/gatsby-source-strapi/commit/eb0e67a6d6b7828b776f4bbcac3a03b9321aae75#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556) commit. I'll close this issue here, thank you.

best regards
Oliver

**Comment by LukeVibes** [comment]
Any word on fixing this issue?

**Comment by GalvinCn** [comment]
change  the  theme of wordpress seems  work

**Comment by Morlin1129** [comment]
@inverser-pro 
I solved this problem by simply changing the theme to "Twenty Twenty-One".

**Comment by RiddMa** [comment]
I'm using Chinese language for the WP site, and yes changing the theme to 2021 or more does solve this issue. I guess it's related to first installation language you set, cuz only 2022 theme shows up as "twenty twenty-two", while other year themes are Chinese titled "二〇二一""二〇二〇"
