### ISSUE TITLE
[gatsby-image] Support image loading with JavaScript disabled

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#3109]
I think that by default, images' `src`, `srcSet` and other attributes should be set to the final displayable image instead of e.g. an image with a width of 20 pixels.

If JS is enabled, change to the preview image immediately until the final image is available.

**Comment by KyleAMathews** [comment]
There's no way afaik to tell the browser to delay loading an image *unless* we don't render the img element in the HTML.

I'm not sure any image lazy loading technique works with JavaScript disabled.

**Comment by kripod** [comment]
I think that the `noscript` tag [could be used](https://stackoverflow.com/questions/30319/is-there-a-html-opposite-to-noscript) to display the entire image instead of using a preview.

**Comment by KyleAMathews** [comment]
Ahhhhhh!!!! Yes! Of course! Could you put together a PR adding this?

**Comment by kripod** [comment]
I’ll try my best to do so as soon as I’ll have some free time 😊

**Comment by aderaaij** [comment]
Would this be achieved by something like adding

```
_react2.default.createElement("noscript", {className: "noscript"},
  _react2.default.createElement("img", {
    alt: alt,
    title: title,
    src: image.src,
  })
),   
```
to the index.js of gatsby-image?

**Comment by kripod** [comment]
I have already created a pull request which solves the issue (tested on the latest version of Firefox).

**Comment by aderaaij** [comment]
👌 that's awesome, thanks! Does it also prevent the base64 or tracedsvg image from showing up?

**Comment by kripod** [comment]
@aderaaij With Firefox, the base64 / traced SVG image is shown until the original gets loaded.
