### ISSUE TITLE
Redundant CSS in output when using CSS modules & mixing direct imports with `composes`

### ISSUE THREAD

**Issue by dryan-FF** [gatsbyjs/gatsby#31105]
## Description
Our Gatsby project with CSS modules is not compiling the CSS as expected. The way the modules are resolved, importing a CSS module's class into a component after using it through composition in another, earlier CSS module file is causing Webpack to put the definition for that class twice into the outputted CSS. This is bad because the second output of the original class is overwriting the composed class

See the [README](https://github.com/dryan-FF/gatsby-css-modules-testing#readme)  in the repository linked below for a more detailed explanation., including some other findings:
- changing the alphabetical order of the files causes the issue to not appear, as webpack will properly resolve the two uses
- if you never directly import the CSS module and always compose it (even with no properties added), webpack will properly resolve. see this branch for an example https://github.com/dryan-FF/gatsby-css-modules-testing/tree/no-issues 

Also note that I'm able to successfully compile similar CSS modules without Gatsby (just webpack), see this repository for an example https://github.com/dryan-FF/webpack-modules-css-testing

 
### Steps to reproduce
see this repository here: https://github.com/dryan-FF/gatsby-css-modules-testing 

1. Create gatsby project (see repository link above)
2. create CSS module file, like https://github.com/dryan-FF/gatsby-css-modules-testing/tree/main/src/styling/button.module.css
3. directly import that module file and use into one of your components
4. for a component that is _alphabetically after_ the component in step 3, import a CSS module with a class that `composes` the file used in step 3
5. run `gatsby develop` and observe the resulting CSS on the page

### Expected result
- webpack should resolve this mixed use of CSS modules, and not put the CSS Module  twice in the `commons.css` output
- I should be able to use a CSS module both directly and through composition, without worrying about the order that webpack  finds the files

### Actual result
- see: https://github.com/dryan-FF/gatsby-css-modules-testing/tree/main/CSS_OUTPUT.css . In my CSS file, the webpack compilation placed the class `.button-module--button--9nqNa` from  the original CSS module first, then the class which composed it `.another-page-module--linkButton--2Ugz9`, then the button  class from original CSS module again, which overwrote the composed class due to CSS's  specificity rules and how CSS modules composes classes `class="another-page-module--linkButton--2Ugz9 button-module--button--9nqNa"`

### Environment

  System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.7.0 - ~/.nvm/versions/node/v14.7.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v14.7.0/bin/npm
  Languages:
    Python: 3.7.10 - /Users/davidryan/.pyenv/shims/python
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 88.0
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.4.0 => 3.4.0 

flags used: none

**Comment by vladar** [comment]
Is it the same in `develop` and `build`? Also, have you tried bisecting which part of our webpack config causes this? Maybe using https://www.gatsbyjs.com/docs/reference/config-files/actions/#replaceWebpackConfig

Also related: https://www.gatsbyjs.com/docs/how-to/custom-configuration/add-custom-webpack-config/

**Comment by dryan-FF** [comment]
hi @vladar, thanks for checking in on this. The output is different from `build`, though still causing the  same issue. you can see it here: https://github.com/dryan-FF/gatsby-css-modules-testing/blob/main/CSS_OUTPUT_PROD.css

this time, there is no duplicate `.button` styles, but its still *after* the `.linkButton` composed from `.button`  in `another-page`, which causes the same CSS specificity issues i mention above 

I was doing what I could to read through the configuration gatsby has for webpack - like most webpack configs, it's a lot to wrap my head around 😅 . i'll keep looking to see if any specific loader is the issue

**Comment by Haizzz** [comment]
I'm also experiencing the same issue where both `develop` and `build` have a CSS file duplicated twice, overwriting compositions in other places. I had a quick test and looks like this problem didn't exist in Gatsby v2.32?

The workaround I did is to remove the compositions and put the composited classes directly onto the tags
