### ISSUE TITLE
Deploying to cloudflare should be free, but documentation is wrong

### ISSUE THREAD

**Issue by ben-xD** [gatsbyjs/gatsby#31103]
According to Cloudflare docs, [Workers KV is now free](https://developers.cloudflare.com/workers/platform/pricing).

But in the [docs here](https://www.gatsbyjs.com/docs/deploying-to-cloudflare-workers/), it says we need to pay the $5 Workers unlimited plan. So the documentation is a bit outdated on this.

Also though, I tried using this guide, and it doesn't work: I only get a white empty page. Funny that the favicon still loads in the browser though.

**Comment by ben-xD** [comment]
I solved the latter issue by first running `npm run build`, which is not in the documentation :). I think this should be added to it too

**Comment by ben-xD** [comment]
I will leave it open in case someone wants to improve the documentation? :)

**Comment by orangemn6** [comment]
I can do this if it is still needed

**Comment by ben-xD** [comment]
I think I should add something about the `npm run build` step though, since that was quite important to avoid a white screen after deploying. Will do it asap and create a PR

**Comment by KyleAMathews** [comment]
Thanks @ben-xD !

**Comment by orangemn6** [comment]
@ben-xD I can add it to mine if that works too

**Comment by ben-xD** [comment]
> @ben-xD I can add it to mine if that works too

Sorry @orangemn6, I just realised its better that I wrote it because I directly faced the issues I mentioned and can help people avoid the same issues as me.
