### ISSUE TITLE
gatsby-plugin-netlify-cms breaks build due to mini-css-extract-plugin already being registered

### ISSUE THREAD

**Issue by gijsbotje** [gatsbyjs/gatsby#31102]
## Description

I'm trying to setup my site with netlify-cms with gatsby v3. Did it for a different site but when I rebuild my yarn lock on that site I now get the same error. While building the bundles it crashes with the error:
```
ObjectMiddleware.register: serializer for
mini-css-extract-plugin/dist/CssModule/null is already registered

  Error: ObjectMiddleware.register: serializer for mini-css-extract-plugin/dist/Css
  Module/null is already registered
  
  - ObjectMiddleware.js:182 Object.register
    [liquefy-gatsby-site]/[webpack]/lib/serialization/ObjectMiddleware.js:182:10
  
  - index.js:163 Function.getCssModule
    [liquefy-gatsby-site]/[mini-css-extract-plugin]/dist/index.js:163:34
  
  - index.js:358 MiniCssExtractPlugin.apply
    [liquefy-gatsby-site]/[mini-css-extract-plugin]/dist/index.js:358:44
  
  - webpack.js:74 createCompiler
    [liquefy-gatsby-site]/[webpack]/lib/webpack.js:74:12
  
  - webpack.js:123 create
    [liquefy-gatsby-site]/[webpack]/lib/webpack.js:123:16
  
  - webpack.js:147 webpack
    [liquefy-gatsby-site]/[webpack]/lib/webpack.js:147:32
  
  - index.js:54 f
    [liquefy-gatsby-site]/[webpack]/lib/index.js:54:15
  
  - start-server.ts:164 startServer
    [liquefy-gatsby-site]/[gatsby]/src/utils/start-server.ts:164:20
  
  - start-webpack-server.ts:44 startWebpackServer
    [liquefy-gatsby-site]/[gatsby]/src/services/start-webpack-server.ts:44:7
  

not finished Building development bundle - 6.380s
```

I've tried downgrading all my packages to the same for the site it does work for, but it just won't work. Reinstalled packages and rebuilding yarn.lock multiple times with no success.

### Steps to reproduce
This repo is setup to recreate the error: https://github.com/gijsbotje/gijsbotje-gatsby-bug-repro
- clone the repo
- run `yarn develop`
to see that it works without netlify cms, comment out the netlify cms app at the bottom of the gatsby-config and run it again. Now the develop build works.

### Expected result
I expect the build to succeeds and have the CMS available at `localhost://8000/admin`.

### Actual result
The above mentioned error keeps coming up.

### Environment
```
  System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.19.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.85
    Firefox: 85.0
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.2.0 => 3.4.0 
    gatsby-background-image: ^1.4.1 => 1.5.3 
    gatsby-plugin-catch-links: 3.2.0 => 3.2.0 
    gatsby-plugin-fontawesome-css: ^1.0.0 => 1.1.0 
    gatsby-plugin-gdpr-cookies: ^1.0.7 => 1.0.14 
    gatsby-plugin-image: ^1.2.0 => 1.4.0 
    gatsby-plugin-manifest: 3.2.0 => 3.2.0 
    gatsby-plugin-netlify: 3.2.0 => 3.2.0 
    gatsby-plugin-netlify-cms: ^5.3.0 => 5.4.0 
    gatsby-plugin-offline: ^4.2.0 => 4.4.0 
    gatsby-plugin-react-helmet: ^4.2.0 => 4.4.0 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.1 
    gatsby-plugin-sass: ^4.2.0 => 4.4.0 
    gatsby-plugin-sharp: ^3.2.0 => 3.4.0 
    gatsby-plugin-sitemap: 3.2.0 => 3.2.0 
    gatsby-plugin-stylelint: ^3.2.0 => 3.2.0 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-remark-classes: ^1.0.0 => 1.0.0 
    gatsby-remark-copy-linked-files: ^3.2.0 => 3.2.0 
    gatsby-remark-images: ^4.2.0 => 4.2.0 
    gatsby-remark-prismjs: ^4.2.0 => 4.2.0 
    gatsby-remark-relative-images: ^2.0.2 => 2.0.2 
    gatsby-remark-responsive-iframe: ^3.2.0 => 3.2.0 
    gatsby-source-filesystem: ^3.2.0 => 3.4.0 
    gatsby-transformer-remark: ^3.2.0 => 3.2.0 
    gatsby-transformer-sharp: ^3.2.0 => 3.4.0 
  npmGlobalPackages:
    gatsby-cli: 3.0.0

```

**Comment by tatsu** [comment]
It seems to be due to gatsby-plugin-netlify-cms 5.4.0 starting to use mini-css-extract-plugin 1.5.0 and starting to mix the two versions. For the time being, downgrading to gatsby-plugin-netlify-cms 5.3.0 (`"^5.3.0"` to `"5.3.0"`) will work.

**Comment by gijsbotje** [comment]
@tatsu thanks, it's running again!

**Comment by gijsbotje** [comment]
Cool, @LekoArts got the fix for it 👍🏻

**Comment by hoangbn** [comment]
I'm still running into this issue when trying to create minimal reproduction for #31179. Downgrading to `5.3.0` did not work.
Repo: https://github.com/hoangbn/wepack-bug-repro

**Comment by gijsbotje** [comment]
@hoangbn did you delete your node_modules and lock file before installing  packages again?

**Comment by hoangbn** [comment]
I forgot to downgrade "^5.3.0" to "5.3.0". Works now

**Comment by aibinary** [comment]
> It seems to be due to gatsby-plugin-netlify-cms 5.4.0 starting to use mini-css-extract-plugin 1.5.0 and starting to mix the two versions. For the time being, downgrading to gatsby-plugin-netlify-cms 5.3.0 (`"^5.3.0"` to `"5.3.0"`) will work.

I have the same issue with Netlify cms. I used the version you quoted here, when i add "gatsby-plugin-netlify-cms" am having the build failure with below error.
ObjectMiddleware.register: serializer for mini-css-extract-plugin/dist/CssModule/null is already registered



  Error: ObjectMiddleware.register: serializer for mini-css-extract-plugin/dist/CssModule/null is already registered
  
  - ObjectMiddleware.js:182 Object.register
    [gatsby-starter-blog]/[webpack]/lib/serialization/ObjectMiddleware.js:182:10
  
  - index.js:163 Function.getCssModule
    [gatsby-starter-blog]/[mini-css-extract-plugin]/dist/index.js:163:34
  
  - index.js:371 MiniCssExtractPlugin.apply
    [gatsby-starter-blog]/[mini-css-extract-plugin]/dist/index.js:371:44
  
  - webpack.js:74 createCompiler
    [gatsby-starter-blog]/[webpack]/lib/webpack.js:74:12
  
  - webpack.js:123 create
    [gatsby-starter-blog]/[webpack]/lib/webpack.js:123:16
  
  - webpack.js:147 webpack
    [gatsby-starter-blog]/[webpack]/lib/webpack.js:147:32
  
  - index.js:54 f
    [gatsby-starter-blog]/[webpack]/lib/index.js:54:15
  
  - start-server.ts:165 startServer
    [gatsby-starter-blog]/[gatsby]/src/utils/start-server.ts:165:20
  
  - task_queues.js:62 runNextTicks
    internal/process/task_queues.js:62:5
  
  - timers.js:434 processImmediate
    internal/timers.js:434:9
  
  - start-webpack-server.ts:44 startWebpackServer
    [gatsby-starter-blog]/[gatsby]/src/services/start-webpack-server.ts:44:7
  

not finished Building development bundle - 4.277s

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-blog@0.1.0 develop: `gatsby develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gatsby-starter-blog@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hari/.npm/_logs/2021-05-18T04_52_30_024Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-blog@0.1.0 start: `npm run develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gatsby-starter-blog@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by sj-rai** [comment]
@gijsbotje Is this fixed?. I still get the same issue. I tried with version, 5.5.0 and also tried downgrading to 5.3.0, but no luck.

**Comment by gijsbotje** [comment]
@sj-rai i havent upgraded yet, the downgrade fixed it for me but didnt check if there is a new version with a fix

**Comment by sj-rai** [comment]
@gijsbotje I had to downgrade `gatsby` to 3.2.0, along with downgrading `gatsby-plugin-netlify-cms` and it worked. Looks like version of `mini-css-extract-plugin` in these two packages have to be the same at all times, or else the plugin will give this error.

**Comment by jnicewander** [comment]
@gijsbotje @sj-rai `gatsby@3.6.0` and `gatsby-plugin-netlify-cms@5.6.0` are both updated to use `mini-css-extract-plugin@1.6.0`. Looks like both versions were released ~6 hours ago.

**Comment by gijsbotje** [comment]
@jnicewander Awesome! Thanks for the update.

**Comment by glenn-mccomb** [comment]
Have just updated to `gatsby-plugin-netlify-cms@5.6.0` and am no longer experiencing this issue.

**Comment by aibinary** [comment]
am still getting the same error. i literally downloaded the new blog starter, did everything from the start.
Updated Gatsby to latest version and gatsby-plugin-netlify-cms-^5.6.0

ObjectMiddleware.register: serializer for mini-css-extract-plugin/dist/CssModule/null is already registered



  Error: ObjectMiddleware.register: serializer for mini-css-extract-plugin/dist/CssModule/null is already registered
  
  - ObjectMiddleware.js:182 Object.register
    [my-gatsby-project]/[webpack]/lib/serialization/ObjectMiddleware.js:182:10
  
  - index.js:163 Function.getCssModule
    [my-gatsby-project]/[mini-css-extract-plugin]/dist/index.js:163:34
  
  - index.js:371 MiniCssExtractPlugin.apply
    [my-gatsby-project]/[mini-css-extract-plugin]/dist/index.js:371:44
  
  - webpack.js:74 createCompiler
    [my-gatsby-project]/[webpack]/lib/webpack.js:74:12
  
  - webpack.js:123 create
    [my-gatsby-project]/[webpack]/lib/webpack.js:123:16
  
  - webpack.js:147 webpack
    [my-gatsby-project]/[webpack]/lib/webpack.js:147:32
  
  - index.js:54 f
    [my-gatsby-project]/[webpack]/lib/index.js:54:15
  
  - start-server.ts:165 startServer
    [my-gatsby-project]/[gatsby]/src/utils/start-server.ts:165:20
  
  - task_queues.js:62 runNextTicks
    internal/process/task_queues.js:62:5
  
  - timers.js:434 processImmediate
    internal/timers.js:434:9
  
  - start-webpack-server.ts:44 startWebpackServer
    [my-gatsby-project]/[gatsby]/src/services/start-webpack-server.ts:44:7
  

not finished Building development bundle - 4.190s

**Comment by sj-rai** [comment]
@aibinary ``` "gatsby": "^3.2.0",
    "gatsby-plugin-netlify-cms": "5.3.0",```. This worked for me.

**Comment by Rashmi-278** [comment]
`npm ls mini-css-extract-plugin why mini-css-extract-plugin`

@stackrole/gatsby-starter-foundation@2.0.0 /home/torch/Desktop/Building/gatsby-starter-foundation-main
├─┬ gatsby@3.2.0
│ └── mini-css-extract-plugin@1.3.9 
└─┬ gatsby-plugin-netlify-cms@5.6.0
  └── mini-css-extract-plugin@1.6.0 


This works for me.

**Comment by TahseenAlaa** [comment]
Update the package using this command ```npm install gatsby-plugin-netlify-cms@latest```

**Comment by ThuwarakeshM** [comment]
Thanks @TahseenAlaa , it worked for me once I upgraded to `gatsby-plugin-netlify-cms@latest`

**Comment by mykeels** [comment]
To fix this, I removed `mini-css-extract-plugin` from package.json, and ran:

```sh
npm i
npm i gatsby-plugin-netlify-cms
```

This made sure the version of `mini-css-extract-plugin` that `gatsby-plugin-netlify-cms` plays well with was installed, and it worked.

**Comment by Megajin** [comment]
For anyone flying by:

I have testet this issue with a fresh start of a Gatsby site (minimal starter).
However since `gatsby-plugin-netlify-cms` is already at version 6, I was wondering if the error would still occur.
Yes it did indeed. However there is one catch: I did use `pnpm`. So I went ahead deleted node_modules and the *.lock file of pnpm and reinstalled everything with `yarn`.

With yarn it worked fine. So if you can switch your Packagemanager go ahead, it will work.
But for me there was a huge `nx` monorepo managed with pnpm. So we had to create a new repository just for the Gatsby site, which is a shame. But it fixed it 🚀.

**Comment by ricovitch** [comment]
Having same issue with the current latest stable releases of gatsby and gatsby-plugin-netlify-cms using yarn pnp.
I did not find any workaround yet. I tried using resolutions to find a working version of gatsby-plugin-netlify-cms without success.

Now investigating if I can hack the webpack config to resolve this.

**Comment by felschr** [comment]
@ricovitch did you resolve your issue? I'm running into the same issue after updating all gatsby dependencies to their latest versions:
`gatsby@4.20.0`, `gatsby-plugin-netlify-cms@6.23.0`

**Comment by ricovitch** [comment]
@felschr not really sorry.
For now I abandonned yarn pnp setup as it is working with "nodeLinker: node-modules".
