### ISSUE TITLE
Cache uses absolute directories and build crashes if project is moved

### ISSUE THREAD

**Issue by tmadeira** [gatsbyjs/gatsby#31128]
## Description

Build crashes if a project is moved from one directory to another, because .cache uses absolute directories.

I believe this is new; was not happening a few days ago.

### Steps to reproduce

Just build any project, move it to another directory, and try building again. The simplest way to reproduce it is by creating a new Gatsby site from the default starter to do so:

```
~ $ npx -p gatsby gatsby new directory
~ $ cd directory
~/directory $ npm run build
~/directory $ cd ..
~ $ mv directory new-directory
~ $ cd new-directory
~/new-directory $ npm run build
```

### Expected result

Build should work.

### Actual result

Build crashes:

```
failed Building static HTML for pages - 0.088s

 ERROR #95313 

Building static HTML failed for path "/404/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


  75 |     return context[query].data
  76 |   } else {
> 77 |     throw new Error(
     |           ^
  78 |       `The result of this StaticQuery could not be fetched.\n\n` +
  79 |         `This is likely a bug in Gatsby and if refreshing the page does not fix it, ` +
  80 |         `please open an issue in https://github.com/gatsbyjs/gatsby/issues`


  WebpackError: The result of this StaticQuery could not be fetched.
  
  - gatsby-browser-entry.js:77 
    gatsby-starter-default/.cache/gatsby-browser-entry.js:77:11
  
  - layout.js:16 
    gatsby-starter-default/src/components/layout.js:16:30
  
  - extends.js:3 
    [gatsby-starter-default]/[@babel]/runtime/helpers/extends.js:3:42
  
  - extends.js:2 
    [gatsby-starter-default]/[@babel]/runtime/helpers/extends.js:2:1
  
  - extends.js:13 
    [gatsby-starter-default]/[@babel]/runtime/helpers/extends.js:13:1
  
  - static-entry.js:263 
    gatsby-starter-default/.cache/static-entry.js:263:20
  


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-default@0.1.0 build: `gatsby build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gatsby-starter-default@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Environment

```
  System:
    OS: Linux 5.11 Arch Linux
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.volta/tools/image/node/14.16.1/bin/node
    Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
    npm: 6.14.12 - ~/.volta/tools/image/node/14.16.1/bin/npm
  Languages:
    Python: 3.9.4 - /usr/bin/python
```

**Comment by vladar** [comment]
Hey, interesting. I don't see the version of gatsby you use? Can you maybe bisect it to figure out which version introduced this behavior?

**Comment by avi312singh** [comment]
I have got this too! Any idea on this? Seems to be failing at the build stage

**DarkThemeContext.js**
`import React, { useState, useContext } from "react"

const DarkThemeContext = React.createContext({
  darkMode: false,
  setDarkMode: () => {},
})

export const DarkThemeProvider = ({ children }) => {
  const [isDark, setIsDark] = useState(false)

  return (
    <DarkThemeContext.Provider
      value={{
        darkMode: isDark,
        setDarkMode: setIsDark,
      }}
    >
      {children}
    </DarkThemeContext.Provider>
  )
}

const useDarkThemeContext = () => useContext(DarkThemeContext);

export default useDarkThemeContext;
`
**gatsby-browser.js**

`import React from "react"

import { DarkThemeProvider } from './src/pages/components/DarkThemeContext/DarkThemeContext'

export const wrapRootElement = ({ element }) => {
  return <DarkThemeProvider>{element}</DarkThemeProvider>
}
`

**failed Building static HTML for pages - 1.173s
 ERROR #95313 
Building static HTML failed for path "/components/DarkThemeContext/DarkThemeContext/"**

```
  - static-entry.js:263 
    gatsby-starter-hello-world/.cache/static-entry.js:263:20
```

**Comment by avi312singh** [comment]
```
╰$ gatsby -v
Gatsby CLI version: 3.0.0
Gatsby version: 3.7.2
```
