### ISSUE TITLE
[gatsby-plugin-image] Unmounting error on dynamic `image` prop value update

### ISSUE THREAD

**Issue by patibugaj** [gatsbyjs/gatsby#31131]
## Description

I receive an error `Warning: render(...): It looks like the React-rendered content of this container was removed without using React. This is not supported and will cause errors. Instead, call ReactDOM.unmountComponentAtNode to empty a container.`. on the dynamic change of the image prop value in the `<GatsbyImage />`.

### Steps to reproduce

I am using a carousel with the thumbnail images as the pagination. We are using `<GatsbyImage />` to display the image of the active slide and thumbnails. During changing the slides the main image of the active slide (`<ActiveSlide />`) has thrown an error `Warning: render(...): It looks like the React-rendered content of this container was removed without using React. This is not supported and will cause errors. Instead, call ReactDOM.unmountComponentAtNode to empty a container.`.

Example code:

```
import React, { useState, useEffect, useRef } from 'react'
import { GatsbyImage } from 'gatsby-plugin-image'
import { Splide, SplideSlide } from '@splidejs/react-splide'
import '@splidejs/splide/dist/css/themes/splide-default.min.css'

export default function ({ testimonials }) {
  const [splide, setSplide] = useState(null)
  const [activeIndex, setActiveIndex] = useState(0)
  const activeTestimonial = testimonials[activeIndex]
  
  const splideRef = useRef(null)

  useEffect(() => {
    if (!splideRef?.current) return
    setSplide(splideRef.current.splide)
  }, [splide])

  return (
    <>
      <ActiveSlide>
        <GatsbyImg image={activeTestimonial.videoPoster.gatsbyImageData} alt={activetestimonial.videoPoster.title} />
      </ActiveSlide>
      <Splide ref={splideRef}>
        {testimonials.map(
          ({ id, videoPoster }, index) =>
            videoPoster?.gatsbyImageData && (
              <SplideSlide key={id}>
                <Slide
		  isActive={activeIndex === index}
		  onClick={() => setActiveIndex(index)}
                >
                  <div>
                    <GatsbyImage image={videoPoster.gatsbyImageData} />
                  </div>
                </Slide>
              </SplideSlide>
            ),
        )}
      </Splide>
    </>
  )
}
```

### Expected result

I checked if the issue is related to our components. I logged the unmount status, but this was not the case.
What I noticed was that the issue of the not unmounted component was directly inside `GatsbyImage`. I fixed this issue by adding the `key` prop to the `<GatsbyImage />` in `<ActiveSlide />`. So the React knows that GatsbyImage with updated `image` prop value from the state, is a different element.

```
  ...
  <ActiveSlide>
    <GatsbyImg
      key={activeTestimonial.id}
      image={activeTestimonial.videoPoster.gatsbyImageData}
      alt={activetestimonial.videoPoster.title}
    />
  </ActiveSlide>
  ...
```

### Actual result

In the documentation, I couldn't find any info about this case scenario. Maybe it would be nice to add it?

### Environment

System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - /c/Users/patry/.windows-build-tools/python27/python
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (90.0.818.49)
  npmPackages:
    gatsby: ^2.32.3 => 2.32.4
    gatsby-cypress: ^1.0.0 => 1.0.0
    gatsby-plugin-emotion: ^4.5.0 => 4.5.0
    gatsby-plugin-eslint: ^3.0.0 => 3.0.0
    gatsby-plugin-image: ^0.7.1 => 0.7.2
    gatsby-plugin-loadable-components-ssr: ^2.1.0 => 2.1.0
    gatsby-plugin-manifest: ^2.12.0 => 2.12.0
    gatsby-plugin-netlify: ^2.11.0 => 2.11.0
    gatsby-plugin-react-helmet: ^3.10.0 => 3.10.0
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5
    gatsby-plugin-sharp: ^2.14.1 => 2.14.1
    gatsby-plugin-sitemap: ^2.12.0 => 2.12.0
    gatsby-plugin-svgr: ^2.1.0 => 2.1.0
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.20 => 1.1.20
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.5 => 1.0.5
    gatsby-source-contentful: ^4.6.1 => 4.6.3
    gatsby-source-filesystem: ^2.11.0 => 2.11.0
    gatsby-transformer-remark: ^2.16.0 => 2.16.0
    gatsby-transformer-sharp: ^2.12.0 => 2.12.0
  npmGlobalPackages:
    gatsby-cli: 3.4.0

**Comment by LekoArts** [comment]
You're using a very outdated version of `gatsby-plugin-image`. Please update to the latest version (that is 1.x) and the problem will probably be fixed. See https://github.com/gatsbyjs/gatsby/issues/30176 & https://github.com/gatsbyjs/gatsby/issues/29982
