### ISSUE TITLE
What's the current state of support for URL rewriting?

### ISSUE THREAD

**Issue by daniel-vu** [gatsbyjs/gatsby#3113]
We're trying to serve some Gatsby pages by using Nginx to rewrite the page URLs, but it seems that Gatsby depends on the page URL to reference a direct path on disk--I get the following console errors when I then try to access these sites (we're rewriting URLs such as `/hotels-ng?district=1234` to page directory paths such as `public/district_1234`):

```
A page wasn't found for "/hotels-ng"
loader.js:259:8
A page wasn't found for "/404.html"
```

I saw that a similar question about path rewriting was raised in #383 but that issue is over a year old and the advice there seems to be outdated, so I figured that I'd raise it again. Like, is [this](https://github.com/KyleAMathews/blog/blob/master/gatsby-node.js#L79) the new example that I should be following? Looking for any guidance really. Thanks!

**Comment by daniel-vu** [comment]
Actually, if I'm understanding https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#removing-trailing-slashes properly, it seems like I should also be able to use onCreatePage to modify a page path like 'district_1234' to look like 'hotels-ng?district', no?

**Comment by KyleAMathews** [comment]
When you're working with a static site generator — you need to create paths which correspond to file directories.

Why not just make urls like `/hotels-ng/district/1234/`?

**Comment by daniel-vu** [comment]
We could. I can see how this could call for pushing back on the URL structure. Thanks for the quick reply.
