### ISSUE TITLE
gatsbyjs/docs broken link

### ISSUE THREAD

**Issue by wodin** [gatsbyjs/gatsby#3114]
On the following page in the docs:
https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules
The `customize` link takes you here:
https://www.gatsbyjs.org/add-custom-webpack-config

Strangely if I hover over the link it looks right (i.e. it includes /docs/) but if I click on it it doesn't work.

**Comment by KyleAMathews** [comment]
Huh yeah — fixed now — it's something we should also add support for to https://www.gatsbyjs.org/packages/gatsby-plugin-catch-links/
