### ISSUE TITLE
gatsby-plugin-sitemap: incorrect sitemap path in index sitemap

### ISSUE THREAD

**Issue by moonmeister** [gatsbyjs/gatsby#31167]
## Description

The site map index doesn't include the sub-folder that the sitemap files are placed in. 

The current work around would be to set the `output` config to `/`. 
#31130 

This issue has been reported upstream at https://github.com/ekalinin/sitemap.js/issues/359

### Steps to reproduce

see the up stream issue for more info. This is being opened to track that issue on the gatsby side so our dependencies can be updated when that issue is fixed. 

### Environment

gatsby-plugin-sitemap: ^4.0

**Comment by moonmeister** [comment]
I'm working on a fix for this

**Comment by alexgladd** [comment]
Note that until PR #31130 is deployed, a better workaround is setting the `output` config to `/./`. Otherwise, the sitemap href in the link tag doesn't work.
