### ISSUE TITLE
gatsby-plugin-netlify-cms Webpack Error (Gatsby v3)

### ISSUE THREAD

**Issue by hoangbn** [gatsbyjs/gatsby#31179]
## Description

When upgrading to v3, gatsby-plugin-netlify-cms throws a Webpack error:
```
"gatsby-plugin-netlify-cms" threw an error while running the onCreateWebpackConfig lifecycle:

Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.node should be one of these:
   false | object { __dirname?, __filename?, global? }
   -> Include polyfills or mocks for various node stuff.
   Details:
    * configuration.node has an unknown property 'fs'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'child_process'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'module'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.

```

### Steps to reproduce

I followed the migration guide from v2 to v3. I have already updated Webpack node configuration: 

```
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    resolve: {
      alias: {
        path: require.resolve("path-browserify")
      },
      fallback: {
        fs: false
      }
    }
  });
};
```
### Expected result

Develop runs without error.

### Actual result

Webpack error

### Environment
```
  flags: {
    DEV_SSR: true,
    PRESERVE_WEBPACK_CACHE: true,
    FAST_REFRESH: true,
    PRESERVE_FILE_DOWNLOAD_CACHE: true
  },
```
  System:
    OS: macOS 11.2.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Languages:
    Python: 3.7.5 - /Users/macbookpro/.pyenv/shims/python
  Browsers:
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.4.0 => 3.4.0 
    gatsby-plugin-create-client-paths: ^3.4.0 => 3.4.0 
    gatsby-plugin-image: ^1.4.0 => 1.4.0 
    gatsby-plugin-manifest: ^3.4.0 => 3.4.0 
    gatsby-plugin-mdx: ^2.4.0 => 2.4.0 
    gatsby-plugin-netlify: ^3.4.0 => 3.4.0 
    gatsby-plugin-netlify-cms: ^5.4.0 => 5.4.0 
    gatsby-plugin-react-helmet: ^4.4.0 => 4.4.0 
    gatsby-plugin-sharp: ^3.4.0 => 3.4.0 
    gatsby-plugin-sitemap: ^4.0.0 => 4.0.0 
    gatsby-plugin-svgr: ^3.0.0-beta.0 => 3.0.0-beta.0 
    gatsby-plugin-typescript: ^3.4.0 => 3.4.0 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.22 => 1.1.22 
    gatsby-remark-relative-images: ^1.1.1 => 1.1.1 
    gatsby-source-filesystem: ^3.4.0 => 3.4.0 
    gatsby-telemetry: ^2.4.0 => 2.4.0 
    gatsby-theme-material-ui: ^2.0.1 => 2.0.1 
    gatsby-theme-material-ui-top-layout: ^2.0.1 => 2.0.1 
    gatsby-transformer-remark: ^4.1.0 => 4.1.0 
    gatsby-transformer-sharp: ^3.4.0 => 3.4.0

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by hoangbn** [comment]
Resolved it - had additional custom webpack config for `gatsby-plugin-netlify-cms` that I had to update

**Comment by wyqydsyq** [comment]
> Resolved it - had additional custom webpack config for `gatsby-plugin-netlify-cms` that I had to update

@hoangbn What did you update it to? I have been trying to use the same plugin but my webpack config overrides seems to get ignored: https://github.com/gatsbyjs/gatsby/issues/31475

**Comment by hoangbn** [comment]
@wyqydsyq netlify-cms does not use webpack settings from gatsby-node.
These are my config options:

```
{
      resolve: "gatsby-plugin-netlify-cms",
      options: {
        manualInit: true,
        modulePath: `${__dirname}/src/cms/cms.ts`,
        publicPath: "cms",
        htmlFavicon: "src/assets/logoCircle.png",
        customizeWebpackConfig: (config, { stage, plugins }) => {
          config.resolve = {
            ...config.resolve,
            alias: {
              ...config.resolve.alias,
              path: require.resolve("path-browserify")
            },
            fallback: {
              ...config.resolve.fallback,
              fs: false,
              child_process: false,
              module: false
            }
          };
          if (stage === "build-javascript" || stage === "develop") {
            config.plugins.push(plugins.provide({ process: "process/browser" }));
          }
          config.plugins.push(plugins.provide({ Buffer: ["buffer", "Buffer"] }));
        }
      }
    },
```
