### ISSUE TITLE
Build static HTML - WebpackError: render-page.js,  get error on require('fs').constants

### ISSUE THREAD

**Issue by master12** [gatsbyjs/gatsby#31199]
## Description

When running the build process, I get a webpack error during the Build static HTML. 

``
failed Building static HTML for pages - 3.848s

 ERROR #95313 

Building static HTML failed

See our docs page for more info on this error: https://gatsby.dev/debug-html

> 1 | module.exports = require('fs').constants || require('constants')
    |                  ^
  2 |

  WebpackError: TypeError: 'get' on proxy: property 'constants' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '[object Object]' 
  but got '[object Object]')
``

I have updated my gatsby-node to include the webpack config:

``
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    resolve: {
      fallback: {
        fs: false,
      }
    }
  })
}
``

### Steps to reproduce

Basically upgraded libraries to gatsby 3.4.0 and run build. Run develop is fine its just on the build process, specifically the render-page.js file tries to export
``
module.exports = require('fs').constants || require('constants')
``

That is the line that throws the error.

Link to open source repo:
https://github.com/ONRR/nrrd

### Expected result

It should build.

### Actual result

Webpack error

### Environment

  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    npm: 6.14.11 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    gatsby: ^3.4.0 => 3.4.0 
    gatsby-cli: ^3.4.0 => 3.4.0 
    gatsby-image: ^2.4.3 => 2.11.0 
    gatsby-legacy-polyfills: 1.2.0 => 1.2.0 
    gatsby-plugin-anchor-links: ^1.1.1 => 1.2.1 
    gatsby-plugin-google-tagmanager: ^3.4.0 => 3.4.0 
    gatsby-plugin-image: 1.4.0 => 1.4.0 
    gatsby-plugin-layout: ^1.3.1 => 1.10.0 
    gatsby-plugin-manifest: ^3.4.0 => 3.4.0 
    gatsby-plugin-material-ui: ^2.1.8 => 2.1.10 
    gatsby-plugin-mdx: ^1.2.6 => 1.10.1 
    gatsby-plugin-meta-redirect: ^1.1.1 => 1.1.1 
    gatsby-plugin-offline: ^4.4.0 => 4.4.0 
    gatsby-plugin-react-helmet: ^4.4.0 => 4.4.0 
    gatsby-plugin-remove-console: 0.0.2 => 0.0.2 
    gatsby-plugin-sharp: ^3.4.0 => 3.4.0 
    gatsby-plugin-use-query-params: ^1.0.1 => 1.0.1 
    gatsby-remark-autolink-headers: ^2.3.1 => 2.11.0 
    gatsby-source-filesystem: ^3.4.0 => 3.4.0 
    gatsby-source-graphql: ^3.4.0 => 3.4.0 
    gatsby-transformer-react-docgen: ^6.4.0 => 6.4.0 
    gatsby-transformer-sharp: ^3.4.0 => 3.4.0 
    gatsby-transformer-yaml: ^2.4.1 => 2.11.0 
  npmGlobalPackages:
    gatsby-cli: 3.4.0

**Comment by master12** [comment]
@vladar 2.24.85, I also traced it to a specific library 'exceljs'. For some reason this causes the error. When I remove the reference to it in our code it builds fine.

The branch I am using is https://github.com/ONRR/nrrd/tree/1426-update-js-libs

The current commit has the library commented out. It is located in ./src/js/utlis/index.js line 5

So this current branch does build but when you add that library you see the error.

**Comment by pieh** [comment]
Open PR with fix in https://github.com/gatsbyjs/gatsby/pull/31346
