### ISSUE TITLE
gatsby-plugin-sass failing on gatsby-cloud

### ISSUE THREAD

**Issue by llamerr** [gatsbyjs/gatsby#31209]
## Description

Everything works fine locally when in develop or in build mode (latest osx). I fixed it once by removing node_modules/package-lock and removing some packages from package.json and installing them again (their versions updated, at least for some of them). Now it broken again, and repeating those steps didn't help. I don't have access to cloud and will provide exact error later when I have it

### Steps to reproduce

When deployed on gatsby cloud, fails with this error:

![image](https://user-images.githubusercontent.com/1281970/116737959-839db100-a9fa-11eb-8811-80ca102576ac.png)

### Environment
Local that works:
```
 System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 88.0
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.3.1 => 3.4.0
    gatsby-plugin-gatsby-cloud: ^2.2.0 => 2.4.1
    gatsby-plugin-image: ^1.4.0 => 1.4.0
    gatsby-plugin-manifest: ^3.2.0 => 3.4.0
    gatsby-plugin-offline: ^4.2.0 => 4.4.0
    gatsby-plugin-react-helmet: ^4.2.0 => 4.4.0
    gatsby-plugin-sass: ^4.4.0 => 4.4.0
    gatsby-plugin-sharp: ^3.4.0 => 3.4.0
    gatsby-source-filesystem: ^3.4.0 => 3.4.0
    gatsby-transformer-sharp: ^3.4.0 => 3.4.0
  npmGlobalPackages:
    gatsby-cli: 3.2.0
```

no idea about gatsby-cloud environmentt

**Comment by LekoArts** [comment]
Hi, thanks for the issue!
For Cloud support please head here, this issue tracker is solely for the open source project: https://www.gatsbyjs.com/support/

Thanks!

**Comment by llamerr** [comment]
I ended up removing `gatsby-plugin-gatsby-cloud` (which came with no configuration from starter) and everything started working
