### ISSUE TITLE
Can't use `graphql` in `onCreateNode`

### ISSUE THREAD

**Issue by MrToph** [gatsbyjs/gatsby#3121]
Hi,
I'm trying to make a graphql query in `onCreateNode` in `gatsby-node.js`, but `graphql` is undefined.
It seems like it's not passed to this function.

```javascript
exports.onCreateNode = ({
  graphql,
  node,
  boundActionCreators,
  getNode,
}) => {
  console.log(graphql)
}
```

It works on `exports.createPages`, so I expected it to also work here. (The [documentation](https://www.gatsbyjs.org/docs/node-apis/#onCreateNode) also doesn't give much info on what arguments are available for the `gatsby-node` functions.)

Is there a reason why I cannot use `graphql` in this function?

**Comment by pieh** [comment]
It's because it this stage of build process graphql schema is not yet created. Use `getNodes` to get all created nodes and filter/process it in js

**Comment by MrToph** [comment]
Alright will do it this way then, thanks.
