### ISSUE TITLE
useScrollRestoration only restores scroll in a sidebar nav when the link has already been visited

### ISSUE THREAD

**Issue by wileybaba** [gatsbyjs/gatsby#31253]
## Description

`useScrollRestoration` only works for a side nav div with overflow y when the nav `<Link />`s have already been visited.  When clicking these links for the first time, the page rerenders and the nav div (with useScrollRestoration) renders with its scroll all the way up.  This likely has to do with the way the pages are created from markdown files but I am unsure

### Steps to reproduce

https://github.com/wileybaba/rocket-docs-test/tree/master

`yarn install`
`gatsby develop`

scroll the left nav all the way down to the bottom and click one of the links down there and you'll see the scroll pop back to the top when the page rerenders.

### Expected result

The div with overflow should have its scroll position stored regardless if the `<Link />` component children have been visited.

### Actual result

The div with overflow and the `useScrollRestoration` hook does not restore its scroll when clicking a child `<Link />` that has not yet been visited.

### Environment
```
  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM)
i7-1068NG7 CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.11.0 -
/usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.10.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 87.0
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.0.4 => 3.4.1
    gatsby-plugin-canonical-urls:
^3.0.0 => 3.4.0
    gatsby-plugin-google-analytics:
^3.0.0 => 3.4.0
    gatsby-plugin-manifest: ^3.0.0 =>
3.4.0
    gatsby-plugin-offline: ^4.0.0 =>
4.4.0

gatsby-plugin-remove-trailing-slashes:
 ^3.0.0 => 3.4.0
    gatsby-plugin-sitemap: ^3.0.0 =>
3.3.0
  npmGlobalPackages:
    gatsby-cli: 3.4.0

```

**Comment by wileybaba** [comment]
decided to write a similar hook that leverages localStorage:

```
const useScrollRestoration = () => {
    const ref = useRef(null);
    const [scrollPos, setScrollPos] = useState(() => window.localStorage.getItem('nav-scroll-pos') ?? 0)

    const handleScroll = () => {
      if (ref.current) {
        setScrollPos(ref.current.scrollTop);
        console.log(scrollPos)
      }
    };

    // add event listener to window when component mounts
    useEffect(() => {
      ref.current.addEventListener("scroll", handleScroll);
    }, [])

    useLayoutEffect(
      () => {
        // restore scroll whenever component remounts
        ref.current.scrollTo(0, scrollPos);
        // set scroll position in local storage for setting on unmount
        return () => {
          window.localStorage.setItem('nav-scroll-pos', ref.current.scrollTop)
        }
      },
      [scrollPos]
    );

    return { ref }
  };
```

**Comment by vladar** [comment]
Can you try the same but with `gatsby build` and `gatsby serve` (vs `gatsby develop`)?

**Comment by wileybaba** [comment]
Same outcome with `gatsby build && gatsby serve`
