### ISSUE TITLE
[enhancement] Split plugins, examples from main repo.

### ISSUE THREAD

**Issue by HaoZeke** [gatsbyjs/gatsby#3125]
It's rather inconvenient to have to clone the entire repo for these segments which should probably be separate repos...

Is this by design?

**Comment by fk** [comment]
Yep, Gatsby is a [monorepo managed using Lerna](https://github.com/gatsbyjs/gatsby#packages).

I do not have a lot of personal experience with monorepos and/or frequently publishing (_many_) NPM packages, but I think [this article](https://github.com/babel/babel/blob/master/doc/design/monorepo.md) might do a good job explaining the reasons.

**Comment by HaoZeke** [comment]
Ah, damn, I missed that line in the README...

Nevertheless perhaps a dev repo (not for publishing to npm) might be officially sanctioned?

**Comment by KyleAMathews** [comment]
Why split off the plugins?

Agree it'd be really nice if it was easier to create copies of the example site. I have some ideas on how to do that. Having a monorepo makes maintaining Gatsby far easier as for example, PRs affecting core and plugins can land at the same time. Also we can maintain common tooling for things like tests and prettier and linting.
