### ISSUE TITLE
npm audit found 4 high severity vulnerabilities found after fresh install @gatsby3.4.1

### ISSUE THREAD

**Issue by sniperyork** [gatsbyjs/gatsby#31266]
## Description

Npm alerted 4 high severity vulnerabilities after creating a brand new project using Gatsby-cli.

After running npm audit, the report shows the following:

`# npm audit report

xmlhttprequest-ssl  <1.6.2
Severity: high
Arbitrary Code Injection - https://npmjs.com/advisories/1665
fix available via `npm audit fix --force`
Will install gatsby@2.22.10, which is a breaking change
node_modules/xmlhttprequest-ssl
  engine.io-client  1.6.0 - 4.1.3
  Depends on vulnerable versions of xmlhttprequest-ssl
  node_modules/engine.io-client
    socket.io-client  1.4.0 - 3.1.3
    Depends on vulnerable versions of engine.io-client
    node_modules/socket.io-client
      gatsby  2.18.13-telemetry-test.2972 - 2.18.13-telemetry-test.2976 || >=2.22.11-no-pollyfils.22
      Depends on vulnerable versions of socket.io-client
      node_modules/gatsby

4 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force`

### Steps to reproduce

1. Create a new project using 'gatsby new project'
2.  observe msg after installation

### Expected result

success msg with 0 vulnerabilities.

### Actual result

`4 high severity vulnerabilities`

### Environment

  System:
    OS: macOS 11.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    npm: 7.11.2 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 88.0
    Safari: 14.1
  npmPackages:
    gatsby: ^3.4.1 => 3.4.1
    gatsby-plugin-gatsby-cloud: ^2.4.1 => 2.4.1
    gatsby-plugin-image: ^1.4.0 => 1.4.0
    gatsby-plugin-manifest: ^3.4.0 => 3.4.0
    gatsby-plugin-offline: ^4.4.0 => 4.4.0
    gatsby-plugin-react-helmet: ^4.4.0 => 4.4.0
    gatsby-plugin-sharp: ^3.4.1 => 3.4.1
    gatsby-source-filesystem: ^3.4.0 => 3.4.0
    gatsby-transformer-sharp: ^3.4.0 => 3.4.0
  npmGlobalPackages:
    gatsby-cli: 3.4.1

**Comment by bacxhus** [comment]
This happened to me as well but on an existing gatsby site that I'm currently developing.

**Comment by slk333** [comment]
I did `npm update` and now it says my projet has 12 high severity vulnerabilities. So I can confirm this issue exists

**Comment by LekoArts** [comment]
Hi!

While those audit messages might seem scary it doesn't show the full picture of the individual package is affected as they are not sophisticated enough to check the actual code. While we're on a old version (and at some point we'll update), the current verison of `engine.io-client` and also the one we use isn't even affected by that as they always used `async`. See: https://github.com/socketio/engine.io-client/releases/tag/4.1.4
And the version we currently use: https://unpkg.com/browse/engine.io-client@1.6.0/lib/transports/polling-xhr.js

Additionally, we only use socket.io for the local development experience, it's not used on production builds or on your own live site.
