### ISSUE TITLE
gatsby-plugin-netlify-cms converting circular structure to JSON

### ISSUE THREAD

**Issue by timtilch** [gatsbyjs/gatsby#31278]
## Description

I am migrating a Gatsby page from v2 to v3. In my project I am using `gatsby-plugin-netlify-cms` together with `netlify-cms-app` both on newest version. Locally `gatsby develop` and `gatsby build` are working perfectly. I am facing no problems at all, but when it comes to running within a pipeline on gitlab I am running into an error. I have already run `gatsby clean` without any effect. Also I deactivated the cache within the pipeline. If I remove `gatsby-plugin-netlify-cms` from gatsy-config.js the build process succeeds also on CI. NPM and NODE are running on the same versions in both environments.

<img width="848" alt="Bildschirmfoto 2021-05-06 um 09 09 15" src="https://user-images.githubusercontent.com/15344527/117256398-eeac1500-ae4a-11eb-93eb-ed4ed0e3cdfd.png">

### Steps to reproduce

1. Add `gatsby-plugin-netlify-cms` together with `netlify-cms-app` to package.json
2. Import `gatsby-plugin-netlify-cms` in gatsy-config.js
3. Run `gatsby build` locally and on CI.

### Expected result

`gatsby build` should succeed on pipeline like it does locally.

### Actual result

`gatsby build` fails with the error shown in the screenshot above.

### Environment

```
System:
    OS: Linux 4.19 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (1) x64 Intel(R) Xeon(R) CPU @ 2.30GHz
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 12.22.1 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
  Languages:
    Python: 2.7.13 - /usr/bin/python
  npmPackages:
    gatsby: 3.4.1 => 3.4.1 
    gatsby-image: 3.4.0 => 3.4.0 
    gatsby-plugin-gdpr-cookies: 2.0.0 => 2.0.0 
    gatsby-plugin-json-remark: 1.1.5 => 1.1.5 
    gatsby-plugin-manifest: 3.4.0 => 3.4.0 
    gatsby-plugin-netlify-cms: 5.4.1 => 5.4.1 
    gatsby-plugin-react-helmet: 4.4.0 => 4.4.0 
    gatsby-plugin-react-svg: 3.0.1 => 3.0.1 
    gatsby-plugin-remove-serviceworker: 1.0.0 => 1.0.0 
    gatsby-plugin-robots-txt: 1.5.6 => 1.5.6 
    gatsby-plugin-s3: 0.3.8 => 0.3.8 
    gatsby-plugin-sharp: 3.4.1 => 3.4.1 
    gatsby-plugin-sitemap: 2.12.0 => 2.12.0 
    gatsby-plugin-styled-components: 4.4.0 => 4.4.0 
    gatsby-remark-custom-blocks: 3.4.0 => 3.4.0 
    gatsby-remark-images: 5.1.0 => 5.1.0 
    gatsby-source-filesystem: 3.4.0 => 3.4.0 
    gatsby-source-graphql: 3.4.0 => 3.4.0 
    gatsby-transformer-json: 3.4.0 => 3.4.0 
    gatsby-transformer-remark: 4.1.0 => 4.1.0 
    gatsby-transformer-remark-frontmatter: 1.0.1 => 1.0.1 
    gatsby-transformer-sharp: 3.4.0 => 3.4.0 
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. Unfortunately I personally haven't seen this error. If you can create a [minimal reproduction][reproduction] that shows this behavior during `gatsby build` we can help further -- otherwise I'm afraid this is a deployment/GitLab issue. Maybe double check pages like https://www.gatsbyjs.com/docs/deploying-to-gitlab-pages/ or https://gitlab.com/pages/gatsby if you set it up correctly.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by floka94** [comment]
@LekoArts same problem here! I created a minimal reproduction repo here >https://gitlab.com/flo_kas/bug-repro<, as you can see, my build job is also failing with the same error >https://gitlab.com/flo_kas/bug-repro/-/jobs/1247734074<

**Comment by adrian-goe** [comment]
Here is a npm debug log from @timtilch's pipeline. Maybe this will help.
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.14.12
3 info using node@v14.16.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle homepage@1.0.0~prebuild: homepage@1.0.0
6 info lifecycle homepage@1.0.0~build: homepage@1.0.0
7 verbose lifecycle homepage@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle homepage@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/builds/companyname/homepage/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle homepage@1.0.0~build: CWD: /builds/companyname/homepage
10 silly lifecycle homepage@1.0.0~build: Args: [ '-c', 'gatsby build' ]
11 silly lifecycle homepage@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle homepage@1.0.0~build: Failed to exec build script
13 verbose stack Error: homepage@1.0.0 build: `gatsby build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid homepage@1.0.0
15 verbose cwd /builds/companyname/homepage
16 verbose Linux 4.19.78-coreos
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v14.16.1
19 verbose npm  v6.14.12
20 error code ELIFECYCLE
21 error errno 1
22 error homepage@1.0.0 build: `gatsby build`
22 error Exit status 1
23 error Failed at the homepage@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by timtilch** [comment]
Updated some dependencies to latest version and now it works again.

```
"gatsby": "3.5.0",
"gatsby-plugin-netlify-cms": "5.5.0",
```

**Comment by LekoArts** [comment]
@floka94 Can you please test out the versions that @timtilch posted?

**Comment by floka94** [comment]
Does not work for me (https://gitlab.com/flo_kas/bug-repro/-/jobs/1268629724) @timtilch can you please check what i did wrong? https://gitlab.com/flo_kas/bug-repro/-/blob/master/package.json

**Comment by timtilch** [comment]
@floka94 I can see nothing wrong with your code. Have you tried cleaning the runners cache?

**Comment by floka94** [comment]
Yep ... still does not work :-/ see the last pipeline (I cleared runners cache before https://gitlab.com/flo_kas/bug-repro/-/jobs/1276644620)
