### ISSUE TITLE
ACF 'User' has inconsistent behavior at server Graphql endpoint vs Gatsby local graphql

### ISSUE THREAD

**Issue by shawngrona** [gatsbyjs/gatsby#31290]
## Description
ACF Value for a User field has inconsistent behavior at server Graphql endpoint vs Gatsby local graphql.  The Wordpress server endpoint reports the correct User array while the local Gatsby graphql is reporting different values, sometimes empty, sometimes filled out, sometimes only after updating the User on the Wordpress server.

This is similar kind of issue reported in multiple other places: https://github.com/gatsbyjs/gatsby/issues/30755, https://github.com/gatsbyjs/gatsby/issues/29529, https://github.com/gatsbyjs/gatsby/issues/30868

### Steps to reproduce

I have created a minimum reproducible solution here https://github.com/shawngrona/gatsby-acf-mri with instructions to reproduce listed at top of the README

### Expected result

ACF Values should be the same in the server Wordpress GraphQL endpoint as they are on the local Gatsby

### Actual result

The ACF values are not the same on Wordpress GraphQL endpoint vs the local Gatsby

### Environment

```

  System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.0 - ~/.nvm/versions/node/v12.16.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 88.0
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.4.1 => 3.4.1 
    gatsby-plugin-sharp: ^3.4.1 => 3.4.1 
    gatsby-source-wordpress: ^5.4.1 => 5.4.1 
    gatsby-transformer-sharp: ^3.4.0 => 3.4.0 
```

**Comment by shawngrona** [comment]
I noticed @TylerBarnes worked on some of the related issues I linked above, Typer is it possible you can take a look into this issue?

**Comment by shawngrona** [comment]
same kind of issue here https://github.com/gatsbyjs/gatsby/issues/31614

**Comment by shawngrona** [comment]
Since I've opened this I've done some more troubleshooting I dont believe this to be an issue with gatsby or gatsby-source-wordpress. I've opened an issue with wp-graphql https://github.com/wp-graphql/wp-graphql/issues/1931

**Comment by TylerBarnes** [comment]
You will have to find the right WPGQL hook to make all users public or otherwise I would suggest using a CPT for Authors instead of using Users
