### ISSUE TITLE
Enable brotli compression for all files currently compressed gzip, and add custom file types in your internal Gatsby Hosting integration with Fastly

### ISSUE THREAD

**Issue by doctorpangloss** [gatsbyjs/gatsby#31294]
## Description

Gatsby Hosting is serving gzipped content instead of brotli-compressed content.

Additionally, some file types, like `application/octet-stream` and `application/wasm`, are not compressed at all.

This is a great win - some people online record a mean improvement of 21% in compression of brotli over gzip.

### Steps to reproduce

 1. Visit https://hiddenswitch.com in Chrome.
 2. Open the Chrome Inspector tab.
 3. Check Disable cache.
 4. Reload.
 5. Observe `page-data.json` is requested with `gzip, deflate, br`
 6. Observe `page-data.json` is served with `content-encoding: gzip`. It should be `br`.
 7. Observe `https://hiddenswitch.com/6325457c53738c5e7be9753274664076.wasm` is requested with `gzip, deflate, br`.
 8. Observe `https://hiddenswitch.com/6325457c53738c5e7be9753274664076.wasm` is not served compressed. It should be `br`.
 9. Observe `https://hiddenswitch.com/4100c18dfdfedb72c293daea1884818a.data` is requested with `gzip, deflate, br`.
 10. Observe `https://hiddenswitch.com/4100c18dfdfedb72c293daea1884818a.data` is not served compressed. It should be `br`.

### Expected result

Wherever there is currently `gzip` being served, the host should serve brotli compressed content.

`application/octet-stream` and `application/wasm` files should be served compressed with brotli.

### Actual result

Gzip content or uncompressed content is served instead.

### Environment

```

  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor              
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.5 - /c/Python39/python
  Browsers:
    Edge: Spartan (44.19041.964.0), Chromium (90.0.818.51)
  npmPackages:
    gatsby: ^3.2.1 => 3.2.1 
    gatsby-background-image: ^1.5.2 => 1.5.2 
    gatsby-plugin-brotli: ^2.0.0 => 2.0.0 
    gatsby-plugin-image: ^1.3.0 => 1.3.0 
    gatsby-plugin-react-helmet: ^4.3.0 => 4.3.0 
    gatsby-plugin-sass: ^4.3.0 => 4.3.0 
    gatsby-plugin-sharp: ^3.3.0 => 3.3.0 
    gatsby-plugin-styled-components: ^4.4.0-next.0 => 4.4.0-next.0 
    gatsby-source-filesystem: ^3.3.0 => 3.3.0 
    gatsby-transformer-remark: ^4.0.0 => 4.0.0 
    gatsby-transformer-sharp: ^3.3.0 => 3.3.0 
    gatsby-transformer-yaml: ^3.3.0 => 3.3.0 
  npmGlobalPackages:
    gatsby-cli: 2.12.42
```

**Comment by doctorpangloss** [comment]
https://docs.fastly.com/en/guides/enabling-automatic-compression#setting-up-an-advanced-compression-policy

**Comment by LekoArts** [comment]
Hi, thanks for the suggestion!

This repository (and its bug reports & feature requests) is solely for the open source product. For Gatsby Cloud please post your suggestion here: https://portal.gatsbyjs.com/gatsby-cloud

Thanks!
