### ISSUE TITLE
Image Generation not Working

### ISSUE THREAD

**Issue by tderflinger** [gatsbyjs/gatsby#3131]
Hello!

I have GatsbyJS version 1.1.5 and Node 6.3.1 on Ubuntu Linux 15.04.
Every time I am building for production with "yarn build", the images are not converted correctly. Meaning they look fuzzy on the production site.
When I change something in my gatsby-config.js, the images are generated though. I can see that when I subsequently call "yarn build".

Is there any switch or any other way to let Gatsby generate the images automatically? 

Otherwise, thanks for this great product! :) It is super!

Regards,
-Tommy

**Comment by calcsam** [comment]
Assume you're using gatsby-plugin-sharp / gatsby-transformer-sharp -- are you downsampling the images in your GraphQL queries?

**Comment by tderflinger** [comment]
Tnx for the response!

This is part of my gatsby-config.js:

{
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: [
          {
            resolve: 'gatsby-remark-images',
            options: {
              maxWidth: 600,
              linkImagesToOriginal: false
            }
          },
          {
            resolve: `gatsby-plugin-google-analytics`,
            options: {
              trackingId: '',
              // Setting this parameter is optional
              anonymize: true
            }
          }
        ]
      }
    },
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-sharp'

So I am using gatsby-remark-images and gatsby-plugin-sharp. I remember I used a scaffolding tool to do the initial creation of the Gatsby blog app. I did not change anything with the way images are sampled.

**Comment by fk** [comment]
Hi @tderflinger! I think @calcsam is headed in the right direction when mentioning downsampling: As you mentioned, `gatsby-remark-images` uses `gatsby-plugin-sharp`, more specifically its [`responsiveSizes`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sharp#responsivesizes) method, to generate responsive images from images referenced in Markdown.

`responsiveSizes` has `quality` at `50`% (for JPGs, and `pngCompressionLevel` at `9`) per default. Assuming that your images are JPGs, it might be those 50% causing blurry images/compression artifacts.

Could you please try to add `quality: 80` to your configuration …

```
{
  resolve: 'gatsby-remark-images',
  options: {
    quality: 80,
    maxWidth: 600,
    linkImagesToOriginal: false
  }
},
```

… and see if that helps/improves things?

Note to self: In any case we should update the [`gatsby-remark-images` README](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-remark-images) to mention `gatsby-plugin-sharp` and its options.

**Comment by tderflinger** [comment]
Hi fk! Thanks for your response.
Unfortunately, it still causes a blurry image with my jpegs. But when I change something in the gatsby-config.js (just a add or remove a space) and run "yarn build", all images get regenerated and it works. I can see during the build process that the images are getting generated.
Now I need a switch or a workaround to generate the images every yarn build call.

**Comment by fk** [comment]
@tderflinger Did you find a solution to this? Do you have your project online somewhere so we could take a look?

**Comment by tderflinger** [comment]
Hi @fk, thanks for asking. Unfortunately not, I still just change a space in the gatsby-config.js before regenerating, then it works.
Here is my gatsby-config.js:
  plugins: [
    'gatsby-plugin-sass',
    'gatsby-plugin-catch-links',
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/pages`,
        name: 'pages',
      },
    },
    {
      resolve: `gatsby-plugin-sitemap`,
      options: { 
        priority: 0.9
      }
    },
    {
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: [
          {
            resolve: 'gatsby-remark-images',
            options: {
              quality: 80,
              maxWidth:  600,
              linkImagesToOriginal: false
            }
          },
          {
            resolve: `gatsby-plugin-google-analytics`,
            options: {
              trackingId: 'UA-xx-1',
              // Setting this parameter is optional
              anonymize: true
            }
          }
        ]
      }
    },
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-sharp'
  ],

**Comment by protoEvangelion** [comment]
Even the Kanye photos on the demo site are fuzzy.
Is that an intentional effect or just an acceptable resolution?
https://image-processing.gatsbyjs.org/
![](https://image-processing.gatsbyjs.org/static/fecolormatrix-kanye-west-77e6f7a658028a2953e5ff1f7a849b32-daa58.jpg)

**Comment by domhacking** [comment]
I am having the same issue but adding a space and removing in config worked for me as well.
