### ISSUE TITLE
[gatsby-source-filesystem] createRemoteFileNode replaces original filename with hash

### ISSUE THREAD

**Issue by nik-s** [gatsbyjs/gatsby#3132]
If files are downloaded through createRemoteFileNode [the original filename is replaced by digest](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-filesystem/src/create-remote-file-node.js#L45).

The problem is that if you download images you lose the descriptive filenames (a similar issue has already been fixed in [gatsby-plugin-sharp](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sharp) #2752).

Would it be possible to append the original filename to digest? I know that`path.parse(url).ext` could be replaced with `path.parse(url).base` in [gatsby-remote-file-node.js](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-filesystem/src/create-remote-file-node.js#L45), however I'm not sure how this will work in cases such as #2985.

Thank you.

**Comment by calcsam** [comment]
What's the use-case where you'd like the original image name to remain? Do you expect the user to download images?

**Comment by nik-s** [comment]
As pointed out in #2306, descriptive image file names containing keywords are important for SEO.

Plugins such as [gatsby-source-wordpress](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-wordpress) download media from remote sources using **createRemoteFileNode** (I see now that *gatsby-source-wordpress* is the only one working like that at the moment?).

Thanks!

**Comment by ajayns** [comment]
Is there any documentation describing how to use createRemoteFileNode and also about how it works? I wanted to know the best method to handle files and images from a headless CMS while working on a gatsby-source plugin. @calcsam @nik-s @KyleAMathews

**Comment by m-allanson** [comment]
@ajayns It looks like the docs for `createRemoteFileNode` are currently a TODO. I'll open an issue for creating docs for this.

**Comment by ajayns** [comment]
@m-allanson Could you brief me a bit about it then? That'd help me for now and maybe that;d help me come up with a PR.

**Comment by m-allanson** [comment]
@ajayns I've put everything I know (which admittedly isn't that much) about `createRemoteFileNode` into #4302. Let me know if you've any specific questions and I'll see if I can help.

**Comment by ajayns** [comment]
@m-allanson Okay that's great!

**Comment by KyleAMathews** [comment]
Per the original request — we should keep the original name + a bit of hash at the end.

The hash is to differentiate between files named the same but from different places in the domain e.g. there could be a dozen files named avatar.jpg but which are all different.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
