### ISSUE TITLE
createRedirect does not forward query params

### ISSUE THREAD

**Issue by JKlause** [gatsbyjs/gatsby#31327]
## Description

In using `createRedirect()` (being built and hosted onAWS), the redirects do not forward any query params (if present).
I would request a boolean be exposed as an option on createRedirect() to forward queryParams if they are present.

This feature request was mentioned in this [discussion](https://github.com/gatsbyjs/gatsby/discussions/27582). 
If this has been formally entered as a feature request, is there a way to track that progress?

### Steps to reproduce

In `createPages`:
`createRedirect(
     toPath: '/foo',
     isPermanent: true,
     fromPath: '/bar,
)`

### Desired result

When a user travels to `/bar?queryParam=happyGilmore`
they will be redirected to `/foo?queryParam=happyGilmore`

### Actual result

user gets redirected to `/foo`

### Environment

I don't know that you need this for this feature request, but I am happy to supply you with more information if needed.
Thank you!

**Comment by KyleAMathews** [comment]
This could make sense to add to Gatsby but I'm curious if it's necessary? Since you're self-hosting on AWS, couldn't you configure this in AWS?

**Comment by LekoArts** [comment]
Please leave any comments in the feature request, thanks!
