### ISSUE TITLE
Gatsby build error when WordPress CMS has moved uploads folder

### ISSUE THREAD

**Issue by paulstroot** [gatsbyjs/gatsby#31335]
## Description

When updating an image in WordPress, my Gatsby build (production or development) throws the error. "url passed to create-remote-file-node is either missing or not a proper web uri". If I run the build again it is successful. It seems as if this only happens the first time a remote image is pulled into Gatsby. There are no special characters in the file name and responsive images is turned off in WordPress.

### Steps to reproduce

Set the url of your wordpress CMS to a wordpress site that has the "uploads" directory set to "media". i.e/ _define('UPLOADS','media');_

Run "Gatsby Develop" or "Gatsby Build" on your gatsby site.

If I am running a development build, updating an image in the "media" section of WordPress will cause Gatsby to automatically update the development build, and the updated image will crash the development build throwing the error.

In a production build, If I update the image in WordPress, the next build causes the error. Subsequent builds are successful.

### What Happens
Gatsby returns the error 
`"Error: url passed to create-remote-file-node is either missing or not a proper web uri: [IMAGE URL]", `
where [IMAGE URL] is the url of the image that was just updated.

### What should happen?
successful build with no errors. The new media item pulled into the gatsby public folder.

### gatsby-config.js

```
module.exports = {
  plugins: [
    {
      resolve: `gatsby-source-wordpress`,
      options: {
        url: `http://wp-base-install.paulstroot.com/graphql`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `assets`,
        path: `${__dirname}/content/assets`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    `gatsby-plugin-react-helmet`,
  ],
}

```

### Environment
```
  npmPackages:
    "gatsby": "^3.3.0",
    "gatsby-image": "^3.3.0",
    "gatsby-plugin-manifest": "^3.3.0",
    "gatsby-plugin-offline": "^4.3.0",
    "gatsby-plugin-react-helmet": "^4.3.0",
    "gatsby-plugin-sharp": "^3.3.0",
    "gatsby-source-filesystem": "^3.3.0",
    "gatsby-source-wordpress": "^5.3.0",
    "gatsby-transformer-sharp": "^3.3.0",
    "html-react-parser": "^1.1.1",
    "lodash": "^4.17.20",
    "postcss": "^8.2.10",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-helmet": "^5.2.1",
    "typeface-merriweather": "1.1.13",
    "typeface-montserrat": "1.1.13"
```

### Wordpress
```
    Version 5.7

Installed Plug-ins:
    WP Gatsby 1.0.10
    WP GraphQL 1.3.9
    
Only edit to wp-config.php:
    define('UPLOADS','media');
```

I found the code that throws this error. It can be found in [create-nodes/create-remote-file-node/index.js:424-430](https://github.com/gatsbyjs/gatsby/blob/54d4721462b9303fed723fdcb15ac5d72e103778/packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-remote-file-node/index.js#L424-L430)
```
  if (!url || isWebUri(url) === undefined) {
    return Promise.reject(
      new Error(
        `url passed to create-remote-file-node is either missing or not a proper web uri: ${url}`
      )
```

**Comment by paulstroot** [comment]
Another update on this. I have tested this with a clean install of WordPress (v5.7), and a clean installation of "gatsby-wordpress-starter-blog". As soon as I change the uploads folder to "media" in the wp-config file, I get an error whenever I update an image in WordPress. I am going to update my original post to reflect this minimal environment.

**Comment by paulstroot** [comment]
I just discovered something in the gatsby-source-wordpress source code that may be the crux of the issue. There is a method in process-node.js named "ensureSrcHasHostname()", that has a hardcoded "wp-content' as the media directory.

See this file for the exact lines of code.
[/create-nodes/process-node.js:88-96](https://github.com/gatsbyjs/gatsby/blob/54d4721462b9303fed723fdcb15ac5d72e103778/packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js#L88-L96)

```
export const ensureSrcHasHostname = ({ src, wpUrl }) => {  
  const { protocol, host } = url.parse(wpUrl)
  if (src.startsWith(`/wp-content`)) {    
    src = '${protocol}//${host}${src}'
  }
  return src
}
```

Ideally, this should probably bring in the media directory from the wordpress configuration instead of assmung wp-content, right?

I have not been able to dig deep enough to find out why the URL does not have the absolute path to start with, but I think this might be a good lead on the case.

**Comment by Lornz-** [comment]
Hi @paulstroot, I got the exact same issue since my wordpress is setup with [Bedrock](https://roots.io/bedrock/) which move the **uploads** directory to the another root (/app) directory. 
Did you find a workaround on this?

**Comment by paulstroot** [comment]
I did not ever get a fix for this. I believe the Gatsby cloud guys were aware of the issue when we were working with this, but I guess it didn't seem to be a priority. I even called out the exact line of code that was causing the issue in his thread. The only solution I found was to publish immediately again after getting the error, or moving everything back into the uploads folder. sorry.
