### ISSUE TITLE
Spelling issue

### ISSUE THREAD

**Issue by EugeneGohh** [gatsbyjs/gatsby#31341]
## Summary

Fix spelling issue from **Javascript** to **JavaScript** according to [Wikipedia](https://en.wikipedia.org/wiki/JavaScript). Link to the page https://www.gatsbyjs.com/why-gatsby/.

![Untitled11](https://user-images.githubusercontent.com/64187129/117563790-d8b48380-b0da-11eb-9859-4dbcce195419.png)

### Motivation

To increase specificity. **Javascript** should be **JavaScript** according to Wikipedia. Everyone will benefit from the change.

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.com/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.com/contributing/docs-templates/)
  - [Example of a similar article]()

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by LekoArts** [comment]
Thanks, I've updated the text!
