### ISSUE TITLE
After a fresh install of Gatsby I got problems was required audit fix

### ISSUE THREAD

**Issue by carloslsilva** [gatsbyjs/gatsby#31377]
## Description

After install gatsby packcage I get --> 10 vulnerabilities (5 moderate, 5 high)
Update an old project with gatsby v2 drives to a similar situation (I know this is another problem, but I got here testing if a new version free me of this problems)

Audit fix doesn't  fix anything

### Steps to reproduce

npm install --save react react-dom gatsby

### Expected result

0 vulnerabilities

#### npm audit report

postcss  7.0.0 - 8.2.9
Severity: moderate
Regular Expression Denial of Service - https://npmjs.com/advisories/1693
fix available via `npm audit fix --force`
Will install gatsby@2.32.13, which is a breaking change
node_modules/postcss
  gatsby  2.6.1-ink-node6.16 - 2.6.1-ink-node6.17 || 2.18.13-telemetry-test.2972 - 2.18.13-telemetry-test.2976 || >=2.22.12
  Depends on vulnerable versions of gatsby-cli
  Depends on vulnerable versions of postcss
  node_modules/gatsby
    babel-plugin-remove-graphql-queries  >=2.17.0-next.0
    Depends on vulnerable versions of gatsby
    node_modules/babel-plugin-remove-graphql-queries
    gatsby-plugin-page-creator  >=2.11.0-next.0
    Depends on vulnerable versions of gatsby
    node_modules/gatsby-plugin-page-creator
    gatsby-plugin-typescript  >=2.13.0-next.0
    Depends on vulnerable versions of gatsby
    node_modules/gatsby-plugin-typescript
    gatsby-plugin-utils  >=0.10.0-next.0
    Depends on vulnerable versions of gatsby
    node_modules/gatsby-plugin-utils

trim  <0.0.3
Severity: high
Regular Expression Denial of Service in trim - https://npmjs.com/advisories/1700
fix available via `npm audit fix --force`
Will install gatsby@2.32.13, which is a breaking change
node_modules/trim
  remark-parse  <=8.0.3
  Depends on vulnerable versions of trim
  node_modules/remark-parse
    gatsby-recipes  0.0.7-unifiedroutes.76 - 0.0.7-unifiedroutes-v2.135 || >=0.1.31
    Depends on vulnerable versions of remark-parse
    node_modules/gatsby-recipes
      gatsby-cli  2.8.20-telemetry-test.2972 - 2.8.20-telemetry-test.2976 || 2.11.10-unifiedroutes.76 - 2.11.10-unifiedroutes-v2.135 || >=2.12.37
      Depends on vulnerable versions of gatsby-recipes
      node_modules/gatsby-cli
        gatsby  2.6.1-ink-node6.16 - 2.6.1-ink-node6.17 || 2.18.13-telemetry-test.2972 - 2.18.13-telemetry-test.2976 || >=2.22.12
        Depends on vulnerable versions of gatsby-cli
        Depends on vulnerable versions of postcss
        node_modules/gatsby
          babel-plugin-remove-graphql-queries  >=2.17.0-next.0
          Depends on vulnerable versions of gatsby
          node_modules/babel-plugin-remove-graphql-queries
          gatsby-plugin-page-creator  >=2.11.0-next.0
          Depends on vulnerable versions of gatsby
          node_modules/gatsby-plugin-page-creator
          gatsby-plugin-typescript  >=2.13.0-next.0
          Depends on vulnerable versions of gatsby
          node_modules/gatsby-plugin-typescript
          gatsby-plugin-utils  >=0.10.0-next.0
          Depends on vulnerable versions of gatsby
          node_modules/gatsby-plugin-utils

10 vulnerabilities (5 moderate, 5 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

### Environment

  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/bin/node
    npm: 7.12.1 - /usr/bin/npm
  npmPackages:
    gatsby: ^3.5.0 => 3.5.0

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

Similar to https://github.com/gatsbyjs/gatsby/issues/31266#issuecomment-833319227 I want to re-iterate here that those messages won't affect your finished site as nothing of that is run on the client, only during development. You can ignore those as they are not relevant to Gatsby.

**Comment by carloslsilva** [comment]
> Hi, thanks for the issue!
> 
> Similar to [#31266 (comment)](https://github.com/gatsbyjs/gatsby/issues/31266#issuecomment-833319227) I want to re-iterate here that those messages won't affect your finished site as nothing of that is run on the client, only during development. You can ignore those as they are not relevant to Gatsby.

Hi, I can understand it, but this doesn't sell very well.
Thank you for for your guidance and your prompt reply.

**Comment by el7cosmos** [comment]
@LekoArts maybe those messages won't affect the finished site, but they break builds on CI

**Comment by reekrd** [comment]
I get the same 10 vulnerabilities and the below warnings are logged during installation

`npm WARN ERESOLVE overriding peer dependency`
`npm WARN Found: graphql@15.5.0`
`npm WARN node_modules/graphql`
`npm WARN   graphql@"^15.4.0" from gatsby@3.5.1`
`npm WARN   node_modules/gatsby`
`npm WARN     gatsby@"*" from the root project`
`npm WARN     1 more (babel-plugin-remove-graphql-queries)`
`npm WARN   1 more (eslint-plugin-graphql)`
`npm WARN `
`npm WARN Could not resolve dependency:`
`npm WARN peer graphql@"^14.4.1" from express-graphql@0.9.0`
`npm WARN node_modules/express-graphql`
`npm WARN   express-graphql@"^0.9.0" from gatsby@3.5.1`
`npm WARN   node_modules/gatsby`
`npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained`
`npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained`
`npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated`
`npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated`
`npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.`
`npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.`
`npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.`
`npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'`
`npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained`
`npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'`

Not sure if it affects anything at all but that fsevents 1 & Cokidar 2 will break on node v14+ feels like it's not optimal. But as I said no idea if that affects anything .

**Comment by meera** [comment]
I get similar warning manual review  flags postcss, trim and browserslist packages. 
'Regular Expression Denial of Service in trim' is high.

This doesn't affect the functionality - but ignoring it isn't the solution.
