### ISSUE TITLE
question: does gatsby still render a page if its data dependencies are unchanged?

### ISSUE THREAD

**Issue by r1b** [gatsbyjs/gatsby#3137]
I am curious if gatsby can do `incremental` builds. Lets say I have a page that depends on some set of nodes. If gatsby can determine that none of the data dependencies have changed will it still attempt to render the page again?

**Comment by calcsam** [comment]
Currently Gatsby does incremental builds in development, for example while using `gatsby-source-filesystem` it will hot reload when you change any markdown file that is being pulled in. However there is no ability to do data dependency diffing in production -- it does full rebuilds.
