### ISSUE TITLE
Imported CSS from packages with sideEffects set to false is omitted from bundle when using `import` syntax.

### ISSUE THREAD

**Issue by mtlewis** [gatsbyjs/gatsby#31388]
## Description

Imported CSS from packages with sideEffects set to false is omitted from bundle when using `import` syntax.

### Steps to reproduce

1. Clone https://github.com/mtlewis/gatsby-css-import-bug-repro. A few things to note about this repro:
  * In order to reproduce the bug, there's a local private package named `local-css-package` inside the repository, depended on with a `file:` dependency in package.json. However, I originally encountered this bug with an npm package loaded from a registry, there's nothing about this issue that is specific to file dependencies.
  * The package contains a single stylesheet, with a single selector that adds "package CSS included!" pseudocontent before the body.
2. `yarn install`
3. `yarn develop`

Notice that the page loaded doesn't include the pseudocontent, even though styles.css is imported in pages/index.js. There's two ways to get it to work:
1. Remove `sideEffects: false` from the package.json in local-css-package.
2. Switch to importing the styles using `require`.

### Expected result

It seems to me that the value of the `sideEffects` property in package.json should have no bearing on whether CSS inside the package can be used. Perhaps the underlying cause here is that the CSS is getting tree-shaken away when using `import` syntax - maybe because we're not directly using anything from the imported styles.

### Actual result

When `sideEffects` is set to true, the CSS is not included in the bundle.

### Environment

> Run `gatsby info --clipboard` in your project directory and paste the output here.

Gatsby Info:
```
  System:
    OS: macOS 11.2.1
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.4.1 => 3.5.0 
```

> Also name any `flags` you use inside `gatsby-config.js`.

None

**Comment by herecydev** [comment]
> Perhaps the underlying cause here is that the CSS is getting tree-shaken away when using import syntax - maybe because we're not directly using anything from the imported styles.

I think it's exactly that. Something with no side effects *and* that's not imported will be omitted (as it's deemed safe to do so). Css should absolutely be marked as a side effect, i.e. `"sideEffects": ["*.css"]`

**Comment by mtlewis** [comment]
Great shout, thanks for pointing it out @herecydev! Lots of discussion about this in webpackjs/webpack#6741, and it's explicitly called out in the webpack docs here: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free.

I'll reach out to the original package authors and suggest they update their "sideEffects" property accordingly, and close this issue. Thanks again!
