### ISSUE TITLE
Cannot use assetPrefix to make asset url relative

### ISSUE THREAD

**Issue by darron1217** [gatsbyjs/gatsby#31383]
## Description

I used `assetPrefix` to prefix every images with relative path `./`.
(To open index.html directly on browser)

### Steps to reproduce

1. Put `assetPrefix` to `gatsby-config.js` with value `./`
  ```js
  module.exports = {
    assetPrefix: `./`,
  }
  ```

2. Build with `--prefix-paths` option
  ```shell
  gatsby build --prefix-paths
  ```

### Expected result

Every image path prefixed with `./`

### Actual result

Every image path prefixed with `/./`

### Related Source
https://github.com/gatsbyjs/gatsby/blob/b274d80b46baaeaafb00fcbb24332a1e5660e9bf/packages/gatsby/src/utils/get-public-path.ts#L21

https://github.com/gatsbyjs/gatsby/blob/b274d80b46baaeaafb00fcbb24332a1e5660e9bf/packages/gatsby/src/utils/get-public-path.ts#L3-L4

I guess `isURL` determines whether to put `/` or not, but it should also check whether it is relative path or not!

### Environment

```
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  Binaries:
    Node: 14.16.1 - ~\AppData\Local\Temp\yarn--1620810233350-0.5306059472857247\node.CMD
    Yarn: 1.22.5 - ~\AppData\Local\Temp\yarn--1620810233350-0.5306059472857247\yarn.CMD
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 90.0.4430.93
    Edge: Spartan (44.19041.906.0), Chromium (90.0.818.56)
  npmPackages:
    gatsby: 3.2.1 => 3.2.1 
    gatsby-plugin-create-client-paths: ^3.3.0 => 3.3.0 
    gatsby-plugin-graphql-config: ^0.13.0 => 0.13.0 
    gatsby-plugin-react-helmet: ^4.3.0 => 4.3.0 
    gatsby-plugin-sass: ^4.4.0 => 4.4.0 
    gatsby-plugin-styled-components: 4.3.0 => 4.3.0 
    gatsby-plugin-typegen: ^2.2.4 => 2.2.4 
```

**Comment by darron1217** [comment]
I tested adding `.` case on `isURL`, and it causes redirect to `C:\` on windows.
I cannot find proper way to make every image url relative.

**Comment by LekoArts** [comment]
Hi!

Please see https://github.com/gatsbyjs/gatsby/discussions/14161 - we currently don't support this and you can upvote the feature request there.
