### ISSUE TITLE
Gatsby-awesome-pagination is preventing me from deploying my site - Uninstalled plugin issue

### ISSUE THREAD

**Issue by RubenGarciaBri** [gatsbyjs/gatsby#31398]
## Description

Hi, I'm trying to deploy my Gatsby site to Netlify, but every time I trigger the deployment, it fails showing the following issue:

_Error: /opt/build/repo/gatsby-node.js:2
import { paginate } from 'gatsby-awesome-pagination'
^^^^^^
SyntaxError: Cannot use import statement outside a module_

The thing is that the above line of code is nowhere in my gatsby-node file, **I don't even have the gatsby-awesome-pagination installed and the site works fine locally.**

Does anyone know what's going on? I'm definitely missing something here...

### Steps to reproduce

`npm clone https://github.com/RubenGarciaBri/contentful-blog.git`
`npm install`
`npm run develop`

### Expected result

Site gets successfully deployed

### Actual result

I get this error message
![image](https://user-images.githubusercontent.com/65225318/118035882-bd0fde00-b363-11eb-98a1-acfbe01be4c4.png)

**This is my gatsby-node.js file:**

`const path = require(`path`)
const { createFilePath } = require(`gatsby-source-filesystem`)

exports.createPages = async ({ graphql, actions, reporter }) => {
  const { createPage } = actions

  // Define a template for blog post
  const blogPost = path.resolve(`./src/templates/blog-post-contentful.js`)

  // Get all markdown blog posts sorted by date
  const result = await graphql(
    `
      {
        allContentfulPost {
          edges {
            node {
              slug
              title
              id
            }
          }
        }
      }
    `
  )

  if (result.errors) {
    reporter.panicOnBuild(
      `There was an error loading your blog posts`,
      result.errors
    )
    return
  }

  const posts = result.data.allContentfulPost.edges

  // Create blog posts pages
  // But only if there's at least one markdown file found at "content/blog" (defined in gatsby-config.js)
  // `context` is available in the template as a prop and as a variable in GraphQL

  if (posts.length > 0) {
    posts.forEach((post, index) => {
      // const previousPost = index === 0 ? null : posts[index - 1].slug
      // const nextPost = index === posts.length - 1 ? null : posts[index + 1].slug

      createPage({
        path: post.node.slug,
        component: blogPost,
        context: {
          slug: post.node.slug,
          previousPost: index === 0 ? null : posts[index - 1].slug,
          nextPost: index === posts.length - 1 ? null : posts[index + 1].slug 
        },
      })
    })
  }
}

exports.onCreateNode = ({ node, actions, getNode }) => {
  const { createNodeField } = actions

  if (node.internal.type === `MarkdownRemark`) {
    const value = createFilePath({ node, getNode })

    createNodeField({
      name: `slug`,
      node,
      value,
    })
  }
}

exports.createSchemaCustomization = ({ actions }) => {
  const { createTypes } = actions

  // Explicitly define the siteMetadata {} object
  // This way those will always be defined even if removed from gatsby-config.js

  // Also explicitly define the Markdown frontmatter
  // This way the "MarkdownRemark" queries will return `null` even when no
  // blog posts are stored inside "content/blog" instead of returning an error
  createTypes(`
    type SiteSiteMetadata {
      author: Author
      siteUrl: String
      social: Social
    }

    type Author {
      name: String
      summary: String
    }

    type Social {
      twitter: String
    }

    type MarkdownRemark implements Node {
      frontmatter: Frontmatter
      fields: Fields
    }

    type Frontmatter {
      title: String
      description: String
      date: Date @dateformat
    }

    type Fields {
      slug: String
    }
  `)
}
`

### Environment

System:
    OS: Windows 8.1 6.3.9600
    CPU: (4) x64 Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz
  Binaries:
    Node: 14.15.2 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 90.0.4430.93
  npmPackages:
    gatsby: ^3.4.2 => 3.4.2
    gatsby-plugin-feed: ^3.4.0 => 3.4.0
    gatsby-plugin-gatsby-cloud: ^2.4.1 => 2.4.1
    gatsby-plugin-google-analytics: ^3.4.0 => 3.4.0
    gatsby-plugin-image: ^1.4.0 => 1.4.0
    gatsby-plugin-manifest: ^3.4.0 => 3.4.0
    gatsby-plugin-offline: ^4.4.0 => 4.4.0
    gatsby-plugin-react-helmet: ^4.4.0 => 4.4.0
    gatsby-plugin-sass: ^4.4.0 => 4.4.0
    gatsby-plugin-sharp: ^3.4.0 => 3.4.0
    gatsby-remark-copy-linked-files: ^3.2.0 => 3.2.0
    gatsby-remark-images: ^4.2.0 => 4.2.0
    gatsby-remark-prismjs: ^4.2.0 => 4.2.0
    gatsby-remark-responsive-iframe: ^3.2.0 => 3.2.0
    gatsby-remark-smartypants: ^3.2.0 => 3.2.0
    gatsby-source-contentful: ^5.4.0 => 5.4.0
    gatsby-source-filesystem: ^3.4.0 => 3.4.0
    gatsby-transformer-remark: ^4.1.0 => 4.1.0
    gatsby-transformer-sharp: ^3.4.0 => 3.4.0
  npmGlobalPackages:
    gatsby-cli: 3.4.0

Thanks!

**Comment by KyleAMathews** [comment]
Are you looking at a branch perhaps? It's still here: https://github.com/RubenGarciaBri/contentful-blog/blob/a3e5ff3be851f7fb37e80a234fc4e1d9e656cdf7/gatsby-node.js#L2

**Comment by RubenGarciaBri** [comment]
> Are you looking at a branch perhaps? It's still here: https://github.com/RubenGarciaBri/contentful-blog/blob/a3e5ff3be851f7fb37e80a234fc4e1d9e656cdf7/gatsby-node.js#L2

Hi Kyle, thanks for pointing that out. Apologies for my lack of knowledge but how should I go about fixing this? That is an old commit so that import statement was deleted long ago. I don't understand why that's causing a problem.
