### ISSUE TITLE
New blog post gives error on first load

### ISSUE THREAD

**Issue by sedubois** [gatsbyjs/gatsby#3142]
The full images did not load on my first visit of the [new blog post](https://www.gatsbyjs.org/blog/2017-12-06-gatsby-plus-contentful-plus-netlify/). (Second time was fine.) Using Chrome 62.0.3202.94 (Official Build) (64-bit) on macOS. Unfortunately I closed the window before noting exactly which file threw the error (I seem to remember from a mouse hover that it was something with prop-types).

I can't reproduce the issue by visiting the page from a private session.

<img width="1421" alt="screen shot 2017-12-06 at 9 59 20" src="https://user-images.githubusercontent.com/4217871/33650894-8208c3c2-da6c-11e7-80de-7d164cd342a3.png">

**Comment by calcsam** [comment]
I've been able to reproduce this the first time I loaded the blog post, but not in an incognito window or after clearing cache. Perhaps this is a service worker bug?

**Comment by rdela** [comment]
Not seeing in 63.0.3239.90 beta or 65.0.3293.0 canary FWIW

**Comment by sedubois** [comment]
Maybe it was because I had already visited the blog previously, so my local service worker had something different from the updated website?

I don’t know much about service workers but it looks like there can be issues when the code gets updated. I’ve been observing the same several times when updating my own site, had to clear my browser cache to fix it.

**Comment by sedubois** [comment]
I had the issue again when opening https://www.gatsbyjs.org/blog/ today. Second load was okay.

<img width="1397" alt="screen shot 2018-01-26 at 21 23 07" src="https://user-images.githubusercontent.com/4217871/35456828-7c899e6c-02df-11e8-8f5f-b5154eb53a24.png">

Error is thrown at bootstrap%204819ead1ea268be1797a:52 which is a file starting with `// install a JSONP callback for chunk loading`. Code looks like this:
```
 		// Execute the module function
 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
```

Same issue is reported in #3582 with my own site.

**Comment by sedubois** [comment]
Closing as duplicate of #3582.
