### ISSUE TITLE
Set title for posts written as React components

### ISSUE THREAD

**Issue by melissamcewen** [gatsbyjs/gatsby#3143]
Is there an easy way to do this? I'm using React Helmet for the head and it's easy to set a global title, but I'm wondering if there is a way to set the title of pages created as React components?

**Comment by mpartipilo** [comment]
You can set the title from anywhere. React Helmet will use the last set value for the title (or any <head> tag) from anywhere it gets called.

**Comment by melissamcewen** [comment]
oooo that's easy, thanks! 

It seems to be working great. I just stuck a Helmet in the component. Sweet.

`
import React from 'react'
import Helmet from 'react-helmet'

const SecondPage = () => (
  <div>
    <Helmet
      title="TEST 123"
      meta={[
        { name: 'description', content: 'this is a test' },
        { name: 'keywords', content: 'test' },
      ]}
    />
    <h1>Test</h1>
    <p>Blah blah blah. </p>

  </div>
)

export default SecondPage


`

**Comment by benjaminhoffman** [comment]
Hope that was helpful @melissamcewen !  Closing this issue for now as it appears your question has been answered. Feel free to re open if not :)
