### ISSUE TITLE
Sitemap plugin wrong URL for link to sitemap

### ISSUE THREAD

**Issue by yagudaev** [gatsbyjs/gatsby#31452]
## Description

Wrong URL for sitemap, the header links to `/sitemap/sitemap-index.xml` which is correct. Hover that file links to `/sitemap-0.xml` instead of `/sitemap/sitemap-0.xml`.

![Screen Shot 2021-05-17 at 10 42 53 AM](https://user-images.githubusercontent.com/1386966/118533267-b8994b80-b6fc-11eb-9638-6150dae928a9.png)

### Steps to reproduce

1. Create new gatsby project 
2. Add the sitemap plugin with minimal settings as described in: https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap/#how-to-use
3. Run `yarn develop`
4. Open the gatasby page and view source, search for sitemap. Go to the `/sitemap/sitemap-index.xml` file the above broken link (missing the folder prefix)

### Expected result

Working link

### Actual result

Broken link

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here. Also name any `flags` you use inside `gatsby-config.js`.

```
  System:
    OS: macOS 11.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.1.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.11.2 - /usr/local/bin/npm
npmPackages:
  gatsby: ^3.2.0 => 3.2.0
  gatsby-plugin-sitemap: ^4.1.0 => 4.1.0  
```

**Comment by t2ca** [comment]
This is an issue that is getting fixed.

There is a temp fix and that is to change the folder path where sitemaps are stored to root. 

```
    {
      resolve: "gatsby-plugin-sitemap",
      options: {
        output: "/",
      },
    },
```

Otherwise you could use v3 of `gatsby-plugin-sitemap`.

**Comment by LekoArts** [comment]
This has been fixed with https://github.com/gatsbyjs/gatsby/pull/31184 and will be published as a patch soon.

**Comment by sriramgroot** [comment]
> This is an issue that is getting fixed.
> 
> There is a temp fix and that is to change the folder path where sitemaps are stored to root.
> 
> ```
>     {
>       resolve: "gatsby-plugin-sitemap",
>       options: {
>         output: "/",
>       },
>     },
> ```
> 
> Otherwise you could use v3 of `gatsby-plugin-sitemap`.

This working as sitemap file is moved to root folder of public, but they are named as `sitemap-index.xml` and its linked to `sitemap-0.xml`. Iam asking this because **Google's search console** is expecting the sitemap path as like i achieved now, it is expecting as `public/sitemap.xml` (<DOMAIN>/sitemap.xml)

How do i keep a single sitemap.xml with the file naming expected by **Google's search console**
