### ISSUE TITLE
gatsby-cli: Consider exposing Reporter For Use By Starters and Plugins

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#3145]
Using the reporter is a nice way to keep logging consistent, but it isn't exposed by `gatsby-cli`. I think it is worth exposing it or moving it to a separate consumable package. 

It can be used by reaching in to lib: `const reporter = require('gatsby-cli/lib/reporter');` which is fragile.

**Comment by jquense** [comment]
the reporter is exposed to plugins via the plugin api (https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/api-runner-node.js#L76) I think this is probably safer than everyone requiring a singleton package. especially if we want to tweak or change how this is handled (or make them pluggable)

**Comment by Undistraction** [comment]
That's great. I'd missed that. However, it would be nice to have access to it in `gatsby-node`and any related code, for example to report on the creation of pages, tags etc.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
