### ISSUE TITLE
[gatsby-plugin-image] translateZ(0) hacks can result in off by one pixel rendering in Firefox

### ISSUE THREAD

**Issue by jgosmann** [gatsbyjs/gatsby#31488]
## Description

I have images with a box shadow (on the `gatsby-image-wrapper` `<div>`) around them on my Gatsby site. After switching to `gatsby-plugin-image` from `gatsby-image`, a one pixel white line can appear between the actual image and the added shadow:

![image](https://user-images.githubusercontent.com/850157/118873167-b516e780-b8e9-11eb-8329-808508f55769.png)

This can either happen on the bottom or right side. Note that I am using an image width in dependence of the browser window which can end up being non-integer. By disabling all `transform: translateZ(0)` styles on the inner image, the issue is fixed.

At times I saw a similar problem in Chrome too, but it is much rarer, requires prior resizing of the browser window, and does not persist across page reloads (whereas reloading the page does not change anything in Firefox as long as the browser window size stays unchanged).

### Steps to reproduce

I created a [fairly minimal example](https://github.com/jgosmann/gatsby-plugin-image-translateZ). See the last commits for the relevant changes. Run it and open the site in Firefox. Then resize the browser window until the issue appears. I'm using a solid black image with a black border here:

![image](https://user-images.githubusercontent.com/850157/118876299-62d7c580-b8ed-11eb-99e2-f82f4c12a8d7.png)

### Expected result

There shouldn't be a white line appearing between the image and border:

![image](https://user-images.githubusercontent.com/850157/118877366-a8e15900-b8ee-11eb-846f-b0628335ebc6.png)

### Actual result

There appears a white line between the image and the border, see screenshots above.

### Environment

```
  System:
    OS: macOS 11.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.8 - /opt/local/bin/zsh
  Binaries:
    Node: 14.16.0 - /opt/local/bin/node
    Yarn: 1.22.10 - /opt/local/bin/yarn
    npm: 6.14.12 - /opt/local/bin/npm
  Languages:
    Python: 3.8.9 - /opt/local/bin/python
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0.1
    Safari: 14.1
  npmPackages:
    gatsby: ^3.4.1 => 3.4.1 
    gatsby-plugin-gatsby-cloud: ^2.4.1 => 2.4.1 
    gatsby-plugin-image: ^1.4.0 => 1.4.0 
    gatsby-plugin-manifest: ^3.4.0 => 3.4.0 
    gatsby-plugin-offline: ^4.4.0 => 4.4.0 
    gatsby-plugin-react-helmet: ^4.4.0 => 4.4.0 
    gatsby-plugin-sharp: ^3.4.1 => 3.4.1 
    gatsby-source-filesystem: ^3.4.0 => 3.4.0 
    gatsby-transformer-sharp: ^3.4.0 => 3.4.0 
  npmGlobalPackages:
    gatsby-cli: 3.5.0
```

**Comment by vladar** [comment]
I observe this behavior too but not sure if this is a bug in Gatsby. If you remove this line in your repro the issue goes away:

https://github.com/jgosmann/gatsby-plugin-image-translateZ/blob/3ebcd23cacf7c2c134c05aa60da5046765940341/src/pages/index.js#L21

So one workaround is to wrap the image with another element for the border (suboptimal for sure).

Also the issue goes away if I replace it with:

```diff
- style={{ border: "1px solid black" }}
+ imgStyle={{ border: "1px solid black" }}
```

Feel free to open a PR to remove `translateZ`. I think we should be safe as we also have `will-change: opacity` on the same element which should do the same trick in modern browsers.
