### ISSUE TITLE
Dependabot alerts

### ISSUE THREAD

**Issue by pelikhan** [gatsbyjs/gatsby#31486]
A few direct/indirect dependencies of gatsbyjs generated dependabot alerts downstream. Would be it possible to enable dependabot in gatsbyjs?

For example, this alert is generated by dependabot.

```
gatsby@3.5.1 requires trim@0.0.1 via a transitive dependency on remark-parse@6.0.3
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

Sadly most of the alerts are irrelevant to Gatsby and activating dependabot would create unnecessary noise and distraction for us. We have the renovate bot to update our dependencies (dependabot would be duplicate).
