### ISSUE TITLE
default WordPress starter fails when running gatsby develop

### ISSUE THREAD

**Issue by rickgregory** [gatsbyjs/gatsby#31513]
## Description

running 'gatsby develop' on a brand new  install of the default  WordPress starter fails
### Steps to reproduce
1) install gatsby cli (this was tested with 3.5.0)
2) Issue `gatsby new my-wordpress-gatsby-site https://github.com/gatsbyjs/gatsby-starter-wordpress-blog` to install the starter from the gatsby-source-WordPress repo docs (https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/getting-started.md)
3) enter the newly created my-wordpress-gatsby-site directory and issue `gatsby develop` 

Right after it runs the page queries this error occurs:

```
 ERROR #98124  WEBPACK

Generating development SSR bundle failed

Can't resolve 'mitt' in '/Users/rick/gatsbyprojects/my-wordpress-gatsby-site/.cache'

If you're trying to use a package make sure that 'mitt' is installed. If you're trying to use a local file make sure that the path is
correct.
```
running npm update fails and produces this error log:
[errorlog.txt](https://github.com/gatsbyjs/gatsby/files/6519107/errorlog.txt)

### Expected result

gatsby develop runs as expected on the default starter. 

### Actual result

It doesn't...

### More info
Also this is not related the the yarn issue in https://github.com/gatsbyjs/gatsby/issues/30114 as yarn actually isn't installed here. 

Note that the starter wasn't edited in any way. Changing the GraphQL endpoint to another one made no difference. Running gatsby clean did nothing either. 

### Environment

  System:
    OS: macOS 11.3.1
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    npm: 7.13.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0.1
    Safari: 14.1
  npmPackages:
    gatsby: ^3.3.0 => 3.3.0 
    gatsby-image: ^3.3.0 => 3.3.0 
    gatsby-plugin-manifest: ^3.3.0 => 3.3.0 
    gatsby-plugin-offline: ^4.3.0 => 4.3.0 
    gatsby-plugin-react-helmet: ^4.3.0 => 4.3.0 
    gatsby-plugin-sharp: ^3.3.0 => 3.3.0 
    gatsby-source-filesystem: ^3.3.0 => 3.3.0 
    gatsby-source-wordpress: ^5.3.0 => 5.3.0 
    gatsby-transformer-sharp: ^3.3.0 => 3.3.0 
  npmGlobalPackages:
    gatsby-cli: 3.5.0

**Comment by rickgregory** [comment]
OK, never mind. Actually installing yarn fixed this. This could be considered a documentation bug since the linked repo docs don't actually mention that you need yarn installed. Basically if you follow the directions, you get the error above.

**Comment by kzsa** [comment]
npm i mitt

**Comment by PublicDomainHub** [comment]
> npm i mitt

Ty..  Hours of searching and head-scratching for a noob like me resolved 👯‍♂️
