### ISSUE TITLE
Autogenerated sitemap file is not in the exact filename sitemap.xml

### ISSUE THREAD

**Issue by sriramgroot** [gatsbyjs/gatsby#31515]
## Description

When i try to add sitemap to my website through the below mentioned plugin it is just creating a file named `sitemap-0.xml` and `sitemap-index.xml`

**Plugin Link:** [https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap](https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap)

### Steps to reproduce

- Run the command `npm install gatsby-plugin-sitemap` in the root of your project were we have the `package.json` is located
- Follow the instruction provide in the plugin
[https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap](https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap)

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

Basically `sitemap.xml` file should be created in the root of public folder

### Actual result

Bug `sitemap-0.xml` and `sitemap-index.xml` files are created in the root of public folder

### Environment

```
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0.1
    Safari: 14.0.1
  npmPackages:
    gatsby: ^3.1.2 => 3.2.1
    gatsby-image: ^3.1.0 => 3.2.0
    gatsby-plugin-breadcrumb: ^12.1.1 => 12.1.1
    gatsby-plugin-fontawesome-css: ^1.1.0 => 1.1.0
    gatsby-plugin-google-gtag: ^3.4.0 => 3.4.0
    gatsby-plugin-google-tagmanager: ^3.4.0 => 3.4.0
    gatsby-plugin-image: ^1.1.2 => 1.2.0
    gatsby-plugin-manifest: 3.5.0 => 3.5.0
    gatsby-plugin-react-helmet: ^4.4.0 => 4.4.0
    gatsby-plugin-robots-txt: 1.5.6 => 1.5.6
    gatsby-plugin-sharp: ^3.1.2 => 3.2.0
    gatsby-plugin-sitemap: 4.0.0 => 4.0.0
    gatsby-source-filesystem: ^3.1.0 => 3.2.0
    gatsby-source-strapi: 0.0.12 => 0.0.12
    gatsby-transformer-inline-svg: ^0.1.0 => 0.1.0
    gatsby-transformer-remark: ^3.1.0 => 3.2.0
    gatsby-transformer-sharp: ^3.1.0 => 3.2.0
```

My `gatsby-config.js` have the configuration as mentioned below
```
module.exports = {
    /* Your site config here */
    siteMetadata: {
      siteUrl: `https://www.example.com`
    },
    plugins: [
      {
        resolve: `gatsby-plugin-sitemap`,
        options: {
          output: `/`,
          entryLimit: 45000
        }
      }
    ]
  };
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

This is working as expected, the underlying library (https://github.com/ekalinin/sitemap.js) is creating them like that. And it's perfectly fine, you can tell Google to look at the index file and it'll work.

**Comment by sambunting** [comment]
Somewhat of a workaround - I've added a bit of code to `gatsb-node.js` to rename the file.

```js
const fs = require('fs');

exports.onPostBuild = () => {
  if (fs.existsSync('./public/sitemap-index.xml')) {
    fs.renameSync('./public/sitemap-index.xml', './public/sitemap.xml');
  }
};
```

Also important to note that I've change the output to just be `.` in `gatsby-config`

```js
{
  resolve: 'gatsby-plugin-sitemap',
  options: {
    output: '.',
  },
},
```

**Comment by rwieruch** [comment]
Phew, updating from Gatsby 2 to 4 and this plugin's breaking changes consumed 4/5 of the time ... Thanks for your solution @sambunting I did something similar in my package.json file:

```
"postbuild": "mv public/sitemap/sitemap-0.xml public/sitemap.xml",
```
