### ISSUE TITLE
gatsby-cli fails to init if `rootPath` is set to pwd

### ISSUE THREAD

**Issue by yeskunall** [gatsbyjs/gatsby#3151]
Here's a screenshot illustrating my issue:

<img width="654" alt="screen shot 2017-12-06 at 8 29 48 pm" src="https://user-images.githubusercontent.com/14703164/33694108-45c1c55a-dac4-11e7-81c3-9dc9d3e433f5.png">

I don't know if this is intended or not, but I would love to see an option to run this command from within the folder AKA the pwd. My use-case is when I already have a dedicated folder where I want to introduce the boilerplate by running `gatsby-cli new`.

My `gatsby` version is 1.1.25. My `node` version is 8.9.1. I'm running macOS Sierra v10.12.6.

If this issue has been brought to your attention previously, feel free to close by referencing the issue. Thanks a lot. 💖

**Comment by jquense** [comment]
Hey there. What you are seeing is generally a limitation of git clone, which will refuse to bulldoze files in an existing directory when cloning from a remote repo. There is probably a git flag to force it but I think not destroying files already in the directory is good default

**Comment by yeskunall** [comment]
Thanks for the quick response!

I fully understand that deleting existing files and folders in the directory is not the best option; however, I decided to bring this up because I decided to make the switch from create-react-app to gatsby, and I'm certain that the former allows you to specify the pwd as an argument. In fact, if there are existing files it needs to overwrite, I think it chooses to skip them and instead just warns the user.

However, if it's a limitation of git rather than the CLI in itself, then I guess it can't be helped. 🤷‍♂️

**Comment by yeskunall** [comment]
@calcsam please don't close issues before they get an apt response from the maintainers. All I received was an explanation as to _why_ this might be happening. 😓

If this can't/won't be fixed, then please close __after__ giving a reason.

**Comment by pieh** [comment]
per https://stackoverflow.com/questions/2411031/how-do-i-clone-into-a-non-empty-directory
there are 2 options listed there that could solve that:

- cloning to tmp directory and moving files to main directory later or
- initing empty git repo, adding remote to starter and pulling files then (to keep files in current directory from being overwritten propably would have to add files that already exist  to index, stash them and stash pop them after pulling starter)

**Comment by KyleAMathews** [comment]
@jquense and @calcsam are both maintainers :-) @pieh should be too so I'll add him

In any case, to repeat @jquense, we're not going to support trying to create directories in an existing directory as that's not safe or predictable.

**Comment by yeskunall** [comment]
> we're not going to support trying to create directories in an existing directory as that's not safe or predictable.

That's what I was looking for. Thanks, you guys.
