### ISSUE TITLE
Automate the process of upgrading deps for gatsby starters

### ISSUE THREAD

**Issue by yeskunall** [gatsbyjs/gatsby#3152]
As suggested by Kyle in https://github.com/gatsbyjs/gatsby/issues/2960#issuecomment-349853084, I think we'll be better off if we could automatically update the deps for all the gatsby starters to latest stable. That way we could avoid issues like https://github.com/gatsbyjs/gatsby/issues/2960#issuecomment-349851674 that stem from the lack of said automated process.

Thoughts?

/cc @KyleAMathews

**Comment by calcsam** [comment]
The ideal scenario is to pin a blessed set of starters to `latest`, and automatically build them on PRs, tied into visual regression diffing to detect changes. We're working on this but it's a bit complicated.

**Comment by calpa** [comment]
At least knowing there is the new version is released in the command line, for example:
`Gatsbyjs's new version is released!: v1.9.128`

More information for the command line tools can be find inside the [gatsby-cli](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-cli).

**Comment by yeskunall** [comment]
@calpa I think that is a separate issue of its own 😆 but yeah, with [`update-notifier`](https://github.com/yeoman/update-notifier), it shouldn't be a hard task.

**Comment by calpa** [comment]
@yeskunall [`update-notifier`](https://github.com/yeoman/update-notifier) seems awesome, and we don't need to reinvent the wheel 😄

**Comment by KyleAMathews** [comment]
@calpa @yeskunall either of you want to add update-notifier to gatsby-cli? That'd be a great addition!

**Comment by yeskunall** [comment]
@KyleAMathews on it 👍🏽

**Comment by kakadiadarpan** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub issues, we have to clean some of the old issues as many of them have already been resolved with the latest updates.

Please make sure to update to the latest Gatsby version and check if that solves the issue. Let us know if that works for you by adding a comment 👍

**Comment by kakadiadarpan** [comment]
This issue is being closed because there hasn't been any activity for at least 30 days. Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem 👍
