### ISSUE TITLE
fast-refresh-overlay: infinite loop

### ISSUE THREAD

**Issue by pindjur** [gatsbyjs/gatsby#31553]
Throwing error inside render will cause infinite loop when offline.

Reproduction:
1. clone https://github.com/pindjur/gatsbyFastRefreshBug
2. run gastby develop
3. load home page 
4. go  offline
5. click button to set and throw error

Expected result:
network error shown in overlay ui. I guess

Actual result: 
infinite loop

It started in uncought fetch error here:
https://github.com/gatsbyjs/gatsby/blob/54d4721462b9303fed723fdcb15ac5d72e103778/packages/gatsby/cache-dir/fast-refresh-overlay/components/hooks.js#L22-L35
If you swallow fetch error, issue is gone but so is the stack trace from the overlay ui.

**Comment by LekoArts** [comment]
Wrapping it in a `try ... catch` with a graceful `decoded` message should be fine.

**Comment by meenal06** [comment]
Hi @LekoArts , I have made a PR please do take a look!
