### ISSUE TITLE
gatsby-plugin-mdx randomly inserts non breaking spaces

### ISSUE THREAD

**Issue by joeplaa** [gatsbyjs/gatsby#31559]
## Description

Some lines (text) are not properly broken up on when using MDX. This is especially annoying on mobile, where the lines will run out of the screen. When looking into the generated html, these lines have `&nbsp;` instead of regular spaces. I can't find anything odd or specific in our markdown that could trigger this.

### Steps to reproduce

1. Clone demo: [https://github.com/joeplaa/gatsby-mdx-repro-31559](https://github.com/joeplaa/gatsby-mdx-repro-31559)
2. Install and run develop
3. Browse to article "Hoeveel btw zit er op iZettle diensten?" (top of page)
4. Search for "Je zou misschien denken"
5. Open devtools in Chrome (or equivalent in other browser) and view element with text from search above. It shows it is rendered as: `Je zou misschien denken&nbsp;dat&nbsp;je&nbsp;deze&nbsp;uitgaven&nbsp;dan helemaal niet&nbsp;in&nbsp;`

![image](https://user-images.githubusercontent.com/58688994/119461004-8eb8d800-bd3f-11eb-9b94-4e66bb8f65ee.png)

### Expected result

MDX/markdown/Gatsby should not insert non breaking spaces. Instead it should only insert normal spaces.

### Actual result

Multiple lines contain non breaking spaces without explicitly having typed them.

### Environment

```shell
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Xeon(R) CPU E3-1245 v3 @ 3.40GHz
  Binaries:
    Node: 12.21.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - /c/Users/Joepje/.windows-build-tools/python27/python
  Browsers:
    Edge: Spartan (44.19041.964.0), Chromium (90.0.818.66)
  npmPackages:
    gatsby: ^3.4.1 => 3.4.1 
    gatsby-plugin-mdx: ^2.5.1 => 2.5.1 
    gatsby-source-filesystem: ^3.5.0 => 3.5.0 
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it. It must be on Gatsby v3 and the latest version of `gatsby-plugin-mdx`. Please also remove any other plugins until you see the issue.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by joeplaa** [comment]
@LekoArts 

Sure. I updated the link in original description (and environment info) to a minimal demo with `gatsby` v3 and `gatsby-plugin-mdx` v2.5.1. Let me know if that is indeed what you're looking for.

**Comment by joeplaa** [comment]
This is still an issue. Don't close.

**Comment by joeplaa** [comment]
Still waiting for a reply.

**Comment by joeplaa** [comment]
Keep open please.

**Comment by umbiermann** [comment]
I just had the a similar problem, and noticed that content pasted to a CMS from Microsoft Word contained non breaking spaces, which look exactly the same as normal spaces, but get converted differently. They are visible through small dots when marking them in VSCode:
![image](https://user-images.githubusercontent.com/70113318/128349741-34e3888e-634a-4f6f-a081-a2c32664f6c5.png)

**Comment by joeplaa** [comment]
Thanks @umbiermann, that solved my problem too!!! We initially copied all our existing posts from WordPress to Gatsby and some of those posts were indeed originally written in Microsoft Word, which explains where those non-breaking spaces come from. Apparently WordPress is less strict when it comes to displaying them.

@LekoArts, I'll close this issue as my problem is solved and this is not, strictly speaking, a Gatsby issue.
