### ISSUE TITLE
[gatsby-source-contentful] Unknown argument "tracedSVGOptions" on field "ContentfulAsset.gatsbyImageData".

### ISSUE THREAD

**Issue by prichey** [gatsbyjs/gatsby#31557]
## Description

I'd like to pass in a configuration object for `tracedSVGOptions` (per [Gatsby reference](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-plugin-image/#customizing-the-default-options), [example](https://github.com/gatsbyjs/gatsby/blob/e351588365c32ebf84c06048ba3b2da16e12793c/examples/using-gatsby-image/src/pages/traced-svg.js#L53)) but I get the following GraphQL error: `Unknown argument "tracedSVGOptions" on field "ContentfulAsset.gatsbyImageData".`.

### Steps to reproduce

In the query:

```
exampleQuery {
  image {
    gatsbyImageData(
      placeholder: TRACED_SVG
      tracedSVGOptions: { background: "#ffffff", color: "#663399" }
    )
  }
}
```

Yields the error: `Unknown argument "tracedSVGOptions" on field "ContentfulAsset.gatsbyImageData".`

### Expected result

The query should not throw, and a traced SVG with the given background / color should be rendered.

### Actual result

The above error is thrown.

### Environment

```
 System:
    OS: macOS 11.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /var/folders/gb/n4714k6158z5svmlr6y_yrfh0000gn/T/fnm_multishell_5036
2_1621521683727/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - /var/folders/gb/n4714k6158z5svmlr6y_yrfh0000gn/T/fnm_multishell_50362
_1621521683727/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  npmPackages:
    gatsby: ^3.5.0 => 3.5.0
    gatsby-awesome-pagination: ^0.3.8 => 0.3.8
    gatsby-core-utils: ^2.5.0 => 2.5.0
    gatsby-plugin-algolia: ^0.20.0 => 0.20.0
    gatsby-plugin-force-trailing-slashes: ^1.0.5 => 1.0.5
    gatsby-plugin-google-tagmanager: ^3.5.0 => 3.5.0
    gatsby-plugin-image: ^1.5.0 => 1.5.0
    gatsby-plugin-less: ^5.5.0 => 5.5.0
    gatsby-plugin-manifest: ^3.5.0 => 3.5.0
    gatsby-plugin-mdx: ^2.5.0 => 2.5.0
    gatsby-plugin-meta-redirect: ^1.1.1 => 1.1.1
    gatsby-plugin-netlify: ^3.5.0 => 3.5.0
    gatsby-plugin-offline: ^4.5.0 => 4.5.0
    gatsby-plugin-react-helmet: ^4.5.0 => 4.5.0
    gatsby-plugin-react-svg: ^3.0.1 => 3.0.1
    gatsby-plugin-robots-txt: ^1.6.2 => 1.6.2
    gatsby-plugin-root-import: ^2.0.6 => 2.0.6
    gatsby-plugin-sharp: ^3.5.0 => 3.5.0
    gatsby-plugin-sitemap: ^4.1.0 => 4.1.0
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.21 => 1.1.22
    gatsby-remark-copy-linked-files: ^4.2.0 => 4.2.0
    gatsby-source-contentful: ^5.5.0 => 5.5.0
    gatsby-source-filesystem: ^3.5.0 => 3.5.0
    gatsby-source-git: ^1.1.0 => 1.1.0
    gatsby-source-github-api: ^1.0.0 => 1.0.0
    gatsby-transformer-sharp: ^3.5.0 => 3.5.0
  npmGlobalPackages:
    gatsby: 3.5.1
```

**Comment by prichey** [comment]
Looking into this a bit more, it seems like `ContentfulAsset.gatsbyImageData` should conform to `ImageSharp.gatsbyImageData` (type extension [here](https://github.com/gatsbyjs/gatsby/blob/151d269bdd7182c64d40b0e7e70c0596f877ce7d/packages/gatsby-transformer-sharp/src/customize-schema.js#L403)). Is there any reason why this isn't possible? I understand not all `ContentfulAssets` are images, so maybe it makes sense to expose the underlying `childImageSharp`? I'm curious to hear what the thinking is here, or if there's a workaround here I'm unaware of. Thanks!

**Comment by prichey** [comment]
After looking into this even more, it looks like I need to set `downloadLocal: true` to be able to get at the underlying `localFile` in order to enable full Sharp transformations. If that's the case, this might just be a documentation problem since I don't see any reference to the fact that you're currently limited in the sharp transformations in the `gatsbyImageData` query without the `downloadLocal` route. I'm curious to hear others' thoughts though!

**Comment by prichey** [comment]
This is not stale! Maybe if maintainers don't have the bandwidth to look into issues we should extend the timeout for the stalebot?

**Comment by prichey** [comment]
Yeah, I give up

**Comment by lukethacoder** [comment]
Ran into a similar issue today with hygraph (GraphCMS). I thinking I'll build my own `getImage` method to fit my needs instead of relying on the one provided.
