### ISSUE TITLE
Downloaded images from wordpress are not working 

### ISSUE THREAD

**Issue by mtuchi** [gatsbyjs/gatsby#31560]
## Description

I mages are not loaded am getting `"childImageSharp": null`

### Steps to reproduce

Run the container once it's done try to run this in _`localhost:8000/__graphql`_
```
query MyQuery {
  allWpPost {
    nodes {
      featuredImage {
        node {
          localFile {
            childImageSharp {
              gatsbyImageData
            }
          }
        }
      }
    }
  }
}

```
[https://codesandbox.io/s/elated-shtern-7fxzk](https://codesandbox.io/s/elated-shtern-7fxzk)

### Expected result

All downloaded images should appear 

### Actual result

```
 {
    "featuredImage": {
            "node": {
              "localFile": {
                "childImageSharp": null
              }
            }
          }
        },
        {
          "featuredImage": {
            "node": {
              "localFile": {
                "childImageSharp": null
              }
            }
          }
        },
        {
          "featuredImage": {
            "node": {
              "localFile": {
                "childImageSharp": null
              }
            }
          }
        },
        {
          "featuredImage": {
            "node": {
              "localFile": {
                "childImageSharp": null
            }
         }
       }
   },
```

### Environment

  System:
    OS: macOS 11.3.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0.1
    Safari: 14.1
  npmPackages:
    gatsby: ^3.3.0 => 3.5.1 
    gatsby-image: ^3.3.0 => 3.5.0 
    gatsby-plugin-algolia: ^0.19.0 => 0.19.0 
    gatsby-plugin-feed: ^3.4.0 => 3.5.0 
    gatsby-plugin-google-tagmanager: ^3.4.0 => 3.5.0 
    gatsby-plugin-image: ^1.4.1 => 1.5.0 
    gatsby-plugin-mailchimp: ^5.2.2 => 5.2.2 
    gatsby-plugin-manifest: ^3.3.0 => 3.5.0 
    gatsby-plugin-nprogress: ^3.4.0 => 3.5.0 
    gatsby-plugin-offline: ^4.3.0 => 4.5.1 
    gatsby-plugin-preload-fonts: ^2.4.0 => 2.5.0 
    gatsby-plugin-react-helmet: ^4.3.0 => 4.5.0 
    gatsby-plugin-sharp: ^3.3.0 => 3.5.0 
    gatsby-plugin-sitemap: ^4.0.0 => 4.1.0 
    gatsby-source-filesystem: ^3.3.0 => 3.5.0 
    gatsby-source-wordpress: 4.0.0 => 4.0.0 
    gatsby-transformer-sharp: ^3.3.0 => 3.5.0 

Run `gatsby info --clipboard` in your project directory and paste the output here. Also name any `flags` you use inside `gatsby-config.js`.

**Comment by mtuchi** [comment]
My issue is related to this 
https://github.com/gatsbyjs/gatsby/issues/31529

**Comment by LekoArts** [comment]
Please comment on one of the two issues (the one that is more relevant). Thanks!
Otherwise we'll have a duplicate.
