### ISSUE TITLE
[gatsby-plugin-gatsby-cloud] Opt-in for preview indicator

### ISSUE THREAD

**Issue by kelvindecosta** [gatsbyjs/gatsby#31597]
## Description

With `gatsby-plugin-gatsby-cloud@2.6.0`, a new [preview indicator](https://www.gatsbyjs.com/docs/reference/release-notes/v3.6/#preview-status-indicator) feature was added.
While this feature is a nice quality-of-life update, it increases the bundle size and provides no opt-out mechanism.

## Behavior

This section outlines the use of the `gatsby-plugin-gatsby-cloud` plugin with versions `2.5.0` and `2.6.0`.

### `v2.5.0` 

![Screenshot_20210526_210548](https://user-images.githubusercontent.com/38982451/119709960-7e4f4d00-be66-11eb-8df3-0557ff276197.png)

*Parsed size* : **335.55 KB** 
*Gzipped size* : **108.73 KB** 

### `v2.6.0` 

![Screenshot_20210526_210510](https://user-images.githubusercontent.com/38982451/119710365-ef8f0000-be66-11eb-8709-2bd1f718049b.png)

*Parsed size* : **427.52 KB** 
*Gzipped size* : **129.48 KB** 

## Conclusions

As per my understanding, the `date-fns` package should take most of the blame.
A method exported by this package is being used in the preview indicator.

While this is just about **20 KB** of added code, I think it serves no benefit to the end-user of the website.

I might be wrong about this and would appreciate any feedback!
Thank you for your time.

### Environment

<details>
<summary>Local information</summary>

```
  System:
    OS: Linux 5.4 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.4/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Languages:
    Python: 3.9.3 - /usr/bin/python
  Browsers:
    Firefox: 88.0
  npmPackages:
    gatsby: ^3.6.0 => 3.6.0 
    gatsby-plugin-gatsby-cloud: 2.6.0 => 2.6.0 
    gatsby-plugin-image: ^1.6.0 => 1.6.0 
    gatsby-plugin-layout: ^2.6.0 => 2.6.0 
    gatsby-plugin-loadable-components-ssr: ^2.1.0 => 2.1.0 
    gatsby-plugin-manifest: ^3.6.0 => 3.6.0 
    gatsby-plugin-mdx: ^2.6.0 => 2.6.0 
    gatsby-plugin-minify: ^0.4.0 => 0.4.0 
    gatsby-plugin-no-sourcemaps: ^3.6.0 => 3.6.0 
    gatsby-plugin-nprogress: ^3.6.0 => 3.6.0 
    gatsby-plugin-offline: ^4.6.0 => 4.6.0 
    gatsby-plugin-postcss: ^4.6.0 => 4.6.0 
    gatsby-plugin-preact: ^5.6.0 => 5.6.0 
    gatsby-plugin-react-helmet: ^4.6.0 => 4.6.0 
    gatsby-plugin-remove-generator: ^1.1.0 => 1.1.0 
    gatsby-plugin-remove-trailing-slashes: ^3.6.0 => 3.6.0 
    gatsby-plugin-robots-txt: ^1.6.2 => 1.6.2 
    gatsby-plugin-sharp: ^3.6.0 => 3.6.0 
    gatsby-plugin-sitemap: ^4.2.0 => 4.2.0 
    gatsby-plugin-styled-components: ^4.6.0 => 4.6.0 
    gatsby-plugin-use-dark-mode: ^1.3.0 => 1.3.0 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.22 => 1.1.22 
    gatsby-remark-vscode: ^3.2.1 => 3.2.1 
    gatsby-source-filesystem: ^3.6.0 => 3.6.0 
    gatsby-transformer-sharp: ^3.6.0 => 3.6.0 
  npmGlobalPackages:
    gatsby-cli: 2.19.1
```

</details>

Flags:

- `DEV_SSR`
- `FAST_DEV`

**Comment by wardpeet** [comment]
Thanks for reporting, I thought I fixed it in a previous PR but I forgot to add sideEffects to the PR.
