### ISSUE TITLE
Vulnerability due to trim version 0.0.1

### ISSUE THREAD

**Issue by ko1imai** [gatsbyjs/gatsby#31603]
## Description

I witnessed vulnerability waring during installation of Gatsby, the latest version 3.6.0.

### Steps to reproduce

It will be confirmed by invoking npm install gatsby .

### Expected result

No high vulnerabilities were expected.

### Actual result

12 vulnerabilities (7 moderate, 5 high) were reported.
As I investigated, I found those high vulnerabilities are due to trim 0.0.1 as following dependencies.

gatsby 3.6.0
gatsby-cli 3.6.0
gatsby-recipes 0.17.0
remark-parse 6.0.3
trim 0.0.1

updating remark-parse to 9.0.0 did not resolve the issue due to dependency.

### Environment

  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.3 - ~/.nodenv/versions/14.15.3/bin/node
    Yarn: 1.22.10 - ~/.nodenv/versions/14.15.3/bin/yarn
    npm: 7.13.0 - ~/.nodenv/versions/14.15.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.212
    Safari: 14.1.1
  npmPackages:
    gatsby: ^3.6.0 => 3.6.0
  npmGlobalPackages:
    gatsby-cli: 3.6.0

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

Similar to https://github.com/gatsbyjs/gatsby/issues/31266#issuecomment-833319227 I want to re-iterate here that those messages won't affect your finished site as nothing of that is run on the client, only during development. You can ignore those as they are not relevant to Gatsby.

**Comment by ko1imai** [comment]
Thank you so much for your swift action.

Br, ko1

iPadから送信
