### ISSUE TITLE
[gatsby-starter-blog] Classes in CSS modules are not correctly applied to MDX files

### ISSUE THREAD

**Issue by leemorrowdev** [gatsbyjs/gatsby#31616]
## Description

When using CSS modules with MDX files in the Gatsby Starter Blog, if there is some identical class selector in multiple CSS modules, the styles of only one class selector will be applied to all MDX files instead of each CSS module's class selector's styles being applied to its corresponding MDX file. 

### Steps to reproduce

1. Create a new Gatsby site using the Gatsby blog starter: `gatsby new my-blog-starter https://github.com/gatsbyjs/gatsby-starter-blog`
2. Change the my-second-post example post into a directory structure like the hello world example post
3. Create a CSS module file in each directory
4. Create an identical class selector in each CSS module but give each selector different styles
5. Import and apply the class selector in each mdx file

Minimal Reproduction: <https://github.com/leemorrowdev/gatsby-starter-blog-reproduction>

### Expected result

The styles applied to each mdx file should match its corresponding CSS module.

### Actual result

The styles applied to each mdx file are identical. When inspected, all blog posts have the same class.

### Environment

System:
  OS: Linux 4.19 Ubuntu 20.04.2 LTS (Focal Fossa)
  CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  Shell: 5.0.17 - /bin/bash
Binaries:
  Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
  npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
npmPackages:
  gatsby: ^3.4.1 => 3.4.1
  gatsby-theme-blog: ^3.0.0 => 3.0.0

**Comment by CesarSant2000** [comment]
Maybe what was happening was that **resolve -> alias** in Webpack wasn't working as expected for CSS and it was failing on importing the shared files (like typography).
You can refer to this: https://github.com/storybookjs/storybook/issues/10238
