### ISSUE TITLE
ACF Image field returns null when queried from Gatsby

### ISSUE THREAD

**Issue by bourneidBH** [gatsbyjs/gatsby#31614]
## Description

Querying an ACF Image field from the WordPress GraphiQL IDE gives the expect results based on WordPress ACF image data. Querying the same field from Gatsby returns null. The Gatsby query is dropping all query request steps below the ACF field group name. Same issue described in #20439 but I am using the latest version of gatsby-source-wordpress & WPGraphQL for Advanced Custom Fields instead of the REST API version referenced in that issue.
Compare query results from WordPress 
![ACF-image-query_WP-GraphiQL-IDE](https://user-images.githubusercontent.com/74982939/119867496-90bb9c00-bee3-11eb-9670-32c777deeb30.JPG)
to query results from Gatsby
![ACF-image-query_Gatsby-GraphiQL](https://user-images.githubusercontent.com/74982939/119867604-adf06a80-bee3-11eb-8d02-99f801518dd9.JPG)

### Steps to reproduce

1. Set up a WordPress site with these plugins: WP Gatsby, WP GraphQL, Advanced Custom Fields, WPGraphQL for Advanced Custom Fields.
2. Set up an ACF field type Image with Show in GraphQL set to YES
3. Add image to new ACF field.
4. Set up a Gatsby site with gatsby-source-wordpress & connect it to the wordpress site. Installation guide: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/getting-started.md
5. Run gatsby develop & then query the ACF image field at http://localhost:8000/___graphql

Reproduction can be found at https://github.com/bourneidBH/gatsby3test

### Expected result

If ACF image field has an image applied querying the field with this pattern should return the sourceUrl of the uploaded image.

```graphql
export const query = graphql`
  {
    postType {
      acfFieldGroup {
        acfImageField {
          sourceUrl
        }
      }
    }
  }
`
```

### Actual result

Query pattern above returns result below. Note acfImageField & sourceUrl are missing from the results:

```
{
  "data": {
    "postType": {
      "acfFieldGroup": null
    }
  },
  "extensions": {}
}
```

### Environment

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  Binaries:
    Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.964.0), Chromium (90.0.818.66)
  npmPackages:
    gatsby: ^3.4.0 => 3.4.0 
    gatsby-awesome-pagination: ^0.3.8 => 0.3.8 
    gatsby-plugin-gatsby-cloud: ^2.4.1 => 2.4.1 
    gatsby-plugin-image: ^1.4.0 => 1.4.0 
    gatsby-plugin-manifest: ^3.4.0 => 3.4.0 
    gatsby-plugin-react-helmet: ^4.4.0 => 4.4.0 
    gatsby-plugin-sass: ^4.4.0 => 4.4.0 
    gatsby-plugin-sharp: ^3.4.0 => 3.4.0 
    gatsby-plugin-sitemap: ^4.0.0 => 4.0.0 
    gatsby-source-filesystem: ^3.4.0 => 3.4.0 
    gatsby-source-wordpress: ^5.4.0 => 5.4.0 
    gatsby-transformer-sharp: ^3.4.0 => 3.4.0 

Contents of package.json:

```json
{
  "name": "woo-gatsby-test-site",
  "version": "1.0.0",
  "private": true,
  "description": "Woo Gatsby Test Site",
  "author": "bourneidBH",
  "keywords": [
    "gatsby"
  ],
  "scripts": {
    "develop": "gatsby develop",
    "start": "gatsby develop",
    "build": "gatsby build",
    "serve": "gatsby serve",
    "clean": "gatsby clean"
  },
  "dependencies": {
    "fslightbox-react": "^1.6.2",
    "gatsby": "^3.4.0",
    "gatsby-awesome-pagination": "^0.3.8",
    "gatsby-plugin-gatsby-cloud": "^2.4.1",
    "gatsby-plugin-image": "^1.4.0",
    "gatsby-plugin-manifest": "^3.4.0",
    "gatsby-plugin-react-helmet": "^4.4.0",
    "gatsby-plugin-sass": "^4.4.0",
    "gatsby-plugin-sharp": "^3.4.0",
    "gatsby-plugin-sitemap": "^4.0.0",
    "gatsby-source-filesystem": "^3.4.0",
    "gatsby-source-wordpress": "^5.4.0",
    "gatsby-transformer-sharp": "^3.4.0",
    "path": "^0.12.7",
    "prop-types": "^15.7.2",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-helmet": "^6.1.0",
    "react-icons": "^4.2.0",
    "sass": "^1.32.12"
  }
}
```

Contents of gatsby-config.js:

```js
module.exports = {
  siteMetadata: {
    title: "Woo Gatsby Test Site",
  },
  plugins: [
    {
      resolve: "gatsby-source-wordpress",
      options: {
        url: "http://gatsby3test.local/graphql",
        schema: {
          perPage: 10,
          requestConcurrency: 2, 
          previewRequestConcurrency: 1, 
        },
        develop: {
          hardCacheMediaFiles: true,
          hardCacheData: true,
        },
        type: {
          MediaItem: {
            lazyNodes: true,
            localFile: {
              requestConcurrency: 2,
            },
          },
          Coupon: {
            exclude: true
          },
          Customer: {
            exclude: true
          },
          Order: {
            exclude: true
          },
          PaymentGateway: {
            exclude: true
          },
          PostFormat: {
            exclude: true
          },
          ShippingClass: {
            exclude: true
          },
          Refund: {
            exclude: true
          },
          TaxRate: {
            exclude: true
          },
          UserRole: {
            exclude: true
          },
        },
        excludeFieldNames: [
          `averageRating`, 
          `catalogVisibility`, 
          `dateOnSaleFrom`, 
          `dateOnSaleTo`, 
          `nodeType`, 
          `onSale`, 
          `purchasable`, 
          `purchaseNote`,
          `reviews`,
          `reviewCount`,
          `reviewsAllowed`,
          `totalSales`,
          `commentCount`,
          `commentStatus`,
          `comments`,
          `desiredSlug`,
          `enclosure`,
          `isRevision`,
          `isSticky`,
          `pingStatus`,
          `pinged`,
          `toPing`,
        ],
      },
    },
    "gatsby-plugin-sass",
    "gatsby-plugin-gatsby-cloud",
    "gatsby-plugin-image",
    "gatsby-plugin-react-helmet",
    "gatsby-plugin-sitemap",
    {
      resolve: "gatsby-plugin-manifest",
      options: {
        icon: "src/images/icon.png",
      },
    },
    "gatsby-plugin-sharp",
    "gatsby-transformer-sharp",
    {
      resolve: "gatsby-source-filesystem",
      options: {
        name: "images",
        path: "./src/images/",
      },
      __key: "images",
    },
  ],
};
```

**Comment by igorbumba** [comment]
Same thing is happening to me: https://github.com/gatsbyjs/gatsby/issues/31503

**Comment by TylerBarnes** [comment]
Please try `gatsby-source-wordpress@5.10.0-alpha-wordpress.19+3d743f8f07` as I believe it solves this issue.

**Comment by kdotamoh** [comment]
Hey @TylerBarnes, I've run into this issue after upgrading all my packages and Wordpress plugins. I'd be happy to provide a reproduction if needed?
