### ISSUE TITLE
Include TSLint in gatsby-plugin-typescript

### ISSUE THREAD

**Issue by kriim** [gatsbyjs/gatsby#3162]
I'd love to see a default configuration for TSLint in `gatsby-plugin-typescript` that is picked up automatically by IDEs like VS Code.

Currently I'm seeing errors like the following in VS Codes console output. I used `gatsby-starter-typescript` without notable modifications.

```
Failed to load the TSLint library for the document c:\_dev\ws\gatsby-app\node_modules\gatsby-link\index.d.ts

To use TSLint in this workspace please install tslint using 'npm install tslint' or globally using 'npm install -g tslint'.
TSLint has a peer dependency on `typescript`, make sure that `typescript` is installed as well.
You need to reopen the workspace after installing tslint.
```

I could imagine a similiar config as in [wmonk/create-react-app-typescript](https://github.com/wmonk/create-react-app-typescript) (a TypeScript flavour of `create-react-app`).

In `dependencies` of `package.json`
```
    "tslint": "^5.2.0",
    "tslint-loader": "^3.5.3",
    "tslint-react": "^3.0.0",
```

In Webpack config (`config/webpack.config.dev.js` in `create-react-app-typescript`)
```
      // First, run the linter.
      // It's important to do this before Babel processes the JS.
      {
        test: /\.(ts|tsx)$/,
        loader: require.resolve('tslint-loader'),
        enforce: 'pre',
        include: paths.appSrc,
      },
```

In `tslint.json`
```
{
     "extends": ["tslint-react"],
      ...
}
```

Do you think it would be feasible to include such a configuration in `gatsby-plugin-typescript`? Would you like to see something like that too or is it to opinionated to include it by default?

**Comment by calcsam** [comment]
This seems to be two questions. 

First, is it desirable to include TSLint as a dependency of `gatsby-plugin-typescript`, and a `tslint.json` in the `gatsby-starter-typescript` in order to provide better developer UX when using IDEs. Seems like the answer here is a clear "yes".

Second, is it desirable to include an opinionated config in `tslint.json` in order to force folks down a happy path. This might be a good idea depending on how common `tslint-react` configs are, but am not personally well versed in TS linting norms.

**Comment by kriim** [comment]
Good point. I guess it would be sufficient to only include `tslint` and `tslint-loader` in the Gatsby plugin then. This way at least the custom Webpack config is taken care of.

The `tslint.json` could be provided by the user as it is the case now. If somebody wants additional React lint rules, `tslint-react` can be added and the `tslint.json` modified accordingly. When I filed this issue I didn't realize that `tslint-react` only contains rules. So a pointer in the README might be enough here.

**Comment by calcsam** [comment]
Feel free to add one!

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
