### ISSUE TITLE
The "Submit a Starter" link takes to Community Contribution page

### ISSUE THREAD

**Issue by atapas** [gatsbyjs/gatsby#31623]
## Summary

- I am trying to submit a starter project from this link: https://www.gatsbyjs.com/starters/?. 
- I clicked on this button, 
![image](https://user-images.githubusercontent.com/3633137/119921277-56a5d500-bf8b-11eb-8753-d777e1ebe6ab.png)
- It takes me to this page, https://www.gatsbyjs.com/contributing/community-contributions/. This page doesn't talk anything about how to create a starter for a plugin and submit it.

The same issue is from the plug-ins page also 
![image](https://user-images.githubusercontent.com/3633137/119921505-c1571080-bf8b-11eb-929c-c80aef7d0cb5.png)

After a few searches, I found this page that talks about creating a starter, https://www.gatsbyjs.com/docs/creating-a-starter/. You should link to this page instead of from the button mentioned above. However, this page also has the same problem in the submit section,

![image](https://user-images.githubusercontent.com/3633137/119921691-12ff9b00-bf8c-11eb-9b92-fabc1c56fb5d.png)

The link ` add it to the Gatsby Starter Library` goes to the community contribution page again. It is not clear how to submit a starter.

### Motivation

I have created a plugin and a starter. I am not sure, how to submit it.

## Steps to resolve this issue

Point to the documentation on how to submit a starter. Also, link the same doc from the relevant pages.

**Comment by LekoArts** [comment]
Hi!

It links you to this page (https://www.gatsbyjs.com/contributing/community-contributions/) because of the paragraph there:

> Note: Showcase and starter contributions are currently paused while the Gatsby team develops a new workflow for sharing your Gatsby sites with the community.

For having your plugin show up in the plugin search you can follow these steps:
https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/submit-to-plugin-library/
