### ISSUE TITLE
Unexpected WebpackCompilationHash change

### ISSUE THREAD

**Issue by herecydev** [gatsbyjs/gatsby#31628]
## Description

The `webpackCompilationHash` is changing value when running 2 back-to-back `gatsby build` with no changes.

### Steps to reproduce

With the following flags:

```
    PRESERVE_WEBPACK_CACHE: true,
    PRESERVE_FILE_DOWNLOAD_CACHE: true,
```

Following the instructions outlined here: https://www.gatsbyjs.com/docs/debugging-incremental-builds/

1. gatsby clean
2. gatsby build
3. cp -r public public-first-build
4. gatsby build
5. diff -u -r public-first-build public > build-diff.diff

### Expected result

No changes occur (this randomly does happen so it's functional sometimes)

### Actual result

```diff
diff -u -r public-first-build/page-data/app-data.json public/page-data/app-data.json
--- public-first-build/page-data/app-data.json	2021-05-28 11:02:01.347655500 +0100
+++ public/page-data/app-data.json	2021-05-28 11:02:13.830908900 +0100
@@ -1 +1 @@
-{"webpackCompilationHash":"9998e29559e89ee74554"}
+{"webpackCompilationHash":"496bc43b70381f3027d3"}
```

This is the strange part, nothing else has changed but the webpackCompilationHash did which prompted all the pages to be rebuilt.

### Environment

```
  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 9 5950X 16-Core Processor            
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.964.0), Chromium (90.0.818.62)
  npmPackages:
    gatsby: ^3.0.0 => 3.6.0 
    gatsby-cypress: ^1.0.0 => 1.6.0 
    gatsby-plugin-google-tagmanager: ^3.0.0 => 3.6.0 
    gatsby-plugin-image: ^1.0.0 => 1.6.0 
    gatsby-plugin-no-sourcemaps: ^3.0.0 => 3.6.0 
    gatsby-plugin-react-helmet: ^4.0.0 => 4.6.0 
    gatsby-plugin-remove-generator: ^1.0.6 => 1.1.0 
    gatsby-plugin-sharp: ^3.0.0 => 3.6.0 
    gatsby-plugin-sitemap: ^4.2.0 => 4.2.0 
    gatsby-plugin-styled-components: ^4.0.0 => 4.6.0 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.10 => 1.1.22 
    gatsby-source-filesystem: ^3.0.0 => 3.6.0 
    gatsby-transformer-remark: ^4.0.0 => 4.3.0 
    gatsby-transformer-sharp: ^3.0.0 => 3.6.0 
  npmGlobalPackages:
    gatsby-cli: 2.19.2

```

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

As this is still currently an experiment behind a flag we collect all forms of feedback inside an umbrella discussion. Please post your issue there: https://github.com/gatsbyjs/gatsby/discussions/28331?sort=new

Thanks!
