### ISSUE TITLE
Starter Library - gatsby-starter-tailwind resolves to 404

### ISSUE THREAD

**Issue by igorradovanov** [gatsbyjs/gatsby#31625]
## Description

The gatsby-starter-tailwind starter page at https://www.gatsbyjs.com/starters/ resolves to Page not found.

### Steps to reproduce

Go to https://www.gatsbyjs.com/starters/ and try to access the gatsby-starter-tailwind page. Alternatively, go directly to https://www.gatsbyjs.com/starters/taylorbryant/gatsby-starter-tailwind/

### Expected result

The page should resolve to Starter page information.

### Actual result

Page resolves to 404 Not Found error.

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

The source code for the website isn't here anymore and thus any issues related to the website should go to https://www.gatsbyjs.com/support/ - please file your problem there. Thanks!
