### ISSUE TITLE
[gastby-plugin-image] fails to validate W3C

### ISSUE THREAD

**Issue by Skil3e** [gatsbyjs/gatsby#31635]
## Description

Images displayed with gastby-plugin-image fail to validate on [W3C Validator](https://validator.w3.org/)

### Steps to reproduce

Check this link [W3C validator emmbrand](https://validator.w3.org/nu/?doc=https%3A%2F%2Femmbrand.com%2F)

Sample code used to display the image:

```jsx
/* Graphql query */
 const query = useStaticQuery( graphql`{
        intro: file(relativePath: {eq: "landing-header.jpg"}) {
            relativePath
            childImageSharp {
                gatsbyImageData(layout: FULL_WIDTH)
            }
        }
    }
 ` )

/* Display inside the retur function */
<GatsbyImage
    className={ "h--v100" }
    image={ query.intro.childImageSharp.gatsbyImageData }
    imgStyle={ { objectFit: "cover" } }
    alt={ imgAlt( query.intro.relativePath ) }
/>
```

### Expected result

No errors.

### Actual result

Error: Element source is missing required attribute srcset.
Error: The sizes attribute may be specified only if the srcset attribute is also present.
Error: Element img is missing required attribute src

### Environment

```
  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
    npm: 7.14.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.964.0), Chromium (90.0.818.66)
  npmPackages:
    gatsby: ^3.6.1 => 3.6.1 
    gatsby-plugin-anchor-links: ^1.2.1 => 1.2.1 
    gatsby-plugin-image: ^1.6.0 => 1.6.0 
    gatsby-plugin-manifest: ^3.6.0 => 3.6.0 
    gatsby-plugin-react-helmet: ^4.6.0 => 4.6.0 
    gatsby-plugin-sass: ^4.6.0 => 4.6.0 
    gatsby-plugin-sharp: ^3.6.0 => 3.6.0 
    gatsby-plugin-sitemap: ^4.2.0 => 4.2.0 
    gatsby-source-filesystem: ^3.6.0 => 3.6.0 
    gatsby-theme-i18n: ^2.0.0 => 2.0.0 
    gatsby-transformer-sharp: ^3.6.0 => 3.6.0 
  npmGlobalPackages:
    gatsby-cli: 3.5.0
```

**Comment by Henrik-Hey** [comment]
I'm having this issue as well

**Comment by Skil3e** [comment]
The issue still exists.

**Comment by LekoArts** [comment]
Hi!

This is not an issue and you can ignore the warnings from the validator. We use React to eventually build the image and for that we e.g. use `data-srcset` instead of `srcset`. Thus warnings like `Element source is missing required attribute srcset` are false positives.

**Comment by Skil3e** [comment]
I understand the concept. Although most of the sites I develop must be
compliant with the ESPA specification which includes w3c validation. Maybe
adding a placeholder prop could solve this problem. Thanks for your time.
