### ISSUE TITLE
Developing resource error: framework.js not found

### ISSUE THREAD

**Issue by zhaohuanyuu** [gatsbyjs/gatsby#31648]
### Developing error
error in console: GET http://localhost:8000/framework.js net::ERR_ABORTED 404 (Not Found)

I had tried **gatsby clean** the .cache directory, but it still doesn't work.
developing html postBodyComponents reference /framework.js: eg. <script src="/framework.js"></script>

### Steps to reproduce

i'll list the gatsby-config.js in below.

### Expected result

no error happen

### Actual result

the framework.js resource not found (actually it doesn't exist)

### Environment

  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 7.14.0 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.93
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.4.1 => 3.6.1 
    gatsby-plugin-gatsby-cloud: ^2.6.0 => 2.6.1 
    gatsby-plugin-image: ^1.6.0 => 1.6.0 
    gatsby-plugin-manifest: ^3.6.0 => 3.6.0 
    gatsby-plugin-mdx: ^2.6.0 => 2.6.0 
    gatsby-plugin-react-helmet: ^4.6.0 => 4.6.0 
    gatsby-plugin-sass: ^4.6.0 => 4.6.0 
    gatsby-plugin-sass-resources: ^2.0.0 => 2.0.0 
    gatsby-plugin-sharp: ^3.6.0 => 3.6.0 
    gatsby-plugin-sitemap: ^4.2.0 => 4.2.0 
    gatsby-source-filesystem: ^3.6.0 => 3.6.0 
    gatsby-transformer-sharp: ^3.6.0 => 3.6.0 
  npmGlobalPackages:
    gatsby-cli: 3.5.0

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by zhaohuanyuu** [comment]
> Hi!
> 
> Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction](https://gatsby.dev/reproduction). This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.
> 
> If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction](https://gatsby.dev/reproduction) and we'll be able to take another look.
> 
> Thanks for using Gatsby! 💜

Sorry for not providing the code to reproduce the problem in the first time.

here is: https://github.com/zhaohuanyuu/my-bug-reproduction

I have deleted irrelevant configuration and codes,So now the high probability is because of gatsby-plugin-sass-resources.
is there an incompatibility between sass and gatsby 3.x?

**Comment by lucas-paulger-sonarsource** [comment]
I'm running into this issue as well while trying to upgrade to v3. I'm going to skip ahead to v4 to see if I can get over this issue. The reproduced issue reference is gone now 🤷🏻 .  I'll try and follow up to see if that fixes the issue.
