### ISSUE TITLE
`gatsby develop` page reloads fail if URL ends with a SemVer range

### ISSUE THREAD

**Issue by danoc** [gatsbyjs/gatsby#3164]
Hi! This is a weird one.

`gatsby develop` uses `parse-filepath` to grab the extension from a URL and serve `public/index.html`:

https://github.com/gatsbyjs/gatsby/blob/b21a0225d93e6c5eebb5e0d423715f9f16d9593d/packages/gatsby/src/commands/develop.js#L146-L158

Line 149 incorrectly fails for our URLs that include a SemVer range at the end. 

This happens because `parse-filepath` believes that a URL like `/tp-ui-react-button/1.6.3/` has a file extension of `.3`:

![image](https://user-images.githubusercontent.com/916038/33778477-a8884e7c-dbfd-11e7-9a7f-fd6a4141eb25.png)

This causes the development server to throw a 404 when attempting to reload the page: "Cannot GET /tp-ui-react-button/1.6.3/". The reloads work when I use URLs that end in `index.html`

***
I'll likely work around this by wrapping `gatsby-link` to append `index.html` to URLs on development.

Any thoughts on adding `parsedPath.path.endsWith('/')` to the conditional on L149? I can make the change if y'all would like.

**Comment by calcsam** [comment]
Sure, definitely add a PR w/ a test case.
