### ISSUE TITLE
Uncaught (in promise) DOMException: Quota exceeded. sw.js

### ISSUE THREAD

**Issue by awesomebob** [gatsbyjs/gatsby#3165]
Site: https://www.gatsbyjs.org/
Browser: Chrome Version 62.0.3202.94 (Official Build) (64-bit)
OS: Ubuntu 16.04.3 LTS

I've noticed some issues with the https://www.gatsbyjs.org/ site, and am getting numerous errors in the console log:

![screenshot_1512753349](https://user-images.githubusercontent.com/3677807/33778978-dd355ec4-dbff-11e7-94ea-e2d0da6aadea.png)

When I get these errors, links stop functioning until I hard refresh my browser. After visiting a few more pages, the error returns.

I suspect that it has something to do with pre-fetching data on pages with lots of links.

I'm not overly familiar with service workers, but I'm hoping that there would be a way to handle this exception and fallback to loading data normally when the service worker quota is reached.

**Comment by ratikanta-sdrc** [comment]
@awesomebob This error is because you have low memory space on your operating system installed drive. Empty some space, this will work. I am also stuck in this error. Trying to handle it.

**Comment by kevinsalerno** [comment]
You're storing too much data in the allowed browser cache for the service worker.

See this:
https://github.com/NitroBAY/meteor-service-worker/issues/6

Ignore Ratikanta's answer.

**Comment by awesomebob** [comment]
This is happening on gatsbyjs.org, so I would think that the Gatsby project would benefit from catching this error and handling it instead of just letting site navigation break.

**Comment by nicholaai** [comment]
+1

**Comment by m-allanson** [comment]
@awesomebob and @nicholaai I'm unable to replicate this on macOS with Chrome v64.0.3282.186.

What output do you get if you go to gatsbyjs.org and paste the following into Chrome's console?

```javascript
navigator.webkitTemporaryStorage.queryUsageAndQuota(
  (bytesUsed, bytesRemaining) => {
    console.log("bytes used", bytesUsed);
    console.log("bytes left", bytesRemaining);
  },
  e => { console.log(e) }
);
```

Alternatively the _Application_ tab in Chrome's dev tools will give you similar info:

![screen shot 2018-02-28 at 11 14 02](https://user-images.githubusercontent.com/381801/36784780-a014318c-1c78-11e8-8c78-0fccde69550a.png)

**Comment by awesomebob** [comment]
I'm not able to reproduce the problem currently either.

```
bytes used 64597200
bytes left 2199497117
```

This might have been fixed recently?

**Comment by nicholaai** [comment]
I had this happen on my own project, not on the gatsby.org website. Apologies for not being more specific. Oddly enough, the problem self-resolved after some more refreshes & opening new incognito windows.

**Comment by m-allanson** [comment]
I'm going to close this as I don't think there's anything Gatsby can do here. Please re-open if that's wrong!

**Comment by stonehz** [comment]
Is there a method we can exclude opaque requests ? looking into https://www.gatsbyjs.org/docs/browser-apis/#onServiceWorkerRedundant
 or  https://www.gatsbyjs.org/docs/browser-apis/#onServiceWorkerActive but not sure what which API allows us to add the suggested logic
