### ISSUE TITLE
[gatsby-source-mongodb] Getting "MongoServerSelectionError: getaddrinfo ENOTFOUND" error

### ISSUE THREAD

**Issue by iozcelik** [gatsbyjs/gatsby#31650]
## Description

I try to connect MongoDb atlas database and from mongoCompass, connection string is working. However, when I start gatsby server, I get error.

### Steps to reproduce

- type `gatsby develop`
- When process starting wait a while, then write warning log.
- So I cannot see the my query inside graphql page.

```
{
      resolve: "gatsby-source-mongodb",
      options: {              
        dbName: 'myDb',
        collection: "myCollection",
        server: {
            address: "cluster0.tl25n.mongodb.net",
            port: 27017
        },
        auth: {
            user: "myUserName",
            password: "myPassword"
        },
        extraParams: {
            replicaSet: "atlas-n3c6zn-shard-0",
            ssl: true,
            authSource: "admin",
            retryWrites: true
        }
      },
    },
```

### Actual result

```
warn MongoServerSelectionError: getaddrinfo ENOTFOUND cluster0.tl25n.mongodb.net
    at Timeout._onTimeout (E:\Kisisel\gatsbyTest\sultansehir\node_modules\mongodb\lib\core\sdam\topology.js:438:30)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map { 'cluster0.tl25n.mongodb.net:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}
```

### Environment
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.8
  Browsers:
    Chrome: 90.0.4430.212
    Edge: Spartan (44.19041.964.0), Chromium (91.0.864.37)
  npmPackages:
    gatsby: ^3.4.1 => 3.5.0
    gatsby-plugin-breadcrumb: ^12.1.1 => 12.1.1
    gatsby-plugin-google-analytics: ^3.5.0 => 3.5.0
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-image: ^1.5.0 => 1.5.0
    gatsby-plugin-manifest: ^3.5.0 => 3.5.0
    gatsby-plugin-mdx: ^2.5.0 => 2.5.0
    gatsby-plugin-react-helmet: ^4.5.0 => 4.5.0
    gatsby-plugin-resolve-src: ^2.1.0 => 2.1.0
    gatsby-plugin-sharp: ^3.5.0 => 3.5.0
    gatsby-plugin-sitemap: ^4.1.0 => 4.1.0
    gatsby-source-filesystem: ^3.5.0 => 3.5.0
    gatsby-source-mongodb: ^3.6.0 => 3.6.0
    gatsby-transformer-sharp: ^3.5.0 => 3.5.0
  npmGlobalPackages:
    gatsby-cli: 3.6.0

**Comment by diliptekwani** [comment]
+1 same problem I am also having, anyone found solution for this??
