### ISSUE TITLE
Node js server is not running when deployed on Gatsby Cloud

### ISSUE THREAD

**Issue by kevinNejad** [gatsbyjs/gatsby#31716]
## Description

I followed the tutorial [Gatsby plugin for easy integration with Node.js servers](https://www.gatsbyjs.com/plugins/gatsby-plugin-nodejs/) to setup an express server to handle an api call request. It work on the development (localhost), but it seems to fail after deployment (context of the page is returned as response body).

### Steps to reproduce

Create a gatsby website following the tutorial. Install gatsby-plugin-nodejs + express dependencies. Created a server folder and add a minimal express server code.  

### Expected result
server returns the response as it does in the development (localhost).

### Actual result

The context of the page is returned for each request.

### Environment

  System:
    OS: Linux 5.10 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Languages:
    Python: 3.9.5 - /usr/bin/python
  npmPackages:
    gatsby: ^3.4.1 => 3.6.1
    gatsby-plugin-gatsby-cloud: ^2.6.1 => 2.6.1
    gatsby-plugin-image: ^1.6.0 => 1.6.0
    gatsby-plugin-nodejs: ^0.7.0 => 0.7.0
    gatsby-plugin-sharp: ^3.6.0 => 3.6.0
    gatsby-source-filesystem: ^3.6.0 => 3.6.0
    gatsby-transformer-sharp: ^3.6.0 => 3.6.0
  npmGlobalPackages:
    gatsby-cli: 3.6.0

gatsby-config.js:
```module.exports = {
  siteMetadata: {
    title: "testweb",
  },
  plugins: [
    "gatsby-plugin-gatsby-cloud",
    "gatsby-plugin-image",
    "gatsby-plugin-sharp",
    "gatsby-transformer-sharp",
    "gatsby-plugin-nodejs",
    {
      resolve: "gatsby-source-filesystem",
      options: {
        name: "images",
        path: "./src/images/",
      },
      __key: "images",
    },
  ],
};
```

**Comment by KyleAMathews** [comment]
Hey, that's not a plugin we support. What it sounds like you want to use instead is Functions! https://www.gatsbyjs.com/docs/how-to/functions/ They're pretty new but they're a replacement for running standalone node.js servers for APIs.
