### ISSUE TITLE
using-MDX example not working

### ISSUE THREAD

**Issue by kemalgencay** [gatsbyjs/gatsby#31725]
## Description

Describe the issue that you're seeing.
![Screenshot_2021-06-02_09:12:35](https://user-images.githubusercontent.com/38295784/120433107-838b2b00-c383-11eb-8717-65e973fc5b32.png)

### Steps to reproduce
I take the steps in README.md file and get the error in the attached screenshot.
### Expected result

I expect using-MDX example to run as my other Gatsby sites.

### Actual result..

I typed gatsby develop and got the error shown in the attached screen shot file.
### Environment

  System:
    OS: Linux 5.4 Peppermint 10 (Ten)
    CPU: (2) x64 Pentium(R) Dual-Core CPU       T4500  @ 2.30GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 14.15.3 - ~/.config/nvm/versions/node/v14.15.3/bin/node
    Yarn: 1.21.0 - ~/.config/nvm/versions/node/v14.15.3/bin/yarn
    npm: 7.11.1 - ~/.config/nvm/versions/node/v14.15.3/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0.1
  npmPackages:
    gatsby: next => 3.7.0-next.0 
    gatsby-image: next => 3.7.0-next.0 
    gatsby-plugin-manifest: next => 3.7.0-next.0 
    gatsby-plugin-mdx: next => 2.7.0-next.0 
    gatsby-plugin-offline: next => 4.7.0-next.0 
    gatsby-plugin-react-helmet: next => 4.7.0-next.0 
    gatsby-plugin-sharp: next => 3.7.0-next.0 
    gatsby-source-filesystem: next => 3.7.0-next.0 
    gatsby-transformer-sharp: next => 3.7.0-next.0 
  npmGlobalPackages:
    gatsby-cli: 3.6.0

No changes were made to the original files.

Run `gatsby info --clipboard` in your project directory and paste the output here. Also name any `flags` you use inside `gatsby-config.js`.

**Comment by LekoArts** [comment]
The example seems to be outdated/not working anymore. If you want to try out MDX with Gatsby I'd rather suggest using `npm init gatsby`.

For me it fails on this:

```
 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'performance-now' in '/c/Users/Lennart/Development/Playground/using-mdx/node_modules/react-charts/dist'

If you're trying to use a package make sure that 'performance-now' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/react-charts/dist/react-charts.cjs.development.js:8:26
```

So something with the `react-charts` package needs to be fixed.

**Comment by kemalgencay** [comment]
Thanks
Regards
