### ISSUE TITLE
[gatsby-source-wordpress] - Uses gatsby-plugin-catch-links can't overwrite this

### ISSUE THREAD

**Issue by mrlagmer** [gatsbyjs/gatsby#31738]
### Description

Gatsby source wordpress seems to be using gatsby plugin catch links. This takes over sitewide and gets applied to all links. This is breaking navigation on our site and causing issues. I have attempted to use plugin options in gatsby config to set up excludeRegex but this does not seem to run.

### Steps to reproduce

1. Clone / view minimal repo using gatsby-starter-default
2. Add the gatsby-source-wordpress plugin 
3. Add a link with a tag to the site
4. Run gatsby develop and hit the link with network tab open.
5. See that the link no longer does a full page refresh as gatsby-plugin-catch-links takes over and makes all links Gatsby Link.

### Expected result

Creating a link without Gatsby Link should work as expected and should cause a page refresh when hit.

### Actual result

link does not leave the app and it runs any link as if you are using Gatsby Link.

### Environment

OS: Pop!_OS 20.04 LTS x86_64 
Gatsby CLI version: 3.6.0
Gatsby version: 3.6.1
Node Version: v14.17.0

Happy to help contribute a fix if someone can point me in correct direction for this. Also be good to document this and save someone else from hours of troubleshooting.

**Comment by mrlagmer** [comment]
This issue is still open and has not been solved.

**Comment by mrlagmer** [comment]
So my take on what should be done is Gatsby plugin catch links should be removed from gatsby-source-wordpress. In the docs and guides for source wordpress the users should be advised that adding catch links is a good idea and will speed up the site. This will then allow the user to know that this plugin is installed as they do it. It also allows the user to actually put in exclusions where they don't want catch links to catch the link.

This is what we have done on our site now to solve the above issue. If anyone looks at this and agrees I can get a PR going for you just let me know that it is worth doing and would be accepted.

**Comment by snibbo71** [comment]
Ignore my comment above - my issue is in a completely different area of the code, and is likely by design :) Apologies.
