### ISSUE TITLE
No HTTP response detected for gatsby-plugin-google-analytics

### ISSUE THREAD

**Issue by melissamcewen** [gatsbyjs/gatsby#3174]
I just installed this plugin and I'm getting this error detected by Tag Manager
> No HTTP response detected

I assume it is due to Tag manager wanting to see the tags.js implementation that Google now recommends rather than Analytics.js?

**Comment by KyleAMathews** [comment]
For tag manager you want to use https://www.npmjs.com/package/gatsby-plugin-google-tagmanager

**Comment by melissamcewen** [comment]
Ah it's confusing because now Google is recommending this code instead of analytics.js:
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=TRACKINGID"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'TRACKINGID');
</script>
```

It is called Global Site Tag not Tag Manager, they work together apparently. Either way, need to read more about it, but analytics.js should still work so probably was not the cause of my problem. Still have no idea why I'm getting that HTTP error then.
