### ISSUE TITLE
gatsby-plugin-mdx's MDXRenderer requires the 'unsafe-eval' value to be set in the Content-Security-Policy header to work correctly

### ISSUE THREAD

**Issue by vinassefranche** [gatsbyjs/gatsby#31767]
## Description

I'm trying to add the CSP header on my website built with gatsby, which uses the `gatsby-plugin-mdx` plugin, specifically the `MDXRenderer`. I'm forced to set the `'unsafe-eval'` value for the `script-src` directive for this component to work correctly. This removes most of the benefits of setting the CSP header.
The incriminated code seems to be https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/mdx-renderer.js#L28

### Steps to reproduce

- [ ] clone this [repository](https://github.com/vinassefranche/gatsby-mdx-csp-issue): `git clone git@github.com:vinassefranche/gatsby-mdx-csp-issue.git`
- [ ] `cd gatsby-mdx-csp-issue`
- [ ] `yarn install`
- [ ] `yarn build && yarn serve -p 8000`
- [ ] Open http://localhost:8000/hello-with-mdx-renderer/ in a browser
- [ ] Click on the `click me` button

### Expected result

This should trigger an alert saying 'hello'
You can see the expected result by running `WITH_UNSAFE_EVAL=true yarn build && yarn serve -p 8000` which sets the  `'unsafe-eval'` value in the CSP.

### Actual result

No alert is triggered.

### Environment

  System:
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Shell: 5.4.2 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Firefox: 89.0
  npmPackages:
    gatsby: ^3.6.2 => 3.6.2
    gatsby-plugin-csp: ^1.1.3 => 1.1.3
    gatsby-plugin-mdx: ^2.6.0 => 2.6.0
    gatsby-source-filesystem: ^3.6.0 => 3.6.0

**Comment by vinassefranche** [comment]
This issue is still relevant. I have no idea how to solve it though...

**Comment by ryanerringtonatom** [comment]
Unfortunately this issue has been around for a while now. It was even mentioned on the [original plugin repo](https://github.com/ChristopherBiscardi/gatsby-mdx/issues/303).

My understanding is that for low level uses of `MDXRenderer`, i.e. to output a single component on a page there is no alternative. However, for full page layouts which can be wrapped in a template `gatsby-node.js` can be used instead. This is described more clearly on the linked issue above.

**Comment by vinassefranche** [comment]
@ryanerringtonatom Thanks for your answer! I'll try to have a look if I can build them on the server side!
