### ISSUE TITLE
Examples not loading in GraphQL Query Options Reference

### ISSUE THREAD

**Issue by chromjs** [gatsbyjs/gatsby#31785]
Hi! I'm unable to see any of the code examples on this page:
https://www.gatsbyjs.com/docs/graphql-reference/

> Your Preview is not running.
Please visit
https://www.gatsbyjs.com/dashboard/ab141368-6f33-4c23-82ed-5531dcc907f8/sites/18f22d3b-6501-4397-bf45-63d95ae0afa1/cmsPreview
to restart it.
If the issue persists, please contact: support@gatsbyjs.com

I just started to learn Gatsby and this documentation would be very useful to me.
Thanks

**Comment by LekoArts** [comment]
Thanks, they are up now again!
