### ISSUE TITLE
createPage path option should default to "/"

### ISSUE THREAD

**Issue by luczaki114** [gatsbyjs/gatsby#3178]
createPage path option requires a non empty string and it would be nice for it to default to "/" when it is empty.

**Comment by calcsam** [comment]
This seems like a great idea. Want to write a PR adding this?

**Comment by KyleAMathews** [comment]
You can add the code here https://github.com/gatsbyjs/gatsby/blob/70aae389afc42db66aa60e5abe632c17f44bbb8c/packages/gatsby/src/redux/actions.js#L104

**Comment by luczaki114** [comment]
I'll put something together. :)

**Comment by calpa** [comment]
@luczaki114 any update?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
