### ISSUE TITLE
Got render-page.js, render-page.js.map instead of index.html with "gatsby develop" command.

### ISSUE THREAD

**Issue by eric8979** [gatsbyjs/gatsby#31795]
## Description

Got render-page.js, render-page.js.map instead of index.html with "gatsby develop" command.
Similar to issue #13202.

### Steps to reproduce

1. `npm install -g gatsby-cli`
2. `gatsby new [project_name] https://github.com/gatsbyjs/gatsby-starter-hello-world`
3. `gatsby develop` 

### Expected result

index.html file should be generated in the public folder.

### Actual result

no `index.html` file in public folder. 
`render-page.js`, `render-page.js.map` generated instead.

### Environment

 System:
    OS: macOS 11.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    npm: 7.15.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 91.0.4472.77
    Firefox: 88.0.1
    Safari: 14.1
  npmPackages:
    gatsby: ^3.6.2 => 3.6.2
  npmGlobalPackages:
    gatsby-cli: 3.6.0

No modification on `gatsby-config.js`.

**Comment by LekoArts** [comment]
Hi!

Your expected result is wrong as everything is working as intended. If you want to see the final HTML you'll need to run `gatsby build` or enable the `DEV_SSR` flag: https://github.com/gatsbyjs/gatsby/discussions/28138
