### ISSUE TITLE
[gatsby-remark-prismjs] command-line plugin ouput lines retain syntax highlighting

### ISSUE THREAD

**Issue by ben-dyer** [gatsbyjs/gatsby#31794]
## Description

In the prismjs command line plugin, output lines are not highlighted (cf. https://prismjs.com/plugins/command-line/). This gives consistent coloring for outputs that may happen to be alphanumeric / numeric / capital / lower case / etc.

With the gatsby-remark-prismjs plugin, the line is colored the same whether it is marked as an outputLine or not.

### Steps to reproduce

Follow installation instructions for gatsby-remark-prismjs, use the commandline plugin (also in instructions)

<pre>
```bash{outputLines: 2}
echo "123"
123
```</pre>

observe unexpected (with prismjs) syntax-highlighting in the second line.


### Expected result

These blocks would have their second line rendered the same color

<pre>
```bash{outputLines: 2}
echo "hello"
hello
```</pre>

<pre>
```bash{outputLines: 2}
echo "123"
123
```
</pre>

### Actual result

The  second value is syntax highlighted as an integer

### Environment

```
  Browsers:
    Chrome: 90.0.4430.85
    Firefox: 88.0.1
  npmPackages:
    gatsby: ^3.4.1 => 3.6.1
    gatsby-plugin-gatsby-cloud: ^2.4.1 => 2.6.1
    gatsby-plugin-goatcounter: ^0.4.0 => 0.4.0
    gatsby-plugin-image: ^1.4.0 => 1.6.0
    gatsby-plugin-manifest: ^3.4.0 => 3.6.0
    gatsby-plugin-offline: ^4.4.0 => 4.6.0
    gatsby-plugin-postcss: ^4.6.0 => 4.6.0
    gatsby-plugin-react-helmet: ^4.4.0 => 4.6.0
    gatsby-plugin-sharp: ^3.4.1 => 3.6.0
    gatsby-remark-copy-linked-files: ^4.3.0 => 4.3.0
    gatsby-remark-katex: ^4.0.0 => 4.2.0
    gatsby-remark-prismjs: ^5.3.0 => 5.3.0
    gatsby-remark-remove-comments: ^0.1.0 => 0.1.0
    gatsby-source-filesystem: ^3.4.0 => 3.6.0
    gatsby-transformer-remark: ^3.2.0 => 3.2.0
    gatsby-transformer-sharp: ^3.4.0 => 3.6.0
  npmGlobalPackages:
    gatsby-cli: 3.6.0
```

**Comment by vladar** [comment]
Thanks for opening this issue. Sounds like a valid enhancement request. If you can come up with a PR implementing this - we will be happy to accept it.

**Comment by ben-dyer** [comment]
Thanks @vladar, I will take a look

**Comment by ben-dyer** [comment]
Hi @vladar I have opened a PR https://github.com/gatsbyjs/gatsby/pull/31835
