### ISSUE TITLE
Multiple `gatsby-global-css` ids 

### ISSUE THREAD

**Issue by rootkowsky** [gatsbyjs/gatsby#31801]
## Description

I've realised that gatsby prints `<style>` tag with repeated id `gatsby-global-css`

https://github.com/gatsbyjs/gatsby/blob/e8daa513ba1c1907eda8785eb5f788430957775a/packages/gatsby/cache-dir/static-entry.js#L346-L356

### Steps to reproduce

1. `gatsby new my-default-starter https://github.com/gatsbyjs/gatsby-starter-default`
2. `cd my-default-starter`
3. `npm install gatsby-plugin-split-css`
4. add `gatsby-plugin-split-css` to `gatsby-config.js` 
```
// gatsby-config.js

module.exports = {
  plugins: [
    `gatsby-plugin-split-css`
  ],
}
```
5. create and import any `.css` file in `gatsby-browser.js` and `gatsby-ssr.js` file:
`import './src/assets/global.css';`
6. `gatsby build && gatsby serve`

### Expected result

Ids of `<style>` tag should be unique 

### Actual result

Ids of `<style>` tags are not unique

### Environment

```
  System:
    OS: macOS 11.4
    CPU: (8) x64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 2.4.1 - ~/.nvm/versions/node/v12.14.1/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 91.0.4472.77
    Safari: 14.1.1
  npmPackages:
    gatsby: ^3.6.2 => 3.6.2 
    gatsby-plugin-gatsby-cloud: ^2.6.1 => 2.6.1 
    gatsby-plugin-image: ^1.6.0 => 1.6.0 
    gatsby-plugin-manifest: ^3.6.0 => 3.6.0 
    gatsby-plugin-offline: ^4.6.0 => 4.6.0 
    gatsby-plugin-react-helmet: ^4.6.0 => 4.6.0 
    gatsby-plugin-sharp: ^3.6.0 => 3.6.0 
    gatsby-plugin-split-css: ^2.0.0 => 2.0.0 
    gatsby-source-filesystem: ^3.6.0 => 3.6.0 
    gatsby-transformer-sharp: ^3.6.0 => 3.6.0 
  npmGlobalPackages:
    gatsby-cli: 3.3.0

```

**Comment by vladar** [comment]
You are right. The change was introduced as a part of DEV SSR in https://github.com/gatsbyjs/gatsby/pull/27432/files#diff-4cd5b620539129dfa79254b9cdae3bd9b619426b83b412d2647cfb416730d362

And it was based on an assumption that there will be only one global style tag. But this plugin essentially splits css to multiple files. Regardless, this `id` is only needed for tests: https://github.com/gatsbyjs/gatsby/pull/27432/files#diff-e441aad1b67dcbd399b4013a3c9bf3c84033436213bdceb1ebdf92f07e5fed1dR25

So we can easily replace it with some `data-x` attribute instead.
