### ISSUE TITLE
What's the expected behaviour when disabling JavaScript

### ISSUE THREAD

**Issue by aderaaij** [gatsbyjs/gatsby#3181]
Whilst working on my personal site, I noticed that only the first page will be rendered when I disable JavaScript. All the other pages just show the header and an empty page. I saw some Gatsby starters that don't work with JavaScript either and I was wondering what the expected behavior is when disabling JavaScript on your production build. Are there certain things like extending a React Component that prevents pages from being output in HTML?

* Gatsby version: 1.9.130
* Node version: 8.6.0
* OS: OSX High Sierra

**Comment by aderaaij** [comment]
I apologize for this premature thread! I just discovered that it was the service worker messing about. When I clear out the site data / service worker and disable JavaScript, all the pages still work.

**Comment by abumalick** [comment]
Thank you very much, I ran into the same problem. Your messaged helped me a lot
