### ISSUE TITLE
window.history.state resets in built version, but persists in develop mode

### ISSUE THREAD

**Issue by EugeneDraitsev** [gatsbyjs/gatsby#31868]
## Description

Hi

I'm trying to use `state` in options for `navigate` function, based on your [documentation](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/#add-state-to-programmatic-navigation)

I have super simple index page:
```tsx
const IndexPage = () => {
  const goToTest = () => {
    navigate('/test', {
      state: {
        action: 123,
      },
    })
  }

  return (
    <main>
      <button onClick={goToTest}>Go to test page</button>
    </main>
  )
}
```

and I just render `JSON.stringify(window.history.state)` on /test page

I expect to see persistent state value after page refresh and it works fine in develop mode:

![1](https://user-images.githubusercontent.com/16540432/121606880-41cb4600-ca4f-11eb-9a6e-a01b481ccf5f.gif)

But when I build my application and use gatsby serve, history state resets after page reloading:

![2](https://user-images.githubusercontent.com/16540432/121606984-7e973d00-ca4f-11eb-8d21-d1406c3368b4.gif)

Why this behavior is different for these cases and what is correct expected behavior for `window.history.state` after page reloading?

### Steps to reproduce

1. Clone this repository [https://github.com/EugeneDraitsev/gatsby-history-state-bug](https://github.com/EugeneDraitsev/gatsby-history-state-bug)
2. yarn clean+ yarn start to see persistent `window.history.state`
3. yarn build + yarn server to see reloading `window.history.state` 

One more funny thing about this issue: if you run `yarn start` after `yarn build` without cleaning, then  `window.history.state` in develop mode will work the same, as built mode (resets after page reloading). But if you run `yarn  clean` + `yarn start` then `window.history.state` will be persistent.

Also you can check deployed [demo](https://gatsby-history-state-bug.netlify.app/)

### Expected result

Same behavior in dev/prod modes. Preferable to not reset  `window.history.state` in both modes

### Actual result

Different behavior in dev/prod modes

### Environment

  System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.1
  Browsers:
    Chrome: 91.0.4472.77
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.41)
  npmPackages:
    gatsby: ^3.6.2 => 3.7.1

**Comment by Atsushi-Haba** [comment]
It seems to redirect from `~~/test` to `~~/test/` when reload page
