### ISSUE TITLE
Change to svgo config in #31620 removes attributes from SVGs in CSS

### ISSUE THREAD

**Issue by bwlng** [gatsbyjs/gatsby#31876]
## Description

The change to the the svgo config in #31620 removes the `xmlns` attribute and dimension attributes from SVGs inlined in CSS. In my testing, removing the `xmlns` attribute prevents the SVG from displaying.

### Steps to reproduce

I created a test case [here](https://github.com/bwlng/gatsby-svgo-issue/tree/v3.7.1) that includes [styles](https://github.com/bwlng/gatsby-svgo-issue/blob/main/src/css/styles.css) for an inline SVG for list item bullets.

* Run `npm run build && npm run serve` on the [main branch (3.6.2)](https://github.com/bwlng/gatsby-svgo-issue/tree/main) and visit the homepage, you'll see teal list item bullets
* Run `npm run build && npm run serve` on the [v3.7.1 branch](https://github.com/bwlng/gatsby-svgo-issue/tree/v3.7.1) and the bullets won't appear. Inspect the `li::before` element in both branches and you'll see the svg attributes are different

If I edit `node_modules/gatsby/dist/utils/webpack-utils.js`  and remove `removeDimensions` and `removeXMLNS` from the svgo/minifyCss config it works again on 3.7.1. 

### Expected result

List item bullets should appear as teal SVGs

### Actual result

List item bullets do not appear on the homepage because the `xmlns` attribute is missing.

Is there a straightforward way to specify my own settings for svgo or minifyCSS to workaround this?

### Environment

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.17.0 - ~/.nvm/versions/node/v12.17.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.17.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 91.0.4472.101
    Edge: 91.0.864.41
    Firefox: 83.0
    Safari: 14.1.1
  npmPackages:
    gatsby: ^2.32.11 => 3.6.0 
    gatsby-image: ^2.4.6 => 3.7.1 
    gatsby-plugin-algolia: ^0.11.1 => 0.20.1 
    gatsby-plugin-manifest: ^2.4.10 => 3.7.1 
    gatsby-plugin-meta-redirect: ^1.1.1 => 1.1.1 
    gatsby-plugin-netlify: ^2.3.4 => 3.7.1 
    gatsby-plugin-postcss: ^3.5.0 => 4.7.1 
    gatsby-plugin-react-helmet: ^3.3.3 => 4.7.1 
    gatsby-plugin-react-helmet-canonical-urls: ^1.3.0 => 1.4.0 
    gatsby-plugin-sharp: ^2.6.10 => 3.7.1 
    gatsby-plugin-sitemap: ^2.4.4 => 3.3.0 
    gatsby-plugin-styled-components: ^3.3.3 => 4.7.1 
    gatsby-source-filesystem: ^2.3.10 => 3.7.1 
    gatsby-transformer-sharp: ^2.5.4 => 3.7.1

**Comment by DavidRouyer** [comment]
This is the same issue as https://github.com/gatsbyjs/gatsby/issues/31878 and you can take a look at my workaround here https://github.com/gatsbyjs/gatsby/issues/31878#issuecomment-860578064

**Comment by bwlng** [comment]
Thanks @DavidRouyer. Can confirm that your workaround addresses the issue.
