### ISSUE TITLE
WPGatsby Preview not working as expected

### ISSUE THREAD

**Issue by bogdancss** [gatsbyjs/gatsby#31897]
Hey,

I am using `Gatsby Cloud` and have `Preview` setup correctly (all fields filled in in `WPGatsby`, preview enabled and started in `Gatsby cloud`, id being passed to context in `gatsby-node`). The `Preview Instance` url filled in `WPGatsby` is smth like this `https://preview-test.gtsb.io` however, then I press the `Preview` button on a post in WordPress, I am being redirected to a url like this `https://test.com/blog/post-name/?preview_id=21576&preview_nonce=6338660213&preview=true` - so no like the preview instance.

I am running the latest versions of all plugins.

Would appreciate help - thank you!

**Comment by LekoArts** [comment]
Hi!

For Gatsby Cloud support please head here: https://www.gatsbyjs.com/support/

Thanks!
