### ISSUE TITLE
[gatsby-plugin-netlify-cms] Global styles not confined to preview pane

### ISSUE THREAD

**Issue by jcoryalvernaz** [gatsbyjs/gatsby#31909]
## Description

Possibly related to [#20428](https://github.com/gatsbyjs/gatsby/issues/20428). When importing a global style sheet into `cms.js` the styles are applied to the entire app instead of just the preview pane. This issue appears to be different from the above-linked issue, as this is present in development and production.

This is what my `cms.js` config looks like with the imported stylesheet:
```
import CMS from 'netlify-cms-app';
import DocsPreview from './preview-templates/DocsPreview';
import KnowledgeBasePostPreview from './preview-templates/KnowledgeBasePostPreview';

import '../styles/global.scss';

CMS.registerPreviewTemplate('api_docs', DocsPreview);
CMS.registerPreviewTemplate('data_pipeline_docs', DocsPreview);
CMS.registerPreviewTemplate('integration_docs', DocsPreview);
CMS.registerPreviewTemplate('post', KnowledgeBasePostPreview);
```

Screenshot showing styles applied to app instead of just on the preview pane:
<img width="1355" alt="Content Manager 2021-06-14 14-16-33" src="https://user-images.githubusercontent.com/38389357/121961889-d4543980-cd1c-11eb-8fb7-cff1a0730ad7.png">

### Steps to reproduce

Import a style sheet in the `cms.js` config and see the styles applied to the app instead of confined to the preview pane.

### Expected result

Styles should only be applied to the preview pane.

### Actual result

The stylesheet is applied to the entire app instead of the preview pane.

### Environment

```
  System:
    OS: Linux 5.10 Alpine Linux
    CPU: (8) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.1.0 - /bin/bash
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
  npmPackages:
    gatsby: ^3.7.0 => 3.7.0 
    gatsby-cli: ^3.7.0 => 3.7.0 
    gatsby-image: ^3.3.0 => 3.7.0 
    gatsby-plugin-algolia: ^0.19.0 => 0.19.0 
    gatsby-plugin-amplitude-analytics: ^3.2.0 => 3.2.0 
    gatsby-plugin-catch-links: ^3.7.0 => 3.7.0 
    gatsby-plugin-google-gtag: ^3.7.0 => 3.7.0 
    gatsby-plugin-google-tagmanager: ^3.7.0 => 3.7.0 
    gatsby-plugin-image: ^1.7.1 => 1.7.1 
    gatsby-plugin-layout: ^2.7.0 => 2.7.0 
    gatsby-plugin-manifest: ^3.7.0 => 3.7.0 
    gatsby-plugin-netlify-cms: ^5.7.0 => 5.7.0 
    gatsby-plugin-offline: ^4.7.0 => 4.7.0 
    gatsby-plugin-printer: ^1.1.1 => 1.1.1 
    gatsby-plugin-react-helmet: ^4.7.0 => 4.7.0 
    gatsby-plugin-remove-trailing-slashes: ^3.7.0 => 3.7.0 
    gatsby-plugin-resolve-src: ^2.1.0 => 2.1.0 
    gatsby-plugin-robots-txt: ^1.5.5 => 1.6.2 
    gatsby-plugin-sass: ^4.7.0 => 4.7.0 
    gatsby-plugin-sharp: ^3.7.0 => 3.7.0 
    gatsby-plugin-sitemap: ^4.3.0 => 4.3.0 
    gatsby-remark-copy-linked-files: ^4.4.0 => 4.4.0 
    gatsby-remark-prismjs: ^5.4.0 => 5.4.0 
    gatsby-source-filesystem: ^3.7.0 => 3.7.0 
    gatsby-source-marketo: ^1.0.2 => 1.0.2 
    gatsby-transformer-json: ^3.7.0 => 3.7.0 
    gatsby-transformer-remark: ^4.4.0 => 4.4.0 
    gatsby-transformer-sharp: ^3.7.0 => 3.7.0 
```

**Comment by LekoArts** [comment]
cc @erezrokah @ascorbic

**Comment by erezrokah** [comment]
Thanks for the tag @LekoArts!

@jcoryalvernaz can you share a public repo reproducing issue? That will make it much easier to debug and also to confirm we're fixing the same issue you're experiencing

**Comment by jcoryalvernaz** [comment]
@erezrokah Here is a [repo](https://github.com/jcoryalvernaz/netlify-cms-issue-reproduction) that reproduces the issue. It is setup with the `local_backend` so you can see the issue locally. Let me know if you need anything else. Thanks

**Comment by erezrokah** [comment]
Looks like we need to do this:
https://github.com/gatsbyjs/gatsby/blob/069cb535fa5bf5d2eead31533be18b1fe64c2568/packages/gatsby-plugin-netlify-cms/src/gatsby-node.js#L201

I'll try to use the skip assets plugin and see if that works.

**Comment by erezrokah** [comment]
Hit a bug with the new plugin, see https://github.com/swimmadude66/html-webpack-skip-assets-plugin/pull/7

I have a workaround and will submit a PR soon.
