### ISSUE TITLE
Automatic support for many-to-many fields through linked node creation in source plugins

### ISSUE THREAD

**Issue by flmuel** [gatsbyjs/gatsby#3190]
So in the last few days I tried to get only Wordpress posts with a passed variable (id of a category)...
I am creating category sites in gatsby-node, which uses my category template.

Is there a simple way in GraphQL to filter after categories with this plugin?
Categories is the only node which is not selectable in the GraphiQL Editor...

```my Query
{
  allWordpressPost(filter: {categories is not here}) {
    edges {
      node {
        id
        categories {
          id
        }
      }
    }
  }
}
```

**Comment by calcsam** [comment]
This is a limitation of how you can query many-to-many fields in GraphQL with Gatsby -- we don't automatically create two-way links between nodes pulled in by plugins. 

This would be a bit of a complicated PR and should happen in gatsby core rather than the Wordpress source plugin; feel free to dive in if you'd like. 

https://github.com/gatsbyjs/gatsby/blob/57f7b0d372a7461f019ce86a9003371d45204f3b/packages/gatsby/src/schema/build-node-connections.js

**Comment by loremipson** [comment]
This is a pretty big limitation that we just ran into as well. Just being a second voice for now.

**Comment by KyleAMathews** [comment]
Would love to help someone through a PR to add support for filtering on linked nodes 👍

**Comment by alvinthen** [comment]
I'd love to help on supporting filtering on linked nodes, would be great to point me to where to start  in Gatsby, I can work my way on GraphQL

**Comment by KyleAMathews** [comment]
@alvinthen sweet! That'd be a huge help. 

The two files you'll be working in are:

* https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/infer-graphql-input-fields.js
* https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/__tests__/infer-graphql-input-type-test.js

This line in particular is where the action should happen https://github.com/gatsbyjs/gatsby/blob/c0c4bb795ddd2a41fa5f5320c2154ff439a9baed/packages/gatsby/src/schema/infer-graphql-input-fields.js#L204

Adding support for `___NODE` style links is step 1 as it's the most common way of linking. There are two other main ones — links to files are automatically created as well + people can manually create links in their gatsby-config.js. An initial PR could focus just on supporting `___NODE` however.

**Comment by KyleAMathews** [comment]
@alvinthen fixed this! Thanks!

**Comment by flmuel** [comment]
@KyleAMathews reopen?
