### ISSUE TITLE
Gatsby HMR very slow with postcss + tailwind

### ISSUE THREAD

**Issue by leroynas** [gatsbyjs/gatsby#31927]
## Description

We've upgraded our project to gatsby v3, after the upgrade the re-building of the project took about 50 seconds every time, before this was not the case (0.5-1s). After some investigation, I concluded that all CSS files are processed every time with either gatsby-plugin-sass or gatsby-plugin-postcss. We make use of tailwind and tailwind takes quite some time to process everything (adding up to 50s). 

### Steps to reproduce

- create gatsby project with postcss
- install tailwind + add config
- add some css files making use of tailwind
- or just use my [repo](https://github.com/leroynas/gatsby-bug) ;)
- start develop mode
- change some code (even adding a space in a js file will trigger the full css processing)
- watch the console log

### Expected result

Building takes < 1-3s

### Actual result

Building takes a long time.

### Environment

```
  System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.15.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 91.0.4472.101
    Safari: 14.0.2
  npmPackages:
    gatsby: ^3.6.2 => 3.7.1
    gatsby-plugin-postcss: ^4.7.1 => 4.7.1
```

**Comment by KyleAMathews** [comment]
Perhaps you have the same issue as https://github.com/gatsbyjs/gatsby/discussions/31479#discussioncomment-844535 ?

**Comment by leroynas** [comment]
> Perhaps you have the same issue as [#31479 (comment)](https://github.com/gatsbyjs/gatsby/discussions/31479#discussioncomment-844535) ?

I was able to reproduce the issue by simply following these steps:

- Create new gatsby project
- Install postcss plugin
- Install Tailwind
- Configure tailwind
- Adding CSS files

I didn't have any workspace dependencies configured, so I don't see how this can be related to the issue you're referring to.

**Comment by leroynas** [comment]
Seemed like my reproduction repo didn't start because the postcss version was too new. I decreased it to version 7 and it works now. The bug is still there. Reloading after a code change takes about +/- 3s, instead of <1s.
