### ISSUE TITLE
[gatsby-remark-external-links] Doesn't work on reference style link

### ISSUE THREAD

**Issue by blazeu** [gatsbyjs/gatsby#3194]
With
```md
This is [GatsbyJS][ref] link

[ref]: https://www.gatsbyjs.org
```
The resulting HTML will be

```html
This is <a href="https://www.gatsbyjs.org">GatsbyJS</a> link
```

No attribute added, while the normal style (`[]()`) works as expected.

**Comment by KyleAMathews** [comment]
Looks like you want to post your issue on https://github.com/JLongley/gatsby-remark-external-links `gatsby-remark-external-links` isn't hosted here.
