### ISSUE TITLE
Gatsby v3 - Plugins and Dependencies causing issues in Legacy Browsers

### ISSUE THREAD

**Issue by joe-glasgow** [gatsbyjs/gatsby#31952]
### Description
Certain plugins are now using es6 syntax as standard and no longer perform es2015 transpilation.

For example in Postcss 8 (used by Gatsby v3) its dependency nanoid now uses arrow syntax (breaking ie11 and iOS9)
https://github.com/ai/nanoid/blob/main/index.browser.js

Previously in v2 this wasn't an issue:
https://github.com/ai/nanoid/blob/2.1.11/index.browser.js

Similarly Gatsby Plugin Image is setting an arrow function as a string as part of its render, which will of course completely miss any transpilation: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-image/src/gatsby-ssr.tsx#L67

### Steps to reproduce
Create a Gatsby v3 Project

Use gatsby-plugin-material-ui - see output javascript has arrow syntax breaking ie11/iOS9

Use Gatsby-Plugin-Image - see output javascript has arrow syntax breaking ie11 / iOS9

e.g.

```
e.exports={nanoid:(e=21)=>{let t="",n=e;for(;n--;)t+="ModuleSymbhasOwnPr- 
   0123456789ABCDEFGHNRVfgctiUvz_KqYTJkLxpZXIjQW"[64*Math.random()|0];return t},customAlphabet:(**e,t)=>()=>**{
...
```

### Expected result
What should happen?

Gatsby v3 - including dependencies should be transpiled to be compatible with ie11 as per: https://www.gatsbyjs.com/docs/how-to/custom-configuration/browser-support/

### Actual result
Sites break using these plugins and metods

### Environment
System:
OS: macOS 10.15.3
CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
Shell: 5.7.1 - /bin/zsh
Binaries:
Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.0/bin/yarn
npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
Languages:
Python: 2.7.16 - /usr/bin/python
Browsers:
Chrome: 91.0.4472.106
Firefox: 88.0.1
Safari: 13.0.5
npmGlobalPackages:
gatsby: 3.7.1

**Comment by TMUND** [comment]
@joe-glasgow Were you able to reach any resolution on the above? 

We need to support IE11 and are seeing issues like `Page resources not found for /foo/bar. Not rendering React` and `Unhandled Promise rejection ReferenceError: 'Proxy' is undefined`. We haven't had any luck polyfilling for Proxy nor identifying where exactly the issues are cropping up from, next step is to start turning plugins off one by one.

**Comment by garethterrace** [comment]
Seeing the same issue with Gatsby V3 and transpilation seeming to not work correctly: 
![image](https://user-images.githubusercontent.com/7371188/127481852-57526cb9-fd88-4e6b-a3c4-ca0cb22a48f1.png)

Even with browserslist config set to include IE11 it's still failing.  Any help/updates appreciated!

**Comment by TMUND** [comment]
@garethterrace Try polyfilling manually. Worked for me with a similar warning for Proxy

**Comment by LekoArts** [comment]
`gatsby-plugin-image` is not an issue as it's wrapped with `type: "module"`. We're transpiling `node_modules` so  not sure why it doesn't work with the plugins you tried.

We don't have time to look into this further at the moment but you should check why the transpilation of `node_modules` doesn't work.
