### ISSUE TITLE
Using YML files as Markdown

### ISSUE THREAD

**Issue by exrishu** [gatsbyjs/gatsby#3195]
Hi , I am new to Gatsby trying to port my website from hugo to gatsby,  But am stuck in , that how to change the YML files into markdown, In hugo there is an awesome property  

> |markdownify 

which easily convert yml into markdown and we can also use some HTML tags inside it. 
Is there is any way I can convert ?

**Comment by calcsam** [comment]
Gatsby can take in YAML input if you want. Take a look at:

https://gatsbyjs.github.io/gatsby-starter-kitchen-sink/yaml/

https://www.gatsbyjs.org/blog/2017-11-06-migrate-hugo-gatsby/

**Comment by KyleAMathews** [comment]
For converting markdown fields in frontmatter, this would be a useful pattern to support. We'd be open to a PR adding this to [gatsby-transformer-remark](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-remark).

**Comment by exrishu** [comment]
@calcsam Thanks for your help, but I think think is not the answer of my question, I am able to pull data from YML files successfully, I want data to be in YML file and convert it to markdown

**Comment by exrishu** [comment]
@KyleAMathews I guess gatsby-transformer-remark will not recognize the file having YML extension.

**Comment by KyleAMathews** [comment]
Oh sorry, you want gatsby-transformer-yaml.

If you haven't yet, try going through the official tutorial.

**Comment by exrishu** [comment]
@KyleAMathews CheckOut this link `[issue-2817](https://github.com/gatsbyjs/gatsby/issues/2817)` . I am also facing exactly the same problem. Is there is any another way to solve this issue?

**Comment by KyleAMathews** [comment]
This isn't supported right now — so either you can write custom code as described in that issue for handling the markdown or you can put together a PR to add support.

**Comment by exrishu** [comment]
Thanks, Gonna try the custom code ...I

**Comment by calcsam** [comment]
Closing this issue as it's contained in the linked issue.

**Comment by avinashs735** [comment]
I am  getting the same kind of problem, I am able to pull the contents of yaml using gatsby-transformer-yaml  but all pulled data is rendered as plain text ,If i enter any html tag or any url it is rendered as plain text only.Is there any way that I can markdownify this yaml while using it in gatsby so that I dont get all as plain text only?

**Comment by jlengstorf** [comment]
@avinashs735 in that case you may want to use a third-party component like https://github.com/rexxars/react-markdown
