### ISSUE TITLE
className doesn't exist on gatsby-link TypeScript types

### ISSUE THREAD

**Issue by ahstro** [gatsbyjs/gatsby#3197]
## Description

I've been converting some modules that use `gatsby-link` to TypeScript, but when I did, tsc started complaining that `Property 'className' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<GatsbyLink> & Readonly<{ children?: ReactNode; }>`.
Using `className` worked before, so it's just a problem with the TypeScript declaration files.

### Environment

Gatsby version: 1.9.119
Gatsby-link version: 1.6.31
Node.js version: v9.2.1
Operating System: Arch Linux 4.14.4-1-ARCH

### Actual result

TypeScript complained about `className` not existing on `gatsby-link`.

### Expected behavior

TypeScript shouldn't complain.

### Steps to reproduce

1\. Use `gatsby-plugin-typescript`

2\. Try to use the `className` prop on a `gatsby-

**Comment by ahstro** [comment]
Wow, that was quick. Thanks! 🙌

**Comment by h3d0** [comment]
Getting the same problem again:

![image](https://user-images.githubusercontent.com/7346327/44330197-11b1f300-a46f-11e8-9a50-933b315a95f4.png)

"gatsby": "^2.0.0-beta.111",
"gatsby-plugin-typescript": "^2.0.0-beta.9",
