### ISSUE TITLE
Gatsby cannot fetch a new contentful field via GraphQL suddenly

### ISSUE THREAD

**Issue by xunjing-liyuan** [gatsbyjs/gatsby#31978]
## Description

I was adding a new field into my one of my contentful model and published it. I was working on my gatsby project when I first built and published my project. But now I got error message which is showing as below.
![image](https://user-images.githubusercontent.com/75966889/122513579-278bfc00-d03d-11eb-85c0-b7e6ecc182ac.png)
"promotionPrice" is the field I add, and it was working fine. But after about two weeks, when I updated content of a field on contentful, and tried to rebuild and publish my project(no code changed in my project), I started to get error message during build step.

### Steps to reproduce

I don't have a public repo to share yet, and you can just try to add a new field in your contentful model to reproduce this issue.

### Expected result

GraphQL can fetch my new add field of my contentful model.

### Actual result

GraphQL cannot fetch my new add field of my contentful model.

### Environment

System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.5 - /bin/python
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: support!
Mozilla Firefox 78.9.0esr
  npmPackages:
    gatsby: 2.17.7 => 2.17.7
    gatsby-image: ^2.2.30 => 2.2.30
    gatsby-plugin-canonical-urls: ^2.1.13 => 2.1.13
    gatsby-plugin-google-analytics: ^2.1.23 => 2.1.23
    gatsby-plugin-google-gtag: ^1.0.16 => 1.1.14
    gatsby-plugin-hotjar: ^1.0.1 => 1.0.1
    gatsby-plugin-i18n: ^1.0.1 => 1.0.1
    gatsby-plugin-layout: ^1.1.13 => 1.1.13
    gatsby-plugin-less: ^3.0.12 => 3.0.12
    gatsby-plugin-manifest: 2.2.26 => 2.2.26
    gatsby-plugin-no-sourcemaps: ^2.1.1 => 2.1.1
    gatsby-plugin-nprogress: ^2.1.12 => 2.1.12
    gatsby-plugin-preact: ^3.1.19 => 3.1.19
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.13
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-sharp: 2.2.36 => 2.2.36
    gatsby-plugin-sitemap: ^2.2.19 => 2.2.19
    gatsby-source-contentful: 2.1.54 => 2.1.54
    gatsby-source-filesystem: 2.1.35 => 2.1.35
    gatsby-transformer-csv: ^2.1.15 => 2.1.15
    gatsby-transformer-sharp: 2.3.2 => 2.3.2
  npmGlobalPackages:
    gatsby-cli: 3.6.0

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by xunjing-liyuan** [comment]
Hi, @LekoArts 

Now I'm working on creating a demo to reproduce this issue. At the same time, I noticed that there is another similar issue https://github.com/gatsbyjs/gatsby/issues/13838, and may I ask if this one is fixed, cause I may can apply same approach to solve my issue.

Thanks.
