### ISSUE TITLE
[gatsby v3, gatsby-source-contentful, gatsby-plugin-image migration] resource / documentation / repos

### ISSUE THREAD

**Issue by ShahAnuj2610** [gatsbyjs/gatsby#31981]
### Discussed in https://github.com/gatsbyjs/gatsby/discussions/31924

<div type='discussions-op-text'>

<sup>Originally posted by **ShahAnuj2610** June 15, 2021</sup>
Any good resources, documentation or repos where the latest versions of gatsby, gatsby-plugin-image and contentful are used?

We're using it at onequince.com and while migrating ran into some weird issues.

I want to migrate it seamlessly.</div>

**Comment by LekoArts** [comment]
Please stick to your discussion. Thanks!
