### ISSUE TITLE
Gatsby-Plugin-Image doesn't render image on first visit

### ISSUE THREAD

**Issue by quansenB** [gatsbyjs/gatsby#31984]
## Description

When I'm opening my site the first time the image isn't displayed. After refreshing the site, the image shows up.
This behaviour can be seen on: https://gastroenterologen-nuernberg.netlify.app/. 

I've tested this with Chrome and Firefox and the most recent version of gatsby-plugin-image (v. 1.7.1).

It appears as if the image is only served from cache as it also doens't work on reload with cache disabled

### Steps to reproduce

1. Query Image like: 
```
image {
  childImageSharp {
     gatsbyImageData (width: 240)
  }
}
```

2. Use image like: 
```
<GatsbyImage
    image={el.imageObject.image.childImageSharp.gatsbyImageData}
/>
```

3. Build & Serve
4. Open Page
5. (Refresh to see image working)

### Expected result

Image is displayed on first visit

### Actual result

Image doesn't show until site is manually refreshed

### Environment

  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    npm: 7.18.1 - ~/Desktop/Dev/Website-Groepel-Seutter/node_modules/.bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Edge: 91.0.864.53
    Firefox: 88.0.1
    Safari: 14.1.1
  npmPackages:
    gatsby: ^3.7.2 => 3.7.2
    gatsby-cli: ^3.7.1 => 3.7.1
    gatsby-plugin-google-tagmanager: ^3.7.1 => 3.7.1
    gatsby-plugin-image: ^1.7.1 => 1.7.1
    gatsby-plugin-manifest: ^3.7.1 => 3.7.1
    gatsby-plugin-minify-html: ^1.0.4 => 1.0.4
    gatsby-plugin-netlify: ^3.7.1 => 3.7.1
    gatsby-plugin-netlify-cache: ^2.0.0 => 2.0.0
    gatsby-plugin-netlify-cms: ^5.7.1 => 5.7.1
    gatsby-plugin-offline: ^4.7.1 => 4.7.1
    gatsby-plugin-postcss: ^4.7.1 => 4.7.1
    gatsby-plugin-preact: ^5.7.1 => 5.7.1
    gatsby-plugin-preload-fonts: ^2.7.1 => 2.7.1
    gatsby-plugin-react-helmet: ^4.7.1 => 4.7.1
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-robots-txt: ^1.6.2 => 1.6.2
    gatsby-plugin-scroll-reveal: 0.0.7 => 0.0.7
    gatsby-plugin-sharp: ^3.7.1 => 3.7.1
    gatsby-plugin-sitemap: ^4.3.1 => 4.3.1
    gatsby-plugin-svgr: ^3.0.0-beta.0 => 3.0.0-beta.0
    gatsby-remark-images: ^5.4.1 => 5.4.1
    gatsby-remark-relative-images-v2: ^0.1.5 => 0.1.5
    gatsby-source-filesystem: ^3.7.1 => 3.7.1
    gatsby-transformer-remark: ^4.4.1 => 4.4.1
    gatsby-transformer-sharp: ^3.7.1 => 3.7.1

**Comment by ardiewen** [comment]
Your netlify site is showing this in the console:

```
[gatsby-plugin-image] You're missing out on some cool performance features. Please add "gatsby-plugin-image" to your gatsby-config.js
```

Have you checked that you've added the plugin to gatsby-config?

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by quansenB** [comment]
> Your netlify site is showing this in the console:
> 
> ```
> [gatsby-plugin-image] You're missing out on some cool performance features. Please add "gatsby-plugin-image" to your gatsby-config.js
> ```
> 
> Have you checked that you've added the plugin to gatsby-config?

Good catch, this solved the issue for me. Thank you :)
