### ISSUE TITLE
TypeError: Failed to fetch when using gatsbyImageData with gatsby v3 and gatsby-source-contentful v5.7.1

### ISSUE THREAD

**Issue by ShahAnuj2610** [gatsbyjs/gatsby#31992]
## Description
getting this error in Gatsby GraphiQL server when running this query
```
query MyQuery {
  contentfulHomePage(
    id: {eq: "xxx"}
  ) {
    socialPhotosHomePage {
      id
      image {
        id
        fluid: gatsbyImageData(layout: CONSTRAINED, width: 960)
      }
    }
  }
}

```

```json
{
  "message": "Failed to fetch",
  "stack": "TypeError: Failed to fetch"
}
```

### Steps to reproduce
Run any query for contentful graphql image with and without `gatsbyImageData`
#### this will work
```
query MyQuery {
  contentfulHomePage(
    id: {eq: "xxx"}
  ) {
    socialPhotosHomePage {
      id
      image {
        id
      }
    }
  }
}
```
#### this will not work
```
query MyQuery {
  contentfulHomePage(
    id: {eq: "xxx"}
  ) {
    socialPhotosHomePage {
      id
      image {
        id
        fluid: gatsbyImageData(layout: CONSTRAINED, width: 960)
      }
    }
  }
}
```

### Expected result
query should successfully run as was in `gatsby v2`

### Actual result

got error

### Environment

```

  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.7.0 - /usr/local/bin/npm
  Languages:
    Python: 3.8.8 - /Users/anujshah/opt/anaconda3/bin/python
  Browsers:
    Chrome: 91.0.4472.106
    Firefox: 88.0.1
    Safari: 14.1.1
  npmPackages:
    gatsby: ^3.7.1 => 3.7.2 
    gatsby-core-utils: ^2.7.1 => 2.7.1 
    gatsby-plugin-google-analytics: ^3.7.1 => 3.7.1 
    gatsby-plugin-image: ^1.7.1 => 1.7.1 
    gatsby-plugin-manifest: ^3.7.1 => 3.7.1 
    gatsby-plugin-nprogress: ^3.7.1 => 3.7.1 
    gatsby-plugin-polyfill-io: ^1.1.0 => 1.1.0 
    gatsby-plugin-portal: ^1.0.7 => 1.0.7 
    gatsby-plugin-react-helmet: ^4.7.1 => 4.7.1 
    gatsby-plugin-react-svg: ^3.0.1 => 3.0.1 
    gatsby-plugin-robots-txt: ^1.6.2 => 1.6.2 
    gatsby-plugin-sentry: ^1.0.1 => 1.0.1 
    gatsby-plugin-sharp: ^3.7.1 => 3.7.1 
    gatsby-plugin-sitemap: ^4.3.1 => 4.3.1 
    gatsby-plugin-styled-components: ^4.7.1 => 4.7.1 
    gatsby-plugin-use-query-params: ^1.0.1 => 1.0.1 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.22 => 1.1.22 
    gatsby-source-contentful: ^5.7.1 => 5.7.1 
    gatsby-transformer-sharp: ^3.7.1 => 3.7.1 
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by ShahAnuj2610** [comment]
I'm not able to replicate with few number of contents on contentful.

I think it may be happening due to this warning. It gets stuck at 33% and not moving forward.

![](https://i.imgur.com/mqiZpxP.png)

When I remove this query on `HomePage.js`, the development bundle is built.

PS: this same warning I get on gatsby: v2 and gatsby-source-contentful: 2.3.1, but there the query doesn't get stuck and development bundle is built.
