### ISSUE TITLE
Development server 404s on first visit for pages which definitely exist

### ISSUE THREAD

**Issue by FraserThompson** [gatsbyjs/gatsby#32016]
## Description

After upgrading from Gatsby 2 to 3 my build works and all the pages exist, but the development server is behaving strangely:

* First visit of pages generated via createPage() in gatsby-node.js returns a 404
* Second visit shows the page
* If I then navigate to another generated page, it forgets the first one and 404s again until the second visit

All the while the 404 page is showing me my list of pages and the page I'm trying to visit is definitely in that list: 

![404 page](https://user-images.githubusercontent.com/6093858/122885374-24717280-d393-11eb-9fc6-88c232c2cb47.JPG)

### Steps to reproduce

I'm not sure because I'm not sure what's causing this, but here's a fairly minimal reproduction: https://github.com/FraserThompson/dunedinsound-gatsby-minimal-test

### Expected result

The dev server should not 404 on pages which exist.

### Actual result

The dev server 404s on pages which exist.

### Environment

 System:
    OS: Windows 10
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
  Binaries:
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.5 - /c/Users/Fraser/AppData/Local/Programs/Python/Python37/python
  Browsers:
    Edge: 44.19041.1023.0
  npmPackages:
    gatsby: ^3.7.2 => 3.7.2
    gatsby-image: ^3.7.1 => 3.7.1
    gatsby-parallel-runner: ^1.3.0 => 1.3.0
    gatsby-plugin-emotion: ^6.7.1 => 6.7.1
    gatsby-plugin-google-analytics: ^3.7.1 => 3.7.1
    gatsby-plugin-manifest: 3.7.1 => 3.7.1
    gatsby-plugin-react-helmet: ^4.7.1 => 4.7.1
    gatsby-plugin-react-leaflet: ^3.0.2 => 3.0.2
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-s3: ../gatsby-plugin-s3 => 0.3.3
    gatsby-plugin-sharp: 3.7.1 => 3.7.1
    gatsby-plugin-typography: ^3.7.1 => 3.7.1
    gatsby-remark-copy-linked-files: ^4.4.1 => 4.4.1
    gatsby-remark-images: ^5.4.1 => 5.4.1
    gatsby-remark-smartypants: ^4.4.1 => 4.4.1
    gatsby-source-filesystem: ^3.7.1 => 3.7.1
    gatsby-transformer-remark: ^4.4.1 => 4.4.1
    gatsby-transformer-sharp: 3.7.1 => 3.7.1

(followed by a bunch of 'Error: The system cannot find the path specified.' related stuff for some reason)

**Comment by FraserThompson** [comment]
Turns out this is because I was importing Link directly from Reach router for some reason (like this `import { Link as RouterLink } from '@reach/router'`) and I guess the development server didn't know how to handle that as far as hot reloading went? Not sure what changed between version 2 and 3, but this can be closed since it was because I was doing something non-standard and not an issue with Gatsby at all!

**Comment by rodikh** [comment]
This reproduces for me but when using:
`import { Link as GatsbyLink } from "gatsby";`
