### ISSUE TITLE
Wrong data when using `useStaticQuery`

### ISSUE THREAD

**Issue by llamerr** [gatsbyjs/gatsby#32028]
So I have `gatsby-node.js` which generates pages like this:
```
const result = await graphql(
    `
      {
        articles: allContentfulWork {
          edges {
            node {
              slug
              id
            }
          }
        }
      }
    `
  )
...
const workTemplate = path.resolve('./src/templates/Work/index.tsx')
...
articles.forEach(({ node }) => {
    createPage({
      path: `/page/${node.slug}`,
      component: workTemplate,
      context: {
        id: node.id,
      },
    })
  })
```

then in template I have this for gql:

```
export const query = graphql`
query WorkPageQuery($id: String) {
  article: contentfulWork(id: {eq: $id}) {
    slug
...
```

and this for page:
```
const WorkTemplate: FC<unknown> = (params): ReactElement => {
  console.log(params)
  const { article } = useStaticQuery(query);
```

logged data shows that id provided by `gatsby-node.js` with `pageContext` is correct, and when queried through http://localhost:8000/___graphql it returns correct data, but when I look into `article` result, or inside `pageResources. staticQueryResults` I can find only wrong data for that query

### Environment
gatsby info --clipboard

  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.15.1 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 91.0.4472.106
    Firefox: 89.0.1
    Safari: 14.1.1
  npmPackages:
    gatsby: ^3.3.1 => 3.6.2
    gatsby-plugin-image: ^1.6.0 => 1.6.0
    gatsby-plugin-manifest: ^3.6.0 => 3.6.0
    gatsby-plugin-offline: ^4.2.0 => 4.6.0
    gatsby-plugin-react-helmet: ^4.2.0 => 4.6.0
    gatsby-plugin-sass: ^4.4.0 => 4.6.0
    gatsby-plugin-sharp: ^3.6.0 => 3.6.0
    gatsby-source-contentful: ^5.6.1 => 5.6.1
    gatsby-source-filesystem: ^3.4.0 => 3.6.0
    gatsby-transformer-sharp: ^3.6.0 => 3.6.0
  npmGlobalPackages:
    gatsby-cli: 3.2.0

**Comment by llamerr** [comment]
Tried `gatsby clean` without any success

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by llamerr** [comment]
Actually I know how I'm going to fix this - I will just fetch ALL data like I'm doing in other places and just select that single record manually.
