### ISSUE TITLE
Save data to the Database

### ISSUE THREAD

**Issue by abraztsov** [gatsbyjs/gatsby#3203]
I have a simple input with "subscribe for future updates" form (where you can type your email and submit it). 

### What I want to achieve ?

How to save this email to some BD/Or send yourself on Slack/other variation ?
Does Gatsby provide such functionality ?

**Comment by KyleAMathews** [comment]
Services like MailChimp can handle this. Combine that with a client for e.g. https://github.com/revolunet/react-mailchimp-subscribe

**Comment by abraztsov** [comment]
@KyleAMathews I want to collect users emails that they put into the form  - NOT sent some email with mailchimp!

**Comment by KyleAMathews** [comment]
Check out all the services listed here https://github.com/agarrharr/awesome-static-website-services#forms
