### ISSUE TITLE
gatsby-plugin-gatsby-cloud plugin throwing error in Gatsby Cloud

### ISSUE THREAD

**Issue by LinnJS** [gatsbyjs/gatsby#32042]
## Description
When merging a seemly unrelated PR this error started popping up in Gatsby Cloud. I reverted the PR and now all my branches on Gatsby Cloud are failing... is this due to some kind of service outage?

![image](https://user-images.githubusercontent.com/23741323/123002542-05b5b080-d380-11eb-97dd-637fad9f1bfc.png)

### Steps to reproduce

Steps to reproduce are hard since this error erroneously appeared out of nowhere. I reverted PRs and the error is still coming up. I have no idea how to debug. 

### Expected result

Error should not appear in GatsbyCloud or have a path to help debug where the error is occurring in my project if at all.

### Actual result

Gatsby build failed and is pointing to a undefined error of `(0 , _gatsbyTelemetry.captureEvent) is not a function` this error does not happen locally, only happens in GatsbyCloud. 

### Environment

  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.17.0 - ~/.nvm/versions/node/v14.17.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 85.0
    Safari: 14.1.1
  npmPackages:
    gatsby: ^3.7.2 => 3.7.2
    gatsby-background-image: ^1.5.3 => 1.5.3
    gatsby-plugin-env-variables: ^2.1.0 => 2.1.0
    gatsby-plugin-fullstory: ^3.7.1 => 3.7.1
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-google-tagmanager: ^3.7.1 => 3.7.1
    gatsby-plugin-image: ^1.7.1 => 1.7.1
    gatsby-plugin-manifest: ^3.7.1 => 3.7.1
    gatsby-plugin-mdx: ^2.7.1 => 2.7.1
    gatsby-plugin-react-helmet: ^4.7.1 => 4.7.1
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-robots-txt: ^1.6.2 => 1.6.2
    gatsby-plugin-root-import: ^2.0.6 => 2.0.6
    gatsby-plugin-sharp: ^3.7.1 => 3.7.1
    gatsby-plugin-sitemap: ^4.3.1 => 4.3.1
    gatsby-plugin-styled-components: ^4.7.1 => 4.7.1
    gatsby-remark-images: ^5.4.1 => 5.4.1
    gatsby-source-drupal: ^4.7.2 => 4.7.2
    gatsby-source-filesystem: ^3.7.1 => 3.7.1
    gatsby-transformer-json: ^3.7.1 => 3.7.1
    gatsby-transformer-remark: ^4.4.1 => 4.4.1
    gatsby-transformer-sharp: ^3.7.1 => 3.7.1
  npmGlobalPackages:
    gatsby-cli: 3.7.1

**Comment by trevlar** [comment]
I'm also seeing this issue with the PhoneSoap websites build.

**Comment by LinnJS** [comment]
@trevlar glad I am not the only one I have been messing around with the project configs to see if I could figure it out. Added `gatsby-plugin-gatsby-cloud` and removing experimental feature flags but still having failing builds 😭 . Gonna walk away for a bit and check back in the AM. At least the prod sites are still working cause static 🤷‍♂️ .

**Comment by davidfekke** [comment]
I am getting it to when I try to use this plugin.

**Comment by tkatchenko** [comment]
Also getting this on Gatsby Cloud and when building locally with the plugin enabled.

**Comment by tkatchenko** [comment]
Gatsby Cloud automatically injects the plugin but manually installing and enabling `gatsby-plugin-gatsby-cloud@2.7.0` fixed it for me.

**Comment by abhiaiyer91** [comment]
Hi all, these were the related PRs that introduced the issue. 

https://github.com/gatsbyjs/gatsby/pull/31831
https://github.com/gatsbyjs/gatsby/pull/31833

With the release of 3.8 and its related dependencies bumps for `gatsby-telemetry` and `gatsby-plugin-gatsby-cloud` should fix the issue.

If upgrading to 3.8 is not possible for you right now, then installing your own version of `gatsby-plugin-gatsby-cloud` like @tkatchenko did will prevent Gatsby Cloud for installing the latest plugin version.

This was my fault! I am so sorry for the inconvenience! When I had written my PR `captureEvent` did exist :(.

**Comment by KyleAMathews** [comment]
gatsby-plugin-gatsby-cloud@2.8.1 is out with `gatsby-telemetry` as a dependency so this should be solved now. Let us know if there's any other troubles!
