### ISSUE TITLE
gatsby-source-drupal: RequestError: urlToHttpOptions is not a function

### ISSUE THREAD

**Issue by Vacilando** [gatsbyjs/gatsby#32043]
After upgrading to Gatsby v3.8 all our Gatsby sites sourcing from Drupal 8 fail with "RequestError: urlToHttpOptions is not a function".

Here's the relevant section of the build log:

```
11:39:16 PM: success createSchemaCustomization - 0.005s
11:39:16 PM: error urlToHttpOptions is not a function
11:39:16 PM: 
11:39:16 PM: 
11:39:16 PM:   RequestError: urlToHttpOptions is not a function
11:39:16 PM:   
11:39:16 PM:   - index.js:1177 Request._makeRequest
11:39:16 PM:     [repo]/[gatsby-source-drupal]/[got]/dist/source/core/index.js:1177:19
11:39:16 PM:   
11:39:16 PM:   - index.js:328 
11:39:16 PM:     [repo]/[gatsby-source-drupal]/[got]/dist/source/core/index.js:328:17
11:39:16 PM:   
11:39:16 PM:   - auto.js:97 module.exports
11:39:16 PM:     [repo]/[http2-wrapper]/source/auto.js:97:11
11:39:16 PM:   
11:39:16 PM:   - index.js:1124 Request._makeRequest
11:39:16 PM:     [repo]/[gatsby-source-drupal]/[got]/dist/source/core/index.js:1124:43
11:39:16 PM:   
11:39:16 PM:   - index.js:328 
11:39:16 PM:     [repo]/[gatsby-source-drupal]/[got]/dist/source/core/index.js:328:28
11:39:16 PM:   
11:39:16 PM: 
11:39:16 PM: not finished source and transform nodes - 0.128s
11:39:16 PM: failed Fetch incremental changes from Drupal - 0.042s
```

**Comment by KyleAMathews** [comment]
Did you install the latest `gatsby-source-drupal` as well? We released a new version of that.

It looks possibly like an install error actually. `urlToHttpOptions` is from https://github.com/szmarczak/http2-wrapper which was just added to the source plugin in https://github.com/gatsbyjs/gatsby/pull/32012

**Comment by Vacilando** [comment]
I was previously on an up-to-date 3.7. 
I upgraded using npm update. Several plugins got updated, including gatsby-source-drupal to version 4.8.0.

**Comment by KyleAMathews** [comment]
Can you try removing your lock file and node_modules and reinstalling? I couldn't reproduce this just now.

**Comment by Vacilando** [comment]
Just did. Same result, this is from a local build:

```
success onPreBootstrap - 0.253s
success createSchemaCustomization - 0.008s

 ERROR 

urlToHttpOptions is not a function



  RequestError: urlToHttpOptions is not a function
  
  - index.js:1177 Request._makeRequest
    [www-vacilando-org]/[gatsby-source-drupal]/[got]/dist/source/core/index.js:1177:19
  
  - auto.js:97 module.exports
    [www-vacilando-org]/[http2-wrapper]/source/auto.js:97:11
  
  - index.js:1124 Request._makeRequest
    [www-vacilando-org]/[gatsby-source-drupal]/[got]/dist/source/core/index.js:1124:43
  
  - index.js:328 
    [www-vacilando-org]/[gatsby-source-drupal]/[got]/dist/source/core/index.js:328:28
  
  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5
  

not finished source and transform nodes - 0.184s
failed Fetch incremental changes from Drupal - 0.053s
```

**Comment by KyleAMathews** [comment]
Can you verify http2-wrapper is installed? Maybe try grepping your node_modules for `urlToHttpOptions`?

Puzzled.

**Comment by Vacilando** [comment]
Yep, `urlToHttpOptions` found in node_modules in the following files:

- http.d.ts
- auto.js
- client-request.js

Look, it may be some freak complication in my setup. These are existing sites. 
I did not and now cannot test it on a fresh setup.
Let's see whether other people bump into this problem, maybe it will get clearer.

**Comment by LinnJS** [comment]
This error was coming up for me as well when trying to debug this [issue](https://github.com/gatsbyjs/gatsby/issues/32042) over here they may or may not be related. Have been messing around with all kinds of stuff to fix my broken builds.

**Comment by KyleAMathews** [comment]
Oh drat — this is a node.js built-in API that was only added in Node 15 — I was testing on Node 16. So we'll need to revert this https://nodejs.org/api/url.html#url_url_urltohttpoptions_url or make it optional
