### ISSUE TITLE
Spoiled inlined to scss svg after build

### ISSUE THREAD

**Issue by Scorpovi4** [gatsbyjs/gatsby#32058]
## Description
I've inlined svg to SASS and uses it as backgroundbut after ` npm run build` they're spoiled! In develop mode everything is okay.

source SVG 
`data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512'%3E%3Ctitle%3EHTML5 Logo%3C/title%3E%3Cpath fill='%23fff' d='M108.4 0h23v22.8h21.2V0h23v69h-23V46h-21v23h-23.2M206 23h-20.3V0h63.7v23H229v46h-23M259.5 0h24.1l14.8 24.3L313.2 0h24.1v69h-23V34.8l-16.1 24.8l-16.1-24.8v34.2h-22.6M348.7 0h23v46.2h32.6V69h-55.6'/%3E%3Cpath fill='%23e44d26' d='M107.6 471l-33-370.4h362.8l-33 370.2L255.7 512'/%3E%3Cpath fill='%23f16529' d='M256 480.5V131H404.3L376 447'/%3E%3Cpath fill='%23ebebeb' d='M142 176.3h114v45.4h-64.2l4.2 46.5h60v45.3H154.4M156.4 336.3H202l3.2 36.3 50.8 13.6v47.4l-93.2-26'/%3E%3Cpath fill='%23fff' d='M369.6 176.3H255.8v45.4h109.6M361.3 268.2H255.8v45.4h56l-5.3 59-50.7 13.6v47.2l93-25.8'/%3E%3C/svg%3E`

SVG after build
 `data:image/svg+xml;charset=utf-8,%3Csvg viewBox='0 0 512 512'%3E%3Cpath fill='%23fff' d='M108.4 0h23v22.8h21.2V0h23v69h-23V46h-21v23h-23.2M206 23h-20.3V0h63.7v23H229v46h-23m53.5-69h24.1l14.8 24.3L313.2 0h24.1v69h-23V34.8l-16.1 24.8-16.1-24.8V69h-22.6m89.2-69h23v46.2h32.6V69h-55.6'/%3E%3Cpath fill='%23e44d26' d='m107.6 471-33-370.4h362.8l-33 370.2L255.7 512'/%3E%3Cpath fill='%23f16529' d='M256 480.5V131h148.3L376 447'/%3E%3Cpath fill='%23ebebeb' d='M142 176.3h114v45.4h-64.2l4.2 46.5h60v45.3H154.4m2 22.8H202l3.2 36.3 50.8 13.6v47.4l-93.2-26'/%3E%3Cpath fill='%23fff' d='M369.6 176.3H255.8v45.4h109.6m-4.1 46.5H255.8v45.4h56l-5.3 59-50.7 13.6v47.2l93-25.8'/%3E%3C/svg%3E`

### Steps to reproduce

- use this stippet

```
.tag {
  &--technology {
    font-size: 0;
    width: 42px;
    height: 42px;
    background-repeat: no-repeat;
    background-size: contain;
    background-position: left bottom;
    & svg {
      width: 100%;
      height: 100%;
    }
  }
  &--js {
    background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 630 630'%3E%3Crect width='630' height='630' fill='%23f7df1e'/%3E%3Cpath d='m423.2 492.19c12.69 20.72 29.2 35.95 58.4 35.95 24.53 0 40.2-12.26 40.2-29.2 0-20.3-16.1-27.49-43.1-39.3l-14.8-6.35c-42.72-18.2-71.1-41-71.1-89.2 0-44.4 33.83-78.2 86.7-78.2 37.64 0 64.7 13.1 84.2 47.4l-46.1 29.6c-10.15-18.2-21.1-25.37-38.1-25.37-17.34 0-28.33 11-28.33 25.37 0 17.76 11 24.95 36.4 35.95l14.8 6.34c50.3 21.57 78.7 43.56 78.7 93 0 53.3-41.87 82.5-98.1 82.5-54.98 0-90.5-26.2-107.88-60.54zm-209.13 5.13c9.3 16.5 17.76 30.45 38.1 30.45 19.45 0 31.72-7.61 31.72-37.2v-201.3h59.2v202.1c0 61.3-35.94 89.2-88.4 89.2-47.4 0-74.85-24.53-88.81-54.075z'/%3E%3C/svg%3E");
  }
}
```
- add elemet to the page `<div className="tag tag--technology tag--js"></div>`
- use `npm run build`

### Expected result

compile svg from scss to css without any additional changes 

### Actual result

compilation scss to css with changes which make svgs invalid

### Environment

```
  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.1 - /c/Users/Thou/AppData/Local/Programs/Python/Python38-32/python
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.54)
  npmPackages:
    gatsby: ^3.8.0 => 3.8.0
    gatsby-plugin-gatsby-cloud: ^2.4.1 => 2.4.1
    gatsby-plugin-i18n: ^1.0.1 => 1.0.1
    gatsby-plugin-image: ^1.8.0 => 1.8.0
    gatsby-plugin-manifest: ^3.4.0 => 3.4.0
    gatsby-plugin-next-seo: ^1.7.0 => 1.7.0
    gatsby-plugin-offline: ^4.4.0 => 4.4.0
    gatsby-plugin-react-helmet: ^4.4.0 => 4.4.0
    gatsby-plugin-robots-txt: ^1.6.2 => 1.6.2
    gatsby-plugin-sass: ^4.6.0 => 4.6.0
    gatsby-plugin-sharp: ^3.4.1 => 3.4.1
    gatsby-source-filesystem: ^3.4.0 => 3.4.0
    gatsby-transformer-remark: ^4.3.0 => 4.3.0
    gatsby-transformer-sharp: ^3.4.0 => 3.4.0
  npmGlobalPackages:
    gatsby: 3.8.0
```

**Comment by Scorpovi4** [comment]
As I spotted the main issue is xmlns attribute removes within build, but how to fix it?

**Comment by tu4mo** [comment]
https://github.com/gatsbyjs/gatsby/issues/31878
