### ISSUE TITLE
bug: Adding new product type doesn't trigger new page creation

### ISSUE THREAD

**Issue by LekoArts** [gatsbyjs/gatsby#32074]
When having https://github.com/gatsbyjs/gatsby-starter-shopify set up it has the different product types in the navigation, e.g.:

![image](https://user-images.githubusercontent.com/16143594/118490890-bd6ef700-b71e-11eb-8347-61a02f57e153.png)

When adding a new product type and assigning this to a product a new page should be created. A warm build is triggered but the result is:

![image (1)](https://user-images.githubusercontent.com/16143594/118490984-d5df1180-b71e-11eb-8098-1d8e2a90f5c7.png)

(Here `DOLLS` was added as a new product type)

Triggering a cold build solves this.

**Comment by jacksellwood** [comment]
@LekoArts how can I reproduce this? Is this still an issue in version 5.0.2 of `gatsby-source-shopify`?

**Comment by LekoArts** [comment]
It's been too long since I filed this. If this is still an issue someone will report it but for now I think we can close this.
