### ISSUE TITLE
Not retrieving all products

### ISSUE THREAD

**Issue by dominichawton** [gatsbyjs/gatsby#32073]
I've got 40 active products in my store but only 24 are being returned when I query `AllShopifyProducts`.  Increasing the `limit` doesn't affect the result. Any assistance would be appreciated!

**Comment by jacksellwood** [comment]
Products must be in a sales channel for `gatsby-source-shopify` to pull them in. 
If you're looking for a way to separate products for your Gatsby front-end from other products, [Gatsby Cloud](https://apps.shopify.com/gatsby-storefront?surface_detail=gatsby&surface_inter_position=1&surface_intra_position=3&surface_type=search) is now available as a sales channel from the Shopify app store.

At this time, we do not have support planned for sourcing products which aren't in any sales channels.
