### ISSUE TITLE
[gatsby-plugin-sitemap]: Sub path is stripped from siteUrl in sitemap-index.xml

### ISSUE THREAD

**Issue by prichey** [gatsbyjs/gatsby#32080]
## Description

My `siteUrl` is mangled in the `sitemap.xml`. In this example, the `siteUrl` is `https://mysite.com/foo` but the location in `sitemap-index.xml` is `https://mysite.com/sitemap/sitemap-0.xml` (rather than `https://mysite.com/foo/sitemap/sitemap-0.xml`).

`gatsby-config.js`:
```
module.exports = {
  /* Your site config here */
  siteMetadata: {
    siteUrl: 'https://mysite.com/foo'
  },
  plugins: ['gatsby-plugin-sitemap'],
}
```

### Steps to reproduce

`npm run build`

### Expected result

`public/sitemap/sitemap-index.xml`:
```
<?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><sitemap><loc>https://mysite.com/foo/sitemap/sitemap-0.xml</loc></sitemap></sitemapindex>
```

### Actual result

`public/sitemap/sitemap-index.xml`:
```
<?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><sitemap><loc>https://mysite.com/sitemap/sitemap-0.xml</loc></sitemap></sitemapindex>
```

### Environment

```
  System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /var/folders/gb/n4714k6158z5svmlr6y_yrfh0000gn/T/fnm_multishell_59135_1624470024651/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - /var/folders/gb/n4714k6158z5svmlr6y_yrfh0000gn/T/fnm_multishell_59135_1624470024651/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 88.0.1
    Safari: 14.1.1
  npmPackages:
    gatsby: ^3.6.2 => 3.6.2 
    gatsby-plugin-sitemap: ^4.4.0 => 4.4.0 
  npmGlobalPackages:
    gatsby: 3.5.1
```

Reproduction repo: https://github.com/prichey/sitemap-bug

**Comment by moonmeister** [comment]
So my guess is this is happening because the siteUrl is expected to be a domain. `https://mysite.com/`. If you're hosting a Gatsby site at a sub path you need to use the built in path prefix functionality. https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/path-prefix/

**Comment by moonmeister** [comment]
I could be wrong here but that's always been my assumption.

**Comment by prichey** [comment]
Thing is, that doesn't work either:

`gatsby-config.js`:
```
module.exports = {
  pathPrefix: "/foo",
  siteMetadata: {
    siteUrl: "https://mysite.com",
  },
  plugins: ["gatsby-plugin-sitemap"],
}
```

-> `sitemap-index.xml`:
```
<?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><sitemap><loc>https://mysite.com/sitemap/sitemap-0.xml</loc></sitemap></sitemapindex>```

The path in the output is still `https://mysite.com/sitemap/sitemap-0.xml` rather than `https://mysite.com/foo/sitemap/sitemap-0.xml`

**Comment by prichey** [comment]
Reproduction branch here: https://github.com/prichey/sitemap-bug/tree/path-prefix. Thanks for the quick response!

**Comment by moonmeister** [comment]
Good to know!! Looks like this was missed. 

I'll fix this if I have time but I work on Gatsby for fun so I don't have a timeline. Anyone who wants to tackle this please do so.

**Comment by BastavChoudhury** [comment]
I could be wrong here but that's always been my assumption. Given I wrote the sitemap plugin this is probably why that's getting stripped, cause I expected it to be a domain.

It's been a while but I believe if you are using the pathPrefix functionality the sitemap plugin will correctly append that in the sitemap. If not we can fix that.

@Bastav

**Comment by antdking** [comment]
It's possible this will fix your issue, as it changes to using `config.pathPrefix`: https://github.com/gatsbyjs/gatsby/pull/32107

**Comment by moonmeister** [comment]
Okay, I checked out your repro and this is working as expected. If you gatsby config is:

```js
module.exports = {
  /* Your site config here */
  pathPrefix: '/foo',
  siteMetadata: {
    siteUrl: 'https://mysite.com/',
  },
  plugins: ['gatsby-plugin-sitemap'],
}

```

then you use the command `gatsby build --prefix-paths` everything is done correctly. 

#32107 will make sure that the asset prefix isn't also appended and will fix a different bug.
