### ISSUE TITLE
[gatsby-source-contentful] Provide a code example for rendering rich-text embedded assets images 

### ISSUE THREAD

**Issue by slk333** [gatsbyjs/gatsby#32099]
Embedding an image in a rich-text field is a common need, yet it's **extremely difficult** to make it work nicely with the contentful plugin. Information about how to do it is often outdated if not plain wrong.

The current README does not explain how to render an image that comes from a Rich-Text field.
The image is an embedded asset.
Rendering that image is far from trivial, many developers had to open stackoverflow questions, and the answers are not precise. 
https://stackoverflow.com/questions/66061787/how-to-query-for-an-image-in-rich-text
https://stackoverflow.com/questions/65829246/gatsby-contentful-embedded-image

Moreover, most of the snippets we find through Google are outdated or using the old Gatsby Image.

**Comment by slk333** [comment]
As of today, I got this code working, but It's not using the latest gatsby-plugin-image
import
`import { renderRichText } from "gatsby-source-contentful/rich-text"
`

Graphql
`mainContent {
        raw
        references {
          ... on ContentfulAsset {
            contentful_id
            __typename
            fixed {
              src
            }
          }
        }
      }`

options
`const options = {
    renderNode: {
      'embedded-asset-block': node => {
        console.log(node.data.target)
        const url = node.data.target.fixed.src
        return <img src= {url} alt="illustrative image"/> 
      },
    },
  }`

render
`        <article> {blogPost.mainContent && renderRichText(blogPost.mainContent,options)}</article>
`

**Comment by njbmartin** [comment]
Agree that the documentation / Readme for `gatsby-source-contentful` doesn't reflect the new image plugin, but the same principles apply if you combine these two examples:
https://www.gatsbyjs.com/plugins/gatsby-source-contentful/#query-rich-text-content-and-references
https://www.gatsbyjs.com/plugins/gatsby-source-contentful/#using-the-new-gatsby-image-plugin

Your GraphQL query becomes:

```GQL
mainContent {
        raw
        references {
          ... on ContentfulAsset {
            contentful_id
            __typename
            gatsbyImageData
          }
        }
      }
```

And you use `gatsby-source-contentful/rich-text` like so:

```js
const options = {
  renderNode: {
    'embedded-asset-block': node => {
      const { gatsbyImageData } = node.data.target
      if(!gatsbyImageData) { // asset is not an image
        return null
      } 
      return (
        <Box
          sx={{
            paddingY: 5,
          }}
        >
          <GatsbyImage image={image} />
        </Box>
      )
    },
  },
}
```

Hope this helps in the meantime.

**Comment by LekoArts** [comment]
We'd be happy to review a PR improving this section of the README!

**Comment by Prashant-Sharma-TWS** [comment]
const options = {
  renderNode: {
    'embedded-asset-block': node => {
      const { gatsbyImageData } = node.data.target
      if(!gatsbyImageData) { 
        return null
      } 
      return (<GatsbyImage image={image} />)
    },
  },
}
