### ISSUE TITLE
gatsby build hangs

### ISSUE THREAD

**Issue by neilyoung** [gatsbyjs/gatsby#3210]
## Description

Gatsby build excepts and hangs

### Environment

Gatsby version: 1.1.25
Node.js version: v8.2.1
Operating System: Mac OSX High Sierra

### File contents (if changed):

`gatsby-config.js`: 
`package.json`: 
{
  "name": "myProject",
  "description": "description",
  "license": "MIT",
  "scripts": {
    "develop": "gatsby develop",
    "build": "gatsby build",
    "serve": "gatsby serve"
  },
  "dependencies": {
    "bootstrap": "^3.3.7",
    "gatsby": "^1.9.119",
    "google-map-react": "^0.25.0",
    "react-bootstrap": "^0.31.5",
    "react-bootstrap-sweetalert": "^4.1.0",
    "react-bootstrap-validation": "^0.1.11",
    "react-helmet": "^5.2.0",
    "react-markdown": "^3.1.0",
    "react-native-dynamic-graph": "0.0.16",
    "whatwg-fetch": "^2.0.3"
  }
}

`gatsby-node.js`: 
`gatsby-browser.js`: 
`gatsby-ssr.js`: 

### Actual result

~/myProject $ gatsby build
success delete html files from previous builds — 0.012 s
success open and validate gatsby-config.js — 0.003 s
success copy gatsby files — 0.014 s
success onPreBootstrap — 0.008 s
success source and transform nodes — 0.019 s
success building schema — 0.071 s
success createLayouts — 0.027 s
success createPages — 0.001 s
success createPagesStatefully — 0.019 s
success onPreExtractQueries — 0.001 s
success update schema — 0.043 s
success extract queries from components — 0.011 s
success run graphql queries — 0.005 s
success write out page data — 0.003 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.000 s

info bootstrap finished - 1.777 s

success Building CSS — 8.611 s
⢀ Building production JavaScript bundlesTypeError: Cannot read property 'initial' of undefined
    at ExtractTextPlugin.<anonymous> (/Users/me/myProject/node_modules/extract-text-webpack-plugin/index.js:22:8)
    at Array.forEach (native)
    at ExtractTextPlugin.mergeNonInitialChunks (/Users/me/myProject/node_modules/extract-text-webpack-plugin/index.js:21:16)
    at ExtractTextPlugin.<anonymous> (/Users/me/myProject/node_modules/extract-text-webpack-plugin/index.js:275:12)
    at Array.forEach (native)
    at ExtractTextPlugin.<anonymous> (/Users/me/myProject/node_modules/extract-text-webpack-plugin/index.js:273:21)
    at /Users/me/myProject/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/Users/me/myProject/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/Users/me/myProject/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:209:22)
    at ExtractTextPlugin.<anonymous> (/Users/me/myProject/node_modules/extract-text-webpack-plugin/index.js:237:10)
    at Compilation.applyPluginsAsync (/Users/me/myProject/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.seal (/Users/me/myProject/node_modules/webpack/lib/Compilation.js:525:7)
    at Compiler.<anonymous> (/Users/me/myProject/node_modules/webpack/lib/Compiler.js:397:15)
    at /Users/me/myProject/node_modules/tapable/lib/Tapable.js:103:11
    at Compilation.<anonymous> (/Users/me/myProject/node_modules/webpack/lib/Compilation.js:445:10)
    at /Users/me/myProject/node_modules/webpack/lib/Compilation.js:417:12
    at /Users/me/myProject/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/me/myProject/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/me/myProject/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /Users/me/myProject/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Users/me/myProject/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/me/myProject/node_modules/webpack/node_modules/async/lib/async.js:52:16
⠐ Building production JavaScript bundles

### Expected behavior
Should run

What should happen?
Should build

### Steps to reproduce

difficult

**Comment by KyleAMathews** [comment]
Hey there Neil Young :-)

This is a fairly common issue unfortunately with webpack 1 — if you search the issues there's lots of discussions + possible fixes.

**Comment by neilyoung** [comment]
Thanks. Not sure if this comment was helpful, though

**Comment by KyleAMathews** [comment]
It's a bug in webpack. There's sometimes things you can do in your site to fix it but our hands are tied until we upgrade out of webpack.

**Comment by neilyoung** [comment]
The thing is: Everything works fine with "gatsby develop" Gatsby build fails.

It seems to boil down to this sequence:

```
import MapStoreForm from "./mapStoreForm.js"
...
render() {
        return (
            <MapStoreForm></MapStoreForm>
        )
    }
```

And mapStoreForm.js (stripped down):
```

import React, { Component } from 'react';


export default class MapStoreForm extends React.Component {
  constructor(props) {
     super(props);
  }


  render() {
    return (
       <div></div>
    )
  }
}

```

This leads to the a.m. error.

If I comment the import statement, I'm getting this (correct) error
```


  49 |     render() {
  50 |         return (
> 51 |             <MapStoreForm></MapStoreForm>
     |              ^
  52 |         )
  53 |     }
  54 | 


  WebpackError: MapStoreForm is not defined
  
  - maps.js:51 Maps.render
    src/pages/maps.js:51:14
  
  - ReactCompositeComponent.js:796 ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext
    ~/react-dom/lib/ReactCompositeComponent.js:796:1
  
  - ReactCompositeComponent.js:819 ReactCompositeComponentWrapper._renderValidatedComponent
    ~/react-dom/lib/ReactCompositeComponent.js:819:1
  
  - ReactCompositeComponent.js:359 ReactCompositeComponentWrapper.performInitialMount
    ~/react-dom/lib/ReactCompositeComponent.js:359:1
  
  - ReactCompositeComponent.js:255 ReactCompositeComponentWrapper.mountComponent
    ~/react-dom/lib/ReactCompositeComponent.js:255:1
  
  - ReactReconciler.js:43 Object.mountComponent
    ~/react-dom/lib/ReactReconciler.js:43:1
  
  - ReactMultiChild.js:234 ReactDOMComponent.mountChildren
    ~/react-dom/lib/ReactMultiChild.js:234:1
  
  - ReactDOMComponent.js:657 ReactDOMComponent._createContentMarkup
    ~/react-dom/lib/ReactDOMComponent.js:657:1
  
  - ReactDOMComponent.js:524 ReactDOMComponent.mountComponent
    ~/react-dom/lib/ReactDOMComponent.js:524:1
  
  - ReactReconciler.js:43 Object.mountComponent
    ~/react-dom/lib/ReactReconciler.js:43:1
  





```


If I additionally replace the render statement by plain <div></div>, everything is fine.

I don't get it...

**Comment by neilyoung** [comment]
Is anybody supposed to know more from this crap?
```

success Building CSS — 8.515 s
error UNHANDLED EXCEPTION


  TypeError: Cannot read property 'initial' of undefined
  
  - index.js:22 ExtractTextPlugin.<anonymous>
    [myProject]/[extract-text-webpack-plugin]/index.js:22:8
  
  - Array.forEach
  
  - index.js:21 ExtractTextPlugin.mergeNonInitialChunks
    [myProject]/[extract-text-webpack-plugin]/index.js:21:16
  
  - index.js:275 ExtractTextPlugin.<anonymous>
    [myProject]/[extract-text-webpack-plugin]/index.js:275:12
  
  - Array.forEach
  
  - index.js:273 ExtractTextPlugin.<anonymous>
    [myProject]/[extract-text-webpack-plugin]/index.js:273:21
  
  - async.js:52 
    [myProject]/[extract-text-webpack-plugin]/[async]/lib/async.js:52:16
  
  - async.js:236 Object.async.forEachOf.async.eachOf
    [myProject]/[extract-text-webpack-plugin]/[async]/lib/async.js:236:30
  
  - async.js:209 Object.async.forEach.async.each
    [myProject]/[extract-text-webpack-plugin]/[async]/lib/async.js:209:22
  
  - index.js:237 ExtractTextPlugin.<anonymous>
    [myProject]/[extract-text-webpack-plugin]/index.js:237:10
  
  - Tapable.js:71 Compilation.applyPluginsAsync
    [myProject]/[tapable]/lib/Tapable.js:71:13
  
  - Compilation.js:525 Compilation.seal
    [myProject]/[webpack]/lib/Compilation.js:525:7
  
  - Compiler.js:397 Compiler.<anonymous>
    [myProject]/[webpack]/lib/Compiler.js:397:15
  
  - Tapable.js:103 
    [myProject]/[tapable]/lib/Tapable.js:103:11
  
  - Compilation.js:445 Compilation.<anonymous>
    [myProject]/[webpack]/lib/Compilation.js:445:10
  
  - Compilation.js:417 
    [myProject]/[webpack]/lib/Compilation.js:417:12
  
  - Compilation.js:332 
    [myProject]/[webpack]/lib/Compilation.js:332:10
  
  - async.js:52 
    [myProject]/[webpack]/[async]/lib/async.js:52:16
  
  - async.js:246 done
    [myProject]/[webpack]/[async]/lib/async.js:246:17
  
  - async.js:44 
    [myProject]/[webpack]/[async]/lib/async.js:44:16
  
  - Compilation.js:332 
    [myProject]/[webpack]/lib/Compilation.js:332:10
  
  - async.js:52 
    [myProject]/[webpack]/[async]/lib/async.js:52:16
  

```

**Comment by neilyoung** [comment]
Stupid, when you realize, you have bet on the wrong horse :(

**Comment by KyleAMathews** [comment]
If you haven't yet, try reading through these issues https://github.com/gatsbyjs/gatsby/search?q=Cannot+read+property+%27initial%27+of+undefined&type=Issues&utf8=%E2%9C%93
