### ISSUE TITLE
query dependency tracking not working properly

### ISSUE THREAD

**Issue by Marco-Daniel** [gatsbyjs/gatsby#32102]
## Description

I'm using gatsby-source-wordpress as a source plugin. In Gatsby node I use the createPages API to create an overview page for each term of a taxonomy. If i update or delete a page that is connected to that term, the term overview page rebuilds properly, but if I add a new page to the term, the term overview page doesn't get rebuild. I have to clear the cache and do a full rebuild for it to reflect the changes.

@TylerBarnes advised me in the wp-graphql slack to open an issue here on the Gatsby core repo

### Steps to reproduce

Run the following query in gatsby-node and pass the id to an template:
`     query allCategories {   
  allWpCategory(filter: { name: { ne: "Uncategorized" } }) {
          nodes {
            id
            uri
          }
  }        
}
`

then in side the template run:

`    query BlogQuery($id: String!) {
    wpCategory(id: { eq: $id }) { 
     posts {
        nodes {
id 
         ...PostData
       }
      }
    }
  }`

### Expected result
When adding a page to the term it should be added to the overview page

### Actual result

The page only gets added after clearing the cache

### Environment

R
  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17
  Browsers:
    Chrome: 91.0.4472.114
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.54)
  npmPackages:
    gatsby: ^3.7.0 => 3.7.0 
    gatsby-image: ^3.7.0 => 3.7.0 
    gatsby-plugin-image: ^1.7.0 => 1.7.0 
    gatsby-plugin-layout: ^2.7.0 => 2.7.0 
    gatsby-plugin-manifest: ^3.7.0 => 3.7.0 
    gatsby-plugin-material-ui: ^3.0.1 => 3.0.1 
    gatsby-plugin-netlify: ^3.7.0 => 3.7.0 
    gatsby-plugin-react-helmet: ^4.7.0 => 4.7.0 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-sharp: ^3.7.0 => 3.7.0 
    gatsby-plugin-sitemap: ^4.3.0 => 4.3.0 
    gatsby-plugin-styled-components: ^4.7.0 => 4.7.0 
    gatsby-source-filesystem: ^3.7.0 => 3.7.0 
    gatsby-source-wordpress: 5.7.0 => 5.7.0 
    gatsby-transformer-sharp: ^3.7.0 => 3.7.0 
  npmGlobalPackages:
    gatsby-cli: 3.7.1

`  flags: {
    PRESERVE_FILE_DOWNLOAD_CACHE: true,
    PRESERVE_WEBPACK_CACHE: true,
  },`

**Comment by TylerBarnes** [comment]
@Marco-Daniel do you know if this was working with Gatsby v2?

**Comment by Marco-Daniel** [comment]
@TylerBarnes V2 has exactly the same behaviour. It also doesn't matter if I enable GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES env variable or not. In both cases this happens. 

I think [32194](https://github.com/gatsbyjs/gatsby/issues/32194) is the same issue.

**Comment by lemonadvertising** [comment]
We're facing a similar issue. We've created content types using Wordpress ACF and whenever the content in the ACF is updated, Gatsby detects the change and publishes the page, however it does not republish the parent page in which the content type is displayed in a carousel format. Is there anyway to have some kind of dependency relationship between pages? 

An example of this is a News Article which gets published as a page but if the Article were to appear on the homepage as a featured article it requires manual publishing of the home page.

**Comment by vinniedauer** [comment]
I'm experiencing a very similar issue. My homepage has a static query that returns all posts with a certain WP tax term. When that list is updated in Wordpress with different posts, I _usually_ have to clear cache and rebuild on Gatsby hosting to see the changes.

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
