### ISSUE TITLE
gatsby-source-wordpress source from Jetpack CDN instead of locally

### ISSUE THREAD

**Issue by amcc** [gatsbyjs/gatsby#32103]
I believe that a recent version of gatsby-source-wordpress would automatically take images from the Jetpack CDN (https://jetpack.com/features/design/content-delivery-network/) if available.

Jetpack if installed shows up in the sourceUrl of an image node. gatsby-source-wordpress appears to not use that and is using the file on the wordpress server, perhaps the mediaItemUrl instead

## Description

I'm working on a few wordpress/gatsby websites - there is an obvious slowdown on sourcing images on builds with slower wordpress servers around the image download section particularly. Sourcing from the Jetpack CDN at build would really help people with smaller/cheaper wordpress servers.

At one stage it seemed builds were sourcing from the sourceUrl, which in this case is a Jetpack url, in the format https://i1.wp.com..... etc

It seems pretty certain that the images are sourced from the wordpress server now instead. After accidentally downloading a wordpress database where I forgot to modify all the links from my online server to my local one I got the below error:

```Error: failed to process https://localsite.test:8888/wp-content/uploads/2021-06-21_15-33-49_105725.png```

...easily solved and negated by fixing my db... 

but it also shows the image are definitely sourcing from the wordpress server, not the Jetpack CDN. However it is also printed out during develop on the "gatsby-source-wordpress Fetching....." stage.

### Steps to reproduce

Create a wordpress website and install the Jetpack plugin to put images on the Wordpress CDN

### Expected result

Images source from sourceUrl rather than mediaItemUrl, or ideally a config option to choose.

### Actual result

Images source from the

### Environment

gatsby develop, or gatsby build - both locally and on Gatsby Cloud

What would be ideal, if possible is an option to switch between the CDN and the wordpress source. 

I have a personal use case where its very useful to have rapid preview builds during upload phases and changes for a website, then later on a single build can be done using the original images (if we have an option) for higher quality images.

However there are an awful lot of people using wordpress on slower servers which this would really benefit. Wordpress's Jetpack CDN is completely free, and the image phase of a build can easily either kill the server (or cause 500 errors etc), even if the config download settings are tweaked multiple builds swamp most peoples bandwidth quickly.

**Comment by LekoArts** [comment]
So is your issue a question/feature request or a bug report? I'm not sure reading your description.

**Comment by amcc** [comment]
Thats a fair point.
The bugginess is that the source for gatsby-plugin-image seems to have changed with an update, either to the wordpress plugin, or somewhere else in gatsby recently. Tyler mentioned to me that it should use the sourceUrl before mediaItemUrl and this was the logic:
```
const fileUrl = sourceUrl || mediaItemUrl
```

If we can consider this 'unexpected' behaviour or a bug and separate out the 'feature' i mentioned after that might be more useful!
