### ISSUE TITLE
Gatsby Cloud Possibly Bug With HTTP Request Headers

### ISSUE THREAD

**Issue by RafidMuhymin** [gatsbyjs/gatsby#32137]
I am trying to add CSP (Content Security Headers) headers to my Gatsby Project. The project is hosted at Gatsby Cloud at the URL [https://muhymin.gatsbyjs.io/](https://muhymin.gatsbyjs.io/) . There is already a plugin, gatsby-plugin-csp but it adds the headers using the meta httpEquiv tag. Even Chrome doesn't support this. So, I took the headers that it created and used the transformHeaders function to add these headers to Gatsby Cloud. But now the problem is GC sends incomplete headers. For example, if you go to [https://muhymin.gatsbyjs.io/_headers.json](https://muhymin.gatsbyjs.io/_headers.json), you'll find the following header attached with every page:

`"Content-Security-Policy: base-uri 'self'; default-src 'self'; script-src 'self' https://platform-api.sharethis.com https://l.sharethis.com https://count-server.sharethis.com 'sha256-ecIkKw1UaQjeT+fiAh0Q6OKT97qwaQ/RStEQaewwWyI=' 'sha256-KWO6UOhc/cfhZd4gtXYPu4WkSRPuCQDtCkF/v9OyJB8=' 'sha256-d1U3Nlory+rDKhRqRYnw+9l2UU7SXzTpwRIIyvWnr80='; style-src 'self' 'unsafe-inline' 'sha256-C8hTSF2IwRpX57+q1wBgC/84JUFFdDxC/fUGfu4C0VQ=' 'sha256-LEbWFSWxt+oVnC4xzh4AJ3cGaYv3SkbW0vbyUq1a5Vw='; object-src 'none'; form-action 'self'; font-src 'self' data:; connect-src 'self'; img-src 'self' data: https://platform-cdn.sharethis.com;",`

But if you check the Network tab in Chrome Dev Console, you'll see the header as shown in the below image :

![Screenshot (2)](https://user-images.githubusercontent.com/63650415/123552605-c2ff2a00-d72b-11eb-923a-8f8c02d6def3.png)

As soon as the server reaches the word 'https', it stops sending the rest of the header. A very weird problem. The website looks like the 90s and the console is logging tens of violations. If I omit the 'https://
' from the header, then the server sends some of the other directives but don't send img-src, font-src, connect-src, base-uri, and some other directives. It may be only sending the default-src, script-src, and the style-src directive.

**Comment by KyleAMathews** [comment]
Could you file a support ticket as well that points to this issue?

**Comment by RafidMuhymin** [comment]
I didn't found anything named Support Ticket. I left a message by going to the GC dashboard, then the Help dropdown, then the Get Help link, then Leave a Message button.

**Comment by RafidMuhymin** [comment]
I didn't found anything named Support Ticket. I left a message by going to the GC dashboard, then the Help dropdown, then the Get Help link, then Leave a Message button.

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

For issues related to Gatsby Cloud please reach out to our support here: https://www.gatsbyjs.com/support/
For issues about the plugin you mentioned please open an issue here: https://github.com/bejamas/gatsby-plugin-csp

Thanks!
