### ISSUE TITLE
Adding a Gatsby CLI install step to starters' guides

### ISSUE THREAD

**Issue by AntoineGRoy** [gatsbyjs/gatsby#32133]
## Summary

Users can land directly on the starters pages - installing the CLI is a required step they cannot skip, if they have not already installed the CLI they have to leave the starter Guide and come back.

### Motivation

Provide a better experience to new users

## Steps to resolve this issue

Add a first step to the starters' guides explaining how to install the CLI.
The changes have to be ported to all the starters guides. 
I will make a pull request for one of them, /starters/gatsby-starter-theme/README.md,  I not sure of the most efficient way to update all of them.

### Draft 

1.  **Install gatsby-cli globally**

    Use the Gatsby CLI to create a new site, specifying the default starter.
     The <a href="https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/README.md">Gatsby CLI</a> is available via npm and is installed globally by using npm.

     ```shell
    # install gatsby-cli globally 
    npm install -g gatsby-cli
    ```
      ```shell
    # Verify its installed by running  
    gatsby -v
    ```

2.  **Create a Gatsby site**  

    Use the Gatsby CLI to create a new site, specifying the default starter.

    ```shell
    # create a new Gatsby site using the default starter
    gatsby new my-default-starter https://github.com/gatsbyjs/gatsby-starter-default
    ```

3.  **Start developing.**
[...]

### Open a pull request

- [x] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

From our experience most users begin with our tutorial/docs and install the `gatsby-cli` in the process of that. Thus the instructions assume you have it installed already.

We could add a link to https://www.gatsbyjs.com/docs/tutorial/part-0/#gatsby-cli in the first paragraph of `Use the Gatsby CLI to create a new site` to be something like `Use the Gatsby CLI ([install instructions](https://www.gatsbyjs.com/docs/tutorial/part-0/#gatsby-cli)) to create a new site`

That change would need to be made to all READMEs in https://github.com/gatsbyjs/gatsby/tree/master/starters and to the template https://github.com/gatsbyjs/gatsby/blob/master/starters/README-template.md

**Comment by AntoineGRoy** [comment]
Hi LekoArts, I agree that a full new step might be overkill, so if we just add a link it could be as simple as :

_Use the `<a href=""https://www.gatsbyjs.com/docs/tutorial/part-0/#gatsby-cli">Gatsby CLI</a>` to create a new site, specifying the <%= name %> starter._

If you agree on this I will make the pull request in the template.
Wouldn't the change be automatically applied to  all the starters? Or do I need to create a different pull request on all of them?

**Comment by LekoArts** [comment]
I think this will be clearer:

```md
Use the Gatsby CLI ([install instructions](https://www.gatsbyjs.com/docs/tutorial/part-0/#gatsby-cli)) to create a new site
```

The change will be automatically transferred to the respective repositories so no need to open separate PRs :)
