### ISSUE TITLE
Gatsby functions should be mentioned as breaking change in "Migrating from v2 to v3"

### ISSUE THREAD

**Issue by AndrewKMoses** [gatsbyjs/gatsby#32186]
### Preliminary Checks

- [x] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

The [migration guide from v2 to v3](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/) does not mention the new Gatsby Functions. According to the [docs](https://www.gatsbyjs.com/docs/reference/functions/getting-started/) for Gatsby Functions `src/api` is now a reserved directory. This is not mentioned in the migration guide and of course we had javascript files in that directory.

We wasted lots of time trying to understand why our imports using alias no longer worked. onCreateWebpackConfig is called after `Compiling Gatsby Functions` and therefor there are no webpack aliases available at that time.

Documentation should state that you should no longer use `src/api` for other things that Gatsby Functions.

### Steps to Resolve this Issue

Rename existing `src/api` to something else.

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

At the time of writing the migration guide Gatsby Functions didn't exist yet and thus weren't added to the guide. But it makes sense to add this to the guide.

Would you be up for submitting a PR fixing this?

**Comment by Dipinrajc** [comment]
Thanks @AndrewKMoses

**Comment by AndrewKMoses** [comment]
@LekoArts Unfortunately I won't have time for a while. On vacation now. However I can mention that the path is not mentioned in the [project structure](https://www.gatsbyjs.com/docs/reference/gatsby-project-structure/) either.

I find it strange that Gatsby Function was introduced in a minor release when it is this intrusive.

**Comment by MiKatre** [comment]
Thanks @AndrewKMoses !

Yes, this should at least be mentioned as breaking changes. 

Here is the error I was getting. (I past it here so future victims of this error can find this thread better). 


```
failed Compiling Gatsby Functions - 1.794s
error Failed to compile Gatsby Functions. Module parse failed: Unexpected token (26:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

  return (
>     <React.Fragment>
|       {finalData && render(finalData)}
|       {!finalData && <div>Loading (StaticQuery)</div>}

 ModuleParseError: Module parse failed: Unexpected token (26:4)
 You may need an appropriate loader to handle this file type, currently no load  ers are configured to process this file. See https://webpack.js.org/concepts#l  oaders

return (
  <React.Fragment>
 {finalData && render(finalData)}
 {!finalData && <div>Loading (StaticQuery)</div>}

- NormalModule.js:921 handleParseError
 [repo]/[webpack]/lib/NormalModule.js:921:19

- NormalModule.js:1023 
 [repo]/[webpack]/lib/NormalModule.js:1023:5

- NormalModule.js:743 processResult
[repo]/[webpack]/lib/NormalModule.js:743:11

- NormalModule.js:807 
[repo]/[webpack]/lib/NormalModule.js:807:5

- LoaderRunner.js:406 
[repo]/[loader-runner]/lib/LoaderRunner.js:406:3

- LoaderRunner.js:232 iterateNormalLoaders
[repo]/[loader-runner]/lib/LoaderRunner.js:232:10

 - LoaderRunner.js:223 Array.<anonymous>
[repo]/[loader-runner]/lib/LoaderRunner.js:223:4

- CachedInputFileSystem.js:27 runCallbacks
[repo]/[enhanced-resolve]/lib/CachedInputFileSystem.js:27:15

- CachedInputFileSystem.js:200 
[repo]/[enhanced-resolve]/lib/CachedInputFileSystem.js:200:4

- graceful-fs.js:123 
[repo]/[graceful-fs]/graceful-fs.js:123:16

- read_file_context.js:63 FSReqCallback.readFileAfterClose [as oncomplete]
internal/fs/read_file_context.js:63:3

```

**Comment by ruskid** [comment]
Thanks, guys! This is especially frustrating when "npm run develop" works but "npm run build" doesn't and you have to figure out the changes that have been made.

Reserving such directories is a recipe for issues 😅  but at least it would be nice to throw warnings & exceptions when developing
