### ISSUE TITLE
gatsby-plugin-typescript webpack cache issue

### ISSUE THREAD

**Issue by klittlepage** [gatsbyjs/gatsby#32197]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When running `gatsby build` warnings of the form:

```
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Resolving 'gatsby-plugin-typescript/package.json' in /site/node_modules/gatsby/dist/internal-plugins/internal-data-bridge for build dependencies doesn't lead to expected result '/site/node_modules/gatsby-plugin-typescript/package.json', but to '/site/node_modules/gatsby/node_modules/gatsby-plugin-typescript/package.json' instead. Resolving dependencies are ignored for this path.
<w>  at unknown 4 gatsby-plugin-typescript/package.json
<w>  at file dependencies /site/node_modules/gatsby/dist/internal-plugins/internal-data-bridge/gatsby-node.js
<w>  at file /site/node_modules/gatsby/dist/internal-plugins/internal-data-bridge/gatsby-node.js
<w>  at file dependencies /site/node_modules/gatsby/dist/utils/api-runner-node.js
<w>  at file /site/node_modules/gatsby/dist/utils/api-runner-node.js
<w>  at file dependencies /site/node_modules/gatsby/dist/utils/webpack.config.js
```

appear and the webpack cache appears to be invalidated. Prior to the release of `3.8.0` this behavior could be avoided by setting `PRESERVE_WEBPACK_CACHE: false` in `gatsby-config.js`.

### Reproduction Link

https://github.com/klittlepage/gatsby-yarn2-webpack-issue

### Steps to Reproduce

Running yarn build will result in the reproduction repo will result in the error above.

### Expected Result

No warnings & caching behavior.

### Actual Result

The warnings cited above.

### Environment

```shell
System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/opt/node@14/bin/node
    Yarn: 2.4.2 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/opt/node@14/bin/npm
  Languages:
    Python: 3.8.5 - /opt/miniconda3/bin/python
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0.2
    Safari: 14.1.1
  npmPackages:
    gatsby: ^3.8.1 => 3.8.1
    gatsby-plugin-typescript: ^3.8.0 => 3.8.0
```

**Comment by LekoArts** [comment]
Is there a reason why you set this plugin? It's included by default so it's not necessary to add it. Does the issue go away if you remove it from the config?

**Comment by klittlepage** [comment]
> Is there a reason why you set this plugin. It's included by default so it's not necessary to add it.

It's a minimal repo of a real config that predates  https://github.com/gatsbyjs/gatsby/commit/19332305408e9ce024df79c88d26b18d02ea533c.

> Does the issue go away if you remove it from the config

Confirmed that removing it from the config fixes the issue, but leaving it in and attempting to set any configuration options results in the same.

**Comment by MartinDawson** [comment]
This should be re-opened. It's definitely an issue still.
