### ISSUE TITLE
Generate a JS file for each page.

### ISSUE THREAD

**Issue by demoneaux** [gatsbyjs/gatsby#322]
I'm currently working on shifting my blog to Gatsby. I was wondering if it was possible to generate say one JavaScript file per page. This is to allow each post to use its own React components for demos and tutorials, while not adding excess page weight by causing users to load the whole blog's content.

**Comment by KyleAMathews** [comment]
@demoneaux see https://github.com/gatsbyjs/gatsby/issues/10 for discussions of ideas on how to do this. It'd be great if you want to pick this up and run with it and start creating some PRs!
