### ISSUE TITLE
Consider using Parcel bundler instead of webpack

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#3220]
Using [Parcel](https://parceljs.org/) instead of webpack could improve the developer experience by providing lower build times (especially with cache). Plugins and APIs would have to be rewritten in order to support new (or even multiple) bundling mechanisms.

**Comment by KyleAMathews** [comment]
I'd be very interested in seeing a prototype of Gatsby using Parcel — it definitely seems like it'd provide big speedups.

It wouldn't be possible to try the port until we finish the webpack 3 upgrade as Gatsby core uses `require.ensure` still for code splitting. Once we're using async import, it'd be much easier to try the port.

**Comment by Niko-La** [comment]
Parcel fits in very well with Gatsby design philosophy @kylemathews

**Comment by calpa** [comment]
Would it be faster if gatsby is using Parcel?

**Comment by gaui** [comment]
This would be awesome.

**Comment by tsiq-swyx** [comment]
i dont know how much is needed to "prototype" gatsby but i did a parcel SSG recently: https://github.com/sw-yx/boring-ssg

parcel lacks the event system to truly parallelize builds, and I raised an issue here: https://github.com/parcel-bundler/parcel/issues/1660 

once that gets built in, parcel-based SSGs should easily outperform webpack-based ones.

**Comment by colbyhub** [comment]
I would love to see this!

**Comment by DOSputin** [comment]
BUMP!

**Comment by Odelya** [comment]
Adding the request

**Comment by cosbor11** [comment]
@KyleAMathews - Hey! It it looks like parcel supports code-splitting with the current version: 
https://parceljs.org/code_splitting.html. I like that parcel is all about trying to minimize configuration

**Comment by pranshuchittora** [comment]
Hi there, I think a lot of work is required in order to migrate. I think the webpack ecosystem is huge, tried and tested by the industry.

I am closing this issue, but feel free to reopen.
Happ Hacking :+1:
