### ISSUE TITLE
Static HTML build error with dynamic expressions in import()

### ISSUE THREAD

**Issue by wafflepie** [gatsbyjs/gatsby#32262]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi, I'm having issues with using dynamic imports in Gatsby. We have an `Icon` component which lazily imports `.svg` files, but has special handling in server contexts (because we need to use the component in a lot of different contexts, including Storybook, Gatsby, custom Webpack configs for standard web applications and SSR.

Basically something like this:

```
export const importIconAsset = (type: IconType): Promise<{ default: AssetComponentType }> =>
	import(
		`!!@svgr/webpack!./assets/${type}.svg`
	);

const serverAssetComponents: Partial<Record<IconType, AssetComponentType>> = {};
const IS_SERVER = typeof window === 'undefined';

if (IS_SERVER) {
	iconTypes.forEach(async type => {
		const assetModule = await importIconAsset(type);

		serverAssetComponents[type] = assetModule.default;
	});
}

const useAssetComponent = (type: IconType) => {
	const Asset = useMemo(
		() => (IS_SERVER ? serverAssetComponents[type] : lazy(() => importIconAsset(type))),
		[type]
	);

	return Asset;
};
```

However, I'm getting errors in Gatsby. All other Webpack applications, including an SSR microservice, work just fine. Minimal reproduction repository is included.

I think `webpackEmptyContext` might be one of the clues, but the import syntax is definitely valid.

EDIT: Managed to find a temporary workaround using a Babel codegen macro, I'm replacing `import` with `require` when the stage includes `'html'`.

### Reproduction Link

https://github.com/wafflepie/reproduction-gatsby-dynamic-import

### Steps to Reproduce

1. `npm install`
2. `npm build`

### Expected Result

No error.

### Actual Result

```
Error: Cannot find module '../assets/foo.svg'
    at webpackEmptyContext (/home/waffle/reproduction-gatsby-dynamic-import/public/webpack:/gatsby-starter-default/src/pages|sync:2:1)
    at /home/waffle/reproduction-gatsby-dynamic-import/public/webpack:/gatsby-starter-default/src/pages/index.js:8:25
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

### Environment

```shell
System:
    OS: Linux 4.19 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.17.2 - ~/.nvm/versions/node/v14.17.2/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.2/bin/npm
  npmPackages:
    gatsby: ^3.8.1 => 3.8.1 
    gatsby-plugin-gatsby-cloud: ^2.8.1 => 2.8.1 
    gatsby-plugin-image: ^1.8.0 => 1.8.0 
    gatsby-plugin-manifest: ^3.8.0 => 3.8.0 
    gatsby-plugin-offline: ^4.8.0 => 4.8.0 
    gatsby-plugin-react-helmet: ^4.8.0 => 4.8.0 
    gatsby-plugin-sharp: ^3.8.0 => 3.8.0 
    gatsby-source-filesystem: ^3.8.0 => 3.8.0 
    gatsby-transformer-sharp: ^3.8.0 => 3.8.0
```

**Comment by wafflepie** [comment]
As a workaround, I'm using a Babel macro to replace `import` with `require` when `process.env.GATSBY_BUILD_STAGE` includes `html`.

**Comment by Remownz** [comment]
same issue here (also in development environment):
works:
```
import(`./img/de_DE.svg`)
```
doesn't work:
```
import(`./img/${lang}.svg`)
```

**Comment by minimit** [comment]
Same here, also just need to concatenate string that breaks

This works `import(`./test.js`),` this don't works `import(`./${'test'}.js`)`

**Comment by JannikWempe** [comment]
I can confirm that. I have the same error using `gatsby-preset-babel`:

```
react_devtools_backend.js:4045 Error: Cannot find module '../../svgs/icons/phone.svg'
    at webpackEmptyContext (commons.js:19)
    at eval (useDynamicSVGImport.tsx:22)
```

**Comment by JannikWempe** [comment]
I was able to fix it by forcing the resolution of `babel-plugin-dynamic-import-node` to `2.3.0`.

Added this to my `package.json`:
```
"resolutions": {
    "babel-plugin-dynamic-import-node": "2.3.0"
  }
```

This works with yarn@1 out of the box but I remember that you have to do something in order to force resolutions with `npm`.

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
