### ISSUE TITLE
[gatsby-source-shopify] Shopify Source Product Variants Missing inventoryItem

### ISSUE THREAD

**Issue by drmartin1998** [gatsbyjs/gatsby#32274]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Product variants are missing the inventoryItem field. This field is important when dealing with multiple locations and querying availability based on store location.

https://shopify.dev/api/admin/graphql/reference/products-and-collections/productvariant
https://shopify.dev/api/admin/graphql/reference/inventory/inventoryitem

### Reproduction Link

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-shopify/src/query-builders/product-variants-query.ts

### Steps to Reproduce

1. Attempt to query product variant inventoryItem

### Expected Result

Successfully query varient inventoryItem data

### Actual Result

inventoryItem data is not available

### Environment

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
  Binaries:
    Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.5
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.64)
  npmPackages:
    gatsby: ^3.7.2 => 3.7.2
    gatsby-image: ^3.7.1 => 3.7.1
    gatsby-plugin-image: ^1.7.1 => 1.7.1
    gatsby-plugin-postcss: ^4.7.1 => 4.7.1
    gatsby-plugin-react-helmet: ^4.7.1 => 4.7.1
    gatsby-plugin-sharp: ^3.7.1 => 3.7.1
    gatsby-source-contentful: ^5.7.1 => 5.7.1
    gatsby-source-shopify: ^5.0.0-rc.27 => 5.0.0-rc.27
    gatsby-transformer-remark: ^4.4.1 => 4.4.1
    gatsby-transformer-sharp: ^3.7.1 => 3.7.1
  npmGlobalPackages:
    gatsby: 3.7.2
```

**Comment by DanielSLew** [comment]
For example, does adding this to the `productVariant` query help?

```
                    inventoryItem {
                      id
                      countryCodeOfOrigin
                      createdAt
                      duplicateSkuCount
                      harmonizedSystemCode
                      inventoryHistoryUrl
                      legacyResourceId
                      locationsCount
                      provinceCodeOfOrigin
                      requiresShipping
                      sku
                      tracked
                      trackedEditable {
                        locked
                        reason
                      }
                      unitCost {
                        amount
                        currencyCode
                      }
                      updatedAt
                    }
```

**Comment by drmartin1998** [comment]
@DanielSLew there is also the inventoryLevels beneath the inventoryItem that returns nodes of availability for each location. Your proposal would be a live query call passing in inventoryId and locationId, which would work as well but would not be generated during build. Either way I think AllShopifyLocations may need to be added as well to query all of the shops locations in addition to exposing either the inventoryItems + inventoryLevels or just the inventoryItem.

```
{
  productVariants {
   edges {
      node {
        inventoryItem {
          inventoryLevels {
            edges {
              node {
                available
                location {
                  id
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by DanielSLew** [comment]
@drmartin1998 I added in a query for `ShopifyLocations` as well as `InventoryItem` and `inventoryLevels`. I believe this will help you manage multiple locations. To query for the `ShopifyLocations` you need to add `'locations'` to your `pluginOptions.shopifyConnections`, ie `shopifyConnections: ["locations"]`

I published a canary that you can access at `gatsby-source-shopify@5.3.0-alpha-shopify.2`. Do you mind testing this out and letting me know if it does what you'd like it to?

**Comment by drmartin1998** [comment]
> @drmartin1998 I added in a query for `ShopifyLocations` as well as `InventoryItem` and `inventoryLevels`. I believe this will help you manage multiple locations. To query for the `ShopifyLocations` you need to add `'locations'` to your `pluginOptions.shopifyConnections`, ie `shopifyConnections: ["locations"]`
> 
> I published a canary that you can access at `gatsby-source-shopify@5.3.0-alpha-shopify.2`. Do you mind testing this out and letting me know if it does what you'd like it to?

@DanielSLew pulled the build in and it looks like this will have everything in it to do what we need to do. We now have enough data to pull locations and then filter products by location chosen.

**Comment by DanielSLew** [comment]
Thanks for bringing this up and testing out the solution @drmartin1998!
