### ISSUE TITLE
 Some vulnerabilities require your attention to resolve

### ISSUE THREAD

**Issue by abhishekkacham507** [gatsbyjs/gatsby#32277]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Dear Team, Please cloud you suggest to me how to run the gatsby command through the run as admin or else a normal user.

Because yesterday I have installed the gatsby on my system by executing the command npm install -g gatsby-cli in CMD as administrator. 

Today I have executed the other command npm install gatsby-source-wordpress in CMD as a normal user, not as admin. 

After executing the above command I have faced some issues and for that, I have executed npm audit fix. Some of the issues have resolved but still I am facing some issues.

High            Prototype Pollution

  Package         immer

  Patched in      >=8.0.1

  Dependency of   gatsby-source-wordpress

  Path            gatsby-source-wordpress > @rematch/immer > immer

  More info       https://npmjs.com/advisories/1603

  Moderate        Regular Expression Denial of Service

  Package         postcss

  Patched in      >=7.0.36 <8.0.0 || >=8.2.10

  Dependency of   gatsby

  Path            gatsby > postcss

  More info       https://npmjs.com/advisories/1693

  High            Regular Expression Denial of Service in trim

  Package         trim

  Patched in      >=0.0.3

  Dependency of   gatsby

  Path            gatsby > gatsby-cli > gatsby-recipes > remark-parse > trim

  More info       https://npmjs.com/advisories/1700

  Moderate        Regular Expression Denial of Service

  Package         browserslist

  Patched in      >=4.16.5

  Dependency of   gatsby

  Path            gatsby > react-dev-utils > browserslist

  More info       https://npmjs.com/advisories/1747

  Moderate        Regular Expression Denial of Service

  Package         ws

  Patched in      >=5.2.3 <6.0.0 || >=6.2.2 <7.0.0 || >=7.4.6

  Dependency of   gatsby

  Path            gatsby > eslint-plugin-graphql > graphql-config >
                  @graphql-tools/url-loader > ws

  More info       https://npmjs.com/advisories/1748

  Moderate        Regular expression denial of service

  Package         glob-parent

  Patched in      >=5.1.2

  Dependency of   gatsby

  Path            gatsby > webpack-dev-server > chokidar > glob-parent

  More info       https://npmjs.com/advisories/1751

  High            Regular Expression Denial of Service

  Package         trim-newlines

  Patched in      >=3.0.1 <4.0.0 || >=4.0.1

  Dependency of   gatsby-plugin-sharp

  Path            gatsby-plugin-sharp > imagemin-mozjpeg > mozjpeg > logalot >
                  squeak > lpad-align > meow > trim-newlines

  More info       https://npmjs.com/advisories/1753

  High            Regular Expression Denial of Service

  Package         trim-newlines

  Patched in      >=3.0.1 <4.0.0 || >=4.0.1

  Dependency of   gatsby-plugin-sharp

  Path            gatsby-plugin-sharp > imagemin-pngquant > pngquant-bin >
                  logalot > squeak > lpad-align > meow > trim-newlines

  More info       https://npmjs.com/advisories/1753

  High            Denial of Service

  Package         css-what

  Patched in      >=5.0.1

  Dependency of   gatsby-plugin-sharp

  Path            gatsby-plugin-sharp > svgo > css-select > css-what

  More info       https://npmjs.com/advisories/1754

found 9 vulnerabilities (4 moderate, 5 high) in 2191 scanned packages
  9 vulnerabilities require manual review. See the full report for details.

Please cloud you help me on how to fix the above issues. Please

### Reproduction Link

N/A

### Steps to Reproduce

N/A

### Expected Result

N/A

### Actual Result

N/A

### Environment

```shell
Windows 10 64 bit
node -v
v14.17.3
npm -v
6.14.13
git --version
git version 2.32.0.windows.1
```

### Config Flags

N/A

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

While those audit messages might seem scary they are almost always irrelevant in the context of Gatsby as it's a build tool. So there is nothing to "fix" as the warning is not relevant.

Gatsby creates static assets and runs everything at build time and not during runtime. `npm audit` is designed for runtime / Node apps so it flags issues that can occur there. This means that almost every "vulnerability" report we receive are false positives. While in principle Gatsby can also have vulnerabilities you need to make sure that it's relevant to Gatsby before reporting it. For example a "Regex DDOS attack" can never be a real vulnerability for a development-time tool. If you want to override/update a transitive dependency you can use [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/).

If you know that a vulnerability affects Gatsby because you understand what the vulnerability is, please report it [here](https://github.com/gatsbyjs/gatsby/blob/master/SECURITY.md). Thanks!

**Comment by abhishekkacham507** [comment]
Dear Team, Now how should I integrate my WordPress with gatsby by executing the below command or not npm install gatsby-source-wordpress. If not then how to integrate and get rid of those vulnerabilities.

**Comment by abhishekkacham507** [comment]
Dear Team, In the below link of your gatsby site it's clearly mentioned that I need to run the command "npm install gatsby-source-wordpress" in order to connect to my WordPress. And when I execute the command I am facing the above issues.

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/getting-started.md

So, Please help me on how to solve the issues and how to integrate my wordpress with gatsby

**Comment by LekoArts** [comment]
You'll only need to run `npm install gatsby-source-wordpress`, no further action required on the audit messages.

**Comment by abhishekkacham507** [comment]
Dear Team, Please can you show me a way to update the versions.

https://www.npmjs.com/advisories/1693
https://www.npmjs.com/advisories/1603

**Comment by abhishekkacham507** [comment]
Dear Team, Please show a way to solve the issues of the below links.

https://www.npmjs.com/advisories/1747
https://www.npmjs.com/advisories/1748
https://www.npmjs.com/advisories/1751
https://www.npmjs.com/advisories/1753
https://www.npmjs.com/advisories/1754
https://www.npmjs.com/advisories/1700
https://www.npmjs.com/advisories/1693
https://www.npmjs.com/advisories/1603

**Comment by abhishekkacham507** [comment]
Dear Team, Please show a way to solve the issues of the below links.

Please help me. I need this and much important for us to implement our project.

https://www.npmjs.com/advisories/1747
https://www.npmjs.com/advisories/1748
https://www.npmjs.com/advisories/1751
https://www.npmjs.com/advisories/1753
https://www.npmjs.com/advisories/1754
https://www.npmjs.com/advisories/1700
https://www.npmjs.com/advisories/1693
https://www.npmjs.com/advisories/1603
