### ISSUE TITLE
[gatsby-source-wordpress] getting images from wordpress.com

### ISSUE THREAD

**Issue by DarrylD** [gatsbyjs/gatsby#3228]
Is it possible without ACF? With wordpress.com, on the free tier, no plugins can be installed making it not possible to use ACF (correct me if I'm wrong).

Specifically looking to grab the `featured_image` url opposed to the id.

Wondering if a PR is needed to add `_embed` to the wordpress api [example here](http://chrisltd.com/blog/2017/06/get-featured-images-from-the-wordpress-rest-api) or if I'm missing something.

**Comment by DarrylD** [comment]
As in trying to use acf despite it be on wordpress.com?

Ass in adding something like this?
```
acf {
    featured_media
}
```

It just breaks, I assume since no fields are coming from the response.

**Comment by pieh** [comment]
check https://www.gatsbyjs.org/packages/gatsby-source-wordpress/#image-processing - plugin will pull in featured_media (no need for acf for that)

**Comment by DarrylD** [comment]
This is what I've been getting from that.
```
GraphQL Error Field "featured_media" must not have a selection since type "Int" has no subfields.

  file: /site/src/templates/post.js

   1 |
   2 |     query currentPostQuery($id: String!) {
   3 |         wordpressPost(id: { eq: $id }) {
   4 |             id
   5 |             slug
   6 |             title
   7 |             content
   8 |             excerpt
   9 |             modified
  10 |             # featured_media
> 11 |             featured_media {
     |                            ^
  12 |                 localFile {
  13 |                     childImageSharp {
  14 |                         resolutions(width: 500, height: 300) {
  15 |                             src
  16 |                         }
  17 |                     }
  18 |                 }
  19 |             }
  20 |             ...PostIcons
  21 |         }
```

I have both  `gatsby-transformer-sharp` and  `gatsby-plugin-sharp` in the config file.

Could I be missing something?

**Comment by b0gd4n** [comment]
@DarrylD you managed to get this to work?

**Comment by DarrylD** [comment]
@b0gd4n i have not :(

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by ShawnBaek** [comment]
Same problem...

**Comment by Casey6624** [comment]
Sorry if I've misunderstood, but I'm not using ACF and I query the featured images of my posts like this:

query postsQuery{
        allWordpressPost{
            edges{
                node{
                    id
                    title
                    excerpt
                    slug
                    date(formatString: "MMMM DD, YYYY")
                  featured_media {
                  	source_url
                  }
                }
            }
        }
    }

I don't see why that wouldn't work on WordPress.com hosting

**Comment by kharrop** [comment]
> Sorry if I've misunderstood, but I'm not using ACF and I query the featured images of my posts like this:
> 
> ![carbon](https://user-images.githubusercontent.com/34159052/53946930-ace18180-40bc-11e9-97c2-c5bf13ce0690.png)
> 
> I don't see why that wouldn't work on WordPress.com hosting

This worked for me, thank you!
