### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by hamiltonbrooke** [gatsbyjs/gatsby#32288]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Been developing a couple of different Gatsby websites over the last few weeks with no issues at all.
Both websites source data from WordPress using GraphQL. 

Last night I ran npm run develop as usual and now my browser isn't rendering the website and throwing up the following error:

"Loading chunk node_modules_gatsby-plugin-image_dist_lazy-hydrate-9f0721eb_js failed"

My terminal is throwing up the following error:

"Error: ENOENT: no such file or directory, open '/Users/olivermcvey/Gatsby/hamiltonbrooke/.cache/caches/gatsby-plugin-sharp/diskstore-4d952606169b55fb368c7f62f68deb2c.json'"

I've tried running gatsby clean a few times and reinstalling my node_modules folder but no joy.

I'm still finding my way round Gatsby but this issue only occurs on pages with images.

Not sure if the problem lays with:

gatsby-plugin-image, childImageSharp or gatsby-source-wordpress?
<img width="752" alt="Screenshot_2021-07-07_at_10 30 23" src="https://user-images.githubusercontent.com/14992849/124767616-e007da00-df2f-11eb-91af-f19111bb69b3.png">

### Reproduction Link

Sorry, no repo to share.

### Steps to Reproduce

1.
2.
3.

### Expected Result

Website to build and render normally

### Actual Result

Website development server fails after visiting localhost

### Environment

```shell
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.2 - /usr/local/bin/node
    npm: 7.18.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 88.0.1
    Safari: 14.1.1
  npmPackages:
    gatsby: ^3.9.0 => 3.9.0
    gatsby-plugin-emotion: ^6.9.0 => 6.9.0
    gatsby-plugin-image: ^1.9.0 => 1.9.0
    gatsby-plugin-manifest: ^3.9.0 => 3.9.0
    gatsby-plugin-postcss: ^4.9.0 => 4.9.0
    gatsby-plugin-react-helmet: ^4.9.0 => 4.9.0
    gatsby-plugin-sharp: ^3.9.0 => 3.9.0
    gatsby-plugin-sitemap: ^4.5.0 => 4.5.0
    gatsby-source-filesystem: ^3.7.1 => 3.9.0
    gatsby-source-wordpress: ^5.9.0 => 5.9.0
    gatsby-transformer-sharp: ^3.9.0 => 3.9.0
```

**Comment by klittlepage** [comment]
I can confirm this exact issue, which manifested itself when updating from 3.8.0 to 3.9.0 of `gatsby-plugin-sharp`. As a temporary workaround, forcing a downgrade of `gatsby-plugin-sharp` from 3.9.0 to 3.8.0 or earlier fixes the issue on my end at least.

```

  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.2 - /usr/local/opt/node@14/bin/node
    Yarn: 2.4.2 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/opt/node@14/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0.2
    Safari: 14.1.1
  npmPackages:
    gatsby: ^3.9.0 => 3.9.0
    gatsby-plugin-force-trailing-slashes: ^1.0.5 => 1.0.5
    gatsby-plugin-google-gtag: ^3.9.0 => 3.9.0
    gatsby-plugin-image: ^1.9.0 => 1.9.0
    gatsby-plugin-layout: ^2.9.0 => 2.9.0
    gatsby-plugin-manifest: ^3.9.0 => 3.9.0
    gatsby-plugin-material-ui: ^3.0.1 => 3.0.1
    gatsby-plugin-mdx: ^2.9.0 => 2.9.0
    gatsby-plugin-offline: ^4.9.0 => 4.9.0
    gatsby-plugin-react-helmet: ^4.9.0 => 4.9.0
    gatsby-plugin-react-svg: ^3.0.1 => 3.0.1
    gatsby-plugin-robots-txt: ^1.6.8 => 1.6.8
    gatsby-plugin-sharp: 3.8.0 => 3.8.0
    gatsby-plugin-sitemap: ^4.5.0 => 4.5.0
    gatsby-plugin-typescript: ^3.9.0 => 3.9.0
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-remark-copy-linked-files: ^4.6.0 => 4.6.0
    gatsby-remark-images: ^5.6.0 => 5.6.0
    gatsby-source-filesystem: ^3.9.0 => 3.9.0
    gatsby-transformer-sharp: ^3.9.0 => 3.9.0
    gatsby-transformer-yaml: ^3.9.0 => 3.9.0
```

**Comment by hamiltonbrooke** [comment]
Thanks so much @klittlepage, downgrading gatsby-plugin-sharp to the previous 3.8.0 version has resolved the issue. Sounds like a bug with 3.9.0 which hopefully will be addressed in the next release.

**Comment by runemadsen** [comment]
I am running into the exact same problem: `gatsby-plugin-image` version `3.9.0` will randomly generate some images but not other, causing the dev server to crash when trying to load the `.json` cache files:

```
Error: ENOENT: no such file or directory, open 'GATSBYREPOPATH/.cache/caches/gatsby-plugin-sharp/diskstore-33fef0dc22f08
  97aa1fd038bd02e4ebb.json'
```

This does not seem to be a problem when running `gatsby build`. The problem is solved by fixing the package version to `3.8.0`.

**Comment by LekoArts** [comment]
Hi!

Please [provide a minimal reproduction][reproduction] and we'll be able to take a look.

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment]
Thanks for that. I'm also seeing this in my test repo: https://github.com/LekoArts/issue-32288

I see two issues:

1) When editing the query inside the page, e.g. changing the width from 800 to 900 in gatsbyImageData it shows the error overlay and I need to reload the page
2) When removing the cache and starting up gatsby develop the page shows the placeholder and crashes on the error that the people mentioned

Starting the server again solves it for me. So it only occurred when I used `gatsby clean` and then `gatsby develop`.

**Comment by klittlepage** [comment]
@LekoArts, how many images/queries are you testing it with? After a `gatsby clean` and multiple runs of `gatsby develop`, I'm seeing a seemingly random subset of images loading successfully before the server crashes. This holds for `n > 3` static images and roughly ten attempts at running `gatsby develop`.

I'm only bringing this up if it helps to isolate the issue; using `3.8.0` is probably a better workaround than repeatedly starting the server.

**Comment by runemadsen** [comment]
@klittlepage In my repo it crashes when loading 8 images. Haven't tested anything less than that.

**Comment by pieh** [comment]
Hey folks, this seems to be combination of new gatsby and gatsby-plugin-sharp versions introduced in https://github.com/gatsbyjs/gatsby/pull/31901 . https://github.com/gatsbyjs/gatsby/pull/32307 is potential fix.

**Comment by mbcod3** [comment]
> I am running into the exact same problem: `gatsby-plugin-image` version `3.9.0` will randomly generate some images but not other, causing the dev server to crash when trying to load the `.json` cache files:
> 
> ```
> Error: ENOENT: no such file or directory, open 'GATSBYREPOPATH/.cache/caches/gatsby-plugin-sharp/diskstore-33fef0dc22f08
>   97aa1fd038bd02e4ebb.json'
> ```
> 
> This does not seem to be a problem when running `gatsby build`. The problem is solved by fixing the package version to `3.8.0`.

Actually its not gatsby-plugin-image, its gatsby-plugin-sharp that needs to be downgraded to 3.8.0.

**Comment by runemadsen** [comment]
Yes, sorry. It’s the sharp plug-in like stated in my other comments.

**Comment by vladar** [comment]
The fix is published in `gatsby@3.9.1` (not in sharp plugin; sharp plugin 3.9.0 should work with this patch version of gatsby)

**Comment by runemadsen** [comment]
Beautiful! That was fast. Thanks so much.

**Comment by timtilch** [comment]
We have downgraded node to `12.22.1` and npm to `6.14.13.` Problem seems to be solved for the moment. Maybe helps someone else.
