### ISSUE TITLE
[gatsby-source-contentful] getNode returns undefined on child node when using latest gatsby-source-contentful@5.9.0

### ISSUE THREAD

**Issue by vlomocso-fullscale** [gatsbyjs/gatsby#32290]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

We are in the process of migrating to Gatsby v3
Our `onCreateNode ` script which uses `getNode` on a child node now returns `undefined`

### Reproduction Link

https://github.com/vlomocso-fullscale/getnode-issue-repro

### Steps to Reproduce

1. Run gatsby develop on the reproduction repository
2. the reproduction gatsby-node.js will `console.log(typeof childNode)` on the child node result from getNode

### Expected Result

See the terminal output `object` type

### Actual Result

See the terminal output `undefined`

### Environment

```shell
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.3 - /c/Users/user/AppData/Local/Programs/Python/Python37/python
  Browsers:
    Chrome: 91.0.4472.124
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.64)
  npmPackages:
    gatsby: ^3.8.1 => 3.8.1
    gatsby-plugin-gatsby-cloud: ^2.8.1 => 2.8.1
    gatsby-plugin-image: ^1.8.0 => 1.8.0
    gatsby-plugin-manifest: ^3.8.0 => 3.8.0
    gatsby-plugin-offline: ^4.8.0 => 4.8.0
    gatsby-plugin-react-helmet: ^4.8.0 => 4.8.0
    gatsby-plugin-sharp: ^3.8.0 => 3.8.0
    gatsby-source-contentful: ^5.9.0 => 5.9.0
    gatsby-source-filesystem: ^3.8.0 => 3.8.0
    gatsby-transformer-sharp: ^3.8.0 => 3.8.0
  npmGlobalPackages:
    gatsby-cli: 3.9.0
```

**Comment by osartun** [comment]
This might be related to this issue: https://github.com/gatsbyjs/gatsby/issues/22792#issuecomment-874037765

**Comment by LekoArts** [comment]
Hi!

Please see https://github.com/gatsbyjs/gatsby/discussions/32414. Unfortunately it must have been luck that your logic worked as the Contentful plugin is now working as expected. You should use the `createResolvers` API for any logic like that.
