### ISSUE TITLE
It might not be allowed to say that here, but..

### ISSUE THREAD

**Issue by neilyoung** [gatsbyjs/gatsby#3230]
...I don't really know, what gatsby is beyond "gatsby develop". Developing is fun (more or less).

But:

I'm literally unable to come through with "gatsby build", running from one error into the next. This sucks, really.

A list of errors I had to cope with

1)  bundlesTypeError: Cannot read property 'initial' of undefined
Solution: Could be fixed by following rshah03 https://github.com/gatsbyjs/gatsby/issues/1846 and patching line 21 and 23 of node_modules/extract-text-webpack-plugin/index.js

2) A bunch of errors 107 and 130 on webpack minify
Solution: Fix "bugs" (minor typos) in code. The error expressions where sligthly helpful

3) Cannot resolve 'file' or 'directory' ../public/chunk-manifest.json 
Happened after deleting public.  Was trying to supply chunk-manifest.json from some deleted cont. The build comes through, but at runtime error 4) 

4) At runtime after successful build I'm appearing tons of "Uncaught ReferenceError: webpackJsonp is not defined"
Right now I have no clue. I'm trying to rebuild my project from scratch 

That to say: I need to consider for myself:  gatsby is NOT production ready.

**Comment by neilyoung** [comment]
Building from scratch didn't help.

`Cannot resolve 'file' or 'directory' ../public/chunk-manifest.json remains.
`
It is referred in render-page.js 

`	  var chunkManifest = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"!raw!../public/chunk-manifest.json\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
`

**Comment by benjaminhoffman** [comment]
@neilyoung try starting here: https://www.gatsbyjs.org/docs/gatsby-starters/
... then build up from there.  Each step of the way try to understand what you are adding/deleting.  It will become much easier to handle this way.

**Comment by neilyoung** [comment]
@benjaminhoffman Thanks, but I did. The point is: Gatsby is awesome, as long as you develop. If it comes to a more complex app (more than a "Hello World" starter) you will definitely run into problems if you try to make a productive version. You will have to face errors over errors. All is pointing into WebPack direction or the way how it is used by Gatsby, so maybe not Gatsby is to blame, but I don't care: They appear as the frontend, so they have to deal with the problems (IMHO).

I have meanwhile dropped Gatsby and switched over to react-static. It took a couple of hours, but it was worth it. I was able to roll my productive version and you know what? It was ways easier, much more seamless and really the fun, Gatsby promises. 

No need to argue. This is my opinion based upon experiences. The "make my project productive" thing is not working as it should.

**Comment by benjaminhoffman** [comment]
Thank you for your input @neilyoung and apologies you have experienced so much difficulty.  As you know, Gatsby is still fairly new (less than a couple years old) and we are doing our best to improve the developer workflow, documentation, and time it takes to get started.  We appreciate your comments, especially because you provided examples w/ suggested solutions.

We hope you give Gatsby another chance in the future and would love it even more if you wanted to contribute!  

Thanks again for your comments / suggestions!

**Comment by neilyoung** [comment]
Hi @benjaminhoffman Thanks for your understanding. Yes, I know about the status of Gatsby. I will be a bit patient and see, what's cooking in the future. Merry Christmas everybody :)
