### ISSUE TITLE
`gatsby develop` crashes from time to time in the middle of its run

### ISSUE THREAD

**Issue by DamnedScholar** [gatsbyjs/gatsby#3235]
This is probably a configuration problem with my project, not a bug in Gatsby, so I will start by describing my overall intentions and what I've done.

## Description

I have [a project](https://github.com/DamnedScholar/gatsby-cusco) (based on `gatsby-advanced-starter`) where I've modified the build process to automatically generate non-blog-post pages (which I will hereafter refer to as "pages" as opposed to "posts" in the Wordpress vernacular) from markdown files. I have `gatsby-filesystem-source` configured for two sources, and I've added fields in `gatsby-node.js` to allow my pages to sort `markdownRemark` nodes by source. For the `createPages` step, I have an additional template page, `templates/page.jsx`. I basically copied `templates/post.jsx` and gutted it. My intention is to have each file under `content/pages` generate a templated page unless there's a file in `pages/` that wants to create the same page. It works, for the most part. At first, it seems to work perfectly, but then I'll be tweaking it and on a recompile, it crashes. But not just any recompile. If I change a stylesheet, it recompiles fine with no problems. However, when I change `layouts/index.jsx`, it always crashes with the same error.

### Environment

Gatsby version: ^1.8.11
Node.js version: 7.0.0
Operating System: Windows 10

### File contents (if changed):

`gatsby-config.js`: 
```
  plugins: [
    {
      resolve: "gatsby-source-filesystem",
      options: {
        name: "pages",
        path: `${__dirname}/content/pages`
      }
    }
  ]
```
`package.json`: No changes except additional `dependencies`, certainly nothing build-process-wise.

`gatsby-node.js`: [Link to changed code](https://github.com/DamnedScholar/gatsby-cusco/blob/master/gatsby-node.js#L43-L140).

`gatsby-browser.js`: Not changed.

`gatsby-ssr.js`: Not changed.

### Actual result
```
 DONE  Compiled successfully in 690ms                                                           5:31:34 PM


 I  Your site is running at http://localhost:8000
 I  Your graphql debugger is running at http://localhost:8000/___graphql
 WAIT  Compiling...                                                                             5:32:14 PM


changed file at D:\github\cusco\gatsby-adv\src\layouts\index.jsx
error UNHANDLED REJECTION


  Error: Invariant Violation: D:/github/cusco/gatsby-adv/src/templates/page.jsx not found in the store com
  ponents: {"D:/github/cusco/gatsby-adv/src/layouts/index.jsx":{"componentPath":"D:/github/cusco/gatsby-ad
  v/src/layouts/index.jsx","query":"query LayoutQuery {\n  allMarkdownRemark {\n    edges {\n      node {\
  n        frontmatter {\n          title\n        }\n        fields {\n          slug\n          source\n
            parsedFilePath {\n            name\n            dir\n          }\n          fileNode {\n
        changeTime\n          }\n        }\n      }\n    }\n  }\n}\n"},"D:/github/cusco/gatsby-adv/.cache/
  dev-404-page.js":{"componentPath":"D:/github/cusco/gatsby-adv/.cache/dev-404-page.js","query":"query Dev
  404Page {\n  allSitePage(filter: {path: {ne: \"/dev-404-page/\"}}) {\n    totalCount\n    edges {\n
   node {\n        path\n      }\n    }\n  }\n}\n"},"D:/github/cusco/gatsby-adv/src/templates/post.jsx":{"
  componentPath":"D:/github/cusco/gatsby-adv/src/templates/post.jsx","query":"query BlogPostBySlug(\n  $sl
  ug: String!\n) {\n  markdownRemark(fields: {slug: {eq: $slug}}) {\n    html\n    timeToRead\n    excerpt
  \n    frontmatter {\n      title\n      cover\n      date\n      category\n      tags\n    }\n    fields
   {\n      slug\n    }\n  }\n}\n"},"D:/github/cusco/gatsby-adv/src/templates/tag.jsx":{"componentPath":"D
  :/github/cusco/gatsby-adv/src/templates/tag.jsx","query":"query TagPage(\n  $tag: String\n) {\n  allMark
  downRemark(limit: 1000, sort: {fields: [frontmatter___date], order: DESC}, filter: {frontmatter: {tags:
  {in: [$tag]}}}) {\n    totalCount\n    edges {\n      node {\n        fields {\n          slug\n
  }\n        excerpt\n        timeToRead\n        frontmatter {\n          title\n          tags\n
    cover\n          date\n        }\n      }\n    }\n  }\n}\n"},"D:/github/cusco/gatsby-adv/src/templates
  /category.jsx":{"componentPath":"D:/github/cusco/gatsby-adv/src/templates/category.jsx","query":"query C
  ategoryPage(\n  $category: String\n) {\n  allMarkdownRemark(limit: 1000, sort: {fields: [frontmatter___d
  ate], order: DESC}, filter: {frontmatter: {category: {eq: $category}}}) {\n    totalCount\n    edges {\n
        node {\n        fields {\n          slug\n        }\n        excerpt\n        timeToRead\n
  frontmatter {\n          title\n          tags\n          cover\n          date\n        }\n      }\n
   }\n  }\n}\n"},"D:/github/cusco/gatsby-adv/src/pages/about.jsx":{"componentPath":"D:/github/cusco/gatsby
  -adv/src/pages/about.jsx","query":"query AboutQuery {\n  allMarkdownRemark {\n    edges {\n      node {\
  n        html\n        fields {\n          slug\n          source\n          parsedFilePath {\n
     name\n          }\n          fileNode {\n            changeTime\n          }\n        }\n      }\n
   }\n  }\n}\n"},"D:/github/cusco/gatsby-adv/src/pages/index.jsx":{"componentPath":"D:/github/cusco/gatsby
  -adv/src/pages/index.jsx","query":"query IndexQuery {\n  allMarkdownRemark(limit: 2000, sort: {fields: [
  frontmatter___date], order: DESC}) {\n    edges {\n      node {\n        fields {\n          slug\n
     }\n        excerpt\n        timeToRead\n        frontmatter {\n          title\n          tags\n
       cover\n          date\n        }\n      }\n    }\n  }\n}\n"},"D:/github/cusco/gatsby-adv/src/pages/
  menu.jsx":{"componentPath":"D:/github/cusco/gatsby-adv/src/pages/menu.jsx","query":"query MenuQuery {\n
   menuYaml {\n    id\n    internal {\n      type\n    }\n    parent {\n      id\n    }\n  }\n}\n"}}

  - invariant.js:42 invariant
    [gatsby-adv]/[invariant]/invariant.js:42:15

  - query-watcher.js:98
    [gatsby-adv]/[gatsby]/dist/internal-plugins/query-runner/query-watcher.js:98:9

  - Map.forEach

  - query-watcher.js:95
    [gatsby-adv]/[gatsby]/dist/internal-plugins/query-runner/query-watcher.js:95:15

  - next_tick.js:67 _combinedTickCallback
    internal/process/next_tick.js:67:7

  - next_tick.js:98 process._tickCallback
    internal/process/next_tick.js:98:9
```

### Expected behavior

There must be a way to make it not crash.

### Steps to reproduce

Create a new template under `src/templates/` and add code to `gatsby-node.js` to include it (a minimal reproduction is available [here](https://github.com/DamnedScholar/gatsby-invariant-test)).

**Comment by KyleAMathews** [comment]
Could you try upgrading to the latest versions of gatsby and other packages?

Does this happen often? Or just once?

**Comment by DamnedScholar** [comment]
This happens whenever Gatsby recompiles following a change of a file under `src/layouts/`, `src/templates/`, or `src/pages/`. I've checked with files from `content/` and `src/components/`, and none of them trigger the crash. After upgrading Gatsby to `1.9.138`, I still see the crashing behavior.

**Comment by KyleAMathews** [comment]
Can you reproduce this with a starter? If not, could you share your code so we can reproduce the problem on our machine? Sounds like a bug we should fix!

**Comment by DamnedScholar** [comment]
Okay, I got a minimal reproduction from the `gatsby-advanced-starter` uploaded [here](https://github.com/DamnedScholar/gatsby-invariant-test). All I've changed from that starter is replacing [`gatsby-node.js`](https://github.com/DamnedScholar/gatsby-invariant-test/blob/master/gatsby-node.js) and copying in my [`templates/page.jsx`](https://github.com/DamnedScholar/gatsby-invariant-test/blob/master/src/templates/page.jsx), so the only possible culprit is the `createPages` method. As before, `gatsby develop` runs normally until a recompile is caused by editing `layouts/index.jsx` (for example).

**Comment by calcsam** [comment]
Can you post this?

**Comment by DamnedScholar** [comment]
Post it to where?

**Comment by KyleAMathews** [comment]
@calcsam it's linked in his earlier comment https://github.com/DamnedScholar/gatsby-invariant-test

**Comment by DamnedScholar** [comment]
I have since updated to `1.9.206` and now the problem seems to have disappeared. Thanks for the help.
