### ISSUE TITLE
[gatsby-source-wordpress] setting schema.perPage to lower values, doesn't return all results of data

### ISSUE THREAD

**Issue by rforster-dev** [gatsbyjs/gatsby#32350]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When setting schema.perPage in gatsby-config.js file, the nodes fetched is not correct in total.

When leaving it at default, it would fetch all the categories I have on my WordPress site (129).

BUT the server would then return a 500 later on at the build for being overloaded.

If I set it to 15 - it would return 59

If set to 20 - it would return 80.

Surely it should return all the categories, regardless of what the perPage schema is set too, just at a much slower pace?

### Reproduction Link

/

### Steps to Reproduce

1. Source from a WordPress website, with multiple categories, with nested categories, and posts assigned.
2. Set schema.perPage to 15
3. Start a build (develop or build)

### Expected Result

The build should source all the nodes correctly.

### Actual Result

It does not, categories are missed in particular I have found.

### Environment

```shell
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 7.6.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.124
    Edge: Spartan (44.18362.1593.0)
  npmPackages:
    gatsby: ^3.8.1 => 3.8.1
    gatsby-cli: ^3.8.0 => 3.8.0
    gatsby-image: ^3.8.0 => 3.8.0
    gatsby-plugin-manifest: ^3.8.0 => 3.8.0
    gatsby-plugin-no-index: ^1.0.2 => 1.0.2
    gatsby-plugin-react-helmet: ^4.8.0 => 4.8.0
    gatsby-plugin-remove-fingerprints: 0.0.2 => 0.0.2
    gatsby-plugin-remove-trailing-slashes: ^3.8.0 => 3.8.0
    gatsby-plugin-sharp: ^3.8.0 => 3.8.0
    gatsby-plugin-sitemap: ^3.3.0 => 3.3.0
    gatsby-source-filesystem: ^3.8.0 => 3.8.0
    gatsby-source-wordpress: ^5.8.0 => 5.8.0
    gatsby-source-wordpress-experimental: ^7.0.6 => 7.0.6
    gatsby-transformer-remote-filesystem: ^1.0.0 => 1.0.0
    gatsby-transformer-sharp: ^3.8.0 => 3.8.0
    gatsby-wpgraphql-inline-images: ^0.2.5 => 0.2.5
  npmGlobalPackages:
    gatsby-cli: 3.1.0
```

### Config Flags

PRESERVE_FILE_DOWNLOAD_CACHE: true,
PRESERVE_WEBPACK_CACHE: true,
FAST_DEV: false,
DEV_SSR: false,
FAST_REFRESH: false,
PARALLEL_SOURCING: false

**Comment by rforster-dev** [comment]
I have updated my versions of Gatbsy and Wordpress as above with the merged PR, and this is not resolved.

I have noticed that if I am doing "hot" builds as opposed to cold builds, the target source (WP) returns less nodes.

If I am consistently requesting builds, our resources are scaling up and more results are coming back without altering page schema and request concurrency. It's still fairly sporadic so it's hard to pin down, but my assumption would be that requests are failing or responding that they are complete when they are not? 

Shouldn't gatsbyjs be resolving all the nodes regardless?

**Comment by rforster-dev** [comment]
Hello - I think I have finally got to the bottom of this @LekoArts

https://en-gb.wordpress.org/plugins/taxonomy-terms-order/ Having this plugin installed causes the issues. The plugin adds another column to the table wp_terms (term_order) and having the setting of "Auto Sort" enabled, causes the issues.

You can have the plugin enabled, and Auto Sort turned off, and it will work again correctly, even with smaller concurrency.

Is it worth investigating why this is, and why this would be a problem with gatsbyjs? My assumption is because having the setting enabled, is that it is modifying SQL.

**Comment by LekoArts** [comment]
I'm not familiar with WordPress so I'll let @TylerBarnes chime in for this :)

**Comment by TylerBarnes** [comment]
@rforster-dev the message can definitely be amended if you can think of wording that would make it clearer. In this case there is a WP plugin which is causing WPGraphQL to return the same ID multiple times during pagination. From Gatsby's perspective there are multiple nodes being returned with the same ID. Maybe the message could be "There are either duplicate ID's in WordPress or a plugin is causing WPGraphQL to return the same nodes multiple times"?

**Comment by rforster-dev** [comment]
@TylerBarnes Apologies for the delay in getting back to you, and thanks for getting back to me.

I think it would help, purely because the message was indicating that there were duplicate ID's in the database, when there are not. 

However, there still weren't duplicate ID's across multiple rows. There duplicate id's because of the new column being added to the table which referenced _another_ ID. 

![image](https://user-images.githubusercontent.com/70289994/130634195-cd7dfd51-a48d-41b7-a583-d86443c29e23.png)

Here's a screenshot of a row that was affecting it. The "term_order" is a custom column that has been added by the plugin. The number "3" in this context, is not a ID, but the ordering (ASC from 0). 

BUT, "3" is also a "term_id" which is where I think it is getting mixed up. 

All the categories in this table that have a term_order that isn't 0, was causing it to trip up, and find a duplicate (it shouldn't be looking against an unknown column, only WP core of term_id).

This is the wp_terms table for reference.

**Comment by TylerBarnes** [comment]
For sure, there aren't duplicate ID's in the db, WPGraphQL is returning the same node multiple times. We should definitely change that warning message. I'm open to a PR for that if you're interested in improving it :) I think we should close this issue otherwise though since there isn't a bug on the Gatsby/gatsby-source-wordpress side of things and this needs to be resolved in your WP instance.

**Comment by rforster-dev** [comment]
@TylerBarnes OK understood, i'll create a PR to improve the WP messaging. 

Do you think it would be beneficial to add a list of known "gotchas" at all, or is this out of scope of gatsby-source-wordpress?

I think as well, adding this to the debugging documentation would be helpful of knowing where to look in WP db, perhaps? Happy to submit a separate PR for that content change?

**Comment by TylerBarnes** [comment]
Hey again! Sorry for the delayed response, I've been away the last 2 weeks. I think a list of gotchas is a great idea! I'm thinking looking in the WP db might not be that useful for debugging since probably most folks (like yourself) don't actually have duplicate DB's and it's a bug with a plugin returning the same node multiple times. A list of gotchas is a great idea though

**Comment by rforster-dev** [comment]
No problem! Shall I make a PR to the docs perhaps?

I was maybe thinking either:

- separate page?
- [Debugging and troubleshooting](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/debugging-and-troubleshooting.md) adding a sub section of "Conflicts with WP plugins". and detailing how to get round it?

**Tasks I need to do (eventually...!)**
- [ ] Make separate PR to improve WP messaging that gatsby shows on build
- [ ] Make separate PR to add known "Gotchas" to add to documentation

**Comment by TylerBarnes** [comment]
That's a great idea. I think adding it to the debugging/troubleshooting page would work well 👍
