### ISSUE TITLE
Broken Link from main A/B Testing page to GA+Netlify Example

### ISSUE THREAD

**Issue by Jedidiah** [gatsbyjs/gatsby#32376]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

On https://www.gatsbyjs.com/docs/ab-testing/ the next link at the bottom of the article links to https://www.gatsbyjs.com/docs/ab-testing-with-google-analytics-and-netlify/ which doesn't exist.

![image](https://user-images.githubusercontent.com/113929/125760315-fdf07e1e-d5d7-47f0-8dab-6b6d3320ca7b.png)

### Steps to Resolve this Issue

1. Go to https://www.gatsbyjs.com/docs/ab-testing/
2. Scroll to the bottom of the article 
3. Click "Next - A/B Testing with Google Analytics & Netlify"
4. ![image](https://user-images.githubusercontent.com/113929/125760721-cce577b5-e558-444d-89c9-8deb760b39f4.png)

**Comment by Jedidiah** [comment]
I believe the correct link should be https://www.gatsbyjs.com/docs/how-to/testing/ab-testing-with-google-analytics-and-netlify/

**Comment by Jedidiah** [comment]
I don't know if it should be a separate issue but adding here first as it is on the same page, the link in the body is also wrong. It links to a [markdown version of the doc](https://www.gatsbyjs.com/f2ec6fc524f25d7e69688be360dc83ff/ab-testing-with-google-analytics-and-netlify.md) not the html.

![image](https://user-images.githubusercontent.com/113929/125761940-da1c6a37-b1d4-4515-b4ce-45a1406bd634.png)

**Comment by LekoArts** [comment]
Thanks! I've updated the doc and will update the navigation
