### ISSUE TITLE
Gatsby V3 - The argument 'path' must be a string or Uint8Array without null bytes

### ISSUE THREAD

**Issue by stephenkellyit** [gatsbyjs/gatsby#32382]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

After updating to Gatsby V3, the popular [memoizee](https://github.com/medikoo/memoizee) causes a webpack error when imported. [es5-ext](https://github.com/medikoo/es5-ext) is a dependency of the `memoizee` package and the issue appears to be with the `#` character in the path. This package worked as expected in Gatsby V2.
```
The argument 'path' must be a string or Uint8Array without null bytes. Received
'.../my-gatsby-project/node_modules/es5-ext/array/\u0000#/e-index-of.js'
```

### Reproduction Link

https://github.com/stephenkellyit/gastby-path-issue-reproduction

### Steps to Reproduce

1. `gatsby new`
2. Select `gatsby-starter-default`
3. `cd my-gatsby-project/ && yarn add memoizee`
4. Inside `src/pages/index.js` Import `memoizee` and use basic example
```
var memoize = require("memoizee");

var fn = function(one, two, three) {
	/* ... */
  console.log(one, two, three);
};

memoized = memoize(fn);

memoized("foo", 3, "bar");
memoized("foo", 3, "bar"); // Cache hit
```
5. Run `npm start` and webpack will compile with an error
```
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

The argument 'path' must be a string or Uint8Array without null bytes. Received
'.../my-gatsby-project/node_modules/es5-ext/array/\u0000#/e-index-of.js'

failed Building development bundle - 4.790s
ERROR in The argument 'path' must be a string or Uint8Array without null bytes. Received 
'.../my-gatsby-project/node_modules/es5-ext/array/\u0000#/e-index-of.js'
```
...

### Expected Result

The development server will start without any webpack error.

### Actual Result

Running `npm start` causes a webpack error.
```
The argument 'path' must be a string or Uint8Array without null bytes. Received
'.../my-gatsby-project/node_modules/es5-ext/array/\u0000#/e-index-of.js'
```

### Environment

```shell
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.19.1 - ~/.nvm/versions/node/v12.13.0/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 76.0.1
    Safari: 13.1.2
  npmPackages:
    gatsby: ^3.9.1 => 3.9.1
    gatsby-plugin-gatsby-cloud: ^2.9.1 => 2.9.1
    gatsby-plugin-image: ^1.9.0 => 1.9.0
    gatsby-plugin-manifest: ^3.9.0 => 3.9.0
    gatsby-plugin-offline: ^4.9.0 => 4.9.0
    gatsby-plugin-react-helmet: ^4.9.0 => 4.9.0
    gatsby-plugin-sharp: ^3.9.0 => 3.9.0
    gatsby-source-filesystem: ^3.9.0 => 3.9.0
    gatsby-transformer-sharp: ^3.9.0 => 3.9.0
  npmGlobalPackages:
    gatsby-cli: 2.8.30
```

**Comment by LekoArts** [comment]
Hi!

The reproduction you linked doesn't show the issue as it's missing e.g. the `memoizee` dependency. Also please note that `gatsby` itself uses it:

https://github.com/gatsbyjs/gatsby/blob/a0b542be35c15e71f8fe76cc5400576dfd0b1391/packages/gatsby/package.json#L106

You might be running into issues with duplicate package versions so try a `yarn why memoizee` and see if it resolves to the correct version.

**Comment by stephenkellyit** [comment]
Apologies, I have updated the reproduction now.

`yarn why memoizee` does resolve to the correct version `memoizee@0.4.15`. 

That is a good thing to note that Gastby uses memoizee, I noticed that myself, so I checked and the same error also occurs without doing `yarn add memoizee` and trying a basic example like this inside `src/pages/index.js`: 
```
var memoize = require("memoizee");

var fn = function(one, two, three) {
	/* ... */
  console.log(one, two, three);
};

memoized = memoize(fn);

memoized("foo", 3, "bar");
memoized("foo", 3, "bar"); // Cache hit
```
