### ISSUE TITLE
graphiql debugger?

### ISSUE THREAD

**Issue by jonathan-chin** [gatsbyjs/gatsby#3245]
Previous versions of gatsby (at least 1.9.70) used to launch a graphiql debugger at /__graphql

I'm now running 1.9.138 and no debugger gets launched. I'm new to graphql and really need the debugger.

Is there any way to access it without rolling back?

**Comment by fk** [comment]
Hi @jonathan-chin! http://localhost:8000/___graphql should still work – maybe you're just missing that third underscore?

**Comment by jonathan-chin** [comment]
@fk you're correct, I was missing the third underscore.

I assumed it was removed because old builds of gatsby printed a message during develop:
```Your graphql debugger is running at http://localhost:8000/___graphql```

the latest build I have doesn't print that.

**Comment by fk** [comment]
Yep, also noticed that just now. :-/ Maybe you could you open an issue for that (would do myself, but on the phone now)?

**Comment by jonathan-chin** [comment]
@fk might be better if you do? I'm not 100% familiar with how github works.

**Comment by fk** [comment]
Just like you did with this issue - open a new one and use your comment (or parts of it) from this issue to describe the missing graphql debugger note issue.

**Comment by KyleAMathews** [comment]
Oh crap, I removed the Graphiql link :-( yeah let's get that back in.

**Comment by KyleAMathews** [comment]
Fixed in https://github.com/gatsbyjs/gatsby/pull/3248
