### ISSUE TITLE
Webpack Error using Client-only routes Filesystem API

### ISSUE THREAD

**Issue by pmarxbraun** [gatsbyjs/gatsby#32465]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi,

I'm using [Filesystem API to create client-only routes](https://www.gatsbyjs.com/docs/reference/routing/file-system-route-api/#syntax-client-only-routes) with path `/pages/association/[id].js`

Running `gatsby develop` works fine
Running `gatsby build` throws me this error

```
ERROR 

Page data from page-data.json for the failed page "/association/[id]/": {
  "componentChunkName": "component---src-pages-association-[id]-js",
  "path": "/association/[id]/",
  "matchPath": "/association/:id",
  "result": {
    "pageContext": {
      "matchPath": "/association/:id"
    }
  },
  "staticQueryHashes": []
}

failed Building static HTML for pages - 0.445s

 ERROR #95313 

Building static HTML failed for path "/association/[id]/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


> 1 | export default function _defineProperty(obj, key, value) {
    |                ^
  2 |   if (key in obj) {
  3 |     Object.defineProperty(obj, key, {
  4 |       value: value,


  WebpackError: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=und
  efined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful 
  warnings.
  
  - defineProperty.js:1 
    [youggy-website]/[@babel]/runtime/helpers/esm/defineProperty.js:1:16
  
  - defineProperty.js:8 
    [youggy-website]/[@babel]/runtime/helpers/esm/defineProperty.js:8:6
  
  - static-entry.js:286 
    youggy-website/.cache/static-entry.js:286:22
  
  - history.js:82 
    [youggy-website]/[@gatsbyjs]/reach-router/es/lib/history.js:82:1
```

Can't find any solution. Thanks for you help !

### Reproduction Link

https://github.com/pmarxbraun/youggy-test

### Steps to Reproduce

Create client only routes using Filesystem API
My template lives in this file `/pages/association/[id].js`

### Expected Result

Site built normally

### Actual Result

```
ERROR 

Page data from page-data.json for the failed page "/association/[id]/": {
  "componentChunkName": "component---src-pages-association-[id]-js",
  "path": "/association/[id]/",
  "matchPath": "/association/:id",
  "result": {
    "pageContext": {
      "matchPath": "/association/:id"
    }
  },
  "staticQueryHashes": []
}

failed Building static HTML for pages - 0.445s

 ERROR #95313 

Building static HTML failed for path "/association/[id]/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


> 1 | export default function _defineProperty(obj, key, value) {
    |                ^
  2 |   if (key in obj) {
  3 |     Object.defineProperty(obj, key, {
  4 |       value: value,


  WebpackError: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=und
  efined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful 
  warnings.
  
  - defineProperty.js:1 
    [youggy-website]/[@babel]/runtime/helpers/esm/defineProperty.js:1:16
  
  - defineProperty.js:8 
    [youggy-website]/[@babel]/runtime/helpers/esm/defineProperty.js:8:6
  
  - static-entry.js:286 
    youggy-website/.cache/static-entry.js:286:22
  
  - history.js:82 
    [youggy-website]/[@gatsbyjs]/reach-router/es/lib/history.js:82:1
```

### Environment

```shell
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.0/bin/yarn
    npm: 7.14.0 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Safari: 14.1.2
  npmPackages:
    gatsby: ^3.10.1 => 3.10.1 
    gatsby-cli: ^3.5.0 => 3.10.0 
    gatsby-image: ^3.1.0 => 3.5.0 
    gatsby-plugin-gatsby-cloud: ^2.4.1 => 2.5.0 
    gatsby-plugin-google-analytics: ^3.1.0 => 3.5.0 
    gatsby-plugin-image: ^1.5.0 => 1.5.0 
    gatsby-plugin-manifest: ^3.1.0 => 3.5.0 
    gatsby-plugin-mdx: ^2.1.0 => 2.5.1 
    gatsby-plugin-offline: ^4.1.0 => 4.5.1 
    gatsby-plugin-react-helmet: ^4.1.0 => 4.5.0 
    gatsby-plugin-sharp: ^3.5.0 => 3.5.0 
    gatsby-plugin-sitemap: ^4.0.0 => 4.1.0 
    gatsby-source-filesystem: ^3.1.0 => 3.5.0 
    gatsby-transformer-sharp: ^3.5.0 => 3.5.0 
  npmGlobalPackages:
    gatsby-cli: 3.9.0
```

**Comment by barbalex** [comment]
I have the exact same error. On Windows and MacOS. Have spent about 4 hours pinning it down so far 😢. 

I finally got an error on MacOS mentioning yoga-layout-prebuilt. Which according to yarn is used by gatsby-cli.

**Comment by barbalex** [comment]
I found the culprit: 

md5-hex added 
```js
import crypto from 'node:crypto';
```
when updating from 3.0.1 to 4.0.0.

See: https://github.com/sindresorhus/md5-hex/blob/199598328d4d11b938f86a9ba9b82dc0796c8331/index.js, listed in https://github.com/sindresorhus/md5-hex/compare/v3.0.1...v4.0.0#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346

Is this an issue in md5-hex or gatsby?

**Comment by barbalex** [comment]
So it seems that webpack no longer polyfills for node.js beginning at version 5 (source: https://stackoverflow.com/a/67335037/712005). So I had to alter the webpack config to do it like this:
```js
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    resolve: {
      fallback: {
        // md5-hex uses node:crypto
        // webpack v5 does not polyfill for it any more
        // so need to do that here
        // see: https://github.com/gatsbyjs/gatsby/issues/32465#issuecomment-884255203
        // and: https://stackoverflow.com/a/67335037/712005
        crypto: require.resolve('crypto-browserify'),
      },
    },
  })
}
```
and add crypto-browserify ad dev dependency: `yarn add --dev crypto-browserify`.

Well, that's what I _thought_ would solve the issue. But id does not 😢.

**Comment by barbalex** [comment]
It seems to me that explicitly requiring from 'node:crypto' overrides any polyfills added for crypto.

So that would be the problem. Thus the issue would bi in md5-hex as it claims to be usable in the browser too ("Works in the browser too, when used with a bundler like Webpack, Rollup, Browserify.").

Does that sound correct?

**Comment by LekoArts** [comment]
@pmarxbraun The reproduction you linked doesn't work for me. Can you make sure the link is correct?

@barbalex I think your problem is unrelated to this and https://github.com/sindresorhus/md5-hex/issues/17 seems the right place to ask :)

**Comment by pmarxbraun** [comment]
@LekoArts can you try this one https://github.com/pmarxbraun/youggy-test ? Tha KS
