### ISSUE TITLE
Gatsby does not build JS files to HTML

### ISSUE THREAD

**Issue by jeffpowrs** [gatsbyjs/gatsby#3246]
I just want to say I'm a huge fan of Gatsby and am very grateful for the work your doing on this project. <3 

With that being said I'm running into a strange problem that seems to be an issue with Gatsby. 

Everything runs and loads perfectly when I am running `gatsby develop`. I do not have any errors or warnings.

And, everything compiles without errors or warnings when I run `gatsby build`.

But, when I run `gatsby serve` or look in the public folder, all the React components that should have been transformed into HTML files, are still javascript files containing my React components unchanged.

<img width="1552" alt="screen shot 2017-12-16 at 5 17 19 pm" src="https://user-images.githubusercontent.com/2141296/34075815-2578ba7c-e287-11e7-9848-3518913202be.png">

**Comment by KyleAMathews** [comment]
Look in some of the subfolders

**Comment by petrgazarov** [comment]
Seeing the same result as @jeffpowrs.

I only seem to have files with extensions `js`, `css`, `png`, and `json`, but not `html`. I'll see if I can figure out what's going on, but suggestions welcome.

**Comment by petrgazarov** [comment]
Reran `gatsby build` and it worked. Must have missed an error or other message.
