### ISSUE TITLE
Unclear how to use local plugins

### ISSUE THREAD

**Issue by MrToph** [gatsbyjs/gatsby#3251]
## Description

I can't get local plugins to work.
I followed [the documentation](https://www.gatsbyjs.org/docs/plugins/), but it then throws an error if I leave the plugin's `package.json` as an empty object `{}`. (See the JSON.parse error below)
When I specify a `main` field in the `package.json`, I don't get the error but my plugin seems to not be executed at all.

The documentation page just tells to create an empty `package.json` and a `gatsby-node.js`, but if you look at actual plugins in this repo, their structure is completely different. For example [here](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-offline), the `main` field is also specified and points to an empty `index.js` file, while the `gatsby-node.js` file is inside a `src` folder and not on the plugin's root.

This is all really confusing to me, and doing it as specified in the documentation doesn't work for me.

### Environment

Gatsby version: 1.9.119
Node.js version: v8
Operating System: Windows 10

### File contents (if changed):

`gatsby-config.js`:
```js
plugins: [
    {
      resolve: `local-plugin`, // this does not need to be a relative path, doesn't it?
      options: {
        // Setting a color is optional.
        color: `tomato`,
      },
    }
]
```

### Actual result
Running `gatsby-develop` throws an error:
```js
error UNHANDLED REJECTION


  SyntaxError: Unexpected token / in JSON at position 5

  - JSON.parse

  - load-plugins.js:65 resolvePlugin
    [gatsby-starter-blog-master]/[gatsby]/dist/bootstrap/load-plugins.js:65:32

  - load-plugins.js:147 processPlugin
    [gatsby-starter-blog-master]/[gatsby]/dist/bootstrap/load-plugins.js:147:27

  - load-plugins.js:168
    [gatsby-starter-blog-master]/[gatsby]/dist/bootstrap/load-plugins.js:168:28
```
### Expected behavior

What should happen?

My plugin should be executed.

**Comment by jquense** [comment]
plugins should be in in a `plugins` directory under your package root, and have a package.json, check out https://github.com/jquense/react-widgets/tree/master/www which has a local plugin!

**Comment by MrToph** [comment]
Thanks, setting it up like in your project works :+1:

Not sure what I did differently, I couldn't reproduce my JSON parse error anymore, even with an empty `package.json`

The other times it just looked like it was not working, because I made a default export like in [remark-plugins](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-copy-linked-files/src/index.js), and did not use one of the provided hooks.

We can close this
