### ISSUE TITLE
Not all headers present in Gatsby functions request object

### ISSUE THREAD

**Issue by xylophonehero** [gatsbyjs/gatsby#32542]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I'm using Storyblok CMS and one of their features is to pass a `webhook-signature` on the POST request header to verify the request came from Storyblok. However when I check the function logs, the `webhook-signature` header can't be found. 

I've replicated the request in Postman and also found out that locally, I can access a `webhook-signature` header but when I build on Gatsby cloud, I can't access it. 

I don't believe this is an issue with Storyblok as I have tested out it's webhook on [webhook.site](https://webhook.site/) and it works fine and I can see the `webhook-signature` header.

My logs from GC are as follows. Top is `req.headers` bottom is `req.rawHeaders`.

```
{
  host: "gatsbynickportfoliomaster.gatsbyjs.io",
  "user-agent": "PostmanRuntime/7.28.2",
  "content-length": "238",
  accept: "*/*",
  "accept-encoding": "gzip",
  "content-type": "application/json",
  "x-build-id": "8e528ec9-ec1b-43b8-8938-656344682953",
  "x-function-id": "939f7b85-6ac6-5afa-810b-cac85db2048c",
  "x-original-host": "gatsbynickportfoliomaster.gatsbyjs.io",
}

[
  "Host",
  "cloud-run-26c77bc5-9f0c-481a-8ef2-6a22fc0c32a5-prod.default.example.com",
  "User-Agent",
  "PostmanRuntime/7.28.2",
  "Content-Length",
  "238",
  "Accept",
  "*/*",
  "Accept-Encoding",
  "gzip",
  "Content-Type",
  "application/json",
  "Forwarded",
  "for=10.25.11.2;proto=http, for=10.25.8.9",
  "K-Proxy-Request",
  "activator",
  "X-B3-Sampled",
  "1",
  "X-B3-Spanid",
  "8329bbddeaee8e12",
  "X-B3-Traceid",
  "89709f38b441b1a68329bbddeaee8e12",
  "X-Build-Id",
  "8e528ec9-ec1b-43b8-8938-656344682953",
  "X-Datadog-Parent-Id",
  "2915369484288117193",
  "X-Datadog-Sampling-Priority",
  "1",
  "X-Datadog-Trace-Id",
  "2915369484288117193",
  "X-Envoy-Decorator-Operation",
  "cloud-run-26c77bc5-9f0c-481a-8ef2-6a22fc0c32a5-prod-00005.default.svc.cluster.local:80/*",
  "X-Envoy-Internal",
  "true",
  "X-Forwarded-For",
  "10.25.11.2, 10.25.8.9, 10.25.13.4",
  "X-Forwarded-Proto",
  "http",
  "X-Function-Id",
  "939f7b85-6ac6-5afa-810b-cac85db2048c",
  "X-Original-Host",
  "gatsbynickportfoliomaster.gatsbyjs.io",
  "X-Request-Id",
  "57ee61c0-45e6-97c2-9257-d64795f00cee",
]
```

Below is what I from the same function on localhost. I get a `webhook-signature` header here.
```
{
  'content-length': '238',
  connection: 'close',
  'accept-encoding': 'gzip, deflate, br',
  host: 'localhost:51358',
  'postman-token': '6d9a51c1-d235-41a2-86ff-06e271dd8396',
  accept: '*/*',
  'user-agent': 'PostmanRuntime/7.28.2',
  'content-type': 'application/json',
  'webhook-signature': '0993129a502bb5a863bcc48ab10bbd83515f8851'
}

[
  'content-length',
  '238',
  'connection',
  'close',
  'accept-encoding',
  'gzip, deflate, br',
  'host',
  'localhost:51358',
  'postman-token',
  '6d9a51c1-d235-41a2-86ff-06e271dd8396',
  'accept',
  '*/*',
  'user-agent',
  'PostmanRuntime/7.28.2',
  'content-type',
  'application/json',
  'webhook-signature',
  '0993129a502bb5a863bcc48ab10bbd83515f8851'
]
```

### Reproduction Link

https://github.com/xylophonehero/gatsby-nick-portfolio

### Steps to Reproduce

1. Create a new project with a new function which logs the `req.headers`
2. Build on Gatsby cloud
3. Try POST request to the function with a custom request header `webhook-secret`

### Expected Result

`webhook-secret` should be available on the `req.headers` object

### Actual Result

I can't find it anywhere!

### Environment

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
  Binaries:
    Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.12.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.0
  Browsers:
    Chrome: 92.0.4515.107
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.55)
  npmPackages:
    gatsby: ^3.10.2 => 3.10.2
    gatsby-plugin-gatsby-cloud: ^2.10.1 => 2.10.1
  npmGlobalPackages:
    gatsby-cli: 3.10.0
```

**Comment by LekoArts** [comment]
Hi!

We intentionally don't provide all headers and `req.rawHeaders` is a bit misleading as it doesn't represent the actual `rawHeaders`. If you want to get "non standard" headers you'll need to prefix them with `x-gatsby-`.

For feature requests on this please go to https://www.gatsbyjs.com/support/ and more specifically to https://portal.gatsbyjs.com/gatsby-cloud. Thanks!
