### ISSUE TITLE
getSavedScrollPosition is wrong after 2nd page transition without scrolling

### ISSUE THREAD

**Issue by MatthiasDunker** [gatsbyjs/gatsby#32546]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hey all,

referring to the [shouldUpdateScroll docs](https://www.gatsbyjs.com/docs/reference/config-files/gatsby-browser/#shouldUpdateScroll), I experienced an unexpected behavior.

I would think that `getSavedScrollPosition(prevRouterProps.location)` would always return the coords of the last page (if there is one). But instead it only gives the right coords if the last page had been scrolled.

See the example code and follow the steps for a better understanding: [https://codesandbox.io/s/busy-gould-kq0or?file=/gatsby-browser.js](https://codesandbox.io/s/busy-gould-kq0or?file=/gatsby-browser.js)

### Reproduction Link

https://codesandbox.io/s/busy-gould-kq0or?file=/gatsby-browser.js

### Steps to Reproduce

Written down in the sandbox: [https://codesandbox.io/s/busy-gould-kq0or?file=/gatsby-browser.js](https://codesandbox.io/s/busy-gould-kq0or?file=/gatsby-browser.js)

### Expected Result

I would think that `getSavedScrollPosition(prevRouterProps.location)` would always return the coords of the last page (if there is one).

### Actual Result

It just does if the last scrolled had been scrolled or rather the scroll event had been triggered.

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.13.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.12.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 92.0.4515.107
    Firefox: 89.0.2
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.10.2 => 3.10.2
    gatsby-plugin-emotion: ^6.6.0 => 6.6.0
    gatsby-plugin-gatsby-cloud: ^2.6.1 => 2.6.1
    gatsby-plugin-image: ^1.6.0 => 1.6.0
    gatsby-plugin-manifest: ^3.6.0 => 3.6.0
    gatsby-plugin-postcss: ^4.6.0 => 4.6.0
    gatsby-plugin-react-helmet: ^4.6.0 => 4.6.0
    gatsby-plugin-sharp: ^3.6.0 => 3.6.0
    gatsby-plugin-sitemap: ^4.2.0 => 4.2.0
    gatsby-source-filesystem: ^3.7.1 => 3.7.1
    gatsby-source-strapi: ^1.0.1 => 1.0.1
    gatsby-transformer-sharp: ^3.6.0 => 3.6.0
  npmGlobalPackages:
    gatsby-cli: 3.5.0
    gatsby: 3.3.1
```

### Config Flags

DEV_SSR: false

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

The parameter description is this:

> Takes a location and returns the coordinates of the last scroll position for that location, or null.

But I can understand that this might get lost in the docs.

We'd be happy to receive a PR clarifying the information that you either get the result or `null` depending on whether a scroll happend or not. I needs to be changed here:

https://github.com/gatsbyjs/gatsby/blob/15100915364ad6ea538d5384076260935e7967a6/packages/gatsby/src/utils/api-browser-docs.ts#L75-L105
