### ISSUE TITLE
webpack error due to flow types when using gatsby-plugin-flow 

### ISSUE THREAD

**Issue by montemishkin** [gatsbyjs/gatsby#32556]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi all, I'm creating a new issue here because I'm unsure if [my comment on this closed issue](https://github.com/gatsbyjs/gatsby/issues/32060#issuecomment-884672752) triggered notifications or not since that issue is closed.

Apologies if this is inappropriate. I'm not super familiar with the social conventions around resurrecting closed issues.

My assessment of the bug is that the flow types are not being stripped during transpilation, so presumably the babel config is not quite right. But that's just a guess based on super minimal understanding of how y'all have everything hooked up.

### Reproduction Link

https://github.com/montemishkin/repro-issue-gatsby-plugin-flow

### Steps to Reproduce

# from scratch
```
npm init gatsby
# go with all the defaults
npm add gatsby-plugin-flow
# add 'gatsby-plugin-flow' to gatsby-config.js
# add some flow types to src/pages/index.js
npm run develop
# webpack build fails due to parsing error from the flow types
```

# from my reproduction repo
```
git clone git@github.com:montemishkin/repro-issue-gatsby-plugin-flow.git
npm install
npm run develop
```

### Expected Result

webpack build with no issue

### Actual Result

webpack build fails
```
/Users/monte/mdv/my-gatsby-site/src/pages/index.js
  2:17  error  Parsing error: Unexpected token, expected "," (2:17)

✖ 1 problem (1 error, 0 warnings)
```

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.5.0 - ~/.nvm/versions/node/v16.5.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v16.5.0/bin/yarn
    npm: 7.19.1 - ~/.nvm/versions/node/v16.5.0/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 92.0.4515.107
    Safari: 14.0.1
  npmPackages:
    gatsby: ^3.9.1 => 3.10.1 
    gatsby-plugin-flow: ^2.10.0 => 2.10.0
```

### Config Flags

nope

**Comment by GemN** [comment]
current workaround if someone need:

`yarn add @babel/preset-flow"`

And add in your .babelrc

```
{
  "presets": [
    ...
    ["@babel/preset-flow"]
  ]
}

```
