### ISSUE TITLE
Gatsby Node APIs `onCreateNode` caching mechanism?

### ISSUE THREAD

**Issue by baseten** [gatsbyjs/gatsby#3260]
Is there a caching mechanism applied to Gatsby data nodes? I'm writing a custom plugin and during testing, I noticed that `onCreateNode` isn't getting called every time I run `gatsby dev`, is there some sort of cache which prevents it being run too frequently? I'm using gatsby 1.9.52

**Comment by KyleAMathews** [comment]
Yes — Gatsby automatically caches the results of all data processing.

During development you can "solve" this by deleting the .cache directory in between runs. Long-term the plan is to enable a cli flag to disable the cache for when doing development.

**Comment by baseten** [comment]
OK, that's useful anyway as I was looking into creating a cache of my own, but perhaps it's no longer necessary. What will invalidate the cache in production? 

I've written a custom plugin that takes tweet ids stored in contentful and downloads the tweets from the twitter api. The tweet data is then added to the contentful data node using `createNodeField`. I don't want to hit the twitter api any more than is necessary, so was going to cache the results in a JSON file and only download new tweets.

**Comment by KyleAMathews** [comment]
Yeah, caching is taken care of automatically. In production, if the contentful data hasn't updated, then your plugin won't get called and all the custom twitter data you've fetched in the past will get served from cache. But if someone does update the tweet ids, then your plugin will get called so you can fetch new data.

**Comment by baseten** [comment]
OK, as the tweets will change infrequently, I think I may create a separate cache of my own as I only really want to call the API for new and changed tweets. Would saving a JSON file to the gatsby .cache folder work, or should I put it somewhere else?

**Comment by KyleAMathews** [comment]
Oh ok — yeah. Gatsby has a simple key/value cache API you can use that stores data in .cache — https://github.com/gatsbyjs/gatsby/blob/dcfa0fab32e168c075c052dde7ecd97736c6147a/packages/gatsby-transformer-remark/src/extend-node-type.js#L70

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
