### ISSUE TITLE
Gatsby Word press Source - images beings saved in static with - removed and replaced with ' ' empty space

### ISSUE THREAD

**Issue by garryburch** [gatsbyjs/gatsby#32683]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Gatsby Word press Source - images beings saved in static with - removed and replaced with ' ' empty space

### Reproduction Link

https://gatsby.dev/reproduction - @TylerBarnes said I could skip this

### Steps to Reproduce

1. gatsbyu build or develop
2. review static publicURL
3.
...

### Expected Result

/static/asd9asd980a09asd890089a/fractory-image-v1.png

### Actual Result

/static/asd9asd980a09asd890089a/fractory image v1.png

### Environment

```shell
System:
    OS: Linux 5.4 KDE neon 5.22
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.21.0/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.21.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Firefox: 90.0
  npmPackages:
    gatsby: ^2.30.1 => 2.32.9
    gatsby-background-image: ^0.8.15 => 0.8.19
    gatsby-cli: ^2.19.1 => 2.19.2
    gatsby-image: ^2.4.13 => 2.11.0
    gatsby-plugin-algolia: ^0.17.0 => 0.17.0
    gatsby-plugin-breadcrumb: ^12.1.1 => 12.1.1
    gatsby-plugin-canonical-urls: ^2.3.6 => 2.10.0
    gatsby-plugin-csp: ^1.1.3 => 1.1.3
    gatsby-plugin-feed: ^2.5.11 => 2.13.1
    gatsby-plugin-google-tagmanager: ^2.1.13 => 2.11.0
    gatsby-plugin-manifest: ^2.2.21 => 2.12.1
    gatsby-plugin-netlify: ^2.3.13 => 2.11.0
    gatsby-plugin-netlify-functions: ^0.0.3 => 0.0.3
    gatsby-plugin-postcss: ^2.1.11 => 2.3.13
    gatsby-plugin-react-helmet: ^3.1.11 => 3.10.0
    gatsby-plugin-react-svg: ^2.1.2 => 2.1.2
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-remove-trailing-slashes: ^2.8.0 => 2.10.0
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5
    gatsby-plugin-sass: ^2.1.18 => 2.8.0
    gatsby-plugin-sharp: ^2.2.32 => 2.14.3
    gatsby-plugin-sitemap: ^2.2.17 => 2.12.0
    gatsby-plugin-styled-components: ^3.3.4 => 3.10.0
    gatsby-source-atom: ^0.3.0 => 0.3.0
    gatsby-source-filesystem: ^2.1.31 => 2.11.1
    gatsby-source-wordpress: ^4.0.5 => 4.0.5
    gatsby-transformer-sharp: ^2.2.21 => 2.12.0
  npmGlobalPackages:
    gatsby-cli: 3.10.0
```

### Config Flags

    PRESERVE_WEBPACK_CACHE: true,
    PRESERVE_FILE_DOWNLOAD_CACHE: true,

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
