### ISSUE TITLE
gatsby develops throws error "TypeError: Expected pattern to be a non-empty string"

### ISSUE THREAD

**Issue by SAYEED05** [gatsbyjs/gatsby#32691]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I have searched through the issues,there are many similar ones but not with this error message.
When i created a new gatsby project by `gatsby new` or `npm init gatsby` and tried to run `gatsby develop` or `npm run develop` this error occurs

```
D:\[Web dev]\gatsby-test\my-gatsby-site>npm run develop

> my-gatsby-site@1.0.0 develop D:\[Web dev]\gatsby-test\my-gatsby-site
> gatsby develop

info Cache exists but contains no nodes. There should be at least some nodes available so it seems the cache was corrupted. Disregarding the cache and proceeding as if there was none.
success open and validate gatsby-configs, load plugins - 0.154s
success onPreInit - 0.024s
success initialize cache - 0.017s
success copy gatsby files - 0.152s

D:\[Web dev]\gatsby-test\my-gatsby-site\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

TypeError: Expected pattern to be a non-empty string
    at picomatch (D:\[Web dev]\gatsby-test\my-gatsby-site\node_modules\picomatch\lib\picomatch.js:48:11)
    at createPattern (D:\[Web dev]\gatsby-test\my-gatsby-site\node_modules\anymatch\index.js:27:18)
    at D:\[Web dev]\gatsby-test\my-gatsby-site\node_modules\anymatch\index.js:91:21
    at Array.map (<anonymous>)
    at anymatch (D:\[Web dev]\gatsby-test\my-gatsby-site\node_modules\anymatch\index.js:91:6)
    at D:\[Web dev]\gatsby-test\my-gatsby-site\node_modules\chokidar\index.js:272:51
    at Array.every (<anonymous>)
    at D:\[Web dev]\gatsby-test\my-gatsby-site\node_modules\chokidar\index.js:270:22
    at Array.some (<anonymous>)
    at WatchHelper.filterDir (D:\[Web dev]\gatsby-test\my-gatsby-site\node_modules\chokidar\index.js:269:43)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (D:\[Web dev]\gatsby-test\my-gatsby-site\node_modules\chokidar\index.js:647:10)
    at ReaddirpStream.NodeFsHandler._boundHandleError (D:\[Web dev]\gatsby-test\my-gatsby-site\node_modules\chokidar\lib\nodefs-handler.js:303:43)
    at ReaddirpStream.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
⠋ onPreBootstrap
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! my-gatsby-site@1.0.0 develop: `gatsby develop`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the my-gatsby-site@1.0.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sayee\AppData\Roaming\npm-cache\_logs\2021-08-04T03_00_10_029Z-debug.log
```
`gatsby build` and `gatsby serve` works fine

### Reproduction Link

gatsby new https://github.com/gatsbyjs/gatsby-starter-hello-world - i haven't added any code or files after generating the starter pack using this link

### Steps to Reproduce

1.create new gatsby project by `npm init gatsby` or `gatsby new `
2.try to run `gatsby develop` or `npm run develop`

### Expected Result

start devlopment in localhost:8000

### Actual Result

D:\[Web dev]\gatsby-test\my-gatsby-site\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

TypeError: Expected pattern to be a non-empty string

### Environment

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
  Binaries:
    Node: 14.17.4 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.5
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.62)
  npmPackages:
    gatsby: ^3.10.2 => 3.10.2 
  npmGlobalPackages:
    gatsby-cli: 3.10.0
```

**Comment by LekoArts** [comment]
Hi!

I followed your steps best as I can (on WSL2 on Windows) and I can't reproduce. Please give more details and also try your steps on different machines if you have those available. Thanks!

**Comment by LekoArts** [comment]
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!
