### ISSUE TITLE
Error: UNHANDLED REJECTION write EPIPE (v3.10.2)

### ISSUE THREAD

**Issue by sniperyork** [gatsbyjs/gatsby#32697]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I believe this issue has been reported before, but it looks like it is still happening in the latest version of gatsby (v3.10.2).
Every time when I try to shut down the server, the following error happens.

![Screen Shot 2021-08-04 at 11 07 31 AM](https://user-images.githubusercontent.com/16144192/128232237-44be7e43-a08a-4e7e-bf02-56cd2c5f6994.png)

### Reproduction Link

https://github.com/sniperyork/bug-repo

### Steps to Reproduce

1. Start a new project via gatsby new project command
2. gatsby develop
3. Ctrl + C to shut down the server
4. Error occurs
...

### Expected Result

Server shuts down without errors

### Actual Result

The following error occurs:

` ERROR 

UNHANDLED REJECTION write EPIPE

  Error: write EPIPE
  
  - child_process.js:839 ChildProcess.target._send
    internal/child_process.js:839:20
  
  - child_process.js:710 ChildProcess.send
    internal/child_process.js:710:19
  
  - develop.ts:133 ControllableScript.stop
    [montessori]/[gatsby]/src/commands/develop.ts:133:22
  
  - develop.ts:540 shutdownServices
    [montessori]/[gatsby]/src/commands/develop.ts:540:28
  
  - develop.ts:467 process.<anonymous>
    [montessori]/[gatsby]/src/commands/develop.ts:467:11`

### Environment

```shell
System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - /usr/local/bin/node
    npm: 7.20.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 92.0.4515.107
    Firefox: 88.0
    Safari: 14.1.1
  npmPackages:
    gatsby: ^3.10.2 => 3.10.2
    gatsby-plugin-gatsby-cloud: ^2.10.0 => 2.10.0
    gatsby-plugin-image: ^1.10.1 => 1.10.1
    gatsby-plugin-manifest: ^3.10.0 => 3.10.0
    gatsby-plugin-offline: ^4.10.0 => 4.10.0
    gatsby-plugin-react-helmet: ^4.10.0 => 4.10.0
    gatsby-plugin-sharp: ^3.10.2 => 3.10.2
    gatsby-plugin-styled-components: ^4.10.0 => 4.10.0
    gatsby-source-filesystem: ^3.10.0 => 3.10.0
    gatsby-transformer-sharp: ^3.10.0 => 3.10.0
  npmGlobalPackages:
    gatsby-cli: 3.10.0
```

**Comment by chhpt** [comment]
Same issue in gatsby v3.11.0 when using `Ctrl + C`

![image](https://user-images.githubusercontent.com/19288423/128468616-b877ecaa-ef76-4cc8-a557-2a199f51922a.png)

**Comment by gh640** [comment]
It looks like #28011 is for the same issue.

**Comment by LekoArts** [comment]
I'm closing this in favor of https://github.com/gatsbyjs/gatsby/issues/28011
