### ISSUE TITLE
Shopify Bulk operation failing on new release [Gatsby v3.11.0] [Shopify v5.3.0]

### ISSUE THREAD

**Issue by AsathalMannan** [gatsbyjs/gatsby#32702]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [x] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

After updating all the packages to new release v3.11.0.
build failing on quering bulk operations for `PRODUCT_VARIANTS`

Tried running old deployment again with cloudflare it works perfectly with same API credentials.
only with new package versions its failing during bulk operations.

### Reproduction Link

https://github.com/AsathalMannan/build_failed_shopify_gatsby

### Steps to Reproduce

1. npm run develop
or
1. npm run build

### Expected Result

```shell
info Initiating bulk operation query PRODUCT_VARIANTS
--

success Waiting for bulk operation to complete - 7.682s -
Polling bulk operation: gid://shopify/BulkOperation/348077850755
Status: COMPLETED
Object count: 1067

info Completed bulk operation PRODUCT_VARIANTS:
gid://shopify/BulkOperation/348077850755

info Creating nodes from bulk operation PRODUCT_VARIANTS

success Source from bulk operation PRODUCT_VARIANTS - 8.905s - Processing 1067
results for PRODUCT_VARIANTS: gid://shopify/BulkOperation/348077850755

success Waiting for operation gid://shopify/BulkOperation/348077850755 :
COMPLETED - 0.001s
```

### Actual Result

```shell
> rayhan-web@2.0.0 develop
> gatsby develop

success open and validate gatsby-configs, load plugins - 0.840s
success onPreInit - 0.074s
success initialize cache - 0.112s
success copy gatsby files - 0.115s
success Compiling Gatsby Functions - 0.341s
success onPreBootstrap - 0.368s
success createSchemaCustomization - 0.019s

info Cache is cold, running a clean build
success Waiting for operation gid://shopify/BulkOperation/348077883523 : COMPLETED - 0.003s

info Initiating bulk operation query PRODUCTS
success Waiting for bulk operation to complete - 23.012s -
Polling bulk operation: gid://shopify/BulkOperation/348080177283
Status: COMPLETED
Object count: 4347

info Completed bulk operation PRODUCTS: gid://shopify/BulkOperation/348080177283
info Creating nodes from bulk operation PRODUCTS
success Source from bulk operation PRODUCTS - 27.956s - Processing 4347 results for PRODUCTS:
gid://shopify/BulkOperation/348080177283
success Waiting for operation gid://shopify/BulkOperation/348080177283 : COMPLETED - 0.002s

info Initiating bulk operation query PRODUCT_VARIANTS
success Waiting for bulk operation to complete - 4.096s -
Polling bulk operation: gid://shopify/BulkOperation/348080210051
Status: FAILED
Object count: 0


 ERROR #gatsby-source-shopify_111000 

Your credentials don't have access to a resource you requested



  **Error: Operation gid://shopify/BulkOperation/348080210051 failed with ACCESS_DENIED**
  
  - operations.ts:190 completedOperation
    [RayhanWeb]/[gatsby-source-shopify]/src/operations.ts:190:15
  
  - runMicrotasks
  
  - task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
  
  - make-source-from-operation.ts:63 sourceFromOperation
    [RayhanWeb]/[gatsby-source-shopify]/src/make-source-from-operation.ts:63:20
  
  - gatsby-node.ts:88 sourceAllNodes
    [RayhanWeb]/[gatsby-source-shopify]/src/gatsby-node.ts:88:5
  
  - gatsby-node.ts:210 Object.sourceNodes
    [RayhanWeb]/[gatsby-source-shopify]/src/gatsby-node.ts:210:5
  
  - api-runner-node.js:432 runAPI
    [RayhanWeb]/[gatsby]/src/utils/api-runner-node.js:432:16
  

not finished source and transform nodes - 33.860s
not finished Source from bulk operation PRODUCT_VARIANTS - 5.807s
```

### Environment

```shell
System:
  OS: Zorin OS 16
  CPU: Core i3 2nd Gen
Binaries:
  Node: 16.6.1
  Npm: 7.20.3
npmPackages:
  gatsby: 3.11.0
  gatsby-plugin-google-gtag: 3.11.0
  gatsby-plugin-image: 1.11.0
  gatsby-plugin-react-helmet: 4.11.0
  gatsby-plugin-sass: 4.11.0
  gatsby-plugin-sharp: 3.11.0
  gatsby-plugin-sitemap: 4.7.0
  gatsby-plugin-styled-components: 4.11.0
  gatsby-source-filesystem: 3.11.0
  gatsby-source-prismic: 4.0.2
  gatsby-source-shopify: 5.3.0
  gatsby-transformer-sharp: 3.11.0
  @apollo/client: 3.4.5
  react: 17.0.2
  react-bootstrap: next
  react-dom: 17.0.2
  react-helmet: 6.1.0
```

**Comment by matthewkwong2** [comment]
Kind of related to https://github.com/gatsbyjs/gatsby/issues/32704

**Comment by DanielSLew** [comment]
Hi @AsathalMannan,

I looked into this. I tried it out on our shopify starter with the same versions of `gatsby` and `gatsby-source-shopify` and it worked fine. I then pulled down your repo and tried it out and it worked fine. I'm guessing this has to do with your shopify shop permissions. For the new version of `gatsby-source-shopify` we added information about locations, so my guess if anything it has to do with needing permissions to read location information.

Let me know if this helps

**Comment by DanielSLew** [comment]
I was able to reproduce this error when I disabled Inventory access
![image](https://user-images.githubusercontent.com/51924260/128360789-f537d5bc-ae85-4758-9e32-e87cd117a250.png)

So for the time being you'll need to allow access to Inventory to enable this. I'll add it to the next release where it will only add the new part of the query if you explicitly opt in to `locations` so you won't need to worry about these extra permissions.

Thanks for catching this!

**Comment by AsathalMannan** [comment]
> I was able to reproduce this error when I disabled Inventory access
> ![image](https://user-images.githubusercontent.com/51924260/128360789-f537d5bc-ae85-4758-9e32-e87cd117a250.png)
> 
> So for the time being you'll need to allow access to Inventory to enable this. I'll add it to the next release where it will only add the new part of the query if you explicitly opt in to `locations` so you won't need to worry about these extra permissions.
> 
> Thanks for catching this!

@DanielSLew Thanks lot,.. issue fixed after giving READ access to Inventory.
