### ISSUE TITLE
Create a new site. gatsby new gatsby-site is not working

### ISSUE THREAD

**Issue by kahmad07** [gatsbyjs/gatsby#3270]
## Description

Trying to set up gatsby locally for the first time, encountering an issue while executing gatsby new gatsby-site command.

Steps complete so far:
- Update node and nvm with latest versions.
- Successfully installed Gatsby command line tool.

The place where I am stuck:
When I try to execute gatsby new gatsby-site, which I guess help me clone the repository gives me below error. 

error Command failed: git clone git://github.com/gatsbyjs/gatsby-starter-default.git gatsby-site --single-branch

I understand it might be a firewall issue at my end because the command uses git:// instead of https://. As a way out I try to manually clone the repository by using https instead of git 
 **git clone https://github.com/gatsbyjs/gatsby-starter-default.git gatsby-site --single-branch**
It lets me clone repository successfully, I cd into gatsby-site directory, however, post that when I try to execute **gatsby develop** command it throws me this error 

**error There was a problem loading the local develop command. Gatsby may not be installed.**

Need help in resolving this issue also want to understand that besides cloning repository what else the command gatsby new gatsby-site does? If it helps in just cloning then why after manual cloning using https I am getting above mentioned error?

### Environment

Gatsby version: 1.1.27 (cli)
Node.js version: 8.9.3
Operating System: Mac X EL Capiton v10.11.6

### File contents (if changed):

`gatsby-config.js`: 
`package.json`: 
`gatsby-node.js`: 
`gatsby-browser.js`: 
`gatsby-ssr.js`: 

### Actual result

What happened.

### Expected behavior

What should happen?

### Steps to reproduce

1\.

2\.

3\.

...

**Comment by KyleAMathews** [comment]
It does sound like a git error.

The steps gatsby new runs are:

1. git clone
2. Runs `npm install`

It sounds like you just need to run `npm install` in your manually cloned directory.
