### ISSUE TITLE
[gatsby-source-shopify] Build fails on Bulk operation in Shopify store with metafields

### ISSUE THREAD

**Issue by hudsonandtask** [gatsbyjs/gatsby#32722]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Last week we were using
"gatsby-source-shopify": "rc",

We had some bulk operation failures on wednesday and on thursday we updated to gatsby-source-shopify 5.2.1. Which worked until monday.

On Monday we started getting a failure around the product_variant step of the process.

![Screen Shot 2021-08-06 at 4 16 35 PM](https://user-images.githubusercontent.com/5720950/128569939-298be189-28ca-4a04-9d86-c80666e2ed73.png)

We've also tried gatsby-source-shopify 5.3.0.

We don't have that many products 1000 or so with Metafields.

We're noticing metafields in shopify have changed (definitions?) and we're able to get the source plugin to work in another environment without metafields, same product count and configuration.

### Reproduction Link

https://github.com/hudsonandtask/gatsbybulkerrorMetafields

### Steps to Reproduce

1. Run Gatsby Build or Gatsby Develop 
2.  Build will error sourcing products
3.
...

### Expected Result

Build to complete sourcing all products with metafields 

### Actual Result

Build fails with the following errors:

 gatsby build
success open and validate gatsby-configs, load plugins - 1.239s
success onPreInit - 0.039s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's no stale data.
success initialize cache - 0.047s
success copy gatsby files - 0.124s
success Compiling Gatsby Functions - 0.340s
success onPreBootstrap - 0.359s
success createSchemaCustomization - 0.011s
info Cache is cold, running a clean build
success Waiting for operation gid://shopify/BulkOperation/474194149544 : FAILED - 0.002s
info Initiating bulk operation query PRODUCTS
success Waiting for bulk operation to complete - 131.175s -
Polling bulk operation: gid://shopify/BulkOperation/474208895144
Status: FAILED
Object count: 1353

 ERROR #gatsby-source-shopify_111001 

Operation PRODUCTS failed after 1353 objects
- With status: FAILED - error code: INTERNAL_SERVER_ERROR

  Error: Operation gid://shopify/BulkOperation/474208895144 failed with INTERNAL_SERVER_ERROR
  
  - operations.ts:190 completedOperation
    [rccommence-store]/[gatsby-source-shopify]/src/operations.ts:190:15
  
  - runMicrotasks
  
  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5
  
  - make-source-from-operation.ts:63 sourceFromOperation
    [rccommence-store]/[gatsby-source-shopify]/src/make-source-from-operation.ts:63:20
  
  - gatsby-node.ts:88 sourceAllNodes
    [rccommence-store]/[gatsby-source-shopify]/src/gatsby-node.ts:88:5
  
  - gatsby-node.ts:210 Object.sourceNodes
    [rccommence-store]/[gatsby-source-shopify]/src/gatsby-node.ts:210:5
  
  - api-runner-node.js:432 runAPI
    [rccommence-store]/[gatsby]/src/utils/api-runner-node.js:432:16
  

not finished source and transform nodes - 132.682s
not finished Source from bulk operation PRODUCTS - 132.617s

### Environment

```shell
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    npm: 6.14.13 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 92.0.4515.131
    Edge: 92.0.902.67
    Firefox: 82.0.3
    Safari: 14.1.2
  npmPackages:
    gatsby: ^3.10.2 => 3.10.2 
    gatsby-plugin-gatsby-cloud: ^2.4.1 => 2.5.0 
    gatsby-plugin-image: ^1.4.0 => 1.5.0 
    gatsby-plugin-react-helmet: ^4.4.0 => 4.5.0 
    gatsby-plugin-sharp: ^3.4.1 => 3.5.0 
    gatsby-plugin-sitemap: ^4.0.0 => 4.1.0 
    gatsby-source-filesystem: ^3.4.0 => 3.5.0 
    gatsby-source-shopify: ^5.2.1 => 5.3.0 
    gatsby-transformer-sharp: ^3.4.0 => 3.5.0 
  npmGlobalPackages:
    gatsby-cli: 3.3.0
```

### Config Flags

  flags: {
    FAST_DEV: true,
    DEV_SSR: false
  },

**Comment by hudsonandtask** [comment]
Aug 9 Update: I've updated all of the gatsby plugins in my project to the following and still get the build error. 

    "gatsby": "^3.11.0",
    "gatsby-plugin-gatsby-cloud": "^2.11.0",
    "gatsby-plugin-image": "^1.11.0",
    "gatsby-plugin-react-helmet": "^4.11.0",
    "gatsby-plugin-sharp": "^3.11.0",
    "gatsby-plugin-sitemap": "^4.7.0",
    "gatsby-source-filesystem": "^3.11.0",
    "gatsby-source-shopify": "^5.3.0",
    "gatsby-transformer-sharp": "^3.11.0",




 ERROR #gatsby-source-shopify_111001 


Operation PRODUCTS failed after 1353 objects
- With status: FAILED - error code: INTERNAL_SERVER_ERROR




  Error: Operation gid://shopify/BulkOperation/476570058920 failed with INTERNAL_SERVER_ERROR

**Comment by DanielSLew** [comment]
Thanks for providing all the information @hudsonandtask I'm looking into this now. You mention Shopify has changed their definition of metafields, where do you see this change?

I've narrowed it down to the `valueType` field of the `metafields` gql query
```
                    metafields {
                      edges {
                        node {
                          createdAt
                          description
                          id
                          key
                          legacyResourceId
                          namespace
                          ownerType
                          updatedAt
                          value
                          valueType
                        }
                      }
                    }
```

When I remove `valueType` it works. I'm not sure why this is throwing an error with your shop. Are you using an invalid `valueType`? or is there maybe a `valueType` set to `null`? https://shopify.dev/api/admin/graphql/reference/metafields/metafieldvaluetype

**Comment by hudsonandtask** [comment]
@DanielSLew I was refering to these metafields definitions we're seeing in our shopify backend. 

These seem new-ish to me, but i'm unsure of when these appeared. 

![Screen Shot 2021-08-09 at 10 38 35 AM](https://user-images.githubusercontent.com/5720950/128724942-23940365-988d-416c-8d60-fc66657ed06b.png)

![Screen Shot 2021-08-09 at 10 38 17 AM](https://user-images.githubusercontent.com/5720950/128725433-d9cdf222-d7c3-4fdf-b396-def5b81d5b60.png)

When we initially did our product load in this environment we didn't have anything like a Metafield definition defined. 

Thinking that might be the issue I applied definitions to our 5 product metafields which still didnt resolve the issue. 

I'll work with another developer to check the Value type thing. Thank you.

**Comment by DanielSLew** [comment]
It looks like Shopify has deprecated the `valueType` field in exchange for a more robust `type` field in the latest API. It seems like it may be an error on their side with accidentally deprecating it in older versions of the API as well, so we might have to get rid of the `valueType` field. I'm guessing they've added the more robust type definitions on your store if it's newer, whereas the shopify plugin uses a version that does not account for the new field `type`.

Let me know if you're able to fix the `valueType` thing on your end, if not, chances are this is going to be a problem for other stores as well.

**Comment by hudsonandtask** [comment]
@DanielSLew Ok thats super helpful thanks, we're looking into valueType now.

**Comment by hudsonandtask** [comment]
@DanielSLew Hi I created an issue with shopify and they got back to me with the following. 
Hope this is helpful. 

_Thanks again for your patience on this. 

Our escalation team was able to find the following workarounds.

The valueType field on a metafield is a field scheduled for deprecation being replaced with the type field in 2021-07 and above. The work arounds are:


	
Update the API calls to version 2021-07 and use the metafield type field instead of valueType in the metafields portion of the bulk query.
	
If using the most recent API version is not ideal for their team, and the metafield type is not being used by the calling app they could exclude the valueType field from the metafields portion of the bulk query._

**Comment by DanielSLew** [comment]
@hudsonandtask thanks for the update! Not an ideal handling of deprecating a gql field but I'm going to look into what it would take to update the API to the newest. If it's a big ordeal, I'll likely release a fix that just removes the field.

**Comment by hudsonandtask** [comment]
@DanielSLew Man serious re: Deprecation. Thanks a lot for taking a look!

**Comment by iamaminemesbah** [comment]
> @hudsonandtask thanks for the update! Not an ideal handling of deprecating a gql field but I'm going to look into what it would take to update the API to the newest. If it's a big ordeal, I'll likely release a fix that just removes the field.

any ETA?

**Comment by DanielSLew** [comment]
@hudsonandtask @sonomesbah here's a canary version I released that updates the API version and hopefully fixes the issues. Try it out here and let me know if it works `gatsby-source-shopify@5.4.0-alpha-gatsby-source-shopify.9`

**Comment by sonomesbah** [comment]
> @hudsonandtask @sonomesbah here's a canary version I released that updates the API version and hopefully fixes the issues. Try it out here and let me know if it works `gatsby-source-shopify@5.4.0-alpha-gatsby-source-shopify.9`

It works!!!

**Comment by lchristina26** [comment]
I know this is a WIP, but I am also getting a similar issue on the 5.3.0. I can get past it with the above suggested version of `5.4.0-alpha-gatsby-source-shopify.9`, but get a new issue:
```
Error: query: Invalid bulk query: Argument 'if' on Directive 'include' has an invalid value (undefined). Expected type 'Boolean!'.
```

**Comment by DanielSLew** [comment]
> I know this is a WIP, but I am also getting a similar issue on the 5.3.0. I can get past it with the above suggested version of `5.4.0-alpha-gatsby-source-shopify.9`, but get a new issue:
> 
> ```
> Error: query: Invalid bulk query: Argument 'if' on Directive 'include' has an invalid value (undefined). Expected type 'Boolean!'.
> ```

I've got a fix for this issue up in this PR https://github.com/gatsbyjs/gatsby/pull/32775
I think this error is because you have no `shopifyConnections` so to temporarily fix this, you can add and empty array to `shopifyConnections` in your pluginOptions in `gatsby-config` for example:

```
  plugins: [
    {
      resolve: "gatsby-source-shopify",
      options: {
        password: process.env.SHOPIFY_SHOP_PASSWORD,
        storeUrl: process.env.GATSBY_SHOPIFY_STORE_URL,
        shopifyConnections: [],
      },
    },
```

**Comment by hudsonandtask** [comment]
This issue is addressed for me.
