### ISSUE TITLE
Setting cropFocus to attention or entropy crashes Gatsby

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#32720]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

You can set custom cropFocus strategies with gatsby-plugin-image (see https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-plugin-image/#transformoptions)

This generally works fine but if you try to set it to `entropy` or `attention` it fails with this error:

```
error converting image Processing
/Users/kylemathews/programs/gatsby/examples/using-gatsby-image/.cache/caches/gatsby-plugin-image/db148be6b48f9dfcfa151d035fc34218/photo-1597305877032-0668b3c6413a.jpg failed

Original error:

Expected valid fit for fit but received top of type string



  WorkerError: Processing /Users/kylemathews/programs/gatsby/examples/using-gatsby-image/.cache/caches/gatsby-plugin-image/db148be6b48f9dfcfa151d035fc34218/photo-1597305877032-0668b3c6413a.jpg fai
  led
  Original error:
  Expected valid fit for fit but received top of type string

  - manager.ts:291 enqueueJob
    [using-gatsby-image]/[gatsby]/src/utils/jobs/manager.ts:291:13
```

The problem is attention/entropy are numeric codes defined in the sharp package. `attention` is the default and we set it like this:

https://github.com/gatsbyjs/gatsby/blob/59a6287a11eb5b136e3e681e7d1d1c08d169b601/packages/gatsby-plugin-sharp/src/image-data.ts#L117

So for user set `attention`/`entropy` settings to work, we need to check for those strings and then replace it with the var set on the `sharp` package.

### Reproduction Link

https://github.com/gatsbyjs/gatsby/blob/master/examples/using-gatsby-image/README.md

### Steps to Reproduce

Create a `<StaticImage>` component with `cropFocus` set to `entropy` like:

```
<StaticImage
  src="image.jpg"
  transformOptions={{cropFocus: `entropy`}}
/>
```

Notice that `cropFocus: "north"` works (as do other strategies https://sharp.pixelplumbing.com/api-resize#resize

### Expected Result

No error 

### Actual Result

Error

### Environment

```shell
n/a
```

**Comment by nategiraudeau** [comment]
@KyleAMathews I can work on this issue.

**Comment by KyleAMathews** [comment]
@nategiraudeau thanks!

**Comment by nategiraudeau** [comment]
Would this fix the problem?:

replace
```ts
const {
  fit = `cover`,
  cropFocus = sharp.strategy.attention,
  duotone,
} = transformOptions
```

with

```ts
const { fit = `cover`, duotone } = transformOptions

let cropFocus = transformOptions.cropFocus || `attention`

if (cropFocus === `attention` || cropFocus === `entropy`) {
  cropFocus = sharp.strategy[cropFocus]
}
```

**Comment by KyleAMathews** [comment]
that looks right yup! Best thing is to setup your local environment with a site that's fails with this error and then make sure the fix makes it work https://www.gatsbyjs.com/contributing/setting-up-your-local-dev-environment/

**Comment by nategiraudeau** [comment]
I'm having trouble reproducing the issue. I created a `StaticImage` with `transformOptions={{cropFocus: 'entropy'}}`, but I didn't get any errors and it just worked the way it's supposed to.

**Comment by KyleAMathews** [comment]
Can you share your code?

**Comment by nategiraudeau** [comment]
package.json:
```json
{
    "name": "test-32720",
    "version": "1.0.0",
    "keywords": [
        "gatsby"
    ],
    "scripts": {
        "develop": "gatsby develop",
        "start": "gatsby develop",
        "build": "gatsby build",
        "serve": "gatsby serve",
        "clean": "gatsby clean"
    },
    "dependencies": {
        "gatsby": "^3.13.0",
        "gatsby-plugin-image": "^1.13.0",
        "gatsby-plugin-sharp": "^3.13.0",
        "gatsby-source-filesystem": "^3.13.0",
        "gatsby-transformer-sharp": "^3.13.0",
        "react": "^17.0.1",
        "react-dom": "^17.0.1"
    }
}
```

gatsby-config.js:
```js
module.exports = {
  siteMetadata: {
    title: "test-32720",
  },
  plugins: [
    `gatsby-plugin-image`,
    `gatsby-plugin-sharp`,
    `gatsby-transformer-sharp`,
  ],
};
```

src/pages/index.js:
```jsx
import * as React from "react"
import { StaticImage } from "gatsby-plugin-image"

// markup
const IndexPage = () => {
  return (
    <main>
      <title>Home Page</title>
      <StaticImage
        src="../images/icon.png"
        transformOptions={{cropFocus: `entropy`}}
      />
    </main>
  )
}

export default IndexPage
```

**Comment by KyleAMathews** [comment]
hmm can you reproduce it with using-gatsby-image like I did? Maybe it only
happens if there's other components
--
Kyle Mathews

Blog: *http://bricolage.io <http://bricolage.io>*
Twitter: http://twitter.com/kylemathews

**Comment by nategiraudeau** [comment]
I tried reproducing the issue in the `using-gatsby-image` example by adding `transformOptions={{ cropFocus: 'entropy' }}` on some of the `StaticImages`, but I didn't get any errors. When I set `cropFocus` to something that is not an actual option I get an error message that is almost exactly the same as the one you showed in the original comment.

**Comment by KyleAMathews** [comment]
Huh, maybe this was just a typo on my part 😆 

Well... there's not as much urgent here to fix. One thing you could still do if interested is try to provide a better error message.

**Comment by nategiraudeau** [comment]
Maybe there should be a check in `image-data.ts` to make sure that `cropFocus` is set to one of the actual options, and if it's not, it should reset it to the default value and then log either a warning or an error to the console rather than causing the entire app to crash.

**Comment by KyleAMathews** [comment]
yeah, that'd be a great place to put the validation!
--
Kyle Mathews

Blog: *http://bricolage.io <http://bricolage.io>*
Twitter: http://twitter.com/kylemathews

**Comment by nategiraudeau** [comment]
The pull request is #33123

**Comment by LekoArts** [comment]
This must have fixed itself in the meantime. I can no longer reproduce any errors when e.g. using `cropFocus: "entropy"`
