### ISSUE TITLE
[gatsby-source-wordpress] Live Preview breaks on Post Update with ERR_INVALID_ARG_TYPE.

### ISSUE THREAD

**Issue by janmei** [gatsbyjs/gatsby#32732]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When updating a post in wordpress on gatsby-source-wordpress at version 5.11.0 the Live Preview for the server breaks with the following error: 

```bash
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string.
Received undefined
    at validateString (internal/validators.js:124:11)
    at Url.parse (url.js:160:3)
    at Object.parse (url.js:155:13)
    at sourcePreviews (/Users/XXX/code/bug-repro/node_modules/gatsby-source-wordpress/src/steps/preview/index.ts:313:48)
    at step (/Users/XXX/code/bug-repro/node_modules/gatsby-source-wordpress/src/steps/source-nodes/index.ts:24:11)
    at runSteps (/Users/XXX/code/bug-repro/node_modules/gatsby-source-wordpress/src/utils/run-steps.ts:41:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runAPI (/Users/janmeininghaus/code/bug-repro/node_modules/gatsby/src/utils/api-runner-node.js:432:16) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

This error happens on 5.11.0 . On 5.9.2 it is working normal. 

As this only happens in Compination with wordpress a reproduction is hard from your. 
I used the current versions of WPGatsby (1.0.11) and WPGraphQL (1.6.2) to recreate the error on a fresh installation of WP and used ngrok to tunnel to my local process. 

It also happens on another wordpress instance on a different server.

Here is also an excerpt from the WP Report
WP Version 5.8 

### wp-plugins-active (4) ###

Classic Editor: version: 1.6.2, author: WordPress Contributors, 
WP Gatsby: version: 1.0.11, author: GatsbyJS, Jason Bahl, Tyler Barnes, 
WP GraphQL: version: 1.6.2, author: WPGraphQL, 

### Reproduction Link

https://github.com/janmei/bug-repro

### Steps to Reproduce

1. Clone linked Repo
2. install dependencies.
3. Install on a fresh WP Instance WPGatsby (1.0.11) and WPGraphQL (1.6.2) on their mentioned versions
4. start the dev server with `npm run live`
5. start a new ngrok tunnel
6. update the WPGatsby plugin with the ngrok preview instance url and the preview webhook and check the preview checkbox
5. update any post and watch the console output

### Expected Result

It is expected to update the preview instance with the new data and keep running. 

### Actual Result

Preview process breaks and outputs beforementioned error. 

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 92.0.4515.131
    Firefox: 90.0.2
    Safari: 14.1.2
  npmPackages:
    gatsby: ^3.11.0 => 3.11.0
    gatsby-plugin-sharp: ^3.11.0 => 3.11.0
    gatsby-source-wordpress: ^5.11.0 => 5.11.0
    gatsby-transformer-sharp: ^3.11.0 => 3.11.0
  npmGlobalPackages:
    gatsby-cli: 3.9.0
```

**Comment by joernroeder** [comment]
same here after publishing post in wp.

```
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Url.parse (url.js:160:3)
    at Object.parse (url.js:155:13)
    at sourcePreviews
(/node_modules/gatsby-source-wordpress/src/steps/preview/index.ts:313:48)
```

**Comment by TylerBarnes** [comment]
Just figured this one out. There was a missing property on one webhook on the WPGatsby side. Upgrade to WPGatsby 1.0.12 for a fix 👍

**Comment by janmei** [comment]
Thanks!
