### ISSUE TITLE
[Question] Populate redux store with graphql query results

### ISSUE THREAD

**Issue by canastro** [gatsbyjs/gatsby#3273]
### Description
I was looking into the gatsbygram example and ran into the usage of `getChildContext`, which is something I was trying to avoid:
https://github.com/gatsbyjs/gatsby/blob/1cd83ac23794d1f2537a9e5ca81fb8f665069590/examples/gatsbygram/src/layouts/index.js#L23

So my goal is to add redux to manage the global state, in this case I would like to have access to all posts through a reducer.

### Question
How can I have a reducer that would have the posts resultant from the following graphql query?
https://github.com/gatsbyjs/gatsby/blob/1cd83ac23794d1f2537a9e5ca81fb8f665069590/examples/gatsbygram/src/pages/index.js#L200

Is there any way to seemingly integrate this, or the only solution is to get the posts in the constructor and dispatch a action to update the store?

### Environment

**Gatsby version:** 1.9.118
**Node.js version:** 8.4.0
**Operating System:** macOS Sierra 10.12.6

**Comment by KyleAMathews** [comment]
Right now there's not a way to access the GraphQL data directly in the client other than in e.g. `componentDidMount`.

It might make sense to make an extension API directly for this.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
