### ISSUE TITLE
Better documentation for structure of public directory, and caching recommendations.

### ISSUE THREAD

**Issue by tmccombs** [gatsbyjs/gatsby#3275]
I can't find any documentation on the structure of the public directory, and what all the files in there are. In particular, I want to know if some files should be cached for longer than others. For example it looks like some files (like component--*.js)  contain a hash that I presume is generated from the source files, so could be cached indefinitely, whereas others such as index.html probably shouldn't be cached for as long, since they don't have a unique id in the filename. 

It would be nice to have some kind of documentation with recommendations on how to set Cache-Control headers for paths, and which paths should be invalidated when a new version is released.

**Comment by KyleAMathews** [comment]
Agreed! I've been meaning to do this — so let me do write something quickly as I have a bit of time.
