### ISSUE TITLE
Tailwind CSS Responsive classes overridden

### ISSUE THREAD

**Issue by matteofrana** [gatsbyjs/gatsby#32770]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I configured Tailwind in a very standard way, using the `gatsby-postcss` plugin.
The responsive classes get overridden: for example you see that, if I set `flex-col sm:flex-row`, I always get a the `flex-direction: column` behavior:
<img width="987" alt="Schermata 2021-08-11 alle 11 53 50" src="https://user-images.githubusercontent.com/46195306/129009175-d15db2fd-07f3-40c3-bc64-402ddc36f62c.png">

### Reproduction Link

https://github.com/ReactBricks/gatsby-starter-reactbricks-tailwind/tree/rb-v3

### Steps to Reproduce

Just start the project, you see that the Home and About us links are not well aligned in the header.

### Expected Result

The Tailwind responsive class should prevail for a screen larger than the "sm" breaking point.

### Actual Result

Inspecting the code you see that where there is a tailwind class `flex flex-col sm:flex-row`, the `flex-col` css overrides the media query code for `sm:flex-row`:
<img width="987" alt="Schermata 2021-08-11 alle 11 53 50" src="https://user-images.githubusercontent.com/46195306/129009175-d15db2fd-07f3-40c3-bc64-402ddc36f62c.png">

### Environment

```shell
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 92.0.4515.131
    Firefox: 57.0.4
    Safari: 14.1.2
  npmPackages:
    gatsby: ^3.11.1 => 3.11.1
    gatsby-plugin-manifest: ^3.11.0 => 3.11.0
    gatsby-plugin-offline: ^4.11.0 => 4.11.0
    gatsby-plugin-postcss: ^4.11.0 => 4.11.0
    gatsby-plugin-react-helmet: ^4.11.0 => 4.11.0
```

### Config Flags

None.

Tailwind is configured in a very standard way, using the `gatsby-postcss` plugin.

**Comment by LekoArts** [comment]
Hi!

I can't reproduce this locally with `gatsby develop` and `gatsby build`.

I started a project with `yarn create gatsby -y tailwind-test`, then followed these steps: https://tailwindcss.com/docs/guides/gatsby

My `src/pages/index.js` then was changed to:

```jsx
import * as React from "react"

const IndexPage = () => {
  return (
    <main className="flex text-6xl flex-col sm:flex-row">
      <h1>Title</h1>
      <p>Test123</p>
    </main>
  )
}

export default IndexPage
```

The media query is working fine.

**Comment by matteofrana** [comment]
Thank you! 
Can you reproduce the problem cloning my repo, to understand if there's something wrong with the code or my environment?
I followed the same steps to use Tailwind (you just see the css file is `style.css` instead of `global.css`).

Thank you,
Matteo

**Comment by matteofrana** [comment]
@LekoArts You see that in my case some css comes from the injected `<style>` tag, while the overridden responsive class is in a `commons.css` file (created by Gatsby). 
Thank you very much for your help!

**Comment by LekoArts** [comment]
Unfortunately I can't get the project you linked running locally. I figured I don't have the correct credentials and it fails at the reading config stage with:

```shell
  Error: Cannot find module 'classNames'
  Require stack:
  - /home/lennart/development/playground/gatsby-starter-reactbricks-tailwind/node_modules/react-bricks/react-bricks.cjs.production.min.js
  - /home/lennart/development/playground/gatsby-starter-reactbricks-tailwind/node_modules/react-bricks/index.js
  - /home/lennart/development/playground/gatsby-starter-reactbricks-tailwind/gatsby-node.js
  - /home/lennart/development/playground/gatsby-starter-reactbricks-tailwind/node_modules/gatsby/dist/bootstrap/resolve-module-exports.js
  - /home/lennart/development/playground/gatsby-starter-reactbricks-tailwind/node_modules/gatsby/dist/bootstrap/load-plugins/validate.js
  - /home/lennart/development/playground/gatsby-starter-reactbricks-tailwind/node_modules/gatsby/dist/bootstrap/load-plugins/load.js
  - /home/lennart/development/playground/gatsby-starter-reactbricks-tailwind/node_modules/gatsby/dist/bootstrap/load-plugins/index.js
  - /home/lennart/development/playground/gatsby-starter-reactbricks-tailwind/node_modules/gatsby/dist/bootstrap/load-config-and-plugins.js
  - /home/lennart/development/playground/gatsby-starter-reactbricks-tailwind/node_modules/gatsby/dist/services/initialize.js
  - /home/lennart/development/playground/gatsby-starter-reactbricks-tailwind/node_modules/gatsby/dist/services/index.js
  - /home/lennart/development/playground/gatsby-starter-reactbricks-tailwind/node_modules/gatsby/dist/state-machines/develop/services.js
  - /home/lennart/development/playground/gatsby-starter-reactbricks-tailwind/node_modules/gatsby/dist/state-machines/develop/index.js
  - /home/lennart/development/playground/gatsby-starter-reactbricks-tailwind/node_modules/gatsby/dist/commands/develop-process.js
  - /home/lennart/development/playground/gatsby-starter-reactbricks-tailwind/.cache/tmp-12699-I5lkOHme1RIv

  - loader.js:880 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:880:15

  - loader.js:725 Function.Module._load
    internal/modules/cjs/loader.js:725:27

  - loader.js:952 Module.require
    internal/modules/cjs/loader.js:952:19

  - v8-compile-cache.js:159 require
    [gatsby-starter-reactbricks-tailwind]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - react-bricks.cjs.production.min.js:1 Object.<anonymous>
    [gatsby-starter-reactbricks-tailwind]/[react-bricks]/react-bricks.cjs.production.min.js:1:667

  - v8-compile-cache.js:192 Module._compile
    [gatsby-starter-reactbricks-tailwind]/[v8-compile-cache]/v8-compile-cache.js:192:30

  - loader.js:1092 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1092:10

  - loader.js:928 Module.load
    internal/modules/cjs/loader.js:928:32

  - loader.js:769 Function.Module._load
    internal/modules/cjs/loader.js:769:14

  - loader.js:952 Module.require
    internal/modules/cjs/loader.js:952:19

  - v8-compile-cache.js:159 require
    [gatsby-starter-reactbricks-tailwind]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - index.js:1 Object.<anonymous>
    [gatsby-starter-reactbricks-tailwind]/[react-bricks]/index.js:1:80

  - v8-compile-cache.js:192 Module._compile
    [gatsby-starter-reactbricks-tailwind]/[v8-compile-cache]/v8-compile-cache.js:192:30

  - loader.js:1092 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1092:10

  - loader.js:928 Module.load
    internal/modules/cjs/loader.js:928:32

  - loader.js:769 Function.Module._load
    internal/modules/cjs/loader.js:769:14

```

**Comment by matteofrana** [comment]
Hi @LekoArts,
I'll fix it as soon as possible, so that you can reproduce my error.

Thank you,
Matteo

**Comment by matteofrana** [comment]
Hi @LekoArts,
I found the problem, that was on my side (I was loading Tailwind two times for a bug).

Thank you very much for your support, I close the issue.
Matteo

**Comment by Adiiieee** [comment]
Hey, I got the similar problem,can you please tell me how you solved it? thank you.

**Comment by Adiiieee** [comment]
<img width="674" alt="Screenshot 2024-07-01 at 18 46 01" src="https://github.com/gatsbyjs/gatsby/assets/91801576/659120cc-5401-478f-a685-da5256408df3">
in my case also this media query class is coming from global CSS and is overwritten by index.css classes

**Comment by Adiiieee** [comment]
Nevermind i found the issue. I'm using this stupid library uploadthing and applied its CSS file to root so this classes from index.css are coming from it(smh).
