### ISSUE TITLE
Video not available for link in guidelines/logo page

### ISSUE THREAD

**Issue by AnilSeervi** [gatsbyjs/gatsby#32785]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

The link to [YouTube video](https://youtube.com/watch?v=BY9Jv1gWFwY) in [Footnotes section](https://www.gatsbyjs.com/guidelines/logo/) of *Kyle Mathews and Sacha Greif live streaming the initial design of the official Gatsby website, featuring the freshly designed Gatsby logo* is **Private**.

### Steps to Resolve this Issue

Make it public or remove it.

**Comment by LekoArts** [comment]
Thanks, I've noted this internally to get it fixed!
