### ISSUE TITLE
html.generateWebpImages reported as unkown plugin option for "gatsby-source-wordpress"

### ISSUE THREAD

**Issue by cjogles** [gatsbyjs/gatsby#32798]
### Preliminary Checks

- [x] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Within gatsby-config.js, I have configured the gatsby-source-wordpress plugin options object with the html key. Within the html object I have inserted the following name value pair: `generateWebpImages: true,` this is specified as a [usable plugin option here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/plugin-options.md#htmlgeneratewebpimages). 

Upon building the gatsby app in gatsby cloud I see the following error: 

Warning: there are unknown plugin options for "gatsby-source-wordpress": html.generateWebpImages
Please open an issue at ghub.io/gatsby-source-wordpress if you believe this option is valid.

Granted, this error appears in my gatsby cloud dashboard as that is where I am hosting the project. Perhaps I need to open an issue in a more specific place related to gatsby cloud? Or does the hosting platform pull this incorrect error from the gatsby-source-plugin? 

I didn't make a reproduction link, because I wasn't sure if its safe to share my wordpress backend connection details. This is also my first time opening an issue. Feedback welcome. 

### Reproduction Link

Not sure if its safe to share wordpress back end that would make this minimal reproduction possible

### Steps to Reproduce

1. clone gatsby starter and add and install gatsby-plugin-sharp (its necessary for the next plugin)
2. add and install gatsby-source-wordpress with the following minimal config
```
{
  resolve: "gatsby-source-wordpress",
    options: {
      url: "https://***wordpress-backend-url-here***/graphql",
        html: {
          generateWebpImages: true,
        },
      },
},
```
3. build the app and look at warning that shouldn't be there. 

### Expected Result

No warning about html.generateWebpImages should appear. 

### Actual Result

warning about html.generateWebpImages does appear in build logs in gatsby cloud. 

### Environment

```shell
System:
    OS: macOS 11.5.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 7.16.0 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 92.0.4515.131
    Edge: 92.0.902.73
    Firefox: 89.0.2
    Safari: 14.1.2
  npmPackages:
    gatsby: ^3.11.1 => 3.11.1
    gatsby-awesome-pagination: ^0.3.8 => 0.3.8
    gatsby-plugin-algolia: ^0.22.0 => 0.22.0
    gatsby-plugin-apollo: ^3.0.2 => 3.0.2
    gatsby-plugin-canonical-urls: ^3.11.0 => 3.11.0
    gatsby-plugin-gatsby-cloud: ^2.11.0 => 2.11.0
    gatsby-plugin-google-analytics: ^3.11.0 => 3.11.0
    gatsby-plugin-hotjar: ^1.1.1 => 1.1.1
    gatsby-plugin-image: ^1.11.0 => 1.11.0
    gatsby-plugin-loadable-components-ssr: ^3.2.0 => 3.2.0
    gatsby-plugin-manifest: ^3.11.0 => 3.11.0
    gatsby-plugin-next-seo: ^1.7.0 => 1.7.0
    gatsby-plugin-offline: ^4.11.0 => 4.11.0
    gatsby-plugin-perf-budgets: ^0.0.18 => 0.0.18
    gatsby-plugin-react-helmet: ^4.11.0 => 4.11.0
    gatsby-plugin-robots-txt: ^1.6.8 => 1.6.8
    gatsby-plugin-root-import: ^2.0.6 => 2.0.6
    gatsby-plugin-sharp: ^3.11.0 => 3.11.0
    gatsby-plugin-sitemap: ^4.7.0 => 4.7.0
    gatsby-plugin-styled-components: ^4.11.0 => 4.11.0
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.24 => 1.1.24
    gatsby-plugin-wpgraphql-seo: ^1.2.2 => 1.2.2
    gatsby-source-filesystem: ^3.11.0 => 3.11.0
    gatsby-source-shopify: ^4.7.1 => 4.7.1
    gatsby-source-wordpress: 5.11.0 => 5.11.0
    gatsby-transformer-sharp: ^3.11.0 => 3.11.0
```

### Config Flags

FAST_DEV: true,
PARALLEL_SOURCING: true,
PRESERVE_WEBPACK_CACHE: false,
PRESERVE_FILE_DOWNLOAD_CACHE: true,

**Comment by DanielRiveraHQ** [comment]
Same issue over here
