### ISSUE TITLE
Data not passed as data from graphql query in layouts/index.js

### ISSUE THREAD

**Issue by ataylorme** [gatsbyjs/gatsby#3279]
## Description

When running a graphql query in `layouts/index.js` the information is not available in `data` as expected.

### Environment

Gatsby version: `1.9.142`
Node.js version: `8.8.1`
Operating System: macOS High Sierra

### Actual result

`data` is undefined

### Expected behavior

`data` is expected to be defined. 

### Steps to reproduce
My `layouts/index.js` looks like this:
```js
import React, {Component, PropTypes} from 'react'
import Link from 'gatsby-link'
import { Container } from 'react-responsive-grid'

import { rhythm, scale } from '../utils/typography'
import Header from '../components/Header'
import HeroImage from '../components/HeroImage'

require('prismjs/themes/prism-solarizedlight.css')
require('../global.scss')

export default class Template extends Component {
	render() {
		const { location, children, data } = this.props
		console.log(data);
		const siteTitle = data.site.siteMetadata.title
		const { heroImage } = data;
		let header, aboutImage, bodyClass
		
			let rootPath = `/`
			if (typeof __PREFIX_PATHS__ !== `undefined` && __PREFIX_PATHS__) {
			  rootPath = __PATH_PREFIX__ + `/`
			}
		
			if (location.pathname === rootPath) {
				return (
					<div id='main' className='home'>
						<Header />
						<HeroImage image={heroImage} title={siteTitle} />
						<Container
						  style={{
						  maxWidth: rhythm(30),
						  padding: `${rhythm(1.5)} ${rhythm(3 / 4)}`,
						  }}
						  className="home"
					  >
						  {children()}
						</Container>
					</div>
				  )
			} else {
				return (
					<div>
						  {children()}
					</div>
				  )
			}
	}
}

export const HomePageQuery = graphql`
query HomePageQuery {
  site {
	siteMetadata {
	  title
	  author
	}
  }
  heroImage: file(relativePath: { eq: "images/heroes/salt-creek-falls.jpg" }) {
	  childImageSharp {
		sizes(maxHeight: 350) {
		  ...GatsbyImageSharpSizes_withWebp_tracedSVG
		}
	  }
  }
}
`
```

This query works in GraphiQL and I've tried a simplified version with just `siteMetadata`.

Any idea why `data` isn't populated would be helpful. [This PR](https://github.com/gatsbyjs/gatsby/pull/1503), [the example file](https://github.com/gatsbyjs/gatsby/blob/master/examples/using-remark/src/layouts/index.js) and [the docs](https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#choosing-the-page-layout) all indicate it should be fine.

My main goal is to create a different layout for the home (root) page. If there's an easier way to do that, such as injecting the needed front matter into that page's creation, that would be helpful but I'm still not sure why the graphQL query inside of layout isn't passing `data`.

**Comment by KyleAMathews** [comment]
Have you tried restarting `gatsby develop`? We've spent more time making sure page components are "hot reloadable" vs. layouts.

**Comment by ataylorme** [comment]
Yeah, still happens on a fresh start of `gatsby develop` and even during `gatsby build`. I've tried deleting and re-downloading `node_modules` too.

**Comment by ataylorme** [comment]
> My main goal is to create a different layout for the home (root) page. If there's an easier way to do that, such as injecting the needed front matter into that page's creation, that would be helpful

Think I got this sorted with `exports.onCreatePage` in [this example](https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#choosing-the-page-layout). Yay for the good docs!

Even with the new layout for the homepage, instead of the default layout, `data` isn't available.

**Comment by KyleAMathews** [comment]
@ataylorme huh, this could be a bug — multi-layouts don't seem to be used much so not entirely sure how reliable they are — could you build a very simple reproduction of the problem you're seeing so I could debug it?

**Comment by ataylorme** [comment]
@KyleAMathews I was unable to recreate in a fresh install of [the Hello World repo](https://github.com/gatsbyjs/gatsby-starter-hello-world) modifying the homepage layout file with `exports.onCreatePage`. I'm going to close this and keep debugging my site
