### ISSUE TITLE
setParserPlugins doesn't take plugin options

### ISSUE THREAD

**Issue by AlahmadiQ8** [gatsbyjs/gatsby#3280]
## Description

I'm trying to use [remark-custom-blocks](https://github.com/zestedesavoir/zmarkdown/tree/master/packages/remark-custom-blocks). However I am unable to find a way to pass in required plugin options. I looked at #706 but still no luck. 

See how the plugin is used below

```javascript
  remark.use(remarkCustomBlocks, {
    someType: 'a-css-class another-class',
    anotherType: 'foo',
  })
```

I have tried the following, but no luck unfortunately

```javascript
module.exports.setParserPlugins = () => [
  function customRemark() {
    return remarkCustomBlocks({
      danger: 'danger',
      info: 'info',
    });
  },
];
```

Is there a way to pass parser option arguments?

Perhaps we could change https://github.com/gatsbyjs/gatsby/blob/dcfa0fab32e168c075c052dde7ecd97736c6147a/packages/gatsby-transformer-remark/src/extend-node-type.js#L63 to also take parser plugin options? 

### Environment

Gatsby version: 1.1.20
Node.js version: v8.5.0

**Comment by KyleAMathews** [comment]
Hey sure! That totally makes sense and seems like it was an oversight not adding that originally.

Would you like to create a PR for this?

A plugin for remark-custom-blocks would be 💯 too :-)

**Comment by AlahmadiQ8** [comment]
Absolutely :). I'll work on a PR tonight.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
