### ISSUE TITLE
[gatsby-source-shopify] allShopifyProductVariant(filter: {storefrontId: {regex: $shopifyRefs}}) returns maximum of 5 items

### ISSUE THREAD

**Issue by codeithuman** [gatsbyjs/gatsby#32816]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

We're working on converting a Gatsby + Shopify site into a Gatsby + Shopify + Contentful site so that we have additional CMS capabilities that are not available in Shopify's CMS. 

When generating our product pages, we want to avoid querying all product data from Shopify so that we can make the best use of incremental builds, therefore, in our our `/templates/product.js` file, we have a query that looks like the following:

```
query MyQuery($shopifyRefs: String) {
  allShopifyProductVariant(filter: {storefrontId: {regex: $shopifyRefs}}) {
    edges {
      node {
        id
        storefrontId
        title
        shopifyId
        price
        availableForSale
        internal {
          type
        }
      }
    }
  }
}
```

With the query variable being a large regex containing all the variant `storefrontId`'s.
```
{
  "shopifyRefs": "/Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zNzQ3NDY2NDgwODY0Mw==|Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zNzQ3NDY2NDg0MTQxMQ==|Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zNzQ3NDY2NDg3NDE3OQ==|Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80MDI3Njk3MjYwMTUzOQ==|Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80MDI3Njk3MjYzNDMwNw==|Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80MDI3Njk3NzAyNTIxOQ==|Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80MDI3Njk3NzA1Nzk4Nw==|Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80MDI3Njk3NzA5MDc1NQ==/gi"
}
```

What we're finding is that the `allShopifyProductVariant(filter: {storefrontId: {regex: $shopifyRefs}})` query returns a maximum of 5 items. If we remove the first `storefrontId` from the regex, as expected, we lose our first item and gain a new item in the data that is returned. 

The data that is most important to us here are the `price` and `availableForSale`. 

Our main goal is to make the best use of incremental builds and we are curious when and where you would recommend requesting this data? 

Thanks so much for all the help!

### Reproduction Link

https://github.com/codeithuman/shopify-test

### Steps to Reproduce

See description

### Expected Result

See description

### Actual Result

See description

### Environment

```shell
System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    gatsby: ^3.9.1 => 3.9.1 
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5 
    gatsby-plugin-catch-links: ^3.9.0 => 3.9.0 
    gatsby-plugin-gatsby-cloud: ^2.9.1 => 2.9.1 
    gatsby-plugin-google-analytics: ^3.9.0 => 3.9.0 
    gatsby-plugin-google-gtag: ^3.9.0 => 3.9.0 
    gatsby-plugin-hotjar: ^1.1.1 => 1.1.1 
    gatsby-plugin-image: ^1.9.0 => 1.9.0 
    gatsby-plugin-jss: ^3.9.0 => 3.9.0 
    gatsby-plugin-mailchimp: ^5.2.2 => 5.2.2 
    gatsby-plugin-manifest: ^3.9.0 => 3.9.0 
    gatsby-plugin-offline: ^4.9.0 => 4.9.0 
    gatsby-plugin-preload-fonts: ^2.9.0 => 2.9.0 
    gatsby-plugin-react-helmet: ^4.9.0 => 4.9.0 
    gatsby-plugin-sharp: ^3.9.0 => 3.9.0 
    gatsby-plugin-typography: ^3.9.0 => 3.9.0 
    gatsby-plugin-use-query-params: ^1.0.1 => 1.0.1 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-source-contentful: ^5.10.0 => 5.10.0 
    gatsby-source-filesystem: ^3.9.0 => 3.9.0 
    gatsby-source-shopify: ^5.1.0 => 5.1.0 
    gatsby-transformer-sharp: ^3.9.0 => 3.9.0 
  npmGlobalPackages:
    gatsby-cli: 3.11.0
```

### Config Flags

No

**Comment by codeithuman** [comment]
I think in the short term, I think we'll have to update our query to `allShopifyProductVariant {}` and just know that anytime we update Shopify, we'll have to rebuild every product page.

All of our content lives in Contentful, except for pricing and inventory, so that'll be okay for now.

**Comment by DanielSLew** [comment]
I may be misunderstanding your issue but incremental builds functions so that only the product pages that have data changes will be updated when you update your shopify store.

I also can't clone your site and test it out, I think the repo you posted is private.
