### ISSUE TITLE
Issue regarding the useStaticQuery

### ISSUE THREAD

**Issue by Jassi10000** [gatsbyjs/gatsby#32825]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Getting this error while running the make script which involves gatsby dependencies and runs gatsby build in background
Error in function useStaticQuery in ./.cache/gatsby-browser-entry.js:77

### Reproduction Link

https://github.com/layer5io/layer5

### Steps to Reproduce

1. gatsby build and gatsby serve
2.
3.
...

### Expected Result

It should run successfully in the browser

### Actual Result

Already describeld in the issue descriptiondescribed

### Environment

```shell
System:
    OS: Linux 4.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - /mnt/c/Program Files/nodejs/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  npmPackages:
    gatsby: ^3.2.1 => 3.3.0
    gatsby-awesome-pagination: ^0.3.8 => 0.3.8
    gatsby-cli: ^3.3.0 => 3.3.0
    gatsby-plugin-anchor-links: ^1.1.0 => 1.2.1
    gatsby-plugin-feed-mdx: ^1.1.0 => 1.1.0
    gatsby-plugin-google-gtag: ^3.2.0 => 3.3.0
    gatsby-plugin-image: ^1.3.0 => 1.3.0
    gatsby-plugin-manifest: ^3.2.0 => 3.3.0
    gatsby-plugin-mdx: ^2.2.0 => 2.3.0
    gatsby-plugin-meta-redirect: ^1.1.1 => 1.1.1
    gatsby-plugin-preload-fonts: ^2.2.0 => 2.3.0
    gatsby-plugin-react-helmet: ^4.2.0 => 4.3.0
    gatsby-plugin-sharp: ^3.2.0 => 3.3.0
    gatsby-plugin-sitemap: ^3.2.0 => 3.3.0
    gatsby-plugin-styled-components: ^4.2.0 => 4.3.0
    gatsby-redirect-from: ^0.3.0 => 0.3.0
    gatsby-source-filesystem: ^3.2.0 => 3.3.0
    gatsby-transformer-sharp: ^3.2.0 => 3.3.0
```

### Config Flags

no

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by Jassi10000** [comment]
@LekoArts Thanks you acknowledging my issue , but I just got freed resolving this 
It was just a matter of cache 
I just used <code> gatsby clean </code> to clear all the cache and now all things are working fine and smooth .

**Comment by LekoArts** [comment]
Ok, good to hear! If you have a reproduction of your issue, please post it here: https://github.com/gatsbyjs/gatsby/issues/26563

**Comment by Jassi10000** [comment]
yeah sure

**Comment by jsg2021** [comment]
https://github.com/jsg2021/gatsby-staticquery-error-repro this is my min reproduction... lazy load components seem to be one trigger.
