### ISSUE TITLE
[gatsby-source-contentful] Call createTypes from createSchemaCustomisation instead of sourceNodes

### ISSUE THREAD

**Issue by me4502** [gatsbyjs/gatsby#32848]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

In order to support LDBM store and dependent flags such as parallel query running, schema types cannot be created via sourceNodes.

The `createTypes` calls should be moved to `createSchemaCustomisation` rather than `sourceNodes` to resolve this. Source: https://github.com/gatsbyjs/gatsby/discussions/32389#discussioncomment-1032400

For most instances, this should be as simple as moving them, however, one of the createTypes calls depends on the `contentTypeItems` field. (https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/src/gatsby-node.js#L413)

### Reproduction Link

N/A - This was an issue noticed by looking at the code

### Steps to Reproduce

1. Run gatsby-source-contentful with LDBM-Store or Parallel Query Running enabled
2. It will fail due to the aforementioned constraint

### Expected Result

As this is a relatively simple fix, ideally it wouldn't fail the constraint and therefore allow the site to be built with these flags enabled.

### Actual Result

This will fail currently as it does not meet the constraints to run Parallel Source Running or LDBM

### Environment

```shell
N/A as was found via code
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

This was an oversight on my end, I forgot the add the instructions for plugins to the discussion. I now added it to https://github.com/gatsbyjs/gatsby/discussions/32389.

So TL;DR is: We know that it needs fixing so we're using `gatsby-source-contentful@alpha-pqr-compat` for now and will be fixing it in stable for the new major version. See here: https://github.com/gatsbyjs/gatsby/pull/32351
