### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by kajal4329** [gatsbyjs/gatsby#32857]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

As a user, this statement : 
"Functions on Gatsby Cloud scales perfectly alongside **_your_** the size of your website’s workload, reducing the cost associated with running traditional servers. No need to mess around with load balancers, scaling and routing issues, or paying for capacity and **_compute your just not using_**",  
confused me and I could figure out it was because of few grammatically errors in sentence and missing keyword in last line.

![Screenshot (121)](https://user-images.githubusercontent.com/77650495/130179851-e3d4e524-9dce-4410-8097-f89aecfec7fb.png)

### Steps to Resolve this Issue

1. One can get access to statement and make required changes after getting permission from owner.
2. Even though changes are minimal they help in better understanding to great extent.
2.
3.
...

**Comment by LekoArts** [comment]
Thanks for the issue! I noted it internally and corrected the sentence.
