### ISSUE TITLE
Support JSX fragment syntax

### ISSUE THREAD

**Issue by nickmccurdy** [gatsbyjs/gatsby#3285]
As of React 16.2 JSX fragments can use a `<></>` syntax instead of `<Fragment></Fragment>`. The latter syntax is supported in Gatsby, but the former is unsupported yet because it involves updating `babel-preset-react`.

**Comment by KyleAMathews** [comment]
Yeah, this will come along with our upgrade to Babel 7 in v2.

**Comment by gaven** [comment]
Is this still relevant? I'm having issues implementing the `React.Fragment` shorthand in v2.

**Comment by NaderIkladious** [comment]
Any updates on this ?
I cannot use `React.Fragment`
It gives me this error
```
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

Check your code at file.js:6.
```

**Comment by sbliznyuk** [comment]
Hey!

Shortcut for fragment still not working:

`postslist.js: Unexpected token (11:13)

   9 |           return (
  10 |             {/* <div className="blog-post-preview" key={post.id}> */}
> 11 |             <>
     |              ^`
