### ISSUE TITLE
Problem installing Plugins / Windows10

### ISSUE THREAD

**Issue by KingLouisXVII** [gatsbyjs/gatsby#3287]
I was able to install a theme and the filesystem but failed at sharp and remark. Any clue what the problem is here?

> PS C:\Users\Daniel Jakobian\Documents\HTML PROJECTS\gatsbyTest\gatsby-site> npm install --save gatsby-plugin-sharp
 sharp@0.17.3 install C:\Users\Daniel Jakobian\Documents\HTML PROJECTS\gatsbyTest\gatsby-site\node_modules\sharp
 node-gyp rebuild
C:\Users\Daniel Jakobian\Documents\HTML PROJECTS\gatsbyTest\gatsby-site\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-b
in\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python27\python.exe -c import platform; print(platform.python_version());
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:272:12)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Daniel Jakobian\Documents\HTML PROJECTS\gatsbyTest\gatsby-site\node_modules\sharp
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN gatsby-starter-hello-world@ No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.17.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.17.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Daniel Jakobian\AppData\Roaming\npm-cache\_logs\2017-12-20T13_45_48_365Z-debug.log

**Comment by mpolinowski** [comment]
Hi,

the sharp plugin is a bit painful - but the instruction here:

https://www.gatsbyjs.org/docs/gatsby-on-windows/

make it work on Windows (go to "If npm install still fails…")

**Comment by sebastienfi** [comment]
Could you try with Python 2.7 not 3 ?

**Comment by KingLouisXVII** [comment]
thanks so much for the quick responses! I was able to install the plugins after installing the windows build tools. But now I am stuck a the gatsby develop part. Any ideas?

> PS C:\Users\Daniel Jakobian\Documents\HTML PROJECTS\gatsbyTest\gatsby-site> gatsby develop
success delete html files from previous builds — 0.009 s
success open and validate gatsby-config.js — 0.004 s
success copy gatsby files — 0.034 s
success onPreBootstrap — 0.021 s
success source and transform nodes — 0.424 s
success building schema — 0.391 s
success createLayouts — 0.035 s
success createPages — 0.042 s
success createPagesStatefully — 0.035 s
success onPreExtractQueries — 0.001 s
success update schema — 0.124 s
success extract queries from components — 0.116 s
success run graphql queries — 0.328 s
error The system cannot find the path specified.
  Error: spawn C:\Users\Daniel Jakobian\Documents\HTML PROJECTS\gatsbyTest\gatsby-site\node_modules\pngquant-bin\vendor\pngquant.exe ENOENT
  - enoent.js:11 notFoundError
    [gatsby-site]/[cross-spawn]/lib/enoent.js:11:11
  - enoent.js:46 verifyENOENT
    [gatsby-site]/[cross-spawn]/lib/enoent.js:46:16
  - enoent.js:33 ChildProcess.cp.emit
    [gatsby-site]/[cross-spawn]/lib/enoent.js:33:19
  - child_process.js:209 Process.ChildProcess._handle.onexit
    internal/child_process.js:209:12
error UNHANDLED REJECTION
  Error: spawn C:\Users\Daniel Jakobian\Documents\HTML PROJECTS\gatsbyTest\gatsby-site\node_modules\pngquant-bin\vendor\pngquant.exe ENOENT
  - enoent.js:11 notFoundError
    [gatsby-site]/[cross-spawn]/lib/enoent.js:11:11
  - enoent.js:46 verifyENOENT
    [gatsby-site]/[cross-spawn]/lib/enoent.js:46:16
  - enoent.js:33 ChildProcess.cp.emit
    [gatsby-site]/[cross-spawn]/lib/enoent.js:33:19
  - child_process.js:209 Process.ChildProcess._handle.onexit
    internal/child_process.js:209:12

**Comment by mpolinowski** [comment]
ah i remember, i had the same problem. this pngquant. exe was not installed. I think i npm installed pngquant-bin manually. make sure the exe shows up in the node_modules directory

**Comment by KingLouisXVII** [comment]
thanks so much! It is working now (the real work can finally begin).
