### ISSUE TITLE
there are unknown plugin options for "gatsby-source-shopify": shopName, accessToken

### ISSUE THREAD

**Issue by StanLepunK** [gatsbyjs/gatsby#32880]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hello, I try to use Gatsby with Shopify, but when I pass my `shopName` and my `accesToken` I have an error message 
```
Invalid plugin options for "gatsby-source-shopify":

- "password" is required
- "storeUrl" is required
```
It's my first time with an API Shopify and with implement it in `Gatsby` 

My config is something like that 
```
module.exports = {
  siteMetadata: {
    siteUrl: `https://www.yourdomain.tld`,
  },
  plugins: [
    {
      resolve: `gatsby-source-shopify`,
      options: {
        // storeUrl: `cafe-366.myshopify.com`,
        // password: `xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`,
        shopName: `cafe-366.myshopify.com`,
        accessToken: `xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`,
      },
    },
  ],
};
```

I try to replace the `shopName` and the `accesToken` by the `StoreUrl `and the `accesToken` by the `password`, but that's don't work too.

For information in the Shopify Partners I create an `Custom App` and I give the authorization to activate the `API Storefront`   for the URL application I write `https://cafe-366.myshopify.com/` and for the authorized redirection I write `http://localhost:8000/` because for now I work locally. 

I cannot figure me why I cannot pass the `ShopName` and the `accesToken` like in your example.

### Reproduction Link

none

### Steps to Reproduce

none

### Expected Result

none

### Actual Result

` ERROR #11331  PLUGIN`

### Environment

```shell
OSX mojave
```

### Config Flags

none

**Comment by kamerondotcom** [comment]
I'm having this issue too. Strange to see a password required as an option :/
