### ISSUE TITLE
having `"` in page path results in a build crash: `Query was not run and no cached result was found.`

### ISSUE THREAD

**Issue by laurenskling** [gatsbyjs/gatsby#32892]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When having a `"` char in my page path, my build has started to crash:

```
  Error: Error loading a result for the page query in "/5027276-Audi-RS-3-Sportback-2.5-TFSI-S-tr.-19"RotorSportabgasanla". Query was not run and 
  no cached result was found.
```

I've set up a repo that crashes on it:
https://github.com/laurenskling/no-cached-result

One could say "well don't put that char in the path!" But that's not the point ;)

Did some further testing, works in Gatsby `3.11.1`, starts crashing in `3.12.0`. Still doesn't work in `@next (gatsby@3.13.0-next.2)`

### Reproduction Link

https://github.com/laurenskling/no-cached-result

### Steps to Reproduce

1. clone repo
2. yarn install
3. yarn build
4. see crash

### Expected Result

Successful build

### Actual Result

`Error: Error loading a result for the page query in "/ZmlsbXM6Ng=="". Query was not run and no cached result was found.`

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-1060NG7 CPU @ 1.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.17.4 - /var/folders/gh/yg99pwqj2rngz5wysjcgl8ph0000gn/T/yarn--1629788457366-0.508846866931753/node
    Yarn: 1.22.4 - /var/folders/gh/yg99pwqj2rngz5wysjcgl8ph0000gn/T/yarn--1629788457366-0.508846866931753/yarn
    npm: 6.14.14 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 92.0.4515.159
    Safari: 14.0.2
  npmPackages:
    gatsby: ^3.13.0-next.2 => 3.13.0-next.2
    gatsby-source-graphql: ^3.12.0 => 3.12.0
```

**Comment by vladar** [comment]
This bug was likely introduced in https://github.com/gatsbyjs/gatsby/pull/32763 but should be fixed via https://github.com/gatsbyjs/gatsby/pull/33067#discussion_r703401272
