### ISSUE TITLE
(quick) Question: new pages on live sites

### ISSUE THREAD

**Issue by brandonmp** [gatsbyjs/gatsby#329]
Since the site is rendering content files to html during the webpack build, does this mean that for something like a blog, every new post would require a fresh push to server?

If that's the case, does anyone have best-practices for that workflow? 

New to static site concepts (but not react/webpack), so apologies if this is an absurd question!

**Comment by KyleAMathews** [comment]
@brandonmp thanks for the question! I have an answer but this is the perfect sort of question to put on Stackoverflow. Could you go there and create the question (and tag it with `gatsby`) and then come back and paste the link here? I'll then answer over there. Thanks!

**Comment by brandonmp** [comment]
Absolutely, thanks kyle. Great work keeping the issues channel clean :) 

http://stackoverflow.com/questions/37818542/gatsby-static-site-gen-publishing-new-content

**Comment by KyleAMathews** [comment]
Answered!
