### ISSUE TITLE
Gatsby X Contentful X Netlify

### ISSUE THREAD

**Issue by Maxhodges** [gatsbyjs/gatsby#330]
Hi I'm new here. Is there a forums for peer-to-peer help?

> Transform plain text into dynamic blogs and websites using the latest web technologies.

why "plain text"? Can it also render video and images?

Can it be used with content from Contentful? is anyone doing something like that?

Cheers!

**Comment by KyleAMathews** [comment]
It can't natively treat video/images as "content types" *yet* but is in the plans. Right now you can still easily include images/text in pages either by linking to it normally e.g. `<img src="./my-picture.jpg" />` or using image loaders. See for example what @timurc did https://github.com/gatsbyjs/gatsby/pull/303

**Comment by KyleAMathews** [comment]
Oh and on peer-to-peer help. Most activity has happened either here or on Discord but now that you've added the tag on Stackoverflow, I'm going to start pushing more people there. I've subscribed to the Gatsby tag there so should be easy enough to follow along.

**Comment by Maxhodges** [comment]
You prefer gatsby or gatsbyjs? 

Cheers,
Max




On Wed, Jun 15, 2016 at 1:51 AM +0900, "Kyle Mathews" <notifications@github.com> wrote:












Oh and on peer-to-peer help. Most activity has happened either here or on Discord but now that you've added the tag on Stackoverflow, I'm going to start pushing more people there. I've subscribed to the Gatsby tag there so should be easy enough to follow along.

**Comment by KyleAMathews** [comment]
`gatsby` seems fine. I looked at a number of other JS projects to see what they use and it seems many don't have a trailing `js`. Gatsby is an uncommon enough word that we should be fine.

**Comment by Maxhodges** [comment]
do you have any tips on how to get started with something like Contentful? So the articles would be structured JSON. Is there some way to feel that into the react components, or do I basically need to convert it to gatsby md first?

**Comment by KyleAMathews** [comment]
Gatsby can handle JSON natively, see http://gatsbyjs.github.io/gatsby-starter-default/json/ So you could pull json straight from Contentful and use that to build pages.

Also there's some people discussing Contentful integration already @ https://github.com/gatsbyjs/gatsby/issues/324 How about we close this issue and move the discussion there?

**Comment by Maxhodges** [comment]
Awesome news!
Sure thing! weird, I searched the repo before I posted, but somehow missed that

**Comment by Maxhodges** [comment]
tag approved!
http://stackoverflow.com/tags/gatsby/info

**Comment by KyleAMathews** [comment]
nice! 👍
