### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by pavelnikitin** [gatsbyjs/gatsby#3300]
## Description

Describe the issue or the enhancement that you want to see.

### Environment

Gatsby version:
Node.js version:
Operating System:

### File contents (if changed):

`gatsby-config.js`: 
`package.json`: 
`gatsby-node.js`: 
`gatsby-browser.js`: 
`gatsby-ssr.js`: 

### Actual result

What happened.

### Expected behavior

What should happen?

### Steps to reproduce

1\.Hello Kayle ! Sorry for my bad english it's not my native language.
I have portfolio on hosting and from it i want to refferense on my webpage made with awesome Gatsby js.
How can I indicate the path, because refference from my portfolio just on index.html not working.But  it fine working with module http server /public in my cpu. Or how can i replace "/" on "./" in beginning path, because pathprefix add another "/" at beginning. Thanks!

2\.

3\.

...

**Comment by KyleAMathews** [comment]
You want to use an absolute link e.g. `https://example.com/portfolio`.

**Comment by pavelnikitin** [comment]
I want to link in my portfolio site index.html like 
"<a href="./gatsbywebpage/index.html">gatsbywebpage</a>". There is root folder on hosting "portfolio" made with just css and html, in there folder with gatsby project "gatsbywebpage" .A Folder "gatsbywebpage" it's renamed folder "public" made with script "gatsby build". "https://portfolio/gatsbywebpage/index.html"  - not working (error files not found in  browser's console).

**Comment by pavelnikitin** [comment]
I have understood, build with path-refix "/gatsbywebpage".Thanks Kyle. Closed.
