### ISSUE TITLE
Failed to write out requires Maximum call stack size exceeded when creating many pages (~150000)

### ISSUE THREAD

**Issue by hornetDC** [gatsbyjs/gatsby#33038]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

In my build, I fetch a large array of items and then create nodes with them. After about 120000 I get this error:

```
success run page queries - 86.493s - 140017/140017 1618.82/s

 ERROR 

Failed to write out requires Maximum call stack size exceeded



  RangeError: Maximum call stack size exceeded

  - requires-writer.ts:149 getMatchPaths
    [broker-pages]/[gatsby]/src/bootstrap/requires-writer.ts:149:20

  - requires-writer.ts:189 writeAll
    [broker-pages]/[gatsby]/src/bootstrap/requires-writer.ts:189:22

  - write-out-requires.ts:18 writeOutRequires
    [broker-pages]/[gatsby]/src/services/write-out-requires.ts:18:11

  - build.ts:123 build
    [broker-pages]/[gatsby]/src/commands/build.ts:123:9
```

On another run I get slightly different error log:

```
  RangeError: Maximum call stack size exceeded

  - requires-writer.ts:149 getComponents
    [broker-pages]/[gatsby]/src/bootstrap/requires-writer.ts:149:20
```

### Steps to Reproduce

I can't reproduce it outside of my project, but here is my setup:
1. Create local plugin
2. In plugins gatsby-node.js sourceNodes use "createNode" to create many nodes
3. In gatsby-node.js createPages get created nodes and create pages
4. Build

### Expected Result

Build desn't throw "Maximum call stack size exceeded" error

### Actual Result

Build throws "Maximum call stack size exceeded" error

### Environment

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.17.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.6 - C:\Python39\python.EXE
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.84)
  npmPackages:
    gatsby: 3.13.0 => 3.13.0 
    gatsby-image: ^3.11.0 => 3.11.0 
    gatsby-plugin-canonical-urls: ^3.13.0 => 3.13.0 
    gatsby-plugin-emotion: ^6.0.0 => 6.13.0 
    gatsby-plugin-gtag: ^1.0.13 => 1.0.13 
    gatsby-plugin-load-script: ^1.1.0 => 1.1.0 
    gatsby-plugin-manifest: ^3.13.0 => 3.13.0 
    gatsby-plugin-offline: ^4.13.0 => 4.13.0 
    gatsby-plugin-preconnect: ^1.2.0 => 1.2.1 
    gatsby-plugin-react-helmet: ^4.13.0 => 4.13.0 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.1 
    gatsby-plugin-remove-trailing-slashes: ^3.13.0 => 3.13.0 
    gatsby-plugin-root-import: ^2.0.5 => 2.0.7 
    gatsby-plugin-sharp: ^3.13.0 => 3.13.0 
    gatsby-plugin-svgr: ^3.0.0-beta.0 => 3.0.0-beta.0 
    gatsby-plugin-typescript: ^3.13.0 => 3.13.0 
    gatsby-plugin-use-query-params: ^1.0.1 => 1.0.1 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.22 => 1.1.25 
    gatsby-source-filesystem: ^3.13.0 => 3.13.0 
    gatsby-transformer-json: ^3.13.0 => 3.13.0 
    gatsby-transformer-sharp: ^3.13.0 => 3.13.0
```

**Comment by KyleAMathews** [comment]
Are you creating pages with `matchPath`? That's an expensive thing to do so if you can remove it, that's the best.

**Comment by LekoArts** [comment]
Hi!

Please provide a [minimal reproduction][reproduction] so that we can help you. Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by hornetDC** [comment]
> Are you creating pages with `matchPath`? That's an expensive thing to do so if you can remove it, that's the best.

You mean that?

```
exports.onCreatePage = async ({ page, actions }) => {
  const { createPage } = actions;

  if (page.path.match(/^\/listing/)) {
    createPage({ ...page, matchPath: '/listing/*' });
  }

  if (page.path.match(/^\/profile/)) {
    createPage({ ...page, matchPath: '/profile/*' });
  }
};
```

@LekoArts thing is, I can't =(
I created a test project, added over 200k pages and build worked. Trying to figure out the difference, probably "onCreatePage"

**Comment by hornetDC** [comment]
Issue is resolved, matchPath was the problem.
