### ISSUE TITLE
Github links lead to 404

### ISSUE THREAD

**Issue by Shriever** [gatsbyjs/gatsby#33031]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

I was reading through the [participation guildlines](https://github.com/gatsbyjs/gatsby/blob/5c06cd9ad46de28a3a43f9e51b03ea5814efdc32/docs/contributing/where-to-participate.md) and a few of the links were leading me to Github's 404 not found page.

### Steps to Resolve this Issue

1. Looks like the links are relative paths. Maybe it's better to use a full URL.

**Comment by LekoArts** [comment]
Hi!

Our docs are set up to be read on the website not on GitHub :)
You can read it here: https://www.gatsbyjs.com/contributing/where-to-participate/

**Comment by Shriever** [comment]
Oh silly me XD

Thanks for your patience with my noobity.
