### ISSUE TITLE
bug(node-api: pluginOptionsSchema): fails to pass validate options on warning

### ISSUE THREAD

**Issue by moonmeister** [gatsbyjs/gatsby#33033]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I'm working on a plugin and I head some test data in the plugin that was throwing a warning. I didn't mind and kept on my way. I noticed though that my defaults set in `Joi` were not being passed: 

Schema:
```js
export function pluginOptionsSchema({ Joi }: { Joi: PluginOptionsSchemaJoi }) {
  return Joi.object().keys({
    port: Joi.number(),
    host: Joi.string(),
    compression: Joi.boolean().default(true),
  });
}
```

plugin options:
```js
 {
      resolve: `gatsby-plugin-fastify`,
      options: {
        stuff: "test",
      },
    },
```

Expected plugin options:
```js
{
  compression: true,
  stuff: "test",
}
```

Actual received Plugin Options: 
```js
{
  stuff: "test",
}
```

### Issue:

the bug lies in the try catch statement of the validation code. https://github.dev/gatsbyjs/gatsby/blob/4a765b5c62208d58f0bd7fd59558160c0b9feed3/packages/gatsby/src/bootstrap/load-plugins/validate.ts

On line 227 the awaited validation throws when there is a warning. this moves into the catch statement as expect. Except this means the assignment to `plugin.options` never happens and the rest of the code from lines 218-240. All of which SHOULD happen if there is a warning. 

### Steps to Reproduce

If the above isn't clear, let me know. 

### Environment

```shell
System:
    OS: macOS 11.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.4 - /var/folders/zv/tlvx0jxx3mg89pcbfr4ptzbc0000gp/T/yarn--1630613025893-0.9394872895630431/node
    Yarn: 1.22.10 - /var/folders/zv/tlvx0jxx3mg89pcbfr4ptzbc0000gp/T/yarn--1630613025893-0.9394872895630431/yarn
    npm: 7.20.3 - ~/.nvm/versions/node/v14.17.4/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 92.0.4515.159
    Firefox: 91.0.2
    Safari: 14.1.2
  npmPackages:
    gatsby: ^3.6.1 => 3.14.0-next.1 
    gatsby-plugin-fastify: * => 0.3.2
```

**Comment by moonmeister** [comment]
FYI, I believe this is contributing to several subtle bugs in the `gatsby-plugin-sitemap`. I wrote that plugin using this API to set defaults. 

https://github.com/gatsbyjs/gatsby/issues/31416 is definitely caused by this and another I can't seem to find atm is probably caused by this as well.

**Comment by moonmeister** [comment]
https://github.com/sideway/joi/issues/2669

**Comment by TylerBarnes** [comment]
Good catch! seems like validateOptionsSchema shouldn't throw when an option is omitted but there's a default 🤔 

Looks to me like the `warnings` option should be set to true here https://github.com/gatsbyjs/gatsby/blob/4712acc619c19cd23a1b2e94e7253ddd624aa927/packages/gatsby-plugin-utils/src/validate.ts#L24

see https://joi.dev/api/?v=17.4.2#anyvalidateasyncvalue-options

And then warning handling should be moved out of the catch block.

**Comment by moonmeister** [comment]
So I think I tried that and it was still throwing but it's been a couple weeks so I don't remember specifically.  I tried a lot of things. If you can figure it out, great!!

**Comment by TylerBarnes** [comment]
I wont have time to work on it myself, just triaging issues right now, but if someone wants to dive into it I think that's probably the solution. Might take some more investigation though. As a workaround you can set default plugin options on the plugin options object before accessing options in your plugin.

**Comment by moonmeister** [comment]
Okay, so the issue here is `allowUnknown` is set to false. Which makes unknown fields errors, not warnings. For @TylerBarnes' suggestion to work we need to be able to throw a Joi warning, not an error when an unknown field is encountered. I'll double check setting `allowUnknown` to true doesn't make them warnings, but I assume it means they are just ignored.

**Comment by moonmeister** [comment]
not stale
