### ISSUE TITLE
[gatsby-plugin-gatsby-cloud] Mandatory plugin breaks builds on Gatsby Cloud even if not installed in your project

### ISSUE THREAD

**Issue by thclark** [gatsbyjs/gatsby#33042]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Building on Gatsby Cloud now **forces** installation of `gatsby-plugin-gatsby-cloud` regardless of whether you want or need it.

Unfortunately, that breaks the build (which works fine without the plugin), and I can't get rid of it because I've no control over the Gatsby Cloud environment scripts.

### Reproduction Link

https://github.com/octue/planex-site/tree/b712dc12227c0089d8a59bf0766ae82c23cf7fd0

### Steps to Reproduce

Yes, I know the reproduction link above is supposed to be a clean vanilla repository, but if the problem were reproducible like that then every single build using gatsby 3 would be breaking, so it's not as easy as that unfortunately. 

I've made the steps as easy for you as possible...

At that sha above, the repo will build locally but not on Gatsby Cloud, because GC forces installation of the aforementioned plugin. To reproduce the issue locally, you can do:

1.  Git clone the tree above with:
```
git clone https://github.com/octue/planex-site.git
git checkout b712dc12227c0089d8a59bf0766ae82c23cf7fd0
```
2. `yarn install`
3. `yarn run gatsby build` << builds perfectly fine
4. `yarn add gatsby-plugin-gatsby-cloud`
5. Install the plugin in gatsby-config [as instructed](https://www.gatsbyjs.com/plugins/gatsby-plugin-gatsby-cloud/) `plugins: [ 'gatsby-plugin-gatsby-config', ...]`
6. `yarn run gatsby build` << yields the error below

### Expected Result

Successful build

### Actual Result

The build fails with the following error:
```

Error in "/Users/thc29/source/octue/planex-site/node_modules/gatsby-plugin-gatsby-cloud/gatsby-node.js": Cannot read property 'RawSource' of undefined



  TypeError: Cannot read property 'RawSource' of undefined
  
  - WebpackAssetsManifest.js:17 Object.<anonymous>
    [planex-site]/[webpack-assets-manifest]/src/WebpackAssetsManifest.js:17:47
  
  - v8-compile-cache.js:192 Module._compile
    [planex-site]/[v8-compile-cache]/v8-compile-cache.js:192:30
  
  - loader:1138 Object.Module._extensions..js
    node:internal/modules/cjs/loader:1138:10
  
  - loader:989 Module.load
    node:internal/modules/cjs/loader:989:32
  
  - loader:829 Function.Module._load
    node:internal/modules/cjs/loader:829:14
  
  - loader:1013 Module.require
    node:internal/modules/cjs/loader:1013:19
  
  - v8-compile-cache.js:159 require
    [planex-site]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - gatsby-node.js:7 Object.<anonymous>
    [planex-site]/[gatsby-plugin-gatsby-cloud]/gatsby-node.js:7:53
  
  - v8-compile-cache.js:192 Module._compile
    [planex-site]/[v8-compile-cache]/v8-compile-cache.js:192:30
  
  - loader:1138 Object.Module._extensions..js
    node:internal/modules/cjs/loader:1138:10
  
  - loader:989 Module.load
    node:internal/modules/cjs/loader:989:32
  
  - loader:829 Function.Module._load
    node:internal/modules/cjs/loader:829:14
  
  - loader:1013 Module.require
    node:internal/modules/cjs/loader:1013:19
  
  - v8-compile-cache.js:159 require
    [planex-site]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - resolve-module-exports.ts:197 resolveModuleExports
    [planex-site]/[gatsby]/src/bootstrap/resolve-module-exports.ts:197:26
  
  - validate.ts:349 
    [planex-site]/[gatsby]/src/bootstrap/load-plugins/validate.ts:349:31
  

not finished open and validate gatsby-configs, load plugins - 0.571s
```

### Environment

```shell
The working local build is as follows:


  System:
    OS: macOS 11.5.2
    CPU: (8) arm64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - /var/folders/5t/2c5j81h11kvb2151y1f7rdh80000gn/T/yarn--1630686364769-0.6686595308620291/node
    Yarn: 1.22.10 - /var/folders/5t/2c5j81h11kvb2151y1f7rdh80000gn/T/yarn--1630686364769-0.6686595308620291/yarn
    npm: 7.15.1 - /opt/homebrew/bin/npm
  Languages:
    Python: 3.9.1 - /Users/thc29/.pyenv/shims/python
  Browsers:
    Chrome: 93.0.4577.63
    Safari: 14.1.2
  npmPackages:
    gatsby: ^3.0.0 => 3.13.0 
    gatsby-background-image: ^1.4.1 => 1.5.3 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-google-gtag: ^3.13.0 => 3.13.0 
    gatsby-plugin-image: ^1.10.1 => 1.13.0 
    gatsby-plugin-manifest: ^3.13.0 => 3.13.0 
    gatsby-plugin-offline: ^4.13.0 => 4.13.0 
    gatsby-plugin-react-helmet: ^4.13.0 => 4.13.0 
    gatsby-plugin-robots-txt: ^1.6.8 => 1.6.10 
    gatsby-plugin-sharp: ^3.13.0 => 3.13.0 
    gatsby-plugin-sitemap: ^4.6.0 => 4.9.0 
    gatsby-source-datocms: ^2.6.16 => 2.6.16 
    gatsby-source-filesystem: ^3.13.0 => 3.13.0 
    gatsby-theme-material-ui: ^2.0.1 => 2.0.1 
    gatsby-transformer-sharp: ^3.13.0 => 3.13.0 
```

The reproduced failing build gives:
```


### Config Flags

_No response_

**Comment by thclark** [comment]
# Workaround

This can be worked around by removal of `gatsby-plugin-gatsby-cloud` from your `gatsby-config.js` file, and addition of the following script in `package.json`:
```
  "scripts": {
    "postinstall": "rm -rf node_modules/gatsby-plugin-gatsby-cloud && echo TODO remove this postinstall script (see https://github.com/gatsbyjs/gatsby/issues/33042 )",
  }
```

**Comment by graysonhicks** [comment]
Hi @thclark !  Thanks for the report and workaround for this.  I don't see any instances of this happening before on our end.  I have gotten your support ticket via Gatsby Cloud so I am going to close this and we will make an internal Gatsby, Inc. ticket to track down what is causing this.  Thanks!

**Comment by thclark** [comment]
Thanks @graysonhicks yeah, I figured there's some weird edge case in there; something to do with the webpack upgrade I expect.

**Comment by pepijn-vanvlaanderen** [comment]
Got the same error as above after updating packages. I noticed two versions of webpack (4&5) in the yarn lock and found this: https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#handling-dependencies-for-plugins-that-are-not-yet-updated

So eventually after adding the resolutions and reinstalling all packages the error went away:
```
{
  "resolutions": {
    "graphql": "^15.4.0",
    "graphql-compose": "^7.25.0",
    "webpack": "^5.24.2"
  }
}
```

**Comment by thclark** [comment]
@pepijn-vanvlaanderen thanks, that's significantly more elegant than my brutal workaround :rofl:

**Comment by iamkratos** [comment]
@pepijn-vanvlaanderen ty 🙏

**Comment by LinnJS** [comment]
@thclark thanks so much for following up fixed this on all my projects, big face palm moment for me as well 🙂

**Comment by LinnJS** [comment]
Just wanted to note on this issue I had to add the `resolutions` otherwise this wont work reliably.

**Comment by LekoArts** [comment]
@thclark I've edited your workaround message to point to the `resolutions` as your suggestion is breaking Gatsby Cloud functionality. For Gatsby 4 features (SSR/DSG) and coming features to work, `gatsby-plugin-gatsby-cloud` needs to be installed.

**Comment by thclark** [comment]
> @thclark I've edited your workaround message to point to the `resolutions` as your suggestion is breaking Gatsby Cloud functionality. For Gatsby 4 features (SSR/DSG) and coming features to work, `gatsby-plugin-gatsby-cloud` needs to be installed.

Thanks @LekoArts, that avoids anyone skipping over the rest of the conversation. Good practice when you're editing other people's comments, though, is to strikethrough their comments ~~using two tildes~~ rather than completely remove them, so what's happened is more easily understandable.

**Comment by LinnJS** [comment]
@thclark thanks for taking the time to respond and clarify embarrassingly enough I didn't see your response till now when I re-googled this issue that I had on another project and forgot how to fix.
