### ISSUE TITLE
Try using v8-compile-cache

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#3306]
webpack-cli just added it and saw substantial speedups

https://twitter.com/ev1stensberg/status/943865463406301184

https://www.npmjs.com/package/v8-compile-cache

**Comment by KyleAMathews** [comment]
Easy to add — just require it https://github.com/webpack/webpack-cli/commit/0564ceb77a995239d0be7a022b948cbd727773a4

**Comment by pwener** [comment]
Eu posso fazer?

**Comment by KyleAMathews** [comment]
@pwener would love a PR! Please test the bootstrap times with and without the compile cache.

**Comment by pwener** [comment]
Hello, where you think would be the best place to put this? I've try with `gatsby/packages/gatsby/src/bin/gatsby.js` but the bootstrap times decreased little.

**Comment by KyleAMathews** [comment]
It might not have much effect. Try adding a process.exit() right after the require and measure the time to their with and without the require.

**Comment by pwener** [comment]
The results were good, can you evaluate my PR @KyleAMathews?

**Comment by KyleAMathews** [comment]
PR merged 💯
