### ISSUE TITLE
gatsby-source-graphql

### ISSUE THREAD

**Issue by MotaZor94** [gatsbyjs/gatsby#33065]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi everyone,

we are experiencing a weird issue during the builds in Gatsby.

After our colleague duplicated rows in Strapi, we started seeing this error and we simply can't track it down for the past 3 days now.

Did anyone have any experience with something similar to this, or if there is a way to fix this issue?

There was an error in your GraphQL query:

select "programmes".* from "programmes" where "programmes"."id" = $1 limit $2 - invalid input syntax for type integer:
"{}"

File path: /Users/markocolic/Desktop/WORK-CMS/GUS-MAIN/src/templates/landing-page.js
Url path: /online/study-online
Plugin: none

### Reproduction Link

N/A

### Steps to Reproduce

1. Duplicate table row in Strapi
2. Run gatsby build
3. You will see this issue.
...

### Expected Result

We are expecting to see the data on the front end.

### Actual Result

The builds are failing due to the graphql error.

### Environment

```shell
System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 93.0.4577.63
    Safari: 14.1.1
  npmPackages:
    gatsby: 3.6.2 => 3.6.2
    gatsby-plugin-eslint: 3.0.0 => 3.0.0
    gatsby-plugin-image: ^1.1.0 => 1.1.0
    gatsby-plugin-manifest: 3.0.0 => 3.0.0
    gatsby-plugin-offline: 4.0.0 => 4.0.0
    gatsby-plugin-postcss: ^4.0.0 => 4.0.0
    gatsby-plugin-react-helmet: 4.0.0 => 4.0.0
    gatsby-plugin-remove-fingerprints: 0.0.2 => 0.0.2
    gatsby-plugin-sharp: ^3.0.1 => 3.0.1
    gatsby-plugin-styled-components: ^4.6.0 => 4.6.0
    gatsby-source-filesystem: ^3.1.0 => 3.1.0
    gatsby-source-graphql: ^3.6.0 => 3.6.0
    gatsby-source-strapi: ^1.0.2 => 1.0.2
    gatsby-transformer-sharp: ^3.1.0 => 3.1.0
  npmGlobalPackages:
    gatsby-cli: 3.6.0
```

**Comment by LekoArts** [comment]
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!
