### ISSUE TITLE
[gatsby-link] `to` should be of type string or location object

### ISSUE THREAD

**Issue by nsimonson** [gatsbyjs/gatsby#3309]
## Description

`gatsby-link` does not accept a location object as specified in [react-router](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/Link.md#to-object) as a valid prop.

### Environment

Gatsby version: 1.9.119
Node.js version: 8.9.1
Operating System: macOS 10.13.2

### Actual result

`<Link to={{ pathname: '/my-page', search: '?sort=name', }} />`

Passing an object to the `to` prop of `Link` results in a url of "/[object Object]"

### Expected behavior

Url should be "/my-page?sort=name"

...

Current work around is to use Link directly from `react-router-dom`

**Comment by KyleAMathews** [comment]
Yeah, we don't currently support the location version — for no particular reason :-) Happy to take a PR to gatsby-link adding support!
