### ISSUE TITLE
Gatsby source wordpress fails on lots of products.

### ISSUE THREAD

**Issue by TomasSinkevicius** [gatsbyjs/gatsby#33139]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

After adding a lot of products to wordpress woocomerce, graphql fails to fetch and gives me this error: 

` ERROR #gatsby-source-wordpress_111007 

 gatsby-source-wordpress  Request failed with status code 500

Your WordPress server is either overloaded or encountered a PHP error.

Error occurred while fetching nodes of the "Product" type.

Enable WordPress debugging by adding the following to your wp-config.php file:

define("WP_DEBUG", true);
define("WP_DEBUG_LOG", true);
define("GRAPHQL_DEBUG", true);

(See https://wordpress.org/support/article/debugging-in-wordpress/ for more info)

Then run another build before checking your WordPress instance's debug.log file for errors.

If you don't see any errors in debug.log:

Try reducing the requestConcurrency for content updates or the previewRequestConcurrency for previews, and/or
reducing the schema.perPage option:

{
  resolve: 'gatsby-source-wordpress',
  options: {
    schema: {
      perPage: 20, // currently set to 20
      requestConcurrency: 5, // currently set to 5
      previewRequestConcurrency: 2, // currently set to 2
    }
  },
}

not finished source and transform nodes - 57.910s
not finished  gatsby-source-wordpress  fetching nodes - 57.835s - 388 total
not finished  gatsby-source-wordpress  Product - 33.799s - fetched 80`

If i add this line to the gatsby source wordpress everything starts normally. 
`  type: {
          Product: {
            limit:
              process.env.NODE_ENV === `development`
                ? // Lets just pull 50 posts in development to make it easy on ourselves (aka. faster).
                  50
                : // and we don't actually need more than 5000 in production for this particular site
                  5000,
          },
        },`

### Reproduction Link

https://github.com/brandu-agency/Etikete

### Steps to Reproduce

Add a lot of products to wordpress woocomerce.

### Expected Result

Graphql to fetch all the products.

### Actual Result

Graphql fails to fetch all products.

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.8.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 93.0.4577.63
    Firefox: 91.0.2
    Safari: 14.0
  npmPackages:
    gatsby: ^3.10.2 => 3.10.2
    gatsby-plugin-gatsby-cloud: ^2.10.0 => 2.10.0
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-image: ^1.10.1 => 1.10.1
    gatsby-plugin-manifest: ^3.10.0 => 3.10.0
    gatsby-plugin-offline: ^4.10.0 => 4.10.0
    gatsby-plugin-polished: ^1.0.4 => 1.0.4
    gatsby-plugin-react-helmet: ^4.10.0 => 4.10.0
    gatsby-plugin-react-svg: ^3.0.1 => 3.0.1
    gatsby-plugin-sass: ^4.11.0 => 4.11.0
    gatsby-plugin-sharp: ^3.10.2 => 3.10.2
    gatsby-plugin-styled-components: ^4.10.0 => 4.10.0
    gatsby-plugin-svgr: ^3.0.0-beta.0 => 3.0.0-beta.0
    gatsby-source-filesystem: ^3.10.0 => 3.10.0
    gatsby-source-wordpress: ^5.10.0 => 5.10.0
    gatsby-transformer-sharp: ^3.10.0 => 3.10.0
  npmGlobalPackages:
    gatsby-cli: 3.4.1
```

**Comment by graysonhicks** [comment]
You need to allocate more resources to your Wordpress server.  What do the Wordpress debug logs say?

**Comment by TomasSinkevicius** [comment]
Update. I have allocated 512MB memory in wp.config file and it seems that this fixed the issue. Thanks.

`define( ‘WP_MEMORY_LIMIT’, ‘512M’ );`

**Comment by graysonhicks** [comment]
Great to hear, thanks @TomasSinkevicius
