### ISSUE TITLE
Gatsby Cloud keeps using cache even if the child fields in GraphQL have updates

### ISSUE THREAD

**Issue by xxbxxqxx** [gatsbyjs/gatsby#33195]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi there,
I found that Gatsby Cloud cannot update GraphQL when I create a new post in Contentful.
I assume that Gatsby Cloud cannot detect the updates of child fields in GraphQL.
I'd appreciate if you have any idea and give me some advice.

**Precondition**
- The app is running on Gatsby Cloud and uses Contentful as CMS.
- The app has the page that lists up the posts created on Contentful.
- The posts data can be retrieved in `allContentfulBlogPosts` in GraphQL
- Each post has a category and these data(and these relations) can be retrieved in `allContentfulBlogPostsCategory` in GraphQL

**Problem**
- when I create a new post on Contentful and the builds on gatsby cloud side done,
  - `allContentfulBlogPosts` reflects newly-created posts(that's what I expected)
  - but `allContentfulBlogPostsCategory` does NOT reflect newly-created posts(that's NOT what I expected)

**The GraphQL query is as follows**:
```
// GraphQL
export const pageQuery = graphql`
  query {
    allContentfulBlogPostsCategory {
      edges {
        node {
          title
          slug
          blog_posts {
            title
            slug
          }
        }
      }
    }
    allContentfulBlogPosts{
      edges {
        node {
          title
          slug
        }
      }
    }
```

**`blog_posts { ~  }` in `allContentfulBlogPostsCategory` is the same objects as `allContentfulBlogPosts`.**

### Steps to Reproduce

1. Create a new post on Contentful
2. Gatsby Cloud starts to build and done
3. `allContentfulBlogPosts` ... it reflects newly-created posts
4. `allContentfulBlogPostsCategory` ... it does NOT reflect newly-created posts
5. If I "clear cache and restart builds" on the Gatsby dashboard, `allContentfulBlogPostsCategory` reflects newly-created posts.

### Expected Result

In `allContentfulBlogPostsCategory` it can reflect fresh data even if related posts in the child field are updated or newly created.

### Actual Result

If I create a new entry on Contentful,
- `allContentfulBlogPosts` ... it reflects newly-created posts
- `allContentfulBlogPostsCategory` ... it does NOT reflect newly-created posts

It happens both in production Builds(Gatsby Cloud Builds) and Preview Builds.

**If I "clear cache and restart builds" on the Gatsby dashboard, `allContentfulBlogPostsCategory` reflects newly-created posts.**

### Environment

```shell
"gatsby": "^3.4.1",
"gatsby-plugin-gatsby-cloud": "^2.4.1",
```

**Comment by nbangba** [comment]
I am also facing this issue. I found reports on this issue as far back as 2018. I don't know if there is a work around or  I am not doing something right

**Comment by LekoArts** [comment]
Hi!

For Gatsby Cloud specific support please go here: https://www.gatsbyjs.com/support/
