### ISSUE TITLE
[Discussion] AMP Pages with Gatsby

### ISSUE THREAD

**Issue by misscs** [gatsbyjs/gatsby#3319]
Opening this issue to discuss a functioning (and flexible) solution for generating valid AMP pages. I'm looking for feedback and improvements to the code, as I do believe it can be better. This solution is working on a project that's using one template to generate thousands of pages. 

The biggest hurdle to generating valid AMP pages with Gatsby is removing all the JS bundles that Gatsby automatically inlines in the head during the build process. My solution is to filter these out in `componentWillMount` in `html.js`. 

```js
  componentWillMount(props) {

  if (process.env.NODE_ENV === `production`) {
    function isJSFile(obj) {
      if ( (typeof obj.key === 'string' || obj.key instanceof String) ) {
        return path.isAbsolute(obj.key) === true
      }
    }

    const ampify = this.props.headComponents.filter((obj, index) => {
      return obj.key !== 'webpack-manifest' && obj.type !== 'script' && !(isJSFile(obj))
    })

    this.props.headComponents = ampify
  }
}
```

I feel like this solution is still a bit hacky. Given that AMP pages won't use any JS, it seems like an unnecessary use of cycles to even generate the files in the first place. Personally, I think it would be much cleaner to pass a flag to a build process that instructs Gatsby not to output any JS files. 

I'm curious what folks that more familiar with Gatsby internals think. Would a plugin be a more flexible solution? Are there any gotchas, or conerns, you have with this approach?

I'm working on a more indepth write-up to share the full project implementation. Feel free to ask questions in the meantime. 

Big thanks in advance to @KyleAMathews for answering my questions on Twitter throughout the development process and for making such a fun, elegant framework.

**Comment by calcsam** [comment]
@chiedo made a starter kit to do this. His approach is basically to take the outputted files and then use a separate step to convert them into AMP.

https://github.com/chiedo/gatsby-amp-starter-blog/blob/master/ampify.js

You could extend this to be a plugin, which would make it much more composable; users would have to place this plugin last in their plugin list for it to work properly. 

A good example here is plugins that implement `gatsby-ssr`, eg https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-google-analytics/src/gatsby-ssr.js

Here's the docs:
https://www.gatsbyjs.org/docs/ssr-apis/#replaceRenderer

**Comment by calcsam** [comment]
Ah, read the other thread -- you've already taken a look at the current AMP starter kit. 

Your approach seems good. Would love to see a starter kit using your approach. Looks like converting to a plugin may be hard with the current APIs as `setHeadComponents` does concatenation rather than replacement. In addition blocking all JS generation may not be possible as other parts of gatsby (GatsbyLink chunk prefetching -- take a look at the docs at https://www.gatsbyjs.org/packages/gatsby-link/ or watch the network tab at eg reactjs.org)

**Comment by misscs** [comment]
@chido’s starter kit is not a viable solution. It doesn’t account for all the possibilities within AMP. It’s quite limited. For example, it does not account for all the attributes one can set on `amp-img` or any of the other amp components. 

In React, there’s no need to replace HTML components with amp components in post step. Just create a component. 

The complex part is removing the JS. I actually do not see the issue with Gatsby-Link and AMP pages. AMP needs to be 100% static which means that the benefits of GatsbyLink don’t really apply. If you are going for 100% AMP then don’t use GatsbyLink, just use plain old html `<a>`.

**Comment by chiedo** [comment]
@misscs there are A LOT of different way you can treat AMP pages. In my solution, you can do whatever you want after this. https://github.com/chiedo/gatsby-amp-starter-blog/blob/master/ampify.js#L65

I currently use my solution on 5 websites and it works like a charm. :)

But my way isn't the only way. Just a way that is proven and works in production and can be customized. It's definitely not plug and play... coding is required.

**Comment by misscs** [comment]
@chiedo Quite true! Many ways to skin the amp cat.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
