### ISSUE TITLE
site search

### ISSUE THREAD

**Issue by Maxhodges** [gatsbyjs/gatsby#332]
what are some strategies to getting search working on a static generated site? i.e. is it possible to allow people to search my blog if it's a static site? How would that work?

**Comment by ivanoats** [comment]
I'm working on LunrJS integration. Therepo is on https://bitbucket.org/aerobatic/gatsby-lunr and hope to have a blog post on it by end of week.

**Comment by Maxhodges** [comment]
thanks mate! LunrJS looks pretty good. Do let us know when your blog post is up!

**Comment by MoOx** [comment]
You might find interesting stuff in this issue https://github.com/MoOx/phenomic/issues/142

**Comment by erlend-sh** [comment]
An officially supported strategy for search in Gatsby would be wonderful. I'm not aware of a "1.1" or "2.0" roadmap, but if there was such a thing I'd vote for "Search" to be on there.

@bvaughn was [asking around about Gatsby site search](https://twitter.com/erlend_sh/status/883229845588672512) a while back, and I replied:

> I'd love to see a plugin for @fergiemcdowall's [norch](https://github.com/fergiemcdowall/norch) [and/or [search-index](https://github.com/fergiemcdowall/search-index)]

I know great search can be achieved with services like Algolia or Elastic, but it'd be nice to have a fairly feature-rich self-hosted option, static or otherwise.

**Comment by bvaughn** [comment]
FWIW I still have plans to build a plug-in for [js-worker-search](https://github.com/bvaughn/js-worker-search) at some point.

**Comment by DanielRuf** [comment]
Any updates on this? Please use GitHub repos so we can collaborate.

**Comment by andrew-codes** [comment]
I turned some earlier work from this thread into a gatsby plugin NPM package; [npm](https://www.npmjs.com/package/%40andrew-codes%2Fgatsby-plugin-elasticlunr-search) and [repo](https://github.com/andrew-codes/gatsby-plugin-elasticlunr-search). I'd like some feedback on it, though. I feel like the `gatsby-config.js` was not intended to have imperative code like in the example of the readme. If this is true, I'm thinking of refactoring the plugin to use sub-plugins to index the content.

Thoughts?

**Comment by KyleAMathews** [comment]
Adding code to the config is certainly allowed as it's a normal node.js module, especially small amounts of code like in your readme. If the plugin could require more code than that, I'd encourage consumers to out the code in a separate module.

**Comment by andrew-codes** [comment]
I believe that is the extent of code required for the config file. I will submit a PR shortly to the docs's page listing the above plugin on the list of community supported plugins. Thanks!

**Comment by fergiemcdowall** [comment]
Heres an article about how to make a searchable static site with `search-index`: http://www.gordonburgett.net/post/2017/07_making_a_searchable_static_site/

**Comment by KyleAMathews** [comment]
Closing this issue as it's a problem that'll be solved via plugins rather than in Gatsby core.
