### ISSUE TITLE
docs: Tutorial part 6 & 7 code highlight doesn't rendered correctly.

### ISSUE THREAD

**Issue by mupinnn** [gatsbyjs/gatsby#33204]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

Hi, I am going through Gatsby v3 tutorial part 6, and I saw this [code line highlighting](https://www.gatsbyjs.com/contributing/gatsby-style-guide/#code-formatting-line-highlighting) not working well.

![Screenshot_2021-09-16_07-14-14](https://user-images.githubusercontent.com/46535277/133529326-04f47a8c-8078-464e-b1da-0c4a05176854.png)

And when I am going to the next part which is part 7, I saw that problem again.

![Screenshot_2021-09-16_07-20-07](https://user-images.githubusercontent.com/46535277/133529658-1a93e114-f750-44ac-bab4-f59e8f59974f.png)

I want to really know is it really true if I or other people want to contribute to fixing the documentation, we can't see the changes locally? Before I addressing this issue, I'm trying to resolve it first but I don't know exactly how to see the local version of Gatsby's site, and then I found [this statement](https://www.gatsbyjs.com/contributing/docs-contributions/#:~:text=there%20is%20no%20way%20for%20community%20members%20to%20build%20the%20docs%20site%20locally.). Telling that community can't build the docs locally :(

### Steps to Resolve this Issue

1. Check the code highlighting feature inside `.mdx` code blocks.

**Comment by cary-mao** [comment]
In the part 6, I got a different error.
```js
export const query = graphql`
  query {
    allMdx(sort: {fields: frontmatter___date, order: DESC}) {
      nodes {
        frontmatter {
          date(formatString: "MMMM D, YYYY")
          title
        }
        id
        slug
      }
    }
  }
`
```
In my blog page, the slug was undefined.
![image](https://user-images.githubusercontent.com/77195068/133579417-b7040f5b-004e-45ef-b6f9-740ac1863369.png)

Have you encountered the same problem?

**Comment by cary-mao** [comment]
> ### Preliminary Checks
> * [x]  This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
> * [x]  This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions
> 
> ### Summary
> Hi, I am going through Gatsby v3 tutorial part 6, and I saw this [code line highlighting](https://www.gatsbyjs.com/contributing/gatsby-style-guide/#code-formatting-line-highlighting) not working well.
> 
> ![Screenshot_2021-09-16_07-14-14](https://user-images.githubusercontent.com/46535277/133529326-04f47a8c-8078-464e-b1da-0c4a05176854.png)
> 
> And when I am going to the next part which is part 7, I saw that problem again.
> 
> ![Screenshot_2021-09-16_07-20-07](https://user-images.githubusercontent.com/46535277/133529658-1a93e114-f750-44ac-bab4-f59e8f59974f.png)
> 
> I want to really know is it really true if I or other people want to contribute to fixing the documentation, we can't see the changes locally? Before I addressing this issue, I'm trying to resolve it first but I don't know exactly how to see the local version of Gatsby's site, and then I found [this statement](https://www.gatsbyjs.com/contributing/docs-contributions/#:~:text=there%20is%20no%20way%20for%20community%20members%20to%20build%20the%20docs%20site%20locally.). Telling that community can't build the docs locally :(
> 
> ### Steps to Resolve this Issue
> 1. Check the code highlighting feature inside `.mdx` code blocks.

Luckly, my program ran successfully after restarting the computer and you can make a try.

**Comment by LekoArts** [comment]
Hi!

We're aware of the issue and will fix it :) Thanks
