### ISSUE TITLE
Onchange event not fired after reloading page and setting default state value

### ISSUE THREAD

**Issue by jbred** [gatsbyjs/gatsby#33205]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I have this page where I read a value from the url and set it as the default state in a useState hook. 
When updating the input field, the value is written back to the url. Everything works as expected in develop, but in a build the onChange event of the input element ist not fired, if the default state of the input value contains only a single character. When it contains multiple characters the onChange event is fired.

```
import React, { useState } from "react";
import querystring from "query-string";
import { navigate } from "gatsby";

const setUrl = (search) => {
  const parameters = querystring.stringify({
    search,
  });
  navigate(`/?${parameters}`);
};

const parseQueryString = (queryString) => ({
  search: queryString.search,
});

const Index = ({ location }) => {
  const { search } = parseQueryString(querystring.parse(location.search));
  const [value, setValue] = useState(search);
  const handleChange = (e) => {
    console.log(`handleChange ${e.target.value}`);
    setUrl(e.target.value);
    setValue(e.target.value);
  };
  return (
    <div>
      <input type="text" value={value} onChange={handleChange} />
    </div>
  );
};

export default Index;

```

### Reproduction Link

https://github.com/Alexander-Burkle/gatsby-input-bug.git

### Steps to Reproduce

1.  **Install dependencies**

    ```shell
    yarn
    ```

2.  **build site and serve**

    ```shell
    gatsby build
    gatsby serve
    ```

3.  **Open the page in browser**

    Enter just one single charachter in the input and observe how this value is written to the url query params.

4.  **Reload page**

    As expected the search value from the url search parameter is inserted in the input field.

5.  **Remove the charachter**

    Delete the character from the input field.

### Expected Result

Removing a value from the input field triggers the onChange event and updates the url search parameter

### Actual Result

The url is not updated, if only a single character is read from the url. This only happens when serving a build not in develop.

### Environment

```shell
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.4 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 93.0.4577.82
    Firefox: 91.0
    Safari: 14.1.1
  npmPackages:
    gatsby: ^3.13.0 => 3.13.0
  npmGlobalPackages:
    gatsby-cli: 3.5.0
```

**Comment by wardpeet** [comment]
Have you tried using replace instead? Each navigation change will re-render React. Check https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/#replace-history-during-programmatic-navigation
