### ISSUE TITLE
[graphql] "absolute" filepath to fileNode

### ISSUE THREAD

**Issue by zionis137** [gatsbyjs/gatsby#3322]
## Current State
Currently strings that look like relative paths are replaced with a fileNode. 

For example:

```
---
title: relative Demo
image: "cat.png"
---

## this is a post with a relative image path

```
`image` is converted to a fileNode which allows GraphQL queries like

```
image{
 childImageSharp {
    ....
  }
}
```

This does not work for "absolute" paths that start with `/`. 

## Motivation 
Netlify-CMS is only working with absolute paths for images and files. So it is currently not possible to use [gatsby-image](https://www.gatsbyjs.org/packages/gatsby-image/) if the markdown file is generated by netlify-cms

## Proposal

paths that start with `/` should also be converted into fileNodes. 
For example:
```
---
title: absolute Demo
image: "/src/pages/absoluteDemo/absCat.png"
---

## this is a post with an absolute image path
```

## Related Issues
* https://github.com/netlify/netlify-cms/issues/325
* https://github.com/gatsbyjs/gatsby/issues/2968
* https://github.com/gatsbyjs/gatsby/issues/950

**Comment by calcsam** [comment]
Have you taken a look at https://github.com/netlify/netlify-cms/issues/325? There seems to be a workaround there, that breaks preview on the Netlify CMS. 

Seeing paths like /src/pages/absoluteDemo/absCat.png is a bit weird because the implication is that that is the absolute path from your computer root directory, where it's actually a relative path from your gatsby project root. This seems semantically confusing.

**Comment by zionis137** [comment]
In netlify-cms I can set the image-directory like this:
```
media_folder: /data/img
```
And then it feels more natural to use `/data/image/cat.png` in gatsby than (for example) `../../../data/image/cat.png`



> Seeing paths like /src/pages/absoluteDemo/absCat.png is a bit weird because the implication is that that is the absolute path from your computer root directory, where it's actually a relative path from your gatsby project root. This seems semantically confusing.

I agree, the path `/src/pages/absoluteDemo/absCat.png` is not technically an correct (absolute) path. But it is a helpful extension and the  **real** absolute path should (hopefully) never be used in projects

**Comment by ilyabo** [comment]
I found a way to work around this problem. Check this out: https://github.com/netlify/netlify-cms/issues/325#issuecomment-354514547

**Comment by zionis137** [comment]
Thanks, that works for me. 

I would still love to see this either directly in core or as a plugin

**Comment by KyleAMathews** [comment]
See my comment there. You shouldn't mutate data directly but instead use https://www.gatsbyjs.org/docs/bound-action-creators/#createNodeField

This absolutely could be a plugin

**Comment by zionis137** [comment]
@KyleAMathews what about adding the functionality directly to the core (like i started with https://github.com/gatsbyjs/gatsby/pull/3323 )? 

Or do you strongly prefer it as a plugin?

**Comment by ilyabo** [comment]
Or maybe this could be an option of `gatsby-source-filesystem`? Something like: 
```
   {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/static/img/`,
        name: 'images',
        relativePaths: true    // or absolute from the project's 'public' dir
      }
    }
```


Then gatsby could have some special treatment for such nodes. There is this place in `infer-graphql-type.js` where it currently fails to find the matching image file nodes for the relative paths referred to in the frontmatter:
```
  const pathToOtherNode = normalize(joinPath(rootNode.dir, value))
  const otherFileExists = getNodes().some(
    n => n.absolutePath === pathToOtherNode
  )
```

I think this would actually work if `n.absolutePath` was in fact absolute relative from the project's `public` directory.

**Comment by aaronaustin** [comment]
I tried the workaround above with createNodeField, but when I run my query with `imageLocalFile___NODE` I get this error: GraphQL Error Unknown field imageLocalFile___NODE on type fields`.  The relative path is there in `imageLocalFile`.  Not sure what I'm doing wrong here.

**Comment by KyleAMathews** [comment]
Sorry, my instructions were wrong. You need to find the File node and link to its id.

**Comment by aaronaustin** [comment]
Thanks.  Are there any instructions on how to access the File node? Right now, I'm just able to get to the relative path string created by ilyabo's code here: https://github.com/netlify/netlify-cms/issues/325#issuecomment-354514547.

**Comment by zionis137** [comment]
I tried the conversion-to-relative-path approach for nested values... and it does not work at all. The first level is transformed to a file, but the deeper levels are not.

```
fields{
   abs2rel{
    // Nested example
     gallery{
         image {
           childImageSharp {
              // This fails
           }
        }
    }

     // First level
     Titleimage{
        childImageSharp {
            // This works
         }
      }
  }
```

@KyleAMathews is this my fault or is it simply not possible? Currently I am using one `createNodeField` and use as value an `object`.

**Comment by aaronaustin** [comment]
I still can't seem to get any node to transform to a file, even at the first level.  I'm getting the path, but not a file.  Here's what I did in gatsby-node: 

`exports.onCreateNode = ({
  node,
  getNode,
  loadNodeContent,
  boundActionCreators,
}) => {
  const { frontmatter } = node
  if (frontmatter) {
    const { image } = frontmatter
    if (image) {
      if (image.indexOf('/img') === 0) {
        const { createNodeField } = boundActionCreators;
        const localFile = path.relative(
          path.dirname(node.fileAbsolutePath),
          path.join(__dirname, '/static/', image)
        )

        createNodeField({
          node,
          name: 'localFile',
          value: localFile,
        })
      }
    }
  }
}`

When I query, I get the error that this node is a string. @zionis137 Is this what you were doing to get the first level to work?

**Comment by zionis137** [comment]
Yes, this is basically what I was doing. 

plugin-code: https://github.com/zionis137/abs2rel
demo: https://github.com/zionis137/demoAbsoluteFilePath

Currently the demo works for all first-level stuff, independent of the name. 
Nested graphQL queries should look like [this](https://github.com/zionis137/demoAbsoluteFilePath/blob/master/src/templates/blog-post.js#L76)

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
