### ISSUE TITLE
Ignoring *.swp file types when using `gatsby develop`

### ISSUE THREAD

**Issue by tribou** [gatsbyjs/gatsby#333]
I wasn't sure where I'm supposed to configure ignoring file types such as `*.swp` produced by vim when using `gatsby develop`.  Currently, it reloads every time I switch between viewing different files since vim produces a `.swp` file for the current buffer.  Not a big issue, but it would be nice to ignore.  It might be good to go ahead and add that as default along with a `*.swp` entry to the default `.gitignore`.

**Comment by KyleAMathews** [comment]
Webpack is what's responsible for watching files so I would research there. I'm not entirely sure how to help though as I use Vim and don't have any troubles. One easy solution would be to move saving your swp files to a different directory http://stackoverflow.com/questions/1636297/how-to-change-the-folder-path-for-swp-files-in-vim

**Comment by ptolemybarnes** [comment]
I'm having a similar issue with it serving up test files, which I have co-located with components. I guess the solution is to just move test files to a top-level test folder, but it would be nice if Gatsby supported this popular convention.
