### ISSUE TITLE
"gatsby-source-contentful" threw an error while running the setFieldsOnGraphQLNodeType lifecycle:

### ISSUE THREAD

**Issue by Webdev-DavidM** [gatsbyjs/gatsby#33303]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I am trying to build a gatsby app which uses contentful, it works locally but when I try and build it on gatsby cloud I get the error

https://github.com/Webdev-DavidM/honestly-burger

### Reproduction Link

https://github.com/Webdev-DavidM/honestly-burger

### Steps to Reproduce

Running a build on gatsby cloud and I get the build error

"gatsby-source-contentful" threw an error while running the setFieldsOnGraphQLNodeType lifecycle:

Cannot find module gatsby-plugin-image/graphql-utils
Require stack:
- /usr/src/app/www/node_modules/gatsby-source-contentful/extend-node-type.js
- /usr/src/app/www/node_modules/gatsby-source-contentful/gatsby-node.js
- /usr/src/app/www/node_modules/gatsby/dist/bootstrap/load-plugins/validate.js
- /usr/src/app/www/node_modules/gatsby/dist/bootstrap/load-plugins/load.js
- /usr/src/app/www/node_modules/gatsby/dist/bootstrap/load-plugins/index.js
- /usr/src/app/www/node_modules/gatsby/dist/bootstrap/load-config-and-plugins.js
- /usr/src/app/www/node_modules/gatsby/dist/services/initialize.js
- /usr/src/app/www/node_modules/gatsby/dist/services/index.js
- /usr/src/app/www/node_modules/gatsby/dist/utils/worker/child/queries.js
- /usr/src/app/www/node_modules/gatsby/dist/utils/worker/child/index.js
- /usr/src/app/www/node_modules/gatsby-worker/dist/index.js
- /usr/src/app/www/node_modules/gatsby/dist/utils/worker/messaging.js
- /usr/src/app/www/node_modules/gatsby/dist/utils/jobs/worker-messaging.js
- /usr/src/app/www/node_modules/gatsby/dist/redux/actions/public.js
- /usr/src/app/www/node_modules/gatsby/dist/redux/actions/index.js
- /usr/src/app/www/node_modules/gatsby/dist/utils/webpack.config.js
- /root/.nvm/versions/node/v12.22.6/lib/node_modules/@gatsby-cloud-pkg/gatsby-inc-build-cli/dist/index.js
- /root/.nvm/versions/node/v12.22.6/lib/node_modules/@gatsby-cloud-pkg/gatsby-inc-build-cli/bin/cli.js

For more details see https://gatsby.dev/issue-how-to

### Expected Result

build the site

### Actual Result

build fail

### Environment

```shell
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5675R CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.0 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 93.0.4577.82
    Firefox: 87.0
    Safari: 14.1.2
  npmPackages:
    gatsby: ^3.13.1 => 3.14.0
    gatsby-image: ^3.11.0 => 3.11.0
    gatsby-plugin-gatsby-cloud: ^3.2.0 => 3.2.0
    gatsby-plugin-sass: ^4.14.0 => 4.14.0
    gatsby-source-contentful: ^5.14.0 => 5.14.0
  npmGlobalPackages:
    gatsby: 3.13.0
```

### Config Flags

no

**Comment by LekoArts** [comment]
Hi!

If you want to use image transformation with Contentful you'll need to install and use `gatsby-plugin-image`. Please remove `gatsby-image` and use `gatsby-plugin-image` instead and see if it works :)
