### ISSUE TITLE
Gatsby 4 Homepage has a horizontal scroll

### ISSUE THREAD

**Issue by igorradovanov** [gatsbyjs/gatsby#33315]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

The homepage of a new Gatsby 4 (https://www.gatsbyjs.com/gatsby-4/) has a horizontal scroll which does not look appealing. This issue can be replicated on Windows using both Chrome, Firefox, and Edge:

![image](https://user-images.githubusercontent.com/20539903/134778920-4acf890f-7745-4db2-8782-c6a9bab272cf.png)

### Steps to Resolve this Issue

1.  Set overflow-x: hidden; on this div element (currently called _css-19zfpgs_ as a class name on the live build).

![image](https://user-images.githubusercontent.com/20539903/134778979-32c4c316-bef3-4b86-bd67-c4208378dc6b.png)

**Comment by Utkarsh1504** [comment]
I would like to work on this issue.
Please assign me

**Comment by igorradovanov** [comment]
I am unable to assign you to the ticket, only owners of the repo can do that. However, the triage is still in progress so you'll need to wait a bit. Thank you for your interest!

**Comment by graysonhicks** [comment]
@igorradovanov I was unable to reproduce on Mac Chrome/Safari.  Can you confirm if this is still an issue?

**Comment by igorradovanov** [comment]
@graysonhicks Yes, still visible on Windows 10 with the latest Chrome and Firefox versions:

![image](https://user-images.githubusercontent.com/20539903/135758164-bbad23d9-0f99-440b-abca-cb2709332d21.png)

**Comment by LekoArts** [comment]
Hi, thanks for the issue! The issue tracker is for Gatsby as a OSS product and we don't track issues about the homepage here. I've filed an internal ticket for this though. In the future you can reach our support here: https://www.gatsbyjs.com/support/

**Comment by fk** [comment]
Thank you, @igorradovanov and @Utkarsh1504!

**Comment by shdq** [comment]
@LekoArts I have the same issue with my custom layout after upgrading gatsby to v4
