### ISSUE TITLE
Images not visible on initial page load with gatsby-plugin-image

### ISSUE THREAD

**Issue by ile** [gatsbyjs/gatsby#33321]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Images are not visible (did not check how) on initial page load when using `gatsby-plugin-image` and `layout: FULL_WIDTH` or `layout: CONSTRAINED`.

Images work if `layout: FIXED` is used. Also they work with `gatsby-image`. Also images work when rendered "with javascript" i.e. the page is rendered by clicking a link. Also, the images work when running the site in development mode, but not in build mode.

The latest Gatsby 3 is used, couldn't check with gatsby@next because the other plugins were not compatible with it. There are a few plugins, most notably `gatsby-source-graphql`.

The images are coming through `gatsby-source-graphql` plugin and a web app (headless CMS or graphql server). 

Links: 
- Site demo: https://festive-shaw-a1257b.netlify.app/
- Repo: https://github.com/ile/gatsby-aamu-starter-bug2 .... Relevant lines:
   - https://github.com/ile/gatsby-aamu-starter-bug2/blob/main/src/pages/index.js#L57
   - https://github.com/ile/gatsby-aamu-starter-bug2/blob/main/src/pages/index.js#L71
   - https://github.com/ile/gatsby-aamu-starter-bug2/blob/main/src/templates/blog-post.js#L61

You can test the site yourself if you want, there is an API key already present in `.env` file.

This looks like a bug to me but I'm not 100% sure. 

If you want a more minimal reproduction, I could try to do it. Thanks.

### Reproduction Link

https://festive-shaw-a1257b.netlify.app/

### Steps to Reproduce

1. Clone the repo
2. npm install
3. npm run build
...

### Expected Result

Images should be visible.

### Actual Result

Images are not visible.

### Environment

```shell
System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 14.17.4 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Firefox: 92.0, Brave
  npmPackages:
    gatsby: ^3.11.0 => 3.14.0
    gatsby-plugin-image: ^1.14.0 => 1.14.0
    gatsby-plugin-react-helmet: ^4.11.0 => 4.14.0
    gatsby-plugin-sharp: ^3.11.0 => 3.14.0
    gatsby-source-filesystem: ^3.11.0 => 3.14.0
    gatsby-source-graphql: ^3.11.0 => 3.14.0
    gatsby-transformer-sharp: ^3.11.0 => 3.14.0
  npmGlobalPackages:
    gatsby: 3.14.0
```

**Comment by graysonhicks** [comment]
Hi @ile thanks for the report?  Can you change (or add) the minimal reproduction link with the images _not_ working?  The current one linked is using `fixed`.  Thanks!

**Comment by graysonhicks** [comment]
Seems to be same issue described here https://github.com/gatsbyjs/gatsby/issues/30584

**Comment by eriklofblad** [comment]
I'm having the same issue. For me it doesn't work in Chrome or Firefox on Windows 10 but does work in both Chrome and Safari on iOS. In #30584 it didn't load the image when following a gatsby-link but did work when refreshing. For me and @ile the issue is the oposite (works with link but not when refreshing). Here's a [link](https://nordictraumarad.com/courses) to my site where the issue is present.

**Comment by ile** [comment]
Oh, well, that seemed to help, adding it to gatsby-config.js. Why didn't I think of it earlier?

> it'll seem to work mostly without it added

True.

Thanks!

**Comment by eriklofblad** [comment]
Thanks! That fixed it for me as well. I totally missed that when migrating my project from v2 to v3. A bit confusing that it works to 95% without adding it to the config. Is it possible to add a helpful warning in the console if it's not added to the config?
