### ISSUE TITLE
Development proxy doesn't return response body for 400 (4xx) status code

### ISSUE THREAD

**Issue by dangkyokhoang** [gatsbyjs/gatsby#33333]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

This happens after upgrading to Gatsby 3.14.0 which depends on `got` 11.8.2.

The `error` event no longer has response as the third parameter. It's now a property of the error object.
https://github.com/gatsbyjs/gatsby/blob/5196e40ef38660b6d8d621deb87fa719f124f1a4/packages/gatsby/src/utils/start-server.ts#L505
The `error.response` has `.body` and `.rawBody`, which possibly means that response body has already been consumed so piping just doesn't work as well. The fix is to `res.end(response.rawBody)` on error.
https://github.com/gatsbyjs/gatsby/blob/5196e40ef38660b6d8d621deb87fa719f124f1a4/packages/gatsby/src/utils/start-server.ts#L516

### Reproduction Link

https://codesandbox.io/s/infallible-phoebe-69w1t?file=/src/pages/index.js

### Steps to Reproduce

1. Set `proxy` in `gatsby-config.js`
```
proxy: [
  {
    prefix: "/v3",
    url: "https://run.mocky.io"
  }
]
```
2. `yarn develop`
3. Try fetching this `https://run.mocky.io/v3/99fc1661-4a34-4334-a123-ae9c02b33db4` which has 400 status code and `{"error":1}` response body.

### Expected Result

Should receive 400 {"error":1}

### Actual Result

Received 500 Internal Server Error

### Environment

```shell
System:
    OS: Linux 5.4 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 14.17.6 -
/tmp/yarn--1632937225269-0.21021899177501946/node
    Yarn: 1.22.11 -
/tmp/yarn--1632937225269-0.21021899177501946/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    gatsby: ^3.14.0 => 3.14.0
    gatsby-plugin-image: ^1.14.0 => 1.14.0
    gatsby-plugin-manifest: ^3.14.0 => 3.14.0
    gatsby-plugin-offline: ^4.14.0 => 4.14.0
    gatsby-plugin-react-helmet: ^4.14.0 => 4.14.0
    gatsby-plugin-sharp: ^3.14.0 => 3.14.0
    gatsby-source-filesystem: ^3.14.0 => 3.14.0
    gatsby-transformer-sharp: ^3.14.0 => 3.14.0
```

**Comment by carlos-algms** [comment]
I'm having something similar here.

One of my APIs returns multiple status codes depending on the business logic validation, and everything is being converted to `500` regardless of what is being returned by the server.

**Comment by dangkyokhoang** [comment]
Gatsby previously depends on `got` v8. After upgrading to `got` 11, the error handler in `start-server.js` doesn't work as expected because of this https://github.com/sindresorhus/got/issues/1898.

I'm currently using this post-install script as a temporary fix.

``` js
const { readFile, writeFile } = require('fs/promises')

// temporary fix for start-server.js
{
  const file = `${ __dirname }/../node_modules/gatsby/dist/utils/start-server.js`
  
  readFile(file, 'utf-8').then(content => writeFile(
    file,
    content
      .replace('if (response) {', 'if (response = err.response) {')
      .replace(
        'res.writeHead(response.statusCode || 400, response.headers);',
        `res.writeHead(response.statusCode || 400, response.headers); res.end(response.rawBody);`,
      ),
  ))
}
```

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
