### ISSUE TITLE
docs : link break,  showing undefined link at  "Edit this page on GitHub"

### ISSUE THREAD

**Issue by rahul3v** [gatsbyjs/gatsby#33400]
### Preliminary Checks
- [x] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [x] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

open this link https://www.gatsbyjs.com/docs/reference/config-files/gatsby-node/ and 
**go to "Edit this page on GitHub"** on the page

it will show https://github.com/gatsbyjs/gatsby/blob/master/undefined

--------------------------------------------------------------------------------

well I am not able to figure out, which file compiles 'doc' directory,

**Comment by LekoArts** [comment]
Hi!

This is something created from a source file and the logic is handled by us in our private gatsbyjs.com repository. I'll file an internal ticket to look into this. Thanks for the issue!
