### ISSUE TITLE
gatsby-source-shopify failing local build but not Gatsby Cloud

### ISSUE THREAD

**Issue by jarodpeachey** [gatsbyjs/gatsby#33441]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

The build succeeds on Gatsby cloud, but not locally. I get an error from Shopify: `Received error 404 from Shopify: {"errors":"Not Found"}`

### Reproduction Link

https://github.com/jarodpeachey/transcendental-dreamer

### Steps to Reproduce

1. Run NPM install
2. Run NPM start
3. Build fails
...

### Expected Result

I expect the build to succeed.

### Actual Result

The build fails with the error `Received error 404 from Shopify: {"errors":"Not Found"}`

### Environment

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 15.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.4 - /c/Users/Able Family Life/AppData/Local/Programs/Python/Python37-32/python
  Browsers:
    Edge: 44.19041.1023.0
  npmPackages:
    gatsby: ^3.4.1 => 3.14.1
    gatsby-plugin-gatsby-cloud: ^2.4.1 => 2.11.0
    gatsby-plugin-google-analytics: ^3.4.0 => 3.14.0
    gatsby-plugin-image: ^1.4.0 => 1.14.0
    gatsby-plugin-no-javascript: ^2.0.5 => 2.0.5
    gatsby-plugin-no-javascript-utils: ^0.7.2 => 0.7.2
    gatsby-plugin-purgecss: ^6.0.2 => 6.0.2
    gatsby-plugin-react-helmet: ^4.14.0 => 4.14.0
    gatsby-plugin-robots-txt: ^1.6.10 => 1.6.10
    gatsby-plugin-sass: ^4.14.0 => 4.14.0
    gatsby-plugin-sharp: ^3.14.0 => 3.14.0
    gatsby-plugin-sitemap: ^4.10.0 => 4.10.0
    gatsby-plugin-split-css: ^2.0.0 => 2.0.0
    gatsby-plugin-zopfli: ^2.0.0 => 2.0.0
    gatsby-source-filesystem: ^3.14.0 => 3.14.0
    gatsby-source-shopify: ^5.0.1 => 5.6.0
    gatsby-transformer-sharp: ^3.14.0 => 3.14.0
```

### Config Flags

FAST_DEV: true,

**Comment by graysonhicks** [comment]
What step in the build process does that happen?  If you log everywhere you are using the Shopify store URL, does it log correctly?
