### ISSUE TITLE
[gatsby-transformer-json]: Server stops running if JSON filename is camel case

### ISSUE THREAD

**Issue by peduarte** [gatsbyjs/gatsby#3345]
Hello,

I'm using `gatsby-transformer-json` to be able to query some data via GraphQL. I noticed that when I name my data file `withCamelCase` Gatsby's development server stops running and refuses to re-start.

The error shown is:
```
Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "0" does not.
```

Is this expected?

Thanks

**Comment by KyleAMathews** [comment]
It's not!

Could you look into making a fix? Would love a PR with a fix and new test. Or a sample site you create on GitHub that reproduces the issue.

**Comment by peduarte** [comment]
Sure, I’ll take a look 😊

**Comment by peduarte** [comment]
I created a new repo to replicate this issue but I was unable to do so 🤔 

I'm now wondering if the error was coming from somewhere else? Perhaps my GraphQL query was wrong? 

Very strange! 

In any case, I'll keep an eye out for this and will re-open if it happens again or if I'm able to reproduce it.

Thanks
