### ISSUE TITLE
Got ` RangeError: Invalid string length`

### ISSUE THREAD

**Issue by arnondora** [gatsbyjs/gatsby#3347]
I got this error when I run `gatsby develop` and `gatsby build`. I tried to copy my markdown files one by one and see build status for each markdown. It turned almost 20 files are the causes of this error. So I duplicated the project, remove all of the markdowns, copy all of the error markdowns into a duplicated project and run `yarn develop`, it compiled successfully. So I copy the error markdowns back to the original project and run `yarn develop`, I got this error again.

Any solution to this problem?

```
error UNHANDLED EXCEPTION


  RangeError: Invalid string length
  
  - Array.join
  
  - SourceListMap.js:76 SourceListMap.toStringWithSourceMap
    [arnondoraBlog]/[source-list-map]/lib/SourceListMap.js:76:5
  
  - SourceAndMapMixin.js:19 ConcatSource.proto.sourceAndMap
    [arnondoraBlog]/[webpack]/[webpack-core]/lib/SourceAndMapMixin.js:19:33
  
  - CachedSource.js:34 CachedSource.sourceAndMap
    [arnondoraBlog]/[webpack]/[webpack-core]/lib/CachedSource.js:34:28
  
  - SourceMapDevToolPlugin.js:55 Compilation.<anonymous>
    [arnondoraBlog]/[webpack]/lib/SourceMapDevToolPlugin.js:55:32
  
  - Array.map
  
  - SourceMapDevToolPlugin.js:43 Compilation.<anonymous>
    [arnondoraBlog]/[webpack]/lib/SourceMapDevToolPlugin.js:43:84
  
  - Array.forEach
  
  - SourceMapDevToolPlugin.js:42 Compilation.<anonymous>
    [arnondoraBlog]/[webpack]/lib/SourceMapDevToolPlugin.js:42:11
  
  - Tapable.js:26 Compilation.applyPlugins
    [arnondoraBlog]/[tapable]/lib/Tapable.js:26:37
  
  - Compilation.js:571 Compilation.<anonymous>
    [arnondoraBlog]/[webpack]/lib/Compilation.js:571:10
  
  - Tapable.js:60 Compilation.applyPluginsAsync
    [arnondoraBlog]/[tapable]/lib/Tapable.js:60:69
  
  - Compilation.js:567 Compilation.<anonymous>
    [arnondoraBlog]/[webpack]/lib/Compilation.js:567:9
  
  - Tapable.js:60 Compilation.applyPluginsAsync
    [arnondoraBlog]/[tapable]/lib/Tapable.js:60:69
  
  - Compilation.js:563 Compilation.<anonymous>
    [arnondoraBlog]/[webpack]/lib/Compilation.js:563:8
  
  - Tapable.js:60 Compilation.applyPluginsAsync
    [arnondoraBlog]/[tapable]/lib/Tapable.js:60:69
```

Gatsby version: 1.9.119
Node.js version: v6.11.4
Operating System: macOS 10.13.2

**Comment by KyleAMathews** [comment]
Is your site open source or could you create a small site which reproduces this problem? It's a bit hard to tell what's happening from your description.

**Comment by arnondora** [comment]
Yep It's open source. https://github.com/arnondora/arnondoraBlog

**Comment by arnondora** [comment]
I have tried to checkout to the previous commit, it can run `yarn develop` but it got the same error when run `yarn build`. I trying to reproduce the error by checking the error markdown.

**Comment by arnondora** [comment]
Finally, I solve it!! I just removed `gatsby-paginate` and implemented the pagination by myself. The problem still occurs. So, I ran `gatsby develop` for several times. The error is gone. I still don't know why it happened and how to reproduce this error. I am not quite sure the source of the problem, it may comes from `gatsby-paginate` or a cache.

**Comment by arnondora** [comment]
Finally, I solve it!! I just removed `gatsby-paginate` and implemented the pagination by myself. The problem still occurs. So, I ran `gatsby develop` for several times. The error is gone. I still don't know why it happened and how to reproduce this error. I am not quite sure the source of the problem, it may comes from `gatsby-paginate` or a cache.
