### ISSUE TITLE
Unhandled Runtime Error - Error in function useStaticQuery in ./.cache/gatsby-browser-entry.js:77

### ISSUE THREAD

**Issue by JHunter09** [gatsbyjs/gatsby#33481]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

No matter what I do, I simply cannot get useStaticQuery to work. I've tried putting it in different components, tried changing the name of the components to both start with a Capital letter and with a lowercase error, i've tried deleting the node modules folder and reinstalling, as well as using `gatsby clean`. Nothing seems to be working.

### Reproduction Link

https://github.com/iamshaunjp/gatsby-tutorial/blob/lesson-10/src/components/Navbar.js

### Steps to Reproduce

1. Implement useStaticQuery in any component

### Expected Result

Have the query execute successfully, not prompt me with an error, and allow me to retrieve the contents of said query.

### Actual Result

![image](https://user-images.githubusercontent.com/79439337/136690663-3a15e5a9-d28f-49be-a85f-d4b25c09a38c.png)

### Environment

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor             
  Binaries:
    Node: 14.17.0 - D:\Apps-Utils\nodejs\node.EXE
    Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.0.0 - D:\Apps-Utils\nodejs\npm.CMD
  Languages:
    Python: 3.9.5
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (94.0.992.38)
  npmPackages:
    gatsby: ^3.13.1 => 3.14.2 
    gatsby-link: ^3.14.0 => 3.14.0 
    gatsby-react-router-scroll: ^4.14.0 => 4.14.0 
  npmGlobalPackages:
    gatsby-cli: 3.14.1
```

**Comment by krichey15** [comment]
Getting the same error 

using Gatsby 3.4.1

**Comment by Tarunvarma9** [comment]
![Screenshot 2021-10-11 122149](https://user-images.githubusercontent.com/68417534/136745236-85f1a8dc-e0fd-4c48-a817-90938881ddd3.jpg)

I got the same error again.

**Comment by enkiBrant** [comment]
Same problem... no plugins outdated, clean cache. No error into the terminal. query look's good...

Gatsby 3.14.2

Thank's

**Comment by dwicke** [comment]
Same problem encountered while following: https://www.gatsbyjs.com/docs/tutorial/part-4/ 

Gatsby 3.14.3

Thanks!

**Comment by TheComeBackGuy** [comment]
Same issue with a Frontend Masters course. Since it won't go away I'm pretty much dead in the water now.

**Comment by krichey15** [comment]
@TheComeBackGuy @dwicke @enkiBrant not sure if it will help but at least for my use case I was able to convert to <StaticQuery>

**Comment by TheComeBackGuy** [comment]
> @TheComeBackGuy @dwicke @enkiBrant not sure if it will help but at least for my use case I was able to convert to

I actually just did a "clean" and that worked it out.

**Comment by LekoArts** [comment]
Hello!

Can you please update your reproduction to Gatsby 4 and explain the reproduction steps in more detail? Following your current instructions with Gatsby 4 I couldn't reproduce this. Thanks!

**Comment by JHunter09** [comment]
@LekoArts 
> Hello!
> 
> Can you please update your reproduction to Gatsby 4 and explain the reproduction steps in more detail? Following your current instructions with Gatsby 4 I couldn't reproduce this. Thanks!

Sure thing, I have updated gatsby:
```
System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
  Binaries:
    Node: 14.17.0 - D:\Apps-Utils\nodejs\node.EXE
    Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.3 - D:\Apps-Utils\nodejs\npm.CMD
  Languages:
    Python: 3.9.5
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.44)
  npmPackages:
    gatsby: ^4.1.2 => 4.1.2
    gatsby-link: ^3.14.0 => 3.14.0
    gatsby-react-router-scroll: ^4.14.0 => 4.14.0
    gatsby-source-strapi: ^0.0.0 => 0.0.0
  npmGlobalPackages:
    gatsby-cli: 4.1.1
```

This is the code I am attempting to use:
```js
import React from 'react'
import { graphql, Link, useStaticQuery } from 'gatsby'
import * as styles from '../styles/navbar.module.css'

export default function Navbar() {

  const data = useStaticQuery(graphql`
    query SiteInfo {
      site {
        siteMetadata {
          title
        }
      }
    }
  `)
  
  const {title} = data.site.siteMetadata

  return (
    <nav>
      
      <h1><img className={styles.logo} src="./logo.png" alt=""/>{title}</h1>
      <div className="links">
        <Link to="/">Home</Link>
        <Link to="/about">About</Link>
        <Link to="/projects">Projects</Link>
        <Link to="/news">News</Link>
        <Link to="/contact">Contact</Link>
      </div>
    </nav>
  )
}

```

This is my gatsby-config:
```js
/**
 * Configure your Gatsby site with this file.
 *
 * See: https://www.gatsbyjs.com/docs/gatsby-config/
 */

 module.exports = {
  siteMetadata: {
    title: `JH Industries`,
    siteUrl: `https://www.jhindustries.tk`,
    description: `Official site for JH Industries`,
    copyright: 'Copyright 2021 - JH Industries',
  },
}
```

And, as before, after running `gatsby develop` and navigating to `localhost:8000`, Instead of my site I am shown this:
![image](https://user-images.githubusercontent.com/79439337/141059548-f3c42191-5231-4008-a444-a7860a6d3a28.png)

**Comment by minhtri0795** [comment]
I have same problem and resolved, do you have rename any component recently, if have you need to double check where that component import to, sometime when you change name,import path for component not change automatic too.

**Comment by JHunter09** [comment]
@minhtri0795 I'm sorry, I'm not quite sure what you mean by your response.
