### ISSUE TITLE
--ca-file options seems to be broken with Node >= 12

### ISSUE THREAD

**Issue by vhiairrassary** [gatsbyjs/gatsby#33492]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

--ca-file is used to set `NODE_EXTRA_CA_CERTS` at 
https://github.com/gatsbyjs/gatsby/blob/934035d73bb14a08a0051acfd465325056187f4b/packages/gatsby/src/utils/get-ssl-cert.ts#L65-L67
But `NODE_EXTRA_CA_CERTS`
 must not be set at runtime: https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file (and it is loaded at startup since node 12, see https://github.com/nodejs/node/pull/23354).

We don't know exactly why we had this regression (node upgrade, Gatsby 3 upgrade, ?) but socket.io URL (such as `.../8001/socket.io/?EIO=4&transport=polling`) was presenting wrong certificate, while regular server is Ok. Manually setting `NODE_EXTRA_CA_CERTS` fix the issue.

### Reproduction Link

- 

### Steps to Reproduce

Set `--ca-file` option

### Expected Result

No certificate error on `socket.io/?EIO=4&transport=polling` URLs

### Actual Result

Certificate error on `socket.io/?EIO=4&transport=polling` URLs

### Environment

```shell
System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.6 - ~/.nodenv/versions/12.22.6/bin/node
    Yarn: 1.22.11 - ~/.nodenv/versions/12.22.6/bin/yarn
    npm: 6.14.15 - ~/.nodenv/versions/12.22.6/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 94.0.4606.71
    Safari: 15.0
  npmPackages:
    gatsby: ^3.14.2 => 3.14.2
    gatsby-image: ^3.11.0 => 3.11.0
    gatsby-plugin-datadog: ^1.1.1 => 1.1.1
    gatsby-plugin-material-ui: ^3.0.1 => 3.0.1
    gatsby-plugin-offline: ^4.14.0 => 4.14.0
    gatsby-plugin-react-helmet: ^4.14.0 => 4.14.0
    gatsby-plugin-sharp: ^3.14.1 => 3.14.1
    gatsby-plugin-styled-components: ^4.14.0 => 4.14.0
    gatsby-plugin-svgr: ^3.0.0-beta.0 => 3.0.0-beta.0
    gatsby-plugin-use-query-params: ^1.0.1 => 1.0.1
    gatsby-source-filesystem: ^3.14.0 => 3.14.0
    gatsby-transformer-sharp: ^3.14.0 => 3.14.0
```

**Comment by LekoArts** [comment]
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!
