### ISSUE TITLE
Is there anyway to disable progressive loading of the next page?

### ISSUE THREAD

**Issue by reywright** [gatsbyjs/gatsby#3350]
I like gatsby very much as a concept... however I need to disable the progressive loading feature as I'm on a product that has some stringent requirements for ads (in that they must render on initial page reload). Is there a way to make this happen?

**Comment by KyleAMathews** [comment]
Prefetching wouldn't hurt as the next full page reload would be much faster as resources would be cached.

Also prefetching is triggered by using gatsby-link so if you use normal a components then there'll be no prefetching.

**Comment by reywright** [comment]
Ah. You're right! That was pretty easy. Just turned

<Link to="/">Homepage</Link>

into

<a href="/">Homepage</a>

I'll close this. Thanks for the help!
