### ISSUE TITLE
Add default form plugin for easy plugin to Gatsby

### ISSUE THREAD

**Issue by calcsam** [gatsbyjs/gatsby#3351]
There are two form use-cases right now in Gatsby that are very common for personal and company websites and so should really have some sort of official support -- email collection forms and general form contacts.

The main thing would be providing sensible defaults for various use cases, that can be dropped into various pages and customized with a few props. Something like a gatsby-collection-form component. 

Right now, existing React form libraries (primarily react-final-form and formik) tend towards infinite customizability with few defaults. This is well suited for business workflow apps with dedicated teams, project managers and strong opinions on UI & validation rules. Works less well with websites where people will want to drop in a ready-made email collection component that fits one of several use cases:

Here are some thoughts about what we could build and officially support to fill this need:

### Sensible defaults...

Default forms that fit the four most common use cases:

#### Email collection:
* pop-up-block-when-reaching-bottom-of-page (eg https://codingvc.com/becoming-your-future-self/)
* inline-block-at-bottom-of-post (eg what @benjaminhoffman added to gatsbyjs.org: https://github.com/gatsbyjs/gatsby/pull/3333)
* slim-version-for-use-in-header-or-footer (eg the default mailchimp embedded form: 
![image](https://user-images.githubusercontent.com/4388699/34398746-8942c3f8-eb3e-11e7-933f-ec41500e7cd4.png)

#### Contact form:
* Eg http://gatsby-dimension.surge.sh/ (https://github.com/ChangoMan/gatsby-starter-dimension) but with more fields. 

Should involve [NewsletterProvider] and [SubmitURL] props. NewsletterProvider should probably default to Mailchimp.

### ...which allow customizations

Potential additional props:

1. leftTextComponent, border, buttonPosition: ['bottom', 'right']

2. baseColor, backgroundColor [optional]
Take hexes to allow styling that feels native to that webpage

3. displayFields, including primitives like Name, First Name, Last Name, Email, Company, etc out of the box with validations. possibly default to [Email]?

4. validationDisplay: ['displayErrorMessageBelow', 'redHighlight']

5. onSuccess: ['openNewPage', 'redirect', 'replaceComponent' (whole component? just the form parts)]
targetUrl [optional]
newComponent [optional]

6? Since the use here is websites rather than apps, we may want a fake HTML form to deal with bot signups, eg what Mailchimp provides above or what's mentioned here: https://stackoverflow.com/questions/15319942/preventing-bot-form-submission

Would love to hear people's thoughts on this!

**Comment by rdela** [comment]
Agree completely. Happy to help cc @benjaminhoffman …background https://github.com/gatsbyjs/gatsby/pull/3333#issuecomment-354009977

**Comment by jquense** [comment]
Hey there, thanks for the write up. I don't think it makes sense for gatsby to provide ui or form libraries out of the box. Partly because that's a bit out of scope for gatsby but also mainly because forms are the mostly unexpectedly complicated part of web de  in the general case.

There is a reason why popular form libraries tend towards customization, it's that practically there are an infinite amount of "simple use cases" that are not shared among apps. For instance I've built tons of forms and many  form inputs and libraries but rarely if ever built an email subscribe input or contact form. My point is not that those aren't valid or common use cases (they require) ! It's that overlap is a lot more limited between audiences than it feels like it should be. To that end "sensible defaults" in this area is kind of a lost cause (imo)

**Comment by benjaminhoffman** [comment]
@calcsam you're write up sounds awesome.  I'd like to start with an MVP though.  Thoughts?  Specifically, I'll bet a solid use case for Gatsby devs is an unstyled Mailchimp React component.  My reasoning is that Mailchimp is the most popular email marketing tool (esp for small/mid size companies) and that using MC on the client is not straight forward, as can be seen by my resent PR.

What's your thoughts on starting with a super bare-bones, unstyled MC React component for Gatsby? It other words, start with a basic component that works great with Gatsby, with the intent to build it out into a full-features React component for Gatsby.

**Comment by KyleAMathews** [comment]
A few thoughts:

* Gatsby's sweet spot is combining data processing w/ React website building. Coordinating pulling data from anywhere w/ data transformation pipelines controlled by the user via GraphQL queries.
* Gatsby doesn't care about *runtime* concerns i.e. once your site/app is running in the browser, do whatever you want (w/ a few caveats e.g. Gatsby wants you to use "pages" driven by React components and handles prefetching all statically defined page components/data).
* Any sort of form requires a backend. Gatsby generates decoupled apps w/ no backend. You can of course pair Gatsby with a dynamic backend but how you do that is up to you. Again this is a runtime concern that Gatsby doesn't have strong opinions on.
* There are a [number of services that handle receiving form data](https://github.com/agarrharr/awesome-static-website-services#forms) but any official form component would require us to build support for many different backends.
* 100% agree with @jquense's point that there's not very many truly common forms so anything we provide would meet a low % of needs.
* A good question when considering work is where can Gatsby — both the core package + those of us working on community tooling — provide the most leverage. I thought/think doing gatsby-image makes sense as a) it covers many/most image use cases and b) it's a living demo of how Gatsby enables you to create components that blend frontend code w/ backend data processing through the GraphQL interface that others can learn from and copy.

I think the best course here is to double-down on making it really easy for creators to share plugins/components with others in the community — https://github.com/gatsbyjs/gatsby/issues/3003

There's probably 100s of possible form components. I think we can best help people by a) documenting possible solutions (existing components + backends), b) creating the plugin library search, soliciting tutorials from people showing step-by-step how to build out common patterns.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
