### ISSUE TITLE
[gatsby-plugin-sass] Autoprefixer doesn't work

### ISSUE THREAD

**Issue by fpdrozd** [gatsbyjs/gatsby#33519]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

My project is using **gatsby-plugin-sass** and while I was testing it on Microsoft Edge I realized that css box-shadow does't work. When I opened the css bundle that Gatsby produced during the build process I realized that it didn't add all the necessary prefixes (-webkit-, -moz-, -ms-). In my **gatsby-config.js** file I just import the plugin without any configuration. I've also tried passing autoprefixer manually like so:
```
const autoprefixer = require('autoprefixer');
...
{
  resolve: "gatsby-plugin-sass",
  options: {
    postCssPlugins: [autoprefixer()]
  }
},
```
but it doesn't work either. I'm pretty confused because the documentation says that: 

> PostCSS is also included to handle some default optimizations like autoprefixing and common cross-browser flexbox bugs. Normally you don’t need to think about it...

Sorry if I'm getting something wrong but I couldn't find any good explanation for this thing.

### Reproduction Link

https://github.com/fpdrozd/gatsby-sass-autoprefixer-bug

### Steps to Reproduce

1. Run build on the linked reproduction project
2. Check the css bundle in the public folder

### Expected Result

The plugin should autoprefix the box-shadow property.

### Actual Result

It doesn't autoprefix the box-shadow property.

### Environment

```shell
System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.22.6 - /usr/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 6.14.15 - /usr/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 94.0.4606.54
    Firefox: 93.0
  npmPackages:
    gatsby: ^3.14.2 => 3.14.2 
    gatsby-plugin-sass: ^4.14.0 => 4.14.0 
  npmGlobalPackages:
    gatsby-cli: 3.5.0
```

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
