### ISSUE TITLE
My site is no longer using Gatsby

### ISSUE THREAD

**Issue by kentcdodds** [gatsbyjs/gatsby#33539]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

On [this marketing page](https://www.gatsbyjs.com/use-cases/content-media#technology-educator), my site is listed as using Gatsby, but I have [rewritten it to use Remix](https://kentcdodds.com/blog/how-i-built-a-modern-website-in-2021) so my site should be removed from this page.

### Steps to Resolve this Issue

1. Go to the part of your CMS that lists my site on [this page](https://www.gatsbyjs.com/use-cases/content-media#technology-educator)
2. Delete the reference to my site
3. Rebuild and deploy

**Comment by validity-check** [comment]
Or is this direct CMS work, that can only be done by maintainers?
