### ISSUE TITLE
Fetching remote files can fail with timeout on busy links

### ISSUE THREAD

**Issue by smroe** [gatsbyjs/gatsby#33549]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

The method gatsby-core-utils/fetch-remote-file.js/requestRemoteNode doesn't observe the updating state of a file that is being transferred. As a result, large/slow transfers that are succeeding fail before they complete causing problems with gatsby develop.

The timeout system in the above method doesn't get reset when the 'downloadProgress' event is triggered so when a large download is performed then it can be aborted before completion.

### Reproduction Link

https://www.no-where.com

### Steps to Reproduce

There is no site to reproduce this. The problem is specific to the user's internet connectivity.
1. Configure a CMS source with a large number of large downloads at a remote location
2. Using a limited bandwidth link, run gatsby develop

### Expected Result

gatsby develop builds the site after downloading the large number large files from the remote CMS

### Actual Result

The downloading of files is aborted as they take too long to download.

### Environment

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - C:\Users\Stuart\.windows-build-tools\python27\python.EXE
  Browsers:
    Chrome: 94.0.4606.81
    Edge: Spartan (44.19041.1266.0), Chromium (94.0.992.47)
  npmPackages:
    gatsby: ^3.11.1 => 3.14.2
    gatsby-plugin-gatsby-cloud: ^2.11.0 => 2.11.0
    gatsby-plugin-i18n: ^1.0.1 => 1.0.1
    gatsby-plugin-image: ^1.11.0 => 1.14.1
    gatsby-plugin-manifest: ^3.11.0 => 3.14.0
    gatsby-plugin-offline: ^4.11.0 => 4.14.0
    gatsby-plugin-react-helmet: ^4.11.0 => 4.14.0
    gatsby-plugin-sass: ^4.11.0 => 4.14.0
    gatsby-plugin-sharp: ^3.11.0 => 3.14.1
    gatsby-source-filesystem: ^3.11.0 => 3.14.0
    gatsby-source-graphql: ^3.11.0 => 3.14.0
    gatsby-transformer-sharp: ^3.11.0 => 3.14.0
```

**Comment by wardpeet** [comment]
That's a great idea! Mind adding tests and a PR for it?

**Comment by wardpeet** [comment]
Hey, We've added it ourselves and it's available on the @next channel. We'll backport it tomorrow to 4.1.0 release.
