### ISSUE TITLE
Gatsby build occasionally time out after "Caching JavaScript and CSS webpack compilation"

### ISSUE THREAD

**Issue by robinmetral** [gatsbyjs/gatsby#33557]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

About a month ago, [builds of my Gatsby site](https://github.com/robinmetral/gatsby-source-s3/actions/workflows/test.yml) started failing in GitHub Actions.

_For context, this  Gatsby site is a minimal example using my [`gatsby-source-s3`](https://github.com/robinmetral/gatsby-source-s3) plugin, that I use for testing the plugin end-to-end._

Here's from an [example of a failed build](https://github.com/robinmetral/gatsby-source-s3/runs/3912139392?check_suite_focus=true):

```sh
# ℹ️ omitted earlier logs, check out the link above to view the entire output
success run page queries - 13.660s - 1/1 0.07/s # 👈 this is after all nodes were sourced from S3, so I don't think the problem is with my plugin
success write out requires - 0.011s
success Building production JavaScript and CSS bundles - 9.577s
success Rewriting compilation hashes - 0.005s
success Writing page-data.json files to public directory - 0.017s - 1/1 57.50/s
success Caching JavaScript and CSS webpack compilation - 13.059s # 👈 this is where is hangs
Error: Timed out waiting for: http://localhost:9000 # 👈 this is the timeout from cypress. I've also increased it to see if it just took too long, but that was not the issue
```

At first, all builds were failing, and in the last week it seems that some of them are passing again while others are still failing.

I'm not sure what's happening here, as there are no helpful logs in the build output. A local `gatsby develop` works completely fine. The occasional passing build seem to rule out issues in my project or in other dependencies. I also [asked on discord](https://discord.com/channels/484383807575687178/537691356487876624/898110109966811156) but it didn't seem like anyone was having the same issue.

Any thoughts on:
- what the issue is here
- how I could debug this—I haven't found anything on [the docs](https://www.gatsbyjs.com/docs/reference/gatsby-cli/#build) about this

Thank you!

_A note about the reproduction link 👇 I am aware that the issue template says "Do not link to your actual project", but  in my case this example site is exactly a minimal example, since the only thing is does is pulling images from S3. I added the GH Action output there, [here's the link to the actual source](https://github.com/robinmetral/gatsby-source-s3/tree/main/examples/gatsby-starter-source-s3) although I doubt that it will be helpful._

### Reproduction Link

https://github.com/robinmetral/gatsby-source-s3/runs/3912139392?check_suite_focus=true

### Steps to Reproduce

1. Visit the link above to see the failing build output. I cannot reliably reproduce this locally, as mentioned in the summary.

### Expected Result

`gatsby build` should not time out

### Actual Result

`gatsby build` is flaky and unreliable, and regularly hangs in CI envs

### Environment

My local environment is not the issue here, this is failing on a clean GH Actions machine with:

- Ubuntu 20.04 LTS
- Latest Node 14
- Gatsby 3

**Comment by robmarshall** [comment]
> i.e. the bump from 3.13 to 3.14.
I can confirm the issue is introduced by gatsby-plugin-sharp 3.14. Bumping it to next does not solve the problem.

**Comment by lezan** [comment]
Hello, I am still experience the same issue of @sirichards with `gatsby-plugin-sharp` but also with `3.14.3`:  build freezed at `Caching JavaScript and CSS webpack compilation`.
Then I updated to `4.1.2` and now I get the same issue of @sirichards: stucked after `success run queries in workers - 160.247s - 111/111 0.69/s`.

**Comment by NickBarreto** [comment]
+1,  I am having the same issue as @lezan and @sirichards. Upgraded to Gatsby v4, and the first few builds had no issues.

However, today all of my builds are hanging at `success run queries in workers`, and then eventually timing out. 

Log snipped below from the first time it happened, and has persisted all day:

```
10:01:13 AM: success Building production JavaScript and CSS bundles - 80.112s
10:01:45 AM: success Building HTML renderer - 32.379s
10:01:45 AM: success Execute page configs - 0.092s
10:01:45 AM: success Caching Webpack compilations - 0.001s
10:03:37 AM: success run queries in workers - 111.803s - 1691/1691 15.12/s
10:27:08 AM: Build exceeded maximum allowed runtime
```

Tried a few various things to get things unstuck, turning on parallel workers, DSG in some pages, but doesn't seem to be having any effect. The next step in the process, 'merge worker state', never seems to happen/finish.

**Comment by lezan** [comment]
> 
> 
> +1, I am having the same issue as @lezan and @sirichards. Upgraded to Gatsby v4, and the first few builds had no issues.
> 
> However, today all of my builds are hanging at `success run queries in workers`, and then eventually timing out.
> 
> Log snipped below from the first time it happened, and has persisted all day:
> 
> ```
> 10:01:13 AM: success Building production JavaScript and CSS bundles - 80.112s
> 10:01:45 AM: success Building HTML renderer - 32.379s
> 10:01:45 AM: success Execute page configs - 0.092s
> 10:01:45 AM: success Caching Webpack compilations - 0.001s
> 10:03:37 AM: success run queries in workers - 111.803s - 1691/1691 15.12/s
> 10:27:08 AM: Build exceeded maximum allowed runtime
> ```
> 
> Tried a few various things to get things unstuck, turning on parallel workers, DSG in some pages, but doesn't seem to be having any effect. The next step in the process, 'merge worker state', never seems to happen/finish.

Maybe I digged my issue to `gatsby-plugin-sharp` config. Using `formats: ['auto', 'webp', 'avif']` with around 355 images (400MB) does not make finish my build process. With the default config for` gatsby-plugin-sharp` I can build it.

**Comment by NickBarreto** [comment]
Interesting! I just dig into my config files and I am set to `formats: ['auto', 'webp']`, which I believe is the default (at least, according to the [docs](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-plugin-image/#formats).  

I am, however, using `placeholder: 'blurred'`, which may be the expensive operation. I'm going to try and switch it back to 'dominantColor' and see if that helps.

Something must be going on that has degraded the performance of sharp though, because my builds were not taking as long as all this before I started running into this error. 

I've also managed to burn through so so many build minutes on Netlify trying to debug this as well, as I kept trying to see whether the adjustments I made were cutting back on the build time or not. So will be careful in testing this out, will try the builds locally and see if it takes less time before trying things out on Netlify.

Aside: DSG, incidentally, hasn't helped this because I guess Gatsby needs the images available in advance even if the page generation gets deferred, so those operations always happen on build anyway.

**Comment by lezan** [comment]
Hey @NickBarreto for my particular case `placeholder: 'blurred'` does not make any difference, neither `defaultQuality: 100` or `webpOptions: {quality: 100,},`. The only difference is with and without `avif`. With `formats: ['auto', 'webp', 'avif'],` I cannot finish my build. it is like stucked (after hours of running still not finish it), while with `formats: ['auto', 'webp']` I can build it without issue in around 340 seconds. Maybe something is changed with `sharp` and `avif` in the latest version?

**Comment by robinmetral** [comment]
Do you think it would be worth writing a new issue with all these findings? 👀 it looks like a different bug, and it might have more visibility when not at the bottom of a closed issue 😛

**Comment by LekoArts** [comment]
It is expected (and not a bug) that with `avif` it takes longer and more memory. This is why we do not enable it by default. See https://github.com/gatsbyjs/gatsby/issues/30256 or https://github.com/lovell/sharp/issues/2597

**Comment by NickBarreto** [comment]
Thanks for the info everyone. I think I will create another issue because I do think there has been a regression here. 

Admittedly my site has quite a few images (~1600), but under v3 and also in my first builds of v4 the time elapsed in the logs between `run queries in workers` and `merge worker state` was virtually instant, in milliseconds.

Now the process is hanging between those two steps, with the same number of images processed, and can take upwards of 20 minutes to move on to merging the worker state.

So I've gone from full, uncached builds in Gatsby v3 taking ~13 minutes to taking so long in v4 I hit the 30 minute limit on Netlify which causes my builds to fail.

**Comment by delasign** [comment]
This was resolved for me when I removed:
GATSBY_EXPERIMENTAL_QUERY_CONCURRENCY=1
GATSBY_CPU_COUNT=1
from my .env file.
