### ISSUE TITLE
Incorrect internal typescript for "graphql types"

### ISSUE THREAD

**Issue by tonyhallett** [gatsbyjs/gatsby#33589]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Given string type is parsed to DocumentNode https://github.com/gatsbyjs/gatsby/blob/a800d9d45ecf94ea58fa783be7dac464986e8fef/packages/gatsby/src/redux/actions/restricted.ts#L216
[ICreateTypes](https://github.com/gatsbyjs/gatsby/blob/a800d9d45ecf94ea58fa783be7dac464986e8fef/packages/gatsby/src/redux/types.ts#L644) payload is incorrect
```
  createTypes: (
    types:
      | string
      | GraphQLOutputType
      | GatsbyGraphQLType<any, any>
      | Array<string | GraphQLOutputType | GatsbyGraphQLType<any, any>>,
    plugin: IGatsbyPlugin,
    traceId?: string
  ): ICreateTypes => {
    return {
      type: `CREATE_TYPES`,
      plugin,
      traceId,
      payload: Array.isArray(types)
        ? types.map(parseTypeDef)
        : parseTypeDef(types),
    }
  },

```

```
export interface ICreateTypes {
  type: `CREATE_TYPES`
  plugin: IGatsbyPlugin
  traceId?: string
  payload: DocumentNode | Array<DocumentNode>
}

```
should be 
```
DocumentNode | GraphQLOutputType | GatsbyGraphQLType | Array<DocumentNode | GraphQLOutputType | GatsbyGraphQLType>
```

So given the [reducer] just adds the plugin (https://github.com/gatsbyjs/gatsby/blob/a800d9d45ecf94ea58fa783be7dac464986e8fef/packages/gatsby/src/redux/reducers/schema-customization.ts#L29) 

```
    case `CREATE_TYPES`: {
      let types: IGatsbyState["schemaCustomization"]["types"]
      if (Array.isArray(action.payload)) {
        types = [
          ...state.types,
          ...action.payload.map(typeOrTypeDef => {
            return {
              typeOrTypeDef,
              plugin: action.plugin,
            }
          }),
        ]
      } else {
        types = [
          ...state.types,
          { typeOrTypeDef: action.payload, plugin: action.plugin },
        ]
      }
      return {
        ...state,
        types,
      }
    }


```

the [gatsby state slice](https://github.com/gatsbyjs/gatsby/blob/a800d9d45ecf94ea58fa783be7dac464986e8fef/packages/gatsby/src/redux/types.ts#L320) is also incorrect.

```
  schemaCustomization: {
    //...
    types: Array<
      string | { typeOrTypeDef: DocumentNode; plugin: IGatsbyPlugin }
    >
  }

```

should be
```
schemaCustomization: {
    //...
    types: Array<
      { typeOrTypeDef: DocumentNode | GraphQLOutputType | GatsbyGraphQLType; plugin: IGatsbyPlugin }
    >
  }

```

I have removed the string type which is permitted by https://github.com/gatsbyjs/gatsby/blob/a800d9d45ecf94ea58fa783be7dac464986e8fef/packages/gatsby/src/schema/schema.js#L248.  Perhaps it should be there for backwards compatibility ?

### Reproduction Link

https://github.com/gatsbyjs/gatsby/blob/a800d9d45ecf94ea58fa783be7dac464986e8fef/packages/gatsby/src/redux/types.ts#L644

### Steps to Reproduce

1. Check the code path described above.

### Expected Result

The typescript is correct.

### Actual Result

The typescript is incorrect.

### Environment

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  Binaries:
    Node: 16.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.0 - C:\Program Files\nodejs\yarn.CMD
    npm: 7.21.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (94.0.992.50)
  npmGlobalPackages:
    gatsby-cli: 3.14.0
    gatsby-dev-cli: 3.14.0
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue.

I'll close this one as it's not related to public types but only our internal code. While having correct types everywhere would be nice fixing the internal ones is not our top priority as it normally yields small benefits compared to other things we (and contributors) can work on. If you find them while browsing the code, feel free to open a PR, but I wouldn't recommend hunting for them. Thanks!
