### ISSUE TITLE
Semantic UI Theming using Less

### ISSUE THREAD

**Issue by iwarner** [gatsbyjs/gatsby#3358]
## Description

I want to introduce theming to semantic UI and have gone down the path of using the less distro

Please refer to this Link http://neekey.net/2016/12/09/integrate-react-webpack-with-semantic-ui-and-theming/

### Environment

Gatsby version: latest
Node.js version: latest
Operating System: OSX High Siera

### File contents (if changed):

I added a gatsby-node file to try and wedge in the rewrite required for the theme file as described in the above link

```
exports.modifyWebpackConfig = ({config, stage}) => {
  switch (stage) {
    case 'develop':
      config.loader('less', {
        options: {
          paths: ['.', 'node_modules'],
          plugins: [
            new RewriteImportPlugin({
              paths: {
                '../../theme.config': 'semantic-ui/theme.config'
              }
            })
          ]
        }
      })
  }
}
```

### Actual result

The result is

    object.allowUnknown , "options" is not allowed

### Expected behavior

I want the file to be renamed - but do not know the correct syntax for the gatsby node and webpack configuration

**Comment by hprobotic** [comment]
Hi @iwarner, have you got that fixed yet?

**Comment by iwarner** [comment]
@hprobotic No fix as yet, still a major issue for me

I have tried so many combinations, docs on webpack 1 for this are few and far between.

> Module build failed: Cannot resolve 'file' or 'directory' ../../theme.config in /Users/ianwarner/Documents/r/rush-partners/public/fs-shell/node_modules/semantic-ui-less/definitions/elements

```
      config.loader(`less`, {
        test: /\.less$/,
        exclude: /node_modules/,
        loader: _combineLoaders([
          {
            loader: 'style'
          },
          {
            loader: 'css'
          },
          {
            loader: lessLoaderDev,
            query: [
              new _rewriteImportPlugin({
                paths: {
                  '../../theme.config': `${__dirname}/src/semantic-ui/theme.config`
                }
              })
            ]
          }
        ])
      })
```

```
      config.loader(`less`, {
        test: /\.(less|config)/,
        // loaders: [
        //   'style-loader',
        //   'css-loader',
        //   {
        loader: 'less',
        query: {
          lessOptions: {
            paths: [__dirname, 'node_modules'],
            lessPlugins: [
              new _rewriteImportPlugin({
                paths: {
                  '../../theme.config': `${__dirname}/src/semantic-ui/theme.config`
                }
              })
            ]
          }
        }
      })

```

**Comment by hprobotic** [comment]
The other solution is you can link current theme/config file to node_module by `postinstall` like this
`"postinstall": "ln -s ../../src/semantic-ui/theme.config node_modules/semantic-ui-less/theme.config"`
Btw, it's only work with less version 2.7.2

**Comment by iwarner** [comment]
Hiya I will give everything a shot at this point

It could be that my solutions above are limited due to package versions, with Gatsby so behind in Webpack its troublesome to configure

**Comment by iwarner** [comment]
I added the -f to be sure
ln -sf ../../src/semantic-ui/theme.config ./node_modules/semantic-ui-less/theme.config
