### ISSUE TITLE
Page is undefined in loader.js after running gatsby develop on Windows.

### ISSUE THREAD

**Issue by michal-damiecki** [gatsbyjs/gatsby#3359]
## Description

Hi,
I'm trying to follow docs getting started tutorial, but after `gatsby develop` browser shows some errors (screenshot below). I've read [Gatsby on Windows](https://www.gatsbyjs.org/docs/gatsby-on-windows/) and installed `windows-build-tools`. It might be some problem with pageFinderFactory but I'm not sure.

### Environment

Gatsby version: 1.9.145
Node.js version: 8.9.3
Operating System: Windows

### Screenshot:

![](https://image.ibb.co/emxDgb/localhost_8000.png)

**Comment by calcsam** [comment]
@michal-damiecki could you clarify where in the tutorial you encountered this?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
