### ISSUE TITLE
gatsby serve / build not generating typography.js

### ISSUE THREAD

**Issue by jonathan-chin** [gatsbyjs/gatsby#3360]
when using ```gatsby develop```, a style element gets inserted. I can see it by inspecting the site:

```<style id="typography.js"> ... </style>```

however, when I build or serve it, that style element never gets generated (again, verified by inspecting the source when visiting).

one of the major things the style does is set the font family. am I missing something?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
