### ISSUE TITLE
Error: "can't access property "images", e is undefined" using withArtDirection and getImage

### ISSUE THREAD

**Issue by Cecile-Lebleu** [gatsbyjs/gatsby#33636]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I'm trying to add an image to a website, where a different image is shown if the window is smaller than 800px wide.

Following [this guide](https://paulie.dev/posts/2021/04/gatsby-plugin-image-with-art-direction/) and the docs for [Gatsby Plugin Image](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-plugin-image/#withartdirection).

Here's what my Image component looks like:
```
import React from 'react'
import { graphql, useStaticQuery } from 'gatsby'
import { GatsbyImage, getImage, withArtDirection } from "gatsby-plugin-image"

const Image = () => {
	const data = useStaticQuery(graphql`
		query MyQuery {
			allFile(filter: {name: {regex: "/image-[0-9]/g"}}) {
				edges {
					node {
						name
						childImageSharp {
							gatsbyImageData(layout: FULL_WIDTH)
						}
					}
				}
			}
		}
		
	`)

	const images = withArtDirection(getImage(data.largeImage), [{
		media: "(max-width: 1024px)",
		image: getImage(data.smallImage),
	}])
	return <GatsbyImage image={images} />
}
export default Image
```

I get the following error:
![Screen Shot 2021-10-22 at 1 07 41 PM](https://user-images.githubusercontent.com/22694361/138510097-26ea94ca-5e75-4a62-95df-b1d54731617d.png)

Am I doing something wrong? 

### Reproduction Link

https://github.com/Cecile-Lebleu/gatsby-image-issue

### Steps to Reproduce

1. Clone repo linked above
2. Run `gatsby develop`

### Expected Result

An image is shown

### Actual Result

Unknown Runtime Error
can't access property "images", e is undefined

Console:

![Screen Shot 2021-10-22 at 1 11 30 PM](https://user-images.githubusercontent.com/22694361/138510454-7230ee77-7c7e-4110-9b8a-659301004ee2.png)

![Screen Shot 2021-10-22 at 1 10 33 PM](https://user-images.githubusercontent.com/22694361/138510356-744fc5bd-8ba1-4236-be3e-71cb6217e413.png)

### Environment

```shell
System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    npm: 7.15.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 94.0.4606.81
    Firefox: 89.0.2
    Safari: 15.0
  npmPackages:
    gatsby: ^4.0.0 => 4.0.0 
    gatsby-image: ^3.11.0 => 3.11.0 
    gatsby-plugin-image: ^2.0.0 => 2.0.0 
    gatsby-plugin-sharp: ^4.0.0 => 4.0.0 
    gatsby-transformer-sharp: ^4.0.0 => 4.0.0 
  npmGlobalPackages:
    gatsby-cli: 4.0.0
```

**Comment by JannikWempe** [comment]
Is there any solution to this? I have a very similar issue: 

![image](https://user-images.githubusercontent.com/7524745/141684619-4d0c006f-4649-4ea8-8d46-07b75bafb287.png)

![image](https://user-images.githubusercontent.com/7524745/141684675-9d0eeaeb-eb22-4382-a204-f3f3df61fc8f.png)
![image](https://user-images.githubusercontent.com/7524745/141684701-829dbd28-a536-4984-9e47-ad1b085b4b6f.png)

This is the code causing the issue:

```jsx
<GatsbyImage
  image={getImage(heroImage.image)}
  alt={""}
/>
```

And the image is definitely defined. It worked without issues before upgrading to v4.

![image](https://user-images.githubusercontent.com/7524745/141684741-d3e9f065-7b79-406f-b767-18abd0979c28.png)

**Comment by JannikWempe** [comment]
I was finally able to resolve the issue for me. It was due to a custom `babel.config.js` which looked like: 

```js
module.exports = (api) => {
  // workaround for https://github.com/cypress-io/cypress/issues/2945
  if (api.cache.using(() => process.env.CYPRESS_INTERNAL_ENV)) {
    return {};
  }
  return {
    plugins: [["@babel/plugin-proposal-private-methods", { loose: true }]],
    presets: [["babel-preset-gatsby"]],
  };
};
```

Getting rid of it and just using the default babel config resolved the issue in my case. BUT I am not exactly sure about the root cause and the reproduction repo does not use a custom babel config.
