### ISSUE TITLE
Gatsby 4 with IE11 is broken: using onClick-handlers throws a "EventTarget undefined"

### ISSUE THREAD

**Issue by jablonski** [gatsbyjs/gatsby#33663]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Using onClick-handlers with IE11 works fine with Gatsby 3.14.x, but did stop working with Gatsby 4.
Error message in the browser console: "EventTarget" is undefined.

### Reproduction Link

https://github.com/jablonski/gatsby-ie11-onclick-error

### Steps to Reproduce

1. npm run build
2. npm run serve
3. Open http://localhost:9000/ in IE11 and press the button.

### Expected Result

IE11 doesn't throw an error and the counter increases as expected.

### Actual Result

IE11 throws an error in the browser console: "EventTarget" is undefined

### Environment

```shell
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.12.0 - ~/.nvm/versions/node/v16.12.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.12.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Firefox: 93.0
    Safari: 15.0
  npmPackages:
    gatsby: 4.0.0 => 4.0.0
```

**Comment by wardpeet** [comment]
Thanks, this got fixed in the next channel, you can test it by installing `npm install gatsby@next`. We'll release it on Tuesday.
