### ISSUE TITLE
Some Question about deploying to VM

### ISSUE THREAD

**Issue by Quorafind** [gatsbyjs/gatsby#3367]
## Description

Hello.
Before, I wanted to deploy the files built from gatsbyjs to my own virtual machine. What should I do next? I have viewed the doc from your official site, but I can't find the solution for deploying to VM. Have you supported deploying files to VM directly?

### Environment

Gatsby version: v1.0.0
Node.js version: v9.3.0
Operating System: windows 10 pro and centos 7 in VM

### Expected behavior

Sorry, I just want to ask some question. And if you don't support deploy things to VM, I will wait for it.

**Comment by KyleAMathews** [comment]
We don't have deploy docs for this use case yet. You'll want to search for how to host a static site. Any tutorial for e.g. Jekyll would work the same for gatsby. Good luck! Would love a PR from you with documentation for this once you have things working.
