### ISSUE TITLE
Gatsby 4 + Tailwind with CSS Modules

### ISSUE THREAD

**Issue by stevensacks** [gatsbyjs/gatsby#33688]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Gatsby 4 has a bug with Tailwind and css modules. This did not happen in Gatsby 3.

If you write a custom class in your tailwind.css and then try to reference it in a *.modules.css file in a component, Gatsby 4 crashes during the build process.

You can reproduce it in the minimal test repo I have created.

Here's the error output:
```
⠇ Building development bundle
<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/Users/steven/Development/gatsby-tailwind-issue/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[9].oneOf[0].use[0]!/Users/steven/Development/gatsby-tailwind-issue/node_modules/gatsby-plugin-postcss/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[9].oneOf[0].use[1]!/Users/steven/Development/gatsby-tailwind-issue/src/pages/styles.module.css': No serializer registered for SyntaxError

 ERROR 

Module build failed (from ./node_modules/gatsby-plugin-postcss/node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(2:5) /Users/steven/Development/gatsby-tailwind-issue/src/pages/styles.module.css The `base-title` class does not exist. If `base-title` is a custom class, make sure it is defined within a `@layer` directive.

  1 | .title {
> 2 |     @apply base-title;
    |     ^
  3 | 
  4 |     text-shadow: 1px 1px 2px green;

  ModuleBuildError: Module build failed (from ./node_modules/gatsby-plugin-postcss/node_modules/postcss-loader/dist/cjs.js):
  SyntaxError
  (2:5) /Users/steven/Development/gatsby-tailwind-issue/src/pages/styles.module.css The `base-title` class does not exist. If `base-title` is a custom class, make sure it is defined within a `@layer` directive.
    1 | .title {
  > 2 |     @apply base-title;
      |     ^
    3 | 
    4 |     text-shadow: 1px 1px 2px green;
  
  - NormalModule.js:748 processResult
    [gatsby-tailwind-issue]/[webpack]/lib/NormalModule.js:748:19
  
  - NormalModule.js:850 
    [gatsby-tailwind-issue]/[webpack]/lib/NormalModule.js:850:5
  
  - LoaderRunner.js:399 
    [gatsby-tailwind-issue]/[loader-runner]/lib/LoaderRunner.js:399:11
  
  - LoaderRunner.js:251 
    [gatsby-tailwind-issue]/[loader-runner]/lib/LoaderRunner.js:251:18
  
  - LoaderRunner.js:124 context.callback
    [gatsby-tailwind-issue]/[loader-runner]/lib/LoaderRunner.js:124:13
  
  - index.js:102 Object.loader
    [gatsby-tailwind-issue]/[gatsby-plugin-postcss]/[postcss-loader]/dist/index.js:102:7
```

### Reproduction Link

https://github.com/sklawren/gatsby-tailwind-issue

### Steps to Reproduce

1. Write a custom class in tailwind.css
2. apply that custom class in a *.module.css file
3. run Gatsby 4

### Expected Result

That it compiles correctly

### Actual Result

Crashes Gatsby

### Environment

```shell
System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
  Languages:
    Python: 3.9.7 - /usr/local/opt/python3/libexec/bin/python
  Browsers:
    Chrome: 95.0.4638.54
    Firefox: 93.0
    Safari: 15.0
  npmPackages:
    gatsby: ^4.0.1 => 4.0.1 
    gatsby-cli: ^4.0.0 => 4.0.0 
    gatsby-plugin-postcss: ^5.0.0 => 5.0.0
```

### Config Flags

No flags

**Comment by stevensacks** [comment]
This issue does not occur with Gatsby 2 or 3, it does not occur with Storybook in the same project. It’s something with Gatsby 4 and PostCSS or CSS Modules.

**Comment by stevensacks** [comment]
Hi, it's been about a month so I'm checking in to see how this is going since I'm still blocked from upgrading to Gatsby 4.

**Comment by LekoArts** [comment]
Hi!

With Adam's comment (https://github.com/tailwindlabs/tailwindcss/issues/5989#issuecomment-1002297586) in mind and the given documentation here (https://tailwindcss.com/docs/functions-and-directives#using-apply-with-per-component-css) I'll close this. I have to agree, that we wouldn't want to make the changes that would enable this use case. I can't pinpoint the exact update we did that would have changed this behavior, probably a dependency update or a change in our webpack config -- anyway, I think the last paragraph in the docs is a good advice:

> Honestly though the best solution is to just not do weird stuff like this at all. Use Tailwind’s utilities directly in your markup the way they are intended to be used, and don’t abuse the `@apply` feature to do things like this and you will have a much better experience.
