### ISSUE TITLE
Scheme relative URLs are treated as relative paths

### ISSUE THREAD

**Issue by claudiopro** [gatsbyjs/gatsby#3370]
## Description

[Scheme relative URLs](https://url.spec.whatwg.org/#scheme-relative-url-string) are treated as relative paths, and intercepted by Gatsby's `gatsby-plugin-catch-links`, while they should just be followed as-is. The issue can be reproduced in React pages as well as in pages generated from markdown with `gatsby-transformer-remark`.

I'm providing a repro on https://ludicrous-sock.surge.sh for your convenience. The site was partially generated from markdown pages following [Gatsby.js Tutorial Part Four](https://www.gatsbyjs.org/tutorial/part-four/).

This is related to https://github.com/reasonml/reasonml.github.io/issues/253, where the `gh-pages` page https://reasonml.github.io/guide/what-and-why links to https://reasonml.github.io/reason-react/docs/en/installation.html from another repo in the same organization as `[ReasonReact](//reasonml.github.io/reason-react/docs/en/installation.html)`.

### Environment

Gatsby version: master
Node.js version: 9.3
Operating System: Mac OS X 10.11.6

### Actual result

Scheme relative links (`//ludicrous-sock.surge.sh/foo/bar`) are intercepted by Gatsby and considered relative, e.g. `https://ludicrous-sock.surge.sh//ludicrous-sock.surge.sh/foo/bar`

### Expected behavior

Links should be followed and not intercepted.

### Steps to reproduce

1\. Open https://ludicrous-sock.surge.sh
2\. Follow the instructions on screen 😄

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
