### ISSUE TITLE
Edit content from browser

### ISSUE THREAD

**Issue by rogovdm** [gatsbyjs/gatsby#3373]
## Description

Would it be super nice to be able to edit content (e.g. markdown files) while viewing them in browser?

## Possible implementation

This might be possible by creating a hook like `__content-edit` which would be responsible for updating data on disk.

**Comment by dotmagic** [comment]
I think it's beyond the scope of a static site generator?

**Comment by rogovdm** [comment]
@dotmagic It is a feature more for development mode. And might be very useful in various use cases.

**Comment by calcsam** [comment]
This is a cool feature present in a few CMSes (such as Sitecore) designed for that purpose.

To do this in Gatsby you would have to have to directly link the data sources pulled in by eg gatsby-transformer-remark to specific components in dev mode.

Not currently on the roadmap but it would be a super cool experience and happy to advise if you're interested in implementing @rogovdm

**Comment by dotmagic** [comment]
@rogovdm Btw, I'm using the Markdown preview plugins for Visual Code & Atom. With a large screen you can type and see the result in another pane. I found it much more comfortable to work.
