### ISSUE TITLE
Longer build - long query - after migrate to gatsby 4

### ISSUE THREAD

**Issue by Axel-KIRK** [gatsbyjs/gatsby#33735]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi, 
We have one project which is full mdx pages website.
Since we migrate on gatsby 4, the build become very long (+30min for initially 20min) and we have this kind of message : 

![image](https://user-images.githubusercontent.com/38718957/139426955-d2e30da6-4bc9-4c50-b92e-7c48ace0c4ad.png)

It's seem's that is related too the quantity of mdx, if I remove some mdx page the issue disappear 
Currently our build key number are: 
![image](https://user-images.githubusercontent.com/38718957/139427110-9fed3465-e44b-497a-aab4-68cfd93a7e41.png)

It's seems also related with image, we use gatsby-plugin-image / gatsby-plugin-sharp / gatbsy-transform-sharp
```
    "gatsby": "latest",
    "gatsby-plugin-algolia": "^0.22.2",
    "gatsby-plugin-image": "^2.0.0",
    "gatsby-plugin-layout": "^3.0.0",
    "gatsby-plugin-mdx": "latest",
    "gatsby-plugin-module-resolver": "^1.0.3",
    "gatsby-plugin-portal": "^1.0.55",
    "gatsby-plugin-react-helmet": "^5.0.0",
    "gatsby-plugin-react-svg": "^3.1.0",
    "gatsby-plugin-segment-js": "^3.7.0",
    "gatsby-plugin-sharp": "latest",
    "gatsby-plugin-sitemap": "^5.0.0",
    "gatsby-plugin-styled-components": "^5.0.0",
    "gatsby-remark-smartypants": "^4.9.0",
    "gatsby-source-filesystem": "^4.0.0",
    "gatsby-transformer-sharp": "latest",
```

I try to reproduce it with minimal config/code but no success until there.

I try to not update sharp plugins (remain in 3.1.4) , and it throw erreur : `Gatsby-plugin-sharp wasn't setup correctly in gatsby-config.js. Make sure you add it to the plugins array`. 

I try parallel query --> no change.

### Reproduction Link

.

### Steps to Reproduce

1.
2.
3.
...

### Expected Result

.

### Actual Result

.

### Environment

```shell
System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.10.0 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 7.24.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 95.0.4638.54
    Firefox: 93.0
    Safari: 14.1.2
  npmPackages:
    gatsby: latest => 4.0.2
    gatsby-plugin-algolia: ^0.22.2 => 0.22.2
    gatsby-plugin-image: ^2.0.0 => 2.0.0
    gatsby-plugin-layout: ^3.0.0 => 3.0.0
    gatsby-plugin-mdx: latest => 3.0.0
    gatsby-plugin-module-resolver: ^1.0.3 => 1.0.3
    gatsby-plugin-portal: ^1.0.55 => 1.0.65
    gatsby-plugin-react-helmet: ^5.0.0 => 5.0.0
    gatsby-plugin-react-svg: ^3.1.0 => 3.1.0
    gatsby-plugin-segment-js: ^3.7.0 => 3.7.0
    gatsby-plugin-sharp: latest => 4.0.1
    gatsby-plugin-sitemap: ^5.0.0 => 5.0.0
    gatsby-plugin-styled-components: ^5.0.0 => 5.0.0
    gatsby-remark-smartypants: ^4.9.0 => 4.11.0
    gatsby-source-filesystem: ^4.0.0 => 4.0.0
    gatsby-transformer-sharp: latest => 4.0.0
  npmGlobalPackages:
    gatsby-cli: 3.6.0
```

### Config Flags

    DEV_SSR: false,

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by Axel-KIRK** [comment]
I solve this issue by query first all images and then pass src to pageContext. 
I was querying gatsbyImage on component/template side
