### ISSUE TITLE
Gatsby v4: Typescript error "Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier"

### ISSUE THREAD

**Issue by nathsimpson** [gatsbyjs/gatsby#33747]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I'm updating an existing Gatsby project to Gatsby v4, and stumbled upon an issue when running typescript checking that I'm not sure what to do with...
```
➜  nathansimpson.design git:(gatsby-4) ✗ yarn types
yarn run v1.22.10
$ tsc --project tsconfig.json
node_modules/gatsby/index.d.ts:33:1 - error TS1046: Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.

33 class StaticQueryDocument {
   ~~~~~


Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Issue is found in the gatsby/index.d.ts file, since updating from Gatsby 3 to Gatsby 4.

- Gatsby version: 4.0.2
- Typescript version: 4.4.4

### Reproduction Link

https://github.com/nathsimpson/nathansimpson.design/pull/76

### Steps to Reproduce

1. Clone above repo and checkout `gatsby-4` branch
2. Run yarn to download dependencies
3. Run `yarn. types` to run typescript checks
...

### Expected Result

Typescript checks would pass

### Actual Result

Terminal output as above

### Environment

```shell
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 95.0.4638.54
    Firefox: 88.0.1
    Safari: 14.1.2
```

**Comment by nathsimpson** [comment]
Would really appreciate any help with this. Thank you 😄

**Comment by chandrakumarreddy** [comment]
facing same issue

**Comment by wkillerud** [comment]
Same issue using TypeScript 4.4.4 and Gatsby 4.0.2.

This diff in [gatsby/index.d.ts](https://github.com/gatsbyjs/gatsby/blob/ac60fbcd284a2cd8fba0ee282313afe644dfc512/packages/gatsby/index.d.ts#L33) fixes it for me:

```diff
-class StaticQueryDocument {
+export class StaticQueryDocument {
   /** Prevents structural type widening. */
   #kind: "StaticQueryDocument"
 

```

Not sure if it should be `export` or `declare`, but either should do the trick.

**Comment by nathsimpson** [comment]
Thanks all! 👏
