### ISSUE TITLE
Proposal: set up Algolia Docsearch

### ISSUE THREAD

**Issue by whmountains** [gatsbyjs/gatsby#3378]
Now that Gatsby is beginning to develop a larger corpus of documentation, we need a good search interface.  Seems like most large OSS projects including Bootstrap and React have gone with [Algolia DocSearch](https://community.algolia.com/docsearch/), and I'm personally a big fan of it's UX.

Any thoughts?

**Comment by KyleAMathews** [comment]
Would love help on this! https://github.com/gatsbyjs/gatsby/issues/3097
