### ISSUE TITLE
[gatsby-source-wordpress] Custom Taxonomy hard limit of 100

### ISSUE THREAD

**Issue by charles-langley** [gatsbyjs/gatsby#33794]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

We have a custom taxonomy type, created using the plugin "Custom Post Type UI". The taxonomy is non-hierarchal and is exposed to GraphQL as expected. We are able to query the taxonomy as expected.

The issue is, at present, we have 118 items assigned to this taxonomy, but no matter which limits we set, increase, or remove, this taxonomy is limited to 100.

We have attempted to increase this limit in both gatsby-config.js as well as adding a custom filter for the WP GraphQL plugin.

I'm not sure how to link a reproduction to this issue as it's to be in either the core gatsby-source-wordpress, or the WP GraphQL plugin and isn't related to any custom pages or templates.

### Reproduction Link

https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-wordpress

### Steps to Reproduce

1. Create a custom non-hierarchal taxonomy type in wordpress
2. Populate taxonomy with more than 100 items
3. Set type -> __all -> limit to 150 in gatsby-config.js
4. Ensure no other limits are set.
5. Ensure Custom Taxonomy is shown in GraphQL
6. execute gatsby develop

### Expected Result

success  gatsby-source-wordpress  WpMyCustomTaxonomy - 4.898s - fetched 118

### Actual Result

success  gatsby-source-wordpress  WpMyCustomTaxonomy - 4.898s - fetched 100

### Environment

```shell
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    gatsby: ^4.0.1 => 4.0.1 
    gatsby-plugin-breadcrumb: ^12.2.0 => 12.2.0 
    gatsby-plugin-image: ^2.0.0 => 2.0.0 
    gatsby-plugin-manifest: ^4.0.0 => 4.0.0 
    gatsby-plugin-offline: ^5.0.0 => 5.0.0 
    gatsby-plugin-react-helmet: ^5.0.0 => 5.0.0 
    gatsby-plugin-react-svg: ^3.1.0 => 3.1.0 
    gatsby-plugin-sharp: ^4.0.0 => 4.0.0 
    gatsby-plugin-typesense: ^0.3.0 => 0.3.0 
    gatsby-source-filesystem: ^4.0.0 => 4.0.0 
    gatsby-source-wordpress: ^6.0.0 => 6.0.0 
    gatsby-transformer-sharp: ^4.0.0 => 4.0.0 
  npmGlobalPackages:
    gatsby-cli: 4.0.0
```

**Comment by LekoArts** [comment]
Hi!

We'll need a [minimal reproduction][reproduction] as your reproduction steps are not enough for me or my colleagues to understand where the problem might lie.

Maybe you have a typo in https://www.wpgraphql.com/filters/graphql_connection_max_query_amount/ or your `gatsby-config.js`. We don't know 🤷 

[reproduction]: https://gatsby.dev/reproduction

**Comment by charles-langley** [comment]
Here is a reproduction, which is nothing more than the gatsby-starter-wordpress-blog base with a limit increase in gatsby-config.js set for all types to 150.

https://github.com/charles-langley/demo

gatsby-node.js:

      resolve: `gatsby-source-wordpress`,
      options: {
        // the only required plugin option for WordPress is the GraphQL url.
        url:
          process.env.WPGRAPHQL_URL ||
          `https://api.example.com/graphql`,
        type: {
          __all: {
            limit: 150
          },
        },
      },
    }

As far as I can tell, setting the limit to 150 has the expected behavior for everything except custom taxonomies.

For example, here's the output for a custom post type, fetching the number of posts expected:
`success  gatsby-source-wordpress  WpCptContent - 11.496s - fetched 126`

Being able to pull more than 100 posts from a custom post type does not require us to alter any limits set by the WP GraphQL plugin. I was merely mentioning the fact that we also tried that, to no avail. That being said, here's what we have for that as well:

`add_filter( 'graphql_connection_max_query_amount', function ( int $max_amount, $source, array $args, $context, $info ) {
        return 1000;
}, 10, 5 );`

We also tried, to no avail, to increase the limits for individual types in gatsby-config.js, based on the documentation here: 
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/plugin-options.md


The issue appears to be a bug



Side Note: When creating this reproduction demo, `gatsby new my-wordpress-gatsby-site https://github.com/gatsbyjs/gatsby-starter-wordpress-blog` fails as it's requiring `gatsby-plugin-manifest@^4.0.2` when 4.0.0 is the latest version as of 5 hours ago according to npmjs. Let me know if you want me to submit a new bug report for that.

**Comment by charles-langley** [comment]
I'm updating this as per the email to keep the issue open.

**Comment by charles-langley** [comment]
Updating to include this bug affects standard wordpress tags as well

**Comment by charles-langley** [comment]
I've narrowed this bug down to taxonomies of any type (wordpress default or custom) being tied to "perPage" in gatsby-source-wordpress schema option for some reason. Taxonomies are just as important as posts/pages, so they should be handled the same.
