### ISSUE TITLE
[gatsby-source-wordpress] Initial creation fails due to dep version mismatch

### ISSUE THREAD

**Issue by charles-langley** [gatsbyjs/gatsby#33797]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Initial `npm install` fails when creating a new gatsby wordpress starter.

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for gatsby-plugin-manifest@^4.0.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'my-wordpress-gatsby-site'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:

 ERROR

Command failed with exit code 1: npm install
```

### Reproduction Link

https://github.com/gatsbyjs/gatsby-starter-wordpress-blog

### Steps to Reproduce

1. gatsby new my-wordpress-gatsby-site https://github.com/gatsbyjs/gatsby-starter-wordpress-blog

### Expected Result

initial install completes successfully

### Actual Result

initial install fails

### Environment

```shell
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmGlobalPackages:
    gatsby-cli: 4.0.0
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue. The specific starter https://github.com/gatsbyjs/gatsby-starter-wordpress-blog is managed in that repository (and not in this one). I filed this internally as a bug so that I'll be fixed soon.
