### ISSUE TITLE
graphql : Unterminated template

### ISSUE THREAD

**Issue by fvisticot** [gatsbyjs/gatsby#3381]
From the following sample code : 

```
export const query = graphql`
  query MyFilesQuery {
    allFile {
      edges {
        node {
          relativePath
          prettySize
          extension
          birthTime(fromNow: true)
        }
      }
    }
  }
```
I got this error

> Syntax Error: Unterminated template (40:29)
> 
>   38 | }
>   39 | 
> > 40 | export const query = graphql`
>      |                              ^
>   41 |   query MyFilesQuery {
>   42 |     allFile {
>   43 |       edges {
>

**Comment by m-allanson** [comment]
Do you need a closing ` character after the last bracket?

**Comment by akadop** [comment]
add the closing ` after the end of the query

**Comment by fvisticot** [comment]
Tx a lot !!!
That fixed my issue !!
