### ISSUE TITLE
Incorrect typescript - ITypeInfoDate 

### ISSUE THREAD

**Issue by tonyhallett** [gatsbyjs/gatsby#33838]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

[example field](https://github.com/gatsbyjs/gatsby/blob/a8745ea26624ef758080846adefff3d5d7784291/packages/gatsby/src/schema/infer/inference-metadata.ts#L78) typed incorrectly

```
export interface ITypeInfoDate extends ITypeInfo {
  example: string
}
```
Should be
export interface ITypeInfoDate extends ITypeInfo {
  example: string | Date
}

getType will return date for a node field value that is a Date or is a string that looksLikeADate
```
const getType = (value: unknown, key: string): ValueType | "null" => {
  // Staying as close as possible to GraphQL types
  switch (typeof value) {
    case `number`:
      return is32BitInteger(value) ? `int` : `float`
    case `string`:
      if (key.includes(`___NODE`)) {
        return `relatedNode`
      }
      return looksLikeADate(value) ? `date` : `string` // *********************************
    case `boolean`:
      return `boolean`
    case `object`:
      if (value === null) return `null`
      if (value instanceof Date) return `date` // *****************************************
      if (value instanceof String) return `string`
      if (Array.isArray(value)) {
        if (value.length === 0) {
          return `null`
        }
        return key.includes(`___NODE`) ? `relatedNodeList` : `array`
      }
      if (!Object.keys(value).length) return `null`
      return `object`
    default:
      // bigint, symbol, function, unknown (host objects in IE were typeof "unknown", for example)
      return `null`
  }
}
```

and for date types the [example value](https://github.com/gatsbyjs/gatsby/blob/a8745ea26624ef758080846adefff3d5d7784291/packages/gatsby/src/schema/infer/inference-metadata.ts#L351) is the node field value - a string or a Date

### Reproduction Link

https://github.com/gatsbyjs/gatsby/blob/a8745ea26624ef758080846adefff3d5d7784291/packages/gatsby/src/schema/infer/inference-metadata.ts#L78

### Steps to Reproduce

1. Follow my description
2.
3.
...

### Expected Result

typescript is correct

### Actual Result

typescript is incorrect

### Environment

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  Binaries:
    Node: 16.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - C:\Program Files\nodejs\yarn.CMD
    npm: 7.21.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.40)
  npmPackages:
    gatsby: ^3.13.1 => 3.14.2
    gatsby-plugin-mdx: ^2.14.0 => 2.14.0
    gatsby-source-filesystem: ^3.14.0 => 3.14.0
  npmGlobalPackages:
    gatsby-cli: 3.14.0
    gatsby-dev-cli: 3.14.0
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue.

I'll close this one as it's not related to public types but only our internal code. While having correct types everywhere would be nice fixing the internal ones is not our top priority as it normally yields small benefits compared to other things we (and contributors) can work on. If you find them while browsing the code, feel free to open a PR, but I wouldn't recommend hunting for them. Thanks!
