### ISSUE TITLE
Chrome's Lighthouse audit not working when 'gatsby-plugin-offline' is enabled

### ISSUE THREAD

**Issue by ansmlc** [gatsbyjs/gatsby#33837]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When`'gatsby-plugin-offline' ` is enabled, auditing page with Chrome's Lighthouse audit tool is not working properly. Lighthouse gets stuck and loads infinitely. Testing in latest Chrome (v95.0.4638.69) on Windows 10. 

Rarely, it will finish and show " ? " instead of score, and very rarely it will succeed and show correct scores, but still either it takes very long (up to 10 minutes) to finish the audit or it happens rapidly within a few seconds. Overall erratic behavior.

On the other hand, Google's online PageSpeed Insights tool successfully audits the same page every time. So do other online tools.

- Recreated with a fresh install 'gatsby-starter-minimal'. Merely enabling PWA with 'gatsby-plugin-offline' breaks Lighthouse: https://naughty-yonath-344d6c.netlify.app/
- Same results with gatsby-default-starter and gatsby-starter-hello-world 
- Testing on another device (MacOS, same Chrome version) produces same results.
- It's the same behavior whether testing at localhost:9000 with `gatsby serve` or at a live site on Netlify. 
- Being in Incognito mode doesn't seem to make a difference.
- It's the same whether testing with a Gatsby v3.7.2. or Gatsby v4.1.0. site.

### Reproduction Link

https://github.com/ansmlc/gatsby-minimal-pwa

### Steps to Reproduce

1. Install latest version of Gatsby and Google Chrome
2. Install gatsby-starter-minimal
3. Add 'gatsby-plugin-offline' in gatsby-config.js
4. Build & Serve
5. Visit localhost:9000 and run Lighthouse audit 
...
Or
1. Visit https://naughty-yonath-344d6c.netlify.app/
2. Run Lighthouse audit

### Expected Result

Lighthouse to finish loading and show performance scores

### Actual Result

Lighthouse loads infinitely and never delivers performance scores

#### gatsby-minimal
```shell
  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.40)
  npmPackages:
    gatsby: ^4.1.0 => 4.1.0 
    gatsby-plugin-manifest: ^4.1.0 => 4.1.0 
    gatsby-plugin-offline: ^5.1.0 => 5.1.0 
  npmGlobalPackages:
    gatsby-cli: 3.8.0
```

#### Edit:
- Updated with gatsby-minimal recreation repo and live site link

**Comment by iChenLei** [comment]
Latest update https://github.com/GoogleChrome/lighthouse/issues/13396#issuecomment-989286890

**Comment by LekoArts** [comment]
Please follow https://github.com/GoogleChrome/lighthouse/issues/13396 for resolution on this. It's not something we can fix. Thanks!
