### ISSUE TITLE
proposed typescript correction

### ISSUE THREAD

**Issue by tonyhallett** [gatsbyjs/gatsby#33842]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

[IGatsbyState](https://github.com/gatsbyjs/gatsby/blob/926dc6fd37ba805b007f372941fb4024488a3470/packages/gatsby/src/redux/types.ts#L331) has a slice for inference metadata.

```
export interface IGatsbyState {
  //.....
  inferenceMetadata: {
    step: string // TODO make enum or union
    typeMap: {
      [key: string]: ITypeMetadata
    }
  }
}

```
[ITypeMetadata ](https://github.com/gatsbyjs/gatsby/blob/926dc6fd37ba805b007f372941fb4024488a3470/packages/gatsby/src/schema/infer/inference-metadata.ts#L117) has fields that are not set by the reducer and seem present as a convenience.

```
export interface ITypeMetadata {
  
  disabled?: boolean
  ignored?: boolean
  dirty?: boolean
  total?: number
  ignoredFields?: Set<string>
  fieldMap?: Record<string, IValueDescriptor>

  // ************************************************************ 
  typeName?: string
  typeConflictReporter?: TypeConflictReporter
  [key: string]: unknown
}

```

The typeName and typeConflictReporter are fields on the [getExampleObject](https://github.com/gatsbyjs/gatsby/blob/926dc6fd37ba805b007f372941fb4024488a3470/packages/gatsby/src/schema/infer/index.js#L101) argument.  

In my opinion [getExampleObject](https://github.com/gatsbyjs/gatsby/blob/926dc6fd37ba805b007f372941fb4024488a3470/packages/gatsby/src/schema/infer/build-example-data.ts#L19) should be changed from

```
const getExampleObject = ({
  fieldMap = {},
  typeName,
  typeConflictReporter,
}: ITypeMetadata): 
```

to
```
interface ExampleObjectConfig = {
  fieldMap: ITypeMetadata["fieldMap"] // or use Pick
  typeName:string,
  typeConfictReporter?: TypeConflictReporter
} 
const getExampleObject = ({
  fieldMap = {},
  typeName,
  typeConflictReporter,
}: ExampleObjectConfig ): 
```

Remove from ITypeMetadata
```
  typeName?: string
  typeConflictReporter?: TypeConflictReporter
  [key: string]: unknown
```

Then adjust errors that arise.

### Reproduction Link

https://github.com/gatsbyjs/gatsby/blob/926dc6fd37ba805b007f372941fb4024488a3470/packages/gatsby/src/schema/infer/inference-metadata.ts#L117

### Steps to Reproduce

1. Try to find in source code where the state could match the typing
2.
3.
...

### Expected Result

ITypeMetadata to reflect what is in state.

### Actual Result

I think that the typescript does not represent possible state accurately enough.

### Environment

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  Binaries:
    Node: 16.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - C:\Program Files\nodejs\yarn.CMD
    npm: 7.21.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.40)
  npmPackages:
    gatsby: ^3.13.1 => 3.14.2 
    gatsby-plugin-mdx: ^2.14.0 => 2.14.0 
    gatsby-source-filesystem: ^3.14.0 => 3.14.0 
  npmGlobalPackages:
    gatsby-cli: 3.14.0
    gatsby-dev-cli: 3.14.0
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue.

I'll close this one as it's not related to public types but only our internal code. While having correct types everywhere would be nice fixing the internal ones is not our top priority as it normally yields small benefits compared to other things we (and contributors) can work on. If you find them while browsing the code, feel free to open a PR, but I wouldn't recommend hunting for them. Thanks!
