### ISSUE TITLE
[Side project] Free Wix competitor using Gatsby. Who is interested?

### ISSUE THREAD

**Issue by MarcCoet** [gatsbyjs/gatsby#3386]
For approx a year, when Gatsby 1.0 was still in its early alphas, I have been working on a website builder for clients to be able to create and modify their own static websites. I have called it **toile**.
A result can be seen [there](http://www.toile.io/) and a few "test clients" are referenced on the [portfolio page](http://www.toile.io/portfolio/).

It is meant to be open source and (truly) free for personal use and probably even for commercial use but I am still thinking of a good business model if any.

Who is interested in using this?
Who is interested in contributing?

**Comment by arsmth** [comment]
It's a bit difficult to understand what you're offering as your site is all text. I would suggest an actual demo or example of your product. Maybe have a look at the [Figma](https://www.figma.com) site for inspo on getting the gist of your product across.

**Comment by MarcCoet** [comment]
Of course. At this point I just want to know if there is any interest at all in this kind of product.
The site is just a demo of what is possible, not how. I don't even have any documentation whatsoever.
Thanks for the figma example. Maybe you are right and I'll need to show more before I can get feedbacks...

**Comment by KyleAMathews** [comment]
I think a Wix built on top of Gatsby would be very cool :-) Wix seems to have a good business model and lots of interest! It'd be perhaps a bit tougher to do it as an open source project though as open source is better at infrastructure vs. products as lots of people need the same infrastructure whereas relatively few need great products so more difficult to get contributors for the latter.

**Comment by arsmth** [comment]
If it was open source and anyone could contribute components to the library that can be dropped in like navbars, footers or carousels etc. then that would be really cool. [Alva](https://meetalva.io) is another open source project with a somewhat similar vibe - I think it creates code from a drag and drop interface but I haven’t tried it so I’m not sure.

Btw I think it’s definitely something people would be interested in but this is the wrong place to find that interest because everyone here can code and wouldn’t use wix anyway. Something I would be more interested in is some sort of UI for setting up a gatsby project with all the essential plugins that I want without having to code it myself e.g. I want page transitions so I just select it in my interface and then it will update my code with page transitions and all I have to do is choose a style.

**Comment by MarcCoet** [comment]
Great feedbacks. Thanks!
I think the project would need to be backed by a company indeed. Counting on contributors only for development would be a risky bet.
For now toile lacks "user friendliness" of course but an interesting fact is that I managed to keep user editing very close to the code. I think that even experienced developers might like the experience as you can start building very fast and tweak everything with html (in markdown) and css along the way. Then when you need more, you can just use Gatsby as you normally would. That's another advantage of making the project open source. You can "eject" in your own repo anytime and customize as much as you want there.

Anyway... I know that without showing any code that does not mean much. I just want to let you know that I appreciate the feedbacks.

**Comment by mushroomgenie** [comment]
@MarcCoet Interesting project. I too have been using Gatbsy for a while now and had the similar kind of idea of building data driven websites for businesses. Any idea how AWS could be used for such an implementation?

**Comment by MarcCoet** [comment]
@mushroomgenie no idea. I am not using AWS for now. For lambda functions, first place I would check is Netlify. They are implementing a way to use lambda functions on build. It is in Alpha so dunno how it will look like. You can apply for early access I think.

**Comment by MarcCoet** [comment]
Still working on this but closing the issue 'cause... it is not really an issue after all. ^^
I'll still read the feedbacks so don't hesitate.
And don't hesitate to contact me for further discussions.
