### ISSUE TITLE
nprogress accessibility issues

### ISSUE THREAD

**Issue by pelikhan** [gatsbyjs/gatsby#33875]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

The plugin https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-nprogress uses npgroress, which has accessibilty issues (https://github.com/rstacruz/nprogress/issues/180).

It seems that a fork exists which has address those issues at https://github.com/nmackey/accessible-nprogress.

### Reproduction Link

na

### Steps to Reproduce

1. install gatsby-plugin-nprogress 
2. run accessibilty checker

### Expected Result

No accessiblity violations

### Actual Result

![image](https://user-images.githubusercontent.com/4175913/140557326-b7072e94-dd58-4706-9fc5-d2db7f6d1142.png)

### Environment

```shell
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  npmPackages:
    gatsby: ^3.14.2 => 3.14.2
    gatsby-plugin-catch-links: ^3.14.0 => 3.14.0
    gatsby-plugin-image: ^1.14.1 => 1.14.1
    gatsby-plugin-manifest: ^3.14.0 => 3.14.0
    gatsby-plugin-mdx: ^2.14.0 => 2.14.0
    gatsby-plugin-meta-redirect: ^1.1.1 => 1.1.1
    gatsby-plugin-nprogress: ^3.14.0 => 3.14.0
    gatsby-plugin-offline: ^4.14.0 => 4.14.0
    gatsby-plugin-react-helmet: ^4.14.0 => 4.14.0
    gatsby-plugin-robots-txt: ^1.6.10 => 1.6.10
    gatsby-plugin-sharp: ^3.14.1 => 3.14.1
    gatsby-plugin-sitemap: ^4.10.0 => 4.10.0
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.25 => 1.1.25
    gatsby-prismjs-dracula: ^0.1.15 => 0.1.15
    gatsby-remark-autolink-headers: ^4.11.0 => 4.11.0
    gatsby-remark-external-links: 0.0.4 => 0.0.4
    gatsby-remark-images: ^5.11.0 => 5.11.0
    gatsby-remark-makecode: ^1.0.19 => 1.0.19
    gatsby-remark-prismjs: ^5.11.0 => 5.11.0
    gatsby-remark-static-images: ^1.2.1 => 1.2.1
    gatsby-source-filesystem: ^3.14.0 => 3.14.0
    gatsby-theme-material-ui: ^5.0.0 => 5.0.0
    gatsby-transformer-csv: ^3.14.0 => 3.14.0
    gatsby-transformer-json: ^3.14.0 => 3.14.0
    gatsby-transformer-plaintext: ^2.0.0 => 2.0.0
    gatsby-transformer-remark: ^4.11.0 => 4.11.0
    gatsby-transformer-sharp: ^3.14.0 => 3.14.0
  npmGlobalPackages:
    gatsby: 4.0.2
```

### Config Flags

No

**Comment by Bruce-Hopkins-Jr** [comment]
Hi!

Can you create a [minimal reproduction](https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/) so I can assist with this issue more efficiently?

**Comment by LekoArts** [comment]
Happy to review a PR changing out the library! :)

**Comment by pranav0281999** [comment]
Hi @LekoArts , can I be assigned to this issue? Trying to solve it right now.

**Comment by pranav0281999** [comment]
Just letting everyone know, I have made the changes and I will be creating a PR after I read about the proper way to document commit and PR messages.
