### ISSUE TITLE
Can't compile latest version of Gatsby

### ISSUE THREAD

**Issue by kisabelle** [gatsbyjs/gatsby#33890]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Unable to run `gatsby develop` or `gatsby build` with a fresh install of Gatsby or with a Gatsby 3 project that has been updated to Gatsby 4.

Seems to be an issue with a (new?) dependencies `lmdb-store` and `weak-lru-cache`, as the build process errors out very early on with the following error: `WeakRef is not defined`

I am running Node v14.9

### Steps to Reproduce

1. Upgrade a Gatsby 3 project to Gatsby 4
2. Run `gatsby develop` or `gatsby build`

### Expected Result

Successfully build Gatsby site

### Actual Result

Fails to build. Console error on `gatsby build` or `gatsby develop`:

```
success open and validate gatsby-configs, load plugins - 0.184s
success onPreInit - 0.001s

 ERROR

WeakRef is not defined



  ReferenceError: WeakRef is not defined

  - index.cjs:17 new LRFUExpirer
    [project-name]/[weak-lru-cache]/dist/index.cjs:17:25

  - index.cjs:163 new WeakLRUCache
    [project-name]/[weak-lru-cache]/dist/index.cjs:163:142

  - caching.js:31 new <anonymous>
    [project-name]/[lmdb-store]/caching.js:31:16

  - index.js:257 LMDBStore.openDB
    [project-name]/[lmdb-store]/index.js:257:6

  - lmdb-datastore.ts:68 getDatabases
    [project-name]/[gatsby]/src/datastore/lmdb/lmdb-datastore.ts:68:21

  - lmdb-datastore.ts:230 clearIndexes
    [project-name]/[gatsby]/src/datastore/lmdb/lmdb-datastore.ts:230:15

  - lmdb-datastore.ts:261 setupLmdbStore
    [project-name]/[gatsby]/src/datastore/lmdb/lmdb-datastore.ts:261:3

  - datastore.ts:11 getDataStore
    [project-name]/[gatsby]/src/datastore/datastore.ts:11:19

  - datastore.ts:50 callback
    [project-name]/[gatsby]/src/datastore/datastore.ts:50:3

  - mett.ts:44 forEach
    [project-name]/[gatsby]/src/utils/mett.ts:44:11

  - Set.forEach

  - mett.ts:43 Object.emit
    [project-name]/[gatsby]/src/utils/mett.ts:43:17

  - index.ts:153
    [project-name]/[gatsby]/src/redux/index.ts:153:11

  - redux.js:228 next
    [project-name]/[redux]/lib/redux.js:228:7

  - index.ts:72
    [project-name]/[gatsby]/src/redux/index.ts:72:68

  - index.js:27 Object.dispatch
    [project-name]/[redux-thunk]/lib/index.js:27:16


not finished initialize cache - 0.206s
```

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    npm: 6.14.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.13 - /Applications/MAMP/Library/bin/python
  Browsers:
    Chrome: 95.0.4638.69
    Edge: 95.0.1020.44
    Firefox: 94.0.1
    Safari: 15.0
  npmPackages:
    gatsby: ^4.1.0 => 4.1.0
  npmGlobalPackages:
    gatsby-cli: 3.14.1
```

**Comment by kisabelle** [comment]
Disregard. Had switched to Node 14 in the current tab of my terminal app but was still running Node 12 in the tab where I was running `gatsby develop`. Ensuring that current tab was switched to Node 14 resolved the issue!

Thanks for being my rubber duck

**Comment by LekoArts** [comment]
Please note that you have to use at least Node >= 14.15.0

**Comment by simonjoom** [comment]
it's possible to use old node. For me i cannot update my node because my old mac.
install this: tc39-weakrefs-shim

and patch weak-lru-cache/index.js with:
this in first line
const { WeakRef, FinalizationGroup:FinalizationRegistry } = require("tc39-weakrefs-shim/lib/node");

With this, sometimes compilation can stop for me (certainly memory loss)
