### ISSUE TITLE
Resource loading issues

### ISSUE THREAD

**Issue by baseten** [gatsbyjs/gatsby#3391]
I'm having some odd issues with resource loading, especially on slow connections. I think it may be related to [this issue](https://github.com/gatsbyjs/gatsby/issues/3372). I'm using `gatsby 1.9.149` and `gatsby-link 1.6.32`

I'm trying to use the `onRouteUpdate` API to trigger page transitions. Looking through the loader code and gatsby-link, it looks like `history.push` shouldn't be called until all the resources are loaded, but the first time I navigate to a page `onRouteUpdate` seems to fire *before* the resources are actually loaded messing up my transitions. There are also issues where gatsby-link's `activeClassName` prop doesn't function correctly, and the previously navigated link is showing as active.

I'm not sure if it's related but when navigating from page to page, the `onPostLoadPageResources` event fires multiple times. The first time I navigate to a page it fires 4 times and from then on it fires 3 times. Not sure if this is intentional?

**Comment by KyleAMathews** [comment]
Yeah — looks like the same issue :-(

`onPostLoadPageResources` is called after every page resource is loaded — so probably what you're seeing is the first page loaded is loading the layout component but from then on it's not.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
