### ISSUE TITLE
[gatsby-plugin-emotion] Avoid using @emotion/babel-preset-css-prop when jsxRuntime set to automatic

### ISSUE THREAD

**Issue by mwskwong** [gatsbyjs/gatsby#33936]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

As mentioned in the [Emotion official document](https://emotion.sh/docs/@emotion/babel-preset-css-prop), `@emotion/babel-preset-css-prop` should only be used for classic JSX, but `gatsby-plugin-emotion` seems to use it regardless what value is specified in `jsxRuntime`.

### Reproduction Link

N/A

### Steps to Reproduce

N/A

### Expected Result

`gatsby-plugin-emotion` will use `@emotion/babel-preset-css-prop` when users are using classic JSX transformation. And use `@emotion/babel-plugin` directly when users are using automatic JSX transformation.

### Actual Result

`gatsby-plugin-emotion` always uses `@emotion/babel-preset-css-prop` regardless the runtime setting.

### Environment

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Node: 16.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.10.0
  Browsers:
    Chrome: 94.0.4606.81
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.44)
  npmPackages:
    gatsby: ^4.1.3 => 4.1.3 
    gatsby-plugin-emotion: ^7.1.0 => 7.1.0 
    gatsby-plugin-image: ^2.1.1 => 2.1.1 
    gatsby-plugin-manifest: ^4.1.2 => 4.1.2 
    gatsby-plugin-netlify: ^4.0.0-next.0 => 4.0.0-next.0 
    gatsby-plugin-offline: ^5.1.2 => 5.1.2 
    gatsby-plugin-perf-budgets: ^0.0.18 => 0.0.18 
    gatsby-plugin-perfect-dark-mode: ^1.0.0 => 1.0.0 
    gatsby-plugin-preconnect: ^1.3.0 => 1.3.0 
    gatsby-plugin-react-helmet: ^5.1.0 => 5.1.0 
    gatsby-plugin-sharp: ^4.1.1 => 4.1.2 
    gatsby-plugin-sitemap: ^5.1.1 => 5.1.1 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.25 => 1.1.25 
    gatsby-source-contentful: ^6.1.2 => 6.1.2 
    gatsby-transformer-sharp: ^4.1.0 => 4.1.0
```

### Config Flags

FAST_DEV: true,
PARALLEL_SOURCING: true,
PRESERVE_FILE_DOWNLOAD_CACHE: true

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by mwskwong** [comment]
> Hi!
> 
> Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction](https://gatsby.dev/reproduction). This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.
> 
> If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction](https://gatsby.dev/reproduction) and we'll be able to take another look.
> 
> Thanks for using Gatsby! 💜

Unlike most of the issues, I don't think reproduction will add any benefits to this one. Everything will still work with the plugin with or without the changes and you can't really tell the differences unless you take a look at the source code of the plugin or the build files of the website. It is more about best practices.

Instead, if you just have a look at the [source code](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-emotion/src/gatsby-node.js) of the plugin. It clearly shows the plugin is using the preset in any situations.

**Comment by mwskwong** [comment]
@LekoArts I hope you understand. A reproduction will have zero help in this case.
