### ISSUE TITLE
Cannot get type name from ThunkComposer

### ISSUE THREAD

**Issue by marcomiduri** [gatsbyjs/gatsby#33957]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I have enabled server-side rendering and DSG for our shop product pages. Page fetches the product review information in real-time using server-side rendering. After I enable server-side rendering, I am getting this error on build process.

`Error: Cannot get type name from ThunkComposer({ _thunk: [function ], _typeName: "ContentBlock" })`

This `ContentBlock` is a custom schema interface that I created using the `createSchemaCustomization` API.

FYI, it's working fine on development mode.

### Reproduction Link

[Minimal Reproduction Repository](https://github.com/marcomiduri/gatsby-issue-reproduction)

### Steps to Reproduce

1. Run `gatsby build`

### Expected Result

Build should be done without any problems

### Actual Result
```
3:19:48 PM: error /opt/build/repo/.cache/query-engine/index.js:130612
3:19:48 PM:       throw new Error(`Cannot get type name from ${(0,_misc__WEBPACK_IMPORTED_MODULE_2__.inspect)(type)}`);
3:19:48 PM:             ^
3:19:48 PM: error Error: Cannot get type name from ThunkComposer({ _thunk: [function ], _typeName: "ContentBlock" })
3:19:48 PM:     at getComposeTypeName (/opt/build/repo/.cache/query-engine/index.js:130612:13)
3:19:48 PM:     at ObjectTypeComposer.hasInterface (/opt/build/repo/.cache/query-engine/index.js:126738:93)
3:19:48 PM:     at ObjectTypeComposer.addInterface (/opt/build/repo/.cache/query-engine/index.js:126743:15)
3:19:48 PM:     at /opt/build/repo/.cache/query-engine/index.js:206241:56
3:19:48 PM:     at Array.forEach (<anonymous>)
3:19:48 PM:     at mergeTypes (/opt/build/repo/.cache/query-engine/index.js:206241:26)
3:19:48 PM:     at /opt/build/repo/.cache/query-engine/index.js:207100:7
3:19:48 PM:     at Array.forEach (<anonymous>)
3:19:48 PM:     at parseTypes (/opt/build/repo/.cache/query-engine/index.js:207086:19)
3:19:48 PM:     at /opt/build/repo/.cache/query-engine/index.js:206133:23
3:19:48 PM:     at Array.forEach (<anonymous>)
3:19:48 PM:     at addTypes (/opt/build/repo/.cache/query-engine/index.js:206120:9)
3:19:48 PM:     at updateSchemaComposer (/opt/build/repo/.cache/query-engine/index.js:205982:9)
3:19:48 PM:     at buildSchema (/opt/build/repo/.cache/query-engine/index.js:205925:9)
3:19:48 PM:     at build (/opt/build/repo/.cache/query-engine/index.js:24422:18)
3:19:48 PM:     at GraphQLEngine._doGetRunner (/opt/build/repo/.cache/query-engine/index.js:448573:5)
```
### Environment

```shell
System:
  OS: Windows 11
Binaries
  Node: v16.3.0
  NPM: v7.15.1
Gatsby: v4.1.4
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by marcomiduri** [comment]
@LekoArts Thanks for checking this issue. I actually produced a minimal reproduction but it works fine on there. I really can't sure how to reproduce the issue on there. What can I do here?

**Comment by graysonhicks** [comment]
@marcomiduri Yes, if the `.env` file is needed to reproduce, please add it.  Thanks!

**Comment by jroehl** [comment]
Hi @graysonhicks - I have a similar issue:

I am using `gatsby-source-contentful` and need to fix a type on an existing (automatically) created type by letting it implement an interface: 

```graphql
interface SubPage {
  contentful_id: String!
  node_locale: String!
  slug: String
  subPages: [SubPages]
  dynamicSubPageKeys: [String]
}

union SubPages = ContentfulPage | ContentfulPureContent

type ContentfulPage implements SubPage {
  subPages: [SubPages]
}

type ContentfulPureContent implements SubPage {
  subPages: [SubPages]
}
```

Everything works fine with `gatsby develop`. 
During `gatsby build` it fails at `Validating Rendering Engines` with the error
`Error: Cannot get type name from ThunkComposer({ _thunk: [function ], _typeName: "SubPage" })`.

Apparently, it has something to do with adding an interface - or even fixing a type on an existing (inferred) type.

It would be great if you could look into it ...
Thanks for all the great work!

**Comment by marcomiduri** [comment]
@graysonhicks I have committed the `.env` file with test sanity project access. You should be able to replicate the error on your side. https://github.com/marcomiduri/gatsby-issue-reproduction/blob/master/.env

**Comment by marcomiduri** [comment]
Hi, @LekoArts @graysonhicks Just wanted to check if this issue is still progressing

**Comment by LekoArts** [comment]
You can't do this with engines as it doesn't support bundling these files:

https://github.com/marcomiduri/gatsby-issue-reproduction/blob/50bbe785b4abcd0e92f82a4e16f0b1ee3b255295/gatsby-node.js#L17-L20

You'll need to put the definition either in a file and import it or directly put it into gatsby-node.js

(So this is not a bug but a limitation)

**Comment by marcomiduri** [comment]
@LekoArts @graysonhicks Thanks for your immediate response. I just removed `schema.graphql` file and moved the graphql code into `gatsby-node.js`. Please check my last commit. But it's the same... If I don't use the `union` define, it works. Hope this gives you a good clue.

**Comment by LekoArts** [comment]
I'm not really understanding why you're redefining the types there as it already correctly creates a union:

![image](https://user-images.githubusercontent.com/16143594/143007475-e1e28bc2-0834-46b8-9b11-f2337a2eced8.png)

But anyways, if you want to have a custom union, you need to define it this way:

```js
exports.createSchemaCustomization = ({ actions, schema }) => {
  const { createTypes } = actions

  const typeDefs = `    
    type SanityBifold {
      id: ID!
      _type: String!
      _key: String!
    }
    
    type SanityCallToAction {
      id: ID!
      _type: String!
      _key: String!
    }
    
    type SanityPage implements Node {
      contentBlocks: [ContentBlocks]
    }
  `

  const ContentBlocks = schema.buildUnionType({
    name: `ContentBlocks`,
    types: [`SanityBifold`, `SanityCallToAction`],
    resolveType: (value, info) => {
      if (value._type === `bifold`) {
        return `SanityBifold`
      } else {
        return `SanityCallToAction`
      }
    }
  })

  createTypes(typeDefs)
  createTypes([ContentBlocks])
}
```

Then it'll also work:

![image](https://user-images.githubusercontent.com/16143594/143008594-50a4e746-5ed0-4f14-abc4-dd66756d470b.png)

Successfully built:

![image](https://user-images.githubusercontent.com/16143594/143008791-318992b5-2d61-4252-a28c-cf125930f658.png)

**Comment by marcomiduri** [comment]
@LekoArts Thank you very much for this code snippet. But I have to define `ContentBlock` interface for this project. I have pushed a new commit to my reproduction repository. Can you please review that? I followed this for creating interface but I am still getting the same error. 

My last commit URL: https://github.com/marcomiduri/gatsby-issue-reproduction/commit/a6a60811e253a365e52a6119f513b06040a7d558
Comment URL: https://github.com/gatsbyjs/gatsby/issues/20969#issuecomment-579879720

Thank you

**Comment by LekoArts** [comment]
@marcomiduri 

> But I have to define ContentBlock interface for this project.

Why do you have to do that?

**Comment by marcomiduri** [comment]
@LekoArts I have defined a fragment called ContentBlockBase and used it on all block fragment like below:

```graphql
  fragment ContentBlockBase on ContentBlock {
    _type
    _key
  }
  fragment Blocks on ContentBlocks {
    ...ContentBlockBase
  }
```

So we don't need to write `_type`, `_key` fields everytime.

**Comment by pieh** [comment]
I have minimal repro for error like this to happen during regular schema building in https://github.com/pieh/i33957-mini/blob/c8a1c27fcd8a6400fc2585daded1387c116e5847/gatsby-node.js

Not yet sure where the problem is, but this at least it seems to simulate what happens when engines validation happen and should make it easier to debug moving forward (it doesn't have any plugins other than internals so there is less "noise" in there)
