### ISSUE TITLE
GatsbyImage css classes specificity overtakes Tailwind only on build, not develop

### ISSUE THREAD

**Issue by hisnameisjimmy** [gatsbyjs/gatsby#33960]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When working with [Tailwind CSS aspect ratio](https://github.com/tailwindlabs/tailwindcss-aspect-ratio) and GatsbyImage, everything looks and works fine locally when working with `gatsby develop`, but once deployed I saw that GatsbyImage is providing css classes that override Tailwind specificity and produce unexpected results. I found [this discussion around StaticImage](https://github.com/gatsbyjs/gatsby/discussions/33565), but a few things come to mind:
- This should work the same in development as in production, I shouldn't be surprised by build time css specificity issues
- For aspect ratio, Tailwind doesn't add !important when using the `important: true` directive in their config, so the workaround specified in the discussion won't work here
- There should be an explicit workaround for these cases in the gatsby-plugin-image documentation

You can see the live version of this here: https://inspiring-hamilton-bd685d.netlify.app/

### Reproduction Link

https://github.com/hisnameisjimmy/gatsby-plugin-image-tailwind-specificity

### Steps to Reproduce

1. Clone the repo & `npm install`
2. `gatsby develop` and go to localhost:8000
3. Stop the dev server and `gatsby build && gatsby serve`
4. Go to localhost:9000

### Expected Result

- Things should look the same both in develop and build versions of the site. 
- GatsbyImage should not be injecting css classes that conflict with any classes that I write

### Actual Result

- Things look and work differently between develop and build versions of the site
- GatsbyImage messes with my css

### Environment

```shell
System:
    OS: macOS 11.5.2
    CPU: (8) arm64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.9.1 - ~/.nvm/versions/node/v16.9.1/bin/node
    npm: 7.21.1 - ~/.nvm/versions/node/v16.9.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 95.0.4638.69
    Safari: 14.1.2
  npmPackages:
    gatsby: ^4.1.3 => 4.1.3 
    gatsby-plugin-image: ^2.1.2 => 2.1.2 
    gatsby-plugin-mdx: ^3.1.3 => 3.1.3 
    gatsby-plugin-postcss: ^5.1.0 => 5.1.0 
    gatsby-plugin-sharp: ^4.1.3 => 4.1.3 
    gatsby-source-filesystem: ^4.1.2 => 4.1.2 
    gatsby-transformer-sharp: ^4.1.0 => 4.1.0 
  npmGlobalPackages:
    gatsby-cli: 4.1.1
```

**Comment by hisnameisjimmy** [comment]
As is traditional in software, I figured out a workaround after spending a huge amount of time documenting the core issue. 

If you enable `jit` in your tailwind config:
```
module.exports = {
    mode: 'jit',
    purge: [
      './public/**/*.html',
      './src/**/*.{js,jsx,ts,tsx,vue}',
    ],
    darkMode: false,
    theme: {},
    variants: {
      extend: {},
    },
    plugins: [
      require("@tailwindcss/aspect-ratio"),
      require("@tailwindcss/typography"),
      require("@tailwindcss/forms"),
    ],
  }
```

You can then add a ! in front of the utility, as specified here: https://tailwindcss.com/docs/just-in-time-mode#built-in-important-modifier

In my case, I put it in front of the aspect ratio classes, like so:
`<div className="!aspect-w-3 aspect-h-2 sm:!aspect-w-4 sm:aspect-h-3">`

I still think this is a bit kludgey, but it works! Hopefully this will benefit future internet travelers.

**Comment by LekoArts** [comment]
Hi! Thanks for the issue.

For the develop/build mismatch you can try https://github.com/gatsbyjs/gatsby/discussions/28138 and we're working on getting it into the hands of everyone by default.
That the component overwrites custom styles from you is expected and how the CSS cascade works. We're not putting the CSS into a css file as that would mean an additional request, so it's either in a `<style>` tag or inline styles -- and those take precedence. Using `!important` is a well known workaround for these cases.

**Comment by sgarcia-dev** [comment]
Why is this closed? I'm having the same issue, and regardless of build/dev environment difference, the issue is caused by `gatsby-plugin-image` injecting it's styles later than we're able to do so via `gatsby-browser`. Thus, beating any custom CSS we add due to equal specificity but being located later. Shouldn't `gatsby-plugin-image` inject it's styles to the very top of the DOM tree to make this easier to override? @LekoArts
