### ISSUE TITLE
Gatsby new behind a proxy

### ISSUE THREAD

**Issue by HarrySystems** [gatsbyjs/gatsby#3396]
I'm trying to run the command `gatsby new tutorial-part-one https://github.com/gatsbyjs/gatsby-starter-hello-world` behind a proxy, and it's returning the following:
![image](https://user-images.githubusercontent.com/16313346/34517385-f44eb620-f061-11e7-9722-4bc635f92cf6.png)

**Comment by benjaminhoffman** [comment]
You can confirm it works when you are not behind a proxy?

**Comment by calcsam** [comment]
How did your original git clone of the gatsby repo succeed if your proxy cannot connect to Github?

**Comment by HarrySystems** [comment]
@calcsam it worked because I installed it via NPM.

**Comment by HarrySystems** [comment]
@benjaminhoffman I can't try to access it without the proxy as this computer is in the private network inside the company I work for.

**Comment by benjaminhoffman** [comment]
so strange.  cant say I know the answer but try:
- installing another repo from github.  does that work?
- installing one of the [gatsby starters](https://www.gatsbyjs.org/docs/gatsby-starters/).  does that work?
- installing another gatsby tutorial (part 1, 2, etc).  does that work?

in other words, let's try to narrow down the possible culprits.

**Comment by jaegz** [comment]
I know I've had trouble with `git://` on proxies. Try using https:// only with this command:
`git config --global url."https://".insteadOf git://`

**Comment by VinSpee** [comment]
similarly, this error occurs when trying to use a starter from a private git repo (even if I have access to it)

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by ambroiseRabier** [comment]
This issue is solved here https://www.gatsbyjs.org/docs/setting-up-gatsby-without-gatsby-new/. Took me quite a while to find that link...
