### ISSUE TITLE
gatsby-source-wordpress content images does not appear in develop

### ISSUE THREAD

**Issue by alexadark** [gatsbyjs/gatsby#33985]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

in the example repo if you write /test in the browser the images don't appear, but if you go to another page and go back, or go there through a  link then they appear 

### Reproduction Link

https://github.com/alexadark/gatsby-wp-sandbox

### Steps to Reproduce

1.clone the repo
2.yarn && gatsby develop
3.type the url  /test manually
...

### Expected Result

Images on the page should appear

### Actual Result

They don't appear

### Environment

```shell
System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.4 - ~/.nvm/versions/node/v14.17.4/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.4/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 95.0.4638.69
    Firefox: 94.0.1
    Safari: 14.1.2
  npmPackages:
    gatsby: ^4.1.5 => 4.1.5 
    gatsby-plugin-image: ^2.1.2 => 2.1.2 
    gatsby-plugin-manifest: ^4.1.3 => 4.1.3 
    gatsby-plugin-offline: ^5.1.3 => 5.1.3 
    gatsby-plugin-react-helmet: ^5.1.0 => 5.1.0 
    gatsby-plugin-sharp: ^4.1.3 => 4.1.3 
    gatsby-source-filesystem: ^4.1.2 => 4.1.2 
    gatsby-source-wordpress: ^6.1.2 => 6.1.2 
    gatsby-transformer-sharp: ^4.1.0 => 4.1.0 
  npmGlobalPackages:
    gatsby-cli: 4.0.0
```

**Comment by tiggeymone** [comment]
Same problem after updating to gatsby v4 and gatsby-source-wordpress >6

**Comment by graysonhicks** [comment]
I was unable to replicate this exactly.  The images *do* show when I go to the /test page, but *not* when I click on an image and go back to /test.

**Comment by graysonhicks** [comment]
Also, seeing this error in the console:

>react-dom.development.js:67 Warning: The tag < gwmw > is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.
    at gwmw
    at p
    at section
    at article
    at main
    at div
    at Layout (webpack-internal:///./src/components/layout.js:21:25)
    at BlogPostTemplate (webpack-internal:///./src/templates/blog-post.js:37:24)
    at PageRenderer (webpack-internal:///./.cache/page-renderer.js:23:29)

**Comment by graysonhicks** [comment]
Seeing this warning in the build logs, not sure if relevant:

>warn ./node_modules/gatsby-source-wordpress/dist/gatsby-browser.js
Attempted import error: 'createRoot' is not exported from 'react-dom' (imported as 'ReactDOM')

**Comment by graysonhicks** [comment]
The build warning above seems relevant when looking at this code:

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/gatsby-browser.ts#L35

**Comment by graysonhicks** [comment]
@wardpeet Looks like you and @TylerBarnes worked on that file for v4 ☝️  if you have any insights as to what might be happening.

**Comment by TylerBarnes** [comment]
Thanks for the repro @alexadark ! I'll need @wardpeet to confirm my fix is ok as I don't fully understand the code here but it seems to be working. A canary is available in `gatsby-source-wordpress@6.3.0-alpha-wordpress-image-hydration.5+633909e707`

**Comment by alexadark** [comment]
Thanks, @TylerBarnes and @wardpeet all works fine now :-)

**Comment by mrbjjackson** [comment]
Just to check - should this issue be fixed now? Because I'm seeing a very similar error on my site: When I load a page initially (or click refresh on a page) the images are loaded correctly, but if I navigate to a page containing images from another page, the images do not appear. This is only for the inline images in the Wordpress post content.

If this is a separate bug, I can open a new issue.

Any thoughts? Many thanks.

 ```
     "gatsby": "^4.2.0",
     "gatsby-plugin-image": "^2.2.0",
     "gatsby-plugin-sharp": "^4.2.0",
     "gatsby-source-wordpress": "^6.2.0",
     "gatsby-transformer-sharp": "^4.2.0",
 ```

**Comment by graysonhicks** [comment]
@mrbjjackson Are you using `react-html-parser` by chance?

**Comment by mrbjjackson** [comment]
@graysonhicks Thanks for your reply. I am using `react-html-parser`, yes. After reading your reply I tried removing it and my images are still not showing up. Is that something that was causing your issue?

FYI If I inspect the DOM, the images are all there as expected but they are not being shown.

**Comment by TylerBarnes** [comment]
@mrbjjackson wpgraphql.com had the same issue yesterday and it was due to `react-html-parser` stripping out the JSON script tags in html fields that are used to hydrate image components. 

https://github.com/wp-graphql/wpgraphql.com/pull/28/files

**Comment by mrbjjackson** [comment]
Just FYI I've narrowed the issue I was having down to me using Framer Motion to provide page transitions on my site. I've created a separate issue here: [https://github.com/gatsbyjs/gatsby/issues/34187](https://github.com/gatsbyjs/gatsby/issues/34187)

> Just to check - should this issue be fixed now? Because I'm seeing a very similar error on my site: When I load a page initially (or click refresh on a page) the images are loaded correctly, but if I navigate to a page containing images from another page, the images do not appear. This is only for the inline images in the Wordpress post content.
> 
> If this is a separate bug, I can open a new issue.
> 
> Any thoughts? Many thanks.
> 
> ```
>     "gatsby": "^4.2.0",
>     "gatsby-plugin-image": "^2.2.0",
>     "gatsby-plugin-sharp": "^4.2.0",
>     "gatsby-source-wordpress": "^6.2.0",
>     "gatsby-transformer-sharp": "^4.2.0",
> ```
