### ISSUE TITLE
[React 18] Various compatibility issues

### ISSUE THREAD

**Issue by mwskwong** [gatsbyjs/gatsby#34002]
### Preliminary Checks

- [x] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Since React 18 has entered the beta stage, indicating most, if not all breaking changes should have been settled at this point, I believe it is time for me to create this issue that has been here for two months.

**TL;DR** Despite Gatsby claiming to work with React 18, certain breaking changes are made in React in early October resulting in various compatibility issues.

**DEV Build**
1. `render` is used in some cases instead of `createRoot`
2. SSR is completely disabled

**PROD Build**
3. `Suspense` in React 18 has similar behavior to that of React 17 when using it with Gatsby. Components wrapped in `Suspense` are not SSRed. Instead, it is CSRed.

### Reproduction Link

https://github.com/mwskwong/gatsby-react-18

### Steps to Reproduce

1. Clone the `gatsby-starter-minimal` template
2. Install `react@beta` and `react-dom@beta`

You may switch to `react@18.0.0-alpha-7d38e4fd8-20210930` and `react@18.0.0-alpha-7d38e4fd8-20210930` just to observe the differences when using `Suspense`.

### Expected Result

1. `createRoot` will be used instead of `render`
2. SSR will be enabled in DEV build
3. `Suspense` will work in SSR.

### Actual Result

1. `render` is still used in some cases
2. CSR is used in DEV build
3. `Suspense` will render nothing in SSR.

See the deployments as follow:
[Using React 18 Beta](https://c42bc22b.gatsby-react-18.pages.dev/)
[Using React 18 Beta with `Suspense`](https://61802827.gatsby-react-18.pages.dev/) (the "Congratulations — you just made a Gatsby site! 🎉🎉🎉" heading is lazy-loaded)

### Environment

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Node: 16.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.10.0
  Browsers:
    Chrome: 94.0.4606.81
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.53)
  npmPackages:
    gatsby: ^4.2.0 => 4.2.0
```

**Comment by mwskwong** [comment]
Would mind updating me once the changes have been pushed to the `next` branch? Can't wait to try it out.

**Comment by graysonhicks** [comment]
Yea, this feels like something that used to work when I tried it a few months ago.  🤔

**Comment by wardpeet** [comment]
I'll test and fix when I reproduce. Dev will always be csr until we have dev ssr again

**Comment by mwskwong** [comment]
> I'll test and fix when I reproduce. Dev will always be csr until we have dev ssr again

If I'm not mistaken, Gatsby 4 + React 17 enables SSR by default in DEV build right? I believe there are some technical difficulties preventing this from happening for React 18?

**Comment by wardpeet** [comment]
Hey, DEV_SSR isn't available in v4 for now. We'll be fixing it somewhere in the coming weeks/month to make it a first class citizen.
