### ISSUE TITLE
Unable to bind to port 80 on macOS

### ISSUE THREAD

**Issue by simon-abbott** [gatsbyjs/gatsby#34014]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

MacOS has allowed unprivileged access to binding to all ports [since macOS 10.14](https://news.ycombinator.com/item?id=18302380), but only when binding to `0.0.0.0`.

### Reproduction Link

https://github.com/gatsbyjs/gatsby-starter-minimal

### Steps to Reproduce

1. Open any gatsby project on a mac
2. Run `gatsby develop --host 0.0.0.0 --port 80`

### Expected Result

It should bind to port 80

### Actual Result

It does not bind to port 80

### Environment

```shell
System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 96.0.4664.45
    Firefox: 94.0.1
    Safari: 14.1.2
```

**Comment by simon-abbott** [comment]
I saw #13880, but that was on Ubuntu, which still has privileged ports. This issue is on macOS.

It is possible to do this, as `detect-port` does have support for changing the hostname:

```js
const dp = require("detect-port");

dp({
  hostname: "0.0.0.0",
  port: 80,
  callback(err, port) {
    if (err) {
      console.err("Something went wrong");
      console.err(err);
    } else {
      console.log(`port: ${port}`);
    }
  },
});
```

**Comment by leithonenglish** [comment]
Hi @simon-abbott!

Sorry to hear you're running into an issue. I suggest trying a few different ports above 1000 because on you computer some other application may be using port `80`.

If you still having the issue on a different port please paste the error that you're seeing.

Thanks for using Gatsby! 💜

**Comment by simon-abbott** [comment]
@leithonenglish I can bind to other ports just fine. The issue is that gatsby is not passing the hostname along to `detect-port`, so it's incorrectly erroring. The only reason `--host 0.0.0.0 --port 80` doesn't work is because the `detect-port` call isn't being passed the hostname, so it's testing with the wrong interface.

This will also cause a bug where the user has two or more interfaces (which is completely valid, if uncommon), and is trying to bind to port X on the second interface while something else is bound to port X on the default one.

The fix is as shown above, just pass the hostname along to `detect-port`.

**Comment by simon-abbott** [comment]
Hey bot, please don't close this yet.

**Comment by simon-abbott** [comment]
Once again, still not resolved, please don't close.

**Comment by simon-abbott** [comment]
Still not fixed.

**Comment by simon-abbott** [comment]
Bump!

**Comment by simon-abbott** [comment]
Still not fixed.

**Comment by simon-abbott** [comment]
Bump.

**Comment by simon-abbott** [comment]
> This issue has gone quiet. Spooky quiet. 👻

Then I shall make noise 📣

**Comment by simon-abbott** [comment]
Aah! A ghost! (not fixed, don't close)

**Comment by simon-abbott** [comment]
@KyleAMathews If I remember this issue when I have some spare time to do so, sure!

**Comment by simon-abbott** [comment]
I haven't had time to fix it yet, but it's still relevant!

**Comment by the-redx** [comment]
I have the same issue, looking forward to a fix. @KyleAMathews @leithonenglish when will you fix it?

**Comment by LekoArts** [comment]
@the-redx Go ahead and put up a PR yourself :)
