### ISSUE TITLE
gatsby-plugin-mdx not calling function in gatsbyRemarkPlugin built from Typescript

### ISSUE THREAD

**Issue by watway** [gatsbyjs/gatsby#34015]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I'm attempting to use `gatsby-remark-shiki` with `gatsby-plugin-mdx` to remark code blocks, but the output is unchanged.  

I've had a look through the code for `gatsby-plugin-mdx` and I noticed that `get-source-plugins-as-remark-plugins.js` was recently changed from using an `interopDefault` function which handled if the module was a 'function' or an 'object', and if 'object' then use `exp['default']`.  The code now only handles the module being a 'function'.
```  // return list of remarkPlugins
  const userPluginsFiltered = gatsbyRemarkPlugins.filter(
    plugin => typeof plugin.module === `function`
  )
```

Debugging into this code I can see that the `gatsby-remark-shiki` plugin in being referenced, but the `module` is not a 'function', but an 'object' containing a `default` member, which is a function.

![image](https://user-images.githubusercontent.com/2321110/142334521-26d81b52-3d1e-49c1-a8b7-a9263baade4d.png)

Looking then at the `gatsby-remark-shiki` plugin, which is written in Typescript, the generated code uses `exports.default = index`.  I also tried another plugin `@enpitsulin/gatsby-remark-shiki` which is also written in Typescript, and it has the same problem.

### Reproduction Link

https://github.com/watway/gatsby-mdx-with-shiki

### Steps to Reproduce

1. create basic gatsby site
2. follow adding the `gatsby-plugin-mdx` instructions, including adding `gatsby-source-filesystem`
3. follow adding the `gatsby-remark-shiki` instructions
4. add mdx file to the `pages` folder which contains a code block
5. build the site and navigate to the page
6. style of the code block will look no different to other text around it
...

### Expected Result

The style of the javascript block should be changed
![image](https://user-images.githubusercontent.com/2321110/142332298-b33cecf6-58ea-40a0-9729-a649b7b78d76.png)

### Actual Result

The style of the javascript block remains unchanged
![image](https://user-images.githubusercontent.com/2321110/142332221-577ccdcf-304b-4284-9638-d53b0a39f06b.png)

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 96.0.4664.45
    Safari: 14.1.1
  npmPackages:
    gatsby: ^4.2.0 => 4.2.0 
    gatsby-plugin-mdx: ^3.2.0 => 3.2.0 
    gatsby-remark-shiki: ^0.3.0 => 0.3.0 
    gatsby-source-filesystem: ^4.2.0 => 4.2.0
```

**Comment by jlkiri** [comment]
As the author of `gatsby-remark-shiki` I probably should mention that the plugin was created for Gatsby 2

**Comment by iChenLei** [comment]
This issue had been fixed ? @watway

**Comment by watway** [comment]
@iChenLei no the issue has not been fixed yet.  I just ran though the steps again and the problem still exists.

**Comment by N0K0** [comment]
Hi! Just bumped into this issue as its affecting me too :/
Is there any workarounds or the likes that works? :D

**Comment by watway** [comment]
Please keep this open.  I may try and open a PR to move this forward.
