### ISSUE TITLE
`createNodeField` does not work on `SitePage` or other internal Gatsby types in v4

### ISSUE THREAD

**Issue by eligundry** [gatsbyjs/gatsby#34027]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi all, Gatsby 4 seems to have introduced a regression around `createNodeField` in `gatsby-node.js` when attaching fields to `SitePage` nodes (and probably other Gatsby datatypes).

A little bit of background: I am attaching Git last modified timestamps to the `sitePages` nodes in a script on my site. I am able to get the component in `onCreateNode`, run a Git command for last commit, and attach the timestamp to the `SitePage` node so that it can be used as a `<lastmod />` in my sitemap.

This worked perfectly fine in Gatsby 3 but after to Gatsby 4, it seems that I cannot add fields to this data type. Based upon my experimentation, I cannot add any fields to any internal Gatsby types, like `Site`, `SiteBuildMetadata`, etc.

### Reproduction Link

https://github.com/eligundry/gatsby-starter-minimal/pull/1

### Steps to Reproduce

1. Add `gatsby-node.js` to minimal site
2. Add a `onCreateNode` handler that runs `createNodeField` on all nodes created
3. Run the GraphQL query explorer and see that the fields are not there

Alternately, check out the branch in the reproduction link and run `npm ci && npm run build`.

### Expected Result

https://github.com/eligundry/gatsby-starter-minimal/pull/2

I reverted this example to Gatsby 3 and the fields show up fine and the site builds.

### Actual Result

```
 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "fields" on type "SitePage".

If you don't expect "fields" to exist on the type "SitePage" it is most likely a typo.
However, if you expect "fields" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your
development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which
fields you can query and what shape they have
- You want to optionally use your field "fields" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add
it to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the
mentioned "dummy content". Visit our docs to learn how you can define the schema for "SitePage":
https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization#creating-type-definitions

File: src/pages/index.js:189:7

failed extract queries from components - 0.028s
```

The build fails because no field was added.

### Environment

```shell
System:
    OS: macOS 11.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.10.0 - /var/folders/4y/8gkljs2x08ddzs4mhkvz4d_h0000gn/T/fnm_multishells/75203_1637281294963/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.1 - /var/folders/4y/8gkljs2x08ddzs4mhkvz4d_h0000gn/T/fnm_multishells/75203_1637281294963/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 96.0.4664.55
    Firefox: 94.0.1
    Safari: 15.0
  npmPackages:
    gatsby: ^4.2.0 => 4.2.0 
  npmGlobalPackages:
    gatsby-source-ical: 0.0.0-development
```

### Config Flags

Nope

**Comment by graysonhicks** [comment]
I can't speak to the `createNodeField` bug itself, but you should be able to add this via [createResolvers](https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization/#createresolvers-api):

```
exports.createResolvers = ({ createResolvers }) => {
  const resolvers = {
    SitePage: {
      gitLastModified: {
        resolve(source, args, context, info) {
          // shouldn't need args, context, or info
          // get timestamp same way you are now
          // use `source` to get information on the page in question
          const lastModified = gitApi(source.foo);
          return lastModified
        },
      },
    },
  }
  createResolvers(resolvers)
}
```

**Comment by LekoArts** [comment]
Hi!

This is expected behavior as with v4 these types no longer use inference (the `@dontInfer`):

https://github.com/gatsbyjs/gatsby/blob/27cf7e7b0416f5559438ff296232afb2a7237654/packages/gatsby/src/schema/types/built-in-types.ts#L103-L133

This is mentioned here: https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v3-to-v4/#changes-to-built-in-types

You'll need to use the `createSchemaCustomization` API to add your fields explicitly to `type SitePage`.

**Comment by eligundry** [comment]
Ah okay, this makes sense. I figured it had something to do with that. I'm very pleased that I'm going to be able to do this, so thanks both of you!

**Comment by karlhorky** [comment]
@eligundry Did you come up with a solution here using `createSchemaCustomization`?

**Comment by karlhorky** [comment]
I wrote the following for our MDX frontmatter fields, the build seems to be running now...

```js
// gatsby-node.js
exports.createSchemaCustomization = ({ actions }) => {
  const { createTypes } = actions;

  createTypes(`
    type SitePage implements Node {
      fields: Fields
    }
    type Fields {
      title: String
      navTitle: String
    }
  `);
};
```

This is what we had before, which worked with Gatsby v3 without the changes above:

```js
exports.onCreateNode = async ({ node, actions: { createNodeField } }) => {
  // Add custom properties from front matter
  if (node.internal.type === 'SitePage') {
    createNodeField({
      node,
      name: 'title',
      value:
        node.context &&
        node.context.frontmatter &&
        node.context.frontmatter.title,
    });
    createNodeField({
      node,
      name: 'navTitle',
      value:
        node.context &&
        node.context.frontmatter &&
        node.context.frontmatter.navTitle,
    });
  }
};
```

**Comment by eligundry** [comment]
@karlhorky yes, I did! If you are looking for a reference solution, I added a `fields` schema like so:

https://github.com/eligundry/eligundry.com/blob/4de32d88ca8f9b3b64de944ef352d9440abf573e/gatsby/config/gatsby-node.ts#L160-L183

**Comment by karlhorky** [comment]
Cool, hopefully these will be useful for others as they have to upgrade too. My solution above was really a bunch of guessing... 😄
