### ISSUE TITLE
Trailing slashes cannot be forced

### ISSUE THREAD

**Issue by lgraubner** [gatsbyjs/gatsby#3402]
## Description

Trailing slashes seem to be optional. I want to force trailing slashes and do so with Netlify. But once the initial page is displayed react-router takes over and the pages are reachable with and without `/`. How can I redirect to the trailing slash version? Could not find any examples, just the remove trailing slashes plugin.

### Environment

Gatsby version: 1.9.149
Node.js version: 9.3.0
Operating System: MacOS

**Comment by benjaminhoffman** [comment]
What about reverse engineering the remove trailing slash plugin to do what you want?  Specifically, updating this line? https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-remove-trailing-slashes/gatsby-node.js#L2

Not sure if that will work as expected but just a thought.  Worth a try.

**Comment by lgraubner** [comment]
Thanks for your idea, I already tried this. But this plugin is not working for me at all, even as it is. I don't know how it's supposed to work, doesn't make sense to me.

**Comment by benjaminhoffman** [comment]
@lgraubner strange bc I've experienced the same.  I think there may be something wrong? https://twitter.com/benhoffman_/status/934497974553595909

**Comment by ryanwiemer** [comment]
@lgraubner or @benjaminhoffman any luck with this? 

I chose not to do trailing slashes on my website but I noticed an issue whenever a slash got accidentally added to the URL. The slug would just get appended to the URL for example `www.example.com/page1/page2`. This is particularly a problem when Facebook mysteriously decides to add a trailing slash when I share a link. 

Should this be resolved at the Netlify level perhaps? I'm not sure the best way to handle this either but the `gatsby-plugin-remove-trailing-slahes` did nothing for me either. I don't really care if links have a slash or not but I feel like I should stick with one and force it but I'm not sure how.  

Appreciate any advice if you have any. 

Thanks,
Ryan

**Comment by lgraubner** [comment]
Sadly I still don't have a real solution. I can't even find a Netlify Option to force trailing slashes (or the opposite). The only thing I did was adding a canonical with trailing slash as well as making sure all internal link have the trailing slash.

```javascript
<link
  rel="canonical"
  href={`https://larsgraubner.com${location.pathname.replace(/\/?$/,  '/')}`}
/>
```

**Comment by ryanwiemer** [comment]
@lgraubner gotcha. Thanks for responding. 

@KyleAMathews any advice for this particular issue of whether or not to have a trailing slash and the proper method for forcing that? I noticed on https://www.gatsbyjs.org/ all URLs have a trailing slash and it is forced. 

It would be great to come to some type of consensus especially since if you mix and match it has negative effects on Gatsby powered sites.

**Comment by joakimlustig** [comment]
I have problems with this as well, gatsby-plugin-remove-trailing-slahes doesn't seem to do anything about the urls. I'm also using gatsby-plugin-canonical-urls to generate canonical urls, and that plugin creates canonical urls without trailing slash for my blog posts.

So I have links that automatically goes to the posts with a trailing slash added, and canonical urls generated without trailing slash. I just noticed that this actually makes my blog posts non-indexable by google.

**Comment by lgraubner** [comment]
I discovered that if I disable `gatsby-plugin-offline` (which I'm using) it seems to work.

The reason is the default `navigateFallbackWhitelist` regex:

```javascript
{
    resolve: 'gatsby-plugin-offline',
    options: {
        navigateFallbackWhitelist: [/^.*(?!\.\w?$)/],
    }
}
```

This basically says the service worker should handle everything but URL's ending with a file extension. Therefore it's not reaching Netlify to rewrite it to a trailing slash. Solution is simply adjusting the regex:

```javascript
options: {
    navigateFallbackWhitelist: [/\/$/]
}
```

Seems to work fine for me.
