### ISSUE TITLE
Issue with garsby-plugin-image peer dependencies

### ISSUE THREAD

**Issue by m5kr1pka** [gatsbyjs/gatsby#34039]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Upgrading to gatsby, gatsby-shopify-source, gatsby-plugin-image to latest versions there is an peer dependency issue due to bad definition of peer dependency (I think) or intentional. Should be ">1.1.0" which covers major releases instead of "^1.1.0" which only subject to version 1 minor releases following SemVer, for testing purpose: https://semver.npmjs.com/

```
npm WARN Could not resolve dependency:
npm WARN peer gatsby-plugin-image@"^1.1.0" from gatsby-source-shopify@6.2.0
```

### Reproduction Link

none

### Steps to Reproduce

- clone repo: https://github.com/gatsbyjs/gatsby-starter-shopify
- upgrade package dependencies to latest
- NPM install fails

### Expected Result

No breaking errors.

### Actual Result

```
using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: gatsby-source-shopify@6.2.0
npm WARN Found: gatsby-plugin-image@2.2.0
npm WARN node_modules/gatsby-plugin-image
npm WARN   gatsby-plugin-image@"^2.0.0" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer gatsby-plugin-image@"^1.1.0" from gatsby-source-shopify@6.2.0
npm WARN node_modules/gatsby-source-shopify
npm WARN   gatsby-source-shopify@"^6.2.0" from the root project
npm WARN 
npm WARN Conflicting peer dependency: gatsby-plugin-image@1.14.2
npm WARN node_modules/gatsby-plugin-image
npm WARN   peer gatsby-plugin-image@"^1.1.0" from gatsby-source-shopify@6.2.0
npm WARN   node_modules/gatsby-source-shopify
npm WARN     gatsby-source-shopify@"^6.2.0" from the root project
````

### Environment

```shell
System:
    OS: macOS 12.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 96.0.4664.55
    Safari: 15.1
  npmPackages:
    gatsby: ^4.2.0 => 4.2.0
    gatsby-plugin-gatsby-cloud: ^4.2.0 => 4.2.0
    gatsby-plugin-google-analytics: ^4.2.0 => 4.2.0
    gatsby-plugin-image: ^2.0.0 => 2.2.0
    gatsby-plugin-react-helmet: ^5.2.0 => 5.2.0
    gatsby-plugin-sharp: ^4.2.0 => 4.2.0
    gatsby-plugin-sitemap: ^5.2.0 => 5.2.0
    gatsby-source-filesystem: ^4.2.0 => 4.2.0
    gatsby-source-shopify: ^6.2.0 => 6.2.0
    gatsby-transformer-sharp: ^4.2.0 => 4.2.0
  npmGlobalPackages:
    gatsby-plugin-firebase: 0.2.0-beta.5
```

### Config Flags

FAST_DEV: true

**Comment by thomHayner** [comment]
I received a similar error message when trying to install gatsby-plugin-image and gatsby-source-shopify on an existing project.

I was able to restart the project from scratch using the ```npm init gatsby``` quickstart and it worked, but this issue still exists if you try to install shopify outside of the initial quickstart setup
