### ISSUE TITLE
Deprecated dependencies on `gatsby-source-graphql`

### ISSUE THREAD

**Issue by joselcvarela** [gatsbyjs/gatsby#34042]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Using latest version of `gatsby-source-graphql` (4.2.0) causes an error to be thrown on running `develop`.

The error is:
```sh
npm run develop

> gatsby@1.0.0 develop
> gatsby develop

success open and validate gatsby-configs, load plugins - 0.109s
success onPreInit - 0.001s

 ERROR 

(node:56888) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./public/" in the "exports" field module resolution of the package at
.../gatsby/node_modules/extract-files/package.json.
Update this package.json to use a subpath pattern like "./public/*".
(Use `node --trace-deprecation ...` to show where the warning was created)

```

A further investigation led me to see that the issue comes from `extract-files@9` but is solved in 10.
I could found the root of this issue and it seems is a chain of dependencies issue, unfortunately.
The package `gatsby-source-graphql` is using `@graphql-tools/links@7.1.0`.
And `@graphql-tools/links@7.1.0` is using `apollo-upload-client@14.1.3`. In this version we can see `apollo-upload-client` is using `extract-files@9.0.0`.
Although the issue you reported is solved in `extract-files@10.0.0`, which is also solved in `apollo-upload-client@15.0.0`. ​https://github.com/jaydenseric/extract-files/issues/18

Since `@graphql-tools/links` is now on `8.2.1` and is using `apollo-upload-client@^16.0.0` I believe an upgrade on dependencies should solve the issue.

### Reproduction Link

https://github.com/joselcvarela/gatsby-source-graphql-issue

### Steps to Reproduce

1. Install `npm install gatsby-source-graphql`
2. Configure `plugins` in `gatsby.node.js` to use `gatsby-source-graphql`
3. Run `npm run develop` and the error appears on the console

### Expected Result

No error to show up.

### Actual Result

An error is shown on running `npm run develop`.

### Environment

```shell
System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 95.0.4638.69
    Edge: 95.0.1020.53
    Safari: 15.1
  npmPackages:
    gatsby: ^4 => 4.2.0 
    gatsby-source-graphql: ^4.2.0 => 4.2.0 
  npmGlobalPackages:
    gatsby: 4.2.0
```

**Comment by LekoArts** [comment]
Hi!

Since I couldn't use your reproduction as I don't have any directus running I was simply adding the plugin to the config and used the SWAPI endpoint from the README. I don't get any errors during `gatsby develop` or `gatsby build`. Please post a [minimal reproduction][reproduction] which shows this. Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by laurenzcodes** [comment]
I am also having this warning. It's related to the `@graphql-tools/links` package being outdated (the newer (v8.2.1) one uses a more recent version of `extract-files` (11.0.0) which might fix the bug.

**Comment by joselcvarela** [comment]
Hello @LekoArts 
Sorry for not giving a proper reproduction. As you mentioned, I have updated to use the Swapi url, but I still have the issue:

![image](https://user-images.githubusercontent.com/14039341/143067080-fd026802-a26a-4bb8-8c7d-366349a15757.png)

**Comment by LekoArts** [comment]
I'm still not seeing this on my end, but this might not be the normal behavior for others then. It's a warning and things will still work, so I'm not considering this a bug. Feel free to put up a PR updating the required dependencies to get rid of this warning.

**Comment by pranav0281999** [comment]
@LekoArts the warning only shows up in the latest npm and node version. I was able to reproduce it with the versions provided by @joselcvarela. I am creating a PR updating the dependency.

**Comment by pozda** [comment]
Apple silicon m1 with: 
- node v17.0.1 and npm v8.1.0
- gatsby v4.4.0
- gatsby-source-graphql v4.4.0

having the same issue when running `npm start` on gatsby that I initiated today with gatsby init

`Error: Package subpath './public/extractFiles' is not defined by "exports" in /myMachineFolders/node_modules/apoll
  o-upload-client/node_modules/extract-files/package.json`
  
nvm use v16.13.1 resolves this issue locally, but when trying to deploy on vercel this weird issue pops-up:

`error Error in "/vercel/path0/node_modules/gatsby-source-graphql/gatsby-node.js": Cannot find module '/vercel/path0/node_modules/extract-files/public/extractFiles'`

**Comment by vinayakweb-prog** [comment]
Apple silicon m1 with:

node v17.0.1 and npm v8.1.0
gatsby v4.4.0
gatsby-source-graphql v4.4.0
having the same issue when running npm start on gatsby that I initiated today with gatsby init

Error: Package subpath './public/extractFiles' is not defined by "exports" in /myMachineFolders/node_modules/apoll o-upload-client/node_modules/extract-files/package.json

nvm use v16.13.1 resolves this issue locally, but when trying to deploy on vercel this weird issue pops-up:

error Error in "/vercel/path0/node_modules/gatsby-source-graphql/gatsby-node.js": Cannot find module '/vercel/path0/node_modules/extract-files/public/extractFiles'

**Comment by karunakaran186** [comment]
this issue is slight tricky do  kindly solve soon @gatsbybot

**Comment by carolinmaisenbacher** [comment]
I ran into the same error and downgrading to node@16 worked.

**Comment by presto2116** [comment]
I am still getting this error locally and on netlify and gatsby cloud. downgrading to v16.13.2 didn't help since we have been on node v16.13.0. 
I attempted downgrading from gatsby-source-graphql v4.4.0 => v4.2.0
I also attempted upgrading to v4.5.2

Neither removed the error in the build logs

**Comment by anyav77** [comment]
I don't know if it's related, but I'm getting an error on pulling images from 8base after updating to Gatsby 4:
<img src={article.cover_thumbnail.shareUrl + "?download=true"} />

**Comment by AshuuDixit** [comment]
Steps to Reproduce


Install npm install gatsby-source-graphql
Configure plugins in gatsby.node.js to use gatsby-source-graphql
Run npm run develop and the error appears on the console

**Comment by LekoArts** [comment]
Please try out `gatsby-source-graphql@4.11.0-next.1` and report back. Thanks!

**Comment by pascal-lauener-livinguard** [comment]
gatsby-source-graphql@4.11.0-next.1  is solving the issue for me

**Comment by hood** [comment]
can this get backported for v3 too?
