### ISSUE TITLE
[gatsby-transformer-remark] Using remark plugins causes build to crash

### ISSUE THREAD

**Issue by cameronmcefee** [gatsbyjs/gatsby#34055]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When trying to load plugins, gatsby-transformer-remark fails to resolve the plugins and throws an error. [I believe this is the culprit](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/src/create-schema-customization.js#L44), where in Gatsby 4 it tries to assign `resolvedPlugin` to `plugin.module` which is undefined.

### Reproduction Link

https://github.com/cameronmcefee/gatsby-transformer-remark-bug

### Steps to Reproduce

1. Clone the reproduction example and install dependencies (`npm i` etc).
2. `gatsby build`

### Expected Result

A clean build

### Actual Result

"gatsby-transformer-remark" threw an error while running the createSchemaCustomization lifecycle:

Cannot read property 'createSchemaCustomization' of undefined

  TypeError: Cannot read property 'createSchemaCustomization' of undefined
  
  - create-schema-customization.js:47 
    [gatsby-starter-default]/[gatsby-transformer-remark]/create-schema-customization.js:47:31
  

### Environment

```shell
System:
    OS: macOS 11.5.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 96.0.4664.55
    Safari: 14.1.2
  npmPackages:
    gatsby: ^4.2.0 => 4.2.0 
    gatsby-plugin-gatsby-cloud: ^4.2.0 => 4.2.0 
    gatsby-plugin-image: ^2.2.0 => 2.2.0 
    gatsby-plugin-manifest: ^4.2.0 => 4.2.0 
    gatsby-plugin-offline: ^5.2.0 => 5.2.0 
    gatsby-plugin-react-helmet: ^5.2.0 => 5.2.0 
    gatsby-plugin-sharp: ^4.2.0 => 4.2.0 
    gatsby-remark-autolink-headers: ^5.2.0 => 5.2.0 
    gatsby-source-filesystem: ^4.2.0 => 4.2.0 
    gatsby-transformer-remark: ^5.2.0 => 5.2.0 
    gatsby-transformer-sharp: ^4.2.0 => 4.2.0
```

**Comment by LekoArts** [comment]
Hi!

I've cloned your repo, ran `yarn` and `yarn build` (since I don't use npm) and it successfully built:

![image](https://user-images.githubusercontent.com/16143594/142995653-2ba2ee2a-7963-42c9-bf1b-c6894b091dc1.png)

Your `package-lock.json` doesn't contain the remark plugins you installed since you used `yarn` to install that. If you now use npm it won't install it is my guess.

**Comment by cameronmcefee** [comment]
Hmm, you're correct, though the yarn/npm discrepancy was user error in creating the example. I swear it initially shared the same problem that my actual project has. I must have something else at play in my main project. I'll close for now, sorry for the noise.

**Comment by cameronmcefee** [comment]
I found the issue, which I'll leave here for posterity. I'm in the process of upgrading to Gatsby 4, with a lot of out of date plugins. My gatsby-config.json still had an old config option in it:

```javascript
{
  resolve: `gatsby-transformer-remark`,
  options: {
    pedantic: false,
    plugins: [
      // ...
    ]
  }
}
```

There was a warning about this unrecognized option that I missed in the noisy logs:

```
warn Warning: there are unknown plugin options for "gatsby-transformer-remark": pedantic
```

While I'd expect this would just be safely ignored and the build would still be successful, when this value is present it causes something downstream to break. Removing it resolves the issue. In my book this is a bug, but since it's a bug in a scenario I shouldn't have been in the first place, I'm going to leave this issue closed.
