### ISSUE TITLE
embed snippet inside details html tag does not work

### ISSUE THREAD

**Issue by mac2000** [gatsbyjs/gatsby#34065]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Imagine you have a few repeatable code samples you wish to embed into the page, but do not want them to take all the space

There is an detail HTML tag for such scenarios, e.g.:

```md
<details>
<summary>sample1.js</summary>
`embed:sample1.js`
</details>

<details>
<summary>sample2.js</summary>
`embed:sample2.js`
</details>
```

Which should be rendered to something like:

<details>
<summary>sample1.js</summary>
<pre>sample1.js contents</pre>
</details>

<details>
<summary>sample2.js</summary>
<pre>sample1.js contents</pre>
</details>

Here is [repro commit](https://github.com/mac2000/gatsby-embed-snippet-repro/commit/c45914c02bcd9c1cf19daaacae99666981cbf3bd)

Also I'm not sure if it is at all related to gatsby and its plugins or to libraries used to work with markdown, not sure here but need to strat from somewhere

### Reproduction Link

https://github.com/mac2000/gatsby-embed-snippet-repro

### Steps to Reproduce

```bash
gatsby new bug-repro https://github.com/gatsbyjs/gatsby-starter-minimal

cd bug-repro

npm i gatsby-remark-embed-snippet gatsby-remark-prismjs gatsby-source-filesystem gatsby-transformer-remark prismjs

tee gatsby-config.js > /dev/null <<EOT
module.exports = {
  siteMetadata: {
    siteUrl: `https://www.yourdomain.tld`,
  },
  plugins: [
    {
      resolve: "gatsby-transformer-remark",
      options: {
        plugins: ["gatsby-remark-embed-snippet", "gatsby-remark-prismjs"],
      },
    },
    {
      resolve: "gatsby-source-filesystem",
      options: {
        name: "pages",
        path: "./src/pages/",
      },
      __key: "pages",
    },
  ],
};
EOT

tee src/pages/demo.md > /dev/null <<EOT
---
title: demo
slug: demo
---

# demo

demo

<details>
<summary>index.js</summary>
`embed:index.js`
</details>
EOT

npm run develop

curl -s 'http://localhost:8000/___graphql' -H 'Content-Type: application/json' -d '{"query":"{ allMarkdownRemark { nodes { html } } }","variables":null}' | jq -r ".data.allMarkdownRemark.nodes[0].html" | grep 'embed:index.js'
```

### Expected Result

grep should not find `embed:index.js`

### Actual Result

grep found `embed:index.js`

### Environment

```shell
System:
  OS: macOS 12.0.1
  CPU: (8) arm64 Apple M1
  Shell: 5.1.12 - /opt/homebrew/bin/bash
Binaries:
  Node: 14.18.1 - /opt/homebrew/opt/node@14/bin/node
  Yarn: 1.22.17 - /opt/homebrew/bin/yarn
  npm: 6.14.15 - /opt/homebrew/opt/node@14/bin/npm
Languages:
  Python: 2.7.18 - /usr/bin/python
Browsers:
  Chrome: 96.0.4664.45
  Safari: 15.1
npmPackages:
  gatsby: ^4.2.0 => 4.2.0
  gatsby-remark-embed-snippet: ^7.2.0 => 7.2.0
  gatsby-remark-prismjs: ^6.2.0 => 6.2.0
  gatsby-source-filesystem: ^4.2.0 => 4.2.0
  gatsby-transformer-remark: ^5.2.0 => 5.2.0
```

### Config Flags

no flags used

<details>
<summary>gatsby-config.js</summary>
<pre>
module.exports = {
  siteMetadata: {
    siteUrl: `https://www.yourdomain.tld`,
  },
  plugins: [
    {
      resolve: "gatsby-transformer-remark",
      options: {
        plugins: ["gatsby-remark-embed-snippet", "gatsby-remark-prismjs"],
      },
    },
    {
      resolve: "gatsby-source-filesystem",
      options: {
        name: "pages",
        path: "./src/pages/",
      },
      __key: "pages",
    },
  ],
};
</pre>
</details>

**Comment by LekoArts** [comment]
Hi!

You need to have paragraphs around the tags as otherwise the parser can't understand it:

![image](https://user-images.githubusercontent.com/16143594/143209088-c66c3348-9216-4daa-a525-a247dee14e32.png)

So this works:

```md
<details>
<summary>index.js</summary>

`embed:index.js`

</details>
```

**Comment by mac2000** [comment]
@LekoArts indeed, thank you for example it works as expected, hopefully will help someone in future

PS: seems like it **must** be exactly:

```md
<details>
<summary>index.js</summary>

`embed:index.js`

</details>
```

nothing else won't work (e.g. trying to put different tags instead of blank lines)
