### ISSUE TITLE
Wrapping links have broken style

### ISSUE THREAD

**Issue by jsimplicio** [gatsbyjs/gatsby#34090]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

While reading Gatsby docs on mobile, I noticed that when links wrap, the style breaks as in the image below.
 
This is reproducible in all browsers, mobile and desktop in responsive view.

1. Open a page that has a long link that will wrap on mobile, such as [Quick Start](https://www.gatsbyjs.com/docs/quick-start/)
2. View page in mobile
3. Scroll down to the long, wrapping link, in this example "Install and configure additional plugins"

<img width="367" alt="broken style link" src="https://user-images.githubusercontent.com/7318958/143799251-65d326da-0d1b-4c8b-8ce9-4184c36a172a.png">

### Steps to Resolve this Issue

1. Declaring `display: inline` fixes this.

**Comment by LekoArts** [comment]
Thanks, I created an internal ticket for this to get fixed :)
