### ISSUE TITLE
Can I delete a path in onPostBuild?

### ISSUE THREAD

**Issue by aaronsky** [gatsbyjs/gatsby#3414]
I have a page that I'm using as the basis for a build task that I'm performing in onPostBuild. I do not want this page to be accessible in a production build as I am considering it to be a build artifact for all intents and purposes. Is the best practice here to just delete the file/directory for this path, or is there something else or additional I should be doing?

**Comment by calcsam** [comment]
You should do whatever makes sense for your project, there's not really a "best practice" here -- different people solve this problem different ways. For example, chiedo did this kind of post-processing (no deletions tho) in a separate file for the AMP starter: https://github.com/chiedo/gatsby-amp-starter-blog/blob/master/ampify.js

**Comment by aaronsky** [comment]
Okay, that's good to know. Thanks for getting back to me!

The post processing step is already done, I just need to figure out what to do to disallow this path. I may end up just creating a redirect since I'm on Netlify.
