### ISSUE TITLE
formalize API for hooking into page load lifecycle...

### ISSUE THREAD

**Issue by busticated** [gatsbyjs/gatsby#3415]
looking at the  [gatsby-plugin-nprogress](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-nprogress) plugin, i noticed that it relies on internal events - e.g.

    window.___emitter.on(`onDelayedLoadPageResources`, ...)

it would be nice to expose an official public API to hook into the page load lifecycle - something like: `onPageLoadStart`, `onPageLoaded`, `onPageLoadDelayed` but ¯\_(ツ)_/¯

my motivation being that i would like to create my own variant of the gatsby-plugin-nprogress plugin (but one that does not use nprogress lib)

### Environment

Gatsby version: 1.9.149
Node.js version: 8.9.3
Operating System: macOS 10.13.2

**Comment by calcsam** [comment]
Interesting idea -- are there any other use cases that come to mind? A quick search through this repo seems to show the nprogress plugin as the only one using `window.___emitter.on(` page load events.

**Comment by busticated** [comment]
@calcsam nothing beyond what i cited. i realize there's some overlap w/ the `gatsby-browser.js` APIs and perhaps some of the [page transition stuff](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-page-transitions).

at the moment, i just have a _component_ that i render in my main layout that hooks into the `onDelayedLoadPageResources` and `onPostLoadPageResources` events to draw progress.

perhaps a more general way to think about it is: how do _components_ hook into the page load lifecycle?

thanks for taking a look 👍

**Comment by KyleAMathews** [comment]
@busticated we're working on an API for delayed load https://github.com/gatsbyjs/gatsby/issues/3368 Would love to hear any of your thoughts there.

Other loading APIs make sense too.

Question is how to pass the data to components as right now they're just for plugins. Perhaps we could pass some sort of observable object into layout/page components.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
