### ISSUE TITLE
Runtime errors on Cloud 9

### ISSUE THREAD

**Issue by kosirm** [gatsbyjs/gatsby#3416]
## Description
Running fresh gatsby site on Cloud 9 with this command: gatsby develop -H $IP -p $PORT
### Environment
Gatsby version: 1.1.28
Node.js version:  8.9.4 (with 6.11.2 same result)
Operating System: Ubuntu

### Problem:
Console says it's all cool, but... 
- Live reload is non-working.
- Site works ok, but there are some errors in console:

> Uncaught Error: The error you provided does not contain a stack trace.
>     at parseError (index.js:2369)
>     at getStackFrames (index.js:2262)
>     at crashWithFrames (index.js:1926)
>     at index.js:1944
>     at rejectionHandler (index.js:2040)
> gatsby-infocube.c9users.io/:1 Uncaught (in promise) DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
> 0.0.0.0:8080/__webpack_hmr Failed to load resource: net::ERR_ADDRESS_INVALID
> 

Thanks in advance for any hint!

**Comment by calcsam** [comment]
This looks like a CORS issue with hot reloading on Cloud9 -- you need to set up some proxying:

https://community.c9.io/t/webpack-hot-reload-not-working/4383/2
https://community.c9.io/t/hot-module-reloading-with-browserify-watchify/1347/8

**Comment by kosirm** [comment]
Thanks, I'm aware of that it's not a Gatsby problem, I've searched all these topics before posting here...
Did I mention that I'm total Gatsby beginner? 😄
I just don't know how to tell webpack to use other port or host or something...
