### ISSUE TITLE
Missing `basePath` documentation. 

### ISSUE THREAD

**Issue by moonmeister** [gatsbyjs/gatsby#34175]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

https://github.com/gatsbyjs/gatsby/blob/91187dacdab45034c9ce4a1aa9f7018eb3bb1049/packages/gatsby/src/utils/api-runner-node.js#L379-L380

The `basePath` property made available to `onPostBuild` is completely undocumented. It seems this is simply the `pathPrefix` value with is super confiusing is given there is the other `pathPrefix` value. But that contains asset prefix if the asset prefix is set. The point is, this is all very confusing and undocumented. 

Bugs like https://github.com/gatsbyjs/gatsby/issues/34010 and https://github.com/gatsbyjs/gatsby/issues/25207 could be helped with some propper docs it seems. 

I'll add there is a general lack of reference documentation around the resources passed into  different APIs. https://www.gatsbyjs.com/docs/reference/config-files/gatsby-node/#onPostBuild contains no inofrmation. We're all left guessing for the most part. https://www.gatsbyjs.com/docs/reference/config-files/node-api-helpers/ is slightly helpful but contains confusing duplicate entries for things like `reporter` and is incomplete when it comes to things like `basePath`. Also the second link is hard to find when you lookup a individual API. 

### Steps to Resolve this Issue

1. Document API and differences between it and `pathPrefix`
2. Document what kind of scenarios you want to use one or the other when building plugins.
3. Party time. 🥳

**Comment by moonmeister** [comment]
I'll note https://www.gatsbyjs.com/docs/reference/config-files/node-api-helpers/#pathPrefix seems straight wrong. cause it also adds the `assetPrefix` and that's not clear.

**Comment by LekoArts** [comment]
Thanks, we'll get this documented! :)
