### ISSUE TITLE
Building static HTML failed for path "/infographics"

### ISSUE THREAD

**Issue by CeliaDagorne** [gatsbyjs/gatsby#34189]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

**gatsby build:**
failed Building static HTML for pages - 1.118s

 ERROR #95313

Building static HTML failed for path "/infographics"
**_(sometimes show other dynamics paths )_**

See our docs page for more info on this error: https://gatsby.dev/debug-html

  1 | var setPrototypeOf = require("./setPrototypeOf.js");
  2 |
> 3 | function _inheritsLoose(subClass, superClass) {
    | ^
  4 |   subClass.prototype = Object.create(superClass.prototype);
  5 |   subClass.prototype.constructor = subClass;
  6 |   setPrototypeOf(subClass, superClass);

  WebpackError: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnin
  gs.

  - inheritsLoose.js:3
    [gatsby-getting-started-tutorial]/[@babel]/runtime/helpers/inheritsLoose.js:3:1

  - static-entry.js:299
    gatsby-getting-started-tutorial/.cache/static-entry.js:299:22

  - utils.js:54
    [gatsby-getting-started-tutorial]/[@gatsbyjs]/reach-router/lib/utils.js:54:1

not finished Caching JavaScript and CSS webpack compilation - 9.901s
not finished Caching HTML renderer compilation - 1.186s

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**gatsby develop:**
<img width="1051" alt="Capture d’écran 2021-12-03 à 12 25 17" src="https://user-images.githubusercontent.com/17254120/144595295-b9676b77-0f48-4dea-bb6b-ee25dcff5aa2.png">

### Reproduction Link

https://github.com/CeliaDagorne/gatsby-bug-repro

### Steps to Reproduce

1. gatsby build
2. gatsby develop

### Expected Result

Builds static site

### Actual Result

Failure (See above)

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.0.0 - ~/.nvm/versions/node/v16.0.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.10.0 - ~/.nvm/versions/node/v16.0.0/bin/npm
  Languages:
    Python: 2.7.17 - /Library/Frameworks/Python.framework/Versions/2.7/bin/python
  Browsers:
    Chrome: 96.0.4664.55
    Firefox: 88.0
    Safari: 15.1
  npmPackages:
    gatsby: ^3.5.0 => 3.14.6 
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5 
    gatsby-plugin-gdpr-cookies: ^2.0.8 => 2.0.8 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-image: ^1.8.0 => 1.14.2 
    gatsby-plugin-layout: ^3.3.0 => 3.3.0 
    gatsby-plugin-mailchimp: ^5.2.2 => 5.2.2 
    gatsby-plugin-manifest: ^4.3.0 => 4.3.0 
    gatsby-plugin-postcss: ^5.3.0 => 5.3.0 
    gatsby-plugin-react-helmet: ^3.10.0 => 3.10.0 
    gatsby-plugin-sass: ^5.3.0 => 5.3.0 
    gatsby-source-filesystem: ^3.5.0 => 3.14.0 
    gatsby-source-prismic: ^5.2.3 => 5.2.3
```

**Comment by wardpeet** [comment]
Hi,

Thank you for the reproduction, but I couldn't run it locally as I didn't have prismic env vars. To help you further, we would need a minimal reproduction that works without prismic. 

From glancing at the code, the problem is somewhere here:
```js
       <div className={styles.headerText}>
          <h4 className={styles.eyebrow}>
            {eyebrow.raw ? eyebrow.raw : eyebrow}
          </h4>
          <h2 className={styles.title}>
            {headline?.raw ? headline.raw : parse(headline.html)}
          </h2>
          <div data-html className={styles.content}>
            {description && parse(description.html)}
          </div>
        </div>
```

**Comment by CeliaDagorne** [comment]
Hi @wardpeet,

Thanks a lot for your answer. I've removed this chunk, still got the same error. I've added all needed files to run locally the reproduction :) thank you for your time !
