### ISSUE TITLE
[gatsby-source-contentful]  Unsupported `image/svg+xml` assets

### ISSUE THREAD

**Issue by thisjeremiah** [gatsbyjs/gatsby#3418]
## Description

First off, thank you for your work on this project!

SVG image (`image/svg+xml`) assets are currently unsupported in **gatsby-source-contentful**. A fix similar to #2120 for `image/gif` is needed, but maybe with no resizing capabilities?

I'm happy to work on the solution, but I want to get a read on what the best way forward might be.

### Environment

Gatsby version: 1.9.149

### Actual result

Image properties (e.g., `src`) are not returned. `null` is returned instead. The [isImage](https://github.com/gatsbyjs/gatsby/blob/84bfc00a0cacc004dc8adbb8e119ed2e1d9a6e34/packages/gatsby-source-contentful/src/extend-node-type.js#L69) function does not support `image/svg+xml`.

### Expected behavior

Properties `src` should be able to be returned, without any transformation applied. Maybe there should be a better fallback than `null` for all non-image assets?

### Steps to reproduce

1\. Send query like the following for an SVG image:

`image {
          resolutions(width: 100) {
            src
          }
 }`

2\. See result:

`image: { resolutions: null }`

**Comment by tremby** [comment]
In the mean time I can query for the URL to the SVG and use that as is, but is there a way to have Gatsby fetch that file so it'll be bundled with my app?

**Comment by m-allanson** [comment]
How does contentful treat SVG's? Are they image assets or just plain file assets? Maybe @pieh or @KyleAMathews have some thoughts on how best to handle SVG's in the Contentful source plugin?

**Comment by tremby** [comment]
That *is* what I meant, but I later realized that other images from Contentful are just fetched from Contentful rather than what I assumed was happening, which was that they were being pulled down processed at build time and bundled with my app. Since my site is reaching out to Contentful for assets anyway I actually don't have strong feelings about this any more.

**Comment by janosh** [comment]
It would be great to be able to fetch the actual source, i.e. the HTML content of SVGs stored in Contentful. That would allow targeting them with CSS from within Gatsby.

**Comment by kakadiadarpan** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub issues, we have to clean some of the old issues as many of them have already been resolved with the latest updates.

Please make sure to update to the latest Gatsby version and check if that solves the issue. Let us know if that works for you by adding a comment 👍

**Comment by kakadiadarpan** [comment]
This issue is being closed because there hasn't been any activity for at least 30 days. Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem 👍

**Comment by bsgreenb** [comment]
Has this been fixed? Does SVG fallback work?

**Comment by kabadisha** [comment]
> Has this been fixed? Does SVG fallback work?

No. I've just faced this issue and had to write my own custom handling for SVGs.
The `image.gatsbyImageData` property returns null.
I had to explicitly also fetch the `image.mimeType` and `image.url` properties and then implement conditional logic based on mimeType.

Hers's my code for anyone facing the same issue (a simple hero image):
```javascript
export default function Hero(props) {
  function renderImage(image) {
    if (image) {
      if (image.mimeType === "image/svg+xml") {
        return <img 
          src={image.url}
          alt={image.alt}
          className={styles.heroImage} />
      } else {
        return <GatsbyImage
          alt={image.alt}
          image={getImage(image.gatsbyImageData)}
        />
      }
    }
  }
  
  return (
    <Section>
      <Container>
        <Flex gap={4} variant="responsive">
          <Box width="half">
            {renderImage(props.image)}
          </Box>
        </Flex>
      </Container>
    </Section>
  )
}

export const query = graphql`
  fragment HomepageHeroContent on HomepageHero {
    id
    image {
      id
      gatsbyImageData
      alt
      mimeType
      url
    }
  }
`
```
