### ISSUE TITLE
Post inline images not showing when using gatsby-source-wordpress with Framer Motion animation

### ISSUE THREAD

**Issue by mrbjjackson** [gatsbyjs/gatsby#34187]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi there,

I have a new Gatsby site which sources page content from a Wordpress site via `gatsby-source-wordpress`. 

It also uses Framer Motion to provide page transitions via the `AnimatePresence` component.

After updating Gatsby recently I have noticed that there is a bug arising with images in the page content. On the initial page load, or when pressing refresh, the images show as expected, however when a page is navigated to via another page (i.e. invoking the `AnimatePresence` animation, the images are not revealed.

Note 1: this only happens when the exitBeforeEntry prop is set on the AnimatePresence component (which is required 

Note 2: this only occurs with images in the post content. If I display other images (e.g. the post's featured image) using GatsbyImage, they load as expected in all situations.

Any help would be much appreciated. I'm at a loss with how to debug this issue. Thanks.

### Reproduction Link

https://github.com/mrbjjackson/gatsby-source-wordpress-framer-motion-bug

### Steps to Reproduce

I have created a minimal reproduction that demonstrates the problem.

Also - there is a live version of the site [here](https://gatsby-source-wordpress-framer-bug.netlify.app/)

Essentially, this bug occurs when using Gatsby 4, gatsby-source-wordpress with Framer Motion. I have recently updated the site (from Gatsyb 2) and I'm _90%_ sure this bug was not occuring before I updated.

### Expected Result

The post content images to display as usual.

### Actual Result

Post images show on the initial page load. However if you navigate to the page from another page, they do not appear.

### Environment

```shell
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.11.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 96.0.4664.55
    Firefox: 94.0.1
    Safari: 12.1.2
  npmPackages:
    gatsby: ^4.4.0-next.0 => 4.4.0-next.0 
    gatsby-plugin-image: ^2.3.0 => 2.3.0 
    gatsby-plugin-manifest: ^4.3.0 => 4.3.0 
    gatsby-plugin-react-helmet: ^5.3.0 => 5.3.0 
    gatsby-plugin-sharp: ^4.3.0 => 4.3.0 
    gatsby-plugin-sitemap: ^5.3.0 => 5.3.0 
    gatsby-source-wordpress: ^6.3.0 => 6.3.0 
    gatsby-transformer-sharp: ^4.3.0 => 4.3.0 
  npmGlobalPackages:
    gatsby-cli: 4.2.0
```

**Comment by marvinjude** [comment]
Hi, 

Thanks for the reproduction, 

Tried to debug this and I noticed a few things: 

- The image shows up when I change `data-srcset`  prop on the img element to `srcset`  (video here
https://watch.screencastify.com/v/s0beQCrjdmGEfPSQE9ZH)
- The Image shows up fine without the using framer
- There's an embeded script that swap the attributes 

```js
 <script type="module">
      const t =
        "undefined" != typeof HTMLImageElement &&
        "loading" in HTMLImageElement.prototype;
      if (t) {
        const t = document.querySelectorAll("img[data-main-image]");
        for (let e of t) {
          e.dataset.src &&
            (e.setAttribute("src", e.dataset.src),
            e.removeAttribute("data-src")),
            e.dataset.srcset &&
              (e.setAttribute("srcset", e.dataset.srcset),
              e.removeAttribute("data-srcset"));
          const t = e.parentNode.querySelectorAll("source[data-srcset]");
          for (let e of t)
            e.setAttribute("srcset", e.dataset.srcset),
              e.removeAttribute("data-srcset");
          e.complete && (e.style.opacity = 1);
        }
      }
 </script>
```

@wardpeet @TylerBarnes  Have an idea what this is ?

**Comment by graysonhicks** [comment]
Looks like this: https://github.com/gatsbyjs/gatsby/blob/4a765b5c62208d58f0bd7fd59558160c0b9feed3/packages/gatsby-plugin-image/src/components/layout-wrapper.tsx

**Comment by graysonhicks** [comment]
Not sure if this is released or if it would resolve: https://github.com/wp-graphql/wpgraphql.com/pull/28/files

**Comment by TylerBarnes** [comment]
I think the reason might be that framer isn't rendering the html field with Gatsby images when Gatsby expects them to be rendered (which is immediately). Most likely they're being rendered after some delay and the code which hydrates the images has already ran https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/gatsby-browser.ts

**Comment by benekoehler** [comment]
i got the same problem. i think @TylerBarnes is right. the hydration happens before framer renders the image, thus they are not hydrated correctly

**Comment by gabacode** [comment]
up

**Comment by chiefofsinners** [comment]
I have exactly this problem with images added inline to a Wordpress page not rendering in my Gatsby site. Looking forward to a fix, and any workarounds that people can suggest.

**Comment by mrbjjackson** [comment]
OP here. Just to say the only work around I found for the moment was to add the following option to gatsby-config.js:


```
html: {
          useGatsbyImage: false
}
```

[See here for documentation](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/plugin-options.md#htmlusegatsbyimage)

Obviously this is far from ideal as the Gatsby Image optimisations are one of my primary reasons for using Gatsby. However for now it does work as a fix for me.

**Comment by chiefofsinners** [comment]
> The only work around I found for the time-being was to add the following option to gatsby-config.js as an option in gatsby-source-wordpress:
> 
> ```
> html: {
>           useGatsbyImage: false
> }
> ```
> 
> [See here for documentation](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/plugin-options.md#htmlusegatsbyimage)
> 
> Obviously this is far from ideal as the Gatsby Image optimisations are one of my primary reasons for using Gatsby. However for now it does work as a fix for me.

Fixed it for me! Thanks.

**Comment by chiefofsinners** [comment]
> > The only work around I found for the time-being was to add the following option to gatsby-config.js as an option in gatsby-source-wordpress:
> > ```
> > html: {
> >           useGatsbyImage: false
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [See here for documentation](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/plugin-options.md#htmlusegatsbyimage)
> > Obviously this is far from ideal as the Gatsby Image optimisations are one of my primary reasons for using Gatsby. However for now it does work as a fix for me.
> 
> Fixed it for me! Thanks.

Sadly I now find that after switching off Gatsby images, images in my Wordpress content no longer keep their aspect ratio for mobile devices. Would you be able to point me to a solution to this? I know I'm going off topic a bit.

**Comment by chiefofsinners** [comment]
> > > The only work around I found for the time-being was to add the following option to gatsby-config.js as an option in gatsby-source-wordpress:
> > > ```
> > > html: {
> > >           useGatsbyImage: false
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > [See here for documentation](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/plugin-options.md#htmlusegatsbyimage)
> > > Obviously this is far from ideal as the Gatsby Image optimisations are one of my primary reasons for using Gatsby. However for now it does work as a fix for me.
> > 
> > 
> > Fixed it for me! Thanks.
> 
> Sadly I now find that after switching off Gatsby images, images in my Wordpress content no longer keep their aspect ratio for mobile devices. Would you be able to point me to a solution to this? I know I'm going off topic a bit.

Fixed it simply by:

img {
  height: 100%;
  object-fit: contain;
}

**Comment by mrbjjackson** [comment]
I've come up against this issue again recently and I've used a fix that retains the Gatsby Image functionality that was lost using [my earlier solution](https://github.com/gatsbyjs/gatsby/issues/34187#issuecomment-1016539919).

I used the [solution above](https://github.com/gatsbyjs/gatsby/issues/34187#issuecomment-986954368) suggested by @TylerBarnes . 

i.e. I copied the function `hydratedImages()` from the the gatsby-browser.ts file he linked to. Then I passed this function to the "onExitComplete" prop on Framer's AnimatePresence component.

However this was not quite enough. The `hydrateImages` function was still running fractionally early. It appeared to be running before the new content had loaded into the `document`. I've fixed this in a slightly hacky way - using a very short `setTimeout` (see below) which should be fine for my needs. But if anyone can advise on how to do this without relying on a `setTimeout` that would be very helpful.

```
<AnimatePresence exitBeforeEnter={true} onExitComplete={()=>setTimeout(()=>hydrateImages(), 100)}>
   //components to animate in and out of the DOM
</AnimatePresence>
```

Thanks to @TylerBarnes for pointing me in the direction of this fix. It's taken a while for me to come back round to it but a massively appreciate it.

**Comment by Mrchow86** [comment]
So Ur saying this acc has not been active for 60 days now?...? But it was
till sitting there

**Comment by TylerBarnes** [comment]
@Mrchow86 it says it auto-closes after 60 days and has added a `stale?` label since it's been 20 days so far.

**Comment by peach-inzn** [comment]
>

> I've come up against this issue again recently and I've used a fix that retains the Gatsby Image functionality that was lost using [my earlier solution](https://github.com/gatsbyjs/gatsby/issues/34187#issuecomment-1016539919).
> 
> I used the [solution above](https://github.com/gatsbyjs/gatsby/issues/34187#issuecomment-986954368) suggested by @TylerBarnes .
> 
> i.e. I copied the function `hydratedImages()` from the the gatsby-browser.ts file he linked to. Then I passed this function to the "onExitComplete" prop on Framer's AnimatePresence component.
> 
> However this was not quite enough. The `hydrateImages` function was still running fractionally early. It appeared to be running before the new content had loaded into the `document`. I've fixed this in a slightly hacky way - using a very short `setTimeout` (see below) which should be fine for my needs. But if anyone can advise on how to do this without relying on a `setTimeout` that would be very helpful.
> 
> ```
> <AnimatePresence exitBeforeEnter={true} onExitComplete={()=>setTimeout(()=>hydrateImages(), 100)}>
>    //components to animate in and out of the DOM
> </AnimatePresence>
> ```
> 
> Thanks to @TylerBarnes for pointing me in the direction of this fix. It's taken a while for me to come back round to it but a massively appreciate it.

Hey @mrbjjackson, how did you implement this? I have the same exact issue and I am unable to copy the hydrateimages function to `gatsby-browser.js`. Would you mind sharing your file with me?

**Comment by mrbjjackson** [comment]
> Hey @mrbjjackson, how did you implement this? I have the same exact issue and I am unable to copy the hydrateimages function to `gatsby-browser.js`. Would you mind sharing your file with me?

@peach-inzn - `hydrateImages()` doesn't go in gatsby-browser.js . It needs to be declared or imported into the page (or component) you are calling it from.

Personally I copied it into a file `/utilities/hydrateImages.js` then made it an export (`export default function hydrateImages() {... `) and then imported it into the page that contained my AnimatePresence component.

I hope that helps.
