### ISSUE TITLE
[gatsby-plugin-mdx] unreachable code after return statement

### ISSUE THREAD

**Issue by Glazy** [gatsbyjs/gatsby#34191]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When using `gatsby-plugin-mdx` and rendering `MDXRenderer` the following warning appears in the console on Firefox:

`unreachable code after return statement`

### Reproduction Link

https://github.com/Glazy/unreachable-mdx-repro

### Steps to Reproduce

1. Clone and run reproduction repository
2. Open http://localhost:8000 on Firefox
3. Check console

### Expected Result

The console shouldn't display any warnings about unreachable code.

### Actual Result

The console displays a warning.

### Environment

```shell
System:
    OS: macOS 12.0
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - ~/.nvm/versions/node/v17.0.1/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v17.0.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Firefox: 94.0.2
    Safari: 15.0
  npmPackages:
    gatsby: next => 4.3.0 
    gatsby-plugin-mdx: next => 3.3.0 
    gatsby-source-filesystem: next => 4.3.0
```

**Comment by LandonSchropp** [comment]
I can confirm that this issue is occurring in Firefox.

**Comment by ownchoice** [comment]
Same here. Everything seems okay but I see the error message on the Firefox console.

**Comment by Glazy** [comment]
Bumping this to prevent the bot from closing the issue.

**Comment by jonohewitt** [comment]
This has been happening for a few years now - I see you commented on #23171 which also describes it. From what I understand, [it's been fixed](https://github.com/mdx-js/mdx/pull/1024#issuecomment-747542867) in the just released MDX v2 however this [isn't supported by Gatsby yet as it requires ESM](https://github.com/gatsbyjs/gatsby/discussions/34421). I've read that Gatsby [plans to support ESM "this quarter"](https://github.com/gatsbyjs/gatsby/discussions/34421#discussioncomment-1923110) so hopefully we'll be able to update soon!

**Comment by Glazy** [comment]
Bumping this to prevent the bot from closing the issue.

**Comment by LandonSchropp** [comment]
Bumpity bump.
