### ISSUE TITLE
Gatsby cache irrelevant in onCreateNode

### ISSUE THREAD

**Issue by Vacilando** [gatsbyjs/gatsby#34199]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

"cache" is one of the shared helpers (https://www.gatsbyjs.com/docs/reference/config-files/node-api-helpers/#apis), so it should also work for all Gatsby Node APIs.

However, when I tried to apply it to onCreateNode I found out that while cache can successfully be set, it has no sense whatsoever to set it, because onCreateNode itself is cached on subsequent builds. 
If cache is invalidated in any way, then onCreateNode will run again, but by definition it will fetch new data instead of using cache.

### Steps to Resolve this Issue

Clarify in the docs (eg in section https://www.gatsbyjs.com/docs/reference/config-files/node-api-helpers/#cache) that shared helper "cache" is not relevant for onCreateNode (and perhaps other APIs).

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

The section you're referring to is the API documentation and we try to keep that concise and encapsulated. Did you follow a specific guide or instructions so that you wanted to use `cache` in `onCreateNode`? We typically show examples of this in `sourceNodes` or `onPostBuild`.

I'd propose to modify the description of `onCreateNode` to say that it won't be called on subsequent runs without changes as no new nodes are created (as those are cached).

**Comment by Vacilando** [comment]
We never know which way will the users follow. Examples and tutorials may be useful for some but in my case I already knew about the "cache" helper (I've implemented it in sourceNodes in another plugin) and wanted to use it for onCreateNode.

I set cache but never managed to read it - indeed Gatsby was skipping onCreateNode at subsequent builds without source changes. 
So I looked further, found https://www.gatsbyjs.com/docs/reference/config-files/gatsby-node/ which reassured me "Every Gatsby Node API gets passed a set of helper functions." 
That is confusing, for example. It is _true_ that it's possible to use "cache" in onCreateNode, but it's also important to say that it is useless there.

Eventually good ol' Google helped me with an ancient (2017) thread comment from Kyle in https://github.com/gatsbyjs/gatsby/issues/3260#issuecomment-352518793 "Yeah, caching is taken care of automatically. In production, if the [...] data hasn't updated, then your plugin won't get called ...".

@LekoArts I am am sure you and the seasoned docs writers will know better what and where to improve, my only input is:
- please indicate the non-applicability of "cache" for onCreateNode so that people don't waste hours testing a black box
- do it at or link it to all possible entryways since there the user journey vary wildly
- do the same for other helpers and Node APIs, where applicable
