### ISSUE TITLE
[gatsby-plugin-image] Images flickering on route change using GatsbyImage

### ISSUE THREAD

**Issue by Glazy** [gatsbyjs/gatsby#34190]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When moving from one page to another any images that are rendered using `GatsbyImage` from `gatsby-plugin-image` will briefly flicker/blink.

I have created a minimal reproduction of this which can be found attached to this issue alongside the following screen recording.

Also checked with `gatsby` and all associated plugins using version `next` but still find the same issue.

https://user-images.githubusercontent.com/8593744/144645285-5c7ea255-69cd-423c-80de-3c304bdc17e7.mov

### Reproduction Link

https://github.com/Glazy/gatsby-image-flicker-repro

### Steps to Reproduce

1. Clone and run reproduction repository
2. Use link to toggle between `/` and `/about`

### Expected Result

The image shouldn't flicker and should remain rendered at all times (like the regular `img` tag included in the example).

### Actual Result

The image flickers causing a jarring UX.

### Environment

```shell
System:
    OS: macOS 12.0
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - ~/.nvm/versions/node/v17.0.1/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v17.0.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Firefox: 94.0.2
    Safari: 15.0
  npmPackages:
    gatsby: next => 4.3.0 
    gatsby-plugin-image: next => 2.3.0 
    gatsby-plugin-sharp: next => 4.3.0 
    gatsby-source-filesystem: next => 4.3.0 
    gatsby-transformer-sharp: next => 4.3.0
```

**Comment by Glazy** [comment]
Pinging to keep this issue open.

**Comment by Glazy** [comment]
Pinging again to keep this issue open.

**Comment by Glazy** [comment]
Pinging again to keep this issue open.

**Comment by ConnorMcF** [comment]
+1, also seeing this.

**Comment by Hahlh** [comment]
Not stale

**Comment by Magofoco** [comment]
Not stale :)

**Comment by LekoArts** [comment]
This will be fixed by https://github.com/gatsbyjs/gatsby/pull/35226

**Comment by adamatronix** [comment]
I am seeing something similar wit 2.25.0. I see a flash with the alt text then the image. No placeholder.

**Comment by talkhot** [comment]
> I am seeing something similar wit 2.25.0. I see a flash with the alt text then the image. No placeholder. I should note that it is most notable in Safari Version 16.1 and not chrome. I see it on iOS chrome.

The effect seems to happen more prominent when the image is nested in anchor tag.

**Comment by airfortech** [comment]
have flickering too with "gatsby-plugin-image": "^3.10.0".
Is there any version of package that works fine?

**Comment by EKarpinsky** [comment]
@wardpeet can this be reopened please? Many people are still experiencing this issue (see latest comments)
