### ISSUE TITLE
Using custom post types in WP, on a cached build, content changes in the editor are not being picked up - only on a clean build

### ISSUE THREAD

**Issue by rforster-dev** [gatsbyjs/gatsby#34210]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When using a Custom Post Type, if you make changes to an existing post and run a cached build, the changes are not being picked up. 

If you run a clean build, the changes are being picked up. 

### Reproduction Link

not possible, the steps are simple enough to reproduce locally

### Steps to Reproduce

1. Create a custom post type in WordPress and include that in the sourcing
2. Run a build
3. Make a change in WordPress to the post in the custom post type
4. Run a cached build
5. Viewing the created page, nothing has changed.
...

### Expected Result

Running a cached build should pick up these changes as it does for posts

### Actual Result

Running a cached build does not update the content of a custom post type

### Environment

```shell
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 7.24.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 96.0.4664.45
    Edge: Spartan (44.18362.1593.0)
  npmPackages:
    gatsby: ^3.11.0 => 3.11.0
    gatsby-cli: ^3.11.0 => 3.11.0
    gatsby-image: ^3.8.0 => 3.11.0
    gatsby-plugin-manifest: ^3.11.0 => 3.11.0
    gatsby-plugin-no-index: ^1.0.2 => 1.0.2
    gatsby-plugin-react-helmet: ^4.11.0 => 4.11.0
    gatsby-plugin-remove-fingerprints: 0.0.2 => 0.0.2
    gatsby-plugin-schema-snapshot: ^2.11.0 => 2.11.0
    gatsby-plugin-sharp: ^3.11.0 => 3.11.0
    gatsby-plugin-sitemap: ^4.7.0 => 4.7.0
    gatsby-source-filesystem: ^3.11.0 => 3.11.0
    gatsby-source-wordpress: ^5.11.0 => 5.11.0
    gatsby-source-wordpress-experimental: ^7.0.6 => 7.0.6
    gatsby-transformer-remote-filesystem: ^1.0.0 => 1.0.0
    gatsby-transformer-sharp: ^3.11.0 => 3.11.0
    gatsby-wpgraphql-inline-images: ^0.2.5 => 0.2.5
  npmGlobalPackages:
    gatsby-cli: 3.1.0
```

### Config Flags

PRESERVE_FILE_DOWNLOAD_CACHE: true,
FAST_DEV: false,
DEV_SSR: false,
PARALLEL_SOURCING: false,
PARALLEL_QUERY_RUNNING: false

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

To make the process of resolving problems quicker for both sides we need you to fill out the issue template and give us a [minimal reproduction][reproduction]. This reproduction should also use the latest version of every package (so Gatsby 4).

[reproduction]: https://gatsby.dev/reproduction

**Comment by rforster-dev** [comment]
Thanks @LekoArts - can I ask (and apologies if this is comes across as being really dumb), how do you want me to create a minimal reproduction with a WP instance being involved as the data source?

**Comment by LekoArts** [comment]
It can be an instance completely separate from your actual project that then one can access without any credentials, just for the testing purposes. Then after that you can delete it more easily.

**Comment by rforster-dev** [comment]
Sorry not stale - I just can't get round to providing a reproducible build (sorry!)
