### ISSUE TITLE
pnpm support

### ISSUE THREAD

**Issue by TinsFox** [gatsbyjs/gatsby#34218]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I want to use pnpm to manage dependencies instead of npm, after install dependencies, run command `gatsby develop` I saw an error in terminal.

`Module not found: Error: Can't resolve 'gatsby-link' in '/Users/tinsfox/workplace/hello-world/.cache'`

### Reproduction Link

https://github.com/TinsFox/gatsby-hello

### Steps to Reproduce

1. gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world
2. cd hello-world 
3. rm -rf node_modules
4. rm package-lock.json
5.  pnpm install
6. gatsby develop 
...

### Expected Result

I hope the project can run normally.

### Actual Result

The project is interrupted, and the following error is prompted `Module not found: Error: Can't resolve 'gatsby-link' in '/Users/tinsfox/workplace/hello-world/.cache'`

### Environment

```shell
System:
    OS: macOS High Sierra 10.13.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 96.0.4664.55
    Safari: 11.1
  npmPackages:
    gatsby: ^4.3.0 => 4.3.0
  npmGlobalPackages:
    gatsby-cli: 4.3.0
```

**Comment by LekoArts** [comment]
Hi!

Have you tried using https://github.com/Js-Brecht/gatsby-plugin-pnpm ?

**Comment by TinsFox** [comment]
> 

This solved my problem, thank you

**Comment by TinsFox** [comment]
> Hi!
> 
> Have you tried using https://github.com/Js-Brecht/gatsby-plugin-pnpm ?

This solved my problem, thank you
