### ISSUE TITLE
using navigate function with query strings throws 404

### ISSUE THREAD

**Issue by cesarvarela** [gatsbyjs/gatsby#34216]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Using `navigate('?lalala')` returns a 404, the same URL works when refreshing.

### Reproduction Link

https://github.com/cesarvarela/navigate-query-string

### Steps to Reproduce

Just run the example repo and click the `navigate` button.

### Expected Result

It shouldn't throw a 404

### Actual Result

Throws 404

### Environment

```shell
System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 96.0.4664.93
    Firefox: 94.0.1
    Safari: 15.1
  npmPackages:
    gatsby: ^4.3.0 => 4.3.0
    gatsby-plugin-image: ^2.3.0 => 2.3.0
    gatsby-plugin-manifest: ^4.3.0 => 4.3.0
    gatsby-plugin-mdx: ^3.3.0 => 3.3.0
    gatsby-plugin-react-helmet: ^5.3.0 => 5.3.0
    gatsby-plugin-sharp: ^4.3.0 => 4.3.0
    gatsby-plugin-sitemap: ^5.3.0 => 5.3.0
    gatsby-plugin-styled-components: ^5.3.0 => 5.3.0
    gatsby-source-filesystem: ^4.3.0 => 4.3.0
    gatsby-transformer-sharp: ^4.3.0 => 4.3.0
  npmGlobalPackages:
    gatsby: 4.2.0
```

**Comment by graysonhicks** [comment]
Are you trying to navigate to same URL you are already on, but with a query string attached?

**Comment by cesarvarela** [comment]
Yes

**Comment by cesarvarela** [comment]
I'm looking at this: https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/#recommendations-for-programmatic-in-app-navigation

**Comment by graysonhicks** [comment]
Okay, so two things:

- with the `@reach/router` version of `navigate` it 404s in develop, but works with build + serve
- more importantly, I think the docs are stale there.  instead of importing `navigate` from `@reach/router`, import it from gatsby:

```
import { navigate } from "gatsby";
```

Then it works as intended in develop and prod.  PR to fix docs incoming.

**Comment by graysonhicks** [comment]
PR to update docs here: https://github.com/gatsbyjs/gatsby/pull/34217

Odd that the docs seem to specifically say you *can't* do this, but it seems to work for me.
