### ISSUE TITLE
Gatsby Functions is not working after deploy to Gatsby Cloud

### ISSUE THREAD

**Issue by chiulam** [gatsbyjs/gatsby#34223]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi I started a new project with template https://github.com/gatsbyjs/gatsby-starter-default
Added a simple `hello-world` api and it work locally.
=> https://github.com/chiulam/functions-test/blob/master/src/api/hello-world.js
But when I deployed to Gatsby Cloud, the API doesn't work

From the dashboard I can see the functions in the list
<img width="841" alt="Gatsby_Cloud" src="https://user-images.githubusercontent.com/11757496/145215428-7bf19c73-d3bc-4ecf-900a-4c530a6a0b1b.png">

But when I call the URL, it doesn't work

Build URL:
https://build-f75219fe-ceb1-4124-b84a-5dbb1224fa55.gtsb.io/api/hello-world

Hosted URL:
https://functionstestmaster.gatsbyjs.io/api/hello-world

Thanks in advance!

### Reproduction Link

https://functionstestmaster.gatsbyjs.io/api/hello-world

### Steps to Reproduce

See description above

### Expected Result

`{ hello: "world" }`

### Actual Result

`404 Not Found` or `This site can’t be reached`

### Environment

```shell
gatsby info --clipboard

  System:
    OS: macOS 11.2.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 96.0.4664.93
    Firefox: 61.0.2
    Safari: 14.0.3
  npmPackages:
    gatsby: ^4.3.0 => 4.3.0
    gatsby-plugin-gatsby-cloud: ^4.3.0 => 4.3.0
    gatsby-plugin-image: ^2.3.0 => 2.3.0
    gatsby-plugin-manifest: ^4.3.0 => 4.3.0
    gatsby-plugin-offline: ^5.3.0 => 5.3.0
    gatsby-plugin-react-helmet: ^5.3.0 => 5.3.0
    gatsby-plugin-sharp: ^4.3.0 => 4.3.0
    gatsby-source-filesystem: ^4.3.0 => 4.3.0
    gatsby-transformer-sharp: ^4.3.0 => 4.3.0
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue!
We're only tracking issues for the open source product here, please head over to https://www.gatsbyjs.com/support/ to report issues with Gatsby Cloud.

Thanks!
