### ISSUE TITLE
Ensure file names downloaded with createRemoteFileNode work on windows

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#34233]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Many source plugins use `createRemoteFileNode` to download files from CMSs and other sources. Windows has many reserved characters for file names that linux/macs don't — which means a mac user might upload a file that's valid on their machine to a CMS but which breaks when `createRemoteFileNode` downloads it on Windows. See https://stackoverflow.com/a/31976060 for the list of reserved characters.

The two places where this would need implemented are:
- https://github.com/gatsbyjs/gatsby/blob/2ac366e3745990d47c01f19875f185d0355c89b5/packages/gatsby-source-filesystem/src/utils.js#L52
- https://github.com/gatsbyjs/gatsby/blob/2ac366e3745990d47c01f19875f185d0355c89b5/packages/gatsby-core-utils/src/filename-utils.ts#L38

We do something similar here https://github.com/gatsbyjs/gatsby/blob/63183e392fa8b33551b4d1a18e637299635c4f76/packages/gatsby/src/utils/node-manifest.ts#L286-L288 — though we should probably do this on all platforms as we don't want to create different filenames on different OSs as potentially a site could deploy changes from both windows & non windows OSs (this is pretty niche) but we should probably ensure all OSs produce the same site.

### Reproduction Link

n/a

### Steps to Reproduce

1. use createRemoteFileNode to download a file on windows with an invalid character

### Expected Result

It doesn't error crashing the server.

### Actual Result

It crashes.

### Environment

```shell
Windows
```

### Config Flags

none

**Comment by Sameedahmad** [comment]
This issue needs to be resolved as someone on windows wouldn't be able to run the project as the build fails everytime.
