### ISSUE TITLE
"Corrupt JPG" from image-size, could we switch to probe-image-size?

### ISSUE THREAD

**Issue by awesomebob** [gatsbyjs/gatsby#3423]
## Description

I'm working with some large, high-quality images.

I get this error during the build step, both on `gatsby develop` and `gatsby build`, but only about 50% of the time: "Corrupt JPG, exceeded buffer limits".

From the `image-size` repo, it appears that this is a known bug (Issue [37](https://github.com/image-size/image-size/issues/37), but the `probe-image-size` project appears to handle this better. Could we consider switching to use that instead?

### Environment

Gatsby version: 1.9.149
Node.js version: 8.9.2
Operating System: Ubuntu 16.04

**Comment by fk** [comment]
Hi @awesomebob, thanks for reporting this!
Do you want to give switching [gatsby-plugin-sharp](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sharp) and [gatsby-transformer-sharp](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-sharp) to use `probe-image-size` a go?

Sidenote: Seems we're using two different versions of `image-size`: https://github.com/gatsbyjs/gatsby/blob/53f66a4648989e604340afb9afa59751ea08b38c/packages/gatsby-transformer-sharp/package.json#L22 https://github.com/gatsbyjs/gatsby/blob/53f66a4648989e604340afb9afa59751ea08b38c/packages/gatsby-plugin-sharp/package.json#L10
