### ISSUE TITLE
gatsby-transformer-documentationjs plugin fails 

### ISSUE THREAD

**Issue by m5kr1pka** [gatsbyjs/gatsby#34246]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

gatsby-transformer-documentationjs plugins fails due to dependency related issues.

### Reproduction Link

none

### Steps to Reproduce

1. Install gatsby-transformer-documentationjs
2. npm run develop

### Expected Result

Works

### Actual Result

Returns an Error:

```
Cannot find module
'micromark/dist/character/markdown-line-ending'
Require stack:
- .../node_modules/documentation/src/remark-jsDoc-link.js
- .../node_modules/documentation/src/remark-parse.js
- .../node_modules/documentation/src/sort.js
- .../node_modules/documentation/src/index.js
- .../node_modules/gatsby-transformer-documentationjs/gatsby-node.js
- .../node_modules/gatsby/dist/bootstrap/resolve-module-exports.js
```

### Environment

```shell
System:
    OS: macOS 12.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 96.0.4664.93
    Safari: 15.1
  npmPackages:
    gatsby: ^4.3.0 => 4.3.0 
    gatsby-plugin-catch-links: ^4.3.0 => 4.3.0 
    gatsby-plugin-image: ^2.3.0 => 2.3.0 
    gatsby-plugin-manifest: ^4.3.0 => 4.3.0 
    gatsby-plugin-offline: ^5.3.0 => 5.3.0 
    gatsby-plugin-postcss: ^5.3.0 => 5.3.0 
    gatsby-plugin-react-helmet: ^5.3.0 => 5.3.0 
    gatsby-plugin-sharp: ^4.3.0 => 4.3.0 
    gatsby-plugin-typescript: ^4.3.0 => 4.3.0 
    gatsby-source-filesystem: ^4.3.0 => 4.3.0 
    gatsby-transformer-documentationjs: ^6.3.0 => 6.3.0 
    gatsby-transformer-remark: ^5.3.0 => 5.3.0 
    gatsby-transformer-sharp: ^4.3.0 => 4.3.0
```

**Comment by m5kr1pka** [comment]
Might be related issue: https://github.com/gatsbyjs/gatsby/issues/16840

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
