### ISSUE TITLE
Clarify how to properly namespace a schema to use with addThirdParty schema.

### ISSUE THREAD

**Issue by dopry** [gatsbyjs/gatsby#34243]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

I am working on a source plugin and encountering issues using addThirdPartySchema. It is unclear what the documentation means by namespacing a schema.  

see: https://github.com/gatsbyjs/gatsby/blob/af6632b08e7867d5304cfb13448c2086fb622543/packages/gatsby/src/redux/actions/restricted.ts#L41

The article is missing after `it's user's responsibility.` It would be nice to drop the use of the conjunctive `'s` followed by the possessive `'s` for non-native speakers who may not parse this easily.  This could read `it is the user's responsibility. `

### Steps to Resolve this Issue

1.  link to an example of how to properly namespace a schema for use with addThirdPartySchema

**Comment by LekoArts** [comment]
Hi, thanks for the issue.

PRs improving this are appreciated!

**Comment by VividhPandey003** [comment]
Hey, I am a beginner and first time contributing to open source. I found this documentation issue which I think I can maybe rectify but I wanted a bit of guidance regarding the same.

**Comment by atharva20-coder** [comment]
> Hi, thanks for the issue.
> 
> PRs improving this are appreciated!

Hey!, I think @dopry wanted to say that **Gatsby schema, so it's user's responsibility to make sure it doesn't happen** should be written as **Gatsby schema, so it's the user's responsibility to make sure it doesn't happen**. Correct me if I am wrong.

**Comment by AshuuDixit** [comment]
> Hey, I am a beginner and first time contributing to open source. I found this documentation issue which I think I can maybe rectify but I wanted a bit of guidance regarding the same

**Comment by karunakaran186** [comment]
hi thanks for the issues @gatsbybot
