### ISSUE TITLE
gatsby-plugin-mdx: `slug` miss non-ASCII characters while their file name contains

### ISSUE THREAD

**Issue by jiusanzhou** [gatsbyjs/gatsby#34262]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I create some mdx file which name contains Chinese and unicode emoji, such as `测试 for test`, I query the `slug` field and got `for-test`, seems like trim the non-ASCII off before generate `slug` from file name. What we excepted should be `测试-for-test` or `%E6%B5%8B%E8%AF%95-for-test`

### Reproduction Link

https://github.com/jiusanzhou/report-gatsby-issue-demo-repo

### Steps to Reproduce

1. Create a mdx file which file name contains non-ASCII characters, for example: `测试 for test.mdx`
2. Query the `slug` from mdx nodes.

### Expected Result

%E6%B5%8B%E8%AF%95-for-test

### Actual Result

for-test

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.9.1 - ~/.nvm/versions/node/v16.9.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.9.1/bin/yarn
    npm: 7.21.1 - ~/.nvm/versions/node/v16.9.1/bin/npm
  Languages:
    Python: 3.6.1 - /Users/johnzoe/anaconda3/envs/py36/bin/python
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 95.0
    Safari: 14.0.3
```

**Comment by seshaljain** [comment]
Is there any update on this?

**Comment by LekoArts** [comment]
This could be potentially a breaking change as people might rely on the current behavior. I'm not sure if we can fix this without a major bump as now _suddenly_ adding non-ascii characters to the slug will change the URLs that people use (and link to).

**Comment by LekoArts** [comment]
Hi!

We merged https://github.com/gatsbyjs/gatsby/pull/35650 which means that a new major version of `gatsby-plugin-mdx` will be released on August 16. You can already try it out by installing `gatsby-plugin-mdx@next` & `gatsby@next`.

We removed the automatic creation of `slug` in this new major version so you can create this field however (and with which ever library) you want. Hence I'll close this as it's now in user land, not in the plugin anymore.
