### ISSUE TITLE
gatsby-remark-images does not lazy load images

### ISSUE THREAD

**Issue by itsZed0** [gatsbyjs/gatsby#34295]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I'm using `gatsby-remark-images@6.4.0` to lazy load my markdown images. However, when I check the In Chrome network tab the image is loaded on page load and not lazy loaded. Also, when I check the img tag in the browser, I see no `loading=lazy` attribute added below:
![html-img-tag](https://user-images.githubusercontent.com/18530552/146721037-5a2a086e-3a78-4c2c-98a7-33d2d9871334.png)

The image I want to be loaded lazily is under [this](https://demo-khannida.netlify.app/blog/2020-12-22-sensible-headings-are-seldom-used/#h3--sub-sub-heading) heading in the website
  
I tried with version 3.1.10 too, does'nt work, Am I missing something?

Below are the contents of my gatsby-config.js file:

```js
// require("dotenv").config({
//   path: `.env.dev`,
// });

module.exports = {
  plugins: [
    "gatsby-plugin-react-helmet",
    "gatsby-plugin-sass",
    {
      // keep as first gatsby-source-filesystem plugin for gatsby image support
      resolve: "gatsby-source-filesystem",
      options: {
        path: `${__dirname}/static/img`,
        name: "uploads",
      },
    },
    {
      resolve: "gatsby-source-filesystem",
      options: {
        path: `${__dirname}/src/pages`,
        name: "pages",
      },
    },
    {
      resolve: "gatsby-source-filesystem",
      options: {
        path: `${__dirname}/src/img`,
        name: "images",
      },
    },
    {
      resolve: "gatsby-transformer-remark",
      options: {
        plugins: [
          {
            resolve: "gatsby-remark-relative-images",
            options: {
              name: "uploads",
            },
          },
          {
            resolve: "gatsby-remark-images",
            options: {
              // It's important to specify the maxWidth (in pixels) of
              // the content container as this plugin uses this as the
              // base for generating different widths of each image.
              maxWidth: 800,
              withWebp: true,
              withAvif: true,
              loading: "lazy",
            },
          },
          {
            resolve: "gatsby-remark-copy-linked-files",
            options: {
              destinationDir: "static",
            },
          },
          {
            resolve: `gatsby-remark-responsive-iframe`,
            options: {
              wrapperStyle: `margin-bottom: 1.0725rem`,
            },
          },
          `gatsby-remark-autolink-headers`,
          {
            resolve: `gatsby-remark-highlight-code`,
            options: {
              highlightLines: true,
            },
          },
        ],
      },
    },
    "gatsby-plugin-image",
    "gatsby-plugin-sharp",
    "gatsby-transformer-sharp",
    {
      resolve: "gatsby-plugin-netlify-cms",
      options: {
        modulePath: `${__dirname}/src/cms/cms.js`,
      },
    },
    {
      resolve: "gatsby-plugin-webpack-bundle-analyser-v2",
      options: {
        devMode: true,
      },
    },
    {
      resolve: "gatsby-plugin-purgecss", // purges all unused/unreferenced css rules
      options: {
        develop: true, // Activates purging in npm run develop
        purgeOnly: ["/all.sass"], // applies purging only on the bulma css file
      },
    }, // must be after other CSS plugins
    "gatsby-plugin-netlify", // make sure to keep it last in the array
  ],
};
```

### Reproduction Link

https://demo-khannida.netlify.app/blog/2020-12-22-sensible-headings-are-seldom-used/

### Steps to Reproduce

1. Go to [this](https://demo-khannida.netlify.app/blog/2020-12-22-sensible-headings-are-seldom-used/) link.
2. Check network tag that the image inside [this](https://demo-khannida.netlify.app/blog/2020-12-22-sensible-headings-are-seldom-used/#h3--sub-sub-heading) heading is not lazy loaded.
3. Check in Inspect element in Chrome browser for the above image,  `loading="lazy"` is not added to the image.
...

### Expected Result

Image taken from the markdown should be lazy loaded.

### Actual Result

Image not lazy loading

### Environment

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.62)
  npmPackages:
    gatsby: ^4.0.0 => 4.3.0
    gatsby-plugin-feed: ^4.4.0 => 4.4.0
    gatsby-plugin-google-gtag: ^4.4.0 => 4.4.0
    gatsby-plugin-image: ^2.4.0 => 2.4.0
    gatsby-plugin-mailchimp: ^5.2.2 => 5.2.2
    gatsby-plugin-netlify: ^3.14.0 => 3.14.0
    gatsby-plugin-netlify-cms: ^6.0.0 => 6.3.0
    gatsby-plugin-purgecss: ^6.0.0 => 6.1.0
    gatsby-plugin-react-helmet: ^5.0.0 => 5.3.0
    gatsby-plugin-sass: ^5.0.0 => 5.3.0
    gatsby-plugin-sharp: ^4.4.0 => 4.4.0
    gatsby-plugin-social9-socialshare: ^1.0.5 => 1.0.5
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.26 => 1.1.26
    gatsby-remark-autolink-headers: ^5.3.0 => 5.3.0
    gatsby-remark-copy-linked-files: ^5.0.0 => 5.3.0
    gatsby-remark-highlight-code: ^3.1.0 => 3.1.0
    gatsby-remark-images: ^6.4.0 => 6.4.0
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0
    gatsby-remark-responsive-iframe: ^5.4.0 => 5.4.0
    gatsby-source-filesystem: ^4.4.0 => 4.4.0
    gatsby-transformer-remark: ^5.4.0 => 5.4.0
    gatsby-transformer-sharp: ^4.4.0 => 4.4.0
  npmGlobalPackages:
    gatsby-cli: 4.3.0
```

**Comment by graysonhicks** [comment]
That image looks like it is using an absolute URL to another domain.  I believe the plugin works by using relative URLs to files on the local filesystem.

**Comment by itsZed0** [comment]
Hey @graysonhicks , Thanks for looking into this.
The image is from local file system, the way I'm using it in the markdown is - ![flavor wheel](/img/image1.png)
Also, I`m using `gatsby-remark-relative-images` too.

**Comment by itsZed0** [comment]
I removed the `gatsby-remark-relative-images` plugin and using the markdown code to -`![flavor wheel](../../img/chemex.jpg)`
Works fine, we can close the issue.

Thanks for all the help.
Happy Holidays!
