### ISSUE TITLE
"React DOM tree root should always have a node reference"

### ISSUE THREAD

**Issue by maidh91** [gatsbyjs/gatsby#3429]
## Description

Whenever I click any links, it does not update the page content, and this error is shown from the console:
`React DOM tree root should always have a node reference`

If I made a full page refresh, then the page is loaded ok.

I guess there is something related to `gatsby-plugin-catch-links`.

```
reactProdInvariant.js:29 Uncaught Error: Minified React error #34; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=34 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at n (reactProdInvariant.js:29)
    at c (ReactDOMComponentTree.js:170)
    at v.getHostNode (ReactDOMComponent.js:949)
    at Object.getHostNode (ReactReconciler.js:60)
    at f.getHostNode (ReactCompositeComponent.js:381)
    at Object.getHostNode (ReactReconciler.js:60)
    at v._updateChildren (ReactMultiChild.js:342)
    at v.updateChildren (ReactMultiChild.js:295)
    at v._updateDOMChildren (ReactDOMComponent.js:944)
    at v.updateComponent (ReactDOMComponent.js:758)
```

This is the full message from facebook:
```
Error Decoder
In the minified production build of React, we avoid sending down full error messages in order to reduce the number of bytes sent over the wire.

We highly recommend using the development build locally when debugging your app since it tracks additional debug info and provides helpful warnings about potential problems in your apps, but if you encounter an exception while using the production build, this page will reassemble the original text of the error.

The full text of the error you just encountered is:

React DOM tree root should always have a node reference.
```

### Environment

Gatsby version: 1.1.28
Node.js version: 8.9.3
Operating System: Ubuntu 16.04

### File contents (if changed):

This is the source:
https://github.com/aquabubu/home-gatsby

...

**Comment by calcsam** [comment]
Cloned the repo locally. I'm not getting this on gatsby develop. Does it only show up on production? Does it only happen for specific links? Could you put your repo on eg Netlify and point to a couple of links?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
