### ISSUE TITLE
[gatsby-source-shopify] Shopify bulk operations cause race condition with Live vs. Preview builds in Gatsby Cloud

### ISSUE THREAD

**Issue by brianecook** [gatsbyjs/gatsby#34303]
### Description

When merging a feature branch to master, Gatsby Cloud automatically kicks off a build for Live and Preview environments simultaneously. This ends up creating a race condition in relation to Shopify bulk operation API.  Whichever build is slower fails with this error:

Couldn't initiate bulk operation query

Error: A bulk query operation for this app and shop is already in progress: gid://shopify/BulkOperation/${id}.

The documentation for gatsby-source-shopify mentions "For a given store + app combination, only one bulk operation can be run at a time, so this plugin will wait for in-progress operations to complete."

This would be fine with me if it worked, however, this does not seem to be true. If another bulk operation is in progress the current build fails with the above error message. For the record, this after the createSchemaCustomization API.

### Steps to Reproduce

1. Enable CMS Preview builds in Gatsby Cloud
2. Connect github in "Site Details" in GC.
3. Merge feature branch.
4. Either Preview or Live build (whichever was slower/hit Shopify bulk operation API later) will fail.

### Expected Result

Whichever build occurs later (usually a case of milliseconds or seconds since Gatsby Cloud kicks Preview and Live builds immediately after branch merge) waits for previous bulk operation to finish before trying to create a new bulk operation and build successfully.

### Actual Result

Build that occurs slightly later fails with error:

Couldn't initiate bulk operation query

Error: A bulk query operation for this app and shop is already in progress: gid://shopify/BulkOperation/${id}.

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 96.0.4664.110
    Safari: 15.0
  npmPackages:
    gatsby: ^3.13.0 => 3.13.1
    gatsby-background-image: ^1.5.3 => 1.5.3
    gatsby-plugin-contentful-optional-fields: ^2.2.2 => 2.2.2
    gatsby-plugin-gatsby-cloud: ^3.1.0 => 3.1.0
    gatsby-plugin-google-analytics: ^3.13.0 => 3.13.0
    gatsby-plugin-image: ^1.14.0 => 1.14.0
    gatsby-plugin-react-helmet: ^4.13.0 => 4.13.0
    gatsby-plugin-root-import: ^2.0.7 => 2.0.7
    gatsby-plugin-sharp: ^3.14.0 => 3.14.0
    gatsby-plugin-sitemap: ^4.9.0 => 4.9.0
    gatsby-plugin-styled-components: ^4.13.0 => 4.13.0
    gatsby-source-contentful: ^5.14.0 => 5.14.0
    gatsby-source-filesystem: ^3.14.0 => 3.14.0
    gatsby-source-shopify: ^5.5.0 => 5.5.0
    gatsby-transformer-sharp: ^3.14.0 => 3.14.0
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue!
It's a limitation of the bulk API and noted in the source plugin itself, but Gatsby Cloud should behave differently here and work around this limitation. Please open a ticket on https://www.gatsbyjs.com/support/ and feel free to reference this issue.
Thanks!

**Comment by benrobertsonio** [comment]
I talked to our integrations team and they said the best way to work around this at the moment is to create multiple private Shopify apps: one for production, one for preview, and one for each local environment. 

Otherwise, the source plugin will always prioritize production bulk operations and cancel all others (multiple private apps gets around this)

**Comment by njbmartin** [comment]
I have also been hit by this and it has become quite frustating. Can we keep this open until it has been fixed to be used with a single "private app"?

There was a decision to use the bulk operation in the plugin, but this isn't ideal for any production environments where builds can happen concurrently - Gatsby Cloud being a prime example of this.
