### ISSUE TITLE
Unable to load preview page for Wordpress

### ISSUE THREAD

**Issue by SergiOca87** [gatsbyjs/gatsby#34310]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

On the Wordpress CMS, when a user clicks on "Preview Changes" it opens a "polishing changes" page that always end up in an error. Console shows:

"Timed out waiting for node manifest. Builds are idle and no manifest was found"

The page then says there was an error and when I click on "View Error Logs" I see that there is no error at all, the preview build was built, the user is simply not redirected to it.

Everything is on the latest version. I actually have this problem on the 2 websites that I'm building with Gatsby with Wordpress as a data source.

### Reproduction Link

https://preview-kohnenbuild.gtsb.io/

### Steps to Reproduce

1 - Change content on Wordpress
2 -  Click on "Preview Changes"
3- Preview build starts and finishes without errors

WordPress

### Expected Result

The user is redirected to a new preview page.

### Actual Result

The user is stuck on a page with "Polishing Changes" which ends up in an error.

### Environment

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor        
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE        
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.62)
  npmPackages:
    gatsby: ^4.4.0 => 4.4.0
    gatsby-plugin-gatsby-cloud: ^4.4.0 => 4.4.0
    gatsby-plugin-google-analytics: ^4.4.0 => 4.4.0
    gatsby-plugin-image: ^2.4.0 => 2.4.0
    gatsby-plugin-manifest: ^4.4.0 => 4.4.0
    gatsby-plugin-offline: ^5.4.0 => 5.4.0
    gatsby-plugin-react-helmet: ^5.4.0 => 5.4.0
    gatsby-plugin-react-svg: ^3.1.0 => 3.1.0
    gatsby-plugin-scroll-reveal: 0.0.7 => 0.0.7
    gatsby-plugin-sharp: ^4.4.0 => 4.4.0
    gatsby-plugin-sitemap: ^5.4.0 => 5.4.0
    gatsby-plugin-styled-components: ^5.4.0 => 5.4.0
    gatsby-source-filesystem: ^4.4.0 => 4.4.0
    gatsby-source-wordpress: ^6.4.0 => 6.4.0
    gatsby-transformer-sharp: ^4.4.0 => 4.4.0
  npmGlobalPackages:
    gatsby-cli: 3.9.0
```

**Comment by graysonhicks** [comment]
Hi @SergiOca87 !  We are also tracking this internally on the Gatsby Cloud side, we will post the eventual resolution here.  Thanks!

**Comment by LekoArts** [comment]
I'm closing this as it's tracked somewhere else. For Gatsby Cloud related issues please go here: https://www.gatsbyjs.com/support/

**Comment by helmutgranda** [comment]
@LekoArts , can we get better direction other than just being sent to a Support landing page? How about an article or another ticket where it is being tracked.

@SergiOca87 , we have run into the same issue, anyway you can post the resolution here?
