### ISSUE TITLE
Adding query string doesn't trigger update

### ISSUE THREAD

**Issue by OKNoah** [gatsbyjs/gatsby#3431]
## Description

When I add a query string to the URL, the app does not update.

```js
<Link to="/?hello" />
// or
this.props.history.push('/') // removing a querystring
```

### Environment

Gatsby version: 1.1.28
Node.js version: 8.9.1
Operating System: macOS

### Actual result

```js
shouldComponentUpdate (nextProps) {
 // this does not execute at all when query string changes
}
```

### Expected behavior

The component should update

### Steps to reproduce

1\. Use `Link` or history to go to `/?someString`

2\. Observe that component does not update.

**Comment by calcsam** [comment]
Should be fixed when https://github.com/gatsbyjs/gatsby/pull/3516 is merged

**Comment by OKNoah** [comment]
As a workaround I used `this.forceUpdate` and the global `location`. But that meant if I triggered an update in a child component I had to pass `forceUpdate` down through props.

@calcsam Thanks!

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
