### ISSUE TITLE
[gatsby-plugin-image] Cannot read properties of undefined (reading 'createElement')

### ISSUE THREAD

**Issue by piotr-zurek** [gatsbyjs/gatsby#34324]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

After upgrade to Gatsby v4 and latest `gatsby-plugin-image` in development mode I can see errors:
![image](https://user-images.githubusercontent.com/24444007/147483631-b5b8718b-be6d-4cd4-a237-686379ea5cab.png).

```tsx

const MyComponent = (props) => {
    return <GatsbyImage
      image={props.image}
      alt={props.alt}
      objectFit={props.objectFit}
      style={props.style}
      className={props.className}
    />
}
```

After compiled code analysis i found that first argument, which is an object of props is used also as `react` reference. 

Here is the screenshot from my Sources panel from Chrome Dev Tools:

`t` is a variable containing component props, but is also used to render component with `.createElement()` method.

![image](https://user-images.githubusercontent.com/24444007/147483987-5e523c5c-dc03-462a-b0fa-28f3669db715.png)

Error only happens in dev mode and only on pages with `GatsbyImage`, all others works as before.
Also there is no error in production mode, after building the app and running on web server (`http-server`).

### Reproduction Link

not able to create

### Steps to Reproduce

1. Render `<GatsbyImage />`

### Expected Result

App renders correctly

### Actual Result

Gatsby is showing errors:
![image](https://user-images.githubusercontent.com/24444007/147484348-2a524ae1-4edd-4c6b-88df-39e0a94d3945.png)

### Environment

```shell
System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 7.20.0 - ~/.npm-global/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 94.0.2
    Safari: 15.1
  npmPackages:
    gatsby-plugin-styled-components: ^5.4.0 => 5.4.0
```

**Comment by iChenLei** [comment]
@piotr-zurek  Can you provide minimal reproducation repository ? Otherwise we can't debug this issue.

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by piotr-zurek** [comment]
I found root cause of the issue. Previously I used old version of `babel-preset-gatsby` package `^1.8.0`, but after upgrade to  `^2.5.1` it works well.

Closing issue.

**Comment by JenniferFalkenstein** [comment]
I still have this problem, even after updating to `^2.5.1` unfortunately 😞 
Here are the dependencies I have. If you need more informations, feel free to ask. I removed the ones, where I'm pretty sure that they aren't important (e.g. `styled-components`).
```
"dependencies": {
    "gatsby": "^4.4.0",
    "gatsby-core-utils": "^3.5.1",
    "gatsby-plugin-image": "^2.5.1",
    "gatsby-plugin-manifest": "^4.5.1",
    "gatsby-plugin-react-helmet": "^5.4.0",
    "gatsby-plugin-sharp": "^4.5.1",
    "gatsby-source-filesystem": "^4.4.0",
    "gatsby-transformer-sharp": "^4.5.0",
    "postcss": "^8.4.5",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-helmet": "^6.1.0",
  },
  "devDependencies": {
    "@babel/plugin-proposal-private-methods": "^7.16.7",
    "@babel/preset-env": "^7.16.8",
    "@babel/preset-react": "^7.16.7",
    "babel-preset-gatsby": "^2.5.1",
    "standard-version": "^9.3.2",
  }
```
