### ISSUE TITLE
Cannot resolve StaticQuery: JSON file not being generated

### ISSUE THREAD

**Issue by davwheat** [gatsbyjs/gatsby#34323]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I have a StaticQuery inside a component, which is being imported into an MDX file.

The StaticQuery JSON data is not being generated, meaning that at runtime in dev, I get an error like this:

```
The result of this StaticQuery could not be fetched. This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues
```

If I stop the dev server and start it again, the server never starts, instead erroring out with a `ModuleNotFoundError`:

![image](https://user-images.githubusercontent.com/7406822/147466825-61d9d3aa-db17-4641-b8c0-f390917e87f1.png)

The attached minimal reproduction shows this issue.

### Reproduction Link

https://github.com/davwheat/gatsby-issue-reproduction-2

### Steps to Reproduce

1. Create an MDX file
2. Import a component with a static query
3. Build fails

### Expected Result

Static Query would be handled correctly and build would not fail.

### Actual Result

Build fails as query JSON file doesn't exist.

### Environment

```shell
`wmic` is removed in latest Windows 11 builds, breaking this Gatsby command.
```

### Config Flags

None.

**Comment by iChenLei** [comment]
### offtopic issue
```
`wmic` is removed in latest Windows 11 builds, breaking this Gatsby command.
```
We can fix it until this PR https://github.com/tabrindle/envinfo/pull/214 be merged.

**Comment by fbanke** [comment]
Did you find a solution to this? 
I have the same problem
