### ISSUE TITLE
 Error: Module not found: Error: Cannot resolve module 'react-helmet'

### ISSUE THREAD

**Issue by spences10** [gatsbyjs/gatsby#3432]
## Description

I run `gatsby develop` and get the following error:

```sh
  Error: Module not found: Error: Cannot resolve module 'react-helmet' in /mnt/c/Users/spenc/repos/blog.scottspence.me/node_modules/gatsb
  y-plugin-react-helmet
```

Describe the issue or the enhancement that you want to see.

### Environment

Gatsby version:     "gatsby": "1.9.149",
Node.js version: 5.6.0
Operating System: Wondoze

I've had a look at the `node_modules/gatsby/node_modules/` and it appears to be empty

I'm in the process of `npm i` now but wondering if it is my environment or gatsby

**Comment by pieh** [comment]
do you have `react-helmet` installed? you need to install both `react-helmet` and `gatsby-plugin-react-helmet`

**Comment by spences10** [comment]
Yes I do|did|have

I've also reinstalled all packages again, verified and cleared the cache

I'm going to uninstall WSL and try again

**Comment by spences10** [comment]
So, it appears that I updated `gatsby-plugin-react-helmet` to v2.0.3 

I have gone back to v1.0.8 and was able to build the projec5t again

**Comment by spences10** [comment]
>do you have react-helmet installed? you need to install both react-helmet and gatsby-plugin-react-helmet

Apologies @pieh I read your comment on mobile after several beers 🍺 and have only re-read it this morning, apologies 🙃 

So, I've installed `react-helmet` and installed `gatsby-plugin-react-helmet@latest` tried the build and all works fine.

Thanks 👍
