### ISSUE TITLE
allowSyntheticDefaultImports TypeScript compiler option not used

### ISSUE THREAD

**Issue by corydeppen** [gatsbyjs/gatsby#3433]
## Description

The `allowSyntheticDefaultImports` TypeScript compiler option doesn't seem to be respected by Gatsby and requires React to be imported using `import * as React from 'react'`. I've tried including the option in both `tsconfig.json` and in the `gatsby-plugin-typescript` options in `gatsby-config.js` and neither work.

```js
// gatsby-config.js
{
  resolve: `gatsby-plugin-typescript`,
  options: {
    allowSyntheticDefaultImports: true,
  },
}
```

### Environment

Gatsby version: 1.1.28
Node.js version: 8.9.3
Operating System: Win10
TypeScript version: 2.6.2

### Actual result

Importing React using the cleaner `import React from 'react'` results in `TypeError: Cannot read property 'createElement' of undefined at ./src/pages/about.tsx.exports.default (about.tsx:7)`.

### Expected behavior

Should be able to use the `allowSyntheticDefaultImports` TypeScript compiler option in either `tsconfig.json` or in the `gatsby-plugin-typescript` options in `gatsby-config.js` to import modules using the `import DefaultExport from 'module'` syntax.

**Comment by nsimonson** [comment]
I just ran into this as well. This fixed it for me. Set `esModuleInterop: true` in your `tsconfig.json`. `allowSyntheticDefaultImports` doesn't affect emitted code, just type checking.
```
{
  "compilerOptions": {
    ...
    "esModuleInterop": true,
    ...
  },
}
```

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
