### ISSUE TITLE
Reading from "node:async_hooks" is not handled by plugins (Unhandled scheme)

### ISSUE THREAD

**Issue by LinnJS** [gatsbyjs/gatsby#34348]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

[Discussion started around this error](https://github.com/gatsbyjs/gatsby/discussions/34335)

I am trying to implement `Twind` which is a tailwind CSS-in-JS library in my Gatsby starter and am trying to implement it as it states in its docs [here](https://twind.dev/usage-guides/gatsby.html) and I am getting the errors below:

![image](https://user-images.githubusercontent.com/23741323/147597192-aef7a4ba-ed61-4c0c-9035-784fabe27179.png)

![image](https://user-images.githubusercontent.com/23741323/147597198-ec0c4801-7d10-4930-b025-e1f55e1fddea.png)

Generating SSR bundle failed

Reading from "node:async_hooks" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.

The code looks like this in the `gatsby-ssr.js` file:

```
import { setup } from 'twind';
import { asyncVirtualSheet, getStyleTagProperties } from 'twind/server';
import { createElement } from 'react';
import './src/tailwind.css';

const sheet = asyncVirtualSheet();

setup({ sheet });

export const wrapPageElement = ({ element }) => {
  sheet.reset();

  return element;
};

export const onRenderBody = ({ setHeadComponents, pathname }) => {
  console.log('sheet: ', sheet);
  const { id, textContent } = getStyleTagProperties(sheet);
  console.log('twind props: ', { id, textContent });
  const twindId = `twind-ssr-${id}-${Math.random()}`;

  // eslint-disable-next-line no-unused-vars
  const styleProps = {
    id,
    dangerouslySetInnerHTML: {
      __html: textContent,
    },
  };
  setHeadComponents([
    createElement('style', {
      id: twindId,
      dangerouslySetInnerHTML: {
        __html: textContent,
      },
    }),
  ]);
};

```

### Reproduction Link

https://github.com/LinnJS/gatsby-scalable-starter/pull/20

### Steps to Reproduce

1. git clone https://github.com/LinnJS/gatsby-scalable-starter
2. cd ./gatsby-scalable-starter
3. git checkout branch LinnJS-landing-refactor
4. yarn && yarn build (you will see the error above in this step)
5. Look at `gatsby-ssr-.js` for root cause of error where I am tryin to implement Twind as the docs state [here](https://twind.dev/usage-guides/gatsby.html)
...

### Expected Result

Build should pass without error.

I would like to know how to resolve  "node:async_hooks" node error so I can eventually write this code into a gatsby plugin. I am just not sure how to go about resolving this problem in the Gatsby ecosystem or if there is another place in Gatsby this should be implemented. 

Error:
Reading from "node:async_hooks" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.

### Actual Result

I get this error and the build fails.

Error:
Reading from "node:async_hooks" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.

### Environment

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.3.0 - /opt/homebrew/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Safari: 15.2
  npmPackages:
    gatsby: ^4.4.0 => 4.4.0 
    gatsby-plugin-gatsby-cloud: ^4.4.0 => 4.4.0 
    gatsby-plugin-image: ^2.4.0 => 2.4.0 
    gatsby-plugin-manifest: ^4.4.0 => 4.4.0 
    gatsby-plugin-offline: ^5.4.0 => 5.4.0 
    gatsby-plugin-postcss: ^5.4.0 => 5.4.0 
    gatsby-plugin-react-helmet: ^5.4.0 => 5.4.0 
    gatsby-plugin-root-import: ^2.0.8 => 2.0.8 
    gatsby-plugin-sharp: ^4.4.0 => 4.4.0 
    gatsby-source-filesystem: ^4.4.0 => 4.4.0 
    gatsby-transformer-json: ^4.4.0 => 4.4.0 
    gatsby-transformer-remark: ^5.4.0 => 5.4.0 
    gatsby-transformer-sharp: ^4.4.0 => 4.4.0 
  npmGlobalPackages:
    gatsby-cli: 4.4.0
```

### Config Flags

All flags in this Gatsby starter are off.

**Comment by LinnJS** [comment]
[Issue I opened with Twind](https://github.com/tw-in-js/twind/issues/231)

**Comment by LekoArts** [comment]
Hi, please use https://github.com/tw-in-js/twind/issues/231 as this is not directly related to Gatsby. Thanks!
