### ISSUE TITLE
TypeError: Cannot read property 'childImageSharp' of undefined

### ISSUE THREAD

**Issue by MaralS** [gatsbyjs/gatsby#3437]
## TypeError: Cannot read property 'childImageSharp' of undefined

When I try to insert a featured image to my blog post ([following this tutorial](https://hunterchang.com/gatsby-featured-images/?utm_source=hashnode.com)) I got this error message : 
`GraphQL Error There was an error while compiling your site's GraphQL queries.
  Invariant Violation: GraphQLParser: Unknown field `image` on type `frontmatter_2`. Source: document `IndexQuery` file: `GraphQL request`.`

### Environment

Gatsby version: 1.1.27
Node.js version: v.8.9.3
Operating System: Mac OSX

### File contents (if changed):

`gatsby-config.js`: 

> module.exports = {
>   siteMetadata: {
>     title: `Contrôle technique des Hexagones`,
>     siteUrl: `https://www.autocontrole-hexagones.fr`
> 
>   },
>   plugins: [`gatsby-plugin-react-helmet`,
>     `gatsby-plugin-catch-links`, 
>     {
>       resolve: `gatsby-source-filesystem`,
>       options: {
>         path: `${__dirname}/src/pages/conseils`,
>         name: `conseils`,
>       },
>     },
>     {
>       resolve: `gatsby-transformer-remark`,
>       options: {
>         plugins: [] // just in case those previously mentioned remark plugins sound cool :)
>       }
>     },
>     {
>       resolve: `gatsby-plugin-sitemap`
>     },
>     {
>       resolve:  `gatsby-transformer-sharp`
>     },
>    {
>      resolve: `gatsby-plugin-sharp`
>    }
>           
> ],
> 
> }

`gatsby-node.js`: 

> const path = require('path');
> 
> exports.createPages = ({ boundActionCreators, graphql }) => {
>     const { createPage } = boundActionCreators;
> 
>     const blogPostTemplate = path.resolve(`src/templates/blog-post.js`);
> 
>     return graphql(`{
>     allMarkdownRemark(
>       sort: { order: DESC, fields: [frontmatter___date] }
>       limit: 1000
>     ) {
>       edges {
>         node {
>           excerpt(pruneLength: 250)
>           html
>           id
>           frontmatter {
>             date
>             path
>             title
>             image
>           }
>         }
>       }
>     }
>   }`)
>         .then(result => {
>             if (result.errors) {
>                 return Promise.reject(result.errors);
>             }
> 
>             result.data.allMarkdownRemark.edges
>                 .forEach(({ node }) => {
>                     createPage({
>                         path: node.frontmatter.path,
>                         component: blogPostTemplate,
>                         context: {} // additional data can be passed via context
>                     });
>                 });
>         });
> }

index.js in folder (/pages/conseils)

>  export const pageQuery = graphql`
>   query IndexQuery {
>     allMarkdownRemark(sort: { order: DESC, fields: [frontmatter___date] }) {
>       edges {
>         node {
>           excerpt(pruneLength: 250)
>           id
>           frontmatter {
>             title
>             date(formatString: "DD/MM/YYYY")
>             path
>             image {
>                 childImageSharp{
>                     sizes(maxWidth: 630) {
>                         ...GatsbyImageSharpSizes
>                     }
>                 }
>               }
>           }
>         }
>       }
>     }
>   }
> `;

`<Img sizes={post.frontmatter.image.childImageSharp.sizes} />`

### Actual result

`GraphQL Error There was an error while compiling your site's GraphQL queries.
  Invariant Violation: GraphQLParser: Unknown field `image` on type `frontmatter_2`. Source: document `IndexQuery` file: `GraphQL request`.`

### Expected behavior

A featured image expected to appear to index.js and blog post page.
[You can see all my files in my repo here](https://github.com/MaralS/autocontrole)
I'm really stuck, if anyone can help, I'd be very grateful ! Thanks in advance,

Kind regards

Maral

**Comment by zionis137** [comment]
As far as i can see you have no image field in the frontmatter of the [markdown](https://github.com/MaralS/autocontrole/blob/master/src/pages/conseils/12-12-2017-bonjour-tout-le-monde/index.md) file. 

Does it work if you add in your frontmatter:
```image: './image.png'```
 and a `image.png` in the directory ?

**Comment by MaralS** [comment]
@zionis137 I tried to add a .jpg file in the directory but I still have the same error message :/ 
`image: "./mercedes-benz.jpg"`

**Comment by MaralS** [comment]
@zionis137 I did `ctrl+c` and `yarn develop` and it worked. So I will close this ticket. :)

**Comment by adisher** [comment]
> @zionis137 I did `ctrl+c` and `yarn develop` and it worked. So I will close this ticket. :)

I did that but it didn't work for me. The only difference is I'm using npm instead of yarn.
