### ISSUE TITLE
Gatsby 4 migration issue : ModuleParseError: Module parse failed: Unexpected character '�' (1:0)

### ISSUE THREAD

**Issue by jonmadison-amzn** [gatsbyjs/gatsby#34382]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I am attempting to upgrade to gatsby 4 from gatsby 3, but am running into an issue that I can't properly diagnose, due to not enough information being displayed. This is for a private internal project so I will share as much as I'm able with regards to my configuration.  The only thing somewhat out of the ordinary is that I have.a PDF viewer as one of my pages (via `pdfjs-dist` package), and as such had to exclude `canvas` in the webpack config.

Below is what i think is the relevant portion of the error while running `gatsby develop --verbose`

```
verbose Transition to "runningQueries" > "done"
verbose Transition to "startingDevServers"

 ERROR 

Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)



  ModuleParseError: Module parse failed: Unexpected character '�' (1:0)
  You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
  (Source code omitted for this binary file)
  
  - NormalModule.js:969 handleParseError
    [DDG-AssetLibrary]/[webpack]/lib/NormalModule.js:969:19
  
  - NormalModule.js:1088 
    [DDG-AssetLibrary]/[webpack]/lib/NormalModule.js:1088:5
  
  - NormalModule.js:793 processResult
    [DDG-AssetLibrary]/[webpack]/lib/NormalModule.js:793:11
  
  - NormalModule.js:853 
    [DDG-AssetLibrary]/[webpack]/lib/NormalModule.js:853:5
  
  - LoaderRunner.js:406 
    [DDG-AssetLibrary]/[loader-runner]/lib/LoaderRunner.js:406:3
  
  - LoaderRunner.js:232 iterateNormalLoaders
    [DDG-AssetLibrary]/[loader-runner]/lib/LoaderRunner.js:232:10
  
  - LoaderRunner.js:223 
    [DDG-AssetLibrary]/[loader-runner]/lib/LoaderRunner.js:223:4
  
  - NormalModule.js:827 
    [DDG-AssetLibrary]/[webpack]/lib/NormalModule.js:827:15
  
  
  - CachedInputFileSystem.js:27 runCallbacks
    [DDG-AssetLibrary]/[enhanced-resolve]/lib/CachedInputFileSystem.js:27:15
  
  - CachedInputFileSystem.js:200 
    [DDG-AssetLibrary]/[enhanced-resolve]/lib/CachedInputFileSystem.js:200:4
  
  - graceful-fs.js:123 
    [DDG-AssetLibrary]/[graceful-fs]/graceful-fs.js:123:16
  
  - read_file_context:68 FSReqCallback.readFileAfterClose [as oncomplete]
    node:internal/fs/read_file_context:68:3
  

not finished Building development bundle - 3.011s
```

### Reproduction Link

N/A

### Steps to Reproduce

1. ncu -u, npm install
2. run `gatsby develop`

### Expected Result

dev server starts

### Actual Result

does not start, exits with error (see above) same thing for `gatsby build1

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.12.0 - ~/.nvm/versions/node/v16.12.0/bin/node
    Yarn: 1.22.10 - ~/.volta/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.12.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 91.4.0
    Safari: 15.2
  npmPackages:
    gatsby: ^4.4.0 => 4.4.0
    gatsby-image: ^3.11.0 => 3.11.0
    gatsby-plugin-image: ^2.4.0 => 2.4.0
    gatsby-plugin-postcss: ^5.4.0 => 5.4.0
    gatsby-plugin-react-helmet: ^4.10.0 => 4.14.0
    gatsby-plugin-s3: ^0.3.8 => 0.3.8
    gatsby-plugin-sharp: ^4.4.0 => 4.4.0
    gatsby-source-contentful: ^7.2.0 => 7.2.0
    gatsby-source-filesystem: ^4.4.0 => 4.4.0
    gatsby-transformer-remark: ^4.7.0 => 4.11.0
    gatsby-transformer-sharp: ^4.4.0 => 4.4.0
  npmGlobalPackages:
    gatsby-cli: 4.4.0
```

### Config Flags

  ```
flags: {
    DEV_SSR: false,
    FAST_DEV: false,
  },
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by jonmadison-amzn** [comment]
While I was hoping it would be something more immediately recognizable, I'll attempt to do a minimal repro this week.

Thanks!

jon

**Comment by LekoArts** [comment]
My only hunch on that issue would be that one of your packages (e.g. the PDF one) uses ES Modules and/or some exports logic that would tell webpack to use a "version" of the package that is not suitable for the frontend environment (I saw the issue last year and wrote about it: https://www.lekoarts.de/garden/using-package-exports-to-define-multiple-entrypoints)

**Comment by pachkovska** [comment]
I ran into same issue. The thing is error doesn't give an idea what package is causing it

**Comment by LekoArts** [comment]
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Comment by NobinPegasus** [comment]
I'm also facing the same error.

**Comment by cbroomemktw** [comment]
In my case I needed to add a new loader for compiled node files. 

First add the dependency: `npm i node-loader`

Then modify `gatsby-node` to update webpack:

```
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    module: {
      rules: [
        {
          test: /\.node$/,
          loader: 'node-loader'
        }
      ]
    }
  });
};
```

Of course your webpack config may already have some other custom stuff in there, you should add this new rule to that. 

YMMV, hopefully this helps
