### ISSUE TITLE
[gatsby-link] Error visiting internal links on new deploy

### ISSUE THREAD

**Issue by sarahatwork** [gatsbyjs/gatsby#3439]
## Description

In my networks panel:
<img width="576" alt="screenshot 2018-01-08 14 49 43" src="https://user-images.githubusercontent.com/11855531/34678083-59cb09d4-f492-11e7-9234-33da57b22dd2.png">

In console:
<img width="401" alt="screenshot 2018-01-05 18 00 52" src="https://user-images.githubusercontent.com/11855531/34678095-618d4c2c-f492-11e7-8200-0f9316e0d0c1.png">

I'm deploying my project via Netlify, with webhooks set up to trigger new builds anytime we update Github or Contentful. If you have an existing site window open and a new deploy finishes, any internal links fail with the errors/messages above.

At first I thought this was an edge case, but since deploys will be frequent (whenever the CMS is updated) it seems like a big issue. I assume the issue is that the JS bundle locations are changing, so the previous build's manifest links are no longer valid.

I've tried reproducing this issue on Gatsby test projects deployed to Netlify and can't get the same problem, so it's probably something specific to my environment.

The problem seems to go away when I disable downloading images. Right now, since my site needs to run in China where Contentful could conceivably someday be blocked, I download all Contentful images locally to `static/images` so they will be hosted on Netlify.

Like I said, this might be specific to my project, but any insights on how to troubleshoot this issue would be helpful. The error is getting throw in this file: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/loader.js#L369. But even when I try to log `err` I just get "true" so it's hard to get visibility into what's happening.

### Environment

Gatsby version: 1.9.63
Node.js version: 6.12.3
Operating System: (Netlify)

**Comment by KyleAMathews** [comment]
Hoping on a plane but `loader.js` is *supposed* to catch loading errors like this and force a refresh... https://github.com/gatsbyjs/gatsby/pull/2996

**Comment by sarahatwork** [comment]
Thanks @KyleAMathews - I updated Gatsby and it's working much better! Still feels a little slow, but much improved from before. Safe travels ✈️
