### ISSUE TITLE
[Netlify] SSR Page is not found in production build

### ISSUE THREAD

**Issue by marcomiduri** [gatsbyjs/gatsby#34398]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

This is the continuous issue of this ticket. https://github.com/gatsbyjs/gatsby/issues/33957 The issue is fixed but SSR pages are not found in the production build. I built the project using `yarn build` command and run `gatsby serve`. It worked fine on my local but if I deploy this on Netlify, it says 404 error. Do you have any idea?

### Reproduction Link

https://github.com/marcomiduri/gatsby-issue-reproduction

### Steps to Reproduce

1. `yarn build`
2. `gatsby serve`

### Expected Result

Pages shouldn't make 404 errors

### Actual Result

SSR pages are erroring 404 Not Found.

https://zen-tesla-a04fbb.netlify.app/1

### Environment

```shell
System:
  OS: Windows
Binaries:
  Node: v16.3.0
  NPM: 8.1.4
Gatsby: v4.4.0
```

**Comment by LekoArts** [comment]
Hi, please open a ticket/issue with Netlify as https://github.com/netlify/netlify-plugin-gatsby/ is making SSR work. Thanks!
