### ISSUE TITLE
Bug: Code tags within links wrap last-letter on Firefox

### ISSUE THREAD

**Issue by AnilSeervi** [gatsbyjs/gatsby#34412]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

## Problem as seen on Firefox
![image](https://user-images.githubusercontent.com/61609033/147843311-be98a289-947c-4017-96c5-ed3fdd61442c.png)

`<code>` blocks inside the `.main-body a` tags wrap the last-letter as shown in picture above.
Page-link - https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v1-to-v2/

Affected pages: All pages on `/docs`

### Reproduction Link

https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v1-to-v2/

### Steps to Reproduce

Visit pages with links with `<code>` tag

### Expected Result

As seen on chromium browsers

### Actual Result

`<code>` blocks inside the `.main-body a` tags wrap the last-letter

### Environment

```shell
Not applicable
```

**Comment by AnilSeervi** [comment]
Expected fix for the issue at:
- https://github.com/gatsbyjs/gatsby/discussions/34377#discussioncomment-1892854

**Comment by LekoArts** [comment]
Hi, thanks for the issue! We're not tracking .com bugs here so I created an internal ticket with a link to this issue here. Thanks!

**Comment by AnilSeervi** [comment]
> Hi, thanks for the issue! We're not tracking .com bugs here so I created an internal ticket with a link to this issue here. Thanks!

I created #34377 in discussions and also have provided a possible fix for the issue over there. It might be worth having a look at it!
