### ISSUE TITLE
[gatsby-plugin-mdx] Nodes created from Strapi api return null

### ISSUE THREAD

**Issue by shelleyphant** [gatsbyjs/gatsby#34420]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When using Strapi cms to create a blog post, I can successfully retrieve it using `gatsby-source-strapi`, but then when it comes to converting it to mdx to display on the site, all the created nodes return null. I thought it might have been an issue with the number of plugins/dependencies, but even on a fresh Gatsby project (linked below), the GraphiQL window is still reporting my nodes as null, even though it can see the Strapi data just fine. My reproduction link doesn't have the page templates, but let me know if you need them too.

### Reproduction Link

https://github.com/shelleyphant/elowen-test

### Steps to Reproduce

1. Install the repo
2. Run `npm run develop`
3. Open `http://localhost:8000/___graphql`
4. Use the following query to see the Strapi data and the Mdx null error
```
{
  strapiPosts {
    data {
      attributes {
        body
      }
    }
    childPostMd {
      body
    }
  }
}
```

### Expected Result

Before updating to Gatsby v4, my Mdx nodes were similar to the Strapi data ones, and able to be converted in the page template using MDXRenderer and MDXProvider

### Actual Result

Nodes are null so the page renders an error (Error in function _construct in ./node_modules/@babel/runtime/helpers/construct.js:19)

### Environment

```shell
System:
    OS: macOS 12.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - ~/.nvm/versions/node/v17.0.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v17.0.1/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Safari: 15.2
  npmPackages:
    gatsby: ^4.4.0 => 4.4.0 
    gatsby-plugin-mdx: ^3.4.0 => 3.4.0 
    gatsby-source-filesystem: ^4.4.0 => 4.4.0 
    gatsby-source-strapi: ^1.0.2 => 1.0.2 
  npmGlobalPackages:
    gatsby-cli: 4.2.0
```

**Comment by LekoArts** [comment]
Please report this to https://github.com/strapi/gatsby-source-strapi - thanks!
