### ISSUE TITLE
[gatsby-plugin-image] W3C validator flagging Gatsby Image generated picture and img tags

### ISSUE THREAD

**Issue by bnbabu55** [gatsbyjs/gatsby#34431]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

W3C reported a lot of errors on the picture, img tags generated by the Gatsby Image component, please visit the provided link to get the list of errors.

The site works fine and but the client insists that there should not be any errors in the site while validating using the W3C tool.

### Reproduction Link

https://validator.w3.org/nu/?showsource=yes&showoutline=yes&showimagereport=yes&doc=https%3A%2F%2Fpomareslawgroup.com%2F

### Steps to Reproduce

1. Goto the above URL, you will see the list of errors there.

### Expected Result
No errors are listed in W3C validator.

### Actual Result
When you visit the link provided, you will see for yourself all errors.

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.18
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.62)
  npmPackages:
    gatsby: ^4.4.0 => 4.4.0 
    gatsby-background-image: ^1.6.0 => 1.6.0 
    gatsby-plugin-advanced-sitemap: ^2.0.0 => 2.0.0 
    gatsby-plugin-image: ^2.4.0 => 2.4.0 
    gatsby-plugin-manifest: ^4.4.0 => 4.4.0 
    gatsby-plugin-offline: ^5.4.0 => 5.4.0 
    gatsby-plugin-perf-budgets: ^0.0.18 => 0.0.18 
    gatsby-plugin-postcss: ^5.4.0 => 5.4.0 
    gatsby-plugin-react-helmet: ^5.4.0 => 5.4.0 
    gatsby-plugin-react-intl: ^3.0.2 => 3.0.2 
    gatsby-plugin-schema-snapshot: ^3.4.0 => 3.4.0 
    gatsby-plugin-sharp: ^4.4.0 => 4.4.0 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.26 => 1.1.26 
    gatsby-source-filesystem: ^4.4.0 => 4.4.0 
    gatsby-source-wordpress: ^6.4.0 => 6.4.0 
    gatsby-transformer-remark: ^5.4.0 => 5.4.0 
    gatsby-transformer-sharp: ^4.4.0 => 4.4.0 
  npmGlobalPackages:
    gatsby-cli: 4.4.0
```

**Comment by LekoArts** [comment]
Hi!

The validator is only reading the HTML given to it, and not accounting any React rehydration that is happening on render.

![Bildschirmfoto 2022-01-10 um 08 18 20](https://user-images.githubusercontent.com/16143594/148730048-f15fd903-39c9-43b5-9338-c1068d24e1c0.png)

As you can see at the bottom the `<script>` is changing out the `data-*` attributes with their respective attributes. The plugin does this to improve speed up until the actual React rehydration. There's nothing we can do about "fixing" this as it's already working correctly, only the validator is incorrect.

Hope that helps!

**Comment by bnbabu55** [comment]
> Hi!
> 
> The validator is only reading the HTML given to it, and not accounting any React rehydration that is happening on render.
> 
> ![Bildschirmfoto 2022-01-10 um 08 18 20](https://user-images.githubusercontent.com/16143594/148730048-f15fd903-39c9-43b5-9338-c1068d24e1c0.png)
> 
> As you can see at the bottom the `<script>` is changing out the `data-*` attributes with their respective attributes. The plugin does this to improve speed up until the actual React rehydration. There's nothing we can do about "fixing" this as it's already working correctly, only the validator is incorrect.
> 
> Hope that helps!

Thanks for the information Lennart, I have created a new ticket in the **validator** tool repo, let's hope they resolve this soon. I am sure lot many people would want this resolved soon too.
