### ISSUE TITLE
Caching build files?

### ISSUE THREAD

**Issue by AnalogMemory** [gatsbyjs/gatsby#3444]
Does Gatsby have any way to cache the build files that end up in /public? 

If I make one text change it takes about 5 minutes to rebuild everything. I have about 300 posts so this delay is magnified for me. Is there a way to have only rebuild the post that changed?

Here's the part of the build output

```
$ gatsby build
success delete html files from previous builds — 0.019 s
success open and validate gatsby-config.js — 0.008 s
success copy gatsby files — 0.045 s
success onPreBootstrap — 0.045 s

=START PLUGIN=====================================
... getting API data
=END PLUGIN=====================================: 5561.419ms

success source and transform nodes — 9.566 s
success building schema — 4.381 s
success createLayouts — 0.022 s
success createPages — 1.522 s
success createPagesStatefully — 0.029 s
success onPreExtractQueries — 0.008 s
success update schema — 2.999 s
success extract queries from components — 0.470 s
success run graphql queries — 0.023 s
success write out page data — 0.021 s
success write out redirect data — 0.002 s
success onPostBootstrap — 0.001 s

info bootstrap finished - 24.473 s

success Building CSS — 12.945 s
success Building production JavaScript bundles — 45.886 s
success Building static HTML for pages — 12.871 s
info Done building in 96.186 sec
```

**Comment by IridescentIndia** [comment]
Assuming some sort of caching of API data is implemented in the future, would it work for the case of CI/CD with Netlify?

**Comment by Jaikant** [comment]
Assuming some sort of caching of API data is implemented in the future, would it work for the case of CI/CD with Netlify?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
