### ISSUE TITLE
Node-Links are breaking when content changes

### ISSUE THREAD

**Issue by f-kottek** [gatsbyjs/gatsby#34456]
Hey everybody,

### Brief description of the issue:
When content in json-files (I'm not sure if the format matters in this case tho) changes, node links will break, thus making following builds break.

### reproduction repository
https://github.com/f-kottek/gatsby-breaking-node-links-demo

### more thorough description:
Articles are stored as JSON-Files in a cloud storage. In the reproduction repository they're stored in folder locally, but that doesn't make a difference for the issue -> builds still break. Just keep in mind that we cant use relative links to images referenced in these files, since they're NOT store locally in production. 
Articles look something like this:
```
[
...,
{
    "title": "article-2",
    "text_content": "article-2 content",
    "images": [
      {
        "url": "https://images.unsplash.com/photo-1493397212122-2b85dda8106b"
      },
      {
        "url": "https://images.unsplash.com/photo-1511818966892-d7d671e672a2"
      },
      {
        "url": "https://images.unsplash.com/photo-1435575653489-b0873ec954e2"
      }
    ],
    "thumbnail_url": "https://images.unsplash.com/photo-1516205651411-aef33a44f7c2"
  },
...,
]
```
The important parts of `gatsby-node.js` are: (See code comments and below for the temporary fix of this issue)
```
exports.sourceNodes = async ({
  actions: { createNode, createNodeField },
  createContentDigest,
  createNodeId,
  getCache,
  getNodesByType,
}) => {
  // this is needed for the fix, unused, when part 1 and 2 are commented out
  const all_cached_file_nodes = await getNodesByType(`File`)

  const promisedArticles = allArticles.map(async article => {
    const { title, images, thumbnail_url, text_content } = article

    const article_node_id = createNodeId(title)

    const all_article_image_nodes = await Promise.all(
      images?.map(async ({ url }) => {
        let articleImageNode

        // Part 1 of the fix here

        // const cached_image_node = all_cached_file_nodes.find(
        //   image => image.url === url
        // )
        // if (!cached_image_node) {

        try {
          articleImageNode = await createRemoteFileNode({
            url: url,
            parentNodeId: article_node_id,
            createNode,
            createNodeId,
            getCache,
          })
        } catch (error) {
          console.log(error)
        }

        // Part 2, uncomment these two to keep the build running after chaning the json file
        // } else {
        //   articleImageNode = cached_image_node
        // }
        return articleImageNode
      })
    )

    let thumbnailImageNode

    try {
      thumbnailImageNode = await createRemoteFileNode({
        url: thumbnail_url,
        parentNodeId: article_node_id,
        createNodeId,
        createNode,
        getCache,
      })
    } catch (error) {
      console.log(error)
    }

    const articleNode = await createNode({
      article_images: all_article_image_nodes?.map(({ id }) => id),
      thumbnail: thumbnailImageNode?.id,
      id: article_node_id,
      parent: null,
      children: [],
      internal: {
        type: `BlogArticle`,
        contentDigest: createContentDigest(article),
      },
    })
    return articleNode
  })
  await Promise.all(promisedArticles)
}

exports.createSchemaCustomization = ({ actions }) => {
  const { createTypes } = actions
  const typeDefs = `
    type BlogArticle implements Node {
      article_images: [File] @link,
      thumbnail: File @link
    }
  `
  createTypes(typeDefs)
}
```

### Steps to reproduce

1. run `gatsby build` 
2. remove one object from any of the `images` arrays inside `src/data/articles.json`. I like to simply cut the object from the file and paste (and comment) it into the `blog-article.js` template, so I can redo the step relatively easy. Dont paste it into one of the API files though! 
3. run `gatsby build` again **without(!)** deleting/clearing the cache and **without(!)** making changes to the config or any other Node file. (invalidates the cache also)

### Expected result
Build should run fine, all images, expect the removed one, should be there. 

### Actual result
Build breaks, all image links INSIDE the article are broken, linked thumbnails still work. (See screenshots of both the 1st working build and the 2nd failing one below)

#### Working build, all images are referenced, thumbnails too, but not shown in screenshot
![working build](https://github.com/f-kottek/gatsby-breaking-node-links-demo/blob/master/readme-content/gatsby-dev-working.png?raw=true)

#### Failing build, all image references are broken, "article_images" only consists of ids, thumbnails still work
![failing build](https://github.com/f-kottek/gatsby-breaking-node-links-demo/blob/master/readme-content/gatsby-dev-crashing.png?raw=true)

### Environment

- no .env Vars needed
- Node Version 16.13.1
- build crashing both in Gatsby Cloud and locally (AMD Ryzen 5 5600x, 16gig ram, Win 10)

### Config Flags
PRESERVE_FILE_DOWNLOAD_CACHE: true
-> I'm not sure if this would make a difference, but it would be a shame, since re-downloading all files every time you for example add a simple comment inside `gatsby-node.js` would be a huge waste

### My "fix": (see reproduction repo for reference)
In `gatsby-node` you can see some commented code, that sort of manually gets cached image nodes and links those to the `BlogArticle`-nodes. You can see this working when you un-comment these lines (the code ones of course, not the "actual" comments 😉) and then build -> make said change to the `articles.json` -> DONT delete the cache or make a change to one of the API files -> rebuild w/ cache -> profit.

### My suspicion: 
Could the error arise, because I'm using an async map-function to create image nodes? Thumbnails still work and there is only one per article. Could also just as well be a coincidence...

original comment here
https://github.com/gatsbyjs/gatsby/discussions/32860#discussioncomment-1918870_

**Comment by LekoArts** [comment]
Hi!

Please fill out the issue template as while instructions in a repo are really appreciated, you might delete this in the future and then that information would be lost. Here's the template:

```md
### Description

### Reproduction Link

### Steps to Reproduce

### Expected Result

### Actual Result

### Environment

### Config Flags
```

**Comment by f-kottek** [comment]
Hey @LekoArts, 
I edited the initial issue to fit the template. I thought a repo with a decent README would be sufficient but I haven't thought of what would happen if I delete it... ^^

I'm happy to help, if need be!
