### ISSUE TITLE
Error: `_gatsbyCoreUtils.updateSiteMetadata` is not a function

### ISSUE THREAD

**Issue by MJWils** [gatsbyjs/gatsby#34455]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

After following the steps to use the gatsby image plugin, found on https://www.gatsbyjs.com/plugins/gatsby-plugin-image, my terminal refuses to run gatsby develop.

<img width="595" alt="Screenshot 2022-01-12 at 08 07 43" src="https://user-images.githubusercontent.com/68286467/149088154-1f09a76b-d2ee-4d71-8dff-b2dc389ea01b.png">

I'm guessing there's an issue somewhere inside my installation of Gatsby, because this error is reproduced on the most barebones of websites, see the [repo](https://github.com/MJWils/gatsby-imageplugin-bug) / [sandbox](https://codesandbox.io/s/sad-payne-2g271?file=/src/pages/index.js) .

### Reproduction Link

https://github.com/MJWils/gatsby-imageplugin-bug

### Steps to Reproduce

1. npm install -g gatsby-cli
2. gatsby new
3. npm install gatsby-plugin-image gatsby-plugin-sharp gatsby-source-filesystem gatsby-transformer-sharp
4. module.exports = {
  plugins: [
    +++ `gatsby-plugin-image`,
    +++ `gatsby-plugin-sharp`,
    +++ `gatsby-transformer-sharp`, // Needed for dynamic images
  ],
}
...

### Expected Result

I expected to be able to use the plugin.

### Actual Result

I was not able to use the plugin, and gatsby develop throws an UNHANDLED REJECTION error. 

### Environment

```shell
System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    npm: 8.1.0 - /opt/homebrew/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 95.0.2
    Safari: 15.0
  npmPackages:
    gatsby: ^4.4.0 => 4.4.0 
    gatsby-plugin-image: ^2.5.0 => 2.5.0 
    gatsby-plugin-postcss: ^5.5.0 => 5.5.0 
    gatsby-plugin-sharp: ^4.5.0 => 4.5.0 
    gatsby-source-filesystem: ^4.5.0 => 4.5.0 
    gatsby-transformer-sharp: ^4.5.0 => 4.5.0
```

**Comment by LekoArts** [comment]
Hi!

Please update your `gatsby-cli` to `4.5.0` (by rerunning `npm install -g gatsby-cli`) or run `npm run develop` in the repository itself. Let me know if that helped. Thanks!

**Comment by plourenco** [comment]
I can confirm the above fixes the problem.

**Comment by JenniferFalkenstein** [comment]
I ran into this problem too and updating the `gatsby-cli` didn't work unfortunately... Here are the versions I use:
```
    "gatsby": "^4.4.0",
    "gatsby-core-utils": "^2.9.0",
    "gatsby-plugin-image": "^2.4.0",
    "gatsby-plugin-manifest": "^4.4.0",
    "gatsby-plugin-offline": "^5.4.0",
    "gatsby-plugin-react-helmet": "^5.4.0",
    "gatsby-plugin-sharp": "^4.4.0",
    "gatsby-source-filesystem": "^4.4.0",
    "gatsby-transformer-sharp": "^4.4.0",
    "npm": "^7.19.1",
    "prism-react-renderer": "^1.2.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-helmet": "^6.1.0",
    "react-spring": "^9.2.3",
```

**Comment by MJWils** [comment]
> Hi!
> 
> Please update your `gatsby-cli` to `4.5.0` (by rerunning `npm install -g gatsby-cli`) and update `gatsby` to `4.5.0` or run `npm run develop` / `npm run build` in the repository itself. Let me know if that helped. Thanks!

Hi LekoArts,

Thanks for coming to help. After some time I managed to figure it out, `npm install --force gatsby@latest` did the trick. I think the issue was my Gatsby version not matching the cli version. Odd. 

Thanks again.

**Comment by MJWils** [comment]
> I ran into this problem too and updating the `gatsby-cli` didn't work unfortunately... Here are the versions I use:
> 
> ```
>     "gatsby": "^4.4.0",
>     "gatsby-core-utils": "^2.9.0",
>     "gatsby-plugin-image": "^2.4.0",
>     "gatsby-plugin-manifest": "^4.4.0",
>     "gatsby-plugin-offline": "^5.4.0",
>     "gatsby-plugin-react-helmet": "^5.4.0",
>     "gatsby-plugin-sharp": "^4.4.0",
>     "gatsby-source-filesystem": "^4.4.0",
>     "gatsby-transformer-sharp": "^4.4.0",
>     "npm": "^7.19.1",
>     "prism-react-renderer": "^1.2.1",
>     "react": "^17.0.1",
>     "react-dom": "^17.0.1",
>     "react-helmet": "^6.1.0",
>     "react-spring": "^9.2.3",
> ```

Hi Jennifer, I can see you have the same issue as me regarding the Gatsby version being 4.4. Try running `npm install --force gatsby@latest` or `npm install gatsby@latest` (if your pc is more friendly).

**Comment by LekoArts** [comment]
I'll publish a new version of `gatsby-core-utils` (which is an internal dependency) so that you won't run into this.
