### ISSUE TITLE
[gatsby-source-contentful]: Asset nodes do not expose `metadata.tags` when `enableTags` flag is enabled

### ISSUE THREAD

**Issue by mike-plummer** [gatsbyjs/gatsby#34450]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When the `enableTags` flag is enabled, Contentful Entry nodes expose a `metadata.tags` field in GraphQL with the public tags applied in Contentful. ContentfulAsset nodes do not appear to expose this data, even though they have public tags applied and published in Contentful.

It appears that the plugin attempts to handle tags for entry nodes, but not for asset nodes:

gatsby-source-contentful, `src/normalize.js`

```
// Link tags
if (pluginConfig.get(`enableTags`)) {
  entryNode.metadata = {
    tags___NODE: entryItem.metadata.tags.map(tag =>
      createNodeId(`ContentfulTag__${space.sys.id}__${tag.sys.id}`)
    ),
  }
}
```
No corresponding logic for asset nodes

### Reproduction Link

https://github.com/mike-plummer/gatsby-contentful-asset-tag-repro

### Steps to Reproduce

1. Clone reproduction repo, add SpaceID and AccessToken for a Contentful space to `.env`
2. In Contentful, upload a PDF asset. Add one or more public tags, publish.
3. In Contentful, create a simple ContentType, create an instance of that ContentType and add one or more public tags, publish
4. Launch Gatsby app in development mode, navigate to GraphQL explorer (http://localhost:8000/___graphql)

### Expected Result

1. All contentful tags appear as `ContentfulTag` nodes in GraphQL
2. Contentful content entries expose a `metadata.tags` field
3. Contentful asset entries expose a `metadata.tags` field

### Actual Result

1. Contentful tag entries appear as expected
2. Contentful content entries expose tags as expected under `metadata.tags`
3. Contentful asset nodes **_do not_** expose a `metadata.tags` field

### Environment

```shell
System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.9.1 - ~/.nvm/versions/node/v16.9.1/bin/node
    npm: 7.21.1 - ~/.nvm/versions/node/v16.9.1/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 95.0.2
    Safari: 15.2
  npmPackages:
    gatsby: ^4.5.0 => 4.5.0
    gatsby-plugin-image: ^2.5.0 => 2.5.0
    gatsby-source-contentful: ^7.3.0 => 7.3.0
  npmGlobalPackages:
    gatsby: 4.5.0
```

**Comment by axe312ger** [comment]
Hey Mike,

thank you for the report. This is was definitely overlooked in the initial implementation.

I'll provide a patch today for code & tests.

Stay tuned,
Benedikt

**Comment by axe312ger** [comment]
Fix PR available at https://github.com/gatsbyjs/gatsby/pull/34480

**Comment by axe312ger** [comment]
Great and thank you @LekoArts! So this fix should be part of the next GatsbyJS release :)

**Comment by StanLepunK** [comment]
I'm in the same scenario, I cannot access to the tag in the `allContentfulAsset`
my configuration is correct, I think 
`package.json`
```
"dependencies": {
    "@emotion/react": "^11.7.1",
    "@material-ui/core": "^4.12.3",
    "@material-ui/icons": "^4.11.2",
    "axios": "^0.25.0",
    "gatsby": "^4.5.3",
    "gatsby-plugin-image": "^2.5.2",
    "gatsby-plugin-manifest": "^4.5.2",
    "gatsby-plugin-material-ui": "^4.1.0",
    "gatsby-plugin-offline": "^5.5.2",
    "gatsby-plugin-react-helmet": "^5.5.0",
    "gatsby-plugin-sharp": "^4.5.2",
    "gatsby-plugin-web-font-loader": "^1.0.4",
    "gatsby-source-contentful": "^7.3.2",
    "gatsby-source-filesystem": "^4.5.2",
    "gatsby-source-mongodb": "^4.5.0",
    "gatsby-transformer-sharp": "^4.5.0",
    "p5": "^1.4.0",
    "prop-types": "^15.8.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-helmet": "^6.1.0"
  },
```

`gatsby-config.js`
```
// CONTENTFUL
    {
      resolve: `gatsby-source-contentful`,
      options: {
        spaceId: process.env.CONTENTFUL_SPACE_ID,
        // Learn about environment variables: https://gatsby.dev/env-vars
        accessToken: process.env.CONTENTFUL_ACCESS_TOKEN,
        enableTags: true,
      },
    },
```
But in the `graphQl`i find no trace of tag or metadata, I'm not an expert, but We don't find a solution with M. Ferran Buireu on [stackOverflow ](https://stackoverflow.com/questions/70759297/sort-allcontentasset-by-tag-in-gatsby-is-it-possible)

when I write this code in the graph
```
allContentfulAsset(
   filter: {metadata: { tags: { in: ["art work", "vies paralleles"] } }}) {
  edges { node { title }}} 
```
this message is returned `Field "Metadata" is not defined by type "ContentfulAssetFilterInput"` That's can be normal because I found no trace of `tag` or `metadata` in tree
for information, a screenshot of my graph
<img width="262" alt="Capture d’écran 2022-01-20 à 16 16 55" src="https://user-images.githubusercontent.com/3332269/150367777-7a0febf4-aefc-427f-819c-6c80e84971b1.png">

**Comment by baparham** [comment]
This seems to still reproduce with 8.12.0 (possibly others, but that's the version I have now). I get the same exact error message when attempting to filter `allContentfulAsset` on tags. There is no metadata listed.

I have pushed a minimal reproducer to https://github.com/baparham/gatsby-source-contentful-asset-tag-reproducer

What's odd is that I see there are e2e tests for this, any ideas if this is a misconfiguration on my part? I have `enableTags` as true, I have valid media assets in Contentful with tags attached (though they don't have entries linked to them...could that be keeping those assets from downloading and showing up in my graphql query?)

**Comment by baparham** [comment]
> This seems to still reproduce with 8.12.0 (possibly others, but that's the version I have now). I get the same exact error message when attempting to filter `allContentfulAsset` on tags. There is no metadata listed.
> 
> I have pushed a minimal reproducer to https://github.com/baparham/gatsby-source-contentful-asset-tag-reproducer
> 
> What's odd is that I see there are e2e tests for this, any ideas if this is a misconfiguration on my part? I have `enableTags` as true, I have valid media assets in Contentful with tags attached (though they don't have entries linked to them...could that be keeping those assets from downloading and showing up in my graphql query?)

ugh, oh no... they hadn't been published after I added the tags to the assets.

Forgive the false alarm...things seem to be working fine!
