### ISSUE TITLE
Is there any way to reduce bundle size?

### ISSUE THREAD

**Issue by arnondora** [gatsbyjs/gatsby#3445]
I use Gatsby for 200+ pages but my bundle size which are built by `gatsby build` is very large (around 1 GB). Is there any way reducing the size?

**Comment by LeKoArts** [comment]
I‘d suggest looking into the bundle first:
https://www.npmjs.com/package/source-map-explorer

Maybe you can find big „unnecessary“ packages there.

**Comment by KyleAMathews** [comment]
+1 to source-map-explorer.

Also 1 gb is incredibly big :-) very curious how that happened.

**Comment by arnondora** [comment]
So where and how can I put this thing to my code?

**Comment by KyleAMathews** [comment]
Try watching their demo movie to understand how to use it https://www.youtube.com/watch?v=7aY9BoMEpG8

**Comment by arnondora** [comment]
I ran `gatsby build` and `source-map-explorer path---38-bc6ef7e5e0fcb1e0bf78.js render-page.js.map` and it return an error

```
buffer.js:495
    throw new Error('"toString()" failed');
    ^

Error: "toString()" failed
    at Buffer.toString (buffer.js:495:11)
    at loadSourceMap (/usr/local/share/.config/yarn/global/node_modules/source-map-explorer/index.js:122:50)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/source-map-explorer/index.js:221:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
```

**Comment by KyleAMathews** [comment]
It does the same thing every time you run `source-map-explorer`?

**Comment by arnondora** [comment]
No, only when I run with my gatsby project. I have tried to run on simple react-app, it works! @KyleAMathews

**Comment by arnondora** [comment]
I try source-map-explorer with one of the js file in public after ran `gatsby-develop`. It doesn't tell anything. How can I generate fully bundle.js ? @KyleAMathews 

<img width="1280" alt="screen shot 2561-01-15 at 1 36 43 am" src="https://user-images.githubusercontent.com/4264361/34919335-c07010e2-f994-11e7-8c41-f202f6037e0b.png">

**Comment by KyleAMathews** [comment]
Run "gatsby build" first.

**Comment by arnondora** [comment]
If I run using build file, I will got the error that I mentioned.

**Comment by arnondora** [comment]
I have found the reason why the bundle size is so huge. I looked into the `path—___.js` File, I found the large amout of data that is not necessary from `pathContext` prop. So I filter the necessary data from `gatsby-node.js`. The bundle of the path file size is reduce from 2.1 MB to 15 kB

**Comment by Teo0303** [comment]
> I have found the reason why the bundle size is so huge. I looked into the `path—___.js` File, I found the large amout of data that is not necessary from `pathContext` prop. So I filter the necessary data from `gatsby-node.js`. The bundle of the path file size is reduce from 2.1 MB to 15 kB

How did you do that?

**Comment by arnondora** [comment]
I used the **pick** method form **lodash** lib to filter the field that I don't use in the view

`
const _ = require('lodash')
post = _.pick(post, ['node.fields.slug', 'node.frontmatter.title', 'node.frontmatter.excerpt', 'node.frontmatter.category', 'node.frontmatter.date', 'node.frontmatter.author', 'node.frontmatter.image'])
`

you can find more information about the method on my repository.
https://github.com/arnondora/arnondoraBlog
