### ISSUE TITLE
Project Showcase: Navigation dropdowns hide behind project screenshots making them inaccessible

### ISSUE THREAD

**Issue by AnilSeervi** [gatsbyjs/gatsby#34475]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

The navigation dropdowns on any specific project showcase page hide under the project showcase screenshot as shown below

![image](https://user-images.githubusercontent.com/61609033/149317616-1f59a888-f546-4765-aabc-35e11459f44a.png)

### Steps to Resolve this Issue

Resolve The stacking context

**Comment by LekoArts** [comment]
Thanks, I've forwarded it internally!
