### ISSUE TITLE
Webpack file changes not properly detected inside docker container

### ISSUE THREAD

**Issue by SaculRennorb** [gatsbyjs/gatsby#34497]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When calling develop for the provided repo inside a docker container hot reloading files in the mounted volume does not work. A change is detected and a recompile is triggered, but notably the line `Webpack file changed: [...]\app\src\pages\index.js` is missing in the debug output if running inside a container. On the browser side of things this is also reflected by the line `[HMR] Nothing hot updated.`. It seems as if there are two different change detections at work and one does not fire, but i have no clue if that is actually whats happening.

The repro repo is just the gatsby default starter with `-H 0.0.0.0 --verbose` added to the develop command and a docker setup added.

### Reproduction Link

https://github.com/SaculRennorb/gatsby_hot_reloading_bug

### Steps to Reproduce

host:
1. clone the provided repo
2. enter the directory
2. `npm i`
3. `npm run develop`
4. wait for the server to boot
4. change something in the source and save the file
5. works as expected

docker:
1. clone the provided repo
2. enter the directory
3. `docker-compose up`
4. wait for the server to boot
4. change something in the source and save the file
4. hot reloading does not work (`[HMR] Nothing hot updated.`)

### Expected Result

after changing something in the source while running natively:
```
[....]
verbose Transition to "waiting" > "aggregatingFileChanges"
verbose Webpack file changed: C:\Users\Rennorb\source\repos\gatsby_hot_reloading_bug\app\src\pages\index.js
verbose Transition to "runningQueries"
[....]
```

### Actual Result

after changing something in the source while running in docker:
```
[....]
verbose Transition to "waiting" > "aggregatingFileChanges"
verbose Transition to "runningQueries"
[....]
```

### Environment

```shell
inside docker:
  System:
    OS: Linux 4.19 Alpine Linux
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Shell: 1.31.1 - /bin/ash
  Binaries:
    Node: 17.3.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.0 - /usr/local/bin/npm
  npmPackages:
    gatsby: ^4.5.2 => 4.5.2
    gatsby-plugin-gatsby-cloud: ^4.5.1 => 4.5.1
    gatsby-plugin-image: ^2.5.1 => 2.5.1
    gatsby-plugin-manifest: ^4.5.1 => 4.5.1
    gatsby-plugin-offline: ^5.5.1 => 5.5.1
    gatsby-plugin-react-helmet: ^5.5.0 => 5.5.0
    gatsby-plugin-sharp: ^4.5.1 => 4.5.1
    gatsby-source-filesystem: ^4.5.1 => 4.5.1
    gatsby-transformer-sharp: ^4.5.0 => 4.5.0
```

**Comment by JDDoesDev** [comment]
I am also dealing with this same issue.  I can see the HMR process working in the browser console as well as in the gatsby develop feed, but the file itself is not being marked as changed
```verbose Transition to "waiting" > "aggregatingFileChanges"
verbose Transition to "runningQueries"
success onPreExtractQueries - 0.006s
success extract queries from components - 0.280s
verbose Transition to "runningQueries" > "waitingPendingQueries"
verbose Transition to "runningQueries" > "writingRequires"
success write out requires - 0.015s
verbose Transition to "runningQueries" > "calculatingDirtyQueries"
verbose Transition to "runningQueries" > "runningStaticQueries"
verbose Transition to "runningQueries" > "runningPageQueries"
verbose Transition to "runningQueries" > "waitingForJobs"
verbose Transition to "runningQueries" > "done"
verbose Transition to "recompiling"
success Writing page-data.json files to public directory - 0.156s - 0/1 6.41/s
success Re-building development bundle - 1.248s
verbose Transition to "waiting"
```
and in the browser:
```
[HMR] bundle 'develop' rebuilt in 785ms
process-update.js:51 [HMR] Checking for updates on the server...
process-update.js:123 [HMR] Nothing hot updated.
process-update.js:132 [HMR] App is up to date.
```

**Comment by pieh** [comment]
Hey @SaculRennorb and @JDDoesDev

Can you try https://github.com/gatsbyjs/gatsby/issues/4109#issuecomment-667628363 ?

**Comment by JDDoesDev** [comment]
@pieh Unfortunately, that did not help.

Here is what I got: 
```
verbose Transition to "waiting" > "aggregatingFileChanges"
verbose Transition to "runningQueries"
success onPreExtractQueries - 0.004s
success extract queries from components - 0.472s
verbose Transition to "runningQueries" > "waitingPendingQueries"
verbose Transition to "runningQueries" > "writingRequires"
success write out requires - 0.020s
verbose Transition to "runningQueries" > "calculatingDirtyQueries"
verbose Transition to "runningQueries" > "runningStaticQueries"
success run static queries - 0.050s - 1/1 19.87/s
verbose Transition to "runningQueries" > "runningPageQueries"
verbose Transition to "runningQueries" > "waitingForJobs"
verbose Transition to "runningQueries" > "done"
verbose Transition to "recompiling"
success Writing page-data.json files to public directory - 0.078s - 0/1 12.87/s
success Re-building development bundle - 0.711s
verbose Transition to "waiting"
success Writing page-data.json files to public directory - 0.128s - 1/2 15.63/s
```
and in the inspector console:

```
[HMR] connected
client.js:250 [HMR] bundle 'develop' rebuilt in 822ms
client.js:250 [HMR] bundle 'develop' rebuilt in 627ms
```

The page appeared to reload, but changes were not reflected in the browser.

**Comment by JDDoesDev** [comment]
Interesting find:  If I make changes to metadata like in `gatsby-config.js`
```
module.exports = {
    siteMetadata: {
      title: `My Site`,
      description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
      author: `@gatsbyjs`,
      siteUrl: `https://www.yourdomain.tld`,
    },
  }
```
then save, those changes are reflected.  It appears that it's data in components that isn't being updated, such as styling and props that are being used.

**Comment by pieh** [comment]
@JDDoesDev

Ah sorry, the snippet I pasted was for older webpack version than what currently is used. Please try:

```
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    watchOptions: {
      aggregateTimeout: 200,
      poll: 1000,
    },
  })
}
```

I did test run this in docker - but I did mount local fs (not volume as described by OP, just to test quicker without setting up volume stuff, not sure if it matters or not, given that this force polling instead of relying on some form of fs events, it shouldn't but 🤷 ).

The part about changing `gatsby-config` (well any "data" file, like markdown files etc) - this part is using different file watcher than "frontend code" (for frontend, files is watched by webpack internals). In particular `gatsby-config` is using `chokidar` (in the past webpack used to use `chokidar` under the hood, but they moved to different, in-house implementation some time ago). I do wonder wether you might have `CHOKIDAR_USEPOLLING` env set in your docker image that make chokidar backed watchers work

**Comment by SaculRennorb** [comment]
this seems to work! i removed `GATSBY_WEBPACK_PUBLICPATH: /` and `CHOKIDAR_USEPOLLING: 'true'` from the docker-compose as it does not seem necessary anymore. for anyone looking for what exactly i did; i pushed my changes to get a working version to the repro repo. **This should definitely be easily accessible in the documentation**, i cant imagine i'm the only person that tries to use gatsby inside a container.

**Comment by xaviemirmon** [comment]
In case anyone stumbles across this one, adding `CHOKIDAR_USEPOLLING=true` as an environment variable is also **required** if you are using .MD/.MDX.

I've written a blog post about it [here](https://blog.xavie.mirmon.co.uk/running-gatsby-inside-a-docker-container-on-macos-5e98a77787df).
