### ISSUE TITLE
Gatsby 4: webpack caching errors when a .pack file is > 2GB

### ISSUE THREAD

**Issue by odunet** [gatsbyjs/gatsby#34506]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

We have a large app in a monorepo using Gatsby (v.4.5.2). We have thousands of errors logged in the console in every 2nd consecutive warm **development build**. We observed that this occurs only when the app builds enough pages to make the size of the generated .pack file greater 2GB. When we generate fewer pages, and our webpack .pack file goes below 2GB, we have a clean build without errors. 

The first, second development build runs without the webpack cache error, but on subsequent warm build runs (with no code changes)

The reproduction repo below has 100 pages to mimics our large app. The issue continues as more pages are added. However, once the number pages in the app is reduced enough to cause webpack's .pack file to be < 2GB, the error no longer occurs.

See possible related issue: [webpack#14907](https://github.com/webpack/webpack/issues/14907)

### Reproduction Link

https://github.com/odunet/gatsby-v4-test

### Steps to Reproduce

```
git clone git@github.com:odunet/gatsby-v4-test.git
cd gatsby-v4-test
yarn install
yarn clean

# Cold development build below
yarn develop  
Ctrl + C

# 1st warm development build below
yarn develop
Ctrl + C

# 2nd warm development build below
yarn develop
```

### Expected Result

I expect a clean build on the 3rd run of gatsby develop build (i.e. `yarn develop`).

### Actual Result

I got the warnings shown below.

The errors below were logged in the console:
```
...
<w> [webpack.cache.PackFileCacheStrategy] Restoring failed for Compilation/modules|/Users/odunet/Documents/company/production_Gatsby/gatsby/node_modules/lodash/merge.js from pack: TypeError: Cannot read property 'length' of undefined
<w> [webpack.cache.PackFileCacheStrategy] Restoring failed for Compilation/modules|external commonjs "/Users/odunet/Documents/companyr/production_Gatsby/gatsby/node_modules/react-dom/server.js" from pack: TypeError: Cannot read property 'length' of undefined
<w> [webpack.cache.PackFileCacheStrategy] Restoring failed for ResolverCachePlugin|normal|dependencyType=|commonjs|path=|/Users/odunet/Documents/company/production_Gatsby/gatsby/node_modules/lodash|request=|./_baseMerge from pack: TypeError: Cannot read property 'length' of undefined
...
...
```
```
...
<w> [webpack.cache.PackFileCacheStrategy] Restoring failed for Compilation/codeGeneration|/Users/odunet/Documents/company/production_Gatsby/gatsby/node_modules/gatsby/dist/utils/babel-loader.js??ruleSet[1].rules[2].use[0]!/Users/odunet/Documents/company/production_Gatsby/gatsby/packages/02-functional/shared-components/src/components/stock/stock-card/stock-card-section-wishlist.jsx|render-page from pack: TypeError: Cannot read property 'length' of undefined
<w> [webpack.cache.PackFileCacheStrategy] Restoring failed for Compilation/codeGeneration|/Users/odunet/Documents/company/production_Gatsby/gatsby/node_modules/gatsby/dist/utils/babel-loader.js??ruleSet[1].rules[2].use[0]!/Users/odunet/Documents/company/production_Gatsby/gatsby/packages/02-functional/shared-components/src/components/stock/stock-card/stock-card-section-body.jsx|render-page from pack: TypeError: Cannot read property 'length' of undefined
...
```
```
...
<w> [webpack.cache.PackFileCacheStrategy] Restoring failed for ResolverCachePlugin|normal|dependencyType=|commonjs|path=|/Users/odunet/Documents/company/production_Gatsby/gatsby/node_modules/axios/lib/adapters|request=|../core/enhanceError from pack: TypeError: Cannot read property 'length' of undefined
<w> [webpack.cache.PackFileCacheStrategy] Restoring failed for ResolverCachePlugin|normal|dependencyType=|commonjs|path=|/Users/odunet/Documents/company/production_Gatsby/gatsby/node_modules/axios/lib/adapters|request=|./../helpers/cookies from pack: TypeError: Cannot read property 'length' of undefined
...
```
\
Additional snapshot of errors:
![Screen Shot 2022-01-17 at 1 12 51 pm](https://user-images.githubusercontent.com/40292574/149690195-8bcf39aa-2a42-4c14-b061-ebc4a8c8957b.png)

### Environment

```shell
System:
    OS: macOS 11.5.1
    CPU: (8) x64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.17.6/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 97.0.4692.71
    Edge: 97.0.1072.62
    Safari: 14.1.2
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue! This is most likely an issue directly in webpack we can't fix ourselves. Please follow https://github.com/webpack/webpack/issues/14907 and if the outcome of it would be that our webpack config need changing, please report back. Thanks!
