### ISSUE TITLE
[gatsby-source-wordpress] Extend Normalisers

### ISSUE THREAD

**Issue by moshie** [gatsbyjs/gatsby#3450]
## Description

It would be great if we could implement our own normalizers for manipulating WordPress entities.

For example when we want to search and replace the hostname in URLs.

I was playing around with a simple PR where normalizers are passed via the options object then executed like so:

```js
  for (let i = 0; i < normalizers.length; i++) {
    if (typeof normalizers[i] === 'function') {
      entities = normalizers[i](entities)
      continue
    }
  }
```

This is a very crude example ideally you would prepare the code to accept promises as well as functions.

The remark package has some similar [extension functionality](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/src/extend-node-type.js#L60)

### Environment

Gatsby version: Latest
Node.js version: 8.2.1
Operating System: OSX El Capitan

### File contents (if changed):

`gatsby-config.js`: not changed
`package.json`: not changed
`gatsby-node.js`: not changed
`gatsby-browser.js`: not changed
`gatsby-ssr.js`: not changed

**Comment by calcsam** [comment]
This sounds like a great idea! Feel free to implement this!

**Comment by KyleAMathews** [comment]
Yeah, plugins can have plugins (which could have plugins!!!!!!! — but don't do that :-)). So this sounds great.

Though for this particular example of replacing hostnames — that sounds like something the source plugin should handle directly?

**Comment by moshie** [comment]
I had difficulty testing this package any tips?

Also hope the PR is ok Let me know if you require any amendments.

**Comment by KyleAMathews** [comment]
@moshie checkout https://www.gatsbyjs.org/docs/how-to-contribute/#contributing

**Comment by Fetten** [comment]
Thought of passing custom normalizers as well today via `gatsby-config.js` and played around with an implementation before I saw this issue :)

Any progress on this? Do you need help with anything, @moshie?

**Comment by moshie** [comment]
Apologies, I have been short on time this week I have been working on bits here and there. 

I will have something PR'd soon I `promise()` 👍

**Comment by moshie** [comment]
So I was thinking about how this might work and came up with this idea of setting the normalisers to an object. 

Some people may want to run a normaliser before the "built in" ones so I specified a priority argument to define when it gets called, I was thinking the default priority could just be anything after.

This way also allows you to define multiple normalisers in one plugin.

```js
// Plugin
// 
exports.normalizer = function (normalizer) {

    function modifyEntitys(entities, args) {
        // Normalizer
        return entities;
    }

    // returns normalizer
    return normalizer.set(modifyEntitys, 20); // callback, priority
}
```

If anyone has an

**Comment by Fetten** [comment]
Giving priorities is a great idea! How about giving the built-in normalizers a priority as well, so you could modify entities between two of them?
Just a quick thought, could make things more complicated and might be a bit overengineered as well.

**Comment by moshie** [comment]
Glad you think so! I think that's a good idea about giving the built in normalisers the same priority argument, Ill write it up and report back soon :)

**Comment by moshie** [comment]
I am sort of stuck / out of my depth with this one. 
Can't think of a clean way of integrating custom normalisers with the already coded ones.
I would appreciate a hand in making this happen.

**Comment by KyleAMathews** [comment]
Could you get by with a new `normalize` option that got called with each entity after all the built-in ones are finished? That wouldn't complicate the code much and would let you fix urls and other normal tweaks.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
