### ISSUE TITLE
New SSR Render Mode Documentation Unclear

### ISSUE THREAD

**Issue by xaviemirmon** [gatsbyjs/gatsby#34519]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

I am working with Gatsby v4's new SSR render mode and running into a funny one.  I've got some code that is browser-based reliant on `window`.  It's working just fine in `gatsby develop`.  However when I run `gatsby build && gatsby serve` I get a whole bunch of window undefined errors unless I short circuit it to check if `window` is available.  This is along the lines of what's documented in https://www.gatsbyjs.com/docs/debugging-html-builds/#how-to-check-if-window-is-defined however that article is speaking to build time SSR but should also probably refer runtime SSR.  Does anyone know what's different between the two processes that would lead to this behaviour?  I've looked at the Gatsby Docs https://www.gatsbyjs.com/docs/conceptual/rendering-options/, https://www.gatsbyjs.com/docs/reference/rendering-options/server-side-rendering/ and https://www.gatsbyjs.com/docs/how-to/rendering-options/using-server-side-rendering/ and don't see any examples or mention of this.  

My understanding from the current runtime SSR documentation is that `getServerData()` is the only logic that should be SSR'd but that doesn't seem to be the case.  

As Gatsby Cloud's Preview service uses a build rather than a background `gatsby develop` my deployments were failing without any feedback (just a white screen).  

### Steps to Resolve this Issue

1. A diagram on https://www.gatsbyjs.com/docs/how-to/rendering-options/using-server-side-rendering/ similar to the ones provided on https://www.gatsbyjs.com/docs/conceptual/rendering-options/ outlining how an SSR request is working behind the scenes
2. Better parity in how `gatsby develop` and `gatsby serve` behave for SSR requests
3.  https://www.gatsbyjs.com/docs/debugging-html-builds/#how-to-check-if-window-is-defined to include runtime SSR too

**Comment by LekoArts** [comment]
Hi!

If you add a `getServerData` to a page, the rest of the page will still be going through some HTML generation so both in your page and/or `getServerData` an unchecked access to `window` will fail.

Steps to fix this issue:

- Add a note about Server-Side Rendering to first paragraph of https://www.gatsbyjs.com/docs/debugging-html-builds/

The better parity between develop and build is currently still a work in progress 👍

**Comment by xaviemirmon** [comment]
@LekoArts I've created a PR for this https://github.com/gatsbyjs/gatsby/pull/34631
