### ISSUE TITLE
Clarification/deprecation of where to set React JSX import source

### ISSUE THREAD

**Issue by aaronadamsCA** [gatsbyjs/gatsby#34518]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

Since Gatsby v3.0, `babel-preset-gatsby` in `.babelrc.json` has accepted options `reactRuntime` and `reactImportSource`:

https://www.gatsbyjs.com/docs/reference/release-notes/v3.0/#babel-preset-gatsby

However, neither option was ever documented on the package itself:

https://github.com/gatsbyjs/gatsby/blob/master/packages/babel-preset-gatsby/README.md

Since Gatsby v4.1, `gatsby-config.js` has also accepted options `jsxRuntime` and `jsxImportSource`:

https://www.gatsbyjs.com/docs/reference/release-notes/v4.1/#jsx-runtime-options-in-gatsby-configjs

**As far as I can tell, it's presently necessary to set these values in both places to successfully opt into the automatic runtime with a custom import source.** If I remove either one, `gatsby build` fails:

1. If I don't pass `reactRuntime` and `reactImportSource` to `babel-preset-gatsby` in `.babelrc.json`, JSX is invalid in `gatsby-browser.js`.
2. If I don't set `jsxRuntime` and `jsxImportSource` in `gatsby-config.js`, JSX is invalid in components.

Until the implementation can be further improved, I think it's important to clarify this in the docs.

(Obviously an ideal implementation would allow us to put runtime, import source, and browserslist targets together in one place; but given this is set just once, documentation is probably adequate for now.)

### Steps to Resolve this Issue

Update the docs.
Optionally simplify the API.

**Comment by LekoArts** [comment]
So if I understand it correctly, two things would need to happen:

- Update https://github.com/gatsbyjs/gatsby/blob/master/packages/babel-preset-gatsby/README.md to include both settings
- Update https://www.gatsbyjs.com/docs/reference/config-files/gatsby-config/#jsxruntime to link to https://github.com/gatsbyjs/gatsby/blob/master/packages/babel-preset-gatsby/README.md (when it is used)

**Comment by olgashi** [comment]
@LekoArts if no one is working on this, can I please be assigned to it? Thank you!

**Comment by pieh** [comment]
@olgashi I just assign you ;) Thanks for taking this on!

**Comment by AshuuDixit** [comment]
So if I understand it correctly, two things would need to happen:

Update https://github.com/gatsbyjs/gatsby/blob/master/packages/babel-preset-gatsby/README.md to include both settings
Update https://www.gatsbyjs.com/docs/reference/config-files/gatsby-config/#jsxruntime to link to https://github.com/gatsbyjs/gatsby/blob/master/packages/babel-preset-gatsby/README.md (when it is used)

**Comment by aaronadamsCA** [comment]
That looks right to me based on what I see in my repository.

I don't know if it's helpful to note this, but adding it to `tsconfig.json` adds no value of which I'm aware.

(I also hope a lot of this gets cleaned up in the next major version of Gatsby!)

**Comment by oneknucklehead** [comment]
Hey @aaronadamsCA if no one is working on this, can I work on it and make a pr?

**Comment by LekoArts** [comment]
@oneknucklehead Sure, go ahead!
