### ISSUE TITLE
tsconfig.json ignored

### ISSUE THREAD

**Issue by dominicfallows** [gatsbyjs/gatsby#3452]
I've been attempting to setup my project using tsconfig.json and target/lib was not being picked up.
```
{
  "compilerOptions": {
    "outDir": "./dist",
    "target": "es5",
    "lib": ["es2017", "dom"],
    "module": "es2015",
    "moduleResolution": "node",
    "jsx": "react",
...
}
```

 By adding `gatsby-config.js` config instead, it works:
```
{
      resolve: 'gatsby-plugin-typescript',
      options: {
        transpileOnly: true, // default
        compilerOptions: {
        target: 'es5',
        experimentalDecorators: true,
        jsx: 'react'
      }, // default
},
```

Can we actually use `tsconfig.json` - what could I be doing wrong?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
