### ISSUE TITLE
gatsby-plugin-gatsby-cloud doesn't redirect with statusCode: 200

### ISSUE THREAD

**Issue by ShaunDychko** [gatsbyjs/gatsby#34535]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

The [gatsby-plugin-gatsby-cloud](https://www.gatsbyjs.com/plugins/gatsby-plugin-gatsby-cloud/) documentation suggests that it's possible to create a redirect that returns a status code 200. Example from the docs:
```js
createRedirect({
  fromPath: "/url_that_is/not_pretty",
  toPath: "/pretty/url",
  statusCode: 200,
})
```
However, the status code returned is 302, and the URL in the browser location bar changes to the `toPath`.
The motivation for this issue is to visit an external API while using the Gatsby Cloud hosted site domain in order to obtain a session cookie from the external API and to avoid CORS issues. This is possible on Netlify as described [here](https://docs.netlify.com/routing/redirects/rewrites-proxies/#proxy-to-another-service).

### Reproduction Link

https://github.com/ShaunDychko/hello-world-public

### Steps to Reproduce

1. Clone https://github.com/ShaunDychko/hello-world-public
2. Build and deploy on Gatsby Cloud
3. Visit `[your-site-name].gatsbyjs.io/url_that_is/not_pretty`

### Expected Result

The contents of `[your-site-name].gatsbyjs.io/pretty/url` displayed while the URL in the browser remains as `[your-site-name].gatsbyjs.io/url_that_is/not_pretty`.

### Actual Result

A 302 redirect occurs and the browser location bar changes to `[your-site-name].gatsby.io/pretty/url`.

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 95.0.2
    Safari: 15.2
  npmPackages:
    gatsby: ^4.5.3 => 4.5.3 
    gatsby-plugin-gatsby-cloud: ^4.5.2 => 4.5.2 
  npmGlobalPackages:
    gatsby-cli: 4.2.0
    gatsby-transformer-katex: 1.0.1
```

**Comment by LekoArts** [comment]
Hi! For Gatsby Cloud related issues please open a ticket here: https://www.gatsbyjs.com/support/
Thanks!
