### ISSUE TITLE
Not able to set "send_page_view" parameter for gtag using gatsby-plugin-google-gtag

### ISSUE THREAD

**Issue by xy-lin** [gatsbyjs/gatsby#34534]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi there,
I am using gatsby-plugin-google-gtag to add Google Analytics. It basically works. But I have problem of setting one of options for the gtag configuration. My plugin config looks like this in gatsby-config.js

```
 {
      resolve: `gatsby-plugin-google-gtag`,
      options: {
        trackingIds: [
          "UA-xxxxxx",
          "AW-xxxxxx",
        ],

        gtagConfig: {
          anonymize_ip: true,
          send_page_view: true, // Explicitly set to true
        },

        pluginConfig: {
          head: true,
          respectDNT: true,
        },
      },
},
```
I set the "send_page_view" to true explicitly. But when loading the page and check the head section, the script looks like this:

```
if(!(navigator.doNotTrack == "1" || window.doNotTrack == "1")) {
        window.dataLayer = window.dataLayer || [];
        function gtag(){window.dataLayer && window.dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-xxxxxx', {"anonymize_ip":true,"send_page_view":false});
		
	gtag('config', 'AW-xxxxxx', {"anonymize_ip":true,"send_page_view":false});
}
```
As you can see, the "send_page_view" option is still false for gtag function. What have I done wrong?

According to Google, if the default for this "send_page_view" parameter is true. But if I don't set it explicitly, the value is still false in page head.
https://developers.google.com/analytics/devguides/collection/gtagjs/pages

This is demo site hosted in Gatsby Cloud:
https://gtagpluginsendpageviewbugmain.gatsbyjs.io

How to force "send_page_view" to be true? Is this parameter not relevant to this plugin, and will always be true/false? 

Many thanks.

### Reproduction Link

https://github.com/xy-lin/gtag-plugin-send-page-view-bug

### Steps to Reproduce

0. npm init gatsby
1. npm install gatsby-plugin-google-gtag
2. In gatsby-config.js, add config for above plugin, and set send_page_view to true
3. npm run build
4. check gtag script in the head section loaded using chrome dev tool

### Expected Result

gtag('config', 'UA-xxxxxx', {"anonymize_ip":true,"send_page_view":**true**,"cookie_expires":123});

### Actual Result

gtag('config', 'UA-xxxxxx', {"anonymize_ip":true,"send_page_view":**false**,"cookie_expires":123});

### Environment

```shell
Gatsby Cloud Build
```

**Comment by justinh00k** [comment]
I have the same issue. Same setup but only one tracking ID. https://googlefeud.com
