### ISSUE TITLE
Building Gatsby static site in GitHub Actions CI fails with generic error

### ISSUE THREAD

**Issue by GabrielMajeri** [gatsbyjs/gatsby#34555]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I've been trying to get my Gatsby-based static [site](https://github.com/GabrielMajeri/gabrielmajeri.github.io) to build automatically using GitHub Actions, so that then I can automatically deploy it with GitHub Pages. The issue is that the static build works perfectly on my local machine, but it fails mysteriously, without a very useful error message, in CI.

```
> gatsby build

success open and validate gatsby-configs, load plugins - 0.152s
success onPreInit - 0.000s
success initialize cache - 0.095s
success copy gatsby files - 0.071s
success Compiling Gatsby Functions - 0.244s
success onPreBootstrap - 0.252s
success createSchemaCustomization - 0.000s
success Checking for changed pages - 0.000s
success source and transform nodes - 0.189s
info Writing GraphQL type definitions to /home/runner/work/gabrielmajeri.github.io/gabrielmajeri.github.io/.cache/schema.gql
success building schema - 0.372s
success createPages - 0.001s
success createPagesStatefully - 0.065s
info Total nodes: 22, SitePage nodes: 1 (use --verbose for breakdown)
success Checking for changed pages - 0.000s
success onPreExtractQueries - 0.000s
success extract queries from components - 1.080s
success write out redirect data - 0.010s
success onPostBootstrap - 0.000s
info bootstrap finished - 4.606s
success write out requires - 0.004s
error UNHANDLED REJECTION Worker exited before finishing task


  Error:Worker exited before finishing task
  
  - index.js:112 ChildProcess.<anonymous>
    [gabrielmajeri.github.io]/[gatsby-worker]/dist/index.js:112:45
  
  - node:events:390 ChildProcess.emit
    node:events:390:28
  
  - child_process:290 Process.ChildProcess._handle.onexit
    node:internal/child_process:290:12
  

not finished Building production JavaScript and CSS bundles - 0.712s
```

Is there any way to get something more descriptive than `Error: Worker exited before finishing task`?

I've commented out all of the CSS, and left a minimal/empty component for the index page. I've been unable to determine why it would fail otherwise.

### Reproduction Link

https://github.com/GabrielMajeri/gabrielmajeri.github.io

### Steps to Reproduce

This issue seems to only happen in GitHub Actions CI, which is very weird. I've tried reproducing everything exactly locally but haven't been able to figure it out.

```
      - name: Build static files
        run: npm run build
        env:
          GATSBY_CPU_COUNT: 1
```

I've added the `GATSBY_CPU_COUNT` thinking it would help. The code still fails either way.

### Expected Result

Gatsby successfully builds the static version of the site in GitHub Actions CI.

### Actual Result

`npm run build` exits with a generic `error UNHANDLED REJECTION Worker exited before finishing task`, without providing additional information.

### Environment

```shell
System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Languages:
    Python: 3.8.10 - /usr/bin/python
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 95.0.1
  npmPackages:
    gatsby: ^4.5.4 => 4.5.4 
    gatsby-plugin-react-helmet: ^5.5.0 => 5.5.0
```

**Comment by LekoArts** [comment]
Hi!

The GitHub Action might not have enough memory available to build. For the CircleCI issue: Try setting `GATSBY_CPU_COUNT`, in our experience CircleCI sometimes tells Gatsby that e.g. 32 cores are available (which is not correct).

Anyways, please follow https://github.com/gatsbyjs/gatsby/discussions/34215 for improvements on memory management. We're actively working on this at the moment. Thanks!

**Comment by jrusso1020** [comment]
thanks @LekoArts setting `GATSBY_CPU_COUNT=2` seems to have done the trick
