### ISSUE TITLE
Images from Gutenberg Image blocks not displaying on Safari in production mode

### ISSUE THREAD

**Issue by houseofx-nyc** [gatsbyjs/gatsby#34552]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I am sourcing pages from my WordPress backend using `gatsby-source-wordpress`.  I'm including page content by including
```
 <section
  dangerouslySetInnerHTML={{ __html: getContent(props.data, props.pageTitle) }}
></section>
```
in my React components.  `getGontent` is defined by

```
function getContent(data: QueryData, title: string): string {
  const page = data.allWpPage.nodes.find((page) => {
    return page.title === title;
  });
  if (!page) {
    // bad markup
    throw new Error(`no page found with title ${title}`);
  }
  return page.content;
}
```

Everything works fine until I try to view the page in production mode on Safari.  When `useGatsbyImage` is enabled in teh options, no images show up on my page:

Chrome:
<img width="1263" alt="Screen Shot 2022-01-20 at 10 23 02 AM" src="https://user-images.githubusercontent.com/93601376/150368277-1999fbdf-eaf1-483f-ac31-948cbacbff0f.png">

Safari:
<img width="1162" alt="Screen Shot 2022-01-20 at 10 19 34 AM" src="https://user-images.githubusercontent.com/93601376/150368321-fe716eb6-8e77-47c2-8d21-2b57c7429889.png">

These are from https://build-90733a9b-f6b7-4f29-adca-6ad49e73913a.gtsb.io if you have access to it. 

I can not use GatsbyImage, but that creates an issue where the image urls don't get rewritten, so my media is being distributed from the WordPress backend as opposed to the GatsbyCloud CDN.

### Reproduction Link

https://drive.google.com/drive/folders/1M1RxqFVpDRquK5LZ9KAFyAV9FWxr3Cd9?usp=sharing.  test.zip is an exported WP site from Local. wp-gatsby-test is a simple gatsby site to reproduce the issue which reads from the WP site.

### Steps to Reproduce

1. Run the WordPress site locally at test.local
2. run npm install && npx gatsby build && npx gatsby serve from the root of the Gatsby project
3. navigate to localhost:9000 in Safari.

### Expected Result

Images appear on Safari

### Actual Result

No image appears on Safari.

### Environment

```shell
System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 97.0.4692.99
    Safari: 14.1.2
  npmPackages:
    gatsby: ^4.1.2 => 4.4.0 
    gatsby-plugin-image: ^2.1.0 => 2.4.0 
    gatsby-plugin-react-helmet: ^5.4.0 => 5.4.0 
    gatsby-plugin-sharp: ^4.1.1 => 4.4.0 
    gatsby-source-filesystem: ^4.4.0 => 4.4.0 
    gatsby-source-wordpress: ^6.4.0 => 6.4.0 
    gatsby-transformer-sharp: ^4.4.0 => 4.4.0
```

**Comment by houseofx-nyc** [comment]
[Exported WP site from Local:](https://drive.google.com/drive/folders/1M1RxqFVpDRquK5LZ9KAFyAV9FWxr3Cd9?usp=sharing) has a reproduction:

test.zip is an exported WP site from Local.  wp-gatsby-test is a simple gatsby site to reproduce the issue.

To reproduce:

1. Run the WordPress site locally at `test.local`
2. run `npm install && npx gatsby build && npx gatsby serve` from the root of the Gatsby project
3. navigate to `localhost:9000` in Safari.  

You'll see a bug empty page with some copy at the bottom.  The empty space would have an image in it if you opened the page in Chrome.

**Comment by houseofx-nyc** [comment]
Another piece of evidence from the WPGraphql Slack: 

> fwiw, when I go to the reproduction url I don't see the images in safari on initial page load, but do see them when I click a link on the site to go to the page.
For example, visiting: https://build-90733a9b-f6b7-4f29-adca-6ad49e73913a.gtsb.io/#private-events directly, no images
But clicking the "Private Events" link in the header, then I see the images

https://slack-files.com/T3PDM1KRC-F02UXL8C7SP-dc3a00e993

**Comment by steelbridge-io** [comment]
Having the same exact issue.

**Comment by steelbridge-io** [comment]
I set up a default latest Gatsby. Installed gatsby-source-wordpress, see setup here https://github.com/steelbridge-io/gatsby-safari-image-issue
Experienced no images on /hello-world in Safari, but images worked in all other browsers.
I then downgraded to 3.14.6 along with all plugins and my tests worked as they should with gutneblock image rendering in Safari. Here's the gatsby default .v 3.14.6 https://github.com/steelbridge-io/gatsby-3.14.6-no-safari-issue

I think I'm just going to downgrade the client site for now. That's a solution that will work for me.

**Comment by houseofx-nyc** [comment]
I can confirm this works as a short term fix, but we shouldn't need to downgrade all of our deps to get images on Safari.  Makes me wonder that somehow we aren't using this plugin differently than it was intended?

**Comment by andripeetso** [comment]
Experiencing the same issue. Images not loading on iOS devices at all, not even when using other browsers.

**Comment by usuallyno** [comment]
> Experiencing the same issue. Images not loading on iOS devices at all, not even when using other browsers.

Yes we notice this bug in all iOS devices.
read this -> [https://developer.apple.com/app-store/review/guidelines/#performance](https://developer.apple.com/app-store/review/guidelines/#performance)

> 2.5.6 Apps that browse the web must use the appropriate WebKit framework and WebKit Javascript

**Comment by andrewgolovanov** [comment]
@steelbridge-io 
you don't have to give up using `gatsby v4`, 
try just installing `gatsby-source-wordpress` version `5.14.2` - it works fine for me
