### ISSUE TITLE
Cannot access to tag information with  Contentful plugin

### ISSUE THREAD

**Issue by StanLepunK** [gatsbyjs/gatsby#34556]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I'm in the same scenario as https://github.com/gatsbyjs/gatsby/issues/34450, I cannot access to the tag in the `allContentfulAsset`
my configuration is correct, I think 
`package.json`
```
"dependencies": {
    "@emotion/react": "^11.7.1",
    "@material-ui/core": "^4.12.3",
    "@material-ui/icons": "^4.11.2",
    "axios": "^0.25.0",
    "gatsby": "^4.5.3",
    "gatsby-plugin-image": "^2.5.2",
    "gatsby-plugin-manifest": "^4.5.2",
    "gatsby-plugin-material-ui": "^4.1.0",
    "gatsby-plugin-offline": "^5.5.2",
    "gatsby-plugin-react-helmet": "^5.5.0",
    "gatsby-plugin-sharp": "^4.5.2",
    "gatsby-plugin-web-font-loader": "^1.0.4",
    "gatsby-source-contentful": "^7.3.2",
    "gatsby-source-filesystem": "^4.5.2",
    "gatsby-source-mongodb": "^4.5.0",
    "gatsby-transformer-sharp": "^4.5.0",
    "p5": "^1.4.0",
    "prop-types": "^15.8.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-helmet": "^6.1.0"
  },
```

`gatsby-config.js`
```
// CONTENTFUL
    {
      resolve: `gatsby-source-contentful`,
      options: {
        spaceId: process.env.CONTENTFUL_SPACE_ID,
        // Learn about environment variables: https://gatsby.dev/env-vars
        accessToken: process.env.CONTENTFUL_ACCESS_TOKEN,
        enableTags: true,
      },
    },
```
But in the `graphQl`i find no trace of tag or metadata, I'm not an expert, but We don't find a solution with M. Ferran Buireu on [stackOverflow ](https://stackoverflow.com/questions/70759297/sort-allcontentasset-by-tag-in-gatsby-is-it-possible)

when I write this code in the graph
```
allContentfulAsset(
   filter: {metadata: { tags: { in: ["art work", "vies paralleles"] } }}) {
  edges { node { title }}} 
```
this message is returned `Field "Metadata" is not defined by type "ContentfulAssetFilterInput"` That's can be normal because I found no trace of `tag` or `metadata` in tree
for information, a screenshot of my graph
<img width="262" alt="Capture d’écran 2022-01-20 à 16 16 55" src="https://user-images.githubusercontent.com/3332269/150367777-7a0febf4-aefc-427f-819c-6c80e84971b1.png">

### Reproduction Link

https://github.com/StanLepunK/bug-repro

### Steps to Reproduce

Nothing happen in the GraphQl

### Expected Result

That's work and I can catch the tag info everywhere !

### Actual Result

I cannot catch tag or metadata except in `contentfulTag`

### Environment

```shell
OS Monterey
Macbook pro 2018 intel
Navigator : Mozilla

"dependencies": {
    "gatsby": "^4.5.4",
    "gatsby-source-contentful": "^7.3.2",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  }
```
```


### Config Flags

_No response_

**Comment by StanLepunK** [comment]
Maybe link too this problem https://github.com/gatsbyjs/gatsby/issues/34545

**Comment by axe312ger** [comment]
@StanLepunK as mentioned in the other issue, tag support for assets was just added to the plugins.

Please use gatsby-source-contentful@7.5.0-next.0 or wait for the next release
