### ISSUE TITLE
SecurityError The operation is insecure in production-app.js

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#34598]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

We are seeing the following (unhandled) error in Sentry logs on our production site:

> SecurityError
The operation is insecure.

It originates in Gatsby's `production-app.js`  on line [209](https://github.com/gatsbyjs/gatsby/blob/77e4bb01a1994448d685afa82620f5125dd029d3/packages/gatsby/cache-dir/production-app.js#L209) at the conditional `if(sessionStorage)`. 

```
if (sessionStorage) {
      sessionStorage.removeItem(reloadStorageKey)
}
```

Looks like it is happening when a user has disabled cookies, however I believe this error should either be handled, or a more useful message raised. 

### Reproduction Link

None

### Steps to Reproduce

1. Disable cookies
2. Open a Gatsby site

### Expected Result

No exceptiion, or useful exception message. 

### Actual Result

Unhelpful exception. 

### Environment

```shell
System:
    OS: macOS 11.6.2
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.2/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 97.0.4692.99
    Edge: 97.0.1072.69
    Firefox: 96.0.2
    Safari: 15.2
  npmPackages:
    gatsby: ^4.5.0 => 4.5.0
    gatsby-cli: ^4.5.0 => 4.5.0
    gatsby-link: ^4.2.0 => 4.5.0
    gatsby-plugin-anchor-links: ^1.2.1 => 1.2.1
    gatsby-plugin-catch-links: ^4.5.0 => 4.5.0
    gatsby-plugin-google-tagmanager: ^4.5.0 => 4.5.0
    gatsby-plugin-image: ^2.5.0 => 2.5.0
    gatsby-plugin-manifest: ^4.5.0 => 4.5.0
    gatsby-plugin-netlify-cms: ^6.5.0 => 6.5.0
    gatsby-plugin-node-fields: 3.1.0 => 3.1.0
    gatsby-plugin-page-creator: ^4.5.0 => 4.5.0
    gatsby-plugin-react-helmet-async: ^1.2.1 => 1.2.1
    gatsby-plugin-scroll-reveal: ^0.0.7 => 0.0.7
    gatsby-plugin-sharp: ^4.5.0 => 4.5.0
    gatsby-plugin-sitemap: ^5.5.0 => 5.5.0
    gatsby-plugin-styled-components: ^5.5.0 => 5.5.0
    gatsby-plugin-svgr: 3.0.0-beta.0 => 3.0.0-beta.0
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.26 => 1.1.26
    gatsby-react-router-scroll: 5.5.0 => 5.5.0
    gatsby-remark-autolink-headers: ^5.5.0 => 5.5.0
    gatsby-remark-component-parent2div: ^1.2.3 => 1.2.3
    gatsby-remark-copy-linked-files: ^5.5.0 => 5.5.0
    gatsby-remark-footnotes: ^0.0.8 => 0.0.8
    gatsby-remark-images: ^6.5.0 => 6.5.0
    gatsby-remark-numbered-footnotes: ^1.0.1 => 1.0.1
    gatsby-remark-relative-images: ^2.0.2 => 2.0.2
    gatsby-remark-responsive-iframe: ^5.5.0 => 5.5.0
    gatsby-remark-smartypants: ^5.5.0 => 5.5.0
    gatsby-remark-unwrap-images: ^1.0.2 => 1.0.2
    gatsby-source-filesystem: 4.5.0 => 4.5.0
    gatsby-transformer-json: ^4.5.0 => 4.5.0
    gatsby-transformer-remark: ^5.5.0 => 5.5.0
    gatsby-transformer-sharp: ^4.5.0 => 4.5.0
```

### Config Flags

    FAST_DEV: true,
    PRESERVE_FILE_DOWNLOAD_CACHE: true,
    PARALLEL_SOURCING: true,

**Comment by LekoArts** [comment]
This was fixed by https://github.com/gatsbyjs/gatsby/pull/34525, please update to at least 4.5.4
