### ISSUE TITLE
`WebpackError` when running gatsby develop or build

### ISSUE THREAD

**Issue by apnerve** [gatsbyjs/gatsby#3466]
## `WebpackError` when running gatsby develop or build

Describe the issue or the enhancement that you want to see.

### Environment

Gatsby version: 1.1.28
Node.js version: 8.9.4
npm version: 5.6.0
Operating System: macOS High Sierra

### Actual result

```
error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND


  Error: WebpackError

  - option-manager.js:293
    [tutorial-part-one]/[babel-core]/lib/transformation/file/options/option-manager.js:293:19

  - Array.map

  - option-manager.js:275 OptionManager.resolvePresets
    [tutorial-part-one]/[babel-core]/lib/transformation/file/options/option-manager.js:275:20

  - option-manager.js:264 OptionManager.mergePresets
    [tutorial-part-one]/[babel-core]/lib/transformation/file/options/option-manager.js:264:10

  - option-manager.js:249 OptionManager.mergeOptions
    [tutorial-part-one]/[babel-core]/lib/transformation/file/options/option-manager.js:249:14

  - option-manager.js:368 OptionManager.init
    [tutorial-part-one]/[babel-core]/lib/transformation/file/options/option-manager.js:368:12

  - index.js:212 File.initOptions
    [tutorial-part-one]/[babel-core]/lib/transformation/file/index.js:212:65

  - index.js:135 new File
    [tutorial-part-one]/[babel-core]/lib/transformation/file/index.js:135:24

  - pipeline.js:46 Pipeline.transform
    [tutorial-part-one]/[babel-core]/lib/transformation/pipeline.js:46:16

  - index.js:46 transpile
    [tutorial-part-one]/[babel-loader]/lib/index.js:46:20

  - fs-cache.js:79
    [tutorial-part-one]/[babel-loader]/lib/fs-cache.js:79:18

  - fs-cache.js:15 ReadFileContext.callback
    [tutorial-part-one]/[babel-loader]/lib/fs-cache.js:15:14

  - From previous event:

  - build-html.js:48 _callee$
    [tutorial-part-one]/[gatsby]/dist/commands/build-html.js:48:46

  - next_tick.js:131 _combinedTickCallback
    internal/process/next_tick.js:131:7

  - next_tick.js:180 process._tickCallback
    internal/process/next_tick.js:180:9
```

### Expected behavior

`gatsby develop` should have started the development server but instead this error shows up

### Steps to reproduce

Not sure if it is reproducible

**Comment by KyleAMathews** [comment]
Is there any way you could share the code for the site? The error isn't helpful unfortunately :-(

**Comment by apnerve** [comment]
@KyleAMathews I'm sorry. I just followed the instructions as mentioned in this tutorial - [Introduction to basics](https://www.gatsbyjs.org/tutorial/part-one/)

```
npm install --global gatsby-cli
gatsby new tutorial-part-one https://github.com/gatsbyjs/gatsby-starter-hello-world
cd tutorial-part-one
gatsby develop
```

No files were modified. I just blindly followed the instructions and got this error. I switched to node 8.0.0/npm 5.0.0 but still got the same error.

**Comment by KyleAMathews** [comment]
Super weird :-(

Just tried the exact above instructions and it worked.

Only other thing I can suggest is to try installing Yarn — Yarn tends to be more reliable but still weird as lots of other people are using NPM successfully.

**Comment by apnerve** [comment]
Everything works fine after removing certain global packages and re-installing gatsby. 🤘

Closing this issue as it was specific to my system.

**Comment by KyleAMathews** [comment]
@apnerve btw, could you describe how you fixed this over at https://github.com/gatsbyjs/gatsby/issues/2427 as it looks like they're running into the same problem

**Comment by KyleAMathews** [comment]
Ah! Yeah, that can cause trouble — good idea on adding this to the debugging page — could you add a PR for that?
