### ISSUE TITLE
gatsby develop  unable to connect  in node 17 

### ISSUE THREAD

**Issue by Livins1** [gatsbyjs/gatsby#34668]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

i am just starting a new gatsby project and this the first time i use gatsby.
when i just following the get start steps,  and get into my project folder, then run "gatsby develop"  evething works just fine. and i got the right stdout like http://localhost:8000.

But, i cant open this site in my browser both firefox or chrome. the brower just show a blank page. there is no proxy working around and i tried different port, different command like "gatsby develop -H 0.0.0.0 -p 8001". they are not working. it looks like the develop server just not there. nothing about the address and ports. all these step i running in my laptop which the enviroment over there  in this issue

this is  weird, then I tried in my desktop that running windows11 and node version is v16.13.1. everthing works fine. i can open the site in my browser and the default index just showed up.

last, install the nvm and change my node version to 16.13.4 in my laptop. then "gatsby develop",  the problem solved.  i can see my page in my firefox now.

actully, this issue is solved. i just write is down here. In case someone encounters the same problem

### Reproduction Link

https://github.com/gatsbyjs/gatsby

### Steps to Reproduce

1.
2.
3.
...

### Expected Result

browser  show the start page. http://localhost:8000

### Actual Result

browser cannot show the start page. just blank page. and the request  stuck

### Environment

```shell
System:
    OS: Linux 5.16 Arch Linux
    CPU: (16) x64 AMD Ryzen 7 PRO 4750U with Radeon Graphics
    Shell: 3.3.1 - /usr/bin/fish
  Binaries:
    Node: 17.4.0 - ~/.local/share/nvm/v17.4.0/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.3.1 - ~/.local/share/nvm/v17.4.0/bin/npm
  Languages:
    Python: 3.10.2 - /usr/bin/python
  Browsers:
    Firefox: 96.0.3
  npmPackages:
    gatsby: ^4.6.0 => 4.6.0
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by pywkt** [comment]
also seeing this issue

```
OS: Manjaro Linux x86_64
Kernel: 5.14.21-2-MANJARO
CPU: Intel i7-8565U (8) @ 4.600GHz
Browser: 
  Chromium Version 98.0.4758.80 (Official Build) Manjaro Linux (64-bit)
  Mozilla Firefox Developer Edition for Manjaro Linux Version 97.0b3 (64-bit)
Gatsby:
  Gatsby CLI version: 4.6.1
  Gatsby version: 4.6.2
```

- install node 17.0.0 or higher
- create a new gatsby project and cd to project root
- run `gatsby develop`
- localhost:8000
- see blank screen as described by Livins1

downgrading to node 16.13.x seems to "fix" it
