### ISSUE TITLE
Docs site does not have distinct titles for all pages

### ISSUE THREAD

**Issue by markerikson** [gatsbyjs/gatsby#3469]
## Description

Several portions of the Gatsby docs site have the same basic title: "GatsbyJS".  It appears that other portions of the docs do have a distinct title, such as "Building with Components | GatsbyJS", but the "Getting Started" page and the Gatsby blog page only say "GatsbyJS".

Those happened to be the first two links I opened up off the Gatsby home page, so my immediate assumption was that _all_ of the docs pages only said "GatsbyJS".  It was only after I clicked around further that I realized most of the docs pages do have distinct titles.

It would be good if every page had a distinct title.  Keeping the home page as just "GatsbyJS" would be reasonable, but the others should be "Getting Started | GatsbyJS" and "Blog | GatsbyJS", or something similar.

### Environment

Gatsby docs site

**Comment by KyleAMathews** [comment]
👍  agreed!

Anyone (Mark? :-)) want to create a PR? We'd just need to a React Helmet call to set the title on those pages.

**Comment by KyleAMathews** [comment]
@benforshey fixed this in https://github.com/gatsbyjs/gatsby/pull/3550 🎉
