### ISSUE TITLE
[gatsby-plugin-image] "Cannot read  properties of undefined (reading 'originalPositionFor')"

### ISSUE THREAD

**Issue by t2ca** [gatsbyjs/gatsby#34696]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

After updating babel today, I am now getting a failed development build when running `gatsby develop`

I experienced this on 2 different projects.

However, `gatsby build` appears to work without errors.

The following 2 packages got updated to v7.17.0, it's possible this may not be related.

```
@babel/core          7.16.12 7.17.0 7.17.0 devDependencies https://babel.dev/docs/en/next/babel-core
@babel/eslint-parser 7.16.5  7.17.0 7.17.0 devDependencies https://babel.dev/
```

### Reproduction Link

https://github.com/gatsbyjs/gatsby/

### Steps to Reproduce

1. Yarn upgrade
2. gatsby develop
3.
...

### Expected Result

No error

### Actual Result

```
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

/node_modules/gatsby-plugin-image/dist/gatsby-image.browser.module.js: Cannot read
 properties of undefined (reading 'originalPositionFor')

File:node_modules/gatsby-plugin-image/dist/gatsby-image.browser.module.js
```

### Environment

```shell
System:
    OS: macOS 12.1
    Shell: 5.8 - /usr/local/bin/zsh
  Binaries:
    Node: 17.4.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.4.0 - /usr/local/bin/npm
```

**Comment by stevepepple** [comment]
I also just started seeing the same when running the `build` command. 

```
failed Building production JavaScript and CSS bundles - 337.074s
6:00:10 PM: error Generating JavaScript bundles failed
6:00:10 PM: /opt/build/repo/site/node_modules/gatsby-plugin-image/dist/gatsby-image.browser.module.js: Cannot read property 'originalPositionFor' of undefined
```

**Comment by patotoma** [comment]
Same for me started seeing this error after updating deps.

**Comment by cameronbraid** [comment]
Same here - I am upgrading a gatsby v3 project to v4.  Anyone know of a workaround ?

**Comment by patotoma** [comment]
This should be now resolved as per https://github.com/babel/babel/issues/14229#issuecomment-1028610186

**Comment by cameronbraid** [comment]
Nope, the resolution talked about there is in `@jridgewell/trace-mapping` not `@babel`

**Comment by t2ca** [comment]
> This should be now resolved as per [babel/babel#14229 (comment)](https://github.com/babel/babel/issues/14229#issuecomment-1028610186)

Thank you very much! 

I can confirm that it's working again.

**Comment by cameronbraid** [comment]
Its not working for me, what package did you upgrade to make it work ?

**Comment by cameronbraid** [comment]
found that the following workaround works for me

```
  "resolutions": {
    "@babel/core": "7.16.12"
  }
```

**Comment by LekoArts** [comment]
Thanks for finding the culprit! Closing as upstream package got fixed.
