### ISSUE TITLE
[gatsby-plugin-mdx] ERR_REQUIRE_ESM: require() of ES Module @mdx-js\mdx\index.js from gatsby-plugin-mdx\utils\mdx.js not supported.

### ISSUE THREAD

**Issue by decanTyme** [gatsbyjs/gatsby#34706]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

After a fresh `npx gatsby new` and choosing the _Add Markdown and MDX support_ option, the following error is thrown when develop/build is started:

~~~
Error in "<omitted>\node_modules\gatsby-plugin-mdx\gatsby-node.js": require() of ES Module <omitted>\node_modules\@mdx-js\mdx\index.js from <omitted>\node_modules\gatsby-plugin-mdx\utils\mdx.js not supported.
Instead change the require of index.js in <omitted>\node_modules\gatsby-plugin-mdx\utils\mdx.js to a dynamic import() which is available in all CommonJS modules.


  Error: [ERR_REQUIRE_ESM]: require() of ES Module <omitted>\node_modules\@mdx-js\mdx\index.js from <omitted>\node_modules\gatsby-plugin-mdx\utils\mdx.js not supported.
  Instead change the require of index.js in <omitted>\node_modules\gatsby-plugin-mdx\utils\mdx.js to a dynamic import() which is available in all CommonJS modules.

  - v8-compile-cache.js:159 require
    [my-gatsby-site]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - mdx.js:1 Object.<anonymous>
    [my-gatsby-site]/[gatsby-plugin-mdx]/utils/mdx.js:1:75

  - v8-compile-cache.js:192 Module._compile
    [my-gatsby-site]/[v8-compile-cache]/v8-compile-cache.js:192:30

  - v8-compile-cache.js:159 require
    [my-gatsby-site]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - create-mdx-node.js:3 Object.<anonymous>
    [my-gatsby-site]/[gatsby-plugin-mdx]/utils/create-mdx-node.js:3:13

  - v8-compile-cache.js:192 Module._compile
    [my-gatsby-site]/[v8-compile-cache]/v8-compile-cache.js:192:30

  - v8-compile-cache.js:159 require
    [my-gatsby-site]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - on-create-node.js:10 Object.<anonymous>
    [my-gatsby-site]/[gatsby-plugin-mdx]/gatsby/on-create-node.js:10:5

  - v8-compile-cache.js:192 Module._compile
    [my-gatsby-site]/[v8-compile-cache]/v8-compile-cache.js:192:30

  - v8-compile-cache.js:159 require
    [my-gatsby-site]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - gatsby-node.js:10 Object.<anonymous>
    [my-gatsby-site]/[gatsby-plugin-mdx]/gatsby-node.js:10:5

  - v8-compile-cache.js:192 Module._compile
    [my-gatsby-site]/[v8-compile-cache]/v8-compile-cache.js:192:30

  - v8-compile-cache.js:159 require
    [my-gatsby-site]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - resolve-module-exports.js:190 resolveModuleExports
    [my-gatsby-site]/[gatsby]/dist/bootstrap/resolve-module-exports.js:190:26

  - validate.js:318 
    [my-gatsby-site]/[gatsby]/dist/bootstrap/load-plugins/validate.js:318:78

  - Array.forEach

  - validate.js:311 collatePluginAPIs
    [my-gatsby-site]/[gatsby]/dist/bootstrap/load-plugins/validate.js:311:20

  - index.js:116 loadPlugins
    [my-gatsby-site]/[gatsby]/dist/bootstrap/load-plugins/index.js:116:45

  - load-config-and-plugins.js:101 async loadConfigAndPlugins
    [my-gatsby-site]/[gatsby]/dist/bootstrap/load-config-and-plugins.js:101:28

  - initialize.js:170 async initialize
    [my-gatsby-site]/[gatsby]/dist/services/initialize.js:170:7


not finished open and validate gatsby-configs, load plugins - 0.167s
~~~

This is my first time using MDX so I don't know much about it or the plugin. Sure enough if `gatsby-plugin-mdx` is removed from `gatsby-config.js`, the error is gone and the build succeeds. Searching through the issues revealed https://github.com/gatsbyjs/gatsby/issues/33682 might be a related problem. The OP closed it without much info though.

### Reproduction Link

Can be reproduced on a fresh `npx gatsby new`, so no repro link should be required

### Steps to Reproduce

1. Run `npx gatsby new`
2. Make sure to choose _Add Markdown and MDX support_ in the wizard.
3. Wait for the deps install to finish and run the start command.

### Expected Result

No build errors

### Actual Result

The error described above.

### Environment

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor            
  Binaries:
    Node: 17.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.4.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.10.2 - /c/Python310/python
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.76)
  npmPackages:
    gatsby: ^4.6.1 => 4.6.1 
    gatsby-plugin-mdx: ^3.6.0 => 3.6.0 
    gatsby-source-filesystem: ^4.6.0 => 4.6.0 
  npmGlobalPackages:
    gatsby-cli: 4.2.0
    gatsby: 4.3.0
```

**Comment by fzyzcjy** [comment]
Same issue here. Any updates?

**Comment by tangytang** [comment]
I'm also facing this same issue

**Comment by LekoArts** [comment]
You need to use v1 of `@mdx-js/mdx` and `@mdx-js/react` (via `npm install @mdx-js/mdx@v1 @mdx-js/react@v1`) until `gatsby-plugin-mdx` is compatible with v2

**Comment by Unkn0wnCat** [comment]
@LekoArts Is there an Issue for v2 functionality yet? I haven't found any, but v2 brings a few changes which are very important to my work and will allow me to retire a few hacky workarounds, so I'd like to follow v2 compatibility status

**Comment by rajxir** [comment]
Upgraded Gatsby from 3.1 to 4.2 but didn't upgrade the following plugins -
"@mdx-js/mdx"   // Current Ver - 1.6
"@mdx-js/react”  // Current Ver - 1.6
"gatsby-plugin-mdx”  // Current Ver - 3.20

Not sure if I can upgrade gatsby-plugin-mdx to 4.0?

**Comment by LekoArts** [comment]
Please note that this is fixed and you should update your dependencies to use MDX 2:

> You need to upgrade to `gatsby@4.21` and `gatsby-plugin-mdx@4.0.0`, see https://www.gatsbyjs.com/docs/reference/release-notes/v4.21/#gatsby-plugin-mdx-v4
