### ISSUE TITLE
Docs for Glamor & Styled Components have Redundant Content

### ISSUE THREAD

**Issue by deadcoder0904** [gatsbyjs/gatsby#3472]
The start of both the sites explain the same thing. It might be intentional because some people will always only use one between Glamor or Styled Components. But, the general explanation is of CSS in JS. So I was thinking maybe in Tutorial 2, there must be CSS in JS page where the common explanation go & then in Glamor or Styled Components, their individual code remains.

**Comment by KyleAMathews** [comment]
The duplication is intentional. In the future we'll want to reorganize things so we can have another layer of nesting in the docs so we can have a `css-in-js` section that does a general overview of css-in-js and then has little mini-tutorials (like these two) for setting up different libraries.
