### ISSUE TITLE
`gatsby-transformer-remark`'s `excerpt` does not have `format` argument for Mdx

### ISSUE THREAD

**Issue by fzyzcjy** [gatsbyjs/gatsby#34729]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When using https://www.gatsbyjs.com/plugins/gatsby-transformer-remark/ with Remark, the `excerpt` does have a `format` argument where I can say `format: HTML` which is very useful for me.

However, when using with Mdx, it does not. Then I cannot output HTML for it :(

Here is the graphiql demonstrating this:

![image](https://user-images.githubusercontent.com/5236035/152624153-7c33bd20-e9c3-4a0c-a176-20c38ca8295a.png)
![image](https://user-images.githubusercontent.com/5236035/152624163-5612d78d-f26f-40d2-a54c-f7377b5bc340.png)

### Reproduction Link

just use the gatsby-transformer-remark plugin and you will see it

### Steps to Reproduce

1. use gatsby-transformer-remark plugin
2. have a look at graphiql

### Expected Result

have `format` query parameter

### Actual Result

no such thing

### Environment

```shell
System:
    OS: macOS 11.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.2.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.4 - /usr/local/bin/npm
  Languages:
    Python: 3.7.6 - /Users/tom/opt/anaconda3/bin/python
  npmPackages:
    gatsby: ^4.6.0 => 4.6.1 
    gatsby-plugin-image: ^2.6.0 => 2.6.0 
    gatsby-plugin-manifest: ^4.6.0 => 4.6.0 
    gatsby-plugin-mdx: ^3.6.0 => 3.6.0 
    gatsby-plugin-postcss: ^5.6.0 => 5.6.0 
    gatsby-plugin-react-helmet: ^5.6.0 => 5.6.0 
    gatsby-plugin-sharp: ^4.6.0 => 4.6.0 
    gatsby-plugin-typegen: ^2.2.4 => 2.2.4 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.26 => 1.1.26 
    gatsby-remark-copy-linked-files: ^5.6.0 => 5.6.0 
    gatsby-remark-images: ^6.6.0 => 6.6.0 
    gatsby-remark-prismjs: ^6.6.0 => 6.6.0 
    gatsby-remark-responsive-iframe: ^5.6.0 => 5.6.0 
    gatsby-remark-smartypants: ^5.6.0 => 5.6.0 
    gatsby-source-filesystem: ^4.6.0 => 4.6.0 
    gatsby-transformer-remark: ^5.6.0 => 5.6.0 
    gatsby-transformer-sharp: ^4.6.0 => 4.6.0
```

**Comment by LekoArts** [comment]
Please open a feature request for this here: https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests

Thanks!

**Comment by fzyzcjy** [comment]
https://github.com/gatsbyjs/gatsby/discussions/34743

Thanks for the reply
