### ISSUE TITLE
Gatsby-plugin-image produces invalid HTML

### ISSUE THREAD

**Issue by namiskuukkel** [gatsbyjs/gatsby#34720]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Running Gatsby produced HTML through W3C html validator (https://validator.w3.org/) produces errors. This is reproducable with both static and dynamic images. Gatsby generates two <img> elements, the first of which seems to be some kind of background. This image element is missing alt value and there's something wrong with src attribute.
![image](https://user-images.githubusercontent.com/5670621/152531581-fa1ad766-e92a-4a87-83f5-8bd1d6bc1cf1.png)
![validation_error](https://user-images.githubusercontent.com/5670621/152531917-fd22961d-29d7-44da-98c3-089c99930900.png)

### Reproduction Link

https://github.com/namiskuukkel/gatsby-bug-repro

### Steps to Reproduce

1. Add an image with gatsby-plugin-image to your project.
2. Run generated HTML through https://validator.w3.org/ HTML validator

### Expected Result

No validation errors.

### Actual Result

Receive two validation errors for the generated image.

### Environment

```shell
System:
    OS: Windows 10 10.0.18363
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
  Binaries:
    Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 97.0.4692.99
    Edge: Spartan (44.18362.1593.0)
  npmPackages:
    gatsby: ^4.6.2 => 4.6.2
    gatsby-plugin-image: ^2.6.0 => 2.6.0
    gatsby-plugin-sharp: ^4.6.0 => 4.6.0
    gatsby-source-filesystem: ^4.6.0 => 4.6.0
    gatsby-transformer-sharp: ^4.6.0 => 4.6.0
  npmGlobalPackages:
    gatsby-cli: 4.6.1
```

**Comment by LekoArts** [comment]
Please see https://github.com/gatsbyjs/gatsby/issues/34431#issuecomment-1008598727
