### ISSUE TITLE
gatsby-browser.js Can't resolve — Tailwindcss Guide

### ISSUE THREAD

**Issue by D1no** [gatsbyjs/gatsby#34731]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I followed the tailwindcss documentation and gatsby documentation to get tailwindcss working in Gatsby. They require to create a `gatsby-browser.js` file and add import in there a css file. That leads to a *Module not found: Error: Con't resolve*

### Reproduction Link

https://www.gatsbyjs.com/docs/how-to/styling/tailwind-css/#option-1-postcss

### In the Gatsby Docs
https://www.gatsbyjs.com/docs/how-to/styling/tailwind-css/#option-1-postcss

In your `gatsby-browser.js` put:
```js
import "tailwindcss/dist/base.min.css"
```

That is outdated since there is no `dist/base.min.css` in the tailwind npm package. Leads to the same error.

### In the Tailwind Docs
https://tailwindcss.com/docs/installation/using-postcss

Learning you need to do
![image](https://user-images.githubusercontent.com/2397125/152626395-402a6174-ba3c-484c-863d-65e3a0b1223a.png)

So following that by creating a css file in my project; a `src/global.css` with the content:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```
and imported in a new `gatsby-browser.js` file as
```js
import './src/global.css'
```
leads also to the same error. Incl. many require / import path variations etc.

### After hours of
searching around (not much experience with wepback and how gatsby stringed this together) I found this:
https://stackoverflow.com/a/67172790

Incl the mentioned issue [this comment](https://github.com/postcss/postcss/issues/1509#issuecomment-790147136) and https://github.com/postcss/postcss/issues/1509#issuecomment-772097567

So after doing `npm i path-browserif` and created a `gatsby-node.js` file with the content
```js
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
   resolve: {
      fallback: {
        path: require.resolve('path-browserify'),
      },
    },
  })
}

```

the error is gone now.

### Expected Result

Documentation that is correct or has an outdated flag, as well as a peanut butter jelly sandwich.

### Actual Result

```bash
failed Re-building development bundle - 0.244s
ERROR in ./gatsby-browser.js 4:0-24
Module not found: Error: Can't resolve '/src/global.css' in '/Users/worker/development/gatsbytest'
 @ ./.cache/api-runner-browser-plugins.js 36:10-41
 @ ./.cache/api-runner-browser.js 4:14-53
 @ ./.cache/app.js 12:0-65 29:87-33:1 37:20-29 50:0-14 116:17-26 150:6-15 29:0-33:2
```

### Environment

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvs/default/bin/node
    npm: 8.1.2 - ~/.nvs/default/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 97.0.4692.99
    Safari: 15.2
  npmPackages:
    gatsby: ^4.6.2 => 4.6.2
    gatsby-plugin-emotion: ^7.6.0 => 7.6.0
    gatsby-plugin-google-analytics: ^4.6.0 => 4.6.0
    gatsby-plugin-image: ^2.6.0 => 2.6.0
    gatsby-plugin-mdx: ^3.6.0 => 3.6.0
    gatsby-plugin-postcss: ^5.6.0 => 5.6.0
    gatsby-plugin-react-helmet: ^5.6.0 => 5.6.0
    gatsby-plugin-sharp: ^4.6.0 => 4.6.0
    gatsby-source-filesystem: ^4.6.0 => 4.6.0
    gatsby-transformer-sharp: ^4.6.0 => 4.6.0
```

**Comment by pieh** [comment]
Hi @D1no, you are right - the docs must have been written against older version of tailwind. Would you be willing to update https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/how-to/styling/tailwind-css.md ?

**Comment by duykienvp** [comment]
I had the same issue. I tried what @D1no suggested but still got the same error. Please help

**Comment by ZamZao** [comment]
Hello,
I stumbled on the same issue and found that the trick is to go through import in CSS file and import the CSS in the gatsby-browser (same as OP) 

 I am willing to update the document, so people do not get confused and waste hours as OP and I did.
