### ISSUE TITLE
HMR not working with preact

### ISSUE THREAD

**Issue by cortopy** [gatsbyjs/gatsby#34767]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

This [issue](https://github.com/gatsbyjs/gatsby/issues/30190) regarding HMR not working with preact. The issue was closed, but as reported by several users, HMR still doesn't work with latest versions of Gatsby

### Reproduction Link

https://github.com/pieh/gatsby-plugin-preact-hmr-repro

### Steps to Reproduce

1. Clone the preact demo
2. Test HMR

### Expected Result

HMR should work with `gatsby develop`

### Actual Result

INstead of HMR, the page is fully reloaded for each change

### Environment

```shell
System:
    OS: Linux 5.10 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 14.18.3 - /tmp/xfs-d693acfa/node
    Yarn: 3.1.1 - /tmp/xfs-d693acfa/yarn
    npm: 8.4.0 - ~/.opt/n/bin/npm
  Languages:
    Python: 3.10.2 - /usr/bin/python
  npmPackages:
    gatsby: 4.5.5 => 4.5.5
    gatsby-image: 3.11.0 => 3.11.0
    gatsby-omni-font-loader: 1.3.3 => 1.3.3
    gatsby-plugin-image: 2.5.2 => 2.5.2
    gatsby-plugin-postcss: 5.5.0 => 5.5.0
    gatsby-plugin-preact: 6.5.0 => 6.5.0
    gatsby-plugin-react-helmet: 5.5.0 => 5.5.0
    gatsby-plugin-resolve-src: 2.1.0 => 2.1.0
    gatsby-plugin-sass: 5.5.0 => 5.5.0
    gatsby-plugin-sharp: 4.5.2 => 4.5.2
    gatsby-plugin-typescript: 4.5.2 => 4.5.2
    gatsby-plugin-webpack-bundle-analyser-v2: 1.1.26 => 1.1.26
    gatsby-source-filesystem: 4.5.2 => 4.5.2
    gatsby-source-strapi: 1.0.2 => 1.0.2
    gatsby-transformer-sharp: 4.5.0 => 4.5.0
  npmGlobalPackages:
    gatsby-cli: 4.6.0
```

**Comment by LekoArts** [comment]
Please create a new [minimal reproduction][reproduction] using the latest Gatsby versions (and possibly React 18)

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment]
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!
