### ISSUE TITLE
Gatsby build throw error when using preact and new jsx runtime

### ISSUE THREAD

**Issue by Austaras** [gatsbyjs/gatsby#34783]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

There're two layers of bug:
1. when set `jsxRuntime: "automatic"` and add `gatsby-plugin-preact`, develop and build will throw "not found react/jsx-runtime" and mannually set `jsxImportSource: "preact"` could solve this
2. build will throw
```
 ERROR #95313

Building static HTML failed for path "/404/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


  221 |           ...pageData.result,
  222 |           params: {
> 223 |             ...grabMatchParams(this.props.location.pathname),
      |                                                    ^
  224 |             ...(pageData.result?.pageContext?.__params || {}),
  225 |           },
  226 |         }


  WebpackError: TypeError: Cannot read properties of undefined (reading 'pathname')
```

### Reproduction Link

https://github.com/Austaras/bug-repro

### Steps to Reproduce

1. `yarn`
2. `yarn run build`

### Expected Result

Build website

### Actual Result

Build throw error

### Environment

```shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Shell: 3.3.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 17.4.0 - /var/folders/t0/h670jy_11_l3v79qdx_pjf500000gn/T/yarn--1644463332534-0.47280520291650063/node
    Yarn: 1.22.17 - /var/folders/t0/h670jy_11_l3v79qdx_pjf500000gn/T/yarn--1644463332534-0.47280520291650063/yarn
    npm: 8.3.1 - /opt/homebrew/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 98.0.4758.80
    Safari: 15.2
  npmPackages:
    gatsby: ^4.7.1 => 4.7.1 
    gatsby-plugin-preact: ^6.7.0 => 6.7.0 
    gatsby-source-filesystem: ^4.7.0 => 4.7.0 
    gatsby-transformer-remark: ^5.7.0 => 5.7.0
```

### Config Flags

jsxRuntime: "automatic"

**Comment by LekoArts** [comment]
We recently updated https://www.gatsbyjs.com/docs/reference/config-files/gatsby-config/#jsximportsource to include more documentation. Please create a [minimal reproduction][reproduction] using the latest versions of everything and following the instructions.

[reproduction]: https://gatsby.dev/reproduction
