### ISSUE TITLE
Webfaction/self-hosting deployment?

### ISSUE THREAD

**Issue by IainIsCreative** [gatsbyjs/gatsby#3480]
I have a question in regards to deployment: I'm seeing a lot of documentation in regards to deploying Gatsby to Github, Gitlab, Heroku, Netlify etc. but I'm not seeing much in regards to using your own host...is there any advice that can be given to deploying to places like Webfaction, Media Temple etc.?

Is there any extra tips that are required for deploying a Gatsby site to other hosts, or is it acceptable to deploy the `public` directory by itself? Any advice?

**Comment by KyleAMathews** [comment]
Static sites are ideally served by a CDN as that's fastest. Beyond that, where you deploy it doesn't matter too much. Serving a static site with something like Nginx can work well. Using a dedicated static site host is easiest though as they take care of things working best.

**Comment by fk** [comment]
> acceptable to deploy the public directory by itself

Totally!

Did this work out for you @IainIsCreative?
If yes, please consider closing this issue. 🤗

**Comment by IainIsCreative** [comment]
Hey folks,

I made a simple page a few weeks ago, and the public directory has been deployed to webfaction. Seems to be working fine!

Closing this now.

**Comment by fk** [comment]
Yay! Happy to hear things are working!
