### ISSUE TITLE
System freezes on stopping `gatsby develop`

### ISSUE THREAD

**Issue by harshraj8843** [gatsbyjs/gatsby#34808]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

On stopping development server with `^C` , system freezes for a very long time i.e full ram is used for some process.

### Reproduction Link

https://github.com/adobedocs/dev-site-documentation-template/

### Steps to Reproduce

1. `npm install`
2. `npm run dev`
3. `^C`

### Expected Result

development server should stop normally.

### Actual Result

This is frequently happening.

![Screenshot from 2022-02-14 14-37-14](https://user-images.githubusercontent.com/54644599/153839089-a0461695-33de-4ef3-b250-922b8d49818e.png)

Sometimes it takes whole memory and take much time to recover.

![Screenshot from 2022-02-14 14-56-20](https://user-images.githubusercontent.com/54644599/153839105-1cc60194-14ac-429e-94cd-0ef077c5ac18.png)

### Environment

```shell
System:
    OS: Linux 5.13 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.19.0/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 96.0
  npmPackages:
    gatsby: ^3.14.6 => 3.14.6
    gatsby-plugin-exclude: ^1.0.2 => 1.0.2
    gatsby-source-filesystem: ^4.7.0 => 4.7.0
  npmGlobalPackages:
    gatsby-cli: 4.7.0
```

### Config Flags

No

**Comment by marvinjude** [comment]
Hi @harshraj8843,

Thanks for opening this issue. We suspect that this may be some issues with some issue with Gatsby(most like not) or third party dependencies doing some memory intensive work during process tear-down. This may be addressed during future memory improvement projects. 

Does this happen every single time you exit the process?

**Comment by harshraj8843** [comment]
@marvinjude 

> Does this happen every single time you exit the process?

Yes every single time.

To reduce system freeze time, i do follows :- 
- close every application while server is running (free up RAM)
- close server with ` ^C `
- close terminal immediately
  - I noticed that `closing terminal immediately` reduces system freeze time
- wait for system to recover

😞
