### ISSUE TITLE
StaticQuery failing

### ISSUE THREAD

**Issue by martinpsz** [gatsbyjs/gatsby#34815]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I cannot execute a StaticQuery from one of my components. I am trying to query the siteMetaData. The query works in Graphiql but does not retrieve anything when run in my component. 

I have tried using StaticQuery, which returns no error just 'StaticQuery(loading)'. When I use the useStaticQuery hook and running 'gatsby develop', I get an error like so:

`ModuleNotFoundError: Module not found: Error: Can't resolve '../public/
  page-data/sq/d/3080673216.json' in '../components'`

I have tried executing the static query in a separate custom hook component, which does not resolve the situation. I have also tried other things like running 'gatsby clean' and reinstalling the node_modules. Nothing has worked. 

I have one page query at index.js required by the react i18 next plugin I am using for multi-language support. 

### Reproduction Link

https://gitlab.com/martinpsz/chalice/-/tree/dev

### Steps to Reproduce

1.In MenuItems.jsx, execute static query to return siteMetadata.
2.
3.
...

### Expected Result

Return siteMetadata as data for use in component

### Actual Result

Failed to compile when using useStaticQuery and 'gatsby develop'. Compiles when using staticQuery but returns StaticQuery loading rather than data.

### Environment

```shell
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Max
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.5.0 - /opt/homebrew/bin/node
    npm: 8.4.1 - /opt/homebrew/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 98.0.4758.102
    Firefox: 97.0
    Safari: 15.3
  npmPackages:
    gatsby: ^4.7.1 => 4.7.1
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-netlify: ^4.1.0 => 4.1.0
    gatsby-plugin-react-helmet: ^5.7.0 => 5.7.0
    gatsby-plugin-react-i18next: ^1.2.2 => 1.2.2
    gatsby-plugin-styled-components: ^5.7.0 => 5.7.0
    gatsby-source-filesystem: ^4.7.0 => 4.7.0
```

**Comment by marvinjude** [comment]
Hi @martinpsz,

The `components` directory  needs to be in your `src` directory. A quick look through the examples in the [static query docs](https://www.gatsbyjs.com/docs/how-to/querying-data/use-static-query/) should show you the ideal place to add it :)

Happy building!

**Comment by AlastairTaft** [comment]
Seemed to hit this issue when I had two different graphQL queries with the same name.

**Comment by WillGarman** [comment]
> @AlastairTaft  Seemed to hit this issue when I had two different graphQL queries with the same name.

This is the answer I have been looking for. Instantly fixed my problem!

**Comment by 2u841r** [comment]
> Seemed to hit this issue when I had two different graphQL queries with the same name.

Thank you.

**Comment by mukuljhamb** [comment]
> Seemed to hit this issue when I had two different graphQL queries with the same name.

Thanks

**Comment by JayKania** [comment]
> Seemed to hit this issue when I had two different graphQL queries with the same name.

2025 and still helpful!
