### ISSUE TITLE
gatsby-plugin-sitemap default output does not comply with spec and Google

### ISSUE THREAD

**Issue by don-esteban** [gatsbyjs/gatsby#34811]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

`gatsby-plugin-sitemap` default `output` option generates sitemaps in the folder `/sitemap`. The [spec](https://www.sitemaps.org/protocol.html) says about [sitemap location](https://www.sitemaps.org/protocol.html#location):

> The location of a Sitemap file determines the set of URLs that can be included in that Sitemap. A Sitemap file located at http://example.com/catalog/sitemap.xml can include any URLs starting with http://example.com/catalog/ but can not include URLs starting with http://example.com/images/.

Google [says](https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap#general-guidelines):

> **A sitemap can be posted anywhere on your site, but a sitemap affects only descendants of the parent directory.** Therefore, a sitemap posted at the site root can affect all files on the site, which is where we recommend posting your sitemaps.

### Reproduction Link

https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sitemap#options

### Steps to Reproduce

Use the plugins default configuration.

1. https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sitemap#options

### Expected Result

The path should be `/`

### Actual Result

The path is `/sitemap`

### Environment

```shell
System:
    OS: macOS 12.1
    CPU: (16) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    npm: 8.3.0 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 97.0
    Safari: 15.2
  npmPackages:
    gatsby: ^4.5.4 => 4.6.0 
    gatsby-image: ^3.11.0 => 3.11.0 
    gatsby-plugin-fontawesome-css: ^1.2.0 => 1.2.0 
    gatsby-plugin-manifest: ^4.6.0 => 4.6.0 
    gatsby-plugin-mdx: ^3.5.2 => 3.6.0 
    gatsby-plugin-react-helmet: ^5.6.0 => 5.6.0 
    gatsby-plugin-root-import: ^2.0.8 => 2.0.8 
    gatsby-plugin-sass: ^5.5.0 => 5.6.0 
    gatsby-plugin-sharp: ^4.5.2 => 4.6.0 
    gatsby-plugin-sitemap: ^5.6.0 => 5.6.0 
    gatsby-remark-autolink-headers: ^5.5.0 => 5.6.0 
    gatsby-remark-copy-linked-files: ^5.5.0 => 5.6.0 
    gatsby-remark-images: ^6.5.2 => 6.6.0 
    gatsby-remark-normalize-paths: ^1.1.0 => 1.1.0 
    gatsby-remark-responsive-iframe: ^5.5.0 => 5.6.0 
    gatsby-remark-smartypants: ^5.5.0 => 5.6.0 
    gatsby-source-filesystem: ^4.5.2 => 4.6.0 
    gatsby-transformer-sharp: ^4.6.0 => 4.6.0 
    gatsby-transformer-yaml: ^4.6.0 => 4.6.0 
  npmGlobalPackages:
    gatsby-cli: 4.7.0
```

**Comment by marvinjude** [comment]
Hi @don-esteban,

Thanks for reporting this issue. We'll probably change the defaults here and in an upcoming major release. For now, I believe passing your desired option should work well for you.

**Comment by acidicX** [comment]
I've just seen this as well, makes absolute sense to change the default. I also had to set the option to `/` explicitly.

**Comment by don-esteban** [comment]
I would like to suggest an intermediate solution. Updating the docs with a highlighted advice. We had for some weeks a broken sitemap (not really broken, but useless) until SEO-people notices us.

**Comment by laurenskling** [comment]
So, I was struggling getting a new project indexed. But now I really have a feeling this /sitemap/ folder is causing the hurt. I just changed it to root and submitted it. Just stumbled upon this issue by chance; checking out the issues list. If I didn't end up here by chance I would have never known my sitemaps where broken/useless. This is pretty nasty. We should really consider alerting users using /sitemap/ if it is really hurting the indexing.

**Comment by laurenskling** [comment]
I really think this should be reopened. The current defaults make the sitemap useless, with users trusting everything being alright after installing the plugin.
