### ISSUE TITLE
gatsby-plugin-mdx causes "Maximum call stack size exceeded" error on gatsby build

### ISSUE THREAD

**Issue by wltrallen2** [gatsbyjs/gatsby#34846]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Using gatsby v.4.7.2, when adding gatsby-plugin-mdx 3.7.1 (or any other version for that matter), on running `gatsby develop`, the build fails with the following error:

```
  ModuleBuildError: Module build failed (from ./node_modules/gatsby/
  dist/utils/babel-loader.js):
  RangeError: /Users/waltermayallen/Sites/akinsCounseling/node_modul
  es/gatsby-plugin-mdx/gatsby-ssr.js: Maximum call stack size exceed
  ed
```

This occurs whether I install the mdx plugin from the `gatsby new` script or independently after I've already created the project.

### Reproduction Link

https://github.com/wltrallen2/mdxErrorReproduction

### Steps to Reproduce

1. Run `gatsby new`
2. Choose to install markdown/MDX  - or - run `gatsby-plugin-mdx` after generating a new project
3.  Run `gatsby build`

### Expected Result

The project builds.

### Actual Result

The project build fails with
```
ModuleBuildError: Module build failed (from ./node_modules/gatsby/
  dist/utils/babel-loader.js):
  RangeError: /Users/waltermayallen/Sites/akinsCounseling/node_modul
  es/gatsby-plugin-mdx/gatsby-ssr.js: Maximum call stack size exceed
  ed
```

### Environment

```shell
System:
    OS: macOS 11.6.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 98.0.4758.102
    Firefox: 92.0
    Safari: 15.1
  npmPackages:
    gatsby: ^4.7.2 => 4.7.2
    gatsby-plugin-image: ^2.7.0 => 2.7.0
    gatsby-plugin-mdx: ^3.7.1 => 3.7.1
    gatsby-plugin-sharp: ^4.7.0 => 4.7.0
    gatsby-source-filesystem: ^4.7.0 => 4.7.0
  npmGlobalPackages:
    gatsby-cli: 4.7.0
```

### Config Flags

NO

**Comment by LekoArts** [comment]
Hi! This was an intermittent upstream issue that is fixed now: https://github.com/gatsbyjs/gatsby/issues/34823

Your lock file still has

```
"node_modules/@babel/core": {
      "version": "7.17.3",
      "resolved": "https://registry.npmjs.org/@babel/core/-/core-7.17.3.tgz",
```

So delete it and re-install again and it'll work as 7.17.4 will get installed.

Both `gatsby new` and just installing the plugin don't have a lock file or pinned version to this, so I'm not sure how you installed this faulty version and not the `latest`.
