### ISSUE TITLE
AVIF format: gatsby-plugin-sharp defaults don't get picked up

### ISSUE THREAD

**Issue by buondevid** [gatsbyjs/gatsby#34840]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I can't manage to set `gatsby-plugin-sharp` defaults to output AVIF images.

I tried every combination and order of `auto`, `webp`, `avif` and the images outputted never show up as AVIF and they don't even appear in `<source>` of `<picture>` HTML tag.

My configs:
```js
// gatsby-config.js
`gatsby-plugin-image`,
    {
      resolve: `gatsby-plugin-sharp`,
      options: {
        defaults: {
          formats: [`avif`, `webp`, `auto`],
          quality: 90,
        },
      },
    },
    `gatsby-transformer-sharp`,
```

An example of image query:
```js
backgroundImage {
                gatsbyImageData(layout: FULL_WIDTH, quality: 90)
              }
```
_AVIF format doesn't show up_
![image](https://user-images.githubusercontent.com/36935593/154459111-4ad8d954-ad23-4147-955a-ba909a9b8de6.png)

Am I doing something wrong?

---

The only way I can manage to output an AVIF is working directly on the query like so:
```js
backgroundImage {
                gatsbyImageData(layout: FULL_WIDTH, quality: 90, formats: [AVIF, WEBP, AUTO])
              }
```
This solution doesn't require any settings in `gatsby-config.js` but this is far from desirable as I have hundreds of images on the website and I would like to be able to just set my desirable output in the configs.

NB: This last snippet only works if you set `AVIF` first. If you set it up like in the docs (i.e. `formats: [AVIF, WEBP, AUTO]` it doesn't work, webp gets picked up, so I think there is also a problem of priority in format).

### Reproduction Link

-

### Steps to Reproduce

1.  In `gatsby-config.js`, under `gatsby-plugin-sharp`, configure:
```js
 {
      resolve: `gatsby-plugin-sharp`,
      options: {
        defaults: {
          formats: [`avif`, `webp`, `auto`],
          quality: 90,
        },
      },
    },
```
You can try also changing the order of the formats.
2.  Then in your GraphQL query, query the image like so:
```js
... on ContentfulHeroBlock {
              backgroundImage {
                gatsbyImageData(layout: FULL_WIDTH, quality: 90)
              }
            }
```
3. Now run `gatsby develop` the website and check the image that is actually downloaded (in the latest Chrome).
...

### Expected Result

I would expect the AVIF to be downloaded, in the latest Chrome, or at least to show up in the `<source>` of `<picture>` HTML element.

### Actual Result

AVIF format image never shows up.

The only way to make it work is writing directly in the query, for every image, and with the right order of formats.

### Environment

```shell
System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.5.0 - ~/.nvm/versions/node/v17.5.0/bin/node
    npm: 8.4.1 - ~/.nvm/versions/node/v17.5.0/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 98.0.4758.102
    Safari: 15.1
  npmPackages:
    gatsby: ^4.7.2 => 4.7.2 
    gatsby-plugin-google-gtag: ^4.7.0 => 4.7.0 
    gatsby-plugin-hubspot: ^2.0.0 => 2.0.0 
    gatsby-plugin-image: ^2.7.0 => 2.7.0 
    gatsby-plugin-manifest: ^4.7.0 => 4.7.0 
    gatsby-plugin-page-progress: ^2.2.1 => 2.2.1 
    gatsby-plugin-preload-fonts: ^3.7.0 => 3.7.0 
    gatsby-plugin-react-helmet: ^5.7.0 => 5.7.0 
    gatsby-plugin-sharp: ^4.7.0 => 4.7.0 
    gatsby-plugin-sitemap: ^5.7.0 => 5.7.0 
    gatsby-plugin-styled-components: ^5.7.0 => 5.7.0 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.26 => 1.1.26 
    gatsby-remark-autolink-headers: ^5.7.0 => 5.7.0 
    gatsby-source-contentful: ^7.5.0 => 7.5.0 
    gatsby-source-filesystem: ^4.7.0 => 4.7.0 
    gatsby-transformer-remark: ^5.7.0 => 5.7.0 
    gatsby-transformer-sharp: ^4.7.0 => 4.7.0
```

**Comment by buondevid** [comment]
We think it might be related to `gatsby-source-contentful` plugin which doesn't let the images pass through the sharpen plugin more than related to Gatsby itself, so if you think this is the case and you don't know any solution, feel free to close this 👍 .

**Comment by tyhopp** [comment]
Hi @buondevid!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction].

I did check that `gatsby-source-contentful` does have [support for AVIF](https://github.com/gatsbyjs/gatsby/pull/33903) and some [info in the readme on using the image and sharp plugin](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-contentful#displaying-responsive-image-with-gatsby-plugin-image) so it looks like your case should work.

If you're still running into this issue please provide a minimal reproduction and we can go from there. Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by jhowsick** [comment]
Yeah the documentation is Poor ;)

I found out that you need to add defaultQuality  to the root of your gatsby-plugin-sharp options (options.defaultQuality). This way the images are downloaded losslessly. The default is [50-75] which is why the queries return poor results no matter the quality set in options.defaults. 

There seems to be another processing step that occurs when downloading the images per downloadLocal. The options.defaults are ignored and only the other root options parameters are used. 

You can verify that the downloaded images are Lossless by setting the options.defaultQuality to 100 and then comparing the files that are downloaded / generated in public/static to the ones you have uploaded in Contentful.  

I hope this helps anyone scratching their head wondering what the fish! :)
