### ISSUE TITLE
Gatsby build as part of express app

### ISSUE THREAD

**Issue by suchy** [gatsbyjs/gatsby#3485]
Hi,  first of all - Gatsby looks very interesting - grat job and thanks! ;-)

So my question is - I'm planing to build a solution based on static sites generator and express.
I have hosting where `/public` is served by nginx and everything else could be a express route.

My plan is to have express route `/api/rebuild` which will be the place for webhooks (contentful and github). When request came gatsby will build static site into `/public`.

This way allows me also to have some custom api endpoints (sending emails, do some custom stuff) and still keep static site.

Any ideas how to call gatsby build from express route? Any chance for promisify build to have way to hook into after it's finish?

Thanks!

**Comment by KyleAMathews** [comment]
Sounds cool! I'd just use the exec API for Node.js. Good luck! https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

**Comment by suchy** [comment]
Thanks!
