### ISSUE TITLE
Add semicolons at end of line in starter templates

### ISSUE THREAD

**Issue by andrewpmk** [gatsbyjs/gatsby#34866]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

The JavaScript and TypeScript in the starter templates gatsby/starters/gatsby-starter-minimal and gatsby/starters/gatsby-starter-minimal-ts should have semicolons at the end. Causes jshint to complain and eslint to complain if you install it and is generally bad practice.

e.g.

const pageStyles = {
  color: "#232129",
  padding: 96,
  fontFamily: "-apple-system, Roboto, sans-serif, serif",
}

should be changed to

const pageStyles = {
  color: "#232129",
  padding: 96,
  fontFamily: "-apple-system, Roboto, sans-serif, serif",
};

### Reproduction Link

https://github.com/gatsbyjs/gatsby

### Steps to Reproduce

1. Create a new project with Gatsby CLI

### Expected Result

Starter templates should use semicolons at end of line.

### Actual Result

Starter templates are missing semicolons and causes jshint to complain in Visual Studio Code.

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.10.1
  Browsers:
    Chrome: 98.0.4758.102
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.56)
  npmGlobalPackages:
    gatsby-cli: 4.7.0
```

### Config Flags

none

**Comment by tyhopp** [comment]
Hi @rahulsunil2, thanks for making the effort to create this issue and associated PRs.

No ending semicolons is a deliberate style choice for all files in the monorepo that you can see in our [prettier config](https://github.com/gatsbyjs/gatsby/blob/master/.prettierrc.js#L3). The starters are a starting point for your project, feel free to adjust the tooling however you like after you've cloned them.

If you are having issues configuring tools like eslint, [the docs on eslint configuration](https://www.gatsbyjs.com/docs/how-to/custom-configuration/eslint/) may be helpful.

I'll consider this resolved and will close this issue and the PRs. Thanks again for the effort!
