### ISSUE TITLE
"/*" as key leads to GraphQL warning

### ISSUE THREAD

**Issue by zionis137** [gatsbyjs/gatsby#3487]
## Description

If one adds in gatsby-config an option with key `/*` (like: `'/*': "SomeStuff"`) this leads to the following GraphQL warning:
> Name "\__" must not begin with "__", which is reserved by GraphQL introspection. In a future release of graphql this will become a hard error.

Notice that it does not matter to which plugin I pass this object.

### Environment

Gatsby version: 1.9.153
Node.js version: 9.4.0
Operating System: Linux, Windows

### File contents:

`gatsby-config.js`: 
```
  plugins: [
    {
      resolve: `gatsby-source-filesystem`,    // Just a demo, works for all plugins
      options: {
        path: `${__dirname}/src/pages`,
        name: 'pages',
        '/*': "SomeStuff"         // This leads to warning
      },
    },
  ]
```

### Actual result

The full warning text is in #2925

### Expected behavior

No warning

### Steps to reproduce

1\. add the key `'/*'` to a plugin-option

**Comment by DSchau** [comment]
This was kind of a difficult one (for me!) to debug, but I think I've traced the issue.

The error is that [this line](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/create-key.js#L17) is creating the structure `___SOMETHING` (or `__`, if the expression matches each character). For example, consider the following table:

|Input|Output|
|:----:|:------:|
|`/*`|`__`|
|`/*.js`|`___js`|
|`/*.html`|`___html`|

As `__` is reserved for internal GraphQL stuff, herein lies the issue. I'm not really sure what the resulting node name _should_ be but I think I've identified the issue at least. Should be easy to fix once I'm aware of how to proceed! I'll open a PR with a first shot at it, and then we can iterate from there further.
