### ISSUE TITLE
Bug with gatsby-source-google-docs documentation?

### ISSUE THREAD

**Issue by acao** [gatsbyjs/gatsby#34872]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

The plugin library docs flash the SSG content, but then they vanish on hydration.

Other pages work, it's just something with this source plugin

The only error i saw in chromium was that the logo.png for this plugin failed to load

If i go to another page and navigate back it loads, so it's definitely hydration related

If the failing image request causes this, then that might be something to look into!

### Reproduction Link

https://www.gatsbyjs.com/plugins/gatsby-source-google-docs/

### Steps to Reproduce

1. Navigate straight to page
2. See SSG version flash for .5s
3. Observe plugin docs vanishing on hydration
...

### Expected Result

I should see the gatsby-source-google-docs plugin docs on a full page load

### Actual Result

They appear and then vanish on a full page load

### Environment

```shell
Linux & Firefox (also tried with chromium incognito, with browser extensions disabled)
```

**Comment by tyhopp** [comment]
Hi @acao, thanks for the report! I will close this now as we will track this internally as a support issue.
