### ISSUE TITLE
gatsby-plugin-image not showing images on first load.

### ISSUE THREAD

**Issue by dongepulango** [gatsbyjs/gatsby#34883]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

`gatsby-plugin-image` not showing images on first load in Safari and Chrome when I build the site. In `gatsby develop` everything works fine but in `gatsby serve` and in my Netlify images are not shown in first load, I have to click a router link to make the images show. I'm using Wordpress as a headless CMS btw, and I think only affects images pulled from WP. Any help would be greatly appreciated. 

### Reproduction Link

https://gatsby-image-wp-test.netlify.app/

### Steps to Reproduce

1. Open the link
2. See no images are show on first load
3. Click a some link and go back to home page.

### Expected Result

Images are shown like in Development.

### Actual Result

No images shown on first load when site is built.

### Environment

```shell
System:
    OS: macOS 12.1
    CPU: (8) x64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.19.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 98.0.4758.102
    Firefox: 90.0.2
    Safari: 15.2
  npmPackages:
    gatsby: ^4.4.0 => 4.6.0
    gatsby-image: ^3.11.0 => 3.11.0
    gatsby-plugin-image: ^2.5.0 => 2.6.0
    gatsby-plugin-manifest: ^4.4.0 => 4.6.0
    gatsby-plugin-offline: ^5.4.0 => 5.6.0
    gatsby-plugin-react-helmet: ^5.0.0 => 5.6.0
    gatsby-plugin-sass: ^5.6.0 => 5.6.0
    gatsby-plugin-sharp: ^4.5.0 => 4.6.0
    gatsby-plugin-sitemap: ^5.7.0 => 5.7.0
    gatsby-plugin-styled-components: ^5.4.0 => 5.6.0
    gatsby-plugin-wpgraphql-seo: ^1.4.1 => 1.4.1
    gatsby-source-filesystem: ^4.4.0 => 4.6.0
    gatsby-source-wordpress: ^6.4.0 => 6.6.0
    gatsby-transformer-json: ^4.4.0 => 4.6.0
    gatsby-transformer-remark: ^5.4.0 => 5.6.0
    gatsby-transformer-sharp: ^4.5.0 => 4.6.0
  npmGlobalPackages:
    gatsby-cli: 3.1.0
```

**Comment by tyhopp** [comment]
Hi @dongepulango!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by dongepulango** [comment]
@tyhopp Hi, I updated the link now with just 1 image on it. Hope it helps to demonstrate the issue. You can open the link in Safari and the` <img>` has `data-src` and `opacity: 0;`.

Also I just found out it happens to Chrome as well, depends on the screen size. Not sure if this is a `gatsby-plugin-image` issue or a `gatsby-source-wordpress` one.

**Comment by tyhopp** [comment]
Hi @dongepulango, [gatsby@4.8.0](https://www.gatsbyjs.com/docs/reference/release-notes/v4.8) was released yesterday and includes [a fix for `gatsby-source-wordpress` image loading on Safari](https://github.com/gatsbyjs/gatsby/pull/34727). Can you try upgrading to that version and see if it fixes the issue on Safari?

I was able to see that the image from the link you shared loads sometimes in Chrome and doesn't load other times. Can you share a link to the source code for your minimal reproduction?

**Comment by Mrchow86** [comment]
Mate I honestly don't know what I mean by the minimal reproductive
thing.... I went on there to try see if my partner was on there that's the
only time iv been on that I don't know how to use it properly

**Comment by dongepulango** [comment]
@tyhopp closing since updating to latest version did fix the problem. Thank you

**Comment by Mrchow86** [comment]
Thanks you... can you please send me that information the fish name on
email.. they have all different ones
