### ISSUE TITLE
how to replace index.md with index.jsx

### ISSUE THREAD

**Issue by Maxhodges** [gatsbyjs/gatsby#349]
I pulled the [starter documentation demo](https://github.com/gatsbyjs/gatsby-starter-documentation), and added Semantic-UI to the project. How can I replace the default `index.md` file with a react component instead? I'm not sure why it's expecting index.md. I removed it.

```
.*$:33 Uncaught Error: Cannot find module './index.md'.
client.js:58 [HMR] connected
```

**Comment by Maxhodges** [comment]
ah nevermind! It seems after deleting files I need to stop the server and run gatsby develop again then refresh the browser!

**Comment by KyleAMathews** [comment]
Yeah... :-( not obvious at all unfortunately. I think this can be eliminated in the future but need to do some experimenting...
