### ISSUE TITLE
Shopify no longer uses private apps and passwords

### ISSUE THREAD

**Issue by mcdowellalex** [gatsbyjs/gatsby#34908]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

Shopify has deprecated the use of private apps as of a couple of months ago. They are now custom apps and no longer use a password, it is just an access token. https://help.shopify.com/en/manual/apps/private-apps

### Steps to Resolve this Issue

1. Update the documentation on this page
2. Update the plugin

**Comment by tyhopp** [comment]
Hi @mcdowellalex, thanks for the issue!

To make the process of resolving problems quicker for both sides please include what you expect to see and what you're actually seeing in the documentation (links are also helpful) in the issue description.

We also welcome PRs if you are interested in putting one up for this!

**Comment by Mrchow86** [comment]
No I don't want anything I honestly don't know what I have done I wasn't
expecting anything like I said I thought my partner was in there that's all.

**Comment by tyhopp** [comment]
Related https://github.com/gatsbyjs/gatsby/discussions/34828
