### ISSUE TITLE
Error occurred while fetching nodes of the "Post" type.

### ISSUE THREAD

**Issue by andreybo** [gatsbyjs/gatsby#34902]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

im trying to get database from wordpress with gatsby-source-wordpress. tags, categories, users were fetched but posts always ZERO. demo data from tutors works fine, i think the problem in the current database for wordpress. im getting issue "An empty string was returned instead of a response when making a GraphQL request. Error occurred while fetching nodes of the "Page" type." i don't know, maybe problem with the wrong lines i MySQL for post_type. i have a few lines like nav_menu_item,tribe_organizer,tribe_venue etc. how to solve it or exclude these post_types from fetching.

### Reproduction Link

https://github.com/gatsbyjs/gatsby-starter-blog

### Steps to Reproduce

1. add https://www.blog.udonis.co/graphql
2. add url to the current website (sorry I can share just parts of code)
3. build
...

### Expected Result

Get more than 300 posts. But  now its ZERO. tags and categories are fine

### Actual Result

success  gatsby-source-wordpress  ingest WPGraphQL schema - 2.825s
success createSchemaCustomization - 5.003s
success  gatsby-source-wordpress  Taxonomy - 1.004s - fetched 3
success  gatsby-source-wordpress  UserRole - 1.009s - fetched 0
success  gatsby-source-wordpress  Block - 1.099s - fetched 0
success  gatsby-source-wordpress  Cache - 1.117s - fetched 0
success  gatsby-source-wordpress  fetch root fields - 1.139s
success  gatsby-source-wordpress  PostFormat - 1.110s - fetched 8
success  gatsby-source-wordpress  Menu - 1.135s - fetched 1
success  gatsby-source-wordpress  ContentType - 1.159s - fetched 3
⠀
warn  gatsby-source-wordpress 

An empty string was returned instead of a response when making a GraphQL request.
This may indicate that you have a WordPress filter running which is causing WPGraphQL
to return an empty string instead of a response.
Please open an issue with a reproduction at
https://github.com/gatsbyjs/gatsby/issues/new
for more help

Error occurred while fetching nodes of the "Page" type.

WPGraphql
----------------
        {
          "sql": "SELECT post_id, meta_key, meta_value FROM wpon_postmeta WHERE post_id IN (9229) ORDER BY meta_id ASC",
          "time": 0.0002040863037109375,
          "stack": "require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, wpDiscuzForm->initPersonalDataExporter, wpdFormAttr\\Tools\\PersonalDataExporter::getInstance, wpdFormAttr\\Tools\\PersonalDataExporter->__construct, wpdFormAttr\\Tools\\PersonalDataExporter->initFormsFields, get_posts, WP_Query->query, WP_Query->get_posts, update_post_caches, update_postmeta_cache, update_meta_cache"
        },

### Environment

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.10.1
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (98.0.1108.56)
  npmPackages:
    gatsby: ^4.8.0 => 4.8.0
    gatsby-plugin-disqus: ^1.2.3 => 1.2.3
    gatsby-plugin-gdpr-cookies: ^2.0.8 => 2.0.8
    gatsby-plugin-google-analytics: ^4.7.0 => 4.7.0
    gatsby-plugin-image: ^2.7.0 => 2.7.0
    gatsby-plugin-manifest: ^4.7.0 => 4.7.0
    gatsby-plugin-mdx: ^3.7.0 => 3.7.0
    gatsby-plugin-no-sourcemaps: ^4.7.0 => 4.7.0
    gatsby-plugin-offline: ^5.7.0 => 5.7.0
    gatsby-plugin-react-helmet: ^5.7.0 => 5.7.0
    gatsby-plugin-robots-txt: ^1.7.0 => 1.7.0
    gatsby-plugin-sass: ^5.7.0 => 5.7.0
    gatsby-plugin-sharp: ^4.7.0 => 4.7.0
    gatsby-plugin-sitemap: ^5.7.0 => 5.7.0
    gatsby-remark-images: ^6.7.0 => 6.7.0
    gatsby-remark-lazy-load: ^1.0.2 => 1.0.2
    gatsby-source-filesystem: ^4.7.0 => 4.7.0
    gatsby-source-wordpress: ^6.8.0 => 6.8.0
    gatsby-transformer-remark: ^5.7.0 => 5.7.0
    gatsby-transformer-sharp: ^4.7.0 => 4.7.0
  npmGlobalPackages:
    gatsby-cli: 4.5.0
```

**Comment by tyhopp** [comment]
Hi @andreybo!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

For your case, this would mean cloning [`gatsby-starter-minimal`](https://github.com/gatsbyjs/gatsby-starter-minimal), adding the `gatsby-source-wordress` plugin and your configuration, and sharing the link to the public repo here.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by Mrchow86** [comment]
Umm wow really I have no idea what  is going in... and I didn't put up and
photos other then  my face which u would be able to see

**Comment by LekoArts** [comment]
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!
