### ISSUE TITLE
Typo for new TS option when creating a new project

### ISSUE THREAD

**Issue by rshackleton** [gatsbyjs/gatsby#34918]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

After running the `npx create-gatsby -ts` command added in [4.8](https://www.gatsbyjs.com/docs/reference/release-notes/v4.8/#new-typescript-option-when-creating-gatsby-projects-from-the-cli) the config file has a typo.

```
/** @type {import('gatsby).GatsbyConfig} */
module.exports = {
```

Should be:

```
/** @type {import('gatsby').GatsbyConfig} */
module.exports = {
```

Missing the closing ' in the type import.

### Reproduction Link

https://github.com/rshackleton/rs-gatsbyconf-2022/blob/ea17ea43ee238a93e1fe2777148e0ab96e1b7bf9/gatsby-config.js

### Steps to Reproduce

1. Create a new project with `npx create-gatsby -ts`

### Expected Result

Type import should provide intellisense for gatsby config.

### Actual Result

No intellisense on gatsby config due to typo.

### Environment

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor             
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (98.0.1108.55)
  npmPackages:
    gatsby: ^4.8.0 => 4.8.0 
    gatsby-plugin-emotion: ^7.8.0 => 7.8.0 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-image: ^2.8.0 => 2.8.0 
    gatsby-plugin-manifest: ^4.8.0 => 4.8.0 
    gatsby-plugin-react-helmet: ^5.8.0 => 5.8.0 
    gatsby-plugin-sharp: ^4.8.0 => 4.8.0 
    gatsby-plugin-sitemap: ^5.8.0 => 5.8.0 
    gatsby-source-filesystem: ^4.8.0 => 4.8.0 
    gatsby-transformer-sharp: ^4.8.0 => 4.8.0 
  npmGlobalPackages:
    gatsby-cli: 4.7.0
```

**Comment by brherr** [comment]
Would love to give this a shot!

**Comment by tyhopp** [comment]
Hi @rshackleton, thank you for the bug report! We'll definitely get this fixed.

@brherr if you're willing to put up a PR that would be fantastic!

**Comment by LekoArts** [comment]
It needs to be fixed here: https://github.com/gatsbyjs/gatsby/blob/master/starters/gatsby-starter-minimal-ts/gatsby-config.js#L1

**Comment by brherr** [comment]
#34924

**Comment by tyhopp** [comment]
Thanks @brherr for the fix!
