### ISSUE TITLE
[v2] Update Babel to v7

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#3492]
CRA just landed this https://github.com/facebookincubator/create-react-app/pull/3522

**Comment by jquense** [comment]
I tried this maybe last month or so and it was a bit of nightmare. Maybe the ecosystem is a bit more ready for switching over

**Comment by KyleAMathews** [comment]
Done!

**Comment by KyleAMathews** [comment]
https://github.com/gatsbyjs/gatsby/pull/3785
