### ISSUE TITLE
GatsbyCloud does not rebuild on commit of main (production) branch

### ISSUE THREAD

**Issue by peach-inzn** [gatsbyjs/gatsby#34948]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When pushing a new commit to my repository, GatsbyCloud does not trigger a new build. I am using Gatsby with WordPress as CMS. When something in WordPress changes, GatsbyCloud rebuilds, but on commit changes nothing happens.

### Expected Result

Trigger rebuild

### Actual Result

No rebuild triggered

### Environment

```shell
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.5.0 - /opt/homebrew/bin/node
    npm: 8.4.1 - /opt/homebrew/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 98.0.4758.109
    Safari: 15.3
  npmPackages:
    gatsby: ^4.8.0 => 4.8.0
    gatsby-plugin-image: ^2.8.1 => 2.8.1
    gatsby-plugin-manifest: ^4.8.1 => 4.8.1
    gatsby-plugin-sharp: ^4.8.1 => 4.8.1
    gatsby-source-filesystem: ^4.8.1 => 4.8.1
    gatsby-source-graphql: ^4.8.1 => 4.8.1
    gatsby-source-wordpress: ^6.8.1 => 6.8.1
    gatsby-transformer-sharp: ^4.8.0 => 4.8.0
  npmGlobalPackages:
    gatsby-cli: 4.8.1
    gatsby: 4.8.1
```

**Comment by LekoArts** [comment]
For Gatsby Cloud support please go here: https://www.gatsbyjs.com/support/
