### ISSUE TITLE
Make all tutorials use React 16

### ISSUE THREAD

**Issue by deadcoder0904** [gatsbyjs/gatsby#3497]
Right now there are a lot of useless `div`'s in many tutorials like [this one](https://www.gatsbyjs.org/tutorial/part-three/) so the new Fragment API `<></>` introduced in React 16 can take advantage of that. What do you think?

**Comment by KyleAMathews** [comment]
We're working on [Gatsby v2](https://github.com/gatsbyjs/gatsby/projects) actually as we speak which will include upgrading to React 16. Would love to discuss adding `<Fragment>` to tutorials then!
