### ISSUE TITLE
Remote images never deliver AVIF sources 

### ISSUE THREAD

**Issue by ascorbic** [gatsbyjs/gatsby#35019]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

`<picture>` tags generated by the new image-cdn feature include sources for AVIF and WebP by default. However because they list WebP first, the AVIF source will never be loaded. Sources are evaluated in the order they are listed, and every browser that supports AVIF also supports WebP. The standard sharp plugin always ensures that AVIF is listed before WebP if included.

### Reproduction Link

https://build-a7f6225e-5582-4606-9f25-b8a3d17f945f.gtsb.io/

### Steps to Reproduce

1. Load the linked site with the network tab open in a browser that supports AVIF such as the latest version of Chrome or Firefox

### Expected Result

The AVIF source is loaded

### Actual Result

The WebP source is loaded

### Environment

```shell
System:
    OS: macOS 11.6.4
    CPU: (8) arm64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.11.0 - /var/folders/k2/ffw3_41j7h17rzsmx25wcwl80000gn/T/yarn--1646218930294-0.06575311356425417/node
    Yarn: 1.22.17 - /var/folders/k2/ffw3_41j7h17rzsmx25wcwl80000gn/T/yarn--1646218930294-0.06575311356425417/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v16.11.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 98.0.4758.102
    Safari: 14.1.2
  npmPackages:
    gatsby: ^4.10.0-next.2 => 4.10.0-next.2
    gatsby-plugin-image: next => 2.10.0-next.2
    gatsby-plugin-sharp: next => 4.10.0-next.2
    gatsby-source-contentful: next => 7.8.0-next.2
    gatsby-source-filesystem: next => 4.10.0-next.2
    gatsby-source-wordpress: next => 6.10.0-next.2
    gatsby-transformer-sharp: next => 4.10.0-next.1
```

**Comment by wardpeet** [comment]
Thanks, fixed in attached PR :)
