### ISSUE TITLE
`gatsby@next` fails to build any site because page mode is unset

### ISSUE THREAD

**Issue by ascorbic** [gatsbyjs/gatsby#35015]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

The latest `gatsby@next` version fails to build because `_CFLAGS_.GATSBY_MAJOR` is unset. This means that the features added in Gatsby 4 are not enabled. This causes builds to fail, because when the page tree is generated it expects `page.mode` to be set. This will presumably be fixed when the next major is released (_ahem_), but in the meantime `gatsby@next` cannot be used. This is a problem for us because our repos use `gatsby@next` in CI.

Simple way to check: search [the published source](https://unpkg.com/gatsby@next/dist/redux/actions/public.js) for 
```
"" === `4`
```

### Reproduction Link

https://github.com/ascorbic/gatsby-next-build-error

### Steps to Reproduce

1. Run `gatsby build` in the repro, or any other site with `gatsby@next`. Setting `GATSBY_LOGGER=yurnalist` makes it easier to see the error.

### Expected Result

Site builds

### Actual Result

Build fails at the end of the build with the error:

```
success onPostBuild - 0.000s
error Cannot read properties of undefined (reading 'add')


  TypeError: Cannot read properties of undefined (reading 'add')

  - index.js:41
    [my-gatsby-site]/[gatsby-cli]/lib/reporter/loggers/yurnalist/index.js:41:36

  - Set.forEach

  - index.js:38 generatePageTreeToConsole
    [my-gatsby-site]/[gatsby-cli]/lib/reporter/loggers/yurnalist/index.js:38:11

  - index.js:247
    [my-gatsby-site]/[gatsby-cli]/lib/reporter/loggers/yurnalist/index.js:247:11

  - index.js:60 dispatch
    [my-gatsby-site]/[gatsby-cli]/lib/reporter/redux/index.js:60:5

  - redux.js:554 Object.renderPageTree
    [my-gatsby-site]/[redux]/lib/redux.js:554:12

  - reporter.js:369 Reporter._renderPageTree
    [my-gatsby-site]/[gatsby-cli]/lib/reporter/reporter.js:369:21

  - build.ts:465 build
    [my-gatsby-site]/[gatsby]/src/commands/build.ts:465:12

  - task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
```

### Environment

```shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /var/folders/2v/9fbywb7565dfmjmtljplshd80000gn/T/yarn--1646203058236-0.9315975782346246/node
    Yarn: 1.22.10 - /var/folders/2v/9fbywb7565dfmjmtljplshd80000gn/T/yarn--1646203058236-0.9315975782346246/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 98.0.4758.109
    Safari: 15.2
  npmPackages:
    gatsby: ^4.10.0-next.1 => 4.10.0-next.1
```

**Comment by wardpeet** [comment]
Republished :)  Thank you for letting us know

**Comment by ascorbic** [comment]
Thanks!

**Comment by DanielRiveraHQ** [comment]
Thank you for reporting this. Have you been able to find a workaround @ascorbic ?

**Comment by ascorbic** [comment]
@DanielRiveraHQ it was fixed in the next prerelease that Ward published
