### ISSUE TITLE
Issue in the gatsbyconf.com/jobs page

### ISSUE THREAD

**Issue by Jassi10000** [gatsbyjs/gatsby#35027]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

On visiting the page https://gatsbyconf.com/jobs , am not able to apply to any of the jobs, the *Apply Now* link doesn't has any of the links associated with it . Please check on this

### Reproduction Link

https://gatsbyconf.com/jobs

### Steps to Reproduce

1. Visit  https://gatsbyconf.com/jobs
2. Click on any of the jobs available there to apply
3. The  *Apply Now* doesn't work on any of them
...

### Expected Result

The *Apply Now * link should work for all the jobs present there 

### Actual Result

The *Apply Now * link is not working for all the jobs present there 

### Environment

```shell
none
```

### Config Flags

none

**Comment by LekoArts** [comment]
Thanks, fixed now!
