### ISSUE TITLE
Gatsby Plugin Image and Typescript: getImage returns IGatsbyImageData | undefined but getImage helper Function in GatsbyImage expects only IGatsbyImageData 

### ISSUE THREAD

**Issue by lautenschlager-dev** [gatsbyjs/gatsby#35072]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

The function getImage() returns IGatsbyImageData | undefined but GatsbyImageProps.image only accepts IGatsbyImageData. Typescript then complains "Type 'IGatsbyImageData | undefined' is not assignable to type 'IGatsbyImageData'.

### Reproduction Link

https://github.com/lautenschlager-dev/getimage-typescript

### Steps to Reproduce

1. npm install
2. see typescript error in VsCode

### Expected Result

Maybe GatsbyImageProps.image need to accept both types IGatsbyImageData | undefined

### Actual Result

GatsbyImageProps.image only accepts IGatsbyImageData

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.10.2 - /c/Python310/python
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.30)
  npmPackages:
    gatsby: ^4.9.2 => 4.9.2
    gatsby-plugin-image: ^2.9.0 => 2.9.0
    gatsby-plugin-sharp: ^4.9.0 => 4.9.0
    gatsby-source-filesystem: ^4.9.0 => 4.9.0
    gatsby-transformer-sharp: ^4.9.0 => 4.9.0
  npmGlobalPackages:
    gatsby-cli: 4.6.0
```

**Comment by LekoArts** [comment]
Hi!

Please see https://github.com/gatsbyjs/gatsby/discussions/31088
