### ISSUE TITLE
[gatsby-source-filesystem] bug when upgrading gatsby from 4.8.2 to 4.9.0+

### ISSUE THREAD

**Issue by klittlepage** [gatsbyjs/gatsby#35079]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

After upgrading from 4.8.2 to 4.9.0 (or any version thereafter) and running `gatsby develop` or `gatsby build` results in:

```
The path passed to gatsby-source-filesystem does not exist on your file system:
/site/.cache/compiled/src/assets/images
Please pick a path to an existing directory.
See docs here - https://www.gatsbyjs.org/packages/gatsby-source-filesystem/
```

The *original* (not cached) directory passed to `gatsby-source-filesystem` exists:

```
  {
    resolve: `gatsby-source-filesystem`,
    options: {
      name: `images`,
      path: `${__dirname}/src/assets/images`,
    },
  },
```

### Reproduction Link

https://github.com/klittlepage/gatsby-source-filesystem-bug

### Steps to Reproduce

Upgrade gatsby beyond `4.8.2`.

### Expected Result

The build/development session to succeed, as it did before.

### Actual Result

Both `gatsby build` and `gatsby develop` exit with an error code.

```
The path passed to gatsby-source-filesystem does not exist on your file system:
/site/.cache/compiled/src/assets/images
Please pick a path to an existing directory.
See docs here - https://www.gatsbyjs.org/packages/gatsby-source-filesystem/
```

### Environment

```shell
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.5.0 - /private/var/folders/fx/p2_4_3n90h5g164wqpmz7c7h0000gn/T/xfs-f8522be1/node
    Yarn: 3.1.1 - /private/var/folders/fx/p2_4_3n90h5g164wqpmz7c7h0000gn/T/xfs-f8522be1/yarn
    npm: 8.5.1 - /opt/homebrew/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 99.0.4844.51
    Firefox: 97.0.2
    Safari: 15.3
  npmPackages:
    gatsby: 4.9.2 => 4.9.2
    gatsby-plugin-google-gtag: ^4.9.0 => 4.9.0
    gatsby-plugin-image: ^2.9.0 => 2.9.0
    gatsby-plugin-layout: ^3.9.0 => 3.9.0
    gatsby-plugin-manifest: ^4.9.0 => 4.9.0
    gatsby-plugin-mdx: ^3.9.0 => 3.9.0
    gatsby-plugin-offline: ^5.9.0 => 5.9.0
    gatsby-plugin-react-svg: ^3.1.0 => 3.1.0
    gatsby-plugin-robots-txt: ^1.7.0 => 1.7.0
    gatsby-plugin-sharp: ^4.9.0 => 4.9.0
    gatsby-plugin-sitemap: ^5.9.0 => 5.9.0
    gatsby-plugin-typescript: ^4.9.0 => 4.9.0
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-remark-copy-linked-files: ^5.9.0 => 5.9.0
    gatsby-remark-images: ^6.9.0 => 6.9.0
    gatsby-source-filesystem: ^4.9.0 => 4.9.0
    gatsby-transformer-sharp: ^4.9.0 => 4.9.0
    gatsby-transformer-yaml: ^4.9.0 => 4.9.0
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by klittlepage** [comment]
Hi @LekoArts , I've isolated the issue. Prior to `4.9.0` `__dirname` returns a path to the gatsby project directory, i.e., `/path/to/site`. It now returns `/path/to/site/.cache/compiled`, breaking `gatsby-source-filesystem`, among other things.

**Comment by klittlepage** [comment]
I've isolated the issue—it occurs when using typescript and a typescript gatsby configuration `gatsby-config.ts`: [minimal reproduction](https://github.com/klittlepage/gatsby-source-filesystem-bug).

**Comment by LekoArts** [comment]
This is a known limitation :)
https://www.gatsbyjs.com/docs/how-to/custom-configuration/typescript/#__dirname

**Comment by klittlepage** [comment]
@LekoArts , the issue is that that from what I can tell gatsby-config.ts takes precedence over gatsby-config.js. Using a gatsby-config.js to load a gatsby-config.ts via ts-node was the standard way to use typescript for gatsby-* files prior, and this change breaks the build (in a confusing way) for anyone migrating to 4.9. Unless I’m missing something, the release notes say nothing about this—they focus on how to type the configuration. It was not obvious that gatsby-config.js was being ignored, and it’s now impossible for anyone who hits an issue with parcel to use ts-node.

**Comment by LekoArts** [comment]
@klittlepage Ok, gotcha! Your reproduction didn't show/mention this. I've put up https://github.com/gatsbyjs/gatsby/pull/35134 for folks using ts-node (we want to encourage you to migrate away from it)

**Comment by docforcedev** [comment]
> This is a known limitation :) https://www.gatsbyjs.com/docs/how-to/custom-configuration/typescript/#__dirname

@LekoArts Would it be possible to update this plugin readme to also reflect how it should be done if using `gatsby-config.ts`? https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-filesystem/README.md
