### ISSUE TITLE
`gatsby build` hangs on "Building static HTML for pages" when using React 18 RC 2

### ISSUE THREAD

**Issue by mwskwong** [gatsbyjs/gatsby#35083]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

As the title suggests, the build process will hang when reaching the "Building static HTML for pages" stage if React 18 RC 2 is used. 

Workaround: Falling back to React 18 RC 1

### Reproduction Link

https://github.com/mwskwong/react-18-rc-2-repo

### Steps to Reproduce

1. Create a Gastby project with any templates
2. Upgrade the React version to `18.0.0-rc.2`

### Expected Result

The build process will proceed and success.

### Actual Result

The build process hangs and never returns.

### Environment

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.10.2
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (99.0.1150.36)
  npmPackages:
    gatsby: ^4.9.2 => 4.9.2
```

**Comment by justinh00k** [comment]
I am having this same issue. Build works with Gatsby cloud but not locally.
