### ISSUE TITLE
Gatsby-source-wordpress: Cannot query field "wpGatsbyCompatibility" on type "Query"

### ISSUE THREAD

**Issue by Karol-Waliszewski** [gatsbyjs/gatsby#35157]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

After upgrade from gatsby 3 to gatsby 4 plugin stopped working. We updated plugin as well as Wordpress plugins in CMS.

Error we get: 
![image](https://user-images.githubusercontent.com/27155557/158829136-d5474b83-2e23-4db4-af68-a99987e7f020.png)

https://reactjs.org/docs/error-decoder.html/?invariant=31&args[]=AggregateError%3A%20GraphQL%20Document%20Validation%20failed%20with%206%20errors%3B%0A%20%20Error%200%3A%20GraphQLDocumentError%3A%20Cannot%20query%20field%20%22wpGatsbyCompatibility%22%20on%20type%20%22Query%22.%0A%20%20%20%20at%20%2FUsers%2Fkarolwaliszewski%2FDocuments%2FProgramming%2Findigital%2Fvictoriadom%2Fnode_modules%2Fgatsby-source-wordpress%2Fdist%2Fsteps%2Fcheck-plugin-requirements.js%3A5%3A3%0A%0AError%201%3A%20GraphQLDocumentError%3A%20Cannot%20query%20field%20%22isWpGatsby%22%20on%20type%20%22Query%22.%0A%20%20%20%20at%20%2FUsers%2Fkarolwaliszewski%2FDocuments%2FProgramming%2Findigital%2Fvictoriadom%2Fnode_modules%2Fgatsby-source-wordpress%2Fdist%2Fsteps%2Fcheck-plugin-requirements.js%3A2%3A3%0A%0AError%202%3A%20GraphQLDocumentError%3A%20Cannot%20query%20field%20%22generalSettings%22%20on%20type%20%22Query%22.%0A%20%20%20%20at%20%2FUsers%2Fkarolwaliszewski%2FDocuments%2FProgramming%2Findigital%2Fvictoriadom%2Fnode_modules%2Fgatsby-source-wordpress%2Fdist%2Fsteps%2Fcheck-plugin-requirements.js%3A2%3A3%0A%0AError%203%3A%20GraphQLDocumentError%3A%20Cannot%20query%20field%20%22wpGatsby%22%20on%20type%20%22Query%22.%0A%20%20%20%20at%20%2FUsers%2Fkarolwaliszewski%2FDocuments%2FProgramming%2Findigital%2Fvictoriadom%2Fnode_modules%2Fgatsby-source-wordpress%2Fdist%2Fsteps%2Fcheck-plugin-requirements.js%3A5%3A3%0A%0AError%204%3A%20GraphQLDocumentError%3A%20Cannot%20query%20field%20%22schemaMd5%22%20on%20type%20%22Query%22.%0A%20%20%20%20at%20%2FUsers%2Fkarolwaliszewski%2FDocuments%2FProgramming%2Findigital%2Fvictoriadom%2Fnode_modules%2Fgatsby-source-wordpress%2Fdist%2Fsteps%2Fingest-remote-schema%2Fdiff-schemas.js%3A2%3A3%0A%0AError%205%3A%20GraphQLDocumentError%3A%20Cannot%20query%20field%20%22generalSettings%22%20on%20type%20%22Query%22.%0A%20%20%20%20at%20%2FUsers%2Fkarolwaliszewski%2FDocuments%2FProgramming%2Findigital%2Fvictoriadom%2Fnode_modules%2Fgatsby-source-wordpress%2Fdist%2Fsteps%2Fingest-remote-schema%2Fdiff-schemas.js%3A5%3A3

### Reproduction Link

.

### Steps to Reproduce

1. Update gatsby and plugins from 3 to 4
2. Try to run a dev server or build

### Expected Result

Development starts

### Actual Result

Error

### Environment

```shell
"dependencies": {
    "@svgr/webpack": "^5.5.0",
    "@types/recompose": "^0.30.8",
    "axios": "^0.21.1",
    "babel-plugin-styled-components": "1.10.2",
    "formik": "^2.2.9",
    "gatsby": "^4.10.0",
    "gatsby-plugin-canonical-urls": "^4.10.0",
    "gatsby-plugin-eslint": "^4.0.2",
    "gatsby-plugin-google-analytics": "^4.10.0",
    "gatsby-plugin-google-tagmanager": "^4.10.0",
    "gatsby-plugin-graphql-codegen": "^3.0.0",
    "gatsby-plugin-hotjar": "^1.1.1",
    "gatsby-plugin-image": "^2.10.0",
    "gatsby-plugin-manifest": "^4.10.0",
    "gatsby-plugin-netlify": "^4.1.0",
    "gatsby-plugin-nprogress": "^4.10.0",
    "gatsby-plugin-offline": "^5.10.0",
    "gatsby-plugin-react-helmet": "^5.10.0",
    "gatsby-plugin-remove-trailing-slashes": "^4.10.0",
    "gatsby-plugin-robots-txt": "^1.6.14",
    "gatsby-plugin-sharp": "^4.10.0",
    "gatsby-plugin-sitemap": "^5.10.0",
    "gatsby-plugin-styled-components": "^5.10.0",
    "gatsby-plugin-svgr": "^3.0.0-beta.0",
    "gatsby-plugin-typescript": "^4.10.0",
    "gatsby-plugin-web-font-loader": "^1.0.4",
    "gatsby-source-filesystem": "^4.10.0",
    "gatsby-source-wordpress": "^6.10.0",
    "gatsby-theme-i18n": "^3.0.0",
    "gatsby-theme-i18n-react-i18next": "^3.0.0",
    "gatsby-transformer-sharp": "^4.10.0",
    "i18next": "^20.3.2",
    "i18next-browser-languagedetector": "^6.1.2",
    "jquery": "^3.6.0",
    "js-cookie": "^3.0.1",
    "polished": "^4.1.3",
    "react": "^17.0.1",
    "react-dom": "^17.0.2",
    "react-google-maps": "^9.4.5",
    "react-helmet": "^6.1.0",
    "react-i18next": "^11.11.1",
    "react-keep-alive": "^2.5.2",
    "react-lazyload": "^3.2.0",
    "react-loader-spinner": "^6.0.0-0",
    "react-medium-image-zoom": "^4.3.5",
    "react-resize-detector": "^6.7.4",
    "react-router-dom": "^5.2.0",
    "react-router-transition": "^2.1.0",
    "react-slider": "^1.3.1",
    "recompose": "^0.30.0",
    "slugify": "^1.6.0",
    "spritespin": "^4.1.0",
    "styled-components": "^5.3.3",
    "swiper": "^6.7.5",
    "ts-node": "^10.2.1",
    "typescript": "4.3.4",
    "yup": "^0.32.9"
  },
  "devDependencies": {
    "@types/jquery": "^3.5.6",
    "@types/react-dom": "^17.0.9",
    "@types/react-helmet": "^6.1.1",
    "@types/react-lazyload": "^3.1.1",
    "@types/react-router-dom": "^5.1.8",
    "@types/react-router-transition": "^2.1.1",
    "@types/react-slider": "^1.3.1",
    "@types/styled-components": "^5.1.10",
    "@types/yup": "^0.29.13",
    "@typescript-eslint/eslint-plugin": "^4.27.0",
    "eslint": "^7.28.0",
    "eslint-config-airbnb-typescript": "^12.3.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-prettier": "^3.4.0",
    "eslint-plugin-react": "^7.24.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "eslint-webpack-plugin": "^2.5.4",
    "prettier": "^2.3.1"
  },
```

**Comment by marvinjude** [comment]
Hi @Karol-Waliszewski,

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction](https://gatsby.dev/reproduction). This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction](https://gatsby.dev/reproduction) and we'll be able to take another look.

Thanks for using Gatsby! 💜
