### ISSUE TITLE
gatsby-source-contentful: Encountered an error trying to infer a GraphQL type for Content Types on new content creation with multiple Contentful spaces

### ISSUE THREAD

**Issue by EvanBancroft** [gatsbyjs/gatsby#35161]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

This is an error that started to appear after connecting a second Contentful account to our website. After doing so publishing any new piece of content will cause the builds to break and we are given the error listed below. 

I should also note that this is an issue I am seeing with another one of my sites the most recent version of the source plugin but I am not seeing it on older versions of the plugin. I just tested 7.1.0 and it worked fine.

Contentful source options in my `gatsby-config.js`
```
   {
      resolve: `gatsby-source-contentful`,
      options: {
        spaceId: process.env.SPACE_ID,
        accessToken: process.env.ACCESS_TOKEN,
        host: process.env.HOST,
      },
    },
   {
      resolve: `gatsby-source-contentful`,
      options: {
        spaceId: process.env.SECOND_SPACE_ID,
        accessToken: process.env.SECOND_ACCESS_TOKEN,
        useNameForId: false,
        host: process.env.SECOND_HOST,
      },
    },
```

### Reproduction Link

https://github.com/gatsbyjs/gatsby-starter-minimal

### Steps to Reproduce

1. Clean the Gatsby cache and run a new build.
2. Publish a new piece of content from one of your two Contentful spaces.
3. Build the site without clearing the cache.

### Expected Result

The site will build without issues.

### Actual Result

The build stalls/breaks with an error code similar to this one.
```

Missing onError handler for invocation 'building-schema', error was 'Invariant Violation: Encountered an error trying to infer a GraphQL type for: `updatedContentType___NODE`. There is no corresponding node with the `id` field matching: "7aXKmHrqeAQ9QaNeK2N3dH".'. Stacktrace was
 'Invariant Violation: Encountered an error trying to infer a GraphQL type for: `updatedContentType___NODE`. There is no corresponding node with the `id` field matching: "7aXKmHrqeAQ9QaNeK2N3dH".
    at invariant (/path/to/project/node_modules/invariant/invariant.js:40:15)
    at getFieldConfigFromFieldNameConvention (/path/to/project/node_modules/gatsby/src/schema/infer/add-inferred-fields.js:254:3)
    at getFieldConfig (/path/to/project/node_modules/gatsby/src/schema/infer/add-inferred-fields.js:143:19)
    at forEach (/path/to/project/node_modules/gatsby/src/schema/infer/add-inferred-fields.js:88:25)
    at Array.forEach (<anonymous>)
    at addInferredFieldsImpl (/path/to/project/node_modules/gatsby/src/schema/infer/add-inferred-fields.js:72:28)
    at addInferredFields (/path/to/project/node_modules/gatsby/src/schema/infer/add-inferred-fields.js:27:3)
    at addInferredType (/path/to/project/node_modules/gatsby/src/schema/infer/index.js:107:3)
    at map (/path/to/project/node_modules/gatsby/src/schema/infer/index.js:65:5)
    at Array.map (<anonymous>)
    at addInferredTypes (/path/to/project/node_modules/gatsby/src/schema/infer/index.js:64:23)
    at updateSchemaComposer (/path/to/project/node_modules/gatsby/src/schema/schema.js:130:9)
    at buildSchema (/path/to/project/node_modules/gatsby/src/schema/schema.js:64:3)
    at build (/path/to/project/node_modules/gatsby/src/schema/index.js:112:18)
    at buildSchema (/path/to/project/node_modules/gatsby/src/services/build-schema.ts:19:3)'

⠹ building schema
not finished building schema - 21.612s
```

### Environment

```shell
System:
    OS: macOS 11.6.3
    CPU: (8) arm64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    Yarn: 1.22.11 - /opt/homebrew/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 99.0.4844.51
    Firefox: 88.0
    Safari: 15.3
  npmPackages:
    gatsby: ^4.7.1 => 4.7.2
    gatsby-omni-font-loader: ^1.3.3 => 1.3.3
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5
    gatsby-plugin-catch-links: ^4.7.0 => 4.7.0
    gatsby-plugin-feed: ^4.7.0 => 4.7.0
    gatsby-plugin-gatsby-cloud: ^4.7.0 => 4.7.0
    gatsby-plugin-google-analytics: ^4.7.0 => 4.7.0
    gatsby-plugin-google-gtag: ^4.7.0 => 4.7.0
    gatsby-plugin-hotjar: ^1.1.1 => 1.1.1
    gatsby-plugin-image: ^2.7.0 => 2.7.0
    gatsby-plugin-jss: ^4.7.0 => 4.7.0
    gatsby-plugin-mailchimp: ^5.2.2 => 5.2.2
    gatsby-plugin-manifest: ^4.7.0 => 4.7.0
    gatsby-plugin-metricool: ^1.0.7 => 1.0.7
    gatsby-plugin-offline: ^5.7.0 => 5.7.0
    gatsby-plugin-preload-fonts: ^3.7.0 => 3.7.0
    gatsby-plugin-react-helmet: ^5.7.0 => 5.7.0
    gatsby-plugin-remote-images: ^3.3.0 => 3.3.0
    gatsby-plugin-robots-txt: ^1.7.0 => 1.7.0
    gatsby-plugin-sharp: ^4.7.0 => 4.7.0
    gatsby-plugin-sitemap: ^5.7.0 => 5.7.0
    gatsby-source-contentful: ^7.5.0-next.1 => 7.5.0
    gatsby-source-filesystem: ^4.7.0 => 4.7.0
    gatsby-source-vimeo-all: 0.0.18 => 0.0.18
    gatsby-transformer-sharp: ^4.7.0 => 4.7.0
  npmGlobalPackages:
    gatsby-cli: 4.9.0
```

**Comment by EvanBancroft** [comment]
This appears to be the same issue that was supposed to be resolved in [this PR.](https://github.com/gatsbyjs/gatsby/pull/35006) I am still seeing the error in `7.8.0`, but it seems that the maintainers are aware of this still being an issue so I'm closing this issue for now.

**Comment by Mangal5** [comment]
> ### Preliminary Checks
> * [x]  This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
> * [x]  This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions
> 
> ### Description
> This is an error that started to appear after connecting a second Contentful account to our website. After doing so publishing any new piece of content will cause the builds to break and we are given the error listed below.
> 
> I should also note that this is an issue I am seeing with another one of my sites the most recent version of the source plugin but I am not seeing it on older versions of the plugin. I just tested 7.1.0 and it worked fine.
> 
> Contentful source options in my `gatsby-config.js`
> 
> ```
>    {
>       resolve: `gatsby-source-contentful`,
>       options: {
>         spaceId: process.env.SPACE_ID,
>         accessToken: process.env.ACCESS_TOKEN,
>         host: process.env.HOST,
>       },
>     },
>    {
>       resolve: `gatsby-source-contentful`,
>       options: {
>         spaceId: process.env.SECOND_SPACE_ID,
>         accessToken: process.env.SECOND_ACCESS_TOKEN,
>         useNameForId: false,
>         host: process.env.SECOND_HOST,
>       },
>     },
> ```
> 
> ### Reproduction Link
> https://github.com/gatsbyjs/gatsby-starter-minimal
> 
> ### Steps to Reproduce
> 1. Clean the Gatsby cache and run a new build.
> 2. Publish a new piece of content from one of your two Contentful spaces.
> 3. Build the site without clearing the cache.
> 
> ### Expected Result
> The site will build without issues.
> 
> ### Actual Result
> The build stalls/breaks with an error code similar to this one.
> 
> ```
> 
> Missing onError handler for invocation 'building-schema', error was 'Invariant Violation: Encountered an error trying to infer a GraphQL type for: `updatedContentType___NODE`. There is no corresponding node with the `id` field matching: "7aXKmHrqeAQ9QaNeK2N3dH".'. Stacktrace was
>  'Invariant Violation: Encountered an error trying to infer a GraphQL type for: `updatedContentType___NODE`. There is no corresponding node with the `id` field matching: "7aXKmHrqeAQ9QaNeK2N3dH".
>     at invariant (/path/to/project/node_modules/invariant/invariant.js:40:15)
>     at getFieldConfigFromFieldNameConvention (/path/to/project/node_modules/gatsby/src/schema/infer/add-inferred-fields.js:254:3)
>     at getFieldConfig (/path/to/project/node_modules/gatsby/src/schema/infer/add-inferred-fields.js:143:19)
>     at forEach (/path/to/project/node_modules/gatsby/src/schema/infer/add-inferred-fields.js:88:25)
>     at Array.forEach (<anonymous>)
>     at addInferredFieldsImpl (/path/to/project/node_modules/gatsby/src/schema/infer/add-inferred-fields.js:72:28)
>     at addInferredFields (/path/to/project/node_modules/gatsby/src/schema/infer/add-inferred-fields.js:27:3)
>     at addInferredType (/path/to/project/node_modules/gatsby/src/schema/infer/index.js:107:3)
>     at map (/path/to/project/node_modules/gatsby/src/schema/infer/index.js:65:5)
>     at Array.map (<anonymous>)
>     at addInferredTypes (/path/to/project/node_modules/gatsby/src/schema/infer/index.js:64:23)
>     at updateSchemaComposer (/path/to/project/node_modules/gatsby/src/schema/schema.js:130:9)
>     at buildSchema (/path/to/project/node_modules/gatsby/src/schema/schema.js:64:3)
>     at build (/path/to/project/node_modules/gatsby/src/schema/index.js:112:18)
>     at buildSchema (/path/to/project/node_modules/gatsby/src/services/build-schema.ts:19:3)'
> 
> ⠹ building schema
> not finished building schema - 21.612s
> ```
> 
> ### Environment
> ```shell
> System:
>     OS: macOS 11.6.3
>     CPU: (8) arm64 Apple M1
>     Shell: 5.8 - /bin/zsh
>   Binaries:
>     Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
>     Yarn: 1.22.11 - /opt/homebrew/bin/yarn
>     npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
>   Languages:
>     Python: 2.7.16 - /usr/bin/python
>   Browsers:
>     Chrome: 99.0.4844.51
>     Firefox: 88.0
>     Safari: 15.3
>   npmPackages:
>     gatsby: ^4.7.1 => 4.7.2
>     gatsby-omni-font-loader: ^1.3.3 => 1.3.3
>     gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5
>     gatsby-plugin-catch-links: ^4.7.0 => 4.7.0
>     gatsby-plugin-feed: ^4.7.0 => 4.7.0
>     gatsby-plugin-gatsby-cloud: ^4.7.0 => 4.7.0
>     gatsby-plugin-google-analytics: ^4.7.0 => 4.7.0
>     gatsby-plugin-google-gtag: ^4.7.0 => 4.7.0
>     gatsby-plugin-hotjar: ^1.1.1 => 1.1.1
>     gatsby-plugin-image: ^2.7.0 => 2.7.0
>     gatsby-plugin-jss: ^4.7.0 => 4.7.0
>     gatsby-plugin-mailchimp: ^5.2.2 => 5.2.2
>     gatsby-plugin-manifest: ^4.7.0 => 4.7.0
>     gatsby-plugin-metricool: ^1.0.7 => 1.0.7
>     gatsby-plugin-offline: ^5.7.0 => 5.7.0
>     gatsby-plugin-preload-fonts: ^3.7.0 => 3.7.0
>     gatsby-plugin-react-helmet: ^5.7.0 => 5.7.0
>     gatsby-plugin-remote-images: ^3.3.0 => 3.3.0
>     gatsby-plugin-robots-txt: ^1.7.0 => 1.7.0
>     gatsby-plugin-sharp: ^4.7.0 => 4.7.0
>     gatsby-plugin-sitemap: ^5.7.0 => 5.7.0
>     gatsby-source-contentful: ^7.5.0-next.1 => 7.5.0
>     gatsby-source-filesystem: ^4.7.0 => 4.7.0
>     gatsby-source-vimeo-all: 0.0.18 => 0.0.18
>     gatsby-transformer-sharp: ^4.7.0 => 4.7.0
>   npmGlobalPackages:
>     gatsby-cli: 4.9.0
> ```
> 
> ### Config Flags
> _No response_

The issue is being addressed. So, for now, you can use version 7.4.
