### ISSUE TITLE
Command failed with exit code 1: git clone

### ISSUE THREAD

**Issue by benackles** [gatsbyjs/gatsby#35188]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

```
$ gatsby new demo-starter https://github.com/gatsbyjs/gatsby-starter-landing-page 
info Creating new site from git:
https://github.com/gatsbyjs/gatsby-starter-landing-page.git

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools
 ERROR 

Command failed with exit code 1: git clone
https://github.com/gatsbyjs/gatsby-starter-landing-page.git demo-starter
--recursive --depth=1



  Error: Command failed with exit code 1: git clone https://github.com/gatsbyjs/
  gatsby-starter-landing-page.git demo-starter --recursive --depth=1
  
  - error.js:60 makeError
    [lib]/[gatsby-cli]/[execa]/lib/error.js:60:11
  
  - index.js:118 handlePromise
    [lib]/[gatsby-cli]/[execa]/index.js:118:26
  
  - task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
  
  - init-starter.js:197 clone
    [lib]/[gatsby-cli]/lib/init-starter.js:197:3
  
  - init-starter.js:343 initStarter
    [lib]/[gatsby-cli]/lib/init-starter.js:343:5
  
  - create-cli.js:460 
    `[lib]/[gatsby-cli]/lib/create-cli.js:460:9`
```

### Reproduction Link

https://github.com/gatsbyjs/gatsby-starter-landing-page

### Steps to Reproduce

1. Install Gatsby CLI version: 4.10.1
2. Generate new site with starter using ```gatsby new demo-starter https://github.com/gatsbyjs/gatsby-starter-landing-page```
3. Evaluate error...

### Expected Result

A local instance of a gatsby site should be created in the directory ```demo-starter```.

### Actual Result

Getting error ```Command failed with exit code 1: git clone```

### Environment

```shell
System:
    OS: macOS 12.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 99.0.4844.74
    Safari: 15.1
  npmGlobalPackages:
    gatsby-cli: 4.10.1
```
```


### Config Flags

_No response_

**Comment by tyhopp** [comment]
Hi @benackles, I wasn't able to reproduce this. Looking at the error I suspect macOS may have had an update and you need to re-install the Xcode CLI tools to get git working again. [Here's a good thread on the topic](https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a).
