### ISSUE TITLE
Gatsby DEV works. Gatsby BUILD fails. Cannot access props in MDX file.

### ISSUE THREAD

**Issue by matthewhoth** [gatsbyjs/gatsby#35189]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I'm going insane trying to get a single line of anything from passed from props to render.

If nothing is passed or needed, then the MDX render outs. If props are passed and tried to be used, failure.

Unless in DEV.. then it works! Why would it work in DEV but not on BUILD?

Again, running [Gatsby Dev] works, and the MDX file renders out and can use all props passed to it. Any attempt to [Gatsby Build] fails saying that it can't read undefined.

I've tried wrapping the render in a MDX provider, in a conditional statement that checks for the specific props first, but nothing works. Gatsby Build pretends like there are no props being passed at all.

### Reproduction Link

https://github.com/mcnaveen/gatsby-mdx-starter-blog

### Steps to Reproduce

1. Pass props to MDX renderer ( EX: post={post} )
2. Attempt to access that those props in the MDX file 
(EX: <div>{post.frontmatter.title}</div>)
3. Fails on build.
...

### Expected Result

The props to be passed and accessible on build. 

And/or a more helpful error response than 

```Error in function MDXContent (eval at _construct in ./node_modules/@babel/runtime/helpers/construct.js), <anonymous>:
```

### Actual Result

Errors out on build. 

### Environment

```shell
System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Firefox: 96.0.3
    Safari: 15.2
  npmPackages:
    gatsby: ^4.10.1 => 4.10.1
    gatsby-plugin-feed-mdx: ^1.1.0 => 1.1.0
    gatsby-plugin-html-attributes: ^1.0.5 => 1.0.5
    gatsby-plugin-image: ^2.10.0 => 2.10.0
    gatsby-plugin-manifest: ^4.10.1 => 4.10.1
    gatsby-plugin-mdx: ^3.10.1 => 3.10.1
    gatsby-plugin-offline: ^5.10.1 => 5.10.1
    gatsby-plugin-preconnect: ^1.3.0 => 1.3.0
    gatsby-plugin-react-helmet-async: ^1.2.1 => 1.2.1
    gatsby-plugin-sharp: ^4.10.1 => 4.10.1
    gatsby-plugin-sitemap: ^5.10.1 => 5.10.1
    gatsby-remark-images: ^6.10.1 => 6.10.1
    gatsby-source-filesystem: ^4.10.0 => 4.10.0
  npmGlobalPackages:
    gatsby-cli: 2.12.91
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by matthewhoth** [comment]
Hey Leko, guess I misunderstood that page. I thought "Create a new Gatsby site with a starter" meant any starter. 

Data from the query wasn't reaching the component in time returning undefined. Putting in a ```if (!data) return X;``` check worked great.

**Comment by LekoArts** [comment]
Great! Thanks for clarifying that 👍
