### ISSUE TITLE
Vulnerable Package Dependency: minimatch

### ISSUE THREAD

**Issue by pamo** [gatsbyjs/gatsby#352]
Ran [snyk](https://snyk.io/features) on my blog and found a vulnerable dependency in Gatsby.

[Regular Expression Denial of Service](https://snyk.io/vuln/npm:minimatch:20160620)

**Snyk Details**

> Introduced through: likescoffee@pamo/pamo.github.io#384dbb3717fb6bf07c2f693dc5b0ad8eac19893a › gatsby@0.11.7 › postcss-import@8.1.2 › pkg-resolve@0.1.14 › jspm@0.17.0-beta.22 › jspm-github@0.14.9 › rimraf@2.3.4 › glob@4.5.3 › minimatch@2.0.10

**Comment by pamo** [comment]
Seems like it would be on the contributors of postcss-import to update 😞

**Comment by KyleAMathews** [comment]
Hey @pamo — thanks for raising this issue. This *shouldn't* be a problem though for your blog or Gatsby sites in general as minimatch code is only run by Gatsby while developing so safely protected from any malicious actors. I don't recommend exposing a Gatsby development server to the public generally speaking. This is one of the great things about static sites is that they're just files, so not an attack vector.

And yes — postcss-import would need to apply the update for this.
