### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'string')

### ISSUE THREAD

**Issue by mluce194** [gatsbyjs/gatsby#35222]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When I type in my terminal gatsby develop, I get the following error:
`TypeError: Cannot read properties of undefined (reading 'string')
    at Object.<anonymous> (/Users/marie-luce/Documents/projets/gatsby-contentful gatsby contentful/node_modules/gatsby/dist/isomorphic/html.js:15:37)
    at t (webpack/bootstrap 32976bbda241c65385a4:9:1)
    at Object.<anonymous> (webpack/bootstrap 32976bbda241c65385a4:33:1)
    at Object.<anonymous> (webpack/bootstrap 32976bbda241c65385a4:36:1)
    at t (webpack/bootstrap 32976bbda241c65385a4:9:1)
    at webpack/bootstrap 32976bbda241c65385a4:19:1
    at webpack/bootstrap 32976bbda241c65385a4:22:1
    at Script.runInContext (node:vm:139:12)
    at /Users/marie-luce/Documents/projets/gatsby-contentful gatsby contentful/node_modules/gatsby/node_modules/webpack-require/lib/webpackRequire.js:87:14
    at /Users/marie-luce/Documents/projets/gatsby-contentful gatsby contentful/node_modules/gatsby/dist/utils/develop.js:99:18`

### Reproduction Link

https://github.com/mluce194/contentful-lawyer

### Steps to Reproduce

1.Do npm run dev or gatsby develop

### Expected Result

The development session should start

### Actual Result

The development session does not start and I get this error: 
`TypeError: Cannot read properties of undefined (reading 'string')
    at Object.<anonymous> (/Users/marie-luce/Documents/projets/gatsby-contentful gatsby contentful/node_modules/gatsby/dist/isomorphic/html.js:15:37)
    at t (webpack/bootstrap 32976bbda241c65385a4:9:1)
    at Object.<anonymous> (webpack/bootstrap 32976bbda241c65385a4:33:1)
    at Object.<anonymous> (webpack/bootstrap 32976bbda241c65385a4:36:1)
    at t (webpack/bootstrap 32976bbda241c65385a4:9:1)
    at webpack/bootstrap 32976bbda241c65385a4:19:1
    at webpack/bootstrap 32976bbda241c65385a4:22:1
    at Script.runInContext (node:vm:139:12)
    at /Users/marie-luce/Documents/projets/gatsby-contentful gatsby contentful/node_modules/gatsby/node_modules/webpack-require/lib/webpackRequire.js:87:14
    at /Users/marie-luce/Documents/projets/gatsby-contentful gatsby contentful/node_modules/gatsby/dist/utils/develop.js:99:18`

### Environment

```shell
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 17.4.0 - ~/.nvm/versions/node/v17.4.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v17.4.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 92.0.4515.159
    Firefox: 98.0.1
    Safari: 14.1.2
  npmPackages:
    gatsby: ^0.7.7 => 0.7.7
    gatsby-background-image: ^1.6.0 => 1.6.0
    gatsby-plugin-image: ^0.7.2 => 0.7.2
    gatsby-plugin-postcss: ^5.6.0 => 5.10.0
    gatsby-plugin-react-helmet: ^3.10.0 => 3.10.0
    gatsby-plugin-sharp: ^2.14.4 => 2.14.4
    gatsby-plugin-styled-components: ^5.6.0 => 5.10.0
    gatsby-source-contentful: ^4.6.4 => 4.6.4
    gatsby-transformer-remark: ^5.0.0 => 5.10.2
    gatsby-transformer-sharp: ^2.12.1 => 2.12.1
  npmGlobalPackages:
    gatsby-cli: 4.10.2
```

**Comment by pieh** [comment]
Hi @mluce194

The gatsby version used in reported project is `0.7.7` which was released over 6 years ago and is unsupported for quite some time ( see https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/ for our version support ).

Please migrate to newer Gatsby version
