### ISSUE TITLE
Property 'to' does not exist on type gatsby-link, Typescript

### ISSUE THREAD

**Issue by Nikki1993** [gatsbyjs/gatsby#3525]
## Description

Using Typescript with Gatsby, get an error on Link component file:
```
severity: 'Error'
message: 'Property 'to' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<GatsbyLink> & Readonly<{ children?: ReactNode; }> ...'.'
source: 'ts'
```

### Environment

Gatsby version: 1.9.153
Node.js version: 9.4.0
Operating System: Solus (Linux)

### File contents (if changed):

`gatsby-config.js`: 

```
module.exports = {
  siteMetadata: {
    title: 'MyAwesomeTitle',
  },
  plugins: ['gatsby-plugin-react-helmet', 'gatsby-plugin-typescript'],
};
```

`package.json`: 
```
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Nick",
  "dependencies": {
    "gatsby": "^1.9.153",
    "gatsby-link": "^1.6.34",
    "gatsby-plugin-react-helmet": "^2.0.3",
    "gatsby-plugin-typescript": "^1.4.12",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-helmet": "^5.2.0",
    "styled-components": "^2.4.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "main": "n/a",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --trailing-comma es5 --no-semi --single-quote --write \"src/**/*.js\"",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "@types/react": "^16.0.34",
    "@types/react-helmet": "^5.0.3",
    "eslint": "^4.15.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.5.1",
    "prettier": "^1.10.2",
    "tslint-react": "^3.4.0"
  }
}
```
`gatsby-node.js`: **not changed**
`gatsby-browser.js`: **not changed**
`gatsby-ssr.js`: **not changed**

### Actual result

TSLint gives an error 
`'Property 'to' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<GatsbyLink> & Readonly<{ children?: ReactNode; }> ...'.'`

### Expected behavior

Property 'to' should exist on Link component.

### Steps to reproduce

1\. Instal typescript and gatsby typescript plugin

2\. Import Link component in any file `import Link from 'gatsby-link`

3\. Use 'to' property on link  `<Link to="/">Go back to the homepage</Link>`

4\. Get an error from tslint (in my case I used VSCode) about 'to' property

**Comment by KyleAMathews** [comment]
Could you check out the typescript definition here and see if you can fix this? https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-link/index.d.ts

**Comment by Nikki1993** [comment]
@KyleAMathews I made the PR here https://github.com/gatsbyjs/gatsby/pull/3552 

Gotta confess, the first PR ever and I am not even that skilled in TS so apologies for any mishaps.

I ran through contribution documentation and it seems some tests didn't pass but all of them seem to be unrelated to my changes (as I only modified the definitions file and nothing else).

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
