### ISSUE TITLE
Implement a Navigation Lifecycle API

### ISSUE THREAD

**Issue by peduarte** [gatsbyjs/gatsby#3528]
Here's a draft proposal to implement a Navigation Lifecycle API.

The available events would be:
- `onPageLoadStarted` - emitted as soon as a new page is requested
- `onPageLoadEnded` - emitted when the new page has been loaded (should include response status code?)
- `onPageLoadDelayed` - emitted when the page load is delayed. This raises another question: **how do we define the delay timeout?** Should this be configurable by the user (perhaps via `gatsby-config.js`?

For more context: https://github.com/gatsbyjs/gatsby/issues/3368

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
