### ISSUE TITLE
Language format for the date in GraphQL

### ISSUE THREAD

**Issue by MaralS** [gatsbyjs/gatsby#3529]
## Description
For a client, I'm using this amazing framework to build a fast web app. However, I'm beginning with GraphQL. I noticed that the date is formatted to display months in English. I wanted to know which parameters is necessary to display the date in french.

### Environment

Gatsby version: 1.1.27
Node.js version: 8.9.3
Operating System: OS X El Capitan 10.11.6

### File contents (if changed):

`gatsby-node.js`: 

const path = require('path');

exports.createPages = ({ boundActionCreators, graphql }) => {
    const { createPage } = boundActionCreators;

    const blogPostTemplate = path.resolve(`src/templates/blog-post.js`);

    return graphql(`{
    allMarkdownRemark(
      sort: { order: DESC, fields: [frontmatter___date] }
      limit: 1000
    ) {
      edges {
        node {
          excerpt(pruneLength: 250)
          html
          id
          frontmatter {
            date
            path
            title
          
          }
        }
      }
    }
  }`)
        .then(result => {
            if (result.errors) {
                return Promise.reject(result.errors);
            }

            result.data.allMarkdownRemark.edges
                .forEach(({ node }) => {
                    createPage({
                        path: node.frontmatter.path,
                        component: blogPostTemplate,
                        context: {} // additional data can be passed via context
                    });
                });
        });
}

**GraphQL Query :** 

export const pageQuery = graphql`

  query BlogPostByPath($path: String!) {
    markdownRemark(frontmatter: { path: { eq: $path } }) {
      html
      frontmatter {
        date(formatString: "DD/MM/YYYY")
        path
        title
        
        image{
          childImageSharp{
            sizes(maxWidth: 1000, quality: 100, cropFocus: CENTER, toFormat: JPG) {
                ...GatsbyImageSharpSizes
            }
            responsiveSizes(quality: 70){
              src
              srcSet
            }
          }
        }
      }
    }
  }
`;
### Actual result
I just have the month date like DD/MM/YYYY with numbers like 12/05/2017.

### Expected behavior
I wanted to show the date like : 12 mai 2017 

Thank you in advance for your help,

kind regards,

Maral.

**Comment by LeKoArts** [comment]
„date“ is what you write in your frontmatter. You should stick to this format and rather use something like date-fns in your component:
https://date-fns.org/docs/format

You can then format your property with date-fns.
Example:

https://github.com/LeKoArts/gatsby-starter-portfolio-emma/blob/master/src/templates/project.jsx#L16

**Comment by KyleAMathews** [comment]
The GraphQL date field takes an optional `locale` argument for modifying how the date is formatted https://github.com/gatsbyjs/gatsby/pull/2652

Good luck with the client site!

**Comment by derozan10** [comment]
Is it possible to show how to get this working on my example? I'm trying to sort on the "datumString"which has a format like "01-12-2018" (first of december, 2018).

```
{
  allThirdPartyClubwedstrijden(
    sort: {fields: datumString, order: ASC}
    filter: {
      uitslag: {eq: ""}
      datumString: {ne: null}
    }
    limit: 5
  ){
    edges {
      node {
        datumString
        tTNaam
        tUNaam
        uitslag
        beginTijd
      }
    }
  }
}
```
