### ISSUE TITLE
Need to change the method to create project

### ISSUE THREAD

**Issue by StanLepunK** [gatsbyjs/gatsby#35315]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

To create the project for `https://www.gatsbyjs.com/tutorial/authentication-tutorial/` I think it's better to use now

`npx gatsby new gatsby-auth gatsby-starter-hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world`
instead
`gatsby new gatsby-auth gatsbyjs/gatsby-starter-hello-world`  because in my case on OSX the my github account is asked, then my password and a the end that's failed because my console return this method is outdated.

### Steps to Resolve this Issue

nothing is necessary to be write here !

**Comment by LekoArts** [comment]
Hi!

The tutorial mentions:

> You should have already configured your environment to be able to use the gatsby-cli. A good starting point is the [main tutorial](https://www.gatsbyjs.com/tutorial).

It sounds like you didn't use the latest version of `gatsby-cli` or when you set it up something went wrong. The proposed solution you gave will also not work, see the README (https://www.npmjs.com/package/gatsby-cli) for exact information on the `gatsby new` usage.

In the future if you're having problems though you can also use `git clone` and `npm install` to set up the project.
