### ISSUE TITLE
Gatsby 4.11.1 Unable to build

### ISSUE THREAD

**Issue by ezrover** [gatsbyjs/gatsby#35321]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

error [ThrowableDiagnostic [Error]: The plugin "@parcel/reporter-dev-server" is not compatible with the current version of Parcel. Requires "^2.4.1" but the current version is "2.4.0".] {
  diagnostics: [
    {
      message: 'The plugin "@parcel/reporter-dev-server" is not compatible with the current version of Parcel. Requires "^2.4.1" but the current version is "2.4.0".',
      origin: '@parcel/core',
      codeFrames: [Array]
    }
  ]
}

### Reproduction Link

private

### Steps to Reproduce

npm run build fails after upgrading to 4.11.1

  "dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@babel/core": "^7.17.5",
    "@material-ui/core": "^4.12.3",
    "@material-ui/icons": "^4.11.2",
    "@material-ui/styles": "^4.11.4",
    "@popperjs/core": "^2.11.2",
    "@reach/router": "^1.3.4",
    "@reach/skip-nav": "^0.16.0",
    "@reduxjs/toolkit": "^1.8.0",
    "@stripe/react-stripe-js": "^1.7.0",
    "@stripe/stripe-js": "^1.23.0",
    "@styled-system/prop-types": "^5.1.5",
    "@vimeo/player": "^2.16.4",
    "acorn": "^8.7.0",
    "antd": "^4.18.9",
    "axios": "^0.26.0",
    "babel-plugin-module-resolver": "^4.1.0",
    "babel-plugin-styled-components": "^2.0.6",
    "babel-preset-gatsby": "^2.8.2",
    "body-scroll-lock": "^3.1.5",
    "classnames": "^2.3.1",
    "core-js": "^3.21.1",
    "country-state-city": "^3.0.1",
    "css-loader": "^6.6.0",
    "file-loader": "^6.2.0",
    "fontfaceobserver": "^2.1.0",
    "form-serialize": "^0.7.2",
    "framer-motion": "^6.2.8",
    "gatsby": "^4.11.1",
    "gatsby-plugin-catch-links": "^4.11.0",
    "gatsby-plugin-client-side-redirect": "^1.1.0",
    "gatsby-plugin-google-tagmanager": "^4.11.1",
    "gatsby-plugin-image": "^2.11.1",
    "gatsby-plugin-manifest": "^4.11.1",
    "gatsby-plugin-material-ui": "^4.1.0",
    "gatsby-plugin-react-helmet": "^5.11.0",
    "gatsby-plugin-remove-serviceworker": "^1.0.0",
    "gatsby-plugin-robots-txt": "^1.7.0",
    "gatsby-plugin-s3": "^0.3.8",
    "gatsby-plugin-sass": "^5.11.1",
    "gatsby-plugin-sharp": "^4.11.1",
    "gatsby-plugin-sitemap": "^5.11.1",
    "gatsby-plugin-styled-components": "^5.10.0",
    "gatsby-source-drupal": "^5.11.1",
    "gatsby-source-filesystem": "^4.11.1",
    "gatsby-transformer-sharp": "^4.11.0",
    "gsap": "^3.10.2",
    "i18next": "^21.6.14",
    "i18next-browser-languagedetector": "^6.1.4",
    "jquery": "^3.6.0",
    "js-cookie": "^3.0.1",
    "js-video-url-parser": "^0.5.1",
    "jwt-decode": "^3.1.2",
    "load-script": "^2.0.0",
    "lodash": "^4.17.21",
    "lodash.map": "^4.6.0",
    "moment": "^2.29.1",
    "normalize-wheel": "^1.0.1",
    "object-hash": "^3.0.0",
    "pannellum-react": "^1.2.4",
    "prop-types": "^15.8.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-helmet": "^6.1.0",
    "react-hook-form": "^6.1.2",
    "react-html-parser": "^2.0.2",
    "react-i18next": "^11.7.2",
    "react-load-script": "0.0.6",
    "react-loader-spinner": "^3.1.5",
    "react-number-format": "^4.9.1",
    "react-plaid-link": "^3.3.0",
    "react-popper": "^2.2.5",
    "react-redux": "^7.2.6",
    "react-script-hook": "^1.6.0",
    "react-scroll": "^1.8.6",
    "react-scroll-parallax": "^3.0.5",
    "react-select": "^5.2.2",
    "react-sequence-animator": "^2.3.0",
    "react-show-more": "^2.0.0",
    "react-slick": "^0.28.1",
    "react-smooth-collapse": "^2.1.1",
    "react-transition-group": "^4.4.2",
    "redux": "^4.1.2",
    "redux-thunk": "^2.4.1",
    "resize-observer-polyfill": "^1.5.1",
    "rodal": "^1.8.3",
    "slick-carousel": "^1.8.1",
    "snifferjs": "^4.1.0",
    "style-loader": "^3.3.1",
    "styled-components": "^5.3.5",
    "styled-system": "^5.1.5",
    "three": "^0.139.2",
    "sass": "^1.49.10",
    "use-media": "^1.4.0"
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.17.0",
    "@testing-library/react": "^12.1.3",
    "@typescript-eslint/eslint-plugin": "^5.17.0",
    "@wojtekmaj/enzyme-adapter-react-17": "^0.6.7",
    "a11y-sitechecker": "^6.0.1",
    "babel-jest": "^27.5.1",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.6",
    "enzyme-to-json": "^3.6.2",
    "eslint": "^8.12.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-prettier": "^8.5.0",
    "eslint-import-resolver-babel-module": "^5.3.1",
    "eslint-nibble": "^8.0.1",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "^7.29.4",
    "eslint-plugin-react-hooks": "^4.4.0",
    "finalhandler": "^1.2.0",
    "gatsby-cli": "^4.11.1",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^27.5.1",
    "jest-image-snapshot": "^4.5.1",
    "jest-junit": "^13.0.0",
    "jest-styled-components": "^7.0.8",
    "prettier": "^2.6.1",
    "react-test-renderer": "^16.14.0",
    "sharp": "^0.30.3",
    "stylelint": "^14.6.1",
    "stylelint-config-recommended": "^7.0.0",
    "stylelint-config-standard-scss": "^3.0.0",
    "stylelint-config-styled-components": "^0.1.1",
    "stylelint-processor-styled-components": "^1.10.0",
    "typescript": "^4.6.3",
    "yaml-jest": "^1.2.0"
  },

### Expected Result

Should build without errors

### Actual Result

> node --max-old-space-size=8192 ./node_modules/.bin/gatsby build

error [ThrowableDiagnostic [Error]: The plugin "@parcel/reporter-dev-server" is not compatible with the current version of Parcel. Requires "^2.4.1" but the current version is "2.4.0".] {
  diagnostics: [
    {
      message: 'The plugin "@parcel/reporter-dev-server" is not compatible with the current version of Parcel. Requires "^2.4.1" but the current version is "2.4.0".',
      origin: '@parcel/core',
      codeFrames: [Array]
    }
  ]
}
error [ThrowableDiagnostic [Error]: The plugin "@parcel/reporter-dev-server" is not compatible with the current version of Parcel. Requires "^2.4.1" but the current version is "2.4.0".] {
  diagnostics: [
    {
      message: 'The plugin "@parcel/reporter-dev-server" is not compatible with the current version of Parcel. Requires "^2.4.1" but the current version is "2.4.0".',
      origin: '@parcel/core',
      codeFrames: [Array]
    }
  ]
}
error [ThrowableDiagnostic [Error]: The plugin "@parcel/reporter-dev-server" is not compatible with the current version of Parcel. Requires "^2.4.1" but the current version is "2.4.0".] {
  diagnostics: [
    {
      message: 'The plugin "@parcel/reporter-dev-server" is not compatible with the current version of Parcel. Requires "^2.4.1" but the current version is "2.4.0".',
      origin: '@parcel/core',
      codeFrames: [Array]
    }
  ]
}
error Failed to compile Gatsby files (@parcel/core):                                                                                      

The plugin "@parcel/bundler-default" is not compatible with the current version of Parcel. Requires "^2.4.1" but the current version is "2.4.0".. 

### Environment

```shell
System:
    OS: macOS 11.6.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.8.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 99.0.4844.84
    Safari: 15.3
  npmPackages:
    gatsby: ^4.11.1 => 4.11.1
    gatsby-cli: ^4.11.1 => 4.11.1
    gatsby-plugin-catch-links: ^4.11.0 => 4.11.0
    gatsby-plugin-client-side-redirect: ^1.1.0 => 1.1.0
    gatsby-plugin-google-tagmanager: ^4.11.1 => 4.11.1
    gatsby-plugin-image: ^2.11.1 => 2.11.1
    gatsby-plugin-manifest: ^4.11.1 => 4.11.1
    gatsby-plugin-material-ui: ^4.1.0 => 4.1.0
    gatsby-plugin-react-helmet: ^5.11.0 => 5.11.0
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-robots-txt: ^1.7.0 => 1.7.0
    gatsby-plugin-s3: ^0.3.8 => 0.3.8
    gatsby-plugin-sass: ^5.11.1 => 5.11.1
    gatsby-plugin-sharp: ^4.11.1 => 4.11.1
    gatsby-plugin-sitemap: ^5.11.1 => 5.11.1
    gatsby-plugin-styled-components: ^5.10.0 => 5.10.0
    gatsby-source-drupal: ^5.11.1 => 5.11.1
    gatsby-source-filesystem: ^4.11.1 => 4.11.1
    gatsby-transformer-sharp: ^4.11.0 => 4.11.0
```

**Comment by marvinjude** [comment]
Hi @ezrover, 

This should go away if you delete your lock file and install dependencies
