### ISSUE TITLE
Bakers links are switched

### ISSUE THREAD

**Issue by hackhat** [gatsbyjs/gatsby#3532]
Bakers links are switched, see image. Click on one and will go to the other. Maybe baker index is updated based on the value donated? Doesn't look like is doing that, but you could double check. Putting urls to the profile directly maybe is better and easier to maintain.

![image](https://user-images.githubusercontent.com/11173732/34946782-142f994e-fa00-11e7-8d00-9df9fe30b23a.png)

**Comment by KyleAMathews** [comment]
Thanks for finding this! Is this something we can fix? Or if not, could you alert opencollective to the problem?

**Comment by hackhat** [comment]
I guess you will need to replace the links of the images in the git repo?

**Comment by peduarte** [comment]
This works fine for me...

Checked against README source code and the link's href matches the images source. 

Clicking on each avatar links to the correct backer.

**Comment by KyleAMathews** [comment]
Yeah, clicking on Dan goes to his page as well. Perhaps it was a temporary glitch on their part. Thanks for reporting @hackhat!
