### ISSUE TITLE
[gatsby-source-wordpress] html: useGatsyImage fails on build

### ISSUE THREAD

**Issue by Haldaug** [gatsbyjs/gatsby#35330]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I have a big wordpress site with over 3000 posts and I've been using gatsby for my front end to big success. Lately, though, my builds have started failing. During build, when gatsby-source-wordpress fetches MediaItems, I get this error message after around 1400 mediaItems have been downloaded:

```
 TypeError: Cannot read properties of undefined (reading 'attribs')
  
  - process-node.js:317 
    [site]/[gatsby-source-wordpress]/src/steps/source-nodes/create-nodes/process-
    node.js:317:28
  
  - Array.filter
  
  - process-node.js:317 getCheerioElementsFromMatches
    [site]/[gatsby-source-wordpress]/src/steps/source-nodes/create-nodes/process-
    node.js:317:28
```

If I set the option `html: {useGatsbyImage: false}` to false this problem does not occur.

I suspect some of the inline images some of my over 3000 posts have some sort of malformed <img>-tag that trips up the parser in process-node.js. The problem is that the error message gives no indication to in what post this parser error occurs. 

### Reproduction Link

---

### Steps to Reproduce

1. Create a wordpress post with a malformed image tag, for example an alt-attribute containing <sub> elements
2. Enable html: UseGatsbyImage in gatsby-source-wordpress
3. Run gatsby build
...

### Expected Result

I expect my build to complete, even though some images can't be parsed.

### Actual Result

The build encounters an error and fails to complete.

### Environment

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  npmPackages:
    gatsby: ^4.11.0 => 4.11.1 
    gatsby-plugin-algolia: ^0.26.0 => 0.26.0 
    gatsby-plugin-exclude: ^1.0.2 => 1.0.2 
    gatsby-plugin-feed: ^4.0.0 => 4.11.1 
    gatsby-plugin-gatsby-cloud: ^4.0.0 => 4.11.1 
    gatsby-plugin-google-gtag: ^4.0.0 => 4.11.0 
    gatsby-plugin-image: ^2.10.1 => 2.11.1 
    gatsby-plugin-manifest: ^4.0.0 => 4.11.1 
    gatsby-plugin-no-sourcemaps: ^4.0.0 => 4.11.0 
    gatsby-plugin-postcss: ^5.0.0 => 5.11.0 
    gatsby-plugin-react-helmet: ^5.0.0 => 5.11.0 
    gatsby-plugin-react-svg: ^3.1.0 => 3.1.0 
    gatsby-plugin-sharp: ^4.10.2 => 4.11.1 
    gatsby-plugin-sitemap: ^5.0.0 => 5.11.1 
    gatsby-source-filesystem: ^4.0.0 => 4.11.1 
    gatsby-source-wordpress: ^6.10.2 => 6.11.1 
    gatsby-transformer-sharp: ^4.10.0 => 4.11.0 
  npmGlobalPackages:
    gatsby-cli: 4.11.1
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by Haldaug** [comment]
I think the problem was that I had a function in wordpress that performed a search and replace on the post content. The idea was to replace `CO2` with `CO<sub>2</sub>`. This messed up the code for some of the inline images in the post content.

**Comment by Haldaug** [comment]
That's good to hear. I'm glad i could be of help.
