### ISSUE TITLE
@gatsbyjs/reach-router: incorrect peer dependency

### ISSUE THREAD

**Issue by vrabe** [gatsbyjs/gatsby#35339]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When I install Gatsby with React 18, yarn shows this warning:
```
warning "gatsby > @gatsbyjs/reach-router@1.3.6" has incorrect peer dependency "react@15.x || 16.x || 17.x".
warning "gatsby > @gatsbyjs/reach-router@1.3.6" has incorrect peer dependency "react-dom@15.x || 16.x || 17.x".
```
Does it support React 18? 

### Reproduction Link

https://github.com/vrabe/gatsby-starter-minimal

### Steps to Reproduce

1. `yarn install`

### Expected Result

No these warnings.

### Actual Result

Warnings above.

### Environment

```shell
System:
    OS: Linux 5.16 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 17.8.0 - /usr/bin/node
    Yarn: 1.22.18 - /usr/bin/yarn
    npm: 8.5.5 - /usr/bin/npm
  Languages:
    Python: 3.10.4 - /usr/bin/python
  Browsers:
    Firefox: 98.0.2
  npmPackages:
    gatsby: ^4.11.1 => 4.11.1
```

**Comment by LekoArts** [comment]
Thanks!

This is fixed in `@gatsbyjs/reach-router@1.3.7`
