### ISSUE TITLE
[gatsby-source-wordpress] extra placeholder when an image is wrapped in an anchor tag

### ISSUE THREAD

**Issue by kelleyco2** [gatsbyjs/gatsby#35348]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

We are in the process of updating multiple client sites from v3 to v4. We believe the way the HTML is being processed is not working well when an image is wrapped in an anchor tag. One of our clients wraps the images within their posts in anchor tags which causes an extra placeholder to show above the image within a post:
![Screen Shot 2022-04-05 at 12 10 45 PM](https://user-images.githubusercontent.com/42013663/161823352-8762b957-b546-49c1-a814-74ac06627f8a.png)

We tested this on another site of ours and got the same result:
<img width="780" alt="Screen Shot 2022-04-05 at 12 21 45 PM" src="https://user-images.githubusercontent.com/42013663/161823766-e18f5cf2-1a7a-45b7-bd5d-35251da49f36.png">

https://user-images.githubusercontent.com/42013663/161826779-0536ffe5-cda7-49d8-af55-5b7ff36c8105.mov

### Reproduction Link

https://hghstaging.gatsbyjs.io/smoked-chicken-legs/

### Steps to Reproduce

1. Create a WordPress post with an image wrapped in an anchor tag
2. Build
3. View post with an extra placeholder image

### Expected Result

We expect the images to only have one placeholder image.

### Actual Result

An extra placeholder is added and takes up space when it shouldn't.

### Environment

```shell
System:
    OS: macOS 12.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 100.0.4896.75
    Firefox: 96.0.2
    Safari: 15.3
  npmPackages:
    gatsby: 4.11.1 => 4.11.1 
    gatsby-awesome-pagination: 0.3.8 => 0.3.8 
    gatsby-plugin-algolia: 0.26.0 => 0.26.0 
    gatsby-plugin-canonical-urls: 4.10.0 => 4.10.0 
    gatsby-plugin-force-trailing-slashes: 1.0.6 => 1.0.6 
    gatsby-plugin-gatsby-cloud: 4.10.0 => 4.10.0 
    gatsby-plugin-google-analytics: 4.10.0 => 4.10.0 
    gatsby-plugin-image: 2.11.1 => 2.11.1 
    gatsby-plugin-loadable-components-ssr: 4.2.0 => 4.2.0 
    gatsby-plugin-manifest: 4.10.1 => 4.10.1 
    gatsby-plugin-netlify: 4.1.0 => 4.1.0 
    gatsby-plugin-perf-budgets: 0.0.18 => 0.0.18 
    gatsby-plugin-react-helmet: 5.10.0 => 5.10.0 
    gatsby-plugin-react-helmet-canonical-urls: 1.4.0 => 1.4.0 
    gatsby-plugin-remove-serviceworker: 1.0.0 => 1.0.0 
    gatsby-plugin-robots-txt: 1.7.0 => 1.7.0 
    gatsby-plugin-root-import: 2.0.8 => 2.0.8 
    gatsby-plugin-sharp: 4.11.1 => 4.11.1 
    gatsby-plugin-sitemap: 5.10.1 => 5.10.1 
    gatsby-plugin-styled-components: 5.10.0 => 5.10.0 
    gatsby-plugin-webpack-bundle-analyser-v2: 1.1.27 => 1.1.27 
    gatsby-plugin-wpgraphql-seo: 1.4.1 => 1.4.1 
    gatsby-source-filesystem: 4.10.0 => 4.10.0 
    gatsby-source-shopify: 6.10.1 => 6.10.1 
    gatsby-source-wordpress: 6.10.1 => 6.10.1 
    gatsby-transformer-sharp: 4.11.0 => 4.11.0 
  npmGlobalPackages:
    gatsby-cli: 4.9.0
```

### Config Flags

FAST_DEV: true
PARALLEL_SOURCING: true
PRESERVE_FILE_DOWNLOAD_CACHE: true

**Comment by ui-jb** [comment]
We're also experiencing this issue with gatsby-source-wordpress. The only difference is that our images aren't wrapped in anchor tags.

Here is our dependency list:
`"axios": "^0.22.0",
"dayjs": "^1.10.7",
"gatsby": "^4.16.0",
"gatsby-background-image": "^1.6.0",
"gatsby-plugin-catch-links": "^4.16.0",
"gatsby-plugin-gatsby-cloud": "^4.16.0",
"gatsby-plugin-google-analytics": "^4.16.0",
"gatsby-plugin-google-tagmanager": "^4.16.0",
"gatsby-plugin-image": "^2.16.1",
"gatsby-plugin-manifest": "^4.16.0",
"gatsby-plugin-offline": "^5.16.0",
"gatsby-plugin-react-helmet": "^5.16.0",
"gatsby-plugin-react-svg": "^3.1.0",
"gatsby-plugin-robots-txt": "^1.7.1",
"gatsby-plugin-rollbar": "^1.1.0",
"gatsby-plugin-sharp": "^4.16.1",
"gatsby-plugin-wpgraphql-seo": "^1.4.1",
"gatsby-remark-responsive-iframe": "^5.16.0",
"gatsby-source-filesystem": "^4.16.0",
"gatsby-source-graphql": "^4.16.0",
"gatsby-source-wordpress": "^6.16.1",
"gatsby-transformer-sharp": "^4.16.0",
"gbimage-bridge": "^0.2.1",
"html-react-parser": "^1.4.0",
"prop-types": "^15.7.2",
"react": "^17.0.2",
"react-dom": "^17.0.2",
"react-helmet": "^6.1.0",
"react-share": "^4.4.0",
"reading-time": "^2.0.0-1",
"rollbar": "^2.24.0",
"typescript": "^4.4.3"`

**Comment by jehns** [comment]
We have the same issue without anchor tags. Still trying to figure out the exact behavior but either this happens or only the placeholder image is rendered (before disappearing). Also, it seems like dev behavior differs from build behavior. Will provide more information once i know more.

**Comment by jehns** [comment]
On our site, the only gatsby images affected by this issue are the ones coming from Wordpress WYSIWYG editors (html). On develop the behavior is exactly as posted above where an empty image seems to be stacked on top of the actual image. On build, you see the placeholder image appear then quickly be replaced with nothing. Will post videos of both behaviors below (please note image in upper-left corner is a gatsby image _not_ coming from a WYSIWYG editor), throttling network to fast 3g to emphasize the issue. All gatsby dependencies are running the latest versions and Wordpress version & plugins are up to date as well. Happy to provide any additional information and would love to hear from anyone else who has or is experiencing this. 

Develop

https://user-images.githubusercontent.com/36684202/175436175-bd21290c-9427-44c1-b1d0-4d5f4d75c24b.mov


Build

https://user-images.githubusercontent.com/36684202/175436197-0816969e-0373-4773-b41f-16139a9f0f08.mov

**Comment by AndrewKepson** [comment]
I have been having the same issue as well. Images are not wrapped in a tags and are coming from posts (Gutenberg editor). This started happening in the last month after deps to latest version.

**Comment by ui-jb** [comment]
Updating to Gatsby version 4.19.0 has resolved this issue for me. I think this is the pr that fixed it: https://github.com/gatsbyjs/gatsby/pull/36002

**Comment by TylerBarnes** [comment]
Heck yes, thanks for trying it out and following up here @ui-jb !
