### ISSUE TITLE
Doesn't work on windows 7

### ISSUE THREAD

**Issue by hackhat** [gatsbyjs/gatsby#3534]
## Description

Getting this error: 

```
>gatsby new gatsby-site
info Creating new site from git: git://github.com/gatsbyjs/gatsby-starter-defaul
t.git
Cloning into 'gatsby-site'...
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=No error
github.com[1: 192.30.253.112]: errno=No error

error Command failed: git clone git://github.com/gatsbyjs/gatsby-starter-default
.git gatsby-site --single-branch


  Error: Command failed: git clone git://github.com/gatsbyjs/gatsby-starter-defa
  ult.git gatsby-site --single-branch
```

### Environment

Gatsby version: 1.1.28
Node.js version: 8.9.1
Operating System: Win 7 64 bit

### Actual result

Getting this error: 
```
>gatsby new gatsby-site
info Creating new site from git: git://github.com/gatsbyjs/gatsby-starter-defaul
t.git
Cloning into 'gatsby-site'...
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=No error
github.com[1: 192.30.253.112]: errno=No error

error Command failed: git clone git://github.com/gatsbyjs/gatsby-starter-default
.git gatsby-site --single-branch


  Error: Command failed: git clone git://github.com/gatsbyjs/gatsby-starter-defa
  ult.git gatsby-site --single-branch
```

### Expected behavior

No error

### Steps to reproduce

Follow steps from: https://www.gatsbyjs.org/docs/
1\. npm install --global gatsby-cli

2\. gatsby new gatsby-site

### Fix

1. `git clone https://github.com/gatsbyjs/gatsby-starter-default`
2. `npm install`

**Comment by KyleAMathews** [comment]
Looks like for some reason git couldn't connect to github — `fatal: unable to connect to github.com:` — so this isn't a Gatsby error. It could have been a temporary network problem so please try again!

**Comment by hackhat** [comment]
But worked with custom `git` command. See the fix section. It worked when the other didn't work, so I doubt is a git network issue.
