### ISSUE TITLE
[gatsby-source-contentful] Assets with no linked entries fail the builds

### ISSUE THREAD

**Issue by patibugaj** [gatsbyjs/gatsby#35356]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

From yesterday we have noticed that `gatsby-source-contentful` started throwing an error on processing assets during the build process in Gatsby Cloud. The project runs locally on development without any issues.
We discovered that not processed assets have something in common - all of them have no linked entry in Contentful. But this is not anything new. That is why we cannot figure out the main issue and we need your help with that.

We are using `"gatsby-source-contentful": "^5.14.1"`

### Reproduction Link

https://www.gatsbyjs.com/dashboard/e334dd9e-3fcc-48e0-9a51-8ec9f4684dc1/sites/1bb1425a-bce7-4fab-9a08-c5843f5fc298/builds/e52f9908-79d0-449c-8df5-5871287ac1ca/details#rawLogs

### Steps to Reproduce

Triggering builds in Gatsby Cloud with cleared cache started this issue yesterday. We didn't release any code changes that could have an impact on that.

### Expected Result

The builds should not fail on assets without entry linked in Contentful.

### Actual Result

The builds fail on assets without linked entries in Contentful.

### Environment

```shell
The issue appears in Gatsby Cloud builds. But this environment config is from a local machine.

System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (100.0.1185.29)
  npmPackages:
    gatsby: ^3.14.2 => 3.14.6
    gatsby-cypress: ^1.14.0 => 1.14.0
    gatsby-plugin-emotion: ^6.14.0 => 6.14.0
    gatsby-plugin-env-variables: ^2.1.0 => 2.2.0
    gatsby-plugin-eslint: ^3.0.0 => 3.0.0
    gatsby-plugin-gatsby-cloud: ^2.11.0 => 2.11.0
    gatsby-plugin-image: ^1.14.1 => 1.14.2
    gatsby-plugin-loadable-components-ssr: ^3.4.0 => 3.4.0
    gatsby-plugin-manifest: ^3.14.0 => 3.14.0
    gatsby-plugin-react-helmet: ^4.14.0 => 4.14.0
    gatsby-plugin-robots-txt: ^1.6.10 => 1.6.14
    gatsby-plugin-sharp: ^3.14.1 => 3.14.3
    gatsby-plugin-sitemap: ^3.3.0 => 3.3.0
    gatsby-plugin-svgr: ^3.0.0-beta.0 => 3.0.0-beta.0
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.25 => 1.1.26
    gatsby-source-contentful: ^5.14.1 => 5.14.1
    gatsby-source-filesystem: ^3.14.0 => 3.14.0
    gatsby-transformer-remark: ^4.11.0 => 4.11.0
    gatsby-transformer-sharp: ^3.14.0 => 3.14.0
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

For Gatsby Cloud specific support please head here: https://www.gatsbyjs.com/support/

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by patibugaj** [comment]
The issue has been fixed based on https://status.gatsbyjs.com/ 🚀
