### ISSUE TITLE
[gatsby-source-filesystem] Incorrect type definition for createFileNodeForAsset

### ISSUE THREAD

**Issue by Joe-Edwards** [gatsbyjs/gatsby#35363]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

The type definition for `createRemoteFileNode` (specifically the `CreateRemoteFileNodeArgs` interface) doesn't match the [documentation](https://www.gatsbyjs.com/plugins/gatsby-source-filesystem/#createremotefilenode) or [implementation](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-filesystem/src/create-remote-file-node.js#L105), in particular:
- `store` is mandatory in the types, but not present in the docs or implementation
- `cache` is mandatory in the types, but not present in the docs, and optional in the implementation
- `getCache` is missing from the types, but mandatory in the docs, and optional in the implementation (but you must pass one of `cache` or `getCache`)
- `reporter` is mandatory in the types, but not present in the docs or implementation

### Steps to Reproduce

1. Use Typescript `gatsby-node.ts`
2. Use the `createRemoteFileNode` function as documented:
```
  const fileNode = createRemoteFileNode({
    url: encodeURI(node.url),
    getCache, // Object literal may only specify known properties, and 'getCache' does not exist in type 'CreateRemoteFileNodeArgs'.
    createNode,
    createNodeId,
    parentNodeId: node.id,
  });
```

### Expected Result

Typescript compiles successfully

### Actual Result

Type errors being reported due to incorrect arguments

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.6.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    gatsby: ^4.10.3 => 4.10.3 
    gatsby-plugin-eslint: ^4.0.2 => 4.0.2 
    gatsby-plugin-image: 2.10.1 => 2.10.1 
    gatsby-plugin-react-helmet-async: ^1.2.1 => 1.2.1 
    gatsby-plugin-styled-components: ^5.10.0 => 5.10.0 
    gatsby-source-contentstack: 4.0.1 => 4.0.1 
    gatsby-source-filesystem: ^4.10.1 => 4.10.1 
    gatsby-transformer-json: ^4.10.0 => 4.10.0
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

Indeed, the TypeScript definition diverged from what is actually correct now.

The TypeScript definitions are here:

https://github.com/gatsbyjs/gatsby/blob/b669468677434a5659842c697b51e838ca470e80/packages/gatsby-source-filesystem/index.d.ts#L29-L45

A reference for what it actually should be is https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-filesystem/src/create-remote-file-node.js#L105 and https://github.com/gatsbyjs/gatsby/blob/b669468677434a5659842c697b51e838ca470e80/packages/gatsby-source-filesystem/src/create-remote-file-node.js?rgh-link-date=2022-04-07T13%3A09%3A47Z#L26-L37

**Comment by Apprentice76** [comment]
Hi, can I work on this? If I understand right, I have to modify the index.d.ts to match the references, like adding the missing argument and setting the others to optional when required.

**Comment by Apprentice76** [comment]
The same thing as been bothering me but the function description here
https://github.com/gatsbyjs/gatsby/blob/f63d13db0c635c0ade66169982e061630306fca0/packages/gatsby-source-filesystem/src/create-remote-file-node.js#L26-L37
has me confused as to whether the reporter param is required or not, should I remove this line as well?

I'm removing the Store param as it's not mentioned in the refrences.

Also I noticed, that createFileNodeFromBuffer has the same issue, should I change that as well? Here
https://github.com/gatsbyjs/gatsby/blob/b669468677434a5659842c697b51e838ca470e80/packages/gatsby-source-filesystem/index.d.ts#L47-L58

when it should be like

https://github.com/gatsbyjs/gatsby/blob/f63d13db0c635c0ade66169982e061630306fca0/packages/gatsby-source-filesystem/src/create-file-node-from-buffer.js#L118-L129

**Comment by Joe-Edwards** [comment]
This is still an issue, looks like the PR https://github.com/gatsbyjs/gatsby/pull/35422 has got stuck

**Comment by raaz001** [comment]
> its ....a  spooky quiet   about not logging many days in past .
