### ISSUE TITLE
Broken embed link in blogpost: Flying Feature Flags with LaunchDarkly’s New Plugin for Gatsby

### ISSUE THREAD

**Issue by kkhan01** [gatsbyjs/gatsby#35384]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

The youtube embed link in https://www.gatsbyjs.com/blog/2020-03-23-flying-feature-flags-with-new-launchdarkly-plugin/ is not a valid link.

### Steps to Resolve this Issue

Probably add a missing `h` to `ttps://www.youtube.com/embed/kCidJJf75CA` to make it https://www.youtube.com/embed/kCidJJf75CA.

**Comment by LekoArts** [comment]
Thanks, it's fixed.
