### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by suhasdeshpande** [gatsbyjs/gatsby#3539]
## Description

This is not a issue. Gatsby works pretty smooth. Has great documentation. I am requesting a feature or I would want to work with Gatsby to get a support for Angular. People/community building their apps on angular are missing out or could use these on these powerful and clean interfaces that Gatsby provides for react ecosystem. 

As discussed on twitter, https://twitter.com/gatsbyjs/status/952745191923789825 I would love to get the discussion started here. I would love to contribute but I will need help in understanding how I can go about.

**Comment by akadop** [comment]
you would probably need a whole rewrite of gatsby.. the only thing remaining from gatsby would be the name. i understand the appeal for angular devs but I don't think this is really feasible

**Comment by suhasdeshpande** [comment]
Angular and react on higher level offer somewhat similar interfaces/life cycle hooks. @akadop trying to understand what parts of Gatsby are really hard to make it work for other frameworks?

**Comment by KyleAMathews** [comment]
Hey! Thanks for dropping by @suhasdeshpande :-)

So definitely thought about supporting Angular, Vue, Glimmer, etc. with Gatsby. It's definitely possible. Basically where we directly do React things, we'd need to create abstractions so we could choose between different frameworks. Most of the direct React actions happens in files in https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby/cache-dir

This would also cause problems with plugins which implement gatsby-browser.js & gatsby-ssr.js as many of them add React components to sites. Either you duplicate those for angular/ember/vue equivalents or there's some way of easily choosing the specific framework version that's needed e.g. gatsby-browser-angular.js.

Many parts of Gatsby wouldn't change e.g. the GraphQL data layer, webpack/babel setup, and the other node-specific APIs.

This would be a major undertaking — once which I'm not going to jump on any time soon. I don't think we could do this unless there parties from at least two other frameworks that were willing to commit serious time to refactoring parts of Gatsby and building out support for their framework-of-choice.

**Comment by softEngJason** [comment]
The time has come for integration. Angular Team and @robwormald have released Angular 6 which include aforementioned Angular Elements.  This should make for easier path to including Gatsby within Angular applications. Maybe without even reworking the React parts.

**Comment by mbaljeetsingh** [comment]
Is anyone working on the Gatsby Angular Integration?

**Comment by KishanIos007** [comment]
Hi everyone I am searching how we can use gatsby inside specific folder of an angular app and google lands me here @KyleAMathews  Thanks for the technical description but after lots of research and google I am still not able to figure it out how we can combine this wonderful frameworks. anyone with any kind of success ?

**Comment by suhasdeshpande** [comment]
I'm actually fine closing it.

**Comment by alfaproject** [comment]
Awwww, I was looking forward to 1st class support for Angular ):

**Comment by mbaljeetsingh** [comment]
> Are there any alternatives for angular?

Angular has something similar in the form of **Angular Universal**, There is currenly first class support for Server Side Rendering (**SSR**). First class support for **prerendering (Static site)** is coming soon.

In the mean time, you can use something like [**angular-prerender**](https://github.com/chrisguttandin/angular-prerender) for static site generation.

Thanks
