### ISSUE TITLE
Attempting to require better-queue-memory

### ISSUE THREAD

**Issue by paolodedomini** [gatsbyjs/gatsby#35391]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Running a build in gatsby 4.7.1 on node 16 and i get: 

`Error: Attempting to require better-queue-memory, but failed.
  Please ensure you have this store installed via npm install --save better-queue-memory`

So i installed the requested module but nothing changed.

Since this is a build problem i post the entire project, which is a test for odoo apis.

Many Thanks.

### Reproduction Link

[monemaweb-gatsby-odoo-ecommerce-1b5da44ada60.zip](https://github.com/gatsbyjs/gatsby/files/8462576/monemaweb-gatsby-odoo-ecommerce-1b5da44ada60.zip)

### Steps to Reproduce

1. npm run build
2. Get the error
3. :(
...

### Expected Result

an actual build to serve

### Actual Result

` Error: Attempting to require better-queue-memory, but failed.
  Please ensure you have this store installed via npm install --save better-queue-memory
  
  - index.js:227040 loadStore
    /Users/paolo/Documents/lavoro/gatsby-commerce/gatsbycommerce/.cache/query-engine/index.js:227040:13
  
  - index.js:227045 Queue.use
    /Users/paolo/Documents/lavoro/gatsby-commerce/gatsbycommerce/.cache/query-engine/index.js:227045:17
  
  - index.js:226978 new Queue
    /Users/paolo/Documents/lavoro/gatsby-commerce/gatsbycommerce/.cache/query-engine/index.js:226978:8
  
  - index.js:222522 Object.<anonymous>
    /Users/paolo/Documents/lavoro/gatsby-commerce/gatsbycommerce/.cache/query-engine/index.js:222522:15
  
  - index.js:391693 __webpack_require__
    /Users/paolo/Documents/lavoro/gatsby-commerce/gatsbycommerce/.cache/query-engine/index.js:391693:42
  
  - index.js:219335 Object.<anonymous>
    /Users/paolo/Documents/lavoro/gatsby-commerce/gatsbycommerce/.cache/query-engine/index.js:219335:32
  
  - index.js:391693 __webpack_require__
    /Users/paolo/Documents/lavoro/gatsby-commerce/gatsbycommerce/.cache/query-engine/index.js:391693:42
  
  - index.js:219203 Object.<anonymous>
    /Users/paolo/Documents/lavoro/gatsby-commerce/gatsbycommerce/.cache/query-engine/index.js:219203:5
  
  - index.js:391693 __webpack_require__
    /Users/paolo/Documents/lavoro/gatsby-commerce/gatsbycommerce/.cache/query-engine/index.js:391693:42
  
  - index.js:189058 Module.__webpack_modules__.buildSchema.buildSchema
    /Users/paolo/Documents/lavoro/gatsby-commerce/gatsbycommerce/.cache/query-engine/index.js:189058:164
  
  - index.js:391693 __webpack_require__
    /Users/paolo/Documents/lavoro/gatsby-commerce/gatsbycommerce/.cache/query-engine/index.js:391693:42
  
  - index.js:391827 
    /Users/paolo/Documents/lavoro/gatsby-commerce/gatsbycommerce/.cache/query-engine/index.js:391827:27
  
  - index.js:392005 
    /Users/paolo/Documents/lavoro/gatsby-commerce/gatsbycommerce/.cache/query-engine/index.js:392005:3
  
  - index.js:392010 Object.<anonymous>
    /Users/paolo/Documents/lavoro/gatsby-commerce/gatsbycommerce/.cache/query-engine/index.js:392010:12
  
  - loader:1103 Module._compile
    node:internal/modules/cjs/loader:1103:14
  
  - loader:1155 Object.Module._extensions..js
    node:internal/modules/cjs/loader:1155:10
  

not finished Running gatsby-plugin-sharp.IMAGE_PROCESSING jobs - 78.004s`

### Environment

```shell
In Windows, ubuntu, mac...: same result.
```

**Comment by tyhopp** [comment]
Hi @paolodedomini, sorry to hear you're running into an issue.

`better-queue-memory` is a transitive dependency of `gatsby-source-wordpress`, you don't need to install it yourself. I wasn't able to reproduce this after bootstrapping a [new wordpress starter blog project](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/getting-started.md).

I'd recommend doing the same to see if you run into the same issue. Also for minimal reproductions in the future please include a link to a public repository so we can inspect the code before downloading it.

Closing this, we can reopen if your issue persists with a new project. Thanks!

**Comment by paolodedomini** [comment]
I don't use gatsby-source-wordpress, but i get that error message aniway.
Why you tried to bootstrap a new wordpress project and how is this related to this kind of issue?
Have you tried to build from the package linked in the description? There is all the project files from github.
I don't think thi issue is so closed aniway.
Thanks.

**Comment by tyhopp** [comment]
Please create a public repository with your minimal reproduction, thank you.

**Comment by paolodedomini** [comment]
git@github.com:paolodedomini/Godoo-reproduction-.git
I made a public repository, 
Thanks

**Comment by tyhopp** [comment]
Hi, I wasn't able to reproduce this issue. I recommend [starting with the latest default starter](https://www.gatsbyjs.com/starters/gatsbyjs/gatsby-starter-default/) so you have all the latest modules. Also I saw `gatsby-recipes` is installed, please note that [it is deprecated](https://github.com/gatsbyjs/gatsby/tree/master/deprecated-packages/gatsby-recipes).

If you have questions please post them [in a discussion](https://github.com/gatsbyjs/gatsby/discussions), we try to make sure issues are for bug reports. Thanks!
