### ISSUE TITLE
Disabling Prefetching is not working as expected!

### ISSUE THREAD

**Issue by ezrover** [gatsbyjs/gatsby#35409]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I have disabled link prefetching in gatsby-browser.js with the following line: 

`
export const disableCorePrefetching = () => true
`

When you visit a simple page such as https://www.lucidmotors.com/test you can see that it is still downloading content for pages that are not yet visible.

Thank you in advance for your help

### Reproduction Link

https://www.lucidmotors.com/test

### Steps to Reproduce

1. Visit https://www.lucidmotors.com/test
2. Open Chrome Developer tab
3. View Network requests

...

### Expected Result

Page data for other CTAs should not be downloaded! For example https://www.lucidmotors.com/page-data/sq/d/402129575.json

### Actual Result

Gatsby is downloading all the data for other CTAs that are not yet visible!

### Environment

```shell
System:
    OS: macOS 11.6.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.8.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 100.0.4896.75
    Safari: 15.3
```

### Config Flags

d

**Comment by ezrover** [comment]
Any eyes on this request?

**Comment by pieh** [comment]
Hey @ezrover

I looked at your built site and prefetching is disabled - the primary thing here is that `page-data` (which is page/route entry point) do not fetch for linked pages when link is in viewport - you do have to hover you mouse over link (if on desktop) to trigger loading.

All those `<some_number>.json` files however are marked as "needed" by current page (`staticQueryHashes` property) as if all 19 of them would be used by either 404 page template or some shared code (things like shared layout etc):

![Screenshot 2022-04-19 at 21 39 23](https://user-images.githubusercontent.com/419821/164083158-ab0292dd-6097-4f52-94b4-8fb6f727c0d0.png)

If those are not expected to be part of the page we would need source to debug this further (it does look at very least a little weird that there are so many of them)

**Comment by ezrover** [comment]
Thanks Michael (@pieh ), how can we get in touch to do a remote zoom call to review the code? please reach out directly ardumotion at gmail

**Comment by LekoArts** [comment]
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!
