### ISSUE TITLE
[gatsby-plugin-mdx] Subplugin cache is never set

### ISSUE THREAD

**Issue by raae** [gatsbyjs/gatsby#35415]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Using the Gatsby cache in a gatsbyRemarkPlugins under gatsby-plugin-mdx seems to never be set.

Minimal gatsbyRemarkPlugin:

```
// gatsbyRemarkPlugin -> index.js
module.exports = async ({markdownNode, cache, reporter}) => {
  const test = await cache.get("test");
  if (!test) {
    reporter.info(`Node: ${markdownNode.id} - No cache for test`);
    await cache.set("test", "hello");
  } else {
    reporter.info(`Node: ${markdownNode.id} - Cache for test`);
  }
};
```

results in: 

<img width="770" alt="CleanShot 2022-04-13 at 07 45 26@2x" src="https://user-images.githubusercontent.com/478531/163109661-ac45dace-5d58-4e11-a12c-0b45cd7dd195.png">

### Reproduction Link

https://github.com/raae/gatsby-mdx-cache-bug/blob/main/plugins/cache-bug/index.js

### Steps to Reproduce

1. Run `yarn develop`

### Expected Result

There to be a cached value for test at some point.

### Actual Result

There is no cache for test.

### Environment

```shell
System:
    OS: macOS 11.6.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.17.6 - /var/folders/t7/4k164scs3l374b1xwglxkxy80000gn/T/yarn--1649829568021-0.10182785175509079/node
    Yarn: 1.22.4 - /var/folders/t7/4k164scs3l374b1xwglxkxy80000gn/T/yarn--1649829568021-0.10182785175509079/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 100.0.4896.75
    Firefox: 97.0
    Safari: 14.1.2
  npmPackages:
    gatsby: ^4.4.0 => 4.11.1
    gatsby-plugin-gatsby-cloud: ^4.0.0 => 4.11.1
    gatsby-plugin-manifest: ^4.0.0 => 4.11.1
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.22 => 1.1.27
```

**Comment by raae** [comment]
@Swizec seemed to be running into the same problem: https://twitter.com/Swizec/status/1512812875223486466?s=20&t=2UQ4OM3mhUm9KQoVLTWfDQ

I am pretty sure this worked in December 2019 btw.

**Comment by raae** [comment]
It seems to also be true when used as a sub-plugin for gatsby-transformer-remark (I get around this in gatsby-remark-oembed by setting the value needed in onPreBootstrap, however that would not solve the @Swizec case or my future case of caching results per link found in the markdown).

**Comment by ediblecode** [comment]
I _think_ I'm seeing a similar thing, with using `cache.set` and `cache.get` in a custom source plugin. My case is within `createSchemaCustomization` inside a field extension created via `createFieldExtension` but the same symptom applies: the cache is not set.

I've inspected the `cache` object whilst debugging and the cache directory looks correct (.cache/<name>) but none of the JSON files are _actually_ stored inside the .cache folder. I'll keep poking around and update if I find out anything useful.

**Comment by LekoArts** [comment]
Hi!

We merged https://github.com/gatsbyjs/gatsby/pull/35650 which means that a new major version of `gatsby-plugin-mdx` will be released on August 16. You can already try it out by installing `gatsby-plugin-mdx@next` & `gatsby@next`.

If you're still experiencing this issue with the new version of `gatsby-plugin-mdx` and MDX v2, please open a new issue with a minimal reproduction. Thanks!
