### ISSUE TITLE
Add GTM to Gatsby's `www` for better analytics & tracking

### ISSUE THREAD

**Issue by benjaminhoffman** [gatsbyjs/gatsby#3542]
I'd like to propose adding [Gatsby Google Tag Manager plugin](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-google-tagmanager) to Gatsby's www for the following reasons:

- allows for easy conversion tracking of things like form submits or link clicks (vs hard coding these within the code on each page)
- we can easy add/remove marketing tools as we grow without having to update code
- protects Gatsby's GA ID (since GA will fire within GTM, our property ID will never be exposed on the client)
- GTM has version control whereas GA and other marketing tools does not
- using a tag manager is the "right way" to do it
- dog fooding.  We already have a plugin, we should be using it and updating it over time, especially as the market as a whole starts to migrate to tag managers

Would love to help address any questions or concerns around switching from Gatsby-GA plugin to Gatsby-GTM plugin.  Please ask away!

My proposed roadmap:

- install Gatsby GTM plugin
- create a _new_ GA account, with conversion tracking, etc
- in 90 days compare the traffic of the GTM/GA setup vs the current GA setup... if numbers align, remove the gatsby-GA plugin and migrate that GA account to using the GTM plugin.  If the numbers are not the same, then dig deeper to figure out why.

**Comment by nickmccurdy** [comment]
Out of curiosity how this different from the new [`gtag.js`](https://developers.google.com/analytics/devguides/collection/gtagjs/) snippet for Google Analytics, is it just for hiding the analytics tag?

**Comment by benjaminhoffman** [comment]
good question @nickmccurdy.  For starters, _gtag.js_ is still in beta, I _think_, so there are still more questions than answers for a handful of topics related to GA.  But more specifically, the gtag is for GA, whereas GTM is a tag manager (gtag is GA's newest version of their js snippet).

A tag manager allows you to manage a whole handful of marketing tags, not just google.  So let's say we want to fire a fb ad pixel... 3 clicks in GTM allow us to set that up vs. opening a PR that adds the pixel.  Now we want to add twitter ad pixel.  Boom, same thing.

Next thing you know, we have a million ad pixels on our site.  Also have a million analytics tracking pixels too.  It gets super messy and could even slow down our website.

Instead, let's bundle everything up in **one** pixel (GTM) and allow that to pass on the info.  This is not unlike how Segment (analytics.js) works.  Other benefits include hiding the IDs from third parties and having an easy UI for marketers to work with (since they generally don't know enough code to be adding/removing their pixels / snippets).

Makes sense?  Let me know if I can diver deeper on any of that, or if you have add'l questions.

**Comment by KyleAMathews** [comment]
Sounds reasonable and safe! Let's do it 👍

**Comment by benjaminhoffman** [comment]
@KyleAMathews can you create an account here.  add me as admin, I'll take care of the rest and provide an update as soon as I get it up and running.  https://tagmanager.google.com
