### ISSUE TITLE
Error when using create-gatsy: TypeError: qi.cursorTo is not a function

### ISSUE THREAD

**Issue by sinedied** [gatsbyjs/gatsby#35426]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When running `npx create-gatsby@latest -y gatsby` on Debian, I get the following error:
```
TypeError: qi.cursorTo is not a function
    at Timeout._onTimeout (/root/.npm/_npx/002b89b2b79de663/node_modules/create-gatsby/lib/inde
```

### Reproduction Link

https://github.com/sinedied/frameworks-playground/runs/6021942621?check_suite_focus=true

### Steps to Reproduce

1. On an Debian machine (or docker image based on Debian), run `npx create-gatsby@latest -y gatsby`

### Expected Result

No crash :)

### Actual Result

Crash with error :
```
TypeError: qi.cursorTo is not a function
    at Timeout._onTimeout (/root/.npm/_npx/002b89b2b79de663/node_modules/create-gatsby/lib/inde
```

### Environment

```shell
This error is related to create-gatsby: version 2.12.1

System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (6) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.14.2 - /usr/local/share/nvm/current/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.6.0 - /usr/local/share/nvm/current/bin/npm
  Languages:
    Python: 3.9.10 - /usr/local/bin/python
```

**Comment by tyhopp** [comment]
Hi @sinedied, sorry to hear you're running into an issue. Before I attempt to reproduce this in a Docker image could you try these two things and see if the issue persists:

- [Disable colors in CLI output](https://www.gatsbyjs.com/docs/reference/gatsby-cli/#disabling-colored-output)
- Setting `GATSBY_LOGGER=yurnalist` env var to switch from the default logger `ink`

Thanks!

**Comment by THEDARKMAN007** [comment]
> Hi @sinedied, sorry to hear you're running into an issue. Before I attempt to reproduce this in a Docker image could you try these two things and see if the issue persists:
> 
> * [Disable colors in CLI output](https://www.gatsbyjs.com/docs/reference/gatsby-cli/#disabling-colored-output)
> * Setting `GATSBY_LOGGER=yurnalist` env var to switch from the default logger `ink`
> 
> Thanks!

pls could you explain in detail how to do this. i dont understand the commands to run on my terminal or what file to edit
@tyhopp @sinedied
