### ISSUE TITLE
`gatsbyImageOptions` doesn’t seem to apply when sourcing images from WP + Gutenberg

### ISSUE THREAD

**Issue by stephencottontail** [gatsbyjs/gatsby#35439]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [x] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I’m using the Gutenberg editor with WP and so I use [`wp-graphql-gutenberg`](https://github.com/pristas-peter/wp-graphql-gutenberg) to pull the blocks in GraphQL. I have `useGatsbyImage: true` in `gatsby-config.js`, so any images in blocks get transformed to `GatsbyImage` components, but I wanted to use some different options for that transformation. I found the `gatsbyImageOptions` setting in the [documentation](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/plugin-options.md#htmlgatsbyimageoptions), but it appears that that setting gets ignored during the transformation process.

### Reproduction Link

https://github.com/stephencottontail/gatsby-minimal-repro

### Steps to Reproduce

1. Clone the repo
2. `yarn install` and `gatsby develop`
3. Go to `localhost:8000` in the browser and you’ll see some text and a picture of an office building
...

### Expected Result

I expected that the placeholder for the office building would be a traced SVG.

### Actual Result

 There is nothing shown until the picture loads (though it does appear that the browser is “reserving” space for the picture so if there was any content after the picture, it wouldn’t jump around).

### Environment

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (2) x64 DO-Regular
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.14.2 - /tmp/yarn--1650222949670-0.7733995177049007/node
    Yarn: 1.22.18 - /tmp/yarn--1650222949670-0.7733995177049007/yarn
    npm: 8.5.0 - /usr/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    gatsby: ^4.12.1 => 4.12.1
    gatsby-plugin-catch-links: ^4.12.1 => 4.12.1
    gatsby-plugin-image: ^2.12.1 => 2.12.1
    gatsby-plugin-sharp: ^4.12.1 => 4.12.1
    gatsby-source-wordpress: ^6.12.2 => 6.12.2
    gatsby-transformer-sharp: ^4.12.1 => 4.12.1
```

### Config Flags

No flags

**Comment by TylerBarnes** [comment]
Hi @stephencottontail , apologies for the delayed response time here. [We don't support the integration with `wp-graphql-gutenberg`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/usage-with-popular-wp-graphql-extensions.md#unconfirmed-extensions-might-still-work-but-will-have-problems) as it's a community plugin which is only partially maintained. If you use Gutenberg content in the regular post `content` html field it should work. WPGraphQL is also working on official Gutenberg support though there's no date on when that will arrive.
