### ISSUE TITLE
 [gatsby-source-wordpress] please reopen #32712 

### ISSUE THREAD

**Issue by KeetTechSol** [gatsbyjs/gatsby#35434]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

This is to reopen issue #32712 as this is proving to be a critical problem. I run a couple of sites with more than 2500 products and incremental rebuilds are not updating product changes or adding new products that are added to woocommerce. Even for a price change of 1 product, I am forced to clear that cache and rebuild from the beginning and it takes 4-6 hrs every time to rebuild. The logs clearly show that updates are fetched from woocommerce, but are not reflected on the site or within the graphql IDE.

### Reproduction Link

https://github.com/gatsbyjs/gatsby/issues/32712

### Steps to Reproduce

  please refer to https://github.com/gatsbyjs/gatsby/issues/32712

### Expected Result

please refer to https://github.com/gatsbyjs/gatsby/issues/32712

### Actual Result

please refer to https://github.com/gatsbyjs/gatsby/issues/32712

### Environment

```shell
please refer to https://github.com/gatsbyjs/gatsby/issues/32712
```

### Config Flags

please refer to https://github.com/gatsbyjs/gatsby/issues/32712

**Comment by LekoArts** [comment]
Please open a proper bug report with filling out the template and providing a minimal reproduction. The linked issue is outdated as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
