### ISSUE TITLE
`TRACED_SVG` placeholder for `gatsby-plugin-sharp` returns the full size image tracing

### ISSUE THREAD

**Issue by mhalshehri** [gatsbyjs/gatsby#35537]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When using`TRACED_SVG` as placeholder for images processed using `gatsby-plugin-sharp`, the returned placeholder has the full size of the original image. On the other hand, `gatsby-remark-images` approach returns fixed 400px wide tracedSVG.

### Reproduction Link

https://codesandbox.io/s/gatsby-traced-svg-size-bug-forked-lcnxo9?file=/src/pages/index.js

### Steps to Reproduce

Use GatsbyImage with placeholder of `TRACED_SVG`

### Expected Result

The resulted placeholder image should not exceed the minimum breakpoint or a fixed small width as the tracing details are not necessary.

### Actual Result

The resulted placeholder image has the full size of the original image which compromises the placeholder idea.

![screenshot](https://user-images.githubusercontent.com/542855/166110506-188b340a-eca9-4c08-9c61-852d0912c0d1.png)

### Environment

```shell
System:
  OS: Linux 5.4 Debian GNU/Linux 10 (buster) 10 (buster)
  CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  Shell: 5.0.3 - /bin/bash
Binaries:
  Node: 14.18.1 - /tmp/yarn--1651328268451-0.8489838887442636/node
  Yarn: 1.22.17 - /tmp/yarn--1651328268451-0.8489838887442636/yarn
  npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
Languages:
  Python: 2.7.16 - /usr/bin/python
npmPackages:
  gatsby: ^4.13.0 => 4.13.1
  gatsby-plugin-image: ^2.13.0 => 2.13.0
  gatsby-plugin-sharp: ^4.13.0 => 4.13.0
  gatsby-source-filesystem: ^4.13.0 => 4.13.0
  gatsby-transformer-sharp: ^4.13.0 => 4.13.0
```

**Comment by LekoArts** [comment]
Hi! Thanks for the issue.

I'm not sure I understand the problem here. The placeholder is generated from the source file as this will give the best representation of the original image. If the placeholder would be generated from a minified image details would be lost.

SVG is a mathematical/vector image so having the width/height at higher numbers doesn't increase the size compared to a version with smaller numbers. So there's no need to have the SVG in a smaller size.

**Comment by mhalshehri** [comment]
Seems fixed on newer versions
