### ISSUE TITLE
Gatsby depends on concerning event-source-polyfill package

### ISSUE THREAD

**Issue by just-boris** [gatsbyjs/gatsby#35530]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Gatsby includes `event-source-polyfill` at this line: https://github.com/gatsbyjs/gatsby/blob/54d4721462b9303fed723fdcb15ac5d72e103778/packages/gatsby/cache-dir/polyfill-entry.js#L4

Recent 1.0.26 release included [a change with possibly unwanted side-effects](https://github.com/Yaffle/EventSource/commit/de137927e13d8afac153d2485152ccec48948a7a). More details can be found in this HN post: https://news.ycombinator.com/item?id=30963600

A recommendation would be to drop this dependency

### Reproduction Link

n/a

### Steps to Reproduce

n/a

### Expected Result

n/a

### Actual Result

n/a

### Environment

```shell
n/a
```

**Comment by LekoArts** [comment]
Gatsby still depends on 1.0.25 but it'll be better to pin to that version.
