### ISSUE TITLE
Got stuck on gatsby build, using greensock.

### ISSUE THREAD

**Issue by meiskv** [gatsbyjs/gatsby#3554]
Hi Guys,

I hope this is the right place to post my question regarding my issue on testing a build using gatsby with greensock.

Below is the error that I am getting. I couldn't find any source somewhere on the web that encountered my problem.

https://pasteboard.co/H3fa9l0.png

Thanks!

**Comment by KyleAMathews** [comment]
Looks like a JavaScript error. Search your code for the variables named in the error.

**Comment by meiskv** [comment]
Hi @KyleAMathews , I just attached the greensock code onto the same my component. I wonder if I should place it somewhere for gatsby or webpack to be able to buld it.

Thanks mate!

**Comment by meiskv** [comment]
Hi @KyleAMathews , I already fixed it by putting it on a function and a variable.
