### ISSUE TITLE
HMR breaks following error

### ISSUE THREAD

**Issue by makeable** [gatsbyjs/gatsby#35563]
### Description

HMR breaks following error - requires browser restart to function again.

Tested on both Safari and Chrome on macOS.

### Steps to Reproduce

1) install gatsby as per the docs and run develop
2) make something that will cause an error in the index page and save
3) undo the error and save

### Expected Result

HMR works as usual

### Actual Result

You now have broken HMR. Manual refreshing of the browser is also broken. If you close the browser tab and reopen you get the same problem.

You must close down your browser session (i.e. quit the browser) and restart for it to work again.

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

To make the process of resolving problems quicker for both sides we need you to fill out the issue template and give us a [minimal reproduction][reproduction].

[reproduction]: https://gatsby.dev/reproduction

**Comment by makeable** [comment]
> give us a [minimal reproduction](https://gatsby.dev/reproduction).

Not sure it can be more minimal than what i have given
