### ISSUE TITLE
Terminal `gatsby develop` command broken link URL output

### ISSUE THREAD

**Issue by samjcarter** [gatsbyjs/gatsby#3558]
## Description

The terminal output includes links that used to be clickable (via a plugin for Hyper Terminal using Powershell on Windows) but the link is not longer clickable when running `gatsby develop`.
**The terminal I'm using:**
-  [Hyper Terminal](https://hyper.is/)
-  [Hyperlinks plugin to make links clickable](https://www.npmjs.com/package/hyperlinks)

<u>`http://localhost`</u>:8000 is the output, with the `localhost` portion being clickable, and the port `:8000` on the end is not clickable.

@KyleAMathews  recommended looking at `**develop.js**` to track down the possible cause.

https://github.com/gatsbyjs/gatsby/blob/88445ea480f3cfff90c0fddfcee46853a50bfa94/packages/gatsby/src/commands/develop.js#L277

### Environment

Gatsby version: 1.9.119
Node.js version: 8.8.0
Operating System: Windows 10 Pro 64-bit (running from Pwershell)

### File contents (if changed):
Tested on a fresh install of `gatsby new gatsby-site`

`gatsby-config.js`: 
`package.json`: 
`gatsby-node.js`: 
`gatsby-browser.js`: 
`gatsby-ssr.js`: 

### Actual result

Inspectable terminal (Hyper) output from `gatsby develop`

```html
<x-row>
  <span><a href="http://localhost" data-id="3" class="">http://localhost</a>:</span>
  <span style="font-weight: bold;">8000</span>
  <span>/</span>
</x-row>
```

The image below shows the highlighted code clearly with the "separated" link. The working portion is in pink and the non-working portion in white.

![gatsby-develop-terminal](https://user-images.githubusercontent.com/35503137/35016611-49302a84-fb11-11e7-97a1-73b14347e070.PNG)

### Expected behavior

Inspectable terminal (Hyper) output from `gatsby build`, then `gatsby serve`

```html
<span>
  <a href="http://localhost:9000" data-id="27" class="">http://localhost:9000</a>
</span>
```

### Steps to reproduce

**Pre-requisite if you want to reproduce my set up**

1. Install Hyper Terminal

2. Install Hyperlink plugin for Hyper to make your `http://localhost:8000` linkable/clickable

**Then, to reproduce issue**

1\. `gatsby new gatsby-site`

2\. `cd gatsby-site`

3\. `gatsby develop`

4\. Watch terminal output for the `http://localhost:8000` link

**Comment by KyleAMathews** [comment]
I wonder if something changed in Hyper Terminal? I can click on links just fine in iterm3. I copied the characters and put it into a UTF-8 analyzer and all the characters are normal ASCII characters so we're not outputting weird stuff.

**Comment by KyleAMathews** [comment]
Anyone else seeing problems?

**Comment by samjcarter** [comment]
I've installed a fresh hyper on a different machine and could not reproduce the issue there. Reinstalled on my original machine and the issue has gone. I now get an all-white clickable hyperlink. This might have been a combination of my older 1.4.8 version of hyper and the hyperlinks plugin. I've updated hyper to their unstable pre-release version now, 2.0.0-canary10.

**Comment by peduarte** [comment]
I look at the code that builds the link and everything looks fine. It's most likely an issue with Hyper, but as @samjcarter has said it seems to have been fixed in its latest release. 

The code is also not setting any hardcoded colour, so if the link is all white, I believe it's also due to Hyper (or perhaps a theme if you're using one)

**Comment by KyleAMathews** [comment]
Cool! Thanks for checking again @samjcarter!
