### ISSUE TITLE
Add “--strict” CLI flag for initiating new projects

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#3559]
I think there would be a place for adding a `--strict` CLI flag in order to enforce so-called “best practices” as much as possible.

For example, in strict mode, ESLint could be pre-installed with a strict set of rules (e.g. [eslint-config-airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb)) and corresponting scripts (`lint`, `format`). I think that the recent rise in the amount of Gatsby starters makes the choice harder for beginners, so there should be a more official way to bootstrap projects following a strict set of rules.

**Comment by KyleAMathews** [comment]
Interesting idea!

We're planning on adding support for eslint-loader to v2 which would solve some of this. See the [v2 project](https://github.com/gatsbyjs/gatsby/projects)

I'm a bit wary of pushing too much on people as "best practices" aren't always best :-)

**Comment by kripod** [comment]
@KyleAMathews Surely, "best practices" are subjective, but I think there should be a way to provide a clearer path towards perfectionism (just like [create-react-app](https://github.com/facebookincubator/create-react-app) does so with its ESLint warnings).

**Comment by KyleAMathews** [comment]
Yeah for sure — I think eslint is something we should definitely add to core. Would happy to hear proposals for other specific additions! I don't think a `--strict` flag makes too much sense. Either something is in core, something is in the official starters, or we document "best practices" for other additions.

**Comment by kripod** [comment]
I think that using the default ESLint config of create-react-app would definitely make sense.
