### ISSUE TITLE
Unable to use the fs lib for some reason?

### ISSUE THREAD

**Issue by colbycheeze** [gatsbyjs/gatsby#356]
Hi, I am trying to load a file with fs so doing the usual `import fs from 'fs'`

...but for some reason I get this:
```
Module not found: Error: Cannot resolve module 'fs' in /Users/colbywilliams/projects/gatsby-example-site/pages
resolve module fs in /Users/colbywilliams/projects/gatsby-example-site/pages
```

Can't seem to find an answer that works from Google. Any idea what causes this?

**Comment by KyleAMathews** [comment]
Is this in a frontend module or node module? If frontend, you can't access
the file system.

**Comment by colbycheeze** [comment]
Nevermind I'm silly, I guess I was able to just `require('myfile.yaml')` and it read it as an object properly. Thanks for the quick response though :)
