### ISSUE TITLE
static files with slash have code status 200

### ISSUE THREAD

**Issue by Artemdanilov5** [gatsbyjs/gatsby#35605]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I have gatsby website that hosted on gatsby cloud. I use new option of gatsby "trailingSlash: "always":

```
module.exports = {
    trailingSlash: "always",
}
```

I use default config gatsby-plugin-gatsby-cloud without any options.

After `gatsby build` all my static files with slash at the end have status code 200, but should 404. If I use `gatsby serve` on localhost it's working good and I get 404.

Example: `website.com/static/img.jpg/`

But if I use "never" option I get 301 redirect from `website.com/static/img.jpg/`  to `website.com/static/img.jpg` and I think it's better than 200, but still need to get 404.

```
module.exports = {
    trailingSlash: "never",
}
```

I've noticed this problem on many gatsby sites including `starter-blog-theme`: https://github.com/gatsbyjs/gatsby-starter-blog-theme

### Reproduction Link

https://www.leaftfoods.com/static/8d8cfc95f97e007180db73d4464271af/2432c/3daddde8-33e9-4722-8775-ff1e409641d8_field_-16.jpg/

### Steps to Reproduce

1.Open any static images and add "/" at the end. It must give 404, but it's 200
2.
3.
...

### Expected Result

It must give 404, but it's 200

### Actual Result

but it's 200

### Environment

```shell
any
```

**Comment by LekoArts** [comment]
Hi!

For Gatsby Cloud related issues, please contact the support here: https://www.gatsbyjs.com/support/

Thanks!

**Comment by Artemdanilov5** [comment]
"

> Hi!
> 
> For Gatsby Cloud related issues, please contact the support here: https://www.gatsbyjs.com/support/
> 
> Thanks!

But I have the same problem if deploy on Netlify or other

**Comment by LekoArts** [comment]
You've said:

> After gatsby build all my static files with slash at the end have status code 200, but should 404. If I use gatsby serve on localhost it's working good and I get 404.

So on a framework level the handling is correct, the change is made on the hosting level.

**Comment by Artemdanilov5** [comment]
> You've said:
> 
> > After gatsby build all my static files with slash at the end have status code 200, but should 404. If I use gatsby serve on localhost it's working good and I get 404.
> 
> So on a framework level the handling is correct, the change is made on the hosting level.

If I use 'gatsby develop' it's also code status 200. is it correct behavior?

**Comment by LekoArts** [comment]
`gatsby develop` is trying to be similar to the production environment but it's still a development environment so things are not exact. `gatsby serve` mimics the real-world production environment and it's what you should look out for.
