### ISSUE TITLE
Problem with react-pdf in Gatsby 4

### ISSUE THREAD

**Issue by jakoblind** [gatsbyjs/gatsby#35614]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When I use `react-pdf` in a Gatsby 4 project, I get the following error:

```
  ModuleParseError: Module parse failed: Unexpected character '�' (1:0)
  You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
  (Source code omitted for this binary file)
```

This worked fine for me in Gatsby 3. I saw this had [already been reported](https://github.com/gatsbyjs/gatsby/issues/34382), but now I have created a reproduction repo.

### Reproduction Link

https://github.com/jakoblind/gatsby-react-pdf-bug-repro

### Steps to Reproduce

1. `npm install`
2. `npm run develop`
3. see error

### Expected Result

No errors

### Actual Result

errors as described in description

### Environment

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Edge: 97.0.1072.69
    Firefox: 99.0.1
    Safari: 15.4
  npmPackages:
    gatsby: ^4.13.1 => 4.13.1
```

**Comment by LekoArts** [comment]
Hi!

I'm pretty sure it's a misconfiguration on your end with this specific library but let's make sure it's that and not an actual bug in Gatsby.

I think you misconfigured your entry, you should use `react-pdf/dist/esm/entry.webpack5` as Gatsby 4 uses webpack 5. It's also possible that you'll need to use Gatsby's `onCreateWebpackConfig` API to configure webpack to handle PDF, but we already use the file loader for PDF files:

https://github.com/gatsbyjs/gatsby/blob/15356829a46c2f35973147c120e3dffd3b0bf3e4/packages/gatsby/src/utils/webpack-utils.ts#L590-L595

Maybe that interferes with `react-pdf`, I don't have much context on that package.

**Comment by jakoblind** [comment]
I have updated the repo with `react-pdf/dist/esm/entry.webpack5` and `onCreateWebpackConfig` (inspired by [this](https://github.com/react-pdf-viewer/react-pdf-viewer/issues/497) which worked for me in Gatsby 2). I still get the same error.

I don't import pdf files in the repo, so I don't think the problem is that I need a webpack loader for PDF files.

**Comment by LekoArts** [comment]
I tried a bunch of things from the instructions in https://github.com/wojtekmaj/react-pdf, more specifically https://github.com/wojtekmaj/react-pdf#create-react-app by placing the PDF file inside `static` folder so that it gets copied over during build and referenced it with `./file.pdf`. But that didn't work.

Please open an issue with https://github.com/wojtekmaj/react-pdf. I'm afraid we can't help here in the context of Gatsby.

**Comment by developdeez** [comment]
@LekoArts do you know of any PDF viewers that work with current Gatsby?
My company has the same issue.

**Comment by kelseyn12** [comment]
@LekoArts were you able to find something that works?

**Comment by Monknow** [comment]
In my case, I was able to pin down the problem to a file in the [canvas](https://www.npmjs.com/package/canvas) module, specifically on the `node_modules\canvas\build\Release\canvas.node`

What I did was add a loader in the webpack config to handle `.node` files. Here it's the code


1. Install the node-loader 
```bash
npm install node-loader --save-dev
```


2. add the loader to the webpack config at `gatsby-node.js`
```js
exports.onCreateWebpackConfig = ({actions}) => {
	actions.setWebpackConfig({
		module: {
			rules: [
				{
					test: /\.node$/,
					use: ["node-loader"],
				},
			],
		},
	});
};

```

**Comment by aziz1234** [comment]
> In my case, I was able to pin down the problem to a file in the [canvas](https://www.npmjs.com/package/canvas) module, specifically on the `node_modules\canvas\build\Release\canvas.node`
> 
> What I did was add a loader in the webpack config to handle `.node` files. Here it's the code
> 
> 
> 1. Install the node-loader 
> ```bash
> npm install node-loader --save-dev
> ```
> 
> 
> 2. add the loader to the webpack config at `gatsby-node.js`
> ```js
> exports.onCreateWebpackConfig = ({actions}) => {
> 	actions.setWebpackConfig({
> 		module: {
> 			rules: [
> 				{
> 					test: /\.node$/,
> 					use: ["node-loader"],
> 				},
> 			],
> 		},
> 	});
> };
> 
> ```

This worked for me, Thanks a lot.
