### ISSUE TITLE
`gatsby-image-plugin` race condition prevents placeholder img from fading out when full-res img loads before DOM finishes parsing

### ISSUE THREAD

**Issue by nonAlgebraic** [gatsbyjs/gatsby#35628]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

There is a race condition between the script in charge of hiding placeholder images when full-size images are fully loaded ([this one](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-image/src/gatsby-ssr.tsx#L74-L110)) and pages that take very long to parse. Under certain conditions, this race condition causes the placeholder image generated by the plugin to remain on the page, "behind" the full-size image, instead of fading out.

`gatsby-image-plugin` handles the removal of placeholder images by appending a script during SSR which listens to `load` events on `<body>` and, when the event target is a `GatsbyImage` (or `StaticImage`), sets the `opacity` of the image's placeholder image to `0`. But because this script is appended as a `<script type="module">`, and is thus implicitly a `defer` script ([see here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-defer)), it will only run after the DOM is fully parsed (i.e., when `DOMContentLoaded` is emitted). For any images that finished loading and emitted their `load` event **before the DOM finished parsing**, the listener bound by the plugin's script will have never been called, and thus the placeholder for those images will not be faded out and will remain on the page.

### Reproduction Link

https://github.com/nonAlgebraic/eager-image-race-codition-repro

### Steps to Reproduce

I have created a minimal reproduction which features a page with a `<StaticImage>` followed by 50,000 empty `<div>`s. This virtually ensures that the image will be fully loaded before the DOM finishes parsing.

1. Clone the minimal reproduction repo and `npm install`
2. Run `npm run build`
3. Run `npm run serve`
4. Browse to the served site.

### Expected Result

The "blurred" placeholder image for the Gatsby logo is removed (i.e., faded out) once the full-resolution image is loaded.

### Actual Result

The "blurred" placeholder image is never removed.

**Note:** since this is a race condition bug, you may or may not need to refresh a couple of times to "catch" it.

Also, in order to dispel any concerns that the page is simply stalled due to the huge DOM, I included a little state-changing button to prove that the page is perfectly fine, although it may perform slowly on some machines. The button is not related to the bug at all - it's just a helpful proof that the bug is **not** a matter of the large DOM stalling the JS thread.

If you want a more concrete indication that the cause for this bug is the race condition I described above, you can:
1. manually add a `console.log('binding listener')` above [this line in the SSR script](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-image/src/gatsby-ssr.tsx)
2. manually add a 'onload="console.log('loaded')"' to the `<img>` element in the generated HTML page
3. observe that the second log is printed before the first

### Environment

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Firefox: 98.0.2
    Safari: 15.4
  npmPackages:
    gatsby: ^4.15.0-next.1 => 4.15.0-next.1
    gatsby-plugin-image: ^2.14.0 => 2.14.0
    gatsby-plugin-sharp: ^4.14.0 => 4.14.0
    gatsby-source-filesystem: ^4.14.0 => 4.14.0
    gatsby-transformer-sharp: ^4.14.0 => 4.14.0
```

**Comment by nrandell** [comment]
I think I'm seeing this as well on my dev sites. It's trying to set `root.current.innerHTML` but `root.current` is null. Downgrading to gatsby-plugin-image@2.13 works as a workaround though

**Comment by nonAlgebraic** [comment]
> I think I'm seeing this as well on my dev sites. It's trying to set `root.current.innerHTML` but `root.current` is null. Downgrading to gatsby-plugin-image@2.13 works as a workaround though

@nrandell I don't see that in the source code of the plug-in, so I'm confused as to how it could be related. Would you mind linking me to the line/lines where this is?

**Comment by nrandell** [comment]
> > I think I'm seeing this as well on my dev sites. It's trying to set `root.current.innerHTML` but `root.current` is null. Downgrading to gatsby-plugin-image@2.13 works as a workaround though
> 
> @nrandell I don't see that in the source code of the plug-in, so I'm confused as to how it could be related. Would you mind linking me to the line/lines where this is?

Have a look at    https://github.com/gatsbyjs/gatsby/blob/90e1b8a2035a20d6eda0ec9dc756d74f454fec12/packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx#L154

**Comment by nrandell** [comment]
Ok - my thinking was that if root.current was null, it means that the dom has not been loaded. I could be wrong - if so, I'm happy to raise another issue - just conscious of not raising too many issues that could be duplicates!

**Comment by roffelsaurus** [comment]
> I think I'm seeing this as well on my dev sites. It's trying to set `root.current.innerHTML` but `root.current` is null. Downgrading to gatsby-plugin-image@2.13 works as a workaround though

Seeing the exact same issue, and downgrading to 2.13 fixed it. The offending MR is #35226 which had a big rewrite and an what seems to be a usage of a useRef before assignment:

https://github.com/gatsbyjs/gatsby/pull/35226/files#diff-79ed7d705ccb6ef05727d9662082da89b5a63225c01b5f56ff48f82129527a05R154

Unfortunately I needed to stop short when trying to create a reproduction repo as it took an unfeasible amount of time for this trivial of a bug. So I guess it will stay unreported until someone less impatient than me comes along.

**Comment by nrandell** [comment]
> > I think I'm seeing this as well on my dev sites. It's trying to set `root.current.innerHTML` but `root.current` is null. Downgrading to gatsby-plugin-image@2.13 works as a workaround though
> 
> Seeing the exact same issue, and downgrading to 2.13 fixed it. The offending MR is #35226 which had a big rewrite and an what seems to be a usage of a useRef before assignment:
> 
> https://github.com/gatsbyjs/gatsby/pull/35226/files#diff-79ed7d705ccb6ef05727d9662082da89b5a63225c01b5f56ff48f82129527a05R154
> 
> Unfortunately I needed to stop short when trying to create a reproduction repo as it took an unfeasible amount of time for this trivial of a bug. So I guess it will stay unreported until someone less impatient than me comes along.

I've tried to create a minimal reproduction, but have so far failed. I've opened a discussion https://github.com/gatsbyjs/gatsby/discussions/35656 where I talk about it, but keep struggling with that reproduction.  It would be useful to add a bit more content in the discussion so at least we can help other people and potentially start to find how to reproduce it!

**Comment by runemadsen** [comment]
We're having the same issue on our production site. Images are loaded but have `opacity: 0` sitting behind a placeholder blur image.
