### ISSUE TITLE
gatsby-source-wordpress: image rewriting no longer works with the introduction of IMAGE_CDN (i.e. gatsby >= 4.10.x)

### ISSUE THREAD

**Issue by rburgst** [gatsbyjs/gatsby#35626]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

It appears that with the introduction of IMAGE_CDN the whole html image rewriting to gatsby image no longer works.

It appears that it is no longer possible to use gatsbyImage without IMAGE_CDN, the HTML content that gets rewritten appears to require gatsby functions (and probably the IMAGE_CDN) to be present.

### Reproduction Link

https://github.com/gatsbyjs/gatsby-starter-wordpress-blog

### Steps to Reproduce

1. ` npx gatsby new gatsby-starter-wordpress-blog https://github.com/gatsbyjs/gatsby-starter-wordpress-blog`
2. `cd gatsby-starter-wordpress-blog`
3. `yarn build`
4. `yarn serve`

now open the URL localhost:9000/block-image/
and inspect the HTML

### Expected Result

Images should be rewritten to static gatsby images

e.g. (this is the output with gatsby 4.9.1)
```html
<img data-gatsby-image-ssr="" data-wp-inline-image="1" data-main-image="" 
  style="height: 100%; left: 0px; position: absolute; top: 0px; transform: translateZ(0px); transition: opacity 250ms linear 0s; width: 100%; will-change: opacity; opacity: 1;" sizes="(min-width: 580px) 580px, 100vw" 
  decoding="async" loading="lazy" alt="Image Alignment 580x300" 
  src="/static/539c0066996ddbcc605b6947b35b041e/974bc/image-alignment-580x300-1.jpg" 
  srcset="/static/539c0066996ddbcc605b6947b35b041e/e72ad/image-alignment-580x300-1.jpg 145w,/static/539c0066996ddbcc605b6947b35b041e/b0e80/image-alignment-580x300-1.jpg 290w,/static/539c0066996ddbcc605b6947b35b041e/974bc/image-alignment-580x300-1.jpg 580w">
```

### Actual Result

All of the images are being rewritten to something like
```html
﻿﻿<img data-wp-inline-image="1" 
  data-main-image="" 
  style="height: 100%; left: 0px; position: absolute; top: 0px; transform: translateZ(0px); transition: opacity 250ms linear 0s; width: 100%; will-change: opacity; opacity: 0;" 
  sizes="(min-width: 580px) 580px, 100vw" 
  decoding="async" loading="lazy" 
  data-src="/_gatsby/image/406ca6ba97b4c609708eb571aa991c5e/7d9d8c0a03f4a29416110437c078ce56/image-alignment-580x300-1.jpg?u=https%3A%2F%2Fwpgatsbydemo.wpengine.com%2Fwp-content%2Fuploads%2F2013%2F03%2Fimage-alignment-580x300-1.jpg&amp;a=w%3D145%26h%3D75%26fm%3Djpg%26q%3D90" 
  data-srcset="/_gatsby/image/406ca6ba97b4c609708eb571aa991c5e/7d9d8c0a03f4a29416110437c078ce56/image-alignment-580x300-1.jpg?u=https%3A%2F%2Fwpgatsbydemo.wpengine.com%2Fwp-content%2Fuploads%2F2013%2F03%2Fimage-alignment-580x300-1.jpg&amp;a=w%3D145%26h%3D75%26fm%3Djpg%26q%3D90 145w,/_gatsby/image/406ca6ba97b4c609708eb571aa991c5e/2495b497796c4fc6b582c85dbe643ebe/image-alignment-580x300-1.jpg?u=https%3A%2F%2Fwpgatsbydemo.wpengine.com%2Fwp-content%2Fuploads%2F2013%2F03%2Fimage-alignment-580x300-1.jpg&amp;a=w%3D290%26h%3D150%26fm%3Djpg%26q%3D90 290w,/_gatsby/image/406ca6ba97b4c609708eb571aa991c5e/d0968e16e1dde1ded1f1e3f63ae649be/image-alignment-580x300-1.jpg?u=https%3A%2F%2Fwpgatsbydemo.wpengine.com%2Fwp-content%2Fuploads%2F2013%2F03%2Fimage-alignment-580x300-1.jpg&amp;a=w%3D580%26h%3D300%26fm%3Djpg%26q%3D90 580w" 
  alt="Image Alignment 580x300"
>
```

Specifically look at the image srcset url: 
http://localhost:9000/_gatsby/image/406ca6ba97b4c609708eb571aa991c5e/7d9d8c0a03f4a29416110437c078ce56/image-alignment-580x300-1.jpg

This URL does not resolve. Actually I am not even sure whether this would be taken into account anyway as the `<img` tag has no normal `src` or `srcset` tag.

### Environment

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /var/folders/9h/6y70jr3x7cb4cykkjldnppgc0000gn/T/yarn--1652203561098-0.7754946860868244/node
    Yarn: 1.22.18 - /var/folders/9h/6y70jr3x7cb4cykkjldnppgc0000gn/T/yarn--1652203561098-0.7754946860868244/yarn
    npm: 8.1.2 - ~/.volta/tools/image/node/16.13.1/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Firefox: 100.0
    Safari: 15.4
  npmPackages:
    gatsby: ^4.0.0 => 4.14.0 
    gatsby-plugin-image: ^2.0.0 => 2.14.0 
    gatsby-plugin-manifest: ^4.0.0 => 4.14.0 
    gatsby-plugin-offline: ^5.0.0 => 5.14.0 
    gatsby-plugin-react-helmet: ^5.0.0 => 5.14.0 
    gatsby-plugin-sharp: ^4.0.0 => 4.14.0 
    gatsby-source-filesystem: ^4.0.0 => 4.14.0 
    gatsby-source-wordpress: ^6.0.0 => 6.14.0 
    gatsby-transformer-sharp: ^4.0.0 => 4.14.0
```

**Comment by rburgst** [comment]
this is what the output page looks like
<img width="704" alt="image" src="https://user-images.githubusercontent.com/22971/167687301-00ea8051-0a96-4291-b531-0b4b22212156.png">

**Comment by rburgst** [comment]
reran the generated sample with the following versions
```json
    "gatsby": "4.9.1",
    "gatsby-plugin-image": "2.11.1",
    "gatsby-plugin-manifest": "4.9.1",
    "gatsby-plugin-offline": "5.9.1",
    "gatsby-plugin-react-helmet": "5.9.0",
    "gatsby-plugin-sharp": "4.9.1",
    "gatsby-source-filesystem": "4.11.1",
    "gatsby-source-wordpress": "6.9.1",
    "gatsby-transformer-sharp": "4.9.0",
```
With that all the images look good.

**Comment by veryspry** [comment]
Hey @rburgst :wave:

I just followed the reproduction steps and the images do seem to be loading correctly for me (no 404's in the network tab). The `img` tags also look okay to me. As an example, one of them looks like this:

```html
<img src="/_gatsby/file/406ca6ba97b4c609708eb571aa991c5e/image-alignment-580x300-1.jpg?u=https%3A%2F%2Fwpgatsbydemo.wpengine.com%2Fwp-content%2Fuploads%2F2013%2F03%2Fimage-alignment-580x300-1.jpg" alt="Image Alignment 580x300" class="wp-image-906 inline-gatsby-image-wrapper" data-reactroot="">
```

The images are rendering in the browser for me to:
![image](https://user-images.githubusercontent.com/21110659/168028314-9794b44b-2f9f-44ae-a58d-5f44cecdbb4b.png)

When using the `gatsbyImage` field and resolver, it is expected behavior that the image path will be `/_gatsby/image`. Can you double check that the images that are 404'ing in your browser are indeed missing from `/public/_gatsby/image` in your gatsby site directory?

Hopefully that will help narrow down where the bug is happening. Thanks!

**Comment by rburgst** [comment]
hmm, very weird. I can now see the images again. I still have a rewriting problem in my production database. Obviously its not so simple as I had thought. I will try to replicate our problem and produce a repro.

**Comment by rburgst** [comment]
I will create a new issue as the title is no longer correct
