### ISSUE TITLE
Reconciliation between routes

### ISSUE THREAD

**Issue by uttrasey** [gatsbyjs/gatsby#3563]
### Description

When `gatsby-link`ing between 2 different pages in the browser, is it possible to allow React reconciliation between the two pages? rather than what appears to be full unmount and mount (unless I'm doing something dumb).  

### Environment

Gatsby version: 1.9.150
Node.js version:  8.9.1
Operating System: MacOS 10.13.1

### File contents (if changed):

Example repo demonstrating the issue here https://github.com/uttrasey/gatsby-reconciliation-demo

In any Gatsby project create 2 pages with links between them. 

#### src/pages/a.js

```js
import React from 'react'
import PropTypes from 'prop-types'
import Link from 'gatsby-link'

class Page extends React.Component {
  constructor(props) {
    super(props)
    console.log(
      `goal is for this to be called once only when flicking between 'a' to 'b'`
    )
  }

  render() {
    return (
      <div>
        <h1>
          Page that links to <b>{this.props.link}</b>
        </h1>
        <Link to={this.props.link || `/b`}>Goto B</Link>
      </div>
    )
  }
}

Page.defaultProps = {
  link: `/b`,
}

Page.propTypes = {
  link: PropTypes.string.isRequired,
}

export default Page
```

#### src/pages/b.js

```js
import React from 'react'
import Link from 'gatsby-link'
import Page from './a'

export default () => <Page link="/a" />
```

### Actual result

When clicking to navigate from `/a` to `/b` and vice versa the `Page` constructor is called and the previous page tree is entirely torn down before the new one is mounted.

### Expected behavior

Previous page component tree to be reconciled.

### What should happen?

Previous page component tree to be reconciled.

### Steps to reproduce

1\. Add the 2 pages listed above to a gatsby project

2\. Navigate to `/a` then use the link to go to `/b` and then that pages link to go back to `/a`

3\. Notice constructor log occurs twice

**Comment by uttrasey** [comment]
I just read through this https://github.com/gatsbyjs/gatsby/issues/1866 and sounds like it's off the table.

**Comment by KyleAMathews** [comment]
Yeah... it might be possible to add as an opt-in mode but as a default, it was pretty confusing to people https://github.com/gatsbyjs/gatsby/issues/1866#issuecomment-332693153

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
