### ISSUE TITLE
Develop/Build fails on `extracting-queries` with latest Gatsby (glob 7.2.2)

### ISSUE THREAD

**Issue by linfordbacon-ngenius** [gatsbyjs/gatsby#35654]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When attempting to use the YARN package manager, the gatsby develop server fails on the `extract queries from components` step with the error message:

Missing onError handler for invocation 'extracting-queries', error was 'TypeError: Cannot read properties of undefined (reading 'charAt')'. Stacktrace was 'TypeError: Cannot read properties of undefined        
(reading 'charAt')

### Reproduction Link

https://www.gatsbyjs.com/docs/tutorial/part-1/

### Steps to Reproduce

1. Install gatesby
2. run `gatesby new`
3. select 'yarn' as package manager (or ensure you have set this previously)
4. run `gatesby develop`
5. observe error

### Expected Result

Several things:
1. gatesby development server should start
2. gatesby should provide a more useful error message

### Actual Result

```
Missing onError handler for invocation 'extracting-queries', error was 'TypeError: Cannot read properties of undefined (reading 'charAt')'. Stacktrace was 'TypeError: Cannot read properties of undefined        
(reading 'charAt')
    at GlobSync._processReaddir (C:\Users\...\gatsby test\gatsby_yarn\node_modules\glob\sync.js:148:35)
    at GlobSync._process (C:\Users\...\gatsby test\gatsby_yarn\node_modules\glob\sync.js:132:10)
    at new GlobSync (C:\Users\...\gatsby test\gatsby_yarn\node_modules\glob\sync.js:45:10)
    at Function.sync (C:\Users\...\gatsby test\gatsby_yarn\node_modules\glob\sync.js:23:10)
    at reduce (C:\Users\...\gatsby test\gatsby_yarn\node_modules\gatsby\src\query\query-compiler.js:128:15)
    at Array.reduce (<anonymous>)
    at parseQueries (C:\Users\...\gatsby test\gatsby_yarn\node_modules\gatsby\src\query\query-compiler.js:126:5)
    at compile (C:\Users\...\gatsby test\gatsby_yarn\node_modules\gatsby\src\query\query-compiler.js:65:25)
    at updateStateAndRunQueries (C:\Users\...\gatsby test\gatsby_yarn\node_modules\gatsby\src\query\query-watcher.ts:223:40)
    at extractQueries (C:\Users\...\gatsby test\gatsby_yarn\node_modules\gatsby\src\services\extract-queries.ts:18:3)'

⠙ extract queries from components
```

### Environment

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics         
  Binaries:
    Node: 18.1.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.8.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.10.4
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (101.0.1210.39)
  npmPackages:
    gatsby: ^4.14.0 => 4.14.0 
    gatsby-plugin-emotion: ^7.14.0 => 7.14.0 
  npmGlobalPackages:
    gatsby-cli: 4.14.0
```

### Config Flags

No

**Comment by barbalex** [comment]
I ran into this after updating gatsby from v4.13.1 to 4.14.0

**Comment by barbalex** [comment]
So I reverted to the version that had last worked, using it's yarn.lock.
Project still has this issue.

I'm fucked.

**Comment by linfordbacon-ngenius** [comment]
Yeah, same. It seems like you end up in a completely unrecoverable state.

You could try `gatsby clean` but that didn’t work for me.

mine thing I forgot to mention is that I’m using the `emotion` plug-in but I really don’t think that’s the culprit.

**Comment by yolomep** [comment]
yeah I have the same issue. Probably should not have updated gatsby cli.

**Comment by draghia-andrei** [comment]
Same issue after updating gatsby from v4.13.1 to 4.14.0.
I am using "npm" and also Windows OS.
Version of "glob" library is 7.2.2
`gatsby clean` didn't` fix it.

**Comment by duongthaicuong** [comment]
Yeah, same
`"gatsby": "^3.8.1"`

**Comment by djwinston** [comment]
@draghia-andrei Thanks. You right. 
gatsby 4.13.0 has devDependencies "glob": "^7.1.7".  
gatsby 4.14.0 has devDependencies "glob": "^7.2.0" , so `^` installed glob 7.2.2 which published a day ago

I guess to overrides glob only for gatsby
`
 "overrides": {
    "gatsby": {
      "glob": "7.2.0"
    }
  }
`

**Comment by Alexyoe** [comment]
Same issue. Glob fix doesn't seem to help.
`"gatsby": "^4.12.1"`

**Comment by djwinston** [comment]
@alexyo

> Same issue. Glob fix doesn't seem to help. `"gatsby": "^4.12.1"`

Did you try to remove `node_modules` `package-lock.json` and reinstall packages with overrides section ? Probably `package-lock.json` has gatsby 4.14.0 and glob 7.2.2 because record `"^4.12.1"`  means that package manager can install latest major version

**Comment by M4ss1ck** [comment]
Hi.
I'm using `pnpm` and getting the exact same error. Setting `"overrides"` in `package.json` didn't work for me.
It's a fresh install: I did `pnpm init gatsby`, then `pnpm i` and I'm getting this error with `gatsby develop` and `gatsby build`

**Comment by mbrinkl** [comment]
I had to update npm to get the "overrides" to work properly. As per this issue ( https://github.com/npm/cli/issues/4322 ) it should work properly as of npm@8.6.0. That fixed it for me.

**Comment by djwinston** [comment]
@M4ss1ck Exactly. overrides introduced in config of [package.json v8.x ](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) npm v8.x and this solution related to author issue

my environment
```
gatsby info

  System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.10.2
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (101.0.1210.47)
  npmPackages:
    gatsby: ^4.14.0 => 4.14.0
    gatsby-plugin-image: ^2.14.1 => 2.14.1
    gatsby-plugin-manifest: ^4.14.0 => 4.14.0
    gatsby-plugin-react-helmet: ^5.14.0 => 5.14.0
    gatsby-plugin-sass: ^5.14.0 => 5.14.0
    gatsby-plugin-sharp: ^4.14.1 => 4.14.1
    gatsby-plugin-sitemap: ^5.14.0 => 5.14.0
    gatsby-source-filesystem: ^4.14.0 => 4.14.0
    gatsby-transformer-sharp: ^4.14.0 => 4.14.0
  npmGlobalPackages:
    gatsby: 4.14.0
```

**Comment by King-Mufasa** [comment]
Same issue,  is there any solution for this error?

**Comment by linfordbacon-ngenius** [comment]
So I've tried out the glob override fixed proposed by @draghia-andrei (thanks!) and that seems to work well.

I'll update the name of the issue as it doesn't seem to be Yarn related (although using `yarn`/ `pnpm` seems to break the build immediately from `gatsby new` whereas using `npm` seems to work until you add additional dependencies)

**Comment by pieh** [comment]
Are you all on Windows by any chance? I'm looking into `glob` changes recently and do see Windows specifically mentioned ( https://github.com/isaacs/node-glob/commits/v7.2.3 )

**Comment by pieh** [comment]
Ok, I tested on Windows and here are results:

When using `glob@7.2.3`, things work. Forcing `glob@7.2.2` result in reported error.

So there was breakage happening upstream package, but it was fixed since then (`7.2.3` was released ~20h ago).

As a way to force package managers to bump you have options (one of)):
 - drop lock file and let package manager install latest of everything
 - use something like yarn resolutions or npm overrides to force installation of `glob@7.2.3` (and then you can probably get rid of the resolution / override as that version should be set in lock file)

We will bump our deps to use `^7.2.3` and release new stable with it (tho at this point when package was already fixed upstream, this will just help folks that already hit it, and you can use workarounds above until bump happen on `gatsby` side)

**Comment by pieh** [comment]
Just for reference - this issue was reported in upstream https://github.com/isaacs/node-glob/issues/471 and https://github.com/isaacs/node-glob/issues/474 and both are resolved with `glob@7.2.3` release

**Comment by pieh** [comment]
Published patch of gatsby (`4.14.1`) that bumps minimal requirerment for `glob` to not allow `glob@7.2.2` - https://www.runpkg.com/?gatsby@4.14.1/package.json#101

**Comment by engineergit** [comment]
> Mufasa

Which version did you use then?
I have downgraded and upgraded version of gatsby many times but still stuck here.
My build doesn't get failed it is just keep running with the message extracting-queries .

**Comment by SergiOca87** [comment]
Same issue here, endless "extract queries form components"
