### ISSUE TITLE
gatsby develop results in Connection error at createSchemaCustomization

### ISSUE THREAD

**Issue by Reva118** [gatsbyjs/gatsby#35662]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

After installing gatsby-source-contentful, gatsby develop command throws connection error at createSchemaCustomization
<img width="328" alt="image" src="https://user-images.githubusercontent.com/105613303/168500165-4628c091-4f78-4d26-ba36-508c395399aa.png">

<img width="379" alt="image" src="https://user-images.githubusercontent.com/105613303/168500140-545fece6-52b6-4783-9884-be853133aa45.png">

### Reproduction Link

na

### Steps to Reproduce

1. Greate new Gatsby site using Gatsby new command (gatsby develop - works)
2. npm install gatsby-source-contentful
3. Add space and Accesstoken in gatsby-config.js 
4. Run gatsby develop
...

### Expected Result

It should start local development server

### Actual Result

Connection Error - createSchemaCustomization not finished

### Environment

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.1
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.47)
  npmPackages:
    gatsby: ^4.14.0 => 4.14.0 
    gatsby-plugin-image: ^2.14.1 => 2.14.1 
    gatsby-source-contentful: ^7.12.0 => 7.12.0 
  npmGlobalPackages:
    gatsby-cli: 4.14.0
```

**Comment by pieh** [comment]
I tested baseline (site using contentful we use for e2e tests) and that seems to work (on Mac and Windows).

This seems like connection to Contentful APIs can't be established so it's more on your side of things:
 - it could be flaky internet connection (if it happens sometimes but not alway)
 - might be use of proxies or VPNs that is not exactly playing nice?

The screenshot with error specifically mention `ENOTFOUND` which is related to your network (can't resolve hostname?)
