### ISSUE TITLE
Optimize inlined webpack manifest

### ISSUE THREAD

**Issue by szimek** [gatsbyjs/gatsby#3567]
Current Gatsby inlines webpack manifest than includes entries for all generated pages. It looks like this:
```js
window.webpackManifest = {
  "231608221292675": "app-fb486cd66ee7dc210c02.js",
  "201563372448855": "component---src-templates-index-jsx-31455cbc54628eb22eac.js",
  "129745722219136": "component---src-templates-category-jsx-ae1a7dcca9d0ee6f61fc.js",
  "213130420965792": "component---src-templates-post-jsx-72785cb602b4a3d338e6.js",
  "183328146348521": "component---src-pages-404-jsx-4503918ea3a16cfcdb75.js",
  "60335399758886": "path----557518bd178906f8d58a.js",
  "163376924989756": "path---de-blog-e1772e4651ca75976ba1.js",
  "5520618729643": "path---de-blog-page-2-ea7fe874aa743d63b0b0.js",
  "37430569857568": "path---de-blog-page-3-bf1cd84edfc64475e2d9.js",
  "146399927938408": "path---de-blog-page-4-e24838adf248f481bc79.js",
  "158433505380798": "path---de-blog-page-5-59288192b67682fb9ea1.js",
  "163364179272051": "path---de-blog-page-6-4e2a080ea6106a53e483.js",
  ...
};
```
It's used e.g. to preload code for all pages that are linked to on the current page to speed up opening new pages.

The issue is that when there are a lot of pages, e.g. a few thousand, this manifest gets pretty big (one entry in my case has ~65 bytes; times e.g. 5000 pages gives 325kB) and it's inlined into every generated page. Not only it makes the first page slower to load, but the build itself gets huge because of it as well.

Maybe there's some way to either get rid of it completely or reduce its size, by e.g. inlining only the paths to pages that are linked to on the current page and somehow updating this manifest as new pages are loaded.

CC @TheLarkInn

**Comment by szimek** [comment]
@KyleAMathews It looks like it's a (kind of) duplicate of https://github.com/gatsbyjs/gatsby/issues/3574. Close it if you think it doesn't make sense to keep both tickets opened.

**Comment by KyleAMathews** [comment]
Yeah, I'll close this one. Thanks for writing it up.
