### ISSUE TITLE
gatsby develop doesn't work with special characters in dir name

### ISSUE THREAD

**Issue by IamSoPrada** [gatsbyjs/gatsby#35690]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

"gatsby develop" doesn't build app if you have special characters (Russian letters) in dir name. But it works if you change the directory with only English letters.

Not working : C:\Users\100go\Desktop\Пpoекты\Проекты Gatsby\gatsby-2

Worked perfect : C:\Users\100go\Desktop\test-dir

![FS-Bx8aXwAApV5g](https://user-images.githubusercontent.com/64264723/169089068-52e2c645-2c20-47ca-8b49-94fd58779f73.png)

### Reproduction Link

na

### Steps to Reproduce

1. clone gatsby starter kit to the folder named in Russian or with some special characters.
2. gatsby develop
3. 
...

### Expected Result

Build and start app in development mode.

### Actual Result

ERROR#11903 COMPILATION
Error:Error opening directory
not finished compile gatsby files-1.022s

### Environment

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (100.0.1185.39)
  npmGlobalPackages:
    gatsby-cli: 4.14.0
```

**Comment by KyleAMathews** [comment]
Sorry you ran into this! Could you put in the issue description the exact directory name you used?
