### ISSUE TITLE
NPM `gatsby-theme-i18n` package point to wrong place in github

### ISSUE THREAD

**Issue by lambdaxyzt** [gatsbyjs/gatsby#35712]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

NPM `gatsby-theme-i18n` package point to wrong place in github
error 404 not found !!!

### Steps to Resolve this Issue

go to NPM `gatsby-theme-i18n` package page click github link

**Comment by LekoArts** [comment]
Hi!

It points to the correct place but for some reason the algolia npm search doesn't update it: https://github.com/gatsbyjs/themes/blob/master/packages/gatsby-theme-i18n/package.json#L29

It'll get updated eventually but for now this is an upstream issue we sadly can't fix as the source is already correct.

**Comment by cesarvarela** [comment]
<img width="827" alt="image" src="https://user-images.githubusercontent.com/1172479/172927760-66f64f75-5c3f-4a05-9dfd-fa55a08c5486.png">


The `View plugin on Github` link points to the wrong place too.
