### ISSUE TITLE
webpack loading error after deployed

### ISSUE THREAD

**Issue by ktei** [gatsbyjs/gatsby#3572]
Hi, I run `gatsby build` and deployed all the files, but when I open the website [http://ktei.github.io/](http://ktei.github.io/), I sometimes (very often actually) got this JS error:

<img width="1251" alt="screen shot 2018-01-18 at 10 54 43 am" src="https://user-images.githubusercontent.com/2195250/35075185-be027e40-fc45-11e7-9c4d-e77331bc3ac7.png">

And this is what sourcemaps told me:

<img width="762" alt="screen shot 2018-01-18 at 11 50 57 am" src="https://user-images.githubusercontent.com/2195250/35075208-e3d8d308-fc45-11e7-91c5-7a292317f7c1.png">

And my page is only half rendered: only the top navbar is shown, the rest of the page being blank.
It seems a webpack module is missing but I can't find out the reason.

Also, When I run `gatsby serve` to serve my website locally, I have this error on localhost:9000 as well, usually after I refresh the page, but my page shows up properly.

Does this ring a bell? Or this is just me doing something wrong...
https://github.com/ktei/ktei.github.io/tree/develop

Thank you very much.

**Comment by KyleAMathews** [comment]
Hi! Sorry about that — we merged a PR a few days ago that caused this. Luckily we also just merged a fix a few minutes ago so if you update to the latest Gatsby you'll be fine again :-) https://github.com/gatsbyjs/gatsby/issues/3568
