### ISSUE TITLE
Gatsby config fails to load during Gatsby Cloud GitHub checks, not consistent.

### ISSUE THREAD

**Issue by kevinhaube** [gatsbyjs/gatsby#35740]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When the build process kicks off as part of a PR, most of the time it results in passing checks, but on occasion it'll fail on `load gatsby config` and I get the following message from Gatsby Cloud:

![Screenshot 2022-05-24 200246](https://user-images.githubusercontent.com/4022304/170151150-6bd6148b-9c13-424e-a777-3e81d0064be2.png)

After clearing the cache and re-building through Gatsby, everything is fine. Build locally does not fail, either. This seems related to caching through Gatsby Cloud, and old vs new builds, maybe losing track of dependencies along the way.

### Reproduction Link

https://github.com/kevinhaube/dev-blog

### Steps to Reproduce

[This link](https://www.gatsbyjs.com/dashboard/30906204-0f64-4f99-b88d-178d1c8a6ca2/sites/9dab10ee-61b9-4350-ad05-c097fd58f875/builds/8f47bab5-84ee-4ba2-8f69-3832ef8a244c/details#errors) shows the most recent failures. Feel free to open a PR on my repo and try to get those checks to run and fail. 

### Expected Result

Config should load fresh every time.

### Actual Result

Errors loading config some of the time.

### Environment

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1.0), Chromium (101.0.1210.39)
  npmPackages:
    gatsby: ^4.14.1 => 4.14.1 
    gatsby-plugin-dts-css-modules: ^2.2.0 => 2.2.0 
    gatsby-plugin-mdx: ^3.14.0 => 3.14.0 
    gatsby-plugin-netlify-cms: ^6.14.0 => 6.14.0 
    gatsby-plugin-react-helmet: ^5.14.0 => 5.14.0 
    gatsby-plugin-styled-components: ^5.14.0 => 5.14.0 
    gatsby-source-filesystem: ^4.14.0 => 4.14.0
```

**Comment by LekoArts** [comment]
Hi! For Gatsby Cloud related issues please contact our support here: https://www.gatsbyjs.com/support/

Thanks!
