### ISSUE TITLE
Increase webpack build speeds and decrease webpack manifest size by handling loading page data (from GraphQL queries) ourselves

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#3574]
Currently we load data results from GraphQL through webpack.

This has a few negatives effects:

* Slows "hot reloading" of data when developing
* Slows webpack builds as webpack has to handle an extra file / page. This can be considerable. E.g. imagine a blog with 1000 posts. The blog might use ~10 components to power the site. That plus dependencies might be ~100 modules. The 1000 blog posts require a "module" per graphql result so end up being 90.9% of modules.
* Bloats the webpack manifest. Webpack requires a "manifest" of all entry/async modules. For a large site of ~5000 pages, this ends up around ~300kb (uncompressed) — so a lot. By handling things ourselves, we could lazy load our own "manifest" for page data a lot more cheaply.

**Comment by KyleAMathews** [comment]
Hey, we did this! @m-allanson @pieh

**Comment by leonfs** [comment]
@KyleAMathews - Quick question: there is an issue (#3567) that talks about fixing the large size of the webpack pages-manifest. We have a moderate site (around 1K pages) and the manifest is bigger than the main app itself. You mentioned in your comment that you did it, is there a link to the documentation on how to split that manifest?

**Comment by KyleAMathews** [comment]
You're in v2 I assume? There is still a page manifest there. @Moocar is actually close to fixing that see his meta-pr https://github.com/gatsbyjs/gatsby/pull/13004
