### ISSUE TITLE
Prop name and markdown key mismatch in "working with video" documentation

### ISSUE THREAD

**Issue by aghreed** [gatsbyjs/gatsby#35750]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

In short, there's a typo in the markdown document in use on this page, which lists the property `videoSourceURL`, when the usage of those in code is under the prop name `videoSrcURL`. This can lead to a frustrating experience following along if you're copying and pasting the examples to your own code editor.

### Steps to Resolve this Issue

1. Find the page in the docs here (https://github.com/gatsbyjs/gatsby/blob/21567d41a528c7dcad0262eb9b95c28bd946529f/docs/docs/how-to/images-and-media/working-with-video.md#L2)
2. Update the key in the markdown document to match the props
3. Open a PR!

**Comment by paulreece** [comment]
Hi I just created a PR for this here. https://github.com/gatsbyjs/gatsby/pull/35764

**Comment by paulreece** [comment]
@aghreed Let me know if I need to change anything, thanks for your time.
