### ISSUE TITLE
Add peerDependencies to every plugin

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#3575]
Going forward, we'll be doing every so often major releases for Gatsby but individual plugins might not need upgraded as the APIs they depend on won't have changed. We should prepare for that now by adding a `peerDependencies` for Gatsby to every plugin. Then when there is a breaking change that affects the plugin or there's a new major release of Gatsby, we update the peerDependencies for the plugin.

**Comment by tsriram** [comment]
If it's still not taken up by anyone, I'd like to take this up.

**Comment by KyleAMathews** [comment]
Nope, have at it!

**Comment by tsriram** [comment]
Awesome! What version should be set as the peer dependency now - the latest one on npm v1.9.164?

**Comment by KyleAMathews** [comment]
Just do `^1.0.0` to keep things simple.
