### ISSUE TITLE
[gatsby-config] ERROR #10124 Please rename "gatsby-config.ts" to "gatsby-config.js"

### ISSUE THREAD

**Issue by tmkasun** [gatsbyjs/gatsby#35768]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I have initialized a Gatsby project using the typescript template
```
npm init gatsby -ts
```
I was able to run the project for the first time without any issues
```
npm start
```
But thereafter I couldn't run `start`, `develop` or `build` commands, as I'm getting the following error for all those commands

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/3313885/170825794-1bc0cb91-c009-4cc1-89db-01279eccfda3.png">

But I was able to run any command after cleaning the cache 
```
npm run clean
```

and has to run it every time after running any of the `start`, `develop` or `build` commands

### Reproduction Link

N/A

### Steps to Reproduce

1.  Initialize a new gatsby ts project
```
npm init gatsby -ts
```
2. Start the development server for the first time
```
npm start
```
3. Stop the server
4. Start the development server again
```
npm start
```
5. Command will fail with 
```
 ERROR #10124  CONFIG
 ```

### Expected Result

`start`, `develop` & `build` commands should be able to run without clearing the cache every time

### Actual Result

Have to run 

```
npm run clean
```

everytime before running `start`, `develop` & `build` commands

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    gatsby: ^4.15.0 => 4.15.1
    gatsby-plugin-google-analytics: ^4.15.0 => 4.15.0
    gatsby-plugin-image: ^2.15.0 => 2.15.0
    gatsby-plugin-manifest: ^4.15.0 => 4.15.0
    gatsby-plugin-mdx: ^3.15.0 => 3.15.0
    gatsby-plugin-react-helmet: ^5.15.0 => 5.15.0
    gatsby-plugin-sharp: ^4.15.0 => 4.15.0
    gatsby-plugin-sitemap: ^5.15.0 => 5.15.0
    gatsby-plugin-styled-components: ^5.15.0 => 5.15.0
    gatsby-source-filesystem: ^4.15.0 => 4.15.0
    gatsby-transformer-remark: ^5.15.0 => 5.15.0
    gatsby-transformer-sharp: ^4.15.0 => 4.15.0
```

### Config Flags

import type { GatsbyConfig } from "gatsby";

const config: GatsbyConfig = {
  siteMetadata: {
    title: `My little corner in the Web`,
    siteUrl: `https://me.knnect.com`,
    description: `Kasun Thennakoon's personal web`,
  },
  plugins: ["gatsby-plugin-styled-components", {
    resolve: 'gatsby-plugin-google-analytics',
    options: {
      "trackingId": "foo"
    }
  }, "gatsby-plugin-image", "gatsby-plugin-react-helmet", "gatsby-plugin-sitemap", {
    resolve: 'gatsby-plugin-manifest',
    options: {
      "icon": "src/images/icon.png"
    }
  }, "gatsby-plugin-mdx", "gatsby-transformer-remark", "gatsby-plugin-sharp", "gatsby-transformer-sharp", {
    resolve: 'gatsby-source-filesystem',
    options: {
      "name": "images",
      "path": "./src/images/"
    },
    __key: "images"
  }, {
    resolve: 'gatsby-source-filesystem',
    options: {
      "name": "pages",
      "path": "./src/pages/"
    },
    __key: "pages"
  }]
};

export default config;

**Comment by tyhopp** [comment]
Hi @tmkasun!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

[reproduction]: https://gatsby.dev/reproduction

**Comment by tmkasun** [comment]
Hi @tyhopp ,

Thank you for your reply, I actually tried to get a reproducible project, since you have asked for it in the issue template `Reproduction Link`, But this is what happened.

- I initialized a new project in `/tmp/`(MacOS) directory, and tried the above erroneous path, There it worked without any issue.
- Then tried to initialize a new project `npm init gatsby` in a different directory, and it also worked without any issue (I actually continue using that project thereafter) 

So, I'm not sure why this typescript issue occurs only in a specific directory path, Could be due to some npm dependency conflicts.
I can push the faulty project code to a repo and share it with you, But I doubt whether it will cause the same error in your local machine?

**Comment by tyhopp** [comment]
Hi @tmkasun, if you can't reproduce it in a different directory then it may be related to your environment.

For context the error you encountered is thrown [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/bootstrap/get-config-file.ts#L78-L86), where it attempts to check for a `gatsby-config.js` file in the root of your site because it couldn't find the compiled `gatsby-config` file in `.cache/compiled/gatsby-config`.

Can you check in your site that has this issue whether the config file exists at `.cache/compiled/gatsby-config` when the error is thrown?

The "It looks like you were trying to add the config file? ..." error message is a little misleading for this case so we may want to add a case or adjust the message.

**Comment by tyhopp** [comment]
Related to compiled `gatsby-config` error handling https://github.com/gatsbyjs/gatsby/pull/35038

**Comment by tmkasun** [comment]
Hi @tyhopp ,

Thank you for the insights, 

> Can you check in your site that has this issue whether the config file exists at .cache/compiled/gatsby-config when the error is thrown?

Yes, you are correct, 
```
<PROJECT_ROOT>/.cache/compiled/
```
directory does not have any files at the time I get the 
```
It looks like you were trying to add the config file? Please rename "gatsby-config.ts" to "gatsby-config.js"
```
error.

I have to delete the `.cache` directory and rerun the build to get it working, But only for 1 time, after 1st run, I have to clear the `.cache` directory again.

**Comment by kevinhaube** [comment]
Interested to see if this fixes a similar issue that I thought was related to GastbyCloud; same error message.
