### ISSUE TITLE
Jest tests are broken with Gatsby 4.15.1

### ISSUE THREAD

**Issue by feedm3** [gatsbyjs/gatsby#35778]
### Description

Our jest tests are broken after the update to Gatsby 4.15.1. It is due to `gatsby-script` being imported as ES module.

![Screenshot 2022-05-30 at 11 45 11](https://user-images.githubusercontent.com/7814926/170966591-d1b23855-1f85-40d3-b35d-aeb857a9a361.png)

The Gatsby Docs are already updated with this error here: https://github.com/gatsbyjs/gatsby/pull/35744 but the problem still occurs even after updating our jest config. We copied the `transformIgnorePatterns` directly from the docs, this is what our jest config looks like:

```js
module.exports = {
  preset: "ts-jest",
  testEnvironment: "jsdom",
  testPathIgnorePatterns: [`node_modules`, `\\.cache`, `<rootDir>.*/public`],
  transformIgnorePatterns: [`node_modules/(?!(gatsby|gatsby-script)/)`],
  setupFiles: ["<rootDir>/jest/loadershim.ts"],
  setupFilesAfterEnv: ["<rootDir>/jest/setup-jest.ts"],
  globals: {
    "ts-jest": {
      // rewrite locale ts-config to work with ts-jest
      tsconfig: {
        allowJs: false,
        jsx: "react",
      },
    },
  },
  moduleNameMapper: {
    "\\.(css|less)$": "identity-obj-proxy",
    "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$":
      "<rootDir>/__mocks__/fileMock.js",
  },
};
```

### Reproduction link
[codesandbox.io/s/gatsby-4-15-1-jest-error-yh6o3b?file=/src/components/button.test.tsx](https://codesandbox.io/s/gatsby-4-15-1-jest-error-yh6o3b?file=/src/components/button.test.tsx)

### Expected Result

Jest tests run successfully as they did with Gatsby 4.14.0

### Actual Result

Jest tests are broken.

### Environment

```shell
System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 100.0.2
    Safari: 15.5
  npmPackages:
    gatsby: ^4.15.1 => 4.15.1
    gatsby-plugin-gatsby-cloud: ^4.15.0 => 4.15.0
    gatsby-plugin-image: ^2.15.0 => 2.15.0
    gatsby-plugin-manifest: ^4.15.0 => 4.15.0
    gatsby-plugin-meta-redirect: ^1.1.1 => 1.1.1
    gatsby-plugin-react-helmet: ^5.15.0 => 5.15.0
    gatsby-plugin-robots-txt: ^1.7.1 => 1.7.1
    gatsby-plugin-schema-snapshot: ^3.15.0 => 3.15.0
    gatsby-plugin-sitemap: ^5.15.0 => 5.15.0
    gatsby-plugin-styled-components: ^5.15.0 => 5.15.0
    gatsby-source-contentful: 7.13.0 => 7.13.0
    gatsby-source-filesystem: ^4.15.0 => 4.15.0
```

**Comment by LekoArts** [comment]
Hi!

It worked fine for me on my update: https://github.com/LekoArts/portfolio-v2/pull/43/files

So we'll need a minimal reproduction showing this problem.

**Comment by feedm3** [comment]
Here it is: https://codesandbox.io/s/gatsby-4-15-1-jest-error-yh6o3b?file=/src/components/button.test.tsx

I used the Gatsby Starter for it and removed some stuff that is not relevant. 

The test I created is super simple and just imports a trivial `button` component. As soon as I imported `import { navigate } from "gatsby"` the tests broke. All dependencies are up-to-date.


<details>
<summary>Screenshot</summary>
<img width="500" src="https://user-images.githubusercontent.com/7814926/170985974-1397af4a-3cfa-4fd0-994d-c746d542d580.png">
</details>

**Comment by tyhopp** [comment]
Hi @feedm3, in your reproduction the `transform` key is missing from the Jest config (and `gatsby-script` missing in `transformIgnorePatterns`):

```
transform: {
  "^.+\\.jsx?$": `<rootDir>/jest/jest-preprocess.js`
},
```

I forked the sandbox, added this and the preprocess file (can be copied from the [docs](https://www.gatsbyjs.com/docs/how-to/testing/unit-testing/#2-creating-a-configuration-file-for-jest)) and the tests pass - https://codesandbox.io/s/gatsby-4-15-1-jest-error-forked-myp1ck?file=/jest.config.js

**Comment by feedm3** [comment]
Oh man 🙈 Thanks a lot @tyhopp, tests are working now 🙂

**Comment by tyhopp** [comment]
Glad it worked out @feedm3!
