### ISSUE TITLE
[gatsby-source-contentful] `proxy.protocol` is not considered as a valid option

### ISSUE THREAD

**Issue by mwskwong** [gatsbyjs/gatsby#35774]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

According to Axios document and example https://github.com/axios/axios#request-config, `protocol` should be a valid option in `proxy` but `gatsby-source-contentful` thinks otherwise and return an error when such an option is specified.

See the source code of  `gatsby-source-contentful` 
https://github.com/gatsbyjs/gatsby/blob/1ea9358e1943f494608bf4523e3fda2f461560a0/packages/gatsby-source-contentful/src/gatsby-node.js#L125

### Reproduction Link

N/A

### Steps to Reproduce

1. Use `gatsby-source-contentful`
2. Specify the `proxy` option
3. Specify the `protocol` option in `proxy`

### Expected Result

`protocol` should be accepted and passed to Axios.

### Actual Result

`protocol` is rejected and an error is returned

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
  Binaries:
    Node: 17.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.53)
  npmPackages:
    gatsby: ^4.15.1 => 4.15.1 
    gatsby-plugin-emotion: ^7.15.0 => 7.15.0 
    gatsby-plugin-image: ^2.15.0 => 2.15.0 
    gatsby-plugin-manifest: ^4.15.0 => 4.15.0 
    gatsby-plugin-material-ui: ^4.1.0 => 4.1.0 
    gatsby-plugin-netlify: ^5.0.0 => 5.0.0 
    gatsby-plugin-offline: ^5.15.0 => 5.15.0 
    gatsby-plugin-perf-budgets: ^0.0.18 => 0.0.18 
    gatsby-plugin-react-helmet: ^5.15.0 => 5.15.0 
    gatsby-plugin-robots-txt: ^1.7.1 => 1.7.1 
    gatsby-plugin-sharp: ^4.15.0 => 4.15.0 
    gatsby-plugin-sitemap: ^5.15.0 => 5.15.0 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.27 => 1.1.27 
    gatsby-source-contentful: ^7.13.0 => 7.13.0 
    gatsby-source-filesystem: ^4.15.0 => 4.15.0 
    gatsby-transformer-sharp: ^4.15.0 => 4.15.0
```

### Config Flags

FAST_DEV: true,
PARALLEL_SOURCING: true,
PRESERVE_FILE_DOWNLOAD_CACHE: true

**Comment by LekoArts** [comment]
For anyone who wants to pick this up:

It's a matter of adding `proxy` to this `keys` object:

https://github.com/gatsbyjs/gatsby/blob/1ea9358e1943f494608bf4523e3fda2f461560a0/packages/gatsby-source-contentful/src/gatsby-node.js#L126-L132

**Comment by andrmaz** [comment]
@LekoArts Can I handle this ? I would love to start contributing

**Comment by Timxyx** [comment]
I will work on this if it hasn't already been fixed.
