### ISSUE TITLE
accessing directories in theme

### ISSUE THREAD

**Issue by joshuacox** [gatsbyjs/gatsby#35784]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

When following the [building a theme](https://www.gatsbyjs.com/tutorial/building-a-theme/) doc, I run into this error after the step where you add the data directory:

```
The path passed to gatsby-source-filesystem does not exist on your file system:
data                                                                                                                                                                                      
Please pick a path to an existing directory.   
```

### Steps to Resolve this Issue

1. Follow the [tutorial](https://www.gatsbyjs.com/tutorial/building-a-theme/)
2. At the step when building the data directory you'll run into the error
3. Here is a [gist](https://gist.github.com/joshuacox/d2635f63797907a64a4194ac8f4f44a9) that duplicates the steps I have taken.

I think the most significant difference is that this is gatsby 4 and not 3:
```
{
  "private": true,
  "name": "site",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "clean": "gatsby clean"
  },
  "dependencies": {
    "gatsby": "^4.15.1",
    "gatsby-theme-events": "*",
    "react": "^18.1.0",
    "react-dom": "^18.1.0"
  }
}
```

**Comment by tyhopp** [comment]
Hi @joshuacox, I reproduced this and the [building a theme](https://www.gatsbyjs.com/tutorial/building-a-theme/) doc needs an update to include the full path to the `data` directory to match the usage instructions in [`gatsby-source-filesystem`](https://www.gatsbyjs.com/plugins/gatsby-source-filesystem/):

```js
module.exports = {
  plugins: [
    {
      resolve: "gatsby-source-filesystem",
      options: {
        name: `data`,
        path: `${__dirname}/data/`,
      },
    },
    {
      resolve: "gatsby-transformer-yaml",
      options: {
        typeName: "Event",
      },
    },
  ],
};
```

If anyone wants to pick this up, the page could also use an update to show the latest dependencies in the package.json snippets.

**Comment by joshuacox** [comment]
@tyhopp confirmed working, tyvm.   Here's your requested [PR](https://github.com/gatsbyjs/gatsby/pull/35792)
