### ISSUE TITLE
What is the proper upgrade routine?

### ISSUE THREAD

**Issue by everdimension** [gatsbyjs/gatsby#358]
If I install a newer version of `gatsbyjs`, should I / can I upgrade the project I am already working on?

**Comment by KyleAMathews** [comment]
Do you mean when you install a newer "global" version of Gatsby? If that's the case, the global Gatsby install always defers to the local install so you don't need to worry about upgrading the actual project you're working on.

So if something is working, there's no need to upgrade really. That being said, you can read the release notes on newer versions and see if there's anything that tempts an upgrade. There might be new features or bug fixes that affect you. Typically upgrades are fairly painless as well.

**Comment by everdimension** [comment]
> the global Gatsby install always defers to the local install 

Just noticed that after I posted. An idea: why don't you ship the `package.json` with the `develop` and `build` scripts added so that someone who doesn't have `gatsby` installed globally can collaborate on a gatsby project, too? `npm run develop` and `npm run build` are by far more common within the community than `gatsby develop` and `gatsby build`


Another thing. More offtopic, but a problem occured just recently. `gatsby build` worked, now it stops after `Generating CSS`. Just quits without any errors as if it's finished. Any ideas why that might happen?

**Comment by KyleAMathews** [comment]
That's a great point re adding scripts to the starters. I'll do that shortly.

Hmmm... it's a bug if the errors aren't being sent to the console... let me know if you figure out where they're being silenced.

**Comment by KyleAMathews** [comment]
Added the scripts to the starters https://github.com/gatsbyjs/gatsby-starter-default/blob/master/package.json#L60

I'm going to close this now but please tell me if you find out why the error wasn't being written out.

**Comment by everdimension** [comment]
sure!
