### ISSUE TITLE
[gatsby-source-wordpress] Inconsistent images behavior

### ISSUE THREAD

**Issue by tiggeymone** [gatsbyjs/gatsby#35829]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hello,

after encountering some images issues on my wordpress-gatsby project, I tried to create a brand new Wordpress test installation with two simple articles, wpgraphql and wpgatsby. Using the wordpress starter configuration on Gatsby side, I can't properly visualize the images. The image rendering seems to be inconsistent, as you can see in this video.

If I use the example wordpress endpoint (https://wpgatsbydemo.wpengine.com/graphql) everything works fine, but if I use my Wordpress installation, things are like in the following video:

https://user-images.githubusercontent.com/4254655/171671577-e26b5009-d410-455b-b254-c1cc429bda65.mov

You can test my test wp installation using the following endpoint:

https://rotarius.it/graphql

### Reproduction Link

https://github.com/tiggeymone/gatsby-inconsistent-images-behavior

### Steps to Reproduce

1. Clone the reproduction repository
2. change the WPGRAPHQL_URL. If you use the default one everything is ok. If you use my brand new test installation endpoint (https://rotarius.it/graphql) you should have the inconsistent results you see in the video
3. npm install
4. gatsby build && gatsby serve
5. go to localhost:9000 and navigate
...

### Expected Result

Images should always display

### Actual Result

Images are inconsistently displayed: sometimes they load, sometimes not.

### Environment

```shell
System:
    OS: macOS 12.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 100.0.2
    Safari: 15.4
  npmPackages:
    gatsby: ^4.0.0 => 4.15.2
    gatsby-plugin-image: ^2.0.0 => 2.15.1
    gatsby-plugin-manifest: ^4.0.0 => 4.15.1
    gatsby-plugin-offline: ^5.0.0 => 5.15.1
    gatsby-plugin-react-helmet: ^5.0.0 => 5.15.0
    gatsby-plugin-sharp: ^4.0.0 => 4.15.1
    gatsby-source-filesystem: ^4.0.0 => 4.15.0
    gatsby-source-wordpress: ^6.0.0 => 6.15.1
    gatsby-transformer-sharp: ^4.0.0 => 4.15.1
  npmGlobalPackages:
    gatsby-cli: 4.11.1
```

**Comment by tiggeymone** [comment]
Not stale

**Comment by stackpath-andrew** [comment]
We are having issues with this as well. 

Images either tale a long time to load, or there are inconsistencies. For example, some images have an odd empty div above it causing strange white space above our images.

<img width="1388" alt="Screen Shot 2022-06-25 at 1 52 28 PM" src="https://user-images.githubusercontent.com/97123695/175785052-88a21267-8585-438e-bf1f-fcc142f6ae8a.png">

**Comment by omardeangelis** [comment]
I've got the same issue but reversed. Inline images works when user lands from internal routes but shows an empty div when user lands directly on the page with inline images
