### ISSUE TITLE
GraphQL Typegen only picking up graphql tag usage from gatsby-node.ts

### ISSUE THREAD

**Issue by openscript** [gatsbyjs/gatsby#35853]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I've split up my `gatsby-node.ts`, so it's easier to maintain and test. For example:

```typescript
import { GatsbyNode } from 'gatsby';
import { CreateGenericPages } from './src/gatsby/createPages/createGenericPages.ts';

export const createPages: GatsbyNode['createPages'] = async args => {
  await CreateGenericPages(args);
};
```

Within `createGenericPages.ts` I'm using the `graphql` tag:

```typescript
import { CreatePagesArgs } from 'gatsby';
import { resolve } from 'path';

export async function CreateGenericPages({ actions, graphql }: CreatePagesArgs) {
  const { createPage } = actions;
  const allPages = await graphql<Queries.AllGenericPagesQuery>(`
    query AllGenericPages {
      allMdx(filter: { fields: { kind: { eq: "pages" } } }) {
        edges {
          node {
            id
            fields {
              path
              translations {
                locale
                path
              }
            }
          }
        }
      }
    }
  `);

  allPages.data?.allMdx.edges.forEach(p => {
    if (p.node.fields && p.node.fields.path) {
      createPage({
        component: resolve('./src/templates/GenericPage.tsx'),
        context: { id: p.node.id, translations: p.node.fields.translations },
        path: p.node.fields.path,
      });
    }
  });
}
```
As @LekoArts mentioned in https://github.com/gatsbyjs/gatsby/discussions/35420#discussioncomment-2883589 picking up such graphql usage for type generation is set to `gatsby-node.ts` files specifically here: https://github.com/gatsbyjs/gatsby/blob/7dfd52d9b43e9fe2e456b273dc75de99634ace5d/packages/gatsby/src/utils/graphql-typegen/ts-codegen.ts#L97

So the types for these queries are not generated in my case.

### Reproduction Link

https://github.com/openscript-ch/gatsby-starter-dogmatism/tree/feat/migrate-to-built-in-typegen

### Steps to Reproduce

1. Use `graphql` elsewhere than `gatsby-node.ts`
2. Start your project
3. Check if types are generated.

### Expected Result

It would be great, that this types are picked up, because otherwise we can not split up `graphql-node.ts` and using type generation at the same time.

### Actual Result

Types are not generated for graphql usage elsewhere than `gatsby-node.ts`.

### Environment

```shell
System:
    OS: Linux 5.18 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.14.2 - /tmp/yarn--1654526027837-0.40294770445210526/node
    Yarn: 1.22.18 - /tmp/yarn--1654526027837-0.40294770445210526/yarn
    npm: 8.5.0 - /usr/local/bin/npm
  Languages:
    Python: 3.9.2 - /usr/bin/python
  npmPackages:
    gatsby: 4.15.2 => 4.15.2
    gatsby-plugin-catch-links: 4.15.0 => 4.15.0
    gatsby-plugin-emotion: 7.15.0 => 7.15.0
    gatsby-plugin-i18n-l10n: 4.6.2 => 4.6.2
    gatsby-plugin-image: 2.15.1 => 2.15.1
    gatsby-plugin-manifest: 4.15.1 => 4.15.1
    gatsby-plugin-mdx: 3.15.2 => 3.15.2
    gatsby-plugin-offline: 5.15.1 => 5.15.1
    gatsby-plugin-react-helmet: 5.15.0 => 5.15.0
    gatsby-plugin-sharp: 4.15.1 => 4.15.1
    gatsby-remark-autolink-headers: 5.15.1 => 5.15.1
    gatsby-remark-copy-linked-files: 5.15.0 => 5.15.0
    gatsby-remark-images: 6.15.1 => 6.15.1
    gatsby-source-filesystem: 4.15.0 => 4.15.0
    gatsby-transformer-sharp: 4.15.1 => 4.15.1
```

**Comment by LekoArts** [comment]
With https://github.com/gatsbyjs/gatsby/pull/35966 the basis was created to add additional options to the typegen feature. Since https://github.com/gatsbyjs/gatsby/issues/36157 also now came up I think the easiest solution will be having a new option to configure the relevant setting.

**Comment by LekoArts** [comment]
I don't have time to add that option myself but I'd be happy to help with a PR and review it :)

**Comment by Prasundas99** [comment]
@LekoArts  I would like to work on this. Please assign it to me

**Comment by tujoworker** [comment]
@Prasundas99 and @andrmaz you have to make a fork of the repo, Celine/check it out locally, make the changes there in a new branch, push it and make PR back to this repo. Hope this clears things out.
