### ISSUE TITLE
[gastby-source-drupal] URLSearchParams dropping valid JSONAPI filter parameters

### ISSUE THREAD

**Issue by wayne-weibel** [gatsbyjs/gatsby#35869]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

A valid Drupal JSONAPI filter is to use the `IN` operator, which requires the value parameter to be defined as an array using `filter[name][condition][value][]=param1&filter[name][condition][value][]=param2`.  This format would apply to operator expecting multiple values.

Currently the filter url is created by looping over `filters[type]` using separate key and object arrays after passing to URLSearchParams, and omitting 'duplicate' keys.  This results in any value after the first to be dropped.

### Reproduction Link

https://www.example.com

### Steps to Reproduce

1. enable `gatsby-source-drupal`
2. add a filter to a drupal content type using the 'IN' operator
3. examine the generated url

### Expected Result

http://drupal.lndo.site/jsonapi/node/blog?filter[moderation-filter][condition][path]=field_moderated_state&filter[moderation-filter][condition][operator]=IN&filter[moderation-filter][condition][value][]=published&filter[moderation-filter][condition][value][]=imp

### Actual Result

http://drupal.lndo.site/jsonapi/node/blog?filter[moderation-filter][condition][path]=field_moderated_state&filter[moderation-filter][condition][operator]=IN&filter[moderation-filter][condition][value][]=published

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.5.5 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 97.0.1
    Safari: 15.4
  npmPackages:
    gatsby: ^4.15.2 => 4.15.2 
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5 
    gatsby-plugin-asset-path: ^3.0.4 => 3.0.4 
    gatsby-plugin-env-variables: ^2.2.0 => 2.2.0 
    gatsby-plugin-feed: ^4.15.1 => 4.15.1 
    gatsby-plugin-fontawesome-css: ^1.2.0 => 1.2.0 
    gatsby-plugin-image: ^2.15.1 => 2.15.1 
    gatsby-plugin-react-helmet: ^5.15.0 => 5.15.0 
    gatsby-plugin-react-svg: ^3.1.0 => 3.1.0 
    gatsby-plugin-resolve-src: ^2.1.0 => 2.1.0 
    gatsby-plugin-sass: ^5.15.1 => 5.15.1 
    gatsby-plugin-sharp: ^4.15.1 => 4.15.1 
    gatsby-plugin-sitemap: ^5.15.1 => 5.15.1 
    gatsby-source-drupal: ^5.16.2 => 5.16.2 
    gatsby-source-filesystem: ^4.15.0 => 4.15.0 
    gatsby-transformer-remark: ^5.15.1 => 5.15.1 
    gatsby-transformer-sharp: ^4.15.1 => 4.15.1
```

**Comment by Vacilando** [comment]
It looks like a properly reported issue - why was it closed by a bot? Has anyone with expertise of the gatsby-source-drupal plugin had a look into this?
