### ISSUE TITLE
Using getServerData in a dynamically (Template) created page (actions.createPage) results in a 404

### ISSUE THREAD

**Issue by jhowsick** [gatsbyjs/gatsby#35861]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I'm trying to create templates pages which mix Contentful and Api Data.  The route is dynamically created per CreatePage. Everything works as expected and the routes show the dynamically created page and its Contentful Data. The problem is that i get a 404 as soon as I export a  getServerData function (Like in the docs) in the Template. 

Is this even possible or is this a Bug? Or is there a different approach when using Templates (src/templates) then with pages under src/pages

### Reproduction Link

N/A

### Steps to Reproduce

Export getServerData in any Programmatically  created Page 

### Expected Result

The Template / Page should still be accessible (No 404) when exporting getServerData within 

### Actual Result

exporting getServerData in the Template results in a 404

### Environment

```shell
System:
    OS: macOS 11.6.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.4 - /var/folders/7w/7s9lfj854kx9clzvl8h_l2g8zhz56d/T/yarn--1654598720126-0.039192618663733914/node
    Yarn: 1.22.17 - /var/folders/7w/7s9lfj854kx9clzvl8h_l2g8zhz56d/T/yarn--1654598720126-0.039192618663733914/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.4/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 101.0
    Safari: 15.4
  npmPackages:
    gatsby: ^4.13.1 => 4.14.0 
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5 
    gatsby-plugin-image: ^2.13.0 => 2.14.1 
    gatsby-plugin-manifest: ^4.13.0 => 4.14.0 
    gatsby-plugin-material-ui: ^4.0.2 => 4.1.0 
    gatsby-plugin-react-helmet: ^5.13.0 => 5.14.0 
    gatsby-plugin-react-svg: ^3.1.0 => 3.1.0 
    gatsby-plugin-robots-txt: ^1.7.1 => 1.7.1 
    gatsby-plugin-sharp: ^4.13.0 => 4.14.1 
    gatsby-plugin-sitemap: ^5.13.0 => 5.14.0 
    gatsby-source-contentful: ^7.11.0 => 7.12.0 
    gatsby-source-filesystem: ^4.13.0 => 4.14.0 
    gatsby-transformer-sharp: ^4.13.0 => 4.14.0
```

**Comment by lambdadev007** [comment]
I am getting the same issue. when I use getServerData to generate server side rendered page, it works find locally, but it gives me 404 page on Netlify.

**Comment by lambdadev007** [comment]
@jhowsick in my case, The server side rendered pages that use getServerData works fine locally. it only gives me 404 page on Netlify. I was able to address this issue by installing **gatsby-plugin-netlify** plugin.
FYI - https://github.com/netlify/netlify-plugin-gatsby/#readme

**Comment by LekoArts** [comment]
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!
