### ISSUE TITLE
pathPrefix is ignored by the build script when generating static html pages

### ISSUE THREAD

**Issue by moretti** [gatsbyjs/gatsby#3587]
## Description

I'm trying to upload static assets (images, JavaScript files, etc) to a CDN.

I changed the configuration, so that the public path points to a custom domain (`https://example.com/static/` - see the file contents section below).

The problem is that static HTML templates are still generated with relative paths:

![screen shot 2018-01-18 at 17 24 02](https://user-images.githubusercontent.com/1186409/35111978-91b4b3a6-fc74-11e7-8d4e-953b6b27a67c.png)

I had a quick look at the source code and it seems that in the following script, used to generate the templates:
https://github.com/gatsbyjs/gatsby/blob/53c05d087218982cb157712b118dd9387bc1783d/packages/gatsby/cache-dir/static-entry.js#L44-L46
`__PATH_PREFIX__` is set to `false`, rather than `https://example.com/static` (defined in my `gatsby-config.js`)

### Environment

Gatsby version: 1.9.157
Node.js version: 8.9.4
Operating System: MacOS 10.13.2

### File contents (if changed):

`gatsby-config.js`:
```.js
module.exports = {
  pathPrefix = 'https://example.com/static'
}
```
`gatsby-node.js`:
```
module.exports = {
  modifyWebpackConfig({ config, stage }) {
    config.merge({
      output: {
        publicPath:
          'https://example.com/static',
      },
    });
  },
};
```

### Actual result

```
<link rel="preload" href="/component---src-layouts-index-js-6d9cca314a40eb6d4fd1.js" as="script"/>
```

### Expected behavior

```
<link rel="preload" href="https://example.com/static/component---src-layouts-index-js-6d9cca314a40eb6d4fd1.js" as="script"/
```

### Steps to reproduce

1\. Create a new project with `gatsby new`

2\. Edit `gatsby-config.js` and `gatsby-node.js`

3\. Run `gatsby build`

4\. Inspect the HTML generated in the `public` folder

**Comment by sjkp** [comment]
You need to run `gatsby build --prefix-paths`

**Comment by moretti** [comment]
@sjkp I tried that, and looks like the absolute `http://` path is turned into a relative one
![screen shot 2018-01-18 at 18 07 26](https://user-images.githubusercontent.com/1186409/35124311-8a71fc92-fc9d-11e7-8751-8e7e019b17da.png)
```
Loading failed for the <script> with source "http://localhost:9000/https://example.com/static/commons-03554c3de8e6350a1b07.js".
localhost:9000:1
```
setting `pathPrefix` to `'/example.com/static'` seems to do the trick, but feels really hacky

**Comment by KyleAMathews** [comment]
@moretti Gatsby is a static site builder so you should upload the entire site to your CDN. Gatsby doesn't have any native way to handle splitting off some assets for the CDN. Just serve everything from the CDN and you won't have to worry about changing paths.
