### ISSUE TITLE
Getting new posts in production. [question]

### ISSUE THREAD

**Issue by krsjoseph** [gatsbyjs/gatsby#3588]
I'm using Gatsby with wordpress, when I publish a new post on my wordpress site, do I have to rebuild my Gatsby project and do a deploy every time this occurs?

**Comment by krsjoseph** [comment]
closed per https://github.com/gatsbyjs/gatsby/issues/2753

**Comment by fk** [comment]
Just was about to send you that way, glad you found it yourself!
