### ISSUE TITLE
Error loading a result for the page query in "/". Query was not run and   no cached result was found.

### ISSUE THREAD

**Issue by AleJo2995** [gatsbyjs/gatsby#35889]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi team,

This error is happening when it attempts to build our site via Travis randomly. When I say randomly is that a couple of days, happen and other days the build runs successfully. What is the root cause of the issue per-sé? I have ran the development instance and it runs perfectly fine but I don´t fully understand why when the build runs it toggles between working and not working sometimes. Even when it runs bad one day I restart the build and then it runs perfectly fine.

I´ve reviewed other issues related to this behavior such as https://github.com/gatsbyjs/gatsby/issues/27644, and the solution provided is the usage of gatsby clean before build which I thought it was not necessary any longer. Even though i tried that solution it still behaves weird and toggles between working and not.

![image](https://user-images.githubusercontent.com/8278478/172668538-e6c64f01-cb0d-4057-b2ff-06b51ced4eb0.png)

I´ve debugged the code going trough the functions mentioned in the log that gives the problem, and apparently the line that breaks it all is this one: `return JSON.parse(rawPageData);`  at page-data.ts/js line 47 where it seems that the JSON file is missing a '}' at the very end, which results in this error: `Uncaught SyntaxError: Unexpected token d in JSON at position 30126`

Brief context
We´re using gatsby build out a site with fetches different sorts of markdown files from other repos using `gatsby-source-git` plugin, with which I haven´t face any problem during the sourcing.

**IMPORTANT**

I´ve created an issue for that before(#34764) but it was not yet resolved, so I´m asking for help again since this bug has been around for a while now.

### Reproduction Link

n//a

### Steps to Reproduce

1.
2.
3.
...

### Expected Result

Build should work consistently and not toggling with this random and non descriptive issue

### Actual Result

Right now we´re unable to build consistently without human assist

### Environment

```shell
System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.1 - /usr/local/bin/npm
  Languages:
    Python: 3.9.2 - /usr/local/bin/python
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 96.0.2
    Safari: 15.4
  npmPackages:
    gatsby: ^3.14.0 => 3.14.0
    gatsby-plugin-changelog-context: ^1.1.0 => 1.1.0
    gatsby-plugin-local-search: ^2.0.1 => 2.0.1
    gatsby-plugin-mdx: ^2.12.0 => 2.13.0
    gatsby-plugin-page-creator: ^3.12.0 => 3.14.0
    gatsby-plugin-slug-field: ^0.3.1 => 0.3.1
    gatsby-remark-check-links: ^2.1.0 => 2.1.0
    gatsby-remark-embed-markdown: ^0.0.4 => 0.0.4
    gatsby-source-filesystem: ^3.12.0 => 3.13.0
    gatsby-source-git: ^1.1.0 => 1.1.0
    gatsby-theme-carbon: ^2.0.0 => 2.0.0
    gatsby-transformer-csv: ^3.14.0 => 3.14.0
    gatsby-transformer-javascript-frontmatter: ^3.12.0 => 3.13.0
    gatsby-transformer-json: ^4.0.0 => 4.0.0
    gatsby-transformer-remark: ^4.9.0 => 4.10.0
  npmGlobalPackages:
    gatsby-cli: 3.6.0
```

**Comment by div-cowboy** [comment]
I'm also experiencing this issue periodically both locally and on Netlify

**Comment by LekoArts** [comment]
Please use https://github.com/gatsbyjs/gatsby/issues/34764 and provide a reproduction
