### ISSUE TITLE
https: mode (devcert) fails with `Error: "localhost" is not a valid domain name`

### ISSUE THREAD

**Issue by grgcnnr** [gatsbyjs/gatsby#35892]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

On Gatsby 4.15 and 4.16 using a minimal starter with `npm init gatsby`  running `gatsby develop -S` fails to generate a certificate with devcert

![image](https://user-images.githubusercontent.com/2694014/172738042-3f17cc02-ba2c-4aa5-9f82-afdbc6aea2d7.png)

This has happened in the past due to a change in the regex devcert uses: https://github.com/gatsbyjs/gatsby/issues/25064

reproduction is literally just the typescript starter with gatsby updated to 4.16.0

### Reproduction Link

https://github.com/grgcnnr/gatsby-devcert-minimal

### Steps to Reproduce

1. Checkout + `npm i` 
2. run `npm run develop -- -S`
...

### Expected Result

Gatsby should generate a self-signed certificate and boot the dev server with HTTPS

### Actual Result

devcert throws a fatal error `"Error: "localhost" is not a valid domain name."`

### Environment

```shell
System:
    OS: macOS 11.6.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 102.0.5005.61
    Safari: 15.5
  npmPackages:
    gatsby: ^4.16.0 => 4.16.0
```

**Comment by grgcnnr** [comment]
Providong a valid host does fix this issue as long as the hostname points to your loopback IP address in `/etc/hosts`

ie
`$ sudo gatsby develop -S -p 443 --host karbonhq.com`

and in `/etc/hosts/`
`127.0.0.1       karbonhq.com`

**Comment by LekoArts** [comment]
As in https://github.com/gatsbyjs/gatsby/issues/25064 - please report this to https://github.com/davewasmer/devcert/issues or pin your version of it. Thanks!
