### ISSUE TITLE
Do I need to make changes to the existing code to continue using yaml?

### ISSUE THREAD

**Issue by colbycheeze** [gatsbyjs/gatsby#359]
After the update I am getting this error anywhere I am trying to read a yaml file:
![image](https://cloud.githubusercontent.com/assets/8884298/17001896/8a323148-4e8e-11e6-81f5-ff0eb4d1f758.png)

This is what shows up in the browser:
![image](https://cloud.githubusercontent.com/assets/8884298/17002096/6d34a462-4e8f-11e6-8272-d2141bd9872c.png)

I only bumped the version and then saw this.

**Comment by KyleAMathews** [comment]
Quick thing to try is installing the latest yaml-loader in your project

**Comment by colbycheeze** [comment]
I tried pulling down your latest "gatsby-starter-default" to see if it was related my project but it seems to be happening there as well:
![image](https://cloud.githubusercontent.com/assets/8884298/17003393/5ca3a660-4e95-11e6-8dac-de7c2e608672.png)

**Comment by joshhornby** [comment]
I can confirm this is a bug on a fresh install.

**Comment by KyleAMathews** [comment]
Hrmm... investigating

**Comment by KyleAMathews** [comment]
huh... works on my machine :-)

Wiping `node_modules` and trying a fresh install.

**Comment by KyleAMathews** [comment]
Ok found it. yaml-loader doesn't need to be chained with json-loader anymore. They just made a new release and I missed the change. https://github.com/okonet/yaml-loader/commit/36d12a8b336a87e7d4f0a3e60b83a6e82e5772e9 Will make a new release of Gatsby real quick.

**Comment by KyleAMathews** [comment]
0.12.1 is out.
