### ISSUE TITLE
TS2786: 'Link' cannot be used as a JSX component.   Its instance type 'GatsbyLink<unknown>' is not a valid JSX element.

### ISSUE THREAD

**Issue by asinha08** [gatsbyjs/gatsby#35918]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

<img width="869" alt="image" src="https://user-images.githubusercontent.com/604180/173200836-d1585ade-0f22-46ff-be4a-0b86af9e6f23.png">

### Reproduction Link

NA

### Steps to Reproduce

May not be needed. If required it will post the steps

### Expected Result

No Typescript error.

### Actual Result

Typescript should not throw error.

### Environment

```shell
NA
```

### Config Flags

NA

**Comment by LekoArts** [comment]
Please see https://github.com/gatsbyjs/gatsby/issues/35715

**Comment by webashraf** [comment]
I face the same issue after using react-scroll Link, but my error occurs after deploying in Vercel.
