### ISSUE TITLE
Image Always Encoded At Original Size In All Formats

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#35976]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When using `gatsby-remark-images`, and specifying a `maxWidth`, `srcSetBreakpoints` and multiple image formats, the original image is always included and encoded into all formats, despite it being larger than `maxWidth`. This can be very expensive when using more demanding formats like `.avif`, and/or when the original image is of a significant size. 

It seems the assumption has been made that the original image will always be the same width as the larges image size which is a false assumption. It is quite common to use a larger source image, either for future-proofing or for improved encoding. 

Note
- It seems that images that are not pulled in through `gatsby-remark-images` are _not_ affected by this bug. It seems to be specific to images within Markdown. 
- I wondered if setting `linkImagesToOriginal` to false would make a difference, but it doesn't.

### Reproduction Link

https://github.com/Undistraction/gatsby-remark-images-bug

### Steps to Reproduce

1. gatsby build
2. Inspect the generated image files in `/static/`. 

### Expected Result

The original image shouldn't have been encoded, and the largest image for all formats should be the `maxWidth` as specified in `gatsby-config.js` (630px). 

### Actual Result

The original 1600px-wide image has been encoded into `.avif` and `.webp` despite this size never being used. 

### Environment

```shell
System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.2/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Edge: 102.0.1245.44
    Firefox: 101.0.1
    Safari: 15.5
  npmPackages:
    gatsby: ^4.17.0 => 4.17.0
    gatsby-cli: ^4.17.0 => 4.17.0
    gatsby-plugin-feed: ^4.17.0 => 4.17.0
    gatsby-plugin-gatsby-cloud: ^4.17.0 => 4.17.0
    gatsby-plugin-google-analytics: ^4.17.0 => 4.17.0
    gatsby-plugin-image: ^2.17.0 => 2.17.0
    gatsby-plugin-manifest: ^4.17.0 => 4.17.0
    gatsby-plugin-offline: ^5.17.0 => 5.17.0
    gatsby-plugin-react-helmet: ^5.17.0 => 5.17.0
    gatsby-plugin-sharp: ^4.17.0 => 4.17.0
    gatsby-remark-copy-linked-files: ^5.17.0 => 5.17.0
    gatsby-remark-images: ^6.17.0 => 6.17.0
    gatsby-remark-prismjs: ^6.17.0 => 6.17.0
    gatsby-remark-responsive-iframe: ^5.17.0 => 5.17.0
    gatsby-remark-smartypants: ^5.17.0 => 5.17.0
    gatsby-source-filesystem: ^4.17.0 => 4.17.0
    gatsby-transformer-remark: ^5.17.0 => 5.17.0
    gatsby-transformer-sharp: ^4.17.0 => 4.17.0
```

### Config Flags
None

**Comment by LekoArts** [comment]
gatsby-plugin-image is separate from gatsby-remark-images. The latter still uses the `fluid` functions from gatsby-plugin-sharp that have that behavior.

**Comment by Undistraction** [comment]
OK. That makes sense. Thanks @LekoArts
