### ISSUE TITLE
Gatsby-Source-Wordpress - Creating A New Site From Scrath page is outdated

### ISSUE THREAD

**Issue by jkgatt** [gatsbyjs/gatsby#35982]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

Basically the following documentation: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/tutorials/building-a-new-site-wordpress-and-gatsby.md, is quite outdated and can be explained in an easier, simpler fashion.

### Steps to Resolve this Issue

Visit: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/tutorials/building-a-new-site-wordpress-and-gatsby.md and compare to: https://www.gatsbyjs.com/docs/tutorial/part-6/#render-post-contents-in-the-blog-post-page-template

**Comment by LekoArts** [comment]
@TylerBarnes Couldn't this whole tutorial section be completely removed from the README and repository? I'd say https://www.gatsbyjs.com/docs/how-to/sourcing-data/sourcing-from-wordpress/ should be the source of truth and be updated.

**Comment by TylerBarnes** [comment]
@jkgatt do you mean it's outdated because it doesn't use the filesystem route api? The FS route api doesn't work very well for CMS backed sites where page templates are determined via data (which is often the case with WP). So I wouldn't say it's outdated, though it could show an example of both ways of creating pages.

@LekoArts I'm good with conslidating on the docs page like you mentioned as long as the source plugin readme links to it somewhere.

**Comment by jkgatt** [comment]
@TylerBarnes Basically I feel that the method showcased on the GatsbyJS website using page templates is much cleaner than adding the query to gatsby-node.js file, but maybe I don't know about the limitations for this. Are there any limitations from your understanding? Thanks!

**Comment by TylerBarnes** [comment]
@jkgatt the limitation is when you need to pick a template based on data from a node. FS route api creates a 1:1 relationship between a node type and a specific template, but WP sites very rarely work that way. For example for the Page node type you'll likely have 3 or 4 different templates in WP and select one using the template picker dropdown (or a custom field) in WP.

With FS route API all Page nodes will use the same template. Sometimes this is fine, but usually not.

**Comment by TylerBarnes** [comment]
So it's worth showing both examples and even explaining when you'd want to use each

**Comment by jkgatt** [comment]
Okay thank you @TylerBarnes for the explanation! 
I am using mine for blog posts and other post data so for my case it is fine. Do you want me to handle updating the documentation?

thank you!
