### ISSUE TITLE
gatsby-source-wordpress plugin doesn't work when using yarn pnp linker

### ISSUE THREAD

**Issue by cameronbraid** [gatsbyjs/gatsby#35993]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

The plugin fails to be used even when configured so nothing is sourced and it then fails trying to run the first query

### Reproduction Link

https://github.com/cameronbraid/gatsby-starter-wordpress-blog-yarn-pnp

### Steps to Reproduce

check repor and run `yarn develop`

### Expected Result

Should work

### Actual Result

**
❯ yarn develop
success compile gatsby files - 0.592s
success load gatsby config - 0.035s
success load plugins - 0.853s
success onPreInit - 0.005s
success initialize cache - 0.076s
success copy gatsby files - 0.090s
success Compiling Gatsby Functions - 0.302s
success onPreBootstrap - 0.335s
success createSchemaCustomization - 0.006s
success Checking for changed pages - 0.003s
success source and transform nodes - 0.098s
success building schema - 0.358s

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "allWpPost" on type "Query".
**

### Environment

```shell
System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 17.8.0 - /tmp/xfs-db945f70/node
    Yarn: 3.2.1 - /tmp/xfs-db945f70/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v17.8.0/bin/npm
  Browsers:
    Chrome: 94.0.4606.71
    Firefox: 96.0
```

**Comment by cameronbraid** [comment]
I have found a workaround by using a patched `gatsby-plugin-utils` package.json changing the exports field.  Mobing the `./dist/*` line before the `./*` line

```
  "exports": {
    ".": "./dist/index.js",
    "./dist/*": "./dist/*.js",
    "./*": "./dist/*.js",
    "./dist/polyfill-remote-file": null,
    "./dist/utils": null,
    "./polyfill-remote-file": "./dist/polyfill-remote-file/index.js",
    "./dist/polyfill-remote-file/jobs/gatsby-worker.js": "./dist/polyfill-remote-file/jobs/gatsby-worker.js",
    "./dist/polyfill-remote-file/graphql/*": "./dist/polyfill-remote-file/graphql/*.js"
  },
```

**Comment by LekoArts** [comment]
Feel free to put up a PR and we'll see if our yarn pnp checks are happy

**Comment by cameronbraid** [comment]
I'll look to put up a PR for this soon.

One thing I would like if you (or someone with more gatsby internal knowledge) could do is look into why the plugin silently fails (see my repro above) and put in a trap for that and inform the user.
