### ISSUE TITLE
GatsbyConfig type defined Sync update required

### ISSUE THREAD

**Issue by zhaohuanyuu** [gatsbyjs/gatsby#35991]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

**Question：**
The site's gatsby-config.js failed validation:

"graphqlTypegen" must be a boolean

**Reason:**
index.d.ts:
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/25791574/175763451-96c6bdf7-df60-4128-a9f6-6536e58d0caf.png">

https://www.gatsbyjs.com/docs/reference/config-files/gatsby-config/#graphqltypegen

The latest document clearly states that an object can be set to set the output location of gatsby-types.d.ts, but the type definition of index.d.ts is still boolean, resulting in an error

### Reproduction Link

unnecessary

### Steps to Reproduce

index.d.ts > line: 249

### Expected Result

```ts
graphqlTypegen?: boolean | object
```

### Actual Result

The site's gatsby-config.js failed validation:

"graphqlTypegen" must be a boolean

### Environment

```shell
System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /var/folders/mk/1t1ldctx4996h4xp021w12nr0000gn/T/yarn--1656142624076-0.10872253719598057/node
    Yarn: 1.22.19 - /var/folders/mk/1t1ldctx4996h4xp021w12nr0000gn/T/yarn--1656142624076-0.10872253719598057/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Safari: 15.5
  npmPackages:
    gatsby: ^4.17.0 => 4.17.1 
    gatsby-plugin-feed: ^4.14.0 => 4.15.0 
    gatsby-plugin-gatsby-cloud: ^4.15.0 => 4.15.0 
    gatsby-plugin-image: ^2.15.0 => 2.15.0 
    gatsby-plugin-manifest: ^4.0.0 => 4.15.0 
    gatsby-plugin-mdx: ^3.11.1 => 3.15.0 
    gatsby-plugin-postcss: ^5.12.1 => 5.15.0 
    gatsby-plugin-react-helmet: ^5.11.0 => 5.15.0 
    gatsby-plugin-sharp: 4.15.0 => 4.15.0 
    gatsby-plugin-sitemap: ^5.11.1 => 5.15.0 
    gatsby-remark-images: ^6.12.1 => 6.15.0 
    gatsby-remark-prismjs: ^6.11.0 => 6.15.0 
    gatsby-remark-reading-time: ^1.1.0 => 1.1.0 
    gatsby-source-filesystem: ^4.11.0 => 4.15.0 
    gatsby-transformer-sharp: ^4.11.0 => 4.15.0
```

**Comment by LekoArts** [comment]
You can set it as an object with `gatsby@next` or you'll want to wait for the stable release on July 5th.

**Comment by zhaohuanyuu** [comment]
> July

ok, i'll wait for stable version
