### ISSUE TITLE
Update to "Basic Hardware and Software Requirements"

### ISSUE THREAD

**Issue by LiamJSP** [gatsbyjs/gatsby#36000]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

https://www.gatsbyjs.com/docs/basic-hardware-software-requirements/

The hardware requirements page omits an important detail, that on Linux specifically, CPUs must support the SSE4.2 instruction set (this is a requirement of the Sharp library). Running on CPUs that do not support this instruction set (typically those from before 2012) do not produce an instructive error, instead just a generic sigkill. The source of the issue is discovered using "dmesg", specifically "invalid opcode".

I honestly don't expect a resolution in the source as it's reasonable that 10 year old CPUs may not be supported for enterprise applications like NodeJS etc. Just figured that it'd be worth clarifying this requirement in the doc to save time as its not immediately apparent what the issue is, especially since oddly Gatsby/Sharp does not have this CPU requirement when building on Windows.

I think it's worth making it clear in this page that the Sharp library can be the source of certain hardware requirements (i.e a little infobox noting users should check Sharp's compatibility list if they experience platform specific issues), as this is not the first time I encountered an undocumented hardware requirement for Gatsby - for the longest time you couldn't build on Raspberry Pi/ARM, again due to Sharp.

### Steps to Resolve this Issue

1. Add note that currently Gatsby (or at least the Sharp plugin) will not work on Linux if the CPU does not support SSE4.2, aka CPUs pre-2012. This requirement does not exist for Windows, it seems the windows binary is built with the bare minimum instruction set requirements (aka less optimized than the linux bin).
2. Possibly add general note indicating that users experiencing platform specific issues, should check whether their platform is supported by the Sharp library

**Comment by spiderxp3** [comment]
I am interested to work on that.

**Comment by LekoArts** [comment]
Happy to review a PR updating that page 👍

**Comment by RajputUsman** [comment]
@LekoArts #36153
