### ISSUE TITLE
[www] Open search form with keyboard shortcut

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#3602]
Add keyboard shortcut `/` to open the search form on gatsbyjs.org. 

Ref: https://github.com/gatsbyjs/gatsby/pull/3421#issuecomment-358740434

**Comment by markmichon** [comment]
Is this convention? Some browsers default `/` to Find. (like Firefox)

Currently, it's the first tab target, which generally a good a11y practice.

**Comment by KyleAMathews** [comment]
Oh hmmm good point. I've done it on a web app before and it was great but perhaps it's not worth doing it here.

**Comment by m-allanson** [comment]
Maybe we could look at how GitHub handles it? On the issues page `/` opens Firefox's built in 'Find in page' control, but for other browsers it focusses the issue search box.

**Comment by m-allanson** [comment]
We could also use a key that doesn't conflict with any existing browser shortcuts. Check out the full range of GitHub shortcuts with `?`.

**Comment by KyleAMathews** [comment]
Yeah, they use `s` which seems reasonable. We could also use copy their "go to" commands e.g. `gd` is go to docs, `gp` is go to package search page (once that's built that is :-)). Which would be fun too.
