### ISSUE TITLE
Bad dependency: gatsby-remark-embed-snippet  depends on really old gatsby-remark-prismjs 

### ISSUE THREAD

**Issue by EdPike365** [gatsbyjs/gatsby#36046]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

My first issue! Don't hate plz.
The @latest gatsby-remark-embed-snippet (7.17.0) has a peer dependency of gatsby-remark-prismjs@^4.0.0-next. 
The @latest gatsby-remark-prismjs is 6.17.0, which is 2 plus major semvers higher, which seems odd.
I looked through embed-snippet's 7.17.0 package.json and noticed:
  "peerDependencies": {
    "gatsby": "^4.0.0-next",
    "gatsby-remark-prismjs": "^4.0.0-next"
  },
Is this perhaps a typo, copying the **gatsby** dep "^4.0.0-next" (which makes sense) with the gatsby-remark-prismjs dep?
Could just be coincidence but...

### Reproduction Link

https://codesandbox.io/s/competent-bhaskara-wlhb13

### Steps to Reproduce

I tried this in code sandbox above but I could not see if it completely started over after I installed embed-snippet because there was an "upgrade to newer gatsby" message. On my machine, I have to run gatsby develop again. 
1. Install/Upgrade to gatsby-remark-prismjs@latest ( 6.17.0 )
2. Install gatsby-remark-embed-snippet@latest ( 7.17.0)
3. You will get peer dependency error shown further down.

### Expected Result

Upgrade would work because gatsby-remark-embed-snippet is part of Gatsby core repo and should generally keep up like the other remark plugins.

### Actual Result

npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: gatsby-remark-embed-snippet@7.17.0
npm WARN Found: gatsby-remark-prismjs@6.17.0
npm WARN node_modules/gatsby-remark-prismjs
npm WARN   gatsby-remark-prismjs@"^6.17.0" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer gatsby-remark-prismjs@"^4.0.0-next" from gatsby-remark-embed-snippet@7.17.0
npm WARN node_modules/gatsby-remark-embed-snippet
npm WARN   gatsby-remark-embed-snippet@"7.17.0" from the root project
npm WARN 
npm WARN Conflicting peer dependency: gatsby-remark-prismjs@4.2.0
npm WARN node_modules/gatsby-remark-prismjs
npm WARN   peer gatsby-remark-prismjs@"^4.0.0-next" from gatsby-remark-embed-snippet@7.17.0
npm WARN   node_modules/gatsby-remark-embed-snippet
npm WARN     gatsby-remark-embed-snippet@"7.17.0" from the root project
...

### Environment

```shell
System:
    OS: Linux 5.15 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (16) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    npm: 8.11.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    gatsby: 4.6.2 => 4.6.2
    gatsby-cli: ^4.0.0 => 4.17.1
    gatsby-head-style-boss: ^3.2.0 => 3.2.0
    gatsby-plugin-catch-links: ^4.9.0 => 4.17.0
    gatsby-plugin-emotion: ^7.9.0 => 7.17.0
    gatsby-plugin-feed: ^4.9.0 => 4.17.0
    gatsby-plugin-gatsby-cloud: ^4.9.1 => 4.17.0
    gatsby-plugin-google-analytics: ^4.9.0 => 4.17.0
    gatsby-plugin-image: ^2.9.1 => 2.17.0
    gatsby-plugin-manifest: ^4.9.1 => 4.17.0
    gatsby-plugin-offline: ^5.9.1 => 5.17.0
    gatsby-plugin-react-helmet: ^5.9.0 => 5.17.0
    gatsby-plugin-sharp: ^4.9.1 => 4.17.0
    gatsby-remark-autolink-headers: ^5.9.0 => 5.17.0
    gatsby-remark-code-titles: ^1.1.0 => 1.1.0
    gatsby-remark-copy-linked-files: ^5.9.0 => 5.17.0
    gatsby-remark-embed-snippet: ^7.17.0 => 7.17.0
    gatsby-remark-emoji: 0.0.3 => 0.0.3
    gatsby-remark-graphviz: ^4.9.0 => 4.17.0
    gatsby-remark-images: ^6.9.1 => 6.17.0
    gatsby-remark-katex: ^6.17.0 => 6.17.0
    gatsby-remark-prismjs: ^6.17.0 => 6.17.0
    gatsby-remark-responsive-iframe: ^5.9.0 => 5.17.0
    gatsby-remark-smartypants: ^5.9.0 => 5.17.0
    gatsby-remark-table-of-contents: ^2.0.0 => 2.0.0
    gatsby-source-build-date: ^1.0.0 => 1.0.1
    gatsby-source-filesystem: ^4.9.1 => 4.17.0
    gatsby-transformer-remark: ^5.9.1 => 5.17.0
    gatsby-transformer-sharp: ^4.9.0 => 4.17.0
  npmGlobalPackages:
    gatsby-cli: 4.17.1
```

**Comment by tyhopp** [comment]
Hi @EdPike365, thanks for the issue. Having a peer dependency for an older version of a package isn't incorrect if the package still works with that version.

Please provide a [minimal reproduction][reproduction] and a clear description if you encounter some functionality that seems broken. Thank you!

[reproduction]: https://gatsby.dev/reproduction

**Comment by vrabe** [comment]
I think the peer dependency is incorrect. 
(Latest `gatsby-remark-embed-snippet` depends on `gatsby@^4.0.0-next` and `gatsby-remark-prismjs@^4.0.0-next`, but  `gatsby-remark-prismjs@^4.0.0-next` depends on `gatsby@^3.0.0-next.0` and `prismjs@^1.15.0`)
