### ISSUE TITLE
Client-only paths not working anymore on Gatsby Cloud builds

### ISSUE THREAD

**Issue by NSpehler** [gatsbyjs/gatsby#36078]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hello there 👋 

In 3 of my projects using Gatsby Cloud, all of my client-side paths (using the `[slug].js` format as documented [here](https://www.gatsbyjs.com/docs/reference/routing/file-system-route-api/#syntax-client-only-routes)) don't work anymore (they redirect to a 404 page).

I've also reproduced the issue on a brand new repo and the most minimal client-only route, and it doesn't work in Gatsby Cloud. When developing or building locally, it works just fine.

### Reproduction Link

N/A (Gatsby Cloud issue)

### Steps to Reproduce

1. Create a `[slug].js` page in the `pages` directory
2. Run `gatsby build` locally, the page will work fine
3. Setup the project in Gatsby Cloud, the client-only path won't work

### Expected Result

The client-only routes redirect to a 404 page.

### Actual Result

The client-only routes should work as they do when building locally.

### Environment

```shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Safari: 16.0
```

**Comment by LekoArts** [comment]
Please open a support ticket with Gatsby Cloud. Thanks!

https://www.gatsbyjs.com/support
