### ISSUE TITLE
Jest failing to parse a file due to `gatsby-link`: `Cannot use import statement outside a module`

### ISSUE THREAD

**Issue by rupdegraff** [gatsbyjs/gatsby#36079]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

The builds for our three production websites began failing 5 July 2022, each giving a similar message:

![image](https://user-images.githubusercontent.com/22844783/177634981-dff2813f-7bf2-491a-ac91-ae51f879ea13.png)

I solved the issue by adding `|gatsby-link`: 

![image](https://user-images.githubusercontent.com/22844783/177637153-709bafc5-21d1-4f5a-bc19-8cb2565befa8.png)

We've never needed to list `gatsby-link` in `transformIgnorePatterns` prior to this and I'm wondering if this should be added to the documentation here: https://www.gatsbyjs.com/docs/how-to/testing/unit-testing/#2-creating-a-configuration-file-for-jest

![image](https://user-images.githubusercontent.com/22844783/177637548-92117550-805c-4178-a0a0-6e2a0b294459.png)

![image](https://user-images.githubusercontent.com/22844783/177637077-5ad73756-57a7-44d7-92bb-66d2567fa04e.png)

Or perhaps there's a bug in either gatsby or a third-party module which has caused this.

### Reproduction Link

https://github.com/rupdegraff/gatsby-link-jest-issue

### Steps to Reproduce

1. Install the following dependencies

![image](https://user-images.githubusercontent.com/22844783/177813470-948a191c-07ab-42a4-acb2-d4801653181e.png)

2. `gatsby clean`
3. `npm test`
...

### Expected Result

![image](https://user-images.githubusercontent.com/22844783/177670812-b0d66f55-e33a-4e7d-945c-bf93969d5ac3.png)

### Actual Result

![image](https://user-images.githubusercontent.com/22844783/177813855-8ac51a62-a717-4cfd-9626-12d948c13d94.png)

### Environment

```shell
System:
    OS: Windows 8.1 6.3.9600
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
  Binaries:
    Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.10.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.6
  Browsers:
    Chrome: 103.0.5060.114
  npmPackages:
    gatsby: ^4.18.0 => 4.18.0
    gatsby-plugin-algolia: ^0.26.0 => 0.26.0
    gatsby-plugin-google-gtag: ^4.12.1 => 4.18.0
    gatsby-plugin-purgecss: ^6.1.2 => 6.1.2
    gatsby-plugin-react-helmet: ^5.12.1 => 5.18.0
    gatsby-plugin-sass: ^5.12.1 => 5.18.0
    gatsby-plugin-sitemap: ^5.12.1 => 5.18.0
    gatsby-source-filesystem: ^4.12.1 => 4.18.0
    gatsby-source-graphql: ^4.12.1 => 4.18.0
    gatsby-transformer-json: ^4.12.1 => 4.18.0
  npmGlobalPackages:
    gatsby-cli: 4.18.0
```

**Comment by schwigri** [comment]
I am facing the same issue, however even adding `gatsby-link` to `transformIgnorePatterns` is not resolving this issue for me.

**Comment by gh640** [comment]
I met the same issue after updating Gatsby from `4.17.2` to `4.18.0`.

Sample error output:

```text
> my-gatsby-site@1.0.0 test
> jest

 FAIL  src/components/__tests__/link.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /tmp/my-gatsby-site/node_modules/gatsby-link/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import _objectWithoutPropertiesLoose from "@babel/runtime/helpers/objectWithoutPropertiesLoose";
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1796:14)
      at Object.require (node_modules/gatsby/cache-dir/commonjs/gatsby-browser-entry.js:28:43)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.123 s, estimated 1 s
Ran all test suites.
```

Excluding `gatsby-link` as well `gatsby` and `gatsby-script` resolved the error in my env.

### Environment

```text
  System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    npm: 8.13.1 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Safari: 15.5
  npmPackages:
    gatsby: ^4.18.0 => 4.18.0
```

### Reproduction link

https://github.com/gh640/gatsby-link-jest-repro

- `main` branch is for reproducing the error with `npm test`.'
- `fix` branch is a sample for the fix with `gatsby-link` adjustment.

**Comment by gh640** [comment]
This PR might be related:

- https://github.com/gatsbyjs/gatsby/pull/36012

**Comment by gh640** [comment]
A similar issue with `gatsby-script`:

- https://github.com/gatsbyjs/gatsby/issues/35736

**Comment by schwigri** [comment]
> I am facing the same issue, however even adding `gatsby-link` to `transformIgnorePatterns` is not resolving this issue for me. I specifically see this when trying to run Jest on a component using `StaticQuery` and `graphql` combination, Jest runs fine otherwise.
> 
> I am using Gatsby@4.18.0 and typescript only (e.g., all files are typescript, even jest.config.ts and gatsby-config.ts).

For anyone stumbling across this, I had to update my `transform`:

### Before

    transform: { "^.+\\.tsx?$": "<rootDir>/jest/preprocess.ts" },

### After

    transform: { "^.+\\.(t|j)sx?$": "<rootDir>/jest/preprocess.ts" },
