### ISSUE TITLE
gatsby-plugin-sass: Add additionalData sass-loader option

### ISSUE THREAD

**Issue by laneparton** [gatsbyjs/gatsby#36085]
### Preliminary Checks

- [x] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

This isn't as much of a bug as it is a resolution to a warning in the gatsby-plugin-sass config.

sass-loader supports an option called [additionalData](https://webpack.js.org/loaders/sass-loader/#additionaldata) and gatsby-plugin-sass is not aware that this is a valid option.

### Reproduction Link

n/a

### Steps to Reproduce

1. Add additionalData to the options in `gatsby-plugin-sass`
2. Run develop/build
3. Observe warning for invalid plugin option
...

### Expected Result

No warnings, because it is a valid option.

### Actual Result

```
warn Warning: there are unknown plugin options for "gatsby-plugin-sass", configured by
node_modules/@dws-contributes/sitespro-gatsby-base: additionalData
```

### Environment

```shell
System:
    OS: macOS 11.6.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.1.0 - ~/.nvm/versions/node/v18.1.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.8.0 - ~/.nvm/versions/node/v18.1.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 91.0.4472.164
    Firefox: 100.0
    Safari: 15.5
  npmPackages:
    gatsby: ^4.18.0 => 4.18.0
```

**Comment by j0sh77** [comment]
Thanks for reaching out _and_ offering a PR! Looks like we've got a solution pending test updates. 😄
