### ISSUE TITLE
Cypress version in "End-to-End Testing" page 

### ISSUE THREAD

**Issue by gh640** [gatsbyjs/gatsby#36097]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

The current latest version of Cypress is 10.x. 10.0.0 was released at Jun 02, 2022.

- https://github.com/cypress-io/cypress/releases/tag/v10.0.0

The current description in ["End-to-End Testing" doc page](https://www.gatsbyjs.com/docs/how-to/testing/end-to-end-testing/) is correct for Cypress 9.x but incorrect for Cypress 10.x. It's better to mention the target version (9.x) or to update the page for Cypress 10.x.

The migration guide from 9.x to 10.x:

- https://docs.cypress.io/guides/references/migration-guide

### Steps to Resolve this Issue

1. Update the linked doc page to show how Cypress is used in Version 10
2. Update the linked example (https://github.com/gatsbyjs/gatsby/tree/master/examples/using-cypress) to Version 10, too

**Comment by LekoArts** [comment]
Feel free to put up a PR updating the page to version 10 👍

**Comment by shikhar13012001** [comment]
I would like to work on this issue @LekoArts

**Comment by manthony9** [comment]
@gh640 @LekoArts is this issue just for the documentation update or does it include the actual migration too ?

**Comment by LekoArts** [comment]
It would be updating both the page and example (see "Steps to resolve this issue")

**Comment by nodebotanist** [comment]
I've got the upgrade working and I should have a PR by EOD today 7/21

**Comment by nodebotanist** [comment]
We can close this, the PR was merged.
