### ISSUE TITLE
Community section - Translations redirection

### ISSUE THREAD

**Issue by mbiesiad** [gatsbyjs/gatsby#36092]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

On the main site, the Translations link is doesn't work correct.

# Steps to Reproduce
1. Go to: https://www.gatsbyjs.com
2. Scroll down and click 'Translations' (or just type https://www.gatsbyjs.com/contributing/translation/)
3. See the issue

It's a little bit similar / related to the issue https://github.com/gatsbyjs/gatsby/issues/31883 (related PR 32328)
Perhaps related with changes https://github.com/gatsbyjs/gatsby/commit/4cb514f7a545a0afa0b718e07f7c75688122f225

Best wishes,

### Steps to Resolve this Issue

There is few ways to resolve this. One of the way is make it similar like solutions with issue 31883 (related PR 32328) - add a proper info.

**Comment by LekoArts** [comment]
Hi! The redirect is working as intended. We no longer pursue the translation effort and thus the page was deleted. If you still visit that link, it'll be redirected.

The link in the footer will be removed
