### ISSUE TITLE
File System Collection Routes don't update on changes to data

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#36090]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

If you create a collection route e.g. `src/pages/{MarkdownRemark.frontmatter__slug}.js` — pages will be created correctly when you start the develop server but any changes to markdown pages aren't picked up — either a change to a slug or a new markdown file. The develop server must be restarted for this to take effect.

### Reproduction Link

https://www.gatsbyjs.com/docs/how-to/routing/adding-markdown-pages/#create-a-collection-route-for-the-markdown-files

### Steps to Reproduce

1. Build a site with a fs collection route e.g. following this guide https://www.gatsbyjs.com/docs/how-to/routing/adding-markdown-pages/#create-a-collection-route-for-the-markdown-files
2. change the data associated with the route
3. notice the page isn't updated

### Expected Result

Routes are recreated when their associated data changes.

### Actual Result

They don't change until the dev server is restarted.

### Environment

```shell
n/a
```

### Config Flags

n/a

I POCed a fix to this last year — https://github.com/gatsbyjs/gatsby/commit/b3eb68989b83f6bccb53017a76e13b41584393f8

The algorithm in short is a) the framework tracks which nodes are created/updated/deleted and b) gatsby-plugin-page-creator uses that in `createPages` to see if any pages it owns need to be deleted or new ones created e.g. if it's using the type `MarkdownRemark` and a new MarkdownRemark node is created — then it creates a new page just like it does upfront.

**Comment by keegankb93** [comment]
This is something that would be very much desired for our workflow.

We currently use Strapi and Gatsby together where Strapi serves as our CMS for our website and app.

Our website's pages are currently all created dynamically via the fs api and Strapi dynamic zones and are housed in specific collections. For example, we have a 'RootPages' collection that houses our pages that are located on the root. We also have a 'FeaturePages' collection that houses our features. 

Generally, our marketing team handles content and we have it setup with content-sync as well, so previewing the content before it's pushed to our live site is paramount. Using the above scenario, if we implement a new feature and marketing needs to add that feature to our site, the workflow would be to create a new page in the 'FeaturePages' section. The anticipated outcome would be that the preview rebuilds the routes and the new page allowing us to preview the new feature page.

The only way to do this currently is to log into GatsbyCloud and hit the 'restart preview' button to rebuilt the entire preview.
