### ISSUE TITLE
No warning for gatsby-node.tsx

### ISSUE THREAD

**Issue by arsinclair** [gatsbyjs/gatsby#36127]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

This issue might be a question (and I [posted it on the Discussions](https://github.com/gatsbyjs/gatsby/discussions/36093) and got no replies at all), however it might qualify as a bug as well.

After I upgraded Gatsby from 4.6.2 to 4.18.0 the `gatsby build` fails like this

>  ERROR #98124  WEBPACK
Generating JavaScript bundles failed
Can't resolve '~/components/SEO' in 'F:\GIT\new-project\src\pages\{languagesJson.language}'

> If you're trying to use a package make sure that '~/components/SEO' is installed. If you're trying to use a local file make sure that the path is correct.

> File: src\pages\{languagesJson.language}\404.tsx:1:121

It fails on all pages and components where a custom import is used, like this

```ts
import { SEO } from "~/components/SEO";
```

I have the following configuration in the _tsconfig.json_:

```json
{
    "extends": "@tsconfig/node16/tsconfig.json",
    "compilerOptions": {
        ...,
        "baseUrl": ".",
        "paths": {
            "~/*": ["src/*"]
        }
    }
}
```

and the following in _gatsby-node.tsx_:

```ts
export const onCreateWebpackConfig: GatsbyNode["onCreateWebpackConfig"] = ({ actions }) => {
    actions.setWebpackConfig({
        resolve: {
            alias: {
                "~": path.resolve("src")
            }
        }
    });
```

I have a feeling this is related to Parcel Limitations, mentioned here: https://www.gatsbyjs.com/docs/how-to/custom-configuration/typescript/#current-limitations, however I don't know what a Parcel is and why it used to work before and now suddenly fails.

What can be done about it? Is it a bug?

Can I somehow make it work, or in order to use the new version of Gatsby I have to update all my imports to use relative paths?

### Steps to Reproduce

1. Install Gatsby 4.6.2
2. Configure a custom path in tsconfig.json, then implement a component and import it to a page using the custom path (see an example in the description)
3. Run `gatsby develop` and check that the page is working
4. Upgrade Gatsby to 4.18.0
5. Run `gatsby develop` and a compile error

### Expected Result

Expect custom paths to work

### Actual Result

Compilation fails.

### Environment

```shell
System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.10.5 - /c/Users/user/AppData/Local/Programs/Python/Python310/python
  Browsers: {}
  npmPackages:
    gatsby: ^4.18.0 => 4.18.0 
    gatsby-background-image: ^1.6.0 => 1.6.0 
    gatsby-cli: ^4.6.1 => 4.18.0 
    gatsby-image: ^3.1.0 => 3.11.0 
    gatsby-plugin-canonical-urls: ^4.18.0 => 4.18.0 
    gatsby-plugin-google-gtag: ^4.18.0 => 4.18.0 
    gatsby-plugin-image: ^2.18.0 => 2.18.0 
    gatsby-plugin-imgix: ^0.9.0 => 0.9.1 
    gatsby-plugin-manifest: ^4.18.0 => 4.18.0 
    gatsby-plugin-netlify: ^5.0.0 => 5.0.0 
    gatsby-plugin-offline: ^5.18.0 => 5.18.0 
    gatsby-plugin-polished: ^1.0.4 => 1.0.4 
    gatsby-plugin-preload-fonts: ^3.18.0 => 3.18.0 
    gatsby-plugin-react-helmet: ^5.18.0 => 5.18.0 
    gatsby-plugin-remove-generator: ^1.1.0 => 1.2.0 
    gatsby-plugin-sharp: ^4.18.0 => 4.18.0 
    gatsby-plugin-sitemap: ^5.18.0 => 5.18.0 
    gatsby-plugin-styled-components: ^5.18.0 => 5.18.0 
    gatsby-plugin-typescript: ^4.6.0 => 4.18.0 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-source-datocms: ^4.0.4 => 4.0.4 
    gatsby-source-filesystem: ^4.18.0 => 4.18.0 
    gatsby-transformer-json: ^4.18.0 => 4.18.0 
    gatsby-transformer-sharp: ^4.18.0 => 4.18.0
```

**Comment by arsinclair** [comment]
Here's a reproduction repo: https://github.com/arsinclair/gatsby-ts-custom-paths-reproduction

**Comment by arsinclair** [comment]
@LekoArts the reproduction is provided, please update the status.

**Comment by pieh** [comment]
I could not get repro to work with older version of gatsby, I get same/similar result regardless if I use 4.18, 4.6, or 3.

Gatsby is using `@babel/preset-typescript` to handle typescript for bundles for a long time and that doesn't make use of `tsconfig` file.

The Parcel limitations you linked to apply only to `gatsby-config` and `gatsby-node` (and their imports), so it isn't applicable here.

If you need path aliasing - you will need to add following snippet to `gatsby-node.ts` (or use js version of it):

```ts
import { resolve } from "path";
import type { GatsbyNode } from "gatsby";

export const onCreateWebpackConfig: GatsbyNode["onCreateWebpackConfig"] = ({
  actions,
}) => {
  actions.setWebpackConfig({
    resolve: {
      alias: {
        "~": resolve(__dirname, `src`),
      },
    },
  });
};
```

**Comment by arsinclair** [comment]
@pieh I wonder why you can't reproduce. I've tried on two different workstations, one Windows and another one Debian Linux, the result is the same. As soon as I install dependencies and run `gatsby build` I get this:

![image](https://user-images.githubusercontent.com/2878904/182063780-bf890e02-d4d6-4a06-8c87-5c2e34a7a2ee.png)

As soon as change the import `import TestComponent from "~/components/testcomponent"` in _index.tsx_ to `import TestComponent from "../components/testcomponent"` and run the build again, the issue doesn't reproduce.

**Comment by arsinclair** [comment]
I figured it out. My file is called `gatsby-node.tsx` and that's why it is not working. If I rename it to `gatsby-node.ts` it starts working.

I've updated the reproduction repo, so it is reproduced now.

I'll leave it to you to decide if this is a bug or not. From my standpoint, I think it's a bug - `.tsx` files should be processed exactly like `.ts` files.

**Comment by arsinclair** [comment]
@pieh thanks for your help!

**Comment by pieh** [comment]
> I'll leave it to you to decide if this is a bug or not. From my standpoint, I think it's a bug - `.tsx` files should be processed exactly like `.ts` files.

This is interesting point. `.jsx` / `.tsx` were introduced to signal JSX parsing mode. And we do support them for files where you write jsx syntax - so your components etc ... but also `gatsby-browser.tsx` and `gatsby-ssr.tsx` are both supported (because you would put actual React code in there for some APIs).

The `gatsby-node` and `gatsby-config` are files that SHOULD NOT have any react components inside (no `React.createElement`, no JSX). It feels like supporting `.tsx` extension might signal that react code is fine there when it's not.

**Comment by arsinclair** [comment]
> The gatsby-node and gatsby-config are files that SHOULD NOT have any react components inside (no React.createElement, no JSX).

You have a point. 

Maybe then gatsby should reject (or notify) processing gatsby-node if it has a _jsx_ / _tsx_ extension whatsoever. Because right now it's slightly ambiguous: if it wasn't for webpack config override, everything would have worked.

**Comment by pieh** [comment]
> Maybe then gatsby should reject (or notify) processing gatsby-node if it has a _.jsx_ / _.tsx_ extension whatsoever. Because right now it's slightly ambiguous: if it wasn't for webpack config override, everything would have worked.

That's what I'm thinking of right now. We already have something like that for gatsby-config:

```
success compile gatsby files - 0.915s

 ERROR #10124  CONFIG

It looks like you were trying to add the config file? Please rename "gatsby-config.tsx" to "gatsby-config.js"



  Error: Cannot find module '/home/misiek/test/blog/gatsby-config'
```

but not `gatsby-node` yet

**Comment by arsinclair** [comment]
Ah, that's a great idea!
