### ISSUE TITLE
Using a local font does not work

### ISSUE THREAD

**Issue by aidan-rypens** [gatsbyjs/gatsby#36123]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Font family is not applied. Followed the recipes from the website.

### Steps to Reproduce

A new gatsby project.

1. Added fonts (woff2) in `src\fonts\ArticulatCF\...`
2. Added a `src\fonts\fonts.css` with the following font face's:
```
@font-face {
  font-family: "Articulat CF", sans-serif;
  font-weight: 100;
  font-style: normal;
  font-display: swap;
  src: url("./ArticulatCF/ArticulatCF-Thin.woff2") format("woff2");
}
```

3. Imported this CSS file with `import "./src/fonts/fonts.css";` in `gatsby-browser.ts`.

Checked the following:
- Font is downloaded in the browser tab
- Font is wrapped with " "
- Checked or font is present in browser
- Develop vs production build does not differ

### Expected Result

Fonts should be usable.

### Actual Result

Font family is not applied.

### Environment

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 18.4.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.10.5
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.44)
  npmPackages:
    gatsby: ^4.17.2 => 4.17.2
    gatsby-plugin-react-helmet: ^5.17.0 => 5.17.0
    gatsby-plugin-sitemap: ^5.17.0 => 5.17.0
  npmGlobalPackages:
    gatsby-cli: 4.18.1
```

**Comment by AidanRRR** [comment]
Very weird results. Tried a new project, it does work with different local fonts.
In [this](https://github.com/AidanRRR/CWX.IRS.Website) specific repo fonts are loaded (checked in network tab) and styles are applied.

Does it matter in which order things are loaded in or something? The font face happens before importing the font.
