### ISSUE TITLE
WordPress Preview Doesn't Get Past The "Deploying..." Step

### ISSUE THREAD

**Issue by ui-jb** [gatsbyjs/gatsby#36163]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

My team and I are trying to enable Gatsby Previews from our WordPress environment, but have been running into issues.

We've followed this guide step by step: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/tutorials/configuring-wp-gatsby.md#setting-up-preview

The preview page show that it gets to the "Deploying..." step, but then an error is shown.
![Pasted Graphic](https://user-images.githubusercontent.com/90284201/179599284-b816085a-7158-45ad-b0ac-1dafe2d18cda.png)
![Pasted Graphic 1](https://user-images.githubusercontent.com/90284201/179599337-70e1aaa7-3788-40b4-9c14-4261799dc3f5.png)

When I click on "View Error Logs", it takes me to the preview build history, which only shows successful builds:
![Pasted Graphic 3](https://user-images.githubusercontent.com/90284201/179599492-bbb2a725-67d7-4228-a477-79725ff15602.png)

### Reproduction Link

-

### Steps to Reproduce

1. Create a Gatsby Site and Host it on Gatsby Cloud
2. Enable CMS Previews
3. Follow this guide step by step to hook up Gatsby Preview to WordPress: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/tutorials/configuring-wp-gatsby.md#setting-up-preview
4. Click the "Preview" button while editing a page in WordPress

### Expected Result

A Preview of the page using Gatsby should be shown to the user.

### Actual Result

An error page is displayed that links the user to a Gatsby Cloud page that only shows successful builds.

### Environment

```shell
System:
    OS: macOS 11.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 90.0.2
    Safari: 14.1.2
  npmPackages:
    gatsby: ^3.14.0 => 3.14.0 
    gatsby-background-image: ^1.5.3 => 1.5.3 
    gatsby-image: ^3.11.0 => 3.11.0 
    gatsby-plugin-external-css: ^1.0.1 => 1.0.1 
    gatsby-plugin-gatsby-cloud: ^3.2.0 => 3.2.0 
    gatsby-plugin-google-analytics: ^4.0.0 => 4.0.0 
    gatsby-plugin-google-tagmanager: ^4.0.0 => 4.0.0 
    gatsby-plugin-image: ^1.14.0 => 1.14.0 
    gatsby-plugin-manifest: ^3.14.0 => 3.14.0 
    gatsby-plugin-offline: ^4.14.0 => 4.14.0 
    gatsby-plugin-react-helmet: ^4.14.0 => 4.14.0 
    gatsby-plugin-react-svg: ^3.1.0 => 3.1.0 
    gatsby-plugin-robots-txt: ^1.6.14 => 1.6.14 
    gatsby-plugin-rollbar: ^1.1.0 => 1.1.0 
    gatsby-plugin-sharp: ^3.14.0 => 3.14.0 
    gatsby-plugin-wpgraphql-seo: ^1.2.2 => 1.2.2 
    gatsby-remark-responsive-iframe: ^4.11.0 => 4.11.0 
    gatsby-source-filesystem: ^3.14.0 => 3.14.0 
    gatsby-source-graphql: ^3.14.0 => 3.14.0 
    gatsby-source-wordpress: ^5.14.2 => 5.14.2 
    gatsby-transformer-sharp: ^3.14.0 => 3.14.0
```

### Config Flags

 FAST_DEV: true,
 DEV_WEBPACK_CACHE: true,
 PRESERVE_FILE_DOWNLOAD_CACHE: true,
 PARALLEL_SOURCING: true

**Comment by TylerBarnes** [comment]
Hi @ui-jb , can you open a Gatsby Cloud support ticket instead? These kinds of issues are usually specific to individual sites so it's easier for us to solve through Gatsby Cloud support. Thanks!

**Comment by ui-jb** [comment]
Hi @TylerBarnes, do you have a link where I can file a ticket? Google doesn't give me any results and I don't see any links while I'm logged into Gatsby Cloud.

**Comment by ui-jb** [comment]
Thank you!
