### ISSUE TITLE
Looks like the new release broke builds in Gatsby Cloud? @gatsby-cloud-pkg/gatsby-inc-build-cli: Not found

### ISSUE THREAD

**Issue by njbmartin** [gatsbyjs/gatsby#36187]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

![image](https://user-images.githubusercontent.com/5699471/179937541-ec6458c6-5f11-42f7-9c27-411e0324ea62.png)

That says it all really...

### Reproduction Link

N/A

### Steps to Reproduce

1. Use Gatsby Cloud on a previous version of Gatsby.

### Expected Result

Gatsby Cloud should just work...

### Actual Result

It does not...

### Environment

```shell
Gatsby Cloud...
```

**Comment by LekoArts** [comment]
For Gatsby Cloud related issues please use https://www.gatsbyjs.com/support
