### ISSUE TITLE
Gatsby Cloud language-based redirects ignore the `Accept-Language` header quality values

### ISSUE THREAD

**Issue by FelDev** [gatsbyjs/gatsby#36226]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

If I define a redirect like so:
```js
createRedirect({
    fromPath: `/`,
    toPath: `/en/`,
    conditions: {
      language: [`en`],
    },
  })
```
It will redirect to `/en/` as long as English is present in the request's `Accept-Language` header.

But it ignores the quality value (a.k.a. "weigth") of the languages.

If the `/` route is in French and the Accept-Language header is like so:
`Accept-Language: fr-CA,en-CA;q=0.5`
Gatsby will redirect to the English homepage even though English is defined as the second choice by the user.

The behaviour is perfect only if English is completely absent, eg;
`Accept-Language: fr-CA`

### Reproduction Link

https://github.com/FelDev/gatsby-bug-repro

### Steps to Reproduce

1. Create a language based redirect
2. Have a browser which accepts many languages, but prefers one in particular.. 
![Capture d’écran, le 2022-07-24 à 22 46 49](https://user-images.githubusercontent.com/17578204/180683882-1a1bf3fb-1975-4093-836a-50f169fe7db7.png)

3. Visit the page.

### Expected Result

There should be a way to account for the [quality values](https://developer.mozilla.org/en-US/docs/Glossary/Quality_values) of languages in the [Accept-Language headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language).

### Actual Result

There is not.

Here is a repro:
https://build-036ac0c9-fdf2-4c8e-8226-f36c34519aa8.gtsb.io/

### Environment

```shell
Gatsby Cloud.
```

---
edit: After creating the repro and writing all this, I realize this might be considered a feature request after all... Feel free to convert into one.

**Comment by LekoArts** [comment]
For Gatsby Cloud related issues please reach out to the support here: https://www.gatsbyjs.com/support

Thanks!
