### ISSUE TITLE
--https doesn't work since Gatsby 4.19.0

### ISSUE THREAD

**Issue by jens-duttke** [gatsbyjs/gatsby#36241]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

The [Local HTTPS Option](https://www.gatsbyjs.com/docs/local-https/) (`--https`) doesn't work anymore in Gatsby Version 4.19.0, 4.19.1 and 4.19.2.
The terminal still shows:

> You can now view my-gatsby-site in the browser.
>   https://localhost:8000/

But in the browser, only `http://localhost:8000/` works.

This is reproducable in gatsby-starter bundle, by simply appending `--https --key-file ....key --cert-file ....cert` to the start-script.

### Reproduction Link

https://github.com/jens-duttke/gatsby-https-fault

### Steps to Reproduce

1. git clone https://github.com/jens-duttke/gatsby-https-fault.git
2. cd gatsby-https-fault
3. npm i
4. npm start
5. Go to https://localhost:8000/ as shown in the terminal

### Expected Result

The page will be shown

### Actual Result

ERR_SSL_PROTOCOL_ERROR

### Environment

```shell
Windows 10 Pro, Gatsby 4.19.x
```

### Config Flags

None

**Comment by pieh** [comment]
Can confirm, opened https://github.com/gatsbyjs/gatsby/pull/36248 with the fix
