### ISSUE TITLE
graphqlTypegen generating wrong Type definitions for gatsby-plugin-image + gatsby-source-contentful

### ISSUE THREAD

**Issue by Mike-Logit** [gatsbyjs/gatsby#36243]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description
TL;DR The TypeScript generated by Gatsby using the `graphqlTypegen` setting defined in gatsby-config.ts is wrong.

I'm using the following package versions to query gatsbyImageData from Contentful using TypeScript:

```
  "dependencies": {
    "gatsby": "^4.19.2",
    "gatsby-plugin-image": "^2.19.0",
    "gatsby-plugin-sharp": "^4.19.0",
    "gatsby-source-contentful": "^7.17.0",
    "gatsby-transformer-sharp": "^4.19.0",
    "react": "^18.1.0",
    "react-dom": "^18.1.0"
  },
  "devDependencies": {
    "@types/node": "^17.0.45",
    "@types/react": "^18.0.15",
    "@types/react-dom": "^18.0.6",
    "typescript": "^4.7.4"
  }
```

I'm also using `graphqlTypegen` declared in `gatsby-config.ts` to generate types for my Contentful assets to add TypeScript support.

I query images from Contentful using the following example query (by following the [migration guide](https://www.gatsbyjs.com/docs/reference/release-notes/image-migration-guide) and the relevant plugin documentation):

```
  const { allContentfulProduct } = useStaticQuery<Queries.Query>(graphql`
    query {
      allContentfulProduct(limit: 1) {
        nodes {
          image {
            gatsbyImageData(height: 260, width: 380, layout: CONSTRAINED)
          }
        }
      }
    }
  `);
```

The problem is that the following use of the `GatsbyImage` component does not work with this product image I queried for, despite the `gatsbyImage` value being the correct TypeScript type being supplied for the image property:

```
<GatsbyImage
  alt="gatsbyImage"
  image={productImageAsset.gatsbyImage}
/>
```

And using the `gatsbyImageData` property available to me works but is not the correct TypeScript type:
```
<GatsbyImage
  alt="gatsbyImageData"
  image={productImageAsset.gatsbyImageData} // I'm seeing an error reported here but the image shows as expected
/>
```

The generated TypeScript looks like this:
```
type ContentfulAsset = ContentfulReference & Node & RemoteFile & {
  // omitted other properties for brevity...

  /** Data used in the <GatsbyImage /> component. See https://gatsby.dev/img for more info. */
  readonly gatsbyImage: Maybe<Scalars['GatsbyImageData']>;
  readonly gatsbyImageData: Maybe<Scalars['JSON']>;

 // omitted other properties for brevity...
}
```

And the typing definition for the "image" property used by the GatsbyImage component looks like this:

```
export interface GatsbyImageProps extends ... {
     // omitted other properties for brevity...

    image: IGatsbyImageData;
  
     // omitted other properties for brevity...
}
```

So, TypeScript is telling me to use "gatsbyImage" (which results in no image being displayed) instead of "gatsbyImageData" (which shows my image and the plugin works as expected):

![image](https://user-images.githubusercontent.com/41903446/181107120-8df070d0-9003-4c88-8160-d5479be386c2.png)

So I believe the TypeScript being generated is wrong for this scenario as I have to ignore the typing errors for it to work.

### Reproduction Link

https://codesandbox.io/s/vigilant-golick-ekfgim?file=/src/pages/index.tsx

### Steps to Reproduce

1. Open the CodeSandbox link or VSCode
2. Install dependencies from `package.json` using `npm i` if using VSCode. CodeSandbox should do this automatically.
3. If using VSCode, run `gatsby develop`
4. You should see an error with a red squiggly line below `image={productImageAsset.gatsbyImageData}` despite it working correctly due to a typing issue from the generated TypeScript.

### Expected Result

The generated TypeScript should be correct so that you can pass `gatsbyImageData` in the ContentfulAsset to the GatsbyImage component without a TypeScript error due to the wrong types being generated.

### Actual Result

You need to use `gatsbyImageData` for the image to show even though it is not of type `IGatsbyImageData` and the GatsbyImage component expects a type of `IGatsbyImageData` passed to the image property, so this is wrong:

```
type ContentfulAsset = ContentfulReference & Node & RemoteFile & {
  // omitted other properties for brevity...

  /** Data used in the <GatsbyImage /> component. See https://gatsby.dev/img for more info. */
  readonly gatsbyImage: Maybe<Scalars['GatsbyImageData']>; // DOES NOT WORK
  readonly gatsbyImageData: Maybe<Scalars['JSON']>; // WORKS!! But not of type IGatsbyImageData...

 // omitted other properties for brevity...
}
```

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Binaries:
    Node: 18.4.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.12.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.13
  Browsers:
    Edge: 44.19041.1266.0
  npmPackages:
    gatsby: ^4.19.2 => 4.19.2 
    gatsby-plugin-image: ^2.19.0 => 2.19.0 
    gatsby-plugin-sharp: ^4.19.0 => 4.19.0 
    gatsby-source-contentful: ^7.17.0 => 7.17.0 
    gatsby-transformer-sharp: ^4.19.0 => 4.19.0
```

**Comment by Mike-Logit** [comment]
Or am I supposed to query for `gatsbyImage` like this?:

```
const { allContentfulProduct } = useStaticQuery<Queries.Query>(graphql`
  query {
    allContentfulProduct(limit: 1) {
      nodes {
        image {
          gatsbyImage(height: 260, width: 380, layout: CONSTRAINED)
        }
      }
    }
  }
`);
```

And is the [`gatsby-source-contentful` documentation](https://www.gatsbyjs.com/plugins/gatsby-source-contentful/#query-for-assets-in-contenttype-nodes) wrong?

**Comment by Mike-Logit** [comment]
I think it's a documentation issue because I'm pretty sure now that I need to be using `gatsbyImage` as suggested by the generated TypeScript and go against what the documentation suggests or mislead me to believe I needed to use `gatsbyImageData` (please correct me if this is wrong).

The graphql results for both shows that I get more data from `gatsbyImage` and the image looks a bit better quality unless my eyes are playing tricks.

```
{
  "data": {
    "allContentfulProduct": {
      "nodes": [
        {
          "image": [
            {
              "gatsbyImageData": {
                "images": {
                  "sources": [
                    {
                      "srcSet": "https://images.ctfassets.net/rocybtov1ozk/wtrHxeu3zEoEce2MokCSi/73dce36715f16e27cf5ff0d2d97d7dff/quwowooybuqbl6ntboz3.jpg?w=95&h=65&q=50&fm=webp 95w,\nhttps://images.ctfassets.net/rocybtov1ozk/wtrHxeu3zEoEce2MokCSi/73dce36715f16e27cf5ff0d2d97d7dff/quwowooybuqbl6ntboz3.jpg?w=190&h=130&q=50&fm=webp 190w,\nhttps://images.ctfassets.net/rocybtov1ozk/wtrHxeu3zEoEce2MokCSi/73dce36715f16e27cf5ff0d2d97d7dff/quwowooybuqbl6ntboz3.jpg?w=380&h=260&q=50&fm=webp 380w",
                      "sizes": "(min-width: 380px) 380px, 100vw",
                      "type": "image/webp"
                    }
                  ],
                  "fallback": {
                    "src": "https://images.ctfassets.net/rocybtov1ozk/wtrHxeu3zEoEce2MokCSi/73dce36715f16e27cf5ff0d2d97d7dff/quwowooybuqbl6ntboz3.jpg?w=380&h=260&fl=progressive&q=50&fm=jpg",
                    "srcSet": "https://images.ctfassets.net/rocybtov1ozk/wtrHxeu3zEoEce2MokCSi/73dce36715f16e27cf5ff0d2d97d7dff/quwowooybuqbl6ntboz3.jpg?w=95&h=65&fl=progressive&q=50&fm=jpg 95w,\nhttps://images.ctfassets.net/rocybtov1ozk/wtrHxeu3zEoEce2MokCSi/73dce36715f16e27cf5ff0d2d97d7dff/quwowooybuqbl6ntboz3.jpg?w=190&h=130&fl=progressive&q=50&fm=jpg 190w,\nhttps://images.ctfassets.net/rocybtov1ozk/wtrHxeu3zEoEce2MokCSi/73dce36715f16e27cf5ff0d2d97d7dff/quwowooybuqbl6ntboz3.jpg?w=380&h=260&fl=progressive&q=50&fm=jpg 380w",
                    "sizes": "(min-width: 380px) 380px, 100vw"
                  }
                },
                "layout": "constrained",
                "backgroundColor": "#f8f8f8",
                "width": 380,
                "height": 260
              },
              "gatsbyImage": {
                "images": {
                  "sources": [
                    {
                      "srcSet": "/_gatsby/image/ddbbbdef885f28f63d5be5082c4c362e/c956e60f39d9c202adf035901d4c496b/quwowooybuqbl6ntboz3.avif?u=https%3A%2F%2Fimages.ctfassets.net%2Frocybtov1ozk%2FwtrHxeu3zEoEce2MokCSi%2F73dce36715f16e27cf5ff0d2d97d7dff%2Fquwowooybuqbl6ntboz3.jpg&a=w%3D95%26h%3D65%26fm%3Davif%26q%3D75&cd=2017-06-27T09%3A35%3A36.037Z 95w,/_gatsby/image/ddbbbdef885f28f63d5be5082c4c362e/58f8b7539c441cb54bb119bea44400c3/quwowooybuqbl6ntboz3.avif?u=https%3A%2F%2Fimages.ctfassets.net%2Frocybtov1ozk%2FwtrHxeu3zEoEce2MokCSi%2F73dce36715f16e27cf5ff0d2d97d7dff%2Fquwowooybuqbl6ntboz3.jpg&a=w%3D190%26h%3D130%26fm%3Davif%26q%3D75&cd=2017-06-27T09%3A35%3A36.037Z 190w,/_gatsby/image/ddbbbdef885f28f63d5be5082c4c362e/1828e81a6ce8e0640c281ae4cd9f0497/quwowooybuqbl6ntboz3.avif?u=https%3A%2F%2Fimages.ctfassets.net%2Frocybtov1ozk%2FwtrHxeu3zEoEce2MokCSi%2F73dce36715f16e27cf5ff0d2d97d7dff%2Fquwowooybuqbl6ntboz3.jpg&a=w%3D380%26h%3D260%26fm%3Davif%26q%3D75&cd=2017-06-27T09%3A35%3A36.037Z 380w",
                      "type": "image/avif",
                      "sizes": "(min-width: 380px) 380px, 100vw"
                    },
                    {
                      "srcSet": "/_gatsby/image/ddbbbdef885f28f63d5be5082c4c362e/78f6822dc9bb17de75e2496800894fbd/quwowooybuqbl6ntboz3.webp?u=https%3A%2F%2Fimages.ctfassets.net%2Frocybtov1ozk%2FwtrHxeu3zEoEce2MokCSi%2F73dce36715f16e27cf5ff0d2d97d7dff%2Fquwowooybuqbl6ntboz3.jpg&a=w%3D95%26h%3D65%26fm%3Dwebp%26q%3D75&cd=2017-06-27T09%3A35%3A36.037Z 95w,/_gatsby/image/ddbbbdef885f28f63d5be5082c4c362e/d1dedcd1093271312b4ba1395d9c6774/quwowooybuqbl6ntboz3.webp?u=https%3A%2F%2Fimages.ctfassets.net%2Frocybtov1ozk%2FwtrHxeu3zEoEce2MokCSi%2F73dce36715f16e27cf5ff0d2d97d7dff%2Fquwowooybuqbl6ntboz3.jpg&a=w%3D190%26h%3D130%26fm%3Dwebp%26q%3D75&cd=2017-06-27T09%3A35%3A36.037Z 190w,/_gatsby/image/ddbbbdef885f28f63d5be5082c4c362e/6a101cad019d06e7efc4d7483dc299ba/quwowooybuqbl6ntboz3.webp?u=https%3A%2F%2Fimages.ctfassets.net%2Frocybtov1ozk%2FwtrHxeu3zEoEce2MokCSi%2F73dce36715f16e27cf5ff0d2d97d7dff%2Fquwowooybuqbl6ntboz3.jpg&a=w%3D380%26h%3D260%26fm%3Dwebp%26q%3D75&cd=2017-06-27T09%3A35%3A36.037Z 380w",
                      "type": "image/webp",
                      "sizes": "(min-width: 380px) 380px, 100vw"
                    }
                  ],
                  "fallback": {
                    "src": "/_gatsby/image/ddbbbdef885f28f63d5be5082c4c362e/2775d2f76c57a4452ca1fb737ba4c7cd/quwowooybuqbl6ntboz3.jpg?u=https%3A%2F%2Fimages.ctfassets.net%2Frocybtov1ozk%2FwtrHxeu3zEoEce2MokCSi%2F73dce36715f16e27cf5ff0d2d97d7dff%2Fquwowooybuqbl6ntboz3.jpg&a=w%3D95%26h%3D65%26fm%3Djpg%26q%3D75&cd=2017-06-27T09%3A35%3A36.037Z",
                    "srcSet": "/_gatsby/image/ddbbbdef885f28f63d5be5082c4c362e/2775d2f76c57a4452ca1fb737ba4c7cd/quwowooybuqbl6ntboz3.jpg?u=https%3A%2F%2Fimages.ctfassets.net%2Frocybtov1ozk%2FwtrHxeu3zEoEce2MokCSi%2F73dce36715f16e27cf5ff0d2d97d7dff%2Fquwowooybuqbl6ntboz3.jpg&a=w%3D95%26h%3D65%26fm%3Djpg%26q%3D75&cd=2017-06-27T09%3A35%3A36.037Z 95w,/_gatsby/image/ddbbbdef885f28f63d5be5082c4c362e/5d6687389f1e16ddb8f5a1f86a879ab0/quwowooybuqbl6ntboz3.jpg?u=https%3A%2F%2Fimages.ctfassets.net%2Frocybtov1ozk%2FwtrHxeu3zEoEce2MokCSi%2F73dce36715f16e27cf5ff0d2d97d7dff%2Fquwowooybuqbl6ntboz3.jpg&a=w%3D190%26h%3D130%26fm%3Djpg%26q%3D75&cd=2017-06-27T09%3A35%3A36.037Z 190w,/_gatsby/image/ddbbbdef885f28f63d5be5082c4c362e/02d8c002eb4a117b1cf599bfebf854dd/quwowooybuqbl6ntboz3.jpg?u=https%3A%2F%2Fimages.ctfassets.net%2Frocybtov1ozk%2FwtrHxeu3zEoEce2MokCSi%2F73dce36715f16e27cf5ff0d2d97d7dff%2Fquwowooybuqbl6ntboz3.jpg&a=w%3D380%26h%3D260%26fm%3Djpg%26q%3D75&cd=2017-06-27T09%3A35%3A36.037Z 380w",
                    "sizes": "(min-width: 380px) 380px, 100vw"
                  }
                },
                "layout": "constrained",
                "width": 380,
                "height": 260,
                "backgroundColor": "rgb(248,248,248)"
              }
            }
          ]
        }
      ]
    }
  },
  "extensions": {}
}
```

**Comment by Mike-Logit** [comment]
When I viewed the gatsby production build on our test server the images were frequently failing to load. I changed both the query and value used on the GatsbyImage component to use the value from the graphql `gatsbyImageData` field and now the images work as expected, so the Typescript type is wrong as the bug report previously suggested.

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

`gatsbyImage` is only needed for Image CDN: https://www.gatsbyjs.com/blog/image-cdn-lightning-fast-image-processing-for-gatsby-cloud/. So for this issue it's not relevant as you'll want to use `gatsbyImageData`.

So the `gatsbyImageData` field from `ContentfulAsset` is defined here: https://github.com/gatsbyjs/gatsby/blob/0ee492c8bf11917dc08b16acebe92bb752bdc3b7/packages/gatsby-source-contentful/src/create-schema-customization.js#L125

It uses `getGatsbyImageFieldConfig` from here: https://github.com/gatsbyjs/gatsby/blob/0ee492c8bf11917dc08b16acebe92bb752bdc3b7/packages/gatsby-plugin-image/src/resolver-utils.ts#L157-L170

As you can see, it should not return `JSON` but `GatsbyImageData!` as a Scalar type:

```ts
type: hasFeature(`graphql-typegen`) ? `GatsbyImageData!` : `JSON!`,
```

I'll grab your codesandbox and see if I can figure out what it is.

**Comment by LekoArts** [comment]
Found the problem & fix: https://github.com/gatsbyjs/gatsby/pull/36337

**Comment by Mike-Logit** [comment]
> As you can see, it should not return JSON but GatsbyImageData! as a Scalar type

@LekoArts This sounds exactly like what's happening and I'm glad my issue made sense. Thank you for the fix and for the great explanation! I temporarily had to tell TypeScript it was of type `GatsbyImageData` using `const data = image as unknown as GatsbyImageData` so I can remove this now and rely on `graphql-typegen` once again.

Feel free to close this issue either now or when the PR gets merged 👍
