### ISSUE TITLE
Google Translate is "lost" when clicking links

### ISSUE THREAD

**Issue by tordans** [gatsbyjs/gatsby#36262]
### Description

My goal is to be able to translate a Gatsby page _and_ navigate on the translated page (and staying on the translated page while navigating).

### Reproduction Link

https://bikelane-safetycheck.net/

### Steps to Reproduce

1. Open https://bikelane-safetycheck.net/
2. Follow [the translation link](https://radwege--check-de.translate.goog/?_x_tr_sl=de&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp) in the modal
3. Hover over a link in the footer => the browser bar shows the google translate domain (Screenshot)

Expected behavior: Clicking this link opens the google translate URL for that page

What happens: Users get directed to the original page and need to re-translate from there

## Brainstorming

I assume that Gatsby captures the links and does not actually use the href that was shown in the browser bar, but some other URL that.  If true, ideally there would be a way to change or correct this behavior to stay on the given domain. 
Alternatively, maybe disabling this part of Gatsby would help, which is what was proposed in https://github.com/gatsbyjs/gatsby/issues/6300#issuecomment-538234820 I think. However, this disable has to happen based on the domain/location.host …

![Bildschirmfoto 2022-07-29 um 13 12 12](https://user-images.githubusercontent.com/111561/181748663-33575177-8168-4f5b-8f81-4e0d64f44af6.png)

---

In general, this is something else than https://github.com/gatsbyjs/gatsby/issues/6300, which was about a flash of translated content. This is about not being able to navigate on a translated page.

### Environment

```shell
Binaries:
    Node: 16.14.2 - ~/.asdf/installs/nodejs/16.14.2/bin/node
    npm: 8.5.0 - ~/.asdf/plugins/nodejs/shims/npm
  npmPackages:
    gatsby: 4.19.2 => 4.19.2
    gatsby-plugin-image: 2.19.0 => 2.19.0
    gatsby-plugin-manifest: 4.19.0 => 4.19.0
    gatsby-plugin-matomo: 0.13.0 => 0.13.0
    gatsby-plugin-postcss: 5.19.0 => 5.19.0
    gatsby-plugin-react-helmet: 5.19.0 => 5.19.0
    gatsby-plugin-react-svg: 3.1.0 => 3.1.0
    gatsby-plugin-sharp: 4.19.0 => 4.19.0
    gatsby-plugin-sitemap: 5.19.0 => 5.19.0
    gatsby-source-filesystem: 4.19.0 => 4.19.0
    gatsby-transformer-csv: 4.19.0 => 4.19.0
```

**Comment by tyhopp** [comment]
Hi @tordans! I think I understand your issue, but it would be much easier to progress on this if you can provide a [minimal reproduction][reproduction] we can refer to. Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment]
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!
