### ISSUE TITLE
Large HTML (css) & massive JS bundles (duplication)

### ISSUE THREAD

**Issue by vanbroup** [gatsbyjs/gatsby#3626]
We are having some issues with our `gatsby build`:

1> The project is using `semantic-ui-react` and importing `semantic.less`. As result, the generated `index.html` files have become 500KB-700KB (compressed). Using a custom `html.js` and removing the embedded styles and importing the `style.css` directly does reduce the size to about 25k (still quite big) but is actually slowing down the time to first paint. First I think it would be great if `gatsby` can contain some logic to prevent massive index files and split styles to a dedicated file when appropriate and second the generated `style.css` doesn't contain a hash in the filename which is causing problems when styles are updated.

It would be great if the build system can optimize files according to the [Chrome Lighthouse](https://github.com/GoogleChrome/lighthouse) best practices.

2> The `index.html` also imports two massive javascript files (+/- 800KB) which contain mostly the same libs according to `source-map-explorer`. 

Uncompressed file sizes as generated by `gatsby build`:
```
4.2M Jan 19 20:02 component---src-templates-content-jsx-c5bde1f8ced7c6459859.js
3.9M Jan 19 20:02 component---src-layouts-index-jsx-cbcc0310b9f2262b3576.js
527K Jan 19 20:02 404.html
527K Jan 19 20:02 index.html
509K Jan 19 20:01 styles.css
286K Jan 19 20:02 component---src-pages-index-jsx-cb95605cad1e54c799e3.js
234K Jan 19 20:02 commons-1429a87de0069fc4e7f4.js
 69K Jan 19 20:02 app-b91853e04bdc81f3afa7.js
...
```

`source-map-explorer` view of `component---src-templates-content-jsx` and `component---src-layouts-index-jsx` containing mostly the same libraries:
<img width="1434" alt="screen shot 2018-01-20 at 12 00 00" src="https://user-images.githubusercontent.com/722070/35183246-01279022-fde3-11e7-84d5-01e879856cb7.png">

**Comment by vanbroup** [comment]
Adding `gatsby-plugin-lodash` to the `gatsby-config.js` reduced the bundle with about 800KB for both bundles, the duplication is of course still there and the files are still massive.

**Comment by KyleAMathews** [comment]
The default is to inline css in the head as that's the fastest way of loading pages. It sounds like you're loading lots of CSS that's not being used (you can check that here https://developers.google.com/web/updates/2017/04/devtools-release-notes#coverage). I suggest adding this plugin which automatically removes unused css. https://github.com/rongierlach/gatsby-plugin-purify-css

You have the option, as you did, to not inline CSS.

There is a commons.js generated — Gatsby's config is setup to only move modules into the commons bundle if it's used in more than 3 routes. It seems like you only have two page components? We could make that # smarter e.g. drop to 2 for smaller sites and move to 3 or more for larger sites.

You might want to do an audit of the modules you're including e.g. GraphQL probably shouldn't be there? Also crypto-js is generally not needed client side and is often accidentally included when importing node code. Also rambda & lodash do much the same thing so it'd be best to only use one or the other. Esprima is also an odd library to be including.

We've done extensive experimentation to make Gatsby as fast as possible out-of-the-box but no optimizations survive first contact with real-life projects so you need to do as you're doing, use tools like source-map-explorer to see what code you've added to make your bundles bloat. We might include heuristics in the future to suggest e.g. not using lodash & rambda together, etc. but it's hard to make smart suggestions like that.
