### ISSUE TITLE
Out of memory with lots of files (1000+) under AWS Lambda

### ISSUE THREAD

**Issue by kennu** [gatsbyjs/gatsby#363]
I've started to get SIGKILLs when running Gatsby builds under AWS Lambda, after my project went over 1000 .md files. According to the logs all available memory (1536 MB) is being used, so I'm pretty sure this is caused by running out of memory.

Any ideas how to scale Gatsby without requiring more and more memory when the number of static files grows?

**Comment by KyleAMathews** [comment]
Hey @kennu this would be a great question for StackOverflow — you want to move the question over there and tag it with `gatsby` and post the link back here?

**Comment by kennu** [comment]
I take it this is then a configuration issue, not a development issue?

**Comment by KyleAMathews** [comment]
Yeah. I'd like to keep issues for bugs/new development and start moving
more "how do I do x" type questions to stackoverflow where they can live
forever. If an issue is closed it's hard to find which makes them a bit
useless for new people.

**Comment by kennu** [comment]
Okay thanks. I added a question here: http://stackoverflow.com/questions/38536371/how-to-scale-gatsby-to-1000s-of-static-files-without-running-out-of-memory
