### ISSUE TITLE
Can't disable webpack hmr

### ISSUE THREAD

**Issue by kosirm** [gatsbyjs/gatsby#3632]
## Description
Can't disable webpack hmr

### Environment
Gatsby version:1.1.28
Node.js version:6.11.2
Operating System:Ubuntu

### Problem
 According to [documentation](https://www.gatsbyjs.org/docs/add-custom-webpack-config/) I added this to gatsby-node.js:  
```
exports.modifyWebpackConfig = ({ config, stage }) => {
  if (stage == "develop"){
      config.devServer = {
        hot: false, 
        inline: false,
    }
  };
  return config;
};  
```
I still get a bunch of webpack hmr related errors in a browser (chrome):
I run gatsby with this command on cloud 9: **gatsby develop -H $IP -p $PORT**
```
0.0.0.0:8080/__webpack_hmr Failed to load resource: net::ERR_ADDRESS_INVALID
0.0.0.0:8080/__webpack_hmr:1 GET http://0.0.0.0:8080/__webpack_hmr net::ERR_ADDRESS_INVALID
0.0.0.0:8080/__webpack_hmr:1 GET http://0.0.0.0:8080/__webpack_hmr net::ERR_ADDRESS_INVALID
0.0.0.0:8080/__webpack_hmr:1 GET http://0.0.0.0:8080/__webpack_hmr net::ERR_ADDRESS_INVALID
```
Thanks for any hint!

(otherwise everything works perfect and build has no errors)

**Comment by calcsam** [comment]
This is an issue with Cloud 9 -- google "hmr cloud 9" and see if the workarounds there help.

**Comment by kosirm** [comment]
Ok, thanks, so it will stay for now. Anyway, I'm planning to transfer everything to new Cloud9 AWS infrastructure, where all these problems with ports, reverse proxies etc will be gone, hopefully.
I just wanted to temporarily disable hmr so I don't look at these errors all the time 😄 
All the best.
