### ISSUE TITLE
gatsby-remark-responsive-iframe unexpected behavior

### ISSUE THREAD

**Issue by Isaac-Tait** [gatsbyjs/gatsby#36324]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Following the [docs](https://www.gatsbyjs.com/plugins/gatsby-remark-responsive-iframe/) I created a blog post with a video embedded (iframe) with the following code:

`<iframe src="https://player.vimeo.com/video/25372131?h=e9070eaf08" width="500" height="300"></iframe>` and I get this:
![error two](https://user-images.githubusercontent.com/14932877/182945367-15c2cfdd-2dbc-4511-8011-4178232a549c.png)

I have set both the height and width attributes but they are not taking effect. I have also tried wrapping `<iframe>` in a `<div>` and setting the div height, width, etc... w/ TailwindCSS to no avail.

Here is a snippet from my `gatsby-config.js` file:

```
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 630,
            },
          },
          {
            resolve: `gatsby-remark-responsive-iframe`,
            options: {
              wrapperStyle: `margin-bottom: 1.0725rem`,
            },
          },
          `gatsby-remark-prismjs`,
          `gatsby-remark-copy-linked-files`,
          `gatsby-remark-smartypants`,
        ],
      },
    },
```

### Reproduction Link

https://github.com/Isaac-Tait/Fallfish_Tenkara

### Steps to Reproduce

1. run `gatsby develop` 
2. navigate to http://localhost:8000/grayling and you can see the embedded video is not responding to height/width attribute changes 
3.
...

### Expected Result

When I set the height and width I would expect the change to take effect on the embedded video

### Actual Result

The video embed is overflowing the boundaries set by the height/width attributes. It also overflows the container if I attempt to constrain with a `<div>` tag...

Note: my `gatsby-remark-responsive-iframe` dependency is up to date...

### Environment

```shell
System:
    OS: macOS 12.5
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.3.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 100.0.1
    Safari: 15.6
  npmPackages:
    gatsby: ^4.16.0 => 4.16.0 
    gatsby-awesome-pagination: ^0.3.8 => 0.3.8 
    gatsby-plugin-feed: ^4.16.0 => 4.16.0 
    gatsby-plugin-gatsby-cloud: ^4.16.0 => 4.16.0 
    gatsby-plugin-google-analytics: ^4.16.0 => 4.16.0 
    gatsby-plugin-image: ^2.16.1 => 2.16.1 
    gatsby-plugin-manifest: ^4.16.0 => 4.16.0 
    gatsby-plugin-offline: ^5.16.0 => 5.16.0 
    gatsby-plugin-postcss: ^5.16.0 => 5.16.0 
    gatsby-plugin-react-helmet: ^5.16.0 => 5.16.0 
    gatsby-plugin-sharp: ^4.16.1 => 4.16.1 
    gatsby-remark-copy-linked-files: ^5.16.0 => 5.16.0 
    gatsby-remark-images: ^6.16.0 => 6.16.0 
    gatsby-remark-prismjs: ^6.16.0 => 6.16.0 
    gatsby-remark-responsive-iframe: ^5.20.0 => 5.20.0 
    gatsby-remark-smartypants: ^5.16.0 => 5.16.0 
    gatsby-source-filesystem: ^4.16.0 => 4.16.0 
    gatsby-transformer-remark: ^5.16.0 => 5.16.0 
    gatsby-transformer-sharp: ^4.16.0 => 4.16.0 
  npmGlobalPackages:
    gatsby-cli: 2.12.111
```

**Comment by LekoArts** [comment]
The plugin is working as expected, the `width`/`height` are only relevant for generating the correct aspect ratio.

> in a responsive elastic container with a fixed aspect ratio. This ensures that the iframe or object will scale proportionally and to the full width of its container

You can see this in the source code (https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-responsive-iframe/src/index.js) and the test snapshots (https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-responsive-iframe/src/__tests__/__snapshots__/index.js.snap).

If you want to limit the size you'll need to wrap it with a parent and style that one.
