### ISSUE TITLE
Add components to content using MDX

### ISSUE THREAD

**Issue by sahilsuman933** [gatsbyjs/gatsby#36332]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

In Part 3: Importing JSX components and MDX documents, it should mention that `props.pageContext.frontmatter` is only available for folders inside `src/pages` . To use frontmatter in another folder, it should use `_frontmatter`. 

I can make a PR to solve this issue :) 

### Steps to Resolve this Issue

1. Add a Note regarding the usage of `props.pageContext.frontmatter`.
...

**Comment by LekoArts** [comment]
Hey, thanks for the issue! However, `frontmatter` is passed to every page so the information on the current page is correct.
