### ISSUE TITLE
gatsby-plugin-offline not pre-caching pages

### ISSUE THREAD

**Issue by TannerJuby1** [gatsbyjs/gatsby#36340]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

The gatsby-plugin-offline package does not work as it suggests. Either it doesn't actually pre-cache pages or the service worker just doesn't do what it's suppose to, either way, it does not produce a viable PWA. 

I've configured the plugin like so:

```
resolve: 'gatsby-plugin-offline',
options: {
    precachePages: ['/*', '/news/*', '/fundraisers/*', '/locations/*'],
},
```

Whether I save the website from my phone then turn off internet, or use the Chrome Web Inspector to run the Service Worker as "offline", I just receive a "No Internet" error when trying to go to different pages instead of it loading the pre-cached page. 

**UPDATE**

I discovered that the plugin's Service Worker output is causing a `The Installing service worker became redundant` error. I changed my configurations to:

```
resolve: 'gatsby-plugin-offline',
options: {
    precachePages: ['/*'],
},
```

And I am still getting the redundant error. 

The gatsby-plugin-offline module does not do what it's suppose to. Sometimes the page loads without internet, but most of the time I just get an internet connection error. Overall, it's super wonky and does not produce a viable PWA.

### Reproduction Link

https://github.com/TannerJuby1

### Steps to Reproduce

1. Install gatsby-plugin-offline
2. Attempt to precache pages
3. Receive No Internet error when attempting to load pre-cache page

### Expected Result

I would expect the plugin to actually pre-cache the page and to not throw a "No Internet" error when user opens that page when not connected to internet.

### Actual Result

Service Worker doesn't correctly cache/serve the precached page when you are offline

### Environment

```shell
System:
    OS: macOS 12.5
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.12.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 103.0.1
    Safari: 15.6
  npmPackages:
    gatsby: ^4.13.1 => 4.13.1
    gatsby-plugin-apollo: ^4.0.2 => 4.0.2
    gatsby-plugin-env-variables: ^2.2.0 => 2.2.0
    gatsby-plugin-gatsby-cloud: ^4.1.0 => 4.13.0
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-image: ^2.2.0 => 2.13.0
    gatsby-plugin-manifest: ^4.1.0 => 4.13.0
    gatsby-plugin-offline: ^5.1.0 => 5.13.0
    gatsby-plugin-page-creator: ^4.6.0 => 4.13.0
    gatsby-plugin-prismic-previews: ^5.2.1 => 5.2.6
    gatsby-plugin-react-helmet: ^5.1.0 => 5.13.0
    gatsby-plugin-react-svg: ^3.1.0 => 3.1.0
    gatsby-plugin-root-import: ^2.0.8 => 2.0.8
    gatsby-plugin-sass: ^5.1.0 => 5.13.0
    gatsby-plugin-sharp: ^4.1.0 => 4.13.0
    gatsby-plugin-typescript: ^4.14.0 => 4.14.0
    gatsby-source-filesystem: ^4.1.0 => 4.13.0
    gatsby-source-prismic: ^5.2.2 => 5.2.6
    gatsby-transformer-sharp: ^4.1.0 => 4.13.0
```

**Comment by tyhopp** [comment]
Judging from your update that the error message is the same as reported in #36346, I'll close this as a duplicate.
