### ISSUE TITLE
[Docs] Add section on deploying to now.sh

### ISSUE THREAD

**Issue by hamlim** [gatsbyjs/gatsby#3635]
## Description

There are several great sections on deploying to different hosting solutions on the Gatsby site [here](https://www.gatsbyjs.org/docs/deploy-gatsby/), however it seems like there isn't a section on deploying to [Now](https://zeit.co/now).

One way that I am using is the following:

1. `yarn add serve`
2. Add a `start` script to package.json with `serve /public`
3. Run `now` in the project directory.

However I am running into a build issue that I only get during deployment (i.e. local builds work just fine)
<details><summary>See Error</summary><p>

```
success Building production JavaScript bundles — 15.214 s
> error UNHANDLED EXCEPTION
>
>   TypeError: errorStr.split is not a function
>
>   - errors.js:44 createErrorFromString
>     [src]/[gatsby-cli]/lib/reporter/errors.js:44:34
>
>   - build-html.js:58
>     [src]/[gatsby]/dist/commands/build-html.js:58:33
>
>   - Compiler.js:194 Compiler.<anonymous>
>     [src]/[webpack]/lib/Compiler.js:194:14
>
>   - Compiler.js:282 Compiler.emitRecords
>     [src]/[webpack]/lib/Compiler.js:282:37
>
>   - Compiler.js:187 Compiler.<anonymous>
>     [src]/[webpack]/lib/Compiler.js:187:11
>
>   - Compiler.js:275
>     [src]/[webpack]/lib/Compiler.js:275:11
>
>   - Tapable.js:60 Compiler.applyPluginsAsync
>     [src]/[tapable]/lib/Tapable.js:60:69
>
>   - Compiler.js:272 Compiler.afterEmit
>     [src]/[webpack]/lib/Compiler.js:272:8
>
>   - Compiler.js:267 Compiler.<anonymous>
>     [src]/[webpack]/lib/Compiler.js:267:14
>
>   - async.js:52
>     [src]/[webpack]/[async]/lib/async.js:52:16
>
>   - async.js:246 done
>     [src]/[webpack]/[async]/lib/async.js:246:17
>
>   - async.js:44
>     [src]/[webpack]/[async]/lib/async.js:44:16
>
>   - graceful-fs.js:43
>     [src]/[graceful-fs]/graceful-fs.js:43:10
```

</p></details>

**Comment by KyleAMathews** [comment]
Hey — we'd love a PR for a section on deploying to Now!

On the error — sorry you're running into that — could you double-check you're on the latest version of Gatsby? I think this was an error we fixed a month or two ago (though it might be new too in which case we should investigate).

**Comment by KyleAMathews** [comment]
Cool, whenever you have time!
