### ISSUE TITLE
Parcel error handling masks genuine issues

### ISSUE THREAD

**Issue by dan-kirkham** [gatsbyjs/gatsby#36371]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

This part of the code tries to compile the gatsby-config and seemingly sense check it.

https://github.com/gatsbyjs/gatsby/blob/0ee492c8bf11917dc08b16acebe92bb752bdc3b7/packages/gatsby/src/utils/parcel/compile-gatsby-files.ts#L114-L119

There is a problem that it disregards any errors it receives. This caused a lot of confusion where out `gatsby-config.ts` file was doing something like:

```ts
// caused an error (missing quote)
const pathPrefix = JSON.parse('{"foo:"bar"}');

const config: GatsbyConfig = {
  jsxRuntime: "automatic",
  pathPrefix
};

return config;
```

Instead of logging sensible messages, we get the dreaded: `Error: EBUSY: resource busy or locked, unlink 'C:\Users\...\.cache\.parcel-cache\data.mdb'`.

### Reproduction Link

https://github.com/gatsbyjs/gatsby/

### Steps to Reproduce

1. Add the following to gatsby-config.ts:

```ts
// caused an error (missing quote)
const pathPrefix = JSON.parse('{"foo:"bar"}');

const config: GatsbyConfig = {
  jsxRuntime: "automatic",
  pathPrefix
};

return config;
```

2. Run `gatsby dev`
...

### Expected Result

A clear error message that highlights the problem better (that the gatsby-config.ts threw an error)

### Actual Result

`Error: EBUSY: resource busy or locked` error message, which is **very** misleading

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 9 5950X 16-Core Processor            
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.47)
  npmPackages:
    gatsby: ^4.19.2 => 4.19.2 
    gatsby-cypress: 2.19.0 => 2.19.0 
    gatsby-plugin-google-tagmanager: ^4.19.0 => 4.19.0 
    gatsby-plugin-image: ^2.19.0 => 2.19.0 
    gatsby-plugin-newrelic: ^2.2.2 => 2.2.2 
    gatsby-plugin-sharp: ^4.19.0 => 4.19.0 
    gatsby-plugin-sitemap: ^5.19.0 => 5.19.0 
    gatsby-plugin-styled-components: ^5.19.0 => 5.19.0 
    gatsby-plugin-webpack-bundle-analyser-v2: 1.1.27 => 1.1.27 
    gatsby-source-filesystem: ^4.19.0 => 4.19.0 
    gatsby-transformer-remark: ^5.19.0 => 5.19.0 
    gatsby-transformer-sharp: ^4.19.0 => 4.19.0
```

**Comment by tyhopp** [comment]
Hi @dan-kirkham, sorry experienced this issue. I was not able to reproduce using the latest stable (`gatsby@4.20.0`) and the version mentioned in issue description (`gatsby@4.19.2`).

Repo - https://github.com/tyhopp/gatsby-parcel-error-handling-36371

Can you link minimal reproduction? Thanks!

**Comment by dan-kirkham** [comment]
Literally can repo off yours, I'm on a windows machine (potentially makes a difference?):

![image](https://user-images.githubusercontent.com/89638943/184310093-eb4dea4c-9173-4259-8517-132daf9f52e3.png)

**Comment by pieh** [comment]
> I'm on a windows machine (potentially makes a difference?):

Yes, that was important factor in being able to reproduce. I was able to reproduce and opened PR with proposed fix - https://github.com/gatsbyjs/gatsby/pull/36377
