### ISSUE TITLE
create-gatsby does not accept a valid path

### ISSUE THREAD

**Issue by tmadeira** [gatsbyjs/gatsby#36381]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

`create-gatsby` does not accept a valid path to bootstrap a project. The regexp in [packages/create-gatsby/src/utils/question-helpers.ts:12](https://github.com/gatsbyjs/gatsby/blob/master/packages/create-gatsby/src/utils/question-helpers.ts#L12) blocks slashes, so `create-gatsby -y /tmp/foo` fails with: _The destination "/tmp/foo" is not a valid filename. Please try again, avoiding special characters._

### Reproduction Link

https://github.com/gatsbyjs/gatsby/blob/master/packages/create-gatsby/src/utils/question-helpers.ts#L12

### Steps to Reproduce

1. Type `create-gatsby -y /tmp/foo` in a terminal.

### Expected Result

A Gatsby project should be bootstraped in /tmp/foo.

### Actual Result

Failure: _The destination "/tmp/foo" is not a valid filename. Please try again, avoiding special characters._

### Environment

```shell
System:
    OS: Linux 5.18 Arch Linux
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 14.20.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.17.0 - /usr/bin/npm
  Languages:
    Python: 3.10.5 - /usr/bin/python
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue. But this is working as intended, you should `cd` to the directory you want it in and then run `npm init gatsby` to name the directory. We don't intend on changing that in the future for now.

**Comment by tmadeira** [comment]
I'm sorry to insist. Of course I can `cd` to the directory and run `npm init gatsby` on it, but there are several cases where that's annoying, for example in a script.

Also, note the desired behavior is supported by other create-* packages such as `create-react-app` and `create-next-app`:

```
$ yarn create react-app /tmp/foo
  # Project bootstraped in /tmp/foo.
$ yarn create next-app /tmp/bar
  # Project bootstraped in /tmp/bar.
$ yarn create gatsby -y /tmp/baz
  # CLI reports that /tmp/baz is an invalid path, which is false.
```

**Comment by tmadeira** [comment]
Hey @LekoArts,

@TylerBarnes closed my PR (https://github.com/gatsbyjs/gatsby/pull/36382) based on the understanding that `create-gatsby <path_with_slashes>` is intended not to work (while `create-gatsby <path_without_slashes>` work). Do you mind if I ask one more time why?

Of course it's possible for create-gatsby users to work around this issue, but it adds some friction, specially to scripts (e.g. https://github.com/plasmicapp/plasmic/blob/master/packages/create-plasmic-app/src/strategies/gatsby.ts#L29-L37). I really think Gatsby users could benefit from making `create-gatsby /tmp/foo` work (as `create-react-app /tmp/foo` and `create-next-app /tmp/foo` do).

This is really my last attempt. Sorry for insisting. Thanks.
