### ISSUE TITLE
url / issue

### ISSUE THREAD

**Issue by konsumer** [gatsbyjs/gatsby#364]
I have 2 demo sites [my blog](http://blog.jetboystudio.com/) and this [starter demo](http://konsumer.js.org/gatsby-starter-drunkenblog/). Both work great local.

Running with the same code, my blog still needs a trailing `/` on links to work (on gh_pages.) On the starter demo, it adds them.  The only real difference I can tell is that on my blog I put everything directly in `pages/articles/`(`pages/articles/article.md` not `pages/articles/article/index.md`)  and there is a `config.linkPrefix` of `""`, but the starter demo has them all in the root with a `config.linkPrefix` of `"/gatsby-starter-drunkenblog"`.

I think maybe I need to check for a trailing-slash in prefixLink in gatsby-helpers.

**Comment by KyleAMathews** [comment]
So the problem is `page.path` doesn't have a trailing slash at times? https://github.com/konsumer/gatsby-starter-drunkenblog/blob/master/pages/index.js#L38

**Comment by konsumer** [comment]
Ah dood! I just need to edit the front-matter paths! thanks.

**Comment by KyleAMathews** [comment]
Well... this is actually pretty weird. The `page.path` *should* always have a trailing slash. We should investigate why not. This isn't something a site should need to check for.

**Comment by konsumer** [comment]
Yeh, that makes sense. I understand that `articles/article_name/` doesn't exactly map to `articles/article_name.md` as well as `articles/article_name/index.md`, but maybe it should be handled at a higher level than the path-fixer (like in the router) so it will work intuitively, out-of-the-box.

For just fixing the path front-matter on my blog, [here](https://gist.github.com/konsumer/ea6317c2e2d7a2f7604eea3c875a5bb0) is the script I threw together.
