### ISSUE TITLE
[gatsby-core-utils] ESM usage throws `ERR_MODULE_NOT_FOUND` due to internal extension-less import specifiers

### ISSUE THREAD

**Issue by angeloashmore** [gatsbyjs/gatsby#36410]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When using `gatsby-core-utils` in an ESM setting, such as in Vitest, Node throws a `ERR_MODULE_NOT_FOUND` error.

This happens because `gatsby-core-utils` compiles to `.mjs` files (as of PR #36020), but does not use the `.mjs` file extensions in its internal `import` statements.

Example code excerpt from the compiled `gatsby-core-utils/dist/cpu-core-count.mjs` file:

```js
// gatsby-core-utils/dist/cpu-core-count.mjs

import { getPhysicalCpuCount } from "./physical-cpu-count";
```

In order to support ESM, that line should be:

```js
import { getPhysicalCpuCount } from "./physical-cpu-count.mjs";
```

Because `gatsby-core-utils` is compiled using Babel, adding file extensions may be automated using a plugin like this: [babel-plugin-add-import-extension](https://codeberg.org/karl/babel-plugin-add-import-extension)

### Reproduction Link

https://stackblitz.com/edit/node-he4lla

### Steps to Reproduce

1. In the terminal, run the following command:

   ```sh
   node ./index.mjs
   ```

   An `ERR_MODULE_NOT_FOUND` error should be thrown.

### Expected Result

The package is usable like any other valid ESM-compatible module.

### Actual Result

Node is unable to resolve the imported files.

### Environment

```shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Max
    Shell: 5.1.16 - /nix/store/yh4hd5h520nmqnbzhwz7xl43zlh5c4h2-bash-interactive-5.1-p16/bin/bash
  Binaries:
    Node: 16.15.0 - /nix/store/jir78fsqgcrr2kgyifkydy9drchzcbr1-nodejs-16.15.0/bin/node
    npm: 8.5.5 - /nix/store/jir78fsqgcrr2kgyifkydy9drchzcbr1-nodejs-16.15.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Safari: 15.6
  npmGlobalPackages:
    gatsby: 4.20.0
```

**Comment by TylerBarnes** [comment]
Hi @angeloashmore, `gatsby-core-utils` is meant to be used in Gatsby sites and plugins, not without Gatsby. We currently only support it's use in that way.

There are plans to support ESM in Gatsby, and when that's worked on it may happen to solve this issue, but there is no hard date on when that will be worked on or ship.

Thanks for your understanding

**Comment by angeloashmore** [comment]
Hi @TylerBarnes, thanks for the reply. 🙂

I totally understand `gatsby-core-utils` is meant for Gatsby and its plugins, not for general use. In my case, I am using it in a Gatsby plugin, but I unit test the plugin using Vitest. Because the plugin makes use of `gatsby-core-utils`, it is imported in an ESM environment.

In case anyone else comes across this issue in the future, I used [`patch-package`](https://github.com/ds300/patch-package) to remove the `.mjs` entry files as a workaround:

```diff
diff --git a/node_modules/gatsby-core-utils/package.json b/node_modules/gatsby-core-utils/package.json
index d077e3c..d233e81 100644
--- a/node_modules/gatsby-core-utils/package.json
+++ b/node_modules/gatsby-core-utils/package.json
@@ -9,17 +9,17 @@
   "exports": {
     ".": {
       "types": "./dist/index.d.ts",
-      "import": "./dist/index.mjs",
+      "import": "./dist/index.js",
       "require": "./dist/index.js"
     },
     "./*": {
       "types": "./dist/*.d.ts",
-      "import": "./dist/*.mjs",
+      "import": "./dist/*.js",
       "require": "./dist/*.js"
     },
     "./dist/*": {
       "types": "./dist/*.d.ts",
-      "import": "./dist/*.mjs",
+      "import": "./dist/*.js",
       "require": "./dist/*.js"
     }
   },
@@ -35,7 +35,7 @@
   "homepage": "https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-core-utils#readme",
   "license": "MIT",
   "main": "dist/index.js",
-  "module": "dist/index.mjs",
+  "module": "dist/index.js",
   "types": "dist/index.d.ts",
   "repository": {
     "type": "git",
```
