### ISSUE TITLE
Top partially stay hidden on route change in Safari

### ISSUE THREAD

**Issue by lilyntalmers** [gatsbyjs/gatsby#36444]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Initially the web-page loads totally fine. And while staying at, clicking an internal link works fine too. But after scrolling a bit, if a internal link is clicked then top part of the next page stays partially hidden.

[Here is a video of the issue uploaded to YouTube](https://www.youtube.com/shorts/EcW4A0QvFIk)

The video starts at "New Beginnings" page. Then I scroll to the bottom and click "My Second Post!" link. It takes me to the "My Second Post!" page but top part of the page including logo is hidden. So I scroll up and can see the "Gatsby Starter Blog" logo.

This is only happening in Safari of iPad OS. Also tried it on Chrome of iPad OS and it worked totally fine.

Couldn't check in iPhone and Mac as I don't have either.

### Reproduction Link

https://github.com/gatsbyjs/gatsby-starter-blog

### Steps to Reproduce

1. Open the website
2. Scroll a bit
3. Click on a internal link (Gatsby Link)

### Expected Result

Should show from very top on route change, like other browsers.

### Actual Result

Top of the page stays partially hidden by default on route change. Can be seen by scrolling.

### Environment

```shell
Latest Safari on iPad OS (software version: 15.3)
```

**Comment by tyhopp** [comment]
Hi @lilyntalmers, I was able to reproduce this same behavior on non-Gatsby sites, so this is likely an issue with Safari on iOS/iPadOS devices rather than Gatsby.

A good next step I recommend is checking [WebKit's bug tracker](https://bugs.webkit.org) for existing issues describing this behavior or creating a new issue if you can't find one.
