### ISSUE TITLE
Gatsby Head API with react-i18next

### ISSUE THREAD

**Issue by AdrienFery** [gatsbyjs/gatsby#36458]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

Hi,

I would like to know how to use i18n with Head API. I try this but it doesn't work. 

```tsx
export const Head = () =>
{
  const { t } = useTranslation();

  return (<SEO
    title={t('My title')}
  />)
}
```

I don't see any explaination in the documentation about how to use i18n with Head API.

### Steps to Resolve this Issue

1. Add explaination about how to use i18n with Head API : https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/

**Comment by treboryx** [comment]
Hello there.

I've had a quick test with your code, and everything seems to be working correctly.

Is your page title not updating? If so, what's in your SEO component?

**Comment by AdrienFery** [comment]
The page title is always in the default language version for translated pages. Does it work on your side for other language too?

**Comment by LekoArts** [comment]
Hi!

At the moment you can't use libraries that rely on React Context as we currently don't wrap the Head API with these providers, see: https://github.com/gatsbyjs/gatsby/discussions/35841#discussioncomment-3258990

We have to make this change for Gatsby 5 as it'll be a breaking change, but afterwards you'll be able to place your providers there and then the information is available in the Head API.

So for now this is not possible unfortunately.

**Comment by AdrienFery** [comment]
Ok, thanks for your answer @LekoArts! I will use Helmet.

**Comment by gerardolmos** [comment]
Hi!  You can use a conditional inside Head extracting the language of the data props, and based on the result you launch one thing or another.

**Comment by LuisHerrero92** [comment]
Is this posible as of now? I'm running into the same issue with Gatsby 5.12.3

**Comment by aqoraan** [comment]
Same here

**Comment by DDaehn** [comment]
I have the same problem, using Gatsby 5.12.3

**Comment by nNevermore** [comment]
Example:

import * as React from 'react';
import { graphql } from 'gatsby';
import { withLayout } from '../components/layout/DefaultLayout';
import { HeadExtProps } from '../app-types';
import { DataLocalesProps } from '../locales-types';

function IndexPage(): JSX.Element {
  return (
    <div>
...
    </div>
  );
}

export default withLayout(IndexPage);

export function Head({ data, pageContext }: HeadExtProps): JSX.Element {

  const dataLanguage = data.locales.edges.find(
    (e) => e.node.ns === 'translation'
  ).node.data;

  // Access to translation
  const t = JSON.parse(dataLanguage) as DataLocalesProps;

  return <title>{t['Admin Area']}</title>;
}

export const query = graphql`
  query MyPages($language: String!) {
    locales: allLocale(
      filter: {
        language: { eq: $language }
        ns: { in: ["translation", "header", "standard", "common"] }
      }
    ) {
      edges {
        node {
          ns
          data
          language
        }
      }
    }
  }
`;

**Comment by AnderUstarroz** [comment]
@nNevermore solution definitely works, but it's bit hacky, like @LekoArts said, it will be way cleaner wrapping the Head API so we can use the t() function within the Head API normally just like in any other page, but `Gatsby 5.12.12` is already here and seems like that change was never really implemented. @LekoArts will this ever be implemented?

**Comment by imsheth** [comment]
I'm still on 5.11.0 and can confirm @nNevermore 's solution definitely works and that makes me happy with a sign of relif!

**Comment by gabros20** [comment]
This solution worked for me:

```
locales/
├── de/
│   └──  index.json
└── en/
    └──  index.json
```
```js
// locales/de/index.json

{
    "seo": "This is the SEO text translated to English",
}
```
```js
// locales/de/index.json

{
    "seo": "Dies ist der SEO-Text ins Deutsche übersetzt",
}
```

```js
export default function IndexPage() {
    return (
        <Layout>
           ... 
        </Layout>
    )
}

export const query = graphql`
    query ($language: String!) {
        site {
            siteMetadata {
                title
            }
        }
        locales: allLocale(filter: { ns: { in: ["index"] }, language: { eq: $language } }) {
            edges {
                node {
                    ns
                    data
                    language
                }
            }
        }
    }
`

export function Head({ data }) {
    const dataLanguage = data.locales.edges.find(e => e.node.ns === 'index')?.node.data
    const parsedDataLanguage = JSON.parse(dataLanguage)
    const seoValue = parsedDataLanguage.seo
    console.log('seoValue', seoValue)

    const siteMeta = data.site.siteMetadata
    const pageMeta = {
        title: seoValue
    }

    return (
        <>
            <title>{`${siteMeta.title} | ${pageMeta.title}`}</title>
        </>
    )
}
```

Selected language --> English
<img width="732" alt="image" src="https://github.com/gatsbyjs/gatsby/assets/49348865/7a851779-eb24-48b1-9e46-6a1e9c158b69">

Selected language --> German
<img width="723" alt="image" src="https://github.com/gatsbyjs/gatsby/assets/49348865/7a1f1444-6fc3-4e13-9e39-3f9bb1dcb1bf">

**Comment by glassonion1** [comment]
This my solution. Please be in when it is good reference.

index.tsx
``` js
import type { HeadFC, PageProps } from 'gatsby'
import { useTranslation } from 'react-i18next'
import { PageContext } from './PageContext'

const IndexPage: React.FC<PageProps<any, PageContext>> = ({ pageContext }) => {
  // page
})

export default IndexPage

export const Head: HeadFC<any, PageContext> = ({ pageContext, location }) => {
  const { t } = useTranslation('translation', { lng: pageContext.lang })

  return (
    <>
      <html lang={pageContext.lang} />
      <meta name="description" content={`${t('index.title')}`} />
    </>
  )
}
```

PageContext.ts
```js
import { useTranslation } from 'react-i18next'

export interface PageContext {
  lang: string
  originalPath: string
}
interface Props {
  value: PageContext
  children: React.ReactNode
}
const PageContext = React.createContext({
  lang: 'en',
  originalPath: ''
})
export const PageContextProvider = ({ value, children }: Props) => {
  const { i18n } = useTranslation()

  if (i18n.language !== value.lang) {
    i18n.changeLanguage(value.lang)
  }

  return <PageContext.Provider value={value}>{children}</PageContext.Provider>
}
```

gatsby-ssr.tsx
```js
import { I18nextProvider } from 'react-i18next'
import i18n from './src/i18n/configs'
import { PageContext, PageContextProvider } from './src/i18n/PageContext'

export const wrapRootElement: GatsbySSR['wrapRootElement'] = ({ element }) => {
  return <I18nextProvider i18n={i18n}>{element}</I18nextProvider>
}
export const wrapPageElement = ({
  element,
  props
}: WrapPageElementBrowserArgs<any, PageContext>) => {
  return (
    <PageContextProvider value={props.pageContext}>
      {element}
    </PageContextProvider>
  )
}
```

gatsby-node.ts
```js
export const onCreatePage: GatsbyNode['onCreatePage'] = async ({
  page,
  actions
}) => {
  const { createPage, deletePage } = actions
  const originalPath = page.path

  // Delete the original page (since we are gonna create localized versions of it) and add a
  // redirect header
  deletePage(page)

  await Promise.all(
    i18n.languages.map(async (lang: string) => {
      const localizedPath =
        i18n.language === lang ? `${originalPath}` : `/${lang}${originalPath}`

      return createPage<PageContext>({
        ...page,
        path: localizedPath,
        context: {
          lang: lang,
          originalPath: originalPath
        }
      })
    })
  )
}
```
