### ISSUE TITLE
Be less aggressive at deleting sourced data

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#36460]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Gatsby syncs data from local and remote sources into LMDB. We then run queries against our local DB. This syncing takes time and is a frequent cause of slow builds or slow dev server startups as some sources can be quite slow to sync from e.g. WordPress where 10m+ sourcing times aren't uncommon.

This wouldn't be a big deal except for the rare full sync when setting up a new site. Except unfortunately Gatsby's pretty aggressive about deleting the local db of synced data.

Examples of user actions which unexpectedly trigger the local db being deleted:
- adding or upgrading any npm package
- editing gatsby-config.js in any way
- editing gatsby-node.js in any way including common tweaks like editing createPages code

Previous attempts at fixing this:
- https://github.com/gatsbyjs/gatsby/pull/8379
- https://github.com/gatsbyjs/gatsby/pull/32318

### Reproduction Link

https://www.gatsbyjs.com/starters/gatsbyjs/gatsby-starter-wordpress-blog

### Steps to Reproduce

1. setup a site with a source plugin that supports delta fetches like gatsby-source-wordpress and run `gatsby develop`
2. restart `gatsby develop` and observe the sourcing time is much faster as we only sync updated content this time
3. make a trivial edit to gatsby-config.js and restart the dev server
4. observe that the local db is deleted and that gatsby-source-wordpress must refetch all data

### Expected Result

gatsby-source-wordpress only refetches all data if I a) upgrade the plugin or b) edit its config.

### Actual Result

Many changes I make to a site trigger refetching all data.

### Environment

```shell
n/a
```

### Config Flags

n/a

**Comment by ZeldOcarina** [comment]
I love you are still working on features that are not only Gatsby Cloud. We are planning on working a lot with Gatsby at our company and we thank you for not abandoning the software.

**Comment by KyleAMathews** [comment]
@ZeldOcarina — I would kindly direct your attention to [the 100 PRs we merge / month](https://github.com/gatsbyjs/gatsby/pulse/monthly), and the [7 RFCs)(https://github.com/gatsbyjs/gatsby/discussions/categories/rfc) and [16 releases](https://www.gatsbyjs.com/docs/reference/release-notes/) we've put out this year.

**Comment by ZeldOcarina** [comment]
@KyleAMathews you and your team are absolutely amazing!! 🥰
Let me know if there's anything I can contribute on in the open source portion. Let's make Gatsby more and more the best platform in the planet! 🌍

**Comment by KyleAMathews** [comment]
Fixing bugs is always appreciated and for new features, most of the energy will be directed at the active RFCs so testing canaries and helping flesh out the new features is very helpful to ensure robust, fast releases.
