### ISSUE TITLE
npm ci fails

### ISSUE THREAD

**Issue by marcinkowalmedius** [gatsbyjs/gatsby#36493]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

npm ci command fails on clean TypeScript gatsby project

### Reproduction Link

https://github.com/marcinkowalmedius/gatsby-clean

### Steps to Reproduce

1.run npm ci command

or

1. remove package-lock.json
2. run npm install
3. run npm ci

### Expected Result

node_modules installed without problems

### Actual Result

Installation of node modules fails.

Clean installation:
PS C:\dev\gatsby-clean\gatsby-clean> npm ci
npm ERR! code EUSAGE
npm ERR!
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR!
npm ERR! Invalid: lock file's type-fest@0.20.2 does not satisfy type-fest@0.13.1
npm ERR! Invalid: lock file's acorn@7.4.1 does not satisfy acorn@8.8.0
npm ERR! Missing: type-fest@0.20.2 from lock file
npm ERR! Missing: babel-eslint@10.1.0 from lock file
npm ERR! Missing: eslint-visitor-keys@1.3.0 from lock file
npm ERR! Missing: acorn@7.4.1 from lock file
npm ERR! Missing: type-fest@0.20.2 from lock file
npm ERR! Missing: type-fest@0.20.2 from lock file
npm ERR! Missing: type-fest@0.20.2 from lock file
npm ERR!
npm ERR! Clean install a project
npm ERR!
npm ERR! Usage:
npm ERR! npm ci
npm ERR!
npm ERR! Options:
npm ERR! [-S|--save|--no-save|--save-prod|--save-dev|--save-optional|--save-peer|--save-bundle]
npm ERR! [-E|--save-exact] [-g|--global] [--global-style] [--legacy-bundling]
npm ERR! [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
npm ERR! [--strict-peer-deps] [--no-package-lock] [--foreground-scripts]
npm ERR! [--ignore-scripts] [--no-audit] [--no-bin-links] [--no-fund] [--dry-run]
npm ERR! [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
npm ERR! [-ws|--workspaces] [--include-workspace-root] [--install-links]
npm ERR!
npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
npm ERR!
npm ERR! Run "npm help ci" for more info

After removing package-lock.json and generating it via npm install:
PS C:\dev\gatsby-clean\gatsby-clean> npm ci
npm ERR! code EUSAGE
npm ERR!
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR!
npm ERR! Invalid: lock file's type-fest@0.20.2 does not satisfy type-fest@0.13.1
npm ERR! Missing: type-fest@0.20.2 from lock file
npm ERR! Missing: type-fest@0.20.2 from lock file
npm ERR! Missing: type-fest@0.20.2 from lock file
npm ERR! Missing: type-fest@0.20.2 from lock file
npm ERR!
npm ERR! Clean install a project
npm ERR!
npm ERR! npm ci
npm ERR! Options:
npm ERR! [-S|--save|--no-save|--save-prod|--save-dev|--save-optional|--save-peer|--save-bundle]
npm ERR! [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
npm ERR! [--strict-peer-deps] [--no-package-lock] [--foreground-scripts]
npm ERR! [--ignore-scripts] [--no-audit] [--no-bin-links] [--no-fund] [--dry-run]
npm ERR! [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
npm ERR! [-ws|--workspaces] [--include-workspace-root] [--install-links]
npm ERR!
npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
npm ERR!
npm ERR! Run "npm help ci" for more info

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.18.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.70)
  npmPackages:
    gatsby: ^4.21.1 => 4.21.1
  npmGlobalPackages:
    gatsby-cli: 4.21.0
```

**Comment by pieh** [comment]
I can't reproduce this, but even if I could this sounds more like `npm` issue than `gatsby` issue - it's `npm` that generate lock files and if generating lockfile, and then installing again with `npm ci` cause failure that means that `npm` can't decide what that should look like and this is not something we can fix.

One thing I would try is using `--legacy-peer-deps` toggle on `npm` commands / similarly named config option ( https://docs.npmjs.com/cli/v7/using-npm/config#legacy-peer-deps ) and see if that helps
