### ISSUE TITLE
Code Contributions not mentioning verdaccio requirement

### ISSUE THREAD

**Issue by treboryx** [gatsbyjs/gatsby#36497]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

During my attempt to follow the guide I came across an issue with `gatsby-dev` trying to publish to a local private repository, and of course, failing.

After some digging, I figured out that I needed verdaccio in my system along with a local user account created.

I can only assume this is a documentation issue, which I would be happy to assist with, but it's probably best to get a confirmation

### Steps to Resolve this Issue

Include setup instructions for verdaccio if it is indeed a documentation issue

**Comment by pieh** [comment]
https://github.com/gatsbyjs/gatsby/pull/36498 was opened with the fix
