### ISSUE TITLE
Gatsby Fast Builds - using gatsby-source-drupal fails due to cached node missing field

### ISSUE THREAD

**Issue by g-pex-aerian** [gatsbyjs/gatsby#36505]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

We are having an issue with builds due to an apparent bug in gatsby-source-drupal when using Gatsby fast builds.

The builds fail almost instantly, with the following error: 
`TypeError: undefined is not iterable (cannot read property`

We’ve managed to trace the error into `node_modules/gatsby/dist/redux/actions/public.js` : line 802 which is the following:

`deleteActions = findChildren(oldNode.children).map(getNode).map(createDeleteAction);`

The issue is that on the cached node, children is undefined - on the new node, it’s an empty array. The error obviously being that you cannot iterate on an undefined variable. 

Is it possible that when cache is being written, empty arrays are removed for the purpose of saving space without making the necessary changes to accommodate possibly undefined variables? 

We've had a look at how we can fix this on our side however it doesn't seem to be possible as it's the cached node which is corrupted which we're not able to access before the bug occurs.

### Reproduction Link

N/A

### Steps to Reproduce

1. gatsby project using gatsby-source-drupal
2. clean build
3. save a node in drupal
4. run gatsby build

### Expected Result

Gatsby Fast Builds work successfully, updating only the nodes which have changed are re-published

### Actual Result

Gatsby Fast Builds cache is corrupted and removing `children` from the node - a field which is then required to complete the fast build.

### Environment

```shell
System:
    OS: macOS 12.3
    CPU: (8) x64 Apple M1 Pro
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Safari: 15.4
  npmPackages:
    gatsby: ^4.21.1 => 4.21.1 
    gatsby-background-image: ^1.6.0 => 1.6.0 
    gatsby-image: ^3.11.0 => 3.11.0 
    gatsby-link: ^4.21.0 => 4.21.0 
    gatsby-plugin-breadcrumb: 12.3.1 => 12.3.1 
    gatsby-plugin-feed: ^4.21.0 => 4.21.0 
    gatsby-plugin-gatsby-cloud: ^4.21.0 => 4.21.0 
    gatsby-plugin-google-analytics: ^4.21.0 => 4.21.0 
    gatsby-plugin-google-tagmanager: ^4.21.0 => 4.21.0 
    gatsby-plugin-image: ^2.21.0 => 2.21.0 
    gatsby-plugin-manifest: ^4.21.0 => 4.21.0 
    gatsby-plugin-netlify-cache: ^2.0.0 => 2.0.0 
    gatsby-plugin-offline: ^5.21.0 => 5.21.0 
    gatsby-plugin-postcss: ^5.21.0 => 5.21.0 
    gatsby-plugin-react-helmet: ^5.21.0 => 5.21.0 
    gatsby-plugin-robots-txt: ^1.7.1 => 1.7.1 
    gatsby-plugin-sass: ^5.21.0 => 5.21.0 
    gatsby-plugin-sharp: ^4.21.0 => 4.21.0 
    gatsby-plugin-sitemap: ^5.21.0 => 5.21.0 
    gatsby-plugin-svgr: ^3.0.0-beta.0 => 3.0.0-beta.0 
    gatsby-plugin-typescript: ^4.21.0 => 4.21.0 
    gatsby-source-drupal: ^5.22.1 => 5.22.1 
    gatsby-source-filesystem: ^4.21.1 => 4.21.1 
    gatsby-transformer-sharp: ^4.21.0 => 4.21.0 
  npmGlobalPackages:
    gatsby-cli: 4.20.0
```

**Comment by pieh** [comment]
> Is it possible that when cache is being written, empty arrays are removed for the purpose of saving space without making the necessary changes to accommodate possibly undefined variables?

We do store data in LMDB and there is distinction between `null` or empty arrays there. Otherwise we would see this error happenning all the time (there will always be "leaf" nodes that don't have children anymore). So this is likely not the what cause this problem.

> Steps to Reproduce
> gatsby project using gatsby-source-drupal
> clean build
> save a node in drupal
> run gatsby build

This could indicate that at least some kind of changes that are made on Drupal in-between builds are not correctly handled.

I was also checking some related code and found that we do have some weird condition (seems legacy) that decides wether to add empty array as children - for some reason there is check for `array` field - do you by any chance have field named like this? (this could explain why something didn't have empy children array at least)

https://github.com/gatsbyjs/gatsby/blob/232d3b6de2281caa579a619888bcb6771733f548/packages/gatsby/src/redux/actions/public.js#L699-L702

**Comment by g-pex-aerian** [comment]
Thanks for your reply @pieh 

I've managed to dig into it a little further and it looks like it might be related to one of our custom (oembed transformer) plugins.

I don't think it's doing anything out of the ordinary though? 

```javascript
/* eslint-disable import/no-extraneous-dependencies */
/* eslint-disable @typescript-eslint/no-var-requires */
/* eslint-disable import/no-commonjs */
const {
    fetchOembed,
    getProviderEndpointForLinkUrl,
    tranformsLinkNodeToOembedNode
} = require("./utils");

const oembedProviders = require("oembed-providers/providers.json");

const processNode = async (node, providers) => {
    try {
        const endpoint = getProviderEndpointForLinkUrl(
            node.field_media_oembed_video,
            providers
        );

        if ("url" in endpoint) {
            // Currently we are only using OEmbed for Youtube and Vimeo
            // The endpoint url returned for vimeo requires the format (json) to be added in place of "{format}"
            const url = endpoint.url.replace("{format}", "json");

            const oembedResponse = await fetchOembed({
                ...endpoint,
                url
            });

            return tranformsLinkNodeToOembedNode(node, oembedResponse);
        } else {
            return new Error("no endpoint url!");
        }
    } catch (error) {
        return { ...error, url: node.url };
    }
};
exports.onCreateNode = async ({ node, actions }) => {
    if (node.internal.type !== "media__remote_video") {
        // TODO: add all the other content types
        return;
    }

    try {
        const embedCode = await processNode(node, oembedProviders);

        actions.createNodeField({
            node,
            name: "embedCode",
            value: embedCode
        });
    } catch (err) {
        throw err;
    }
};
```

**Comment by pieh** [comment]
That code doesn't seem to do anything wrong - but maybe there's more to unpack in `tranformsLinkNodeToOembedNode`?

**Comment by g-pex-aerian** [comment]
Hi @pieh - sorry for the late reply and thanks for your suggestion. It pointed me in the right direction to what was a real gotcha in the end. 

Thanks again for the support :)
