### ISSUE TITLE
Where did the Gatsby Head API docs go?

### ISSUE THREAD

**Issue by pak11273** [gatsbyjs/gatsby#36550]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

I went to this page: https://www.gatsbyjs.com/docs/reference/

Then I clicked the link to **Gatsby Head API** : https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/

Then it redirects me to this:

![image](https://user-images.githubusercontent.com/2309184/188635185-87bdcfb0-283a-45b4-8ffa-10f68dbaa10e.png)

### Steps to Resolve this Issue

1. Fix broken link or remove it

**Comment by karunsiri** [comment]
@pak11273 For the time being until the link is fixed, you may go to the v4 doc (prefix the url with `v4`).
https://v4.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/, for the Gatsby HEAD API.
