### ISSUE TITLE
[gatsby-plugin-mdx 4.1.1] Example of extending the GraphQL "headings" nodes would't work.

### ISSUE THREAD

**Issue by FoundTheWOUT** [gatsbyjs/gatsby#36591]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

The [example](https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/?=mdx#headings) of creating "headings" GraphQL node seem like missing some thing when calling the `compileMDXWithCustomOptions`.
The resolver yield `"TypeError: Cannot read properties of undefined (reading 'getState')"`.
And i found the secend parameters of the `compileMDXWithCustomOptions`, which is a object owning "store" attribute. This object  would be passed down to `enhanceMdxOptions`, which would call the `getState` from the store.
https://github.com/gatsbyjs/gatsby/blob/e174fbba1d0c6d084ca85eda93eb51773850c46f/packages/gatsby-plugin-mdx/src/compile-mdx.ts#L83
https://github.com/gatsbyjs/gatsby/blob/e174fbba1d0c6d084ca85eda93eb51773850c46f/packages/gatsby-plugin-mdx/src/plugin-options.ts#L55
Therefore, at the example, the object is missing the "store" attribute, undefined has no `getState`, and that causing the error.
But i have no idea what is the "store" meaning for, and what to pass in.

### Reproduction Link

https://codesandbox.io/s/damp-sea-e242s4?file=/gatsby-node.js

### Steps to Reproduce

Just follow the gatsby-plugin-mdx doc.

### Expected Result

GraphQL resolve the heading properly.

### Actual Result

GraphlQL yield "TypeError: Cannot read properties of undefined (reading 'getState')"

### Environment

```shell
System: win11
Gatsby:4.22.1
gatsby-plugin-mdx:4.1.1
```

**Comment by LekoArts** [comment]
Thanks! Between writing the README and publishing the new version the `store` arg was added and the example wasn't updated. `store` refers to the internal Redux store that Gatsby uses.

You can check https://github.com/gatsbyjs/gatsby/pull/36593 to see what you'll need to change.
