### ISSUE TITLE
how to use react modules in gastby?

### ISSUE THREAD

**Issue by milad1367** [gatsbyjs/gatsby#3659]
## Description

I want to use the npm react modules in my Gatsby project but because  adding CSS is different in Gatsby these modules not worked correctly.for example : 
https://github.com/negomi/react-burger-menu
https://github.com/KyleAMathews/react-headroom

Please give me a solution that I can use from these modules in my Gatsby project. 
### Environment

Gatsby version:"^1.9.153"
Node.js version:8.9.2
Operating System:mac-os

### File contents (if changed):

`gatsby-config.js`: 
`package.json`: 
`gatsby-node.js`: 
`gatsby-browser.js`: 
`gatsby-ssr.js`: 

### Actual result

What happened.

### Expected behavior

What should happen?

### Steps to reproduce

1\.

2\.

3\.

...

**Comment by calcsam** [comment]
Please push a repo including what you believe the intended behavior should be and what it is.

**Comment by milad1367** [comment]
sorry. I tested that module in react and that is same problems.
so the problem is not Gatsby.
I will create an issue on the related page.
