### ISSUE TITLE
Gatsby Cloud webhooks: Header "x-gatsby-cache: false" does not clear build cache

### ISSUE THREAD

**Issue by jtaina** [gatsbyjs/gatsby#36602]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

According to [this support article](https://support.gatsbyjs.com/hc/en-us/articles/360052324394-Build-and-Preview-Webhooks) (see section "Clearing the cache"), the build cache can be cleared by

> making a POST request to https://webhook.gatsbyjs.com/hooks/builds/trigger/:siteId with the header x-gatsby-cache: false will trigger a build with no cache. If you want to use this for previews, add an additional header: x-runner-type: PREVIEW

However, with or without `x-gatsby-cache: false`, the triggered build in Gatsby Cloud will use the cache. The header `x-runner-type: PREVIEW` does correctly target the preview site, but in this case, the cache is also used.

I verified this by triggering builds via webhooks with the correct headers, e.g,
`curl -X POST https://webhook.gatsbyjs.com/hooks/builds/trigger/{my-site-id} --header "x-gatsby-cache: false" -v --header "x-runner-type: PREVIEW"`, observing that my site data was not updating, and that `GATSBY CLEAN` and related content was not logged in the logs of the triggered builds.
 
My site uses Contentful as data source.

In case this has any relevance, the project's package.json contains the following dependencies:

```
 "dependencies": {
    "@contentful/rich-text-react-renderer": "^15.12.1",
    "@contentful/rich-text-types": "^15.12.1",
    "@vimeo/player": "^2.16.4",
    "aos": "^2.3.4",
    "cookieconsent": "^3.1.1",
    "current-input": "^2.0.0",
    "dotenv": "^16.0.1",
    "gatsby": "^4.14.1",
    "gatsby-plugin-gatsby-cloud": "^4.14.0",
    "gatsby-plugin-glslify": "^1.0.2",
    "gatsby-plugin-google-tagmanager": "^4.14.0",
    "gatsby-plugin-image": "^2.14.1",
    "gatsby-plugin-manifest": "^4.14.0",
    "gatsby-plugin-offline": "^5.14.1",
    "gatsby-plugin-react-helmet": "^5.14.0",
    "gatsby-plugin-robots-txt": "^1.7.1",
    "gatsby-plugin-sharp": "^4.14.1",
    "gatsby-plugin-sitemap": "^5.14.0",
    "gatsby-plugin-styled-components": "^5.14.0",
    "gatsby-source-contentful": "^7.12.0",
    "gatsby-source-filesystem": "^4.14.0",
    "gatsby-transformer-sharp": "^4.14.0",
    "glsl-blend": "^1.0.3",
    "glsl-noise": "^0.0.0",
    "glslify": "^7.1.1",
    "prop-types": "^15.8.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-helmet": "^6.1.0",
    "react-hubspot-form": "^1.3.7",
    "react-share": "^4.4.0",
    "react-spring": "^9.4.5",
    "react-use-gesture": "^5.2.4",
    "smoothscroll-polyfill": "^0.4.4",
    "three": "^0.108.0"
  },
  "devDependencies": {
    "prettier": "^2.6.2"
  },
```

### Reproduction Link

https://codesandbox.io/s/github/gatsbyjs/gatsby-starter-minimal

### Steps to Reproduce

(Repro link above isn't an actual repro link)

1. In your Gatsby Cloud project, trigger a build via a webook:
`curl -X POST https://webhook.gatsbyjs.com/hooks/builds/trigger/<site id> --header "x-gatsby-cache: false"`
2. Inspect the logs and verify that the cache is not cleared.

### Expected Result

The build cache will be cleared and a full rebuild is triggered.

### Actual Result

A build is triggered but Gatsby Cloud uses/retrieves cached data.

### Environment

```shell
My local system

  System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.10.4 - /c/Python310/python
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.33)
  npmPackages:
    gatsby: ^4.14.1 => 4.14.1
    gatsby-plugin-gatsby-cloud: ^4.14.0 => 4.14.0
    gatsby-plugin-glslify: ^1.0.2 => 1.0.2
    gatsby-plugin-google-tagmanager: ^4.14.0 => 4.14.0
    gatsby-plugin-image: ^2.14.1 => 2.14.1
    gatsby-plugin-manifest: ^4.14.0 => 4.14.0
    gatsby-plugin-offline: ^5.14.1 => 5.14.1
    gatsby-plugin-react-helmet: ^5.14.0 => 5.14.0
    gatsby-plugin-robots-txt: ^1.7.1 => 1.7.1
    gatsby-plugin-sharp: ^4.14.1 => 4.14.1
    gatsby-plugin-sitemap: ^5.14.0 => 5.14.0
    gatsby-plugin-styled-components: ^5.14.0 => 5.14.0
    gatsby-source-contentful: ^7.12.0 => 7.12.0
    gatsby-source-filesystem: ^4.14.0 => 4.14.0
    gatsby-transformer-sharp: ^4.14.0 => 4.14.0
  npmGlobalPackages:
    gatsby-cli: 4.14.0
```

### Config Flags

No flags used

**Comment by LekoArts** [comment]
For Gatsby Cloud related issues please contact our support here: https://www.gatsbyjs.com/support

Thanks!
