### ISSUE TITLE
rule gatsby lost function

### ISSUE THREAD

**Issue by simonjoom** [gatsbyjs/gatsby#36650]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

vue-loader@next for vue3 has got an issue with the last gatsby code from this repo
see problem ans solution provided here:
https://github.com/vuejs/vue-loader/issues/1994

### Reproduction Link

https://github.com/vuejs/vue-loader/issues/1994

### Steps to Reproduce

1.
install vue3 vue-loader@next and last gatsby

2 
test in a vue3 repo the compilation

i m sorry no time to create a reproduction-link but if some admin read that it s important to contact vue-loader to do the patch

### Expected Result

compilation should to succeed

### Actual Result

break compilation due to vue-loader

### Environment

```shell
System Mac
```

**Comment by LekoArts** [comment]
> i m sorry no time to create a reproduction-link

Then we also won't have time to look into this. It also seems that you'll want to open a _proper_ issue at https://github.com/vuejs/vue-loader
