### ISSUE TITLE
Gatsby Cloud: client-side routes failing

### ISSUE THREAD

**Issue by williamzhuang** [gatsbyjs/gatsby#36695]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Deploying a site with client-side routes works locally but fails to render properly when deployed to Gatsby Cloud. 

(Gatsby Cloud Issue 28944)

This seems to happen regardless of if `gatsby-plugin-gatsby-cloud` is declared in the package.json. Builds prior to 9/21 around 4 PM PST were working fine and those builds are still working properly but any build after that fails. It seems like this might be related to a change on the Gatsby Cloud side where the Cloud Build CLI was updated to version 3 from version 2. 

This is the [deployed version](https://gatsbymaster83808.gtsb.io/) of the site with the issue. This issue seems to be related to the browser attempting to fetch the client side routes [...] with a HEAD request rather than a GET request. 
<img width="406" alt="Screen Shot 2022-09-26 at 8 56 50 AM" src="https://user-images.githubusercontent.com/17490376/192324148-a8d1a425-7fe6-4a7b-81a1-06916d706758.png">

### Reproduction Link

https://github.com/gatsbyjs/gatsby/tree/master/examples/client-only-paths

### Steps to Reproduce

1. Fork the Gatsby repository https://github.com/gatsbyjs/gatsby. 
2. Deploy the [client-only paths example](https://github.com/gatsbyjs/gatsby/tree/master/examples/client-only-paths) to Gatsby Cloud.
3. Open the deployed build in the browser.

### Expected Result

Client-side routes should render as shown here.

<img width="982" alt="Screen Shot 2022-09-26 at 8 43 07 AM" src="https://user-images.githubusercontent.com/17490376/192321258-c792ffbc-a42c-435b-ab36-2e4de5ace4b8.png">

### Actual Result

Client-side routes are rendered as blank. 

<img width="1048" alt="Screen Shot 2022-09-26 at 8 44 03 AM" src="https://user-images.githubusercontent.com/17490376/192321421-4895c06b-a1c0-4be4-83a4-fd7a8319a4de.png">

### Environment

```shell
System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /var/folders/db/lz81kcb960v8wgdwcgpbpqqr0000gn/T/yarn--1664207094583-0.9701180507174119/node
    Yarn: 1.21.0 - /var/folders/db/lz81kcb960v8wgdwcgpbpqqr0000gn/T/yarn--1664207094583-0.9701180507174119/yarn
    npm: 8.11.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 104.0.2
    Safari: 15.6.1
  npmPackages:
    gatsby: next => 4.23.1
    gatsby-plugin-netlify: next => 4.0.0-next.0
    gatsby-plugin-typography: next => 4.25.0-next.0
```

**Comment by tyhopp** [comment]
Hi @williamzhuang, we handle Gatsby Cloud related issues in our support workflow (which I see you've started). Will close this since GitHub issues are for the open source project.

Thanks!
