### ISSUE TITLE
Example sites to document CSS systems

### ISSUE THREAD

**Issue by whmountains** [gatsbyjs/gatsby#3670]
https://github.com/gatsbyjs/gatsby/blob/10393e06e2a70db6c3d947604c356680c43b0682/examples/using-gatsby-image/src/pages/index.js#L13

I don't find any mention of it in the [documentation](https://www.gatsbyjs.org/packages/gatsby-image/) or source code.

**Comment by m-allanson** [comment]
@whmountains I only worked this out the other day :) it's enabled by [`gatsby-plugin-glamor`](https://github.com/gatsbyjs/gatsby/tree/10393e06e2a70db6c3d947604c356680c43b0682/packages/gatsby-plugin-glamor), which the `using-gatsby-image` example [is using](https://github.com/gatsbyjs/gatsby/blob/10393e06e2a70db6c3d947604c356680c43b0682/examples/using-gatsby-image/gatsby-config.js).

I wonder if it'd be clearer if non-styling examples only used the `style` and `className` props, or documented which styling plugin they're using?

**Comment by calcsam** [comment]
@m-allanson -- great idea. Probably not worth it to redo them with vanilla React CSS-in-JS, but documenting them would make a lot of sense.

**Comment by KyleAMathews** [comment]
Yeah, a "reading guide" of sorts added to the starter READMEs sounds great.

**Comment by benjaminhoffman** [comment]
cc @shannonbux this ^^ may be related to the recent css doc re org you did the other day.

**Comment by shannonbux** [comment]
Thanks! This has been added to a list of things to do :)

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
