### ISSUE TITLE
Duplicate "OOTB integrations" entries in the feature comparison

### ISSUE THREAD

**Issue by dandv** [gatsbyjs/gatsby#36709]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

This was [already reported](https://github.com/gatsbyjs/gatsby/issues/16233#issuecomment-600156366) in 2020 and hasn't been addressed yet. @LekoArts said [nothing was actionable in that issue](https://github.com/gatsbyjs/gatsby/issues/16233#issuecomment-653531428), hence creating a separate one.

### Steps to Resolve this Issue

![image](https://user-images.githubusercontent.com/33569/192823241-7bc5734e-9445-4765-864d-a55f78ce813e.png)

**Comment by graysonhicks** [comment]
The URL in question is here: https://www.gatsbyjs.com/features/jamstack/gatsby-vs-nextjs

**Comment by LekoArts** [comment]
An internal ticket was created to fix this.
