### ISSUE TITLE
Hello Im unnbale to deploy my site Need help

### ISSUE THREAD

**Issue by EdmoDev** [gatsbyjs/gatsby#36710]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

16:09:03 PM:
Gatsby version Gatsby CLI version: 4.24.0

16:09:03 PM:
  Note: this is the Gatsby version for the site at: /usr/src/app/www

16:09:03 PM:
Gatsby version: 4.24.0

16:09:03 PM:
CLOUD_BUILDS

16:09:04 PM:
Setting gatsby to /usr/src/app/www/node_modules/gatsby

16:09:04 PM:
info Running Cloud Build CLI v3.0.55

16:09:06 PM:
 Tracing initialized

16:09:06 PM:
verbose 2.873907699 Running build in "production" environment

16:09:06 PM:
std::bad_alloc

16:09:06 PM:
ERROR There was an unhandled error during compilation for /usr/src/app/www. Please run the command with the --verbose flag again.

16:09:06 PM:
16:09:06 PM:
  Error: std::bad_alloc

16:09:06 PM:
16:09:06 PM:
not finished compile gatsby files - 0.182s
![Screen Shot 2022-09-28 at 4 48 46 PM](https://user-images.githubusercontent.com/54660657/192902079-207ed16c-3ec3-4adc-a8f5-f690e684bfe6.png)
![Screen Shot 2022-09-28 at 4 48 46 PM (2)](https://user-images.githubusercontent.com/54660657/192902082-ac722eb0-3c17-49a0-9d0b-83f8d3fb4ebe.png)

### Reproduction Link

https://github.com/EdmoDev/edmo-as-dev

### Steps to Reproduce

1. So I'm done building my site and want to deploy and receive that errors I've been attempting to solve it for the past 3 days but am still unsuccessful 
2. pushed to github.
3. Used gatsby Cloud 
4. the error happened 

### Expected Result

basically I want to deploy.

### Actual Result

this happen 

td::bad_alloc

16:09:06 PM:
ERROR There was an unhandled error during compilation for /usr/src/app/www. Please run the command with the --verbose flag again.

16:09:06 PM:
16:09:06 PM:
  Error: std::bad_alloc

16:09:06 PM:
16:09:06 PM:
not finished compile gatsby files - 0.182s

### Environment

```shell
"react": "^18.2.0",
    "gatsby": "^4.24.0",
    "webpack": "^5.74.0"
    "styled-components": "^5.3.6",
    "gatsby-plugin-styled-components": "^5.24.0",
    "gatsby-plugin-react-helmet": "^5.24.0",
```

### Config Flags

module.exports = {
  siteMetadata: {
    title: `Edmond V`,
    description: ` Welcom to my Site! `,
    author: `@me`,
  },

  plugins: [
    `gatsby-plugin-styled-components`,
    `gatsby-plugin-manifest`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/static/images`,
      },
    },

    `gatsby-plugin-offline`,
    {
      resolve: "gatsby-plugin-favicons",
      options: {
        logo: "./src/favicon/favicon.png",
        appName: "MyApp",

        icons: {
          android: true,
          appleIcon: true,
          appleStartup: true,
          coast: false,
          favicons: true,
          yandex: false,
          windows: false,
        },
      },
    },
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `NV`,
        short_name: `N`,
        icon: `src/images/bot.png`,
        start_url: `/`,
        background_color: `#f7f0eb`,
        theme_color: `#a2466c`,
        display: `standalone`,
      },
    },
  ],
};

**Comment by tyhopp** [comment]
Hi @EdmoDev,

For Gatsby Cloud related issues please reach out to the support here: https://www.gatsbyjs.com/support

Thanks!

**Comment by EdmoDev** [comment]
The errors happen during the build its not just Gatsby cloud something happens with Vercel
