### ISSUE TITLE
gatsby-plugin-mdx can't handle layout written in TypeScript

### ISSUE THREAD

**Issue by christopher-besch** [gatsbyjs/gatsby#36726]
When using gatsby-plugin-mdx with a layout component written in TypeScript it fails along the lines of:
```
SyntaxError: The keyword 'interface' is reserved (12:0)
```
Apparently the TypeScript doesn't get converted.

This is the part of my `gatsby-node.js` that loads the layout:
```js
    const article_template = path.resolve("./src/templates/article.tsx");
    data.allMdx.nodes.forEach(node => {
        actions.createPage({
            path: `articles/${node.frontmatter.slug}`,
            // component: `${article_template}`,
            component: `${article_template}?__contentFilePath=${node.internal.contentFilePath}`,
            context: {
                id: node.id,
            },
        })
    });
```

I've tried removing the `__contentFilePath` and the error is gone. But this of course leads to the children prop to be undefined and nothing being shown on the website.
My guess is that by using this more complicated URI, the file doesn't get converted from TypeScript to JavaScript. What should be used instead?

**Comment by FoundTheWOUT** [comment]
I just check out your [repo](https://github.com/christopher-besch/homepage/blob/main/gatsby-node.js). You should query the contentFilePath field to the graphql, which providing the path of your post file. For example.
```js
query Articles {
  allMdx(filter: {frontmatter: {type: {eq: "article"}}}) {
    nodes {
      frontmatter {
        slug
      }
      internal {
        contentFilePath
      }
    }
  }
}
`);
```

And, i think it's better to share a minimal reproduction when you openning a issue.

**Comment by christopher-besch** [comment]
Thank you very much for your quick response, @FoundTheWOUT!

> I just check out your [repo](https://github.com/christopher-besch/homepage/blob/main/gatsby-node.js). You should query the contentFilePath field to the graphql, which providing the path of your post file. For example.

The version on GitHub is outdated. This is how it looks like: https://github.com/christopher-besch/homepage/blob/5404fcc6d73cdeb718c020f52da6c546d83823eb/gatsby-node.js#L4-L18
I already querying the contentFilePath field.

> And, i think it's better to share a minimal reproduction when you openning a issue.

I thought the solution would be as simple as: "You forgot a comma in the URI."
I'll get to creating a reproduction.

**Comment by christopher-besch** [comment]
I really don't know why I didn't create a minimal reproduction. The reproduction doesn't have the issue. And now I'm left figuring out what makes my site not work...

Thanks for your help though!

**Comment by amalitsky** [comment]
@christopher-besch, I'm experiencing similar issue after updating MDX to v.4. Any advice from you?

**Comment by christopher-besch** [comment]
I don't really know what fixed the problem. I recreated gatsby-node.ts, gatsby-config.ts and package.json and it worked. This is the commit that fixed it for me: https://github.com/christopher-besch/homepage/commit/2803d5bcea1ab41757c2b41cf3aa236e6769bb3e#diff-26b5c624a22b9f24d3e683f7ee5b69788ee6b166a655b7423b6a4c5a1ef6f0a1
I hope it helps.

But I'd recommend you do the same and rebuild your application from scratch. You can obviously copy all the content over—you only have to reinstall all plugins and write some of your gatsyb-something.ts files again. This was surprisingly quick to do for me.

**Comment by amalitsky** [comment]
Ok, I'm still working on it but got pages in question to render and build to go through.

My "solution" was to *remove* `gatsby-plugin-typescript` from the list of Gatsby plugins. Since, [apparently](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-typescript#gatsby-plugin-typescript):
> This plugin is automatically included in Gatsby. The only reason you would need to explicitly use this plugin is if you need to configure its options.

And I didn't have any custom options set there.

**Comment by yolomep** [comment]
Can confirm, removing gatsby-plugin-typescript does solve this issue. 
```javascript
        // {
        //     resolve: "gatsby-plugin-tsconfig-paths",
        //     options: {
        //         configFile: `${__dirname}\\tsconfig.json`,
        //     },
        // },
```
is not needed.
