### ISSUE TITLE
Memory leak in 15+ versions

### ISSUE THREAD

**Issue by macsmel** [gatsbyjs/gatsby#36732]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Newer versions Gatsby from 4.15 to 4.24.0 I see a memory leak in **gatsby develop**. He consumes from 6 to 14gb of ram. Each reload or opening of a new page increases consumption. Flags help, but not much. No need to tell me to increase the memory size in the node, this is nonsense. I rolled back all projects to version 14 and will wait for fixes. I carefully checked each dependency and config, the problem is only in the version of the node. I tried debugging each process, but found nothing useful.

150 pages in total.
I am attaching the config below.

PLEASE FIX THAT!

![memory](https://user-images.githubusercontent.com/47138382/193563796-86abb555-fe40-47ff-9ad0-279fe71634f8.jpg)

### Reproduction Link

https://githubbox.com/gatsbyjs/gatsby-starter-minimal

### Steps to Reproduce

1. run gatsby develop

### Expected Result

Consumption of a maximum of 3 GB of RAM. (As in version 14)

### Actual Result

Consumption of 12-14 GB of RAM.

### Environment

```shell
System:
    OS: macOS 12.6
    CPU: (4) x64 Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.91
    Firefox: 104.0.2
    Safari: 16.0
```

### Config Flags

gatsby-plugin-google-gtag
gatsby-plugin-pnpm,
gatsby-plugin-react-helmet,
gatsby-plugin-minify-html,
gatsby-source-contentful,
gatsby-plugin-breakpoints
gatsby-source-filesystem
gatsby-source-filesystem
gatsby-plugin-react-i18next
gatsby-plugin-image,
gatsby-transformer-sharp,
gatsby-plugin-sharp,
gatsby-plugin-manifest
gatsby-plugin-sass,
gatsby-plugin-split-css,
gatsby-plugin-advanced-sitemap
gatsby-plugin-robots-txt
gatsby-plugin-manifest
gatsby-plugin-offline

**Comment by pieh** [comment]
@macsmel Can you provide actual reproduction repository?

Trying latest gatsby on minimal gatsby starter (which you linked) and refreshing 300 times and taking heap snapshots at certain points doesn't show memory leak:

![image](https://user-images.githubusercontent.com/419821/193661459-5866ca8c-b8ab-4c56-beba-c51890216acd.png)

**Comment by macsmel** [comment]
> 
@pieh 
I can't provide a working confidential company repository. You should create a 150 page test repo yourself with the plugins above and test your framework.

**Comment by macsmel** [comment]
There is no memory leak in 4.24.1 version.
