### ISSUE TITLE
Can't remove default plugins via webpack-configurator

### ISSUE THREAD

**Issue by vanbroup** [gatsbyjs/gatsby#3673]
I'm trying to replace the default `UglifyJsPlugin` via `config.removePlugin` as specified in the [webpack-configurator documentation](https://www.npmjs.com/package/webpack-configurator#configremovepluginkey):

```
    config.removePlugin('uglify');
    config.removePlugin('uglify-js');
    config.removePlugin('UglifyJsPlugin');
```

Unfortunately none of the above seem to work. I think because the UglifyJsPlugin is not loaded via the `config.plugin` system in [webpack.config.js](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/webpack.config.js#L323).

I found an ugly workaround by updating the configuration and excluding all files:
```
const webpack = require('webpack')

exports.modifyWebpackConfig = ({ config, stage }) => {
  if (stage === 'build-javascript') {
    // disbale the default uglify plugin
    const uglifyJsPluginInstace = config._config.plugins.find(
      plugin => plugin instanceof webpack.optimize.UglifyJsPlugin
    )
    if (uglifyJsPluginInstace) {
      uglifyJsPluginInstace.options = {
        exclude: /.*/
      }
    }

    // use the es6 compatible uglify plugin
    const UglifyJsPlugin = require('uglifyjs-webpack-plugin')
    config.plugin('uglifyjs-webpack-plugin', () => new UglifyJsPlugin());
  }
  return config
}
```

**Comment by calcsam** [comment]
Yes, we hard-code uglify here:

https://github.com/gatsbyjs/gatsby/blob/3ce568dacf5aac0eaa1103cc1c8f9579e1253569/packages/gatsby/src/utils/webpack.config.js#L323

What's the use case you have for removing it?

**Comment by KyleAMathews** [comment]
A PR making Uglify overridable would be great 👍

**Comment by vanbroup** [comment]
@calcsam the hardcoded version of UglifyJsPlugin breaks on many dependencies such as [punycode](https://www.npmjs.com/package/punycode) and [moment](https://www.npmjs.com/package/moment). The alternative [uglifyjs-webpack](https://github.com/webpack-contrib/uglifyjs-webpack-plugin)-plugin is using [UglifyJS v3](https://github.com/mishoo/UglifyJS2/tree/harmony) (`uglify-es`).

@KyleAMathews I would love to create some pull requests, unfortunately, at this moment all my time is needed to optimize the build, which is still including 70% of not used bytes. _(It would help if included stylesheets would only cover the first render, everything else (for other pages) can be loaded dynamically. In our case, we only need 90% of the styles on a management page when a user logged-in, but currently, they are included in every view. PurifyCSS doesn't help in this case)_

**Comment by dotmagic** [comment]
@vanbroup I'm using CSS-in-JS, I think it's builtin with Gatsby? It still hurts my eyes sometimes because I always cared to keep styles separate. But Gatsby changed the game. It makes now sense to keep it in your Templates, so only the styles that's really used get loaded. Since it's not inline css you don't need to worry about performance. I think I'll remember that's the preferred way Kyle use, so it can't be wrong :+1:

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
