### ISSUE TITLE
How to use animated transition in client-only paths site

### ISSUE THREAD

**Issue by drakang4** [gatsbyjs/gatsby#3674]
I'm trying to add animated transition in my client-only paths site so I looked [client-only-paths example](https://github.com/gatsbyjs/gatsby/tree/master/examples/client-only-paths) and I found out this example was actually designed to do animated transition like [this](https://reacttraining.com/react-router/web/example/animated-transitions) 
```
// in gatsbyjs/examples/client-only-paths/src/pages/index.js

                <ReactCSSTransitionGroup
                  transitionName="fade"
                  transitionEnterTimeout={300}
                  transitionLeaveTimeout={300}
                >
                  {/* no different than other usage of
                ReactCSSTransitionGroup, just make
                sure to pass `location` to `Route`
                so it can match the old location
                as it animates out
            */}
                  <Route
                    location={location}
                    key={location.key}
                    path="/:h/:s/:l"
                    component={HSL}
                  />
                </ReactCSSTransitionGroup>
```
However the example does not trigger any animation: https://client-only-paths.gatsbyjs.org/
Is there any way to do animated transition in client-only paths site?

Thanks!

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
