### ISSUE TITLE
[gatsby-plugin-offline] Ability to listen for service worker updates?

### ISSUE THREAD

**Issue by IljaDaderko** [gatsbyjs/gatsby#3677]
## Description

I've implemented `gatsby-plugin-offline` today, works very nice, but I can't seem to find documentation on updating website if new assets are available. We have previously worked with webpack offline plugin to use service workers in similar manner. It exposed window events i.e. when new service worker files are available, so we had ability to show user a prompt to update, which in my opinion was a nice ux. Once they clicked update we simply reloaded the window.

Is it possible to achieve this with `gatsby-plugin-offline` ?

### Environment

Gatsby version: unrelated
Node.js version: unrelated
Operating System: unrelated

**Comment by calcsam** [comment]
Currently gatsby-plugin-offline caches files locally on your system -- it doesn't use SW to push live content updates into your page post-load. We want to add this capability sometime in the future for live updating data (eg weather, sports scores) but for now if you want to do this the recommended way is having a component that polls your API for new data.

**Comment by KyleAMathews** [comment]
@calcsam he's referring to the SW update lifecycle events https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle e.g. an updated SW has been downloaded.

@IljaDaderko it's not currently possible but we'd be happy to take a PR exposing SW lifecycle events. They could be added to this file https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/register-service-worker.js Would be happy to walk you through a PR!

**Comment by IljaDaderko** [comment]
@KyleAMathews could be interesting!
I had a quick glance at https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/register-service-worker.js#L25 (so it will still reload the window when new content is available?).

Let me know how you'd like these events implemented, I'll give it a shot :)

**Comment by KyleAMathews** [comment]
we added a bunch! https://next.gatsbyjs.org/docs/browser-apis/#onServiceWorkerActive
