### ISSUE TITLE
`TypeError: Cannot read properties of null (reading 'dir')` in index.tsx when using actions.createPage in gatsby-node.ts

### ISSUE THREAD

**Issue by christopher-besch** [gatsbyjs/gatsby#36776]
I'm having the same problem as described in https://github.com/gatsbyjs/gatsby/issues/34693 but only when I'm querying the image in the `index.tsx` page.

I've managed to reproduce this here: [https://github.com/christopher-besch/gatsby_broken_image_sharp](https://github.com/christopher-besch/gatsby_broken_image_sharp)
This issue occurs only sometimes, most of the time when using `gatsby develop`, rather than `gatsby build`. You might have to try every step multiple times.

1. clone the repo and run `gatsby develop`
2. open `http://localhost:8000/test` and you will see three images, this is the expected behaviour.
3. open `http://localhost:8000` and you won't see anything. There should be a few errors in the console:
    ```
    Warning: Failed prop type: The prop `image` is marked as required in `GatsbyImage`, but its value is `undefined`.
    ```
    you sometimes also get an error in the node console:
```
 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Cannot read properties of null (reading 'dir')

   1 | query Articles {
   2 |   allMdx {
   3 |     edges {
   4 |       node {
   5 |         id
   6 |         frontmatter {
>  7 |           thumb {
     |           ^
   8 |             childImageSharp {
   9 |               gatsbyImageData(placeholder: BLURRED)
  10 |             }
  11 |           }
  12 |         }
  13 |       }
  14 |     }
  15 |   }
  16 | }
  17 |

File path: /home/chris/dwn/broken_image_sharp/src/pages/index.tsx
Url path: /
Plugin: none



  TypeError: Cannot read properties of null (reading 'dir')

  - resolvers.ts:535 queryNodeByPath
    [broken_image_sharp]/[gatsby]/src/schema/resolvers.ts:535:63

  - resolvers.ts:546 fileByPathResolver
    [broken_image_sharp]/[gatsby]/src/schema/resolvers.ts:546:14

  - task_queues:95 processTicksAndRejections
    node:internal/process/task_queues:95:5

  - async Promise.all

  - async Promise.all

  - async Promise.all

  - async Promise.all

  - async Promise.all
```
The `index.tsx` and `test.tsx` files are identical.

This problem only occurs when the `gatsby-node.ts` creates all the article pages like this:
```ts
    data.allMdx.nodes.forEach((node: any) => {
        actions.createPage({
            path: `articles/${node.frontmatter.slug}`,
            component: node.internal.contentFilePath,
        })
    });
```
The article pages themselves won't compile but that's only because I didn't bother making them work in the reproduction.

```
  System:
    OS: Linux 5.19 undefined
    CPU: (12) x64 AMD Ryzen 5 PRO 5650U with Radeon Graphics
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.10.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Languages:
    Python: 3.10.7 - /usr/bin/python
  Browsers:
    Firefox: 105.0.2
  npmPackages:
    gatsby: ^4.24.3 => 4.24.3 
    gatsby-plugin-image: ^2.24.0 => 2.24.0 
    gatsby-plugin-mdx: ^4.3.0 => 4.3.0 
    gatsby-plugin-sharp: ^4.24.0 => 4.24.0 
    gatsby-source-filesystem: ^4.24.0 => 4.24.0 
    gatsby-transformer-sharp: ^4.24.0 => 4.24.0 
```

**Comment by marvinjude** [comment]
Hi @christopher-besch,

Sorry you're running into this. This looks similar to https://github.com/gatsbyjs/gatsby/issues/36728. While we figure out how to fix this, you can use the workaround described in https://github.com/gatsbyjs/gatsby/issues/36728#issuecomment-1265889203

**Comment by marvinjude** [comment]
Closing this as duplicate issue. Please feel free to reopen if the workaround doesn't work for you.

**Comment by christopher-besch** [comment]
I tried it and the workaround seems to work. Thanks a lot!
I'll update my page once you role out a proper fix.

**Comment by pieh** [comment]
`gatsby@4.24.5` was released with the fix for this, so you should be able to upgrade and drop the workaround
