### ISSUE TITLE
Gatsby doesn't fail when there is an issue in CSS

### ISSUE THREAD

**Issue by just-boris** [gatsbyjs/gatsby#3678]
Whenever I have any issue in CSS file, for example, I import the missing image

```css
.picture {
    background: url(./missing-file.png);
}
```

It doesn't fail the build. `gatsby build`  just outputs an empty file, omitting all other stylesheets as well. For the sake of safe continuous delivery and deploy, I believe, that such issues should make Gatsby return non-zero exit code.

There are two possible solutions:
* Switch [bail option](https://webpack.js.org/configuration/other-options/#bail) in Webpack to `true`. It will make them to fail on any issue occurred.
* Modify [the following line](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/commands/build-css.js#L12) in `build-css` file:

```diff
+ webpack(compilerConfig.resolve()).run((err, stats) => {
- webpack(compilerConfig.resolve()).run(err => {
+   if(stats.toJson().errors.length > 0) {
+      reject(stats.toJson().errors[0])
+   }
    if (err) {
      reject(err)
    }
```

Which of those two options would you prefer? I can send a PR with the chosen one.

**Comment by benjaminhoffman** [comment]
btw, does it fail for you when you `gatsby develop`?

**Comment by just-boris** [comment]
Yes, I see an error in the console during `gatsby develop`, but not in `gatsby build` command.

**Comment by KyleAMathews** [comment]
@just-boris sorry you're having trouble! We should definitely add the second option to better print out errors.

On bailing — I liked @jquense's suggestion here: https://github.com/gatsbyjs/gatsby/issues/2087#issuecomment-328618722 Would love a PR adding this!

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
