### ISSUE TITLE
Build Order not correct, cache lmdb inconsistent with static query during ssr

### ISSUE THREAD

**Issue by simonjoom** [gatsbyjs/gatsby#36789]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Using caches-lmdb give a problem to gatsby to regenerate pages using static-queries, if the public cache folder is removed.

I use static query that i need their results to render my pages, the actual gatsby code has got a problem about using the cache lmdb and rebuild without removing this cache.

So i dont want to remove caches-lmdb everytime i need to rebuild my website because i have lot of page processed which need time to rebuild.

if i delete the cache folder page-data from public (where static-query live) and try to build again, i end up with a not found error about static query not found in /page-data/sq/d/**.js during ssr generation.

I think there is some change need to be done here.

looked at the code:

i suggest to change the order of some code:
in build.js
The piece of code running the queries should to be before the activity 'Building HTML renderer' and not after, else static queries won t be available during ssr.

in query-runner.js an other test was needed to force to regenerate the static queries even if they are in the cache lmdb
i just added " || !queryJob.isPage", maybe will be better to check the existance of the static queries files.

```
  if ((resultHash !== el)|| !queryJob.isPage || (queryJob.isPage && !(0, _pageData.pageDataExists)(_path.default.join(program.directory, 'public'), queryJob.id))) {
    await resultHashCache.set(queryJob.id, resultHash);

    if (queryJob.isPage) {
      // We need to save this temporarily in cache because
      // this might be incomplete at the moment
      await (0, _pageData.savePageQueryResult)(program.directory, queryJob.id, resultJSON);

      _redux.store.dispatch({
        type: `ADD_PENDING_PAGE_DATA_WRITE`,
        payload: {
          path: queryJob.id
        }
      });
    } else {
      const resultPath = _path.default.join(program.directory, 'public', `page-data`, `sq`, `d`, `${queryJob.hash}.json`); 
console.log("resultpath",resultPath)
      await _fsExtra.default.outputFile(resultPath, resultJSON);
    }
  
  } // Broadcast that a page's query has run.
```

### Steps to Reproduce

1.Remove public cache folder
2.have a repo using static queries for rendering html.
3.keeping caches-lmdb in .cache

result not found error for static queries in public cache folder during ssr rendering pages.

### Expected Result

Should have a rebuild succeed with the conditions acted before.

### Actual Result

built failed

### Environment

```shell
Mac os
Gatsby current version
```

### Config Flags

dev_ssr: false

**Comment by LekoArts** [comment]
You mustn't remove the `.cache` folder or parts of it between builds. You can only get a successful build if you keep `.cache` and `public` around or delete both completely.

**Comment by simonjoom** [comment]
> 

Well for me i do not want to delete the .cache folder completly and want to keep lmdb cache to avoid to process data from my sourcewordpress plugin (who take a long time). 
I have got a multilanguage website, each build is for one language and i would like to keep lmdb cache for saving some times. ( i did add a prefix to lmdb cache to have it consistent)

Anyway it s seems for me not correct that the current code do not process the queries before html ssr render, 
 For those who need result queries for ssr render it will create an error even if .cache folder and public folder is empty. (My static queries have got my mainmenu for some language by exemple)
