### ISSUE TITLE
[www] Add reference to "How to contribute" and the "Gatsby Style Guide" to the "Community" page

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#3682]
Both "How to contribute" and the "Gatsby Style Guide" provide important and helpful (and some quite unique!) content that currently is missing from the ["Community" section](https://www.gatsbyjs.org/community/) on https://www.gatsbyjs.org/.

I want to suggest adding these there – maybe along adding a new layout that allows content to live in two columns? I think on larger screens we should pull these infos above the fold if possible.

/cc @shannonbux

**Comment by shannonbux** [comment]
Very much agree with this. In fact, at some point it would be great to rethink all three docs are organized because they are so closely interrelated. Right now I just keep adding things when we think of them, so the process has been a bit haphazard.

**Comment by shannonbux** [comment]
I'll do a PR later today

**Comment by shannonbux** [comment]
Finished this!

**Comment by fk** [comment]
👍
