### ISSUE TITLE
[gatsby-plugin-sitemap] Custom filter function not used without specifying excludes

### ISSUE THREAD

**Issue by PeterDekkers** [gatsbyjs/gatsby#36830]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I'll start by saying that maybe this is intended, but in that case the documentation could be more clear about it.

When there is no `excludes` array specified (or an empty one) in the options, then the custom `filterPages` function never runs. I feel that it should be run once in this case, across all the pages.

For example, in our project we filter pages based on a `pageContext` value, and so our configuration looks like this:
```typescript
{
    resolve: `gatsby-plugin-sitemap`,
    options: {
        query: `
        {
            allSitePage {
                nodes {
                    path
                    pageContext
                }
            }
        }
        `,
        // Exclude pages which have been explicitly marked as 'noindex' in `createPages.tsx`
        filterPages: (page: PageProps): boolean =>
            Boolean((page.pageContext as PageContext).noindex),
    },
},
```

### Reproduction Link

https://github.com/PeterDekkers/gatsby-plugin-sitemap-filter-bug

### Steps to Reproduce

1. Run `gatsby build`

### Expected Result

This should cause an error to be thrown from `filterPages`.

### Actual Result

The error is never thrown as the custom `filterPages` function is not run.

### Environment

```shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
  Languages:
    Python: 3.10.4 - /Users/peter/.pyenv/shims/python
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 103.0.2
    Safari: 16.0
  npmPackages:
    gatsby: ^4.24.4 => 4.24.4
    gatsby-plugin-image: ^2.24.0 => 2.24.0
    gatsby-plugin-manifest: ^4.24.0 => 4.24.0
    gatsby-plugin-sharp: ^4.24.0 => 4.24.0
    gatsby-plugin-sitemap: ^5.24.0 => 5.24.0
    gatsby-source-filesystem: ^4.24.0 => 4.24.0
    gatsby-transformer-sharp: ^4.24.0 => 4.24.0
```

**Comment by PeterDekkers** [comment]
P.S.: I'm happy to set up a PR for this, if that's deemed useful.

**Comment by LekoArts** [comment]
This is working as intended.

From the README:

> excludes (string[] = []) An array of paths to exclude from the sitemap. You can use glob matching using [minimatch](https://github.com/isaacs/minimatch). While excludes is usually an array of strings it is possible to enter other data types into this array for custom filtering, but doing so will require customization of the [filterPages](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sitemap#filterPages) function.

> [filterPages](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sitemap#filterPages) (function) Takes the current page and a string (or other object) from the exclude array and expects a boolean to be returned. true excludes the path, false keeps it.

Plus explanation of how it works: https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sitemap#filterpages--boolean

Where would you think the documentation could be improved?

**Comment by PeterDekkers** [comment]
Thank you @LekoArts.

> Where would you think the documentation could be improved?

I feel that an explicit mention could be made under the entry for [filterPages](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sitemap#filterPages), to say e.g. (bold for proposed change):
> Takes the current page and a string (or other object) from the exclude array and expects a boolean to be returned. true excludes the path, false keeps it. **Note that when the exclude array is undefined or empty this function will never be called.**

I guess my gripe is with the name of the function, `filterPages`. It seems to imply that you can use it to filter pages, but instead it's reliant on entries in the `excludes` array, which seems like a strange dependency.

How do you suggest someone handles the case of wanting to filter the pages _without_ a specific `excludes` string entry? E.g. by using a `pageContext` value like in the example in my original post.

One could override `resolvePages` to apply filtering?

Or, one could add a callback function into the `excludes` array, instead of a string, and this callback would then be passed to `filterPages` to apply filtering. This would conflict with the typing of `excludes (string[] = [])`, which seems a bit hacky perhaps, even though the documentation mentions this as an option.

Thank you!

**Comment by uberfuzzy** [comment]
Ive also been fighting with the poor documentation with this for a week, and I have an answer.

Providing an override function for `filterPages` is not for filtering your queried content, its for overriding the simple glob-like matching log (via `minimatch` for better or worse) that the simple `exclude` list is matched against. It exists in case you need to do more complex PATH matching than minimatch can handle, or you need to match against things that arent strings. I agree it is a poor choice of function naming.

To filter your content down, do it in `resolvePages`. This sits after the query is run, and ultimately, whatever "big array of stuff"  returned from it is what ends up in the sitemap. You can also do sorting here, if you feel that matters to your sitemap.

The default `resolvePages` is even just a straight `return data.allSitePage.nodes` (after a null check), so its not doing anything really.

**Comment by LekoArts** [comment]
PRs to improve the documentation and wording are very welcome! We currently don't have the bandwidth with Gatsby 5 coming up
