### ISSUE TITLE
unable to use esbuild in a plugin due to webpack bundling

### ISSUE THREAD

**Issue by wKovacs64** [gatsbyjs/gatsby#36841]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When attempting to use `esbuild` in a plugin, consumers of the plugin are met with the following build error:

```
The esbuild JavaScript API cannot be bundled. Please mark the "esbuild" package as external so it's not included in the bundle.

More information: The file containing the code for esbuild's JavaScript API (${__filename}) does not appear to be inside the esbuild package on the file system, which usually means that the esbuild package was bundled into another file. This is problematic because the API needs to run a binary executable inside the esbuild package which is located using a relative path from the API code to the executable. If the esbuild package is bundled, the relative path will be incorrect and the executable won't be found.
```

Kyle confirmed in Discord that plugins are bundled when using SSG/DSG, so that explains it. Is there a workaround for this situation?

**Full story:** I have the need to minify some code in `onRenderBody` (based on user provided plugin options). I am currently using Terser to do this, but Terser removed the synchronous version of its minification API in v5, so I am stuck on an old version (v4) as I have not found a way to do anything asynchronously in `onRenderBody`. Rather than remain stuck on an old version of Terser, I attempted to swap it out for esbuild as it provides a synchronous transform API - but it yields the error above when consumers of the plugin try to build their sites.

### Reproduction Link

https://stackblitz.com/edit/github-rxafmb?view=editor

### Steps to Reproduce

1. Download the provided StackBlitz project (it doesn't run on SB for some reason, but it does locally)
2. `npm install` dependencies in the root and also in `plugins/my-plugin`
3. `npm run build`
4. Observe the error about esbuild

### Expected Result

I would expect it to build successfully.

### Actual Result

The HTML stage of the build fails with the following error:

```
The esbuild JavaScript API cannot be bundled. Please mark the "esbuild" package as external so it's not included in the bundle.

More information: The file containing the code for esbuild's JavaScript API (${__filename}) does not appear to be inside the esbuild package on the file system, which usually means that the esbuild package was bundled into another file. This is problematic because the API needs to run a binary executable inside the esbuild package which is located using a relative path from the API code to the executable. If the esbuild package is bundled, the relative path will be incorrect and the executable won't be found.
```

### Environment

```shell
System:
  OS: Windows 10 10.0.22621
  CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Binaries:
  Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
  Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
  npm: 8.12.2 - C:\Program Files\nodejs\npm.CMD
Languages:
  Python: 3.10.7
Browsers:
  Chrome: 106.0.5249.119
  Edge: Spartan (44.22621.674.0), Chromium (106.0.1370.47)
npmPackages:
  gatsby: ^4.24.4 => 4.24.4
```

### Config Flags

N/A

**Comment by LekoArts** [comment]
If we'd mark `esbulid` as external, webpack would just leave the import instead of trying to bundle it. Locally this will work because you have `node_modules`, but the SSR/DSG engines doesn't have `node_modules` available. So this will never work.

You need to think about another way of parsing the options. Here's what I'd try:

In `onCreateWebpackConfig` parse the options, use the define plugin (https://webpack.js.org/plugins/define-plugin/), and then access it later.
