### ISSUE TITLE
[v2] Upgrade Remark and related packages to latest major release

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#3685]
https://github.com/remarkjs/remark/releases

**Comment by m-allanson** [comment]
Dependencies are updated, I have a branch that updates the example site which I need to finish and push up.

**Comment by m-allanson** [comment]
Related PRs:

- #5097 
- #5047

**Comment by m-allanson** [comment]
This was finished off in #5220, closing!
