### ISSUE TITLE
gzip does not work for .riv files on Gatsby hosting with custom domains

### ISSUE THREAD

**Issue by Den-Bratchikov** [gatsbyjs/gatsby#36871]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

gzip does not work for .riv files on gatsby hosting for custom domains. 

on gatsby domains:  [pixelpoint.gtsb.io](https://pixelpointwebsite-gatsbyhead.gtsb.io/) the content passed as `gzip`, 
<details>

![2022-10-24_16-57-55](https://user-images.githubusercontent.com/75138180/197520703-77b07565-7c1d-4c67-8dc3-303b0f7923d2.png)

</details>

on custom domains:  [pixelpoint.io](https://pixelpoint.io/)- as an `application/wasm` without encoding
<details>

![2022-10-24_16-56-14](https://user-images.githubusercontent.com/75138180/197520647-99782c7e-a9e0-4b0f-bcf2-6ed7c7cf2202.png)

</details>

### Reproduction Link

https://pixelpoint.io/

### Steps to Reproduce

1. Open devtools;
2. Open the `network tab`;
3. Disable cache by clicking the corresponding checkbox;
4. Select the multiple file types;
5. Find the `hero.riv` in a list;
6. See the data in the Response headers tab;

### Expected Result

It was expected that the `.riv` format animation files would be transferred to custom domains using gzip encoding

### Actual Result

Animation files of the `.riv` format are passed raw to custom domains, without gzip encoding.

### Environment

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (6) x64 AMD Ryzen 5 4500U with Radeon Graphics
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.10.4
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (106.0.1370.52)
  npmPackages:
    gatsby: ^4.24.4 => 4.15.2
```

### Config Flags

flags: { DEV_SSR: process.env.GATSBY_DEV_SSR || false },

**Comment by LekoArts** [comment]
For Gatsby Cloud related issues please go here: https://www.gatsbyjs.com/support
