### ISSUE TITLE
Browserslist config not working for old versions browsers

### ISSUE THREAD

**Issue by lararthur** [gatsbyjs/gatsby#36873]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Our team has been trying to achieve a maximum range of browsers support through polyfills, generated by babel and configurated by `browserslist` in `.babelrc` file, when using `babel-preset-gatsby`.

The goal is to make our application not break or accuse errors when using rest/spread operators. But the outcome is always an `Unexpected token ...` in the console when using an old Chrome (v 50.0).

The config at `.babelrc` follows:
```
{
  "presets": [
    [
      "babel-preset-gatsby",
      {
        "targets": {
          "browsers": ["cover 100% in BR"]
        }
      }
    ]
  ]
}
```

Although trying different approaches of configuration like:
- `"browserslist": ["cover 100% in BR"]` on `package.json`
- `cover 100% in BR` in a `.browserslistrc` file
- each config separately, combining two of each possible combinations, or all together.

Seaching in the application, we still have some remaining reference to this `[">0.25%", "not dead"]` browserslist config such as:
- `getBrowsersList` function, on `/node_modules/gatsby/dist/utils/browserslist.js`
- `browserslist.js.map` file on `/node_modules/gatsby/dist/utils/browserslist.js.map`

It seems that there is a problem with the fallbacks when setting a custom range of browsers, since the default config always remains.

### Reproduction Link

https://codesandbox.io/s/cranky-fire-lv2fre

### Steps to Reproduce

1. install `babel-preset-gatsby` as a dev dependency
2. create `.babelrc` file
3. modify target.browsers to `["cover 100% in BR"]`
4. perform a `gatsby build`
5. serve the public folder
...

### Expected Result

Application running in Chrome v50.0 without console errors.

### Actual Result

Chrome still pointing an `Unexpected token ...` error due to usage of the spread operator.

Most likely, polyfills are still being generated considering the `[">0.25%", "not dead"]` config.

### Environment

```shell
System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.15.4/bin/yarn
    npm: 8.1.4 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 104.0.2
    Safari: 16.0
  npmPackages:
    gatsby: ^4.24.4 => 4.24.4 
  npmGlobalPackages:
    gatsby-cli: 4.24.0
```

### Config Flags

no flags

**Comment by lararthur** [comment]
@Malatisahoo how would opera gx be useful?

**Comment by mrahils** [comment]
@lararthur , were you able to find a fix for this? The issue is still exists `Unexpected token ...`. Looks like transpilation issue due to spread operator.

**Comment by lararthur** [comment]
@mrahils i have nothing new on that, sorry :(

Still hoping for a good soul to come and help us

**Comment by 808vita** [comment]
https://babeljs.io/docs/babel-plugin-transform-object-rest-spread
I think this is relevant here .
![image](https://github.com/gatsbyjs/gatsby/assets/97225946/6d0d3842-2e3a-49f8-923c-4989c138279a)


like @lararthur mentioned polyfill is not kicking in (evident from the error ).

please check if babel has the plugin installed and configured .
this is the only lead I have for you guys .

**Comment by 808vita** [comment]
![image](https://github.com/gatsbyjs/gatsby/assets/97225946/fa4add90-cc64-4f55-abc4-0627d2bbdca5)

https://www.npmjs.com/package/babel-preset-gatsby

not sure if spread related package is bundled in this .

**Comment by kristerlooga-bolt** [comment]
Sadly this problem still persists. Although `@babel/plugin-transform-object-rest-spread` is not listed under `babel-preset-gatsby`, then `@babel/preset-env` is listed and it contains `@babel/plugin-transform-object-rest-spread` in it.
