### ISSUE TITLE
SOUBHAGYA SEKHAR

### ISSUE THREAD

**Issue by Malatisahoo** [gatsbyjs/gatsby#36884]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

Hello

### Steps to Resolve this Issue

1.
2.
3.
...
Good

**Comment by Malatisahoooo** [comment]
Good

**Comment by Malatisahoooo** [comment]
Hmm
