### ISSUE TITLE
Is there any way how to make gatsby urls work with any case.

### ISSUE THREAD

**Issue by gowthamik14** [gatsbyjs/gatsby#36910]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

Hello,
I have a requirement where the user want to navigate to  the page directly  /fields/entity. however the static page was generated using Create pages API and the URL generated Fields/Entity. Is there a way that Gatsby support case insensitive URLs.
Is there any documentation available

Gatsby version : 4.21.1

### Steps to Resolve this Issue

1.
2.
3.
...

**Comment by LekoArts** [comment]
Please use https://github.com/gatsbyjs/gatsby/discussions for questions
