### ISSUE TITLE
Gatsby logo not found

### ISSUE THREAD

**Issue by ShaneMckenna23** [gatsbyjs/gatsby#3696]
The Gatsby SVG image is missing: https://www.gatsbyjs.org/gatsby-negative.svg

**Comment by fk** [comment]
Hi @ShaneMckenna23! I removed that file in #3639, but tried to make sure it's not in use anywhere. Did I miss something? Were you linking to it directly?

**Comment by ShaneMckenna23** [comment]
Hey @fk,
I was using it like this:
<img alt="Gatsby" src="https://www.gatsbyjs.org/gatsby-negative.svg" width="100">

I copied it from your readme, which is also missing the logo

**Comment by fk** [comment]
Ouch, sorry for that. That and some more logo variants eventually will come back to gatsbyjs.org, in the meantime you can grab the updated logos from https://github.com/gatsbyjs/gatsby/issues/3363#issuecomment-360206669 to fix your issue.

> I copied it from your readme, which is also missing the logo

Argh! Apparently I am too stupid to properly search! 😳
Will fix in a minute! Thank you!

**Comment by fk** [comment]
Fixed, logo is now at https://www.gatsbyjs.org/monogram.svg. Maybe consider not hotlinking it in the future?! ;-) Thanks for reporting! <3
