### ISSUE TITLE
Add link - where to submit ideas 

### ISSUE THREAD

**Issue by akkshayTandon** [gatsbyjs/gatsby#36973]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

- Under the privileges section of gatsby-governance-model (https://www.gatsbyjs.com/contributing/gatsby-governance-model/)
it is written if that if any one has ideas for privileges one send it but not specified where to submit it.

- So a link should be added as where to send ideas.

### Steps to Resolve this Issue

1. Link to the gatsby discusssions page could be added as for now.
2. A discussion should be done on if a seperate form should be added on the website for this purpose.

**Comment by LekoArts** [comment]
Please see https://github.com/gatsbyjs/gatsby/pull/36974#issuecomment-1305162782
