### ISSUE TITLE
Text content does not match server-rendered HTML.

### ISSUE THREAD

**Issue by MotaZor94** [gatsbyjs/gatsby#36982]
### Preliminary Checks

- [x] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi, 

I am currently working on a project that has this error in production 
<img width="735" alt="Screenshot 2022-11-07 at 20 26 16" src="https://user-images.githubusercontent.com/45624002/200397133-877d0f19-5cd1-44d1-ab0b-16562d3f266f.png">

It points to https://reactjs.org/docs/error-decoder.html/?invariant=418

I have tried cloning a fresh instance of gatsby-starter-default and it has the same issue so I assume it's something for you guys to check what's going on. 

### Reproduction Link

https://www.gatsbyjs.com/starters/gatsbyjs/gatsby-starter-default

### Steps to Reproduce

1. Download gatsby-starter-default
2. Deploy it to gatsby cloud
3. Check the errors in the console
...

### Expected Result

I'm expecting to get rid of this error :D

### Actual Result

I've got the above mentioned error.

### Environment

```shell
System:
    OS: macOS 12.4
    CPU: (10) x64 Apple M1 Pro
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Safari: 15.5
  npmPackages:
    gatsby: ^4.24.7 => 4.24.7
    gatsby-plugin-image: ^2.24.0 => 2.24.0
    gatsby-plugin-manifest: ^4.24.0 => 4.24.0
    gatsby-plugin-prettier-build: ^0.4.4 => 0.4.4
    gatsby-plugin-sharp: ^4.24.0 => 4.24.0
    gatsby-source-filesystem: ^4.24.0 => 4.24.0
    gatsby-transformer-sharp: ^4.24.0 => 4.24.0
  npmGlobalPackages:
    gatsby-cli: 4.23.0
```

**Comment by marvinjude** [comment]
Hi!

I was unable to reproduce by following the steps above and this is most likely because we released a new major recently that somehow fixed it. 

To start looking into this it would be helpful if you could provide a link to the repository where this is happening on.

**Comment by MotaZor94** [comment]
Hi @marvinjude, if you run gatsby starter default with below dependencies you will be able to see the error: 

 "dependencies": {
    "gatsby": "^4.24.7",
    "gatsby-plugin-image": "^2.24.0",
    "gatsby-plugin-manifest": "^4.24.0",
    "gatsby-plugin-prettier-build": "^0.4.4",
    "gatsby-plugin-sharp": "^4.24.0",
    "gatsby-source-filesystem": "^4.24.0",
    "gatsby-transformer-sharp": "^4.24.0",
    "prop-types": "^15.8.1",
    "react": "^18.1.0",
    "react-dom": "^18.1.0"
  },

**Comment by barbalex** [comment]
Having the same problem in a build using gatsby v5: https://github.com/barbalex/gs3, see production site (dev tools console): https://gabriel-software.ch

**Comment by tyhopp** [comment]
@MotaZor94 I wasn't able to reproduce this with `gatsby-starter-default` using Gatsby 4 or Gatsby 5 versions.

Can you link your reproduction so we can see if there's some difference we're not seeing? Preferably a public repo with a lockfile

**Comment by tyhopp** [comment]
Thanks for sharing the repro @MotaZor94, with that I was able to find what causes the issue.

The [gatsby-plugin-prettier-build](https://www.gatsbyjs.com/plugins/gatsby-plugin-prettier-build/) community plugin is used in the site (in the default starter it's not used) and removing it makes the tree mismatch error go away.

Diffing the HTML output with and without the plugin doesn't reveal any notable differences, only the build hashes (which is expected):

```diff
diff --git a/with-prettier-plugin.html b/without-prettier-plugin.html
index 85c76bc..41dd0bc 100644
--- a/with-prettier-plugin.html
+++ b/without-prettier-plugin.html
@@ -688,12 +688,12 @@
     </div>
     <script id="gatsby-script-loader">
       /*<![CDATA[*/ window.pagePath = "/";
-      window.___webpackCompilationHash = "30e56678bdd327735963"; /*]]>*/
+      window.___webpackCompilationHash = "2874447cd6ac0f48e1fc"; /*]]>*/
     </script>
     <script id="gatsby-chunk-mapping">
       /*<![CDATA[*/ window.___chunkMapping = {
         polyfill: ["/polyfill-c9fa82aa5b1f9c65f078.js"],
-        app: ["/app-34be17eaf1807346fe3b.js"],
+        app: ["/app-580458601d50252398d5.js"],
         "component---src-pages-404-js": [
           "/component---src-pages-404-js-3074e039138b006d2680.js",
         ],
@@ -715,7 +715,7 @@
       }; /*]]>*/
     </script>
     <script src="/polyfill-c9fa82aa5b1f9c65f078.js" nomodule=""></script>
-    <script src="/app-34be17eaf1807346fe3b.js" async=""></script>
+    <script src="/app-580458601d50252398d5.js" async=""></script>
     <script src="/framework-c57a9454c0e3bef16c3b.js" async=""></script>
     <script src="/webpack-runtime-f5450bf4aad168a01050.js" async=""></script>
   </body>
```

Given `gatsby-plugin-prettier-build` is a community plugin I recommend opening an issue in [the repo](https://github.com/jmsv/gatsby-plugin-prettier-build) and track it there.

**Comment by abouroubi** [comment]
Hello @tyhopp 
I'm commenting on this issue cause I'm having the same issue (gatsby 5.11), and I'm not using `gatsby-plugin-prettier-build`

Also, I can't find `gatsby-plugin-prettier-build` as a dependency on the repo shared @MotaZor94, so I'm not sure the issue came from that.

**Comment by Viktor19931** [comment]
@tyhopp I also dont use that lib and got same errro
