### ISSUE TITLE
[question] Gatsby bundle size

### ISSUE THREAD

**Issue by danielemesh** [gatsbyjs/gatsby#3698]
How much space doe's "gatsby code" takes from the final bundles?

Is it possible to assess?

**Comment by KyleAMathews** [comment]
Gatsby sites have a number of libraries it ships with e.g. react, react-dom, history, react-router, react-router-scroll, etc. Gatsby's runtime is fairly slim. I haven't measured it directly in a while but I'd guess it's ~5-10kb or so. You can use https://www.npmjs.com/package/source-map-explorer to look directly.

**Comment by danielemesh** [comment]
@KyleAMathews Should I run it against all the js files in the public directory?

**Comment by KyleAMathews** [comment]
Try looking at several. E.g. commons & app & some page components.
