### ISSUE TITLE
[docs] Typo in graphql-concepts fragments section

### ISSUE THREAD

**Issue by Nischal2015** [gatsbyjs/gatsby#36991]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

## Problem

`...GatsbyImageSharpFixed` is not used in [querying images](https://www.gatsbyjs.com/docs/conceptual/graphql-concepts/#images) in the above examples but is mentioned in the [Fragments](https://www.gatsbyjs.com/docs/conceptual/graphql-concepts/#advanced) section

### Steps to Resolve this Issue

1. The problem can be solved by editing that part of the docs.

**Comment by LekoArts** [comment]
Good catch. The paragraph that needs a change:

> Notice that in the above example for [querying images](https://www.gatsbyjs.com/docs/conceptual/graphql-concepts/#images), we used ...GatsbyImageSharpFixed, which is a GraphQL Fragment, a reusable set of fields for query composition. You can read more about them [here](https://graphql.org/learn/queries/#fragments).

Should be changed to something like this:

> Fragments let you construct sets of fields, and then include them in queries where you need to. You can learn more about them in the [GraphQL documentation](https://graphql.org/learn/queries/#fragments).

**Comment by Nischal2015** [comment]
Yeah, I think that is much better.
Can I make the changes and open PR?

**Comment by LekoArts** [comment]
Sure, go ahead :)
