### ISSUE TITLE
Gatsby v5 graphiql missing ENABLE_GATSBY_REFRESH_ENDPOINT feature.

### ISSUE THREAD

**Issue by ZeldOcarina** [gatsbyjs/gatsby#37002]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I've just upgraded to Gatsby v5 and graphiql seems not to have the **ENABLE_GATSBY_REFRESH_ENDPOINT** feature anywhere.

### Reproduction Link

https://githubbox.com/gatsbyjs/gatsby-starter-minimal

### Steps to Reproduce

1. Create a new v5 starter
2. Add to .env.development ENABLE_GATSBY_REFRESH_ENDPOINT
3. Navigate to localhost:8000/__graphql and notice the refresh button has disappeared.

### Expected Result

What is described here: https://www.gatsbyjs.com/docs/refreshing-content/

> Additionally, the sourced content can also be refreshed with the “Refresh Data” button in the [GraphiQL explorer](https://www.gatsbyjs.com/docs/how-to/querying-data/running-queries-with-graphiql). This button is only visible if ENABLE_GATSBY_REFRESH_ENDPOINT is set to true.

### Actual Result

The button is missing:

![image](https://user-images.githubusercontent.com/42982095/200858028-6b6dda2f-e879-4452-96c5-a7c47fa894b8.png)

### Environment

```shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.0.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 102.0.1
    Safari: 16.0
  npmGlobalPackages:
    gatsby-cli: 4.24.0
```

### Config Flags

No

**Comment by LekoArts** [comment]
I can't reproduce that. The icon in the middle shows up as expected:

![image](https://user-images.githubusercontent.com/16143594/200863458-c6dc1270-8536-479f-bc22-41d2d88a04ba.png)

**Comment by ZeldOcarina** [comment]
Hi @LekoArts I've changed the variable from `true`to `1`and it's now working properly.
The docs though are still saying that you should use `true`so that may be confusing.

Proposed Pull Request:
#37011

**Comment by ZeldOcarina** [comment]
Thank you guys! :)
