### ISSUE TITLE
[gatsby-source-contentful] Preview API not returning all data 

### ISSUE THREAD

**Issue by sunnymis** [gatsbyjs/gatsby#3701]
## Description

I am able to retrieve all of my content from Contentful when I use the Content Delivery API. However, when I use the Preview API my data is not being delivered. When I look into the `.cache` directory, some nested field references are missing from the page JSON. Not all of the pages are missing content and it seems to be random ones that are missing content.

Everything else is the same setup, only difference is I am using the Preview API. 

### Environment

Gatsby version: 1.9.165
gatsby-source-contentful version: 1.3.33
Node.js version: v8.9.3
Operating System: macOS Sierra 10.12.5

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
