### ISSUE TITLE
quick start flags must be preceded by --

### ISSUE THREAD

**Issue by SheetJSDev** [gatsbyjs/gatsby#37019]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

Current docs:

"""
Flags are not positional, so these commands are equivalent:

- `npm init gatsby -y -ts my-site-name`
- `npm init gatsby my-site-name -y -ts`

"""

Running against Node 18.12.1 + npm 8.19.2 on macOS, the questionnaire shows up even with the `-y` flag.

To force the `-y` to be passed along, `--` is needed.  For example:

```
npm init gatsby -- -y -ts my-site-name
```

### Steps to Resolve this Issue

Run the example commands, observe they do not appear to skip the questionnaire, and include examples that do behave as expected.

**Comment by tyhopp** [comment]
Hi @SheetJSDev, thanks! You are correct, this seems to have changed in later npm versions.

If you or anyone else would like to pick this up the docs update would be for this page/section -> https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/quick-start.md#use-flags

**Comment by shogohida** [comment]
Hi @tyhopp, can I take this issue?

**Comment by tyhopp** [comment]
> Hi @tyhopp, can I take this issue?

Absolutely! We have a [docs contribution guide](https://www.gatsbyjs.com/contributing/docs-contributions/) with some info you might find helpful if this is your first contribution to Gatsby

**Comment by shogohida** [comment]
@tyhopp 
I made a pull request so please have a look when you have time!

https://github.com/gatsbyjs/gatsby/pull/37041

**Comment by tyhopp** [comment]
Thank you @shogohida!
