### ISSUE TITLE
[gatsby-cli] Can't create project using 1.1.30

### ISSUE THREAD

**Issue by aoc** [gatsbyjs/gatsby#3702]
## Description

Can't create a basic project using `gatsby new gatsby-site` on 1.1.30 version. Previous version (1.1.29) works fine.

### Environment

Gatsby version: 1.1.30
Node.js version: 9.4.0
Operating System: macOS High Sierra 10.13.2
Git version: 2.16.1

### Actual result

```
❯ gatsby new gatsby-site
info Creating new site from git: shortcut
fatal: repository 'shortcut' does not exist
error Command failed: git clone shortcut gatsby-site --single-branch


  Error: Command failed: git clone shortcut gatsby-site --single-branch

  - index.js:236 Promise.all.then.arr
    [lib]/[gatsby-cli]/[execa]/index.js:236:11
```

### Expected behavior

Creates basic project without errors.

### Steps to reproduce

1\. Run `gatsby new gatsby-site` on an empty directory

**Comment by rluncasu** [comment]
Same thing here for ```gatsby new gatsby-site```. In addition, running gatsby new with a github url also results in a fatal error:
```
$ gatsby new tutorial-part-one https://github.com/gatsbyjs/gatsby-starter-hello-world
info Creating new site from git: https
fatal: repository 'https' does not exist
error Command failed: git clone https tutorial-part-one --single-branch
```

**Comment by KyleAMathews** [comment]
Hmmm sorry folks — will fix this real quick.

**Comment by aoc** [comment]
thanks @KyleAMathews I think you've already found the problem. But I tried to review the changes and made a comment here:

https://github.com/gatsbyjs/gatsby/commit/466aad7b91f6166bf6cac345f78a72b4360c1504#r27115011

**Comment by zachgibson** [comment]
I can successfully install tutorial-part-one but once I run `gatsby develop` I get errors such as:

```zsh
Failed to require /Users/zacharygibson/repos/tutorial-part-one/html.js
Module not found: Error: Cannot resolve module 'config' in /usr/local/lib/node_modules/gatsby/dist/isomorphic
```

**Comment by abhinavjonnada82** [comment]
All this can be solved........... By two simple steps actually three:
1.) Open GIT BASH
2.) Type the command: _gatsby new gatsby-site https://github.com/gatsbyjs/gatsby-starter-hello-world..._
3.) And from your TERMINAL type _gatsby develop_
