### ISSUE TITLE
Cannot run any of my gatsby files anymore

### ISSUE THREAD

**Issue by judepark** [gatsbyjs/gatsby#37031]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I updated npm and gatsby version and my previous files that used to work no longer runs, when I run gatsby develop it breaks. It seems like a plugin issue with graphql but I don't know what is breaking my code with various errors:

    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/promise.js:547:31

  - promise.js:604 Promise._settlePromise
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/promise.js:604:18

  - promise.js:641 Promise._settlePromiseCtx
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/promise.js:641:10

  - async.js:97 _drainQueueStep
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/async.js:97:12

  - async.js:86 _drainQueue
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/async.js:86:9

  - async.js:102 Async._drainQueues
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/async.js:102:5

  - async.js:15 Immediate.Async.drainQueues
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/async.js:15:14

  - timers:471 processImmediate
    node:internal/timers:471:21

 ERROR #11321  PLUGIN

"gatsby-transformer-sharp" threw an error while running the setFieldsOnGraphQLNodeType
lifecycle:

Class constructor GraphQLList cannot be invoked without 'new'

  TypeError: Class constructor GraphQLList cannot be invoked without 'new'

  - extend-node-type.js:405 fluidNodeType
    [jude-park-gatsby]/[gatsby-transformer-sharp]/extend-node-type.js:405:15

  - extend-node-type.js:455 Object.module.exports [as setFieldsOnGraphQLNodeType]
    [jude-park-gatsby]/[gatsby-transformer-sharp]/extend-node-type.js:455:21

  - api-runner-node.js:487 runAPI
    [jude-park-gatsby]/[gatsby]/src/utils/api-runner-node.js:487:22

  - api-runner-node.js:638 Promise.catch.decorateEvent.pluginName
    [jude-park-gatsby]/[gatsby]/src/utils/api-runner-node.js:638:13

  - debuggability.js:384 Promise._execute
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/debuggability.js:384:9

  - promise.js:518 Promise._resolveFromExecutor
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/promise.js:518:18

  - promise.js:103 new Promise
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/promise.js:103:10

  - api-runner-node.js:636
    [jude-park-gatsby]/[gatsby]/src/utils/api-runner-node.js:636:16

  - util.js:16 tryCatcher
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/util.js:16:23

  - reduce.js:166 Object.gotValue
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/reduce.js:166:18

  - reduce.js:155 Object.gotAccum
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/reduce.js:155:25

  - util.js:16 Object.tryCatcher
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/util.js:16:23

  - promise.js:547 Promise._settlePromiseFromHandler
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/promise.js:547:31

  - promise.js:604 Promise._settlePromise
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/promise.js:604:18

  - promise.js:641 Promise._settlePromiseCtx
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/promise.js:641:10

  - async.js:97 _drainQueueStep
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/async.js:97:12

  - async.js:86 _drainQueue
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/async.js:86:9

  - async.js:102 Async._drainQueues
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/async.js:102:5

  - async.js:15 Immediate.Async.drainQueues
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/async.js:15:14

  - timers:471 processImmediate
    node:internal/timers:471:21

                                                                                                
 ERROR #11321  PLUGIN

"gatsby-transformer-sharp" threw an error while running the setFieldsOnGraphQLNodeType
lifecycle:

Class constructor GraphQLList cannot be invoked without 'new'

  TypeError: Class constructor GraphQLList cannot be invoked without 'new'

  - extend-node-type.js:405 fluidNodeType
    [jude-park-gatsby]/[gatsby-transformer-sharp]/extend-node-type.js:405:15

  - extend-node-type.js:455 Object.module.exports [as setFieldsOnGraphQLNodeType]
    [jude-park-gatsby]/[gatsby-transformer-sharp]/extend-node-type.js:455:21

  - api-runner-node.js:487 runAPI
    [jude-park-gatsby]/[gatsby]/src/utils/api-runner-node.js:487:22

  - api-runner-node.js:638 Promise.catch.decorateEvent.pluginName
    [jude-park-gatsby]/[gatsby]/src/utils/api-runner-node.js:638:13

  - debuggability.js:384 Promise._execute
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/debuggability.js:384:9

  - promise.js:518 Promise._resolveFromExecutor
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/promise.js:518:18

  - promise.js:103 new Promise
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/promise.js:103:10

  - api-runner-node.js:636
    [jude-park-gatsby]/[gatsby]/src/utils/api-runner-node.js:636:16

  - util.js:16 tryCatcher
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/util.js:16:23

  - reduce.js:166 Object.gotValue
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/reduce.js:166:18

  - reduce.js:155 Object.gotAccum
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/reduce.js:155:25

  - util.js:16 Object.tryCatcher
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/util.js:16:23

  - promise.js:547 Promise._settlePromiseFromHandler
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/promise.js:547:31

  - promise.js:604 Promise._settlePromise
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/promise.js:604:18

  - promise.js:641 Promise._settlePromiseCtx
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/promise.js:641:10

  - async.js:97 _drainQueueStep
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/async.js:97:12

  - async.js:86 _drainQueue
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/async.js:86:9

  - async.js:102 Async._drainQueues
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/async.js:102:5

  - async.js:15 Immediate.Async.drainQueues
    [jude-park-gatsby]/[gatsby]/[bluebird]/js/release/async.js:15:14

  - timers:471 processImmediate
    node:internal/timers:471:21

success building schema - 0.677s
success createPages - 0.066s
success createPagesStatefully - 0.151s
info Total nodes: 232, SitePage nodes: 23 (use --verbose for breakdown)                         
success Checking for changed pages - 0.001s                                                     
success write out redirect data - 0.003s                                                        
warn The icon(src/assets/img/logo.png) you provided to 'gatsby-plugin-manifest' is not square.  
The icons we generate will be square and for the best results we recommend you provide a square 
icon.

success Build manifest and related icons - 0.140s
success onPostBootstrap - 0.147s
info bootstrap finished - 12.676s                                                               
success onPreExtractQueries - 0.006s
warn Deprecated syntax of sort and/or aggregation field arguments were found in your query (see
https://gatsby.dev/graphql-nested-sort-and-aggregate). Query was automatically converted to a
new syntax. You should update query in your code.

File: C:/Users/jude/jude-park-gatsby/src/pages/about.js

Current query:

query AboutQuery {
  allMarkdownRemark(sort: {fields: [frontmatter___date], order: DESC}) {
    edges {
      node {
        fields {
          slug
        }
        frontmatter {
          title
          notebrief
          color
          image {
            childImageSharp {
              fluid(maxWidth: 900) {
                ...GatsbyImageSharpFluid
              }
            }
          }
          thumb {
            childImageSharp {
              fluid(maxWidth: 900) {
                ...GatsbyImageSharpFluid
              }
            }
          }
          categories
        }
      }
    }
  }
}

Converted query:

query AboutQuery {
  allMarkdownRemark(sort: {frontmatter: {date: DESC}}) {
    edges {
      node {
        fields {
          slug
        }
        frontmatter {
          title
          notebrief
          color
          image {
            childImageSharp {
              fluid(maxWidth: 900) {
                ...GatsbyImageSharpFluid
              }
            }
          }
          thumb {
            childImageSharp {
              fluid(maxWidth: 900) {
                ...GatsbyImageSharpFluid
              }
            }
          }
          categories
        }
      }
    }
  }
}
warn Deprecated syntax of sort and/or aggregation field arguments were found in your query (see 
https://gatsby.dev/graphql-nested-sort-and-aggregate). Query was automatically converted to a   
new syntax. You should update query in your code.

File: C:/Users/jude/jude-park-gatsby/src/pages/index.js

Current query:

query ProjectQuery {
  allMarkdownRemark(sort: {fields: [frontmatter___date], order: DESC}) {
    edges {
      node {
        fields {
          slug
        }
        frontmatter {
          title
          notebrief
          color
          image {
            childImageSharp {
              fluid(maxWidth: 900) {
                ...GatsbyImageSharpFluid
              }
            }
          }
          thumb {
            childImageSharp {
              fluid(maxWidth: 900) {
                ...GatsbyImageSharpFluid
              }
            }
          }
          categories
        }
      }
    }
  }
}

Converted query:

query ProjectQuery {
  allMarkdownRemark(sort: {frontmatter: {date: DESC}}) {
    edges {
      node {
        fields {
          slug
        }
        frontmatter {
          title
          notebrief
          color
          image {
            childImageSharp {
              fluid(maxWidth: 900) {
                ...GatsbyImageSharpFluid
              }
            }
          }
          thumb {
            childImageSharp {
              fluid(maxWidth: 900) {
                ...GatsbyImageSharpFluid
              }
            }
          }
          categories
        }
      }
    }
  }
}
warn Deprecated syntax of sort and/or aggregation field arguments were found in your query (see
https://gatsby.dev/graphql-nested-sort-and-aggregate). Query was automatically converted to a
new syntax. You should update query in your code.

File: C:/Users/jude/jude-park-gatsby/src/pages/research.js

Current query:

query ResearchQuery {
  allMarkdownRemark(
    sort: {fields: [frontmatter___date], order: DESC}
    filter: {fileAbsolutePath: {regex: "/research/"}}
  ) {
    edges {
      node {
        fields {
          slug
        }
        frontmatter {
          title
          notebrief
          color
          image {
            childImageSharp {
              fluid(maxWidth: 900) {
                ...GatsbyImageSharpFluid
              }
            }
          }
          thumb {
            childImageSharp {
              fluid(maxWidth: 900) {
                ...GatsbyImageSharpFluid
              }
            }
          }
          categories
          date(formatString: "MMM D, YYYY")
        }
      }
    }
  }
}

Converted query:

query ResearchQuery {
  allMarkdownRemark(
    sort: {frontmatter: {date: DESC}}
    filter: {fileAbsolutePath: {regex: "/research/"}}
  ) {
    edges {
      node {
        fields {
          slug
        }
        frontmatter {
          title
          notebrief
          color
          image {
            childImageSharp {
              fluid(maxWidth: 900) {
                ...GatsbyImageSharpFluid
              }
            }
          }
          thumb {
            childImageSharp {
              fluid(maxWidth: 900) {
                ...GatsbyImageSharpFluid
              }
            }
          }
          categories
          date(formatString: "MMM D, YYYY")
        }
      }
    }
  }
}
warn Deprecated syntax of sort and/or aggregation field arguments were found in your query (see
https://gatsby.dev/graphql-nested-sort-and-aggregate). Query was automatically converted to a
new syntax. You should update query in your code.

File: C:/Users/jude/jude-park-gatsby/src/pages/work.js

Current query:

query WorkQuery {
  allMarkdownRemark(
    sort: {fields: [frontmatter___date], order: DESC}
    filter: {fileAbsolutePath: {regex: "/work/"}}
  ) {
    edges {
      node {
        fields {
          slug
        }
        frontmatter {
          title
          worksummary
          workheading
          color
          image {
            childImageSharp {
              fluid(maxWidth: 900) {
                ...GatsbyImageSharpFluid
              }
            }
          }
          thumb {
            childImageSharp {
              fluid(maxWidth: 900) {
                ...GatsbyImageSharpFluid
              }
            }
          }
          categories
          date(formatString: "YYYY")
        }
      }
    }
  }
}

Converted query:

query WorkQuery {
  allMarkdownRemark(
    sort: {frontmatter: {date: DESC}}
    filter: {fileAbsolutePath: {regex: "/work/"}}
  ) {
    edges {
      node {
        fields {
          slug
        }
        frontmatter {
          title
          worksummary
          workheading
          color
          image {
            childImageSharp {
              fluid(maxWidth: 900) {
                ...GatsbyImageSharpFluid
              }
            }
          }
          thumb {
            childImageSharp {
              fluid(maxWidth: 900) {
                ...GatsbyImageSharpFluid
              }
            }
          }
          categories
          date(formatString: "YYYY")
        }
      }
    }
  }
}

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ImageSharpFluid". Did you mean "ImageSharp" or "ImageSharpEdge"?

GraphQL request:2:37
1 |
2 |   fragment GatsbyImageSharpFluid on ImageSharpFluid {
  |                                     ^
3 |     base64

File: src\pages\about.js:648:37

                                                                                                

  GraphQLError: Unknown type "ImageSharpFluid". Did you mean "ImageSharp" or "ImageSharpEdge"?  

  - query-compiler.js:373 processDefinitions
    [jude-park-gatsby]/[gatsby]/src/query/query-compiler.js:373:20

  - query-compiler.js:178 processQueries
    [jude-park-gatsby]/[gatsby]/src/query/query-compiler.js:178:10

  - query-compiler.js:80 compile
    [jude-park-gatsby]/[gatsby]/src/query/query-compiler.js:80:19

  - query-watcher.ts:236 updateStateAndRunQueries
    [jude-park-gatsby]/[gatsby]/src/query/query-watcher.ts:236:40

  - extract-queries.ts:18 extractQueries
    [jude-park-gatsby]/[gatsby]/src/services/extract-queries.ts:18:3

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "fluid" on type "ImageSharp".

If you don't expect "fluid" to exist on the type "ImageSharp" it is most likely a typo. However,
 if you expect "fluid" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node/gatsby-config,     
please try a restart of your development server.
- You want to optionally use your field "fluid" and right now it is not used anywhere.

It is recommended to explicitly type your GraphQL schema if you want to use optional fields.    

File: src\pages\about.js:661:7

See our docs page for more info on this error: https://gatsby.dev/creating-type-definitions     

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "fluid" on type "ImageSharp".

If you don't expect "fluid" to exist on the type "ImageSharp" it is most likely a typo. However,
 if you expect "fluid" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node/gatsby-config,     
please try a restart of your development server.
- You want to optionally use your field "fluid" and right now it is not used anywhere.

It is recommended to explicitly type your GraphQL schema if you want to use optional fields.    

File: src\pages\about.js:668:7

See our docs page for more info on this error: https://gatsby.dev/creating-type-definitions     

                                                                                                
 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ImageSharpFluid". Did you mean "ImageSharp" or "ImageSharpEdge"?

GraphQL request:2:37
1 |
2 |   fragment GatsbyImageSharpFluid on ImageSharpFluid {
  |                                     ^
3 |     base64

File: src\pages\index.js:440:37

  GraphQLError: Unknown type "ImageSharpFluid". Did you mean "ImageSharp" or "ImageSharpEdge"?  

  - query-compiler.js:373 processDefinitions
    [jude-park-gatsby]/[gatsby]/src/query/query-compiler.js:373:20

  - query-compiler.js:178 processQueries
    [jude-park-gatsby]/[gatsby]/src/query/query-compiler.js:178:10

  - query-compiler.js:80 compile
    [jude-park-gatsby]/[gatsby]/src/query/query-compiler.js:80:19

  - query-watcher.ts:236 updateStateAndRunQueries
    [jude-park-gatsby]/[gatsby]/src/query/query-watcher.ts:236:40

  - extract-queries.ts:18 extractQueries
    [jude-park-gatsby]/[gatsby]/src/services/extract-queries.ts:18:3

                                                                                                
 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "fluid" on type "ImageSharp".

If you don't expect "fluid" to exist on the type "ImageSharp" it is most likely a typo. However,
 if you expect "fluid" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node/gatsby-config,     
please try a restart of your development server.
- You want to optionally use your field "fluid" and right now it is not used anywhere.

It is recommended to explicitly type your GraphQL schema if you want to use optional fields.    

File: src\pages\index.js:453:7

See our docs page for more info on this error: https://gatsby.dev/creating-type-definitions     

                                                                                                
 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "fluid" on type "ImageSharp".

If you don't expect "fluid" to exist on the type "ImageSharp" it is most likely a typo. However,
 if you expect "fluid" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node/gatsby-config,     
please try a restart of your development server.
- You want to optionally use your field "fluid" and right now it is not used anywhere.

It is recommended to explicitly type your GraphQL schema if you want to use optional fields.    

File: src\pages\index.js:460:7

See our docs page for more info on this error: https://gatsby.dev/creating-type-definitions     

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ImageSharpFluid". Did you mean "ImageSharp" or "ImageSharpEdge"?

GraphQL request:2:37
1 |
2 |   fragment GatsbyImageSharpFluid on ImageSharpFluid {
  |                                     ^
3 |     base64

File: src\pages\research.js:321:37

  GraphQLError: Unknown type "ImageSharpFluid". Did you mean "ImageSharp" or "ImageSharpEdge"?  

  - query-compiler.js:373 processDefinitions
    [jude-park-gatsby]/[gatsby]/src/query/query-compiler.js:373:20

  - query-compiler.js:178 processQueries
    [jude-park-gatsby]/[gatsby]/src/query/query-compiler.js:178:10

  - query-compiler.js:80 compile
    [jude-park-gatsby]/[gatsby]/src/query/query-compiler.js:80:19

  - query-watcher.ts:236 updateStateAndRunQueries
    [jude-park-gatsby]/[gatsby]/src/query/query-watcher.ts:236:40

  - extract-queries.ts:18 extractQueries
    [jude-park-gatsby]/[gatsby]/src/services/extract-queries.ts:18:3

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "fluid" on type "ImageSharp".

If you don't expect "fluid" to exist on the type "ImageSharp" it is most likely a typo. However,
 if you expect "fluid" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node/gatsby-config,     
please try a restart of your development server.
- You want to optionally use your field "fluid" and right now it is not used anywhere.

It is recommended to explicitly type your GraphQL schema if you want to use optional fields.    

File: src\pages\research.js:337:7

See our docs page for more info on this error: https://gatsby.dev/creating-type-definitions     

                                                                                                
 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "fluid" on type "ImageSharp".

If you don't expect "fluid" to exist on the type "ImageSharp" it is most likely a typo. However,
 if you expect "fluid" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node/gatsby-config,     
please try a restart of your development server.
- You want to optionally use your field "fluid" and right now it is not used anywhere.

It is recommended to explicitly type your GraphQL schema if you want to use optional fields.    

File: src\pages\research.js:344:7

See our docs page for more info on this error: https://gatsby.dev/creating-type-definitions     

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ImageSharpFluid". Did you mean "ImageSharp" or "ImageSharpEdge"?

GraphQL request:2:37
1 |
2 |   fragment GatsbyImageSharpFluid on ImageSharpFluid {
  |                                     ^
3 |     base64

File: src\pages\work.js:293:37

  GraphQLError: Unknown type "ImageSharpFluid". Did you mean "ImageSharp" or "ImageSharpEdge"?  

  - query-compiler.js:373 processDefinitions
    [jude-park-gatsby]/[gatsby]/src/query/query-compiler.js:373:20

  - query-compiler.js:178 processQueries
    [jude-park-gatsby]/[gatsby]/src/query/query-compiler.js:178:10

  - query-compiler.js:80 compile
    [jude-park-gatsby]/[gatsby]/src/query/query-compiler.js:80:19

  - query-watcher.ts:236 updateStateAndRunQueries
    [jude-park-gatsby]/[gatsby]/src/query/query-watcher.ts:236:40

  - extract-queries.ts:18 extractQueries
    [jude-park-gatsby]/[gatsby]/src/services/extract-queries.ts:18:3

                                                                                                
 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "fluid" on type "ImageSharp".

If you don't expect "fluid" to exist on the type "ImageSharp" it is most likely a typo. However,
 if you expect "fluid" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node/gatsby-config,     
please try a restart of your development server.
- You want to optionally use your field "fluid" and right now it is not used anywhere.

It is recommended to explicitly type your GraphQL schema if you want to use optional fields.    

File: src\pages\work.js:310:7

See our docs page for more info on this error: https://gatsby.dev/creating-type-definitions     

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "fluid" on type "ImageSharp".

If you don't expect "fluid" to exist on the type "ImageSharp" it is most likely a typo. However,
 if you expect "fluid" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node/gatsby-config,     
please try a restart of your development server.
- You want to optionally use your field "fluid" and right now it is not used anywhere.

It is recommended to explicitly type your GraphQL schema if you want to use optional fields.    

File: src\pages\work.js:317:7

See our docs page for more info on this error: https://gatsby.dev/creating-type-definitions     

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ImageSharpFluid". Did you mean "ImageSharp" or "ImageSharpEdge"?

GraphQL request:2:37
1 |
2 |   fragment GatsbyImageSharpFluid on ImageSharpFluid {
  |                                     ^
3 |     base64

File: src\templates\research.js:470:37

                                                                                                

  GraphQLError: Unknown type "ImageSharpFluid". Did you mean "ImageSharp" or "ImageSharpEdge"?  

  - query-compiler.js:373 processDefinitions
    [jude-park-gatsby]/[gatsby]/src/query/query-compiler.js:373:20

  - query-compiler.js:178 processQueries
    [jude-park-gatsby]/[gatsby]/src/query/query-compiler.js:178:10

  - query-compiler.js:80 compile
    [jude-park-gatsby]/[gatsby]/src/query/query-compiler.js:80:19

  - query-watcher.ts:236 updateStateAndRunQueries
    [jude-park-gatsby]/[gatsby]/src/query/query-watcher.ts:236:40

  - extract-queries.ts:18 extractQueries
    [jude-park-gatsby]/[gatsby]/src/services/extract-queries.ts:18:3

                                                                                                
 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "fluid" on type "ImageSharp".

If you don't expect "fluid" to exist on the type "ImageSharp" it is most likely a typo. However,
 if you expect "fluid" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node/gatsby-config,     
please try a restart of your development server.
- You want to optionally use your field "fluid" and right now it is not used anywhere.

It is recommended to explicitly type your GraphQL schema if you want to use optional fields.    

File: src\templates\research.js:487:8

See our docs page for more info on this error: https://gatsby.dev/creating-type-definitions     

                                                                                                
 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ImageSharpFluid". Did you mean "ImageSharp" or "ImageSharpEdge"?

GraphQL request:2:37
1 |
2 |   fragment GatsbyImageSharpFluid on ImageSharpFluid {
  |                                     ^
3 |     base64

File: src\templates\work.js:499:37

                                                                                                

  GraphQLError: Unknown type "ImageSharpFluid". Did you mean "ImageSharp" or "ImageSharpEdge"?  

  - query-compiler.js:373 processDefinitions
    [jude-park-gatsby]/[gatsby]/src/query/query-compiler.js:373:20

  - query-compiler.js:178 processQueries
    [jude-park-gatsby]/[gatsby]/src/query/query-compiler.js:178:10

  - query-compiler.js:80 compile
    [jude-park-gatsby]/[gatsby]/src/query/query-compiler.js:80:19

  - query-watcher.ts:236 updateStateAndRunQueries
    [jude-park-gatsby]/[gatsby]/src/query/query-watcher.ts:236:40

  - extract-queries.ts:18 extractQueries
    [jude-park-gatsby]/[gatsby]/src/services/extract-queries.ts:18:3

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "fluid" on type "ImageSharp".

If you don't expect "fluid" to exist on the type "ImageSharp" it is most likely a typo. However,
 if you expect "fluid" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node/gatsby-config,     
please try a restart of your development server.
- You want to optionally use your field "fluid" and right now it is not used anywhere.

It is recommended to explicitly type your GraphQL schema if you want to use optional fields.    

File: src\templates\work.js:520:8

See our docs page for more info on this error: https://gatsby.dev/creating-type-definitions     

failed extract queries from components - 1.175s
warn The GraphQL query in the non-page component                                                
"C:/Users/jude/jude-park-gatsby/src/disabled/photography.js" will not be run.
Exported queries are only executed for page components. It's possible you're trying to create   
pages in your gatsby-node.js and that's failing for some reason.

If the failing component is a regular component and not intended to be a page component, you    
generally want to use "useStaticQuery"
(https://www.gatsbyjs.com/docs/how-to/querying-data/use-static-query/) instead of exporting a   
page query.

If you're more experienced with GraphQL, you can also export GraphQL fragments from components  
and compose the fragments in the Page component query and pass data down into the child
component (https://www.gatsbyjs.com/docs/reference/graphql-data-layer/using-graphql-fragments/) 
success write out requires - 0.049s

 ERROR 

Module not found: Error: Can't resolve 'gatsby-core-utils/create-content-digest' in
'C:\Users\jude\jude-park-gatsby\.cache\slice'

  ModuleNotFoundError: Module not found: Error: Can't resolve 'gatsby-core-utils/create-content-
  digest' in 'C:\Users\jude\jude-park-gatsby\.cache\slice'

  - Compilation.js:2016
    [jude-park-gatsby]/[webpack]/lib/Compilation.js:2016:28

  - NormalModuleFactory.js:798
    [jude-park-gatsby]/[webpack]/lib/NormalModuleFactory.js:798:13

  - NormalModuleFactory.js:270
    [jude-park-gatsby]/[webpack]/lib/NormalModuleFactory.js:270:22

  - NormalModuleFactory.js:434
    [jude-park-gatsby]/[webpack]/lib/NormalModuleFactory.js:434:22

  - NormalModuleFactory.js:116
    [jude-park-gatsby]/[webpack]/lib/NormalModuleFactory.js:116:11

  - NormalModuleFactory.js:670
    [jude-park-gatsby]/[webpack]/lib/NormalModuleFactory.js:670:25

  - NormalModuleFactory.js:855
    [jude-park-gatsby]/[webpack]/lib/NormalModuleFactory.js:855:8

  - NormalModuleFactory.js:975
    [jude-park-gatsby]/[webpack]/lib/NormalModuleFactory.js:975:5

  - async.js:6883
    [jude-park-gatsby]/[neo-async]/async.js:6883:13

  - NormalModuleFactory.js:958
    [jude-park-gatsby]/[webpack]/lib/NormalModuleFactory.js:958:45

  - Resolver.js:312 finishWithoutResolve
    [jude-park-gatsby]/[enhanced-resolve]/lib/Resolver.js:312:11

  - Resolver.js:386
    [jude-park-gatsby]/[enhanced-resolve]/lib/Resolver.js:386:15

  - Resolver.js:435
    [jude-park-gatsby]/[enhanced-resolve]/lib/Resolver.js:435:5

  - Resolver.js:435
    [jude-park-gatsby]/[enhanced-resolve]/lib/Resolver.js:435:5

  - DescriptionFilePlugin.js:87
    [jude-park-gatsby]/[enhanced-resolve]/lib/DescriptionFilePlugin.js:87:43

  - Resolver.js:435
    [jude-park-gatsby]/[enhanced-resolve]/lib/Resolver.js:435:5

  - Resolver.js:435
    [jude-park-gatsby]/[enhanced-resolve]/lib/Resolver.js:435:5

  - Resolver.js:435
    [jude-park-gatsby]/[enhanced-resolve]/lib/Resolver.js:435:5

  - Resolver.js:435
    [jude-park-gatsby]/[enhanced-resolve]/lib/Resolver.js:435:5

  - DescriptionFilePlugin.js:87
    [jude-park-gatsby]/[enhanced-resolve]/lib/DescriptionFilePlugin.js:87:43

not finished Building development bundle - 3.223s

### Reproduction Link

https://github.com/judepark/jude-park-gatsby

### Steps to Reproduce

1. run "gatsby develop"

### Expected Result

the environment should run as normal as it always had

### Actual Result

cannot run environment due to errors

### Environment

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.3
  Browsers:
    Chrome: 107.0.5304.107
    Edge: Spartan (44.22000.120.0), Chromium (107.0.1418.42)
  npmPackages:
    gatsby: ^5.0.1 => 5.0.1
    gatsby-image: ^2.2.17 => 2.2.17
    gatsby-plugin-google-analytics: ^2.1.14 => 2.1.14
    gatsby-plugin-layout: ^1.1.6 => 1.1.6
    gatsby-plugin-manifest: ^2.2.13 => 2.2.13
    gatsby-plugin-react-helmet: ^3.1.6 => 3.1.6
    gatsby-plugin-sharp: ^2.2.19 => 2.2.19
    gatsby-plugin-styled-components: ^3.1.4 => 3.1.4
    gatsby-remark-embed-video: ^3.0.10 => 3.0.10
    gatsby-remark-images: ^3.1.20 => 3.1.20
    gatsby-remark-images-medium-zoom: ^1.2.1 => 1.2.1
    gatsby-remark-responsive-iframe: ^2.4.5 => 2.4.5
    gatsby-source-filesystem: ^2.1.21 => 2.1.21
    gatsby-transformer-remark: ^2.6.21 => 2.6.21
    gatsby-transformer-sharp: ^2.2.13 => 2.2.13
  npmGlobalPackages:
    gatsby-cli: 5.0.0
```

**Comment by tyhopp** [comment]
Hi @judepark, please follow the [Gatsby 4 to 5 migration guide](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/) if you haven't already.

If you still encounter a specific issue after following the migration guide, feel free to ask in the [Gatsby 5 umbrella discussion](https://github.com/gatsbyjs/gatsby/discussions/36609) or open a new issue with a [minimal reproduction](https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/).
