### ISSUE TITLE
[gatsby-source-shopify]: `createNodeField` not adding to fields node in v7

### ISSUE THREAD

**Issue by jamesrice96** [gatsbyjs/gatsby#37037]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I'm working on a project which requires upgrading from v6 to v7 of the gatsby-source-shopify plugin.

In the current set up we query some additional information and add this to the `ShopifyProductVariant` node.

We do this in the `gatsby-node` file using the [gatsby action](https://www.gatsbyjs.com/docs/reference/config-files/actions/#createNodeField) `createNodeField`.

A simple example I have used for testing is - 
```
exports.onCreateNode = ({ node, actions, getNode }) => {
const { createNodeField } = actions
  if (node.internal.type === "ShopifyProductVariant") {
    createNodeField({
      node,
      name: "Hello",
      value: "World!",
    })
  }
}
```

In the latest version of v6 (6.10.2) I get the node attached to the field as expected - 

![image](https://user-images.githubusercontent.com/19837752/201685105-7d85cd15-0a86-426d-8b96-af7600fdc898.png)

As soon as I upgrade to v7 this no longer works, any thoughts/help on this is greatly appreciated 🙏

### Reproduction Link

n/a

### Steps to Reproduce

1. configure a project using v7 of the gatsby-source-shopify 
2. use the example code used in the description in the gatsby-node file.
...

### Expected Result

You should see a `fields` node attached to `ShopifyProductVariant` with this containing the information from the `createNodeField` function.

### Actual Result

No fields node is created.

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
  Binaries:
    Node: 16.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.42)
  npmPackages:
    gatsby: ^4.0.2 => 4.6.1 
    gatsby-background-image: ^1.6.0 => 1.6.0 
    gatsby-image: ^3.11.0 => 3.11.0 
    gatsby-plugin-emotion: ^7.8.0 => 7.8.0 
    gatsby-plugin-gatsby-cloud: ^4.0.0 => 4.6.0 
    gatsby-plugin-google-analytics: ^4.0.0 => 4.6.0 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-google-tagmanager: ^4.7.0 => 4.7.0 
    gatsby-plugin-image: ^2.0.0 => 2.6.0 
    gatsby-plugin-layout: ^3.6.0 => 3.6.0 
    gatsby-plugin-react-helmet: ^5.0.0 => 5.6.0 
    gatsby-plugin-robots-txt: ^1.7.0 => 1.7.0 
    gatsby-plugin-sharp: ^4.0.0 => 4.6.0 
    gatsby-plugin-sitemap: ^5.9.0 => 5.9.0 
    gatsby-source-filesystem: ^4.0.0 => 4.24.0 
    gatsby-source-shopify: ^6.10.2 => 6.10.2 
    gatsby-transformer-sharp: ^4.0.0 => 4.6.0 
  npmGlobalPackages:
    gatsby: 5.0.1
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment]
In the new version of the Shopify plugin it explicitly defines the types with `@dontInfer`: https://github.com/gatsbyjs/gatsby/blob/f595257c51fed9ab18dc558e4b85188853eb0e15/packages/gatsby-source-shopify/src/type-builders/product-variant-type.ts#L3

So it won't pick up the addition automatically.

You can add this to your `gatsby-node`:

```js
exports.createSchemaCustomization = ({ actions }) => {
  const { createTypes } = actions
  const typeDefs = `
    type ShopifyProductVariant implements Node {
      fields: ShopifyProductVariantFields
    }
    type ShopifyProductVariantFields {
      Hello: ShopifyProductVariantFieldsHello
    }
    type ShopifyProductVariantFieldsHello {
      example: String
    }
  `
  createTypes(typeDefs)
}
```

This way you explicitly define your newly added field on the `ShopifyProductVariant` type.

It's all explained here: https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization/
