### ISSUE TITLE
[gatsby-cli] npm warning deprecated graceful-fs

### ISSUE THREAD

**Issue by rdela** [gatsbyjs/gatsby#3705]
So working, I see:

```sh
Update available 1.1.29 → 1.1.31
Run npm i -g gatsby-cli to update  
```

…during update to gatsby-cli@1.1.31

```
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
```

[/packages/gatsby-cli/package.json](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/package.json#L20)

…looks like that is [fs-extra](https://www.npmjs.com/package/fs-extra) depending on [graceful-fs](https://www.npmjs.com/package/graceful-fs)

[isaacs/node-graceful-fs](https://github.com/isaacs/node-graceful-fs):

> v4
> Do not monkey-patch the fs module. This module may now be used as a drop-in dep, and users can opt into monkey-patching the fs builtin if their app requires it.

Node.js version: 9.4
Operating System: MacOS 10.13.3

**Comment by rdela** [comment]
Can we bump that to `5.0.0`? Or are we holding back for a we reason?


https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md#500--2017-12-11

> 5.0.0 / 2017-12-11
> Significant refactor of `copy()` & `copySync()`, including breaking changes. No changes to other functions in this release.

**Comment by rdela** [comment]
https://github.com/gatsbyjs/gatsby/blob/157f1c806bc5962c20c9c731048ef0fa2d8ac28e/packages/gatsby-cli/package.json#L20

**Comment by KyleAMathews** [comment]
Nobody has tried upgrading afaik. Would love it if could do the upgrade and take care of any breaking changes! Perhaps it might take care of all the weird copy issues on Windows

**Comment by rdela** [comment]
Great will give it a try and post here if I get stuck or lost!

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
