### ISSUE TITLE
Tutorial Part 6 Unhandled Runtime Error

### ISSUE THREAD

**Issue by jeustan** [gatsbyjs/gatsby#37056]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

https://github.com/jeustan/first-gatsby-site

I'm following along with the tutorial. Instead of creating pages from data using the {mdx.frontmatter__slug.js I get Error in function useStaticQuery in ./.cache/static-query.js:83.

I've checked my code, I've followed the tutorial closely and haven't found my error.

Edit: this does not occur on the live version of the site - https://firstgatsbysitemain65907.gatsbyjs.io/blog/my-first-post/

### Reproduction Link

https://github.com/jeustan/first-gatsby-site

### Steps to Reproduce

1. Load the repository
2. Launch development
3. Go to /blog/my-first-post
...

### Expected Result

Load pages from data

### Actual Result

Unhandled runtime error.

### Environment

```shell
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 19.1.0 - /usr/local/bin/node
    npm: 8.19.3 - /usr/local/bin/npm
  Languages:
    Python: 3.7.3 - /Users/justinreed/.pyenv/shims/python
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 61.0.2
    Safari: 14.1.2
  npmPackages:
    gatsby: ^5.0.0 => 5.0.0
    gatsby-plugin-image: ^3.0.0 => 3.0.0
    gatsby-plugin-mdx: ^5.0.0 => 5.0.0
    gatsby-plugin-sharp: ^5.0.0 => 5.0.0
    gatsby-source-filesystem: ^5.0.0 => 5.0.0
  npmGlobalPackages:
    gatsby-cli: 5.0.0
```

**Comment by ShaneMcX** [comment]
This was closed without comment, yet still repros.

**Comment by jeustan** [comment]
Yeah, it still repros for me and others in the discussion.

**Comment by jeustan** [comment]
https://github.com/gatsbyjs/gatsby/issues/37060
