### ISSUE TITLE
Issue building project using firebase - firestore

### ISSUE THREAD

**Issue by cnolimit** [gatsbyjs/gatsby#3706]
## Description

I'm having an issue using firestore in my project. Each time I try to build the project it produces the an error stating that it can't find the `aws-sdk` module. Then after installing the module it produces a webpack error.

I've been trying to work this out for a while, it works in development, but just can't seem to figure out why its happening during builds.

### Environment

Gatsby version: 1.9.158
Node.js version: 8.4.0
Operating System: macOs High Sierra (v10.13.2)

### File contents (if changed):

`package.json`: 
```json
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "eslint": "^4.16.0",
    "firebase": "^4.9.0",
    "gatsby": "^1.9.158",
    "gatsby-link": "^1.6.34",
    "gatsby-plugin-react-helmet": "^2.0.3",
    "react-helmet": "^5.2.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "main": "n/a",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --trailing-comma es5 --no-semi --single-quote --write \"src/**/*.js\"",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "prettier": "^1.10.2"
  }
}

```

### Actual result

What happened.

Running the build script produced the errors below.

#### Error before installing `aws-sdk` module
```java

error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND


  Error: Module not found: Error: Cannot resolve module 'aws-sdk' in /Users/phillip/Desktop/gatsby-firebase/node_modules/node-pr  e-gyp/lib
  resolve module aws-sdk in /Users/phillip/Desktop/gatsby-firebase/node_modules/node-pre-gyp/lib
    looking for modules in /Users/phillip/Desktop/gatsby-firebase/node_modules
      /Users/phillip/Desktop/gatsby-firebase/node_modules/aws-sdk doesn't exist (module as directory)
      resolve 'file' aws-sdk in /Users/phillip/Desktop/gatsby-firebase/node_modules
        resolve file
          /Users/phillip/Desktop/gatsby-firebase/node_modules/aws-sdk doesn't exist
          /Users/phillip/Desktop/gatsby-firebase/node_modules/aws-sdk.js doesn't exist
          /Users/phillip/Desktop/gatsby-firebase/node_modules/aws-sdk.jsx doesn't exist
    looking for modules in /Users/phillip/Desktop/gatsby-firebase/node_modules
      /Users/phillip/Desktop/gatsby-firebase/node_modules/aws-sdk doesn't exist (module as directory)
      resolve 'file' aws-sdk in /Users/phillip/Desktop/gatsby-firebase/node_modules
```

#### Error after installing the `aws-sdk`
```javascript
error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  15 | exports.find = function(package_json_path,opts) {
  16 |    if (!existsSync(package_json_path)) {
> 17 |         throw new Error("package.json does not exist at " + package_json_path);
     | ^
  18 |    }
  19 |    var package_json = require(package_json_path);
  20 |    versioning.validate_config(package_json);


  WebpackError: package.json does not exist at /package.json

  - pre-binding.js:17 Object.exports.find
    ~/node-pre-gyp/lib/pre-binding.js:17:1

  - grpc_extension.js:29 Object.<anonymous>
    ~/grpc/src/grpc_extension.js:29:1


  - client.js:38 Object.<anonymous>
    ~/grpc/src/client.js:38:1

  - index.js:30 Object.<anonymous>
    ~/grpc/index.js:30:1


  - grpc_connection.js:18 Object.<anonymous>
    ~/@firebase/firestore/dist/cjs/src/platform_node/grpc_connection.js:18:1

```

### Expected behavior

What should happen?

The project should successfully build with no issues.

### Steps to reproduce

I've stripped my project and created a repo that generates the error [here](https://github.com/cnolimit/gatsby-firebase)

**Comment by calcsam** [comment]
Seems to be an instance of this bug in grpc: https://github.com/grpc/grpc/issues/13049

**Comment by cnolimit** [comment]
@calcsam This issue seems to been more closely related to #3686 which I missed initially when searching through issues, but seemed to be closed with no real resolution. Would be good if we could re-open the original issue and work out why the build fails when using `firestore`

**Comment by KyleAMathews** [comment]
It could just be that we're still on webpack v1 until Gatsby v2 is released.

**Comment by shaunpersad** [comment]
What's interesting to me is that I started a project a few months ago that uses firebase and it works just fine. I started a new project two weeks ago and just added firebase yesterday and I'm getting this `aws-sdk` error. So I just started a brand new test project, added firebase and imported it, and it builds fine!

So I'm in the process of checking off differences between the project that doesn't build with the two that do.

**Comment by shaunpersad** [comment]
Found the issue. Gatsby 1.x is only compatible with Firebase < 4.x. The latest version of Firebase (5.x) will not install properly. See here: https://github.com/shaunpersad/gatsby-and-firebase

**Comment by MarcCoet** [comment]
Hey, in my experience it is only firestore that is causing issues (but you may be right with the 'version thing' too. I did not test everything)
Until I decide to get on board with Gatsby v2 I managed to overcome all firebase linked issues by only importing it in `gatsby-browser' and passing it through context. [This article series](https://medium.com/@UnicornAgency/jamstack-pwa-lets-build-a-polling-app-with-gatsby-js-firebase-and-styled-components-pt-1-78a03a633092) inspired me to do so. I personally use the new context API but the idea remains.
Hope this can be helpful.

**Comment by AAverin** [comment]
@shaunpersad Did you also find any solution for this? It would be great to use latest firebase without migrating to the new GatsbyJS
