### ISSUE TITLE
Gatsby v5 not support   npx process-top ./node_modules/.bin/gatsby build

### ISSUE THREAD

**Issue by NeilShang** [gatsbyjs/gatsby#37086]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I have an empty gatsby v5 project.after finish gatsby init.I want check the memory for Gatsby build.and I run
npx process-top ./node_modules/.bin/gatsby build
but after 10s  I got error
node(87804,0x7ff8444c74c0) malloc: Heap corruption detected, free list is damaged at 0x600002c56ac0
*** Incorrect guard value: 51984391841496
node(87804,0x7ff8444c74c0) malloc: *** set a breakpoint in malloc_error_break to debug

only v5 have this error.please check

### Reproduction Link

do not have

### Steps to Reproduce

1.init a empty gatsby site with v5
2.run     ` npx process-top ./node_modules/.bin/gatsby build`

### Expected Result

build success

### Actual Result

get error 
*** Incorrect guard value: 51984391841496
node(87804,0x7ff8444c74c0) malloc: Heap corruption detected, free list is damaged at 0x600002c56ac0
*** Incorrect guard value: 51984391841496
node(87804,0x7ff8444c74c0) malloc: *** set a breakpoint in malloc_error_break to debug

### Environment

```shell
System:
    OS: macOS 13.0
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Safari: 16.1
  npmPackages:
    gatsby: ^5.0.0 => 5.0.0 
    gatsby-plugin-image: ^3.1.0 => 3.1.0 
    gatsby-plugin-sharp: ^5.1.0 => 5.1.0 
    gatsby-source-contentful: ^8.1.0 => 8.1.0 
    gatsby-transformer-sharp: ^5.1.0 => 5.1.0
```

**Comment by LekoArts** [comment]
Please open an issue on the process-top repository.

**Comment by fostimus** [comment]
I don't think this is a process-top issue. I just upgrade to gatsby v5 and Node 18, and getting the same error during `gatsby build`

**Comment by fostimus** [comment]
Consistently happens at `[========                    ]   18.966 s 188/628 30% Running gatsby-plugin-sharp.IMAGE_PROCESSING jobs`
