### ISSUE TITLE
Add others‘ plugins?

### ISSUE THREAD

**Issue by LeKoArts** [gatsbyjs/gatsby#3708]
Hi,

I stumbled across two cool gatsby plugins which are sadly not on the homepage:
https://github.com/vacas5/gatsby-source-unsplash
https://github.com/Creatiwity/gatsby-plugin-favicon

Should always and only the creator submit a PR to add them to the list or can everyone do that?

**Comment by julien1619** [comment]
Hi,

I'm the creator of the second one, and yeah, I completely forgot to do a PR to add it to the list :)
I will do it right now. Thanks!

**Comment by fk** [comment]
Hmm, good question. While I don't see a big problem in other people than the plugin creator adding community plugins to the list, those adding should probably make sure that the plugin works with the latest version of Gatsby, is intended for a public release, is published to npm …

Maybe opening an issue here in which we ping the plugin authors – as long as the plugin source is hosted on GitHub, that should be easy: @vacas5 @Creatiwity What do you think? Want to add your plugins to https://www.gatsbyjs.org/docs/plugins/#community-plugins? Is there a reason you didn't?

**Comment by fk** [comment]
Haha, hey @julien1619! Looking forward to your PR! 🤗

**Comment by LeKoArts** [comment]
> those adding should probably make sure that the plugin works with the latest version of Gatsby, is intended for a public release, is published to npm

Yes, I also think that's the necessary steps.
But mentioning the respective authors is also a valid option 😆

**Comment by LeKoArts** [comment]
@fk @KyleAMathews On the same note:
Aren't there also official plugins missing in the list? I had to open up the examples/using-emotion folder to see that  ``gatsby-plugin-emotion`` exists as it's missing on the website.

**Comment by fk** [comment]
Yep, just added one today: #3712 
Would be cool if you could add a PR for `gatsby-plugin-emotion` (and any other missing ones ;-))!

**Comment by LeKoArts** [comment]
Ok, will create a PR now 👍

**Comment by fk** [comment]
Thank you @LeKoArts! 🤗

**Comment by calcsam** [comment]
Closing this, thanks @LeKoArts ! :)

**Comment by vacas5** [comment]
late to the party here, but I'll open a PR for mine as well

**Comment by LeKoArts** [comment]
Actually I found via the search plenty more source plugins. Will mention them later today.

**Comment by LeKoArts** [comment]
Sooo, want to mention some more plugin/source creators. Would be cool if you add your plugin to the list!

Source plugins:
@ryanflorence @angeloashmore @pierreburgy @jondubin @danoc @Necmttn @mpartipilo @taessina @G100g @codingdefined @frikille 

Plugins:
@designbyadrian @mikefowler

**Comment by mpartipilo** [comment]
@LeKoArts I am not 100% happy with my source plugin yet, but perhaps more visibility and feedback is exactly what it needs. I'll work on a PR over the weekend.

**Comment by mikefowler** [comment]
@LeKoArts thanks for the tag! Similarly, I'm not quite ready to call https://github.com/mikefowler/gatsby-plugin-collections ready for production. Been traveling the past month, but hoping to make a 1.x release in March :)

**Comment by G100g** [comment]
@LeKoArts PR opened. Thank you!
