### ISSUE TITLE
graphql: gatsbyPath doesn't materialize nodes

### ISSUE THREAD

**Issue by nrandell** [gatsbyjs/gatsby#37103]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

In a query, using gatsby patch does not correctly expand the paths.

`gatsbyPath(filePath: "/{Article.articleType__slug}/{Article.slug}")`

I would expect to see a path such as `/type1/article1/` but instead I get `{Article.articleType__slug}/article1/`

### Reproduction Link

https://github.com/nrandell/gatsby-path-nested-bug

### Steps to Reproduce

yarn install
yarn develop
http://localhost:8000/type1/article1

### Expected Result

On the page I would expect to see

```
Got path as: /type1/article1/

Expect to see: /type1/article1/
```

### Actual Result

On the page I would expect to see

```
Got path as: /{Article.articleType__slug}/article1/

Expect to see: /type1/article1/
```

### Environment

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 PRO 4750G with Radeon Graphics
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.10.4
  Browsers:
    Edge: Spartan (44.22621.819.0), Chromium (107.0.1418.56), ChromiumDev (User home = 'C:\Users\nickr\AppData\Local\IISExpress'
IIS USER HOME configured)
  npmPackages:
    gatsby: ^5.0.0 => 5.1.0
```

**Comment by LekoArts** [comment]
Thanks for the issue, I can reproduce that. Will look into it!

**Comment by LekoArts** [comment]
This is actually the same issue: https://github.com/gatsbyjs/gatsby/issues/30429
I closed the old one as this here has an easier reproduction

**Comment by LekoArts** [comment]
Have something working :)

![Text saying: Got path as: /type1/article1/ Expect to see: /type1/article1/](https://user-images.githubusercontent.com/16143594/204289202-282eaffc-2a58-4d8a-b1a4-8a4aa6b313c4.png)
