### ISSUE TITLE
Gatsby local fonts failing using gatsby-ssr.js

### ISSUE THREAD

**Issue by avi312singh** [gatsbyjs/gatsby#37110]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi I am looking to preload custom fonts after each page is built into the head and have followed [this guide](https://www.gatsbyjs.com/blog/how-to-add-custom-fonts-to-gatsby/) 

I have a [pull request](https://github.com/avi312singh/meghdaminy-bespoke/pull/2) open which proves that this simple [gatsby-ssr.js](https://github.com/avi312singh/meghdaminy-bespoke/blob/200bd231cbf0662af9d2153a28d257d923b06b65/gatsby-ssr.js) file is the culprit for the dev build failing, using gatsby cloud as CI i have placed the `gatsby-ssr.js` in the project to fail the build and then in a following commit i have just removed that file to pass the build to have the site running and deployed.

Proof that site can be built successfully and deployed for this local fonts pull request after removing `gatsby-ssr.js`: [Deployed site with contentful](https://meghdaminybespokemain-gatsbylocalfont.gatsbyjs.io/)

Gatsby cloud builds: [Github commits](https://github.com/avi312singh/meghdaminy-bespoke/pull/2/commits)
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5769090/204163414-2a6be4e8-8734-443b-a46c-dcc5c1dfc2ff.png">

### Reproduction Link

https://github.com/avi312singh/meghdaminy-bespoke/pull/2/commits

### Steps to Reproduce

1. Add this [gatsby-ssr.js](https://github.com/avi312singh/meghdaminy-bespoke/blob/200bd231cbf0662af9d2153a28d257d923b06b65/gatsby-ssr.js) to the project
2. build will fail
3. Remove it
4. Build will pass and site can be completely built successfully

### Expected Result

[gatsby-ssr.js](https://github.com/avi312singh/meghdaminy-bespoke/blob/200bd231cbf0662af9d2153a28d257d923b06b65/gatsby-ssr.js) to not fail the local dev build

### Actual Result

[gatsby-ssr.js](https://github.com/avi312singh/meghdaminy-bespoke/blob/200bd231cbf0662af9d2153a28d257d923b06b65/gatsby-ssr.js) fails the local dev build

### Environment

```shell
$ gatsby info --clipboard

  System:
    OS: macOS 12.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Edge: 107.0.1418.56
    Firefox: 106.0.3
    Safari: 16.1
  npmPackages:
    gatsby: ^5.0.0 => 5.0.1
    gatsby-plugin-image: ^3.0.0 => 3.0.0
    gatsby-plugin-manifest: ^5.0.0 => 5.0.0
    gatsby-plugin-sharp: ^5.0.0 => 5.0.0
    gatsby-plugin-vanilla-extract: ^3.0.1 => 3.0.1
    gatsby-provision-contentful: ^0.0.3 => 0.0.3
    gatsby-source-contentful: ^8.0.0 => 8.0.0
    gatsby-source-filesystem: ^5.0.0 => 5.0.0
    gatsby-transformer-sharp: ^5.0.0 => 5.0.0
```

**Comment by LekoArts** [comment]
Hi!

The error message says: `WebpackError: ReferenceError: React is not defined` - this is quite clear. You're missing a React import in the gatsby-ssr.js file.

The documentation was missing this, I corrected it. In the future you'll be able to help yourself faster by reading the error message and putting that into Google :)

**Comment by avi312singh** [comment]
I never got that error 
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/5769090/204263019-7cbba25c-5adb-42f3-8e43-cf6999a32864.png">
