### ISSUE TITLE
[gatsby-transformer-remark] `htmlAst` field always empty

### ISSUE THREAD

**Issue by elboman** [gatsbyjs/gatsby#3711]
## Description

I noticed the `htmlAst` field has been recently added to the `gatsby-transformer-remark` plugin, which is awesome. The problem is, the field is always empty, no matter what the markdown file content is.

Am I missing something?

/cc @r24y 

### Environment

Gatsby version: 1.9.169
Node.js version: 9.3.0
Operating System: macOs 10.12.6

### Steps to reproduce
1. clone new project from `https://github.com/gatsbyjs/gatsby-starter-blog`
2. install deps and upgrade to latest version (`yarn && yarn upgrade gatsby@latest gatsby-transformer-remark@latest`)
3. run `yarn dev`
4. navigate to `localhost:8000/__graphql` and run this query
```{
  allMarkdownRemark {
    edges {
      node {
        html
        htmlAst
      }
    }
  }
}
```
4. `htmlAst` is empty, while `html` isn't

**Comment by r24y** [comment]
Oh no! I tested this locally on one of my projects but may have messed something up. I'll see if I can fix it.

By the way, if anyone has ideas on how to test this, I'd appreciate tips. The existing tests seem to rely on schema inference, which means they won't work with the GraphQlJson type. It would be helpful to instead run tests against the schema that actually gets generated.

**Comment by elboman** [comment]
No worries, actually I already opened a PR for fixing this (#3719), so we would just need tests for it, which I couldn't figure out either.

**Comment by r24y** [comment]
This is so I don't forget: as soon as #3719 lands, I've got [one more fix](https://github.com/r24y/gatsby/tree/feat/htmlAst-reparse-raw) and then an [addition to `examples/using-remark`](https://github.com/r24y/gatsby/tree/example/remark-with-htmlAst) to propose new content demonstrating the new `htmlAst` feature.
