### ISSUE TITLE
The result of this StaticQuery could not be fetched in Firefox

### ISSUE THREAD

**Issue by grishy** [gatsbyjs/gatsby#37135]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

After build in Firefox:
Error: The result of this StaticQuery could not be fetched.
This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues

Okey in Chrome:
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/13949080/204934164-0c144c6e-8af9-415a-b3a6-4d8aae7065e4.png">

Firefox:
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/13949080/204934147-4e3a3eaa-3ec6-418c-9281-1613879f77b5.png">

### Reproduction Link

https://github.com/grishy/grishy.github.io/tree/85fabaedb08fbf7bd5d2a40d62cf41ac012381f0

### Steps to Reproduce

1. Open Firefox
2. Go to https://grishy.dev/

### Expected Result

Like in Chrome

### Actual Result

White page

### Environment

```shell
😄
Github Action
+
  System:
    OS: macOS 13.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.1.2 - ~/.npm-global/bin/npm
  Browsers:
    Safari: 16.1
  npmGlobalPackages:
    gatsby-cli: 5.2.0
```

**Comment by grishy** [comment]
It was the same behavior on version 4 and next

**Comment by grishy** [comment]
After cleaning Index DB, Storage, this behavior has been corrected. Is it possible to somehow remove the use of these entities?

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

I visited your site in Firefox (with no plugins etc.) and it works:

![image](https://user-images.githubusercontent.com/16143594/204990273-7dc6040a-f16d-405d-a761-6c50fbee29be.png)

Gatsby also doesn't use Index DB or Storage for StaticQuery behavior.

[reproduction]: https://gatsby.dev/reproduction

**Comment by grishy** [comment]
Hm, I think CacheStorage, not  IndexDB :) Sorry

**Comment by grishy** [comment]
As I understand it, it breaks when there was another build before and it wrote something into the cache. After that, the new version cannot start normally.

Now it's empty

<img width="1534" alt="image" src="https://user-images.githubusercontent.com/13949080/204996396-03529a1c-4497-40a4-b8ac-47d838612813.png">

**Comment by LekoArts** [comment]
Sadly I still can't reproduce this when visiting the site with Firefox. Have you also tried this deployed to another host? I assume your caching setup might be incorrect then.
