### ISSUE TITLE
[v2] Move gatsby-link inside the gatsby package

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#3714]
Gatsby requires gatsby-link to work so it doesn't make sense to have it as a separate project.

**Comment by Redmega** [comment]
`import { Link } from 'gatsby';`!

**Comment by tsriram** [comment]
Assuming no one else is working on it yet, I'm gonna give this a go.

**Comment by calcsam** [comment]
Great!
