### ISSUE TITLE
Local plugin for gatsby-plugin-mdx remarkPlugins silently breaks gatsby-config.ts (Typescript)

### ISSUE THREAD

**Issue by robinmessage** [gatsbyjs/gatsby#37152]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

If I include a local plugin which I intend to use with gatsby-plugin-mdx as a remarkPlugins, and I have a gatsby-config.ts in Typescript, then the config silently fails to load, breaking the site (and the plugin can't be used).

As far as I can see from the docs ( https://www.gatsbyjs.com/docs/how-to/custom-configuration/typescript/#requireresolve ) this should be possible to make work.

### Reproduction Link

https://github.com/parcel-bundler/parcel/issues/6925

### Steps to Reproduce

Try to require a local plugin in gatsby-config.ts

### Expected Result

The local plugin works

### Actual Result

Nothing works

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 19.1.0 - ~/.nvm/versions/node/v19.1.0/bin/node
    npm: 9.1.2 - ~/.nvm/versions/node/v19.1.0/bin/npm
  Languages:
    Python: 3.6.3 - /Users/rhm/anaconda3/bin/python
  Browsers:
    Chrome: 108.0.5359.71
    Firefox: 94.0.1
    Safari: 15.6.1
  npmPackages:
    gatsby: ^5.0.0 => 5.0.0 
    gatsby-plugin-image: ^3.1.0 => 3.1.0 
    gatsby-plugin-mdx: ^5.2.0 => 5.2.0 
    gatsby-plugin-sass: ^6.1.0 => 6.1.0 
    gatsby-plugin-sharp: ^5.1.0 => 5.1.0 
    gatsby-source-filesystem: ^5.2.0 => 5.2.0 
    gatsby-transformer-sharp: ^5.1.0 => 5.1.0
```

**Comment by LekoArts** [comment]
Hi!

As the docs specifically point out, require.resolve **does not work** due to the Parcel upstream issue. You should use the name of the plugin instead as explained in https://www.gatsbyjs.com/docs/creating-a-local-plugin/#project-structure-for-a-local-plugin.
