### ISSUE TITLE
`Recently on Gatsby Cloud` overlaps with textboxes

### ISSUE THREAD

**Issue by mbiesiad** [gatsbyjs/gatsby#37167]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

  `Recently on Gatsby Cloud` overlaps with textboxes.

### Reproduction Link

https://www.gatsbyjs.com/dashboard/account

### Steps to Reproduce

1. As logged in user go to https://www.gatsbyjs.com/dashboard/account
2. Click `user-menu-button` (book icon)
3. See issue

### Expected Result

User can read text from opened `Recently on Gatsby Cloud` - textboxes are behind him

### Actual Result

Can't see some parts of text with this scenario
Screenshot:
![image](https://user-images.githubusercontent.com/18367606/205486354-cef2e0c4-e877-4b13-8250-04d69760dcd2.png)

### Environment

```shell
N/A. Chromium based browser.
```

**Comment by LekoArts** [comment]
Hi!

For Gatsby Cloud related issues please go to https://www.gatsbyjs.com/contact-us/ or use the contact form while logged in to Gatsby Cloud. We're only tracking issues about the open source packages here. Thanks!
