### ISSUE TITLE
Image placeholder shows black square instead of blurred/traced image

### ISSUE THREAD

**Issue by soniCaH** [gatsbyjs/gatsby#37205]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Since upgrading to Gatsby v5 the placeholder options for my images no longer seem to work.
Whether I use tracedSVG, blurred, none, dominant color, they all result in a black square as placeholder instead of an image/trace.

The site (see links) also contains working placeholders, so I guess it is related to png's with transparent parts in it?

### Reproduction Link

https://github.com/soniCaH/KCVV-Elewijt-Gatsby

### Steps to Reproduce

1. Go to the teams lineup page or a player detail page

### Expected Result

Build from BEFORE upgrading to Gatsby 5:

https://637bbe21fae3de0052e6e799--kcvvelewijt.netlify.app/team/a-ploeg/#team-lineup

### Actual Result

Actual build WITH Gatsby v5:

https://www.kcvvelewijt.be/team/a-ploeg/#team-lineup

### Environment

```shell
System:
    OS: macOS 13.0.1
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.94
    Firefox: 107.0
    Safari: 16.1
  npmPackages:
    gatsby: 5.2.0 => 5.2.0 
    gatsby-cli: 5.2.0 => 5.2.0 
    gatsby-paginate: 1.1.1 => 1.1.1 
    gatsby-plugin-google-tagmanager: 5.2.0 => 5.2.0 
    gatsby-plugin-image: 3.2.0 => 3.2.0 
    gatsby-plugin-manifest: 5.2.0 => 5.2.0 
    gatsby-plugin-netlify: 5.1.0 => 5.1.0 
    gatsby-plugin-offline: 6.2.0 => 6.2.0 
    gatsby-plugin-sass: 6.2.0 => 6.2.0 
    gatsby-plugin-sharp: 5.2.0 => 5.2.0 
    gatsby-plugin-use-query-params: 1.0.1 => 1.0.1 
    gatsby-plugin-web-font-loader: 1.0.4 => 1.0.4 
    gatsby-source-drupal: 6.2.0 => 6.2.0 
    gatsby-transformer-sharp: 5.2.0 => 5.2.0 
  npmGlobalPackages:
    gatsby-cli: 2.8.14
    gatsby: 2.18.5
```

### Config Flags

  flags: {
    FAST_DEV: false,
    PARALLEL_SOURCING: false,
  },

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

Also note that tracedSvg was removed, so if that doesn't work anymore it's working as expected: https://github.com/gatsbyjs/gatsby/discussions/37104

[reproduction]: https://gatsby.dev/reproduction

**Comment by soniCaH** [comment]
Hi @LekoArts seems like I did not clear cache between changing tracedSVG to blurred. It does work now. Sad to hear about the removal of travedSVG (I don't really see this message in my log), but blur is better than a black square. Sorry for the issue!
