### ISSUE TITLE
[gatsby-image] Best way to force an aspect ratio?

### ISSUE THREAD

**Issue by arsmth** [gatsbyjs/gatsby#3720]
I'm trying to force a 4:3 aspect ratio on images using sizes from a graphql query. I can't find the best way of doing it though.

I know I need to alter the ```padding-bottom``` on the div child of ```gatsby-image-wrapper``` but what's the best way of doing this?

Maybe I'm just missing something obvious.

**Comment by arsmth** [comment]
Are you using this on the actual gatsby-image component?

**Comment by KyleAMathews** [comment]
Just query for a width/height with the aspect ratio you want and gatsby-transformer-sharp will resize your image e.g. `image(width: 300, height: 400)`. gatsby-image just takes the aspect ratio of the image so resize away!

**Comment by arsmth** [comment]
Sorry, I should have given more detail. I'm displaying my images in a flex grid where the width depends on the viewport width. I was using sizes in my query because the images aren't a set size:

```
image {
  sizes(maxWidth: 500) {
    ...GatsbyContentfulSizes
  }
}
```

```
<Gallery>    // Flex grid
  {images.map(({ node }, i) => (
    <GalleryItem key={node.id}>   // Grid item 25% width
      <Img sizes={node.image.sizes} />
    </GalleryItem>
  ))}
</Gallery>
```

Is there a way I can get my images to come in cropped from my query?

**Comment by pieh** [comment]
You can add maxHeight param to query and/or force gatsby-image inner wrappers to match height of flex row if you use `align-items: stretch;` (default value for this property) on your flex container:

```
.gatsby-image-outer-wrapper, 
.gatsby-image-wrapper {
  height: 100%; 
}
``` 
(you propably want to do that only inside your Gallery component)

**Comment by arsmth** [comment]
Thanks for the reply @pieh  

The maxHeight just reduces the quality of my image rather than crop it. I don't want to hardcode a height on my container, so the images just stretch to the height of the tallest one.

Am I being stupid here? I feel like I should be able to just pass ```Img``` an aspectRatio prop which calculates the padding percentage to apply to that inner div, no? 😩

**Comment by pieh** [comment]
Yes, you can - check edit to my comment - I actually show how to do it :)

**Comment by arsmth** [comment]
Perfect! Is that in the documentation? I couldn't find it. Thanks a lot @pieh !

**Comment by pieh** [comment]
I'm not sure if it's in docs - I found about that when inspecting `gatsby-image` source and fields defined in `xxxSizes` fragments

**Comment by ooloth** [comment]
> ```
> <Gallery>    // Flex grid
>   {images.map(({ node }, i) => (
>     <GalleryItem key={node.id}>   // Grid item 25% width
>       <Img sizes={{...node.image.sizes, aspectRatio: 4/3}} />
>     </GalleryItem>
>   ))}
> </Gallery>
> ```

I had no idea you could set an aspect ratio like this! Thanks for this @pieh.

**Comment by bigfanjs** [comment]
```
 .gatsby-image-wrapper > div {
     padding-bottom: 50% /* your aspect ratio */
 }
```

**Comment by bigfanjs** [comment]
```
.gatsby-image-wrapper > div {
    padding-bottom: 60% !important /* your aspect ratio */
}
```

**Comment by dcooney** [comment]
@pieh Thanks! Here are docs on Aspect Ratio.
https://www.gatsbyjs.org/tutorial/gatsby-image-tutorial/#aspect-ratio
