### ISSUE TITLE
`gatsby-node` with TypeScript results in `setBabelPlugin` not supporting ESM modules 

### ISSUE THREAD

**Issue by DennisRosen** [gatsbyjs/gatsby#37201]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I recently moved to using TypeScript in `gatsby-node` which have resulted in build errors inside `onCreateBabelConfig`. The first error was due to using `require.resolve` which I have since switched to `path.resolve` which works fine. The second error is as follows:

```
  ModuleBuildError: Module build failed (from ./node_modules/gatsby/dist/utils/babel-loader.js):
  C:\Projects\bug-repro\src\babel\removeRedundantWhitespace.ts:8
  export default removeRedundantWhitespace;
  ^^^^^^
  SyntaxError: Unexpected token 'export'
```

The contents of `gatsby-node.ts` in the repro repo is:

```
import { GatsbyNode } from "gatsby"
import path from "path"

// Modify babel config
export const onCreateBabelConfig: GatsbyNode['onCreateBabelConfig'] = (
  { actions, stage },
  options
) => {
  if (stage === 'build-html' || stage === 'build-javascript') {
    actions.setBabelPlugin({
      // Plugin location should be relative to gatsby-node.ts
      name: path.resolve(__dirname, './src/babel/removeRedundantWhitespace.ts'),
      options,
    })
  }
}
```

And the contents of `./src/babel/removeRedundantWhitespace.ts`:

```
const removeRedundantWhitespace = () => ({
  visitor: {
    // Code removed for easier repro
  },
});

// SyntaxError: Unexpected token 'export' error shows up here
export default removeRedundantWhitespace;
```

Switching the `export default` to `module.exports = removeRedundantWhitespace;` works fine.
It seems like Gatsby does not support ESM module syntax for babel plugins when using a TypeScript version of `gatsby-node`.

### Reproduction Link

https://github.com/DennisRosen/gatsby-ts-babel-bug-repro

### Steps to Reproduce

1. Clone the repo
2. `yarn install`
3. `yarn start`

### Expected Result

The build should succeed.

### Actual Result

Build error shows up:

```
  ModuleBuildError: Module build failed (from ./node_modules/gatsby/dist/utils/babel-loader.js):
  C:\Projects\bug-repro\src\babel\removeRedundantWhitespace.ts:8
  export default removeRedundantWhitespace;
  ^^^^^^
  SyntaxError: Unexpected token 'export'
```

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.18 - /c/Python27/python
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.42)
  npmPackages:
    gatsby: ^5.2.0 => 5.2.0
  npmGlobalPackages:
    gatsby-cli: 2.12.92
```

**Comment by marvinjude** [comment]
Hi @DennisRosen,

We'd need to support ESM in `gatsby-config.ts` for this to work since the module you're pulling in is directly piped into Gatsby’s internals where `setBabelPlugin` is used. You can keep an eye on [ESM Support in Gatsby files discussion](https://github.com/gatsbyjs/gatsby/discussions/37069) to know when this is possible https://github.com/gatsbyjs/gatsby/discussions/37069
