### ISSUE TITLE
--path-prefix doesn't work on gatsby develop

### ISSUE THREAD

**Issue by benjaminmikiten** [gatsbyjs/gatsby#3721]
## Description
Using gatsby-cli@1.1.28 I'm able to use `gatsby develop --paths-prefix`
As of gatsby-cli@1.1.31 that throws `Unknown argument: prefix-paths`

It appears that changed in this PR: [https://github.com/gatsbyjs/gatsby/pull/1969](https://github.com/gatsbyjs/gatsby/pull/1969)

### Environment

Gatsby version: 1.1.28
Node.js version: 9.4.0
Operating System: macOS 10.13.2

### Steps to reproduce

1\. Use gatsby-cli@1.1.31

2\. Set a pathPrefix in gatsby-config.js

3\. Run `gatsby develop --paths-prefix`

**Comment by pieh** [comment]
This is correct - https://www.gatsbyjs.org/docs/path-prefix/#development

Why you want to use path prefix in development mode?

**Comment by benjaminmikiten** [comment]
`navigateTo` from `gatsby-link` doesn't apply the prefix so to use those links in development, we've been relying on that from 1.1.28.

**Comment by calcsam** [comment]
That issue was fixed a while back: https://github.com/gatsbyjs/gatsby/issues/1533

**Comment by JohannesMerz** [comment]
one where this would come in really handy is if you have a multi app setup, where each app relies on another one, for example:

www.example.com // landing page
www.example.com/login // auth service, same for all apps of the domain
www.example.com/app // gatsby app that needs the credentials stored in local storage from the login app

This works quite nicely on a server, but you cant develop locally with it as you have no way to run gatsby under the `app` prefix

**Comment by keskiju** [comment]
We run our application on Docker Compose during development. User documentation is generated with Gatsby and the documentation is located in `/docs`. It seems that `gatsby develop --paths-prefix` does add the configured `pathPrefix` to all site paths, but not for `/commons.js` and `/socket.io/socket.io.js` paths:

    commons.js                 404 NOT FOUND
    /socket.io/socket.io.js    404 NOT FOUND

Is there an another setting that defines the commons.js and /socket.io/socket.io.js paths?

**Comment by xaviemirmon** [comment]
I am running into this issue myself.  Has anyone found a way around it?

**Comment by schickling** [comment]
Still seems to be broken for me as well.

**Comment by pr1ntr** [comment]
Yeah this is broken for me. We are running some ECS Services attached to a single application load balancers. we need to run the site in dev mode so we can access prismic previews.  In order for this to work now we need to set up a load balancer for each service which just adds cost and complexity to our infra.

**Comment by derakhshanfar** [comment]
any workaround?

**Comment by rafael-nogueras** [comment]
I, too, am looking for path prefix to be added in development, and so far have not found a satisfactory solution (e.g. the one mentioned above seems to only work for the `/` path).

I tried implementing `onCreatePage()` in gatsby-node.js to replace all pages with ones where the path included the prefix path (only in development), but I ran into the following issues:

- For some reason, `onCreatePage()` is not invoked for pages created manually in `createPages()` (even though I can see from console output that `createPages()` is invoked first), so I cannot prepend the path prefix on manually-created pages.
- The `<Link>` component (and presumably `navigate()`) do not prepend the prefix path in development.
- On a lark, I even tried adding the `--prefix-paths` flag to gatsby develop, to see if that would add the prefix path, but that for some reason seems to make the website hang.

Does anyone have any advice as to how to get this to work in development? Thanks! (I am using gatsby version 2.15.7, for the record).

**Comment by SamIngram96** [comment]
My team tried implementing the [onPreRenderHtml](https://www.gatsbyjs.org/docs/ssr-apis/#onPreRenderHTML) function in gatsby-ssr.js to add a [base](https://www.w3schools.com/tags/tag_base.asp) tag to the header to asset prefix all relative links, but this still didn't prefix /common.js or /socket.io/socket.io.js

**Comment by rafael-nogueras** [comment]
@SamIngram96 Huh, that's an interesting approach. Would you mind sharing your  onPreRenderHtml function implementation?

**Comment by SamIngram96** [comment]
@rafael-nogueras I don't have it on me anymore, I didn't keep it because it didn't solve our problem but it was small and went something like
```
export const onPreRenderHTML = ({ getHeadComponents, replaceHeadComponents }) => {
  const headComponents = getHeadComponents();
  headComponents.unshift('<base href="https://www.assetPrefix.com" />')
  replaceHeadComponents(headComponents)
}
```
hope this helps

**Comment by brunokrebs** [comment]
Why is this issue closed? This is a perfectly valid requirement. I, for example, have another app that I would like to run under the same "domain". That is, I would like to have an NGINX or similar in front of both apps and make Gatsby run under `/blog`, even during development.

**Comment by jamestharpe** [comment]
Agreed, this issue should be open. It is hard to debug a path-prefix issue if you can't run it with path-prefix.

**Comment by nebularnoise** [comment]
I agree, I've had issues as well, and would appreciate being able to develop with prefix enabled.

**Comment by theowenyoung** [comment]
agree, I also need to debug if the login redirect callback has correct logic.

**Comment by jonauz** [comment]
All this seems to be caused because develop doesn't seem to support `--prefix-paths` anymore. I'm not sure why such critical issue is not being picked up and fixed immediately, and rather ignored and even closed.  
Makes us to consider moving away from Gatsby because of such consistently appearing issues, quite unstable platform.  
Also Gatsby CLI is very questionable too.

**Comment by jamestharpe** [comment]
> All this seems to be caused because develop doesn't seem to support `--prefix-paths` anymore. I'm not sure why such critical issue is not being picked up and fixed immediately, and rather ignored and even closed.
> Makes us to consider moving away from Gatsby because of such consistently appearing issues, quite unstable platform.
> Also Gatsby CLI is very questionable too.

I'm greatful to the Gatsby team for what they've built. I wish they'd implement this, but if we really want it then we should be willing to contribute it as a community. There's no need to be harsh.

**Comment by HipsterZipster** [comment]
Can someone from the gatsby team suggest how this can be fixed by a first time contributor to the project? We really want this and would be willing to invest some time into adding support for it

**Comment by benjaminmikiten** [comment]
Hey y'all -- I've been watching these replies come in periodically, gratified to see other people with the same issue I had. I only today realized that _I closed this_ initially because the actual bug I was dealing with had nothing to do with the fact that gatsby develop doesn't support paths. Nothing has changed there, however, and given this is where the discussion about this being helpful is happening, I'll reopen it and see if something comes of it.

**Comment by LekoArts** [comment]
This has been superseded by https://github.com/gatsbyjs/gatsby/issues/16040
