### ISSUE TITLE
[gatsby-source-contentful] Flight mode

### ISSUE THREAD

**Issue by uttrasey** [gatsbyjs/gatsby#3724]
## Description

Add a "flight mode" option so it would be possible* to develop locally using Contentful CMS even if you have no network connectivity.  

`*` Dependant on existing prior connection/cache

### Actual result

Currently `develop` falls over 

`source and transform nodesAccessing your Contentful space failed. Perhaps you're offline or the spaceId/accessToken is incorrect.`

### Expected behavior

The app runs using nodes from last sync

**Comment by uttrasey** [comment]
If this is sensible I'll knock a PR together.... about to spend a lot of time on ✈️'s

**Comment by calcsam** [comment]
This would be great! Let's make the gatsby development experience on bad / spotty connections as good as the gatsby site viewing experience :)

**Comment by uttrasey** [comment]
Got around to doing this https://github.com/gatsbyjs/gatsby/pull/3977

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
