### ISSUE TITLE
Gatsby 5 createRedirect does not work

### ISSUE THREAD

**Issue by Simply007** [gatsbyjs/gatsby#37256]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I wanted to use [createRedirect](https://www.gatsbyjs.com/docs/reference/config-files/actions/#createRedirect), but it does not work:
* locally (gatsby develop)
* on Gatsby cloud  (https://build-dd8e8ea4-750f-44e5-8234-a1b51c40d21e.gatsbyjs.io/)
* on Netlify

### Reproduction Link

https://github.com/Simply007/gatsby-reproduce

### Steps to Reproduce

1. Define create a redirect
    ```js
    exports.createPages = async ({ graphql, actions }) => {
      const { createRedirect } = actions;
    
      createRedirect({
        fromPath: `/articles`,
        toPath: `/test`,
        redirectInBrowser: true,
        isPermanent: true,
      });
    };
    ```
1. Create Link to /articles on some page
    ```js
    <Link to="/articles">This should redirect you to /test page</Link>
    ```

### Expected Result

Redirect should work

### Actual Result

Redirect does not work

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900H
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.46)
```

**Comment by LekoArts** [comment]
Hi!

Redirects won't work during `gatsby develop`, you need to use `gatsby build` & `gatsby serve`.
I think your redirects are incorrect though, as with Gatsby 5 the default trailingSlash behavior is `always`, so e.g. the deployed output you see on https://build-dd8e8ea4-750f-44e5-8234-a1b51c40d21e.gatsbyjs.io links to `/articles/` (note the trailing slash).

Your redirect is targeting `/articles` (without a slash) so it can't work. This is intended behavior. Please make these changes and report back.

**Comment by Simply007** [comment]
Thanks @LekoArts,

trailing slash did the trick.

I would suggest changing the examples (I can do the PR if you want). Or adjust the docs - that one i would leave to your docs team.

If you are OK just with this issue, we can close this issue.

**Comment by LekoArts** [comment]
Sure, would be happy to have a PR updating that example to have trailing slashes :) Maybe also a note about trailing slashes there would be good!
