### ISSUE TITLE
How to extend dynamically generated fields in graphql schema?

### ISSUE THREAD

**Issue by bodia-uz** [gatsbyjs/gatsby#3726]
## Description

What is the best way to extend GraphQL Schema for `markdownRemark frontmatter` and `site siteMetadata`?

Gatsby adds fields to schema automatically, based on the data source. But in our case fields may be or may not be in data. And we use those fields in graphql queries.

Currently I use some workaround like This:
![c1f3d07b-9284-44b9-817a-b3106096b035](https://user-images.githubusercontent.com/2445828/35470257-ab0f9498-034e-11e8-9f3b-3dc06d412c17.png)
![35db7a0e-7e04-4c99-a7e2-bd365e21492f](https://user-images.githubusercontent.com/2445828/35470258-ab425de2-034e-11e8-827b-95ee01425a14.png)

### Environment

Gatsby version: latest

### Actual result

Gatsby failed because of field of query is not in schema

### Expected behavior

Fields are added via gatsby api even if thay are absent in data

...

**Comment by pieh** [comment]
Hi, this is unfortunately known issue that I'm working to resolve - you can check discussion here - https://github.com/gatsbyjs/gatsby/issues/3344#issuecomment-359970488

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
