### ISSUE TITLE
framework-[contenthash].js includes react-dom-server when using gatsby-plugin-image

### ISSUE THREAD

**Issue by danilobuerger** [gatsbyjs/gatsby#37281]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When using `GatsbyImage` from `gatsby-plugin-image`, the `framework-[contenthash].js` is getting bloated by including `react-dom/server`:

![Screenshot 2022-12-16 at 12 26 25](https://user-images.githubusercontent.com/996231/208088365-4aa67b7d-46d3-4336-94c2-5a5fceed06b9.png)

This comes from a change at https://github.com/gatsbyjs/gatsby/pull/35226 from @wardpeet by using `renderToStaticMarkup` from `react-dom/server`:

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-image/src/components/lazy-hydrate.tsx#L202

### Reproduction Link

https://github.com/danilobuerger/gatsby-repro

### Steps to Reproduce

1. Get the reproduction
2. build & serve, notice the `framework-[contenthash].js` size (ca 46.2 kb)
3. Uncomment `GatsbyImage` in `src/pages/index.tsx`
4. build & serve, notice the `framework-[contenthash].js` size (ca 67.4 kb)

The size between step 2 and 4 will be different

### Expected Result

`framework-[contenthash].js` should not include `react-dom/server`.

### Actual Result

`framework-[contenthash].js` includes `react-dom/server`.

### Environment

```shell
System:
    OS: macOS 12.6.2
    CPU: (8) arm64 Apple M1
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.2
  npmPackages:
    gatsby: ^5.3.2 => 5.3.2
    gatsby-plugin-image: ^3.3.2 => 3.3.2
    gatsby-plugin-sharp: ^5.3.2 => 5.3.2
    gatsby-source-filesystem: ^5.3.1 => 5.3.1
    gatsby-transformer-sharp: ^5.3.1 => 5.3.1
```
```


### Config Flags

_No response_

**Comment by LekoArts** [comment]
Thanks for the issue!

Analyzing it with Statoscope can give one some more details:

![image](https://user-images.githubusercontent.com/16143594/213170496-3b132ddd-ca5b-4683-83b4-9e8170838010.png)

I'll play with our webpack configuration to see how to fix that

**Comment by BojanHribernik** [comment]
I can confirm this. Found out about it through Lighthouse report
![Screenshot from 2023-01-23 13-59-42](https://user-images.githubusercontent.com/114930095/214046145-4ce3baed-64af-4b58-b022-5d4368ef9fce.png)

**Comment by danilobuerger** [comment]
Thanks @LekoArts !

**Comment by danilobuerger** [comment]
@LekoArts this seems to not be working on the newest 5.6 release. I am seeing the app-[contenthash].js exploding in size. And the framework-[contenthash].js is not being created.

**Comment by LekoArts** [comment]
Please provide a reproduction, I haven't seen this in my local testing when authoring the PR

**Comment by danilobuerger** [comment]
@LekoArts I narrowed down the issue. It seems to only come up when using pnpm (with the gatsby-plugin-pnpm). Most likely related to the code here: 
https://github.com/Js-Brecht/gatsby-plugin-pnpm/blob/master/src/fixes.ts#L6-L10

**Comment by LekoArts** [comment]
The split chunking won't happen in `gatsby develop` anyways

**Comment by danilobuerger** [comment]
@LekoArts I am seeing this with `gatsby build`.

**Comment by LekoArts** [comment]
I was referring to the plugin's comment:

> Fix missing framework in development.

But yeah, I'm afraid if this is caused through this plugin you'll need to send in a PR fixing it

**Comment by danilobuerger** [comment]
@LekoArts Yeah, but it's really a shame that gatsby doesn't just support pnpm out of the box. There are lots of issues related to pnpm in this repository, it might be worth considering adding pnpm support here if people are using it?
