### ISSUE TITLE
dynamic pages?

### ISSUE THREAD

**Issue by lifeiscontent** [gatsbyjs/gatsby#373]
Hi, I was wondering if Gatsby has support for something like this?

https://middlemanapp.com/advanced/dynamic_pages/

I'd like to pass some data to a template and have Gatsby generate the pages

**Comment by KyleAMathews** [comment]
Yes-ish.

You can't yet dynamically create pages but if you add a react component file (e.g. `cool-dynamic-page.js`) it'll get created at `/cool-dynamic-page/`. Each page component gets passed all site data at `this.props.route.pages`. A good example of this is the index page for the blog starter https://github.com/gatsbyjs/gatsby-starter-blog/blob/master/pages/index.js

**Comment by KyleAMathews** [comment]
I'm working towards making this paradigm much more powerful.

**Comment by renatorib** [comment]
I need something like this too =\

**Comment by MoOx** [comment]
FYI, we implemented this in Phenomic by reading user react-router routes and generate all possible pages according to front-matter metadata https://phenomic.io/docs/usage/routing/

**Comment by dmitrig01** [comment]
Would love to see what's possible here! :-)

**Comment by KyleAMathews** [comment]
@dmitrig01 this is all working in v1! Checkout this issue from last fall https://github.com/gatsbyjs/gatsby/issues/421 and the gatsbygram case study https://www.gatsbyjs.org/blog/gatsbygram-case-study/#app-structure

**Comment by dmitrig01** [comment]
Awesome!! Somehow google decide that this issue was the most relevant thing, but seems that is not the case :-) thanks!

**Comment by KyleAMathews** [comment]
Well now all future Google visitors will have breadcrumbs to direct them on
the right path :-)
