### ISSUE TITLE
Error #85911 with gatsby develop

### ISSUE THREAD

**Issue by ZeldOcarina** [gatsbyjs/gatsby#37315]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

From today, In trying to start my gatsby projects in development, I keep getting the same error:

```
 ERROR #85911  GRAPHQL.EXTRACTION

There was a problem parsing "[path omitted]"; any
GraphQL
fragments or queries in this file were not processed.

This may indicate a syntax error in the code, or it may be a file type
that Gatsby does not know how to parse.

File: ../@zeldocarina/gatsby-theme-dgp-landing/src/layout/Layout.jsx
```

This is just an example, it actually happens across the board in any file where a query is present.

The funny side is if I run gatsby build it works like a charme, which is weird, the problem is usually the opposite.

### Reproduction Link

https://github.com/ZeldOcarina/gatsby-graphql-bug

### Steps to Reproduce

1. Clone the repo and `npm install`
2. Use `gatsby develop`
3. See the error
4. See how it builds cleanly with `gatsby build`

### Expected Result

The dev server should start cleanly

### Actual Result

```
ERROR #85911  GRAPHQL.EXTRACTION

There was a problem parsing "/Users/mattiarasulo/Desktop/web-development.nosync/utils/bug-repo/src/pages/index.js"; any GraphQL
fragments or queries in this file were not processed.

This may indicate a syntax error in the code, or it may be a file type
that Gatsby does not know how to parse.

File: src/pages/index.js

failed extract queries from components - 0.148s
```

### Environment

```shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.0.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 107.0
    Safari: 16.0
  npmPackages:
    gatsby: ^5.3.3 => 5.3.3 
  npmGlobalPackages:
    gatsby-cli: 5.2.0
    gatsby: 5.3.3
```

**Comment by ZeldOcarina** [comment]
@LekoArts would you kindly have any suggestion? I've really tried everything now.. 😔

**Comment by ZeldOcarina** [comment]
Update: I've tried recreating the work area in GitHub Codespaces and it's working, still, if you have any suggestions for local development it's appreciated.

**Comment by ZeldOcarina** [comment]
Update: Now it started to occur in codespace too :(

**Comment by ArmanNisch** [comment]
I can confirm. I am having the same issue. The only "solution" I currently have is to delete node_moduels and reinstall, then the dev server will start... but once I stop the server and try and restart, I get the "There was a problem parsing' GraphQL error. This seems quite urgent!

**Comment by ZeldOcarina** [comment]
I'm really stuck on my job. By the way, @ArmanNisch, do you have console ninja installed? I'm starting to think it might be an issue with Visual Studio Code corrupting some characters, but I'm really just feeling my way in the dark.

**Comment by ZeldOcarina** [comment]
@LekoArts @ArmanNisch I've uninstalled console ninja and the dev server has started cleanly. My sensation was correct, what a solid 5 hours thrown in the trash. Leaving this here in case anyone encounters the same issue. Feel free to close it if not able to reproduce it. I'll test my way around a bit more before closing myself.

**Comment by ArmanNisch** [comment]
@ZeldOcarina oh my word! Ok, I can confirm I do have Console Ninja installed. I will uninstall and see if this issue is also fixed... I will report back, just in the middle of another task atm.

**Comment by ArmanNisch** [comment]
@ZeldOcarina I can confirm that after removing Console Ninja the above-mentioned bug is no more. Thank you very much for figuring this out +100

**Comment by ZeldOcarina** [comment]
Hi!
This has been fixed by the console ninja team appearently:

`https://github.com/wallabyjs/console-ninja/issues/67`

Closing this issue for now.

Happy hacking!
