### ISSUE TITLE
Gatsby preview returns a 404 when server goes into "sleep mode" and forces full rebuild vs. incremental.

### ISSUE THREAD

**Issue by apmsooner** [gatsbyjs/gatsby#37322]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Using drupal latest 2.x gatsby module to trigger a preview. Can verify previews are getting sent to the proper preview server however occasionally using a sandbox account, there seems to be a very downscaled tuning on these servers that force a full rebuild on the preview server. When this happens, the rebuild is only building what currently exists on the preview server so the current revision being requested isn't found and leads to a 404. The build in gatsby cloud is however successful so the error on iframe page is not helpful at all.

Built successful
![image](https://user-images.githubusercontent.com/4030604/209195173-429a38b4-2037-4efc-9a1f-60b32172e8c1.png)

Preview page fail:
![image](https://user-images.githubusercontent.com/4030604/209195349-27ce2b76-2454-48d2-b54b-4211cd76de44.png)

Console log with debugging enabled showing 404 response
![image](https://user-images.githubusercontent.com/4030604/209195498-937c7f38-1837-4961-a044-5a6663128437.png)

Note: Posting current version of gatsby drupal module in reproduction Link only cause its a required field and there is too much configuration involved to simulate a gatsby repository against a drupal sandbox.

### Reproduction Link

https://www.drupal.org/project/gatsby/releases/2.0.0-rc5

### Steps to Reproduce

1. Enable gatsby module on a drupal site
2. Set gatsby settings to a sandbox account on Gatsby cloud
3. Enable preview or a content type
4. Create a node, then edit it and click the preview button
5. Acknowledge new window opens preview and if you havn't generated a recent preview, you'll notice it takes a particularly long time to resolve
6. Verify in gatsby cloud dashboard the preview is building and finishes with success
7. Observe the error returned on the drupal preview page "Oh no! We've run into an error previewing your site..."
8. Add ?debug=true query parameter to preview url in browser window and refresh the page
9. Open console log and observe the responseJson when polling finishes and notice the 404.

### Expected Result

Preview server shouldn't be completely rebuilding periodically when requesting a preview. At the very least, the revision being requested should be stored in cache or something that it can still resolve.

### Actual Result

Preview server rebuilds periodically and only pulls existing data. The requested node revision doesn't resolve and leads to a 404.

### Environment

```shell
System:
    OS: macOS 12.3
    CPU: (10) arm64 Apple M1 Max
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
    Safari: 15.4
  npmPackages:
    gatsby: ^5.2.0 => 5.3.2
    gatsby-plugin-google-analytics: ^5.0.0 => 5.3.0
    gatsby-plugin-image: ^3.0.0 => 3.3.2
    gatsby-plugin-manifest: ^5.0.0 => 5.3.1
    gatsby-plugin-sass: ^6.0.0 => 6.3.1
    gatsby-plugin-sharp: ^5.0.0 => 5.3.2
    gatsby-plugin-sitemap: ^6.0.0 => 6.3.1
    gatsby-source-drupal: ^6.0.0 => 6.3.1
    gatsby-source-filesystem: ^5.0.0 => 5.3.1
    gatsby-transformer-sharp: ^5.0.0 => 5.3.1
  npmGlobalPackages:
    gatsby-cli: 5.0.0
```

**Comment by tyhopp** [comment]
For Gatsby Cloud related issues please reach out to the support here: https://www.gatsbyjs.com/support

Thanks!
