### ISSUE TITLE
gatsby-starter-blog creates invalid URL when filename include reserved letters of URL.

### ISSUE THREAD

**Issue by tenpaMk2** [gatsbyjs/gatsby#37330]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi, developers. Thanks for nice application.
I'm a newbie but I think this behavior is an unkind behavior or a bug.

I want to prevent unintentional creation of invalid URLs.
For example, `example.com/#/` .
So, I made `content/blog/#.md` just for the URL test,
but gatsby didn't show any errors or warnings.
Of cause, I cannot see the post ( `#.md` ) by accessing `localhost:8000/#/` because `#` is a reserved letter of URL.

I like non-ASCII URL (japanese kanji URL) because I'm a Japanese.
So, using `encodeURIComponent(entireFilename)` is not good solution for me.
It is enough to realize that I have created an incorrect URL.

### Reproduction Link

https://github.com/tenpaMk2/reserved-letter-in-url

### Steps to Reproduce

1. `npx gatsby new reserved-letter-in-url https://github.com/gatsbyjs/gatsby-starter-blog`
2. add `content/blog/#.md`
3. `npm run develop`
4. access `localhost:8000/#/`

### Expected Result

Show me an error or a warning at building step.

### Actual Result

No errors and warnings.

### Environment

```shell
- Mac OSX 12.6

If you want to know other informations, please see the reproduction repository.
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue! I wouldn't consider this a bug but functionality you'll need to implement. If you don't want pages to be created with specific characters, edit the `createPages` API in your gatsby-node: https://github.com/tenpaMk2/reserved-letter-in-url/blob/main/gatsby-node.js

**Comment by tenpaMk2** [comment]
@LekoArts Thanks for the reply.

> functionality you'll need to implement.

OK. I got it.
I will implement an invalid URL detector in `createPages` .
