### ISSUE TITLE
resolve.fallback in setWebpackConfig (typescript gatsby-node) not working

### ISSUE THREAD

**Issue by paulgrotzke** [gatsbyjs/gatsby#37346]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

It is not possible to resolve modules in the webpack config. (Typescript gatsby-node)

I get the error in my project: `BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default...` But I can't fix it, because it seems that `setWebpackConfig.resolve.fallback` doesn't work correctly. It doesn't matter what you write in `fallback {...}` (as long as syntactically correct) it seems that nothing happens. 

I started two fresh gatsby inits. One TS. One JS. 
TS-Version: It seems you can write gibberish in the fallback, nothing is happening. 
JS-Version: Works as excepted. If correct fallback is declared -> it is used. If wrong fallback is declared, error pops up during build.

### Reproduction Link

https://github.com/paulgrotzke/gatsby-webpack-config

### Steps to Reproduce

1. `npm init gatsby` one with JS and one with TS 
2. Create `gatsby-node.ts/js` and add: 
```
/// js
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    resolve: {
      fallback: {
        crypto: require.resolve("crypto-browserify123"),
      },
    },
  });
};

/// ts
import path from "path";
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    resolve: {
      fallback: {
        crypto: path.resolve("crypto-browserify123"),
      },
    },
  });
};
```
3. `npm run build`
...

### Expected Result

It should resolve the specified module. Or it should throw an error if a module is specified which is not installed or it has a typo. 

### Actual Result

Nothing happens. If you enter syntactically correct but incorrect code, nothing happens. If you specify a module that is not yet installed, or if you have a typo, nothing happens. If you do these steps in the javascript project, it generates an error (as expected). 

You can only generate an error during build if you use require.resolve. But this is because ESM is not yet supported for Gatsby 5.3 in Typescript. 

### Environment

```shell
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1 Pro
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 103.0
    Safari: 15.6.1
  npmPackages:
    gatsby: ^5.3.3 => 5.3.3
  npmGlobalPackages:
    gatsby: 5.3.3
```

**Comment by marvinjude** [comment]
Hi @paulgrotzke,

This is happening because you're only passing the module path and not actual module. You'd want do something like https://github.com/parcel-bundler/parcel/issues/6925#issuecomment-1003935487 in your `.ts` snippet.

e.g:

```
import { createRequire } from "module";
const req = createRequire(__dirname);

exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    resolve: {
      fallback: {
        crypto: req.resolve("crypto-browserify123"),
      },
    },
  });
};
```
Closing this.

**Comment by paulgrotzke** [comment]
hi @marvinjude 

thanks for reply. but i am not quite sure, how this should fix the problem. 

as mentioned [here](https://www.gatsbyjs.com/docs/how-to/custom-configuration/typescript/#requireresolve) and [here](https://github.com/gatsbyjs/gatsby/issues/37152#issuecomment-1336857742) we cant use require. even if we re-creating require, with require-module. it still breaks.

how i am supposed to pass the module without require? 
or did i get you wrong?
