### ISSUE TITLE
Add an option to disable the colours of the errors in the cli

### ISSUE THREAD

**Issue by cricrio** [gatsbyjs/gatsby#3736]
There is a problem of readability of the errors with a white background. (cf: #2645)
I made a pull request to change the background color to red but it doesn't look good. (cf: #3734)

A better solution to solve the problem may be to disable the color with an option like: --disable-error-color

Example:

    gatsby develop --disable-error-color

**Comment by calcsam** [comment]
This is a great solution -- feel free to implement!

**Comment by calcsam** [comment]
You'll probably want to use the --no-color flag, or failing that FORCE_COLOR=0 on chalk: https://www.npmjs.com/package/chalk

**Comment by cricrio** [comment]
Thanks! The --no-color flag does half the trick as it can already be used to disable chalk but it doesn't disable them in the errors because they are using pretty-error. I will write something to catch the flag and call the method  [withoutColors](https://github.com/AriaMinaei/pretty-error#disabling-colors)
