### ISSUE TITLE
Image processing breaks (createPages...) 'gatsby-plugin-sharp'

### ISSUE THREAD

**Issue by AidanRRR** [gatsbyjs/gatsby#37393]
### Preliminary Checks

- [x] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Whenever building my website Gatsby crashes on the image processing part.

```
Start processing D:\repos\website\public\static\c4dab60483da3cbd37e20af2780ad243\b105a\IMG_0506-1200x800.webp
warn Your GraphQL query in createPages took 21.278 seconds which is an unexpectedly long time. See https://gatsby.dev/create-pages-performance for tips on how to improve this.
⠴ createPages
[======================      ]   21.144 s 98/121 81% Running gatsby-plugin-sharp.IMAGE_PROCESSING jobs
PS D:\repos\twill-net\website> ^F
```

Tried following:
- Clearing Gatsby cache
- Using different node version
- Updating to latest Gatsby version
- Lowering parallel CPU count
- Tried logging inside the gatsby-plugin library to see or this is related to specific images

It started occuring at some point. Can't really share more as it is a large website where images are added on a regular frequency. Problem seems to be only occuring on Windows.

When running `gatsby build` again, it can go an image further. It looks to me that it puts a limit on how long it can process images or page queries?

It just stops processing and doesn't report an error, so might be some timeout or something?
Any setting I can override?

Thanks!!

### Reproduction Link

/

### Steps to Reproduce

/

### Expected Result

Processing is done just fine

### Actual Result

Image processing exits without warning

### Environment

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700K
  Binaries:
    Node: 19.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.10.2
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.54)
  npmGlobalPackages:
    gatsby-cli: 5.3.1
```

### Config Flags

SSR / DSG: Disabled

**Comment by tyhopp** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

Also `gatsby-plugin-sharp` does have the `failOn` option you can try to adjust how sharp behaves when it encounters a corrupt image - https://www.gatsbyjs.com/plugins/gatsby-plugin-sharp/#options.

[reproduction]: https://gatsby.dev/reproduction

**Comment by AidanRRR** [comment]
@tyhopp Thanks for sharing. With the `failOn` it still stops working. I've tried to create a minimal example, but the context is really specific to the business I'm working for and can't share it.

I've tried building on different PC, switching node versions, ..
Seems to only be occuring on Windows.

It does get past the image building process if I up the `GATSBY_EXPERIMENTAL_QUERY_CONCURRENCY` variable. So it looks to me that it gets more stuck with the `createpages` rather than image processing. Are there any timeouts or things that you can do to not have it 'exit' the gatsby building process?
