### ISSUE TITLE
Convert responsive image type names to "fixed" and "fluid"

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#3740]
The current "resolutions" and "sizes" are derived loosely from parts of the responsive image specs but do a mostly poor job of indicating to people what to use them for. Let's fix this before it's too late.

**Comment by pieh** [comment]
Should we keep current "resolutions" and "sizes" fields as aliases for "fixed" and "fluid"? Or remove or deprecate them?

**Comment by KyleAMathews** [comment]
Yeah, just remove the older aliases since they were already deprecated.

**Comment by m-allanson** [comment]
Ok, this should do the following?

- remove `responsiveSizes`
- remove `responsiveResolutions`
- replace `resolutions` with `fixed`
- replace `sizes` with `fluid`

**Comment by m-allanson** [comment]
Should using `resolutions` or `sizes` still be supported, maybe with a deprecation notice?

**Comment by KyleAMathews** [comment]
Yeah, just deprecate them — similar to how the older names are set as deprecated.

**Comment by KyleAMathews** [comment]
Fixed by https://github.com/gatsbyjs/gatsby/pull/5250 thanks @m-allanson!
