### ISSUE TITLE
Preview Build - Cannot access Contentful space

### ISSUE THREAD

**Issue by mendoncanorma** [gatsbyjs/gatsby#37416]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I'm on Free Plan of Gatsby Cloud.

The main build works fine, while preview build fails.

Preview build fails with 'Content Preview API - access token' and preview build works fine with 'Content Delivery API - access token'

### Reproduction Link

https://gatsbystarterhelloworld17638.gatsbyjs.io/

### Steps to Reproduce

I'm on Free Plan of Gatsby Cloud.

The main build works fine, while preview build fails.

Gatsby site - https://gatsbystarterhelloworld17638.gatsbyjs.io/

Preview build fails with 'Content Preview API - access token' and preview build works fine with 'Content Delivery API - access token'

### Expected Result

Preview build should work fine.

### Actual Result

Preview build fails with 'Content Preview API - access token' and preview build works fine with 'Content Delivery API - access token'

### Environment

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 14.20.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 108.0.5359.125
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.76)
  npmPackages:
    gatsby: ^4.24.7 => 4.24.8
    gatsby-plugin-image: ^2.24.0 => 2.24.0
    gatsby-plugin-less: ^6.24.0 => 6.24.0
    gatsby-plugin-react-helmet: ^5.24.0 => 5.24.0
    gatsby-plugin-sharp: ^4.24.0 => 4.24.0
    gatsby-plugin-styled-components: ^5.24.0 => 5.24.0
    gatsby-plugin-webfonts: ^2.3.1 => 2.3.1
    gatsby-source-contentful: ^7.22.0 => 7.22.0 reserved.
    gatsby-source-filesystem: ^4.24.0 => 4.24.0
    gatsby-transformer-sharp: ^4.24.0 => 4.24.0
  npmGlobalPackages:
    gatsby-cli: 4.24.0
```

**Comment by mendoncanorma** [comment]
The following error is seen on console:

ERROR Cannot access Contentful space "*********fz3" on environment "master" with access token "***************************************rbC0". Make sure to double check them! (value)

**Comment by tyhopp** [comment]
For Gatsby Cloud related issues please reach out to the support here: https://www.gatsbyjs.com/support

Thanks!
