### ISSUE TITLE
Error in function useStaticQuery in ./.cache/static-query.js:83 on a MBP M1 Pro

### ISSUE THREAD

**Issue by ramojej** [gatsbyjs/gatsby#37412]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I'm having this error on my mac, but not on my Windows machine. Any idea what's causing this?

![image](https://user-images.githubusercontent.com/12524474/210918576-eabe13ae-02ca-4aab-affd-6d1f25ff996d.png)

### Reproduction Link

https://github.com/ramojej/circle-of-life

### Steps to Reproduce

1. npm install
2. gatsby develop
3.
...

### Expected Result

It will run smoothly like in Windows 

### Actual Result

like the screenshot above

### Environment

```shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1 Pro
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.3.0 - /opt/homebrew/bin/node
    npm: 9.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.1
  npmPackages:
    gatsby: ^5.3.0 => 5.3.3 
    gatsby-omni-font-loader: ^2.0.0 => 2.0.2 
    gatsby-plugin-gatsby-cloud: ^5.3.0 => 5.3.1 
    gatsby-plugin-image: ^3.3.0 => 3.3.2 
    gatsby-plugin-manifest: ^5.3.0 => 5.3.1 
    gatsby-plugin-no-index: ^1.0.2 => 1.0.2 
    gatsby-plugin-offline: ^6.0.0 => 6.3.1 
    gatsby-plugin-postcss: ^6.0.0 => 6.3.0 
    gatsby-plugin-preact: ^7.3.0 => 7.3.0 
    gatsby-plugin-react-helmet: ^6.3.0 => 6.3.0 
    gatsby-plugin-react-svg: ^3.3.0 => 3.3.0 
    gatsby-plugin-sharp: ^5.3.0 => 5.3.2 
    gatsby-source-filesystem: ^5.3.0 => 5.3.1 
    gatsby-source-wordpress: ^7.3.0 => 7.3.2 
    gatsby-transformer-sharp: ^5.3.0 => 5.3.1 
  npmGlobalPackages:
    gatsby-cli: 5.3.1
```

**Comment by marvinjude** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

Right now, your site uses environment variables that we don't have access to. That then causes `gatsby develop` to fail

**Comment by ramojej** [comment]
Hey, @marvinjude. Is it okay if I email you the env variables since I can't recreate a codesandbox for this one.

**Comment by marvinjude** [comment]
Sure

**Comment by ramojej** [comment]
This is solved by making some changes in the imports

from 

```
import Seo from '../components/SEO'
```
to

```
import Seo from '../components/seo'
```

file is named seo.js not SEO.js.
