### ISSUE TITLE
gatsby-transformer-yaml - Multiple nodes created for each yaml entry...

### ISSUE THREAD

**Issue by smerth** [gatsbyjs/gatsby#3742]
## Description

Implementing gatsby-transformer-yaml results in duplicate nodes when queried with graphql.

### Environment

Gatsby version: 1.1.28
Node.js version: v8.9.1
Operating System: MacOS 10.13.2

### File contents (if changed):

`gatsby-config.js`: 

```javascript    
`gatsby-transformer-yaml`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `./src/data/yaml`,
      },
    }
```

`package.json`: 

```json
    "gatsby-transformer-yaml": "^1.5.14",
```
`gatsby-node.js`: 
modified according to end of chapter 4 of Gatsby tutorial

`gatsby-browser.js`: 
modified according to end of chapter 4 of Gatsby tutorial

### Actual result

What happened.

I followed the instructions to implement gatsby-transformer-yaml.
1) install the npm module
2) edit the `gatsby-config.js` as above
3) add a yaml file in the folder I defined for data

@ letters.yaml
```yaml
- character: a
- character: u
- character: m
- character: p
```

4) Run a graphql query in GrahpiQL

```
query LettersQuery {
  allLettersYaml(sort: {fields: [character], order: DESC}) {
    edges {
      node {
        character
      }
    }
  }
}
```

### Expected behavior

I expected: 
```
{
  "data": {
    "allLettersYaml": {
      "edges": [
        {
          "node": {
            "character": "u"
          }
        },
        {
          "node": {
            "character": "p"
          }
        },
        {
          "node": {
            "character": "m"
          }
        },
        {
          "node": {
            "character": "a"
          }
        }
      ]
    }
  }
}
```
Instead I got
```
{
  "data": {
    "allLettersYaml": {
      "edges": [
        {
          "node": {
            "character": "u"
          }
        },
        {
          "node": {
            "character": "u"
          }
        },
        {
          "node": {
            "character": "p"
          }
        },
        {
          "node": {
            "character": "p"
          }
        },
        {
          "node": {
            "character": "m"
          }
        },
        {
          "node": {
            "character": "m"
          }
        },
        {
          "node": {
            "character": "a"
          }
        },
        {
          "node": {
            "character": "a"
          }
        }
      ]
    }
  }
}
```

**As you can see I get back two nodes in my graphQL query for each entry in my yaml file...**  

Am I doing something wrong in the query?  or is Gatsby creating two nodes for each entry in my yaml file?  Or is my yaml file formatted wrong (it does validate...)?

**Comment by smerth** [comment]
Ok. I solved this…  Here's the answer.  

I noticed that if I add `id` the graphQL query I can see that the `id` is essentially the path to the data node… the first set of nodes had an id with an absolute path and the second set of nodes had an id with something that looked like a relative path. 

That made me think I had mis-configured the `gatsby-source-filesystem` . 

Sure enough that turned out to be the problem. 

Here is my current `gatsby-config.js` which now delivers one set of node matching the yaml file content.

```javascript
module.exports = {
  siteMetadata: {
    title: `Pandas Eating Lots`
  },
  plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `src`,
        path: `${__dirname}/src/`
      }
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `data`,
        path: `${__dirname}/src/data/yaml`,
      },
    },
    `gatsby-transformer-remark`,
    `gatsby-plugin-glamor`,
    {
      resolve: `gatsby-plugin-typography`,
      options: {
        pathToConfigModule: `src/utils/typography`
      }
    },
    `gatsby-transformer-yaml`,
  ]
};

```

**Comment by donavon** [comment]
Thx for posting! I was having the same issue and this solved it.

Note to others. he fix, specifically, was to change from a relative reference:

```
path: `./src/data/yaml`
```

to an absolute:
```
path: `${__dirname}/src/data/yaml`,
```

Alternatively, I eliminated the reference completely and it worked just fine. I assume this is because I already had:
```
path: `${__dirname}/src/`,
```
