### ISSUE TITLE
Custom Resolvers/Schema skipped due to "no new or changed html files to build"

### ISSUE THREAD

**Issue by claygiffin** [gatsbyjs/gatsby#37428]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I created a custom resolver that checks the current date, and then sets a value on that record for whether a queried from the record date is greater than the current date.

Everything works as expected when the cache has been cleared or there is some other change to the site that would normally trigger changes to the site's html. However, if the only change is that the current date has changed, the custom resolvers and scheme functions in my `gatsby-node` file are not run.

Instead, I see the message: `There are no new or changed html files to build`. There _would be_ new html files to build, if the custom resolvers function ran. 

---

Custom resolvers/schema example:

```
export const createResolvers: GatsbyNode['createResolvers'] = ({
  createResolvers,
}) => {
  const today = new Date()
  createResolvers({
    ExampleRecord: {
      isUpcoming: {
        type: `Boolean!`,
        resolve: async (source) => {
          const { date } = source.frontmatter
          const cutoff = new Date(date)
          return cutoff > today
        },
      },
    },
  })
}

export const createSchemaCustomization: GatsbyNode['createSchemaCustomization'] =
  ({ actions: { createTypes } }) => {
    createTypes(`
    type ExampleRecord implements Node {
      isUpcoming: Boolean!
    }
  `)
  }
```

### Reproduction Link

https://codesandbox.io/s/proud-waterfall-2j4c4p

### Steps to Reproduce

1. Create a custom schema that changes based on `cutoff > today` in the above example.
2. Re-run build when current date has changed (and nothing else)

### Expected Result

Output pages should change based on custom schema

### Actual Result

Site builds with message `There are no new or changed html files to build`, even if `cutoff > today` should result in new values for some records.

### Environment

```shell
System:
    OS: macOS 13.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 107.0.1
    Safari: 16.2

Gatsby Version:
    "gatsby": "^5.3.2",
```

**Comment by tyhopp** [comment]
Hi @claygiffin, I was able to see the behavior you described. There is no built-in hook or option I'm aware of that you can use to force warm builds to recalculate Gatsby node functions that modify the schema.

This may or may not be suitable for your use case, but if it were me I'd probably [SSR](https://www.gatsbyjs.com/docs/how-to/rendering-options/using-server-side-rendering/#prerequisites) or fetch client side if I needed my content to vary based on the current time.

Will close this since we will not look into changing this behavior.

Thanks!
