### ISSUE TITLE
Gatsby fails to load when browser is refreshed

### ISSUE THREAD

**Issue by sproctor** [gatsbyjs/gatsby#37432]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When refreshing the page, I get a blank page and this error in the console:

```
app-7414a12cb7cb584d2cce.js:1
Uncaught (in promise) Error: We couldn't find the correct component chunk with the name component---src-pages-index-tsx
    at e.loadComponent (app-7414a12cb7cb584d2cce.js:1:46054)
    at app-7414a12cb7cb584d2cce.js:1:42983
https://scrapreceiptsmaster.gatsbyjs.io/page-data/offline-plugin-app-shell-fallback/page-data.json:1
Failed to load resource: the server responded with a status of 404 ()
```

The weird thing is that it's not using the offline plugin. That directory doesn't exist when built locally. Is there something weird with Gatsby Cloud?

I have a very slightly modified version of https://github.com/gatsbyjs/gatsby-starter-sanity-homepage-ts running on Gatsby Cloud at https://scrapreceiptsmaster.gatsbyjs.io/. The modifications are only to change the colors and images, and to setup Sanity.

### Reproduction Link

https://github.com/gatsbyjs/gatsby-starter-sanity-homepage-ts

### Steps to Reproduce

1. Follow installation guide on the starter
2. Deploy on Gatsby Cloud
3. Load page
4. Refresh page

### Expected Result

Page to refresh as normal.

### Actual Result

It produces the error mentioned above.

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/bin/node
    Yarn: 1.22.19 - ~/.npm-packages/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.2
  npmPackages:
    gatsby: ^5.0.0 => 5.3.3 
    gatsby-plugin-image: ^3.0.0 => 3.3.2 
    gatsby-plugin-manifest: ^5.0.0 => 5.3.1 
    gatsby-plugin-sharp: ^5.0.0 => 5.3.2 
    gatsby-plugin-vanilla-extract: ^4.0.1 => 4.0.1 
    gatsby-provision-sanity: ^0.0.5 => 0.0.5 
    gatsby-source-contentful: ^8.0.0 => 8.3.1 
    gatsby-source-filesystem: ^5.0.0 => 5.3.1 
    gatsby-source-sanity: ^7.3.2 => 7.6.1 
    gatsby-transformer-sharp: ^5.0.0 => 5.3.1
```

**Comment by sproctor** [comment]
Just to know, I tried adding the `gatsby-offline-plugin`. This fixes the issue. I don't know where the problem is originating, but I'm guessing that either Gatsby Cloud of the Gatsby Sanity plugin is doing something weird.

**Comment by sproctor** [comment]
Also, the above link in the report will no longer reproduce the error as adding `gatsby-offline-plugin` has fixed the issue there.

**Comment by javierfuentesm** [comment]
I had the same issue the project crashed and i get 
error Cannot read properties of null (reading 'fileWatchers')

**Comment by tyhopp** [comment]
Hi @sproctor, can you reproduce this minimally with just the Sanity source plugin? `gatsby-offline-plugin` won't get added to your site (by Gatsby Cloud or otherwise) unless you add it yourself.

**Comment by sproctor** [comment]
Unfortunately, I have almost no experience with Gatsby or Node in general. Making a smaller repro would take more time than I have to devote to this. Maybe someone else more knowledge who is experiencing this has the time for it.

**Comment by sproctor** [comment]
Well, I have an idea as to the cause of the issue. gatsby-offline-plugin (maybe?) had created a shadow copy of an ancient version of my website that would load whenever I visited the production site. Clearing all of the cached data in my browser fixed the issue. 

Refreshing would load the new version at the moment, but opening the page again would always load the old version. Even after a hard refresh. I guess this issue can be closed. It's resolved on my end, but it doesn't feel like a satisfying resolution. I'm not sure why there was an issue with the version at https://scrapreceiptsmaster.gatsbyjs.io/ had an issue as it hadn't ever seen the old version.

**Comment by MadhaviMaithani** [comment]
> gatsby-offline-plugin

I am also getting error -

Cannot read properties of null (reading 'fileWatchers')

can you tell me how you resolve this issue
