### ISSUE TITLE
[WIN32] Path contains invalid characters. Works fine in Darwin/Linux

### ISSUE THREAD

**Issue by agonsgd** [gatsbyjs/gatsby#37466]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I am using the following code in `create-pages.js` to create dynamic/splat urls using `:subscription_id` on `path` and `matchPath` which works perfectly fine in MAC/Linux systems. 

```
		actions.createPage({
			path: "/account/subscriptions/:subscription_id",
			component: require.resolve(`../templates/account/profile/subscription`),
			matchPath: "/account/subscriptions/:subscription_id",
			context: { language: process.env.GATSBY_COUNTRY, settings: { ...settings } },
		});
```

On Windows, this is always failing when you visit the said webpage, in this case `http://localhost:8000/account/subscriptions/8970043674`

The following error throws in terminal:

```
Error: Path contains invalid characters: web\public\page-data\account\subscriptions\:subscription_id

  - utils.js:16 checkPath
    [web]/[fs-extra]/lib/mkdirs/utils.js:16:21

  - make-dir.js:12 Object.module.exports.makeDir
    [web]/[fs-extra]/lib/mkdirs/make-dir.js:12:3

  - index.js:22 Object.defineProperty.value
    [web]/[universalify]/index.js:22:13

  - index.js:20
    [web]/[fs-extra]/lib/output-file/index.js:20:11

  - index.js:22
    [web]/[universalify]/index.js:22:54


not finished Writing page-data.json files to public directory - 0.109s   
```

### Reproduction Link

https://github.com/agonsgd/Invalid_path_win32_gatsby

### Steps to Reproduce

1. Create a dynamic/splat page with createPage action such as 
```
actions.createPage({
  path: "/account/subscriptions/:subscription_id",
  component: require.resolve(`../templates/account/profile/subscription`),
  matchPath: "/account/subscriptions/:subscription_id",
  context: { language: process.env.GATSBY_COUNTRY, settings: { ...settings } },
});
```
2. Visit the page `http://localhost:8000/account/subscriptions/8970043674`
3. Project stops and throws error

### Expected Result

The page should open normally with the :subscription_id parameter in url being passed as a prop in component.

### Actual Result

Project throws error:

```
Error: Path contains invalid characters: web\public\page-data\account\subscriptions\:subscription_id

  - utils.js:16 checkPath
    [web]/[fs-extra]/lib/mkdirs/utils.js:16:21

  - make-dir.js:12 Object.module.exports.makeDir
    [web]/[fs-extra]/lib/mkdirs/make-dir.js:12:3

  - index.js:22 Object.defineProperty.value
    [web]/[universalify]/index.js:22:13

  - index.js:20
    [web]/[fs-extra]/lib/output-file/index.js:20:11

  - index.js:22
    [web]/[universalify]/index.js:22:54


not finished Writing page-data.json files to public directory - 0.109s   
```

### Environment

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (24) x64 AMD Ryzen 9 3900XT 12-Core Processor           
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.76)
  npmPackages:
    gatsby: ^4.24.0 => 4.24.0 
    gatsby-plugin-breadcrumb: ^12.3.1 => 12.3.1 
    gatsby-plugin-google-tagmanager: ^4.18.0 => 4.18.0 
    gatsby-plugin-image: ^2.24.0 => 2.24.0 
    gatsby-plugin-netlify: ^5.1.0 => 5.1.0 
    gatsby-plugin-postcss: ^5.18.0 => 5.18.0 
    gatsby-plugin-react-helmet: ^5.18.0 => 5.18.0 
    gatsby-plugin-react-svg: ^3.1.0 => 3.1.0 
    gatsby-plugin-root-import: ^2.0.8 => 2.0.8 
    gatsby-plugin-sass: ^5.18.0 => 5.18.0 
    gatsby-plugin-sharp: ^4.24.0 => 4.24.0 
    gatsby-plugin-sitemap: ^5.18.0 => 5.18.0 
    gatsby-plugin-svgr: ^3.0.0-beta.0 => 3.0.0-beta.0 
    gatsby-plugin-why-did-you-render: ^2.0.0 => 2.0.0 
    gatsby-source-sanity: ^7.5.1 => 7.5.1 
    gatsby-transformer-sharp: ^4.24.0 => 4.24.0 
  npmGlobalPackages:
    gatsby-cli: 3.4.0
```

**Comment by tyhopp** [comment]
Hi @agonsgd, `path` in `createPage` should be a valid url - https://www.gatsbyjs.com/docs/reference/config-files/actions/#createPage.

To create a splat route via `createPage` you can use `matchPath` with a `*` instead of a`:` - https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v1-to-v2/#change-client-paths-to-use-a-splat

Alternatively, you can use the File System Route API for splat routes as well - https://www.gatsbyjs.com/docs/reference/routing/file-system-route-api/#splat-routes

If you saw an outdated doc somewhere that suggested you use the `:` for splat routes can you link it here? We should update it if so.

I'll close this since we have these documented ways for splat routes and we do test on Windows. Thanks!

**Comment by agonsgd** [comment]
Hi @tyhopp thanks for answer.

What's the equivalent of 

```

		actions.createPage({
			path: "/account/subscriptions/:subscription_id",
			component: require.resolve(`../templates/account/profile/subscription`),
			matchPath: "/account/subscriptions/:subscription_id",
			context: {settings: { ...settings } },
		});
```

in Windows?

I cannot find anything on documentation at all.

**Comment by LekoArts** [comment]
@agonsgd The `path` should be a valid URL. So you could use `/account/subscriptions/[subscription_id]`. It doesn't really matter what placeholder you use as long as it's a valid URL. For the file system routing we use `[]`: https://www.gatsbyjs.com/docs/how-to/routing/client-only-routes-and-user-authentication/

btw, in case `settings` is a big object I wouldn't recommend it passing through `context`: https://www.gatsbyjs.com/docs/creating-and-modifying-pages/#performance-implications

If you can skip the context part you could use `src/pages/account/subscriptions/[subscription_id].js` to create the client-only page. That is our recommended way of creating them.

**Comment by agonsgd** [comment]
So the weird thing is that on MAC, I can use `path: "/account/subscriptions/:subscription_id",` and use context and everything. On windows literally nothing works so I was just wondering if there's an equivalent of that in windows, seems that not.

Thanks

**Comment by dardanbakiu2** [comment]
colon (:) it's not a valid for a directories in Windows, replace it with an underscore (_) in Windows
try this code foreach case

`if(os.platform() === 'win32'){
  path = path.replace(/:/g, '_')
}`

**Comment by LekoArts** [comment]
That's just how Windows works: https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions
