### ISSUE TITLE
StaticQuery could not be fetched when directory contains a space

### ISSUE THREAD

**Issue by dannymate** [gatsbyjs/gatsby#37528]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Occurs during gatsby develop and build.

Trying to use MDX to generate the layout of pages. Using gatsby-node to find MDX files and generate pages at the given slug using a template. As soon as I try to use useStaticQuery in the template or component with this it throws an error.

I have used both TSX and JSX. I have used Gatsby 5.4.2 and 5.5.0.

### Reproduction Link

https://github.com/dannymate/Gatsby-useStaticQuery-Bug

### Steps to Reproduce

1. Install gatsby-plugin-mdx
2. Configure a filesystem location outside of the page directory
3. Use gatsby node to generate the MDX at frontmatter slug with a template
4. Call useStaticQuery in template

### Expected Result

The static query should run correctly.

### Actual Result

![image](https://user-images.githubusercontent.com/26135914/214427227-c65cb2f1-097f-4867-9e62-1ece5a10b902.png)

### Environment

```shell
System:
    OS: Linux 6.1 Fedora Linux 37.20230119.0 (Silverblue)
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.7.0/bin/yarn
    npm: 9.3.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Languages:
    Python: 3.11.1 - /usr/bin/python
  Browsers:
    Firefox: 109.0
  npmPackages:
    gatsby: ^5.4.2 => 5.5.0 
    gatsby-plugin-mdx: ^5.5.0 => 5.5.0 
    gatsby-source-filesystem: ^5.5.0 => 5.5.0 
  npmGlobalPackages:
    gatsby-cli: 5.4.0
```

**Comment by pieh** [comment]
I couldn't reproduce this using provided repro repository - it just works for me:
![image](https://user-images.githubusercontent.com/419821/214797471-d64d20d3-6bae-4ba8-a2dd-0a95eb115c54.png)

Can you verify that this does happen in repro you provided?

**Comment by dannymate** [comment]
I do get the error with the repro. I'll see if I can find another computer to try it on.

**Comment by pieh** [comment]
This is shot in the dark, but does the absolute path to your project on your machine ( `/home/misiek/dev/my-gatsby-project` as example of what I mean) contain any special characters? It might also be case of lower/upper case mixing as linux is case sensitive and there might be some "normalization" going on somewhere that breaks things. Ideally if you could paste your path, I'd try replicating that locally. My previous test was running on ubuntu (via WSL on Windows heh), so ~linux as well tho definitely different distro but not sure if there are any relevant differences betwen fedora and ubuntu that could be relevant for this

**Comment by dannymate** [comment]
My project path: `/var/home/dannymate/Documents/Coding Projects/SCP Gatsby Vanilla Extract/Gatsby-useStaticQuery-Bug`

Maybe not so relevant between Ubuntu and Fedora but I am using the Fedora Silverblue spin which is an immutable OS. I've found somebody else with a similar system to me to try it on so I'll see if they get the same error.

**Comment by dannymate** [comment]
I just got them to try the project and they get the same error message as me. He was running inside a toolbox is why you're getting the OS like that but he is running Silverblue.

```
 System:
    OS: Linux 6.1 Fedora Linux 37 (Container Image)
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.12.1 - /usr/bin/node
    npm: 8.19.2 - /usr/bin/npm
  npmPackages:
    gatsby: ^5.4.2 => 5.5.0
    gatsby-plugin-mdx: ^5.5.0 => 5.5.0
    gatsby-source-filesystem: ^5.5.0 => 5.5.0
  npmGlobalPackages:
    gatsby-cli: 5.5.0
```

![image](https://user-images.githubusercontent.com/26135914/215115297-540e58d5-4555-4d80-ab66-c8d6c26f8323.png)

**Comment by upscalepixels** [comment]
> This is shot in the dark, but does the absolute path to your project on your machine ( `/home/misiek/dev/my-gatsby-project` as example of what I mean) contain any special characters? It might also be case of lower/upper case mixing as linux is case sensitive and there might be some "normalization" going on somewhere that breaks things. Ideally if you could paste your path, I'd try replicating that locally. My previous test was running on ubuntu (via WSL on Windows heh), so ~linux as well tho definitely different distro but not sure if there are any relevant differences betwen fedora and ubuntu that could be relevant for this

Had this same issue setting a new project and took your advice. Seems to be related to upper case letters in the directory name. 

My Website --> Not Working
my website --> Working
my-website --> Working

**Comment by dannymate** [comment]
Moved my project here: `/var/home/dannymate/Gatsby-useStaticQuery-Bug` and it started working. 
I suppose it doesn't like spaces in the path?

**Comment by pieh** [comment]
I can also reproduce now after moving test project to directory with space in it, so will take a look at this more to figure it out

**Comment by pieh** [comment]
I did find the problem, for now added failing (unit) test case for it in https://github.com/gatsbyjs/gatsby/pull/37544

**Comment by pieh** [comment]
Fix published in `@next` dist tag for testing - `gatsby@5.6.0-next.2`

**Comment by pieh** [comment]
@upscalepixels 

> My Website --> Not Working
> my website --> Working
> my-website --> Working

I did test with uppercases and that worked just fined for me, it was always space in path that was the problem - can you confirm that `my website` actually was working? It wasn't in my tests
