### ISSUE TITLE
Sitemap includes homepage with trailing slash even when trailingSlash set to never

### ISSUE THREAD

**Issue by hitfactory** [gatsbyjs/gatsby#37536]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Even when setting trailingSlash to never and siteUrl to the homepage URL without a trailing slash, the homepage URL in sitemap generated by gatsby-plugin-sitemap includes a trailing slash.

### Reproduction Link

https://github.com/hitfactory/gatsby-starter-blog

### Steps to Reproduce

1. gatsby new blog https://github.com/gatsbyjs/gatsby-starter-blog
2. npm install gatsby-plugin-sitemap
3. Set trailingSlash to never in gatsby-config.js and siteUrl to https://gatsbystarterblogsource.gatsbyjs.io
4. Add `gatsby-plugin-sitemap` to plugins array in gatsby-config.js
5. gatsby build
6. gatsby serve
7. View https://gatsbystarterblogsource.gatsbyjs.io/sitemap-0.xml

### Expected Result

sitemap.xml includes siteUrl as configured i.e. without trailing slash

### Actual Result

sitemap-0.xml includes homepage with trailing slash

### Environment

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 103.0.2
    Safari: 16.2
  npmPackages:
    gatsby: ^5.5.0 => 5.5.0 
    gatsby-plugin-feed: ^5.5.0 => 5.5.0 
    gatsby-plugin-image: ^3.5.0 => 3.5.0 
    gatsby-plugin-manifest: ^5.5.0 => 5.5.0 
    gatsby-plugin-sharp: ^5.5.0 => 5.5.0 
    gatsby-plugin-sitemap: ^6.5.0 => 6.5.0 
    gatsby-remark-images: ^7.5.0 => 7.5.0 
    gatsby-remark-prismjs: ^7.5.0 => 7.5.0 
    gatsby-remark-responsive-iframe: ^6.5.0 => 6.5.0 
    gatsby-source-filesystem: ^5.5.0 => 5.5.0 
    gatsby-transformer-remark: ^6.5.0 => 6.5.0 
    gatsby-transformer-sharp: ^5.5.0 => 5.5.0
```

**Comment by LekoArts** [comment]
Please see https://github.com/gatsbyjs/gatsby/discussions/34205#discussioncomment-1945640

**Comment by mikolasan** [comment]
The answer is basically: "it's fine like that, don't worry"
