### ISSUE TITLE
Question: Using with html-webpack-inline-source-plugin

### ISSUE THREAD

**Issue by michellocana** [gatsbyjs/gatsby#3754]
Is it possible to use Gatsby with [html-webpack-inline-source-plugin](https://www.npmjs.com/package/html-webpack-inline-source-plugin)?
I'm trying to configure the plugin inside ```modifyWebpackConfig``` on ```gatsby-node.js```, is that right? 
I'm a newbie into webpack, so maybe i'm just missing something.
```
exports.modifyWebpackConfig = ({ config, stage }) => {
    switch (stage) {
        case 'develop-html':
            config.plugin('html', HtmlWebpackPlugin, [{
                inlineSource: '\.'
            }]);

            config.plugin('html2', HtmlWebpackInlineSourcePlugin, []);

            break;
    }
    
    return config;
};
```
Amazing site generator by the way, thanks :)

**Comment by KyleAMathews** [comment]
Hey, you could probably do this but Gatsby natively handles generating HTML so you don't want to use webpack's HTML plugins.

If you're trying to figure out how to do something specific, feel free to post another issue asking that question.
