### ISSUE TITLE
Gatsby Worpdress Preview Server Issue

### ISSUE THREAD

**Issue by lemonadvertising** [gatsbyjs/gatsby#37540]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

<p style="margin: 0px 0px 1.1em; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI Adjusted&quot;, &quot;Segoe UI&quot;, &quot;Liberation Sans&quot;, sans-serif; font-size: 15px; vertical-align: baseline; box-sizing: inherit; clear: both; --_pr-img-mb:0; color: rgb(35, 38, 41); letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">We are using Gatsby framework and fetching content from WordPress. However, the Gatsby Cloud previews are not consistent and are sometimes redirecting to other pages. Is there any configuration we need to implement in WordPress to fix this issue? We have tried running previews on local preview server, changing settings in WordPress and enabling debug for previews, but the redirect from the WordPress URL to the Gatsby source WordPress post/page URL is still not working properly. Can anyone provide guidance or insights on how to resolve this issue?</p><p style="margin: 0px 0px 1.1em; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI Adjusted&quot;, &quot;Segoe UI&quot;, &quot;Liberation Sans&quot;, sans-serif; font-size: 15px; vertical-align: baseline; box-sizing: inherit; clear: both; --_pr-img-mb:0; color: rgb(35, 38, 41); letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Below are the mentioned versions.</p><div class="s-table-container" style="margin: 0px 0px 1.1em; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI Adjusted&quot;, &quot;Segoe UI&quot;, &quot;Liberation Sans&quot;, sans-serif; font-size: 15px; vertical-align: baseline; box-sizing: inherit; overflow-x: auto; color: rgb(35, 38, 41); letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

  | Version
-- | --
gatsby | 5.4.2
gatsby-source-wordpress | 7.3.2
WordPress | 6.1.1
WP Gatsby | 2.3.3
WP GraphQL | 1.13.7

</div>

As per the gatsby-source-wordpress [troubleshooting doc](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/debugging-and-troubleshooting.md#broken-preview-templates) we even tried running previews on local preview server.

In WP, settings/gatsbyjs we then changed the setting as below: 
Preview Webhook URL : https://mypreviewdomain.com/__refresh 
Gatsby Content Sync URL : https://mypreviewdomain.com/

We enabled the debug for previews and can see the logs of the post/page data when we click preview in WP. The preview URL gets redirected from the WP URL to https://mypreviewdomain.com/gatsby-source-wordpress/postid-date/postid (e.g. https://mypreviewdomain.com/gatsby-source-wordpress/122412023-01-27%2011:01:31/12241/) and it shows 404 page. However, if we browse the post URL directly (https://mypreviewdomain.com/post-url), we can see the updated content. This means that the preview changes are working properly but the redirection to the respective post/page URL is having some issue.

### Reproduction Link

https://gatsby.dev/reproduction

### Steps to Reproduce

As per the gatsby-source-wordpress [troubleshooting doc](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/debugging-and-troubleshooting.md#broken-preview-templates) try running previews on local preview server.

In WP, settings/gatsbyjs we then changed the setting as below:
Preview Webhook URL : https://mypreviewdomain.com/__refresh
Gatsby Content Sync URL : https://mypreviewdomain.com/

### Expected Result

 The previews should work as expected

### Actual Result

 We enabled the debug for previews and can see the logs of the post/page data when we click preview in WP. The preview URL gets redirected from the WP URL to https://mypreviewdomain.com/gatsby-source-wordpress/postid-date/postid (e.g. https://mypreviewdomain.com/gatsby-source-wordpress/122412023-01-27%2011:01:31/12241/) and it shows 404 page. However, if we browse the post URL directly (https://mypreviewdomain.com/post-url), we can see the updated content. This means that the preview changes are working properly but the redirection to the respective post/page URL is having some issue.

### Environment

```shell
gatsby	5.4.2
gatsby-source-wordpress	7.3.2
WordPress	6.1.1
WP Gatsby	2.3.3
WP GraphQL	1.13.7
```

**Comment by LekoArts** [comment]
Hi!

For Gatsby Cloud related issues, please go to https://www.gatsbyjs.com/support/ or reach out via the contact form inside the Gatsby Cloud dashboard.

Thanks!

**Comment by lemonadvertising** [comment]
Hi @LekoArts,

The redirect issue is on custom previews server as well. On the custom preview server, we are able to see the logs for the post/page in question, but the preview does not redirect to the respective post/page URL.

**Comment by LekoArts** [comment]
The engineers on the Cloud support will have more context about the preview feature / Content Sync and I'm also not sure if the local Gatsby environment even supports that type of redirect. So I'd still encourage you to reach out to the support there.
