### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'hook') in new Gatsby build

### ISSUE THREAD

**Issue by bot19** [gatsbyjs/gatsby#37559]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Recently I started a new build using Gatsby and came across this particular error I can't seem to track down in Gatsby [1]. It's `TypeError: Cannot set properties of undefined (setting 'hook')` from the file `head-export-handler-for-browser.js:160` located in the cache `webpack-internal:///Users/user/dir/test-gatsby-for-js-error/.cache/head/head-export-handler-for-browser.js`.

I assume it's a gatsby file as you can find various references to gatsby inside of it. It first started on my actual build but I've manage to do a fresh install & reproduce the issue. This build has TS, SASS, responsive images, gtag, manifest file, MDX. Basically as soon as I run `npm run develop` & get the localhost website, I can see the error.

Images:
![Screenshot 2023-02-01 at 12 23 01 pm](https://user-images.githubusercontent.com/24539964/215924107-5b57b5bf-56b1-4641-99c6-c3a7eeee1816.jpg)
![Screenshot 2023-02-01 at 12 23 19 pm](https://user-images.githubusercontent.com/24539964/215924126-80678133-65e8-4571-a96d-ec3118bab4d5.jpg)

My `package.json`:
```
{
  "name": "test-gatsby-for-js-error",
  "version": "1.0.0",
  "private": true,
  "description": "test-gatsby-for-js-error",
  "author": "bot19",
  "keywords": [
    "gatsby"
  ],
  "scripts": {
    "develop": "gatsby develop",
    "start": "gatsby develop",
    "build": "gatsby build",
    "serve": "gatsby serve",
    "clean": "gatsby clean",
    "typecheck": "tsc --noEmit"
  },
  "dependencies": {
    "@mdx-js/react": "^2.2.1",
    "gatsby": "^5.5.0",
    "gatsby-plugin-google-gtag": "^5.5.0",
    "gatsby-plugin-image": "^3.5.0",
    "gatsby-plugin-manifest": "^5.5.0",
    "gatsby-plugin-mdx": "^5.5.0",
    "gatsby-plugin-sass": "^6.5.0",
    "gatsby-plugin-sharp": "^5.5.0",
    "gatsby-source-filesystem": "^5.5.0",
    "gatsby-transformer-sharp": "^5.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "sass": "^1.57.1"
  },
  "devDependencies": {
    "@types/node": "^18.11.18",
    "@types/react": "^18.0.27",
    "@types/react-dom": "^18.0.10",
    "typescript": "^4.9.4"
  }
}
```

To reproduce, please clone my minimal reproduction repo. Using latest Chrome, but first experienced it in Brave. Also, it seems when I use incognito mode, the TypeError goes away.

Many thanks!

[1] I can find similar errors for next.js, but from a diff file:
- https://stackoverflow.com/questions/73129969/next-js-typeerror-cannot-set-properties-of-undefined-setting-hook
- https://stackoverflow.com/questions/75225532/typeerror-cannot-set-properties-of-undefined-setting-hook

### Reproduction Link

https://github.com/bot19/test-gatsby-for-js-error

### Steps to Reproduce

1. clone repo
2. install packages
3. run develop environment
4. access local build with devTools open, you should see the TypeError, if not, hit refresh a few times.

### Expected Result

Clean fresh build without any TypeErrors

### Actual Result

Fresh build has TypeError despite having not touch any code

### Environment

```shell
System:
    OS: macOS 13.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 3.3.0 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0
    Safari: 16.2
  npmPackages:
    gatsby: ^5.5.0 => 5.5.0
    gatsby-plugin-google-gtag: ^5.5.0 => 5.5.0
    gatsby-plugin-image: ^3.5.0 => 3.5.0
    gatsby-plugin-manifest: ^5.5.0 => 5.5.0
    gatsby-plugin-mdx: ^5.5.0 => 5.5.0
    gatsby-plugin-sass: ^6.5.0 => 6.5.0
    gatsby-plugin-sharp: ^5.5.0 => 5.5.0
    gatsby-source-filesystem: ^5.5.0 => 5.5.0
    gatsby-transformer-sharp: ^5.5.0 => 5.5.0
  npmGlobalPackages:
    gatsby-cli: 5.5.0
```

**Comment by LekoArts** [comment]
Hi!

Thanks for the issue and already looking into it a little bit. I've tried your reproduction and don't see this issue in e.g. Chrome:

![image](https://user-images.githubusercontent.com/16143594/215987857-5dc15b9d-2c0a-443d-a85a-607cea39579a.png)

By also having the links to the StackOverflow issues + the information that this doesn't occur for you in an incognito window I'm quite sure that it has to do with a chrome extension you're using.

I'd try disabling all and manually enabling them to find the culprit. So unfortunately this isn't something we can directly fix.

**Comment by lezan** [comment]
Hey @bot19 is `gatsby-plugin-google-gtag` configure and some tags in Google Tag Manager active? Because I experienced something similar in this situation. A Custom HTML on GTM was referencing a div element still not loaded but defined in gatsby.

**Comment by bot19** [comment]
@LekoArts thanks for looking into it, indeed when I try another profile without my extensions, it doesn't occur, I'll go through it at some point & nail it down.

@lezan thanks for the suggestion, I commented out the plugin `// "gatsby-plugin-google-gtag",` in `gatsby-config.ts` and it seems to also get rid of it, I'll know for sure tomorrow after some more time, but it sounds like you're onto something.
