### ISSUE TITLE
Gatsby Preview widget stuck on  "Building a new preview"

### ISSUE THREAD

**Issue by MotaZor94** [gatsbyjs/gatsby#37556]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Everytime I trigger a build or make a data change in Strapi, the build finishes in 15 20 seconds without any errors, but the widget keeps saying Building a new preview for the next 20 minutes.

<img width="321" alt="Screenshot 2023-01-31 at 18 00 29" src="https://user-images.githubusercontent.com/45624002/215832294-b5bc3fc1-0ac2-4fb7-90dd-c7cd20546532.png">

### Reproduction Link

Private company repo (not able to share)

### Steps to Reproduce

1. Trigger a gatsby cloud build by making a change in Strapi
2. Open Gatsby preview
3. Wait for the build to finish and see that the widget keeps saying Building a new preview
...

### Expected Result

Expecting to see "Preview finished building"

### Actual Result

widget keeps saying Building a new preview

### Environment

```shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 15.5
  npmPackages:
    gatsby: ^5.4.2 => 5.4.2
    gatsby-plugin-eslint: 4.0.3 => 4.0.3
    gatsby-plugin-google-tagmanager: ^5.4.0 => 5.4.0
    gatsby-plugin-image: ^3.4.0 => 3.4.0
    gatsby-plugin-loadable-components-ssr: 4.3.2 => 4.3.2
    gatsby-plugin-lodash: ^6.4.0 => 6.4.0
    gatsby-plugin-manifest: 5.4.0 => 5.4.0
    gatsby-plugin-offline: 6.4.0 => 6.4.0
    gatsby-plugin-perf-budgets: 0.0.18 => 0.0.18
    gatsby-plugin-postcss: ^6.4.0 => 6.4.0
    gatsby-plugin-purgecss: ^6.2.1 => 6.2.1
    gatsby-plugin-react-helmet: 6.4.0 => 6.4.0
    gatsby-plugin-remove-fingerprints: 0.0.2 => 0.0.2
    gatsby-plugin-sharp: ^5.4.0 => 5.4.0
    gatsby-plugin-split-css: ^2.0.3 => 2.0.3
    gatsby-plugin-styled-components: ^6.4.0 => 6.4.0
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.30 => 1.1.30
    gatsby-source-filesystem: ^5.4.0 => 5.4.0
    gatsby-source-strapi: ^3.0.4 => 3.0.4
    gatsby-transformer-sharp: ^5.4.0 => 5.4.0
  npmGlobalPackages:
    gatsby-cli: 5.4.0
```

**Comment by LekoArts** [comment]
Hi!

For Gatsby Cloud related questions please use https://www.gatsbyjs.com/support or the feedback widget on the Gatsby Cloud dashboard.
