### ISSUE TITLE
Webstorm throws duplicate declaration warning. 

### ISSUE THREAD

**Issue by dmxt** [gatsbyjs/gatsby#37558]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I can't find another issue, so I'm making a new one.

I can't figure out how to make the warning disappear without an error. 

WebStorm complains of duplicate declaration over the code.

`gatsby-config.js`
```
  plugins: [
    `gatsby-plugin-image`,
    {
      resolve: `gatsby-source-filesystem`, //duplicate
      options: {
        path: `${__dirname}/content/blog`,
        name: `blog`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`, //duplicate
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
      resolve: `gatsby-source-filesystem`, // duplicate
      options: {
        name: `images`,
        path: `${__dirname}/content/images`,
      },
    },

...
```

**Do you think this is the only way I can do this, and do I have to ignore the error?** 

### Reproduction Link

https://github.com/dmxt/dmxt-blog

### Steps to Reproduce

1. Make multiple declarations for `gatsby-source-filesystem` in `gatsby-config.js` on the JetBrains program
2. Make a git commit in the JetBrains program 
3. Get duplicate warnings

### Expected Result

No warning

### Actual Result

Got warning 

```
Warning:(26, 8) Duplicate declaration
Warning:(27, 8) Duplicate declaration
Warning:(31, 8) Duplicate declaration
Warning:(32, 8) Duplicate declaration
```

over multiple `gatsby-source-filesystem` declarations

### Environment

```shell
System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1 Pro
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.4.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Safari: 16.2
  npmPackages:
    gatsby: ^4.23.0 => 4.25.4
    gatsby-plugin-feed: ^4.23.0 => 4.24.0
    gatsby-plugin-image: ^2.23.0 => 2.24.0
    gatsby-plugin-manifest: ^4.23.0 => 4.24.0
    gatsby-plugin-sharp: ^4.23.0 => 4.24.0
    gatsby-remark-copy-linked-files: ^5.23.0 => 5.24.0
    gatsby-remark-images: ^6.23.0 => 6.24.0
    gatsby-remark-prismjs: ^6.23.0 => 6.24.0
    gatsby-remark-responsive-iframe: ^5.23.0 => 5.24.0
    gatsby-remark-smartypants: ^5.23.0 => 5.24.0
    gatsby-source-filesystem: ^4.23.0 => 4.24.0
    gatsby-transformer-remark: ^5.23.0 => 5.24.0
    gatsby-transformer-sharp: ^4.23.0 => 4.24.0
  npmGlobalPackages:
    gatsby-cli: 5.5.0
```

**Comment by LekoArts** [comment]
Hi!

The code you're using is correct and the only correct way of declaring multiple instances of `gatsby-source-filesystem` in `gatsby-config`.

You'll need to report this problem to Jetbrains.
