### ISSUE TITLE
createNodeField having no effect

### ISSUE THREAD

**Issue by mannieschumpert** [gatsbyjs/gatsby#3759]
## Description
I am using `onCreateNode` and `createNodeField` as I have seen referenced in many places, but node fields are not being added.

### Environment
Gatsby version: 1.9.54
Node.js version: 8.8.1
Operating System: MacOS High Sierra

### File contents (if changed):
In my gatsby-node.js:
```js
exports.onCreateNode = ({
  node, boundActionCreators,
}) => {
  const { createNodeField } = boundActionCreators

  createNodeField({
    node,
    name: 'shareLink',
    value: 'arbitrary string'
  })
}
```
I have tried limiting the code to check for specific `node.internal.type`, as well as removed the `.cache` folder as referenced in other issues.

### Actual result
"shareLink" field is not added. It is not discoverable in the graphql debugger and throws errors when the site attempts to access the field.

### Expected behavior
"shareLink" field should exist in page nodes.

Surely I must be doing something wrong, but that would baffle me, given how many examples I have referenced for this functionality.

**Comment by KyleAMathews** [comment]
Did you look under `fields`? The new field should be at `node.fields.newField`.

**Comment by mannieschumpert** [comment]
Arg. That's the issue. Apologies, I didn't find that referenced!

**Comment by KyleAMathews** [comment]
Curious where you were looking? Would love a PR from you to clarify that part of the docs!

**Comment by iDVB** [comment]
I'm having this exact issue and I **have** looked under `node.fields` which does not seem to exist.
I can only see the field added if I console out that node inside of `onCreateNode` just after calling `actions.createNodeField` 

```javascript
exports.onCreateNode = ({ node, actions, getNode }) => {
  if (!isLeverNode(node)) return;
  actions.createNodeField({
    node,
    name: 'slug',
    value: `${node.lever_id}_test`,
  });
};
```

**Comment by liltechnomancer** [comment]
I am having the same issue as @iDVB

**Comment by dhakan** [comment]
I'm experiencing this same issue that @iDVB and @liltechnomancer is describing. If it's of any use, I'm trying to extend a node of the type `Mdx`. Meaning, it shows up as `node.fields.<name_of_field>` but not in a subsequent GQL query.

Any insights?

**Comment by sn3h** [comment]
Same here, using gatsby-source-prismic plugin

**Comment by dhakan** [comment]
If I remember correctly, my issue was that I was running some async calls which I never made the gatsby API aware of(like a missing `await` or something like that). This is vague in my memory so take it with a grain of salt, but I recall my error being flaky and not consistent. https://www.gatsbyjs.org/docs/debugging-async-lifecycles/ was helpful anyways.

**Comment by sn3h** [comment]
> If I remember correctly, my issue was that I was running some async calls which I never made the gatsby API aware of(like a missing `await` or something like that). This is vague in my memory so take it with a grain of salt, but I recall my error being flaky and not consistent. https://www.gatsbyjs.org/docs/debugging-async-lifecycles/ was helpful anyways.

Sadly, this does not seem to be the issue. When I call createNodeField without any conditions, it appeares on gatsby nodes, that are not set up with the plugin. The plugin itself keeps on ignoring any attempt to add anything. 

`exports.onCreateNode = ({ node, actions}) => {
  const { createNodeField } = actions;
// this adds x at some nodes, like allSitePage
  createNodeField({
    node,
    name: `x`,
    value: `x`,
  });
// this is nowhere to be found..
  if (node.internal.type === `PrismicBlogpost`) {
    createNodeField({
      node,
      name: `slug`,
      value: `/blog/${node.uid}`,
    });
    console.log(actions, node)
  }
};
`

but this seems to be more of gatsby-source-prismic issue, so I it does not belong in here

**Comment by tsdexter** [comment]
I may be misunderstanding `createNodeField` but I believe it is not meant to be available in the GraphQL schema at `node.fields.fieldName` but rather it's used during build time, custom resolvers, etc... 

For those above (or newcomers) if you need a field generated by `createNodeField` available in your GraphQL schema you can add it like so in `gatsby-node.js` 

```js 
exports.onCreateNode = async ({
  node,
  actions: { createNodeField },
}) => {
  // your custom field that you are creating
  // you can skip this part if you want to work with other plugins custom fields
  if (node.internal.type === "ExampleType") {
    createNodeField({
      node,
      name: `testField`,
      value: `testValue-${node.id}`,
    })
  }
}

// customize the GraphQL schema to expose the `testField` 
exports.createSchemaCustomization = async ({ actions }) => {
  const { createTypes, createFieldExtension } = actions
  createFieldExtension({
    name: `testField`,
    extend() {
      return {
        resolve(source) {
          return `${source.fields.testField}`
        },
      }
    },
  })
  createTypes(`
    type ExampleType {
      testField: String @testField
    }`
  )
}
```

**Comment by jcarroll-ceo** [comment]
@tsdexter thank you. That's exactly what I was missing!
