### ISSUE TITLE
Graphql fragments not working inside of gatsby-node.ts

### ISSUE THREAD

**Issue by LiamWinterton** [gatsbyjs/gatsby#37623]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Using graphql fragments only seems to work inside of the page directory. When using fragments inside of gatsby-node.ts, they do not work.

Example:

My fragment:

```js
export const PageSeo = graphql`
	fragment FullSeo on SanitySeo {
		og_title
		og_description
		og_image {
			asset {
				url
			}
		}
		twitter_title
		twitter_description
		...SlugInfo
	}
`
```

In /src/pages/index.tsx:

```js
export const query = graphql`
	query SanityHomepage {
		sanityHomepage {
			hero {
				...HomepageHero
			}
			seo {
				...FullSeo
			}
		}
	}
`
```

This FullSeo fragment works fine. Seo is of type "SanitySeo"

In gatsby-node.ts:

```js
const ABOUT_PAGE_QUERY = await graphql(`
    query AboutPage {
		sanityAboutPage {
			id
			title
			seo {
				...FullSeo
			}
		}
	}
`)
```

When I add this, I get "Unknown fragment "FullSeo".". Seo is still of type "SanitySeo".

### Reproduction Link

Private Repo

### Steps to Reproduce

1. Create fragment
2. Use inside of pages directory (Works fine)
3. Use inside of gatsby-node query (fails)

### Expected Result

I would expect the fragment to be useable project wide

### Actual Result

Fragment was only useable inside of pages directory

### Environment

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
  Binaries:
    Node: 19.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.4.0 - ~\AppData\Roaming\npm\npm.CMD
  Languages:
    Python: 2.7.18 - /c/Python27/python
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (109.0.1518.70)
  npmPackages:
    gatsby: ^5.3.0 => 5.3.2
    gatsby-plugin-google-analytics: ^5.2.0 => 5.2.0
    gatsby-plugin-image: ^3.2.0 => 3.2.0
    gatsby-plugin-manifest: ^5.2.0 => 5.2.0
    gatsby-plugin-react-svg: ^3.3.0 => 3.3.0
    gatsby-plugin-sass: ^6.3.0 => 6.3.0
    gatsby-plugin-sharp: ^5.2.0 => 5.2.0
    gatsby-plugin-sitemap: ^6.2.0 => 6.2.0
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-filesystem: ^5.2.0 => 5.2.0
    gatsby-source-sanity: ^7.6.0 => 7.6.0
    gatsby-transformer-sharp: ^5.2.0 => 5.2.0
  npmGlobalPackages:
    gatsby-cli: 4.24.0
```

**Comment by LekoArts** [comment]
Hi!

It's currently working as expected as it's a feature request to support this: https://github.com/gatsbyjs/gatsby/discussions/12155

It has technical reasons why it currently doesn't work and would need feature work to make it work.
