### ISSUE TITLE
In onPreRenderHTML, getPostBodyComponents is not returning all inline scripts

### ISSUE THREAD

**Issue by martonmegyeri** [gatsbyjs/gatsby#37641]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

After updating to Gatsby v5.6, the following two script elements are not accessible via the `onPreRenderHTML` API:

```
        <script id="gatsby-script-loader">
            /*<![CDATA[*/
            window.pagePath = "/";
            /*]]>*/
        </script>
        <!-- slice-start id="_gatsby-scripts-1" -->
-->     <script id="gatsby-chunk-mapping">
            window.___chunkMapping = "...";
        </script>
-->     <script>
            window.___webpackCompilationHash = "...";
        </script>
        <!-- slice-end id="_gatsby-scripts-1" -->
    </body>
```

In `onPreRenderHTML`, the `getPostBodyComponents` function is used by our team to retrieve script elements with inline content, and based on their content we are generating sha256 hashes for our Content Security Policy. In v4.x this worked without any problems, but after updating to the latest version, not all script elements created by Gatbsy are returned by this function.

I found a related Pull Request from 2018: https://github.com/gatsbyjs/gatsby/pull/8043

### Reproduction Link

It is not related to a specific project.

### Steps to Reproduce

1. Create a new Gatsby project with v5.5+.
2. Check the returned elements by `getPostBodyComponents` in `onPreRenderHTML`.

### Expected Result

In `onPreRenderHTML`, `getPostBodyComponents` should return all inline scripts attached by Gatsby to the end of body.

### Actual Result

In `onPreRenderHTML`, `getPostBodyComponents` is not returning all inline scripts attached by Gatsby to the end of body.

### Environment

```shell
System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 16.3
  npmPackages:
    gatsby: ^5.6.0 => 5.6.0
```

**Comment by LekoArts** [comment]
Please see https://github.com/gatsbyjs/gatsby/discussions/37036 - it's currently working as intended

**Comment by martonmegyeri** [comment]
> 

Thanks for your answer!
It would be useful if this change was included in the v4 to v5 migration guide.
