### ISSUE TITLE
`printTypeDefinitions` expects string argument in TS type definition

### ISSUE THREAD

**Issue by char-cole** [gatsbyjs/gatsby#37642]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

According to the [docs](https://www.gatsbyjs.com/docs/reference/config-files/actions/#printTypeDefinitions) & https://github.com/gatsbyjs/gatsby/issues/26213, the method `printTypeDefinitions` in gatsby-node should require an object (even an empty object) as its first argument, but its type definition expects it to receive a string first argument.

I can reproduce the TS error in the provided link, but I don't actually know which is correct - neither produces a `schema.gql` in my project, likely due to other build errors. So maybe it's been changed and the docs are out of date, in which case please change the issue type.

### Reproduction Link

https://codesandbox.io/s/hungry-pond-hw9jo9?file=/gatsby-node.ts

### Steps to Reproduce

1. Add TypeScript to project
2. Define `exports.createSchemaCustomization` in gatsby-node.ts
3. Call `actions.printTypeDefinitions({})` in the callback defined above

### Expected Result

No type error

### Actual Result

TS shows a type error: Argument of type '{}' is not assignable to parameter of type 'string'

### Environment

```shell
I'm using Gatsby 4.25.4, but the repro shows the error exists in 5.6.0 as well
```

**Comment by pieh** [comment]
Thanks for report!

PR with fixes to the type definition started in https://github.com/gatsbyjs/gatsby/pull/37647
