### ISSUE TITLE
Graphql-Types are not being generated unless inlined

### ISSUE THREAD

**Issue by tippfelher** [gatsbyjs/gatsby#37643]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Graphql-Types are not being generated unless inlined:

```ts
import { GatsbyNode } from 'gatsby';

const TEST_QUERY = `
  query Test {
    allMdx {
      edges {
        node {
          internal {
            contentFilePath
          }
        }
      }
    }
  }
`;

export const createPages: GatsbyNode["createPages"] = async ({ graphql }) => {
  // BAD: does NOT generate Queries.TestQuery
  const testResult = await graphql(TEST_QUERY);
  if (testResult.data) {
    console.log("t");
  }

  // GOOD: does generate Queries.Test2Query
  const test2Result = await graphql<Queries.Test2Query>(`
    query Test2 {
      allMdx {
        edges {
          node {
            internal {
              contentFilePath
            }
          }
        }
      }
    }
  `);
  if (test2Result.data) {
    console.log("t");
  }
}
```

### Reproduction Link

https://github.com/tippfelher/repro-gatsby-graphql-inline

### Steps to Reproduce

@see repo

### Expected Result

Queries can have arguments and should be reusable with different variables, such as

```
const result1 = await graphql<Queries.TestQuery>(TEST_QUERY, vars1);
const result2 = await graphql<Queries.TestQuery>(TEST_QUERY, vars2);
const result3 = await graphql<Queries.TestQuery>(TEST_QUERY, vars3);
```

but this isn't possible atm. (@see description)

### Actual Result

@see description

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 1600 Six-Core Processor            
  Binaries:
    Node: 18.14.0 - ~\AppData\Local\Temp\yarn--1676127507900-0.4531614243396782\node.CMD
    Yarn: 1.22.15 - ~\AppData\Local\Temp\yarn--1676127507900-0.4531614243396782\yarn.CMD
    npm: 9.3.1 - E:\nodejs\npm.CMD
  Languages:
    Python: 3.11.0
  Browsers:
    Chrome: 109.0.5414.120
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.41)
  npmPackages:
    gatsby: ^5.6.0 => 5.6.0 
    gatsby-plugin-emotion: ^8.6.0 => 8.6.0 
    gatsby-plugin-mdx: ^5.6.0 => 5.6.0 
    gatsby-source-filesystem: ^5.6.0 => 5.6.0
```

### Config Flags

none

**Comment by LekoArts** [comment]
Hi!

We use https://the-guild.dev/graphql/tools/docs/graphql-tag-pluck under the hood and only look for the `graphql()` function inside `gatsby-node`. So currently it's working as expected.

As per [its documentation](https://the-guild.dev/graphql/tools/docs/graphql-tag-pluck#gqlmagiccomment), you can add a `/* GraphQL */` comment and it should discover it.

Feel free to put up a PR to improve https://www.gatsbyjs.com/docs/how-to/local-development/graphql-typegen/ in regards to that!
