### ISSUE TITLE
Swag Error

### ISSUE THREAD

**Issue by TwizzyDev** [gatsbyjs/gatsby#37655]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

Swag Error 

### Steps to Resolve this Issue

1.open shop
2.click on free swag
3.
...

**Comment by LekoArts** [comment]
Hi, please write complete sentences as otherwise we can't understand what you want. Thanks!
