### ISSUE TITLE
gatsby-plugin-image and opacity 0

### ISSUE THREAD

**Issue by ile** [gatsbyjs/gatsby#37673]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I have a blog, made with `gatsby@next` here: https://aamu.app/blog/

The sources for the blog are here: https://github.com/AamuApp/aamu-blog

The content comes from a headless CMS. API key not provided at this time, but can be given later if needed. The image urls come from the CMS and I'm handling the conversion in gatsby-node.js.

The problem is that the `opacity` of the `<img>` and other rules are kept as `0`, quite randomly. This error happens maybe 80% of the time, so it should be reproducible on the site.

![image](https://user-images.githubusercontent.com/433707/219554305-e2e43051-0528-4086-87d6-46f258b539d1.png)
![image](https://user-images.githubusercontent.com/433707/219554418-eae04cc8-09e2-4e01-b108-2dfa95775f1c.png)

Any help, ideas?

### Reproduction Link

https://aamu.app/blog/

### Steps to Reproduce

1. Go to https://aamu.app/blog/
2. Click one of the blogs
3. Click the link that goes back to the main page of the blog (on the top right). You should see the bug after a few clicks.

### Expected Result

Images should be showing normally

### Actual Result

Images are left blurry from time to time (now showing the final image).

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 19.5.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.3.1 - /usr/local/bin/npm
  Browsers:
    Firefox: 109.0.1
  npmPackages:
    gatsby: ^5.8.0-next.0 => 5.8.0-next.0
    gatsby-plugin-image: ^3.6.0 => 3.6.0
    gatsby-plugin-react-helmet: ^6.6.0 => 6.6.0
    gatsby-plugin-sharp: ^5.6.0 => 5.6.0
    gatsby-source-filesystem: ^5.6.0 => 5.6.0
    gatsby-source-graphql: ^5.6.0 => 5.6.0
    gatsby-transformer-sharp: ^5.6.0 => 5.6.0
  npmGlobalPackages:
    gatsby: 3.14.0
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by ile** [comment]
Hi,

Here's the reproduction repo: https://github.com/ilkkah/aamu-blog-repro

- git clone 
- npm install
- npm run build
- cd public
- run a webserver on that directory
- go to the url
- when you see the site, press reload (F5) so many times that you see some images left blurry

The blurriness doesn't happen in developer mode, only in build mode.

**Comment by ile** [comment]
It's quiet. Is my issue a non-issue? I saw the problem.

**Comment by LekoArts** [comment]
Unfortunately I can't reproduce it both on your own website and with the reproduction repository.

**Comment by ile** [comment]
For some reason it is harder to reproduce now. I can see it when I go to the site the first time (with empty cache): http://127.0.0.1:8000/testing/

Also I can see it when I disable cache (devtools open).

**Comment by ile** [comment]
I still want to say that I could reproduce it – by setting "disable cache" and reloading the page. DevTools open was enough.

**Comment by ile** [comment]
Ok, let me close this for now. I don't seen to get it at my blog at the moment.

**Comment by khivi** [comment]
I am able to recreate issue. If the image is in cache it does not occur. The first time it loads the opacity is 0 (disable cache).  Only occurs with build not on deploy on laptop.

Occurs with both firefox and safari. You can see it at https://khivi.com/

**Comment by khivi** [comment]
It still occurs for me

**Comment by ile** [comment]
Let's reopen.

**Comment by khivi** [comment]
On website https://khivi.com/ you can see the issue occuring

**Comment by runemadsen** [comment]
We're running into the same issue on our production site. It happens randomly and feels like a race condition between the DOM and the image onloads that remove the placeholder blur. Also, what is up with these issues getting tagged as stale when there are clear reproductions and people saying they are experiencing the same issue?
