### ISSUE TITLE
MDX tableOfContents field doesn't populate titles correctly when headings contain Markdown formatting

### ISSUE THREAD

**Issue by meganesu** [gatsbyjs/gatsby#37704]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi y'all! Running into issues using the `tableOfContents` field on MDX nodes when the headings in my .mdx file contain Markdown formatting (bold, italics, inline code, links). The `title` field truncates the full heading text from the body of the page.

### Reproduction Link

https://github.com/meganesu/repro-gatsby-mdx-table-of-contents-with-markdown-formatting

### Steps to Reproduce

1. Start up the dev server
2. Go to `localhost:8000`

### Potential solution

I was able to get the table of contents titles to display correctly by changing `node_modules/gatsby-plugin-mdx/dist/remark-infer-toc-meta.js` ([lines 52-54](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/src/remark-infer-toc-meta.ts#L52-L54)) to this:

```js
if (item.type === `text` || item.type === `inlineCode`) {
  if (typedCurrent.title) {
    typedCurrent.title = typedCurrent.title + item.value;
  }
  else {
    typedCurrent.title = item.value;
  }
}
```

### Expected Result

The Table of Contents should show the full heading text for each `h2` in the body of the page.

![Screenshot of the index page. The heading titles in the table of contents match the headings in the body of the page.](https://github.com/meganesu/repro-gatsby-mdx-table-of-contents-with-markdown-formatting/raw/main/screenshot-after.png)

### Actual Result

The Table of Contents shows truncated versions of the headings for each `h2` in the body of the page.

![Screenshot of the index page. The heading titles in the table of contents don't match the headings in the body of the page.](https://github.com/meganesu/repro-gatsby-mdx-table-of-contents-with-markdown-formatting/raw/main/screenshot-before.png)

### Environment

```shell
System:
    OS: macOS 11.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.14.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 9.3.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 109.0.1
    Safari: 14.0.3
  npmPackages:
    gatsby: ^5.7.0 => 5.7.0 
    gatsby-plugin-mdx: ^5.7.0 => 5.7.0 
    gatsby-source-filesystem: ^5.7.0 => 5.7.0 
  npmGlobalPackages:
    gatsby-cli: 3.6.0
```

**Comment by LekoArts** [comment]
Hi Megan, nice to see you and hope you're doing great ❤️ 

Thanks for investigating this, then my gut feeling I wrote about in https://github.com/gatsbyjs/gatsby/discussions/36829 was right.

For anyone who wants to pick this up:

- The code above should be the solution
- To validate the new behavior, add a test case to https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/src/__tests__/remark-infer-toc-meta.ts
- Our instructions for contributing to code are here: https://www.gatsbyjs.com/contributing/code-contributions/
