### ISSUE TITLE
Visited pages load at previous scroll position

### ISSUE THREAD

**Issue by jjenzz** [gatsbyjs/gatsby#3770]
## Description

Clicking back to a page you were previously on via main navigation brings you back to your previous scroll position.

### Environment

Gatsby version: 1.9.169
Node.js version: 7.4.0
Operating System: macOS Sierra 

### File contents (if changed):

`gatsby-config.js`:

```
module.exports = {
	siteMetadata: {
		title: '...',
	},
	plugins: [
		'gatsby-plugin-react-helmet',
		'gatsby-plugin-styled-components',
		{
			resolve: 'gatsby-plugin-typography',
			options: {
				pathToConfigModule: 'src/utils/typography.js',
			},
		},
	],
};
```

`package.json`: 

```
{
  "name": "...",
  "description": "...",
  "version": "1.0.0",
  "author": "...",
  "dependencies": {
    "gatsby": "^1.9.169",
    "gatsby-link": "^1.6.34",
    "gatsby-plugin-react-helmet": "^2.0.3",
    "gatsby-plugin-styled-components": "^2.0.5",
    "gatsby-plugin-typography": "^1.7.12",
    "polished": "^1.9.0",
    "react-helmet": "^5.2.0",
    "react-stickynode": "^1.4.1",
    "styled-components": "^3.0.2"
  },
  "keywords": [
    "gatsby"
  ],
  "main": "n/a",
  "scripts": {
    "build": "gatsby build",
    "start": "gatsby develop",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "babel-eslint": "^7.2.3",
    "eslint": "^4.1.1",
    "eslint-config-react-app": "^2.1.0",
    "eslint-plugin-flowtype": "^2.34.1",
    "eslint-plugin-import": "^2.6.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.1.0",
    "husky": "^0.14.3",
    "lint-staged": "^6.1.0",
    "prettier": "^1.10.2"
  },
  "lint-staged": {
    "*.js": [
      "prettier --config .prettierrc --write",
      "git add"
    ]
  }
}
```

`gatsby-node.js`: not changed
`gatsby-browser.js`: not changed
`gatsby-ssr.js`:  not changes

### Actual result

Visited page loads at previous scroll position.

### Expected behavior

The navigation would take you to the top of the visited page.

### Steps to reproduce

1. On a page that can be scrolled, scroll down and click a button that takes you to another page
2. On the new page, click in the main navigation to go back to the page you were just on

Follow steps to reproduce on the following example website: https://jasper-alexander.netlify.com/

1. Scroll to bottom of homepage
2. Click "Materials" in main nav
3. Click logo to go back to home page

Note you are returned to the bottom of the homepage

**Comment by jjenzz** [comment]
Wow, that was quick :+1: :heart:

**Comment by JMV2112** [comment]
I'm actually still confronting this issue, is anyone else having problems, I'm running v2.
