### ISSUE TITLE
Query was not run and no cached result was found.

### ISSUE THREAD

**Issue by Cris-Xu** [gatsbyjs/gatsby#37716]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi team,

This error is happening when it attempts to build our site via Netlify. Everytime I commit code to develop branch, it will trigger a new building, but it will accoured some error if I dont clear cache and retry with latest branch commit

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/103990501/222324372-223dfd57-d453-4f32-a980-042e700838ad.png">

My project structure about "email-verify/[...]/"

<img width="431" alt="image" src="https://user-images.githubusercontent.com/103990501/222324390-d1195ed3-97b9-437a-8a75-41d72b7370af.png">

### Reproduction Link

https://codesandbox.io/s/zealous-goodall-mdcbpb?file=/src/pages/email-verify/index.jsx

### Steps to Reproduce

1.
2.
3.
...

### Expected Result

Build should work consistently

### Actual Result

Right now we´re unable to build consistently without human assist

### Environment

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM)
i5-8257U CPU @ 1.40GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.1 -
~/.nvm/versions/node/v14.20.1/bin/node
    Yarn: 1.22.19 - ~/WorkSpace/mulpas
s/node_modules/.bin/yarn
    npm: 6.14.17 -
~/.nvm/versions/node/v14.20.1/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 40.0.3
    Safari: 16.3
  npmPackages:
    gatsby: ^4.0.0-zz-next.2 => 4.25.4

    gatsby-plugin-alias-imports:
^1.0.5 => 1.0.5
    gatsby-plugin-env-variables:
^2.1.0 => 2.3.0
    gatsby-plugin-eslint: ^4.0.0 =>
4.0.3
    gatsby-plugin-image: ^1.14.1 =>
1.15.0
    gatsby-plugin-react-helmet:
^4.14.0 => 4.15.0
    gatsby-plugin-sass: ^4.14.0 =>
4.15.0
    gatsby-plugin-sharp: ^3.14.1 =>
3.15.0
    gatsby-source-contentful: ^5.14.0
=> 5.15.0
    gatsby-transformer-remark: ^4.11.0
 => 4.12.0
    gatsby-transformer-sharp: ^3.14.0
=> 3.15.0
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

You're creating your pages incorrectly, you can't have a client-only page and a normal page at the same path. But currently you have two paths:

- /email-verify/index.jsx
- /email-verify/[...].jsx

You need to delete one of them, you can't have a splat route and a normal route at the same path.

Please also see https://www.gatsbyjs.com/docs/how-to/routing/client-only-routes-and-user-authentication/ and https://www.gatsbyjs.com/docs/reference/routing/file-system-route-api/#creating-client-only-routes for more information about that.
