### ISSUE TITLE
Pages scroll past top margin zero when <Link> is clicked

### ISSUE THREAD

**Issue by rogerf76** [gatsbyjs/gatsby#37719]
**Update**
This is not due to using ``createPage()`` to generate content as originally reported. This was just a coincidence.

It is happening because these pages have a margin at the top of the page to create space between the nav bar and the start of the content.

- With a margin at the top of the page, Chrome Desktop will scroll past the margin whenever ``<Link>`` is clicked to navigate to the page. Other browsers, eg Chrome Mobile, Firefox Desktop do not show this behaviour
- Replacing the margin with padding of the same size fixes the issue

---
# Original report

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

On **Chrome Desktop**:

When clicking on a ``<Link>`` to a page that has been created via ``createPage()`` (Eg a blog article or team member profile page) the scroll position on the article page is not set to zesro, It's always scrolled down to the first heading/paragraph in the content.

### Reproduction Link

I've since fixed the issue on the site so the reproduction link does not show the problem anymore.
If you want me to publish a branch that demonstrates the issue please message me.

### Steps to Reproduce

1. Create a page, generated from an .mdx file, using the createPage(...) API
In my case I'm using createPages() in gatsby-node.js per the code below

2. Create a link to the generated page using a ``<Link>`` in another page

3. On Chrome Desktop, when the link is clicked you are navigated to the article page as expected but the article page is always scrolled down to the first heading/text in the content, it's never at scroll position zero

You can see the behaviour using the reproduction link. Just click any of:
- Blog article
- Team member page
- Therapy topic page

These have all been generated using createPage() from .mdx files.
They are the only pages on the site that show the behaviour.

```js
exports.createPages = async ({ graphql, actions, reporter }) => {
    await createTeamPages(graphql, actions, reporter);
}

async function createTeamPages(graphql, actions, reporter) {
  const { createPage } = actions

  const result = await graphql(
    `query {
        allMdx(
          filter: {fields: { source: {eq:"team"}}}
        ) {
          nodes {        
            id
            fields {
              source
            }
            frontmatter {
              slug
            }
            internal {
              contentFilePath
            }
          }
        }
    }`)

  if (result.errors) {
    reporter.panicOnBuild(`Error while running GraphQL query.`)
    return
  }

  const jsTemplate = path.resolve(`src/templates/team-member-template.js`)
  result.data.allMdx.nodes.forEach((node) => {
    createPage({
      path: "/" + node.frontmatter.slug,
      component: `${jsTemplate}?__contentFilePath=${node.internal.contentFilePath}`,
      context: { 
        id: node.id,
        slug: node.frontmatter.slug
      } 
    })
  })
}
```

### Expected Result

Scroll behaviour is the same as all other links and pages - Always scrolls to position zero when clicking a link

### Actual Result

Page is always scrolled down to first item of content/text on the page

### Environment

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.18.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1344.0), Chromium (110.0.1587.57)
  npmPackages:
    gatsby: ^5.2.0 => 5.2.0 
    gatsby-plugin-image: ^3.2.0 => 3.2.0 
    gatsby-plugin-manifest: ^5.2.0 => 5.2.0 
    gatsby-plugin-mdx: ^5.2.0 => 5.2.0 
    gatsby-plugin-mdx-source-name: ^1.0.1 => 1.0.1 
    gatsby-plugin-netlify: ^5.1.0 => 5.1.0 
    gatsby-plugin-postcss: ^6.2.0 => 6.2.0 
    gatsby-plugin-sharp: ^5.2.0 => 5.2.0 
    gatsby-plugin-sitemap: ^6.2.0 => 6.2.0 
    gatsby-remark-images: ^7.2.0 => 7.2.0 
    gatsby-source-filesystem: ^5.2.0 => 5.2.0 
    gatsby-transformer-sharp: ^5.2.0 => 5.2.0 
  npmGlobalPackages:
    gatsby-cli: 5.2.0
```

### Config Flags

(No flags set)

**Comment by rogerf76** [comment]
**Update**
This is not due to using ``createPage()`` to generate content as originally reported. This was just a coincidence.

It is happening because these pages have a margin at the top of the page to create space between the nav bar and the start of the content.

- With a margin at the top of the page, Chrome Desktop will scroll past the margin whenever ``<Link>`` is clicked to navigate to the page. Other browsers, eg Chrome Mobile, Firefox Desktop do not show this behaviour
- Replacing the margin with padding of the same size fixes the issue

**Comment by LekoArts** [comment]
Hi!

I'm not really following your issue here. If you can't share a reproduction since you fixed it in your site, is it then an actual bug in Gatsby? Can we close this?

**Comment by rogerf76** [comment]
Hi thanks for responding,

I originally reported this as an issue in ``createPage()`` but further testing showed it was not due to ``createPage()``.
The issue is due to the use of **margin** (problematic) vs **padding** (works).

I was using a margin (not padding) on the first ``<div/>`` in a page to create space at the top of the page (for a floating nav bar).

Steps to reproduce: 
- On "Page A" use a **margin** instead of **padding** on the first ``<div/>`` to create a large space at the top of the page
- On "Page B" use a Gatsby ``<Link/>`` to create a link to "Page A"
- On "Page B" when the Link to "Page A" is clicked, "Page A" containing the **margin** will appear and be scrolled down by the margin amount. The margin is scrolled off screen and the start of the ``<div/>`` contents appear at the very top of the screen

This only happens with Gatsby ``<Link/>``, and only on Chrome desktop (doesn't happen on eg Firefox desktop, doesn't happen on Chrome mobile)

It doesn't happen when a normal ``<a/>`` anchor is used

**Resolution/Fix/Workaround**
Use **padding** to create the space, not **margin**.
When padding is used the page is not scrolled down.

**Comment by MonPote** [comment]
Thanks @rogerf76 for the workaround !
