### ISSUE TITLE
valid-url@1.0.9 - No license specified

### ISSUE THREAD

**Issue by xSyki** [gatsbyjs/gatsby#37722]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

The license scanner throws an error on the valid-url library, because in version 1.0.9, there is no MIT license specified. From what I can see it is defined in the repository, but they probably haven't released a version yet. From what I read the library is not trustworthy and has many bugs. In gatsby it is used in two plugins gatsby-source-wordpress and gatsby-source-filesystem. It's used to check the url three times, so replacing it shouldn't be a problem. Suggest to replace it or remove it and use new Url api.

### Reproduction Link

https://github.com/gatsbyjs/gatsby

### Steps to Reproduce

1. Check valid-url 1.0.9 package.json

### Expected Result

valid-url has a license in package.json

### Actual Result

No license in package.json in valid-url version 1.0.9

### Environment

```shell
The environment doesn't matter
```

**Comment by LekoArts** [comment]
It's only used for the `isWebUri` function in here:

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-filesystem/src/create-remote-file-node.js#L138

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js#L330

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js#L773

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-remote-file-node/index.js#L428

It currently checks:

> is the value a well-formed HTTP or HTTPS uri?

Feel free to replace it with something built-in like the `URL` constructor. You can use the `checkUrl` function from https://snyk.io/blog/secure-javascript-url-validation/ and add a utility function to https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-core-utils/src

Then add unit tests to validate that the old behavior shown in https://github.com/ogt/valid-url/blob/master/test/is_web_uri.js is still given.

**Comment by xSyki** [comment]
@LekoArts Thanks for the quick reply. I will gladly take this task, I will take care of it today.

**Comment by xSyki** [comment]
@LekoArts  Pull request submitted, but I may need your help with the version release.
