### ISSUE TITLE
DOM ids not working when using Algolia npm package "react-instantsearch-hooks-web"

### ISSUE THREAD

**Issue by MS3300studios** [gatsbyjs/gatsby#37746]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When component InstantSearch from the npm package "react-instantsearch-hooks-web" is rendered by the Gatsby app, the links in the app break, as they don't support the deafult HTML behaviour, because the links don't go to appropriate sections.
For example: 
example.com/about/#contact 
will simply take us to the /about page, but not to the div with id="contact" on that page.
Also, when a user clicks on a link in the middle of the page (his scroll position being in the middle of the page) they will go to that link, and if they go "back" they will be on the top of the previous page, and not taken back to their previous scroll position. 
So somehow this package must overwrite the default HTML behaviour. I am wondering whether Gatsby is loading the content too slowly with that package... 
Does anyone have any suggestions as to what could cause this problem, and how to fix it? 
I already wrote to Algolia support but they weren't able to reproduce this problem

### Reproduction Link

https://mf11successdev.z4.web.core.windows.net/

## 1st bug:
1. Go to the "Invoice to Pay" (top right corner) card, and press the AP Automation arrow.
2. On the content tree on the left side go to Coding (Under Expense Invoice).
3. In the Coding article scroll down until you see the FetchResponsibleUserPerspective link (you can find it using ctrl+F)
4. Go to the link
5. Press the back button, and you'll be taken to the top of the page, whereas in the working solution you'd be taken to your previous scroll position (where the link was visible)
## 2nd bug:
1. Go to link: https://mf11successdev.z4.web.core.windows.net/documentation/user_guide/expense_invoice/coding/#validating-and-correcting-coding
2. You will be at the top of the article, whereas in the working solution you should be at the #validating-and-correcting-coding input

If you want to see how it should look correctly, go to success.medius.com, there you'll be able to reproduce these steps, but instead everything will be working and you'll be taken to the correct place.

### Expected Result

1st bug: you should be taken to your previous scroll position
2nd bug: You should be taken to the div with the id from the link

### Actual Result

1st bug: You are taken to the top of the page
2nd bug: You are taken to the top of the page

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.18.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.10.5
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.69)
  npmPackages:
    gatsby: 4.24.4 => 4.24.4
    gatsby-cli: 4.24.0 => 4.24.0
    gatsby-plugin-catch-links: 4.24.0 => 4.24.0
    gatsby-plugin-eslint: 4.0.2 => 4.0.2
    gatsby-plugin-google-fonts: 1.0.1 => 1.0.1
    gatsby-plugin-google-tagmanager: 4.24.0 => 4.24.0
    gatsby-plugin-manifest: 4.24.0 => 4.24.0
    gatsby-plugin-offline: 5.24.0 => 5.24.0
    gatsby-plugin-react-helmet: 5.24.0 => 5.24.0
    gatsby-plugin-robots-txt: 1.7.1 => 1.7.1
    gatsby-plugin-sitemap: 5.24.0 => 5.24.0
    gatsby-plugin-styled-components: 5.24.0 => 5.24.0
    gatsby-plugin-typescript: 4.24.0 => 4.24.0
    gatsby-react-router-scroll: 5.24.0 => 5.24.0
    gatsby-source-filesystem: 4.24.0 => 4.24.0
    gatsby-transformer-json: 4.24.0 => 4.24.0
```

**Comment by Jejebecarte** [comment]
Just saw this floating around - I wasn't able to reproduce either bug. Both worked as intended for me.

Given this, I don't think the issue in Gatsby, though I'm not sure. Perhaps try a hard refresh?

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by MS3300studios** [comment]
Hi, I've been doing a bit of digging, and it was the fault of the Algolia react-instantsearch-hooks-web package. Somehow it breaks the default gatsby-react-router-scroll package, that handles scroll positions in Gatsby apps. For future reference, I fixed this bug by wrapping only the searchbox and resultscard components, and not the entire app. If you wrap the entire app inside of the InstantSearch component, it's going to break the scroll package. 
Now that I have the solution, I will close this issue, I hope others who also use Algolia with Gatsby will find this solution helpful.
