### ISSUE TITLE
Using an iframe shows a 404 error

### ISSUE THREAD

**Issue by monsieurnebo** [gatsbyjs/gatsby#3776]
# Dependencies
All my Gatsby packages are up-to-date.

# Context
I'm using an `iframe` in the homepage of my Gatsby's website, displaying a hardcoded HTML file (yep, that's ugly as hell but I have no other choice ATM). 

This HTML page is imported from my React component:

```jsx
import iframe from "iframe/index.html";

// ...

render() {
  return <iframe src={iframe} />;
}
```

Using the `url-loader` to handle the HTML file in webpack.

# Problem
When loading the homepage as the entry point of the website, the iframe is working fine.

But in some other cases, the iframe shows a 404 error along the following message in the console:

```
loader.js:136 | A page wasn't found for "/static/iframe/index.01a6d7f1.html"
```

It seems pretty random but I sounds like the issue is fired when:
- Refreshing the page
- Accessing the page from another one via `gatsby-link` (component and programmatic)

The last observation is that doesn't happen on `gatsby develop`, but on the real build.
 
---

**I just cannot find anything about this bug on the web and I'm wondering if it could be related to Gatsby in any way?**

**Comment by monsieurnebo** [comment]
I managed to get ride of this crappy iframe in the meantime. 

But for future debugging: what is the main purpose of `loader.js` ?

**Comment by KyleAMathews** [comment]
>But for future debugging: what is the main purpose of loader.js ?

It coordinates loading resources for pages — code & data bundles (maybe more resources in the future)

**Comment by monsieurnebo** [comment]
Ok, thanks !
