### ISSUE TITLE
while `createPage` with `...?__contentFilePath` does not work with the class component

### ISSUE THREAD

**Issue by lesomnus** [gatsbyjs/gatsby#37777]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I tried to render `.mdx` with layout.
```ts
...
		createPage({
			path: resolveContentPath(contentFilePath),
			component: `${post_template_path}?__contentFilePath=${contentFilePath}`,
			context: {
				id: node.id,
			},
			 
		})
...
```

First my layout was defined by class componenet but it doesn't work.
The `this.props.children` was `undefined`.
```ts
export default class Layout extends React.Component<Props> {
	constructor(props: Props) {
		super(props)
		asdf = JSON.stringify(props.children)
	}

	render(): React.ReactNode {
		// this.props.children === undefined
		...
	}
}
```

It works if I use functional component.
```ts
export default function Layout(props: Props) {
	// props.children !== undefined
	...
}
```

I really want to make a reproduction but the link does not work (both CodeSandbox and StackBlitz), sorry.
I already spent 3 hours to figure it out the problem so im tired.

### Reproduction Link

https://not-working

### Steps to Reproduce

1. `export default class Layout extends React.Component ...`

### Expected Result

`this.props.children` must be rendred `.mdx` nodes.

### Actual Result

`this.props.children`  was `undefined`.

### Environment

```shell
System:
    OS: Linux 5.19 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
  npmPackages:
    gatsby: ^5.8.0 => 5.8.0
    gatsby-plugin-image: ^3.7.0 => 3.8.0
    gatsby-plugin-mdx: ^5.8.0 => 5.8.0
    gatsby-plugin-postcss: ^6.7.0 => 6.8.0
    gatsby-plugin-sass: ^6.7.0 => 6.8.0
    gatsby-plugin-sharp: ^5.8.0 => 5.8.0
    gatsby-source-filesystem: ^5.8.0 => 5.8.0
    gatsby-transformer-sharp: ^5.8.0 => 5.8.0
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. Please create a [minimal reproduction][reproduction]. I've tried the `using-mdx` example locally with a class component and it all works for me.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by krischer** [comment]
Hi all,

I encounter the same issue and created a minimal reproducible example here:

https://github.com/krischer/gatsby-mdx-bug-minimal

The template contains a functional component that works as expected:

https://github.com/krischer/gatsby-mdx-bug-minimal/blob/f1538617b42e919bdb8eae9e4a44a2ac89e1c6d6/src/templates/template.tsx#L10-L15

And a class based component that has undefined children:

https://github.com/krischer/gatsby-mdx-bug-minimal/blob/f1538617b42e919bdb8eae9e4a44a2ac89e1c6d6/src/templates/template.tsx#L17-L25

The example page can be found at `/trial`.

Please let me know if you'd like me to open a new issue instead.

**Comment by lesomnus** [comment]
@krischer Thanks for the example. But I don't use Gatsby anymore so I don't need any fix... You can open new issue if you want to.
