### ISSUE TITLE
How to build Gatsby without minifying ?

### ISSUE THREAD

**Issue by sidzan** [gatsbyjs/gatsby#3778]
I ran into some classic issue of HTML minification i.e Uncaught Error: Minified React error #32; and seems to be with Gatasby not related with any CDN ( how - > cause i tried to build it in my local and serve and i get the same issue ).

I am currently seeking any way to deploy it without minifying (with out production env), is there any way to do this ? Any suggestion is much appreciated .

here you can see the issue https://ariamerican-53d2e.firebaseapp.com/

EDIT:
I only have issue with carousel , tried 3 different carousel including the popular react-slick , has anoyone ran into this issue and found a fix ?

**Comment by calcsam** [comment]
No, this is not possible currently.

**Comment by rilexus** [comment]
I have one related issue!
After building the project, my animation are not triggered. Any other styles are applied correctly. In development everything is fine. 
I use "emotion" styled component and the "react-transition-group"(CSSTransition) for the animation. 
How ever! When i **un-minify the relalated html file** after build, all animation are triggered correctly.

**Comment by dennisapdm88** [comment]
> No, this is not possible currently.

is this available now? unminify js files when gatsby build.>??

**Comment by AlexLeung** [comment]
If you can't minify this can lead to near impossible to resolve issues https://stackoverflow.com/questions/68050244/unexpected-escaping-special-characters-with-may-help-angular-12-build-d
