### ISSUE TITLE
chore(docs): GitHub link on gatsby-plugin-preview docs points to page Not Found (404)

### ISSUE THREAD

**Issue by benomatis** [gatsbyjs/gatsby#37797]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

On the [`gatsby-plugin-preview` plugin documentation page](https://www.gatsbyjs.com/plugins/@gatsby-cloud-pkg/gatsby-plugin-preview/) the link behind [`View plugin on GitHub`](https://github.com/gatsby-inc/gatsby-plugin-preview) points to https://github.com/gatsby-inc/gatsby-plugin-preview, which doesn't exist.

### Steps to Resolve this Issue

1. Go to https://www.gatsbyjs.com/plugins/@gatsby-cloud-pkg/gatsby-plugin-preview/
2. Click [`View plugin on GitHub`](https://github.com/gatsby-inc/gatsby-plugin-preview) - observe the page doesn't exist

**Comment by LekoArts** [comment]
Hi!

This is an internal plugin for now, so that the link doesn't work is expected for now. You don't need to use this plugin though as it'll gets automatically installed on Gatsby Cloud if necessary.

**Comment by benomatis** [comment]
@LekoArts on that note, and sorry for being a little offtopic, do you know if there are any plans making the api (or part of it) public? I have posted [a question about it in discussions](https://github.com/gatsbyjs/gatsby/discussions/37798), but I wasn't sure it was the right place, so moved to [the netlify forums](https://answers.netlify.com/t/gatsby-cloud-api-eg-build-status/88884), but that doesn't appear to be very popuplar ([no topics in Gatsby Cloud category](https://answers.netlify.com/c/gatsbycloud/62)), so not sure if I'll get an answer... Would you recommend a better place for such a question...?

**Comment by LekoArts** [comment]
The Netlify forums is the correct place for this, yes 👍 Unfortunately I'm not able to answer your question though.

**Comment by benomatis** [comment]
@LekoArts Thank you.
