### ISSUE TITLE
Unable to use pluginOptionsSchema when using remark plugins in gatsby-plugin-mdx

### ISSUE THREAD

**Issue by Talaxy009** [gatsbyjs/gatsby#37792]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I am try to using a remark plugins in gatsby-plugin-mdx, and I found the `pluginOptionsSchema` in gatsby-node.js of remark plugins won't run.

I have create a repo which is base on using-mdx example and add a local remark plugin in it to reproduce this issue, you can find the link below. As you can see, no `test` string is output and no default options are defined.

![image](https://user-images.githubusercontent.com/41264828/228251160-bc3993eb-bea8-4a91-a219-d7f9056aec7b.png)

### Reproduction Link

https://github.com/Talaxy009/gatsby-test

### Steps to Reproduce

1. Clone Reproduction Link
2. Install dependencies
3. Run gatsby develop

### Expected Result

The output should be: 

```
plugin init
test
plugin run
{ plugins: [], ping: 'Hello', test: 'Can you see me?' }
```
or

```
test
plugin init
plugin run
{ plugins: [], ping: 'Hello', test: 'Can you see me?' }
```

### Actual Result

The actural output is: 

```
plugin init
plugin run
{ plugins: [], ping: 'Hello' }
```

### Environment

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz
  Binaries:
    Node: 18.12.1 - ~\AppData\Local\Temp\xfs-bb0e7540\node.CMD
    Yarn: 3.4.1 - ~\AppData\Local\Temp\xfs-bb0e7540\yarn.CMD
    npm: 8.19.2 - D:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.10.6
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (111.0.1661.54)
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

This should work, so it's a bug. We do subPlugin validation here but it checks for the `plugins` key, not `gatsbyRemarkPlugins`, too.

https://github.com/gatsbyjs/gatsby/blob/35b23399e0af9f18f5c01d3d7a8a0321b436210c/packages/gatsby/src/bootstrap/load-plugins/validate.ts#L367-L379

**Comment by Talaxy009** [comment]
Thanks for your reply, I would like to take some time to read the code you provided and try to fix this bug.
