### ISSUE TITLE
[Question] Redirecting a path to different domain?

### ISSUE THREAD

**Issue by youmustfight** [gatsbyjs/gatsby#3782]
## Question

Is there a way to create a redirect for external domain? `createRedirect` works for pushing a user just from path to path. I'm looking for:

`myservice.com/doiqualify` -> `https://myservice.typeform.com/qw/2i42ori`

I noticed createRedirect just appends the url to the root like `myservice.com/https://myservice.typeform...`

## My environment

Deploying to S3 bucket and using Cloudfront (using Route 53 if that matters)

## How I'm Doing It Now

I have a redirect template that's blank which runs some javascript checking for the path and then assigns a new URL.

_Snippet from my gatsby-node.js_
```
  // Create Redirect Pages....
  const redirectPage = path.resolve("src/templates/redirect.jsx");
  redirectsBatch.forEach(({ from }) => {
    createPage({
      path: from,
      component: redirectPage,
    });
  });
```

_code snippet in the `redirect.jsx` template that cycles through the same redirect JSON and assigns the new href_
```
...
    redirectBatch.forEach((re) => {
      if (window.location.pathname.includes(re.from)) window.location.href = re.to;
    });
...
```

## Should I be doing it that way?

This feels a little wonky, so I'm not sure if this is the right way to go about it. Is there an method or plugin I should be using instead?

**Comment by KyleAMathews** [comment]
Hmmm this looks like a bug. I'm not sure we considered redirecting to other domains when designing the `createRedirect` API. Could you look into creating a PR with a fix?

**Comment by youmustfight** [comment]
Sure thing! 👍

**Comment by carsonkk** [comment]
Needed exactly this functionality of having an internal path redirect to some other domain, cool trick @youmustfight 

Was a PR ever submitted for this?

**Comment by oskareke** [comment]
+1 Would be neat if createRedirect worked for external urls as well. Neither window.location.replace(url) or window.location = url works for me on Netlify for some reason...

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by harrysolovay** [comment]
I'd love for this issue to be reopened please––it would be great if `createRedirect` could handle external redirects.

**Comment by slorber** [comment]
For anyone interested to redirect with wildcard, you just need to ensure you have the correct host config (netlify/apache. Gatsby does not really filter it out so it gives us some freedom.


For example:

```
createRedirect({
  fromPath: "/someLegacyPath/*",
  toPath: "https://newDomain.com/someLegacyPath/:splat",
})
```

`:splat` is something specific for Netlify redirects. (see https://www.netlify.com/docs/redirects/#splats)
Your redirect won't be "portable" but at least it will work in Netlify.

**Comment by shariqanwar20** [comment]
I am using **gatsby with aws services**. I have implemented **Cognito** authentication and in order to use the UI provided by cognito, I have to **redirect the user to an external url** when I click on **SignUp/Login** button. Is there a way to redirect the user to external url ?

### My Environment
Frontend on Gatsby. Deployment on S3 Bucket. Cognito Authentication without AWS amplify

       ` <NavLink
            as={Button}
            onClick={() => {
              !userData.userToken
                ? (window.location.href = `${config.domainUrl}/login?client_id=${config.clientId}&response_type=code&scope=email+openid&redirect_uri=${config.loginRedirectUri}`)
                : (() => {
                  window.location.href = `${config.domainUrl}/logout?client_id=${config.clientId}&logout_uri=${config.logoutUri}`;
                  sessionStorage.clear();
                });
            }}
          >
    <NavLink  />`

### Error I am recieving when building gatsby project
![Screenshot from 2021-03-11 16-40-07](https://user-images.githubusercontent.com/61353122/110782145-99a7b480-8288-11eb-977a-f7019ccb2805.png)



### Repository Link
[https://github.com/shariqanwar20/Todo-App-With-AWS](url)

**Comment by kmatthews812** [comment]
Has anybody figured out how to accomplish what @slorber's Netlify solution does but do so on Gatsby Cloud? Unfortunately, I share his problem but his solution doesn't work on Gatsby Cloud.

**Comment by socmov** [comment]
@kmatthews812 did you ever figure out how to do a redirect on Gatsby cloud?
