### ISSUE TITLE
Build error after upgrade from V1 to latest

### ISSUE THREAD

**Issue by vishalniit** [gatsbyjs/gatsby#3784]
## Description

Describe the issue or the enhancement that you want to see.

### Environment

Gatsby version: Latest
Node.js version: 8.9.4
Operating System: Windows 10

### File contents (if changed):

`gatsby-config.js`: 
`package.json`: 
`gatsby-node.js`: 
`gatsby-browser.js`: 
`gatsby-ssr.js`: 

### Actual result
**Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  28 |         <WindowResizeListener onResize={this.resizeHandler} />
  29 |         <Carousel indicators pauseOnHover>
> 30 |           {carouselpara.map((item, i) => {
     |                         ^
  31 |             if (view == "desktop") {
  32 |               return (
  33 |                 <Carousel.Item key={i}>

  WebpackError: Cannot read property 'map' of null

  - CarouselComponent.js:30 CarouselComponent.render
    src/components/Composite/Carousel/CarouselComponent.js:30:25

  - ReactCompositeComponent.js:799 ReactCompositeComponentWrapper._renderValidatedComponentWithou    tOwnerOrContext
    ~/react-dom/lib/ReactCompositeComponent.js:799:1

  - ReactCompositeComponent.js:822 ReactCompositeComponentWrapper._renderValidatedComponent
    ~/react-dom/lib/ReactCompositeComponent.js:822:1

  - ReactCompositeComponent.js:362 ReactCompositeComponentWrapper.performInitialMount
    ~/react-dom/lib/ReactCompositeComponent.js:362:1

  - ReactCompositeComponent.js:258 ReactCompositeComponentWrapper.mountComponent
    ~/react-dom/lib/ReactCompositeComponent.js:258:1

  - ReactReconciler.js:46 Object.mountComponent
    ~/react-dom/lib/ReactReconciler.js:46:1

  - ReactMultiChild.js:238 ReactDOMComponent.mountChildren
    ~/react-dom/lib/ReactMultiChild.js:238:1

  - ReactDOMComponent.js:653 ReactDOMComponent._createContentMarkup
    ~/react-dom/lib/ReactDOMComponent.js:653:1

  - ReactDOMComponent.js:520 ReactDOMComponent.mountComponent
    ~/react-dom/lib/ReactDOMComponent.js:520:1

  - ReactReconciler.js:46 Object.mountComponent
    ~/react-dom/lib/ReactReconciler.js:46:1**
What happened.

### Expected behavior
if run using develop should be able to see localhost
What should happen?
It should be able to build successfully.
### Steps to reproduce

1\.  Go to https://github.com/MindtreePGSSG/ModernWeb this is private so intended for Kyle

2\. setup code & pacakges

3\. run gatsby build

...

**Comment by MaralS** [comment]
@vishalniit the link to the GitHub repository leads to a 404 page :)

**Comment by KyleAMathews** [comment]
@vishalniit what's `carouselpara`? Could you trace that back some more to narrow down what the source of the problem is? E.g. is it missing data from a GraphQL query? A missing import?
