### ISSUE TITLE
Latest version of Gatspy Wordpress Plugin fails to build on Netlify

### ISSUE THREAD

**Issue by craig-doyle-uk** [gatsbyjs/gatsby#3787]
## Description

When I run or build my site locally everything works correctly but when I deploy to Netlify, the latest version of all of the plugins are used and it has been failing to build since last Friday with the following error :  

     TypeError: createNodeId is not a function
   
    - normalize.js:170 
    [repo]/[gatsby-source-wordpress]/normalize.js:170:12
  
     - Array.map
   
     - normalize.js:169 Object.exports.createGatsbyIds
    [repo]/[gatsby-source-wordpress]/normalize.js:169:19
  
     - gatsby-node.js:102 _callee$
     [repo]/[gatsby-source-wordpress]/gatsby-node.js:102:34
 
     - next_tick.js:73 _combinedTickCallback
     internal/process/next_tick.js:73:7
 
     - next_tick.js:104 process._tickCallback
      internal/process/next_tick.js:104:9

When I specify version **2.0.37** of the Gatsby Wordpress plugin in package.json everything builds correctly on Netlify.

My package.json now reads as follows and everything works correctly.

    "gatsby": "^1.9.145",
    "gatsby-image": "^1.0.31",
    "gatsby-link": "^1.6.32",
    "gatsby-plugin-react-helmet": "^1.0.8",
    "gatsby-plugin-sass": "^1.0.14",
    "gatsby-plugin-sharp": "^1.6.22",
    "gatsby-source-wordpress": "2.0.37",
    "gatsby-transformer-sharp": "^1.6.15",

**Comment by pieh** [comment]
Try to update gatsby, updated wordpress plugin relies on functionality added to gatsby in 1.9.167

**Comment by craig-doyle-uk** [comment]
Excellent, thanks @pieh , I'm not sure why Netlify was using the latest version of the WP plugin but not using the latest version of Gatsby itself. Once changed to `"gatsby": "^1.9.167",` everything builds correctly.
