### ISSUE TITLE
gatsby new project-name . creates infinite folders if terminated using CTRL+C

### ISSUE THREAD

**Issue by daas-ankur-shukla** [gatsbyjs/gatsby#3789]
## Description

While creating a new gatsby project I used a dot after the `gatsby new project-name` command, thinking that dot will make gatsby create the project within my parent directory (similar to some python packages). 
When the command started creating the project i noticed that it was creating a directory named homepage inside my current directory. So I terminate the process by using CTRL+C twice. 
This created infinite folder tree inside my working directory. 

### Environment

Gatsby version: 1.1.33
Node.js version: 8.9.1
Operating System: Windows 10

### File contents (if changed): 

Not Changed

### Actual result

```
E:\GitHub\homepage>gatsby new homepage .
info Creating new site from local starter: .
Copying local starter to homepage ...
^CTerminate batch job (Y/N)?
^C
E:\GitHub\homepage>
```
This resulted in a infinite folder tree as `E:\GitHub\homepage\homepage\homepage\homepage\homepage\homepage\homepage\homepage\homepage\homepage\homepage\...`

Each folder contained all the files in the parent directory `E:\GitHub\homepage\`

### Expected behavior

I was expecting the batch job to terminate normally.

### Steps to reproduce

1\. gatsby new project-name . 
`the dot at the end is significant`

2\. Press CTRL+C when the following line appear `Copying local starter to project-name ...` and then press Y to terminate the batch job.

Apologies if I am creating a redundant or improper issue

**Comment by KyleAMathews** [comment]
Thanks for the bug report! Added a new validation that prevents people from trying to creating a starter in the same directory as the path to the source.

**Comment by daas-ankur-shukla** [comment]
Welcome. Thanks for the quick patch :)
