### ISSUE TITLE
Fail in cleaner fashion if user runs gatsby develop in a non-gatsby directory

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#379]
Right now it complains about their not being a local gatsby install and throws out a bunch of cryptic errors and then quits. I was helping a friend setup Gatsby and they got stuck for a bit as they hadn't entered the new gatsby directory after running `gatsby new`.

It's now been ~6 months since we added support for Gatsby being a local install. I think at the next minor version we should enforce this and not run gatsby develop/build unless gatsby can find itself (haha) in node_modules.

**Comment by nason** [comment]
Hi @KyleAMathews, I'm going to take this one too if that's alright with you.

I'm thinking adding a check towards the top of `lib/bin/cli.js`, before I get too far I could use a little input on what the signal(s) for being in a valid gatsby directory should be. For example:

- Do you still want to support a globally installed `gatsby` package or is a local install required? 
- Should anything besides is `gatsby` in `node_modules` be considered?

**Comment by KyleAMathews** [comment]
Hey great! Yeah disable global install working at all. An html.js is
required and I think config.toml might be required (though it should be
optional). There's a few other required files e.g. _template.js and an
index.* in the pages directory.

**Comment by vinnymac** [comment]
@nason @KyleAMathews I was actually creating this exact ticket when I discovered that one already existed. May I recommend that we use [this](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-dev-utils/checkRequiredFiles.js) to provide some good UX around telling the user what files gatsby needs in order to be used properly. We should make sure it works well across various gatsby commands. What do you think?

**Comment by KyleAMathews** [comment]
@vinnymac that function looks perfect! CRA does it again 😀 they're our UX design agency basically.

@nason what's the status on your PR for this?

We can reuse the same pattern in 1.0 but with a different list of required files.

**Comment by nason** [comment]
@vinnymac thanks! CRA is great inspiration. it was super simple to drop-in that module and replace the one I had started on.

@KyleAMathews sorry last week got a bit busy for me! I opened PR https://github.com/gatsbyjs/gatsby/pull/583, let's chat about it there

**Comment by jbolda** [comment]
The related PRs have been closed already. Closing this.

**Comment by whmountains** [comment]
If this is done can we move it to the "done" section on the roadmap?
