### ISSUE TITLE
The result of this StaticQuery could not be fetched.\n\n

### ISSUE THREAD

**Issue by marketingsolution** [gatsbyjs/gatsby#37917]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Build on gatsby cloud fail for some unknown reason. On my local machine it works just fine, this page is displaying ok.
Building static HTML for pages
Truncated page data information for the failed page /news/21-dni-bmw-motorrad-2023-pure&crafted-festiwal/:

https://build-e7d78a58-df82-4608-9e88-8bc5591e0e77.gatsbyjs.io/news/21-dni-bmw-motorrad-2023-pure&crafted-festiwal/

return context[query].data
  82 |   } else {
> 83 |     throw new Error(
     |           ^
  84 |       `The result of this StaticQuery could not be fetched.\n\n` +
  85 |         `This is likely a bug in Gatsby and if refreshing the page does not fix it, ` +
  86 |         `please open an issue in https://github.com/gatsbyjs/gatsby/issues`

### Reproduction Link

https://github.com/marketingsolution/MotoTripsPL

### Steps to Reproduce

1. comit 
2. gatsby cloud build throw an error
3.it works fine on local build

### Expected Result

build in gatsby cloud works as on localhost

### Actual Result

return context[query].data
  82 |   } else {
> 83 |     throw new Error(
     |           ^
  84 |       `The result of this StaticQuery could not be fetched.\n\n` +
  85 |         `This is likely a bug in Gatsby and if refreshing the page does not fix it, ` +
  86 |         `please open an issue in https://github.com/gatsbyjs/gatsby/issues`

### Environment

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.10.6 - /c/Python310/python
  Browsers:
    Edge: Spartan (44.22621.1485.0), Chromium (111.0.1661.62)
  npmPackages:
    gatsby: ^5.8.0 => 5.8.0
    gatsby-plugin-disqus: ^1.2.4 => 1.2.4
    gatsby-plugin-google-tagmanager: ^5.8.0 => 5.8.0
    gatsby-plugin-image: ^3.8.0 => 3.8.0
    gatsby-plugin-manifest: ^5.8.0 => 5.8.0
    gatsby-plugin-mdx: ^5.8.0 => 5.8.0
    gatsby-plugin-offline: ^6.8.0 => 6.8.0
    gatsby-plugin-react-helmet: ^6.8.0 => 6.8.0
    gatsby-plugin-sharp: ^5.8.0 => 5.8.0
    gatsby-plugin-sitemap: ^6.8.0 => 6.8.0
    gatsby-plugin-styled-components: ^6.8.0 => 6.8.0
    gatsby-remark-autolink-headers: ^6.8.0 => 6.8.0
    gatsby-remark-images: ^7.8.0 => 7.8.0
    gatsby-source-filesystem: ^5.8.0 => 5.8.0
    gatsby-source-wordpress: ^7.8.0 => 7.8.0
    gatsby-transformer-remark: ^6.8.0 => 6.8.0
    gatsby-transformer-sharp: ^5.8.0 => 5.8.0
  npmGlobalPackages:
    gatsby-cli: 5.8.0
    gatsby-plugin-recaptcha: 1.0.5
    gatsby-starter-default: 0.1.0
```

**Comment by LekoArts** [comment]
Hi!

For Gatsby Cloud related issues please use the contact form in the top right of the interface. Thanks!
