### ISSUE TITLE
gatsby-source-mongodb - Intermittent error when sourcing from 2 views from based on same collection

### ISSUE THREAD

**Issue by djavco** [gatsbyjs/gatsby#37915]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

We are using the plugin to source mongodb views that are pulling data from the same collection.

There is an intermittent error that only happens for the odd node. The node initially appears to exist but when we pass the id of this node to a query in a template from gatsby-node the data does not exist.

If we do a gatsby clean, the node will not necessarily be found. After a few builds it may partially re-appear again.

Very occasionally the template query will run successfully and the page will build.

I'm aware that we are using views rather than collections, but my understanding was that they are ostensibly the same to the outside world.

This is the error we get on Gatsby cloud:
```
Building static HTML for pages
2.92s
Truncated page data information for the failed page
```

The odd thing is that if I remove the collection from the array of collections in the the config for 'gatsby-source-mongo' - all the data behaves.

This has intermittent errors:

```
    {
      resolve: `gatsby-source-mongodb`,
      options: {
        dbName: process.env.MONGODB_DB,
        collection: [`viewOne`, `viewOneVariant`, `viewTwo`],
        server: {
          address: process.env.MONGODB_ADDRESS,
          port: process.env.MONGODB_PORT,
        },
        auth: {
          user: process.env.MONGODB_USER,
          password: process.env.MONGODB_PASS,
        },
        preserveObjectIds: `true`,
      },
    },
```

This has many errors with fields missing from `viewTwo`:

```


    {
      resolve: `gatsby-source-mongodb`,
      options: {
        dbName: process.env.MONGODB_DB,
        collection: [`CollectionOne`, `viewOne`, `viewOneVariant`, `viewTwo`],
        server: {
          address: process.env.MONGODB_ADDRESS,
          port: process.env.MONGODB_PORT,
        },
        auth: {
          user: process.env.MONGODB_USER,
          password: process.env.MONGODB_PASS,
        },
        preserveObjectIds: `true`,
      },
    },
```

This works and I reliably get all the data:
```
    {
      resolve: `gatsby-source-mongodb`,
      options: {
        dbName: process.env.MONGODB_DB,
        collection: [`viewOne`, `viewTwo`],
        server: {
          address: process.env.MONGODB_ADDRESS,
          port: process.env.MONGODB_PORT,
        },
        auth: {
          user: process.env.MONGODB_USER,
          password: process.env.MONGODB_PASS,
        },
        preserveObjectIds: `true`,
      },
    },
```

### Reproduction Link
NOTE: THIS REPO WILL NOT WORK AS CANNOT MAKE PUBLIC
https://github.com/MTJ-io/mongo-source-error

### Steps to Reproduce

1. Add mongodb source plugin and configure mongoDb source plugin
2. Configure source plugin collections with one collection and two or three views that source from the same collection
2. Run gatsby build
...

### Expected Result

All data should be reliably sourced

### Actual Result

Intermittent error whereby the same node is only partially retrieved.

In gatsby-node.js the id of this node is available - when creating a page with a query in a template the data is not available.
```
Building static HTML for pages
2.92s
Truncated page data information for the failed page
```

### Environment

```shell
System:
    OS: macOS 13.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.1.0 - ~/.nvm/versions/node/v18.1.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.8.0 - ~/.nvm/versions/node/v18.1.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Firefox: 109.0.1
    Safari: 16.2
  npmPackages:
    gatsby: ^5.5.0 => 5.5.0
    gatsby-plugin-algolia: ^1.0.3 => 1.0.3
    gatsby-plugin-google-analytics: ^5.5.0 => 5.5.0
    gatsby-plugin-image: ^3.5.0 => 3.5.0
    gatsby-plugin-manifest: ^5.5.0 => 5.5.0
    gatsby-plugin-sass: ^6.5.0 => 6.5.0
    gatsby-plugin-sharp: ^5.5.0 => 5.5.0
    gatsby-plugin-sitemap: ^6.5.0 => 6.5.0
    gatsby-plugin-svgr: ^3.0.0-beta.0 => 3.0.0-beta.0
    gatsby-source-filesystem: ^5.5.0 => 5.5.0
    gatsby-source-mongodb: ^5.5.0 => 5.5.0
    gatsby-source-sanity: ^7.6.3 => 7.6.3
    gatsby-transformer-cloudinary: ^4.3.1 => 4.3.1
    gatsby-transformer-sharp: ^5.5.0 => 5.5.0
  npmGlobalPackages:
    gatsby-cli: 5.5.0
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by djavco** [comment]
I will be able to get a repo with a minimal reproduction of the issue that has access to placeholder data that I can make public very during week 1st May 2023
