### ISSUE TITLE
Error when using create-gatsy: TypeError: qi.cursorTo is not a function

### ISSUE THREAD

**Issue by 0618** [gatsbyjs/gatsby#37921]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When running `npx create-gatsby@latest -y my-gatsby` on Github Workflow, got following error

```
TypeError: Xi.cursorTo is not a function
    at Timeout._onTimeout (/home/runner/.npm/_npx/fe8a8be88628f971/node_modules/create-gatsby/lib/index.js:5:854)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

Same as https://github.com/gatsbyjs/gatsby/issues/35426

### Reproduction Link

https://github.com/0618/amplify-ui/actions/runs/4634161974/jobs/8200091938

### Steps to Reproduce

1. In Github workflow, set Node version to be 18
2. run `npx create-gatsby@latest -y my-gatsby`

### Expected Result

Shouldn't crash

### Actual Result

See error

```sh
TypeError: Xi.cursorTo is not a function
    at Timeout._onTimeout (/home/runner/.npm/_npx/fe8a8be88628f971/node_modules/create-gatsby/lib/index.js:5:854)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

### Environment

```shell
Operating System
  Ubuntu
  22.04.2
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 20230402.1
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230402.1/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230402.1
Node.js v18.15.0
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

As explained in the old issue, please try https://github.com/gatsbyjs/gatsby/issues/35426#issuecomment-1099798549. Our code uses https://github.com/ascorbic/tiny-spin to create a spinner icon. It uses `process.stderr.cursorTo`.

https://nodejs.org/docs/latest-v18.x/api/readline.html#rlcursortox-y

Reading https://github.com/nodejs/node-v0.x-archive/issues/6933 it seems that this is only available in TTY streams though. And according to https://github.com/actions/runner/issues/241 GitHub actions has problems with that (and only workarounds). So I'd also try these.

Please make sure that you run `create-gatsby` in the right environment and let us know if you need any more guidance. Thanks!

**Comment by 0618** [comment]
@LekoArts https://github.com/gatsbyjs/gatsby/issues/35426#issuecomment-1099798549 doesn't work as you can see in the original issue. `--no-color` is for `gatsby build`, but the issue is from `create-gatsby`. Also, adding `GATSBY_LOGGER=yurnalist`  before `create-gatsby` doesn't work either. 

The issue is still not resolved. Please do not close it.
