### ISSUE TITLE
Gatsby's documentation about visual testing with storybook is out of date / not working.

### ISSUE THREAD

**Issue by darylthornhill** [gatsbyjs/gatsby#37936]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

Storybook has had an update and the documentation linked to configuring storybook no longer works!

Also Gatsby's Link component doesnt play nice with storybook any longer. This is how i came across the issue with this part of the documentation.

Im not sure exactly on how to resolve these issues, but thought it would be worth reporting incase other people have any issues setting it up in the mean time!

### Steps to Resolve this Issue

1. download https://github.com/darylthornhill/test-gatsby-storybook-error  `npm run storybook` to start storybook and see the errors with Gatsby Link.
2. After trying that, copy and paste the example code pieces for the `main.js` and the `preview.js` into the respective files and run `npm run storybook` and see further errors.

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

I don't personally use Storybook and we probably also won't spend any time writing glue code for this. I assume you refer to the 7.0 release?
https://storybook.js.org/releases/7.0

If I read it correctly, they introduced a new API: https://storybook.js.org/blog/framework-api/
But I couldn't find anything for Gatsby.

It seems like https://storybook.js.org/docs/react/contribute/framework needs to be followed for Gatsby now. But again, we don't have time to do this, so it's up for the community to contribute this.

However, I've seen https://github.com/storybookjs/storybook/issues/22065, so happy to help updating our docs.

**Comment by rasmusbe** [comment]
Still an issue

**Comment by Vishrut19** [comment]
Hey! Is this issue still open?

**Comment by graysonhicks** [comment]
Looks like storybook's own Gatsby example is broken on their v7 version, so they need to provide guidance on what should change.  There is already an open issue on the Storybook repo.  Since the issue was introduced by them, it will be tracked there.  I guess this can remain open to update docs once the underlying functionality is fixed.

https://github.com/storybookjs/storybook/issues/21958

**Comment by hameemkay** [comment]
will be better if a Video tutorial is made.

**Comment by rasmusbe** [comment]
Still an issue

**Comment by ranjanmangla1** [comment]
can someone assign me this issue? would love to work on it!

**Comment by Vishrut19** [comment]
I have already asked for it. Let's see

**Comment by quantumflo** [comment]
Hi I can work on the issue if its still open

**Comment by VineeTagarwaL-code** [comment]
Lets work on this

**Comment by salonisahu** [comment]
Still an issue

**Comment by apneduniya** [comment]
Issue?

**Comment by TheShiveshNetwork** [comment]
Is this still an issue?

**Comment by jdahdah** [comment]
still an issue

**Comment by yacxn** [comment]
can I work on this issue ?

**Comment by ralexrdz** [comment]
Still an issue
