### ISSUE TITLE
Support for remote MDX actually exists now (and plugin is not part of Algolia search)

### ISSUE THREAD

**Issue by hoijnet** [gatsbyjs/gatsby#37949]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

I created a new plugin, [gatsby-mdx-remote](https://github.com/dfrnt-com/gatsby-mdx-remote), which is published onto npmjs, and also has additional users it works for. The documentation on gatsbyjs.com and npmjs for gatsby-plugin-mdx probably should be updated to provide a link once the Algolia plugin search is resolved.

This is the specific text in the gatsby-plugin-mdx text that is inaccurate:

> Loading MDX from other sources as the filesystem is not supported. If you have a need for that, please comment in the [GitHub Discussion](https://github.com/gatsbyjs/gatsby/discussions/25068)

Also the refresh of the Gatsby plugin list does not list the new plugin after about one week, unsure if there is an error, as my other added plugin, @dfrnt/gatsby-plugin-graphql-nodes is also not listed yet (generic plugin to source nodes from any graphql endpoint, and is very usable with the previous mdx plugin).

### Steps to Resolve this Issue

1. Update Algolia search repo to include the two new plugins
2. Update gatsby-plugin-mdx, that there is community support to create mdx from remote sources, and add a link to the community plugin for arbitrary nodes - remote mdx support: gatsby-mdx-remote

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

1. We don't have control over this, we use https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-npm-package-search which uses https://github.com/algolia/npm-search. It seems to have long indexing times: https://github.com/algolia/npm-search/issues/1112
2. I'm vary of adding a recommendation without us actually having a look at it. I don't want to recommend something that will be a footgun over the long run or which uses anti-patterns.

**Comment by hoijnet** [comment]
Thanks Lennart, looks like a broad problem. And thanks for the reference, then I know it's on their end!

Of course! I have tried to follow the latest standards and authoring it with Typescript and making it as focused as possible (which is why I split the problems into two parts). Let me know if there is anything I can do with it to better adapt it to community needs, it's my first two plugins to the Gatsby ecosystem.

**Comment by LekoArts** [comment]
Do you have an example site I can just clone and run to test the plugin out?

**Comment by thiagorossener** [comment]
Hi again @hoijnet, thanks for working hard on that plugin. It's extremely necessary since `gatsby-plugin-mdx` supports only files now.

I have the exact same scenario than @rsaarloos [here](https://github.com/gatsbyjs/gatsby/discussions/25068#discussioncomment-5614477). We were using `<MDXRenderer>` from `gatsby-plugin-mdx` v3 to render MDX content from Contentful and it's no longer possible.

I'd like to ask you a question. Does your plugin work with Gatsby Cloud [incremental builds](https://www.gatsbyjs.com/docs/tutorial/creating-a-source-plugin/part-5/)?

I've been having a hard time to make Contentful + MDX work with that. I was able to grab MDX content from Contentful, create `.mdx` files and use it in like the [documentation](https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/#updating-createpage-action-in-gatsby-node) recommends:

```
component: `${postTemplate}?__contentFilePath=/path/to/my-generated-file-from-contentful.mdx`
```

However, when previewing content in Contentful, the preview works for the first run and fails with a run out of memory error due the incremental builds feature. It's frustrating since I already spent over 3 entire days trying to fix.

This is the schema for incremental builds:

![image](https://user-images.githubusercontent.com/1750826/233348399-9bf25d60-702f-4805-9f9c-fb5741a93524.png)

@LekoArts if you know how to make Gatsby Cloud previews work with Contentful + MDX, it'd be super helpful and we'd much appreciate it.

For now, we decided to drop MDX completely and are converting all Contentful blog posts (~120 posts) to common markdown.

**Comment by hoijnet** [comment]
> Do you have an example site I can just clone and run to test the plugin out?

I have set aside some time in the coming days to provide a demo repo to clone and help people get started!

I'll add a link here and a ping once updated 🎉

**Comment by hoijnet** [comment]
> I have the exact same scenario than @rsaarloos [here](https://github.com/gatsbyjs/gatsby/discussions/25068#discussioncomment-5614477). We were using `<MDXRenderer>` from `gatsby-plugin-mdx` v3 to render MDX content from Contentful and it's no longer possible.
> 
> I'd like to ask you a question. Does your plugin work with Gatsby Cloud [incremental builds](https://www.gatsbyjs.com/docs/tutorial/creating-a-source-plugin/part-5/)?

I have not tried as I don't have any incremental source plugin to try with yet. As I use the cache I think the standard mechanisms should work, but it's outside what I have tested and worked with in the past.

Thanks a lot for clarifying the flow. Could be a good first step after the demo repo is released. Bit unsure how to get started. Feel free to massage your post into an enhancement request to help track it.

I believe I will need more help to test incremental parts as things stand now.

**Comment by hoijnet** [comment]
> What we do is create a `File` node using `crateFileFromNodeBuffer` from `gatsby-source-filesystem`. We do that in `onCreateNode` after `gatsby-source-contentful`. So, for each `text/markdown` type from Contentful, we create a `File` node pointing to a `.mdx` file.

It sounds like this is much of what the plugin is automating, could be worth to collab and fix together 😄 The plugin source should (IMHO) be fairly straightforward. As long as the cache cleans up downstream nodes, normal semantics should apply I hope.

**Comment by hoijnet** [comment]
> Do you have an example site I can just clone and run to test the plugin out?

@LekoArts Yes, now I have! Thanks for looking into it! It was easier than I thought to create a starter repo for it, and it creates a single node programmatically to keep things super simple:

* [gatsby-starter-mdx-remote-hello-world](https://github.com/dfrnt-com/gatsby-starter-mdx-remote-hello-world)

Or just go with below. README.md is updated too for others to follow the instructions and get started.

```
gatsby new my-mdx-remote-hello-world-starter https://github.com/dfrnt-com/gatsby-starter-mdx-remote-hello-world
```

Kept it as simple as possible. Do you think it makes submit it as a separate starter, considering its bare-boned-ness? I'm thinking of adding a graphql source too and gauging whether to keep it all together in one repo, or have two separate ones, leaving this as-is to just show how to get started with the remote MDX part?

**Comment by Jejebecarte** [comment]
@LekoArts Out of curiosity, how does https://www.gatsbyjs.com/docs pull its content?
Given its hosted [in the monorepo](https://github.com/gatsbyjs/gatsby/tree/master/docs), which is no the same location as the source for the website, as far as I'm aware.

I know [gatsby-source-git](https://github.com/stevetweeddale/gatsby-source-git) exists, but it's not maintained and has some pretty critical bugs. I'm just looking to pull MDX content from a GitHub repository...

**Comment by LekoArts** [comment]
We use https://github.com/stevetweeddale/gatsby-source-git

**Comment by Jejebecarte** [comment]
Interesting. I've tried using but got a series of unhelpful errors, unfortunately

**Comment by hoijnet** [comment]
> Or just go with below. README.md is updated too for others to follow the instructions and get started.
> 
> ```
> gatsby new my-mdx-remote-hello-world-starter https://github.com/dfrnt-com/gatsby-starter-mdx-remote-hello-world
> ```

@LekoArts, did get a chance to get it up and running? Anything I can help with?

**Comment by LekoArts** [comment]
No, unfortunately not. I hope to get to it this week with my colleagues

**Comment by LekoArts** [comment]
So I've given the code and the repository a look & try. Yeah, it kind of works, but I don't think this will scale and work correctly all the time. That it doesn't work properly with Incremental Builds is already a sign of it that the data tracking of those nodes is not set up.

I think MDX from remote sources should be totally separate from `gatsby-plugin-mdx`, so do not try to somehow make things work with `gatsby-plugin-mdx` and create a transformer plugin: https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/creating-a-transformer-plugin/

I think much inspiration can be taken from https://github.com/hashicorp/next-mdx-remote

**Comment by hoijnet** [comment]
Thanks @LekoArts for the review! It's a first plugin attempt. Your pointers are super helpful to take the next steps with it. Your point about transformer plugins is unclear. It sounds like transformer plugins could be a good idea to align to? Your working make it sounds like it is not a good idea?

As for the linked library I have reviewed it and it uses eval to render on the client side with MDXRemote which can be dangerous from XSS perspective.

> I think much inspiration can be taken from https://github.com/hashicorp/next-mdx-remote

We operate in a strict-dynamic CSP environment and I avoid eval as much as I can. Their note on security is clear:

> This [next-mdx-remote] library evaluates a string of JavaScript on the client side, which is how it MDXRemotes the MDX content. Evaluating a string into javascript can be a dangerous practice if not done carefully, as it can enable XSS attacks.

Fixing the issues of incremental builds in the plugin would be helpful I think. If aligning with a transformer plugin makes sense I think I will continue the exploration and learn some more, but incremental builds is so far new territory for me. Hopefully I can get some help testing from others that are interested in getting this working ☀️

So key question is whether there are significant roadblocks to foresee doing this with a transformer pattern?

**Comment by hoijnet** [comment]
Seems it's still broken at the source from the comments there.

**Comment by hoijnet** [comment]
> > it uses eval to render on the client side with MDXRemote which can be dangerous from XSS perspective.
> 
> But you'll only use this at build time from a source that you can (hopefully) trust. So my first gut feeling would be that in context of Gatsby it's not more dangerous than all other existing patterns from remote sources.
> 

I agree, this makes a lot of sense. I'll reiterate and see where I take it from here! Thanks a lot for the detailed comments. Get a bit overwhelmed with other things for a while.
