### ISSUE TITLE
gatsby-plugin-sharp breaks build when partial hydration is enabled

### ISSUE THREAD

**Issue by parry84** [gatsbyjs/gatsby#37948]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When enabling the partial hydration, the build fails as described in "steps to reproduce" (see error message there).

Everything works fine in _develop_ mode.

I didn't get additional info using the `--verbose` flag.

### Reproduction Link

https://github.com/parry84/parry84.github.io/

### Steps to Reproduce

1. Enable `PARTIAL_HYDRATION` into gastby.config.js
2. Launch `npm run build`
...

### Expected Result

The build finishes correctly

### Actual Result

The build breaks with the following error message:

```
failed Building production JavaScript and CSS bundles - 0.721s

 ERROR #98123  WEBPACK.BUILD-JAVASCRIPT

Generating JavaScript bundles failed

couldn't find async-requires module

not finished Running gatsby-plugin-sharp.IMAGE_PROCESSING jobs - 6.729s
```

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/bin/node
    npm: 9.5.1 - /usr/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 112.0.5615.49
    Firefox: 112.0
  npmPackages:
    gatsby: ^5.8.1 => 5.8.1
    gatsby-cli: ^5.8.0 => 5.8.0
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-google-tagmanager: ^5.8.0 => 5.8.0
    gatsby-plugin-image: ^3.8.0 => 3.8.0
    gatsby-plugin-manifest: ^5.8.0 => 5.8.0
    gatsby-plugin-robots-txt: ^1.8.0 => 1.8.0
    gatsby-plugin-sass: ^6.8.0 => 6.8.0
    gatsby-plugin-sharp: ^5.8.1 => 5.8.1
    gatsby-plugin-sitemap: ^6.8.0 => 6.8.0
    gatsby-plugin-svgr: ^3.0.0-beta.0 => 3.0.0-beta.0
    gatsby-remark-bibliography: git+https://github.com/parry84/gatsby-remark-bibliography.git => 1.2.0
    gatsby-remark-images: ^7.8.0 => 7.8.0
    gatsby-remark-tufte: github:zygar/gatsby-remark-tufte => 1.1.0
    gatsby-source-filesystem: ^5.8.0 => 5.8.0
    gatsby-transformer-remark: ^6.8.0 => 6.8.0
    gatsby-transformer-sharp: ^5.8.0 => 5.8.0
```

### Config Flags

```
PARTIAL_HYDRATION: true
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

I see that your issue is about a specific experiment/flag we currently have. We collect any feedback (bug reports, feature requests, questions, etc.) inside a respective discussion.

Please direct your feedback here: https://github.com/gatsbyjs/gatsby/discussions/36608

Thanks!
