### ISSUE TITLE
The documention for the gatsby-plugin-gatsby-cloud headers is not accurate

### ISSUE THREAD

**Issue by jfo8001** [gatsbyjs/gatsby#37942]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

So I have been messing around with the headers to a site and this plugin documentation is super confusing.

* what is the expected format of transformHeaders
* it says no inheritance happens but that's not how I've observed it in the wild. 

From the docs: https://www.gatsbyjs.com/plugins/gatsby-plugin-gatsby-cloud/

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/106567118/232050562-e03f6a14-4e17-40c0-bcbf-c92fbd6c7547.png">

Regards the second point if I pass in headers like this
```
      { 
        "/*": [    
            `X-Debug: "/*"`,
            `X-Debug2: "/*"`,
        ],
        "/subpage/*": [
            `X-Debug: "/subpage/*"`,
        ]
   }

```

and then I `curl -I https://thewebsite/`  and `curl -I https://thewebsite/subpage/` 

The main page has 
```
X-Debug: /*
X-Debug2: /*
```

The subpage has headers from both routes
```
X-Debug: /subpage/*
X-Debug2: /*
```

This makes it super painful to remove a header, especially since the documentation for transformHeaders is unclear. 
<img width="939" alt="image" src="https://user-images.githubusercontent.com/106567118/232051658-182719a7-0ed6-43c7-91a8-9949333183d8.png">

I'm throwing this out there into github because mainly it took me a few hours of trial and error to divine how this is meant to work.  And still not 100% confident as it doesnt match the docs.  

Any help here MUCH appreciated!!! :) 

### Reproduction Link

(n/a)

### Steps to Reproduce

1. Start up a gatsgby site that's hosted on gatsby cloud
2. Add in gatsby-cloud-gatsby-plugin
3. Try to have different headers for the main page from a subpage by following the documentation.
4. Try to remove a header in the subpage that was provided by the /* route 

.

### Expected Result

The documentation is more clear

### Actual Result

The documenation is unclear

### Environment

```shell
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (8) arm64 unknown
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.18.1 - /tmp/yarn--1681476965749-0.6121771813166315/node
    Yarn: 1.22.19 - /tmp/yarn--1681476965749-0.6121771813166315/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    gatsby: ^4.19.2 => 4.24.8
    gatsby-plugin-gatsby-cloud: ^4.19.0 => 4.25.0
```

**Comment by LekoArts** [comment]
Hi!

Feel free to put up a PR improving the README: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-gatsby-cloud/README.md

**Comment by dennisgon** [comment]
Hi @LekoArts , 
can you assigned this issue to me? I will try to solved this issues
