### ISSUE TITLE
Version dropdown causes page navigation, and version is not respected by search

### ISSUE THREAD

**Issue by CobyPear** [gatsbyjs/gatsby#37943]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

Hi, sort of two issues here but I feel they are very related.

When reading the Gatsby docs, they default to version 5. Often I find the page I want to read and then realize this, then I change the version in the dropdown to `v4` and I am navigated away from the page I was just looking at. I realize this may be because the page might not exist in the v4 docs, but this experience feels a bit worse than a 404.

The other issue is that when I try to search for the page I was just on with the search feature, it only shows me v5 docs. This means for v4 docs I have to navigate manually using the sidebar.

Ideally, the version dropdown would refresh the current page with the version of the docs selected. And the search feature should use the version selected instead of default to v5.

### Steps to Resolve this Issue

I have not looked at the code so I am unsure how to resolve this. I would imagine some change to the version dropdown so that the selected version persists in the application state in such a way that search will only search using the selected version, and using the dropdown itself does not cause navigation.
1.
2.
3.
...

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

We don't have the resources to keep older versions of the docs up to date so they are just deployed versions of older versions of the docs. We don't intend to add the functionalities you pointed out and unfortunately you can't help with that as the source code is private at the moment.
