### ISSUE TITLE
Updating post type product breaks the schema

### ISSUE THREAD

**Issue by MichLan90** [gatsbyjs/gatsby#37982]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi,
Somebody else wrote about it in this thread https://github.com/wp-graphql/wp-graphql-woocommerce/issues/393
And we are experiencing the same issue. If you read the discussion, they suggest at the end that the cause of this might lie in gatsby-source-wordpress.
The given solution, which is manually cleaning the cache, is not convenient when you manage hundred of websites as you might understand.
I wanted to ask if there is any update regarding this or plan to fix it. 
The error occurs only for products (WooCommerce plugin in Wordpress) and it seems to be cause by a gatsby-source-wordpress depency if I am reading the error log correctly, called _graphql-compose_. The action_monitor on anything else (post, page, cpt) seems to work fine otherwise.

I tried to install a minimal reproduction on the sandbox but it says I need node 18 (and have 16) and did not manage to change the version via nvm after installing it? So I cannot provide a reproduction link unfortunately. Hope you can reproduce by following the steps

### Reproduction Link

https://github.com/MichLan90/bug-repro-gsw

### Steps to Reproduce

1. Clone repo and install node modules with `npm i`
2. Launch the repo with `npm run develop/gatsby develop`
3. Login into our test CMS (Wordpress). I created a user for you to test this:
https://test.enkle.re/wp-admin
Username: bug_repro
Password: bug_repro_2023!
4. Once everything is set up, its enough to update a product on wordpress to reproduce the error

### Expected Result

```
info  gatsby-source-wordpress  Watching for WordPress changes
success  gatsby-source-wordpress  diff schemas - 0.793s
success  gatsby-source-wordpress  ingest WPGraphQL schema - 0.903s
success createSchemaCustomization - 0.953s
success  gatsby-source-wordpress  fetch root fields - 0.732s
⠀
info  gatsby-source-wordpress  update product Black Puma Shoes (#4797)
```

### Actual Result

```
Missing onError handler for invocation 'building-schema', error was 'Error: Cannot find ObjectTypeComposer with name WpProduct'. Stacktrace was 'Error: Cannot find ObjectTypeComposer with name WpProduct 
    at SchemaComposer.getOTC (C:\code\varmeshop-gatsby\node_modules\graphql-compose\src\SchemaComposer.ts:730:11)
    at forEach (C:\code\varmeshop-gatsby\node_modules\gatsby\src\schema\infer\index.js:30:37)
    at Array.forEach (<anonymous>)
    at addInferredTypes (C:\code\varmeshop-gatsby\node_modules\gatsby\src\schema\infer\index.js:27:13)
    at updateSchemaComposer (C:\code\varmeshop-gatsby\node_modules\gatsby\src\schema\schema.js:141:9)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:533:9)
    at processTimers (node:internal/timers:507:7)
    at buildSchema (C:\code\varmeshop-gatsby\node_modules\gatsby\src\schema\schema.js:75:3)
    at build (C:\code\varmeshop-gatsby\node_modules\gatsby\src\schema\index.js:111:18)
    at buildSchema (C:\code\varmeshop-gatsby\node_modules\gatsby\src\services\build-schema.ts:19:3)'

success  gatsby-source-wordpress  diff schemas - 0.919s
success  gatsby-source-wordpress  ingest WPGraphQL schema - 1.020s
success createSchemaCustomization - 1.060s
success  gatsby-source-wordpress  fetch root fields - 0.881s

  - get-page-data.ts:100
    [varmeshop-gatsby]/[gatsby]/src/utils/get-page-data.ts:100:13

  - start-server.ts:320
    [varmeshop-gatsby]/[gatsby]/src/utils/start-server.ts:320:24


⠏ building schema
```

Building schema just kinda stay there forever loading and the build fails.

### Environment

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 9 5900HS with Radeon Graphics
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (112.0.1722.58)
  npmPackages:
    gatsby: ^5.4.2 => 5.4.2
    gatsby-plugin-anchor-links: ^1.2.1 => 1.2.1
    gatsby-plugin-apollo: ^4.0.3 => 4.0.3
    gatsby-plugin-gatsby-cloud: ^5.4.0 => 5.4.0
    gatsby-plugin-gdpr-cookies: ^2.0.9 => 2.0.9
    gatsby-plugin-image: ^3.4.0 => 3.4.0
    gatsby-plugin-local-search: ^2.0.1 => 2.0.1
    gatsby-plugin-manifest: ^5.4.0 => 5.4.0
    gatsby-plugin-react-helmet: ^6.4.0 => 6.4.0
    gatsby-plugin-react-svg: ^3.3.0 => 3.3.0
    gatsby-plugin-robots-txt: ^1.8.0 => 1.8.0
    gatsby-plugin-scroll-reveal: ^0.0.7 => 0.0.7
    gatsby-plugin-sharp: ^5.4.0 => 5.4.0
    gatsby-plugin-sitemap: ^6.4.0 => 6.4.0
    gatsby-plugin-styled-components: ^6.4.0 => 6.4.0
    gatsby-source-filesystem: ^5.4.0 => 5.4.0
    gatsby-source-wordpress: ^6.14.3 => 6.14.3
    gatsby-transformer-sharp: ^5.4.0 => 5.4.0
  npmGlobalPackages:
    gatsby-cli: 5.2.0
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

> I tried to install a minimal reproduction on the sandbox but it says I need node 18 (and have 16) and did not manage to change the version via nvm after installing it? So I cannot provide a reproduction link unfortunately. Hope you can reproduce by following the steps

You don't need to use Codesandbox if it doesn't work for your use case. Any reproduction is okay, be that a Dockerfile one can execute locally or you use the Dockerfile inside Codesandbox etc.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by MichLan90** [comment]
Thank you for your answer. I managed to create a minimal reproduction here
https://github.com/MichLan90/bug-repro-gsw

I will update the first post "Step to reproduce" :)

**Comment by MichLan90** [comment]
Any update about this? Thanks!

**Comment by LiamWinterton** [comment]
Would also like to hear about this. Getting the exact same issue:

gatsby: 5.7.0
gatsby-source-woocommerce: 0.17.3

Plugins:
WPGatsby: 2.3.3
WPGraphQL: 1.13.10
WPGraphQL WooCommerce (WooGraphQL): 0.12.1
WooCommerce: 7.4.1

**Comment by MichLan90** [comment]
> Hiya!
> 
> This issue has gone quiet. Spooky quiet. 👻
> 
> We get a lot of issues, so we currently close issues after 60 days of inactivity. It’s been at least 20 days since the last update here. If we missed this issue or if you want to keep it open, please reply here. As a friendly reminder: the best way to see this issue, or any other, fixed is to open a Pull Request. Check out [gatsby.dev/contribute](https://www.gatsbyjs.com/contributing#how-to-contribute) for more information about opening PRs, triaging issues, and contributing!
> 
> Thanks for being a part of the Gatsby community! 💪💜

This is still an issue for us with high priority since it is affecting all of our projects.
