### ISSUE TITLE
Gatsby inserts unexpected NUL character into `.html` .

### ISSUE THREAD

**Issue by tenpaMk2** [gatsbyjs/gatsby#37989]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Gatsby inserts NUL character to `.html` .
This is unexpected.

![スクリーンショット 2023-04-30 17 01 21](https://user-images.githubusercontent.com/8945311/235342531-6c7d8b58-3aac-44bf-93e3-a6e49ac65474.png)
![スクリーンショット 2023-04-30 17 02 23](https://user-images.githubusercontent.com/8945311/235342537-e55e0e84-0f67-40a4-9d9e-ad23733799b0.png)

Reproduction link is my demo project that use my [`@tenpamk2/gatsby-theme-figure-blog`](https://github.com/tenpaMk2/gatsby-theme-figure-blog) .
Sorry, if is not minimal enough.

### Reproduction Link

https://github.com/tenpaMk2/gatsby-starter-figure-blog

### Steps to Reproduce

1. Clone repository in my reproduction link.
2. `npm install`
3. `npm run build` ( `gatsby build` )

### Expected Result

No NUL characters in `.html` .

### Actual Result

After the reproduction steps, the following `.html` has `0x00` (NUL) character.

- `public/tags/markdown/pages/2/index.html`
  - Ln 15, Col 19066

(This causes the [netlify-plugin-checklinks](https://github.com/Munter/netlify-plugin-checklinks) test result to fail. Therefore, I can find this issues.)

### Environment

```shell
System:
    OS: macOS 13.3.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.0.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Edge: 110.0.1587.41
    Safari: 16.4
  npmPackages:
    gatsby: ^5.8.1 => 5.9.0
    gatsby-plugin-feed: ^5.8.0 => 5.9.0
    gatsby-plugin-google-gtag: ^5.8.0 => 5.9.0
    gatsby-plugin-manifest: ^5.8.0 => 5.9.0
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by tenpaMk2** [comment]
Thank you for your reply❗
I'll try to reproduce by minimal reproduction steps.

**Comment by tenpaMk2** [comment]
Hi, @LekoArts .

I made the minimal reproduction project from `gatsby-starter-minimal` .

<https://github.com/tenpaMk2/gatsby-null-reproduction>

You can reproduce `npm run build` .
You can test which files have NULL character by `npm run test` .

The following files have NULL ( `0x00` ) character.

- `./public/Doll example/index.html`
- `./public/Excerpt test/index.html`
- `./public/Figure example/index.html`
- `./public/Link card test/index.html`
- `./public/Markdown test/index.html`
- `./public/Twitter test/index.html`

![スクリーンショット 2023-05-03 22 38 20](https://user-images.githubusercontent.com/8945311/235932771-a2e94079-e22a-40ec-a00b-cc0c15d17cd5.png)

The NULLs are inserted in same position (Ln:1, Col: 5603) across all NG files.
Sometimes there are 3 consecutive NULLs, sometimes there is 1 only.

If you change the my `components/*.js` , the problem may or may not be reproduced.

I re-executed `gatsby info --clipboard` .

```txt
  System:
    OS: macOS 13.3.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.0.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Edge: 110.0.1587.41
    Safari: 16.4
  npmPackages:
    gatsby: ^5.9.0 => 5.9.0 
    gatsby-plugin-image: ^3.9.0 => 3.9.0 
    gatsby-plugin-sharp: ^5.9.0 => 5.9.0 
    gatsby-remark-images: ^7.9.0 => 7.9.0 
    gatsby-remark-prismjs: ^7.9.0 => 7.9.0 
    gatsby-source-filesystem: ^5.9.0 => 5.9.0 
    gatsby-transformer-remark: ^6.9.0 => 6.9.0 
    gatsby-transformer-sharp: ^5.9.0 => 5.9.0 
  npmGlobalPackages:
    gatsby-cli: 5.9.0
```

This problem also can be reproduced by my Windows machine (Windows 10 10.0.19045) .
The same files have NULL character.
