### ISSUE TITLE
Build gatsby/wordpress/3000 posts

### ISSUE THREAD

**Issue by highlabs** [gatsbyjs/gatsby#3799]
Hi! I'm testing Gatsby as an alternative to wordpress. I created a simples Gatsby project with index + content page.

But, when I try to build, I get some errors:
With `gatsby build`, It just don't compile.
https://pastebin.com/pyqB0nER

So I tried with `node --max_old_space_size=12000 --stack-size=100000 ./node_modules/gatsby/dist/bin/gatsby.js build --prefix-paths`
It's compile but takes 9minutes. (https://pastebin.com/KqTnK7PB)

I want to use Gastby and Netlify (it's fail in free tier, I know...) But are normal to take so long to build the content? My blog has at least 10k posts, so if take 9minutes to compile only 3k posts Gatsby are not a alternative to use. :(

### Environment

Gatsby version: 1.9.158
Node.js version: v8.9.4
Operating System: Linux Ubuntu 16.04 (4.13.0-32-generic)
Hardware: AMD Ryzen 5 1400 Quad-Core Processor, 4gb ram

### File contents (if changed):

`gatsby-config.js`: https://pastebin.com/UVEQkygL
`package.json`: https://pastebin.com/hpLZ3dRf
`gatsby-node.js`: https://pastebin.com/i7U3S63R
`gatsby-browser.js`: default
`gatsby-ssr.js`: default

**Comment by sebastienfi** [comment]
Thanks for bringing this matter forward @highlabs . I believe that Gatsby v2 will provide a faster build. @KyleAMathews Can you please elaborate on that ?

**Comment by calcsam** [comment]
@sebastienfi is correct. We're working on scalability issues, including v2 which will increase performance by upgrading from webpack 1 to webpack 3.

Your personal blog has 10k posts? Or is this a company blog? Either way, impressive.

https://github.com/gatsbyjs/gatsby/issues/2641

**Comment by highlabs** [comment]
@calcsam It's a lifestyle magazine. :) So we have 4 ~5 posts per day, but the blog was created 10 years ago.

Thanks for the feedback, but one more question. It's a issue in Gastby or in the `gatsby-source-wordpress`? If I change to contentful or other headless cms will optimize the build time?

**Comment by sebastienfi** [comment]
I think it's a webpack issue, so it would be located on the underlaying architecture and changing the source plugin won't make a difference in my humble opinion. V2 will also include I believe a performance monitoring tool so we should be able to have comparable metrics results upon configuration changes.
