### ISSUE TITLE
Production build issues when adding custom .babelrc file

### ISSUE THREAD

**Issue by IljaDaderko** [gatsbyjs/gatsby#3804]
## Description

I had to add custom .babelrc file to my project as I kept getting errors related to using `async` and `await` in my app. Something along the lines of `Unexpected character <<*>> expected punctualtion <<)>>` Here is how my babelrc looks like

```
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "browsers": [
            "last 2 versions",
            "safari >= 9",
            "edge >= 13",
            "chrome >= 50",
            "firefox >= 50"
          ]
        }
      }
    ],
    "react",
    "stage-0"
  ],
  "env": {
    "development": {
      "plugins": ["transform-runtime"]
    }
  }
}
```

I had to add `babel-plugin-transform-runtime` as it wasn't working in development.

Now once I do `gatsby build` I get a bunch of errors, that I'm almost certain are due to me adding custom babelrc

```
WebpackError: a.type.toLowerCase is not a function
  
  - react-dom-server.node.production.min.js:36 a.renderDOM
    ~/gatsby-plugin-react-next/~/react-dom/cjs/react-dom-server.node.production.min.js:36:378
  
  - react-dom-server.node.production.min.js:36 a.render
    ~/gatsby-plugin-react-next/~/react-dom/cjs/react-dom-server.node.production.min.js:36:217
  
  - react-dom-server.node.production.min.js:35 a.read
    ~/gatsby-plugin-react-next/~/react-dom/cjs/react-dom-server.node.production.min.js:35:208
  
  - react-dom-server.node.production.min.js:44 renderToString
    ~/gatsby-plugin-react-next/~/react-dom/cjs/react-dom-server.node.production.min.js:44:1
  
  - gatsby-ssr.js:26 Object.exports.replaceRenderer
    ~/gatsby-plugin-styled-components/gatsby-ssr.js:26:1
  
  - api-runner-ssr.js:29 
    .cache/api-runner-ssr.js:29:41
  
  
  - api-runner-ssr.js:27 module.exports
    .cache/api-runner-ssr.js:27:25
  
  - static-entry.js:113 module.exports
    .cache/static-entry.js:113:3
```

### Environment

Gatsby version: 1.9.175
Node.js version: 9.3.0
Operating System: macOS High Sierra

### File contents (if changed):

`gatsby-config.js`: 
```
module.exports = {
  siteMetadata: {
    title: `Loot`
  },
  plugins: [
    `gatsby-plugin-react-next`,
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-styled-components`,
    `gatsby-plugin-jss`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: "Loot",
        short_name: "Loot",
        start_url: "/",
        background_color: "#000000",
        theme_color: "#000000",
        display: "minimal-ui"
      }
    },
    `gatsby-plugin-offline`
  ]
};
```
`package.json`: 
`gatsby-node.js`: 
`gatsby-browser.js`: 
`gatsby-ssr.js`: 

### Actual result

Production build fails

### Expected behavior

Should build correctly

### Steps to reproduce

1\. add your own .babelrc file

If I remove .babelrc file, it works in development, but prod build fails with this error again
```
Error: component---src-pages-index-js-f0dc7df123033f5a997d.js from UglifyJs
  SyntaxError: Unexpected token operator «*», expected punc «(» [./src/controlers/BudgetController.j  s:9,7]
```

line it refers to is

```
export async function getBudget() {
```

**Comment by KyleAMathews** [comment]
Part of the problem looks like you're not using the browserslist key in your package.json https://www.gatsbyjs.org/docs/browser-support/#specify-what-browsers-your-project-supports-using-browserslist

Could you build a simple site reproducing this problem I could look at?

**Comment by IljaDaderko** [comment]
Ah nice. So what I did is delete my custom `.babelrc` and added this to package.json

```
"browserlist": [
    "last 2 versions",
    "safari >= 9",
    "edge >= 13",
    "chrome >= 50",
    "firefox >= 50"
  ]
```

In dev mode all issues are gone, works nicely. Still getting this error however

```
component---src-pages-index-js-2733c300e30f44b89bd6.js from UglifyJs
  SyntaxError: Unexpected token operator «*», expected punc «(» [./src/controlers/BudgetController.j  s:9,7]
```

In my src this just refers to line that uses async function, that actual files line 9 is this

`/***/ (function(module, exports, __webpack_require__) {`

For more context of this line

```
webpackJsonp([35783957827783],[
/* 0 */,
/* 1 */,
/* 2 */,
/* 3 */,
/* 4 */,
/* 5 */,
/* 6 */
/***/ (function(module, exports, __webpack_require__) {

	var __WEBPACK_AMD_DEFINE_ARRAY__, __WEBPACK_AMD_DEFINE_RESULT__;/*!
	  Copyright (c) 2016 Jed Watson.
	  Licensed under the MIT License (MIT), see
	  http://jedwatson.github.io/classnames
	*/
	/* global define */
```

**Comment by calcsam** [comment]
The problem is that webpack / babel is not processing your line `export async function getBudget() {` correctly. @IljaDaderko could you push a simple repo where you can reproduce this problem?

**Comment by Jaikant** [comment]
@calcsam you are right. I saw exactly the same error because I did a

`import Box from '../Layouts';
`
instead of a 

`import { Box } from '../Layouts';`

**Comment by IljaDaderko** [comment]
@calcsam hey, sorry for being quiet for such long period. I also tried changing that line to `export const getBudget = async () => {` no luck. Does gatsby support async / away out of the box by the way? Or do I need to add appropriate babel plugins?

As for repo, I will try to port this to small example 👍

**Comment by IljaDaderko** [comment]
Issue solved with adding `.babelrc` with following config

```
{ 
    "presets": ["react", "es2015", "stage-0"],
    "plugins": ["transform-runtime"]
}

```

I guess I was assuming a lot of this came out of the box.
