### ISSUE TITLE
Document `@gatsbyjs/parcel-namer-relative-to-cwd`

### ISSUE THREAD

**Issue by fregante** [gatsbyjs/gatsby#38047]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

There's nothing in the readme: https://www.npmjs.com/package/@gatsbyjs/parcel-namer-relative-to-cwd

How can I use this plugin?

### Steps to Resolve this Issue

I don't know, that's why it needs documentation

**Comment by LekoArts** [comment]
Hi!

You don't need to use it, it's internally used by Gatsby and can be reused in your Parcel app if you want. The functionality is described in the README.
If you just use Gatsby you don't need to worry about it.

**Comment by fregante** [comment]
The point is that I don't use Gatsby and the plugin is the first on Parcel’s official plugin list:

- https://parceljs.org/plugin-browser/?type=%22namer%22&page=0&filter=%22%22&includeOfficial=false

<img width="869" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/235592227-584f9582-5bcb-46dd-b833-5aae6a748b2b.png">


This only needs 3 lines in the readme

- "Already included in Gatsby, otherwise add `"namers": ["@gatsbyjs/parcel-namer-relative-to-cwd", "..."] to .parcelrc

**Comment by LekoArts** [comment]
Hope this makes it clearer: https://github.com/gatsbyjs/gatsby/pull/38049
