### ISSUE TITLE
Gatsby MDX reports invalid AST

### ISSUE THREAD

**Issue by davwheat** [gatsbyjs/gatsby#38058]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Issue created from #37518

When using the MDX plugin and programmatically generating pages, I get an error about invalid AST which renders MDX-generated pages unusable.

This only occurs during SSG, and the pages will work correctly during development despite the error.

### Reproduction Link

https://github.com/davwheat/gatsby-issue-reproduction-3

### Steps to Reproduce

1. Clone repo
2. Run `yarn build`

### Expected Result

The pages to be built in SSG successfully.

### Actual Result

SSG fails due to "invalid AST":

```
 ERROR #gatsby-plugin-mdx_10003  PLUGIN

Invalid AST. Parsed source code did not return valid output.

Template:
/home/david/gatsby-issue-reproduction-3/src/templates/blog-article/BlogPageTemplate.tsx
File: /home/david/gatsby-issue-reproduction-3/blog/test/test.mdx



  SyntaxError: Unexpected token (17:35)
  
  - acorn.mjs:3454 Parser.pp$4.raise
    [gatsby-issue-reproduction-3]/[acorn]/dist/acorn.mjs:3454:13
  
  - acorn.mjs:755 Parser.pp$9.unexpected
    [gatsby-issue-reproduction-3]/[acorn]/dist/acorn.mjs:755:8
  
  - acorn.mjs:2838 Parser.pp$5.parseExprAtom
    [gatsby-issue-reproduction-3]/[acorn]/dist/acorn.mjs:2838:10
  
  - index.js:445 Parser.parseExprAtom
    [gatsby-issue-reproduction-3]/[acorn-jsx]/index.js:445:22
  
  - acorn.mjs:2630 Parser.pp$5.parseExprSubscripts
    [gatsby-issue-reproduction-3]/[acorn]/dist/acorn.mjs:2630:19
  
  - acorn.mjs:2596 Parser.pp$5.parseMaybeUnary
    [gatsby-issue-reproduction-3]/[acorn]/dist/acorn.mjs:2596:17
  
  - acorn.mjs:2548 Parser.pp$5.parseExprOp
    [gatsby-issue-reproduction-3]/[acorn]/dist/acorn.mjs:2548:41
  
  - acorn.mjs:2525 Parser.pp$5.parseExprOps
    [gatsby-issue-reproduction-3]/[acorn]/dist/acorn.mjs:2525:91
  
  - acorn.mjs:2506 Parser.pp$5.parseMaybeConditional
    [gatsby-issue-reproduction-3]/[acorn]/dist/acorn.mjs:2506:19
  
  - acorn.mjs:2473 Parser.pp$5.parseMaybeAssign
    [gatsby-issue-reproduction-3]/[acorn]/dist/acorn.mjs:2473:19
  
  - acorn.mjs:2436 Parser.pp$5.parseExpression
    [gatsby-issue-reproduction-3]/[acorn]/dist/acorn.mjs:2436:19
  
  - acorn.mjs:945 Parser.pp$8.parseStatement
    [gatsby-issue-reproduction-3]/[acorn]/dist/acorn.mjs:945:45
  
  - acorn.mjs:1231 Parser.pp$8.parseBlock
    [gatsby-issue-reproduction-3]/[acorn]/dist/acorn.mjs:1231:21
  
  - acorn.mjs:3280 Parser.pp$5.parseFunctionBody
    [gatsby-issue-reproduction-3]/[acorn]/dist/acorn.mjs:3280:22
  
  - acorn.mjs:1353 Parser.pp$8.parseFunction
    [gatsby-issue-reproduction-3]/[acorn]/dist/acorn.mjs:1353:8
  
  - acorn.mjs:1664 Parser.pp$8.parseExport
    [gatsby-issue-reproduction-3]/[acorn]/dist/acorn.mjs:1664:31
  
```

### Environment

```shell
yarn run v1.22.19
$ /home/david/gatsby-issue-reproduction-3/node_modules/.bin/gatsby info --clipboard

  System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (6) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.16.0 - /tmp/yarn--1683215542858-0.1128147637279342/node
    Yarn: 1.22.19 - /tmp/yarn--1683215542858-0.1128147637279342/yarn
    npm: 9.5.1 - /usr/bin/npm
  npmPackages:
    gatsby: ^5.9.0 => 5.9.0
    gatsby-plugin-mdx: ^5.9.0 => 5.9.0
    gatsby-plugin-typescript: ^5.9.0 => 5.9.0
    gatsby-source-filesystem: ^5.9.0 => 5.9.0


Done in 1.04s.
```

### Config Flags

Happens with DEV SSR on (in project) and off (in reproduction).

**Comment by LekoArts** [comment]
Hi!

You've already received your answer here: https://github.com/gatsbyjs/gatsby/discussions/37518#discussioncomment-4753706

This is due to invalid MDX files on your end, we can't do anything about as MDX complains about it. Please see the section in the docs: https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/#updating-mdx-content
You can e.g. use `eslint-mdx` to uncover your invalid content.

**Comment by davwheat** [comment]
@LekoArts Unfortunately, I didn't get my answer.

If you read the thread, you can see immediately below the message you linked that I updated the MDX file to fix the invalid issues raised, as Paulie suggested, and the issue remains.

In fact, if you open the minimum reproduction, I fail to see how it could be invalid at all.

I'll include a copy below for convenience:

```mdx
---
title: "Test?"
description: Test!
path: test
created_at: 2022-04-19T16:00Z
---

EE's innovation in RAN has found it at the bleeding edge of new 5G deployments in the UK, being the first operator to deploy 5G NR carrier
aggregation in a relatively widespread manner across many parts of the UK capital, London.
```

**Comment by davwheat** [comment]
@LekoArts Any chance my issue can be reopened?

**Comment by davwheat** [comment]
Doing deeper research into MDX and Acorn, it seems this is caused by trying to use Typescript.

Where it was tripping over was an `import type ...` in my MDX page template.

It then also proceeded to fall over at modern JS syntax like `||=` and `&&=`.

After "downgrading" my layout template from TS to JS, and removing instances of `||=`, `&&=` and `??=`, I could successfully build my site.

**This really needs to be documented somewhere in the Gatsby Docs.**
