### ISSUE TITLE
[Head API] Somebody has monkeypatched console.error in `head-export-handler-for-browser.js` file

### ISSUE THREAD

**Issue by JustFly1984** [gatsbyjs/gatsby#38053]
I'm currently updating my gatsby project, and trying to fix the Head API. The sad thing that I can't use pageContext in wrapRootElement has no access to pageContext, so I can't use react-intel's IntlProvider.
wrapPageElement is not wrapping Head components, so the only solution which is ugly - I had to wrap Head into IntelProvider in each page template file.

After that I've almost pulled my hair out for another 2 hours, trying to debug something what actually is not broken. Somebody has monkeypatched console.error in `head-export-handler-for-browser.js` file, 

<img width="688" alt="Screen Shot 2023-03-16 at 8 13 44 PM" src="https://user-images.githubusercontent.com/2255993/225627921-b48fe340-ba48-4f83-ae41-cfe2b7c92381.png">

and this just crashes my app in the place where console.error should behave correct, but now it does not! Please forbid monkeypatching!!!

_Originally posted by @JustFly1984 in https://github.com/gatsbyjs/gatsby/discussions/35841#discussioncomment-5333718_

**Comment by LekoArts** [comment]
The issue tracker is for bugs, please not use it for discussions or questions. Thanks!

**Comment by JustFly1984** [comment]
I'm sorry, but how is that not a bug?

**Comment by JustFly1984** [comment]
@LekoArts There is a button in github - create an issue from post in disscussion. I've used that. Here is an explanation of a bug with monkeypatching console.error, which is only caused by using console.error. please reopen.
