### ISSUE TITLE
Navigationg to homepage while accessing other routes in website

### ISSUE THREAD

**Issue by halloween603** [gatsbyjs/gatsby#3806]
Hi,
If i am accessing any other route in my website without going to homepage, it is going to homepage and then only it is navigating to particular route. i implemented my homepage in pages main index file.
Thank you in advance.

**Comment by mpolinowski** [comment]
This is the default behaviour if you use gatsby-link / <Link to="somewhere"/>. You can use <a href="somewhere"> instead if you don't want that.

Same with the catch-links plugin in Markdown files.

**Comment by halloween603** [comment]
Is there any way to handle it.

**Comment by mpolinowski** [comment]
Those two plugins "cause" this behaviour:

https://www.gatsbyjs.org/packages/gatsby-link/
https://www.gatsbyjs.org/packages/gatsby-plugin-catch-links/

By using a-tag links you avoid it. Or do you mean you have an auto-prefix, like this:

https://www.gatsbyjs.org/docs/path-prefix/ ?

**Comment by calcsam** [comment]
Closing this as @mpolinowski has answered the question

**Comment by halloween603** [comment]
Thank you for your suggession @mpolinowski
