### ISSUE TITLE
index.html returns a white empty page

### ISSUE THREAD

**Issue by kickbk** [gatsbyjs/gatsby#38080]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I generated a brand new Gatsby site with `npm init gatsby` - typescript, sass and nothing else
When I go to `http://localhost:8000/index.html` it returns an empty page. It doesn't show the default homepage and doesn't redirect to it.
Is this normal? I believe it's a bug since I haven't seen anywhere it mentions this is the expected behavior.

### Reproduction Link

don't have it. I'm talking super basic here.

### Steps to Reproduce

1. create a new Gatsby site with `npm init gatsby`
2. select Typescript and Sass and nothing else
3. Start Gatsby with gatsby develop
4. Go to `http://localhost:8000/index.html` and you should see an empty white page
...

### Expected Result

I believe we're supposed to see the homepage or get redirected to it?

### Actual Result

Shows an empty white page

### Environment

```shell
System:
  OS: macOS Big Sur
  CUP: 2.4 GHz Dual-Core Intel Core i5
Binaroes:
  Node: v18.16.0
  npm: v18.16.0
Browser:
  Chrome and Firefox - same result
npmPackages:
  gatsby - the latest
```

**Comment by LekoArts** [comment]
Hi!

During `gatsby develop` an optimized environment for fast hot-reloading and development is spun up and only a SPA shell is served. It's expected behavior that you don't see anything on the route you mentioned.

You can simulate a deployed version through `gatsby serve` but in the end your Gatsby site will always be served by a webserver where then the URL you mentioned works.
