### ISSUE TITLE
Setting `<html> style` attribute in head API does not work

### ISSUE THREAD

**Issue by DennisRosen** [gatsbyjs/gatsby#38097]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Trying to set `style` on the `<html>` element in the Gatsby head API results in the following build-time error:

`WebpackError: The 'style' prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX.`

Note that this only occurs in production builds using `gatsby build`, not `gatsby develop`. I have not tested other element types than the `html` element, but I guess they won't work with the `style` attribute either.

### Reproduction Link

N/A

### Steps to Reproduce

1. Add the following Head export to a page:

`export const Head = () => <html style={{ color: 'red' }} />`

2. Run `gatsby build`

### Expected Result

The site starts without errors.

### Actual Result

The following build error occurs:

`WebpackError: The 'style' prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX.`

### Environment

```shell
System:                                                        
    OS: Windows 10 10.0.19044                                    
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz        
  Binaries:                                                      
    Node: 18.12.0 - C:\Program Files\nodejs\node.EXE             
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD      
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD                
  Languages:                                                     
    Python: 2.7.18 - /c/Python27/python                          
  Browsers:                                                      
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.42)    
  npmPackages:                                                   
    gatsby: ^5.10.0 => 5.10.0                                    
    gatsby-plugin-eslint: 4.0.2 => 4.0.2                         
    gatsby-plugin-extract-schema: 0.2.1 => 0.2.1                 
    gatsby-plugin-gatsby-cloud: ^5.8.0 => 5.10.0                 
    gatsby-plugin-google-tagmanager: ^5.3.1 => 5.10.0            
    gatsby-plugin-graphql-codegen: ^3.1.1 => 3.1.1               
    gatsby-plugin-image: ^3.3.2 => 3.10.0                        
    gatsby-plugin-manifest: ^5.3.1 => 5.10.0                     
    gatsby-plugin-postcss: ^6.3.0 => 6.10.0                      
    gatsby-plugin-prettier-eslint: ^1.0.4 => 1.0.6               
    gatsby-plugin-react-helmet: ^6.3.0 => 6.10.0                 
    gatsby-plugin-react-svg: ^3.1.0 => 3.3.0                     
    gatsby-plugin-robots-txt: ^1.8.0 => 1.8.0                    
    gatsby-plugin-sharp: ^5.3.2 => 5.10.0                        
    gatsby-plugin-sitemap: ^6.3.1 => 6.10.0                      
    gatsby-plugin-split-css: ^2.0.2 => 2.0.3                     
    gatsby-plugin-typescript: ^5.3.1 => 5.10.0                   
    gatsby-source-filesystem: ^5.3.1 => 5.10.0                   
    gatsby-source-sanity: ^7.6.1 => 7.6.3                        
    gatsby-transformer-sharp: ^5.3.1 => 5.10.0                   
  npmGlobalPackages:                                             
    gatsby-cli: 2.12.92
```

**Comment by panstav** [comment]
[Reproduction link](https://codesandbox.io/p/devbox/boring-snowflake-2sgfh4)
