### ISSUE TITLE
Javascript in Gatsby

### ISSUE THREAD

**Issue by sunfudge** [gatsbyjs/gatsby#3809]
I need the following javascript to make the navbar menu toggle work correctly:

document.addEventListener('DOMContentLoaded', function () {
// Get all "navbar-burger" elements
var $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

// Check if there are any navbar burgers
if ($navbarBurgers.length > 0) {
  // Add a click event on each of them
  $navbarBurgers.forEach(function ($el) {
    $el.addEventListener('click', function () {
      // Get the target from the "data-target" attribute
      var target = $el.dataset.target;
      var $target = document.getElementById(target);
      // Toggle the class on both the "navbar-burger" and the "navbar-menu"
      $el.classList.toggle('is-active');
      $target.classList.toggle('is-active');
    }); 
  });
 }
});

When I run gatsby build, I get the document undefined error which I believe is described in gatsbyjs docs - "How to check if window / document is defined"

How do I modify the above javascript based on the debugging guide?

Thanks

**Comment by pieh** [comment]
Wrap that code in `if (typeof document !== 'undefined')` to get rid of the build error. But I'm not sure if this will work for react application as gatsby will add/remove html elements without page reload when you navigate to new page - that peace of code might be not fit for react based page.

**Comment by calcsam** [comment]
Yes, the above code looks like something you would write for a jQuery / Backbone app. You will want to read some pieces on React's concept of a virtual DOM and rewrite ^ code to fit that model.
