### ISSUE TITLE
Unexpected remount on client-side routing (@gatsbyjs/reach-router)

### ISSUE THREAD

**Issue by bebbi** [gatsbyjs/gatsby#38107]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Since the router, like @reach/router, doesn't seem to support optional parameters, my use-case is to simulate an optional parameter in an editor that should not get remounted:

```js
    <Router basepath="/">
      <Editor path="/" />
      <Editor path="/:someId" />
    </Router>
```

Once `someId` is processed, we `navigate('/')`.
But the issue is that the editor gets remounted and loses state.

It seems that this was an issue introduced between `@reach/router@1.2.1` and `1.3.4`
Another useful description and a repro is [here (gh issue link)](https://github.com/reach/router/issues/478).

### Reproduction Link

https://github.com/gustafc/reach-remounts

### Steps to Reproduce

See the instructions in the repro repo.

### Expected Result

The above routing config should not unmount any part of `<App />`

### Actual Result

The above routing config unmounts and remounts all of `<App />`

### Environment

```shell
System:
    OS: macOS 13.3.1
    Shell: 5.2.15
  Binaries:
    Node: 19.8.1 - /private/var/folders/ht/18wcb1f538bgx47qrfc1n0q80000gq/T/xfs-a8153025/node
    Yarn: 3.4.1 - /private/var/folders/ht/18wcb1f538bgx47qrfc1n0q80000gq/T/xfs-a8153025/yarn
    npm: 9.5.1
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 113.0.1
    Safari: 16.4
```

**Comment by LekoArts** [comment]
Hi!

This repository is for issues related to Gatsby. In client-side only routes of Gatsby you can use any router you want, you don't need to use `reach-router`. We only use a forked version of it for our own SPA navigations.

Thus this is not something we'll fix. You can use https://reactrouter.com/en/main or https://tanstack.com/router/v1
