### ISSUE TITLE
The plugin "gatsby-source-name" created a node of a type "File" owned by "gatsby-source-filesystem"

### ISSUE THREAD

**Issue by tordans** [gatsbyjs/gatsby#38117]
### Description

This is extracted from https://github.com/gatsby-uc/plugins/issues/426#issuecomment-1562455390…

> [LekoArts](https://github.com/LekoArts) commented on 2023-05-25
> …
>This shouldn't happen and is probably a regression from https://github.com/gatsbyjs/gatsby/pull/37782
>The current PR https://github.com/gatsby-uc/plugins/pull/431 shouldn't be merged as this needs to be fixed inside gatsby

… and https://github.com/gatsby-uc/plugins/issues/426#issuecomment-1562572974

> [LekoArts](https://github.com/LekoArts) commented on 2023-05-25
> …
> * We tell users to use `createRemoteFileNode` like this: https://www.gatsbyjs.com/plugins/gatsby-source-filesystem/#createremotefilenode
> * Your PR is changing the `createNode` function for `createRemoteFileNode`
> * It should continue to work how we document it in the public docs
> 
> `File` nodes should be managed by `gatsby-source-filesystem` and that's how it used to work in the past.
> 
> However, https://github.com/gatsby-uc/plugins/pull/431/files#diff-77a5459c74cf8818897d5690b621b8bca7f96d363a1eb68a6ed55f65711e061aR61 seems like a correct change. The source plugin shouldn't touch `File` nodes, it should only touch its own nodes: https://www.gatsbyjs.com/docs/tutorial/creating-a-source-plugin/part-5/#1-prevent-garbage-collection

The linked issues goes into more details.

### Reproduction Link

-

### Steps to Reproduce

-

### Expected Result

-

### Actual Result

-

### Environment

```shell
-
```

**Comment by LekoArts** [comment]
Can you please attach a minimal reproduction we can run?
I don't have a Strapi account or it hosted somewhere and we'd need that to run the source plugin.

**Comment by laurenskling** [comment]
@derrickmehaffy is there a Strapi demo site the Gatsby team can use to debug this issue?

**Comment by tordans** [comment]
> Can you please attach a minimal reproduction we can run? I don't have a Strapi account or it hosted somewhere and we'd need that to run the source plugin.

@LekoArts you can fork https://github.com/FixMyBerlin/plan-f.info and use it with our staging content to test the integration. 
Please send me an email to tobias@fixmycity.de for the required `.env` variable to pull data from the Strapi backend (which we have at https://github.com/FixMyBerlin/plan-f-backend).

**Comment by rileybathurst** [comment]
I built this here
https://github.com/rileybathurst/strapi-bug
with the strapi key in the gastby-config file and the server at
http://45.79.101.19:1345/
let me know if you need any changes on this

**Comment by LiamJSP** [comment]
I'd like to add that this issue is affecting most gatsby-source plugins. It also affects gatsby-source-prismic, and gatsby-source-directus.

[https://github.com/prismicio/prismic-gatsby/issues/530](https://github.com/prismicio/prismic-gatsby/issues/530)

**Comment by LekoArts** [comment]
Thanks for that context @LiamJSP - we've been busy with something else but given that this seems to be more widespread I'll escalate this

**Comment by JustinGillespie** [comment]
This issue is breaking our builds as well. From what i've read, downgrading to 5.8.0 will solve the issue, but i've had no luck so far. Hopefully this can be fixed soon.

**Comment by TylerBarnes** [comment]
I believe I've fixed it, can someone try this canary? `gatsby@5.11.0-touch-nodes-fix.4` I tried it on @rileybathurst 's repro above and it seemed to work.

I think the oversight here was thinking nodes shouldn't be touched by a plugin that doesn't own them. I'm not sure `source-strapi` should touch File nodes but I believe allowing it to again will make this work

**Comment by laurenskling** [comment]
Thanks for the help @TylerBarnes and @pieh . Anything we can do to improve on our side?

**Comment by LekoArts** [comment]
Our, as-in source plugins?

Yeah, we saw room of improvement here:

- Ideally the source plugin creates `Asset` types for nodes that will hold those image assets
- When calling `createRemoteFileNode` the `parentNodeId` should be set to those `Asset`
- You don't `touchNode` `File` nodes but only your `Asset` nodes. Because they are linked, files will be kept around

This is what `gatsby-source-contentful` is doing

**Comment by LekoArts** [comment]
The fix to this issue was released in `gatsby@5.11`. Please try that 👍

**Comment by LiamJSP** [comment]
I can confirm gatsby-source-prismic is now working with gatsby@5.11.0! I got a working build. Thanks a bunch all! I'll CC LekoArts suggestions for source-plugin improvement into the respective Prismic thread. Thx again!

**Comment by rileybathurst** [comment]
> I believe I've fixed it, can someone try this canary? `gatsby@5.11.0-touch-nodes-fix.4` I tried it on @rileybathurst 's repro above and it seemed to work.
> 
> I think the oversight here was thinking nodes shouldn't be touched by a plugin that doesn't own them. I'm not sure `source-strapi` should touch File nodes but I believe allowing it to again will make this work
> 
> EDIT: btw for trying the canary with the mentioned repro I had to use yarn due to dep tree issues, npm wouldn't install the canary. In a released version that wont be an issue, it's just for the canary

Thanks for the fix.
Are you cool with me pulling the same project down or would you like it left up for more testing?

**Comment by TylerBarnes** [comment]
Feel free to take it down, thanks for the repro!
