### ISSUE TITLE
bug(gatsby-transformer-screenshot): aws webservice returns 403

### ISSUE THREAD

**Issue by doxsch** [gatsbyjs/gatsby#38129]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When I tried to start a new build, for all requests to take a screenshot, I received an error that it could not be taken:

```
Run npm run build -- --prefix-paths

> my-package@0.0.1 build
> gatsby build --prefix-paths
...
success createSchemaCustomization - 0.004s
Failed to screenshot https://ashleighsimonelli.co.uk./ Retrying...
Failed to screenshot https://aarondunphy.com./ Retrying...
Failed to screenshot https://aashutosh.dev./ Retrying...
Failed to screenshot [https://portfolio-n4sn.vercel.app/.](https://portfolio-n4sn.vercel.app/) Retrying...
...
```
So I had a quick look at what I get as a response from the web service that is supposed to do this conversion:
```
$ curl -s -X POST https://h7iqvn4842.execute-api.us-east-2.amazonaws.com/ -d '{"url": "https://www.google.com/?&bih=889&biw=1500&hl=de"}'
{"message":"Forbidden"}
```

### Reproduction Link

-

### Steps to Reproduce

1. Create new project
2. Install gatsby-transformer-screenshot
3. Use gatsby-transformer-screenshot to create screenshot
...

### Expected Result

Should create screenshot nodes.

### Actual Result

All requests fail:

Failed to screenshot https://ashleighsimonelli.co.uk./ Retrying...
Failed to screenshot https://aarondunphy.com./ Retrying...
Failed to screenshot https://aashutosh.dev./ Retrying...

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.50)
  npmPackages:
    gatsby: ^5.10.0 => 5.10.0
    gatsby-plugin-image: ^3.10.0 => 3.10.0
    gatsby-plugin-manifest: ^5.8.0 => 5.8.0
    gatsby-plugin-sharp: ^5.10.0 => 5.10.0
    gatsby-source-filesystem: ^5.10.0 => 5.10.0
    gatsby-transformer-screenshot: ^5.8.0 => 5.8.0
    gatsby-transformer-sharp: ^5.8.0 => 5.8.0
    gatsby-transformer-yaml: ^5.10.0 => 5.10.0
```

**Comment by doxsch** [comment]
Hi @LekoArts 

Has been super handy so far, of course. But of course I can understand that you can no longer pay for the costs.

Thanks for the quick reply.

**Comment by LekoArts** [comment]
I don't know the estimated cost so unfortunately I can't add anything to the README. If you try it out and can give an estimate, feel free to put up a PR adding it to the README :)
