### ISSUE TITLE
Adding Flightcontrol Docs

### ISSUE THREAD

**Issue by ModupeD** [gatsbyjs/gatsby#38128]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

Flightcontrol offers a seamless and efficient solution for automating Gatsby deployments directly to your AWS account. With Flightcontrol, users gain complete control over their deployments and have the freedom to modify configurations as needed. This platform not only simplifies the process of deploying Gatsby.js sites on AWS but also enhances the overall digital experience, surpassing other platforms in terms of usability and convenience.

### Steps to Resolve this Issue

I created a Flightcontrol documentation page. You can access it [here](https://github.com/gatsbyjs/gatsby/pull/38127)

**Comment by LekoArts** [comment]
Please see: https://github.com/gatsbyjs/gatsby/pull/38127#issuecomment-1569491912
