### ISSUE TITLE
Build stuck at createPagesStatefully

### ISSUE THREAD

**Issue by Graham42** [gatsbyjs/gatsby#3813]
## Description

Build never finishes, gets stuck at `createPagesStatefully`

### Environment

Gatsby version: 1.9.177
Node.js version: 8.9.4
Operating System: Ubuntu 16.04.3

### File contents (if changed):

Nothing was changed.

### Actual result

Build was stuck for 10 minutes until I killed it. Log:

<details>

```
success delete html files from previous builds — 0.040 s
success open and validate gatsby-config.js — 0.004 s
success copy gatsby files — 0.015 s
success onPreBootstrap — 0.005 s
success source and transform nodes — 0.014 s
success building schema — 0.068 s
success createLayouts — 0.023 s
success createPages — 0.000 s
⠐ createPagesStatefully^C
```

</details>

### Expected behavior

Site should build.

### Steps to reproduce

1\. `npm install -g gatsby`

2\. `gatsby new gatsby-site && cd gatsby-site`

3\. `gatsby build`

**Comment by tomazy** [comment]
Looks like this commit is the culprit: 6bbc0d17

**Comment by nsimonson** [comment]
Looks like it's because `done` is never called here: https://github.com/gatsbyjs/gatsby/blob/6bbc0d17a84a532c4d58ba5cba852be232114b51/packages/gatsby/src/internal-plugins/dev-404-page/gatsby-node.js

**Comment by monsieurnebo** [comment]
Same here, our deployment via CircleCI is stuck with gatsby v1.9.177.

**Comment by situplastik** [comment]
Same error. We think as @tomazy and @nsimonson that the problem is this commit.

**Comment by Graham42** [comment]
Would be good to have some integration tests to prevent something like this from happening in the future... should I open a separate issue for that?

**Comment by m-allanson** [comment]
@Graham42 There's plans for this but it's still a work in progress: https://github.com/gatsbyjs/gatsby/pull/3242

**Comment by rdricco** [comment]
Same here on Gitlab CI (but working fine locally on Windows 10).

**Comment by mpolinowski** [comment]
+1 Downgrading gatsby to v1.9.167 solved it for me. Thx m-allanson for the tip

**Comment by calcsam** [comment]
Fixed here: https://github.com/gatsbyjs/gatsby/commit/7bb93fe195d4c7d0683507da99c3b9602eee3657

**Comment by Graham42** [comment]
Thanks all for the quick resolution.

**Comment by monsieurnebo** [comment]
Thanks!
