### ISSUE TITLE
v2 - Don't generate source maps by default

### ISSUE THREAD

**Issue by tomazy** [gatsbyjs/gatsby#3817]
## Description

Gatsby by default generates very expressive source maps. They include the full, non-minified source code of the site, including all comments like TODO, etc. They also expose absolute paths to the project directory leaking things like user names and naming conventions. 

Source maps in general should not be available to anyone willing to open the dev tools in their browser. Access to them should be restricted and this requires some additional adjustments on the web server level. 

I suggest we disable the default source map generation in the next version of the project.

See: https://github.com/gatsbyjs/gatsby/issues/3324#issuecomment-361401512

**Comment by monsieurnebo** [comment]
A nice way of handling sourcemaps could be a config parameter, such as:

```js
// gatsby-config.js

module.exports = {

  pathPrefix    : "/blog",
  sourceMaps : true,
  // ...

}
```

It would let users choose when and where use them and would be particulary useful on multi-environments development (develop, staging, etc...).

**Comment by jquense** [comment]
I don't think not generating source maps the right approach. For every production app I've made we've wanted them either to load when devtools were opened or to upload to sentry for clearer error tracking. I think if you don't want them in your uploaded site that's more of publishing concern than a building on?

**Comment by KyleAMathews** [comment]
Instead of disabling sourcemaps by default — how about instead we a) investigate using relative paths, removing comments and otherwise making them more tidy by default and b) add a plugin to easily disable producing source maps by modifying the webpack config which also conveniently would speed up builds some.

**Comment by monsieurnebo** [comment]
@KyleAMathews I cannot see the advantage of a plugin instead of a basic gatsby-config parameter? 🤔

**Comment by KyleAMathews** [comment]
@monsieurnebo mainly because we avoid config options at (almost) all costs :-)

Adding config is a much weightier decision vs. a plugin. Also plugins are much more flexible than config.

**Comment by monsieurnebo** [comment]
Ok! Would this plugin's purpose be only to disable sourcemaps via webpack configuration? Isn't that a bit overkill?

**Comment by KyleAMathews** [comment]
@monsieurnebo that's how a config option would work so it's the same thing

**Comment by siakaramalegos** [comment]
So it looks like that might actually work. Either my finder wasn't refreshing the file list or the /public/folder was holding on to old sourcemap files.

**Comment by github0013** [comment]
This solved removing source map in v2.
https://github.com/gatsbyjs/gatsby/issues/6289

```bash
yarn add gatsby-plugin-no-sourcemaps@next
```

```json
  plugins: [
    "gatsby-plugin-no-sourcemaps",
  ]
```

**Comment by BillyWM** [comment]
Neither is working for me. `workbox`, used by `gatsby-plugin-offline` is still generating maps for all its files, so apparently all parts in the pipeline don't necessarily respect this setting.

Maybe that complain properly belongs in that plugin's repo, but it's
1. a plugin officially recommend in the official tutorial
2. a problem other plugins are going to be prone to. Need to override at the top level.

**Comment by j127** [comment]
I think having sourcemaps on by default in production is dangerous. There must be countless people out there who think their code comments, environment variable names, and source code are private because the output was minified, without realizing that everything is public. It seems like a security/privacy risk, because most people will assume that only the compiled version will be visible in production.

**Comment by ankurparihar** [comment]
Why do we need to develop and maintain separate plugin for a simple config option, which by the way should be a default setting in production?
