### ISSUE TITLE
Getting error on a freshly cloned Gatsby Blog with no changes "gatsby-config.ts" file failed to compile to "gatsby-config.js"

### ISSUE THREAD

**Issue by sudheerkaushik** [gatsbyjs/gatsby#38195]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Been a fan of Gatsbyjs since 2019 and just 2 weeks ago I decided to upgrade. Was getting some issues so I thought of creating a fresh project and to my surprise I am getting error while trying to run Gatsbyjs project. NO Single change has been made so far in this freshly cloned repository:

Here is the setup screenshot:

![image](https://github.com/gatsbyjs/gatsby/assets/8871502/6650ea4f-b36b-406e-8802-e0656710ed21)

Setup asked questions and started scaffolding things:
![image](https://github.com/gatsbyjs/gatsby/assets/8871502/bbb18db0-d370-4a57-8c91-7f64eba4ac68)

Switched to project folder and tried running it:

![image](https://github.com/gatsbyjs/gatsby/assets/8871502/6b67bca0-d041-4ef0-90ed-802d8836cf2d)

My environment:

![image](https://github.com/gatsbyjs/gatsby/assets/8871502/28af4be5-38f7-4d0e-bb7b-c0d97744d5b0)

### Reproduction Link

https://github.com/sudheerkaushik/gatsby-issue

### Steps to Reproduce

1. Clone Repo
2. Run npm install
3. Run `gatsby serve -o`
...

### Expected Result

Project was supposed to open index.js loaded in browser

### Actual Result

Getting error in Terminal : 

 ERROR #10127  API.TYPESCRIPT.COMPILATION

Your "gatsby-config.ts" file failed to compile to "gatsby-config.js". Please run "gatsby clean" and try again.

If the issue persists, please open an issue with a reproduction at https://gatsby.dev/new-issue for more help."

  Error: Cannot find package 'D:\Projects\sudhir-blog\gatsby-config'

  - get-config-file.ts:116 attemptImportUncompiled
    [sudhir-blog]/[gatsby]/src/bootstrap/get-config-file.ts:116:17

  - task_queues:95 processTicksAndRejections
    node:internal/process/task_queues:95:5

  - get-config-file.ts:24 getConfigFile
    [sudhir-blog]/[gatsby]/src/bootstrap/get-config-file.ts:24:28

  - serve.ts:110 module.exports
    [sudhir-blog]/[gatsby]/src/commands/serve.ts:110:28

### Environment

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.18 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.11.0
  Browsers:
    Edge: Spartan (44.22621.1778.0), Chromium (113.0.1774.57)
  npmGlobalPackages:
    gatsby: 5.6.0
```

**Comment by sudheerkaushik** [comment]
Project ran once for a scenario:

1. I ran `gatsby build`
2. Ran `gatsby serve -o` , site opened up in Chrome and showed content from index.tsx
3. Changed content, but page did not reloaded, on refresh too no content change.
4. Ran `gatsby clean` followed by `gatsby serve -o` , error comes again


![image](https://github.com/gatsbyjs/gatsby/assets/8871502/5f72411e-bf55-4bd5-ad51-9f7c81420390)

**Comment by LekoArts** [comment]
Hi!

I think you misunderstood how the Gatsby CLI commands work and how you can develop a Gatsby site. These things haven't changed since 2019 though.

Here's an overview of the commands: https://www.gatsbyjs.com/docs/reference/gatsby-cli/
And here's a introduction tutorial that explains how you can develop your site: https://www.gatsbyjs.com/docs/tutorial/getting-started/part-1/#run-your-site-locally

Essentially:

- `gatsby serve` is only there to serve the site after a `gatsby build`. No hot reloading expected.
- Use `gatsby develop` to preview your site and see hot reloading
