### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'key') from react component library using emotion css prop

### ISSUE THREAD

**Issue by kimbaudi** [gatsbyjs/gatsby#38193]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I created a gatsby site using @emotion & gatsby-plugin-emotion. I also created a npm package that is a react component library using @emotion. When I install my react component library from my gatsby site and render a component from the library that uses @emotion css prop, and I run `gatsby build`, I get the following error:

> `WebpackError: TypeError: Cannot read properties of null (reading 'key')`

If I run `gatsby develop`, then I get no error so it only affects production builds w/ SSR. I even installed/configured `gatsby-plugin-emotion`, but I still get the error.

### Reproduction Link

https://github.com/kimbaudi/my-gatsby-site

### Steps to Reproduce

I created 2 repos:

- https://github.com/kimbaudi/testreacttslib (react component library using @emotion css prop)
- https://github.com/kimbaudi/my-gatsby-site (gatsby site consuming react component lib)

To reproduce, 
clone the my-gatsby-site repo, which consumes testreacttslib npm library. run `npm install`, & `npm run build`

```shell
git clone https://github.com/kimbaudi/my-gatsby-site.git
cd my-gatsby-site
npm install
npm run build
```

### Expected Result

I expected `gatsby build` to build without any error

### Actual Result

`gatsby build` throws `WebpackError: TypeError: Cannot read properties of null (reading 'key')`. 

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Binaries:
    Node: 18.12.0 - C:\Program Files\nodejs\node.EXE     
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD       
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD        
  Languages:
    Python: 3.10.5 - /c/Python310/python
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.57)
  npmPackages:
    gatsby: ^5.10.0 => 5.10.0
    gatsby-plugin-emotion: ^8.10.0 => 8.10.0
  npmGlobalPackages:
    gatsby-cli: 5.10.0
```

**Comment by LekoArts** [comment]
Hi!

Please open an issue for this at https://github.com/emotion-js/emotion/issues. Thanks!
