### ISSUE TITLE
"Unspecified fatal error encountered, aborting" during Sharp image processing on Windows

### ISSUE THREAD

**Issue by FraserThompson** [gatsbyjs/gatsby#38206]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

On the latest version of gatsby, gatsby-plugin-sharp, gatsby-plugin-image (5.10.0) my builds eventually fail on the image processing step with this error:

<img width="250" alt="error" src="https://github.com/gatsbyjs/gatsby/assets/6093858/2a14a179-cdb9-45cc-a979-2386d49e2b0a">

In verbose mode I also see in console: `smartcrop: no property named 'premultiplied'`

And occasionally I see this error: `g_win32_pop_invalid_parameter_handler: assertion 'handler->pushed_handler == popped_handler' failed`

It appears to be related to sharp and/or libvips and pinning the sharp version to the previous (0.31.3) solves the issue.

I'm on Windows 11, not sure if it affects 10 as well.

### Reproduction Link

https://github.com/gatsbyjs/gatsby-starter-blog

### Steps to Reproduce

1. Make a gatsby site with a bunch of images and sharp processing
2. Build the site on Windows
3. Wait until it starts processing images

### Expected Result

Success

### Actual Result

Errors

### Environment

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.6.7 - ~\AppData\Roaming\npm\npm.CMD
  Languages:
    Python: 3.11.3
  Browsers:
    Chrome: 114.0.5735.110
    Edge: Spartan (44.22621.1702.0), Chromium (114.0.1823.41)
  npmGlobalPackages:
    gatsby-cli: 5.10.0
```

**Comment by LekoArts** [comment]
Hi!

Please open an issue on https://github.com/lovell/sharp/issues for this. Thanks!
