### ISSUE TITLE
allWpCategory count post is not updating in wpgraphql using gatsby-source-wordpress.

### ISSUE THREAD

**Issue by sarniel** [gatsbyjs/gatsby#38200]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

My problem is the category count post, the graphql is not updating when I start assigning post in the categories. It's still showing null, even though there is a post in the category. I understand, running clean will fix everything, but shouldn't be automatically updating the graphql as will as in the gatsby cloud?

Here is the simple query.

`  allWpCategory(filter: {slug: {eq: "boxing"}}) {
    nodes {
      name
      count
    }
  }
`

The count value here should be the same as the wp-admin category.

### Reproduction Link

none

### Steps to Reproduce

1. Assign a post to any empty category. (ex: boxing)
2. Now get the count from the category boxing
`  allWpCategory(filter: {slug: {eq: "boxing"}}) {
    nodes {
      name
      count
    }
  }
`
3. The value of the count should be 1.

### Expected Result

I'm expecting to see value in the category count without clearing the cache.

### Actual Result

`{
  "data": {
    "allWpCategory": {
      "nodes": [
        {
          "name": "Boxing",
          "count": null
        }
      ]
    }
  },
  "extensions": {}
}`

### Environment

```shell
//
```

### Config Flags

//

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by sarniel** [comment]
Hi LekoArts,

Thank you for your immediate response, I'm trying to make a dummy Wordpress, but I'm unsure if this is the right way to do it for reproduction. 

Steps:

1. Please pull this repo git@github.com:sarniel/gatsby-starter-wordpress-blog.git
2. And go to http://localhost:8000/___graphql and run this query
`query MyQuery {
  allWpCategory {
    nodes {
      name
      count
    }
  }
}`
3. Login to wp-admin user account below and modify one of the posts, moving it to another category.

https://admin.to-educate.com/wp-admin/
username: user    
pwd: D4^Y!P%P!GJ03!S#rBNztVV&

4. After saving, the "Count" value in the graphql allWpCategory should be also updated when the post is triggered, as they are somehow related.


Was this intended behavior? or did I miss something here? I hope it makes sense to you. I'm looking forward to your help.

Thanks!

**Comment by elisavetTriant** [comment]
Hello, any chance on looking into this? Is this something to be expected? Any ideas on workarounds? Thank you in advance.

**Comment by webdevi121** [comment]
Hi @elisavetTriant , unfortunately, nothing. I'm still waiting for an answer as well. It's one of the major problems that I'm facing with using gatsby as an SSG.

**Comment by elisavetTriant** [comment]
@sarniel Thank you for taking the time to open this issue.

@sarniel @webdevi121 I'm not sure we are facing with the same issue exactly, so I'll try to expand a bit on my research thus far.

For my use case, I'm using a query like this on taxonomy lists and tag clouds Components, both on default taxonomies (category, post_tag, etc) and on custom taxonomies,  and they don't seem to [hydrate](https://www.gatsbyjs.com/docs/conceptual/react-hydration/) with the saving of post related information. Neither the count field data nor the related contentNodes of the related term(s) influenced by the post that they are related to. So I'm scratching my head on where I can catch the related contentNodes count, and to get it to "hydrate" without cleaning the cache and rebuilding every time.

What I can see at the dev server from the listener of the Gatsby plugin, is that it IS actually creating, updating or deleting post nodes plus updating author information.

One other thing to consider, is that WordPress itself does NOT update automatically the count with such operations but rather deep inside of its lifecycle. Take a look at this private function for instance: [_update_post_term_count/](https://developer.wordpress.org/reference/functions/_update_post_term_count/)

So really at this point I would appreciate any feedback and/or guidance on this issue. Thank you in advance.
