### ISSUE TITLE
gatsby-source-filesystem warning on Jetbrains

### ISSUE THREAD

**Issue by dmxt** [gatsbyjs/gatsby#38207]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I use JetBrains, and I have 4 warnings every time I push because of multiple `gatsby-plugin-image`

I tried to get it to 0, but it won't function correctly.

### Reproduction Link

https://github.com/dmxt/dmxt-blog

### Steps to Reproduce

I have 4 warnings regarding multiple "gatsby-source-filesystem" in my gatsby-config

```javascript
    `gatsby-plugin-image`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content/blog`,
        name: `blog`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/content/img`,
      },
    },
```

Screenshot:
<img width="503" alt="Screenshot 2023-06-08 at 2 13 55 PM" src="https://github.com/gatsbyjs/gatsby/assets/3248782/abcea589-0beb-42ef-895b-4733e0443352">

### Expected Result

0 warning

### Actual Result

4 warnings indicating I have 4`gatsby-source-filesystem` in my gatsby-config.json

### Environment

```shell
System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.7.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 110.0
    Safari: 16.6
  npmPackages:
    gatsby: ^4.23.0 => 4.25.4 
    gatsby-plugin-feed: ^4.23.0 => 4.24.0 
    gatsby-plugin-google-gtag: ^5.10.0 => 5.10.0 
    gatsby-plugin-image: ^2.23.0 => 2.24.0 
    gatsby-plugin-manifest: ^4.23.0 => 4.24.0 
    gatsby-plugin-sharp: ^4.23.0 => 4.24.0 
    gatsby-remark-copy-linked-files: ^5.23.0 => 5.24.0 
    gatsby-remark-images: ^6.23.0 => 6.24.0 
    gatsby-remark-prismjs: ^6.23.0 => 6.24.0 
    gatsby-remark-responsive-iframe: ^5.23.0 => 5.24.0 
    gatsby-remark-smartypants: ^5.23.0 => 5.24.0 
    gatsby-source-filesystem: ^4.23.0 => 4.24.0 
    gatsby-transformer-remark: ^5.23.0 => 5.24.0 
    gatsby-transformer-sharp: ^4.23.0 => 4.24.0 
  npmGlobalPackages:
    gatsby-cli: 5.5.0
```

### Config Flags

No

**Comment by LekoArts** [comment]
Hi!

You'll want to reach out to JetBrains for support on this. Defining multiple `gatsby-source-filesystem` or really any plugins is just fine. It's working as intended and there's nothing for us to fix.
