### ISSUE TITLE
api route work in the local environment, but 404 in the production environment

### ISSUE THREAD

**Issue by no13bus** [gatsbyjs/gatsby#38230]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi, everyone, I just use the api route in the local eniverment, I add the src/api/handler.js, here is the code
```
export default function handler(request, response) {
  response.status(200).json({
    body: request.body,
    query: request.query,
    cookies: request.cookies,
  });
}
```

when I open the url http://localhost:8000/api/handler, it is ok. But when I deploy it to the production envirement with vercel, it has 404 error.

Gastby version is 3.x.

### Reproduction Link

https://github.com/no13bus/happyCV

### Steps to Reproduce

1.add the src/api/handler.js
2. the code is 
```
export default function handler(request, response) {
  response.status(200).json({
    body: request.body,
    query: request.query,
    cookies: request.cookies,
  });
}
```
3. deploy it in the vercel
...

### Expected Result

in the vercel environment, when open http://aaaaa.com/api/handler, return json data.  

### Actual Result

404 error

### Environment

```shell
gastby version: 3.8.0
node: 18
```

### Config Flags

no

**Comment by LekoArts** [comment]
Hi!

Please open a support ticket with Vercel as this has something to do with your deployment there. Thanks!
