### ISSUE TITLE
Gatsby intro tutorial is showing wrong (outdated) GraphQL queries 

### ISSUE THREAD

**Issue by harrisdeploy** [gatsbyjs/gatsby#38252]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

I am new to Gatsby and currently up to parts 5 & 6 of the tutorial. 

I encountered a discrepancy between the queries coming up on my own GraphiQL versus [the ones in the tutorial](https://www.gatsbyjs.com/docs/tutorial/getting-started/part-5/#task-update-the-blog-page-query-to-use-the-allmdx-field-instead-of-allfile).

For example, 
`frontmatter {
          date(formatString: "MMMM D, YYYY")
          title
        }
`
But on my end, this is all that shows for this snippet, 
`      frontmatter {
        name
        datePublished
        author
      }
`

More problematically, part 6 requests the user to utilise a 'slug' query but this isn't available anywhere at all in my GraphiQL. 

In fact, it may have been removed entirely during from the transformer plugin 'gatsby-plugin-mdx'. [There was a migration from V3 to V4 where certain queries were deleted](https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/#extending-the-graphql-mdx-nodes) such as, '...timeToRead, rawBody, slug, headings, html, mdxAST, wordCount, fileAbsolutePath from the query result.'

There is a [means](https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/#extending-the-graphql-mdx-nodes) of bringing those queries back.

I have posted a [question](https://stackoverflow.com/questions/76469870/graphiql-doesnt-show-date-or-allow-formatstring-function-in-the-browser-sch) on StackOverflow regarding this too. 

### Steps to Resolve this Issue

1. Updating the documentation in light of such developments to 'gatsby-plugin-mdx' and the missing/changedGraphQL queries 
2.
3.
...

**Comment by LekoArts** [comment]
Hi!

I'm assuming that you followed these instructions:
![CleanShot 2023-06-26 at 07 58 44](https://github.com/gatsbyjs/gatsby/assets/16143594/23a290ac-921c-44f4-aaae-1c555343978a)

Since you can query what is shown there.

But you want to actually create these files:

![CleanShot 2023-06-26 at 07 59 30](https://github.com/gatsbyjs/gatsby/assets/16143594/33dad4fc-7c08-49f9-915f-5a782c5a0177)

Then you'll have the fields available.
