### ISSUE TITLE
Warning: smartcrop: no property named `premultiplied'  while Running gatsby-plugin-sharp.IMAGE_PROCESSING jobs

### ISSUE THREAD

**Issue by a-bochilo** [gatsbyjs/gatsby#38257]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

While compile app via gatsby develop command every time (when cache was cleared) next warning appears: 

> [                            ]   0.005 s 0/2 0% Running gatsby-plugin-sharp.IMAGE_PROCESSING jobs
> 
> ** (process:7844): WARNING **: 10:47:10.924: smartcrop: no property named `premultiplied'

Process number different every time.
And sometime error occurs and build become aborted. Next run have a chance to be successful but error could appear several times in a row.

![image](https://github.com/gatsbyjs/gatsby/assets/103776395/c166d031-abfe-4f4b-9361-ce3ce67f269d)

![image](https://github.com/gatsbyjs/gatsby/assets/103776395/722cac93-876d-471d-a051-854d7b1e6659)

### Reproduction Link

https://github.com/a-bochilo/gatsby-bug

### Steps to Reproduce

1. clone repository
2. install all the packages with 'npm i' command
3. run dev server with 'gatsby develop' command
4. watch the process in the terminal
...

### Expected Result

App compiled without any errors and warnings

### Actual Result

WARNING **: 10:47:10.924: smartcrop: no property named `premultiplied' appears

"Unspecified fatal error encountered, aborting." error appears.

### Environment

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.11.3
  Browsers:
    Edge: Spartan (44.22621.1848.0), Chromium (114.0.1823.51)
  npmPackages:
    gatsby: ^5.11.0 => 5.11.0 
    gatsby-plugin-image: ^3.11.0 => 3.11.0 
    gatsby-plugin-sharp: ^5.11.0 => 5.11.0 
    gatsby-source-filesystem: ^5.11.0 => 5.11.0 
    gatsby-source-filesystem-markdown-name: ^1.0.1 => 1.0.1 
    gatsby-transformer-remark: ^6.11.0 => 6.11.0 
    gatsby-transformer-sharp: ^5.11.0 => 5.11.0 
  npmGlobalPackages:
    gatsby-cli: 5.10.0
```

**Comment by LekoArts** [comment]
Hi!

Please open an issue at https://github.com/libvips/libvips/ since Gatsby uses `sharp` which in turn uses this. The error is most probably coming from there.
