### ISSUE TITLE
gatsby-plugin-image – Failed prop type: The prop `alt` is marked as required in `MainImage`, but its value is `undefined`.

### ISSUE THREAD

**Issue by therealgilles** [gatsbyjs/gatsby#38259]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

During the gatsby build, I see odd warning messages about missing `alt` tags with no pointer to which image(s) are concerned.

```TSX
Warning: Failed prop type: The prop `alt` is marked as required in `MainImage`, but its value is `undefined`.
    at MainImage
    at U (.../node_modules/gatsby-plugin-image/dist/gatsby-image.js:1:10921)

 ERROR  UNKNOWN

Warning: Failed prop type: The prop `alt` is marked as required in `A`, but its value is `undefined`.
    at A .../node_modules/gatsby-plugin-image/dist/gatsby-image.js:1:7460)
    at T (.../node_modules/gatsby-plugin-image/dist/gatsby-image.js:1:7721)
    at MainImage
    at F (.../node_modules/gatsby-plugin-image/dist/gatsby-image.js:1:10569)
    at div
    at U (.../node_modules/gatsby-plugin-image/dist/gatsby-image.js:1:10921)
```

I have no `MainImage` nor `A` components in my repo. Please improve/fix.

### Reproduction Link

N/A

### Steps to Reproduce

I have no idea how to reproduce this as the error message is too obscure to figure it out.

### Expected Result

The plugin should say which image is missing the `alt` tag.

### Actual Result

See warning/error message above.

### Environment

```shell
System:
    OS: macOS 13.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.9 - /bin/zsh
  Binaries:
    Yarn: 1.22.10 - ~/.yvm/shim/yarn
    npm: 9.7.1 - /var/folders/pd/_hnt8dqd19g05yjbj_mngrr40000gn/T/fnm_multishells/4399_1686893467220/bin/npm
  Languages:
    Python: 3.8.5 - .../.pyenv/shims/python
  Browsers:
    Chrome: 114.0.5735.133
    Firefox: 114.0.1
    Safari: 16.6
  npmPackages:
    gatsby: ^5.11.0 => 5.11.0
    gatsby-background-image: ^1.6.0 => 1.6.0
    gatsby-image: ^3.11.0 => 3.11.0
    gatsby-link: ^5.11.0 => 5.11.0
    gatsby-plugin-emotion: ^8.11.0 => 8.11.0
    gatsby-plugin-eslint: ^4.0.4 => 4.0.4
    gatsby-plugin-graphql-config: ^1.14.0 => 1.14.0
    gatsby-plugin-image: ^3.11.0 => 3.11.0
    gatsby-plugin-manifest: ^5.11.0 => 5.11.0
    gatsby-plugin-offline: ^6.11.0 => 6.11.0
    gatsby-plugin-postcss: ^6.11.0 => 6.11.0
    gatsby-plugin-purgecss: ^6.2.1 => 6.2.1
    gatsby-plugin-react-helmet: ^6.11.0 => 6.11.0
    gatsby-plugin-sharp: ^5.11.0 => 5.11.0
    gatsby-plugin-styled-components: ^6.11.0 => 6.11.0
    gatsby-plugin-typegen: ^3.1.0 => 3.1.0
    gatsby-plugin-typescript: ^5.11.0 => 5.11.0
    gatsby-source-filesystem: ^5.11.0 => 5.11.0
    gatsby-source-graphql: ^5.11.0 => 5.11.0
    gatsby-source-wordpress: ^7.11.0 => 7.11.0
    gatsby-transformer-sharp: ^5.11.0 => 5.11.0
  npmGlobalPackages:
    gatsby-cli: 5.3.1
```

### Config Flags

    FAST_DEV: false,
    DEV_SSR: false,
    PRESERVE_FILE_DOWNLOAD_CACHE: true,
    PARALLEL_SOURCING: true,
    // causes featuredImage.node null issues
    DETECT_NODE_MUTATIONS: false,

**Comment by LekoArts** [comment]
Hi!

You're using `gatsby-background-image`, so my best guess is that you're missing some `alt` tags in your usage of it there. You can also run `gatsby develop` and check the browser console to see the same warning, it should point to the culprit. The plugin is working as intended so it's not a bug but a user error. Moreover, without a [minimal reproduction][reproduction] we can't help anyways.

[reproduction]: https://gatsby.dev/reproduction

**Comment by therealgilles** [comment]
@LekoArts I appreciate the quick response.
> You can also run gatsby develop and check the browser console to see the same warning, it should point to the culprit.

This is what I did (even used the `--verbose` flag) and the only warning/error messages I got were the ones I pasted in my report. As you can see, there is no indication of what the culprit is. In my opinion, that's the bug. It's also clearly pointing to `gatsby-plugin-image`, not `gatby-background-image`. I have the latter installed but I don't use it anywhere in my code.

Additionally as seen in the report I pasted above, it says "ERROR UNKNOWN". That's another bug. Gatsby should not be generated any unknown errors.

Lastly, I have checked all my usages of `gatsby-plugin-image` in my code and they have have the `alt` prop specified. The only thing I can image is that one of the images coming from `gatsby-source-wordpress` is missing the `alt` tag but that's multiple dozens of images and again I should be allowed to expect some kind of image name or reference. Which is clearly not there. Meaningful error messages should not be nice-to-have or feature request, so in my opinion, this is clearly a bug.

**Comment by therealgilles** [comment]
FYI I disabled `gatsby-background-image` from `gatsby-config` and got the exact same error message, here again:
```TSX
 ERROR  UNKNOWN

Warning: Failed prop type: The prop `alt` is marked as required in `MainImage`, but its value is `undefined`.
    at MainImage
    at U (.../node_modules/gatsby-plugin-image/dist/gatsby-image.js:1:10921)


 ERROR  UNKNOWN

Warning: Failed prop type: The prop `alt` is marked as required in `A`, but its value is `undefined`.
    at A (.../node_modules/gatsby-plugin-image/dist/gatsby-image.js:1:7460)
    at T (.../node_modules/gatsby-plugin-image/dist/gatsby-image.js:1:7721)
    at MainImage
    at F (.../node_modules/gatsby-plugin-image/dist/gatsby-image.js:1:10569)
    at div
    at U (.../node_modules/gatsby-plugin-image/dist/gatsby-image.js:1:10921)
```

**Comment by therealgilles** [comment]
How come `altValidator` is not used in all the places where the `alt` prop is required in `gatsby-plugin-image`?
```TSX
export const altValidator: PropTypes.Validator<string> = (
  props: GatsbyImageProps,
  propName,
  componentName,
  ...rest
): Error | undefined => {
  if (!props.alt && props.alt !== ``) {
    return new Error(
      `The "alt" prop is required in ${componentName}. If the image is purely presentational then pass an empty string: e.g. alt="". Learn more: https://a11y-style-guide.com/style-guide/section-media.html`
    )
  }

  return PropTypes.string(props, propName, componentName, ...rest)
}
```

All the places where it's missing:
- https://github.com/gatsbyjs/gatsby/blob/f8a758c51b0c894841c184c1b0657504872e528c/packages/gatsby-plugin-image/src/components/picture.tsx#L100
- https://github.com/gatsbyjs/gatsby/blob/f8a758c51b0c894841c184c1b0657504872e528c/packages/gatsby-plugin-image/src/components/picture.tsx#L92

Then you could enhance `altValidator` to display the other props of the component. That would give users a lot more clues as to which image is at fault.

**Comment by therealgilles** [comment]
I should add that the error/warning happens when running `gatsby-source-wordpress`, here is the log line above the error/warning:
```TSX
success  gatsby-source-wordpress  Post - 2.529s - fetched 10
```

**Comment by therealgilles** [comment]
I traced it down to this image data:
```JSON
{
    "alt": undefined,
    "children": null,
    "className": undefined,
    "data-gatsby-image-ssr": "",
    "data-wp-inline-image": "4",
    "children": null,
    "fallback": {
        "src": "/_gatsby/image/...",
        "srcSet": "/_gatsby/image/... 256w,/_gatsby/image/... 512w,/_gatsby/image/... 1024w",
        "sizes": "(min-width: 1024px) 1024px, 100vw"
    },
    "sources": [],
    "loading": "lazy",
    "shouldLoad": false,
    "data-main-image": "",
    "style": {
        "height": "100%",
        "left": 0,
        "position": "absolute",
        "top": 0,
        "transform": "translateZ(0)",
        "transition": "opacity 250ms linear",
        "width": "100%",
        "willChange": "opacity",
        "opacity": 0
    }
}```

As you can see, this has nothing to do with my source code. This is an image source from WordPress and many images in WordPress have no `alt` field because WordPress defines the field as follows:
<img width="598" alt="Screenshot 2023-07-04 at 3 01 48 PM" src="https://github.com/gatsbyjs/gatsby/assets/18076992/19f2275f-dd43-4499-8900-e7e780deff7f">

In my opinion, there is:
- A `gatsby-source-wordpress` bug, it should either warn about the image or behave like WordPress, i.e. add an empty field
- A `gatby-plugin-image` bug, it should be reporting the image URL

**Comment by therealgilles** [comment]
The bug in `gatsby-plugin-image` seems to be here: https://github.com/gatsbyjs/gatsby/blob/b074b8545c7c0c1d11ff042a444ef698ba84c7c3/packages/gatsby-plugin-image/src/components/gatsby-image.server.tsx#L105C1-L105C1
where it's not adding a default `alt` prop.

**Comment by therealgilles** [comment]
And here in `gatsby-source-wordpress`, `alt` can easily be `undefined`:
https://github.com/gatsbyjs/gatsby/blob/b074b8545c7c0c1d11ff042a444ef698ba84c7c3/packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js#L673

**Comment by therealgilles** [comment]
@LekoArts Hopefully this is enough information for you to take another look and fix these bugs in Gatsby plugins code 🤞🏻
