### ISSUE TITLE
sliceMap doesn't seem to work in a 404 page created via createPage

### ISSUE THREAD

**Issue by dbismut** [gatsbyjs/gatsby#38263]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

It seems like there is an issue with slice maps and a 404 page that would be created with `createPages` rather than having a `404.js` file in the `pages` directory. My use case is similar to [the one discussed here](https://github.com/gatsbyjs/gatsby/discussions/16176#discussioncomment-2526740), with the 404 page context needing to be fed with graphql data.

I also decided to try the new Slice feature (which is incredible, thank you for this). Since my website is localized, I'm also using the `slices` attribute in `createPages` [as described here](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-slice/#aliases) in order to have localized slices.

However, it looks like when the 404 page is reached when redirecting to it when a page doesn't exist, the slices alias don't seem to work properly.

### Reproduction Link

https://codesandbox.io/p/sandbox/admiring-lucy-cz3nm4

### Steps to Reproduce

1. Navigate to a non existing page (ie https://cz3nm4-8000.csb.app/awol)
2. The dev 404 page should show
3. Click on Preview custom 404 page
4. You should get an error with the slice not existing

### Expected Result

However, if you go to the 404 page https://cz3nm4-8000.csb.app/404 everything behaves properly.

<img width="377" alt="image" src="https://github.com/gatsbyjs/gatsby/assets/5003380/9ae025bb-d911-426a-a6b4-27d30551c21c">

### Actual Result

**Mapped slice is missing:**

<img width="881" alt="image" src="https://github.com/gatsbyjs/gatsby/assets/5003380/265ff946-a046-43c6-b6ca-e09b17a5effc">

### Environment

```shell
Codesandbox env:

  System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11
(bullseye)
    CPU: (2) x64 AMD EPYC
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
  npmPackages:
    gatsby: ^5.11.0 => 5.9.1
```

**Comment by pieh** [comment]
We merged a fix and for now released it in `@next` dist tag - `gatsby@5.12.0-next.1`. This will be published to stable likely next week.

Thanks for providing reproduction!
