### ISSUE TITLE
Path rewrite

### ISSUE THREAD

**Issue by theduke** [gatsbyjs/gatsby#383]
For some pages, I want to to change the URL path in the router to not map directly to the path on the filesystem.

For example: a blog post in a file "blog/2015-01-01-post-title" should have a path "blog/post-title".

Where can I hook into the route building process to change that?

**Comment by theduke** [comment]
Ok, seems like Gatsby automatically rewrites the path if the page has a metadata field "path".

This should really be documented somewhere!

**Comment by KyleAMathews** [comment]
You can also programatically rewrite paths by exporting a `rewritePath` in gatsby-node.js. Also not documented yet :-\

https://github.com/gatsbyjs/gatsby/blob/364a5496ce172e117cc9fc7b10bb1e338693c2ec/lib/utils/build-page/url-resolver.js#L11

See my blog for an example https://github.com/KyleAMathews/blog/blob/master/gatsby-node.js

**Comment by JanoshRiebesell** [comment]
Would be really cool if some documentation would be added for `rewritePath` at some point!

**Comment by digitaldiy** [comment]
Can something like next.js approach be implemented?
https://nextjs.org/docs/api-reference/next.config.js/rewrites

**Comment by KyleAMathews** [comment]
@digitaldiy and others this is a very old issue from pre Gatsby-v1 :-D

Generally speaking there's two options — `createRedirect` or `onCreatePage` https://www.gatsbyjs.com/docs/reference/config-files/actions/#createRedirect & https://www.gatsbyjs.com/docs/creating-prefixed-404-pages-for-different-languages/#reach-skip-nav but if you have a specific request/need, please open a new issue!

**Comment by digitaldiy** [comment]
Is there a simple way to achieve the code below (next.js), the reason being is that one treatment can have loads of categories but the page is exactly the same so there's no point in duplication but rather a rewrite so people can still see the category/treatment in the search bar but be taken to the right page, this is super useful for categorisation in general ( think how amazon has there departments but products are in loads of categories at the same time but are still listed under the categories you clicked on. Thanks in advance.

 async rewrites() {
      return [
        {
          source: '/:category/:treatment',
          destination: '/treatments/:treatment',
        }, 
      ]
    },

**Comment by KyleAMathews** [comment]
Yes, those are redirects. We don't have a way to bulk match the source/destination but you can create redirects for each page while you're creating the pages as well https://www.gatsbyjs.com/docs/reference/config-files/actions/#createRedirect

**Comment by digitaldiy** [comment]
Thanks for the link ill go through that now, may I ask if there Is plans to implement a system like this in the feature ( say Gatsby 5), thanks for your help
