### ISSUE TITLE
fresh gatsby-starter-blog-theme install has FOUC issues and styles broken on mobile chrome

### ISSUE THREAD

**Issue by kerematam** [gatsbyjs/gatsby#38339]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Well, this seems to be FOUC issue. But on mobile Chrome, it does not even triggers refresh.

### Reproduction Link

https://github.com/kerematam/gatsby-starter-blog-theme-bug

### Steps to Reproduce

1. `npx gatsby new my-themed-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme`
2. `npm run build`
3. Check the site on a mobile browser - NOT(!) on the mobile view of desktop browser.
...

### Expected Result

No FOUC, or at least refresh to be triggered on mobile browser.

### Actual Result

FOUC and styles are broken on mobile chrome.

### Environment

```shell
System:
Node v18

I've tried various mobile phones, all are on android. Here is one of them:
Application version
Chrome 111.0.5563.115
Operating system
Android 7.0; SM-G955F Build/NRD90M
```

**Comment by kerematam** [comment]
Deployed: https://gatsbystarterblogthemebugmain.gatsbyjs.io/

**Comment by LekoArts** [comment]
Hi!

I don't have a lot of android phones at hand, the ones I tested don't show the behavior you're describing. Also not on desktop chrome happening.

Anyways, I'd recommend using https://github.com/gatsbyjs/gatsby-starter-blog instead as a starting point since this one is still maintained. The starter with the theme is most likely outdated.

**Comment by kerematam** [comment]
Thank you for the recommendation! Sadly, I switched to the boilerplate after spending some time on this theme and ended up spending some extra time transferring my work there.

I understand there must be a lot of other priorities, but it's a lot easier to fall into using this outdated blog theme from the documentation than starting with this more actively maintained boilerplate. So, an update to the docs could help newcomers like me: https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/using-a-gatsby-theme/

Alternatively, converting this boilerplate into a theme could also be an option.

This is the desktop view:
![image](https://github.com/gatsbyjs/gatsby/assets/5495509/d958cf4a-226a-4a0d-ac6d-8461df0b3183)

This is from BrowserStack, just pick the one you like. Almost all have this issue:

<video src='https://github.com/gatsbyjs/gatsby/assets/5495509/7a55bd46-2d0a-4fe7-9301-5ec20b755de7' width=180/>

**Comment by LekoArts** [comment]
The video doesn't show a flash of unstyled content and the website looks like it's supposed to look like. Can you point out in more detail what you're expecting?

**Comment by kerematam** [comment]
- You may check how flicker happens on the desktop view. It is observable on avatar icon. I've intentionally did not add anything else to the site. When I add more styled content, their styles come after that flicker.
- On mobile, it does not reload/flicker. Video is showing mobile view does not have the correct background. (I've assumed if it could reload it would still work somehow).
