### ISSUE TITLE
gatsby-source-wordpress causes ssr pages timeouts on Netlify

### ISSUE THREAD

**Issue by Karol-Waliszewski** [gatsbyjs/gatsby#38343]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

It is stated that using graphQL in SSR pages is permitted... However when using it along with gatsby-source-wordpress plugin the page just breaks. 

The plugin starts as if it was just a build instead of SSR page and tries to fetch the data which results in timeout..
It doesn't matter if query contains gatsby image or not.

info  gatsby-source-wordpressJul 5, 11:47:57 AM: 5deea6e9 This is either your first build or the cache was cleared.Jul 5, 11:47:57 AM: 5deea6e9 Please wait while your WordPress data is synced to your Gatsby cache.Jul 5, 11:47:57 AM: 5deea6e9 Maybe now's a good time to get up and stretch? :DJul 5, 11:47:57 AM: 5deea6e9 2023-07-05T09:48:09.067Z 5deea6e9-85e9-47dc-9a50-782d092a9f29 Task timed out after 10.03 seconds

### Reproduction Link

https://gatsby-middleware.netlify.app/warszawa/nova-viva-garden/46

### Steps to Reproduce

1. Gatsby 5 SSR + gatsby-source-wordpress + netlify plugins
2. Create SSR page with GraphQL query
3. Breaks on Netlify

### Expected Result

Works

### Actual Result

Breaks

### Environment

```shell
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.6.5 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Languages:
    Python: 3.10.10 - /Users/karolwaliszewski/miniconda3/bin/python
  Browsers:
    Chrome: 114.0.5735.198
    Firefox: 106.0.5
    Safari: 16.1
  npmPackages:
    gatsby: 5.8.1 => 5.8.1
    gatsby-plugin-canonical-urls: 5.8.0 => 5.8.0
    gatsby-plugin-eslint: 4.0.4 => 4.0.4
    gatsby-plugin-google-analytics: 5.8.0 => 5.8.0
    gatsby-plugin-google-tagmanager: 5.8.0 => 5.8.0
    gatsby-plugin-hotjar: 1.1.1 => 1.1.1
    gatsby-plugin-image: 3.8.0 => 3.8.0
    gatsby-plugin-manifest: 5.8.0 => 5.8.0
    gatsby-plugin-netlify: 5.1.0 => 5.1.0
    gatsby-plugin-nprogress: 5.8.0 => 5.8.0
    gatsby-plugin-offline: 6.8.0 => 6.8.0
    gatsby-plugin-react-helmet: 6.8.0 => 6.8.0
    gatsby-plugin-remove-serviceworker: 1.0.0 => 1.0.0
    gatsby-plugin-remove-trailing-slashes: 4.19.0 => 4.19.0
    gatsby-plugin-robots-txt: 1.8.0 => 1.8.0
    gatsby-plugin-sharp: 5.8.1 => 5.8.1
    gatsby-plugin-sitemap: 6.8.0 => 6.8.0
    gatsby-plugin-styled-components: 6.8.0 => 6.8.0
    gatsby-plugin-svgr: 3.0.0-beta.0 => 3.0.0-beta.0
    gatsby-plugin-typescript: 5.8.0 => 5.8.0
    gatsby-plugin-web-font-loader: 1.0.4 => 1.0.4
    gatsby-plugin-webpack-bundle-analyser-v2: 1.1.30 => 1.1.30
    gatsby-source-filesystem: 5.8.0 => 5.8.0
    gatsby-source-wordpress: 7.8.0 => 7.8.0
    gatsby-theme-i18n: 3.0.0 => 3.0.0
    gatsby-theme-i18n-react-i18next: 3.0.0 => 3.0.0
    gatsby-transformer-sharp: 5.8.0 => 5.8.0
```

### Config Flags

FAST_DEV: true,
PARALLEL_SOURCING: true,

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
