### ISSUE TITLE
[gatsby-plugin-sitemap] Documentation error in `filterPages` function.

### ISSUE THREAD

**Issue by evad1n** [gatsbyjs/gatsby#38364]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

The [documentation for the plugin](https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap/#filterpages--codebooleancode) incorrectly states the 2nd parameter is a single entry from the `excludes` Array, but it is actually the whole Array. Trying to use this function and logging out the params led me to this conclusion.

### Steps to Resolve this Issue

1. Update the documentation to the correct value.

**Comment by Rish-P** [comment]
I can go ahead and correct the documentation. Can someone just give me an idea what exactly the new version needs to look like and what needs changing...

**Comment by Rish-P** [comment]
![Screenshot 2023-08-14 at 5 06 58 PM](https://github.com/gatsbyjs/gatsby/assets/63592727/6f358675-83f2-4584-a786-e20d2be159f7)

**Comment by pieh** [comment]
Testing locally I do get second param as single string not array of strings - can you share version of plugin you are using and options you pass into it?

**Comment by serhalp** [comment]
Closing as stale and not reproducible
