### ISSUE TITLE
Add option to set default Moment.js locale

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#3837]
It would be convenient if there was a global option (e.g. in `gatsby-config.json`) to set the default locale used for Moment.js in GraphQL queries. Websites made for a non-English audience are harder to maintain because something like `locale: "hu"` shall always be added to date queries.

**Comment by pieh** [comment]
Here's where gatsby sets default locale - https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/infer-graphql-type.js#L150 if anyone want to try adding this feature

**Comment by sedubois** [comment]
Ideally this should be integrated in an i18n plugin, for websites which need to support multiple locales.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
