### ISSUE TITLE
How do I get React Router to handle links to markdown files?

### ISSUE THREAD

**Issue by hiddentao** [gatsbyjs/gatsby#384]
I have a folder structure like:

```
pages/
  docs/
    index.md
    Middleware/
      index.md
```

In `pages/docs/index.md` I have a link to the middleware docs like: `[Middleware](Middleware/).

When I run `gatsby develop` the pages get rendered correctly. But when I click the middleware link above the browser loads the Middleware HTML page afresh instead of doing an in-page navigation (i.e. using React Router). 

What am I doing wrong?

**Comment by hiddentao** [comment]
I've tried to figure this out from looking at Gatsby code. From what I can see the files are stored in the bundle.js using against their original paths rather than the URL I use in the link (e.g. `./docs/Middleware/index.md`). Perhaps this is a reason why the React Router doesn't handle the URL?

**Comment by KyleAMathews** [comment]
You want to do something like this line in gatsby-starter-blog https://github.com/gatsbyjs/gatsby-starter-blog/blob/master/pages/index.js#L29

Use the `<Link>` component from react-router and `prefixLink` from 'gatsby-helpers' if you are deploying to something like Github pages.
