### ISSUE TITLE
Add a simple option to auto-transform markdown files in “src/pages”

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#3849]
Setting up the transformation of markdown files in “src/pages” and creating actual pages for them [can be cumbersome](https://www.gatsbyjs.org/tutorial/part-four/), especially for beginners.

I think there should be an official plugin _(gatsby-plugin-remark?)_ to achieve the aforementioned goal without bloating codebases with boilerplate.

**Comment by calcsam** [comment]
Assume you mean `src/blog` or similar? `src/pages` is a directory of components that becomes pages -- you shouldn't put any .md files in there.

**Comment by kripod** [comment]
Yes, exactly.

**Comment by tsriram** [comment]
I think [gatsby-starter-blog](https://github.com/gatsbyjs/gatsby-starter-blog) does it already and people can just keep adding markdown files without having to configure any source / transform plugins manually (I mean it's there pre-configured in the starter). Not sure if I understood your problem correctly!

**Comment by kripod** [comment]
The problem is that I don’t want all those code to be in each of my projects, but inside a separate, importable package.

**Comment by calcsam** [comment]
@kripod what were you thinking for an API here? first thought is something like:

```
[
     resolve: 'gatsby-plugin-remark',
     options: {
         path: './path/to/files', [default: './src/blog/']
         template: './path/to/template', [default: './src/components/blog.js'],
         name: 'blog'
    }
]
```

**Comment by kripod** [comment]
@calcsam Yeah, something similar to that would be great.

**Comment by mikefowler** [comment]
@kripod @calcsam https://github.com/mikefowler/gatsby-plugin-collections is in a decent alpha state. If you give it a shot, feel free to open issues letting me know where there are holes in the docs, or things that just aren't working entirely. 

The primary thing I need to update before it's in a state for initial release is the version of Node it targets (currently 8, and I'm using some language features unavailable in Node 4, which is what Gatsby targets currently).

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by dhoulb** [comment]
@kripod @calcsam FYI I recently made a plugin to do something like you want: https://www.gatsbyjs.org/packages/gatsby-plugin-templated-files/

I wanted to dial back the configuration complexity for simple sites, so the config is minimal and doesn't need `gatsby-source-filesystem` or any page creation hooks in `gatsby-node.js`:

```js
// gatsby-config.js
{
  resolve: "gatsby-plugin-templated-files",
  options: {
    path: "./pages",
    template: "Page.jsx", // (in src/templates)
    url: "/pages/:slug", // optional
    includes: ["*.md"], // optional
    ignore: ["LICENSE.md"], // optional
    indexes: ["index.md"], // optional
  },
  "gatsby-plugin-remark",
},
```

I originally had it replace `gatsby-plugin-remark` too (to make config even simpler), but realised it's super easy to get the MarkdownRemark content for nodes in GraphQL queries via `childMarkdownRemark`. I've put examples of this in [the readme](https://www.gatsbyjs.org/packages/gatsby-plugin-templated-files/).

**Comment by calcsam** [comment]
Wow, that's great. Thanks @dhoulb!
