### ISSUE TITLE
Try creating responsive variants of images specified by a URL with gatsby-remark-images

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#3850]
While using Netlify CMS, I realized that images are always added to markdown files by their absolute URL instead of using a relative path.

`gatsby-remark-images` can automatically create responsive variants for images specified by a path, but it cannot deal with images specified by an absolute URL. I think it would be reasonable to verify that an image’s URL refers to an absolute path **inside the domain of the Gatsby-based project** and then transform it into a set of responsive images.

**Comment by KyleAMathews** [comment]
Perhaps? Absolute paths are a big problem for making sites work across machines. I'd much rather Netlify CMS default to relative paths. /cc @erquhart

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
