### ISSUE TITLE
Gatsby Source Contentful with Variable in Query

### ISSUE THREAD

**Issue by aaronaustin** [gatsbyjs/gatsby#3851]
I'm creating some landing pages on my Gatsby site and want to list nodes from specific content types. For instance, I have:

```
allContentfulSongs
allContentfulBlogs
```
In my landing page template, how can I dynamically query songs or blogs? I tried:

```
all${landingPage} {
    edges {
      node {
       id
     }
   }
}
```
but I'm getting a syntax error. Is there a way to add a variable in this part of the query in Gatsby?  I've tried working with an ` @include(if: $landingPage) ` but I can't find a way to compare the value I'm passing in to create a boolean.

**Comment by KyleAMathews** [comment]
Try going through part 4 of the tutorial which explains how to do this — particularly this section https://www.gatsbyjs.org/tutorial/part-four/#programmatically-creating-pages-from-data

Another tutorial is https://www.gatsbyjs.org/blog/2017-07-19-creating-a-blog-with-gatsby/#creating-the-pages
