### ISSUE TITLE
[request] using-less example

### ISSUE THREAD

**Issue by terrelltechsup** [gatsbyjs/gatsby#3854]
## Description

Request:  A more in-depth tutorial on using LESS with gatsby-plugin-less.  

I am attempting to use the gatsby-plugin-less plugin and I am having trouble determining how it works.  Where do the LESS files have to live to be compiled by this plugin?  What is the syntax to import them? etc.  A working example to work off of would be much appreciated.

Thank you,

Josh Terrell

**Comment by calcsam** [comment]
Here are a few: https://github.com/search?q=gatsby-plugin-less&type=Code&utf8=%E2%9C%93

We're also going to add a showcase in the next couple of months, hopefully we'll be able to include search by plugin used.

**Comment by calcsam** [comment]
A using-less example, or using-sass, or using-postcss, would all be awesome

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
