### ISSUE TITLE
Anchor Links, part 2

### ISSUE THREAD

**Issue by ivanoats** [gatsbyjs/gatsby#386]
Is there a plan to support or document how to make anchor links work?

I know https://github.com/gatsbyjs/gatsby/issues/302 is closed for now, but it's not clear how to work-around. 

I have a fork of gatsby-starter-default that reproduces the error here: https://github.com/ivanoats/gatsby-starter-default/blob/master/pages/html.html

**Comment by ivanoats** [comment]
D'oh - https://github.com/adjohnson916/anchorate#gatsby - I will try that.

**Comment by ivanoats** [comment]
Works great! Should we add it to starters, README, or both?

**Comment by KyleAMathews** [comment]
Don't think they need to be in starters (other than perhaps the documentation one) but yeah, this would be great to add to the README.

**Comment by ivanoats** [comment]
1) Cool, I will make a PR for the README. 

2) Starters: OK, hear me out on this. Anchors are such a basic part of HTML that we need to explain if something is broken with HTML out of the box. Maybe I've been using HTML for too long and that's why I feel that way, but that's what I think.

**Comment by KyleAMathews** [comment]
hmmm... that is a good point actually. I added react-router-scroll for the
same reason. We do have to emulate features that the browser normally
provides by default. Changed positions — perhaps even make this turned on
by default in Gatsby?

**Comment by rojobuffalo** [comment]
Maybe taking this one step further, it might be cool to be able to opt-in to have anchors auto-generated for all `h1` and `h2` tags based on the text for that heading.

**Comment by f0rr0** [comment]
@rojobuffalo you can use something likw `markdown-it-anchor` for that

**Comment by f0rr0** [comment]
@ivanoats are you sure it is working 100% of the time? i tested it in my project and the result is almost the same as without using anchorate.

**Comment by f0rr0** [comment]
The correct way to fix this would involve stopping a re render in the first place. anchorate gets called only after the route is changed

**Comment by ivanoats** [comment]
Pretty sure. I haven't had any issues from manual testers. I would be interested in an automated test.

**Comment by f0rr0** [comment]
Confirmed this is a `react-router-scroll` issue.
https://github.com/gatsbyjs/gatsby/issues/462#issuecomment-249452553
https://github.com/taion/react-router-scroll/issues/10

**Comment by f0rr0** [comment]
As far as `anchorate` is concerned, you ca achieve what it does with this basically in `gatsby-browser.js`:
```js
exports.onRouteUpdate = (location) => {
  if (location.hash) {
    setTimeout(() => {
      document.querySelector(`${location.hash}`).scrollIntoView();
    }, 0);
  }
};

**Comment by adrianescat** [comment]
native HTML anchor links are broken, even using `import { Link } from "gatsby";` ...
Only this worked for me *:

```javascript
import { navigate } from "@reach/router";

<div className="custom-link" onClick={() => {navigate("#section_id")}}>Section</div>
```

*But my website works with and without `www`. This approach only works for my website without `www`.

**Comment by magnusarinell** [comment]
navigate doesn't work for me either. I get redirected to my index page.
