### ISSUE TITLE
[gatsby-plugin-sharp] filter images by aspect ratio

### ISSUE THREAD

**Issue by davidbarratt** [gatsbyjs/gatsby#3862]
I would really like to filter images in `allImageSharp` by the aspect ratio, but I can't find a way to do this. 

The reason why is that I only want to include images that are horizontal (not vertical).

Alternatively, is there a way to filter that the width is greater than the height?

**Comment by nsimonson** [comment]
The gatsby graphql filter for Floats and Ints only allows for equal `eq` or not equal `ne`. Although I imagine this could be (should be?) extended to the other relational operators.

The best way for now might be to filter the result of the query on the client side.

**Comment by KyleAMathews** [comment]
Yeah, we need to add "greater than" and "less than" filtering support. The library we use under the hood to run queries supports it, someone just needs to add some tests and enable the support! https://github.com/crcn/sift.js/

**Comment by KyleAMathews** [comment]
@pieh mentioned he might be working on this soon https://github.com/gatsbyjs/gatsby/pull/3688#issuecomment-363555622

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
