### ISSUE TITLE
gatsby-transformer-javascript-static-exports seems to not work anymore

### ISSUE THREAD

**Issue by peXed** [gatsbyjs/gatsby#3868]
## Description

The plugin "gatsby-transformer-javascript-static-exports" seems to not work anymore.
I did try to update the entiry project and even tried the plugin on a completly new gatsby website, but I always get: **Cannot query field "allJsFrontmatter" on type "RootQueryType"**

### Environment

Gatsby version: 1.9.158
Node.js version: 5.6.0
Operating System: Windows

### Actual result

Get the error 
`Cannot query field \"allJsFrontmatter\" on type \"RootQueryType\".`

### Expected behavior

Query should run perfectly.

### Steps to reproduce

1\. create new gatsby (default) starter website

2\. add plugin

3\. add data from example (docs) to index page

4\. run example query (from docs) in graphql

**Comment by jbolda** [comment]
Just to confirm, I believe you are referring to https://github.com/gatsbyjs/gatsby-starter-default ?

The plugin "gatsby-transformer-javascript-static-exports" is a "transformer" type, that is, it requires a "source" for the data (most likely gatsby-source-filesystem). Would you be able to confirm that you have added a source and added the necessary items to `gatsby-config.js`?

**Comment by KyleAMathews** [comment]
You can also try out the example site for the plugin which demonstrates a full setup https://github.com/gatsbyjs/gatsby/tree/master/examples/using-javascript-transforms

**Comment by peXed** [comment]
Hello and thanks for the fast reply.

Sorry, I didn't think about that. I thought the pages folder it self is a data source.

So it is not possible to get the default pages (from the pages folder) into the system?

**Comment by jbolda** [comment]
It is, you just need to source the data. Gatsby doesn't automatically do this for you. See the example posted above. Change the src/mainPages to src/pages, and update the gatsby-config.js to match. It should work the same.

**Comment by peXed** [comment]
Thank you very much! :)
