### ISSUE TITLE
gatsby build output should be gzipped

### ISSUE THREAD

**Issue by kaihendry** [gatsbyjs/gatsby#387]
I noticed the files in the `public/` output folder aren't gzipped. They should be by default, shouldn't they?

Or is there a deployment trick I'm missing?

**Comment by KyleAMathews** [comment]
Most web servers gzip files on the file for you. This certainly could be
done if you'd like post-build.

**Comment by kaihendry** [comment]
I think it's silly to put this (dynamic) task on the server when should be statically gzipped to begin with.

I'm not familiar with the JS toolchain. How doesn't one do a gzip post-build?

**Comment by benstepp** [comment]
Gatsby has a [hook for postBuild](https://github.com/gatsbyjs/gatsby#perform-additional-post-build-step) that allows you to do pretty much anything with the files after their built. Here's a quick example that will gzip all html, css, and js files to their .gz counterparts postBuild.

```js
// in gatsby-node.js
import fs from 'fs'  // native
import zlib from 'zlib'  // native
import path from 'path'  // native
import glob from 'glob' // https://www.npmjs.com/package/glob

export function postBuild(pages, callback) {
  const publicPath = path.join(__dirname, 'public')
  const gzippable = glob.sync(`${publicPath}/**/?(*.html|*.js|*.css)`)
  gzippable.forEach(file => {
    const content = fs.readFileSync(file) 
    const zipped = zlib.gzipSync(content)
    fs.writeFileSync(`${file}.gz`, zipped)
  })
  callback()
}
```

That said I would still leave gzipping to the webserver / CDN.

**Comment by kaihendry** [comment]
Why would you leave gzipping to server? Increase latency? For it to use something inferior to `gzip --best`? Seriously would love to know! :laughing: 

Btw, you shouldn't add the .gz content. It should just be compressed and typically `--content-encoding gzip` needs to added to dumb servers if they can't detect it's gzipped.

**Comment by benstepp** [comment]
We only have nginx running in front of a bunch of Rails APIs in Docker containers at this point and I'm just guessing that nginx is faster at gzipping than any ruby runtime. 

For our static assets, we just check the compress objects automagically checkbox on CloudFront and let it do its thing. I figure Amazon has got the fastest way possible figured out by now.

**Comment by kaihendry** [comment]
Surely the "fastest way" is to do it in advance as a build step? It's pointless to put this task on the server unless you're lazy.

**Comment by KyleAMathews** [comment]
I'm perfectly happy to be lazy left and right as long as someone else picks up the slack :-)

I've never seen another system like Gatsby that defaults to gzipping output. It seems better to just let users choose. Once we have a plugin system, you could create a plugin that gzips everything by default and share it with the community. In the meantime, @benstepp's code example is a great solution. Closing this.

**Comment by abumalick** [comment]
Here is the code of @benstepp ported new gatsby hooks, if someone needs it
```js
// in gatsby-node.js
const fs = require('fs');
const zlib = require('zlib');
const iltorb = require('iltorb');
const glob = require('glob');

exports.onPostBuild = () =>
  new Promise((resolve, reject) => {
    try {
      const publicPath = path.join(__dirname, 'public');
      const gzippable = glob.sync(`${publicPath}/**/?(*.html|*.js|*.css|*.svg)`);
      gzippable.forEach((file) => {
        const content = fs.readFileSync(file);
        const zipped = zlib.gzipSync(content);
        fs.writeFileSync(`${file}.gz`, zipped);
        
        const brotlied = iltorb.compressSync(content);
        fs.writeFileSync(`${file}.br`, brotlied);
      });
    } catch (e) {
      reject(new Error('onPostBuild: Could not compress the files'));
    }

    resolve();
  });
```

**Comment by denisx** [comment]
> ```
> const fs = require('fs');
> ```
to
 ```
 const fs = require('fs');
 const path = require('path');
 ```

**Comment by joefiorini** [comment]
@benstepp @abumalick Just curious, why rely on this custom code when you could add plugins to the webpack config to handle it? Is there something about the way gatsby builds that makes webpack unreliable for compressing files?

**Comment by abumalick** [comment]
there is more than one webpack configuration in gatsby, it is difficult to imagine that a simple webpack plugin will do that job correctly. I am interested by any feedback if you can make it work.

https://www.gatsbyjs.org/docs/behind-the-scenes/

**Comment by himynameistimli** [comment]
Just as a note we were having problems with (https://github.com/gatsbyjs/gatsby/issues/387#issuecomment-436672441) and the latest versions of gatsby where, for some reason, 404.html was added a folder, so we modified `glob.sync()` with `{ nodir: true }`.

Just in case anyone else has this issue:

```javascript
    const options = { nodir: true };
    const gzippable = glob.sync(`${publicPath}/**/?(*.html|*.js|*.css|*.svg)`, options);
```

**Comment by gusliedke** [comment]
> I'm perfectly happy to be lazy left and right as long as someone else picks up the slack :-)
> 
> I've never seen another system like Gatsby that defaults to gzipping output. It seems better to just let users choose. Once we have a plugin system, you could create a plugin that gzips everything by default and share it with the community. In the meantime, @benstepp's code example is a great solution. Closing this.

Hello @KyleAMathews, does it still the preferable way to compress Gatsby built files? Or there is a newer method? It takes around 3 mins to compress my app files (approx: 3k pages).

**Comment by gusliedke** [comment]
ok, just realised we don't need it anymore as CloudFront is compressing it for us. 👍

**Comment by wardpeet** [comment]
It's better to rely on your CDN to do the compression. Lots of CDNs support brotli which makes things even smaller than gzip. So it's probably not worth to gzip it before uploading.

**Comment by ebuildy** [comment]
We use gitlab pages to server our documentation, and the page must be already compressed:

https://docs.gitlab.com/ee/user/project/pages/introduction.html#serving-compressed-assets

(but I believe github gzip compress pages content on-the-fly)
