### ISSUE TITLE
[v2] Use uglify-es with browserlist

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#3871]
CRA has some ongoing work here that we can copy

**Comment by jquense** [comment]
Beyond the webpack plugin? We should already be on uglify-es!

**Comment by KyleAMathews** [comment]
Oh ok, perfect! :-)

What webpack plugin?

I guess there wasn't much to be done around integrating with browserlist — https://github.com/facebook/create-react-app/issues/3748 — just changing the ecma version https://github.com/facebook/create-react-app/commit/6f05355ba07118efd277b3d8fcd00cfcc5c7666b
