### ISSUE TITLE
Unable to find remote helper for 'git+https'

### ISSUE THREAD

**Issue by joshfarrant** [gatsbyjs/gatsby#3874]
## Description

Attempting to init a starter site using `gatsby new gatsby-example-site` causes the error `fatal: Unable to find remote helper for 'git+https'`. Is this related to 8261ac36?

### Environment

Gatsby version: 1.1.35
Node.js version: 8.9.0
Operating System: MacOS 10.13.1

### Actual result

The full error printed to the console is as follows:

```
info Creating new site from git: git+https://github.com/gatsbyjs/gatsby-starter-default.git
Cloning into 'gatsby-example-site'...
fatal: Unable to find remote helper for 'git+https'
error Command failed: git clone git+https://github.com/gatsbyjs/gatsby-starter-default.git gatsby-example-site --single-branch


  Error: Command failed: git clone git+https://github.com/gatsbyjs/gatsby-starter-defaul  t.git gatsby-example-site --single-branch

  - index.js:236 Promise.all.then.arr
    [lib]/[gatsby-cli]/[execa]/index.js:236:11

  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:693 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:693:18

  - promise.js:638 Promise._fulfill
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:693 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:693:18

  - async.js:133 Async._drainQueue
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:133:16

  - async.js:143 Async._drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:143:10

  - async.js:17 Immediate.Async.drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:17:14

```

### Expected behavior

A starter site should be initialised.

### Steps to reproduce

1\. Install Gatsby globally with npm.

2\. Run `gatsby new gatsby-example-site`

**Comment by cortopy** [comment]
Also having this issue

**Comment by sliw** [comment]
@joshfarrant @cortopy 

I had the exact same problem and I solved that by typing the following command in the terminal:

`git config --global url."https://".insteadOf git+https://`

**Comment by cortopy** [comment]
It does @sliw ! Thanks a lot!!

should this be necessary though?

**Comment by joshfarrant** [comment]
Thanks @sliw, works like a charm!

**Comment by nareshbhatia** [comment]
@KyleAMathews, is anyone looking into this issue. It appears that the latest build has broken `gatsby new`. Please help!

**Comment by calcsam** [comment]
Reverted the commit in question, should be fixed now.

**Comment by KyleAMathews** [comment]
Sorry about that everyone!

**Comment by geneno99** [comment]
> @joshfarrant @cortopy
> 
> I had the exact same problem and I solved that by typing the following command in the terminal:
> 
> `git config --global url."https://".insteadOf git+https://`
> 
> I think there were few issues similar to the current one (but they were git:// instead of git+https://).
> 
> Hope this helps.

how to execute this one in vagrant?
