### ISSUE TITLE
While shadowing a css file from a gatsby theme the changes are reflected in netlify preview but not on deployment 

### ISSUE THREAD

**Issue by bhuwan1998** [gatsbyjs/gatsby#38740]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

While shadowing a css file from gatsby theme portfolio minimal, there was an issue that the css changes were reflected in ```gatsby develop``` and netlify preview as well. However, the changes were not reflected on deployment even though the changes can be seen on the github repository. 

### Reproduction Link

NA

### Steps to Reproduce

1. Shadow a css file that you want to change from a gatsby theme 
2. Deploy on netlify 
3. Check if the changes are being implemented on deployed website. 
...

### Expected Result

Webpage should include changes 

### Actual Result

Webpage have no extra changes that were made on the shadowed css file 

### Environment

```shell
System:
    OS: macOS 14.1.1
    CPU: (12) arm64 Apple M3 Pro
    Shell: 5.2.21 - /opt/homebrew/bin/bash
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.9.0/bin/npm
  Languages:
    Python: 3.11.5 - /opt/homebrew/Caskroom/miniconda/base/bin/python
  Browsers:
    Chrome: 119.0.6045.199
    Edge: 119.0.2151.97
    Safari: 17.1
  npmPackages:
    gatsby: ^5.8.0 => 5.12.9
    gatsby-image: ^3.11.0 => 3.11.0
    gatsby-plugin-google-analytics: ^5.12.0 => 5.12.0
    gatsby-plugin-google-gtag: ^5.12.3 => 5.12.3
    gatsby-plugin-image: ^3.11.0 => 3.12.3
    gatsby-plugin-mdx: ^5.12.3 => 5.12.3
    gatsby-plugin-sharp: ^5.12.0 => 5.12.3
    gatsby-source-filesystem: ^5.12.0 => 5.12.1
    gatsby-theme-portfolio-minimal: 4.6.3 => 4.6.3
    gatsby-transformer-inline-svg: ^1.2.0 => 1.2.0
    gatsby-transformer-sharp: ^5.12.0 => 5.12.3
  npmGlobalPackages:
    gatsby-cli: 5.12.4
```

**Comment by bhuwan1998** [comment]
The changes were implemented on deployment but my own browser cache loaded the older website.

**Comment by bhuwan1998** [comment]
@bhavik001 I am not a contributor of this project so I cannot assign you this issue. I do not know how to reproduce this issue if someone is not deploying on netlify. The changes are seen in the production preview on netlify but when published/deployed no changes are to be seen on the successful deployment.

**Comment by ChrisLaRocque** [comment]
@bhuwan1998 if you clear the netlify cache + deploy from the netlify UI does the issue get fixed?

**Comment by bhuwan1998** [comment]
@ChrisLaRocque thanks for the suggestion. I tried it and it works
