### ISSUE TITLE
Showcase page has some sites which are not using Gatsby js anymore, and still they are in Featured sites section

### ISSUE THREAD

**Issue by officialrj18** [gatsbyjs/gatsby#38756]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

The [show case page](https://www.gatsbyjs.com/showcase/) has some sites which are not now using Gatsby framework anymore which is actually giving bad impression:

Below are some sites i have listed from the page which are also part of the top Horizontal Featured Sites which are not using gatsby anymore :
[American Foundation for Suicide Prevention](https://www.gatsbyjs.com/showcase/afsp.org)
[Little Caesars](https://www.gatsbyjs.com/showcase/littlecaesars.com)
[Figma](https://www.gatsbyjs.com/showcase/www.figma.com)
[ReactJS](https://www.gatsbyjs.com/showcase/reactjs.org)
[Strivectin](https://www.gatsbyjs.com/showcase/www.strivectin.com)

Please remove them as well as all those sites like this from the showcase page asap and update with the sites which are currently using Gatsby which will motivate the developers to use Gatsby more.

### Steps to Resolve this Issue

1. By Removing all those sites in showcase which are not using Gatsby from the page
2. By Updating the sites with more new sites which are using Gatsby
3. If you have the new list or just want to remove the outdated sites which are not using Gatsby, If its possible I would love to update this page for you, because i have been using Gatsby since long and i still have trust in Gatsby that it has great potential.
Thank you

**Comment by pieh** [comment]
Thanks for creating issue for this - I did mass checks and remove bunch of outdated entries (including ones you explicitly reported)

**Comment by officialrj18** [comment]
Hi pieh,
Thanks for removing the outdated entries, but i have checked there are still some present like [Calendly](https://www.gatsbyjs.com/showcase/calendly.com) which are not using gatsby now.
Could you please check each of them again and update all the  entries.

**Comment by pieh** [comment]
Thanks, rerun validator and found https://calendly.com/ + https://www.oomphinc.com that are no longer gatsby and will be removing them as well. I did run same validator before, tho I don't have logs, so not clear to me wether this changed since my previous run or there were failures preventing to figure out for sure it's not gatsby site in the validator

**Comment by officialrj18** [comment]
There must be some failures in the validator because I had checked it earlier I think, it (calendly) was using next only.
Thanks for your prompt response and actions for it.
