### ISSUE TITLE
Show case crashed when search

### ISSUE THREAD

**Issue by spartan-huyle** [gatsbyjs/gatsby#38765]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

https://github.com/gatsbyjs/gatsby/assets/144250684/a499be66-adc0-4ddc-aa33-d0f85f71faaa

### Reproduction Link

https://www.gatsbyjs.com/showcase/

### Steps to Reproduce

1. Go to https://www.gatsbyjs.com/showcase/
2. Typing into Search sites

### Expected Result

Error doesn't occur

### Actual Result

Error occurs

### Environment

```shell
N/A
```

**Comment by pieh** [comment]
This was fixed now. Thanks for report!
