### ISSUE TITLE
Gatsby 5 is dead? 

### ISSUE THREAD

**Issue by Leksat** [gatsbyjs/gatsby#38859]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

According to
https://github.com/gatsbyjs/gatsby/blob/222158e1ea88d0aedfbec10af1a24aae32acedb2/docs/docs/reference/release-notes/gatsby-version-support.md?plain=1#L15-L17
Gatsby 5 already reached its End Of Life.

Is this a typo maybe?

### Steps to Resolve this Issue

1. Go to docs: https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/
2. See Gatsby 5 EOL date

**Comment by ricky-harrys** [comment]
Related to #38696

**Comment by serhalp** [comment]
Resolved by https://github.com/gatsbyjs/gatsby/pull/39023
