### ISSUE TITLE
Docs reference a PostLink component, but I can't find its example

### ISSUE THREAD

**Issue by tremby** [gatsbyjs/gatsby#3886]
At https://www.gatsbyjs.org/docs/adding-a-list-of-markdown-blog-posts/ there's an example of looping through documents and giving a link to each one's page. It uses a `PostLink` component, but I can't see the implementation of that anywhere.

I'm wondering if it has some special Gatsby way to link to the node's URL, or if that component is just simply going to be using `node.path` in a regular link tag. Either way, I think the doc page could be clearer about it.

**Comment by fk** [comment]
> I'm wondering if it has some special Gatsby way to link to the node's URL, or if that component is just simply going to be using node.path in a regular link tag.

You want to use [gatsby-link](https://www.gatsbyjs.org/packages/gatsby-link/). It's introduced in the  [first part of the tutorial](https://www.gatsbyjs.org/tutorial/part-one/#linking-between-pages). Will whip together a `PostLink` and post here in a few.

**Comment by fk** [comment]
Here's a quick shot at `PostLink`:

```js
import React from "react"
import Link from "gatsby-link"

const PostLink = ({ post }) => (
  <div>
    <Link to={post.frontmatter.path}>
      {post.frontmatter.title} ({post.frontmatter.date})
    </Link>
  </div>
)

export default PostLink
```

Will add a PR that expands https://www.gatsbyjs.org/docs/adding-a-list-of-markdown-blog-posts/ with that now!

**Comment by tremby** [comment]
That's great; thanks.

**Comment by fk** [comment]
@tremby You're welcome—thank you for bringing this up!
Please close if this issue is resolved.
