### ISSUE TITLE
[Question] it is posible to run gatsbyJS on firebase cloud functions? 

### ISSUE THREAD

**Issue by k1r0s** [gatsbyjs/gatsby#3888]
```javascript
const functions = require('firebase-functions');

exports.app = functions.https.onRequest(gatsbyMiddleware);

```

Im trying to deploy a gatsby site using firebase functions. But I need to provide a middleware, or. Deploy gatsby somehow and fallback any request to gatsby instance.. any one has an idea about? Thanks :)

**Comment by szimek** [comment]
@k1r0s What are you trying to achieve? Gatsby generates HTML files, so once you somehow build your project, you can host it using e.g. https://firebase.google.com/docs/hosting. Or use e.g. https://www.netlify.com to build, deploy and host it for you.

**Comment by k1r0s** [comment]
Im trying to read the docs before asking anything

**Comment by s-kennedy** [comment]
@k1r0s did you figure this out? My idea is to use a cloud function to build and deploy my gatsby site whenever an authorized user adds new content.

**Comment by k1r0s** [comment]
I guess you can use could function as a proxy, and dispatch user request to another server which is effectively serving static assets

**Comment by leomercier** [comment]
I've written a step by step guide on how to host a Gatsby site on Firebase, as well as deploying it automatically using Google Cloud Build.

[Automatically Deploying a Gatsby Site to Firebase with Google Cloud Build (CI/CD)](https://www.crowdform.co.uk/blog/deploying-a-gatsby-site-to-firebase-with-google-cloud-build)
