### ISSUE TITLE
Gatsby & Fish-Shell

### ISSUE THREAD

**Issue by RXminuS** [gatsbyjs/gatsby#3890]
## Description

`gatsby new` does not work in fish-shell

### Environment

Gatsby version:1.1.37
Node.js version:v9.5.0
Operating System:MacOS

### Actual result
It get's stuck after `[4/4] Building fresh packages` with a blinking `nsfw` and `loading` messages

### Expected behavior
If I switch to `bash` the command works just fine and install all dependencies.

### Steps to reproduce

1. Download [fish-shell](https://fishshell.com/)
2. `$> gatsby new test`

**Comment by KyleAMathews** [comment]
Hey — I use fish-shell so `gatsby new` definitely works with it. Could have been a temporary problem? NPM is unfortunately somewhat prone to install failures.
