### ISSUE TITLE
Blogged about plans for Gatsby

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#390]
This is a quick announcement issue. I blogged just now about my plans moving forward with Gatsby. The tl;dr is I'm now working full-time on Gatsby and I'm looking for sponsorship/consulting opportunities. Read the post for more details plus the highlights on what I want to work on in the next few months:

https://bricolage.io/gatsby-open-source-work/

Please contact me @ mathews.kyle@gmail.com if you're interested in sponsoring work or need help on a current/future Gatsby project.

Also a retweet would be appreciated :-) https://twitter.com/kylemathews/status/764162167536889856

**Comment by kylegach** [comment]
Super excited about the Service Worker and ”Pull instead of Push” work!

Best of luck, Kyle!

**Comment by cutemachine** [comment]
Tweet sent :)

Yes, best of luck from me too.

+1 for code splitting

**Comment by hiddentao** [comment]
Totally with you on this. I find myself picking up Gatsby every time I want to do a static site nowadays.
