### ISSUE TITLE
gatsby-plugin-sitemap is generating default sitemap even when given custom options

### ISSUE THREAD

**Issue by maghaffar** [gatsbyjs/gatsby#39006]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I want to generate custom sitemap for my site and I want to change the priority value based on the when the page is modified. For this I am using custom options of gatsby-plugin-sitemap as shown below:
![image](https://github.com/gatsbyjs/gatsby/assets/98881071/003f4cf5-fcb9-4516-9792-28fa46d47921)
But the plugin is always generating the default sitemap like this given below:
![image](https://github.com/gatsbyjs/gatsby/assets/98881071/85630347-53c6-4c55-a307-8dbf893d87b8)

I don't know what is happening? Can someone please explain this? Can we change the changefreq and priority values?

### Reproduction Link

https://herb.co/sitemap.xml

### Steps to Reproduce

I am not able to reproduce I can give the link of my site
https://herb.co/sitemap.xml

### Expected Result

N/A

### Actual Result

N/A

### Environment

```shell
gatsby: 4.12.0
gatsby-plugin-sitemap:4.0.0
```

**Comment by maghaffar** [comment]
@janson @mojodna @mudge @farcaller 
Kindly reply to this and give solution to this problem.

**Comment by Viktor19931** [comment]
@maghaffar use advanced sitemap plugin 
Its more flexible

**Comment by maghaffar** [comment]
I was'nt able to create sitemap by using the plugin. I created using my own custom code and uploaded. 
Concerned people of the plugin should have to do something for this problem
