### ISSUE TITLE
[Blog/Docs] Zoom bug at 110% – text gets smaller

### ISSUE THREAD

**Issue by html5cat** [gatsbyjs/gatsby#3904]
## Description

Zooming in on docs and blog pages reduces font size at first step instead of increasing it.

### Environment

Operating System: MacOS High Sierra, Latest Chrome, 13" macbook pro

### Steps to reproduce

1\. Open any docs or blog page, i.e. https://www.gatsbyjs.org/blog/2017-11-08-migrate-from-jekyll-to-gatsby/

2\. Zoom in one step from 100% to 110%

3\. See the fonts decrease in size instead of increasing

**Comment by KyleAMathews** [comment]
Looks like it's just running into our media queries which are adjusting the font size up and down https://github.com/gatsbyjs/gatsby/blob/f02cc2bf0893bcc17c19fe6c5dc799babb978057/www/src/utils/typography.js#L260

This is kinda weird I'll agree — feel free to tweak our media queries to make this edge case a little less "edgy" :-)

**Comment by fk** [comment]
![giphy](https://user-images.githubusercontent.com/21834/35966771-179471e6-0cbf-11e8-8525-34b653dbaf84.gif)
