### ISSUE TITLE
Blank white pages loading on gatsbyjs.com on Safari browsers (MacOS and iOS)

### ISSUE THREAD

**Issue by mikeygee** [gatsbyjs/gatsby#39074]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Not sure if this is the right place to report this, but routing seems to be broken for Safari browsers (desktop and mobile) on the gatsbyjs.com production site. I was trying to browse docs, and all relative links just load a blank white page. Page reload is required to get it back. Other browsers work fine.

There is an error in the console `ReferenceError: Can't find variable: cancelIdleCallback`. It looks like this method is not supported in Safari only (https://developer.mozilla.org/en-US/docs/Web/API/Window/cancelIdleCallback).

### Reproduction Link

https://www.gatsbyjs.com

### Steps to Reproduce

1. Go to gatsbyjs.com in a Safari browser (MacOS or iOS)
2. Click any relative link

### Expected Result

Links should load pages normally

### Actual Result

Blank white page loads. JS error in console: `ReferenceError: Can't find variable: cancelIdleCallback`.

### Environment

```shell
Safari browsers on MacOS and iOS
```

**Comment by michael-bitterdata** [comment]
I believe I have run into this issue, and it seemed related to this
https://github.com/angular/angular/issues/53721

which I resolved locally by setting a development feature flag, seen here
<img width="831" alt="Screenshot 2024-09-02 at 1 49 53 PM" src="https://github.com/user-attachments/assets/a42eb3d2-c641-44ba-95ee-d69ff9e36cc3">

**Comment by mikeygee** [comment]
Thanks for that workaround, confirmed it resolves the issue. I’ll close this assuming that feature is eventually activated by default.
