### ISSUE TITLE
SyntaxError: Unexpected token '??=' when running with GitHub actions on Ubuntu

### ISSUE THREAD

**Issue by khider** [gatsbyjs/gatsby#39128]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I am trying to update a Gatsby site that requires older version of nodes through GitHub action. Everything was working fine until this month. I'm still able to successfully build on my local Mac machine but I get a token error when building on Ubuntu workers (GitHub action).

Full error:

```
success open and validate gatsby-configs - 0.063s
error Error in "/home/runner/work/LeapFROGS/LeapFROGS/node_modules/gatsby-plugin-offline/gatsby-node.js": Unexpected token '??='


  Error:/home/runner/work/LeapFROGS/LeapFROGS/node_modules/undici/lib/core/util  .js:623
    const listeners = (obj[kListeners] ??= [])
                                       ^^^
  SyntaxError: Unexpected token '??='
  
  - v8-compile-cache.js:240 NativeCompileCache._moduleCompile
    [LeapFROGS]/[v8-compile-cache]/v8-compile-cache.js:240:18
  
  - v8-compile-cache.js:184 Module._compile
    [LeapFROGS]/[v8-compile-cache]/v8-compile-cache.js:184:36
  
  - loader.js:1143 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1143:10
  
  - loader.js:979 Module.load
    internal/modules/cjs/loader.js:979:32
  
  - loader.js:819 Function.Module._load
    internal/modules/cjs/loader.js:819:12
  
  - loader.js:1003 Module.require
    internal/modules/cjs/loader.js:1003:19
  
  - v8-compile-cache.js:159 require
    [LeapFROGS]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - client.js:8 Object.<anonymous>
    [LeapFROGS]/[undici]/lib/dispatcher/client.js:8:14
  
  - v8-compile-cache.js:192 Module._compile
    [LeapFROGS]/[v8-compile-cache]/v8-compile-cache.js:192:30
  
  - loader.js:1143 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1143:10
  
  - loader.js:979 Module.load
    internal/modules/cjs/loader.js:979:32
  
  - loader.js:819 Function.Module._load
    internal/modules/cjs/loader.js:819:12
  
  - loader.js:1003 Module.require
    internal/modules/cjs/loader.js:1003:19
  
  - v8-compile-cache.js:159 require
    [LeapFROGS]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - index.js:3 Object.<anonymous>
    [LeapFROGS]/[undici]/index.js:3:16
  

not finished load plugins - 0.876s
Error: Process completed with exit code 1.
```

### Reproduction Link

https://github.com/LinkedEarth/LeapFROGS/

### Steps to Reproduce

Link to workflow file: https://github.com/LinkedEarth/LeapFROGS/actions/runs/11151671210/workflow

### Expected Result

Deployment of site on gh-pages

### Actual Result

Link to error: https://github.com/LinkedEarth/LeapFROGS/actions/runs/11151671210/job/30995632172

### Environment

```shell
Not sure how to do this from a GitHub runner.
```

**Comment by serhalp** [comment]
Hi @khider,

The [nullish coalescing assignment operator was added in node 15](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_assignment#browser_compatibility). Your CI is configured to use node 14. You need to upgrade [here](https://github.com/LinkedEarth/LeapFROGS/actions/runs/11151671210/workflow#L20).

[Gatsby officially only supports node 18 and later](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/#minimal-nodejs-version-1800). I recommend going straight to node 20 if you can.
