### ISSUE TITLE
Is it possible to use Gatsby with React 16?

### ISSUE THREAD

**Issue by peduarte** [gatsbyjs/gatsby#3915]
Hello 👋 

Currently React 15 is a dependency of Gatsby.

I can see that for v2, this is going to be changed to be a peer dependency (https://github.com/gatsbyjs/gatsby/issues/1990) 👍 

However, is there a way to use React 16 currently? If I install React 16 as a dependency of my project, will I be able to use `React.Fragment` in my app?

Thanks

**Comment by m-allanson** [comment]
Hey @peduarte 👋 There's a plugin for React 16 at https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-react-next. However, fragments are only supported with babel v7 which is coming with Gatsby v2.

Which means you can currently use React 16, but without the new fragment syntax.

**Comment by pieh** [comment]
Just to clarify - you can use `<Fragment>` or `<React.Fragment>` (however you import it from `react` package) just not `<>` short syntax.

**Comment by peduarte** [comment]
Yeah, I'm happy to not use babel v7 and instead use `React.Fragment` 👍 

Thanks guys, very helpful!

**Comment by mpolinowski** [comment]
@pieh A question about [Loading performance? how to order the files loading to client? #2049](https://github.com/gatsbyjs/gatsby/issues/2049#issuecomment-363755928): solution posted at the bottom of the thread installs react/react-dom v16 over the dependencies that gatsby brings in (v15).

I could bring the material-ui/gatsby example to work, by first installing gatsby and then add react/react-dom @latest over it.

But trying this on my own repository doesn't work at all. Maybe I should have posted this over in the other thread...

**Comment by PedroGao** [comment]
If you are a typescript user , you can use React16 and Typescript in projects that is what I do . And it worked! Enjoy the react fregments!

**Comment by ThiagoMiranda** [comment]
@pieh getting undefined when importing Fragment like `import React, { Fragment } from 'react'`. Just installed a fresh new gatsby new project using their docs. Can you help me?

Thanks

**Comment by pieh** [comment]
@ThiagoMiranda you need to install https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-react-next plugin to use react 16

**Comment by ThiagoMiranda** [comment]
@pieh wow thanks for the quick response! It worked nicely
