### ISSUE TITLE
[www] Tutorial intro mentions five parts but lists four

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#3918]
Found that a little bit confusing. I think the fifth list item teasing the last part of the tutorial might have been removed recently and the "five parts" bit might be a leftover?

![image](https://user-images.githubusercontent.com/21834/35974305-d9831906-0cd8-11e8-8ce8-55351dd9cde5.png)

/cc @KyleAMathews @shannonbux

**Comment by KyleAMathews** [comment]
Oh right 😅

**Comment by KyleAMathews** [comment]
I'll fix it real quick.

**Comment by KyleAMathews** [comment]
Fixed in https://github.com/gatsbyjs/gatsby/pull/3927
