### ISSUE TITLE
Component setState callback is not fired

### ISSUE THREAD

**Issue by th0th** [gatsbyjs/gatsby#3919]
## Description

I couldn't find anything related on docs or issues, so I am not sure if it is a bug or is it a known caveat :) But `setState` callbacks are not fired on react components. I tried a very simple component:

    import React from 'react';

    export default class TestComponent extends React.Component {
      constructor(props) {
        super(props);

        this.state = {
          test: false,
        };

        this.setSetStateCallback = this.setSetStateCallback.bind(this);
      }

      setSetStateCallback() {
        console.log("State set.");
        
        this.setState({
          test: true,
        }, () => {
          console.log("It works!");
        });
      }

      render() {
        return (
          <div>
            <button onClick={this.setSetStateCallback}>Test!</button>
          </div>
        );
      }
    }

### Environment

Gatsby version: 1.9.158
Node.js version: 9.5.0
Operating System: macOS 10.12.6

### Actual result

I see only "State set." log on console. 

### Expected behavior

"It works!" log should appear on console when setState callback is fired.

**Comment by m-allanson** [comment]
Hey @th0th, I dropped your code into an existing Gatsby project and it seemed to work ok: 

<img width="128" alt="screen shot 2018-02-08 at 14 08 57" src="https://user-images.githubusercontent.com/381801/35977025-d615f116-0cd9-11e8-9148-99a4512813a0.png">

Using Gatsby v1.9.184, Node.js 9.5.0, macOS 10.13.3. I don't think there's anything that Gatsby does that should cause the issue you're seeing.

**Comment by th0th** [comment]
@m-allanson this is really strange :/ Any idea what might cause this issue? What's the react version you are using? Can you share your `package.json`?
