### ISSUE TITLE
[www] Consider consolidate "Filing an issue" and "Special Note on Issues"

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#3923]
* https://www.gatsbyjs.org/docs/how-to-contribute/#filing-an-issue
* https://www.gatsbyjs.org/docs/how-to-contribute/#special-note-on-issues

Worked on #3750 earlier today and wondered why the two sections above are "interrupted" by the "[Contributing](https://www.gatsbyjs.org/docs/how-to-contribute/#contributing)" section.

I find both "Filing an Issue" and "Special note on Issues" equally important and would like to suggest consolidating the two sections. Also it would allow us to link to one place instead of two in the starter `CONTRIBUTING.md` (first horrible draft here https://github.com/gatsbyjs/gatsby-starter-default/pull/44).

I also feel https://www.gatsbyjs.org/docs/how-to-contribute/#contributing would do a great job at acting as the introduction to https://www.gatsbyjs.org/docs/how-to-contribute/.

What do you think? Am I missing the obvious?

/cc @shannonbux

**Comment by shannonbux** [comment]
Those all sound like great ideas. These docs have evolved without planning
an overall vision. They need to be organized better! Please feel free to
organize them how you think is best!

I also think the section
https://www.gatsbyjs.org/docs/gatsby-style-guide/#how-to-contribute is
possibly inaccurate and redundant considering the How to Contribute page.
Should we just remove the how to contribute section from the style guide?

**Comment by KyleAMathews** [comment]
There should be a single page for "how to file an issue". The "How to Contribute" page has become sprawling and needs split up.

**Comment by m-allanson** [comment]
I just went to open a new issue and noticed this nice notification from GitHub 🎉 :

![screen shot 2018-02-12 at 10 21 31](https://user-images.githubusercontent.com/381801/36092287-bee49d6e-0fde-11e8-8e7e-0ddb720c6e6e.png)

**Comment by fk** [comment]
I 🤒 don't :sneezing_face: fully understand _how_ but 😻!

**Comment by shannonbux** [comment]
wow magical! How nice.
