### ISSUE TITLE
gatsby build issues - likely async related

### ISSUE THREAD

**Issue by gbailey4** [gatsbyjs/gatsby#3931]
## Description

Upon running ```gatsby build``` the build process crashes on the minify js portion.

### Environment

Gatsby version:
1.9.158
Node.js version:
8.9.1
Operating System:
macOS 10.13.3

### File contents (if changed):

`gatsby-config.js`: no change
`package.json`: no change
`gatsby-node.js`: no change
`gatsby-browser.js`: no change
`gatsby-ssr.js`: no change

### Actual result

error thrown:
```Error: component---src-pages-index-js-cfc2a63fd364824d8a69.js from UglifyJs
  SyntaxError: Unexpected token operator «*», expected punc «(» [./src/components/CreateLuncher.js:50,19]
```

### Expected behavior

successful build of project

### Steps to reproduce

1\. Build the repo here:
https://github.com/gbailey4/SimpleLunch

2\.
The specific file that is throwing the error is here:
https://github.com/gbailey4/SimpleLunch/blob/master/src/components/CreateLuncher.js

...

**Comment by m-allanson** [comment]
@gbailey4 I had a go at fixing this, based on [@Kalcode's comment](https://github.com/gatsbyjs/gatsby/issues/3314#issuecomment-355038591) .

First install a couple of babel plugins:
`npm i babel-plugin-transform-decorators-legacy babel-plugin-transform-regenerator`

Then add the following to your `gatsby-node.js` file:
```javascript
 exports.modifyBabelrc = ({ babelrc }) => ({
    ...babelrc,
    plugins: babelrc.plugins.concat(['transform-decorators-legacy', 'transform-regenerator']),
  })
```
That left the build with a _different_ error, which looks like it's related to trying to run browser code in Node. I'm not familiar with Apollo but if it should be client-only code, you'll need to check you're in a browser before running it. There's a bit more info at https://www.gatsbyjs.org/docs/debugging-html-builds/

**Comment by gbailey4** [comment]
Thank you very much. I actually forgot about the other error, but do have a fix for that. I will trust your fix soon and hope it goes as predicted!

**Comment by gscottqueen** [comment]
Had the same alert with async/await, @m-allanson is right on with the transform-regenerator recommendation.

**Comment by cdock1029** [comment]
This is the simplest solution I could find to solve **both** dev and prod which did not require `import`-ing anything in code:

My `.babelrc` file:

```json
{
  "env": {
    "development": {
      "plugins": ["syntax-async-functions"]
    },
    "production": {
      "plugins": ["transform-regenerator", "transform-runtime"]
    }
  }
}
```

**Comment by imcodingideas** [comment]
I have my fix similar to @gscottqueen but in `gatsby-browser.js` I added

```
exports.onClientEntry = () => {
  require('babel-polyfill')
}
```

**Comment by hassanshaikley** [comment]
hey all, I seem to be running into something similar? I am using async/awaits in some plugins.

Got these errors:

![screenshot_20181128_165820](https://user-images.githubusercontent.com/6746840/49190280-e45ac800-f32e-11e8-887c-f0a9d32570cf.png)

So I tried:

```
exports.onCreateBabelConfig = ({ actions }, pluginOptions) => {
    actions.setBabelPlugin({
        name: `@babel/plugin-transform-regenerator`
    })
    actions.setBabelPlugin({
        name: `@babel/plugin-transform-runtime`
    })
}
```
