### ISSUE TITLE
develop command fails silently on a new project with latest gastby-cli

### ISSUE THREAD

**Issue by pixelsonly** [gatsbyjs/gatsby#3932]
## Description

After having some issues updating dependencies on a production app, I installed a fresh gatsby-cli in Node 8.9.4 and created a new project for testing. Running `gatsby develop` fails silently.
<img width="842" alt="screen shot 2018-02-08 at 3 58 57 pm" src="https://user-images.githubusercontent.com/1099513/36004761-3f6a8104-0ce9-11e8-9865-14224dda7fee.png">

### Environment

Gatsby version: `1.1.38`
Node.js version: `8.9.4`
Operating System: `MacOS 10.13.3`

### Actual result

Build command fails with no output.

### Expected behavior

The app should finish booting, run GraphQL queries, and be ready for development.

...

**Comment by KyleAMathews** [comment]
Hmmm weird — testing

**Comment by KyleAMathews** [comment]
Replicated... just barely did a new release — what in the world went wrong...

**Comment by KyleAMathews** [comment]
1.1.39 is out with the fix. Thanks @pixelsonly for the issue!

**Comment by pixelsonly** [comment]
You're awesome @KyleAMathews!
