### ISSUE TITLE
gatsby-starter-docs-master throws error when gatsby develop issued on windoes 10 x64 machine

### ISSUE THREAD

**Issue by wisemonkey47** [gatsbyjs/gatsby#3938]
gatsby develop
success delete html files from previous builds — 0.033 s
success open and validate gatsby-config.js — 0.019 s
error UNHANDLED REJECTION

  Error: Unable to find plugin "gatsby-remark-images"

  - load-plugins.js:96 resolvePlugin
    [gatsby-starter-docs-master]/[gatsby]/dist/bootstrap/load-plugins.js:96:11

  - load-plugins.js:147 processPlugin
    [gatsby-starter-docs-master]/[gatsby]/dist/bootstrap/load-plugins.js:147:27

  - load-plugins.js:130
    [gatsby-starter-docs-master]/[gatsby]/dist/bootstrap/load-plugins.js:130:35

  - Array.forEach

  - load-plugins.js:129 processPlugin
    [gatsby-starter-docs-master]/[gatsby]/dist/bootstrap/load-plugins.js:129:40

  - load-plugins.js:168
    [gatsby-starter-docs-master]/[gatsby]/dist/bootstrap/load-plugins.js:168:28

  - Array.forEach

  - load-plugins.js:167 _callee$
    [gatsby-starter-docs-master]/[gatsby]/dist/bootstrap/load-plugins.js:167:28

  - index.js:122 _callee$
    [gatsby-starter-docs-master]/[gatsby]/dist/bootstrap/index.js:122:20

I am receiving above error message when I try to run gatsby develop on my windows 10 x64 machine. I am using node version 8.4.0 and npm version 5.3.0

Any help or suggestions would be welcome,

Nilkanth S. Desai

**Comment by m-allanson** [comment]
@wisemonkey47 Can you fill out the issue template here? With that info I can then look into what's going on.

**Comment by pieh** [comment]
It happens sometimes for me on windows that npm won't install packages correctly - usually deleting `node_modules` directory and rerunning `npm install` fixes this for me

**Comment by wisemonkey47** [comment]
Hi thank for tour time,
        Afrer following u r instructions Now I am getting following python path related error. For which I set the path corretly and python.exe gets executed correctly from the specified path in message. 


> sharp@0.17.3 install c:\dev\d\gatsby-starter-docs-master\gatsby-starter-docs-master\node_modules\sharp
> node-gyp rebuild


c:\dev\d\gatsby-starter-docs-master\gatsby-starter-docs-master\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python2.7", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\dev\d\gatsby-starter-docs-master\gatsby-starter-docs-master\node_modules\sharp
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN gatsby-docs-starter@1.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.17.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.17.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nsdesai\AppData\Roaming\npm-cache\_logs\2018-02-10T06_03_06_867Z-debug.log

c:\dev\d\gatsby-starter-docs-master\gatsby-starter-docs-master>

**Comment by KyleAMathews** [comment]
@wisemonkey47 it looks like Python isn't installed or setup correctly. Try following the instructions on this page to setup the necessary dependencies for Gatsby on Windows https://www.gatsbyjs.org/docs/gatsby-on-windows/
