### ISSUE TITLE
Bug parsing an array of dates from a yaml file on a cold build

### ISSUE THREAD

**Issue by lourd** [gatsbyjs/gatsby#3953]
## Description

When parsing an array of dates from a yaml file, gatsby fails to add it to the GraphQL schema when doing a build without a cache. This triggers warnings about invalid queries, because the property being requested doesn't exist. After killing the process and starting gatsby again, leaving the cache in place, the problem is resolved.

I've only observed this for data coming from yaml files, not JSON files.

This may be related to the work done in #3688 that resolved #3556. 

### Environment

Gatsby version: 1.9.190
Node.js version: 8.9
Operating System: macOS 10.12.6 and whatever version of Debian Netlify is using on their Docker container

### Steps to reproduce

See this repo https://github.com/lourd/gatsby-yaml-dates-array-bug

**Comment by pieh** [comment]
I will investigate this.

**Comment by pieh** [comment]
Just quick question - is this regression? Was it working earlier on cold build?

**Comment by lourd** [comment]
I just tried my test repo with Gatsby 1.9.185 and it also failed. (it's under a new branch called `regression` if you want to try it out). So it does not look like this is a regression. I guess your new work on date parsing is unrelated.

**Comment by pieh** [comment]
Yeah, I didn't change anything related to date specifically.

I see where the issue is and will make pull request with fix soon.
