### ISSUE TITLE
gatsby-transformer-remark - warn if there is no markdown file

### ISSUE THREAD

**Issue by tsriram** [gatsbyjs/gatsby#3961]
Well, it was totally (may be not totally!) wrong on my part that I installed & added all the required plugins to `gatsby-config` at the beginning of setting up a new Gatsby site. One of the plugins was `gatsby-transformer-remark` and when I opened up `GraphiQL` to check if I can see `allMarkdownRemark`, I could not see it. I was doing all sorts of things (deleting `node_modules` & reinstalling, moving around plugins in `gatsby-config` etc.) without realizing that I did not have any markdown file in my site directory :man_facepalming:

Not sure if anyone else faced this problem! Ideally I'd expect the plugin to print a warning if it is added to `gatsby-config` but did not get any resource to process (in this case a markdown file). I'm happy to send a PR if this makes sense.

**Comment by Jaikant** [comment]
Yes this is an issue, more so as the schema is generated dynamically and if your graphql queries makes an assumption on the non existing frontmatter, the build process bails out in between with errors which are confusing.

**Comment by benjaminhoffman** [comment]
wow.  deleting my `node_modules` solved this.  SMH.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
