### ISSUE TITLE
Question re: Custom typography

### ISSUE THREAD

**Issue by edouerd** [gatsbyjs/gatsby#397]
Hello!

I have a quick question regarding custom font inclusion:

How might I go about adding a set of fonts to a project? Is there a particular folder I'd place font assets inside? Is this all as straightforward as normally adding fonts to a `/static` folder (static assets) and referencing the fonts via style.css?

I saw that gatsby is packaged with typography.js, but I'm unsure how to have my site easily utilize fonts that are non-google fonts.

Thanks!

**Comment by KyleAMathews** [comment]
I haven't done this but this blog post should get you started https://shellmonger.com/2016/01/22/working-with-fonts-with-webpack/

Gatsby *should* be setup correctly already for Webpack to handle things so you just need to import the font files and they'll be included in the public directory.

If the default webpack config doesn't work out of the box please let us know! https://github.com/gatsbyjs/gatsby/blob/5d6872f7446a5d71734532889feb5ccf191b1f37/lib/utils/webpack.config.js#L241

**Comment by KyleAMathews** [comment]
I should add that you can still use Typography.js with custom fonts! Just put your font name at the start of the `headerFontFamily` and `bodyFontFamily` arrays!

**Comment by edouerd** [comment]
thank you much!

for one last question re: the answers above — I see that the article you linked mentions placing fonts into a client/src/fonts directory, yet the file structure he's describing differs quite a bit from the default structure gatsby constructs pre-compiling:

The author's setup:

![screen shot 2016-08-18 at 4 35 53 pm](https://cloud.githubusercontent.com/assets/1195363/17789826/dc2436ce-6561-11e6-97b7-2d4301fabd54.png)

mine/gatsby's:

![screen shot 2016-08-18 at 4 32 12 pm](https://cloud.githubusercontent.com/assets/1195363/17789700/5a8cc73e-6561-11e6-87c8-b37af9bd0de4.png)

Will simply creating the directory structure mentioned in the author's document work for my purpose?

**Comment by KyleAMathews** [comment]
I would simply create a fonts directory and put the src files there. The
webpack file-loader will take care then of copying the files to the public
directory.
