### ISSUE TITLE
Guide for "Styled Components" missing some info so it breaks

### ISSUE THREAD

**Issue by m2mathew** [gatsbyjs/gatsby#3973]
## Description

In the ["Using CSS-in-JS library Styled Components" guide](https://www.gatsbyjs.org/docs/styled-components/) there is a step missing when adding the styled-components code to the `pages/index.js` file.

Based on the specific installation instruction provided, this component doesn't exist in the project at any point. It will break the app when running `gatsby develop`.

```
import Container from "../components/container";
```

### Expected behavior

Show the user how to build the `<Container>` component so that that goodness of styled-components can shine through! 🌞

**Comment by calcsam** [comment]
Thanks for finding this! Want to add this?

**Comment by RxAssim** [comment]
I can take this one if no one's working on it already :)

**Comment by KyleAMathews** [comment]
Fixed by @RxAssim in https://github.com/gatsbyjs/gatsby/pull/3988 🎉
