### ISSUE TITLE
Gatsby-image not working with Gatsby-paginate

### ISSUE THREAD

**Issue by aaronaustin** [gatsbyjs/gatsby#3983]
I’m trying to get Gatsby-image working with Gatsby-pagination.  I managed to get gatsby-paginate working, but when I include 

```
image {
  sizes(maxWidth: 400) {
    ...GatsbyContentfulSizes
  }
}
```
in my graphql query in gatsby-node.js, my development build fails.  I've tried to include a graphql query in my template, but I get this error: `GraphQLError: Variable "$id" of required type "String!" was not provided.`  

Everything works when I remove the image sizes query above.  Is there a way to get gatsby-image working with pagination?  I've been through the examples, but haven't found one yet.  

Here's the relevant gatsby-node section.  Thanks.

```
.then(() => {
        graphql(
          `
            {
              allContentfulSongs(limit: 1000) {
                edges {
                  node {
                    id
                    slug
                    title
                    path
                    image {
                      id
                      #sizes(maxWidth: 200) {
                      #  ...GatsbyContentfulSizes
                      #}
                    }
                  }
                }
              }
            }
          `
        ).then(result => {
          if (result.errors) {
            reject(result.errors)
          }
          const categoryTemplate = path.resolve(`./src/templates/category.js`)
          createPaginatedPages({
            edges: result.data.allContentfulSongs.edges,
            createPage: createPage,
            pageTemplate: categoryTemplate,
            pageLength: 5,
            pathPrefix: "songs",
            buildPath: (index, pathPrefix) => index > 1 ? `${pathPrefix}/${index}` : `/${pathPrefix}`
          })
          _.each(result.data.allContentfulSongs.edges, edge => {
            createPage({
              path: `${edge.node.slug}/`,
              component: slash(categoryTemplate),
              context: {
                id: edge.node.id,
              },
            })
          })
```

**Comment by pieh** [comment]
You can't use fragments (`...GatsbyContentfulSizes`) in `gatsby-node.js`. Instead write specific fields you want to get (so just copy fields from here https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/src/fragments.js#L46-L50 to get equivalent)

**Comment by KyleAMathews** [comment]
Also, the only data you should query for in gatsby-node.js is the slug and id. You use the id then in your src/templates/category.js page to query for the data needed by each page.

**Comment by aaronaustin** [comment]
Thanks @pieh. That makes sense. 

Thanks @KyleAMathews - that's what I've been doing until using gatsby-paginate.  When I try to query data in category.js, I get this error `GraphQLError: Variable "$id" of required type "String!" was not provided.`  As you can see above, I'm still passing in the id, but I haven't been able to figure out why the id isn't getting passed.

**Comment by aaronaustin** [comment]
Thanks @pieh.  I got this working without the fragment in Gatsby-paginate.  I can't find any examples of Gatsby-paginate using querys in the template though.  Is there an example somewhere?

**Comment by KyleAMathews** [comment]
They're just normal page components so query like normal.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by sakhisheikh** [comment]
@KyleAMathews We embed all paginated data from server at build time? Suppose if we have 20 pages how can we optimize it ?
