### ISSUE TITLE
Errors in config cause dev server to exit

### ISSUE THREAD

**Issue by nickmccurdy** [gatsbyjs/gatsby#3990]
## Description

When there is any syntax error or other uncaught error added to `gatsby-config.js` after `gatsby develop` is started, the development server exits with a non-zero code.

### Environment

Gatsby version: 1.9.192
Node.js version: 9.5.0
Operating System: macOS

### File contents (if changed):

`gatsby-config.js`: Anything with invalid syntax or throwing an error, added after starting Gatsby. The contents when starting Gatsby should be valid.

### Actual result

The development server exits with a non-zero code.

### Expected behavior

Gatsby's development server should not quit because other file modifications never cause the server to quit, and this causes an inconsistent and confusing development experience. It should either keep the server running and display the error like with other Gatsby errors, or not watch the config after starting at all.

**Comment by deltaskelta** [comment]
this seems similar to the error I was experiencing as well

**Comment by nickmccurdy** [comment]
I'm not sure if it happens elsewhere, though I tested by typing random invalid syntax in the other `gatsby-*.js` files and in `src/*.js` and the server kept running.

**Comment by KyleAMathews** [comment]
Should be fixed now! Please upgrade to the latest and report back if there's any problems still. Thanks for reporting the issue
