### ISSUE TITLE
Code blocks highlight all keywords even in which are enclosed in HTML tags

### ISSUE THREAD

**Issue by ajayns** [gatsbyjs/gatsby#4002]
## Description

In the Gatsby Docs, the code blocks highlight keywords even though they are plain text within html.
I started noticing this while I was at this particular tutorial page: (https://www.gatsbyjs.org/tutorial/part-three/)

### Actual result
![image](https://user-images.githubusercontent.com/20743219/36136250-7cf4a2aa-10b5-11e8-930a-a5c778582884.png)

### Expected behavior

The above image, the words `do`, `of`, `as` should be displayed like normal text, not highlighted.

**Comment by m-allanson** [comment]
Thanks @ajayns, this looks like a bug in PrismJS. I've opened an issue over there.

**Comment by m-allanson** [comment]
This has been fixed in PrismJS 🎉. Once the fix is released [`gatsby-prism-remark` will need to be updated here](https://github.com/gatsbyjs/gatsby/blob/888d3e6dbcccf3fe986137bbd027f6ff1d99fa84/packages/gatsby-remark-prismjs/package.json#L12).
