### ISSUE TITLE
[docs] Improve gatsby-image docs

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#4009]
We need to make it clear in the [gatsby-image](https://www.gatsbyjs.org/packages/gatsby-image/) README that we're using [gatsby-plugin-sharp](https://www.gatsbyjs.org/packages/gatsby-plugin-sharp/) under the hood and all its options like `quality` are available.

Ref. #3984

**Comment by tulikavijay** [comment]
I would like to work on this.

**Comment by fk** [comment]
Hi @tulikavijay! That's great, thank you!

**Comment by stevenandersonz** [comment]
Is this issue already taken? I would like to work on it.

**Comment by fk** [comment]
Hi @stevenandersonz! Thank you for offering help! 🤗 
@tulikavijay resolved this issue in #4019, we just didn't follow up closing it—will do so now.

However if you find anything to add or improve, please don't hesitate opening a new issue and/or adding a pull request. Help with documentation is always super appreciated!
