### ISSUE TITLE
Manifest.json - error on missing images

### ISSUE THREAD

**Issue by imshuffling** [gatsbyjs/gatsby#4010]
## Description

Just moved hosting from Github pages to Netlify.

Manifest images seem to be 404 in the console, using the default layout as here - https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-manifest

### Environment

Gatsby version: 1.9.194
Node.js version:  9.2.0
Operating System: Mac

Using -  "gatsby-plugin-manifest": "^1.0.14",

**Comment by imshuffling** [comment]
`Error while trying to use the following icon from the Manifest: https://XXX/favicons/android-chrome-192x192.png (Download error or resource isn't a valid image)`

**Comment by m-allanson** [comment]
Does it work if you move your favicons from `/src/favicons/` to `/static/favicons`?

**Comment by imshuffling** [comment]
Thanks - tried that, strange thing is when i run `gatsby serve` locally to runs no problem.

<img width="568" alt="screen shot 2018-02-15 at 10 56 22" src="https://user-images.githubusercontent.com/739061/36253286-fcb204bc-123e-11e8-803b-3ab1de473498.png">

<img width="322" alt="screen shot 2018-02-15 at 10 56 54" src="https://user-images.githubusercontent.com/739061/36253289-00aac324-123f-11e8-9ead-de9832451052.png">

Wondering if netlify changes paths somehow?

**Comment by imshuffling** [comment]
Looking into whether this is the answer - https://www.gatsbyjs.org/packages/gatsby-plugin-netlify/

**Comment by pieh** [comment]
Do you have your icons in `static/static/favicons/android_chrome_X.png` in your project directory? (content of `static` directory is being copied to build (`public` directory)

**Comment by imshuffling** [comment]
@pieh - Nope, they are currently in `public/static/favicons/android_chrome_X.png`

I manually copied them into this directory, am i missing something?

**Comment by pieh** [comment]
In general you don't want to put anything manually in `public` directory as this directory can be purged. If you want files in your `public` directory then use `static` directory ( https://www.gatsbyjs.org/docs/adding-images-fonts-files/#using-the-static-folder )

**Comment by imshuffling** [comment]
Ok I'll give that a go, must of missed that in the docs - thanks for your help.

**Comment by imshuffling** [comment]
OK - just deployed and I'm still not seeing the files.

<img width="285" alt="screen shot 2018-02-15 at 11 43 24" src="https://user-images.githubusercontent.com/739061/36255113-968931ea-1245-11e8-827e-21cb33600432.png">

Cache gets cleared on deploy so not sure where I'm going wrong?

**Comment by pieh** [comment]
I do see them - https://davidrich.es/favicons/android-chrome-192x192.png

This might be confusing but files from `static` directory are copied directly to `public` directory (and not `public/static`) - this is so people can put stuff like `robots.txt` etc directly in root directory of their build. So you will have to adjust paths in your `gatsby-plugin-manifest` config to `/favicons/android-chrome-192x192.png` (remove `static` directory there)

**Comment by imshuffling** [comment]
@pieh - That seems to have done the trick, thanks for your help.
