### ISSUE TITLE
Rendering completely different page as parent route

### ISSUE THREAD

**Issue by oznekenzo** [gatsbyjs/gatsby#4015]
Hello!

Thanks for making Gatsby.  Figuring out how to do routes here.

I'm wanting to render a page whose contents are entirely different from that of its parent route.
Case 1, 2, and 3 all share some common components.  The contents of these pages are dependent upon on params and rendered correctly with switch statements.

For case 4, however, I want to render all new components.

With Gatsby, for case 4, is the best practice to wrap this in yet another switch statement?

**Case 1, 2, 3:**
/user/:username (user bio + list of repos)
/user/:username/following (user bio + following users)
/user/:username/followers (user bio + users following)

**Case 4:**
/user/:username/repo (only repo info)

Gatsby v1.9.127
Node v6.9.5

**Comment by calcsam** [comment]
You probably want to take a look at https://www.gatsbyjs.org/docs/bound-action-creators/#createPage. 

Gatsby works differently than React Router -- it doesn't use the nested-routes / nested-layouts model. Instead, you use createPage, typically in a loop following a GraphQL query, to create whatever pages you want, with whatever component you want. Take a look at this example:

https://github.com/gatsbyjs/gatsby-starter-blog/blob/master/gatsby-node.js

**Comment by KyleAMathews** [comment]
Also part 4 of the tutorial covers creating pages https://www.gatsbyjs.org/tutorial/part-four/
