### ISSUE TITLE
`gatsby develop` broken on case-sensitive filesystems.

### ISSUE THREAD

**Issue by jaen** [gatsbyjs/gatsby#402]
For some reason this file here: https://github.com/gatsbyjs/gatsby/blob/master/lib/isomorphic/html.js is compiled into `HTML.js` in your dist tarball (https://registry.npmjs.org/gatsby/-/gatsby-0.12.5.tgz) which makes the `gatsby develop` command to break on case-sensitive filesystems.

Would you mind releasing a new version with lowercased filesystem names?

**Comment by KyleAMathews** [comment]
Well... that's bizarre. I have no idea why this is happening. The build script just runs babel over the `lib` files to compile them to `dist`. I release from my mac fwiw. If you have some time to research what's happening I'd really appreciate that. Otherwise I'll get to this in the next few days.

**Comment by jbolda** [comment]
@KyleAMathews I assume this is fixed? Closing on that assumption.
