### ISSUE TITLE
Webpack resolve.modules not working

### ISSUE THREAD

**Issue by jarodtaylor** [gatsbyjs/gatsby#4025]
## Description

I'm unable to use Webpack [resolve.modules](https://webpack.js.org/configuration/resolve/#resolve-modules) in my `gatsby-node-js` file.

### Environment

Gatsby version: 1.1.39
Node.js version: 8.2.1
Operating System: OS X

### File contents (if changed):
`gatsby-node.js`:
```js
  config.merge({
    resolve : {
      modules : [
        'src',
        'node_modules'
      ]
    }
  });
```

### Actual result

This throws an error when I run `gatsby develop`:

```bash
There were errors with your webpack config:
[1]
resolve.modules
object.allowUnknown , "modules" is not allowed


Your Webpack config does not appear to be valid. This could be because of
something you added or a plugin. If you don't recognize the invalid keys listed
above try removing plugins and rebuilding to identify the culprit.
```

I'm not sure if this repo is using [webpack-validator](https://www.npmjs.com/package/webpack-validator), and that's causing the issue, but I know that Webpack 2 pretty much made webpack-validator obsolete.

**Comment by KyleAMathews** [comment]
We're on webpack 1 still so yeah, using webpack-validator. 

What are you trying to accomplish with the webpack config edit?

**Comment by jarodtaylor** [comment]
@KyleAMathews ah, got it. I thought you guys were on Webpack 2 (pushing for 3 in Gatsby 2.0). Makes sense.

I was able to accomplish it with `resolve.alias`:

```
  config.merge({
    resolve : {
      alias: {
        src: path.resolve(__dirname, 'src'),
        components: path.resolve(__dirname, 'src/components'),
        layouts: path.resolve(__dirname, 'src/layouts'),
        pages: path.resolve(__dirname, 'src/pages')
      }
    }
  });
```

This was just so I could `import FileName from 'components/FileName'` instead of `import FileName from '../../components/FileName'`;

**Comment by KyleAMathews** [comment]
Ah cool :-) Yeah, common request.

For others who stumble across this thread, there's also a plugin that does this webpack tweak https://github.com/alampros/gatsby-plugin-resolve-src
