### ISSUE TITLE
Tutorial project 'gatsby develop' reloading suboptimal

### ISSUE THREAD

**Issue by Twitchkidd** [gatsbyjs/gatsby#4027]
## Description

HMR for the tutorial project

### Environment

Gatsby version: 1.1.40
Node.js version: 8.9.3
Operating System: macOS 10.13.3 

### File contents (if changed):

`gatsby-config.js`: not changed
`package.json`: not changed
`gatsby-node.js`: not changed
`gatsby-browser.js`: not changed
`gatsby-ssr.js`: not changed

### Actual result

404, process terminated

### Expected behavior

404, process waits for like onchange '**/*.js'

### Steps to reproduce

1\. gatsby new tutorial-part-one-recreation https://github.com/gatsbyjs/gatsby-starter-hello-world

2\. cd tutorial-part-one-recreation && gatsby develop

3\. navigate to localhost:8000/

4\. import Link from "gatsby-link"; and return (<div><Link to="second-page">second page</Link></div>) from index.js in pages/

5.\ hmr does it's thing, click Link from localhost:8000/

6.\ 404

7.\ create pages/second-page.js with import React from 'react'; export default () => <div>hai</div>

8.\ navigate to localhost:8000/

9.\ 404

10.\ Inspect terminal, see that "You have an empty file in the "src/pages" directory at "src/pages/second-page.js". Please remove it or make it a valid component" was printed and the process killed.

11.\ gatsby develop

12.\ navigate to localhost:8000/

13.\ All's well that ends well, but getting that onboarding flow down is a doozy, ya know?

14.\ Looks like same thing with just gatsby new new-gatsby-site, not just from the url above

**Comment by m-allanson** [comment]
I thought maybe we could wrap [these](https://github.com/gatsbyjs/gatsby/blob/3c1cae921cc5804707902356b9ba35b79302ac69/packages/gatsby/src/redux/actions.js#L235) [exits](https://github.com/gatsbyjs/gatsby/blob/3c1cae921cc5804707902356b9ba35b79302ac69/packages/gatsby/src/redux/actions.js#L252) with `if (process.env === 'production') process.exit(1)`. Which _does_ prevent the `develop` command from exiting. 

However, the page doesn't get revalidated when you change it. It looks like we'd need to trigger this on a `MODIFY_PAGE` action? Currently Gatsby has just `CREATE_PAGE` and `DELETE_PAGE` actions. I don't have a full model of how these parts of Gatsby work, so there may be a more efficient way to fix this.

**Comment by KyleAMathews** [comment]
Working on a better solution for this.

@jquense suggested at some point in the past that we have an easy way for warnings/errors to only warn in some environments and hard error (i.e. kill the process) in others. E.g. many more things should die during builds but not during development. It probably makes sense as well for some things to kill the process during the development bootstrap but *not* while the development server is running. The first is what I was thinking with killing things when there's an empty file but forgot that this is a common state for files to be in when you first add them.

I think I'll just make these all warnings for now and we can do a refactor in the future to make it easy for warnings to turn into errors when we want.

**Comment by m-allanson** [comment]
It'd be great to tie this in with a 'logging level' system also - so the points where Gatsby silently eats errors could optionally be reported too. I saw there's a verbose mode for that in `gatsby-cli` but I'm not sure how widely it's used.

**Comment by jquense** [comment]
@KyleAMathews  we should be in a place to do that BTW, gatsby cli sets the running command to process.env, we really just need to add a helper method in reporter. that's `panicOnBuild`

**Comment by KyleAMathews** [comment]
@jquense let's do it for v2
