### ISSUE TITLE
No documentation found or referred to in tutorials for createFilePath

### ISSUE THREAD

**Issue by ajayns** [gatsbyjs/gatsby#4028]
## Description

While going through tutorial 4, there seem to a couple of functions which seem to be just appear and do things magically. No links or documentation could be found for details on how `node`, `getNode`, `createFilePath` works. 

Only documentation I could find was for [gatsby-source-filesystem](https://www.gatsbyjs.org/packages/gatsby-source-filesystem/)

**Comment by m-allanson** [comment]
Thanks for raising this @ajayns, I agree it's not very clear where they're coming from.

You're right that `createFilePath` comes from `gatsby-source-filesystem`, it could do with being documented.

A `node` object is the basis of how Gatsby structures its data, there's a bit more info about nodes on the [Node Interface docs page](https://www.gatsbyjs.org/docs/node-interface/).

It looks like `getNode()` is commonly used by plugins, but I can't see any docs on it. There's actually a lot more data that gets passed to the API methods like `onCreateNode`. 

How should we document `node`, `getNode` and the other data that gets passed to the API methods? Should there be an in-depth page in the _Reference_ section that covers a bit more about how Gatsby works internally?

**Comment by ajayns** [comment]
To get started with, the [Node Interface docs page](https://www.gatsbyjs.org/docs/node-interface/) can be mentioned in the [section](https://www.gatsbyjs.org/tutorial/part-four/#programmatically-creating-pages-from-data) where nodes come in tutorial 4, this would help guide people who wanna know a bit in depth of how it works in the back.

Further more, you're right `getNode()` is commonly used by these plugins and there are no docs. This wouldn't really affect a person who's building projects on GatsbyJS but then for developers working on plugins, this could be a matter of importance. I haven't gotten into developing plugins myself right now, so I can't exactly say, but, a Reference section would really help if it explained a bit of how everything goes together without being verbose. @m-allanson

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by selrond** [comment]
@ajayns just stumbled upon `createFilePath`, and haven't found any docs for it - any updates?
