### ISSUE TITLE
Uncaught TypeError: (0 , _reactRouterScroll2.default) is not a function

### ISSUE THREAD

**Issue by renatorib** [gatsbyjs/gatsby#403]
This error is not leaving my application to run. What can be causing this, since this is part of gatsby core?

**Comment by KyleAMathews** [comment]
You need to upgrade to 0.12.5. This bug was released as part of 0.12.4.

**Comment by KyleAMathews** [comment]
Let me know if that doesn't fix it.

**Comment by renatorib** [comment]
Thanks, I'll try
