### ISSUE TITLE
Api check for `gatsby-plugin-react-helmet` fails

### ISSUE THREAD

**Issue by digitalkaoz** [gatsbyjs/gatsby#4030]
`The plugin "gatsby-plugin-react-helmet@2.0.5" is exporting a variable named "onRenderBody" which isn't an API.`

there was a patch yesterday, but i guess it was only half done...

```
    "gatsby": "^1.9.197",
    "gatsby-plugin-react-helmet": "^2.0.5",
```

**Comment by nickmccurdy** [comment]
I had this in Gatsby 1.9.194 using 2.0.5 of the plugin, upgrading to Gatsby 1.9.197 fixed it for me.

**Comment by digitalkaoz** [comment]
yeah it seemed there was still an old version...seems workin now

**Comment by KyleAMathews** [comment]
Yeah @m-allanson fixed it yesterday! Sorry for the brief weirdness 😅
