### ISSUE TITLE
[gatsby-plugin-netlify-cms]: Breaks Gatsby `develop` and `build`

### ISSUE THREAD

**Issue by peduarte** [gatsbyjs/gatsby#4031]
Hello 👋

I've noticed that by adding the latest `gatsby-plugin-netlify-cms` plugin, `gatby develop` and `gatsby build` stop working.

I've done a few tests and isolated the issue down to this plugin. If I remove it, everything works again.

Below are the errors I'm getting:

----

**gatsby develop**

![carbon 3](https://user-images.githubusercontent.com/372831/36196826-d8b3a334-1169-11e8-9fda-01dce7ceb270.png)

**gatsby build**

![carbon 2](https://user-images.githubusercontent.com/372831/36196834-ddad5db2-1169-11e8-8d77-94e35f4338d1.png)

---

**package.json**
![carbon 4](https://user-images.githubusercontent.com/372831/36196899-0bfe01ee-116a-11e8-827b-d9100d92b72f.png)

---

I've tried downgrading the version of all packages, but not luck. The only way to get my build to work again is by removing `gatsby-plugin-netlify-cms`.

Appreciate any guidance, thanks! 👍

**Comment by tech4him1** [comment]
(I will warn that this is somewhat speculation, I haven't dug too deeply.)

Tracing the error back to Acorn and WebPack, it looks like WebPack version 1, which Gatsby is using, has the Acorn parser set to parse ES6 and lower ([webpack/lib/Parser.js#v1.15.0](https://github.com/webpack/webpack/blob/d4878a55be7a4b7ac4e5db1ae5eef89e15811072/lib/Parser.js#L880)). The latest version of WebPack supports parsing up to ES2017 and lower ([webpack/lib/Parser.js#master](https://github.com/webpack/webpack/blob/60275c377d63428c26bc5060c2056e3ae164665a/lib/Parser.js#L27)). This is why the Gatsby WebPack loader cannot parse the Netlify CMS unless we transpile anything newer than ES6.

cc/ @erquhart @talves

**Comment by talves** [comment]
@tech4him1 Your hypothesis seems right on point with what I was finding in my tests.

**Comment by pogo19** [comment]
@tech4him1 @talves I've read somewhere that Webpack version upgrade is planned for Gatsby v2 by @KyleAMathews ... still a solution for Gatsby v1 is needed I think.

**Comment by tech4him1** [comment]
@pogo19 Yes, @erquhart linked it to https://github.com/gatsbyjs/gatsby/issues/2641.

**Comment by peduarte** [comment]
It's mentioned on https://github.com/netlify/netlify-cms/issues/1097 that the temp fix is to revert to `netlify-cms@1.1.0.`.

However, as `gatsby-plugin-netlify-cms` declares `netlify-cms` dependency with `^1.0.1` so it's installing  `1.2.0`.

Is there a temp workaround?

**Comment by tech4him1** [comment]
If you are using Yarn, you can add to your `package.json`:
```
"resolutions": {
  "gatsby-plugin-netlify-cms/netlify-cms": "1.1.0"
}
```

**Comment by bytheway875** [comment]
@peduarte 
Do you have any custom rules in your gatsby-node file for the js loader by chance?

**Comment by pogo19** [comment]
@peduarte If you are using yarn, you can use this in your package.json:
```
"resolutions": {
  "gatsby-plugin-netlify-cms/netlify-cms": "1.1.0"
}
```

**Comment by erquhart** [comment]
#4046 will break the plugin in an additional, unrelated way once merged. Tracking here since the net goal of this issue is making the plugin work again. Thoughts on a potential alternate approach in [#4044](https://github.com/gatsbyjs/gatsby/issues/4044#issuecomment-365824391).

**Comment by peduarte** [comment]
@pogo19 awesome, thank you! 🙏

**Comment by Jaikant** [comment]
@pogo19 Using the work around the `gatsby develop` and `gatsby build` works fine. Thanks!

Unfortunately the cms is still broken on going back. Uploading media files or submit fails. An image file upload fails with the below error ...

```
cms.js:174 Uncaught (in promise) TypeError: Cannot read property 'find' of undefined
    at http://localhost:8000/cms.js:2883:75088
    at r (http://localhost:8000/cms.js:2899:122589)
    at Generator._invoke (http://localhost:8000/cms.js:2899:122377)
    at Generator.e.(anonymous function) [as next] (http://localhost:8000/cms.js:2899:122768)
    at o (http://localhost:8000/cms.js:2727:11606)
    at http://localhost:8000/cms.js:2727:11754
    at new Promise (<anonymous>)
    at new t (http://localhost:8000/cms.js:2727:1085)
    at http://localhost:8000/cms.js:2727:11548
    at http://localhost:8000/cms.js:2883:76032
```

**Comment by pogo19** [comment]
@Jaikant If you think it is an error in Netlify CMS, please report the issue in Netlify CMS Github.

**Comment by csi-lk** [comment]
Is it worth pushing a new release of `gatsby-plugin-netlify-cms` with `netlify-cms@1.1.0` to work around for the moment or are we going to wait for the upstream fix?

**Comment by erquhart** [comment]
That won't be necessary, I'm working on a fix for this right now. Stay tuned.

**Comment by erquhart** [comment]
Fixed in netlify-cms 1.2.2.

**Comment by erquhart** [comment]
@peduarte can you try it now and close this if things are working?

**Comment by peduarte** [comment]
@erquhart sure, will do!

**Comment by talves** [comment]
@peduarte you may have to `yarn upgrade gatsby-plugin-netlify-cms` , it updates the sub dependencies.

**Comment by peduarte** [comment]
Beautiful, great work everyone 🎉

**Comment by TomPichaud** [comment]
I just started a new project using 'gatsby-plugin-netlify-cms', and I'm still not able to build my CSS Module if the plugin is active, 'gatsby develop' works fine 'gatsby build' output an error : 

`Error: /Users/Tom/Developer/GitHub/wise-starter/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"r  emove":true}!/Users/Tom/Developer/GitHub/wise-starter/node_modules/style-loader/index.js!/Users/Tom/Developer/GitHub/wise-starter/node_modules/css-loader/index.js?modules&minimize&importLoa  ders=1&localIdentName=[path]---[name]---[local]---[hash:base64:  5]!/Users/Tom/Developer/GitHub/wise-starter/node_modules/sass-loader/index.js?{"plugins":[]}!/Users/Tom/Developer/GitHub/wise-  starter/src/components/header.module.sass doesn't export conten  t`

**Comment by pogo19** [comment]
Hey Tom! Do you have the newest versions? What are the used versions of plugin and of its dependency to `netlify-cms`?

**Comment by TomPichaud** [comment]
```
"gatsby-plugin-netlify-cms": "^1.0.11"

"dependencies": {
    "html-webpack-include-assets-plugin": "^1.0.2",
    "html-webpack-plugin": "^2.30.1",
    "netlify-cms": "^1.0.1",
    "netlify-identity-widget": "^1.4.11"
  }

```
I tried your solution, but still not working

`"resolutions": {
  "gatsby-plugin-netlify-cms/netlify-cms": "1.1.0"
}`

**Comment by erquhart** [comment]
@TomPichaud are you using css modules?

**Comment by TomPichaud** [comment]
yes

**Comment by TomPichaud** [comment]
Simple test using CSS Modules, https://github.com/TomPichaud/test-cms-plugin

<img width="1440" alt="screen shot 2018-03-02 at 01 24 30" src="https://user-images.githubusercontent.com/963740/36878882-ed6098f4-1db8-11e8-95a2-322545108ea3.png">

But `Gatsby develop` works just fine !

**Comment by erquhart** [comment]
Alright I think I know what's going on, I'll take a swing at it in the morning.

**Comment by TomPichaud** [comment]
Thanks for having a look, I hope this will be resolved soon. Should we reopen the issue or create a new one ?

**Comment by erquhart** [comment]
@TomPichaud creating a new one would be great.
