### ISSUE TITLE
Offer more DateTime filter options (currently only eq)

### ISSUE THREAD

**Issue by babycourageous** [gatsbyjs/gatsby#4033]
## Description

The site I am building needs more DateTime filtering options than currently provided with Gatsby. Fro example filtering content based on whether it falls before or after a certain date. I'm hoping that a future version of Gatsby might be able to supply that!

**Comment by pieh** [comment]
This is something I want to add. I have planned refactoring of graphql that should make it easier to add, just need to get more free time to get this done.

**Comment by AniaMakes** [comment]
@pieh I was wondering if you could point out to me where in the code this logic lives? My current project would benefit hugely from a Date-after filter, and if this something that I can help with on Gatsby end, I'd like to give that a go.

**Comment by mattferderer** [comment]
One simple fix I implemented was to use a reduce function to remove any future marked content after the GraphQL query returns the results. Then I make sure to run a build task daily. It's a simple hack but one I thought worth mentioning.

A GraphQL solution would be much better though!

**Comment by pieh** [comment]
This is 2 part job:
1. Adjust input schema to add needed operators for Date fields - this happens here https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/infer-graphql-input-fields.js (inferring from data) and https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/infer-graphql-input-fields-from-fields.js (creating filter input schema for fields created with `setFieldsOnGraphQLNodeType` action).

Problem to solve here - we don't know there if strings represents date so would have to use same check we do when we generate output fields - https://github.com/gatsbyjs/gatsby/blob/4a946428cb555c8141c7f69544bbd528f11a5c1a/packages/gatsby/src/schema/infer-graphql-type.js#L96
2. Actually apply filterring in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/run-sift.js - I see 2 options here:
- add new operators to sift to handle date filtering ( https://www.npmjs.com/package/sift#custom-expressions )
- or convert date fields to something that can use already existing operators - like `lt`, `lte`, `gt`, `gte` for numbers

**Comment by AniaMakes** [comment]
@mattferderer yeah, I considered that approach - at the moment it's not an issue, but eventually we are likely to end up with 100s of irrelevant entries that are getting fetched. My other option is to write a script that runs every day and archives past events on Contentful so they are not being served to the website. 

@pieh Thanks for the info! I'm a relative newcomer to the world of software development, so it looks like it's more than I can manage, but I (and anyone else wanting to tackle this issue) now know what needs to be done :)

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by ScreamZ** [comment]
@KyleAMathews @pieh Hey guys,

I would like to filter all my documents that are less than now/today ? Any way nowadays to do this using the graphQL syntax or am I forced to to this after the query ? (eq / ne / regex, …) only atm

Regards
