### ISSUE TITLE
Help debugging vague build failures that occur at building HTML

### ISSUE THREAD

**Issue by lourd** [gatsbyjs/gatsby#4035]
## Description

I've got a Gatsby site that I'm hosting on Netlify that has a failing build on Netlify. I've tried everything I can think of and was hoping to find advice on other things to try. I've read the [docs page](https://www.gatsbyjs.org/docs/debugging-html-builds/) and tried the suggestions there, but my case is not one of the problems listed there. (But I will definitely add my case and more steps to the docs when I figure out what it is!)

My hunch is that it's something with Sharp and image processing. I've got a few dozen images that get processed at build time, and I'm wondering if the Netlify build server is somehow choking on them. The missing data causing the null reference is related to a GraphQL query looking for image data.

I've tried building with a clear Netlify build cache — didn't change anything.

### Environment

Gatsby version: 1.9.197
Node.js version: 8.9.4
Operating System: Ubuntu 14.04
Yarn: 1.4.1

### File contents (if changed):

`gatsby-config.js`:

```js
module.exports = {
  plugins: [
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-styled-components`,
    `gatsby-plugin-resolve-src`,
    `gatsby-plugin-react-next`,
    `gatsby-plugin-catch-links`,
    `gatsby-transformer-yaml`,
    'gatsby-transformer-sharp',
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content/`,
      },
    },
    {
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: [
          `gatsby-remark-external-links`,
          {
            resolve: 'my-gatsby-remark-images',
            options: { maxWidth: 800, addCaptions: true },
          },
          'gatsby-remark-copy-linked-files',
          'my-gatsby-remark-youtube',
          // This has to come after the youtube plugin
          'gatsby-remark-responsive-iframe',
          'gatsby-remark-autolink-headers',
        ],
      },
    },
    {
      resolve: 'gatsby-plugin-google-analytics',
      options: {
        trackingId: 'UA-xxxxxxxxx-x',
      },
    },
  ],
}
```

`package.json`:

```json
{
  "scripts": {
    "build": "gatsby build",
    "start": "gatsby develop"
  },
  "dependencies": {
    "color": "^2.0.1",
    "gatsby": "^1.9.99",
    "gatsby-image": "^1.0.33",
    "gatsby-link": "^1.6.24",
    "gatsby-plugin-catch-links": "^1.0.14",
    "gatsby-plugin-google-analytics": "^1.0.15",
    "gatsby-plugin-react-helmet": "^1.0.8",
    "gatsby-plugin-react-next": "^1.0.4",
    "gatsby-plugin-resolve-src": "^1.0.0",
    "gatsby-plugin-styled-components": "^2.0.4",
    "gatsby-remark-autolink-headers": "^1.4.11",
    "gatsby-remark-copy-linked-files": "^1.5.25",
    "gatsby-remark-external-links": "^0.0.4",
    "gatsby-remark-images": "^1.5.36",
    "gatsby-remark-responsive-iframe": "^1.4.16",
    "gatsby-source-filesystem": "^1.5.8",
    "gatsby-transformer-remark": "^1.7.28",
    "gatsby-transformer-sharp": "^1.6.16",
    "gatsby-transformer-yaml": "^1.5.11",
    "knuth-shuffle": "^1.0.8",
    "prop-types": "^15.6.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-helmet": "^5.2.0",
    "react-icons": "^2.2.7",
    "react-ink": "^6.2.0",
    "react-side-effect": "^1.1.3",
    "react-transition-group": "^2.2.1",
    "styled-components": "2.2.0",
    "unist-util-select": "^1.5.0",
    "unist-util-visit": "^1.3.0"
  },
  "devDependencies": {}
}

```

`gatsby-node.js`:

```js
const createStoryPages = require('./src/server/createStoryPages');

exports.createPages = async props => {
  await createStoryPages(props);
};
```

### Actual result

```
...
Executing user command: gatsby build
success delete html files from previous builds — 0.050 s
success open and validate gatsby-config.js — 0.009 s
success copy gatsby files — 0.039 s
success onPreBootstrap — 0.009 s
success source and transform nodes — 0.779 s
success building schema — 0.444 s
success createLayouts — 0.016 s
success createPages — 0.052 s
success createPagesStatefully — 0.022 s
success onPreExtractQueries — 0.003 s
success update schema — 0.212 s
success extract queries from components — 0.252 s
success run graphql queries — 6.011 s
success write out page data — 0.004 s
success write out redirect data — 0.001 s
info bootstrap finished - 226.22 s
success onPostBootstrap — 0.001 s
success Building CSS — 6.031 s
success Building production JavaScript bundles — 14.493 s
error Building static HTML for pages failed
See our docs page on debugging HTML builds for help https://goo.gl/yL9lND
  135 |           path={node.frontmatter.path}
  136 |           title={node.frontmatter.title}
> 137 |           image={node.frontmatter.image.childImageSharp.sizes}
      |                                         ^
  138 |           description={node.frontmatter.description}
  139 |         />
  140 |       ))}

  WebpackError: Cannot read property 'childImageSharp' of null

  - portfolio.js:137 
    src/pages/portfolio.js:137:41
  

  - portfolio.js:132 Portfolio
    src/pages/portfolio.js:132:43
  
  - react-dom-server.node.production.min.js:31 za
    ~/react-dom/cjs/react-dom-server.node.production.min.js:31:388
  
  - react-dom-server.node.production.min.js:36 a.render
    ~/react-dom/cjs/react-dom-server.node.production.min.js:36:16
  
  - react-dom-server.node.production.min.js:35 a.read
    ~/react-dom/cjs/react-dom-server.node.production.min.js:35:208
  
  - react-dom-server.node.production.min.js:44 renderToString
    ~/react-dom/cjs/react-dom-server.node.production.min.js:44:1
  
  - gatsby-ssr.js:26 Object.exports.replaceRenderer
    ~/gatsby-plugin-styled-components/gatsby-ssr.js:26:1
  
  - api-runner-ssr.js:29 
    .cache/api-runner-ssr.js:29:41
```

The page/component being referenced here is [this one](https://github.com/lourd/descioli-design/blob/master/src/pages/portfolio.js)

### Expected behavior

A successful build.

### Steps to reproduce

You can clone [the repo](https://github.com/lourd/descioli-design) and try building it for yourself if you want, but it passes every time locally for me. I've also downloaded Netlify's [build image](https://github.com/netlify/build-image), built the container, and tried my build within that on my local machine -- also passes.

**Comment by pieh** [comment]
If your build work locally then you propably to commit your some of your image files to your repository

**Comment by lourd** [comment]
@pieh, you brilliant, helpful man 😄

Turns out it was due to a file type capitalization mismatch — `.PNG` vs `.png`. I changed it in VSCode and it showed it as lowercase, but it didn't actually change it in the filesystem, so it never got changed in git. Freshly cloning the repo still had it as uppercase.

The `diff` command ended up being helpful for this:

```sh
diff --brief -r ./clone/content/ ./descioli-design/content/
Only in ./clone/content/stories/sidekicks: screenshot.PNG
Only in ./descioli-design/content/stories/sidekicks: screenshot.png
```

**Comment by ghardin137** [comment]
I know i'm a bit late here, but you should also be checking your objects prior to using a deeply nested value.  You'd likely have a successful build, without an image on a single page.

**Comment by lourd** [comment]
Hey Greg, thanks for the suggestion.

I think that would be defeating the main benefit of GraphQL — having a clear contract for the data I'm receiving. If my query starts returning data with unexpected null values, then I want my build to fail. I think having my site in an undetermined state, where an image is missing without any warning, is worse.

I definitely appreciated Netlify's ability to override the automated deploy from GitHub by just uploading a folder on their site while this hasn't been working for the past week 😅
