### ISSUE TITLE
Plugin loader can't parse local ES6 files

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#4037]
I'm still pulling on this thread that leads to #3889, and I think this is the cause of the [bug mentioned here](https://github.com/gatsbyjs/gatsby/pull/3889#issuecomment-364204661).

[This function](https://github.com/gatsbyjs/gatsby/blob/3c1cae921cc5804707902356b9ba35b79302ac69/packages/gatsby/src/bootstrap/load-plugins.js#L17-L29) attempts to resolve a site's plugins, which is generally 👍.

However, the _current_ site's `gatsby-node.js`, `gatsby-ssr.js` and `gatsby-browser.js` files could have things like `import` statements in them. Which will cause `resolvePluginModule`'s `require()` checks to fail (when they should pass), leaving us with an inaccurate list of which plugins implement which APIs.

That in turn means that the later checks for things like bad API exports and duplicated API exports won't work correctly.

@KyleAMathews (or anyone else 😄) do you have any thoughts on how to handle this?

**Comment by jquense** [comment]
I'm not sure if it's intended that node files should be transpiled? My instinct is that the current behavior is good, You wouldn't really want `gatsby-node.js` run against the same set of transforms as the browser files anyway...

**Comment by KyleAMathews** [comment]
>However, the current site's gatsby-node.js, gatsby-ssr.js and gatsby-browser.js files could have things like import statements in them. Which will cause resolvePluginModule's require() checks to fail

Hmm yeah — people shouldn't be using import in `gatsby-node.js` in general. import/export in Node is still a huge mess and we should warn people against that. And yeah, the others can't often be imported into node due to webpack-specific requires. This reminds me now why I didn't add exports checking back in the day for browser/ssr APIs :-D

Perhaps instead we just read in plugin's files and use regex to check for `exports.${API_NAME}`? Or use babel & check the AST?

**Comment by jquense** [comment]
what is the check for? Isn't this about requiring the file? It seems like it's gonna be requires at some point right might as well fail early, maybe wrap the SyntaxError with a helpful gatsby not aobut how this file isn't compiled?

**Comment by KyleAMathews** [comment]
@jquense @m-allanson has been working on adding a warning for when multiple plugins implement `replaceRenderer` — which will then silently break things because Gatsby can only use one implementation of `replaceRenderer` during SSR https://github.com/gatsbyjs/gatsby/pull/3889

**Comment by jquense** [comment]
ah ok sorry, missing context :) 👍
