### ISSUE TITLE
Breaking webpack config change introduced in 1.9.162

### ISSUE THREAD

**Issue by robwierzbowski** [gatsbyjs/gatsby#4044]
## Description

Previously, Gatsby users were able to override loader `exclude`s by specifying their own regex in gatsby-node.js. Example:

```
config.loader('js', {
  exclude: [/(node_modules(?!(\/some-package))|bower_components)/]
});
```

In https://github.com/gatsbyjs/gatsby/pull/3611/commits/50b0a47b20ae4a5e07b3b9bc9f4b87cc3bb509d1, which was released in [1.9.162](https://github.com/gatsbyjs/gatsby/commit/cc468b029819ce2279e47f5d75f3ded9d0f07a1c), `exclude` values in the Gatsby webpack.config.js were wrapped in an array. 

If my co-worker and I are reading the source of [webpack-configurator](https://github.com/lewie9021/webpack-configurator) correctly, overrides to `exclude` will now be concatenated, where before they were replaced.

The most commonly documented method of excluding all but one node_module is a regex that excludes a package with a negative lookahead, like the code sample above. But since `/node_modules/` is excluded in the base configuration, and Webpack `exclude`s within an array are cumulative, that won't work anymore.

The author of https://github.com/gatsbyjs/gatsby/pull/3611/commits/50b0a47b20ae4a5e07b3b9bc9f4b87cc3bb509d1 didn't run into this problem because they were adding additional excludes, not attempting to reduce the scope of existing excludes.

### Environment

Gatsby version: 1.9.162+
Node.js version: Any
Operating System: Mac 

### Expected behavior

There should be a documented method for overriding loader configuration in arrays, specifically `exclude`. 

A patch update doesn't introduce breaking changes 🙂.

It would be pleasant if Gatsby used a more widely used/understood/updated method of merging webpack configs like [webpack-merge](https://www.npmjs.com/package/webpack-merge) (used by the Vue team).

**Comment by bytheway875** [comment]
Confirmed that this can be "fixed" in the short term by implementing something like the poster of this issue did:

https://github.com/gatsbyjs/gatsby/issues/3052

But this requires recreating the program variable, loading in the babelConfig, and wrapping the config stuff in a promise, removing the defaultloader, and then adding customconfig.

------
In my opinion, reverting the exclude to be a string that must be completely overwritten is the best short-term course of action in order to replicate the expected behavior as documented in the Gatsby docs.

**Comment by tech4him1** [comment]
The related PR to that commit is https://github.com/gatsbyjs/gatsby/pull/3611.

**Comment by erquhart** [comment]
@robwierzbowski passing config as a function or using a resolver function doesn't allow replacement?

**Comment by erquhart** [comment]
I should have prefaced my comment with: this was totally a breaking change and I overlooked use cases where that would be true, apologies for that. In light of the break, I believe reverting is the only proper course. I'll open a PR to do that now.
