### ISSUE TITLE
Update Netlify CMS plugin to replace webpack loader exclusions

### ISSUE THREAD

**Issue by erquhart** [gatsbyjs/gatsby#4047]
#4046 will revert the changes introduced in #3611. The purposes of the commit being reverted as mentioned in the PR:

> * uses arrays when defining webpack loader.exclude so that exclusions may be added by plugins
> * adds node_modules/netlify-cms to css loader exclusions (build-javascript stage)

Since the exclusions will go back to being strings, we should be able to address this by passing a function to the webpack-configurator [`loader`](https://github.com/lewie9021/webpack-configurator#configloaderkey-config-resolver) method to replace the string with an array and achieve the same result.

@KyleAMathews you can consider this assigned to me.

**Comment by KyleAMathews** [comment]
👍

**Comment by KyleAMathews** [comment]
Added you as a collaborator so you can assign stuff to yourself directly :-)
