### ISSUE TITLE
Use config.plugin() in webpack.config.js so easy to override webpack plugins in a site

### ISSUE THREAD

**Issue by renatorib** [gatsbyjs/gatsby#405]
Why plugins are not used with webpack-configurator? 
https://github.com/lewie9021/webpack-configurator#configpluginkey-constructor-parameters

Thus I thought it would be easier if you need to remove a plugin. `config.removePlugin('key')`

**Comment by KyleAMathews** [comment]
It could... I don't remember for sure why that wasn't added (I didn't do the initial PR to add support for webpack-configurator) but this could sense to add in when we add a plugin system to Gatsby (soonish).

How would you group things if we were using webpack-configurator plugins?

**Comment by renatorib** [comment]
Well, It's about replace core plugins.

On your core, can have something like this:
```js
config.plugin('extract-css', ExtractTextPlugin, ['styles.css'])
```

It's give me more flexibility if I want to replace it:
```js
config.removePlugin('extract-css');
config.plugin('extract-css', ExtractTextPlugin, ['my-awesome-styles.css']);
```

**Comment by brandonmp** [comment]
it looks like the docs reflect the ability to use `configurator` to add/remove/mod webpack plugins. is this implemented yet? it looks like it in the `src`, but the `webpack-configurator` docs call for replacing plugins by `key name`, and as far as i can tell, none of the `plugins` in the `gatsby webpack config` have key names. 

I'd like to set some specific `uglifyJS` options, as well as add some `globals` in `DefinePlugin()`. Is this possible to do in current build?

**Comment by KyleAMathews** [comment]
@brandonmp hmmm... you're right — for loaders we use keys but for whatever reason plugins didn't get converted over. Would love it if you created a PR to convert the plugins to use keys! Also, if you think your uglifyjs options are of general use, we could make them the default.

**Comment by brandonmp** [comment]
this is what I use in a few other projects. if anyone wants to opine would love to hear other opinions

```
webpack.optimize.UglifyJsPlugin({
      comments: false, // drop comments, except copyrights i think
      compress: {
        unused: true, // drop unref'd vars/funcs
        dead_code: true, // drop unreachable code
        warnings: false, // silent dead code elimination
        drop_console: true // drop console.* calls
      }
    })

```

**Comment by KyleAMathews** [comment]
Here's an article https://davidwalsh.name/compress-uglify

I'm not well-versed in uglify options so would appreciate others weighing in.

**Comment by KyleAMathews** [comment]
@brandonmp what would be great is if you could build one (or several of the starters) with the current uglify setup and then with your settings and report back on the outputted JS bundle size. Would love to see improvements here!

**Comment by brandonmp** [comment]
that's a great idea. i'm a 1-person dev shop atm but if it's still incomplete when i get some time i'm happy to conduct a little experiment.

**Comment by jbolda** [comment]
Merged PR took care of the issue. Closing.
