### ISSUE TITLE
[docs] Add example showing how to modify JS Babel loader

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#4053]
…to https://www.gatsbyjs.org/docs/add-custom-webpack-config/
Refs. #3052 and https://github.com/gatsbyjs/gatsby/issues/3052#issuecomment-347652689

**Comment by tulikavijay** [comment]
I would like to help on this!

**Comment by fk** [comment]
That's great @tulikavijay, thanks for helping out!

**Comment by tulikavijay** [comment]
Am i supposed to add this bit of code [#3052](https://github.com/gatsbyjs/gatsby/issues/3052#issuecomment-347550506) in the example?

**Comment by calpa** [comment]
Any progress on this issue?

**Comment by tulikavijay** [comment]
I am going to submit a PR soon...

**Comment by m-allanson** [comment]
Done in #4390, thanks @tulikavijay!
