### ISSUE TITLE
hello I would like to contribute to your project by serving as a translator to Spanish which is my native language I can translate the file README and CONTRUBUTING since I have to translate a thousand words or more

### ISSUE THREAD

**Issue by LuigiBaute** [gatsbyjs/gatsby#4065]
## Description

Describe the issue or the enhancement that you want to see.

### Environment

Gatsby version:
Node.js version:
Operating System:

### File contents (if changed):

`gatsby-config.js`: 
`package.json`: 
`gatsby-node.js`: 
`gatsby-browser.js`: 
`gatsby-ssr.js`: 

### Actual result

What happened.

### Expected behavior

What should happen?

### Steps to reproduce

1\.

2\.

3\.

...

**Comment by fpoumian** [comment]
I'd also be happy to help translate any material to Spanish if needed.

**Comment by m-allanson** [comment]
Great! Maybe the best thing to do is create a new repo with the translated README and CONTRIBUTING files in it, then we can link to them from here?

**Comment by LuigiBaute** [comment]
ok i'll start working on it.

**Comment by LuigiBaute** [comment]
I'd like to discuss a few terms I saw to be able to give you the best translation, and not just my interpretation of what it means.
per example:
Titles in _italics_ on gatsbyjs are [STUBS] and need contributions
(The word stubs doesn't mean the same in spanish, I'd like to know what other word could I use)

[Triaging] GitHub issues --
The world triaging could be use as urgency? I'd like to get suggestions on this one too.

**Comment by LuigiBaute** [comment]
When you talk about a website ''dependencies'' it means its configurations?
