### ISSUE TITLE
Uncaught TypeError: t.replace is not a function (A page wasn't found for "[object Object]")

### ISSUE THREAD

**Issue by fpoumian** [gatsbyjs/gatsby#4067]
## Description

I'm getting the following browser error on a production site generated by Gatsby.

```
A page wasn't found for "[object Object]"  loader.js:136 
Uncaught TypeError: t.replace is not a function
    at T (loader.js:144)
    at Object.getResourcesForPathname (loader.js:318)
    at o (production-app.js:85)
    at Object.onClick (index.js:204)
    at r.handleClick (Link.js:50)
    at Object.l (react-dom.production.min.js:26)
    at Object.invokeGuardedCallback (react-dom.production.min.js:25)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.production.min.js:25)
    at h (react-dom.production.min.js:30)
    at m (react-dom.production.min.js:32)
react-dom.production.min.js:27 
```

The error doesn't show up when the page first loads, but it does whenever I click on any of the internal links (all of which use Gatsby Link). This in turn causes the site to react way slower when navigating the site. Oddly enough I don't have this problem during development (the Links work as intended there), but only in the production site itself.

I have worked in a couple of Gatsby sites already and never had this problem before, so I have no idea what I'm doing wrong this time. 

### Environment

Gatsby version: 1.9.158
Node.js version: 8.9.3
Operating System: Ubuntu 16.04

### Actual result

Whenever I click on any of the links the previously described error pops up and the site takes way longer to load the new page. 

### Expected behavior

The site should navigate to the linked route quickly and without any errors (just as it does in the development site.)

...

**Comment by m-allanson** [comment]
Can you recreate the issue on a local build of the site? e.g. if you do `gatsby build` and then `gatsby serve`.

**Comment by fpoumian** [comment]
Hi @m-allanson ,
Yes, unfortunately, I'm having the exact same issue with a local build. I have also tried disabling some Gatsby plugins which I hadn't used on other sites before, but the result is always the same. Any idea of what the underlying problem might be?

**Comment by m-allanson** [comment]
Hmm. As a baseline try deleting your `node_modules`, `.cache` and `public` directories, then reinstall and rebuild.

Your error is coming from [`loader.js`](https://github.com/gatsbyjs/gatsby/blob/2ce6c5ce3ea0431384f2a3115f7f4a47eaeeb5b8/packages/gatsby/cache-dir/loader.js#L318), if you're comfortable digging in to the code you could [set up `gatsby-dev-cli`](https://www.gatsbyjs.org/docs/how-to-contribute/#contributing-to-the-repo) and have a look around at what that `[object Object]` is.

Alternatively if you can post an example repo I can have a look?

**Comment by KyleAMathews** [comment]
I wonder if it's related to this? https://github.com/gatsbyjs/gatsby/pull/3407

**Comment by janjarfalk** [comment]
I had the same issue but it resolved when I updated from Gatsby 1.9.102 to 1.9.203.

**Comment by ChrisSki** [comment]
I'm currently getting this issue only in production. Not when I build and serve locally. I have deleted my node_modules, .cache and public folders. 

Gatsby: 1.9.238
Node: 8.9.1
MacOS: 10.13.3

**Comment by ChrisSki** [comment]
@fpoumian did you find a fix for this?

**Comment by altayaydemir** [comment]
Hey guys, it seems like a **gatsby-link** related issue. We were using 1.6.34, upgraded to 1.6.39 and encountered with this problem. Downgrading to 1.6.34 resolved.

I think there's an argument mismatch on the function chain triggered by react-router -> gatsby-link -> loader.js

**Comment by ChrisSki** [comment]
@altayaydemir This didn't seem to work for me. Here's my `package.json`. Please let me know if you see any other issues. This is keeping me from pushing anything to prod.

```
{
  "dependencies": {
    "babel-plugin-lodash": "^3.3.2",
    "emotion": "^9.1.0",
    "emotion-server": "^9.1.0",
    "gatsby": "^1.9.241",
    "gatsby-cli": "^1.1.48",
    "gatsby-link": "^1.6.34",
    "gatsby-plugin-catch-links": "^1.0.19",
    "gatsby-plugin-emotion": "^1.1.16",
    "gatsby-plugin-feed": "^1.3.20",
    "gatsby-plugin-google-analytics": "^1.0.24",
    "gatsby-plugin-lodash": "^1.0.11",
    "gatsby-plugin-manifest": "^1.0.15",
    "gatsby-plugin-nprogress": "^1.0.14",
    "gatsby-plugin-offline": "^1.0.15",
    "gatsby-plugin-react-helmet": "^2.0.8",
    "gatsby-plugin-sharp": "^1.6.41",
    "gatsby-plugin-sitemap": "^1.2.20",
    "gatsby-plugin-twitter": "^1.0.20",
    "gatsby-plugin-typography": "^1.7.18",
    "gatsby-remark-autolink-headers": "^1.4.13",
    "gatsby-remark-copy-linked-files": "^1.5.30",
    "gatsby-remark-images": "^1.5.59",
    "gatsby-remark-prismjs": "^1.2.21",
    "gatsby-remark-responsive-iframe": "^1.4.18",
    "gatsby-source-contentful": "^1.3.44",
    "gatsby-source-filesystem": "^1.5.27",
    "gatsby-transformer-remark": "1.7.37",
    "grid-emotion": "^3.2.0",
    "hidden-styled": "^1.0.0-0",
    "lodash": "^4.17.5",
    "lodash-webpack-plugin": "^0.11.4",
    "npm-check-updates": "^2.14.1",
    "react": "^16.2.0",
    "react-disqus-comments": "^1.1.1",
    "react-dom": "^16.2.0",
    "react-emotion": "^9.1.0",
    "react-helmet": "^5.2.0",
    "react-share": "^2.0.0",
    "react-twitter-widgets": "^1.7.1"
  },
  "devDependencies": {
    "babel-plugin-emotion": "^9.1.0",
    "cli-glob": "^0.1.0",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-config-prettier": "^2.9.0",
    "eslint-plugin-import": "^2.9.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.7.0",
    "gh-pages": "^1.1.0",
    "prettier": "^1.11.1",
    "remark-cli": "^5.0.0",
    "remark-preset-lint-recommended": "^3.0.1",
    "stylefmt": "^6.0.0",
    "stylelint": "^9.1.3",
    "stylelint-config-standard": "^18.2.0",
    "write-good": "^0.11.3"
  }
```

**Comment by sean6bucks** [comment]
@KyleAMathews Looks like the update to allow an object for "to" prop in https://github.com/gatsbyjs/gatsby/pull/3407 correctly updated the production only block on Line 142 to only send the path/pathname
https://github.com/nsimonson/gatsby/commit/d458fe72e35951c951d699e62cf311652fb952a8#diff-f0712f4b9f6079d8d9ba1ea7fa2c95d5L142 

But was then reverted back to passing the whole state with this update for adding to history https://github.com/gatsbyjs/gatsby/pull/3802 

https://github.com/gatsbyjs/gatsby/pull/3802/files#diff-f0712f4b9f6079d8d9ba1ea7fa2c95d5L160

which seems to be what is causing the loader.js to throw this log error only in built versions

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by daudtribakti** [comment]
ikeh kimochi

**Comment by daudtribakti** [comment]
eerer
