### ISSUE TITLE
[v2] outstanding small issues 

### ISSUE THREAD

**Issue by jquense** [gatsbyjs/gatsby#4069]
Just documenting stuff as i'm noticing it and trying to get stuff working so I don't forget.

- `babelrc.js` support isn't right
  - gatsby mutates the babelrc, which isn't a problem for json, but a big deal for `.js` since the plugins keep getting added over time (need to clone it)
  - Something weird is happening with 'cacheDirectory' i think related to the mutation

**Comment by KyleAMathews** [comment]
Anything that needs addressed here still @jquense? We've done a lot of work on babelrc + have issues for remaining work. Do remember what the `cacheDirectory` issue was?

**Comment by jquense** [comment]
I think we got this all addressed with the reduxification of the babel config :)
