### ISSUE TITLE
Convert panic (and any console.log) errors to `panicOnBuild` if the error should stop a build from succeeding

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#4070]
/cc @jquense

**Comment by anjawaldbauer** [comment]
@KyleAMathews Is my understanding correct that you want Gatsby v2 to stop a build on any error or warning? This is exactly what I would want. I would love to help implement this, if you could give a little bit of guidance. I would also very much appreciate if you could explain how to do implement this behavior in Gatsby v1 as an opt-in. Thank you in advance!

**Comment by m-allanson** [comment]
@anjawaldbauer This has been implemented in v2 as a [`panicOnBuild` method of the reporter](https://github.com/gatsbyjs/gatsby/blob/v2/packages/gatsby-cli/src/reporter/index.js#L30). I don't think there are any plans to backport it to v1, as that effort could be spent getting v2 out more quickly :)

**Comment by KyleAMathews** [comment]
Yeah, let's close this. It won't be back-ported. There's still work to sort out which errors/warnings should use this but that can be an on-going project.
