### ISSUE TITLE
[www] gatsby develop error

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#4093]
## Description

Editing a markdown file can cause the site to error while `gatsby develop` is running.

### Environment

Gatsby version: from `master`
Node.js version: 9.5.0
Operating System: macOS

### File contents (if changed):

see https://github.com/gatsbyjs/gatsby/tree/c246262d10830eda09135ff5f8a3ee64883757ce/www

### Actual result

Page displays an error:

<img width="653" alt="screen shot 2018-02-16 at 21 58 05" src="https://user-images.githubusercontent.com/381801/36331445-be1acc48-1365-11e8-9810-6313cb663045.png">

### Expected behavior

Page should not display an error 😄 

### Steps to reproduce
- in this repo, `cd www`
- `rm -r .cache`
- `yarn run develop`
- browse to http://localhost:8000/docs/graphql-reference/
- edit and save `docs/docs/graphql-reference.md`
- wait for auto-page reload (or refresh the browser)
- There will be an error `TypeError: Cannot read property 'markdownRemark' of undefined`, which will remain until deleting the `.cache` directory

I've been able to recreate this with various docs pages and blog posts - all markdown files. Maybe the query data isn't being retrieved from the cache properly?

This query will still work in graphiql:

```
{    
  markdownRemark(fields: { slug: { eq: "/docs/querying-with-graphql/" } }) {
      html
      excerpt
      timeToRead
      fields {
        slug
        anchor
      }
      frontmatter {
        title
      }
      
    }
}
```

**Comment by fk** [comment]
Saw this too just now.

**Comment by m-allanson** [comment]
I wonder if this is similar to the issue that @peduarte was seeing earlier today?

**Comment by peduarte** [comment]
Nope, actually my issue was me being stupid and using mutable array methods on `props.data` 😒🔫

**Comment by davidvenin** [comment]
I got the same issue. If I had link in .md, browser throw me the exact same error.

**Comment by gurtjun** [comment]
Same issue here, every time I edit a markdown file.

**Comment by peduarte** [comment]
but yeah this issue happens to me, when I edit a markdown file. but not ALL the time.

**Comment by patrickodacre** [comment]
I'm seeing this issue, too. Bare bones Gatsby install. Just added transformer remark. Most edits to my .md file break the develop build and I have to restart the server to get it working again.

**Comment by KyleAMathews** [comment]
This should have fixed the bug, thanks for your patience!

https://github.com/gatsbyjs/gatsby/pull/4213/files/cb52bc81b85f466e846da528bc0ec9b0eead9ec4#diff-a45448af33cc109010d5aab8911336dd
