### ISSUE TITLE
[gatsby-transformer-javascript-frontmatter] Only create nodes from files that actually export frontmatter

### ISSUE THREAD

**Issue by cwgw** [gatsbyjs/gatsby#4095]
Since we've switched from [gatsby-transformer-javascript-static-exports] to [gatsby-transformer-javascript-frontmatter], and limited the focus of the plugin to frontmatter in javascript files (as described by @jbolda in [#3795](https://github.com/gatsbyjs/gatsby/issues/3795#issuecomment-362829915)), I'd like to suggest that the plugin only create nodes from javascript files that actually export frontmatter.

Right now, the plugin seems to create a `javascriptFrontmatter` node for each file with a media type of `application/javascript` before actually checking for the existence of `exports.frontmatter`. This can produce a lot of false positives, resulting in queries like…

```
{
  allJavascriptFrontmatter (
    filter: {frontmatter: {title: {ne: null}}}
  ) {
    edges {
      node {
        frontmatter {
          ...
        }
      }
    }
  }
}
```

Filtering in this way is not really a big deal, but it seems silly to have to explicitly exclude nodes that don't have frontmatter when you're querying for nodes that have frontmatter.

I don't think I'm capable of offering a PR. If there's some other way I can help, or if there's a use case for the current behavior that I'm missing, please let me know.

Thanks.

**Comment by KyleAMathews** [comment]
Great idea!

You might very well be able to create a PR though :-) It'd just be adding an `if` check on the result of looking of looking for frontmatter.

**Comment by cwgw** [comment]
Well, okay. I'll give it a shot. I appreciate the confidence.

**Comment by jbolda** [comment]
Makes sense to me 👍

Thanks for the initiative!
