### ISSUE TITLE
Consider auto-injecting .env.* variables into the node.js process like we do in the browser environment

### ISSUE THREAD

**Issue by gantzy** [gatsbyjs/gatsby#4099]
First contribution to an open source project so my apologies if this isn't in the proper format.

## Description

When using gatsby-node.js to createPage with templates using a graphql queries, the queries will fail if process.env is referenced from the .env.* files. If you hard code the variables instead, the graphql queries will execute.

For reference, I was generating a way to build out pagination for my site. When introducing environment variables to the project, the graphql queries started throwing warnings and wouldn't build the pages. Replace the env vars with hardcoded variables, they go away and the pages are generated

`gatsby-node.js`:
```
const pages = process.env.POSTS_PER_TOPIC;

exports.createPages = ({ boundActionCreators, graphql }) => {
  const { createPage } = boundActionCreators;

  return graphql(`
    {
      allMarkdownRemark(
        sort: { order: DESC, fields: [frontmatter___date] }
        limit: 1000
      ) {
        edges {
          ... (basic frontmatter query)
        }
      }
    }
  `).then(result => {
   //some logic determining landingPages
   _.each(landingPages, (numArticles, page) => {
      const categoryTemplate = path.resolve(`src/templates/category-page.js`);
      const maxPages = Math.ceil(numArticles / pages);

      for (let i = 1; i <= maxPages; i++) {
        const route = i === 0 ?
          `/${page}` :
          `/${page}/${i + 1}` ;

        createPage({
          path: route,
          component: categoryTemplate,
          context: {
            category: page,
            baseRoute: `/${page}`,
            maxPages,
            limit: pages,
            currentPage: i,
            offset: i === 1 ? 0 : (i - 1) * pages
          }
        });
      }
    });
  });
}):
```

### Environment

Gatsby version: 1.9.201
Node.js version: 8.9.1
Operating System: MacOSX High Sierra

### Actual result

GraphQL Queries on templates fail during createPage

### Expected behavior

GraphQL Queries should generate the proper pages

### Steps to reproduce

1\. Generate a createPages function in gatsby-node.js that uses a template with graphql query

2\. Attach an environment variable via `.env.development` || `.env.production`

3\. `npm run develop` will throw warnings about pages not being generated for that template

**Comment by nickmccurdy** [comment]
I believe this is intentional:

> To add environment variables for the JavaScript run in node.js, e.g. in
> `gatsby-config.js` or `gatsby-node.js`, you can add environment variables the
> normal ways e.g. when calling gatsby on the command line or by adding
> environment variables through your hosting/build tool.
> 
> If you want to access variables in `.env.*` files in your node.js code, use the
> NPM package [dotenv](https://www.npmjs.com/package/dotenv). Install the package and 
> require it in your `gatsby-config.js` or `gatsby-node.js` the following way on top of your file:
> 
> ```
> require('dotenv').config({
>   path: `.env.${process.env.NODE_ENV}`
> });
> ```
> 
> Now the variables are available.

https://www.gatsbyjs.org/docs/environment-variables/

**Comment by gantzy** [comment]
Yes I've used environment variables before in a gatsby project. I may have stated my issue poorly. Basically, not using the environment variables lets me use createPages in the gatsby-node.js file via a template that uses a graphql query for data. The instant I start referencing `process.env.{insert_env_var_here}`, gatsby will start throwing warnings and skip creating those pages.

Seems odd to me that referencing an environment variable would be the difference between being able to use GraphQL query in a template file.

**Comment by nickmccurdy** [comment]
The body of your for loop never runs because the environment variable is missing.

```js
// pages is undefined
const pages = process.env.POSTS_PER_TOPIC

// dividing by undefined produces NaN, and ceil also returns NaN
const maxPages = Math.ceil(numArticles / pages)

// 1 <= NaN is false so the for loop does not run
for (let i = 1; i <= maxPages; i++) {
```

**Comment by gantzy** [comment]
Appreciate the help, even if it ended up being a duh moment. That's what i get for staying up too late. Closing issue.

Maybe food for thought, even though its in the docs, it might be a good QoL change to auto check if those files exist, especially since they are specified in the docs. In reality those files could be whatever you wanted. But I imagine its just to reduce bloat and only an if necessary sort of thing.

Anyways, thanks again.

**Comment by KyleAMathews** [comment]
Auto check if which files exist? We're always interested in new checks :-)

**Comment by gantzy** [comment]
@KyleAMathews The .env.development, .env.production files. They seem to inject automatically for React/Webpack using the GATSBY_* flag. But are ignored completely, as far as i can tell, with regards to the node scripts without the use of dotenv.

Even though its specified in the docs thats how you have to do it, its a wierd user experience to have some things magically work and some things in the same files not work as you might expect.

Side note, initially I read the docs as though the .env.production/development files were automatically injected everywhere but for .env.* (meaning anything else like .env.qa) required the dotenv snippet. I had used the GATSBY_* flag in another project and that worked without question.

**Comment by KyleAMathews** [comment]
Ah, so you're suggesting that we could setup dotenv for you in gatsby-node.js and gatsby-config.js?

**Comment by gantzy** [comment]
Essentially. It’s more of a user experience thing than anything else since
certain vars get auto injected but not all vars.

**Comment by KyleAMathews** [comment]
Yeah, this makes sense. Let's see if anyone else has thoughts on it. I think I'd support a PR adding this.

**Comment by nickmccurdy** [comment]
I'm 👍 for including dotenv in Gatsby scripts. 😄 Would feel more consistent and convenient.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
