### ISSUE TITLE
Migrate hot-loader to react-transform's family of modules

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#41]
https://github.com/gaearon/react-transform-boilerplate

**Comment by MoOx** [comment]
Maybe that can help https://github.com/MoOx/statinamic/commit/b19974e73a9dfb4f759f80127bafe964423e2d6e :)

**Comment by jeberly** [comment]
Any news on getting the transform merged in?  Thanks!

**Comment by KyleAMathews** [comment]
Done in 0.8
