### ISSUE TITLE
Gatsby fails on build

### ISSUE THREAD

**Issue by renatorib** [gatsbyjs/gatsby#410]
I investigated a bit but could not figure out

```
→ gatsby --version
0.12.5
```

```
→ gatsby build
Generating CSS
Generating Static HTML
Failed at generating HTML

/home/renato/Projects/landing/node_modules/gatsby/dist/bin/cli.js:52
      throw err;
      ^
Error: TypeError: enquire.register is not a function
    at ResponsiveMixin.media (render-page.js:67576:14)
    at render-page.js:66057:16
    at Array.forEach (native)
    at componentWillMount (render-page.js:66050:20)
    at ReactCompositeComponentMixin.performInitialMount (render-page.js:14106:13)
    at ReactCompositeComponentMixin.mountComponent (render-page.js:14009:22)
    at Object.ReactReconciler.mountComponent (render-page.js:6851:36)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (render-page.js:12980:45)
    at ReactDOMComponent.Mixin._createContentMarkup (render-page.js:9973:33)
    at ReactDOMComponent.Mixin.mountComponent (render-page.js:9840:30)
```

**Comment by KyleAMathews** [comment]
The problem is that ResponsiveMixin has a "dom check" https://github.com/akiran/react-responsive-mixin/blob/master/index.js#L2 that means it's not loading enquire.js when server rendering which is why `enquire.register` is not a function.

You should file an issue with ResponsiveMixin to not try to register enquire if server rendering.

**Comment by renatorib** [comment]
Oh, dammit!
```
├─┬ react-slick@0.13.3
│ ├─┬ json2mq@0.2.0
│ │ └── string-convert@0.2.1
│ └─┬ react-responsive-mixin@0.3.5
│   ├── can-use-dom@0.1.0
│   └── enquire.js@2.1.1
```

Struck by the fact a dependency of a dependency breaks my build

And sorry for the issue, I thought it was something of Gatsby...

**Comment by KyleAMathews** [comment]
Haha no worries. Reminds me of this joke https://twitter.com/jckarter/status/762683017466744832

It should be an easy fix though for the mixin so hopefully you can get this working quickly.

**Comment by renatorib** [comment]
Hahahaha, thanks! I will try to do something :D

**Comment by ArchieHicklin** [comment]
Hi @renatorib - just running into the exact same issue! Did you manage to fix this in the end?

**Comment by renatorib** [comment]
@ArchieHicklin I've sent a PR to `react-responsive-mixin` https://github.com/akiran/react-responsive-mixin/pull/4
