### ISSUE TITLE
[gatsby-source-filesystem] Speed up initial scan of file system by first checking if files' last modified time is different before calculating a new contentDigest

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#4102]
Calculating the md5 hash of a file's contents is expensive. We can do a much faster initial check on subsequent runs by checking if the mtime of a file has changed since the last time Gatsby ran. If it hasn't, we can skip the more expensive md5 generation.

**Comment by m-allanson** [comment]
I just had a thought - should we start marking feature enhancements like this as 'after version 2'? In an attempt to keep v2 momentum going, and hopefully reduce those enourmous `master into v2` merges.

**Comment by KyleAMathews** [comment]
Yeah... good point. Or just tell people to land them on the v2 branch. The merges are rather painful (about to do another one...)

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
