### ISSUE TITLE
TypeError: Cannot read property 'frontmatter' of null

### ISSUE THREAD

**Issue by stefanwille** [gatsbyjs/gatsby#4103]
### Environment

Gatsby version: 1.9.158
Node.js version: 8.9.3
Operating System: MacOS X

### File contents (if changed):

`gatsby-config.js`:
      resolve: `gatsby-transformer-remark`,

`package.json`:

  "dependencies": {
    "gatsby": "^1.9.158",
    "gatsby-link": "^1.6.34",
    "gatsby-plugin-canonical-urls": "^1.0.12",
    "gatsby-plugin-react-helmet": "^2.0.3",
    "gatsby-plugin-sharp": "^1.6.27",
    "gatsby-remark-images": "^1.5.43",
    "gatsby-remark-prismjs": "^1.2.15",
    "gatsby-source-filesystem": "^1.5.16",
    "gatsby-transformer-remark": "^1.7.30",
  ...
}

`gatsby-node.js`: 
`gatsby-browser.js`: 
`gatsby-ssr.js`: 

### Actual result

I write my pages in Markdown. When I forgot the leading slash in the frontmatter's `path` property, like so:

```
path: about-me
```
then I see an error in the browser in `yarn develop`:

```
TypeError: Cannot read property 'frontmatter' of null
```

This error message is not helpful at all. It cost me lots of time. 

### Expected behavior

Gatsby should show a useful error message like 

```
path property in frontmatter of file XYZ must have a leading slash
```

### Steps to reproduce

1\.

2\.

3\.

...

**Comment by KyleAMathews** [comment]
I don't know why the lack of a leading slash would cause anything to fail. It's certainly not a requirement. Is your site public? Perhaps we could take a look at it? Sorry for the mysterious error!

**Comment by stefanwille** [comment]
My code is not public, but I will create new site and reproduce the issue there.

**Comment by jarodtaylor** [comment]
I'm having the same issue after following the [Creating a Blog with Gatsby tutorial](https://www.gatsbyjs.org/blog/2017-07-19-creating-a-blog-with-gatsby/).

**Comment by bernardinoalvarez** [comment]
Not sure if this will help any:

I ran into the same error today while building a site with @LeKoArts' [Gatsby Starter: Minimal Blog](https://github.com/LeKoArts/gatsby-starter-minimal-blog).

![screen shot 2018-03-11 at 11 51 53 am](https://user-images.githubusercontent.com/36980855/37279680-b140847c-25a8-11e8-8579-b0acee04cfd6.png)

<img width="1068" alt="screen shot 2018-03-12 at 1 28 28 am" src="https://user-images.githubusercontent.com/36980855/37279690-b989caee-25a8-11e8-9c01-4d53e341fc6d.png">

The solution that ended up working, per @LeKoArts, was deleting .cache and node_modules, and updating npm/yarn/node and reinstalling node_modules.

**Comment by gaearon** [comment]
I get this all the time working on React blog. It's pretty frustrating. To reproduce, clone `reactjs.org`, open a blog post and start editing it. Eventually you'll hit this.

**Comment by KyleAMathews** [comment]
It is a really obnoxious bug though :-\

**Comment by tatwater** [comment]
I just resolved this same issue by adding a leading `/` in the `path` of my latest post, after much struggle trying to decipher its meaning and finally landing on this thread! Just thought I'd throw my +1 in for this being a rather unhelpful error :)

**Comment by RedHoodJT1988** [comment]
I put the `/` in front of the path for my new post but it's not working. Here is my code for the file that it isn't liking:
```import React from 'react'
import Helmet from 'react-helmet'
import { graphql } from 'gatsby'

// import '../css/blog-post.css';

export default function Template({ data }) {
  const { markdownRemark: post } = data
  return (
    <div className="blog-post-container">
      <Helmet title={`Your Blog Name - ${post.frontmatter.title}`} />
      <div className="blog-post">
        <h1>{post.frontmatter.title}</h1>
        <div
          className="blog-post-content"
          dangerouslySetInnerHTML={{ __html: post.html }}
        />
      </div>
    </div>
  )
}

export const pageQuery = graphql`
  query BlogPostByPath($path: String!) {
    markdownRemark(frontmatter: { path: { eq: $path } }) {
      html
      frontmatter {
        date(formatString: "MMMM DD, YYYY")
        path
        title
      }
    }
  }
`
```

Any help on this would be really great.

**Comment by eLeontev** [comment]
looks like we can use workaround like preparing synthetic field which will match to asked path
```
let prefix = '/'

createNodeField({
  node,
  name: `syntheticPath`,
   value: `${prefix}${node.frontmatter.path}`, // lead custom filed to necessary structure to use math to it further
})
```

and in necessary template
```
export const pageQuery = graphql`
  query($path: String!) {
    markdownRemark(fields: { syntheticPath: { eq: $path } }) {
    // list of asked fields
    }
 }
`
```

**Comment by balamanoharb** [comment]
I'm using gatsby advanced starter and I got this error. If I compiled twice (exit and do gatsby develop again) this error goes away. But it works only for some time. If there is a permanent solution it would be good.

**Comment by neo01124** [comment]
I hit this issue today. 
I changed from `"gatsby": "^2.1.4"`  to `"gatsby": "^1.x",` and I don't have it anymore. Reading the comments here I can't understand why this works.

**Comment by javiersuzuki** [comment]
Thank you so much @stefanwille and @tatwater for your help!!! 

Adding that sneaky missing forward slash made it work!

**Comment by tomwilliamfranklin** [comment]
Bit of a avoiding the problem solution, but to fix this I contained the entire function and return statement in an if statement like: 
`if(frontmatter !== null) { }` 

and then put an else statement `else return null`, it seemed like it was trying to produce a blog post from a null markdown after producing the actual blog posts. Probably my dodgy code - but it builds

**Comment by pburtchaell** [comment]
> I just resolved this same issue by adding a leading `/` in the path of my latest post, after much struggle trying to decipher its meaning and finally landing on this thread! 
This was the solution for me as well. Wanted to signal boost this because it seems to be the solution on this thread that reliably works.

**Comment by andrewmartin** [comment]
First off, Gatsby is amazing.

Second, I'm having the same issue as everyone else here, but it's a bit strange. I am only seeing this issue on incremental or subsequent changes to a `md` file after I've initially built. It's pretty frustrating because if i want to live-edit a blog post, I have to make my edits and then manually run a restart.

```javascript
exports.onCreateNode = ({ node, getNode, actions }) => {
  const { createNodeField } = actions
  if (node.internal.type === `MarkdownRemark`) {
    const slug = createFilePath({ node, getNode })

    createNodeField({
      node,
      name: `slug`,
      value: slug,
    })
  }
}


exports.createPages = async ({ actions, graphql, reporter }) => {
  const { createPage } = actions
  const blogPostTemplate = path.resolve("src/templates/blog.tsx")
  const tagTemplate = path.resolve("src/templates/tags.tsx")
  const result = await graphql(`
    query getContent {
      posts: allMarkdownRemark(
        sort: { order: DESC, fields: [frontmatter___date] }
        limit: 2000
      ) {
        edges {
          node {
            fields {
              slug
            }
            frontmatter {
              tags
              title
              date
            }
          }
        }
      }
      tags: allMarkdownRemark(limit: 2000) {
        group(field: frontmatter___tags) {
          fieldValue
        }
      }
    }
  `)
  // handle errors
  if (result.errors) {
    reporter.panicOnBuild(
      `Error while running GraphQL query. ${JSON.stringify(result.errors)}`
    )
    return
  }
  const posts = result.data.posts.edges
  posts.forEach(({ node }, index) => {
    const prev = index === 0 ? false : posts[index - 1].node
    const next = index === posts.length - 1 ? false : posts[index + 1].node

    createPage({
      path: node.fields.slug,
      component: blogPostTemplate,
      context: {
        prev,
        next,
      },
    })
  })

  const tags = result.data.tags.group
  tags.forEach(tag => {
    createPage({
      path: `/tags/${_.kebabCase(tag.fieldValue)}/`,
      component: tagTemplate,
      context: {
        tag: tag.fieldValue,
      },
    })
  })
}

```

**Comment by andrewmartin** [comment]
Ah, just to follow up:

Looks like that `gatsby-plugin-remove-trailing-slashes` was, in fact, causing some issues for me. I removed that and changed the format to something like this in my frontmatter and it seemed to work. Needed both the leading and trailing slash.

`path: /projects/lego/`

**Comment by sk8Guerra** [comment]
> Bit of an avoiding the problem solution, but to fix this I contained the entire function and return statement in an if statement like:
> `if(frontmatter !== null) { }`
> 
> and then put an else statement `else return null`, it seemed like it was trying to produce a blog post from a null markdown after producing the actual blog posts. Probably my dodgy code - but it builds

For now, I've solved it like this too. thanks @tomwilliamfranklin

**Comment by akash-yadav12** [comment]
I was facing the same issue, so what i did, i created another post with same content as previous post(post which was showing cannot read property of null) and rerun the code, then the new post which i created was working fine and the previous post which was showing the error was still showing the error so i deleted it. now everything is working fine.
This worked out for me :)

**Comment by ishwarrimal** [comment]
Tried editing the existing post by adding "/" but still didn't help.
The only solution was to delete the old blog and add a new one.

**Comment by kohane27** [comment]
> 
> 
> Bit of an avoiding the problem solution, but to fix this I contained the entire function and return statement in an if statement like:
> `if(frontmatter !== null) { }`
> 
> and then put an else statement `else return null`, it seemed like it was trying to produce a blog post from a null markdown after producing the actual blog posts. Probably my dodgy code - but it builds

Hello where do I put this if statement? Thanks!

**Comment by sk8Guerra** [comment]
@kohane27 I've placed it in my `post.js` template.

```javascript
if(frontmatter !== null) {
    // you article content...
}
```

**Comment by hiteshsahu** [comment]
For me, the issue was in docs.js adding a null check solved it. I do not see this error anymore. Here are the changes that I have applies there:

```diff

    // meta tags
-  const metaTitle = mdx.frontmatter.metaTitle;
+ const metaTitle = mdx.frontmatter? mdx.frontmatter.metaTitle : "";

-  const metaDescription = mdx.frontmatter.metaDescription;
+ const metaDescription = mdx.frontmatter? mdx.frontmatter.metaDescription: "";
```

**Comment by Isaac-Tait** [comment]
I am running into this error as well. I have an open discussion thread going right now [here](https://github.com/gatsbyjs/gatsby/discussions/34274)...

My mdx format blogs did not have a `path` in the frontmatter... Not sure if I need to add that to my frontmatter as just this morning there was no error and now there is. Does someone have an example of how to implement the null check they can share? Thanks in advance for any guidance offered.
