### ISSUE TITLE
Include html file as a react component / iframe

### ISSUE THREAD

**Issue by jquintozamora** [gatsbyjs/gatsby#4104]
I'm using **Gatsbyjs** (latest version) to create a demo site. 
On my demo site I have two solutions, one is React App and the second one is HTML app (**pure html**).
I'd like to use gatsby as a Static Site Generator for both solutions.
I'm **not able to import an HTML file** within react. Basically, this is what i am trying to do:

```jsx
import React from 'react'
import Link from 'gatsby-link'
import App from '../../example_2/index.html'

const SecondPage = () => (
  <div style={{ margin: '40px auto', width: '700px' }}>
    <h2 style={{ textAlign: 'center' }}>example_2</h2>
    <Link to="/">Go back</Link>
    <App />
  </div>
)

export default SecondPage
```

Any help / guidance will be appreciated.

**Comment by KyleAMathews** [comment]
Try writing `console.log(App)`. The HTML isn't a React component so you won't be able to render it like a React component.

Also, if the HTML file has a head, then that'll cause trouble.

See https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml
