### ISSUE TITLE
gatsby-plugin-canonical-urls not using the siteUrl option

### ISSUE THREAD

**Issue by danhounshell** [gatsbyjs/gatsby#4110]
## Description

I believe that the latest fix for canonical urls, #3405,  broke the intended functionality. Example: I have the canonical urls plugin configured with siteUrl set to http://danhounshell.com, my primary domain. However when you view the page at https://danhounshell.github.io/blog/tips-for-gatsby-elasticlunr-search-plugin/ you can see that the canonical meta uses the danhounshell.github.io domain rather than danhounshell.com. I have several other older domain names that are no longer being used also pointing to that blog and for SEO purposes I want the canonical source to be the domain danhounshell.com.

### Environment

Gatsby version: v1.9.199
gatsby-plugin-canonical-urls: v1.0.13
Node.js version: v8.9.1
Operating System: macOS High Sierra 10.13.3

### File contents (if changed):

`gatsby-config.js`: relevant change: 

```
{ resolve: "gatsby-plugin-canonical-urls", 
     options: { siteUrl: "http://danhounshell.com" }
}
```

`package.json`: added gatsby-plugin-canonical-urls
`gatsby-node.js`: no relevant changes
`gatsby-browser.js`: not changed
`gatsby-ssr.js`: not changed

### Actual result

The canonical meta tag uses the current domain, in the case of the example domains below it would be another.com

### Expected behavior

The canonical meta tags should use the domain name set in the siteUrl config option for the plugin: example.com

### Steps to reproduce

1\. Have more than one domain name pointing to a site, ex: example.com and another.com

2\.  Implement gatsby-plugin-canonical-urls with siteUrl option set to one of those domains, ex: example.com

3\. After building and deploying, access the site through a different domain than set for the siteUrl. Ex: another.com

**Comment by KyleAMathews** [comment]
Ah good point — could you PR a fix? `siteURL` is optional right so the code in gatsby-browser.js should check if it's available and use it and if not, use what's set on window.location.

**Comment by robwierzbowski** [comment]
@KyleAMathews can you explain the purpose of using `window.location`? If there are identical pages at different subdomains, the `window.location` fallback will give two different canonical URLs, negating canonical URL benefits. If there's only one domain, there's no need for canonical URLs.

**Comment by KyleAMathews** [comment]
Good point haha. I guess we shouldn't do anything if there's not a siteURL?

**Comment by szimek** [comment]
This more of a question than a bug report ;) I've just noticed that in `gatsby-browser.js`, this plugin adds query params and hash to canonical url. Should it do that? If I have a urls like `https://mysite.com/buy-stuff` and `https://mysite.com/buy-stuff?cid=some-campaign` - these 2 pages should have the same canonical url, but won't, right?

**Comment by danhounshell** [comment]
@szimek I guess it depends on what the developer's intentions are for the query params and hash. In the case you mentioned it seems like you would not want those to be two separate canonical urls. However, in a case like https://mysite.com/search?q=something&page=1 and https://mysite.com/search?q=something&page=22, I would want those to be 2 separate canonical urls.

**Comment by szimek** [comment]
@danhounshell You're right, though it would probably make sense to mention how it works in the README.

I converted `gatsby-plugin-canonical-urls` to local plugin and I modified it to not add query and hash to canonical url and also to add `og:url` meta tag. Now I just need to figure out how to add scope (or I'll just add `local-` prefix) to names of local plugins, so that it's harder to confuse them with the official ones ;)

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
