### ISSUE TITLE
Request: Enable filtering for non array properties contained in an array

### ISSUE THREAD

**Issue by danhounshell** [gatsbyjs/gatsby#4111]
## Description

This was previously raised in #1645, allowing for filtering for a property in an array using the example: 
```
query Foo {
  allX(
    filter: { id: { in: ['1', '2', '3'] } }
  ) {
    ....
  }
}
```
@KyleAMathews answered that it is already a feature and showed an example using `tags: { in: [$tag] }`. He is correct, but it only works for properties, like tags, that are arrays. It does not work for properties that are strings. The example above, filtering by id, does not work.

It would be great if `in` and `notin` were supported by all property types.

FWIW I was able to work around this by adding an `ids` field to the node in onCreateNode that is basically just an array with the one single value of the id of the node. Then it my queries I query for `fields: { ids: { in: [$ids] } }`.

### Actual result

Query throws a graphQL error, syntax is not supported.

### Expected behavior

Query should resolve and include any nodes with ids of 123, 456 or 789.

### Steps to reproduce

1\. Perform a graphQL allThings query with a filter for id existing in an array of strings: 
`filter: { id: { in: ['123', '456', '789'] } } `

**Comment by adam-kuhn** [comment]
I'm willing to give this a try

**Comment by pieh** [comment]
@adam-kuhn couple hints if You want to implement this:

Here we add operators to filters in schema:
- https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/infer-graphql-input-fields.js#L30-L56 ( here we infer from data )
- https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/infer-graphql-input-fields-from-fields.js#L84-L107 (here we infer from custom graphql fields that are created using [setFieldsOnGraphQLNodeType](https://www.gatsbyjs.org/docs/node-apis/#setFieldsOnGraphQLNodeType) api function )

And here's where actual filtering take place - https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/run-sift.js

**Comment by adam-kuhn** [comment]
hey... I think this is over my head. So don't expect a solution from me. Thanks for the hints, I'll still attempt to get my head around this, just for the sake of learning

**Comment by m-allanson** [comment]
No problem, thanks for giving it a shot!
