### ISSUE TITLE
React and ReactDom Version? (createPortal error)

### ISSUE THREAD

**Issue by benjamingeorge** [gatsbyjs/gatsby#4113]
how do I find out which version of ReactDom Gatsby is using ?  I get errors when trying to use `createPortal` or `<Fragment>`. Is there a way to update React to a later version ? 
```
TypeError: _reactDom2.default.createPortal is not a function
```

I'm using Gatsby version 1.9.201

**Comment by KyleAMathews** [comment]
Gatsby v1 is on React 15. You can install gatsby-plugin-react-next to use React 16. V2 (coming soon!) will use React 16 by default.
