### ISSUE TITLE
ERR_EMPTY_RESPONSE when accessing dev site on host OS with vagrant

### ISSUE THREAD

**Issue by JheeBz** [gatsbyjs/gatsby#4126]
## Description

Using a Vagrant Ubuntu 16.04 virtual machine on Windows 10 I'm unable to access the site on a forwarded port.

### Environment

Gatsby version: 1.9.158
Node.js version: v8.9.4
Operating System: 
- Guest OS (VM): Ubuntu 16.04.3 LTS 
- Host OS: Windows 10 64-bit build 1709

### File contents (if changed):

`gatsby-config.js`: not changed
`package.json`: not changed
`gatsby-node.js`: not changed
`gatsby-browser.js`: not changed
`gatsby-ssr.js`: not changed

### Actual result

When I navigate to http://localhost:3030 I receive an empty response as per below:

```
localhost didn’t send any data.
ERR_EMPTY_RESPONSE
```

### Expected behavior

My Vagrantfile is set up to forward port 3000 to 3030. It should be displaying the develop site. I can confirm this works in the exact same project using create-react-app (I used CRA in the project root on port 3000 and it displayed correctly at http://localhost:3030/cra-test on my host OS).

### Steps to reproduce

1\. Install [Vagrant](https://www.vagrantup.com/downloads.html)
2\. Install [Git for Windows](https://git-scm.com/download/win) and open it as an Administrator
3\. Run `sudo npm install --global gatsby-cli`
4\. Run `gatsby new tutorial-part-one https://github.com/gatsbyjs/gatsby-starter-hello-world`
5\. Open a Command Prompt as an Administrator
6\. Navigate to the directory you created and run vagrant init ubuntu/xenial64
7\. Replace the contents of the Vagrantfile with the following:
```Ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, guest: 3000, host: 3030,
    auto_correct: true
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end 
end
```
8\. Create a bootstrap.sh file in the parent directory with the following:
```bash
#!/usr/bin/env bash
# Install Node and Apache 
sudo apt-get update -y
sudo apt-get install -y apache2
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install nodejs -y
if ! [ -L /var/www/html ]; then
  rm -rf /var/www/html
  ln -fs /vagrant /var/www/html
fi
```
9\. Run `vagrant up && vagrant ssh` (note this will take a while because it'll have to download the ubuntu/xenial64 image)
10\. `$ cd /vagrant && npm run develop -p 3000`
11\. Navigate to http://localhost:3030 on the host OS

When I use cUrl on the guest OS I receive a successful HTTP response. When I use cUrl on the host OS I receive the following unsuccessful response:
```
C:\>curl http://localhost:3030
curl: (52) Empty reply from server
```

At this point I get the error described above. I've tried searching for similar issues but I've not been able to find any issues like this. Any help would be much appreciated because Vagrant is a very useful tool for developing on a non-Unix platform.

**Comment by m-allanson** [comment]
Does this work if you set the host to `0.0.0.0`? `npm run develop -H 0.0.0.0 -p 3000`

**Comment by JheeBz** [comment]
Interestingly that did work but I have to access it via http://localhost:3030 on my host OS and http://0.0.0.0:3030 does not work. That solves my issue, thanks!


Perhaps a note in the documentation about this kind of workaround would help others using VM environments like Vagrant.

**Comment by m-allanson** [comment]
👍 Some docs on `gatsby-cli`'s `-p` and `-H` options would be really useful I think.

For a bit of background info, [this is a good explanation of 0.0.0.0 vs localhost](https://stackoverflow.com/questions/20778771/what-is-the-difference-between-0-0-0-0-127-0-0-1-and-localhost#20778887). It looks like CRA defaults to 0.0.0.0 rather than localhost which is why your CRA test worked.

**Comment by m-allanson** [comment]
Actually I'm going to close this and create a separate issue about docs.
