### ISSUE TITLE
Error: Cannot find module 'gatsby-cli/lib/reporter'

### ISSUE THREAD

**Issue by vegmorse** [gatsbyjs/gatsby#4131]
This builds just fine locally both in gatsby develop and gatsby build.

But once it pulls from my git repo (and runs on Netlify), it throws this.

Gatsby 1.9.118

6:44:23 PM: error UNHANDLED EXCEPTION
6:44:23 PM: 
6:44:23 PM:   Error: Cannot find module 'gatsby-cli/lib/reporter'
6:44:23 PM:   
6:44:23 PM:   - v8-compile-cache.js:159 require
6:44:23 PM:     [repo]/[v8-compile-cache]/v8-compile-cache.js:159:20
6:44:23 PM:   
6:44:23 PM:   - index.js:574 Object.<anonymous>
6:44:23 PM:     [repo]/[gatsby-plugin-sharp]/index.js:574:14
6:44:23 PM:   
6:44:23 PM:   - v8-compile-cache.js:178 Module._compile
6:44:23 PM:     [repo]/[v8-compile-cache]/v8-compile-cache.js:178:30
6:44:23 PM:   
6:44:23 PM:   - v8-compile-cache.js:159 require
6:44:23 PM:     [repo]/[v8-compile-cache]/v8-compile-cache.js:159:20
6:44:23 PM:   
6:44:23 PM:   - extend-node-type.js:28 Object.<anonymous>
6:44:23 PM:     [repo]/[gatsby-transformer-sharp]/extend-node-type.js:28:17
6:44:23 PM:   
6:44:23 PM:   - v8-compile-cache.js:178 Module._compile
6:44:23 PM:     [repo]/[v8-compile-cache]/v8-compile-cache.js:178:30

Is there any way I can dig into the actual unhandled error?

**Comment by m-allanson** [comment]
I think @pieh is working on a fix for this. As a temporary workaround adding [`gatsby-cli`](https://www.npmjs.com/package/gatsby-cli) to your project (not globally) should fix it.

**Comment by jonavila** [comment]
For me, it's failing on both develop and build. It's started happening after I updated some packages, but reverting back to the previous version doesn't seem to fix the issue.

**Comment by pieh** [comment]
Fix is ready for review https://github.com/gatsbyjs/gatsby/pull/4122 

@jonavila `gatsby-remark-images` depends on bugged `gatsby-plugin-sharp` so downgrading `gatsby-plugin-sharp` in your project won't fix this if you use `gatsby-remark-images` unfortunately. Try using workaround provided by @m-allanson for now.

**Comment by vegmorse** [comment]
Many thanks!! the @m-allanson solution works for me. ;)

**Comment by pieh** [comment]
Fixed with #4122 . Update `gatsby-plugin-sharp` to 1.6.31 and `gatsby-remark-images` (if used) to 1.5.47

**Comment by solokiran** [comment]
Hi,
Any solution for the similar problem please. Occurred while following tutorial video of quick-start https://www.gatsbyjs.org/docs/quick-start/


npm run develop

> gatsby-starter-default@0.1.0 develop /home/batman/gatsby/my-default-starter
> gatsby develop

success open and validate gatsby-configs - 0.010 s
error Error in "/home/batman/gatsby/my-default-starter/node_modules/gatsby-source-filesystem/gatsby-node.js":


  Error: Cannot find module 'gatsby-cli/lib/reporter'
  
  - loader.js:636 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:636:15
  
  - loader.js:562 Function.Module._load
    internal/modules/cjs/loader.js:562:25
  
  - loader.js:690 Module.require
    internal/modules/cjs/loader.js:690:17
  
  - v8-compile-cache.js:159 require
    [my-default-starter]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - utils.js:15 Object.<anonymous>
    [my-default-starter]/[gatsby-source-filesystem]/utils.js:15:18
  
  - v8-compile-cache.js:178 Module._compile
    [my-default-starter]/[v8-compile-cache]/v8-compile-cache.js:178:30
  
  - loader.js:787 Object.Module._extensions..js
    internal/modules/cjs/loader.js:787:10
  
  - loader.js:653 Module.load
    internal/modules/cjs/loader.js:653:32
  
  - loader.js:593 tryModuleLoad
    internal/modules/cjs/loader.js:593:12
  
  - loader.js:585 Function.Module._load
    internal/modules/cjs/loader.js:585:3
  
  - loader.js:690 Module.require
    internal/modules/cjs/loader.js:690:17
  
  - v8-compile-cache.js:159 require
    [my-default-starter]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - create-file-node.js:7 Object.<anonymous>
    [my-default-starter]/[gatsby-source-filesystem]/create-file-node.js:7:18
  
  - v8-compile-cache.js:178 Module._compile
    [my-default-starter]/[v8-compile-cache]/v8-compile-cache.js:178:30
  
  - loader.js:787 Object.Module._extensions..js
    internal/modules/cjs/loader.js:787:10
  
  - loader.js:653 Module.load
    internal/modules/cjs/loader.js:653:32
  
  - loader.js:593 tryModuleLoad
    internal/modules/cjs/loader.js:593:12
  
  - loader.js:585 Function.Module._load
    internal/modules/cjs/loader.js:585:3
  
  - loader.js:690 Module.require
    internal/modules/cjs/loader.js:690:17
  
  - v8-compile-cache.js:159 require
    [my-default-starter]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - gatsby-node.js:12 Object.<anonymous>
    [my-default-starter]/[gatsby-source-filesystem]/gatsby-node.js:12:19
  
  - v8-compile-cache.js:178 Module._compile
    [my-default-starter]/[v8-compile-cache]/v8-compile-cache.js:178:30
  

⠋ load plugins
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-default@0.1.0 develop: `gatsby develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gatsby-starter-default@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/batman/.npm/_logs/2019-06-19T09_12_18_591Z-debug.log



System :  ubuntu 64bit
node and npm : 10.16.0  and 6.9.0
