### ISSUE TITLE
Document gatsby-cli's --port and --host options

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#4132]
When running `gatsby develop`, you can pass in a hostname and port. The hostname option isnt' documented anywhere (that I can find 😄), and the port option is only mentioned briefly in the Getting Started docs.

We should document both options, and common cases where you might want to use them.

Refs: https://github.com/gatsbyjs/gatsby/issues/4126#issuecomment-366791476

**Comment by KyleAMathews** [comment]
Thanks for the PR @jmoujaes! FWIW, you can see more detailed help for individual commands on the command line by running `gatsby develop --help`. But yeah, that's more hidden away.

**Comment by fk** [comment]
Fixed in #4145(?)! Thanks @jmoujaes!

**Comment by jmoujaes** [comment]
Correct, should've commented :) np!
