### ISSUE TITLE
Error after build: Uncaught TypeError n(...) is not a function (prop-types)

### ISSUE THREAD

**Issue by awesomebob** [gatsbyjs/gatsby#4133]
Gatsby: 1.9.202

I haven't been able to reliably reproduce the issue, but thought I'd post this just in case someone else has noticed a similar issue.

More than once, I've noticed that when I load my site after a fresh production build, some of the content will load and some will not. My first thought was that my layout/index.js was loading but not the page content, but upon inspecting the DOM I found that the page elements were there but not fully rendered.

The javascript console included this error:

![screenshot_1519078148](https://user-images.githubusercontent.com/3677807/36400391-74ea7bbe-1585-11e8-90a0-25a2bc488ee3.png)

Clicking on the first index.js:27 link showed me what appears to be code from the [prop-types package](https://github.com/facebook/prop-types/blob/b7d03cef5abd5bb3de8428013e4f921157d949b4/index.js#L27), which led me to think it could be related to this [prop-types webpack issue](https://github.com/contra/react-responsive/issues/134)

The error persists through page refreshes until I clear the cache with a hard Ctrl+F5 refresh.

I realize that I haven't provided much to go on in terms of reproducing the bug, but would be happy to learn how I can better debug this.

**Comment by KyleAMathews** [comment]
I'd guess you're caching the JavaScript? https://www.gatsbyjs.org/docs/caching/

**Comment by awesomebob** [comment]
@KyleAMathews Ah, it appears you are correct. I remember reading that page and so had not implemented any JS caching myself, but I failed to check whether my server setup had caching in place already (and it does). Thanks for the help.
