### ISSUE TITLE
Can I Register a Type to the Root Schema?

### ISSUE THREAD

**Issue by dairyisscary** [gatsbyjs/gatsby#4137]
## Description

I've been writing some local plugins for Gatsby and been really enjoying myself (thanks for the awesome tech by the way!). I'm working on a pair of plugins that create/transform nodes, but they both suffer from the same issue: if the  `onCreateNode`/`sourceNodes` functions never call `createNode`, then the type never gets added to the graph scheam at all and queries will fail in the client side. For instance, I'm working on an S3 source plugin that creates a node for each object in the bucket, but we can totally imagine a bucket with no objects inside. I would want the client to still query the `allS3Object` field, just getting an empty `edges`.

Is there a way in which I "register" a node type to the schema even though I may never end up producing a node of that type? I looked around at a few of the official source producers, but they all at least always produce at least one node that I can see. Am I missing an obvious API?

### Environment

Gatsby version: 1.9.202
Node.js version: 8.9.4

### Plugin Example
```js
// Condensed code...
async function sourceNodes({ boundActionCreators }, { bucketName }) {

  let objects;
  try {
    objects = await getAllObjectsInBucket(bucketName);
  } catch (e) {
    console.error(e);
    process.exit(1);
  }

  const { createNode } = boundActionCreators;

  // Heres the problem:
  // If `objects` is an empty array, we never call `createNode` and queries on type `S3Object`
  // wont work.
  objects.forEach(object => {
    createNode({
      id: `${Key} s3 object from ${bucketName}`,
      parent: "__SOURCE__",
      children: [],
      internal: {
        type: "S3Object",
        contentDigest: getDigest(object),
      },
      // ... 
    });
  });
}

exports.sourceNodes = sourceNodes;
```

**Comment by pieh** [comment]
There's no way to register data type without any data as currently gatsby does infer data types from data. One (messy) way to go around it is to create "dummy" node with some kind of dummy flag and dummy data so fields are inferred if no objects were created (so type gets registered) and then when querying for that data of that type filtering out objects that are flagged as dummy.

**Comment by dairyisscary** [comment]
Oh, okay. That's unfortunate. For my particular use case, its fine since I always expect to produce at least one value, I'm going to close this issue; thanks for the help.

**Comment by Floriferous** [comment]
@pieh Is still still the best practice? Sounds really hacky, instead of simply getting an empty array on the client?
