### ISSUE TITLE
Feature Request: Page collections

### ISSUE THREAD

**Issue by renatorib** [gatsbyjs/gatsby#414]
### Briefing

My project has a big number of Landing pages for sales. One landing page per partner using the same template and changing only the variables.

But, it's a bit complicated. The landing pages change frequently. 
Today I have a huge operational task to delete and create new .md files every time it is changed.

To handle that, _before I started using Gatsby_, we had a script that generate all the things we need in a single json file, a collection file. At that time I had written another script that generate all the pages using the template (gulp and handlebars were my friends).
### Suggestion: theory

My suggestion is that it works:

**pages/collection.json** =>

``` json
[
  {
    "title": "My phone page",
    "path": "/my-phone-page",
    "cta": "Call me maybe"
  },
  {
    "title": "My selling page",
    "path": "/my-selling-page",
    "cta": "Buy me, please"
  }
]
```
### Suggestion: implementation

I confess that I have not mastered the Gatsby code yet, despite having given a good study xD. 
But I have a suggest of implementation of this: when Gatsby read the file and parse it, you can check if it's an array, then split in multiple pages. To deal with url resolver, if items not have a `path`, you can resolve it as `/${filename}-${arrayOrder}/`: `/collection-1/`, `/collection-2/`, etc.

**Comment by KyleAMathews** [comment]
With the current Gatsby I'd suggest you maintain the data as you suggest and then auto-generate JSON files for each page and create a json wrapper component (like https://github.com/gatsbyjs/gatsby-starter-default/blob/master/wrappers/json.js) for the landing pages.

For Gatsby 1.0 — read #420 and #421 — would love to hear your reaction to my ideas!

**Comment by renatorib** [comment]
Yes, I have the json wrapper :) 

Nice to know you are working on 1.0
I'll check this!
