### ISSUE TITLE
Render HTML tags from frontmatter

### ISSUE THREAD

**Issue by Ieuanoh** [gatsbyjs/gatsby#4146]
## Description

Hello! New to using Gatsby and I'm trying to render HTML tags from a frontmatter field in a post template. I need a short paragraph of text with breaks in it separate to the main body of content from my Markdown file. I'm used to doing this with Hugo using it's safeHTML function. Is there a way I can do it in Gatsby?

I'm using the remark plugin to pull in my frontmatter fields. But it's just pulling in the text as a string, as expected. 

Thanks!

**Comment by pieh** [comment]
You can use react's `dangerouslySetInnerHTML` (as a contrast to safeHTML i guess :) ):

```jsx
<div dangerouslySetInnerHTML={{__html: post.frontmatter.fieldWithHtml }} />
```

**Comment by Ieuanoh** [comment]
Doh. Of course that works! Thanks very much :)
