### ISSUE TITLE
Replace React with web components

### ISSUE THREAD

**Issue by dcroitoru** [gatsbyjs/gatsby#4147]
## Description

Question: 
Is it possible to replace React with something that uses web components, like StencilJS?

**Comment by nickmccurdy** [comment]
I'm not sure what Stencil is capable of, but as far as I'm aware web components don't support SSR so it would be hard to do what Gatsby does at build time.

**Comment by daniel-packard** [comment]
According to stencil docs: 

> Stencil also enables a number of key capabilities on top of Web Components, in particular Server Side Rendering (SSR) without the need to run a headless browser, pre-rendering, and objects-as-properties (instead of just strings).

https://stenciljs.com/docs/server-side-rendering

**Comment by romulocintra** [comment]
Would be great just start some kind of experimental branch or fork to replace react by any WC lib , love stencil and is getting  better everyday .

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
