### ISSUE TITLE
File changes not detected when using vagrant

### ISSUE THREAD

**Issue by JheeBz** [gatsbyjs/gatsby#4149]
## Description

File changes are not being detected when using Vagrant. This is also the case for CRA but the official solution is to create .env file with `CHOKIDAR_USEPOLLING=true`. In gatsby, the best workaround I've seen is to run the dev environment with the following shell script:

```bash
#!/usr/bin/env bash

export CHOKIDAR_USEPOLLING=1
gatsby develop -H 0.0.0.0
```

This works, but it's definitely not ideal.

### Environment

Gatsby version: 1.9.158
Node.js version: v8.9.4
Operating System:
- Guest OS (VM): Ubuntu 16.04.3 LTS
- Host OS: Windows 10 64-bit build 1709

### Actual result

Gatsby is not recompiling when changes are made to files. I believe Vagrant does an rsync to get the updated files on the Guest OS.

### Expected behavior

Should be reloading as changes are made to files.

### Steps to reproduce

The steps outlined in #4126 step 10 changed to:
10\. `$ cd /vagrant && npm run develop -H 0.0.0.0 -p 3000`
...
And with the following additional step:
12\. Make a change to a file
At this point the changes are not reflected on the dev site.

**Comment by KyleAMathews** [comment]
Interesting. Thanks for the work around! We're planning on automatically adding env variables from `.env` files soon too to the node process which will make `.env.development` work as well.
