### ISSUE TITLE
Url-loader dependency

### ISSUE THREAD

**Issue by newswim** [gatsbyjs/gatsby#415]
I got an error after a fresh install of gatsby and initializing from the starter-blog.

```
Module not found: Error: Cannot resolve module 'url-loader'
```

I believe that it was getting called by an internal gatsby package, `prefixLink`, simple fix:

```
npm i url-loader --save
```

**Comment by newswim** [comment]
same for `raw-loader`

if this does not bear mentioning, feel free to close this issue.

**Comment by KyleAMathews** [comment]
@newswim which version of node/npm are you using? NPM 2 isn't well supported right now. I or someone needs to go clean that up.

**Comment by newswim** [comment]
For this I was using Node @ 4.5.0, and NPM @ 2.15.9

**Comment by KyleAMathews** [comment]
Ok, if you can — just upgrade to NPM 3 and reinstall.

**Comment by newswim** [comment]
Everything seems fine now, I just added those two modules to my dependencies and was able to deploy via netlify.

**Comment by KyleAMathews** [comment]
Thanks for the report. I added those two modules to the blog starter.
