### ISSUE TITLE
[gatsby-plugin-sharp] Resize issue - "Int cannot represent non-integer value"

### ISSUE THREAD

**Issue by Betree** [gatsbyjs/gatsby#4156]
## Description

When trying to resize an image using only width, Gatsby doesn't round calculated height.

```graphql
thumbs: allImageSharp {
  edges {
    node {
      id
      img: resize(width: 300) {
        src
        width
        height
      }
    }
  }
}
```

### Environment

Gatsby version: 1.9.202
Node.js version: 8.9.4
Operating System: Ubuntu 16.04 x64

### Actual result

```
The GraphQL query from xxx/index.js failed

        Errors:
          GraphQLError: Int cannot represent non-integer value: 395.9183673469388,
```

### Expected behavior

Calculated height should be rounded.

Example : resize 128x125 with width 64 should give 64x76

### Steps to reproduce

1. Install `gatsby-plugin-sharp` and add it to your `gatsby-config.js`
2. Add a picture with resolution `128x125` (like [this one](https://user-images.githubusercontent.com/1556356/36455998-d3446ae0-16f6-11e8-9b84-17b22e7cc7ce.png))
3. Add the following query :

```graphql
thumbs: allImageSharp {
  edges {
    node {
      id
      img: resize(width: 64) {
        src
        width
        height
      }
    }
  }
}
```

### Causes

I suspect that the root cause is this : https://github.com/gatsbyjs/gatsby/blob/25458558c3f8cc2974297444ee08e04600892d3f/packages/gatsby-plugin-sharp/src/index.js#L318

I'm going to test this hypothesis and I'll make a PR if confirmed.

**Comment by pieh** [comment]
Calculation is correct, but returned value isn't rounded - so wrapping that in `Math.round` should fix the issue.

**Comment by Betree** [comment]
@pieh You're right I've edited the description. 

Just submitted PR #4156 that fixes my crash.

**Comment by eric-personal** [comment]
Is this fix only in V2. Trying to figure out how to stop this in V1. Its driving me crazy.
