### ISSUE TITLE
Example site running clarification

### ISSUE THREAD

**Issue by orshick** [gatsbyjs/gatsby#4160]
## Description

I tried to run run some sites from the gatsby example section (gatsbygram and using-page-transitions). Basically I cloned the gatsby repo, npm installed inside it, entered the example site's directory and npm installed there too. "gatsby develop" errored out with this message.

![image](https://user-images.githubusercontent.com/3633609/36461550-1e3b07fe-168c-11e8-9c6f-a0e42194d641.png)

Anybody have any idea why I got this? Did I just miss something about how to run the example sites?

Thanks.

### Environment

Gatsby version: 1.1.41
Node.js version: 9.5.0
Operating System: Windows 10

### Actual result

Error that is listed above. Site does not go into 'develop' mode.

### Expected behavior

I should be able to see the site! 

### Steps to reproduce

1\. git clone the gatsby repo, then npm -i inside of it

2\. enter the example site directory, then npm -i inside of it

3\. When installation is done, run 'gatsby develop' 

...

**Comment by calcsam** [comment]
Closing this, thanks @fk
