### ISSUE TITLE
File change detected, but GraphQL data not updated

### ISSUE THREAD

**Issue by Betree** [gatsbyjs/gatsby#4163]
## Description

I'm trying to build a website with markdown pages. HMR detect the changes but the new data is not fetched and I have to restart development server to see updates. 

Making the request directly in GraphiQL **works** - I get the refreshed data.

Is there a cache for templates requests that could be messing up here ?

### Environment

Gatsby version: 1.9.202
Node.js version: 8.9.4
Operating System: Ubuntu 16.04 x64

### File contents (if changed):

`src/templates/page.js`:

```jsx
import React from "react"


class Page extends React.Component {
  render() {
    const post = this.props.data.markdownRemark
    return (
      <div className="project">
        <div dangerouslySetInnerHTML={{ __html: post.html }} />
      </div>
    )
  }
}

export default Page

export const pageQuery = graphql`
query PageByPath($path: String!) {
  markdownRemark(fileAbsolutePath: {eq: $path}) {
    id
    html
  }
}
`
```

`gatsby-config.js`:

```javascript
module.exports = {
  siteMetadata: {
    title: "xxxxxxxxxxx",
    author: "xxxxxxxxxx",
  },
  plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/pages`,
        name: "pages",
      },
    },
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 590,
            },
          },
          {
            resolve: `gatsby-remark-responsive-iframe`,
            options: {
              wrapperStyle: `margin-bottom: 1.0725rem`,
            },
          },
          "gatsby-remark-copy-linked-files",
          "gatsby-remark-smartypants",
        ],
      },
    },
    `gatsby-plugin-sharp`,
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sass`,
    `gatsby-plugin-react-helmet`,
  ],
}
```

`package.json`: 

```json
{
  "name": "coline.piouffle.com",
  "description": "Coline Piouffle personnal website",
  "version": "0.8.0",
  "dependencies": {
    "bulma": "^0.6.2",
    "gatsby": "^1.9.204",
    "gatsby-link": "^1.6.8",
    "gatsby-plugin-manifest": "^1.0.4",
    "gatsby-plugin-offline": "^1.0.4",
    "gatsby-plugin-react-helmet": "^2.0.5",
    "gatsby-plugin-sass": "^1.0.17",
    "gatsby-plugin-sharp": "https://github.com/Betree/gatsby/releases/download/v1.9.204-resize-fix/gatsby-plugin-sharp.tar.gz",
    "gatsby-remark-copy-linked-files": "^1.5.2",
    "gatsby-remark-images": "^1.5.47",
    "gatsby-remark-responsive-iframe": "^1.4.3",
    "gatsby-remark-smartypants": "^1.4.3",
    "gatsby-source-filesystem": "^1.5.21",
    "gatsby-transformer-remark": "^1.7.33",
    "gatsby-transformer-sharp": "^1.6.20",
    "lodash": "^4.15.0",
    "react": "^16.2.0",
    "react-dimensions": "^1.3.0",
    "react-dom": "^16.2.0",
    "react-grid-gallery": "^0.4.8",
    "react-helmet": "^5.2.0"
  },
  "devDependencies": {
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "prettier": "^1.6.1"
  },
  "scripts": {
    "start": "gatsby develop",
    "build": "gatsby build"
  }
}
```

`gatsby-node.js`:

```javascript
const _ = require("lodash")
const Promise = require("bluebird")
const path = require("path")
const select = require(`unist-util-select`)
const fs = require(`fs-extra`)


exports.createPages = ({ graphql, boundActionCreators }) => {
  const { createPage } = boundActionCreators

  return new Promise((resolve, reject) => {
    const pages = []
    const Project = path.resolve("./src/templates/project.js")
    const Page = path.resolve("./src/templates/page.js")
    resolve(
      graphql(
        `
        {
          directory {
            absolutePath
          }
          allMarkdownRemark {
            edges {
              node {
                id
                fileAbsolutePath
                frontmatter {
                  thumb {
                    base
                  }
                }
              }
            }
          }
        }
    `
      ).then(result => {
        if (result.errors) {
          console.log(result.errors)
          reject(result.errors)
        }

        // Create pages
        _.each(result.data.allMarkdownRemark.edges, edge => {
          const relativePath = _.replace(edge.node.fileAbsolutePath, result.data.directory.absolutePath, '')
          const route = _.trimEnd(_.trimEnd(relativePath, '.md'), 'index')
          const component = _.startsWith(route, '/projects/') ? Project : Page
          const parentDir = edge.node.fileAbsolutePath.replace(/\/[^\/]+$/, '')
          const thumbName = edge.node.frontmatter.thumb && edge.node.frontmatter.thumb.base

          createPage({
            path: route,
            component: component,
            context: {
              path: edge.node.fileAbsolutePath,
              resourcesGlob: parentDir + '/*',
              thumbGlob: `${parentDir}/${thumbName}*`
            },
          })
        })
      })
    )
  })
}
```

### Actual result

* Modify + save file
* Console show

```
info changed file at /xxx/src/pages/about.md
 WAIT  Compiling...                                                                                                                                                             18:11:55
 DONE  Compiled successfully in 75ms 
```

* HMR detect the change and reload page

```
[HMR] connected
[HMR] bundle rebuilding
[HMR] bundle rebuilt in 83ms
[HMR] bundle rebuilding
[HMR] bundle rebuilt in 96ms
```

* Changes to markdown file are not there

### Expected behavior

I should be able to see the modifications.

**Comment by jonavila** [comment]
Experiencing the same issue. File changes are detected but the cache gets corrupted. I have to clean the `.cache` directory and restart.

**Comment by jonavila** [comment]
I believe this update on gatsby@1.9.199 might be what is causing it:
https://github.com/gatsbyjs/gatsby/commit/7f510ccca4a133f518f2d24094377c24cf68d832#diff-c493f1f6a7fbc32136fda0e6522712aa

**Comment by jonavila** [comment]
More specifically, this empty query:
https://github.com/gatsbyjs/gatsby/commit/7f510ccca4a133f518f2d24094377c24cf68d832#diff-a45448af33cc109010d5aab8911336ddR16

**Comment by rayk** [comment]
I am having the similar problem, restarting the development server, or making a change to the template causing it to be rebuilt fixes the problem.

**Comment by subsid** [comment]
I am having the same problem. Making a change to a *.md file causes the data returned to be empty. I can also confirm that removing the empty query from `component.js` as suggested by @jonavila fixes the problem.

**Comment by KyleAMathews** [comment]
I'm pretty sure this was causing the trouble. At least it fixed things when I reproduced the problem on gatsbyjs.org :-)

https://github.com/gatsbyjs/gatsby/pull/4213/files/cb52bc81b85f466e846da528bc0ec9b0eead9ec4#diff-a45448af33cc109010d5aab8911336dd

**Comment by Betree** [comment]
@KyleAMathews I just tried with the latest update (gatsby@1.9.211), I'm still having this issue.

**Comment by KyleAMathews** [comment]
@Betree do you have a site where I could reproduce the problem?

**Comment by KyleAMathews** [comment]
@jonavila oh and just saw you pointed out the exact problem :-D

**Comment by jonavila** [comment]
@KyleAMathews 👍. I would have PR'ed a fix, but hadn't looked through the contribution guidelines and I'm fairly new to Gatsby 😄. I just texted the fix and it's working great.

**Comment by Betree** [comment]
@KyleAMathews here is the project with bare minimum files to reproduce the bug.

[gatsby-graphql-reload-bug.tar.gz](https://github.com/gatsbyjs/gatsby/files/1754066/gatsby-graphql-reload-bug.tar.gz)

Just run `npm install` then `gatsby develop`, open http://0.0.0.0:8000 and try to edit `src/pages/index.md`. On my local machine change is detected (recompiling) but needs server restart to take effect (= to re-run graphql query).

**Comment by KyleAMathews** [comment]
Thanks for the reproduction @Betree! With that, narrowed it down fairly quickly to your setting `path` on the page context — internally, we expect `context.path` to be the "page" path e.g. `/` in this case and use it to track dependencies between data and pages. Because `path` was now the path to the file that you passed in, when the markdown data changed, we weren't able to find the page that should be updated so quit. Change path to something else and things started working.

#4225 adds validation for context field names to prevent people from using names that overlap with core page field names.

**Comment by Betree** [comment]
@KyleAMathews Amazing, thanks for your support ! Validation works well and so does changing `path`.

**Comment by cettoana** [comment]
Problem solved, thanks!!

**Comment by baerrach** [comment]
I think this is a newbie trap.

Is this the same as https://github.com/gatsbyjs/gatsby/issues/3460#issuecomment-356642274?

As https://github.com/gatsbyjs/gatsby/issues/3460#issuecomment-481493689 suggests noting this in the docs might alleviate these issues being raised.
