### ISSUE TITLE
Delete css from previous builds as well

### ISSUE THREAD

**Issue by danielberndt** [gatsbyjs/gatsby#4166]
## Description

I've took and build the starter with basic css. I then switched to including *all* my css via glamor.

I then executed `gatsby build` once more. Since the old css file from the previous build was not deleted, it included both, the inlined glamor css as well as the old css from the starter, leading to unintended style issues.

### Environment

Gatsby version: 1.9.202
Node.js version: 9.4.0
Operating System: macOS 10.12.6

### Actual result

The html of the `gatsby build` included both, the new glamor inline style as well as the old, removed css files from the starter

### Expected behavior

Delete all css from the `/public` as a first step when performing `gatsby build`.

### Steps to reproduce

1\. use any starter kit using css files

2\. build it

3\. remove all css files, build it again. The css will still be embedded in the html

**Comment by KyleAMathews** [comment]
Oh right, we should do this. Thanks for reporting the bug! Would you like to PR a fix? It should go right after deleting the HTML https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/bootstrap/index.js#L62

**Comment by danielberndt** [comment]
Working on a PR now :)

**Comment by danielberndt** [comment]
fixed by #4187

**Comment by adamUpchurch** [comment]
Would one of you point me to a resource why running 'gatsby develop' deletes html and css file changes and what is the proper way to make such a change that isn't supposed to be deleted? Google isn't doing the trick. lol
