### ISSUE TITLE
Automatically run gatsby develop after creating a new site

### ISSUE THREAD

**Issue by tsriram** [gatsbyjs/gatsby#4167]
Just wondering why don't we run `gatsby develop` after creating a new site i.e. after running `gatsby new ...`? I'm quite sure there'll be some platform quirks across different OSes to get this done. Is there any other reason why we shouldn't / can't do this? May be everyone doesn't want this? FWIW, I've always wanted to run `gatsby develop` after creating a new one. Other tools like CRA also requires users to switch to the project directory and run it manually. Doing this automatically would be great. Would love to hear others thoughts on this!

**Comment by KyleAMathews** [comment]
🤷‍♂️ not everyone would like this? Some people want to init a new git repo first? It's also a relatively uncommon task, creating new sites so we haven't tried optimizing the process as much.

**Comment by tsriram** [comment]
Hmm yeah, perhaps not everyone needs this!
