### ISSUE TITLE
[gatsby-source-contentful] Do not include localized nodes when required fields are not translated

### ISSUE THREAD

**Issue by anjawaldbauer** [gatsbyjs/gatsby#4170]
## Description

It would be great if we could ask that localized nodes should not be included, if required fields in contentful are not localized. I know that there is an option to make localized fields required, but that would required all pages to be translated. What I would like to have is the ability to translate some pages, but not all, but then not include the ones I didn't yet translate in the response.

Is this currently possible? If not, please consider this a polite feature request :)

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
