### ISSUE TITLE
Issues with React 16 and react-test-renderer

### ISSUE THREAD

**Issue by nickmccurdy** [gatsbyjs/gatsby#4171]
## Description

When using Gatsby 1 with gatsby-plugin-react-next (React 16), I'm unable to resolve all peer dependencies since Gatsby wants 15, the plugin wants 16, and react-test-renderer wants only one of the two. I tried using react-test-renderer-16 but it causes my Gatsby build to break because of the React version it uses. For now my workaround is to remove gatsby-plugin-react-next and stick to React 15, but it would be nice to be able to use both React 16 and react-test-renderer.

### Environment

Gatsby version: 5.6.0
Node.js version: 9.5.0
Operating System: macOS

### File contents (if changed):

https://github.com/nickmccurdy/nickmccurdy.github.io/tree/gatsby-rtr-bug

### Actual result

https://gist.github.com/nickmccurdy/28f4af0added2e7c4283253004f12724

### Expected behavior

Gatsby 1 and react-test-renderer 16 can be installed and used in the same project without errors.

### Steps to reproduce

1. `npm install gatsby gatsby-plugin-react-next react react-test-renderer`
2. `gatsby build` or `gatsby serve` to see the unminified error

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
