### ISSUE TITLE
Evaluate hard-source-webpack-plugin

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#418]
Has anyone tried https://github.com/amireh/happypack?

Curious if it could be adopted to Gatsby for reducing build times.

**Comment by KyleAMathews** [comment]
Andd hard-source https://github.com/mzgoddard/hard-source-webpack-plugin

**Comment by thangngoc89** [comment]
Hi @KyleAMathews , I implemented hard source webpack plugin for Phenomic and I must say the result is awesome. It boosts build time up to 300%. But happypack isn't working with hard-source those.

**Comment by KyleAMathews** [comment]
Nice! It seems super promising. How plug-n-play did you find it?

**Comment by thangngoc89** [comment]
100% plug-n-play. There is some bugs, we reported it and a patch was released immediately.

**Comment by stereobooster** [comment]
Webpack 2.0 https://webpack.github.io/docs/roadmap.html? It promise tree shacking for ES6

**Comment by fabien0102** [comment]
I have a tried with [fusebox](https://github.com/fuse-box/fuse-box), it's very fast (50ms for a react project)! (but less modules as webpack when I tried) @KyleAMathews If you want have a try with gatsby, it can be cool 😉

**Comment by KyleAMathews** [comment]
We're pretty tightly integrated with webpack... so switching off would be a big project. Would love faster hot reloading but all the goodies in webpack and the breath of the ecosystem are really hard to beat.

**Comment by fabien0102** [comment]
It was just a proposition for "evaluation", I was really impressed by the hot-reload reactivity with fusebox (it's just instant!), but I understand that all of our ecosystem is based on webpack ^^
