### ISSUE TITLE
No styling on gatsby build

### ISSUE THREAD

**Issue by ajayns** [gatsbyjs/gatsby#4183]
I'm working on a project kickstarted with `gatsby-starter-default` and uses the `gatsby-source-hackernews` plugin. I've added custom styling by importing `.css` files into React components and there's default styling in the boilerplate as well.

All these display perfectly with I run `gatsby develop` but when I do a production build using `gatsby build` and serve the `/public` folder I notice that the entire styling is missing, except for inline styling maybe. 

**Expected Behavior**
![Giphy](https://media.giphy.com/media/PoK1epauQuWcuhmH57/giphy.gif)

**Current Behavior**
https://gatsby-hacker-news.netlify.com/
![image](https://user-images.githubusercontent.com/20743219/36523215-8d8e18c2-17c6-11e8-9fdf-752fbcd4c9fe.png)

Project repo: https://github.com/ajayns/gatsby-hacker-news

**Comment by KyleAMathews** [comment]
Looks like you need to inject the styles in the head like in the default html.js https://github.com/gatsbyjs/gatsby/blob/ba4666829b1c908c75e4e65b726516c501ef0bca/packages/gatsby/cache-dir/default-html.js#L3

**Comment by Jaikant** [comment]
I had the same issue, in a sas project. In which I had to use the css from react-slick. Injecting it in the html.js resolved it for me.
