### ISSUE TITLE
Gatsby does not reload my page on Windows 10

### ISSUE THREAD

**Issue by TheOpti** [gatsbyjs/gatsby#4186]
### Description
I set up a new gatsby project and ran it via gatsby develop command. Everything seems to be OK, network monitor in my Google Chrome DevTools doesn't show any errors (i.e. __webpack_hmr loads properly). I already checked similar topics and people there had problems with loading __webpack_hmr, but in my case it loads properly. I tried both these two commands:

1) `gatsby develop`
2) `gatsby develop --host localhost --port 8000`

### Environment
Gatsby version: 1.1.41
Node.js version: 9.3.0
NPM version: 5.5.1
Operating System: Microsoft Windows [Version 10.0.15063]

### Expected behavior
I would like to have my project refreshed when I make changes in my code.

### Steps to reproduce

1\. Install gatsby, set up a new project
2\. Run it via `gatsby develop` command

**Comment by mpolinowski** [comment]
Hi @TheOpti ,

can you update gatsby in your app? I am using gatsby v1.9.204 in Windows 10 / Chrome and hot-reloading works fine with it.

**Comment by TheOpti** [comment]
Hey @mpolinowski 

Unfortunately it doesn't work with any files in my case. No matter which file I edit, page is not being refreshed.

**Comment by m-allanson** [comment]
@TheOpti are you able to publish a repo with your project?

**Comment by nenu-git** [comment]
I have the same issue on Windows 10 using Chrome. 

HMR was working just fine, and stopped working for unknown reason (didn't change any package or something).

The strange thing about it is that when I kill `gatsby develop` (ctrl + c), I have the `[HMR] connected` message in the console.

When I check on the `Network` tab of the dev console, I can see that `__webpack_hmr` status is `(pending)`:

![image](https://user-images.githubusercontent.com/26092508/37771849-282581f4-2dd9-11e8-846a-fe551c431cb0.png)

I also tired with Firefox but HMR is not working here too.

**Comment by jorispz** [comment]
Reload isn't working for me either (Windows 10, gatsby v1.9.273) when using Edge or Firefox, but it does work under Chrome.

In my case, it is not a problem of file changed not being detected - I see gatsby compiling on every edit just fine. But somehow, Firefox and Edge just sit there and not show the change (unless I reload), while Chrome does pick up the changes live.

In Edge's console it says:
> webpack-hot-middleware's client requires EventSource to work. You should include a polyfill if you want to support this browser: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events#Tools

Firefox doesn't seem to load any HMR related stuff at all:

![image](https://user-images.githubusercontent.com/2202571/41998647-858617c2-7a5b-11e8-8b02-44271af2beae.png)


What's really odd is that I am positive everything worked fine on my previous laptop, on Firefox. I recently upgraded and reinstalled everything (including Node etc) so maybe that broke something?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
