### ISSUE TITLE
[question] Private wordpress blog

### ISSUE THREAD

**Issue by nobuti** [gatsbyjs/gatsby#4190]
I just set up a wordpress api integration and it works great, but when I configure the blog as private one in wordpress.com, the api returns 404. The thing is I have to fill the credentials in the `
gatsby-source-wordpress` configuration, is there any way to achieve this?

**Comment by calcsam** [comment]
Yes, you can read the documentation here, you'll want to add `wpcom_user` and `wpcom_pass` fields: https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-wordpress

**Comment by nobuti** [comment]
I'm missing something for sure, because I have filled those fields, but still I get `The server response was "403 Forbidden". Inner exception message : "User cannot access this private blog." No routes to fetch. Ending.`.  This is the related config:
```
{
      resolve: 'gatsby-source-wordpress',
      options: {
        baseUrl: 'cartogatsby.wordpress.com',
        protocol: 'http',
        hostingWPCOM: true,
        useACF: false,
        auth: {
          wpcom_app_clientSecret: 'supersecret',
          wpcom_app_clientId: '555',
          wpcom_user: 'wadus',
          wpcom_pass: 'wadus'
        },
        verboseOutput: false
      }
}
```
Like I said if I set the blog hidden or public, all the things go fine, but when it's private I get the error above.

The documentation you linked says you'll need to [provide an api key](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-wordpress#how-to-use-gatsby-with-wordpresscom-hosting) but it's not clear to me where in the config file I need to put it on.

**Comment by lazharichir** [comment]
Same... Switching the blog to private gives me:

```
source and transform nodes
The server response was "403 Forbidden"
Inner exception message : "User cannot access this private blog."
No routes to fetch. Ending.
```

**Comment by lazharichir** [comment]
I fixed it by editing fetcher.js and replacing:

```

      if (_auth) {
        options.auth = {
          username: _auth.htaccess_user,
          password: _auth.htaccess_pass
        };
      }
```
with...
```

      if (_auth && _auth.htaccess_user) {
        options.auth = {
          username: _auth.htaccess_user,
          password: _auth.htaccess_pass
        };
      }

      if (_hostingWPCOM) {
        options.headers = {
          Authorization: `Bearer ${_accessToken}`
        }
      }
```

**Comment by pieh** [comment]
Would you be willing to open PR with your change @lazharichir?

**Comment by lazharichir** [comment]
> Would you be willing to open PR with your change @lazharichir?

Done - #8110 (my first time contributing, so I hope it's done properly)
