### ISSUE TITLE
[question] using URL parameters for dynamic page

### ISSUE THREAD

**Issue by pibemillo** [gatsbyjs/gatsby#4192]
How would I go about using URL parameters on a page to display different data?

Ex. `domain.com/dyanamic-page/?param=dogs`  

Page would then render data from a dog.json file and display something like "You like dogs".

Or ex. `domain.com/dyanamic-page/?param=cats`  

"You like cats".

Just need to be pointed in the right direction, thanks!

**Comment by KyleAMathews** [comment]
Check out `this.props.location` as it has all the url info parsed out. Good luck!
