### ISSUE TITLE
Detect if the site named passed to "gatsby new" is a URL

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#4193]
I tried creating a site just now with `gatsby new https://github.com/etc/etc` and Gatsby helpfully created a new default starter deep into a nested set of directories `https: >> github >> etc >> etc`.

This is a reasonably easy accident to make, be trying to create a site from a starter and forget to set the site name. To catch this, we should test the site name if it looks like a URL and if it does, error and quit.

**Comment by yeskunall** [comment]
I've actually done this a few times. PR's up for review!
