### ISSUE TITLE
[gatsby-source-hackernews] Does it need to rebuild everytime for new posts?

### ISSUE THREAD

**Issue by ajayns** [gatsbyjs/gatsby#4202]
I was recently working with `gatsby-source-hackernews` plugin and I realized that all the data is queried on build and it's used as nodes in Gatsby. So for a deployment, which is supposed to update each time on reload, to show new posts, what is the method to be followed? 
Or when it's called static does it mean it's not supposed to update?

**Comment by CanRau** [comment]
if i understand you correctly i would say you would need to have some more dynamic parts which fetch content on reload or whenever you want
so you build some parts statically maybe have the overall application/website statically so when the users enters the most part is already usable and then you load in the content

or, if it's not updating too often you could just build the whole thing statically and pull every now and then to check if there is anything new which you could then fetch if necessary

or you could have the whole thing rebuild automatically by a CI server on git push or similar so it'll just rebuild everything without the need for dynamic and continuous polling

hope my gibberish helps in any way ^^

**Comment by KyleAMathews** [comment]
The actual files that are generated are only regenerated on build.

*data* can be refreshed or gotten new from the client as with any web site.

If you're building a HN clone, I'd just setup your CI to rebuild the site every 5-10 minutes or so the static data is fresh.

**Comment by ajayns** [comment]
@KyleAMathews That is the answer I was looking for. Thank you, I'm closing this issue!

P.S It would really help if you could share some guide on doing that.

**Comment by mbavio** [comment]
@ajayns Seems to me like you need to write a script that uses [Netlify API](https://www.netlify.com/docs/api/) to trigger a deploy. Then you need to run that script every 5-10 minutes, or whatever time you need in order to keep it fresh.

**Comment by YannickLeRoux** [comment]
Any ressources/tutorials regarding automatic scheduled deploys on netlify ??
