### ISSUE TITLE
GraphQL question: Can query values refer to each other?

### ISSUE THREAD

**Issue by ooloth** [gatsbyjs/gatsby#4211]
A GraphQL-with-Gatsby question:

If I store my data in `src/data/example.json` like this...

```json
[
  { 
    "image": "../images/image1.jpg", 
    "imageWidth": 2000,
    "alt": "Description of image1..."
  },
  { 
    "image": "../images/image2.jpg", 
    "imageWidth": 3000,
    "alt": "Description of image1..."
  }
];
```

...and I query it with `gatsby-transformer-json` like this...

```js
{
  allExampleJson {
    edges {
      node {
        image {
          childImageSharp {
            sizes(maxWidth: 3000) {
              ...GatsbyImageSharpSizes_withWebp
            }
          }
        }
        imageWidth
        alt
      }
    }
  }
}
```

...is there a way to use the result of `imageWidth` as the `maxWidth` value in the query (instead of `3000`)? Something like this:

```js
{
  allExampleJson {
    edges {
      node {
        image {
          childImageSharp {
            sizes(maxWidth: imageWidth) {
              ...GatsbyImageSharpSizes_withWebp
            }
          }
        }
        imageWidth
        alt
      }
    }
  }
}
```

The above attempt doesn't work, but I'd love to know if there's a way to accomplish it.

I like storing my image file paths and alt text in one place (hence the JSON), but when querying multiple images this way, I usually set the Sharp `maxWidth` to the width of the largest image in the query. Is there a way around this?

**Comment by LeKoArts** [comment]
Do you use this query for a file in `/templates` directory?

**Comment by pieh** [comment]
if `imageWidth` in json is actual width of the image (and not some arg) then `gatsby-plugin-sharp` will use lower of the `maxWidth` arg and image width, so for this use case you don't need anything like this - just use high enough maxWidth

**Comment by KyleAMathews** [comment]
It seems you're confused about `maxWidth` — this should be the `maxWidth` of your design — not your images.

If your design has a fluid-width column whose max-width is 800px, you set `maxWidth` in the query to 800. Then Gatsby will make thumbnails with widths smaller and larger than 800px so whatever the actual width of the the fluid column, your browser will download the correct image.

**Comment by ooloth** [comment]
Ohhh!

@KyleAMathews Thanks for clarifying this. I was confused. This makes things simple. Much appreciated!

@LeKoArts I use a query like that in a file in the `src/pages` directory (querying JSON stored in a `src/data` directory.

@pieh Good to know that Sharp uses the lower of the `maxWidth` and the image's actual width! That was my main concern.

Thanks everyone.
