### ISSUE TITLE
Add instructions for how to profile gatsby

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#4218]
I found this gist from @kittens. We should make it easy to do something similar for Gatsby. Today's debugging session would have been far easier if I could have profiled my code.

https://gist.github.com/kittens/768c883f6c4523bc2499fc046d7e15d3

**Comment by sandys** [comment]
This is +1000 from all of us. We really struggle to set debugging and profiler  sessions for gatsby. I think the overall support requests will go down if we can figure out how to debug this.

One specific request - please make it doubly easy to debug graphql in the gatsby build. I know we have that other tool, but as code becomes more complex and we have large compositions of graphql, it would be good to inspect them inline

**Comment by KyleAMathews** [comment]
Hey @pieh did this!
