### ISSUE TITLE
"Reserved field in the context object error" after updating Gatsby

### ISSUE THREAD

**Issue by martynhoyer** [gatsbyjs/gatsby#4227]
## Description

After upgrading Gatsby from `1.9.149` to `1.9.213` I get the following when running `gatsby develop`:

```
error You used a reserved field name in the context object when creating a page:

"path"

{
    "path": "/logistics",
    "component": "/[redacted]/gatsby-starter-netlify-cms/src/templates/logistics-home.js",
    "context": {
        "path": "/logistics"
    }
}

Replace your invalid field names with ones not on the list of reserved field names:

"path", "matchPath", "component", "componentChunkName", "pluginCreator___NODE", "pluginCreatorName"
```

### Environment

Gatsby version: 1.9.213 (CLI 1.1.44)
Node.js version: 9.4.0
Operating System: macOS 10.13.3

### File contents (if changed):

Largely unchanged from the following repo: 
https://github.com/AustinGreen/gatsby-starter-netlify-cms

**Comment by pieh** [comment]
Check https://github.com/gatsbyjs/gatsby/pull/4225 - rename your context params so it doesn't conflict with reserved field names (and adjust your queries to use newly used name)

**Comment by KyleAMathews** [comment]
Yeah, using `path` in context has silently been causing problems in people's sites. We just started validating against it in #4225.

@AustinGreen could you upgrade your starter?

**Comment by KyleAMathews** [comment]
Actually, I'll make a PR real quick.

**Comment by KyleAMathews** [comment]
Hmm the warning could be improved by making it clear that `path` and other data on the page object are already passed to the graphql queries as arguments.

**Comment by martynhoyer** [comment]
Thanks folks!

**Comment by martynhoyer** [comment]
Hmm, `gatsby develop` works fine with these fixes, but `gatsby build` gives me:

```
error Generating JavaScript bundles failed


  Error: app-8c7523a84d54af1a2332.js from UglifyJs
  SyntaxError: Unexpected character '`' [./~/gatsby-plugin-netlify-cms/gatsby-browser.js:10,0]
```

Looks like the same issue at https://github.com/AustinGreen/gatsby-starter-netlify-cms/pull/41

Any pointers? Not really sure where to start looking there!
