### ISSUE TITLE
Consider using graphcool/graphql-playground ?

### ISSUE THREAD

**Issue by muhajirframe** [gatsbyjs/gatsby#4231]

**Comment by pieh** [comment]
For now you can use their desktop app using `http://localhost:8000/___graphql` (or whatever it is if you change host/port params) as endpoint:

![dca39370161121fd8458f197af0558b7](https://user-images.githubusercontent.com/419821/36720183-8c74db26-1ba7-11e8-9da6-17eacf445f4f.png)

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
