### ISSUE TITLE
How do I import custom components from NPM package correctly?

### ISSUE THREAD

**Issue by rojcyk** [gatsbyjs/gatsby#4234]
This isn't necessarily an issue with Gatsby but probably my lack of understanding how it works. I'm working on a small [React Component library](https://github.com/boomhaus/boom-layout) which I would like to use across my projects as an [NPM package](https://www.npmjs.com/package/boom-layout).

[So far it is pretty barebones.](https://github.com/boomhaus/boom-layout/blob/master/source/index.js)

```
import React, { Component } from "react";

export class Row extends Component {
  constructor(props) {
    super(props);

    this.state = {
      children: props.children
    }
  }

  render() {
    return (
      <div className="row">{this.state.children}</div>
    )
  }
}
```

☝️ This gets build into before publishing to NPM 👇

```
import React, { Component } from "react";

export class Row extends Component {
  constructor(props) {
    super(props);

    this.state = {
      children: props.children
    };
  }

  render() {
    return React.createElement(
      "div",
      { className: "row" },
      this.state.children
    );
  }
} 
```

I've tested it with a basic react app and everything has worked as expected. But the problem arises when I want to include it in my Gatsby project. **When I import the file**  `import Row from 'boom-layout'` the project gets compiled just fine (no error message), but the project itself does not work, it has an error in console saying `Uncaught SyntaxError: Unexpected identifier commons.js:4252` which is `import React, { Component } from "react";`

So as far as I understand it Gatsby has a problem with how I import React in my package. But I have no idea how to solve it 😞

**Comment by LeKoArts** [comment]
I think you're missing a `default`:

```JS
export class Row extends Component ...
```

**Comment by KyleAMathews** [comment]
Also, check if you're transiling the component to es5 before publishing to npm

**Comment by brunomfonseca** [comment]
@rojcyk, I was stuck on the same point as you. If you're using Babel, take a look at babel-preset-env. Transforming the code to es5 solved my issue (as @KyleAMathews mentioned before).

**Comment by rojcyk** [comment]
Thanks guys, finally found some time to test it. Exporting converting to es5 solved the issue!
