### ISSUE TITLE
[gatsby-image & gatsby-plugin-sharp] Configure generated resolutions & sizes

### ISSUE THREAD

**Issue by blazeu** [gatsbyjs/gatsby#4238]
I have hundreds of images and querying/generating it takes ages because gatsby-plugin-sharp generates too many images that I don't even need.

What if I wanted to only generate 1 or 2 sizes / resolutions?

Or if I want to only resize + generate the blur up image?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
