### ISSUE TITLE
Create Gatsby plugin: how to make post request using gatsby-config settings

### ISSUE THREAD

**Issue by benjaminhoffman** [gatsbyjs/gatsby#4244]
I'd like to make a Gatsby plugin, `gatsby-plugin-mailchimp`. It will handle all the logic around adding an email address to a user's Mailchimp account.  It accepts their Mailchimp creds (API key, list ID, etc) via their gatsby-config file, and uses it to make a jsonp req to their MC endpoint.  The dev can simply add a method to their form submit that sends the data to MC.  (I want to build out that method and export it)

The MC setup can be arduous for some. This plugin will be lightweight and extrapolate much of the complexity to working with MC's API on the client (which, is possible but not actively promoted).

Also, I think the Gatsby docs are severely lacking in documentation around how to build a plugin for newbs so if I can get this working (the "right" way), I'll write up a blog post for others on how to get started.

I'm not sure how to wire everything up here but I know I want the result to look like:

```javascript
// user's gatsby-config.js
module.exports = {
  plugins: [
    {
       resolve: 'gatsby-plugin-mailchimp',
       options: {
          hostname: // string, the MC hostname for your account
          listId: // string; the MC list id
          settings: // object; maybe some other important MC config settings
       }
  ]
}
```

```javascript
// in the user's React component
import React from 'react'
import { addToMailchimp } from 'gatsby-plugin-mailchimp'

export default class SomeForm extends Component {
  _handleSubmit = async (e) = {
    // accepts an email address and optionally, other attributes to be saved along w the email address
    const result = await addToMailChimp(e.target.value, {attributes})
    // do something with 'result' 
  }
  render () {...}
}
```

My guess is to export a method from `gatsby-plugin-mailchimp/index.js` that makes a jsonp call to mailchimp with the user's MC settings (from their `gatsby-config`), along with the website visitor's email address (that's passed in from the React component).  Any suggestions on how to get started and wire everything up?

**Comment by DamnedScholar** [comment]
Since Gatsby produces flat HTML files, you have to use some method to write your own JavaScript into the flat files on node creation. In my reading of the Gatsby API, I discovered that I could use a `gatsby-ssr.js` file to add external JS libraries.

```
import React from "react"
import fs from 'fs'

exports.onRenderBody = ({ setPostBodyComponents, setHeadComponents }, pluginOptions) => {
  // This could be broken out into a plugin and, if I make any other additions to this file, probably should be.
  var dir = "src/scripts/"
  var files = fs.readdirSync(dir)
  var scripts = []
  var scriptLog = []

  files.forEach((file) => {
    var text = fs.readFileSync(dir + file, {encoding: 'utf8'})
    scripts.push(
      <script
        key={file}
        dangerouslySetInnerHTML={{__html: text}}
      />)
    scriptLog.push(file)
  })

  if (scriptLog)
    console.log("Adding scripts: " + JSON.stringify(scriptLog))

  return setHeadComponents(scripts)
}
```
Now, that file lives in the body of my Gatsby project, but I'm given to understand from looking at [plugins](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-google-analytics/src/gatsby-ssr.js) and the documentation that a plugin with the same file could accomplish the same thing. So using this method, you can write a little script to process the information from the form submission and make the request to MailChimp, and then inject it into the `<head>`.

**Comment by benjaminhoffman** [comment]
Thank you @DamnedScholar for the quick response!  Much appreciated.  I did briefly look at this solution but determined it wasn't the right fit because having this MC code in the head, on every page, seems messy and overly broad, no?  Ideally, I'd like it to be within _only_ the component that invokes my `addToMailchimp` method.  It should not be in the head and not be on every page.

Thoughts?

**Comment by KyleAMathews** [comment]
I think a helper function makes a lot of sense. To make the plugins options available to the helper function, I'd add a gatsby-browser.js to the plugin and use the (`onClientEntry` API](https://www.gatsbyjs.org/docs/browser-apis/#onClientEntry) to set the options on the window object where then the helper function can access them to complete sending data to mailchimp. 

```javascript
exports.onClientEntry = (_a, options) => window.___GATSBY_PLUGIN_MAILCHIMP_OPTIONS = options
```

**Comment by KyleAMathews** [comment]
And a blog post/docs page on writing plugins would be super helpful!

**Comment by DamnedScholar** [comment]
> having this MC code in the head, on every page, seems messy and overly broad, no?

Yes in the sense of strict design principles. It would be inelegant and terrible if you were editing the pages yourself, but you're not, and unless you're doing something *very* fancy I can't see your functions taking up more than 30 lines of code. Whatever you need to do is going to be tiny, and since it will *just* be loaded and not be run until the `Submit` button is pressed, it would take a very old computer to be negatively impacted by including the script on every page.

In the same project, it just so happens that I've got *another* script that I'm loading inside [one of my components](https://github.com/DamnedScholar/gatsby-cusco/tree/master/src/components/RestaurantMenu), and for that I'm using `react-helmet`, [like so](https://github.com/DamnedScholar/gatsby-cusco/blob/master/src/components/RestaurantMenu/RestaurantMenu.jsx#L131-L141).

**Comment by tulikavijay** [comment]
@benjaminhoffman documentation on making gatsby plugins sounds great!
@KyleAMathews  @DamnedScholar I have been thinking about how some sort of gatsby data structure would be great too, to handle nodes - in terms of parents and children hierarchy. I am a beginner in gatsby but would really like to know more about making gatsby-plugins.

**Comment by DamnedScholar** [comment]
@tulikavijay Are you talking about making a `gatsby-source-scripts` plugin to make the live scripts on your site available through the data layer? That could work, and I could see there being some use cases, but it feels like over-engineering. It would be a more complicated solution than the ones I've presented above, and most pages with substantial scripts on them aren't going to be generated in the same way that blog posts are.

**Comment by benjaminhoffman** [comment]
🤔 hm lemme think.  It sounds like my only options are either: attach my Mailchimp data to the global window object or add my mailchimp script to the head.  Both sound like the _opposite_ of best practice but if I can't find a better solution by this weekend, I'll likely go with one of these routes.

I do appreciate the advice here!  Will give this some thought and update this thread when I push up my code.  Thank you!

**Comment by tulikavijay** [comment]
@DamnedScholar I was talking about using APIs and a content tree. And then converting them into a static Gatsby website using GraphQL. Sorry for being confusing!

**Comment by benjaminhoffman** [comment]
Hmm gave this more thought.  Both proposed solutions require the code to be on _every single page_ whether as in the head (@DamnedScholar solution) or as data on the window object (@KyleAMathews solution).  

I just don't think that's the right move here because what if the user has a large site but has their Mailchimp form on one page... it just doesn't seem right to have the MC info or logic on all the pages.  Also, although the MC settings are not private per se, we also don't want to make it easy for others (or bots) to capture the info (to prevent spam, etc).  Lastly, I don't want to use the API's settings as the place to determine when or when not to include this code, I think that logic should be left to the component that imports the Mailchimp settings on a per-page basis.

I'm going to continue to look for a solution.  If anyone has any ideas or further explanation, I'm all ears! 👂

**Comment by jlengstorf** [comment]
@benjaminhoffman I may be wrong about this, but if you were to include the MailChimp info in the component that uses it, then code-splitting should make sure that it's only loaded when the component that calls MailChimp is actually used.

For example:

```js
// ... import dependencies ...
import { sendToMailChimp } from 'gatsby-plugin-mailchimp';

const handleSubmit = event => sendToMailChimp(event);

const MailChimpForm = () => {
 // ... define your form and attach the submit handler ...
};

// ... proptypes, etc.
```

I just ran a quick test on this and set up a click handler that's exported from a Gatsby plugin and it does indeed bundle with only the template that used it. So it looks like that would be a valid option for making the helper available without exposing it on every page.

As far as not exposing the settings to bots, etc., there's not much to be done there. If it's bundled on the front-end, it's available to anyone looking. 🤷‍♂️  I suppose you could do something to obfuscate it (e.g. `btoa` => `atob`), but that's certainly not going to secure anything. Could confuse bots, I guess.

Honestly, though, if you only use settings that MailChimp exposes in their own web forms, it's probably safe to trust their spam prevention efforts.

**Comment by benjaminhoffman** [comment]
thanks @jlengstorf !  When you say `MailChimp info`, are you referring to the MC settings (like API key, list ID, etc) or the user info (like their email and other attributes)?

I want the MC settings to be sent in via the `gatsby-config` file loaded _only_ on the pages with the MC form, not sitewide.  The user settings will be available on a per-component basis (ie, in your `sendtoMailchimp` method).

One may say, simply have the user pass the settings in with your MC component.  I'd retort: this is cumbersome and defeats the purpose of this being a "gatsby plugin". At that point, it's simply a node module.

(I dont mind exposing the settings to bots or whatever... I just don't want to expose it on pages that the MC plugin isn't used on).  

ps - which plugin did you test this concept with?  I'd love to take a look!

**Comment by benjaminhoffman** [comment]
solved!  thank you @jlengstorf for the following suggestion!  I decided to have my `addToMailchimp` method import the user's `gatsby-config` file, search for the Mailchimp options object, and use the MC settings listed therein to make the request to MC's server.  This keeps the MC settings out of the document's `<head>` and off the global window object.  The plugin setup is still a bit much, but it's much better than building this logic from scratch!

https://github.com/benjaminhoffman/gatsby-plugin-mailchimp

Next steps:
- [ ] update Gatsby blog to use this plugin
- [ ] add this plugin to Gatsby packages list
- [ ] finish blog on _how to create a gatsby plugin_
