### ISSUE TITLE
'cannot find module gatsby-config.js' when attempting Tutorial-One

### ISSUE THREAD

**Issue by rohancragg** [gatsbyjs/gatsby#4247]
Issue relates to https://www.gatsbyjs.org/tutorial/part-one/

I'd suggest either of 2 solutions

1. Add instruction into tutorial text (similar to tutorial-two) 

"in your code editor, create a file at the root of your project folder named gatsby-config.js"

`module.exports = {
    siteMetadata: {
      title: 'Gatsby Default Starter',
    },
    plugins: [],
  };`

2. Amend https://github.com/gatsbyjs/gatsby-starter-hello-world to include this file by default

**Comment by KyleAMathews** [comment]
I can't reproduce this on my mac. Could you post the full error?

`gatsby-config.js` files aren't required and we try to ignore the errors here https://github.com/gatsbyjs/gatsby/blob/6698317e156933236766384f04485489053c6221/packages/gatsby/src/utils/test-require-error.js#L5

Tests for this are here https://github.com/gatsbyjs/gatsby/blob/6698317e156933236766384f04485489053c6221/packages/gatsby/src/utils/__tests__/test-require-error.js

It's apparently not working for some sub-set of people though. The more information you can provide about the failure the easier it'll be for us to figure out why the error is happening.

/cc @pieh

**Comment by pieh** [comment]
This doesn't happen on windows too, just checked - https://gist.github.com/pieh/de0791a33c91f753286d77522336db51 . But it was happening before https://github.com/gatsbyjs/gatsby/pull/4196 - so if you develop on windows and your gatsby version is older than 3-4 days, try doing creating new site using hello-world starter or update gatsby package in your already existing project.

**Comment by rohancragg** [comment]
Thanks guys, I can also no longer repro this. I think I had the problem on 25th Feb and reported it in the Discord chat but now seems to be resolved.

**Comment by pieh** [comment]
Right, I actually made that PR after You reported this issue in discord :) So thanks for reporting it!

**Comment by rohancragg** [comment]
Thanks @pieh - for the real (npm) newbies amongst us, would you mind sharing how to 'update gatsby package'

**Comment by m-allanson** [comment]
@rohancragg From your project directory you should be able to run `npm update` to update all your packages to the latest versions. npm have a [good overview here](https://docs.npmjs.com/getting-started/updating-local-packages).
