### ISSUE TITLE
Export production build to new folder

### ISSUE THREAD

**Issue by rockmandash** [gatsbyjs/gatsby#4248]
Please export all contents to new folder, not public folder as it may confuse developer what is right or wrong.

**Comment by LeKoArts** [comment]
Why do you think that it may confuse developers?

**Comment by rockmandash** [comment]
If you move whole production build into an independent folder, then you index.html can add some additional features like
```
  <link rel="manifest" href="%CUSTOM_URL%/manifest.json">
  <link rel="shortcut icon" href="%CUSTOM_URL%/favicon.ico">
```
like this, it is very intuitive, I can add addtional meta tag without losing indentation.

**Comment by LeKoArts** [comment]
You could do that by using `react-helmet` in your layouts/index.js or by modifying the `html.js` (more info on that in documentation).

And to be honest I don't understand what it has to do with the build folder. `public` contains everything you need, `static` contains the things you just want to be copied.

**Comment by rockmandash** [comment]
@LeKoArts Ok I got it !
