### ISSUE TITLE
Product page and documentation

### ISSUE THREAD

**Issue by theduke** [gatsbyjs/gatsby#425]
Gatsby is a really great project, but I think it needs better discoverability and documentation.

Does anybody want to collaborate on working on a product page, and writing up a Getting Started guide and some documentation?

It would probably be great to have something set up when publishing a 1.0 release.

@KyleAMathews  maybe you can set up a gatsbyjs/gatsbyjs.github.io repo where we can send PR?

ps: Naturally, the site *must* be built using Gatsby. ^^

**Comment by renatorib** [comment]
I think is great to launch documentation together with 1.0 release

**Comment by KyleAMathews** [comment]
@theduke it'd be fantastic if you start working on this! Launching a website concurrent with the 1.0 release is my plan.

My plan is to put docs as markdown files in a `/docs` directory and build the site from them. The place to start would be by making PRs against the 1.0 branch.

There's a website issue up already at https://github.com/gatsbyjs/gatsby/issues/149 so I'm going to close this one in favor of that one.

Glad you guys want to get involved!
