### ISSUE TITLE
gatsby build doesn't generate css file

### ISSUE THREAD

**Issue by frmok** [gatsbyjs/gatsby#426]
I have following setting in `gatsby-node.js`. When I try to run `gatsby build`, all things work perfectly except the `style.css` is empty. However, if i use `gatsby developer`, i can get the `style.css`. Is there anything wrong in my setting?
```
var ExtractTextPlugin = require("extract-text-webpack-plugin")

exports.modifyWebpackConfig = function (config, env) {
    config.removeLoader('scss')
    config.loader('scss', function (cfg) {
        cfg.test = /\.scss$/
        cfg.loader = ExtractTextPlugin.extract('style', 'css?minimize!sass')
        return cfg
    })
    config.plugin('extract-scss',
        ExtractTextPlugin,
        ["style.css", { allChunks: true }])
    return config
}
```

**Comment by KyleAMathews** [comment]
ExtractTextPlugin is already setup. What happens if you just remove your custom webpack config?

**Comment by frmok** [comment]
wow, it works but instead it generates `styles.css` but it is ok. thanks a lot.
