### ISSUE TITLE
Querying from components

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#4262]
Is it possible to execute a GraphQL query from a regular component? _(Which is **not** a page or a layout)_

If so, how can it be done?

**Comment by fk** [comment]
I think GraphQL Fragments is what you're looking for: https://www.gatsbyjs.org/docs/querying-with-graphql/#fragments

**Comment by KyleAMathews** [comment]
Check out `<StaticQuery>` in v2!
