### ISSUE TITLE
gatsby-image graphQL not loading in build

### ISSUE THREAD

**Issue by petemiller89** [gatsbyjs/gatsby#4265]
I'm trying to use gatsby-image to load images using graphQL queries. When running `gatsby develop`, I get no errors however `gatsby build` throws the following error:

```
error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  19 | 
  20 | const DividerImage = ({ classes, image }) => (
> 21 |   <Img sizes={image.sizes} className={classes.imageStyle} />
     |                     ^
  22 | );
  23 | 
  24 | DividerImage.propTypes = {


  WebpackError: Cannot read property 'sizes' of null
  
  - DividerImage.jsx:21 DividerImage
    src/components/DividerImage.jsx:21:21
  
  - react-dom-server.node.production.min.js:31 za
    ~/react-dom/cjs/react-dom-server.node.production.min.js:31:388
  
  - react-dom-server.node.production.min.js:36 a.render
    ~/react-dom/cjs/react-dom-server.node.production.min.js:36:16
  
  - react-dom-server.node.production.min.js:35 a.read
    ~/react-dom/cjs/react-dom-server.node.production.min.js:35:208
  
  - react-dom-server.node.production.min.js:44 renderToString
    ~/react-dom/cjs/react-dom-server.node.production.min.js:44:1
  
  - gatsby-ssr.js:20 Object.exports.replaceRenderer
    ~/gatsby-plugin-jss/gatsby-ssr.js:20:1
  
  - api-runner-ssr.js:29 
    .cache/api-runner-ssr.js:29:41
  
  
  - api-runner-ssr.js:27 module.exports
    .cache/api-runner-ssr.js:27:25
  
  - static-entry.js:113 module.exports
    .cache/static-entry.js:113:3

```
I've tried searching previous issues and no one seems to have had this error message. The section of my graphQL query looks like this:

```
    FirstBackground: imageSharp(id: { regex: "/Background-mp-1/" }) {
      sizes(maxWidth: 3000) {
        ...GatsbyImageSharpSizes
      }
    }
```

I have the appropriate directory marked in my `gatsby-config.js` file:

```
    {
      resolve: "gatsby-source-filesystem",
      options: {
        name: "img",
        path: `${__dirname}/src/img/`
      }
    },
```

**Comment by KyleAMathews** [comment]
Does your query work in graphiql?

**Comment by KyleAMathews** [comment]
Also can you check if your data is available in the main render function? Perhaps you're passing the data in incorrectly?

**Comment by petemiller89** [comment]
Yes the data was being passed in correctly. The issue seems to have been with the DividerImage component, by checking to see if the image data exists before rendering the component seemed to solve the problem. 

I changed this: 

`const DividerImage = ({ classes, image }) => (
 <Img sizes={image.sizes} className={classes.imageStyle} />}
);`

To this:

`const DividerImage = ({ classes, image }) => (
  <div>
    {image && <Img sizes={image.sizes} className={classes.imageStyle} />}
  </div>
);`

**Comment by KyleAMathews** [comment]
👍
