### ISSUE TITLE
How to identify why GraphQL fields are missing?

### ISSUE THREAD

**Issue by awesomebob** [gatsbyjs/gatsby#4271]
Context: I'm using gatsby-source-wordpress with lots of ACF fields

I frequently run into errors similar to this one: #4267 
Most of the time I'm able to determine why a field is missing, usually because the field has a blank value on a single post somewhere.

```
@ GraphQL Error There was an error while compiling your site's GraphQL queries.
@   Invariant Violation: GraphQLParser: Unknown field `features` on type `acf_26`. Source: document `property` file: `GraphQL request`.
@
```

Is there an easier way to determine why an ACF field is failing to compile to GraphQL? I'm already using `gatsby build --verbose`, is there an additional layer of verbosity I can add to the GraphQL step?

I've tried looking in GraphiQL and the field is just missing, doesn't give me any additional information at this point.

**Comment by pieh** [comment]
Hi, currently there's not easy way to do it - I work on this ( https://github.com/gatsbyjs/gatsby/pull/3905 ) but for now had to put in on hold to get more spare time to do some performance testing as this does change the way gatsby gathers field types from data.

You best bet currently is to examine your wordpress REST endpoints - you can see them if you have verbose output enabled for wordpress plugin: it would be something like `https://<wordpress_url>/wp-json/wp/v2/pages` (for pages) and check what data it shows for `acf` -> `features` fields - it's very often `false` if value wasn't entered, and gatsby will treat that as type conflict if it's for example string or object in other pages/posts

**Comment by awesomebob** [comment]
Hmm, I'm looking at the WP REST endpoints and I see all my fields there, including the `features` field with the values I would expect (arrays).

**Comment by jlengstorf** [comment]
@awesomebob Does _every_ instance of that field return an array? I ran into this with one of my fields where it was returning a boolean for unset fields, which broke the type checking as @pieh described.

**Comment by awesomebob** [comment]
@jlengstorf In this case, yes every instance. I've seen the boolean error several times as well, as recently as this morning:

`@ GraphQL Error Field "gallery" must not have a selection since type "Boolean" has no subfields.`

**Comment by awesomebob** [comment]
Just throwing this out there, this is my only ACF field for which the value is an array of strings (checkbox field), could that be an issue? It was working just fine until this morning.

**Comment by pieh** [comment]
Are arrays always arrays of string or are they are sometimes arrays of string, sometimes arrays of booleans? Array with mixed types is considered as mixed type too.

You can try locally edit `node_modules/gatsby/dist/schema/data-tree-utils.js` function `extractFieldExamples` and add 
```
if (key === 'features') {
  console.log('conflict', obj, next)
}
``` 
in places where it returns `INVALID_VALUE` to see what values it considers as conflicts (it won't tell you *where* they are, but will tell you *what* they are). If this is array then probably `if (!areAllSameType(array)) return INVALID_VALUE` will discard this field.

**Comment by awesomebob** [comment]
@pieh thanks, I'm trying that now. My builds are taking much longer than usual, but hopefully I'll find something with this.

**Comment by hussain-t** [comment]
After spending hours on searching a fix for this, I came up with my own solution. Add the following function in your `functions.php` file. This will return an empty string for `source_url` which is the default property for ACF image in Gatsby GraphQL.

`function set_acf_image_source_url_empty($value, $post_id, $field) {
	if ($field['type'] == 'image' && $value === false) {
		return (object) ['source_url' => ''];
	}
	
	return $value;
}
add_filter('acf/format_value', 'set_acf_image_source_url_empty', 10, 3);
`

I hope this helps :)
