### ISSUE TITLE
Gatsby Link url incorrect after refreshing page

### ISSUE THREAD

**Issue by craig-doyle-uk** [gatsbyjs/gatsby#4282]
## Environment
Gatsby version: 1.9.149
Node.js version: 6.12.3
Operating System: OSX 10.13.2

## File contents
gatsby-config.js:

    module.exports = {
     siteMetadata: {
     title: `Gatsby Default Starter`
    },
    pathPrefix: `https://whatever.netlify.com`,
    plugins: [
     `gatsby-plugin-react-helmet`,
     `gatsby-transformer-sharp`,
     `gatsby-plugin-sharp`,
     {
      resolve: 'gatsby-source-wordpress',
      options: {
        baseUrl: 'f******s.w******y.co.uk',
        protocol: 'http',
        hostingWPCOM: false,
        useACF: true,
        verboseOutput: true
       }
      },{
       resolve: `gatsby-plugin-sass`,
       options: {
        precision: 8
       }
      }]
     }

package.json:
     
    {
     "name": "gatsby-starter-default",
     "description": "Gatsby default starter",
     "version": "1.0.0",
     "author": "Kyle Mathews <mathews.kyle@gmail.com>",
     "dependencies": {
      "gatsby": "^1.9.149",
      "gatsby-image": "^1.0.27",
      "gatsby-link": "^1.6.28",
      "gatsby-plugin-react-helmet": "^1.0.8",
      "gatsby-plugin-sass": "^1.0.14",
      "gatsby-plugin-sharp": "^1.6.22",
      "gatsby-source-wordpress": "^2.0.37",
      "gatsby-transformer-sharp": "^1.6.15",
      "webfontloader": "^1.6.28"
     },
     "keywords": [
      "gatsby"
      ],
     "license": "MIT",
     "main": "n/a",
     "scripts": {
       "build": "gatsby build",
       "develop": "gatsby develop",
       "format": "prettier --trailing-comma es5 --no-semi --single-quote --write \"src/**/*.js\"",
       "test": "echo \"Error: no test specified\" && exit 1"
      },
     "devDependencies": {
      "prettier": "^1.8.2"
     }
    }

## Issue

I am using Gatsby Link tags for my site's navigation, and they work perfectly when the site is entered via the home page, but if I refresh the browser in any other page on the site the base url is set to that page. eg: If I hit refresh on `mysite.com/marine`, then when I try to visit any other page the link addresses in the navigation are now `mysite.com/marine/someOtherPage` instead of `mysite.com/someOtherPage`. I have added a pathPrefix to the config file but this has had no effect and means we are not able to finish and launch the site until we find a resolution.

We are using the links as follows : 

    <Link to={item.page.post_name}>
      {item.page.post_title}
    </Link>

I appreciate any help / pointers anybody can give to resolve this issue! Thanks!

**Comment by m-allanson** [comment]
@craig-doyle-uk Do your `to` attributes all start with a `/`? If not, then the links will be relative to the current page, which sounds like what's happening.

**Comment by jlengstorf** [comment]
Specifically:

```diff
- <Link to={item.page.post_name}>
+ <Link to={`/${item.page.post_name}`}>
    {item.page.post_title}
  </Link>
```

**Comment by craig-doyle-uk** [comment]
Face palm 🙈
Excellent thanks very much @jlengstorf  and @m-allanson !
