### ISSUE TITLE
[docs] Add template for plugin READMEs

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#4284]
It would be helpful to have a standard format for plugin READMEs that covers standard information:

- [ ] How to install
- [ ] Available options (if any)
- [ ] Example(s) of usage (or before-and-after examples of data when the plugin is enabled)
- [ ] How to run tests
- [ ] How to develop locally
- [ ] How to contribute

If a CLI add-on for generating plugins comes to be, this template could easily be generated with the plugin's actual information, but that's down the road a bit.

Other things that still need to be figured out:

- Where do we keep this template? (e.g. its own repo, in the docs somewhere)
- Should we/how do we update existing plugins to use the updated format?
- Does this template change significantly depending on whether the repo is a source, transformer, or general plugin?

**Comment by calcsam** [comment]
cc @ajayns

**Comment by ajayns** [comment]
> If a CLI add-on for generating plugins comes to be, this template could easily be generated with the plugin's actual information

This sounds very interesting, could save a lot of time on getting started and will also improve consistency in plugins

**Comment by shannonbux** [comment]
@jlengstorf I just referenced this issue in a PR where I've included a plugin READme template. Open to ideas of a better place to put the template!

**Comment by shannonbux** [comment]
closed by #6489
