### ISSUE TITLE
Load custom .js on every react route

### ISSUE THREAD

**Issue by imshuffling** [gatsbyjs/gatsby#4285]
I've got some custom .js in the /static folder, I want to load this on every react route.

<img width="835" alt="screen shot 2018-02-28 at 17 37 08" src="https://user-images.githubusercontent.com/739061/36802911-126777be-1cae-11e8-98c6-dc9c920fe9f8.png">

Can anyone point me in the right direction?

<img width="1198" alt="screen shot 2018-02-28 at 17 38 45" src="https://user-images.githubusercontent.com/739061/36802997-504abd20-1cae-11e8-82c2-06975f015ac6.png">

Thanks.

**Comment by KyleAMathews** [comment]
You can require it to your `gatsby-browser.js` file which is loaded into the browser and run on startup.

**Comment by jlengstorf** [comment]
@imshuffling It also may make sense in this case to use a [layout](https://www.gatsbyjs.org/tutorial/part-three/#our-first-layout-component) so you only have to define your page structure once.

**Comment by imshuffling** [comment]
Thanks guys.

**Comment by imshuffling** [comment]
Is there an example project with a working example?

**Comment by jlengstorf** [comment]
@imshuffling This example site uses a layout: https://github.com/gatsbyjs/gatsby/tree/master/examples/using-remark

When you set it up in the `layouts` folder, Gatsby will automatically wrap your page content with the layout you define. (See [the tutorial](https://www.gatsbyjs.org/tutorial/part-three/#our-first-layout-component) for specifics about how to set up your layout.)

Under the hood, Gatsby is taking the contents of each page and dropping it into that layout as a `children` prop. This is a bit of convenience code.

If you _didn't_ use a layout, you could achieve the same effect by creating a `Layout` React component and importing that to all of your pages (which, of course, is what you were trying to avoid 😄). When I built my personal site, I failed to wrap my head around layouts, so I ended up writing my own [`Layout` component](https://github.com/jlengstorf/lengstorf.com/blob/master/src/components/Layout.js) and imported it into all of my [templates](https://github.com/jlengstorf/lengstorf.com/blob/master/src/templates/page.js) and [pages](https://github.com/jlengstorf/lengstorf.com/blob/master/src/pages/error.js).

Does that make sense?

**Comment by imshuffling** [comment]
Thanks - Yup kinda, thanks for taking the time to write that up!
