### ISSUE TITLE
[RFC] Add a roadmap section to the site

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#4295]
It seems like we've got a lot of great RFCs and feature discussions happening, but it's a little hard to track what's been prioritized or is under active development.

Something fun and helpful that we could build is a "roadmap" page for the gatsbyjs.org site that could either be (ranked by how I feel about them):

1. ☹️ A manually edited Markdown file with features that are under active development and links to the issues/PRs
2. 😐 A mix of Markdown for big goals (e.g. Gatsby v2) and a link to open PRs and/or a GitHub Project
3. 🙂 A dynamically generated list of issues and PRs that are placed into a "Gatsby Roadmap" GitHub Project
4. 😄 Same as #3, but also reading issue labels to sort for things like priority, "good first contribution", etc.

This might be more work than it's worth, but if we define a solid workflow for moving from RFC => todo => WIP => merged, we could put those into a Gatsby Roadmap GitHub Project with columns matching the stages of progress. Whenever the site rebuilds, it could read the project's issues from the API and build a list of planned, active, and completed projects.

### The big questions around this are:

1. How feasible is it to keep issues organized in a project with as many contributors as we have?
2. How much work is involved in creating a `gatsby-source-github` plugin that could get us access to the GitHub Project?
  - This may already exist — we can evaluate https://github.com/ldd/gatsby-source-github-api to make sure it does what we need
3. How much value does this add?
  - I would argue that this is a big value add for people who aren't super familiar with GitHub or who are overwhelmed by the GitHub Issues interface. It could help potential contributors quickly find high-value contributions. As we start onboarding more and more non-technical users (e.g. #4201), it could help them understand what features are on the way.

There's a chance that this'll end up being a bit too ambitious, but it seems like it could be a great way to show off the power of Gatsby _and_ create a better at-a-glance overview of the project's status, progress, goals, and direction.

I'd love to get feedback on whether or not you think this is a worthwhile project. ❤️

**Comment by KyleAMathews** [comment]
@DavidWells didn't you do something like this for Serverless? I remember you showing me something a while ago. Would love to hear about how Serverless thought about it!

**Comment by DavidWells** [comment]
⊂◉‿◉つ

I created the https://github.com/serverless/scope to help wrangle issues for the serverless project.

We use it here https://serverless.com/framework/status/. It's a self contained "third party" JS react app that cab be embedded anywhere.

In a nutshell, it lets you funnel issues/PRs with a given github label into a [column grouping of your choosing](https://github.com/serverless/scope/blob/master/frontend/src/default.config.js#L42). It also helps highlight issues like "help wanted" etc. You can see that in the demo. 

This video series explains it all in (too much) detail https://www.youtube.com/watch?v=kTrPeKZ0JxI&list=PLIIjEI2fYC-BtxWcDeTziRp7cIZVEepB3

If you have a sane tagging structure setup in your github repo, it's pretty easy to setup one (or as many as you want) and embed them on a site.

Holler if you want help setting it up @KyleAMathews

**Comment by m-allanson** [comment]
👍 for a roadmap. 

For point 1. as @DavidWells says, this could be done via a good labelling system. I think two categories of labels, _type_ and _status_ would do the trick?
<details>
<summary>Expand this for a couple of examples.</summary>

In [serverless](https://github.com/serverless/serverless/labels) they have these labels:

```
kind/bug
kind/docs
kind/enhancement
kind/feature
kind/question
kind/refactoring
kind/tests

stage/accepted
stage/in-progress
stage/in-review
stage/needs-feedback
stage/wait-cf-support
status/more-info-needed 
```

And in [stylelint](https://github.com/stylelint/stylelint/issues/labels) they have these labels:

```
type: bug
type: documentation
type: enhancement
type: infrastructure
type: new option
type: new rule
type: refactor
type: tests 

status: blocked
status: discussion
status: needs clarification
status: needs investigation
status: wip
```

</details>

---

For point 3. I think a roadmap is also really useful for people who're familiar with GitHub. To me a good roadmap signals that a project is well organised and actively maintained, which is a big plus when evaluating a new tool.

**Comment by jlengstorf** [comment]
@DavidWells this is _doooooooope_.

@KyleAMathews @m-allanson Does Scope look like a good fit for Gatsby?

@m-allanson I was [just talking about how much I love labeling](https://twitter.com/jlengstorf/status/969037682750959617), so I'm way into creating a sane label structure. I opened https://github.com/gatsbyjs/gatsby/issues/4311 to get a discussion going to make this happen.

**Comment by KyleAMathews** [comment]
I think a roadmap page with a high-level overview for the goals of the project in general and specifically what we're working towards in v2, v3, etc. would be perfect.

Pulling in links automatically *might* make sense. I don't know if a high-level page would benefit much though from detailed page links and getting the tagging and sorting working seems more difficult than it's worth. Just link people to the project page(s).

I don't think we need Scope (Sorry David...) — we already have GitHub Projects.

**Comment by jlengstorf** [comment]
We’ve done the labeling part of this, but would still benefit from surfacing issues. @marisamorby is cooking up ideas around this goal in #9634, so I'll close this in favor of that effort.
