### ISSUE TITLE
[docs] Write up trade-offs of using `gatsby-image`

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#4296]
There was a good discussion in #4270 about the performance difference in using `gatsby-image` vs. a standard `img` tag. @KyleAMathews mentioned that we should write up the trade-offs since it's often assumed that `gatsby-image` is equivalent to using an `img` tag.

I'm capturing this issue so we remember to actually do it. 😄

**Comment by KyleAMathews** [comment]
We added a bit of docs in gatsby-image so calling this done
