### ISSUE TITLE
Document createRemoteFileNode

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#4302]
The docs for `gatsby-source-filesystem`'s [`createRemoteFileNode`](https://github.com/gatsbyjs/gatsby/blob/a5c08719ebe1a3004ac8f97b888a73a65fa4fa32/packages/gatsby-source-filesystem/README.md#createremotefilenode) are the word TODO. We should write up some documentation so it's DONE.

It's [implemented here](https://github.com/gatsbyjs/gatsby/blob/a5c08719ebe1a3004ac8f97b888a73a65fa4fa32/packages/gatsby-source-filesystem/src/create-remote-file-node.js).

And there are example usages in:

- [gatsby-source-drupal](https://github.com/gatsbyjs/gatsby/blob/a5c08719ebe1a3004ac8f97b888a73a65fa4fa32/packages/gatsby-source-drupal/src/gatsby-node.js#L140)
- [gatsby-source-wordpress](https://github.com/gatsbyjs/gatsby/blob/a5c08719ebe1a3004ac8f97b888a73a65fa4fa32/packages/gatsby-source-wordpress/src/normalize.js#L394)
- [gatsby-transformer-screenshot](https://github.com/gatsbyjs/gatsby/blob/a5c08719ebe1a3004ac8f97b888a73a65fa4fa32/packages/gatsby-transformer-screenshot/src/gatsby-node.js#L75)

Refs #3132

**Comment by ajayns** [comment]
@m-allanson Thanks for providing all the references to look into and get to know about it. 

Referring to the example usage, I was able to understand what it does and where it can be used, but then how is this data later queried in GraphQL and used in the react components and so on?

**Comment by KyleAMathews** [comment]
Downloaded files are created as File nodes so you can query them e.g. via `allFile`. All the above source plugins create links directly to the file nodes e.g. gatsby-source-wordpress when it finds a referenced image, downloads it and then links to the image from the Media node type (it's been a while since I looked at source-wordpress so the details might be off).

**Comment by ajayns** [comment]
@KyleAMathews Okay that makes sense.
One other thing I noticed was that in both the plugins, nodes are created and also remote ones for the same data. The method that's used in fetching data is, all data fetched and stored, and each of them is used to create nodes. Also before that separately, file nodes and iterated and remote nodes are created. I didn't quite understand the purpose of this?

**Comment by ajayns** [comment]
@pieh  I didn't quite understand that. Let's take the case of [soucre-drupal](https://github.com/gatsbyjs/gatsby/blob/a5c08719ebe1a3004ac8f97b888a73a65fa4fa32/packages/gatsby-source-drupal/src/gatsby-node.js#L140) which seems to bit more clearer to understand. 

There, remote nodes are created for all files and then this seems to be done:
```javascript
if (fileNode) {
          node.localFile___NODE = fileNode.id
}
```

Is `localFile_NODE` a property of each node? And what's the purpose of that step?

**Comment by pieh** [comment]
no - it adds `localFile` field to node (note that this is done before `createNode` function is called). `___NODE` appendix to fieldname tells gatsby that this field will link to other node (in this case it's `File` node that is created by `createRemoteFileNode`).

You can name it however you like - apart from few required fields (`id`, `children`, `parent` and `internal`) you can specify any data you want in node - gatsby will automaticly build schema types for it for graphql.

**Comment by ajayns** [comment]
@pieh Okay that makes sense! Thank you!

**Comment by ajayns** [comment]
@m-allanson This issue can be closed now yeah?

**Comment by m-allanson** [comment]
@ajayns yes, thanks for your work on this!
