### ISSUE TITLE
[CSS MODULE] Compilation issue, passing props to css module

### ISSUE THREAD

**Issue by TomPichaud** [gatsbyjs/gatsby#4303]
Hello there, I'm trying to build reusable components with different style settings, maybe my solution is wrong and you have a better one ?

I'm trying to use a props as a class in styles, using Gatsby CSS Module

```
    import styles from './header.module.sass'

    const Header = props => (
    <header className={styles + props.position}>
```

In my layout, I call header component like this, so header would then render using the specific css for top. I know I can easily do it without the CSS Module, but it's not the point.

`    <Header position="top" />`

This compile the className : `class="[object Object]top"` instead of the proper CSS Module

**Comment by TomPichaud** [comment]
`<header className={styles[props.position]}>` did the trick

**Comment by m-allanson** [comment]
For reference: https://stackoverflow.com/questions/49050257/gatsby-component-props-css-module
