### ISSUE TITLE
Wrap page components before rendering on client?

### ISSUE THREAD

**Issue by slorber** [gatsbyjs/gatsby#4308]
Hi,

This is a question I ask after this twitter conversation with 
@KyleAMathews https://twitter.com/sebastienlorber/status/968540483759886336

I created a React Native Web plugin for Gatsby, but generally the RNW does wrap the root component into a new container.

In SSR there is no problem to generate the pages with this extra wrapping container, but on first client render. The workaround I've found is to remove the extra container of RNW in a [hacky way](https://github.com/slorber/gatsby-plugin-react-native-web/commit/7eac30651181e126e168e1b9b161e9c3af4dae35)

I'd like to remove this hack, so I wonder how to wrap page components on first browser render.

The way to start a RNW application on the frontend is normally:

```
// register the app
AppRegistry.registerComponent('App', () => App);

AppRegistry.runApplication('App', {
  initialProps: {},
  rootTag: document.getElementById('react-app')
});
```

This basically wraps the app into the new container before rendering it. It's also possible to get the wrapped App component from the registry with `AppRegistry.getApplication('App', { initialProps });` so that Gatsby can still be in control of calling the rendering

Any idea?

**Comment by KyleAMathews** [comment]
This should handle that just fine https://www.gatsbyjs.org/docs/browser-apis/#wrapRootComponent

**Comment by slorber** [comment]
thanks I missed this API, i'll try it and reopen if it does not work
