### ISSUE TITLE
[gatsby-plugin-catch-links] doesn't seem to work

### ISSUE THREAD

**Issue by daaain** [gatsbyjs/gatsby#4318]
## Description

I thought it's my website being special, but it seems there's an issue with `gatsby-plugin-catch-links` (or its dependencies).

### Actual result

Page reloads.

### Expected behavior

`pushState` page change.

### Steps to reproduce

1\. Go to https://using-remark.gatsbyjs.org/excerpts/

2\. Click on the last link on the page ("You can see the results here").

3\. Page reloads :(

**Comment by m-allanson** [comment]
@daaain Thanks for the report and providing a good example. You're right that this plugin isn't working as expected, I've added a PR that should fix it.

**Comment by daaain** [comment]
Thanks a lot, just updated the packages and it fixed the issue on my website too 🙏
