### ISSUE TITLE
[Question] Data is not inserted into the component

### ISSUE THREAD

**Issue by li-xinyang** [gatsbyjs/gatsby#4320]
Does the data insertion only apply to `page` and `template` components?

## Description

I am creating a documentation app and would love to insert some FS data into the demo component file, however, nothing is passed down to the demo component props when I try to do so.

```
import { Card, Button, ButtonGroup } from 'sample-ui-react'
import Container from '../../../components/ExampleContainer/container'
import React from 'react'

const CardDemo = props => {
  console.log('data:', props)

  return <div>TEST CONTENT</div>
}

export default Container(CardDemo)

export const query = graphql`
  query aboutQuery {
    site {
      siteMetadata {
        title
      }
    }
  }
`
```

The `props` is always `{}`

### Environment

Gatsby version:
Node.js version:
Operating System:

### File contents (if changed):

```
module.exports = {
  siteMetadata: {
    title: 'UI Design System'
  },
  plugins: [
    'gatsby-plugin-react-helmet', // document `header` manager, (GitHub) https://goo.gl/g8b7bP
    'gatsby-plugin-sass', // pre-processor makes SASS into CSS, (NPM) https://goo.gl/LEPBXW
    'gatsby-transformer-remark', // Markdown parser, (NPM) https://goo.gl/fCrcSu
    {
      resolve: 'gatsby-source-filesystem', // Creating `File` nodes from the FS, (NPM) https://goo.gl/bFuU1v
      options: {
        name: 'componentDemos',
        path: `${__dirname}/src/components-ui-demo/`
      }
    }
  ]
}
```

### Actual result

The `props` is always `{}`

### Expected behavior

It should return the site metadata

### Steps to reproduce

N/A

**Comment by LeKoArts** [comment]
GraphQL queries only work in templates/pages/layouts. You‘ll need to pass the props to the component.
