### ISSUE TITLE
gatsby-remark-prismjs Coy theme broken

### ISSUE THREAD

**Issue by vojtechruz** [gatsbyjs/gatsby#4325]
I was following https://www.gatsbyjs.org/packages/gatsby-remark-prismjs/ tutorial. Works great with solarized light theme, which is used in the tutorial. Even dark or twilight. However, when using coy theme, it is broken, see the following image.

![coy](https://user-images.githubusercontent.com/7038612/36887417-6ff00970-1df1-11e8-98be-1d4cdb49e8f1.jpg)

I just used gatsby-starter blog project, the code is available here.

https://github.com/vojtechruz/vojtechruzicka-blog/

Gatsby remark prism plugin: 1.2.15
Node version: 9.5.0
npm version: 5.6.0
Gatsby: 1.9.199

Windows 10

**Comment by m-allanson** [comment]
Thanks for the report @vojtechruz! I've opened a PR that should fix this.

**Comment by vojtechruz** [comment]
Cool, thanks for the quick resolution.
