### ISSUE TITLE
Backslash escapes are missing in compiled SASS on some starters.

### ISSUE THREAD

**Issue by cmsbased** [gatsbyjs/gatsby#4326]
## Description

I used `forty` starter https://github.com/ChangoMan/gatsby-starter-forty and noticed that grid is not functional. 

Checked code and found that Gatsby compiled SASS and grid element is missing escape backslashes for parenthesis and dollar signs:
```
.-6u28xlarge29 {margin-left: 50%}
```
Compiled same SASS files outside Gatsby and CSS looks like this:
```
 .\-6u\28xlarge\29 {margin-left: 50%}
```

### Environment

Gatsby version: 1.1.45
Node.js version: v8.9.4
Operating System: Windows 10

### Steps to reproduce

1\. `gatsby build` and `gatsby serve` forty starter https://github.com/ChangoMan/gatsby-starter-forty Grid is compiled from _skel.scss
 
2\. View compiled css and find `.-6u28xlarge29` instead of ` .\-6u\28xlarge\29`

3\.  Unescaped `Left parenthesis  \28`,  `right parenthesis \29` and `dollar sign \24` make grid unusable.

**Comment by KyleAMathews** [comment]
I haven't used Sass in years and years... any chance you could dive in and try to understand what's going wrong? AFAIK, our use of SASS is pretty vanilla so not sure why this wouldn't be working.

@ChangoMan any thoughts?

**Comment by cmsbased** [comment]
We can simplify everything and completely remove SASS from this issue and use CSS code only. 
I imported into hello-world starter CSS file with 1 line:
```
.\31 2u\28small\29{width:100%;}
```
The build output is:
```
.\31 2u28small29{width:100%}
```
The div class `12u(small)` wrapping hello world will not be working. 

I suspect this is the minification or compression problem. I have been using Gatsby for couple of days only, so I do not have enough skills to further adjust or troubleshoot this.

**Comment by ChangoMan** [comment]
This might be a webpack issue, related to: https://github.com/webpack-contrib/css-loader/issues/578
The same thing happens when using create-react-app.

**Comment by cmsbased** [comment]
The workaround for this problem is "turning CSS modules off with options.modules = false".  Can this be completed with modifyWebpackConfig in gatdby-node.js ? Any examples on how to do this?

**Comment by cmsbased** [comment]
Just an update. I had no luck with `modules: false` and  `minimize: false` options in webpack config. This problem persisted for many months, so I will be just replacing the grid itself.
