### ISSUE TITLE
Improve GraphQL reference docs page

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#4333]
On https://www.gatsbyjs.org/docs/graphql-reference/ the GraphiQL instances are a bit cramped for space, there are a couple of things that could be done to give them more room:

- [ ] Increase their width beyond the default content width ([mockup](https://github.com/gatsbyjs/gatsby/pull/4143#issuecomment-369764539))
- [ ] Add a 'pop-out' link below each one ([ref](https://github.com/gatsbyjs/gatsby/pull/4143#issuecomment-369764218))

Would it be possible to create a remark plugin that auto-generates pop-out links for iframes?

Refs: https://github.com/gatsbyjs/gatsby/pull/4143#issuecomment-369764218

**Comment by KyleAMathews** [comment]
100% possible for the iframe plugin. It'd just iterate through iframes and you could extend any that are graphiql links. @bvaughn's plugin does something very similar https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-remark-code-repls
