### ISSUE TITLE
Markdown from repository 

### ISSUE THREAD

**Issue by tonihauptcc** [gatsbyjs/gatsby#4336]
## Description

Here is the way I want to go. I had created a system wich is able to generate and edit markdown files. The generated folder for content is published to a content directory. Below this there are several subfolders like pages, collections, assets, galleries and so on.

Now I want to point the source file system to grab my git repo and parsing down with remark and so on this version controlled folder.

Every time the editor is editing the files or updates or publishes a hook is triggered wich will push it to the content repository. Than another hook is triggered wich tells my so called gatsby service to rebuild the site with the newly added content from the content repo. Right now I just could say take local MD files but not from any remote repo. Is there some best practice or some advices how to deal with such a scenario?

### Environment

Gatsby version:
Node.js version:
Operating System:

### File contents (if changed):

`gatsby-config.js`: 
`package.json`: 
`gatsby-node.js`: 
`gatsby-browser.js`: 
`gatsby-ssr.js`: 

### Actual result

What happened.

### Expected behavior

What should happen?

### Steps to reproduce

1\.

2\.

3\.

...

**Comment by KyleAMathews** [comment]
Perhaps you can pull the markdown using https://www.npmjs.com/package/gatsby-source-github-api?

**Comment by NoopDog** [comment]
@tonihauptcc did  the gatsby-source-github-api work out for your or did you end up using something else? Thanks!
