### ISSUE TITLE
gatsby.com links do not work 

### ISSUE THREAD

**Issue by lau32** [gatsbyjs/gatsby#4340]
## Description

When accessing the gatsby.com website none of the links work. This issue seams to have apeared today.
Yesterday everything was working fined.
It seams it tries to access pathname of undefined as you can see from the attached image.

![image](https://user-images.githubusercontent.com/8844319/36918562-fa51bb10-1e62-11e8-9efa-7015eb619283.png)

**Comment by KyleAMathews** [comment]
Thanks for the issue — fixing it in https://github.com/gatsbyjs/gatsby/pull/4339

Forgot it'd be live already :-( I just reverted the deployed version to one that's working

**Comment by lau32** [comment]
Ok, thanks for the quick fix:D
