### ISSUE TITLE
Use microbundle to bundle all browser code

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#4345]
It does a great job shrinking down code to the smallest possible size.

Could use it to build all code in cache-dir as well as gatsby-image and gatsby-link

https://github.com/developit/microbundle

**Comment by anjawaldbauer** [comment]
@KyleAMathews For v2 only, or should this land on master?

**Comment by KyleAMathews** [comment]
This could land on master still. It should be pretty simple change and port directly to v2.

**Comment by VernL** [comment]
I tried using microbundle to build gatsby-image and gatsby-link and ran into a mysterious error:  "TypeError: Cannot read property 'type' of undefined".

**Comment by tryzniak** [comment]
Microbundle has a few issues open, like [1](https://github.com/developit/microbundle/issues/86), [2](https://github.com/developit/microbundle/issues/97), that makes hard/impossible to tackle this issue until they're fixed.

**Comment by KyleAMathews** [comment]
Hmm yeah, thanks for the info @tryzniak.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
