### ISSUE TITLE
Navigating issue with creating client paths plugin

### ISSUE THREAD

**Issue by varakumar1105** [gatsbyjs/gatsby#4346]
## Description

Navigating issue with creating client paths plugin. I am using components from components folder instead of creating folders in pages/page/ path. 

It is rendering 404 page first and then talking to correct page in after prod build. Can you help me out of this? 

### Environment

Gatsby version: 1.1.34
Node.js version: v7.8.0
Operating System: Linux

### File contents (if changed):

`gatsby-config.js`: 
   {
      resolve: `gatsby-plugin-create-client-paths`,
      options: { prefixes: [`/sample-page/*`] }
    } 
`package.json`: 
   "gatsby-plugin-create-client-paths": "1.0.5"

...

**Comment by m-allanson** [comment]
@varakumar1105 Can you try updating all your packages to the latest versions?

**Comment by chinmayakcv** [comment]
@m-allanson : I observed that 404 page is shown till `onInitialClientRender` is called

**Comment by varakumar1105** [comment]
We configured server routing to eliminate this issue. Our server is serving 404.html when route was not found

**Comment by acerbetti** [comment]
I'm seeing the same issue. How did you solve it?
