### ISSUE TITLE
gatsby-ssr.js: `onRenderBody` pathname property (how to access?)

### ISSUE THREAD

**Issue by benjaminhoffman** [gatsbyjs/gatsby#4350]
## Description
I'm almost embarrassed to ask because surely I'm accidentally overlooking something super obvious here (sorry!) but I have a quick question about `gatsby-ssr`'s `onRenderBody` method.  Shouldn't it return `pathname`?  Using Gatsby's example site, I log out the first param of `onRenderBody`.  I don't see the `pathname` in the output.  See below.

docs: https://www.gatsbyjs.org/docs/ssr-apis/#onRenderBody

### Environment

Gatsby version: 1.9.222
Node.js version: 9.5.0
Operating System: Mac OS

<img width="1625" alt="screen shot 2018-03-03 at 12 33 48 pm" src="https://user-images.githubusercontent.com/6520022/36939056-c00b3940-1edf-11e8-85e0-93c1bae3c63f.png">

**Comment by KyleAMathews** [comment]
The pathname is only set during builds. In development, it's not set because we do just one server render which covers all pages.

**Comment by Wendenburg** [comment]
thats a pitty since pathname is the only way to - kind of - identify what page you are currently rendering. So e.g. onRenderBody offer a lot of options to manipulate html.js, but in develop there are no infos available what manipulation you need to do for the current page. Always have to hardcode it...

**Comment by Johnrobmiller** [comment]
> The pathname is only set during builds. In development, it's not set because we do just one server render which covers all pages.

This describes the problem, which is a very good start.  However, does anybody know of any solutions?

**Comment by rimx** [comment]
> > The pathname is only set during builds. In development, it's not set because we do just one server render which covers all pages.
> 
> This describes the problem, which is a very good start. However, does anybody know of any solutions?

did you find a solution?
