### ISSUE TITLE
Handle Deleting of Files Properly w/ GraphQL, etc

### ISSUE THREAD

**Issue by bradennapier** [gatsbyjs/gatsby#4351]
## Description

If you delete or rename markdown pages right now you can not get rid of them and errors pop up even if you restart `gatsby develop`.  Only way to fix it appears to be to delete everything and start over (`.cache` and `public` folders).  

Perhaps cleaning the cache should be done in some way?  It still thinks these posts exist many hours after they are completely removed.

I had assumed maybe there was a `gatsby clean` or `gatsby purge` but I didn't see it so it would appear this would break forever for anyone that did't know they had to manually delete those folders on every change?

### Steps to reproduce

1\. Make Markdown File in `gatsby-advanced-starter` but any should work as the gatsby node config doesnt re-run and/or runs in cache (dont know really with the magic that happens)

2\. Delete it

3\.It still exists on reloads in the graphql database

...

I get these errors because it is thinking a bunch of files exist when I simply renamed or deleted them.

![image](https://user-images.githubusercontent.com/15365418/36941555-0d2c62c0-1f13-11e8-8ea4-bbbf31714239.png)

**Comment by KyleAMathews** [comment]
Are you on the latest version of gatsby? Thanks spent nearly a day on this very issue a few weeks ago :-)

**Comment by bradennapier** [comment]
I believe I am unless it came out like a day ago.  Will be *awesome* if that is it - one moment.

**Comment by bradennapier** [comment]
![image](https://user-images.githubusercontent.com/15365418/36941694-027e4b2e-1f16-11e8-8481-5786021bc3c6.png)

Nope.. reinstalled gatsby completely and on version `gatsby@1.9.222` and still the "Node Guides" there is rendering and I deleted that file about 8 hours ago.  Only fix is to delete `.cache` and `public` manually

**Comment by bradennapier** [comment]
oof - just noticed tons of errors - yall need a `gatsby clean` to clear the cache and public or something.  Looks like updating versions made it break since it was reading cache which was now invalid?

**Comment by KyleAMathews** [comment]
Those errors are React errors... it's not necessarily something Gatsby is doing. I'll look at gatsby-advanced-starter and see if I can reproduce this really quick.

**Comment by KyleAMathews** [comment]
We aim towards the cache being 100% accurate. A cache you have to clean all the time is useless.

Would love it if you could help me figure out why this is happening so we can solve it!

**Comment by KyleAMathews** [comment]
I just installed the starter and ran `yarn why gatsby` and it said the version of Gatsby is 1.9.178 — which means it doesn't have any of the new fixes for handling deleting files.

Can you double-check what version you're on?

**Comment by bradennapier** [comment]
I updated to the package shown in the post above.  The errors were react but they were a result of the query returning data about files that no longer exist.

**Comment by KyleAMathews** [comment]
I've replicated the bug — looking into why it's happening.

**Comment by bradennapier** [comment]
Great!  Also happens when I move them into different folders as well.  Seems it just needs to run a new query on the overall file contents when certain things occur.

**Comment by KyleAMathews** [comment]
Just put up a PR which *should* fix this. I'm feeling a bit gun-shy given I thought I'd fixed this once or twice before 😅 But I improved the tests + manually tested this a bunch so I think I've wrapped my head around the problem and the solution is correct.

Will merge and release once tests pass.

**Comment by KyleAMathews** [comment]
Thanks for reporting the issue! And sorry for the frustration!

**Comment by bradennapier** [comment]
Sweet!  Thank you for working on this so quickly!  It's a bit hard to work out the magic Gatsby does but overall everything is pretty well put together!  It definitely manages the details very well!

**Comment by bradennapier** [comment]
Sorry to say now deleting files crashes Gatsby

```
 DONE  Compiled successfully in 808ms                                                                                                                                                                                                                                   02:32:37

file deleted at /exchange_services.md
error UNHANDLED REJECTION


  TypeError: Cannot read property 'type' of undefined

  - page-query-runner.js:127
    /[gatsby]/src/internal-plugins/query-runner/page-query-runner.js:127:47

  - Array.reduce

  - page-query-runner.js:124 findDirtyIds
   [gatsby]/src/internal-plugins/query-runner/page-query-runner.js:124:13
```

**Comment by m-allanson** [comment]
@bradennapier I'm not able to replicate that error, deleting a markdown file gives me output like:
```
info file deleted at /Users/m-allanson/gatsby/examples/using-remark/src/pages/2017-03-21---copy-linked-files-intercepting-local-links/index.md

 WAIT  Compiling...                                                                                             14:18:17

 DONE  Compiled successfully in 349ms                                                                           14:18:18

 WAIT  Compiling...                                                                                             14:18:18

 DONE  Compiled successfully in 121ms
```

Could you try out the [_Using remark_](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-remark) example and see if you still get that unhandled rejection error? You'll need to upgrade it to use the latest version of Gatsby.
