### ISSUE TITLE
[v2]: Error: 'load-babel-config must pass options to "setBabelOptions"'

### ISSUE THREAD

**Issue by lettertwo** [gatsbyjs/gatsby#4370]
## Description

Custom `.babelrc` causes a validation error.

### Environment

Gatsby version: 2.0.0-alpha.8
Node.js version: 8.9.3
Operating System: OSX 10.13.3

### File contents (if changed):

Just a custom `.babelrc`:
```json
{
  "cacheDirectory": true,
  "babelrc": false,
  "presets": [
    ["@babel/preset-env", {
      "loose": true,
      "modules": false,
      "useBuiltIns": "usage",
      "sourceType": "unambiguous",
      "shippedProposals": true,
      "targets": {
        "browsers": [
          "> 1%",
          "IE >= 11",
          "last 2 versions"
        ]
      }
    }],
    ["@babel/preset-react", {
      "useBuiltIns": true,
      "pragma": "React.createElement"
    }],
    "@babel/preset-flow"
  ],
  "plugins": [
    ["@babel/plugin-proposal-class-properties", {
      "loose": true
    }],
    "@babel/plugin-syntax-dynamic-import",
      ["@babel/plugin-transform-runtime", {
      "helpers": true,
      "regenerator": true,
      "polyfill": false
    }],
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-export-default-from"
  ]
}
```
### Actual result

It seems [load-babel-config](https://github.com/gatsbyjs/gatsby/blob/ea72ace7cad11e6b45e77809989f2b07a01e1acc/packages/gatsby/src/internal-plugins/load-babel-config/gatsby-node.js) correctly [loads](https://github.com/gatsbyjs/gatsby/blob/ea72ace7cad11e6b45e77809989f2b07a01e1acc/packages/gatsby/src/internal-plugins/load-babel-config/gatsby-node.js#L128-L131) and [uses](https://github.com/gatsbyjs/gatsby/blob/ea72ace7cad11e6b45e77809989f2b07a01e1acc/packages/gatsby/src/internal-plugins/load-babel-config/gatsby-node.js#L135) the custom babel config like:
```js
{
  cacheDirectory: true,
  babelrc: false,
  presets: [...],
  plugins: [...]
}
```

Which is [pared down](https://github.com/gatsbyjs/gatsby/blob/ea72ace7cad11e6b45e77809989f2b07a01e1acc/packages/gatsby/src/internal-plugins/load-babel-config/gatsby-node.js#L79) to:
```js
{
  cacheDirectory: true,
  babelrc: false
}
```

That value is then passed to the [setBabelOptions](https://github.com/gatsbyjs/gatsby/blob/ea72ace7cad11e6b45e77809989f2b07a01e1acc/packages/gatsby/src/redux/actions.js#L839) action creator, which [describes](https://github.com/gatsbyjs/gatsby/blob/ea72ace7cad11e6b45e77809989f2b07a01e1acc/packages/gatsby/src/redux/actions.js#L835-L837) accepting options in this form, but seems to [actually expect](https://github.com/gatsbyjs/gatsby/blob/ea72ace7cad11e6b45e77809989f2b07a01e1acc/packages/gatsby/src/redux/actions.js#L853-L859) a nested `options` object, like:
```js
{
  options: {
    cacheDirectory: true,
    babelrc: false
  }
}
```

### Steps to reproduce

1\. Add a `.babelrc` to the project root

2\. run `gatsby build`

**Comment by KyleAMathews** [comment]
Thanks for the bug report + reproduction instructions! Fixed the bug in #4381
