### ISSUE TITLE
Hover states for definitions and hints

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#4372]
## Description

It would be great to be able to add more information to some words on the Gatsby site. Some examples of why this would be useful:

- Have gotten some feedback that the plugin cards can look crowded with too many statistics. With hover states (like npms.org), it would look cleaner and still provide the same information.
- It's a well-researched phenomenon that too many hyperlinks and information that is not immediately useful gets in the way of learning for true beginners. So hover states would allow them to get more information if they want to or feel ready.

### Help needed

I'm not sure hover states is the best way to do this. This isn't a critical priority, just an idea for an enhancement that would make things visually cleaner and more up-to-date with modern learning theories. Open to other ideas!!

**Comment by KyleAMathews** [comment]
Interesting idea. HTML has the [abbreviation tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr) which we could add support to our markdown for:

https://github.com/zestedesavoir/zmarkdown/tree/master/packages/remark-abbr#syntax

**Comment by jlengstorf** [comment]
+1 for abbreviation tags. Using `abbr` would be great for acronyms.

Another idea might be to just create a glossary of terms so we can link the first usage on any page to its glossary entry. This would allow us to add more detail (e.g. examples, further reading links) without hiding a bunch of info in tooltips.

From an accessibility standpoint, we'd also want to be careful about what's added inline. `abbr` is semantic, so it's no problem, but anything more involved could make it weird/difficult to read using a screen reader.

**Comment by KyleAMathews** [comment]
Ooo yeah, doing just the first usage is better. This would be easy to automate. And yeah, a glossary page we link to would be perfect. We could use abbr and then add js to drive a pop-up that would have a link to the glossary page where optionally we include a richer/longer description.

**Comment by shannonbux** [comment]
Hm, interesting ideas. Your ideas have got me thinking about how to determine which words to even define. Might be something to outline in a style guide, like "anything people can't easily find in google (or can't be found easily, in the form we like, ought to be defined in a glossary"? 
We might just have to go with gut instinct on this for the time being, although usability testing will likely reveal a lot about this (from the 3 people I've observed so far, they were pretty vocal about "huh, I don't know what this word means."
