### ISSUE TITLE
[docs] Add linkable API reference

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#4377]
The existing API reference (e.g. https://www.gatsbyjs.org/docs/browser-apis/) is helpful, but sometimes it's tricky to find things like a function signature (this is a major complaint I have about most docs sites).

In my opinion, the Right Way™ to do docs is how PHP and jQuery do it: I can type in php.net/function_name or api.jquery.com/function_name and get a full reference for the signature + examples. (E.g. http://php.net/strtr and http://api.jquery.com/add/)

Gatsby is mostly there, but if I find a snippet of code that shows me `exports.onCreateNode = ...`, I'm not sure how to find that on the existing Gatsby site and would likely end up Googling "gatsby oncreatenode" to find it.

I think we could borrow ideas from PHP/jQuery (two extremely beginner-friendly technologies) to make Gatsby's docs a really excellent getting started experience for devs.

## A couple permalink structure ideas:

- `https://gatsbyjs.org/onCreateNode`
- `https://gatsbyjs.org/api/onCreateNode`

### Option 1: Updated API-specific redirects

My personal preference is to put each function on its own page. We could add redirects so the the permalink structure stays simple to type, but the deep link communicates more information:

- `https://gatsbyjs.org/api/onCreateNode` => `https://gatsbyjs.org/api/node/onCreateNode`
- `https://gatsbyjs.org/api/onClientEntry` => `https://gatsbyjs.org/api/browser/onClientEntry`

#### The advantages of this are:

- The URL is extremely clear about what you're looking at
    - It's clear from the URL these are API docs for the Node function `onCreateNode`)
    - It's less clear that `https://www.gatsbyjs.org/docs/api-specification/` is an explanation of the concepts behind the idea and `https://www.gatsbyjs.org/docs/browser-apis/` is actually API documentation
- It's extremely clear what's being linked to
    - In issues or chat, linking to a page with multiple things on it can sometimes be confusing. This is a minor thing, but one that has tripped me up in the past.

#### The disadvantages are:

- We'd need to change logic in `gatsby-node.js` for gatsbyjs.org to support this
- I'm not sure how easy it will be to redirect anchor links to the appropriate pages
    - If this isn't easily possible, we'd need to rewrite the docs at `https://www.gatsbyjs.org/docs/browser-apis/` et al. to link to the new API docs, which might be inconvenient for people arriving from older links to the docs.

### Option 2: Redirect to existing anchor links

If we keep the existing structure, we can redirect to the anchors:

- `https://gatsbyjs.org/api/onCreateNode` => `https://www.gatsbyjs.org/docs/node-apis/#onCreateNode`
- `https://gatsbyjs.org/api/onClientEntry` => `https://www.gatsbyjs.org/docs/browser-apis/#onClientEntry`

#### The advantages of this are:

- No need to change the underlying structure of the site
- This would be really fast to implement

#### The disadvantages are:

- As the APIs expand in the future and more examples are added, these pages will become unwieldy.
- This is subjective, but I think there's an advantage to separating conceptual "why" and "how" docs from practical/reference docs. I'd love to see reference docs under `/api` and conceptual/instructional docs under `/docs`.
    - I see this as a similar difference between https://www.gatsbyjs.org/docs/ and https://www.gatsbyjs.org/tutorial/

## Questions to the Gatsby community:

1. Does the idea of a predictable URL structure for quickly looking up Gatsby function references seem valuable to people other than myself?
2. Do you have an immediate reaction and/or preference to Option 1 vs. Option 2?
3. Do you see a benefit in separating reference (API) docs from other types of docs via URL (e.g. `/api/` vs. `/docs/`)?

**Comment by KyleAMathews** [comment]
I think there's a lot of value to having all the APIs listed in one place as often when you're new to Gatsby (or even have a plugin or two under your belt) it's hard to know which one to use so browsing through all the APIs e.g. for the browser is really helpful in quickly getting up to speed.

I can see the value for sure in separating why & how. I wonder though if the two are too tightly connected here e.g. if you explain "why" an API is a given way, you've basically re-written its description.

The pace of new APIs has slowed down a ton. I'm not sure we'll be adding that many more so the pages even growing by 25% over the next couple of years seems somewhat unlikely. Could be wrong though...

**Comment by gillkyle** [comment]
It's been helpful to me seeing several of the APIs listed side by side in the same palce, sometimes I have an idea of what I need to be looking for and I can sort of peruse the page of browser or node APIs to find exactly what one I need to be referencing. 

Maybe I just haven't paid a lot of the attention to the URL as I'm navigating through the site or I haven't had a lot of links to docs sent to me. ¯\_(ツ)_/¯

**Comment by jlengstorf** [comment]
That makes a lot of sense — thanks @KyleAMathews and @gillkyle!

Regarding this comment:

> I wonder though if the two are too tightly connected here e.g. if you explain "why" an API is a given way, you've basically re-written its description.

I think I may have made that description of "how" vs. "why" too squishy. What I meant to say is that I think it's helpful to distinguish with URLs that a page is intended to be a reference vs. being a guide or an architectural write-up.

In my experience, I like to read the philosophy of a project when I'm first researching it, but afterward I just want to find the function names, their parameters, and the expected return values + examples of usage. The description of the API can absolutely include some of the history behind why it exists in its current form — I didn't mean to suggest we change the way the APIs are currently written up or add a new section.

But I do think there's value in separating the architectural docs (e.g. https://www.gatsbyjs.org/docs/api-specification/) from the actual reference pages using a URL structure.

(@shannonbux has already talked about updating the information architecture of the docs, so I'll leave that full discussion to another thread.)

Based on that feedback, let me update with a third option:

### Option 3: Keep the existing path structure, but relocate to a new path

We can keep the pages themselves as-is, but move them to a new URL that makes it a reference doc.

- `https://gatsbyjs.org/api/onCreateNode` => `https://www.gatsbyjs.org/api/node/#onCreateNode`
- `https://gatsbyjs.org/api/onClientEntry` => `https://www.gatsbyjs.org/api/browser/#onClientEntry`

#### The advantages of this are:

- Simple to implement
- Clear communication of what info the URL contains
- Keeps all related APIs in one place

**Comment by KyleAMathews** [comment]
I think option 3 would work great!

**Comment by KyleAMathews** [comment]
Oh! I forgot about this idea but a while ago I was thinking how cool it'd be to link from each API to plugins that are using that API. e.g. `onClientEntry -> 17 open source plugins use this API ..., ..., ...`

**Comment by shannonbux** [comment]
@jlengstorf thanks for reminding me to check if I've created an issue about improving IA. I did a review of the current IA that I'll post to kick off an overall discussion.

I think the separation between the "why" and "how" is important. From educational psychology research, experts typically need reference docs that are easily scannable and searchable. They don't need step-by-step instructions.

So it makes sense to me that anything we can do to make it easier for people to find what they're looking for is a great idea for experts. 

For beginners, they need organization and structure, and a long list of unorganized docs, guides, or even a list of function names is not helpful because they have no way of knowing how to conceptually organize those things. Will continue this discussion in issue about IA.

**Comment by jlengstorf** [comment]
I won't have time to pick this up in the next week or two, but I need to:

- [ ] Convert this issue into an RFC
- [ ] Extend the scope to include adding all possible arguments for each function

**Comment by hsribei** [comment]
Adding to the why/how separation, I like how React's docs are structured. There's a clear `Reference` section where it's just a list of APIs, and everything else is much more "guide-like".

**Comment by jlengstorf** [comment]
Reopening this — we should still do this.

**Comment by moonmeister** [comment]
@jlengstorf Is it me or has this been done? Can we close this?

https://www.gatsbyjs.org/docs/browser-apis/#onInitialClientRender

**Comment by jlengstorf** [comment]
Kinda. Good enough, I guess.
