### ISSUE TITLE
Add onPostInstall extension hook

### ISSUE THREAD

**Issue by rgbkrk** [gatsbyjs/gatsby#438]
All the base setup is there, and I'd love to see this `git init` if it can.

**Comment by KyleAMathews** [comment]
This is for starters? Setting up a git repo seems a bit too opionated as the end user might not have git installed or might want to use hg etc.

The next version of Gatsby will have plugin support plus more extension APIs. One could be onPostInstall at which point for a custom starter/theme you could create a git repo.

**Comment by rgbkrk** [comment]
As a big user of git, I had no problem taking these steps:

```
git init
git add .gitignore
git status # Figure out what should be added directly
git add STUFF
```

However, I'd love to not have to walk others through that and have it be automated.

**Comment by KyleAMathews** [comment]
For sure, I totally see the use case but I just don't think it should be
the default.

Are you creating a starter right now?

**Comment by rgbkrk** [comment]
Not yet, this was the first "pain point" I experienced in starting out with gatsby and thinking of follow on users. This is pretty exciting stuff, thanks for building it!

**Comment by KyleAMathews** [comment]
Ah cool! Yeah, I can imagine a "Github plugin" which installs a starter, creates a git repo, creates repo on Github, pushes the initial commit, then does an initial gh-pages install. That'd be ++.

a `onPostInstall` extension should definitely be added so I'll change the title of this issue to that.

Thanks for the pain report! Keep them coming. Working on turning Gatsby from a cool hack to a full-fledged product so use case ideas are super helpful.

**Comment by rgbkrk** [comment]
Alright friendly bot I’ll close it
