### ISSUE TITLE
if I have a static page make with react-static, can I make the static web to dynamic

### ISSUE THREAD

**Issue by kavanLi** [gatsbyjs/gatsby#4380]
1. if I have a static page make with react-static or gatsby, I want to add something dynatmic a few month later. Can I make the web to dynamic, in other words, to write some javascript or jQuery to add eventListner or ajax request?And Is that react-static or gatsby can integrate with react to solve this problem?

2. Is that gatsby can't biuld with SEO?

3.
![image](https://user-images.githubusercontent.com/33696428/37008029-2de11f4c-211b-11e8-8b84-5091879b6cf5.png)
![image](https://user-images.githubusercontent.com/33696428/37008032-30dcbed6-211b-11e8-8833-725abfdf608c.png)
I need to develop a static website like the above image, this static web may have 15 pages. Can I use react-static or gatsby to make it out? And whick one is best? or those things are not good, just use html + bootstrap4 to achive the goal? or there is aother technich that I can use?

These is my question? Can anyone familiar to static web can answer me? Thanks in Advanced.

**Comment by KyleAMathews** [comment]
Gatsby is obviously the best.

Gatsby loads your React into the client so you could do everything you normally do with React.

Gatsby generates full HTML pages so works great for SEO.

Good luck!

**Comment by kavanLi** [comment]
thanks again. but, there is a thing that I don't understand. Is that The gatsby and react-static are developed by same team? What is the main diff with each other? Thanks in advanced.
