### ISSUE TITLE
What the main diff between gatsby and react-static? whick one should I use?

### ISSUE THREAD

**Issue by kavanLi** [gatsbyjs/gatsby#4383]
There is a thing that I don't understand. Is that The gatsby and react-static are developed by same team? What is the main diff with each other? Thanks in advanced.

**Comment by m-allanson** [comment]
Hey @kavanLi Gatsby and react-static are developed by different teams. 

As for which one to use - Gatsby people might tell you Gatsby is the best and react-static people might tell you react-static is the best.  You should try them both and see which you prefer. The [Gatsby tutorial](https://www.gatsbyjs.org/tutorial/) is a great place to get started.
