### ISSUE TITLE
Polishing Plugin library

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#4394]
## Description

The plugin library is in dark deploy, thanks to @gillkyle and many others! 
This fixes Issue #3003.  

Next steps based off of discussions w/ @fk, @KyleAMathews, and @calcsam.
 @KyleAMathews do these things?
- [x] Make sure deprecated packages are not appearing in plugin search
- [x] Support searching for `gatsby-library` in addition to `gatsby-plugin` and `gatsby-component`
- [x] Add "gatsby-plugin" keyword to package.json where missing
- [x] show total count of plugins w/o any search
- [x] script fetching all community plugins to find which ones aren't in the library and then PR adding keyword to them

@jlengstorf do this:
- [x] Template for plugin READme's (#4284 thanks @jlengstorf) and can we make sure people know (possibly thru template and plugin instructions you wrote) that they need to use gatsby-plugin as a keyword, since Algolia search uses this?
- [x] Add instructions to the page for plugin authors about how to get their plugin to show up  — namely
  - [x] add "gatsby-plugin" as keyword 
  - [x] wait 24 hours while Algolia reindexes

@fk do this:
- [x] Fix bug in Safari https://twitter.com/ARasheedPhoto/status/971407215553781761
- [x] Design enhancements
- [x] send mobile icon to Shannon
- [x] redirect `/plugins/` to `/packages/`

Shannon do this:
- [x] Figuring out _where_ the plugin library ought to reside and how to navigate there on gatsbyjs.org ("Packages on top nav desktop and bottom nav in mobile) --> edit plugin docs page to redirect to packages library and plugin authoring page

Notes on possible future enhancements to the library:
- [x] Introduce filters (examples: filter by category, popularity, and what version of Gatsby the package works with)
- [x] For each plugin, include a list of open source websites from the showcase (and how many) that are using the plugin

**Comment by KyleAMathews** [comment]
Community plugins missing the "gatsby-plugin" keyword so not currently showing up in the search. Each one should have a PR adding either `gatsby-plugin`, `gatsby-component`, or `gatsby-library` as a keyword https://github.com/alampros/gatsby-plugin-accessibilityjs/pull/1

Please check them off when you've made a PR!

* [ ] https://github.com/alampros/gatsby-plugin-accessibilityjs
* [ ] https://github.com/indigotree/gatsby-plugin-bugherd
* [ ] https://github.com/Creatiwity/gatsby-plugin-favicon
* [ ] https://github.com/didierfranc/gatsby-plugin-google-fonts
* [ ] https://github.com/marcobiedermann/gatsby-plugin-svg-sprite
* [ ] https://github.com/getchalk/gatsby-plugin-meta-redirect
* [ ] https://github.com/angeloocana/gatsby-plugin-i18n
* [ ] https://github.com/rongierlach/gatsby-plugin-purify-css
* [ ] https://github.com/jlengstorf/gatsby-remark-numbered-footnotes
* [ ] https://github.com/kevzettler/gatsby-source-airtable
* [ ] https://github.com/Rulikkk/gatsby-remark-emoji
* [ ] https://github.com/jcreamer898/gatsby-plugin-typescript-css-modules
* [ ] https://github.com/pixelstew/gatsby-paginate
* [ ] https://github.com/jedidiah/gatsby-source-soundcloud
* [ ] https://github.com/angeloashmore/gatsby-node-helpers
* [ ] https://github.com/jedidiah/gatsby-source-twitch
* [ ] https://github.com/G100g/gatsby-source-twitter
* [ ] https://github.com/infinitedescent/gatsby-pagination
* [ ] https://github.com/atrauzzi/gatsby-plugin-protoculture

**Comment by KyleAMathews** [comment]
cc-ing repo owners if you want to fix things yourselves :-D @alampros @crgeary @julien1619 @didierfranc @marcobiedermann @dannywils @angeloocana @rongierlach @jlengstorf @kevzettler @Rulikkk @jcreamer898 @pixelstew @Jedidiah @angeloashmore @G100g @haysclark

**Comment by jcreamer898** [comment]
Thanks for the heads up!

**Comment by crgeary** [comment]
Thanks! Mine `gatsby-plugin-bugherd` has been updated.

**Comment by rongierlach** [comment]
The deed is done -- `gatsby-plugin-purify-css`

**Comment by Rulikkk** [comment]
`gatsby-remark-emoji` updated with keywords. Thanks.

**Comment by dannywils** [comment]
`gatsby-plugin-meta-redirect` has been updated

**Comment by fk** [comment]
I added a PR #4472 'Replace main navigation item "Community" with "Plugins"' over the weekend, preview here: https://deploy-preview-4472--gatsbyjs.netlify.com/

**Comment by fk** [comment]
Hey @jacobmischka, want to tag https://github.com/jacobmischka/gatsby-plugin-react-svg/?

**Comment by DirtyF** [comment]
keyword added on https://github.com/didierfranc/gatsby-plugin-google-fonts

**Comment by DirtyF** [comment]
@KyleAMathews all listed plugins have now a PR to add the missing keyword ✅

**Comment by didierfranc** [comment]
@DirtyF merged and published ;)

**Comment by jacobmischka** [comment]
@fk Will do!

**Comment by fk** [comment]
Wow, thanks @DirtyF! 
Thanks @jacobmischka!
 🙏 🤗

**Comment by angeloashmore** [comment]
Merged PR into `gatsby-node-helpers`. Thanks @DirtyF!

**Comment by marcobiedermann** [comment]
Merged in https://github.com/marcobiedermann/gatsby-plugin-svg-sprite/pull/2 for `gatsby-plugin-svg-sprite` by @DirtyF

**Comment by lowmess** [comment]
@jlengstorf Opened #4622 before seeing this issue and that the task was already on your roadmap. feel free to adjust/suggest wording or close the issue if it's not what was in mind.

**Comment by nihgwu** [comment]
I think we should support versioned plugin, I'm planning publish some of my own plugins but realize that they are for Gatsby V2

for example packages for Sublime Text
![image](https://user-images.githubusercontent.com/2595058/37646850-b9ce89b8-2c65-11e8-8627-512808a2a411.png)

**Comment by m-allanson** [comment]
@lowmess @jlengstorf I merged #4622 and checked it off at the top of this issue.

**Comment by shannonbux** [comment]
@nihgwu Can you explain more about this? Do you mean you want the plugin library to show what version of Gatsby the plugin is compatible with?

**Comment by nihgwu** [comment]
@shannonbux exactly

**Comment by shannonbux** [comment]
@KyleAMathews just updated your checklist to reflect that PR's have been made and/or merged for the entire list of plugins! Wait to go everyone.

@fk and @jlengstorf what do we have left to do to close this issue? Are your checklists at the top of this issue updated? Happy to help where I can.

**Comment by jlengstorf** [comment]
@shannonbux I need to write the README template still, and I haven't done anything about the Algolia notes. 

I also think we discussed keeping plugins instead of packages even though it's technically more than plugins. 

Maybe those should be tracked in separate issues (the README already is) and close this?

**Comment by shannonbux** [comment]
will do tomorrow! Thanks!

**Comment by KyleAMathews** [comment]
Fun being able to regularly see the count of plugins now — we're already up 8-10 or so since we launched the library

**Comment by shannonbux** [comment]
@nihgwu Just created an issue to add filters to plugin library, which would include version compatibility! Thanks!

**Comment by shannonbux** [comment]
Ok closing this issue because I turned the remaining tasks into smaller issues in the UX project.

- Maintain light purple selected state in plugin library #4670
- Plugin library filters and sorting enhancements #4671
- Plugin library list sites that use plugin #4672
- Add Algolia notes to Plugin Authoring doc #4673
- Create READme template for plugins #4284

**Comment by muescha** [comment]
> Community plugins missing the "gatsby-plugin" keyword so not currently showing up in the search. Each one should have a PR adding either `gatsby-plugin`, `gatsby-component`, or `gatsby-library` as a keyword [alampros/gatsby-plugin-accessibilityjs#1](https://github.com/alampros/gatsby-plugin-accessibilityjs/pull/1)

@KyleAMathews 
should someone run [scripts/gatsby-plugin-checker](https://github.com/gatsbyjs/gatsby/blob/master/scripts/gatsby-plugin-checker/README.md) regulary, because i see some new plugins showing up?
