### ISSUE TITLE
[Documentation request] "Building apps with Gatsby"

### ISSUE THREAD

**Issue by zshannon** [gatsbyjs/gatsby#4395]
## Description

I'd like to see documentation examples of using React Router inside of Gatsby on the [Building apps with Gatsby](https://www.gatsbyjs.org/docs/building-apps-with-gatsby/) page eg.

### Steps to reproduce

Include an instance of `HashRouter` in a Gatsby page.

```javascript
import React from 'react'
import { HashRouter as Router } from 'react-router-dom'

export default class Page extends React.Component {
  render() {
    return (
      <div>
        <Router></Router>
      </div>
     )
  }
}
```

### Expected result

`gatsby build` should compile the app.

### Actual result

`gatsby build` crashes: `WebpackError: Hash history needs a DOM`

### Environment

- Gatsby version (`yarn list gatsby`): gatsby@1.9.209
- gatsby-cli version (`gatsby --version`): 1.1.6
- Node.js version: 8.4.0
- Operating System: MacOS 10.13.3 (17D102)

### File contents (if changed):

`gatsby-config.js`: 
```javascript
module.exports = {
  plugins: [
    {
      resolve: `gatsby-plugin-sass`,
      options: {
        camelCase: "dashes",
        precision: 8 // SASS default: 5
      }
    },
    `gatsby-plugin-netlify`,
    `gatsby-plugin-react-helmet`,
  ],
}
```

`package.json`: 
```json
{
  "dependencies": {
    "animate.css": "^3.5.2",
    "bootstrap": "^4.0.0",
    "classnames": "^2.2.5",
    "dotenv": "^4.0.0",
    "font-awesome": "^4.7.0",
    "gatsby": "^1.9.207",
    "gatsby-link": "^1.6.37",
    "gatsby-plugin-netlify": "^1.0.18",
    "gatsby-plugin-react-helmet": "^2.0.5",
    "gatsby-plugin-sass": "^1.0.16",
    "golden-sdk": "link:./golden-sdk",
    "jquery": "^3.3.1",
    "moment": "^2.20.1",
    "popper.js": "^1.12.9",
    "prop-types": "^15.6.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-fontawesome": "^1.6.1",
    "react-helmet": "^5.2.0",
    "react-mobile-store-button": "^0.0.3",
    "react-moment": "^0.7.0",
    "react-router-dom": "^4.2.2",
    "react-transition-group": "^2.2.1",
    "reactstrap": "^5.0.0-beta"
  },
  "license": "UNLICENSED",
  "scripts": {
    "build": "NODE_ENV=production gatsby build",
    "deploy": "NODE_ENV=production gatsby build && netlify deploy",
    "develop": "gatsby develop",
    "format": "prettier --trailing-comma es5 --no-semi --single-quote --write \"src/**/*.js\"",
    "start": "gatsby develop",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "babel-preset-es2017": "^6.24.1",
    "netlify-cli": "^1.2.2",
    "prettier": "^1.10.2"
  }
}
```

`gatsby-node.js`: 
```javascript
const path = require('path')
const webpack = require('webpack')

exports.modifyBabelrc = ({ babelrc }) => ({
  ...babelrc,
  plugins: babelrc.plugins.concat(['transform-regenerator']),
})

exports.modifyWebpackConfig = ({ config, stage }) => {
  if (!config.plugins) config.plugins = []
  config.plugin('jquery', webpack.ProvidePlugin, [{
    '$': 'jquery',
    'jQuery': 'jquery',
    'window.jQuery': 'jquery',
    'Popper': 'popper.js'
  }])
  if (stage === 'build-html') {
    config.loader('null', {
      test: /bootstrap/,
      loader: 'null-loader'
    })
  }
  return config
}
```

`gatsby-browser.js`: 
```javascript
import 'babel-polyfill'
```

`gatsby-ssr.js`: not changed

**Comment by KyleAMathews** [comment]
Perhaps this is what you're looking for? https://github.com/gatsbyjs/gatsby/tree/master/examples/client-only-paths

**Comment by KyleAMathews** [comment]
Perhaps this is what you're looking for? https://github.com/gatsbyjs/gatsby/tree/master/examples/client-only-paths

**Comment by zshannon** [comment]
@KyleAMathews doesn't seem to be. Adding this to `gatsby-node.js` doesn't change the Webpack error:
```javascript
exports.onCreatePage = ({ page, boundActionCreators }) => {
  const { createPage } = boundActionCreators
  return new Promise((resolve, reject) => {
    // Make the front page match everything client side.
    // Normally your paths should be a bit more judicious.
    if (page.path === `/`) {
      page.matchPath = `/:path`
      createPage(page)
    }
    resolve()
  })
}
```

**Comment by pieh** [comment]
@zshannon `<Router>` is already provided by gatsby up the component tree - use directly in your page `<Route>`s

**Comment by zshannon** [comment]
@pieh I'm using S3 as my webserver, so I'd like to use the `HashRouter` in my page so reloads and direct links don't 404 when S3 can't locate the correct content. Does that make sense? Is there a means to do that?

**Comment by pieh** [comment]
Ok, if that's the case then I would assume `Hash history needs a DOM` error comes from server side rendering as then we don't have access to any browser features. 

Not sure how nesting routers will work - didn't try it, but You could probably make it at least build if you either didn't use HashRouter during ssr build or replace HashRouter with StaticRouter - I think You will find more answers to this by researching `react router` and `ssr`.

**Comment by m-allanson** [comment]
@zshannon I may be misunderstanding what you're aiming for, so please ignore this if it's not appropriate :) 

When hosting on S3 I think you can configure Cloudfront to handle 404s correctly for you. e.g. see [step 3b of this article](https://hackernoon.com/hosting-static-react-websites-on-aws-s3-cloudfront-with-ssl-924e5c134455). Then you don't need to use the HashRouter at all.

**Comment by KyleAMathews** [comment]
Yeah, we don't support multiple routers so closing this. Thanks @pieh and @m-allanson for jumping in to help!

**Comment by jlleblanc** [comment]
Not sure if this addresses @zshannon's issue, but I discovered a workaround for when you really need hashlinks. (Another disclaimer: this is my first React app! I make no claims or warranties as to whether this is a wise idea, just that you can do it.) 

If you're willing to skip the router, you can access the hash values from the `props` that get passed to your component. Here's how I did it:

```javascript
const Reader = (props) => {
  let hash = props.location.hash

  if (hash === '' || hash === '#/') {
    return <TruffleFeed />
  }

  return <SingleTruffle id={hash.replace(/#\//, '')} />
}
``` 

The `TruffleFeed` component here is a list of items, while `SingleTruffle` displays a single item. The property `props.location.hash` will contain a string with the hash (if present.) For the single component, I want everything after `#/`, so I'm using the `String.replace` method to pass the `hash` property with `#/` removed.

You can see the full view here http://truffle.jlleblanc.com/reader/ with an example of a hashlink here: http://truffle.jlleblanc.com/reader/#/d1dc04c0-e1ed-477b-ab49-e94b945b00bf
