### ISSUE TITLE
Style Guide: Change "we" to "you"

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#4396]
## Context

Currently, the Gatsby tutorial and docs vary between "you" and "we". For consistency and to create a warm, friendly tone, the standard will be to use "you".

## Steps to complete this issue
Make the following changes throughout the entire www.gatsbyjs.org site.
"we" changes to "you"
"us" changes to "you"
"let's create a new directory" changes to "create a new directory"
"our" changes to "your"

## Example 

"We just built a blog using..." would change to "you just built a blog using..."

## Motivation

We decided to go with "you" because it's more accurate ("we" isn't really referring to a real "we") and still has a warm, friendly tone as opposed to the passive voice, which avoids implying a subject.

**Comment by m-allanson** [comment]
Good plan! There's a section in the [Gatsby Style Guide](https://www.gatsbyjs.org/docs/gatsby-style-guide/#general-writing-tips) that says:

> Text should use the second person (“you”) to help to give it a conversational tone.

So I guess that's another vote for "you" :)

**Comment by anabellaspinelli** [comment]
Hi @shannonbux and @m-allanson! 

I'm currently doing the tutorial and could take on the task of changing the "we"s to "you"s if you like :) 

I've already submitted a tiny PR for a change in part one of the tutorial, but I could do another one for this :) 

These are my first contributions to OSS so I'd appreciate any guidance too :)

**Comment by shannonbux** [comment]
Closing this since it's now in the style guide. During some sort of docs sprint we'll do a "make every doc match the style guide" sort of activity

**Comment by amberleyromo** [comment]
Closed in #8752
