### ISSUE TITLE
Examples using-wordpress errors

### ISSUE THREAD

**Issue by paulrobertpine** [gatsbyjs/gatsby#4398]
When I try running gatsby develop in the using-wordpress example I get the following errors at the terminal:

`
⠄ source and transform nodesThe server response was "530 Site is frozen"
No routes to fetch. Ending.

error gatsby-node.js returned an error

TypeError: Cannot read property 'allWordpressPage' of undefined

error UNHANDLED REJECTION

`
The browser will not load

**Comment by pieh** [comment]
Unfortunately wordpress example instance is frozen for now. Your best bet is to try one of Your wordpress sites (it won't work with `using-wordpress` example site as it relies on specific advanced custom fields setup )

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
