### ISSUE TITLE
Develop failing - fileAbsolutePath removed from gatsby-transformer-remark

### ISSUE THREAD

**Issue by jonavila** [gatsbyjs/gatsby#4399]
## Description

I upgraded to the latest gatsby release and I'm seeing error messages running `develop` because the `fileAbsolutePath` field was removed from gatsby-transformer-remark. 

@KyleAMathews Looks like it was removed fixing #4385
https://github.com/gatsbyjs/gatsby/commit/4faec67de67a806a27ae1fdb80be2e418e75f00c#diff-37476cc0992c8d09852786ba4d4037ffL62

Any reason why this was removed? 

### Steps to reproduce

Try to use the filed `fileAbsolutePath` in GraphQL queries

### Expected result

Expect the field `fileAbsolutePath` to exist in the GraphQL schema

### Actual result

`fileAbsolutePath` is unknown

### Environment

- Gatsby version (`npm list gatsby`):gatsby@1.9.225 
- gatsby-cli version (`gatsby --version`): 1.1.45
- Node.js version: 8.9.4
- Operating System: OS X High Sierra

**Comment by KyleAMathews** [comment]
Oh oops, that was deliberate. Let me fix it real quick. Thanks for the bug report!

**Comment by jonavila** [comment]
Awesome. Thanks for the quick fix.

**Comment by KyleAMathews** [comment]
*was not deliberate

Can't type either :-)
