### ISSUE TITLE
[v2] Cache Dir should probably be compiled down somewhat :/

### ISSUE THREAD

**Issue by jquense** [gatsbyjs/gatsby#4402]
There are some flow types in `cache-dir` babel@6 used to take care of them i think with the react-preset, v7 doesn't. We don't compile `cache-dir` having relied on letting the user's site handle it. We probably should do a pass over it to at least remove non-standard features, as well as outline in the Docs what the minimal babel setup should be (I think Kyle is already on that one)

**Comment by KyleAMathews** [comment]
Oh? Doesn't @babel/preset-flow take care of it? I haven't seen any problem running gatsby v2 sites locally.

**Comment by jquense** [comment]
Ya i don't quite understand why i wasn't seeing it before, I just hit it in https://github.com/react-bootstrap/react-bootstrap/pull/3045

**Comment by KyleAMathews** [comment]
Does that site have its own babelrc?

**Comment by jquense** [comment]
yes!

**Comment by KyleAMathews** [comment]
Well clearly my new babel loading code is doing a great job now loading your babelrc :-P

**Comment by m-allanson** [comment]
Done in #5637
