### ISSUE TITLE
[v2] Change deleteNode so it uses named arguments like rest of actions

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#4409]
This is the only action that uses two arguments — which kinda breaks some internal code which expects there to be only one argument.

**Comment by m-allanson** [comment]
Should it just accept a `nodeId`?

The current signature is:

```
deleteNode = (nodeId: string, node: any, plugin: Plugin)
```

new signature?

```
deleteNode = (nodeId: string, plugin: Plugin)
```

**Comment by KyleAMathews** [comment]
It should be `({ node }, plugin)` — we have to send the whole node object because once the node is deleted, the node passed to the action is the only record we have left so it's needed for other internal systems to respond to the deletion.

**Comment by m-allanson** [comment]
Done in #5222
