### ISSUE TITLE
[www] Bugs on new /packages library

### ISSUE THREAD

**Issue by LeKoArts** [gatsbyjs/gatsby#4411]
@fk 
I encountered some issues on the new library page on my iPhone. Made a video for you 👍 

https://drive.google.com/open?id=1Z1xytCEVPd3KGvJtr3-tisZ15DAF7W5Q

On desktop:

- [x] If I select an item and press the "Load More" the content in the middle vanishes. It should stay there and only change if I select another package
- https://www.gatsbyjs.org/packages/@andrew-codes/gatsby-plugin-elasticlunr-search
Here it says `@andrew-codes/gatsby-plugin-elasticlunr-search` instead of `gatsby-plugin-elasticlunr-search`
- The "Load More" button feels unpolished

**Comment by fk** [comment]
Thank you Lennart, will take a look now!

**Comment by fk** [comment]
Here's another bug reported via Twitter: https://twitter.com/ARasheedPhoto/status/971407215553781761

**Comment by fk** [comment]
> If I select an item and press the "Load More" the content in the middle vanishes. It should stay there and only change if I select another package

In the same ballpark: Typing in the search form _after_ selecting a package from the results, the detail view gets replaced with the initial "Welcome to the Gatsby Package Library!" view.

**Comment by fk** [comment]
#4436 hopefully addresses the most crucial of the issues you reported @LeKoArts: "Load more" and the Algolia credits show up on mobile, and the Mobile Safari overscroll issue is fixed.

In regards to `@andrew-codes/gatsby-plugin-elasticlunr-search` I don't think there's much we can/_should_ do—`@andrew-codes` simply is part of the package name: https://www.npmjs.com/package/@andrew-codes/gatsby-plugin-elasticlunr-search

Not sure how to polish the "Load more" button…more ;-) given the markup provided by `react-instantsearch`—maybe you want to give that a shot?
