### ISSUE TITLE
Add debugging info to contributing docs

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#4413]
## Description
VSCode has great built in NodeJS debugging support. @pieh has a debugging config that works for Gatsby: https://gist.github.com/pieh/c6a57b53bb4648344be53ea8b37add82

The config is probably useful for contributors, so it could be added to the [_Development Tools_ section of the contributing docs](https://www.gatsbyjs.org/docs/how-to-contribute/#development-tools).

**Comment by KyleAMathews** [comment]
Hey, we kinda did this!
