### ISSUE TITLE
Query error when I want to get ACF data [wp.com]

### ISSUE THREAD

**Issue by jarekpelczynski** [gatsbyjs/gatsby#4415]
I use wp.com with ACF Pro and ACF seems to work 
```
=== [ Fetching wordpress__wp_acf_field ] === https://public-api.wordpress.com/wp/v2/sites/****.com/acf-field
⠄ source and transform nodes -> wordpress__wp_acf_field fetched : 13
```
but... I got an error when I want to query ACF
```Cannot query field "acf" on type "wordpress__PAGE".```

**Comment by KyleAMathews** [comment]
Have you tried graphiql? Check out the schema in the docs section in the top right.

**Comment by jarekpelczynski** [comment]
@KyleAMathews yes, of course. That an error about "acf" is from GraphQL. Previously, I used a self-hosted WP and it worked until I moved to WP.com.

Probably, ACF-to-REST-API doesn't support WP.com public end-points... :(

**Comment by KyleAMathews** [comment]
Ah. A PR adding support for those would be great!

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
