### ISSUE TITLE
Dynamic Requires not working

### ISSUE THREAD

**Issue by SachaG** [gatsbyjs/gatsby#443]
I'm trying to get dynamic requires to work but I'm running into a weird issue.

The following works:

```
require("foo.md")
```

But this gives me `Uncaught Error: Cannot find module '../../data/features/foo.md'.`:

```
const path = "foo.md"
require(path)
```

How can I get dynamic requires to work?

**Comment by KyleAMathews** [comment]
Does something different happen if you do:

```javascript
const path = "./foo.md"
require(path)
```

**Comment by SachaG** [comment]
Well in my case the path is actually `../../foo.md`.

**Comment by KyleAMathews** [comment]
It's a bit hard to debug this without seeing your directory structure etc. I can't think of anything that Gatsby would be doing to cause trouble with dynamic requires.

If you haven't read over this doc that might help: https://webpack.github.io/docs/context.html

Something I've found useful in the past is finding and examining the context module that's created.

**Comment by KyleAMathews** [comment]
Also something that's tripped me up a few times is that if Webpack has trouble loading your loader then it won't tell you that. So if you've customized the markdown loader, put a console.log in there to make sure it's getting run.

**Comment by SachaG** [comment]
OK, thanks for the tips. But I can work around it so I'll probably leave it for later.

**Comment by KyleAMathews** [comment]
Ok great. I'll close this issue for now. Please reopen it if you discover it is a Gatsby caused problem.
