### ISSUE TITLE
undefined data from graphql in a component inside layout folder 

### ISSUE THREAD

**Issue by ahgharian** [gatsbyjs/gatsby#4435]
This is my first ever issue! I hope I am not making a duplicate issue. We will find out I guess. I am afraid it might be something very stupid that I am missing. 

## Description
From what I have learned gatsby treats `layout` and `pages` in a special way which you can use graphql to query your posts. Here is what I am seeing: 

query used: 
```
export const postQuery = graphql`
    query postQuery {
        allMarkdownRemark {
            edges {
                node {
                    frontmatter {
                        path
                        title
                    }
                }
            }
        }
    }
`;
```
### Steps to reproduce
❌ if you were to create a component in the `layout` folder say `Sidebar`, the query doesn't return the data to the component. 
✅  if you were to add the query to `index.js` in `layout` folder, you will get the data in your component (`TemplateWrapper`).

### Expected result
Data from graphql query is passed to the component

### Actual result
Data is undefined 

### Environment

- Gatsby version : 1.9.223
- gatsby-cli version : 1.1.45
- Node.js version: 9.3.0
- Operating System: macOS (10.13.3)

### File contents (if changed):

`gatsby-config.js`: 
```
module.exports = {
    siteMetadata: {
        title: 'Gatsby Default Starter'
    },
    plugins: [
        'gatsby-plugin-react-helmet',
        'gatsby-transformer-remark',
        {
            resolve: 'gatsby-source-filesystem',
            options: {
                path: `${__dirname}/src/pages`,
                name: 'pages'
            }
        },
        {
            resolve: 'gatsby-source-filesystem',
            options: {
                path: `${__dirname}/src/pages/components`,
                name: 'components'
            }
        }
    ]
};
```
`package.json`: not changed
`gatsby-node.js`: 
```
/**
 * Implement Gatsby's Node APIs in this file.
 *
 * See: https://www.gatsbyjs.org/docs/node-apis/
 */

const path = require('path');

exports.createPages = ({ boundActionCreators, graphql }) => {
    const { createPage } = boundActionCreators;

    const componentTemplate = path.resolve(`src/template/postTemplate.js`);

    return graphql(`
        {
            allMarkdownRemark {
                edges {
                    node {
                        frontmatter {
                            path
                            title
                        }
                    }
                }
            }
        }
    `).then(result => {
        if (result.errors) {
            return Promise.reject(result.errors);
        }

        result.data.allMarkdownRemark.edges.forEach(({ node }) => {
            createPage({
                path: node.frontmatter.path,
                component: componentTemplate,
                context: {} // additional data can be passed via context
            });
        });
    });
};
```
`gatsby-browser.js`: N/A
`gatsby-ssr.js`: N/A

Thanks for the amazing work! 🤘🏼

**Comment by KyleAMathews** [comment]
This is as expected actually. You can only write queries in layout components that are being used as layouts so layouts/index.js. 

Your `Sidebar.js` file isn't actually a "layout" as Gatsby understands it and you shouldn't have it in that folder.

Instead, query for the data that Sidebar needs in layout/index.js and then pass the data to Sidebar.

Good luck!

**Comment by ahgharian** [comment]
This is what I ended up doing last night which works but it wasn't super obvious or that I am not very bright 😁 either way thanks for the help! 👍

**Comment by KyleAMathews** [comment]
Cool! Have fun!
