### ISSUE TITLE
don't include polyfills in main bundle

### ISSUE THREAD

**Issue by JacobBlomgren** [gatsbyjs/gatsby#4439]
## Description

I noticed that 80 kb (10 kb Gzipped) worth of polyfills (core-js) are included in the common bundle, thereby penalizing modern browsers as discussed here https://webpack.js.org/guides/shimming/#loading-polyfills. Note that I might very well be missing something, but otherwise this would perhaps be something worth looking into, in the Gatsby spirit of effectiveness. In that case, I could take a look in a couple of days.

### Steps to reproduce
Just create a new project from the default starter `gatsby new gatsby-example-site`, install [webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer) `npm install --save-dev webpack-bundle-analyzer` and add the following to `gatsby-node.js`:

```
const { BundleAnalyzerPlugin } = require('webpack-bundle-analyzer');

exports.modifyWebpackConfig = ({ config, stage }) => {
  if (stage === 'build-javascript')
    config.plugin('webpack-bundle-analyzer', BundleAnalyzerPlugin);
  return config;
};

```

and the Bundle Analyzer should open a tab with the report in the default browser.

**Comment by JacobBlomgren** [comment]
What makes this even more interesting is that I had an old `report.html` webpack-bundle-analyzer file from a Gatsby project lying around, and the core-js folder was missing from the common bundle then. That build was _probably_ built in like mid-December, so it must have been introduced since.

**Comment by KyleAMathews** [comment]
Polyfills are required for Promise support https://www.gatsbyjs.org/docs/browser-support/#polyfills

We didn't use to require Promise support hence why this changed.

In v2 we'll add polyfills dynamically depending on what browsers you support + probably will be doing two builds, one focused on modern browsers and one on older browsers.
