### ISSUE TITLE
[gatsby-source-wordpress] Mention the dependency of gatsby-transformer-sharp on gatsby-image in image processing example

### ISSUE THREAD

**Issue by rbachleitner** [gatsbyjs/gatsby#4440]
## Description

Following the documentation of gatsby-source-wordpress might lead to unknown fragments like 'GatsbyImageSharpSizes' for users that don't now about gatsby-image.

### Steps to reproduce

Follow the docs for gatsby-source-wordpress without the knowledge of gatsby-image.

### Expected result

Should work as shown.

### Actual result

gatsby complains about unknown fragment 'GatsbyImageSharpSizes_withWebp'

### Environment

* Gatsby version (`npm list gatsby`):
* gatsby-cli version (`gatsby --version`): 1.1.45
* Node.js version: 9.7.0
* Operating System: Arch Linux

**Comment by pieh** [comment]
Thanks for report! Do you feel like You could make PR to address? Docs are here - https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/README.md

**Comment by rbachleitner** [comment]
I extended one line: #4441

**Comment by pieh** [comment]
PR merged, so I'll close this. Thanks!
