### ISSUE TITLE
Build generates broken links

### ISSUE THREAD

**Issue by mtabasco** [gatsbyjs/gatsby#4442]
## Description

It is possible that I am doing something very basic, but I did not find any solution in the tutorial or here.

When I run "gatsby build", resources are generated in the public directory, but when I browse the web: css, images, etc. are not loaded. Also, the links do not work, because they redirect to, for example: file: /// C: / Macbook /

When I upload the files to firebase, the same thing happens, of course.

When I try a starter project, the same behavior occurs.

What I can be doing wrong? Thank you!

### Steps to reproduce

Install a gatsby starter project and run gatsby build

### Expected result

Website runs fine.

### Actual result

When I run "gatsby build", resources are generated in the public directory, but when I browse the web: css, images, etc. are not loaded. Also, the links do not work, because they redirect to, for example: file: /// C: / Macbook /

### Environment

* Gatsby version (`npm list gatsby`): gatsby@1.9.231
* gatsby-cli version (`gatsby --version`): 1.1.45
* Node.js version: v8.9.4
* Operating System: Windows 10 Pro

**Comment by KyleAMathews** [comment]
Try running `gatsby serve` after `gatsby build` and go to the web address directed there.

**Comment by mtabasco** [comment]
Same behaviour. See the images of develop and build versions. Doesnt load CSS, JS and links fail. Thanks
![develop](https://user-images.githubusercontent.com/24628682/37193504-8845ee94-236a-11e8-92b6-6eeffeda1dbd.png)
![build](https://user-images.githubusercontent.com/24628682/37193514-94bafe4e-236a-11e8-973c-e1bef774fdf6.png)

**Comment by KyleAMathews** [comment]
You have a React error — `validateDOMNesting` — it's not a Gatsby error
