### ISSUE TITLE
[using-page-transitions] Not working in IE11

### ISSUE THREAD

**Issue by proeung** [gatsbyjs/gatsby#4445]
## Description

We're currently using the example pulled from [using-page-transitions
](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-page-transitions) to implement subtle page transitions in one of our Gatsby projects. When loading the site on IE11, none of the links are firing correctly.

### Steps to reproduce

You can reproduce by serving the build version of this example ([using-page-transitions
](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-page-transitions)) on IE11.

### Expected result

When a link is being clicked, `react-transition-group` should be fired.

### Actual result

IE11 console error - `SCRIPT445: Object doesn't support this action`

### Environment

* "gatsby": "^1.9.128",
* "gatsby-cli": "^1.1.25",
* "gatsby-link": "^1.6.39",
*  "gatsby-plugin-catch-links": "^1.0.19",
*  "react-transition-group": "^2.2.1",

**Comment by KyleAMathews** [comment]
We don't vet example sites for older browsers (just the core Gatsby code). We'd love a PR updating the example site though to work on older browsers.
