### ISSUE TITLE
Documentation for deploying in heroku creates caching problems

### ISSUE THREAD

**Issue by michelbl** [gatsbyjs/gatsby#4447]
## Description

Documentation for deploying to heroku leads to caching issues (described in #2538)

### Steps to reproduce

Follow this documentation: https://www.gatsbyjs.org/docs/deploy-gatsby/#heroku

Make a change that affects the js. The bundle is still cached by heroku for 4 hours.

### Expected result

The js bundle is updated.

### Actual result

New HTML files clash with the old bundle.

### Environment

* Gatsby version (`npm list gatsby`): 1.9.172
* Node.js version: 8.9
* Operating System: heroku

### Solution

I made a PR to document how to prevent caching: #4444

**Comment by KyleAMathews** [comment]
Fixed in #4444 (btw, lovely PR number there :-D)

**Comment by KyleAMathews** [comment]
Thanks for finding the issue and making the fix!
