### ISSUE TITLE
Run Webpack in separate process to reduce memory usage

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#445]
Some people have complained about Gatsby running out of memory on small VPSs.

I just hit the node.js built-in heap limit while building a largeish site.

Apparently by design Webpack doesn't release memory after builds so while building Gatsby sites we accumulate memory with each build. Running Webpack in a separate process would ensure the memory is reclaimed after each build https://github.com/webpack/webpack/issues/2137

**Comment by KyleAMathews** [comment]
By running webpack in separate process I mean we'd write out the config for each webpack build to a temp file and then run webpack as a child process so that when it finishes its memory gets released.

**Comment by aaronshaf** [comment]
I came here from #1829. I am having a similar problem: ~1500 pages in the site, crashes upon `gatsby development` or `gatsby build`

**Comment by szimek** [comment]
@KyleAMathews @m-allanson Any chances for some tips how to move on with this ticket? 

The blog I'm working on has 6 languages with ~600 pages in each language. During the development phase we were building only 2 languages, but now that we're finally getting closer to deployment, I've added a third one and I started getting these "JavaScript heap out of memory" errors when building HTML pages (https://github.com/gatsbyjs/gatsby/issues/1651).

It works fine for 3 languages, if I use `node --max_old_space_size=4096`, but I'm not sure if it will work with 6 languages and as we're going to add more pages, there's always a risk that at some point we'll start running out of memory. Our Jenkins worker nodes have only 2GB RAM (:sob:) and Travis CI Ubuntu Trusty environment, which we're using to run our tests, has 4GB.

**Comment by pieh** [comment]
@szimek you might be interested in checking out this PR for v2 (mainly this comment with memory usage changes) - https://github.com/gatsbyjs/gatsby/pull/4912#issuecomment-381407967

**Comment by KyleAMathews** [comment]
Perhaps still a good idea but v2 uncovered a bunch of other lower-hanging perf improvements to pick so closing for now.
