### ISSUE TITLE
gatsby-cli: rename new command to init

### ISSUE THREAD

**Issue by pravdomil** [gatsbyjs/gatsby#4451]
for example `npm` has `init` command

**Comment by KyleAMathews** [comment]
That'd definitely work as well but since we already went with `new` several years ago, there's not much reason to change now.

**Comment by pravdomil** [comment]
or make an alias

**Comment by KyleAMathews** [comment]
There's plenty of diversity in the verb used for this sort of thing, "init", "new", create", etc. If people want to make their own aliases, that'd be great.
