### ISSUE TITLE
Avoid dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by cortopy** [gatsbyjs/gatsby#4454]
Having read some source code and a few starters, I can gather that it is accepted as common practice to pass raw html to the layout component when calling `createPage`. 

However, this means using `dangerouslySetInnerHTML` in the layout component (e.g.: consuming the html field in a remark node). I would like to develop an alternative to this by using some kind of string-to-react-elements parser in `gatsy-node` like so:

```
const path = require("path");
const HtmlToReactParser = require("html-to-react").Parser;

exports.createPages = ({ boundActionCreators, graphql }) => {
  const { createPage } = boundActionCreators;

  const template = path.resolve(`src/templates/myTemplate.tsx`);
  const htmlToReactParser = new HtmlToReactParser();

  return graphql(`
    {
      Node(sort: { order: ASC, fields: [slug] }) {
        edges {
          node {
            slug
            html
          }
        }
      }
    }
  `).then(result => {
    if (result.errors) {
      return Promise.reject(result.errors[0]);
    }

    return Promise.all(
      result.data.allNodes.edges.map(({ node }) => {

        const html = node.html.map(htmlToReactParser.parse);

        createPage({
          path: node.slug,
          component: template,
          context: {
             html
          }
        });
      })
    );
  });
};

```

The big problem with this is that, as per the [docs](https://www.gatsbyjs.org/docs/bound-action-creators/#createPage), context gets passed to BOTH component and graphQL

>Context data for this page. Passed as props to the component this.props.pathContext as well as to the graphql query as graphql arguments.

GraphQL won't accept javascript (react element include `Symbol`) and it will throw.

I've not been able to find an API method that allows passing data to the layout outside of GraphQL. I guess this is by design, but I think it would be a good addition to allow passing javascript to the layout component

**Comment by KyleAMathews** [comment]
You should generally only pass into context IDs or other arguments for the component's GraphQL query.

In the component query, you query there for the HTML. You could try running `html-to-react` in the component.

Also, passing anything other than data to context also causes trouble as you found out :-)

**Comment by KyleAMathews** [comment]
If you haven't gone through this part of the tutorial, that might be useful https://www.gatsbyjs.org/tutorial/part-four/#programmatically-creating-pages-from-data
