### ISSUE TITLE
Pagination with GatsbyImageSharp

### ISSUE THREAD

**Issue by vojtechruz** [gatsbyjs/gatsby#4458]
I was able to implement pagination in gatsby-node.js by:
1. querying all posts
2. chunking them
3. creating a page for every chunk

---
However, the problem was when passing data to each page component. I figured I could do it two ways:
1. Pass all the post information since I already have it anyway
2. Pass just pages IDs and query them in the component

---
Option 1 was working well until I wanted to pass images using Gatsby image sharp. While the following query works well in components:
```

 frontmatter {
            date(formatString: "DD MMMM, YYYY")
            title
            tags
            featuredImage {
                childImageSharp{
                    sizes(maxWidth: 200) {
                        ...GatsbyImageSharpSizes_tracedSVG
                    }
                }
            }
          }
```

I got the following error when using it in the query for all posts in gatsby-node.js:

`GraphQLError: Unknown fragment "GatsbyImageSharpSizes_tracedSVG"`

I want to be able to have image thumbnails of featured images on my paginated blog post links so this is crucial for me.

----

I tried another solution, inspired by filtering in Tag example:
https://github.com/gatsbyjs/gatsby/blob/52e36b9994a86fc473cd2f966ab6b6f87ee8eedb/examples/using-remark/src/templates/template-tag-page.js#L39

I tried to pass only article slugs and wanted to query for only articles which have their slug in the array specified. However, when tested with hardcoded values, I was not getting any data as a result of the query. The query was however syntactically correct:

`        filter: {fields: { slug: { in: ["/avoid-telescoping-constructor-pattern/"]}}}`

However ordinary equals query worked:
`       filter: {fields: { slug: { eq: "/avoid-telescoping-constructor-pattern/"}}}`

When I try to use variable, like this:

```
export const pageQuery = graphql`
  query IndexQuery($foo: [String]) {
    site {
      siteMetadata {
        title
      }
    }
    allMarkdownRemark(
    sort: { fields: [frontmatter___date], order: DESC }
    filter: { fields: {slug: {in: $foo} } }
    
    ) {
      edges {
        node {
          excerpt
          fields {
            slug
          }
          frontmatter {
            date(formatString: "DD MMMM, YYYY")
            title
            tags
            featuredImage {
                childImageSharp{
                    sizes(maxWidth: 200) {
                        ...GatsbyImageSharpSizes_tracedSVG
                    }
                }
            }
          }
        }
      }
    }
  }
`



```
I get error:

> GraphQL Error Argument "filter" has invalid value {fields: {slug: {in: $foo}}}.
> In field "fields": In field "slug": In field "in": Unknown field.

----
Why can I not use GatsbyImageSharpSizes_tracedSVG in gatsby-node.js? What is the correct way to use 'in' operator? Thank you.

**Comment by KyleAMathews** [comment]
The query should us `eq` not `in` which is just for arrays. Try out queries in GraphiQL.

The error at the end is saying `$foo` is unknown. That's because you define arguments at the top like `query IndexQuery($foo: String!) {`

**Comment by vojtechruz** [comment]
I am sorry, I know you have a lot of issues, but if you carefully read my post, I actually am using IN and need to use it, because I need to return only posts where their slug is in a specified array. And also, I am defining the argument in my query. Thank you.

`query IndexQuery($foo: [String]) {`

**Comment by KyleAMathews** [comment]
Ah sorry about misreading that.

I'm not sure then. Easiest way for me or anyone else to help you then would be to build a very simple reproduction site of your problem and share a link to that here so we can look at your code.

**Comment by vojtechruz** [comment]
Thank you for your help, appreciate that. My code is here: 

https://github.com/vojtechruz/vojtechruzicka-blog/tree/pagination-my

The file with the graphql query is here:

https://github.com/vojtechruz/vojtechruzicka-blog/blob/pagination-my/src/templates/paginated-posts.js

```
export const pageQuery = graphql`
  query IndexQuery($pageSlugs: [String]) {
    site {
      siteMetadata {
        title
      }
    }
    allMarkdownRemark(
        sort: { fields: [frontmatter___date], order: DESC }
        filter: { fields: {slug: {in: $pageSlugs} } }
    ) {
      edges {
        node {
          excerpt
          fields {
            slug
          }
          frontmatter {
            date(formatString: "DD MMMM, YYYY")
            title
            tags
            featuredImage {
                childImageSharp{
                    sizes(maxWidth: 200) {
                        ...GatsbyImageSharpSizes_tracedSVG
                    }
                }
            }
          }
        }
      }
    }
  }
`
```

**Comment by vojtechruz** [comment]
I was able to find a workaround using graphql-skip-limit, the issue can be kept closed. Thanks.

**Comment by eamontaaffe** [comment]
I ran into the same issue. It just seems to be an issue with the fragment's not being available when gatsby-node.js is run. 

One quick fix is to not use a fragment. The GatsbyImageSharpResolution fragment's can be found here: https://github.com/gatsbyjs/gatsby/blob/3445b9a7541dfd181ef7f062dc8b21e380a31d93/packages/gatsby-transformer-sharp/src/fragments.js#L2

All you have to do is change this:
```js
sizes(maxWidth: 200) {
    ...GatsbyImageSharpSizes_tracedSVG
}
```

To this:
```js
sizes(maxWidth: 200) {
    tracedSVG
    width
    height
    src
    srcSet
}
```

**Comment by KyleAMathews** [comment]
@eamontaaffe why not run the query in the template component? The fragment is available there and you get hot reloading when you change your query, etc.
