### ISSUE TITLE
[plugins] Handling remote images in a source-plugin

### ISSUE THREAD

**Issue by ajayns** [gatsbyjs/gatsby#4474]
I've used the transformer-sharp plugin to be able to call and use multiple sizes of the same image in a project. But what's the best method to be followed in the case that multiple sizes are available from the source itself? 

For instance, when the source has a 400x400 image we can use transformer-sharp to call and get a 200x200 image. But what's the case when we already have both 400x400 and 200x200 images from the source itself?

**Comment by KyleAMathews** [comment]
Grab the largest possible, hopefully the original. You can resize down but not up.
