### ISSUE TITLE
Gatsby isn't picking up my file changes in the tutorial example

### ISSUE THREAD

**Issue by RickyRomero** [gatsbyjs/gatsby#4476]
## Description

In part one of the introduction to Gatsby, the page says the following:

> Once you open that file, try changing “Hello world!” in the page component to “Hello Gatsby!“. Once you save that change, the text in your browser should change within a second (tip: you will always need to save changes before they appear in your browser).

I'm unable to get this behavior to work on my system.

I'm using Textmate as my editor, but TextEdit produces the same behavior. Running `export CHOKIDAR_USEPOLLING=1` beforehand doesn't fix the problem. I installed `gatsby-cli` globally using a separate admin user account - I don't use an admin account as my main login.

### Steps to reproduce

Follow the steps in the tutorial through to the section quoted above.

### Expected result

When I change "Hello world!" to "Hello Gatsby!" and save `src/pages/index.js`, Gatsby should rebuild the page and reload the browser tab as described in the tutorial.

### Actual result

Gatsby doesn't appear to notice that I change the file, as no additional output appears in Terminal after saving. The page doesn't update even if I reload manually. The server only picks up the change if I stop and restart it.

### Environment

* Gatsby version (`npm list gatsby`):
```
Sentinel:tutorial-part-one r$ npm list gatsby
gatsby-starter-hello-world@ /Users/r/Desktop/gatsby-example/tutorial-part-one
└── gatsby@1.9.223 
```
* gatsby-cli version (`gatsby --version`):
```
Sentinel:tutorial-part-one r$ gatsby --version
1.1.45
```
* Node.js version:
```
Sentinel:tutorial-part-one r$ node --version
v9.7.1
```
* Operating System:
macOS High Sierra 10.13.3 (17D102)

### File contents (if changed):

`gatsby-config.js`: unchanged
`package.json`: unchanged
`gatsby-node.js`: unchanged
`gatsby-browser.js`: unchanged
`gatsby-ssr.js`: unchanged

**Comment by m-allanson** [comment]
Hmmm, I wonder what's causing this... It's not an issue I've seen before. I don't think you'd need to change chokidar's polling mode. Maybe this is a file permissions issue?

From the tutorial directory can you try running `node_modules/.bin/gatsby develop` instead of `gatsby develop`? And what are the permissions of your project files? e.g. the output from `ls -al`

**Comment by RickyRomero** [comment]
Sorry for the delayed response, looks like I'm not getting GitHub notifications.

Just to follow up on this... It's working now? I didn't change anything, but I did restart my iMac between the time I made this bug report and now. Gatsby's picking up changes as intended.

**Comment by m-allanson** [comment]
Ok, I’m glad things worked out :)
