### ISSUE TITLE
Styles missing on production for SASS + CSS Module with gatsby-plugin-sass

### ISSUE THREAD

**Issue by linmic** [gatsbyjs/gatsby#4477]
## Description

SASS + CSS Module cause issues on production build, part of styles are missing to be exact.

### Steps to reproduce

1. Use `gatsby new test` to create a new project.
2. Add `gatsby-plugin-sass` and add it to `gatsby-config.js`.
3. Create `styles.module.scss` under `src/components/Header` with a simple `.red { color: red; }` within.
4. In `src/components/Header/index.js`, `import styles from './styles.module.scss`, and use it anywhere you want.
5. `gatsby build` then serve `public`

### Expected result

Styles from layouts is missing from generated inline styles within `<style id="gatsby-inlined-css">`.
e.g. Styles for `<body>` should exist.

### Actual result

It's gone.

### Environment

* Gatsby version: `1.9.231`
* gatsby-cli version: `1.1.45`
* Node.js version: `8.9.4`
* Operating System: `macOS High Sierra`

### Minimum Reproducible Case

[https://github.com/linmic/gatsby-module-issue](https://github.com/linmic/gatsby-module-issue)

**Comment by linmic** [comment]
Replacing `gatsby-plugin-sass` with `gatsby-plugin-postcss-sass` seems works.

**Comment by chrisk2020** [comment]
There is an issue with a recent update of gatsby-plugin-sass the plugin author is looking into it A temporary solution is to specify the version of gatsby-plugin-sass #4457

**Comment by erquhart** [comment]
Fixed in #4495.
