### ISSUE TITLE
 Error: Command failed: npm install

### ISSUE THREAD

**Issue by gnunua** [gatsbyjs/gatsby#4486]
`node -v`
 v8.9.3
`gatsby -v` 
 1.1.45

error Command failed: npm install
```
Error: Command failed: npm install
  
  - index.js:236 Promise.all.then.arr
    [lib]/[gatsby-cli]/[execa]/index.js:236:11
  
  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18
  
  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10
  
  - promise.js:693 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:693:18
  
  - promise.js:638 Promise._fulfill
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18
  
  - promise_array.js:126 PromiseArray._resolve
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19
  
  - promise_array.js:144 PromiseArray._promiseFulfilled
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14
  
  - promise.js:574 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26
  
  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10
  
  - promise.js:693 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:693:18
  
  - async.js:133 Async._drainQueue
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:133:16
  
  - async.js:143 Async._drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:143:10
  
  - async.js:17 Immediate.Async.drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:17:14
```

**Comment by m-allanson** [comment]
@gnunua Can you provide an example repo, or exact steps to recreate this error?

**Comment by gnunua** [comment]
Hey @m-allanson. Thanks for the response.
Just running ` gatsby new gatsby-site` as described in official doc.

<img width="951" alt="g__screenshot at mar 14 12-31-44" src="https://user-images.githubusercontent.com/5013933/37391132-b7acf714-2783-11e8-80ad-848d63f61911.png">

The result of this issue is starter repo dependency:
```
npm ERR! code E404
npm ERR! 404 Not Found: @zeit/check-updates@1.1.0

```

**Comment by m-allanson** [comment]
Thanks @gnunua. This sounds like just an npm hiccup, have you tried running the command again?

**Comment by gnunua** [comment]
Thanks for your replay @m-allanson. You are right, the problem was in npm config.  Just configured registry and everything works great.

**Comment by m-allanson** [comment]
Great!

**Comment by praveen2896** [comment]
@m-allanson how can i configure the npm config ,where it is found?

**Comment by Ravothulachandu** [comment]
I am also having the same problem please help me.

**Comment by benhartouz** [comment]
same issue with me

**Comment by DSchau** [comment]
@benhartouz can you provide any more detail as to what is happening? A stacktrace for example?

**Comment by benhartouz** [comment]
@DSchau thanks for you response, just i want to install dependencies so i ran 
```
npm install
```
Then i got this issue
```
WARN tar ENOENT: no such file or directory, open '/Users/macbook-pro/Desktop/React/gatsby/gatsby-site/node_modules/.staging/micromatch-f241d030/package.json'
WARN tar ENOENT: no such file or directory, open '/Users/macbook-pro/Desktop/React/gatsby/gatsby-site/node_modules/.staging/micromatch-f241d030/CHANGELOG.md'
WARN tar ENOENT: no such file or directory, open '/Users/macbook-pro/Desktop/React/gatsby/gatsby-site/node_modules/.staging/micromatch-f241d030/index.js'
WARN tar ENOENT: no such file or directory, open '/Users/macbook-pro/Desktop/React/gatsby/gatsby-site/node_modules/.staging/micromatch-f241d030/LICENSE'
WARN tar ENOENT: no such file or directory, open '/Users/macbook-pro/Desktop/React/gatsby/gatsby-site/node_modules/.staging/micromatch-f241d030/README.md'
npm ERR! code E404
npm ERR! 404 Not Found: @reach/router@https://registry.npmjs.org/@reach/router/-/router-1.2.1.tgz

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/macbook-pro/.npm/_logs/2019-02-13T16_33_32_897Z-debug.log
```

**Comment by DSchau** [comment]
@benhartouz are you behind a proxy or something?

Does `npm config get registry` show `https://registry.npmjs.org/`?

This link https://registry.npmjs.org/@reach/router/-/router-1.2.1.tgz works just fine for me.

**Comment by benhartouz** [comment]
@DSchau yeah `npm config get registry` show `https://registry.npmjs.org/` . but i still get this issue 
```
npm ERR! code E404
npm ERR! 404 Not Found: @reach/router@https://registry.npmjs.org/@reach/router/-/router-1.2.1.tgz

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/macbook-pro/.npm/_logs/2019-02-13T16_53_12_397Z-debug.log
```

**Comment by DSchau** [comment]
What about `npm config list`? Do you see a proxy or something?

**Comment by benhartouz** [comment]
@DSchau  i get this.
```
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/5.6.0 node/v8.11.4 darwin x64"

; userconfig /Users/macbook-pro/.npmrc
//registry.npmjs.org/:always-auth = false
//registry.npmjs.org/:email = "benhartouzmohamed@gmail.com"
//registry.npmjs.org/:username = "kokizz"

; node bin location = /usr/local/Cellar/node/10.8.0/bin/node
; cwd = /Users/macbook-pro/Desktop/React/gatsby/gatsby-site
; HOME = /Users/macbook-pro
; "npm config ls -l" to show all defaults.
```

**Comment by benhartouz** [comment]
(`npm logout`). It worked for me :)

**Comment by Nanavati13** [comment]
I am also facing the same issue and can't solve it. I have just run `gatsby new gatsby-site` as described in the official doc and got this issue: Error: Command failed: npm install.
![Screenshot from 2019-06-19 11-38-50 (1)](https://user-images.githubusercontent.com/51984416/59740935-288bc680-9287-11e9-95c2-565a3ddc18c9.png)

**Comment by JaybeeClassical** [comment]
This issue shouldn't have been closed since most people here didn't get that solved, now i'm in the same issue then coming here to see no concrete response towards how to get this solved

**Comment by nariusk** [comment]
Entering npm cache verify fixed the issue for me. Remember to remove the existing folder before installing again.

**Comment by radheshjoshi** [comment]
npm ERR! code 1
npm ERR! Command failed: git clone --depth=1 -q -b 1.3.8 git://github.com/eligrey/FileSaver.js.git /home/radhesh/.npm/_cacache/tmp/git-clone-083c2df0
npm ERR! /home/radhesh/.npm/_cacache/tmp/git-clone-083c2df0/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/radhesh/.npm/_logs/2019-12-23T05_27_02_190Z-debug.log



DSchau can you solve this asap
