### ISSUE TITLE
user registration and user profile

### ISSUE THREAD

**Issue by Abdelrahman146** [gatsbyjs/gatsby#4489]
Hello,
is their a way to let gatsby, have user registration. user can have a profile and edit it. and user can add new article or item to the website ?

I know gatsby is static site generator. but I'm wondering if I can use Gatsby as a solution for such web application..

thanks.

**Comment by m-allanson** [comment]
You can build client-side only routes and add any functionality you like. Check out the docs on [building apps with Gatsby](https://www.gatsbyjs.org/docs/building-apps-with-gatsby/)

And here's a [Gatsby starter that uses Firebase for authentication](https://github.com/rwieruch/gatsby-firebase-authentication).
