### ISSUE TITLE
WebpackError: cancelAnimationFrame is not defined

### ISSUE THREAD

**Issue by rockmandash** [gatsbyjs/gatsby#4504]
WebpackError: cancelAnimationFrame is not defined
What can I do to manage this?
Thanks for helping.

**Comment by m-allanson** [comment]
Hi @rockmandash, there's not enough information in your issue to help you. Can you list steps to reproduce the error or link to an example repo?

**Comment by rockmandash** [comment]
@m-allanson Thank you for your reply
I think the Gatsby didn't understand cancelAnimationFrame during build process.
So I need to avoid using cancelAnimationFrame in several places like componentDidMount.

**Comment by m-allanson** [comment]
👍 

You can also do a check like:

```
if (typeof window !== `undefined`) {
  // your code here
}
```
https://www.gatsbyjs.org/docs/debugging-html-builds/#how-to-check-if-window-is-defined
