### ISSUE TITLE
Consistently use `yarn` or `npm` across docs

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#4514]
Across Gatsby's docs both `yarn` and `npm` are used interchangeably, which seems a bit confusing.  The docs should consistently mention either `yarn` _or_ `npm`. Or both?

**Comment by KyleAMathews** [comment]
I always use NPM — but yeah, we should standardize that and fix anyone's any uses of Yarn.

**Comment by giladronat** [comment]
@KyleAMathews I’d gladly make it all consistent and PR -- do you prefer standardizing to NPM because you use it or Yarn because it’s probably more common?

**Comment by shannonbux** [comment]
good question @giladronat and thanks for offering.

**Comment by shannonbux** [comment]
And then I accidentally closed and opened this again haha. Still a github newb.

**Comment by KyleAMathews** [comment]
@giladronat yeah NPM cause it's the default and anyone using Yarn is already familiar with translating instructions to Yarn. Thanks!

**Comment by giladronat** [comment]
@KyleAMathews that makes sense. As a JS newbie that was [recommended Yarn by friends](https://twitter.com/giladronat/status/974226719379922944), I don’t fall into that category, but I don’t know if I’m a representative sample. I’ll change to NPM though; most of the work is just finding all instances, not changing one way or another 😄

**Comment by WebRuin** [comment]
I am happy to help go through the docs looking for `yarn` and `npn`.  Which do you prefer.  I can update it.

**Comment by m-allanson** [comment]
Thanks @giladronat! 

And thanks @WebRuin too, but it looks like @giladronat is working on this one already.

**Comment by giladronat** [comment]
This is done. Feel free to close @KyleAMathews

**Comment by KyleAMathews** [comment]
Thanks @giladronat!

**Comment by eballeste** [comment]
i personally use npm but anytime i start a new gatsby project it automatically uses yarn in it's install process and throws an npm related warning:

> warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.

it also creates a yarn lock file in addition to the package-lock.json
