### ISSUE TITLE
Ship graphql playground as default

### ISSUE THREAD

**Issue by rockmandash** [gatsbyjs/gatsby#4518]
Ship https://github.com/graphcool/graphql-playground as default please

**Comment by fk** [comment]
Replacing https://github.com/graphql/graphiql?

**Comment by rockmandash** [comment]
@fk Yes, as graphql-playground is built upon graphiql.

**Comment by pieh** [comment]
This is duplicate of https://github.com/gatsbyjs/gatsby/issues/4231 . Check there to see how you can currently use `graphql-playground`

**Comment by rockmandash** [comment]
Insane~~

**Comment by KyleAMathews** [comment]
@rockmandash please be more polite. Your last message feels like harassment which is against our community code of conduct https://www.gatsbyjs.org/code-of-conduct/

**Comment by rockmandash** [comment]
@KyleAMathews No, you misunderstand my word.
I mean I can now use graphql-playground which is good.
OK?  you misunderstand too much.

**Comment by KyleAMathews** [comment]
Ah sorry! Miscommunication :-)
