### ISSUE TITLE
[gatsby-source-wordpress] Newer ACF Fields not showing up in graphQL

### ISSUE THREAD

**Issue by AnalogMemory** [gatsbyjs/gatsby#4523]
So I feel like something is just wonky but I can't isolate the issue. I've added some new ACF fields to an existing WordPress setup that is working great with Gatsby. But graphQl refuses to see them.

#### Setup
gatsby: 1.9.232
gatsby-source-wordpress: 2.0.68

#### What I can see
✔️ The fields show up with values when I view the WP-JSON feed from WordPress
✔️ The fields show up in `.cache/redux-state.json`

#### Where it breaks
✖️ When I try to view it in graphQl viewer
✖️ When I try to add the queries to the templates

Example of what's breaking:
I have a ACF Flexible Content field with a repeater field containing a text and wysiwig fields

redux-state.json
```
"60e3130f-63fe-5ff8-bbd3-8e24afa87a131sectionsWordPressAcf_text": {
  "copy_columns": [
    {
      "title": "Something",
      "copy": "<p>Lorem Ipsum</p>\n"
    },
    {
      "title": "More text",
      "copy": "<p>Lorem Ipsum</p>\n"
    }
  ],
  "id": "60e3130f-63fe-5ff8-bbd3-8e24afa87a131sectionsWordPressAcf_text",
  "parent": "60e3130f-63fe-5ff8-bbd3-8e24afa87a131",
  "children": [],
  "internal": {
    "type": "WordPressAcf_text",
    "contentDigest": "39d14ae46048b8d8712ff69863ca0f11",
    "owner": "gatsby-source-wordpress"
  }
},
```

What GraphQl viewer shows 
```
{
  "data": {
    "wordpressPage": {
      "title": "Home",
      "id": "60e3130f-63fe-5ff8-bbd3-8e24afa87a13",
      "acf": {
        "sections_page": [
          {
            "__typename": "WordPressAcf_text",
            "id": "60e3130f-63fe-5ff8-bbd3-8e24afa87a131sectionsWordPressAcf_text"
          },
        ]
      }
    }
  }
}
```

If i try to add the field copy_columns it gives an error

`"message": "Cannot query field \"copy_columns\" on type \"WordPressAcf_text\"."`

#### Things I've tried:
* Trashed .cache, public, node_modules and started fresh
* Nuked the whole folder and pulled a fresh copy from gitlab
* Angrily ate a bag a chips

**Comment by pieh** [comment]
Hi @AnalogMemory 
This might be similar issue as here: https://github.com/gatsbyjs/gatsby/issues/4461#issuecomment-371775563 . Try to check if code snippet I pasted there (with additional hook added for `flexible_content` acf field type) will fix this.

**Comment by AnalogMemory** [comment]
@pieh In my case all of the fields had values so it wasn't a null/empty issue. But that actually will help a related issue I've had.

I think it was a field name collision. Seems graphql can't handle multiple fields with the same name. When i renamed all the fields to something less generic it started showing up 🤷‍♀️
