### ISSUE TITLE
Query params not captured in Google Analytics 

### ISSUE THREAD

**Issue by longsangstan** [gatsbyjs/gatsby#4527]
## Description

Query params not captured in Google Analytics.

### Steps to reproduce

1) Install google analytics plugin
2) Go to the website using a url with query params e.g. `http://www.example.com/?from=abc`
3) Go to google analytics console

### Expected result

If a user goes to my website using a url like this `http://www.example.com/?from=abc`, I expect in my analytics console I would see:
```
Page         Page Views
/?from=abc     123
```

### Actual result
Instead, I can only see the path without the query params:
```
Page         Page Views
/                123
```

### Environment

* Gatsby version (`npm list gatsby`): ^1.9.223
* gatsby-cli version (`gatsby --version`): 1.1.29
* Node.js version: v6.11.0
* Operating System: --

**Comment by KyleAMathews** [comment]
Could you look into how to capture these and add a PR to the plugin? https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-google-analytics/src/gatsby-browser.js

**Comment by longsangstan** [comment]
@KyleAMathews Thanks! I will look into that.
