### ISSUE TITLE
Add default 404 page for development

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#453]
It should use fuzzy search to find the nearest matching path and say "did you mean to go to xyz page?"

And then below that show a searchable list of all pages.

This may or may not be possible with Gatsby 0.x (have to think more about that) but will be trivial with 1.x.

**Comment by stereobooster** [comment]
Some ideas in the box http://alistapart.com/article/perfect404

**Comment by KyleAMathews** [comment]
Done in https://github.com/gatsbyjs/gatsby/pull/1051
