### ISSUE TITLE
Removing trailing slash not working on a production?

### ISSUE THREAD

**Issue by jarekpelczynski** [gatsbyjs/gatsby#4530]
I use **gatsby-plugin-remove-trailing-slashes** and it's everything ok when I use the navigation to change pages but when I go directly to, for example, `mydomain.com/terms`, a slash is present at the end of URL and it causes a problem with URLs in navigation – adds a slug to URLs, e.g.`mydomain.com/terms/terms`.

**Comment by KyleAMathews** [comment]
You need to setup your host to not use the slash. Many redirect from slashless to the slash be default

**Comment by jarekpelczynski** [comment]
I didn't mention that I use S3.

**Comment by guillewu** [comment]
@jarekpelczynski have you found a solution?
