### ISSUE TITLE
HMR in production build?

### ISSUE THREAD

**Issue by f0rr0** [gatsbyjs/gatsby#454]
After generating a static site, I test it via a simple http-server. The server keeps logging:
```
127.0.0.1 - - [21/Sep/2016 06:26:22] code 404, message File not found
127.0.0.1 - - [21/Sep/2016 06:26:22] "GET /__webpack_hmr HTTP/1.1" 404 -
```
every few seconds. Is this intended behavior?

**Comment by KyleAMathews** [comment]
Do you have the dev site still open? It'll keep trying to reconnect to your
dev server. Close that browser tab and it'll stop trying to reconnect.
