### ISSUE TITLE
Specify configuration file when developing or building

### ISSUE THREAD

**Issue by eads** [gatsbyjs/gatsby#4547]
## Description

I have different path prefixes on my staging site and my production site. As far as I can tell, I can't specify an alternate config file or otherwise munge configuration at build-time. 

Path prefixes feel like a special configuration case -- I could see a good argument for allowing that setting to be overridden via the cli (e.g. `gatsby build --path-prefix=my/path/prefix`).

I could also see an argument for allowing a configuration file to be specified via environment variable or command line flag. I think there's potentially two issues here: Generally specifying a configuration file to use during build (or development) and specifically setting the path prefix during build.

I am running recent versions of Gatsby (1.1.45) and Node (9.8).

**Comment by pieh** [comment]
`gatsby-config.js` is `js` file - you can add logic to it (like conditionally pick path-prefix depending on env vars)

**Comment by KyleAMathews** [comment]
Yeah, we've made the choice to encourage people to put logic into gatsby-config.js vs. using CLI overrides. Should be straightforward to vary the pathPrefix by ENV.

**Comment by eads** [comment]
Ah, groovy! Thanks.

**Comment by ThiagoMiranda** [comment]
this solution only works for the `gatsby-config.js` file. All other places in my site that is using the env variables uses the ones found at `.env.production`

**Comment by stoque** [comment]
+1
