### ISSUE TITLE
gatsby-remark-prismjs: allow adding aliases (e.g. sh => bash)

### ISSUE THREAD

**Issue by docwhat** [gatsbyjs/gatsby#4549]
It would be nice if the `gatsby-remark-prismjs` plugin would allow adding aliases.

Something like this would be good:

```javascript
// In your gatsby-config.js
plugins: [
  {
    resolve: `gatsby-transformer-remark`,
    options: {
      plugins: [
        {
          resolve: `gatsby-remark-prismjs`,
          options: {
            classPrefix: "language-",
            aliases: {
              'sh': "bash",
              'js': "javascript",
              // etc.
            }
          },
        },
      ],
    },
  },
];
```

**Comment by KyleAMathews** [comment]
That'd be cool! Does PrismJS have some sort of native way of doing this? I'm a bit wary of adding additional features to our PrismJS implementation as it'd be confusing to people expecting PrismJS to work as normal.

**Comment by docwhat** [comment]
I _think_ that you would just change [`index.js` line 21](https://github.com/gatsbyjs/gatsby/blob/ae18f24867b12f664ecee9af0553b58d1703a8bc/packages/gatsby-remark-prismjs/src/index.js#L21) to something like this:

``` js
      // I don't know how to get to the gatsby-config.js options...
      languageName = options.aliases[language] || language
```

You can see they do something similar in [prism.js line 787](https://github.com/PrismJS/prism/blob/gh-pages/prism.js#L787-L797) and they use it at [line 814](https://github.com/PrismJS/prism/blob/gh-pages/prism.js#L812-L815):

``` js
			if (!language) {
				var extension = (src.match(/\.(\w+)$/) || [, ''])[1];
				language = Extensions[extension] || extension;
			}
```

Of course, that is _slightly_ different in that it is looking for a file extension, but the principle should be the same.

**Comment by KyleAMathews** [comment]
ah yeah interesting. Yeah, that could work — the second argument to the file is the plugin options so if you want to experiment with this and create a PR this sounds like a great addition! https://www.gatsbyjs.org/docs/how-to-contribute/
