### ISSUE TITLE
Layout not being used when "/src/layouts" doesn't exist and layout provides by plugin.

### ISSUE THREAD

**Issue by pauldotknopf** [gatsbyjs/gatsby#4558]
I am wrapping my theme/styles/pages/etc in a gatsby plugin.

Inside of my plugin, I create the default ``index``` layout.

```js
export const createLayouts = ({ graphql, boundActionCreators }) => {
    const { createLayout } = boundActionCreators;
    const defaultLayout = slash(path.resolve(path.join(__dirname, 'layouts/index.js')));
    createLayout({
        component: defaultLayout,
        id: 'index',
    })
};
```

My custom plugin is used, but only if a file matches ```/src/layouts/index.*``` exists, like ```/src/layouts/index.sdfwefw```.

I think it may have something to do with this line: https://github.com/gatsbyjs/gatsby/blob/6ac0eb96b7a231d1182ab25cbdf5c36e93805a65/packages/gatsby/src/redux/actions.js#L244

My requirements require me to have a directory with pure markdown files. I'm building a tool that is geared more towards non-developers. I'd like to avoid having this magical ```/src/layouts/index.sdfsf``` existing.

**Comment by pauldotknopf** [comment]
Temporary workaround:

```js
export const onCreatePage = ({ page, boundActionCreators }) => {
    const { createPage, deletePage } = boundActionCreators;
    let newPage = page || {};
    if (!newPage.layout) {
        newPage.layout = 'index';
        deletePage(newPage);
        createPage(newPage);
    }
};
```

**Comment by KyleAMathews** [comment]
Yeah, we special case src/layouts/index.js as it's so common. What you did in the previous comment is what's required for custom layouts.

**Comment by pauldotknopf** [comment]
Maybe you should log if a page doesn't have a layout? Why not always set "index" as the default, and let the cli barf when it tries to use the non-existent layout?

Either way, it isn't good to have imperative magic that depends on something seemingly so unrelated. At least at some logging around it, it would have save me a lot of time.
