### ISSUE TITLE
How to build for cordova?

### ISSUE THREAD

**Issue by ostrichegret** [gatsbyjs/gatsby#4560]
I am looking for React SSR solution that can also build for cordova.

Thank you

**Comment by m-allanson** [comment]
Hey @ostrichegret 👋 I'm not sure if anyone's used Cordova with Gatsby, would love to see a link if you get it working!

**Comment by bitttttten** [comment]
Hey @sixman9 did you get any further on this? I am trying to build a gatsby app in phonegap for iOS, although I am currently struggling with the lack of .index.html extensions on links, and also the relative links to JavaScript that gatsby generates.

For example Gatsby generates`<script src="/webpack-runtime..js" />`, and phonegap wants `<script src="webpack-runtime..js" />`. So I am still having a few issues.

**Comment by flogy** [comment]
Hi @ostrichegret , @m-allanson , @sixman9 and @bitttttten ,

I recently tried to transform my Gatsby web app into mobile apps using Capacitor, too. Capacitor is the spiritual successor to Apache Cordova and Adobe PhoneGap.

If you still require help with it you can find a **step by step manual** on how I was able to do it here: https://react-freelancer.ch/blog/build-mobile-apps-using-gatsby-and-capacitor

Also, you can use this **Gatsby starter** to kick start your next project using Gatsby and Capacitor: https://github.com/flogy/gatsby-starter-capacitor

Hope this helps you with your projects 😊

**Comment by bitttttten** [comment]
Thanks for the heads up @flogy ! And really nice article. I ended up moving Gatsby project to React Native with Expo. It was a fair amount of work but I am really happy with the the result.

**Comment by flogy** [comment]
Thank you @bitttttten ! I believe you this was quite some work, but nothing beats native apps 😉
