### ISSUE TITLE
Clarification on which component to use for app wide React Context, and how to dynamically make pages right

### ISSUE THREAD

**Issue by fxfactorial** [gatsbyjs/gatsby#4564]
I love gatsby. Love it. 

Assuming a site created with the starter blog kit

1. Which component is the kosher one to use for using React's context API? So that I can have data accessible everywhere. Right now I'm using `layout/index.js` but this seems incorrect. 

2. How to properly make dynamic routes? I want to have a jobs board, say like foo.com/hiring-board/job/SOME_UNIQUE_ID, where should I programmatically hook that? Again, `layout/index.js` comes with this default code: `    if (location.pathname === '/') {`, but then I guess I'd need to do string splitting there? Something more coherent with react-router available? 

Much appreciated.

**Comment by KyleAMathews** [comment]
layout/index.js should work. Which context API are you using? We're (still) on React 15 until Gatsby v2 is released. You can use gatsby-plugin-react-next to use React 16 in the meantime.

On routes, check out the tutorial which covers this https://www.gatsbyjs.org/tutorial/
