### ISSUE TITLE
Generating Javascript bundles failed

### ISSUE THREAD

**Issue by d33con** [gatsbyjs/gatsby#4581]
## Description

Auto deploy from github repo using Netlify causes error. 
I also tried a manual deploy within Netlify but I'm getting the same result
_failed during stage 'building site': Build script returned non-zero exit code: 1_

I'm getting this in the deploy details on Netlify
![screenshot-2018-3-17 deploy details oliverbullen](https://user-images.githubusercontent.com/13669754/37555887-8a20e264-29e6-11e8-84dc-91ae2040702c.png)

Local build is failing with the same error message.

Local development is working fine.

### Expected result

On pushing changes to the Github repo, Netlify should automatically update the site to reflect those changes.

### Actual result

Build fails 

### Environment

* Gatsby version (`npm list gatsby`): gatsby@1.9.192
* gatsby-cli version (`gatsby --version`): 1.1.46
* Node.js version: 9.5.0
* Operating System: Windows 10

**Comment by m-allanson** [comment]
Can you try updating to the latest version of Gatsby?

**Comment by d33con** [comment]
I've updated Gatsby. Now I'm getting this error on both gatsby develop & build

4:05:53 PM: error RootQueryType.allSitePage field type must be Output Type but got: SitePageConnection.
4:05:53 PM: 
4:05:53 PM:   Error: RootQueryType.allSitePage field type must be Output Type but got: SiteP  ageConnection.
4:05:53 PM:   
4:05:53 PM:   - Array.forEach
4:05:53 PM:   
4:05:53 PM:   - Array.reduce
4:05:53 PM:   
4:05:53 PM:   - index.js:52 _callee$
4:05:53 PM:     [repo]/[gatsby]/dist/schema/index.js:52:20

**Comment by m-allanson** [comment]
That error seems to occur if you have multiple versions of GraphQL, see https://github.com/gatsbyjs/gatsby/issues/2001. Can you see if that's what's happening in your case? `yarn list graphql` or `npm list graphql` should do it.

**Comment by d33con** [comment]
Yeah, that's fixed it. Thanks! There's quite a lot of different solutions in that linked issue but this is what worked for me

https://github.com/gatsbyjs/gatsby/issues/2001#issuecomment-353098959
```
npm remove graphql
npm install gatsby
```

**Comment by infinitbility** [comment]
gatsby build generating javaScript bundles failed issue solution

https://infinitbility.com/gatsby-build-generating-javascript-bundles-failed
