### ISSUE TITLE
Guidance on building tree menu with expanded children for active paths?

### ISSUE THREAD

**Issue by pauldotknopf** [gatsbyjs/gatsby#4583]
Is there a template/project out there that currently does this?

[Here](https://wyam.io/docs/extensibility/customizing-recipe-pipelines) is an example side menu.

Thanks in advance!

**Comment by pauldotknopf** [comment]
@benjaminhoffman, that makes sense for a dynamic menu, which I have no problem doing.

The problem is how do I get the data *into* gatsby. Graphql doesn't support nested queries.

I was thinking if there was some way to listen to ```onCreatePage``` to build/update a hierarchical navigation structure (based on ```page.path```). Maybe create/manage a single node with ```createNode``` that maintains this structure, and then query the single node in my layout, then determine the active path inside of the component?

I'm surprised nobody has needed/done this before.

**Comment by pauldotknopf** [comment]
Here is what I am thinking.

1. Extend ```SitePage``` graphql type to include a ```Menu``` property that contains a curated tree-like menu structure, specifically for that page.

```js
export const setFieldsOnGraphQLNodeType = ({ type }) => {
    if (type.name !== "SitePage") {
      return {};
    }

    return Promise.resolve({
      menu: {
        type: new GraphQLScalarType({
            name: 'Menu',
            serialize(value) {
                return value;
            },
        }),
        resolve: node => {
            // TODO: Based off of node path, build a tree-like structure
            // representing the current path, including properties
            // indicating the "active" path.
            return {

            }
        },
      },
    });
  };
```

2. Within the resolver for property ```menu```, query all the pages (```allSitePages```). Then,use something like ```tree-from-paths``` (See [here](https://www.npmjs.com/package/tree-from-paths) to build a menu for the page. Note, my custom ```GraphQLScalarType``` supports unbounded nested children (dynamic schema). This will allow arbitrary menu depths.

3. Copy custom fragement to be used by page queries that will include the current page, and the menu for that page.

```js
export const menuFragement = graphql`
  fragment menu on RootQueryType {
    menu: allSitePage(filter: {path: {eq:$slug}}) {
        edges {
          node {
            path
            menu
          }
        }
      }
  }
`
```

4. Build a custom react component that will render the menu.

@KyleAMathews, can you give this a quick glance? Maybe there is a better way to do this? Maybe I am intending on using something that will eventually be deprecated?

Thanks in advance!

PS: I intend on wrapping this up in a plugin to share.

**Comment by gagan0723** [comment]
@pauldotknopf have a look at [reactjs.org](https://reactjs.org/tutorial/tutorial.html#before-we-start). The code is available on [github](https://github.com/reactjs/reactjs.org). Its controlled by a [prop](https://github.com/reactjs/reactjs.org/blob/da8a7df2049c89d81505a6f6909f51d613dc58ba/src/templates/tutorial.js#L25) as in **tutorial.js** template in ```src/templates``` and this is the actual [component ](https://github.com/reactjs/reactjs.org/blob/master/src/components/StickyResponsiveSidebar/StickyResponsiveSidebar.js).

**Comment by KyleAMathews** [comment]
@pauldotknopf looks like a promising approach!

**Comment by pauldotknopf** [comment]
Yes it worked.

But I abandoned Gatsby all together. There is just too much weight weighing down seemingly simple tasks with this project.

https://www.npmjs.com/package/gatsby-plugin-page-tree

https://github.com/pauldotknopf/docgen/tree/archived/attempt3/packages/gatsby-plugin-page-tree

**Comment by frazerf** [comment]
Awesome! You don't happen to have a how to use guide/readme do you?

**Comment by pauldotknopf** [comment]
Sorry, no.

Checkout the `attempt3` branch in [this](https://github.com/pauldotknopf/docgen) to see it used.
