### ISSUE TITLE
Additional non 'post' pages

### ISSUE THREAD

**Issue by edouerd** [gatsbyjs/gatsby#459]
In which file(s) might I add an additional non-post page?

I'm currently trying to build a site which has an 'index' (/), a similarly-structured 'info' page, and 'posts' which comprise of actual blog posts that could be iterated upon and rendered in the index — these 'post' pages are actually affected by the included md.js file.

[This blog post](http://jxnblk.com/writing/posts/static-site-generation-with-react-and-webpack/#create-a-data-file) I had come across while searching for an answer to this referenced something called a 'data.js' file which seems to enable what I'm attempting to do.

Thanks!

**Comment by KyleAMathews** [comment]
All pages come from `/pages`. You can put react components there and they become pages automatically. If you put in static files e.g. markdown, they need a wrapper component but also become pages automatically.

That help?

**Comment by edouerd** [comment]
It did! Thanks!
