### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by benjaminhoffman** [gatsbyjs/gatsby#4590]
## Description
Adding `async/await` to Gatsby's blog creates this error:

`email-capture-form.js:46 Uncaught (in promise) ReferenceError: regeneratorRuntime is not defined`

After searching the issues, I've seen this pop up a couple times.  

This line is throwing the error: https://github.com/gatsbyjs/gatsby/pull/4589/files#diff-0b944fc95fef100bc9dd4aa6fbcb4647R44

**Comment by m-allanson** [comment]
Hey @benjaminhoffman 👋 I think this can be fixed with the following steps: https://github.com/gatsbyjs/gatsby/issues/3931#issuecomment-364414141

**Comment by benjaminhoffman** [comment]
Hey @m-allanson !  Thanks for the comment. Sadly, I'm not sure if that did the trick. :( . I followed that step for _both_ gatsby and for my plugin.

The branch is `mailchimp2` and here is the diff: https://github.com/gatsbyjs/gatsby/compare/master...benjaminhoffman:mailchimp2?expand=1

Do you have a moment to pull down my branch?  My steps:

```bash
git checkout -b mailchimp2
git pull origin mailchimp2
cd www
rm -rf .cache public node_modules
yarn install
yarn build
yarn serve
```

Then I load this page: http://localhost:9000/blog/2018-03-07-why-we-created-the-plugin-library/

The error still shows in the console.  Any other guesses on what it can be?

**Comment by m-allanson** [comment]
I've had a look at this and got as far as confirming the error using your above repro steps. But I haven't had a chance to dig any further yet. 

I'd like to come back and work out a fix for this issue later. In the interest of getting your PR going again it may be worth writing the offending method with Promises instead of async / await, particularly as async / await isn't used anywhere else in the Gatsby site.

**Comment by benjaminhoffman** [comment]
refactored to using `then/catch` instead of `async/await` . thx for the rec @m-allanson !
https://github.com/gatsbyjs/gatsby/pull/4589

closing this.

**Comment by thebarty** [comment]
Just ran into the same error. It sucks…
