### ISSUE TITLE
Autobuild docker image with CLI

### ISSUE THREAD

**Issue by spawnia** [gatsbyjs/gatsby#4591]
I would like to use Gatsby, but not install it locally but rather through Docker. The [official image](https://hub.docker.com/r/gatsbyjs/gatsby/) looks like it is abandoned and after further examination, it serves the purpose of hosting a ready built site - while valuable, this is not what i expected the official image to do.

Because of this, i propose changing the official image. The official image should contain the CLI and be ready to use to create new projects, develop and build them. Hosting the site seems like a step that comes after that and as such, could be made into a seperate image.

I really like the approach taken [here](https://github.com/aripalo/gatsby-docker/) and think this could form the basis for the official gatsby image. Also, i would be willing to contribute and set up the build.

**Comment by KyleAMathews** [comment]
Yeah, making the Docker image work for both development and production usages could make sense. They're the same thing except production use also needs Nginx to host the site.

@aripalo what do you think? Would you be interested in working together with @spawnia on something?

**Comment by spawnia** [comment]
There is one issue with running the CLI on Docker, which is that exposing `localhost` does not allow access from outside of the container. For that, the flag `--host 0.0.0.0` has to be added to the develop command.

While i like that @aripalo has considered this in his entrypoint, in the long run i think that overwriting the command like this could cause feature drift.

Also, do you think that doing a `npm install -g gatsby-cli` as part of building the Docker image is a good idea? While this is certainly the easiest approach and avoids setting up a second build for the CLI tool, this brings another challenge with it: Building the CLI image must be done after a new version is published to npm. Docker Hub allows adding webhooks to build a new image, can such a trigger be added after a new version becomes available on `npm`?

**Comment by izuolan** [comment]
the base image `node:9.5-alpine` maybe have a bug, it can't install `pngquant-bin`.

```
npm install -g pngquant-bin
```

I tried a lot of alpine images will not work.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
