### ISSUE TITLE
Multi-language example using Gatsby and jsLingui

### ISSUE THREAD

**Issue by morloy** [gatsbyjs/gatsby#4592]
At [Ledgy](https://www.ledgy.com) we just launched our new website that uses Gatsby together with jsLingui to create a German version.
Since there are only examples on using `i18next`, we thought it might be useful to also share the [source](https://github.com/morloy/ledgy.com) with the community.
For further instructions on setting up jsLingui with Gatsby, see the [related thread in their repository](https://github.com/lingui/js-lingui/issues/158#issuecomment-371096693).

I hope to see more pages with jsLingui soon! It was very useful to create the translated version of our website.

**Comment by m-allanson** [comment]
Thanks @morloy!  It's great to see more examples of how people are handling this. Would you be able to add your site and source to the [showcase](https://github.com/gatsbyjs/gatsby/blob/master/README.md#showcase)? Currently this is just a list of links, but I believe there are future plans to expand on it.

Your example might also be of interest to people reading #3853.

**Comment by m-allanson** [comment]
Thanks for the showcase link! I'm going to close this for now. If you wanted to, I'm sure people would be interested in a more detailed write up :)

**Comment by dcroitoru** [comment]
This inspired me to create a gatsby starter:
https://github.com/dcroitoru/gatsby-starter-i18n-lingui

**Comment by m-allanson** [comment]
Nice! Would you like to add it to the community section of the [Gatsby Starters](https://www.gatsbyjs.org/docs/gatsby-starters/) list? The file to edit is here: https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/gatsby-starters.md

**Comment by dcroitoru** [comment]
Thanks!
Yes, I'd like to add it. PR pending (#4741)
