### ISSUE TITLE
Dynamically import component based on GraphQL result

### ISSUE THREAD

**Issue by oltodo** [gatsbyjs/gatsby#4600]
Hi,

I'm developing a style guide for my React app's design system using Gatsby 1.x and I meet troubles to do something.

I would like to create a page for each of my UI components that are defined in a `data/components.yaml` file like this:

```yml
- name: Card
  source: "@scope/card"

- name: Button
  source: "@scope/button"
```

__Nota:__ as you can see, each component are in separated NPM packages.

Creating pages was easy using `gatsby-source-filesystem` and `gatsby-transformer-yaml` plugins, as well as `createPages`'s API.

Actually, troubles come from on how I could require the component from the `source` value coming from the GraphQL result in the related template :

```jsx
import React from 'react';

export default props => {
  const component = props.data.componentsYaml;

  // How make the below line working on?
  const Component = require(component.source);

  return (
    <div>
      <h1>{component.name}</h1>
      <Component />
    </div>
  );
};

export const pageQuery = graphql`
  query ComponentBynName($name: String!) {
    componentsYaml(name: { eq: $name }) {
      name
      source
    }
  }
`;
```

If someone has any idea on how do this, I'll be very grateful!

**Comment by KyleAMathews** [comment]
You should have a module that imports all the components and exposes them on an object e.g.

```javascript
module.exports = {
  card: require(`@scope/card`),
  button: require(`@scope/button`),
}
```

Then require that in and dynamically grab the right component.
