### ISSUE TITLE
Multi language support for sitemap

### ISSUE THREAD

**Issue by KikahaPlus44** [gatsbyjs/gatsby#4603]
## Description

I propose to discuss in which way will be better implement multi language support in gatsby-plugin-sitemap. One of the way, is implement in a way how to google proposed in this article
https://support.google.com/webmasters/answer/2620865?hl=en

**Comment by KyleAMathews** [comment]
Hey @KikahaPlus44, sounds great! Would you like to put together a PR so we can look in more detail at what you're proposing?

**Comment by kakadiadarpan** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub issues, we have to clean some of the old issues as many of them have already been resolved with the latest updates.

Please make sure to update to the latest Gatsby version and check if that solves the issue. Let us know if that works for you by adding a comment 👍

**Comment by kakadiadarpan** [comment]
@KikahaPlus44 would you like to work on this and create a PR for the same?

**Comment by tinder-kyleboss** [comment]
Heya! For those stumbling across this issue looking to internationalize their sitemaps, I do have a bit of good news 😄gatsby-plugin-sitemap actually does support [internationalized sitemaps](https://support.google.com/webmasters/answer/2620865?hl=en)

Let's say your website is https://sitemaps.com and your Spanish version is https://sitemaps.com/es. 

```
// In your gatsby-config.js
siteMetadata: {
  siteUrl: `https://sitemaps.com`,
},
plugins: [
  {
    resolve: `gatsby-plugin-sitemap`,
    options: {
      query: `
        {
          site {
            siteMetadata {
              siteUrl
            }
          }
 
          allSitePage {
            edges {
              node {
                path
              }
            }
          }
      }`,
      serialize: ({ site, allSitePage }) => allSitePage.edges
        .map(edge => {
          return {
            url: site.siteMetadata.siteUrl + path // https://sitemaps.com/page-path
            changefreq: 'daily',
            priority: 0.7,
            links: [
              // https://sitemaps.com/page-path
              { lang: 'en', url: site.siteMetadata.siteUrl + path },
              // https://sitemaps.com/es/page-path
              { lang: 'es', url: `${site.siteMetadata.siteUrl}/es${path}` },
              // The default in case page for user's language is not localized.
              { lang: 'x-default', url: site.siteMetadata.siteUrl + path } 
            ]
          };
        })
    }
  }
]
```

Unfortunately, this will cause most web-viewers to not be able to pretty print the sitemap anymore. For an in-depth reason as to why, check out [How to indicate alternate languages pages?](https://github.com/ekalinin/sitemap.js/issues/37). The sitemap is still a valid sitemap, however.

**Comment by cakasuma** [comment]
any workaround how can we fix pretty print for sitemap?

**Comment by i-bsd** [comment]
> I found a workaround to make the sitemap pretty, got excited and [blogged about making pretty sitemaps with this plugin smile](https://www.felixparadis.com/posts/pretty-sitemaps-with-gatsby-plugin-sitemap-and-xsl-stylesheets/)
> 
> The TL;DR is that you can put an XSL stylesheet in your static folder and modify the XML files `onPostBuild`
> 
> ```js
> // inside gatsby-node.js
> const fs = require("fs");
> // ...
> exports.onPostBuild = () => {
>   fs.readdir("./public/sitemap/", (err, files) => {
>     files.forEach((file) => {
>       fs.readFile(`./public/sitemap/${file}`, "utf-8", (err, data) => {
>         const newValue = data.replace(
>           `<?xml version="1.0" encoding="UTF-8"?>`,
>           `<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="/sitemap.xsl"?>`
>         );
>         fs.writeFileSync(`./public/sitemap/${file}`, newValue, "utf-8");
>       });
>     });
>   });
> };
> ```
> 
> A bit hacky, but it works like a charm.

There really should be an option for this, IMO.
I think there used to be something like: 

`xslUrl: "/sitemap.xsl"`

Can someone make this happen so we don't have to use the onPostBuild hack?
