### ISSUE TITLE
Deploy preview for using-wordpress

### ISSUE THREAD

**Issue by lightstrike** [gatsbyjs/gatsby#4608]
As I was getting together #4538, I noticed deploy preview messages for `gatsbygram` and `using-drupal`. How do those work?

Would it be useful/helpful to get one set up for the `using-wordpress` example? Happy to help here, or getting the using-wordpress example back up in running in general to resolve #4398

**Comment by KyleAMathews** [comment]
Netlify is building the using-wordpress site too — just take the url generated for the other sites and change the e.g. gatsbygram to `using-wordpress`. We didn't want all of them posting comments as that got very noisy.
