### ISSUE TITLE
Don't re render on hash anchors from markdown wrapper

### ISSUE THREAD

**Issue by f0rr0** [gatsbyjs/gatsby#462]
This should be set by default. Markdown headings usually have anchor hashes. The component gets re-rendered if the hash link is clicked.

**Comment by KyleAMathews** [comment]
Oh? Didn't realize this. How do you stop the rerender? Some react-router config?

**Comment by KyleAMathews** [comment]
related: https://github.com/gatsbyjs/gatsby/issues/386

**Comment by emilyaviva** [comment]
What about https://github.com/adjohnson916/anchorate ?

**Comment by f0rr0** [comment]
@KyleAMathews a naive way could be to intercept links with `#something` in `componentDidMount` and then `document.querySelector(`#${something}`).scrollIntoView();`

**Comment by f0rr0** [comment]
that could be followed up with:
```js
window.history.pushState(null, null, `#hash`);
```
However, the back button does not seem to work as expected

**Comment by f0rr0** [comment]
I think this issue was being faced by Phenomic as well https://github.com/taion/react-router-scroll/issues/37

The behavior I am seeing is the same as mentioned in the issue above

**Comment by f0rr0** [comment]
Back button will not work for same page hash anchors with https://github.com/gatsbyjs/gatsby/pull/467
But the scrolling is fixed

**Comment by KyleAMathews** [comment]
On not re-rendering, just was investigating this — easiest solution is to add a `shouldComponentUpdate` on routes and don't render on hash changes. This is possibly something Gatsby could add automatically as we generate the routes and could wrap them with a sCU like this.
