### ISSUE TITLE
404 and SW fallback pages are included in sitemap.xml

### ISSUE THREAD

**Issue by madcatsu** [gatsbyjs/gatsby#4621]
## Description

gatsby-plugin-sitemap includes `dev-404-page`, `offline-plugin-app-shell-fallback`, `404` and `404.html` in generated sitemap. See comment on Issue #4562 by @prince0203

### Steps to reproduce

Include gatsby-plugin-sitemap in gatsby-config.js with the following GraphQL query:

```
{
    site {
        siteMetadata {
            siteUrl
        }
    }

    allSitePage {
        edges {
            node {
                path
             }
         }
     }
}
```

### Expected result

404 and offline service worker pages should be excluded from the generated sitemap.xml

### Actual result

Dev, 404 and service worker fallback pages were included in the sitemap.xml

### Environment

* Gatsby version (`npm list gatsby`): 1.9.158
* gatsby-cli version (`gatsby --version`): 1.1.40
* Node.js version: v8.9.1
* Operating System: MacOS

### File contents (if changed):

`gatsby-config.js`: 
`package.json`: 
`gatsby-node.js`: 
`gatsby-browser.js`: 
`gatsby-ssr.js`:

**Comment by pieh** [comment]
Hey @madcatsu, would you be interested in submitting PR updating defaults? Or maybe even better - adjusting code so it matches for both paths with trailing slash and without one?

**Comment by madcatsu** [comment]
@pieh I believe this one might be best left to someone with more experience in contributing to Gatsby following the standard process. I'd be happy to just fork and submit a PR with @prince0203 proposed changes if someone else has time to test otherwise.
