### ISSUE TITLE
Any way to reduce the size of `__webpack_require__()` in the bundle?

### ISSUE THREAD

**Issue by chmac** [gatsbyjs/gatsby#4625]
## Description

I have a site with ~3.5k, pages loaded from markdown. My `app-*,js` bundle file is ~2.7M. It is not minified because it's >500KB.

I've broken it into chunks, and about 1.5M of the file is repeating sections like this:

```es6
/* 396 */
/***/ (function(module, exports, __webpack_require__) {

        __webpack_require__(
              1
            );
            module.exports = function(cb) { return __webpack_require__.e/* nsure */(137361941401043, function(_, error) {
                if (error) {
                  console.log('bundle loading error', error)
                  cb(true)
                } else {
                  cb(null, function() { return __webpack_require__(3893) })
                }
              });
             }


/***/ }),
```

Is there any way to reduce the size of these repeated sections? There are 62k lines in the file like this, and they're almost all identical. I guess uglify will not actually compress these parts that much.

**Comment by pieh** [comment]
I'll close this in favour of more detailed https://github.com/gatsbyjs/gatsby/issues/4626 . Problem described there is most of what cause app bundle size scaling problems
