### ISSUE TITLE
Suggestions about a CMS that would manage Markdown pages for Gatsby ?

### ISSUE THREAD

**Issue by sebastienfi** [gatsbyjs/gatsby#4629]
## Description

I will soon implement a Gatsby site based on Markdown. I am looking for suggestions on how to provide the editors ability to create pages and edit contents, upload images, etc.
My initial idea is to host the markdown on GitHub and have the editors use the GitHub UI. Do you guys have better suggestions ? The GIT commands should be wrapped in UI as my editors don't know what a terminal is 🦄 
We basically have 2 page template : the regular page and the blog post.

**Comment by zanedev** [comment]
@sebastienfi go with [NetlifyCMS](https://www.netlifycms.org/) it can manage markdown and images with ease.

**Comment by sebastienfi** [comment]
@zanedev Netlify CMS looks good. Thanks for the input!

Anybody knows any good alternative ?

**Comment by zanedev** [comment]
Unfortunately there is nothing open source that is as flexible or feature rich as NetlifyCMS, the rest are all really basic or paid solutions.  Here you can see a good comparison of the alternatives: 

[https://headlesscms.org/](https://headlesscms.org/)

**Comment by KyleAMathews** [comment]
Many headless CMSs support markdown as well. Check out these posts https://www.gatsbyjs.org/blog/2018-2-3-sites-with-headless-cms/ https://www.gatsbyjs.org/blog/2018-2-6-choosing-a-back-end/
