### ISSUE TITLE
Redudant service worker bug

### ISSUE THREAD

**Issue by CharlyJazz** [gatsbyjs/gatsby#4636]
![image](https://user-images.githubusercontent.com/12489333/37713389-2e9d08dc-2ced-11e8-8292-120aa5831eaa.png)

 When recharge by gatsby website:

Configuration: 

``` javascript
module.exports = {
  siteMetadata: {
    title: 'Gatsby Default Starter',
  },
  plugins: [
    'gatsby-plugin-react-helmet',

    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: "DigitalKeys API Documentation",
        short_name: "DigitalKeys API",
        start_url: "/",
        background_color: "#f7f0eb",
        theme_color: "#a2466c",
        display: "minimal-ui",
        icons: [
          {
            "src": "/favicons/android-icon-36x36.png",
            "sizes": "36x36",
            "type": "image/png",
            "density": "0.75"
           },
           {
            "src": "/favicons/android-icon-48x48.png",
            "sizes": "48x48",
            "type": "image/png",
            "density": "1.0"
           },
           {
            "src": "/favicons/android-icon-72x72.png",
            "sizes": "72x72",
            "type": "image/png",
            "density": "1.5"
           },
           {
            "src": "/favicons/android-icon-96x96.png",
            "sizes": "96x96",
            "type": "image/png",
            "density": "2.0"
           },
           {
            "src": "/favicons/android-icon-144x144.png",
            "sizes": "144x144",
            "type": "image/png",
            "density": "3.0"
           },
           {
            "src": "/favicons/android-icon-192x192.png",
            "sizes": "192x192",
            "type": "image/png",
            "density": "4.0"
           }
        ],
      },
    },

    'gatsby-plugin-offline'
  ],
};

```

Site: https://5ab2502c0b79b74dd086b74b--festive-mestorf-04611b.netlify.com/

**Comment by KyleAMathews** [comment]
Not sure — perhaps this Stackoverflow post can help? https://stackoverflow.com/questions/45694239/service-worker-is-installing-with-every-page-reload-though-the-sw-js-did-not-c?rq=1

**Comment by CharlyJazz** [comment]
I do not know, this kind of thing does not happen in create-react-app or in workbox. I had to migrate my entire site.

**Comment by BeomyeonAndrewKim** [comment]
I have same issue but just at Chrome. 
So, I think this issue is related with Chrome.

But, still I do not know how to deal it.

**Comment by CharlyJazz** [comment]
Workbox

2018-03-22 10:53 GMT-04:00 Andrea Kim <notifications@github.com>:

**Comment by fabe** [comment]
I'm having the same issue on multiple unrelated sites, pretty sure it's recent. Only happens when I reload the page while the developer console is opened in Chrome. Some kind of loop going on there. Additional warning:

> Service Worker was updated because "Update on reload" was checked in the DevTools Application panel.

**Comment by CharlyJazz** [comment]
This warning is normal. @fabe. The SW can work with normality even the warning exist

**Comment by fabe** [comment]
@CharlyJazz Yes, but the warning is being shown constantly in an infinite loop, together with the redundancy error. Here's a [video](https://streamable.com/z9mwu). Sorry for the confusion.

**Comment by dunglas** [comment]
https://api-platform.com also has this problem, in the exact same conditions (only on Chrome, and everytime we deploy a new version).
It prevents the site from working until the browser fetches a fresh SW.

**Comment by LekoArts** [comment]
Should be fixed now. If you encounter other issues with serviceWorker please open up a new issue!

**Comment by johant87** [comment]
@LekoArts  Interesting, I see a comment that this issue is fixed? but I ran into the exact same issue as the original poster now with the latest version of gatsby/the offline plugin.

**Comment by interglobalmedia** [comment]
I have the exact same issue now. Gatsbyjs, my projects, downloaded starters, whichever Gasbyjs, does not work with Chrome right now. And I have tried on the latest (or nearly latest) of everything. Works fine with Firefox and Safari. But the question is, would I really want to work with either of those browsers? I got the following warning in Chrome Developer Tools Console:

`app.js:66 Warning: found one or more service workers present. If your site isn't behaving as expected, you might want to remove these. `

And a zillion messages from workbox. I use it in my regular React projects and never had a problem. But there is a problem here all of a sudden. I have been removing the .cache, public, node_modules, and re-installing, re-building, updating plugins, etc. Nothing helps. Just started all of a sudden yesterday. But I think it has been slowly building up to this.

**Comment by maxcan** [comment]
@interglobalmedia I'm experiencing the same.  did you ever resolve that?

**Comment by laradevitt** [comment]
I'm seeing this issue sporadically on a site that has been live for awhile now. Having a hard time replicating it but I'll keep trying. As far as I know it only ever happens when dev tools is open in Chrome. All packages are  up-to-date.

**Comment by GlebDolzhikov** [comment]
I have same issue with gatsby,  continuously reload site in chrome in dev mode.

**Comment by wardpeet** [comment]
can you post a screenshot of the application tab?
![image](https://user-images.githubusercontent.com/1120926/78336769-39949280-7590-11ea-834a-a51829e0d223.png)

Also please open a new ticket with new information.
