### ISSUE TITLE
Rendering webp images using GatsbyContentfulSizes_withWebp

### ISSUE THREAD

**Issue by imshuffling** [gatsbyjs/gatsby#4643]
Trying to render images using `GatsbyContentfulSizes_withWebp` but I cannot seem to get it to work.

![screen shot 2018-03-21 at 16 45 12](https://user-images.githubusercontent.com/739061/37723993-b65f05c4-2d27-11e8-8089-8307c3ea1342.png)

I've got `GatsbyContentfulSizes` pulling through the images ok, am i missing something?

References
https://using-contentful.gatsbyjs.org/image-api/
https://using-gatsby-image.gatsbyjs.org/

**Comment by m-allanson** [comment]
Are you seeing any error messages? 

Could you fill out the issue template or link to an example repo?

**Comment by imshuffling** [comment]
Hi @m-allanson 

Link to repository - https://github.com/imshuffling/davidrich.es/blob/master/src/templates/portfolio-post.js

I would like to use `GatsbyContentfulSizes_withWebp` if possible, do you know where I'm going wrong?

Cheers.

**Comment by m-allanson** [comment]
As far as I can tell, this works? Changing your `...GatsbyContentfulResolutions` fragment to `...GatsbyContentfulResolutions_withWebp`, and then logging `data.contentfulPortfolio.image.resolutions` shows the following:

```js
{
    base64:
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAALABQDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAgDBgcJ/8QAJRAAAQMDBAEFAQAAAAAAAAAAAQIDBAUREgAGByExExQiQVEV/8QAFwEAAwEAAAAAAAAAAAAAAAAAAwUGB//EACQRAAEDAgQHAAAAAAAAAAAAAAECAxEABAUSIVEiMYGRscHR/9oADAMBAAIRAxEAPwBe5HLzu1xR2ajSxFmVNj3Meq0NSHD2sCy21DF0lKU/Enq6SMfAulO4Ac3RyzSaqmGzWtly2W3GXZUgxW0JNgpSkhOeVikYkC4INzY6h4r3ZUaTSYVNhmJHistpwwgsep8gMruYZkn9JPgfmmo4JbFV2zQ3pSnHVuPOrWC4oJWoqJJUkGx8m1x19W1neGMF+7UhoBMAzqdR2kGNjHOmTZS2CtesRt7nxWIjj/kTabrsbb9bc2LAfV7n+HAqLkhqOtQAVZYAvcp8EdeOxY6NdGKZBYiQGGmmwhsJ6TckDv60apEWVxlHCk9T8oq7lOYxNf/Z",
    width: 960,
    height: 539,
    src:
      "//images.ctfassets.net/anjlutb8dq3v/4xATseuvXWyGy0aOGe8SsO/3c3924c251f194a7a86754b637a598c5/01.2bbb1a86.jpg?w=960&q=50",
    srcSet: "",
    srcWebp:
      "//images.ctfassets.net/anjlutb8dq3v/4xATseuvXWyGy0aOGe8SsO/3c3924c251f194a7a86754b637a598c5/01.2bbb1a86.jpg?w=960&q=50&fm=webp",
    srcSetWebp: "",
  }
```

**Comment by imshuffling** [comment]
![screen shot 2018-04-19 at 14 40 18](https://user-images.githubusercontent.com/739061/38994930-9ea78ba8-43df-11e8-84bc-7feca4f4ce02.png)

I don't think I'm doing this right.

<img width="557" alt="screen shot 2018-04-19 at 14 40 53" src="https://user-images.githubusercontent.com/739061/38994971-b1adc906-43df-11e8-9d52-46b15976f61b.png">

Do I need to specify it being webp below?

<img width="830" alt="screen shot 2018-04-19 at 14 41 14" src="https://user-images.githubusercontent.com/739061/38995016-c9b8d09a-43df-11e8-82a2-736dd3974d8d.png">

**Comment by pieh** [comment]
what version of contentful plugin are you using? this was added in gatsby-source-contentful@1.3.37

**Comment by m-allanson** [comment]
Try removing your `node_modules` folder, `yarn.lock` file and `package-lock.json` file, then run `yarn` again.

**Comment by imshuffling** [comment]
Ahhh I was using - "gatsby-source-contentful": "^1.3.23".
Thanks guys, I upgraded to 1.3.37 and it's now working!
