### ISSUE TITLE
GatsbyJS Newsletter

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#4644]
## Description

We have a lot of people signed up through MailChimp to receive a GatsbyJS newsletter, and they haven't received anything yet :) which means we need to actually write newsletters. Suggestions on the following?

Format:
* Product announcements, new features
* Bug fixes
* Site highlight of the week + interview with site's creator
* New docs / tutorials / UX projects that have been finished or need help
* Funny quote
* Recommended reading
* Blogposts

Options for how to create drafts:
* We could create a Trello board and throw links to articles on there and then we'll link to the Trello board in the email
* We could have a shared google drive folder and send out a new googledoc every week
* We could somehow draft things in github (not my preference since imho googledocs work much better for long-form prose editing & reviews)

**Comment by alysonpaige** [comment]
I saw the first newsletter went out yesterday, nice job! Need any help?

**Comment by shannonbux** [comment]
Hey @alysonpaige for sure! What kinds of things would you like to help with? And what collaboration environment do you prefer? We're drafting the emails in MailChimp currently. There are some more ideas above in this issue (googledocs, trello, etc.)

**Comment by alysonpaige** [comment]
@shannonbux Trello or Google Docs is fine, I'm flexible so whatever works for you or the current workflow. If interested, there could be a section on Gatsby in the News or "In the Wild" which could link to external sources of either well polished Gatsby sites or articles or references that make positive mention of Gatsby. I can help with the newsletter format/creation or the aggregation of content available to include in them. If you have any suggestions, let me know - I'm open!

**Comment by shannonbux** [comment]
That'd be awesome! Email me at shannon@gatsbyjs.com from whatever email you'd like to use to collaborate and I'll invite you to the next newsletter draft :)

**Comment by shannonbux** [comment]
Closing this issue for now because @alysonpaige and I will handle May's newsletter. Always happy for more help with this if anyone runs across this closed issue!
