### ISSUE TITLE
Add semicolons after Flow type expressions to restore syntax highlighting

### ISSUE THREAD

**Issue by calcsam** [gatsbyjs/gatsby#4647]
Our lack of semicolons on Flow `Type` expressions like eg `type Plugin = { name: string, }` (see eg https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/redux/actions.js#L77) causes syntax highlighting to fail in Sublime Text, as documented in https://github.com/babel/babel-sublime/issues/309. If we add semicolons in, highlighting works again. 

A couple screenshots from my local environment:

Without semicolon:
![image](https://user-images.githubusercontent.com/4388699/37734381-35e1f092-2d08-11e8-9a56-fd03a43de62a.png)

With semicolon:
![image](https://user-images.githubusercontent.com/4388699/37734395-41403c14-2d08-11e8-984a-514f6df7c3e3.png)

**Comment by KyleAMathews** [comment]
We're a semicolon-less repo. Not sure adding semicolons in a handful of spots to workaround a bug in a editor's syntax highlighting makes sense?

**Comment by emwalker** [comment]
Since there are repos that do not use semicolons, a better approach would be to fix the syntax highlighting rules for flow, as seen here:

https://github.com/babel/babel-sublime/issues/309#issuecomment-306340132

**Comment by KyleAMathews** [comment]
:+1:
