### ISSUE TITLE
Creating custom graphql nodes after fs changes in onPreBootstrap

### ISSUE THREAD

**Issue by lmaddio** [gatsbyjs/gatsby#4649]
I am using onPreBootstrap for reading some json and generating new ones from their content, saving them in a folder inside `src`, like a plugin would do. I wanna that new jsons to be available to graphql but they never do, I am using onCreateNode for generating the new node as `gatsby-transformer-json` does (I can't use this plugin because it never reads my new json files, everything in onPreBootstrap is made synchronous)

**Comment by KyleAMathews** [comment]
If you want your generated JSON to be turned into nodes, you need to add gatsby-source-filesystem and point it at the generated JSON files.

https://www.gatsbyjs.org/packages/gatsby-source-filesystem/

**Comment by lmaddio** [comment]
Your answer didn't applied to my needs, because the source-filesystem runs and detects the json that was originally created but not the new ones that I created in the onPreBootstrap, even so I put the path in the config

**Comment by pieh** [comment]
Can you confirm that your file is created before `source and transform nodes` step? If you can - please share reproduction repository

**Comment by lmaddio** [comment]
I have do some console.logs and yes, in sourceNodes functions they exists (I am taking info from them at this point actually for putting data in graphql) I will try to give you an example in a few hours. Thanks
