### ISSUE TITLE
HMR not working with Stateless components?

### ISSUE THREAD

**Issue by TheAncientGoat** [gatsbyjs/gatsby#465]
Currently, if I create a stateless component, updating it does not trigger HMR re-renders. It may be because https://github.com/danmartinez101/babel-preset-react-hmre is deprecated due to the transform family hot loaders being deprecated https://github.com/gaearon/react-transform-hmr - there are a few issues suggesting changing to https://github.com/gaearon/react-hot-loader 's V3 release (which is still in beta)

Has anyone tried this out?

**Comment by KyleAMathews** [comment]
I actually just got this working on the 1.0 branch. See https://github.com/gatsbyjs/gatsby/commit/5185c3ab69d6750de0f1ced9153ba99cc0f2b2a3

Would you like to try backporting this to the 0.x line? It should be fairly straightforward. React-hot-loader 3 beta has been stable in my testing. For backporting, just move things from the app.js to web-entry.js.

**Comment by TheAncientGoat** [comment]
Ok, implemented React Hot Loader 3 (well, removed babel-hmre-preset and used react-hot-loader's appcontainer) here: https://github.com/TheAncientGoat/gatsby/commit/376888654b64a9f45bdd69571e2b7bb32d85d333 

It still doesn't seem to do HMR on stateless components when they're exported though? Stateless components inside stateful components update as expected - not sure if I've overlooked something here, is the transition to webpack-dev server also necessary?

**Comment by TheAncientGoat** [comment]
Just realized that npm link isn't the only thing required to update gatsby - the locally installed version also needs to be updated (of course). Doing so indicates that it isn't implemented properly in that commit yet - element being passed to the container is undefined, will resolve now

**Comment by TheAncientGoat** [comment]
Ok - it seems that with my implementation, `import { AppContainer } from 'react-hot-loader'`  results in an undefined AppContainer, as importing the 'react-hot-loader' module by itself results in a sourcemap wrapper - no idea why this is happening; not going to dig into it further for the time being - will rather see if I can test out the alpha instead

**Comment by KyleAMathews** [comment]
You might be running into a similar problem as I did — make sure you've removed all the old hot reloading stuff (include the hapi-webpack plugin) and then run `npm prune`.

**Comment by TheAncientGoat** [comment]
If the hapi-webpack plugin is removed, it needs to be replaced with webpack-dev-server right? Seems like quite a few things were re-written to support that - my naive swap runs the dev server but webpack doesn't seem to be compiling a serve able bundle (but tests pass?)

**Comment by KyleAMathews** [comment]
Yes it does. Look at my commit, it's all there.
