### ISSUE TITLE
Using page-specific data on layouts.

### ISSUE THREAD

**Issue by pauldotknopf** [gatsbyjs/gatsby#4651]
It doesn't look like it's possible, but I just wanted to clarify.

I have a common layout for my pages. I'd like to hide/show components, add classes to body, etc, on this layout for specific pages.

For example, some front matter properties.

1. ```showGutter```: Add/remove body class that changes style a little.
2. ```showMenu```: Show or hide a common side menu.

I don't mind configuring these properties with the ```createPage```.

```js
createPage({
    ...
    context: {
        showGutter: true,
        showMenu: false
    }
});
```

Maybe there is some way to do what the helmet plugin does, using the ```onRenderBody``` method?

**Comment by KyleAMathews** [comment]
Yeah, layouts are a bit wonky so stuff like this is hard as you don't have access to page data. You'd need to add to the layout component which pages should have gutters/menus and then look at the props.location.pathname (the layout component's render function is called on every page change) to decide to show or hide menus.

We're removing the special layout component in v2 for this and other reasons https://github.com/gatsbyjs/gatsby/issues/3830
