### ISSUE TITLE
Add support for inlining fonts

### ISSUE THREAD

**Issue by tlvenn** [gatsbyjs/gatsby#4652]
If i am not mistaken, it's not possible or easy to inline a given set of fonts with Gatsby at the moment. It would be great if this could be added.

**Comment by zionis137** [comment]
Do you mean something like this: 
https://github.com/KyleAMathews/typefaces

**Comment by tlvenn** [comment]
unless I am missing something, those fonts are self hosted but not inlined in the page itself using base64.

I was kinda thinking of leveraging something like that: https://www.npmjs.com/package/base64-inline-loader

**Comment by KyleAMathews** [comment]
This would be a great plugin to add! Check out the guide for plugin authoring https://www.gatsbyjs.org/docs/plugin-authoring/
