### ISSUE TITLE
gatsby-plugin-feed unusable for article images.

### ISSUE THREAD

**Issue by vojtechruz** [gatsbyjs/gatsby#4653]
I am using gatsby-plugin-feed to generate my RSS feed. I am using markdown files as sources. These files contain images.

When gatsby site and the RSS is built, all the images are replaced with a version with appended hash so the filename is unique between builds. This link is also used for images in RSS.

This means whenever I update my site or release a new post, all the images have new names - that means my RSS is now broken. Every time I release a new article, all the existing RSS posts downloaded and cached by RSS readers have image links pointing to non-existing resources.

**Comment by KyleAMathews** [comment]
The hash part of the name is a hash of the image file so shouldn't change between builds. If they are, that's a bug we should fix.

**Comment by KyleAMathews** [comment]
As long as you don't change source images, the generated URLs don't change. If this is still causing difficulties, please create a sample site reproducing the problem and create a new issue.
