### ISSUE TITLE
[gatsby-image] Position prop not being used

### ISSUE THREAD

**Issue by mbavio** [gatsbyjs/gatsby#4654]
I need the `.gatsby-image-outer-wrapper` element to have absolute positioning. By default, [it's positioned as relative](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-image/src/index.js#L227). According to that line, you can change it by using the styles object. 

But there's also an [optional position props](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-image/src/index.js#L441) for the component that is not being used at all. Is this a missing functionality? If so, I would be more than willing to provide my first PR in here!

As a side note, can you explain me why it's not just using the value being sent by props than setting `position: initial`?

**Comment by KyleAMathews** [comment]
Oh weird, yeah that position prop isn't used. Don't remember how it showed up there. Would you like to remove that for us in a PR?

`position: initial` is only set if there's not something set in the style object right?

**Comment by mbavio** [comment]
@KyleAMathews yup, I can definitely do that. Regarding `position: initial`, if you look [in here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-image/src/index.js#L227), it's set if `absolute` is being passed, which is completely weird. Would you like for me to also include a fix for that on the PR?

**Comment by KyleAMathews** [comment]
We set the child element to absolute https://github.com/gatsbyjs/gatsby/blob/1e035a514ad5e6651df7255594c126c564139bb0/packages/gatsby-image/src/index.js#L235

**Comment by CanRau** [comment]
would love to be able to position the outer wrapper to absolute :+1:

**Comment by mattiasnordqvist** [comment]
I've messing around with this too. At least remove it from the docs https://www.gatsbyjs.org/packages/gatsby-image/

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
