### ISSUE TITLE
`request` should be added to `gatsby` package.json

### ISSUE THREAD

**Issue by vjpr** [gatsbyjs/gatsby#4656]

**Comment by m-allanson** [comment]
Hey @vjpr can you add a bit more info about this request?

**Comment by pieh** [comment]
So I remember I had this issue once - gatsby develop errored out because it couldn't find `request` module ( https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/commands/develop.js#L8 ). It seems like gatsby depends on this module being hoisted.

**Comment by KyleAMathews** [comment]
Looks like `request` is in the v2 gatsby package.json so closing this.
