### ISSUE TITLE
 DefinePlugin cannot be invoked without 'new'(similar previous solutions aren't working)

### ISSUE THREAD

**Issue by SaintEmbers** [gatsbyjs/gatsby#4663]
I'm trying to add a plugin to webpack config through gatsby-node but I'm getting an error that says TypeError: Class constructor DefinePlugin cannot be invoked without 'new' ... The going solution is to have:
  exports.modifyWebpackConfig = ({ config, stage }) => {
    config.plugin("define-plugin", webpack.DefinePlugin, [{"global.GENTLY": false}])
    return config
  }
But it isn't working for me.  I have tried with webpack 3 and webpack 4.  Any help would be much appreciated. Thanks!

**Comment by KyleAMathews** [comment]
Gatsby supports only webpack v1 btw.
