### ISSUE TITLE
Maintain light purple selected state in plugin library

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#4670]
## Problem

I observed someone using the plugin library yesterday, and noticed that this workflow has a painpoint for him:

1. He selected a plugin from the left-hand cards
2. On the right hand side of the screen, he scrolled to the bottom of the READme file for that plugin
3. He wanted to look at other similar plugins that were already pulled up on the left, but didn't remember which plugin he was on, so he clicked on the same plugin name again.
4. Then he was confused since the READme file didn't change, so he scrolled to the top of the READme file to remind himself what plugin he was looking at.

## Solution

When someone clicks a plugin card on the left, if the light purple selected state persisted until they click on another plugin card, they wouldn't have the problem described above.

**Comment by KyleAMathews** [comment]
@fk we had styles for this right?

**Comment by calebsylvest** [comment]
@shannonbux sounds like what you are saying is a Current state needs to be shown on the plugins list. Currently, there is a Hover state, but no Active/Current indicator.

Here's a simple concept to consider if these styles don't already exist:
![gatsby-plugin-states](https://user-images.githubusercontent.com/4457883/37870218-e7651f62-2f95-11e8-96e5-2b7a9f593c35.png)

**Comment by tsriram** [comment]
So we have the styles for selected state of a search result card but the logic to check if a result is selected is broken. Before I push a fix for this, is the existing style for the selected plugin enough? Or should I change the style as described above?

This is how it looks with the current styles:

![image](https://user-images.githubusercontent.com/450559/37887425-510386f8-30df-11e8-807e-1cafe850fd15.png)


@shannonbux

**Comment by KyleAMathews** [comment]
Yeah, the current styles are fine — let's get it restored first and if we think the styles should be changed, let's do that in a follow-up PR.

**Comment by shannonbux** [comment]
Looks like this is done! Will close and thanks everyone!!!

**Comment by fk** [comment]
Sorry @KyleAMathews, only saw your comment now :-/ (thanks to @shannonbux' last comment from today and Gmail filters finally set up 🎉). Not opposed to make the current "selected" state clearer, and I also like the hover-state @calebsylvest suggested – seems a bit lighter than the current ones, while still visible enough?

Thanks @tsriram! 🤗<3
