### ISSUE TITLE
Plugin library filters and sorting enhancements

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#4671]
## Problem

I observed someone going through the plugin library and saw that they wanted to be able to sort by category, especially by whether a plugin was a "source" plugin or not.

## Solution
* Introduce filters 
* Introduce sorting

Don't know which would fit in filters and which would fit in sorting:
* category
* popularity
* what version of Gatsby the package works with
* date added (this also brings up the possibility of featuring particular plugins based on some criteria, like recently added OR most popular, etc)

**Comment by LeKoArts** [comment]
Filters:
- Category
- Gatsby Version (I'd only use major(?) version of Gatsby, so currently probably all plugins should work)

Sorting:
- Name
- Popularity
- Date of the last update

**Comment by shannonbux** [comment]
Sort of related to issue #4827 because as we expand what categories of plugins are included in the library, the naming conventions for plugins will likely need to change.

**Comment by shansmith01** [comment]
Hey @shannonbux, There is a load of new plugins being added (over 500 I recall from the Gatsby days keynote) but the discovery of new plugins is pretty tricky.

The UX is also a bit painful at the moment. As a user each time I scroll the list of plugins I need to click to load more. On clicking plugin, the list goes back to the top on redirect. On clicking back the list still stays at the top forcing the sure to start scrolling and clicking load more.

While I'm at it I would think this is low hanging fruit from a content marketing point of view for your blog/email list. I would be stoked to get at weekly/month email highlighting new plugins.

**Comment by shannonbux** [comment]
@shansmith01 Ah great feedback. Setting up calls to watch people using the plugin library soon! Want to be one of them? ;) 

Highlighting new plugins is a great idea for the newsletter, too

**Comment by shansmith01** [comment]
Sure thing @shannonbux count me in

**Comment by shannonbux** [comment]
ok I'll write that down; will email you once that round of research starts! Thanks @shansmith01!
