### ISSUE TITLE
Plugin library list sites that use plugin

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#4672]
## Description

For each plugin, it would be awesome to include a list of websites (and maybe the number of websites) that are using the plugin, so that people can browse the src code for those sites and also see more demos of plugins in action.

**Comment by ajayns** [comment]
I totally agree with this! More than the documentation itself, people would love to see real world use cases and examples that help them decide how to fit it in their own project itself. 
@shannonbux
