### ISSUE TITLE
ES6 Modules

### ISSUE THREAD

**Issue by mjurczyk** [gatsbyjs/gatsby#468]
# Issue

In the latest build of Gatsby, loaders doesn't seem to work with ES6 modules' `import/export`, even though sample loaders are written with those.

The issue occurs when I try to _modify_ a loader, if I leave them as they are after installation, nothing seems to happen.

`import/export` seem to work perfectly for `pages/`.
# Specs

Gatsby ver. - `0.12.9`
Node ver. - `v5.0.0`
OS - macOS Sierra v10.12

**Comment by KyleAMathews** [comment]
This is an oddity around Babel and .babelrc. Gatsby sets Webpack up to load JS files for your project JS files using babel-loader but afaik doesn't let you use the same babel-loader setup for loading custom loaders. Those only use Babel if you put a `.babelrc` in your project directory.

I removed the .babelrcs from the official starters recently which is perhaps is causing the problem you're seeing?

So the easiest thing you can do is to just drop a .babelrc in your project e.g. restore https://github.com/gatsbyjs/gatsby-starter-default/commit/ba341b9dbc14eab4e0858a2d72d084351d438204

It'd also be great if you wanted to investigate if there's a way to make Webpack load loaders using babel-loader. I don't think there is but it'd be nice.

**Comment by SanthoshRaju91** [comment]
@KyleAMathews I have a similar, I don't want open up another issue.

In `gatsby-node.js`, importing writing a source plugin

```
import { GraphQLClient } from 'graphql-request'
```
This throws me the same error, even though I added a .babelrc and downloaded babel-present-env.
