### ISSUE TITLE
[v2] Add api "sourceNodesStatefully" for plugins that update nodes themselves (so as to make calling sourceNodes repeatedly safe)

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#4682]
To migrate:

- gatsby-source-filesystem
- gatsby-source-sanity
- gatsby-source-datocms
- gatsby-source-contentful

If we make this migration, then we are able to call `sourceNodes` safely on any source plugin. When we do that, we'll also need to add garbage collecting for source plugins when we call them.

**Comment by KyleAMathews** [comment]
Hmm confused as this didn't happen :-(

Sep 7 me was mistaken!

**Comment by KyleAMathews** [comment]
@gatsbyjs/core we need to do this sooner than later as having gatsby-source-filesystem use `sourceNodes` will (is?) cause trouble with Gatsby Preview as every time we refresh nodes, a new Chokidar instance will be setup to read nodes which eventually will grow memory until it kills the process.

/cc @thebigredgeek @rase-

**Comment by m-allanson** [comment]
Stop that, gatsbot.

**Comment by wardpeet** [comment]
@m-allanson should I add it to oss-roadmap?
