### ISSUE TITLE
[v2] Move reducers to store data in Maps and Sets where appropriate as much more efficient/rich data structures vs. arrays

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#4685]
e.g. right now we're storing pages and nodes in an array and updating these can get mildly expensive as we loop over a long array every time we add a page or node to check if the new page/node is a duplicate or not. Using a Map would be much cheaper.

Also, @docwhat ran into a weird bug that replacing the array with a map fixed.

**Comment by Steveeeie** [comment]
Please do this I can’t live with the slow build time any longer 😩

**Comment by m-allanson** [comment]
@Steveeeie did you see #6226? Hoping to get that merged in fairly soon.

**Comment by pieh** [comment]
This was done in https://github.com/gatsbyjs/gatsby/pull/6226
