### ISSUE TITLE
Auto build and deploy whenever a post is added to firebase database.

### ISSUE THREAD

**Issue by Abdelrahman146** [gatsbyjs/gatsby#4687]
Hello everyone,

I'm working on a simple project using Gatsby + Firebase. and what I need is an auto Build and Deploy to be triggered whenever a post is added to firebase database ... 
I would like to know how to make a simple app that whenever a post is added to firebase database an auto Build and Deploy will be triggered. 

 I need to do this because I want the post pages to be server-rendered.

I didn't start my project with details yet. but I'm thinking of having firebase as a data source, and my source code will be on Github, and the host is on firebase web host.

I would appreciate any kind of help, Thanks.

**Comment by KyleAMathews** [comment]
It looks like you can setup a Cloud Function which triggers on every write https://github.com/firebase/functions-samples/tree/master/minimal-webhook

Have that webhook be sent to wherever you're building the site to trigger a new build.

Good luck!
