### ISSUE TITLE
[v2] add error boundaries around pages so harder to break sites

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#4691]

**Comment by tsriram** [comment]
Have any content in mind to show from error boundary when there's an error?

**Comment by davidbailey00** [comment]
Is this related to #4779, or for general errors / errors which could be caused by the users?

**Comment by KyleAMathews** [comment]
Yeah, for user errors so they don't break the site as a whole. A page could throw an error but the user can still navigate.
