### ISSUE TITLE
Unhandled async method somewhere.

### ISSUE THREAD

**Issue by pauldotknopf** [gatsbyjs/gatsby#4699]
So, I am using ```gatsby/dist/bootstrap``` manually from my application. I have to embed Gatsby.

However, when I call this function, my application will never exist due to an unhandled async callback. 

This seems to exist in your production code, but you handled it in the CLI by manually exiting the process.

https://github.com/gatsbyjs/gatsby/blob/bfb8f9446e38894497b63163bf8bf9a248572d8a/packages/gatsby-cli/src/create-cli.js#L11

I am trying to dig down what call is causing the issue. I've started by commenting out the entire ```gatsby/dist/bootstrap``` function, and manually bring things back one by one to determine at which point the error is introduced. The first line I came across causing the issue is this:

https://github.com/gatsbyjs/gatsby/blob/bfb8f9446e38894497b63163bf8bf9a248572d8a/packages/gatsby/src/bootstrap/index.js#L272

Any ideas? I could dig further into ```../utils/source-nodes``` to determine where at *in there* is causing the issue, but before I do, I'd like get a sense of how much of an uphill battle this would be to find all the problematic areas.

What do you think? Was that manual ```process.exit``` you added because there were numerous unhandled async methods, and it was just easier to manually exit the process? Since the ```process.exit``` was added, I wonder how many problems there are now that have gone unnoticed.

**Comment by m-allanson** [comment]
I don't know the answer to your `create-cli.js` question... however if there are any unhandled callbacks it'd be great to track them down. Are you seeing errors about unhandled callbacks? Or do you have an example repo that replicates the issue?

**Comment by pauldotknopf** [comment]
It is pretty straightforward to reproduce.  See [here](https://github.com/pauldotknopf/docgen/blob/6dad945c1d6a24fb67099db13ea9a7d9fd25862e/packages/docgen-gatsby/src/index.ts#L14) (excuse the typescript) .

After calling the ```buildDirectory``` method, the only way to exit the node process is with a ```process.exit(0)```.

Later, I'll fork Gatsby and add a package that will reproduce it so that it can be easier to hunt down the issue.

**Comment by pauldotknopf** [comment]
Also, I am not seeing any errors about the callbacks. It was my understanding that logging is only done for unhanded *rejections*.

**Comment by KyleAMathews** [comment]
Curious why you're embedding Gatsby code somewhere? Our code isn't designed for this and it's not something we're going to support. It might be simpler to just run Gatsby as a sub-process.

**Comment by pauldotknopf** [comment]
Yeah, I might just do the sub process route.

The reason I'm embedding is because I am trying to hide the complexity of Gatsby from my users. They aren't even comfortable in the command line.

However, requiring ```process.exit``` seems like a bad approach to handle bugs deeper in the code base.

**Comment by KyleAMathews** [comment]
We catch all errors and then decide what to do with them. Sometimes we exit, sometimes we don't. Gatsby is a system which is why simply pulling in a single module won't work.

I know of others that have taken the sub-process route with success.
