### ISSUE TITLE
Page indexes

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#47]
Frequently when creating a site you'll want to reference pages elsewhere e.g. on index pages or menu sections.

To simplify this, it'd be nice if you could create ad-hoc page indexes something like:

```javascript
const blogIndex = createIndex('/blog/*.md', {sort: (page) => page.meta.date})

// Now on an index page.
latestBlogPosts = blogIndex({first: 10})

// Render links...
```

**Comment by MoOx** [comment]
I handled this in [statinamic](https://github.com/MoOx/statinamic) by creating a [collection.json in the webpack loader that consume md](https://github.com/MoOx/statinamic/blob/15dee2893c546b1ecb199d00560ba2684079422b/src/markdown-as-json-loader/index.js#L68-L75).

I also provide a [simple helper](https://github.com/MoOx/statinamic/blob/82b5ca6b50f0d0247e78befa9520829a8480f4c8/src/enhance-collection/index.js) to play with the collection.

**Comment by KyleAMathews** [comment]
The page index json could be written out to file as a custom module. The `createIndex` call could be rewritten by a babel plugin perhaps to be a require call to the custom module e.g. `createIndex() becomes `require('indices/a12')`. If this sounds crazy and you're curious I'll clarify :)

**Comment by andreypopp** [comment]
You might be interested in Query API for sitegen which does similar thing: https://sitegen.github.io/api

It doesn't implement chunked indices yet though so all metadata is always in the main chunk (which can be an overhead for super large sites > 1000 pages or something).

**Comment by KyleAMathews** [comment]
:+1: yeah, that's pretty much what I'm thinking for v1 of this. v2 where I'm writing out custom modules w/ metadata could be a later optimization.

**Comment by andreypopp** [comment]
Also note that passing a function for sorting is not a great API for that purpose, I think, cause that function should be evaluated during build at webpack context (so it can sort and then chunk results).

The API should be static enough, for example using query string:
```
let index = createIndex('./posts/*.md?sort-by=published_date&chunk-by=50')
```

**Comment by KyleAMathews** [comment]
Not 100% sure now this is needed. Closing for now but if someone has strong thoughts on this, we can reopen it in the future.

**Comment by MoOx** [comment]
For people which are interested, statinamic will handle that and more by adding a way to generate pages based on some metadata filters (eg: pages per categories, year, tags etc)

https://github.com/MoOx/statinamic/issues/15

**Comment by KyleAMathews** [comment]
@MoOx a utility module for pagination (filter then sort then paginate) would be a nice project that could be shared across projects. It'd definitely be nice for Gatsby sites. I closed this issue as it's not something that'll be handled natively in core. Instead components will declare themselves as multi-page components as described in https://github.com/gatsbyjs/gatsby/issues/33#issuecomment-189420854
