### ISSUE TITLE
Documentation: Windows Install Python Pre-Requisite

### ISSUE THREAD

**Issue by myappincome** [gatsbyjs/gatsby#470]
I've just finished installing on Windows.

Just wondering if it's worth adding a Pre-Requisite section somewhere to say Python is needed? I installed Python 2 and it installed ok, but I'm not sure if that's required on other environments.

**Comment by KyleAMathews** [comment]
This would be great in the FAQ on the README — could you add that?

**Comment by KyleAMathews** [comment]
We'll be building a website soon for this where we can add more detailed platform specific docs.

**Comment by myappincome** [comment]
Sure thing, I'll give it a go now.
