### ISSUE TITLE
[gatsby-transformer-javascript-frontmatter] Cannot query field allJavascriptFrontmatter

### ISSUE THREAD

**Issue by zedman** [gatsbyjs/gatsby#4703]
## Description

Running a query for allJavascriptFrontmatter results in an error, with no allJavascriptFrontmatter field being found. Am trying to access from within gatsby-node.js' onPostBuild function, but also tried within GraphiQL.

### Steps to reproduce

- Installed package
- Added plugin to gatsby-config.js with `plugins: [
    'gatsby-transformer-javascript-frontmatter',  ...`
- Added frontmater export from homepage's JS file
```
export const frontmatter = {
  title: "Homepage"
};
```
- Queried for allJavascriptFrontmatter on the root
```
{
  allJavascriptFrontmatter {
    edges {
      node {
        frontmatter {
          title
        }
      }
    }
  }
}
```

### Expected result

allJavascriptFrontmatter object should be returned with nodes attached.

### Actual result

Error returned `Cannot query field \"allJavascriptFrontmatter\" on type \"RootQueryType\".`

### Environment

* Gatsby version: 1.9.238
* gatsby-cli version: 1.1.46
* Node.js version: 6.10.1 (just updated to 9.9.0, issue still exists)
* Operating System: MacOS 10

**Comment by pieh** [comment]
do you have `gatsby-source-filesystem` pointing to dir with your js file?

**Comment by zedman** [comment]
Brilliant, thank you. Got it working.

I had gatsby-source-filesystem pointing at my markdown sub-directory, but not where my JS pages lived. When going through the blog/markdown tutorial it was made clear I needed to set up gatsby-source-filesystem, but didnt see any reference to it when setting up gatsby-transformer-javascript-frontmatter. 

For anyone else's reference I just had to duplicate the declaration in my gatsby-config.js file:

```
{
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/pages/posts`,
        name: "markdown-pages",
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/pages`,
        name: "javascript-pages",
      },
    },
```

**Comment by pieh** [comment]
Glad that you got things working. Would you like to make PR and update "How to use" section in https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-javascript-frontmatter so it would be clear You need that?

**Comment by zedman** [comment]
I was thinking about doing that, but I actually don't see it on https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-remark either, though its in the Gatsby Doc 'Adding Markdown Pages'. 

So should it be mentioned in the READMEs for both of those plugins?

**Comment by pieh** [comment]
Hmmm, you are right. After You pointed it out not sure what's the best way to handle that.

@shannonbux How do you think we could handle this in docs? Gist of the issue is that all transformer plugins need to have accompanying source plugin (most often `gatsby-source-filesystem`). Perhaps we could automatically add some kind of information block to transformer plugins about it?

**Comment by KyleAMathews** [comment]
We do discuss this in the tutorial — but yeah, not everyone reads that... an information block is a cool idea — we could auto-link to docs pages & tutorials depending on the plugin we're on.

**Comment by shannonbux** [comment]
Yes, @pieh and @KyleAMathews is an information block something like [this](https://vimawesome.com/plugin/fugitive-vim)? So there could be standard info at the top that pulls data from different places, and then the READme file below.

**Comment by pieh** [comment]
We do cover this in tutorials but it might be unreasonable to assume that everyone will read whole tutorial (and remember every concept presented there). 

By information block (this is term I just made up!) I just meant some UI element that is visually different from rest of READme (so it doesn't get lost in wall of text) that would have maybe 1 or 2 lines of text and potentially link to page with more detailed information (if it exists).

**Comment by pieh** [comment]
And don't focus to much on my initial idea - there are other ways to do this (f.e. manually editing "How to use" sections - maybe generic information about transformer and source plugins wouldn't really be that useful and people wouldn't really get the meaning of that without concrete examples specific for given transformer plugin) .

**Comment by KyleAMathews** [comment]
@shannonbux here's a quick sketch of what I was thinking
![2018-03-27 11 05 25](https://user-images.githubusercontent.com/71047/37985929-f8642e64-31ae-11e8-86da-f76fb6d29324.jpg)

**Comment by shannonbux** [comment]
Yeah, we initially wanted to do something like this! I will create an issue.
