### ISSUE TITLE
Can you import a normal react library? Or does it need to be a plugin?

### ISSUE THREAD

**Issue by daydream05** [gatsbyjs/gatsby#4704]
I'm still confused on how Gatsby and plugins work. Why does Gatsby need to have its own version of a library? (i.e. styled-components).

**Comment by KyleAMathews** [comment]
It's too handle SSR which, depending on the library, can require special Babel or webpack settings. Also with css-in-js libraries the plugins extract and inline in the head the critical css https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-styled-components/src/gatsby-ssr.js
