### ISSUE TITLE
wrong GraphQLSchema

### ISSUE THREAD

**Issue by nihgwu** [gatsbyjs/gatsby#4707]
## Description

I created a plugin [gatsby-transformer-code](https://github.com/nihgwu/gatsby-transformer-code), if I add `relativePath: node.relativePath` to the `codeNode` https://github.com/nihgwu/gatsby-transformer-code/blob/master/gatsby-node.js#L27, the generated `GraphQLType` for `relativePath` should be `GraphQLString` but got `File`, that's quite strange, I'm not familiar with GraphQL, I try to concat the `relativePath` field by my self but still the same, unless I make the value different from `node.relativePath`

I test it on both V2 and V1, and both have the same problem

### Steps to reproduce

Clear steps describing how to reproduce the issue.

### Expected result

if I add `relativePath` to the node, I should be able to query like this:
```graphql
{
  allRawCode {
    edges {
      node {
        name
        content
        extension
        instanceName
        relativePath
      }
    }
  }
}
```

### Actual result

but now I have to query like this:
```graphql
{
  allRawCode {
    edges {
      node {
        name
        content
        extension
        instanceName
        relativePath {
          id
          relativePath
        }
      }
    }
  }
}
```

### Environment

* Gatsby version (`npm list gatsby`): 2.0.0-alpha.12(v2) 1.9.181(v1)
* gatsby-cli version (`gatsby --version`): 1.1.47
* Node.js version: v8.9.0
* Operating System: MacOS

### File contents (if changed):

`gatsby-config.js`: 
```javascript
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'examples',
        path: `${__dirname}/src/examples`,
      },
    },
    {
      resolve: 'gatsby-transformer-code',
      options: {
        name: 'examples',
      },
    },
```
`package.json`: 
`gatsby-node.js`: 
`gatsby-browser.js`: 
`gatsby-ssr.js`:

**Comment by pieh** [comment]
gatsby automatically converts string fields with relative paths to files to `File` nodes

You shouldn't really copy fields from parent node to your node - if you need to access those fields do it in graphql using `parent` field which gives you access to `File` node from `RawCode` node

**Comment by nihgwu** [comment]
`parent` only contains `id`

**Comment by pieh** [comment]
try this:
```graphql
{
  allRawCode {
    edges {
      node {
        parent {
          ... on File {
            relativePath
          }
        }
        name
        content
        extension
        instanceName
      }
    }
  }
}
```

**Comment by nihgwu** [comment]
@pieh Thanks, the convert thing bothered me a lot
