### ISSUE TITLE
Proposal: Add plug-n-play support for arbitrary GraphQL sources

### ISSUE THREAD

**Issue by coco98** [gatsbyjs/gatsby#4708]
## Use-case

I already have a graphql API that can export a graphql schema. I want to use that as a gatsby source so that I can specify graphql queries (in the graphql type system that I have in my graphql schema) for each component and have that fetched during gatsby build.

## Things to figure out

- Support schema-stitching for gatsby graphql queries
- Add support for "sync" or "changes" so that gatsby can avoid rebuilding components for which the graphql queries will not return an updated dataset

@KyleAMathews This is with ref. to our conversation on twitter.

**Comment by jaisontj** [comment]
Hi @KyleAMathews. Is there any update on this? Is anyone working on this for v2?

**Comment by KyleAMathews** [comment]
@jaisontj still gathering requirements/user stories/speccing out design. Could you describe how you'd like to use this feature?

**Comment by gusnips** [comment]
Any updates? I'm trying to use with craftCMS/craftQL/graphQL as mentioned here https://github.com/markhuot/craftql/issues/41

**Comment by rjgux** [comment]
We are also in the same position, trying to use Gatsby with CraftCMS + CraftQL!

**Comment by m-allanson** [comment]
No news on this yet, but it is a popular feature request and is something we want to work on soon.

**Comment by gusnips** [comment]
I managed to build a plug-in to fetch data from craftCMS, will add to GitHub soon. How do I add to gatsby plugins page?
Thanks

**Comment by gusnips** [comment]
thanks @KyleAMathews , I meant to add to gatsby plugins page... It's fully working already

**Comment by gusnips** [comment]
Thanks, @KyleAMathews ... will do it as soon as I have some free time

**Comment by Dean177** [comment]
@gusnips do you plan on open sourcing your plugin? Its exactly what I am looking for and I would love to be able to use it / contribute.

**Comment by gusnips** [comment]
@Dean177 I just need to test it better, as I was using it in plugins/folder until now
https://github.com/gusnips/gatsby-source-craftcms
feel free to open an issue if you a problem

**Comment by Dean177** [comment]
@gusnips thanks, will do.

**Comment by KyleAMathews** [comment]
And it's out!
