### ISSUE TITLE
v2: GraphQL peers and type packages.

### ISSUE THREAD

**Issue by jquense** [gatsbyjs/gatsby#4711]
I think we need to come up with a better strategy for the duplicate `graphql` issues. The main one is well known, regardless of version mismatch graphql will not run if there are multiple copies, which is dumb. The concern on the horizon (especially with theming) is that any custom types, inadvertently have this problem as well. case in point, both `gatsby-transformer-remark` and `gatsby-transformer-react-docgen` use `graphql-type-json`, but if the package isn't deduped that will break, with gql complaining of an existing type named 'JSON' already.

The only sort of approach i can think that might help here is to do what we do with webpack and provide the `graphql` object to plugins as well as a set of custom scalars like JSON. That may not super scalable tho :/

**Comment by KyleAMathews** [comment]
I think this makes sense — it should be scalablish — people wanting new ones can just PR in the new field type — same as React did for years with DOM property support.

**Comment by pieh** [comment]
What is the best way to pass `graphql` module?

We do pass `graphql` as a function to run queries in `createPages`/`createPagesStatefully` node hooks, so either pass graphql module under different field or export it from gatsby package?

**Comment by m-allanson** [comment]
Done in #5415
