### ISSUE TITLE
Dynamically-Rendered Navigation Tutorial

### ISSUE THREAD

**Issue by giraffesyo** [gatsbyjs/gatsby#4721]
I see there's a stub for [Dynamically-Rendered Navigation](https://www.gatsbyjs.org/docs/creating-dynamically-rendered-navigation/).

By this do you mean a nav component that keeps track of what state it is in based on the current page or state of another component? If so, I think I could work on this tutorial.

**Comment by KyleAMathews** [comment]
I think the idea there was for navigation built automatically from the site's pages data e.g. you have a number of team member pages and whenever someone new joins, the menu is updated automatically.

**Comment by imshuffling** [comment]
Any examples of this working somewhere? thanks

**Comment by cdvillard** [comment]
@imshuffling, I don't know of anyone who has built this yet, but it's something commonly available in other static site generators. Wintersmith and Jekyll are two such generators that generate navigation using template engines like nunjucks and handlebars.

**Comment by imshuffling** [comment]
@cdvillard manage to achieve what I wanted in the end.

E.g I have 3 content types (yes poorly named Template 1, 2, 3...)

Rough menu structure as below.

-- Template 1
-- Template 1
-- Template 1
   ---- Template 2
   ---- Template 2
-- Template 1
   ---- Template 3
   ---- Template 3
   ---- Template 3

I then have a content type called "Navigation" which is a multi reference field allowing you to add Template 1 pages, this will create our top level nav.

![screen shot 2018-08-08 at 11 47 45](https://user-images.githubusercontent.com/739061/43832960-002b982e-9b01-11e8-9be4-3e22b8802614.png)

To get the nested pages I simply have a reference field called "ChildPages" on each Template 1 page

![screen shot 2018-08-08 at 11 49 53](https://user-images.githubusercontent.com/739061/43833027-3cb15ad6-9b01-11e8-9f5c-c1529c3b4675.png)

And now the graphQL query which i have in my layout.js file

```
       query LayoutQuery {
         contentfulNavigation {
           navigationItem {
             menuTitle
             title
             slug
             childPages {
               ... on ContentfulTemplate2 {
                 menuTitle
                 title
                 slug
                 id
               }
               ... on ContentfulTemplate3 {
                 menuTitle
                 title
                 slug
                 id
               }
             }
           }
         }
       }
```

Hope this helps someone.

FYI I'm using Gatsby V2.

**Comment by CharlieDieter** [comment]
It would be pretty easy to do this with `gatsby-source-filesystem`.  I added this to gatsby-config.js: 
``` {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/pages`,
        name: 'pages',
      },
    },
``` 

Then in my layout component I create a StaticQuery:
```
...
<StaticQuery
        query={graphql`
          query {
            allSitePage {
              edges {
                node {
                  path
                }
              }
            }
          }
        `}
        render={data => {
...
```
Then filter out the paths you don't want (like 404 and test). That's the best way I can figure out for now.
