### ISSUE TITLE
[gatsby-source-contentful] Validating entries in 'draft' when using the Preview API

### ISSUE THREAD

**Issue by danniehakan** [gatsbyjs/gatsby#4726]
## Description

I'm building a site powered by Gatsby and the official Contentful plugin. I have two versions of this website, one that pulls in published + draft content via the Contentful Preview API, and one that pulls in only published content via the Content Delivery API. 

As I understand it as per the official documentation from Contentful, validations only happen upon publishing content, meaning newly created content that is put in draft is not validated. This effectively means that when I fetch data using the Preview API I get records where fields marked as *required*, for instance a *slug* field, is not there. This breaks my website in all sorts of places depending on what fields have not yet been filled in.

I'm wondering if there's any way to perform this validation for content in draft as well. It's kind of annoying because I can clearly see that the errors are raised in the Contentful Web App, but I've no idea how to detect them in Gatsby.

Any ideas?

**Comment by KyleAMathews** [comment]
This sounds like an issue for Contentful.

As far as your Gatsby site — perhaps just check that fields exist before rendering? E.g. at the top of your render function and return early if there's missing data.
