### ISSUE TITLE
v2: dealing with babels new aggressive version errors.

### ISSUE THREAD

**Issue by jquense** [gatsbyjs/gatsby#4730]
One thing I'm noticing using babel7 with gatsby is that plugins have started to really care about the version of babel-core. Since gatsby is consuming babel/core directly that makes the upgrading it from the user's perspective impossible (they can rely on the dedupe behavior but eeeh). I'm sure if this is just because of the beta's have strict ranges, but if every update of a plugin is going to bump the peer dep range to the current, users will have this error often.

In which case we should move babel/core to a peer dep ourselves, which isn't great from a UX perspective

**Comment by jlengstorf** [comment]
Peer deps seem like a good move if the entire ecosystem will be sharing that dep. From a standard workflow perspective, this shouldn't change much; `gatsby new` can install peer deps in the background, so the UX only suffers for people building from scratch.

@m-allanson @pieh does this seem reasonable?

**Comment by m-allanson** [comment]
I think we should avoid making people install `@babel/core` themselves, if possible.

If I've got this right, it looks like this won't be an issue once babel 7.0.0 is published. The peerDep ranges have been loosened up for the v7 RC releases: https://github.com/babel/babel/pull/8445/files

**Comment by KyleAMathews** [comment]
Yeah, it looks like we're good with that @m-allanson. I honestly haven't seen any peerDependencies warnings so this doesn't feel like much of an issue.

**Comment by KyleAMathews** [comment]
We can revisit if problems come up again.
