### ISSUE TITLE
Add a --debug flag for production builds which disables uglify

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#4732]
It's really hard to debug some problems (e.g. mismatches between SSR & client renders https://github.com/gatsbyjs/gatsby/issues/3067) without this.

**Comment by m-allanson** [comment]
Could this initially be done as a plugin if someone wanted to work on it?

**Comment by KyleAMathews** [comment]
Yeah — but this seems like something that should be built in — not something people have to install and add/remove to their gatsby-config.

Let's perhaps not name it `--debug` though as that'll confuse people as the scope of the feature is small and `debug` seems expansive. Maybe be really specific e.g. `--no-uglify`.

It'd be a really easy PR to add.

**Comment by tsriram** [comment]
I'll give this a go.

**Comment by dandv** [comment]
If `--no-uglify` was necessary, am I to understand that `gatsby build` *does* uglify by default (or should uglify)?

I see code in clear, including comments, as a result of `gatsby build`, and you can see that in some big brand public sites:

![image](https://user-images.githubusercontent.com/33569/81273783-85f95380-90a3-11ea-9b4c-b4ea0c42c123.png)

![image](https://user-images.githubusercontent.com/33569/81273911-b04b1100-90a3-11ea-8ce2-8eaaf49fd701.png)

I thought, maybe those sites are engineering-oriented and leave their code open for inspection, but then I looked at https://www.shopflamingo.com. Same story. https://impossiblefoods.com/ Same.

Does Gatsby actually no longer uglify when `build`ing?

**Comment by LekoArts** [comment]
Please don't open up year old issues, it's not really helping your cause. Thanks!

About your comment: You can see those things due to "Sourcemaps" that get shipped with the build (you can disable this behavior manually if you want).
