### ISSUE TITLE
Gatsby meetups

### ISSUE THREAD

**Issue by patreeceeo** [gatsbyjs/gatsby#4738]
Do you want to grow as a developer, open source contributor, consultant etc with Gatsby and related technologies? Personally, I find it helpful to have places to go offline, to have conversations not mediated by a screen. I feel like I learn 10x more than I could have versus remote mediums like Github, Discord etc when I can sit down with someone, laptop alongside laptop.

However, a problem with a lot of tech meetups is the more proficient people tend to stay home, perhaps because they don't see the personal benefit in helping the less proficient. To that I'd say whenever I teach someone less proficient than myself I notice flaws in my own understanding, or discover valuable new variations on something I already knew. Teaching helps me go from mere competence to mastery. See that Bruce Lee quote about the one kick practiced a thousand times. 

So, would anyone be interested in forming or joining a local in-person group that meets regularly to

A. show off what you're working on, give talks/presentations
B. get/give help
C. whatever else people do in meetups

I could organize a chapter in San Francisco since that's where I'm located.

**Comment by lightstrike** [comment]
@pzatrick This is a great idea, I've been thinking about how great this could be for Gatsby too. I've actively organized a meetup in the past and it is an excellent way to build a community. I found regularity is the biggest key to success, both in terms of frequency and day/time of week. I'm not based in SF right now but would be happy to give any guidance if that would be helpful!

**Comment by Jaikant** [comment]
Anyone here in Bengaluru, who would like to help organize something similar here?

**Comment by KyleAMathews** [comment]
@pzatrick I'd love to help organize a meetup in SF! I'm in Berkeley so would love to have a regular meetup with Gatsby folks in the bay area. We should do one soon to chat about the v2 release :-) Do you know of a space?

For people wanting to organize elsewhere — we have a lot of money in open collective so we could use that money to pay for meetup.com fees.

**Comment by pzatrick** [comment]
Making inquiries about event spaces! @KyleAMathews, would a not-too-raucous cafe or bar work, worst case scenario?

**Comment by KyleAMathews** [comment]
For the after party :-) it doesn't do too well for the actual meetup

**Comment by ajayns** [comment]
@Jaikant Hey! Would love to help out and participate in one.

**Comment by itsPR** [comment]
@ajayns & @Jaikant We are planning Gatsby + GraphQl Session in Bangalore on Sept 22. Looking forward to seeing you there.  Ping me for the invite. [[prashanth@developerweekend.org](url)]

 !#ForTheLoveOfGatsby .

**Comment by nodox** [comment]
Would love to create a meetup in NYC!

**Comment by jesstelford** [comment]
I'm the organiser of [React Sydney](https://yarnpkg.com/en/docs/selective-version-resolutions) (🇦🇺 Australia), and would love to have more Gatsby users there to participate and to get to know others in the community.

Reach out and say hi if you're in the area and want to give a talk or attend :)
