### ISSUE TITLE
Proxy Setting | gatsby-source-contentful 

### ISSUE THREAD

**Issue by spatrame** [gatsbyjs/gatsby#4744]
Contentful latest version provide proxy settings as below, but gatsby-source-contentful doesn't give option to provide the proxy. 
I am using "gatsby-source-contentful": "1.3.44"

https://www.npmjs.com/package/contentful 
var contentful = require(`contentful`);
var client = contentful.createClient({
    space: `XXX`,
    accessToken:`XXX`  ,
    host: `XXX`,
    proxy: {
        host: 'XXX',
        port: 8085,
    }
});

I am expecting some configuration like below
gatsby-config.js
 {
      resolve: `gatsby-source-contentful`,
      options: {
        spaceId: `xxx`,
        accessToken: `xxxx`,
        proxy: {
          host: 'XXX',
          port: 8085,
        }
      }

**Comment by Khaledgarbaya** [comment]
hi @spatrame,

That's not supported in the plugin but it is really easy to add
you need to pass the proxy [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/src/gatsby-node.js#L62) from the plugin option and [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/src/fetch.js#L11) when creating the client.
It would be nice if you have some time to add this feature

Best,
Khaled

**Comment by jreidgreer** [comment]
@spatrame @Khaledgarbaya hopefully #5950 addresses this issue, as I ran into it as well. Let me know if you see room for improvement.

**Comment by Khaledgarbaya** [comment]
This should be fixed in https://github.com/gatsbyjs/gatsby/pull/5950
