### ISSUE TITLE
Broken css after build 

### ISSUE THREAD

**Issue by ponchique** [gatsbyjs/gatsby#4754]
Hi there!

Can't find a css for static pages, after `gatsby build`.
This behavior I see only if I reload all existing pages in a browser, but if I'm roaming through site links - 
css is working.
Also, css works in the dev mode

There are no errors in console, no errors while building, just as the result - broken css and from time to time they looks different.

### Environment
* gatsby-cli version:`1.9.243`
* Node.js version: `8.9.4`
* Operating System: MacOS `10.13.2`

### File contents :

`gatsby-config.js`:
    
    + `gatsby-plugin-jss`,

Would be thankful if you can help me!

**Comment by ajayns** [comment]
@KyleAMathews Don't you think it would be a good idea mentioning this somewhere in the documentation? Because devs usually just check how good everything works using `gatsby develop` and then `gatsby build` seems to break everything just like that.

**Comment by KyleAMathews** [comment]
If you use the default html.js (which we strongly encourage you to) then this happens by default.

**Comment by ponchique** [comment]
Yes, I resolve it by rewriting all css using sass. I thought the problem was in jss.
