### ISSUE TITLE
[gatsby-source-contentful] Letf-padding `c` to ids

### ISSUE THREAD

**Issue by Khaledgarbaya** [gatsbyjs/gatsby#4762]
## Background
Every entry id that starts with a number an extra `c` character will be added to the beginning 

@KyleAMathews was there any reasons this [code](https://github.com/gatsbyjs/gatsby/blob/41bf10f2a244bf8981bb276cee2aff21c8345ffe/packages/gatsby-source-contentful/src/normalize.js#L30-L39) was added.
Since the `id` there is the value I don't think we need to change it. Or am I missing something

**Comment by proko** [comment]
Just happened to see [the answer](https://github.com/gatsbyjs/gatsby/issues/4001) on this yesterday

**Comment by KyleAMathews** [comment]
Ooops, sorry for not seeing this @Khaledgarbaya! But yeah, graphql doesn't allow for ids that start with a number 🤷‍♂️ https://github.com/gatsbyjs/gatsby/issues/4001#issuecomment-365356347

**Comment by Khaledgarbaya** [comment]
@KyleAMathews but I thought that's only valid for the keys and the ids here are values?

**Comment by KyleAMathews** [comment]
IDs are special for whatever reason. Probably because it's an internal Facebook restriction that leaked out into open source.

**Comment by Khaledgarbaya** [comment]
😱 OMG TIL
