### ISSUE TITLE
Using gatsby-plugin-react-next + styled-components will break style in production

### ISSUE THREAD

**Issue by rockmandash** [gatsbyjs/gatsby#4774]
Thanks for the wonderful tool.
I've noticed that using gatsby-plugin-react-next + styled-components will break style in production.
This happens with or without using Fragment I think.
The build stylesheet class name shifted, causing a weird result.

**Comment by m-allanson** [comment]
The styled components plugin was recently updated to support using the babel plugin `babel-plugin-styled-components` for server side rendering (see https://github.com/gatsbyjs/gatsby/pull/4722), does using that fix your issue? 

Also see the discussion at https://github.com/gatsbyjs/gatsby/issues/3067

**Comment by rockmandash** [comment]
@m-allanson Nope, I tried today.
The problem still the same.

**Comment by rockmandash** [comment]
I think the babel plugin is adding the name to hash style name.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
