### ISSUE TITLE
Cross post to Medium!

### ISSUE THREAD

**Issue by f0rr0** [gatsbyjs/gatsby#478]
I wrote a [script](https://github.com/f0rr0/f0rr0.github.io/blob/dev/src/scripts/medium.js) to automate cross posting to medium from my blog. I don't know how relevant this is, but someone may find it useful. Maybe we can add a ref in the `README`. If enough people find it useful, I can build this into gatsby itself. It makes it really simple and pretty:

![medium](https://cloud.githubusercontent.com/assets/8574219/18883218/f9853a7a-84ff-11e6-9db1-202734155689.gif)

**Comment by KyleAMathews** [comment]
This would be make for an awesome Gatsby plugin! The next or next next alpha will have plugin support and it'd be great if you could figure out how to make this work there (adding any necessary APIs).

**Comment by f0rr0** [comment]
@KyleAMathews It should be fairly simple to implement this as a gatsby run command like `gatsby medium` or something. To maintain consistency between the original content as rendered on the gatsby site and that sent to medium, users should be forced to keep the core markdown parsing logic in a separate file which can be required by different plugins etc. Right now that logic is within a webpack loader. This is a design decision of course so I'll leave that to you.

**Comment by KyleAMathews** [comment]
With 1.0 and the GraphQL data layer, Markdown rendering won't happen in Webpack any longer but instead through "source" plugins (probable name). Plugins like this would be able to query a standardized Markdown schema. So a plugin could require the standard `gatsby-plugin-markdown-source` (or whatever they end up being named) be installed and from that know they can query for rendered HTML. The markdown rendering pipeline will be setup so users can modify that but without changing the exposed graphql schema.

Plugins will also be able to add new commands to `gatsby`.

**Comment by vinnymac** [comment]
What if instead of making this a separate command like `gatsby medium` it was a `postBuild` task? It could even do a diff of your articles and then determine which were new/changed and needed to be updated on medium. Thoughts?

**Comment by f0rr0** [comment]
@vinnymac in most use cases, you wouldn't want to build the site to post to medium. You can spawn a child process and run the task from `postBuild` however. Also, I don't think Medium supports editing articles via the API. Will have to double check.

**Comment by vinnymac** [comment]
@f0rr0 yea in that case it sounds better as part of a starter packs deploy task, it is probably better off just a separate task like you originally proposed. Then someone can just add it where they need it. Thanks for explaining!

**Comment by jbolda** [comment]
@f0rr0, we are a couple alphas further ahead from before, and plugin support is there. Still interested in building a plugin for support?

**Comment by KevM** [comment]
I just wanted to say I would be interested in a something like this. I'd love to have a single workflow to publish content created using Gatsby to one or more platforms.
