### ISSUE TITLE
accept argument on many relation

### ISSUE THREAD

**Issue by abumalick** [gatsbyjs/gatsby#4783]
Hello,

I am trying to integrate a rest api made with feathers into gatsby. Right now I could import my data and it very good. The website will be multilingual, so I made some relations like this in the database:
![image](https://user-images.githubusercontent.com/8377185/38161052-4a06d3fe-34c8-11e8-8974-71ad3ba311eb.png)
Every chapter have one or more chapterString, so in the chapter table I have fields that are common to all languages, and in chapterString, I have the translations for my chapter.

I imported my data into gatsby and now I am able to query like this:
```
allFeathersChapters {
    edges {
      node{
        slug
        chaptersStrings {
          locale
          title
        }
      }
    }
  }
```
And everything is working well, I get an array of chapterStrings. Here is one chapter for example:
```
{
          "node": {
            "slug": "chapter1",
            "chaptersStrings": [
              {
                "locale": "en",
                "title": "my english title"
              },
              {
                "locale": "fr",
                "title": "my french title"
              }
            ]
          }
        },
```

Now, I want to get chapterStrings only for one language so I can include it on my page. I can do this for example:
```
allFeathersChaptersStrings (filter: {locale: {eq: "fr"}}) {
    edges {
      node {
        locale
      }
    }
  }
```

This works well, but I need to get the strings associated with a chapter, so I would like something like this:
```
allFeathersChapters {
    edges {
      node {
        slug
        chaptersStrings (filter: {locale: {eq: "fr"}}) {
          locale
          title
        }
      }
    }
  }
```
With this, I would get only the translations that I need for the french chapter page.

I get an error here through:
```
{
  "errors": [
    {
      "message": "Unknown argument \"filter\" on field \"chaptersStrings\" of type \"FeathersChapters\".",
      "locations": [
        {
          "line": 6,
          "column": 26
        }
      ]
    }
  ]
}
```

So my question is : 
- Is it possible to do this with gatsby now ?
- If it is not possible, and you would accept a PR: would it be hard to implement it ? Can you give me some indications on how to do ?

I am very interested by this, as I don't see a better way to handle multi-language. I tried to create a node for each language but I want to avoid that as I would have to make a lot of changes on the backend side.

Thank you for your great framework !

**Comment by pieh** [comment]
Currently you cant filter arrays/lists inside nodes via graphql, but it surely would be welcomed addition.

If you want start hacking on this here's starting point for this - https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/infer-graphql-type.js#L58-L96 (this will require some graphql knowledge):
- you want need to add `filter` to `listType.args`:
  this would require to generate input schema for `filter` arg (same as we need to generate input schema for filter we use in root fields so you probably could reuse that (`inferInputObjectStructureFromNodes`)
- either add (if field doesn't have custom resolver) or modify/wrap existing resolver (in case it has resolver) to handle filtering - for nodes filtering we use `sift` (which we call in `run-sift.js`)

**Comment by abumalick** [comment]
Thank you very much for your indications. Right now I am busy so I cannot take care of that but I will try to hack it when I have some time.

If someone wants to fix it, he can take it through.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
