### ISSUE TITLE
Conditional component in layout

### ISSUE THREAD

**Issue by b0gd4n** [gatsbyjs/gatsby#4792]
I have my Header component part of the `layouts/index.js`. However, I want the header to be rendered on every page except for the main homepage.
I figured I could include the header in every page that I want it part of and remove it from the layout, but would rather keep it there.

**Comment by ryanditjia** [comment]
Layout has a prop called `location`. The gist is you can access `location.pathname` and conditionally show Header if `location.pathname !== '/'`.

**Comment by b0gd4n** [comment]
@ryanditjia thank you - that makes sense.
