### ISSUE TITLE
`$nin` operator from `sift` not supported?

### ISSUE THREAD

**Issue by jazen** [gatsbyjs/gatsby#4793]
## Description

I'm trying to use `$nin` operator from `sift` in a query.

### Steps to reproduce

A `.md` post with frontmatter:

```
---
path: "/test"
date: "2018-03-21T10:14:00.000+02:00"
title: "test"
tags:
  - noindex
---

Test.
```

Running

```
query IndexQuery {
  allMarkdownRemark(
    filter: {
      frontmatter: {
        tags: {nin: ["noindex"]}
      }
    }, 
    edges {
      node {
        frontmatter {
          title
          tags
        }
      }
    }
  }
}
```

### Expected result

I would expect the query to exclude nodes where `frontmatter.tags` is an array including a `noindex` string. 

### Actual result

```
{
  "errors": [
    {
      "message": "Argument \"filter\" has invalid value {frontmatter: {tags: {nin: [\"noindex\"]}}}.\nIn field \"frontmatter\": In field \"tags\": In field \"nin\": Unknown field.",
      "locations": [
        {
          "line": 3,
          "column": 13
        }
      ]
    }
  ]
}
```

### Environment

* Gatsby version (`npm list gatsby`): `1.9.243`
* gatsby-cli version (`gatsby --version`): `1.1.49`
* Node.js version: `v9.10.1`
* Operating System: `OSX High Sierra`

**Comment by vai0** [comment]
I'm experiencing the same with the other filters ($regex, $in, $nin). The only two that are working for me are $eq and $ne

**Comment by KyleAMathews** [comment]
@vai0 `$in` is only available for filtering arrays.

`$nin` hasn't been implemented yet. Not all sift functions have supported added yet. A PR doing this would be great! This is where the code is — https://github.com/gatsbyjs/gatsby/blob/94da32474c4bd1dd18311c2e87a7a8f6d17ae61b/packages/gatsby/src/schema/infer-graphql-input-fields.js#L30

You'd need to add the additional functions the schema + add tests + implement them in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/run-sift.js
