### ISSUE TITLE
Filtering on Contains in Array - JSON content

### ISSUE THREAD

**Issue by thekevinbrown** [gatsbyjs/gatsby#4799]
## Description

I have tags arrays in my content, and I want to be able to fetch by those tags.

### Steps to reproduce

Use JSON content like this:

```
{
  tags: ['a', 'b']
}
```

Then try to fetch for content which contains tag 'a' with this query:

```
query testQuery($tag: String) {
	allContentJson(filter: { tags: { in: [$tag]}}) {
		totalCount
	}
}
```

### Expected result

I would expect this to work as per this example and this issue:

Example: https://github.com/gatsbyjs/gatsby/blob/52e36b9994a86fc473cd2f966ab6b6f87ee8eedb/examples/using-remark/src/templates/template-tag-page.js#L39
Issue: https://github.com/gatsbyjs/gatsby/issues/1645

### Actual result

```
{
  "errors": [
    {
      "message": "Variable \"$tag\" of type \"String\" used in position expecting type \"contentJsonConnectionTopicsInputObject_2\".",
      "locations": [
        {
          "line": 1,
          "column": 56
        },
        {
          "line": 2,
          "column": 67
        }
      ]
    }
  ]
}
```

The only way I've found to get the query to run is this:

```
query testQuery($tag: String) {
	allContentJson(filter: { tags: { in: {tag: { eq: $tag}}}}) {
		totalCount
	}
}
```

But I always end up with `null` as the result.

### Environment

* Gatsby version (`npm list gatsby`): `gatsby@1.9.243`
* gatsby-cli version (`gatsby --version`): Not installed (I use `package.json` commands)
* Node.js version: v8.9.4
* Operating System: OS X 10.13.3

### File contents (if changed):

(I'll provide an example project which reproduces this if needed.)

**Comment by MarcCoet** [comment]
+1
I also tried using the brackets AND the eq operator like so:
```
query testQuery($tag: String) {
	allContentJson(filter: { tags: { in: [{tag: { eq: $tag}}]}}) {
		totalCount
	}
}
```

because when exploring QraphiQL it looks like that is what is needed but it always returns null.
I was starting to wonder if there was a problem with my source plugin but maybe not then...

Gatsby version: 1.9.233

**Comment by btk** [comment]
Just stumbled upon this.

For my case, this was the syntax that I expected to work, similar to @MarcCoet 

```
      filter: { language: { eq: $language }, category: { in: [{slug: {eq: $slug} }] } } }
```

But seems like this structure is not supported. Will have to pull out data without filtering and filter it in javascript.

**Comment by SarathSantoshDamaraju** [comment]
Facing same problem, 
In my case i want to generate pages based on tags that will list the tagged items in each of the pages. But as the query is returning null, i am unable to generate pages as well

**Comment by pieh** [comment]
There is a bug in how schema is constructed for array of objects - inside `in` operator Gatsby shouldn't add more operators in "leafs"

So in example from this issue:
```gql
filter: { language: { eq: $language }, category: { in: [{slug: {eq: $slug} }] } } }
```
schema shouldn't add that `eq` there - it should be:
```gql
filter: { language: { eq: $language }, category: { in: [{slug: $slug }] } } }
```

If anyone is interested in fixing this - https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/infer-graphql-input-fields.js and https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/infer-graphql-input-fields-from-fields.js is where schema is constructed for inputs

**Comment by Mathspy** [comment]
Is this bug affecting v2? I'd look into it if it's affecting both versions

**Comment by pieh** [comment]
This is affecting both v1 and v2 (there were no schema related changes in v2)

**Comment by ErisDS** [comment]
I also ran into this bug, but I found this PR: https://github.com/gatsbyjs/gatsby/pull/6315 which appears to fix it in gatsby@2.0.0-beta.22.

I'm now able to do queries like:

`filter: {category: { elemMatch: {slug: {eq: $slug } } } } }`

**Comment by ErisDS** [comment]
Argh I definitely had this working, now elemMatch is an unknown field. Did something change?

**Comment by pieh** [comment]
This was fixed in gatsby v2 by, so I'm closing this issue
