### ISSUE TITLE
Support page URLs without trailing slash

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#481]
Jekyll has good documentation on how to setup this up with different hosts.

http://jekyllrb.com/docs/permalinks/#extensionless-permalinks

This shouldn't be the default as not all serving software/hosts support this.

**Comment by jeroenransijn** [comment]
Thanks for sharing. Would be nice if this is also documented within this repo. Or steps to production basically.

**Comment by teebolt** [comment]
So this isn't really a gatsby concern so much as a web server issue? Not having the trailing slash would be nice

**Comment by KyleAMathews** [comment]
@teebolt exactly. Gatsby defaults to using a slash since it's the most universal way of doing things. If you know what you're doing, you can go slashless.
