### ISSUE TITLE
[gatsby-plugin-netlify] Proxy issues when using Netlify functions

### ISSUE THREAD

**Issue by gosseti** [gatsbyjs/gatsby#4812]
I’m currently trying to get Netlify functions working in Gatsby. I have a proxy set up like this in `gatsby-config.js` so that the `/functions` endpoint forwards on requests to my Netlify function handler:

```
proxy: {
  prefix: '/functions',
  url: 'http://localhost:9000',
}
```

Everything works on the Netlify functions side as hitting the URL `http://localhost:9000/hello` gives me back:

```
{"msg":"Hello, Lawrence!"}
```

I’m then running a request like this:

```
axios.get('/functions/hello').then(data => {
  // requests to `http://localhost:8000/functions/hello`
})
```

If I visit `http://localhost:8000/functions/hello` I get the error:

```
Function invocation failed: Error: Cannot find module '/Users/Gosset/Dev/gosset/lambda/functions'
```

The expected behaviour is that I’d want:

`http://localhost:8000/functions/hello` to hit the URL: `http://localhost:9000/hello`

This is using:

```
"gatsby": "^1.9.244",
"netlify-lambda": "^0.3.0"
```

**Comment by KyleAMathews** [comment]
Sounds like you have the same issue as https://github.com/gatsbyjs/gatsby/pull/4797?

**Comment by gosseti** [comment]
Ah thanks, doesn’t seem like there’s any real concrete solutions in either place yet unfortunately. How would you approach this?

**Comment by m-allanson** [comment]
This should be handled by #4920.
