### ISSUE TITLE
Use SeedAndDew to allow users to contribute to the project by reading documentation

### ISSUE THREAD

**Issue by ageorgie** [gatsbyjs/gatsby#4814]
Hi everyone,

I'm Alex from SeedAndDew. We're building a common subscription platform that allows users to contribute to a number of projects at the same time with a single subscription. The idea here is that it's a lot easier to get people to contribute $10/month to every open source project they work with than it is to get them to contribute $5/month for a specific project. The subscription revenue will distributed based on the amount of time users spend reading documentation of the respective project which we anticipate will correspond well with actual use. So if a user spends 10% of their time reading the Gatsby documentation, you get 10% of the subscription revenue.

Just to be clear, this isn't a paywall. If a user isn't part of the service, they still see the documentation without any visual cues or any indication that they are missing anything. Our goal is merely to make it easy for people to contribute to freely available content like Gatsby.

I chatted briefly with @KyleAMathews via email and he mentioned I should create an issue to gauge the community's interest in this. We pretty early with this right now but if we get a few projects on board, the next steps will be registering a new account with us, entering your bank details through Stripe so we have a place to send the distributed revenue and adding a provided script tag to your documentation head.

Any thoughts or concerns about this?

**Comment by sebastienfi** [comment]
On that $10 what would be the platform costs ?

Other than that question to solve, I'm 100% in.

**Comment by ageorgie** [comment]
We take 30% or $3 out of the 10. That includes payment processing costs on both ends. In the interest of transparency, we might also introduce a minimum payout amount (probably $10 or so) eventually but we're waiving that for now to see the data and verify that it's a problem.

Sound good?

**Comment by ageorgie** [comment]
Hey everyone,

Just wanted to follow up on this. We think we have an MVP ready and are looking to start onboarding projects. Is this something you guys are still interested in? If so, would one of you guys mind registering the project on www.seedanddew.com/register? If you want the money to go to your OpenCollective account, you can select them in the 'Are you fiscally sponsored by another foundation' dropdown. Otherwise, you can leave it as 'no' and we will send you to Stripe to get your bank details.

After you register and your on your dashboard, we'll show you the integration instructions (with the script you need to include) and provide you a live test account you can use to validate the integration. We share that account with all our projects so you might see existing projects with the account. The important thing is that your project shows up in the drop distribution list.

Let me know if you have any questions, concerns or feedback and thanks for being a part of this.

**Comment by ageorgie** [comment]
Hey @sebastienfi do you have the bandwidth to help with the integration? Basically, we need a point person to do the registration for Gatsby and add the script to the documentation pages. I'm happy to help with the latter if needed.

**Comment by KyleAMathews** [comment]
Hey appreciate you dropping by but it doesn't seem like there's enough interest atm to make this on our todo list. Closing for now.
