### ISSUE TITLE
Wrong spelling in Readme.md of OutboundLink (is Outboundink) for gatsby-plugin-google-analytics/

### ISSUE THREAD

**Issue by johot** [gatsbyjs/gatsby#4815]
It says Outboundink instead of OutboundLink which actually breaks all gatsby builds if you did like me and made a copy / paste. Thanks!

**Comment by ryanditjia** [comment]
Made a PR: https://github.com/gatsbyjs/gatsby/pull/4819

**Comment by KyleAMathews** [comment]
Fixed in https://github.com/gatsbyjs/gatsby/pull/4819
