### ISSUE TITLE
How to add links in markdown to other markdown pages 

### ISSUE THREAD

**Issue by DonJayamanne** [gatsbyjs/gatsby#482]
OS: OS X Elcapitan 10.11.6
Nodejs: 6.6.0
Gatsby: 0.12.12

I'd like to add a link in a markdown file to another markdown file.
This works in development mode, however doesn't when trying to publish with the ```--prefix-links``` option.

Basically, links generated in the markdown files are not prefixed.
Is this supported or am I missing something?
Thanks.

**Comment by KyleAMathews** [comment]
In 0.x It might be possible if you use a custom loader like https://github.com/gatsbyjs/gatsby-starter-default/blob/master/loaders/markdown-loader/index.js

Related is https://github.com/gatsbyjs/gatsby/issues/475 — this wouldn't be an issue if we were using `basename` with React Router.

**Comment by DonJayamanne** [comment]
Perfect, that works along with the use of [markdown-it-replace-link](https://github.com/martinheidegger/markdown-it-replace-link)
Thanks
