### ISSUE TITLE
Naming conventions for plugins

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#4827]
## Description
Currently, the Plugin Authoring doc describes four categories in the Gatsby plugin/package naming convention. This covers most existing plugins. However, there is potential to add packages and plugins that must adhere to other naming conventions. 

## Problem
Here's an example scenario: if we add eslint to Gatsby and want to share it through the plugin library, we'll need to name it according to eslint.org's conventions: `eslint-plugin-<plugin-name>`. The plugin library would currently not pull this into search results, so we'd need to expand how the library finds packages and plugins.

## Additional Questions
* What kinds of things fit into the plugin library beyond what is currently outlined in the [Plugin Authoring](docs/plugin-authoring/) doc?

@kkemple

**Comment by shannonbux** [comment]
Sort of related to issue #4671 because as we expand what categories of plugins are included in the library, the naming conventions for plugins will likely need to change.

**Comment by KyleAMathews** [comment]
We actually filter which NPM packages show up in the library using NPM "keywords" not the names of the packages so a package named `eslint-preset-gatsby` would show up if it added the right keyword.

The two keywords we match on (currently) are `gatsby-plugin` and `gatsby-component`. I've thought about adding `gatsby-library` to this list in the past as that'd be a perfect fit for something like `eslint-preset-gatsby`.

We specify these keywords in two places:

* https://github.com/gatsbyjs/gatsby/blob/924e74273bd3b3fff4cac5d4cf0a403eadd4f417/www/src/components/searchbar-body.js#L201
* https://github.com/gatsbyjs/gatsby/blob/84e7b7ff2aba2b32ce0bf1b47badcfa417576a93/www/gatsby-config.js#L14

**Comment by shannonbux** [comment]
ok @KyleAMathews cool! Should I add those links to our Plugin Authoring doc?

**Comment by KyleAMathews** [comment]
Perhaps not the links to the code as that's likely to change and not interesting to most people but definitely which keywords people should use. Add the two to the keywords bullet [here](https://www.gatsbyjs.org/docs/plugin-authoring/#what-files-does-gatsby-look-for-in-a-plugin)

We should perhaps have a section near the top making it very clear how they get their plugin to show up in the plugin library.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
