### ISSUE TITLE
Contentful image sizes for images inside Markdown

### ISSUE THREAD

**Issue by squaredindex** [gatsbyjs/gatsby#4828]
I'm currently importing content from Contentful to my page like so:
```
      <div
        dangerouslySetInnerHTML={{
          __html: data.contentfulPageNoMansOrchard.aboutContent.childMarkdownRemark.html,
        }}
      />
```
I have an image within that markdown post and it renders out as a plain jpg (inside a <p> tag for some reason) at the moment. 

I'd like to generate responsive sizes and webp versions, but struggling to figure out how, doesn't seem like I can manipulate with sharp as I would in other cases, I'm assuming I can use `GatsbyContentfulSizes` but searching through all the docs and other issues, can't seem to fill that gap in my knowledge as to how I connect these things, but I am a massive noob to this still.

**Comment by KyleAMathews** [comment]
There's some discussion about adding this exact feature over at https://github.com/gatsbyjs/gatsby/issues/1502

Would love your help there!
