### ISSUE TITLE
[gatsby-plugin-sitemap] Excludes should use regex to exclude paths

### ISSUE THREAD

**Issue by mrkre** [gatsbyjs/gatsby#4833]
## Description

Sitemap plugin now takes an array of paths for exclusion when building the sitemap. However, there may be use cases where we want to exclude certain paths without specifying all the subpaths, e.g. all routes under `/parent`.

For now i am overriding serialize to filter out the pages. Happy to contribute to the code base if it's agreeable to use regex.

### Expected result

Passing in an array for sitemap config should turn the paths into a regexp instead of just doing an array check in [includes.js](https://github.com/gatsbyjs/gatsby/blob/f639fab66bfcc297c0d27c5f55e1d14c8595059a/packages/gatsby-plugin-sitemap/src/internals.js#L17)

**Comment by pieh** [comment]
As mentioned by @lightstrike, this issue is resolved by #4770. Feature in slightly other form than requested (glob instead of regex) is available in gatsby-plugin-sitemap@1.2.21 .
