### ISSUE TITLE
[Gatsbygram] 404 link back to site breaks

### ISSUE THREAD

**Issue by mpartipilo** [gatsbyjs/gatsby#4842]
## Description

The link in the 404 page that is supposed to bring the user to a page in the site points to a non-existent url, leading to another 404.

### Steps to reproduce

Open a valid URL: https://gatsbygram.gatsbyjs.org/1632234281433883850/, once it loads, change the browser URL to something non-existent like https://gatsbygram.gatsbyjs.org/1632234281433883850asdf/. 

### Expected result

The link Back to our site should lead to another existent page in the main site.

### Actual result

The link to Back to our site is broken, as it points to the same not-found URL.

### Environment

Currently deployed gatsbygram.gatsbyjs.org. At the time I write this, the github repo shows: "Latest commit e26fe79  5 days ago"

**Comment by kakadiadarpan** [comment]
@mpartipilo this is because of how default 404 are handled by Netlify when the app is not handling 404. I don't think there is anything we can do about this at the moment.
