### ISSUE TITLE
[gatsby-plugin-contentful] GraphQL - allow content-type queries without contents

### ISSUE THREAD

**Issue by rubengarciam** [gatsbyjs/gatsby#4847]
## Description

(I've tried looking around for a solution but haven't been able to find any, hence posting it here; apologies if the answer existed previously).

When querying non-standard data types in Contentful, there might be situations were some content might or not exist but you still need to query for it and validate a 0/null return. Currently, fields that do not have at least 1 populated instance are not created in the graphql schema.

**Example:** 

There's an existing content type _Events_ with information about upcoming events but, at this point of time, there are no events in the future.

Querying for _allContentfulEvent_ should have 0 nodes, while now it fails with

> GraphQL Error There was an error while compiling your site's GraphQL queries.
> Invariant Violation: GraphQLParser: Unknown field `allContentfulEvent` on type `RootQueryType`. Source: document `HomeQuery` file: `GraphQL request`.

### Steps to reproduce

1. Create a new content model.
2. Include query in any post/template

### Expected result

Returns 0 contents, null, an empty array, etc

### Actual result

Error displayed before

### Environment

* Gatsby version: 1.9.202
* gatsby-source-contentful version: 1.3.38

**Comment by m-allanson** [comment]
Hey @rubengarciam, at the moment Gatsby can only structure content from the data available to it. There's not a built-in solution for this yet, however there's a proposed feature over at https://github.com/gatsbyjs/gatsby/issues/4261, and you may be able to find a workaround in https://github.com/gatsbyjs/gatsby/issues/3344 (particularly the linked issues).

**Comment by rubengarciam** [comment]
Thanks @m-allanson! Will have a look at them and see if any could work :) Cheers

**Comment by pieh** [comment]
I'll close this - we already track this problem in issues mentioned in previous comment.
