### ISSUE TITLE
[gatsby-plugin-google-analytics] Exclude option

### ISSUE THREAD

**Issue by valse** [gatsbyjs/gatsby#4848]
Hi,
I added a preview post page in our gatsby blog site as a client only page.
This page is not indexed and I'd like to exclude it from the google analytics pageview event too.

Like the "gatsby-plugin-sitemap" it will be useful add an "exclude" array option to blacklist pages from GA by url prefix or by a regex.

Thanks and go ahead!

**Comment by KyleAMathews** [comment]
Sounds like a nice idea! Happy to take a PR from you or others adding this!

**Comment by valse** [comment]
#4862
