### ISSUE TITLE
Gatsbyjs deleting and adding files in .cache directory many times

### ISSUE THREAD

**Issue by adityapandey9** [gatsbyjs/gatsby#4849]
## Description

I have customized some option for gatsby-source-filesystem plugin. Set the path to the root instead of specific path where markdown file exist. Previously config file data were path --> `${__dirname}/src/posts` and  name --> `posts`. I have change it to path --> `${__dirname}/` and name -> `/`. And the query for the files 

`{
 allFile(filter: {
   internal: {
     mediaType: {
       eq: "text/markdown"
     }
   }
   relativeDirectory: {
     regex: "/src/"
   }
 }) {
   edges {
     node {
       dir
       childMarkdownRemark{
         id
         html
         frontmatter {
           title
           path
           date(formatString: "MMMM DD, YYYY")
         }
       }
     }
   }
 }
}`

It start printing on terminal like 

info changed file at D:\xampp\htdocs\intern\Redcarpet\site\gatsby\.cache\pages.json
info changed file at D:\xampp\htdocs\intern\Redcarpet\site\gatsby\.cache\sync-requires.js
error ENOENT: no such file or directory, stat 'D:\xampp\htdocs\intern\Redcarpet\site\gatsby\.cache\async-requir
es.js.1522930126054'

  Error: ENOENT: no such file or directory, stat 'D:\xampp\htdocs\intern\Redcarpet\site\gatsby\.cache\async-req
  uires.js.1522930126054'

many times. 

### Expected result

Previously it was not printing this type of messages. 

### Environment

* Gatsby version (`npm list gatsby`): 1.9.241
* gatsby-cli version (`gatsby --version`): 1.1.50
* Node.js version: 8.9.0
* Operating System: windows 7 x64

### File contents (if changed):

`gatsby-config.js`: 
module.exports = {
  siteMetadata: {
    title: 'Gatsby Default Starter',
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-catch-links`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/`,
        name: '/',
      },
    },
    `gatsby-transformer-remark`,
  ],
};

`gatsby-node.js`: 
const path = require('path');

exports.createPages = ({ boundActionCreators, graphql }) => {
  const { createPage } = boundActionCreators;
const blogPostTemplate = path.resolve(`src/templates/blog-post.js`);
return graphql(`{
  allFile(filter: {
    internal: {
      mediaType: {
        eq: "text/markdown"
      }
    }
    relativeDirectory: {
      regex: "/src/"
    }
  }) {
    edges {
      node {
        dir
        childMarkdownRemark{
         	excerpt(pruneLength: 250)
          html
          id
          frontmatter {
            date
            path
            title
          }
        }
      }
    }
  }
}`)
    .then(result => {
      if (result.errors) {
        return Promise.reject(result.errors);
      }
      // console.log("SS: ", JSON.stringify(result))
result.data.allFile.edges
        .forEach(({ node }) => {
          // console.log("Node: ", JSON.stringify(node))
          createPage({
            path: node.childMarkdownRemark.frontmatter.path,
            component: blogPostTemplate,
            context: {} // additional data can be passed via context
          });
        });
    });
}

**Comment by m-allanson** [comment]
Using `${__dirname}/` as the path is telling `gatsby-source-filesystem` to watch Gatsby's cache folder, which will receive writes from Gatsby as part of the build process. You'll need to change the path to `${__dirname}/src/` or create multiple paths as shown [in this example](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-filesystem#how-to-use).

**Comment by adityapandey9** [comment]
Thanks, I am new in Gatsby. Your solution works fine.

**Comment by m-allanson** [comment]
Good stuff, thanks for following up!
