### ISSUE TITLE
IndexRoute for markdown files with custom path?

### ISSUE THREAD

**Issue by f0rr0** [gatsbyjs/gatsby#485]
If I have a `about.md` file in `./pages` directory with `path` set to `/about/index.html`, this file will not be rendered as `IndexRoute` at `/about/` due to the way `IndexRoute`  is [currently set](https://github.com/gatsbyjs/gatsby/blob/dcb4d7b53d4135edb0eacbf2695ae18825dee531/lib/isomorphic/create-routes.js#L148) in `create-routes.js`.

**Comment by KyleAMathews** [comment]
IndexRoute's are a bit odd. They're only used for the route which should render by default for a given parent route. So how Gatsby figures this out is it sets the IndexRoute to the `index.*` in the same directory as a `_template.*` file.

This is more explicit in Gatsby 1.0.
