### ISSUE TITLE
Gatsby.js promo materials?

### ISSUE THREAD

**Issue by grantmoran** [gatsbyjs/gatsby#4857]
I was wondering if there is anyone involved in designing or creating some simple promo materials for Gatsby. Personally I'd love to see some official laptop stickers released!

Is there a core project member that would be willing to link up with a service like [unixstickers.com](http://www.unixstickers.com/)? They handle production / shipping but a portion of the sales goes back to supporting the project. It's small but something and could add up eventually.

👍 if you'd like to see some stickers!

**Comment by KyleAMathews** [comment]
@jlengstorf @kkemple @fk were chatting about putting some together I believe

**Comment by kkemple** [comment]
I've been gathering some assets we think could make good stickers! I haven't really thought about vendors, it looks like that site sells them for you? Is that how it works?

**Comment by m-allanson** [comment]
Stickers have been ordered :tada: https://twitter.com/jlengstorf/status/1007657688174481408

Keep an eye on twitter or the blog for more news on that soon.
