### ISSUE TITLE
[gatsby-transformer-remark] Ast cache possible bug

### ISSUE THREAD

**Issue by DxCx** [gatsbyjs/gatsby#4860]
Hey!

I'm just revising the code, and i've found a possible bug with ASTPromiseMap,
so this is a suggestion to revisit it yourself ;)

https://github.com/gatsbyjs/gatsby/blob/362f78a3e16830770b68023e8e939992e47a3cb5/packages/gatsby-transformer-remark/src/extend-node-type.js#L200-L208

Shouldn't that be:
```Javascript
     // Save new AST to cache and return 
     cache.set(cacheKey, ast) 
     // We can now release promise, as we cached result 
     ASTPromiseMap.delete(cacheKey) 
     return resolve(ast) 
   }) 
   ASTPromiseMap.set(cacheKey, ASTGenerationPromise) 
   return await ASTGenerationPromise 
 } 
```

Note that `astCacheKey` is a function, while `cacheKey` is the original key used to store the promise.

**Comment by pieh** [comment]
Your change seems fine, `cacheKey` is actually result of `astCacheKey(markdownNode)`:
https://github.com/gatsbyjs/gatsby/blob/362f78a3e16830770b68023e8e939992e47a3cb5/packages/gatsby-transformer-remark/src/extend-node-type.js#L98

So your change just remove unnecessary function call and use stored value, but doesn't really change anything. Is it actually bugged currently?

**Comment by DxCx** [comment]
Well, you use delete but pass function as a key, so nothing is really deleted..

**Comment by pieh** [comment]
Ohhh, sorry - you are right, I didn't notice that other change which is important! Could you create PR with change?
