### ISSUE TITLE
[gatsby-source-wordpress] - error when ACF feature is active but not used in a post resulting in an unexpected value in the api

### ISSUE THREAD

**Issue by jamiepotepa** [gatsbyjs/gatsby#4864]
Hi

I've been migrating our current Wordpress site to take advantage of Gatsby but ran into an issue with ACF. I have a Relationship field added to our posts for some internal linking. If the field isn't used then the Wordpress api returns an empty string instead of an array. I get the below errors when running Gatsby.

 Error: acf fields must be an object with field names as keys or a function which returns such an object.
  - Array.forEach
  - Array.forEach
  - Array.forEach
  - Array.forEach

I've read that Wordpress can return unexpected results and this is the case for me. I have fixed my issue by editing the normalizeACF function located at line 78 in normalise.js in the source files. I changed it to the below to solve my issue based on the example at the bottom here: https://spectrum.chat/thread/4cabd489-5b0b-4998-b961-76fe60429af4

```
var normalizeACF = function normalizeACF(entities) {
  return entities.map(function (e) {
    if (!_.isPlainObject(e[`acf`])) {
      delete e[`acf`];
    } else {
        e[`acf`] = _.mapValues(e[`acf`], function(value) {
            return value || null;
        });
    }
    return e;
  });
};
```

This works fine for me as I only have one ACF field but is there a better way I should be doing this to cover other use cases?

**Comment by pieh** [comment]
Try adding code snippet from here https://github.com/gatsbyjs/gatsby/issues/4461#issuecomment-371775563 to your wordpress `functions.php`

**Comment by jamiepotepa** [comment]
Hi Pieh

I came across your answer and tried it earlier but it didn't work. When I checked my endpoint http://MY-SITE/wp-json/acf/v3/posts I was still receiving empty strings. 

The overview from ACF docs states:
This filter is applied to the $value after it is loaded from the db and before it is returned to the template via functions such as get_field().

so not sure how you can get it to affect the api call as well.

**Comment by pieh** [comment]
`acf-to-rest-api` plugin does use `get_field`/`get_fields` functions internally, so output is affected by those filters

**Comment by pieh** [comment]
Can you share your endpoint so I could check it locally (this might be some other issue)? Either here or privately on discord channel https://discord.gg/0ZcbPKXt5bVoxkfV via PM (my handle on discord is grajen3)

**Comment by jamiepotepa** [comment]
I've been working on this issue locally and trying all sorts but I've just added your filter code to our live server.

Endpoint: https://weareready.com/wp-json/acf/v3/posts?per_page=20. Post 18 is the first one that isn't using the advanced_linking, therefore, returning an empty string.

**Comment by pieh** [comment]
This is really weird, this code snippet has proven to be working many times, so not sure why it wouldn't for You. Are you sure its `relationship` field? Maybe we just target wrong field type?

**Comment by jamiepotepa** [comment]
Hi Pieh, To confirm I am using the relationship field. I've added an additional text field with some dummy text which is showing at this endpoint: https://weareready.com/wp-json/acf/v3/posts/3402. In my functions.php I have the below code but as you can see I am still getting an empty string and my default text.

```
function nullify_empty($value, $post_id, $field) {
    if (empty($value)) {
        return null;
    }
    return $value;
}

function nullify_text($value, $post_id, $field) {
    $value = null;
        return $value;	
}

add_filter('acf/format_value/type=relationship', 'nullify_empty', 100, 3);
add_filter('acf/format_value/type=text', 'nullify_text', 100, 3);
```

**Comment by pieh** [comment]
This seems like filters you add have no effect - this might be either:
- your functions.php is not ran at all
- maybe your acf version doesn't support these filters - what version do You use?

Maybe try doing `var_dump(get_field('advanced_linking', 3402));` in one of your wordpress pages to see if it will show empty string or null

**Comment by jamiepotepa** [comment]
The functions.php is being called as the site is a custom build full of other code. I have worked out the issue though. It seems that the filters I am using:
```
add_filter('acf/format_value/type=relationship', 'nullify_empty', 100, 3);
add_filter('acf/format_value/type=text', 'nullify_text', 100, 3)
```;

are taking effect in the Admin area only. This means I have to go into each post and manually click update for the filters to save and take effect.  For example, if I select a post to advance link to and click update, the admin area will stay blank as the filter is displaying null. If I then reload the page and dump out get_field, the value is that of the post I previously selected. I then have to go back into that post and click update to save the filtered results. I was hoping the filter would just override all previously save field data in every post. To note though,  even by going back in and clicking update with a blank relationship field, it still displays an empty string on the front end and in the api.

I think I'm going to leave this now as I've changed the gatsby plugin to achieve what I need it to. Thanks very much for your help in this.

**Comment by pieh** [comment]
hmm this is weird - this should be called everytime `get_fields` is called. ACF make use of wordpress cache but it is not persistent by default - do you use anything that takes takes care of wordpress cache? it might suggest that this thing doesn't honor `wp_cache_add_non_persistent_groups` function

**Comment by jamiepotepa** [comment]
We don't have any cache plugins installed but the admin team have added jetpack. I'm not sure if that handles any caching?

Like I said above the filters are working when I go to the post in the admin section but like you, I thought if they are applied, they would filter the text on each page template.

**Comment by jamiepotepa** [comment]
For future readers:

If you have the ACF to REST API plugin installed. Go to the plugins page and click settings on this plugin. This will take you to the permalink page. Scroll down to the ACF to REST API section and change the Request Version to v2. Doing this fixed my issue without having to edit node_modules.

**Comment by pieh** [comment]
Closing this - problems seems to be on wordpress side of things and there's not much Gatsby can do about it currently
