### ISSUE TITLE
[gatsby-plugin-sharp] npm install is broken by imagemin-pngquant dependency

### ISSUE THREAD

**Issue by shaunbent** [gatsbyjs/gatsby#4866]
## Description

This issue is pretty well documented down the chain but `pngquant-bin` a dependency of `imagemin-pngquant` is currently breaking the `npm install` process. It seems to be mainly effecting Linux systems aka common build environments. As a result, in my case I am not able to build and deploy my site.

https://github.com/imagemin/imagemin-pngquant/issues/46
https://github.com/imagemin/pngquant-bin/issues/78

I wonder if we could downgrade the version of `imagemin-pngquant` required by `gatsby-plugin-sharp` to `5.0.1` so avoid the broken version.

### Environment

* Gatsby version (`npm list gatsby`): `gatsby@1.9.231`
* gatsby-cli version (`gatsby --version`): `1.9.194`
* Node.js version: `9.8.0`
* Operating System: MacOS 10.13.4

**Comment by KyleAMathews** [comment]
Yeah, that seems like a reasonable fix. Is there any big differences between `pngquant-bin` v3 and v4?

**Comment by shaunbent** [comment]
Looks like v4 introduces a dependancy on Node V4 as well as this commit which is the one that seems to be causing everyone problems: https://github.com/imagemin/pngquant-bin/pull/75

**Comment by shaunbent** [comment]
https://github.com/gatsbyjs/gatsby/pull/4915
