### ISSUE TITLE
[gatsby-node] How to get request?

### ISSUE THREAD

**Issue by liqueflies** [gatsbyjs/gatsby#4868]
## How to get request into gatsby-node?
Hi folks, thanks for awesome work.

I've two language and i need to redirect app based on browser language with `createRedirect`.
I can use ```req.headers["accept-language"]``` in any node app, `req` is representing the request.

How to get access to request?

### File contents (if changed):

my `gatsby-node`:

```
const path = require('path')

const browserRequestLanguage = // how to get request?

exports.createPages = ({ boundActionCreators, graphql }) => {
  const { createPage, createRedirect } = boundActionCreators

  const locales = ['it', 'en']

  locales.map(locale => createPage({
    path: `/${locale}`,
    layout: locale,
    component: path.resolve(`src/pages/IndexPage.js`),
    context: {
      locale,
    },
  }))

  createRedirect({
    fromPath: `/`,
    isPermanent: true,
    redirectInBrowser: true,
    toPath: `/${browserRequestLanguage}`,
  })
}
```

**Comment by pieh** [comment]
Closing as not directly related to `gatsby`
