### ISSUE TITLE
Add an option to configure default image quality for ImageSharp queries

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#4873]
Currently, the default quality of ImageSharp-generated images are too low for most of the projects I participate in. I would like to configure a global default for ImageSharp query parameters, because it may become tedious to always specify `quality: 92` in every single image query.

Issue #3837 is related, but it's about specifying a default locale for Moment.js date queries.

**Comment by pieh** [comment]
If anyone is interested in doing this - this could be done by adding optional config paramater to `gatsby-transformer-sharp` and using it instead of default `50` in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-sharp/src/extend-node-type.js

**Comment by KyleAMathews** [comment]
50 quality is often recommended as a good default as it's good enough quality while providing significant size savings. I agree that providing a way to override it globally for a project makes sense.

**Comment by KyleAMathews** [comment]
ImageMagick has many other uses other than generating thumbnails for the web so its default isn't necessarily what you'd want for the web.

**Comment by kripod** [comment]
@KyleAMathews Sounds fair, thank you for the explanation!

**Comment by anthw** [comment]
@pieh please could you provide an example of how I would configure this, would it be in gatsby-config.js ? I looked at the file you linked too but can't figure out what I need to do, I currently have:

```
{
  resolve: `gatsby-source-filesystem`,
  options: {
    name: `src`,
    path: `${__dirname}/src/`,
  },
},
```

**Comment by gricard** [comment]
If no one else is working on this then I'll snag it for Hacktoberfest. :)

**Comment by gricard** [comment]
Cool. Thanks!

**Comment by gricard** [comment]
I'm super sorry, but I've been real busy with other stuff and traveling for work and never ended up having time to work on this. If anyone else wants to take it, go for it. Otherwise I'll see if I can get to it soon. :(

**Comment by SheldonNunes** [comment]
I am happy to pick this one up :)

**Comment by SheldonNunes** [comment]
I was looking to use the `Cache` util like so `const Cache = require('gatsby/src/utils/cache')`  from the gatsby project. It doesn't look like any other plugins use it explicitly. I am wanting to use it to store the defaultQuality value so it can be more globally applicable.

Otherwise would implementing a `gatsby-transformer-sharp-quality` plugin that can hold that quality option be more appropriate?

**Comment by justinformentin** [comment]
I could be completely wrong, so hopefully someone will add to this post, but I think dealing with the cache may be unnecessary.

`gatsby-remark-images` has a quality option, so why not look to emulate what that plugin's doing? If you go to the index file, there's nothing about quality anywhere. 

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-images/src/index.js

But you'll notice `const { fluid } = require(`gatsby-plugin-sharp`)`  So if we go to the plugin-sharp's index, you'll see the default quality: 50 under `const generalArgs`.

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sharp/src/index.js

So, I'm not sure what needs to be done to connect it all together to get the same thing in transformer-sharp, but hopefully I'm on the right track.

Also, for what it's worth, I think a separate plugin just to set the default quality is overkill.
