### ISSUE TITLE
Adding Firebase Hosting Scripts 

### ISSUE THREAD

**Issue by will-sparger** [gatsbyjs/gatsby#4875]
## Description

I'm not clear how to add the config snippets for Firebase hosting to my project. I searched the docs as well as googled approaches but wasn't able to find info that clarified the solution for me.

<img width="777" alt="firebase config snippets" src="https://user-images.githubusercontent.com/23318203/38446085-cdfca8b2-39bb-11e8-9032-f4cc51f7caf4.png">

In a standard React app you add the scripts to the bottom of the public index.html's body and are good to go.

>>> https://www.gatsbyjs.org/docs/custom-html/#adding-custom-javascript

Is the **Adding custom Javascript** section in the above link what I need to do in this case? I successfully initialized firebase in the project via the command line (below image) but haven't been able to figure out adding the configuration as well. 

<img width="231" alt="firebase files" src="https://user-images.githubusercontent.com/23318203/38446127-10bc284e-39bc-11e8-86b9-dece27359731.png">

**Comment by pieh** [comment]
Do you want to use any firebase services in your website or just their hosting? If just for hosting - check this blog post - https://heygrady.com/first-launch/ it seems to have instructions how to setup deployment

**Comment by will-sparger** [comment]
Thanks for the reply Michal.

Just looking to use hosting right now. I reviewed  https://heygrady.com/first-launch/  a couple of times actually and it does not address adding the config info I mention in my original post. Additionally, he was using an older version of Gatsby that doesn't align with how it appears to work now (v1.0.0). Specifically:

<img width="651" alt="deploy guidance" src="https://user-images.githubusercontent.com/23318203/38458870-880fad74-3a68-11e8-8e46-d65bee93eec9.png">

^ I don't show any deploy script in my package.json but he seemed to have a gh-pages default deploy in his config. He discusses setting up a Firebase account and initializing it via the command line but I have already completed these steps. 

When I go to the url generated by Firebase for the project I see the message below which in the past indicated I had not completed configuration. If configuration was fully in place I would see my app homepage.

<img width="856" alt="firebase message" src="https://user-images.githubusercontent.com/23318203/38458977-a41cb3da-3a69-11e8-89d4-23f7113c15e7.png">

Console error:

<img width="507" alt="firebase console error 404" src="https://user-images.githubusercontent.com/23318203/38458983-b2131542-3a69-11e8-9598-201398b3ff25.png">

Any advice?

**Comment by pieh** [comment]
For hosting you shouldn't need to include those firebase init scripts - these are to use their services (database, auth, etc) in your web app.

You should have index.html after succesful `gatsby build` (that is - if you have index file in your project)

**Comment by pieh** [comment]
Glad you got it working. 

I'll close this issue as problem was resolved :)
