### ISSUE TITLE
[Docs] Minor clipping of sidebar bottom margin w/ banner 

### ISSUE THREAD

**Issue by giladronat** [gatsbyjs/gatsby#4878]
Super minor visual issue: many (all?) pages that have a sidebar and display the banner of Kyle’s workshop have an _issue displaying the bottom links in the sidebar_. 

I have no idea what CSS magic is required to fix this, so I’m posting the issue.

### Actual

See bottom left. Sidebar scrolled all the way down. Latest Safari on macOS.

![screen shot 2018-04-06 at 17 45 07](https://user-images.githubusercontent.com/2069737/38449340-8ff1e486-39c2-11e8-8415-110b718ab922.png)

![screen shot 2018-04-06 at 17 44 57](https://user-images.githubusercontent.com/2069737/38449343-9683136a-39c2-11e8-853f-98c3ca24e75e.png)

### Expected

Links at the bottom should not clip, or at the very list be visible.

(I tried deleting the banner in the Inspector, didn’t help 😅)

### Notes

Probably not important if this is the only time a banner will be displayed, but it’s something that could be improved 😃

**Comment by KyleAMathews** [comment]
Ugh, adding that banner was way trickier than I expected. Lemme fix this.

**Comment by KyleAMathews** [comment]
Fix on its way out, thanks for the detailed bug report!
