### ISSUE TITLE
Use react helmet as default

### ISSUE THREAD

**Issue by dardub** [gatsbyjs/gatsby#488]
I just wanted to get your thoughts on replacing react document title with react helmet.  Since react helmet is more full featured as mentioned on react document title documentation. I think it's needed if you want different meta description or facebook opengraph meta from page to page.

**Comment by MoOx** [comment]
I confirm it's a good, choice. Really mature & flexible. We use it for Phenomic and it's 👌

**Comment by KyleAMathews** [comment]
Agreed :-) @chiedo actually switched out all the starters to use it a few weeks ago e.g. https://github.com/gatsbyjs/gatsby-starter-blog/pull/15 It's an [easy switch](https://github.com/gatsbyjs/gatsby-starter-blog/pull/15/files) so go ahead!

**Comment by f0rr0** [comment]
Did the same thing today https://github.com/f0rr0/f0rr0.github.io/commit/8fb4da489099c35b887e10b605245b187b421ed5

**Comment by dalareo** [comment]
I am also migrating to Helmet but: 

How can I use config data here?

    meta={[
                  {"name": "description", "content": "Sitio web personal: artículos, proyectos y material de autobombo" },
                ]}

I want to replace "Sitio (...) autobombo" for { config.siteDescrp }
