### ISSUE TITLE
[Question] Extend node on client side

### ISSUE THREAD

**Issue by DxCx** [gatsbyjs/gatsby#4882]
Hey!

I there any way today to define client side graphql properties? (Or, resolvers)
For example, i have on server side some node which contains ‘values’
And i want (on client side object, after query) have 1 more field named sum (getter) which is actually a function defined on client side which gets the node and sum the values..
(My real case is abit more complicated then that)

Is this possible today?
If not, i might implement it myself, however, is client side GraphQL is a wanted feature?

**Comment by pieh** [comment]
Not possible currently with client graphql - gatsby run graphql stuff only during build - outputted site have no idea about graphql at all - its all json objects there with results of the queries. Having something like this in client runtime might be a little bit heavy - but not sure how would you see it and what it would involve - could you elaborate?

**Comment by DxCx** [comment]
Even if that happen, all i need is the field to be evaluated on client side.. are you using apollo client today? Or?
Basiclly i have ast on graphql server which i want to render on client

**Comment by pieh** [comment]
We don't use any sort of graphql client - graphql queries are run locally during the build and results are saved as plain json files.

You can just do whatever you need to do outside of graphql, right?

**Comment by DxCx** [comment]
yeah yeah i'll take alook at the internals, thanks =)
