### ISSUE TITLE
Nested directories for components in "pages" and "wrapper" directories

### ISSUE THREAD

**Issue by TheTourer** [gatsbyjs/gatsby#489]
Firstly, forgive me if this is documented somewhere, but I've not been able to find it if it is (if it can be done through overriding the Webpack config, that'd be fine as well obviously!).

I am a big fan of organizing all of my Component + CSS Modules (plus any other resources) together in directories. As a test, I have so far done this with the Bio and ReadNext components in the base blog starter:

```
<project root>/
   components/
      Bio/
         index.js
         Bio.module.scss
         profile-pic.png
      ReadNext/
         index.js
         ReadNext.module.scss
```

This worked fine, as I expected—just had to change some import statements; however, the same doesn't seem to work for `wrapper/` (specifically converting `md.js` -> `md/index.js`) or for the component JS files within `pages/`. Because I can't find any references to the components `Template`, `MarkdownWrapper` or `BlogIndex`, I'm not sure how to move these files into subdirectories without breaking everything.

Can someone point me in the right direction to get this working correctly? Thanks in advance!

**Comment by f0rr0** [comment]
I was facing the same issue. The simplest (not ideal) way could be to use symlinks. Gatsby expects certain files to be in certain places, if I am not wrong. You can put the the files wherever you want and add symlinks where gatsby expects them. See https://github.com/f0rr0/f0rr0.github.io

**Comment by KyleAMathews** [comment]
`/pages` => all page types (e.g. .md, .js., .jsx, .yaml, .json, .cjsx) get turned into pages automatically *unless* you prefix the name with an underscore e.g. `/pages/about/_this-is-just-a-component.js`.

`/wrappers` => wrappers are special react components which wrap non-component files in `/pages` and have to go here. They have to be named the same as the file extension they're wrapping e.g. `md.js` wraps `*.md` files.

`/*` do whatever you want. No other directory names (other than `/node_modules` has any significance so name them as you will and require/import them in. `/components` and `/css` or `/styles` are common folder names.

**Comment by oliverbenns** [comment]
Is it possible we could add functionality so we can prefix an entire directory? E.g. `/pages/about/_components/title.jsx`?

**Comment by KyleAMathews** [comment]
Possibly! But the normal convention is to put components in its own directory outside of pages. Webpack is setup by gatsby so you can then do require('components/Button') or whatever

**Comment by oliverbenns** [comment]
Yeah, you're right. But I've always seen the `components` as where all the dumb components live. Sometimes other container components are needed that aren't whole pagesbut are specific to certain pages.

**Comment by scottyeck** [comment]
(Just now hopping on the Gatsby train. This is very very awesome and I'm excited to dig in.)

Given I experienced the same confusion met by both @TheTourer and @f0rr0 , maybe this is worth mentioning explicitly in the docs? (Probably somewhere around [here](https://github.com/gatsbyjs/gatsby#structure-of-a-gatsby-site).) I'm happy to submit a PR if y'all agree.

**Comment by KyleAMathews** [comment]
@scottyeck yes, this should be in the README — would love a PR! (And welcome aboard!)

**Comment by jbolda** [comment]
I'm guessing this is resolved or you are on v1  🙂
