### ISSUE TITLE
[gatsby-link] Make it usable outside Gatsby

### ISSUE THREAD

**Issue by rstacruz** [gatsbyjs/gatsby#4892]
## Description

If you try to use `<Link />` outside of Gatsby (eg, when running tests), it fails because the component tree doesn't have the context injected by Gatsby:

```
    TypeError: Cannot read property 'history' of undefined

      at new GatsbyLink (node_modules/gatsby-link/index.js:107:34)
      at constructClassInstance (node_modules/react-dom/cjs/react-dom.development.js:6355:20)
      at updateClassComponent (node_modules/react-dom/cjs/react-dom.development.js:7839:9)
```

It'd be nice if `<Link />` will fallback to a common `<a href=...>` in the absence of this context.

## Example

If you have a component (eg, `MyMenu.js`) that uses gatsby-link:

```js
import * as React from 'react'
import Link from 'gatsby-link'

export const MyMenu = () => (
  <nav>
    <Link to='/'>Home</Link>
  </nav>
)
```

And have a test file that renders with it (using Jest syntax here, but it doesn't matter what test harness you use):

```js
import * as React from 'react'
import { render } from 'react-dom'
import MyMenu from '../MyMenu'

it('works', () => {
  const div = document.createElement('div')
  render(<MyMenu />, div)
})
```

You'll get :warning: `TypeError: Cannot read property 'history' of undefined`.

## Environment

* Gatsby version (`npm list gatsby`): gatsby@1.9.236
* gatsby-cli version (`gatsby --version`): n/a
* Node.js version: 8.10.0
* Operating System: Linux

**Comment by KyleAMathews** [comment]
Hmmm yeah. What do people normally do when testing components that rely on context?

**Comment by phs1919** [comment]
I had the same issue when testing Gatsby Link. [This comment](https://github.com/gatsbyjs/gatsby/issues/2932#issuecomment-377009281) was useful to solve it. Hope this helps you :)

**Comment by rstacruz** [comment]
Testing things with context? It really depends. I typically do one of two things:

1. Create a context-less version (eg, `<MediaPlayerView>`) that's used by a "connector" component (eg, `<MediaPlayer>`) which will convert context stuff into props. I can now just test the `<MediaPlayerView>` component.

2. Create a mock context.

Anyway, I'd really love for this for react-storybook too, so I can make storybook pages out of my components that use gatsby-link!

**Comment by KyleAMathews** [comment]
Perhaps it'd be best to just create a context-less version? Can react-storybook do aliases? E.g. in there just create a component that wraps `<a>`. gatsby-link just has a bunch of logic necessary to make Gatsby page loading work, etc.

**Comment by varya** [comment]
I have the same problem. Is it possible to provide a property which would render `Link` but not access context things? This way it would be visible how it looks. This is what testing cares about.
