### ISSUE TITLE
Google Fonts URL missing 'https:' in link after running `gatsby build`

### ISSUE THREAD

**Issue by jjprevite** [gatsbyjs/gatsby#4895]
## Description

There is an issue when running `gatsby build` where the Google Fonts are not loaded correctly because the `href` attribute is missing the `https:`:
<img width="1049" alt="screen shot 2018-04-08 at 8 54 21 pm" src="https://user-images.githubusercontent.com/3806031/38478893-9a80da6a-3b70-11e8-899c-69dd6026fd4e.png">

I am not sure if this is an error with the `gatsby build` process or `typography.js`. 
### Steps to reproduce

1. Create a new gatsby site with `gatsby new gatsby-example-site`
2. Run `npm i --save typography gatsby-plugin-typography`
3. Create a new directory inside `src/utils` and add the file `typography.js`
4. Add the following to the `typography.js` file:

```javascript
import Typography from 'typography'

const typography = new Typography({
  baseFontSize: '22px',
  scaleRatio: 3.5,
  googleFonts: [
    {
      name: 'Varela Round',
      styles: ['400'],
    },
    {
      name: 'Raleway',
      styles: ['400'],
    },
  ],
  headerFontFamily: ['Varela Round', 'sans-serif'],
  bodyFontFamily: ['Raleway', 'sans-serif'],
})

export default typography
```
5. Modify your `gatsby-config.js` to use the typography plugin
6. Delete the `index.css` file inside `src/layouts` (otherwise it will override your styles)
7. Run `gatsby build`
8. Open the `index.html` file in your browser. Notice the `font-family` on the headers and body.

### Expected result

The site should be using 'Varela Round' for headers and 'Raleway' for the body font. 

### Actual result

The site can't find the Google Fonts because the link to the fonts is missing the `https:`.

### Environment

* Gatsby version (`npm list gatsby`):  error?
<img width="260" alt="screen shot 2018-04-08 at 9 01 54 pm" src="https://user-images.githubusercontent.com/3806031/38479069-c5cfadb2-3b71-11e8-8c5c-c9ef3de4c1ea.png">

* gatsby-cli version (`gatsby --version`): 1.9.247
* Node.js version: 9.8.0
* Operating System: macOS 10.13.3

### File contents (if changed):

`gatsby-config.js`: 
```javascript
module.exports = {
  siteMetadata: {
    title: 'Gatsby Default Starter',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    {
      resolve: `gatsby-plugin-typography`,
      options: {
        pathToConfigModule: `src/utils/typography.js`,
      },
    },
  ],
}

```
`package.json`: 
```javascript
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "gatsby": "^1.9.241",
    "gatsby-link": "^1.6.39",
    "gatsby-plugin-react-helmet": "^2.0.8",
    "gatsby-plugin-typography": "^1.7.18",
    "react-helmet": "^5.2.0",
    "typography": "^0.16.6"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write 'src/**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "prettier": "^1.11.1"
  }
}

```
`gatsby-node.js`: not changed
`gatsby-browser.js`: not changed
`gatsby-ssr.js`: not changed

*Here's a [link to a repo](https://github.com/jjprevite/gatsby-issue) with all the code in case that helps:

**Comment by KyleAMathews** [comment]
This is a "protocol-relative URL". We use it because we don't know if the person will be loading google fonts from https or http and this works on both. Not sure why you're fonts aren't loading but this isn't the problem.

Another option is to just use typefaces and skip google fonts altogether — https://github.com/kyleamathews/typefaces

**Comment by jjprevite** [comment]
Ah okay - got it, that makes sense. Thanks for the quick response! @KyleAMathews
