### ISSUE TITLE
[gatsby-source-wordpress] not getting all ACF fields when theres too much data

### ISSUE THREAD

**Issue by cwahlfeldt** [gatsbyjs/gatsby#4903]
### Description

I'm noticing an issue with the gatsby-source-wordpress plugin. It seems to be failing silently for some ACF fields. I'm able to initially see all the data attached to a custom post type ("Product"), but when I start to add content to multiple products, some of the data goes missing and I cant seem to see the fields again in graphiql or running queries during a build. Verbose output is giving me OK for all Product content and I can still see most of the ACF data while running graphiql except for a repeater field and an upload field. These fields exist in the rest data and can be seen from the REST API.

### Steps to reproduce

- Create a custom post type in your wordpress installation.
- Add different ACF fields to that type.
- Add as much test data as possible as I think this relies on heavy data.
- Try to fetch the wordpress data from your Gatsby site.

### Expected result

I expect to get all ACF fields and there corresponding child fields. 

### Actual result

Im not geting all ACF fields to show in graphiql or on normal gatsby builds.

I run the following query in graphiql on the data and get errors.

```
{
  allWordpressWpProduct {
    edges {
      node {
        title
        acf {
          manufacturer
          product_category
          featured_image
          gallery
          description
          misc_equipment
          aerial_equipment
          misc_equipment
          specs {
            spec
          }
          file_upload {
           source_url
          }
          product_type {
            product_category
            aerial_equipment
          }
        }
      }
    }
  }
}
```

which spits out the following errors:

```
{
  "errors": [
    {
      "message": "Cannot query field \"specs\" on type \"acf_4\".",
      "locations": [
        {
          "line": 15,
          "column": 11
        }
      ]
    },
    {
      "message": "Cannot query field \"file_upload\" on type \"acf_4\".",
      "locations": [
        {
          "line": 18,
          "column": 11
        }
      ]
    }
  ]
}
```

If you compare the query to the rest API there is obviously a disconnect because the data clearly exists in the rest API.

http://dev-kemper.pantheonsite.io/wp-json/wp/v2/product

### Environment

* Gatsby version (`npm list gatsby`): gatsby@1.9.202
* gatsby-cli version (`gatsby --version`): gatsby-cli@1.1.49
* Node.js version: v9.11.1
* Operating System: macOS 10.13.1

### File contents (if changed):

https://github.com/mckenziewagner/kemper
see them all in the github repo dont wanna clutter this issue with code.

`gatsby-config.js`: 
`package.json`: 
`gatsby-node.js`: 
`gatsby-browser.js`: 
`gatsby-ssr.js`: 

Thanks!!!

**Comment by cwahlfeldt** [comment]
Might be a duplicate of #4864?

**Comment by sebastienfi** [comment]
That's also what I'm thinking

**Comment by pieh** [comment]
Please check https://www.gatsbyjs.org/packages/gatsby-source-wordpress/#graphql-error---unknown-field-on-acf . I'll close issue because there wasn't any activity here lately.
