### ISSUE TITLE
source plugins: create or find package for managing http requests

### ISSUE THREAD

**Issue by pieh** [gatsbyjs/gatsby#4904]
source plugins can implement this feature on their own, but this seam like common problem we could solve with utility package that could handle:

- limiting maximum number of concurent requests
- rate limiting
- handle automatic retry after 503 response

this should be configurable per source plugin entry in `gatsby-config.js` with sane defaults

ref: https://github.com/gatsbyjs/gatsby/pull/4884

**Comment by tsimons** [comment]
Love the idea of having the different queues setup

**Comment by pieh** [comment]
I'd like to move forward with this and I think I will be implementing it myself as I can't find package that would do most of requierments.

My plan is to create `gatsby-fetcher` package that would be dependency (or peerDependency) of wordpress and drupal plugins (for start - this can be added to other plugins later). This would not be gatsby plugin - more of a utility package - similiar to `gatsby-paginate` or `gatsby-node-helpers`.

In initial PR I would like to implement request queue (which is already done in referenced PR) and 503 retry.

I am thinking about concurrency setup vs ability to fine-tune settings yourself, maybe we think of "high", "medium", "low" as presets that can be used instead of explicit settings:

```js
{
  resolve: `gatsby-source-drupal`,
  options: {
    baseUrl: `your-url`,
    fetcher: `medium`
  },
},
```
Would be just short way of something like this:
```js
{
  resolve: `gatsby-source-drupal`,
  options: {
    baseUrl: `your-url`,
    fetcher: {
      concurrent: 10,
      maxRetries: 3,
      retryDelay: 1000
    }
  },
},
```
Source plugin would just pass those options to fetcher pacakge when initializing queue and it could default to "medium"

Does this make sense?

**Comment by KyleAMathews** [comment]
Something that occurred to me the other day that'd be useful is an automatic backoff — if the fetcher gets 503(s), it'd automatically slow down the concurrency.

**Comment by pieh** [comment]
Yes, I was thinking about it - from technical standpoint I'm not sure if we can adjust `concurrent` in `better-queue` (which I will probably use) or this would involve creating new queue and redirecting tasks etc.

**Comment by KyleAMathews** [comment]
Yeah, we'd need to add support for changing concurrency to `better-queue` https://github.com/diamondio/better-queue/issues/33

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
