### ISSUE TITLE
Automating performance testing to maintain small bundle sizes and fast loading over lifetime of project

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#491]
There's some really cool ideas in this post https://medium.com/engineering-housing/continuous-integration-using-webpagetest-and-webpack-1f4465d95405#.9j1ttu4h6

I've been thinking about some of these ideas on a smaller scale e.g. tracking route sizes on a local machine and showing a table after builds and highlighting if any bundles grew significantly.

But any larger project is going to have a build environment of some sort off the developers machines and so there's the question of how to collect build info from there. But then also, as this article shows, collecting real world perf info via webpagetest would be super valuable as well.

I think there's a lot here that we could do to make these perf testing available to everyone regardless of the scale of your site. Even one-dev sites developed on your machine could still have a testing workflow where you build and push to a temp host (there's lots these days) to get performance results.

It also might make sense to build a free service to store this info. I.e. put it on AWS lambda which is basically free for something of this scale.

**Comment by bvaughn** [comment]
Say it ain't so, bot.

**Comment by KyleAMathews** [comment]
Bad bot!
