### ISSUE TITLE
Links break, unable to navigate

### ISSUE THREAD

**Issue by vojtechruz** [gatsbyjs/gatsby#4911]
Sometimes when navigating my page, all internal navigation links stop working.

Console log in attachment.

Source code available here:
https://github.com/vojtechruz/vojtechruzicka-blog

![bug](https://user-images.githubusercontent.com/7038612/38547731-22ebc564-3cb0-11e8-9f7e-70df576c4a7d.gif)

**Comment by KyleAMathews** [comment]
I haven't seen this error before nor have I seen it reported which suggests it's a bug in your code. If you're able to isolate the problem and it is something wrong with Gatsby, please let us know!

We'll be adding error boundary support in Gatsby v2 which will help with bugs like this! https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html#introducing-error-boundaries
