### ISSUE TITLE
Add bots for common PR blockers 

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#4918]
## Description

Pull Request checks can fail due to some common, easily fixable reasons. Create a bot that looks out for these and posts a comment describing how to fix the failing checks.

The bot could check for the following:

* Failling snapshots
* Missing DCO sign-off

Optionally the bot could post a more descriptive message for first-time contributors vs repeat contributors.

Is there anything else the bot could check for? (maybe this should be an RFC?)

### Steps to reproduce

Create a PR with failing snapshots and no DCO sign-off

### Expected result

A bot should comment on the PR describing how to create a DCO sign-off and update test snapshots.

### Actual result

PR checks will fail, but you're required to click through to the 'Details' link on each failing check.

**Comment by KyleAMathews** [comment]
https://github.com/danger/danger-js is one solution for this I know of.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
