### ISSUE TITLE
Hacktoberfest 2016

### ISSUE THREAD

**Issue by gesposito** [gatsbyjs/gatsby#492]
@KyleAMathews interested in getting new contributors?
https://hacktoberfest.digitalocean.com/

**Comment by KyleAMathews** [comment]
Always :-)

What do we need to do to work with hacktoberfest?

**Comment by gesposito** [comment]
So:

### Here are tips for creating a good Hacktoberfest issue in your project:

- [x] Add a CONTRIBUTING.md file with contribution guidelines to your repo.
- [ ] Choose issues that have a well-defined scope and are self-contained.
- [ ] They should serve as good introductions to the codebase.
- [x] Consider adopting a code of conduct to foster a greater sense of community.

---

- [ ] Apply the label "Hacktoberfest" to issues in your GitHub-hosted project that are ready for new contributors to work on.

**Comment by KyleAMathews** [comment]
@gesposito thanks for the suggestion! Added the label to a bunch of low-hanging fruit issues https://github.com/gatsbyjs/gatsby/labels/Hacktoberfest
