### ISSUE TITLE
[v2] Document how to create a "SEO" component using <StaticQuery>

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#4921]
This is a common problem people run into — it's much more straightforward in v2 with `<StaticQuery>` so let's improve the docs for this.

**Comment by jlengstorf** [comment]
FYI, this is built. I just have to write up the docs.

https://github.com/jlengstorf/marisamorby.com/blob/master/src/components/SEO/SEO.js

**Comment by spences10** [comment]
Hey @jlengstorf do you want me to expand on the documentation you have for this already if I can get it workingnfor my own purposes first?

**Comment by jlengstorf** [comment]
@spences10 Yes! That would be amazing — I definitely have not had time to write it up. 😅

**Comment by DSchau** [comment]
See #9075 for the implementation of this. Can merge when it's merged!
