### ISSUE TITLE
How to use CSS Variables and CSS Modules together, canonically ? 

### ISSUE THREAD

**Issue by fxfactorial** [gatsbyjs/gatsby#4933]
I want to use CSS variables, 

```css
:root {
  --foo-bar: orange;
}
```

But in my CSS modules, I get errors about undefined variables because I assume PostCSS implements its own layer for that. 

I found this plugin, but I am not sure how to integrate it into a gatsby project, guidance appreciated. 

https://github.com/postcss/postcss-custom-properties

**Comment by m-allanson** [comment]
@fxfactorial Does issue https://github.com/gatsbyjs/gatsby/issues/2773 help? If not, can you provide some more details on your setup and the errors you're seeing?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
