### ISSUE TITLE
[gatsby-link] How to debug results?

### ISSUE THREAD

**Issue by thebarty** [gatsbyjs/gatsby#4934]
Hi guys,

any quick tip on how to debug if gatsby-link actually works and to find out WHERE potential latency is created?

I have it installed on my site and things still loads pretty slow on production. So I am wondering how to optimize.

Any tips?

**Comment by pieh** [comment]
You need to make sure that paths passed to links match paths you use to create pages (trailing slash matters).

To debug (check if it actually prefetch resources for linked pages) you can for example open network tab in chrome develope tools and see if gatsby makes requests for linked pages - you should see it trying to fetch `path---<normalized_path>-hash.js` (for example - this is for `docs` path: `path---docs-a0e39f21c11f6a62c5ab.js`)

**Comment by pieh** [comment]
I guess this should be closed earlier - question was answered. Closing it now.
