### ISSUE TITLE
Experiment with jsxtreme-markdown

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#4942]
This is a really cool utility from @mapbox that would allow us to easily interpolate JSX into Markdown. This could open up some awesome possibilities for Gatsby. (Thanks for pointing me to it, @elifitch!)

https://github.com/mapbox/jsxtreme-markdown/

I'm opening this issue to:

1. Remind myself that this exists so I can revisit it later.
2. Invite anyone in the Gatsby community to play with this and see what we can build. 😄

**Comment by jquense** [comment]
I've messed around a bit with this. Ideally we'd integrate into the remark flow directly bt that takes some API changes I haven't gotten around too...https://github.com/jquense/react-widgets/tree/master/www/plugins/gatsby-plugin-jsxtreme-markdown

**Comment by jlengstorf** [comment]
`gatsby-mdx` handles the use cases I had in mind and is under active development by @ChristopherBiscardi, so I'm going to close this.
