### ISSUE TITLE
Add link to signup for the newsletter on the community page

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#4943]

**Comment by ajayns** [comment]
@KyleAMathews I'd like to take this up! Could you guide me to what you refer to as the 'community page' though?

**Comment by KyleAMathews** [comment]
That'd be great! This is the page I was referencing https://www.gatsbyjs.org/docs/community/

**Comment by ajayns** [comment]
Okay, but I can't seem to find "Signup for newsletter" linked anywhere (wherever I expected it to be found, like the homepage)? So shouldn't we add this there as well? 

Also, if we're adding a link, would it be a good idea to include this on the part above the main heading 'Community'? So that users can easily see and access this? @KyleAMathews

**Comment by ajayns** [comment]
Alternative option would be to add this as a part of the **Gatsby News** section, above the twitter heading. @KyleAMathews

**Comment by m-allanson** [comment]
@ajayns There's a newsletter signup form at the bottom of each blog post: https://www.gatsbyjs.org/blog/2018-04-11-trying-out-gatsby-at-work-and-co/

@KyleAMathews Maybe there should be a dedicated newsletter signup page? e.g. gatsbyjs.org/newsletter. Then it's easy to link from any markdown file or external site.

**Comment by KyleAMathews** [comment]
@m-allanson — yeah, like that idea!

**Comment by ajayns** [comment]
Dedicated page would be a good idea, but what content can be put in that separate page? Currently all the content that's required is an Email id form for subscribing to the newsletter.

**Comment by KyleAMathews** [comment]
It should tell people about the newsletter and that they should sign up and
then show the same signup form as on the blog posts.

**Comment by m-allanson** [comment]
It could be a pretty small page, maybe the layout could be something like:

![screen shot 2018-04-17 at 12 12 36](https://user-images.githubusercontent.com/381801/38866399-ace458e8-4238-11e8-8312-547383e41cac.png)

(excuse the low quality drawing 😄)

**Comment by ajayns** [comment]
Looks good, I'll try to PR when I'm free!

**Comment by ajayns** [comment]
@m-allanson @KyleAMathews Sorry guys but I've exams and work coming for the next few weeks and so won't be available much. I still can make small contributions like adding links and so on, so when that work comes up do let me know.

**Comment by m-allanson** [comment]
No problem, thanks for all your contributions already and good luck with the exams!

**Comment by m-allanson** [comment]
Closing this in favour of #6236
