### ISSUE TITLE
Fix createNode documentation for parent field.

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#4944]
Currently, the docs for `createNode` read:

> **parent {string}**
> The ID of the parent’s node. If the node is derived from another node, set that node as the parent. Otherwise it can just be an empty string.

This is incorrect; `parent` must be `null` if there is no parent.

Anyone looking for a really quick first contribution?

**Comment by pieh** [comment]
Fixed with #4944
