### ISSUE TITLE
Improve gatsby-dev docs

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#4946]
Be more specific about how gatsby-dev-cli works. 

Make it clearer that you have the Gatsby repo checked out in one directory, and a test site in another directory. The `gatsby-dev` command should be run in the test site's directory.

This could be demo'd with a gif. Here's an example:

![gatsby-dev-cli-usage](https://user-images.githubusercontent.com/381801/38645411-e12e4656-3ddb-11e8-843f-f4ffb46a4fe9.gif)

Although I had to make it pretty lossy to fit inside GitHub's 6MB limit. Maybe this is better as a video?

@kkemple does something like this do the trick?

This info should be added to one of these docs:

- https://www.gatsbyjs.org/docs/how-to-contribute/#contributing-to-the-repo
- https://www.gatsbyjs.org/packages/gatsby-dev-cli/

**Comment by kkemple** [comment]
I think that gif is plenty clear! 🎉👏

**Comment by kkemple** [comment]
honestly, I think it could be added to both places 🤷‍♂️

**Comment by KyleAMathews** [comment]
Short videos are great! Though we can do it as an MP4 (way way smaller than gifs) since it'll be displayed on the website.

**Comment by AlanFoster** [comment]
@m-allanson +1 for a video. Out of interest - how are you currently recording GIFs/MP4s?

I've been using [licecap](https://www.cockos.com/licecap/) for recording GIFs, and using QuickTime + [HandBrake](https://handbrake.fr/) to generate MP4s - but I'd be interested in knowing your approach :+1:

**Comment by m-allanson** [comment]
Here it is as a video: https://youtu.be/D0SwX1MSuas, although I can put the .mp4 file somewhere if that's more useful.

@AlanFoster I used licecap too! But recently have been using [Giphy Capture](https://giphy.com/apps/giphycapture) for gifs and videos - thanks to @kkemple for the reccommendation. The interface is pretty similar to licecap but it's a bit more polished.

**Comment by lesliecdubs** [comment]
I'm on it!

Unfortunately markdown doesn't allow mp4 embeds and, because the `gatsby-remark-images` option `linkImagesToOriginal` is turned on, there's no way to drop in a YouTube-linked screenshot.

Due to those limitations, I went ahead and dropped in a compressed version of the gif, linked to the YouTube vid, in the "How To Contribute" page. Feel free to counter this approach if you have a better idea!

PR is here: #6632

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
