### ISSUE TITLE
Infinite Scroll

### ISSUE THREAD

**Issue by thekevinbrown** [gatsbyjs/gatsby#4947]
## Description

Unclear how to implement infinite scroll in Gatsby without loading all data for all pages on initial page load.

### Steps to reproduce

The only example I could find was Gatsbygram, but it loads all data, then uses state to show parts of the data. What if we have a large amount of data? How do we load pages and show them?

### Expected result

We should be able to implement infinite scrolling on Gatsby sites.

### Actual result

I'm not sure we can because the components must be bound up to all of their data at build time.

### Environment

* Gatsby version (`npm list gatsby`): gatsby@1.9.248
* gatsby-cli version (`gatsby --version`): 1.1.50
* Node.js version: v8.9.4
* Operating System: OS X 10.13.3

## Question

Has anyone had any success doing this without loading all data with the page?

**Comment by blargity** [comment]
@KyleAMathews that'd be amazing!

**Comment by DylanVann** [comment]
For users with JS disabled you'd want normal pagination. People have come up with a bunch of ways to do this with Gatsby. So you should have a bunch of pages generated anyways. If there was someway to get the url to the json data for those pages then it would be pretty easy to fetch it and merge it in.

**Comment by baobabKoodaa** [comment]
@DylanVann @thekevinbrown The solution is to generate your own JSON that corresponds to the pages created by your pagination. I made a starter and a demo: https://github.com/baobabKoodaa/gatsby-starter-infinite-scroll

**Comment by ggarcia92** [comment]
@baobabKoodaa Your starter is very useful but dosen't solve the problem of @thekevinbrown . Your starter also works with all data and he wants fetch data according to the page, to avoid getting a large amount of data, something like react-infinite-scroll-component but using Gatsby.

**Comment by baobabKoodaa** [comment]
@ggarcia92 You are mistaken. My starter doesn't load all data for all pages on initial page load. On initial page load it only loads the data corresponding to the initial page. As the user scrolls down, it fetches more data as needed. So it solves exactly the problem described by @thekevinbrown .

**Comment by ggarcia92** [comment]
@baobabKoodaa In your `gatsby-node.js` you use a variable `images` that contains all images to display, and @thekevinbrown wants load server data according to the scrolling to avoid a big response data from the server or I understood his issue in wrong way?

**Comment by baobabKoodaa** [comment]
@ggarcia92 In my `gatsby-node.js` there is indeed a variable `images` which contains all images, but it is never sent to the client. It only exists during build when we create pages on the server. When we create pages, each page is only given "one page worth of images", rather than all of the images. So when a client requests a page, they only fetch the data they need for that page. You can easily confirm this yourself by opening the demo with devtools and looking at the contents of the resources which are sent on initial pageload.
