### ISSUE TITLE
[EPIC]gatsby-dev-cli should handle package dependencies

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#4948]
gatsby-dev-cli doesn't copy over package dependencies, which means manually installing those dependencies into your test sites.

Explore how best to fix this or document a work around. 

Can this be fixed with symlinking? Will that mess with yarn / npm's module resolution. What are other ways to handle this.

**Comment by pieh** [comment]
my approach currently is to `npm pack` package when I change dependencies and install resulting tarball in test site (which will handle dependencies) before running `gatsby-dev` - not cleanest and require some manual work but it does the trick

**Comment by m-allanson** [comment]
That sounds good! Would it be possible for `gatsby-dev-cli` to do that automatically?

**Comment by m-allanson** [comment]
Verdaccio is often used for this. This SO answer gives examples of how other project have configured it: https://stackoverflow.com/questions/50206729/how-to-test-an-npm-publish-result-without-actually-publishing-to-npm#50222427

**Comment by m-allanson** [comment]
Related tools: 

- https://github.com/zkochan/package-preview
- https://github.com/whitecolor/yalc

**Comment by m-allanson** [comment]
Related tools: 

- https://github.com/zkochan/package-preview
- https://github.com/whitecolor/yalc
- https://github.com/pnpm/pnpm

**Comment by m-allanson** [comment]
[Done in `gatsby-dev-cli@2.4.13`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-dev-cli/CHANGELOG.md) 🎉
