### ISSUE TITLE
Gatsby cli runs compile over and over again

### ISSUE THREAD

**Issue by tonypig93** [gatsbyjs/gatsby#4951]
## Description

I was following the guide to create pages from md files, but whenever I wrote some code and save 
 the changes, the gatsby cli would throw an warning:

(node:4260) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit

then it ran compile task over and over again, just like this:

 WAIT  Compiling...20:55:05

 DONE  Compiled successfully in 2868ms20:55:08

 WAIT  Compiling...20:55:08

 DONE  Compiled successfully in 2552ms20:55:11

 WAIT  Compiling...20:55:11

 DONE  Compiled successfully in 2593ms20:55:14

 WAIT  Compiling...20:55:14

 DONE  Compiled successfully in 2607ms20:55:17

 WAIT  Compiling...20:55:17

 DONE  Compiled successfully in 2821ms20:55:20

 WAIT  Compiling...20:55:20

### Steps to reproduce

I think there's something wrong with the gatsby-node.js, here's my code:
```
const { createFilePath } = require(`gatsby-source-filesystem`);
const path = require(`path`);

exports.onCreateNode = ({ node, getNode, boundActionCreators }) => {
  const { createNodeField } = boundActionCreators
  if (node.internal.type === `MarkdownRemark`) {
    const slug = createFilePath({ node, getNode, basePath: `md-pages` });
    createNodeField({
      node,
      name: `slug`,
      value: slug,
    });
  }
};

exports.createPages = ({ graphql, boundActionCreators }) => {
  const { createPage } = boundActionCreators
  return new Promise((resolve, reject) => {
    graphql(`
      {
        allMarkdownRemark {
          edges {
            node {
              fields {
                slug
              }
            }
          }
        }
      }
    `).then(result => {
      result.data.allMarkdownRemark.edges.forEach(({ node }) => {
        const _path = node.fields.slug.replace(/README\/?/, '');
        createPage({
          path: _path,
          component: path.resolve(`./src/templates/basic/index.js`),
          context: {
            // Data passed to context is available in page queries as GraphQL variables.
            slug: node.fields.slug,
          },
        })
      })
      resolve()
    })
  })
};
```
### Expected result

What should happen?

### Actual result

What happened.

### Environment

* Gatsby version (`npm list gatsby`): gatsby@1.9.247
* gatsby-cli version (`gatsby --version`): 1.1.50
* Node.js version: 8.7.0
* Operating System: windows 10

### File contents (if changed):

`gatsby-config.js`: 
`package.json`: 
`gatsby-node.js`: 
`gatsby-browser.js`: 
`gatsby-ssr.js`:

**Comment by tsriram** [comment]
I'm not sure, but it could be your code editor that auto saves some file every few seconds which is triggering the compilation. Could you check that?

**Comment by tonypig93** [comment]
@tsriram I'm using vs code, and I didn't install any auto save plugin, it works fine on other projects. The thing is, as long as I remove gatsby-node.js, the cli would go normal with no warning and no endless compilation. Couldn't figure it out.

**Comment by m-allanson** [comment]
Are you able to narrow this down to any part of `gatsby-node.js`? e.g. if you start commenting out lines, when does gatsby cli stop repeating?

**Comment by huy-nguyen** [comment]
I ran into the same annoying errors (infinite recompilation) and I fixed it by removing the `gatsby-plugin-remove-trailing-slashes` plugin. @tonypig93 can you try it to see if that works?

**Comment by tonypig93** [comment]
@huy-nguyen oh, i did install `gatsby-plugin-remove-trailing-slashes`, and everything went fine when I removed it, thanks.
@m-allanson FYI.
