### ISSUE TITLE
Show progress bar for running GraphQL queries

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#496]
Also while at it only run queries once at startup.

Add a verbose mode perhaps too so show queries being run per file.

**Comment by priyaclerisy** [comment]
Hi
I have started a project in Gatsby. I want to pass dynamic parameters in url for a particular page like
localhost:8000/docs/param1, localhost:8000/docs/param2
where docs is a folder in pages folder and param1, param2 are the dynamic parameters.
I want to send these dynamic parameter to a index.md file created and called as default while calling above url. but these urls are not working as according to Gatsby these parameters should be pages in docs folder. So, is there any way to modify routing or sending parameters to a common page in Gatsby.
Please help me.
Thanks
