### ISSUE TITLE
Gatsby Drupal Taxonomy workflow

### ISSUE THREAD

**Issue by cf73** [gatsbyjs/gatsby#4961]
mistakenly started thread in comment below -- see below : )

**Comment by cf73** [comment]
@KyleAMathews 
I am enjoying developing a Gatsby site using the drupal-source plugin. However, it is not clear to me how, or if, Gatsby supports Drupal's taxonomy relationships? 
e.g. if I have a taxonomical structure THEME > SUBTHEMES > CONTENT NODES, in Drupal this is set up as two taxonomy 'terms' (theme and subtheme), and then multiple different 'content types' for the content nodes. In Gatsby I am able to pull in any theme or subtheme or content via GraphQL, but cannot see a way to create relationships between them, e.g. "show me all the subthemes in this theme", or "all the content in this subtheme". Does Gatsby understand the parent/child structure implicit in Drupal's taxonomy > content types structure?
Sketch attached showing desired template.
![template](https://user-images.githubusercontent.com/25471024/38693523-25315090-3e55-11e8-885b-b8335707c108.JPG)

**Comment by cf73** [comment]
@pieh You might also want to take a look at this question?

**Comment by dubcanada** [comment]
If I understand you want to get all nodes that have a certain taxonomy term? So you could get all content with X taxonomy term.

Is that correct?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by tony-gutierrez** [comment]
The drupal source plugin will get the taxonomies, but it fails to create parent/child relationships.
