### ISSUE TITLE
internal, absolute links broken in documentation

### ISSUE THREAD

**Issue by Strangehill** [gatsbyjs/gatsby#4964]
Links such as this one are broken.

at /docs/blog/2018-01-22-getting-started-gatsby-and-wordpress/index.md: 

`([Source](https://www.gatsbyjs.org/docs/api-specification/#concepts)).`
leads to
`https://www.gatsbyjs.org/blog/2018-01-22-getting-started-gatsby-and-wordpress/https://www.gatsbyjs.org/docs/api-specification/`

I made a couple of these links relative, and that fixes them, but perhaps this is a configuration issue?

**Comment by m-allanson** [comment]
Thanks @Strangehill! It looks like there's a [TODO for this in `gatsby-plugin-catch-links`](https://github.com/gatsbyjs/gatsby/blob/462e3b5b57c444e8d6acd3321422e29c06d69674/packages/gatsby-plugin-catch-links/src/catch-links.js#L72).

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
