### ISSUE TITLE
gatsby-plugin-manifest should use pathPrefix for 'start_url'

### ISSUE THREAD

**Issue by ChrisBoon** [gatsbyjs/gatsby#4966]
Gatsby-plugin-manifest allows you to add your preferred 'start_url' via gatsby-config.js. However when it is used in the plugin it doesn't use withPrefix to add the prefix. 
This means if I want to build both with and without prefix I have to manually change the config file each time.

In gatsby-plugin-manifest / src/ gatsby-node.js could we add a check for __PREFIX_PATHS__ and amend the 'start_url' to include it if __PATH_PREFIX__ if so?

**Comment by KyleAMathews** [comment]
@moonmeister thoughts?

**Comment by moonmeister** [comment]
I'm not sure I entirely understand what your asking. Can you give an example? That said, i think the end result is you want the plug-in to automate some config changes. Once I understand what you're asking I can make a better assessment. My initial opinion is that the plug-in config is designed to become the manifest contents. It saves a lot of code and doesn't require us to keep up on every spec chance. This means no automation. 

But, I'm open to better understanding what you're asking for before I throw my final opinion into the ring.

**Comment by ChrisBoon** [comment]
Let's say we want the 'start_url' to simply point to the root of the site. We would just add `start_url: '/'` in the manifest. This works if your site is hosted at the root of a URL and you just run 'gatsby build'. Eg if I am hosting a Gatsby built site at 'website.com' it will work fine.

However if I want to host my site at a subdirectory (either because this is simply part of a larger site, or as in my case, because I want to host it on github-pages) I have change the manifest to `start_url: '/my-subdirectory-name/'`. 

This is true even when I build with the flag `--prefix-paths`, whereas all other links in the site would automatically pick up on the pathPrefix value in 'gatsby-config.js'.

It isn't a huge problem if you always host at a subdomain, but if you want to be able to do either at will, you're stuck. 

In my example I want to use the gh-pages cli to run `"deploy": "gatsby build --prefix-paths && gh-pages -d public"` to host preview builds on GitHub whilst also using Netlify CI hooks to run `"build": "gatsby build"` whenever I update the master branch.

It also just adds another thing to remember if you change subdomains - most people will expect to have to change just one thing - the pathPrefix value in gatsby-config.js.

**Comment by moonmeister** [comment]
@ChrisBoon Okay, this makes a lot more sense. thanks for the explanation. I think this is a reasonable request. 

@KyleAMathews seems like this should be done "automatically" with webpack, is there some reason webpack wouldn't catch this and we need to implement this manually? My ignorance on webpack is vast so yeah...

I probably won't have time to implement this, and not sure where to start. PR is welcome.

**Comment by ChrisBoon** [comment]
Ugh, forget all this. I just realized something obvious. There's no need to fix root-relative URLs, when we can just use relative URLs. 

The start_url value when relative is relative to the mainfest.json location, not the page you call it on.
So if i set the start_url to `'.'` it will be the root of my project regardless of whether it is a subdirectory or not. I'm not able to think of a situation where a user would _need_ to declare a root relative URL given the manifest.json file sits at the root anyway.

Sorry for wasting your time thinking about this. Maybe worth adding a note the docs to call this out for people like me who are dumb enough to overlook this :)

**Comment by moonmeister** [comment]
@ChrisBoon haha. Good point. Didn't think about that. Good thinking.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by rwilson-releaseapp** [comment]
> The start_url value when relative is relative to the mainfest.json location, not the page you call it on.
> So if i set the start_url to `'.'` it will be the root of my project regardless of whether it is a subdirectory or not. I'm not able to think of a situation where a user would _need_ to declare a root relative URL given the manifest.json file sits at the root anyway.

This never actually worked for me, and if anyone finds this issue like I did in a Google search, here is how I fixed it:

In `gatsby-config.js`, (recommended to use `dotenv` to read environment variables for this) during your build pipeline you will substitute variables in your configuration string templates. Feel free to change the environment variables to your liking:

```javascript
require('dotenv').config();
...
module.exports = {
    siteMetadata: {
      siteUrl: `${process.env.SITE_URL || "example.com"}`,
      pathPrefix: `${process.env.PATH_PREFIX || "/"}`,
      plugins: [
        {
          options: {
            start_url: `${process.env.PATH_PREFIX || "/"}`,
            ...
          }
        }
      ...
    }
}
