### ISSUE TITLE
Localization : Multiple locales with different Style

### ISSUE THREAD

**Issue by spatrame** [gatsbyjs/gatsby#4968]
I am creating a website with two different locales (say en-US and es-US). Both will be having small variation in the CSS. I wants to have separate CSS files to be generated for each locale. 

**Challenges:** 
1. I will be using same reactjs component/page templates.
2. Both locale will be having same className, but its style will be different. (ex: color in en-US is red and in es-US is blue)

**Problem:**
1. When I build the project, it generate single css file, and both locale it will consider one color.

**Comment by pieh** [comment]
If you are using css and not any css in js variant you can use BEM method and set class modifiers with language being your modifier: 
```js
className={`button--${locale}`}
```
and in css declare
```css
.button--en-us {
  color: red;
}
.button--other-locale {
  color: blue;
}
```
