### ISSUE TITLE
GA Plugin and GDPR

### ISSUE THREAD

**Issue by kbariotis** [gatsbyjs/gatsby#4976]
## Description

Google's new [EU user consent policy](https://www.google.com/about/company/consentstaging.html) states that Google's products, such as Google Analytics must have user's consent in order to work in a page. That means that a website must take the user's consent and then enable the Google Analytics plugin. With that in mind, I would like to see some sort of a toggle to enable/disable the Gatsby Google Analytics plugin on demand.

### Expected result

I would like to be able to have Google Analytics plugin disabled by default. Then ask the user's consent and only then enable it.

Here are some references on GA tracking code:

1) https://developers.google.com/analytics/devguides/collection/gtagjs/user-opt-out
2) https://developers.google.com/analytics/devguides/collection/gtagjs/#disable_page_view_tracking

**Comment by sebastienfi** [comment]
To know if the user is browsing from EU, we'd have to use an IP Geolocation service. I don't know any that's free.
As an easy workaround, we could detect the timezone of the user and from there extrapolate it's location. 
@kbariotis would you like to submit a PR doing that ?

**Comment by kbariotis** [comment]
No @sebastienfi I don't think this is Gatsby's responsibility at all. This must be left at the owner's choice. Gatsby should just give control to the owner whether the plugin is enabled or not and allow to enable it at run time, rather than built time.

**Comment by jurosh** [comment]
Btw. using google analytics is OK (even in Europe) if you anonymize IPs and also disable cross session (bad) cookies.

With this config tracking should be fine:
```
gtag('config', 'UA-...', {
      'anonymize_ip': true,
      'cookie_expires': 0
  });
```
Ofc. you loose cross-session user tracking feature of analytics, but it might be good for many developers who jsut want to do basic tracking and don't care about GDPR.

Currently plugin allows to anonymize IP, but doesn't allow (cannot see option) to enable session only cookies - `cookie_expires`.

As I understand (don't take as lawyer advice) whole GDPR (no consent) compliant code might be:
```
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-XYZ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-XYZ', {
      'anonymize_ip': true,
      'cookie_expires': 0
  });
</script>
```

**Comment by discordianfish** [comment]
@jurosh Thanks, that's very helpful! Looks like cokies_expires is now also available as `cookieExpires` in the plugin too: https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-google-analytics#create-only-fields

**Comment by mmmoli** [comment]
I published this a couple months back for GDPR compliance:
https://www.gatsbyjs.org/packages/gatsby-plugin-cookiehub/

Cookiehub looked way nicer than tarteaucitron.

**Comment by bonakor** [comment]
Yes, it does, but it's not as customizable as Tarteaucitron :(
And I needed some services other than GA, that Cookiehub doesn't support! But I tried your plugin when I started working on my project and it worked as expected :)

**Comment by lookoutwehave** [comment]
> https://www.gatsbyjs.org/packages/gatsby-plugin-cookiehub/

I can't seem to find the widget ID on cookie hub, would you mind telling me where to look for it?

**Comment by lookoutwehave** [comment]
> I published this a couple months back for GDPR compliance:
> https://www.gatsbyjs.org/packages/gatsby-plugin-cookiehub/
> 
> Cookiehub looked way nicer than tarteaucitron.

I can't seem to find the widget ID on cookie hub, would you mind telling me where to look for it?
