### ISSUE TITLE
Improve caching setup on offiicial site

### ISSUE THREAD

**Issue by sivakumar-kailasam** [gatsbyjs/gatsby#4978]
## Description

The caching setup on the official site doesn't seem to be optimised to leverage cache expiry headers to account for browsers without service workers. Although it might not be noticable by most users, it's probably good to set them so that everyone gets the best possible user experience.

### Steps to reproduce

See https://www.webpagetest.org/performance_optimization.php?test=180414_0X_9e33d65d8b02c6ac171bb98c8c2de9b5&run=3#first_byte_time

### Expected result

Far fetched cache expiry time like a year along with immutable cache headers could be set.

### Actual result

No max-age or expires is set on fingerprinted static assets.

### Environment
https://www.gatsbyjs.org/blog/

**Comment by KyleAMathews** [comment]
We'll do this in v2 https://www.gatsbyjs.org/docs/caching/
