### ISSUE TITLE
Upgrade gatsby-plugin-react-next to React 16.3

### ISSUE THREAD

**Issue by alvinsight** [gatsbyjs/gatsby#4980]
Hi everyone!

## Description

As I'm sure you're well aware, [React 16.3](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) has introduced big changes to the life-cycle of components and the way we write them, deprecating a few methods along the way.

 *A lot* of the code in the official React docs won't work in Gatsby, and this is bound to confuse a lot of beginners, and will probably bring up a lot of questions to you, the maintainers, so it's definitely a worthwhile upgrade in my opinion.

I'm not sure how much work this would require internally, but ideally we'd want `gatsby-plugin-react-next` to be upgraded to React 16.3, or even the main Gatsby package, if possible.

### Expected result

`gatsby-plugin-react-next` should use React 16.3

### Actual result

`gatsby-plugin-react-next` currently uses React 16.0

**Comment by pieh** [comment]
Check https://github.com/gatsbyjs/gatsby/issues/4800 - this plugin does depend on latest of v16 release - so currently it depend on 16.3

**Comment by m-allanson** [comment]
Note that the next major version of Gatsby should use React 16 by default 🎉

**Comment by alvinsight** [comment]
Hi,
Right, I looked at the `package.json` version and got confused, I should have paid attention to the `^` sign.
Thanks for this!

**Comment by franva** [comment]
@m-allanson  Hi there, just wonder how long will it take for the Gatsby V2 to be released??

**Comment by m-allanson** [comment]
Hey @franva, it's actively being work on but there's no timeline. You can track progress over at https://github.com/gatsbyjs/gatsby/projects/2
