### ISSUE TITLE
question - incremental builds support

### ISSUE THREAD

**Issue by ekdev2** [gatsbyjs/gatsby#4981]
is it on your guys' radar to support incremental builds in upcoming versions? If one content page is modified, rebuild only that page. Awesome project by the way!

**Comment by jquense** [comment]
hey there, Gatsby uses webpack under the hood so for builds we get incremental builds automatically as you change code!

**Comment by LeKoArts** [comment]
@jquense I don‘t think that‘s the answer he‘s looking for.
He‘s probably asking if you could just build one page and not the whole page when you change something.
