### ISSUE TITLE
Validation errors with gatsby-source-filesystem@1.5.31

### ISSUE THREAD

**Issue by tschaub** [gatsbyjs/gatsby#4985]
## Description

After upgrading to gatsby-source-filesystem@1.5.31, I'm seeing this validation issue:
```
The new node didn't pass validation
ValidationError: child "internal" fails because ["description" is not allowed]
```

### Steps to reproduce

`npm install gatsby@1.9.249 gatsby-source-filesystem@1.5.31`

In `gatsby-config.js`:
```js
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'src',
        path: `${__dirname}/src/`
      }
    }
  ]
};
```

Run `npx gatsby develop` with a few files in the `src` directory.

### Expected result

No validation errors.

### Actual result

```
The new node didn't pass validation
ValidationError: child "internal" fails because ["description" is not allowed]
{ id: '/path/to/gatsby-site/src/pages/index.js absPath of file',
  children: [],
  parent: '___SOURCE___',
  internal: 
   { contentDigest: '19d579cf1c21a7306f3ec59289ee8382',
     mediaType: 'application/javascript',
     type: 'File',
     description: 'File "src/pages/index.js"',
     owner: 'gatsby-source-filesystem' },
  sourceInstanceName: 'src',
  absolutePath: '/path/to/gatsby-site/src/pages/index.js',
  relativePath: 'pages/index.js',
  extension: 'js',
  // etc
```

Downgrading to gatsby-source-filesystem@1.5.29 resolves the issue.

### Environment

* Gatsby version: 1.9.249
* gatsby-cli version: 1.9.249
* Node.js version: 8.9.1
* Operating System: macOS 10.13.4

**Comment by tschaub** [comment]
I see the validation change in https://github.com/gatsbyjs/gatsby/pull/3905/files#diff-bd517ec758aa05f3e6e1c34b15f65394R60

Looks like gatsby-source-filesystem@1.5.31 depends on gatsby@1.9.250.

**Comment by tschaub** [comment]
Confirmed that upgrading to gatsby@1.9.250 fixes the issue.

**Comment by pieh** [comment]
I'll close this issue as problem was resolved. If anyone will have same error, solution is presented here.

**Comment by KyleAMathews** [comment]
We should bump the peerDependency for gatsby to when we added description
support

**Comment by kodepareek** [comment]
Worked for me. Just upgraded gatsby to no more errors.

**Comment by thebarty** [comment]
As a reference and no brainer: `npm update gatsby` fixed it for me

**Comment by sundarrajanm** [comment]
> As a reference and no brainer: `npm update gatsby` fixed it for me

Updating gatsby also fixed the below error, seen in the recent versions:

```
 ERROR #11467 

The new node didn't pass validation: "internal.contentFilePath" is not allowed

Failing node:

{
    "id": "89436a88-d175-5f56-9289-3cd83877cf7b",
    "children": [],
    "parent": "3cd243dd-54c3-529c-8659-e5d84e9e70d5",
    "internal": {
        "type": "Mdx",
        "contentDigest": "a6c6b13aceb209c25d029033a9e1f7f9",
        "contentFilePath": "/Users/.../blog/my-first-post.mdx",
        "owner": "gatsby-plugin-mdx"
    },
    "body": "\nThis is my first blog post! Isn't it *great*?\nSome of my **favorite** things are:\n* Petting dogs\n* Singing\n* Eating potato-based foods\n",
    "frontmatter": {
        "title": "My First Post",
        "date": "2022-06-01",
        "slug": "another-post"
    }
}

```

**Comment by raonsol** [comment]
> > As a reference and no brainer: `npm update gatsby` fixed it for me
> 
> Updating gatsby also fixed the below error, seen in the recent versions:
> 
> ```
>  ERROR #11467 
> 
> The new node didn't pass validation: "internal.contentFilePath" is not allowed
> 
> Failing node:
> 
> {
>     "id": "89436a88-d175-5f56-9289-3cd83877cf7b",
>     "children": [],
>     "parent": "3cd243dd-54c3-529c-8659-e5d84e9e70d5",
>     "internal": {
>         "type": "Mdx",
>         "contentDigest": "a6c6b13aceb209c25d029033a9e1f7f9",
>         "contentFilePath": "/Users/.../blog/my-first-post.mdx",
>         "owner": "gatsby-plugin-mdx"
>     },
>     "body": "\nThis is my first blog post! Isn't it *great*?\nSome of my **favorite** things are:\n* Petting dogs\n* Singing\n* Eating potato-based foods\n",
>     "frontmatter": {
>         "title": "My First Post",
>         "date": "2022-06-01",
>         "slug": "another-post"
>     }
> }
> ```

Much appreciated. I was digging for this error for several days.
