### ISSUE TITLE
Prism JS not running when compiling Markdown manually (I think)

### ISSUE THREAD

**Issue by mikecrittenden** [gatsbyjs/gatsby#4988]
## Description

PrismJS doesn't seem to be getting added to my page. I added the theme and the CSS for that is there, but the JS itself doesn't exist so none of the highlighting happens.

I think it may be because I followed [this guide](https://blog.airtable.com/build-your-own-custom-blog-cms-with-airtable-and-gatsbyjs/) which tells me to compile the markdown like so:

```
<div dangerouslySetInnerHTML={{
        __html: unified()
            .use(markdown)
            .use(html)
            .processSync(post.Body)
    }}
/>
```

Maybe doing it that way prevents remark from adding Prism to the page?

### Steps to reproduce

You could clone [this repo](https://github.com/mikecrittenden/personal-site) and run `npm install` then `gatsby develop` and then visit `http://localhost:8000/ramblings/exporting-importing-large-drupal-databases` if necessary, I suppose.

### Expected result

Prism should be highlighting code blocks.

### Actual result

Code blocks just get displayed as regular old `<pre>` tags.

### Environment

* Gatsby version (`npm list gatsby`): 1.9.250
* gatsby-cli version (`gatsby --version`): 1.1.50
* Node.js version: 9.3.0
* Operating System: macOS High Sierra

### File contents (if changed):

**All of these are available at the repo posted above, if needed**

`gatsby-config.js`: 
`package.json`: 
`gatsby-node.js`: 
`gatsby-browser.js`: 
`gatsby-ssr.js`:

**Comment by mikecrittenden** [comment]
Looks like the actual fix is to make the Airtable source plugin allow for something like this: https://www.gatsbyjs.org/packages/gatsby-source-mongodb/?=mongo#mapping-mediatype-feature

Yeah?

**Comment by KyleAMathews** [comment]
Have you looked at using https://www.gatsbyjs.org/packages/gatsby-remark-prismjs/?=prismjs

**Comment by KyleAMathews** [comment]
Ah yeah! Adding mapping like that would be ideal as then gatsby-remark-prismjs would just work.

**Comment by mikecrittenden** [comment]
@KyleAMathews yes I believe I've followed all of the directions on that page. I think the question is basically just "how can I make remark plugins run on my content if I'm transforming markdown to HTML manually"? But yeah, just fixing the Airtable plugin seems like it would solve this.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
