### ISSUE TITLE
Locally builds and runs fine but fails in Netlify

### ISSUE THREAD

**Issue by vickylance** [gatsbyjs/gatsby#4989]
## Description

`gatsby build` runs fine locally but fails in Netlify.

### Steps to reproduce

clone this repo -> `git clone https://github.com/bradtraversy/gatsby_crash_course`
cd into that folder `cd gatsby_crash_course`
run `npm run build`
cd into public folder `cd public`
run `http-server -p 3000`
go to `http://localhost:3000`

it will work fine but if you deploy that to netlify it fails with an error

### Expected result

it should build fine in netlify as it builds in locally

### Actual result

It fails in netlify with 
`GraphQLError: Cannot query field "allMarkdownRemark" on type "RootQueryType".`
error in netlify

### Environment

* Gatsby version (` gatsby@1.9.247`):
* gatsby-cli version (` 1.1.50`):
* Node.js version: v8.9.1
* Operating System: Windows 10

### File contents (if changed):

`package.json`: 
```
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "gatsby": "^1.9.247",
    "gatsby-link": "^1.6.40",
    "gatsby-plugin-catch-links": "^1.0.19",
    "gatsby-plugin-react-helmet": "^2.0.10",
    "gatsby-source-filesystem": "^1.5.29",
    "gatsby-transformer-remark": "^1.7.39",
    "react-helmet": "^5.2.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write 'src/**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "prettier": "^1.11.1"
  }
}
```
`gatsby-node.js`: 
```
const path = require('path')

exports.createPages = ({ boundActionCreators, graphql }) => {
  const { createPage } = boundActionCreators

  const postTemplate = path.resolve('src/templates/blog-post.js')

  return graphql(`
    {
      allMarkdownRemark {
        edges {
          node {
            html
            id
            frontmatter {
              path
              title
              date
              author
            }
          }
        }
      }
    }
  `).then(res => {
    if (res.errors) {
      return Promise.reject(res.errors)
    }
    res.data.allMarkdownRemark.edges.forEach(({ node }) => {
      createPage({
        path: node.frontmatter.path,
        component: postTemplate,
      })
    })
  })
}
```

**Comment by noeleont** [comment]
I experience similar issues, it seems that gatsby-source-filesystem is broken in 1.5.31 try to set it explicitly to 1.5.30

**Comment by pieh** [comment]
It doesn't seem to be same issue as #4990 . 

Are there any other errors or warnings before error you reported? Gist with full output could be helpful

**Comment by vickylance** [comment]
I can close this issue if no further clarification regarding the bug in v1.5.31 of gatsby-source-filesystem is needed. @pieh

**Comment by pieh** [comment]
Updating `gatsby` to at least 1.9.250 (and better to 1.9.251) and `gatsby-source-filesystem` to 1.5.32 should fix the issue. It turned out to be exact same issue as #4990. We can leave this open until you confirm that updating packages fixes the issue.

**Comment by vickylance** [comment]
@pieh I just updated my package.json to `gatsby` `v1.9.251` and `gatsby-source-filesystem` to `v1.5.32` and uploaded to netlify and I can confirm it is working :)
