### ISSUE TITLE
Accessing {css} from other components

### ISSUE THREAD

**Issue by marcelosomers** [gatsbyjs/gatsby#499]
Loving Gatsby so far! Thanks for all the hard work poured into this.

I'm trying to take the Inline CSS that's generated [as in the docs](https://github.com/gatsbyjs/gatsby#inline-css) and use it in another React component. I've got some code like this:

``` js
class RandomComponent extends React.Component {
  render() {
    let css
    if (process.env.NODE_ENV === 'production') {
      css = <style dangerouslySetInnerHTML={{ __html: require('!raw!./public/styles.css') }} />
    }

    console.log(css)

    return (
      <p>Nothing here yet</p>
    )
  }
}
```

But it simply spits out `undefined`. I'm still somewhat new to the whole React/Webpack loading ecosystem, so maybe I'm thinking of this wrong? Is there some way for that component to get access to the CSS that's being generated and injected in `html.js`? Am I missing something?

In reality what I'm trying to accomplish is to get a string of the generated CSS to pass into an iframe - it's for rendering a component within an iframe in a Pattern Library. The iframe library can be passed a string to add to the `<head>` of the iframe.

Thanks so much!

**Comment by KyleAMathews** [comment]
The `/public/styles.css` file is only generated on build which is probably why you're getting `undefined`.

Could each component in the iframe just require its own styles? E.g.

```js
// A react component

import React from 'react'
import './my-styles'

export default const (props) => (
  <div className="a-class-name>
  </div>
)
```

**Comment by marcelosomers** [comment]
Tried it and it doesn't seem to work given the [other library I'm using](https://github.com/ryanseddon/react-frame-component) (not Gatsby's issue).

What I'm curious though is how can Gatsby can compile and inject the CSS on my `html.js` template, but then I can't access that CSS anywhere else?

**Comment by KyleAMathews** [comment]
During development, it uses the [style-loader](https://github.com/webpack/style-loader) to inject css.
