### ISSUE TITLE
gatsby-source-filesystem@1.5.31 is broken

### ISSUE THREAD

**Issue by noeleont** [gatsbyjs/gatsby#4990]
## Description

Using gatsby-source-filesystem version results in 

``
The new node didn't pass validation                                                                 
ValidationError: child "internal" fails because ["description" is not allowed] 
``

### Steps to reproduce

Update any project to the new gatsby-source-filesystem and see it yourself. 

Clear steps describing how to reproduce the issue.

### Expected result

What should happen?

### Actual result

What happened.

### Environment

* Gatsby version: gatsby@1.9.244
* gatsby-cli version (`gatsby --version`): 1.9.250
* Node.js version: v9.8.0
* Operating System: macOs 10.12.6

### File contents (if changed):

`gatsby-config.js`: 

```
module.exports = {
  plugins: [
    'gatsby-plugin-react-helmet',
    {
      resolve: `gatsby-source-filesystem`,
        options: {
          name: `pages`,
          path: `${__dirname}/src/pages/`,
        },
      },
    {
      resolve: 'gatsby-plugin-typography',
      options: {
        pathToConfigModule: 'src/utils/typography.js',
      },
    },
  ],
};
```
`package.json`: 

```
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "gatsby": "^1.9.241",
    "gatsby-link": "^1.6.39",
    "gatsby-plugin-react-helmet": "^2.0.8",
    "gatsby-plugin-typography": "^1.7.18",
    "gatsby-source-filesystem": "1.5.31",
    "react-helmet": "^5.2.0",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write 'src/**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "prettier": "^1.11.1"
  }
}
```

**Comment by pieh** [comment]
Check https://github.com/gatsbyjs/gatsby/issues/4985 , updating `gatsby` package to latest should fix that. I will create PR adding peerDependency do `gatsby-source-filesystem` shortly as suggested in that issue.
