### ISSUE TITLE
[v2] enhancedNodeCacheId collisions

### ISSUE THREAD

**Issue by ptb** [gatsbyjs/gatsby#4992]
I've uncovered an issue (that granted most people wouldn't encounter), where duplicate files create identical `cacheKey`s. In my case, I was just duplicating a single file several times to have a couple files to work with. Since they're all identical, they all had the same contentDigest and thus cacheKey.

My suggestion would be to change `args` to` node.id` in creating the cacheKey:
https://github.com/gatsbyjs/gatsby/blob/v2/packages/gatsby/src/schema/run-sift.js#L13

**Comment by ptb** [comment]
Normally, I wouldn't bother with such an esoteric bug, but it took me a couple hours to figure out where this issue was coming from. :)

**Comment by pieh** [comment]
At this point we don't look into specifics of nodes. But same `contentDigest` can possibly cause problems in different areas so maybe it would be worth to update how we generate `contentDigest` for file nodes? F.e. take path into account there?

**Comment by pieh** [comment]
For files we use `md5-file` package that only cares about content of file and not its name or any other metadata:  
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-filesystem/src/create-file-node.js#L45

**Comment by KyleAMathews** [comment]
Hmmm ok, that's the bug then there. Happy to take a PR for this. I'll add this to the v2 project to make sure we fix this soon-ish.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by KyleAMathews** [comment]
Oh actually, we do still want to do this.
