### ISSUE TITLE
gatsby-plugin-react-next bumps react version but fails to bump react-dom version

### ISSUE THREAD

**Issue by mvasin** [gatsbyjs/gatsby#4995]
## Description
I want to use `<React.Fragment>` , so I added `gatsby-plugin-react-next` to bump the React version. That works fine - `{React.version}` displays 16.3.1 and `<React.Fragment>` works.

But if along with it I add `"react": "^16.3.1"` to my project's `package.json`,
1) `{React.version}` is still displayed as 16.3.1,
2) `<React.Fragment>` gets broken (`Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: symbol.`)

The same problem appears if I add  `"react": "^16.3.1"` to `package.json` and do not add `gatsby-plugin-react-next` to `package.json` and `gatsby-config.js` (`{React.version}` is fresh but fragment is broken).

### Steps to reproduce
Copy, paste and run this code in a terminal:

```
npx gatsby new test-fragment && cd test-fragment &&
yarn add react gatsby-plugin-react-next &&

echo "module.exports = {
  siteMetadata: {
    title: 'Gatsby Default Starter',
  },
  plugins: ['gatsby-plugin-react-helmet', 'gatsby-plugin-react-next'],
}" > gatsby-config.js &&

echo "import React from 'react'

const FragmentUnderTest = () => (
  <React.Fragment>
    <p>1</p>
    <p>2</p>
  </React.Fragment>
)

export default () => <div><FragmentUnderTest /></div>" > src/layouts/index.js &&
rm gatsby-node.js gatsby-browser.js gatsby-ssr.js &&
gatsby develop
```

Notice that if you `yarn remove react`, `<React.Fragment>` starts to work. And if you `yarn add react` back, `<React.Fragment>` breaks.

### Expected result
`<React.Fragment>` should work at all times if `React.version` is reported as 16.3.1.

### Actual result
It breaks if React is explicitly added to project's `package.json`.

### Environment

* Gatsby version (`npm list gatsby`): `1.9.250`
* gatsby-cli version (`gatsby --version`): `1.1.50`
* Node.js version: `v8.9.4`
* Operating System: macOS 10.13.4.

### File contents (if changed):
`gatsby-config.js`: 
```
module.exports = {
  siteMetadata: {
    title: 'Gatsby Default Starter',
  },
  plugins: ['gatsby-plugin-react-helmet', 'gatsby-plugin-react-next'],
}
```

`package.json`: 
```
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "gatsby": "^1.9.247",
    "gatsby-link": "^1.6.40",
    "gatsby-plugin-react-helmet": "^2.0.10",
    "gatsby-plugin-react-next": "^1.0.11",
    "react": "^16.3.1",
    "react-helmet": "^5.2.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write 'src/**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "prettier": "^1.12.0"
  }
}
```

`gatsby-node.js`, `gatsby-browser.js`, `gatsby-ssr.js`:  absent.

**Comment by m-allanson** [comment]
Thanks for the detailed report @mvasin. If you're specifically adding `react` to your `package.json`, you also need to add `react-dom`.

**Comment by m-allanson** [comment]
BTW your code snippet for creating a test site in one command is great - it made it very straightforward to investigate your issue. Thanks :)

**Comment by mvasin** [comment]
Thanks for the answer, @m-allanson! I'm glad the snippet helped.

Indeed, `yarn add react-dom` fixes the issue.

But I'm still curious: if `gatsby-plugin-react-next` adds both current `react` and `react-dom`, why presence of `react` and absence of `react-dom` in a project's `composer.json` breaks stuff. Thanks to `gatsby-plugin-react-next` both should be there anyway.

**Comment by mvasin** [comment]
@m-allanson if so, it looks more like a bug then a question.

**Comment by mvasin** [comment]
Here's one more perspective: install the latest `gatsby` and `gatsby-plugin-react-next` with this single command (copy and paste to terminal):

```
npx gatsby new test-versions && cd test-versions &&
yarn add react gatsby-plugin-react-next &&

echo "module.exports = {
  siteMetadata: {
    title: 'Gatsby Default Starter',
  },
  plugins: ['gatsby-plugin-react-helmet', 'gatsby-plugin-react-next'],
}" > gatsby-config.js &&

echo "import React from 'react'
import ReactDOM from 'react-dom'

const Versions = () => (
  <div>
    <p>React version: {React.version}</p>
    <p>React DOM version: {ReactDOM.version}</p>
  </div>
)

export default () => <Versions />" > src/layouts/index.js &&
gatsby develop
```

and observe the output in a browser:
```
React version: 16.3.2
React DOM version: 15.6.2
```

**Comment by m-allanson** [comment]
> why presence of `react` and absence of `react-dom` in a project's `package.json` breaks stuff. Thanks to `gatsby-plugin-react-next` both should be in node_modules anyway.

You shouldn't need to install `gatsby-plugin-react-next` and `react`. Interestingly if you swap `yarn` for `npm` in your newest example, `gatsby develop` will fail .

It looks like node's module resolution gets confused when you add `gatsby-plugin-react-next` _and_ `react`. With these dependencies:
```
gatsby-plugin-react-next@1.0.11
gatsby@1.9.250
react@16.3.2
```

`yarn list --pattern react` will show:
```
├─ gatsby-plugin-react-next@1.0.11
│  └─ react-dom@16.3.2
├─ gatsby@1.9.250
│  └─ react@15.6.2
├─ react-dom@15.6.2
├─ react@16.3.2
```

If you install `gatsby-plugin-react-next` without adding `react`, then `yarn list --pattern react` will show something like:
```
├─ gatsby-plugin-react-next@1.0.11
│  ├─ react-dom@16.3.2
│  └─ react@16.3.2
├─ react-dom@15.6.2
├─ react@15.6.2
```
and version 16 of React and ReactDOM are used when you import React in your modules ([example repo](https://github.com/m-allanson/gatsby-test-react-versions)).

You don't need to install `gatsby-plugin-react-next` _and_ `react`, but if you do, you need to also install `react-dom` to prevent the already 

I'm going to close this as I don't think it's an issue with Gatsby.

**Comment by mvasin** [comment]
That's a fake alarm indeed 😬
I didn't pay attention that `react` crept into `yarn add` in the last snippets, I intended to take it away.

I confirm that there is no issue. @m-allanson Thanks a lot for clarification!

**Comment by m-allanson** [comment]
No problem!
