### ISSUE TITLE
[www] Search results don't always show

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#4997]
## Description

Based on investigation from @shannonbux and @tsriram. It seems that clicking to select a search result does not remove focus from the search input, which can prevent the search result panel from re-opening when re-focussing the search input.

### Steps to reproduce

- Go to gatsbyjs.org and type a query into the search box.
- Click on a result to navigate to another page
- Click back onto the search input
- See that search results panel does not open

Note that clicking anywhere else on the page, then clicking back to the search input _does_ bring up the results panel.

![apr-16-2018 12-35-03](https://user-images.githubusercontent.com/381801/38806934-d3c93d50-4172-11e8-88ac-a997120f1087.gif)

### Expected result

The search results panel should re-open.

### Actual result

The search results panel does not re-open. 

Refs #4561

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
