### ISSUE TITLE
Using other webpack loaders

### ISSUE THREAD

**Issue by tamagokun** [gatsbyjs/gatsby#50]
I'm trying to use stylus and just prepend the loader when requiring the file since there's no way to alter the webpack config:

```javascript
require('!css!stylus!./css/main.styl')
```

but it appears gatsby only searches its own `node_modules` rather than node_modules of the project itself. Any way around this?

This also brings up a good question about implementing a way to extend the webpack config with other plugins and things.

**Comment by KyleAMathews** [comment]
Hmmm... yeah this line needs fixed https://github.com/gatsbyjs/gatsby/blob/efd87b45e60f7118ff1fda07fd8725252cbfe391/lib/utils/webpack.config.coffee#L193

Let me add `node_modules` there real quick so you can add your own loaders.

Modifying/extending the webpack config is in the plans. I'm going to post an RFC hopefully this week addressing that problem plus a few other things I want fixed up for a 1.0.

**Comment by KyleAMathews** [comment]
Published 0.5.0 with this addition. Tell me if it works!

**Comment by tamagokun** [comment]
Yep, that did it. Thanks!

I figured a plan for webpack integration would be in the works. Excited to see this project grow.

**Comment by clouddra** [comment]
+1 for modifying/extending webpack
