### ISSUE TITLE
[1.0] Implement offline support

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#500]
Currently Gatsby 1.0-alpha-4 uses [offline-plugin](https://github.com/NekR/offline-plugin) to create a service worker which caches JS chunks and other assets handled by Webpack. Having this service worker installed can dramatically speed up subsequent loads.

The next thing to do is add AppShell and offline support plus the option for caching resources your site is loading that is not handled by Webpack (as offline-plugin doesn't know about these resources automatically).

This article is a great introduction to these two ideas: https://medium.com/@addyosmani/progressive-web-apps-with-react-js-part-3-offline-support-and-network-resilience-c84db889162c#.u6zzu3ar5

My thought with AppShells/offline support is that once the SW has cached assets, on subsequent page loads, pages would be loaded directly from cache. So effectively Gatsby sites would always work as if they're offline. Anything network dependent would be viewed as a "progressive enhancement". With Gatsby this is a safe assumption as most Gatsby sites are primarily static.

For the fastest load, it'd be great to cache the HTML for each page so that users don't have to wait for the JS to be loaded for that page before doing the initial render. But SW caches are somewhat limited (depends on the browser) it's best to avoid caching things if we don't need it. So a good compromise could be to cache the HTML from each layout. Gatsby 1.0 lets you define layouts (similar to `_template.js` in Gatsby 0.x). We could statically render these (with no inner content) and then cache these. Then on loading, we map from the URL to the what will be the active layout and fetch the HTML for that layout from cache so this renders quickly while the browser is fetching the JS for that page from cache and rendering it.

So to make this concrete, if your site has a global header that's part of the layout, then this would be the "AppShell" and load immediately followed shortly after by the remainder of the page content once the JS loads and renders.

I can see this not working well in some cases e.g. a site that has a header and footer as if those render without any content, the footer would come up right to the top of the page and then bounce to the bottom on the full render. This would be a janky experience.

What could make sense is to "race" the network against the cache. Start loading JS from the cache immediately while also simultaneously fetching the static HTML from the server. On a fast browser, the page might render from the cache before the server has responded. On slow devices where evaling JS takes a while, the HTML might be rendered first.

Need to do some prototyping to understand all this more.

**Comment by jbolda** [comment]
Can we also just load pages from cache initially as well to avoid the janky footer jump? I presume you know of @jakearchbald's demo? (Which is actually getting old now, jeez!)

https://github.com/jakearchibald/trained-to-thrill

**Comment by KyleAMathews** [comment]
@jbolda that's perhaps the right strategy. Cache all HTML as well as JS so even in offline we render first the HTML and then hydrate it later with Javascript. Older devices are just slow when it comes to handling JS and provided there's not too many pages, caching all the HTML wouldn't be a problem. For larger sites though it would be a problem. For there either we use an AppShell or just do a pure JS/React client render.

**Comment by NekR** [comment]
@KyleAMathews I recently released `v4` of `offline-plugin` with some features added (like `cacheMaps` for app-shell). Let me know if you would like my help with updating to it. I also could help with writing part of dynamic caching because it still isn't in `offline-plugin`. Just let me know what ideas you may have about it and what would be the best way to use `offline-plugin` here :-)
