### ISSUE TITLE
Include port as part of the url

### ISSUE THREAD

**Issue by Maxhodges** [gatsbyjs/gatsby#5003]
Not sure if this issue is with Gatsby or a the contentful plugin

Could you guys include the port as part of the URL when you output up it during a build?

![image](https://user-images.githubusercontent.com/957271/38817291-074e38e6-41d3-11e8-83f1-e875c677d028.png)

Since the port is broken off from the URL, I gotta copy and paste the url, when I could simply click it in my terminal if it were done properly.

![image](https://user-images.githubusercontent.com/957271/38817351-2a3bd8a4-41d3-11e8-8e21-69c4e9ffdb28.png)

**Comment by m-allanson** [comment]
@Maxhodges I believe Gatsby outputs the url as a single string, you can see [the responsible line here](https://github.com/gatsbyjs/gatsby/blob/8680988fc922186c2d52f80ab6acb6e935fd4ebf/packages/gatsby/src/commands/develop.js#L349). 

What is your first screenshot from? I suspect your terminal is splitting the url and highlighting it incorrectly.

**Comment by Maxhodges** [comment]
wow, thanks. But now I'm really confused!  It's from Hyper, which has a plugin to make urls clickable. Some urls with ports ARE clickable from other routines. So I'm quite perplexed as to where this is coming from exactly.

https://github.com/zeit/hyperlinks/issues/44

**Comment by Maxhodges** [comment]
ah I see, maybe coming from CHALK
https://github.com/zeit/hyperlinks/issues/25

OK to close.
