### ISSUE TITLE
Tutorial Part Six: No Date or Title in frontmatter in GraphiQL

### ISSUE THREAD

**Issue by twhiteaker** [gatsbyjs/gatsby#5024]
## Description

In the part of the tutorial where we first view the frontmatter node in GraphiQL, the title is blank and the date node is missing.

### Steps to reproduce

The problem is caused by copying all text in a code block in the tutorial from Firefox and pasting into a text editor on a Windows machine.

1. Using a Windows 10 machine, create a new empty text file called sweet-pandas-eating-sweets.md per the tutorial. 
2. In Firefox, on the tutorial part six page, use your mouse to select all text in the markdown code block for sweet-pandas-eating-sweets.md. Be sure to select all text, from the opening `---` through the closing `>` on the iframe.

![image](https://user-images.githubusercontent.com/699496/38896083-5fea078a-4257-11e8-8434-58bac26dc17a.png)

3. Copy the text, e.g., CTRL+C.
4. Paste the text in sweet-pandas-eating-sweets.md.  Notice two extra lines (Line Feed character, Hex 0A) at the top and bottom of the file.  It's the two extra lines at the top that break things.  Save and close the file.

![image](https://user-images.githubusercontent.com/699496/38896140-8253147e-4257-11e8-8fea-f365b2f7cbed.png)

5. Continue with the tutorial, installing gatsby-transformer-remark and configuring gatsby-config.js.
6. Restart the server and open GraphiQL to browse to the frontmatter element. Notice title is empty, and date node is completely missing.

The key is selecting and copying **all text** in the code block in **Firefox** on **Windows**. 

Here are things that DO NOT reproduce the problem:
* Selecting just part of the text, such as a single line. 
* Copying the text from Chrome instead of Firefox.
* Copying the text from Chrome or Firefox on a Mac, as tested by @shannonbux.

### Expected result

Title and date nodes should be present and populated with text from the markdown file.

![image](https://user-images.githubusercontent.com/699496/38896013-3341e2c0-4257-11e8-91a8-884a8059c903.png)

### Actual result

Title is empty, and date node is completely missing.

![image](https://user-images.githubusercontent.com/699496/38895940-02c5209e-4257-11e8-867a-2f76a97bc648.png)

### Environment

* Gatsby version:  gatsby@1.9.250
* gatsby-cli version: 1.1.50
* Node.js version: Node.js 8.10.0 (x64)
* Operating System: Windows 10 64-bit
* Browser: Firefox
* Code editor: Tested and reproduced in Notepad++, Visual Studio Code, and Notepad

### File contents (if changed):

`gatsby-config.js`: 
```
module.exports = {
  siteMetadata: {
    title: `Pandas Eating Lots`,
  },
  plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `src`,
        path: `${__dirname}/src/`,
      },
    },
    `gatsby-transformer-remark`,
    `gatsby-plugin-glamor`,
    {
      resolve: `gatsby-plugin-typography`,
      options: {
        pathToConfigModule: `src/utils/typography`,
      },
    },
  ],
};
```

### Comments

A copy button in the top right corner of each code window could help avoid this problem, as long as the extra lines weren't copied. 

I also wonder if the gatsby-transformer-remark plugin is intended to fail to read the metadata if there are blank lines at the top of the markdown file.  It looks like the tutorial examples follow the [YAML metadata block](http://pandoc.org/MANUAL.html#extension-yaml_metadata_block) convention, which states, "A YAML metadata block may occur anywhere in the document." Or does it only count as blog-post-level-metadata if it's at the top?

Another possible solution is to instruct the user to remove any blank lines at the top.

**Comment by m-allanson** [comment]
Thanks for the detailed report @twhiteaker!

> I also wonder if the gatsby-transformer-remark plugin is intended to fail to read the metadata if there are blank lines at the top of the markdown file

I think we should fix this behaviour if possible. The next steps might be:

- demonstrate the issue with a failing test in the [`gatsby-transformer-remark`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-remark/src/__tests__) plugin
- investigate if this behaviour exists in [`gray-matter`](https://github.com/jonschlinkert/gray-matter), which is the module that Gatsby uses for parsing frontmatter 

I'm going to mark this as _help wanted_ for anyone to jump in and help out.

Also note that @shannonbux has created an issue for the copy / paste button: #5030 🎉

**Comment by twhiteaker** [comment]
Looks like the behavior does exist in `gray-matter`.  Here's the result from the [gray-matter example](https://github.com/jonschlinkert/gray-matter#what-does-this-do) with no blank lines at the top, and then after adding two blank lines and running `node example` again.

![image](https://user-images.githubusercontent.com/699496/38939844-6b3f090e-42ee-11e8-838a-31352c07f923.png)

**Comment by m-allanson** [comment]
Thanks @twhiteaker! Want to file an issue over on the gray-matter repo?

**Comment by twhiteaker** [comment]
[done](https://github.com/jonschlinkert/gray-matter/issues/71)

**Comment by KyleAMathews** [comment]
We could start trimming top whitespace in the meantime as well though it'd be great to have this fixed upstream.

**Comment by jonschlinkert** [comment]
> We could start trimming top whitespace in the meantime as well though it'd be great to have this fixed upstream.

I mention this in https://github.com/jonschlinkert/gray-matter/issues/71, but we would be breaking established front-matter conventions to trim whitespace. Typically, front-matter is expected to be the _very first thing_ in a file. 

I'm open to discussing, but just wanted to be clear that this is a feature request, and we'd be breaking conventions to support it.

**Comment by KyleAMathews** [comment]
Oh really? Wasn't really sure what the convention was.

The other approach for fixing this is to add a copy button to code blocks — this problem is only cropping up it seems in Firefox.

**Comment by jonschlinkert** [comment]
I'm open to feedback, let me know what you think we should do.

**Comment by shannonbux** [comment]
@twhiteaker thanks for submitting such a thorough issue and contacting me
to figure out the problem!

**Comment by twhiteaker** [comment]
Per my [comment in gray-matter](https://github.com/jonschlinkert/gray-matter/issues/71#issuecomment-382723455), it looks like there is no formal specification, but placing it at the top is what several projects follow and so it has become the de facto convention.  Thus, I think the best solution is to bring this to the user's attention in the tutorial. It's better to have users construct "valid" front-matter than to make gatsby too smart.

**Comment by twhiteaker** [comment]
Oh, and that Copy button will be great, too!

**Comment by KyleAMathews** [comment]
Title is about in and we're working on a copy button

**Comment by baerrach** [comment]
I've just bumped into this issue as well by following along with the tutorial.

The other option is to remove date from the GraphQL query string.
