### ISSUE TITLE
Some links in CONTRIBUTING.md broken on GitHub

### ISSUE THREAD

**Issue by twhiteaker** [gatsbyjs/gatsby#5027]
## Description

It looks like you're trying to use a single CONTRIBUTING.md file, with [how-to-contribute.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/how-to-contribute.md) in the docs folder being a symlink to [CONTRIBUTING.md](https://github.com/gatsbyjs/gatsby/blob/master/CONTRIBUTING.md) at the root level of this project. As CONTRIBUTING.md is currently written, the relative links to things like "Reporting bugs or issues" work fine when the file is viewed on gatsbyjs.org, but not when the file is viewed directly on GitHub. 

### Steps to reproduce

View CONTRIBUTING.md on GitHub and click the link for "Reporting bugs or issues". 

### Expected result

The link would bring me to information about how to file an issue.

### Actual result

404 Page not found

### Comments

I started to fix the relative links on CONTRIBUTING.md so it would work on GitHub and PR it, but then I realized it would probably break links on gatsbyjs.org.  I don't know how to magic this, unless you include the full URL to the files as they live on gatsbyjs.org.

**Comment by m-allanson** [comment]
Yeah this trips people up fairly regularly... it'd be nice to fix. The way to do it would be:

- change all the docs links to work on GitHub
- write a transformer plugin for gatsbyjs.org that rewrites the links when the site is published

Related discussion: https://github.com/gatsbyjs/gatsby/pull/3982

**Comment by KyleAMathews** [comment]
I had a thought about how to fix this yesterday — keep "how-to-contribute.md" the same and make CONTRIBUTING.md just be a link to the website.

**Comment by SD10** [comment]
Fixed in #5249
