### ISSUE TITLE
Remount componentDidMount() on route change 

### ISSUE THREAD

**Issue by discovrbookings** [gatsbyjs/gatsby#5031]
When the page loads I use componentDidMount() to `document.createElement("script");` in the layout `index.js` of a **ReactJS** and **GatsbyJS** project as 

    componentDidMount () {
      const tripadvisorLeft = document.createElement("script");
      tripadvisorLeft.src = "https://www.jscache.com/wejs?wtype=selfserveprop&uniq=789&locationId=10467767&lang=en_NZ&rating=true&nreviews=0&writereviewlink=true&popIdx=true&iswide=true&border=false&display_version=2";
      tripadvisorLeft.async = true;
      document.body.appendChild(tripadvisorLeft);
    }

This then requests the data to be displayed and works fine. However, when I `<link to=...` another page using `gatsby-link`, `componentDidMount()` has already run so it will does not fetch the data again.

How can I ensure that this script is `mounted` after each `path` change, or better by a specific `path`? Normally achieved with hooks like `onChange` and `onUpdate` in `react-router` but cannot find documentation here for `gatsby-link`

**Comment by m-allanson** [comment]
Where is your `componentDidMount()` method? If you add it to a page component it should run when the page mounts.

Alternatively, maybe you can use the [`replaceRouterComponent` browser API](https://www.gatsbyjs.org/docs/browser-apis/#replaceRouterComponent). See [here](https://github.com/gatsbyjs/gatsby/blob/c89cfd18e57b2e0f656d57b1b3a17f5ce5b70aa2/examples/using-redux/gatsby-browser.js) for an example usage.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
