### ISSUE TITLE
splitting static files/images into subfolders

### ISSUE THREAD

**Issue by CanRau** [gatsbyjs/gatsby#5033]
## Description

I'm having close to 10k images in public static and it's likely going to grow so I thought about splitting them up into sub directories

At first I was so confident that just changing webpacks file-loader name template would do the trick, only to realize that it was kind of stupid haha…
anyway I think it would be awesome to have some kind of splitting option

Some thoughts:
- provide plugin option (to not "break" anything or at least not confuse people) e.g. `splitFiles` which auto splits by count (number of images) for example
- something like [file-loader's placeholders](https://github.com/webpack-contrib/file-loader#placeholders) or some [customisation function](https://github.com/webpack-contrib/file-loader#function) but functions are not (yet) supported in gatsby-config right?

what do you guys think? who is responsible gatsby-plugin-sharp & gatsby-remark-copy-linked-files? anyone else?
to late, don't even remember if I had more thoughts or not, so submitting and sleeping

**Comment by m-allanson** [comment]
Hey @CanRau 👋, I'm not sure I understand your question. That said, it sounds like something that you could experiment with in a plugin? The [custom webpack config docs](https://www.gatsbyjs.org/docs/add-custom-webpack-config/) might be useful.

**Comment by KyleAMathews** [comment]
I forget — is 10k a magic number for files in a directory on some OS?

**Comment by CanRau** [comment]
hehe hi 🖖 @m-allanson that's what i tried and it works for a few fonts and svg's i'm importing but the majority of the images come from graphql queries so webpack is not responsible for copying them right? https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sharp/src/index.js#L307 this one seems to be at least one of the responsible lines
maybe there is a nice way to allow for customisation of this filePath

it could be that i'm a little traumatised because i had a folder full of images, don't remember exact figures, but it was becoming really slow so you could hardly do your business in there haha
all of this happened on another macbook with way less ram than i'm having now so all of this might be history

hi @kyle :) i don't really now as far as i remember it's differs in os's i guess it has to do with some inode limits but those might be fairly large
could've been some circumstances in my case, i'm at least sure it wasn't millions of files and quite sure less than 50k because we have a lot of images but not that much^^

so i'm open to keep it like this for now and investigating further what happens

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
