### ISSUE TITLE
Windows hot reloading of new page components doesn't work in some cases

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#5037]
## Description

When holding a Gatsby workshop last week, several people on old, slow Windows computers didn't get new page hot reloading to work. They had to restart the dev server to see new page components (in src/pages) added as routes.

### Steps to reproduce

1. Use an old, slow Windows computer (haha. I wish I had written down more details about their computer specs)
2. Install Gatsby CLI (@KyleAMathews do your remember the commands we had them run here? And is this list of steps correct according to your memory?)
3. Run `gatsby new my-new-site`
4. Run `gatsby develop`
5. Open localhost:8000
6. Navigate to a route that doesn't exist and see the dev 404 page
7. Follow the instructions to add a new page component for that route
8. The browser doesn't refresh with the new page.

### Expected result

Adding the new page component makes the browser refresh to show it.

### Actual result

Nothing happens

### Environment

I wish I had written down more details about their computer specs. Don't have these.

* Gatsby version (`npm list gatsby`):
* gatsby-cli version (`gatsby --version`):
* Node.js version:
* Operating System:

**Comment by shannonbux** [comment]
ah thanks @kyleamathews!

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
