### ISSUE TITLE
Add codemod for v1 to v2 migration

### ISSUE THREAD

**Issue by kkemple** [gatsbyjs/gatsby#5038]
It would make upgrading much easier if users could run a codemod to convert any breaking changes programatically.

Some things to consider/questions to be answered:

- seems like this could be a plugin and use existing Gatsby APIs to figure out necessary changes
- would need to convert layout queries to static queries
- ???

**Comment by kkemple** [comment]
Seems facebook is working on a nice interactive version of codemod
https://github.com/facebookincubator/fastmod

**Comment by rdela** [comment]
I started my site on `canary` branch based on Kyle’s tweet/branch, so maybe in good spot to diff with `starter-blog` and make that *upgrading to v2* doc?

https://github.com/rdela/rdela.com

https://github.com/KyleAMathews/blog/tree/gatsby-v2-canary?files=1

https://github.com/KyleAMathews/blog/pull/21/files

https://twitter.com/kylemathews/status/954905518874664960?s=20

**Comment by rdela** [comment]
Inspiring prior art https://svelte.technology/blog/version-2

**Comment by rdela** [comment]
Everything from here down in this PR seems relevant
https://github.com/gatsbyjs/gatsby/pull/4887#issuecomment-383259888

**Comment by rdela** [comment]
Particularly this PR where Kyle updates his blog
https://github.com/KyleAMathews/blog/pull/21/files

I remember the `boundActionCreators` => `actions` step, that seems ripe for codemod
https://github.com/rdela/rdela.com/commit/0042e19aa563d15fe9bd6387b17e51ba27c64a54#diff-fda05457e393bada716f508859bfc604

Need to dig into both of those PRs more; unsure currently about how `<StaticQuery>` changes will play out for codemod: whether that ends up being a suggestion codemod could make or item in aforementioned `upgrading to v2` doc

**Comment by m-allanson** [comment]
Taking a look through the migration guide, things it might possible to codemod are:

- [change navigateTo to push](https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#change-navigateto-to-push)
- [import link from gatsby](https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#import-link-from-gatsby)
- [rename boundactioncreators to actions](https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#rename-boundactioncreators-to-actions)
- [use query in place of rootquery](https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#use-query-in-place-of-rootquerytype)

**Comment by tsriram** [comment]
I'll give `import link from gatsby` codemod a try this weekend

**Comment by tsriram** [comment]
Doing another - `rename boundActionCreators to actions`

**Comment by DSchau** [comment]
@tsriram that would be great :) I'm not even 100% sure if you get file name, but if you do, you may want to restrict it to only certain files where that's valid. But looking forward to it!

**Comment by pieh** [comment]
@DSchau It's already opened - https://github.com/gatsbyjs/gatsby/pull/7955 :)

**Comment by DSchau** [comment]
@pieh that's what I get for scrolling through the feed and replying before I get all the way to the bottom 😛 Commented on it :)

**Comment by m-allanson** [comment]
I think we can call this done. Thanks folks :)
