### ISSUE TITLE
Let gatsby-plugin-google-tagmanager accept optional "environment" params

### ISSUE THREAD

**Issue by ssanchez** [gatsbyjs/gatsby#5042]
## Description

Currently gatsby-plugin-google-tagmanager accepts the GTM container ID and the "includeInDevelopment" flag. However, for projects that leverage GTM environments there are two more params that need to get sent with the ID, namely "gtm_auth" and  "gtm_preview".

Can we add the ability to optionally pass in those two params? I needed it for a project and think it might be an enhancement to the plugin others could benefit from too.

### Links

* https://www.simoahava.com/analytics/better-qa-with-google-tag-manager-environments/
* https://support.google.com/tagmanager/answer/6311518?hl=en

**Comment by m-allanson** [comment]
That sounds like a reasonable addition! I've marked this up as _help wanted_.

**Comment by ssanchez** [comment]
Nice! I'm willing to work on this though am not sure if what's outlined in CONTRIBUTING.md applies to plugins as well. I've been looking for an opportunity to contribute for the first time to OSS and would love for this to be it if possible!

**Comment by pieh** [comment]
CONTRIBUTING.md applies to entire repository. Would love if gatsby would be your first OSS contribution! :)

**Comment by sudodoki** [comment]
Seems to be fixed via #5067 and thus should be closed, I guess.

**Comment by kakadiadarpan** [comment]
Closed with #5067
