### ISSUE TITLE
createContext is not a function

### ISSUE THREAD

**Issue by b0gd4n** [gatsbyjs/gatsby#5043]
Trying to use the React context, but and getting `createContext is not a function`.

I see Gatsby is using React version 16.3.10, which should have the new context - what am I missing?

**Comment by b0gd4n** [comment]
@pieh thanks, was not aware of this. 

What's the timeline for v2?

**Comment by pieh** [comment]
We don't have timeline - only github project tracking things that need to be done - https://github.com/gatsbyjs/gatsby/projects/2
