### ISSUE TITLE
Add option for custom ssl cert on develop command

### ISSUE THREAD

**Issue by deltaskelta** [gatsbyjs/gatsby#5044]
## Description

Using the `--https` flag is convenient most of the time, but I have run into a situation where I am running the dev server inside of a docker container. I would like to replicate my prod environment as much as possible so I want to run on https. running the `--https` flag works, but it gives ugly browser warnings and errors retrieving static content because the cert is trusted in the container and not on the host machine.  

### Steps to reproduce

Run `gatsby develop --https --host 0.0.0.0` in a container. with port `8080` forwarded to the container.

### Proposed outcome

1. If there is a workaround to get the devcerts library to trust the cert on my host machine, that would be great.

2. If that fails, if there was a way to pass the gatsby dev server a custom cert, then I could give it a cert that is trusted on my host machine already.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
