### ISSUE TITLE
Filter/sort group() results

### ISSUE THREAD

**Issue by Destroy666x** [gatsbyjs/gatsby#5046]
## Description

I'm not sure if me and documentation are missing something or the feature is missing, but filtering/sorting `group` results seems to be impossible within single GraphQL, correct me if I'm wrong.

### Steps to reproduce

Execute:
```
query TagsForPostBySlug($slug: String!) {
    tags: allMarkdownRemark(filter: { fields: { slug: { eq: $slug } } }) {
      group(field: frontmatter___tags) {
        name: fieldValue
        totalCount
      }
    }
  }
```
What I had it mind was getting (only) all the tags for a specific post with their overall usage counts. But the above query obviously always returns `totalCount` of 1. And if I skip the filter I get all tags that I need to filter in JS.

### Environment

* Gatsby version (`npm list gatsby`): 1.9.224
* gatsby-cli version (`gatsby --version`): 1.1.50
* Node.js version: 9.10.1
* Operating System: Ubuntu 17.10

**Comment by pieh** [comment]
`group` does grouping in context of query - if you apply filter to query then it will have only single MarkdownRemark node to group and will therefore result in totalCount being always `1`

I'm thinking if you would pass `tags` via context in `createPage` (in addition to `slug`) and use those `tags` to filter nodes then this might work?

**Comment by Destroy666x** [comment]
Thanks for reply. Do you mean `query PostBySlug($slug: String!, $tags: [String]!)` into:
```
tags: allMarkdownRemark(filter: { frontmatter: { tags: { in: $tags } } }) {
      group(field: frontmatter___tags) {
        name: fieldValue
        totalCount
      }
    }```
? If so, that gets all the tags that are in the same arrays as tags from the article I'm passing.

**Comment by pieh** [comment]
Hmm, isn't that what You wanted? I think I missunderstood then. Could you explain what are you trying to achieve? I thought this was to list all tags assigned to post and their post count

**Comment by Destroy666x** [comment]
> I thought this was to list all tags assigned to post and their post count

Exactly. But the result has still more entries than I need. Let me provide you with an example. We search by `tags: ["PHP"]`, which is the only tag of a post. It's used in 3 posts, the count is correct. I get JSON with `PHP` and a bunch of tags from other 2 posts though.

**Comment by pieh** [comment]
Ok, I see now. You are defenitely right. My proposition would work as intented if there was only single tag I guess then (which is not most people would use `tags` for)

We could add filtering to groups ( here - https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/build-connection-fields.js#L57 if any one is interested to actually do this). More we data handling we can do via graphql the better - as this doesn't force to do this in js and decrease ammount of data needed to load later during runtime.

I guess until this is done you are stuck with filtering with JS (possibly with prefiltering as I proposed to decrease ammount of data being loaded).

**Comment by Destroy666x** [comment]
Ok. I can try providing a PR for both `filter` and `sort`. Unless someone more experience with Gatsby does so until tommorow.

**Comment by vernalkick** [comment]
I’m also having the same issue

**Comment by ekaoddlass** [comment]
I'm having the same issue (cannot sort `group`s of posts). 

An observation: It appears to be sorted in ascending alphabetical order, based on the field used for grouping. Eg. I group my query based on `frontmatter__date`. The results are ordered from earliest date to latest -- which unfortunately does not make sense for this case!

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
