### ISSUE TITLE
 [gatsby-source-wordpress] GraphQL Error Unknown type "acf_post_photo"

### ISSUE THREAD

**Issue by williharder** [gatsbyjs/gatsby#5049]
When I run `gatsby develop` I get a GraphQL error regarding the ACF fields and on the frontend I get an error message. 

![bildschirmfoto 2018-04-19 um 20 12 57](https://user-images.githubusercontent.com/794605/39010204-313f9d7e-440e-11e8-9d98-e5ed707c9140.png)

The shown error message in the terminal console reads 
`GraphQL Error Unknown type "acf_post_photo".`

I started a Gatsby App & WordPress Site from scratch and copied carefully the everything in order. I also changed the acf field names in the backend and in templates/post.js

![bildschirmfoto 2018-04-19 um 20 01 22](https://user-images.githubusercontent.com/794605/39010429-f0c58190-440e-11e8-96af-7802cd0876a6.png)

**When I delete all code respective to ACF from templates/post.js the app builds just fine and all regular wordpress content is shown.** 

The curios thing is, that when I run a query from GraphiQL it successfully pulls all the acf fields and content. 
 
![bildschirmfoto 2018-04-19 um 20 20 55](https://user-images.githubusercontent.com/794605/39010567-4cf5c556-440f-11e8-99dc-b88c54b5e668.png)
![bildschirmfoto 2018-04-19 um 20 21 32](https://user-images.githubusercontent.com/794605/39010569-4f4f41c4-440f-11e8-9c18-62e08a6f9818.png)

These are all my plugins in WordPress

![bildschirmfoto 2018-04-19 um 19 51 10](https://user-images.githubusercontent.com/794605/39010694-ab190f4e-440f-11e8-9baf-7408aa4a72a7.png)

This is my edited code from [templates/post.js](https://pastebin.com/H9Ccr3d1)

There were already several similar issues, though none brought a solution. Hopefully somebody can help?  (Sorry about not keeping it short 🌚)

**Comment by williharder** [comment]
But that's what I don't get. In the example source code from [gatsby-source-wordpress] inline fragments are also used. In the [documentation for the plugin ](https://www.gatsbyjs.org/packages/gatsby-source-wordpress/?=wordpres#query-with-acf-flexible-content)its being done this exact way.

**Comment by pieh** [comment]
Oh, I didn't catch it is flexible content - so problem here is You use only single type - gatsby will not create Union for single type (and when union is created that's when inline fragments are needed). So if you will have more content of different type in your flexible field (it doesn't have to be in same post) then union will be created and you will need inline fragments.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
