### ISSUE TITLE
Flow error

### ISSUE THREAD

**Issue by neptunian** [gatsbyjs/gatsby#5051]
i get this error when trying to implement Flow types: ` Cannot resolve name graphql`
Is Gatsby compatible with Flow?  Obviously, this is from the graphql query function that Gatsby understands but causes Flow to throw an error.  Is there any way around it?

**Comment by neptunian** [comment]
yea, i did see that issue, which has me wondering whether they were using queries in the components if they arent getting the error...

**Comment by PolGuixe** [comment]
+1 with the same issue. 

@eleith I don't get your solution. Do you have any references I can use?

**Comment by PolGuixe** [comment]
I ended up doing the following:

```
//.flowconfig

...
[options]
suppress_comment= \\(.\\|\n\\)*\\$FlowIgnore
...
```

And then adding a comment everytime I am using graphql
``` js

//...

// $FlowIgnore: ignore graphql
export const query = graphql`
  query SiteTitleQuery {
    site {
      siteMetadata {
        title
      }
    }
  }
`;

//...

```

It is not a good solution anyway

**Comment by mukealicious** [comment]
I believe @eleith's solution works, with one small change.

Probably just a typo, but the file should be `/flow-typed/graphql.js` with the same content as mentioned above:

```
declare var graphql: any;
```
