### ISSUE TITLE
markdown plugins, those are already on npm, just make some option to enable usage

### ISSUE THREAD

**Issue by liesislukas** [gatsbyjs/gatsby#506]
I was looking how to make textAlign={'center'} with md file and found this plugin:

https://www.npmjs.com/package/markdown-it-center-text

to use it you have just enter this:

```
var md = require('markdown-it')()
            .use(require('markdown-it-center-text'));
```

I can't find any way to option-in markdown plugins now and there are many plugins available on npm: https://www.npmjs.com/browse/keyword/markdown-it-plugin

What is more i could write plugin for markdown if something missing, but there must be some way to import it into gatsby. Do you have any ideas? I've noticed, that i use 

`"gatsby": "^0.12.12"`

I'll try updating to newest

**Comment by chris-alexander** [comment]
I think you need to add a custom markdown loader: e.g. https://github.com/gatsbyjs/gatsby-starter-default/blob/master/loaders/markdown-loader/index.js

then add your plugin with `md.use(...)` like in lines 28-32

**Comment by liesislukas** [comment]
I can't test, already switched to phenomic.io, sorry, but seems valid. Gatsby should have better documentation.

**Comment by chris-alexander** [comment]
@KyleAMathews can I submit a PR to add this to the FAQ?

Something along the lines of this but better written:

**How to include additional `markdown-it` plugins**

- copy the markdown loader from the `gatsby-starter-default` template
- install required modules `npm i -S front-matter markdown-it ...`
- add a new `.use(require('markdown-it-plugin-name')` for each `markdown-it` plugin you want to use

**Comment by KyleAMathews** [comment]
That'd be great, thanks Chris!
