### ISSUE TITLE
Error when using gatsby-image plugin

### ISSUE THREAD

**Issue by b0gd4n** [gatsbyjs/gatsby#5060]
Following the minimal setup for the gatsby-image plugin and I am getting the following error after adding the query to the index page:

`GraphQL Error Unknown field 'imageSharp' on type 'RootQueryType'`

What am I missing? I have this in my config file:

```
    'gatsby-transformer-sharp',
    'gatsby-plugin-sharp',
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `src`,
        path: `${__dirname}/src/`,
      },
    },
```

This is the query:

```graphql
  query FrontPageQuery {
    imageSharp(id: { regex: "/caseStudyPlaceholder/" }) {
      sizes(maxWidth: 1500, rotate: 180) {
        ...GatsbyImageSharpSizes
      }
    }
  }
```

**Comment by m-allanson** [comment]
Have you tried using the graphQL explorer to test your query? When running `gatsby develop` it should be available at http://localhost:8000/___graphql

**Comment by m-allanson** [comment]
There's some new docs on using images with Gatsby, they're still being reviewed but you can preview them here: https://github.com/melissamcewen/gatsby/blob/b8f19c22b60cd6c58472bb16ea264b54366e1b47/docs/docs/working-with-images.md

**Comment by b0gd4n** [comment]
OK, I tried the query from the docs mentioned above:

```
export const query = graphql`
  query indexQuery {
    fileName:file(relativePath: { eq: "assets/caseStudyPlaceholder.jpg" }) {
      childImageSharp {
        sizes(maxWidth: 400, maxHeight: 250) {
          ...GatsbyImageSharpSizes
        }
      }
    }
  }
`;
```

and am getting `GraphQL Error Unknown field `file` on type `RootQueryType``

**Comment by b0gd4n** [comment]
I cleaned all `node_modules` and the `package.lock` file, reinstalled and it seems to be working now.

**Comment by danielwrobert** [comment]
I'm getting this exact same issue. Removing `node_modules` and `package-lock.json` then reinstalling did not seem to fix anything.

Same errors you mentioned above, depending on the query structure. ☹️
