### ISSUE TITLE
Query multiple images with GrapQL

### ISSUE THREAD

**Issue by b0gd4n** [gatsbyjs/gatsby#5062]
I would like to load all images in a certain folder (e.g. `assets/team/`) and use them through the gatsby-image plugin.

I currently have it working for 1 single file with this query:
```
export const query = graphql`
  query BlurUpQuery {
    heroAssets: imageSharp(id: { regex: "/testImage/" }) {
      sizes(maxWidth: 600) {
        ...GatsbyImageSharpSizes_tracedSVG
      }
    }
  }
`
```
which returns sizes for this asset. Is it possible to grab all assets in a certain folder?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
