### ISSUE TITLE
gatsby-plugin-sharp – toFormat not flexible enough

### ISSUE THREAD

**Issue by signalwerk** [gatsbyjs/gatsby#5072]
Hi! I'd like to have TIFF-images in my markdown-files: `![image test](./test.tif)`. This actually already works more or less (#5071) when I take the `gatsby-remark-images` package and run it like that:

```JS
// gatsby-config.js
{
  resolve: 'gatsby-transformer-remark',
  options: {
    plugins: [
      {
        resolve: 'gatsby-remark-images',
        options: {
          toFormat: "JPG", // ←––––––– HERE
        }
      },
    ],
  },
},
```
Cool. But now my png-files are also converted to jpeg-files. Any idea how we should implement a more detailed handling. My first thought:

`toFormat: <string> | <object>`

So we can have the backward-compatible defintion
```
options: {
  toFormat: "JPG",
}
```

or new:
```
options: {
  toFormat: {
    '*': 'JPG',
    'PNG': 'PNG',
    'JPG': 'JPG',
  },
}
```

second thoght would be to indicate that in markdown:

`![image test](./test.tif?toFormat:JPG)`

I think the `options`-solution is more elegant.

**Comment by m-allanson** [comment]
Thanks for investigating this @signalwerk! There's a few ways this API could work, maybe @KyleAMathews has some thoughts on this? I wonder if this option is too specific to add directly to `gatsby-remark-images`, is it something that could be done in a custom plugin?

**Comment by signalwerk** [comment]
@m-allanson thank you for your opinion. what would you think if we fallback to jpg if it's not png or jpg. therefore the .tiff's would end as jpg and we have no configuration.

**Comment by m-allanson** [comment]
Yeah that could be an option too, just picking a format to convert to.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
