### ISSUE TITLE
Errors while working with gatsby-source-filesystem

### ISSUE THREAD

**Issue by ajayns** [gatsbyjs/gatsby#5078]
I'm currently working on a gatsby-source-plugin, that requires `createRemoteFileNode` for handling images and media files.

I've added `gatsby-source-filesystem` for `createRemoteFileNode` function:
```javascript
const { createRemoteFileNode } = require(`gatsby-source-filesystem`);
```
And when run the plugin in a tester project, even though I'm not even using the function yet, it throws the following error:
```bash
error UNHANDLED EXCEPTION


  Error: Cannot find module 'better-queue'
  
  - module.js:11 require
    internal/module.js:11:18

```

Any help or suggestions in fixing this issue would be appreciated.

**Comment by m-allanson** [comment]
This looks like a missing dependency in the package. Adding `better-queue` to `gatsby-source-filesystem`'s [`package.json`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-filesystem/package.json#L9) should fix it.

**Comment by ajayns** [comment]
I was thinking of doing the same, but doubted if it was a local error on my system rather than an issue in package. If we can confirm the issue is with the package, I'll make the PR and try. @m-allanson

**Comment by ajayns** [comment]
@m-allanson This issue has been resolved with the PR, closing it.

**Comment by m-allanson** [comment]
Thanks @ajayns 🙏

**Comment by ajayns** [comment]
Happy to help :smiley:  @m-allanson
