### ISSUE TITLE
gatsby-plugin-remove-trailing-slashes causes blank blog post and infinite recompilation

### ISSUE THREAD

**Issue by huy-nguyen** [gatsbyjs/gatsby#5080]
## Description

`gatsby-plugin-remove-trailing-slashes` causes infinite recompilation and cases blog posts' content to go blank after a few saves/edits.

### Steps to reproduce

- Clone the repo https://github.com/huy-nguyen/demo-gatsby-plugin-remove-trailing-slashes-bug. I made it very minimal to help isolate the problem.
- Run `gatsby develop`.
- Go to `http://localhost:8000/posts/one/` if Gatsby is served from port 8080.
- Post content should show up just fine.
- Edit and save the file `src/posts/one.md` a few times. This is the content of the post.
- Blog post content goes blank.

### Expected result
Blog post should be updated according to the new content.
### Actual result
Blog post goes blank after a few save/edits. However, `git checkout` the last commit before `HEAD` (`a13b5b8d`) doesn't cause this problem so the problem must be in the `gatsby-plugin-remove-trailing-slashes` plugin.
### Environment

* Gatsby version (`npm list gatsby`): 1.9.250
* gatsby-cli version (`gatsby --version`): 1.1.50
* Node.js version: 9.10.1.
* Operating System: Mac OS 10.12.6

### File contents (if changed):

See diff between `a13b5b8d` and `0b26e909`.

**Comment by huy-nguyen** [comment]
@m-allanson I created another [branch](https://github.com/huy-nguyen/demo-gatsby-plugin-remove-trailing-slashes-bug/tree/afcfe7a43ced5f3ce535b26bddcb8c8f77a7637a) on the repo that replaces the plugin with the snippet from the link you mentioned. The bug didn't happen. What does that mean?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
