### ISSUE TITLE
String interpolation/concat on Graphql Queries

### ISSUE THREAD

**Issue by ThiagoMiranda** [gatsbyjs/gatsby#5090]
Hi...
I'm trying to make a search and concatenate an variable with some surround string to work with the `regex` filter. How can I do that in Graphql? My goal is to wrap the $lang variable in `/` characters. Somehthing like that ( this don´t work ):

```graphql
  query ContentByPath($slug: String!, $lang: String!) {
    site {
      siteMetadata {
        title
      }
    }
    markdownRemark(
      frontmatter: { slug: { eq: $slug } }, fileAbsolutePath: { regex: "/${$lang}/" }) {
      id
      htmlAst
      html
      frontmatter {
        section
        title
        date(formatString: "MMMM DD, YYYY")
      }
    }
  }
```
Is it possible?

Thanks

**Comment by julionav** [comment]
I know this is closed but when googling how to do interpolation in gatsby this still shows up.

The workaround that I did for this is to construct the **regex expression** outside the graphql query. 

In my case, it was inside `createPages` inside `gatsby-node`

```javascript
context: {
  moduleRegex: `/${module}/`,
}
```

Then inside the query:
```javascript
query($moduleRegex: String, $mdxId: String) {
    mdx(id: { eq: $mdxId }) {
      body
    }
    allFile(filter: { relativeDirectory: { regex: $moduleRegex } }) {
      nodes {
        name
      }
    }
}
```
