### ISSUE TITLE
How can I include a polyfill?

### ISSUE THREAD

**Issue by b0gd4n** [gatsbyjs/gatsby#5091]
I am interested in finding out how I could include a polyfill, such as [object-fit-images](https://www.npmjs.com/package/object-fit-images) or [babe-polyfill](https://babeljs.io/docs/usage/polyfill/) ?

**Comment by m-allanson** [comment]
@b0gd4n have you tried searching through older issues? There's a few discussing polyfills that might be useful.

I'm going to close this, please open a new issue if you have a specific problem! Note that filling out the issue template makes it much easier to give you useful advice.
