### ISSUE TITLE
gatsby-source-npm-package-search doesn’t pull in all packages

### ISSUE THREAD

**Issue by calcsam** [gatsbyjs/gatsby#5092]
## Description

Querying the Algolia NPM package search via yarnpkg.com identifies [101 plugins](https://yarnpkg.com/en/packages?q=gatsby-source&p=1) named gatsby-source-* , but our package search [only identifies 79](https://www.gatsbyjs.org/plugins/?=gatsby-source).

One example of a source plugin that’s being omitted is https://yarnpkg.com/en/package/gatsby-source-github-projects

### Steps to reproduce

Clone gatsby, cd www, gatsby develop and [query the GraphiQL IDE](http://localhost:8000/___graphql?query=%7B%0A%20allNpmPackage%20%7B%0A%20%20totalCount%0A%20%20%20edges%20%7B%0A%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20name%0A%20%20%20%20%20%7D%0A%20%20%20%7D%0A%20%7D%0A%20%20%0A%7D). The data isn't coming through gatsby-source-npm-package-search.

### Expected result

A package should come through with name: "gatsby-source-github-projects"

### Actual result

No package comes through.

**Comment by KyleAMathews** [comment]
Yeah the reason is that we only pull in packages that include the "gatsby-plugin" keyword which that package doesn't https://www.npmjs.com/package/gatsby-source-github-projects

We could perhaps also search for unique strings like "gatsby-source" that are unlikely to have false positives.

**Comment by m-allanson** [comment]
The search could be updated to include `gatsby-source` and `gatsby-transformer` along with gatsby plugin?

**Comment by KyleAMathews** [comment]
@m-allanson yeah and perhaps `gatsby-plugin` too.

**Comment by KyleAMathews** [comment]
Let's just stick with `gatsby-plugin` for our keyword. It seems plugin authors are figuring out they need this pretty well and adding more keywords just complicates the process needlessly.
