### ISSUE TITLE
Firefox 'Add to Home Screen'

### ISSUE THREAD

**Issue by HTEredrock** [gatsbyjs/gatsby#5112]
## Description

So Firefox now supports PWAs with an "Add To Home Screen" button in Firefox for Android 58. 
However it doesnt seem like `gatsby-plugin-offline` supports this out of the box.

It would be great if it did :smile: 

More details here: https://developer.mozilla.org/en-US/Apps/Progressive/Add_to_home_screen

**Comment by KyleAMathews** [comment]
That'd be great! Would you like to work on a PR adding support?

**Comment by HTEredrock** [comment]
No guarantees, but I'll give it a bash :)

**Comment by HTEredrock** [comment]
So it seems, upon further investigation, like a `.json` file works as well. This seems to be more an issue of an unclear spec. However, `.webmanifest` is the current latest spec: https://w3c.github.io/manifest/.
You can confirm this by visiting gatsbyjs.org on Firefox 58 for Android. 

So it might be worth updating `gatsby-plugin-manifest` to use it? 
@KyleAMathews your thoughts on this?

I also noticed that `gatsby-plugin-manifest` deosnt seem to take `--prefix-paths` into account and always just uses `\` as the `start_url` parameter, which does seem to cause issues from my very initial testing. I think that the parameter should be set to `\index.html` and also that it should include the prefix path if there is one to match the current PWA standards.

**Comment by m-allanson** [comment]
The `.webmanifest` update was done in #5128, thanks @AurelioDeRosa!

**Comment by m-allanson** [comment]
@HTEredrock thanks for raising this, I'm going to close it as your initial request has been handled. If you're seeing an issue with `--prefix-paths` in `gatsby-plugin-manifest` could you open a new issue and fill out the issue template?
