### ISSUE TITLE
Import SVGs throught JSON data

### ISSUE THREAD

**Issue by MaralS** [gatsbyjs/gatsby#5113]
Hi everyone,

I'm managing datas with `gatsby-transformer-json` but I wanted to know how to import our SVGs with **GraphQL queries**.

If you have any solution, I'll appreciate,

Thanks in advance,

Maral 😃

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
