### ISSUE TITLE
Add plugin to support CSS Blocks

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#5120]
More details about CSS Blocks can be found at [css-blocks.com](https://css-blocks.com).

**Comment by m-allanson** [comment]
Refs #1199

**Comment by kripod** [comment]
I just made an experimental implementation: https://github.com/gatsbyjs/gatsby/pull/5146

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
