### ISSUE TITLE
Error working with createRemoteFileNode

### ISSUE THREAD

**Issue by ajayns** [gatsbyjs/gatsby#5126]
I've been following the documentation for createRemoteFileNode and have used similar code, but a few errors seem to be thrown when I attempt to create nodes.

```bash
The new node didn't pass validation
ValidationError: child "internal" fails because ["description" is not allowed]
```

For some reason, even though my code makes no changes to `internal.description`, this error seems to occur. Is there a possibility that this is an internal error with 'createRemoteFileNode`?

**Comment by pieh** [comment]
You need gatsby@1.9.250 to use `internal.description` field - but you can omit that field

**Comment by ajayns** [comment]
But I'm not using that field in my code at all, the createRemoteFileNode function seems to be doing this by itself. @pieh

**Comment by pieh** [comment]
In that case you need to update gatsby to at least 1.9.250

**Comment by ajayns** [comment]
@pieh Thanks a bunch, this issue has been resolved with the update.

**Comment by ajayns** [comment]
Closing issue, thanks again community for such fast resolution.
