### ISSUE TITLE
[v2] prepare new animation example 

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#5135]
Perhaps based on this https://twitter.com/mike_wagz/status/972480264654983168?s=19

**Comment by KyleAMathews** [comment]
Or this is a more interesting example to copy https://imgur.com/a/VXP0l5N

Or best of all copy https://page-transitions.com/

**Comment by ajayns** [comment]
I love the transitions at https://page-transitions.com/ 
They look similar to what's done in [react-morph](https://brunnolou.github.io/react-morph/?down=0).

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
