### ISSUE TITLE
No documention on using files cached by createRemoteFileNode

### ISSUE THREAD

**Issue by ajayns** [gatsbyjs/gatsby#5147]
While working with remote files, the current documentation that we wrote is pretty clear on how to use the function, but I feel we need to add an example of how to use such files in a Gatsby project.

@m-allanson @KyleAMathews

**Comment by ajayns** [comment]
Is there any existing use case that you can point me to, so that I can work on a PR? @KyleAMathews

**Comment by KyleAMathews** [comment]
https://www.gatsbyjs.org/packages/gatsby-source-wordpress/?=wordpres#image-processing

**Comment by ajayns** [comment]
Isn't that specifically for images? Wouldn't it be better to add an example for general files so that they include linking documents, videos and everything else as well.  @KyleAMathews

**Comment by KyleAMathews** [comment]
Your hypothetical example can be about whatever you'd like it to be :-)

**Comment by ajayns** [comment]
So in cases of files, I was thinking the data URL can be queried by `relativePath` in Gatsby, and then used in the project as `<a href="path-here">File</a>`.
Is this approach advisable?

**Comment by KyleAMathews** [comment]
No — `createRemoteFileNode` is only for use by source/transformer plugins that know about a remote file and want to pull it locally. The downloaded files aren't findable via directly searching. That's why the examples on source-filesystem and source-wordpress have you querying the file through other data.

**Comment by ajayns** [comment]
Oh I wasn't aware of that. So in the case of remote files, say a PDF and maybe even a mp4 video that's stored in the CMS, what's the best approach to sourcing these files in a plugin? @KyleAMathews 

Also, I'll try to add an example usage to the wordpress handling images only then.

**Comment by ajayns** [comment]
Before I close this issue, I'd really appreciate a bit of help from the community on how to handle remote files as mentioned above! Any suggestions on best approach are appreciated!
