### ISSUE TITLE
[gatsby-plugin-sass] Code splitting for SASS styles

### ISSUE THREAD

**Issue by eads** [gatsbyjs/gatsby#5149]
This is a question that might entail some additional tasks. 

There's something I can't quite figure: I'd love to split up SASS per-route for a project with two very different and independent pages. One, a full page presentation, needs a maximal stylesheet based on my company's standard library (which is written in scss). The other, an embeddable widget, needs literally none of that stuff.

The SASS plugin compiles everything together, inline, on both pages. Is there a way to change this behavior? 

I should also note that at first, I was assuming there was code-splitting for SASS styles, so I used `@import` for bits and pieces of the standard library in the per-page scss files. That actually made things worse -- inspecting the generated CSS, I saw repeated rules. That makes perfect sense without code-splitting, but the way it interacted with how I initially expected the system to work actually led to additional unintended bloat.

**Comment by KyleAMathews** [comment]
This isn't easy to do with Gatsby v1 but Gatsby v2 will do this out of the box (assuming you import different SASS files per component) with help from [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin).

**Comment by eads** [comment]
That's what I feared. For this project, I can just split the codebases and have two separate projects. But is Gatsby v2 stable enough to start using?
