### ISSUE TITLE
Help: Gatsby performance in low bandwidth environment. (30+ seconds to load)

### ISSUE THREAD

**Issue by thebetterjort** [gatsbyjs/gatsby#5156]
I'm using the basic starter template.
I've added Packages:
typography.js
typography-theme-us-web-design-standards
 styled-components

I simulated a low-bandwidth situation for a laptop using Firefox Dev Tools.

According to [Firefox Dev tools](https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode)

Selection | Download speed | Upload speed | Minimum latency (ms)
-- | -- | -- | --
GPRS | 50 KB/s | 20 KB/s | 500
Regular 2G | 250 KB/s | 50 KB/s | 300
Good 2G | 450 KB/s | 150 KB/s | 150
Regular 3G | 750 KB/s | 250 KB/s | 100
Good 3G | 1.5 MB/s | 750 KB/s | 40
Regular 4G/LTE | 4 MB/s | 3 MB/s | 20
DSL | 2 MB/s | 1 MB/s | 5
Wi-Fi | 30 MB/s | 15 MB/s | 2

**3.3 Mb (size)
30.42 seconds**

Is this expected behavior?

The connection to ws://localhost:8000/socket.io/?EIO=3&transport=websocket&sid=Vm6u8UYK95eN3kkIAAAH was interrupted while the page was loading.

**Comment by pieh** [comment]
Size seems quite large for basically starter with some styling - it doesn't seem right. Can you share your testing methodology? What and how did you test it? Also if you have site you were testing in repository - could you share link so I could check this?

**Comment by KyleAMathews** [comment]
Guessing you tested with `gatsby develop`? As the console output indicates, the JS generated in development is (highly) unoptimized. You should run `gatsby build` then `gatsby serve` to get an idea of what a production build of Gatsby looks like.

**Comment by thebetterjort** [comment]
Thank you!
