### ISSUE TITLE
[www] Base font size for screens > 768px is 16px, not 18px

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#5166]
The gatsbyjs.org base font size for >768px is 16px, not 18px as it used to/should be. It seems `baseFontSize` from https://github.com/gatsbyjs/gatsby/blob/73a0683fe4f03d393f9a5c0bd4420cf352b37b77/www/src/utils/typography.js#L38 doesn't get picked up anymore.

FWIW this was still working a few days ago, e.g. here's a PR preview from like a week ago for #5071 where things are still working fine: https://deploy-preview-5071--gatsbyjs.netlify.com/

**Comment by KyleAMathews** [comment]
Fixed it here: https://github.com/KyleAMathews/compass-vertical-rhythm/commit/9040cf65a8e40bbaa39b9dfb1f9ef562e46dfbd8

I'll upgrade the lock file for www.

**Comment by KyleAMathews** [comment]
Oh well actually we don't have a lock file — so this will get fixed on the next deploy of gatsbyjs.org.

**Comment by KyleAMathews** [comment]
Thanks for the issue! Heard a few other complaints and this got me to investigate more :-)
