### ISSUE TITLE
Best Practice: RSS and Atom Feeds

### ISSUE THREAD

**Issue by Algram** [gatsbyjs/gatsby#517]
Hello,

I wanted to know what the current standard for adding feed generation is. I honestly think this should be a default feature in the starte blog btw (I'll probably make a pull request once I have a clean solution).

Should it be done via a post-build like here (https://github.com/KyleAMathews/blog/blob/master/post-build.coffee) or during the build process, where u create a `feed.js` in the `pages` folder where u generate the feed with React which then gets rendered and converted by gatsby.

I would love some suggestions!

**Comment by KyleAMathews** [comment]
Hey! Definitely agree that the starter blog should have a feed generated. I'm very focused on the 1.0 stuff so would love it if you'd take this on.

The feed should definitely be built using `postBuild` as during the regular build process, Gatsby only creates HTML files (and runs everything through your `html.js` file) so you wouldn't be able to create the feed there.

**Comment by Algram** [comment]
Alright, I will do that and make a PR.

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by mchandleraz** [comment]
@Algram any progress on this? Need some help? I'm considering implementing RSS for my blog.

**Comment by KyleAMathews** [comment]
@mchandleraz if you're on 1.0 @nicholaswyoung just added a PR for an RSS feed plugin https://github.com/gatsbyjs/gatsby/pull/1073

**Comment by KyleAMathews** [comment]
Closing since we got gatsby-plugin-feeds now
