### ISSUE TITLE
Pass data from JS to Sass

### ISSUE THREAD

**Issue by cpineda** [gatsbyjs/gatsby#5176]
Hi everyone,

I'm new to Gatsby, it's a great tool! I'm using Contentful which provides content and images, I'm currently using the gatsby-source-contentful plugin. For a hero image on my homepage I want to use a different background from desktop to mobile which Contentful hosts. In my component sass file I've got a style with a media query:

` 
.hero

    background-image: url("../../assets/images/bgimage_desktop.png");
    background-position: right bottom;
    background-repeat: no-repeat;
    background-size: 450px 400px;
    @media screen and (max-width: $break-large)
        background-image: url("../../assets/images/bgimage_mobile.png");
        background-size: 125px 310px;
`
I've got the data from Contentful ready from a graph query, i.e.:

`
  query HeroQuery {
    contentfulHomepage {
      heroBackgroundImageDesktop{
        file{
          url
        }
      }
  }
`

I would like to replace the hard coded image urls with the contentful query data. Any ideas of how to pass teh data from JS to sass?

Thanks.

**Comment by daydream05** [comment]
I don't think you can pass data to sass. You can look into using styled-components instead or any other CSS in js libraries. With https://www.styled-components.com/docs/basics#adapting-based-on-props, you can pass 'props.data.contentfulHomepage.heroBackgroundImageDesktop.file' to a styled component then you can access that through a props function.

**Comment by cpineda** [comment]
Thanks daydream, I thought as much. I thought there might be some gatsby trickery that could do this. Cheers.

**Comment by KyleAMathews** [comment]
If sass can read JSON, you could write a plugin for gatsby which writes out data which then sass reads in.
