### ISSUE TITLE
Production build: some styles/classes are misapplied when using react-responsive

### ISSUE THREAD

**Issue by owenhoskins** [gatsbyjs/gatsby#5183]
I've been struggling with this for sometime now and have not yet been able to make a simple reproduction because the site was already quiet complex at the point where I recognized the issue.

I am using react-responsive to render a completely different structure for mobile and desktop like so:

```
<Responsive minWidth={1025} values={{width: 1025}}>
>
  <Desktop {...props} />
</Responsive>
<Responsive maxWidth={1024}>
  <Mobile {...props} />
</Responsive>
```

In development mode everything works as expected, but with a production build either locally or on Netlify, a few of the classes & styles from the desktop version are applied to the mobile version at the corresponding point in the DOM tree.

- This __only__ happens when you hit a page directly or refresh a page. 
   - If you navigate away from the page the correct styles will now be applied.
- If you server render the Mobile version the reverse happens where Desktop has styles from Mobile
- If you server render both Mobile and Desktop, then whichever version appears first in the mark-up will have the correct styles where the other will not.
- If you __do not__ server render either version then the issue disappears.

This leads me to a broader question: __what would the best practice be for server rendering a desktop and mobile version for both speed and SEO purposes?__

### Environment

* gatsby@1.9.175
* On Netlify or with gatsby build locally
* gatsby-plugin-glamor __OR__ vanilla css classes & inlined styles

I'll continue to attempt to create a simple reproduction but in the meantime, if this sort of issue rings a bell, or you might have any suggestions, please let me know!

**Comment by ryanditjia** [comment]
What styling method are you using?

**Comment by owenhoskins** [comment]
@ryanditjia I am using gatsby-plugin-glamor but I've completely removed it and refactored with vanilla class names and inline styles but the behavior persists: misapplying styles between Desktop and Mobile at corresponding places in the DOM tree.

I've added more details to the description regarding server rendering with react-responsive ([docs](https://github.com/contra/react-responsive#server-rendering)).

**Comment by ryanditjia** [comment]
I use [react-media](https://github.com/ReactTraining/react-media), which supports server rendering too. Its API doesn’t differ too much from react-responsive’s. Could you give react-media a try and see if the problem persist?

**Comment by owenhoskins** [comment]
@ryanditjia I've just now tested with react-media and it has not solved the issue with the mismatches. 

I did some more digging and the underlying cause is starting to become clearer, I think this issue describes it well: https://github.com/ReactTraining/react-media/issues/81

> I recently had an issue while rehydrating server side rendered markup that contained a react-media component. I'm pretty sure it was because the server side rendered markup was the desktop version and on the client the component immediately rendered the mobile markup when the respective media query matches.

I am now investigating ReactDOM.hydrate and two-pass rendering. It seems like it may be possible to use the new hydrate with gastby v1 if I read this correctly: https://github.com/gatsbyjs/gatsby/issues/2550#issuecomment-385158612

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by owenhoskins** [comment]
Interesting to hear you are facing the same issue @Kadrian. I didn't find a solution per say, but following the advice of this https://github.com/ReactTraining/react-media/issues/81#issuecomment-387810514 I simply stopped trying to server render my components. I am not entirely comfortable with it and would be very interested in a solution which involves responsive server rendering down the line.

**Comment by AndrejGajdos** [comment]
+1

**Comment by am-coding** [comment]
same issue , any solution yet?

**Comment by rkenmi** [comment]
I'm also getting this issue, removing all media queries from react-responsive fixes the styling issue in production build, but develop works fine. Is this a known a issue with SSR?

**Comment by stonix26** [comment]
I'm also getting this issue. It works in develop build, but not in production build. Any solution yet?

**Comment by ChiuMungZitAlexander** [comment]
An easy way to solve - use combination of components together with css.

```javascript
<div className="desktop"></div>
<div className="mobile"></div>
```

```scss
.desktop {
  @media screen and (max-width: 768px) {
    .desktop {
      display: none;
    }
  }
  @media screen and (min-width: 769px) {
    .mobile {
      display: none;
    }
  }
}
```

**Comment by adstr123** [comment]
I am also getting this issue. Below is the output of gatsby info if it's at all helpful - using styled-components and my issue matches the above description exactly (from [this issue](https://github.com/ReactTraining/react-media/issues/81)):

> I recently had an issue while rehydrating server side rendered markup that contained a react-media component. I'm pretty sure it was because the server side rendered markup was the desktop version and on the client the component immediately rendered the mobile markup when the respective media query matches.

```
  System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
  Binaries:
    Node: 14.5.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.3 - /c/Python38/python
  Browsers:
    Chrome: 87.0.4280.66
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.47)
  npmPackages:
    gatsby: ^2.26.1 => 2.26.1
    gatsby-awesome-pagination: ^0.3.6 => 0.3.6
    gatsby-image: ^2.5.0 => 2.5.0
    gatsby-plugin-manifest: ^2.6.1 => 2.6.1
    gatsby-plugin-react-helmet: ^3.4.0 => 3.4.0
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-sass: ^2.5.1 => 2.5.1
    gatsby-plugin-sharp: ^2.8.0 => 2.8.0
    gatsby-plugin-styled-components: ^3.4.0 => 3.4.0
    gatsby-source-contentful: ^2.2.9 => 2.3.52
    gatsby-source-filesystem: ^2.5.0 => 2.5.0
    gatsby-transformer-remark: ^2.10.0 => 2.10.0
    gatsby-transformer-sharp: ^2.6.0 => 2.6.0
  npmGlobalPackages:
    gatsby-cli: 2.14.1
```
