### ISSUE TITLE
Integrate rollbar-browser with gatsby

### ISSUE THREAD

**Issue by apetitdev** [gatsbyjs/gatsby#5188]
## Description

Integrate rollbar-browser with gatsby.

### Steps to reproduce

How to integrate rollbar-browser with gatsby to track errors, log etc..

### Expected result

See the errors, log on rollbar.

### Actual result

Following the search on how to integrate rollbar with react app using webpack https://github.com/rollbar/rollbar.js/issues/221 We can't manage to it with gatsby.

### Environment

* Gatsby version (`npm list gatsby`): 1.9.250
* gatsby-cli version (`gatsby --version`): 1.9.255
* Node.js version: 8.5.0
* Operating System: ubuntu 16.04

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
