### ISSUE TITLE
Moving from create react app to gatsby

### ISSUE THREAD

**Issue by adamwright104** [gatsbyjs/gatsby#5191]
Any documentation or example site on moving a site that is built in create react app to work with gatsby?
Site uses react, redux, router, and contentful cms

**Comment by m-allanson** [comment]
There's no specific guides that I'm aware of, but there's some tutorials on using Contentful with Gatsby that might be useful. 

Check out the following:

- The [`gatsby-source-contentful-plugin`](https://www.gatsbyjs.org/packages/gatsby-source-contentful/)
- [Contentful's Gatsby starter](https://github.com/contentful-userland/gatsby-contentful-starter)
- [Contentful's Gatsby video series](https://www.contentful.com/blog/2018/02/28/contentful-gatsby-video-tutorials/)

I'd love to hear how you get on!

**Comment by Khaledgarbaya** [comment]
Hey, @adamwright104 I am actually working on a blog post to cover that. we'll keep you posted

**Comment by Khaledgarbaya** [comment]
👋the blog post is live [Moving from create react app to Gatsby.js](https://khaledgarbaya.net/articles/moving-from-create-react-app-to-gatsby-js)

**Comment by KyleAMathews** [comment]
@Khaledgarbaya's post is great! Go read that!
