### ISSUE TITLE
GatsbyJS working as a "common" SPA page after build

### ISSUE THREAD

**Issue by ThiagoMiranda** [gatsbyjs/gatsby#5193]
Hi...
Probably is my third question here ( I know that I can be very annoying but we are under some pressure here ) but I have some doubts within the "after build" process.

I´m at my very final stage of development and when I did some SEO tests ( using Chrome plugins to simulate crawlers ) I´ve realized some unexpected behaviors:

My home page has it´s content embed on the static html ( I can see it with view->source ) so it´s almost fine. One thing that bothers me is that my Head and Footer aren´t "static". I don´t know how to make them so. This is my `layout/index.js`

```javascript
const Template = (props) => (
  <I18nextProvider i18n={createI18n} initialLanguage={language ? language[0] : 'pt'}>
    <Fragment>
      <Helmet
        defaultTitle='Site title'
        meta={[
          { name: 'description', content: 'Description content.' },
          { name: 'keywords', content: 'static keywords' }
        ]}
      >
        <link href='https://fonts.googleapis.com/css?family=Lato:300,400,700,900' rel='stylesheet' />
      </Helmet>
      <Header data={props.data} location={props.location} />
      <Body>{props.children()}</Body>
      <Footer />
    </Fragment>
  </I18nextProvider>
)
```
Basically I have the body on the view->source but any of the Header and Footer content ( not even the enclosing tags ). That´s critical because the crawler can´t find any links being stucked at the Home page. 

Another thing is that our other pages ( even though using the very same template structure as the Home )  doesn´t have any static content at all. When I access them directly I have a bunch of css, some json markup and this empty div ( exactly how it is ):
```html
<div id="___gatsby"><main class="main-content"><div></div></main></div>
```
So.. where is the content? Why does the Home page has all the content but other pages doesn´t?

One thing that I´ve saw is that the `gatsbyjs build` produces the pages correctly ( pages/page1/index.html ) but this doesn´t reach the browser ( I´m using netfly temporarily to preview my website but the final version will be using a S3 bucket ). How can I "force" Gatsbyjs to get the static .html page and not a "simple" SPA application?

This is my `gatsbyjs-config.js`:
```javascript
  plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-resolve-src',
    {
      resolve: 'gatsby-plugin-sass',
      options: {
        precision: 8
      }
    },
    'gatsby-plugin-react-next',
    'gatsby-plugin-offline',
    'gatsby-transformer-sharp',
    'gatsby-plugin-sharp',
    'gatsby-plugin-netlify',
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/pages`,
        name: 'pages'
      }
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/assets/images`,
        name: 'img'
      }
    },
    {
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: ['gatsby-remark-component', 
        {
          resolve: 'gatsby-remark-images',
          options: {
            showCaptions: true,
            wrapperStyle: 'margin-right: 0; margin-right: 0;'
          }
        }, 'gatsby-remark-copy-linked-files']
      }
    },
]
```

### PS:
I work in a Bank so I´m a little concerned in expose the preview URL. But if someone wants it to see how it´s working, can tag me here and we find a way to communicate directly. 

Thanks

**Comment by KyleAMathews** [comment]
It seems you're looking at the development version of the site. To preview a production build, run "gatsby build" then "gatsby serve".

**Comment by pfftdammitchris** [comment]
Just to help out with the references, the same issue is posted today at:
https://github.com/gatsbyjs/gatsby/issues/5186

What I found out is that there should be a way for components in the layouts *deeper in the tree* to be rendered in the **page source**, but only html.js is being rendered into the static builds (where your header and footer is missing from). Doesn't react-helmet have support for rendering its metadata to the static builds? Currently it seems like your header and footer is just being injected into the root div ("#___gatsby") in client side which is happening *after* build time.

**Comment by pfftdammitchris** [comment]
@KyleAMathews any idea for this?

**Comment by ThiagoMiranda** [comment]
@KyleAMathews this is the gatbsyjs build outcome not the gatsby develop. The same behavior is happening on my Netflify URL.

**Comment by ThiagoMiranda** [comment]
@pfftdammitchris what I can´t figure is that why only my Home body is being rendered correctly. There´s no real difference between it and the other pages.

**Comment by ThiagoMiranda** [comment]
@pfftdammitchris I´m suspecting that the I18nextProvider is causing this. I´ll run some tests here.

**Comment by ThiagoMiranda** [comment]
@pfftdammitchris @KyleAMathews @pieh Just an update:
I18nprovider ( actually the translate function ) was causing this behavior on the Header and Footer. Now I´m passing directly to the 18nnext my stores. But still getting an "empty div" inside my "non home" page.. Still digging here.

**Comment by pfftdammitchris** [comment]
@ThiagoMiranda does your header and footer have some kind of performance optimization HoC applied to them? Or is one of your pages/layouts implementing a componentDidMount and not rendering on initial load. I found out the page source is viewing more info now that I've taken out some of the performance optimizations. 

Looks like some parts of the app was blocked by these optimizations and was unable to get into the static builds

**Comment by ThiagoMiranda** [comment]
@pfftdammitchris It was exactly that. The i18n was loading the locale file so this wasn't showing in my original DOM.
