### ISSUE TITLE
Should support Surge (and other publish plugins)

### ISSUE THREAD

**Issue by kennethormandy** [gatsbyjs/gatsby#52]
Via #6. Should have the ability to add Surge as an option for deployment.

Right now, `surge token` will give you a token ([example](https://surge.sh/help/integrating-with-travis-ci)) you could use in your config as mentioned in the other issue, but you wouldn’t want it committed to repo, so not sure that’s the best approach. For Surge at least, account creation is implicit, if you aren’t logged in already you will be prompted, so that isn’t necessarily an issue.

**Comment by KyleAMathews** [comment]
I'm going to say deploy plugins are out of scope. It's easy enough to install the Surge (and other deploy options) and add an npm script which runs gatsby build and then deploys.

Let's just add instructions on how to use Surge in the (coming) docs site.
