### ISSUE TITLE
allowing the client to "take over" the initial server loaded page

### ISSUE THREAD

**Issue by ekdev2** [gatsbyjs/gatsby#5217]
Would gatsby accommodate the following scenario? Initially the static page loads with some data (ie. list of friends). Then as the page continues to load a react component will take over and load the same version of friends from a statically generated json file that comes with the build. Basically, I just want the server route (static route) to be a backup for seo initial loading but then the client (react components) to take over and load and interact with json data.

**Comment by pieh** [comment]
This is what Gatsby is doing right now. After page is loaded Gatsby mounts react component, so you have your react app working as any react app.

**Comment by KyleAMathews** [comment]
Also any data you query in pages is made available both for SSR and in the client. So sounds like what you want!

**Comment by ekdev2** [comment]
@KyleAMathews now I'm a little confused. I thought the SSR is the statically generated part so it has static list of friends based on what was generated during the build. Then the client list of friends component can query the json (either from an api or static json file) once it loads.

**Comment by KyleAMathews** [comment]
The client gets the exact same data (based on your graphql query) as SSR. You can optionally query in the client for additional/fresh data from an API.

**Comment by ekdev2** [comment]
@KyleAMathews  Thanks much! this will work great then. We have a relatively large site (few thousand pages) so it will allow us to do incremental builds  of the content through the json files. The we dont have to rebuild the whole site each time a small content change is made. The SSR doesnt have to have the most updated data throughout the day because its good enough for seo. My only concern is if google seo treats us nicely because we're covering up almost identical data with client data that might be different at some point.
