### ISSUE TITLE
Feature: Optional Amp version of build

### ISSUE THREAD

**Issue by chiedo** [gatsbyjs/gatsby#522]
Hey Kyle!

This is just a feature request. One that I may work on myself but wanted to get some thoughts first.

It would be awesome if we could turn on an 'AMP' option for builds.

The 'Amp' option would create an amp version of the site that lived in the public/amp directory and added all the necessary amp changes to the amp version along with the needed additions to the html head section on the normal version of the site.

Interested to hear thoughts. I think Gatsby follows most of the Amp conventions out of the box so it seems doable.

**Comment by KyleAMathews** [comment]
I think this makes a ton of sense :-) A *lot* of people would like AMP support. And yes Gatsby does follow most of the AMP conventions as I modeled a fair bit of Gatsby after their ideas 😂 

Would love to help out with this. I might have a client who'll pay for getting this added but it'd be a little while so feel free to run at it if this is a priority for you.

**Comment by chiedo** [comment]
Awesome!

It's on my todo list. You know how it goes though with paid client work...

Hopefully I can get this added soon. Not a priority but would be pretty darn cool to have an AMP ready site out of the box :)

**Comment by chiedo** [comment]
Worked some on this yesterday and I don't feel like there's any way to automate this in a reliable and user-friendly way unless the Gatsby site was built following very specific conventions.

Between the two sites I did with Gatsby that I tested my ampify-cli implementation in, I got VERY different results.

Here's the question. Do you think I should abandon this or make "standards" that would have to be followed for ampify-cli to work with a Gatsby website?

**Comment by KyleAMathews** [comment]
Hmmm... not sure actually what ampify-cli is (google isn't helping). Perhaps start with creating a simple AMP starter that works and we go from there? I don't think it's realistic to expect every Gatsby site to work so "standards" (or even better, some sort of automated checks system) seems like a better route to go.

**Comment by chiedo** [comment]
Hahaha my bad, 'ampify-cli' was tool I was creating. But I like the Amp starter idea.

I'm going to go that route.

Thanks for the input! :)

**Comment by chiedo** [comment]
Officially made https://labs.chiedo.com Amp ready with an auto script on build time. :)

Just need to whip up a little starter repo now.

**Comment by chiedo** [comment]
Hey @KyleAMathews,

I went ahead and just added the amp build file I put together to your gatsby starter.

https://github.com/gatsbyjs/gatsby-starter-blog/pull/19

**Comment by KyleAMathews** [comment]
@chiedo I wonder if it might be better if your ampify script was its own project that then you could use on any Gatsby (or other site generator) site?

Or perhaps make it its own starter? I like keeping the starters relatively simple and approachable to help out beginners. I worry adding AMP would be confusing as many/most people still don't know what it is.

**Comment by chiedo** [comment]
That makes perfect sense @KyleAMathews 

I tried making it it's own project initially but there are too many variations of how the initial static file structure could be set up, that it would fail on more codebases than it would succeed on.

But it's officially it's own starter:
https://github.com/chiedo/gatsby-amp-starter-blog

Want me to add it to the Gatbsy README and do a PR?

**Comment by KyleAMathews** [comment]
Yeah, that'd be great!

**Comment by chiedo** [comment]
Done!
