### ISSUE TITLE
GraphQL queries return null instead of result with empty edges array

### ISSUE THREAD

**Issue by koluch** [gatsbyjs/gatsby#5226]
## Description

GraphQL queries to connections should return empty results instead of nulls. Current behaviour causes a lot of confustion and null-pointer-errors.

### Steps to reproduce

1. Put `gatsby-source-filesystem` to `gatsby-config.js` 
2. Run query like this:
```
    {
      allFile(filter: {name: {eq: "not_existed_file"}}) {
        edges {
          node {
            name
          }
        }
      }
    }
```

### Expected result

```
{
  "data": {
    "allFile": {
      "edges": []
    }
  }
}
```

### Actual result

```
{
  "data": {
    "allFile": null
  }
}
```

### Environment

* Gatsby version (`npm list gatsby`): 1.9.255
* gatsby-cli version (`gatsby --version`): 1.1.51
* Node.js version: v8.4.0
* Operating System: OS X 10.12.6

**Comment by m-allanson** [comment]
I don't understand your example... why should there be a result if the file doesn't exist?

**Comment by koluch** [comment]
@m-allanson Sorry, I fixed "Expected result" field, it should be an empty array in `edges`.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
