### ISSUE TITLE
[v2] Show GraphQL errors in browser and help debug e.g. by adding link to open bad query in graphiql

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#5234]

**Comment by leimonio** [comment]
👋I was wondering if anyone is working on this, and if I can work on that.

**Comment by leimonio** [comment]
@pieh Just checked the codebase and noticed how the GraphQL errors are currently handled logged in the run instance. Is there any way you'd recommend passing errors to the console?
Maybe something like `utils/test-require-error.js` would work?

**Comment by leimonio** [comment]
Another idea would be to write errors in the `.cache/json/{pageName}.json` instead of the data and with a HOC `console.log` or even display a custom error on screen.

**Comment by pieh** [comment]
@leimonio Do you mean pass from node to browser? Maybe you could reuse websocket that we currently use to transport json data - so emit from `query-runner.js` and listen for those in `cache-dir/root.js` (and pass those errors to error overlay there)

**Comment by leimonio** [comment]
#6247

**Comment by LekoArts** [comment]
Done with https://github.com/gatsbyjs/gatsby/pull/6247
