### ISSUE TITLE
allMarkdownRemark: allow next / previous query

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#5242]
`allMarkdownRemark` currently offers `skip` and `limit`. This makes pagination easy. However there is a related pattern that this doesn't support - being able to query for the next and previous nodes. 

Consider the following;

```
allMarkdownRemark(
      sort: { fields: [frontmatter___date], order: DESC }
      filter: { fields: { type: { eq: "article" } } }
      skip: $startIndex
      limit: $thisGroupSize
```

I can query for all articles by order of date, then use a `startIndex` and `thisGroupSize` to select a subset of the articles. However I cannot select the next article or the previous article. I'm aware that I could pass `next` and `previous` slugs in via the `context`, but my understanding is that we should be doing as much using template/page based queries as possible (vs queries from `gatsby-node`).

Obviously it is possible to find a single node using a slug:

```
markdownRemark(fields: { slug: { eq: $slug } }) 
```

So I'm wondering if it is would be possible to add api to find a node relative to a slug?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
