### ISSUE TITLE
Passing dynamic variable to graphQL

### ISSUE THREAD

**Issue by Neha-takhi-cipl** [gatsbyjs/gatsby#5244]
Hi, I need to pass a dynamic variable to my graphQL Query. I am using a typescript. But i am getting error "expected two arguments but got one".
`My query is `
```
export const queryFragment = graphql`
query fqlQuery1 ($slug: String!) {
    allFile {
      edges {
        node {
          childFaqsJson {
            title
            questions {
              title
              content
            }
          }
        }
      }
    }
    result : faqsJson(fields: { slug: { eq: $slug } }) {
      title
      questions {
        title
        content
      }
    }
  }
`;
// export default injectIntl();
export default graphql(queryFragment, {  _## //--> Here i am getting error, not able to pass two arguments_ 
  options: {
    variables: {
      slug: "/en/faqs/borrower-eligibility/",
    },
  },
})(Faq);
```
`in src/declarations.d.ts`
I have declared the constant like this

`declare const graphql: (query: TemplateStringsArray) => void;`

If I add the queryVariable like this
`declare const graphql: (query: TemplateStringsArray, queryVariable?: any) => void;`
then it give following error 
[ts] Argument of type 'void' is not assignable to parameter of type 'TemplateStringsArray'.
const queryFragment: void

**Comment by goodok21** [comment]
I think that you can't do gatsby graphql query with dynamic variables, but you can use `gatsby-node.js` in root project directory to generate pages.

**Comment by LekoArts** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by martin-braun** [comment]
This was helpful: https://stackoverflow.com/questions/53804219/variables-in-graphql-queries
