### ISSUE TITLE
Is gatsbyjs.org/docs/gatsby-starters/ the best place to find starters? [META QUESTION]

### ISSUE THREAD

**Issue by acomito** [gatsbyjs/gatsby#5246]
I feel like there is an opportunity for selling gatsby starters, but I haven't found them sold anywhere like on themeforest. Is there a more conclusive list/website or is the gatsby-starters list the best resource? Or an awesome-gatsby list? It does seem like the gatsby-starters list is updated pretty regularly, but, I figured I'd ask.

**Comment by m-allanson** [comment]
The starters list on gatsbyjs.org is probably a good place to start. These might be useful:

- https://www.gatsbyjs.org/docs/awesome-gatsby/
- https://www.gatsbyjs.org/blog/2018-02-09-announcing-gatsby-manor-themes-for-gatsbyjs/

There's also discussion around a more comprehensive theme system: https://github.com/gatsbyjs/gatsby/issues/2662

If you find any other useful links, drop them in here too!

**Comment by acomito** [comment]
Thanks! Sorry to clog up the issues with a meta question, but, I'm sure others will have similar questions in the future. Closing it for now unless you want it open.
