### ISSUE TITLE
[gatsby-source-contentful] Unable to filter by reference to a reference

### ISSUE THREAD

**Issue by ouchadam** [gatsbyjs/gatsby#5251]
## Description

Apologies if this is expected behaviour, I was unable to find any information about it. 

`ContentModels` which reference a reference are not available in the `filterContentful{MyModel}Connection`.

Querying works as expected but not filtering.

### Steps to reproduce

Create a content model with a reference to a reference.

![screenshot from 2018-05-03 17-28-21](https://user-images.githubusercontent.com/1848238/39589927-6717b5b4-4ef7-11e8-9d8c-5c12aab44a85.png)

Query
```graphql
fragment slugReference on ContentfulSlug {
  value
}

{
  allContentfulExample {
    edges {
      node {
        slug {
          ... slugReference
        }
        reference {
          slug {
            ... slugReference
          }
        }
      }
    }
  }
}
```

Output
```json
{
  "data": {
    "allContentfulExample": {
      "edges": [
        {
          "node": {
            "slug": {
              "value": "/hello/world/"
            },
            "reference": {
              "slug": {
                "value": "/hello/world/"
              }
            }
          }
        }
      ]
    }
  }
}
```

Working filter
```graphql
  allContentfulExample(filter:{slug:{value: {eq:""}}})
```

Non working filter with reference to reference
```graphql
  allContentfulExample(filter:{reference: {slug:{value: {eq:""}}}})
```

### Expected result

Filtering should have the same fields available as the query.

### Actual result

References to references fields are unavailable when filtering.

![screenshot from 2018-05-03 17-24-25](https://user-images.githubusercontent.com/1848238/39590119-e59dfd62-4ef7-11e8-9205-849c1eb3093b.png)

### Environment

* Gatsby version (`npm list gatsby`): gatsby@1.9.238 
* gatsby-cli version (`gatsby --version`): 1.1.45
* Node.js version: 8.9.4
* Operating System: Arch Linux

**Comment by Khaledgarbaya** [comment]
I think you achieve this using the back reference that was created by Gatsby. 
You can query in a reverse order, first get the reference with the slug you are looking for and include the parent content type.

```
{
  ContentfulSlug(filter:{slug:{value: {eq:"myslug"}}}) {
    edges {
      node {
        slug 
        contentfulExample {
          slug 
          ...
        }
      }
    }
  }
}
```

**Comment by ouchadam** [comment]
Thanks for your help!

I am able to query the rest of the values via the back reference of the filter results parent field name, which in my example is `reference`.

Although `example` is available at the top level, it's always `null`. Is this expected?

```graphql
{
  allContentfulSlug(filter: {value: {eq: "/hello/world/ref/"}}) {
    edges {
      node {
        example {
          id
        }
    	reference {
          example {
            slug {
              value
            }
            reference {
              slug {
                value
              }
            }
          }
        }
      }
    }
  }
}
```
Result

```json
{
  "data": {
    "allContentfulSlug": {
      "edges": [
        {
          "node": {
            "example": null,
            "reference": [
              {
                "example": [
                  {
                    "node_locale": "en-GB",
                    "slug": {
                      "value": "/example/"
                    },
                    "reference": {
                      "slug": {
                        "value": "/hello/world/ref/"
                      }
                    }
                  }
                ]
              }
            ]
          }
        }
      ]
    }
  }
}

**Comment by Khaledgarbaya** [comment]
Hi @ouchadam,
hmm I am not sure I have the answer for that 😅 Maybe Someone else can chime in

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
