### ISSUE TITLE
Enhancement: CrowdIn localization intregration

### ISSUE THREAD

**Issue by ericnakagawa** [gatsbyjs/gatsby#5254]
## Description

The [React](https://reactjs.org/) website uses Gatsby for a fantastic user experience. React's docs are drafted in English, however millions of potential developers outside the US have been asking for ways to make the documentation accessible to non-english speaking audience. Currently, we have much of the site's content almost completely translated by the international community on the [CrowdIn React translation project](https://crowdin.com/project/react).

Crowdin provides free accounts for open source projects. My team at Facebook Open Source has enabled localization on several of our large and growing projects. 

I'd love to see support, guides, or even walkthroughs for adding crowdin localization to gatsby sites like [React](https://reactjs.org/).

**Comment by m-allanson** [comment]
Yes @ericnakagawa! Do you know if there's a write-up on how CrowdIn was implemented on the React website? It'd make a good post for the [Gatsby blog](https://www.gatsbyjs.org/blog) or [tutorial section of the docs](https://www.gatsbyjs.org/docs/).

Also a CrowdIn Gatsby starter could be useful, to join the [existing i18n starters](https://www.gatsbyjs.org/docs/gatsby-starters/). There's also [a long discussion on internationalising Gatsby websites](https://github.com/gatsbyjs/gatsby/issues/3853).

**Comment by KyleAMathews** [comment]
@m-allanson he's looking for help in localizing reactjs.org — they haven't done it yet.

**Comment by m-allanson** [comment]
Ah ok! It'd be great to get examples from someone who's implemented CrowdIn for a Gatsby site.

**Comment by gedeagas** [comment]
@KyleAMathews we are translating it on https://crowdin.com/project/react.

but because there is no official support yet to enable multiple languages in gatsby our hard work translating ReactJS is not yet live in the ReactJS website :(.

**Comment by bvaughn** [comment]
Hi 👋 

Myself and @clemmy worked on integration a bit back in November but were unable to finish. At the time, we created a new Gatsby plug-in, `gatsby-plugin-crowdin`, that we were hoping to get plugged into the ReactJS.org site.

You can see our work in progress here if you'd like:
https://github.com/reactjs/reactjs.org/compare/master...integrate-crowdin

I am planning to spend a little time today and tomorrow trying to bring myself back up to speed on where we left off and what more needs to be done to finish.

**Comment by gedeagas** [comment]
Thank you for your hard work @bvaughn. That is a great news for us. please tell us when it finished

**Comment by clemmy** [comment]
@bvaughn Lemme know if you need some help! I just came back from my grad trip and can use some de-rusting. 😆

**Comment by samajammin** [comment]
@ericnakagawa I'm curious, does React and/or Facebook use CrowdIn for translations? I see you're still the owner of [the React project](https://crowdin.com/project/react) but it looks like you folks may have moved entirely to Github? I would love to learn the approach your taking with Calibra. Appreciate anything you could share :)

**Comment by samajammin** [comment]
I'd also love to know if there's any update on a Gatsby plugin or starter. I searched for both but didn't find any on gatsbyjs.org. Thanks all!

**Comment by bvaughn** [comment]
> I'd also love to know if there's any update on a Gatsby plugin or starter for CrowdIn.

No update on this, unfortunately. I ended up getting distracted by other project. @tesseralis took over the translation/localization efforts for reactjs.org.

**Comment by tesseralis** [comment]
@samajammin we decided on a GitHub-based approach. I'm actually working with Gatsby to do their translations and decided on the same approach. You can see my thoughts here: https://github.com/gatsbyjs/rfcs/pull/42/files

In short:

* Our translations are sourced from the developer community, and most of them prefer Git.
* Crowdin has some trouble handling markdown content, leading to sometimes mismatched tags.
* Crowdin's (English) documentation quality is lacking.
* This approach takes some effort to get started since you need to build automation for it.

It all depends who's doing your translations and what they prefer, and whether you have the dev-power to build that automation (feel free to check React's out at https://github.com/reactjs/reactjs.org-translations

**Comment by samajammin** [comment]
Awesome! I'll look into this. Thank you both.
