### ISSUE TITLE
Disabling cache-busting JS URLs

### ISSUE THREAD

**Issue by lightstrike** [gatsbyjs/gatsby#5262]
Is there a way to disable cache busting URLs for JS bundle files?

I have been trying to use Netlify's [split testing feature](https://www.netlify.com/docs/split-testing/) and have been unsuccessful for two reasons:

1. On first page load, links with `rel="preload"` are randomly assigned along with the main page to a variant, so it's quite common for one or more bundle files to 404.
2. More generally, the use of cache-busting URLs is the core issue here, as there would be no possibility of errors when the app is split between two versions.

A member of the Netlify team pointed out to me that cache-busting URLs should [not be needed with Netlify](https://www.netlify.com/blog/2017/02/23/better-living-through-caching/).

**Comment by m-allanson** [comment]
You'd need to modify Gatsby's webpack config, you can see [JS filenames are specified](https://github.com/gatsbyjs/gatsby/blob/c5ae88be382755997920b7dc51bf3da452e313cd/packages/gatsby/src/utils/webpack.config.js#L120) during Gatsby's `build-javascript` stage. 

The docs on [adding custom webpack configs](https://www.gatsbyjs.org/docs/add-custom-webpack-config/) could be useful here.

**Comment by KyleAMathews** [comment]
I think it's strange of Netlify to say that unique filename URLs isn't necessary. Checking if a file has changed always takes time even if http/2 makes it faster — more importantly, not having unique file names makes SW support a lot more difficult.

>On first page load, links with rel="preload" are randomly assigned along with the main page to a variant, so it's quite common for one or more bundle files to 404.

I don't understand this — Netlify randomly splits up the entire site?

**Comment by lightstrike** [comment]
> I don't understand this — Netlify randomly splits up the entire site?

Only on first page load before a variant cookie is set. I find it really strange too, I did some nginx-driven split testing for Gatsby and the approach I took to get around this was to create a grouped hash based on IP, device type and date. This way the same user always gets all files from the same version.
