### ISSUE TITLE
[Question] How can I use GatsbyJS with reactstrap?

### ISSUE THREAD

**Issue by jonasmarco** [gatsbyjs/gatsby#5263]
Hello everyone,
I'm starting with Gatsby and React :)
I'm tryong to add [Reactstrap](https://reactstrap.github.io/) in my starter template.
So I have, 

`npm install --save reactstrap react react-dom`
`import { Button } from 'reactstrap';`
```
class Header extends Component {
  render() {
    return (
    <Button color="danger">Danger!</Button>      
    );
  }
}

export default Header
```
However, the style isn't showing.. can you help me?
ps: sorry for bad english

**Comment by KyleAMathews** [comment]
You need to add the Bootstrap styles manually. Search for "Adding Bootstrap" on the reactstrap website for their instructions. Good luck!

**Comment by platonish** [comment]
Make sure you've installed bootstrap:
`npm install bootstrap --save`

Then in your index.js:
`import 'bootstrap/dist/css/bootstrap.min.css';`
