### ISSUE TITLE
Can `gatsby develop` *not* include host and port for images?

### ISSUE THREAD

**Issue by achekulaev** [gatsbyjs/gatsby#5264]
I have Gatsby 1.1.51 development server running like this in the docker container

```
gatsby develop --host=0.0.0.0 --port=80
```

I access the site by **another** IP. 
The site is **not** accessible by `0.0.0.0` from my host.

The problem is all the assets that I use 

```javascript
import pic01 from '../assets/images/pic01.jpg'

...

<img src={pic01} alt="" />
``` 

are rendered with hostname in them. 

Like this pic01 will get rendered as `http://0.0.0.0:80/static/pic01.b9959e16.jpg`

---
**Question:**

Can I tell `gatsby develop` to *not* include that hostname and just use relative paths for all assets i.e. `/static/pic01.b9959e16.jpg` ?

**Comment by pieh** [comment]
I'm not sure why (and if) this is needed - but if You would like to try changing it - I think here's place where host is added to paths - https://github.com/gatsbyjs/gatsby/blob/fcc5019cdef96a73f5b0c26343f1678b2e343e48/packages/gatsby/src/utils/webpack.config.js#L90-L92

**Comment by achekulaev** [comment]
Let me know if I can describe the issue better, because I thought my explanations were pretty detailed. 

Re-capping what I said above, it is needed because for `gatsby develop` (Gatsby CLI) the host is `0.0.0.0`, while for my browser the host is `something.locahost` and it's IP is different. This is how Docker or any other Virtual Machine works, it has different IP addresses on the "inside" and on the "outside". 
You have [related issues](https://github.com/gatsbyjs/gatsby/issues/4478) in the issue queue and an [issue](https://github.com/gatsbyjs/gatsby-docker/issues/11) to track possible creation of a Docker image for Gatsby. It will never be possible unless this issue is resolved.

I have taken a look at the piece of code you mentioned. It seems to be related to the JS files, while I have issues with image:

```javascript
import pic01 from '../assets/images/pic01.jpg'
```

will get rendered as `http://0.0.0.0:80/static/pic01.b9959e16.jpg` while I want it to render as `/static/pic01.b9959e16.jpg`

**Comment by achekulaev** [comment]
For the time being I changed the line that pieh advised above. 
From 

```
publicPath: `${program.ssl ? `https` : `http`}://${program.host}:${webpackPort}/`,
```

to

```
publicPath: `/`,
```

It seems to cover all assets including images.

**Comment by dgopsq** [comment]
I have this problem as well. Instead of changing an internal file, a better (but still a workaround I think) solution is adding this piece of code to the `gatsby-node.js` file in the root directory of your project:
```js

exports.modifyWebpackConfig = ({config, stage}) => {
  switch(stage) {
    case 'develop':
      config._config.output.publicPath = `/`;
      break;
  }
};
```

**Comment by hsribei** [comment]
Thanks @dgopsq and @frankf-cgn for the tips. I got it to work by adding this to `gatsby-node.js`:

```javascript
if (process.env.NODE_ENV === 'development') {
  process.env.GATSBY_WEBPACK_PUBLICPATH = '/'
}
```

**Comment by hugo-marques-m3** [comment]
@frankf-cgn That flag is also in V1 afaik.

**Comment by kakadiadarpan** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub issues, we have to clean some of the old issues as many of them have already been resolved with the latest updates.

Please make sure to update to the latest Gatsby version and check if that solves the issue. Let us know if that works for you by adding a comment 👍

**Comment by ivanoats** [comment]
Thank you all for the solutions. I am just commenting in case anyone else searches for this problem. It is the solution I needed to run `gatsby develop` on a cloud server that I connect to from my iPad for development.

**Comment by kennu** [comment]
This is still happening to me when I use `gatsby develop --host 0.0.0.0` to bind the listener to the local network. It doesn't really make sense to load images from http://0.0.0.0 by default in that situation. The workaround by @hsribei works (thanks), but I think the default should be fixed.

**Comment by DSchau** [comment]
@kennu this is likely something different with your personal environment setup.

Does this issue also persist in something like e.g. [create-react-app](https://github.com/facebook/create-react-app)?

**Comment by kennu** [comment]
I realized the project was using an older version of Gatsby, sorry for the trouble. Images are working fine with 2.3.16.

If anyone else stumbles here from google because of the 0.0.0.0 issue, make sure you upgrade Gatsby first.
