### ISSUE TITLE
gatsby-plugin-sass glob?

### ISSUE THREAD

**Issue by kenmallar** [gatsbyjs/gatsby#5265]
Hi there!

Just started to play with Gatsby and its plugin gatsby-plugin-sass and wanted to know if there's anyway to simply import sass files like this npm package:

https://www.npmjs.com/package/gulp-sass-glob

I'd like to use this semantic:
`
// SETUP
@import 'setup/*';

// COMMON
@import 'common/*';

// BLOCKS
@import 'blocks/*';
`
At the moment,  i import my files one by one.
So the code would be cleaner and lighter!

Thanks a lot for your help!

**Comment by pieh** [comment]
You could adjust sass plugin to accept `sass-loader` options and use this - https://www.npmjs.com/package/node-sass-glob-importer

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
