### ISSUE TITLE
Trouble with "gatsby develop" command

### ISSUE THREAD

**Issue by arcarson** [gatsbyjs/gatsby#527]
Hi Kyle,

I've just run into a problem spinning up new projects in Gatsby.

If I run the commands recommended in the README for getting started:

$gatsby new my-test-gatsby-site
$cd my-test-gatsby-site
$gatsby develop

I get an error of:

"wrong type of arguments with: 8000"

This is an issue that is not present in a project that I span up several days ago.

node version: v5.10.1
gatsby version: 0.12.18
osx version: 10.11.6

Cheers,
Andy

**Comment by arcarson** [comment]
I should also mention that the `gatsby build` command works - but the `gatsby serve-build` also returns the same error of "wrong type of arguments with: 8000"

**Comment by KyleAMathews** [comment]
Sorry for the bother — a dependency added a new check that broke things. Fixed in https://github.com/gatsbyjs/gatsby/pull/526 and released in 0.12.19.

**Comment by arcarson** [comment]
Awesome, thanks for the update 😀
