### ISSUE TITLE
Allow to generate non-html files to a subfolder(s)

### ISSUE THREAD

**Issue by szimek** [gatsbyjs/gatsby#5270]
Gatsby generates all non-html files (e.g. `*.js` files, `styles.css` and `chunk-manifest.json` etc.) directly into `public` folder. However, there are some cases where it would be convenient to generate them into a subfolder, or subfolders.

I explained my use case in detail here: https://github.com/gatsbyjs/gatsby/issues/2335#issuecomment-385990241, but the gist is that if one has more than one app available at the same path, e.g. `/`, it would make it much easier to write proxy rules for Gatsby apps, if all html files were e.g. at `/:locale/blog/` and all non-html assets were at `/blog-assets/`, instead of `/`.

There's already a similar ticket https://github.com/gatsbyjs/gatsby/issues/2335.

An alternative is to use `pathPrefix` option, but, at least in my case, it complicates things a lot and not everything works with it correctly, e.g. `serve` command etc.

**Comment by m-allanson** [comment]
Also linking #5271 as it's mentioned above.

**Comment by szimek** [comment]
@m-allanson It does solve my issue, *if* I can select name of the folder in which all non-html files end up. If Gatsby new folder structure end up like `public/js`, `public/css` etc. it doesn't help me much if I want to have more than one Gatsby app, because if I have e.g. a blog app at `/:locale/blog` and other app at `/:locale/hub`, then both apps will generate their js files in `/js/` and I still can't easily figure out which app should handle which request.

If I can set it up, so that all non-html files for the blog app end up e.g. in `public/blog-assets` and for the other app app in `public/hub-assets` and all links to assets in Gatsby are aware of it, then I can create server rules that proxy all requests to `/blog-assets/*.*` to the blog app and `/hub-assets/*.*` to the other app.

If that's what #3760 is proposing, then this ticket can be closed as a duplicate.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
