### ISSUE TITLE
Postcss variables' value is no applied

### ISSUE THREAD

**Issue by haohcraft** [gatsbyjs/gatsby#528]
I need to use my customized postcss' variables and the postcss setting is done [here](https://github.com/haohcraft/mingxiepiano/blob/master/gatsby-node.js). Works fine when in `development`. But those color [variables](https://github.com/haohcraft/mingxiepiano/blob/master/postcss/vars/color.js) are not applied once `build-css`. In this [file](https://github.com/haohcraft/mingxiepiano/blob/master/public/styles.css), search `$color-inactive` you will notice its value is not applied.

Not sure why. No any warning or error thrown.

**Comment by haohcraft** [comment]
so I added the postcss loader in [html.js](https://github.com/haohcraft/mingxiepiano/blob/master/html.js#L21) and it works. Feels like when `build-css`, it picked the default setting of postcss in [prod](https://github.com/gatsbyjs/gatsby/blob/47e0c358bff5fd4f9d532ebd58a76a6e53e76172/lib/utils/webpack.config.js#L380) even though I did not merge [config](https://github.com/haohcraft/mingxiepiano/blob/master/gatsby-node.js) by any environment variable .

**Comment by KyleAMathews** [comment]
Something you could try is running `console.log(compilerConfig.resolve())` in `dist/utils/build-css` to see what the config is.
