### ISSUE TITLE
How to invoke a plugin before the build process start?

### ISSUE THREAD

**Issue by kunxi** [gatsbyjs/gatsby#5289]
Hello,

I have some ipython notebook files I want to integrate them into the gatsby build process. jupyter's `nbconvert` can convert the notebook to Markdown, or HTML either way.

I'd like to use the remark transformer for the sake of consistence. I wonder whether anybody can provide some example or tips how to achieve the following?

- The plugin is invoked to convert the `.ipython` to `.md` and other images once gatsby runs.
- The newly created markdown should be recognized by the source-filesystem.
- They are treated just as other markdown files in the pipeline.

Thanks.

**Comment by pieh** [comment]
> The plugin is invoked to convert the .ipython to .md and other images once gatsby runs.

You can hook into [onPreBootstrap](https://www.gatsbyjs.org/docs/node-apis/#onPreBootstrap) in your `gatsby-node.js` to invoke conversion and write your newly created markdown files. Best return promise there, so gatsby wait for it to finish before moving on to next stages.

> The newly created markdown should be recognized by the source-filesystem.
> They are treated just as other markdown files in the pipeline.

Add `gatsby-transformer-remark` and `gatsby-source-filesystem` pointing to location where you write your converted markdown files.

**Comment by KyleAMathews** [comment]
A point of clarification — transformer plugins shouldn't directly read from the filesystem — instead they should work together with gatsby-source-filesystem — source-filesystem reads files and then transformer plugins transform them — in this case gatsby-source-filesystem would read the .ipython files, your transformer plugins would transform those into IPython nodes w/ probably a child markdown node when then gatsby-transformer-remark would convert to HTML.
