### ISSUE TITLE
remark table alignments not working

### ISSUE THREAD

**Issue by foreverfighter** [gatsbyjs/gatsby#5290]
## Description

Table alignments using colons should work properly when using gatsby-transformer-remark.

### Steps to reproduce

You can see it on even the gatsbyjs site.
https://using-remark.gatsbyjs.org/hello-world-kitchen-sink/

### Expected result

Center- and right-aligns should work properly.

### Actual result

They are all left-aligned.

### Environment

* Gatsby version (`npm list gatsby`):  gatsby@1.9.255
* gatsby-cli version (`gatsby --version`): 1.1.51
* Node.js version: 6.0.0
* Operating System: Win10

**Comment by pieh** [comment]
Yeah, you are right. Not sure if this is `remark` issue and should be reported upstream, would need someone to investigate.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
