### ISSUE TITLE
Question: Double script import in build?

### ISSUE THREAD

**Issue by wemyss** [gatsbyjs/gatsby#5303]
Hi, New here! Really enjoying the hard work that has been put into the project thus far 😸

## Description

I've been experiencing multiple script imports of the same file in the `index.html` outputted by `gatsby build`.

### Steps to reproduce

1. `﻿gatsby new site` 
2. `cd site`
3. `gatsby build` (doesn't happen in `develop`)
4. Open up `public/` using a simple server and view in browser, see multiple resources being loaded twice.

### Expected result

Resources should only be loaded once? Not sure if there is some reason why they are done twice 

### Actual result

They get loaded twice.
<img width="1083" alt="screen shot 2018-05-07 at 12 41 13 am" src="https://user-images.githubusercontent.com/8426915/39674492-1ccc2bfc-5190-11e8-946c-507101488f50.png">

### Environment

* Gatsby version (`npm list gatsby`): gatsby@1.9.250
* gatsby-cli version (`gatsby --version`): 1.1.51
* Node.js version: 9.11.1
* Operating System: OSX

### File contents (if changed):

NA

**Comment by pieh** [comment]
To my knowledge, double script imports doesn't cause double script loading. And we do have doubled scripts import because first ones are written to html files, so it start fetching them as fast as possible on browsers that don't supporting link preloads. Second "copies" of scripts are caused by webpack runtime that adds those dynamically to `<head>` (you can view html to see there are not there initially) when we want to load them (that's how we prefetch needed data and components for pages that user might go next).

**Comment by KyleAMathews** [comment]
Agree with @pieh that this shouldn't be a problem as the browser dedupes requests. Could you check the network tab in your browser dev tools to verify that there isn't multiple downloads happening?

**Comment by wemyss** [comment]
@KyleAMathews yeah that's what confused me initially, as firefox displays it's loading both, while chrome does not 😕 
Firefox:
<img width="1378" alt="screen shot 2018-05-08 at 11 10 10 am" src="https://user-images.githubusercontent.com/8426915/39732642-e3aa4444-52b1-11e8-861c-3934a661fe1d.png">

Chrome:
<img width="1087" alt="screen shot 2018-05-08 at 11 11 04 am" src="https://user-images.githubusercontent.com/8426915/39732624-cc3fbfdc-52b1-11e8-9d61-be14ef48a862.png">

**Comment by KyleAMathews** [comment]
Oh interesting — that's not good.

**Comment by wemyss** [comment]
Sorry just updated my comment. So I don’t think it’s an issue, just Firefox being a bit weird.

**Comment by GuillaumeAmat** [comment]
Hi there 👋

Actually, if you have several script tags with the same source file, it will be loaded once **but**, it will be parsed and executed at each call... (more on that [here](https://calendar.perfplanet.com/2014/the-pain-of-duplicate-scripts)).

What about putting only one script tag and add a <link rel="preload" href="[...]"/> to properly preload it as soon as possible?

cc @KyleAMathews @pieh @wemyss
