### ISSUE TITLE
request: Automatically Map Generic HTML Elements Rendered By Markdown To React Components

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#5306]
It would be great if gatsby offered a way to map generic html elements generated from markdown to React components. For example an h3 declared in markdown:

```
### Example
```

Could be mapped to:

```
const tertiaryTitle = styled.h3``
```

This wouldn't require anything extra in the markdown, just a map somewhere mapping html element to React component. 

This particularly makes sense when used with styled components (or a similar js-in-css solution). 

This is a much better solution than relying on descendent selectors for html generated from markdown, as it allows the same styles/components to be shared between parts of the site rendered directly from react components with elements rendered from markdown. 

Note that this is a different request from #312 which calls for explicit declaration of components (which is also outlined in the [docs](https://using-remark.gatsbyjs.org/custom-components/) for custom components which again require explicit declaration of components.

**Comment by pieh** [comment]
I'm not familiar with custom components in markdown but can't you use same technique as in linked docs for replacing html elements to react components:
```js
const renderAst = new rehypeReact({
  createElement: React.createElement,
  components: { "h3": tertiaryTitle },
}).Compiler;
```
?

**Comment by Undistraction** [comment]
@pieh Thanks. You are correct - it also works with generic HTML elements. I'll add a note about this to the docs to make it explicit.
