### ISSUE TITLE
gatsby build stuck on createPages - gatsby wordpress starter

### ISSUE THREAD

**Issue by aks84** [gatsbyjs/gatsby#5307]
I have been trying this for some time, unfortunately had no luck. Please help! Thanks!

Also, there was no Wordpress Tags on my website, it was throwing an error. So, I create two tags and it got fetched.

### Stuck on createPages

- `source and transform nodes -> wordpress__POST fetched : 25
- ⢀ source and transform nodes -> wordpress__PAGE fetched : 6
- ⢀ source and transform nodes -> wordpress__wp_media fetched : 44
- ⠂ source and transform nodes -> wordpress__wp_types fetched : 1
- ⠂ source and transform nodes -> wordpress__wp_statuses fetched : 1
- ⠐ source and transform nodes -> wordpress__wp_taxonomies fetched : 1
- ⢀ source and transform nodes -> wordpress__CATEGORY fetched : 11
- ⢀ source and transform nodes -> wordpress__TAG fetched : 2
- ⠂ source and transform nodesThe server response was "403 Forbidden"
- ⢀ source and transform nodesThe server response was "401 Unauthorized"
- Inner exception message : "You are not currently logged in."
- ⡀ source and transform nodes -> wordpress__wp_comments fetched : 0
- ⠐ source and transform nodesThe server response was "401 Unauthorized"
- Inner exception message : "Sorry, you are not allowed to do that."
- success source and transform nodes — 46.407 s
- success building schema — 2.282 s
- success createLayouts — 0.257 s
- ⢀ createPages

`

**Comment by gapgag55** [comment]
Do you put resolve() after createPages()?

**Comment by gapgag55** [comment]
Do you put resolve() after createPages()?

For example,

`
exports.createPages = ({ graphql, boundActionCreators }) => {
const { createPage } = boundActionCreators;

return new Promise((resolve, reject) => {
createPage({
path: '/video/'.concat(node.slug),
component: path.resolve('./src/templates/video.jsx'),
context: {
slug: node.slug,
},
});
resolve()
}`

**Comment by dvdslns** [comment]
@aks84 I was having the same issue and @gapgag55's solution worked for me.

Added `resolve()` to the gatbsy-node.js file, just after line 128 (`// === END TAGS ===`).

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
