### ISSUE TITLE
ValidationError: child "id" fails because ["id" must be a string]

### ISSUE THREAD

**Issue by humphreybc** [gatsbyjs/gatsby#5310]
## Description

When using `gatsby-source-filesystem` and `gatsby-transformer-json`, if your JSON objects have an `id` key, with a number instead of a string, you’ll get the following error for each node:

```sh
ValidationError: child "id" fails because ["id" must be a string]
```

### Steps to reproduce

1. Install `gatsby-source-filesystem` and `gatsby-transformer-json`
1. Create a file under `./src/data/posts/posts.json`,
1. In `posts.json`, add an object with an id key with the value as a number (e.g. `"id": 42`)
1. Run `gatsby develop`
1. Get the error above

The solution is to use strings, instead of numbers for id.

### Expected result

No validation error since number values are valid JSON.

### Actual result

```sh
ValidationError: child "id" fails because ["id" must be a string]
```

### Environment

* Gatsby version (`npm list gatsby`): 1.9.259
* gatsby-cli version (`gatsby --version`): 1.9.259
* Node.js version: 9.4.0
* Operating System: MacOS High Sierra 10.13.4

### File contents

Only including relevant details.

`package.json`:

```json
{
  "dependencies": {
    "gatsby": "^1.9.259",
    "gatsby-link": "^1.6.40",
    "gatsby-plugin-canonical-urls": "^1.0.18",
    "gatsby-plugin-google-analytics": "^1.0.29",
    "gatsby-plugin-manifest": "^1.0.20",
    "gatsby-plugin-nprogress": "^1.0.14",
    "gatsby-plugin-react-helmet": "^2.0.10",
    "gatsby-plugin-react-next": "^1.0.11",
    "gatsby-plugin-remove-trailing-slashes": "^1.0.9",
    "gatsby-plugin-robots-txt": "^1.0.1",
    "gatsby-plugin-sentry": "^0.0.4",
    "gatsby-plugin-sharp": "^1.6.42",
    "gatsby-plugin-sitemap": "^1.2.22",
    "gatsby-plugin-typescript": "^1.4.19",
    "gatsby-remark-images": "^1.5.61",
    "gatsby-source-filesystem": "^1.5.31",
    "gatsby-transformer-json": "^1.0.17",
    "gatsby-transformer-remark": "^1.7.39",
  }
}
```

**Comment by pieh** [comment]
`id` is special case for gatsby and it needs to be string. I would suggest trying to add extra handling for that in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-json/src/gatsby-node.js lines 40 and 47 - that if `id` is preset and is not a string that it should convert to string. 

Better yet save `id` from json to field like like `original_id` and use `createNodeId` for creating valid and globally unique id (which would be breaking change, so would need major version bump)

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
