### ISSUE TITLE
Gatsby doesn't redirect in the browser on the initial render which means a 404 is temporarily shown

### ISSUE THREAD

**Issue by imarem** [gatsbyjs/gatsby#5312]
Hi,

I 'have a project when I have to required create redirects to old pages, caused by renaming de slug. When I create the redirect, like this:

```
  createRedirect({
    fromPath: `/contact`,
    isPermanent: true,
    redirectInBrowser: true,
    toPath: `/contacto`,
  })
```
In gatsby-node.js, in dev mode works fine, but when I deploy it in Netlify, only apears the "404" page.

There's a special configuration for running together custom redirects and the 404 default redirect?

I'll apreciate your help.

Thanks!!

**Comment by KyleAMathews** [comment]
You need to install https://www.gatsbyjs.org/packages/gatsby-plugin-netlify/?=netlify

For redirects to be handled by a server — you have to write out information specific for that server so it knows how to handle redirects.

**Comment by imarem** [comment]
Hi @KyleAMathews 

Of course I already use gatsby-plugin-netlify. The problem is that before doing the redirection to the desired page, it passes momentarily through the 404. I have validated that the redirections are correctly configured through https://play.netlify.com/redirects, and are resolved correctly with a 301. But as I commented, before it shows a few seconds the 404.

Do I have to configure something around Gatsby and so the regex aplied to 404, for takes the custom redirects considerations created?

Thanks in advance.

**Comment by KyleAMathews** [comment]
Are you using a service worker?

**Comment by imarem** [comment]
@KyleAMathews 

Yes!! Can there be problems with the cache?

**Comment by KyleAMathews** [comment]
Try an incognito window. When you have a sw installed, your browser doesn't make a request to the server.

That being said, this is a big because we should do the redirect before trying to render a page so I'll reopen this.

**Comment by imarem** [comment]
@KyleAMathews 

You were right! I clean the sw, and redirects works fine.

Thanks again for all,

**Comment by KyleAMathews** [comment]
I'll create a separate issue for the underlying problem
