### ISSUE TITLE
gatsby-remark-autolink-headers: Page jump on scrolling to anchor links

### ISSUE THREAD

**Issue by sidoshi** [gatsbyjs/gatsby#5314]
## Description

`gatsby-remark-autolink-headers` adds a [script](https://github.com/gatsbyjs/gatsby/blob/10a1fafc385c56d73f71d57bbf3706750162a8ef/packages/gatsby-remark-autolink-headers/src/gatsby-ssr.js#L39-L53) to scroll to the anchor. The issue is since the native browser event is also fired, it takes to target to complete top and then the above script adds the offset which leads to a jumping effect
![jumpy](https://user-images.githubusercontent.com/23718874/39700410-c0417d7a-521a-11e8-84e9-39d953aa749f.gif)
.

### Steps to reproduce

Visit this [page](https://reactjs.org/tutorial/tutorial.html#prerequisites) and click on anchor link to see it

### Expected result

The native click event needs to be somehow prevented from firing.

**Comment by sidoshi** [comment]
Not sure if its something to fix because most of the time, it does not jump on first click, But it gets annoying when it does.

**Comment by sidoshi** [comment]
There are two different issues here. The [SSR](https://github.com/gatsbyjs/gatsby/blob/10a1fafc385c56d73f71d57bbf3706750162a8ef/packages/gatsby-remark-autolink-headers/src/gatsby-ssr.js#L39-L53) script that scrolls to the target element on load is broken. 

For eg, when this [link](https://reactjs.org/docs/hello-world.html#a-note-on-javascript) on the react site is visited for the first time, the offset is calculated from the top of the screen and hence it overlaps with the fixed header. Further, when we scroll away and refresh the page, it does not take back to the target.
![may-07-2018 23-46-31](https://user-images.githubusercontent.com/23718874/39717441-e5962338-5250-11e8-8ae6-4eee06cc44fc.gif)

I am not sure what causes this wierd behaviour on the initial load. But on next refreshes, the problem seems to be that the scroll function is called too early. I have verified the using the `load` event instead of `DOMContentLoaded` solves this issue.  Though it still creates a jumpy effect.

The other issue is when we click on a link on a loaded page, It goes all the way to the top and then offsets back. Currently we use [`onRouteUpdate`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-autolink-headers/src/gatsby-browser.js#L27-L34) to set the offset. But, as you said, we could instead listen for click events on all the `a` elements that target an internal element, call `e.preventDefault` and manually scroll that element to view.

**Comment by TomPichaud** [comment]
The SSR script seems ok so the bug must be within Gatsby, `getElementById`can't find the element even know we are listening to `DOMContentLoaded`. Tested in V1 and V2. @KyleAMathews any hints ?

**Comment by zslabs** [comment]
Found this issue after dealing with quite an odd one on my end. Using `tableOfContents` from MarkdownRemark and here's what I'm seeing:

![kapture 2018-10-12 at 12 07 22](https://user-images.githubusercontent.com/1018402/46880712-6a6e8e00-ce17-11e8-92fb-28cbafdb1843.gif)

Then links generated by that property are just simple anchor links, but also noticed that refreshing the page with a hash isn't scrolling down to where it needs to. I do see

```

    document.addEventListener("DOMContentLoaded", function(event) {
      var hash = window.decodeURI(location.hash.replace('#', ''))
      if (hash !== '') {
        var element = document.getElementById(hash)
        if (element) {
          var offset = element.offsetTop
          // Wait for the browser to finish rendering before scrolling.
          setTimeout((function() {
            window.scrollTo(0, offset - 16)
          }), 0)
        }
      }
    })
  ```

But I'm wondering if this has something to do with it... really confused on why a simple anchor link is getting confused. When I run `gatsby build`, I can see a flicker of the right element being pushed to the top of the screen, but then it reverts to the wrong position again. Here's my `gatbsy-config` around this area:

```
{
  resolve: 'gatsby-transformer-remark',
  options: {
    excerpt_separator: '<!-- end -->',
    plugins: [
      'gatsby-remark-relative-images-v2',
      {
        resolve: 'gatsby-remark-images',
        options: {
          maxWidth: 1000,
          linkImagesToOriginal: false,
          quality: 75,
        },
      },
      {
        resolve: 'gatsby-remark-autolink-headers',
        options: {
          offsetY: 16,
        },
      },
      'gatsby-remark-prismjs',
    ],
  },
},
```

**Comment by DSchau** [comment]
@zslabs would you be able to provide a link to the repo or some other way to reproduce? [reactjs.org](https://reactjs.org/tutorial/tutorial.html#what-is-react) follows a similar approach (e.g. a sidebar linking to anchor tags) and it seems like it works just fine!

**Comment by zslabs** [comment]
@DSchau This ended up being a very specific issue to my setup; not Gatsby-derived at all, a very odd CSS thing that I dare not recite 💪

Sorry for the false alarm!
