### ISSUE TITLE
Typescript: gatsby-browser not picked up after Gatsby Update

### ISSUE THREAD

**Issue by iv-mexx** [gatsbyjs/gatsby#5317]
## Description

I have a fully working project using Typescript and Gatsby 1.9.127. Now I wanted to update Gatsby to the newest version (1.9.259) but after doing so, `gatsby-browser.tsx` is not compiled anymore and so my site does not work anymore. 

This also is the case if I use a fresh project based on [this starter](https://github.com/resir014/gatsby-starter-typescript-plus)

### Steps to reproduce

* Create new Gatsby Project based on [gatsby-starter-typescript-plus](https://github.com/resir014/gatsby-starter-typescript-plus)
* Create `gatsby-browser.tsx` in root directory
* Add something to `gatsby-browser.tsx`, e.g.: 

```
console.log('Hello');

exports.onInitialClientRender = () => {
  console.log('ReactDOM.render has executed!!!')
}
```

### Expected result

* `gatsby-browser.tsx` should be compiled, code in the file should run
  * Browser Console should show the log messages

### Actual result

* `gatsby-browser.tsx` is not compiled, code is not run
  * Browser Console does not show the log messages

### Note

If `gatsby-browser` is not written in typescript (`gatsby-browser.js`), it works as expected.

### Environment

* Gatsby version (`npm list gatsby`): gatsby@1.9.259
* gatsby-cli version (`gatsby --version`): 1.1.20
* Node.js version: v10.0.0
* Operating System: macOS High Sierra 10.13.4 (17E202)

### File contents (if changed):

`gatsby-config.js`: **no changes from starter project**
`package.json`: **no changes from starter project**
`gatsby-node.js`: **no changes from starter project**
`gatsby-browser.js`: **changed to .tsx**
`gatsby-browser.tsx`

```
console.log('Hello');

exports.onInitialClientRender = () => {
  console.log('ReactDOM.render has executed!!!')
}
```

`gatsby-ssr.js`: **no changes from starter project**

**Comment by alvis** [comment]
What was your setting to compile `gatsby-browser.tsx` in gatsby 1.9.127?

`gatsby-plugin-typescript` doesn't cover API files such as `gatsby-config`, `gatsby-browser` etc.
To use typescript on these files, you need a transpiler placed in front of `gatsby`, e.g. 
```
babel-node --presets @babel/preset-typescript --extensions '.ts,.tsx' gatsby develop
```

**Disclaimer**: I'm the author of another typescript starter (WIP) for gatsby: 
https://github.com/alvis/barebone-webapp

There are a few things broken at the moment, but it should work to some extent out of the box.

**Comment by iv-mexx** [comment]
Honestly - I don't know how it worked before. I've used the aforementioned starter and it just worked. 
I assumed that this was as intended and supported by Gatsby (or by `gatsby-plugin-typescript`). 

I'll checkout your starter

**Comment by calcsam** [comment]
@iv-mexx -- were you able to resolve this?

**Comment by iv-mexx** [comment]
No, that project is only semi active, and I did not have the time to look into this further. Currently, I'm still using the old version of Gatsby where this still worked.
