### ISSUE TITLE
Using imageSharp and Wordpress

### ISSUE THREAD

**Issue by b0gd4n** [gatsbyjs/gatsby#5318]
Hey,

I've been trying to get imageSharp to work with images polled from WordPress posts.

My current query is as follows:

```allWordpressPost {
      edges {
        node {
          title
          slug
          link
          content
          author {
            name
          }
          featured_media {
            source_url
          }
        }
      }
    }

The I am using `source_url` to generate the image url to get the image from WordPress - is there a way of getting this to work with imageSharp?

Thanks

**Comment by pieh** [comment]
Check https://www.gatsbyjs.org/packages/gatsby-source-wordpress/#image-processing

**Comment by b0gd4n** [comment]
hey @pieh - I saw that, however when I tried adding the `localFile` part to my query I get `GraphQL Error Unknown field `localFile` on type `wordpress__wp_media``

**Comment by sarahannnicholson** [comment]
Yes, also seeing this same issue I didn't find what I'm doing wrong by looking at the [gatsby docs](https://www.gatsbyjs.org/packages/gatsby-source-wordpress/#image-processing). 

I wonder if there's something on WordPress that needs to be enabled?

**Comment by sever1an** [comment]
The `exports.downloadMediaFiles` is for `gatsby-source-wordpress` to use as a plugin and will not work in `gatsby-node.js`
