### ISSUE TITLE
⡀ Building static HTML for pagesKilled

### ISSUE THREAD

**Issue by decimoseptimo** [gatsbyjs/gatsby#5321]
Hi, instead of SFTPing, I'm trying to build in production server, these are my steps:
```
git clone ...
npm install
gatsby build
```

It's failing throwing:
```
...
info bootstrap finished - 3.324 s

success Building CSS — 4.108 s
success Building production JavaScript bundles — 10.445 s
⡀ Building static HTML for pagesKilled
```
This isn't happening in my development machine, where the build succeeds.

server versions:
```
$ gatsby -v
1.1.51
$ node -v
v8.11.1
$ npm -v
5.6.0
$ npm list gatsby
gatsby-starter-hello-world@ /home/...
└── gatsby@1.9.250
```

Can I get more insight in what that error means? there doesn't seem to be much info available.

**Comment by decimoseptimo** [comment]
I retried. It seems that `gatsby build` is non-deterministic.

It can also throw:
```
info bootstrap finished - 3.151 s

success Building CSS — 4.180 s
success Building production JavaScript bundles — 9.458 s
error UNHANDLED EXCEPTION


  RangeError: Array buffer allocation failed

  - new ArrayBuffer

  - typedArrayConstructByLength

  - new Uint8Array

  - png.js:20 new exports.PNG
...
```

And it can also succeed:
```
...
success Building static HTML for pages — 21.174 s
info Done building in 39.171 sec
```

🤔

**Comment by m-allanson** [comment]
Hey @decimoseptimo it's difficult to say what's happening here. The first error looks like something external to Gatsby has killed the Gatsby process. The second could be some kind of memory allocation error?

Can you replicate the environment of your production server in a virtual machine (or similar?).

**Comment by decimoseptimo** [comment]
I'm thinking perhaps `gatsby build` is an expensive process, and the machine is underpowered (DO 1GB VPS).

**Comment by dov-yih** [comment]
I had a similar problem:

```
⠄ Building production JavaScript and CSS bundles
Killed
```

It works will on my PC, But failed on VPS. And my VPS's memory  is 2G. I think that 8G mey be enough.

**Comment by tryzniak** [comment]
Could you provide the output of a
‘gatsby info’ command?
