### ISSUE TITLE
Hot Reload Intermittent Error / GraphQLError: Cannot read property 'parent' of undefined

### ISSUE THREAD

**Issue by chibicode** [gatsbyjs/gatsby#5323]
## Description

My blog ([source](http://github.com/chibicode/chibicode)) keeps getting this error on **hot reload** after 20-50 hot reloads - not sure exactly how to reproduce it.

```
Errors:
  GraphQLError: Cannot read property 'parent' of undefined
URL path:
   /posts/...
Plugin:
  Plugin default-site-plugin
```

The error happens on `PostTemplate`, which is used by `createPage`. I'm using `allMarkdownRemark` because I want to show all other posts on a single post page.

Here's the query:

```js
export const pageQuery = graphql`
  query PostBySlugQuery($slug: String!) {
    site {
      siteMetadata {
        title
        author
        siteUrl
      }
    }
    allMarkdownRemark(sort: { fields: [frontmatter___date], order: DESC }) {
      edges {
        node {
          htmlAst
          excerpt
          fields {
            slug
          }
          frontmatter {
            date(formatString: "MMMM DD, YYYY")
            title
            draft
            tags
            imageAttributionName
            imageAttributionUrl
            twitterId
            image {
              childImageSharp {
                width1200: resolutions(width: 1200, quality: 80) {
                  height
                  src
                  width
                }
                width1000: sizes(maxWidth: 1000, quality: 80) {
                  aspectRatio
                  base64
                  sizes
                  src
                  srcSet
                }
              }
            }
          }
        }
      }
    }
    markdownRemark(fields: { slug: { eq: $slug } }) {
      id
      htmlAst
      excerpt
      fields {
        slug
      }
      frontmatter {
        title
        date(formatString: "MMMM DD, YYYY")
        dateRaw: date
        imageAttributionName
        imageAttributionUrl
        twitterId
        draft
        tags
        image {
          childImageSharp {
            width1200: resolutions(width: 1200, quality: 80) {
              height
              src
              width
            }
            width1000: sizes(maxWidth: 1000, quality: 80) {
              aspectRatio
              base64
              sizes
              src
              srcSet
            }
          }
        }
      }
    }
  }
`

```

Here's my [gatsby config](https://github.com/chibicode/chibicode/blob/master/gatsby-config.js) and [gatsby node](https://github.com/chibicode/chibicode/blob/master/gatsby-node.js).

* Gatsby version (`npm list gatsby`): 1.9.259
* gatsby-cli version (`gatsby --version`): 1.9.259
* Node.js version: 9.7.1
* Operating System: macOS 10.13.4

It'd be great if someone could point me to how to debug this error... I don't even know which code is running `.parent`.

**Comment by m-allanson** [comment]
Urgh, intermittent errors are the worst. 

`default-site-plugin` is the name given to the `gatsby-x.js` files in the root of your project. So it sounds like the error could be occurring when running your `gatsby-node.js` file.

That particular error is created in [Gatsby's query runner](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/internal-plugins/query-runner/query-runner.js#L34). There's an [open PR](https://github.com/gatsbyjs/gatsby/pull/5214) for adding more info to that error, which could be useful. 

You can either dive into the transpiled JS in `node_modules/gatsby/dist/internal-plugins/query-runner/query-runner.js`, or set up a [local Gatsby dev environment](https://www.gatsbyjs.org/docs/how-to-contribute/#contributing-to-the-repo) to make changes to your Gatsby instal.

**Comment by pieh** [comment]
`parent` reference there gives 2 potential guesses where this could fail:
- it could happen here - https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/types/type-file.js#L167
- or here - https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-sharp/src/extend-node-type.js#L196 / https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-sharp/src/extend-node-type.js#L304 

in any case as this doesn't happen all the time, it would probably mean that Gatsby tries to resolve fields during some kind of bad state, where node is not defined :/

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
