### ISSUE TITLE
How to add/post data in mongoDB using gatsby-source-mongodb plugin

### ISSUE THREAD

**Issue by yug95** [gatsbyjs/gatsby#5326]
## Description

Describe the issue or the enhancement that you want to see.

### Steps to reproduce

Clear steps describing how to reproduce the issue.

### Expected result

What should happen?

### Actual result

What happened.

### Environment

* Gatsby version (`npm list gatsby`):
* gatsby-cli version (`gatsby --version`):
* Node.js version:
* Operating System:

### File contents (if changed):

`gatsby-config.js`: 
`package.json`: 
`gatsby-node.js`: 
`gatsby-browser.js`: 
`gatsby-ssr.js`:

**Comment by m-allanson** [comment]
Hey @yug95, generally source plugins are for reading data from a source at build time. If you want to push data once your site has built, you'll need to do that however you'd normally handle pushing data in your apps. Have a look at the docs on [Building Apps with Gatsby](https://www.gatsbyjs.org/docs/building-apps-with-gatsby/).

I'm going to close this. Please open a new issue (and fill out the issue template) if you have a more specific question.
