### ISSUE TITLE
[gatsby-react-router-scroll] Need undocumented config ?

### ISSUE THREAD

**Issue by gnuletik** [gatsbyjs/gatsby#5332]
Hi, I'm new to Gatsby and I wanted to use the gatsby-react-router-scroll to keep scroll position on a page.

I found it quite tricky to use.

## What I expected to work
So, this is how I expected it to work
```
yarn add gatsby-react-router-scroll
```

```
import React, { Component } from 'react'
import { ScrollContext } from 'gatsby-react-router-scroll'

export default Page extends React.Component {
    render() {
        <ScrollContext>
            <SomeComponent />
        </ScrollContext>
    }
}
```

## First issue

By default Gatsby call window.scrollTop(0, 0) on every page.
So the component behavior is overriden.
I needed to configure `gatsby-browser.js` to not scroll on my page.

```
exports.shouldUpdateScroll = ({prevRouterProps, pathname}) => {
    if (pathname === '/menu') {
        return false
    } else {
        return true
    }
}
```
## Second issue
scroll-behavior (which is a dependency) is using `window` before checking it.
So, the HTML build failed.

To avoid this, I needed to use a wrapper around ScrollContext like:
```
import React, { Component } from 'react'
import { ScrollContext } from 'gatsby-react-router-scroll'

// Wrapper
class Scroll extends Component {
    render() {
        let { children } = this.props
        if (typeof window !== 'undefined') {
            return <ScrollContext>{children}</ScrollContext>
        } else {
            return children
        }
    }
}

Scroll.propTypes = {
    children: PropTypes.node
}

export default Page extends React.Component {
    render() {
        <Scroll>
            <SomeComponent />
        </Scroll>
    }
}

```

Is there something wrong in the way I use it ?
If not, could this be done in gatsby instead ?

gatsby@1.9.259
gatsby-react-router-scroll@1.0.17
node v9.11.1
GNU/Linux

**Comment by m-allanson** [comment]
Hey @gnuletik, what you're doing looks pretty close I think. `gatsby-react-router-scroll` is included automatically by Gatsby, so you don't need to add it as a dependency.

> I needed to configure gatsby-browser.js to not scroll on my page.

You will need to do this to override the default behaviour

> To avoid this, I needed to use a wrapper around ScrollContext like:

You can remove `import { ScrollContext } from 'gatsby-react-router-scroll'` and remove any use of `<ScrollContext>` as Gatsby add this for you.

Does that help?

**Comment by gnuletik** [comment]
Hey @m-allanson !
Thanks for your response.

I tried to removing ScrollContext but my scroll position don't get saved.
Here is how I try:
1. Scroll on page menu
2. Go to some other page (scroll position go to the top, that's expected)
3. Click on menu link
4. On page menu the scroll position is at the top (what I expect is to be at position of 1.)

**Comment by crickford** [comment]
Had a similar issue, found the solution in the react-router-scroll documentation: https://github.com/ytase/react-router-scroll#scrolling-elements-other-than-window
Bottom line: use `ScrollContainer` rather than `ScrollContext`.

Perhaps this could be added to the Gatsby documentation? A note or link from here might be helpful for others with this issue: https://www.gatsbyjs.org/docs/browser-apis/#shouldUpdateScroll

**Comment by tinoguti** [comment]
I am having a lot of issues with Gatsby and the scroll position management. Documentation around the web is unclear and quite confusing. In my current situation I have a Gatsby project and what I actually need is the normal browser behavior where every time you click on a link you are redirected to that page and scrolled to the top, but somehow the scroll position its not being restarted and the scroll position ends up somewhere else. Which is quite annoying as it seems like a random position.
Any link, documentation, solution for this?
Thanks
