### ISSUE TITLE
WP Netlify webhook not triggering

### ISSUE THREAD

**Issue by b0gd4n** [gatsbyjs/gatsby#5333]
I have a Netlify webhook ready and added this to the end of the `functions.php` file:

```
add_action( 'save_post', 'fireFunctionOnSave' );
function fireFunctionOnSave($post_id)
{
  if(wp_is_post_revision( $post_id) || wp_is_post_autosave( $post_id )) {
    return;
  }
    $curl = curl_init( 'https://api.netlify.com/build_hooks/123123123' );
    curl_setopt( $curl, CURLOPT_POST, true );
    curl_setopt( $curl, CURLOPT_RETURNTRANSFER, true );
    $response = curl_exec( $curl );
    curl_close( $curl );
}
```

After adding/deleting/updating a post, it does not trigger any builds - what am I missing?

Thanks

**Comment by zetdotcom** [comment]
Hi. Have you set up your deploy settings in Netlify?  I.e. give your repository url, ,set build command as 'gatsby build', public directory 'public/', and production branch to 'master'.
Is build triggered when you push to your github repo?

**Comment by b0gd4n** [comment]
hey @zetdotcom - yep, here are my current settings:

```

Repository - https://github.com/***
Build command - gatsby build
Publish directory - public/
Production branch - master
Branch deploys - Deploy only the production branch and its deploy previews
```

Pushing any commits to the `master` branch is being picked up by Netlify and the build start immediately.

I double checked, and under the `Build hooks` section, the hook matches the one I have on the `functions.php` file.

**Comment by zetdotcom** [comment]
I just checked mine and it is working fine. I know it may be stupid, but maybe you posted it to the wrong functions.php file, i.e. the wrong theme... or try to move the code up a little bit. If github pushes are triggering the build it must be something wrong with WP or webhook. Maybe try to get another webhook

**Comment by b0gd4n** [comment]
It might be worth mentioning that I edited the `functions.php` file from within the WordPress admin page (Appearance -> Editor -> Theme Functions (functions.php)) and added the code at the end of the file.

**Comment by zetdotcom** [comment]
Make sure you are editing the right theme. If you are using gatsby you actually dont care about your theme. I use twenty-seventeen and posted the code in line 568, which is not the very end of the file. It is just before this comment:
/**
 * Implement the Custom Header feature.
 */

**Comment by zetdotcom** [comment]
THe code should be in the theme that is activated. However if you are using gatsby the theme shouldnt matter as you are developing your own front end? Maybe it is something in the theme that is preventing the code.

**Comment by b0gd4n** [comment]
OK - I activated (and updated) the Twenty Seventeen theme, added the code above to the functions.php file, just before the `Implement the Custom Header feature.` comment, published a new post - nothing in Netlify.

Deleted all webhooks, generated another one, updated the hook link in the functions.php file, saved, new post published - nothing in Netlify ☹️

**Comment by m-allanson** [comment]
This doesn't seem like a Gatsby issue so I'm going to close it. Feel free to carry on the discussion here, and I hope you get the problem resolved!

**Comment by b0gd4n** [comment]
just for reference, I managed to fix with using the following snippet:

`add_action( 'save_post', 'fireFunctionOnSave' );
function fireFunctionOnSave($post_id)
{
   if(wp_is_post_revision($post_id) || wp_is_post_autosave($post_id)) {
      return;
   }
   $response = Requests::post( NETLIFY_BUILD_HOOK_URL );
}`
