### ISSUE TITLE
Prevent GraphQL from returning everything as nullable

### ISSUE THREAD

**Issue by humphreybc** [gatsbyjs/gatsby#5337]
## Description

For a certain part of our website I'm generating pages based on data from a JSON file via `gatsby-source-filesystem` and `gatsby-transformer-json`. Everything is working great, however, the GraphQL queries return literally everything as nullable. TypeScript doesn’t like this, and it’s driving me nuts.

For example:

```jsx
<Masonry
  containerWidth={WIDTH}
  gap={32}
  items={edges!
    .sort(sortComparatorAsc(edge => edge!.node!.steps![0]!.title!))
    .map(edge => (
      <IntegrationCard
        app={edge!.node!.steps![0]!.title!}
        color={edge!.node!.steps![0]!.color!}
        icon={edge!.node!.steps![0]!.icon!}
        title={edge!.node!.title!}
        path={edge!.node!.path!}
      />
    ))}
  minColumnWidth={220}
/>
```

Is there a way to say, “look, I know the data is there, don’t make these fields nullable?” so I don’t have to put `!` after every item in the object? Or any other way to handle this more gracefully?

Thanks!

**Comment by pieh** [comment]
Where is nullable "attribute" of fields comming from? graphql schema? (I'm not familiar with TypeScript)

**Comment by humphreybc** [comment]
@pieh Yep. We generate the types based on the GraphQL schema. I'm not really sure if this is something that Gatsby can solve through different configuration or something in `gatsby-transformer-json`, or whether it's a quirk of GraphQL. [Here's a good blog post on nullable fields in GraphQL.](https://medium.com/@calebmer/when-to-use-graphql-non-null-fields-4059337f6fc8)

Here's the type definition for this particular query:

```tsx
export interface IntegrationIndexQuery {
  // Connection to all IntegrationsJson nodes
  allIntegrationsJson: {
    // A list of edges.
    edges: Array<{
      // The item at the end of the edge
      node: {
        title: string | null;
        path: string | null;
        steps: Array<{
          color: string | null;
          icon: string | null;
          title: string | null;
        } | null> | null;
      } | null;
    } | null> | null;
  } | null;
}
```

**Comment by calcsam** [comment]
Going to close this issue -- see https://github.com/gatsbyjs/gatsby/issues/4261 for further discussion!
