### ISSUE TITLE
fetch as google

### ISSUE THREAD

**Issue by brandonmp** [gatsbyjs/gatsby#534]
I'm unable to get Fetch as Google to correctly render my `gatsby` site. Has anyone else experienced this? is there a setting, etc., I have to finagle to get it rendered correctly? 

My html.js is pretty close to default, I think

```
import React from 'react'
import Helmet from 'react-helmet'
import { prefixLink } from 'gatsby-helpers'
import { TypographyStyle, GoogleFont } from 'react-typography'
import typography from './utils/typography'

const BUILD_TIME = new Date().getTime()
const style = {
    margin: 0,
    paddin: 0,
}
module.exports = React.createClass({
    propTypes() {
        return {
            body: React.PropTypes.string,
        }
    },
    render() {
        const head = Helmet.rewind()

        let css
        if (process.env.NODE_ENV === 'production') {
            css = <style dangerouslySetInnerHTML={{ __html: require('!raw!./public/styles.css') }} />
        }



        return (
            <html style={style} lang='en'>
                <head>
                    <link rel="apple-touch-icon" sizes="57x57" href="/assets/apple-icon-57x57.png" />
                    <link rel="apple-touch-icon" sizes="60x60" href="/assets/apple-icon-60x60.png" />
                    <link rel="apple-touch-icon" sizes="72x72" href="/assets/apple-icon-72x72.png" />
                    <link rel="apple-touch-icon" sizes="76x76" href="/assets/apple-icon-76x76.png" />
                    <link rel="apple-touch-icon" sizes="114x114" href="/assets/apple-icon-114x114.png" />
                    <link rel="apple-touch-icon" sizes="120x120" href="/assets/apple-icon-120x120.png" />
                    <link rel="apple-touch-icon" sizes="144x144" href="/assets/apple-icon-144x144.png" />
                    <link rel="apple-touch-icon" sizes="152x152" href="/assets/apple-icon-152x152.png" />
                    <link rel="apple-touch-icon" sizes="180x180" href="/assets/apple-icon-180x180.png" />
                    <link rel="icon" type="image/png" sizes="192x192" href="/assets/android-icon-192x192.png" />
                    <link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon-32x32.png" />
                    <link rel="icon" type="image/png" sizes="96x96" href="/assets/favicon-96x96.png" />
                    <link rel="icon" type="image/png" sizes="16x16" href="/assets/favicon-16x16.png" />
                    <link rel="manifest" href="/manifest.json" />
                    <meta name="msapplication-TileColor" content="#ffffff" />
                    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png" />
                    <meta name="theme-color" content="#ffffff" />
                    <meta charSet='utf-8' />
                    <meta httpEquiv='X-UA-Compatible' content='IE=edge' />
                    <meta
                        name='viewport'
                        content='width=device-width, initial-scale=1.0'
                        />
                    {head.title.toComponent()}
                    {head.meta.toComponent()}
                    <TypographyStyle typography={typography} />
                    <GoogleFont typography={typography} />
                    {css}
                   
                </head>
                <body style={style}>
                    <div id='react-mount' dangerouslySetInnerHTML={{ __html: this.props.body }} />
                    <script src={prefixLink(`/bundle.js?t=${BUILD_TIME}`)} />
                </body>
            </html>
        )
    },
})

```

The fetcher gives an ostensibly valid response (img b/c I can't seem to copy/paste the response):

![image](https://cloud.githubusercontent.com/assets/14139991/19969898/a28d5414-a1b0-11e6-83d6-5dd40a3a6ba7.png)

But the renderer shows it naked as the day it was born :/

![image](https://cloud.githubusercontent.com/assets/14139991/19969950/d1d08b1a-a1b0-11e6-9af6-8539078fbaa8.png)

**Comment by KyleAMathews** [comment]
What sort of error do you get?

**Comment by brandonmp** [comment]
hmm no error--page loads fine in browser, and fetch-as-google indicates that fetching/rendering completes w/o issue. the only indication that something's amiss is the blank screens.

**Comment by oliverbenns** [comment]
This will probably answer your concern: http://webmasters.stackexchange.com/questions/89076/render-as-google-always-shows-a-blank-page-should-i-be-concerned :)

**Comment by KyleAMathews** [comment]
Tried it on my blog and it worked just fine... this doesn't seem like a Gatsby-related problem.
<img width="1014" alt="screen shot 2016-11-11 at 9 37 35 pm" src="https://cloud.githubusercontent.com/assets/71047/20235934/2b27d090-a857-11e6-8641-a2fe93029c37.png">

**Comment by brandonmp** [comment]
thanks Kyle. I finally figured this out. One of the npm modules I use was throwing a minor `warning` during `gatsby build`: 

```
Generating CSS
Generating Static HTML
Wrapper div has no height or width, try overriding style with `containerStyle` option
Wrapper div has no height or width, try overriding style with `containerStyle` option
Wrapper div has no height or width, try overriding style with `containerStyle` option
Compiling production bundle.js
Copying assets
Done
```

This had the strange result of **not** actually rendering the `html`.  However, the page still loaded fine, so I didn't notice.

When Google came to crawl it, though, it wasn't able to render the `bundle.js` React code, resulting in the blank screens. 

Once I cleared out those warnings, though, everything worked fine.

**Comment by KyleAMathews** [comment]
Oh strange... not rendering HTML should be an error you'd think not just a warning.

**Comment by brandonmp** [comment]
So the warning is from the third party library. The weird thing is the app works fine, despite the warning also appearing in the console, so I don't think the warning is breaking the html rendering when it's live. The only problem seems to be  when gatsby tries to render the html... If render warnings w/in the app are supposed to break html, def. agree it should a loud, loud error, esp since the fallback behavior is to render the app as a non static fully functional react app

**Comment by RobinHerzog** [comment]
Hey guys. Sorry to re-open this topic. I have the same issue right now ?
Did you figured out what was the issue ?

**Comment by pieh** [comment]
@RobinHerzog this seemed like issue not directly related to gatsby - it's either in one of 3rd party libraries you use or in your code - try stripping your code to bare minimum and add libraries / your features one by one and see which one cause problems
