### ISSUE TITLE
Copying build files to FTP server

### ISSUE THREAD

**Issue by b0gd4n** [gatsbyjs/gatsby#5346]
My client has a Wordpress website and I build a nice Gatsby replacement which works nicely with Netlify and webhooks, so when a post is updated, Netlify starts building.

Unfortunately, I cannot completely move the website to be hosted on Netlify - the client wants to keep using the existing host.

I want to keep using Netlify and all it's goodies, but basically add another step to the build process that would copy over the files to the existing server (either using FTP, SSH).

Is this possible?

If not, should I consider using another deployment process?

Thank you.

**Comment by Jaikant** [comment]
You probably want to use circleci instead. There isn't a way to transfer the build outside of netlify AFAIK

**Comment by b0gd4n** [comment]
thank you - will give that a go.
I'll close this as it's not really a Gatsby issue

**Comment by thomasheimstad** [comment]
Huh, not possible? I just uploaded the content of the public folder, and it posts just fine on an ftp-server.
