### ISSUE TITLE
[v2] Use [contenthash] instead of [chunkhash] for webpack compilation

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#5347]
Investigate whether using `contenthash` makes sense for JS also.

- [x] `contenthash` for CSS
- [ ] `contenthash` for JS

This issue split out from #4677

**Comment by m-allanson** [comment]
`contenthash` for CSS was added in #5808. It seems we should [use `contenthash` for JS](https://github.com/webpack/webpack.js.org/issues/2096) also, however I wasn't seeing consistent filenames when doing that. This needs a bit more investigation.

**Comment by KyleAMathews** [comment]
E.g. you'd change css but not js but the js filename still changed?
