### ISSUE TITLE
[v2] Upgrade gatsbyjs.org to run on v2

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#5348]

**Comment by ryanditjia** [comment]
I’ve set up v2 www on my machine and want to help with this. Some changes that I want to make / have questions about:

1. Move `layouts/index.js` to `src/components/layout.js`
2. The layout component is sometimes imported as Layout, sometimes GlobalLayout, should this be standardized?
3. Remove the unused imports to get rid of `no-unused-vars` lint errors. Mostly has to do with `rhythm, scale, options` typography imports.
4. `import { Link } from "gatsby"`. Is this the idiomatic v2 way? If yes, I’ll change the gatsby-link imports in favor of this.

Let me know if all these are good to implement. Thanks!

**Comment by m-allanson** [comment]
> I’ve set up v2 www on my machine and want to help with this

That's great, thank you!

> Move `layouts/index.js` to `src/components/layout.js`

Sounds good

> 2. The layout component is sometimes imported as Layout, sometimes GlobalLayout, should this be standardized?

Yes please. Either one seems fine.

> 3. Remove the unused imports to get rid of `no-unused-vars` lint errors. Mostly has to do with `rhythm, scale, options` typography imports. EDIT: alternatively, we could perhaps add `rhythm, scale, options` to the [ignore list](https://eslint.org/docs/rules/no-unused-vars#varsignorepattern).

Fixing all the lint errors would be 👍. I think remove the unused imports rather than adding them to an ignore list.

> 4. `import { Link } from "gatsby"`. Is this the idiomatic v2 way? If yes, I’ll change the gatsby-link imports in favor of this.

Yes please 👍

**Comment by m-allanson** [comment]
I've noticed some other areas that need fixing up for the v2 branch, listing them here for reference.  @ryanditjia these are up for grabs if you want to take them on too, but don't feel like you have to! I'm happy to answer any questions here for anyone that wants to look into these.

- Individual tag pages are not found

https://deploy-preview-5454--gatsbyjs.netlify.com/blog/tags/react/
https://www.gatsbyjs.org/blog/tags/react/


- Sidebar missing for the following pages:

https://deploy-preview-5454--gatsbyjs.netlify.com/docs/actions/
https://www.gatsbyjs.org/docs/bound-action-creators/

https://deploy-preview-5454--gatsbyjs.netlify.com/docs/browser-apis/
https://www.gatsbyjs.org/docs/browser-apis/

https://deploy-preview-5454--gatsbyjs.netlify.com/docs/node-apis/
https://www.gatsbyjs.org/docs/node-apis/

https://deploy-preview-5454--gatsbyjs.netlify.com/docs/ssr-apis/
https://www.gatsbyjs.org/docs/ssr-apis/


- Search sidebar missing for:

https://deploy-preview-5454--gatsbyjs.netlify.com/plugins/
https://www.gatsbyjs.org/plugins/


- Blog pages missing:

https://deploy-preview-5454--gatsbyjs.netlify.com/blog/2018-2-3-sites-with-headless-cms/
https://www.gatsbyjs.org/blog/2018-2-3-sites-with-headless-cms/

Set up a redirect from `/docs/bound-action-creators/` to `/docs/actions/`

**Comment by ryanditjia** [comment]
I believe redirect is already done [here](https://github.com/gatsbyjs/gatsby/commit/04931e67ce62808e4bb0cd6030806f6355f6d4cd#diff-fb043578f52339bcb2a2d2b4df1203c8). Unless there is more to do?

**Comment by ryanditjia** [comment]
Individual tag pages are there when running on my local machine (both develop and build+serve).

I’ll look into the missing plugins search sidebar and blog post.

**Comment by ryanditjia** [comment]
![image](https://user-images.githubusercontent.com/16177372/40482888-6643cf9e-5f80-11e8-8044-83a79037aef4.png)

Some blog posts aren’t showing because of the limit of 1000, while in actuality there are 1036 markdownRemark nodes, majority of which are nulls and should be removed.

Problem isn’t isolated to v2 because master also has 1005 nodes, causing the first few blog posts to go missing.
https://www.gatsbyjs.org/blog/gatsbygram-case-study/
https://www.gatsbyjs.org/blog/gatsby-first-beta-release/
https://www.gatsbyjs.org/blog/gatsby-v1/
https://www.gatsbyjs.org/blog/2017-07-19-creating-a-blog-with-gatsby/
