### ISSUE TITLE
Using HtmlWebpackPlugin with Gatsby

### ISSUE THREAD

**Issue by TimPetricola** [gatsbyjs/gatsby#5349]
I'm trying to add a new html page that is just loading a JS file. The purpose is to have this page being loaded in an iframe. It does not need all the Gatsby overhead. In development it works nicely, but when I try to build, the script being referenced is `render-page.js` instead of `demo-[chunkhash].js` (because the output is being set as `render-page.js` in Gatsby's webpac config for the `build-html` page). Is there a way to get around that?

My modified webpack config:

```js
const path = require(`path`)
const HtmlWebpackPlugin = require("html-webpack-plugin")

exports.modifyWebpackConfig = ({ config, stage }) => {
  config.merge(current => {
    current.entry = { 
      ...current.entry, 
      demo: path.resolve(__dirname, "./src/demo.js")
    }
    return current
  })

  config.plugin("html-webpack", () =>
    new HtmlWebpackPlugin({
      title: "Demo",
      filename: "demo.html",
      chunks: ["demo"]
    })
  )
}
```

And the resulting html after running `gatsby build`

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Demo</title>
    // <link rel="apple-touch-icon" sizes="57x57"...
    // ...
  </head>
  <body>
    <script type="text/javascript" src="/demo.js"></script>
  </body>
</html>
```

Here I would expect `src="/demo-[chunkhash].js`.

Thanks a lot for your help 😊

**Comment by moroshko** [comment]
@TimPetricola It's been a while since you opened this issue, but I wonder what solution you ended up with?

**Comment by TimPetricola** [comment]
@moroshko if I recall correctly, I ended up not using Gatsby (but for other reasons though). Sorry I can't be of much more help 😬
