### ISSUE TITLE
Some Images failing to have hashed name on build

### ISSUE THREAD

**Issue by oliverbenns** [gatsbyjs/gatsby#535]
Hi there. 

Thanks for Gatsby!

I've got some images that I am requiring into one of my pages. On build the image src gets converted to [hash].(jpg|png), so the page is requesting them. However in my public directory some images appear to not actually get their file name changed are only copied over. I've tried using absolute paths from the project root as well as relative ones. I've even moved the images into the `assets` folder but to no luck. I've also tried running the images through imageoptim to ensure there's not any bad metadata or something. It's odd that it only appears to be happening to a select few pages. This doesn't happen on `npm run develop`. 

Example here:
- https://github.com/oliverbenns/oliverbenns.com/blob/version-2/pages/work/life-with-bird/index.jsx

**Comment by KyleAMathews** [comment]
I *think* this is working as expected given our [current Webpack config](https://github.com/gatsbyjs/gatsby/blob/master/lib/utils/webpack.config.js#L268). In the 1.0 config, I'm not explicitly setting the naming scheme which works nicely https://github.com/gatsbyjs/gatsby/blob/1.0/lib/utils/webpack.config.js#L323-L341

Perhaps try making the same change to the webpack config for your site (you can do this temporarily by editing `node_modules/gatsby/dist/utils/webpack.config.js`) and seeing if that fixes things?

Probably should backport these same changes to 0.x.

**Comment by oliverbenns** [comment]
Yeah ok I'll have a look into it later on today. I don't think that explains why it would hash some images and not others though.

**Comment by oliverbenns** [comment]
Seemed this didn't work. The urls appear to need a slash infront of them. But how can I do this when requiring them in? Also, how come some are have a base 64 string and others use a url?

![screen-shot-2016-11-06-at-12 02 33](https://cloud.githubusercontent.com/assets/1992355/20037547/7054cf0c-a419-11e6-8083-da552ab4f981.png)

**Comment by oliverbenns** [comment]
It seems the the assets do go into the static folder on build with your change. However the urls remain relative to the current directory and not the root (`/static`). 

![screen shot 2016-11-06 at 22 45 21](https://cloud.githubusercontent.com/assets/1992355/20042497/e699f21a-a472-11e6-9bac-f1dfc977aa45.png)

**Comment by oliverbenns** [comment]
I managed to fix this by upgrading from `0.12.6` to `0.12.19`.

**Comment by KyleAMathews** [comment]
Oh yes — there were some fixes on this in the past month or so.

**Comment by oliverbenns** [comment]
Thanks for the support @KyleAMathews :)
