### ISSUE TITLE
plugin: Post-build HTML Validation

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#5351]
## Summary

How about a plugin to run post-build that runs each page that has been built through an HTML validator and reports on any validation errors? Although it's harder to make these kind of errors nowadays thanks to the fact so much of the html is generated and editors are much better at flagging these errors early on, I think this might still be useful.

### Motivation

There are two very good reasons to ensure HTML is valid:

1. There are a wealth of subtle CSS errors that can be causes by invalid HTML given the variety in how browsers handle invalid markup.
2. HTML validity is a signal used by Google in ranking a site.

**Comment by m-allanson** [comment]
Good idea! Referencing the plugin wishlist at #1199 for anyone that might want to pick this up.
