### ISSUE TITLE
Arguments for fields inside GraphQL query is not working

### ISSUE THREAD

**Issue by megin1989** [gatsbyjs/gatsby#5352]
We are using Gatsby plugin: gatsby-source-graphcms.
When we connect our GraphQL end points to GatsbyJS using "gatsby-source-graphcms",  Arguments for fields inside GraphQL queries not working.

See the example below.
We are creating "campaignNameSpace" as the query with arguments is working. Inside this we are fetching a field called “campaigns” with arguments to filter and that filter is not working for some reason.
When Gatsby creates new schema, arguments for fields are not listing. Please see the below query that works in our end point.

```graphql
{
  campaignNameSpace{
    id
    name
    campaigns{          //arguments example  campaigns(campaignId:"142"){
      id
      name
      contents{
        id
        name
        identity
      }
    }
  } 
} 
```

Please see the below query generated by gatsby, In that we are not getting arguments for field “campaigns”.

```graphql
allCampaignNameSpace{
    edges{
      node{
        id
        namespace
        campaigns {    //we are not getting arguments here  campaigns(campaignId:"142"){
          id
          name
          contents{
            id
            name
            identity
          }
        }        
      }
    }
  }
```

Please help us to fix this. Thanks in advance

**Comment by pieh** [comment]
There are two things here:

1. Gatsby doesn't support yet remote schemas stitching that would made it possible to use same graphql schema as source in Gatsby schema. Instead we fetch all available data and reconstruct schema from data we get. That's something we want to add in the future.
2. In gatsby schema we support filtering only on top level field (`campaignNameSpace` or `allCampaignNameSpace`). There are already issues about adding more robust support for filtering - https://github.com/gatsbyjs/gatsby/issues/4783

**Comment by pieh** [comment]
So for now, You'll need to get all `campaigns` and filter them in JS.
