### ISSUE TITLE
Gatsby plugin medium failing for allMediumPost

### ISSUE THREAD

**Issue by kodepareek** [gatsbyjs/gatsby#5353]
Hi guys

Followed the instructions for installing and using the plugin. However I getting the error

`GraphQL Error Unknown field `allMediumPost` on type `RootQueryType`
`

Not very experienced with Graphql and so unable to debug deeply. However looking through GraphiQL is showing allMediumUser as an available query but not allMediumPost as shown in the docs.

**Comment by kodepareek** [comment]
Edited the title for clarity

**Comment by pieh** [comment]
Can you prepare minimal repo to reproduce that issue?

**Comment by kodepareek** [comment]
Hmm this is embarrassing. Just tried it all again on a different system and things worked out pretty smoothly. Quite strange. Closing issue.

**Comment by volkanger** [comment]
> Hmm this is embarrassing. Just tried it all again on a different system and things worked out pretty smoothly. Quite strange. Closing issue.

On a different system, as in OS?
