### ISSUE TITLE
How to use Google Auto Complete API

### ISSUE THREAD

**Issue by franva** [gatsbyjs/gatsby#5359]
Hi there,

I need to use Google Auto Complete API on my address search textbox.

I found this library:
https://github.com/kenny-hibino/react-places-autocomplete

Which asks for loading this script
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places"></script>
into my project.

What I have tried?

1. index.html
If it's a pure Reactjs project, I would do it in /public/index.html, but as you may know that this file(index.html) gets deleted and re-generated every time when we run
`gatsby develop`
so it  always loses the javascript reference after I re-run the command.

```
<!DOCTYPE html>
        <html>
        
        <head>
            <meta charSet="utf-8" />
            <meta http-equiv="x-ua-compatible" content="ie=edge" />
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
            <title data-react-helmet="true"></title>
            <script src="/socket.io/socket.io.js"></script>
            <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key={API_KEY}&libraries=places" async defer ></script>
        </head>
        
        <body>
            <div id="___gatsby"></div>
            <script src="/commons.js"></script>
        </body>
        
        </html>
```

2. layout/index.js with React-Helmet

I included this script in-between <Helmet> ....here... </Helmet>

      <Helmet>
              <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key={API}&libraries=places&callback=initAutocomplete" async defer></script>
            </Helmet>

this sometime works, but when I refresh my page, it breaks and asks for loading the Google Map API lib.

Been stuck here for a day~!

Please help.

**Comment by m-allanson** [comment]
This could be documented better I think, but you can use the `onRenderBody` API to do this. Have a look at [this example](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-fullstory/src/gatsby-ssr.js).

**Comment by m-allanson** [comment]
Oh and here's a link to the [`onRenderBody` docs](https://www.gatsbyjs.org/docs/ssr-apis/#onRenderBody)

**Comment by nik-s** [comment]
You could also try [customizing html.js](https://www.gatsbyjs.org/docs/custom-html/).

Is using `onRenderBody` a better approach?

**Comment by KyleAMathews** [comment]
It's cleaner as the code can be put into a plugin. But either way works and for a one-off integration, editing html.js is often easier.

**Comment by skube** [comment]
I'm trying to do something similar with the Maps JavaScript API but I'm confused as to where [the Google code](https://developers.google.com/maps/documentation/javascript/tutorial#The_Hello_World_of_Google_Maps_v3) is supposed to go inside of `html.js`. I've tried before the closing `</body>` and also inside the `<head>` of `html.js`.  In both cases, while I don't get any errors, I don't see any map either 😕

**Comment by skube** [comment]
n/m I figured it out... I needed to use `dangerouslySetInnerHTML`:
```js
<script dangerouslySetInnerHTML={{
  __html: `
    let map;
    function initMap() {
      map = new google.maps.Map(document.getElementById('map'), {
        center: { lat: -34.397, lng: 150.644 },
        zoom: 8,
     });
   }
 `,
}} />
```
