### ISSUE TITLE
Comparison with Hugo, Jekyll, Next, etc. in Documentation

### ISSUE THREAD

**Issue by aniketpanjwani** [gatsbyjs/gatsby#5364]
## Summary

Request for a comparison of Gatsby with existing static site generators, especially along the following dimensions:
1. What are the use cases for which Hugo (or another SSG) is better suited than Gatsby, and vice versa?
2. What does Gatsby do better/worse than other SSGs, and vice versa?

### Basic example

A good example of such a document is [this comparison](https://vuejs.org/v2/guide/comparison.html) written by the team of Vue.js

### Motivation

Part of the demand for a framework comes from non-technical or semi-technical end users who have to make a choice about a particular framework. A CTO who once coded Javascript, but hasn't touched recent frameworks, can use the Vue.js document to make a more educated decision between frameworks. Additionally, there's a reason why Vue wrote that document, and not React or Angular - it's because Vue is not the "default" framework choice, and so the onus is on Vue to convince others to switch.

I would argue that Gatsby is a bit of an underdog relative to other SSGs, and so such a document, honestly written, would be very useful at informing decision-making. I know it's easy to ask for such a document, and likely a months-long process to actually write the document, but I wanted to throw it out there, since I think the community would find it very useful.

**Comment by KyleAMathews** [comment]
I'd argue that they're underdogs ;-) perhaps they just haven't realized this yet hehe :-)

We do have this page though which seems sufficient for this purpose.

https://www.gatsbyjs.org/features/

Also, as an aside, we don't see ourselves as a traditional SSG. We're trying to forge a new path.

**Comment by aniketpanjwani** [comment]
Haha - fair enough! That page is really cool - thanks for the link. I tried to find a page like that by searching Hugo and Jekyll in the Algolia search, but I couldn't find it; just got a bunch of stuff on migrating.

Thanks Kyle!
