### ISSUE TITLE
Is there a way to route visitors coming with double slashes in the URL?

### ISSUE THREAD

**Issue by skube** [gatsbyjs/gatsby#5365]
This is possibly an edge case, but I'm wondering if it's possible to override routing to prevent someone from getting a `404` by visiting my domain with extra slashes?

For example, https://www.gatsbyjs.org// will result in a `404`.

**Comment by KyleAMathews** [comment]
Is this something you're running into or idle curiosity?

**Comment by skube** [comment]
Something I'm running into.
