### ISSUE TITLE
How Do I Create Multiple Templates To Route From YAML/Markdown Files?

### ISSUE THREAD

**Issue by frostyweather** [gatsbyjs/gatsby#5368]
I'm creating a Gatsby project that needs more than just an `index` template and `blogPostTemplate`. I have markdown files that create pages, but all of these pages now link up to the `blogPostTemplate`. I'd like to separate these markdown files into a `detail` template and a `landing-page` template. Anyone have any experience with this or can anyone point me in the right direction on how to do this? I'm assuming it involves digging into gatsby-node.js. Thanks!

**Comment by KyleAMathews** [comment]
You might want to read/review part 7 of the tutorial 

https://www.gatsbyjs.org/tutorial/part-seven/
