### ISSUE TITLE
Conditional commenting (for webfont cookies) 

### ISSUE THREAD

**Issue by ajmalafif** [gatsbyjs/gatsby#5376]
I am trying to load this conditional commenting as for `fontfaceobserver` best practices mentioned [here](https://prowebtype.com/delivering-web-fonts/#observer), [here](https://helloanselm.com/2015/using-webfonts-in-2015/#cache) and [here](https://jonsuh.com/blog/font-loading-with-font-events/) (you get the idea).

```
<!--#if expr="$HTTP_COOKIE=/webfont-loaded=true/" -->
<html lang="en" class="webfont-loaded">
<!--#else -->
<html lang="en">
<!--#endif -->
```

However, after a lot of digging through documentation for example using `html.js` as [per doc](https://www.gatsbyjs.org/docs/custom-html/) and trying some suggestions here: https://github.com/facebook/react/issues/1035#issuecomment-356455474

I still couldn't figure it out. Appreciate any help or pointer. Thanks!

**Comment by m-allanson** [comment]
Editing html.js should allow you to add that markup. However it looks like those comments are SSI includes, which it seems need support from the server rendering the page. You'll need to host your site with a server that supports SSI includes, which might not be what you were expecting?
