### ISSUE TITLE
Improve formatting of query-runner error log

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#5379]
## Summary

PR #5214 added extra context to the query-runner error log. 

There was some discussion on whether the formatting could be neater. Look into [this suggestion](https://github.com/gatsbyjs/gatsby/pull/5214#issuecomment-387387640) or find some other way of improving the error format.

### Motivation

Tidier error messages are easier to read.

**Comment by alexluong** [comment]
Hi, I went ahead and tried to help with this. How does this look?

<img width="860" alt="screen shot 2018-05-24 at 4 55 53 am" src="https://user-images.githubusercontent.com/26750127/40478520-de2fa7fc-5f0e-11e8-80d0-961c7f23817d.png">

**Comment by flipactual** [comment]
Closing per https://github.com/gatsbyjs/gatsby/commit/12c20f84e2d55fce2c730499253542ac97a6846c !

Please re-open the issue if there's more to be done 💃
