### ISSUE TITLE
Use "you" instead of "we"?

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#5381]
Was editing the tutorial for v2 recently and noticed we're always using "we" — and not sure why I picked that now 🤔

Isn't "you" generally preferred for tutorials since only the person reading the tutorial is actually doing anything?

**Comment by m-allanson** [comment]
👍 "you" is recommended in the [style guide](https://www.gatsbyjs.org/docs/gatsby-style-guide/#general-writing-tips).

**Comment by ryanditjia** [comment]
Should this be closed?

**Comment by m-allanson** [comment]
Yep, thanks @ryanditjia!

**Comment by KyleAMathews** [comment]
Thanks @ryanditjia! That was super helpful!
