### ISSUE TITLE
Is there any way to GraphQL query through the entire site in a template?

### ISSUE THREAD

**Issue by frostyweather** [gatsbyjs/gatsby#5382]
Basically I have a `components` markdown page that serves as an overview page for components (`/components/card`, `/components/hero`, etc). Along with markdown, I also want to add in a list of cards that represents the components within (Hero, header, footer, etc.). I tried querying the entire site from a template, but i only gives me the category that that markdown file is in. Is there any way to pull in the global data in a template or is that not possible?

**Comment by m-allanson** [comment]
Hey @frostyweather, I don't think I understand your question... could you give some examples of what you tried and what you were expecting to happen?
