### ISSUE TITLE
Using `^` on a beta version of a package like `@babel/runtime` version is super dangerous

### ISSUE THREAD

**Issue by loganfsmyth** [gatsbyjs/gatsby#5386]
I noticed while looking over #5378 that many packages use

    "@babel/runtime": "^7.0.0-beta.42"

which is super dangerous, because it means users of the package will pick up future betas automatically, since they don't have the benefit of a lockfile. We may well make add/rename/delete helpers still because it is beta, and if your users pull in a runtime without a helper that the module needs, it will be entirely broken with no way for them to fix it.

**Comment by m-allanson** [comment]
Thanks! This was causing a problem earlier which is what prompted me to open #5378. 

For now this issue should be closed by #5389.
