### ISSUE TITLE
Relative require from frontmatter

### ISSUE THREAD

**Issue by chrisdmacrae** [gatsbyjs/gatsby#539]
Including images in the markdown automatically resolves the images in the rendered component. However, including an image in the frontmatter simply passes the string to the template, page, component, etc.

I am using a component to render a list of pages, and I want an image stored relative to the md file that is specified in the frontmatter to be rendered by the component without having to hardcode the path resolving logic into the component (trying to keep it DRY).

Is there a good way of resolving the relative filepath to a rendered page so that I can require the image in the development bundle?

**Comment by KyleAMathews** [comment]
The very quick answer is to create a context module with all your images in them and then in your md wrapper reference the filepath to pull in the image path.

https://webpack.github.io/docs/context.html

I might add this to the blog starter soon as it's a pretty common request.

I'll add an actual code sample when I have time or just add it to the blog starter.

**Comment by jbolda** [comment]
This should be covered in 1.0 I would think. Closing unless you have anything else.

**Comment by anandrikka** [comment]
@chrisdmacrae Hi, I'm also facing similar issue. Did you resolved it ?
