### ISSUE TITLE
[gatsby-transformer-remark] Add excerpt option to prune to sentence or paragraph

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#5393]
Currently there is a single parameter: `pruneLength()` which dictates how many characters an excerpt should be pruned to. How about adding another parameter `pruneTo`.

`pruneTo` would accept either `sentence` or `paragraph` and would prune the excerpt to the first period or newline character encountered. 

Using natural intervals like these would mean the ellipsis character might not be appropriate, so I would suggest that the ellipsis should be separate parameter: `useEllipsis` which can either be `true` or `false` and defaults to `true`. 

One things that needs to be resolved is the interplay between `pruneLength` and `pruneTo` - should `pruneLength` be ignored if `pruneTo` is supplied? Or should it still be applied if a paragraph or sentence is longer than the `pruneLength`. If the former, then it might make sense to combine all three into a single parameter as they would be mutually exclusive - in this case we could overload `pruneTo` to accept either a number of chars or `sentence` or `paragraph`. 

I'd be happy to put together a PR adding this functionality. 

Note that although greymatter offers the option to supply a custom function for deciding where to truncate, this option isn't currently exposed, or doesn't function correctly. See my comment in #4459

**Comment by m-allanson** [comment]
Yeah it'd be nice to have more control over this. Maybe `pruneTo` could accept a regex instead of specific options. Similarly `useEllipses` could be `separator` and accept a string, allowing you to choose whatever separator you like.

Oh, looking at the last line - maybe it'd be better to fix up the problems in #4459 as that sounds like it'd handle a lot of this functionality?

**Comment by alexito4** [comment]
I started using Gatsby recently and I personally would prefer the API to support `sentence` or `paragraph` (specially paragraph). I think supporting more advanced uses is fine but at least this basic ones could be provided by default.

**Comment by joseph-allen** [comment]
This is still desired behavior.
