### ISSUE TITLE
[gatsby-transformer-sharp] Support for apng / animated webp

### ISSUE THREAD

**Issue by yodahuang** [gatsbyjs/gatsby#5400]
## Summary

I would like to use apng or animated webp in my site. Currently the transformer will only process the first frame of the image instead of the whole image. It would be nice if it can handle the situation (even better if it could do apng/webp/gif transformation based on browser support)

**Comment by m-allanson** [comment]
This would be great to see, but as far as I know [Sharp](http://sharp.pixelplumbing.com/en/stable/) doesn't support outputting animated image formats. It'd be interesting to see a new transformer plugin for dealing with animated images.

I'm going to reference issue #1199 in case anyone wants to pick this up.

**Comment by johannesjo** [comment]
Are there any news on this?

**Comment by Zrce** [comment]
I'm interested in this too. animated webp is much smaller than gifs

**Comment by nkuehn** [comment]
> but as far as I know [Sharp](http://sharp.pixelplumbing.com/en/stable/) doesn't support outputting animated image formats.

That's not correct, Sharp can be initialized with `animated: true` or `pages: -1` to retain multi frame PNG or webP (and likely also AVIF) input.  I have not tested it but it's definitely not "unsupported".  The fact that the gatsyby plugins additionally shove PNGs through pngcrush may be an additional blocker, but even supporting just WebP would be great.   As opposed to PNG, where the animations are not really a first class part of the spec, animated WebP is an official feature.  

No idea how to reopen or activate this though, I think I'll resort to opening a new issue.

**Comment by polarathene** [comment]
> That's not correct,
> I have not tested it but it's definitely not "unsupported"

No *longer* correct. It definitely was not supported at the time the comment was made.
