### ISSUE TITLE
npm WARN deprecated babel-preset-es2015@6.24.1: 

### ISSUE THREAD

**Issue by thebetterjort** [gatsbyjs/gatsby#5414]
+ gatsby-cli@1.1.52
added 210 packages from 104 contributors in 10.582s
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by m-allanson** [comment]
Hey @thebetterjort please open a new issue and fill out the issue template if you'd like some help. There's not enough info here to know what you're asking.
