### ISSUE TITLE
Use of Promise in tutorial for createPages

### ISSUE THREAD

**Issue by davidnorth** [gatsbyjs/gatsby#5424]
In the tutorial here https://github.com/davidnorth/gatsby/blob/master/docs/tutorial/part-seven/index.md , "new Promise" is used in the createPages function but it seems unnecessary since the function graphql itself returns a promise.  Also it seems you don't even need to return a promise from createPages for it to work. I'm happy to submit a PR but I wanted to check if there's a reason its done this way.

**Comment by pieh** [comment]
You are probably right that extra `new Promise` is not needed in that case. In tutorial we try to show code that is easily understandable, so explicitely creating Promise, returning and resolving it *should* make it easier for reader to see that we indeed want to return promise there (just returning promise from `graphql` function might make it a little harder to understand for people not familiar with promises).

As for the second part - returning promise is for gatsby to wait with next stages until all work that is needed is done - it might not manifest any problems now, but then You will have some builds that work, some that don't and some that don't have pages created if pages won't be created before next step in the process. So You defenitely want to return promise there.

**Comment by davidnorth** [comment]
That makes perfect sense, thank you.
