### ISSUE TITLE
Why do queries have to be named?

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#5425]
I'm not sure why every single query has to be named, especially with the arrival of [`StaticQuery`](https://github.com/gatsbyjs/rfcs/blob/master/text/0002-remove-special-layout-components.md#detailed-design) in v2. Are there any advantages besides more developer-friendly error messages?

**Comment by pieh** [comment]
This is requirment from `relay-compiler` used under the hood. We want to autogenerate query names in v2 so users won't have to do that manually - https://github.com/gatsbyjs/gatsby/issues/5095
