### ISSUE TITLE
Error while executing tutorial part 5

### ISSUE THREAD

**Issue by TheFastCat** [gatsbyjs/gatsby#5437]
Following tutorial 5, I get the following error from

`gatsby develop`

after installing

`npm install --save gatsby-source-filesystem`

...
```
⠁ The new node didn't pass validation
ValidationError: child "internal" fails because ["description" is not allowed]
```
...

gatsby develop executes and the localhost site is served but I can't continue with the tutorial because the gatsby-source-filesystem source plugin is not loaded.

I just upgraded to Node v10 and npm 6 and the error remains 

Am I doing something wrong?

**Comment by KyleAMathews** [comment]
Sorry about the error  — to fix it, just upgrade the `gatsby` package to the latest version.
