### ISSUE TITLE
[v2] Error: Cannot find module 'gatsby-starter-modern\.babelrc.js'

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#5438]
## Description

Since I have updated gatsby@2, the following error gets shown when running `yarn develop` on [gatsby-starter-modern](https://github.com/kripod/gatsby-starter-modern).

### Steps to reproduce

1. Clone [gatsby-starter-modern](https://github.com/kripod/gatsby-starter-modern)
2. Run `yarn add gatsby@next gatsby-plugin-sass@next`
3. Execute `yarn develop`

### Expected result

No errors should be thrown.

### Actual result

```
$ gatsby develop
success delete html and css files from previous builds — 0.009 s
success open and validate gatsby-config.js — 0.009 s
success copy gatsby files — 0.131 s
success onPreBootstrap — 0.048 s
success source and transform nodes — 0.029 s
success building schema — 0.210 s
success createLayouts — 0.011 s
success createPages — 0.003 s
success createPagesStatefully — 0.058 s
success onPreExtractQueries — 0.001 s
success update schema — 0.076 s
success extract queries from components — 0.089 s
success run graphql queries — 0.038 s
success write out page data — 0.010 s
success write out redirect data — 0.005 s
success onPostBootstrap — 0.001 s

info bootstrap finished - 10.947 s

error UNHANDLED EXCEPTION


  Error: Cannot find module 'C:\Development\Projects\gatsby-starter-modern\.babelrc.js'

  - v8-compile-cache.js:159 require
    [gatsby-starter-modern]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - gatsby-node.js:48 findBabelrcJs
    [gatsby-starter-modern]/[gatsby]/dist/internal-plugins/load-babel-config/gatsby-node.js:    48:29

  - gatsby-node.js:152 Object.exports.onCreateBabelConfig
    [gatsby-starter-modern]/[gatsby]/dist/internal-plugins/load-babel-config/gatsby-node.js:    152:43

  - api-runner-node.js:98 runAPI
    [gatsby-starter-modern]/[gatsby]/dist/utils/api-runner-node.js:98:37

  - api-runner-node.js:167 mapSeries
    [gatsby-starter-modern]/[gatsby]/dist/utils/api-runner-node.js:167:25

  - map.js:27
    [gatsby-starter-modern]/[async]/internal/map.js:27:9

  - eachOfLimit.js:64 replenish
    [gatsby-starter-modern]/[async]/internal/eachOfLimit.js:64:17

  - eachOfLimit.js:49 iterateeCallback
    [gatsby-starter-modern]/[async]/internal/eachOfLimit.js:49:17

  - onlyOnce.js:12
    [gatsby-starter-modern]/[async]/internal/onlyOnce.js:12:16

  - map.js:29
    [gatsby-starter-modern]/[async]/internal/map.js:29:13

  - util.js:16 tryCatcher
    [gatsby-starter-modern]/[bluebird]/js/release/util.js:16:23

  - nodeify.js:23 Promise.successAdapter
    [gatsby-starter-modern]/[bluebird]/js/release/nodeify.js:23:30

  - promise.js:566 Promise._settlePromise
    [gatsby-starter-modern]/[bluebird]/js/release/promise.js:566:21


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Environment
* Gatsby version (`npm list gatsby`): 2.0.0-alpha.36
* gatsby-cli version (`gatsby --version`): 2.0.0-alpha.36
* Node.js version: 8.11.1
* Operating System: Windows 10 x64

### File contents (if changed)

See https://github.com/kripod/gatsby-starter-modern/tree/d2ce864348782014214842da3e3b484a14b5a83c.

**Comment by pieh** [comment]
I tried to reproduce it, but there seems to be broken gatsby alpha release currently (at least for me) and when I tried to workaround it and used `gatsby-dev` to get latest gatsby, I didn't get this error. Did you have problems when installing `gatsby@next`?

**Comment by kripod** [comment]
@pieh I haven't tried `gatsby-dev`, but as stated in the issue, installing `gatsby@next` using yarn produces the error above during `gatsby develop`. It may be a yarn-related issue, as yarn treats some `canary` versions as the latest instead of releases on the `next` channel.

**Comment by KyleAMathews** [comment]
I published a new gatsby release which should have fixed the broken one from last night. Please try again @kripod! Thanks for jumping in to help get v2 ready for release!

**Comment by kripod** [comment]
Everything works fine now, thank you for the quick response and fix!
