### ISSUE TITLE
[gatsby-source-filesystem] mutliple configuration options

### ISSUE THREAD

**Issue by fraed** [gatsbyjs/gatsby#5444]
Can anyone make the usage of the `sourceNodes` API more clear? I am using it in conjunction with gatsby-source-filesystem. Two folders are configured to be sourced.

My config:
```
...
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: '${__dirname}/category',
        name: "category",
      },
    },{
      resolve: 'gatsby-source-filesystem',
      options: {
        path: '${__dirname}/posts',
        name: "posts",
      },
    },
    'gatsby-transformer-remark',
    'gatsby-source-netlify-relation',
...
```

The two folders have markdown files in it. I want a local plugin to create new nodes to put both folder in relation. I expect a local plugin gatsby-source-netlify-relation using the `sourceNodes`API to provide all markdown nodes. But only the 'category' files are provided as markdown entries in `getNodes`. For me only the first configuration entry affect the result.

Am I missing something or is here something going wrong with gatsby-source-filesystem using multiple folders?

Thanks!

**Comment by m-allanson** [comment]
`getNodes` should return all the available nodes. Do the file nodes show up in GraphiQL? http://localhost:8001/___graphql

Maybe there's some useful info in https://github.com/gatsbyjs/gatsby/issues/1634?

**Comment by KyleAMathews** [comment]
sourceNodes is the API for source plugins to *start* collecting nodes. The API is async. source-filesystem won't have collected any nodes basically by the point your plugin is called. You want to use onCreateNode if you'd like to respond to nodes being created.

**Comment by fraed** [comment]
Ok, thanks. Using onCreateNode instead of sourceNodes solved my issue.
