### ISSUE TITLE
[feature] Child Themes

### ISSUE THREAD

**Issue by selrond** [gatsbyjs/gatsby#5445]
## Summary

Could Gatsby have something like [Child Themes](https://developer.wordpress.org/themes/advanced-topics/child-themes/) in WordPress?
So it would be possible to inherit / import certain files, while versioning the starter theme - base theme - separately.

### Motivation

When using `.md` files as a source, I'd like to opensource my theme, but not the content. Having some child theme mechanism in place, I could oepnsource and iterate upon them main - base - theme, while also keeping my child theme private / tracked separately.

What do you think?

**Comment by m-allanson** [comment]
Hey @selrond, there's a discussion on themes and how they should work over in https://github.com/gatsbyjs/gatsby/issues/2662. Would you like to add your thoughts over on that issue?
