### ISSUE TITLE
[v2] css modules class names with dashes / camelCased locals

### ISSUE THREAD

**Issue by pieh** [gatsbyjs/gatsby#5458]
Currently in v2 css modules there is undocumented breaking change - dashed class names will be camelCased ( https://github.com/gatsbyjs/gatsby/blob/c0e503d0df7cefb3b072e85155e2ce853e48fb53/packages/gatsby/src/utils/webpack-utils.js#L201 )

Omitting that setting or setting it to false will result in same behaviour as in v1. Setting it to true or 'dashes' would return both dashed and camelCased version of it - might be worth using that?

**Comment by jquense** [comment]
`dashes` is the most accepting setting, but it leads to larger bundles since most css classes are duplicated in the locals export (the camel and dash cases). I went with the `dashesOnly` setting a bit out of personal convenience, but i do think it's probably the community wide "best practice" (for lack of a better word) and fairly uncontroversial, saving on bytes while also allowing idiomatic casing for css and js

**Comment by pieh** [comment]
It makes sense - in this case we would "just" need to update https://github.com/gatsbyjs/gatsby/blob/v2/Breaking%20Changes.md so it's documented. 

I'll leave this issue opened just to get more input on the matter from other folks.

**Comment by pieh** [comment]
I was just thinking about it - would it make sense to revert to v1 default and create plugin to easily overwrite css module rule options? Something that walks webpack config object rules and if loader is `css-loader` and `options.modules === true` replace/merge options with what user specify?

**Comment by m-allanson** [comment]
Maybe let's go the other way around? `dashesOnly` seems like a good option and v2 is the time to make breaking changes. I'll add a section to the migration guide.

**Comment by dustinhorton** [comment]
@pieh did you happen to write something to allow for v1 behavior? have multiple projects where this change is causing some pain.

**Comment by HamidReazaNikoonia** [comment]
what about pt-5 , pt5 not working

**Comment by dustinhorton** [comment]
@HamidReazaNikoonia what part 5?

**Comment by acalderongarcia** [comment]
> @HamidReazaNikoonia what part 5?

pt-5 padding-top

**Comment by dustinhorton** [comment]
@acalderongarcia have you added this to your `gatsby-config.js`?

```javascript
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-plugin-sass',
      options: {
        cssLoaderOptions: {
          camelCase: false,
        },
      },
    },
  ],
}
```
