### ISSUE TITLE
Is there a way to specify a port other than 8000 for the development server?

### ISSUE THREAD

**Issue by VictorioBerra** [gatsbyjs/gatsby#547]
I use cloud9 as my IDE and I cant preview anything running on any port other than 3000.

**Comment by VictorioBerra** [comment]
I was using npm run develop instead of gatsby develop.

**Comment by jerickBilalat** [comment]
I'm trying to do the same thing. I tried to change the port by entering "gatsby develop -p 8080" but it did not work cloud9 says there's no app running at 8080. The npm run develop also did not work.

**Comment by itaditya** [comment]
Same issue

**Comment by itaditya** [comment]
Note that if you use `gatsby serve -p 8080` after building, then it does work on c9 ide

**Comment by alesanchezr** [comment]
For anyone still trying, the solutions is to include also the host as a flag, like this:
```
$ gatsby develop -p $PORT -H $IP
```

**Comment by DamengRandom** [comment]
Hi alesanchezr, its not working ...

**Comment by DamengRandom** [comment]
reference link: https://www.gatsbyjs.org/docs/gatsby-cli/#develop
