### ISSUE TITLE
Helmet does not correctly work for facebook scraper

### ISSUE THREAD

**Issue by nealoke** [gatsbyjs/gatsby#5471]
## Description

Unfortunatly the scraper of Facebook does not pick up the correct meta tags created with the `helmet` plugin for pages which are not the `index`. The tags the scraper picks up are only from the `index page`

**Example /index.js**
```
<Helmet>
    <meta
        name="description"
        content="My index page description"
    />
</Helmet>
```

**Example /mypage.js**
```
<Helmet>
    <meta
        name="description"
        content="My other page's description"
    />
</Helmet>
```

### Steps to reproduce

Create a gatsby project, create a meta tag within the `helmet` component for 2 pages namely an `index page` and an `other page`. Build it, host it and try to scrape the `other page` with the [facebook tool](https://developers.facebook.com/tools/debug/echo/?q=yourURL) (set the `q` parameter in the url)

### Expected result

Should pick up the meta tags you created in the `helmet ` component for the `other page`.

### Actual result

Scraper only gets the meta tags from the `index page`

### Environment
* Gatsby version (`npm list gatsby`): 1.9.260
* gatsby-cli version (`gatsby --version`): Not installed
* Node.js version: v6.9.4
* Operating System: Windows 10

### File contents (if changed)
[See my gist for these files](https://gist.github.com/nealoke/18b893de665b1be481c086fc6a3ea4cb)

**Comment by KyleAMathews** [comment]
Is there any console errors?

**Comment by nealoke** [comment]
@KyleAMathews none when building and none when hosted 😢

**Comment by nealoke** [comment]
Also note that the generated `HMTL page` contains the correct `meta tags`. For some reason they change when being scraped 😒

**Comment by jkarttunen** [comment]
Why is Title and Metadata defined in gatsby-config.js? Shouldn't that be page-level metadata, not site level metadata?

**Comment by nealoke** [comment]
Thanks everybody for your help but I've found why this was occuring namely having my `.htaccess` file on the server with the following rule. Removing this fixed the issue

```
RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} !-f
RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} !-d
RewriteRule ^ /index.html [L]
```
