### ISSUE TITLE
Cannot query field \"acf\" on type \"wordpress__TAG\"

### ISSUE THREAD

**Issue by gapgag55** [gatsbyjs/gatsby#5477]
`Cannot query field \"acf\" on type \"wordpress__TAG\"`

I use ACF in allWordPressCategory. It's worked, but Tag is otherwise.
as well as I got below one.
`source and transform nodes -> wordpress__acf_tags fetched : 0`

Please help,
Thanks

**Comment by kristyanne** [comment]
I think I'm also having a similar issue (Loving Gatsby so far by the way!). 

The project I'm working on (Wordpress + Gatsby) relies quite heavily on tagging. The majority of the content/post types (Posts, Pages and various Custom Post Types) all use the built in Wordpress tagging functionality. However, and I'm not sure if it's the way I've set up my post types, the fragment I have only works of `Post` content, it does not ork on Pages or any other custom post type I have created.

For the following fragment:

```
fragment Tag on wordpress__TAG {
    id
    name
    slug
 }
```

I get the following error:

`GraphQL request: Fragment "Tag" cannot be spread here as objects of type "tags_12" can never be of type "wordpress__TAG".`

I've tried using both Wordpress's native tagging functionality and also adding tags using ACF's Taxonomy field type but neither are working. 

Any ideas? I can supply more info if needed :)

Thanks

**Comment by pieh** [comment]
> Cannot query field \"acf\" on type \"wordpress__TAG\"
> 
> I use ACF in allWordPressCategory. It's worked, but Tag is otherwise.
> as well as I got below one.
> source and transform nodes -> wordpress__acf_tags fetched : 0

gatsby can't infer schema if it has no data to infer from. Do you actually have any tags in your wordpress instance?

**Comment by pieh** [comment]
> However, and I'm not sure if it's the way I've set up my post types, the fragment I have only works of Post content, it does not ork on Pages or any other custom post type I have created.

wordpress plugin link tags only for posts currently - https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/normalize.js#L190-L212 . Maybe you could try adding mapping to your `gatsby-config.js`:
```js
module.exports = {
  plugins: [...],
  mapping: {
    "wordpress__PAGE.tags": `wordpress__TAG.wordpress_id`,
  },
}
```

**Comment by kristyanne** [comment]
@pieh Thanks for your response :)

I've tried adding the mapping as you suggested and it's no longer throwing a GraphQL error, but, the tags are all returning as `null` now:

```
mapping: {
   'wordpress__PAGE.tags': 'wordpress__TAG.wordpress_id'
 }
```

Gives this result:

```
{
  "data": {
    "allWordpressPage": {
      "edges": [
        {
          "node": {
            "id": "9168ec1c-795e-5eb1-852d-084b89c51d51",
            "title": "A Test Page",
            "tags": [
              null,
              null,
              null
            ]
          }
        },
        {
          "node": {
            "id": "d7df9746-bd37-5f12-b503-0ce78145e76a",
            "title": "Another Page",
            "tags": [
               null
            ]
          }
        }
      ]
    }
  }
}

```

So, seems like it's almost there but the mapping isn't quite right? I've tried reading the docs about mapping and I've tried a few variations of the above but no joy so could do with a point in the right direction.

**Comment by pieh** [comment]
@kristyanne Hmm, are tags used for page the same tags that are used for posts? Can you share your wordpress endpoint? (you can email me at misiek.piechowiak@gmail.com if you don't want to post it publicly)

**Comment by kristyanne** [comment]
@pieh I haven't deployed it anywhere yet, I'm just running it locally at the moment. I can send you the returned JSON if that'll help?

**Comment by ibanlopez** [comment]
> gatsby can't infer schema if it has no data to infer from. Do you actually have any tags in your wordpress instance?

Hi @pieh, I've been struggling with this quite a lot and I'm stuck. I do have tags: 
`=== [ Fetching wordpress__TAG ] === https://domain.com/wp-json/wp/v2/tags
 -> wordpress__TAG fetched : 15
Fetching the wordpress__TAG took: 321.604ms`

But no fetching ACF fields from them:
`=== [ Fetching wordpress__acf_tags ] === https://domain.com/wp-json/acf/v3/tags
 -> wordpress__acf_tags fetched : 0
Fetching the wordpress__acf_tags took: 299.886ms`

ACF fields for categories get fetched fine. I do not use tags in any special way different from what a tag should be, but there's no way to get ACF fields created on tags.

![Captura de pantalla 2019-07-24 a las 5 27 38](https://user-images.githubusercontent.com/11489638/61762949-ee589c00-add3-11e9-81e2-8ba963c6d358.png)

Any idea what I might be doing wrong?

Thanks a lot!

**Comment by ibanlopez** [comment]
It's nothing related to Gatsby. It's about WordPress.

Gatsby can't fetch those ACF fields because `https://domain.com/wp-json/acf/v3/tags` endpoint gives an empty array as result. Categories endpoint is correct and shows ACF fields.

So I'll check what's on WordPress config and see solution.

Thanks.

**Comment by ibanlopez** [comment]
Just to shed some light into this: https://github.com/airesvsg/acf-to-rest-api/issues/230
