### ISSUE TITLE
importing css module with background image rules results in compilation error.

### ISSUE THREAD

**Issue by iamsuneeth** [gatsbyjs/gatsby#5479]
## Description

When using background image in css (using css modules) like:
`body{
    color:#888;
    background: url('../staticFiles/images/san-francisco.jpg') center no-repeat;
}`

getting the following error:
`Loader D:\Personal\Projects\gatsby\myPage\node_modules\url\url.js?{"limit":10000,"name":"static/[name].[hash:8].[ext]"} didn'tstcss-loader!./src/layouts/index.module.css 6:61-111 return a function

 @ ./~/css-loader?modules&minimize&importLoaders=1&localIdentName=[path]---[name]---[local]---[hash:base64:5]&sourceMap!./~/postcss-loader!./src/layouts/index.module.css 6:61-111`

This issue is exactly similar to the comment by  @rossthedevigner under closed issue #3478 
### Environment
* Gatsby version : 1.9.260
* gatsby-cli version : 1.1.51
* Node.js version: 8.1.3
* Operating System: Microsoft Windows 10

### File contents 
`gatsby-config.js`: module.exports = {
  siteMetadata: {
    title: 'Personal site',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    {
      resolve: 'gatsby-plugin-typography',
      options: {
        pathToConfigModule: './src/utils/typography.js',
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/staticFiles`,
        name: 'markdown-pages',
      },
    },
    `gatsby-transformer-remark`,
    `gatsby-transformer-json`,
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
  ],
}`

**Comment by codeincontext** [comment]
I have this too. I think the cause is that Webpack is trying to load the `url` npm module instead of `url-loader`

**Comment by nebsi04** [comment]
Same here.

**Comment by codeincontext** [comment]
FWIW the fix was adding `url-loader` to my package.json

**Comment by 777sha** [comment]
Same issue here on gatsby 1.9 I couldn't import images and `npm install url-loader --save-dev` solved it

**Comment by DZuz14** [comment]
Yeah, why is this not included as a dev dependency by default? I have the same issue right now, and fixed it by installing url-loader.

**Comment by KyleAMathews** [comment]
Is url-loader not in your node_modules when you run into this bug?

**Comment by DZuz14** [comment]
Not sure, but I know I had to manually npm install url loader. I would have to create a new gatsby project to see if it shows up in node modules on initial setup.

**Comment by CSumm** [comment]
Url-loader didn't seem to be in my node_modules as well, so I just installed it thanks to this. Would be great if it could be included in the standard Gatsby startup package.

**Comment by rperez2021** [comment]
It normally is installed. The current project I am working on was started about 3 days ago and url-loader was not included. I just created a new gatsby starter site and it was included. Weird.

**Comment by adidaas** [comment]
Same issuess on my end. Made two new separate projects today and neither had url-loader in node_modules. Manually installing myself and that fixed everything. Weird.

**Comment by LeKoArts** [comment]
`url-loader` is already in the dependencies and hence should be installed. It seems that's a npm issue. Did you try it with `yarn` ? I never had any issues with yarn.
Otherwise delete the node_modules folder and install again.

**Comment by OskarHulter** [comment]
What a lifesaver! Were just tearing my hair out about this issue but installing url-loader manually fixed it. Thanks you so much guys!

**Comment by codeincontext** [comment]
For context in why the bug presents itself in this way, Webpack 1 lets you
use 'url' to reference 'url-loader' which was a consistent source of
bugs/confusion. As url-loader is missing, I assume it falls back to 'url'
instead

**Comment by KyleAMathews** [comment]
@codeincontext thanks for the explanation — but how is `url-loader` missing when it's a dependency?

**Comment by KyleAMathews** [comment]
Oh I see — so webpack tries to load `url` first and then fails because it's not actually a loader?

**Comment by codeincontext** [comment]
I'm not sure what the root cause is, I just know that the error message is
because Webpack is trying to use using the `url` module as a loader.
Webpack 1 interprets "url" and "url-loader" as the same

**Comment by mudspringhiker** [comment]
Had exactly the same issue and url-loader also fixed it. I'm using npm and I used the default starter. Thanks!
