### ISSUE TITLE
[1.0] GraphQL syntax errors for .js locations

### ISSUE THREAD

**Issue by iiroj** [gatsbyjs/gatsby#548]
I upgraded my blog (not released yet) from 0.12.12 to 1.0.0-alpha9 by cloning your blog. Everything seems to be ok now, but I'm getting a lot of seemingly redundant errors when building:

    message: 'Syntax Error GraphQL request (1:1) Unexpected <EOF>\n\n1: \n   ^\n',
    locations: [ [Object] ],
    path: undefined } ]

I get one of these for every `.js` in _./pages/_ excluding the main _index.js_. I have my blog files in _./pages/blog/_ and then some other manual routes like _./pages/resume/index.js_.

It seems the _allMarkdown_ query doesn't limit itself to only markdown files.

[gatsby-config.js.txt](https://github.com/gatsbyjs/gatsby/files/586489/gatsby-config.js.txt)
[gatsby-node.js.txt](https://github.com/gatsbyjs/gatsby/files/586490/gatsby-node.js.txt)
[package.json.txt](https://github.com/gatsbyjs/gatsby/files/586491/package.json.txt)

**Comment by KyleAMathews** [comment]
Hmmm... not 100% sure what's going on here — sorry about the GraphQL errors — they're lousy at the moment. Definitely need to clean those up before a beta.

So one (not necessary) restriction right now is that every js page component has to export a query. Perhaps some of the pages you've created aren't doing that?

**Comment by iiroj** [comment]
Would it be ok if I send you my working copy blog for debugging? It'd be a matter of `npm install` after that to find out more.

I'm not comfortable releasing it as open-source before it's ready for release.

**Comment by KyleAMathews** [comment]
Yeah for sure

**Comment by iiroj** [comment]
I sent it to the email listed in your GitHub profile. I'll close this ticker for now.

Hopefully it'll give you an idea of how a ~~clueless~~ person might try to use Gatsby. 🙂

**Comment by KyleAMathews** [comment]
@iiroj hey — haven't gotten your email yet?

**Comment by iiroj** [comment]
@KyleAMathews Could it have gone into your spam folder, or Gmail filters? I just re-sent it just in case. I have _iiro [at] jappinen.fi_ hosted with FastMail, so maybe Gmail doesn't like it.

**Comment by KyleAMathews** [comment]
oh weird, it's in spam now. I thought I'd checked there earlier but perhaps not. Thanks!
