### ISSUE TITLE
Articles all under `/blog` while still have homepage

### ISSUE THREAD

**Issue by ajmalafif** [gatsbyjs/gatsby#5480]
Hi all,

I am trying to get this specific setup for my gatsby site. I want to have a landing page and a separate blog articles to be inside `/blog` folder or path. The closest example I found so far is this:
https://github.com/DSchau/gatsby-blog-starter-kit/issues/28

is this possible with Gatsby?

**domain.com**
![homepage](https://user-images.githubusercontent.com/827167/40267902-40403658-5b97-11e8-97a4-bbbd02d36081.png)

**domain.com/blog**
![blog](https://user-images.githubusercontent.com/827167/40267906-47b00b02-5b97-11e8-9fde-78274f6766d2.png)

**domain.com/blog/article-1**
![article](https://user-images.githubusercontent.com/827167/40267909-4c2b9822-5b97-11e8-9705-a209e5dfe36f.png)

**Comment by daydream05** [comment]
Here's a tutorial on that if you'll be using markdown for your articles https://www.gatsbyjs.org/tutorial/part-seven/

Basically the idea is, on your gatsby-node.js, you'll be generating pages that has a path with /blog/ as the prefix + the slug of your article.

**Comment by pieh** [comment]
As mentioned by @daydream05 - this is covered in linked tutorial.

**Comment by axhamre** [comment]
@daydream05  @pieh  

I assume you refer to the `basePath` parameter?

This does NOT seem to work.

**Comment by pieh** [comment]
@axhamre Please provide more details - and ideally separate issue/question.

**Comment by axhamre** [comment]
This seems to be how to solve it (see basePath variable), `exports.onCreateNode`:

```
    createNodeField({
      name: `slug`,
      node,
      value: `/${basePath}${value}`,
    })
```
