### ISSUE TITLE
Deploying gatsby web application on Digital Ocean

### ISSUE THREAD

**Issue by mahayash** [gatsbyjs/gatsby#5484]
Can someone help me in deploying my gatsby web application to Digital Ocean, as I tried a lot but keep on getting 404 error. 
It would be great if someone draft and published the step of publishing the gatsby web app to digial ocean

**Comment by tsriram** [comment]
Is the built site working locally? What HTTP server are you using to serve the site on Digital Ocean? You might have to configure it to work for Single Page Applications. Not sure if you've done it already. It would be helpful if you post the steps you followed for the deployment to see if something's missing.

**Comment by mahayash** [comment]
Yeah, the site is working fine locally
I am using nginx server on ubuntu to serve the site on Digital Ocean
Steps followed from the link : https://www.robinwieruch.de/deploy-applications-digital-ocean
tried all the step, but then too gives 404 error

**Comment by valgalin** [comment]
Hello @mahayash ,

I also followed the tutorial from Robin, and also encountered the 404 error.

I was able to fix the issue by manually copying the public folder to /var/www/yourgatsbysite.com/html/.

Do not do the symlink step. If you did the symlink already, you need to delete if first before doing the manual copying of the public folder.

**Comment by m-allanson** [comment]
It sounds like @valgalin's fix might work for you? Check out the [deployment docs](https://www.gatsbyjs.org/docs/deploy-gatsby/) for alternative ways to host your Gatsby site.

Closing as this seems to be a hosting issue rather than a problem with Gatsby.

**Comment by dkeesey** [comment]
m-allanson: your link to the "deployment docs" now returns 404 "oops".
