### ISSUE TITLE
Documentation, Examples or use cases missing for gatsby-plugin-catch-links

### ISSUE THREAD

**Issue by ajayns** [gatsbyjs/gatsby#5489]
Going through the plugin in the Gatsby [docs](https://www.gatsbyjs.org/packages/gatsby-plugin-catch-links/) didn't seem very informative on how to use this plugin or where it could be used.

I think adding a bit more documentation on it's working and also an example use case with it would really help!

**Comment by ajayns** [comment]
I could work on improving the docs here, if anyone could guide me to an example use case somewhere. @m-allanson @KyleAMathews

**Comment by melissamcewen** [comment]
Hmm yeah just looking at this myself. It seems like it might solve my current issue which is that my pages created with markdown don't use gatsby-link for internal links. So I don't get the benefits that gatsby-link provides like preloading. It appears this plug in parses for internal links and turns them into gatsby-link components?

**Comment by ajayns** [comment]
I believe it's for handling relative links in sources such as maybe .md files or so when imported to Gatsby as pages. But that doesn't quite explain how it works and such, so I figured it'd be a good idea to add some docs/examples.

**Comment by ajayns** [comment]
@ryanditjia Thanks, I'll look into that post! And exactly, felt that the readme was pretty unhelpful right now.

**Comment by ajayns** [comment]
@ryanditjia I went through the post, it still doesn't make it clear what difference this plugin would make. Anything else that can help us here?

**Comment by ryanditjia** [comment]
[https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-catch-links/src](Plugin source). I believe in essence what it does is set up a browser listener for clicks. If the link should go to another page within the site, it replaces the default `a` behavior with `navigateTo` (what’s used by `gatsby-link` behind the scene).

This is to preserve the SPA-like page change when, say, you click on a link in markdown—which by default is a normal `a`.

**Comment by ajayns** [comment]
Okay that made proper sense. Should I try making a PR with that explanation? I believe that could help a lot of people!

**Comment by ryanditjia** [comment]
Yeah, I feel `gatsby-transformer-remark` and `gatsby-plugin-catch-links` docs could use some explanation about how their usages are linked to each other. Perhaps a PR for each?

Perhaps it’s best to wait for a core contributor to chime in.

**Comment by KyleAMathews** [comment]
`gatsby-plugin-catch-links` is for anytime that you render a blob of HTML that has links pointing to other pages on the site. So it's not necessarily just for use with markdown though that is a common use case.

@ryanditjia what were you thinking of adding to the docs? The larger problem is that for people to create a markdown-based site, there's a lot of pieces they have to pull together.

**Comment by melissamcewen** [comment]
There are a lot of docs in plugins which are primarily accessed in the repo. It would be interesting to pull them all into one easily accessible place like the documentation section of the main site - either automatically (I work with some systems that do this - you have a block of code or md file in a repo and it consolidates them into documentation files) or manually. And add some use cases.

**Comment by ryanditjia** [comment]
I was thinking to add a real world use case for `gatsby-plugin-catch-links` to the doc, the most common one being blog posts with `gatsby-transformer-remark`. Plus add a note that says the use case isn’t limited to markdown.

In the same vein, update `gatsby-transformer-remark`’s docs to mention that blog posts sometimes link to other pages within the site. To prevent page refresh, use `gatsby-plugin-catch-links`.

Pairing these two is very common, but we currently can’t find a lot of references for this. I searched through the Gatsby repo and only found relevant catch-links examples in a [blog post](https://github.com/gatsbyjs/gatsby/blob/master/docs/blog/2017-07-19-creating-a-blog-with-gatsby/index.md) and [a page inside `using-remark` example](https://github.com/gatsbyjs/gatsby/blob/master/examples/using-remark/src/pages/2017-03-21---copy-linked-files-intercepting-local-links/index.md).

**Comment by KyleAMathews** [comment]
@ryanditjia sounds like a great next step!

**Comment by m-allanson** [comment]
> There are a lot of docs in plugins which are primarily accessed in the repo. It would be interesting to pull them all into one easily accessible place like the documentation section of the main site

A lot of those docs are available in a roundabout way via the [plugin library](https://www.gatsbyjs.org/plugins/). I agree it'd be useful to make these more accessible via gatsbyjs.org.

**Comment by ryanditjia** [comment]
Hi @ajayns, would you like to attempt this?

> I was thinking to add a real world use case for gatsby-plugin-catch-links to the doc, the most common one being blog posts with gatsby-transformer-remark. Plus add a note that says the use case isn’t limited to markdown.
>
> In the same vein, update gatsby-transformer-remark’s docs to mention that blog posts sometimes link to other pages within the site. To prevent page refresh, use gatsby-plugin-catch-links.
>
> Pairing these two is very common, but we currently can’t find a lot of references for this. I searched through the Gatsby repo and only found relevant catch-links examples in a blog post and a page inside using-remark example.

**Comment by ajayns** [comment]
Sure! I'll go through it and try to make a PR if I have enough good information.  @ryanditjia

**Comment by ajayns** [comment]
@ryanditjia @m-allanson @KyleAMathews I'm unsure about mentioning `plugin-catch-links` in the `transformer-remark` docs as well cause it already has this link mentioned: https://using-remark.gatsbyjs.org/ And that includes most of the popular plugins used in combination. Maybe I could link that page itself to the `plugin-catch-links` docs?

**Comment by ryanditjia** [comment]
Ah right, so we just need to add a link to https://using-remark.gatsbyjs.org/copy-linked-files-intercepting-local-links/#intercepting-local-links in `plugin-catch-links` docs?
