### ISSUE TITLE
[1.0] Pictures next to .md files do not display

### ISSUE THREAD

**Issue by iiroj** [gatsbyjs/gatsby#549]
After cloning [your blog](https://github.com/KyleAMathews/blog), out of the box, pictures next to .md blog posts inside their respective folders do not display properly.

I assume this is because of the path rewriting going on: `host/2016-11-11---post` turns into `host/post` so images added with `![image](./image.jpg)` return a 404.

**Comment by KyleAMathews** [comment]
This will be fixed soon with the work I'm doing right now on the GraphQL layer. In Gatsby 0.x most assets are just copied over to the public directory. What will happen soon is that if you query for an HTML representation of a Markdown file, while creating that, the markdown handler will copy over any referenced assets into a static folder in the public directory. This will also open up the possibility for auto-optimizing images e.g. creating mobile/retina versions of the image. This way you can just drop the full-sized version of an image in your blog and not worry about having to resize it (to avoid serving 5mb files to mobile clients on crappy connections).

**Comment by hsribei** [comment]
> This way you can just drop the full-sized version of an image in your blog and not worry about having to resize it (to avoid serving 5mb files to mobile clients on crappy connections).

This is very enticing. It would be awesome to have something like Medium's blurred lazy-loading of images with device-optimized sizes.

**Comment by KyleAMathews** [comment]
@hsribei already is working if you're using `gatsby-remark-responsive-images`. Load https://www.gatsbyjs.org/blog/gatsbygram-case-study/ for example.
