### ISSUE TITLE
Create Static Pages incrementally

### ISSUE THREAD

**Issue by jquintozamora** [gatsbyjs/gatsby#5491]
Hi,
I'm new on Gatsby, and I'd like to understand if we can configure gatsby in response to some webhook from CMS and then automatically generate the incremental static file, or if on the opposite we have to generate all static files every time we have some content change.

Thanks!

**Comment by charnz** [comment]
Depending on what CMS and deployment platform you use you should be able to configure webhooks to trigger a new build of your static site. Contentful, for example, can be configured to trigger builds on Netlify in response to different events in the CMS (for example adding or updating content).

**Comment by weitzman** [comment]
The question is about incremental builds, not full builds. I'm curious as well.

**Comment by m-allanson** [comment]
Hey @jquintozamora 👋At the moment there's no way to do incremental updates when running `gatsby build`, although `gatsby develop` will give you fast updates while developing your site.

Gatsby will cache data between builds so a second build will be faster, and the upcoming Gatsby v2 should improve build times too. 

I'm going to close this but would love to hear about your use-cases for incremental builds.
