### ISSUE TITLE
[gatsby] Render just one page

### ISSUE THREAD

**Issue by jquintozamora** [gatsbyjs/gatsby#5496]
I've scenario with 5 different templates and more than 50 pages on my site. 

I'd like to know if there is a cli option for gatsby which allow me to render only one given page. So If I only change the content for one page ( one url on my app ) then only that static file is generated and it doesn't update everything on my app.

Something like:
`gatsby generate /mysite/mypage.html` 

And that specific page is updated and generated quickly, so the gatsby process does not have to process everything on my site.

Is that something I can achieve ? 

Thanks!

**Comment by jquintozamora** [comment]
Hi @mquandalle , 
Thanks for that, but I guess with that approach we still need to generate all the project and later on remove the pages we don't need. Did I understand well?
The main reason I asked for a single page approach is to save time and being able to render a preview when I change something on my CMS.

**Comment by mquandalle** [comment]
The `onCreatePage` function is called at the beginning of the bundling process, when pages aren't built yet, so you'll indeed save time by using something like the above.

**Comment by oliviertassinari** [comment]
I have a SSR issue, I would like to debug the problem without having to rebuild the whole app between each iteration. It's frustrating.

**Comment by maxcorbeau** [comment]
Similar need here, my use case is previewing individual WordPress pages when using:
https://www.gatsbyjs.org/docs/sourcing-from-wordpress/

The content is managed in WP, the page generation in Gatsby, but would like to visualize individual WP pages as I create/update them without having to rebuild everything.

**Comment by amitprajapati7747** [comment]
> Similar need here, my use case is previewing individual WordPress pages when using:
> https://www.gatsbyjs.org/docs/sourcing-from-wordpress/
> 
> The content is managed in WP, the page generation in Gatsby, but would like to visualize individual WP pages as I create/update them without having to rebuild everything.

Please contact me on skype : amitprajapati7747 or whats up : +919638138616

**Comment by maxcorbeau** [comment]
What about allowing to pass a series of node ids to the `localhost:8000/__refresh` endpoint and make those available in `gatsby-node.js/createPages` to decide to refresh 1 or multiple specific pages? (similar to https://github.com/gatsbyjs/gatsby/issues/5496#issuecomment-394076283 except we replace env variables with URL parameters)

**Comment by spik3s** [comment]
> What about allowing to pass a series of node ids to the `localhost:8000/__refresh` endpoint as body or URL parameters and make those available in `gatsby-node.js/createPages` to decide to refresh 1 or multiple specific pages? (similar to [#5496 (comment)](https://github.com/gatsbyjs/gatsby/issues/5496#issuecomment-394076283) except we replace env variables with URL parameters)

I like that approach, it would make it easier to create hooks in CMS to automatically re-generate content on change when using 3rd party services.

**Comment by dandv** [comment]
Closed by the bit due to inactivity in 2018. Reopening due to activity since then, and no official solution for this very common use case.

**Comment by LekoArts** [comment]
This has been superseded by https://github.com/gatsbyjs/gatsby/issues/5002 and is solved with Incremental Builds. Locally this always worked withing `gatsby develop` and [refresh env var](https://www.gatsbyjs.org/docs/environment-variables/#reserved-environment-variables).

**Comment by dandv** [comment]
Thanks for pointing to #5002, @LekoArts. If I understand correctly,
* locally, re-rendering just on page withing `gatsby-develop` works
* in production, [incremental builds are only available for Gatsby Cloud customers](https://spectrum.chat/gatsby-js/general/big-news-introducing-incremental-builds~945420ee-45e6-4a62-abcc-eea31d3ee1ac?m=MTU5MDEzNjQzNzQ4Ng==).

I believe @jquintozamora was asking in [the OP](https://github.com/gatsbyjs/gatsby/issues/5496#issue-324965875) was asking about generating just one page in production.

@LekoArts, can you please clarify how to re-render just one page in production without Gatsby Cloud?

**Comment by firstdoit** [comment]
> @LekoArts, can you please clarify how to re-render just one page in production without Gatsby Cloud?

I am also interested in this 👀 

Any updates?
