### ISSUE TITLE
Gatsby should have consistent route resolution for development and production

### ISSUE THREAD

**Issue by Algram** [gatsbyjs/gatsby#550]
Currently Gatsby resolves a fake "404"-Route, but **only** in development. The user gets confused by this as one might think this route will also show in production. That will never happen though, because the server won't find the page and therefore it wil return a **real** 404 status code.

My suggestion would be to remove this fake 404 page from development mode and instead show a proper error, since a link to a non-existant page **is** a proper error.

Here are two images from my blog to show you what I am talking about:

Development
![development-404](http://i.imgur.com/gqzLeHd.png)

Production:
![production-404](http://i.imgur.com/HIjajuK.png)

**Comment by KyleAMathews** [comment]
Big 👍 to this! The development environment and production environment should be as consistent as possible so the current behavior is definitely wrong. Thanks for bringing this up!

This would be an easy first PR for someone — in the development server we have a list of all the pages https://github.com/gatsbyjs/gatsby/blob/477bdb9447f28fcbf3ac56dc00e3bd9e3a5b3cd7/lib/utils/develop.js#L32. Basically [check against that when loading a page](https://github.com/gatsbyjs/gatsby/blob/477bdb9447f28fcbf3ac56dc00e3bd9e3a5b3cd7/lib/utils/develop.js#L129) and return the 404 page if the page doesn't exist.

**Comment by vinnymac** [comment]
@Algram @KyleAMathews is this not dependent on server routing configuration? The 404 page loads the same for both development and production on my blog.

[See production here](https://vinnymac.github.io/123123)

Also @KyleAMathews you propose changing the develop.js file to return a 404 page, but in the example above @Algram shows the 404 page loading just fine for development. What behavior does your recommended change create?

**Comment by radubrehar** [comment]
Has anyone started some work on this? Or can I offer to try & fix it?

**Comment by KyleAMathews** [comment]
Please do!

**Comment by KyleAMathews** [comment]
I think this was fixed? Comment or reopen if there's still trouble.
