### ISSUE TITLE
Add 'gatsby clean' to Gatsby CLI

### ISSUE THREAD

**Issue by ajayns** [gatsbyjs/gatsby#5500]
Numerous times, I've faced issues and unexpected bugs due to cache not cleaned. Some of these include changes made not visible, runtime errors and so on. A regular fix for these seems be to clear the cache with `rm -rf cache` but I think since it's so commonly used, it'd help with it being a command in the Gatsby CLI itself.

So maybe a command like:
`gatsby clean`
Which would remove all the cache and later can build the project fresh.

**Comment by ryanditjia** [comment]
I second this. Cache seems to be busted sometimes when creating/modifying content model in Contentful. Often enough that I run this script more often that the vanilla develop.

```sh
"cdev": "rm -rf .cache && npm run develop"

**Comment by sebastienfi** [comment]
I would use `rimraf` npm package instead as `rm` is a Unix command.

**Comment by hassanshaikley** [comment]
I am interested in doing this

**Comment by Undistraction** [comment]
Yes. The cache is often problematic. It would actually be useful to be able to disable it:

```
yarn develop --nocache
```

**Comment by pieh** [comment]
We know that cache is not bulletproof but instead of adding this feature to gatsby-cli, we actually would prefer to fix issues we have and not hide them (so we prefer people to create issues with descriptions allowing us to reproduce it). You still can use `rm -rf .cache` of course.

**Comment by Undistraction** [comment]
@pieh I think the problem is these issues tend to crop up late on in a project lifecycle when there is a  lot going on in the way of plugins and custom code, making it really hard to isolate issues and give a useful report or isolate in a test-case. They are also often seemingly intermittent.
