### ISSUE TITLE
Mobex Use with Gatsby

### ISSUE THREAD

**Issue by ashutosh02** [gatsbyjs/gatsby#5505]
Hello Team,

How to use Mobex in Gatsby at build time. I want to fetch some data from Api (Graphql) & store this data in Store using Mobex  , so can you please guide me regarding that.

I'm waiting for your responses.

**Comment by flipactual** [comment]
Hey @ashutosh02 👋 

Have you checked out https://github.com/gatsbyjs/gatsby/issues/2940?

I'm going to close this for now in favor of that issue, but feel encouraged to re-open if you have unique concerns that should not be addressed there 🙂
