### ISSUE TITLE
Update babel-preset-es2015 -> babel-preset-env in the config files? 

### ISSUE THREAD

**Issue by meghna-saxena** [gatsbyjs/gatsby#5508]
I see this warning in the command line, while creating a new Gatsby site with the starter pack. 

`warning gatsby > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!`

**Comment by flipactual** [comment]
Going to go ahead and close this, feel free to re-open if more discussion is needed!
