### ISSUE TITLE
Capture data entered into search field

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#5509]
## Summary

It would be valuable to capture everything people search for on the site for improving the docs and improving Gatsby itself and also verify that they are finding what they looked for. It would be put all the data into something like a google spreadsheet or Airtable so we can easily sort and filter everything people are searching for.

### Basic example

I'm not sure what this would involve from a code perspective. Perhaps google analytics or Algolia have straightforward ways to accomplish this?

### Motivation

We are doing this to figure out what the most common questions and search terms are and whether they find what they're looking for. If they are not finding what they're looking for, we can make that happen through writing new docs, improving the discoverability of existing docs, or solving the problems that cause them to ask questions in the first place.

**Comment by m-allanson** [comment]
I opened an issue to see if we can get usage data straight from Algolia: https://github.com/algolia/docsearch/issues/346

Otherwise we'd probably need to manually send this data to Google Analytics.

**Comment by shannonbux** [comment]
Just emailed docsearch@algolia.com in issue @m-allanson referenced above.

**Comment by shannonbux** [comment]
Ok, @m-allanson I've logged into our Algolia search dashboard and it looks like we have some analytics already being automatically tracked, and others that we have to set up. The two that seem important are click thru rate and conversion rate. Should I create issues for each of those separately and close this one?

https://www.algolia.com/doc/guides/analytics/analytics-implementation/

**Comment by m-allanson** [comment]
> Should I create issues for each of those separately and close this one?

Yeah that sounds good - I guess they'll be two separate pieces of work.
