### ISSUE TITLE
[gatsby-source-contentful]: Missing content breaks the build.

### ISSUE THREAD

**Issue by 0xsven** [gatsbyjs/gatsby#5512]
Let's say you have a content type with an asset or reference field in Contentful. If you want to query this field without adding content for the field, Gatsby will throw a schema related error.

To circumvent this, I have to set every field in Contentful as required. But I would like my users to have the option to remove certain content and let my website handle it gracefully.

Is it possible somehow to just get undefined as a response from graphQL? Am i missing something? I am still a graphQL beginner but if someone gives me a few hints on where to start I could work on a PR for that.

**Comment by isabellachen** [comment]
@0xsven Did you ever find a workaround for this?

**Comment by 0xsven** [comment]
@isabellachen unfortunately nothing satisfying. The only thing that worked is to create one „dummy entry“ of every content type and then ignore those „dummy entries“ in your build. but this will worsen the editor experience. 

I believe contentful has released their own graphql api in the meantime. maybe they have solved it?
