### ISSUE TITLE
[Gtasby-Plugin-Sharp@1.6.44] deprecated Gulp-Util dependancy

### ISSUE THREAD

**Issue by tomVlt** [gatsbyjs/gatsby#5513]
## Description

When installing plugin "gatsby-plugin-sharp" npm CLI warn on deprecated "gulp-util@3.0.8" dependancy.
Answer might be here : https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

### Steps to reproduce

npm i --save gatsby-plugin-sharp

### Expected result

The plugin is still installing and working fine. However it may contains vulnerabilities due to decrepated dependancy.

### Actual result

npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

$ npm ls gulp-util
gatsby-starter-default@1.0.0 C:\ [my_own_path]
`-- gatsby-plugin-sharp@1.6.44
  `-- imagemin-pngquant@5.0.1
    `-- pngquant-bin@3.1.1
      `-- bin-build@2.2.0
        `-- download@4.4.3
          `-- gulp-decompress@1.2.0
            `-- gulp-util@3.0.8

### Environment
* Gatsby version (`npm list gatsby`): v1.9.250
* gatsby-cli version (`gatsby --version`): v1.1.52
* Node.js version: v8.11.1
* Operating System: windows

### File contents (if changed)
`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by leptest** [comment]
Looks like this might be fixed now.  `imagemin-pngquant@6.0.0` upgraded the `pngquant-bin` dependency to `5.0.0` which seems to address the problem: https://github.com/imagemin/pngquant-bin/commits/master.

`pngquant-bin` [diff v4.0.0-v5.0.0](https://github.com/imagemin/pngquant-bin/compare/42091a7cfa0f862463d3292ddf192006fecdf7a4...30d0f40e7866e10c5a24f785e0800e0d5013daaf)

Sorry i can't fully test this, but definitely worth another look now.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by JustFly1984** [comment]
Still having this issue npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated 

<img width="538" alt="screenshot 2018-11-23 22 44 44" src="https://user-images.githubusercontent.com/2255993/48964270-a7c74f00-ef71-11e8-8e48-e27658af7194.png">

Please reopen
