### ISSUE TITLE
A way to extract the first header in gatsby-transformer-remark 

### ISSUE THREAD

**Issue by ubenzer** [gatsbyjs/gatsby#5521]
Hi all,
I am trying to give Gatsby a go for the first time. I have about ~700 blog posts in the following format:

```
---
created: 2018-05-19
edited: 2018-05-19
taxonomy:
  category:
    - Category 1
    - Category 1/Sub Category 1
    - Category 2
---

# Post Title

![some_custom_class_to_imge_tag|Allt text for image](js-logo.png) Lorem ipsum dolor sit amet...

## Another Title
Lorem ipsum...

# Another title...
...
```

In my current setup in the tool I use, I extract the __first header__ from the post content and treat it as the page title. I also calculate the slug of the blog post from it. I am looking for a way to do the same thing on Gatsby.

I was following the tutorial [over here](https://www.gatsbyjs.org/docs/adding-markdown-pages/#create-a-page-template-for-the-markdown-data). The problem is, `path` is not defined in frontmatter in my case, and I have no idea how to provide a proper `path` to `createPage` function.

I would be super helpful if you advise me a way to start. (e.g. shall I read and try to write a plugin for remark? or do I need a plugin to extends `gatsby-transformer-remark` etc.)

Cheers!

**Comment by nathanforce** [comment]
It's a bit contrived, but I think this should be possible in theory.

`gatsby-transformer-remark` lets you map custom React components to Markdown elements, so you could create a custom component for your header that adds something like `data-post-title`

https://using-remark.gatsbyjs.org/custom-components/#mapping-from-generic-html-elements

Then, in your `createPages` function you can grab the generated html 

```        {
          allMarkdownRemark(
            limit: 1000
          ) {
            edges {
              node {
								html
              }
            }
          }
        }```

Now you just need to parse the html for your first `data-post-title`.

**Comment by ubenzer** [comment]
Cool, thanks for pointing to a direction, I'll see what I can do. :-)

**Comment by nathanforce** [comment]
@ubenzer Not sure where you got on this one but MarkdownRemark gives you back headings out of the box!

```
        {
          allMarkdownRemark(
            limit: 1000
          ) {
            edges {
              node {
                headings(depth: h1) {
                  value
                }
              }
            }
          }
        }```

**Comment by ubenzer** [comment]
Hi @nathanforce 
I stopped working on this for a while. I'll definitely check this when I start working on it again.
