### ISSUE TITLE
WebpackError: Cannot read property 'pathname' of undefined

### ISSUE THREAD

**Issue by gapgag55** [gatsbyjs/gatsby#5528]
I run `gatsby build` the result errors like this.
Please help 👍 

```
error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  47 |
  48 | var createPath = exports.createPath = function createPath(location) {
> 49 |   var pathname = location.pathname,
     | ^
  50 |       search = location.search,
  51 |       hash = location.hash;
  52 |


  WebpackError: Cannot read property 'pathname' of undefined
```

**Comment by ryanditjia** [comment]
Does following the debugging steps outlined [here](https://www.gatsbyjs.org/docs/debugging-html-builds/) help? If not, could you provide us more info using the below bug report format?



## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue.

### Expected result

What should happen?

### Actual result

What happened.

### Environment
* Gatsby version (`npm list gatsby`):
* gatsby-cli version (`gatsby --version`):
* Node.js version:
* Operating System:

### File contents (if changed)
`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by pieh** [comment]
We need more information, please update the description using bug report template provided by @ryanditjia . I'll close it for now and re-open it if this will be updated (please ping me if you will update it)

**Comment by DanielRuf** [comment]
I get the same error with the Preact plugin.
