### ISSUE TITLE
[gatsby-plugin-sharp] Support Default Configuration

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#5531]
## Summary

At present there is no way to define default configuration for images used on a Gatsby site. The only option is to redefine shared configuration whenever an image is needed.

### Basic example

Even if all the images on a site should be duotone or greyscale, this has to be declared whenever an image is being queried. 

The plugin should allow a default configuration for all images to be declared in `gatsby-config.js`:

```
{
  resolve: `gatsby-plugin-sharp`,
  options: {
    defaultOpts: {
      grayscale: true
    }
  },
```

Any configuration options defined here would then be applied by default, but would always be overridable in specific instances:

Default
```
resize(width: 150, height: 150) { … } // `greyscale: true` would be applied.
```

```
resize(width: 150, height: 150, grayscale: false) { … } // greyscale is overriden
```

### Motivation

This would ensure consistency and reduce duplication.  In many sites, all images are the same size, so dimensions could also be defined as a default.

**Comment by pieh** [comment]
I think this should be part of `gatsby-transformer-sharp` and not `gatsby-plugin-sharp`, but in general seems like good idea

**Comment by KyleAMathews** [comment]
Let's not do this.

We don't do this anywhere in core or plugins and this opens a pandora's box of questions around how to setup global overrides like this e.g. ensuring all options are overridable etc. + spreading this to other plugins — all of which would be ton of work for questionable amount of value.

Also this violates a core design principle that code should be explicit and not implicit. Someone reading a code base with global overrides would have to read through all the plugin configs to have any idea what is actually happening.

We add defaults where they're sensible and widely used (80%+).

**Comment by KyleAMathews** [comment]
You can also pass in arguments via `context` when creating pages in `createPages`.

**Comment by Undistraction** [comment]
> You can also pass in arguments via context when creating pages in createPages.

That's true. I guess you could push the image settings to a site configuration and pass them in there.   I think I just like that idea of a single location where the information about all the images used in the site is collected. It makes it much easier to audit images and ensure they are consistent. But I suppose it's the classic double edged sword. Push it to config / settings and make it obscure or declare at point of use and risk inconsistency.

**Comment by Undistraction** [comment]
What do you mean by global graphql variables? My understanding is that variables have to be passed into the query function?

Also, one of the things I'd personally love to work on is coming up with a library of image transforms for use in Gatsby - `gatsby-plugin-sharp` allows for grayscale and duotone which are great, but I'd love to put together a library of other image treatments for people to apply to their images. There are so many possibilities - on one end you have basic colour and gamma manipulation a la Instagram, but there are a wealth of other possibilities. These would be fantastic for someone who doesn't have access to curated photos but wants a consistent look across the site. And something like this would really benefit from a central place for image configuration.

**Comment by Undistraction** [comment]
> right — but we could set things up so you can add variables that are available in every query.

OK. I follow. This is potentially really interesting, but also quite limited I guess - I remember trying to pass an object into a query and pull props off it but it seems like that wasn't possible - so the globals would have to be strings, numbers and booleans only. Maybe that would be fine.

 > This would be incredible! And yeah, the more we go this direction, the more image "presets" would b necessary.

It's on my list of things to look at over the next month. I need to dig into Sharp's API a bit more. There is definitely a lot of potential there - compositing text onto an image, clipping etc. A lot of little things that are possible in CSS only if you don't have to support IE.
