### ISSUE TITLE
[gatsby-remark-smartypants] Triple dash not rendered

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#5538]
# Description

When setting `dashes` to `oldSchool` or `inverted` three dashes will always render an HR to the DOM. _I don't see how this could ever work because three dashes are converted to a Horizontal Rule in standard Markdown and I'm guessing this will always take priority._

### Steps to reproduce

1. Add `gatsby-remark-smartypants`
2. Use the following config:

```
{
  resolve: `gatsby-remark-smartypants`,
  options: {
    dashes: `oldschool`, // Two dashes for an en-dash, three for an em-dash
  },
}
```

3. Type three dashes in a markdown document:

```
---
```

### Expected result

According to the linked docs an em-dash should be rendered to the DOM.

### Actual result

An HR is rendered to the DOM

### Environment
* Gatsby version (`npm list gatsby`): gatsby@1.9.261
* gatsby-cli version (`gatsby --version`): gatsby-cli@1.1.52
* Node.js version: 9.3.0
* Operating System: OSX 10.11.6

**Comment by m-allanson** [comment]
This sounds like we should update the docs?

**Comment by Undistraction** [comment]
Just sat down to try and get to the bottom of this and it is working for me now. Not sure what changed but I'll reopen if it proves to be a problem again.
