### ISSUE TITLE
How to use icomoon fonts with Gatsby?

### ISSUE THREAD

**Issue by karanrajpal14** [gatsbyjs/gatsby#5546]
## Summary
Hello, I've been trying to get icomoon working on my site. Unfortunately, there's some issue with the fonts and I can't get them to load.

## Relevant information
Firstly, I open up Icomoon and pick a few icons and then while downloading I choose to have the sass version included as well.

I choose to use the sass version mainly because I have one sass stylesheet that has all my customizations and I'd like to have the icons there as well.

Now, when I download the zip, I see the following:
```
.
├── demo-files
│   ├── demo.css
│   └── demo.js
├── demo.html
├── fonts
│   ├── portfolio.eot
│   ├── portfolio.svg
│   ├── portfolio.ttf
│   └── portfolio.woff
├── ie7
│   ├── ie7.css
│   └── ie7.js
├── Read Me.txt
├── selection.json
├── style.css
├── style.scss
└── variables.scss
```

My project's tree is as follows:
```
.
├── gatsby-config.js
├── gatsby-node.js
├── package.json
├── package-lock.json
├── README.md
├── src
│   ├── components
│   │   ├── about.js
│   │   ├── Bio.js
│   │   ├── contact.js
│   │   ├── education.js
│   │   ├── footer.js
│   │   ├── hero.js
│   │   ├── profile-pic.jpg
│   │   ├── projects.js
│   │   ├── skills.js
│   │   └── work.js
│   ├── layouts
│   │   └── index.js
│   ├── pages
│   │   ├── blog.js
│   │   └── index.js
│   ├── sass
│   │   ├── main.sass
│   │   ├── style.scss
│   │   └── variables.scss
│   └── templates
│       └── blog-post.js
└── static
    ├── favicon.ico
    ├── fonts
    │   ├── portfolio.eot
    │   ├── portfolio.svg
    │   ├── portfolio.ttf
    │   └── portfolio.woff
    └── robots.txt
```

What I'm trying to do is I open up `main.sass` and then import `style.scss` which was included in the font I downloaded. I import them in `main.sass` like so:
`@import './style.scss'`

In `variables.scss` (also included in the font bundle) I need to set the path to the font files like so:
`$icomoon-font-path: "~/static/fonts" !default;`

I should be able to reference them in the css after thy're imported, correct? What ends up happening is that it can't find the font files even though the paths are correct and then the fonts don't load.

Any idea how this should be dealt with? Maybe my approach is wrong?

### Environment (if relevant)
* Gatsby version (`npm list gatsby`): 1.9.259
* gatsby-cli version (`gatsby --version`): 1.1.52
* Node.js version: 8.11.1
* Operating System: Ubuntu 17.10

**Comment by ryanditjia** [comment]
Could you try changing this `$icomoon-font-path: "~/static/fonts" !default;` to `$icomoon-font-path: "~/fonts" !default;` and see if that fixes?

Because whatever is in `static` folder will be copied to the root of the `public` folder once it’s built.

**Comment by karanrajpal14** [comment]
My apologies! The docs do mention that and I missed it.
That fixed the issue. Thank you very much @ryanditjia!
