### ISSUE TITLE
Handling files in a gatsby-source plugin

### ISSUE THREAD

**Issue by ajayns** [gatsbyjs/gatsby#5547]
I'm working on a source plugin that fetches data from a CMS. Some of its content objects may contain file types including PDFs, Video files, and so on. I was wondering what'd be the best approach to retrieving these files to the Gatsby project and querying?

I want the static site generated to be totally independent of the source site, so these files have to be downloaded locally. Is `createRemoteFileNode` what I'm looking for?

Any help, suggestions, or example use cases and such would be greatly appreciated!

**Comment by pieh** [comment]
Yes, `createRemoteFileNode` is something you want to use for that. Unfortunately there is no docs on using it, but you should be able to work it out from source code of one of the plugins that use it - for example https://github.com/gatsbyjs/gatsby/blob/2983e0f44900ba8b986369d76d26485ad5b8f506/packages/gatsby-transformer-screenshot/src/gatsby-node.js#L75-L98

We do plan on adding docs on that - any with that would be welcome

**Comment by ajayns** [comment]
Okay thanks, I'll check it out. Also, wouldn't mind contributing docs, is there anything to get started on that I can improve or do we have to write some from scratch? @pieh

**Comment by ajayns** [comment]
Also, how do you query the file which is retrieved locally using GraphQL? Is there a query to directly get the localFile URL?

**Comment by pieh** [comment]
Usually those files are not "hanging loose" and they are linked from other nodes - like in example I posted - there is `Screenshot` node which has fields `url` (so you can filter by it) and `screenshotFile` which You would use somehow

And something I missed earlier completely - we actually **do** have some docs on that function - https://www.gatsbyjs.org/packages/gatsby-source-filesystem/#createremotefilenode

**Comment by ajayns** [comment]
I have used the approaches that you've mentioned, linking the file nodes to other nodes, as per the wordpress createRemoteFileNode example and the one which you linked. Still, I'm unable to retrieve anything from `localFile` Graph query in the linked node. Any idea what could be causing this?

Ref: https://github.com/ajayns/gatsby-source-plone/blob/8e265110aace9d523118aa45ab2c422c649db6da/src/gatsby-node.js#L113-L137
