### ISSUE TITLE
Cannot resolve modules

### ISSUE THREAD

**Issue by KingLouisXVII** [gatsbyjs/gatsby#5549]
## Description

Build command on netlify fails while generating javascript bundles. Works locally with develop and build command. Any ideas what could be the problem?

### Expected result

Successfull Build.

### Actual result

` success delete html and css files from previous builds — 0.073 s
1:37:32 PM: success open and validate gatsby-config — 0.008 s
1:37:32 PM: success copy gatsby files — 0.017 s
1:37:33 PM: success onPreBootstrap — 0.297 s
1:37:33 PM: success source and transform nodes — 0.203 s
1:37:33 PM: success building schema — 0.612 s
1:37:33 PM: success createLayouts — 0.013 s
1:37:33 PM: success createPages — 0.046 s
1:37:33 PM: success createPagesStatefully — 0.020 s
1:37:33 PM: success onPreExtractQueries — 0.001 s
1:37:34 PM: success update schema — 0.164 s
1:37:34 PM: success extract queries from components — 0.099 s
1:37:35 PM: success run graphql queries — 1.411 s
1:37:35 PM: success write out page data — 0.005 s
1:37:35 PM: success write out redirect data — 0.001 s
1:37:38 PM: info bootstrap finished - 8.597 s
1:37:38 PM: success onPostBootstrap — 0.001 s
1:37:46 PM: success Building CSS — 7.439 s
1:37:56 PM: error Generating JavaScript bundles failed
1:37:57 PM: 
1:37:57 PM:   Error: ./.cache/async-requires.js
1:37:57 PM:   Module not found: Error: Cannot resolve module 'gatsby-module-loader' in /opt/  build/repo/.cache
1:37:57 PM:   resolve module gatsby-module-loader in /opt/build/repo/.cache
1:37:57 PM:     looking for modules in /opt/build/repo/node_modules
1:37:57 PM:       module variation gatsby-module-loader-webpack-loader
1:37:57 PM:         /opt/build/repo/node_modules/gatsby-module-loader-webpack-loader doesn't   exist (module as directory)
1:37:57 PM:         resolve 'file' gatsby-module-loader-webpack-loader in /opt/build/repo/no  de_modules
1:37:57 PM:           resolve file
1:37:57 PM:             /opt/build/repo/node_modules/gatsby-module-loader-webpack-loader doe  sn't exist
1:37:57 PM:             /opt/build/repo/node_modules/gatsby-module-loader-webpack-loader.web  pack-loader.js doesn't exist
1:37:57 PM:             /opt/build/repo/node_modules/gatsby-module-loader-webpack-loader.web  -loader.js doesn't exist
1:37:57 PM:             /opt/build/repo/node_modules/gatsby-module-loader-webpack-loader.loa  der.js doesn't exist
1:37:57 PM:             /opt/build/repo/node_modules/gatsby-module-loader-webpack-loader.js   doesn't exist
1:37:57 PM:       module variation gatsby-module-loader-web-loader
1:37:57 PM:         /opt/build/repo/node_modules/gatsby-module-loader-web-loader doesn't exi  st (module as directory)
1:37:57 PM:         resolve 'file' gatsby-module-loader-web-loader in /opt/build/repo/node_m  odules
1:37:57 PM:           resolve file
1:37:57 PM:             /opt/build/repo/node_modules/gatsby-module-loader-web-loader doesn't   exist
1:37:57 PM:             /opt/build/repo/node_modules/gatsby-module-loader-web-loader.webpack  -loader.js doesn't exist
1:37:57 PM:             /opt/build/repo/node_modules/gatsby-module-loader-web-loader.web-loa  der.js doesn't exist
1:37:57 PM:             /opt/build/repo/node_modules/gatsby-module-loader-web-loader.loader.  js doesn't exist
1:37:57 PM:             /opt/build/repo/node_modules/gatsby-module-loader-web-loader.js does  n't exist
1:37:57 PM:       module variation gatsby-module-loader-loader
1:37:57 PM:         /opt/build/repo/node_modules/gatsby-module-loader-loader doesn't exist (  module as directory)
1:37:57 PM:         resolve 'file' gatsby-module-loader-loader in /opt/build/repo/node_modul  es
1:37:57 PM:           resolve file
1:37:57 PM:             /opt/build/repo/node_modules/gatsby-module-loader-loader doesn't exi  st
1:37:57 PM:             /opt/build/repo/node_modules/gatsby-module-loader-loader.webpack-loa  der.js doesn't exist
1:37:57 PM:             /opt/build/repo/node_modules/gatsby-module-loader-loader.web-loader.  js doesn't exist
1:37:57 PM:             /opt/build/repo/node_modules/gatsby-module-loader-loader.loader.js d  oesn't exist
1:37:57 PM:             /opt/build/repo/node_modules/gatsby-module-loader-loader.js doesn't   exist`

### Environment
gatsby: "^1.9.250",
gatsby-cli: "^1.1.28",
Node.js version:"8.5.2",

**Comment by KingLouisXVII** [comment]
Problem solved. Had to use npm 4.* instead of 5.

**Comment by ralphstodomingo** [comment]
Can report this is an issue in Gitlab CI as well, when previously this worked well (was using a `node 8.9.4` image).

**Comment by ralphstodomingo** [comment]
I used yarn, and this was no longer an issue.
