### ISSUE TITLE
gatsby-plugin-typography breaks site in IE11?

### ISSUE THREAD

**Issue by jp887** [gatsbyjs/gatsby#5553]
The default Gatsby starter works great in IE11. However, after installing gatsby-plugin-typography I get the following error in the browser console and the app fails:
> Object doesn't support property or method 'assign'

The same error occurs for starters that use typography.js by default like the [blog starter](https://github.com/gatsbyjs/gatsby-starter-blog).

I even get this error in the console when I visit the Gatsby documentation site (which presumably uses typography.js).

I've tried adding babel-polyfill using [this method](https://github.com/gatsbyjs/gatsby/issues/2177#issuecomment-382280801) but this didn't seem to make a difference. In any case, as far as I can tell the babel-preset-env config is including a polyfill for Object.assign anyway.

The Object.assign statement that is failing seems be within typography.js code that gets included in the production bundle. I was actually slightly surprised to find typography.js code is running on the client for production builds, as I though typography.js was just used to generate styles to be added to the document head at build time?

In any case I need to support IE11 in my site. Any advice would be much appreciated.

**Comment by pieh** [comment]
I can confirm - it happens on gatsbyjs.org too in IE11

@KyleAMathews should typograhy code be included in production runtime? (not familiar with it)

**Comment by KyleAMathews** [comment]
Typography.js can also be used in the browser to style components using css-in-js. I have a refactor almost ready that'll remove this particular error.

**Comment by johnperdue** [comment]
Thanks @KyleAMathews. Out of interest what's the need to do typography styling via css-in-js for Gatsby if the styles are already rendered as css into the doc head?

**Comment by jp887** [comment]
Thanks @KyleAMathews. Out of interest what's the need to do typography styling via css-in-js in Gatsby if the css is already injected into the document head?

**Comment by jp887** [comment]
@KyleAMathews any idea when this fix will be ready? I have a site going live soon that needs to support IE11. If the fix is a still a while off I'll temporarily remove typography.js. Thanks again.

**Comment by dectys** [comment]
Same problem here with IE11, is that soon to be released or is there a quick fix ? Thanks

**Comment by mclarkos** [comment]
Not stale—still keen to see this fixed.

**Comment by TuckerWhitehouse** [comment]
This is is not stale and should be re-opened.

**Comment by wardpeet** [comment]
@TuckerWhitehouse still an issue? I couldn't reproduce it. I just followed https://www.gatsbyjs.org/docs/typography-js/
