### ISSUE TITLE
Loading plugins specifying a nested main file fail to load the plugin package.json

### ISSUE THREAD

**Issue by thekevinscott** [gatsbyjs/gatsby#5559]
## Description

I am writing a plugin. In my `package.json`, I specify a `main` entry point of `./dist/index.js`.

```
{
  ...
  "main": "dist/index.js"
}
```

When running `yarn develop`, it fails to load the plugin. 

I believe the reason is because of [these lines of code](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/bootstrap/load-plugins/load.js#L65):

```
    const resolvedPath = slash(path.dirname(require.resolve(pluginName)))

    const packageJSON = JSON.parse(
      fs.readFileSync(`${resolvedPath}/package.json`, `utf-8`)
    )
```

I believe the steps the code takes are:

1) `require.resolve` looks for the plugin's package.json
2) it finds out, and parses out the `main` field (which is `./dist/index.js`)
3) `resolvedPath` becomes `node_modules/plugin/dist/`
4) gatsby is unable to find a `package.json` at `node_modules/plugin/dist/` and throws an error.

This is solvable in my particular case by copying the `package.json` file into the dist folder as part of the plugin build process, but that feels like a bit of a hack.

I'm happy to try opening a PR but I'd like guidance from the team as to whether this is something worth fixing or not, and if so, the best way to do so.

### Steps to reproduce

Clone this repo:

https://github.com/thekevinscott/gatsby-demonstrating-plugin-bug

Don't install modules, I've checked them into the repo (since a particular plugin format is what fails).

Run:

```
yarn develop
```

In the console, you should see errors as to why this fails.

### Expected result

It should load the plugin

### Actual result

It fails to load the plugin

### Environment
* Gatsby version (`npm list gatsby`): gatsby@1.9.250
* gatsby-cli version (`gatsby --version`): 1.1.28
* Node.js version: v8.9.4
* Operating System: macOS 10.13.4

### File contents (if changed)
`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by thekevinscott** [comment]
Ah, I see. 

I have my code in a src folder, since I'm transpiling it. I wanted to build to a dedicated dist folder to make cleanup and organization better. 

Assuming that's no good, are there any examples of how other plugin authors have handled a transpiling step?

**Comment by pieh** [comment]
I think all plugins in monorepo are being transpiled.

Usually we have `src` directory and then babel would output transpiled files to main plugin directory (which is where gatsby will look for `gatsby-*` files. For example - https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-filesystem
