### ISSUE TITLE
Running into bug when using react-fullpage with Gatsby

### ISSUE THREAD

**Issue by jskrt** [gatsbyjs/gatsby#5561]
## Description

Running into the following error when trying to use react-fullpage with gatsby:

https://imgur.com/a/WYJO58b

### Steps to reproduce

Should be as straightforward as using SectionsContainer tag when using the react-fullpage component.

### Expected result

Should render a page with content.

### Actual result

See image showcasing the error.

### Environment
* Gatsby version (`npm list gatsby`): 1.9.261
* gatsby-cli version (`gatsby --version`): 1.1.52
* Node.js version: 8.10.0
* Operating System: Mac OS

**Comment by pieh** [comment]
This seem like issue in `react-fullpage` - https://github.com/subtirelumihail/react-fullpage/issues/59

**Comment by daydream05** [comment]
I created a pull request on react-fullpage's repo that fixes this. In the meantime, you can use my forked [repo](https://github.com/daydream05/react-fullpage)
