### ISSUE TITLE
How to call command of Gatsby (build and develop) from javascript? (e.g Electron)

### ISSUE THREAD

**Issue by muukii** [gatsbyjs/gatsby#5562]
I'm creating the Electron app for Gatsby.
I would like to run the command of Gatsby from Electron.
But, I don't know how to call command of Gatsby from JavaScript.

Can I call it from JavaScript?

Thank you.

**Comment by pieh** [comment]
check [`gatsby-cli`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/create-cli.js) invokes commands. Or spawn process in Electron that runs `gatsby develop`/`build`

**Comment by muukii** [comment]
@pieh Thank you!
I'll try it
