### ISSUE TITLE
[docs] Deploy to Surge

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#5563]
## Summary

There are currently no docs for deploying to [Surge](https://surge.sh/) on the deploy page [here](https://www.gatsbyjs.org/docs/deploy-gatsby/) 

Would you accept a PR adding info on deploying to surge? It's probably the simplest deploy around.

**Comment by ryanditjia** [comment]
Since [tutorial](https://www.gatsbyjs.org/tutorial/part-one/#deploying-gatsbyjs-websites) uses Surge, I believe adding it to the docs should be okay.

**Comment by pieh** [comment]
@Undistraction PR would most certainly be welcome!

**Comment by Undistraction** [comment]
@pieh Thanks. I'll put something together tomorrow.

**Comment by marcysutton** [comment]
Hi @Undistraction, any interest in still creating a PR for a Surge deployment doc? I got a question about it and found this closed issue. We would definitely love a contribution!

**Comment by hydrosquall** [comment]
Hi @marcysutton, I'll open a PR to take care of a first pass at this.
