### ISSUE TITLE
Having trouble using particlesjs with Gatsby

### ISSUE THREAD

**Issue by jskrt** [gatsbyjs/gatsby#5565]
## Description

I incorporate particlesjs using the react component react-particles-js. I want to use it as the background for a page but when the page loads, the particles show up but I cannot interact with them through my mouse.

### Steps to reproduce

All I did was incorporate particles js into my code. Here is my code:

setup: https://paste.ofcode.org/GLPYADa6H98DiEbYycR4LN 

render function: https://paste.ofcode.org/34sLWSti9eESF3ukda3UhUx

CSS: https://paste.ofcode.org/fUWtbm3m5QdBWAAjipwv9u

### Expected result

Should be the text with the particles as a background (white particles+lines, black background). Should be able to interact with the particles using mouse movement and clicks.

### Actual result

Particles show up but no interaction possible whatsoever.

### Environment
* Gatsby version (`npm list gatsby`): 1.9.261
* gatsby-cli version (`gatsby --version`):  1.1.52
* Node.js version: 8.10.0
* Operating System: Mac OS

**Comment by ryanditjia** [comment]
I have no experience with `react-particles-js` nor `fullpage-react` but my hunch says it could be one of 2 things:

- `FullPage` component sits above `Particles` in terms of z-index and tampers with mouse events
- A mistake with `Particles` params causing it to not respond to mouse events

Another thing could be that particles-js references `window` global. But this should only cause Gatsby to error out during build.

Can you try using `Particles` without `FullPage`? If problem persists, check if your `Particles` work with create-react-app.

**Comment by jskrt** [comment]
Got the particles working after removing fullpage. I think I can accomplish what I want to without it, although it would be nice to be able to use it in a straightforward manner as I did in create-react-app. 

Running into the problem of not being able to scroll now, though. Here's the updated code:

https://paste.ofcode.org/36HPdMNbDq7PgqF7zCACNCW

I don't have anything about overflow in my CSS. Just that the height of .Mission should be 100vh to recreate that fullscreen effect.

**Comment by pieh** [comment]
If gatsby renders particles component and there are any problems, it most likely mean problem in your code or with particles component and not in gatsby. For following issues, please create repository that other people can use to reproduce the problem (from pasted code samples nothing indicate problem, but I can't reproduce it without rest of your code).
