### ISSUE TITLE
Static website without JS bundle?

### ISSUE THREAD

**Issue by AriaFallah** [gatsbyjs/gatsby#5566]
Is there any way to generate a website that has no need to build the JS or add a bundle to the page? I really like React as a templating language and the tooling that Gatsby has created around it, but don't actually want to load React or anything else on the frontend.

https://github.com/gatsbyjs/gatsby/issues/962 touched upon this a year ago, but the answer there was, to me, unsatisfactory because flipkart, the example used to describe how PWAs are better, is a full fledged online store whereas most Gatsby projects are much simpler.

**Comment by pieh** [comment]
You could edit edit `html.js` ( https://www.gatsbyjs.org/docs/custom-html/ ) to not include js assets in head (would still get generated), but you would a lot of functionality like page prefetching and in-browser navigation, lazy image loading, etc.

**Comment by AriaFallah** [comment]
@pieh thanks!

It's not a big deal for me as my pages are smaller than the JS bundle that would enable that functionality 😛
