### ISSUE TITLE
Consider using Pundle over Webpack

### ISSUE THREAD

**Issue by ncammarata** [gatsbyjs/gatsby#557]
https://github.com/motion/pundle

Pundle's main goals are a simpler API and faster HMR. For applications like blogs, fast HMR can be great, because you can do things like turn off explicit saving in your editor (save on every keystroke) and get an experience where you can type while looking at your blog, rather than your text editor.

**Comment by KyleAMathews** [comment]
I'd love faster HMR than Webpack but... Gatsby uses a ton of advanced Webpack features e.g. code splitting, bundle naming, creating a "commons" bundle (Webpack figures out what modules are used the most and puts them in their own bundle), hashed file names, offline-plugin (which adds service worker + offline support) etc. Also Webpack lets Gatsby easily support basically every flavor of anything Web pretty easily as someone has already made a loader for it.

As I understand it, Pundle doesn't support some of these things yet?

**Comment by ncammarata** [comment]
Ah, you're correct that this is a bit early for Pundle. Makes sense if you need to access such low-level features of the bundler. Maybe one day!
