### ISSUE TITLE
Custom Javascript in Gatsby JS

### ISSUE THREAD

**Issue by gabedeko** [gatsbyjs/gatsby#5570]
I've create a few small script functions that I want triggered every time a page loads or is refreshed. Below is an example of one built for the third party library Anime JS but it's mostly arbitrary since it's the same issue for all my script functions.

```
import anime from 'animejs'

    if (typeof window !== `undefined`) {
      var bioLayerIn = anime.timeline();
      bioLayerIn
      .add({
        targets: ['.color-layer'],
        translateX: '100%',
        easing: 'easeInOutQuint',
        duration: 400
      })
      .add({
        targets: ['.color-layer'],
        translateX: '200.1%',
        easing: 'easeInOutQuint',
        duration: 430,
        delay:5
      });
      }
```

For some reason **it only runs once** when I edit the script and save it and never again until I make a change to the script and save it again. I'm not sure how to make Gatsby/React have it run how javascript functions traditionally run which is every time the page is loaded/refreshed. I'm sure this has to do with the way Gatsby links and routes it's pages.

I've I know Gatsby deals with custom JS differently since it's being built on a framework but there's no clear answer in Gatsby's documentation that explains this. [This](https://www.gatsbyjs.org/docs/custom-html/) page discusses adding custom js but not if it's for a third party library

Currently my script lives in **/src/js/custom.js**

**Comment by pieh** [comment]
That's because your code will run only once it's loaded (it won't be reloaded when you switch pages). You need to use https://www.gatsbyjs.org/docs/browser-apis/#onRouteUpdate to hook into route change event in `gatsby-browser.js`
