### ISSUE TITLE
Docs Error: Tutorial Part 6

### ISSUE THREAD

**Issue by dominictwlee** [gatsbyjs/gatsby#5571]
I'm just going through gatsby tutorials right now (absolutely amazing btw, probably one of the most intuitive static site generators I've used) and I think there might be a slight error in one of the snippets used in part six of the tutorial.

In this snippet:
![gatsby-docs-tutorial-6](https://user-images.githubusercontent.com/34794189/40591572-89ad121e-620b-11e8-98e5-c56dc206d29b.png)

Looking through the schema in GraphiQL, it only takes a string I don't believe date can take the argument formatString, and thus will throw an error.

I'm happy to do a pull request and amend it if that's the case. If not, sorry for being completely ignorant!

**Comment by pieh** [comment]
Date type fields DO have formatString argument (we even use it in gatsbyjs.org site - https://github.com/gatsbyjs/gatsby/blob/master/www/src/templates/template-blog-post.js#L310 ) - if you don't have it, it means gatsby didn't recognize that field as date type - which would mean you probably used not supported date format in your frontmatter (i mean value - field name doesn't matter here). Here's list of supported formats: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/types/type-date.js#L11-L41

**Comment by dominictwlee** [comment]
@pieh Thanks for clarifying that for me.
