### ISSUE TITLE
Where to place a single API request

### ISSUE THREAD

**Issue by tsmith123** [gatsbyjs/gatsby#5582]
I'm busy converting my site into a Gatsby version. I would like to make a request to my own API to fetch some exchange rates and I'm wondering where I should put this so that it only executes once.

It should happen when a user visits any page but if they then navigate to other pages then it should not fetch any data.

Is there some kind of "parent" container that I can place this call?

**Comment by ryanditjia** [comment]
I believe you can accomplish this by setting a flag in Layout (`src/layouts/index.js`) component, which is the parent container of every page. Something like (`state = { fetched: true }`) should do the trick.

Gatsby v2 removes this special Layout component though. If you want to be future-proof, you can use React Context to contain this global state instead.

**Comment by tsmith123** [comment]
Ok, this is a possibility but how can pass the data down to components?

**Comment by pieh** [comment]
@tsmith123  Check https://github.com/gatsbyjs/gatsby/issues/2112#issuecomment-329452753 how to pass props from layout to pages.

Or you could make use of one of global state managment libraries (if your usage would justify including them and making your runtime bundles heavier)
