### ISSUE TITLE
ACF with repeater images build failure - image upload problem

### ISSUE THREAD

**Issue by margaretlydon** [gatsbyjs/gatsby#5587]
Hi folks, 

I am experiencing a build failure with a repeater image on a wordpress page. There is another bug identical in symptom to this which has been closed, but folks are still experiencing it and I think i have more information to offer, so please bear with me a minute. 

In my custom field configuration I have a repeater field with an image member of type image with a return value of "image array". This is a mandatory field, so a user always has to populate it when adding a new row to the repeater on their page. The previous bug was mainly attributed to the fact that wordpress will return a "false" instead of an object if the image isn't populated. This is different. 

This is the piece of graphql on my page which grabs the image:

```
			acf {
				resources {
					resource_name
					resource_image {
						url
					}
					resource_link
					resource_type
				}
			}
```

this is how to reproduce the bug:

add an image to the media library using the media library page. go to your page with the repeater and select this image from the library. build. the build happens merrily, yay!

now add an image to the repeater on your page while you are on the page, instead of loading it up through the media page. build. the build fails like this:

```
error GraphQL Error Unknown field `url` on type `wordpress__wp_media`
  file: /buddy/toolkittechtrailscom-gatsby/src/templates/page-helpful-link.js
   2 | 	query helpfulLinkQuery($id: String!) {
   3 | 		wordpressPage(id: { eq: $id }) {
   4 | 			title
   5 | 			content
   6 | 			date(formatString: "MMMM DD, YYYY")
   7 | 			wordpress_id
   8 | 			acf {
   9 | 				resources {
  10 | 					resource_name
  11 | 					resource_image {
> 12 | 						url
     | 						^
  13 | 					}
  14 | 					resource_link
  15 | 					resource_type
  16 | 				}
  17 | 			}
  18 | 			yoast {
  19 | 				metadesc
  20 | 			}
  21 | 		}
  22 | 		site {
error Command failed with exit code 1.
```

looking into it, i ran this query in my wordpress database:

```
select * from wp_postmeta, wp_posts
where wp_postmeta.post_id = 410 
and wp_postmeta.meta_key like '%resource_image%' 
and wp_posts.id = wp_postmeta.meta_value
order by wp_postmeta.meta_key;
```

410 is the id of the post that i am interested in. the wp_postmeta table is where wordpress stores custom fields. the wp_posts table is where wordpress stores a bunch of stuff, mainly posts/pages, but also images. kind of crazy, i know, but in wordpress an image is a post of type 'resource_image'. On the wp_post page there is a field called post_parent which for an image type post, represents the page on which the image was uploaded, kind of, but that's true enough for our situation. For the image which was uploaded while i was on page id 410 as opposed to being in the media folder, the post_parent id was 410 aswell as the wp_postmeta.post_id value being 410. this is most assuredly the cause of the problem. when i update the wp_posts.post_parent id value to by anything other than the page_id of the page which houses my custom fields, the build succeeds. 

For anyone who is experiencing this problem, a workaround is to always upload your images to the media directory. If you already have an image which has been uploaded to the page, go to the media library and search for it. On the list there is a column which says "uploaded to". This will show the page which houses your custom field data. Click on detach and you should be able to build now. 

Looking forward to any updates which may fix this problem, it is causing a lot of issues for me, as I work for clients who upload their own content, and trying to get them to follow steps while editing content is pretty painful. 

Thanks for your time,
Margaret

**Comment by pieh** [comment]
Hmmm, I'm not sure I follow - I don't have `url` field in my example wordpress media objects (where you show error) - closest thing to that is `source_url` but You would rather want to use `localFile` there.

**Comment by pieh** [comment]
Can you setup minimal repository to reproduce this problem?

**Comment by kakadiadarpan** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub issues, we have to clean some of the old issues as many of them have already been resolved with the latest updates.

Please make sure to update to the latest Gatsby version and check if that solves the issue. Let us know if that works for you by adding a comment 👍

**Comment by kakadiadarpan** [comment]
This issue is being closed because there hasn't been any activity for at least 30 days. Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem 👍
