### ISSUE TITLE
[v2] Add error handling for setWebpackConfig => onCreateWebpackConfig migration

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#5591]
## Description

As it stands, the error message for using `setWebpackConfig` in v2 suggests using `onCreateWebpackConfig` but doesn’t mention the API changes, which means that after switching over you hit a new error:

```
TypeError: Cannot read property 'loader' of undefined
```

https://github.com/gatsbyjs/gatsby/blob/v2/packages/gatsby/src/utils/api-node-docs.js#L151-L179

Potential solutions:

- Add more information to the error message when `setWebpackConfig` is encountered
- Add error handling that checks for the old API and links to docs for the new API
- [probably not worth it] a codemod

### Environment
* Gatsby version (`npm list gatsby`): `gatsby@2.0.0-alpha.42`

**Comment by m-allanson** [comment]
Add a link to https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#change-modifywebpackconfig-to-oncreatewebpackconfig
