### ISSUE TITLE
[v2] Update examples in v2 branch

### ISSUE THREAD

**Issue by camsjams** [gatsbyjs/gatsby#5598]
## Summary
Some of the examples in the v2 branch https://github.com/gatsbyjs/gatsby/tree/v2/examples

Have package.json versions pointed at `latest` instead of `next` - is this intentional?

Examples include:
https://github.com/gatsbyjs/gatsby/blob/v2/examples/using-styled-components/package.json
https://github.com/gatsbyjs/gatsby/blob/v2/examples/using-redux/package.json

**Comment by m-allanson** [comment]
Upgrading the examples is still a work in progress - any help would be very welcome! 

Although note that the v2 upgrade guide hasn't been written yet, so you'll need to rely on checking how other examples have been changed and the placeholder [breaking changes list](https://github.com/gatsbyjs/gatsby/blob/v2/Breaking%20Changes.md).

If anyone wants to take any of these on, I'm happy to provide any guidance needed.

**Comment by pieh** [comment]
I added this issue to v2 project, so people can discover it easier if they want to help out on v2

**Comment by webwurst** [comment]
It would be nice to have a list of already ported and yet to be done examples :)

**Comment by m-allanson** [comment]
A list would be excellent - would you like to make one and and add it here?

You can check the `package.json` of each example to see which ones have been upgraded. For examples running on `v2`, their Gatsby dependencies will be using the `next` version and have `react` and `react-dom` included:

https://github.com/gatsbyjs/gatsby/blob/d0e29272ed7b009dae18d35d41a45e700cdcab0d/examples/image-processing/package.json#L8-L18

Examples running on v1 will have different version numbers and no `react` or `react-dom`:

https://github.com/gatsbyjs/gatsby/blob/d0e29272ed7b009dae18d35d41a45e700cdcab0d/examples/using-remark-copy-linked-files/package.json#L7-L20

**Comment by m-allanson** [comment]
Oh and there's a work-in-progress migration guide at https://github.com/gatsbyjs/gatsby/pull/5575/files

**Comment by webwurst** [comment]
Examples migrated to `v2`:
- [ ] [Client-only paths](https://github.com/gatsbyjs/gatsby/tree/v2/examples/client-only-paths)
- [ ] [RSS Feed Example](https://github.com/gatsbyjs/gatsby/tree/v2/examples/feed)
- [x] [Gatsbygram](https://github.com/gatsbyjs/gatsby/tree/v2/examples/gatsbygram)
- [ ] [Gatsby Hacker News](https://github.com/gatsbyjs/gatsby/tree/v2/examples/hn)
- [x] [Image Processing](https://github.com/gatsbyjs/gatsby/tree/v2/examples/image-processing)
- [ ] [No plugins](https://github.com/gatsbyjs/gatsby/tree/v2/examples/no-plugins)
- [ ] [No trailing slashes](https://github.com/gatsbyjs/gatsby/tree/v2/examples/no-trailing-slashes)
- [ ] [Gatsby Authentication Demo](https://github.com/gatsbyjs/gatsby/tree/v2/examples/simple-auth)
- [ ] [Sitemap](https://github.com/gatsbyjs/gatsby/tree/v2/examples/sitemap)
- [ ] [Gatsby Styleguide Example](https://github.com/gatsbyjs/gatsby/tree/v2/examples/styleguide)
- [x] [Using Drupal](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-asciidoc)
- [x] [Using Contentful](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-contentful)
- [ ] [using-css-modules](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-css-modules)
- [ ] [using-csv](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-csv)
- [x] [Using Drupal](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-drupal)
- [ ] [using-emotion-prismjs](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-emotion-prismjs)
- [ ] [using-emotion](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-emotion)
- [ ] [using-excel](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-excel)
- [x] [Using Faker](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-faker)
- [x] [Using Gatsby Image](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-gatsby-image)
- [ ] [Using Glamor](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-glamor)
- [x] [using-hjson](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-hjson)
- [ ] [Using Javascript Transforms](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-javascript-transforms)
- [ ] [Using JSS](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-jss)
- [ ] [Using Medium](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-medium)
- [ ] [using-mongodb](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-mongodb)
- [ ] [using-page-loading-indicator](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-page-loading-indicator)
- [ ] [using-page-transitions](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-page-transitions)
- [ ] [using-path-prefix](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-path-prefix)
- [ ] [using-react-native-web](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-react-native-web)
- [ ] [using-react-url-query](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-react-url-query)
- [ ] [using-redirects](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-redirects)
- [ ] [Redux](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-redux)
- [ ] [using-gatsby-remark-copy-linked-files](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-remark-copy-linked-files)
- [x] [Using remark](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-remark)
- [x] [Using gatsby-plugin-sass](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-sass)
- [ ] [(using-sqip)](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-sqip)
- [ ] [Using Styled Components](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-styled-components)
- [x] [using-styled-jsx](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-styled-jsx)
- [ ] [Using Styletron CSS-in-JS engine](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-styletron)
- [x] [Using gatsby-plugin-stylus](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-stylus)
- [ ] [using-typescript](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-typescript)
- [x] [Using Wordpress](https://github.com/gatsbyjs/gatsby/tree/v2/examples/using-wordpress)

**Comment by piotrkwiecinski** [comment]
I could probably grab sitemap one for start :). Happy to help

**Comment by m-allanson** [comment]
😍 for all the pull requests updating these examples. Keep 'em coming :)

**Comment by piotrkwiecinski** [comment]
RSS feed one has similar issue as sitemap. It's quite basic. I'll try to PR extended version to master first over the weekend.

**Comment by ryanditjia** [comment]
I’m getting errors with source-hacker-news.

```
⠠ source and transform nodesfetch HN data: 17699.665ms
success source and transform nodes — 23.070 s
error UNHANDLED REJECTION


  TypeError: Cannot read property 'internal' of undefined

 - build-node-types.js:85 _.flatMap.groupBy.node
    [project-name]/[gatsby]/dist/schema/build-node-typ    es.js:85:55

  - lodash.js:489 arrayAggregator
    [project-name]/[lodash]/lodash.js:489:34

  - lodash.js:4835 Function.groupBy
    [project-name]/[lodash]/lodash.js:4835:16

  - lodash.js:4380
    [project-name]/[lodash]/lodash.js:4380:28

  - lodash.js:675 arrayReduce
    [project-name]/[lodash]/lodash.js:675:21

  - lodash.js:4379 baseWrapperValue
    [project-name]/[lodash]/lodash.js:4379:14

  - lodash.js:9042 LodashWrapper.wrapperValue
    [project-name]/[lodash]/lodash.js:9042:14

  - build-node-types.js:85 createNodeFields
    [project-name]/[gatsby]/dist/schema/build-node-typ    es.js:85:111

  - build-node-types.js:171 fields
    [project-name]/[gatsby]/dist/schema/build-node-typ    es.js:171:23

  - Array.forEach

  npm ERR!
```

**Comment by ajayns** [comment]
@ryanditjia I'm getting the same errors. Looks like an issue with the plugin itself. 

Also, going through using-javascript-transforms example, I'm unsure of what's going wrong but looks like it keeps throwing `exports is undefined` errors.

**Comment by m-allanson** [comment]
Thanks everyone for your help with this issue 🎉 Marking this as done.
