### ISSUE TITLE
[v2] Additional changes to tutorial

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#5607]
- [ ] Finish part 8 (@KyleAMathews will do this)
- [ ] Link to part 8 from the tutorial overview page
- [ ] Convert glamorous to use emotion (~~this is up for grabs!~~ grabbed by @ryanditjia)

**Comment by ryanditjia** [comment]
What style of emotion should be used?

I think `css` + string template literals is pretty nice for people new to CSS-in-JS.

But `styled` is shinier 😄.

I’m familiar with using both styles and can help with this.

**Comment by m-allanson** [comment]
I've not used emotion too much, so don't have a strong preference either way! It sounds like `css` with string template literals will be accessible to more people so maybe go that way?

**Comment by KyleAMathews** [comment]
Let's use the css prop since that's supported out of the box with gatsby-plugin-emotion.

**Comment by m-allanson** [comment]
Closing this as it's two issues and one part has been done - thanks @ryanditjia 👍

Moving the other parts to #6571
