### ISSUE TITLE
Emphasize file names

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#5608]
Before people copy and past code, make sure they know WHERE to paste it by emphasizing the file names. People often miss the name of the file or directory where the code is supposed to go.

**Comment by tulikavijay** [comment]
I want to work on this ...where should i start??

**Comment by Aloysb** [comment]
Hi!

I will work on this now if still available.

Cheers

**Comment by shannonbux** [comment]
Oh man, @tulikavijay and @Aloysb I apologize for the late response! Yes, this is still available. It would be useful to make the name of each file where people are supposed to paste their code more emphasized (probably a level 4 header, or at least bold or something). I've noticed that people often paste their code into the wrong place! I'm open to other ideas of how to solve this problem, too!

**Comment by Aloysb** [comment]
No worries! I'll have a go at it.

**Comment by shannonbux** [comment]
Sounds great @Aloysb! Why don't you try it with just one page of the tutorial to test out the idea and see if the community likes it before editing all the pages. Thanks for volunteering for this!

**Comment by Aloysb** [comment]
@shannonbux Ok, I tried to do a PR on this issue but I don't know if I am doing this right (I am new to this). Help would be welcomed! :)

I tried to do the PR to the V1 branch as asked for modifications to docs, but I had 700+ commits, mostly other people's work... So I thought something is wrong! To "master", only my changes appeared, so I did the PR to Master. I hope I am not creating a mess here!

There it is:
https://github.com/gatsbyjs/gatsby/pull/6220

Thanks.

**Comment by shannonbux** [comment]
Hi @Aloysb yes, it is a bit confusing right now because we have v1 and master versions of the docs! Apologies for the difficulty that creates. I did the exact same thing the other day: I wrote a blogpost and when I tried to merge it into v1, I also had 700+ conflicts with the v1 branch because I had already updated my local version of Gatsby to master. So I just merged the PR to master and then @m-allanson "cherry picked" or just copied the blogpost over to v1 so that it could reside in both branches. Hopefully this will get less confusing pretty soon :)

**Comment by shannonbux** [comment]
Saving this image @Aloysb--thanks! If anyone wants to pick up the work left over from #6220, that would be great!

![image](https://user-images.githubusercontent.com/32467162/45039076-0c80a680-b020-11e8-99a3-50e5d1f7f822.png)

**Comment by DSchau** [comment]
@shannonbux I think I can take this. I even wrote something a while ago to do just this :)

[The plugin](https://www.npmjs.com/package/gatsby-remark-code-titles) | [Example](https://objectpartners.netlify.com/2018/01/11/migrating-a-wordpress-powered-site-to-gatsbyjs)

**Comment by shannonbux** [comment]
Wow awesome @DSchau--that'd be great! 

This + a copy/paste button would resolve about 80% of problems we saw happen in our first Gatsby workshop back in April :)

**Comment by kakadiadarpan** [comment]
@shannonbux @DSchau is this issue fixed?

**Comment by DSchau** [comment]
@kakadiadarpan thanks for circling back!

It is _done_ but I'd still like to do the copy snippet at some point. That said, the actual issue itself we should call done, so I'll close!

**Comment by DSchau** [comment]
Note: we should also open another issue to actually use the functionality (i.e. add it to tutorials and blog posts!) so we can get some community members involved!

**Comment by kakadiadarpan** [comment]
@DSchau we already have another issue open for copy snippet functionality #5030

**Comment by DSchau** [comment]
@kakadiadarpan I meant an issue for people to actually tie into the title functionality. Basically I've implemented the functionality so that it's available, but very few tutorials/posts are actually using it currently!

**Comment by kakadiadarpan** [comment]
Got it, thanks for the clarification! 😄
