### ISSUE TITLE
Tutorials: say "edit the GraphQL query"

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#5609]
When people are new to GraphQL, they can get confused on what area of the file is a query and what's not. So when the tutorial asks them to "edit the query," it might be better to say "edit the GraphQL query"

**Comment by ajayns** [comment]
Would like to help out if you could point me to where exactly do you need these changes.

**Comment by leonardo-garcia** [comment]
Do you mean this tutorial?
https://www.gatsbyjs.org/tutorial/part-four/

**Comment by gvarandas** [comment]
Created the PR #6890 to start to attack this issue. ❤️

**Comment by m-allanson** [comment]
Hey @daliadefelipee it looks like there are a few places in parts six and seven of the tutorial where it'd be useful to do this.

- [Here's where the source for the tutorials is](https://github.com/gatsbyjs/gatsby/tree/master/docs/tutorial)
- [And here's where the tutorial is published](https://next.gatsbyjs.org/tutorial/part-six/)

shout if you need some more info!

**Comment by shannonbux** [comment]
Thanks for working on these tasks, @daliadefelipee and @gvarandas! And
thanks for the suggestions, @m-allanson!

**Comment by mikelax** [comment]
Closing this issue, the referenced PR seems to have made the text updates within the relevant tutorial sections
