### ISSUE TITLE
Speed up Netlify builds with caching

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#5613]
## Summary

Netlify has an undocumented feature that allows a persistent cache between builds. For sites that are generating a lot of image thumbnails and other time-intensive tasks, being able to cache that work between builds could be a huge time saver.

The feature isn't documented, but two examples exist that we can pull from:

- This article from Contentful includes [caching example code](https://www.contentful.com/blog/2018/05/17/faster-static-site-builds-part-one-process-only-what-you-need/#caching-for-the-win)
- @philhawksworth shared a [demo project](https://github.com/philhawksworth/content-shards) that leverages Netlify's cache for faster builds

From a conversation with @KyleAMathews, it sounds like [`gatsby-plugin-netlify`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-netlify) could potentially leverage this cache (either by copying the caches or symlinking) to make subsequent Gatsby builds on Netlify _significantly_ faster.

### Motivation

Generating images takes a lot of time and doesn't require duplicate work between builds. Gatsby already has a great cache, so if we can get Netlify to persist that cache between builds, we're able to get a big speed boost for Gatsby developers using Netlify with a relatively low effort.

**Comment by axe312ger** [comment]
hmm... "done" 😅 

see #5662

**Comment by axe312ger** [comment]
As discussed on Discord, this won't be merged into the Gatsby core repository.

I published it to npm and created a separate repo. Lets continue over there:
* https://www.npmjs.com/package/gatsby-plugin-netlify-cache
* https://github.com/axe312ger/gatsby-plugin-netlify-cache

I guess we can close this issue and do further discussions within the other repo @jlengstorf

**Comment by jlengstorf** [comment]
Sounds good. Thanks again for taking the lead on this, @axe312ger!
