### ISSUE TITLE
[gatsby-plugin-styled-components] url() not transformed in styled component

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#5615]
I'm flagging this for two reasons:

1. Hopefully it will be easily discoverable for someone looking to understand why this isn't working and looking for a workaround (see below).

2. Although this might not be a bug exactly, this behaviour isn't great and is inconsistent and I'm wondering if it can be improved. 

## Description

When using the CSS function `url()` with a styled component, the referenced image is not copied to `public/static` and path of the image is not replaced in the generated CSS

### Steps to reproduce

Inside a standard CSS file the following styles:

```
body {
  background-image: url('../../images/example.png');
}
```

Will be transformed (correctly) to:

```
body {
  background-image: url(http://localhost:8000/static/example.png);
}
```

And the image will be coped to public during build. 

However inside a styled component in the same directory:

```
const Example = styled.div`
  background-image: url('../../images/example.png');
`
```

URL not transformed and image isn't copied to public during build.

### Workaround

The image can be directly referenced using an import, then the import interpolated into the url:

```
import image from '../../images/example.png'

const Example = styled.div`
  background-image: url(${image});
`
```

### Improvement

When`url()` is used inside a styled component, the path should be transformed and the referenced image copied across to `public/static`.

### Environment
* Gatsby version (`npm list gatsby`): 1.9.259
* gatsby-cli version (`gatsby --version`): 1.1.51
* Node.js version: npm list gatsby
* Operating System: OSX: 10.11.6

### File contents (if changed)
`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by m-allanson** [comment]
As far as I can tell this expected way to import images with webpack and Styled Components. I'd love to be proven wrong though :) 

It'd be good to add this pattern to `gatsby-plugin-styled-components`'s readme.

**Comment by eugenehp** [comment]
any hints on what's the best way to implement this one?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
