### ISSUE TITLE
Stuck in installation step

### ISSUE THREAD

**Issue by droidMakk** [gatsbyjs/gatsby#5634]
## Summary
I tried to install gatsby-cli using yarn but i've stuck in this windows-build-tools setup for the past few hours. Yet it's not completed. Please find the reference image below.
PS: I tried using npm it got installed but gatsby develop is throwing out an error. Unsupport win32 directory structure and it was on a boilerplate.
<img width="484" alt="gatsby-cli" src="https://user-images.githubusercontent.com/20293708/40791945-40176556-6516-11e8-8969-c0ebdafdefff.PNG">

### Environment (if relevant)
* Gatsby version (`npm list gatsby`):
* gatsby-cli version (`gatsby --version`):
* Node.js version: v9.6.1
* Operating System: Win10 x64 ( Creator's Update )

### File contents (if changed)
`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by robsonpf** [comment]
I install the gatsby-cli package i don't know if is the role issue.

**Comment by ralphstodomingo** [comment]
Have used yarn for this as well, and `windows-build-tools` is a bit large but it usually pulls through in our case.
Also, I suggest either sticking with npm or yarn, not both.
What boilerplate might you be talking about and can we take a look at this structure?

**Comment by droidMakk** [comment]
Is it something like the size of windows build tools is large. So I need to wait till it's done

**Comment by pieh** [comment]
Please check https://github.com/felixrieseberg/windows-build-tools/issues/47 or report this issue there. That's outside of something that gatsby can fix
