### ISSUE TITLE
Dynamic GrapQL Query Fields

### ISSUE THREAD

**Issue by pungggi** [gatsbyjs/gatsby#5635]
I searched about dynamic queries but did not found exactly what I am looking for, so my question:

Is it possible to pass Query Variables to be used as Fields?

Let me explain with an example:

```graphql
query SpecificationsTemplateQuery($categoryName: String, $fields: datasheet_2) {
  allSpecificationsYaml(filter: {categoryName: {eq: $categoryName}}) {
    edges {
      node {
        title
        datasheet {
          $fields
        }
      }
    }
  }
}
```

This is similar idea> https://github.com/apollographql/react-apollo/issues/330#issuecomment-299354804

**Comment by jquense** [comment]
unfortunately no, there is no way to do this. GraphQL variables don't work like that, we'de need to see it added to the spec :/
