### ISSUE TITLE
After upgrading to version 1.9.264, site is blank and status code is 404

### ISSUE THREAD

**Issue by domachine** [gatsbyjs/gatsby#5636]
## Description

I just upgraded gatsby from version 1.9.250 to 1.9.264. Before that upgrade my site was working fine in development mode. After the upgrade all pages yield blank output with a 404 as status code.

### Steps to reproduce

1. `gatsby new test`
2. `cd test; npm i gatsby@latest`
3. `npm run develop`
4. Visit `http://localhost:8000` in the browser

### Expected result

A sample page.

### Actual result

A blank page with HTTP status 404.

### Environment
* Gatsby version (1.9.264):
* gatsby-cli version (1.1.52):
* Node.js version: v8.9.4
* Operating System: Mac OS X

### File contents (if changed)
`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by wiesson** [comment]
Same here. 

Node: v10.3.0

**Comment by WebD00D** [comment]
Noticing this same issue.

**Comment by pieh** [comment]
Can you downgrade to `gatsby@1.9.262` and see if this fixes problem? I'm working on fix right now

**Comment by WebD00D** [comment]
@pieh downgrading to `1.9.262` fixes

**Comment by m-allanson** [comment]
This is fixed by https://github.com/gatsbyjs/gatsby/pull/5630

**Comment by KyleAMathews** [comment]
I reverted https://github.com/gatsbyjs/gatsby/pull/4756 which was the source of these troubles. Sorry for the bother everyone! Thing are back to working.

**Comment by rdela** [comment]
@m-allanson @pieh @KyleAMathews The downgrade should work, `build` command also hosed like `develop` as Kyle suggests in https://github.com/gatsbyjs/gatsby/pull/4756#issuecomment-393637140

Will add a more complete report of my issue over there but https://github.com/GraphCMS/gatsby-graphcms-example/pull/72#issuecomment-393635255
has the gist with links.

**Comment by KyleAMathews** [comment]
@rdela reverted the PR causing the trouble so things are working again. Thanks for the detailed bug report!

**Comment by rdela** [comment]
Upgrading to Gatsby `1.9.266` with #4756 reverted solved the issue for me. https://github.com/rdela/gatsby-graphcms-rd/pull/60#issuecomment-393517264
