### ISSUE TITLE
Gatsby Build Error - WebpackError: Cannot find module './/Users/james/Sites/xplivin/public/chunk-manifest.json'

### ISSUE THREAD

**Issue by JWeis** [gatsbyjs/gatsby#5639]
## Description

I started getting this error on Netlify for a site I am building for a client. The client site is using a lot of plugins and is based on the Hello World starter. To make sure it was something that I had done in my site, I tried to make a new site with gatsby new command. I am not getting develop or build to work properly. 

### Steps to reproduce

```gatsby new xplivin```

```gatsby develop --https```
```This localhost page can’t be found
No webpage was found for the web address: https://localhost:8000/
HTTP ERROR 404
```

```gatsby build```
```WebpackError: Cannot find module './/Users/james/Sites/xplivin/public/chunk-manifest.json'```

### Expected result

Fresh site should build and run in dev mode. 

### Actual result

See steps to reproduce

### Environment
* Gatsby version (`gatsby@1.9.264`):
* gatsby-cli version (`1.1.56`):
* Node.js version: v10.1.0
* Operating System: macOS High Sierra version 10.13.4

### File contents (if changed)
`gatsby-config.js`: 
```
module.exports = {
  siteMetadata: {
    title: 'Gatsby Default Starter',
  },
  plugins: ['gatsby-plugin-react-helmet'],
}
```
`package.json`: 
```
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "gatsby": "^1.9.264",
    "gatsby-link": "^1.6.40",
    "gatsby-plugin-react-helmet": "^2.0.10",
    "react-helmet": "^5.2.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write 'src/**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "prettier": "^1.12.0"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  }
}
```
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by craveytrain** [comment]
I have similar behavior and think this is related to #5636.

**Comment by KyleAMathews** [comment]
This is fixed now by reverting #4756

**Comment by KyleAMathews** [comment]
Sorry for the trouble.

**Comment by JWeis** [comment]
@KyleAMathews All set. Thank you!
