### ISSUE TITLE
Gatsby re-creates the absolute path to public folder in project root

### ISSUE THREAD

**Issue by helaoban** [gatsbyjs/gatsby#5641]
## Description

The absolute path to the public folder is re-created inside the project directory. 

A picture is worth a...

![screen shot 2018-05-31 at 11 58 03 am](https://user-images.githubusercontent.com/6245479/40802312-1dc595e6-64ca-11e8-848e-049a56320db5.png)

### Steps to reproduce

1. `gatsby new project-name`
2. `gatsby build` OR `gatsby develop`

### Expected result

A setup that builds to the local public directory on `gatsby build` and `gatsby develop`.

### Actual result

A setup that builds to a copy of the absolute system path to the public directory, nested inside the project directory.

### Environment
* Gatsby version (`npm list gatsby`): 1.9.265
* gatsby-cli version (`gatsby --version`): 1.1.56
* Node.js version: 9.0.0
* Operating System: macOS 10.12.6

### File contents (if changed)
`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by mquandalle** [comment]
I have the same issue, and it doesn't happen with previous versions of Gatsby such as `1.9.262`.

**Comment by KyleAMathews** [comment]
Can you try upgrading to the latest release? There was a PR that caused a lot of breakage that I reverted earlier https://github.com/gatsbyjs/gatsby/issues/5636#issuecomment-393638796

**Comment by KyleAMathews** [comment]
This should be fixed now in the latest release.

**Comment by helaoban** [comment]
@KyleAMathews Yes working now!
