### ISSUE TITLE
Support source files outside baseDir/src

### ISSUE THREAD

**Issue by gera2ld** [gatsbyjs/gatsby#5663]
## Summary

Support source files outside `${baseDir}/src`.

### Basic example

```
.
├── components
│   └── a.js
└── src
    └── layouts
        └── index.js
```

```js
// ./components/a.js
export default () => <div></div>;
export const query = graphql`
  fragment fragA on ... {
  }
`;
```

```js
// ./src/layouts/index.js
import A from '../../components/a';

export A;
export const query = graphql`
  query foo {
    ...fragA
  }
`;
```

Currently if a fragment is defined in a file outside `${baseDir}/src`, gatsby throws an error saying the fragment is not found. The expected result is a successful compilation.

### Motivation

To support components outside of the current project, so that we can switch to a different theme easily by assigning a path to some theme directory (maybe another repository).

I found this in the source code:
https://github.com/gatsbyjs/gatsby/blob/40c94f94d6b988ed923b93b0050424dfff606cf4/packages/gatsby/src/internal-plugins/query-runner/query-compiler.js#L85-L94

Will this be fixed since there is already a `FIXME` there?
Can we add some options to include more files with fragments?

**Comment by pieh** [comment]
FIXME is unrelated to to something you want. 

You can copy fragments outside of src directory to `.cache/fragments` like `gatsby-transformer-sharp` does - https://github.com/gatsbyjs/gatsby/blob/40c94f94d6b988ed923b93b0050424dfff606cf4/packages/gatsby-transformer-sharp/src/gatsby-node.js#L34-L39
