### ISSUE TITLE
Cannot Update Gatsby E404 serve@^6.4.0

### ISSUE THREAD

**Issue by brandonkal** [gatsbyjs/gatsby#5670]
## Description

I am unable to update Gatsby from 1.9.261 to 1.9.267

### Steps to reproduce

Run `npm update` or `npm install gatsby@1.9.267`

### Expected result

No E404 errors

### Actual result

404 Not Found: serve@^6.4.0

### Environment
* Gatsby version (`npm list gatsby`): 1.9.261
* gatsby-cli version (`gatsby --version`): 1.1.57
* Node.js version:  v8.11.1
* Operating System: MacOS 10.12.6

**Comment by nfmontenegro** [comment]
i get the same error  
`npm ERR! 404 Not Found: serve@^6.4.0`

**Comment by chang-ryan** [comment]
temp workaround found here: https://github.com/zeit/serve/issues/398#issuecomment-394041910

**Comment by m-allanson** [comment]
I think this was a temporary npm issue. Closing, but please comment or re-open if you're still seeing this.
