### ISSUE TITLE
Jump to top of the page when the app is not fully loaded

### ISSUE THREAD

**Issue by abumalick** [gatsbyjs/gatsby#5675]
## Description

I searched in the issues and couldn't find this.

When using gatsby with a slow connexion, when I visit a gatsby website for the first time, I get two small bugs:
- If I scroll the page (I assume it is before the javascript is loaded), the page will jump back to top.
- if I click on a link in the bottom of the page for example (I assume that the target page is not pre-loaded yet), the page will jump back to the top of the page before displaying the second page content

You can see what's happening on this recording: https://cl.ly/0t0j0W212t1O

This won't happen the second time I visit the website (I think when the offline plugin has cached all pages).

### Steps to reproduce

- clear browser data (cache and service worker ?)
- in dev tools, connection tab, set to slow 3g
- go to gatsbyjs.org (or gatsbyjs.com )
- scroll the page directly (your browser should jump to the top)
- scroll again and click on any link (your browser should jump to the top before transiting to next page

### Expected result

Not jump to the top of page

### Actual result

Jumped to the top of the page

### Environment
Well, I am not sure about this, as it is happening on gatsby website.
* Gatsby version (`npm list gatsby`): ^1.9.246
* gatsby-cli version (`gatsby --version`): /
* Node.js version: default netlify version ?
* Operating System: Im am on macOS High Sierra version 10.13.4
* browser: Chrome Version 66.0.3359.181 (Official Build) (64-bit) or chromium Version 68.0.3439.0 (Developer Build) (64-bit). I tested with firefox quantum 60.0.1 (64-bit) but could only reproduce the first jump with it (I don't know how to limit the speed in firefox), I could see this on chrome for android also.

### File contents (if changed)
`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by ryanditjia** [comment]
I seem to be able to reproduce this with all browsers I tested (Safari, Chrome, Firefox Developer Edition).

Maybe it’s got something to do with `react-router` or `shouldUpdateScroll`. This must be another one of those SPA quirks 😅.

Perhaps it’s best to just ignore this and see if v2 still exhibits the same bug.

**Comment by pieh** [comment]
Second issue is being worked on for v2 ( https://github.com/gatsbyjs/gatsby/pull/5109 ). For first part some investigation would be needed, what triggers this - @ryanditjia suggestion about `shouldUpdateScroll` (or I guess rather tracking where gatsby calls it) seems reasonably here as first suspect

**Comment by m-allanson** [comment]
Thanks folks! I'm going to close this as one part has been solved, and the remaining part is covered in #6392.

**Comment by abumalick** [comment]
Great !

It will only be fixed in v2 right ? No planned fix for v1 ?
