### ISSUE TITLE
Log which process is using port when there's a conflict

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#569]
This is too cool — added recently to create-react-app https://github.com/facebookincubator/create-react-app/pull/816

**Comment by vinnymac** [comment]
I would love to see this type of thing used in more modules. Small additional request, improve CLI UX by adding `chalk` for color in output like they do in create-react-app.

**Comment by KyleAMathews** [comment]
@vinnymac yes! Would love to hear your ideas for improving the CLI UX of Gatsby! Also feel free to port over more ideas from create-react-app :-) They've been doing a killer job and we've already borrowed several ideas and once 1.0 stuff starts solidifying, I'd like to port a lot more but feel free to create issues & PRs in the meantime!
