### ISSUE TITLE
Conflicting field types in Wordpress ACF query

### ISSUE THREAD

**Issue by iaindurie** [gatsbyjs/gatsby#5692]
## Summary
I'm using gatsby-source-wordpress in order to query some ACF fields on a Wordpress page. All was working fine but suddenly I'm getting an error about conflicting field types. The error is referencing a ACF repeater field called 'fullscreen_paged_content' - the graphql query and resulting error are below:

### GraphQL query
````
wordpressPage(wordpress_id : {eq : 137}) {
      id
      wordpress_id
      title
      acf {
        parent_website
        fullscreen_paged_content {
          content_type
          subheading
          heading
          background
          call_to_action {
            title
            url
            target
          }
        }
      }
    }
  }

````

### Error
```
warning There are conflicting field types in your data. GraphQL schema will omit those fields.
wordpress__acf_pages.acf.fullscreen_paged_content:
 - type: array<object>
   value: [ { content_type: 'Video', subheading: 'Foobar', heading: 'Lore ipsum dolor sit amet', background: false, call_to_action: [Object] } ]
 - type: boolean
   value: false
wordpress__PAGE.acf.fullscreen_paged_content:
 - type: array<object>
   value: [ { content_type: 'Video', subheading: 'Foobar', heading: 'Lore ipsum dolor sit amet', background: false, call_to_action: [Object] } ]
 - type: boolean
   value: false
GraphQL Error Unknown field `fullscreen_paged_content` on type `acf_4`


  file: C:/Projects/pi-bi/src/pages/index.js

   1 |
   2 |   query homepageQuery {
   3 |     wordpressPage(wordpress_id : {eq : 137}) {
   4 |       id
   5 |       wordpress_id
   6 |       title
   7 |   acf {
   8 |     parent_website
>  9 |     fullscreen_paged_content {
     |     ^
  10 |       content_type
  11 |       subheading
  12 |       heading
  13 |       background
  14 |       call_to_action {
  15 |         title
  16 |         url
  17 |         target
  18 |       }
  19 |     }
```

Does anyone know what could be causing this? It was working fine previously but now I get the warning about conflicting fields. I'm not really sure where to start in trying to fix this. Any help appreciated!

### Environment (if relevant)
* Gatsby version: 1.9.256
* gatsby-cli version: 1.1.53
* Node.js version: 6.9.5

**Comment by crgeary** [comment]
Are there any pages on the site that do not have anything set for `fullscreen_paged_content` ?

ACF outputs `false` in these cases which makes Gatsby/GraphQL turn that field type into a boolean.. Or it may be an array/object depending on the order the fields are processed.

The trick is to tell ACF to return `null` instead.

Take a look here for an example of how to do this: https://github.com/gatsbyjs/gatsby/issues/4461#issuecomment-371775563

**Comment by pieh** [comment]
This is recurring issue - is anyone up for updating `gatsby-source-wordpress` README with `nullify_empty` snippet (preferably in troubleshooting section if it exists or add one if it doesn't)?

**Comment by crgeary** [comment]
@pieh I can do that this evening for you (UK Time)

**Comment by iaindurie** [comment]
@crgeary yeah there a pages with nothing set for fullscreen_paged_content - #4461 fixed the issue, thanks very much
