### ISSUE TITLE
gatsby-plugin-google-analytics and virtual pageviews

### ISSUE THREAD

**Issue by tzehe** [gatsbyjs/gatsby#5696]
Hi, 

I am curious if it is possible to extend the analytics plugin to set virtual pageviews (https://support.google.com/analytics/answer/1116091?hl=en).

`ga('send', 'pageview', '/funnel_G1/step1.html');`
`ga('send', 'pageview', '/funnel_G1/step2.html');`
`ga('send', 'pageview', '/funnel_G1/step3.html');`

Or is it possible to modify the code somehow as a workaround.

Looking forward hearing from you. Thank you for your work!

Cheers Thomas 😃

**Comment by m-allanson** [comment]
If you want to experiment with new or custom features you could copy the plugin [to a local plugin](https://www.gatsbyjs.org/docs/plugin-authoring/#local-plugins), then make any changes you'd like to see. 

[The source is available here](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-google-analytics).
