### ISSUE TITLE
Remove backticks

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#57]
Not supported on older versions of node.

**Comment by luandro** [comment]
Also in `serve.js`:

`handler(request, reply) {` 

should be

 `handler: function(request, reply) {`

no?

I tried v0.6.2, changed all the backticks and this handler function, got the server to run, but got an error on on the client `bundle.js not found`.

**Comment by KyleAMathews** [comment]
I fixed a number of things in https://github.com/gatsbyjs/gatsby/commit/f07e39c5a325b7b881d831c23b55c4becfdf5bc4

Can you try the changes and see if it works now?

**Comment by BerkeleyTrue** [comment]
Why aren't these being transpiled using babel?

**Comment by gesposito** [comment]
Should be related to https://github.com/gatsbyjs/gatsby/issues/54

**Comment by KyleAMathews** [comment]
Compiling everything now with Babel.
