### ISSUE TITLE
[gatsby-plugin-netlify-cms] Webpack does not resolve "json" module..

### ISSUE THREAD

**Issue by pungggi** [gatsbyjs/gatsby#5700]
## Description
 ERROR  Failed to compile with 1 errors  
This relative module was not found:

./block-elements in ./~/remark-parse/lib/defaults.js

Same issue as https://github.com/grommet/grommet/issues/1018 ?

I added this 2 new packages: 
"gatsby-plugin-netlify-cms": "^2.0.1",
 "netlify-cms": "1.8.4",

### Steps to reproduce

run build

### Expected result

Find the module (block-elements is a json file see https://github.com/grommet/grommet/issues/1018 

 gatsby-plugin-netlify-cms should export `module.exports.resolvableExtensions = () => ['.json'] `? maybe? I dont know.

### Actual result

Error Message:
![grafik](https://user-images.githubusercontent.com/5635709/40924335-474e9250-6817-11e8-94e3-dec38b4fc1a2.png)

### Environment
gatsby@1.9.269
Node.js v9.11.1
Windows 10

### File contents (if changed)

I added `module.exports.resolvableExtensions = () => [`.json`]` to my gatsby-node and it works.

**Comment by erquhart** [comment]
@pungggi I'm not aware of this being an issue, maybe Windows specific? Is there a change required within the plugin?

**Comment by pungggi** [comment]
@erquhart yes like I wrote in the issue it needs to add 
module.exports.resolvableExtensions = () => [.json] 
to gatsby-node

**Comment by erickzhao** [comment]
@erquhart Stumbled upon this issue, and I seem to be getting the same problem on macOS. @pungggi's fix in `gatsby-node.js` worked for me.

**Steps to reproduce:**
1) Clone https://github.com/netlify-templates/gatsby-starter-netlify-cms/ and install dependencies.
2) `yarn add react-markdown`
3) Add `import ReactMarkdown from 'react-markdown'` in any React component file. The import statement by itself makes `gatsby develop` crash.

**Error:** 
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/16010076/44894223-c85a7280-acbc-11e8-8c11-b704164b9384.png">

The message obtained with this set of steps is slightly different, but the one I got on my own project repo was identical to the one in the Original Post.

System:
* macOS High Sierra 10.13.6 (17G2208)
* node 8.11.3
