### ISSUE TITLE
gatsby-transformer-remark should be able to use vanilla remark plugins

### ISSUE THREAD

**Issue by kruton** [gatsbyjs/gatsby#5716]
## Summary

Most remark plugins are simply "remark.use(plugin)" in normal remark use. This doesn't seem to be supported in the current layout

### Basic example

`yarn add remark-align`

In `gatsby-config.js`:

```javascript
{
  resolve: 'gatsby-transformer-remark',
  options: {
    plugins: [
      'gatsby-remark-copy-linked-files',
      'remark-align',
      {
        resolve: 'remark-foo-bar',
        options: { 'foosize': 5 }
      }
    ]
  }
}

```

### Motivation

Without this enhancement, each remark plugin will need to have a `gatsby-remark-XXX` analog for them to be used in Gatsby.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
