### ISSUE TITLE
Data from 3rd API for static files

### ISSUE THREAD

**Issue by Huvik** [gatsbyjs/gatsby#572]
Hey,

i want to have data from 3rd party API in static files. I hacked it around with `gatsby-node.js` and fetch data and then replace it in public folder, but i don't like this approach. Or fetch data before build time and then build with data. Is there any fancier approach or how to handle it in general? I want data in static because of indexing etc :) 

Thx, for answer

**Comment by KyleAMathews** [comment]
Is this data to be part of pages? Like in a table or something?

The simplest thing to do is to just create a `data` folder and then write a script which syncs data from your API to the folder and then import the data into pages with `import data from 'data/my-cool-data/json`.

You can also create pages directly from json files e.g. http://gatsbyjs.github.io/gatsby-starter-default/json/ & https://github.com/gatsbyjs/gatsby-starter-default/blob/master/wrappers/json.js

**Comment by Huvik** [comment]
So my approach is fine. But if i wan't have actual data everyday, i need rebuild my pages everyday. Thx for response i think we can close it now :)

**Comment by KyleAMathews** [comment]
great!
