### ISSUE TITLE
[v2] Appveyor check is failing

### ISSUE THREAD

**Issue by dennari** [gatsbyjs/gatsby#5725]
For some reason the tests are not passing on Appveyor's Windows platform:
```
Summary of all failing tests
FAIL packages\gatsby-transformer-react-docgen\src\__tests__\on-node-create.js
  ● transformer-react-doc-gen: onCreateNode › should delicately remove doclets
    Error
      94 |       `An object hash of field (fix this @mention?) errors for the form.`
      95 |     )
    > 96 |     expect(types.ComponentProp[0].doclets).toEqual({
      97 |       type: `{Foo}`,
      98 |       default: `blue`,
      99 |     })
      Error: expect(received).toEqual(expected)
      
      Expected value to equal:
        {"default": "blue", "type": "{Foo}"}
      Received:
}
      
      Difference:
      
      - Expected
      + Received
      
        Object {
          "default": "blue",
      -   "type": "{Foo}",
",
        }
      at Object.it (packages/gatsby-transformer-react-docgen/src/__tests__/on-node-create.js:96:44)
```
Here's an example: https://ci.appveyor.com/project/KyleAMathews/gatsby/build/1.0.7490/job/dida9pt6nlly1yq6

**Comment by dennari** [comment]
Perhaps #5604 will fix this

**Comment by m-allanson** [comment]
#5604 didn't solve it.. I've assigned to @pieh to take a look 🙏

**Comment by pieh** [comment]
So `types.ComponentProp[0].doclets` looks like this in windows - it doesn't remove `\r` which is part of default windows endline (`\r\n`):
![image 2018-06-07 at 5 08 40 pm](https://user-images.githubusercontent.com/419821/41108707-85c5a9b4-6a75-11e8-8a72-60b785009866.png)

@jquense what's the best place to fix this (I'm not familiar with `gatsby-transformer-react-docgen`)
