### ISSUE TITLE
position="absolute" does not work in gatsby-image component

### ISSUE THREAD

**Issue by nikbelikov** [gatsbyjs/gatsby#5727]
```
<Img sizes={banner.childImageSharp.sizes} outerWrapperClassName={styles.banner} position="absolute"/>
```

the layout is still:

div class="src-components-MainBanner----MainBanner-module---banner---1jnsz gatsby-image-outer-wrapper" style="**position: relative**;"><div class=" gatsby-image-wrapper" style="**position: relative**; overflow: hidden;"

**Comment by nikbelikov** [comment]
Thanks!

**Comment by ChrisCrossCrash** [comment]
This is still a problem, at least with `StaticImage` components in `gatsby-plugin-image` as of version 1.13.0.

I was only getting issues after building the site, not on the dev server. Adding `!important` to `position: absolute !important;` fixed it for me.

**Comment by seshaljain** [comment]
This issue exists in `gatsby-plugin-image` version 2.4.0 as well. Only shows up after building the site, couldn't understand why. Definitely a bug.

**Comment by bebbi** [comment]
@LekoArts Would you consider re-opening this?

For many if not all people, setting the position of a `GatsbyImage` to `absolute` works in development but fails after the build step, when it gets overridden by the components `position: relative` style:

```
<GatsbyImage
  image={myImage}
  alt={alt}
  className="absolute left-2 top-2"
/>
```

Providing a useful reason why the relative position is important so people can work around with confidence, or removing the positioning would both seem useful ways of addressing this issue.

**Comment by LekoArts** [comment]
This is not a bug but working as intended. You shouldn't override the styles of the image but create a wrapper component around the image with your custom styles. The image needs this CSS to function correctly in all cases.

**Comment by coffee-monk** [comment]
in-line styling with "position: 'absolute !important'" did the trick for me
