### ISSUE TITLE
Does `window` or `document` work after the build process?

### ISSUE THREAD

**Issue by wasabigeek** [gatsbyjs/gatsby#5737]
I'm trying to use a variation of [react-add-to-calendar](https://github.com/jasonsalzman/react-add-to-calendar), which works fine in `develop` mode but doesn't work when built. I think it's related to their use of [`document`](https://github.com/jasonsalzman/react-add-to-calendar/blob/master/src/helpers/index.js#L77), [`window.navigator`](https://github.com/jasonsalzman/react-add-to-calendar/blob/master/src/helpers/index.js#L111) and [`window.open`](https://github.com/jasonsalzman/react-add-to-calendar/blob/master/src/ReactAddToCalendar.js#L80).

Is this expected behaviour, and if so, what can I do to work around it?

**Comment by pieh** [comment]
`document` or `window` are objects provided by browsers and they don't exist when Gatsby builds static html files (same limitation as in server side rendering) - check https://www.gatsbyjs.org/docs/debugging-html-builds/ for ways around it.
