### ISSUE TITLE
URIError: URI malformed

### ISSUE THREAD

**Issue by liyuandie** [gatsbyjs/gatsby#5743]
我用gatsby搭建了自己的blog，很长时间没有写了，最近打算更新几篇博客，将之前的项目拉下来，执行npm i 后 执行gatsby develop却报错了，报错如下：
`error UNHANDLED REJECTION

  URIError: URI malformed

  - decodeURI

  - index.js:12 normalize
    [Gatsby-blog]/[normalize-uri]/index.js:12:20

  - link.js:10 link
    [Gatsby-blog]/[mdast-util-to-hast]/lib/handlers/link.js:10:22

  - one.js:29 one
    [Gatsby-blog]/[mdast-util-to-hast]/lib/one.js:29:51

  - all.js:18 all
    [Gatsby-blog]/[mdast-util-to-hast]/lib/all.js:18:14

  - list-item.js:22 listItem
    [Gatsby-blog]/[mdast-util-to-hast]/lib/handlers/list-item.js:22:12

  - one.js:29 one
    [Gatsby-blog]/[mdast-util-to-hast]/lib/one.js:29:51

  - all.js:18 all
    [Gatsby-blog]/[mdast-util-to-hast]/lib/all.js:18:14

  - list.js:17 list
    [Gatsby-blog]/[mdast-util-to-hast]/lib/handlers/list.js:17:36

  - one.js:29 one
    [Gatsby-blog]/[mdast-util-to-hast]/lib/one.js:29:51

  - all.js:18 all
    [Gatsby-blog]/[mdast-util-to-hast]/lib/all.js:18:14

  - root.js:11 root
    [Gatsby-blog]/[mdast-util-to-hast]/lib/handlers/root.js:11:41

  - one.js:29 one
    [Gatsby-blog]/[mdast-util-to-hast]/lib/one.js:29:51

  - index.js:92 toHAST
    [Gatsby-blog]/[mdast-util-to-hast]/lib/index.js:92:14

  - extend-node-type.js:300
    [Gatsby-blog]/[gatsby-transformer-remark]/extend-node-type.js:300:40

  - next_tick.js:131 _combinedTickCallback
    internal/process/next_tick.js:131:7

  - next_tick.js:180 process._tickCallback
    internal/process/next_tick.js:180:9`
q请问我该如何解决这个问题

**Comment by m-allanson** [comment]
Using google translate, I understood your question as:

> I built my own blog with gatsby. I haven't written it for a long time. I recently plan to update several blogs, pull down the previous project, execute gpmsby develop after executing npm i, and get an error. The error is as follows:

Can you try using the latest version of Gatsby? Also delete your `node_modules` and `package-lock.json` and try reinstalling.

**Comment by liyuandie** [comment]
Thank you very much for your advice, I before is, indeed, with the latest version of Gatsby, but appears the question, now I'm under your suggestion to delete the **package-lock.json**, reinstall, after this, my project has been running up, but I want to know is this why? Can you explain it to me

**Comment by liyuandie** [comment]
@m-allanson Thank you very much for your advice, I before is, indeed, with the latest version of Gatsby, but appears the question, now I'm under your suggestion to delete the package-lock.json, reinstall, after this, my project has been running up, but I want to know is this why? Can you explain it to me
