### ISSUE TITLE
[source-contentful] node deletions bug

### ISSUE THREAD

**Issue by Khaledgarbaya** [gatsbyjs/gatsby#5747]
If you hook up your project with a Contentful space that has deleted blog posts, they are still being fetched by GraphQL. It seems like CF doesn't delete the nodes once they are created--they just get returned with `null` values:

<img width="608" alt="nodes" src="https://user-images.githubusercontent.com/19804181/38822610-d1b872ca-4158-11e8-98e7-6eebbf59c307.png">

The issue this presents is in the index page (src/pages/index.js) because the code is looping through each node and creating a `div` for it (so a user could end up with empty white space on their blog if they have deleted entries--I was able to recreate):
```
            {posts.map(({ node }) => {
              return (
                <div className="article" key={node.slug}>
                  <ArticlePreview article={node} />
                </div>
              )
            })}
```

I was looking at this issue with another engineer and the easiest solution we could come up with is to only use nodes that have a valid title. So instead of this:
```
const posts = get(this, 'props.data.allContentfulBlogPost.edges')
```

You can filter for only posts that have a title (or any other field):
```
const allPosts = get(this, 'props.data.allContentfulBlogPost.edges')
const posts = allPosts.filter(post => post.node.title)
```

Question: Is it expected behavior to have phantom nodes even after posts are deleted? And should I create a PR to filter out these nodes if you agree with my assessment? 

@zcei Had a theory
> From what I found, there might a bug here, as [deleted entries are handled by `gatsby-source-contentful`](https://github.com/gatsbyjs/gatsby/blob/ae8e1ccc77f89a13a9828c5c200b6e45e47470c0/packages/gatsby-source-contentful/src/fetch.js#L75-L80).

> I haven't worked a lot with the source, but it looks like we're using the (maybe `c`-prefixed) [entity ID to delete a node](https://github.com/gatsbyjs/gatsby/blob/ae8e1ccc77f89a13a9828c5c200b6e45e47470c0/packages/gatsby-source-contentful/src/gatsby-node.js#L78-L80), while [a different format](https://github.com/gatsbyjs/gatsby/blob/ae8e1ccc77f89a13a9828c5c200b6e45e47470c0/packages/gatsby-source-contentful/src/normalize.js#L70) is used to [create the node](https://github.com/gatsbyjs/gatsby/blob/ae8e1ccc77f89a13a9828c5c200b6e45e47470c0/packages/gatsby-source-contentful/src/normalize.js#L317).

**Comment by KyleAMathews** [comment]
Ooooo that's definitely it! I think I added that deleting code early and then later added the id padding code and forgot to update the deleting code.

**Comment by ryanditjia** [comment]
Could this be the same bug? https://github.com/gatsbyjs/gatsby/issues/5348#issuecomment-391682881

In that comment, I mentioned there being 1036 nodes, close to 70% were nulls.

**Comment by axe312ger** [comment]
Opened a PR which should fix this issue :)
