### ISSUE TITLE
Example site URLs

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#5750]
## Description

Some of the example site URLs are not working. The links come from the README files of the [examples sites](https://github.com/gatsbyjs/gatsby/tree/master/examples).

I guess this is a DNS or Netlify config issue? @calcsam or @KyleAMathews do you know what might be causing this?

TODO: compile a list of which example site urls don't work.

### Steps to reproduce

Visit:

- https://using-emotion-prismjs.gatsbyjs.org
- https://using-page-loading-indicator.gatsbyjs.org/

### Expected result

There should be an example site.

### Actual result

In Chrome, the following message:

```
This site can’t be reached
using-emotion-prismjs.gatsbyjs.org’s server IP address could not be found.
Try:

Checking the connection
Checking the proxy, firewall, and DNS configuration
ERR_NAME_NOT_RESOLVED
```

**Comment by piotrkwiecinski** [comment]
```bash
grep -ihr '[^www].gatsbyjs.org' examples/*/README.md | xargs curl -I --silent --show-error 2>&1 | grep -i 'could not resolve'
```

```
curl: (6) Could not resolve host: feed.gatsbyjs.org
curl: (6) Could not resolve host: no-plugins.gatsbyjs.org
curl: (6) Could not resolve host: styleguide.gatsbyjs.org
curl: (6) Could not resolve host: using-csv.gatsbyjs.org
curl: (6) Could not resolve host: using-emotion-prismjs.gatsbyjs.org
curl: (6) Could not resolve host: using-excel.gatsbyjs.org
curl: (6) Could not resolve host: using-hjson.gatsbyjs.org
curl: (6) Could not resolve host: using-page-loading-indicator.gatsbyjs.org
curl: (6) Could not resolve host: using-react-url-query.gatsbyjs.org
curl: (6) Could not resolve host: using-gatsby-remark-copy-linked-files.gatsbyjs.org
```
Anyone wants to validate manually ? :)

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
