### ISSUE TITLE
Add gatsby-plugin-layout docs to v2 migration post

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#5753]
## Summary

There's a [Gatsby v1 to v2 migration guide](https://github.com/gatsbyjs/gatsby/blob/v2/docs/docs/migrating-from-v1-to-v2.md) which covers breaking changes in v2.

It doesn't have any information about useful techniques for upgrading larger sites, particularly how to convert layouts. See related discussions below:

Refs: https://github.com/gatsbyjs/gatsby/pull/5575#pullrequestreview-125184323
Refs: https://github.com/gatsbyjs/gatsby/issues/3986#issuecomment-393902995

### Motivation

Upgrading to v2 should be straightforward for all Gatsby sites, large or small.

**Comment by shannonbux** [comment]
@amberleyromo in case this looks interesting!

**Comment by m-allanson** [comment]
Let's handle this with a new `gatsby-plugin-layout` plugin

**Comment by jlengstorf** [comment]
@m-allanson is there an issue for `gatsby-plugin-layout`? Or is this it?

**Comment by m-allanson** [comment]
The layout plugin will be added in #7204

**Comment by jlengstorf** [comment]
I'm closing this for now, because we don't really have a clear goal for how to write this out. It kind of seems like it could support a few narratives, e.g. "how to do page transitions" or "how to prevent component rerenders", but for now the scope of this issue is complete.
