### ISSUE TITLE
React's ticking clock example with Gatsby

### ISSUE THREAD

**Issue by heyalbert** [gatsbyjs/gatsby#5754]
How can I create a simple clock with Gatsby?
Like the clock in the React documentation: https://reactjs.org/docs/state-and-lifecycle.html

I was to able to make it work in the way that I see a new time every second. Any suggestion?

Here is my code in src/html.js:

```
import React, { Component } from "react"

class Clock extends React.Component {
	constructor(props) {
	  super(props);
	  this.state = {date: new Date()};
	}
  
	componentDidMount() {
	  this.timerID = setInterval(
		() => this.tick(),
		1000
	  );
	}
  
	componentWillUnmount() {
	  clearInterval(this.timerID);
	}
  
	tick() {
	  this.setState({
		date: new Date()
	  });
	}
  
	render() {
	  return (
		<div>
		  <h1>Hello, world!</h1>
		  <h2>It is {this.state.date.toLocaleTimeString()}.</h2>
		</div>
	  );
	}
}

export default Clock
````

What I have to change in order to get the clock ticking? Thank you for any help!

**Comment by ryanditjia** [comment]
`src/html.js` is the wrong place for it. The root file is at `src/pages/index.js`. Try putting your Clock there. I recommend you go through the tutorial to familiarize yourself with the basics.

**Comment by heyalbert** [comment]
I went through all tutorials. It doesn't say a lot about hml.js and there is still a lot of undocumented things. It makes it unnecessary hard for beginners. Just my honest feedback.

**Comment by KyleAMathews** [comment]
We don't normally suggest using html.js. Curious where you picked up the idea of using it?

**Comment by heyalbert** [comment]
Because I want full control over my website and html.js is the file where everything comes together, right?
It gives me a lot more clarity to have kind of a base.

**Comment by KyleAMathews** [comment]
Page components is where things come together. I suggest going through the first part of the tutorial again plus reading this docs page https://www.gatsbyjs.org/docs/building-with-components/

**Comment by heyalbert** [comment]
Page componentS — plural. It's not the base, it's not where every single piece ends in one file, right? It even says that with `{this.props.headComponents}` and `{this.props.postBodyComponents}` and `{this.props.preBodyComponents}` etc. — or do I miss something?

**Comment by ryanditjia** [comment]
What are you trying to accomplish? For most projects, you don’t have to touch html.js.

**Comment by heyalbert** [comment]
My idea was to bring `Helmet`/stuff for the head and the `scss imports` in my `html` file.

**Comment by ryanditjia** [comment]
You can use `Helmet` from any component. And webpack should be able to load scss with [gatsby-plugin-sass](https://www.gatsbyjs.org/packages/gatsby-plugin-sass/?=sass)
