### ISSUE TITLE
Create nodes / modify data when creating pages with Gatsby Contentful Plugin

### ISSUE THREAD

**Issue by laij84** [gatsbyjs/gatsby#5760]
I'm using the Gatsby Contentful Plugin to create a page for each Event content type in Contentful. 

There is only one instance of the event created in Contentful, but an event may be repeated on multiple dates in which case it has a field for a list of recurrence dates on the content type.

In the gatsby-node.js file, when creating a page for an Event, I also need to create a page for each Recurrence Date that an event may have. Is there a way to do this ?

**Comment by ryanditjia** [comment]
Rough algorithm:

```js
events.forEach(event => {
  event.recurrenceDates.forEach(date => {
    createPage({
      // rest of code
    })
  })
})
```
