### ISSUE TITLE
Reduce the bundle size for modern browsers

### ISSUE THREAD

**Issue by mquandalle** [gatsbyjs/gatsby#5761]
Meteor 1.7 introduced the ability to generate two different JavaScript bundles, one for legacy browsers that includes JS polyfills for features that aren't natively implemented by the browser, and one for modern browsers without these polyfills. The rationale for this feature and the Meteor design is exposed in https://github.com/meteor/meteor/pull/9439 and https://blog.meteor.com/meteor-1-7-and-the-evergreen-dream-a8c1270b0901, but basically the idea is to reduce the bundle size and increase runtime performances for 80+ % of users.

Even if there is some engineering complexity with this feature, I think it would by a good match for Gatsby because of its already strong focus on runtime performances.

**Comment by m-allanson** [comment]
We definitely want to do this, see: #2114. Thanks for the meteor references, I hadn't seen them before. 

Closing this as a duplicate.

**Comment by mquandalle** [comment]
Oh sorry for the duplicate issue, I haven't done by due search before opening this. I'll share the meteor references in the other thread.

**Comment by m-allanson** [comment]
No problem and thank you :)
