### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by rothfels** [gatsbyjs/gatsby#577]
Should gatsby support typescript projects? It provides coffee transpilation out-of-the-box so I suspect the answer is "yes".

I made a [fork](https://github.com/rothfels/gatsby) which adds support for loading `.tsx` pages (including index & templates). I'm happy to clean it up and open a PR. It's a small hack because when you `require` typescript from javascript you get an object with a `default` property instead of the default export. I don't support writing wrappers or loaders in typescript, but maybe should if you want to upstream this.

**Comment by KyleAMathews** [comment]
Yes! Would love to support typescript out of the box. I'm not really sure what's necessary to do that so if you could make it happy that'd be great!

**Comment by KyleAMathews** [comment]
Haha *happen :-) happy kinda works too though

**Comment by KyleAMathews** [comment]
@rothfels when you have a chance, would love it if you added a link to your Typescript starter!
