### ISSUE TITLE
How to add line numbers with PrismJS?

### ISSUE THREAD

**Issue by jasperjn** [gatsbyjs/gatsby#5775]
I've been searching for a while on Gatsby site and `gatsby-remark-prismjs` documents only found how to highlight lines. I found [Line Numbers](https://prismjs.com/plugins/line-numbers/) on Prismjs but it seems only work on client side after adding `line-numbers` class on `pre`. Is there an option or entry can enable showing line numbers with PrismJS?

**Comment by m-allanson** [comment]
This would be a great feature to add, but as far as I know it's not implemented at the moment. You'd need to adapt the PrismJS Line Numbers plugin to work during Gatsby's build step. See the [implementation notes for `gatsby-remark-prismjs`](https://www.gatsbyjs.org/packages/gatsby-remark-prismjs/#implementation-notes) for more info on this.

If you're interested in looking into this, the (source for `gatsby-remark-prismjs`)(https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/index.js#L59] would be a good place to start.

**Comment by phacks** [comment]
Hi! I tried to implement this in PR https://github.com/gatsbyjs/gatsby/pull/5821, do you think you could have a look?

Thanks!

Nico

**Comment by jasperjn** [comment]
Merged https://github.com/gatsbyjs/gatsby/pull/5821
