### ISSUE TITLE
How can I add a meta description field with Helmet?

### ISSUE THREAD

**Issue by heyalbert** [gatsbyjs/gatsby#5777]
How can I add a meta description field with Helmet?

My Helmet snippet in layouts/index.js:

```
    <Helmet
      title={data.site.siteMetadata.title}
      meta={[
        { name: 'description', content: 'Sample' },
		{ name: 'keywords', content: 'sample, something' },
		{ property: 'og:type', content: 'website' }
      ]}
    />
````

 `title={data.site.siteMetadata.title}` comes from gatsby-config.js

```
module.exports = {
  siteMetadata: {
	title: 'Gatsby Default Starter',
 },
```
Now I would like to add a website description. Like so:

```
module.exports = {
  siteMetadata: {
	title: 'Gatsby Default Starter',
	description: 'Sample'
},
```

So, now it comes. How can I now bring this new description field into my Helmet snippet?
Something like this below: 
This is not possible right now. So, what is the alternative? Thank you for any help!

```
    <Helmet
      title={data.site.siteMetadata.title}
      meta={[
        { name: 'description', content: {data.site.siteMetadata.description}},
	{ name: 'keywords', content: 'sample, something' },
	{ property: 'og:type', content: 'website' }
      ]}
    />
````

**Comment by pieh** [comment]
You need to update query in layout to include `description` field (same as it does for `title`). If you were running `gatsby develop` when you changed `gatsby-config.js` you will also have to stop it and restart it so graphql schema get updated.

**Comment by heyalbert** [comment]
I did. And than? How can I bring it back to Helmet? This part `{ name: 'description', content: {data.site.siteMetadata.description}},`?

**Comment by pieh** [comment]
`{ name: 'description', content: data.site.siteMetadata.description }` (drop extra curly braces)
