### ISSUE TITLE
How to Obtain a GraphQLObjectType created through setFieldsOnGraphQLNodeType

### ISSUE THREAD

**Issue by joewood** [gatsbyjs/gatsby#5788]
I'm creating a GraphQL type through `setFieldsOnGraphQLNodeType`, but the type has to be self-referential. Is there a simple way to obtain the instance of the type being created through this function?

**Comment by pieh** [comment]
Check this https://stackoverflow.com/questions/32551022/how-do-i-create-a-graphql-schema-for-a-self-referencing-data-hierarchy - `fields` need to be function - then you will be able to self reference type
