### ISSUE TITLE
[v2] GraphQL parsing error while using TypeScript

### ISSUE THREAD

**Issue by jhh** [gatsbyjs/gatsby#5789]
## Description

I'm converting my v2 project over to TypeScript, everything works fine until I start to convert over pages with GraphQL. I've reproduced the issue [(see fork)](https://github.com/jhh/gatsby/tree/typescript-issue/examples/using-typescript) with the using-typescript example site so I will describe that here.

Running the unmodified using-typescript example works as expected.

I've extended the GraphQL in the example by adding `gatsby-source-filesystem` and a `test.md` file. GraphiQL works on these as expected.

```typescript
interface IndexPageProps {
  data: {
    site: {
      siteMetadata: {
        siteName: string
      }
    }
    file: {
      relativePath: string
    }
  }
}

export const pageQuery = graphql`
  query IndexQuery {
    site {
      siteMetadata {
        siteName
      }
    }
    file(relativePath: { eq: "test.md" }) {
      relativePath
    }
  }
`
```

<img width="737" alt="graphiql" src="https://user-images.githubusercontent.com/14412/41136378-042791cc-6aa4-11e8-938b-f66960a7c34a.png">

Running `yarn develop` produces this error and no data in the props:

```
...
success update schema — 0.073 s
error There was a problem parsing "/Users/jeff/sf/web/gatsby/examples/using-typescript/src/pages/index.tsx"; any GraphQL fragments or queries in this file were not processed.
This may indicate a syntax error in the code, or it may be a file type that Gatsby does not know how to parse.
success extract queries from components — 0.021 s
...
```

If I fully comment out the interface definition then I don't see this error. If I comment out **either** the `site` or `file` property in the interface then I don't see the error.

### Environment

```
  System:
    OS: macOS High Sierra 10.13.5
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.3.0 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.79
    Safari: 11.1.1
  npmPackages:
    gatsby: next => 2.0.0-alpha.51
    gatsby-plugin-typescript: next => 2.0.0-alpha.2
    gatsby-plugin-typography: next => 2.0.1-11
    gatsby-source-filesystem: ^1.5.38 => 1.5.38
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```
### File contents (if changed)

`gatsby-config.js`: 
```javascript
module.exports = {
  siteMetadata: {
    siteName: `Using Typescript Example`,
  },
  plugins: [
    `gatsby-plugin-typescript`,
    {
      resolve: `gatsby-plugin-typography`,
      options: {
        pathToConfigModule: `src/utils/typography.js`,
        omitGoogleFont: true,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `pages`,
        path: `${__dirname}/src/pages/`,
      },
    },
  ],
}
```
`package.json`:
```json
{
  "name": "using-typescript",
  "version": "1.0.0",
  "description": "Gatsby example site demonstrating how to use Typescript with Gatsby",
  "author": "fabien0102 <fabien0102@gmail.com>",
  "license": "MIT",
  "scripts": {
    "start": "gatsby develop",
    "develop": "gatsby develop",
    "build": "gatsby build",
    "type-check": "tsc --noEmit",
    "lint": "tslint --project ."
  },
  "dependencies": {
    "@types/node": "^10.3.1",
    "@types/react": "16.3.16",
    "@types/react-dom": "16.0.6",
    "gatsby": "next",
    "gatsby-plugin-typescript": "next",
    "gatsby-plugin-typography": "next",
    "gatsby-source-filesystem": "^1.5.38",
    "react": "^16.4.0",
    "react-dom": "^16.4.0",
    "react-typography": "^0.16.13",
    "typography": "^0.16.17",
    "typography-theme-bootstrap": "^0.16.7"
  },
  "devDependencies": {
    "tslint": "^5.10.0",
    "tslint-config-prettier": "^1.13.0",
    "tslint-react": "^3.6.0",
    "typescript": "^2.9.1"
  }
}
```
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by m-allanson** [comment]
@dennari or @mquandalle I'd love to know if you have any thoughts on this?

**Comment by dennari** [comment]
Ok I think I figured out the problem: in the interface declaration, there's a place where the semicolon is not optional. In general the interface member declarations should end up in a semicolon.

```typescript
interface IndexPageProps {
  data: {
    site: {
      siteMetadata: {
        siteName: string
      }
    }; // <-- here
    file: {
      relativePath: string
    }
  }
}
```

**Comment by dennari** [comment]
Note also that you seem to be using an old version of `gatsby-source-filesystem`

**Comment by jhh** [comment]
I've confirmed adding the semicolon fixes the problem. Thanks for the help! 

Now to get Prettier in VS Code to stop removing that semicolon automatically...

**Comment by jhh** [comment]
If it helps, here's a link to the project mentioned above that now successfully parses graphql. It has working page creation in `gatsby-node.js` and embedded `graphql` in `.tsx` files.

https://github.com/strykeforce/strykeforce.org

**Comment by resir014** [comment]
Hey, I've encountered this issue as well. Can confirm that adding a semicolon into my interface declaration fixes the issue.

However, I'm not sure that breaking a linting rule is a true solution to this problem... could there be another possible way to fix this issue?

**Comment by deltaskelta** [comment]
I managed to get this error and I chopped my component down to the bare minimum and I am still getting it. There are no interfaces imported and being used.

```
import React from 'react';

class BlogPost extends React.Component {
  public render() {
    return (
      <div>hi</div>
    );
  }
}

export default BlogPost;
```

**Comment by resir014** [comment]
@deltaskelta It is a Babel issue. Also related: #6163, #6174, #6209.

**Comment by deltaskelta** [comment]
Oh yeah I found those too but I didn't have a deep enough knowledge to understand everything. Is there a short term fix that would get this running?

**Comment by deltaskelta** [comment]
I've just swapped the flow plugin for the typescript plugin in `gatsby/src/internal-plugins/query-runner/file-parser.js` as a hotfix
