### ISSUE TITLE
Suggestion: docs plugin pages should have direct link to github issues and (in future) Starter Showcase

### ISSUE THREAD

**Issue by sw-yx** [gatsbyjs/gatsby#5790]
## Summary

a lot of plugins have very poor documentation. Even the well documented ones need a lot more examples.

Idea 1: within the plugin docs (eg <https://www.gatsbyjs.org/packages/gatsby-plugin-preact/?=preact>) add a link to github issue search: https://github.com/gatsbyjs/gatsby/issues?utf8=%E2%9C%93&q=is%3Aissue++sort%3Aupdated-desc++gatsby-plugin-preact.

Idea 2: (optional) we can even label issues with the plugin names so that the docs just point to the github label. this might be better for a more focused search but takes more effort in labeling.

Idea 3: in future we can also add a direct link to starters that use that particular plugin too to the starter showcase.

### Motivation

> Why are we doing this? What use cases does it support? What is the expected outcome?

slight improvement in UX using browsing the plugins pages. configuring/debugging plugins is the gnarliest part of using gatsby. we should do everything we can to link people into existing content.

**Comment by KyleAMathews** [comment]
Yes! We've discussed in the past adding an infobox to plugins with links to doc pages, tutorials, and other info like you've suggested. Would be great improvement.

**Comment by giraffesyo** [comment]
I personally think idea 2 is the better option just like stackexchange does it. There would be no false-positives in the search, however it would require labels to be basically added to everything.

**Comment by shannonbux** [comment]
Was just about to label this with "UX" label to pull it into the TO DO list of the UX Project (which has three other plugin library related enhancements), and realizing now that the documentation project also has lots of plugin-related stuff. Wondering if a plugin library project makes sense?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
