### ISSUE TITLE
Fix link for edit this page on v2 site

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#5791]
Some people were complaining it's not working.

**Comment by m-allanson** [comment]
@KyleAMathews I added #5792 but not sure if that's the fix you intended? What wasn't working with the old link?

**Comment by ryanditjia** [comment]
I think it’s the _edit this page on GitHub_ link at the very bottom of https://v2--gatsbyjs.netlify.com/docs/migrating-from-v1-to-v2/

**Comment by ryanditjia** [comment]
We can modify [MarkdownPageFooter](https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/markdown-page-footer.js) to accept a branch as prop (defaults to master).

Or we could just merge this migration doc to master. What do you guys think?
