### ISSUE TITLE
Support WooCommerce post types in wordpress source plugin

### ISSUE THREAD

**Issue by Amanej** [gatsbyjs/gatsby#5794]
Currently the wordpress source plugin only fetches the woocommerce post titles, excerpts and other generic wordpress content.

It would be good if it supports the product data, such as prices, variations etc.

**Comment by Amanej** [comment]
I would like to do this myself, but the wordpress source plugin was difficult to understand.

**Comment by Amanej** [comment]
I am not receiving any 401s, its just not showing up in the available data in graphql except the most basic post data such as title, excerpt etc.
But not all the other fields.

I am not sure, how you would query the other fields with the wordpress-source-plugins.

They are all public, and if I wrote a request from scratch I would be able to fetch all the products with their prices etc.

**Comment by tscangussu** [comment]
Why not use [WooCommerce REST API](https://woocommerce.github.io/woocommerce-rest-api-docs/) to create a gatsby-source-woocommerce?

**Comment by Amanej** [comment]
![image](https://user-images.githubusercontent.com/10694878/42266500-dadf7162-7f76-11e8-8ff3-ed17717d578b.png)

This is not working, but this works in the browser:
http://mywoocommercesite.com/wp-json/wc/v1/products?consumer_key=key&consumer_secret=secret&category=17

@keithgonzalez

**Comment by keithgonzalez** [comment]
@Amanej what do you mean by not working? Are you getting any errors?

**Comment by Amanej** [comment]
Well, the url works in the browser, as an ajax call, with curl and with nodejs rest api. So its definitely not a wp server config issue.

How exactly does the source plugin use the auth parameters ? That is what is really missing here. If you are able to just provide one example of how it could work, of how the auth parameters would look with WooCommerce keys, not WordPress login (which would not sufficient) that would be helpful.

> If you're receiving 401 Unauthorized, it's because you need to create keys in WooCommerce > Settings > Advanced > REST API. Add these to the auth field in the wordpress section of your gatsby-config.

I have just started my own source plugin anyway: [https://github.com/Amanej/gatsby-source-woocommerce-plugin](wc-source-plugin). But unfortunately for the current project, its way out-of-scope already.

**Comment by wilsonmar** [comment]
The link in the above comment does not resolve for me: https://github.com/gatsbyjs/gatsby/issues/wc-source-plugin
@Amanej we are exploring the same, so let's join forces. Please contact me.

**Comment by Amanej** [comment]
@wilsonmar  I updated the link now!
