### ISSUE TITLE
Create RFC for extending Gatsby's WordPress plugin

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#5796]
## Summary

Create an RFC to spec out extension points to `gatsby-source-wordpress`.

Add extension points to `gatsby-source-wordpress` to allow it to work with additional gatsby plugins. This would enable usage with a variety of WordPress setups (e.g. WooCommerce, Gravity Forms) without having to directly support everything within `gatsby-source-wordpress`. 

### Basic example

See discussion at https://github.com/gatsbyjs/gatsby/pull/5599#issuecomment-394767557

A config might look like:

```javascript
// In your gatsby-config.js
module.exports = {
  plugins: [
    {
      resolve: `gatsby-source-wordpress`,
      options: {
        plugins: [
          {
            resolve: `gatsby-wordpress-woocommerce`,
            options: {
              // options here
            },
          },
          {
            resolve: "gatsby-wordpress-gravity-forms",
            options: {
              // more options
            },
          },
        ],
      },
    },
  ],
}
```

### Motivation

WordPress can be used in many different ways. Supporting every available WordPress plugin within `gatsby-source-wordpress` is likely to become unwieldy quite quickly. Adding plugin support to the `gatsby-source-wordpress` would allow the Gatsby community to evolve with the WordPress community.

**Comment by kennethormandy** [comment]
This sounds great, and I’d be happy to contribute to the RFC, and port what I have for Gravity Forms to this structure as one test case.

A couple of questions (perhaps best saved for the RFC):

- **Would this mean moving the existing plugins supported out of `gatsby-source-wordpress`?** Right now I think we should keep ACF support in `gatsby-source-wordpress`, but I can also see the case for moving all WordPress plugin…plugins out of it.
- **Should the plugins be responsible for re-formatting data for Gatsby when needed?** Often, the WP REST API returns nothing or `false` when you need it to return `null` for GraphQL. This also happens within the WP REST API implementations of each individual WordPress plugin. It can be solved with another WordPress plugin, but then you’d need a the original WP plugin, the companion WordPress plugin, and the companion Gatsby plugin to be able to support any WP plugins. Alternatively, the Gatsby plugin can it. I believe there is a proposal (from @pieh?) about mitigating this at a higher level for other Gatsby source plugins too, not sure if that would extend to this.

**Comment by Amanej** [comment]
I would also be happy to contribute. Documenting the pattern behind the wordpress source plugins, would be helpful to anyone who wants to extend it to other data types created by popular wordpress plugins.

**Comment by Amanej** [comment]
Started here, would appreciate help from anyone with Gatsbyjs.

https://github.com/Amanej/gatsby-source-woocommerce-plugin
