### ISSUE TITLE
I want to run my blog on site name.com/blog ?

### ISSUE THREAD

**Issue by mubeentauni** [gatsbyjs/gatsby#5799]
I want to run buy Gatsby blog on mysitename.com/blog but I am unable to specify that whenever Gatsby run it should run on sitename.com/blog instead of 'site name.com/'

can someone help me with that ?
TIA

**Comment by m-allanson** [comment]
Check out the path prefix docs: https://www.gatsbyjs.org/docs/path-prefix/

**Comment by mubeentauni** [comment]
@m-allanson Thanks man! I was just missing *not* to put the slash.

Thanks a bunch.

**Comment by mubeentauni** [comment]
@m-allanson  Hey I wanted to ask another thing that is if I have my site running on node and I want to say that all the /blog/* routes are to be handled by Gatsby, 

```javascript
app.get('/blog', function (req, res, next) {

    res.sendFile((path.join(__dirname, 'blog/public', 'index.html')));
});

I have written this its rendered the index page that is the  list of all blogs but it doesn't do any further routing ?
How do I support that ? Any help regarding that would be great!

Thanks in advance.
