### ISSUE TITLE
Exit code when module is not found is wrong

### ISSUE THREAD

**Issue by cgarvis** [gatsbyjs/gatsby#58]
``` bash
$ gatsby build

Generating static html pages
failed at generating static html pages
{ [Error: Cannot find module "components/page-layout"] code: 'MODULE_NOT_FOUND' }

$ echo $?

0
```

This should return something other than zero.

**Comment by KyleAMathews** [comment]
It looks like Webpack 2.0 will change the default exit code to 1 when it fails. In the meantime, there's a variety of ways it seems to get this behavior now described in this thread. A PR would be great! https://github.com/webpack/webpack/issues/708

**Comment by jbolda** [comment]
This is or will be fixed. Closing.
