### ISSUE TITLE
DX Bug: Gatsby should safely wrap `window` when used in render

### ISSUE THREAD

**Issue by tsiq-swyx** [gatsbyjs/gatsby#5811]
## Description

using `window.innerWidth` in render works in dev but not in prod. this is no bueno.

### Steps to reproduce

its in the title

### Expected result

Error or warn when someone uses `window` in render in a gatsby app. 

(EDIT: or transform `window` in babel to add stuff, see below)

### File contents (if changed)

Link to code example where i made this mistake: https://github.com/ThatOtherPerson/gatsby/pull/3/files#diff-4b4a6a4395be06bd74e68e1eddff59fbR273

Link to gatsby slack convo where we discuss this https://gatsbyjs.slack.com/archives/DB09D1LLT/p1528481061000545

----

# discussion item:

1. should we warn or error?
2. where best to implement this warning?

**Comment by tsiq-swyx** [comment]
slightly correcting myself - usage of `window` has to be wrapped in something like

```
    let windowWidth
    if (typeof window !== `undefined`) {
      windowWidth = window.innerWidth
    }
```

can we transform `window` in babel?

**Comment by ryanditjia** [comment]
I like this. If this is difficult to implement, an alternative would be to improve the error message during gatsby build.

**Comment by nihgwu** [comment]
`window` is not defined in SSR and that'a common issue, I'd prefer leave the workaround to the user to denote that code block would be executed in the initial rendering so you should check your code to verify if the access to `window` or `document` is necessary or if we can more that to `cDM`

**Comment by sw-yx** [comment]
ok so at bare minimum we should warn; if we want to take it to the next level we can safe-wrap, but it sounds like the MVP of this is just warning.

**Comment by MaralS** [comment]
I have the problem of the undefined window at build step

**Comment by KyleAMathews** [comment]
Auto-wrapping seems like it'd be too unexpected and potentially not work in some cases.

Perhaps we should just create a custom eslint rule warning against using window in render? E.g. suggesting instead you put the logic in componentDidMount. Though I guess there's legitimate cases for using window in render functions. This is a super common problem though so we should do something to help people...

**Comment by KyleAMathews** [comment]
This library is an interesting solution as well https://github.com/Jense5/browser-monads

**Comment by nihgwu** [comment]
also https://github.com/Raynos/global

**Comment by barbalex** [comment]
Please add the browser-monad solution to the docs. It is essential for instance if you want to add navigator.share to a project

**Comment by sw-yx** [comment]
sad but ok
