### ISSUE TITLE
Show javascript errors in overlay

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#582]
create-react-app and next.js have this and it's super cool and useful. You know right away when something is wrong instead of having to keep glancing at your terminal or browser console.

Also next.js adds syntax highlighting to the error which is nifty.

https://github.com/zeit/next.js/pull/195

**Comment by KyleAMathews** [comment]
https://github.com/facebookincubator/create-react-app/pull/1101#issuecomment-263453581

**Comment by vinnymac** [comment]
For those who aren't familiar, [react-redbox](https://github.com/commissure/redbox-react) is usually used to do this.

**Comment by jthegedus** [comment]
Re: ``create-react-app`` the webpack-dev-server@2.3.0 (webpack/webpack-dev-server@d725fd9)[https://github.com/webpack/webpack-dev-server/commit/d725fd9f3b0c2ab92e6489c993f80602c0e47848] added some support for the CRA implementation of overlays. Discussed by CRA (here)[https://github.com/facebookincubator/create-react-app/pull/1291]

**Comment by KyleAMathews** [comment]
PR adding this to another project https://github.com/react-cosmos/react-cosmos/pull/484

**Comment by Timer** [comment]
If anyone takes this on don't hesitate to ask me questions, I could also give it a stab if someone points me in the right direction (where it'd need wired into).

**Comment by KyleAMathews** [comment]
Oh sweet! Thanks for hopping in and offering to help! Would love to get this in soon. First question though is does the overlay work with webpack 1 still? That's where we are still unfortunately.

This is the entry file for development  https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/root.js

**Comment by Timer** [comment]
Depends on what angle you're asking that question -- our webpack middleware *might* work with webpack 1, but we know it works on webpack 3.

As for the overlay itself (just importing): currently, no -- we only ship an ESM version of the overlay (you could put it through babel).
The next version (should) include a CJS version which can be consumed by webpack 1 easily.

The overlay itself does not depend on anything webpack, its a completely separate package with 0 dependencies -- we just have to decide on the integration points.

**Comment by KyleAMathews** [comment]
What does the integration point need to be? Where in the app is it?

**Comment by Timer** [comment]
The overlay simply needs to be required in the applications source, preferably as an entry point.

The "integration" points I was speaking of pertain to the click-to-open source / build errors; you can use our webpack development server or add the necessary hooks to enable those features in your server (none of which are necessary for the overlay to work).

**Comment by KyleAMathews** [comment]
Oh sweet — sounds fairly straightforward then.

Would love a PR adding the overlay to https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/root.js

We use webpack-dev-middleware — is the click-to-open / build errors compatible with that? https://github.com/gatsbyjs/gatsby/blob/9ff14013fbd7f7a48e37c6be9ab6b3f012317cfd/packages/gatsby/src/commands/develop.js#L91 Happy to take suggestions for alternative setups if they're more compatible.

**Comment by Timer** [comment]
#2783

**Comment by KyleAMathews** [comment]
This is shipped! Thanks again @timer!
