### ISSUE TITLE
[v2] Using query in page throws errors after build; works for dev

### ISSUE THREAD

**Issue by bkniffler** [gatsbyjs/gatsby#5828]
## Description

Using `export const query = ...` in v2 to query data for a page throws errors, site doesn't work.

### Steps to reproduce

Use https://github.com/bkniffler/gatsby-issue

Build and run a server (`npm i http-server -g && http-server public`). It throws errors. Comment out the query in `src/pages/page-2.jsx`, it works.

### Expected result

Should work..?

### Actual result

```
GET http://127.0.0.1:8080/static/d/undefined.json 404 (Not Found)

AND

TypeError: Cannot read property 'pageContext' of undefined
    at t.n.render (page-renderer.js:121)
```

### Environment
```
    "gatsby": "next",
    "gatsby-plugin-react-helmet": "next",
    "gatsby-plugin-sass": "next",
    "gatsby-plugin-google-analytics": "1.0.31",
    "gatsby-source-filesystem": "2.0.0-alpha.15",
    "gatsby-transformer-remark": "2.0.1-13",
```

**Comment by ryanditjia** [comment]
That’s because you’re using page-2 as you would a template component.

You’re creating duplicates of page-2 here:

1. src/pages/page-2
  This one errors out because it doesn’t have pageContext
2. createPage using page-2 as component
  This one will be created okay

**Comment by bkniffler** [comment]
Ah, good find, thanks!
