### ISSUE TITLE
[v2] Not sourcing some files on 1 to 2 migration

### ISSUE THREAD

**Issue by wangsongiam** [gatsbyjs/gatsby#5830]
## Description
Excuse me for not providing reproduction codes.

* Not sourcing `src/components/Layout/index.jsx` (but sourcing `src/layouts/index.jsx` looks fine)
* Lost styles from layouts on page templates in production (home page looks fine though); run time doesn't have this issue.

### Steps to reproduce

* move src/components/layout.js to src/components/Layout/index.jsx
* `gatsby develop`

### Expected result

What should happen?

### Actual result

What happened.

### Environment

  System:
    OS: macOS High Sierra 10.13.2
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.4.2 - /usr/local/bin/zsh
  Binaries:
    Node: 9.3.0 - ~/.nvm/versions/node/v9.3.0/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 6.0.0 - ~/.nvm/versions/node/v9.3.0/bin/npm
  Browsers:
    Chrome: 67.0.3396.79
    Firefox: 59.0.2
    Safari: 11.0.2
  npmPackages:
    gatsby: next => 2.0.0-alpha.51
    gatsby-source-filesystem: next => 2.0.0-alpha.15
    gatsby-transformer-remark: next => 2.0.1-13
  npmGlobalPackages:
    gatsby-cli: 1.1.51
    gatsby: 1.9.155

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by ryanditjia** [comment]
Have you followed the migration guide outlined here: https://gatsbyjs.org/docs/migrating-from-v1-to-v2/ ?

**Comment by wangsongiam** [comment]
@ryanditjia Hi, the link is invalid, and I followed the migration doc, which suggested I put layout into components.

**Comment by nihgwu** [comment]
here is the temp link https://v2--gatsbyjs.netlify.com/docs/migrating-from-v1-to-v2/
and simply move layout component from layout folder to components folder is not enough, you need to compose with the layout component
also I notice you have a case sensitive problem with your path which is not an issue on MacOS but is on Linux
