### ISSUE TITLE
[gatsby-source-mongodb] can't connect to MongoDB Atlas db as a service

### ISSUE THREAD

**Issue by lcostea** [gatsbyjs/gatsby#5833]
## Description

When using the gatsby-source-mongodb plugin I can't connect to MongoDB Atlas (their database as a service https://www.mongodb.com/cloud)
Some additional parameters need to be passed to the connection string and the way the plugin is created right now it is not possible

### Steps to reproduce

Create an account on https://www.mongodb.com/cloud/atlas (no cc reuquired, they have a free tier).
Create a database, a collection, add some data and try to connect to it using the plugin.
You will get an error because the connection string has to have additional parameters passed like this:
?ssl=true&replicaSet=<your-replica-set-name>&authSource=admin
When I added them manually to the plugin code I was able to connect, something like this:

```
MongoClient.connect(`mongodb://${authUrlPart}${serverOptions.address}:${serverOptions.port}/${dbName}?ssl=true&replicaSet=<my-replica-set>&authSource=admin`,` function (err, db) {
```
file gatsby-node.js from gatsby-source-mongodb
### Expected result

I should be able to connect to MongoDB Atlas, so actually I should be able to pass these 3 additional parameters to the connection string:
ssl
replicaSet
authSource

### Actual result

The error I get is:
⠐ source and transform nodes{ MongoError: no mongos proxy available
    at Timeout._onTimeout (D:\Personal_Repository\cfp-alerts-website\node_modules\mongodb-core\lib\topologies\mongos.js:677:28)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5) name: 'MongoError', message: 'no mongos proxy available' }
⠠ source and transform nodes

### Environment
  System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    npm: 5.0.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^1.9.241 => 1.9.241
    gatsby-link: ^1.6.39 => 1.6.39
    gatsby-plugin-google-analytics: ^1.0.31 => 1.0.31
    gatsby-plugin-google-fonts: 0.0.4 => 0.0.4
    gatsby-plugin-react-helmet: ^2.0.8 => 2.0.8
    gatsby-source-mongodb: ^1.5.19 => 1.5.19

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by lcostea** [comment]
I identified the error and I can provide a PR (with adding the 3 additional params) if you think the plugin should support MongoDB Atlas

**Comment by m-allanson** [comment]
Adding the params to support MongoDB Atlas sounds like a good plan, 👍 for a PR. 

Gatsby does something similar with the WordPress plugin, where it supports using your own WordPress instance or a hosted wordpress.com site.

**Comment by lcostea** [comment]
Added the PR [5972](https://github.com/gatsbyjs/gatsby/pull/5972)
