### ISSUE TITLE
Make Gatsby more resilient against slow networks, low batteries, etc.

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#5834]
This talk is full of good ideas — https://docs.google.com/presentation/d/169gop22hzmu-NEUiNQyoIZ_oRiMqNLFMKNJVvX42iC8/present?slide=id.g13fd0b2db0_0_13

One easy win would be adding a check to gatsby-image that on slow networks, don't download higher resolution images as that takes longer making for a poorer experience.

**Comment by CanRau** [comment]
Noooo don't close it @gatsbot I really like the idea 💯 or have I missed anything?? 🤓

**Comment by jgierer12** [comment]
Bad bot :wink:

**Comment by m-allanson** [comment]
I'm going to close this for now as it's not specifically actionable. @KyleAMathews will open new issues where appropriate.
