### ISSUE TITLE
Usage information shows something like 'index.js develop' instead of 'gatsby develop'

### ISSUE THREAD

**Issue by LujunWeng** [gatsbyjs/gatsby#5838]
## Relevant information
When I took a look at the usage of gatsby, it showed something like this 
```
$ gatsby --help
Usage: index.js <command> [options]

Commands:
  index.js develop                   Start development server. Watches files, rebuilds, and hot reloads if something changes  index.js build                     Build a Gatsby project.
  index.js serve                     Serve previously built Gatsby site.
  index.js new [rootPath] [starter]  Create new Gatsby project.

Options:
  --verbose      Turn on verbose output                                                           [boolean] [default: false]  --no-color     Turn off the color in output                                                     [boolean] [default: false]  -h, --help     Show help                                                                                         [boolean]  -v, --version  Show version number                                                                               [boolean]
```
They should be gatsby instead of index.js. 

### Environment (if relevant)
* Gatsby version (`npm list gatsby`): gatsby@1.9.149
* gatsby-cli version (`gatsby --version`): 1.1.53
* Node.js version: v8.11.2
* Operating System: Windows 10 (1803)

**Comment by ryanditjia** [comment]
I’m at gatsby-cli@1.1.58 and I’m not seeing index.js. Can you try upgrading and see if it fixes?

**Comment by LujunWeng** [comment]
@ryanditjia 
Got the same result after upgrading to 1.1.58
```
LujunW@DESKTOP MINGW64 /d/GitHub
$ gatsby -v
1.1.58

LujunW@DESKTOP MINGW64 /d/GitHub
$ gatsby --help
Usage: index.js <command> [options]

Commands:
  index.js develop                   Start development server. Watches files, rebuilds, and hot reloads if something
                                     changes
  index.js build                     Build a Gatsby project.
  index.js serve                     Serve previously built Gatsby site.
  index.js info                      Get environment information for debugging and issue reporting
  index.js new [rootPath] [starter]  Create new Gatsby project.

Options:
  --verbose      Turn on verbose output                                                        [boolean] [default: false]  --no-color     Turn off the color in output                                                  [boolean] [default: false]  -h, --help     Show help                                                                                      [boolean]  -v, --version  Show version number          
```

**Comment by LujunWeng** [comment]
I took a look at the code. It uses `$0` to fetch the command name dynamically and I also see some discussions on this in `yargs` issues. Why don't we just use `gatsby` instead of `$0`? The name won't change anyway.

**Comment by m-allanson** [comment]
Thank for the report @LujunWeng! It seems there's an open PR to fix this in yargs: https://github.com/yargs/yargs/pull/1143. Waiting for that to be merged seems like a good fix here.

**Comment by PhiLhoSoft** [comment]
I came here looking if this has been already reported, as I noticed this too.

As a heads up, it seems the yargs issue has been merged some days ago.

Minor problem, but good to see it addressed... :smile:

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by umstek** [comment]
`gatsby-cli` v2.4.2, I still see the issue.
