### ISSUE TITLE
[v2] Error: Cannot find module 'gatsby/graphql' after upgrade to gatsby@2.0.0-alpha.52

### ISSUE THREAD

**Issue by valse** [gatsbyjs/gatsby#5841]
Hi,
   as subject I can't compile my develop gatsby site after latest upgrade... I already tried to delete cache and node_modules folders.

My gatsby-cli version is the 1.1.58.

Thanks
Marco

**Comment by pieh** [comment]
@valse Can You try to do fresh re-install - there was broken release that *should* be fixed

**Comment by valse** [comment]
Hi,
   now with the latest 2.0.0-alpha.55 works, thanks!

Only a strange behavior: yarn (1.7.0) can't complete instead npm does :-\
