### ISSUE TITLE
How can I run V8 profiler to debug excessive CPU usage?

### ISSUE THREAD

**Issue by coreyward** [gatsbyjs/gatsby#5846]
One of my Gatsby apps is using 70% CPU consistently in development (`gatsby develop`). I found [this writeup on profiling Node apps](https://www.dynatrace.com/news/blog/how-to-track-down-cpu-issues-in-node-js/), but I'm not sure how to the approach working with a Gatsby app. 

### Environment (if relevant)
* Gatsby version (`npm list gatsby`): 1.9.252
* gatsby-cli version (`gatsby --version`): 1.1.58
* Node.js version: 10.3.0
* Operating System: macOS High Sierra

**Comment by m-allanson** [comment]
I think there are plans to add profiling support to Gatsby in the future, but I don't know what the timeline is for that.

`gatsby develop` is essentially a shortcut for `node node_modules/gatsby-cli/lib/index.js develop`. I think however you'd normally profile a node app, you should be able to do the same steps here?
