### ISSUE TITLE
[v2] gatsby-plugin-offline on Firefox reloads indefinitly

### ISSUE THREAD

**Issue by mquandalle** [gatsbyjs/gatsby#5848]
## Description

On Firefox 60 (Ubuntu) the `gatsby-plugin-offline` seems broken. When its installed and a new version of a website is served, the browser window is reloaded indefinitely without ending on the new version.

I've experienced this bug on my website, but also on https://www.gatsbyjs.com.

The only way to “solve” the issue on the user side, is to close the tab, and re-open it.

**Comment by KyleAMathews** [comment]
Thanks for the bug report! This is a known issue. I've been trying to find time to fix it but haven't yet so if you'd like to tackle it (or anyone else) please do!

**Comment by mquandalle** [comment]
I don't want to sound too catastrophic, but I think this is a pretty critical bug because it makes sites completely broken for Firefox users. If there isn't a plan to fix this issue soon, I think there should be a notice on the README of the plugin warning that the `gatsby-plugin-offline` is broken on Firefox.

**Comment by Khaledgarbaya** [comment]
could be related to this [issue](https://github.com/GoogleChromeLabs/sw-precache/issues/309).

**Comment by m-allanson** [comment]
@kkemple do you know if this was fixed in #2757?

**Comment by kkemple** [comment]
This is not fixed yet, it's a separate issue that needs investigation, I am working on this next actually.

**Comment by m-allanson** [comment]
This should be fixed in https://github.com/gatsbyjs/gatsby/pull/6566. I'm going to close this, but please reopen if you're still seeing the problem.
