### ISSUE TITLE
Calling all Gatsby contributors!

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/gatsby#5849]
Hi there,

I'm working on launching the Gatsby swag project, and contributors get first dibs. If you've contributed to Gatsby (e.g. code, docs, articles, tutorials), we want to send you swag. Please fill out the form!

 https://goo.gl/forms/EPvrCQJPB13DShJq1 

We're going to close the initial round of responses on June 13th so fill it out now if you want to get in on the first order!

**Comment by jlengstorf** [comment]
cc @gatsbyjs/gatsby-core-maintainers

**Comment by tsiq-swyx** [comment]
i would rock a gatsby monocle so hard, just sayin

**Comment by jlengstorf** [comment]
Closing this since the form is closed.
