### ISSUE TITLE
How to properly use CSS tutorials/example please?

### ISSUE THREAD

**Issue by sincu** [gatsbyjs/gatsby#585]
First of all want to thank all people contributing in this great stack. I really hope to contribute someday in any way, but right now I am kinda newbie in React, webpack, server-render and tons of other cool stuff, but really trying to learn.  

While exploring the source code of `gatsby-starter-blog` I found that there a lot of places where I have to put my stylesheets. Is there's a way to place all necessary CSS code in one place? More specific example, so you could imagine how much pain feel all newbies like me - I simple can't find where I can change media queries for Container (one with max-width), it's inline CSS. 

Appreciate any help, and sorry that it is really not sort like an issue.

**Comment by KyleAMathews** [comment]
Gatsby supports almost any css style e.g. Sass, Less, plain CSS, CSS Modules, inline styles, etc.

If you want something simple to start with, I suggest creating a `main.css` file in the root of your site and importing that into your `pages/index.js` (`import 'main.css` will do this). You can then write normal css with media queries etc.
