### ISSUE TITLE
/www gatsby hompage local build routes not working

### ISSUE THREAD

**Issue by Niko-La** [gatsbyjs/gatsby#5850]
gasby develop has all the routes working fine.

however, gatsby build is not linking the other suburls.  index.html works fine but can not navigate to all other links such as blogs, tutorial, docs.

to reproduce:
```
git clone gatsby repo
cd /www

yarn instaal
yarn run develop
```

update:  deploying the /public folder on netlify the routing is working properly.  if build files only work on static hosting deployment.  this issue is non issue. thanks

**Comment by m-allanson** [comment]
You can use `gatsby serve` to test a built site locally. Closing as I think this is resolved? Please re-open if not!
