### ISSUE TITLE
move /packages , /docs into /www to easily deploy on netlify

### ISSUE THREAD

**Issue by Niko-La** [gatsbyjs/gatsby#5851]
It is difficult to redeploy the /www gatsby homepage on netlify as some of the content is outside of the /www such as /packages and /docs.

It would be easier for people to deploy and see gatsby in their own cdn deployment if all the content was inside /www

especially for the netlify github auto deployment

**Comment by KyleAMathews** [comment]
Curious to hear what you're trying to do?
