### ISSUE TITLE
[v2] Update docs to cover breaking changes in v2

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#5853]
## Summary

Now that the v2 API's have mostly settled down, make a pass through Gatsby's docs and update them to reference the correct parts of Gatsby's API for v2. 

Remove references to layouts, add mentions of StaticQuery. Document `pageContext` (previously `pathContext`, but it doesn't seem like there's any docs for that).

### Basic example

The [_Querying with GraphQL_](https://v2--gatsbyjs.netlify.com/docs/querying-with-graphql/) doc:

- doesn't mention StaticQuery, which it should
- does mention Layouts, which it shouldn't

### Motivation

Docs should be in sync with API updates.

**Comment by fk** [comment]
Let's see if I'll do this right…

The [Actions](https://next.gatsbyjs.org/docs/actions/) doc:

* does still mention `boundActionCreators`, should be `actions`
