### ISSUE TITLE
Remove comments in styled-components stylesheet

### ISSUE THREAD

**Issue by mquandalle** [gatsbyjs/gatsby#5861]
Currently there are comments (and line breaks) in the production stylesheet generated by the `styled-components` plugin, for instance:

```
/* sc-component-id: format-utils__IntegerPart-s1xarsmj-0 */
.kCZZrB{font-size:1.8em;line-height:0.8em;margin-right:0.1em;font-weight:bold;}
/* sc-component-id: format-utils__Exponent-s1xarsmj-1 */
.ejifEU{text-align:top;font-size:0.85em;margin-top:-0.15em;margin-bottom:-0.1em;font-weight:bold;top:0.5em;}
```

I think that in this example the two comments lines `/* sc-component-id ...*/` are unnecessary and should be removed in production.

**Comment by nihgwu** [comment]
does this help? https://github.com/gatsbyjs/gatsby/blob/v2/packages/gatsby-plugin-styled-components/README.md#options

**Comment by mquandalle** [comment]
No, it doesn't solve this issue.

**Comment by m-allanson** [comment]
Hmm it seems like the Styled Components babel plugin should handle minification by default: https://www.styled-components.com/docs/tooling#minification

I'd be interested if anyone can investigate why the styles aren't being minified.

**Comment by m-allanson** [comment]
Also make sure you're using `babel-plugin-styled-components` with the Styled Components plugin.

**Comment by mquandalle** [comment]
Note that this issue is observable in the deployed `styled-components` example: view-source: https://using-styled-components.gatsbyjs.org/

The styles are still minified (line breaks and spaces are removed for instance) but there are these `sc-component-id` comments in the middle. It seems it may be an "issue" with styled-components and not with Gatsby integration.

However it also seems that the `ssr` option isn't working correctly, it is supposed to add unique id on styled-components DOM nodes to avoid bugs during re-hydration, but it never worked for me.

**Comment by mquandalle** [comment]
Ok so the `sc-component-id` are actually needed for re-hydration: https://github.com/styled-components/styled-components/issues/1217

On the SSR issue, I think the problem is that the `ssr` option is only activated while building the HTML, but it should also be activated while bundling the JS in order to add the unique ids in the styled components nodes.

**Comment by mquandalle** [comment]
Closing since the comments are a design decision by styled-components. I opened a separate issue for the SSR bug https://github.com/gatsbyjs/gatsby/issues/5993.
