### ISSUE TITLE
How do I use graphql-compose or extend the schema in gatsby

### ISSUE THREAD

**Issue by richtera** [gatsbyjs/gatsby#5864]
## Summary
I would like to extend graphql to allow elasticsearch queries and I am not sure how. I read through the code but I don't see a good plugin point for extending the graphql schema.
I am trying to use: https://github.com/graphql-compose/graphql-compose-elasticsearch

### Environment (if relevant)
* Gatsby version (`npm list gatsby`):
gatsby@1.9.246
* gatsby-cli version (`gatsby --version`):
1.9.270
* Node.js version:
v9.11.1
* Operating System:
Mac OS 10.13.4 (17E202)

### File contents (if changed)
I just downloaded the gatsby-material-starter to check things out. Didn't make any modifications as of yet since I wanted to a prototype which would connect to our ES server.

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by m-allanson** [comment]
You may be able to do this with the [`setFieldsOnGraphQLNodeType` API](https://www.gatsbyjs.org/docs/node-apis/#setFieldsOnGraphQLNodeType). Check out some of the plugins in this repo for examples of how it's used. 

Note there's [a proposal for enhancing GraphQL schema creation in Gatsby], but there's not been time to implement it yet.

**Comment by pieh** [comment]
Just to clarify - Gatsby graphql layer is used only during build. `elasticsearch` would suggest using it in runtime (when user on your site uses search). If you are looking for runtime graphql then You would need to use some kind of client graphql client (like `apollo-client`).

If this for build, then see comment above. We plan to add schema stitching that would allow you to append 3rd party graphql schemas to one generated by gatsby, but it's not done yet.

**Comment by LekoArts** [comment]
Above mentioned RFC was merged
