### ISSUE TITLE
Netlify redirects with multiple domains and subdirectories

### ISSUE THREAD

**Issue by MathRivest** [gatsbyjs/gatsby#5868]
Hi!
I am trying to serve `/my-page-1` to domain1.com and '/my-page-2' to domain2.com. Everything is working well using Netlify _redirects file but after a split second, I get redirected again to a 404

It goes like this
- User hits `domain1.com`
- User sees content from `/my-page-1`
- User sees 404 or whatever page is at `index.js` **this step shouldn't happen!**

## Relevant information

Here's what my redirects file looks like
```
https://domain-1.com /my-page-1/ 200!
https://domain-2.com /my-page-2/ 200!
```

Anything I'm doing wrong?

**Comment by MathRivest** [comment]
I'm expecting that when I hit `domain-1.com` to see the content from `/page-1` without seeing `domain-1.com/page-1/`. I'd like `page-1` to be my root but since I have two domains, I can't use the index.js.

I would like `domain-1.com` and `domain-2.com` show the content from `/page-1` and `/page-2`

**Comment by m-allanson** [comment]
Hmm I'm not sure how you'd do this without creating two Gatsby sites. Gatsby isn't aware of the domain it's served from (e.g. `example.com`) it only knows about the url path `/`, `/page-1` etc.

You're trying to serve two different pages for the same url path, which I think is what's causing your issue here.

**Comment by MathRivest** [comment]
You can see it in action here https://promessesbrisees.spca.com and https://brokenpromises.spca.com. When you refresh you can see the page located at /fr for a split second before being redirected to the content of the index.js file

**Comment by MathRivest** [comment]
I was thinking that rewriting the url by redirecting with a 200 would work https://www.netlify.com/docs/redirects/#http-status-codes 

But it looks like the client is redirecting after for some reason!
