### ISSUE TITLE
Gatsby Documentation

### ISSUE THREAD

**Issue by briancappello** [gatsbyjs/gatsby#587]
Hi @KyleAMathews,

Following up on https://github.com/gatsbyjs/gatsby/pull/581#issuecomment-263478142, I began splitting out the README and have added a bit of explanation for how (I think) Gatsby's templating works.

I could not find an in-use github pages branch for Gatsby, so I figured it would make sense to use gatsby for generating the documentation. My fork of the documentation starter can be found here: https://github.com/briancappello/gatsby-documentation-site

Aside from splitting out the README into separate smaller files, my additions can be seen towards the end of this commit: https://github.com/briancappello/gatsby-documentation-site/commit/f8c0d1a8525c5b301e71c798248741684dda9071

If you'd prefer the approach of plain markdown files in the gatsby repo, I can open a PR there instead.

**Comment by KyleAMathews** [comment]
Woah! This is awesome! I do actually have a [website-in-progress for 1.0](https://github.com/gatsbyjs/gatsby/issues/149#issuecomment-260153764) so I don't know building/launching a website for 0.x makes sense. I think putting markdown files into a `docs/` directory makes the most sense for now. We can then move/convert those for the 1.0 website as we start working on that.

Thanks for working on this!

**Comment by briancappello** [comment]
Ah look at that, cool. I should still open against master, no? At first glance it looks like 1.0 and master have diverged a fair bit?

**Comment by KyleAMathews** [comment]
Yeah, against master. 1.0 is a decent sized break.

**Comment by briancappello** [comment]
OK, PR at https://github.com/gatsbyjs/gatsby/pull/588
