### ISSUE TITLE
Refresh Endpoint: wrong usage of env variable

### ISSUE THREAD

**Issue by NaderIkladiousC** [gatsbyjs/gatsby#5874]
Hello,
I Tried to use this feature but it is not as documented as the function uses the wrong environment variable.
`gatsby/src/commands/develop.js`

it should be this:
```javascript
  app.post(`/__refresh`, (req, res) => {
    const enableRefresh = process.env.GATSBY_ENABLE_REFRESH_ENDPOINT
    const refreshToken = process.env.GATSBY_REFRESH_TOKEN
    ...
  })
```

instead of this:
```javascript
  app.post(`/__refresh`, (req, res) => {
    const enableRefresh = process.env.ENABLE_GATSBY_REFRESH_ENDPOINT
    const refreshToken = process.env.GATSBY_REFRESH_TOKEN
    ...
  })
```

Nader Ikladious.

**Comment by thibautRe** [comment]
Hey @kakadiadarpan 

> I couldn't find any reference in the documentation for `Refresh Endpoint`
It's an undocumented feature so you won't find any.

I think what @NaderIkladiousC meant is that most of the GATSBY env variables start with `GATSBY_` except this one, which can be confusing. Renaming that env variable would make things more consistent - but would be a breaking change for people using that feature.

**Comment by kakadiadarpan** [comment]
@thibautRe Thanks for the clarification.

@pieh any inputs regarding this?
