### ISSUE TITLE
Site submission for GatsbyJS showcase

### ISSUE THREAD

**Issue by pavsidhu** [gatsbyjs/gatsby#5877]
I'd love to have my website ([blog.pavsidhu.com](https://blog.pavsidhu.com)) to be added to the Gatsby showcase.

Let me know if there's any information/help needed.

**Comment by pieh** [comment]
Hey, we are still ironing out submission process - you can check ongoing work here - https://github.com/gatsbyjs/gatsby/pull/5867 ! Once we finalize on how the process will look like, You will be able to follow instruction to submit your website to showcase! 😃
