### ISSUE TITLE
Move cache dir from /.cache to /node_modules/.cache

### ISSUE THREAD

**Issue by ekoeryanto** [gatsbyjs/gatsby#5880]
## Summary

Just what title says

### Motivation

on most CI we can save node_modules directory to the cache I think it is better to put the cache inside node_modules because it need not more setup, and also on we can speed up netlify build

**Comment by jquense** [comment]
there is prior art for this as well. babel-loader does this, and a few other things i forgot about...

**Comment by m-allanson** [comment]
This seems pretty reasonable to me... any thoughts @pieh @KyleAMathews?

**Comment by m-allanson** [comment]
This is the module used by `babel-loader` (and others): https://github.com/avajs/find-cache-dir

**Comment by jquense** [comment]
I do think we should pair such a change with `gatsby clean` command

**Comment by KyleAMathews** [comment]
Yeah, seems like a reasonable/good change. One problem is that some of the ".cache" folder isn't actually a cache — it's where Gatsby copies runtime and other necessary files into the project folder so they're available for requiring at a predictable place. We'll need to keep that but other cache files we could move inside `node_modules`.

**Comment by mathieudutour** [comment]
I'm trying to run gatsby on AWS Lambda and it's complaining because the only directory with write permission is `/tmp`.

What about giving the possibility to specify the cache location with an option (either in the gatsby config or as a cli option)?

I'm happy to work on this

**Comment by KyleAMathews** [comment]
We should do this — it's kind of a breaking change though so we should do it in v3.

**Comment by langri-sha** [comment]
Would it be possible to make this configurable, or use https://github.com/avajs/find-cache-dir? This would give us some control over where the cache directory is located.

For my use case (and I believe this might be true for most CI users), having a single, common cache directory means we can restore/preserve the cache independently from our sources without introducing any exceptional cases.

**Comment by huy-nguyen** [comment]
Not every Gatsby setup will have a node_modules directory e.g if you use Yarn v2.

**Comment by wardpeet** [comment]
There is not much value in allowing different .cache folders from our perspective. We haven't got many requests for it and it would make our code harder to maintain to make sure we write to the right folder.

Thank you for suggesting it!
