### ISSUE TITLE
gatsby-plugin-sitemap: add an ability to add the rel="alternate" attrubute for URLs in different languages

### ISSUE THREAD

**Issue by oobidin** [gatsbyjs/gatsby#5888]
## Summary

There is a [guide](https://support.google.com/webmasters/answer/2620865?hl=en) to do i18n right way: often you need to set alternate URLs for the same page. Right now there are just 3 attributes for URL, which can be overwritten: 'url', 'changefreq' and 'priority', [proof](https://github.com/gatsbyjs/gatsby/blob/1f8ef1928ea9d5338f268c1a27bda3c39a398329/packages/gatsby-plugin-sitemap/src/internals.js).

### Basic example

I think it should be something like an argument of createPage() function with the name like 'alternates':
```
createPage({
  path: '/example/english/',
  component: path.resolve('src/templates/index.js'),
  context: {
    ...
  },
  alternates: [
    {
      url: '/example/deutsch/',
      hrefLang: 'de'
     }
   ]
})
```

### Motivation

The motivation is an ability to generate internationalized sitemaps in the future.

**Comment by vincentdesmares** [comment]
I wish this was already possible :)

Btw, small typo in the issue name: atrubute -> attribute.

**Comment by nicomfe** [comment]
+1

**Comment by CanRau** [comment]
`alternates` could be stuffed in context? I'm trying to wrap my head around some universal i18n solution for gatsby as well, would be nice to have it as dynamic as possible to allow for different methods like subdomain and directory based routes

**Comment by assainov** [comment]
> Heya! 👋
> For those stumbling across this issue looking to internationalize a sitemap of their own, I do have a bit of good news 😄gatsby-plugin-sitemap actually does support [internationalized sitemaps](https://support.google.com/webmasters/answer/2620865?hl=en). It just takes a little bit of extra code.

I tried the suggested approach, but for me it is not working. The sitemap can no longer be pretty printed, but pages still don't have hreflang tags in them.

Usage in serialize function:
````
return {
  url: site.siteMetadata.siteUrl + edge.node.path,
  changefreq: `daily`,
  priority: 0.7,
  links: [
    { lang: 'en', url: `${site.siteMetadata.siteUrl}/en/${purePath}` },
    { lang: 'ar', url: `${site.siteMetadata.siteUrl}/ar/${purePath}` },
    { lang: 'x-default', url: `${site.siteMetadata.siteUrl}/${purePath}` }
  ]
}
````

**Comment by CanRau** [comment]
@tinder-kyleboss not sure I understand your use case correctly yet as I see it it'll generate one sitemap with links to all pages in all languages right?
Does that make sense for Google?
And I don't understand where you get `path` from? Is it declared somewhere at the top?

I do it like this right now

```
const getSitemapForLanguage = lang => ({
  output: `/${lang}/sitemap.xml`,
  exclude: [`/${lang}/thanks`, `/${lang}/danke`, `/${lang}/404`],
  createLinkInHead: false, // done manually in MainLayout
  query: `
    {
      site {
        siteMetadata {
          siteUrl
        }
      }
      allSitePage( filter: { path: { regex: "/^\/${lang}\//" } } ) {
        edges {
          node {
            path
          }
        }
      }
    }`,
  serialize: ({ site, allSitePage }) =>
    allSitePage.edges.map(edge => ({
      url: site.siteMetadata.siteUrl + edge.node.path,
      changefreq: `daily`,
      priority: 0.7,
    })),
})
```
then in `plugins` array
```
[
  {
    resolve: `gatsby-plugin-sitemap`,
    options: getSitemapForLanguage(`en`),
  },
  {
    resolve: `gatsby-plugin-sitemap`,
    options: getSitemapForLanguage(`de`),
  },
]
```
could of course be looped sthg like 
```
plugins.push([`en`, `de`].forEach(lang => {
    resolve: `gatsby-plugin-sitemap`,
    options: getSitemapForLanguage(lang),
}))
```
especially having more languages..

I define alternate languages in my layout file using (still) `react-helmet`

Or am I missing the point here?

@assainov Maybe it is of any help to you?

**Comment by cakasuma** [comment]
thanks it works for me, but is there any workaround to get it pretty-printed, or customize sitemap styling

**Comment by cakasuma** [comment]
@asainov maybe this could be of help, this is my working solution, tho its still not pretty printed
```
{
      resolve: `gatsby-plugin-sitemap`,
      options: {
        query: `
          {
            site {
              siteMetadata {
                siteUrl
              }
            }
   
            allSitePage {
              edges {
                node {
                  path
                }
              }
            }
        }`,
        serialize: ({ site, allSitePage }) =>
          allSitePage.edges.map((edge) => {
            const { path } = edge.node
            const pathArray = path.split('/')
            const currentLang = pathArray[1]
            const checkLang = currentLang.replace('-', '_')
            let currentPage = path
            const keyLanguages = ['en', 'id']

            if (keyLanguages.includes(checkLang)) {
              pathArray.splice(1, 1)
              currentPage = pathArray.join('/')
            }

            const sitemapLangs = keyLanguages.concat(['x-default'])

            const links = sitemapLangs.map((locale) => {
              const replacedLocale = locale.replace('_', '-')

              const isDefault = locale === 'en' || locale === 'x-default'
              const hrefLocale = isDefault ? '' : `/${replacedLocale}`
              const href = `${site.siteMetadata.siteUrl}${hrefLocale}${currentPage}`

              return { lang: replacedLocale, url: href }
            })

            return {
              url: site.siteMetadata.siteUrl + path, // https://sitemaps.com/page-path
              changefreq: 'daily',
              priority: 0.7,
              links,
            }
          }),
      },
    },
```

**Comment by mustofa-binary** [comment]
Any idea how to make sitemap pretty printed

**Comment by timonmasberg** [comment]
This seems to be impossible now, as `serialize` does not receive the data from the query? I have to map it into every page object in `resolvePages` now?
