### ISSUE TITLE
remove graphql dependency or make graphql into a peerDependency

### ISSUE THREAD

**Issue by timbrandin** [gatsbyjs/gatsby#5897]
Would be great if graphql was a peerDependency or as an extension to gatsby, rather than being central to gatsby's infrastructure.

**Comment by timbrandin** [comment]
I can't render graphiql in gatsby as it is now, because the versions of graphql collide, without any method of resolving the issue.

**Comment by m-allanson** [comment]
This should be resolved in Gatsby v2: https://github.com/gatsbyjs/gatsby/issues/4711

The v2 beta has just been released, check out the [migration guide](https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/).

**Comment by LekoArts** [comment]
Closing this issue as Gatsby v2 has been released.
