### ISSUE TITLE
How do gatsby-remark-custom-blocks works?

### ISSUE THREAD

**Issue by heyalbert** [gatsbyjs/gatsby#5904]
How do Remark Custom Block works? https://www.gatsbyjs.org/packages/gatsby-remark-custom-blocks/?=block

I couldn't figure it out on my own and the documentation is close to non-existent. 

This is in my gatsby-config.js (as the doc says):
```js
	{
		resolve: `gatsby-transformer-remark`,
		options: {
		  plugins: [
			{
			  resolve: "gatsby-remark-custom-blocks",
			  options: {
				blocks: {
				  danger: "custom-block-danger",
				  info: "custom-block-info",
				},
			  },
			},
		  ],
		},
	},
```

And this is in my index.md file:
```md
[[custom-block-danger]]
| content
```

But nothing happened. What is it, that I'm doing wrong?

**Comment by m-allanson** [comment]
Hmm those docs are pretty sparse, it'd be great to see a PR updating them if you have the chance?

I think your example should work if you change your index.md to include:
```
[[danger]]
| content
```

This will wrap your content in a `div` with the class `custom-block-danger`, like this:
```
<div class="custom-block-danger">
  <p>content</p>
</div>
```

Which you can then style how you like.

**Comment by wuweiweiwu** [comment]
@m-allanson I can pick this up!
