### ISSUE TITLE
gatsby-link navigateTo but replace rather than push?

### ISSUE THREAD

**Issue by tremby** [gatsbyjs/gatsby#5910]
## Summary

I'd like to use `gatsby-link`'s `navigateTo`, but replace the current history item rather than push to history.

## Relevant information

My use case is a front page which automatically selects a language for the user based on their preferences. It'll take them to the language-specific home page, and now the back button should take them to whatever site they were on before mine, rather than back to the language select page (which would just boot them forward again).

## Proposal

Perhaps an option for `replace` could be added to `navigateTo`? Perhaps `navigateTo("/whatever", {replace: true})`, or just `navigateTo("/whatever", true)`?

I'm willing to put together a patch for this, if you'll tell me which direction you'd like to go in, and direct me to places in the code I'd need to touch. (Is it just `packages/gatsby/cache-dir/root.js` where `window.___navigateTo` is defined? Or `production-app.js` too? I'm not sure I understand what that one is doing.)

## Alternative?

Or am I going along the wrong lines -- is there some way to set up a redirect which is conditional on information only available at runtime?

## For now

Finally, it appears that `window.___history.replace("whatever")` works for now -- is there any danger with that in the mean time?

**Comment by KyleAMathews** [comment]
Honestly kinda regretting naming it `navigateTo`. We should just emulate push/replace and take the same parameters.

>Finally, it appears that window.___history.replace("whatever") works for now -- is there any danger with that in the mean time?

Yes — look at the implementation of `navigateTo`. It waits for all the resources for that page to be loaded before rendering. `replace` is only working because I guess all the state your page needs is loaded. If they're not, then the page could error.

**Comment by tremby** [comment]
> Honestly kinda regretting naming it `navigateTo`. We should just emulate push/replace and take the same parameters.

Is this something I could help with? Bear in mind I have virtually no knowledge of the Gatsby codebase. If it would be a simple enough change, please point me in the right direction.

**Comment by tremby** [comment]
Pull request at #5934.

**Comment by tremby** [comment]
My v2 PR for this was merged, and the v1 one is accepted. Closing.
