### ISSUE TITLE
no html markup in gatsby page source

### ISSUE THREAD

**Issue by dannyf1090** [gatsbyjs/gatsby#5913]
## Description

When running gatsby build inspecting page source does not display the html tags that we require for google crawling and SEO.  Page source currently displays:    
`<body>
        <div id="___gatsby">
            <app data-reactroot=""></app>
        </div>
        <script id="webpack-manifest">
`

### Steps to reproduce

run gatsby build and view page source

### Expected result

When viewing page source I am expecting the html markup to display in the body

### Actual result
Page is visibly working but the body html markup is not shown on view page source.  No errors appear in the console.

`<body>
        <div id="___gatsby">
            <app data-reactroot=""> </app>
        </div>
`
### File contents (if changed)

gatsby-config.js:
`
module.exports = {
  plugins: [
      'gatsby-plugin-react-helmet',
      'gatsby-plugin-antd',
      'gatsby-transformer-sharp',
      'gatsby-plugin-sharp',
      'gatsby-image',
      `gatsby-plugin-react-next`,
      {
        resolve: 'gatsby-source-filesystem',
        options: {
          name: 'blog',
          path: `${__dirname}/src/`
        }
      },
      {
        resolve: 'gatsby-plugin-purify-css',
        options: {
          styleId: 'gatsby-inlined-css',
          purifyOptions: {
            info: true,
            minify: true
          }
        }
      },
      {
        resolve: `gatsby-source-prismic`
      },
  ]
}
`

package.json: `"dependencies": {
    "@types/googlemaps": "^3.30.9",
    "@types/markerclustererplus": "^2.1.33",
    "antd": "^3.5.2",
    "gatsby": "^1.9.261",
    "gatsby-image": "^1.0.51",
    "gatsby-link": "^1.6.44",
    "gatsby-plugin-antd": "^1.0.12",
    "gatsby-plugin-purify-css": "^2.2.1",
    "gatsby-plugin-react-helmet": "^2.0.11",
    "gatsby-plugin-react-next": "^1.0.11",
    "gatsby-plugin-sharp": "^1.6.44",
    "gatsby-plugin-sitemap": "^1.2.23",
    "gatsby-plugin-webpack-bundle-analyzer": "^0.1.1",
    "gatsby-source-filesystem": "^1.5.36",
    "gatsby-source-prismic": "^1.0.0-alpha.9",
    "gatsby-transformer-sharp": "^1.6.24",
    "prismic-dom": "^2.1.0",
    "prismic-javascript": "^1.5.0-beta.3",
    "prismic-reactjs": "^0.3.1",
    "react-google-maps": "^9.4.5",
    "react-helmet": "^5.2.0",
    "react-lazyload": "^2.3.0",
    "react-redux": "^5.0.7",
    "react-transition-group": "^2.3.1",
    "redux": "^4.0.0",
    "redux-persist": "^5.9.1",
    "styled-components": "^3.2.6"
  },
`

gatsby-node.js: N/A 
gatsby-browser.js: `import React from "react";
import { Provider } from "react-redux";
import { Router } from 'react-router-dom'
import configureStore from './src/redux/store';
import { PersistGate } from 'redux-persist/integration/react'

const { store, persistor } = configureStore()

exports.replaceRouterComponent = ({ history }) => {

  const ConnectedRouterWrapper = ({ children }) => (
    
    <Provider store={store}>
     <PersistGate loading={null} persistor={persistor}>
        <Router history={history}>{children}</Router>
     </PersistGate>
    </Provider>
  )

  return ConnectedRouterWrapper
} `
gatsby-ssr.js: ` import { ServerStyleSheet, StyleSheetManager } from 'styled-components' 
 import React from 'react'
 import { Provider } from 'react-redux'
 import { renderToString } from 'react-dom/server'
 import Helmet from "react-helmet"
 import initStore from './src/redux/store

 exports.replaceRenderer = ({
    bodyComponent,
    replaceBodyHTMLString,
    setHeadComponents,
  }) => {
    const sheet = new ServerStyleSheet();
    const store = initStore();
  
    const app = () => (
      <Provider store={store}>
        <StyleSheetManager sheet={sheet.instance}>
          {bodyComponent}
        </StyleSheetManager>
      </Provider>
    );
    replaceBodyHTMLString(renderToString(<app />));
    setHeadComponents([sheet.getStyleElement()]);
  }; `

**Comment by m-allanson** [comment]
It sounds like `renderToString(<app />)` in `gatsby-ssr.js` is not rendering your app. Can you do some debugging to see what's being output by that function call? Maybe it should be `renderToString(app())` or `renderToString(<App />)`?

**Comment by dannyf1090** [comment]
Thanks for the quick response, the initial problem was the lowercase <app /> which i changed to <App /> allowing me to then debug the other issue which was my implementation of redux-persist.  You have saved me alot of time.  Thanks
