### ISSUE TITLE
[v2] PageRenderer exported from gatsby doesn't work in production

### ISSUE THREAD

**Issue by pieh** [gatsbyjs/gatsby#5920]
https://github.com/gatsbyjs/gatsby/blob/v2/packages/gatsby/src/cache-dir/gatsby-browser-entry.js#L8-L15 
`JSONStore` used there isn't used in production anywhere else and will never render anything in production. My hacky solution to use `page-renderer.js` directly instead of `JSONStore` there for production builds seems to work, but I need to investigate it more and figure out not hacky solution to make it work for both production and development.

For reference - here's hacky fix - https://github.com/pieh/gatsby/commit/fc3b255c80229b537937d3e3f096497b7220fc46

**Comment by KyleAMathews** [comment]
Seems like a reasonable hack :-) Main thing is to avoid loading any extra code into production.
