### ISSUE TITLE
[www/showcase] Add descriptions, creators, and dates added

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#5928]
Most sites have no descriptions, creators, or dates added fields.

The community can add these one-by-one, or someone could write a script to contact each person and ask them whomever initially added their site to the Awesome Gatsby list can now update their site's fields in the showcase.

^^^ @kyleamathews' idea

**Comment by fk** [comment]
Argh, added #6722 a couple mins ago which mostly is a duplicate of this. Will sort this out later.
