### ISSUE TITLE
[v2] Deprecate navigateTo and replace with "push" and "replace"

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#5935]

**Comment by mquandalle** [comment]
I think the PR implementing this should take a look at #5937

**Comment by KyleAMathews** [comment]
This is mostly fixed in https://github.com/gatsbyjs/gatsby/pull/5944

I think it's causing trouble in tests though as we need to mock window.__push and window.__replace now

**Comment by KyleAMathews** [comment]
This is done now afaik.
