### ISSUE TITLE
[v2] window.___push losing state if the page is not loaded yet

### ISSUE THREAD

**Issue by mquandalle** [gatsbyjs/gatsby#5937]
The `window.___navigateTo` accepts an argument that can contain some state like so:

```js
window.___navigateTo({pathname: "/myPath/", state: {modal: true}});
```

This is working as expected if `/myPath/` resources are already loaded, but if there are not the state is lost — the page is still rendered, but not in a modal in the above example.

**Comment by mquandalle** [comment]
This problem is still present in `beta.1` with the new `push` function introduced by #5944:

```js
window.___push({pathname: "/myPath/", state: {modal: true}});
```

won't open the page in a modal if its resources aren't loaded yet (the state is lost). Do you have any idea @tremby?

**Comment by tremby** [comment]
Afraid not. I don't fully understand how the implementation works; I just
renamed and tweaked a little.

**Comment by mquandalle** [comment]
I'm trying to fix this bug, but I have a hard time understating the implementation. I'm not sure how gatsby is waiting for resources to load before navigating to the page.

However I though that this issue had to do with page resources not being loaded, but it doesn't seem to be the case since doing the following doesn't fix the issue:

```js
window.___loader.getResourcesForPathname('/myPath/');
window.___push({pathname: "/myPath/", state: {modal: true}});
```

It seems that the state is lost the first time the page is displayed (independently of page resources being loaded or not) and then once the page has been displayed once, subsequent pushes work as expected with the state being transmitted. @KyleAMathews Any pointer about this issue?

**Comment by mquandalle** [comment]
@m-allanson You moved this issue to “In progress”, have you been able to reproduce it?

**Comment by pieh** [comment]
@mquandalle I didn't notice your comment earlier - here's where Gatsby does wait for resources before changing path and setup `window.___push` and `window.___replace` functions https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/cache-dir/production-app.js#L55-L111 (that's what use for builds, for develop it's simplier but would still need some handling in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/cache-dir/root.js )

**Comment by mquandalle** [comment]
By working on a minimal reproduction I was able to find that the issue was in my implementation of the modal system, I'm sorry for the inconvenience.
