### ISSUE TITLE
Auto-add check if each "publisher" is an owner when publishing npm packages

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#5943]
Otherwise when we add a new package, the first person to publish the package will be the only owner and if another person tries to publish the package, `lerna publish` will fail.

We should add a publishers.txt file or something like that with each npm name.

The only tricky part is identifying new packages. Perhaps the publish script can be expanded to check if there's a previously unpublished package and then add owners after the publish (so the package exists on npm to have owners added to it).

/cc @pieh @m-allanson

**Comment by DSchau** [comment]
We actually did this! We aren't as smart (so it's more manual) but it just checks if you don't own a package--if you don't, the publish will fail.

https://github.com/gatsbyjs/gatsby/blob/master/scripts/check-publish-access/index.js

Closing!
