### ISSUE TITLE
[v2] Update to latest version of babel-loader

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#5949]
beta.3 is latest atm and we're still on the first alpha

**Comment by m-allanson** [comment]
Looks like we're up to beta.0 now https://github.com/gatsbyjs/gatsby/blob/5504d8bc3bf8fd6255dca4f0588e6a588fd1195a/packages/gatsby/package.json#L29

**Comment by KyleAMathews** [comment]
Yeah, I was wrong about the alpha part.

**Comment by langovoi** [comment]
Maybe update babel-loader to latest beta?
<img width="961" alt="image" src="https://user-images.githubusercontent.com/5055595/42713066-b8b489c4-86f6-11e8-8d58-3677f926c8f3.png">

**Comment by KyleAMathews** [comment]
@langovoi yeah, this is still needed! Want to look into what the breaking changes are (if any) and PR an update?

**Comment by langovoi** [comment]
@KyleAMathews sure! I will do ;-)

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by langovoi** [comment]
@KyleAMathews look #6445 ;-)
