### ISSUE TITLE
[v2] Pre-release Todos

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#5953]
- [x] change wordpress/drupal source plugins dependency from `next` back to version range
- [x] remove `--allow-next` flag from `check-versions` script in `package.json`
- [x] change all examples' package.json to use `^2.0.0` (or whatever new latest is) for each plugin (@pieh working on that)
- [x] Remove robots.txt from www/static in prep for moving building gatsbyjs.org to master again (@pieh working on that)
- [x] Merge `v2` branch into to `master` in official starters, update package.json to use "^2.0.0" (or whatever new latest is) and update demo sites
- [x] Update .org banner text "These are the docs for v2 ~beta~. View the v1 docs instead." (@pieh working on that)
- [x] Update gatsby.app links to point to gatsbyjs.org instead of next.gatsbyjs.org
- Change installation instruction in docs to use `master` branches of starters (@pieh working on that)
   - [x] Get Started: Revert https://github.com/gatsbyjs/gatsby/pull/6685
   - [x] Tutorials
- [x] remove `gatsby-link` from plugin library

**Comment by m-allanson** [comment]
Ref: https://github.com/gatsbyjs/gatsby/issues/7976

**Comment by KyleAMathews** [comment]
PRs to merge:

- https://github.com/gatsbyjs/gatsby/pull/8227
- https://github.com/gatsbyjs/gatsby/pull/8172
- https://github.com/gatsbyjs/gatsby/pull/8226
- https://github.com/gatsbyjs/gatsby/pull/8176
- https://github.com/gatsbyjs/gatsby/pull/8177

**Comment by m-allanson** [comment]
V2 is released!
