### ISSUE TITLE
Accessing a programmatically generated page via a direct link

### ISSUE THREAD

**Issue by bluprince13** [gatsbyjs/gatsby#5971]
## Summary
I am using Gatsby to generate a static website which I'm hosting on ForumPass, basically a [Microsoft Sharepoint](http://www.myexostar.com/ForumPass/) server. When I try to directly access pages programmatically generated using the [createPages API](https://www.gatsbyjs.org/docs/creating-and-modifying-pages/), I get a message saying 'Not found. You just hit a route that doesn't exist... the sadness'.  When I look at the console, there is a message that says 'A page wasn't found for loader.js: ...'.

If I navigate to the programmatically generated pages from the Homepage, then the error doesn't occur and the pages render fine. Also, trying to directly access pages from the 'pages' folder, i.e., the ones that are not generated using the createPages API is also fine. 

So, to reiterate, the error only occurs for:

- pages generated using the createPages API
- when I try to access the URL for them (e.g. .../homepage/generated/1/index.html) directly, rather than navigate to them from a link on the homepage.

I'm assuming that the file contents are not really relevant to this issue, so I'm not sharing them here.

**Comment by KyleAMathews** [comment]
It sounds like your page just wasn't created. Perhaps a bug in your code when creating pages. If a page exists, you'd be able to visit it. You can query the pages that are created in graphiql by running a query like `allSitePages { edges { node { path }}}`.

Good luck!

**Comment by KyleAMathews** [comment]
Or you're not actually visiting the page you created.
