### ISSUE TITLE
Gatsby Link go back

### ISSUE THREAD

**Issue by bogdancss** [gatsbyjs/gatsby#5987]
I am trying to add a back button with the Gatsby Link - is there a way to do this?

**Comment by fmmricardo** [comment]
Hi @b0gd4n, I think this might help you.
Using Links from gatsby, you can try this : 
`
import React from 'react';
import Link from 'gatsby-link';

export default () => {
  return (
    <div>
      <Link to="/about">
                <ButtonPrimary>About</ButtonPrimary>
              </Link>
   </div>
 )
}
`
Consider this is happen on the pages/indes.js .

**Comment by maecapozzi** [comment]
@b0gd4n, I think the reason that you're having trouble creating a back button is because `@reach/router` does not include this, the way that `react-router` used to. 

That feature has not yet been implemented in `@reach/router`, but an issue is open for it: https://github.com/reach/router/issues/44

**Comment by crutchcorn** [comment]
reach/router#44 has been implemented

**Comment by decimoseptimo** [comment]
This should be re-opened.

**Comment by Pranav2612000** [comment]
How do we use it now?

**Comment by bogdancss** [comment]
You can use reach router navigate:

`import { navigate } from '@gatsbyjs/reach-router'`
`navigate(-1)`

That should do the trick
