### ISSUE TITLE
gatsby-plugin-netlify-cms: Usage with gatsby-image?

### ISSUE THREAD

**Issue by peterlazzarino** [gatsbyjs/gatsby#5990]
I have been building out a site with gatsby, netlify-cms and would really love to be able to leverage gatsby-image. It seems that since the image URLs need to be known when writing the query and the nature of my CMS data is that its dynamic at compile, I won't be able to set this up. I was wondering if there is any way to query for the childImageSharp resoutions shown in the gatsby-image example in a page level query referencing a fields URL value and then getting the image resolutions from that.

As a followup, is there any way to manually say what I would like my resolutions will be and just pass those to the Img component?

**Comment by peterlazzarino** [comment]
Sorry about this, ended up finding wheat I was looking for in a past issue.

**Comment by SaintEmbers** [comment]
@peterlazzarino were you able to implement this?

**Comment by peterlazzarino** [comment]
@SaintEmbers IO

**Comment by peterlazzarino** [comment]
@SaintEmbers I wasn't. I am reopening because there doesn't seem to be a consensus way to access netlify uploaded images using gatsby graphQL queries. I'm not sure if this should be opened on the netlify CMS repo or not. I did a lot of running around today trying out examples that didn't work out.

**Comment by m-allanson** [comment]
@peterlazzarino are you able to add links to the past issues that talk about handling this?

**Comment by peterlazzarino** [comment]
@m-allanson sure, here's what I could find on the issue.

https://github.com/netlify/netlify-cms/issues/843
https://github.com/gatsbyjs/gatsby/issues/4753
https://github.com/netlify/netlify-cms/issues/325
https://github.com/AustinGreen/gatsby-starter-netlify-cms/issues/7
https://github.com/netlify/netlify-cms/issues/325#issuecomment-354514547

**Comment by hennessyevan** [comment]
@peterlazzarino This has worked for me for the last couple of builds https://github.com/danielmahon/gatsby-remark-relative-images

You need to make sure you read the whole readme very carefully because every placement is important.

**Comment by peterlazzarino** [comment]
@hennessyevan I am not trying to use images uploaded in markdown, sorry I should have clarified. I am trying to use images I have uploaded using the image widget in the netlify CMS which are uploaded to the media folder of the project.

**Comment by hennessyevan** [comment]
@peterlazzarino this should still work for that AFAIK, you just need to source that folder and pass the name to relative-images. The relative-images plugin just fixes some incongruences with gatsby-image and netlifyCMS after that you should be able to run gatsby-image graphql fragments on any image in your media-folder.

```js
{
  resolve: "gatsby-source-filesystem",
  options: {
    path: `${__dirname}/static/mediafolder/`, //path to your media-folder
    name: "media"
  }
},
{
  resolve: "gatsby-transformer-remark",
  options: {
    plugins: [
      {
        resolve: `gatsby-remark-relative-images`,
        options: {
          name: "media" // Must match the source name ^
        }
      },
      {
        resolve: `gatsby-remark-images`,
        options: {	}
        }
    ]
  }
}
```

After setting this up you can run a query on `allImageSharp` filtering for some parameter

```graphql
query getResolutionsByID {
  allImageSharp(filter: {id: {eq: "imageID"}}) {
    edges {
      node {
        id
        resolutions {
          base64
          srcSet
        }
      }
    }
  }
}
```

I may be wrong about this but @danielmahon would be able to let you know if this is indeed in the scope of this plugin. ¯\_(ツ)_/¯

**Comment by peterlazzarino** [comment]
@hennessyevan based on that approach and what I'm trying to accomplish I don't think it's doable with that solution.

I have a page with frontmatter like {
  logo
  etc...
}

where logo could be any file. I can't hardcode that since the imageID depends on the upload and from what I understand my image component can't receive the image id as a prop to pass to the query.

What I would like to and what I saw as an example in other issues would be a graphQL Query that includes this


```
            logo {
              childImageSharp {
                responsiveSizes(quality: 50, cropFocus: CENTER, toFormat: JPG) {
                  src
                  srcSet
                  sizes
                  base64
                }
              }
            }
```

With the example you sent over I get the error. Field "logo" must not have a selection since type "String" has no subfields. This what I've been wrestling with the last few days after trying to configure this correctly.

**Comment by hennessyevan** [comment]
Logo would be added from the netlifyCMS image-widget right? So it would be pointing to some image file, (although not in the `absolute` format remark-images wants). This still seems like the right use-case.

If graphql is giving you that message that could mean that we'll need to make sure everything is configured right.

Can you send your gatsby-config.js and gatsby-node.js?

**Comment by peterlazzarino** [comment]
Also if it helps I can fork my private repo strip out most of the content so it can be cloned / tested.

**Comment by ambethia** [comment]
I've been really struggling with a solution for this same issue for a few days now, if anyone has one.

**Comment by ambethia** [comment]
@danielmahon Oh great!, I ended up converting the path manually and adding it as a field in `gatsby-node.js`, but I think yours might be a better option, thanks! I will try it out.

**Comment by kennedyrose** [comment]
@danielmahon Unfortunately it didn't work for me. I could be wrong, but it looks like [this function](https://github.com/danielmahon/gatsby-remark-relative-images/blob/master/src/index.js#L134) is only backing out once so it will only work if your markdown files are in a directory 1 step in front of the absolute path. That's just my guess though.

**Comment by kakadiadarpan** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub issues, we have to clean some of the old issues as many of them have already been resolved with the latest updates.

Please make sure to update to the latest Gatsby version and check if that solves the issue. Let us know if that works for you by adding a comment 👍

**Comment by peterlazzarino** [comment]
Updating did not solve the issue for me. I am still using a hack to make this work with Netlify CMS but it works nonetheless.

**Comment by kennedyrose** [comment]
I wound up writing a plugin to help with this but it might not be suitable for all use cases.

https://www.npmjs.com/package/gatsby-plugin-netlify-cms-paths

**Comment by kakadiadarpan** [comment]
@peterlazzarino can you try plugins provided by @danielmahon or @kennedyrose?

**Comment by andrejarboe** [comment]
> Updating did not solve the issue for me. I am still using a hack to make this work with Netlify CMS but it works nonetheless.

What is your solution and what brakes it?

**Comment by stlk** [comment]
I was having a hard time setting up Netlify CMS with `gatsby-remark-images`. I described the process on my [blog](https://blog.rousek.name/2018/08/10/cool-image-loading-with-gatsbyjs-v2-and-netlify-cms-v2/). @pieh suggested that I could describe the solution in [gatsby-plugin-netlify-cms/README.md](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-netlify-cms/README.md). What do you think @erquhart?

**Comment by jonathanphz** [comment]
Hi @stlk - tried your blog post but still getting `"Field \"thumbnail\" must not have a selection since type \"String\" has no subfields."`

**Comment by stlk** [comment]
Hi @jonathanphz, do you have a public repo I could check?

**Comment by erquhart** [comment]
@stlk a PR with a quick blurb in the main cms plugin readme would be welcomed, glad you found a working solution!

**Comment by raulrpearson** [comment]
@stlk, [your post](https://blog.rousek.name/2018/08/10/cool-image-loading-with-gatsbyjs-v2-and-netlify-cms-v2/) was very helpful but I was missing one piece: telling [gatsby-source-filesystem](https://www.gatsbyjs.org/packages/gatsby-source-filesystem/) about my NetlifyCMS image folder (as @hennessyevan mentioned at the top of this thread):

```javascript
{
  resolve: "gatsby-source-filesystem",
  options: {
    path: `${__dirname}/static/mediafolder/`, //path to your media-folder
    name: "media"
  }
},
```

@jonathanphz, could this be the reason why it's not working for you?

**Comment by kinduff** [comment]
Took me around 2 days to finally find a solution of what was going on (and I still don't know) but I got it working in my application.

My app is a fresh install of gatsby and I'm manually adding the plugins, including NetlifyCMS. Any of the solutions will always return me this error:

```json
{
  "errors": [
    {
      "message": "Field \"image\" must not have a selection since type \"String\" has no subfields.",
      "locations": [
        {
          "line": 9,
          "column": 17
        }
      ]
    }
  ]
}
```

**What I did** was to include my media folder as recommended by @raulrpearson but with a twist: Media folder should be included before the other content.

My application is very simple, it has a `content` folder with markdown that comes from Netlify. Here's my `gatsby-config.js`:

```javascript
module.exports = {
  plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/static/assets`,
        name: 'assets',
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/content`,
        name: 'content',
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-relative-images`,
            options: {
              name: 'assets'
            }
          },
          {
            resolve: `gatsby-remark-images`,
            options: {},
          },
        ],
      },
    },
    `gatsby-plugin-netlify-cms`,
  ],
}

```

And my `gatsby-node.js` includes this per recommendation from the `gatsby-remark-relative-images` package:

```javascript
exports.onCreateNode = ({ node, actions, getNode }) => {
  fmImagesToRelative(node)
}
```

This configuration above allowed me to query this:

```graphql
{
  allMarkdownRemark {
    edges {
      node {
        frontmatter {
          image {
            childImageSharp {
              fluid(maxWidth: 200) {
                src
              }
            }
          }
        }	
      }
    }
  }
}
```

And it returns

```json
{
  "data": {
    "allMarkdownRemark": {
      "edges": [
        {
          "node": {
            "frontmatter": {
              "image": {
                "childImageSharp": {
                  "fluid": {
                    "src": "/static/dqoq1idu4aag5k1-3d94dd633c52b449121ca8c7e1e754f2-25b9c.jpg"
                  }
                }
              },
            }
          }
        }
      ]
    }
  }
}
```

Posting this so anyone can benefit from the solution since it's not intuitive nor well documented at all.

**Comment by kinduff** [comment]
@peterlazzarino I submitted a PR. If the documented solution works for all, this issue should be closed now.

**Comment by peterlazzarino** [comment]
@kinduff I had a different solution to this in place and attempted to switch to yours without any luck. I might be doing something wrong here but here's my setup.

```gatsby-config```
```javascript
module.exports = {
	siteMetadata: {
		title: "Student Mentorship & College Admissions Consulting | CollegeVine",
		siteUrl: "https://www.collegevine.com",
		description: "CollegeVine is a mentorship, test prep, and admissions advisory firm comprised of consultants from top US universities powered by data-driven technology."
	},
	plugins: [
		{
			resolve: "gatsby-source-filesystem",
			options: {
				path: `${__dirname}/static/img`,
				name: "media"
			}
		},
		"gatsby-plugin-react-helmet",
		"gatsby-plugin-sass",
		{
			resolve: "gatsby-source-filesystem",
			options: {
				path: `${__dirname}/src/pages`,
				name: "pages"
			}
		},
		{
			resolve: "gatsby-source-filesystem",
			options: {
				path: `${__dirname}/src/content`,
				name: "layout"
			}
		},
		"gatsby-plugin-styled-components",
		"gatsby-transformer-sharp",
		"gatsby-plugin-sharp",
		{
			resolve: "gatsby-transformer-remark",
			options: {
				plugins: [
					{
						resolve: "gatsby-remark-images",
						options: {
							maxWidth: 2000
						}
					},
					{
						resolve: `gatsby-remark-relative-images`,
						options: {
							name: "media"
						}
					},
					{
						resolve: "gatsby-remark-external-links",
						options: {
							target: "_blank",
							rel: "noopener noreferrer"
						}
					}
				]
			}
		},
		{
			resolve: "gatsby-plugin-netlify-cms",
			options: {
				modulePath: `${__dirname}/src/cms/cms.js`
			}
		},
		"gatsby-plugin-netlify" // make sure to keep it last in the array
	]
};
```

Snippet from a now failing query

```javascript

			<StaticQuery
				query={graphql` 
					query LayoutQuery {
						markdownRemark(fields: { slug: { eq: "/layout/" } }) {
							id
							frontmatter {
								logo {
									childImageSharp {
										fixed(width: 173) {
											...GatsbyImageSharpFixed
										}
									}
								}
```

I get an error at the query above 

```
GraphQL Error Field "logo" must not have a selection since type "String" has no subfields.

file: /.../layout.js
```

Screen shot showing my folder structure 

![screen shot 2018-11-13 at 10 29 58 am](https://user-images.githubusercontent.com/2364849/48423690-182ece80-e72f-11e8-966e-43fcc1cc6c24.png)

The admittedly not pretty gatsby-node code that works when I remove the examples above

```javascript

exports.onCreateNode = ({ node, actions, getNode }) => {
	const { createNodeField } = actions;
	if (node.internal.type === "MarkdownRemark") {
		deepMap(node.frontmatter, (value) => {
			let newPath = value;
			if (typeof value === "string" && path.isAbsolute(value) && value.indexOf("/img/") !== -1) {
				const mdPath = node.fileAbsolutePath;
				const depth = mdPath.split("src/")[1].split("/");
				newPath = path.join(`${depth.map(() => "../").join("")}`, "static", value);
			}
			return newPath;
		}, {
			inPlace: true
		});
	}
};

```

**Comment by jonathanphz** [comment]
@peterlazzarino you might be missing this part: https://github.com/danielmahon/gatsby-remark-relative-images#to-convert-frontmatter-images

```
// gatsby-node.js
const { fmImagesToRelative } = require('gatsby-remark-relative-images');

exports.onCreateNode = ({ node }) => {
  fmImagesToRelative(node);
};
```

**Comment by peterlazzarino** [comment]
ah yep that was it! Thanks, closing

**Comment by jonathanphz** [comment]
Hi @kinduff - is there documentation for`name` in:

```
{
     resolve: `gatsby-remark-relative-images`,
      options: {
           name: 'assets'
       }
}
```

I'm trying to figure something out and can't find it anywhere.

I'm using Netlify CMS and I set up the images folder to be `uploads` using `public_folder: uploads` (config.yml for CMS) but now that I have this working correctly I see that I have an `uploads` folder and a `static` folder basically duplicating all the images inside `public`.

**Comment by peterlazzarino** [comment]
@jonathanphz the name should match a corresponding entry for gatsby-source-filesystem AFAIK

```javascript
		{
			resolve: "gatsby-source-filesystem",
			options: {
				path: `${__dirname}/static/img`,
				name: "media"
			}
		}
```

In my site the "media" named folder is referenced above, for gatsby-remark-relative-images as "media" and then in my config.yml I have the following

```
media_folder: static/img
public_folder: img
```

**Comment by jonathanphz** [comment]
@peterlazzarino yeah that's what I think but could not find documentation on using 'name' in `options: {}`

So on your public directory do you have an `img` directory and a `static` directory which both have the same images? 

Right now the generated images are being placed in both for me - creating lots of duplicating image files.

**Comment by danielmahon** [comment]
@jonathanphz @peterlazzarino The `options.name` config was removed in the latest version (which supports Gatsby v2), so you shouldnt need to worry about it anymore. The plugin will resolve all relative links from `gatsby-source-filesystem`. Just need:
```
{
     resolve: `gatsby-remark-relative-images`,
}
```

If you have issues or feature request please feel free to open an issue on https://github.com/danielmahon/gatsby-remark-relative-images

**Comment by peterlazzarino** [comment]
@jonathanphz my images only end up in the static/img folder. Not sure how they'd end up in both, is the CMS inserting them in both places on publish?

**Comment by jonathanphz** [comment]
@peterlazzarino When I run `gatsby develop` a `public` folder is generated. Inside that `public` folder I see the `img` folder but also a `static` folder - they share most of the images. This only started happening after I configured `gatsby-image`.

Not sure how it's happening but the images on the front end are coming from the static folder.

**Comment by erquhart** [comment]
Netlify CMS only commits images to one destination, whatever path you've set as `media_folder` in your CMS config.yml. You can check the commits created by Netlify CMS in your repo to confirm this.

**Comment by jonathanphz** [comment]
Actually false alarm - this is still happening. Is not happening on publish. It's when I `gatsby develop`. The generated `public` folder contains images in `static` as well as `uploads`. Seems all the images in `uploads` are also in `static`. Currently debugging this.
![gatsby-config_js_ _cliniko-website](https://user-images.githubusercontent.com/1545577/48501670-7a193200-e81c-11e8-901a-80c689fcb552.jpg)

**Comment by cmmartti** [comment]
@kinduff Unfortunately, I can't replicate your success. I tried following your steps exactly. I created the `src/content` and `static/assets` folders and added a markdown file with frontmatter that links to an image in the assets folder, but when I try to run this same sample query in GraphiQL:

```
{
  allMarkdownRemark {
    edges {
      node {
        frontmatter {
          image {
            childImageSharp {
              fluid(maxWidth: 200) {
                src
              }
            }
          }
        }	
      }
    }
  }
}
```
, I still get the same `Field "image" must not have a selection since type "String" has no subfields.` error. If I query for just `image` directly I get the string that was set in the frontmatter.

I've created a repo with my attempt [here](https://github.com/cmmartti/gatsby-image-from-frontmatter). Does anybody know why it doesn't work?

**Comment by jonathanphz** [comment]
@cmmartti did you tried this: https://github.com/gatsbyjs/gatsby/issues/5990#issuecomment-438315682 ??

**Comment by cmmartti** [comment]
@jonathanphz [Yes I have](https://github.com/cmmartti/gatsby-image-from-frontmatter/blob/master/gatsby-node.js), that's why I'm so confused. Maybe I'm using different library version(s) that are not compatible? I don't what else it could be.

**Comment by kinduff** [comment]
@cmmartti I just cloned and ran your repo and I'm able to query 

![screenshot from 2018-11-20 19-08-33](https://user-images.githubusercontent.com/1270156/48805988-b6a2cd00-ecf7-11e8-835c-1bbf43a3e64d.png)

Try cleaning up your app (.cache, public and node_modules) and run `npm install` again. I didn't update, I just cloned, installed and ran `gatsby develop`. Here's the generated `package-lock.json` https://gist.github.com/kinduff/4def00df2ea189c578caaacaedef791f

**Comment by Coder2012** [comment]
@kinduff @cmmartti 

I have also tried your example - cloned, installed and ran `gatsby develop` but met the same issue as you...

![image](https://user-images.githubusercontent.com/1157627/48842720-e4862100-ed8c-11e8-8480-40919aa22571.png)

Would it be possible to compare environments?

OS: Windows 10
Node: v11.1.0
NPM: v6.4.1

**Comment by peterlazzarino** [comment]
@Coder2012 can you link to your package.json like @kinduff did?

**Comment by Coder2012** [comment]
> @Coder2012 can you link to your package.json like @kinduff did?

@peterlazzarino  I believe @kinduff posted his `package-lock.json` rather than his `package.json`.

As requested - [package-lock.json](https://gist.github.com/Coder2012/dfa82c0f0b430beeaff51cabe7c06b3c)

**Comment by peterlazzarino** [comment]
sorry @Coder2012 that's what I meant :) Seems they are identical, I can test this on my windows machine later to try to verify this as well

**Comment by kinduff** [comment]
Posting sys information of the working example above. Hope this is not an OS issue.

```
OS: Linux 4.14.80-1-MANJARO x86_64 GNU/Linux
NPM: 6.4.1
Node: 8.9.0
```

**Comment by peterlazzarino** [comment]
I will try your example on my windows machine later this afternoon. I will also try the solution i have used in the past which doesn't depend on the gatsby-remark-relative-images plugin to try and narrow down where it might be happening.

**Comment by Coder2012** [comment]
@peterlazzarino @kinduff

I have just tested the example by @cmmartti using Windows Subsystem Linux -  Ubuntu on Windows 10 Enterprise and it works for me.

Given this is a Linux environment I do believe it's pointing more toward a Windows OS issue.

![image](https://user-images.githubusercontent.com/1157627/48950521-539d7a00-ef33-11e8-9b4f-9e910d16d79f.png)

**Comment by peterlazzarino** [comment]
@cmmartti @Coder2012 @kinduff 

I cloned the repo and tested

**Comment by peterlazzarino** [comment]
@Coder2012 @cmmartti @kinduff 

Now that we know its reproducible on windows only I decided to try a solution based on one I use in a project after I was not able to get gatsby-remark-relative-images working (maybe it's because I was building it on windows 😄.

My fork that works on windows is [here](https://github.com/peterlazzarino/gatsby-image-from-frontmatter)

my only change was removing the gatsby-remark-relative transform from gatsby-node and implementing my own, admittedly crude solution. This (IMO) isolates the break to gatsby-remark-relative-images and I will be adding an issue there.

**Comment by delster** [comment]
Also fails for me on Win10 / Node 10.6.0 / npm 6.1.0 and I'm new to GatsbyJS/Netlify CMS but am willing to test if someone can give me specific directions.

**Comment by danielmahon** [comment]
I will try to take a look at this today or this weekend.  My gut says it’s a windows path issue and probably a quick fix once I find the offending line.

**Comment by Coder2012** [comment]
Latest **0.2.1** of the *gatsby-remark-relative-images* plugin is working fine for me now on Windows 10 guys. Thank you.

**Comment by peterlazzarino** [comment]
Woo thanks everyone 👍

**Comment by danielmahon** [comment]
As stated the latest version **0.2.1** of [gatsby-remark-relative-images](https://github.com/danielmahon/gatsby-remark-relative-images) should fix windows support. Thanks @haroldhues and @peterlazzarino for the fix and testing ;)

**Comment by erquhart** [comment]
Relative image path support is now in beta as of Netlify CMS 2.9.8-beta.2 - try it out:

```
npm update netlify-cms-app@beta
```

Then add `media_folder_relative: true` to your Netlify CMS config.

[Docs here](https://www.netlifycms.org/docs/beta-features/#relative-image-paths).

**Comment by 0xsven** [comment]
https://github.com/gatsbyjs/gatsby/issues/5990#issuecomment-433664162

This worked for me with one change: my content folder could not have any sub folders. all `.md` files need to be in a flat folder.

**Comment by davepaiva** [comment]
I followed all the above suggestions plus this blog was the final nail in the coffin regarding this issue
https://theleakycauldronblog.com/blog/problems-with-gatsby-image-and-their-workarounds/

**Comment by MartinSchere** [comment]
I'm having this problem _only_ in the build process, which is extreamly weird. If anyone is kind enough to take a look at it I would greatly appreciate it:

https://github.com/MartinSchere/gatsby-test-ts.git

**Comment by AlmogRnD** [comment]
Is there an official way to do this would like to do this for my blog, if there is a way please tell me about a cup of coffee on me

**Comment by miguelt1** [comment]
I subscribe, I'm having the same problem!

**Comment by yasintze** [comment]
This issue is still happening on Gatsby v4, any solution?

**Comment by ricovitch** [comment]
Having struggled with using netlifycms and gatsby together for managing markown image paths.
Finally found that you can now configure netlifycms collections to use a relative paths for images : https://www.netlifycms.org/docs/beta-features/#folder-collections-media-and-public-folder

Solution for my use case has been to use this configuration for collections with images
```
    media_folder: ''
    public_folder: ''
```

The downside maybe is that you cannot reuse images in different collections easily, but I did not need that.
