### ISSUE TITLE
exact & strict options for createPage

### ISSUE THREAD

**Issue by kukoba** [gatsbyjs/gatsby#5992]
Hi guys,

In client-side possible to configure route (please note for `exact` prop):

```
  <Switch>
    <Route
      exact
      path="/instruments/:symbol/"
      render={routeProps => <InstrumentPage  {...routeProps}/>
      )}
    />
    <Route
      render={() => <Redirect to={{ pathname: '/404.html' }} />}
    />
  </Switch>
```

Almost the same logic could be implemented by a plugin and createPages hook:

```
    instruments.forEach(instrument => {
      createPage({
        path: '/instruments',
        component: templateFilePath,
        matchPath: 'instruments/' + instrument,
        exact: true, //<---- seems that this option does not work
        context: {...},
      });
    });
```

The code above will create one physical page which will process all paths like '/instruments/<instrument>'
under the hood (as I understand) gatsby will creat one index.html in 'instruments' folder which has configured routes for all 'instruments'

So, the questions are: 
1. am I right about general logic?
2. how can I specify 'exact' and 'strict' properties of react router in my plugin (by using createPage function) And is it possible at all?

**Comment by KyleAMathews** [comment]
Pages created by `createPage` are "exact" by default. You should only use `matchPath` for client side sections of the site. Check out the docs page on this https://www.gatsbyjs.org/docs/building-apps-with-gatsby/
