### ISSUE TITLE
SSR is broken with styled-components

### ISSUE THREAD

**Issue by mquandalle** [gatsbyjs/gatsby#5993]
When using the Gatsby styled-component plugin, the layout is currently broken if the very first re-hydration doesn't match perfectly the SSR version — instead of having a small flash and a client rendering as it does without this plugin.

I created a minimal reproduction at https://github.com/mquandalle/repro-gatsby-issue-5993

This should be fixable with the `ssr` option of the babel plugin for styled-components: https://www.styled-components.com/docs/tooling#serverside-rendering

**Comment by KyleAMathews** [comment]
[Seems you're right that we need to activate SSR during the JS build as well](https://github.com/gatsbyjs/gatsby/issues/5861#issuecomment-397870514). Could you create a PR for that?

**Comment by mquandalle** [comment]
I haven't actually tested that yet but I will do it and do a PR if it works.

**Comment by jckw** [comment]
Any solution for this yet?

**Comment by iDVB** [comment]
Seems like this is still an issue? 
https://github.com/styled-components/styled-components/issues/2629#issuecomment-561318866
