### ISSUE TITLE
Not able to deploy to Netflify when I add mdbootstrap (material design) 

### ISSUE THREAD

**Issue by mattdvhope** [gatsbyjs/gatsby#5994]
## Description
I'm attempting add [Material Design for Bootstrap](https://mdbootstrap.com/react/) to my Gatsby app.

When I `yarn add mdbreact` (or mdbootstrap) to my Gatsby app, it works fine in development mode, but when attempt to deploy it to Netlify, the deployment fails.

Apparently there is a conflict in webpack with the `babel-loader`.  

### Steps to reproduce

1. I install it:  `yarn add mdbreact` (or mdbootstrap)
2. I get the following error when I run `gatsby develop`:   `error There was an error compiling the html.js component for the development server. ...WebpackError`
3. I remove the `node_modules` folder and then re-install it (`npm install`).
4. When I run `gatsby develop` again (or `gatsby build`), it works.
5. Then in `index.js`, I add...
```javascript
import 'font-awesome/css/font-awesome.min.css';
import 'bootstrap/dist/css/bootstrap.min.css'; 
import 'mdbreact/dist/css/mdb.css';
```
...and the bootstrap styling works fine in my local development environment.
6. Then, when I `git push origin` (which Netlify uses to automatically re-deploy the app), I get following error in my Netlify Deploy log:

```javascript
Error: ./~/babel-loader/lib?{"plugins":["/opt/build/repo/~/gatsby/dist/utils/b abel-plugin-extract-graphql.js","/opt/build/repo/~/babel-plugin-add-module-exp orts/lib/index.js","/opt/build/repo/~/babel-plugin-transform-object-assign/lib /index.js"],"presets":[["/opt/build/repo/~/babel-preset-env/lib/index.js",{"lo ose":true,"uglify":true,"modules":"commonjs","targets":{"browsers":["> 1%","la st 2 versions","IE >= 9"]},"exclude":["transform-regenerator","transform-es201 5-typeof-symbol"]}],"/opt/build/repo/~/babel-preset-stage-0/lib/index.js","/op t/build/repo/~/babel-preset-react/lib/index.js"],"cacheDirectory":true}!./src/ 
```

### Expected result

I wanted the app to deploy normally, but I got the error mentioned above instead.

Here is my `package.json` file:

```javascript
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "gatsby": "^1.9.247",
    "gatsby-link": "^1.6.40",
    "gatsby-plugin-react-helmet": "^2.0.10",
    "gatsby-source-contentful": "^1.3.53",
    "gatsby-transformer-remark": "^1.7.44",
    "mdbreact": "^4.5.0",
    "react-helmet": "^5.2.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write 'src/**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "prettier": "^1.12.0"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  }
}
```

Any help on this would be much appreciated.  I think adding Material Design Bootstrap to Gatsby would be a great combination!

**Comment by KyleAMathews** [comment]
Does it build locally? If you remove your changes, does the site build?

**Comment by mattdvhope** [comment]
Sorry for the delay..  Yes it does build locally, but only after I have deleted and re-installed `node_modules.js`.  But once I deploy to Netlify, I get the error mentioned above in the Netlify Deploy log.  I wonder if it might be a Netlify-specific problem.

**Comment by pieh** [comment]
@mattdvhope Try to trigger deploy and check "Clear build cache" in popup (netlify will cache dependencies and restore them for subsequent builds)

**Comment by mattdvhope** [comment]
In my local environment, I deleted the `.cache` and `public` folders and then did `gatsby develop` with no problem.  Then, when I triggered a deploy in Netlify and checked "Clear build cache," I got a different Webpack error: `WebpackError: The style-loader cannot be used in a non-browser environment`.

**Comment by KyleAMathews** [comment]
Perhaps try deleting your lock file? I'm going to close this as it doesn't sound like a Gatsby bug. It's sometimes helpful to try building your site in Linux as well since that's what netlify uses. They have a docker container which you can use to test building locally in Linux.
