### ISSUE TITLE
Support custom SVG link icon for gatsby-remark-autolink-headers

### ISSUE THREAD

**Issue by brandonkal** [gatsbyjs/gatsby#5999]
## Summary

Please add the ability to set a custom SVG for autolink headers. I would like to use a different link icon than the generic GitHub clone.

It also seems a bit redundant to repeat the SVG code on every single heading. Setting it as a <symbol> and then making use of <use> would result in less repetition.

**Comment by brandonkal** [comment]
I now see there is a PR for this #5961

**Comment by LeKoArts** [comment]
@brandonkal The PR is merged and available at `gatsby-remark-autolink-headers@2.0.0-beta.2`
