### ISSUE TITLE
Add deploy-gh-pages command which builds site and publishes to Github Pages

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#6]
UPDATE: We'll be using https://www.npmjs.com/package/gh-pages

**Comment by KyleAMathews** [comment]
Algorithm is:

1. Clone site to tmp directory
2. Create orphan `gh-pages` branch (if one doesn't already exist)
3. meanwhile, build site to another tmp directory (or just public directory?)
4. cp new build to cloned site
5. Commit and push (just use a generic commit message?)

Orphan branches have their own history.

Using a cloned git repo avoids having to switch to the `gh-pages` branch on the main repo which deletes all files/directories not under git (e.g. `node_modules`).

**Comment by KyleAMathews** [comment]
Need to auto-prefix links with name of repo. Need way to disable this in config so people pointing a domain at github site can disable this.

**Comment by KyleAMathews** [comment]
Or probably the simplest way to do this is to put the prefix value in the config. Check if the config key is there, if not, ask for it.

**Comment by gesposito** [comment]
Found this
https://github.com/felixge/node-romulus/blob/master/lib/deploySite.js
author could be pinged for contribution, or better

https://github.com/koistya/git-push
external module

**Comment by KyleAMathews** [comment]
Oh nice finds! Yeah, the node-romulus script looks almost perfect. We could copy that pretty easily and tweak it to our needs.

**Comment by gesposito** [comment]
Also:
https://github.com/lukekarrys/git-directory-deploy
that would be as easy as:
`
"scripts": {
    "deploy": "git-directory-deploy --directory _dist --branch gh-pages"
}
`

**Comment by kennethormandy** [comment]
@KyleAMathews Hey! Really nice work on this project so far, I am looking forward to giving it a more thorough try.

Would you be interested in a pull request that adds [Surge](https://surge.sh) as the deployment tool? Surge can be installed as a `devDependency` with npm, so Gatsby sites could be published with one command:

```sh
npm install --save-dev surge
surge ./public my-gatsby-blog.surge.sh
```

This is what React projects [Spectacle](https://github.com/FormidableLabs/spectacle) and  [hjs-webpack](https://github.com/henrikjoreteg/hjs-webpack) do.

You can also use [custom domains](https://surge.sh/help/adding-a-custom-domain) for free, and [catch-all URLs](https://surge.sh/help/adding-a-200-page-for-client-side-routing) for client-side routing with React. Let me know what you think! Either way, excited to see more React + static stuff out there.

**Comment by KyleAMathews** [comment]
@kennethormandy hey adding support for Surge would be great!

I'm actually speccing out a plugin system for Gatsby right now. Surge would be a great "publish" plugin. There could be a number of these like publishing to Surge, Amazon S3, Github, etc.

So to publish to Surge, the cli command would be something like `gatsby build --publish surge`. Within your Gatsby config file, there'd probably be a `surge` key with your Surge auth and other details.

Could you create a quick issue about supporting Surge and other publish plugins to keep track of this?

**Comment by matteodem** [comment]
+1 for this. 

Also was interested if there's any docs on how to use gatsby for github pages. I used the documentation starter and am about to try this out. Any hint into the right direction would be helpful.

**Comment by KyleAMathews** [comment]
This issue is about automating publishing to github pages. It's pretty easy to do manually in the meantime.

Steps are:

1. Build your Gatsby site.
2. Copy files from public into another directory e.g. `/tmp/my-site/`
3. [The first time doing this] create the `gh-pages` branch https://help.github.com/articles/creating-project-pages-manually/
4. Switch to the `gh-pages` branch. Copy back your built site.
5. Add files, commit, and push.

**Comment by matteodem** [comment]
perfect, thanks!

**Comment by matteodem** [comment]
I just tried this and the steps do not work, as the starter template generates absolute link paths. See http://matteodem.github.io/meteor-easy-search/

**Comment by kennethormandy** [comment]
@matteodem I’m hoping I’m able to work on a built-in deployment integration using Surge per #52, but if you want to try that as an alternative in the meantime:

```sh
npm install -g surge
surge ./path/to/gatsby-build
```

This will prompt you to create an account and publish for free. You could also save Surge as a `devDependency` and add it as a run script for your `package.json`, even [on every push](https://surge.sh/help/integrating-with-travis-ci) like with GitHub Pages if you want (but without all the branch switching).

**Comment by matteodem** [comment]
oh, that looks great thanks! I'll have a look this weekend.

**Comment by KyleAMathews** [comment]
Yeah... it's a bit hacky right now getting URLs to work. I think the right solution is to have a `link` function for which you can set a link prefix in your config so when you build for Github all the links turn out right.

**Comment by KyleAMathews** [comment]
And surge is definitely the easy solution for now :)

**Comment by KyleAMathews** [comment]
LOL, actually my former self agrees with my current self. I already added that link function https://github.com/gatsbyjs/gatsby/blob/852ae4bced514558743d0e584484639c0289a9fa/lib/isomorphic/gatsby-helpers.js#L6-L14

**Comment by KyleAMathews** [comment]
@matteodem the 0.7 release I did earlier improved the support for gh-pages a ton. You should be able to create a new docs or blog site and push it to github pages and it'll work.

See the release notes https://github.com/gatsbyjs/gatsby/releases/tag/v0.7.0

**Comment by KyleAMathews** [comment]
Somehow I missed this npm package when looking around before https://www.npmjs.com/package/gh-pages. Just tested the global version and it works beautifully.

I'm thinking now we'll just add deploy support for as targets as people want to support. For starters github pages and surge. The commands will be something like `gatsby deploy gh-pages` and `gatsby deploy surge`

One thought is to add deployment as a option for building e.g. `gatsby build --deploy gh-pages`. My problem with this though is I feel it conflates building and deploying too much as often you'll want to build locally just to make sure the built version of the site is working as expected before deploying. Thoughts?

/cc @kennethormandy

**Comment by matteodem** [comment]
thanks for the update will try it out in the next days!

**Comment by kennethormandy** [comment]
@KyleAMathews Since I last updated you on this, we made it possible to build Surge into a CLI easily. Here are the docs right now for [using Surge and Commander together](https://github.com/surge-sh/example-commander).

I think you would still want the build command separate. With Surge, you can run the build step automatically as part of the deployment, and then show an error if necessary if the compilation fails for some reason, and otherwise finish the deploy. We have a more thorough Commander example doing exactly that which I can pass along as well.

**Comment by KyleAMathews** [comment]
:+1: thanks for the link @kennethormandy, the integration looks like it'll be very easy.

**Comment by KyleAMathews** [comment]
I'm going to say deploy plugins are out of scope. It's easy enough to install `gh-pages` and add an npm script which runs `gatsby build` and then `gh-pages`.

**Comment by gesposito** [comment]
Just for reference, I found this useful gist
https://gist.github.com/cobyism/4730490

**Comment by SachaG** [comment]
> It's easy enough to install gh-pages and add an npm script which runs gatsby build and then gh-pages.

Is there any tutorial that provides more info about this? Or maybe it could be added to the documentation?

**Comment by SachaG** [comment]
Oh, looks like that this is already part of the default boilerplate as `npm run deploy`. My bad!

**Comment by KyleAMathews** [comment]
👍😉👊

**Comment by SachaG** [comment]
Actually this isn't quite usable in its current state because it removes the `CNAME` file every time you deploy, thus breaking your custom domain: 

https://github.com/tschaub/gh-pages/issues/74

I'll submit a PR to fix this once gh-pages itself is fixed: 

https://github.com/tschaub/gh-pages/issues/113

**Comment by KyleAMathews** [comment]
Perhaps just copy the CNAME file into public using the postBuild hook?

**Comment by SachaG** [comment]
Hmm, would that work? If I understand things correctly, the `CNAME` file is being removed by `gh-pages`, not by Gatsby itself?

**Comment by KyleAMathews** [comment]
As I understand, gh-pages just copies directly over from the src directory.
So if the CNAME file is in public it'll end up in the gh-pages branch. That
being said, I could be wrong as I haven't tried to solve this issue.

**Comment by SachaG** [comment]
Oh of course! Since the CNAME has to end up at the root of the `gh-pages` branch, I stupidly put it at the root of my `master` branch too. But it should be in `/public`, that makes sense :)

**Comment by andrewdc** [comment]
I just ran into this problem and tried to sum it up. Let me know if this kinda sorta covers the bases?

http://andrewdc.com/ghpages-gatsby-and-domains/

Thanks all for the solutions above!!

**Comment by KyleAMathews** [comment]
@andrewdc looks great! Thanks for writing up your solution!
