### ISSUE TITLE
Needed to run sudo gatsby develop for first time.

### ISSUE THREAD

**Issue by jlandry** [gatsbyjs/gatsby#602]
The first time I installed gatsby globally it error-ed on "gatsby devlelop" stating it did not have permissions to mkdir a couple locations. Finally I ran "sudo gatsby develop" and it worked and subsequent runs did not need sudo. 
so some how the global install of gatsby did not place some files or the non-sudo gatsby develop did not have permissions to make files?

**Comment by KyleAMathews** [comment]
This sounds like an NPM permissions problem of some sort. Perhaps one of the following links will help?

* http://stackoverflow.com/questions/16151018/npm-throws-error-without-sudo
* https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md
* https://docs.npmjs.com/getting-started/fixing-npm-permissions
