### ISSUE TITLE
Unify bots used in the repo

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#6021]
## Summary

There are several bots used to automate different parts of the repo. Unify them into one single bot - [`gatsbot`](https://github.com/gatsbyjs/peril-gatsbyjs) - which is managed by [Gatsby's Peril setup](https://github.com/gatsbyjs/peril-gatsbyjs).

### Basic example

Existing bots are:

- [stale bot](https://github.com/gatsbyjs/gatsby/issues/1074#issuecomment-352107722) - currently disabled?
- [gatsbybot](https://github.com/gatsbyjs/gatsby/pull/6017#issuecomment-398394699) - comments when deploy previews are ready
- [gatsbot](https://github.com/gatsbyjs/peril-gatsbyjs/pull/7) - this is the new Peril-backed bot for inviting new contributors to the gatsbyjs org
- @KyleAMathews's account - hooked up to post a comment when deploy previews fail (I don't _think_ he's posting all those links himself 🤖) - [example](https://github.com/gatsbyjs/gatsby/pull/5957#issuecomment-397860047)

### Motivation

Centralise repo automation in one place to make it easier to manage. Provide a more consistent experience to contributors.

**Comment by LekoArts** [comment]
@m-allanson This issue is resolved, right?

**Comment by m-allanson** [comment]
It is!
