### ISSUE TITLE
Require reproducible test cases for bug reports

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#6023]
## Summary

Once repl.it / codesandbox support importing from GitHub, require bug reports to include a reproduction.

### Basic example

This requirement could be automated using [Gatsby's Peril config](https://github.com/gatsbyjs/peril-gatsbyjs).

### Motivation

Validating vague bug reports takes a long time. Requiring repro cases should allow us to fix more bugs in a more timely manner.

**Comment by LeKoArts** [comment]
But would it also be okay to link a repository?

**Comment by KyleAMathews** [comment]
@LeKoArts that's what repl.it/codesandbox will allow. You can push code to github then they'll run your site so all maintainers need to do is to visit the link to see the running site instead of setting it up locally. Check out https://repl.it/languages/gatsbyjs

**Comment by LeKoArts** [comment]
Ah, I see. That's cool!

**Comment by DSchau** [comment]
Marking this `not stale`. I think this is a valuable one that I'd still love to see.

**Comment by wardpeet** [comment]
I'll be closing this in favor of https://github.com/gatsbyjs/gatsby/issues/19482. I feel we can wait a couple of months to get this resolved.
