### ISSUE TITLE
Use gastby with 2 different react dashboard apps

### ISSUE THREAD

**Issue by abhijeet2015** [gatsbyjs/gatsby#6029]
## Summary
I am new to Gastby but I want to use the Gatsby site for my web app's main site ( Marketing site ) and after login on the bases of user role - need to load different react applications.
Lets say for User role - 

- admin
I need to load the react dashboard site like [Material-ui-dashboard](https://demos.creative-tim.com/material-dashboard-react/#/dashboard)

- user
Some form based site like [this](https://demos.creative-tim.com/material-kit-react/#/)

Main reason to do this is because I don't want the user to wait for load of the admin website and vice versa. Is it possible to this ?

Other tried approaches -

1. Express app with different static file directories to render different application on the bases of url. (No success )

2. Different sub domain for both admin and user websites.

**Comment by pieh** [comment]
If you want user/admin apps to be separate "sites" then you could use standard browser location change using `a` links or changing `window.location.href`

If you want those to be part of same Gatsby app then builtin code splitting should do this by default - at least `js` part in gatsby v1. If those UI libs are using straight css (not any css in js flavour) then if this can be split in v1, but v2 will split css by default - so maybe you can try gatsby v2 for that?

**Comment by abhijeet2015** [comment]
@pieh 
Thanks for your quick reply.
But can you explain the first little bit more I am not understanding the whole thing what you want to say.
and I am trying this because I don't want to  build whole dashboard application in gatsby just wanted to build marketing site which will help user render website faster on any type of network.

Sorry for the silly questions.

**Comment by pieh** [comment]
There are no silly questions! :)

How/where do you host your app now? Because solution to this would be some kind of server routing on your hosting and Gatsby itself isn't involved in this.

> 1. Express app with different static file directories to render different application on the bases of url. (No success )
>
> 2. Different sub domain for both admin and user websites.

Those are good approaches. What exactly didn't work for you with those?

**Comment by abhijeet2015** [comment]
Still not hosted my application yet. Just trying approaches before building whole application. 

> 1.  Express app with different static file directories to render different application on the bases of url. (No success )

Basically started by making production builds of gatsby and dashboard apps and put them in different folders for static files but the issue here is that all production build are relative to main path (Got this working by manually changing paths in index.html pages but won't be able to do every time using Continuous integration tools (Jenkins).)

```
app.use('/admin', express.static(path.join(__dirname + 'admin')));
app.get('/admin/*', (req, res) => {
    res.sendFile(path.join(__dirname + '/admin/index.html'));
});

app.use('/dashboard', express.static(path.join(__dirname + 'materialUi')));
app.get('/dashboard/*', (req, res) => {
    res.sendFile(path.join(__dirname + '/dashboard/index.html'))
});


app.use('/gatsby', express.static(path.join(__dirname + '/gatsby')));
app.get('/gatsby/*', (req, res) => {
    res.sendFile(path.join(__dirname + '/gatsby/index.html'));
});
```

> 2. Different sub domain for both admin and user websites.

Got this working but not preferring this because I think it will hinder with progressive web apps. 

_[Same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) imposes restrictions on multi-subdomain PWAs, like not being able to share service worker logic and caches between origins, the need to have a start_url relative to each origin in manifest files._ 

there are [workarounds](https://medium.com/@drenzulli/building-progressive-web-apps-on-multi-subdomain-sites-fbd3384d0706) for pwa but don't want to use them as it will remove the main purpose of the application to give user fluid experience and also don't want users to think that they are being redirected to some advertising website.

**Comment by Jaikant** [comment]
@abhijeet2015 did you look at [client routes](https://www.gatsbyjs.org/packages/gatsby-plugin-create-client-paths/)?
You can have two client routes, one for usr and the other for admin. Just that your react components for usr and admin have to be defined within Gatsby. 

I think you are trying to integrate a CRA or NextJS app into the GatsbyJS flow. I don't think that is possible from within GatsbyJS, just like it isn't possible to integrate GatsbyJS within NextJS or CRA flow. They are separate frameworks, though I see the use case and value in this integration any which way.

**Comment by abhijeet2015** [comment]
@Jaikant That also a way to use it too. but I intend to use gastby with full pledge react application  [Material-ui-dashboard](https://demos.creative-tim.com/material-dashboard-react/#/dashboard) I am not developing whole application in gastby. Just the main marketing site.

Any way decided to go with reverse proxy using aws services.
