### ISSUE TITLE
gatsby-source-wikipedia: License and author attribution is missing 

### ISSUE THREAD

**Issue by bep** [gatsbyjs/gatsby#6033]
As seen in this random example in the demo: https://guess-gatsby-wikipedia-demo.firebaseapp.com/wiki/Lighthouse_of_Alexandria/

I see no indication of which license that text and those photos are published with. I assume they are CC BY SA, which requires attribution.

**Comment by pieh** [comment]
You are right, but this demo isn't maintained here - please create issue in appropriate repository - https://github.com/guess-js/gatsby-guess
