### ISSUE TITLE
The examples on GraphQL Reference are all down

### ISSUE THREAD

**Issue by whs-dot-hk** [gatsbyjs/gatsby#6039]
## Description

Describe the issue that you're seeing.

### Steps to reproduce
Visit https://www.gatsbyjs.org/docs/graphql-reference/

### Expected result

What should happen?

### Actual result

What happened.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by pieh** [comment]
Thanks for report! We already are aware of it and working on it https://github.com/gatsbyjs/gatsby/issues/6015 , so I'll close this as duplicate.
