### ISSUE TITLE
cannot find module fbjs

### ISSUE THREAD

**Issue by chrisco23** [gatsbyjs/gatsby#604]
I ran the gatsby-starter-blog locally without issue.
I pushed to my Digital Ocean droplet (I want to use nginx) and I get this:

```
node render-page.js 
/var/www/mysite.net/public/render-page.js:745
        var warning = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"fbjs/lib/warning\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
                                                                                                                                                                         ^

Error: Cannot find module "fbjs/lib/warning"
```

**Comment by KyleAMathews** [comment]
@chrisco23 which versions of Gatsby + Node.js/NPM?

**Comment by chrisco23** [comment]
Ah I hadn't really thought about npm vers, although I had tried a couple node vers.  Recommendations?

Currently:

dev:
  node 4.5.0
  npm 2.15.19
  gatsby 0.12.24

prod:
  node 6.2.0
  npm 3.8.9
  gatsby 0.12.24

**Comment by KyleAMathews** [comment]
Looking at this again — it's probably that you added a dependency locally but then didn't add it to your package.json so it's not found in production.

Does the error show up if you delete your `node_modules` directory locally, run `npm install`, then try building?

**Comment by chrisco23** [comment]
Thanks, this seems to have solved the issue.
For ubuntu / nginx people, to run "gatsby-serve build" I also had to increase max open files  by editing a few files.  There are a few suggestions out there for this, for example: http://posidev.com/blog/2009/06/04/set-ulimit-parameters-on-ubuntu/

"gatsby serve-build" is now working in production.  Sorry if this may be more of a "node" question but can you tell me what is the recommended way in the end to keep the server running?  Some "forever" command or something?

**Comment by KyleAMathews** [comment]
I think https://github.com/Unitech/pm2 is the most popular node.js process
runner these days.

**Comment by chrisco23** [comment]
Thanks again!
Seems to be working so far, with pm2:
```
pm2 startup
pm2 start gatsby -- serve-build
pm2 save
reboot
```
