### ISSUE TITLE
Build in chunks or other way to improve building time

### ISSUE THREAD

**Issue by hellopath** [gatsbyjs/gatsby#6040]
Hey everybody,

I would like to use gatsbyjs for an e-commerce but I have a big amount of pages/products. To generate each page I need to load data from multiple APIs, as a result the time of the building of the website is very very long. 

Is there any good practice to separate builds in chunks or something? 
For example to build only a specific products's page when its data changed on cms side.

Thanks for your help

**Comment by pieh** [comment]
Not possible currently - this issue is often described as adding incremental builds support - for example https://github.com/gatsbyjs/gatsby/issues/5002 - so please check on that. I'll close this as duplicate - this can be discussed in issue I linked.
