### ISSUE TITLE
SEO: indexing dynamical pages

### ISSUE THREAD

**Issue by nikbelikov** [gatsbyjs/gatsby#6046]
Hello!

Please tell me, how can I bring seo indexing by google and other search engines to my website?

I have a template for all news items. It's **one js-file** with some logic, which includes ajax queries after componentDidMount. Data becomes from the server and renders on the page.

But now I'm thinking how to handle seo on that? I need indexing every my news item one by one by search engines. May be it must be some kind of sitemap or something? Or I'm doing something wrong?

**Comment by KyleAMathews** [comment]
Gatsby has excellent support for SEO! https://www.gatsbyjs.org/docs/seo/#seo-with-gatsby

**Comment by nikbelikov** [comment]
It’s true. I read it. But it’s not my case. I have a dynamic page with an api requests when componentDidMoumt for news items. And Gatsby does not generate all news static pages.

**Comment by sparshy** [comment]
@nikbelikov  Even I am curious how we can index these dynamic pages for SEO. Did you find a possible solution for this?

**Comment by wahlforss** [comment]
@KyleAMathews is this solved?

**Comment by Md-Abdul-Halim-Rafi** [comment]
@KyleAMathews Badly need the solution, please.

**Comment by Md-Abdul-Halim-Rafi** [comment]
> It’s true. I read it. But it’s not my case. I have a dynamic page with an api requests when componentDidMoumt for news items. And Gatsby does not generate all news static pages.

I've same situation here
