### ISSUE TITLE
[v2 beta] React 16 not being used

### ISSUE THREAD

**Issue by seejamescode** [gatsbyjs/gatsby#6049]
In the blog post for the v2 beta, it says that React has been upgraded to v16.

I did `yarn global add gatsby-cli@next` to install the beta and checked the version number:
```
jamess-mbp:design jamesrauhut$ gatsby -v
2.0.0-beta.1
```

I then made a new site with this version, but digging into `node_modules` it looks like React v15.6.2 is being used. I caught this by trying to use `<React.Fragment>` and it throwing an error.

**Comment by LeKoArts** [comment]
If you used `gatsby new foldername` the [gatsby-starter-default](https://github.com/gatsbyjs/gatsby-starter-default) is being used. Which is not updated to v2 yet.
So you would upgrade it by hand:
https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/
