### ISSUE TITLE
Fix gatsbyjs.org speed — algolia css is blocking + add font subsetting

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#6051]
Current webpagetest http://www.webpagetest.org/result/180620_YH_f4e91dba994e97f62e523124998e2b2e/

Our speed index score used to be ~2750 and now it's ~6000 due to the blocking css

**Comment by jlengstorf** [comment]
This was fixed for next in #6108, #6123, #6128.

#6144 should fix this for v1.

**Comment by jlengstorf** [comment]
@m-allanson fixed this.
