### ISSUE TITLE
gatsby-plugin-sitemap: Add an option for having the trailing slash for the URLs

### ISSUE THREAD

**Issue by lipis** [gatsbyjs/gatsby#6058]
## Summary & Motivation

My canonical URLs have a trailing slash and I would like to have them in the `sitemap.xml`.

**Comment by KyleAMathews** [comment]
The plug-in is is removing trailing slashes from pathnames?

**Comment by lipis** [comment]
My bad! 😄 

I'm still playing around.. all good! 🍺
