### ISSUE TITLE
Ints > 32 bit are incorrectly inferred to GraphQLInt instead of GraphQLFloat

### ISSUE THREAD

**Issue by MichaelZoerner** [gatsbyjs/gatsby#6069]
## Description

Ints > 32 bit are incorrectly inferred to GraphQLInt instead of GraphQLFloat (GraphQLInt is only 32 bit long).

### Steps to reproduce
Use an integer > 32bit (e.g. 3000000000) in markdown frontmatter or json attribute and query it in GraphiQL or use [this demo repo](https://github.com/MichaelZoerner/GatsbyIssues) and follow the README.

### Expected result
The queried node should be displayed without errors.

### Actual result

The query result has errors such as:
```
{
  "errors": [
    {
      "message": "Int cannot represent non 32-bit signed integer value: 3000000000",
      "locations": [
        {
          "line": 6,
          "column": 7
        }
      ],
      "path": [
        "allDataJson",
        "edges",
        0,
        "node",
        "value"
      ]
    }
  ],
  "data": {
    "allDataJson": {
      "edges": [
        {
          "node": {
            "id": "26dc3246-8f8e-5d5b-8fab-72565b563d30",
            "value": null
          }
        }
      ]
    }
  }
}
```

### Environment

  System:
    OS: Windows 10
    CPU: x64 AMD Ryzen 7 1800X Eight-Core Processor
  Binaries:
    npm: 5.8.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: next => 2.0.0-beta.5
    gatsby-plugin-react-helmet: next => 3.0.0-beta.2
    gatsby-source-filesystem: next => 2.0.1-beta.3
    gatsby-transformer-json: next => 2.1.1-beta.2

### File contents (if changed)
see [repo](https://github.com/MichaelZoerner/GatsbyIssues)

**Comment by pieh** [comment]
Hey, if You are interested in fixing this issue I guess we should copy check graphql is doing ( https://github.com/graphql/graphql-js/blob/master/src/type/scalars.js#L36 ) to places where we preprocess data for inferring: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/data-tree-utils.js#L121 and then during inferring:
 - https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/infer-graphql-type.js#L120
 - https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/infer-graphql-input-fields.js#L79
 - https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/infer-graphql-input-fields.js#L168 (that's a little weird way to check that :) )

Not sure right now if those are all the places that need changes - but that's a good start

**Comment by pieh** [comment]
Oh - and that check should be abstracted, so we don't copy implementation in all those places

**Comment by MichaelZoerner** [comment]
[#6082](https://github.com/gatsbyjs/gatsby/pull/6082) should fix this.
