### ISSUE TITLE
[v2] HMR not updating all pages

### ISSUE THREAD

**Issue by LeKoArts** [gatsbyjs/gatsby#6072]
## Description

HMR is only updating one page.
I made a video:
https://drive.google.com/file/d/1wzHRKqX-e2rWyRXNc60_CZlipAhNTV1e/view?usp=sharing

The shell says:

```
info changed file at E:\Lennart\Documents\GitHub\portfolio\content\blog\2018-06-21\index.md
The "deleteNodes" action is now deprecated and will be removed in Gatsby v3. Please use "deleteNode" instead.
(node:28256) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListe
ners() to increase limit
```

What the video isn't showing:
A split second after switching the page the correct text is shown, but then it goes away.

**Note:** After some time the HMR doesn't work at all anymore. The changes on the same page won't be applied.

### Steps to reproduce

See video + [my repo](https://github.com/LeKoArts/portfolio)

### Expected result

HMR should work normally.

### Environment

Latest Gatsby, Windows 10 64-bit, IDE: Webstorm

**Comment by LeKoArts** [comment]
@pieh Could you tag it with the Bug label?

**Comment by KyleAMathews** [comment]
I haven't seen this nor has anyone else reported it. Can you verify the same problem happens on one of the official starters or example sites?

Planning on refactoring graphql query running soon so will look at what's happening on your site.

**Comment by LeKoArts** [comment]
@KyleAMathews Yes, I can verify that it also happens while using the `using-remark` example site. I also verified that it's a v2 problem (hence v1 has not these problems) and also it's not a Webstorm issue as I used VS Code as a test.

**Comment by m-allanson** [comment]
I can confirm I'm seeing the same issue on the `using-remark` example site.

**Comment by m-allanson** [comment]
Here's a basic markdown repo that demonstrates the bug: https://github.com/m-allanson/gatsby-barebones-markdown

**Comment by karlhorky** [comment]
Hot reloading for Markdown files appears to be broken in 2.0.0-beta.38 again. It can be demonstrated in @m-allanson's repo by upgrading gatsby to this version:

https://github.com/m-allanson/gatsby-barebones-markdown/pull/1

The last working version appears to be 2.0.0-beta.20.

**Comment by karlhorky** [comment]
Maybe I should open another issue for this?

**Comment by karlhorky** [comment]
Opened #6480 for this.
