### ISSUE TITLE
Zoom Image Like Medium

### ISSUE THREAD

**Issue by deadcoder0904** [gatsbyjs/gatsby#6086]
## Feature Request

Medium Image Zoom in Markdown Preview will be helpful because on my 15" screen side-by-side pane for Markdown looks very small & Image can't be read completely

## Basic Example

So something like https://rpearce.github.io/react-medium-image-zoom/ might be helpful in Markdown Preview :)

## Motivation

The images in the docs are too small that I can't read everything clearly so adding a few lines of JS won't hurt for Gatsby :)

**Comment by LeKoArts** [comment]
I actually did implement something like that with [zooming](https://desmonding.me/zooming/) locally in one of my projects with ´gatsby-remark-images`. I could do a PR up if I find time this weekend.

**Comment by m-allanson** [comment]
Hey @deadcoder0904 I'm curious to know which images were too small? Maybe we can improve the images or layout so that they're clearer?

**Comment by deadcoder0904** [comment]
Anything with GraphiQL like https://next.gatsbyjs.org/tutorial/part-five/

I mean you can read it but I don't have to bleed my eyes if it already has Zoom button. I want to look at the actual details on the right side of GraphiQL panel. Also, IMHO if its some website with images then a Zoom in should be the most common thing. But that's just my opinion :)

**Comment by johncmunson** [comment]
FYI, it's slightly hacky, but someone has written a [blog post](https://prestonrichey.com/blog/react-in-markdown/) showing how to achieve this in Gatsby

**Comment by LekoArts** [comment]
In addition to the blogpost and custom components in markdown: You also can use `gatsby-mdx` and use React components out of the box.

I'll close this issue as answered :)

**Comment by shinework** [comment]
Hi there! I've just published http://github.com/premieroctet/gatsby-remark-images-zoom. It brings medium-zoom on top of gatsby-remark-images

**Comment by deadcoder0904** [comment]
@shinework That looks solid. Love it & it works yay 🎉

Thank you ❤️

**Comment by rchrdnsh** [comment]
hmmmm...is there a version of this plugin for ‘gatsby-image’...would love to be able to zoom in to all images on a gatsby site, not just the images in a markdown file...

**Comment by xmflsct** [comment]
Any suggestions?

**Comment by rpearce** [comment]
I'm late to the game, but for what it's worth, I believe I've fixed this for `gatsby-plugin-image` in `react-medium-image-zoom@5.0.2-beta.0` and expect to release it in `5.0.2` soon. Here's the issue for tracking purposes: https://github.com/rpearce/react-medium-image-zoom/issues/347
