### ISSUE TITLE
Tests are babelified on Windows

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#6087]
## Description

On Windows, running `yarn run bootstrap` does not ignore the test files. This causes `yarn run test` to fail as it tries to run the duplicate tests that have missing snapshots (the snapshots are ignored by babel). This _seems_ to be an issue with babel 7-beta.51, but it may be caused by something else.

Refs #5725 

### Steps to reproduce

Check out this repo on windows
- yarn 
- yarn run bootstrap
- yarn run test

### Expected result

The tests should pass

### Actual result

Many tests fail due to missing snapshots - see https://ci.appveyor.com/project/KyleAMathews/gatsby/build/1.0.8054/job/i1gn9hsupdm3xoe6

### Environment

Windows 10

**Comment by m-allanson** [comment]
This might just need to wait for an upstream fix - see @pieh's comment at https://github.com/gatsbyjs/gatsby/pull/6089#issue-196685819

**Comment by m-allanson** [comment]
Is this fixed by #7655?

**Comment by KyleAMathews** [comment]
Yeah, afaik. We can re-open if appveyor keeps failing.
