### ISSUE TITLE
changing location of output js

### ISSUE THREAD

**Issue by trickydisco78** [gatsbyjs/gatsby#6094]
Hi,

Is it possible to configure the output path of the js?

Long story short but i've been told by our internal host that i can deploy index.html but not assets. Essentially I'm taking the deployment of our homepage out of the CMS and replacing it with gatsby. They are using some apache method to pull through this index page to resolve to the root address of the website. It's looking like they can't apply a *.js rule to components in this folder but what they can offer me is a different location for assets

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by m-allanson** [comment]
There's no way to do this at the moment, but it has been requested before. See https://github.com/gatsbyjs/gatsby/issues/5270

I'm going to close this as a duplicate but feel free to continue the conversation in #5270
