### ISSUE TITLE
Update page context

### ISSUE THREAD

**Issue by porfirioribeiro** [gatsbyjs/gatsby#6097]
Hi,

I created a system that creates pages automatically via json files.

In `createPages` i have a graphql query to find all pages i want to create and respective json content
But when i change the json files the page context is not updated.
I even tried to call `deletePage` and `createPage` again with the new context and the page is not getting updated.

It seems like the `public/static/d/path--index-**hash**.json` is not being updated, so even restarting the dev server do not work, i have to delete the files in `public/static/d` to be able to get the new context.

I am using gatsby v2, but this was already giving me the same trouble before

**Comment by pieh** [comment]
Are you using `gatsby-transformer-sharp` or reading `.json` files directly in `gatsby-node.js`? Could you link to repository that we can reproduce this problem?

**Comment by porfirioribeiro** [comment]
I am using gatsby-transformer-sharp for images, but the data I am loading to page context is direct from json files on gatsby-node.js

I will try to extract and simplify the code and share

**Comment by porfirioribeiro** [comment]
Ok so i tried to create a repo with only a minimal example.
https://github.com/porfirioribeiro/gatsby-ml
Remove everything to bare minimum, i hope later to make this a gatsby plugin to be easier to be used in other projects.

In this project i realize i don't get the problem with cache, so if i restart gatsby server i get my updated json content at least. So probably its related with some other plugin

Maybe someone could help me to figure out a way to be able to update pageContext when the JSON is changed and running dev server.

createPages is called and i get the new content from the JSON files, it does not update the content
https://github.com/porfirioribeiro/gatsby-ml/blob/master/plugins/gatsby-plugin-ml/gatsby/createPages.js#L104

**Comment by mortenson** [comment]
I'm seeing this as well https://github.com/gatsbyjs/gatsby/issues/6472#issuecomment-409803001

**Comment by aswinckr** [comment]
I have the same issue. I deleted the .cache folder and ran `gatsby develop` again to get it working.

**Comment by andrewbranch** [comment]
Seeing this as well. Not stale.
