### ISSUE TITLE
TypeScript support is broken

### ISSUE THREAD

**Issue by g8tguy** [gatsbyjs/gatsby#610]
After the last update the TypeScript demo doesn't load the index.tsx

**Comment by andrew8er** [comment]
Probably because commit b1a1850f12c555060050293c5bde71e31d6908f9 does not consider *.ts and *.tsx files in lib/utils/build-page/load-frontmatter.js

**Comment by g8tguy** [comment]
Actually the problem is in:
`create-routes.js`
```ts
} else if (reactComponentFileTypes.indexOf(page.file.ext) !== -1) {
    handler = pagesReq(`./${page.requirePath}`)
 ```
the handler is missing the `requireComponent`
if we add it, the /pages/index.tsx is loaded again!!!
```ts
handler = requireComponent(pagesReq(`./${page.requirePath}`))
```
Also it seem a good idea to add `tsx` support to `load-frontmatter`
`} else if (ext === 'js' || ext === 'jsx' || ext === 'tsx') {`

Kyle is it possible to add the fixes to the next update?

**Comment by KyleAMathews** [comment]
Would be happy to take a PR! I don't use Typescript so not the best to figure out what's working.

**Comment by KyleAMathews** [comment]
Let me know if you want any help putting together a PR — I'm often in the Gatsby discord channel https://discord.gg/0ZcbPKXt5bVoxkfV

**Comment by g8tguy** [comment]
Thanks, Kyle, and yes, I'll do the PR later next week, as I'm working pretty tight with TS, it turned out that there is much more stuff to take care off! Like for example wrappers are not rendered as TS. and we need auto generate the type definitions for ccs modules on the fly. 
So, I Guess besides the gatsby tweaks here and there, it would be the best to create a fully functional SPA/Blog with comments, pagination, next/previous articles, etc. and publish it as an example.
I'm now experimenting with gatsby and dexiejs to save and synchronize local states across the page refreshes and multiple tabs.
It's not really related to the topic but, with local storage control
we can give gatsby another caching layer and make SPA even more interactive.

**Comment by KyleAMathews** [comment]
Sounds fantastic! Looking forward to what you come up with! :-)
