### ISSUE TITLE
Extra word API in Tutorial Part 7 Docs

### ISSUE THREAD

**Issue by deadcoder0904** [gatsbyjs/gatsby#6101]
I'm finding too many issues right now but can't PR as my Mac is servicing. Till then, I'll post an issue :0

This file https://github.com/gatsbyjs/gatsby/blob/master/docs/tutorial/part-seven/index.md has an extra word `API`

Find `You've added an implementation of the createPages API which API Gatsby calls so plugins can add pages.`

& replace with

`You've added an implementation of the createPages API which Gatsby calls so plugins can add pages.`

**Comment by deadcoder0904** [comment]
Another typo `pandas-and-bananas.md"` should be `pandas-and-bananas.md` on the same page. Just an extra double quote"

**Comment by roachnt** [comment]
#6109

**Comment by roachnt** [comment]
#6109 Here you go!

**Comment by deadcoder0904** [comment]
Nice thanks :)

**Comment by jumpalottahigh** [comment]
#6109 is duplicate of #6104 though :) Maybe I should have commented here -.- Sorry about that.

**Comment by deadcoder0904** [comment]
Yeah should've 😅

**Comment by pieh** [comment]
Closed with https://github.com/gatsbyjs/gatsby/pull/6109
