### ISSUE TITLE
[www] Make docsearch non-blocking on v2 www site

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#6107]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">I ran a Lighthouse audit in Chrome DevTools on the Gatsby v2 site. Is this normal? <a href="https://t.co/diyMJoE79n">pic.twitter.com/diyMJoE79n</a></p>&mdash; Gudjon Jonsson ✪ (@gauiis) <a href="https://twitter.com/gauiis/status/1010309776633364482?ref_src=twsrc%5Etfw">June 22, 2018</a></blockquote>

The photo in that tweet is:

![dgvw6tkwaaaadid](https://user-images.githubusercontent.com/163561/41803478-072ddc00-763e-11e8-9282-89738d9cafe8.jpg)

I ran an audit as well, and it looks like the docsearch script we're pulling in is blocking the load and slowing down the page.

<img width="715" alt="screen shot 2018-06-22 at 4 58 41 pm" src="https://user-images.githubusercontent.com/163561/41803484-22acb14a-763e-11e8-9bf0-321ba00a033d.png">

We should make sure that's corrected to speed up the site.

**Comment by jlengstorf** [comment]
The script is loaded here:

https://github.com/gatsbyjs/gatsby/blob/5f50317ed7dc4b183c45c3d6866e9fa7440821b2/www/src/html.js#L57

Adding the `defer` attribute and a `<link rel="preload">` for it would solve the JS part of the problem.

For the CSS:

https://github.com/gatsbyjs/gatsby/blob/5f50317ed7dc4b183c45c3d6866e9fa7440821b2/www/src/html.js#L65-L68

We should look at dynamically appending that to the head or doing something else to prevent it from blocking the render.

This would be a great first issue for someone!

**Comment by yeion7** [comment]
🖐

**Comment by roachnt** [comment]
> Adding the defer attribute and a <link rel="preload"> for it would solve the JS part of the problem.

I understand the `defer` part, what you do you mean by adding a `<link rel="preload">`? Do you mean converting the script tag to a link tag with `as="script"`? Sorry if that's a bit of a naive question!

**Comment by robwierzbowski** [comment]
Preloading resources lets the browser start downloading something before it's called in the DOM. So a preload link at the top will tell the browser "go grab this, I know we'll need it soon". https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

**Comment by roachnt** [comment]
Right! So my initial thought when I read that was convert that script tag to a link tag, i.e. `<<link rel="preload" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js" as="script">`. However, about 3/4 of the way down the link you provided, there's a small script for also handling the defer and preload issue! Thoughts?

**Comment by jlengstorf** [comment]
@roachnt There's actually more that can be done on this front.

The JS is being deferred, but it's not being preloaded. This would actually make an excellent addition.

The CSS is being preloaded, but it's technically still blocking the load. One way we could work around that would be to dynamically insert that CSS via something like [this gist](https://gist.github.com/jlengstorf/4b39f2e5442620f1d26c14d48b580684).

If someone wants to build off @yeion7's fix to add this, I'd be happy to help!

**Comment by yeion7** [comment]
@jlengstorf i worked in this two thinks, on #6123

**Comment by KyleAMathews** [comment]
Fixed in https://github.com/gatsbyjs/gatsby/pull/6108 thanks! Speed Index on webpagetest is like 2x faster 😱 http://www.webpagetest.org/result/180623_TJ_b48f476320b4bffd33ae7d82c7aa36fc/

We need some sort of lighthouse score monitoring for our site to prevent regressions like this :-\

Thanks @jlengstorf and @yeion7!

@yeion7 is your second PR #6123 necessary? Looks like the JS script tries to load the same file and since it's preloaded, it's already cached when you try searching for something.

BTW, we should change the css loading to use prefetch not preload. Preload is only for something that'll be used immediately. People don't necessarily search ever so prefetching loads assets at a lower priority. @yeion7 could you make this change as well?

**Comment by jlengstorf** [comment]
@KyleAMathews I'm not exactly sure how this search works, but previously both the JS and CSS for docsearch were loaded synchronously. The fix @yeion7 is working on in #6123 preloads both the JS and CSS, adds `defer` to the JS, and asynchronously adds the CSS to the head.

Without more context, this seems like the best way to make sure the search is available without needing custom event listeners to load the resources. Am I missing something?

**Comment by jlengstorf** [comment]
Pretty sure this was fixed in #6108 and #6123.
