### ISSUE TITLE
No way to access docs on mobile 

### ISSUE THREAD

**Issue by deadcoder0904** [gatsbyjs/gatsby#6111]
https://next.gatsbyjs.org/docs/ doesn't have docs as v1 site

**Comment by deadcoder0904** [comment]
Below Documentation heading there's nothing on mobile

**Comment by m-allanson** [comment]
Thanks @deadcoder0904 - this should be handled as part of the docs IA rfc, but I'll leave this open so it can be tracked while gatsbyjs/rfcs#5 is worked on.
