### ISSUE TITLE
How to handle different routes to render same component ?

### ISSUE THREAD

**Issue by sovanjana** [gatsbyjs/gatsby#6116]
I want to use same component for both login and signup with just different fields.
for signup route will be '/signup' and for login route will be '/login'.

My question is do I need to add two separate page in the 'pages' folder for login and signup?

help needed...

**Comment by m-allanson** [comment]
You could have an `Auth` component in `components/auth.js`, then include that in `pages/signup.js` and `pages/login.js`?

**Comment by sovanjana** [comment]
thanks @m-allanson
