### ISSUE TITLE
Maintain Scroll Position on Sidebar Links

### ISSUE THREAD

**Issue by deadcoder0904** [gatsbyjs/gatsby#6124]
Visit https://next.gatsbyjs.org/docs/actions/ & it must scroll to that link in the sidebar because when I am reading the docs which has quite a lot of links it scrolls up all the time & this might be better UX

**Comment by ryanditjia** [comment]
Related: https://github.com/gatsbyjs/gatsby/issues/5773

**Comment by m-allanson** [comment]
Also refs: https://github.com/gatsbyjs/rfcs/pull/5

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by deadcoder0904** [comment]
This one works so good its closed
