### ISSUE TITLE
[Feature Request] support mapping node types for markdown

### ISSUE THREAD

**Issue by tsiq-swyx** [gatsbyjs/gatsby#6126]
## Summary

There is a gatsby "advanced feature" for [mapping between node types declaratively](https://www.gatsbyjs.org/docs/gatsby-config/#mapping-node-types) and in [this issue](https://github.com/gatsbyjs/gatsby/issues/4972) we find that only json and yaml is supported with this magic. do we want to support markdown?

### Motivation

> Why are we doing this? What use cases does it support? What is the expected outcome?

increase the usability of this mapping feature.

i'd rate this idea as low priority for now unless more people come along with it. for now i have to transform my md data to yaml just to use this.

**Comment by KyleAMathews** [comment]
We can map between any node type. Needs more docs. Perhaps an alternative API.
