### ISSUE TITLE
bundle.js compression

### ISSUE THREAD

**Issue by g8tguy** [gatsbyjs/gatsby#613]
is it enabled by default? I'm getting like a 1mb bundle.js for an ampty project...

**Comment by KyleAMathews** [comment]
In development or production?

**Comment by g8tguy** [comment]
production - `gatsby build` I have some dynamic components in my site and i need `bundle.js` in production - previously it was compressed if I remember it right.

**Comment by KyleAMathews** [comment]
Compression is done by your server. Gatsby minifies your bundle.js. if you want to see the compressed size serve your site with `gatsby serve-build`.

**Comment by g8tguy** [comment]
got it, thanks!
