### ISSUE TITLE
[v2] Footer on Mobile should be highlighted when tapped 

### ISSUE THREAD

**Issue by deadcoder0904** [gatsbyjs/gatsby#6131]
The Footer at the bottom Docs, Tutorial, etc..  needs to provide some sort of indication like v1 when tapped

**Comment by zebapy** [comment]
I could take this if no one else has

**Comment by deadcoder0904** [comment]
@zebapy Take it. I think no one else has otherwise they would've pinged here.

**Comment by zebapy** [comment]
I have not gotten to this so anyone else can claim if they want

**Comment by sadewole** [comment]
I'll work on it
