### ISSUE TITLE
[v2] Docs need Previous & Next button on mobile 

### ISSUE THREAD

**Issue by deadcoder0904** [gatsbyjs/gatsby#6133]
Visit https://www.gatsbyjs.org/docs/adding-images-fonts-files/ on mobile & then you would realize if you want to read the next thing you gotta go back & then next article. On Desktop it's not a problem.

**Comment by m-allanson** [comment]
Maybe we could have these on the larger versions of the site also.

**Comment by LekoArts** [comment]
The buttons got removed in the meantime.
