### ISSUE TITLE
[v2] Gatsby link is not working after being deployed to netlify

### ISSUE THREAD

**Issue by daydream05** [gatsbyjs/gatsby#6140]
## Description

When deployed to netlify, gatsby links are broken.

### Steps to reproduce

Use `import { Link } from "gatsby"`,
deploy it to netlify and try clicking the generated links.

### Expected result

It should go to the linked page
 
### Actual result

Navigation is not working and it's throwing this error on the console.
```
react-dom.production.min.js:17 Uncaught TypeError: window.___navigateTo is not a function
    at Object.onClick (index.js:206)
    at r.handleClick (Link.js:37)
    at Object.<anonymous> (react-dom.production.min.js:15)
    at Object.invokeGuardedCallback (react-dom.production.min.js:16)
```

### Environment

System:
    OS: macOS High Sierra 10.13.3
    CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.0.0 - /usr/local/bin/node
    Yarn: 1.6.0 - ~/.yarn/bin/yarn
    npm: 6.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.87
    Firefox: 57.0.3
    Safari: 11.0.3
  npmPackages:
    gatsby: next => 2.0.0-beta.1
    gatsby-image: ^2.0.0-beta.1 => 2.0.0-beta.1
    gatsby-link: ^1.6.44 => 1.6.44
    gatsby-plugin-canonical-urls: ^1.0.18 => 1.0.18
    gatsby-plugin-feed: ^1.3.22 => 1.3.25
    gatsby-plugin-google-analytics: ^1.0.31 => 1.0.31
    gatsby-plugin-manifest: ^1.0.22 => 1.0.27
    gatsby-plugin-netlify: ^1.0.19 => 1.0.21
    gatsby-plugin-nprogress: ^1.0.14 => 1.0.14
    gatsby-plugin-offline: ^1.0.16 => 1.0.18
    gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11
    gatsby-plugin-sitemap: ^1.2.23 => 1.2.25
    gatsby-plugin-styled-components: ^2.0.11 => 2.0.11
    gatsby-plugin-svgr: ^1.0.1 => 1.0.1
    gatsby-plugin-typography: ^1.7.19 => 1.7.19
    gatsby-remark-prismjs: ^2.0.2 => 2.0.4
    gatsby-source-contentful: next => 2.0.1-beta.1
    gatsby-source-filesystem: ^1.5.36 => 1.5.39
    gatsby-transformer-remark: ^1.7.41 => 1.7.44
    gatsby-transformer-sharp: ^2.1.1-beta.1 => 2.1.1-beta.1
  npmGlobalPackages:
    gatsby-cli: 1.1.58

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by wiesson** [comment]
Can you add your implementation of the `Link` component?

**Comment by Khaledgarbaya** [comment]
It looks like you are using the old `gatsby-link` you should change your code to `import {Link} from 'gatsby'` as mentioned in the [migration guide](https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#import-link-from-gatsby)

**Comment by daydream05** [comment]
As stated on my steps to reproduce, I'm using the new Link from gatsby js. I still have gatsby-link installed but it's not imported anywhere. (If i remove it, gatsby-plugin-rsss breaks for some reason)

Here's the full code.

```
import React from 'react'
import { Link } from 'gatsby'

const Menu = () => {
  return (
    <Header>
      <Nav>
        <ul>
          <li>
            <Link to="/" exact activeStyle={activeLinkStyle}>
              Home
            </Link>
          </li>
          <li>
            <Link to="/about/" activeStyle={activeLinkStyle}>
              About
            </Link>
          </li>
          <li>
            <Link to="/contact/" activeStyle={activeLinkStyle}>
              Contact
            </Link>
          </li>
        </ul>
      </Nav>
    </Header>
  )
}
```

This was forked from [Gatsby starter gcn](https://github.com/ryanwiemer/gatsby-starter-gcn), which I modified to comply with v2. I've searched the codebase and it doesn't use navigateTo at all.

**Comment by daydream05** [comment]
Case closed! I updated the gatsby-link package to the latest version and it works. For some reason, gatsby-link is still being used somewhere and we can't remove it yet.

**Comment by pieh** [comment]
Fixed with https://github.com/gatsbyjs/gatsby/pull/6147
