### ISSUE TITLE
[v2] Wrapping pages with layout causes CSS Transition issues

### ISSUE THREAD

**Issue by juliettepretot** [gatsbyjs/gatsby#6154]
My v1 page features a cute little animation when navigating between pages. The animations are realized using react routers `activeClassName` and css transitions.

[![https://gyazo.com/3c89045a2bad1cda9f85cf3f32916d1f](https://i.gyazo.com/3c89045a2bad1cda9f85cf3f32916d1f.gif)](https://gyazo.com/3c89045a2bad1cda9f85cf3f32916d1f)

This breaks when migrating to v2 according to the migration guide:

[![https://gyazo.com/4610bd9f7a19c65d4a9a0a4bf3a2548e](https://i.gyazo.com/4610bd9f7a19c65d4a9a0a4bf3a2548e.gif)](https://gyazo.com/4610bd9f7a19c65d4a9a0a4bf3a2548e)

The reason is the following: In v2 the layout component gets unmounted and mounted every time I navigate from one page to another:

[![https://gyazo.com/ecd0e9543213bb12bb3a248fb2739042](https://i.gyazo.com/ecd0e9543213bb12bb3a248fb2739042.gif)](https://gyazo.com/ecd0e9543213bb12bb3a248fb2739042)

This is because in v2 every page is individually wrapped with my layout component. On navigation the entire page, including its wrapper gets unmounted. In v1 the pages were being merely exchanged inside of layout.

The entire layout being remounted means that CSS does not consider the `activeClassName` to be applied to an existing element, instead a new element which happens to have this className appears. This means that the transition never fires.

Any idea if it is at all possible to avoid this?

---

See the page source code here: https://github.com/juliettepretot/juliette.sh

**Comment by LeKoArts** [comment]
+1
Would also strongly be interested into a solution to this!

**Comment by jonbellah** [comment]
For posterity, I reported a similar issue here: https://github.com/gatsbyjs/gatsby/issues/6127

**Comment by m-allanson** [comment]
Closing this in favour of #6127, so discussion is focussed to one issue.
