### ISSUE TITLE
PDF links and --prefix-paths

### ISSUE THREAD

**Issue by cgpro** [gatsbyjs/gatsby#6156]
## Description

I've added some PDFs to the content and the prefix is attached multiple times (2x).

### Steps to reproduce

In pages I have the following folders for my assets:
img
pdf
video
*-content.js

img and video works fine, but
`import pdfref from './pdf/thepdf.pdf'`
in conjunction with gatsby-link
`<Link to={pdfref} className="btn download" target="_blank"><FaDownload /> Download</Link>` 
results in
`href="subfolderA/subfolderB/subfolderA/subfolderB/static/thepdf.pdf`.
It happens with develop and with build /static is corretly added to the path.

### Expected result

The prefix `subfolderA/subfolderB` should be attached only one time.

### Actual result

The prefix is attached two times.

### Environment

System:
    OS: macOS High Sierra 10.13.5
    CPU: x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.4.1 - /usr/local/bin/node
    npm: 6.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.87
    Firefox: 60.0.2
    Safari: 11.1.1
  npmPackages:
    gatsby: ^1.9.272 => 1.9.272 
    gatsby-image: ^1.0.54 => 1.0.54 
    gatsby-link: ^1.6.40 => 1.6.40 
    gatsby-plugin-react-helmet: ^2.0.10 => 2.0.10 
    gatsby-plugin-react-next: ^1.0.11 => 1.0.11 
    gatsby-plugin-sass: ^1.0.26 => 1.0.26 
    gatsby-plugin-sharp: ^1.6.48 => 1.6.48 
    gatsby-transformer-sharp: ^1.6.27 => 1.6.27 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

### File contents (if changed)

`gatsby-config.js: 
const path = require('path')

module.exports = {
  siteMetadata: {
    title: 'Giesecke & Devrient Microsite',
  },
  pathPrefix: '/subfolderA/subfolderB/',
  plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-react-next',
    'gatsby-transformer-sharp',
	  'gatsby-plugin-sharp',
    {
      resolve: 'gatsby-plugin-sass',
      options: {
        precision: 8,
      },
    },
    ],
}
`

`package.json: 
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "bootstrap-4-grid": "^2.4.0",
    "dotenv": "^6.0.0",
    "gatsby": "^1.9.272",
    "gatsby-image": "^1.0.54",
    "gatsby-link": "^1.6.40",
    "gatsby-plugin-react-helmet": "^2.0.10",
    "gatsby-plugin-react-next": "^1.0.11",
    "gatsby-plugin-sass": "^1.0.26",
    "gatsby-plugin-sharp": "^1.6.48",
    "gatsby-transformer-sharp": "^1.6.27",
    "prop-types": "^15.6.2",
    "react-helmet": "^5.2.0",
    "react-icons": "^2.2.7",
    "react-slick": "^0.23.1",
    "slick-carousel": "^1.8.1",
    "typeface-pt-sans": "0.0.54"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write 'src/**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "prettier": "^1.12.0"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  }
}
`

**Comment by pieh** [comment]
`gatsby-link` should be used only for navigation. For downloads, please use regular `<a>` tags

**Comment by cgpro** [comment]
Haha formatted my issue and the feedback was faster, thanks for the hint!
