### ISSUE TITLE
[v2] Gatsby cannot parse 'public' functions in TypeScript

### ISSUE THREAD

**Issue by Mrtenz** [gatsbyjs/gatsby#6157]
## Description

When one of the functions in a class (like a React component) is `public`, Gatsby is not able to parse the file:
```
There was a problem parsing "/examples/using-typescript/src/pages/index.tsx"; any GraphQL fragments or queries in this file were not processed.
This may indicate a syntax error in the code, or it may be a file type that Gatsby does not know how to parse.
```

It does work with React components that are included on those pages.

### Steps to reproduce

1. Get the `using-typescript` example from [here](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-typescript).
2. Change the default export in `src/pages/index.tsx` to this:
```typescript
export default class Index extends React.PureComponent<IndexPageProps> {
  public render () {
    const { siteName } = this.props.data.site.siteMetadata
    return (
      <Layout>
        <h1>Hello Typescript world!</h1>
        <p>
          This site is named <strong>{siteName}</strong>
        </p>
      </Layout>
    )
  }
}
```
3. Run `gatsby develop`.

### Environment

Gatsby version: 2.0.0-beta.2
Node version: 8.11.2
Npm version: 5.6.0

### File contents (if changed)

I used the [`using-typescript`](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-typescript) example for this issue.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
