### ISSUE TITLE
Move Eslint config to npm package

### ISSUE THREAD

**Issue by kkemple** [gatsbyjs/gatsby#6168]
## Summary

The idea is take the Eslint configuration from the webpack loader and move it into a npm package. Then have webpack loader reference that instead of keeping config in a util file. 

### Motivation

There are a few motivating factors:

- It will be easier to configure tooling outside of Gatsby to work well with Gatsby apps
- It becomes more clear how Gatsby linting is working and makes it more accessible to those less familiar with code base
- [All the cool kids are doing it](https://github.com/facebook/create-react-app/tree/master/packages/eslint-config-react-app)

**Comment by KyleAMathews** [comment]
We're just using the create react app eslint config. We should document this but closing this for now.
