### ISSUE TITLE
[gatsby-source-contentful] Generating nodes type using model name not using ID

### ISSUE THREAD

**Issue by ahgz7** [gatsbyjs/gatsby#6169]
## Summary
The nodes generated in graphQL that represent content models in Contentful have their types generated using the content model's name not the ID generated in Contentful.

Here you can see that the ID is generated from the name:
https://github.com/gatsbyjs/gatsby/blob/2512eef2137b147752b35bdd92a2fe6970821d39/packages/gatsby-source-contentful/src/normalize.js#L329

This can cause a lot of problems when a model name is changed from Contentful. The nature of the name is mutable but the ID generated is immutable, which makes it much reliable to build graphQL queries against.

Is this by design? or do you believe it should be changed to use the model ID instead of the name?

**Comment by KyleAMathews** [comment]
GraphQL types should be human readable not random IDs.

When you change model names, can't you just do a copy-replace of graphql queries to update them?

**Comment by ahgz7** [comment]
Hey @KyleAMathews, Thank you for your reply.
Actually it's not a random ID, it's a camel case name generated from the model name with the first letter in lower case.

For example, I created a content model with the `Section - Contact` and the generated ID for this model is `sectionContact`. Here's a screenshot from the content model settings page:
<img width="334" alt="screen shot 2018-06-27 at 8 33 49 pm" src="https://user-images.githubusercontent.com/2143690/41992715-8b4ad556-7a49-11e8-8af4-7fac0d382ca2.png">

Also, in the JSON preview you can get this ID through `sys.id`.

I believe it's much reliable to use this generated ID that Contentful doesn't allow to be changed once created, and that is being generated in the same format in the plugin:
https://github.com/gatsbyjs/gatsby/blob/2512eef2137b147752b35bdd92a2fe6970821d39/packages/gatsby-source-contentful/src/normalize.js#L12

I'm new to Contenful api, but maybe the ID in this format is a new thing, or is it implemented this way by design?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
