### ISSUE TITLE
Unable to change NODE_ENV manually

### ISSUE THREAD

**Issue by oliverbenns** [gatsbyjs/gatsby#617]
Looking at [this PR](https://github.com/gatsbyjs/gatsby/pull/59), it looks like you should be able to edit the NODE_ENV. This works for develop but the build command always overwrites to "production"

Testing with ` NODE_ENV=foo npm run build`. With the package json script being the default `"build": "gatsby build"`

**Comment by KyleAMathews** [comment]
Hmmm... that is true, we set somewhere in code NODE_ENV to production during build — but you kinda have to have it that way — there's all sorts of optimizations within React and other modules within the React ecosystem that are only turned on when `NODE_ENV=production`.

Why not just set another env variable e.g. `MY_CUSTOM_VAR=whatever`? You have to modify the webpack config slightly to add a new `DefinePlugin` like [in core](https://github.com/gatsbyjs/gatsby/blob/2d8e7869ef1672a04ca228a5791d7d46f7499ef8/lib/utils/webpack.config.js#L124)

**Comment by oliverbenns** [comment]
Yeah I also tried custom variables though bash but logging `process.env` only gave me NODE_ENV. I'll have a look at the webpack config.

**Comment by oliverbenns** [comment]
Any news on this? Can't seem to set any custom variables, e.g.: `"develop": "TEST=foobarbaz gatsby develop",`.

For those in a similar circumstance, my current workaround is to create a environment js file that changes depending on environment.

```
const config = {
  production: {
    analyticsId: 'UA-11111111-1',
    api: {
      url: 'https://api.google.com',
    },
  },
  development: {
    analyticsId: 'UA-00000000-0',
    api: {
      url: 'http://localhost:3000'
    },
  },
};

export default config[process.env.NODE_ENV] || {};

```

**Comment by oliverbenns** [comment]
Will close this for https://github.com/gatsbyjs/gatsby/issues/660

**Comment by yvele** [comment]
For reference, this issue is related to https://github.com/gatsbyjs/gatsby/issues/337#issuecomment-226956766

> We autoset `NODE_ENV=production` on `gatsby build`

**Comment by anaibol** [comment]
So we can't override NODE_ENV? I wanted to set NODE_ENV to staging so gatbsy uses `.env.staging` env variables file

**Comment by ruslan-mystore** [comment]
@jongear i get this error according to your workaround (same as in gatsby docs) and tried to install dependencies , but without succes:

```
 Failed to compile with 1 errors                                                                                                              18:26:15

This dependency was not found:

* fs in ./~/dotenv/lib/main.js

To install it, you can run: npm install --save fs
```
