### ISSUE TITLE
Pull in nested entities when using Gatsby Drupal plugin

### ISSUE THREAD

**Issue by sheelah** [gatsbyjs/gatsby#6172]
Is it possible to customize the data pulled in from a Drupal 8 JSON API by the Gatsby Drupal plugin? It's working fine for basic queries, but I'm noticing that it doesn't pull in all nested relationship data for my content types.  

For example, if I have `showcase` content type, I can pull in any showcase's information, but the child showcase items are not getting included:

```js
{
  showcase(nid: {eq: 19389}) {
    id
    uuid
    title
    description
    nid
    description
    children {
      id
    }
  }
}
```
I get back data with `children` being empty, instead of including the nested `relationships` data:
```js
{
  "data": {
    "showcase": {
      "id": "6696c92f-b059-4a26-8bc7-c522b267ec46",
      "uuid": "6696c92f-b059-4a26-8bc7-c522b267ec46",
      "title": "Showcase Contact Us",
      "description": "Holla.",
      "nid": 19389,
      "children": []
    }
  }
}
```

If I query my Drupal 8 JSON API directly I can see the showcase's relationship data:
```js
{
    "data": [
        {
            "type": "showcase",
            "id": "6696c92f-b059-4a26-8bc7-c522b267ec46",
            "attributes": {
                "nid": 19389,
                "uuid": "6696c92f-b059-4a26-8bc7-c522b267ec46",
                "vid": 102223,
                "langcode": "en",
                "status": true,
                "title": "Showcase Contact Us",
                "created": 1529948819,
                "changed": 1529948935,
                "path": null,
                "description": "Holla."
            },
            "relationships": {
                "items": {
                    "data": [
                        {
                            "type": "showcase_item",
                            "id": "e7d9cc10-d606-4801-81a7-94aaf94ebc64",
                            "meta": {
                                "target_revision_id": 43
                            }
                        },
                        {
                            "type": "showcase_item",
                            "id": "3d6b19ee-500b-4ca5-9774-2c3229170414",
                            "meta": {
                                "target_revision_id": 44
                            }
                        }
 ```

Is there something I should be customizing via `gatsby-node.js`, or would I need to recreate this plugin with more customizations? Thanks!

**Comment by KyleAMathews** [comment]
What is the full schema for `showcase`? You can see this in graphiql in the docs explorer.

**Comment by sheelah** [comment]
The schema for `showcase` that the Gatsby Drupal plugin is creating:
![gatsby_drupal_plugin_showcase_schema](https://user-images.githubusercontent.com/1900318/41982874-bf88a4e8-79e9-11e8-902a-4131f3da8cb2.jpg)


Here's the underlying Drupal 8 schema for `showcase`:
![drupal8_schema_showcase](https://user-images.githubusercontent.com/1900318/41983287-df019b1c-79ea-11e8-9050-863ce34af26e.jpg)



Here's the schema for `showcase` `fieldItems` which are the child items that are not coming through in Gatsby when using the Drupal plugin:
![drupal8_schema_showcase_items](https://user-images.githubusercontent.com/1900318/41982974-ff908c04-79e9-11e8-949a-49bb9eb6c3c7.jpg)

**Comment by pieh** [comment]
Hey, drupal plugin currently doesn't support 1 to many relationships - there is open PR to fix that - https://github.com/gatsbyjs/gatsby/pull/5020 but I didn't have time to update it lately. If you feel like you could take that over, fix merge conflicts this could be merged to master because we are developing beta versions of packages, so it's OK-ish to land breaking stuff now

**Comment by sheelah** [comment]
Thanks @pieh - wasn't aware of that.  I'm a bit unclear on what's remaining on #5020 -- just merge conflict fixes, or implementation of that second piece that was being discussed (naming of back-references)?

**Comment by pieh** [comment]
Just merge conflicts for now would be fine. Other things mentioned in that PR could be done later if needed. 

I still think that my point about not using type names as field names for back-references is valid (using same example scenario I presented in that PR), but this could be done with non-breaking change later - for example by using both type names (as we do right now) and additionally `backref_${relationship_name}` (or however that would be called).

**Comment by sheelah** [comment]
I see. Was the plan to still merge this into the `master` branch (which is now defaulting to Gatsby v2), or the `v1` branch?

I tried this branch out and am seeing relationship data coming through  🎉 but I'm getting some GraphQL schema-related errors when trying to pull in some of the child entities' fields (Ex. `"message": "Expected value of type \"press\" but got: [object Object].",`) so I'm thinking that with all its nested relationships, my use case may require a custom plugin altogether.

**Comment by pieh** [comment]
hmm, I might missdiagnoses earlier then, but still I feel like default plugin could be adjusted to handle those too

**Comment by sheelah** [comment]
That was the correct diagnosis.  Update on this one: my team has opted to build a custom GraphQL-based plugin instead, so I'm not going to be able to contribute to #5020.   Happy to open a PR to add a note about the current Gatsby Drupal source plugin limitations in its readme if you'd like though.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
