### ISSUE TITLE
Gatsby Serve doesn't seem to be working

### ISSUE THREAD

**Issue by jskrt** [gatsbyjs/gatsby#6176]
## Description

When running gatsby build, I get:

```error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  40 |       var args = [a, b, c, d, e, f];
  41 |       var argIndex = 0;
> 42 |       error = new Error(format.replace(/%s/g, function () {
     | ^
  43 |         return args[argIndex++];
  44 |       }));
  45 |       error.name = 'Invariant Violation';


  WebpackError: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and addition  al helpful warnings.

  - invariant.js:42 invariant
    ~/fbjs/lib/invariant.js:42:1

  - react-dom-server.node.production.min.js:11 z
    ~/react-dom/cjs/react-dom-server.node.production.min.js:11:166

  - react-dom-server.node.production.min.js:34 a.render
    ~/react-dom/cjs/react-dom-server.node.production.min.js:34:499

  - react-dom-server.node.production.min.js:32 a.read
    ~/react-dom/cjs/react-dom-server.node.production.min.js:32:201

  - react-dom-server.node.production.min.js:43 renderToString
    ~/react-dom/cjs/react-dom-server.node.production.min.js:43:1

  - static-entry.js:126 module.exports
    .cache/static-entry.js:126:31

  - static-entry.js:99 Function.Promise.fromNode.Promise.fromCallback
    .cache/static-entry.js:99:20
```

### Steps to reproduce

I'm not sure. I just run gatsby build. gatsby develop works perfectly fine.

### Expected result

It should build without errors.

### Actual result

Described above

### Environment

  System:
    OS: macOS High Sierra 10.13.5
    CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.10.0 - /usr/local/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 6.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.87
    Firefox: 57.0.2
    Safari: 11.1.1
  npmPackages:
    gatsby: ^1.9.261 => 1.9.261 
    gatsby-link: ^1.6.40 => 1.6.40 
    gatsby-plugin-favicon: ^2.1.1 => 2.1.1 
    gatsby-plugin-react-helmet: ^2.0.10 => 2.0.10 
    gatsby-plugin-react-next: ^1.0.11 => 1.0.11 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

### File contents (if changed)

`gatsby-config.js`:
```
module.exports = {
  siteMetadata: {
    title: 'Violet',
  },
  plugins: ['gatsby-plugin-react-helmet', `gatsby-plugin-react-next`],
}
```
`gatsby-node.js`:
```
exports.modifyWebpackConfig = ({ config, stage }) => {
    if (stage === "build-html") {
      config.loader("null", {
        test: /react-dual-timeline/,
        loader: "null-loader",
      });
    }
};
```

**Comment by KyleAMathews** [comment]
Can you create a site that reproduces this? It's not at all clear from the stack trace what's causing the trouble. A way to debug also is to delete code bit by bit until the error clears up.

**Comment by smasinde** [comment]
Did you find a fix for this?

**Comment by jskrt** [comment]
I haven't had the time to "create a site that reproduces this". I'm not sure what the best way to debug this is but I will get to it in the next couple of weeks with the suggested method above.

**Comment by oprearocks** [comment]
I'm experiencing a similar problem but in production.

`gatsby build` runs smooth, I get a proper build, it gets automatically deployed to Netlify, but when I try to load the site in the browser, I get this error. Not sure if it's because I've used ServiceWorkers in the past, but it seems to manifest itself in private browsing, too.  At one point it seemed to link to the fact that I was using Contentful to host my images and probably the JavaScript that was generating my image code was choking on something but then it became random, again.

I've never seen this error in development, though. It would have been very easy to debug, then. Is there a way to turn on source maps and maybe deploy the development version to production? I think I can properly debug if I have that live.
