### ISSUE TITLE
Nested Lists using Contentful/GraphQL

### ISSUE THREAD

**Issue by squaredindex** [gatsbyjs/gatsby#6180]
I've been trying to find the best way to display multiple lists of documents onto a single page. The trouble I'm having is figuring out how to nest arrays or lists within lists that can be edited and have new lists added via Contentful to keep things simple and DRY for the client adding the content.

### **The Structure of the content is essentially like so:**

---------------
# Planning Documents (Document Type List)
## 2018 (Document Year Archive List)
[Jan](#) (Document File)
[Feb](#) (Document File)
etc...
## 2017 (Document Year Archive List)
[Jan](#) (Document File)
[Feb](#) (Document File)
etc...

# Minutes Documents (Document Type List)
## 2018 (Document Year Archive List)
[Jan](#) (Document File)
[Feb](#) (Document File)
etc...
## 2017 (Document Year Archive List)
[Jan](#) (Document File)
[Feb](#) (Document File)
etc...

---------------

I've been able to get it working in as far as displaying an array of all the documents listing their date of publication and a link to the file as one long list:

- March, 2016
- September, 2015
- April, 2015
- March, 2016
- March, 2016
- July, 2016
- September, 2015
- November, 2015
- November, 2015

I did that by creating a DocListing component:
```javascript
import React from 'react';

const DocListing = ({ doc }) => (
  <li>
    <a title={doc.title} href={doc.file.file.url}>
      {doc.publishDate}
    </a>
  </li>
);

export default DocListing;
```
then displaying the array on my page:

```javascript
<ul>
         {data.allContentfulDocument.edges.map(({ node }) => (
             <DocListing key={node.id} doc={node} />
           ))}
</ul>
```
my graphql for document list look like this:
```graphql
allContentfulDocument {
      edges {
        node {
          type
          publishDate(formatString: "MMMM, YYYY")
          title
          file {
            file {
              url
            }
          }
        }
      }
    }
```

But at the moment that is simply displaying the publication date of all the documents created via Contentful and I'd like to section those under Year of publication and Type of Document lists. However I'm still unsure of how to approach nesting lists/arrays within one another, so that the client has the freedom to use Contentful to add new lists/sections as and when needed.

**Comment by Khaledgarbaya** [comment]
Hey @squaredindex,
You can use graphql aggregation to achieve the grouping of documents by date your query should be something like.

```js
allContentfulDocument {
group(field: publishDate) {
      edges {
        node {
          type
          publishDate(formatString: "MMMM, YYYY")
          title
          file {
            file {
              url
            }
          }
        }
      }
    }
}
```
and you should get an ouput similar to this

```
{
  "data": {
    "allContentfulLesson": {
      "group": [
        {
          "edges": [
            {
              "node": {
                "publishDate": "March 2018"
                 ....
              }
            },
           {
              "node": {
                "publishDate": "March 2018"
                 ....
              }
            }
          ]
        },
        {
          "edges": [
            {
              "node": {
                "publishDate": "April 2018"
                 ....
              }
            }
          ]
        },
        {
          "edges": [
            {
              "node": {
                "publishDate": "May 2018"
                 ....
              }
            }
          ]
        }
      ]
    }
  }
}
```
you need to make sure that publishDate has the same value accross documents in the same group.
This theoretcally should work and I did a small test locally and it looks like it groups data base on a field.
I hope that helps.

Best,
Khaled

**Comment by squaredindex** [comment]
Hey @Khaledgarbaya apologies for the late response, my health hasn't been the best.

I know it might seem blindingly obvious, but I must be missing some fundamentals because I'm struggling to rewrite this section get it to work:

```javascript
<ul>
         {data.allContentfulDocument.edges.map(({ node }) => (
             <DocListing key={node.id} doc={node} />
           ))}
</ul>
```
Tried adding "group" and added an id to node. Then a few different variations, but I may just be approching this from the wrong angle as I haven't been able to get it to work.

My approach may be wrong also because even if I am able to filter them like this, what I'm trying to do is have the months display in order (Jan to Dec) under the header (h2) that displays the Year for that group of documents.

So the structure I'm looking to create would be like so:
```html

<docTypeSection> (repeatable)
    <h1>Minutes</h1>
    <docYearSection> (repeatable)
        <h2>2018</h2>
        <ul>
            <li><a href=(link to document)>January</a></li> (repeatable)
         </ul>
    </docYearSection>
</docTypeSection>

```

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
