### ISSUE TITLE
[gatsby-source-medium] Allow custom post limit to be set

### ISSUE THREAD

**Issue by seaburrows** [gatsbyjs/gatsby#6181]
## Summary

The plugin currently gets the default number of latest posts from Medium but you are able to increase this by passing a `limit` parameter. 

### Basic example

I've not tested this as I'm not certain how you'd implement, but I think it should be a matter of setting the `limit` parameter is this part of `gatsby-node.js`:
```
const fetch = (username, limit = 10) => {
  const url = `https://medium.com/${username}/latest?format=json&limit=${limit}`
  return axios.get(url)
}
```
To supprt the above call you'd need to set the limit parameter in `gatsby-config.js`:
```
// In your gatsby-config.js
plugins: [
  {
    resolve: `gatsby-source-medium`,
    options: {
      username: `username/publication`,
      limit: 100,
    },
  },
]
```
and using it here:
```
exports.sourceNodes = async ({ actions, createNodeId }, { username, limit }) => {
  const { createNode } = actions

  try {
    const result = await fetch(username, limit)
```

### Motivation

I want to be able to load all of my Medium articles to display in my Gatsby site. 

I'd prefer to load them all by default, and then limit the results using the graphql query, but I can't see a way to do that using this endpoint.

**Comment by KyleAMathews** [comment]
Is there any reason not to grab the maximum number of posts from Medium every time? Or at least increase the default a lot? I can't imagine the API request getting that much slower and it is annoying to have the default set so low.

But yeah, we should expose this `limit` parameter and then just set the default to a higher number.

To implement the PR, you'd need to add limit to the pluginOptions (second parameter) here:   https://github.com/gatsbyjs/gatsby/blob/a0f0fc67efb02d7a5f3f3e6425e8b34b18fa7f2a/packages/gatsby-source-medium/src/gatsby-node.js#L28

Then set a default e.g. 100, and then document the change in the README.

Would you like to try doing the PR? A guide for setting up a contrib environment is here: https://www.gatsbyjs.org/docs/how-to-contribute/

**Comment by seaburrows** [comment]
Wow, what a response time! 👍 

Yeah, ideally I'd want to grab everything but there doesn't appear to be a parameter for that. I only found the `limit` one by trying different option tbh.

I'll create the PR with a default of 100 as you suggest - thanks!
