### ISSUE TITLE
Problem fetching media data from Strapi API

### ISSUE THREAD

**Issue by P-Pousin** [gatsbyjs/gatsby#6184]
Hi,

I use gatsby-source-strapi to fetch data, i can get Media data directly from the main table but can't access it via relation.

I'll just show an exemple of what i'm trying to accomplish 

```
{
  strapiArticle {
    id
    title
    cover {
      url
    }
  }
}
```

Result

```
{
  "data": {
    "strapiArticle": {
      "id": "5b213b7b7a522a14f87d6a2e",
      "title": "WESS Conference 2018",
      "cover": {
        "url": "/uploads/5ab4a6fa2ac044268f98262307a87921.jpg"
      }
    }
  }
}
```

Here the cover image url is accessible with all the other fields.
When i'm trying to get this same article from his category like this:

```
{
  strapiCategory {
    articles {
      id
      title
    }
  }
}
```

Result

```
{
  "data": {
    "strapiCategory": {
      "articles": [
        {
          "id": "5b213b7b7a522a14f87d6a2e",
          "title": "WESS Conference 2018"
        }
      ]
    }
  }
}
```

I can get all the fields like (id, title, content, tags ... ) except Media fields like cover

```
{
  strapiCategory {
    articles {
      id
      title
      cover {
        url
      }
    }
  }
}
```

Result

```
{
  "errors": [
    {
      "message": "Cannot query field \"cover\" on type \"articles_6\".",
      "locations": [
        {
          "line": 6,
          "column": 7
        }
      ]
    }
  ]
}
```

Am i doing something wrong?

Thanks

**Comment by pieh** [comment]
Hey, can you report this problem in https://github.com/strapi/gatsby-source-strapi (this plugin isn't maintained here) - they will surely have more context on this issue.
