### ISSUE TITLE
Recommended http server?

### ISSUE THREAD

**Issue by thebetterjort** [gatsbyjs/gatsby#6186]
Serve

At the root of a Gatsby site run gatsby serve to serve the production build of the site for testing.'

sounds to me like gatsby serve is only to test the production build. What is recommended to serve it out? Apache, nginx? etc, does anybody have a configuration?

**Comment by jquense** [comment]
You can use whatever server best suits your situation! Nginx is a popular choice in general for static content and there are lot of docker images (if that is convenient for you) and HTML% boilerplate has a good set of "best practice" configs for it for hosting web apps: https://github.com/h5bp/server-configs-nginx

They also have configs for [Apache](https://github.com/h5bp/server-configs-apache) [IIS](https://github.com/h5bp/server-configs-iis) and others
