### ISSUE TITLE
[www] IA redesign: Mobile navigation menu button placement (and icon)

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#6189]
(Following up on #6153) Currently the button to open the documentation/tutorial/features menu on mobile is a direct copy of the reactjs.org implementation, looking like this:

![image](https://user-images.githubusercontent.com/21834/41990370-86657fca-7a42-11e8-8ac8-37607e66c7b9.png)

This works OK, but:

* The button overlaps the "Showcase" mobile navigation item. We could slightly alter the menu button's position to work around that.
* Alternatively, we could move the menu button to the main navigation (and fix the position of the main navigation for mobile):  
  <img width="360" alt="mobile_navigation_more" src="https://user-images.githubusercontent.com/21834/41181475-03731be2-6b72-11e8-9e78-07601eaed58e.png">
  (Please note that the additional "Access the doc navigation…" callout is not in the scope of this issue) That seems to be a quite common pattern, used e.g. in the [Google Developer docs](https://developers.google.com/web/tools/lighthouse/): 
![image](https://user-images.githubusercontent.com/21834/41990903-0c3f21fe-7a44-11e8-9718-a8292a764080.png)
* @shannonbux mentioned that she does not recognize the button icon as a "menu" icon. We could replace the current icon with a "hamburger" icon to resolve that (which the "navigation button in header" already does).

**Comment by shannonbux** [comment]
I think the Google dev docs follow the material design pattern of menus for mobile, so that must be why it's common!

All I know about mobile navigation is that if you want the button to be super easy to get to, putting it at the bottom makes it easier to touch with one's thumb/finger. Also, I just realized that there's a slight chance people could accidentally hit the button when what they really want to do is scroll down the doc. Putting it at the top means it takes slightly more effort to get to it and also means no one would accidentally touch it.

My vote is to do whatever is easier:
* either do the material design thing and use a hamburger menu at the top
* OR do the button at the bottom but make sure it disappears when someone is scrolling? Would that avoid any accidental clicking? Not sure how to make sure it "reappears" at the right time

**Comment by fk** [comment]
> All I know about mobile navigation is that if you want the button to be super easy to get to, putting it at the bottom makes it easier to touch with one's thumb/finger.

👍 Yeah, the position at the bottom def. is ideal for (right-handed ;-)) users.

> OR do the button at the bottom but make sure it disappears when someone is scrolling? Would that avoid any accidental clicking? Not sure how to make sure it "reappears" at the right time

I think accidental clicking while scrolling is less of an issue than the conflict with the current mobile navigation, but that of course is just an assumption.
IMO getting the "hide while scrolling" stuff right is def. harder than changing the button placement.

If it wasn't for the mobile navigation, I would be 💯 pro "docs button at the bottom right" on mobile. The mobile navigation will become an issue as soon as we want the Starter Showcase (or anything else, really) to show up in there, so we might as well think about that in the context of this issue, too.

The mockup in https://github.com/gatsbyjs/gatsby/issues/6189#issue-336330687 shows a "More" button in the mobile navigation as an easy solution to the need of supporting any number of navigation items, but we probably should also think of the alternative: A hamburger icon in the header that opens the _main navigation_. This would allow a placement of the docs/tutorial button on the bottom right on mobile.

That said, I love the current mobile navigation—not (only) for the icons, but for it being so obvious. I won't go and hunt down proof, but IIRC for example Facebook experimented with different types of navigation for their mobile apps and saw a clear benefit of not hiding all navigation behind a hamburger icon. I'm not a heavy user at all, but at least my current version of their app follows the "persistent bottom navigation with icons and 'more' button" similar to the thing I mocked up.

So…I lean towards:

* moving the docs/tutorial-specific nav button to the top and making the header fixed on mobile and
* handling additional top-level nav items via a "more" button (on both mobile and larger screens).

Curious what @KyleAMathews thinks of this.

**Comment by shannonbux** [comment]
I like the idea of a "more" button at the bottom.
What would a docs button look like at the top? Same as React docs but moved
to top?

**Comment by KyleAMathews** [comment]
Done I believe.
