### ISSUE TITLE
[www] IA redesign: Clearer separation of "Tutorial" sections

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#6193]
(Following up on #6153) The current gatsbyjs.org does a better job at this, let's get even:

![image](https://user-images.githubusercontent.com/21834/41992829-d1272200-7a49-11e8-9103-c6947bc1ec18.png)

-- vs --

![image](https://user-images.githubusercontent.com/21834/41993033-6adf9e68-7a4a-11e8-9f94-00fa785246bd.png)

* Add more vertical space in between tutorial sections:  
  ![image](https://user-images.githubusercontent.com/21834/41992956-3a89d5f8-7a4a-11e8-8165-9726b1a28fb9.png)
* Consider `font-weight: bold`

**Comment by fk** [comment]
I'd say we hold off on this until @shannonbux/we get a first shot at the new docs/tutorial structure in—maybe we will use accordions for different tutorial parts and don't need to treat the layout of this specific sidebar/menu in a special way.

@shannonbux Please take a look at https://github.com/gatsbyjs/gatsby/pull/6153#issuecomment-401030834 and see if that makes sense to you!?

**Comment by shannonbux** [comment]
In a usability test yesterday, the user commented that seeing the entire
main tutorial with all it's parts looked intimidated on first glance. So
collapsing the parts could help with both making things looks less
intimidating and also allowing people to see that there are other
tutorials, not just the main one (is that what you are both suggesting, @fk
and @calcsam? To put more tutorials in the same menu as the main tutorial
at /tutorial?)

**Comment by calcsam** [comment]
Yes, it seems like "everything collapsed except the first section, which is expanded" is a good first take, and we can proceed from there.
