### ISSUE TITLE
warning "gatsby has incorrect peer dependency

### ISSUE THREAD

**Issue by thebetterjort** [gatsbyjs/gatsby#6199]
[3/4] Linking dependencies...
warning "gatsby > babel-loader@8.0.0-beta.0" has incorrect peer dependency "webpack@2 || 3".
warning "gatsby > babel-plugin-remove-graphql-queries@2.0.2-beta.4" has incorrect peer dependency "graphql@^0.11.7".
warning " > gatsby-link@1.6.45" has incorrect peer dependency "gatsby@^1.0.0".
warning " > gatsby-plugin-emotion@1.1.17" has incorrect peer dependency "gatsby@^1.0.0".
warning " > gatsby-plugin-styled-components@2.0.11" has unmet peer dependency "babel-plugin-styled-components@>1.5.0".
warning " > gatsby-plugin-styled-components@2.0.11" has incorrect peer dependency "gatsby@^1.0.0".
warning " > gatsby-plugin-typography@1.7.19" has incorrect peer dependency "gatsby@^1.0.0".
warning " > gatsby-react-router-scroll@1.0.18" has unmet peer dependency "react-router-dom@^4.0".
warning "react-emotion > create-emotion-styled@9.2.3" has unmet peer dependency "prop-types@15.x".

Is there a way to eliminate these warnings?

**Comment by pieh** [comment]
Hey, some of those are from using `gatsby` v2 beta with v1 plugins, some are from dependencies we don't really have control over, but some of the we can fix and will do so.

In any case those are warnings, not errors.
