### ISSUE TITLE
Re-organise GitHub teams

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#6204]
## Summary

Make use of GitHub's team nesting feature

### Basic example

GitHub allows organisation teams to be nested. https://blog.github.com/2017-06-13-nested-teams-add-depth-to-your-team-structure/

The nested team structure should look like:

| Team hierarchy | Access level  | Description
|---|---|---|
| Maintainers  | Write | All maintainers
| --Admin  | Admin | Admin-level maintainers
| ----Inkteam  | Admin | Official team members of Gatsby Inc

### Motivation

This avoids needing to add or remove people to multiple teams.

**Comment by KyleAMathews** [comment]
This is done I believe.
