### ISSUE TITLE
Use @babel/core#parse instead of @babel/parser#parse

### ISSUE THREAD

**Issue by dennari** [gatsbyjs/gatsby#6206]
## Summary
Gatsby parses a project's source files multiple times:
1. To load the possible configuration files (e.g. `gatsby-node.js`)
2. To parse the GraphQL queries
3. To generate the javascript that's run on the site (through Webpack and babel-loader)

Cases 1. and 2. use `@babel/parser` with a hardcoded set of *parser* plugins (different from `babel-plugin-x`). Ideally, they would use the same configuration mechanism as 3 (custom `.babelrc` for example). There's a separate, recently added and so far undocumented, [`parse`](https://github.com/babel/babel/pull/7291) method in `@babel/core` which would allow exactly this.

### Motivation

This would allow, for example, using TypeScript, or any other compile-to-js language supported by Babel, in the configuration files. It would also simplify plugins like `gatsby-plugin-typescript`, which wouldn't need to implement the `preprocessSource` api.

Here's a similar discussion in the babel-eslint project: https://github.com/babel/babel-eslint/issues/573

**Comment by KyleAMathews** [comment]
Done in v2 I believe.
