### ISSUE TITLE
[www] IA redesign: Improve mobile navigation UX/UI

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#6215]
(Following up on #6153, extracted from #6190) IMO we want to extend the sidebar behavior to

- make the navigation dismissable…
  - when hitting the "escape" key
  - when tapping/clicking outside of the menu
- add an overlay that darkens the page background and blocks clicks on elements there/indicates that they will not respond to user interaction; see e.g. https://developers.google.com/web/tools/lighthouse/

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
