### ISSUE TITLE
Yarn support in Plugins Page

### ISSUE THREAD

**Issue by deadcoder0904** [gatsbyjs/gatsby#6216]
As yarn isn't going anywhere & I think most people use that, so yarn support on the plugin website might be good.

Checkout https://next.gatsbyjs.org/packages/gatsby-plugin-emotion/

A tab which selects yarn or npm might be helpful for most for directly copy-pasting commands into terminal

**Comment by LeKoArts** [comment]
npm is integrated in Node (which is a requirement) so all are on the same page. People just starting in the JS business won’t know yarn.

People using yarn just copy an extract of that line. That’s not a problem at all in my opinion.

**Comment by deadcoder0904** [comment]
Yep I know that people familiar with `yarn` know `npm` very well, but when I have `npm` & `yarn` both installed, Gatsby default installs with `yarn`. I just checked :)

So for experienced programmers, directly a copy-paste snippet from the website supporting `yarn` is a huge time-saver as people care about seconds 😂

The thing is nobody in the world who will try Gatsby once will go back to using something else. And people are making lots of websites with it so it gets kinda boring after a while to copy `npm` snippet then delete `npm install --save` & add `yarn add`. 

Also, with v2 as plugins are separated, people won't be typing but copy-pasting. Also, a copy button would be nice.

Its not an issue, but a feature great to have :)

**Comment by m-allanson** [comment]
I agree a copy button would be nice to have - there's [an issue to add that to the tutorials](https://github.com/gatsbyjs/gatsby/issues/5030).

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by deadcoder0904** [comment]
I think this should be re-opened bcz lots of people use yarn due to weird bugs npm faces from time to time

**Comment by KyleAMathews** [comment]
NPM is the default. We might add a way to choose to see yarn instructions instead of NPM but we're not going to work on this right now.

**Comment by deadcoder0904** [comment]
Sure no problem. Maybe add a label on such issues something like fix-later or something so someone can take it at a later point in time. Also, would be helpful for beginners to contribute to issues like this :)
