### ISSUE TITLE
Grids and multiple layouts?

### ISSUE THREAD

**Issue by dhatcode** [gatsbyjs/gatsby#622]
What's the proper way to integrate any grid in layout/template? Should I edit md.js wrapper for this? 

How can I have multiple layout option and how to switch between them right from markdown file?

What "layout: post" in all markdown files mean? Can I change layouts? How to manage them, where are they stored? Is there any other layouts beside "post"?

**Comment by KyleAMathews** [comment]
Hrrmm... the layout stuff in the frontmatter (for the starter-blog) were leftover from older version of things — I just removed them. They weren't being used for anything atm.

So you want to have multiple layouts for posts?

One way you can do that is add a `layout: 'MY_LAYOUT'` in your markdown files then in your md.js render function, check what layout is set and then return a different component e.g.

```js
if (post.data.layout === `post`) {
  return <PostLayout {...post} />
} else if (post.data.layout === `something-else`) {
  return <SomethingElse {...post} />
}
```

You might want to check out this issue as well https://github.com/gatsbyjs/gatsby/issues/605

**Comment by dhatcode** [comment]
Then I must move post.body to that Components? Or what will be in md.js return()?

The problem is I can't do that. It always send me an error. That markdown workflow is pretty confusing when it comes to custom configuration.

Why do I need that wrapper in first place if I will be using such code?

`if (post.data.layout === `post`) {
  return <PostLayout {...post} />
} else if (post.data.layout === `something-else`) {
  return <SomethingElse {...post} />
}`
