### ISSUE TITLE
Change page creation examples to use require.resolve

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#6222]
It's simpler as you can easily do it inline + similar to doing local resolves.

**Comment by m-allanson** [comment]
I'm not sure what this involves, is it a change across all the docs? Can you give a _before_ and _after_ example?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
