### ISSUE TITLE
A way to pass custom functions to gatsby-plugin-sass

### ISSUE THREAD

**Issue by thorn0** [gatsbyjs/gatsby#6234]
## Summary

`node-sass` supports [custom functions](https://github.com/sass/node-sass#functions--v300---experimental), but there seems to be no way to pass them to `gatsby-plugin-sass`.

### Basic example

As [the docs](https://www.gatsbyjs.org/docs/plugins/) of `gatsby-plugin-sass` say:

> Note that plugin options will be stringified by Gatsby, so they cannot be functions.

This means we can't pass this option directly like it can be done with `precision`. We have to specify a module name and load it like `gatsby-plugin-typography` does. So it might look like this:

```js
plugins: [
  {
    resolve: `gatsby-plugin-sass`,
    options: {
      pathToCustomFunctionsModule: 'src/utils/sass-custom-fuctions',
    },
  },
]
```

### Motivation

I'd like to use plugins like https://github.com/bugsnag/chromatic-sass in my SASS files.

**Comment by jquense** [comment]
v2 should already support this! It's a bit tough to make work in gatsby v1 though given the old version of webpack :/

**Comment by thorn0** [comment]
At least I'm fine for now. It turns out there is a pure SASS alternative to chromatic-sass: https://github.com/xi/sass-planifolia

**Comment by m-allanson** [comment]
It sounds like this is resolved for now. Please open a new issue if that's not the case.
