### ISSUE TITLE
[v2] importing browser-only code in gatsby-browser.js throws an error on build

### ISSUE THREAD

**Issue by szimek** [gatsbyjs/gatsby#6235]
## Description

I'm importing a script in `gatsby-browser.js` that, when imported, runs some code that uses `document.location.hostname`: 
```js
import { cid, analytics } from '@freeletics/tracking'; // this calls `document.location.hostname` when imported

export const onClientEntry = () => {
  ...
}
```
This causes an error when running `gatsby build`:
```
success Building production JavaScript and CSS bundles — 16.087 s
error UNHANDLED EXCEPTION


  ReferenceError: document is not defined

  - render-page.js:44102
    /Users/.../blog/public/render-page.js:44102:21
```

I'm using 2.0.0-beta.13. It worked fine in v1.

### Steps to reproduce

Import any code in `gatsby-browser.js` that runs browser-only code.

### Expected result

Doesn't throw an error.

### Actual result

Throws an error.

### Environment

System:
    OS: macOS High Sierra 10.13.5
    CPU: x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Chrome: 68.0.3440.42
    Firefox: 61.0
    Safari: 11.1.1
  npmGlobalPackages:
    gatsby-cli: 1.1.52
    gatsby-dev-cli: 1.2.12

**Comment by KyleAMathews** [comment]
@pieh is this perhaps related to your recent page-renderer change?

**Comment by pieh** [comment]
Yeah, importing `loader.js` in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/cache-dir/public-page-renderer-prod.js would cause this

**Comment by KyleAMathews** [comment]
Yeah... this keeps happening now and then. I wonder if we shouldn't just alias all that stuff to null during SSR.

**Comment by tizzle** [comment]
Hey,
i'm running into the same issue. Trying to build a v2 app with complex client routes is not possible.
