### ISSUE TITLE
Add more directives to sign up for the newsletter

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#6236]
The newsletter is great but we don't have a signup form or link in that many places. @shannonbux and I were just doing a usability test and asked the person to try signing up and they couldn't figure it out.

- [ ] we should have a dedicated page for signing up for the newsletter that we can link to (#4943)
- [ ] add a signup form on the frontpage
- [ ] link to the page from the top of the blog index
- [ ] link to the page from the community page

Edit by @m-allanson: added a link to #4943

**Comment by benoiteyver** [comment]
a dedicated landing page would be easier for tracking purposes but there is only one field (email address), and you'll make the user wait for the page with 1-field form to load (I know GatsbyJS is lightening fast ;-) but still...,you're requiring one more step, so might not be great for usability).
 
Yes this sign-up should be more visible. If it were me I would gave a *sticky/floating* sign-up form at the top right of each post (so even when people scroll down the post they can still see the sign-up form). 
overall: site conversion rate is very low. 0.07% newsletter subscription per  gatsby.org user... without being aggressive we should be able to get to 3%.

Happy to set up google optimize to test different options,  but there are tons of literature on what works best including the color of the buttons ...

**Comment by benoiteyver** [comment]
check with Sam, Kyle or Linda on this. Sam just asked me to add my thoughts. Attached what in my experience would have the best conversion UX wise. Basically the "sticky/floating" characteristic makes sure that the subscription form always remain in view while the the blog post reader is skimming through the post
![blog post and newsletter subscription banners](https://user-images.githubusercontent.com/11895894/42188099-64a8f7c2-7e07-11e8-9d07-25d85323ff33.png)

**Comment by wuweiweiwu** [comment]
@KyleAMathews I'd love to pick this up! :)

**Comment by m-allanson** [comment]
That's great @wuweiweiwu! Although I may have been a bit eager with the "help wanted" label. I think this still needs a bit of work to define what should be done. 

@KyleAMathews maybe adding the dedicated signup page is a safe bet, while the rest of the changes are worked out?

**Comment by shannonbux** [comment]
Would it make sense to have a dedicated page and then later add the sticky
banners, as Benoite suggests? I think the banners will work much better
because clicking to another page would probably annoy a lot of people.
However, having a dedicated page could be really useful for linking to in
the future (say someone on Twitter asks how to sign up).

If it makes sense to have both, then we could do the dedicated page first
and link to it from the places Kyle suggests, then do the banners asap
after that.

**Comment by shannonbux** [comment]
*to be clear, my first question should read: would it make sense to have
both a dedicated page and sticky banners?

**Comment by wuweiweiwu** [comment]
I'd be willing to take this up when the details are fleshed out!

**Comment by shannonbux** [comment]
Sounds awesome @wuweiweiwu! Seems like we need to hear more about @KyleAMathews 's reasoning behind having a dedicated page and then it'll be easier to decide which step to take first!

**Comment by KyleAMathews** [comment]
Let's start with a dedicated page because that's an easy next step. We could then tweet about it—which we've never done—plus link to it from a few places like the community page where having a dedicated form wouldn't make sense.

**Comment by KyleAMathews** [comment]
@wuweiweiwu so would love your help! Please submit a PR with the new page when you have a chance!

**Comment by m-allanson** [comment]
@wuweiweiwu Here's a few notes that might (or might not 😄) be helpful. There's a very rough example page layout at #4943. You could make use of the [existing `EmailCaptureForm` component](https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/email-capture-form.js), and I guess this should be created as a new top-level page, so the URL would be gatsbyjs.org/newsletter.

Drop a line here if you've any questions!

**Comment by wuweiweiwu** [comment]
Will do!
