### ISSUE TITLE
SEO with Gatsby - Helmet don't set title and meta tags

### ISSUE THREAD

**Issue by flavioalves** [gatsbyjs/gatsby#6237]
## Description

I'm building a multi-language website using gatsby-plugin-react-helmet, react-helmet, and react-i18next.

I created the same structure of [this official blog post](https://www.gatsbyjs.org/blog/2017-10-17-building-i18n-with-gatsby/) and I've got the things apparently working well. 

But, the strange part is that my "SEO metadata" isn't been found by SEO analyzers and link previews, as it is supposed to do. 

When I check on my browser inspect I can found the meta tags, but seems that it is loaded on the client side and not on SSR.

### Steps to reproduce
I create a SEO component following the same idea of the [exemple listed here](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/seo.md).

My i18n component (same idea of the post) 
```javascript
const options = {
  fallbackLng   : "en",
  whitelist     : ["en", "pt"],
  ns            : ["translation"],
  defaultNS     : "translations",
  debug         : false,
  interpolation : {
    escapeValue : false
  },
  react         : {
    wait : true
  }
}

i18n
  .use(Backend)
  .use(LanguageDetector)
  .use(reactI18nextModule)
  .init(options)
```

Loading all namespaces before render: 
```javascript
exports.replaceRenderer = ({ bodyComponent, replaceBodyHTMLString }) => {
  i18n.loadNamespaces(NAMESPACES, () => {
    replaceBodyHTMLString(bodyComponent)
  })
}
```

And gatsby-plugin-react-helmet should handle the SSR aspects.

I tested with fixed data (not loaded from a locale file) and it works well.

Do you guys could help me with this? Any guess?

Thanks in advance!

**Comment by flavioalves** [comment]
Hey guys, some updates about what I'm trying to do to fix it.

I change my i18next init options adding:

```javascript
  backend       : {
    loadPath    : '/locales/{{lng}}/{{ns}}.json'
  }
```
Add some console logs on my `gatsby-ssr.js` to the `i18n.loadNamespaces` function running, so I got the following log on server:

```
5:00:29 PM: >>> Copying locales - production mode
5:00:49 PM: success Building CSS — 20.131 s
5:01:21 PM: success Building production JavaScript bundles — 31.960 s
5:01:33 PM: >>> gatsby-ssr - replaceRenderer
5:01:33 PM: i18next::backendConnector: loading namespace translation for language en failed failed parsing /locales/en/translation.json to json
5:01:33 PM: i18next::backendConnector: loading namespace aboutUs for language en failed failed parsing /locales/en/aboutUs.json to json
...
5:01:34 PM: >>> gatsby-ssr - loadNamespaces
5:01:34 PM: i18next: languageChanged en
5:01:34 PM: i18next: initialized { debug: true,
...
```

So we can see that: 

1. My locale files are correctly added in /public/locales
2. The `replaceRenderer  in gatsby-ssr.js` ran correctly
3. I got a `failed parsing` messages when the locale files was loaded in `i18n.loadNamespaces`
As the debugger option is enabled in i18next we can see the files loaded correctly in chrome console:

```
i18next::backendConnector: loaded namespace translation for language en {lang: "en", seo: {…}}
VM129 component---src-layouts-framed-layout-js-e77b096dcada2d96febc.js:2 i18next: languageChanged en
VM129 component---src-layouts-framed-layout-js-e77b096dcada2d96febc.js:2 i18next: initialized {debug: true, initImmediate: true, ns: Array(4), defaultNS: "translation", fallbackLng: Array(1), …}
VM129 component---src-layouts-framed-layout-js-e77b096dcada2d96febc.js:2 i18next::backendConnector: loaded namespace Menu for language en {services: "Services", projects: "Projects", about-us: "About us", blog: "Our blog", phone: "say hello", …}
```

I published a public version of this PR at [this link](https://fix-seo--novatics.netlify.com/). As you can see,  the locales are available if you try to access by the URL [/locale/en/translation.json]( /https://fix-seo--novatics.netlify.com/locales/en/translation.json).

You guys have any guess about is happening here and how can I fix it?

**Comment by flavioalves** [comment]
@m-allanson  After doing some tests I believe that it's a bug related with gatsby and helmet.
Even using strings rather than i18n params the tags aren't correctly been added in the head section during SSR. 
Looking to the source I can see just an empty title tag.
```
 <title data-react-helmet="true"></title>
```

I'm using on my package the following versions:
```
  "gatsby": "^1.9.246",
  "gatsby-plugin-react-helmet": "^2.0.3",
  "react-helmet": "^5.2.0"
```

**Comment by m-allanson** [comment]
It's difficult to tell what the issue might be without running the code... are you able to create a small demo repo with this issue?

**Comment by wiziple** [comment]
I had a similar issue with i18next with SSR and spent a lot of time.
After all, I solved the issue by switching to `react-intl`.
Check this out if you want to look into my approach. 
https://gatsby-starter-default-intl.netlify.com/

**Comment by solarsailer** [comment]
Hello,

I have the same issue, without any i18n. 

React-Helmet works well on the browser-side, but it's completely ignored by the SSR. 

So if I traverse the site, it works fine, but if I hit refresh, all the meta set by Helmet are then ignored.

I don't have a complex website, so I don't see what I'm missing.

List of plugins that I use (I'm still on Gatsby 1.x):

```
  {
    resolve: 'gatsby-source-filesystem',
    options: {
      path: `${__dirname}/content/posts`,
      name: 'posts'
    }
  },
  {
    resolve: 'gatsby-plugin-nprogress',
    options: {
      color: '#f1c40f',
      showSpinner: false
    }
  },
  {
    resolve: 'gatsby-transformer-remark',
    options: {
      plugins: [{resolve: 'gatsby-remark-prismjs'}]
    }
  },
  {
    resolve: 'gatsby-plugin-google-analytics',
    options: {
      trackingId: 'UA-41853457-1'
    }
  },
  'gatsby-plugin-sitemap',
  'gatsby-plugin-feeds',
  'gatsby-plugin-styled-components',
  'gatsby-plugin-react-helmet',
  'gatsby-plugin-react-next',
  'gatsby-plugin-lodash'
```

I'll try to create a simple test repo next week.

Cheers.

**Comment by smakosh** [comment]
here's my custom SEO component: https://github.com/smakosh/smakosh.com/blob/master/src/components/common/Head/index.jsx

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
