### ISSUE TITLE
I copy the build result to ampps/www/my-site but the links not work

### ISSUE THREAD

**Issue by Jatapiaro** [gatsbyjs/gatsby#6239]
## Summary

I copy the build result to ampps/www/my-site but the links not work. I want to create a static site using Gatsby.

## Relevant information

I just create a new app with the gatsby-cli, then run the build command and copy all the content to my apache server under ampps/www/my-site and test if that works. I just want to do a SSR site, but altought I check the documentation there is no a real example of how to do it.

Thanks

**Comment by KyleAMathews** [comment]
Hey, it sounds like either your apache config or how you copied in the build files is wrong. If you want to test a new Gatsby site build, run `gatsby build` then `gatsby serve`

**Comment by Jatapiaro** [comment]
Don't close the issue!
I just grab all the files inside the build folder and move it to my apache site. I don't have the possibility to run a serve in the production serve.

**Comment by pieh** [comment]
If apache serves `ampps/www/my-site` as `http://localhost/my-site` you need to use [path-prefix](https://www.gatsbyjs.org/docs/path-prefix/), by default gatsby assume it will be hosted at root of domain.

**Comment by Jatapiaro** [comment]
Thanks @pieh that works amazing for me! I really apreciate your help!
