### ISSUE TITLE
Does gatsby use plugin ssr over local, or the other way around?

### ISSUE THREAD

**Issue by JigzPalillo** [gatsbyjs/gatsby#6242]
I found this phrase confusing, the Debugging replaceRenderer API page says...

> Note that default-site-plugin refers to your local gatsby-ssr.js file, if this file exists **it will always be used in favor of gatsby-ssr.js from other plugins**.

Which is it? **it(local) will always be used** / **in favor of gatsby-ssr.js from other plugins** If local, then shouldn't it say...

> Note that default-site-plugin refers to your local gatsby-ssr.js file, if this file exists it will always be used **at expense** of gatsby-ssr.js from other plugins.

https://www.gatsbyjs.org/docs/debugging-replace-renderer-api/

**Comment by m-allanson** [comment]
Thanks @JigzPalillo, I _think_ the intent is the same with both sentences. How about we restructure that line a bit - does this read more clearly?

> Note that `default-site-plugin` refers to your local `gatsby-ssr.js` file. Gatsby will always use your local `gatsby-ssr.js` file instead of the `gatsby-ssr.js` file from any plugins.

**Comment by LekoArts** [comment]
Has been merged since
