### ISSUE TITLE
gatsby-plugin-page-creator breaks StaticQuery/graphql

### ISSUE THREAD

**Issue by VictorChen** [gatsbyjs/gatsby#6244]
Perhaps I'm using [`gatsby-plugin-page-creator`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-page-creator) wrong, but when I hook it up, the site gets stuck with:

```
Loading (StaticQuery)
```

I installed `gatsby-plugin-page-creator`, renamed `src/` to `docs/` and updated `gatsby-config.js` with:

```
{
  resolve: `gatsby-plugin-page-creator`,
  options: {
    path: `${__dirname}/docs/pages`,
  },
},
```

The site stopped working after that. Here's a reproducer:

https://github.com/VictorChen/gatsby-bug

**Comment by KyleAMathews** [comment]
This is a known bug which unfortunately isn't fixed yet. Sorry about that! Hopefully will get it solved soon https://github.com/gatsbyjs/gatsby/issues/5473
