### ISSUE TITLE
Warnings in gatsby-starter-documentation

### ISSUE THREAD

**Issue by UsulPro** [gatsbyjs/gatsby#625]
Hi!
I have this warnings when running `gatsby develop` with `gh:gatsbyjs/gatsby-starter-documentation`

steps to reproduce:

```shell
gatsby new docs-site gh:gatsbyjs/gatsby-starter-documentation
cd docs-site
gatsby develop
```

and then I have:

```
...
[534] ./~/webpack/buildin/module.js 251 bytes {0}

WARNING in (webpack)/buildin/module.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in ./~/webpack/buildin/module.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
```

I run it with
Windows8
node v6.3.1
npm 4.0.5
gatsby@0.12.27

**Comment by KyleAMathews** [comment]
@UsulPro it looks like this could be the problem — could you try to find which require is using the wrong case? https://github.com/webpack/webpack/issues/382

**Comment by KyleAMathews** [comment]
@UsulPro any updates on this?

**Comment by UsulPro** [comment]
Oh @KyleAMathews , sorry I missed your first reply
Actually this is a specific Node v6 for Windows issue. This is no longer in the 6.9.4 (and 7) version.

Maybe it could be usefull for node v6.3.1 users:
Take care that in your current dir the drive letter was in Capital case like:
`D:\path\to\project`. 
But not `d:\path\to\project`.
You can switch it by `cd D:\` and `cd \path\to\project`
