### ISSUE TITLE
Filter items by type dynamically.

### ISSUE THREAD

**Issue by NaderIkladiousC** [gatsbyjs/gatsby#6262]
Hello,

It's a great framework and really amazed by what could be accomplished in small time.

Yet I have a question regarding dynamic filtering from a page state.

this is the state to be updated by an event handler
``` javascript
state = {
    filter: ''
}
```
This is the query
```javascript
export const query = graphql`
  query getAllItems ($type: String) {
    alltems (filter:{type:{eq: $type}}) {
      edges {
        node {
        	id
        	title
        	type
        	description	
        }
      }
    }
  }
`
```
How do I make it dynamic so when the user choose a different filter it changes the data.

Thanks in advance.

**Comment by pieh** [comment]
Query results are not dynamic - they are constructued at build time. So you have to query all items (without filter) and do filtering with javascript in runtime in your component
