### ISSUE TITLE
Caching external GraphQL resources

### ISSUE THREAD

**Issue by falconmick** [gatsbyjs/gatsby#6266]
I was wondering if it is possible to cache a GraphQL resource as a file checked into source control and then use it as a fallback for if an external resource (GraphQL) is either unavailable or hits a resource limit. Is this something that the plugin author would need to include in their plugin?

The usecase is a OS blog that queries Github for contributors to an article. I just worry that as the repository ages and more and more commits start to exists that I could hit resource limmits

**Comment by KyleAMathews** [comment]
Yeah, you could write a custom plugin which does this. It could save the remote data to a local json file and then only query the remote API for new or updated content. This isn't something built into Gatsby or generally into plugins.

Good luck!

**Comment by falconmick** [comment]
@KyleAMathews cheers, would the monorepo's github accept a PR /w this feature under an option (default turned off)
