### ISSUE TITLE
[www][v1] Link to next.gatsbyjs.org

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#6276]
I had the honor to participate in a UX interview conducted by @shannonbux today 🎉and the interviewee mentioned that he used Google search to find the documentation for Gatsby v2.

My guess is that adding a banner similar to the one on https://next.gatsbyjs.org/ would resolve that issue. Do we want to push v2 and its docs this way (and at this point)?

/cc @KyleAMathews @m-allanson @pieh @calcsam

**Comment by shannonbux** [comment]
Yes, he also mentioned trying to navigate to next.gatsbyjs.org by
navigating to gatsbyjs.org and then adding "next." into the URL, which
doesn't work. https://www.next.gatsbyjs.org/ returns an error.

Is that worth making an issue about? We could somehow redirect people if
they try to do that?

**Comment by KyleAMathews** [comment]
Makes sense! We're getting closer to v2 so good to start pushing people that way. Also seen a number of questions from people wondering how to try out v2 so it's definitely not obvious right now.

**Comment by m-allanson** [comment]
If anyone would like to take this on, you'd need to check out the `v1` branch of this repo. Then check these two PRs to see how the banner is implemented on next.gatsbyjs.org:

https://github.com/gatsbyjs/gatsby/pull/6161
https://github.com/gatsbyjs/gatsby/pull/5915

A "stretch goal" would be to a configurable standalone component (or local plugin?) and then port that back to the `v1` branch.

**Comment by shannonbux** [comment]
@martynhoyer this is what we talked about in our chat today!

**Comment by fk** [comment]
I'm up for this, and would try the "stretch goal".

I'm happy to give the local plugin a shot, too, but wondering what the benefits of this over a component would be?

Also I've been thinking about the copy that we'd need for the v1 site—I'm thinking it'd need to be a little longer than what we currently have for v2 at https://next.gatsbyjs.org/:

![image](https://user-images.githubusercontent.com/21834/42462611-113e0d0a-83a4-11e8-8b76-b8c32b60876e.png)

Even for that very concise message, we're currently hiding parts to make things fit on a 320px-wide screen to avoid all those `position:fixed` problems with the header:

![image](https://user-images.githubusercontent.com/21834/42462717-52c19abc-83a4-11e8-867d-6fe68c89e152.png)

For v1, I'm thinking the message could be s/th along the lines of "We're working hard on Gatsby v2—head over to next.gatsbyjs.org for the v2 docs and read the [v2 beta blog post](https://www.gatsbyjs.org/blog/2018-06-16-announcing-gatsby-v2-beta-launch/)!". What do people think about this?
To make things fit on mobile/320px-wide screens, we could break that down to just "v2 beta docs / blog post", but maybe we should think about how to handle either any amount of "one-line content" or _really any amount of content_ here.

**Comment by m-allanson** [comment]
> I'm happy to give the local plugin a shot, too, but wondering what the benefits of this over a component would be?

I guess my thinking behind this was - to be able to switch the banner on and off without needing to go through and edit CSS in the files that need to know the header height. But I'm not sure that that's a good idea, as it doesn't particularly make things clearer.

**Comment by munwr** [comment]
Oops,... I was late by 7 hours

**Comment by fk** [comment]
👋Hey @munwr, thanks for looking into this! 🤗 

#6363 is just moving the banner to a component for `www` on `master`, so no reason to abandon your PR (#6370)! I won't get back to this for at least the next 24hrs. Would be 💪 if you could port the component from #6363, but that's nothing to hold off #6370 either (IMO)!

**Comment by munwr** [comment]
Hi,
We are saying in banner "view docs", But linking it to respective version's home page. Would it be better if we can directly land them in their respective docs?

@fk @shannonbux

**Comment by shannonbux** [comment]
ah, good point. I'd say let's link to the docs, since the homepage is
exactly the same on each version of the site. This shows how language is
confusing because "the docs" could either refer to the whole gatsbyjs.org
site OR just gatsbyjs.org/docs/.

@fk, what do you think?

**Comment by jlengstorf** [comment]
Maybe the banner should say:

> Gatsby v2 is now in beta! [Try out v2 today.](https://next.gatsbyjs.org/)

What do you think?

**Comment by shannonbux** [comment]
I think I would expect that link to go straight to the migration guide. If we did that, we'd want to edit the migration guide to say something at the top like "Note: this entire site is on next.gatsbyjs.org, the v2 docs site. See v1 docs here". This would help people who don't see the banner. 

How much longer will we have next.gatsbyj.org? It will be nice when we don't have 2 sites...

**Comment by jlengstorf** [comment]
Oh, good call @shannonbux!

I agree that we should link to <https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/>

How about this text?

> Gatsby v2 is now in beta! [Upgrade to v2 today.](https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/)

**Comment by shannonbux** [comment]
Sounds good!

**Comment by shannonbux** [comment]
PS we just merged a PR so there will be a category called "Migrations &
Versions" as soon as that builds on next.gatsbyjs.org so it ought to be way
easier to find :)

**Comment by shannonbux** [comment]
Hm, just thinking what if we link to both the docs and migration guide like
so:

Gatsby v2 is now in beta! Upgrade to v2 today
<https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/> and visit the v2
docs site <https://next.gatsbyjs.org/>.

**Comment by KyleAMathews** [comment]
Hmm both don't seem necessary because the migration guide is in the middle of the docs.

**Comment by shannonbux** [comment]
Well, people might not notice the beginning of the URL changed so the link
isn't so much for them to click, but just to clue them in on the fact that
they're going to a new site...that looks essentially identical ;).

So maybe "Gatsby v2 is now in beta! Upgrade to v2 today
<https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/> (link will take
you to v2 docs site)" or something like that

**Comment by munwr** [comment]
Point to migration guide directly would be very helpful. Someone is already using v1. this could be the right place for them to start. if they are looking to migrate to v2. 


> So maybe "Gatsby v2 is now in beta! Upgrade to v2 today
<https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/> (link will take
you to v2 docs site)" or something like that

**Comment by jlengstorf** [comment]
I think @munwr makes a good point: many people who see that banner will be migrating sites, and anyone who isn't will be looking at the v2 docs after clicking through.


Maybe we could add a call out at the top of the migration guide, like, "Starting from scratch? Follow the tutorial to get started with Gatsby V2!"

That could help give a thread to follow for new users while emphasizing the upgrade path. 

What do you think?

**Comment by shannonbux** [comment]
Yeah, that sounds great @jlengstorf! Just did it in this commit
https://github.com/gatsbyjs/gatsby/commit/0933d6035cb5182c9818c4f41bed114eeceb2df7

though maybe it could be more obvious.

**Comment by KyleAMathews** [comment]
Done!
