### ISSUE TITLE
🗺 v2 sourcemaps not working (totally NOT styled-components related)

### ISSUE THREAD

**Issue by shelldandy** [gatsbyjs/gatsby#6278]
### Steps to reproduce

Start a new Gatsby project on v2

### Expected result

Sourcemaps show original file names/code to debug (at least in development)

### Actual result

![screen shot 2018-07-03 at 11 54 48 am](https://user-images.githubusercontent.com/7088511/42233715-e962c460-7eb7-11e8-8cb9-917549c12a81.png)

Sourcemaps shown already compiled code 🤔 

### Environment

```
  System:
    OS: macOS High Sierra 10.13.5
    CPU: x64 Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
    Shell: 2.7.1 - /usr/local/bin/fish
  Binaries:
    Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.1.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 58.0
    Safari: 11.1.1
  npmPackages:
    gatsby: ^2.0.0-beta.21 => 2.0.0-beta.21
```

**Comment by giraffesyo** [comment]
I have styled components working here, but I'm not using the gatsby plugin. I'm wondering, do you also have the package `styled-components` added? It's a peer dependency now. 

> v2.0.1
styled-components is moved to a peer dependency. Installing the package alongside gatsby-plugin-styled-components is now required. Use npm install --save styled-components

**Comment by shelldandy** [comment]
Yes it's added, i mean styled-components work, sourcemaps dont

**Comment by shelldandy** [comment]
Since the styled-components plugin doesn't change any webpack config i think this is an issue with gatsby v2 purely I fixed it as follows:

```js
exports.onCreateWebpackConfig = ({ stage, actions }) => {
	if (stage === 'develop') {
		actions.setWebpackConfig({
			devtool: 'cheap-module-source-map'
		});
	}
};
```

That way the sourcemaps are properly loaded:

![screen shot 2018-07-04 at 1 34 57 pm](https://user-images.githubusercontent.com/7088511/42291074-181985c8-7f8f-11e8-9ea7-6b66400fe385.png)

I went with `cheap-module-source-map` since that's what [`react-scripts` is doing](https://github.com/facebook/create-react-app/blob/26f701fd60cece427d0e6c5a0ae98a5c79993640/packages/react-scripts/config/webpack.config.dev.js#L80)

**Comment by shelldandy** [comment]
So now I think this could become a bug hunt for v2 towards why aren't sourcemaps properly loading to begin with???

🤔

**Comment by shelldandy** [comment]
But major props to the fact that as users we can tweak and fix those inner configs ourselves!

Top reason I choose Gatsby!

**Comment by shelldandy** [comment]
Any thoughts @giraffesyo 😮 ?

**Comment by shelldandy** [comment]
I thought initially that was related but later on discovered its not.

I've updated the title and original description to be more fit @giraffesyo

**Comment by KyleAMathews** [comment]
Do sourcemaps not work for any parts of Gatsby v2? Or is this a styled-components specific issue?

**Comment by shelldandy** [comment]
Any parts of Gatsby v2, you can open it up on Chrome Developer tool and for example this non-styled-components non-react just vanillaJS code looks like that:

![](https://user-images.githubusercontent.com/7088511/42233715-e962c460-7eb7-11e8-8cb9-917549c12a81.png)

When it should look like this:

![](https://user-images.githubusercontent.com/7088511/42291074-181985c8-7f8f-11e8-9ea7-6b66400fe385.png)

(It looks like that after I apply the fix on `gatsby-node.js`

**Comment by wking-io** [comment]
This was a problem back in v1 and @KyleAMathews fixed it here: https://github.com/gatsbyjs/gatsby/pull/812/commits/f5191a0b7159ea8152340eb9c83809ad6cc5db40

However, it looks like the same issue is back on v2: https://github.com/gatsbyjs/gatsby/blob/ad142af473fc8dc8555a5cf23a0dfca42fcbbe90/packages/gatsby/src/utils/webpack.config.js#L256
