### ISSUE TITLE
gatsby-source-contentful : graphql not having option to apply "in" filter into query

### ISSUE THREAD

**Issue by sachingvit** [gatsbyjs/gatsby#6279]
I am working on one template where I am having multiple products slugs and using them I want to fetch products. While I search on internet I found solution to use "in" into filter.

Same I am trying but no luck

<img width="960" alt="screenshot 22" src="https://user-images.githubusercontent.com/4231074/42233968-9dc077ec-7f10-11e8-94d0-48a7d80c6a38.png">

I am getting only 4 options 
- eq
- ne
- glob
- regex

To do filter in my requirement I have to pass an array of slugs to get products, Can you please help me to achieve my requirement.

**Note: I have to do this query into my template and I am having slug array into my pathContext.

**Comment by jlengstorf** [comment]
Hi, @sachingvit — can you add a little more detail here?

We need all this information laid out in the [“how to file an issue” docs](https://gatsbyjs.org/docs/how-to-file-an-issue/) so we know your versions, setup, etc.

Can you please add that detail?

Additionally, you can try deleting your cache and Node modules to see if something hung up:

```
# remove the cache and modules
rm -rf .cache/ node_modules/

# reinstall the modules
npm install

# restart the development server
npm run develop
```

Please let us know if a fresh install clears up the issue. If not, add the info above and we'll take a look. 

Thanks!

**Comment by goodok21** [comment]
I'am pretty sure that you don't use `template` right, but I think you can use `regex` for this situation.
Try something like:
`{ slug: { regex: "/\b(123|1234|id123)\b/g" } }`
