### ISSUE TITLE
Google translate does not work with gatsby sites

### ISSUE THREAD

**Issue by rdcw** [gatsbyjs/gatsby#6300]
## Description
When opening a gatsby site in google translate, it shows a flash of translated content and then shows a 404 page.

E.g.
https://translate.google.com/translate?sl=auto&tl=fr&js=y&hl=en&u=https%3A%2F%2Freactjs.org

or 

https://translate.google.com/translate?sl=auto&tl=fr&js=y&hl=en&u=https%3A%2F%2Fabout.sourcegraph.com

### Steps to reproduce

Open any gatsby page in google translate.

### Expected result

To show the page with the translated text.

### Actual result

A 404 page is shown.

### Environment

Production

**Comment by m-allanson** [comment]
Huh. Google translate re-hosts the site (with translated content) in an iframe with a URL like `https://translate.google.com/translate?hl=en&sl=en&tl=fr&u=about.sourcegraph.com`.

Gatsby doesn't know it's being hosted on a different domain and tries to load the content for the `/translate` page, which doesn't exist, so it then shows the 404 page instead.

I've marked this as a bug but I'm not sure what the fix would be. Maybe Gatsby shouldn't load the 404 page if the initial SSR render _isn't_ the 404 page?

**Comment by KyleAMathews** [comment]
That sounds like it could be a reasonable fix. Check if a SSRed page is loaded and trust it over the client URL.

**Comment by jdfm** [comment]
This also seems to be an issue with google's webcache, as the url ends up looking like: `http://webcache.googleusercontent.com/search?q=cache:[GOOGLE_CACHE_KEY]:[YOUR_CONTENTS_ENDPOINT][GOOGLE_APPENDED_QUERY_VARIABLES]`

Which then causes it to redirect to a 404 page and output to the console that `A page wasn't found for "/search"`.

I would imagine this is going to happen for any service that acts as a sort of proxy to the content created through Gatsby.

Currently using Gatsby v1.9.273.

**Comment by jdfm** [comment]
@m-allanson 

Have you tried accessing your endpoint on google webcache? I tried it a few times with the example you posted (about.sourcegraph.com) and it seems to be working, but trying to access the same endpoint via google translate redirects to the 404 page. Whereas in my case, it redirects to 404 consistently on both.

**Comment by johnsonsamuel** [comment]
> I dont see 404 but I see blank screen, when tried to find the issue, I see 'Uncaught (in promise) TypeError: Cannot read property 'pageContext' of undefined'.

Also the below error - Cross-Origin Read Blocking (CORB) blocked cross-origin response https://next.gatsbyjs.org/static/d/164/path---404-html-516-62a-NZuapzHg3X9TaN1iIixfv1W23E.json with MIME type application/json.

**Comment by KyleAMathews** [comment]
Dan Abramov came up with a work around for this — https://github.com/reactjs/reactjs.org/pull/1148

**Comment by gaearon** [comment]
To be clear my workaround is for the crash when using the Translate extension. I haven’t looked into the URL issue but we’d need to solve it too. Ideas?

**Comment by KyleAMathews** [comment]
@gaearon oh hmm yeah — so fixing that would mean Gatsby needs to support alt URL patterns where some other software has taken control of the URL. Seems doable.

**Comment by ryota-murakami** [comment]
Hi All, from Dan Twitter. https://twitter.com/dan_abramov/status/1035575858843578369

Oh, **Page Not Found** 😧

**Comment by ryota-murakami** [comment]
@KyleAMathews @gaearon 

Console say `A page wasn't found for "/translate_c"`
Perhaps Google Translate attempt to try access `/translate_c` at inner JavaScript.

## video
https://www.dropbox.com/s/bfy2t4kc31smc7d/google-react-gatsby.mp4?dl=0

- loader.js
```js
import React, { createElement } from "react"
import pageFinderFactory from "./find-page"
import emitter from "./emitter"
import stripPrefix from "./strip-prefix"
let findPage

let syncRequires = {}
let asyncRequires = {}
let pathScriptsCache = {}
let resourceStrCache = {}
let resourceCache = {}
let pages = []
// Note we're not actively using the path data atm. There
// could be future optimizations however around trying to ensure
// we load all resources for likely-to-be-visited paths.
let pathArray = []
let pathCount = {}
let pathPrefix = ``
let resourcesArray = []
let resourcesCount = {}
const preferDefault = m => (m && m.default) || m
let prefetcher
let inInitialRender = true
let fetchHistory = []
const failedPaths = {}
const failedResources = {}
const MAX_HISTORY = 5

// Prefetcher logic
if (process.env.NODE_ENV === `production`) {
  prefetcher = require(`./prefetcher`)({
    getNextQueuedResources: () => resourcesArray.slice(-1)[0],
    createResourceDownload: resourceName => {
      fetchResource(resourceName, () => {
        resourcesArray = resourcesArray.filter(r => r !== resourceName)
        prefetcher.onResourcedFinished(resourceName)
      })
    },
  })
  emitter.on(`onPreLoadPageResources`, e => {
    prefetcher.onPreLoadPageResources(e)
  })
  emitter.on(`onPostLoadPageResources`, e => {
    prefetcher.onPostLoadPageResources(e)
  })
}

const sortResourcesByCount = (a, b) => {
  if (resourcesCount[a] > resourcesCount[b]) {
    return 1
  } else if (resourcesCount[a] < resourcesCount[b]) {
    return -1
  } else {
    return 0
  }
}

const sortPagesByCount = (a, b) => {
  if (pathCount[a] > pathCount[b]) {
    return 1
  } else if (pathCount[a] < pathCount[b]) {
    return -1
  } else {
    return 0
  }
}

const fetchResource = (resourceName, cb = () => {}) => {
  if (resourceStrCache[resourceName]) {
    process.nextTick(() => {
      cb(null, resourceStrCache[resourceName])
    })
  } else {
    // Find resource
    let resourceFunction
    if (resourceName.slice(0, 12) === `component---`) {
      resourceFunction = asyncRequires.components[resourceName]
    } else if (resourceName.slice(0, 9) === `layout---`) {
      resourceFunction = asyncRequires.layouts[resourceName]
    } else {
      resourceFunction = asyncRequires.json[resourceName]
    }

    // Download the resource
    resourceFunction((err, executeChunk) => {
      resourceStrCache[resourceName] = executeChunk
      fetchHistory.push({
        resource: resourceName,
        succeeded: !err,
      })

      if (!failedResources[resourceName]) {
        failedResources[resourceName] = err
      }

      fetchHistory = fetchHistory.slice(-MAX_HISTORY)
      cb(err, executeChunk)
    })
  }
}

const getResourceModule = (resourceName, cb) => {
  if (resourceCache[resourceName]) {
    process.nextTick(() => {
      cb(null, resourceCache[resourceName])
    })
  } else if (failedResources[resourceName]) {
    process.nextTick(() => {
      cb(failedResources[resourceName])
    })
  } else {
    fetchResource(resourceName, (err, executeChunk) => {
      if (err) {
        cb(err)
      } else {
        const module = preferDefault(executeChunk())
        resourceCache[resourceName] = module
        cb(err, module)
      }
    })
  }
}

const appearsOnLine = () => {
  const isOnLine = navigator.onLine
  if (typeof isOnLine === `boolean`) {
    return isOnLine
  }

  // If no navigator.onLine support assume onLine if any of last N fetches succeeded
  const succeededFetch = fetchHistory.find(entry => entry.succeeded)
  return !!succeededFetch
}

const handleResourceLoadError = (path, message) => {
  console.log(message)

  if (!failedPaths[path]) {
    failedPaths[path] = message
  }

  if (
    appearsOnLine() &&
    window.location.pathname.replace(/\/$/g, ``) !== path.replace(/\/$/g, ``)
  ) {
    window.location.pathname = path
  }
}

let mountOrder = 1
const queue = {
  empty: () => {
    pathArray = []
    pathCount = {}
    resourcesCount = {}
    resourcesArray = []
    pages = []
    pathPrefix = ``
  },
  addPagesArray: newPages => {
    pages = newPages
    if (
      typeof __PREFIX_PATHS__ !== `undefined` &&
      typeof __PATH_PREFIX__ !== `undefined`
    ) {
      if (__PREFIX_PATHS__ === true) pathPrefix = __PATH_PREFIX__
    }
    findPage = pageFinderFactory(newPages, pathPrefix)
  },
  addDevRequires: devRequires => {
    syncRequires = devRequires
  },
  addProdRequires: prodRequires => {
    asyncRequires = prodRequires
  },
  dequeue: () => pathArray.pop(),
  enqueue: rawPath => {
    // Check page exists.
    const path = stripPrefix(rawPath, pathPrefix)
    if (!pages.some(p => p.path === path)) {
      return false
    }

    const mountOrderBoost = 1 / mountOrder
    mountOrder += 1
    // console.log(
    // `enqueue "${path}", mountOrder: "${mountOrder}, mountOrderBoost: ${mountOrderBoost}`
    // )

    // Add to path counts.
    if (!pathCount[path]) {
      pathCount[path] = 1
    } else {
      pathCount[path] += 1
    }

    // Add path to queue.
    if (!queue.has(path)) {
      pathArray.unshift(path)
    }

    // Sort pages by pathCount
    pathArray.sort(sortPagesByCount)

    // Add resources to queue.
    const page = findPage(path)
    if (page.jsonName) {
      if (!resourcesCount[page.jsonName]) {
        resourcesCount[page.jsonName] = 1 + mountOrderBoost
      } else {
        resourcesCount[page.jsonName] += 1 + mountOrderBoost
      }

      // Before adding, checking that the JSON resource isn't either
      // already queued or been downloading.
      if (
        resourcesArray.indexOf(page.jsonName) === -1 &&
        !resourceStrCache[page.jsonName]
      ) {
        resourcesArray.unshift(page.jsonName)
      }
    }
    if (page.componentChunkName) {
      if (!resourcesCount[page.componentChunkName]) {
        resourcesCount[page.componentChunkName] = 1 + mountOrderBoost
      } else {
        resourcesCount[page.componentChunkName] += 1 + mountOrderBoost
      }

      // Before adding, checking that the component resource isn't either
      // already queued or been downloading.
      if (
        resourcesArray.indexOf(page.componentChunkName) === -1 &&
        !resourceStrCache[page.jsonName]
      ) {
        resourcesArray.unshift(page.componentChunkName)
      }
    }

    // Sort resources by resourcesCount.
    resourcesArray.sort(sortResourcesByCount)
    if (process.env.NODE_ENV === `production`) {
      prefetcher.onNewResourcesAdded()
    }

    return true
  },
  getResources: () => {
    return {
      resourcesArray,
      resourcesCount,
    }
  },
  getPages: () => {
    return {
      pathArray,
      pathCount,
    }
  },
  getPage: pathname => findPage(pathname),
  has: path => pathArray.some(p => p === path),
  getResourcesForPathname: (path, cb = () => {}) => {
    if (
      inInitialRender &&
      navigator &&
      navigator.serviceWorker &&
      navigator.serviceWorker.controller &&
      navigator.serviceWorker.controller.state === `activated`
    ) {
      // If we're loading from a service worker (it's already activated on
      // this initial render) and we can't find a page, there's a good chance
      // we're on a new page that this (now old) service worker doesn't know
      // about so we'll unregister it and reload.
      if (!findPage(path)) {
        navigator.serviceWorker
          .getRegistrations()
          .then(function(registrations) {
            // We would probably need this to
            // prevent unnecessary reloading of the page
            // while unregistering of ServiceWorker is not happening
            if (registrations.length) {
              for (let registration of registrations) {
                registration.unregister()
              }
              window.location.reload()
            }
          })
      }
    }
    inInitialRender = false
    // In development we know the code is loaded already
    // so we just return with it immediately.
    if (process.env.NODE_ENV !== `production`) {
      const page = findPage(path)
      if (!page) return cb()
      const pageResources = {
        component: syncRequires.components[page.componentChunkName],
        json: syncRequires.json[page.jsonName],
        layout: syncRequires.layouts[page.layout],
        page,
      }
      cb(pageResources)
      return pageResources
      // Production code path
    } else {
      if (failedPaths[path]) {
        handleResourceLoadError(
          path,
          `Previously detected load failure for "${path}"`
        )

        return cb()
      }

      const page = findPage(path)

      if (!page) {
        handleResourceLoadError(path, `A page wasn't found for "${path}"`)

        return cb()
      }

      // Use the path from the page so the pathScriptsCache uses
      // the normalized path.
      path = page.path

      // Check if it's in the cache already.
      if (pathScriptsCache[path]) {
        process.nextTick(() => {
          cb(pathScriptsCache[path])
          emitter.emit(`onPostLoadPageResources`, {
            page,
            pageResources: pathScriptsCache[path],
          })
        })
        return pathScriptsCache[path]
      }

      emitter.emit(`onPreLoadPageResources`, { path })
      // Nope, we need to load resource(s)
      let component
      let json
      let layout
      // Load the component/json/layout and parallel and call this
      // function when they're done loading. When both are loaded,
      // we move on.
      const done = () => {
        if (component && json && (!page.layoutComponentChunkName || layout)) {
          pathScriptsCache[path] = { component, json, layout, page }
          const pageResources = { component, json, layout, page }
          cb(pageResources)
          emitter.emit(`onPostLoadPageResources`, {
            page,
            pageResources,
          })
        }
      }
      getResourceModule(page.componentChunkName, (err, c) => {
        if (err) {
          handleResourceLoadError(
            page.path,
            `Loading the component for ${page.path} failed`
          )
        }
        component = c
        done()
      })
      getResourceModule(page.jsonName, (err, j) => {
        if (err) {
          handleResourceLoadError(
            page.path,
            `Loading the JSON for ${page.path} failed`
          )
        }
        json = j
        done()
      })

      page.layoutComponentChunkName &&
        getResourceModule(page.layout, (err, l) => {
          if (err) {
            handleResourceLoadError(
              page.path,
              `Loading the Layout for ${page.path} failed`
            )
          }
          layout = l
          done()
        })

      return undefined
    }
  },
  peek: path => pathArray.slice(-1)[0],
  length: () => pathArray.length,
  indexOf: path => pathArray.length - pathArray.indexOf(path) - 1,
}

export const publicLoader = {
  getResourcesForPathname: queue.getResourcesForPathname,
}

export default queue



// WEBPACK FOOTER //
// ./.cache/loader.js
```

**Comment by ryota-murakami** [comment]
`findPage()` appears to be the cause.
How to handle it😰

- loader.js
```js
      const page = findPage(path)

      if (!page) {
        handleResourceLoadError(path, `A page wasn't found for "${path}"`)
```

**Comment by KyleAMathews** [comment]
@ryota-murakami thanks for looking into this! The logic for finding pages is in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/find-page.js

**Comment by jlengstorf** [comment]
This isn't fixed, so I'm reopening it.

**Comment by alexlouden** [comment]
I'm hitting this issue with gatsby v1 - would it be okay for me to offer a $50 USD bounty for someone to solve it?

**Comment by florinme** [comment]
Just came across this issue. At first I thought it was a CORS issue, which I resolved by setting the following settings for gatsby-plugin-netlify:

```
    {
      resolve: `gatsby-plugin-netlify`,
      options: {
        headers: {
          '/*': [
            'Access-Control-Allow-Origin: https://translate.googleusercontent.com',
            'Access-Control-Allow-Credentials: true',
            'Content-Security-Policy: frame-ancestors https://translate.google.com',
            'X-Frame-Options: ALLOW-FROM https://translate.google.com',
          ],
        },
        mergeSecurityHeaders: false,
      },
    },
```

Now I'm seeing a 404 (in the console, not on the front end). 
```
GET https://southsoundymca.jayray.com/page-data/translate_c/page-data.json 404
```

This seems to reflect the issue above. Digging into it further it looks like all Gatsby sites are affected and as such, are not able to be translated by google translate. Anyone know if this is actively being worked on? 🤔

**Comment by broeker** [comment]
We have yet to attempt an install but definitely hope there is a path forward -- Google Translate is a pretty amazing option for clients who don't have the resources do full translations in multiple languages, and it seems perfectly in line with the philosophy behind Gatsby and the JAMstack (so much so that it didn't even occur to me that it would not work, and sadly, I'm finding this out after it is already in the scope-of-work for a current Gatsby project :)

Our team is fairly new to Gatsby and React so I don't understand the internals well enough to jump right in, but if anybody IS working on this and has anything to share or that we can contribute to please let us know, and we will do our best to help as we can.

**Comment by florinme** [comment]
@broeker, I haven't gotten any answer on this. Let's team up and figure it out? It sounds like we're in a similar situation.

**Comment by moonmeister** [comment]
@florinme FYI: Adding your recommend config on my site fixes the white page issue but I don't get a 404, the content flashes with the translation before reverting back to the original language. Maybe I'm on a newer version of Gatsby (I'm at the latest)?

https://5d2ab3e25c12e1d91c1707db--moonmeister-personal.netlify.com/

**Comment by JayRayDeveloper** [comment]
@moonmeister @broeker  had any luck with a workaround? I'm totally in a jam and don't know what to do...

**Comment by moonmeister** [comment]
Okay, so I've done some work on this and understand what's happening better. There are two issues causing problems for sites. The first is unrelated to Gatsby and is a security issue, the second is Gatsby re-hydrating our static pages.

## 1. Security Headers

Translating a site like [reactjs.org](https://translate.google.com/translate?hl=en&sl=en&tl=fr&u=reactjs.com) (yes, they use gatsby) results in the error:
`Load denied by X-Frame-Options: https://reactjs.org/?depth=1&hl=en&rurl=translate.google.com…259,15700262,15700265&usg=ALkJrhgfSw3S-344F8stcoY_Wcxu2-llPA does not permit framing.`

This has nothing to do with Gatsby and everything to do with the security headers set on your web server for CORS and CSP. @florinme has correctly identified the correct settings [above](https://github.com/gatsbyjs/gatsby/issues/6300#issuecomment-508349116). This is probably a more common issue with Gatsby sites; because, newer hosting providers like Netlify, which are commonly used with static asset sites, wisely use CSP to block sites from being embedded in iframes.

I'll give a quick explanation of the 4 settings indicated above:

### [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)
CORS blocks examplea.com from loading content from exampleb.org. To allow cross domain content loading, we must set Response Headers on the web server. So, for Google Translate to load our resources in an iframe we need our hosting provider to set these two headers:
```
Access-Control-Allow-Origin: https://translate.googleusercontent.com
Access-Control-Allow-Credentials: true
```

### [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy)
The CSP Response Header tells the browser what can be done with the page being loaded. Loading a site into an iframe is a potential security risk and thus some hosting providers block this by default. Modifying this header allows only Google Translate to load the site:
```
Content-Security-Policy: frame-ancestors https://translate.google.com
```
### [X-Frame-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options)
Before CSP was a Standard HTTP Response Header we had a convention to block loading content in iframes, it was X-Frame-Options. THis is ignored if a browser supports CSP, but is useful to ensure backwards compatibility of older browsers(mostly IE). 
```
 X-Frame-Options: ALLOW-FROM https://translate.google.com


## 2. Gatsby Magic

Part of Gatsby's mystic is how we ship static content that gets re-hydrated into a fully client-side react app. Cool right? well it's causing an issue. Google Translate is loading a pages static html and translating that, about the time it's finished React swoops in and  turns your translated content into a react app and overwrites it all with the content(in the original language) from the page's `page-data.json`. Because Google Translate thinks it's job is done it moves on and doesn't re-translate the page.

## Conclusion
Fixing problem 1 fixes Google Translate showing a blank white screen. Problem 2 causes the flash of translated content reverting back to the original language.

Unfortunately I have no idea how to fix this. If we somehow disabled the Gatsby's re-hydration of the react app we'd be be disabling site functionality (though pausing JS execution via the debugger does show this would work for translation). What really needs to happen is we need to let Google Translate know the page isn't actually finished loading, or that it has been "reloaded"

. I don't know if this means dispatching the correct event or if it's not even possible.

**Comment by urielhdz** [comment]
This can be solved by disabling the client side router.

You can do that by using this package in your Gatsby site: https://www.gatsbyjs.org/packages/@wardpeet/gatsby-plugin-static-site/ ([currently broken](https://github.com/wardpeet/gatsby-plugin-static-site/issues/10)).

There is a fork that works with the current latest version of Gatsby that you can found here: https://www.npmjs.com/package/@xavivars/gatsby-plugin-static-site

**Comment by urielhdz** [comment]
I uploaded a working example just to show up the solution, the [original page](http://lives.codigofacilito.com/) is in spanish, and [this link](http://translate.google.com/translate?hl=&sl=es&tl=en&u=http%3A%2F%2Flives.codigofacilito.com%2F) displays it translated to english using Google Translate.

**Comment by urielhdz** [comment]
I think that this issue could lead to some frustration so I don't know if it is a good idea to have this documented somewhere @marcysutton, I'm thinking on something like a guide on how to disable the client side router and in which cases you could do that 🤔

Aside from this issue, in #4337 there is a discussion with other potential use cases to disable the router.

**Comment by moonmeister** [comment]
@urielhdz Thanks for the Info, yes this will fix the issue I identified. It'd be nice if there was a way to maintain CSR and make this work.

**Comment by florinme** [comment]
Thanks to both @moonmeister and @urielhdz for the work on this! What are the implications of removing the router, if we disable it for translating, navigation will stop, correct? Can we disable routing temporarily while the user is viewing a translated page?

**Comment by urielhdz** [comment]
I can confirm that navigation still works, 

In regards of the downsides, I think that you lose the speed and performance benefits of using a client side router, so for example, every page transition requires a roundtrip to the server.

**Comment by dlbnco** [comment]
Good question @florinme I was asking myself the same.

>In regards of the downsides, I think that you lose the speed and performance benefits of using a client side router, so for example, every page transition requires a roundtrip to the server.

@urielhdz Thanks for clarifying.

I would set a separate instance of the website with this setting in a separate domain, something like translate.domain.com.

**Comment by muescha** [comment]
gatsbyjs.org is still not translatable :(

https://translate.google.de/translate?sl=auto&tl=de&u=gatsbyjs.org%2Fdocs

**Comment by moonmeister** [comment]
For what it's worth, Chrome's integrated translator works great.

**Comment by edykim** [comment]
I had some free time this morning, and I looked into it. The issue is from `production-app.js` and the router.

## Problems

### `navigate` in `production-app.js`

When the page is opened on the translation service, `production-app.js` made a redirection to the actual webpage. https://github.com/gatsbyjs/gatsby/blob/dced9f1a02eaa266e355599816f8ee14f64614f6/packages/gatsby/cache-dir/production-app.js#L111-L124
The translation service fetches the webpage from their host so that they can manipulate the content on other pages without the CORS problem. That means the URL structure is changed from our routing rules. `navigate` is called from here. This is the reason for blinking.

It redirects to `/translate_c` or something similar URL. The URL is not valid on our website, so a 404 error happens as a result.

### Hydration

The other problem happens when the components hydrate it. If you add the translation service into headers, it will hydrate the data again; however, it loads wrong data based on the wrong URL because of the reason above.

If the website doesn't have CORS headers, it will fail to hydrate the page anyway because the loader cannot load `page-data.json`, actually any resources from the website.

If the website has CORS headers for the translation service, it will hydrate again. However, the router using `window.location` and... you know, it will fail to load the proper page as we see above.

## Solution (but dirty)

This is my solution for this but it is not clean and not ideal. I don't want to specify some translation services in my code so I just added some logic before hitting the `navigate` in `production-app.js`.

```js
// gatsby-node.js

const fs = require("fs")
const path = require("path")

exports.onPreBootstrap = ({ store }) => {
  const { program } = store.getState()
  const filePath = path.join(program.directory, ".cache", "production-app.js")

  const code = fs.readFileSync(filePath, {
    encoding: `utf-8`,
  })

  const newCode = code.replace(
    `const { pagePath, location: browserLoc } = window`,
    `const { pagePath } = window
    let { location: browserLoc } = window

    if (window.parent.location !== browserLoc) {
      browserLoc = {
        pathname: pagePath
      }
    }
  `
  )

  fs.writeFileSync(filePath, newCode, `utf-8`)
}
```

If there is a parent frame, add some stub into `browserLoc` and avoid `navigate` calling. If you don't have CORS headers for these services, it doesn't have a problem with hydration too because the code cannot fetch `page-data.json` from your website.

Obviously, there are downsides to this approach because of missing hydration. Also, it will be a problem if you are using an iframe with the website.

The demo page is here: 
https://translate.google.com/translate?sl=ko&tl=en&u=https%3A%2F%2Fxenodochial-swartz-f568e8.netlify.app%2F

<img width="811" alt="Screen Shot 2020-04-22 at 1 00 36 pm" src="https://user-images.githubusercontent.com/33057457/80027990-4d4d5d80-8499-11ea-8afe-9b595ff535e7.png">

I'd love to see some nice solution for this issue.

**Comment by LekoArts** [comment]
I've tried it with https://translate.google.com/translate?sl=auto&tl=de&u=https://www.gatsbyjs.com and it works.

Closing as stale. If you still see this behavior in the latest Gatsby v3 please open a new issue.
