### ISSUE TITLE
Sub-Domain site per language

### ISSUE THREAD

**Issue by gilamran** [gatsbyjs/gatsby#6301]
Hi,
I want to create a static website, and I want to support several languages.
All the (translated) data will be provided via CMS (Contentful)
I want the website to be served on a different sub-domain per language.
For example http://www.site.com will be the English version and the http://ja.site.com will be the Japanese version.

I don't need all the languages on the same static site, as users won't move from language to language that much (I don't mind the full reload on language change)

I don't want to duplicate the project per language...

What's the best process to achieve this? 
If this is not possible, What are my options for multi-lingual static website?

Thanks!
Keep up the great work

**Comment by m-allanson** [comment]
You could run your build once for each language, then copy the built `public` folder to a language specific location after each build (`public-en`, `public-ja` etc).

There are a few i18n starters / plugins / articles that you could look at to maybe get further ideas on this.

**Comment by gilamran** [comment]
Thanks @m-allanson sounds interesting. I'll give it a try
