### ISSUE TITLE
Trigger build of a single new or update node

### ISSUE THREAD

**Issue by Amanej** [gatsbyjs/gatsby#6305]
So lets say a new data entry is created or an existing one is updated in a Gatsby data source.

How can we trigger a build of the single node instead of rebuilding the entire site ?

I believe this what the Gatsby startup company is looking to due, but maybe there is some way to trigger this by using the existing Gatsby API.

**Comment by LeKoArts** [comment]
You currently can’t do that, this functionality doesn’t exist at the moment

**Comment by Amanej** [comment]
@LeKoArts 

Right, how about creating a fallback until the next build. Ie instead of 404, the react app checks for a item in the most recent version of the data source. And only shows the 404 if the item is not done.

**Comment by m-allanson** [comment]
You can do data fetching from the client side of a Gatsby app if you like, have a look at https://www.gatsbyjs.org/docs/building-apps-with-gatsby/#hybrid-app-pages for some more info.

**Comment by LekoArts** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
