### ISSUE TITLE
Page change scrolling not working

### ISSUE THREAD

**Issue by vning93** [gatsbyjs/gatsby#631]
The page scroll does not work when I change pages. It should automatically get built in to react-router when I run `gatsby build` right?

**Comment by KyleAMathews** [comment]
It only works if you use the back button not when you click directly on a link. Is that perhaps the problem?

**Comment by vning93** [comment]
Gotcha yeah. Well even if I click the back button, it won't work. I started with this kit: https://github.com/gatsbyjs/gatsby-starter-documentation

**Comment by KyleAMathews** [comment]
What are you expecting to happen?

**Comment by vning93** [comment]
When I click on a link that uses <Link> from react-router, for it to auto-scroll up to the top of the destination page.

**Comment by KyleAMathews** [comment]
hmmm... that should be working. Can't think of a reason atm why it wouldn't
be working...

**Comment by Slava** [comment]
Same issue here. Scrolling doesn't go to top after pushing a new route to browser history.

**Comment by sparshy** [comment]
Auto scroll up not working for me as well, can anyone think of a reason why?

**Comment by owenhoskins** [comment]
I just ran into this and it was simply due this `html, body { height: 100%; }` 

Luckily my layout was not dependent on it.

Hope that helps someone!

**Comment by KyleAMathews** [comment]
Closing this out as it's a bit old. If people are still having trouble — would love to see an issue with suggestions on how we can improve our implementation.

**Comment by monsieurnebo** [comment]
Similar issue here:

**Page A**: I'm scrolling to - let say - 50% of the page height, then click on a Gatsby Link.
**Page B**: I'm on the new page, on the top. I click on a link to go back to the previous page.
**Page A**: The page opens on the same position as I was when i leaved out, instead of the top.
