### ISSUE TITLE
[docs/code examples] diff colors not intuitive

### ISSUE THREAD

**Issue by zebapy** [gatsbyjs/gatsby#6311]
It's a little deceiving that the addition colors are almost a red tone and deletions aren't far from a muted green. This is fairly confusing till you look closer and notice the -/+ marks. 

![screenshot 2018-07-05 10 59 38](https://user-images.githubusercontent.com/2199845/42331119-a6e76bc2-8042-11e8-809a-e913d5ecc41b.png)

**Comment by m-allanson** [comment]
That's a very good point! 

Your screenshot is from: https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/

If anyone would like to take a look at fixing this, you probably need to uncomment the colours here and then swap them around: https://github.com/gatsbyjs/gatsby/blob/4a946428cb555c8141c7f69544bbd528f11a5c1a/www/src/css/prism-coy.css#L19-L38

@fk I wonder if we should change the `gatsby-highlight-code-line` colour too? Currently it's [a red-sh colour](https://next.gatsbyjs.org/tutorial/part-seven/#creating-pages).

**Comment by fk** [comment]
Oh wow, indeed a _very good_ (and a little embarrasing) point @zebapy!

@m-allanson 

> I wonder if we should change the gatsby-highlight-code-line colour too?

Hmm, good point, too…I need to let that simmer for a little. Thinking out loud—would we ever want to highlight additions and/or deletions?

**Comment by ThomasAnkcorn** [comment]
Hey, I'd like to help out with this.

**Comment by ThomasAnkcorn** [comment]
The pull request for the color changes is here https://github.com/gatsbyjs/gatsby/pull/6373

**Comment by fk** [comment]
Hey @ThomasAnkcorn! Sorry for closing your PR! 🙏 

As mentioned in the comments of your PR (https://github.com/gatsbyjs/gatsby/pull/6373#issuecomment-409221433) I just opened https://github.com/gatsbyjs/gatsby/issues/6889 which when resolved hopefully prevents further confusion around where to add/modify syntax highlighting CSS.

If you want to jump on that, I'd be happy to guide (with less delay than the last time :-/)!

Also, please feel free to create an issue for WCAG AA compliance and/or suggesting changes to `gatsby-highlight-code-line` -- 💯 to these thoughts!

**Comment by fk** [comment]
Fixed in #6878
