### ISSUE TITLE
TO DO after v2 is done: separate search for v1 and v2 docs

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#6318]
## Relevant information

@m-allanson and I think that Algolia search is collecting all search data from v1 and v2 docs into one stream. Seems like down the road, as v2 progresses, it might be handy to separate that stream into two, so we can get data specific to each site and improve the docs based on the data.

Wondering: are there any reasons to keep v1 and v2 search data in one stream?

**Comment by m-allanson** [comment]
> are there any reasons to keep v1 and v2 search data in one stream?

I don't think there's any good reason to do this, other than it takes work to split them out.

We haven't done any specific config for the search on next.gatsbyjs.org, so I suspect the search results there are actually using the data from gatsbyjs.org. 

Ideally we'd get v2 released immediately and would no longer need next.gatsbyjs.org. Depending on how long next.gatsbyjs.org will exist, it could be worth setting up a separate search index.

**Comment by shannonbux** [comment]
Ok, I'd say let's wait until we have a version of the site we know will last a long time.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
