### ISSUE TITLE
[gatsby-remark-embed-snippet] embend only part of files

### ISSUE THREAD

**Issue by benjaminabel** [gatsbyjs/gatsby#6321]
## Summary

It would be nice to embed only part of files delimited by line numbers.

### Basic example

I think this should be done in the markdown source, for example an object with key lines. For example to embed line 3 and 12 to 15.

`embed:sample-javascript-file.js{lines: [3, 12-15]}`

*+* add keyword highlight to highlight line directly from markdown. for example:  `embed:sample-javascript-file.js{lines: [3, 12-15], highlight: [3, 14-15}`

### Motivation

It would permit to analyse parts of code one by one on a big file.

**Comment by m-allanson** [comment]
@benjaminabel You're in luck! There's a PR to add this functionality over at https://github.com/gatsbyjs/gatsby/pull/6084. I think it's ready to merge so should be released in the next day or two.

**Comment by benjaminabel** [comment]
Thanks @m-allanson I didn't find this PR before I opened this issue.
