### ISSUE TITLE
[v2] `--https` should shell out to get Dev cert, otherwise it runs the rest of the command as elevated user (sudo)

### ISSUE THREAD

**Issue by jquense** [gatsbyjs/gatsby#6329]
I think this is what's happening, but my permissions were all off for any files gatsby touched during the initial setup for the certs. I think we need to spawn a new process for this so the current one doesn't end up with sudo privileges

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
