### ISSUE TITLE
[gatsby-source-mongodb] Impossible to query MongoDB _id field

### ISSUE THREAD

**Issue by ManuelHaag** [gatsbyjs/gatsby#6333]
## Description

It's impossible to use the MongoDB `_id` field in GraphQL queries. Since the `_id` field is deleted and `createNodeId` is used to generate a new one, there is no way to query the field anymore.

Cf. lines 68-74 in the plugins [gatsby-node.js](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-mongodb/src/gatsby-node.js):

```js
        var id = item._id.toString()
        delete item._id

        var node = {
          // Data for the node.
          ...item,
          id: createNodeId(`${id}`),
```

### Steps to reproduce

Using the [gatsby-source-mongodb](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-mongodb) plugin. My exact routine is:

- Create pages from MongoDB documents in `gatsby-node.js`
- Pass the `id` field to the page template
- The template finds the correct document since `id` is obviously the same (non-mongo `id`) in both queries
- Have documents in another collection which I want to query using the page `_id`

Collection "pages":

```json
[
    {
        "_id": "mongoId1"
    },
    {
        "_id": "mongoId2"
    }
]
```

Another collection:

```json
[
    {
        "_id": "otherMongoId1",
        "page": "mongoId1"
    },
    {
        "_id": "otherMongoId2",
        "page": "mongoId2"
    },
    {
        "_id": "otherMongoId3",
        "page": "mongoId1"
    }
]
```

### Expected result

The original MongoDB `_id` should be present in some form. Probably as something like `_id`, `mongoId` or even inside `internal` in the node object.

### Actual result

No MongoDB `_id` present.

### Environment

```
gatsby: next => 2.0.0-beta.15
gatsby-source-mongodb: next => 2.0.0-beta.3
```

**Comment by pieh** [comment]
@ManuelHaag You are defenitely right. Would you be interested in creating PR that adds field with original id to nodes created by that plugin? In other plugins we generally use this naming naming scheme - `<nameOfSource>_id` - so maybe `mongodb_id`?

some examples of this:
https://github.com/gatsbyjs/gatsby/blob/93bc53cb66fdc23cf0aa7e8f51729706b0dd2629/packages/gatsby-source-drupal/src/normalize.js#L7
https://github.com/gatsbyjs/gatsby/blob/93bc53cb66fdc23cf0aa7e8f51729706b0dd2629/packages/gatsby-source-contentful/src/normalize.js#L323

**Comment by ManuelHaag** [comment]
Sure @pieh, thanks for the quick response & naming convention hint.
Check #6334!
