### ISSUE TITLE
[v2] StaticQuery, named export, duplicate document

### ISSUE THREAD

**Issue by crazko** [gatsbyjs/gatsby#6337]
## Description

Hi all, I was struggling with `GraphQL fragments and roots must have unique names` error even with the simplest setup:

- one `Layout` component with `StaticQuery`
- one page importing `Layout`
- no plugins

While running either `gatsby develop` or `gatsby build` it shows error message:

> **GraphQL Error** There was an error while compiling your site's GraphQL queries.
  Invariant Violation: GraphQLCompilerContext: Duplicate document named `TitleQuery`. GraphQL fragments and roots must have unique names.

Eventually I tried to use default export instead of named export and suddenly everything worked:

- `export const Layout`, `import { Layout } from "..."` - causes error
- `export default Layout`, `import Layout from "..."` - works OK

Don't know, is this intended or not?

Thanks for the hard work on this project!

### Steps to reproduce

Just try to clone this repository, install `npm i` and run `npm start` - https://github.com/crazko/gatsby-next-test

### Expected result

Works correctly with both named and default exports.

### Actual result

Throws error:

> **GraphQL Error** There was an error while compiling your site's GraphQL queries.
  Invariant Violation: GraphQLCompilerContext: Duplicate document named `TitleQuery`. GraphQL fragments and roots must have unique names.

### Environment

```
  System:
    OS: macOS High Sierra 10.13.5
    CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.9.4 - /usr/local/bin/node
    npm: 6.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 60.0.2
    Safari: 11.1.1
  npmPackages:
    gatsby: ^2.0.0-beta.19 => 2.0.0-beta.19
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```

**Comment by m-allanson** [comment]
Thanks for the example repo, I can confirm that I'm seeing the same issue. This seems like a bug.

If anyone has the chance to investigate then [file-parser.js](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/internal-plugins/query-runner/file-parser.js) or [query-compiler.js](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/internal-plugins/query-runner/query-compiler.js) might be a good place to start. The [How to Contribute docs](https://www.gatsbyjs.org/docs/how-to-contribute/#contributing-to-the-repo) describe how to get a local Gatsby dev environment running.

**Comment by deadcoder0904** [comment]
LOL this is a weird one. Everything broke for me when I changed from default export to named one 😂
