### ISSUE TITLE
Accessing frontmatter in gatsby-transformer-remark sub plugin

### ISSUE THREAD

**Issue by deemaagog** [gatsbyjs/gatsby#6343]
Hi
I'm trying to create a gatsby-transformer-remark sub plugin. It should be able to modify markdown body and frontmatter. That's how I can modify body:
```javascript
const visit = require(`unist-util-visit`)

module.exports = ({ markdownAST }, pluginOptions = {}) => {
  visit(markdownAST, `text`, node => {
    node.value = doSomething(node.value)
  })
  return markdownAST
}
```

How do I access frontmatter and modify specific field?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
