### ISSUE TITLE
Consider migration mdreizin/gatsby-plugin-robots-txt into gatsbyjs/gatsby

### ISSUE THREAD

**Issue by mdreizin** [gatsbyjs/gatsby#6345]
## Summary

[`gatsby-plugin-robots-txt`](https://github.com/gatsbyjs/gatsby/pull/6344) is a plugin which helps to generate `robots.txt` for your particular environment (e.g. production, development etc).

### Basic example

```js
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-plugin-robots-txt',
      options: {
        env: {
          development: {
            policy: [{ userAgent: '*', disallow: ['/'] }]
          },
          production: {
            policy: [{ userAgent: '*', allow: '/' }]
          }
        }
      }
    }
  ]
};
```

### Motivation

Every time when I start a new `gatsby` project I should add `robots.txt` into `static` folder and configure it manually.

What if we could do that automatically?

The first attempt to solve that issue was [here](https://github.com/gatsbyjs/gatsby/pull/3157). That PR covered only one case - it generates `robots.txt` automatically based, but it doesn't use `gatsby`-internals to set `Sitemap`/`Host` based on `gatsby`-configuration (we have related `siteMetadata.siteUrl` option).

In addition, I would like to have an independent `robots.txt`-configuration for a particular environment (i.e. development, production, deploy preview etc.).

That is why I have created this plugin which does:

- generates `robots.txt` automatically based on your `gatsby`-configuration:

	```js
	module.exports = {
	  siteMetadata: {
	    siteUrl: 'https://www.example.com'
	  },
	  plugins: ['gatsby-plugin-robots-txt']
	};
	```

- allows to have `robots.txt` for a particular environment:

	```js
	module.exports = {
	  siteMetadata: {
	    siteUrl: 'https://www.example.com'
	  },
	  plugins: [
	    {
	      resolve: 'gatsby-plugin-robots-txt',
	      options: {
	        env: {
	          development: {
	            policy: [{ userAgent: '*', disallow: ['/'] }]
	          },
	          production: {
	            policy: [{ userAgent: '*', allow: '/' }]
	          }
	        }
	      }
	    }
	  ]
	};
	```

@KyleAMathews could you please provide feedback?

**Comment by KyleAMathews** [comment]
We haven't been accepting new patients into this repo unless they're core to the Gatsby experience. Do you think most people would want to use this plugin? It definitely seems really nice when you need env specific robots.txt but I'd guess most people don't?

**Comment by mdreizin** [comment]
@KyleAMathews I do agree with you, but from my point of view it is useful and by default it generates what people want to have i.e. like this one:

```
User-agent: *
Allow: /
Sitemap: https://mdreizin.com/sitemap.xml
Host: https://mdreizin.com
```

By the way now it has [3.9K monthly downloads](https://yarnpkg.com/en/packages?q=gatsby-plugin-robots-txt) that means people are using it :)

In further, for instance, you don't need to make such changes, but have `robots.txt` for a particular features, branch etc.

Also I see a lot of possibilities to improve this plugin in further (ie fetch external policies via graphql).

**Comment by mdreizin** [comment]
I will promise to support it :)

**Comment by m-allanson** [comment]
@mdreizin the plugin looks great but I'm going to close this issue - part of the reason that [Gatsby's Plugin Library](https://www.gatsbyjs.org/plugins/) exists is to make it easy for people to discover plugins published by anyone. 

As @KyleAMathews mentioned above, _occasionally_ new plugins will be added here but that's typically when they handle key parts of the core Gatsby experience.
