### ISSUE TITLE
Undocumented parameter in createRemoteFileNode helper

### ISSUE THREAD

**Issue by ajayns** [gatsbyjs/gatsby#6351]
## Description

In the createRemoteFileNode helper in gatsby-source-filesystem, there's a parameter that's used but not documented: https://github.com/gatsbyjs/gatsby/blob/c2b58e0604dd2047c5144f33aa9756f3ca6f7d19/packages/gatsby-source-filesystem/src/create-remote-file-node.js#L278-L285

`createNodeId` I can't seem to find mentioned elsewhere and is confusing so https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-filesystem/README.md#createremotefilenode

**Comment by KyleAMathews** [comment]
It's defined here and passed to all plugins https://github.com/gatsbyjs/gatsby/blob/94761d362016c81738c37b98249e40f926b87b6b/packages/gatsby/src/utils/create-node-id.js

We haven't documented yet the different utilities that are passed to plugins (PRs welcome!!!) but when implementing `createRemoteFileNode` in your plugin, you should pass in the `createNodeId` util function from your plugin to `createRemoteFileNode`

**Comment by ajayns** [comment]
Okay I'd love to help out on this, but let me first understand how it works. So you're saying it's not automatically passed and must be manually passed as a parameter to `createRemoteFileNode` function?

**Comment by KyleAMathews** [comment]
Yeah. All core helper functions like createNodeId are passed into plugins so must also be passed to other helpers.

**Comment by ajayns** [comment]
So wouldn't it be a good idea to mention it here:
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-filesystem/README.md#createremotefilenode

To import it and pass it into the helper while using it. Should I make a PR?

**Comment by m-allanson** [comment]
Yeah that looks like a good place to mention it.

> Should I make a PR?

Yes please!

**Comment by ajayns** [comment]
I think now it's been mentioned in the parameters as well as example, so I think that'd be good enough for users to understand. Although is there any documentation on importing and using `createNodeId` helper? Maybe I could help with that!

**Comment by KyleAMathews** [comment]
Yeah, what we need to do is to add jsdocs for each of the parameters there and then we can create a docs page that queries that info similar to our other API docs pages. If you'd like to do that, this would be a huge contribution!
