### ISSUE TITLE
[v2] PageRenderer Component Documentation

### ISSUE THREAD

**Issue by pgegenfurtner** [gatsbyjs/gatsby#6360]
In the gatsbygram example, a `<PageRenderer />` component, imported from the gatsby package is used. 
Is there any documentation for this? The gatsby package doesn't export it, so I don't understand how it even works. And it works somehow.
I searched here on github and the documentation, but found nothing useful.

**Comment by pieh** [comment]
Hey, what actually gets imported when you import from `gatsby` is here (including `PageRenderer`) - https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/gatsby-browser-entry.js#L50 (this is done with some webpack aliasing).

We would of course welcome docs update to cover this topic! :)

**Comment by m-allanson** [comment]
Huh, I had never noticed that! 

Following the trail, `PageRenderer` actually is exported from Gatsby... In Gatsby's `package.json` the `main` field points to `cache-dir/gatsby-browser-entry.js`:

https://github.com/gatsbyjs/gatsby/blob/7082545076faf7deee02c0e0d98aca8d444f21c1/packages/gatsby/package.json#L168 

Digging in to [`gatsby-browser-entry.js`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/gatsby-browser-entry.js), `PageRenderer` is exported from there. 

[`PageRenderer`](https://github.com/gatsbyjs/gatsby/blob/7082545076faf7deee02c0e0d98aca8d444f21c1/packages/gatsby/cache-dir/page-renderer.js) itself is responsible for making sure resources for the current route are available, before rendering the components for that route. It's also where the [`replaceComponentRenderer` API](https://www.gatsbyjs.org/docs/browser-apis/#replaceComponentRenderer) is used.

In Gatsbygram it's used for the modal rendering. If you visit https://gatsbygram.gatsbyjs.org/ and click one of the images you'll see the URL change and a modal opens on top of the page. https://github.com/gatsbyjs/gatsby/blob/1811a1704fcf48a133d42ddf83d685e7e2931466/www/src/components/layout.js#L74-L148

`PageRenderer` is what renders the background page that the modal sits on top of. It would be useful to add some documentation around this pattern and / or the `PageRenderer` component.

**Comment by pgegenfurtner** [comment]
Thank's for your answers. In a current project, im using the modal rendering. This is why I was wondering about the component.

I could write a guide on how to do this, and use this magically-imported component.

**Comment by m-allanson** [comment]
> I could write a guide on how to do this, and use this magically-imported component.

That would be great!

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
