### ISSUE TITLE
Custom blocks do not add class names defined in blocks

### ISSUE THREAD

**Issue by giraffesyo** [gatsbyjs/gatsby#6366]
## Description

When you create a custom block the class name added is just `custom-block` instead of the class name defined in the config.

### Steps to reproduce

Clone [this demo repo](https://github.com/giraffesyo/gatsby-bug-with-custom-blocks) and run `gatsby develop`. I put a gatsby custom block at the bottom of the hello world post (`http://localhost:8000/hello-world/`)

### Expected result

The string provided as a class name should be used instead of `custom-block`

### Actual result

Only `custom-block` is added

### Environment

(originally ran into this in a windows environment, but made the demo on my mac)
```

  System:
    OS: macOS 10.14
    CPU: x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.3 - ~/n/bin/node
    Yarn: 1.7.0 - ~/n/bin/yarn
    npm: 6.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Safari: 12.0
  npmPackages:
    gatsby: next => 2.0.0-beta.20 
    gatsby-plugin-feed: next => 2.0.0-beta.3 
    gatsby-plugin-google-analytics: next => 2.0.0-beta.2 
    gatsby-plugin-offline: next => 2.0.0-beta.3 
    gatsby-plugin-react-helmet: next => 3.0.0-beta.3 
    gatsby-plugin-sharp: next => 2.0.0-beta.2 
    gatsby-plugin-typography: next => 2.2.0-beta.2 
    gatsby-remark-copy-linked-files: next => 2.0.0-beta.2 
    gatsby-remark-custom-blocks: ^2.0.0-beta.3 => 2.0.0-beta.3 
    gatsby-remark-images: next => 2.0.1-beta.3 
    gatsby-remark-prismjs: next => 3.0.0-beta.3 
    gatsby-remark-responsive-iframe: next => 2.0.0-beta.2 
    gatsby-remark-smartypants: next => 2.0.0-beta.2 
    gatsby-source-filesystem: next => 2.0.1-beta.3 
    gatsby-transformer-remark: ^2.1.1-beta.2 => 2.1.1-beta.2 
    gatsby-transformer-sharp: next => 2.1.1-beta.3 

```

**Comment by giraffesyo** [comment]
I peeked at the source and see that the options are just being passed over to remark-custom-blocks.

The problem is that its not being passed in the right format. Using this instead works:

              blocks: {
                danger: {
                  classes: 'custom-block-danger',
                },
                info: {
                  classes: 'custom-block-info',
                },
              },

**Comment by m-allanson** [comment]
Thanks for creating the demo repo 👍I was fairly sure I had a working demo for this when investigating https://github.com/gatsbyjs/gatsby/issues/5904, but your demo suggests otherwise!
