### ISSUE TITLE
[v2][gatsby-transformer-json] Querying images with relative path result in `null`

### ISSUE THREAD

**Issue by fabe** [gatsbyjs/gatsby#6367]
## Description

I'm trying to use `gatsby-image` with `gatsby-transformer-json` by querying an image via its relative path:

###### content/index.json

```json
{
  "image": "../images/example.jpg"
}
```

The image is successfully found and the GraphQL schema sees `image` as a type `File`, including the `childImageSharp`. However, when using GraphiQL and trying to access any property, `image` always returns `null` without errors.

<img width="280" alt="screen shot 2018-07-10 at 10 19 13 am" src="https://user-images.githubusercontent.com/5220692/42516365-e8401780-842b-11e8-97cc-183ce676b188.png">

### Steps to reproduce

Example repo: https://github.com/fabe/test-gatsby-json-image

Use GraphiQL to query the image specified in the JSON content file.

```graphql
{
  contentJson {
    image {
      id
    }
  }
}
```

### Environment

```
  System:
    OS: macOS High Sierra 10.13.5
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.3 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 61.0
    Safari: 11.1.1
  npmPackages:
    gatsby: next => 2.0.0-beta.20
    gatsby-image: ^2.0.0-beta.5 => 2.0.0-beta.5
    gatsby-plugin-sharp: ^2.0.0-beta.2 => 2.0.0-beta.2
    gatsby-source-filesystem: ^2.0.1-beta.3 => 2.0.1-beta.3
    gatsby-transformer-json: ^2.1.1-beta.2 => 2.1.1-beta.2
    gatsby-transformer-sharp: ^2.1.1-beta.3 => 2.1.1-beta.3
  npmGlobalPackages:
    gatsby-cli: 2.0.0-beta.2
```

**Comment by KyleAMathews** [comment]
Hmm what happens if you have only one instance of gatsby-source-filesystem that's pointed at "src"? This shouldn't matter but perhaps theres a bug.

Also, can you verify that you can query "allFile" and see both files?

**Comment by fabe** [comment]
I'm getting the same result with only one instance pointed at `src`.

`allFile` works as expected, including the sharp processing:

![screen shot 2018-07-10 at 11 11 00 am](https://user-images.githubusercontent.com/5220692/42519397-fa03fd28-8431-11e8-886b-e99259151782.png)

**Comment by fabe** [comment]
It seems that `gatsby-source-filesystem` requires an absolute path to work, otherwise the images won't resolve correctly and show up as `null`, even though everything else works fine.

So instead of:

```js
{
  resolve: `gatsby-source-filesystem`,
  options: {
    name: `content`,
    path: `./src/content`,
  },
},
```

use:

```js
{
  resolve: `gatsby-source-filesystem`,
  options: {
    name: `content`,
    path: `${__dirname}/src/content`,
  },
},
```

Read the docs, I guess. 🤦‍♂️

**Comment by codeincontext** [comment]
Damn, I did exactly the same thing and it took me days to work out why it was silently failing. Nice work @fabe
