### ISSUE TITLE
Can't get images to appear with scss - tried file-loader

### ISSUE THREAD

**Issue by rcwestlake** [gatsbyjs/gatsby#637]
I am having a hard time getting images to appear using `background-image: url()` with scss. I tried to add the `file-loader` and editing the `gatsby-node.js` file, but still get this error: 

![image](https://cloud.githubusercontent.com/assets/9679076/22051656/07ccd624-dd02-11e6-977b-5876d8a87990.png)

This is what my `gatsby-node.js` file looks like: 

![image](https://cloud.githubusercontent.com/assets/9679076/22051686/2452f6fc-dd02-11e6-9c0f-a5974158f958.png)

Any suggestions or fixes?

**Comment by KyleAMathews** [comment]
One quick thing -- you shouldn't be using "export default". Instead use
"exports.modifyWebpackConfig"

**Comment by rcwestlake** [comment]
That did the trick! Thank you @KyleAMathews. For reference and anyone that has a similar issue, this is now my `gatsby-node.js`.

**Comment by ciokan** [comment]
Why post screenshots instead of code?
