### ISSUE TITLE
Update to babel 7 beta 52

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#6371]
## Summary

Update to [babel v7.0.0-beta.52](https://github.com/babel/babel/releases/tag/v7.0.0-beta.52)

### Basic example

Update all the `package.json` files that use `"7.0.0-beta.51"` of babel-related dependencies to use `"7.0.0-beta.52"`

e.g. in `packages/gatsby/package.json`:

https://github.com/gatsbyjs/gatsby/blob/85b25b72a2996bbbbe448b3c4011c72edfa3b89e/packages/gatsby/package.json#L13-L24

Here's a previous update PR https://github.com/gatsbyjs/gatsby/commit/85e59fd31d5228818314cc5731de761b7462dfc9 that can be used as a reference.

### Motivation

Let's keep up to date with the babel betas.

**Comment by beardedpayton** [comment]
@m-allanson I'll take one for the team and tackle this :)

**Comment by beardedpayton** [comment]
@m-allanson PR [here](https://github.com/gatsbyjs/gatsby/pull/6389)

**Comment by jalmarazg** [comment]
Hi, is this issue ready to be closed?

**Comment by m-allanson** [comment]
This was merged and should have been closed, apologies @jalmarazg 🙏
