### ISSUE TITLE
Inline SVG from Contentful

### ISSUE THREAD

**Issue by janosh** [gatsbyjs/gatsby#6372]
What's the best and easiest way to inline an SVG sourced from Contentful?

What I've been doing so far is something like
```
<img src={icon.file.url} alt={icon.title} />
```
which has the considerable drawback that it doesn't allow for outside control of the SVG, i.e. I can't change its fill color, hover state, etc.

**Comment by porfirioribeiro** [comment]
I may be wrong but i think you can use it like this
```svg
<svg viewBox="0 0 193 57">
  <use xlink:href="theurlto.svg"></use>
</svg>
```

**Comment by JanoshRiebesell** [comment]
@porfirioribeiro Thanks for the quick reply! I tried your suggestion. I had to replace `xlink:href` with React's `xLinkHref` as recommended in [this stackoverflow answer](https://stackoverflow.com/a/32994814/4034025) for it to compile. Problem is, the SVGs don't show up. I just get white space. Not sure what the problem is. I thought it might be that the `<use>` tag inside `<svg>` has zero height and width which the Chrome inspector confirmed. But I was unable to change that even by setting explicit values in the dev tools.

**Comment by porfirioribeiro** [comment]
Yeah right, i copied from the generated html not from the react source :no_good_man: 

Well i am using this for sprites width svg's symbols but i tough it would work with the full svg.

By the way, if the only thing you want is a simple color change, you can put fill="currentColor" and then set the css color of the parent.

**Comment by JanoshRiebesell** [comment]
Are your sprites coming from Contentful? Maybe it is related to the source rather than whether its a full or a sprite svg.

**Comment by porfirioribeiro** [comment]
Nop, mine are local using svg-sprite-loader so yeah, it's a diferent story :-1: 
https://css-tricks.com/svg-use-with-external-reference-take-2/

**Comment by zslabs** [comment]
Very interested in this topic as well. Working with the Netlify CMS that has certain content in `yml` files, so getting a generic source to an asset I'd like to inline is difficult since Webpack normally expects you to import this content at the top of the file.

**Comment by braco** [comment]
Agree this would be a nice source transformation. Inlining is difficult from headless CMSes, I'm having this problem with Wordpress right now. I would expand this topic to something more like "Inlining external SVG"

**Comment by PoppinMic** [comment]
Same issue here. I am getting various colored svgs from a headless WordPress. I am currently using `publicURL` from graphql but later realized I will need to manipulate the colors of these svg icons. My code is like `<object data={svgPublicURL} type="image/svg+xml" />`.

I have searched through and found something like image-webpack-loader but I think it will require my to import svg file at the beginning. It will be super handy if we can have a choice to "Inlining external SVG" like @braco mentioned.

**Comment by PoppinMic** [comment]
For anyone who is looking an answer like I was. There is a library from react [https://github.com/gilbarbara/react-inlinesvg](url) and this can convert svg served remotely to inline-svgs.

**Comment by yaroslav-perec** [comment]
@PoppinMic Hi! 

I tried to use `react-inlinesvg`, but I got the following error `Access has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
Maybe you know how to fix it?

**Comment by in-in** [comment]
What if you try to use webpack [require.context](https://webpack.js.org/guides/dependency-management/#requirecontext) for inline svg?

For example:

```js
// icon.js
import React from "react"

const Icon = ({ filename, classname }) => {
  const req = require.context(`../../images/icons`, true, /\.svg$/)
  const IconTag = req(`./${filename}.svg`)

  return <IconTag className={classname} />
}

export default Icon
```

```js
// social.js
import React from "react"
// ...
import Icon from "../icon"

const Social = () => {
 // ...
  return (
    <ul className={st.social}>
      {data.allSocialItemsJson.edges.map(item => (
        <li className={st.social__item} key={item.node.name}>
          <a
            target="_blank"
            rel="noopener noreferrer"
            href={item.node.url}
            className={st.social__link}
          >
            <Icon
              filename={`social/${item.node.name}`}
              classname={st.social__icon}
            />
          </a>
        </li>
      ))}
    </ul>
  )
}

export default Social
```

Folder structure:

```shell
.
├── images
│   ├── icons
│   │   ├── social
│   │   │   ├── facebook.svg
│   │   │   ├── medium.svg
│   │   │   ├── telegram.svg
│   │   │   └── twitter.svg
```

**Comment by PoppinMic** [comment]
@yaroslav-perec Hi, I think your problem is realted to general `CORS` issues. Google the keyword `CORS`. This should config on your server side

**Comment by alexeychikk** [comment]
@in-in I've noticed that importing via `require.context` creates copy of the context in each chunk. Using webpack-bundle-analyzer I can see that `assets/icons/flags` are duplicated:
![image](https://user-images.githubusercontent.com/10129207/73611858-10d33980-45ef-11ea-9a38-b0f784e65953.png)
