### ISSUE TITLE
How do I add images to my blog posts?

### ISSUE THREAD

**Issue by elamahpla** [gatsbyjs/gatsby#6374]
First: I've read the docs. All the ones pertaining to this, I've read. I'm pretty sure I'm missing something, but I don't know what. I have a lot of blog posts and a lot of images. I've tried everything I can think of, changing the pathing, changing the location of the file(s) (The images folder), as well as the src="" pathing. None of it works. 

https://gist.github.com/elamahpla/ce32531ef210fe42b0cf582154076fb1

Is my config file. This is one of the last steps I'm on to finishing this, so I'm incredibly eager to get it done, but I can't seem to figure out what exactly I'm missing. My initial thought was a graphql query, but the docs for [remark-image](https://www.gatsbyjs.org/packages/gatsby-remark-images/?=remark) don't show that I need a query. 

I feel like I'm actually lost here and literally, any help would be appreciated.

**Comment by KyleAMathews** [comment]
Perhaps it's because you have `gatsby-transformer-remark` added there twice? Hmmm perhaps we should warn when transformers are added twice 🤔

**Comment by elamahpla** [comment]
Oh boy, let me clear that up and report back, it's been a long day.

**Comment by elamahpla** [comment]
[Update Here](https://gist.github.com/elamahpla/27467b75785869c1c93ef310fe106bb4)

**Comment by KyleAMathews** [comment]
Want to try playing with the using-remark example site? https://github.com/gatsbyjs/gatsby/tree/master/examples/using-remark

**Comment by elamahpla** [comment]
Yeah, I did that earlier too. I've gone through the steps, searched all the blogs. I'll do it again so I can post results, just to ensure.

**Comment by elamahpla** [comment]
```
<!-- &lt;img src="./randomtest.jpg" alt=""&gt;

<!-- <img className="imagetest" src="../../images/randomtest.jpg">

<!-- <img className="imagetest" src="./randomtest.jpg">

![](./randomtest.jpg)

![](randomtest.jpg)

![](../../images/randomtest.jpg)

![randomtest](./randomtest.jpg) -->
```

Is what I had before even making the issue/request. I had checked your above link earlier in the day but didn't gain too much from it. If there's a graphql query I need, then that's most likely what it is, but it's not mentioned in docs 🤷‍♂️

**Comment by KyleAMathews** [comment]
You did try removing the second gatsby-transformer-remark?

There's no graphql needed — the image processing happens while the markdown is converted to html. And using-remark does work for you?

**Comment by elamahpla** [comment]
[config update three](https://gist.github.com/elamahpla/087f500d5d8723dec71fd7f0eaa28bd2)

I've tried every possible pathing I can think of, and there's no output of the image, at all. If you would like to view the repo I can give access (it's a private repo). I honestly don't know what to do at this point. I keep poking at it, changing small things here and there to see if something will change.

**Comment by KyleAMathews** [comment]
Delete this line https://gist.github.com/elamahpla/087f500d5d8723dec71fd7f0eaa28bd2#file-gatsbyconfig3-js-L33

**Comment by elamahpla** [comment]
Ok, so after I deleted that, I restarted via gatsby develop and it did nothing. However, once I deleted the .cache folder and restarted, it worked perfectly, and my images are showing. Thank you very VERY much for your help.

**Comment by m-allanson** [comment]
Thanks for the update @elamahpla! 

Closing this as it sounds like things are good now 👍
