### ISSUE TITLE
Styled-Components Plugin breaks build after updating gatsby.

### ISSUE THREAD

**Issue by JigzPalillo** [gatsbyjs/gatsby#6383]
— The plugin "gatsby-plugin-styled-components@2.0.11" is exporting a variable named "modifyBabelrc" which isn't an API.

**Comment by dannywils** [comment]
The `modifyBabelrc` api and `gatsby-plugin-styled-components@2.0.11` are only compatible with the Gatsby v1. To use gastby-plugin-styled-components with Gatsby v2, install `gatsby-plugin-styled-components@next` which will correspond to version 3.0.0-beta-x.

**Comment by JigzPalillo** [comment]
Thanks
