### ISSUE TITLE
[v2] Media queries not working with CSS modules

### ISSUE THREAD

**Issue by charlesvdv** [gatsbyjs/gatsby#6393]
## Description

CSS rules inside media queries are not taken into account when using CSS modules. 

### Steps to reproduce

1. Use the [css modules example](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-css-modules) 
2. Apply the patch below 
```diff
--- a/examples/using-css-modules/src/styles/index.module.css
+++ b/examples/using-css-modules/src/styles/index.module.css
@@ -1,4 +1,8 @@
 .index {
+  @media (min-width: 10px) {
+    background-color: red;
+  }
+
   color: tomato;
   padding: 3rem;
   font-size: 3rem;
```

### Expected result

The background should be red.

### Actual result

The background is unchanged.

### Environment

Unfortunately, `gatsby info` crashes (looks like a `envinfo` crash https://github.com/tabrindle/envinfo/issues/51).

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LeKoArts** [comment]
> Nesting case like that isn't a native css feature right? You need sass or postcss for that correct?

Yeah, correct.

**Comment by m-allanson** [comment]
You can write your media query like:

```css
@media (min-width: 10px) {    
  .index {
    background-color: red;  
  }
}
```

Or as mentioned above, use CSS processor that understands the nested media query syntax. Closing this as it's not Gatsby specific.

**Comment by charlesvdv** [comment]
Oh sorry I wasn't aware that this syntax wasn't supported by CSS natively. Thanks for the help and the good work on Gatsby :+1:

**Comment by m-allanson** [comment]
No problem, happy Gatsbying!
