### ISSUE TITLE
Gatsby v2 Landing Page Broken on IE11

### ISSUE THREAD

**Issue by shelldandy** [gatsbyjs/gatsby#6398]
v1 landing is fine, but v2 looks like this:

![screen shot 2018-07-11 at 6 22 23 pm](https://user-images.githubusercontent.com/7088511/42604319-ba436488-8537-11e8-81b0-9e38162322e2.png)

**Comment by m-allanson** [comment]
Oh dear, let's get that fixed. Thanks @shelldandy 👍

**Comment by anantoghosh** [comment]
@m-allanson I made a pr for this.
But `gatsby develop` does not work on IE 11 after gatsby@beta.13, build still works. Is using `develop` in IE 11 supported? It has made testing on IE much harder.
```
SCRIPT5022: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead.
invariant.js (49,5)
SCRIPT5022: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead.
react-dom.development.js (16543,5)
```
I think it was after this commit https://github.com/gatsbyjs/gatsby/commit/2fd9026d0d5d326f104e9abb8e8ee1429a8dd846 but I'm not sure

**Comment by pieh** [comment]
This was fixed in https://github.com/gatsbyjs/gatsby/pull/6414 . Thanks @anantoghosh!

**Comment by msachi** [comment]
@anantoghosh Did you find a way to get `gatsby develop` to work on IE? We are trying to fix an IE issue and it's difficult to debug in production.

**Comment by anantoghosh** [comment]
@msachi develop does not work on ie. Maybe you could find something from this discussion https://github.com/gatsbyjs/gatsby/issues/7003#issuecomment-411652294. You could try using using a custom babel config. All I can say is that the error is because of polyfills not being loaded when using `develop`

**Comment by shelldandy** [comment]
but also on prod sometimes IE doesn't load at all and you can't properly debug since react is on production mode so the errors are not super friendly
