### ISSUE TITLE
Google analytics

### ISSUE THREAD

**Issue by cgarvis** [gatsbyjs/gatsby#64]
Need to be able to fire off page views to google analytics.

**Comment by KyleAMathews** [comment]
Not documented yet but there's a `onRouteChange` hook you can use. See https://github.com/KyleAMathews/blog/blob/e590c31a1b0f9f72b3725f40664cf064fd4595f6/app.coffee#L15-L20

**Comment by SachaG** [comment]
How do you get that `app.coffee` (or in my case `app.js`) file to be loaded?

**Comment by KyleAMathews** [comment]
@SachaG you need to export a function from gatsby-browser.js called `onRouteUpdate`. This will be called on every route change. https://github.com/gatsbyjs/gatsby#structure-of-a-gatsby-site

**Comment by SachaG** [comment]
Thanks, here's what I ended up with in my `gatsby-browser.js` file:

```js
import ReactGA from 'react-ga';
ReactGA.initialize('UA-xxxxxx-x');

exports.onRouteUpdate = (state, page, pages) => {
  ReactGA.pageview(state.pathname);
};

```

I'm not sure if that's the best way to do it though. I'm using [React-GA](https://github.com/react-ga/react-ga) btw.

**Comment by KyleAMathews** [comment]
Seems reasonable!

**Comment by GuillaumeHaben** [comment]
Hi !

The `gatsby-browser.js` file in the starter I use ([https://github.com/wpioneer/gatsby-starter-lumen](https://github.com/wpioneer/gatsby-starter-lumen)) is empty. I've tried your way but I can't get any infos on Google Analytics. Any idea @SachaG ?

**Comment by KyleAMathews** [comment]
@GuillaumeHaben can you post the code you're using?

**Comment by GuillaumeHaben** [comment]
@KyleAMathews I'm using the same code as Sasha (except with my GA id instead of xxxxx). I've also installed react-ga.

**Comment by KyleAMathews** [comment]
We'd need more info to help. It sounds like it should work. Is there errors
in the browser console? Can you add a console.log to your Gatsby-browser.js
and the message shows?

**Comment by GuillaumeHaben** [comment]
You can check my repo [here](https://github.com/GuillaumeHaben/personnal-website). I tried the html.js and the `gatsby-browser.js` method but it doesn't work. There is nothing in the console.
A console log in my `gatsby-browser` file doesn't show neither. Is there any thing I have to do to link it to my project ?

**Comment by KyleAMathews** [comment]
Glad you got it working!

And I should finish converting my blog out of Coffeescript — that it's mixed JS/CS right now is confusing.

**Comment by timarney** [comment]
Is the setup described here https://github.com/gatsbyjs/gatsby/issues/64#issuecomment-241603681 the "correct way" to setup analytics?

Add a file called gatsby-browser.js with and add the following code?
```javascript
import ReactGA from 'react-ga';
ReactGA.initialize('UA-xxxxxx-x');

exports.onRouteUpdate = (state, page, pages) => {
  ReactGA.pageview(state.pathname);
};
```

**Comment by franzejr** [comment]
I did what @timarney did, but I got `path is required in .pageview()`. Any clue?

**Comment by franzejr** [comment]
I got it working using: `onClientEntry`.

```javascript
import ReactGA from "react-ga";
ReactGA.initialize("UA-XXXX");

exports.onClientEntry = () => {
  ReactGA.set({ page: window.location.pathname });
  ReactGA.pageview(window.location.pathname);
};
```

**Comment by calpa** [comment]
@franzejr I find that the `pathname` is inside `state.location`, so change the code to:
```
import ReactGA from 'react-ga';
ReactGA.initialize('UA-xxxxxx-x');

exports.onRouteUpdate = (state, page, pages) => {
  ReactGA.pageview(state.location.pathname);
};
```
