### ISSUE TITLE
Use fast-glob over standard glob?

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#6404]
https://github.com/mrmlnc/fast-glob/blob/master/README.md

Parcel just switched https://github.com/parcel-bundler/parcel/pull/1650

**Comment by tryzniak** [comment]
Is it too early to work on it? I'd like to explore and work it :)

**Comment by m-allanson** [comment]
Feel free to jump in and give it a go :)

There's a new [`benchmarks`](https://github.com/gatsbyjs/gatsby/tree/master/benchmarks) directory that contains a couple of large benchmark sites. It'd be interesting to get some before and after numbers to see how much of a difference `fast-glob` makes.

**Comment by KyleAMathews** [comment]
@tryzniak have at it! Yeah, first things first is to change 1 or 2 of our uses of glob to fast-glob and benchmark how much of a difference the change makes.

**Comment by tryzniak** [comment]
So I tried switching over to fast-glob, and there wasn't any significant difference. In fact, most of the time it was slower haha. I benchmarked it by building gatsby's website, you can checkout the [code](https://github.com/tryzniak/gatsby/blob/7324fd6f6f12ef5b2bb52e8d18ebb44e75d0ecee/packages/gatsby/src/internal-plugins/query-runner/query-compiler.js#L91). 
Maybe fast-glob is really fast when there are millions of files to go over, but in gatsby's case, node-glob seems to be enough.

**Comment by tryzniak** [comment]
And I also forgot to mention, that globbing doesn't seem to be expensive, it takes somewhere around 20ms on 2 GHz Intel Core i5.

**Comment by m-allanson** [comment]
Thanks for investigating @tryzniak! I'd love to see the before and after numbers if you still have them lying around?

**Comment by KyleAMathews** [comment]
Thanks! Yeah, numbers would be great + which usages of glob did you change?

**Comment by tryzniak** [comment]
Ouch, I forgot about the numbers. Here they are:

| glob (ms)  |  fast-glob (ms) |
|--:|--:|
| 8.897 | 28.291 |
| 9.009 | 19.755 |
|8.740 | 20.457 |
|12.479 | 32.580 |
|8.639 | 25.535 |
|12.382 | 19.545 |
|10.491 | 19.500 |
|8.996 | 20.217 |
|9.057 | 19.598 |
|8.702 | 20.063 |

I only tested on the snippet provided below. I used `console.time("glob")...console.timeEnd("glob")` to measure time.
https://github.com/gatsbyjs/gatsby/blob/1194951c0f75a3707aed560d7cee669b463ab16b/packages/gatsby/src/internal-plugins/query-runner/query-compiler.js#L90-L95

I'll take a look at some other places where glob is used and replace it with fast-glob.

**Comment by pieh** [comment]
Huh, so `fast-glob` is actually slower than `glob`?

**Comment by tryzniak** [comment]
Yeah, I was very surprised at the results haha. `glob` looks to be just fine for gatsby. 
I checked some other places like [1](https://github.com/gatsbyjs/gatsby/blob/26c1fbe85fb311a0bcfee0478fd346da22da0d71/packages/gatsby/src/commands/develop.js#L4), [2](https://github.com/gatsbyjs/gatsby/blob/26c1fbe85fb311a0bcfee0478fd346da22da0d71/packages/gatsby/src/utils/api-runner-node.js#L119), and `glob` performs there in under 6.172 and 0.069 ms. I don't think we can gain anything here.

**Comment by KyleAMathews** [comment]
Cool! Let's close this then as we have plenty of other perf issues to work on and this seems like a wash. Thanks for investigating! Very helpful!
