### ISSUE TITLE
[v2] Gatsby Plugin Emotion docs should be updated to use next

### ISSUE THREAD

**Issue by deadcoder0904** [gatsbyjs/gatsby#6406]
Check the docs at https://next.gatsbyjs.org/packages/gatsby-plugin-emotion & it should provide installation step as `npm i -S gatsby-plugin-emotion`

**Comment by deadcoder0904** [comment]
It threw error while using v1.1.17 while deploying to Netlify

```bash
The plugin "gatsby-plugin-emotion@1.1.17" is exporting 
a variable named "modifyBabelrc" which isn't an API.
```

**Comment by LeKoArts** [comment]
I don‘t think it makes sense to change this (and all other plugin‘s) README to use @next just to remove all these notes again when v2 is officially out. The migration guide tells the user to just use @next everywhere and I think that’s a good solution.

**Comment by deadcoder0904** [comment]
Cool I missed the migration guide since I started with v2
