### ISSUE TITLE
Output date so it's broken out in to separate div's for Day/Month/Year

### ISSUE THREAD

**Issue by frazerf** [gatsbyjs/gatsby#6409]
So I'm using headless Wordpress in conjunction with Gatsby.js and I'm outputting the date of posts via a graphql query as below - 

````
query MyFiles {
  allWordpressPost {
    edges {
      node {
        title
        excerpt
        slug
        date(formatString: "MMMM DD YYYY")
        featured_media {
          source_url
          localFile {
            childImageSharp {
              sizes(maxWidth: 500) {
                src
              }
            }
          }
        }
      }
    }
  }
}
````

That's all working fine however I'm wanting to output the date in a slightly different layout, like - 

```
<div>Day</div>
<div>Month</div>
<div>Year</div>
```

Does anyone know if this is possible? Or have any links that could point me in the right direction?

**Comment by KyleAMathews** [comment]
Query the date three times for each format. You'll need to use aliases for the field. Here's an article which explains how to use them.

https://medium.com/graphql-mastery/graphql-quick-tip-aliases-567303a9ddc5

**Comment by frazerf** [comment]
Thanks @KyleAMathews - exactly what I was after!
