### ISSUE TITLE
Docs for gatsby v2 includes installation process for v1

### ISSUE THREAD

**Issue by kmcaloon** [gatsbyjs/gatsby#6410]
The docs over at https://next.gatsbyjs.org/docs/ are for v2 beta, yet the Get Started instructions are for v1. They should be updated to show how to install v2 without starter.

**Comment by pieh** [comment]
Would like to create PR to update it? I think we would only need to adjust `gatsby new gatsby-site` to point to v2 starter there

**Comment by kmcaloon** [comment]
Sure, I can create a PR, but we would need to actually use a starter as opposed to a fresh install? For the latter, I know `npm install gatsby@next` works, but I think the plan is to stick with the CLI commands within the docs right?

**Comment by pieh** [comment]
We can use `gatsby new my-default-project https://github.com/gatsbyjs/gatsby-starter-default#v2` (as mentioned in https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#starting-a-new-project-with-gatsby-v2 ).

`gatsby new` always uses starter - just by default (if not specified) it will use master branch of `gatsby-starter-default`

**Comment by LekoArts** [comment]
Since Gatsby v2 has been released, this issue is resolved.
