### ISSUE TITLE
How do I get css modules working with Gatsby v2

### ISSUE THREAD

**Issue by tsmith123** [gatsbyjs/gatsby#6411]
I thought I would give v2 a try but I seem to be having issues getting css modules working. They worked fine with v1.

I'm using `onCreateWebpackConfig` but there doesn't seem to be much documentation on this yet (understandably). Has anyone managed to get this working yet? 

```
exports.onCreateWebpackConfig = ({
  stage,
  rules,
  loaders,
  plugins,
  actions,
}) => {
  actions.setWebpackConfig({
    module: {
      rules: [
        {
          test: /\.scss$/,
          use: [
            loaders.miniCssExtract(),
            loaders.css({ importLoaders: 1 })
            loaders.postcss(),
            `sass-loader`,
          ],
        },
      ],
    },
    plugins: [
      plugins.define({
        __DEVELOPMENT__: stage === `develop` || stage === `develop-html`,
      }),
    ],
  })
}
```
I’m using scss files.

I'm getting errors like this during `gatsby develop`:

> Module build failed (from ./node_modules/babel-loader/lib/index.js):
> Error: Cannot use styleName attribute for style name 'block' without importing at least one stylesheet.

Also, do I still need to use `gatsby-plugin-react-css-modules`?

**Comment by anantoghosh** [comment]
You do not need add anything extra to use css modules. Just name your css files as `filename.module.css`.
Works with css/sass/scss/less/styl

**Comment by tsmith123** [comment]
Here's another error I'm getting:

```
ERROR in ./src/containers/General/General.module.scss 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
> @import '../../styles/import';
|
 @ ./src/containers/General/General.js 13:0-31
 @ ./src/containers/General/index.js
```

**Comment by anantoghosh** [comment]
Did to install `gatsby-plugin-sass`? That's required for the sass part.
You do not need `onCreateWebpackConfig` for modules. It works out of the box.

**Comment by tsmith123** [comment]
Yes, I have the `gatsby-plugin-sass` installed (which I think has solved latest error shown) and I've removed `onCreateWebpackConfig` but still doesn't work. Still getting errors like this:

> Module build failed (from ./node_modules/babel-loader/lib/index.js):
> Error: Cannot use styleName attribute for style name 'block' without importing at least one stylesheet.
>     at styleNameValue.split.filter.map.styleName (/Users/thomassmith/dev/mysite/node_modules/babel-plugin-react-css-modules/dist/getClassName.js:72:13)
>     at Array.map (<anonymous>)

I'm using the provided `.babelrc` if that's relevant?

```
{
  "cacheDirectory": true,
  "babelrc": false,
  "presets": [
    [
      "@babel/preset-env",
      {
        "loose": true,
        "modules": false,
        "useBuiltIns": "usage",
        "shippedProposals": true,
        "targets": {
          "browsers": [">0.25%", "not dead"]
        }
      }
    ],
    [
      "@babel/preset-react",
      {
        "useBuiltIns": true,
        "pragma": "React.createElement"
      }
    ],
    "@babel/preset-flow"
  ],
  "plugins": [
    [
      "@babel/plugin-proposal-class-properties",
      {
        "loose": true
      }
    ],
    "@babel/plugin-syntax-dynamic-import",
    [
      "@babel/plugin-transform-runtime",
      {
        "helpers": true,
        "regenerator": true,
        "polyfill": false
      }
    ],
    [
      "babel-plugin-module-resolver",
      {
        "root": [
          "./src"
        ],
        "alias": {
          "@actions": "./src/actions",
          "@action-types": "./src/actionTypes",
          "@assets": "./src/assets",
          "@components": "./src/components",
          "@constants": "./src/constants",
          "@containers": "./src/containers",
          "@helpers": "./src/helpers",
          "@reducers": "./src/reducers",
          "@styles": "./src/styles"
        }
      }
    ]
  ]
}
```

**Comment by tsmith123** [comment]
My `gatsby-config` looks like this:

```
    ...
    {
      resolve: `gatsby-plugin-react-css-modules`,
      options: {
        filetypes: {
          '.scss': { syntax: `postcss-scss` }
        },
        exclude: `/global/`
      }
    },
    `gatsby-plugin-sass`,
    ...
```

**Comment by anantoghosh** [comment]
No need to use `gatsby-plugin-react-css-modules`, just remove it.
https://next.gatsbyjs.org/tutorial/part-two/#css-modules

**Comment by LeKoArts** [comment]
If you didn’t change the default babelrc file you can remove it as it‘ll be used automatically

**Comment by tsmith123** [comment]
I added alias’ to it

**Comment by tsmith123** [comment]
@anantoghosh that looks to have sorted it. Thanks for the help.
