### ISSUE TITLE
Server-side rendering is not working for Rebass

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#6413]
## Description

When using [Rebass](https://jxnblk.com/rebass/) along with [styled-components](https://www.styled-components.com/) and [gatsby-plugin-styled-components@next](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-styled-components), `gatsby build` results in a page full of JS, without CSS.

### Steps to reproduce

1. `git clone https://github.com/kripod/gatsby-starter-modern.git`
2. `yarn`
3. `yarn build`
4. `serve public`

### Expected result

Server-side rendering [should just work](https://jxnblk.com/rebass/server-side-rendering/).

### Environment

```
  System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
  Binaries:
    Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.0.0-beta.9 => 2.0.0-beta.29
    gatsby-plugin-react-helmet: ^3.0.0-beta.2 => 3.0.0-beta.3
    gatsby-plugin-styled-components: ^3.0.0-beta.2 => 3.0.0-beta.2
```

### File contents (if changed)

`gatsby-config.js`:

```js
module.exports = {
  siteMetadata: {
    title: 'Gatsby Modern Starter',
    language: 'en',
  },
  plugins: ['gatsby-plugin-react-helmet', 'gatsby-plugin-styled-components'],
};
```

**Comment by KyleAMathews** [comment]
Does the styled-components example site work for you? Do you have a reproduction of this problem?

**Comment by kripod** [comment]
Oops, it turns out that the styles get inlined instead of loading them from a `.css` file. Sorry for the inconvenience! (Although, it's still a bit stunning how much JS gets rendered for such a little project...)

**Comment by KyleAMathews** [comment]
Oh good!

Curious what you mean by "just rendering"?

**Comment by KyleAMathews** [comment]
"js rendering" thanks autocorrect

**Comment by kripod** [comment]
I mean that a lot of JS is being emitted to the final website, see https://gatsby-starter-modern-demo.netlify.com/. Is that normal?

**Comment by KyleAMathews** [comment]
Like the job bundles that are created? How big  are they?

**Comment by kripod** [comment]
8 JS files and 1 JSON file gets created. Size doesn't matter as much as the number of HTTP/1.1 requests do.

**Comment by KyleAMathews** [comment]
They're all requested at the same time on your site?

**Comment by kripod** [comment]
It seems so, please see the source of https://gatsby-starter-modern-demo.netlify.com/ for further details.

**Comment by KyleAMathews** [comment]
There's 5 initial JS requests. Once the JS loads, Gatsby starts prefetching other needed resources, including JS files, for linked pages.

<img width="837" alt="screen shot 2018-07-12 at 2 12 18 pm" src="https://user-images.githubusercontent.com/71047/42659600-9f218b5c-85dd-11e8-9b0e-ef5da0207d85.png">

All modern browsers can do 6+ parallel requests over http 1.1. and unlimited essentially over http 2 https://stackoverflow.com/questions/985431/max-parallel-http-connections-in-a-browser (well, or ~100 parallel requests in http/2 it looks like https://stackoverflow.com/questions/39759054/how-many-concurrent-requests-should-we-multiplex-in-http-2)

**Comment by kripod** [comment]
Thank you for the kind assistance! I'm not concerned anymore.
