### ISSUE TITLE
Does gatsby support content splitting?

### ISSUE THREAD

**Issue by kunxi** [gatsbyjs/gatsby#642]
I found the example site is lightening fast, and also found no data is fetched during the navigation. Out of curiosity, I dig into the `public` folder,  found all content are bundled in the bundle.js. That is a pretty interesting approach, but should we limit the payload for the first load for better user experience?

So I wonder whether gatsby can just load minimum required assets in the first load, and load other contents on demand?

**Comment by KyleAMathews** [comment]
This is coming in 1.0! https://github.com/gatsbyjs/gatsby/issues/431
