### ISSUE TITLE
Broken link in blog post "Announcing Gatsby v2 beta launch!"

### ISSUE THREAD

**Issue by wildpow** [gatsbyjs/gatsby#6420]
There is a broken link at the url:
 [Announcing Gatsby v2 beta launch!](https://next.gatsbyjs.org/blog/2018-06-16-announcing-gatsby-v2-beta-launch/)
When you click on the link to the 'migration guide'  under the Get involved section of the blog post it produces this:
<img width="1092" alt="screen shot 2018-07-12 at 3 03 07 pm" src="https://user-images.githubusercontent.com/17464319/42671648-f16bc8d6-8615-11e8-89b4-82e790251236.png">

**Comment by pieh** [comment]
Thanks for report - created #6473 PR to fix this!
