### ISSUE TITLE
Master broken due to html-renderer.js rename

### ISSUE THREAD

**Issue by LegNeato** [gatsbyjs/gatsby#6421]
https://github.com/gatsbyjs/gatsby/commit/02965d6bcb31b910ca0a53bf3ed4f5c448ea9198 renamed `html-renderer.js` when the develop command is still looking for the old name.

**Comment by LegNeato** [comment]
Temporary workaround is to pin to `2.0.0-beta.29` rather than `next` in `package.json`.

**Comment by poutsopretty** [comment]
gatsby 2.0.0-beta.32

info bootstrap finished - 4.276 s

error The "id" argument must be of type string. Received type object
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object
