### ISSUE TITLE
Bind axios api call server side while `gatsby build` 

### ISSUE THREAD

**Issue by sachingvit** [gatsbyjs/gatsby#6424]
I want to write an REST API call for the time of page is building, Its simile like we write GraphQL in template and at the time of build query trigger to get data on server and bind the response wit the page. In the same fashion I am also want to write one axios call and the data of the query will also be bind to the page after build. 

Is there any way to implement this problem statement?

"gatsby": "1.9.246"

**Comment by m-allanson** [comment]
Does this tutorial help? https://www.gatsbyjs.org/docs/source-plugin-tutorial/

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
