### ISSUE TITLE
[www - transformer-screenshot - createRemoteFileNode] network error handling issues

### ISSUE THREAD

**Issue by anantoghosh** [gatsbyjs/gatsby#6429]
I was working on the gatsbyjs.org website and randomly getting different errors on gatsby build. Most commonly:
```js
TypeError: Cannot read property 'id' of null

  - gatsby-node.js:133
    [www]/[gatsby-transformer-screenshot]/gatsby-node.js:133:39

  - Generator.next

  - next_tick.js:131 _combinedTickCallback
    internal/process/next_tick.js:131:7

  - next_tick.js:180 process._tickCallback
    internal/process/next_tick.js:180:9
```

It looks like transformer screenshot tries to create a `screenShotNode` even if the network request in `createRemoteFileNode` fails and returns null. https://github.com/gatsbyjs/gatsby/blob/fb3232915287ff1a2ffa5fa6f97b23fa27d3a922/packages/gatsby-transformer-screenshot/src/gatsby-node.js#L84.
Since all other screenshot image requests are being downloaded concurrently, as soon as the error occurs (or if ctrl-c at this stage), the cache gets messed up with partially downloaded files. Any subsequent `gatsby build` ignores the screenshot transformer and starts throwing *different* errors like
`WebpackError: TypeError: Cannot read property 'slug' of null`
or
`Cannot read property 'allMarkdownRemark' of null.`
or
`/Develop/gatsby/www/src/pages/showcase.js
error GraphQL Error Unknown field 'fields' on type 'SitesYaml'`
<hr />
The points I want to make are

* Networks related errors should not be hidden by createRemoteFileNode (it just returns null on error) https://github.com/gatsbyjs/gatsby/blob/554d8ec74cf94ca189b34ca0d1a5b74e810090e9/packages/gatsby-source-filesystem/src/create-remote-file-node.js#L232
* Screenshot transformer should not break due to network errors
* On the gatsby website, if the error occurs at screenshot stage (source and transform nodes) or if the process is killed, the next build does not try to fetch the images again, throws a different error.
* Allow users to set the timeout and concurrency option in createRemoteFileNode. 9/10 of the times my build failed because connection got timed out or received code 'ECONNRESET' trying to download so many images on my network. And since the cache breaks, it has to deleted and all the downloads have to be restarted.

To replicate the issue, on the gatsby website project, delete any cache and set https://github.com/gatsbyjs/gatsby/blob/554d8ec74cf94ca189b34ca0d1a5b74e810090e9/packages/gatsby-source-filesystem/src/create-remote-file-node.js#L137 to something really small so that the network requests gets timed out.
 then try `gatsby build` multiple times

**Comment by pieh** [comment]
Would You be interested in creating PR with fixes? 

I agree that network issues in `createRemoteFileNode` should throw rather than return null (tho this would be breaking change I guess, as plugins that utilize it would need to add handling for that).

Setting `concurrency` etc for it would be great too, just not sure what's the best way to do so - we would have to figure out how to do it first - would it be new entry in `gatsby-config.js`? Would it be env var?

**Comment by anantoghosh** [comment]
env variable makes sense because it will be environment related. For the CI or other servers we would have a high number, and different for home/work networks.
I'm a bit busy this week, but I'll try to make some time for the pr.

**Comment by Pr0x1m4** [comment]
Was this resolved? I've been trying to build website docs on a slow connection and have been plagued by these errors. I assuming it's because of the timeout errors @anantoghosh spoke about.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
