### ISSUE TITLE
[v1] stylus plugin use and import cannot work together

### ISSUE THREAD

**Issue by breeswish** [gatsbyjs/gatsby#6431]
## Description

I'm using the following config:

```js
    {
      resolve: 'gatsby-plugin-stylus',
      options: {
        use: [
          ...
        ],
        import: [
          ...
        ],
      },
    },
```

The plugins in `use` are not taking effect.

In fact, I did a config dump in the stylus plugin, and seems that the second `config.merge` for `import` overrides the first config merge for `use`:

```js
    config.merge(function (current) {
      current.stylus = {
        import: options.import
      };
      return current;
    });
```

The merge result is that fields in `stylus` got replaced, instead of merged.

### Environment

  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 5.2 - /bin/zsh
  Binaries:
    Node: 8.11.3 - /usr/local/bin/node
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 60.0.2
    Safari: 11.1.1
  npmPackages:
    gatsby: ^1.9.273 => 1.9.273 
    gatsby-link: ^1.6.45 => 1.6.45 
    gatsby-plugin-nprogress: ^1.0.14 => 1.0.14 
    gatsby-plugin-preact: ^1.0.17 => 1.0.17 
    gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11 
    gatsby-plugin-sharp: ^1.6.48 => 1.6.48 
    gatsby-plugin-stylus: ^1.1.21 => 1.1.21 
    gatsby-plugin-typography: ^1.7.19 => 1.7.19 
    gatsby-remark-autolink-headers: ^1.4.19 => 1.4.19 
    gatsby-remark-copy-linked-files: ^1.5.37 => 1.5.37 
    gatsby-remark-images: ^1.5.67 => 1.5.67 
    gatsby-remark-prismjs: ^2.0.4 => 2.0.4 
    gatsby-transformer-remark: ^1.7.44 => 1.7.44 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
