### ISSUE TITLE
Creating pages with the same path for different locales

### ISSUE THREAD

**Issue by mikeyshing88** [gatsbyjs/gatsby#6434]
## Summary
I want to create multiple pages with the same `path` but with different localized content in one project. For example:

```
usa.com/landing-page - displays the English content
france.com/landing-page - displays the French content
```

Currently (and as far as I know), this is not possible because if my Gatsby build creates the `usa` page first, it will just get overridden once it builds the `france` page - due to both of these having the same `path`.

I have tried to add the locale into the `path` when creating the page - for example,

```js
 createPage({
    path: `/${locale}/landing-page`,
    component: 'index.js'
});
```

However, this causes an issue within React Router as I would then need to do routing like the below, which is not what I want to achieve:

```js
<Link to="/usa/landing-page">
    Go to landing page
</Link>
```

Is there a way to get around this problem that I am just not seeing? Or is the a way to move the created page into their own separate local folder instead? - for example, once the build creates the `usa` page, it will then move the page into the `usa` directory and have no affect on the routing.

Perhaps its a matter of creating a project for each locale, but I was just curious if anyone has any helpful answers

**Comment by mquandalle** [comment]
Hi,

I'm achieving something similar by using an environment variable and then using `process.env.LANG === "fr"` in the code, including in `gatsby-node.js` to create the appropriate pages with `createPage()`. I then use `LANG=fr gatsby build` to get the french version of the site.

**Comment by mikeyshing88** [comment]
Hi @mquandalle - nice workaround! Would that mean that you loop through each locale and build them separately?

**Comment by pieh** [comment]
Not really possible in single app to do so - You would have to create separate projects or builds (for example using trick from @mquandalle) for each locale.
