### ISSUE TITLE
Publishing to GH-Pages

### ISSUE THREAD

**Issue by rcwestlake** [gatsbyjs/gatsby#644]
For some reason, I can use `gatsby build` to bundle my app, but when I visit the my gh-pages link: https://rcwestlake.github.io/personalsite-react/ it just shows my projects README.md. 

![image](https://cloud.githubusercontent.com/assets/9679076/22167222/44e447a0-df22-11e6-80f4-a573a7990179.png)

I noticed in the docs that a prefixLink may be needed, but is that needed for all my links/routes in my app? Or, do I just need to change the reference in `config.toml` and the rest just happens? It wasn't very clear. 

Here's a link to my repo, if need be: https://github.com/rcwestlake/personalsite-react/tree/gh-pages

Thanks for your help.

**Comment by KyleAMathews** [comment]
You need the NPM package `gh-pages` and add a "deploy" NPM script to your package.json like in the default starter. After setting this up, run it from your command line like `npm run deploy` https://github.com/gatsbyjs/gatsby-starter-default/blob/master/package.json#L37

**Comment by KyleAMathews** [comment]
You'll also need a `prefixLink` set it your config.toml.

**Comment by rcwestlake** [comment]
Thanks. And should the prefixLink be set to the while github domain (rcwestlake.github.io/personalsite-react` or just `/`)

**Comment by KyleAMathews** [comment]
https://github.com/gatsbyjs/gatsby/blob/master/README.md#deploying-to-github-pages-and-other-hosts-where-your-sites-links-need-prefixes

**Comment by rcwestlake** [comment]
Thanks @KyleAMathews. I don't mean to drag this along, however, trying to get my site live for interviews. I followed the docs and for some reason still run into issues. I've looked at your starter documentation and blog source code and don't see anything you've done that I haven't. When I run `npm run deploy` it successfully builds (I think). The screenshot below just stays at Done. Second, the `gh-pages` branch is not created.

![image](https://cloud.githubusercontent.com/assets/9679076/22278873/f28f417a-e283-11e6-9630-645a3dfb955d.png)

Current code: https://github.com/rcwestlake/personalsite-react/tree/rw-fix-build-error

**Comment by KyleAMathews** [comment]
For some reason it looks like the gatsby command isnt running. First verify
your site built correctly by running "gatsby serve-build" then run gh-pages
by itself.

**Comment by rcwestlake** [comment]
When I run it, only part of it appears. So obviously the build command isn't completing.

**Comment by KyleAMathews** [comment]
What are the two "it"s here? :-) Could you paste another screenshot?

**Comment by rcwestlake** [comment]
@KyleAMathews a few things are happening. When I run `npm run build` I believe it successfully builds, however, the process stops at Done: 

![image](https://cloud.githubusercontent.com/assets/9679076/22400004/19d4788c-e567-11e6-80d9-892b5d62ea53.png)

If I run `gatsby serve-build` after closing out of the above command, it says another "something is already running on port 8000" when nothing is. If I just say 'yes', it runs and everything works fine, so that's all good.  

However, when I do `npm run deploy` or `gatsby build --prefix-links`, the commands stop here: 

![image](https://cloud.githubusercontent.com/assets/9679076/22400018/89576d40-e567-11e6-862d-81d53d73ee37.png)

![image](https://cloud.githubusercontent.com/assets/9679076/22400024/baa1d836-e567-11e6-854c-f12d3fad388f.png)


And it doesn't finish. 

This is my `config.toml`. It's the same issue whether I have `http://0.0.0.0:8000/` or `rcwestlake.github.io/personalsite-react/` in the `linkPrefix`. 

![image](https://cloud.githubusercontent.com/assets/9679076/22400038/e347e9c4-e567-11e6-8ccb-419108528f12.png)

However, when I set the `linkPrefix` to just `/` it build and I can run `npm run deploy`.  This doesn't create a `gh-pages` branch. Looking at the `gh-pages` docs, it looks like I may need to add something like this: 

```var ghpages = require('gh-pages');
var path = require('path');
 
ghpages.publish(path.join(__dirname, 'dist'), function(err) { ... });```

**Comment by KyleAMathews** [comment]
If it's stalling when generating HTML, start adding some console.log in
different places to trace down the problem e.g. your html.js file, the
static-entry file inside the Gatsby package etc.

**Comment by rcwestlake** [comment]
![image](https://cloud.githubusercontent.com/assets/9679076/22400209/f92993a6-e56b-11e6-891e-c83922b06425.png)

So when I run `build` it logs in the html.js file before exports and then logs in the render. 

![image](https://cloud.githubusercontent.com/assets/9679076/22400207/e541f5e0-e56b-11e6-9b2c-48135ac835ac.png)

And when I run `deploy`, it gets into the html.js file but doesn't log in the `render` method. 

![image](https://cloud.githubusercontent.com/assets/9679076/22400197/b3484d0a-e56b-11e6-9bd7-febd5bd5d697.png)

Interesting, though... when I run `gatsby build && gh-pages -d public` without the `prefixLink`, it successfully runs through. So it seems the issue is related to `prefixLink`.

**Comment by KyleAMathews** [comment]
Perhaps add some logging to the prefixLink function then?

**Comment by frankoespa** [comment]
ghpages throws me an error **--->** fatal: A branch named 'master' already exists
PS C:\Users\frank\Desktop\Proyectos\perfil> npm run deploy

> gatsby-starter-default@1.0.0 deploy C:\Users\frank\Desktop\Proyectos\perfil
> gh-pages -d public -b master

fatal: A branch named 'master' already exists.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-default@1.0.0 deploy: `gh-pages -d public -b master`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gatsby-starter-default@1.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\frank\AppData\Roaming\npm-cache\_logs\2018-03-23T02_20_42_575Z-debug.log

**Why is this happening ?**

**Comment by cluzier** [comment]
> ghpages throws me an error **--->** fatal: A branch named 'master' already exists
> 
> My site is a User or Organization Page.
> 
> PS C:\Users\frank\Desktop\Proyectos\perfil> npm run deploy
> 
> > gatsby-starter-default@1.0.0 deploy C:\Users\frank\Desktop\Proyectos\perfil
> > gh-pages -d public -b master
> 
> fatal: A branch named 'master' already exists.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! gatsby-starter-default@1.0.0 deploy: `gh-pages -d public -b master`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the gatsby-starter-default@1.0.0 deploy script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\frank\AppData\Roaming\npm-cache_logs\2018-03-23T02_20_42_575Z-debug.log
> 
> **Why is this happening ?**

I am having this issue as well.

**Comment by doubledherin** [comment]
I'm having this issue as well.
