### ISSUE TITLE
Redirected link on documentation - the basics of how a website works

### ISSUE THREAD

**Issue by agarrharr** [gatsbyjs/gatsby#6444]
On the Gatsby 2.0 documentation on [part zero](https://github.com/gatsbyjs/gatsby/blob/0933d6035cb5182c9818c4f41bed114eeceb2df7/docs/tutorial/part-zero/index.md), it links to [https://www.codeschool.com/beginners-guide-to-web-development/how-does-a-website-work](https://www.codeschool.com/beginners-guide-to-web-development/how-does-a-website-work), but this now redirects to [https://app.pluralsight.com/paths/skills/html5](https://app.pluralsight.com/paths/skills/html5). This probably isn't what you want since it requires a paid account, and also, I'm guessing that the old link was a free course or article about the basics of how websites work in general.

I'm not sure where this should link now.

**Comment by agarrharr** [comment]
Here are some ideas:

- https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works
- https://www.youtube.com/watch?v=guvsH5OFizE

**Comment by pieh** [comment]
I don't know what this article covered, but developer.mozilla.org links are usually good choice :)

/cc @shannonbux would first link from @agarrharr ideas list work there?

**Comment by shannonbux** [comment]
I think those both look great @agarrharr and nice to see you again! I read the whole Mozilla doc and watched the whole PBS thing and compared them to a few other sources, and they seem better than most resources!

The only thing that's missing is how a "static site" differs. We don't need to worry about that now, but at some point it'd be cool to find an easy-to-understand resource on that. I watched a lynda.com video on static sites that was incredibly difficult to understand and slow.
