### ISSUE TITLE
babel-plugin-remove-graphql-queries requires graphql@^0.11.7, but gatsby uses ^0.13.2

### ISSUE THREAD

**Issue by langovoi** [gatsbyjs/gatsby#6447]
`babel-plugin-remove-graphql-queries` [requires](https://github.com/gatsbyjs/gatsby/blob/master/packages/babel-plugin-remove-graphql-queries/package.json#L12) `graphql@^0.11.7`, but `gatsby` [used](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/package.json#L69) `^0.13.2`
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/5055595/42714971-8e1cf5f0-86fd-11e8-8626-10e8683ba20f.png">

**Comment by pieh** [comment]
Hey, would you be interested in creating PR that brings `babel-plugin-remove-graphql-queries` graphql dependency to be inline with rest of gatsby packages?
