### ISSUE TITLE
jsx pages are missing data.title (example site is broken)

### ISSUE THREAD

**Issue by rattrayalex** [gatsbyjs/gatsby#645]
Hi, 

When I download and try the example `gatsby-documentation-site` by running `gatsby new gatsby-documentation-site https://github.com/gatsbyjs/gatsby-starter-documentation`, the example does not include the `Some React Code` section on the `/docs` page. 

The `SomeReactCode` [jsx file uses](https://github.com/gatsbyjs/gatsby-starter-documentation/blob/master/pages/docs/some-react-code/index.jsx#L10) a static `metadata` method to try to communicate `title`, but in [the docs template](https://github.com/gatsbyjs/gatsby-starter-documentation/blob/master/pages/docs/_template.jsx#L26), `this.page.routes` has `/docs/some-react-code` with an `undefined` title. 

I also tried setting `exports.data = { title: 'Some React Code' }`, as the docs recommend, and `SomeReactCode.data = { title: 'Some React Code' }`, and similar tactics. None have worked. 

I assume this is a recent regression in the gatsby code that reads metadata (eg; `title`) from jsx files. If you can point me in the right direction I can try to submit a PR. 

`gatsby -V` gives `0.12.28`

Thanks!

**Comment by KyleAMathews** [comment]
Hmmm... the code there is pretty old and yeah, looks out of date. Checkout this post on the blog starter to see what a JSX post looks like — http://gatsbyjs.github.io/gatsby-starter-blog/2016-12-9-react-component-post/

If you have time to debug and create a PR to fix the docs site example, that'd be great!

**Comment by rattrayalex** [comment]
Sorry, to be clear, even following the documentation the feature doesn't work. The example itself isn't the only broken thing. 

I'll try to debug nonetheless but this is my first foray into the codebase...

**Comment by rattrayalex** [comment]
The example [you linked to](https://github.com/gatsbyjs/gatsby-starter-blog/blob/master/pages/2016-12-9-react-component-post/index.js) is what I had in my codebase, which wasn't working.

**Comment by rattrayalex** [comment]
Sorry, having poked around at a few things (changing filename to `.js`, adding a `date` field to `exports.data`, etc) I don't think I'm going to be able to debug this.

This is what I have in my `index.js`, after imports:
```
exports.data = {
  title: 'Some React Code'
  date: `${new Date()}`
}

export default function SomeReactCode() {
  return <div>...</div>
}
```

**Comment by KyleAMathews** [comment]
@jbolda could you check things here?

**Comment by jbolda** [comment]
@KyleAMathews yep! I noticed this issue come up, and it's on the list to look at.

@rattrayalex FYI, the exports.data is statically analyzed. That is, the data is only pulled/refreshed when you first start the dev server. It operates in the same fashion as when you add a new file/post. If that is not the issue, I will take a look later this week.

**Comment by rattrayalex** [comment]
Yeah the issue persists across restarts

**Comment by jbolda** [comment]
I refactored the gatsby-start-documentation page in question and submitted a PR.
https://github.com/gatsbyjs/gatsby-starter-documentation/pull/12

Everything seems to work fine for me. @rattrayalex check out the PR, and let us know if we missed something in the code or docs. Feel free to submit a PR to fix as necessary!

**Comment by jbolda** [comment]
@rattrayalex I believe Gatsby uses the local install by default so it might be worth checking that the node_modules version is up to date.

Is the exports.data a properly formatted object? The only other thing I can think of is that gatsby is eating an error in the object. @KyleAMathews you are more familiar with the error output.

@rattrayalex if my recent PR commits don't work either, would you be able to share a larger snippet? Everything I tried, I can't reproduce.

**Comment by jbolda** [comment]
https://github.com/gatsbyjs/gatsby/issues/645#issuecomment-274342398
RE: properly formatted object. The snippet here looks like it might be missing a comma? I kind of ignored it before since you said you tried a few different things.

**Comment by rattrayalex** [comment]
Yep, sorry, forgot the comma when copy/pasting the example in - my code has one there.

I'll try to take another look...

**Comment by rattrayalex** [comment]
K, I tried updating to `^0.12.28` and still get the error... however, if you can't reproduce, I'm happy to close this issue since I no longer need it anyway. The docs have been updated (thanks!), so hopefully I just have some weird unrelated problem in my setup.

**Comment by KyleAMathews** [comment]
Alex -- if you can push an example of your code to a GitHub repo, that'd
help a lot.

**Comment by KyleAMathews** [comment]
Definitely want people to be successful with this but without an example we
can reproduce it's hard to know what's going wrong. Even if it's a "weird
unrelated problem" that'd be good to know if nothing else to document this.

**Comment by rattrayalex** [comment]
Very kind of you!

Hah, sure – [this](https://github.com/lightscript/lightscript.org/blob/gatsby-bug/pages/docs/index.jsx#L122) is where I'm exporting it, and [this](https://github.com/lightscript/lightscript.org/blob/gatsby-bug/pages/docs/index.jsx#L151) is where I'm logging it. The code's a bit of a mess right now, plus I just threw both of those bits back in for this.

Oh, and did I mention that it's in an under-development compile-to-js language :wink: I'd show you the docs, but that's the code that generates them, and, well, it's not done yet! 

So chances are we can chalk it up to something being mangled in there. Chances are, a conflict between `export default` + `babel-plugin-add-module-exports` and trying to set `exports.data`. For example, when I try to do `import * from './docs'` in another file, `data` is nowhere to be found.

If I try removing `babel-plugin-add-module-exports`, React complains that it is receiving an object instead of a function (eg; the `exports` object with a `default` member, instead of just that `default` member).

**Comment by KyleAMathews** [comment]
Ooo... I thought I recognized your name — I saw you helping out over on Prettier. 

And haha we should have gone to code samples earlier — we're extracting the JS frontmatter at build *statically* using Babylon to parse the code. So it only works on JS code—see the code here: https://github.com/gatsbyjs/gatsby/blob/2d8e7869ef1672a04ca228a5791d7d46f7499ef8/lib/utils/build-page/load-frontmatter.js#L26

So if there's a way to get Babylon to parse Lightscript or an easy way to parse Lightscript in a similar manner we could get things going for you but otherwise this issue could be a "can't fix".

**Comment by rattrayalex** [comment]
Hah! That's hilarious. 

Feel pretty comfortable with "can't fix" on this then! Sorry I didn't mention the LightScript factor earlier, wouldn't have guessed you were using Babylon for static analysis! (neat trick, by the way). 

Thanks for your help! 😄

**Comment by KyleAMathews** [comment]
:-)

You can do something kinda similar by just exporting a function from each
component and then calling them but at that point, it'd probably be easier
to just have a global titles.yaml or whatever where you store info like
this.

**Comment by rattrayalex** [comment]
Yep exactly, it was a pretty easy feature to step around.

**Comment by mjesuele** [comment]
@KyleAMathews, I'm having the same problem: I'm setting a title with
```javascript
exports.data = { title: 'Foo' };
```
but when I read the page data in my template (where I render the page title) it's an empty object.

My _template.js file looks like this:

```javascript
import Helmet from 'react-helmet';
import React from 'react';
// eslint-disable-next-line import/no-unresolved, import/extensions
import { config } from 'config';
import get from 'lodash/fp/get';
import last from 'lodash/fp/last';
import pipe from 'lodash/fp/pipe';

const getPageDataFromRoutes = pipe(
  last,
  get(`page.data`),
);

export default ({ children, routes }) => {
  const data = getPageDataFromRoutes(routes);
  console.log(data);

  const pageTitle = data.title ?
    `${data.title} | ${config.siteTitle}` :
    config.siteTitle;

  const displayTitle = data.title &&
    <h1>{data.title}</h1>;

  return (
    <div>
      <Helmet title={pageTitle} />
      {displayTitle}
      {children}
    </div>
  );
};
```

Frontmatter works just fine on HTML files.

Appreciate any help you can give me! Gatsby rocks :)

**Comment by mjesuele** [comment]
Actually, I just realized that this is only happening for my 404.js; I'm able to make it work with other React component pages. Since the 404 is a special case, that makes sense to me.

I care less now, knowing that, but perhaps still something to look into?

**Comment by mjesuele** [comment]
I figured it out. Template literals have a different internal representation than regular string literals do, which results in `prop.value.value` being undefined at https://github.com/gatsbyjs/gatsby/blob/master/lib/utils/build-page/load-frontmatter.js#L55.

Using a single- or double-quoted string fixes the problem.

I think the docs should be updated to reflect this, or the frontmatter code should be reworked to play nice with template strings, at the very least when there's no interpolation. I'm sure I'm not the only one who's started to set eslint's `quotes` rule to `backtick`.

**Comment by KyleAMathews** [comment]
@mjesuele good call! I'm using template literal strings actually as well for all the Gatsby 1.0 stuff :-D

Would you like to submit a PR to add support for them? https://github.com/gatsbyjs/gatsby/blob/master/lib/utils/build-page/load-frontmatter.js#L52

**Comment by mjesuele** [comment]
@KyleAMathews: Okay! Here's my attempt: https://github.com/gatsbyjs/gatsby/pull/656

Let me know how it looks :)
