### ISSUE TITLE
[v2] Enable SplitChunksPlugin during development

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#6453]
This is just as fast and reduces the amount of JS that needs loaded in development + Tobias said it speeds up HMR.

**Comment by TylerBarnes** [comment]
There's a PR open for this at #18949. 
You can test it by running `npm install gatsby@splitchunksdev`.

**Comment by sidharthachatterjee** [comment]
Closing this as a duplicate of https://github.com/gatsbyjs/gatsby/issues/8342
