### ISSUE TITLE
React does not recognize the `styleName` prop

### ISSUE THREAD

**Issue by tsmith123** [gatsbyjs/gatsby#6457]
I'm getting this error with Gatsby v2.

> Warning: React does not recognize the `styleName` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `stylename` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

I have `gatsby-plugin-sass` installed and referenced in my `gatsby-node` file and `node-sass` installed too. In my Home container, my `scss` file is called `Home.module.scss` and I include it using `import from './Home.module.scss` but my styles are not being applied.

My `Layout` component imports a global `scss` file and I use `className` to refer to styles in that file and everything works fine. Why can't I use `styleName` - am I missing something simple?

**Comment by KyleAMathews** [comment]
Perhaps review part three of the tutorial where it talks about using CSS modules? https://www.gatsbyjs.org/tutorial/part-two/

**Comment by jquense** [comment]
What is styleName? Is that a prop that some library adds automatically to components? For css modules generally you need to import the style sheet as if it was like a json file. The import value is an object of class Ames you then explicitly add the class you want to the react element via the class name prop

**Comment by pieh** [comment]
I think to use `styleName` You need https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-react-css-modules and not just gatsby-plugin-sass.

**Comment by IgorBlyznuk** [comment]
> I think to use `styleName` You need https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-react-css-modules...

Hi
Sorry for disturbing you
I have an issue with gatsby-plugin-react-css-modules which i don't understand. Can you help me? After build i have classes like <div class="_2a3sm"></div>  - hash only. 
In develop mode everything fine: <div class="foo_2a3sm"></div>

gatsby-config.js

  plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-layout',
    'gatsby-transformer-json',
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: './src/data/'
      }
    },
    {
      resolve: 'gatsby-plugin-google-fonts',
      options: {
        fonts: [
          'Open sans:300,400,600'
        ]
      }
    }, {
      resolve: 'gatsby-plugin-react-css-modules',
      options: {
        exclude: 'node_modules',
        removeImport: false,
        webpackHotModuleReloading: true
      }
    }
