### ISSUE TITLE
ESLint in Gatsby v2

### ISSUE THREAD

**Issue by tsmith123** [gatsbyjs/gatsby#6460]
I'm getting lots of linting warnings during `gatsby develop` which I don't want to see as I have my own linting styles. How do I remove this from the output?

**Comment by KyleAMathews** [comment]
I believe @kkemple already added support for overriding those by adding your own .eslintrc file to your site. Add that file and gatsby core will stop linting.

**Comment by tsmith123** [comment]
I use `stylelint` and keep my config in `package.json`. Any recommendations for this?
