### ISSUE TITLE
gatsby-remark-images - absolute path to image

### ISSUE THREAD

**Issue by mkozhukharenko** [gatsbyjs/gatsby#6464]
## Intro

It took me several hours to figure out why plugin does not work for me.
And I found that it's because of the image path is absolute. 

```
![image](/img/suv-on-wild-mountain-road.jpg)
```
if I move it to the the folder (place along with md file) - it works: 
```
![image](./suv-on-wild-mountain-road.jpg)
```
But it's not a case since I'm using a CMS which stores them in public folder and adds absolute path.

## Summary

It would be great if plugin could work with absolute paths

**Comment by pieh** [comment]
Hey, it would be great to use https://www.npmjs.com/package/is-relative in https://github.com/gatsbyjs/gatsby/blob/49a63571fd1f369e1b2ea4bc0f1eb508d4465810/packages/gatsby-remark-images/src/index.js#L42-L55 and use current behaviour if path is relative and if it's not then join path with project directory. 

Would You like to create PR for that?

**Comment by Jinksi** [comment]
I solved this problem by using [gatsby-remark-relative-images](https://github.com/danielmahon/gatsby-remark-relative-images). Although v2 support is not ready.

[Working example](https://deploy-preview-21--netlify-cms-react-starter.netlify.com/posts/hello-world/)

I agree it would be great to have this supported.
