### ISSUE TITLE
Disambiguate when StaticQueries is required for Gatsby v2

### ISSUE THREAD

**Issue by hswolff** [gatsbyjs/gatsby#6468]
## Summary

Recently I upgraded my blog to Gatsby v2 using [this upgrade guide](https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/). After reading about `StaticQueries` I assumed that it was required in all locations where `pageQueries` used to be required and ported everything to use that. 

However `pageQueries` seems to still be required for page components which I found a little confusing.

This issue is suggesting making it clear that `pageQueries` is still required for pages.

Alternatively I do suggest deprecating `pageQueries` entirely and use `StaticQueries` (or a HoC) to get rid of the semi-weird non-js standard concept of `pageQueries`.

**Comment by CanRau** [comment]
I, too, find the docs/guides could be a little more clear..

As for your last suggestions, I'm not exactly sure about the specs or reasons but as far as I know you can't throw variables at `StaticQuery` so they're really "static" and without context..
Don't know why, but that seems to be the reason for sticking to `pageQueries` for pages as they need context for you to fetch the corresponding data ;)

**Comment by KyleAMathews** [comment]
BTW, I did verify earlier that there's a bug currently with using StaticQuery inside page components FYI.

**Comment by horacioh** [comment]
Happy to be part of the contributors of Gatsby!! 
thanks @jlengstorf for helping me in the pair programming session! :+1:
