### ISSUE TITLE
Edits to JSON only reflected first time on dev server

### ISSUE THREAD

**Issue by mortenson** [gatsbyjs/gatsby#6472]
## Description

I'm seeing inconsistent caching and reloading when editing JSON source files and viewing my Gatsby site using `gatsby develop`. The first edit gets picked up and my page reloads properly, but subsequent edits do not work.

### Steps to reproduce

Install and run the project I'm working on:

```
git clone git@github.com:drupal-tome/tome-gatsby.git
cd tome-gatsby/gatsby
npm install
gatsby develop
```

Then change the "title" field in `tome-gatsby/drupal/node.832d966e-7478-47ca-8038-6f1b01864dc3.json`, I usually add an exclamation mark. The first edit should work.

Now edit the file again - in the console you can see that `gatsby-source-filesystem` saw a change, but the changes are not reflected on the page.

### Expected result

I would expect that all edits to JSON files cause nodes to properly be regenerated.

### Actual result

Making more than one edit does not work.

### Environment

```
  System:
    OS: macOS High Sierra 10.13.2
    CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 9.8.0 - /usr/local/bin/node
    Yarn: 1.0.2 - /usr/local/bin/yarn
    npm: 6.2.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 50.0.2
    Safari: 11.0.2
  npmPackages:
    gatsby: next => 2.0.0-beta.38
    gatsby-image: next => 2.0.0-beta.6
    gatsby-plugin-react-helmet: next => 3.0.0-beta.3
    gatsby-plugin-sharp: next => 2.0.0-beta.5
    gatsby-source-filesystem: next => 2.0.1-beta.5
    gatsby-transformer-json: next => 2.1.1-beta.2
    gatsby-transformer-sharp: next => 2.1.1-beta.3
  npmGlobalPackages:
    gatsby-cli: 2.0.0-beta.6
```

### File contents (if changed)

`gatsby-node.js`: https://github.com/drupal-tome/tome-gatsby/blob/master/gatsby/gatsby-node.js

**Comment by KyleAMathews** [comment]
This should have been fixed in https://github.com/gatsbyjs/gatsby/pull/6488 along with a couple of other data hot reloading issues. Lemme know if there's still an issue with beta.40!

**Comment by mortenson** [comment]
@KyleAMathews Working pretty good, thanks!

**Comment by KyleAMathews** [comment]
Great! Cool demo on Twitter btw :-D

**Comment by linoxyn** [comment]
I came across this thread and it duplicates the same problem I am having. The edits I make to a JSON file are not being brought into the project with `gatsby develop`. Filesystem sees the change but I get errors when I query graphql using the new/edited field name. The new or edited field names do not show as a choice with `Ctrl+spacebar`. I've tried clearing .cache. I am running Gatsby v2 beta, all Gatsby beta dependencies are updated to current @next.

    OS: Windows 10
    CPU: x64 i7-8550U@1.80GHz
    Memory: 15.85 GB
    Node: 8.11.3 LTS
    npm:  6.2.0
    Yarn: 1.7.0
    VScode: 1.25.1
    npmPackages:
    gatsby: next => 2.0.0-beta.61
    gatsby-image: next => 2.0.0-beta.7
    gatsby-plugin-react-helmet: next => 3.0.0-beta.4
    gatsby-plugin-sharp: next => 2.0.0-beta.7
    gatsby-plugin-styled-components: next => 3.0.0-beta.3
    gatsby-plugin-typography: next => 2.2.0-beta.3
    gatsby-source-filesystem: next => 2.0.1-beta.10
    gatsby-transformer-json: next => 2.1.1-beta.4
    gatsby-transformer-sharp: next => 2.1.1-beta.6


For now, is there a way to manually get my JSON edits to work in the project? 
Thanks :-)

**Comment by mortenson** [comment]
@KyleAMathews I'm seeing this issue with `exports.createPages` as well - the first page generated while `gatsby develop` is running works, but subsequent pages do not work.
