### ISSUE TITLE
[gatsby-plugin-sitemap] – Inform search engines of updated sitemap

### ISSUE THREAD

**Issue by lewisvrobinson** [gatsbyjs/gatsby#6474]
## Summary

Add an option to [gatsby-plugin-sitemap](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sitemap) to [inform](https://www.sitemaps.org/protocol.html#informing) Google, Bing and Ask.com search engines of the sitemap update.

### Basic example

Add inform option to default options
```
{
    resolve: `gatsby-plugin-sitemap`,
    options: {
      ...
      inform: true,
      ...
    }
  }
```

If `inform` is set, ping the search engines with the location of the new/updated sitemap. Possibly something like:
```
const exec = require('child_process').exec

const sitemapLocation = `${siteMetadata.siteUrl + output}`
const pingUrls = [
  `www.google.com/ping?sitemap=${sitemapLocation}`,
  `www.bing.com/ping?sitemap=${sitemapLocation}`,
  `submissions.ask.com/ping?sitemap=${sitemapLocation}`
]

const logPing = (error, stdout, stderr) => {
  if (error) {
    console.log(error)
    return
  }
  if (stderr) {
    console.log(stderr)
    return
  }
  console.log(stdout)
}

const pingSearchEngines = () => pingUrls.forEach(url => exec(`ping -c 1 ${url}`, logPing))
```

### Motivation

*Why are we doing this?*
To easily update search engines when new pages are created, rather than relying on a re-crawl or manually uploading the new sitemap.

*What use cases does it support?*
This would particularly helpful in situations where you are regularly adding content to your site.

*What is the expected outcome?*
When the sitemap is built we ping the search engines to inform them of the change to the sitemap

If this is something that you think should be added or explored I'd be more than happy to give it a crack 🙂

**Comment by pieh** [comment]
This is interesting - few quick thoughts:
 - building and deploying are 2 separate things, so actual ping should happen when production build is deployed, not when it's built I think?
 - how to manage to not spam search engines with pings - we wouldn't want to ping when you do test builds locally or when you build branches other than `master` (f.e. preview deploys for PRs etc)

**Comment by lewisvrobinson** [comment]
You have a good point re building vs deployment and the separation of the two.

I suppose I was thinking about a use-case where you'd use a service like Netlify to build and deploy automatically (ie when new content is published). 

You could then use environment variables to set `inform` how you like to avoid spamming the search engines. For example using the `BRANCH` variable available on Netlify:
```javascript
{
  ...
  inform: (process.env.BRANCH === 'master' && process.env.NODE_ENV === 'production') ? true : false
  ...
}
```
Maybe this solution is a *little* too specific to a certain workflow and would better as it's own plugin?

**Comment by m-allanson** [comment]
Sounds like this would be really useful in some situations, but maybe not as a default option in gatsby-plugin-sitemap. Creating a separate plugin sounds like a great approach 👍 If you create a plugin don't forget to add it to the [Gatsby Plugin Library](https://www.gatsbyjs.org/plugins/) afterwards :)

**Comment by m-allanson** [comment]
Closing as this will be a new plugin outside the Gatsby repo.

**Comment by tunnckoCore** [comment]
@m-allanson the name of the plugin?

**Comment by lewisvrobinson** [comment]
@tunnckoCore I didn't end up creating a plugin to do this as it worked out better to inform the search engines post-deploy (so the sitemap was guaranteed to be available). But you could easily grab the snippet above and integrate it into your build if that works for you 🙂

**Comment by tunnckoCore** [comment]
Ookay, thanks! :)
