### ISSUE TITLE
[V2] IE 11 Needs Template Literals on Babel Config

### ISSUE THREAD

**Issue by shelldandy** [gatsbyjs/gatsby#6478]
IE11 Builds are breaking since the back ticks are not being recognized ``` I think the polyfill is needed

https://www.npmjs.com/package/babel-plugin-transform-es2015-template-literals

**Comment by m-allanson** [comment]
Could you give a bit more info? Creating a demo repo would be very useful.

**Comment by marcobiedermann** [comment]
@shelldandy 
Yes, IE11 does not support template literals. See https://kangax.github.io/compat-table/es6/#test-template_literals.
When using ES6 code you have to use babel or any other transpiler to make you code backwards compatible. This is the default case with gatsby.
As @m-allanson mentioned, could you please share your setup / configuration.
I have the feeling this is some issue on your end and not related to gatsby.
As soon as you could provide some further information, I would be glad to help you out

**Comment by m-allanson** [comment]
> I would be glad to help you out

:tada: great stuff, thanks for offering to help out @marcobiedermann 🙏 

We'd like to encourage folks to ask questions if they're not clear on something - often it turns out that there's something in Gatsby or the docs that can be improved - so I don't think it's necessary to 👎 anyone for asking a polite question.

That said, @shelldandy you'll often get a faster reply if you fill out the template when creating your issue.

**Comment by shelldandy** [comment]
Thanks guys!

No special configuration attached, really starting from scratch.

I figured I need to use the `onCreateBabelConfig` however I can't find any good examples on how to achieve that and the v2 docs have that section basically empty.

https://next.gatsbyjs.org/docs/node-apis/#onCreateBabelConfig

So yeah as you said most likely I need to hook into that to add the plugin I need.

So maybe the issue can become a request documentation issue?

Or at least an example on how to achieve such thing.

**Comment by shelldandy** [comment]
> Could you give a bit more info? Creating a demo repo would be very useful.

Really just a hello world app that also does something like:

```js
const name = `Github`

console.log(`Hello ${name}`)
```

**Comment by shelldandy** [comment]
:wave:

**Comment by ARXChrono** [comment]
Did you end up figuring it out?
