### ISSUE TITLE
[next.gatsbyjs.org] Extra space below the first line of the new slogan

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#6485]
<img width="401" alt="cursor_and_gatsbyjs" src="https://user-images.githubusercontent.com/71047/42777511-2af639fc-88ef-11e8-9b97-e555a7f9e9b1.png">

**Comment by joshbuchea** [comment]
PR submitted: #6626

**Comment by joshbuchea** [comment]
Ok was lazy and just closed the old PR and opened a new one: #6628 ¯\_(ツ)_/¯

**Comment by pieh** [comment]
This was fixed by #6628
