### ISSUE TITLE
Reduce size of files checked into the repo

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#6486]
## Description

We have several files checked into the repo that are pretty large ([this one is 8.6MB](https://github.com/gatsbyjs/gatsby/blob/master/docs/blog/images/15009741473_9ced5e3209_o.jpg)). They all appear to be blog images, so I don't think there's any reason to keep them at that size.

The repo is currently _huge_ right now (I'm watching @jjprevite download it and we're at 200MB+ / over 5 minutes to clone), so finding and shrinking all these images should make it much faster to clone the repo for development.

### Steps to reproduce

Do a fresh clone of the repo after clearing caches.

### Expected result

The repo should clone quickly for development.

### Actual result

Repo takes a _long_ time to clone.

**Comment by KyleAMathews** [comment]
Makes sense! No need to keep images larger than e.g. 3x their intended size (we build 3x/2x/1x resolutions).

You might need to rewrite history though for older versions.

We could also start encouraging people to do shallower checkouts to speed up the initial checkout given Gatsby is 3+ years old now.

**Comment by KyleAMathews** [comment]
Not sure what that's there for. @ThatOtherPerson — do you remember why you added it?

**Comment by roachnt** [comment]
I can help with this. Where do you recommend I start?

**Comment by jlengstorf** [comment]
@roachnt I'd run the `find` command posted above, then resize any images there to be their @2x web size (1,240px wide). That ought to eliminate the image bloat.

There are also two pretty large MP4s (~10MB each) in this post: https://www.gatsbyjs.org/blog/2018-04-11-trying-out-gatsby-at-work-and-co/ — should those be moved to the Gatsby YouTube channel? @KyleAMathews any thoughts on that?

Otherwise, we need to hear back from @ThatOtherPerson about the screenshot plugin to see if we can drop that tarball.

@roachnt if you want to take a crack at the images, that would be an amazing help!

**Comment by jlengstorf** [comment]
@roachnt a better command that ignores built output and `node_modules`:

```
find . -type f -size +500k  -not -path "./.git/*" -not -path "*/node_modules/*" -not -path "*/.cache/*" -not -path "*/public/*" -print0 | xargs -0 ls -Shal
```

**Comment by roachnt** [comment]
I can optimize these images as well, just running them through ImageOptim before resizing takes ~20-30% off the size in total!

**Comment by KyleAMathews** [comment]
Nice! Just don't do lossy compressions please.

**Comment by roachnt** [comment]
#6507 here's a PR for the images!

**Comment by ThomasAnkcorn** [comment]
How about using Git LFS https://git-lfs.github.com/ for all the discussed items.

**Comment by m-allanson** [comment]
> How about using Git LFS https://git-lfs.github.com/ for all the discussed items.

Hmmmmm interesting! That looks like it could be pretty useful, what happens if you try and interact with the repo _without_ installing `git-lfs` first?

I'd be concerned that requiring `git-lfs` could be too much of a barrier for new contributors - particularly if they're just wanting to submit blog posts or documentation changes. It'd make the process of checking out Gatsby different to 99% ( ⚠️ _made-up stats warning_ ⚠️ ) of other projects on GitHub.

**Comment by ThomasAnkcorn** [comment]
GIt for windows comes with git-lfs included. But on mac and linux you need to install it. I will test the behavior with other git clients and check back here with the result.

**Comment by roachnt** [comment]
#7841

**Comment by ThatOtherPerson** [comment]
@KyleAMathews sorry, I somehow missed this! That is Chrome. It's a special build that works on Lambda. It'd probably be possible to have it on S3 or something and download before deploy

**Comment by m-allanson** [comment]
@ThatOtherPerson would something like this make a good replacement for the checked copy of Chrome? https://github.com/alixaxel/chrome-aws-lambda
