### ISSUE TITLE
Dynamic routing to set initial redux store state?

### ISSUE THREAD

**Issue by melalj** [gatsbyjs/gatsby#6494]
## Summary
I have an app that handles its state using redux. I read many times the page ["Creating and Modifying Pages"](https://www.gatsbyjs.org/docs/creating-and-modifying-pages), but couldn't understand how I can extract url parameters from the path and change the initial state for the redux store.

I though to edit the `gatsby-node.js`, query the database to build all possible URLs but couldn't understand where to set the initial state for the store as defined on `gatsby-ssr` and `gatsby-browser`.

Any enlightenment would be super helpful 🙏 Thanks!

### File contents

`gatsby-config.js`: N/A
`package.json`: N/A
`gatsby-node.js`: N/A
`gatsby-browser.js`:
```js
import React from 'react';
import { Router } from 'react-router-dom';
import { Provider } from 'react-redux';

import store from './src/state/store';

export const replaceRouterComponent = ({ history }) => {
  const ConnectedRouterWrapper = ({ children }) => (
    <Provider store={store}>
      <Router history={history}>{children}</Router>
    </Provider>
  );
  return ConnectedRouterWrapper;
};

````

`gatsby-ssr.js`:
```js
import React from 'react';
import { Provider } from 'react-redux';
import { renderToString } from 'react-dom/server';

import store from './src/state/store';

export const replaceRenderer = ({ bodyComponent, replaceBodyHTMLString }) => {
  const ConnectedBody = () => (
    <Provider store={store}>
      {bodyComponent}
    </Provider>
  );
  replaceBodyHTMLString(renderToString(<ConnectedBody/>));
};
```

`./src/state/store`:
```js
import { applyMiddleware, createStore } from 'redux';
import thunk from 'redux-thunk';
import logger from 'redux-logger';

import rootReducer from './reducers';
import initialState from './initial';

export default createStore(
  rootReducer,
  initialState,
  applyMiddleware(thunk, logger),
);
```

**Comment by m-allanson** [comment]
What information do you want to add to the initial store?

**Comment by melalj** [comment]
The initial store have the selected panel and selected items (from the db).

Here's a simplistic representation of the routes and initialStore:
 - `/all-items` → `{ selectedPanel: 'ALL_ITEMS', selectedItemId: null }`
 - `/something-:itemId` → `{ selectedPanel: 'ITEM_PANEL', selectedItemId: :itemId, selectedRelatedId:  null }`
 - `/something-:itemId-:relatedId` → `{ selectedPanel: 'RELATED_ITEM_PANEL', selectedItem: :itemId,  selectedRelatedId: :relatedId }`

**Comment by mramognino** [comment]
Hi guys!! I have a similar issue, does anyone have any idea how to pass the initial state to redux using the url parameters?

**Comment by isachivka** [comment]
Hi! You can get path here:
```
export const replaceRenderer = ({ bodyComponent, replaceBodyHTMLString }) => {
  console.log(bodyComponent.props.url);
};
```
