### ISSUE TITLE
[v2] whole page re-renders on navigation

### ISSUE THREAD

**Issue by sokki** [gatsbyjs/gatsby#6496]
## Description

I'm not sure if this is already a known problem but I could not find a related issue.

### Steps to reproduce

`gatsby new my-default-project https://github.com/gatsbyjs/gatsby-starter-default#v2`
`cd  my-default-project && npm run develop`
open Browser and look into dev-tools

### Expected result

When navigating to a different page, only parts of the DOM should update.

### Actual result

Every DOM node gets recreated. Including the root element.
![2018-07-17 10 59 06](https://user-images.githubusercontent.com/665748/42807412-02c8f588-89b1-11e8-9919-17dbe4b20560.gif)

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 6.1.0 - ~/.nvm/versions/node/v8.9.4/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-beta.40 
    gatsby-plugin-react-helmet: next => 3.0.0-beta.3 
  npmGlobalPackages:
    gatsby-cli: 2.0.0-beta.6
```

**Comment by LeKoArts** [comment]
Here you go:
https://github.com/gatsbyjs/gatsby/issues/6127
