### ISSUE TITLE
JS run at build time vs client side

### ISSUE THREAD

**Issue by robed** [gatsbyjs/gatsby#6497]
I'm new to gatsbyjs and static site generators in general. I am building a blog using the gatsby-source-drupal plugin to pull in content from a Drupal backend.

I have tried using 2 different methods of truncating some text for each blog post. First I wrote a simple function using .substring and then I tried [react-text-truncate](https://www.npmjs.com/package/react-text-truncate). They both worked fine but after building the site I noticed that the static HTML differed between the 2 methods. The first method actually truncated the text at build time whereas the second method did not; all the text was still there in the HTML so therefore the JS must be running on the client to do the truncation.

My question is therefore how is it decided at which point the JS is run? At the point that the site is built (which modifies the HTML being written) or on the client side? I apologise if i have missed something fundamental whilst reading the docs!

Regards,
Rob

**Comment by Khaledgarbaya** [comment]
Hey @robed, Gatsby expose some hooks for you to use at different stages like at build time or in the browser.
I recommend checking these links:

- https://www.gatsbyjs.org/docs/node-apis/
- https://www.gatsbyjs.org/docs/browser-apis/
- https://www.gatsbyjs.org/docs/ssr-apis/

I hope this helps

**Comment by LekoArts** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
