### ISSUE TITLE
Question: Failure after importing OfficeUIFabric React

### ISSUE THREAD

**Issue by stevebeauge** [gatsbyjs/gatsby#6501]
## Summary

I'm trying to include some [OfficeUI React ](https://github.com/OfficeDev/office-ui-fabric-react)component in a gatsby site.

However, as soon as I import something from the library, the site stops to compile. When I try gatsby develop, I got errors `SyntaxError: export declarations may only appear at top level of a module` in the Firefox console. The page remains blanks.

If I try gatsby build, it even does compile.

## Relevant information

Repro steps:

1. Create a new gatsby site: 
       
        gatsby new simple
        cd simple
        yarn
        gatbsy develop

2. At this point, the site works as expected
3. Add the library

       yarn add office-ui-fabric-react --save
       gatsby develop

4. The site is still working
5. Edit the file `src/layouts/index.js` (for example) to import a component from the library

       import React from 'react'
       import PropTypes from 'prop-types'
       import Helmet from 'react-helmet'

       import Header from '../components/header'
       import './index.css'

       import { Button } from 'office-ui-fabric-react/lib/Button'

       const Layout = ({ children, data }) => (

6. The site stop to work. In the Firefox console, I get the error `SyntaxError: export declarations may only appear at top level of a module`. Especially, here is an extract of the bundled javascript:

       /***/ "./node_modules/office-ui-fabric-react/lib/Button.js":
       /***/ (function(module, exports) {

       	       export * from './components/Button/index';
              	//# sourceMappingURL=Button.js.map

       /***/ })

The issue seems to be due to the `export` which isn't transpiled.

Searches I've done leads to babel issues. I tried to play with `.babelrc` files without success.
I tried to play with gatbsy plugins named babel-something, but I didn't succeed.

I'd appreciate some help to understand and fix this issue.

### Environment (if relevant)

`gatsby info --clipboard` gives:
```

  System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^1.9.247 => 1.9.273
    gatsby-link: ^1.6.40 => 1.6.45
    gatsby-plugin-react-helmet: ^2.0.10 => 2.0.11

error Le chemin d'acc�s sp�cifi� est introuvable.



  Error: Le chemin d'acc�s sp�cifi� est introuvable.

  - envinfo.js:1 Function.e.exports.sync
    [global]/[envinfo]/dist/envinfo.js:1:7778

  - envinfo.js:1 Object.copySync
    [global]/[envinfo]/dist/envinfo.js:1:104976

  - envinfo.js:1 Object.t.writeSync.e [as writeSync]
    [global]/[envinfo]/dist/envinfo.js:1:123499

  - envinfo.js:1
    [global]/[envinfo]/dist/envinfo.js:1:124274

  - envinfo.js:1 Promise.all.then.e
    [global]/[envinfo]/dist/envinfo.js:1:124289

  - util.js:16 tryCatcher
    [global]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [global]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [global]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [global]/[bluebird]/js/release/promise.js:614:10

  - promise.js:693 Promise._settlePromises
    [global]/[bluebird]/js/release/promise.js:693:18

  - promise.js:638 Promise._fulfill
    [global]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [global]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [global]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [global]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [global]/[bluebird]/js/release/promise.js:614:10

  - promise.js:693 Promise._settlePromises
    [global]/[bluebird]/js/release/promise.js:693:18


error UNHANDLED REJECTION


  Error: Le chemin d'acc�s sp�cifi� est introuvable.

  - envinfo.js:1 Function.e.exports.sync
    [global]/[envinfo]/dist/envinfo.js:1:7778

  - envinfo.js:1 Object.copySync
    [global]/[envinfo]/dist/envinfo.js:1:104976

  - envinfo.js:1 Object.t.writeSync.e [as writeSync]
    [global]/[envinfo]/dist/envinfo.js:1:123499

  - envinfo.js:1
    [global]/[envinfo]/dist/envinfo.js:1:124274

  - envinfo.js:1 Promise.all.then.e
    [global]/[envinfo]/dist/envinfo.js:1:124289

  - util.js:16 tryCatcher
    [global]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [global]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [global]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [global]/[bluebird]/js/release/promise.js:614:10

  - promise.js:693 Promise._settlePromises
    [global]/[bluebird]/js/release/promise.js:693:18

  - promise.js:638 Promise._fulfill
    [global]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [global]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [global]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [global]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [global]/[bluebird]/js/release/promise.js:614:10

  - promise.js:693 Promise._settlePromises
    [global]/[bluebird]/js/release/promise.js:693:18
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by KyleAMathews** [comment]
It looks like they're shipping uncompiled ES6 code to NPM. Gatsby doesn't compile code in node_modules.

**Comment by stevebeauge** [comment]
Even though it's not a gatbsy issue, do you any advice how to fix that ? (I'm new in node dev)

**Comment by KyleAMathews** [comment]
Without looking at their code no. Perhaps file an issue there? Or is there issues already about using the components with webpack?

**Comment by stevebeauge** [comment]
Let me reformulate my query. I don't ask to look at their code, but ask if there is, within a gatsby site, a way to compile modules before bundling. As I said, I thought gatbsy plugins are here for that, but I didn't succeed

**Comment by LekoArts** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
