### ISSUE TITLE
Get Wordpress post revision

### ISSUE THREAD

**Issue by b0gd4n** [gatsbyjs/gatsby#6508]
I have a website using the WP endpoints to create pages for each post, which works fine.

However, I've encountered an issue where I get 404s when trying to access a post after a revision as the url has changed.
So, if a post is created under `somewebsite/blog/post-a` and after a revision it gets renamed to `post-b` therefore the url becoming `somewebsite/blog/post-b`, the first url will return a 404 page. WP creates 301 redirects automatically in the backend and, ideally, there should be a way of dynamically adding redirects to the Netlify `_redirects` file.

I noticed there is an endpoint that might be able to return what I need [WP API](https://developer.wordpress.org/rest-api/reference/post-revisions/) but I cannot seem to get to this within GraphQL.
When I access the endpoint in a browser (the endpoint looks something like `https://wpwebsite.com/wp-json/wp/v2/posts/742/revisions` I get: 
```{
"code": "rest_cannot_read",
    "message": "Sorry, you are not allowed to view revisions of this post.",
    "data": {
        "status": 401
    }
}

**Comment by lightstrike** [comment]
Hey @b0gd4n! Have you tried to [add authentication credentials](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-wordpress#how-to-use) (see `auth` section of config)?

**Comment by b0gd4n** [comment]
that still does not retrieve the revisions

**Comment by octalmage** [comment]
Looks like post requests are protected by the cookie auth mechanism, you can learn more about this here:

https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/#cookie-authentication

I was able to confirm this by running this JavaScript in my WordPress admin: 

```JavaScript
jQuery.ajax( {
    url: wpApiSettings.root + 'wp/v2/posts/69046/revisions',
    method: 'GEt',
    beforeSend: function ( xhr ) {
        xhr.setRequestHeader( 'X-WP-Nonce', wpApiSettings.nonce );
    },
} ).done( function ( response ) {
    console.log( response );
} );
```

And this returned the post revisions. So unfortunately the wordpress-source-plugin would need to be modified to be able to support revisions.
