### ISSUE TITLE
[gatsby-source-wordpress] Wordpress Media Sizes

### ISSUE THREAD

**Issue by donysukardi** [gatsbyjs/gatsby#6509]
## Description

I am using https://wordpress.org/plugins/manual-image-crop/ for finer controls on cropping for different image sizes/ratios that my application is using.

However, the `media_details.sizes` info is currently being stripped away by the plugin in favor of localFile.

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/normalize.js#L457

### Steps to reproduce

Create any post with image custom field and try to query it on GraphiQL

### Expected result

`$imagePath.media_details.sizes` should return the different sizes for the image files

Ideally, we should be able to transform the different sizes with `gatsby-transformer-sharp` as well.

### Actual result

`$imagePath.media_details.sizes` is set to null

### Environment

```
 System:
    OS: macOS High Sierra 10.13.5
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.4.1 - ~/.nvm/versions/node/v10.4.1/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.1.0 - ~/.nvm/versions/node/v10.4.1/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 60.0.1
    Safari: 11.1.1
  npmPackages:
    gatsby: next => 2.0.0-beta.42
    gatsby-image: next => 2.0.0-beta.6
    gatsby-plugin-glamor: next => 2.0.0-beta.2
    gatsby-plugin-react-helmet: next => 3.0.0-beta.3
    gatsby-plugin-sharp: next => 2.0.0-beta.5
    gatsby-plugin-typography: next => 2.2.0-beta.2
    gatsby-source-wordpress: next => 3.0.0-beta.7
    gatsby-transformer-sharp: next => 2.1.1-beta.4
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by pieh** [comment]
This is done to make to limit time spent on fetching images - because as You pointed, wordpress by default doesn't have ability to do manual cropping for thumbnails, so we could do the same thing with sharp image processing as you can with thumbnail sizes in wordpress.

I think it would be fine to add this as opt-in for use cases like Yours. Would You be interested in creating PR for it?

**Comment by billyjacoby** [comment]
I'm running in to this exact problem, and I can't figure out what exactly to change in this plugin in order to allow all of the sizes to be returned.

Can anyone point me in the right direction to enable the fetching of all thumbnail sizes please?

**Comment by sidharthachatterjee** [comment]
Published in `gatsby-source-wordpress@3.1.16` as `keepMediaSizes` courtesy of @billyjacoby

**Comment by karlromanowski** [comment]
With keepMediaSizes: true would it be possible to also stop downloading media altogether?
Our media gets uploaded to a CDN and I use the sizes to build an img setset, but the plugin still downloads all media locally (that I don't use) and and my public folder is over 1GB containing images that are never referenced. Removing '**/media' stops the downloads but also loses the media_details containing sizes.

**Comment by billyjacoby** [comment]
> With keepMediaSizes: true would it be possible to also stop downloading media altogether?
> Our media gets uploaded to a CDN and I use the sizes to build an img setset, but the plugin still downloads all media locally (that I don't use) and and my public folder is over 1GB containing images that are never referenced. Removing '**/media' stops the downloads but also loses the media_details containing sizes.

hmm this is an interesting idea, and something that definitely seems doable.

I would probably suggest adding a different variable to control this behavior, rather then using the existing keepMediaSizes variable to do it though.
