### ISSUE TITLE
Feature request - Trailing slash should be optional

### ISSUE THREAD

**Issue by scottyeck** [gatsbyjs/gatsby#651]
Hey y'all - thanks for all your hard work with _gatsby_. 👏  👏  👏  We at [Fabric](https://github.com/fabrictech) are super excited to be using it. 😎 

**Context**

Currently, trailing slashes are required in page routes. For context, this is described in the `README` as follows:

> Make sure you also including the **trailing slash** in your URLs:
> - Bad: `http://localhost:8000/foo`
> - Good: `http://localhost:8000/foo/`

**Problem**

If a user wants cosmetic URLs - and thus support for the `http://localhost:8000/foo` URL above - they currently have to configure this via a 301 on the server. This should cover a large majority of use cases for sure, but in some cases, a server may not be able to distinguish between `/foo` and `/foo/`, thus resulting in an endless redirect loop. 😢 

**Solution**

The trailing slash could be optional.

* Supply `optionalTrailingSlash` setting in `config.toml`. Defaults to falsy.
* If truthy, post-process over results from `createRoutes`, to replace instances of `/foo/` with `/foo`.

**Current working state**

I've put this together in a PR - #650. I understand that this change is very very quick and dirty and I'm sure that a more active contributor might well have a better solution here. If so, please let me know how I can improve it! 🌈

**Comment by KyleAMathews** [comment]
Closed by #657
