### ISSUE TITLE
deleting removed files and/or directories after gatsby build

### ISSUE THREAD

**Issue by avocadoras** [gatsbyjs/gatsby#6516]
I tried looking for an issue with similar concern but seems like there isn't one yet.

 I would like to delete from `public/` directory all my previously removed files from my `posts/` which contain markdown files for blog post content. I assumed these files would not be included during a build if they did not exist but they are still in my `public/`.

 I am fairly new to Gatsby so do not know how to solve this problem here. Also, not sure if this is related to my gatsby-plugin set up... any help would be greatly appreciated here.

**Comment by avocadoras** [comment]
specifically all my files and directories in `src/posts`

**Comment by KyleAMathews** [comment]
Hmm we don't copy markdown files to public. Off that's happening.

**Comment by avocadoras** [comment]
Here a picture of my result after `gatsby build`: 
![screenshot 2018-07-18 14 45 39](https://user-images.githubusercontent.com/36335687/42906779-47b3784c-8a99-11e8-861e-e7616f2dd8ce.png)
![screenshot 2018-07-18 14 45 31](https://user-images.githubusercontent.com/36335687/42906790-4e94cddc-8a99-11e8-9cfa-c3c00d552d7b.png)

**Comment by KyleAMathews** [comment]
Could you send a screenshot of a fresh build w/o having deleted things?

**Comment by avocadoras** [comment]
I cannot revert back to that version previously to deletion because I included other changes to my project as well. Even though it's not exactly what you asked, I will send a screenshot of a fresh build I ran a second ago. 
![screenshot 2018-07-18 15 39 40](https://user-images.githubusercontent.com/36335687/42909307-f9070c10-8aa0-11e8-9e38-ea9eb4fa0105.png)

`hi-folks/`, and `my-second-post` are directories I removed in my `src/` directory, and they still appear after my build, you can see the see the date in which they were created and compared them to other dates on other files that were recently edited, to give you an idea of my problem. Please let me know if there is another way to get around what you asked, maybe I could create the folders and files again and run another build?

**Comment by KyleAMathews** [comment]
That looks normal. Gatsby is a static site generator so makes folders with HTML in then for serving your site.

**Comment by avocadoras** [comment]
Hmm, I see. Is there a way I could clean those directories from my `public/`? I don't want to serve unused folders or files (that do not exist). I am thinking something along the lines of https://www.npmjs.com/package/webpack-clean. Hope I am making sense.

**Comment by KyleAMathews** [comment]
We delete the HTML files — if you want to delete empty directories as well, that's something you could do in a `postBuild` step.

**Comment by m-allanson** [comment]
Closing as I think this is resolved? Please re-open if not!
