### ISSUE TITLE
Non-destructive Builds

### ISSUE THREAD

**Issue by daneden** [gatsbyjs/gatsby#6521]
## Summary

I’ve loved using Gatsby for my personal site ([link](https://daneden.me), [repo](https://github.com/daneden/daneden.me)), but one thing that irks me is that the `gatsby build` process deletes existing paths before new builds are complete.

I'd love to have a non-destructive option (or default flag!) to prevent deletion of an existing build until after a new build has successfully completed.

### Motivation

Because the `build` process first deletes existing builds:

- If the build takes a long time, deployment on a server could mean downtime for your site for the duration of the build. (For my site and with my current server setup, build takes about 30s, so visitors to my site during that time see nothing but a blank page)
- If the build fails for some reason after the delete step, then it could take _even longer_ to recover the site, resulting in longer downtimes. Unless I manually create a backup step, recovering the old site is impossible, save for `git checkout {safe-revision} && gatsby build`-ing as quickly as I can

**Comment by KyleAMathews** [comment]
We could change the logic to keep track of what HTML files there are at the start of the build and then delete the ones that aren't written over. That probably would be marginally faster.

Our assumption for the current logic is that you build in a different directory than where you serve the site and then copy over files upon successful completion of a build. Most people use some sort of CI setup which does this. Could you change your build process to do this?

**Comment by daneden** [comment]
@KyleAMathews that's fair! I'm definitely being lazy with my setup (still rocking an Apache VPN 😅). I can add a postbuild step as a workaround, but I still think it may be a valuable addition to the build process as an option.

**Comment by daneden** [comment]
So I moved to Netlify which has been a complete breeze, thanks for the forcing function! Closing this issue to clear up your queue, but still consider it a good idea 😄
