### ISSUE TITLE
[v2] script tag in html.js causes build to get stuck

### ISSUE THREAD

**Issue by Jaikant** [gatsbyjs/gatsby#6523]
I have been upgrading my website to gatsby V2. In V1, I had overridden the default-html.js with a custom html.js. The only additional thing in my custom html.js was a `script` tag for embedly. 
I noticed that `gatsby build` and `gatsby develop` get stuck after the `bootstrap` phase.

`gatsby develop` gets stuck on the below messages:
```
success onPostBootstrap — 0.002 s

info bootstrap finished - 7.256 s

```

The script tag, with which I saw the issue is as below:

```
          <script>
            (function(w, d){
             var id='embedly-platform', n = 'script';
             if (!d.getElementById(id)){
               w.embedly = w.embedly || function() {(w.embedly.q = w.embedly.q || []).push(arguments);};
               var e = d.createElement(n); e.id = id; e.async=1;
               e.src = ('https:' === document.location.protocol ? 'https' : 'http') + '://cdn.embedly.com/widgets/platform.js';
               var s = d.getElementsByTagName(n)[0];
               s.parentNode.insertBefore(e, s);
             }
            })(window, document);
          </script>
```

If the `script` tag is removed from the html.js the build proceeds. 

This script tag isn't super important for me as I don't really use it any longer on my site.  
I am filing this issue, just in case someone else faces it as I spent a couple of hours on this.

**Comment by pieh** [comment]
This looks like duplicate of https://github.com/gatsbyjs/gatsby/issues/6498

**Comment by Jaikant** [comment]
@pieh yes it does seem like that. So let me close this one out!

**Comment by KyleAMathews** [comment]
FYI, the problem here is you need to use dangerouslySetInnerHTML for script tag contents
