### ISSUE TITLE
onCreateWebpackConfig({ loaders }): loaders.url() is broken

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#6525]
I am using [gatsby-plugin-cesium](https://github.com/kripod/gatsby-plugin-cesium) to load glTF files through url-loader with the following syntax: https://github.com/kripod/gatsby-plugin-cesium/blob/59c94ed2fa5a5612554c8d3d1b8e2aac75906625/gatsby-node.js#L50-L57

Since the release of gatsby@2.0.0-beta.41, an URL similar to the one below gets generated when importing a glTF asset:

```
import MyAssetURL from ‘./my-asset.glb’;

console.log(MyAssetURL); // http://localhost:8000/../static/my-asset-[hash].glb
```

In gatsby@2.0.0-beta.40, the aforementioned bug was not present:

```
import MyAssetURL from ‘./my-asset.glb’;

console.log(MyAssetURL); // http://localhost:8000/static/my-asset-[hash].glb
```

**Comment by m-allanson** [comment]
Thanks @kripod, this looks like it's caused by #6346

**Comment by KyleAMathews** [comment]
Reverted #6346. Upgrade to beta.51 to get new version w/o breakage.
