### ISSUE TITLE
Not loading font file

### ISSUE THREAD

**Issue by xiaohuij** [gatsbyjs/gatsby#6526]
## Summary
we have below code in scss file:
```
@font-face {
  font-family: 'rui-icon';
  src: url("//<url-to-cdn>/static/icons/icon.eot");
  src: url("//<url-to-cdn>/static/icons/icon.eot?#iefix") format("embedded-opentype"), url("//<url-to-cdn>/static/icons/icon.woff") format("woff"), url("//<url-to-cdn>/static/icons/icon.ttf") format("truetype"), url("//<url-to-cdn>/static/icons/icon.svg#cool-icon") format("svg");
  font-weight: normal;
  font-style: normal; 
}
```
1. run `yarn serve`
it got request and icon on page
2. run `yarn develop`
no request and no icon on page

Could someone please answer this? and how to make it works on develop mode?

**Comment by m-allanson** [comment]
Hmm it's difficult to say without more info.. Can you post an example site?

**Comment by LekoArts** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
