### ISSUE TITLE
Allow custom file extensions

### ISSUE THREAD

**Issue by rattrayalex** [gatsbyjs/gatsby#653]
Howdy!

I don't necessarily think it would be a good idea to actually accept this, but I thought I should raise it, especially since I will probably move the LightScript Docs off of Gatsby due to this (I may use a fork instead, and I've been very impressed with Gatsby, fwiw). 

It would be nice to allow custom file extensions. In my case, LightScript has the extensions `.lsc` and `.lsx`. 

I was able to support this in my case by modifying the `node_modules/gatsby/dist` dir locally (not exactly sustainable/production-friendly) by adding `lsc` and `lsx` wherever `cjsx` appeared in the codebase, and by adding the following to my `gatsby-node.js`: 

```js
exports.modifyWebpackConfig = function(config, stage) {
  const jsBabelQuery = config._loaders.js.config.query;
  config.loader('lsc', {
    test: /\.lsc|\.lsx/,
    exclude: /(node_modules)/,
    loader: 'babel',
    query: jsBabelQuery,
  });

  const origResolver = config.resolve;
  config.resolve = function lightscriptResolve() {
    const result = origResolver.call(this, arguments);
    result.resolve.extensions.push('.lsc', '.lsx');
    return result;
  }

  return config;
}
```

The locations where I needed to modify the package: 
- https://github.com/gatsbyjs/gatsby/blob/3792215f24b3b87d3fa5ecb5f37e57bad9ebf4c2/lib/isomorphic/create-routes.js#L115
- https://github.com/gatsbyjs/gatsby/blob/b4d585a2c0035dc3c8896c42e2daaac1b520be5a/lib/utils/webpack.config.js#L155 (technically, this wasn't necessary because of the resolver I added to my config). 
- https://github.com/gatsbyjs/gatsby/blob/2d8e7869ef1672a04ca228a5791d7d46f7499ef8/lib/utils/load-context.js#L5
- https://github.com/gatsbyjs/gatsby/blob/2d8e7869ef1672a04ca228a5791d7d46f7499ef8/lib/utils/page-file-types.js#L1

Again, I don't predict it'll be worth your while to support this. I can just fork this for now, or move off Gatsby, since I'm not using most of its power anyway. 

Cheers!
Alex

**Comment by rattrayalex** [comment]
I created the fork, you can see it here: https://github.com/lightscript/gatsby/tree/lightscript

I recommend closing this issue 😄

**Comment by KyleAMathews** [comment]
Yeah, I'd love to be able to support JS alternatives like LightScript but Gatsby 0.x being a monolith means we'd have to ship support for LightScript to everyone...

1.0 will make it really easy to create a gatsby-plugin-lightscript for drop-in support! Would love to help you get that going once plugin support lands (very soon).

**Comment by rattrayalex** [comment]
Wow awesome! Thanks @KyleAMatthews ! Would love your input on the language one of these days if you're interested btw!

**Comment by KyleAMathews** [comment]
That'd be fun! You're in SF right? Send me a DM and we could meetup
sometime.
