### ISSUE TITLE
Can you publish a new version of Gatsby link for v1 ?

### ISSUE THREAD

**Issue by abumalick** [gatsbyjs/gatsby#6533]
## Summary
I saw that push and replace methods were added to v1 branch in gatsby-link.
Can you publish that feature to npm so we can use them on v1 ?

Right now, the version on npm don't have these features.

https://github.com/gatsbyjs/gatsby/tree/v1/packages/gatsby-link

Brief explanation of the feature.

### Motivation

use replace with gatsby-link v1

**Comment by pieh** [comment]
Oh snap, sorry about that - will publish new v1 packages soon
