### ISSUE TITLE
Pick key open source projects using Gatsby and do PRs upgrading their sites

### ISSUE THREAD

**Issue by pieh** [gatsbyjs/gatsby#6537]
- [x] reactjs.org (https://github.com/reactjs/reactjs.org) https://github.com/reactjs/reactjs.org/pull/1104
- [ ] www.howtographql.com (https://github.com/howtographql/howtographql)
- [ ] https://storybook.js.org/ (https://github.com/storybooks/storybook)
- [ ] https://hackclub.com/ (https://github.com/hackclub/site)
- [ ] https://mozilladevelopers.github.io/playground/ (https://github.com/MozillaDevelopers/playground)

**Comment by alexandernanberg** [comment]
I've created a [PR](https://github.com/reactjs/reactjs.org/pull/1104) in the reactjs.org repo. Most stuff seems to be working but I've hit a few problems. Such as CSS have different order in dev and build, but I think #6760 should solve that once that gets merged. 

Also this [redirect](https://github.com/alexandernanberg/reactjs.org/blob/gatsby-v2/gatsby/createPages.js#L149-L154) has stopped working, and I can't figure out why. But I should maybe create a separate issue for that?
