### ISSUE TITLE
[perilbot] validate updates to the site showcase

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#6538]
## Summary

Use [Gatsby's Peril setup](https://github.com/gatsbyjs/peril-gatsbyjs) to automatically check any pull request that modifies [the list of showcase sites](https://github.com/gatsbyjs/gatsby/blob/master/docs/sites.yml).

It should verify that added sites contain the correct fields - url, categories etc.

### Basic example

Example message notifiying about missing fields:

> Gadzooks! It looks like you forgot to add a link to your new site. You should update your pull request to include a `url` field that links to your site. 

Stretch goals:

- check categories and suggest related categories, highlight possible typos or alert to categories where your site will be the only site in the category?
- check that urls are valid

### Motivation

Missing fields mean the added site may not get published to the showcase.

**Comment by jlengstorf** [comment]
> Gadzooks!

😂 

I love this idea. I'm going to set up a project proposal to track ideas like these, and we'll see if we can get it prioritized.

**Comment by m-allanson** [comment]
Additional things Peril could do:

- automatically add a `date_added` field
- automatically add a `gatsby_version` field

(ref: https://github.com/gatsbyjs/gatsby/pull/6930)

**Comment by jlengstorf** [comment]
@pieh Is this the one you wanted to tackle?
