### ISSUE TITLE
How to add material ui to Gatsby

### ISSUE THREAD

**Issue by palaniichukdmytro** [gatsbyjs/gatsby#654]
I try to set up the Gatsby kit and deep in react with this site generator and material ui framework. What did I mess? I've got the error: 

```
     Cannot read property 'prepareStyles' of undefined
        at RaisedButton.render 
```
I installed material ui with npm 
`npm install material-ui`

After add the to components to my post index.js and MyAwesomeReactComponent.js
```
    import React from 'react';
    import ReactDOM from 'react-dom';
    import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';
    import MyAwesomeReactComponent from './MyAwesomeReactComponent';
    
    const MaterialUiWrapper = () => (
      <MuiThemeProvider>
        <MyAwesomeReactComponent />
      </MuiThemeProvider>
    );
    
    export default MaterialUiWrapper

    exports.data = {
      title: "Material UI ",
      date: "2017-12-09T12:40:32.169Z",
    }
```
MyAwesomeReactComponent.js
```

    import React from 'react';
    import RaisedButton from 'material-ui/RaisedButton';
    
    const MyAwesomeReactComponent = () => (
      <RaisedButton label="Default" />
    );
    
    export default MyAwesomeReactComponent;
```

And add the React-Tap-Event-Plugin to listen for touch events to the root html.js
```
import injectTapEventPlugin from 'react-tap-event-plugin'
injectTapEventPlugin();
```

**Comment by g8tguy** [comment]
You should enable CSS modules on  `material-ui` CSS in `node_modules` directory, by default CSS modules are only enabled on files with `.module` in their path if I remember it right, so you should override the WebPack config, 
use 
- https://github.com/g8tguy/g8tguy.com/blob/master/gatsby-node.jsx
- https://github.com/g8tguy/g8tguy.com/blob/d2a8347bdf9a672c869faf165be24e6dc3fb08b3/gatsby-node.jsx
as an example, it's not exactly what you need, but enough to grasp the idea
And yes, I got `material-ui` working with `gatsby'  before a couple of months, so it's totally possible.

**Comment by palaniichukdmytro** [comment]
I've just re run my npm build, and all correct now. without any changes.

**Comment by EvanCarroll** [comment]
@ghost all those links are dead, got any updated how do you "enable CSS modules"

**Comment by KyleAMathews** [comment]
something.module.css
