### ISSUE TITLE
Upgrade `serve` dependency to version 7

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#6546]
## Description

There's a [security vulnerability in `serve`](https://snyk.io/vuln/npm:serve:20180531) that GitHub just started flagging. The fix is to upgrade `serve` to `serve@^7.0.0`. Currently we're still on version 6.

https://github.com/gatsbyjs/gatsby/blob/d8aaa2f346ea30fac760b0fb4359bb251779525a/packages/gatsby/package.json#L117

## Steps to Solve

- [ ] Run `yarn install serve@latest` in the `gatsby` package
- [ ] Ensure `gatsby serve` continues to work as expected
- [ ] Spread the word that everyone should upgrade to remove the vulnerability

We should apply this upgrade to both v1 and v2, assuming there are no breaking changes for v1.

**Comment by m-allanson** [comment]
The latest version is 9.2.0, so it's probably worth updating all the way up to that.

**Comment by m-allanson** [comment]
This was handled in the above mentioned PRs, thanks folks!
