### ISSUE TITLE
Dynamically Load/Fetch data

### ISSUE THREAD

**Issue by ugiacoman** [gatsbyjs/gatsby#655]
Hi, I was wondering if there was a way to dynamically load data, is there somewhere in the react lifecycle where we should be fetching data from? I was implementing with `axios`, which works fine in development mode, because... well react haha. However, when I build my static pages, it won't fetch the data.

EDIT: JK it's because of the AMP build...hmm. Closing this, will post solution when I figure it out

**Comment by KyleAMathews** [comment]
This is a job for "componentDidMount"!

**Comment by KyleAMathews** [comment]
Oh weird. Hope you figure out the AMP stuff.

**Comment by ugiacoman** [comment]
For AMP, since you can't include just any script, if you want to send a get request to a URL, say for analytics, tracking, etc.. you can use `amp-pixel`. Cheers!

**Comment by jobasiimwe** [comment]
Hello @ugiacoman, Did you find a fix for this?

**Comment by ugiacoman** [comment]
Like I mentioned, for my use case, AMP was stripping out certain calls. It's been a really long time since I worked with gatsby, I really don't remember much else. If you are having problems, don't build with AMP.

**Comment by jobasiimwe** [comment]
Thanks @ugiacoman. Elsewhere, I have seen that gatsby is not meant to handle loading data in the components. All data must be preloaded through another node module (like a plugin) and then supplied to the components.

**Comment by guilhermeutzig** [comment]
Guys, I'm having this issue too and I'm not working with AMP. I'm just trying to do a fetch, and on the develop version work and brings the content, but on builded version, it doesn't even make the request (saw it on Network tab, on Inspect).  I'm really struggling with this, can anyone help in any way? This is my code:

`
import React, { Component } from "react";
import Helmet from "react-helmet";

import PageHeader from "../components/PageHeader";
import Button from "../components/Button";
import ButtonLink from "../components/ButtonLink";
import Section from "../components/Section";
import ButtonGroup from "../components/ButtonGroup";
import Breadcrumbs from "../components/Breadcrumbs";
import ContentBlock from "../components/ContentBlock";
import Table from "../components/Table";
import Well from "../components/Well";
import { reject } from "rsvp";

export default class Template extends Component {

  constructor(props){
    super(props)
  }

  state = {
    results: []
  }

  componentDidMount() {
    this.getResults()
  }

  getResults = async () => {
    fetch('https://randomuser.me/api/')
    .then(response => response.json())
    .then(json => {
      this.setState({ results: json.results })
    })
  }

  render() {
    const post = this.props.data.markdownRemark;
    const { results } = this.state;

    return (
        <div className="l-container">
            <Helmet>
              <meta name="description" content="Descricao" />
            </Helmet>

            {post.frontmatter.group &&
                <Breadcrumbs group={post.frontmatter.group} />
            }

            <PageHeader
                kicker={post.frontmatter.kicker}
                title={post.frontmatter.title}
                description={post.frontmatter.description}
                status={post.frontmatter.status}
            />

            <div className="c-text-passage" dangerouslySetInnerHTML={{ __html: post.html }} />

            {post.frontmatter.questions && (
              <div className="questions">
                <h2>FAQ</h2>
                {post.frontmatter.questions.map((item, i) => {
                  return (
                    <div className="question" key={i}>
                      <h4>{item.question}</h4>
                      <p>{item.answer}</p>
                    </div>
                  )
                })}
              </div>
            )}

            {results != [] && results.map((item, i) => {
              return <li>{item.gender}</li>
            })}

        </div>
    );
  }
}

export const componentDetailQuery = graphql'
  query PageQuery($slug: String!) {
    markdownRemark(fields: { slug: { eq: $slug } }) {
      html
      frontmatter {
          path
          tags
          kicker
          title
          description
          status
          group
          questions {
            question
            answer
          }
          usage {
            description
          }
          use {
            title
            description
          }
          altUse {
            title
            description
          }
      }
    }
  }
';
`

**Comment by jobasiimwe** [comment]
Hey @guilhermeutzig you can not do this in gatsby. If you want to load data, you do it in the gatsby-node.js file. Gatsby runs that script and loads the data...you then create sourceNodes which gatsby will avail for you to query with graphql queries in the different components.

It is the magic of the platform but the documentation is not clear. None of your components can load data.

**Comment by guilhermeutzig** [comment]
@jobasiimwe Ok than, thank you very much for the fast answer!!

**Comment by justintemps** [comment]
Wait, so you can't load data except through a source node?

**Comment by justintemps** [comment]
@jobasiimwe so if you want to load data from a rest-api, for example, you need to create a source plugin for it which you would then query with graphql?

**Comment by jobasiimwe** [comment]
Good example https://stackoverflow.com/questions/49299309/gatsbyjs-getting-data-from-restful-api

**Comment by justintemps** [comment]
@jobasiimwe That's really helpful, thanks so much. So if I've understood correctly, in order to bring in data from REST APIs, you need to map it to nodes in Gatsby which components can then "map to props" via GraphQL queries. Do I also understand correctly that this happens at build time, not at run time, and that you'd have to rebuild your app to get new data? Sorry if this sounds like a stupid question.

**Comment by jobasiimwe** [comment]
You understood me correctly. I haven't used _Hybrid Pages._
You can continue your search about that.
