### ISSUE TITLE
[v2] Make v2 default/blog starters score 100 on Lighthouse out of the box

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#6559]
Lighthouse is a fantastic site audit tool and we should make official Gatsby starters pass with flying colors out of the box

https://developers.google.com/web/tools/lighthouse/

Other than the hello-world starter which is intentionally kept completely minimal.

- [ ] Default https://github.com/gatsbyjs/gatsby-starter-default/
- [ ] Blog https://github.com/gatsbyjs/gatsby-starter-blog

**Comment by roachnt** [comment]
Including the PWA section? So we should add those plugins to the starters?

**Comment by jumpalottahigh** [comment]
I'd love to give this a try if no one has started yet.

**Comment by KyleAMathews** [comment]
@roachnt yup!

@jumpalottahigh have at it! Though maybe @roachnt wants to take one as well :-)

**Comment by jumpalottahigh** [comment]
@KyleAMathews Sweet. I'll start on `gatsby-starter-blog` then in case @roachnt wants to pick up the default starter, if not, I'll move to it too after.

**Comment by roachnt** [comment]
Yeah I can take starter-default, thanks for saving me one!

**Comment by jumpalottahigh** [comment]
Sure thing. Got up to here for today, will have to sleep on the last 3 points of performance which seem to require removing unused css styles, yet the purgecss was unable to tree shake anything.

![image](https://user-images.githubusercontent.com/4155121/43040143-d57df064-8d44-11e8-9208-fa758ebe0996.png)

**Comment by roachnt** [comment]
Here's what I've come up with thus far. I've had this "passive listeners" thing come up a lot. Any thoughts on how to take care of that?

<img width="713" alt="screen shot 2018-07-21 at 8 15 49 pm" src="https://user-images.githubusercontent.com/22849869/43041048-00ceb496-8d23-11e8-9643-0ae9b4f7d7f7.png">
<img width="708" alt="screen shot 2018-07-21 at 8 15 40 pm" src="https://user-images.githubusercontent.com/22849869/43041049-010be528-8d23-11e8-8357-b1ac5e1e5d73.png">
<img width="715" alt="screen shot 2018-07-21 at 8 13 31 pm" src="https://user-images.githubusercontent.com/22849869/43041050-014b307a-8d23-11e8-8bee-44888c8e90df.png">

**Comment by roachnt** [comment]
Looking good so far! Last thing is that css preload. Is that something that would need to be handled in gatsby itself?

<img width="717" alt="screen shot 2018-07-21 at 8 40 36 pm" src="https://user-images.githubusercontent.com/22849869/43041184-78b2f6cc-8d26-11e8-8afb-a505aab0f1d4.png">

**Comment by KyleAMathews** [comment]
What's the issue with css preload?

**Comment by roachnt** [comment]
<img width="713" alt="screen shot 2018-07-21 at 8 15 49 pm" src="https://user-images.githubusercontent.com/22849869/43041909-379ec042-8d3c-11e8-8a4c-65badf2e9082.png">

**Comment by KyleAMathews** [comment]
Haha I think lighthouse is confused by our prefetching. It's algorithm there must just be "if css is loaded within x seconds, suggest preloading". Which is fine normally except we start prefetching very quickly after the app starts.

Why though does the second page have its own CSS bundle? It doesn't require any CSS right?

**Comment by roachnt** [comment]
Oddly enough, it's the `layout.css` file's contents...is that just from the Layout component being imported on each page?

**Comment by jumpalottahigh** [comment]
Current state of the gatsby-starter-blog progress:

![image](https://user-images.githubusercontent.com/4155121/43043992-44759290-8da6-11e8-8fc5-cbc6d29559c1.png)

Even with completely removed `typography.js` for testing sake, still can't reach quite 100 score in performance. Out of clues in the Lighthouse report.

Reading here doesn't seem to help either: https://developers.google.com/web/tools/lighthouse/v3/scoring

They link to an excel sheet, which also doesn't point to anything we can improve, it seems we already cover all the values mentioned in the excel sheet.

![image](https://user-images.githubusercontent.com/4155121/43044097-75a1baae-8da8-11e8-8552-70d46c88bf00.png)

Could it be something Gatsby internal that needs to be improved for that last 99 -> 100 points or as mentioned above is it a Lighthouse scoring algorithm issue?

**Comment by jumpalottahigh** [comment]
This PR has been up and quiet for a while - https://github.com/gatsbyjs/gatsby-starter-blog/pull/114
Any feedback would be appreciated if anyone gets a chance (which might also potentially close this issue.

**Comment by KyleAMathews** [comment]
We did it, thanks everyone!

**Comment by jumpalottahigh** [comment]
Hi, @omrllm. The `gastsby-starter-default` doesn't reach 100 score in the PWA category, because the service worker is opt in. You can enable it and that's going to get you to 100, but unless you are aware of how service workers function, I'd suggest you are probably better off leaving it like that, as it might introduce caching issues and serving stale content in some cases. That being said it could be powerful if you really have the use case for it.

As for the `gatsby-starter-blog` it seems like we need to add some fallback content between `noscript` tags to alert users with JavaScript disabled that the app requires JavaScript to run correctly. Thanks for spotting this, I'll open a PR with a suggested fix for that.

**Comment by omrllm** [comment]
> It seems like the starters have moved here: https://github.com/gatsbyjs/gatsby/tree/master/starters and they do get 100 PWA score, check them out.

I still get the same results.. how do you get that 100 PWA score?

What I did:
- Went to https://github.com/gatsbyjs/gatsby/tree/master/starters
- Cloned the https://github.com/gatsbyjs/gatsby repo
- Deleted everything in the folder 
- Installed the gatsby-cli with `npm install gatsby-cli` inside the blog and default folders
- `gatsby build` 
- `gatsby serve`

Same results..

**Brave (a browser based on Chromium):**
Default gives me a PWA score of 58 and a Best Practices score of 93
Blog gives me a Performance score of 98, PWA score of 58 and a Best Practices score of 93

**On Chromium:**
Blog gives me a Performance score of 98, PWA score of 88 and a Best Practices score of 93
Default gives me a PWA score of 58 and a Best Practices score of 93

All the other values are equals to 100

I've got the results in incognito mode to get non distorted values

P.S. even the demo websites do not give me a 100 score.. the one which get the closest to a 100 score is https://gatsby-starter-blog-demo.netlify.com/ -> (performance = 99 & pwa = 96, everything else = 100) **on Chromium**

**Comment by jumpalottahigh** [comment]
I like testing on Netlify in an incognito Chrome tab for (hopefully) most trustworthy results. Following the same steps as you, cloning the monorepo, going to `starters/blog` and installing the dependencies with yarn, then building a production version and deploying it to Netlify, does indeed give me 100 scores across the board except for best practices.

![image](https://user-images.githubusercontent.com/4155121/51087426-b6eda080-175b-11e9-9a6b-fb721a27356d.png)

Run the tests yourself here: https://wonderful-mirzakhani-873806.netlify.com

I'm wondering if the discrepancies are not because you are testing a locally served site on localhost?

The demo site, on the other hand, does seem to be a bit behind than what's in the repository.

**Comment by miloofcroton** [comment]
> ![image](https://user-images.githubusercontent.com/4155121/51087426-b6eda080-175b-11e9-9a6b-fb721a27356d.png)

I have the exact same score. What is up with Netlify + Gatsby and HTTP/2?

**Comment by miloofcroton** [comment]
> > > ![image](https://user-images.githubusercontent.com/4155121/51087426-b6eda080-175b-11e9-9a6b-fb721a27356d.png)
> > 
> > 
> > I have the exact same score. What is up with Netlify + Gatsby and HTTP/2?
> 
> @miloofcroton because most probably you have
> 
> * [ ]  Clear Storage unchecked (just above `Run Audits` button).

No, it's not that.

![screenshot from 2019-01-21 21-19-07](https://user-images.githubusercontent.com/11794494/51513920-387ba900-1dc2-11e9-8c6e-d11929001ad3.png)
