### ISSUE TITLE
Update tutorial part 8 for v2

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#6571]
@KyleAMathews can help with details on what changes are needed to part 8

P.S. The current agreement is to stop making updates to v1 tutorial and focus on v2.

**Comment by shannonbux** [comment]
@KyleAMathews Do there need to be split differences between v1 and v2 versions of tutorials?

**Comment by amberleyromo** [comment]
@KyleAMathews checking status on this.

Part 8 is up on v2 site, not on v1 site at the moment. I understand we'll only be moving forward with v2. First comment on this issue is that you can help with with details on what changes are needed to part 8 -- Can you elaborate?

**Comment by KyleAMathews** [comment]
I wrote part of it a while ago https://next.gatsbyjs.org/tutorial/part-eight/

The idea is basically to take the site they've been building to completion. Lighthouse being the tool to help guide them. So it teaches them about Lighthouse and how the tool works and how to interpret the scores and then takes them through the necessary steps to finish out work w/ react-helmet, gatsby-plugin-manifest, and gatsby-plugin-offline.

So it mainly needs the final bits walking through fixing the lighthouse audit issues.

**Comment by amberleyromo** [comment]
Closed in #6983
