### ISSUE TITLE
Parsing files with shorthand Fragment syntax fail

### ISSUE THREAD

**Issue by alexluong** [gatsbyjs/gatsby#6573]
Debugging why a page component with StaticQuery doesn't work, we found out that shorthand Fragment (<></>) isn't parsed correctly.

It seems like we need to add another plugin to our babel parser array

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/babel-parse-to-ast.js

@dennari @jquense @KyleAMathews

**Comment by m-allanson** [comment]
@alexluong could you create a demo repo that shows this error? It could just be a v2 starter with a StaticQuery and a shorthand fragment added.

**Comment by alexluong** [comment]
@m-allanson Here you go:

https://github.com/alexluong/gatsby-issue-6573

All I did was:
- Clone gatsby default starter v2
- In `components/layout.js`, wrap the `StaticQuery` in `<>...</>`

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
