### ISSUE TITLE
different gatsby-config files during production

### ISSUE THREAD

**Issue by thebetterjort** [gatsbyjs/gatsby#6578]
How would I go about using a gatsby-config js for testing and another for production?

**Comment by m-allanson** [comment]
One way (probably not the best way) would be to do something like:

```js
let conf

if (process.env.NODE_ENV === `production`) {
  conf = {
    // gatsby config
  }
}

if (process.env.NODE_ENV === `test`) {
  conf = {
    // different gatsby config
  }
}

module.exports = conf
```

Check out [the docs on Environment Variables](https://www.gatsbyjs.org/docs/environment-variables/) for a more fine-grained approach to this sort of thing.

**Comment by LekoArts** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
