### ISSUE TITLE
Gatsby plus Redux 

### ISSUE THREAD

**Issue by saturnite** [gatsbyjs/gatsby#658]
@KyleAMathews how do i use Gatsby with Redux?

**Comment by KyleAMathews** [comment]
Gatsby is just React & Webpack w/ a static build. So for the most part, my answer is do things as you normally would.

One issue is setting up the special `<Provider>` component (http://redux.js.org/docs/basics/UsageWithReact.html#passing-the-store). To fix that, someone just needs to take up this (easy) PR idea and finish it: https://github.com/gatsbyjs/gatsby/pull/595#issuecomment-267657259

**Comment by KyleAMathews** [comment]
New browser API makes adding Redux easy. See the example code at https://github.com/gatsbyjs/gatsby/releases/tag/v0.12.34
