### ISSUE TITLE
Add guess.js to gatsbyjs.org

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#6591]
https://github.com/guess-js/guess is a key part of the narrative for v2 so we need to make sure it's running well on gatsbyjs.org

/cc @mgechev and @addyosmani

**Comment by KyleAMathews** [comment]
https://github.com/gatsbyjs/gatsby/issues/9572

**Comment by m-allanson** [comment]
We still want to do this.

**Comment by lannonbr** [comment]
Closing this as it has been implemented in #12351
