### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by jbeard4** [gatsbyjs/gatsby#6594]
## Description

I am getting an error `ECONNREFUSED 127.0.0.1:80`:

```
$ node `which gatsby` build --verbose
verbose 0.771 set gatsby_log_level: "verbose"
verbose 0.774 set gatsby_executing_command: "build"
verbose 0.775 loading local command from: /Users/jbeard4/workspace/scion-scxml-platform/projects/sciblog/node_modules/gatsby/dist/commands/build.js
verbose 4.747 running command: build
success delete html and css files from previous builds — 0.145 s
success open and validate gatsby-config — 0.008 s
success copy gatsby files — 0.024 s
success onPreBootstrap — 2.142 s
success source and transform nodes — 1.035 s
success building schema — 0.607 s
success createLayouts — 0.008 s
success createPages — 0.981 s
success createPagesStatefully — 0.014 s
success onPreExtractQueries — 0.002 s
success update schema — 0.168 s
success extract queries from components — 0.069 s
success run graphql queries — 3.338 s
success write out page data — 0.014 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.007 s

info bootstrap finished - 13.624 s

success Building CSS — 15.479 s
success Building production JavaScript bundles — 44.842 s
error UNHANDLED EXCEPTION


  Error: connect ECONNREFUSED 127.0.0.1:80
```

### Steps to reproduce

Run `$ node `which gatsby` build --verbose`

### Expected result

Build should finish successfully.

### Actual result

Build finished with error.

### Environment

  System:
    OS: macOS Sierra 10.12
    CPU: x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.4.0 - ~/.nvm/versions/v8.4.0/bin/node
    npm: 6.1.0 - ~/.nvm/versions/v8.4.0/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 59.0.2
    Safari: 10.0
  npmPackages:
    gatsby: ^1.8.12 => 1.9.273 
    gatsby-link: ^1.6.8 => 1.6.45 
    gatsby-plugin-feed: ^1.3.25 => 1.3.25 
    gatsby-plugin-google-analytics: ^1.0.31 => 1.0.31 
    gatsby-plugin-manifest: ^1.0.4 => 1.0.27 
    gatsby-plugin-offline: ^1.0.4 => 1.0.18 
    gatsby-plugin-preact: ^1.0.3 => 1.0.17 
    gatsby-plugin-react-helmet: ^1.0.3 => 1.0.8 
    gatsby-plugin-sharp: ^1.6.2 => 1.6.48 
    gatsby-remark-copy-linked-files: ^1.5.2 => 1.5.37 
    gatsby-remark-images: ^1.5.4 => 1.5.67 
    gatsby-remark-prismjs: ^1.2.1 => 1.2.24 
    gatsby-remark-responsive-iframe: ^1.4.3 => 1.4.20 
    gatsby-remark-smartypants: ^1.4.3 => 1.4.12 
    gatsby-source-filesystem: ^1.4.3 => 1.5.39 
    gatsby-transformer-remark: ^1.7.1 => 1.7.44 
    gatsby-transformer-sharp: ^1.6.1 => 1.6.27 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

### File contents (if changed)

`package.json`: N/A 

```
{
  "name": "gatsby-starter-blog-no-styles",
  "description": "Starter Gatsby Blog No Styles",
  "version": "1.0.0",
  "author": "Noah Glusenkamp <noah.glusenkamp@gmail.com>",
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby-starter-blog/issues"
  },
  "dependencies": {
    "bootstrap": "^4.1.1",
    "disqus-react": "^1.0.5",
    "gatsby": "^1.8.12",
    "gatsby-link": "^1.6.8",
    "gatsby-plugin-feed": "^1.3.25",
    "gatsby-plugin-google-analytics": "^1.0.31",
    "gatsby-plugin-manifest": "^1.0.4",
    "gatsby-plugin-offline": "^1.0.4",
    "gatsby-plugin-preact": "^1.0.3",
    "gatsby-plugin-react-helmet": "^1.0.3",
    "gatsby-plugin-sharp": "^1.6.2",
    "gatsby-remark-copy-linked-files": "^1.5.2",
    "gatsby-remark-images": "^1.5.4",
    "gatsby-remark-prismjs": "^1.2.1",
    "gatsby-remark-responsive-iframe": "^1.4.3",
    "gatsby-remark-smartypants": "^1.4.3",
    "gatsby-source-filesystem": "^1.4.3",
    "gatsby-transformer-remark": "^1.7.1",
    "gatsby-transformer-sharp": "^1.6.1",
    "jquery": "^3.3.1",
    "lodash": "^4.15.0",
    "popper.js": "^1.14.3"
  },
  "devDependencies": {
    "eslint": "^5.0.1",
    "eslint-plugin-react": "^7.10.0",
    "gh-pages": "^0.12.0",
    "prettier": "^1.6.1"
  },
  "homepage": "https://github.com/noahg/gatsby-starter-blog-no-styles#readme",
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "main": "n/a",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/noahg/gatsby-starter-blog-no-styles.git"
  },
  "scripts": {
    "dev": "gatsby develop",
    "lint": "./node_modules/.bin/eslint --ext .js,.jsx --ignore-pattern public .",
    "test": "echo \"Error: no test specified\" && exit 1",
    "format": "prettier --trailing-comma es5 --no-semi --single-quote --write 'src/**/*.js'",
    "develop": "gatsby develop",
    "build": "gatsby build",
    "deploy": "gatsby build --prefix-paths && gh-pages -d public",
    "fix-semi": "eslint --quiet --ignore-pattern node_modules --ignore-pattern public --parser babel-eslint --no-eslintrc --rule '{\"semi\": [2, \"never\"], \"no-extra-semi\": [2]}' --fix gatsby-node.js",
    "serve": "gatsby serve"
  }
}
```

`gatsby-node.js`: N/A 

```
exports.modifyWebpackConfig = ({ config, stage }) => {
  config.merge({
    externals: {
      'module': 'module'
    }
  })
  return config;
};
```

Thank you for your help with this.

**Comment by jbeard4** [comment]
I found this was happening because I was making an HTTP request to fetch a static resource in the constructor of a component, which was getting instantiated during the build.

**Comment by jacquescorbytuech** [comment]
@jbeard4 any chance you remember what you had to do to fix this? I am encountering this error when trying to use that gatsby-source-drupal module to populate a Gatsby page.

**Comment by yaimsc** [comment]
@jacquescorbytuech @jbeard4 do you know what did you fix to get it working? i am trying to build my site with Github actions and encountering the same error when its trying to build
