### ISSUE TITLE
[v2][RFC] Deprecate page queries completely and replace with StaticQuery?

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#6596]
Several people have suggested this and it's started feeling better and better over time.

It'd definitely better to have one pattern for queries rather than two. And the reaction to `<StaticQuery>` seems positive.

We'd have to add support for `<StaticQueries>` getting variables passed to them when they're on pages. Which felt weird as that's "magical" but... it's no less magical than the existing page queries. Less since it has a component tied to it.

Oh hmmm... just had a thought — we could create a `<PageQuery>` component that's identical to `<StaticQuery>` except it takes variables 🤔 

Thoughts?

**Comment by LeKoArts** [comment]
Would it be possible to put the query in a variable (like with the queries on pages right now)? Because otherwise my IDE isn’t recognizing it.

**Comment by KyleAMathews** [comment]
Not yet but we'd like to support that as well. Which IDE? Most IDEs go off the `graphql` function I thought.

**Comment by LeKoArts** [comment]
Oh, seems like the responsible plugin had a little hiccup. The ´staticQuery` "way" now also works :)
Then I'm happy with that (and the variable support).

If someone is interested: That's Webstorm + `JS GraphQL` plugin

![image](https://user-images.githubusercontent.com/16143594/43024914-1584db8a-8c70-11e8-96f1-4231ecc5574f.png)
![image](https://user-images.githubusercontent.com/16143594/43024932-245b8014-8c70-11e8-9812-a18bc2cb55dd.png)

**Comment by nakedible** [comment]
FWIW, I personally would find it much more intuitive if there were just a single query component, and that the entire pageQuery magic would be removed.

As I am used to Apollo, I would absolutely love it if the query component was similar. I will show this with a complete example to clarify my thoughts.

Old style:

```javascript
export default ({data}) => {
    return (
        <div>
            <div dangerouslySetInnerHTML={{ __html: data.markdownRemark.html }} />
        </div>
    );
}

export const pageQuery = graphql`
query PageQuery($fileAbsolutePath: String!) {
  markdownRemark(fileAbsolutePath: { eq: $fileAbsolutePath }) {
    html
    frontmatter {
      path
      title
    }
  }
}
`;
```

Suggested style:

```javascript
const query = gql`
query PageQuery($fileAbsolutePath: String!) {
  markdownRemark(fileAbsolutePath: { eq: $fileAbsolutePath }) {
    html
    frontmatter {
      path
      title
    }
  }
}
`;

export default ({pageContext}) => (
    <Query query={query} variables={pageContext.context}>
        {({ loading, error, data }) => {
            return (
                <div>
                    <div dangerouslySetInnerHTML={{ __html: data.markdownRemark.html }} />
                </div>
            );
        }}
    </Query>
);
```

Obviously code could be restructured with the query being at the bottom, if desired. It is a little more boilerplate on each page that uses a query - but it would remove all the magic and allow for much more options on how to query.
