### ISSUE TITLE
Files aren't downloaded when using gatsby-source-drupal with Node v6

### ISSUE THREAD

**Issue by robed** [gatsbyjs/gatsby#6603]
## Description

gatsby-source-drupal doesn't create local files when using Node v6.

gatsby-source-drupal/src/gatsby-node.js, line 145:
```
          // Resolve w/ baseUrl if node.uri isn't absolute.
          const url = new URL(node.url, baseUrl)
```

URLs can't be created using new URL() using Node v6 so 'TypeError: URL is not a constructor' exception is thrown.

**Comment by KyleAMathews** [comment]
Thanks for the detailed bug report! Want to work on a PR that fixes this?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
