### ISSUE TITLE
[Question]Refetch data with gatsby from wordpress source plugin

### ISSUE THREAD

**Issue by Kizbo** [gatsbyjs/gatsby#6604]
Hello guys, i found this discord on gatsbyjs site and i have a little problem, i want to deploy my wordpress content on gatsby, but keeping in mind that im adding posts and pages in wordpress as the time goes, is there a solution for refetching data in gatsby?

i'm using gatsby-source-wordpress, but when i add new post in wordpress, gatsby not following

Is there any way to refetch data when wordpress api updates? Except for rebuild.

**Comment by KyleAMathews** [comment]
The best way to handle this is to add a WP plugin that sends a webhook to your CI for building the site to trigger a new build every time there's a content change. I'm not sure which plugins are best unfortunately. Good luck!
