### ISSUE TITLE
Enable custom shouldUpdateScroll function in gatsby-browser file

### ISSUE THREAD

**Issue by Rusta** [gatsbyjs/gatsby#661]
I was hoping to extend the existing 'gatsby-browser' module to allow for the shouldUpdateScroll functionality in the router to be overridden on a case-by-case basis (due to a semi-obscure requirement that I have on a current project)

Below is my attempt at this, which seems to work:

https://github.com/Rusta/gatsby/commit/1c44f0eb5fdba3182cf7e7800534c25f6c76fb94

However the test suite no longer passes - and I'm not sure how to resolve this. I'm also not sure exactly where I should add any new tests for this feature (if needed/wanted)

Any help would be most appreciated

**Comment by KyleAMathews** [comment]
Oh cool! Just did something similar recently for 1.0.

Just call the API `shouldUpdateScroll` — "custom" is unnecessary since any API override is custom :-)

I don't know why that `cli` test would fail. Perhaps make a PR and see if the tests pass on Travis?

**Comment by Rusta** [comment]
Will give it a go.

RE the naming, I prefixed with "custom" so as not to clash with the existing shouldUpdateScroll function in that file. I could rename that existing function in order to have the API name the snappier one of the two - what do you think is best?

**Comment by KyleAMathews** [comment]
Ah gotcha. Yeah — just rename the function there.
