### ISSUE TITLE
Gatsby Commands (CLI) doc

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#6616]
In workshop, people didn't know they could type gatsby --help or gatsby develop --help (and other similar commands) in the CLI interface. 

It'd be great to have a reference doc that tells them they can do this AND lists all the commands out anyway so they can bookmark it, refer back to it, memorize it, etc.

**Comment by m-allanson** [comment]
There's a doc here, but it's not very findable. Could be used as reference for writing a docs page for gatsbyjs.org: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/README.md

**Comment by shannonbux** [comment]
oh cool, @m-allanson, didn't know that existed! Great starting point. I
wonder how much would be helpful to include, b/c there are new commands I
learned about when I ran
`gatsby develop --help`
vs
`gatsby --help`
vs
`gatsby build --help`

etc.

I am envisioning a very referencey kind of page that is not necessarily for
reading from top to bottom, more a good thing to scan or print out. Or for
someone like me, to make flashcards out of lol

**Comment by shannonbux** [comment]
Closing and replacing with #8103
