### ISSUE TITLE
Docs about Gatsby inner workings

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#6621]
From interviews:

* How does graphql work with redux?
* How does redux work inside gatsby? When one person spotted redux functions in plugins, he'd have to google them to try and figure out why they were there.
* How is Gatsby so fast?
* How does node config work with graphql and output into react?
* How does the createNode function work?
* What optimizations does Gatsby make for me?

Note: some of this information may already be in the docs. If it is, some people might not be finding it and we can consider how to make it more discoverable.

Would be nice to have layers of complexity to explain how Gatsby works.
- Layer 1: visual diagram and 1 paragraph explanation
- Layer 2: reference documents or process documents that go into great details

@kkemple I think you'd be interested in this stuff!

Here's an example of a diagram that helped a lot at a workshop:
<img width="801" alt="screen shot 2018-07-20 at 12 58 51 pm" src="https://user-images.githubusercontent.com/32467162/43020269-b1a7bf2c-8c1c-11e8-8468-de0c09412be6.png">

**Comment by Moocar** [comment]
Great! I've been creating a document that describes the internals of Gatsby that will answer some of these questions. So far it's more focused on how the API/Plugin system works, how nodes are stored in redux, and how the GraphQL schema works. So this will fit in nicely.

**Comment by m-allanson** [comment]
Also related: @sw-yx also added this doc, covering Gatsby's lifecycle API's: https://next.gatsbyjs.org/docs/gatsby-lifecycle-apis/

**Comment by KyleAMathews** [comment]
@Moocar has been rolling through this.

**Comment by fk** [comment]
^ https://next.gatsbyjs.org/docs/behind-the-scenes/
