### ISSUE TITLE
[perilbot] validate yaml for different yaml files + required fields

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#6634]
E.g. the site showcase yaml file.

Travis does this but it'd be nicer to put up a comment with the YAML error printed out so it's easier for people to fix. Many people never look at Travis.

**Comment by KyleAMathews** [comment]
@calcsam just had a great idea too that Peril could auto-merge site show case PRs. It'd validate that it's a Gatsby site, make sure it isn't a porn site, and then merge it in.

**Comment by jlengstorf** [comment]
@KyleAMathews @calcsam I can definitely look into this. I have no idea if there's a way to reliably validate that it's not porn, though.

**Comment by KyleAMathews** [comment]
Yeah, it doesn't have to be perfect — or do any checking really at first — we can just manually check them after the fact and revert any that we don't want in the showcase.

**Comment by KyleAMathews** [comment]
I think just checking they're linking to a Gatsby site would be sufficient to start with — which is trivial as grab HTML from site and look for `___gatsby`

**Comment by KyleAMathews** [comment]
The bot could also post a screenshot to the comment section which would further speed up reviewing sites.

**Comment by fk** [comment]
Ref. #6538
