### ISSUE TITLE
Debugging Gatsby TypeScript in v2

### ISSUE THREAD

**Issue by azdanov** [gatsbyjs/gatsby#6638]
What is the correct way to debug a __v2__ Gatsby project made in TypeScript?

I've managed to get the debugger running, thanks to [debugging-the-build-process](https://github.com/pieh/gatsby/blob/683e1f594daab48af8baeb76da98f78296c7b40f/docs/docs/debugging-the-build-process.md) guide.

But it only worked for `.js` files, like `gatsby-node.js`, both in Chrome and VSCode.

Are there additional steps for TypeScript, or is it even possible?

**Comment by ascorbic** [comment]
It should just work, though you need to enable `sourceMaps` in your `tsconfig.json` otherwise it will just debug the transpiled js.

**Comment by azdanov** [comment]
I have `sourceMaps` enabled.

<details>
<summary>tsconfig.json</summary>

```json
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "jsx": "preserve",
    "lib": ["dom", "es2015", "es2017"],
    "module": "commonjs",
    "noEmit": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "outDir": "./dist/",
    "preserveConstEnums": true,
    "removeComments": false,
    "sourceMap": true,
    "strict": true,
    "target": "esnext",
    "typeRoots": ["src/types", "node_modules/@types"]
  },
  "include": ["./src/**/*"]
}
```

<details>

**Comment by ascorbic** [comment]
What happens when you try to debug TypeScript then?

**Comment by azdanov** [comment]
Skips through breakpoints.

It does stop on `gatsby-node.js` file.

**Comment by ascorbic** [comment]
Does it work in the browser?

**Comment by azdanov** [comment]
Same. Only reacts to `.js`.

**Comment by ascorbic** [comment]
In the browser dev tools, can you see the ts files?

**Comment by azdanov** [comment]
I can. And do set breakpoints there. Skips through `.ts` files.

<img width="1273" alt="screen shot 2018-07-21 at 11 40 17" src="https://user-images.githubusercontent.com/6123841/43033883-e7b8e9f6-8cda-11e8-9ed7-75761afdca71.png">

**Comment by ascorbic** [comment]
If you put a console.log in the TypeScript file, what filename does it show in the console, and if you click through, what file does it show? Does putting a `debugger;` statement work?

**Comment by azdanov** [comment]
`console.log` shows original `.tsx` file.

`debugger` does work! But the code is transpiled. And it works even with `gatsby develop`.

**Comment by ascorbic** [comment]
This situation usually mens the source ma is being messed up somehow, either by Babel or TypeScript. I can't see anything immediately wrong with your project, but you could try enabling inlineSourceMaps in the tsconfig.

**Comment by pieh** [comment]
Right now I'm not sure if there's easy way to do this - we use webpack to create bundle that is used when rendering to html files, so this step probably messes up breakpoints - because we don't use source files directly. That debugging guide was mainly to debug `gatsby-node` code (either in your site or in plugins) and `gatsby` core code, but if we could figure out how to debug html rendering with it - it would be 💯

**Comment by pieh** [comment]
I think for now we should clarify this information in guide and mention the `debugger;` trick.

**Comment by ascorbic** [comment]
It works in my project though, so it is possible.

**Comment by azdanov** [comment]
@ascorbic Could you post a link? I'd like to compare the configuration files.

**Comment by ascorbic** [comment]
Sure: https://github.com/aerian-studios/aerian-site-rebuild/
You can see it live too. Go to https://beta.aerian.com/ and open up your dev tools. Find src/components/ShowcaeCarousel.tsx and set a breakpoint in the handleChange method. Then scroll the window.

**Comment by ascorbic** [comment]
Oh, I've just noticed something. I've been working in Firefox, which works fine. I just tried beta.aerian.com in Chrome and it *didn't* hit the breakpoint. Have you tried your site in Firefox?

**Comment by azdanov** [comment]
I've managed to get some results with `production` build on __Firefox__, but for some reason with all variables _undefined_. Same with __Chrome__. At least debugger was stopping on the breakpoints.

Could it be that `development` strips down the necessary sourcemaps?

@ascorbic It does work on Chrome. I couldn't make it work on Firefox, it kept stopping at compiled code.

**Comment by azdanov** [comment]
By using `source-map-loader` webpack plugin I've managed to sync sourcemaps, before there were similar issues as [here](https://stackoverflow.com/questions/35870940/typescript-babel-sourcemaps-using-webpack).

@m-allanson Should it be included by default in `gatsby-plugin-typescript`? 

```js
module.exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    devtool: "source-map",
    module: {
      rules: [
        {
          test: /\.js$/,
          use: ["source-map-loader"],
          enforce: "pre"
        }
      ]
    }
  });
};
```

Need to figure out how to make it work for `incline-source-map`.
