### ISSUE TITLE
[v2] Problems with offline-plugin?

### ISSUE THREAD

**Issue by LeKoArts** [gatsbyjs/gatsby#6644]
Today and yesterday I had problems with next.gatsbyjs.org. When I visited the site with my computer, the site just went blank (like in the video). The console threw a bunch of errors (files not found). After clearing the cache, the site worked again.

Trying the site on my iPhone again, the same thing occured:
https://drive.google.com/file/d/1foFKSrhu0wh01WYy9iePRJ4cMGKPzR31/view?usp=sharing

I also had a similar issue on my site that after an update the service worker served the old content and didn't grab the new content.

**Comment by dbrookes** [comment]
Yes having the same issue, I believe this is the reason: https://github.com/gatsbyjs/gatsby/issues/4779#issuecomment-406701740

**Comment by jarrodu** [comment]
I am having a similar problem with Firefox on Android.

The screen flickers then goes white when I access the my app while offline.

**Comment by KyleAMathews** [comment]
This should be fixed by https://github.com/gatsbyjs/gatsby/pull/6566

Let us know if there's any more issues!
