### ISSUE TITLE
[v2] GraphQL data injection doesn't seem to work

### ISSUE THREAD

**Issue by mkbs700** [gatsbyjs/gatsby#6647]
Hi, I am trying to use gatsby-image inside a component, but I can't seem to get the GraphQL queries sent into the component I'm building. I'm still very new to Gatsby and can't figure out why.

There is a StaticQuery in the Layout component. That's the only other GraphQL query in my project.

My component looks like this:

```jsx
import React from 'react'
import Img from 'gatsby-image'

const Background = props => (
  <Img
    fluid={props.data.file.childImageSharp.fluid}
    alt="background cloud image"
  />
)

export default Background

export const pageQuery = graphql`
  query ImageQuery {
    file(name: { eq: "background" }) {
      childImageSharp {
        fluid(maxWidth: 1000) {
          ...GatsbyImageSharpFluid
        }
      }
    }
  }
`
```

This throws a lot of error messages, starting with a "Uncaught TypeError: Cannot read property 'file' of undefined". I tried to replace the component with a `console.log(props)` to see what is going on. The log was an empty `{}`.

My gatsby-config.js looks like this: 

```js
module.exports = {
  siteMetadata: {
    title: 'Demo',
    description:
      'Demo',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-styled-components',
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `contents`,
        path: `${__dirname}/src/contents/`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images/`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`
  ],
}
```

If I go to the "__graphql", the query below returns intended information.

```graphql
{
  file(name: {eq: "background"}) {
    name
    id
    childImageSharp {
      fluid(maxWidth: 3000) {
        src
      }
    }
  }
}
```

Returns this:

```json
{
  "data": {
    "file": {
      "name": "background",
      "id": "35bbed9b-5074-5622-9846-2c718f09a24f",
      "childImageSharp": {
        "fluid": {
          "src": "/static/background-f35ae37c12d455eab3bc77a7caa948e2-ef3a8.png"
        }
      }
    }
  }
}
```

There is indeed a picture at "http://localhost:8000/static/background-f35ae37c12d455eab3bc77a7caa948e2-ef3a8.png".

I believe I didn't correctly make Gatsby inject the GraphQL data. I've read the docs but I seem to be doing everything right. Any ideas? :D Thank you!

**Comment by LeKoArts** [comment]
If you‘re using v1 you should query for id, if v2 originalName. In both cases you then have to put the regex to „/background.png/”

**Comment by pieh** [comment]
If your `Background` component isn't page template (which I suspect it isn't) - this query won't run and You should see warning about it in terminal - use `StaticQuery` there

**Comment by mkbs700** [comment]
@pieh Thank you very much! I didn't notice the warning in terminal. How can I specify a component to be a page template? Is the Layout one which comes with default starter the only template?

I have just changed the query into a StaticQuery. Now the query is firing, but the Gatsby-Image component is not processing files when starting up the dev server. In the browser console, for example, the "/static/background-f35ae37c12d455eab3bc77a7caa948e2-ef3a8.png" results in a 404. However, if I open up "___graphql" again and query with that query in my original post, a "Generating image thumbnails" message appears in the terminal Gastby dev server is running in, and going back to the in browser preview, the image gets loaded (not 404 anymore).

Is this becuase Gatsby-Image only supports page queries?

My current code in Background component looks like this:

```jsx
const Background = ({ children, data }) => (
  <StaticQuery
    query={graphql`
      query ImageQuery {
        file(name: { eq: "background" }) {
          childImageSharp {
            fluid(maxWidth: 3000) {
              ...GatsbyImageSharpFluid
            }
          }
        }
      }
    `}
    render={data => (
        <Img
          style={{
            position: 'absolute',
          }}
          fluid={data.file.childImageSharp.fluid}
          alt="background cloud image"
        />
    )}
  />
)
```

@LeKoArts Thanks for the suggestion, I'm using v2. Not sure if I have to put regex there, since I have only one pic and I'm sure of its file name (using eq here).

**Comment by m-allanson** [comment]
> How can I specify a component to be a page template? 

Components in your `src/pages` directory will be treated as page components automatically. It sounds like you might've been through it already, but if not, I'd recommend running through [the tutorial](https://next.gatsbyjs.org/tutorial/). Or there's more in depth [docs on creating and modifying pages](https://next.gatsbyjs.org/docs/creating-and-modifying-pages/).

Are you able to post a link to your repo? The code you've posted above looks like it should work.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
