### ISSUE TITLE
[gatsby-source-contentful] Query custom field on Blog

### ISSUE THREAD

**Issue by isabellachen** [gatsbyjs/gatsby#6650]
Can someone tell me how to query a custom field with gatsby-souce-contentful? I have a custom field called Flickr Album Id on my Blog content model. Per the docs of gatsby-souce-contentful, I expect to be able to query a field 'flickrAlbumId' or something like this, but I am unable to do so. How do I get data from my custom field?

``` 
query blogPostQuery($slug: String!){
    contentfulBlog(slug: {eq:$slug}){
      title
      slug
      flickrAlbumId
    }
  }
```

**Comment by isabellachen** [comment]
I recompiled the gatsby build and gatsby-source-contentful is working as expected.

**Comment by Khaledgarbaya** [comment]
Hey @isabellachen I'm glad that worked for you. I will close the issue for now and feel free to create a new if you have issues.

Khaled
