### ISSUE TITLE
Images not generated when building

### ISSUE THREAD

**Issue by shaneosullivan** [gatsbyjs/gatsby#6653]
## Description

When using gatsby-next, images are not built into the /public folder when doing `yarn build`.  I have six images, and one that is small enough to be inlined shows up just fine in the built site, but the others do not. Looking in the `/public` folder, they do not exist.

There are no build errors or warnings displayed in the terminal.

### Steps to reproduce
Easiest way to reproduce is to clone the repo I set up for this issue at `https://github.com/shaneosullivan/gatsby-issue-min-repro`

To do it manually:

1. Create a new project 
`gatsby new myproject https://github.com/gatsbyjs/gatsby-starter-default#v2`

2. Import the attached file
![shane](https://user-images.githubusercontent.com/49378/43043245-f6849764-8d43-11e8-8fcb-b360f9ce4838.jpg) to the `pages/index.js` component

`import ShaneImage from './images/shane.jpg'`

3. And use it in an image

`<img src={ShaneImage} alt="Please work" />`

Note that it shows up just fine when doing `yarn develop`

Now do `yarn build` and note that it does not appear.

### Expected result

The image should appear in both the develop and build states
### Actual result
The image only shows up in the develop state, and not after building.  Look in the `/public` folder to see that the file does not exist
What happened.

### Environment

 System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 9.2.1 - /usr/local/bin/node
    Yarn: 1.3.2 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.0.0-beta.55 => 2.0.0-beta.55 
    gatsby-link: ^1.6.40 => 1.6.46 
    gatsby-plugin-react-helmet: ^2.0.10 => 2.0.11 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

### File contents (if changed)

`gatsby-config.js`: N/A 
```
module.exports = {
  siteMetadata: {
    title: 'My Site.',
  },
  plugins: ['gatsby-plugin-react-helmet'],
}
```

`package.json`: N/A 
```
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "gatsby": "next",
    "gatsby-plugin-react-helmet": "next",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-helmet": "^5.2.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write 'src/**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "prettier": "^1.12.0"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  }
}
```

`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by Mike-Dax** [comment]
Your test repo works for me.

The photo gets placed in `public/static/shane-ab4932bd10593dd51dbf7c4072ef8fd1.jpg`

Are you just opening the index.html file directly or are you using a tool like `serve` to view it? If you just open the index.html file in a browser static assets won't work given the absolute paths.

The master branch is on v2 now so you shouldn't have to specify that tag.

**Comment by shaneosullivan** [comment]
Ah yes, it's because I was opening the page directly on the file system.  I had not realized Gatsby didn't generate relative urls.  Will close this out, but perhaps consider generating relative urls?

**Comment by LeKoArts** [comment]
Gatsby‘s output is meant to be on host with a webserver, so I don’t think that this will be added

**Comment by KyleAMathews** [comment]
I'm not opposed to relative URLs. Is there any downside to them? I honestly don't remember why I choose absolute over relative. That being said, we generally expect people to preview pages w/ `gatsby serve` which I guess is why this hasn't come up much.
