### ISSUE TITLE
[gatsby-plugin-sass] Little improvements

### ISSUE THREAD

**Issue by rafaell-lycan** [gatsbyjs/gatsby#6655]
## Summary

1. Use the `node-sass-chokidar` lib instead `node-sass` to increase boost performance. 
2. Add `sass-resources-loader` to make common resources (variables, mixins, etc) available in all Sass/Scss files in the project if you need.

### Basic example

```javascript
plugins: [
  {
    resolve: `gatsby-plugin-sass`,
    options: {
      ...
      resources: ['./path/to/vars.scss', './path/to/mixins.scss']
    },
  },
];
```
Check the [documentation](https://github.com/shakacode/sass-resources-loader) for more examples.

### Motivation

1. As a lab, I changed the package in my application during developing mode, and it decreased the RAM consumed by 15%.
2. The `includePaths` param doesn't work to make my variables or mixins available on my `.scss` files.

**Comment by rafaell-lycan** [comment]
@m-allanson I didn't know that, nice feedback btw.

The only thing that still not working it's the `includePaths `. Somehow It doesn't load the `../sass/base/*` files.

Thanks a lot.

**Comment by sambaines** [comment]
@rafaell-lycan did you manage to get `sass-resources-loader` working correctly in the end? 

And would this allow me to be able access variables in a sass partial, for example `_variables.scss` with `$primary-color: red;` , inside/within a `sass.module.scss` file? As currently Gatsby out of the box with just `gatsby-plugin-sass@next` installed doesn't seem to allow this or maybe the import path is wrong. Either way I couldn't get it to work.

**Comment by chengyin** [comment]
Seems like the [custom webpack config](https://next.gatsbyjs.org/docs/add-custom-webpack-config/) merging can combine `gatsby-plugin-sass` and custom configs, so personally I have this `gatsby-node.js` file to _append_ `sass-resources-loader`:

```js
exports.onCreateWebpackConfig = ({
  actions,
  stage,
  rules,
  plugins,
  loaders,
}) => {
  const sassRuleModules = {
    test: /\.module\.s(a|c)ss$/,
    use: [
      {
        loader: 'sass-resources-loader',
        options: {
          resources: [
            'src/styles/_variables.scss',
            'src/styles/_mixins.scss',
            'src/styles/_typography.scss',
          ],
        },
      },
    ],
  };

  actions.setWebpackConfig({
    module: {
      rules: [sassRuleModules],
    },
  });
};
```

**Comment by chengyin** [comment]
Also, sambaines, if you don't mind repeating `@import "variables"` in your `.module.scss` files, `includePaths` works fine. In your `gatsby-config.js` file do something like this:

```js
    {
      resolve: 'gatsby-plugin-sass',
      options: {
        includePaths: ['src/styles'],
      },
    },
```

Path is relative to the project root.

**Comment by sambaines** [comment]
> Also, sambaines, if you don't mind repeating @import "variables" in your .module.scss files, includePaths works fine. In your gatsby-config.js file do something like this:

    {
      resolve: 'gatsby-plugin-sass',
      options: {
        includePaths: ['src/styles'],
      },
    },

Thanks @chengyin for taking the time to respond, much appreciated (I'm relatively new to gatsby and front end in general) - the `includePaths` option for the sass plugin seems to have done the trick and I can get gatsby to run `gatsby develop` and compile `*.module.scss` with the imported variables, but did have to then alter the `@import` path for the `main.scss` file to the styles folder but its all good learning and now I don't need to touch the webpack config!

**Comment by tr1s** [comment]
> To auto-include some sass vars/mixins/etc. into your component *.scss files you simply can pass `data` option for node-sass with `@import`.
> e.g: if you have common file in `src/components/vars.scss`, then use in your plugins declaration:
> 
> ```
>     {
>       resolve: `gatsby-plugin-sass`,
>       options: {
>         data: '@import "vars.scss";',
>         includePaths: [
>           'src/components',
>         ],
>       },
>     }
> ```

Thank you very much! Data option worked great.

This just helped me solve my Gatsby issues. Now I've got mixins and variables getting injected while also live updating that can be used in Gatsby's CSS modules.

Perfect :)

**Comment by manishie** [comment]
FYI, with newer versions of sass-loader the above approach stops working as the data option is no longer supported.  Instead of:

```
    options: {
      data: `@import "${__dirname}/sass/variables";`,
    }

```

Use:

```
    options: {
      additionalData: `@import "${__dirname}/sass/variables";`,
    }
```
