### ISSUE TITLE
Google Fonts are not downloaded in develop mode

### ISSUE THREAD

**Issue by breeswish** [gatsbyjs/gatsby#6657]
## Description

When using develop mode (`gatesby develop`), plugin gatsby-plugin-typography will not embed Google font `<link>` at all, both in v1 and v2, even if `googleFonts` field exists in the typography config file. However it is working after build.

### Steps to reproduce

`typography.js`:

```js
const typo = new Typography({
  googleFonts: [
    {
      name: 'Open Sans',
      styles: ['300', '400', '700'],
    },
  ],
  bodyFontFamily: ['Open Sans', 'sans-serif'],
  headerFontFamily: ['Open Sans', 'sans-serif'],
});
export default typo;
```

### Expected result

Google fonts are loaded.

### Actual result

Google fonts are not loaded in develop mode.

### Environment

```
  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 5.2 - /bin/zsh
  Binaries:
    Node: 8.11.3 - /usr/local/bin/node
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 60.0.2
    Safari: 11.1.1
  npmPackages:
    gatsby: ^1.9.273 => 1.9.273 
    gatsby-link: ^1.6.45 => 1.6.45 
    gatsby-plugin-nprogress: ^1.0.14 => 1.0.14 
    gatsby-plugin-preact: ^1.0.17 => 1.0.17 
    gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11 
    gatsby-plugin-sharp: ^1.6.48 => 1.6.48 
    gatsby-plugin-stylus: ^1.1.21 => 1.1.21 
    gatsby-plugin-typography: ^1.7.19 => 1.7.19 
    gatsby-remark-autolink-headers: ^1.4.19 => 1.4.19 
    gatsby-remark-copy-linked-files: ^1.5.37 => 1.5.37 
    gatsby-remark-images: ^1.5.67 => 1.5.67 
    gatsby-remark-prismjs: ^2.0.4 => 2.0.4 
    gatsby-transformer-remark: ^1.7.44 => 1.7.44 
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```

### File contents (if changed)

```js
module.exports = {
  ...
  plugins: [
    ...
    {
      resolve: 'gatsby-plugin-typography',
      options: {
        pathToConfigModule: 'path/to/typography.js',
      },
    },
  ],
};
```

**Comment by Mike-Dax** [comment]
Possibly related: I'm finding that typeface-* packages are similarly not working, I'm receiving 404 errors when the fonts are downloaded in the browser. Builds work however.

**Comment by m-allanson** [comment]
@breeswish Could you set up a small example repo that demos this problem using Gatsby v2?

**Comment by Chuloo** [comment]
Clone reproduction [here](https://github.com/Chuloo/gatsby-6657), built on the hello-world starter using Gatsby v1.
 
At first trial, google fonts were not loaded. I moved on to create the same project Gatsby v2, fonts were loaded normally. _Going back to test the v1 reproduction again_, everything seemed to work fine. Fonts loaded both on `gatsby develop` and `gatsby build`. Things to note are:

- Restart the development server after adding fonts in `src/utils/typography.js` file.
- Use Gatsby v2, worked on the first try.

Let's know if you still run into the same issue. 👍

**Comment by Chuloo** [comment]
Closing this out as a duplicate. #7399 seems to capture the larger issue of latest `gatsby-plugin-typography` requiring a server reload to implement changes. 
Feel free to [open a new issue here](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you experience something different.
