### ISSUE TITLE
gatsby-image additional callback onStartLoad

### ISSUE THREAD

**Issue by zionis137** [gatsbyjs/gatsby#6659]
## Summary

An additional prop for `gatsby-image` called `onStartLoad` which takes a function and fires when the full-sized starts to get loaded.
Very similar to the `onLoad` prop but always fires earlier. 
It could be called [here](https://github.com/gatsbyjs/gatsby/blob/0d9f892e5df04e7c38e3ca8cc32946d35e5dfc0c/packages/gatsby-image/src/index.js#L174) 

### Motivation
I am recreating this page with gatsbyJS: https://qwergelesen.de/
Every post-box has an animation when it becomes visible. Currently I start the animation with the `onLoad` prop of `gatsby-image`. Hence the loading of the image blocks everything, on devices with slow internet-connections it is very noticeable. The user never sees the small preview, hence `gatsby-image` is not utilized to the fullest. 

I could write my own `IntersectionObserver` which fires exactly when the `gatsby-image` observer fires... which seems kind of redundant and would increase the workload on the client.

**Comment by KyleAMathews** [comment]
Seems like a reasonable addition! Would love to see a PR that fleshes out the idea a bit more.

**Comment by LekoArts** [comment]
Feature was merged.
