### ISSUE TITLE
How to add scroll animation for when the <Link> for the page you're already on is clicked?

### ISSUE THREAD

**Issue by ShayanJavadi** [gatsbyjs/gatsby#6664]
Let's say you're on the home page and you click the link to go to the home page. As of now Gatsby catches this and takes you to the top of the page. This is great and all, however the scroll doesn't have any animation. is there any way to add an animation to the <Link> component to handle this?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
