### ISSUE TITLE
How can I include mapbox-gl in Gatsby?

### ISSUE THREAD

**Issue by lipis** [gatsbyjs/gatsby#6667]
I'm trying to include the https://github.com/mapbox/mapbox-gl-js in a Gatsby project, but I'm getting an error during build. Works nicely in dev mode.

(If someone wants to try this should be easier: https://github.com/alex3165/react-mapbox-gl)

```bash
...{}),!this.workerSources[e][t][r]){var i={send:function(t,r,i){n.actor.send(t,r,i,e);}};this.workerSources[e][t][r]=new this.workerSourceTypes[t](i,this.getLayerIndex(e));}return this.workerSources[e][t][r]},He.prototype.getDEMWorkerSource=function(e,t){return this.demWorkerSources[e]||(this.demWorkerSources[e]={}),this.demWorkerSources[e][t]||(this.demWorkerSources[e][t]=new D),this.demWorkerSources[e][t]},"undefined"!=typeof WorkerGlobalScope&&"undefined"!=typeof self&&self instanceof WorkerGlobalScope&&new He(self),He});
  32 |


  WebpackError: ReferenceError: self is not defined

  - mapbox-gl.js:29
    [lib]/[mapbox-gl]/dist/mapbox-gl.js:29:206

  - mapbox-gl.js:22 define
    [lib]/[mapbox-gl]/dist/mapbox-gl.js:22:1

  - mapbox-gl.js:33
    [lib]/[mapbox-gl]/dist/mapbox-gl.js:33:1

  - mapbox-gl.js:3
    [lib]/[mapbox-gl]/dist/mapbox-gl.js:3:1

  - mapbox-gl.js:6 Object../node_modules/mapbox-gl/dist/mapbox-gl.js
    [lib]/[mapbox-gl]/dist/mapbox-gl.js:6:2

  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1

  - map.js:21 Object../node_modules/react-mapbox-gl/lib/map.js
    [lib]/[react-mapbox-gl]/lib/map.js:21:1

  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1

  - index.js:3 Object../node_modules/react-mapbox-gl/lib/index.js
    [lib]/[react-mapbox-gl]/lib/index.js:3:1

  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1


  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1

  - sync-requires.js:8 Object../.cache/sync-requires.js
    lib/.cache/sync-requires.js:8:51

  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1

  - static-entry.js:9 Module../.cache/static-entry.js
    lib/.cache/static-entry.js:9:22

  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ascorbic** [comment]
I'm not sure about Mapbox, but with Leaflet the problem is that it expects to find `window`, which isn't available in production build. The fact it works in develop means it may be a similar problem. I had to use a silly workaround to load the library only on `componentDidMount`: https://github.com/aerian-studios/aerian-site-rebuild/blob/master/src/components/MapView/MapView.tsx

**Comment by m-allanson** [comment]
As @ascorbic mentions, this is typically caused by libraries that expect to always run in a browser environment. During `gatsby build`, Gatsby runs your code in a Node.js environment to render out all your static html files, so browser globals like `window` don't exist.

Maybe that's not exactly what's happening here (I don't think `self` is a browser global?), but it'd be a good first step to investigate. There's a bit of info here https://www.gatsbyjs.org/docs/debugging-html-builds/

Also searching the `mapbox-gl-js` repo for `ReferenceError: self is not defined` provides a few results that might be relevant.

**Comment by lipis** [comment]
Would that work in Gatsby? https://github.com/mapbox/mapbox-gl-js/issues/4593#issuecomment-397872590

(can't test it at the moment)

**Comment by lipis** [comment]
Here is the minimal example that works locally, but fails during build: https://github.com/lipis/mapbox-gatsby

I didn't manage to make it work.. can anyone else take a look?

(Feel free to use the access key, it's for testing purposes only and I'll delete it afterwards)

**Comment by lipis** [comment]
Thanks to @herrmannplatz!! 

In `gatsby-node.js`:

```js
exports.onCreateWebpackConfig = ({ actions, stage }) => {
  if (stage === "build-html") {
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /mapbox-gl/,
            use: ['null-loader']
          },
        ],
      }
    })
  }
};
```

**Comment by stemmlerjs** [comment]
I wasn't able to get mine to work as per the above suggestions. I ended up mocking my implementation to get it to work.

```javascript
let mapboxgl
let ReactMapboxGl = {}

if (typeof window !== `undefined`) {
  mapboxgl = require('mapbox-gl')
  ReactMapboxGl = require('react-mapbox-gl')
} else {
  ReactMapboxGl.Map = () => {
    return class Mock extends React.Component {
      constructor() {
        super()
      }
      render() {
        return <div />
      }
    }
  }
}

const Map = ReactMapboxGl.Map({
  accessToken:  '[your-token-here]',
})

class DirectoryMap extends React.Component {
  constructor(props) {
    super(props)
  }

  render() {
    return (
      <div className="directory-map">
        <Map
          ref={e => {
            this.map = e
          }}
          zoom={[11]}
          speed={[0.6]}
        >
        </Map>
      </div>
    )
  }
}
```

**Comment by jonlow** [comment]
For this to work in the latest version of Gatsby, you need to modify https://github.com/gatsbyjs/gatsby/issues/6667#issuecomment-409836864 to this:

```
exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
  if (stage === "build-html") {
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /mapbox-gl/,
            use: loaders.null(),
          },
        ],
      },
    })
  }
}
```


so `loaders.null()` instead of `null-loader`, as per https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules

**Comment by arhoy** [comment]
@jonlow I tried this but it is not working for me, I am not really sure what is going on in the code above you explain or take a look at my repo here to see why I cannot load mapbox in production?

Thanks for any help in advance
https://github.com/arhoy/fashion-two

**Comment by jonniebigodes** [comment]
@arhoy if you don't mind i'll take a look tomorrow and see if i can provide you with a solution to the issue. Do you mind waiting a bit?

**Comment by arhoy** [comment]
That would be great! Thank you so much

**Comment by chriswhong** [comment]
For those trying to modify `onCreateWebpackConfig` in `gatsby-node.js`, here's an example of modifying existing settings to add special handling for mapboxGL: https://github.com/brendan-ward/gatsby-starter-mapbox/blob/master/gatsby-node.js

**Comment by jahlherapath** [comment]
Have tried all the above solutions and am still having troubles with my build. Any help would be much appreciated!

**Comment by woss** [comment]
none of the above worked for me so I did the inline exclusion like this
```ts
import mapboxgl from "!mapbox-gl" // https://webpack.js.org/concepts/loaders/#inline
```

Following the MApbpx guideline https://docs.mapbox.com/mapbox-gl-js/api/#excluding-gl-js-explicitly-from-transpilation

**Comment by Hless** [comment]
None of the above worked, because I was using a React library that included mapbpx-gl under the hood. By checking the [mapbox docs](https://docs.mapbox.com/mapbox-gl-js/guides/install/#transpiling) I found another solution that worked.


You can add the following the following property to package.json:
```"browserslist": [">0.25%", "not dead", "not ie 11"]```

This is the default gatsby browserlist config while additionally removing IE11 support, which I find acceptable at this point.

I did try to find a solution by trying to change the babel transpilation excludes, but I found this to be too difficult with gatsby.

**Comment by traversal** [comment]
@Hless, if you were using `react-map-gl` as I was, or for anyone else who is using that, here is a way to get this going in a Gatsby build (well it worked for me): 

First, I installed worker-loader:

    npm i --save-dev worker-loader

Then in `gatsby-node.js` I added this (among other rules):

    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /\bmapbox-gl-csp-worker.js\b/i,
            use: { loader: 'worker-loader' },
          },
        ]
      },
    });

    if (stage === 'build-html') {
      actions.setWebpackConfig({
        module: {
          rules: [
            {
              test: /mapbox-gl/,
              use: loaders.null(),
            },
          ]
        }
      })
    }

All of the above is documented in various places, but the secret-sauce comes from the `Map` component in `react-map-gl` allowing you to override the library used for `mapbox-gl`. Here we're still really using `mapbox-gl`, but we need to modify the workerClass as described in https://docs.mapbox.com/mapbox-gl-js/guides/install/#transpiling

I created a wrapper component for this in Typescript like so (excuse the @ts-ignores, I couldn't work out how to make Typescript ignore the lack of types for those libs):

    /* A wrapper around react-map-gl's Map component to load the correct CSS, and tweak the workerClass to allow this to work with Gatsby */
    import React from 'react';
    // @ts-ignore
    import mapboxgl from 'mapbox-gl/dist/mapbox-gl';
    // @ts-ignore
    import MapboxWorker from 'mapbox-gl/dist/mapbox-gl-csp-worker';
    // @ts-ignore
    mapboxgl.workerClass = MapboxWorker;
    import { Map as MapGL, MapProps } from 'react-map-gl';
    import 'mapbox-gl/dist/mapbox-gl.css';

    export const Map: React.FC<MapProps> = (props) => 
      <MapGL {...props} mapLib={mapboxgl} />

Now I just use the `Map` component from above, and I no longer get the transpiling web worker errors in a Gatsby production build. 

Quite a nightmare, but thought this might help someone else avoid wasting hours on it! :)

**Comment by edsonJordan** [comment]
**Do you have a repository where I can see the project?**
