### ISSUE TITLE
[gatsby-remark-catch-link] doesn't redirect properly if someone links to a full URL on the same site

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#6686]
If you visit the site showcase blog post at https://next.gatsbyjs.org/blog/2018-07-20-why-we-built-the-site-showcase/ and try to click on the showcase link, it doesn't work. We should update gatsby-remark-catch-links so it can handle full URLs pointing to the same domain correctly.

- https://next.gatsbyjs.org/showcase/
- https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-catch-links/src/catch-links.js

**Comment by kylegreene** [comment]
I will take this on @KyleAMathews

**Comment by KyleAMathews** [comment]
Thanks @kylegreene!

**Comment by shobhitchittora** [comment]
@KyleAMathews this thread has been inactive for some days, so I went ahead and pushed a PR. Please  review.

**Comment by chasemccoy** [comment]
@KyleAMathews @shobhitchittora @kylegreene 

I am still having this issue on the latest beta version of Gatsby and `gatsby-plugin-catch-links`. The internal links from the `tableOfContents` field in my `markdownRemark` queries do not get intercepted and are broken.

**Comment by chasemccoy** [comment]
Should we reopen this issue, or should I file a new one?

**Comment by chasemccoy** [comment]
Never mind, looks like it got fixed in #6990

**Comment by haxzie** [comment]
Found a similar issue in Gatsby docs https://www.gatsbyjs.org/docs/gatsby-cli/#gatsby-cli The `Gatsby Starters` link renders a 404 page. The original link specified is `https://www.gatsbyjs.org/docs/gatsby-starters/` while the same entered in browser redirects to `https://www.gatsbyjs.org/starters/?v=2`
