### ISSUE TITLE
Generate og images using puppeteer

### ISSUE THREAD

**Issue by antonmedv** [gatsbyjs/gatsby#6691]
## Summary

I want to create og images for all my pages automatically using puppeteer (headless chrome).

### Basic example

Some plugin for gatsby to automatically use puppeteer to render some special page ogimage.html to png.

### Motivation

Better sharing links.

**Comment by m-allanson** [comment]
Related issue: #1199 

Something that might also be useful is the screenshot transformer plugin: https://www.gatsbyjs.org/packages/gatsby-transformer-screenshot/. It uses headless Chrome set up on AWS Lambda to take site screenshots and then pulls them into Gatsby.

**Comment by antonmedv** [comment]
Not stale

**Comment by antonmedv** [comment]
reopen

**Comment by antonmedv** [comment]
Implemented myself.

**Comment by tormi** [comment]
I am also interested in this. @antonmedv , any hints?

**Comment by antonmedv** [comment]
Just build custom bash script :)
