### ISSUE TITLE
gatsby-blog-starter-kit (demo) link should be updated to use v2

### ISSUE THREAD

**Issue by deadcoder0904** [gatsbyjs/gatsby#6693]
gatsby-blog-starter-kit (demo) is pointing to https://dschau.github.io/gatsby-blog-starter-kit/ & it is giving some 404 (not Gatsby 404s, Github 404s).

The correct link should be https://gatsby-blog-starter-kit.netlify.com

I think its good issue for First Timers :)

**Comment by deadcoder0904** [comment]
Also, open-crowd-fund (demo) points to https://www.roadtolearnreact.com but should be https://roadtoreact.com

I think there should be a script written to find all the 404s from Gatsby site because this website has too many links & it will grow overtime. So that makes sense as someone will retire their website so its better to remove dead links & the script might help with that.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by deadcoder0904** [comment]
This also should be re-opened due to a majority of 404s on the whole Gatsby website

**Comment by KyleAMathews** [comment]
@deadcoder0904 you want to run a dead link checker on next.gatsbyjs.org and PR some fixes?

**Comment by KyleAMathews** [comment]
And just closed 400 issues so don't take me closing this personally :-D

**Comment by deadcoder0904** [comment]
Naah @KyleAMathews I wasn't taking this personally. I know this is bigger than one person. Just stated a valid point. Unfortunately can't make a PR right now but will keep this in mind in the future :)

**Comment by deadcoder0904** [comment]
This might be helpful in future.

https://crawly.app

Crawly is a tool that crawls your web applications to find out broken pages to help you to maintain it. Crawly has a powerful alerting system that if any page of your project is broken, you will get a notification.
