### ISSUE TITLE
Typo on gatsby-source-filesystem Plugin Page

### ISSUE THREAD

**Issue by deadcoder0904** [gatsbyjs/gatsby#6697]
The following on 
https://www.gatsbyjs.org/packages/gatsby-source-filesystem/?=#createfilepath & 
https://next.gatsbyjs.org/packages/gatsby-source-filesystem/?=#createfilepath

```js
// Defaults to `src/pages`. For the example above, you'd use `src/contents`.
```

should be 

```js
  // Defaults to `src/pages`. For the example above, you'd use `src/content`.
```

**Comment by m-allanson** [comment]
Done in #6699, thanks @deadcoder0904 and @kellylawrence 👍
