### ISSUE TITLE
Drop shadows in Starter Showcase

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#6703]
Drop shadow on screenshots on index page creates an extra line on the bottom of the screenshots. Move the thumbnail bit from site showcase and reuse it here.

**Comment by sw-yx** [comment]
the line was a small typo! nice catch. fixed. not sure what the "thumbnail bit" means here.

**Comment by fk** [comment]
Saw your updates on https://dreamy-shannon-191f15.netlify.com/starter-showcase/, looking good!

> not sure what the "thumbnail bit" means here.

We thought about refactoring the card thumbnail + attached hover styles to a component so we can use them in both site and starter showcase.

**Comment by sw-yx** [comment]
ok, closing
