### ISSUE TITLE
Submit to Starter Library instructions

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#6704]
Write instructions similar to submit-to-site-showcase instructions.

**Comment by shannonbux** [comment]
@jlengstorf will Peril be able to validate `.md` submissions?

**Comment by shannonbux** [comment]
The Peril automation is set to be addressed during v2.0 Starter Showcase Issue #7560, but I wanted to make sure we thought it through during v1.0.

**Comment by jlengstorf** [comment]
Yeah, we can validate any file type. The levels of effort will vary, but it's certainly possible. Something like [this](https://www.npmjs.com/package/front-matter) ought to make it pretty straightforward.
