### ISSUE TITLE
Add prev/next links to detail page - starter showcase

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#6711]
Add prev/next links like we have in Site Showcase

**Comment by sw-yx** [comment]
well - there are no prev/next links in the design at the moment...

**Comment by shannonbux** [comment]
Hi @sw-yx, can you clarify your question?

**Comment by sw-yx** [comment]
well, check the wireframe:


![startershowcasedetail](https://user-images.githubusercontent.com/32467162/43238624-20744244-904c-11e8-8f1d-9b402cf1c2fe.png)

there's no design for prev/next links...

(again offering personal opinion here - i dont think this is really needed unlike the site showcase so i never raised a question about it)

**Comment by shannonbux** [comment]
Thanks for clarifying! Hm, I can see your point--maybe people won't
"browse" through starters as much as they would site showcase. I don't know
the answer and would have to do a couple usability tests to be sure. I will
do that!

This conversation is reminding me of what I have noticed which is that
there is no clear way to get back to the index page from a detail page
other than the back arrow on the browser. @fk ideas for how to do that?

**Comment by sw-yx** [comment]
ah. this index navigation issue is something i do care more about. would be fixed when/if you expand the main navigation, but can maybe include a button somewhere

**Comment by fk** [comment]
> there's no design for prev/next links...

True, the [mockups](https://github.com/gatsbyjs/gatsby/issues/5334#issuecomment-396557749) I made for the starter showcase didn't include those. I never intended them to be understood as full wireframes of the pages in question tho, but to highlight the most significant component changes as compared to the site showcase. But I never didn't communicated that clearly :-/ …still learning, apologies again! 🙏 

I always thought prev/next navigation wouldn't be wrong for the starters either; I also assume that much less people will browse starters using them than showcased sites.

---

Regarding the "navigate back to index page" discussion, this could look like this

![image](https://user-images.githubusercontent.com/21834/43427790-79764f1e-945b-11e8-91f8-a9e218914f7c.png)

if we have enough horizontal space (icon is [MdArrowBack](http://react-icons.github.io/react-icons/md.html)), and that link could be preceiding the site/starter title like this for smaller screens:

![image](https://user-images.githubusercontent.com/21834/43428010-6867c8aa-945c-11e8-88d2-cc9db458962b.png)

(screenshot from the [site showcase mobile prototype](https://projects.invisionapp.com/share/T9H9LRCG8Z5#/screens/292717378)).

To really make that work for smaller screens, I think it's best to move the starter author name below the starter title -- we could just re-use the "Built by" bit of the site showcase detail view:

![image](https://user-images.githubusercontent.com/21834/43428152-1d0f6196-945d-11e8-877c-1c42fe4a9319.png)

Will working on consolidating site and starter showcase headers now (#6710, #6098).

**Comment by amberleyromo** [comment]
@fk @shannonbux if i'm reading all this correctly, did this all end with no pagination needed? just back to the starter showcase? if so, let's close, deferring to #6710

**Comment by shannonbux** [comment]
Yes, Amberley, closing for now. Might do this in 2.0 Starter Showcase.
