### ISSUE TITLE
update external dependencies on detail page - starter showcase

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#6716]
To improve scannability, move the icon to the end of each dependency's name 

To improve clickability, expand the selected state to incude the whole word plus icon, instead of just the icon.

**Comment by sw-yx** [comment]
> To improve clickability, expand the selected state to incude the whole word plus icon, instead of just the icon.

fwiw  the phrasing of this was a little awkward for me to parse. "the selected state" has special meaning to me, it means if the link is "selected" somehow (which also kinda doesnt make sense). better to say "expand the link to include the whole word plus icon" IMO. 

words are hard.

**Comment by shannonbux** [comment]
Thank you @sw-yx. I'm learning the lingo!
