### ISSUE TITLE
Thorough mobile feedback - starter showcase

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#6717]

**Comment by shannonbux** [comment]
Yeah, this makes me think we need different MVP's for desktop vs. mobile. I
think it's fine to just have "search sites" available for mobile for the
MVP and then phase 2 can be filters.

On Tue, Jul 31, 2018 at 12:22 PM, Florian Kissling <notifications@github.com

**Comment by fk** [comment]
Closing b/c IMO this is resolved; please reopen if I'm mistaken!
