### ISSUE TITLE
Main navigation expansion - starter showcase

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#6718]
Where to put starter showcase in main navigation (we’d have to implement the More…→ Drop down menu. Already exists in .com source code)

**Comment by fk** [comment]
Ref. #6377 and https://github.com/gatsbyjs/gatsby/issues/6377#issuecomment-404114364, https://github.com/gatsbyjs/rfcs/pull/5#issuecomment-395898919

**Comment by sw-yx** [comment]
fwiw we can link to it from the starter docs for now, it would represent no change from the status quo at all. wouldnt make this an mvp blocker imo

**Comment by shannonbux** [comment]
I think the MVP is done when it's shareable with a URL and discoverable via Google, so however we get that done is fine with me. Would both of those things be possible if it's a link on the starter page? OR have other ideas of how reach those two goals, @sw-yx?

P.S. No need to answer, just curious if you have ideas. This is @fk's realm of responsibility since it's an overall navigation thing

**Comment by sw-yx** [comment]
yep, both work just by linking to it on starter page.

i'll of course do whatever you and fk decide

**Comment by shannonbux** [comment]
ok great, that could be a first step for the MVP and then it'll be phase 2
to add starter showcase to main nav--how do you feel about that @fk?

**Comment by fk** [comment]
@shannonbux Lol at "brilliant master plan". I wish!

👍 To Shawn's suggestions and making this the req's for the MVP.

**Comment by shannonbux** [comment]
ok I'll update MVP and phase 2 to reflect this!

On Mon, Jul 30, 2018 at 11:05 AM, Florian Kissling <notifications@github.com

**Comment by shannonbux** [comment]
Closing in favor of new [EPIC] v1.0 .org redesign
