### ISSUE TITLE
[www/showcase] Add `date_added` field to existing site showcase yaml data

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#6722]
[Phase 2](https://github.com/gatsbyjs/gatsby/issues/5927) of the "Site Showcase" project forsees sorting sites "by date added". This will allow not only sorting, but also fix #6721 ("Newly added sites should be shown at the top of the unfiltered site showcase list").

This issue provides a place to discuss if there's a way to automate adding a `date_added` field to the existing sites in `sites.yml`—can we make use of `git blame` or for getting that information from https://github.com/gatsbyjs/gatsby/blame/master/docs/sites.yml and https://github.com/gatsbyjs/gatsby/blame/master/README.md, and is it worth the effort?

Ref. #6721

/cc @shannonbux @KyleAMathews @calcsam

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by KyleAMathews** [comment]
oops, nvm @fk :-D

**Comment by chiamakaikeanyi** [comment]
I think the `date_added` field should also be added to the [site showcase](https://www.gatsbyjs.org/docs/site-showcase-submissions/) page on the docs
