### ISSUE TITLE
[www/showcase] Make site detail modal responsive

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#6723]
Currently the details modal shown for window widths 750px and larger is hardcoded to that same width of 750px: https://github.com/gatsbyjs/gatsby/blob/49c52f5e78d56083a0cb45e8cd9306fcd0b92de4/www/src/components/layout.js#L74-L94

This means when reducing the window width below 750px, the modal content won't adapt to the screen width, resulting in first links to the next and previous sites to be cut off, and finally the modal content itself.

Let's fix that!

**Comment by ryanditjia** [comment]
At narrower viewport, we could place the prev and next sites _under_ the featured site. I can take this. Are we drawing the line at flexbox or can we use grid?

**Comment by fk** [comment]
We still want to do this! ✌️

**Comment by riencoertjens** [comment]
🤔hello, is this thing on? can I have a go at this? is there a design? for it?

**Comment by gillkyle** [comment]
Hey @riencoertjens! I'm not aware of any design, if you'd like to work on it feel free to make a PR perhaps implementing the suggestion above to add the next/prev links below the site. In response to @ryanditjia's question about flexbox/grid we're happy to use either or whatever makes sense!

I'll mark this as Hacktoberfest - Claimed, if you are unsure of what you've got, feel free to post a screenshot or a link to your PR or branch and someone can take a look at it too to keep all the design consistent with other elements on the site 🙂

**Comment by Italox** [comment]
@riencoertjens Are you working on this? Need some help?

**Comment by riencoertjens** [comment]
I'm sorry I got a sudden flood of work right before I wanted to tackle this... Hoping to do it this weekend

**Comment by riencoertjens** [comment]
@Italox if you want you can go ahead and do this, unfortunately I won't have time for it.

**Comment by brockduncan** [comment]
Hi, I saw this hanging out here and thought I'd take a stab at it.

**Comment by fk** [comment]
Fixed in #18956 by @brockduncan!
Thanks everybody! 🙏 

(Oh … and hey @riencoertjens :( 🙏)
