### ISSUE TITLE
[www/showcase] Bring back previous/next links for detail pages

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#6725]
We removed them because the additional images that we had to create significantly increased built time. Let's get those links back, but use the same images that we use for the previous/next links in the detail modal.

**Comment by berraknil** [comment]
@fk I don't have a reference as to what they were like before, is there an example somewhere where I can see what should it look like?

**Comment by fk** [comment]
The prev/next links for the "permalink" page were supposed to look like this -- the square images at the bottom:

<img width="1440" alt="desktop hd detail view permalink" src="https://user-images.githubusercontent.com/21834/39475805-149f33b4-4d5a-11e8-9fd7-97d534119db4.png">

Those significantly increased the initial build time for `www` though -- something that we didn't want to increase _too_ much to not put off our contributors until we figure out a better solution -- so we decided to remove this additional image size.

I think a good way to bring the prev/next navigation back for the "permalink" page is to re-use the thumbnails we generate for the modal view:

![desktop hd](https://user-images.githubusercontent.com/21834/39437788-2d77c3c8-4ca2-11e8-8cf5-d8b51c74e61a.png)

Will add a design ASAP. 🤞
