### ISSUE TITLE
[www/showcase] If URL contains a "filter" query, scroll the window to show the list of filtered sites

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#6726]
The filtered list of showcase sites for an URL containg a filter query string will be below the fold on most screens. This causes unnecessary confusion for people directly accessing a link with a filter query—they will see the list of "Featured Sites" initially.

Scrolling the screen if the URL contains a filter would enable e. g. https://next.gatsbyjs.org/showcase/?filters%5B0%5D=Education to be a nice landing page.

/cc @calcsam

**Comment by fk** [comment]
NOT STALE :P

**Comment by wardpeet** [comment]
This is fixed :) closing

**Comment by fk** [comment]
🤗 🙏
