### ISSUE TITLE
Hard and fast rule for when to create a plugin for an npm package

### ISSUE THREAD

**Issue by johncmunson** [gatsbyjs/gatsby#6731]
After skimming through the [tutorial](https://www.gatsbyjs.org/tutorial/part-two/#gatsby-plugins), it's unclear to me whether I can use npm packages within Gatsby (lodash for example) without also creating a plugin to go along with that package. If I _can_ use certain packages without needing to create a plugin to go along with it, then it is unclear to me when exactly I _do_ need to create a plugin.

Of course, I can run some simple tests when I have time for it later this week that should help clear a bit of this up, but I still think this is important to address because the existing documentation is pretty vague here.

**Comment by ryanditjia** [comment]
Generally, these npm packages don’t need a plugin:

- helpers (like `lodash` and `polished`) because they have no side effects.
- React component libraries that touch only `<div id="___gatsby">` and state/context. This is why `react-helmet` needs a plugin, because it plugs into `<head>`, while `Formik` and `react-media` work out of the box.

**Comment by LeKoArts** [comment]
It largely depends on the package and I think you can’t generalize too much. 

For example the lodash plugin exists because it also modifies the babel and webpack setup which is of course optional but possible.

**Comment by giraffesyo** [comment]
I would say one use case is when you have a package that you want to adapt to access one of the Gatsby APIs, for instance to do something at build time, then you probably want to make a plugin.

**Comment by jquense** [comment]
As a general rule:

> You can use **any** npm package you might use without gatsby, with gatsby.

This _includes_ situations where there is a similar looking plugin for gatsby. e.g. you can use `sass-loader` and Sass without using `gatsby-plugin-sass`, or Styled components without `gatsby-plugin-styled-components`.

What plugins offer is a prepackaged integration into the gatsby API's to save you time and energy., with minimal configuration. In the styled components case, you can manually render the Styled components `Provider` component near the root of your application, or just use the plugin which does it for you as well as smooth over any difficulties you might run into configuring it to work with server-side rendering.

**Comment by johncmunson** [comment]
Thanks so much everyone for all the helpful feedback! As I've been going through the docs more, I actually came across a [spot](https://www.gatsbyjs.org/docs/add-404-page/) where this question has already been addressed.

Perhaps it would be beneficial to give it slightly more visibility by mentioning and linking to it from the tutorial?

**Comment by LeKoArts** [comment]
Sure, go ahead! ☺️
