### ISSUE TITLE
[www/showcase] Improve shadow indicating overscroll

### ISSUE THREAD

**Issue by ryanditjia** [gatsbyjs/gatsby#6735]
The shadow on the right side (indicating there are more content to the right) of https://next.gatsbyjs.org/showcase is currently static and could use an improvement.

For example: the implementation of https://cssreference.io/property/align-content/ (scroll the left sidebar) is close to ideal.

**Comment by fk** [comment]
Not sure what you referring to—the white-to-transparent linear gradient of the "Featured Sites" component horizontal scroller or (which I suppose) the sidebar to the _left_ containing the filter category accordion?

<3 to have a sidebar behavior similar to cssreference.io for the site showcase filter sidebar as well as for the docs/features/tutorial sidebar!

**Comment by ryanditjia** [comment]
Tinkered with implementing how cssreference.io does it. But since it requires using React ref (to get element’s scrollTop, scrollLeft, offsetHeight, scrollHeight, etc), plus needing to add container scroll listener + window resize listener, it ended up being unmaintainable. Also it didn’t work with horizontal scrolling.

[This PR](https://github.com/gatsbyjs/gatsby/pull/6957) uses CSS-only solution taken from [here](http://lea.verou.me/2012/04/background-attachment-local/). It adds overflow shadows to the category filter accordion.

There are quirks to this solution, but they aren’t apparent when implemented here, and I think it looks good!

Will try it on Featured Sites next. Leaving this issue open for now.

**Comment by ryanditjia** [comment]
Hi @fk. With introduction of React Hooks, I decided to try to solve this once more. Once React Hooks is officially out, and Gatsby supports it (for some reason, I couldn’t make Hooks work with Gatsby).

Demo: https://gatsby-6735.netlify.com
Source: https://github.com/ryanditjia/playing-with-react-hooks

There are plenty of abstraction opportunities, but I’ll leave this here for now.

**Comment by jlengstorf** [comment]
@ryanditjia @fk a fix was found for Hooks and hot module reloading.

See https://github.com/gatsbyjs/gatsby/issues/9489#issuecomment-434868882 for details. I've updated https://github.com/jlengstorf/gatsby-with-hooks so it's working now as well.

**Comment by ryanditjia** [comment]
Thanks! I was also able to make it work by wrapping the component with React.memo.

I will send a PR once React Hooks is finalized. Hopefully by then there will be a permanent fix to this issue.
