### ISSUE TITLE
Develop works, Build fails : Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by benstr** [gatsbyjs/gatsby#674]
When running `$gatsby develop` site builds with no errors. When running `$gatsby build` I'm hit with:

```sh
Failed at generating HTML

/Users/ben/code/benstr/hackiot/fullSite/static/node_modules/gatsby/dist/bin/cli.js:42
      throw err;
      ^
Error: TypeError: Cannot read property 'data' of undefined
    at LessonDetails (render-page.js:70348:88)
    ...
```

Threw a bunch of consoles into my code since I did not know exactly where it was failing (is there a Gatsby debug flag?). All pages using `LessonDetails` component build ok. Error is triggered when the Lesson Index is being built, but all data is present and the index does not use `LessonDetails`. 

Not expecting a specific answer, just wondering how I can debug this? thx

**Comment by KyleAMathews** [comment]
Open up the `render-page.js` (found inside your `public` folder) at the specified line number to find where the problem is.

**Comment by benstr** [comment]
😹  thank you sir!
