### ISSUE TITLE
[www/showcase] Add "star" icon to "Featured" site showcase cards

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#6742]
All cards for sites that are in the "Featured" category should display a small star icon hinting that the site is "Featured": 

![image](https://user-images.githubusercontent.com/21834/43201933-3057eca6-901a-11e8-8d28-44934973061a.png)

Ideally this icon should be clickable and set the "Featured" filter.

**Comment by fk** [comment]
Just merged #6787 and working on getting the "As a user, what can/should I expect icons on cards to do" issue solved--not only the "GitHub icon opens repository" vs. "Star icon sets filter" issue, but also considering how we use icons in the "Starter Showcase" (https://dreamy-shannon-191f15.netlify.com/starter-showcase/#copy-to-clipboard) -- where we have "Copy repository URL to clipboard", "Open Starter demo", and "GitHub icon opens repository".

**Comment by fk** [comment]
I think this is a good way to highlight "Featured" sites. It also avoids mixing the "open link/set filters" functionalities for the "Site Showcase" cards. Don't have a solution to do the latter for the "Starter Showcase" icon links yet, but let's go for this for the "Site Showcase":

<img width="363" alt="bildschirmfoto 2018-07-27 um 16 19 14" src="https://user-images.githubusercontent.com/21834/43326322-d3c4ef20-91b8-11e8-8839-7bf818ca8e16.png">

Icon is in `www/src/assets/featured-sites-icons.svg`.

**Comment by berraknil** [comment]
@fk so right now there won't be any clicking on the featured sites icons, correct? They will only be decorative on top right of the image?

**Comment by fk** [comment]
Good question! I personally would make them clickable and let them set just the "Featured" filter (like the "View all Featured Sites" buttons in the "Featured Sites" section do) (honoring existing filters and just toggling the "Featured" filter would be too confusing IMO).
I'd say let's try that and see what feedback we get.

**Comment by berraknil** [comment]
Hmm OK but question, those images that the Star icon is at the top on z-index is already clickable and takes the user to the page itself, right? so there's going to be a separation with clicking on the image and the icon on top of the image?

**Comment by berraknil** [comment]
Not to mention we made the categories clickable, so one can also click on the Featured tag below and set the featured websites filter that way as well. As a reminder.

**Comment by fk** [comment]
Yep! I think that is OK for desktop, esp. if we add a hover (e.g. change the background to `colors.purple`). On mobile we could increase the click area for the "Featured" filter button without making the button/background itself bigger; for now we can just hide it there as we don't have filters on mobile working yet.

**Comment by berraknil** [comment]
OK changing the icon color on hover and just making it disappear on mobile 👍

**Comment by berraknil** [comment]
Sent a first PR, looking forward to your feedback :) 

![image](https://user-images.githubusercontent.com/6593585/43332514-50b53c48-91d1-11e8-819b-c94baea9c512.png)
