### ISSUE TITLE
[www/showcase] Add "GitHub" icon to "Open Source" site showcase cards

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#6743]
All cards for sites that are in the "Open Source" category/have a `source_url` should display a small GitHub icon hinting that the site is source is available on GitHub: 

![image](https://user-images.githubusercontent.com/21834/43202076-b17814e6-901a-11e8-9aab-d51f59c59e50.png)

Ideally this icon should be clickable and set the "Open Source" filter.

**Comment by berraknil** [comment]
@fk sent a first PR for this, right now when you click on GH icon it takes you to the source page (like we talked about on Slack) but I can change it to the way you want if using it as a filter makes more sense?

The way I saw it we already have an open source filter on the side bar and also as a category tag beneath the cards, so instead linking to the source this way seemed like a better fit? Not to mention GH icon usually signifies that you are going to github to see the relevant page/code etc,

No problem for me to change it to the way you want, just wanted to share my two cents :)

Also the icon is using the Gatsby purple now, should I change the fill to grey? Thoughts?

![image](https://user-images.githubusercontent.com/6593585/43283348-52e4a9fa-9121-11e8-82b3-a7bbe0b4313c.png)
