### ISSUE TITLE
[www/showcase] Fix showcase header position

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#6748]
When scrolling down, the showcase header should sit right below the main navigation and not be covered by it:

![image](https://user-images.githubusercontent.com/21834/43203310-27f2dd06-901e-11e8-93c5-1415b3857ed8.png)

**Comment by berraknil** [comment]
Will take a look at this

**Comment by fk** [comment]
👍 Should be easy, I think I had this fixed once, too. We have two variables here https://github.com/gatsbyjs/gatsby/blob/af799208eb210bc550caada43b5c1aa777dd82cf/www/src/utils/presets.js#L37-L38 that you can use to `calc` the `top` position for the site showcase header -- looks like `bannerHeight` is missing here: https://github.com/gatsbyjs/gatsby/blob/af799208eb210bc550caada43b5c1aa777dd82cf/www/src/views/showcase/index.js#L396-L398

**Comment by berraknil** [comment]
@fk is this the expected behavior? 

![ezgif com-optimize](https://user-images.githubusercontent.com/6593585/43206680-f81744da-902e-11e8-9dec-1cccc4e86ea3.gif)

**Comment by fk** [comment]
Yes! 🤗
