### ISSUE TITLE
bundle.js is a little too big(943kb) in my project

### ISSUE THREAD

**Issue by yefengong** [gatsbyjs/gatsby#675]
bundle.js is a little too big(943kb) in my project.
I'd like to use  `webpack.optimize.CommonsChunkPlugin`.
But I have some problem about how to config the `gatsby-node.js`,although I had read the `How to use your own webpack plugins` 
Would you please wrire a document for this?

**Comment by KyleAMathews** [comment]
Is that the size after running "gatsby build"?

**Comment by yefengong** [comment]
yes, it's the size after running "gatsby build --prefix-links"

**Comment by KyleAMathews** [comment]
Woah, how many pages do you have?

**Comment by KyleAMathews** [comment]
I don't think the commons plugin is what you want as that's useful if you
have multiple chunks and want to extract out a common set of modules.

More likely what will help us using require.ensure to lazy load heavy
modules that you might be using.

https://webpack.github.io/docs/code-splitting.html

**Comment by yefengong** [comment]
Did you use webpack 1 in gatsby.
what I want is something like 
https://webpack.js.org/guides/code-splitting-libraries/#commonschunkplugin
```
var webpack = require('webpack');
var path = require('path');

module.exports = function(env) {
    return {
        entry: {
            main: './index.js',
             vendor: ["React"],
        },
        output: {
            filename: '[chunkhash].[name].js',
            path: path.resolve(__dirname, 'dist')
        },
        plugins: [
            new webpack.optimize.CommonsChunkPlugin({
                name: 'vendor' // Specify the common bundle's name.
            })
        ]
    }
}
```
Is it will be work for me?

I found this writed by lewie9021:https://github.com/lewie9021/webpack-configurator/issues/2
```
var Webpack = require("webpack");
var WebpackConfig = require("webpack-configurator");

var config = new WebpackConfig();

config.plugin('CommonsChunkPlugin', Webpack.optimize.CommonsChunkPlugin, [{name: "vendor"}]);
```

Before I any code to `gatsby-node.js`,I just `npm install webpack --save`, and run `gatsby build --prefix-links`. Then I got a error,what's the reason?
```
exports.modifyWebpackConfig = function(config, stage) {
    return config
}
```
the file `gatsby-node.js` is just simple

**Comment by KyleAMathews** [comment]
Gatsby is using webpack 1. But again, commons chunk plugin won't do anything because gatsby 0.X doesn't do code splitting so there aren't multiple chunks to extract out a common set of modules.

Gatsby 1 will fix this and has commonschunk setup already.

Try using https://www.npmjs.com/package/source-map-explorer to see if there's any modules you can either eliminate or lazy load using require.ensure.

**Comment by yefengong** [comment]
Thank you very much! 'source-map-explorer' is a good tool.
And later I will try Gatsby 1
