### ISSUE TITLE
[gatsby-plugin-sharp] correctly infer width when passing only target height

### ISSUE THREAD

**Issue by danielberndt** [gatsbyjs/gatsby#6752]
If I do 

```graphql
        file(relativePath: {eq: "img"}) {
          childImageSharp {
            fixed(width: 50) {
              ...GatsbyImageSharpFixed
            }
          }
        }
```

it's behaving as expected. The resulting image's height get automatically set according to the aspect ratio.

If on the other hand I want to fix the height:

```graphql
        file(relativePath: {eq: "img"}) {
          childImageSharp {
            fixed(height: 50) {
              ...GatsbyImageSharpFixed
            }
          }
        }
```

unexpected things happen. The width is not inferred by the aspect ratio. Instead it is set to 400 because it's set as a default [here](https://github.com/gatsbyjs/gatsby/blob/af799208eb210bc550caada43b5c1aa777dd82cf/packages/gatsby-plugin-sharp/src/index.js#L65).

For a more consistent behaviour It would be really nice to only use the fallback width of 400 if no height and no width has been set.

**Comment by KyleAMathews** [comment]
Just checking that you're on the latest version of all your plugins? I remember this being an issue but also getting fixed.

**Comment by danielberndt** [comment]
Ah sorry, I should have mentioned: I started a new project today and installed the `@next`version of all plugins:
```
"gatsby": "2.0.0-beta.59",
"gatsby-image": "^2.0.0-beta.7",
"gatsby-plugin-sharp": "^2.0.0-beta.7",
"gatsby-source-filesystem": "^2.0.1-beta.10",
"gatsby-transformer-sharp": "^2.1.1-beta.6",
```
