### ISSUE TITLE
Add a snapshot-and-reset option to the CLI

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#6755]
When things go weird with Gatsby, it's often required to delete the cache and start with a clean slate: `rm -rf node_modules .cache public && yarn && yarn develop`

It's been requested to add a feature to clear the cache to the CLI, but there's been resistance to this because we're unable to fix the cache if issues never get reported.

In a discussion with @calcsam, @pieh, and @KyleAMathews, @pieh suggested a "reset, but with a snapshot sent to the OSS team" option.

This solves two problems:

1. Developers aren't blocked by a bad cache
2. The maintainers receive information that helps fix cache issues

## How it could work:

For now, I'm (semi-seriously) calling this command `gatsby nuke`. It does the following:

- takes an anonymous snapshot of the dev environment
- asks an optional question, e.g. “What happened that made a nuke necessary?”
- sends anonymized data to a public log for maintainers to review
- deletes `.cache`, `public`, `node_modules`
- runs `yarn` or `npm install`

## Questions to answer:

1. What details should be included in the snapshot?
    - `envinfo`
    - ...what else?
2. How is the snapshot structured?
3. How do we anonymize data?
    - This will depend on what data we need to include.
4. Where are snapshots logged?
5. What should the command be called?
    - `gatsby nuke`
    - `gatsby clean`
    - `gatsby cache-reset`
    - ...something else?
6. What optional question(s) are most helpful to maintainers?
    - What happened that made nuking the cache necessary?

**Comment by jlengstorf** [comment]
cc @DSchau — is this what your `gatsby clean` work solves? If so, feel free to close this one.

**Comment by DSchau** [comment]
@jlengstorf sure is! I should take another look at that PR and iron out some issues that @pieh identified!

I'll just leave this open so that we can close it out with #9126!
