### ISSUE TITLE
[v2] Investigate why gatsby-browser.js isn't loaded in production without a stub function

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#6759]
This issue was split off of #5997 to track a separate bug.

Here is the relevant conversation:

@mquandalle:
> I spent a lot of time trying to solve this apparently simple issue and I didn't think of gatsby-browser.js, happy to find there is such a simple solution! But you're right that this definitely needs to be documented.
> 
> So apparently adding the import line isn't enough for the file to be executed in the browser (and the style to be loaded) and we need to add a stub like exports.onClientEntry = () => {};. If the goal is to have gatsby-browser.js be a main.js for the client maybe this behavior should be changed?

@KyleAMathews:
> Oh... hmm that's odd. I'll look into this soon-ish then.

@KyleAMathews:
> Also welcome anyone else who wants to investigate why gatsby-browser.js isn't loading css

@chasemccoy:
> @KyleAMathews I am also being affected by this. My fonts are loading many times and flashing on load in production.
> 
> @mquandalle did you find a way to get this to work in gatsby-browser.js? You mentioned a stub.

@chasemccoy:
> @mquandalle Actually, I was just able to get this to work. Putting this (and only this) in gatsby-browser.js worked for me and loaded all of the appropriate packages and files:
> 
> require("./src/styles/index.scss");
> require("./src/fonts/fonts.css");
> require("svgxuse");
> Edit: This worked on dev, but not in production...
> 
> Edit 2: Ah yes, I understand now. The shim (exports.onClientEntry = () => {};) is required for this to work introduction. Works fine in dev without the shim.

@ahlusar1989:
> @KyleAMathews Would you still like someone to look into why gatsby-browser.js isn't loading css (production)?

@KyleAMathews:
> That'd be great!

**Comment by tryzniak** [comment]
I'm 99% sure that this causes the bug:
https://github.com/gatsbyjs/gatsby/blob/001158ebe5725eed045fd8439c05e8abbc5916e7/packages/gatsby/src/bootstrap/load-plugins/validate.js#L115-L123

**Comment by tryzniak** [comment]
Thank you! I’ll be investigating further

**Comment by m-allanson** [comment]
@tryzniak 💪 💜 😄 

You may have seen these already, but if not, they might be useful:

- [How to setup a local Gatsby dev environment](https://next.gatsbyjs.org/docs/how-to-contribute/#contributing-to-the-repo)
- [Guide to debugging the build process](https://next.gatsbyjs.org/docs/debugging-the-build-process/)

**Comment by tryzniak** [comment]
Ok, I've got a solution for this! Your tips were super helpful. We'll send a PR soon.
