### ISSUE TITLE
[v2] ES6 import/export syntax appears to be working in development, but not production

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#6761]
This issue was split off from #5997 to track a separate issue.

Here's the relevant conversation from that thread:

@kmcaloon:
> Two things. First, standard css imports seem to be working fine for me in gatsby-browser.js. The following is showing up correctly for me on the frontend in development:
> 
> import styles from './src/global.scss';
> 
> However, I think there may be some issues with gatsby-browser.js in production other than strictly not loading css. For instance, my provider is working in development but not production. My build is failing and notifying me that my 'AppState' is not provided by a provider:
> 
> export const replaceRouterComponent = ( { history } ) => {
> 
>   return ( { children } ) => (
> 
>     <Provider AppState={ AppState }>
>       <Router history={ history }>{ children }</Router>
>     </Provider>
> 
>   );
> 
> };
> I might open a separate issue for this specifically, but it might help narrow down the problem here.

@KyleAMathews: 
> @kmcaloon the problem with the later is we don't support es6 import/export for APIs — a restriction which we can/should release. I'm not sure if there's an issue for that but it's a reasonable restriction to fix. Use exports.replaceRouterComponent for now to get that working.

@kmcaloon:
> @KyleAMathews. Thanks, I think what confused me was this #4452 and the fact that it is working in development and not production?

@KyleAMathews:
> Oh hmmm I didn't think we'd got that working. Did we @m-allanson @pieh?

@kmcaloon
> @KyleAMathews, since es6 imports are not supposed to be supported by the APIs, then do you know why most examples around are using them?
> 
> Eg.
> #2940
> #1886
> 
> I'll also try to dig up some other examples I've seen in some repos

**Comment by m-allanson** [comment]
@Chuloo and I went through this on a call and it seems to work with the latest Gatsby beta. Either that or we've misunderstood the issue 😅

The issue as we understand it is:

> When using ES6 `import` / `export` syntax in `gatsby-browser.js`, any exported Gatsby APIs (such as `onClientEntry`) will silently be ignored in production. They will work correctly during development.

Here's a small demo project you can use if anyone would like to investigate further: https://github.com/m-allanson/gatsby-issue-6761. Check the API exported in [`gatsby-browser.js`](https://github.com/m-allanson/gatsby-issue-6761/blob/master/gatsby-browser.js), and confirm that "CLIENT EXPORT" is logged to the browser console:

- after running `gatsby develop` and browsing to http://localhost:8000 
- after running `gatsby build` then `gatsby serve` and browsing to http://localhost:9000

**Comment by kkemple** [comment]
closing since this appears to be resolved
