### ISSUE TITLE
Overriding slugs

### ISSUE THREAD

**Issue by zslabs** [gatsbyjs/gatsby#6764]
👋

I'm starting my first project with Gatsby and have run into an issue with querying data that "may" not always exist. Here is my `gatsby-node.js` file:

    const path = require('path');
    const _ = require('lodash');

    // Lifecycle methods

    function attachFieldsToBlogPost({ node, actions }) {
      if (node.internal.type !== 'MarkdownRemark') {
        return;
      }

      const { createNodeField } = actions;

      const { slug, title } = node.frontmatter;
      const postPath = slug || _.kebabCase(title);

      createNodeField({
        node,
        name: 'slug',
        getter: node => node.frontmatter.slug, // eslint-disable-line no-shadow
        value: postPath,
      });

      createNodeField({
        node,
        name: 'url',
        value: postPath,
      });
    }

    exports.onCreateNode = function() { // eslint-disable-line func-names
      return Promise.all([attachFieldsToBlogPost].map(fn => fn.apply(this, arguments))); // eslint-disable-line prefer-rest-params
    };

    // Implementations

    function getMarkdownQuery({ regex } = {}) {
      return `
        {
          allMarkdownRemark(
            sort: { fields: [frontmatter___date], order: DESC }
            filter: { fileAbsolutePath: { regex: "${regex}" } }
          ) {
            totalCount
            edges {
              node {
                fileAbsolutePath
                excerpt(pruneLength: 280)
                timeToRead
                frontmatter {
                  title
                  date
                  slug
                }
                fields {
                  url
                  slug
                }
              }
            }
          }
        }
      `;
    }

    function createBlogPostPages({ edges, createPage }) {
      const component = path.resolve('src/templates/Post.js');

      edges.forEach(({ node }) => {
        const { slug, title } = node.frontmatter;
        const postPath = slug || _.kebabCase(title);

        createPage({
          path: postPath,
          component,
          context: {
            slug: postPath,
          },
        });
      });
    }

    exports.createPages = async({ actions, graphql }) => {
      const results = await Promise.all([
        graphql(getMarkdownQuery({ regex: '/src/posts/' })),
      ]);

      const error = results.filter(r => r.errors);
      if (error.length) {
        return Promise.reject(error[0].errors);
      }

      const [blogPostResults] = results;

      const { createPage } = actions;
      const blogPostEdges = blogPostResults.data.allMarkdownRemark.edges;

      createBlogPostPages({
        createPage,
        edges: blogPostEdges,
      });
    };

And my example blog post content is:

    ---
    title: 'Hello world there'
    date: '2018-08-25'
    ---

    Here is some content.

    ```javascript
    console.log('test')
    ```

When I supply a `slug` frontmatter component, the page is created as intended. But, I'd only like to use the `slug` parameter when it's available (hence the check to see if the frontmatter is available in both `attachFieldsToBlogPost` and `createBlogPostPages`). If I remove the `slug` frontmatter item, I get the following error:

`GraphQLError: Cannot query field "slug" on type "frontmatter".`

Is there a way to override the path used to create the post pages "if" the `slug` frontmatter is there?

Hopefully this isn't too vague as it's my first Gatsby project, but seems like a pretty useful feature. Thanks!

**I've noticed that if I add another blog post that does have that slug attribute, everything works fine. Which seems like it would mean that if I'm going to query by something in graphql, it needs to exist... somewhere. Would really love to either provide a default or allow a nullable field.**

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by zslabs** [comment]
@KyleAMathews It's actually a great idea to close these out, as it reminded me to post my solution :)

For anyone else that comes across this, I ended up creating a BLUEPRINT file that has all of the fields that "could" be there in case there are no slug overrides, and then just ignored it in my main query; which magically gets around the issue.

```
filter: {
  frontmatter: { title: { ne: "BLUEPRINT" } }
}
```
