### ISSUE TITLE
Add sites to site showcase

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#6767]
@calcsam found these awesome sites, and someone could add these to the sites.yml file here: https://github.com/gatsbyjs/gatsby/blob/master/docs/sites.yml. You'd have to decide what categories apply to the sites so they can be found by filters. And generally just trying to fill out all possible fields for each site you add to the .yml file is helpful! 

support.hackerone.com/
https://partners.patreon.com/
https://beta.bom.gov.au/
https://curbside.com/
https://mux.com/
swapcard.com/
auth.kalixhealth.com/
https://join.hubba.com/
blog.particle.io/
https://airbnb.io/
https://hyperplay.leagueoflegends.com/
bad.creditloan.com/
https://fcfcu.com/
https://open.fda.gov/
http://oira.ua.edu/
https://gm.capitalone.com/
https://housemanager.calstate.aaa.com/
https://us.trintellix.com/
premium.telegraph.co.uk/

**Comment by elrumordelaluz** [comment]
I can start documenting those and other _blazing fast_ websites I know built with `gatsby`.

**Comment by elrumordelaluz** [comment]
https://blog.particle.io/ doesn't seems build in `gatsby`

**Comment by m-allanson** [comment]
> https://blog.particle.io/ doesn't seems build in gatsby

Hmm you're right, let's skip that one. Good catch!

**Comment by m-allanson** [comment]
Also the _is Gatsby?_ browser plugin (by @tsriram 👋) is great for checking these :) https://www.gatsbyjs.org/docs/awesome-gatsby/#tools

**Comment by elrumordelaluz** [comment]
Seems cool that _browser plugin_, will check it out definitely, thanks!

**Comment by tsriram** [comment]
@m-allanson Glad that the plugin is helpful! Just checked that it's got 50 users :)
