### ISSUE TITLE
Route structure breaks React Router's ‘activeClassName’ Link behavior on nested routes

### ISSUE THREAD

**Issue by JLongley** [gatsbyjs/gatsby#677]
I created a simple page with a navigation at the top as follows:

```jsx
export default class Header extends React.Component {
  render () {
    return (
      <header>
        <div className="header">
          <Link to='/'><h1>Jimmy Longley</h1></Link>
          <nav role="navigation" className="clearfix">
            <ul>
              <NavLink onlyActiveOnIndex={true} to='/'><li>About</li></NavLink>
              <NavLink to='/blog/'><li>Blog</li></NavLink>
              <NavLink to='/resume/'><li>Resume</li></NavLink>
              <a href="#contact"><li>Contact</li></a>
            </ul>
          </nav>
        </div>
      </header>
    )
  }
}
```

Where NavLink is a simple react component based on the react-router tutorial

```jsx
export default React.createClass({
  render() {
    return <Link {...this.props} activeClassName="active"/>
  }
})
```

I want my header items to be highlighted when I am in a sub route, e.g. 

`/blog/post1/`

However, the ‘blog’ tab of my header will not get the active class due to this issue
https://github.com/ReactTraining/react-router/blob/master/docs/Troubleshooting.md#parent-path-does-not-show-as-active

The proposed solution is to reconfigure how the routes are set up, but this isn’t an option when gatsby is doing it for you automatically.  After digging through the code, I found `create-routes.js `, which has the following comment:

```js
// Algorithm
  // 1. Find all templates.
  // 2. Create routes for each template russian-doll style.
  // 3. For each index file paired with a template, create a default route
  // 4. Create normal routes for each remaining file under the appropriate
  // template
```

So, I created an empty _template.js file at /blog/_template.js and it resolved the issue

```jsx
module.exports = React.createClass({
  render() {
    return false;
  }
});
```

This seems rather unnecessary.  Would it be possible to change the routing algorithm to create nested routes based on the file path, regardless of the presence of a template?  Also, I believe the behavior of `_template.jsx` could be better documented.  Thanks for everything, this project is awesome!

**Comment by KyleAMathews** [comment]
Hey — I'd love it if you'd like to add a PR documenting edge cases like this + the template system in general. I'd never see this technique used before!

The current template system isn't ideal in a number of ways. My focus is on 1.0 which revamps among other things how the layout system works to make it less magical and more programmatic. See this writeup https://github.com/gatsbyjs/gatsby/issues/421

Changing the routing algorithm at this point for 0.x would be a big breaking change so not under consideration.

**Comment by timarney** [comment]
Just noting this here

http://reactfaq.site/components/ (this route picks up the active class)
http://reactfaq.site/components/lifecycle-methods/ (this nested route doesn't)

The pages are all markdown files - https://github.com/timarney/react-faq/tree/master/pages

Happy to use this as a use case (1.0 release).
