### ISSUE TITLE
Development proxy throws unhandled exceptions

### ISSUE THREAD

**Issue by Bouncey** [gatsbyjs/gatsby#6771]
## Description

Development proxy request errors cause `gatsby` to crash due to an unhandled exception.

It would be nice to keep the `gatsby develop` process alive to test site failover

### Steps to reproduce

Any `gatsby` site with with a development proxy provided in `gatsby-config.js`.

If the proxy url provided is set to fail (proxy server not running, invalid url), `gatsby develop` will crash when a request is made to the proxy.

### Expected result

Exceptions should be handled and reported to the developer. `gatsby develop` process remains alive.

### Actual result
`gatsby develop` process exits on an unhandled exception. 

### Environment
`gatsby info --clipboard` not available in v1?

### File contents (if changed)

Shouldn't be required

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A 

### Notes

I have tried wrapping `req.pipe(request(proxiedUrl)).pipe(res)` in a `try...catch`, but the error slips through.

**Comment by kakadiadarpan** [comment]
@Bouncey can you try upgrading gatsby and dependencies to their latest stable versions? We released version 2 recently, that might solve the issue for you.

(Let us know if it doesn't)
