### ISSUE TITLE
How to properly update a mid-tree node in custom gatsby-source-plugin

### ISSUE THREAD

**Issue by datakurre** [gatsbyjs/gatsby#6781]
On subsequent `gatsby build`, how should I properly update a mid-tree node data in a custom source plugin?

I was surprised to learn that `createNode` deletes recursively all children linked to the previous version of the linked node https://github.com/gatsbyjs/gatsby/blob/e5737cf904798bebc262980c8f78076228fa45ae/packages/gatsby/src/redux/actions.js#L601-L608

So, does updating data for a node with children, really require also to update all its children?

If so, is it safe to hack around this by clearing children array of the existing node before updating the node with `createNode`?

**Context**

I'm trying to optimize our Gatsby source plugin to properly update data on subsequent builds so that only changed data is fetched from the backend (setPluginStatus to set lastFetched timestamp and then touchNode to touch unchanged nodes and createNode to add and update nodes). The source plugin is for CMS, usually with deep hierarchical content structures.

**Version**

`"gatsby": "^2.0.0-beta.59"`

**Comment by KyleAMathews** [comment]
Wrote a response over here: https://github.com/collective/gatsby-source-plone/issues/136#issuecomment-408261772

Basically, I'm guessing you _shouldn't_ be using parent/child relationships for your nodes. Which is confusing I know :-\

**Comment by datakurre** [comment]
@KyleAMathews Thanks. That explained the behavior.
