### ISSUE TITLE
[perilbot] Add labels to issues automatically

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#6782]
Thanks to @m-allanson's excellent definition of when and how to label issues, we can use Peril to automatically apply labels to issues. See 

This needs additional thinking through, but we ought to be able to handle a decent chunk of new issues automatically and fall back to a `status: needs manual review` label if Peril can't figure out how to label it.

**Comment by piotrkwiecinski** [comment]
There is a https://github.com/Moya/moya-peril/blob/master/org/labeler.ts I could give it a shot on the weekend.

Would that be a decent starting point?

**Comment by jlengstorf** [comment]
Hey, @piotrkwiecinski!

I think that's definitely a good starting point. I think our near-term goal is to update the [issue templates](https://github.com/gatsbyjs/gatsby/tree/master/.github/ISSUE_TEMPLATE) to be as simple as possible, but parseable by Peril. (See https://github.com/gatsbyjs/gatsby/issues/6783)

If you set up the labeler to run, that puts us in a great position to start thinking through what those updated templates look like and how we can make the labels as useful as possible.

Let me know if you have any questions on getting started. Our Peril setup is here: https://github.com/gatsbyjs/peril-gatsbyjs — I believe the only way to test is with actual test files, so let me know if you need a hand getting some webhook payloads for testing.

Thanks!

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
