### ISSUE TITLE
[perilbot] Close stale issues

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#6785]
After 20 days, Peril should post a follow-up message.

If no response after another 10 days, Peril should close the issue.

**Comment by m-allanson** [comment]
@marisamorby's decision flowchart from #8415: https://whimsical.co/5bsueDnUNG2K7qQDZKYTGQ

**Comment by marisamorby** [comment]
@jlengstorf: Closing this issue since perilbot is running for stale issues.
