### ISSUE TITLE
Is gatsbyjs.org open source?

### ISSUE THREAD

**Issue by JanoshRiebesell** [gatsbyjs/gatsby#6786]
Is there any way to take a look at the source of [gatsbyjs.org](https://next.gatsbyjs.org)? Seems to me like it would be a great resource from which to learn best practices and see what's possible.

**Comment by piotrkwiecinski** [comment]
Entire website is here https://github.com/gatsbyjs/gatsby/tree/master/www

**Comment by KyleAMathews** [comment]
Yup! Learn away :-)

**Comment by JanoshRiebesell** [comment]
Ah, thanks a lot. I was burrowing through the repo but apparently in all the wrong places. I even searched for `gatsby-config.js`, `gatsby-node.js`, etc. which oddly enough didn't bring anything up.
