### ISSUE TITLE
Gatsby + Drupal 8 - gatsby-config.js

### ISSUE THREAD

**Issue by dougouverson** [gatsbyjs/gatsby#6789]
## Description

Getting json data from Drupal 8 website.

### Steps to reproduce

Created Gatsby site on local machine using https://github.com/gatsbyjs/gatsby-starter-blog

Spun a Drupal 8 website at mastview.com.

Installed jsonapi and jsonapi_extras modules. Made sure that permissions were set so that json was avaiable at http://mastview.com/jsonapi

Configured gatsby-config.js per https://www.gatsbyjs.org/packages/gatsby-source-drupal/

Ran `gatsby develop`

Errors: https://www.screencast.com/t/pfprK09a

> $ gatsby develop                                                                          ⬡ 8.11.3
success delete html and css files from previous builds — 0.008 s
success open and validate gatsby-config.js — 0.004 s
success copy gatsby files — 0.016 s
success onPreBootstrap — 0.376 s
⠁ Starting to fetch data from Drupal
error Plugin gatsby-source-drupal returned an error

  Error: Request failed with status code 404

  - createError.js:16 createError
    [gatsby-blog]/[axios]/lib/core/createError.js:16:15

  - settle.js:18 settle
    [gatsby-blog]/[axios]/lib/core/settle.js:18:12

  - http.js:191 IncomingMessage.handleStreamEnd
    [gatsby-blog]/[axios]/lib/adapters/http.js:191:11

  - next_tick.js:138 _combinedTickCallback
    internal/process/next_tick.js:138:11

  - next_tick.js:180 process._tickCallback
    internal/process/next_tick.js:180:9

⠐ source and transform nodes

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    npm: 6.2.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 61.0.1
    Safari: 11.1.2
  npmPackages:
    gatsby: ^1.9.250 => 1.9.250
    gatsby-link: ^1.6.39 => 1.6.40
    gatsby-plugin-feed: ^1.3.20 => 1.3.20
    gatsby-plugin-google-analytics: ^1.0.29 => 1.0.29
    gatsby-plugin-offline: ^1.0.15 => 1.0.15
    gatsby-plugin-react-helmet: ^1.0.8 => 1.0.8
    gatsby-plugin-sharp: ^1.6.42 => 1.6.42
    gatsby-plugin-typography: ^1.7.18 => 1.7.18
    gatsby-remark-copy-linked-files: ^1.5.31 => 1.5.31
    gatsby-remark-images: ^1.5.61 => 1.5.61
    gatsby-remark-prismjs: ^1.2.24 => 1.2.24
    gatsby-remark-responsive-iframe: ^1.4.18 => 1.4.18
    gatsby-remark-smartypants: ^1.4.12 => 1.4.12
    gatsby-source-drupal: ^2.0.41 => 2.0.41
    gatsby-source-filesystem: ^1.5.31 => 1.5.31
    gatsby-transformer-remark: ^1.7.40 => 1.7.40
    gatsby-transformer-sharp: ^1.6.22 => 1.6.22
  npmGlobalPackages:
    gatsby-cli: 1.1.58

### File contents (if changed)

`gatsby-config.js`:

{
  "name": "gatsby-starter-blog",
  "description": "Starter Gatsby Blog",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby-starter-blog/issues"
  },
  "dependencies": {
    "gatsby": "^1.9.250",
    "gatsby-link": "^1.6.39",
    "gatsby-plugin-feed": "^1.3.20",
    "gatsby-plugin-google-analytics": "^1.0.29",
    "gatsby-plugin-offline": "^1.0.15",
    "gatsby-plugin-react-helmet": "^1.0.8",
    "gatsby-plugin-sharp": "^1.6.42",
    "gatsby-plugin-typography": "^1.7.18",
    "gatsby-remark-copy-linked-files": "^1.5.31",
    "gatsby-remark-images": "^1.5.61",
    "gatsby-remark-prismjs": "^1.2.24",
    "gatsby-remark-responsive-iframe": "^1.4.18",
    "gatsby-remark-smartypants": "^1.4.12",
    "gatsby-source-drupal": "^2.0.41",
    "gatsby-source-filesystem": "^1.5.31",
    "gatsby-transformer-remark": "^1.7.40",
    "gatsby-transformer-sharp": "^1.6.22",
    "lodash": "^4.17.5",
    "typeface-merriweather": "0.0.43",
    "typeface-montserrat": "0.0.43",
    "typography-theme-wordpress-2016": "^0.15.10"
  },
  "devDependencies": {
    "eslint": "^4.19.1",
    "eslint-plugin-react": "^7.7.0",
    "gh-pages": "^1.1.0",
    "prettier": "^1.12.0"
  },
  "homepage": "https://github.com/gatsbyjs/gatsby-starter-blog#readme",
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "main": "n/a",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/gatsbyjs/gatsby-starter-blog.git"
  },
  "scripts": {
    "dev": "gatsby develop",
    "lint": "./node_modules/.bin/eslint --ext .js,.jsx --ignore-pattern public .",
    "test": "echo \"Error: no test specified\" && exit 1",
    "format": "prettier --trailing-comma es5 --no-semi --single-quote --write 'src/**/*.js' 'src/**/*.md'",
    "develop": "gatsby develop",
    "build": "gatsby build",
    "deploy": "gatsby build --prefix-paths && gh-pages -d public",
    "fix-semi": "eslint --quiet --ignore-pattern node_modules --ignore-pattern public --parser babel-eslint --no-eslintrc --rule '{\"semi\": [2, \"never\"], \"no-extra-semi\": [2]}' --fix gatsby-node.js"
  }
}

`package.json`:

{
  "name": "gatsby-starter-blog",
  "description": "Starter Gatsby Blog",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby-starter-blog/issues"
  },
  "dependencies": {
    "gatsby": "^1.9.250",
    "gatsby-link": "^1.6.39",
    "gatsby-plugin-feed": "^1.3.20",
    "gatsby-plugin-google-analytics": "^1.0.29",
    "gatsby-plugin-offline": "^1.0.15",
    "gatsby-plugin-react-helmet": "^1.0.8",
    "gatsby-plugin-sharp": "^1.6.42",
    "gatsby-plugin-typography": "^1.7.18",
    "gatsby-remark-copy-linked-files": "^1.5.31",
    "gatsby-remark-images": "^1.5.61",
    "gatsby-remark-prismjs": "^1.2.24",
    "gatsby-remark-responsive-iframe": "^1.4.18",
    "gatsby-remark-smartypants": "^1.4.12",
    "gatsby-source-drupal": "^2.0.41",
    "gatsby-source-filesystem": "^1.5.31",
    "gatsby-transformer-remark": "^1.7.40",
    "gatsby-transformer-sharp": "^1.6.22",
    "lodash": "^4.17.5",
    "typeface-merriweather": "0.0.43",
    "typeface-montserrat": "0.0.43",
    "typography-theme-wordpress-2016": "^0.15.10"
  },
  "devDependencies": {
    "eslint": "^4.19.1",
    "eslint-plugin-react": "^7.7.0",
    "gh-pages": "^1.1.0",
    "prettier": "^1.12.0"
  },
  "homepage": "https://github.com/gatsbyjs/gatsby-starter-blog#readme",
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "main": "n/a",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/gatsbyjs/gatsby-starter-blog.git"
  },
  "scripts": {
    "dev": "gatsby develop",
    "lint": "./node_modules/.bin/eslint --ext .js,.jsx --ignore-pattern public .",
    "test": "echo \"Error: no test specified\" && exit 1",
    "format": "prettier --trailing-comma es5 --no-semi --single-quote --write 'src/**/*.js' 'src/**/*.md'",
    "develop": "gatsby develop",
    "build": "gatsby build",
    "deploy": "gatsby build --prefix-paths && gh-pages -d public",
    "fix-semi": "eslint --quiet --ignore-pattern node_modules --ignore-pattern public --parser babel-eslint --no-eslintrc --rule '{\"semi\": [2, \"never\"], \"no-extra-semi\": [2]}' --fix gatsby-node.js"
  }
}

`gatsby-node.js`:

const _ = require('lodash')
const Promise = require('bluebird')
const path = require('path')
const { createFilePath } = require('gatsby-source-filesystem')

exports.createPages = ({ graphql, boundActionCreators }) => {
  const { createPage } = boundActionCreators

  return new Promise((resolve, reject) => {
    const blogPost = path.resolve('./src/templates/blog-post.js')
    resolve(
      graphql(
        `
          {
            allMarkdownRemark(sort: { fields: [frontmatter___date], order: DESC }, limit: 1000) {
              edges {
                node {
                  fields {
                    slug
                  }
                  frontmatter {
                    title
                  }
                }
              }
            }
          }
        `
      ).then(result => {
        if (result.errors) {
          console.log(result.errors)
          reject(result.errors)
        }

        // Create blog posts pages.
        const posts = result.data.allMarkdownRemark.edges;

        _.each(posts, (post, index) => {
          const previous = index === posts.length - 1 ? null : posts[index + 1].node;
          const next = index === 0 ? null : posts[index - 1].node;

          createPage({
            path: post.node.fields.slug,
            component: blogPost,
            context: {
              slug: post.node.fields.slug,
              previous,
              next,
            },
          })
        })
      })
    )
  })
}

exports.onCreateNode = ({ node, boundActionCreators, getNode }) => {
  const { createNodeField } = boundActionCreators

  if (node.internal.type === `MarkdownRemark`) {
    const value = createFilePath({ node, getNode })
    createNodeField({
      name: `slug`,
      node,
      value,
    })
  }
}

`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by KyleAMathews** [comment]
A 404 suggests a problem with the Gatsby site or how you've configured the plugin.

**Comment by KyleAMathews** [comment]
Err Drupal site 🙈

**Comment by dougouverson** [comment]
I followed the instructions (there weren't many). Does this look right: http://mastview.com/jsonapi

**Comment by nmacd85** [comment]
Can you post the gatsby-config.js? Looks like you pasted the package.json twice instead. It should look something like below:

module.exports = {
  siteMetadata: {
    title: 'Gatsby Starter Blog',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    {
      resolve: 'gatsby-source-drupal',
      options: {
        baseUrl: 'http://mastview.com/',
        apiBase: 'jsonapi', // endpoint of Drupal server
      },
    },
 ],
}

**Comment by dougouverson** [comment]
module.exports = {
  siteMetadata: {
    title: 'Gatsby Default Starter',
  },
  plugins: ['gatsby-plugin-react-helmet'],
}

plugins: [
  {
    resolve: `gatsby-source-drupal`,
    options: {
      baseUrl: `http://mastview.com/`,
      apiBase: `jsonapi`, // optional, defaults to `jsonapi`
    },
  },
];

**Comment by nmacd85** [comment]
In your version the module.exports doesn’t enclose the 2nd plugin listing so that would be wy]hy no data is there, it’s not included in the export


module.exports = {
siteMetadata: {
title: 'Gatsby Default Starter',
},
plugins: ['gatsby-plugin-react-helmet'],
plugins: [
{
resolve: gatsby-source-drupal,
options: {
baseUrl: http://mastview.com/,
apiBase: jsonapi,
}
}
]
};

This may still cause an issue with plugin being defined twice though. Possibly replace all back ticks with single quotes?

**Comment by nmacd85** [comment]
this works for my site which I also have jsonapi and jsonapi_extras enabled. Feel free tp test with this or replace the site with yours

`module.exports = {
  siteMetadata: {
    title: 'Gatsby Default Starter',
  },
  plugins: ['gatsby-plugin-react-helmet',
    {
      resolve: 'gatsby-source-drupal',
      options: {
        baseUrl: 'http://nicoledawn.design/',
        apiBase: 'jsonapi', // endpoint of Drupal server
      },
    },
  ],
}
`

**Comment by dougouverson** [comment]
I was able to "fetch data from Drupal" 'http://nicoledawn.design/'.

When I change baseUrl to http://mastview.com/ I get the errors.

So, the issue is with my Drupal site. I followed instructions, opened permissions, etc. And http://mastview.com/jsonapi looks to be correct.

Any idea what may be wrong with the Drupal site? What should I be looking for? How can I diagnose?

**Comment by dougouverson** [comment]
I added 3 more nodes, enabled (and updated) JSON API Extras, and now it works.

Versions of modules: https://www.screencast.com/t/G6yjojmG9MWn

**Comment by nmacd85** [comment]
Oh good! I had that installed also, but I was trying different things before trying gatsby so it was enabled beforehand.

**Comment by Chuloo** [comment]
This issue is being closed because it seems the problem has been solved! 😄  
Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem 👍
