### ISSUE TITLE
Can't change favicon

### ISSUE THREAD

**Issue by Vaestro** [gatsbyjs/gatsby#679]
I want to change the favicon to a logo I am using for my website. I have this code in the head tag in my html.js file:

```
<head>
   <meta charSet="utf-8"/>
   <meta httpEquiv="X-UA-Compatible" content="IE=edge"/>
   <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css"/>
   <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"/>
   <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"/>
   <link href="https://fonts.googleapis.com/css?family=Libre+Franklin" rel="stylesheet"/>

   <link rel="logo" href="favicon.ico" type="image/x-icon" />
   {head.title.toComponent()}
   {head.meta.toComponent()}
   <TypographyStyle typography={typography}/>
   <GoogleFont typography={typography}/> {css}
</head>
```

with this line to change the favicon:

```
 <link rel="logo" href="favicon.ico" type="image/x-icon" />

```

But regardless of what path I use, I am unable to change the favicon. How can I change the favicon or where is the default beer logo favicon being set?

**Comment by KyleAMathews** [comment]
Which starter are you using?

**Comment by Vaestro** [comment]
The default starter. And thanks for the prompt response!

**Comment by KyleAMathews** [comment]
It doesn't have a default favicon. Browsers cache icons so the beer one
most be from another site of yours.

To change it, just import the actual icon you want and pass it into the
href prop.

**Comment by Vaestro** [comment]
I cleared the cache and it still has the same icon and I even checked on another internet browser. And yes that's what I did since there was no code to import a favicon before in the html.js file, I added it. Sorry if I'm just missing something painfully obvious here!

**Comment by Necmttn** [comment]
![image](https://cloud.githubusercontent.com/assets/5212808/23103147/176288dc-f6f1-11e6-88cd-cd68d51dce06.png)
Try to drop all the data from your caches..

**Comment by kristojorg** [comment]
@Vaestro I don't believe you can add use `rel="logo"`. It should be `rel="icon"` to indicate that this icon represents the site. You can see valid property values [here](https://www.w3schools.com/tags/att_link_rel.asp)

**Comment by pedromartinez11** [comment]
Is it OK to fix like this fix in `html.js` ?
```
import favicon from './favicon.png';
<link rel="shortcut icon" type="image/png" href={favicon} />
```

**Comment by KyleAMathews** [comment]
Yup! That's exactly what the html.js file is for.

**Comment by ooloth** [comment]
This is working well for me, except for the browserconfig.xml file generated by ...

Here's what I've added to html.js:

```js

import faviconApple from './static/favicons/apple-touch-icon.png'
import favicon32 from './static/favicons/favicon-32x32.png'
import favicon16 from './static/favicons/favicon-16x16.png'
import manifest from './static/favicons/manifest.json'
import safariPinned from './static/favicons/safari-pinned-tab.svg'
import faviconICO from './static/favicons/favicon.ico'
import browserConfig from './static/favicons/browserconfig.xml'

...

<link rel="apple-touch-icon" sizes="180x180" href={faviconApple} />
<link rel="icon" type="image/png" sizes="32x32" href={favicon32} />
<link rel="icon" type="image/png" sizes="16x16" href={favicon16} />
<link rel="manifest" href={manifest} />
<link rel="mask-icon" href={safariPinned} color="#a89472" />
<link rel="shortcut icon" href={faviconICO} />
<meta name="msapplication-config" content={browserConfig} />
<meta name="theme-color" content="#ffffff" />
```

This all works fine if I remove the two browserConfig lines. However, if I leave them in, the following error is thrown:

```
There was an error requiring "src/html.js"

 { Error: Cannot find module "./static/favicons/browserconfig.xml"
    at webpackMissingModule (render-page.js:50258:87)
    at Object.module.exports (render-page.js:50258:199)
    at __webpack_require__ (render-page.js:30:30)
    at Object.<anonymous> (render-page.js:81:11)
    at __webpack_require__ (render-page.js:30:30)
    at Object.assign.i (render-page.js:50:18)
    at render-page.js:53:10
    at webpackUniversalModuleDefinition (render-page.js:3:20)
    at render-page.js:10:3
    at ContextifyScript.Script.runInContext (vm.js:59:29) code: 'MODULE_NOT_FOUND' }
```

The `browserconfig.xml` file is next to the images in the `./static/favicons` folder, so I'm not sure why the images are found, but `browserconfig.xml` is not.

Any idea what I'm doing wrong?

**Comment by monsieurnebo** [comment]
The following code ...
```js
import favicon from './favicon.png';
<link rel="shortcut icon" type="image/png" href={favicon} />
```

... Is working fine, **BUT** it triggers an ESLint error (that I never encountered):

```
/Users/name/Documents/work/company/website-foo/src/favicon.png
  1:1  error  Parsing error: Unexpected character '�'

> 1 | �PNG
    | ^
  2 |
  3 |
  4 | IHDR szz�RIDATX���ϋMa���93����o1~l��BbD�(�����a�?P��l4v(�B���BV��Yf���t�8g8=ݹ3ҽ6����|�����sO�èF��

✖ 1 problem (1 error, 0 warnings)
```

All other images imports of the project are working fine, without triggering any ESLint error.

=> **Does any of you have encounter this issue? May it be related to the root html.js file, that is outside of the React app?**

**Comment by Necmttn** [comment]
> Webpack finds all relative module references in CSS (they start with ./) and replaces them with the final paths from the compiled bundle. If you make a typo or accidentally delete an important file, you will see a compilation error, just like when you import a non-existent JavaScript module. The final filenames in the compiled bundle are generated by Webpack from content hashes. 

maybe it's related to this. [source] (https://www.gatsbyjs.org/docs/adding-images-fonts-files/)

**Comment by benjaminhoffman** [comment]
Closing this issue as it seems it's solved.  @Vaestro @KyleAMathews or others, feel free to re-open if I am mistaken.

**Comment by gnunua** [comment]
Hi @KyleAMathews. Which approach is preferable for implementing icons? 
Overriding `html.js` or use `gatsby-plugin-react-helmet`
Thanks.

**Comment by nickmccurdy** [comment]
Note that you can also use `gatsby-ssr.js` with `onRenderBody`.

**Comment by ooloth** [comment]
@nickmccurdy Is it better to modify `html.js`, use `gatsby-ssr.js` or use `gatsby-plugin-react-helmet` to customize the `<head>`? 

The docs explain each method, but don't offer a clear recommendation for which to choose.

**Comment by nickmccurdy** [comment]
Honestly I'm unsure about that myself, I wish they explained a preference. They seem to prefer Helmet but I personally prefer `gatsby-ssr.js`.

**Comment by ooloth** [comment]
Okay, thanks for the info. I guess I'll use Helmet until I learn more. 

Out of curiousity, would you be willing to post a snippet of how you use `gatsby-ssr.js`? I tried adding some specific values to the [`onRenderBody`](https://www.gatsbyjs.org/docs/ssr-apis/#onRenderBody) example posted in the docs, but wasn't able to get any the values to appear on the site.

For example, I tried this:

```js
// gatsby.ssr.js
import Helmet from "react-helmet"

exports.onRenderBody = (
  { setHeadComponents, setHtmlAttributes, setBodyAttributes },
  pluginOptions
) => {
  const helmet = Helmet.renderStatic()
  setHtmlAttributes(helmet.htmlAttributes.toComponent({lang: `en`}))
  // ...
}
```

...but `lang="en"` did not appear on the `<html>` element on the dev or build version of the site.

**Comment by nickmccurdy** [comment]
I don't think toComponent takes arguments, but I'm not really sure how to set html attributes in Helmet.

```js
import React from 'react'

exports.onRenderBody = ({ setHeadComponents }) =>
  setHeadComponents([
    <title key="title">Nick McCurdy</title>,
    <link key="icon" rel="icon" href="/favicon.png" />
  ])
```

**Comment by ooloth** [comment]
Ah, thank you!

What's your approach for updating page titles and descriptions on subpages?

**Comment by nickmccurdy** [comment]
I'm not using one since this is a single page site, you'd probably need Helmet or html.js for that (personally I'd use Helmet since copying all that extra template HTML is kinda ugly and brittle).

**Comment by HaysS** [comment]
Just wanted to say that ooloth's solution worked for me. Have been trying to fix this for a while. Put a bunch of reactions on the comment so people will know it works if they see this later on.

**Comment by ambwani** [comment]
This worked for me:

import favicon from '../images/favicon.png';

<Helmet
  title="..."
  meta={[
      { name: 'description', content: '...' },
      { name: 'keywords', content: '....' },
  ]}
  link={[
      { rel: 'shortcut icon', type: 'image/png', href: `${favicon}` }
  ]}
/>

**Comment by ambwani** [comment]
This worked for me:

`import favicon from '../images/favicon.png';

<Helmet
  title="..."
  meta={[
      { name: 'description', content: '...' },
      { name: 'keywords', content: '....' },
  ]}
  link={[
      { rel: 'shortcut icon', type: 'image/png', href: `${favicon}` }
  ]}
/>`

**Comment by ambwani** [comment]
This worked for me:

import favicon from '../images/favicon.png';

```
<Helmet
  title="..."
  meta={[
      { name: 'description', content: '...' },
      { name: 'keywords', content: '....' },
  ]}
  link={[
      { rel: 'shortcut icon', type: 'image/png', href: `${favicon}` }
  ]}
/>
```

**Comment by ambwani** [comment]
This worked for me:

```
import favicon from '../images/favicon.png';

<Helmet
  title="..."
  meta={[
      { name: 'description', content: '...' },
      { name: 'keywords', content: '....' },
  ]}
  link={[
      { rel: 'shortcut icon', type: 'image/png', href: `${favicon}` }
  ]}
/>
```

**Comment by ambwani** [comment]
Thanks for such a prompt response. Wow, that is a really great insight, I will definitely try that in the future.

Would you possibly know how one could add links to external websites (say, LinkedIn and so forth) on Gatsby? I have been struggling with this for a while now.

Cheers,
Pranav

**Comment by ooloth** [comment]
@ambwani No problem! 

You just use a normal anchor tag like you would in HTML:

`<a href="https://www.linkedin.com" rel="noopener">LinkedIn</a>`

You don't need to use a special `<Link />` component for external links.

**Comment by ambwani** [comment]
I see @ooloth , but for some reason, Gatsby tends to make my SVG images for my socials invisible if I wrap them with an anchor tag.

Thank you though, I am glad that it is possible. I will let you know if I end up fixing the issue. Thank you, Sir!

**Comment by ooloth** [comment]
@ambwani Ah, your SVG collapsing its width or height is a CSS thing and doesn't relate to Gatsby or React.

Look into the `width` and `height` CSS values applied to the SVG (if you inspect the SVG in your browser's dev tools, you'll be able to figure out which dimension is collapsing). 

In case it helps, I like to set both properties to `1em` for SVGs used as icons. That way, their `width` and `height` will match the `font-size` of their container and the size of the surrounding text.

Good luck!

**Comment by clkent** [comment]
All you have to do to swap out the favicon as of today is change out the favicon.ico in your static folder.

**Comment by malcolm-kee** [comment]
In case anyone looking for similar solution, I'll share here about how to have dynamic favicons on different page.

Steps:
1. If you use [`gatsby-plugin-manifest`](https://www.gatsbyjs.org/packages/gatsby-plugin-manifest/), pass down `include_favicon: false` in the plugin options.
2. Install and configure [`gatsby-plugin-layout`](https://www.gatsbyjs.org/packages/gatsby-plugin-layout/) if you're not using it currently. Note: you need a `index.js` in `src/layouts` folder. Read more at `gatsby-plugin-layout` docs.
3. Create a context to keep track if favicon need to be overwrite. Then, create a custom hook that will set the value if icon is provided. The value will be reset to null when the component that use `useFavIcon` hook is unmounted.

```js
const FavIconContext = React.createContext(function noop() {  });

export const FavIconProvider = FavIconContext.Provider;

export const useFavIcon = ({ icon }) => {
  const setFavIconFolder = React.useContext(FavIconContext);

  React.useEffect(() => {
    if (iconFile) {
      setFavIconFolder(icon);
    }

    return () => setFavIconFolder(null);
  }, []);
};
```

4. In your `layouts/index.js`, create a state to keep track of favIcon value and pass down the value setter into the context. Then, set the favicon to default if favIcon value is `null`, else use the overridden value.

```jsx
import { FavIconProvider  } from './favicon-context.js';
import Helmet from 'react-helmet';

export default function Layout({ children }) {
    const [favIcon, setIcon] = React.useState(null);
   return (
       <React.Fragment>
          <Helmet>
              {/* I assume you use `gatsby-plugin-manifest` to generate icons to `public/icons` folder, adjust yourself if you're not */}
              <link rel="shortcut icon" href={ favIcon || "/icons/icon-48x48.png"} />
          </Helmet>
          <FavIconProvider value={setIcon}>
              {children}
          </FavIconProvider>
       </React.Fragment>
     );
}
```

5. Now, in any pages/page templates that you need to override the favicon, you just need to call `useFavIcon` with the icon file name:

```jsx
export function Page() {
   useFavIcon("/custom-icon.png"); // I assume you put an image with name "custom-icon.png" in static folder, which will be copied to public folder.

    return (<div>Some Page Content</div>
}
```

I implement this in my [personal site](https://github.com/malcolm-kee/malcolm-kee), but it may takes some time to understand because I generate all my icons dynamically instead of putting them in static folder 😅 

Hope this helps.

**Comment by ProgrammingJoe** [comment]
Depending on your Gatsby starter version, you may have to update the logo file in /static/favicon.ico. I have react helmet setup so my favicon was right but when shared on social media it was using the gatsby logo.

**Comment by wiserdivisor** [comment]
> This worked for me:
> 
> ```
> import favicon from '../images/favicon.png';
> 
> <Helmet
>   title="..."
>   meta={[
>       { name: 'description', content: '...' },
>       { name: 'keywords', content: '....' },
>   ]}
>   link={[
>       { rel: 'shortcut icon', type: 'image/png', href: `${favicon}` }
>   ]}
> />
> ```

THIS WORKED.
