### ISSUE TITLE
linkPrefix weirdness  

### ISSUE THREAD

**Issue by benstr** [gatsbyjs/gatsby#680]
Deployed to gh-pages no problem. Project name was `hackiot` so I set the config `linkPrefix = "/hackiot"`. No problems.

Then added a custom CNAME and changed config to `linkPrefix = "/"`. Now my routes do not include the TLD leaving all links broken (ex: http://about). 

Went back and changed  config to include the TLD `linkPrefix = "beta.hackiot.org/"`. That changed the routes to now include the TLD plus more (ex: http://beta.hackiot.org/beta.hackiot.org/about). 

What am I missing here?

**Comment by KyleAMathews** [comment]
What happens if you remove linkPrefix altogether from the config?

**Comment by benstr** [comment]
Removing from config throw an error when building. But it got me thinking... removed `--prefix-links` flag form the deploy script and all is well now.

Thanks for your input.

**Comment by chenvan** [comment]
I have the same problem.
follow @benstr 's solution.
It works. Thanks
