### ISSUE TITLE
gatsby-plugin-netlify-cms does not work with netlifycms v2 + gatsby v1

### ISSUE THREAD

**Issue by pungggi** [gatsbyjs/gatsby#6802]
Error: ./~/gatsby-plugin-netlify-cms/cms.js
  Module not found: Error: Cannot resolve module 'netlify-cms/dist/cms.css' in C:\Users\ap\.root\ws\gm\node_modules\gatsby-  plugin-netlify-cms
  resolve module netlify-cms/dist/cms.css in C:\Users\ap\.root\ws\gm\node_modules\gatsby-plugin-netlify-cms
    looking for modules in C:\Users\ap\.root\node_modules
      C:\Users\ap\.root\node_modules\netlify-cms doesn't exist (module as directory)
    looking for modules in C:\Users\ap\.root\ws\gm\node_modules\gatsby-plugin-netlify-cms\node_modules
      C:\Users\ap\.root\ws\gm\node_modules\gatsby-plugin-netlify-cms\node_modules\netlify-cms doesn't exist (module as dire  ctory)

 Error: ./~/netlify-cms/dist/netlify-cms.js
  Module parse failed: C:\Users\ap\.root\ws\gm\node_modules\netlify-cms\dist\netlify-cms.js Unexpected token (14:144353)
  You may need an appropriate loader to handle this file type.
  SyntaxError: Unexpected token (14:144353)
      at Parser.pp$4.raise (C:\Users\ap\.root\ws\gm\node_modules\acorn\dist\acorn.js:2221:15)

**Comment by ascorbic** [comment]
The first error at least will be fixed by #6798.
