### ISSUE TITLE
bug in v2 documentation 

### ISSUE THREAD

**Issue by saostad** [gatsbyjs/gatsby#6808]
I am following tutorials on v2 version and it seams link to "Create a list of our site's markdown files" https://next.gatsbyjs.org/tutorial/part-six/#create-a-list-of-our-sites-markdown-files-in-srcpagesindexjs is not working.

**Comment by jalmarazg** [comment]
Made a change to the documentation section to solve this issue.

**Comment by jalmarazg** [comment]
@piotrkwiecinski @m-allanson I have just created a PR for solving this issue, please take a look whenever you have a chance.

Thanks in advance.
