### ISSUE TITLE
AWS s3 + Cloudfront  with --prefixpath

### ISSUE THREAD

**Issue by justinwhall** [gatsbyjs/gatsby#6809]
I understand that the `Link` component will handle deploying to a subdirectory. In my case it's:

```
// realavant config settings
module.exports = {
  docsDir: 'docs',
  siteTitle: 'My Site Title',
  siteUrl: 'https://mysite.com',
  pathPrefix: '/docs',
};
```

*Gatsby Develop*

Works as expected. `localhost:8000/mypage/` renders "mypage".

*Production*

CloudFront site (http://cloudfront-dist-id.cloudfront.net) is proxied ---> `https://mysite.com/docs`.
After running `gatsby build --prefixpaths` and deploying to AWS also works as expected.

*Visiting the CloudFront URL directly* 

Does not work. All links across the site are http://cloudfront-dist-id.cloudfront.net/[path-prefix]/mypage.

^^ This 404s for obvious reasons. `mypage` doesn't live in the docs directory in this case. It lives here: `http://cloudfront-dist-id.cloudfront.net/mypage`. Some assets 404 for similar reasons. 

Generally this ins't really a big deal as we'd just use `https://stage.mysite.com/docs` as a staging env but for reasons not relevant to this question, I need the the CloudFront URL operational. 

Short of some runtime hook to sniff out root/prefix, what are my options?

**Comment by jlengstorf** [comment]
Hey, @justinwhall — I haven't actually tried this, but if you can specify an env var for staging vs. production builds, you could potentially try this:

```js
// realavant config settings
module.exports = {
  docsDir: 'docs',
  siteTitle: 'My Site Title',
  siteUrl: 'https://mysite.com',
  pathPrefix: process.env.CUSTOM_STAGING_VAR === 'staging' ? '' : '/docs',
};
```

Depending on how your build pipeline is set up, this would theoretically only apply the prefix when the site would be behind your proxy in production.

Would that work for you?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
