### ISSUE TITLE
Custom components inside markdown inside styled-component

### ISSUE THREAD

**Issue by janosh** [gatsbyjs/gatsby#6810]
I wish I had read [this](https://using-remark.gatsbyjs.org/custom-components/) much earlier but I finally found out what this `htmlAst` thing `remark` creates is for. And may I briefly say this is so cool!

In the linked tutorial, it says

> in general you’ll want to replace this:
> ```
> <div dangerouslySetInnerHTML={{ __html: post.html }} />
> ```
> with this:
> ```
> {
>   renderAst(post.htmlAst)
> }
> ```

In my case, I don't insert `html` into a div but rather a styled component:
```
<PageBody dangerouslySetInnerHTML={{__html: html}} />
```
How can I tell `renderAst` what the parent node should be?

**Comment by giraffesyo** [comment]
The wrapper around your tree is going to be a `p` tag unless you're using [`gatsby-remark-component`](https://www.gatsbyjs.org/packages/gatsby-remark-component/). Then it's a div. Consider that in your styled component by doing something like this:

```javascript
const PageBody = styled.div`
div {
    background-color: red;
}
`

```

Or on the other hand you could do something else:

In your markdown you have something like this:

```
---
title: 'Demo Page'
---
<my-custom-component>Boop</my-custom-component>

```

Assign that to a `MyCustomComponent` component and then within the component use your styled components

```javascript
export const MyCustomComponent = styled.div`
    background-color: red;
`
```

You can use this pattern to use markdown with even complex react components. Consider the following:
- These components can use static queries to pull in even more data
- The children are transformed by other gatsby plugins such as `gatsby-remark-images`, so img tags will automatically be converted into gatsby responsive images if you pass them as children. There is a lot of potential here.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
