### ISSUE TITLE
boundActionCreators warning should say to replace them with "actions" and also link to the upgrade docs for this

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/gatsby#6825]
boundActionCreators warning should say to replace them with "actions" and also link to the upgrade docs for this

**Comment by marisamorby** [comment]
@KyleAMathews: I updated this from a card to an issue so that it could be moved into the appropriate sub-epic. :)

**Comment by jlengstorf** [comment]
We should link to https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#rename-boundactioncreators-to-actions in the error message.

The error message is generated here:

https://github.com/gatsbyjs/gatsby/blob/b6bdb82555893177a6c85d62b28abe471e484b8d/packages/gatsby/src/commands/develop.js#L388-L421

I think we can modify it a bit:

```js
    const fixMap = {
      boundActionCreators: {
        newName: `actions`,
        docsLink: `https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#rename-boundactioncreators-to-actions`,
      },
      // ...
    }
```

And then update the print template to show that docs link as well.

This would be a great first issue for someone!

**Comment by thefifthisa** [comment]
Hi, I'm new here and I'd love to take this!

**Comment by jlengstorf** [comment]
Yes! Thanks @thefifthisa! Let us know if you have questions or need a second set of eyes. 💪💜

**Comment by thefifthisa** [comment]
@jlengstorf Just opened a PR! Please let me know what I need to change or if it's okay already.
