### ISSUE TITLE
Is there any way to use hash routing with Gatsby?

### ISSUE THREAD

**Issue by Tatsuman** [gatsbyjs/gatsby#6826]
## Summary
Is there any way to use hash routing with Gatsby?
## Relevant information

Hello, I am tring to make Single Page App and I wonder if there is any way to use hash routing in Gatsby. All information that I could find is about gatsby-link but I don't believe gatsby-link allow me to do component change with path change. Does anyone know good way to work around this? Thank you in advance!

**Comment by EdPike365** [comment]
[gatsby-plugin-anchor-links](https://www.gatsbyjs.com/plugins/gatsby-plugin-anchor-links/?=anchor) looks promising. I'm implementing it now.
