### ISSUE TITLE
Several example project URLs fail to resolve

### ISSUE THREAD

**Issue by johnaoss** [gatsbyjs/gatsby#6829]
## Description

The URLs linked in the README of [example/styleguide](https://github.com/gatsbyjs/gatsby/tree/master/examples/styleguide), alongside the following  does not resolve to a known host.

Same behaviour with the following:

* [gatsby/examples/using-remark-copy-linked-files/](https://using-gatsby-remark-copy-linked-files.gatsbyjs.org/)
* [gatsby/examples/using-react-url-query/](https://using-react-url-query.gatsbyjs.org/)
* [gatsby/examples/using-prefetching-preloading-modules/](https://using-prefetch-preload-module.gatsbyjs.org/)
* [gatsby/examples/using-page-loading-indicator/](https://using-page-loading-indicator.gatsbyjs.org/)
* [gatsby/examples/using-hjson](https://using-hjson.gatsbyjs.org/)
* [gatsby/examples/using-excel/](https://using-excel.gatsbyjs.org/)
* [gatsby/examples/using-emotion-prismjs/](https://using-emotion-prismjs.gatsbyjs.org/)
* [gatsby/examples/using-csv/](https://using-csv.gatsbyjs.org/)
* [gatsby/examples/no-plugins](https://no-plugins.gatsbyjs.org/)

### Steps to reproduce

Visit the URL specified in the README: https://styleguide.gatsbyjs.org, or any of those specified above

### Expected result

Expected the webpage to load with a website running the specified example site.

### Actual 

Failed to resolve the host of styleguide.gatsbyjs.org, given error: `DNS_PROBE_FINISHED_NXDOMAIN`

This behaviour is consistent across multiple networks, and across multiple example urls. 

### Environment

DNS Servers: 
```
8.8.8.8
8.8.4.4
1.1.1.1
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A 

Example Log:

```
$ ping https://styleguide.gatsbyjs.org
ping: cannot resolve https://styleguide.gatsbyjs.org: Unknown host

$ ping google.ca
PING google.ca (172.217.0.99): 56 data bytes
64 bytes from 172.217.0.99: icmp_seq=0 ttl=53 time=16.599 ms
64 bytes from 172.217.0.99: icmp_seq=1 ttl=53 time=17.677 ms
^C
--- google.ca ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 16.599/17.138/17.677/0.539 ms
```

**Comment by dianasaurio** [comment]
Hi, I would like to help with this issue but I don't know where to find those links. Any clue?

**Comment by shobhitchittora** [comment]
I ran dig on `styleguide.gatsbyjs.org` and 
```shell
$ dig styleguide.gatsbyjs.org


;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;styleguide.gatsbyjs.org.	IN	A

;; AUTHORITY SECTION:
gatsbyjs.org.		274	IN	SOA	ns-cloud-d1.googledomains.com. cloud-dns-hostmaster.google.com. 47 21600 3600 259200 300
```

**Comment by m-allanson** [comment]
Check out [this comment on issue 5750](https://github.com/gatsbyjs/gatsby/issues/5750#issuecomment-395319766) - these should be fixed automatically once Gatsby's new testing infrastructure is in place.

For now I guess the best thing would be to remove the links that don't exist. 

This would mean updating the README.md file for each [example project](https://github.com/gatsbyjs/gatsby/tree/master/examples) that doesn't have a working public URL. e.g. (as @johnaoss mentioned) here's the README.me for the styleguide example: https://github.com/gatsbyjs/gatsby/blob/master/examples/styleguide/README.md

**Comment by dianasaurio** [comment]
I can make a PR if you want!

**Comment by shobhitchittora** [comment]
@dianasaurio Go ahead! 👍

**Comment by johnaoss** [comment]
Thanks @dianasaurio! Closing this issue now.
