### ISSUE TITLE
Importing .otf(Open Type Font) is not working...

### ISSUE THREAD

**Issue by sovanjana** [gatsbyjs/gatsby#6832]
`@font-face {
  font-family: 'Font File';
  src: url('../../asset/font/electraltstd_regular.OTF') format('otf');
  font-weight: normal;
  font-style: normal;
}`

this code snippet throwing error.....

> in ./src/asset/font/electraltstd_regular.OTF
> Module parse failed: Unexpected character ' ' (1:4)
> You may need an appropriate loader to handle this file type.
> (Source code omitted for this binary file)

this same code working fine while I'm using any other font format... #

**Comment by deadcoder0904** [comment]
Use it like [this](https://github.com/gatsbyjs/gatsby/issues/2583#issuecomment-340722928)

Also, I don't know where its written but always use WOFF2 if not available then go with WOFF bcz its smaller than TTF & WOFF2 has more compression. 

I don't know for sure but OTF is not supported on various browsers I guess. Check https://stackoverflow.com/a/3245187/6141587

**Comment by sovanjana** [comment]
great solution [#2583 (comment)](https://github.com/gatsbyjs/gatsby/issues/2583#issuecomment-340722928) ...
but there must be a solution for those who don't want to use "styled-components"...

**Comment by deadcoder0904** [comment]
Put it in your `.css` file globally is one way like - 

```css
@import url('https://fonts.googleapis.com/css?family=Roboto'); 
/* or use it locally like */


html {
  font-family: 'Roboto', sans-serif;
}
```

Typefaces - https://github.com/KyleAMathews/typefaces is another way

`gatsby-plugin-google-fonts` is another way if its on Google Fonts. Try & check if these solve your issue❓

If that doesn't work, then try adding [Custom Webpack Config](https://next.gatsbyjs.org/docs/add-custom-webpack-config/) & add `file-loader` like https://stackoverflow.com/a/46822752/6141587

**Comment by Chuloo** [comment]
Thanks for the pointers @deadcoder0904  👍

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍
