### ISSUE TITLE
Absolute path from dev in bundle.js

### ISSUE THREAD

**Issue by omaksi** [gatsbyjs/gatsby#684]
The absolute path from the dev environment is present in the exported bundle.js

Gatsby 0.12.34, node 7.4.0, Win10, gatsby-starter-blog project

```
pages:[{file:{
root:"",
dir:"",
base:"_template.jsx",
ext:"jsx",
name:"_template",
extname:".jsx",
basename:"_template.jsx",dirname:"",
stem:"_template",
path:"_template.jsx",
absolute:"C:\\Users\\***********\\_template.jsx", <- !!
isAbsolute:!1},
requirePath:"_template.jsx",
...```

**Comment by KyleAMathews** [comment]
Yeah, that shouldn't be shipped to clients. Could you add a PR deleting it from https://github.com/gatsbyjs/gatsby/blob/ac270441f4489f0aca85720237b6a95dc6ff9da7/lib/utils/build-page/path-resolver.js#L10?
