### ISSUE TITLE
Write better documentation for loading remote images in source plugins (createRemoteFileNode)

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#6842]
A common problem we've been seeing for people creating source plugins is that it's really hard to find information about how to pull in remote images for use with `gatsby-image`, etc.

The only docs on it now are [tucked away in `gatsby-source-filesystem`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-filesystem#createremotefilenode). We should create an additional section in the main docs on how to do this. (Really, we need a whole tutorial on writing source plugins in the docs, but we can start here.)

**Comment by jlengstorf** [comment]
@alexluong wrote up [this tutorial](https://blog.alexluong.com/generate-gatsby-image-sharp-from-an-image-url/), which could lay a great foundation for these docs.

**Comment by alexluong** [comment]
@jlengstorf We already have a tutorial for writing source plugins. I think you're the one who wrote it (gatbsy-source-pixabay). Maybe we can just update it with `createRemoteFileNode` to use with `gatsby-image`?

**Comment by stoutlabs** [comment]
There's also a (nearly hidden) link to a [create source plugin](https://next.gatsbyjs.org/docs/create-source-plugin/) page tucked away near the bottom of that tutorial.  

This is actually something I've noticed a few times when using the v2 docs: There are a few things that aren't easily found without scanning thru another page, and they probably need a link from the docs menu for ease of access. (An example that comes to mind is the list of starters.)

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by KyleAMathews** [comment]
Also in v2, the various plugin writing docs are all now in the same group 🎉

**Comment by borekb** [comment]
This is also a great article: [Wrangling remote images with Gatsby](https://www.wildsmithstudio.com/blog/remote-images-with-gatsby/)
