### ISSUE TITLE
Best practices for integrating 3rd party "legacy" JS libraries?

### ISSUE THREAD

**Issue by daneasterman** [gatsbyjs/gatsby#6851]
I am using a popular third party library called Timeline JS developed by Northwestern University's Knight Lab. As it is fairly old, there don't appear be any resources online on how to integrate it with React. 

However, Timeline JS shares some characteristics with the Google Maps API, so after reviewing a number of guides / tutorials on this and adapting the code, I came up with the following which works (partly): 

`templates/blog-post`:

```
import React from "react";
import PropTypes from "prop-types";
import { kebabCase } from "lodash";
import Helmet from "react-helmet";
import Link from "gatsby-link";
import Content, { HTMLContent } from "../components/Content";
import Script from "react-load-script";

class BlogPostTemplate extends React.Component {
  constructor(props) {
    super(props);    
  }

  displayTimeline() {
    const timelineID = document.getElementById('timelineID');

    const timeline = new TL.Timeline(timelineID, "../../data/england.json");
    window.onresize = function(event) {
      timeline.updateDisplay();
    };

  }

  render() {
    const {
      content,
      contentComponent,
      description,
      tags,
      title,
      helmet
    } = this.props;

    const PostContent = contentComponent || Content;

    return (
      <section className="section">
        <Helmet>
          <link
            title="timeline-styles"
            rel="stylesheet"
            href="https://cdn.knightlab.com/libs/timeline3/latest/css/timeline.css"
          />
        </Helmet>
        <Script
          url="https://cdn.knightlab.com/libs/timeline3/latest/js/timeline.js"          
          onLoad={this.displayTimeline.bind(this)}
        />
        <div className="container content">
          <div className="columns">
            <div className="column is-10 is-offset-1">
              <div className="section">
                <h1 className="blog-title">{title}</h1>
                <p>{description}</p>

                <PostContent content={content} />
                <div id="timelineID" style={{ height: "100%", width: "100%" }} />
                {tags && tags.length ? (
                  <div style={{ marginTop: `4rem` }}>
                    <h4>Tags</h4>
                    <ul className="taglist">
                      {tags.map(tag => (
                        <li key={tag + `tag`}>
                          <Link to={`/tags/${kebabCase(tag)}/`}>{tag}</Link>
                        </li>
                      ))}
                    </ul>
                  </div>
                ) : null}
              </div>
            </div>
          </div>
        </div>
      </section>
    );
  }
}

BlogPostTemplate.propTypes = {
  content: PropTypes.string.isRequired,
  contentComponent: PropTypes.func,
  description: PropTypes.string,
  title: PropTypes.string,
  helmet: PropTypes.instanceOf(Helmet)
};

const BlogPost = ({ data }) => {
  const { markdownRemark: post } = data;

  return (
    <BlogPostTemplate
      content={post.html}
      contentComponent={HTMLContent}
      description={post.frontmatter.description}
      tags={post.frontmatter.tags}
      title={post.frontmatter.title}
    />
  );
};

BlogPost.propTypes = {
  data: PropTypes.shape({
    markdownRemark: PropTypes.object
  })
};

export default BlogPost;

export const pageQuery = graphql`
  query BlogPostByID($id: String!) {
    markdownRemark(id: { eq: $id }) {
      id
      html
      frontmatter {
        date(formatString: "MMMM DD, YYYY")
        title
        description
        tags
      }
    }
  }
`;
```

My first problem is that the width and height dimensions of the timeline seem to vary massively after loading the page. Sometimes it is correctly proportioned and other times it is completely wrong. See screenshots below:

**Correct proportions:**

<img width="706" alt="screen shot 2018-07-29 at 15 23 02" src="https://user-images.githubusercontent.com/4712052/43367499-dc7c9f58-9345-11e8-865b-25c748abcd4e.png">

**Incorrect** (text and timeline slider is not visible until substantial scrolling down page)  :

<img width="673" alt="screen shot 2018-07-29 at 15 22 40" src="https://user-images.githubusercontent.com/4712052/43367500-e316bc04-9345-11e8-897d-7bcaca5122c8.png">

In the code have specified the width and height properties to be 100% which does not yield any problems in non-React projects.

What is the best practice here to ensure that width/height is consistently correct? 

My second problem is more specifically Gatsby-related. The problem with the above approach in `templates/blog-post.js` is that every time a new blog post with a timeline needs to be created, I would need to create a new blog post react component. This is because each timeline relies on a new json file to populate it with different content. 

It would be far more scalable to simply publish a markdown file with the reference to the json file. I did this initially, however it involved a weird hack with `window.eval()` in order for this to work and even then it required a manual refresh for the library to actually initialise. 

What are your thoughts on the best approach here?

Thanks so much in advance, Gatsby is awesome!

**PS: My environment details:**

  System:
    OS: OS X Yosemite 10.10.5
    CPU: x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.1.0 - /usr/local/bin/node
    Yarn: yarn install v0.24.6
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.47s. - /usr/local/bin/yarn
    npm: 5.0.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 60.0.1
    Safari: 10.1.2
  npmPackages:
    gatsby: ^1.9.213 => 1.9.273 
    gatsby-link: ^1.6.37 => 1.6.45 
    gatsby-plugin-netlify: ^1.0.19 => 1.0.21 
    gatsby-plugin-netlify-cms: ^1.0.9 => 1.0.12 
    gatsby-plugin-react-helmet: ^2.0.5 => 2.0.11 
    gatsby-plugin-sass: ^1.0.17 => 1.0.26 
    gatsby-plugin-sharp: ^1.6.34 => 1.6.48 
    gatsby-remark-images: ^1.5.50 => 1.5.67 
    gatsby-source-filesystem: ^1.5.39 => 1.5.39 
    gatsby-transformer-remark: ^1.7.33 => 1.7.44 
    gatsby-transformer-sharp: ^1.6.21 => 1.6.27 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

**Comment by anantoghosh** [comment]
React ignores direct manipulations to the dom https://reactjs.org/docs/integrating-with-other-libraries.html

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
