### ISSUE TITLE
Broken v2 Source Plugin Tutorial

### ISSUE THREAD

**Issue by krabbypattified** [gatsbyjs/gatsby#6857]
## Description

The [v2 source plugin tutorial](https://next.gatsbyjs.org/docs/source-plugin-tutorial/) is broken. I believe the cause is :

```
gatsby new source-tutorial-site
```

because it creates a gatsby v1 project. This means we have access to `boundActionCreators`, not `actions`. This produces the following error :

```
Cannot destructure property `createNode` of 'undefined' or 'null'.
```

I am new to Gatsby, so perhaps I am unaware of a v2 cli, but this would be my recommended solution for now (until Gatsby has a v2 cli) :

```
gatsby new my-default-project https://github.com/gatsbyjs/gatsby-starter-default#v2
```

Perhaps there are still other issues with this tutorial, so I would recommend that someone experienced with Gatsby take a look at it. For example, I am still seeing instances of `boundActionCreators` when it should be `actions`.

**Comment by LeKoArts** [comment]
@krabbypattified Hi!
Yes, you're right, the initialization still refers to v1 and your proposed bash command is right. Also there's one occurrence of `boundActionsCreators`. The rest seems fine to me.

How about tackling this issue yourself? 👍 
You can start by clicking on the "Edit this page" at the end of the page.

**Comment by krabbypattified** [comment]
@LeKoArts 
I've fixed `boundActionsCreators`, updated the bash command, and did a bit of housekeeping.
Feel free to review :)

**Comment by m-allanson** [comment]
Thanks @krabbypattified! It looks like @shobhitchittora got there before you on fixing the command, but the rest of your changes look good. Can you create a Pull Request from your commit? You should be able to do that here: https://github.com/gatsbyjs/gatsby/compare/master...krabbypattified:patch-1
