### ISSUE TITLE
Is it possible to get access to window.navigator?

### ISSUE THREAD

**Issue by lipis** [gatsbyjs/gatsby#6859]
`location` is being passed as a prop, but what about `window.navigator` if we want to do device detection? Is that doable?

**Comment by Khaledgarbaya** [comment]
You can still use `window.navigator` anywhere in your component since it's global.
You need to wrap your code with `if(typeof window !== 'undefined')` so when Gatsby is building the website it does not crash.

**Comment by lipis** [comment]
There is small delay/flickering happening at the moment, but at least it works that way. We'll see in the future if there is anything else possible.
