### ISSUE TITLE
Hot reloading not working

### ISSUE THREAD

**Issue by Helw150** [gatsbyjs/gatsby#686]
Hot reloading is not working with the standard starter on Ubuntu 16.04 with version 0.12.34.

**Comment by KyleAMathews** [comment]
Any errors you see?

**Comment by Helw150** [comment]
I have a warning on `os.tmpDir()` being deprecated. The page won't even change on refresh, so I think the issue stems from webpack.

The behavior of the issue is exactly like the following: https://github.com/facebook/react-native/issues/10889

 They point to Watchman being the issue in that thread.

**Comment by Helw150** [comment]
If anyone has experienced this on Linux and knows a fix it'd be great to hear. I toyed around with the different starters, webpack, and my npm packages but can't seem to crack the nut. 

Webpack and hot reloading works on my other React projects so I'm a little bit baffled. I'll give it a more solid shot on the weekend.

**Comment by Helw150** [comment]
When I rebooted today, hot reloading worked. Something I did fixed it, though I am not entirely sure what.

**Comment by Helw150** [comment]
@KyleAMathews Just to update you, I figured out the issue. If you add or remove a file, you have to restart webpack for hot reloading to work on anything else at all.

**Comment by ovikholt** [comment]
I cannot get hot reloading to work either. Do you need to set anything up in your browser for it to work, or is there anything else less than obvious that I might be missing?

**Comment by Helw150** [comment]
My issue stemmed only from when I deleted or created a file after Webpack was running. If you are working with an entirely fresh starter, your best bet is to make webpack is up to date. Nothing should need to be set in your browser.

**Comment by tito300** [comment]
I had the same problem and it was fixed by increasing the number of system watchers following these instructions: 

https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers#the-technical-details
