### ISSUE TITLE
Page query filter not working properly

### ISSUE THREAD

**Issue by graphman65** [gatsbyjs/gatsby#6864]
## Description

Query without filter give me all the data I need with one node having the id XXXXX then when I do the exact same query with a filter on the id, it give me an empty result.

![alt text](https://i.imgur.com/zmr3oYX.png "Second")
![alt text](https://i.imgur.com/olb1xS4.png "First")

### Steps to reproduce

Same as description

### Expected result

The matching node should be returned.

### Actual result

The result is empty.

### Environment
  System:
    OS: Linux 4.15 Ubuntu 18.04 LTS (Bionic Beaver)
    CPU: x64 Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 10.5.0 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/bin/yarn
    npm: 6.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 61.0.1
  npmPackages:
    gatsby: ^2.0.0-beta.61 => 2.0.0-beta.61 
    gatsby-node-helpers: ^0.3.0 => 0.3.0 
    gatsby-plugin-emotion: ^1.1.17 => 1.1.17 
    gatsby-plugin-material-ui: ^0.1.3 => 0.1.3 
    gatsby-plugin-netlify: ^2.0.0-beta.2 => 2.0.0-beta.2 
    gatsby-plugin-react-helmet: ^3.0.0-beta.3 => 3.0.0-beta.3 
    gatsby-plugin-react-svg: ^1.1.1 => 1.1.1 
    gatsby-plugin-sitemap: ^2.0.0-beta.2 => 2.0.0-beta.2 
    gatsby-plugin-typescript: ^2.0.0-beta.5 => 2.0.0-beta.5 
    gatsby-source-filesystem: ^2.0.1-beta.3 => 2.0.1-beta.3 
    gatsby-transformer-json: ^2.1.1-beta.2 => 2.1.1-beta.2

**Comment by Chuloo** [comment]
Hi @graphman65, could you provide more details on how to reproduce the code? Better if you could share a repo containing the stated abnormality. 👍

**Comment by graphman65** [comment]
Hi, any example in the examples folder using filter have the same issue.
I also think the limit arg is buggy aswell.
I'm trying to find what's wrong but I guess it might be related to the recent changes in gatsby/src/schema/build-node-connections.js.

**Comment by dbrookes** [comment]
Seeing the same thing:

`gatsby =2.0.0-beta.20` its possible to filter on id

`gatsby =2.0.0-beta.21` filtering on id returns null

I was able to work around it by adding another field with the ID and it works again:

`(filter: { filterId: { eq: "1788" } })`
