### ISSUE TITLE
[i18n] react-translate working for develop, not for build

### ISSUE THREAD

**Issue by mtt87** [gatsbyjs/gatsby#688]
```
Gatsby 0.12.34
Node 7.5.0
MacOS Sierra 10.12.2
```

I'm using https://github.com/bloodyowl/react-translate and it's working perfectly on `gatsby develop` but then when I try to `gatsby build` I get errors.

`gatsby-browser.js` seems to be fine
```
import React from 'react';
import { TranslatorProvider } from "react-translate";
import cookie from 'react-cookie';
const translations = require('./i18n');

exports.wrapRootComponent = (Root) => {
  const locale = cookie.load('locale') || 'en';
  const Wrapper = () => (
    <TranslatorProvider translations={translations[locale]}>
      <Root />
    </TranslatorProvider>
  )
  return Wrapper;
}
```

The problems are related to the single components calling `translate`

```
import React from 'react';
const Home = ({ t }) => {
  return (
    <div>
      {t("tagline1")}
    </div>
  );
}
export default translate("Home")(Home);
```

The errors I get on build time 
```
Failed at generating HTML

/Users/mattia/Dev/meal/website2/node_modules/gatsby/dist/bin/cli.js:42
      throw err;
      ^
Error: TypeError: translator is not a function
    at Translator.render (render-page.js:36896:18)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (render-page.js:14352:31)
    at ReactCompositeComponentWrapper._renderValidatedComponent (render-page.js:14375:33)
    at ReactCompositeComponentWrapper.performInitialMount (render-page.js:13915:31)
    at ReactCompositeComponentWrapper.mountComponent (render-page.js:13811:22)
    at Object.mountComponent (render-page.js:6882:36)
    at ReactDOMComponent.mountChildren (render-page.js:12945:45)
    at ReactDOMComponent._createContentMarkup (render-page.js:9972:33)
    at ReactDOMComponent.mountComponent (render-page.js:9839:30)
    at Object.mountComponent (render-page.js:6882:36)
```

Any clue why during `gatsby build` (server side rendering) that function isn't working?
Shouldn't it work the same way as redux `connect`?

Thank you 😄

**Comment by KyleAMathews** [comment]
Hmmm I'd suggest console.loging things to try to track down the problem. It
seems like it should work so hard to tell.

**Comment by mtt87** [comment]
Happening the same using `react-intl` module, works fine during development but fails on build.
`Invariant Violation: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.`

Is Gatsby doing something during build time at this step?
```
exports.wrapRootComponent = (Root) => {
  const locale = cookie.load('locale') || 'en';
  const messages = translations[locale];
  const Wrapper = () => (
    <IntlProvider initialNow key={locale} locale={locale} messages={messages}>
      <Root />
    </IntlProvider>
  )
  return Wrapper;
}
```

```
Failed at generating HTML

/Users/mattia/Dev/meal/website2/node_modules/gatsby/dist/bin/cli.js:42
      throw err;
      ^
Error: Invariant Violation: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.
    at invariant (render-page.js:20273:16)
    at invariantIntlContext (render-page.js:49563:6)
    at new FormattedMessage (render-page.js:50613:10)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (render-page.js:13851:17)
    at ReactCompositeComponentWrapper._constructComponent (render-page.js:13838:20)
    at ReactCompositeComponentWrapper.mountComponent (render-page.js:13741:22)
    at Object.mountComponent (render-page.js:6882:36)
    at ReactDOMComponent.mountChildren (render-page.js:12945:45)
    at ReactDOMComponent._createContentMarkup (render-page.js:9972:33)
    at ReactDOMComponent.mountComponent (render-page.js:9839:30)
```

**Comment by mtt87** [comment]
Probably found the problem is related to `react-router`
https://github.com/yahoo/react-intl/issues/352

**Comment by mtt87** [comment]
I think I may have a clue: during development everything runs in the browser where `intl` works fine but this doesn't work in node/webpack and needs to be polyfilled.

I'm not 100% sure it's related to this, I'm still investigating.

**Comment by mtt87** [comment]
I'm quite sure I've isolated the issue and it's 100% related to the fact that `exports.wrapRootComponent` doesn't seem to work properly on server-side rendering (`gatsby build`) and the context is lost.

```
exports.wrapRootComponent = (Root) => {
  const Wrapper = () => (
    <Provider>
      <Root />
    </Provider>
  )
  return Wrapper;
}
```

Any `<Provider>` related to i18n I've tried is failing on this like if it's not applied at all during `gatsby build` and the context is lost so every component doesn't have the translate function in its context.

I'll try with `redux` just to give it a try and understand if that works or not.

**Comment by mtt87** [comment]
Could it be related to this step?
https://github.com/gatsbyjs/gatsby/blob/b4d585a2c0035dc3c8896c42e2daaac1b520be5a/lib/utils/webpack.config.js#L137

```
case 'build-html':
  config.plugin('static-site-generator', StaticSiteGeneratorPlugin, ['render-page.js', routes])
```

Seems like you are adding manually routes to`render-page.js` otherwise it doesn't inherit them automatically from the `context` of `react-router`?

I was thinking if I have to do the same and pass the `translator` function created by the provider but at the moment I have no clear idea how all of this is working.

Could be related to the `scope` of `static-site-generator-webpack`?
https://github.com/markdalgleish/static-site-generator-webpack-plugin#scope

**Comment by KyleAMathews** [comment]
Oh so you need to wrap the render function on both the client *and* the server?

Then the problem is that `wrapRootComponent` is client-only. It doesn't get called when doing the static html build. We need an equivalent API for server rendering in https://github.com/gatsbyjs/gatsby/blob/master/lib/utils/static-entry.js

**Comment by mtt87** [comment]
@KyleAMathews mistery solved.

I'll see tonight if I can contribute and add that API for server rendering, any advice is welcome of course 😄

**Comment by mtt87** [comment]
@KyleAMathews 
What about adding the same on `gatsby-node.js`
```
exports.wrapRootComponent = (Root) => ..
```

But then I have no clue where I should hook that.

**Comment by KyleAMathews** [comment]
sweet!

So basically what you need to do (I had to do something very similar for 1.0) is to add support for a new API file for server rendering. We can't use `gatsby-node.js` for this as there's lots of node modules that'd break things if we imported them into a React site. So instead, like in the browser, try importing a `gatsby-ssr.js` file and then run a `wrapRootComponent` function if one is provided.

**Comment by mtt87** [comment]
Seems to be working 🍾 🎉  but 3 tests are failing 😢  (and I don't understand the reason)

`gatsby-ssr.js`
```js
import React from 'react';
const translations = require('./i18n');
import { TranslatorProvider } from 'react-translate';

exports.wrapRootComponent = (Root) => {
  const locale = 'en';
  const messages = translations[locale];
  const Wrapper = () => (
    <TranslatorProvider translations={messages}>
      <Root />
    </TranslatorProvider>
  )
  return Wrapper;
}
```
`static-entry.js`
```js
import { wrapRootComponent } from 'gatsby-ssr'
...
} else if (renderProps) {
      const componentToWrap = () => (<RouterContext {...renderProps} />)
      let body
      let component

      if (wrapRootComponent) {
        component = wrapRootComponent(componentToWrap)
      } else {
        component = componentToWrap
      }

      // If we're not generating a SPA for production, eliminate React IDs.
      if (config.noProductionJavascript) {
        body = renderToStaticMarkup(component())
      } else {
        body = renderToString(component())
      }

      const html = `<!DOCTYPE html>\n ${renderToStaticMarkup(
        // eslint-disable-next-line comma-dangle
        <Html body={body} {...renderProps} />
      )}`
      callback(null, html)
    }
```

Tests failing
```
1. user-rewrites-path-not-ending-in-slash › build the site
2. static-html-wrappers › build the site
3. user-rewrites-path › build the site
```

Any clue?

**Comment by KyleAMathews** [comment]
Without seeing the test output no. Create the PR and we can see what
travisci says.

**Comment by mtt87** [comment]
Okay now I see a clear log:
https://travis-ci.org/gatsbyjs/gatsby/jobs/204781434

I guess I have to
* write a test in the `fixtures` dir, a case where you use `gatsby-ssr.js`
* write it somewhere in `README.md`
* understand why during `gatsby build` there is some logging that I'm not expecting

```
$ gatsby build
Generating CSS
Generating Static HTML
{ history: 
   { listenBefore: [Function: listenBefore],
     listen: [Function: listen],
     transitionTo: [Function: transitionTo],
     push: [Function: push],
     replace: [Function: replace],
     go: [Function: go],
     goBack: [Function: goBack],
     goForward: [Function: goForward],
     createKey: [Function: createKey],
     createPath: [Function: createPath],
     createHref: [Function: createHref],
     createLocation: [Function: createLocation],
     setState: [Function],
     registerTransitionHook: [Function],
     unregisterTransitionHook: [Function],
     pushState: [Function],
     replaceState: [Function],
     __v2_compatible__: true,
     isActive: [Function: isActive],
     match: [Function: match],
     listenBeforeLeavingRoute: [Function: listenBeforeLeavingRoute] },
  location: 
   { pathname: '/',
     search: '',
     hash: '',
     state: null,
     action: 'POP',
     key: 'omsrwq',
     query: {},
     '$searchBase': { search: '', searchBase: '' } },
  params: {},
  route: 
   { component: { [Function: Translator] contextTypes: [Object] },
     page: { file: [Object], requirePath: 'index.js', path: '/', data: {} },
     pages: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     templates: [ [Object] ],
     parentTemplateFile: undefined },
  routeParams: {},
  routes: 
   [ { path: '/',
       component: [Object],
       childRoutes: [Object],
       indexRoute: [Object],
       pages: [Object],
       templates: [Object] },
     { component: [Object],
       page: [Object],
       pages: [Object],
       templates: [Object],
       parentTemplateFile: undefined } ],
  children: null,
  t: [Function] }
ReferenceError: window is not defined
    at Object.<anonymous> (render-page.js:41457:16)
    at __webpack_require__ (render-page.js:40944:32)
    at executor (render-page.js:41433:19)
    at F (render-page.js:42265:29)
    at dispatchRequest (render-page.js:41421:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)

Compiling production bundle.js
Copying assets
Done
```

**Comment by GiuMagnani** [comment]
If someone is still facing this issue (like me today), I had the `IntlProvider` inside the **Layout** file that was inside `gatsby-browser.js`, so when I tried to build, the server couldn't find the Provider.

I solved it moving **Layout** inside `IntlProvider`, then creating the `gatsby-ssr.js` file and adding the same behaviour using `wrapPageElement` API:

```
export const wrapPageElement = ({ props, element }) => {
  const locale = props.pageContext.locale;
  const pageLocale = locale || defaultLocale;

  return (
    <IntlProvider locale={locale} messages={messages[pageLocale]}>
      <Layout locale={locale} {...props}>
        {element}
      </Layout>
    </IntlProvider>
  );
};
```

My repository: https://github.com/GiuMagnani/giu-magnani-website

Issues related:
#865
https://github.com/yahoo/react-intl/issues/307
markdalgleish/static-site-generator-webpack-plugin#77
