### ISSUE TITLE
How to reference video asset in Markdown file?

### ISSUE THREAD

**Issue by MaxMcKinney** [gatsbyjs/gatsby#6893]
I have a video that I want to put into a Markdown file, and I'm not sure how to do it.

I need the video to be reference in the content of the Markdown and not in the frontmatter.

I have an assets folder inside of the src folder where the video is stored. I also have gatsby-source-filesystem setup to grab assets from the assets folder and I'm able to view the video file in graphql when testing with GraphiQL.

I'm not sure how to reference it though in the Markdown file, I've tried a few different variations of preceding slashes and dots but I don't know how it's all getting built.

Is this possible?

**Comment by anantoghosh** [comment]
You can directly write html `video` tag in your markdown

Here is an example:
https://next.gatsbyjs.org/tutorial/part-five/#introducing-graphiql
source: https://raw.githubusercontent.com/gatsbyjs/gatsby/master/docs/tutorial/part-five/index.md

**Comment by anantoghosh** [comment]
It's in the `static` folder https://github.com/gatsbyjs/gatsby/tree/master/www/static
files in static folder are copied to the root of `public` folder and therefore can be directly accessed from the url `/filename`
https://next.gatsbyjs.org/docs/adding-images-fonts-files/#using-the-static-folder

**Comment by MaxMcKinney** [comment]
Ah okay, thanks for letting me know!
