### ISSUE TITLE
Floating Table of Contents for longer docs (ToC)

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#6896]
@calcsam idea: Quip writing app does this in a clean and clear way

<img width="1046" alt="screen shot 2018-07-31 at 10 09 07 am" src="https://user-images.githubusercontent.com/32467162/43475210-ddcc0f00-94a9-11e8-9107-2379134df175.png">

**Comment by shannonbux** [comment]
Hi @fk I put this in the Docs redesign phase 3 EPIC, open to discussion on how to prioritize it!

**Comment by fk** [comment]
👍

**Comment by johncmunson** [comment]
@shannonbux you might be interested in checking out this [Gatsby starter](https://gatsby-clean-blog.netlify.com/farms-around-the-world/) I've been working on which implements a floating TOC like you've described. I can't remember exactly why it wasn't sufficient for my use case, but my implementation does not make use @DSchau's [TOC plugin](https://github.com/DSchau/gatsby-remark-toc)

**Comment by shannonbux** [comment]
Hi @johncmunson, cool starter! I don't see the floating TOC yet - am I missing something?

Also, just realizing this issue could be split into two
1. Implement TOC in gatsbyjs.org
2. Write a doc that explains how to implement TOC on any site

Finally, have you submitted your starter to the starter library yet?

**Comment by shannonbux** [comment]
@johncmunson that would be excellent. @fk Do you think there would be enough whitespace in docs to implement something like this? This isn't necessarily a top priority, unless @johncmunson you want to work on it!

**Comment by fk** [comment]
@shannonbux Yep, I think starting from at around 1300px viewport width we should have enough whitespace.

**Comment by johncmunson** [comment]
Sounds pretty fun, I'll take a look this week and see what I come up with!

**Comment by shannonbux** [comment]
sounds great!

**Comment by fk** [comment]
Not stale!

**Comment by lannonbr** [comment]
@shannonbux, @marcysutton and I brainstormed on this today and we came up with some ideas on how we could implement this.

On large displays, we have room on the right side of the page to have a sticky section on the right side of the screen that we could have to notify people of their current place in the current document. Below I show how we will take the table of contents out of the normal flow of the document and into a sidebar-like area:

![Large Display TOC](https://user-images.githubusercontent.com/3685876/56622781-72e22580-65ff-11e9-950f-e4628ce7628c.png)

As well, on mobile, we could keep the TOC in the flow of the document but move it up to right under the main heading of the page:

![Mobile TOC](https://user-images.githubusercontent.com/3685876/56622880-c9e7fa80-65ff-11e9-8de4-795a311be822.png)

@fk we'd appreciate some feedback if this feels alright or if there may be a better way to display a table of contents on each form-factor.

**Comment by fk** [comment]
> if this feels alright 

💯, it does!

IMO for the first shot we don't even need to worry too much about making the ToC sticky when it's displayed as a "sidebar", although it'd be nice to have! FWIW here's something similar I did recently:

![image](https://user-images.githubusercontent.com/21834/56657115-84770c00-6697-11e9-8f82-a7a047febca9.png)

![image](https://user-images.githubusercontent.com/21834/56657261-dcae0e00-6697-11e9-8a93-13df67eb3b6e.png)

We now have `presets.letterSpacings` to help with styling the small caps ToC headline.

**Comment by janosh** [comment]
I just coded up a floating ToC very similar to what is being discussed here. You can [check it out in action here](https://janosh.io/blog/hmc-intro). [Here's the code](https://github.com/janosh/janosh.io/commit/1f02f5f26256dd9292dee5fb0fbcad2c24f0fe5e). It relies on #13972.

![floating-toc](https://user-images.githubusercontent.com/30958850/57572599-81f51000-7414-11e9-92e3-b062b1c9dcf3.png)

**Comment by marcysutton** [comment]
Some more information and success criteria from our specification doc:

A floating table of contents widget will help users contextualize where they are in a document, dynamically listing page sections and scrolling with them as they read.

The floating TOC should include a heading like “Table of Contents” to be consistent with the Gatsby Preview docs. It should also include a list of internal links to each of the h2, h3, and possibly h4 headings in the document (need to play around with this–it might be nice to make it configurable). All text colors should be evaluated to meet color contrast requirements (4.5:1 for smaller, non-bold text).

The widget could potentially leverage Remark plugins. It should live in the DOM source between the h1 heading and the article’s main body to allow it to float in the right column at large viewports and slide under the h1 heading on smaller viewports. 

## Acceptance Criteria
- As a user, I should be able to orient myself in a doc with a heading declaring a “Table of Contents” and a list of internal links to h2 and h3 headings
- As a sighted or moderately low-vision user, I should encounter adequate color contrast for headings and links
- As a screen reader user, I should recognize the table of contents as a `<nav>` element with a unique label. Inside I should find a heading and a list of contents.
    - Two techniques are to use aria-labelledby to point to the first heading’s ID or an aria-label directly on the element
- As a sighted user with a large viewport, I should see the table of contents follow my scroll position as I navigate through the page.
- As a sighted user with a smaller viewport, I should see the table of contents following the h1 heading.

**Comment by janosh** [comment]
Small update: The [above mentioned ToC implementation](https://github.com/gatsbyjs/gatsby/issues/6896#issuecomment-491526452) no longer relies on #13972 and now highlights the currently active section of the document. Also wrote a [short blog post about it](https://janosh.io/blog/sticky-active-smooth-responsive-toc).

[![toc](https://user-images.githubusercontent.com/30958850/59429698-38636080-8dd8-11e9-86e6-ee1497fd3e1b.png)](https://janosh.io/blog/sticky-active-smooth-responsive-toc)

**Comment by lannonbr** [comment]
So I'm going to take a dive into implementing this issue this weekend. If I can get a PR up, I'll likely be contacting @fk for some design advice so it fits into the current site design and @marcysutton to make sure it's accessible.

I will as well look into the implementations that @janosh did on his personal blog.

**Comment by gagan0723** [comment]
@lannonbr  `reactjs.org` does something like below gif on mobile devices.
![ScreenRecording2019-07-03at1](https://user-images.githubusercontent.com/6944095/60593205-8b5e8100-9da2-11e9-82fd-b7b1dd4df80c.gif)

**Comment by lannonbr** [comment]
@gagan0723 So we actually already have that functionality for the sidebar on mobile layouts in the various layouts to go between different pages. This issue is specifically for making a Table of Contents for different sections of a single page.

**Comment by janosh** [comment]
@lannonbr Significant parts of the [reactjs.org](https://reactjs.org) implementation could probably still be reused for in-page navigation.
