### ISSUE TITLE
Add "more" link to bottom of search results to link to dedicated search page

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#6898]
## Summary
From usability testing:
Algolia doesn't show all results if there are too many, and it doesn't pull information from headers. This makes it difficult to find things by searching.

This problem will only keep growing as www.gatsbyjs.org has more docs and more blogposts.

### Motivation

We are doing this because our docs are growing and the current small search results box doesn't have room to show all search results.

**Comment by KyleAMathews** [comment]
I vote for moving search to its own page where we can include a lot more results. In any case, let's reduce the number of open issues and close this.

**Comment by fk** [comment]
> I vote for moving search to its own page where we can include a lot more results.

👍
