### ISSUE TITLE
Featured docs dashboard

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#6904]
## Summary

From usability tests: people don't know a lot of docs exist, especially new ones.

Solution:
Perhaps do a featured docs dashboard.

### Basic example

Common topics that were little known: e-commerce, WP tutorials, how to create a plugin, how to pitch Gatsby, how to sign up for the newsletter

### Motivation

We're doing this because every new doc is created to resolve a pain point, and helping people know about the doc empowers them to solve problems and create more successful sites with Gatsby.

**Comment by lannonbr** [comment]
I believe this is still a good idea to eventually implement so I'm going to reopen this.

**Comment by KatieOfCode** [comment]
Hello! Would I be able to work on this?

**Comment by marcysutton** [comment]
Hey @KatieFujihara! I just saw your comment from back in February. This was an older issue that we dug back up as it sounded worthwhile, but we haven't had the resources to devote to it. The first step would be to do some planning around it and determine how this initiative would work, and then we could get to building it. If it's something you're still interested in, let us know!

**Comment by AishaBlake** [comment]
I still think this is worth doing. I've brought this issue up internally as we're planning some larger-scale website updates anyway!
