### ISSUE TITLE
v2 docs change - don't require explicit query names anymore

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#6911]
Write one paragraph explanation of this somewhere in "Querying with GraphQL" section of docs.

https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#explicit-query-names-no-longer-required (this is not a breaking change - just QoL change that we don't require explicit query names anymore)

Gatsby v2 doesn’t require explicit query names. You can skip them now:

```shell
export const query = graphql`
-  query ThisIsExplicitQueryName($slug: String!) {
+  query($slug: String!) {
    markdownRemark(fields: { slug: { eq: $slug } }) {
      html
      frontmatter {
        title
      }
    }
  }
```
You can also skip the `query` keyword if you don’t use query variables:

```shell
export const query = graphql`
-  query ThisIsAnotherExplicitQueryName {
+  {
    site {
      siteMetadata {
        title
      }
    }
  }
```
This isn’t a breaking change. Queries with explicit names will continue to work as they did in v1.

**Comment by m-allanson** [comment]
As examples have been updated already and this is mentioned in the migration guide, we probably don't need to document this specifically. 

It's generally not required in GraphQL, so we don't need to explain it's absense.
