### ISSUE TITLE
v2 docs change - import { Link } from "gatsby"

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#6913]
This is the change that should happen throughout docs per https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#import-link-from-gatsby

```shell
import React from "react"
- import Link from "gatsby-link"
+ import { Link } from "gatsby"
```

**Comment by shannonbux** [comment]
Wondering if there's a faster way to do these edits in the future @jlengstorf? Such as keeping all our code examples somewhere that gets tested or updated automatically against master?

**Comment by shannonbux** [comment]
#6122 might make it easy for people to update their code for a change like this one!

**Comment by jlengstorf** [comment]
A codemod is definitely possible, if we can find someone to write it. 😅

**Comment by KyleAMathews** [comment]
@jquense already did! #6122 needs merged and published.

@shannonbux that's what #6122 does actually, is automatically make code changes.

**Comment by m-allanson** [comment]
The docs are updated for this. There are a couple of examples and plugins that still import from "gatsby-link"

**Comment by shannonbux** [comment]
@m-allanson should I create an issue for examples and plugins specifically
and then close this issue?

**Comment by jlengstorf** [comment]
@shannonbux The docs are fully updated (just checked on this before I saw @m-allanson already did it, so we’re _doubly sure_ that this is done). 😄 

It looks like someone has already updated all the example sites and packages as well, so I think it's safe to close this without opening additional issues.

**Comment by m-allanson** [comment]
There's a few stray Links around, search `from "gatsby-link"` to catch them.
