### ISSUE TITLE
We should add better documentation about custom components to Gatsby docs

### ISSUE THREAD

**Issue by calcsam** [gatsbyjs/gatsby#6917]
## Summary

Add documentation around custom components

### Motivation

A lot of people want to add components inline alongside text, and as @JanoshRiebesell alluded to in #6810, we don't have a lot of documentation around how to do this. 

It would be good to get that in the official docs hierarchy -- it's difficult to discover the [example page](https://using-remark.gatsbyjs.org/custom-components/).

We could reference the [.mdx work](https://github.com/ChristopherBiscardi/gatsby-mdx) being done by @ChristopherBiscardi and @avigoldman as well. 

cc @shannonbux

**Comment by shannonbux** [comment]
ok, so the request is to create a stub article for this?

**Comment by kamranayub** [comment]
Yes please. For example, the example talks about a simple component but doesn't show how to do a more complex `children` and have it render also with Markdown:

```
<custom-component>
This `should` also be **formatted** and run through the same plugins
</custom-component>
```

I am guessing I may need to call `remark` directly inside the component? I'm still not sure how to support this.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
