### ISSUE TITLE
Consider including resolve-url-loader by default for importing SASS node modules

### ISSUE THREAD

**Issue by JLongley** [gatsbyjs/gatsby#692]
I encountered a problem when trying to include [gutenberg](https://github.com/matejlatin/Gutenberg) web typography in my project.

```
ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./stylesheets/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../../assets/images/grid-icons.png
```

The issue was due to a relative path in the SASS in the module, and the solution is to include another loader, as per:
https://github.com/webpack/webpack/issues/2771

I have gotten around this issue by manually including the loader per the gatsby documentation:

```
exports.modifyWebpackConfig = function(config, stage) {
  config._loaders.sass.config.loaders = [ 'style', 'css', 'postcss', 'resolve-url-loader', 'sass-loader?sourceMap' ];

  return config
}
```

I’m mentioning all of this in case anyone else runs into a similar issue.  It seems as if importing sass modules is a common enough use case that we could consider including this loader by default.

**Comment by KyleAMathews** [comment]
Adding this extra loader to core sounds reasonable as long as it doesn't break anything. I'm not super familiar with Sass so would need to rely on y'all for this.

**Comment by aendrew** [comment]
Easy workaround for the moment is to append `node_modules/` to the import path.

**Comment by borekb** [comment]
In Gatsby v1.9.277, this snippet works for me:

```js
// gatsby-node.js:
exports.modifyWebpackConfig = function(config, stage) {
  if (config.config._loaders.sass.config.loaders) {
    config.config._loaders.sass.config.loaders.splice(
        config.config._loaders.sass.config.loaders.length - 1,
        0,
        'resolve-url-loader'
    );
  }
  return config;
}
```

Note that sourceMap _must_ be enabled:

```js
// gatsby-config.js:
module.exports = {
  plugins: [
    {
      resolve: `gatsby-plugin-sass`,
      options: {
        precision: 8,
        sourceMap: true,
      },
    },
  ],
}

```
