### ISSUE TITLE
Inconsistent / incomplete internal Node data structure

### ISSUE THREAD

**Issue by lightstrike** [gatsbyjs/gatsby#6921]
I'm exploring how to do some data transformation on Gatsby nodes using the `onCreateNode` hook for the `gatsby-source-wordpress` plugin. I'm finding that the [internal Node data structure documented](https://next.gatsbyjs.org/docs/node-interface/) is different from what I'm observing: 

```js
{
  type: 'SitePage',
  contentDigest: '5e06d7f4cf28e1f0498cb2fa52539086',
  description: 'Your site\'s "gatsby-node.js"',
  owner: 'internal-data-bridge'
}
```

I'm specifically trying to transform WordPress media nodes. I believe the internal type should be `wordpress__wp_media` for these nodes but only nodes with type `SitePage` are being logged within `onCreateNode`.

I'm trying this with `gatsby: 2.0.0-beta.20` and `gatsby-source-wordpress:  3.0.0-beta.5`

**Comment by KyleAMathews** [comment]
Are you sure any WordPress nodes are being created?

**Comment by lightstrike** [comment]
Yes they [are created here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/normalize.js#L572), which is called within [`sourceNodes`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/gatsby-node.js#L154) in `gatsby-node`.

I can query all the WordPress nodes within graphQL, they aren't surfacing within `onCreateNode` though.

**Comment by lightstrike** [comment]
Looking at this again, internal structure is good, so I'm closing :smile:
