### ISSUE TITLE
[gatsby-plugin-netlify] allPageHeaders option not working

### ISSUE THREAD

**Issue by stripeyjumper** [gatsbyjs/gatsby#6925]
## Description

The `allPageHeaders` option for gatsby-plugin-netlify is not writing headers to the `./public/_headers` file on build.

It looks like the problem is here:
https://github.com/gatsbyjs/gatsby/blob/d4c339e193296d6da0e2bbba8969a20023b27f6c/packages/gatsby-plugin-netlify/src/build-headers-program.js#L183-L190

The pages collection is an instance of Map, and lodash reduce doesn't iterate over its keys.  I'm happy to submit a pull request if you'd like.

I've reproduced the issue here:
https://github.com/stripeyjumper/gatsby-netlify-bug-demo

### Steps to reproduce

Add a link header to the `allPageHeaders` option in `gatsby-config-js`. Run `gatsby build`.

### Expected result

The link header should be added to all the routes in the `./public/_headers` file

### Actual result

No link headers are added from allPageHeaders

### Environment

(I'm using WSL on Windows 10)

System:
OS: Linux 4.4 Ubuntu 16.04.4 LTS (Xenial Xerus)
CPU: x64 Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
Shell: 4.3.48 - /bin/bash
Binaries:
Node: 8.11.3 - /usr/bin/node
Yarn: 1.7.0 - /usr/bin/yarn
npm: 6.2.0 - /usr/bin/npm
npmPackages:
gatsby: ^2.0.0-beta.64 => 2.0.0-beta.64
gatsby-plugin-netlify: ^2.0.0-beta.4 => 2.0.0-beta.4
gatsby-plugin-react-helmet: next => 3.0.0-beta.4
npmGlobalPackages:
gatsby-cli: 1.1.58
gatsby: 1.9.273

### File contents (if changed)

`gatsby-config.js`:

```javascript
const catPicture = '/static/cat.jpg'

module.exports = {
  siteMetadata: {
    title: 'Gatsby Default Starter',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    {
      resolve: 'gatsby-plugin-netlify',
      options: {
        allPageHeaders: [`Link: <${catPicture}>; rel=preload; as=image;`],
      },
    },
  ],
}
```

`package.json`:

```javascript
{
  "name": "gatsby-netlify-bug-demo",
  "description": "Demo of problem with gatsby-plugin-netlify",
  "version": "1.0.0",
  "author": "Andrew Bain",
  "dependencies": {
    "gatsby": "^2.0.0-beta.64",
    "gatsby-plugin-netlify": "^2.0.0-beta.4",
    "gatsby-plugin-react-helmet": "next",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-helmet": "^5.2.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write '**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "prettier": "^1.13.7"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/rbv-andrewb/gatsby-netlify-bug-demo"
  }
}
```

`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by Chuloo** [comment]
hey @stripeyjumper good thing to point this out, have you tried fixing it? Do send in a PR. 👍

**Comment by KyleAMathews** [comment]
Makes sense! We changed some of the internal data structures in v2 and not all plugins apparently have gotten updated.
