### ISSUE TITLE
Word correction - 'listening' instead of 'listing' on port.

### ISSUE THREAD

**Issue by lb-** [gatsbyjs/gatsby#693]
Example error currently
`Unable to start Gatsby on port 8000 as there's already a process listing on that port.`

I suggest that this should be corrected to:
`Unable to start Gatsby on port 8000 as there's already a process listening on that port.`
'listening' instead of 'listing'

Happy to put a pull request through if this is ok for me to fix.

Found two instances of this, see code links below:

https://github.com/gatsbyjs/gatsby/blob/3792215f24b3b87d3fa5ecb5f37e57bad9ebf4c2/lib/utils/develop.js#L180

https://github.com/gatsbyjs/gatsby/blob/264873880f085a1b4a56aadb24c6ea8a4d9aee7c/lib/utils/serve-build.js#L38

**Comment by emilyaviva** [comment]
I believe a PR would be most welcome! 💯

**Comment by lb-** [comment]
Sweet. I'll get on ig

**Comment by lb-** [comment]
It*
