### ISSUE TITLE
How to purge outdated static data after incremental builds?

### ISSUE THREAD

**Issue by datakurre** [gatsbyjs/gatsby#6931]
With a CMS source plugin integration (which deleteNode support), when

* user accidentally publishes content prematurely
* `gatsby build`is triggered and version with published content is deployed
* user reverts their action
* incremental `gatsby build`is triggered and a new version is published

Expected behavior

* reverted content is absent in the new version

What really happens

* related HTML is removed/updated, but static JSON blobs and possible image can still be found below `./static` (they are not re-created, but not removed either)

Is this intended behavior? Is there other option than "clean build" to remove outdated blobs from static?

**Comment by KyleAMathews** [comment]
It is the intended behavior as there's people can be running older versions of a site and expect to be able to access resources from previous builds. If you're deploying a site often, then you'll definitely trip up visitors to your site.
