### ISSUE TITLE
Gatsby 1.0 on windows

### ISSUE THREAD

**Issue by g8tguy** [gatsbyjs/gatsby#694]
You have to decide whether gatsby 1.0 would be targeting windows platforms.
Right now it is not!

I can compile the main project and its modules.   `lerna run build` is working OK!
but when running  `gatsby develop` it constantly crashes:

error from  `https://github.com/KyleAMathews/keystone/tree/add-website/www`
![untitled](https://cloud.githubusercontent.com/assets/22907656/23243868/83768bc2-f9a3-11e6-9afe-17c7385cf0ed.jpg)

error from `https://github.com/gatsbyjs/gatsby/tree/1-blog-update/www`
![untitled](https://cloud.githubusercontent.com/assets/22907656/23243892/b06b082e-f9a3-11e6-8edb-861ffc055ddc.jpg)

**Comment by KyleAMathews** [comment]
There's been no decision to not target windows! I'm merely developing on my
Mac so am not actively seeking problems that might develop.

Would be a great help if you could debug and send PRs to fix these and any
other issues you find!

**Comment by fabien0102** [comment]
I'm working on it -> https://github.com/gatsbyjs/gatsby/pull/781

Gatsbygram works on windows perfectly, and `/www` (docs/blog) partially works

Remaining know issues:
- contributing.md is not parsed
- blog images are not copy/serve
- sometime sharp is not correctly compiled (just reinstall alone and it's works)

If someone find others issues, please tell me in this topic, I really want to play with gatsby 1.0 and I'm a work on Windows 😄

**Comment by fabien0102** [comment]
#781 Merged! I think we can close this issue 😃

**Comment by KyleAMathews** [comment]
Yup!
