### ISSUE TITLE
Add support for relative links with @reach/router

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#6945]
Currently this doesn't work due to how we render routes. This seems like something that can be fixed.

**Comment by kakadiadarpan** [comment]
@KyleAMathews is this issue fixed?

**Comment by Mike-Dax** [comment]
@kakadiadarpan I just noticed this issue when upgrading from one of the beta releases to v2.0.6.

**Comment by KyleAMathews** [comment]
No this is still a problem actually /cc @ryanflorence

**Comment by Mike-Dax** [comment]
This is still an issue.

**Comment by sgnl** [comment]
bump to keep alive

**Comment by sgnl** [comment]
Not exactly sure if this is on topic because the description is a little vague but...

:heavy_check_mark: I'm **able** to implement relative links if I use Link from `'@reach/router'`

:bug: I'm **unable** to implement relative links when using Link from `'gatsby'`

**Comment by bryndyment** [comment]
This is still an issue.

**Comment by ryami333** [comment]
Is using `@reach/router` within a gatsby app "allowed"? Because this solves this problem for our use-case, but I'm not sure what the wider implications are.

**Comment by lucletruc** [comment]
Still an issue!

**Comment by agentofuser** [comment]
Related: https://github.com/gatsbyjs/gatsby/issues/14161

**Comment by devuxer** [comment]
If this isn't something that can be fixed soon, could there at least be a sentence in the [docs](https://www.gatsbyjs.org/docs/gatsby-link/) saying that relative links are not supported? Having ported over some code from @reach/router, I was completely mystified why relative links were not working.

**Comment by patspam** [comment]
Just wasted an hour on this - a note in the doc would be much appreciated by the next N people who run into this..

**Comment by sidharthachatterjee** [comment]
@ascorbic added support for this in https://github.com/gatsbyjs/gatsby/pull/24054 🎉

**Comment by guillaumebriday** [comment]
@KyleAMathews @ascorbic Hey!

I think this PR has broken the Link behaviour. I got something like that in a component:

```jsx
<Link to={post.fields.slug}>
  {post.frontmatter.title}
</Link>
```

This link is under the page `/articles` and the `post.fields.slug` is just a string.

Before it was rendered as (excepted result):

```html
<a href="/my-slug">
```

and now (wrong):

```html
<a href="/articles/my-slug">
```

I think many sites will be affected by this modification.

How could we fix it? Thank you in advance

**Comment by ascorbic** [comment]
@guillaumebriday I'm guessing the slug doesn't start with a slash? That means it's a relative link, so this is expected behaviour. Previously it would have given you a warning as it was unsupported, even if it happened to work. You can get the correct behaviour in your case by adding a slash to the start of the link.

**Comment by guillaumebriday** [comment]
@ascorbic It doesn't. I use `allMarkdownRemark` with the createFilePath method from `gatsby-source-filesysteme` to generate a slug field.

By default it does not prefix with a slash.

I fixed it in https://github.com/guillaumebriday/guillaumebriday.fr/commit/36d1848f3fe931ce74dacdd83c451a9698542cce

But I think there are plenty of applications with this behavior.

Anyway, thanks for the help 🙏

**Comment by drake-smith** [comment]
Per https://www.gatsbyjs.com/docs/gatsby-link/ I should be able to pass a slug `../page` to `<Link>` and have it render the proper relative link. Instead `<Link>` is stripping the `..` and rendering `/page` and so it is not properly allowing for a relative path. 

Gatsby version: `"gatsby": "^2.23.12",`
