### ISSUE TITLE
Propose Gatsby to Who's using Lerna?

### ISSUE THREAD

**Issue by wdavidw** [gatsbyjs/gatsby#6948]
On the homepage of [Lerna](https://lernajs.io/), there is a section called "Who's using Lerna?". Gatsby is not yet listed. Do you want to suggest Gatsby to this section ?

**Comment by KyleAMathews** [comment]
Hey sure! Feel free to PR that.

**Comment by wdavidw** [comment]
done lerna/lerna#1531
