### ISSUE TITLE
Add REPL to Gatsby develop

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#6952]
We've discussed/tried ways to look at gatsby data e.g. redux devtools. But the simplest would be to just allow people to flip to a node repl that has access to all the Gatsby data. This would be fun for checking out data plus running code over data for analysis.

Inspired by https://twitter.com/patrickc/status/1024318691863744512?s=19

**Comment by KyleAMathews** [comment]
Possibly could add this to the build where the build runs and then drops into repl at the end.

**Comment by KyleAMathews** [comment]
We could also include useful commands like pushing the site state to a pastebin or whatever for debugging purposes. Which would be great for issues here.

**Comment by Joshfindit** [comment]
I'll revel in REPLs all day every day

**Comment by kkemple** [comment]
Here is something I used when making an API in the past, not sure if useful or not but thought I'd share :: https://github.com/kkemple/jasper-api/blob/master/src/repl/index.js

You can then run this in node via a bin script which would make it easy to do something like `gatsby repl` and have that start up a context-aware repl.

**Comment by KyleAMathews** [comment]
ooo yeah, a new command could be useful too. It'd do the normal bootstrap and then drop you into the repl
