### ISSUE TITLE
[ gatsby-image ] resolutions( height ) creates a cropped image

### ISSUE THREAD

**Issue by schwiet** [gatsbyjs/gatsby#6954]
## Description

Using `height` with `resolutions` causes cropped image, while `width` does not. Documentation states that using _both_ will cause cropping.

### Steps to reproduce

In my case, using:

```
img {
    childImageSharp {
        resolutions( height: 400 ) {
            ...GatsbyImageSharpResolutions
```
For a source image that is 710px by 800px produces a slightly down-scaled, partially cropped image. In this case, for some reason, the image will only be scaled down until it reaches a width of 400px and then it is cropped, so the image generated by the above query is 400px by 400px with it's height cropped. If I run the same query but with `width: 355`, the result is an image that is 355px by 400px as expected.

### Expected result

The resulting image should be scaled in the same manner as when `width` is used, right? 

### Actual result

An arbitrary scale limit (of 400px in my case) in the width dimension is enforced.

### Environment

```  System:
    OS: macOS Sierra 10.12.2
    CPU: x64 Intel(R) Core(TM) i7-3770S CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 61.0.1
    Safari: 10.0.2
  npmPackages:
    gatsby: ^1.9.277 => 1.9.277 
    gatsby-image: ^1.0.55 => 1.0.55 
    gatsby-link: ^1.6.46 => 1.6.46 
    gatsby-plugin-catch-links: ^1.0.24 => 1.0.24 
    gatsby-plugin-feed: ^1.3.25 => 1.3.25 
    gatsby-plugin-google-analytics: ^1.0.31 => 1.0.31 
    gatsby-plugin-manifest: ^1.0.27 => 1.0.27 
    gatsby-plugin-nprogress: ^1.0.11 => 1.0.14 
    gatsby-plugin-offline: ^1.0.18 => 1.0.18 
    gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11 
    gatsby-plugin-sharp: ^1.6.48 => 1.6.48 
    gatsby-plugin-sitemap: ^1.2.25 => 1.2.25 
    gatsby-plugin-twitter: ^1.0.16 => 1.0.20 
    gatsby-plugin-typography: ^1.7.19 => 1.7.19 
    gatsby-remark-autolink-headers: ^1.4.19 => 1.4.19 
    gatsby-remark-copy-linked-files: ^1.5.37 => 1.5.37 
    gatsby-remark-images: ^1.5.67 => 1.5.67 
    gatsby-remark-prismjs: ^1.2.24 => 1.2.24 
    gatsby-remark-responsive-iframe: ^1.4.20 => 1.4.20 
    gatsby-source-filesystem: ^1.5.39 => 1.5.39 
    gatsby-transformer-remark: ^1.7.44 => 1.7.44 
    gatsby-transformer-sharp: ^1.6.27 => 1.6.27
```

Thanks

**Comment by elrumordelaluz** [comment]
I think the point is that `gatsby-plugin-sharp` set a _default_ [width](https://github.com/gatsbyjs/gatsby/blob/001158ebe5725eed045fd8439c05e8abbc5916e7/packages/gatsby-plugin-sharp/src/index.js#L65) and [expects](https://github.com/gatsbyjs/gatsby/blob/001158ebe5725eed045fd8439c05e8abbc5916e7/packages/gatsby-plugin-sharp/src/index.js#L116-L124) only an optional `height` arg.

If instead of passing the default value, you let [`undefined` or `null`](http://sharp.dimens.io/en/stable/api-resize/#parameters) the behaviour should be what you are expecting.

**Comment by danielberndt** [comment]
Related issue: #6752 

And @elrumordelaluz: given the [current option handling](https://github.com/gatsbyjs/gatsby/blob/af2b27e7cf7359828dcdf5d4b2be659ffd191082/packages/gatsby-plugin-sharp/src/index.js#L64-L87) it seems like width is expected to be set.

**Comment by elrumordelaluz** [comment]
yes @danielberndt and absolutely agree on 
> For a more consistent behaviour It would be really nice to only use the fallback width of 400 if no height and no width has been set.

**Comment by danielberndt** [comment]
fyi, I just created this PR #6970 to resolve this issue :)
