### ISSUE TITLE
Creating no-cache option for gatsby develop

### ISSUE THREAD

**Issue by lightstrike** [gatsbyjs/gatsby#6959]
It is sometimes helpful when working on a Gatsby project to not use cache. As far as I know, this development workflow currently requires `rm -rf .cache` prior to each time `gatsby develop` is run. Having an option such as `gatsby develop --no-cache` would be nice.

How possible would it be to add this functionality? Could it be done through a plugin or changing core?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
