### ISSUE TITLE
What's a good way to include an external JS file?

### ISSUE THREAD

**Issue by ivanakimov** [gatsbyjs/gatsby#696]
Trying to add this: https://github.com/rishabhp/bideo.js (which has no npm module)
Where do I put it so it gets bundled?

**Comment by KyleAMathews** [comment]
Just require it. It doesn't look like it has any exports so copy it into your site and require it into your _template.js

**Comment by ivanakimov** [comment]
Could you give an example? I'm just getting `Module not found: Error: Cannot resolve module 'bideo'`. Is this because it doesn't export anything?

**Comment by ivanakimov** [comment]
Nvm, I got it. Thank you @KyleAMathews.

**Comment by ivanakimov** [comment]
@franva this is not the same thing. I was requiring a file within my own project. If you want to include the Google Maps API, you're gonna have to use a `<script>` tag: <https://developers.google.com/maps/documentation/javascript/examples/map-simple>

**Comment by franva** [comment]
Hi @ivanakimov I tried that way as well, but no luck. Here is my question:
  https://stackoverflow.com/questions/50274502/load-google-place-api-in-gatsbyjs-reactjs-project
