### ISSUE TITLE
Create static pages based on WPML translation

### ISSUE THREAD

**Issue by jarekpelczynski** [gatsbyjs/gatsby#6961]
I want to create pages structure based on translation on WPML.
For example, I want to create a static page `/about` for default languages **and**`/:lang/about` for other languages.

Every page has `wpml_translations` with the ID of the translated page, but how can I get these pages (by ID) and add to the nodes? 

I would be grateful if you could help me :)

--------------
UPDATE:
I've figured out, that `gatsby-source-wordpress` doesn't fetch translations which I need it. I think I could add option to plugin (e.g. `{ translation: ['de', 'fr', ...] }`) and extend it in order to fetch translations.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by cardiv** [comment]
There is a [PR](https://github.com/gatsbyjs/gatsby/pull/10942) for adding custom routes. This includes fetching full WPML translations.

Hope this get merged soon.
