### ISSUE TITLE
[v2] url-loader for miscAssets? (webpack-utils.js)

### ISSUE THREAD

**Issue by zauni** [gatsbyjs/gatsby#6963]
## Summary

A small PDF file gets a base64 encoded URL, whereas in gatsby v1 it got a normal hashed URL.

## Relevant information

In [webpack-utils.js](https://github.com/gatsbyjs/gatsby/blob/001158ebe5725eed045fd8439c05e8abbc5916e7/packages/gatsby/src/utils/webpack-utils.js#L239-#L258) you define the url-loader for the loaders.file object and use it for audio, video and pdf files [here](https://github.com/gatsbyjs/gatsby/blob/001158ebe5725eed045fd8439c05e8abbc5916e7/packages/gatsby/src/utils/webpack-utils.js#L355-L360)

Is this wrong and it should be the normal file-loader (which is not producing base64 encoded urls) or is this the expected behavior and I should change my webpack config in the gatsby-node.js file to get the v1 behavior?

In my code is something like this:

```js
import downloadPdf from '../../assets/downloads/file.pdf';

<a href={downloadPdf} target="_blank">Download</a>
```

In gatsby v1 the URL is like this: `/static/file.a01dde10.pdf`.  
In gatsby v2 the URL is like this: `data:application/pdf;base64,JVBERi0xLjYNJeLjz9...lRU9GDQo=`

Thanks for any help or explanation!

**Comment by colbyfayock** [comment]
having the same issue, though i was thinking it was going to be fixed in https://github.com/gatsbyjs/gatsby/pull/6661 from issue https://github.com/gatsbyjs/gatsby/issues/5998. wasn't sure if it hadnt made it to the most recent build or something

**Comment by KyleAMathews** [comment]
Yeah — PDFs shouldn't ever be inlined.

**Comment by KyleAMathews** [comment]
Anyone want to update the webpack config for this?

**Comment by zauni** [comment]
Thanks for your feedback! I will try to make a pull request.
