### ISSUE TITLE
cannot find file with backslash path in pages subdir

### ISSUE THREAD

**Issue by chenvan** [gatsbyjs/gatsby#697]
my file structural is

pages/
  blog/
     3-4-3让红军涅槃重生.md

![qq 20170225213650](https://cloud.githubusercontent.com/assets/7885757/23331514/82ac6be8-fba2-11e6-83ac-97e35a283bb3.png)

I try to change the file name to others, it work.

I think the '\\' in path  './blog\\3-4-3让红军涅槃重生.md'  cause the problem, but I don't kown how to prove it

**Comment by KyleAMathews** [comment]
You can see a list of all your routes with their paths by adding a
console.log(this.props) to your _template.js

**Comment by chenvan** [comment]
@KyleAMathews I find the problem. It's from create-routes.js.

![qq 20170228124959](https://cloud.githubusercontent.com/assets/7885757/23392039/033fb5fe-fdb4-11e6-8d8b-58f2927eba21.png)

I just add the highlight sentence, replace the backslash to slash. It's a dummy solution. Hope you can find a better one.

**Comment by KyleAMathews** [comment]
@NogsMPLS does this look like a windows issue to you?
