### ISSUE TITLE
Cache headers for static images

### ISSUE THREAD

**Issue by sheelah** [gatsbyjs/gatsby#6971]
This is for Gatsby v1.  I noticed [the docs say that all files in `public/static` should be cached forever](https://www.gatsbyjs.org/docs/caching/#static-files). 

What's the recommendation on appropriate cache headers for images that have been added directly to the `static/` folder via the [Gatsby escape hatch method](https://www.gatsbyjs.org/docs/adding-images-fonts-files/#using-the-code-classlanguage-textstaticcode-folder), which means they live outside the module system?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
