### ISSUE TITLE
Gatsby command Not Found on Deploy

### ISSUE THREAD

**Issue by bhankee** [gatsbyjs/gatsby#6972]
## Summary
Been searching for an answer more then a day but after following deploy instructions for Netlify getting the following logs and Gatsby command not found.

## Relevant information
LOGS:
12:29:08 PM: Starting build script
12:29:08 PM: Installing dependencies
12:29:09 PM: v8.11.3 is already installed.
12:29:09 PM: Now using node v8.11.3 (npm v5.6.0)
12:29:10 PM: Attempting ruby version 2.3.6, read from environment
12:29:12 PM: Using ruby version 2.3.6
12:29:12 PM: Using PHP version 5.6
12:29:12 PM: Started restoring cached go cache
12:29:12 PM: Finished restoring cached go cache
12:29:12 PM: unset GOOS;
12:29:12 PM: unset GOARCH;
12:29:12 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.10.linux.amd64';
12:29:12 PM: export PATH="/opt/buildhome/.gimme/versions/go1.10.linux.amd64/bin:${PATH}";
12:29:12 PM: go version >&2;
12:29:12 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.10.linux.amd64.env';
12:29:12 PM: go version go1.10 linux/amd64
12:29:12 PM: Installing missing commands
12:29:12 PM: Verify run directory
12:29:12 PM: Executing user command: gatsby build
12:29:12 PM: /usr/local/bin/build: line 32: gatsby: command not found
12:29:12 PM: Caching artifacts
12:29:12 PM: Started saving pip cache
12:29:12 PM: Finished saving pip cache
12:29:12 PM: Started saving emacs cask dependencies

### Environment (if relevant)
MAC and Netlify

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.2.0 - /usr/local/bin/node
    Yarn: yarn install v0.27.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 34.53s. - /usr/local/bin/yarn
    npm: 5.3.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 57.0.4
    Safari: 11.1.2
  npmPackages:
    gatsby: ^1.9.247 => 1.9.250
    gatsby-link: ^1.6.40 => 1.6.40
    gatsby-plugin-react-helmet: ^2.0.10 => 2.0.10
    gatsby-plugin-sass: ^1.0.26 => 1.0.26
  npmGlobalPackages:
    gatsby-cli: 1.1.58

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by MaxMcKinney** [comment]
What is your Netlify command setup for the build process? 

Do you have a link to the repo you are using?

**Comment by bhankee** [comment]
@MaxMcKinney  I am using the "Gatsby Build" for the command. 

Link to repo:  AND THANKS  [REPO HERE](https://github.com/bhankee/Portfolio_Gatsby/tree/master/portfolio)

**Comment by MaxMcKinney** [comment]
Hmm, try removing your public folder from the repo (and making sure that's in your gitignore, you don't need the public folder in the repo). Then in Netlify try making a new project with the repo link and it should automatically fill in the same build command you were using, if it does this correctly you know it's detected the correct build platform. 

All I can think of currently is an issue with Netlify not detecting things.

**Comment by anantoghosh** [comment]
change your build command to `npm run build` instead

**Comment by Chuloo** [comment]
Can't find the repro @bhankee, throwing 404. Could be related to #6844.  `gatsby: command not found` this could mean that `gatsby` was not installed properly see #6834 and a workaround on local was to use `yarn`.

**Comment by kakadiadarpan** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub issues, we have to clean some of the old issues as many of them have already been resolved with the latest updates.

Please make sure to update to the latest Gatsby version and check if that solves the issue. Let us know if that works for you by adding a comment 👍

**Comment by kakadiadarpan** [comment]
This issue is being closed because there hasn't been any activity for at least 30 days. Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem 👍
