### ISSUE TITLE
How to add a deprecation warning to a plugin?

### ISSUE THREAD

**Issue by lightstrike** [gatsbyjs/gatsby#6974]
I'd like to include some deprecation warnings in a PR I'm working on for `gatsby-source-wordpress` -- it seems like [`onPreInit`](https://next.gatsbyjs.org/docs/node-apis/#onPreInit) could be a good place to check user-specified configuration options, but it's not clear to me if the config options are available [to this step](https://github.com/gatsbyjs/gatsby/blob/96f142897439fa0348e1213804fbf2831c17dd6b/packages/gatsby/src/bootstrap/index.js#L98). How can I achieve something like the following:

```js
const report = require(`gatsby-cli/lib/reporter`)

exports.onPreInit = async ( { userConfig } ) => {
  if (userConfig.useACF) {
    report.warn(
      `ACF functionality will be removed from gatsby-source-wordpress v4. Please migrate to gatsby-wordpress-acf.`
    )
  }
}  
```

**Comment by Chuloo** [comment]
Hi, @m-allanson is this something you can help with?

**Comment by m-allanson** [comment]
👍 @lightstrike, `pluginOptions` should get passed in as the second argument. 

Here's an example from `gatsby-transformer-screenshot` that uses `pluginOptions` at the `onPreBootstrap` stage, which happens just after `onPreInit`:

https://github.com/gatsbyjs/gatsby/blob/bf3208ddc02c240302fff5b112343d715c69a0ca/packages/gatsby-transformer-screenshot/src/gatsby-node.js#L24-L27

There's a tutorial that runs through this in more detail at https://next.gatsbyjs.org/docs/source-plugin-tutorial/. I thought we had an issue for improving the API docs but having trouble finding it right now..
