### ISSUE TITLE
Script dangerouslySetInnerHTML being overwritten in production via Netlify ONLY on size < 1024px

### ISSUE THREAD

**Issue by brmi** [gatsbyjs/gatsby#6979]
## Summary
I have a Klaviyo script in my html.js file like this. The script populates a div I have set in my footer component: 

`<div className="klaviyo-form-KEY"></div>
`
```
<script
            dangerouslySetInnerHTML={{
              __html: `
                var __klKey = __klKey || 'APIKEY';
                (function() {
                var s = document.createElement('script');
                s.type = 'text/javascript';
                s.async = true;
                s.src = '//static.klaviyo.com/forms/js/client.js';
                var y = document.getElementsByTagName('script');
                var x = y[y.length - 1];
                x.parentNode.insertBefore(s, x);
                })();
              `
            }}
          />
        </body>
      </html>
```

Everything works perfectly on local ((all screen sizes)), and even on running the build site via gatsby serve, but for some reason on the production site via netlify on window sizes >1024px, I see that the div is being populated and then the contents are being deleted/overwritten. How can I stop this from happening?

`gatsby-config.js`: 

```
module.exports = {
  plugins: [
    `gatsby-transformer-yaml`,
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-sass`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `./src/data/`,
      },
    },
    {
      resolve: 'gatsby-plugin-react-svg',
      options: {
        include: /assets/
      }
    },
    {
      resolve: `gatsby-plugin-netlify`,
      options: {
        mergeLinkHeaders: false,
        mergeCachingHeaders: false
      },
    },
  ],
};
```

`package.json`: 

```
{
  "name": "gatsby-starter-hello-world",
  "description": "Gatsby hello world starter",
  "license": "MIT",
  "scripts": {
    "develop": "gatsby develop",
    "build": "gatsby build",
    "serve": "gatsby serve"
  },
  "dependencies": {
    "gatsby": "^1.9.250",
    "gatsby-cli": "^1.1.58",
    "gatsby-link": "^1.6.40",
    "gatsby-plugin-netlify": "^1.0.19",
    "gatsby-plugin-react-helmet": "^2.0.11",
    "gatsby-plugin-react-svg": "^1.1.1",
    "gatsby-plugin-sass": "^1.0.26",
    "gatsby-source-filesystem": "^1.5.36",
    "gatsby-transformer-yaml": "^1.5.17",
    "gridlex": "^2.7.1",
    "html-react-parser": "^0.4.6",
    "react-helmet": "^5.2.0",
    "react-slick": "^0.23.1",
    "react-tabs": "^2.2.2",
    "slick-carousel": "^1.8.1",
    "svg-react-loader": "^0.4.5"
  }
}

```

`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A 

I can see the div get populated and then the next second it disappears/get overwritten. 

I tried setting the script to defer=true but it did not help. 

One last thing, sometimes the script works and the div is populated perfectly! This only happens on first load after deploying the site or waiting about ~10 minutes until I refresh the page. After the first refresh, the div is again empty.

**Comment by PatrykTies** [comment]
Hi, i have similar issue now, how did you solve it? or did you not ?

**Comment by brmi** [comment]
@PatrykTies In one of my components I had a resize function that was causing the site to rerender. I took it out and then it worked!
