### ISSUE TITLE
[gatsby-transformer-sharp] Do not rely on npm flattening

### ISSUE THREAD

**Issue by Andarist** [gatsbyjs/gatsby#6985]
## Description

This transformer has peer dependency on `gatsby-plugin-sharp` which in turn has dependencies on things like `sharp`, `potrace` etc but the transformer also requires them - relying on the fact that most likely those deps will be installed as siblings to both plugin-sharp & transformer-sharp - this is not guaranteed though.

### Steps to reproduce

It's hard to describe exact steps to reproduce, we have problems with this in monorepo setup.

### Expected result

`gatsby-transformer-sharp` should use only require it's explicit dependencies (or peers). 

### Actual result

Somewhat described in description - sharp and others were installed by npm into `gatsby-plugin-sharp/node_modules` and thus can't be find by `gatsby-transformer-sharp` and it crashes.

### Environment

Irrelevant

### File contents (if changed)

No changes.

**Comment by Chuloo** [comment]
hi @Andarist whilst your issue is clearly understood, can you provide a minimal reproduction repo of your code showing the `gatsby-transformer-sharp` crash? Pointers on how to reproduce the crash would be sufficient too.

**Comment by KyleAMathews** [comment]
It seems like the solution is to just add all of gatsby-transformer-sharp's dependencies to its `package.json`? Could you do a PR for that @Andarist?

**Comment by Andarist** [comment]
> hi @Andarist whilst your issue is clearly understood, can you provide a minimal reproduction repo of your code showing the gatsby-transformer-sharp crash? Pointers on how to reproduce the crash would be sufficient too.

Because of the nature of the issue and out complex-ish monorepo setup it seems to me that it would be counter productive to slim it down, because the issue itself seems like a straightforward one.

> It seems like the solution is to just add all of gatsby-transformer-sharp's dependencies to its package.json?

Yeah, I believe this is a proper solution. 

> Could you do a PR for that @Andarist?

Not sure how `gatsby-transformer-sharp` interacts with `gatsby-plugin-sharp`, is peerDep on the latter solving any issues? Maybe it could be a regular dependency too?

I'm also a little bit concerned that other packages in the monorepo might suffer from the same thing. It would need the investigation though.

**Comment by KyleAMathews** [comment]
You use `peerDependencies` when you want the user to have control over what version of a package is installed.

In this case, no user would care about the dependencies of `gatsby-transformer-sharp` so we just need to make sure all of its dependencies are listed in its package.json.
