### ISSUE TITLE
The links in tutorial page doesn't work

### ISSUE THREAD

**Issue by whs-dot-hk** [gatsbyjs/gatsby#6990]
## Description
The links in
https://next.gatsbyjs.org/tutorial/
doesn't work

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue.

Try click on any parts of the tutorial

### Expected result

What should happen?

### Actual result

What happened.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by KyleAMathews** [comment]
Which links? In the sidebar? I just clicked through those without any trouble.

**Comment by whs-dot-hk** [comment]
In the content area

![screenshot_2018-08-03 gatsby js tutorial gatsbyjs](https://user-images.githubusercontent.com/35202375/43651294-8abcfe14-9774-11e8-8c41-4ee279b37380.png)

It doesn't work for any of the links under h1 tag, also other pages

**Comment by KyleAMathews** [comment]
Hmmm ok, can confirm. It looks like gatsby-plugin-catch-links isn't working any longer

**Comment by AniaMakes** [comment]
@KyleAMathews It's the links in the main body of text; I am having the same issue. I can right-click and open in new tab just fine, but clicking on, for example, "Set Up Your Development Environment" doesn't do anything. Maybe a result of a stray preventDefault() ?

I was tracking Network logs and there appears to be a query to woopra made every few seconds. Is this something deliberate?

**Comment by youngboy** [comment]
I think this is regression bug cause by https://github.com/gatsbyjs/gatsby/pull/6866

```javascript
    var anchoreUrl = new URL(anchor.getAttribute(`href`))
```

according to [URL API](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) it says
> url, A USVString representing an absolute or relative URL. If url is a relative URL, base is required, and will be used as the base URL. If url is an absolute URL, a given base will be ignored.

so replace this line to 

```javascript
    var anchoreUrl = new URL(anchor.href)
```

will resolve the issue I think

**Comment by KyleAMathews** [comment]
@youngboy ah nice! Could you create a PR for this? Then I'll merge/release it so we can get thing working again.
