### ISSUE TITLE
ACF Repeater Field not showing data in Gatsby

### ISSUE THREAD

**Issue by omattman** [gatsbyjs/gatsby#6995]
I'm currently working on a website using the ACF Repeater Field and I can gain access to the data through the following graphql query:

```
{
  wordpressWpArtist(slug: { eq: "joey-moe" }) {
    acf {
      beskrivelse {
        titel_label
        titel
        indhold
      }
    }
  }
}

```
Which returns:
```
{
  "data": {
    "wordpressWpArtist": {
      "acf": {
        "beskrivelse": [
          {
            "titel_label": "Test repeater title label 1",
            "titel": "Test repeater title 1",
            "indhold": "<p>Test repeater content 1</p>\n"
          },
          {
            "titel_label": "Test repeater title label 2",
            "titel": "Test repeater title 2",
            "indhold": "<p>Test repeater content 2</p>\n"
          }
        ]
      }
    }
  }
}
```

However when I query it on my page with the following:
```
export const query = graphql`
  query ArtistProfileQuery($slug: String!) {
    wordpressWpArtist(slug: { eq: $slug }) {
      id
      title
      slug
      acf {
        fortael
        beskrivelse {
          titel_label
          titel
          indhold
        }
      }
    }
  }
`;
```
And the following `return` code:
```
class ArtistProfil extends Component {
  render() {
    const { data } = this.props;
    return (
      <div>
        <h1>{ data.wordpressWpArtist.title }</h1>
        <p>
          { data.wordpressWpArtist.acf.beskrivelse.titel_label }
        </p>
        <p>
          { data.wordpressWpArtist.acf.beskrivelse.titel }
        </p>
        <p>
          { data.wordpressWpArtist.acf.beskrivelse.indhold }
        </p>
      </div>
    )
  }
}
```

Then the Repeater Field data doesn't show. I can confirm that other standard ACF fields works perfectly. Only the Repeater Field seems to be an issue.

**Comment by Chuloo** [comment]
@omattman can you send in a minimal reproduction repo showing this issue? 👍

**Comment by omattman** [comment]
@Chuloo 

Hi Chuloo, this is as minimal as it gets. These are the only files edited since I wanted to test if it could accept repeater fields. The graphql accepts the info but the html output clearly doesnt. Does this have to do with the need of a basic loop like [this](https://www.advancedcustomfields.com/resources/repeater/) from the ACF documentaion?

**Comment by nikosolihin** [comment]
`beskrivelse` is a repeater field so it will return an array. Try this instead:
`
class ArtistProfil extends Component {
    render() {
        const { data } = this.props;
        return (
            <div>
                <h1>{data.wordpressWpArtist.title}</h1>
                {data.wordpressWpArtist.acf.beskrivelse.map(item => (
                    <React.Fragment>
                        <p>
                            {item.titel_label}
                        </p>
                        <p>
                            {item.titel}
                        </p>
                        <p>
                            {item.indhold}
                        </p>
                    </React.Fragment>
                ))}
            </div>
        )
    }
}
`

**Comment by nikosolihin** [comment]
`beskrivelse` is a repeater field so it will return an array. Try this instead:
```
class ArtistProfil extends Component {
    render() {
        const { data } = this.props;
        return (
            <div>
                <h1>{data.wordpressWpArtist.title}</h1>
                {data.wordpressWpArtist.acf.beskrivelse.map(item => (
                    <React.Fragment>
                        <p>
                            {item.titel_label}
                        </p>
                        <p>
                            {item.titel}
                        </p>
                        <p>
                            {item.indhold}
                        </p>
                    </React.Fragment>
                ))}
            </div>
        )
    }
}
```
