### ISSUE TITLE
[gatsby-plugin-sharp] Cache base64 calculations

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#6999]
Currently we memoize base64 resizes/calculations in https://github.com/gatsbyjs/gatsby/blob/9db958c02ddf3390e70cb430f8c66b3f320a55cf/packages/gatsby-plugin-sharp/src/index.js#L431 but these are expensive to do so build speeds would also improve (for image heavy sites) by adding the calculated base64 strings to the cache. Because of how graphql invalidation works, we often need to re-run older graphql queries but the expensive parts of graphql queries can be cached ideally so when most parts of the query resolve the same, the whole query resolves very quickly.

I can't remember if gatsby-plugin-sharp has access to the global gatsby cache. If not, that needs fixed.

The cache key should be the file's contentDigest + the meaningful arguments e.g. `cropFocus`, image format, `grayscale`, etc.

**Comment by oorestisime** [comment]
Hey, i would like to give this a go if nobody is touching this (mainly because i work on an image heavy site :) )
