### ISSUE TITLE
[docs] Add a "how to create a lightbox" guide/tutorial

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#7005]
There's no official "Gatsby lightbox", but this is a really common pattern. We should add a guide/tutorial showing how to implement this pattern with something like `react-modal`.

**Comment by iammatthias** [comment]
Ties in with my Lightbox feature request that I filed after speaking with @shannonbux today -> #7007

**Comment by 416serg** [comment]
@jlengstorf I built an example of how to use `gatsby-image` with a custom lightbox that has on screen control buttons and listens to keyboard events

Github: https://github.com/416serg/gatsby-starter-lightbox
Demo: https://gatsby-lightbox.416serg.me/

**Comment by jlengstorf** [comment]
This is great, @416serg! Would you be interested in writing up a tutorial on how you implemented this?

**Comment by 416serg** [comment]
@jlengstorf Jason, so sorry for seeing this 2 months later 😅I have all the Gatsby emails going into the same folder and there are thousands. Yeah, I'd love to do a tutorial on this, stay tuned. Also adding it to the starters for now

**Comment by 416serg** [comment]
@jlengstorf Here's a crack at a blog post: https://416serg.me/building-a-custom-accessible-image-lightbox-in-gatsbyjs

Demo: https://gatsbylightboxv2.416serg.me/
Github: https://github.com/416serg/GatsbyLightbox

Decided to create a new one using Gatsby V2, styled-components and @ryanflorence's `Dialog`

Let me know if it works or if I need to change it in any way/shape/form

Thanks 👋🏼

**Comment by shannonbux** [comment]
Yes, just follow those instructions @jlengstorf linked to and we can give feedback!

**Comment by 416serg** [comment]
@jlengstorf @shannonbux Thanks for the guidance Shannon and Jason ❤️Here it is: https://github.com/gatsbyjs/gatsby/pull/9684

**Comment by jlengstorf** [comment]
Thanks @416serg!
