### ISSUE TITLE
[ gatsby-plugin-sharp ] toFormat: PNG has no effect

### ISSUE THREAD

**Issue by schwiet** [gatsbyjs/gatsby#7008]
## Description

using the `toFormat: PNG` parameter on the `sizes` method does not create a PNG when the source image is a JPEG

### Steps to reproduce

A query containing:
```
background: file( relativePath: { eq: "my-fancy.jpg" } ){
    childImageSharp {
        sizes(
            maxWidth: 1200,
            maxHeight: 450,
            toFormat: PNG
        ){
            ...GatsbyImageSharpSizes
        }
    }
}
```

### Expected result

It seems the file should be converted to the PNG format.

### Actual result

Resulting files are JPEGs

### Environment
```    OS: macOS Sierra 10.12.2
    CPU: x64 Intel(R) Core(TM) i7-3770S CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 61.0.1
    Safari: 10.0.2
  npmPackages:
    gatsby: ^1.9.277 => 1.9.277 
    gatsby-image: ^1.0.55 => 1.0.55 
    gatsby-link: ^1.6.46 => 1.6.46 
    gatsby-plugin-catch-links: ^1.0.24 => 1.0.24 
    gatsby-plugin-feed: ^1.3.25 => 1.3.25 
    gatsby-plugin-google-analytics: ^1.0.31 => 1.0.31 
    gatsby-plugin-manifest: ^1.0.27 => 1.0.27 
    gatsby-plugin-nprogress: ^1.0.11 => 1.0.14 
    gatsby-plugin-offline: ^1.0.18 => 1.0.18 
    gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11 
    gatsby-plugin-sharp: ^1.6.48 => 1.6.48 
    gatsby-plugin-sitemap: ^1.2.25 => 1.2.25 
    gatsby-plugin-twitter: ^1.0.16 => 1.0.20 
    gatsby-plugin-typography: ^1.7.19 => 1.7.19 
    gatsby-remark-autolink-headers: ^1.4.19 => 1.4.19 
    gatsby-remark-copy-linked-files: ^1.5.37 => 1.5.37 
    gatsby-remark-images: ^1.5.67 => 1.5.67 
    gatsby-remark-prismjs: ^1.2.24 => 1.2.24 
    gatsby-remark-responsive-iframe: ^1.4.20 => 1.4.20 
    gatsby-source-filesystem: ^1.5.39 => 1.5.39 
    gatsby-transformer-remark: ^1.7.44 => 1.7.44 
    gatsby-transformer-sharp: ^1.6.27 => 1.6.27
```

**Comment by zauni** [comment]
Hi @schwiet 
I installed the [gatsby default starter](https://github.com/gatsbyjs/gatsby-starter-default) and source-filesystem, plugin-sharp and transformer-sharp with your versions and it transformed my jpg files to png format without any problems.

My GraphQL  query looks like yours: 

```graphql
{
  background: file(relativePath: {eq: "test.jpg"}) {
    childImageSharp {
      sizes(maxWidth: 1200, maxHeight: 450, toFormat: PNG) {
        src
        srcSet
        originalName
      }
    }
  }
}
```

So I have a problem to reproduce the issue. Maybe you can build a simple case where it fails and where I can have a look at? Thanks!

**Comment by polarathene** [comment]
@zauni There is [a very similar bug](https://github.com/gatsbyjs/gatsby/issues/10747) with the `sharp` package which will be fixed in the `0.21.2` release.

It doesn't look like the code changed much since between your two posts, but it does seem like it could have been the same behaviour as I have with jpg to png not working on base64 images.

**Comment by SkelegonDK** [comment]
toFormat is a method by it self. Not a shared option. 

> Shared Options
In addition to their individual parameters, **all methods above share the following**:

grayscale (bool, default: false)
duotone (bool|obj, default: false)
toFormat (string, default: ”)
cropFocus (string, default: ’sharp.strategy.attention‘)
pngCompressionSpeed (int, default: 4)
toFormat
Convert the source image to one of the following available options: NO_CHANGE, JPG, PNG, WEBP.

**Comment by polarathene** [comment]
@SkelegonDK it's a graphql param, try it.
