### ISSUE TITLE
Fix handling of hash links & scrolling

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#7017]
## Description

Currently Gatsby handles clicking on hash links as in we do correctly scroll to the link. However, we don't handle scrolling back to the previous scroll position when you click back.

### Steps to reproduce

- navigate to https://next.gatsbyjs.org/docs/performance-tracing/
- click on "Tracing backend examples"
- click back button
- observe nothing happens

### Expected result

When clicking the back button, it'd scroll to the previous scroll position.

### Actual result

Nothing happens.

## How to fix

After https://github.com/gatsbyjs/gatsby/pull/6918 lands, we should investigate adding remembering the hash scroll position in either gatsby-react-router-scroll or in the new top-level `RouteHandler` component.

**Comment by KyleAMathews** [comment]
@ryanditjia Thanks for sharing!

Note to myself or whoever implements this — we don't call `onRouteUpdate` for hash changes so make sure this is still the case when we move hash links handling to `RouteHandler`.

**Comment by tibotiber** [comment]
@KyleAMathews @stefanprobst, in addition to this shouldn't a `hashchange` event be emitted as well? See [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/hashchange_event). Sorry for commenting on a closed issue but I thought it would help have the context.

**Comment by karlhorky** [comment]
@ryanditjia you'll want to also update the `scrollToHref` function with the following, to fix ids starting with numbers, which results in an error like `SyntaxError: Failed to execute 'querySelector' on 'Document': '...' is not a valid selector.`:

```js
// Fix scrolling for ids starting with numbers
// https://stackoverflow.com/a/20306237/1268612
const hash = location.hash.replace(/^\#(\d)/, '#\\3$1');
```
