### ISSUE TITLE
Documentation on Gatsby + Netlify CMS

### ISSUE THREAD

**Issue by S3B4S** [gatsbyjs/gatsby#7024]
## Summary
👋 
I noticed the documentation on using Netlify-CMS + Gatsby is outdated, if you follow the instructions [here](https://www.gatsbyjs.org/docs/netlify-cms/) (v1), you'll stumble upon issue #6802. It turns out that the README from the package `gatsby-plugin-netlify-cms` [here](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-netlify-cms#gatsby-plugin-netlify-cms) contains the right commands to use. So by using these commands I made it work. 

I want to update the documentation to reflect these commands, however I have two questions about this;

- The documentation for [v1](https://www.gatsbyjs.org/docs/netlify-cms/) and [v2](https://next.gatsbyjs.org/docs/netlify-cms/) share the [same source](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/netlify-cms.md). I was thinking of having two seperated sources, one for each version, is this alright to do?

- The [commands](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-netlify-cms#gatsby-plugin-netlify-cms) are likely to change soon, should I wait until these are stable or should I get started with it now?

**Comment by LekoArts** [comment]
https://www.gatsbyjs.org/docs/sourcing-from-netlify-cms/

**Comment by kpennell** [comment]
@LekoArts Should questions/bugs/challenges about the guide be posted on here as issues or on StackOverflow?
