### ISSUE TITLE
Why need react during runtime?

### ISSUE THREAD

**Issue by coodoo** [gatsbyjs/gatsby#7026]
This is probably a dumb question, but as a static site generator, I would expect gatsby to produce static files like html and js only, but seems it will instantiate react during runtime (hence needing to download 60kb of lib files), what's the use and reasons for doing that?

**Comment by KyleAMathews** [comment]
Gatsby has roots in the static site world but doesn't consider itself a normal static site generator but instead as an easy/excellent way to use React for websites. So loading React into the browser is a feature not a bug ;-)

It's why clicking around a site is so fast plus makes it easy to add clientside enhancements.

**Comment by coodoo** [comment]
Thanks @KyleAMathews for the concise and quick answer!
