### ISSUE TITLE
[gatsby-transformer-react-docgen] throws conflicting field types warning

### ISSUE THREAD

**Issue by danoc** [gatsbyjs/gatsby#7027]
## Description

`gatsby-transformer-react-docgen` throws "There are conflicting field types in your data" warning depending on the PropTypes.

Here are two components that conflict:

```
Button.propTypes = {
  type: PropTypes.oneOf(['button', 'submit']),
}
```
```
DatePicker.propTypes = {
  lastMonth: PropTypes.instanceOf(Date),
}
```

### Steps to reproduce

I've created a [repo to demonstrate this bug](https://github.com/danoc/gatsby-react-docgen-repro):

1. `git clone git@github.com:danoc/gatsby-react-docgen-repro.git && cd gatsby-react-docgen-repro && yarn && yarn develop`
2. See warning in console.

### Expected result

Shouldn't start development environment without throwing warning.

### Actual result

Warning appears:

```
warning There are conflicting field types in your data. GraphQL schema will omit those fields.
ComponentProp.type.value:
 - type: array<object>
   value: [ { value: '\'button\'', computed: false }, ... ]
   source: File "conflicting-components/Button.jsx"
 - type: string
   value: 'Date'
   source: File "conflicting-components/DatePicker.jsx"
ComponentProp.parentType.value:
 - type: array<object>
   value: [ { value: '\'button\'', computed: false }, ... ]
   source: File "conflicting-components/Button.jsx"
 - type: string
   value: 'Date'
   source: File "conflicting-components/DatePicker.jsx"
```

### Environment
I'm running v2, but this happens in both v1 and v2.
```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Shell: 5.5.1 - /usr/local/bin/zsh
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Chrome: 68.0.3440.84
    Firefox: 61.0.1
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-beta.69
    gatsby-source-filesystem: next => 2.0.1-beta.10
    gatsby-transformer-react-docgen: next => 2.1.1-beta.4
```
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by KyleAMathews** [comment]
Hmmm that's no good. @jquense know of any easy way to fiddle with the schema to allow for this?

**Comment by Chuloo** [comment]
Same error noticed when I ran reproduction. 
```
warning There are conflicting field types in your data. GraphQL schema will omit those fields.
ComponentProp.type.value:
 - type: array<object>
   value: [ { value: '\'button\'', computed: false }, ... ]
   source: File "conflicting-components/Button.jsx"
 - type: string
   value: 'Date'
   source: File "conflicting-components/DatePicker.jsx"
ComponentProp.parentType.value:
 - type: array<object>
   value: [ { value: '\'button\'', computed: false }, ... ]
   source: File "conflicting-components/Button.jsx"
 - type: string
   value: 'Date'
   source: File "conflicting-components/DatePicker.jsx"
```

**Comment by thefifthisa** [comment]
Hi! I think I'd like to work on this but I'm trying to understand the issue first. Is it that the types aren't actually conflicting, or that it compiles successfully even with the conflict?

**Comment by jquense** [comment]
They types aren't conflicting, there is a false positive because the fields in question are JSON scalars but the Gatsby inference logic thinks they are objects and lists. I actually "fixed" this problem previously, where it wasn't compiling but it seems like it's still starting to print a warning even tho there aren't any conflicts to print

**Comment by MtthsB** [comment]
Hi all -- I still get this (https://github.com/gatsbyjs/gatsby/issues/7027#issuecomment-410878317) very same issue. I can't see this having been solved or addressed directly anywhere?

Package.json:
    "gatsby": "^2.23.0",
    "gatsby-cli": "^2.12.43",
    "gatsby-plugin-mdx": "^1.2.14",
    "gatsby-plugin-postcss": "^2.3.3",
    "gatsby-plugin-sass": "^2.3.3",
    "gatsby-source-filesystem": "^2.3.10",
    "gatsby-transformer-react-docgen": "^5.2.3",

Thanks in advance for getting back to me!

**Comment by jquense** [comment]
yes this is still broken

**Comment by MtthsB** [comment]
Thanks for the reply. I've worked my way around the problem (basically, using react-docgen as a dependency in itself, and not as a gatsby plugin), so there is no direct need for its solution anymore.

**Comment by jquense** [comment]
still an issue

**Comment by jquense** [comment]
still broken

**Comment by wardpeet** [comment]
Converting this plugin using [schema-customization](https://www.gatsbyjs.com/docs/schema-customization/) should fix these issues as no inference will be done.

**Comment by jquense** [comment]
The plugin most does that already the warnings are happening because gatsby still tried to infer explicit JSON fields. Using dontInfer creates unfixable issues with auto added child fields (either warnings that can't be silenced, or broken  code bc the fields are necessary for inactions with other plugins)

**Comment by tomconder** [comment]
The repo created to reproduce this issue no longer exists. Does anybody have a copy/fork I can clone?

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
