### ISSUE TITLE
"using-asciidoc" example is a "using-drupal" example

### ISSUE THREAD

**Issue by triemenschneider** [gatsbyjs/gatsby#7031]
## Description

The content [here](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-asciidoc) (https://github.com/gatsbyjs/gatsby/tree/master/examples/using-asciidoc) is identical to the content [here](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-drupal) (https://github.com/gatsbyjs/gatsby/tree/master/examples/using-drupal).

![wrong readme](https://user-images.githubusercontent.com/3159548/43685115-374a009e-98ad-11e8-971f-2b2150c6c09f.png)

**Comment by KyleAMathews** [comment]
Ah, it looks like I copied the README and didn't update it 😅

Would you like to do a PR updating it?
