### ISSUE TITLE
Integrate Lighthouse into Continuous Integration pipeline

### ISSUE THREAD

**Issue by thescientist13** [gatsbyjs/gatsby#7034]
## Summary
I'm not super familiar with the release management workflow of Gatsby but was just wondering if the team has considered integrating [Lighthouse as part of the CI process](https://github.com/GoogleChrome/lighthouse#using-the-node-cli) somehow, maybe for the starter / sample projects?

In keeping with being blazing fast ™️ , ensuring performance metrics thresholds are upheld in an automated fashion would help with sustaining that.

## Relevant information
Although I haven't personally implemented Lighthouse via the CLI, my thought would essentially be something along the lines of
1. CI builds
1. At the end of the job, upload the content to CDN (under a domain like http://perf.gatsbyjs.org ?)
1. After the upload is complete, run Lighthouse and point to DNS / CDN
1. Report the findings back in the PR

## Environment
I am aware of some changes to the CI process being discussed [here](https://github.com/gatsbyjs/gatsby/issues/6534) so wanted to make sure those are considered here.

**Comment by thescientist13** [comment]
I should add I am happy to help with any effort towards this if it is desired.  👍

**Comment by KyleAMathews** [comment]
Definitely interested in this. Not sure right now the best approach as adding this to TravisCI sounds like it'd slow things down a lot which we don't want.

**Comment by m-allanson** [comment]
Another thing to note is that lighthouse scores aren't always the same given the same site. Maybe we'd have to keep track of a running average for scores? But it'd be great to know about PRs that reduce performance scores across all the example sites.

**Comment by wardpeet** [comment]
I could help with this if you like. It's best to run it in a docker container as a separate travis stage. The scores might vary but you should test >80 and we can also test part of the audits so we don't look only at the scores.

Note that lighthouse startup and run might take 2-5min on Travis inside a container

**Comment by thescientist13** [comment]
Hey @wardpeet , that sounds good!  Admittedly I have let this one slide.  Feel free to give it a go!

**Comment by thescientist13** [comment]
@m-allanson 
> Another thing to note is that lighthouse scores aren't always the same given the same site. Maybe we'd have to keep track of a running average for scores? 

That's a good point.  I suppose it would have to be targeted to a couple of the key starter repos and / or maybe a standalone Gatsby repo with a "kitchen sink approach" that can really exercise the build with a handful of common plugins to ensure scores stay healthy / consistent across a representative sample size.  

> But it'd be great to know about PRs that reduce performance scores across all the example sites.

I suppose this task could also be seen as a "canary in the coal mine" step as part of an over testing plan for the Gatsby core.  Always building a few sites and having their scores out in the open as it were, can provide verification at any given time that Gatsby is indeed _blazing fast_ ™️ 🔥
