### ISSUE TITLE
[v2] history.location props on JSONStore not updated after change to location.search

### ISSUE THREAD

**Issue by Fetten** [gatsbyjs/gatsby#7035]
## Description

After updating to the latest v2 (2.0.0-beta.69) the location props from the `Router` Component do not get updated on `JSONStore` if just the `location.search` is updated but not `location.pathname` (figured this out with React Dev Tools).

This worked lately with gatsby@2.0.0-beta.34 and gatsby-link@2.0.0-beta.4.  I would guess this is related to this commit https://github.com/gatsbyjs/gatsby/commit/206756315f770ef336007619aa01824056fbfd91 As I cannot really see where the update happens, maybe @pieh could have a look at this.

### Steps to reproduce

Create a page like `/demo/`.

```js
import { push } from 'gatsby'

...

push('/demo/?testparam=1');
...
```

location props on `Router` and `ScrollComponent`:
`{pathname: '/demo/', search: '?testparam=1', ...}`

location props on `JSONStore` :
`{pathname: '/demo/', search: '', ...}`

### Expected result

location props should be updated on JSON Store Component as well (and on children components).

### Environment

gatsby@2.0.0-beta.69
gatsby-link@2.0.0-beta.6

**Comment by pieh** [comment]
My bad, I'll push PR shortly
