### ISSUE TITLE
My gatsby develop build breaks after doing some work locally to gatsby core using gatsby-dev-cli

### ISSUE THREAD

**Issue by ylorenzana** [gatsbyjs/gatsby#7043]
I wanted to go back to working on my personal site using the official version of Gatsby after making some changes to a local version of Gatsby core. I deleted my node_modules and tried running npm install. This error is being thrown when running `gatsby develop`

![image](https://user-images.githubusercontent.com/29875483/43695837-ee91b188-9908-11e8-83f6-72b4cf07fcf3.png)

**Comment by ylorenzana** [comment]
https://github.com/ylorenzana/blog this is the repo for my blog. My local repo is about identical to the remote one, only difference is I used my local version of gatsby using the gatsby-dev-cli to build my project locally.

**Comment by Chuloo** [comment]
Delete the `.cache` folder and try again.

**Comment by ylorenzana** [comment]
Thanks that did the trick. I'll keep that in mind for next time.
