### ISSUE TITLE
gatsby-node.js doesn't work in windows because of path problem

### ISSUE THREAD

**Issue by chenvan** [gatsbyjs/gatsby#705]
other path problem.
In url-resolver.js

![url-resolver](https://cloud.githubusercontent.com/assets/7885757/23656234/c3a6ed0c-0373-11e7-825d-01f220ed1656.png)

![output](https://cloud.githubusercontent.com/assets/7885757/23656235/c62be0aa-0373-11e7-8183-9dc5fa9c569f.png)

**Comment by akadop** [comment]
I have the same problem, I think it relates to:

gatsby/bootstrap/index.js (line 412)

 // Add chunkName.
              pages.forEach(function (page) {
                page.componentChunkName = (0, _jsChunkNames.layoutComponentChunkName)(program.directory, page.component);
              });

program.directory is presumably 'C:\Users\Whatever\Github\Gatsby\Whatever\'

**Comment by chenvan** [comment]
@akadop Thanks for reply. I will check later.

**Comment by fabien0102** [comment]
Fix into https://github.com/gatsbyjs/gatsby/pull/781 😄
