### ISSUE TITLE
vsCode Chrome Debugger settings

### ISSUE THREAD

**Issue by b0gd4n** [gatsbyjs/gatsby#7057]
Hey all,

Not sure how many of you are using the vsCode Chrome Debugger, but it would be awesome if someone can share their settings for the tool.

For reference, the settings for the `create-react-app` is:

```
{
    "version": "0.2.0",
    "configurations": [{
      "name": "Chrome",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceRoot}/src",
      "sourceMapPathOverrides": {
        "webpack:///src/*": "${webRoot}/*"
      }
    }]
  }
```

**Comment by nikosolihin** [comment]
Did you figure out a good debugger settings?
