### ISSUE TITLE
Introduce StaticQuery in the tutorial

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#7059]
## Summary

StaticQuery is a big new feature of Gatsby v2, it's used in part 4 of the tutorial but there's very little info about what it is, why you should use it and how it's different from page queries. Let's update the tutorial to cover StaticQuery.

### Basic example

There are many ways StaticQuery could be introduced, here's one as an example.

The ["Querying for the site title"](https://next.gatsbyjs.org/tutorial/part-four/#querying-for-the-site-title) section could be split into:

- _Make a query from your About page_ - this could be mostly the same content that the tutorial has now 
- _Make a query from any component_ - this would introduce StaticQuery and how to query from any component, along with explaining the tradeoffs of using `StaticQuery`

### Motivation

StaticQuery is a big new feature of v2 and the tutorial is often a first point of contact for people starting with Gatsby. This change ensures the tutorial covers key Gatsby functionality.

@KyleAMathews @shannonbux @amberleyromo it'd be great to get your thoughts on this. I've marked it as a blocker for v2 release, someone please change that if it's incorrect.

**Comment by shannonbux** [comment]
@m-allanson I don't know enough about StaticQuery to know for sure, but if
it's often a first point of contact, definitely seems worth including in
the tutorial and making sure there is standalone documentation on it as
well. I think your plan sounds great.

**Comment by ryanditjia** [comment]
We can introduce this in [part 7](https://github.com/gatsbyjs/gatsby/edit/master/docs/tutorial/part-seven/index.md). Between lines 265 – 319 there is a little bit of unexplained magic how `pageContext` translates to GraphQL variables. We should ask the tutorial taker to:

1. `console.log(this.props.pageContext)`
2. Build the query in GraphiQL, also introducing them to using Query Variables with the GUI (we include screenshot here)
3. Explain that pageContext is automatically passed to page query as variable
4. Explain that this lack of variability is what causes StaticQuery to be named what it is

Then, in part 4, where we used page query and StaticQuery back-to-back, we can add a small note saying, “Confused why we use 2 different queries here? Don’t worry, we will go in depth in part 7. For now, keep in mind that only pages can make page queries, and non-page components (like Layout) use StaticQuery instead.”

What do you guys think? If the plan sounds good, I’ll assign myself to this, and we can fix the nitpicky details later in the PR.

**Comment by shannonbux** [comment]
@m-allanson and @pieh this needs an answer...and unfortunately I don't know the answer. Would appreciate your perspective here!

**Comment by amberleyromo** [comment]
To note here: The changes to tutorial/part-four in #7240 take care of introducing StaticQuery; can't speak to changes in part-seven, but now we have a better baseline intro earlier in the tutorial.

**Comment by amberleyromo** [comment]
Static Query was introduced in part four -- in the changes introduced in #7240 -- meeting the needs of this ticket.

I've opened a new issue for further improvements (referencing your suggested improvements, @ryanditjia!) in #7284.
