### ISSUE TITLE
ACF Repeater Field usage in template

### ISSUE THREAD

**Issue by omattman** [gatsbyjs/gatsby#7067]
If using a Repeater Field in ACF how would it be possible to output the data on a page?

Should we assign the values to objects in Gatsby and then iterate over the objects to output every single row or instance of the Repeater Field.

Can someone clarify if this module is even supported within Gatsby?

**Comment by pieh** [comment]
Yes, it's possible, It will contain array of objects. Please check https://www.gatsbyjs.org/packages/gatsby-source-wordpress/#graphql-error---unknown-field-on-acf in case you can't access repeater field.

**Comment by omattman** [comment]
@pieh Thanks for responding that fast.

The problem isn't that I can't access the fields. I can access them and have gone over your provided link already.

How would I then use this in a template. That's the issue I can't solve.

**Comment by omattman** [comment]
@pieh Would you mind reopening the issue again since I can't define it as solved.

**Comment by omattman** [comment]
@KyleAMathews Hi Kyle,

I've already tried querying it and it shows the following result:

```javascript
{
  wordpressWpArtist(slug: { eq: "joey-moe" }) {
    id
    title
    slug
    featured_media {
      source_url
    }
    acf {
      embed_url
      beskrivelse {
        titel
        titel_label
        indhold
      }
    }
  }
}
```

which returns:
```javascript
{
  "data": {
    "wordpressWpArtist": {
      "id": "26f78084-3203-5f6d-83a5-d11537f431f9",
      "title": "Joey Moe",
      "slug": "joey-moe",
      "featured_media": {
        "source_url": "http://localhost:8080/wp-content/uploads/2018/08/joey-moe.jpg"
      },
      "acf": {
        "embed_url": "https://www.youtube.com/watch?v=i-GXSXn7DCw",
        "beskrivelse": [
          {
            "titel": "test titel 1",
            "titel_label": "test label 1",
            "indhold": "<p>test content 1</p>\n"
          },
          {
            "titel": "test titel 2",
            "titel_label": "test label 2",
            "indhold": "<p>test content 2</p>\n"
          }
        ]
      }
    }
  }
}
```
So the content is there. However, when i access it on my page:
```javascript
import React, { Component } from 'react'
import Player from '../components/artister/player.js';

export default class ArtistProfil extends Component {
  render() {
    const { data } = this.props;
    return (
      <div>
        <h1>{ data.wordpressWpArtist.title }</h1>
        <img src={data.wordpressWpArtist.featured_media.source_url} />
        <Player url={data.wordpressWpArtist.acf.embed_url}/>

        <p>{data.wordpressWpArtist.acf.beskrivelse.titel}</p>          <--
        <p>{data.wordpressWpArtist.acf.beskrivelse.titel_label}</p> <--
        {data.wordpressWpArtist.acf.beskrivelse.indhold}                    <--
      </div>
    )
  }
}

export const query = graphql`
  query ArtistProfileQuery($slug: String!) {
    wordpressWpArtist(slug: { eq: $slug }) {
      id
      title
      slug
      featured_media {
        source_url
      }
      acf {
        embed_url
        beskrivelse {
          titel
          titel_label
          indhold
        }
      }
    }
  }
`;
```
Nothing gets output on the front-end.

**Comment by KyleAMathews** [comment]
Hmm looks like the query isn't getting run. Can you try changing the query in some trivial way to force it to get run again?

**Comment by omattman** [comment]
@KyleAMathews What do you mean by "isn't getting run"? Its querying fine on my setup.

**Comment by omattman** [comment]
I can also see it in the React console window on the front-end:

```javascript

data: {…}
    wordpressWpArtist: {…}
        acf: {…}
            beskrivelse: Array[2]
                0: {…}
                    titel: "test titel 1"
                1: {…}
                    titel: "test titel 2"
            embed_url: "https://www.youtube.com/watch?v=i-GXSXn7DCw"
        featured_media: {…}
        id: "26f78084-3203-5f6d-83a5-d11537f431f9"
        slug: "joey-moe"
        title: "Joey Moe"
```

**Comment by KyleAMathews** [comment]
If the data is showing in the console, double-check your React code then.

**Comment by omattman** [comment]
Do you believe since it shows `Array[2]` I'd have to do some sort of forEach loop to iterate over each instance? Still getting a hang of this setup.

**Comment by danielberndt** [comment]
`data.wordpressWpArtist.acf.beskrivelse` is an array so `data.wordpressWpArtist.acf.beskrivelse.titel` won't return anything.

You need to loop over `data.wordpressWpArtist.acf.beskrivelse` in order to access the values :)

**Comment by omattman** [comment]
@danielberndt Hi Daniel,

Thanks for chipping in. I've tried to loop over the data, but I can agree to the point that my React skills is a joke compared to PHP. Could you give a quick reference or piece of code, which would indicate this kind of loop? :-)

**Comment by danielberndt** [comment]
sure!

```jsx
export default class ArtistProfil extends Component {
  render() {
    const { data } = this.props;
    return (
      <div>{data.wordpressWpArtist.acf.beskrivelse.map(description => (
        <div>
          <p>{description.titel}</p>
          <p>{description.titel_label}</p>
        </div>
      ))}</div>
    )
  }
}

```

or more cleaned up

```jsx
const Description = ({value}) => (
  <div>
    <p>{description.titel}</p>
    <p>{description.titel_label}</p>
  </div>
)

export default class ArtistProfil extends Component {
  render() {
    const { data } = this.props;
    return (
      <div>{data.wordpressWpArtist.acf.beskrivelse.map(description => (
        <Description value={description}/>
      ))}</div>
    )
  }
}
```

**Comment by omattman** [comment]
@danielberndt Absolutely amazing. Thanks for being the man of the day 👍
