### ISSUE TITLE
[V2] Reach/router extremely slow while `gatsby develop`

### ISSUE THREAD

**Issue by monsieurnebo** [gatsbyjs/gatsby#7068]
# Context
All dependencies up-to-date.

# Bug description
I just migrated from `react-dom-router` to `reach/router` (following [these instructions](https://github.com/gatsbyjs/gatsby/blob/33de9f3ba6fed46ca04395887dd0ec8d036c3993/docs/docs/migrating-from-v1-to-v2.md#migrate-from-react-router-to-reachrouter)), and I'm encountering a strange behaviour:
- Everything works as expected on a build project
- Every route change while `gatsby develop` is totally buggy: the current page blink, then change after a huge amount of time.

Did any of you encounter that bug? Any idea?

**Comment by alexandernanberg** [comment]
I'm also seeing this on [the upgraded reactjs.org](https://github.com/alexandernanberg/reactjs.org/tree/gatsby-v2) site.

Profiling from navigating once, I can send a saved profiling json file if you'd like
<img width="929" alt="image" src="https://user-images.githubusercontent.com/8997319/43727305-d760159c-99a1-11e8-881a-f5482bc947a0.png">

**Comment by anantoghosh** [comment]
I also started experiencing this,

Here's the performance profile
[gatsby-slow-link.zip](https://github.com/gatsbyjs/gatsby/files/2263233/gatsby-slow-link.zip)

There is a 5 second lag before the page switch occurs. The url is updated instantly.

**Comment by Fetten** [comment]
Seeing this delay after updating as well. Also noticed that the `location` prop is passed to the `<a>` tag from gatsby-link in html (`<a href="/" location="[object Object]">`.

**Comment by LeKoArts** [comment]
The `activeClassName` also gets passed:

```HTML
<a aria-current="page" location="[object Object]" activeclassname="active" class="active" href="/contact">Contact</a>
```

**Comment by porfirioribeiro** [comment]
I can confirm this issue also.

**Comment by ryanditjia** [comment]
Tested with Safari, Chrome, Firefox. All 3 browsers exhibit slowness in develop, only Firefox is slow in built.

Strangely, title and meta description (plus other stuff within `react-helmet`) are updated instantly, but the rest of the content takes ~5s to update.

**Comment by JoaoTMDias** [comment]
Hey, everyone!
I'm also facing the same issue.
Created a new project from scratch and manually imported step-by-step everything I had from v1.
I'm importing Link from gatsby.

Other than this, everything worked as expected!
Last night I tried to follow the guide from upgrading from v1 to v2 and had all sorts of issues.
Building from scratch works best at the moment, I think.
![gatsby 1](https://user-images.githubusercontent.com/2223881/43772476-2f2c7048-9a3a-11e8-8b40-ad5d6cb1e589.gif)

**Comment by kkemple** [comment]
@JoaoTMDias in regard to
> Last night I tried to follow the guide from upgrading from v1 to v2 and had all sorts of issues.

Was there information missing from the guide? Or were things unclear?
Would love to get your feedback to see if I could make it better! 🙏

**Comment by monsieurnebo** [comment]
I just tested the [PR](https://github.com/gatsbyjs/gatsby/pull/7120).

The "slow behaviour" seems fixed, but there is an "epileptic flash" when switching pages now:

![router-bug](https://user-images.githubusercontent.com/2378274/43822797-74d00ae8-9aed-11e8-818b-54ac90844cc0.gif)


Probably related to @pieh message:
> changes here skip triggering lifecycle methods that causes unneeded component updates and renders.

**Comment by pieh** [comment]
@monsieurnebo is your site source public? I would like to check it and possibly continue with fixes

**Comment by monsieurnebo** [comment]
@pieh  Unfortunatly, I cannot make it public...

However, I can give you specific informations if needed.

**Comment by youngboy** [comment]
With gatsby version in `2.0.0-beta.84`, I am still have the slowness Link redirection issue

during idling, my chrome console keep printing something like:
```
[Violation] 'requestIdleCallback' handler took 83ms
[Violation] 'requestIdleCallback' handler took 121ms
[Violation] 'requestIdleCallback' handler took 144ms
[Violation] 'requestIdleCallback' handler took 124ms
Users/yanghaku/weimi/sites/node_modules/react-dom/cjs/react-dom.development.js:5427 [Violation] 'message' handler took 167ms
[Violation] 'requestIdleCallback' handler took 122ms
``` 

I'll try to create a minimal repo to reproduce this bug

**Comment by benadam11** [comment]
@KyleAMathews Is there a clear resolution to this? Just converted a site to V2 and am experiencing this 
<img width="605" alt="screen shot 2018-09-04 at 10 32 12 am" src="https://user-images.githubusercontent.com/6645985/45047416-d3e7c980-b02d-11e8-913f-4b50fc28c614.png">

**Comment by KyleAMathews** [comment]
The original issue was fixed. Please open a new issue with reproduction instructions for what you're seeing now.
