### ISSUE TITLE
Can't import image into a page.

### ISSUE THREAD

**Issue by BLBaylis** [gatsbyjs/gatsby#7072]
When I try importing an image using a relative path into a page in the src/page folder, I keep receiving this error and can no compile my code: 

> Loader C:\Users\Brad\Desktop\Coding\brad-portfolio\node_modules\url\url.js?{"limit":10000,"name":"static/[name].[hash:8].[ext]"} didn't return a function

I know in the [adding images, fonts and files page in the docs](https://www.gatsbyjs.org/docs/adding-images-fonts-files/), it says:

> To reduce the number of requests to the server, importing images that are less than 10,000 bytes returns a data URI instead of a path. This applies to the following file extensions: svg, jpg, jpeg, png, gif, mp4, webm, wav, mp3, m4a, aac, and oga.

So the limit : 10000 in the error is presumably related to that somehow.  I'm not sure if this is a bug or I'm making an error.

**Comment by LeKoArts** [comment]
Delete your node_modules folder, reinstall (npm install) and make sure that url-loader is in the node_modules folder. Alternatively you could try installing with yarn.

**Comment by BLBaylis** [comment]
Yup that did it, nice one
