### ISSUE TITLE
Hidden/confidential static pages

### ISSUE THREAD

**Issue by bw** [gatsbyjs/gatsby#7074]
I'm curious about Gatsby's potential support for hidden or confidential pages. I'm defining them here as pages that cannot be discovered by inspecting the bundle, Webpack manifest, prefetch logic, or anything like that. The only way to get to these pages would be to enter the correct URL.

I'm aware that one of the changes implemented in Gatsby v2 is the removal of the Webpack manifest that is printed in the HTML of every page. I am unsure, however, whether the page paths would be revealed through any other way.

**Comment by KyleAMathews** [comment]
We don't currently have any support for that but it'd be interesting option to add!

Does webpack have support for doing this sort of thing?

The simplest thing to do perhaps would be to just have a separate site. It'd be straightforward to share components across the site which would simplify building and maintaining the sites!

**Comment by bw** [comment]
@KyleAMathews: unfortunately I don't believe that having a separate site would solve this problem. The hidden/confidential pages would also need to be hidden from each other; it's not a "secret section" of the website, if that makes sense.

For example, if a company posts hiring challenges as pages on their website, they would not want candidates to be able to find the subsequent portions of the challenge. (This is the real scenario that prompted the ticket.)

I am unfamiliar with what parts are controlled by Webpack/React Router and which parts are controlled by Gatsby, but I believe that implementation-wise the burden would likely fall on Gatsby.

**Comment by bw** [comment]
Perhaps some sort of scenario in which we can choose to disable "prefetching" and all related functionality, and then manually specify which pages to pre-load?

**Comment by KyleAMathews** [comment]
Separate sites don't know anything about each other so there's no prefetching, etc.

**Comment by KyleAMathews** [comment]
Webpack includes a "manifest" with all the components linked so a single site is always introspect-able for finding new routes + you can find Gatsby's metadata as well to see page structure.

Separate sites is the only way to handle this afaik.

**Comment by KyleAMathews** [comment]
You could use another tool as well to create the one off pages which might be simpler

**Comment by KyleAMathews** [comment]
Gatsby isn't really optimized for creating only one page. Though this is an interesting problem to think about.

**Comment by bw** [comment]
Right-- I agree. Personally I think that the solution to making hidden/unattached pages as creating a site per page is a non-starter for most scenarios. Maybe if Gatsby could generate them as static pages. Or some sort of separate way to rapidly generate pages...

**Comment by braco** [comment]
Oh man, I'm discovering this pretty late in a big project.

How about disabling chunking/prefetching for one page only?

The contents of a page that's currently protected by an auth redirect on Netlify are getting loaded when they shouldn't be.

**Comment by jgierer12** [comment]
@braco You could just use a normal `<a href="...">` instead of `<Link to="...">` to link to the private page. Prefetching is tied to the Link component so I think that should circumvent it.

**Comment by braco** [comment]
Hey @jgierer12, I think this comment from @KyleAMathews still holds true:

> Webpack includes a "manifest" with all the components linked so a single site is always introspect-able for finding new routes + you can find Gatsby's metadata as well to see page structure.

**Comment by braco** [comment]
I'm assuming something like
https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-create-client-paths
is the only option, though I haven't had a chance to look under the hood there yet, and I think it stops static rendering on those paths entirely, which is too bad

**Comment by braco** [comment]
@KyleAMathews how feasible would it be to write an extension that allowed pages to opt-in to being built as HTML but excluded from the chunking/mapping/etc? That way at least they could be auth-gated cleanly by external systems, like the functionality Netlify provides. I'm willing to code this but would need some guidance.

**Comment by mrlubos** [comment]
Bump bump

**Comment by BilaalHussain** [comment]
Bump!

**Comment by fzyzcjy** [comment]
bump!!
