### ISSUE TITLE
RootQueryType in Gatsby 2.0.0

### ISSUE THREAD

**Issue by coreyward** [gatsbyjs/gatsby#7085]
I'm upgrading a Gatsby 1.x codebase to 2.0.0 (currently @ beta.72) and running into an issue. The codebase uses `RootQueryType` to declare GraphQL fragments that are at the query level, but it doesn't seem like this is a valid type anymore. 

For Example:

```js
// components/about.jsx
export const query = graphql`
  query About {
    contentfulAboutPage {
      title
      phoneNumber
    }

    ...TeamMembers
  }
`

// components/team.jsx
export const query = graphql`
  fragment TeamMembers on RootQueryType {
    allContentfulTeamMembers {
      edges {
        node {
          name
        }
      }
    }
  }
`
```

Previously queries like this worked fine, but now they result in this error:

    error GraphQL Error Unknown type "RootQueryType".

**Has using `RootQueryType` in this way been deprecated? Is there an alternate approach allowing fragments to work, or should I be converting these queries into static queries?**

Thank you!

**Comment by benjaminabel** [comment]
This must be a recent change because it worked in `gatsby": "^2.0.0-beta.17`, and I got the same error with the latest version: `2.0.0-beta.76`.

**Comment by KyleAMathews** [comment]
We recently merged this which probably caused the change https://github.com/gatsbyjs/gatsby/pull/6475

I'm not sure what the new "root" type name would be... what does it say in graphiql? Ideally we wouldn't break this.

**Comment by coreyward** [comment]
@KyleAMathews Looks like `Query` is the new `RootQueryType`.

**Comment by coreyward** [comment]
I've added the relevant documentation to the migration guide. Closing!
