### ISSUE TITLE
Add snapshot tests

### ISSUE THREAD

**Issue by alexandernanberg** [gatsbyjs/gatsby#7089]
## Summary

I'd like to add snapshot testing for some of the packages, like `gatsby-link`. Would also like to see more DOM tests on these kind of components with eg [`react-testing-library`](https://github.com/kentcdodds/react-testing-library) 

### Motivation

Better testing will lead to fewer bugs and will make it easier for new contributors to not break things

I'd be happy to create a PR adding this to `gatsby-link` but I wanted to hear what you think before.

**Comment by KyleAMathews** [comment]
Yeah! That'd be huge help!

**Comment by shobhitchittora** [comment]
@alexandernanberg Great thinking! It'd be great to have a checklist of packages / code-paths / plugins, which would benefit from snapshot testing. I'm pretty new here and would like everyone's input.

Checklist - 
 - [x] `gatsby-link`
 - [ ] `gatsby-image`

**Comment by alexandernanberg** [comment]
Think my PR closed this automatically, might want to reopen if we are going to track other packages as well

**Comment by KyleAMathews** [comment]
Let's create separate issues for each component/package. That'll make it simpler to know when something is done + for people to claim work.

**Comment by shobhitchittora** [comment]
@KyleAMathews will do that!
@alexandernanberg any reason to not use `enzyme` and `jest` snapshots here.
