### ISSUE TITLE
styling {children}

### ISSUE THREAD

**Issue by horak** [gatsbyjs/gatsby#709]
I'm using the Gatsby Starter Blog and would like to style my pages a bit differently. Adding additional css files is not a problem, but in keeping with the best practices described in the [readme](https://github.com/gatsbyjs/gatsby#inline-css), I'd like to understand how to style those inline making use of that nifty head-injected css. 

I've been trying to add styles the `{{children}}` prop within `_template.js`, am I barking up the wrong tree?

Ideally, I'm just looking to, for example, change the padding on the `<h3>`'s on my pages.

**Comment by KyleAMathews** [comment]
So what you want to do then is first, create a file called `main.css` in your site root.

Put there:

```css
h1 {
    padding: 10px;
}
```

Then at the top of your `_template.js` file — write `import "../main.css"`.

Now run `gatsby develop` and open the site on localhost and verify the css is loaded. Now you should be able to make changes to the css, save it, and see the changes hot reload.

**Comment by horak** [comment]
Gotcha, that's what I have been doing and thought there was maybe a more proper way. I'm assuming then that those styles, so those in `main.css` et al., are then also being injected into `<head>`? Via webpack?

Fantastically speedy response and fantastic service, great work.

**Comment by KyleAMathews** [comment]
Yeah, via webpack.

There are many styling options but this is the easiest to get going with.

**Comment by KyleAMathews** [comment]
Adding elements? Everything happens via React.js components so in one of those.

**Comment by horak** [comment]
Thanks, @KyleAMathews.
