### ISSUE TITLE
[gatsby-image] Snapshot test for gatsby-image

### ISSUE THREAD

**Issue by shobhitchittora** [gatsbyjs/gatsby#7099]
Refs: #7089

This is an extension / ref to the above mentioned issue.

To Snapshot testing for [`gatsby-image`](https://www.gatsbyjs.org/packages/gatsby-image/?=gatsby-images) component, we have 2 choices - 

1. `enzyme` with `jest`
2.  `react-testing-library`

I want to have a clear understanding of which to use for the purpose ( I've personally used enzyme with jest and it works great ).

**Comment by alexandernanberg** [comment]
You can actually use `Jest` with `react-testing-library` as well (it's even prefered and how I did it for the `gatsby-link` snapshots). I think the [readme](https://github.com/kentcdodds/react-testing-library/blob/master/README.md) describes what it is and why you want it really well. 

> So rather than dealing with instances of rendered react components, your tests will work with actual DOM nodes. The utilities this library provides facilitate querying the DOM in the same way the user would.

But I guess it's personal preference also,  though I'd vote for keeping consistency between packages for which testing libraries we use.

**Comment by shobhitchittora** [comment]
@alexandernanberg good point. I guess `react-testing-library` has gained some traction now a days. I'd like as much input as we can on this. 

cc: @m-allanson @KyleAMathews
