### ISSUE TITLE
Collect all components / plugin which can benefit from Snapshot testing

### ISSUE THREAD

**Issue by shobhitchittora** [gatsbyjs/gatsby#7100]
### Motivation
The motivation here to have a better code coverage and testing experience for the project. This will help smoothen the experience of contributing to the project and help new comers. Finally, more visibility!

### Checklist 

  - [x] `gatsby-link` - #7089
  - [x] `gatsby-image` - #7099

Please provide more pointers to add to the list, so that they can be taken up individually.

**Comment by calcsam** [comment]
Thanks @shobhitchittora! I'm going to close this issue since the two bullet points you highlighted are done -- if you have more please add them & reopen!
