### ISSUE TITLE
[v2] Huge bundle size difference between v1 and v2

### ISSUE THREAD

**Issue by solarsailer** [gatsbyjs/gatsby#7104]
## Description

I ported my website to Gatsby 2 this morning. I followed the migration guide and it went fine. 👍

However, when comparing the bundle size of my [live website](https://solarsailer.net/) (still using Gatsby 1) and the branch with Gatsby 2, I saw a huge difference between the two.

With Gatsby 1: **181KB**.

![v1](https://user-images.githubusercontent.com/478621/43775745-0e226a2e-9a4e-11e8-8ecf-4afccd8b2a9b.png)

With Gatsby 2: **397KB**.

![v2](https://user-images.githubusercontent.com/478621/43775751-14947c1c-9a4e-11e8-973a-45c24346034d.png)

I can see new files too.

I might have overlooked something while doing the migration, but the site is exactly the same nonetheless (visually speaking).

What could explain this difference? It's almost 200kb more. That's a lot.

### Steps to reproduce

Migrate from Gatsby 1 to 2.

### Expected result

Equivalent bundle size between Gatsby 1 and Gatsby 2. 

I would have expected smaller bundle size thanks to React 16.

### Actual result

Bundle size has doubled.

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
    Shell: 2.7.1 - /usr/local/bin/fish
  Binaries:
    Node: 10.7.0 - /usr/local/bin/node
    Yarn: 1.9.2 - /usr/local/bin/yarn
    npm: 6.2.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.84
    Firefox: 61.0.1
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-beta.74 
    gatsby-paginate: ^1.0.16 => 1.0.16 
    gatsby-plugin-google-analytics: next => 2.0.0-beta.4 
    gatsby-plugin-lodash: next => 3.0.1-beta.3 
    gatsby-plugin-nprogress: next => 2.0.0-beta.4 
    gatsby-plugin-react-helmet: next => 3.0.0-beta.4 
    gatsby-plugin-sitemap: next => 2.0.0-beta.3 
    gatsby-plugin-styled-components: next => 3.0.0-beta.3 
    gatsby-remark-prismjs: next => 3.0.0-beta.5 
    gatsby-source-filesystem: next => 2.0.1-beta.10 
    gatsby-transformer-remark: next => 2.1.1-beta.6 
```

### File contents (if changed)

`gatsby-config.js`: No diff.

`package.json`: 

```
  "scripts": {
    "start": "gatsby develop",
    "build": "gatsby build",
    "serve": "gatsby serve",
    "prod": "gatsby build && gatsby serve",
    "deploy": "gatsby build && gh-pages -d public -b master -r git@github.com:solarsailer/solarsailer.github.io.git"
  },
  "dependencies": {
    "@sindresorhus/is": "^0.11.0",
    "babel-plugin-styled-components": "^1.5.1",
    "gatsby": "next",
    "gatsby-paginate": "^1.0.16",
    "gatsby-plugin-google-analytics": "next",
    "gatsby-plugin-lodash": "next",
    "gatsby-plugin-nprogress": "next",
    "gatsby-plugin-react-helmet": "next",
    "gatsby-plugin-sitemap": "next",
    "gatsby-plugin-styled-components": "next",
    "gatsby-remark-prismjs": "next",
    "gatsby-source-filesystem": "next",
    "gatsby-transformer-remark": "next",
    "lodash": "^4.17.10",
    "polished": "^1.9.3",
    "prismjs": "^1.15.0",
    "react": "^16.4.2",
    "react-dom": "^16.4.2",
    "react-helmet": "^5.2.0",
    "react-pose": "^2.2.0",
    "styled-components": "^3.4.1",
    "xml": "^1.0.1"
  },
  "devDependencies": {
    "gh-pages": "^1.2.0",
    "husky": "^0.14.3",
    "jest": "^23.4.0"
  }
```

`gatsby-node.js`: No diff. 
`gatsby-browser.js`: No diff.
`gatsby-ssr.js`: No diff.

Thanks.

**Comment by KyleAMathews** [comment]
Are you comparing gzipped to non-gzipped size by chance?

The default gatsby bundle size is 15-20kb smaller (haven't measured exact numbers is a while). There's perhaps differences in how webpack does code splitting/bundling that could account for the difference but unlikely it's this large.

You could also go through your bundles with https://www.npmjs.com/package/source-map-explorer to see if you accidentally pulled in a large package or two.

**Comment by solarsailer** [comment]
It's seem that `gatsby serve` v2 doesn't gzip, contrary to v1. 

I was comparing a production build of v1 vs my live site, and it was the same size. I expected v2 to behave the same. :)

My bad. Sorry.

(And a gzipped build of v2 is indeed a bit lighter - 30kb~)
