### ISSUE TITLE
Add hash to the `location` prop in @reach/router

### ISSUE THREAD

**Issue by lipis** [gatsbyjs/gatsby#7107]
While I have access to it during `develop` I'm getting an error during build:

```

  26 |   getHash() {
> 27 |     return parseInt(this.props.location.hash.slice(1)) || LIMIT;
  28 |   }
  29 |


  WebpackError: TypeError: Cannot read property 'slice' of undefined
```

**Comment by KyleAMathews** [comment]
Yes, we switched to @reach/router. Please check out the migration guide! Would love your feedback on it if there's anything missing or where we can help make it better. https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#migrate-from-react-router-to-reachrouter

**Comment by KyleAMathews** [comment]
That being said, I'm not sure why it'd work in development and not in production.

**Comment by Chuloo** [comment]
What file is this script located?

**Comment by lipis** [comment]
@KyleAMathews Actually without making any change the website became very very slow when navigating.. :( Am I holding it wrong?

**Comment by Chuloo** [comment]
@lipis can you share a simple reproduction repo showing your error? or precise steps to reproduce it.

**Comment by KyleAMathews** [comment]
Known issue on slowness https://github.com/gatsbyjs/gatsby/issues/7068

But yeah, would love to know more about where/how you're using location prop.

**Comment by lipis** [comment]
@Chuloo I will try to if I have time today.

**Comment by lipis** [comment]
Here is the minimal example of the said error and how it's used in the actual project:

```js
import React from 'react'
import Layout from '../components/layout'

class IndexPage extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      limit: this.getHash(),
    }
  }

  getHash() {
    return parseInt(this.props.location.hash.slice(1)) || 4
  }

  render() {
    console.log('location', this.props.location)
    return (
      <Layout>
        <h1>Limit {this.state.limit}</h1>
      </Layout>
    )
  }
}

export default IndexPage
```

You can checkout the whole project as is https://github.com/lipis/gatsby-location

Works as expected during `develop` but throwing an error during build.

```
 11 |
  12 |   getHash() {
> 13 |     return parseInt(this.props.location.hash.slice(1)) || 4
     |                                              ^
  14 |   }
  15 |
  16 |   render() {


  WebpackError: TypeError: Cannot read property 'slice' of undefined
```

**Comment by KyleAMathews** [comment]
Oh yeah — it seems @reach/router doesn't set a hash on the location object automatically, at least when server rendering. @ryanflorence is that something that'd be reasonable to add to @reach/router?

**Comment by KyleAMathews** [comment]
(also @lipis thanks for the nice reproduction site 💯)

**Comment by millette** [comment]
Ah, that's probably why my react-intl based site got borked when deployed with a sitePrefix. Working on fixing it, glad I found this issue in migration guide.

**Comment by lipis** [comment]
@KyleAMathews @ryanflorence What's the status with the `location.hash`.. we are stuck in the older versions because of that.. :/ and there are daily updates.. we don't want to be far behind.

**Comment by KyleAMathews** [comment]
@lipis you can check if location.hash exists before trying to access. Will see about adding it to @reach/router as well.

**Comment by lipis** [comment]
Should I change the title accordingly for this issue?

**Comment by KyleAMathews** [comment]
That'd be great

**Comment by lipis** [comment]
Updated.. feel free to edit it as well if it doesn't make sense :)

**Comment by lipis** [comment]
Are we doing this? Would be nice.

**Comment by wardpeet** [comment]
@lipis it should work now as reach router added search & hash props to SSR part of reach router. Could you give it another spin?

https://github.com/reach/router/blob/b60e6dd781d5d3a4bdaaf4de665649c0f6a7e78d/CHANGELOG.md#v120
