### ISSUE TITLE
When updating the styled-components from 3.3.3 to 3.4.0 the order of extended components is not kept.

### ISSUE THREAD

**Issue by lipis** [gatsbyjs/gatsby#7112]
I couldn't reproduce the error in a simple example, but I'm wondering if there is anyone else experienced this issue.

Works fine during develop mode, but not when rendered.. I'm using the latest v2.

**Comment by Chuloo** [comment]
Can you share whichever example throws the error?

**Comment by lipis** [comment]
I couldn't reproduce it with simple example.

We are using [@wireapp/react-ui-kit](https://www.npmjs.com/package/@wireapp/react-ui-kit) (it's our own) and it has a different behaviour when running in develop mode.

Reproducible example: https://github.com/lipis/gatsby-styled 


`develop`
<img width="896" alt="screen shot 2018-08-07 at 22 06 25" src="https://user-images.githubusercontent.com/125676/43799614-588ab96e-9a8e-11e8-89b7-0cabdf6f8f6c.png">

`serve`
<img width="898" alt="screen shot 2018-08-07 at 22 07 12" src="https://user-images.githubusercontent.com/125676/43799619-5a3bc69a-9a8e-11e8-935f-69cb97f4a97e.png">

Maybe we are doing something wrong in the [our own framework](https://github.com/wireapp/wire-web-packages/tree/master/packages/react-ui-kit), but it worked as expected with 3.3.3 :)

**Comment by Yserz** [comment]
I wonder what kind of optimisations Gatsby is running on the CSS when building the project in production mode since this is not happening in development mode.

**Comment by lipis** [comment]
@KyleAMathews @Chuloo any idea for this issue? It started with 3.4.0 actually.

**Comment by Chuloo** [comment]
Tried running your reproduction but everything worked fine. @lipis, waiting for who else has run into the same error.

**Comment by lipis** [comment]
Thanks for bringing that up... it works now like a glove.. so let's forget about it :)
