### ISSUE TITLE
Serve different pages on the same URL

### ISSUE THREAD

**Issue by kareldurdis** [gatsbyjs/gatsby#7117]
## Summary
Hi,
I'm trying to serve different pages on the same URL according to HTTP Header. 
I've generated `/somePage/abc` and `/somePage/xyz` variants and I'm doing the internal rewrite on nginx to serve the correct one on `/somepage` URL.
The rewrite works just fine, but when the JS bundle loads it redirects me to 404 as it doesn't know the `/somePage` path.

### Environment (if relevant)

  npmPackages:
    gatsby: ^1.9.241 => 1.9.241 
    gatsby-link: ^1.6.39 => 1.6.39 
    gatsby-plugin-react-helmet: ^2.0.8 => 2.0.8 
    gatsby-plugin-react-next: ^1.0.11 => 1.0.11 
    gatsby-source-filesystem: ^1.5.27 => 1.5.27 

### File contents (if changed)
`gatsby-node.js`: part that generates the variants
```
        variants.forEach((variant) => {
          createPage({
            path: `/${targetSlug}/${variant}`,
            component: pageComponentPath,
            layout: LAYOUT,
            context: {
              variant,
            },
          });
        });
```
What is the correct approach to this kind of problem? Am I missing something on how to "fool" the JS router, or something else? Thanks in advance.

**Comment by LeKoArts** [comment]
If I understood you correctly:
Have a look at the „pathPrefix“ option

**Comment by KyleAMathews** [comment]
Hey! We've talked about the idea of supporting page "variants" but this has happened yet. This would need to be supported in core so that you can say that page x is really y once it loads.

**Comment by wzrdzl** [comment]
@KyleAMathews do you have already some thought or consideration how to implement it in the core, maybe we could help with contributing this functionality

**Comment by millette** [comment]
How would a static http server know how to deal with this? Wouldn't it depend on nginx, apache http, etc.?

For instance, if I want ```index.html.en``` and ```index.html.fr``` to serve content based on negotiated language, I have to setup the http server for it, or is there a generic way?

Also, I would rename the issue to something like "Serve different representations of a page based on headers".

**Comment by KyleAMathews** [comment]
>do you have already some thoughts or considerations how to implement it in the core, maybe we could help with contributing this functionality

Not a ton but basically it'd need to extend Gatsby's "page" concept to include the idea of variants which would mean adding support for this to `createPage` and to our page matching in the runtime.

**Comment by wzrdzl** [comment]
@millette serving the page is not a concern of Gatsby, so yes the logic of picking up the right page has to live on your HTTP server. The logic could be based on anything pretty much, not only headers.
E.g. during maintenance when user visits my `mywebsite.com/welcome` I would like to serve the page from `gatsbyBuild/maintenance.html` instead of `gatsbyBuild/welcome.html` while preserving the URL in the browser (do rewrite instead of redirect).

The issue right now is that I cannot do this because JS bundle that comes with the page checks `window.location` and downloads the JS chunks for that URL (`welcome.js` in our case). That JS chunk then runs and corrupts the page entirely because it tries to render (reconcile) the React tree for the welcome page.

**Comment by b4stien** [comment]
Hi there. At my company we'd be willing to contribute time (or money) to contribute on this issue, do you have any other reference where this question has been discussed?

(our use case is server side AB testing where we want to send a variant of the requested page)

**Comment by KyleAMathews** [comment]
Not afaik! But happy to jump on a call with you sometime to discuss the idea. There'd need to be an RFC written up before we start implementation.

**Comment by joseflores8082** [comment]
any possible updated on this? or possible work arounds? I I would love to work with someone on this to get this feature introduced.

**Comment by ArpitaSrivas** [comment]
Hi,

Any updates on this? Are we going to have the support of page variants in future?

**Comment by geraldstrobl** [comment]
@ArpitaSrivas I have the same issue.

**Comment by id0Sch** [comment]
is there any progress/workaround for this issue?
we use Gatsby extensively and would really benefit from this as we currently "hurt" our UX intentionally (added loaders and skeletons) to render the correct page on the client.

we would really like to generate all our variants on build time and decide which to serve when the user requests the page.
If there was any way to "opt-out" from the concept that the rendered page "cares" about the URL it would be super beneficial.
