### ISSUE TITLE
Replace "serve" package w/ express for "gatsby serve"

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#7119]
`serve` recently took away many of the nice things about the package e.g. included gzip support.

We want that.

So let's just switch to express w/ a compression middleware.

**Comment by millette** [comment]
Or [micro](https://www.npmjs.com/package/micro) ?

**Comment by KyleAMathews** [comment]
It doesn't do compression afaik

**Comment by KyleAMathews** [comment]
Ah cool. Does it do static file serving? Any particular reason to use it over express?

**Comment by azdanov** [comment]
> Does it do static file serving? Any particular reason to use it over express?

Need to be done manually. Express is simpler, with its built-in middleware.
