### ISSUE TITLE
wrapRootComponent for using Redux provider doesn't work as described in docs

### ISSUE THREAD

**Issue by anthonysapp** [gatsbyjs/gatsby#712]
The default **wrapRootComponent** functionality in gatsby-browser.js as described in the release notes for EG. using a Redux provider doesn't seem to be working. Here's the code suggested in [release notes](https://github.com/gatsbyjs/gatsby/releases/tag/v0.12.34):

```
import { Provider } from 'react-redux';
import store from './store';

exports.wrapRootComponent = (Root) => (
  <Provider store={store}>
    <Root />
  </Provider>
)
```
Using the above code generates the errors:
<img width="1260" alt="screen shot 2017-03-10 at 11 16 02 am" src="https://cloud.githubusercontent.com/assets/5347604/23802968/0399cce8-0583-11e7-98ad-72d4022c4db3.png">

Here's what I needed to do to make it work:
```
import { Provider } from 'react-redux';
import store from './store';

exports.wrapRootComponent = Root => {
  return () => (
    <Provider store={store}>
      <Root />
    </Provider>
  );
};
```

Not 100% sure if this is an actual bug or just something I'm missing.

**Comment by KyleAMathews** [comment]
Oh right... :-) Gah, this sort of thing is the most confusing part of JSX for me. Weird, I thought I'd tested that but apparently not. I've updated the release notes. Thanks!

**Comment by baseten** [comment]
I'm having an issue with this too. Lifting the example code from the documentation I first get an error  - `ReferenceError: React is not defined`. If I then add the import like so:

```
import React from 'react';
import { Provider } from 'react-redux';
import store from './store';

exports.wrapRootComponent = Root => {
    return () => (
        <Provider store={ store }>
            <Root />
        </Provider>
    );
};
```

I get the error: `Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

**Comment by baseten** [comment]
Apologies, the old method is still the first in Google search results. Have found the redux example on the master branch - https://github.com/gatsbyjs/gatsby/blob/master/examples/using-redux/gatsby-browser.js
