### ISSUE TITLE
Gatsby may not be installed. Perhaps you need to run "npm install"?

### ISSUE THREAD

**Issue by jel111** [gatsbyjs/gatsby#7122]
user ~/S/tutorial-part-two> gatsby develop
error There was a problem loading the local develop command. Gatsby may not be installed. Perhaps you need to run "npm install"?

macuser@iMac ~/S/tutorial-part-two> npm install --save gatsby-plugin-emotion emotion react-emotion emotion-server
npm WARN gatsby-plugin-typography@1.7.19 requires a peer of gatsby@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-react-router-scroll@2.0.0-beta.4 requires a peer of react-router-dom@^4.0 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-plugin-emotion@1.1.17 requires a peer of gatsby@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-starter-hello-world@ No repository field.

 Getting this everytime I install a plugin. Have to remove node modules and then run npm install again.
Then I get this but compiles. Soon as I try to add another plug-in it is the same thing all over again.

fsevents@1.2.4 install /Users/macuser/Sites/tutorial-part-two/node_modules/fsevents
> node install

[fsevents] Success: "/Users/macuser/Sites/tutorial-part-two/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm WARN gatsby-starter-hello-world@ No repository field.

**Comment by danoc** [comment]
Hi @jel11 — What's in your `package.json` file?

**Comment by jel111** [comment]
{
  "name": "gatsby-starter-hello-world",
  "description": "Gatsby hello world starter",
  "license": "MIT",
  "scripts": {
    "develop": "gatsby develop",
    "build": "gatsby build",
    "serve": "gatsby serve"
  },
  "dependencies": {
    "emotion": "^9.2.6",
    "emotion-server": "^9.2.6",
    "gatsby": "next",
    "gatsby-plugin-emotion": "^1.1.17",
    "gatsby-plugin-typography": "^1.7.19",
    "gatsby-source-filesystem": "^1.5.39",
    "gatsby-transformer-remark": "^1.7.44",
    "react": "^16.3.2",
    "react-dom": "^16.3.2",
    "react-emotion": "^9.2.6",
    "react-typography": "^0.16.13",
    "typography": "^0.16.17",
    "typography-theme-bootstrap": "^0.16.7",
    "typography-theme-fairy-gates": "^0.15.11",
    "typography-theme-kirkham": "^0.16.3",
    "typography-theme-lawton": "^0.15.10"
  }
}

**Comment by LeKoArts** [comment]
> "gatsby-plugin-emotion": "^1.1.17",
"gatsby-plugin-typography": "^1.7.19",
"gatsby-source-filesystem": "^1.5.39",
"gatsby-transformer-remark": "^1.7.44",


You need to install these with the @next tag

**Comment by LekoArts** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
