### ISSUE TITLE
Unspecified Webpack Error when using V2 guide PostCSS

### ISSUE THREAD

**Issue by coreyward** [gatsbyjs/gatsby#7123]
## Description

Running `gatsby build` when using the fairly minimal PostCSS setup suggested in the [v1 to v2 upgrade guide](https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#restore-v1-postcss-plugin-setup) an unspecified error occurs:

```
error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  31 |     if (!plugin.plugin[api]) {
  32 |       return undefined
> 33 |     }
     |      ^
  34 |     const result = plugin.plugin[api](args, plugin.options)
  35 |     return result
  36 |   })


  WebpackError: ./src/components/header.module.css
  
  - api-runner-ssr.js:33 childCompiler.runAsChild
    lib/.cache/api-runner-ssr.js:33:6
```

### Steps to reproduce

I've created a [demo repo available here](https://github.com/coreyward/gatsby-webpack-error-demo). To reproduce the error, install dependencies with Yarn and run `gatsby build`.

### Environment

  System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 10.7.0 - /usr/local/bin/node
    Yarn: 1.9.2 - /usr/local/bin/yarn
    npm: 6.2.0 - /usr/local/bin/npm
  npmPackages:
    gatsby: next => 2.0.0-beta.76 
    gatsby-plugin-manifest: next => 2.0.2-beta.4 
    gatsby-plugin-offline: next => 2.0.0-beta.9 
    gatsby-plugin-postcss: ^1.0.0 => 1.0.0 
    gatsby-plugin-react-helmet: next => 3.0.0-beta.4 

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by KyleAMathews** [comment]
Ran your reproduction and there is indeed some sort of issue. Thanks for the nice reproduction.

**Comment by m-allanson** [comment]
@coreyward I was scratching my head over this for a while, turns out it's there's a quick fix! Update the plugin version to `gatsby-plugin-postcss@next` 😅 

We're in a temporary state at the moment with the v2 betas so it's a bit confusing to work out correct plugin versions - this is something that lots of folks are tripping on and Gatsby could be more helpful about making sure you're using the compatible plugin versions. I'll write up a separate issue.

**Comment by m-allanson** [comment]
I wrote up an issue here https://github.com/gatsbyjs/gatsby/issues/7143

**Comment by coreyward** [comment]
@m-allanson Can't believe I missed that. 😅 Strangely, it worked fine under `gatsby develop`.

**Comment by m-allanson** [comment]
haha well it's pretty easy to miss! Particularly when it works for `gatsby develop`
