### ISSUE TITLE
[v2] Use location polyfill when calling onRouteUpdate

### ISSUE THREAD

**Issue by andrewoesten** [gatsbyjs/gatsby#7141]
onRouteUpdate is called with `window.history.location` which doesn't seem to be necessarily filled (I read the specs but couldn't really find window.history.location, hmmmm....?) so I would change this to `window.history.location || window.location`

See cache-dir/root.js, around line 46:

```
// Call onRouteUpdate on the initial page load.
apiRunner(`onRouteUpdate`, {
  location: window.history.location,
})
```

**Comment by KyleAMathews** [comment]
Conveniently was working on a fix for this at the same time you posted this ;-) https://github.com/gatsbyjs/gatsby/pull/7142

Just published the fix in beta.86 so upgrade and enjoy!
