### ISSUE TITLE
Markdown example using 1.0

### ISSUE THREAD

**Issue by tonyxiao** [gatsbyjs/gatsby#715]
Is there an example of using Markdown with Gatsby 1.0? I can't seem to find it.

**Comment by KyleAMathews** [comment]
The gatsbyjs website: https://github.com/gatsbyjs/gatsby/tree/1.0/www

And my blog: https://github.com/KyleAMathews/blog

**Comment by KyleAMathews** [comment]
Also read docs https://www.gatsbyjs.org/docs/packages/gatsby-typegen-remark/

**Comment by tonyxiao** [comment]
Awesome, thanks!

**Comment by viktorsmari** [comment]
Came here by Googling '**gatsby markdown**', but these links are dead. Update please?

**Comment by KyleAMathews** [comment]
@viktorsmari weird this very old & insignificant issue is showing up first for "gatsby markdown"!

A few links:

* Official tutorial https://www.gatsbyjs.org/tutorial/
* Community tutorial, many of which talk about Gatsby & Markdown https://www.gatsbyjs.org/docs/awesome-gatsby/#gatsby-tutorials
* This blog post walking through creating a blog w/ Gatsby https://www.gatsbyjs.org/blog/2017-07-19-creating-a-blog-with-gatsby/
