### ISSUE TITLE
[v2] examples/using-page-transitions -- gatsby-browser.js -- fails with CommonJS/ES6 combination error

### ISSUE THREAD

**Issue by jarodtaylor** [gatsbyjs/gatsby#7151]
## Description

Trying to update to v2 from a fork of examples/using-page-transitions and I was having issues due to the Babel 7 requirement to choose CommonJS or ES6 and to not use both inside of a file. So, I went ahead and grabbed the most recently[ up to date version of the file](https://github.com/gatsbyjs/gatsby/blob/master/examples/using-page-transitions/gatsby-browser.js).

When running `gatsby develop` I'm getting this error:
![image](https://user-images.githubusercontent.com/362248/43844203-ca4ed34a-9aee-11e8-8d89-d82ee3636b95.png)

The culprit is [these lines of code](https://github.com/gatsbyjs/gatsby/blob/master/examples/using-page-transitions/gatsby-browser.js#L15-L20):
```
let history
if (typeof document !== 'undefined') {
  history = createHistory({ getUserConfirmation })
  // block must return a string to conform
  history.block((location, action) => location.pathname)
}
```

If I comment out the code within the if block, and throw in `console.log('bla bla bla')` it compiles fine. If I throw in `history = 2` I get the same error as above. 

I'm not sure why this would cause this.

## EDIT
I even just started a new repo using:
```
gatsby new using-page-transitions https://github.com/gatsbyjs/gatsby-starter-default\#v2
```
Then I added the using-page-transitions gatsby-browser.js code from the example/using-page-transitions. The same error occurred.

**Comment by KyleAMathews** [comment]
Sorry about that — I didn't test this new check very throughly. Fix released in 2.0.0-beta.87
