### ISSUE TITLE
Cannot find module webpack/lib/removeAndDo

### ISSUE THREAD

**Issue by aayushineeshu** [gatsbyjs/gatsby#7155]
Below is the error that  i am getting an not able to identify my mistake it came while solving gatsby tutorial part four.....
error There was a problem loading the local develop command. Gatsby may not be installed. Perhaps you need to run "npm install"?

  Error: Cannot find module 'webpack/lib/removeAndDo'

  - loader.js:581 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:581:15

  - loader.js:507 Function.Module._load
    internal/modules/cjs/loader.js:507:25

  - loader.js:637 Module.require
    internal/modules/cjs/loader.js:637:17

  - helpers.js:20 require
    internal/modules/cjs/helpers.js:20:18

  - ExtractedModule.js:30 Object.<anonymous>
    [tutorial-part-four]/[gatsby-1-config-extract-plugin]/[extract-text-webpack-plugin]/ExtractedModule.js:30:42

  - loader.js:689 Module._compile
    internal/modules/cjs/loader.js:689:30

  - loader.js:700 Object.Module._extensions..js
    internal/modules/cjs/loader.js:700:10

  - loader.js:599 Module.load
    internal/modules/cjs/loader.js:599:32

  - loader.js:538 tryModuleLoad
    internal/modules/cjs/loader.js:538:12

  - loader.js:530 Function.Module._load
    internal/modules/cjs/loader.js:530:3

  - loader.js:637 Module.require
    internal/modules/cjs/loader.js:637:17

  - helpers.js:20 require
    internal/modules/cjs/helpers.js:20:18

  - index.js:7 Object.<anonymous>
    [tutorial-part-four]/[gatsby-1-config-extract-plugin]/[extract-text-webpack-plugin]/index.js:7:23

  - loader.js:689 Module._compile
    internal/modules/cjs/loader.js:689:30

  - loader.js:700 Object.Module._extensions..js
    internal/modules/cjs/loader.js:700:10

  - loader.js:599 Module.load
    internal/modules/cjs/loader.js:599:32

  - loader.js:538 tryModuleLoad
    internal/modules/cjs/loader.js:538:12

  - loader.js:530 Function.Module._load
    internal/modules/cjs/loader.js:530:3

  - loader.js:637 Module.require
    internal/modules/cjs/loader.js:637:17

  - helpers.js:20 require
    internal/modules/cjs/helpers.js:20:18

  - index.js:3 Object.<anonymous>
    [tutorial-part-four]/[gatsby-1-config-extract-plugin]/index.js:3:33

  - loader.js:689 Module._compile
    internal/modules/cjs/loader.js:689:30

**Comment by Chuloo** [comment]
try using `yarn` instead of `npm` do you get the same error?

**Comment by kakadiadarpan** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates.

Please make sure to update to the latest Gatsby version and check if that solves the issue. Let us know if that works for you by adding a comment 👍

**Comment by kakadiadarpan** [comment]
This issue is being closed because there hasn't been any activity for at least 30 days. Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem 👍
