### ISSUE TITLE
reorganize guides - preparing your environment

### ISSUE THREAD

**Issue by amberleyromo** [gatsbyjs/gatsby#7164]
Related: #6590.

As we work through the top-level stubs, keeping notes on overall architecture thoughts and discussions to address later (as discussed, @shannonbux).

- Preparing your environment
  - Basic hardware and software requirements
    - I think this is unnecessary / covered by the overview. Not sure what hardware requirements we'd be discussing.
  - Browser Support
    - I think this should move. This is more relevant to working on Gatsby sites than dev environment.
  - Gatsby on Macs
    - 👍🏼
  - Gatsby on Windows
    - 👍🏼

**Comment by shannonbux** [comment]
Great! Just like with #6590, would you link this and future docs nav enhancements to [EPIC] Docs IA redesign phase 2?
