### ISSUE TITLE
Trying to add loader to modifyWebpackConfig not working

### ISSUE THREAD

**Issue by jncampbell** [gatsbyjs/gatsby#7168]
## Summary
I'm converting an existing app to Gatsby. In the OG app, I'm using webpack and the `sass-resources-loader` plugin to @import my SASS resources into every required SASS module so that I don't have to explictly import them. The related webpack config current looks like: 
```
//in the webpack modules object
module: {
  rules: [
    // Apply loader
    {
      test: /\.scss$/,
      use: [
        {
          loader: 'sass-resources-loader',
          options: {
            resources: path.join(__dirname, 'src', 'styles', '_variables.scss'
          },
        },
      ],
    },
  ],
},
```

The Gatsby version of this uses the `gatsby-node.js` file and looks like the following:
```
const path = require('path')

exports.modifyWebpackConfig = ({config, stage}) => {
  config.merge({
    resolve: {
      alias: {
        '@@components': path.join(__dirname, 'src', 'components')
      }
    },
    module: {
      rules: [
        {
          test: /\.scss$/,
          use: [
            {
              loader: 'sass-resources-loader',
              option: {
                resources: path.join(__dirname, 'src', 'styles', '_variables.scss')
              }
            }
          ]
        }
      ]
    }
  })

  return config
}
```
However, when I run the `gatsby develop` command, I receive an error that says 
```
There were errors with your webpack config:
[1]
module.rules
object.allowUnknown , "rules" is not allowed
```
which sounds like a general webpack error. I did some inspecting and saw that gatsby version I'm using depends on webpack v1 but when I use the sass-resources-loader format corresponding to that version, but that throws errors as well

Can anyone help me in figuring out the correct way to handle this?

## Relevant information
Node version = 8.5.0
Gatsby version = ^1.9.277
sass-resources-loader version = ^1.3.3

### File contents (if changed)

`gatsby-config.js`:
```
module.exports = {
  siteMetadata: {
    title: 'Gatsby Default Starter',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-sass'
  ],
}
```

`package.json`:
```
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "gatsby": "^1.9.277",
    "gatsby-link": "^1.6.46",
    "gatsby-plugin-react-helmet": "^2.0.11",
    "gatsby-plugin-sass": "^1.0.26",
    "react-helmet": "^5.2.0",
    "sass-resources-loader": "^1.3.3"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write 'src/**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "prettier": "^1.13.7"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  }
}

```
`gatsby-node.js`:
```
/**
 * Implement Gatsby's Node APIs in this file.
 *
 * See: https://www.gatsbyjs.org/docs/node-apis/
 */

 // You can delete this file if you're not using it
const path = require('path')

exports.modifyWebpackConfig = ({config, stage}) => {
  config.merge({
    resolve: {
      alias: {
        '@@components': path.join(__dirname, 'src', 'components')
      }
    },
    module: {
      rules: [
        {
          test: /\.scss$/,
          use: [
            {
              loader: 'sass-resources-loader',
              option: {
                resources: path.join(__dirname, 'src', 'styles', '_variables.scss')
              }
            }
          ]
        }
      ]
    }
  })

  return config
}
```
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by kakadiadarpan** [comment]
Hey James,

Thanks for providing the detailed information. I can see that you are using `gatsby-plugin-sass` for styles in your app. When you are using `gatsby-plugin-sass`, you can configure it the following way in `gatsby-config.js`:
```js
// in gatsby-config.js
plugins: [
'gatsby-plugin-react-helmet',  // it already exists in your plugins list
  {
    resolve: `gatsby-plugin-sass`,
    options: {
      // your configuration options
    },
  },
];
```

Since there is a plugin available for `sass` in Gatsby plugins library built that handles your use case , you can remove the `module` part from your `gatsby-node.js` configuration. You can get more information about gatsby-plugin-sass [here](https://www.gatsbyjs.org/packages/gatsby-plugin-sass/?=sass).

The error that you are getting is because Gatsby expects custom webpack configuration in a specific way. You can get more information regarding that [here](https://www.gatsbyjs.org/docs/add-custom-webpack-config/).

**Comment by jncampbell** [comment]
@kakadiadarpan Thank you for your response!

Forgive me if I'm wrong, but doesn't the `gatsby-plugin-sass` correspond to the `sass-loader` package? Where in my case, I'm trying to use the `sass-resources-loader` plugin, which I don't think has a corresponding gatsby plugin

**Comment by kakadiadarpan** [comment]
@jncampbell You can do that by providing options to `gatsby-plugin-sass`. I was able to do this with the following configuration:
```js
plugins: [
    'gatsby-plugin-react-helmet',
    {
      resolve:'gatsby-plugin-sass',
      options: {
        loader: 'sass-resources-loader',
        options: {
          // Provide path to the file with resources
          resources: './path/to/resources.scss'
        },
      },
    }
  ],
```

Let me know if this works for you.

**Comment by jncampbell** [comment]
@kakadiadarpan Unfortunately, that didn't work. I was able to get run `gatsby develop` without any errors but the `sass-resources-loader` doesn't seem to be running. Interesting to note, too, that when I change `sass-resources-loader` to anything string, it still builds without errors. So, for instance, 

```
plugins: [
    'gatsby-plugin-react-helmet',
    {
      resolve:'gatsby-plugin-sass',
      options: {
        loader: 'sass-resousdfadfafarces-loader', <- Notice this gobbledy-gook
        options: {
          // Provide path to the file with resources
          resources: './path/to/resources.scss'
        },
      },
    }
  ],
```
this will still run without errors. Normally, an error would be thrown saying "plugin couldn't be found/resolved" or something to that effect so I'm not sure if the build is skipping over this section all together

**Comment by kakadiadarpan** [comment]
@jncampbell Gatsby uses webpack version `1.15.0`, so the setup is a little bit tricky.

In the documentation of `sass-resources-loader`, for webpack version `1.x.x` the [usage](https://github.com/shakacode/sass-resources-loader#usage) is done in the following way:

```js
/* Webpack@1: webpack.config.js */

module: {
  loaders: [
    // Apply loader
    { test: /\.scss$/, loader: 'style!css!sass!sass-resources' },
  ],
},

// Provide path to the file with resources
sassResources: ['./path/to/vars.scss', './path/to/mixins.scss'],
```
Here is how you can do the same configuration in Gatsby:
```js
// in gatsby-config.js
plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-sass'
],
```
```js
// in gatsby-node.js
exports.modifyWebpackConfig = ( { config, stage } ) => {
  config.loader("sass-resources", {
    test: /\.scss$/,
    loader: 'sass-resources',
  });
  config.merge({
    sassResources: [
      './src/styles/index.scss'
    ]
  })
  return config;
};
```

**Comment by kakadiadarpan** [comment]
@jncampbell I have created a gatsby plugin for `sass-resources-loader` which supports Gatsby version `1.x.x` currently.

How to use:
```js
plugins: [
    'gatsby-plugin-sass',
    {
      resolve: `gatsby-plugin-sass-resources`,
      options: {
        // Provide the path to the files with resources
        resources: ['./src/styles/index.scss']
      },
    },
  ],
```

[gatsby-plugin-sass-resources](https://github.com/kakadiadarpan/gatsby-plugin-sass-resources) 🎉

**Comment by jncampbell** [comment]
@kakadiadarpan Both options work perfectly! Thank you for your help and awesome contribution. Cheers!
