### ISSUE TITLE
Global SCSS stylesheet resulting pixrem warning

### ISSUE THREAD

**Issue by bin4ryio** [gatsbyjs/gatsby#717]
Hello, like title. I'm using a SCSS global stylesheet for gatsby. I'm getting the following error:

```
loader!./~/gatsby/~/sass-loader!./sass/main.scss
pixrem: Unit cannot be used for conversion, so 16px is used.
```

It's highly possible that a custom webpack config can fix it but I've no idea where to place it.

Thank you in advance.

**Comment by KyleAMathews** [comment]
Looks like a warning not error from
https://github.com/robwierzbowski/node-pixrem/blob/master/README.md

Possibly could just be ignored. Not sure why it's showing up for you.

**Comment by Bin4ryIO** [comment]
I used a SCSS template from html5up.net, do you know how do I mute the warning?

![2017-03-13_02 47 34_valkyrie_ss](https://cloud.githubusercontent.com/assets/21124691/23834811/7b89df3e-0797-11e7-8568-f80efa5e6a0f.jpg)

**Comment by KyleAMathews** [comment]
No, not at all familiar with this library. I'd research the pixrem lib.

**Comment by nodox** [comment]
A custom webpack config to suppress this error could do the job but you're right, where does someone add the fix? How can we suppress the warnings. All my development is halted until I can find a fix for this. I also was using the HTML5up.nest site.
