### ISSUE TITLE
Searching plugins on V2 site leads to Page Not Found error

### ISSUE THREAD

**Issue by ricopags** [gatsbyjs/gatsby#7171]
## Description

Searching plugins on next.gatsbyjs.org for wordpress leads, eventually, to Page Not Found error

### Steps to reproduce

https://www.useloom.com/share/3ff18de00132409a8b5640ccf4ef20f5

1. Navigate to https://next.gatsbyjs.org/plugins/
2. Click in search field
3. Type anything you'd find in the list
4. Hit enter [or, wait]

### Expected result

Should just load the list

### Actual result

Page not found

### Environment

happens in chrome or firefox, no adblockers.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by shannonbux** [comment]
Resulting URL from typing "word" https://next.gatsbyjs.org/plugins/undefined?=wordpress

**Comment by janosh** [comment]
I believe it's just a typo on [line 408 of plugin-searchbar-body.js](https://github.com/gatsbyjs/gatsby/blob/9cfb7bbd2d30ea7f4a3552ce2b87fa69735a25e4/www/src/components/plugin-searchbar-body.js#L408):

```
reachNavigate(`${this.props.location.~~pathanme~~pathname}?=${value.query}`, {
```
Just created a [pull request](https://github.com/gatsbyjs/gatsby/pull/7193) that fixes this.

**Comment by m-allanson** [comment]
This is fixed, thanks @janosh 👍
