### ISSUE TITLE
[v2] push and replace in development mode not working

### ISSUE THREAD

**Issue by KamiGim** [gatsbyjs/gatsby#7172]
## Description

push and replace url in development mode not working, but in production mode it's working fine

### Steps to reproduce

use push and replace from gatsby

### Expected result

push replace should always work fine

### Actual result

as I describe my problem

### Environment
 System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
  Binaries:
    Yarn: 1.6.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.0.0-beta.84 => 2.0.0-beta.87
    gatsby-image: ^1.0.54 => 1.0.55
    gatsby-plugin-emotion: ^2.0.0-beta.2 => 2.0.0-beta.3
    gatsby-plugin-google-analytics: ^1.0.31 => 1.0.31
    gatsby-plugin-react-helmet: ^3.0.0-beta.3 => 3.0.0-beta.4
    gatsby-plugin-sharp: ^1.6.48 => 1.6.48
    gatsby-source-filesystem: ^1.5.39 => 1.5.39
    gatsby-transformer-sharp: ^1.6.27 => 1.6.27

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by kakadiadarpan** [comment]
@KamiGim can you try upgrading gatsby and dependencies to their latest stable versions? We released version 2 recently, that might solve the issue for you.

(Let us know if it doesn't)
