### ISSUE TITLE
[gatsby-source-wordpress] Inline fragments of nested ACF Flex Contents

### ISSUE THREAD

**Issue by nikosolihin** [gatsbyjs/gatsby#7180]
Having trouble querying a flexible content items nested within another flexible content. 

The parent flexible content field is called `page_builder` and it has layouts with different number of columns (one, two, etc). Within each column is a flexible content subfield called `page_builder_blocks` with block subfields (image, hero, text, etc).

Here's how I'm querying for a two column layout which throws an error. Am I not using inline fragments correctly? Thank you.

```
{
    allWordpressPage {
        edges {
            node {
                acf {
                    page_builder_page {
                        __typename  # <------- This lists all node types
                        ... on WordPressAcf_one_column {
                            page_builder_blocks {
                                __typename  # <------- But not this one

                                # I wish to do the following:
                                ... on WordPressAcf_hero {
                                    title
                                    subtitle
                                }

                            }
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by pieh** [comment]
It looks like You don't access `page_builder_blocks` anywhere? Please try using graphiql editor ( http://localhost:8000/___graphql ) to figure schema shape

**Comment by nikosolihin** [comment]
@pieh Sorry, typo. I've revised the code above with some comments. Questions:
- Why does __typename in the nested flexible content does not list any types?
- Graphiql refers to the nested flexible content field as `page_builder_blocks` and not `page_builder_blocks_page` like the parent. Any reason for this?

**Comment by nikosolihin** [comment]
I ended up using a custom normalizer function to "lift" the nested flex fields up under the `acf` field. I think the current [`createNodesFromEntities`](https://github.com/gatsbyjs/gatsby/blob/0d089e2f0544a802cd20c2c57e71fb3ddd932b9c/packages/gatsby-source-wordpress/src/normalize.js#L536) function in normalize.js is only compatible with non nested flex fields.

**Comment by seamofreality** [comment]
Hey there @nikosolihin, I am currently experiencing the same issue with wanting to access nested flexible layouts. Would you care to share how your normalizer looks, that would be very interesting to see!

**Comment by juice49** [comment]
I recently ran into this issue, and I haven't been able to find a good solution. To properly consume a flexible content field, you need to be able to use inline fragments, and they just don't work if the flexible content field is nested.

I've been trying to figure out the [Gatsby code that handles the creation of these nodes](https://github.com/gatsbyjs/gatsby/blob/0d089e2f0544a802cd20c2c57e71fb3ddd932b9c/packages/gatsby-source-wordpress/src/normalize.js#L536). I am very possibly wrong, but it seems likely this needs to be recursive instead of just running at the top level.
