### ISSUE TITLE
Initial site load in subdirectory instead of root causes other pages to fail

### ISSUE THREAD

**Issue by Devin-Chaves** [gatsbyjs/gatsby#7181]
## Description

Initial load to anything other than the root breaks all links.

### Steps to reproduce

Navigate to: https://www2-staging.wealthsimple.com/en-ca/culture/why/
Click the 'Culture Manual' logo to navigate to home.

### Expected result

Should navigate to the https://www2-staging.wealthsimple.com/en-ca/culture/.

### Actual result

The file fails to load and site redirect takes over.

### Environment

  System:
    OS: macOS High Sierra 10.13.4
    CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 9.5.0 - ~/.nvm/versions/node/v9.5.0/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 6.1.0 - ~/.nvm/versions/node/v9.5.0/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 61.0.1
    Safari: 11.1
  npmGlobalPackages:
    gatsby-cli: 1.1.58

**Comment by kakadiadarpan** [comment]
Hey @Devin-Chaves, when I navigate to https://www2-staging.wealthsimple.com/en-ca/culture/why/ I can see the error as in the screenshot below. The bundles fail to load:

<img width="857" alt="error screenshot" src="https://user-images.githubusercontent.com/10805593/43978216-21fb52aa-9d04-11e8-9fd1-5e5917222ba9.png">

When I open https://www2-staging.wealthsimple.com/en-ca/culture/ I don't see the same problem.

Would it be possible for you to share more details regarding your app?

**Comment by Devin-Chaves** [comment]
Hi @kakadiadarpan thanks for having a look.

The structure looks like this:

```
        <Nav location={location} />
        {this.state.shouldShowLoading && <Loading />}
        <TransitionGroup>
          <CSSTransition
            key={location.pathname}
            classNames="anim"
            timeout={{ enter: 900, exit: 700 }}
            onExit={node => {
              node.style.position = "fixed";
              node.style.top = -1 * window.scrollY + "px";
            }}
          >
            <TransitionHandler location={location}>
              <div>{children()}</div>
            </TransitionHandler>
          </CSSTransition>
        </TransitionGroup>
```

`Nav` and `Loading` are pulled in as basic functional components and not compiled from `pages`

**Comment by kakadiadarpan** [comment]
@Devin-Chaves can you try upgrading gatsby and dependencies to their latest stable versions? We released version 2 recently, that might solve the issue for you.

(Let us know if it doesn't)
