### ISSUE TITLE
[v2] --no-uglify no longer implemented

### ISSUE THREAD

**Issue by danoc** [gatsbyjs/gatsby#7187]
## Description

I've noticed that `gatsby build --noUglify` still uglifies the code in V2. After digging around a little, it seems that `noUglify` is only referenced in `build.js`. Previously, `noUglify` was [referenced in both `babel-config.js` and `webpack.config.js`](https://github.com/gatsbyjs/gatsby/pull/4755/files).

### Steps to reproduce

Run `gatsby build --noUglify` and see that code is still uglified.

### Expected result

Code should not be uglified

### Actual result

Code was uglified

### Environment

```
❯ npx gatsby info --clipboard

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Shell: 5.5.1 - /usr/local/bin/zsh
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 61.0.1
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-beta.83
```
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by KyleAMathews** [comment]
@danoc thanks for reporting this! `--no-uglify` was added to v1 I believe after v2 was well under way and never got merged it seems into v2.

@tryzniak would love a PR!

**Comment by tryzniak** [comment]
Hey folks, can you confirm that a command `gatsby build --no-color` is working for you? Because when I'm running it, I get this:
```
gatsby build

Build a Gatsby project.

Options:
  --verbose                   Turn on verbose output                                                                                                    [boolean] [default: false]
  --no-color                  Turn off the color in output                                                                                              [boolean] [default: false]
  --prefix-paths              Build site with link paths prefixed (set prefix in your config).                                                          [boolean] [default: false]
  --nouglify                  Build site without uglifying JS bundles (for debugging).                                                                  [boolean] [default: false]
  --open-tracing-config-file  Tracer configuration file (open tracing compatible). See https://www.gatsbyjs.org/docs/performance-tracing/                                 [string]
  -h, --help                  Show help                                                                                                                                  [boolean]
  -v, --version               Show version number                                                                                                                        [boolean]

Unknown argument: color
```
Notice the last line:  `Unknown argument: color`. Similar output with `--no-uglify`.

**Comment by KyleAMathews** [comment]
Oh actually the reason is you disable minimization in v4 of webpack differently — see this stackoverflow post https://stackoverflow.com/questions/51263506/webpack-4-disable-uglifyjs-webpack-plugin

Someone want to implement this? It'd be a nice way to get a first PR done.

The setting would go here https://github.com/gatsbyjs/gatsby/blob/a0e64208b6cf0068c1c61eabef134173bb911f44/packages/gatsby/src/utils/webpack.config.js#L424

The `program` variable has what the different flags are.

We _might_ have to disable our `uglify` plugin as well but it might be that webpack handles disabling that for us by setting minimize to false.

**Comment by tryzniak** [comment]
Yeah, I'm on it! Thank you for the nudge in the right direction!

**Comment by danoc** [comment]
Thank you @tryzniak!

**Comment by cyberwombat** [comment]
This doesn't seem to work with either `--no-uglify` or `--noUglify` in Gatsby 2.15.x . I run `gatsby build --no-uglify'` and react still dumps with: `WebpackError: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

Any ideas?

**Comment by stevengrimaldo** [comment]
Noting here not seeing it working running `"gatsby": "^2.32.4",`, year 2022.
