### ISSUE TITLE
"Error: ReferenceError: localStorage is not defined" when running gatsby build

### ISSUE THREAD

**Issue by geohuz** [gatsbyjs/gatsby#719]
I didn't get this error under development mode, but ```gatsby build``` throw out localStorage is not defined

**Comment by KyleAMathews** [comment]
You must have code that expects localstorage. "gatsby build" doesn't run in
a browser environment so browser APIs don't exist. Put localstorage code in
componentDidMount.

**Comment by geohuz** [comment]
I moved the code into getInitialState, I'm still getting the same error under build, but it's ok in development mode:

`  getInitialState() {
    return {appStore: new AppStore(localStorage)}
  },
  componentWillMount() {
    this.state.appStore.loadPolls()
  },
`

**Comment by KyleAMathews** [comment]
You need componentDidMount. getIntialState is called on the server.
