### ISSUE TITLE
Images not showing when running Gatsby on localhost (mobile) 

### ISSUE THREAD

**Issue by danieldelouya** [gatsbyjs/gatsby#7192]
When I try to view my site on mobile via localhost all the content is loaded except images. The images show on web. 
I've tried several browsers on iPhone.

What could be the cause of this?

**Comment by itsmadhusudhan** [comment]
It would be helpful to review if you can share the code

**Comment by danieldelouya** [comment]
Update: I deployed the site to netlify and images show on mobile. Weird

**Comment by danieldelouya** [comment]
The solution to my problem is found here https://github.com/gatsbyjs/gatsby/issues/5264#issuecomment-405424852
