### ISSUE TITLE
Gatsby Build Broke My Site.

### ISSUE THREAD

**Issue by nnagewad** [gatsbyjs/gatsby#7195]
## Description
- As the title illustrates my site broke after running `gatsby build`.
- Was successful when developing, using `gatsby develop`.
- However, when it came time to build, using `gatsby build`, the hamburger button did not work.

### Steps to reproduce
- Built a mobile nav with a hamburger button on the page.
- Plus using custom fonts.
- While using `gatsby develop` whenever the hamburger menu is clicked it will reveal the mobile nav and the custom font is displayed on the page.

### Expected result
- After running `gatsby build` I expect the results to be same as it was on `gatsby develop`.
#### Gatsby Develop:
<img width="594" alt="screen shot 2018-08-09 at 3 38 03 pm" src="https://user-images.githubusercontent.com/8485154/43921620-4ada9dc2-9bea-11e8-9bb1-3ebfaa4b3ba1.png">

### Actual result
- Fonts not loading correctly and mobile nav not working.
#### Gatsby Build:
<img width="592" alt="screen shot 2018-08-09 at 3 37 40 pm" src="https://user-images.githubusercontent.com/8485154/43921659-661c7420-9bea-11e8-96a7-baa9940c1fe9.png">

Also, the React Browser extension noted that site is not using React.

- Returned with error messages:
<img width="1299" alt="screen shot 2018-08-09 at 3 14 31 pm" src="https://user-images.githubusercontent.com/8485154/43921541-0f192fce-9bea-11e8-85bc-e528893eb9ac.png">

### File contents (if changed)

`gatsby-config.js`:
```
module.exports = {
  plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-styled-components',
  ]
};
```
`package.json`: 
```
{
  "name": "cereal-concoction",
  "description": "Cereal Concoction Landing Page",
  "license": "MIT",
  "scripts": {
    "develop": "gatsby develop",
    "build": "gatsby build",
    "serve": "gatsby serve"
  },
  "dependencies": {
    "babel-plugin-styled-components": "^1.5.1",
    "gatsby": "^2.0.0-beta.59",
    "gatsby-image": "^1.0.55",
    "gatsby-plugin-react-helmet": "next",
    "gatsby-plugin-styled-components": "next",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-helmet": "^5.2.0",
    "styled-components": "^3.3.3"
  }
}
```

**Comment by sktt** [comment]
The file:/// paths in the console suggests that you're opening index.html directly. Use `gatsby serve` to start a http server and see if it helps

**Comment by nnagewad** [comment]
@sktt  thank you. I also tested by pushing to Surge and it worked.
