### ISSUE TITLE
Hot Reloading is forcing Provider (redux) to update

### ISSUE THREAD

**Issue by alpgumus** [gatsbyjs/gatsby#7205]
## Description

Hot reloading is causing the Provider to update if Provider is used in wrapRootComponent api.

### Steps to reproduce

Use redux (Provider) in wrapRootComponent api as in using-redux example. Have your Redux connected component (Counter in using-redux) log some text to console (do an increment) in componentDidMount.  (see full code for Counter in the next comment --- every time there is a change and hot reload, the count increases because componentDidMount is called)

### Expected result

componentDidMount methods on Redux connected components should not be called on hot-reload.

### Actual result

componentDidMount methods on Redux connected components are being called.

### More Info and Potential Solution

Hot Module injection should be done on one level below Root before wrapRootComponent so that it will be within Provider. (More info: [you shall not hot reload application initialization code.](https://github.com/gaearon/react-hot-loader/issues/905#issuecomment-375471700)) (Not: Injection should be on one extra level before Root because wrapped Root should not be re-rendered on hot update. `<Root>hotComponentHere</Root>` - hot update will re-render parent Root render but not Provider in wrapRootComponent)

### Environment

System:
OS: macOS Sierra 10.12.6
CPU: x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
Shell: 5.2 - /bin/zsh
Binaries:
Node: 9.7.1 - ~/.nvm/versions/node/v9.7.1/bin/node
Yarn: 1.5.1 - /usr/local/bin/yarn
npm: 6.0.0 - ~/.nvm/versions/node/v9.7.1/bin/npm
Browsers:
Chrome: 67.0.3396.99
Firefox: 57.0.4
Safari: 11.0.1
npmPackages:
gatsby: 2.0.0-beta.93 => 2.0.0-beta.93
gatsby-cli: 2.0.0-beta.5 => 2.0.0-beta.5
gatsby-plugin-react-helmet: next => 3.0.0-beta.3
npmGlobalPackages:
gatsby-cli: 1.1.44

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by alpgumus** [comment]
To reproduce: update the Counter in using-redux example as below. Every time there is a change and hot reload occurs, the count increases on hot reload because componentDidMount is called. (because Provider is re-rendered)

```js
class Counter extends React.Component {
  componentDidMount() {
    console.log('componentDidMount')
    this.props.increment() 
  }
  render() {
    const { count, increment } = this.props
    return (
      <div>
        <p>Count: {count}</p>
        <button onClick={increment}>Increment</button>
      </div>
    )
  }
}
```

**Comment by kakadiadarpan** [comment]
@alpgumus can you try upgrading gatsby and dependencies to their latest stable versions? We released version 2 recently, that might solve the issue for you.

(Let us know if it doesn't)
