### ISSUE TITLE
Add option to gatsby-link for matching active when on child routes

### ISSUE THREAD

**Issue by seaneking** [gatsbyjs/gatsby#7208]
## Summary

Would be great to mirror reach router's `isCurrent` and `isPartiallyCurrent` options to `gatsby-link`s `activeStyle` and `activeClassname` props. Basically I'd want to be able to designate a Link as active when any child routes are also active, without having to bypass gatbsy-link and use `isPartiallyCurrent` directly. 

### Basic example

Hesitant to suggest just tacking on another prop as lazy DX, but that would probably make the most sense. Something like this:

```js
<Link ... activeStyle={{...}} greedyActive={true} />
```

Would default to false, so non-breaking change that doesn't really add much cognitive overhead for people.

### Motivation

Common use-case is top-level nav for any nested content (eg: a blog), where you'd often want to designate the nav item active (eg: 'Blog') when on a child path (eg: `/blog/some-post`).

If this isn't added, would at least be worth documenting how to achieve by accessing react router APIs directly in gatsby-link docs, as I imagine it's a common pattern.

**Comment by pojntfx** [comment]
:+1:  as well. Until then, the following polyfill might help someone:

```js
const isPartiallyActive = ({ isPartiallyCurrent }) =>
  isPartiallyCurrent ? { className: "item active" } : null;
```

```jsx
<div 
  class="item"
  activeClassName={link === "/" ? "active" : undefined}
  getProps={link === "/" ? undefined : isPartiallyActive}
/>
```

This checks whether the link links to the root level (and thus should not be have the `active` class applied on child routes, but only if it is actually the current page) and if it is not, it sets `className` to `item active`.

More info is in the [reach router docs](https://reach.tech/router/api/Link). See [https://gitlab.com/libresat/libresat/tree/master/packages/site](https://gitlab.com/libresat/libresat/tree/master/packages/site) for an example (blog posts).

**Comment by seaneking** [comment]
@KyleAMathews would you accept a PR for this feature?

**Comment by janosh** [comment]
`greedyActive` should definitely be the default. In the vast majority of cases, you want child routes to "activate" their parents. I'm surprised this isn't implemented already.

**Comment by KyleAMathews** [comment]
@ryanflorence any thoughts here?

**Comment by LpmRaven** [comment]
Would be great to get an example of how to implement this with Reach Router if it isn't set as default behavior.

**Comment by janosh** [comment]
@KyleAMathews If @seaneking is willing to provide a PR for this feature, I think that's great. Couldn't `gatsby-link` implement this feature irrespective of Reach Router?

If you're worried about changing the default behavior for everyone, maybe we could add a global option to `gatsby-config`? Something like
```js
module.exports = {
  siteMetadata: {
    ...
  },
  plugins: [
    ...
  ],
  settings: {
    gatsby-link: {
      greedyActive: true,
    }
  }
}
```

**Comment by wllkle** [comment]
> 👍 as well. Until then, the following polyfill might help someone:
> 
> ```js
> const isPartiallyActive = ({ isPartiallyCurrent }) =>
>   isPartiallyCurrent ? { className: "item active" } : null;
> ```
> 
> ```js-jsx
> <div 
>   class="item"
>   activeClassName={link === "/" ? "active" : undefined}
>   getProps={link === "/" ? undefined : isPartiallyActive}
> />
> ```
> 
> This checks whether the link links to the root level (and thus should not be have the `active` class applied on child routes, but only if it is actually the current page) and if it is not, it sets `className` to `item active`.
> 
> More info is in the [reach router docs](https://reach.tech/router/api/Link). See https://gitlab.com/libresat/libresat/tree/master/packages/site for an example (blog posts).

Hi there, if at all possible would you have an example using this? I'm having problems implementing this functionality. Thanks!

**Comment by janosh** [comment]
@wllkle This is how I am using it.
```jsx
import React from 'react'
import { Link } from 'gatsby'

const partlyActive = className => ({ isPartiallyCurrent }) => ({
  className: className + (isPartiallyCurrent ? ` active` : ``),
})

const PartlyActiveLink = ({ className, ...rest }) => (
  <Link getProps={partlyActive(className)} {...rest} />
)
```
In my case, the actual styles are then coming from a `styled-component`.
```js
import styled from 'styled-components'

const NavLink = styled(PartlyActiveLink)`
  color: ${props => props.theme.lightBlue};
  transition: ${props => props.theme.shortTrans};
  cursor: pointer;
  &.active {
    color: ${props => props.theme.darkYellow};
  }
  :hover {
    color: ${props => props.theme.lightGreen};
  }
`
```

**Comment by seaneking** [comment]
Think we should keep this open, until it's clarified either way whether from the team whether this should feature be included in gatsby-link or not (I vote yes, FWIW). 

Tbh I think this should be the default behaviour, with an opt-out flag instead. But that would be a breaking change so fair enough if it's added as an opt-in feature instead.

**Comment by arcanis** [comment]
I've opened a PR, in case someone actually implementing it was all that was needed 😛  (#12495)
