### ISSUE TITLE
[v2][Gatsby Link] Error when hot reloading: React-hot-loader reconciliation failed

### ISSUE THREAD

**Issue by ryanditjia** [gatsbyjs/gatsby#7209]
[Minimal reproduction repo](https://github.com/ryanditjia/reproduction-gatsby-link-hot-reload-error.git)

Steps to reproduce:
1. Clone the repo and run development server
2. Edit anything in `src/pages/index.js` to trigger hot reload

```
React-hot-loader: reconciliation failed – "could not dive into [" – "Go back home" – "] while some elements are still present in the tree."
```
Where "Go back home" is the children prop of `Link`

**Comment by KyleAMathews** [comment]
Is this an error or something we can fix?

**Comment by KyleAMathews** [comment]
I'm not 100% sure what it means.

**Comment by ryanditjia** [comment]
My bad for poor explanation. They’re errors that browser throws every time hot reloading occurs.

**Comment by KyleAMathews** [comment]
Yes but what do they mean? Are they something we can fix?

**Comment by ryanditjia** [comment]
I’m not sure. This issue in `react-hot-loader`’s repo seems related: https://github.com/gaearon/react-hot-loader/issues/1034

**Comment by KyleAMathews** [comment]
Hmm ok, so we can hide them at least. It'd be nice to know if they're indicating a problem or not in our implementation.

**Comment by LeKoArts** [comment]
This error is also flooding my console :(

**Comment by ryanditjia** [comment]
Looks like errors no longer show. Closing.

**Comment by mrdbeck** [comment]
Errors still showing for me

**Comment by ryanditjia** [comment]
Have you upgraded Gatsby and its packages to rc.0?

**Comment by cezarneaga** [comment]
add this to your layout.js file:
```
import {setConfig} from 'react-hot-loader';
setConfig({logLevel: 'no-errors-please'});
```

at least for now it should close the issue. stems from `react-hot-loader`

**Comment by mrdbeck** [comment]
Cheers @cezarneaga 

Can confirm the fix removes the errors

**Comment by ryanditjia** [comment]
I’m not seeing this anymore (even without the fix). Closing issue in 24 hours, please stop me if anyone is still getting it.
