### ISSUE TITLE
[v2][plugin-google-analytics] Error with missing gatsby-browser.js

### ISSUE THREAD

**Issue by azdanov** [gatsbyjs/gatsby#7216]
When building a project with `gatsby-plugin-google-analytics` and with missing `gatsby-browser.js` the plugin throws an error `Error: Cannot find module`.

To reproduce:

1. `gatsby new gatsby-site https://github.com/gatsbyjs/gatsby-starter-default#v2`
2. Remove `gatsby-browser.js` from project root.
3. `yarn add gatsby-plugin-google-analytics@next`
4. add to `gatsby-config.js`: `"gatsby-plugin-google-analytics"`
5. `yarn build`

**Comment by Chuloo** [comment]
Couldn't reproduce your error. Try including a `trackingId`, say 
```
{
      resolve: `gatsby-plugin-google-analytics`,
      options: {
        trackingId: `UA-91652198-1`,
      },
    },
```
## System Info
```
System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.7.0 - /usr/local/bin/node
    Yarn: 1.9.2 - /usr/local/bin/yarn
    npm: 6.2.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-beta.111
    gatsby-plugin-google-analytics: ^2.0.0-beta.5 => 2.0.0-beta.5
    gatsby-plugin-manifest: next => 2.0.2-beta.6
    gatsby-plugin-offline: next => 2.0.0-beta.9
    gatsby-plugin-react-helmet: next => 3.0.0-beta.4
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```

**Comment by azdanov** [comment]
@Chuloo I can't reproduce also. Although before I could.

Probably a new beta version of Gatsby resolved this.
