### ISSUE TITLE
Request: First-Class Storybook Integration

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#7219]
## Summary

It is currently pretty painful to integrate Storybook with Gatsby. I know there is some discussion [here](https://github.com/Mathspy/gatsby-storybook-jest-starter) and there is a great starter [here](https://github.com/Mathspy/gatsby-storybook-jest-starter), but imho, storybook should be something that works out the box (or as close to it as possible). This could be in the form of an official plugin, but I personally think this should be fully integrated so users are provided out-of-the-box with:

- Site
- Testing
- Styleguide

**Comment by seaneking** [comment]
👍 This would be great, but I think it should be provided as an official plugin rather than baked in. It's a rather opinionated feature, when there are other component library helpers out there that people might prefer to use.

**Comment by LekoArts** [comment]
There's a guide for Storybook now: https://www.gatsbyjs.org/docs/visual-testing-with-storybook/

**Comment by seaneking** [comment]
Would be great to keep this open — the Gatsby Babel preset helped, but there's still a fair few hacky workarounds needed to get Storybook working, would be great to see if we can get tighter integration out of the box
