### ISSUE TITLE
[PDX Meetup] Find A/V company to record talks

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#7234]
Goals:

- Good quality video that will be posted on Gatsby‘s YouTube channel
- Ideally, we livestream the talks

**Comment by lindaleebumblebee** [comment]
I don't know any A/V companies in Portland so I'm just doing google searches to figure it out. :) Here's one that I reached out to: http://www.thinkav.com/ They might be a bit expensive so I'll look at other options as well and will post updates here.

**Comment by lindaleebumblebee** [comment]
Here's one more A/V service...they're working on a quote for us now. https://www.meyerproinc.com/

**Comment by lindaleebumblebee** [comment]
Here's the quote from MeyerPro- total cost for live streaming and recording is just under $5K. @jlengstorf How many views do you anticipate we'd get from this (what have you seen in the past)? Or how many followers does Portland JAMstack have? (I didn't see a youtube channel for them). 
[Meyer Quote-181157.pdf](https://github.com/gatsbyjs/gatsby/files/2287802/Meyer.Quote-181157.pdf)

**Comment by jlengstorf** [comment]
This is a little higher than I think we can justify. I'm thinking we can probably get away with something a bit more lo-fi, honestly. I might even just set up a Zoom meeting and record that. 🤷‍♂️

**Comment by KyleAMathews** [comment]
Yeah, it doesn't have to be fancy. Share the screen and broadcast with the
little video.

**Comment by jlengstorf** [comment]
Yeah. I could also set up my phone on Zoom to do a speaker video and share screen from the speaker's laptop. I'm hoping we can find someone with actual gear, but if all else fails I can make that work.

**Comment by jlengstorf** [comment]
Okta handled this!
