### ISSUE TITLE
[PDX Meetup] Decide what the talk schedule will be

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#7235]
## Confirmed Talks

- [x] Gatsby V2 Deep Dive by @KyleAMathews 

## Talks to Consider

- [x] How Gatsby is working to make open source more open
	- @marisamorby to talk research, design, and process development
	- @jlengstorf to talk social media outreach, technical details, potentially a code walkthrough
- [x] Data in Gatsby V2 (differences between V1 and V2, e.g. `StaticQuery`, no more layout queries, schema stitching)
	- Who would give this talk? @m-allanson? @kkemple? Any volunteers?
	- Thanks for the suggestion, @amberleyromo!
- [x] Gatsby + Tailwind w/@kylegalbraith
	- Based on [this blog post](https://blog.kylegalbraith.com/2018/08/07/how-to-make-an-awesome-blog-using-gatsbyjs-and-aws/)
	- This is based on V1 — would it be possible to update to V2 so it's using the latest?

## Format

We have ~2 hours for talks, and we want to leave time for socializing and meeting other folks from the Gatsby community in real life.

For a schedule, I was thinking something like this:

- 6:30–7:00pm — arrive, grab snacks and drinks, socialize
- 7:00–7:45pm — deep dive on V2 w/Kyle
- 7:45–8:00pm — Lightning talk 1
- 8:00–8:15pm — Lightning talk 2
- 8:15–8:30pm — Lightning talk 3
- 8:30–9:00pm — socialize, finish the snacks and drinks, head home (or to the next place)

I'm open to alternative schedules as well. This seemed like a good way to cover a broader set of topics in a short time, but we could also use the time to go really deep on 2 or 3 topics instead.

Anyone have opinions or preferences here?

**Comment by kylegalbraith** [comment]
@jlengstorf I can certainly look into updating this post to be on V2 instead of V1. Is this date finalized? I can start prepping my talk if that is the case. Let me know.

**Comment by marisamorby** [comment]
@jlengstorf I'm happy to talk about research, design, and process. I think a 15 minute lightning talk on that would be fun!

**Comment by jlengstorf** [comment]
Okay — @kylegalbraith can you write up a 2–3 sentence abstract for your talk? You could also give it about converting your V1 site to V2, which might actually be a great resource for people.

With that, let me propose a schedule for approval:

1. @KyleAMathews — **Gatsby V2 deep dive** (35 minutes)
2. @marisamorby — **How Gatsby is working to make open source more open** (15 minutes)
3. @thebigredgeek — **Data in Gatsby V2: schema stitching, StatiQuery, and more** (15 minutes)
4. @kylegalbraith — **Migrating a Gatsby V1 site to V2** _or_ **Building a blog with Gatsby V2** (15 minutes)

@gatsbyjs/maintainers does anyone have suggestions for content that would benefit you and/or the community that we're _not_ covering here? We intend to record these talks and make them available on our YouTube channel, so even if you're not in Portland this is relevant to you. 😄 

Thanks so much!

**Comment by janosh** [comment]
@jlengstorf As @calcsam mentioned in #6917, it would be great to have better documentation on how to place custom components inline with your markdown text. Perhaps someone who would feel comfortable improving the docs in that area could instead distill his/her knowledge into a 15 minute talk. A link to that talk from the pertaining doc articles would go a long way towards closing #6917, I think.

**Comment by kylegalbraith** [comment]
@jlengstorf I just upgraded my blog to V2 and plan on updating the starter project to V2 as well. I think the docs do a great job of covering the migration as it took me all of about 15 minutes. So for my talk, I will stick to the blog post as an outline, here is an abstract:

_"Learn how to build a blog in style using GatsbyJs and TailwindCSS in less than 15 minutes. We will explore how we can leverage Gatsby, Tailwind, and AWS to create and continuously deploy a blog in the time it takes for a pizza to get delivered."_

Open to suggestions as well.

**Comment by dougouverson** [comment]
Suggested small tweak:

> Learn how to build a stylish blog using GatsbyJs and TailwindCSS - in less than 15 minutes! We will explore how to leverage Gatsby, Tailwind, and AWS to create and continuously deploy a blog in the time it takes for a pizza to get delivered.

Or economize:

> Learn how to leverage Gatsby, Tailwind, and AWS to create (and deploy) a stylish blog - in the time it takes for a pizza to get delivered.

**Comment by jlengstorf** [comment]
@janosh That's a great idea!

I'm not sure that we're _quite_ ready to close that, but I know @ChristopherBiscardi is working on `gatsby-mdx`, which will make custom components in Markdown _much_ easier. We'll be making a lot of noise about that as soon as it's ready.

@kylegalbraith I think this sounds great! And thanks for the edits, @dougouverson — I like the super short version (since we're listing all of these in a single Meetup description).

@marisamorby, I'm taking your thumbs-up as agreement that you'll give a 15-minute talk. 😄 

@thebigredgeek, are you cool with this topic? It's not quite what we talked about, but I think it's super important to cover the awesome work @freiksenet has done on GraphQL schema stitching. Let me know ASAP if this works/doesn't work for you.

**Comment by thebigredgeek** [comment]
Hey this works for me!  Looking forward to it

**Comment by jlengstorf** [comment]
Pulling @lindaleebumblebee's description here so it's easier to discuss in-context.

> Title: Gatsby is my JAMstack (PDX Edition)
> Co-hosted with Portland JAMstack
> 
> August 23, 2018
> 6:30pm
> Alchemy Code Lab
> 30 NW 10th Avenue
> Portland, OR 97227
> 
> Join JAMstack Portland as the Gatsby team takes over to share what’s coming in Gatsby V2.
> 
> On Thursday, August 23rd (6:30pm) at Alchemy Code Lab, take a deep dive into what’s coming up in Gatsby V2. Learn how Gatsby leverages React and GraphQL as part of its JAMstack approach to building blazing fast websites.
> 
> Talks for the night:
> - **Gatsby V2 Deep Dive** with Kyle Mathews, creator of Gatsby
> 	Learn what’s new in V2, including additional build optimizations, better error messaging, hotter hot reloading with Gatsby’s Ludicrous Mode, and PostCSS configuration updates.
> - **How We’re Working to Make Open Source More Open** with Marisa Morby
> 	From free swag to open pair programming hours, Gatsby is working hard to make sure the open source community is as welcoming as possible. Learn how we’ve designed our processes, what we’ve learned, and what we’re planning next in this session.
> -	**Build a Gatsby V2 Site with AWS and Tailwind CSS** with Kyle Galbraith
> 	Learn how to leverage Gatsby, Tailwind, and AWS to create (and deploy) a stylish blog - in the time it takes for a pizza to get delivered.
> - **Data in Gatsby V2: GraphQL Schema Stitching, StaticQuery, and More** with Andrew Rhyne
> 	In this session, learn all about the new ways you can access data in Gatsby V2, from the flexibility of the new StaticQuery component to improved integration with existing GraphQL APIs.
> 
> Space is limited so register early to reserve your spot! 

@KyleAMathews @marisamorby @kylegalbraith @thebigredgeek @notcoling can you please take a look at this and sign off so we can get it posted!

**Comment by marisamorby** [comment]
A few questions:
The meetup runs from 6:30 - ??

Are we providing any drinks or snacks?

Do we have a code of conduct that we can point to, and/or inclusivity verbiage so that we make sure all people feel welcome?

**Comment by jlengstorf** [comment]
@marisamorby Good call. Updated to include an end time, call out for food/drinks, and a link to our code of conduct.

Does your abstract look good?

**Comment by marisamorby** [comment]
@jlengstorf The abstract looks good to me, yes!

**Comment by jlengstorf** [comment]
I'm calling this lineup finalized. @KyleAMathews holler if we need to update your talk's abstract.
