### ISSUE TITLE
[PDX Meetup] Get food and drinks for the event

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#7236]
Initial thoughts:

- Soda
- Water (e.g. LaCroix)
- Beer?
- Pizza (maybe Sizzle Pie?)
	- cheese
	- pepperoni
	- vegan

Should we do something other than pizza? @shannonbux, I know you don't really eat pizza; have you seen great food at an event that you were able to eat?

**Comment by shannonbux** [comment]
Thanks for thinking of me, @jlengtsorf! hm...can't remember anything other
than getting actual catering, like Indian, Greek, or Middle Eastern food
like kebabs, or salads. Maybe if the pizza could come with salads that's an
easy middle ground? Other easy things are fruit and veggie platters. Kind
of pricey sometimes though.

**Comment by kkemple** [comment]
Cloudflare will reimburse us for pizza if we do a 30 second shoutout :smile:

https://blog.cloudflare.com/cloudflare-wants-to-buy-your-meetup-group-pizza/

**Comment by jlengstorf** [comment]
I have no problem shouting out Cloudflare. I love that service. 😍

**Comment by jlengstorf** [comment]
Okta sponsored beverages and CloudFlare sponsored pizza. 🍺 🍕
