### ISSUE TITLE
[PDX Meetup] Post details on Meetup.com

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#7237]
- [x] Write a title/description
- [x] Finalize time (18:30 Pacific)
- [x] This will be posted on [JAMstack Portland](https://www.meetup.com/JAMstack-Portland/)’s Meetup account
	- Colin is our contact, so we'll need to get the description to him for posting
	- I have a call with him today to discuss details; will follow up on this issue with specifics

**Comment by notcoling** [comment]
@jlengstorf Hey Jason and Linda, I'm ready to post when you all have a description ready. Thanks again for getting all the logistics going and organized here.

Based on talking with Jason, we'll call the event something like 'JAMstack Portland #2: Gatsby is my JAMstack'.

**Comment by lindaleebumblebee** [comment]
Here's the google doc with description: https://docs.google.com/document/d/1tmLXYZNQqJR-VmwIlrAR9DaIjhknJxL5FRq4g6uLMlE/edit

**Comment by lindaleebumblebee** [comment]
@notcoling Let me know once it's posted and I'll get it promoted on our twitter account. thanks all!

**Comment by jlengstorf** [comment]
@lindaleebumblebee @notcoling I made a few edits just now to include the talk details. They're currently suggestions in the doc, and I added a full version at https://github.com/gatsbyjs/gatsby/issues/7235#issuecomment-412677448 for approval by the speakers.

Please let me know if you need anything else!

Thanks!

**Comment by notcoling** [comment]
Hey Jason,

I've got the event posted on Meetup. Let me know if there are any changes we should make.

- I did not set an attendee limit yet, is there a maximum attendee number for the venue?
- Let me know if you had any images you wanted to include (I just threw up a very simple generic one)

Thanks,
Colin

**Comment by jlengstorf** [comment]
@fk any ideas for an image here?

@notcoling good question about attendee limits. Let me check with Alchemy and I'll get back to you.

**Comment by fk** [comment]
Hmmmm…I saw two very talented people doing this [recently](https://twitter.com/gatsbyjs/status/1027608161526546433):

![](https://pbs.twimg.com/media/DkLL4sMVAAAf3-u.jpg)

Seems perfect given the title @notcoling mentioned. 🤷‍♂️ 😃

**Comment by notcoling** [comment]
@fk I love it 😂 if no objections I've added that to the Meetup page.

**Comment by jlengstorf** [comment]
Closing. Thanks so much, @notcoling and @lindaleebumblebee!
