### ISSUE TITLE
prefixLink should handle null and undefined values

### ISSUE THREAD

**Issue by dardub** [gatsbyjs/gatsby#724]
When pulling in data from an external source, some links I have will have an empty url value.

But when passing a null or undefined value you will get an error due to this line:

https://github.com/gatsbyjs/gatsby/blob/master/lib/isomorphic/gatsby-helpers.js#L10

Is this something prefixLink should handle or should it always receive a valid value?

**Comment by KyleAMathews** [comment]
Handling null and undefined sounds totally reasonable to me! Feel free to
make a PR!
