### ISSUE TITLE
Split JSON tree into children and parent nodes

### ISSUE THREAD

**Issue by jeremylynch** [gatsbyjs/gatsby#7250]
Lets say I have JSON data with a `User` that has many `Posts`. 

```js
{
  "id": 1,
  "name": "Bill",
  "posts": [
    {"id": 1, title="My First Blog Post"},
    {"id": 2, title="My Second Blog Post"},
  ]
}
```

From this JSON tree how can I create seperate Graphql nodes for `User` and `Post`?

**Comment by brotzky** [comment]
You could try using GraphQL Aliases: https://graphql.org/learn/queries/#aliases

Pseudo code:
```graphql
{
  user: User(name: $name}) {
    id
    name
  }
  posts: User(name: $name) {
    posts {
        id
        title
    }
  }
}
```

You could also query it the way it is in GraphQL

```graphql
{
    id
    name
    posts {
        id
        title
    }
}
```
and then split it out with JavaScript

```javascript
render() {
    const { posts } = this.props.data
    ...
```

**Comment by jeremylynch** [comment]
Thanks @brotzky. But I literally want to split the nodes into child and parent. My motivation is to be able to use [createRemoteFileNode](https://www.gatsbyjs.org/packages/gatsby-source-filesystem/) on the child. 

I guess the only way to do it would be to split up the JSON with javascript? Eg. 

```js
Object.values(document).filter(value => {
    return Array.isArray(value)
}).map(child => {
    // process child node creation here
})
```

**Comment by brotzky** [comment]
@jeremylynch I think that way is easiest to implement. I would go with that.
