### ISSUE TITLE
[v2][gatsby-plugin-offline] hard refresh on new build / deploy

### ISSUE THREAD

**Issue by azdanov** [gatsbyjs/gatsby#7254]
Can't figure out if it's a bug to normal behavior due to misconfiguration.

On each new `build -> deploy` with gatsby `sw.js` gets replaced when changing pages inside my app, which causes a hard refresh for the browser.

Does service worker update quietly on each rebuild or this is normal?

**Comment by azdanov** [comment]
This is intentional behavior. More info https://github.com/gatsbyjs/gatsby/pull/7355#issuecomment-413780401 and https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/navigation.js#L58.

I wonder if it's possible to update service-worker smoothly, without a hard reset.

**Comment by KyleAMathews** [comment]
This is intentional. Is it causing trouble or just unexpected?

**Comment by azdanov** [comment]
@KyleAMathews I was having issues prior to https://github.com/gatsbyjs/gatsby/commit/0e2405b31d0c24749d49234730c70edaf574f98b. Now it's working fine.
