### ISSUE TITLE
[perilbot] Auto-close stale questions that have been answered

### ISSUE THREAD

**Issue by calcsam** [gatsbyjs/gatsby#7258]
We could add a `provisional answer provided` tag reflecting that a maintainer provided someone asking a question, what they feel is a reasonable response to that question.

If we see an issue tagged `Type: question or discussion`, that is then tagged with `provisional answer provided` tag, we can close after a reasonably short timeframe, eg 7 days. 

If we want more safety, we could add another condition: only close the issue if the last comment is by a maintainer and _not_ the original user who opened the issue. We will need to remove this tag if for any reason the original issue opener does not feel like the response answered their question.

**Comment by jlengstorf** [comment]
@marisamorby This works into a flow we haven't talked about yet, which is the lifecycle of [`type: question or discussion` issues](https://github.com/gatsbyjs/gatsby/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+question+or+discussion%22). This would impact @kakadiadarpan and other maintainers.

**Comment by marisamorby** [comment]
Let's include this discussion in our meeting this week and discuss how the bot is going to impact that lifecycle before we move forward on this.

**Comment by jlengstorf** [comment]
Will happen automatically once #6785 is implemented.
