### ISSUE TITLE
  WebpackError: TypeError: Cannot read property 'history' of undefined

### ISSUE THREAD

**Issue by gfunk1230** [gatsbyjs/gatsby#7269]
When running gatsby build I get the following errors on the terminal.

  WebpackError: TypeError: Cannot read property 'history' of undefined

![image](https://user-images.githubusercontent.com/6556242/44011771-6a44d510-9e88-11e8-9fed-af5a3f7fdefe.png)

**Comment by gfunk1230** [comment]
@KyleAMathews

**Comment by LeKoArts** [comment]
Please use the issue template provided to you an fill it out (your versions, files etc). Otherwise this is just guessing

**Comment by gfunk1230** [comment]
@LeKoArts please see below.

## Description
When running gatsby build I see:
WebpackError: TypeError: Cannot read property 'history' of undefined

### Steps to reproduce
Run gatsby build. 

### Expected result
Build should succeed. 

### Actual result
Build fails. 

### Environment
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.4.0 - ~/.nvm/versions/node/v8.4.0/bin/node
    Yarn: 1.9.2 - /usr/local/bin/yarn
    npm: 6.3.0 - ~/.nvm/versions/node/v8.4.0/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 60.0.1
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-beta.98 
    gatsby-link: ^1.6.46 => 1.6.46 
    gatsby-plugin-react-helmet: next => 3.0.0-beta.4 
    gatsby-plugin-styled-components: ^2.0.11 => 2.0.11 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

**Comment by Chuloo** [comment]
@gfunk1230 couldn't reproduce your error from the steps you stated. Can you create a minimal reproduction repo showing your error?

**Comment by gfunk1230** [comment]
@Chuloo i found the issue. Had to do with he following someone else had posted. So basically dont add anything other then pages jsx files. I had less files and images in there. My bad :( 

I had added a file within the /src/pages folder which was not a page to be built. In my case it was a styled components file containing styles for my index.js page.
