### ISSUE TITLE
[V2] Bug with setFieldsOnGraphQLNodeType and sort fields - MarkdownRemark

### ISSUE THREAD

**Issue by zyhou** [gatsbyjs/gatsby#7274]
## Description

I'm adding field on my graphql query with `setFieldsOnGraphQLNodeType`. It's work well.
When I want to use this field on sort field in allMarkdownRemark query, the query does not take into account my field.

### Steps to reproduce

- [git clone git@github.com:zyhou/gatsby-sort-field-date.git](https://github.com/zyhou/gatsby-sort-field-date)
- npm i
- npm run develop
- Go to graphiQL ([http://localhost:8000/___graphql](http://localhost:8000/___graphql))
- Copy this query
```js
 {
            allMarkdownRemark(sort: { fields: [date], order: DESC }, limit: 1000) {
              edges {
                node {
                  date
                  fields {
                    slug
                  }
                  frontmatter {
                    title
                    date
                  }
                }
              }
            }
          }
```

### Expected result

Posts should be sort by `date`. You can change the order props and the result doesn't change

### Actual result

Posts aren't sort by `date`

### Environment

```
System:
    OS: Linux 4.15 Linux Mint 18.3 (Sylvia)
    CPU: x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Shell: 5.1.1 - /usr/bin/zsh
  Binaries:
    Node: 8.11.3 - /usr/bin/node
    Yarn: 1.9.4 - /usr/bin/yarn
    npm: 6.3.0 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 61.0.1
  npmPackages:
    gatsby: next => 2.0.0-beta.98 
    gatsby-plugin-feed: next => 2.0.0-beta.4 
    gatsby-plugin-google-analytics: next => 2.0.0-beta.5 
    gatsby-plugin-manifest: next => 2.0.2-beta.5 
    gatsby-plugin-offline: next => 2.0.0-beta.9 
    gatsby-plugin-react-helmet: next => 3.0.0-beta.4 
    gatsby-plugin-sharp: next => 2.0.0-beta.7 
    gatsby-plugin-typography: next => 2.2.0-beta.3 
    gatsby-remark-copy-linked-files: next => 2.0.0-beta.3 
    gatsby-remark-images: next => 2.0.1-beta.10 
    gatsby-remark-prismjs: next => 3.0.0-beta.5 
    gatsby-remark-responsive-iframe: next => 2.0.0-beta.3 
    gatsby-remark-smartypants: next => 2.0.0-beta.3 
    gatsby-source-filesystem: next => 2.0.1-beta.10 
    gatsby-transformer-remark: next => 2.1.1-beta.6 
    gatsby-transformer-sharp: next => 2.1.1-beta.6 
```

### File contents (if changed)

This repo [https://github.com/zyhou/gatsby-sort-field-date](https://github.com/zyhou/gatsby-sort-field-date) reproduce the problem, it's comes from `gatsby new my-blog https://github.com/gatsbyjs/gatsby-starter-blog#v2`

I just change :

- gatsby-node.js, add `setFieldsOnGraphQLNodeType` function
- rename markdown post

**Comment by Chuloo** [comment]
Change the query to this
```
{
            allMarkdownRemark(sort: { fields: [frontmatter___date], order: DESC }, limit: 1000) {
              edges {
                node {
                  date
                  fields {
                    slug
                  }
                  frontmatter {
                    title
                    date
                  }
                }
              }
            }
          }
```
This sorts using the date in the frontmatter.
You can see sort in play in the tutorial here: https://www.gatsbyjs.org/tutorial/part-seven/#creating-pages.

**Comment by zyhou** [comment]
Yes I saw this. I don't want to use `frontmatter___date` but the field `date` (edges.node.date).

The `date` field is create in [setFieldsOnGraphQLNodeType](https://github.com/zyhou/gatsby-sort-field-date/blob/master/gatsby-node.js#L91) function
