### ISSUE TITLE
React App as root with gatsby blog. pathPrefix not working.

### ISSUE THREAD

**Issue by sabbakeynejad** [gatsbyjs/gatsby#7279]
I have a react app and two gatsby blogs that I want to love off it. 

Like this

- React app 
- React app -  gatsby Blog 1
- React app -  gatsby Blog 2

This structure works with a static page as the root but when I have a react app as my root the prefix paths stop not working. Would really appreciate some input on this if anyone has had this problem before.

Thanks
Sabba

**Comment by sktt** [comment]
Hey, there were some problems with pathPrefix not being added to Links that was resolved last week. Are you on the latest version? You can use `gatsby info` in your project folder to find this information in a reliable way

**Comment by sabbakeynejad** [comment]
Hi @sktt Thanks, I will try `npm i` and see if it fixes the problem. I look like I am on an old build of gatsby

Don't I need to configure my react app to allow the URLs to point to a gatsby blog and not redirect me to the root?

**Comment by sktt** [comment]
React in itself is, as you know, only about rendering the view. URLs, path prefixes are not directly related to React, merely the Router if anything. To configure a path prefix depends on how your web app is set up. If it's gatsby: https://next.gatsbyjs.org/docs/path-prefix/ or https://www.gatsbyjs.org/docs/path-prefix/ for the stable version. This will automatically add the prefix to your Link elements among other things. To link somewhere else, for example from one gatsby blog to another, a normal `<a />` tag should probably be used. 

Your client side router is working in the context of your current react application and will only direct you within that context.

I hope I understood your question.

**Comment by kakadiadarpan** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub issues, we have to clean some of the old issues as many of them have already been resolved with the latest updates.

Please make sure to update to the latest Gatsby version and check if that solves the issue. Let us know if that works for you by adding a comment 👍

**Comment by kakadiadarpan** [comment]
This issue is being closed because there hasn't been any activity for at least 30 days. Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem 👍
