### ISSUE TITLE
Is it possible to integrate AND & OR in GraphQL query? 

### ISSUE THREAD

**Issue by GuidovdRiet** [gatsbyjs/gatsby#7282]
Is it possible to integrate a OR/AND in a GraphQL query, like the example below?

`{
  allWordpressPage(filter: {
    AND: [{
      lang: {eq: "nl"}
    }, {
      slug: {eq: "companies"}
    }]
  }) {
    edges {
      node {
        slug
        title
        lang
        translations {
          en
          nl
        }
      }
    }
  }
}
`

More info about this example can be found [here](https://www.graph.cool/docs/reference/graphql-api/query-api-nia9nushae).

Or is it possible to add additional filters another way?

Thanks in advance!

**Comment by LekoArts** [comment]
You can do an `AND` with a comma, e.g. see [this example](https://gatsbygraphql.sloppy.zone/?query=%7B%0A%20%20allMarkdownRemark(filter%3A%20%7Bfrontmatter%3A%20%7Btitle%3A%20%7Bne%3A%20%22%22%7D%2C%20date%3A%20%7Beq%3A%20%222017-06-15%22%7D%7D%7D)%20%7B%0A%20%20%20%20totalCount%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20frontmatter%20%7B%0A%20%20%20%20%20%20%20%20%20%20title%0A%20%20%20%20%20%20%20%20%20%20date%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)
