### ISSUE TITLE
init-starter should cloned faster

### ISSUE THREAD

**Issue by ahonn** [gatsbyjs/gatsby#729]
when clone some big starter source(e.g.  [gatsby-starter-bootstrap](https://github.com/jaxx2104/gatsby-starter-bootstrap)).

`git clone xxxx` is slow, we should make it faster to clone. I think use `--depth` option will better.

What do you think?

**Comment by KyleAMathews** [comment]
That's a great idea! We just throw the git repo away anyways. Could you add a PR for this? This will be a nice time saver for sure!
