### ISSUE TITLE
[docs] Align code in StaticQuery video and written tutorial

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#7297]
Right now, the example code in the [`StaticQuery` docs](https://next.gatsbyjs.org/docs/static-query/) isn't aligned between the video and the written docs.

To avoid confusion, we should probably update the written docs to use the same example as the video.

The code used in the video is here: https://github.com/jlengstorf/gatsby-staticquery

This would be a great first contribution for someone! 💪💜

**Comment by nhc** [comment]
So I had a go at the above issue.
