### ISSUE TITLE
createRemoteFileNode cause gatsby-develop to fail

### ISSUE THREAD

**Issue by alexluong** [gatsbyjs/gatsby#7298]
Hi.

I came across a problem as I use `createRemoteFileNode` when developing a plugin. In the gatsby site that uses the plugin, after I run `gatsby-develop`; `Ctrl + C`; `gatsby-develop`, I'll get an error:

```
TypeError: Cannot read property 'internal' of null
```

I got this problem once a while back. I tried to set up a fresh environment to file an issue but it ended up resolving the issue. Now I can recreate the bug and set up a test repo: https://github.com/alexluong/gatsby-issue-7298

Steps to recreate:

- `gatsby develop`
- `Ctrl + C`
- `gatsby develop`

Now, if I delete `rm -rf .cache` and `gatsby-develop`, it will work again. I don't know if it has something to do with `createRemoteFileNode`. Thanks!

**Comment by Chuloo** [comment]
@alexluong tried running your reproduction, ran into a bunch of errors. Seems like you used ES6 syntax in https://github.com/alexluong/gatsby-issue-7298/blob/master/plugins/gatsby-source-remote/src/gatsby-node.js, changed to CommonJS. 
Also, installed `gatsby-source-filesystem`, then gatsby as a peer dependency. Fixed these, and I couldn't get your errors on `gatsby-develop`
Here's [a reproduction](https://github.com/Chuloo/https://github.com/Chuloo/gatsby-7298) with the fixes.

You can try these let's know if you still run into the same issue.

**Comment by alexluong** [comment]
@Chuloo Thanks for the response. I checked out your repo but didn't see any differences from my original code. Can you show me what you changed?

Also, as for the ES6 syntax, I think I had Babel compile it to be compatible with Node 6 to `dist/gatsby-node.js`. Then in `gatsby-node.js` I just export out whatever it is in `dist`.
