### ISSUE TITLE
Question about 404 pages not redirecting

### ISSUE THREAD

**Issue by razvan-soare** [gatsbyjs/gatsby#7301]
Hey guys im trying to figure out why the 404 page is not working. If i go to `site/404` i can see the right page but if i go on a wrong url it will just say `The requested URL /fsd was not found on this server.`.

I tried to get some starter files that were working with 404 but locally and when i push them on my website the 404 is not working..

If you have any suggestions ? 
Thank you

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by afuh** [comment]
Check #7252

**Comment by Chuloo** [comment]
A duplicate issue to #7252. Closing this as it's a duplicate. If you experience something different, feel free to open a new issue [here](https://github.com/gatsbyjs/gatsby/issues/new/choose).
