### ISSUE TITLE
frontend masters by ryan florence excercise-1

### ISSUE THREAD

**Issue by aayushineeshu** [gatsbyjs/gatsby#7306]
##Refused to apply style from 'http://localhost:8080/1-your-first-component/styles.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
##assert.js:6 Assertion failed: found burrito
module.exports @ assert.js:6
exports.run @ tests.js:5
(anonymous) @ app.js:31
render @ ReactMount.js:386
React_render @ ReactPerf.js:50
(anonymous) @ app.js:30
(anonymous) @ 1-your-first-component.js:13
__webpack_require__ @ shared.js:51
(anonymous) @ multi_1-your-first-component:2
(anonymous) @ 1-your-first-component.js:5
__webpack_require__ @ shared.js:51
webpackJsonpCallback @ shared.js:22
(anonymous) @ 1-your-first-component.js:1
assert.js:6 Assertion failed: found tacos
module.exports @ assert.js:6
exports.run @ tests.js:6
(anonymous) @ app.js:31
render @ ReactMount.js:386
React_render @ ReactPerf.js:50
(anonymous) @ app.js:30
(anonymous) @ 1-your-first-component.js:13
__webpack_require__ @ shared.js:51
(anonymous) @ multi_1-your-first-component:2
(anonymous) @ 1-your-first-component.js:5
__webpack_require__ @ shared.js:51
webpackJsonpCallback @ shared.js:22
(anonymous) @ 1-your-first-component.js:1
assert.js:6 Assertion failed: found tostada
module.exports @ assert.js:6
exports.run @ tests.js:7
(anonymous) @ app.js:31
render @ ReactMount.js:386
React_render @ ReactPerf.js:50
(anonymous) @ app.js:30
(anonymous) @ 1-your-first-component.js:13
__webpack_require__ @ shared.js:51
(anonymous) @ multi_1-your-first-component:2
(anonymous) @ 1-your-first-component.js:5
__webpack_require__ @ shared.js:51
webpackJsonpCallback @ shared.js:22
(anonymous) @ 1-your-first-component.js:1
assert.js:3 ✔︎ ok did not find hush puppies
assert.js:6 Assertion failed: burrito first
module.exports @ assert.js:6
exports.run @ tests.js:9
(anonymous) @ app.js:31
render @ ReactMount.js:386
React_render @ ReactPerf.js:50
(anonymous) @ app.js:30
(anonymous) @ 1-your-first-component.js:13
__webpack_require__ @ shared.js:51
(anonymous) @ multi_1-your-first-component:2
(anonymous) @ 1-your-first-component.js:5
__webpack_require__ @ shared.js:51
webpackJsonpCallback @ shared.js:22
(anonymous) @ 1-your-first-component.js:1
assert.js:6 Assertion failed: tacos second
module.exports @ assert.js:6
exports.run @ tests.js:10
(anonymous) @ app.js:31
render @ ReactMount.js:386
React_render @ ReactPerf.js:50
(anonymous) @ app.js:30
(anonymous) @ 1-your-first-component.js:13
__webpack_require__ @ shared.js:51
(anonymous) @ multi_1-your-first-component:2
(anonymous) @ 1-your-first-component.js:5
__webpack_require__ @ shared.js:51
webpackJsonpCallback @ shared.js:22
(anonymous) @ 1-your-first-component.js:1

**Comment by KyleAMathews** [comment]
Hi, what is the problem you're seeing?

**Comment by aayushineeshu** [comment]
I am getting the error before changing the code in that exercise only i.e refused to apply stylesheet from loacalhost because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by aayushineeshu** [comment]
@KyleAMathews It was a config error, fixed it. Thanks!
