### ISSUE TITLE
Is it possible for a source plugin to return no nodes and without breaking the build?

### ISSUE THREAD

**Issue by reimertz** [gatsbyjs/gatsby#7307]
Hi there,

I am the creator of [gatsby-source-hire-with-google](https://github.com/reimertz/gatsby-source-hire-with-google) and have been running into issues when trying to support when there aren't any job posts. 

I've tried and looked for a solution in other source plugins but couldn't find one. 

Can anyone point me in the right direction how to properly handle this state without Gatsby breaking on build?

<3

**Comment by datakurre** [comment]
@reimertz Sounds like https://github.com/gatsbyjs/gatsby/issues/3344 (waiting for v2 to be released first)

**Comment by LekoArts** [comment]
Closing this in favor of https://github.com/gatsbyjs/gatsby/issues/3344
