### ISSUE TITLE
Allow more options to be given to gatsby-plugin-google-analytics

### ISSUE THREAD

**Issue by mattwexa** [gatsbyjs/gatsby#7308]
Hi,

I'd like to give more options to the gatsby-plugin-google-analytics plugin (so-called "create only" fields), but unfortunately this is not supported at the moment. Would you be open to support more options in the plugin? Or should I create my own plugin based on the existing gatsby-plugin-google-analytics?

Cheers,
Matthieu

**Comment by LeKoArts** [comment]
Feel free to send in a PR. Please make sure that the additional options are **optional** or have sensible defaults so that existing projects without these options don't break.

**Comment by mattwexa** [comment]
Ok I have opened #7316 with the changes I propose

**Comment by oorestisime** [comment]
@mattwexa probably this issue can be closed since the PR was accepted

**Comment by mattwexa** [comment]
Oops you're right, closing the issue now!
