### ISSUE TITLE
Add to KaTeX users

### ISSUE THREAD

**Issue by ylemkimon** [gatsbyjs/gatsby#7311]
Hey there, KaTeX maintainer here. Not really an issue. I'd like to ask if Gatsby (gatsby-remark-katex) would mind adding your logo to KaTeX user list? (https://github.com/Khan/KaTeX/pull/1569, preview availabe at https://deploy-preview-1569--katex.netlify.com/en/users.html) This is a really cool project! 😄

**Comment by KyleAMathews** [comment]
Hey sure! Go ahead and add your logo! You're project is great too :-)

**Comment by KyleAMathews** [comment]
*our logo 😅

**Comment by ylemkimon** [comment]
@KyleAMathews Thank you ❤️
