### ISSUE TITLE
Using Gatsby Image with Picture tag?

### ISSUE THREAD

**Issue by deadcoder0904** [gatsbyjs/gatsby#7313]
## Summary

I want to use `gatsby-image` with the `picture` tag. I need to use `picture` tag because I have different images for mobile, tablet & desktop resolutions.

## Relevant information

This is the current way I do it. Is this the right approach?

```js
<picture>
        <source
          media="(max-width: 560px)"
          srcSet={data.mobile.childImageSharp.fluid.src}
        />
        <source
          media="(max-width: 875px)"
          srcSet={data.tablet.childImageSharp.fluid.src}
        />
        <Img src={data.desktop.childImageSharp.fluid.src} />
</picture>
```

Because its used like this in the docs & I don't know if the method above is right

```js
<Img resolutions={data.file.childImageSharp.resolutions} />
```

I need 2 things from what I'm doing:

1. Optimized Images with Traced SVG in Pages
2. Different Images for Mobile, Tablet & Desktop

Is it right what I'm doing or is there another approach?

**Comment by KyleAMathews** [comment]
gatsby-image doesn't support "art direction" images like this as it seemed like it might overly complicate the API so I left it out.

If you can come up with a nice API, I'd love to explore adding it. Otherwise, your approach looks great! Except, make sure to query `srcSet` in addition to src and pass it to the source `srcSet`.

**Comment by deadcoder0904** [comment]
Hey @KyleAMathews the current way I showed above is wrong as I was not using `Img` from `gatsby-image` but a `styled-component` lol 😂

And AFAIK `Img` from `gatsby-image` is not a replacement for `img` from `DOM`. So I don't know how to get this thing work?

Currently, I am doing:

```js
<picture>
        <source
          media="(max-width: 560px)"
          src={data.mobile.childImageSharp.fluid.src}
          srcSet={data.mobile.childImageSharp.fluid.srcSet}
        />
        <source
          media="(max-width: 875px)"
          src={data.tablet.childImageSharp.fluid.src}
          srcSet={data.tablet.childImageSharp.fluid.srcSet}
        />
        <CustomImg fluid={data.desktop.childImageSharp.fluid} />
</picture>
```

where my custom image is a `styled-component` around `Img` from `gatsby-image` like:

```js
const CustomImg = styled(Img)`
  width: 5rem;
`;
```

The issue is I cannot show Mobile or Tablet images because of that. Only Desktop Image shows up even when screen is reduced. What's the workaround?
