### ISSUE TITLE
Invisible "Load More" button on the Showcase

### ISSUE THREAD

**Issue by greglobinski** [gatsbyjs/gatsby#7321]
When I'm browsing the Showcase, I scroll to the bottom and I'm looking for the "Load More" button, but if my pointer is  over a link area and that is almost always the button is covered by Chorme link preview.

![gatsby-showcase-loadmore-issue](https://user-images.githubusercontent.com/32480082/44115712-e5a0e384-a00e-11e8-9fc9-1a4f3b3a926e.png)

I think that's a good case to be bold. The button should be big centered and surrounded by white space.

![gatsby-showcase-loadmore-new](https://user-images.githubusercontent.com/32480082/44115867-39690848-a00f-11e8-8cbd-86ba45415210.png)

**Comment by haxzie** [comment]
Can I take this up?

**Comment by fk** [comment]
Hey Greg 👋, thanks for reporting this!

> almost always the button is covered by Chrome link preview

This worked in the past, it seems the margin styles that prevented this (and indented the button correctly) broke during a recent merge.

> I think that's a good case to be bold. The button should be big centered and surrounded by white space.

I agree, and I really like your mockup—much better! Let's do this!

**Comment by Manoz** [comment]
There you go. Hope I did everything correctly :)

**Comment by Manoz** [comment]
Fixed and merged in #7353

**Comment by fk** [comment]
Whoops, forgot to close this! Thanks again @Manoz!
