### ISSUE TITLE
[1.0] When inferring field types for graphql, correctly handle fields that are all null

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#733]
Currently it throws a mysterious error.

**Comment by 0x80** [comment]
So I discovered today. It took me a while to figure out what was going on from that error message.

What part of the code is responsible for it? Maybe I could have a look...

**Comment by KyleAMathews** [comment]
Two places:

* https://github.com/gatsbyjs/gatsby/blob/0124901cf6bf532b2b2744e0958c52fb19219935/packages/gatsby/lib/schema/infer-graphql-type.js#L84
* https://github.com/gatsbyjs/gatsby/blob/0124901cf6bf532b2b2744e0958c52fb19219935/packages/gatsby/lib/schema/infer-graphql-type.js#L124

The second line is where we build up a list of examples for fields. The first is where we decide the type of a specific field.

The trick is if a field is all nulls how do we pick a field for it. Default to string?

**Comment by KyleAMathews** [comment]
We just decided to ignore null fields.
