### ISSUE TITLE
[gatsby-source-wordpress] Beginner question about createPage()

### ISSUE THREAD

**Issue by nikosolihin** [gatsbyjs/gatsby#7335]
In the `using-wordpress/gatsby-node.js` example why don't we just pass in the whole page content (ACF, etc.) as argument for `createPage()`in the `context: {...}` object so that they appear in the `pageContext` prop for the template file?

I'm a little confused why it's preferred to query GraphQL twice, first in `gatsby-node.js` using:
```
{
  allWordpressPage { ... }
}
```
and then within the page template:
```
{
  wordpressPage(id: { eq: $id })
}
```

**Comment by KyleAMathews** [comment]
It improves the readability of code if the query for the needed data is in the same file as the component that's using that data.

Also, we don't re-run queries in `gatsby-node.js` so when you're iterating on a query e.g. adding a new field or whatever, this will be much faster when the query is in the component.

**Comment by nikosolihin** [comment]
Thanks for the clarification @KyleAMathews
