### ISSUE TITLE
Apply Sharp Image on Array containing Images?

### ISSUE THREAD

**Issue by deadcoder0904** [gatsbyjs/gatsby#7337]
I have an array containing Images & I need to apply Sharp on them. How do I do that?

Currently I have

```js
import img1 from "./img1";
import img2 from "./img2";

const apps = [
  {
    name: "App 1",
    featureImg: img1
  },
  {
    name: "App 2",
    featureImg: img2
  }
];

const Apps = <>
	{
		apps.map(app => (
			<div key={v4()}>
				<div>{app.name}</div>
				<img src={app.featureImg} />
			</div>
		))
	}
</>
```

As the array of apps is big, I want to use transformation dynamically rather than typing everything statically. Any solutions or workarounds regarding this?

**Comment by KyleAMathews** [comment]
Have you figured out how to query the images with `allFile`?

**Comment by deadcoder0904** [comment]
@KyleAMathews so I can think of a solution now. Tell me if its right?

I will make `Apps` a stateful component with `allFile` query & then print it from there.

**Comment by KyleAMathews** [comment]
@deadcoder0904 curious if you've gone through the tutorial and learned how to use gatsby-source-filesystem?

**Comment by deadcoder0904** [comment]
Ohh yes I did do it a long time ago but I guess I never read the whole thing completely. I'll give that a shot again & close this issue when I resolve it.

**Comment by deadcoder0904** [comment]
On further note, I don't think this use case is covered there & I didn't think too much about it either. Just thought about how would I implement this for 30 mins & couldn't come up with a solution so posted here.

**Comment by deadcoder0904** [comment]
So I used React Lifecycle methods & did it as follows - 

```js
import React from "react";
import { graphql } from "gatsby";
import Img from "gatsby-image";

class Apps extends React.Component {
  state = {
    apps: []
  };

  componentDidMount() {
    const { data } = this.props;
    const apps = [
      {
        name: "App 1",
        featureImg: data.img1.childImageSharp.fluid
      },
      {
        name: "App 2",
        featureImg: data.img2.childImageSharp.fluid
      }
    ];
    this.setState({ apps });
  }

  render() {
    const { apps } = this.state;
    return (
      <>
        {apps.map(app => (
          <div key={v4()}>
            <div>{app.name}</div>
            <img src={app.featureImg} />
          </div>
        ))}
      </>
    );
  }
}

const query = graphql`
  {
    img1: file(relativePath: { eq: "apps/img1.png" }) {
      ...SquaredImageBigFluid
    }
    img2: file(relativePath: { eq: "apps/img2.jpg" }) {
      ...SquaredImageBigFluid
    }
  }
`;
```

Whoops stupid me @KyleAMathews 😂
