### ISSUE TITLE
[v2] Best place for static files to import into components?

### ISSUE THREAD

**Issue by sambaines** [gatsbyjs/gatsby#7358]
Very simply I see that there is no static files folder for images, etc. like you get with some other development environments. So the question is where is the best place to put static files into the directory setup for importing into components?

i.e. do I just put the here `src/components/` or do I need specific directory like `src/components/images/` or do I put them in with pages?

I understand that once I know where to put them I can just import them at the top of react components for use within them.

Likewise for images into say a `.md` for a blog post does these just sit alongside the MD file in the pages directory before being transformed/remarked with the correct plugin?

I am a newbie any help is greatly appreciated. Thanks.

**Comment by Manoz** [comment]
I'm not sure if there is some kind of best practises for this. 
I usually keep my assets inside my components depending on what I do. That way Webpack can do his thing.
If you put your assets inside a `static` folder at the root of your project, Webpack will just copy them at the root of the `public` directory. 

There is a good explanation on how to work with assets in Gatsby v2 [here](https://next.gatsbyjs.org/docs/adding-images-fonts-files/). Have Gatsbying :)

**Comment by sambaines** [comment]
Thanks @Manoz for the information, that seems to be an easy way to structure the files that I can use so will follow it similarly. And that link to the docs answers my question about markdown images - basically handles them the same way as above when bundled.
