### ISSUE TITLE
Refreshing blog index page causes links to 404

### ISSUE THREAD

**Issue by MayerMediaCo** [gatsbyjs/gatsby#7365]
## Description

My site is hosted on Netlify. On the hosted version of my site, when I refresh the blog index page located at "/blog" the url turns to "/blog/" . After the url changes, when I try to follow a link to a blog post, the path becomes '/blog/blog/slug' and the created path name 404s.

On local host, the issue does not occur at all. Asset optimization is off on Netlify. I have installed Gatsby-Plugin-Trailing-Slash as well.

### Steps to reproduce

On hosted site, refresh /blog page.  Url becomes /blog/
After url change, when navigating to a graphql generated path, path becomes /blog/blog/"slug"
blog post page 404s

### Expected result

post link goes to blog page, despite a page refresh

### Actual result

Upon page refresh, url has trailing slash added and navigating to graphql generated path causes 404

Navigating to other pages ("/about" "/" "/contact") works as expected, error only occurs when using a graphql generated path on this page

### Environment

System:
OS: macOS High Sierra 10.13.6
CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Shell: 5.3 - /bin/zsh
Binaries:
Node: 8.11.3 - /usr/local/bin/node
Yarn: 1.7.0 - /usr/local/bin/yarn
npm: 6.3.0 - /usr/local/bin/npm
Browsers:
Chrome: 68.0.3440.106
Safari: 11.1.2
npmPackages:
gatsby: next => 2.0.0-beta.61
gatsby-link: ^1.6.45 => 1.6.45
gatsby-plugin-google-analytics: ^1.0.31 => 1.0.31
gatsby-plugin-google-fonts: 0.0.4 => 0.0.4
gatsby-plugin-mailchimp: ^2.2.3 => 2.2.3
gatsby-plugin-netlify-cms: ^3.0.0-beta.3 => 3.0.0-beta.3
gatsby-plugin-react-helmet: next => 3.0.0-beta.4
gatsby-plugin-remove-trailing-slashes: ^1.0.9 => 1.0.9
gatsby-plugin-sass: ^2.0.0-beta.5 => 2.0.0-beta.5
gatsby-react-router-scroll: ^1.0.18 => 1.0.18
gatsby-source-filesystem: ^1.5.39 => 1.5.39
gatsby-transformer-remark: ^1.7.44 => 1.7.44
npmGlobalPackages:
gatsby-cli: 1.1.58

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by MayerMediaCo** [comment]
I have just used the default starter for v2 in this instance. As far as the actual code itself, most of the GraphQL queries is just follow along to the docs page.

The repo can be found here:
https://github.com/MayerMediaCo/MayerMediaCo2.0

The site is hosted here:
www.mayermediaco.com

I am just super confused as to why it occurs when only when hosted but on local host it is perfectly fine.

Unfortunately I’m only able to access mobile right now or I would post code snippets

**Comment by KyleAMathews** [comment]
This is a netlify setting I believe that does this. Please check that out. Enjoy your new Gatsby site!

**Comment by MayerMediaCo** [comment]
I checked with netlify, and the setting that does this is not enabled

**Comment by Manoz** [comment]
![peek 16-08-2018 15-05](https://user-images.githubusercontent.com/1554207/44210250-3bfd6b00-a166-11e8-8f94-f0b1a4b8432b.gif)
I don't know how to reproduce your issue. Everything runs nicely actually. I'll fork your repo after the work and see if something's wrong.

**Comment by MayerMediaCo** [comment]
The issue occurs when you refresh the page and then follow the link to the blog post. Once I get back to my computer this evening I’ll make a video if it’s helpful. I talked with netlify and it’s not something on their end. I appreciate the help!

**Comment by Manoz** [comment]
First thing first : you're actually using Gatsby v2 but still using some plugins supporting Gatsby v1. You should update all Gatsby plugins to `@next` if possible. It's not necessary since your project can run without this update but its best in case you add more features.

The weird thing is your GraphQL queries. You have 2 different path on your posts.
Gatsby generate `/blog/post-name` links while MarkdownRemark have `/post-name` for your posts path.
```
    "allSitePage": {
      "edges": [
        {
          "node": {
            "path": "/blog/buyer-personas/"
          }
        }
      ]
    },
    "allMarkdownRemark": {
      "edges": [
        {
          "node": {
            "frontmatter": {
              "title": "Buyer Personas",
              "slug": "buyer-personas",
              "path": "buyer-personas"
            }
          }
        }
      ]
    }
```

In your `components/post-link.js` file I changed the `<Link to...>`  component from 
```
<Link to={post.frontmatter.path}>{post.frontmatter.title}</Link>
```
to
```
<Link to={`/blog/${post.frontmatter.path}`}>{post.frontmatter.title}</Link>
```

I deployed the branch on Netlify and looks like it's working and it fixed everything.
You should maybe investigate near your `./gatsby-node.js` file somehow.

It's a workaround for now but looks like its working. Here's the [complete diff](https://github.com/Manoz/MayerMediaCo2.0/commit/0d5bca56625cc8bfb614f96bfe776a21c641c9f9).
I don't have that much time today but at least you have some options to investigate. Good luck :)
