### ISSUE TITLE
Cache /public folder in builds to avoid image thumbnail generation

### ISSUE THREAD

**Issue by humphreybc** [gatsbyjs/gatsby#7366]
## Summary

At the moment Gatsby regenerates over 600 image thumbnails in every build. This adds about 90 seconds to the build time. I know Gatsby will not regenerate thumbnails if it sees they exist in /public, so I can [cache that in CircleCI](https://circleci.com/docs/2.0/caching/), however my problem is then trying to find a key to use for the cache so CircleCI knows when to bust the cache or when to reuse an old one.

If I use a static key like `public-folder`, then CircleCI will never save an updated cache:

```
Skipping cache generation, cache already exists for key: public-folder
Found one created at 2018-08-16 01:52:08 +0000 UTC
```

What do you recommend I use as a key to cache the /public folder in builds?

**Comment by humphreybc** [comment]
Hmm. I think the problem with that is that the /public folder is not committed to the repository. So when the CI runs and pulls down the repo, before it runs `gatsby build`, there's a chicken and egg problem – you can't count the number of items in a folder to determine whether to restore the folder from a cache, when said folder doesn't exist until it's restored.

**Comment by bradleyg** [comment]
I think this would work, as the cache falls back (note the use of `keys` rather than `key`). Effectively always reusing the latest cache. [Docs](https://circleci.com/docs/2.0/caching/#example-caching-configuration).

```yaml
     - restore_cache:
          keys:
            - always-

      - run:
          command: npm run build

      - save_cache:
          key: always-{{ epoch }}
          paths:
            - public
`
