### ISSUE TITLE
404 pages are blank in production

### ISSUE THREAD

**Issue by stripeyjumper** [gatsbyjs/gatsby#7371]
## Description

The page flashes then goes blank if you navigate to any 404 page in production:
https://next.gatsbyjs.org/thispagedoesntexist

- It happens on my own page hosted on Netlify as well as gatsbyjs.org.  
- No errors are thrown on my page, but gatsbyjs.org has some 404 errors for font assets.
- The https://next.gatsbyjs.org/404 page still works ok, so I haven't managed to reproduce it in dev.

It looks like it might be related to #7289.  Could it be something to do with the new router?

### Steps to reproduce

Navigate to a non existent page:
https://next.gatsbyjs.org/thispagedoesntexist

### Expected result

The 404 page should be rendered.

### Actual result

The page renders and then disappears.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by KyleAMathews** [comment]
Thanks for the bug report! This will be fixed in https://github.com/gatsbyjs/gatsby/pull/7355
