### ISSUE TITLE
Can't build the website with the plugin gatsby-plugin-postcss

### ISSUE THREAD

**Issue by MKruschke** [gatsbyjs/gatsby#7372]
## Description
I use PostCSS for my current website and migrated the project from gatsby v1 to gatsby v2 (https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#restore-v1-post-css-setup). After that I couldn't build my website anymore. It seems the [gatsby-plugin-postcss](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-postcss) isn't working when we run the build step. 

Note: This issue affects only the build step the *develop* mode works as expected.

### Steps to reproduce
To reproduce the issue, I created a small project that based on hello-world v2 template.

1. checkout the following repository [gatsby-postcss-build-issue](https://github.com/MKruschke/gatsby-postcss-build-issue).
2. npm install
3. npm run build

### Expected result

The build steps runs through without error and css will be loaded and applied.

### Actual result

The build step encounter an error when we are in the task _Building static HTML for pages failed_.
<img width="569" alt="build output" src="https://user-images.githubusercontent.com/1651782/44205539-000ed980-a157-11e8-9eb2-6b56889b5014.png">

After some debugging I found more details.
<img width="1026" alt="build-html js gatsby-postcss-build-issue 2018-08-16 11-02-33" src="https://user-images.githubusercontent.com/1651782/44205706-980cc300-a157-11e8-83a7-1be0251c22da.png">

### Environment

  System:
    OS: macOS High Sierra 10.13.5
    CPU: x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 9.10.0 - ~/.nvm/versions/node/v9.10.0/bin/node
    Yarn: 1.3.2 - /usr/local/bin/yarn
    npm: 6.3.0 - ~/.nvm/versions/node/v9.10.0/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 61.0
    Safari: 11.1.1
  npmPackages:
    gatsby: next => 2.0.0-beta.105 
    gatsby-plugin-postcss: ^1.0.0 => 1.0.0 
  npmGlobalPackages:
    gatsby-cli: 1.1.58
    gatsby: 1.9.277

### File contents (if changed)
see repository [gatsby-postcss-build-issue](https://github.com/MKruschke/gatsby-postcss-build-issue).

**Comment by MKruschke** [comment]
the issue could be related to this one https://github.com/webpack-contrib/mini-css-extract-plugin/issues/73#issuecomment-385288770. I saw that the gatsby-plugin-postcss only adds the loader but not the webpack plugin.

**Comment by m-allanson** [comment]
Can you try bumping the version of "gatsby-plugin-postcss" to `next`?

**Comment by MKruschke** [comment]
@m-allanson after bumping the version it works 👍 

Can you also tell me where I can find the source code of the v2?  It seems this is not the current master or? I also couldn't saw branch with a proper name :)

**Comment by m-allanson** [comment]
And v1 lives on [the `v1` branch](https://github.com/gatsbyjs/gatsby/tree/v1). Note that v2 is still a beta, which is why the `next` tag is the recommended way to install it.

**Comment by MKruschke** [comment]
Good to know. I'll upgrade my other dependencies to and when I find something I'll add a new issue. Thanks for your time.
