### ISSUE TITLE
[v2] PageRenderer not working as intended

### ISSUE THREAD

**Issue by ivorpad** [gatsbyjs/gatsby#7380]
## Description

I'm trying to recreate the modal version of Gatsbygram in my own site and I need the PageRenderer component to render the background on the modal and when I upgraded Gatsby to 2.0.0-beta.106 PageRenderer stopped working

### Steps to reproduce

1. See below in **File contents**

2. OR If you upgrade the Gatsby package to 2.0.0-beta.106 in Gatsbytagram you get the same result when opening a modal.

3. OR Download the Gatsbygram example > `yarn install` > `gatsby develop` and you get the same issue right out of the box.

### Expected result

The Work page should render below `<h1>Hello</h1>` at the index page.

### Actual result

Got an error: `Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.`

### Environment
```
  System:
    OS: macOS High Sierra 10.13.5
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.5.0 - /usr/local/bin/node
    Yarn: 1.2.1 - /usr/local/bin/yarn
    npm: 6.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 61.0.2
    Safari: 11.1.1
  npmPackages:
    gatsby: ^2.0.0-beta.106 => 2.0.0-beta.106 
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```

### File contents

```
{
  "name": "page-renderer-bug",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "gatsby": "^2.0.0-beta.106",
    "react": "^16.4.2",
    "react-dom": "^16.4.2"
  }
}
```

```
import React, { Component } from 'react'

export default class work extends Component {
  render() {
    return (
      <div>
        <h1>Work</h1>
      </div>
    )
  }
}
```

```
import React, { Component } from 'react'
import { PageRenderer } from 'gatsby';

export default class index extends Component {
  render() {
    return(
	<div>
	 <h1>Hello</h1>
     <PageRenderer location={{ pathname: "/work" }} />
	</div>
	);
  }
}
```

**Comment by ivorpad** [comment]
@Chuloo 

To reproduce the issue just download the current Gatsbygram example and run `yarn install` > `gatsby develop`, open a Gatsbygram post and you'll see the background page doesn't show up.

Here's a graphical representation of the bug:

 
![bug](https://user-images.githubusercontent.com/52452/44362883-6ade4e80-a490-11e8-9f74-e5b7f5044582.gif)

**Comment by DanielPintilei** [comment]
Hi, PageRenderer stopped working for me in production; during development it works fine.
And the gatsbygram example is not working also, it is rendering a gray background as in @ivorpad's example.
