### ISSUE TITLE
Support filtering on deep nested nodes

### ISSUE THREAD

**Issue by LekoArts** [gatsbyjs/gatsby#7385]
## Description

First of all I don't know if it's the best fitting title (feel free to change it to a better one 😉).
So basically my issues are described in this PR:
https://github.com/gatsbyjs/gatsby/pull/6315

This PR unfortunately didn't fix my issues on filtering tags. Those tags are custom types (in the Prismic backend) and look like this in the GraphQL response:
https://github.com/gatsbyjs/gatsby/pull/6315/commits/a17c1d36e949bb66e5ab8c630380c8472fd24855

### Steps to reproduce

I can't give everyone access to my API keys so you'd need to setup a project on your own (though @pieh has one key for testing)

### Expected result

I should be able to query like with markdown:
https://github.com/LeKoArts/portfolio/blob/master/src/templates/tag.jsx#L65

And also be able to use group like with markdown:
https://github.com/LeKoArts/portfolio/blob/master/src/pages/tags.jsx#L78

**Comment by LeKoArts** [comment]
@m-allanson Could this also be added to your EPIC?
