### ISSUE TITLE
Problems loading /starter-showcase/ on next.gatsbyjs.org

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#7391]
If you visit https://next.gatsbyjs.org/starter-showcase/ it shows the SSRed HTML and then once the JS loads, it prints in the browser console: "A page wasn't found for "/starter-showcase/" then shows a 404 page.

**Comment by amberleyromo** [comment]
This fix works locally but not in prod. Originally I thought it was a deploy issue (@thebigredgeek?) but that seems to be resolved and I'm seeing it on prod still.

Non-blocking for further work (since it works locally) but this remains unresolved to some degree.

Thoughts @KyleAMathews?

**Comment by amberleyromo** [comment]
Closing the loop -- resolved.
