### ISSUE TITLE
[perilbot] delete branches after merge

### ISSUE THREAD

**Issue by calcsam** [gatsbyjs/gatsby#7396]
MISSION: Give @m-allanson magical robot assistance so he doesn't have to do this anymore:

![image](https://user-images.githubusercontent.com/4388699/44240915-9d790600-a175-11e8-963a-e3728ba7a588.png)

Peril could do this!

**Comment by DSchau** [comment]
Yeah - actually this would be _awesome_ and probably fairly easy to do with Peril.

Removing the stale label and adding a comment to keep it open 👌

**Comment by DSchau** [comment]
Haven't looked into this _at all_ but a cursory Google surfaced Probot, which seems to have this capability by default.

Would be nice to leverage tools so we don't have to build it ourself, but would merit some further research before we start enabling things on a whim!

https://probot.github.io/apps/delete-merged-branch/

**Comment by lannonbr** [comment]
And this is part of GitHub now as a toggle setting to a repo: https://github.blog/changelog/2019-07-31-automatically-delete-head-branches-of-pull-requests/

Any updates on this?

**Comment by sidharthachatterjee** [comment]
I've installed Probot for now to delete merged branches! See it in action at https://github.com/gatsbyjs/gatsby/pull/17032

Let's close this 🎉
