### ISSUE TITLE
gatsby carousel

### ISSUE THREAD

**Issue by emilbruckner** [gatsbyjs/gatsby#740]
I want to build an image carousel for my gatsby site and was planning to use react-slick, which works perfectly unless I call a subpage directly, where the gatsby-magic does same things that make the slider not work

Does someone know what exactly gatsby does when creating the static sites that stops other components from working?

Thanks

latest gatsby, node, macOS

**Comment by KyleAMathews** [comment]
What do you mean by "call a subpage directly".

Gatsby and react-slick should work together just fine...

**Comment by emilbruckner** [comment]
I now know what's causing the trouble: calling slider.slickGoTo() in componentDidMount, that's why I had no problems when sites weren't served directly.
I guess one should use slick's initialSlide setting for this.

Will close this

Thanks Kyle, Gatsby is awesome
