### ISSUE TITLE
[v2] `gatsby-plugin-catch-links` uses old api

### ISSUE THREAD

**Issue by azdanov** [gatsbyjs/gatsby#7404]
I got `The "push" method is now deprecated and will be removed in Gatsby v3. Please use "navigate" instead.` in my console.

Should this be replaced with `navigate` as per [migration guide](https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#a-history-prop-is-no-longer-passed-to-page-components)?

https://github.com/gatsbyjs/gatsby/blob/eec33935f0beea7971a5bb94eb4b9e481e5b1be9/packages/gatsby-plugin-catch-links/src/gatsby-browser.js#L1

**Comment by pieh** [comment]
I think it should be `import { navigate } from "gatsby"`. Do you want to create PR for it?

**Comment by azdanov** [comment]
Sure!
