### ISSUE TITLE
DPI-dependent variable image quality

### ISSUE THREAD

**Issue by AndrewIngram** [gatsbyjs/gatsby#7407]
## Summary

Automatically adjust image quality downwards for higher pixel density displays

### Motivation

Right now, the default image quality for generated images is 50. This is configurable but still not ideal. Generally speaking, we can get away with higher compression on higher DPI displays. An image that needs a quality of 90 to look good on 1x display, might only need 60 to look good on a 2x display.  There are a few articles discussing the idea, but someone else will need to assess quality because my eyesight isn't accurate enough to do so.

http://alidark.com/responsive-retina-image-mobile/
https://www.netvlies.nl/tips-updates/algemeen/design-interactie/retina-revolution/
https://www.filamentgroup.com/lab/compressive-images.html

The key point is that when generating images, we're not just choosing width-x-height, but also the intended pixel density for display. This means it's possible to adjust other image properties (sharpness, quality, etc) to find the best balance of quality to filesize.

This is definitely an area which will require some research, but right now we're having to up the quality to 90 so that images don't look terrible on 1x monitors, but this excessively penalises mobile users who nearly always have at least 2x.

**Comment by baukevanderlaan** [comment]
Thanks for bringing this up – it looks like this can potentially save a lot on image heavy websites.

@gillkyle Would this be something you know more of?

Would it be a good idea to have an extra set of quality arguments for `2x` and `3x` in `gatsby-plugin-sharp`?

Maybe in the future `gatsby-transformer-sharp` can even take an educated guess about whether an image is photographic or graphic and apply corresponding compression based on that verdict?
