### ISSUE TITLE
GIF not working in markdown-remark 

### ISSUE THREAD

**Issue by philiplackmaker** [gatsbyjs/gatsby#7414]
## Description
Hey, everyone, I hope you can help! I am having a small issue with Gifs not working in markdown remark. They are reproduced in the build but they don't scale and they break the grid.
### Steps to reproduce

1. Add ![Gif](image_preview.gif)
2 Run develop
3. Gif added and multiple breakpoints to the site.

### Expected result

Gif is on the page but scales as the browser scales the same as the example of using-gatsby-remark

### Actual result

What happened.
![image](https://user-images.githubusercontent.com/1346962/44265865-4f6d0c80-a220-11e8-80a0-a3c4e2c26e43.png)

![image](https://user-images.githubusercontent.com/1346962/44265890-627fdc80-a220-11e8-9eda-ca3bca247dc0.png)

(sorry for my too many tabs if it gives you anxiety) 
### File contents (if changed)

```
  module.exports = {
    plugins: [
      {
        resolve: 'gatsby-plugin-mixpanel',
        options: {
          apiToken: 'd6e013f46ee1a5160a1dc40eaf3f3178', // required
        },
      },
      {
        resolve: 'gatsby-plugin-intercom-spa',
        options: {
          app_id: "d7vu7om5"
        },
      },
      `gatsby-plugin-react-helmet`,
      `gatsby-plugin-styled-components`,
      `gatsby-plugin-sass`,
      `gatsby-remark-copy-linked-files`,
      `gatsby-transformer-sharp`,
      `gatsby-plugin-sharp`,
    
      {
        resolve: `gatsby-source-filesystem`,
        options: {
          path: `${__dirname}/src/pages`,
          name: 'pages',
        },
      },
      {
        resolve: 'gatsby-source-filesystem',
        options: {
          path: `${__dirname}/src/images`,
          name: 'images',
        },
      },
      {
        resolve: `gatsby-transformer-remark`,
        options: {
          // In your gatsby-transformer-remark plugin array
          plugins: [

            {
              resolve: `gatsby-remark-images`,
              options: {
                maxWidth: 1080,
              },
            },
            `gatsby-remark-emoji`,
            'gatsby-remark-static-images',
            'gatsby-remark-copy-linked-files',

          ],
        },
      },
      
    ],
  }
```

**Comment by philiplackmaker** [comment]
https://github.com/philiplackmaker/folio-2018 <- my repo

**Comment by Chuloo** [comment]
Could you check your repo, couldn't reproduce the error. Threw a bunch of `Uncaught TypeError: Cannot read property 'childImageSharp' of null` in the browser. Also, would be good to resolve the merge conflict in `src/pages/index.js`.

**Comment by philiplackmaker** [comment]
@Chuloo Thanks for having a look at it. I guess you cloned master? As that was a bit of mess but it should be good with no conflicts.

**Comment by hgezim** [comment]
Here are my reproduction steps:

1. `git clone git@github.com:hgezim/tmp-docs.git`
2. `cd tmp-docs`
3. `yarn install`
4. `yarn run dev`
5. Navigate to [http://localhost:8000/formatting/#main-picture](http://localhost:8000/formatting/#main-picture) and notice the broken image:

<img width="1256" alt="localhost_8002_formatting__main-picture" src="https://user-images.githubusercontent.com/124675/45599500-dd681e80-b9a9-11e8-88e8-028c6b7a8b82.png">

**Comment by khalidsaifullaah** [comment]
Was anyone able to solve the .gifs non-responsive issue?
