### ISSUE TITLE
[www] docs sidebar container sizes not aligned with visible lines

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#7423]
Hm, I'm going to need to come back to this. Can't remember the series of actions that led to this behavior. There were just several times where the boxes around the "expand/collapse" arrows had an extra line at the bottom.

There were also times with the Quick Start category name got indented too far in, along with its accompanying line.

**Comment by fk** [comment]
Yeah there's def. something funky going on with the styles (that I didn't notice before … :/).
Will take a closer look ~Wednesday-ish.

> There were also times with the Quick Start category name got indented too far in, along with its accompanying line.

This was also reported in https://github.com/gatsbyjs/gatsby/issues/7422#issuecomment-414131922, here's a screenshot courtesy of @stefanivic 🙏:

<img src="https://i.imgur.com/YOA0AFE.png" />

That screenshot also shows what I've been noticing -- "Guides" shouldn't be bold and black here.

**Comment by fk** [comment]
Added #7738 to capture just

> There were also times with the Quick Start category name got indented too far in, along with its accompanying line.

which is fixed via #7528 and live on https://next.gatsbyjs.org/.
Couldn't reproduce the other issue described here yet:

> There were just several times where the boxes around the "expand/collapse" arrows had an extra line at the bottom.

**Comment by kkemple** [comment]
this seems to be resolved completely, @shannonbux could you verify?

**Comment by shannonbux** [comment]
Yes, seems resolved. Thanks @kkemple !
