### ISSUE TITLE
[www] docs sidebar user confusion navigating btw docs and tutorial

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#7424]
### Initial problem

Many users, when they are on the Tutorial page, can't remember how to get back to Docs.

In an effort to solve this issue, I made a link to the Main Tutorial under Quick Start category in Docs. I also made a link to the Quick Start doc at the top of the Tutorial sidebar. 

It appears this has created more confusion and didn't solve the initial problem.

### New confusion

Some users get confused when, under Quick Start, they click on Main Tutorial (Step-by-Step) because the sidebar changes, but the top navigation does not show that they are in the Tutorial. And the sidebar is not different enough to indicate that they aren't in the docs anymore.

The same confusion happens when people are in the tutorial and click on "Quick Start" at the top.

### How to solve this
I propose we take out the links that are confusing people and then see if #7425 solves the initial problem mentioned above.

Take out these links:
* link to the Main Tutorial under Quick Start category in Docs
* link to the Quick Start doc at the top of the Tutorial sidebar

### Future enhancements
If #7425 doesn't completely solve the problem, we'll need to think of new solutions.

**Comment by Manoz** [comment]
Might be related to #7429 if I understand the issue?

**Comment by shannonbux** [comment]
Just fixed this by removing the links.
