### ISSUE TITLE
[EPIC] v1.5 Docs IA redesign - cleanup

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#7427]
### Who will own this?

_What Area of Responsibility does this fall into? Who will own the work, and who needs to be aware of the work?_

**Area of Responsibility:**

_Select the Area of Responsibility *most impacted* by this Epic_

- [ ] Community
- [x] Learning
- [ ] Gatsby Core
- [ ] Enterprise
- [ ] Design
- [ ] Marketing
- [ ] Company/Admin
- [ ] Sales

     |                 |       |
     | --------------- | ----- |
     | AoR owner       | @shannonbux |
     | Domain owner   | @shannonbux |
     | Project manager | @name |
     | Tech lead       | @kkemple  |
     | Contributors    | @fk  |

### Summary

This closes https://github.com/gatsbyjs/gatsby/issues/6899, which has been shipped (yay!) and acts as a landing page for any issues and bugs that arise from the new sidebar in the .org docs navigation.

### How will this impact Gatsby?

**Domains**

_List the impacted domains here_

**Components**

_List the impacted Components here_

### Goals

_What are the top 3 goals you want to accomplish with this epic? All goals should be specific, measurable, actionable, realistic, and timebound._

1. Reduce the number of bugs before v2 launch

### How will we know this epic is a success?

**User Can Statement**

- User can clearly see where they are in the docs sidebar
- User can find the docs they are looking for without being distracted or blocked by bugs

**Metrics to Measure Success**

- same as goal above

### Additional Description

We are partially done with this epic. It seems that some of the bugs are related to other bugs too.

### What are the risks to the epic?

This could go wrong if we don't devote enough resources to it or prioritize it correctly in comparison with other projects.

### What questions do we still need to answer, or what resources do we need?

NA

### How will we complete the epic?

- Squash the bugs listed in this Epic (issues listed below)
- Weekly meetings

### How else could we accomplish the same goal?

No other ways to accomplish this goal.

**Comment by fk** [comment]
No objections! 👍
