### ISSUE TITLE
[www] searching for doc doesn't select doc on sidebar

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#7428]
From user interviews:

### Actions
1. Type adding search" into search bar
2. Hit enter to select first search result

### Expected behavior
1. Page appears
2. Title "Adding Search" selected on sidebar and visible

### Actual behavior
1. Page appears, but with no margin above title
2. No items on sidebar are selected

**Comment by fk** [comment]
Thanks for adding this @shannonbux! 🙏

**Comment by kartiklad** [comment]
Hey @shannonbux, I think I've found the bug which causes this issue in the side bar. It's basically to do with a condition in getActiveItem. I also noticed that if the URL has a hash in it and you refresh the page, the Sidebar selection doesn't work. 

I've raised a PR which fixes both issues. #7467

**Comment by fk** [comment]
Hey @kartiklad! 👋
Nice!!! Will take a look at your PR in a minute!

**Comment by fk** [comment]
Thank you @kartiklad! 🤗
