### ISSUE TITLE
Add Snapchat, Stitchfix, AAA, CapitolOne sites to site showcase

### ISSUE THREAD

**Issue by calcsam** [gatsbyjs/gatsby#7430]
Some pretty high profile sites just went up on Gatsby, we should add them to the site showcase!

* https://www.stitchfix.com/
* kit.snapchat.com
* housemanager.calstate.aaa.com/
* unionplus.capitalone.com/

**Comment by rrs94** [comment]
Hi! I made a [PR](https://github.com/gatsbyjs/gatsby/pull/7445), looks like House Manager & Union Plus were already in the showcase so didn't add those.

**Comment by nodox** [comment]
Seems like its been merged! What reasons do we have for keeping the issue open? 

@m-allanson @pieh @calcsam

**Comment by pieh** [comment]
Being forgetful and relying to autoclosing issues with PRs ;) Thanks for reminder @nodox!
