### ISSUE TITLE
gatsby-link: small bug in type declarations for Typescript

### ISSUE THREAD

**Issue by mattes3** [gatsbyjs/gatsby#7435]
## Description

When compiling with Typescript 3.0.1, I get an error message concerning the typings for gatsby-link/index.d.ts.

### Steps to reproduce

`import Link from 'gatsby-link';`

### Expected result

This should compile just fine.

### Actual result

Typescript compiler complains:

`Generic type 'LinkProps<TState>' requires 1 type argument(s).`

This is because LinkProps in reach/router is declared as:

```
export interface LinkProps<TState> extends AnchorProps {
    to?: string;
    replace?: boolean;
    getProps?: (props: LinkGetProps) => {};
    state?: TState;
}
```

### Environment

  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.6.0 - ~/.nvm/versions/node/v10.6.0/bin/node
    Yarn: 1.9.4 - ~/.nvm/versions/node/v10.6.0/bin/yarn
    npm: 6.1.0 - ~/.nvm/versions/node/v10.6.0/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 60.0.1
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.0.0-beta.106 => 2.0.0-beta.106 
    gatsby-image: ^1.0.55 => 1.0.55 
    gatsby-plugin-feed: next => 2.0.0-beta.4 
    gatsby-plugin-google-analytics: next => 2.0.0-beta.5 
    gatsby-plugin-offline: next => 2.0.0-beta.9 
    gatsby-plugin-react-helmet: next => 3.0.0-beta.4 
    gatsby-plugin-sharp: next => 2.0.0-beta.9 
    gatsby-plugin-typescript: ^2.0.0-beta.9 => 2.0.0-beta.9 
    gatsby-plugin-typography: next => 2.2.0-beta.3 
    gatsby-remark-copy-linked-files: next => 2.0.0-beta.3 
    gatsby-remark-embed-youtube: 0.0.7 => 0.0.7 
    gatsby-remark-images: next => 2.0.1-beta.11 
    gatsby-remark-prismjs: next => 3.0.0-beta.7 
    gatsby-remark-responsive-iframe: next => 2.0.0-beta.3 
    gatsby-remark-smartypants: next => 2.0.0-beta.3 
    gatsby-source-filesystem: next => 2.0.1-beta.10 
    gatsby-transformer-remark: next => 2.1.1-beta.7 
    gatsby-transformer-sharp: next => 2.1.1-beta.7 
  npmGlobalPackages:
    gatsby-cli: 2.0.0-beta.7

**Comment by Chuloo** [comment]
update the typescript typings in gatsby-link.

**Comment by mattes3** [comment]
Hi @Chuloo 

Here is a repo that I created to reproduce the compile time errors in Typescript:
https://github.com/mattes3/gatsby-typescript-blog-v2

**Comment by mattes3** [comment]
Hi all...

Any progress on this one?

**Comment by pieh** [comment]
Hey @mattes3 ,
I don't think anyone worked on that. Would you be interested in helping us fix this? I don't know typescript, so I'm not sure what and how should be updated :(

**Comment by seaneking** [comment]
Looks like this is still an issue FWIW
