### ISSUE TITLE
Multiple layout pages with gatsby-starter-business

### ISSUE THREAD

**Issue by sunfudge** [gatsbyjs/gatsby#7439]
What do I need to change in gatsby-node.js file, so that I can use multiple layout files?

What I want to achieve is to have one layout for the landing page and another for the rest.

I found some info [here ](https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#choosing-the-page-layout )but if I couldn't work it out, so that this works with [this ](https://github.com/gatsbyjs/gatsby-starter-default) (gatsby-starter-business) starter.

I would be appreciate your help with this.

**Comment by nikosolihin** [comment]
If you want to gear up for v2, you might want to move layouts under src/components and just use the standard React composition model to render different layouts. Gatsby no longer maintains, or needs to maintain, separate behavior for handling layouts.

If you want to render different templates during the createPages API, query your data source then  conditionally assign different template paths to the component value of createPage().

**Comment by chmac** [comment]
I think this can be closed now that Gatsby v2 is live and layouts are just arbitrary components. @sunfudge if you think this is still an issue, please reopen and I'll try to help you resolve the issue.
