### ISSUE TITLE
Gatsby-Node.js error when trying to create tags page 

### ISSUE THREAD

**Issue by sparklesam** [gatsbyjs/gatsby#7442]
My setup is a bit different from standard template, as I create slug from frontmatter. I got error saying ReferenceError: res is not defined on line 38. `_.each(result.data.allMarkdownRemark.edges, ({ node }) => {` 

I'm still a newbie, would appreciate if there are any syntax error. 

'
    return new Promise((resolve, reject) => {
        const pages = []
        const postTemplate = path.resolve('src/templates/blog-post.js');
        const tagTemplate = path.resolve('src/templates/tag-page.js');
        graphql(`
        {
            allMarkdownRemark {
                edges {
                  node {
                      html
                      id
                      frontmatter {
                          path
                          title
                          date
                          tags
                    }
                  }
                }
              }
            }
        `
    ).then(result => {
        if (result.errors) {
          console.log(result.errors)
          resolve()
          // reject(result.errors);
        }

        _.each(result.data.allMarkdownRemark.edges, ({ node }) => {
            createPage ({
                path: node.frontmatter.path,
                component: postTemplate,
            })
        })
        

        let tags = []
        _.each(result.data.allMarkdownRemark.edges, edge => {
        if (_.get(edge, "node.frontmatter.tags")) {
            tags = tags.concat(edge.node.frontmatter.tags)
        }
        })
        tags = _.uniq(tags)
        tags.forEach(tag => {
        const tagPath = `/tags/${_.kebabCase(tag)}/`
        createPage({
            path: tagPath,
            component: tagTemplate,
            context: {
            tag,
            },
        })
        })

        resolve ()
    })
    })
}

// Add Lodash plugin
exports.modifyWebpackConfig = ({ config, stage }) => {
    if (stage === `build-javascript`) {
      config.plugin(`Lodash`, webpackLodashPlugin, null)
    }
  
    return
  }`

## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue.

### Expected result

What should happen?

### Actual result

What happened.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by Chuloo** [comment]
Could you create a reproduction repo showing the error?

**Comment by sparklesam** [comment]
Turns out the reject value was not defined. Issue resolved. thanks a lot!
