### ISSUE TITLE
[gatsby-link] can't set activeClassName as its props

### ISSUE THREAD

**Issue by zheeeng** [gatsbyjs/gatsby#7455]
## Description

Describe the issue that you're seeing.

[gatsby-link] can't set activeClassName as its props

console report:
```
Warning: React does not recognize the `activeClassName` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `activeclassname` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

### Steps to reproduce

snippets:
```
<Link activeClassName="active" to="/hom1">Home1</Link>
<Link activeClassName="active" to="/hom2">Home3</Link>
<Link activeClassName="active" to="/hom3">Home3</Link>
```

Clear steps describing how to reproduce the issue.

### Expected result

What should happen?

link with 'active' class when is activated.

### Actual result

What happened.

No 'active' class on active link

### Environment

```
    "gatsby": "^1.9.277",
    "gatsby-link": "^1.6.46",
    "gatsby-plugin-react-helmet": "^2.0.11",
    "gatsby-plugin-react-next": "^1.0.11",
    "gatsby-plugin-react-svg": "^1.1.1",
    "gatsby-plugin-styled-components": "^2.0.11",
    "gatsby-plugin-typescript": "^1.4.20",
```
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by kylecesmat** [comment]
@zheeeng where are you importing `Link` from? I'd assume `import Link from 'gastby-link'`?

It may be worth digging into your `node_modules` and seeing what the result of `El` is at this line:
https://github.com/gatsbyjs/gatsby/blob/v1/packages/gatsby-link/src/index.js#L110

Assuming it is properly setting `El` to `NavLink` and passing the props accordingly, this issue would be caused by something within `react-router`.

**Comment by zheeeng** [comment]
@KyleAMathews I found that the current master branch switched the router to `@reach/router` but the document and its `.d.ts` files are about `react router`. I have to achieve the effect that `activeClassName` by manually test path matching
