### ISSUE TITLE
pulling contional data from csv file

### ISSUE THREAD

**Issue by WinterSoilder** [gatsbyjs/gatsby#7461]
Hi, 
My question is how to pull specific data from a csv file using gatsbyjs and graphql.
By specific i mean to say suppose i happen to have a data of a single car but there are variation to the car as 
Make : Hyndai
Model : I20 
Variants : Elite i20 Diesel Magna, Elite i20 Petrol Asta 
Suppose the variant changes by clicking a dropdown or button how can i pull out specific price and features of that variant model

My Stack : Graphql, gatsby, react and data from csv file.

**Comment by endymion1818** [comment]
Hi @WinterSoilder, if I'm right you want to split those 2 items in variants into 2 fields, then loop over them, is that correct?
