### ISSUE TITLE
[v2] How to use replaceRenderer to set {headComponents} in V2?

### ISSUE THREAD

**Issue by humphreybc** [gatsbyjs/gatsby#7464]
## Summary

We use [typestyle](https://github.com/typestyle/typestyle) to write type-safe CSS in React. We’ve been using Gatsby SSR API `replaceRenderer` function in combination with `html.js` to inject CSS into the <head> of the DOM. 

In Gatsby v2 the `html.js` file seems to be gone. My question is – what is the recommended way to use `replaceRenderer` and `{headComponents}` so we can inject the CSS from Typestyle?

## Relevant information

`plugins/gatsby-plugin-typestyle/gatsby-ssr.js`:

This is our small plugin to insert the CSS from Typestyle into `{headComponents}`.

```typescript
import React from "react";
import { getStyles } from "typestyle";
import { renderToString } from "react-dom/server";

export const replaceRenderer = ({ bodyComponent, replaceBodyHTMLString, setHeadComponents }) => {
  const body = renderToString(bodyComponent);

  replaceBodyHTMLString(body);
  setHeadComponents([React.createElement("style", { dangerouslySetInnerHTML: { __html: getStyles() } })]);

  return;
};
```

`src/html.tsx`:

This is our (now deleted) html.js file that inserted `{headComponents}` into the DOM.

```typescript
import React from "react";

// https://github.com/nfl/react-helmet/issues/79#issuecomment-299888528
// require("react-helmet/lib/HelmetConstants.js").HELMET_ATTRIBUTE = "data-react";

// Load production style
let styles: string;
if (process.env.NODE_ENV === "production") {
  try {
    styles = require("!raw-loader!../public/styles.css");
  } catch (err) {
    console.log(err);
  }
}

interface Props {
  body: string;
  headComponents: React.ReactNode;
  postBodyComponents: React.ReactNode;
}

export class Html extends React.PureComponent<Props> {
  public render() {
    const css =
      process.env.NODE_ENV === `production` ? (
        <style id="gatsby-inlined-css" dangerouslySetInnerHTML={{ __html: styles }} />
      ) : null;

    const { body, headComponents, postBodyComponents } = this.props;

    return (
      <html lang="en">
        <head>
          <meta charSet="utf-8" />
          {headComponents}
          {css}
        </head>
        <body>
          <div id="___gatsby" dangerouslySetInnerHTML={{ __html: body }} />
          {postBodyComponents}
        </body>
      </html>
    );
  }
}
```

**Comment by LeKoArts** [comment]
You can still use the html.js. Have a look in the .cache folder and copy it over.

**Comment by humphreybc** [comment]
@LeKoArts Could you please give me some more information? There's a lot of stuff in the .cache folder and I'm not exactly sure what I'm looking for. 

I did have a look at [the html.js for Gatsby's website](https://github.com/gatsbyjs/gatsby/blob/master/www/src/html.js) and updated my `html.tsx` file to more closely match theirs, so now it looks like this:

```typescript
import React from "react";

interface Props {
  body: string;
  headComponents: React.ReactNode;
  postBodyComponents: React.ReactNode;
}

export default class HTML extends React.PureComponent<Props> {
  public render() {
    const { body, headComponents, postBodyComponents } = this.props;

    return (
      <html lang="en">
        <head>
          <meta charSet="utf-8" />
          {headComponents}
        </head>
        <body>
          <div id="___gatsby" dangerouslySetInnerHTML={{ __html: body }} />
          {postBodyComponents}
        </body>
      </html>
    );
  }
}
```

However I still have the same problem as before – the Typestyle styles aren't being added to the DOM during the server build. They arrive later when the JavaScript loads. Here's a gif to demonstrate the FOUC caused by the Typestyle CSS missing in the SSR build:

![gatsbyv2](https://user-images.githubusercontent.com/1124253/44339317-3f755700-a4c4-11e8-92f4-b1a41ed17b69.gif)

**Comment by KyleAMathews** [comment]
You'll want to write a plugin similar to gatsby-plugin-emotion https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-emotion/src/gatsby-ssr.js

**Comment by humphreybc** [comment]
@KyleAMathews Correct me if I'm wrong, but isn't that effectively what we've already got? Here's what we have under `plugins/gatsby-plugin-typestyle/gatsby-ssr.js`, which was working fine in v1:

```javascript
import React from "react";
import { getStyles } from "typestyle";
import { renderToString } from "react-dom/server";

export const replaceRenderer = ({ bodyComponent, replaceBodyHTMLString, setHeadComponents }) => {
  const body = renderToString(bodyComponent);

  replaceBodyHTMLString(body);
  setHeadComponents([React.createElement("style", { dangerouslySetInnerHTML: { __html: getStyles() } })]);

  return;
};
```

**Comment by KyleAMathews** [comment]
Gatsby auto-inlines normal css processed by webpack. css-in-js libs need to inline the css themselves through plugins like this.

Perhaps check that your plugin code is getting called? Also check if there's a warning about their being multiple `replaceRenderer` implementations.

**Comment by humphreybc** [comment]
Okay, I'll have a look there. And just to confirm – `html.js` is not required at all any more?

**Comment by frantic1048** [comment]
Sorry for the disturb, yet another typestyle user here.

@humphreybc 
> Okay, I'll have a look there. And just to confirm – html.js is not required at all any more?

I'm using typestyle@2.0.4 and gatsby@2.13.39 now, and have made typestyle work properly with gatsby's SSR without touching `html.js`

2 steps:

1. Write typestyle CSS into generated page during static rendering:

```js
// gatsby-ssr.js

import * as React from 'react'
import { getStyles } from 'typestyle'
import { renderToString } from 'react-dom/server'

export const onPreRenderHTML = ({ getHeadComponents, replaceHeadComponents }, { styleTargetId = defaultStyleId }) => {
    replaceHeadComponents([
        ...getHeadComponents(),
        React.createElement('style', {
            key: '<id for typestyle target>',
            id: '<id for typestyle target>',
            dangerouslySetInnerHTML: { __html: getStyles() },
        }),
    ])
}
```

2. Call `typestyle.setStylesTarget` after client finishes first rendering:

```js
// gatsby-browser.js

import { setStylesTarget } from 'typestyle'

export const onInitialClientRender = (_, { styleTargetId = defaultStyleId }) => {
    let styleTarget = document.getElementById('<id for typestyle target>')
    if (!styleTarget) {
        // actually this should not happen if SSR works properly
        const newStyleEl = document.createElement('style')
        newStyleEl.setAttribute('id', '<id for typestyle target>')
        styleTarget = document.head.appendChild(newStyleEl)
    }
    setStylesTarget(styleTarget)
}
```
