### ISSUE TITLE
[gatsby-plugin-layout] Duplicate content

### ISSUE THREAD

**Issue by baukevanderlaan** [gatsbyjs/gatsby#7466]
## Description

When using the `gatsby-plugin-layout` and trying to follow the instructions from https://www.gatsbyjs.org/packages/gatsby-plugin-layout/ as close as possible, I get duplicate content. I feel like I'm missing something, but maybe it's a bug?

### Steps to reproduce

I made a [repo](https://github.com/baukevanderlaan/gatsby-layout-duplicate) based on the default starter in which I installed `gatsby-plugin-layout` and implemented a most basic version of it. I added `<ContextProviderComponent>` into the layout component and `<ContextConsumer>` into the header component.

### Expected result
No duplicate content.

### Actual result
It looks like the header component is rendered, but then also passed into the `{children}` of the layout component. This results in duplicate content and two versions of state; one global and one scoped to the page.

### Environment
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
    Shell: 5.4.1 - /usr/local/bin/zsh
  Binaries:
    Node: 8.11.3 - /usr/local/bin/node
    Yarn: 1.3.2 - /usr/local/bin/yarn
    npm: 6.3.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 61.0.1
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-beta.111 
    gatsby-plugin-layout: ^1.0.0-beta.1 => 1.0.0-beta.1 
    gatsby-plugin-manifest: next => 2.0.2-beta.6 
    gatsby-plugin-offline: next => 2.0.0-beta.9 
    gatsby-plugin-react-helmet: next => 3.0.0-beta.4 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

### File contents (if changed)

`gatsby-config.js`: 
```javascript
module.exports = {
  siteMetadata: {
    title: 'Gatsby Default Starter',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    {
      resolve: `gatsby-plugin-layout`,
      options: {
        component: require.resolve(`./src/components/layout`),
      },
    },
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: 'gatsby-starter-default',
        short_name: 'starter',
        start_url: '/',
        background_color: '#663399',
        theme_color: '#663399',
        display: 'minimal-ui',
        icon: 'src/images/gatsby-icon.png', // This path is relative to the root of the site.
      },
    },
    'gatsby-plugin-offline',
  ],
}
```

`package.json`:
```json
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "gatsby": "next",
    "gatsby-plugin-layout": "^1.0.0-beta.1",
    "gatsby-plugin-manifest": "next",
    "gatsby-plugin-offline": "next",
    "gatsby-plugin-react-helmet": "next",
    "react": "^16.4.2",
    "react-dom": "^16.4.2",
    "react-helmet": "^5.2.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write '**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "prettier": "^1.14.2"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  }
}
```

**Comment by Orozco1993** [comment]
Verify the issue, here's a photo of the issue.

<img width="723" alt="screen shot 2018-08-20 at 2 30 37 pm" src="https://user-images.githubusercontent.com/24233012/44362169-cc4cf000-a485-11e8-9dad-9c7c54b05a01.png">

**Comment by KyleAMathews** [comment]
Are you importing the layout component into your pages by chance?

**Comment by baukevanderlaan** [comment]
I did exactly that, and removing the layout component fixed it — thanks!

I'm not familiar with Gatsby v1 and looked for a way to have simple persistent state throughout page routes in v2. So I didn't start with a v1 structure. Is the `gatsby-plugin-layout` intended as more of a bridge/workaround to ensure compatibility between v1 and v2 or is it intended as the recommended way forward in v2 to build (for example) persistent navigation?

**Comment by cpboyd** [comment]
@KyleAMathews Likely related to #7568 as `gatsby-plugin-layout` applies its `wrap-page` in both **browser** and **ssr** APIs.

**Comment by KyleAMathews** [comment]
it's for certain cases where you want persistent global components https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-layout/README.md#why-would-you-want-to-reimplement-the-v1-layout-behavior
