### ISSUE TITLE
[www] Remove duplicate links on docs sidebar

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#7471]
Opening https://next.gatsbyjs.org/docs/adding-search/ currently results in two sidebar items being shown in their "active" state.

![image](https://user-images.githubusercontent.com/21834/44354466-32e40500-a4aa-11e8-8f0c-48bc5bff141c.png)

This happens because both of these items point to the same URL (`/docs/adding-search/`) -- we currently look at the URL/`location.pathname` and compare that to the `href` of the sidebar item link to determine wether an item should be displayed as "active" or not.

I don't see any way around this other than to (either manually in `yaml`, or by convention, e.g. the first occurence of the URL) define one of the multiple links pointing to the same URL as the "primary" one which should become "active"…

/cc @shannonbux @calcsam @KyleAMathews

**Comment by calcsam** [comment]
We shouldn't have duplicate links on the sidebar, that will make this problem go away :)

**Comment by shannonbux** [comment]
I fixed this, can't remember which PR though!

**Comment by fk** [comment]
😄 I also saw this today and wanted to take another quick look just now!
Nice! Thanks Shannon! 🙌
