### ISSUE TITLE
[www] header hidden behind top nav when clicking on links in ToC

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#7475]
### Steps to reproduce behavior
1. Go to this doc: https://next.gatsbyjs.org/docs/deploy-gatsby/
2. Click on any of the ToC links, like "Heroku"

### Expected behavior
1. Page jumps to show Heroku at top of page

### Actual behavior
1. Page jumps and the header "Heroku" is hidden behind the top nav bar

**Comment by kkemple** [comment]
@shannonbux I forgot to tag you in comment above! sorry! :smile:
