### ISSUE TITLE
[www] line that is dotted at either end sometimes appears within guides categories

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#7476]
I'm having a hard time recreating this, but sometimes when I open a guides category in the docs, there is a solid purple vertical line that is dotted at the top and bottom that appears alongside the children items of the docs

<img width="294" alt="screen shot 2018-08-20 at 11 34 39 am" src="https://user-images.githubusercontent.com/32467162/44359559-14abe400-a46d-11e8-91fb-e20d05ef45e2.png">

**Comment by kkemple** [comment]
this also seems resolved, @shannonbux can you try to recreate?

**Comment by shannonbux** [comment]
Can't seem to recreate! Yay!

**Comment by shannonbux** [comment]
Closing because can't recreate issue! Thanks @kkemple !
