### ISSUE TITLE
window is not defined followed only tutorial

### ISSUE THREAD

**Issue by spaceoi** [gatsbyjs/gatsby#748]
Are the tutorial demos deployable or not?

I did nothing but follow the tutorial several times but still got "Error: ReferenceError: window is not defined" message.

Thanks!

**Comment by KyleAMathews** [comment]
Which starter is causing trouble? Yes they should be deployable so if
you're seeing this it's a bug. Did you make any modifications to the
starter e.g. add additional components?

**Comment by spaceoi** [comment]
No I haven't made any modification. I have tried the document starter and the default starter.

**Comment by spaceoi** [comment]
Instead of using gatsby CLI, git clone each demo repository directly and then npm install the required packages fixed my problem. My guessing is gatsby CLI ignores several node module package installation errors.
