### ISSUE TITLE
[blog] Add Gatsby version to frontmatter to identify potentially out-of-date posts

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#7482]
In order to avoid confusion, we should create a way to signify that blog posts about older versions of Gatsby may be out of date. Ideally, there will also be an option to link to the updated post.

So maybe something like this:

```yml
title: My post about Gatsby V1
version: 1.9.*
updated_post: /blog/my-post-about-gatsby-v2
```

Version should be the earliest version of Gatsby that supports the features in the post. (This will matter far more in the future when we start doing a better job of following `semver` conventions.)

If `version` is set, we can check it something like this:
```js
const isCurrent = semver.satisfies(post.frontmatter.version, `>= ${semver.major(GATSBY_CURRENT_VERSION)}`);
```

Any posts _without_ a `version` tag could be assumed as Gatsby v1, so once V2 launches they'd all get the notice.

@calcsam @lindaleebumblebee @shannonbux we can identify high-value posts (e.g. the Gatsbygram implementation) and slot them into the content pipeline for V2-compatible updates, and add the `version` and `updated_post` frontmatter to the original posts as part of the new post’s PR.

**Comment by shannonbux** [comment]
We had a similar idea a while back and de-prioritized it, though I can't remember why!

My thoughts are that if a blogpost is that high value, why not just turn it into a doc or tutorial that we officially maintain?
