### ISSUE TITLE
If the site has a service worker installed, fetch the files into the sw cache

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#7493]
Currently we call prefetch into the browser context which means each prefetch incurs a CPU/memory cost. If we instead just prefetch into the sw, then the browser will just download the file but do nothing until the file is actually needed aka when the user visits the page.

This would be much cheaper for browsers + help avoid jank caused by the UI thread stalling while evaluating files.

We'd probably need to set the cache name in gatsby-plugin-offline and then open the cache and fetch the files like the sample code here: https://developers.google.com/web/ilt/pwa/caching-files-with-service-worker

**Comment by Mortuie** [comment]
Is this a good first issue ?

**Comment by KyleAMathews** [comment]
If you have experience with service workers than yes! Otherwise, it'd probably be fairly tough but feel free to give it a go if you'd like! Happy to answer questions you might have.

**Comment by Seenivasanseeni** [comment]
I can work on this. But pre-fetching every file that is not quite reasonable. Caching Files that are visited is easy. If you want to pre-fetch, we need all the URLs or at least important ones.
