### ISSUE TITLE
[docs] Further clarify how global styles work

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#7499]
Global styles work in different ways depending on the use case, so we want to capture this in more detail.

1. If every page is wrapped with the same layout component, importing a CSS file or including CSS-in-JS global styles works just fine
2. If every page is _not_ wrapped with the same layout component, you can:
    - with regular CSS, include the stylesheet in `gatsby-browser.js`
    - with CSS-in-JS, every page component needs to include the global styles (or a component that does so)

**Comment by twxia** [comment]
BTW, if apply global CSS in `gatsby-browser.js`. The CSS will apply the style after the DOM render so it'll cause some glitch.

**Comment by jlengstorf** [comment]
@twxia have you seen this with regular CSS stylesheets? We know that's the case with CSS-in-JS, but in my (admittedly limited) testing there was no flash of unstyled content using `.css` files.

**Comment by jlengstorf** [comment]
@twxia Yep! That's the Gatsby Official™ way of handling CSS-in-JS now. Once https://github.com/gatsbyjs/gatsby/pull/7503 is merged that will be in the docs as well.
