### ISSUE TITLE
Add support for command-line plugin in PrismJS plugin

### ISSUE THREAD

**Issue by gzzo** [gatsbyjs/gatsby#7500]
## Summary

Add support for command-line plugin in PrismJS plugin

### Motivation

The [command-line](https://prismjs.com/plugins/command-line/) plugin seems extremely useful, it would be great if gatsby supported this since it already does a lot of custom work for line numbers.

**Comment by lookoutwehave** [comment]
Do we have this feature yet? Can't seem to figure out how to implement it.
