### ISSUE TITLE
Move images to netlify

### ISSUE THREAD

**Issue by fauziabd** [gatsbyjs/gatsby#7504]
when using services like contentful or graphcms, images on the content will load from their cdn.
how can i move it to netlify or s3?

**Comment by Chuloo** [comment]
Netlify from my understanding supports mostly static HTML pages, however, you could look to services which offer CDN for Images such as Cloudinary or S3, [here's a guide on how to getting started](https://docs.aws.amazon.com/AmazonS3/latest/gsg/GetStartedWithS3.html) with S3. Visit Cloudinary.com to get started with deploying images on a CDN using Cloudinary.
