### ISSUE TITLE
[gatsby-source-contentful] Image requests return wrong aspect ratio.

### ISSUE THREAD

**Issue by supermoos** [gatsbyjs/gatsby#7511]
## Description

It looks like the Contentful images generated using either sizes, resize or responsive all construct bad contentful image api urls, and also doesn't look at the actual returned image to calculate things like aspectRatio.

### Steps to reproduce
Sample query and result:
```
query Test {
  contentfulModuleImageGallery {
    images {
      image {
        default: sizes(maxHeight: 650, resizingBehavior: NO_CHANGE) {
          aspectRatio
          src
        }
        error: sizes(maxHeight: 650, maxWidth: 0, resizingBehavior: NO_CHANGE) {
          aspectRatio
          src
        }
        highParam: sizes(maxHeight: 650, maxWidth: 4000, resizingBehavior: NO_CHANGE) {
          aspectRatio
          src
        }
        resize(width: null, height: 650, resizingBehavior: NO_CHANGE) {
          aspectRatio
          src
        }
      }
    }
  }
}

```
result:

```
{
  "data": {
    "contentfulModuleImageGallery": {
      "images": [
        {
          "image": {
            "default": {
              "aspectRatio": 1.2307692307692308,
              "src": "//images.ctfassets.net/REDACTED?w=800&h=650&q=50"
            },
            "error": {
              "aspectRatio": 0,
              "src": "//images.ctfassets.net/REDACTED?h=650&q=50"
            },
            "highParam": {
              "aspectRatio": 6.153846153846154,
              "src": "//images.ctfassets.net/REDACTED?w=4000&h=650&q=50"
            },
            "resize": {
              "aspectRatio": 0.6594464500601684,
              "src": "//images.ctfassets.net/REDACTED?h=650&fl=progressive&q=50&fit=fill"
            }
          }
        }
      ]
    }
  }
}
```

### Expected result

The aspect ratio should be calculated on the return image, the problem especially arises when providing only a height value, and no `&fit` query param. In this case contentful will return an image where the ratio can only be calculated by looking at the actual image-data returned from contentful. 

also, the `resize` incorrectly adds the `&fit` query param even with `resizingBehavior: NO_CHANGE`

> "By default, images are resized to fit inside the bounding box given by w and h while retaining their aspect ratio. Using the fit parameter, you can change this behavior."  - https://www.contentful.com/developers/docs/references/images-api/#/reference/resizing-&-cropping

### Actual result

The aspect ratio seems to be calculated based on the GraphQL query params: `maxHeight` and `maxWidth` values.

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.3 - /usr/local/bin/node
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Firefox: 60.0.1
    Safari: 11.1.2
  npmPackages:
    gatsby: ^1.9.277 => 1.9.277
    gatsby-image: ^1.0.55 => 1.0.55
    gatsby-link: latest => 1.6.46
    gatsby-module-loader: latest => 1.0.11
    gatsby-plugin-google-analytics: latest => 1.0.31
    gatsby-plugin-i18n: ^0.4.1 => 0.4.1
    gatsby-plugin-offline: latest => 1.0.18
    gatsby-plugin-page-transitions: ^1.0.7 => 1.0.7
    gatsby-plugin-react-helmet: ^1.0.5 => 1.0.8
    gatsby-plugin-react-next: ^1.0.11 => 1.0.11
    gatsby-plugin-sass: ^1.0.26 => 1.0.26
    gatsby-plugin-sharp: ^2.0.0-beta.9 => 2.0.0-beta.9
    gatsby-plugin-sitemap: ^1.2.25 => 1.2.25
    gatsby-plugin-typescript: ^1.4.20 => 1.4.20
    gatsby-plugin-webpack-bundle-analyzer: ^0.1.1 => 0.1.1
    gatsby-source-contentful: ^1.3.54 => 1.3.54
    gatsby-transformer-remark: latest => 1.7.44
    gatsby-transformer-sharp: ^1.6.27 => 1.6.27
  npmGlobalPackages:
    gatsby-cli: 1.1.58

### File contents (if changed)

`gatsby-config.js`: 

```
const languages = require('./src/data/languages');

module.exports = {
	siteMetadata: {
		title: `Gatsby with Contentful`,
		languages,
		siteUrl: `https://qf-dev.netlify.com`
	},
	plugins: [
		`gatsby-plugin-react-helmet`,
		{
			resolve: 'gatsby-plugin-i18n',
			options: {
				langKeyForNull: languages.defaultLangKey,
				langKeyDefault: languages.defaultLangKey,
				useLangKeyLayout: false
			}
		},
		{
			resolve: `gatsby-source-contentful`,
			options: {
				spaceId: `vvqajlpkgasv`,
				accessToken: `bcbb2221ca3fd7e30d0e14a5cc896c9a1fa95dcd456b9476a37da25b68f5dc9d`,
			},
		},
		{
			resolve: `gatsby-plugin-sass`,
			options: {
				// includePaths: ["./src/styles"],
				data: `@import "./src/styles/variables";@import "./src/styles/mixins";`
			},
		},
		`gatsby-transformer-remark`,
		`gatsby-transformer-sharp`,
		`gatsby-plugin-sharp`,
		`gatsby-plugin-typescript`,
		`gatsby-plugin-sitemap`,
		'gatsby-plugin-page-transitions'/*,
		{
			resolve: 'gatsby-plugin-webpack-bundle-analyzer',
			options: {
				analyzerPort: 3000,
				production: true,
			},
		}*/
	],
};
```

`package.json`: 

```
{
	"name": "gatsby-starter-contentful-i18n",
	"private": true,
	"description": "Gatsby example site using the Contentful source plugin and i18n",
	"version": "1.0.0",
	"author": "Paul McCrodden <paul.mccrodden@x-team.com> (paulmccrodden.com)",
	"dependencies": {
		"@types/gsap": "^1.19.2",
		"@types/react": "^16.4.9",
		"@types/react-helmet": "^5.0.7",
		"@types/react-intl": "^2.3.9",
		"concurrently": "^3.6.1",
		"gatsby": "^1.9.277",
		"gatsby-image": "^1.0.55",
		"gatsby-link": "latest",
		"gatsby-module-loader": "latest",
		"gatsby-plugin-google-analytics": "latest",
		"gatsby-plugin-i18n": "^0.4.1",
		"gatsby-plugin-offline": "latest",
		"gatsby-plugin-page-transitions": "^1.0.7",
		"gatsby-plugin-react-helmet": "^1.0.5",
		"gatsby-plugin-react-next": "^1.0.11",
		"gatsby-plugin-sass": "^1.0.26",
		"gatsby-plugin-sharp": "^2.0.0-beta.9",
		"gatsby-plugin-sitemap": "^1.2.25",
		"gatsby-plugin-typescript": "^1.4.20",
		"gatsby-plugin-webpack-bundle-analyzer": "^0.1.1",
		"gatsby-source-contentful": "^1.3.54",
		"gatsby-transformer-remark": "latest",
		"gatsby-transformer-sharp": "^1.6.27",
		"gsap": "^2.0.1",
		"intl": "^1.2.5",
		"lodash": "^4.16.4",
		"react-intl": "^2.4.0",
		"slash": "^1.0.0",
		"typescript": "^3.0.1"
	},
	"keywords": [
		"gatsby"
	],
	"license": "MIT",
	"main": "n/a",
	"husky": {
		"hooks": {
			"pre-commit": "pretty-quick --staged"
		}
	},
	"scripts": {
		"precommit": "pretty-quick --staged",
		"develop": "gatsby develop",
		"build": "gatsby build",
		"start": "gatsby serve",
		"clear": "rm -rf .cache/",
		"develop-watch": "npm run clear && npm run develop",
		"apollo": "apollo schema:download --endpoint http://localhost:8000/___graphql? gatsby-schema.json && apollo codegen:generate --tagName=graphql --queries='./{graphql,src}/**/*.tsx' --schema=./gatsby-schema.json src/gatsby-queries.d.ts --outputFlat",
		"apollo-watch": "apollo schema:download --endpoint http://localhost:8000/___graphql? gatsby-schema.json && apollo codegen:generate --tagName=graphql --queries='./{graphql,src}/**/*.tsx' --schema=./gatsby-schema.json src/gatsby-queries.d.ts --outputFlat --watch"
	},
	"browserslist": [
		"> 1%",
		"IE >= 11",
		"last 2 versions"
	],
	"devDependencies": {
		"graphql-code-generator": "^0.10.7",
		"graphql-codegen-typescript-template": "^0.10.7",
		"husky": "^0.14.3",
		"prettier": "^1.14.2",
		"pretty-quick": "^1.6.0",
		"sass-resources-loader": "^1.3.3",
		"url-loader": "^1.0.1"
	}
}

```

**Comment by Chuloo** [comment]
Could you create a minimal reproduction showing your error with say a demo contentful account?

**Comment by supermoos** [comment]
I can try when I get time. But even from simply looking at the responses for resize you can see that it incorrectly appends the &fit query to the url.

**Comment by supermoos** [comment]
I'm not sure how to setup a reproduction for you? But if you simply clone this repo: https://github.com/contentful-userland/gatsby-contentful-starter - and follow the setup instructions you'll easily see that the aspect ratio is calculated based on the `maxWidth` and `maxheight` instead of the actual image response from contentful.

See: https://github.com/contentful-userland/gatsby-contentful-starter/blob/master/src/pages/index.js#L68 - lines 68-69
Aspect ratio for 1180/480 =  2.4583333333

Now the actual response from contentful is here: http://images.ctfassets.net/k4u38sf2htzh/7orLdboQQowIUs22KAW4U/9b7f1bbacdf7f3af8551141caeb6f9c9/matt-palmer-254999.jpg?w=1180&h=480&q=50&fit=pad&bg=rgb%3A000000

You can see that the image here is: 1105x449 meaning an aspect ratio of:
1105/449 = 2.4610244989

The GraphQL response for the aspect ratio can be seen in this screenshot, but basically it matches the pre calculated aspect ratio and not the actual responses aspect ratio.

![screen shot 2018-08-23 at 14 54 55](https://user-images.githubusercontent.com/2298345/44526573-b5f09f80-a6e4-11e8-8f2b-1cfd3b6b9637.png)

**Comment by supermoos** [comment]
@Chuloo Do you need more information from me on this? Understand if you haven't had time to look into it, just wondering if all the information needed is there? :-)
