### ISSUE TITLE
The plugin "gatsby-plugin-styled-components@3.0.0-rc.0" is exporting a variable named "wrapRootElement" which isn't an API.

### ISSUE THREAD

**Issue by lipis** [gatsbyjs/gatsby#7514]
I'm getting this error when updating to the latest `gatsby-plugin-styled-components`.

**Comment by Chuloo** [comment]
What version of Gatsby are you running?

**Comment by lipis** [comment]
2.0.0-beta.100 to 2.0.0-rc.0

**Comment by lipis** [comment]
Updated the title to `3.0.0-rc.0`, everything was fine with `3.0.0-beta.3`.

**Comment by lipis** [comment]
Adding `"core-js": "2.5.7"` explicitly solved the issue.. :/

**Comment by zilindeng** [comment]
I'm still getting the same error

**Comment by KyleAMathews** [comment]
You need to upgrade the version of gatsby to the latest. We released an RC last night so upgrade to that.

**Comment by zilindeng** [comment]
Thanks! @KyleAMathews
