### ISSUE TITLE
[plugin-jsx] Add support for styled-jsx CSS file loader

### ISSUE THREAD

**Issue by seaneking** [gatsbyjs/gatsby#7516]
## Summary

Styled-jsx v3 comes with an optional CSS file loader baked in that allows users to import CSS files into components like so:

```js
import css from './styles.css';

<style jsx>{css}</style>
```

### Basic example

Best way to support this would be to add a config option to the plugin, along the lines of `CSSLoader: true`.

### Motivation

This would allow users to separate out styles into CSS files while using styled-jsx for both smaller components and whole pages, removing the need for something like CSS Modules to structure large amounts of CSS cleanly.

**Comment by KyleAMathews** [comment]
How would this interact with Gatsby's existing css importing?

**Comment by seaneking** [comment]
At first look probably not very well, since it requires the CSS that it transforms to be passed to Babel (docs [here](https://github.com/zeit/styled-jsx#styles-in-regular-css-files)), which would make it a destructive/all-or-nothing option.

So might be best to use a suffixed filename like we do with CSS Modules, something like `[filename].jsx.css`?

**Comment by seaneking** [comment]
@KyleAMathews would you take a PR for the latter option, adding support to `gatsby-plugin-styled-jsx` for loading `*.jsx.css` files?
