### ISSUE TITLE
Allow local plugins to reside outside of the app's directory

### ISSUE THREAD

**Issue by JanLenoch** [gatsbyjs/gatsby#7518]
## Summary

Please allow local plugins to reside outside of the app's directory.

### Basic example

Plugin developers would maybe appreciate to have both the sample app and the plugin side-by-side. Like so:

* repository root directory
    * sample-app
    * plugins

### Motivation

Currently, source code files of local plugins [can only be placed](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/bootstrap/load-plugins/load.js) under the app's directory, in the `plugins` directory. For plugin developers, it is often desired to also have an accompanying sample app that demonstrates the use of the plugin. It is best if the app resides in the same repository as the plugin itself. That way, the changes of the code of the plugin can also be immediately seen in the sample app. But, the hard-coded `plugins` search path, under the app's directory, might cause problems as the plugin is dependent on the app.

**Comment by pieh** [comment]
Would using `require.resolve('../plugins/name-of-the-plugin')` work in gatsby-config without making changes to gatsby?

**Comment by oorestisime** [comment]
I ve tested this with a gatsby website
```
      {
-      resolve: 'gatsby-source-instagram',
+      resolve: require.resolve('./plugins/gatsby-source-instagram'),
       options: {
         username: config.instagram,
       }
```
and worked. Should i close the PR?

**Comment by DSchau** [comment]
@oorestisime would you be able to try with plugins/ directory _up_ one directory from your app?

**Comment by oorestisime** [comment]
ah lol i see! Indeed it fails
```
Error: Cannot find module 'gatsby-source-filesystem'
  
  - loader.js:571 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:571:15

**Comment by oorestisime** [comment]
But the same problem happens with my PR as well. if i configure pluginsFolder to be ../plugins then it breaks

**Comment by pieh** [comment]
is `gatsby-source-filesystem` installed in `../plugins/gatsby-source-instagram` dir (as in - does it have its own `node_modules`)?

**Comment by oorestisime** [comment]
nan i haven't added it as a dependency so not in node_modules

**Comment by DSchau** [comment]
@oorestisime so that would be the first thing! Add the necessary dependencies for `gatsby-source-instagram` (i.e. just run `npm install` in that directory, or ensure it has necessary deps!).

**Comment by pieh** [comment]
All right, given that `require.resolve` approach works I would vote for documenting that instead of adding custom plugin directory feature, so we don't add feature that is rarely used and therefore hard to notice when it breaks in the future

**Comment by oorestisime** [comment]
I am closing this issue since the PR for the docs was merged (and forgot to close it automatically)
