### ISSUE TITLE
[1.0] ensure graphql schema names of sub-objects are unique

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#752]
A client building a site had a problem where there was a sub-object in multiple data types with the same name which GraphQL doesn't allow. We need to do something to ensure this doesn't happen. The easiest way might be to just prefix sub-objects with the parent type.

**Comment by 0x80** [comment]
@KyleAMathews I'm thinking this one is solved with the introduction of the createTypeName function?

**Comment by KyleAMathews** [comment]
Yup!
