### ISSUE TITLE
Contentful referenced lists with multiple types

### ISSUE THREAD

**Issue by pixelbreaker** [gatsbyjs/gatsby#7522]
I'm using contentful's `References, Many` to allow editors to choose from a few different page components, so the list of components cannot be strictly typed to only one type.

In contentful it looks like so 
![](https://dl.dropbox.com/s/llprlygexkyapdt/Screenshot%202018-08-21%2018.49.38.png?dl=0)

In GraphiQL, when I dig around I can find that the `components` list is a typed array of `ContentfulPageTextColumns` which is only one of the types I need support for.

![](https://dl.dropbox.com/s/e9ixt36lzwpjjmk/Screenshot%202018-08-21%2018.51.26.png?dl=0)

Any pointers on this would be greatly appreciated.

Oh and hi @m-allanson 😉

**Comment by pixelbreaker** [comment]
Ignore this, fixed by deleting the local cache and rerunning `gatsby develop` and structuring the queries like so

```
contentfulPage(slug: { eq: "home" }) {
    slug
    title
    components {
      ... on ContentfulPageTextColumns {
        column1 {
          column1
        },
        column2 {
          column2
        }
      }
      ... on ContentfulPageVideo {
        youtubeId
      }
    }
  }
```

**Comment by m-allanson** [comment]
Hey @pixelbreaker 😄 👋
