### ISSUE TITLE
Does Link has 'exact' as a prop?

### ISSUE THREAD

**Issue by lxieyang** [gatsbyjs/gatsby#7526]
I wonder the following words on the readme page from npmjs.org is still true:
> Gatsby also supports React Router's props exact, strict, isActive, and location. If any of these props are set, then React Router's NavLink component will be used instead of the default Link.

A bit of a background, what I'd like to do is to build a navbar. Let's say I have:
"/", "/about", "/blogs"
as 3 pages in the app. And if I hit "localhost:8000/blogs", the "/blogs" Links is assigned an "active" attribute. However, if I navigate to a single blog post like "localhost:8000/blogs/what-is-going-on/", then the "/blogs" Link is not "active", which is not an ideal situation.

**Comment by robinpyon** [comment]
V2 is now using reach-router and as such, `<Link>` no longer has an `exact` prop.

However you should be able to accomplish what you're after by using reach-router's `getProps` prop. 

From reach-router's [documentation](https://reach.tech/router/api/Link):

```js
// this link will be active when itself or deeper routes
// are current
const isPartiallyActive = ({
  isPartiallyCurrent
}) => {
  return isPartiallyCurrent
    ? { className: "active" }
    : null
}

const PartialNavLink = props => (
  <Link getProps={isPartiallyActive} {...props} />
)
```

Also relevant: https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#the-following-props-are-no-longer-available-on-link

**Comment by lxieyang** [comment]
Thank you!!
