### ISSUE TITLE
Browser locks up

### ISSUE THREAD

**Issue by dwehrmann** [gatsbyjs/gatsby#7531]
## Description

After launching gatsby develop and opening the site at localhost:8000, the browser freezes. Console shows a lot of errors quickly piling up. Apologies if the information is not complete, all I can snap is a screenshot before everything locks up completely.

1k Errors: TypeError: undefined is not a function (near ...pendingUnsafeLifecycleWarnings.forEach ...') commons.js:500x  (the last number is cut off in the screenshot)

TypeError: undefined is not an object (evaluating 'this.image.onerror = null')   commons.js:398x

### Steps to reproduce

Started out with the gatsby-strapi template and was trying to build it the final site. react-mapbox-gl broke things (window not defined etc., so I tried some of the solutions here on github. Apparently, that was when things broke. I can't nail it down further but I tried to revert all my changes with no success so I'm thinking it might have to do with the installed node_modules.

### Expected result

dev mode should launch in the browser

### Actual result

browser freezes

### Environment

  System:
    OS: macOS High Sierra 10.13.5
    CPU: x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.4 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 61.0.1
    Safari: 11.1.1
  npmPackages:
    gatsby: ^1.9.277 => 1.9.277
    gatsby-image: ^1.0.55 => 1.0.55
    gatsby-link: ^1.6.46 => 1.6.46
    gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11
    gatsby-plugin-react-leaflet: ^1.0.7 => 1.0.7
    gatsby-plugin-react-next: ^1.0.11 => 1.0.11
    gatsby-plugin-sharp: ^1.6.48 => 1.6.48
    gatsby-source-filesystem: ^1.5.39 => 1.5.39
    gatsby-source-strapi: 0.0.3 => 0.0.3
    gatsby-transformer-sharp: ^1.6.27 => 1.6.27
  npmGlobalPackages:
    gatsby-cli: 1.1.58

### File contents (if changed)

`gatsby-config.js`: 

`module.exports = {

  plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-transformer-sharp',
    'gatsby-plugin-sharp',
    'gatsby-plugin-react-next',
    'gatsby-plugin-react-leaflet',
    {
      resolve: 'gatsby-source-strapi',
      options: {
        apiURL: 'http://192.168.1.33:1337',
        contentTypes: [ // List of the Content Types you want to be able to request from Gatsby.
          'Arbeitsgebiete',
          'Referenz',
          'Leistungen',
          'Stellenangebote',
          'Sitemeta',
          'user'
        ]
      },
    },
  ],
}`

`package.json`:

`{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "child_process": "^1.0.2",
    "file-loader": "^1.1.11",
    "fs": "0.0.1-security",
    "gatsby": "^1.9.277",
    "gatsby-image": "^1.0.55",
    "gatsby-link": "^1.6.46",
    "gatsby-plugin-react-helmet": "^2.0.11",
    "gatsby-plugin-react-leaflet": "^1.0.7",
    "gatsby-plugin-react-next": "^1.0.11",
    "gatsby-plugin-sharp": "^1.6.48",
    "gatsby-source-filesystem": "^1.5.39",
    "gatsby-source-strapi": "0.0.3",
    "gatsby-transformer-sharp": "^1.6.27",
    "html-to-react": "^1.3.3",
    "imagesloaded": "^4.1.4",
    "isotope-cells-by-row": "^1.1.4",
    "isotope-layout": "^3.0.6",
    "isotope-masonry-horizontal": "^2.0.1",
    "isotope-packery": "^2.0.1",
    "jquery": "^3.3.1",
    "jsdom": "^11.12.0",
    "leaflet": "^1.3.3",
    "location": "0.0.1",
    "mapbox-gl": "^0.48.0",
    "masonry-layout": "^4.2.2",
    "navigator": "^1.0.1",
    "net": "^1.0.2",
    "react": "^16.4.2",
    "react-accessible-accordion": "^2.4.4",
    "react-background-image-loader": "0.0.5",
    "react-dimensions": "^1.3.1",
    "react-dom": "^16.4.2",
    "react-helmet": "^5.2.0",
    "react-icons": "^3.0.5",
    "react-leaflet": "^2.0.1",
    "react-map-gl": "^3.3.4",
    "react-mapbox-gl": "^3.8.0",
    "react-responsive-carousel": "^3.1.41",
    "react-router-dom": "^4.3.1",
    "react-slick": "^0.23.1",
    "slick-carousel": "^1.8.1",
    "tls": "0.0.1",
    "url-loader": "^1.1.0",
    "xmlhttprequest": "^1.8.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write 'src/**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "emit-file-loader": "0.0.2",
    "prettier": "^1.13.7"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  }
}
`

`gatsby-node.js`: 

`const path = require(`path`);

function slugify(text) {
    const a = 'àáäâèéëêìíïîòóöôùúüûñçßÿœæŕśńṕẃǵǹḿǘẍźḧ·/_,:;'
    const b = 'aaaaeeeeiiiioooouuuuncsyoarsnpwgnmuxzh------'
    const p = new RegExp(a.split('').join('|'), 'g')

    return text.toString().toLowerCase()
        .replace(/\s+/g, '-')           // Replace spaces with -
        .replace(p, c =>
            b.charAt(a.indexOf(c)))     // Replace special chars
        .replace(/&/g, '-and-')         // Replace & with 'and'
        .replace(/[^\w\-]+/g, '')       // Remove all non-word chars
        .replace(/\-\-+/g, '-')         // Replace multiple - with single -
        .replace(/^-+/, '')             // Trim - from start of text
        .replace(/-+$/, '')             // Trim - from end of text
};

const makeRequest = (graphql, request) =>
    new Promise((resolve, reject) => {
        // Query for nodes to use in creating pages.
        resolve(
            graphql(request).then(result => {
                if (result.errors) {
                    reject(result.errors);
                }

                return result;
            })
        );
    });

// Implement the Gatsby API “createPages”. This is called once the
// data layer is bootstrapped to let plugins create pages from data.
exports.createPages = ({ boundActionCreators, graphql }) => {
    const { createPage } = boundActionCreators;

    const getPage = makeRequest(
        graphql,
        `
    {
      allStrapiReferenz {
        edges {
          node {
            id
            Headline
            Ref_Category
          }
        }
      },
      allStrapiArbeitsgebiete{
          edges{
              node{
                id
                Arbeitsgebiet_Titel
              }
          }
      }
    }
    `
    ).then(result => {
        // Create pages for each article.

        result.data.allStrapiReferenz.edges.forEach(({ node }) => {
            createPage({
                path: `/referenz/${slugify(node.Ref_Category)}/${slugify(node.Headline)}`,
                component: path.resolve(`src/templates/referenz.js`),
                context: {
                    id: node.id,
                },
            });
        });
        result.data.allStrapiArbeitsgebiete.edges.forEach(({ node }) => {
            createPage({
                path: `/arbeitsgebiete/${slugify(node.Arbeitsgebiet_Titel)}`,
                component: path.resolve(`src/templates/arbeitsgebiete.js`),
                context: {
                    id: node.id,
                },
            });
        });

    });

    // Query for articles nodes to use in creating pages.
    return getPage;
};`

<img width="1253" alt="bildschirmfoto 2018-08-22 um 05 06 38" src="https://user-images.githubusercontent.com/1969892/44441014-e47a5780-a5ca-11e8-87cb-079517c3af94.png">

`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by dwehrmann** [comment]
Actually, does anybody know where the error "pendingUnsafeLifecycleWarnings..." comes from? As the console states, it seems to be related to infinite loops which would explain why the browser window freezes.

**Comment by Chuloo** [comment]
hi @dwehrmann please can you create a reproduction repo showing this error?

**Comment by dwehrmann** [comment]
Hi @Chuloo  thanks for you reply. I will try to create a simplified version as this project is intended for a client but I reverted to an earlier stage and things are running smoothly again so I'll close this issue.
