### ISSUE TITLE
[1.0] gatsby-plugin-offline doesn't handle sites with prefixed links correctly

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#754]

**Comment by fxcosta** [comment]
News for this issue?

**Comment by lilac** [comment]
I encountered this issue, and wanted to create an issue. Glad to see it was already here.
My current workaround is adding an option `replacePrefix` to the plugin. Therefore, I guess the fix is easy enough. Maybe we could just add a key value pair to the default option of plugin offline.

**Comment by KyleAMathews** [comment]
Fixed I believe
