### ISSUE TITLE
gatsby-transformer-react-docgen - Error: Schema must contain unique named types but contains multiple types named "JSON".

### ISSUE THREAD

**Issue by jonearley** [gatsbyjs/gatsby#7543]
## Description

Installed the `gatsby-transformer-react-docgen` plugin, but get this error message:

```sh
$ gatsby develop
success open and validate gatsby-config — 0.010 s
success load plugins — 0.238 s
success onPreInit — 0.783 s
success delete html and css files from previous builds — 0.017 s
success initialize cache — 0.017 s
success copy gatsby files — 0.069 s
success onPreBootstrap — 0.004 s
success source and transform nodes — 0.179 s
error UNHANDLED REJECTION


  Error: Schema must contain unique named types but contains multiple types named "JSON".

  - Array.forEach

  - Array.forEach

  - Array.forEach

  - Array.forEach

  - Array.forEach

  - Array.forEach
```

If I remove the filesystem path to my components this error goes away, but the point is to read the components.

What could I be missing?

The repo to reproduce: https://github.com/mlibrary/umich-lib-components-react/tree/7a9e43c7900c74e5f9d881d3bfd044a4d8225be5

**Comment by jonearley** [comment]
Still having this issue. Added a link to the repo to reproduce. @Chuloo

**Comment by KyleAMathews** [comment]
To fix this, we'd need to PR a fix to how the docgen transformer creates node type names. Anyone interested in doing this? I can give some pointers

**Comment by jonearley** [comment]
@KyleAMathews I could take a look. Where should I start?

https://github.com/gatsbyjs/gatsby/blob/445f5ff7508ab613967e18b32490e3feffd7730c/packages/gatsby-transformer-react-docgen/src/on-node-create.js#L106

**Comment by jonearley** [comment]
@KyleAMathews Still have this issue since August. A few others have 👍'd it. Could this be investigated?

**Comment by jonearley** [comment]
Still experiencing this issue with the latest package versions. I try every month or so to see if this works.

**Comment by ferittuncer** [comment]
No resolution?
