### ISSUE TITLE
Redesign navbar of .org

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#7544]
There are items we want to add to the .org navbar but there's not screen real estate right now:

* Community (now, see #6377)
* Starters (soon, see #6718)
* People / Organizations (soon, see https://github.com/gatsbyjs/rfcs/pull/8)

We should think through how we want to handle this.

**Comment by fk** [comment]
I want to suggest to use this issue to track a short-term, practical fix that allows us to add "Starters", "Community", and "Creators (People/Organizations)" to the navbar for both desktop and mobile without too much effort.

As mentioned in https://github.com/gatsbyjs/gatsby/issues/6377#issuecomment-404114364, this could be done using the "Priority Nav" pattern:

![facebook1](https://user-images.githubusercontent.com/21834/44213608-5cc9be80-a16e-11e8-8783-cbd0cf2c84fb.png)

* http://bradfrost.com/blog/post/revisiting-the-priority-pattern/
* a jQuery plugin that does a good job at demonstrating how that would look for out navbar on desktop: http://gijsroge.github.io/priority-nav.js/
* a OSS react component implementing the pattern: https://github.com/ericyip/react-priority-navigation

Pros:

* relatively easy to implement
* facilitates keeping as much navbar items visible as screen real estate allows

Drawbacks:

* requires us to make an assumption about the relative importance of each navigation item -- the ones we place first are less likely to ever be hidden in a "More" dropdown
* no clear active state for "hidden" items: if an item currently "stashed away" in the "More" dropdown is active, we can only highlight the "More" label that allows toggling the dropdown containing the active item

Following up on this, I want to suggest thinking about the .org main navigation holistically and long-term — including e.g. breadcrumbs…

> Where am I? (Present)
> Where can I go? (Future)
> Where have I been? (Past)

a footer navigation, adding previous/next article links at the bottom of doc and tutorial pages, improving search, discuss how adding a second level to the main navigation and regrouping items to reduce the number of top-level items potentially could help with current and future requirements, e.g. 

* Documentation/Learn
  * Quick Start
  * Tutorial
  * Guides
  * Reference/API
  * …
* Ecosystem
  * Plugins
  * Starters
  * Themes
* Showcase/Expo
  * Sites
  * Features
* Community
  * Overview
  * Creators
  * Partners
  * Contributing
* Blog

**Comment by berraknil** [comment]
Also wrote about this in detail on Slack, but can we first clarify if the ind/orgs pages are/should be under /creators or /community? RFC says /community which I think is confusing and clashes with this. https://github.com/gatsbyjs/rfcs/blob/rfc-individual-agency-company-pages/text/0008--individual-agency-company-pages.md

@fk @shannonbux @calcsam

**Comment by calcsam** [comment]
@KyleAMathews what were your thoughts on the priority nav in general? Re the rough video Flo made:

dropbox.com/s/391aa7bomr20sv6/priority-nav.mov?dl=0

**Comment by KyleAMathews** [comment]
Priority nav / drop downs are clunky + encourage not thinking hard about what's actually important.

- https://roundpeg.biz/2015/04/drop-drop-menu/
- https://neilpatel.com/blog/common-website-navigation-mistakes/
- https://www.rocketspark.com/blog/drop-down-menus-5-reasons-we-dont-use-them-and-3-tips-what-do-instead/

[Mega-menus](https://www.nngroup.com/articles/mega-menus-work-well/) (dropdowns with _lots_ of links) are the one exception to the rule. But we're not discussing mega-menus.

**Comment by fk** [comment]
Thank you for the links, Kyle! 🙏 

I'll sketch an alternative approach based on the regrouped top-level navigation structure I posted in https://github.com/gatsbyjs/gatsby/issues/7544#issuecomment-415063959:

* Documentation/Learn
  * Quick Start
  * Tutorial
  * Guides
  * Reference/API
  * …
* Ecosystem
  * Plugins
  * Starters
  * Themes
* Showcase/Expo
  * Sites
  * Features
* Community
  * Overview
  * Creators
  * Partners
  * Contributing
* Blog

**Comment by fk** [comment]
Based on regrouping our top-level navigation items to a maximum of five items (as outlined in https://github.com/gatsbyjs/gatsby/issues/7544#issuecomment-415063959), one way to free us from dropdowns (or hamburger menus) for the main navigation would be to **introduce a landing page for each top-level navigation item**—see the first screen here ([Figma source](https://www.figma.com/file/G3x7aYuyigYaibEpyxMsKLcP/gatsbyjs.org%3Ashowcase-starters?node-id=112%3A2598)):

<img width="1622" alt="org-landing-pages" src="https://user-images.githubusercontent.com/21834/44593031-962fa900-a7c2-11e8-9ea4-73f3a561971f.png">


* five items work both in our mobile navigation at the bottom of the viewport, as well as for desktop, where the main navigation is placed in the site header
* things explored in these mockups:
  * active state for mobile navigation items
  * "Blog" could become "News"—we could e.g. feature noteworthy external content on this landing page
  * adds a breadcrumb path above the page title, answering "Where am I? (Present)" (and potentially "Where have I been? (Past)")
  * adds icons for the landing page items—while I don't think we should have those for _every_ item on these pages, but I feel they would be worth it for the "Documentation" and "Showcase/Expo" sections
  * quick first shots at "Community" and "Ecosystem" icons

**Comment by fk** [comment]
One drawback of those landing pages however is that they force the more experienced users to "click through" a landing page to get to a subsection they _know_ they want to go to (note that this _assumes_ that these users do navigate to those pages using the navigation, and not by e.g. using a bookmark or typing out parts of the URL in their browser address field).

Bottom line: I can see how dropdowns help to navigate quicker on desktop.
How could a "dropdown-like" UI work on mobile devices?
Here's a not-so-clunky "[bottom sheet](https://material.io/design/components/sheets-bottom.html#modal-bottom-sheet)/slide-up navigation drawer" approach:

![image](https://user-images.githubusercontent.com/21834/44595470-4f917d00-a7c9-11e8-80ce-68b04c96877c.png)

* _every_ navigation requires two taps—one to open the menu drawer, the next one to navigate to a section/page—which equals the landing page scenario
* in terms of "navigate quicker", this approach only pays off if we _would want to_ provide another level of navigation items in the main navigation, e.g. "Tutorial Part 1, 2, 3…" nested below the "Tutorial" item; again, this IMO adds confusion and unnecessarily raises the amount of information to process—ideally, we want to keep the amount of items below the magic "7" (https://en.wikipedia.org/wiki/The_Magical_Number_Seven,_Plus_or_Minus_Two)
* already the top-most level of the navigation demands a choice, something which i believe to add confusion for new users

**Comment by KyleAMathews** [comment]
These look awesome Flo!

I don't see multiple clicks as an issue even for Gatsby users. Changing pages is just as fast a slider with Gatsby. The main thing is that each step should be obvious and your mockup does that.

**Comment by calcsam** [comment]
I've been thinking about this more and am coming around to agree with @KyleAMathews that we should ultimately have separate landing pages for each top-level concept, because we need a .org information hierarchy the same way. 

@fk what are your thoughts for the desktop versions of each of these pages? (Documentation/Ecosystem/Expo/Community)

**Comment by fk** [comment]
@calcsam I scribbled a bit today to think about the difference of the (new working draft) main sections (Documentation/Ecosystem/Expo/Community/News); I need a little more time there, but I'm quite happy with how things are working out. Will def. share something tomorrow.

I also started mocking up the "Docs" landing page today:

<img width="1280" alt="desktop_ docs" src="https://user-images.githubusercontent.com/21834/44672985-86b29900-aa2a-11e8-923c-5e3a2576fe32.png">

* How about we add an "External Resources" section to that page (linking e.g. to the [egghead.io Gatsby courses and lessons](https://egghead.io/browse/frameworks/gatsby)?
* added a couple more icon ideas
* colored rectangles are illustration placeholders—I'd really like to have some bespoke illustrations for our most important sections; while I think the card-based layout works without them, I think it's worth to invest a little time here
* moved the [Figma source](https://www.figma.com/file/eY2XGFAV06IW8CG3xGNSYwzY/Navigation?node-id=7%3A114) to the [Figma Gatsby team](https://www.figma.com/files/team/557586976043225786/Gatsby)

**Comment by calcsam** [comment]
Flo this looks amazing. 💯 to the card-based layout and bespoke illustrations. 

Really excited to see what you come up with for the other pages!

**Comment by fk** [comment]
Looking at https://next.gatsbyjs.org/docs/awesome-gatsby/ (a little too late), I'm wondering if the "Ecosystem" section also would be a good place to house the other external resources we're currently listing on "[Awesome Gatsby](https://next.gatsbyjs.org/docs/awesome-gatsby/)":

* [Tools](https://next.gatsbyjs.org/docs/awesome-gatsby/#tools)
* [Tutorials](https://next.gatsbyjs.org/docs/awesome-gatsby/#gatsby-tutorials) 
* [Podcasts](https://next.gatsbyjs.org/docs/awesome-gatsby/#podcasts)
* [Videos](https://next.gatsbyjs.org/docs/awesome-gatsby/#videos)

along with similar like the [egghead.io Gatsby courses and lessons](https://egghead.io/browse/frameworks/gatsby) I mentioned [earlier](https://github.com/gatsbyjs/gatsby/issues/7544#issuecomment-416293476)?

The [definition](https://en.wikipedia.org/wiki/Ecosystem) of "ecosystem" makes me think this might be the right place—and both plugins and starters to a large extent are "external", too.

What do y'all think?

**Comment by calcsam** [comment]
@fk -- I agree this looks pretty empty. 

I wonder if we could "preview" each section.

For example, a plugin library section below the plugin library card with a search bar and two/three plugins and when you start typing in it (or click one of the plugins), it takes you to the plugin library page

I don't we should break out "Awesome Gatsby" into subsections -- the traffic to that page has gone down by half since January despite overall site traffic going way up, as we've pulled out important parts into their own sections, and the traffic is way lower than other parts. An "External Resources" card could be fine.

**Comment by fk** [comment]
Here's a couple of things I have been playing around with:

* added a first shot at the "a plugin library section" as suggested by @calcsam
* exploring different card layouts for "Plugins" and "Starters"
* added a "External Resources" card

<img width="1280" alt="desktop_ ecosystem" src="https://user-images.githubusercontent.com/21834/44797652-fdc56a00-abaf-11e8-96f3-59a70c15ddc0.png">

^ not too happy with that yet, but I think the "horizontal scroller" for mobile is not too bad:

<img width="360" alt="mobile_ ecosystem" src="https://user-images.githubusercontent.com/21834/44797999-c0151100-abb0-11e8-8e57-3c725ac467ef.png">

Also took a look at the "Showcase/Expo" section:

* used a horizontal slider there to tease/show subsection content
* cards have secondary CTA buttons to directly jump to related content/section pages

<img width="1280" alt="desktop_ expo" src="https://user-images.githubusercontent.com/21834/44798088-f5216380-abb0-11e8-97d0-a28ff956b545.png">

**Comment by shannonbux** [comment]
Closing in favor of #8768 #8769 #8770
