### ISSUE TITLE
Support for png images

### ISSUE THREAD

**Issue by hsribei** [gatsbyjs/gatsby#756]
Sorry if this is too newbie a question, but I've had the following problem. I created a blog using the official blog starter, then went to replace `profile-pic.jpg` with a png image. I replace `jpg` with `png` in `components/Bio.js`, deleted the original image and added my own `profile-pic.png`. That's all. Then I got this error:
```
ERROR in ./components/profile-pic.png
Module build failed: Error: /home/hsribei/usr/src/blog/node_modules/pngquant-bin/vendor/pngquant: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory

    at Promise.all.then.arr (/home/hsribei/usr/src/blog/node_modules/execa/index.js:201:11)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

Is this something that's missing in the `package.json` file? For now I just used a jpg image and it worked, but I would like to know how to make a png file work. Thanks!

**Comment by KyleAMathews** [comment]
Looks like a package didn't install correctly. You could try deleting
node_modules and rerunning npm install.

**Comment by hsribei** [comment]
I tried that, got the same error. Let me know if I can help with more information in case you want to track this. If it seems like I'm the only person having this trouble then no need to worry as I've "solved" it by using a jpg. Thanks for Gatsby btw :)

**Comment by KyleAMathews** [comment]
Have you tried googling the error?

**Comment by hsribei** [comment]
Yes. This fixed it for me:

```
sudo apt-get install libpng-dev
npm rebuild
```
But I was wondering if this dependency could be installed along with the others.

**Comment by KyleAMathews** [comment]
Seems like it's a problem with the upstream package https://github.com/tcoopman/image-webpack-loader/issues/51

**Comment by KyleAMathews** [comment]
Closing as it's an upstream issue.

**Comment by rmcsharry** [comment]
@KyleAMathews  I just did the exact same thing with the gatsby-starter blog and the png throws the same error.

Yesterday I ran the default starter which load the astronaut.png and that did not throw an error.

Something very strange going on with PNG format.
I have libpng installed on my system so it's not that.

How can one starter work with a PNG and another not?
