### ISSUE TITLE
Netlify deploy fail due to ? in file name from gatsby-plugin-sharp

### ISSUE THREAD

**Issue by lightstrike** [gatsbyjs/gatsby#7565]
I am creating some remote file nodes that have image URLs with querystrings (ie [https://images-na.ssl-images-amazon.com/images/I/41wzgc0dDzL.jpg?w=620&ssl=1](https://images-na.ssl-images-amazon.com/images/I/41wzgc0dDzL.jpg?w=620&ssl=1)), which is fine locally, but trips the following deploy error in Netlify:

```
3:16:11 PM: Build script success
3:16:11 PM: Starting to deploy site from 'public/'
3:16:11 PM: Failing build: Failed to deploy site
3:16:11 PM: failed during stage 'deploying site': Invalid filename 'static/ba9fa7e11fff80162fc7ba76fff2dae3-b5917d30ab5c442b45f83e7f1db03de6-7a16e.jpg?resize=178%2c300&ssl=1'. Deployed filenames cannot contain # or ? characters
```

Is there a way to either change the file name within `createRemoteFileNode` or the hash naming logic to exclude? I don't such an option for the [`createRemoteFileNode` docs](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-filesystem#createremotefilenode), while based on [this comment](https://github.com/gatsbyjs/gatsby/issues/6232#issuecomment-401431738) from #6232 it appears the hashing logic is currently fixed.

**Comment by pieh** [comment]
This should be fixed by https://github.com/gatsbyjs/gatsby/pull/9011
