### ISSUE TITLE
[plugin-react-css-modules] Reinstate react-css-modules configuration in v2 plugin

### ISSUE THREAD

**Issue by seaneking** [gatsbyjs/gatsby#7572]
## Description

Seems that `gatsby-plugin-react-css-modules` had a regression from v1 -> v2, since it no longer passes user config to react-css-modules. 

### Steps to reproduce

Include `gatbsy-plugin-react-css-modules` with valid react-css-module options, eg: 
```js 
{ 
	resolve: 'gatsby-plugin-react-css-modules',
	options: { 
		handleMissingStyleName: 'warn' 
	}
}
```

### Expected result

Options should be passed through to react-css-modules

### Actual result

Additional user config is not passed through the react-css-modules

**Comment by Chuloo** [comment]
Can you create a minimal reproduction of your code showing the error?

**Comment by seaneking** [comment]
I'm not sure what else there is to show? Config options for react-css-modules are mostly to do with DX (eg: suppressing build errors for missing styleNames). Pretty straightforward issue, had a look at the src of the plugin and user options simply aren't passed to the react-css-modules Babel plugin.

Would you accept a PR to pass options to the plugin?
