### ISSUE TITLE
I am creating the project using gatsby with strapi whenever i modify the backend then i need to  restart the gatsby server how can i resolve this kind of issue?

### ISSUE THREAD

**Issue by amit-deligence** [gatsbyjs/gatsby#7575]
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LeKoArts** [comment]
Currently there’s no live update available to my knowledge but the Gatsby team is working on a solution (have a look at the blog)
