### ISSUE TITLE
when i using multiple fetch api to collect data to display then gatsby page component render before collecting data so on the page nothing to display. 

### ISSUE THREAD

**Issue by amit-deligence** [gatsbyjs/gatsby#7576]
My code is :
```js
showProducts(){

        let productids = [];
        let proHtml = [];
        console.log("this upper ===> " , this)
        this.props.data.allStrapiWishlist.edges.map(document =>{
            productids.push(document.node.productid)
        })

        for(let i = 0;i<productids.length;i++){
            fetch('http://localhost:1337/product/' + productids[i], {
                                method: 'get'
            }).then(function(response){
                 if (response.status !== 200) {
                    console.log('Looks like there was a problem. Status Code: '  ,response.status);
                    return;
                }

                return response.json();

                }).then(data =>{

                    proHtml.push(<div>
                        {data.title}
                        </div>)
                    
            })

        }
return proHtml;
}
```

**Comment by LeKoArts** [comment]
Please include more information on your project like the issue template asks for. e.g. where you run this code. If you do it on the client side then you should do it while building your site

**Comment by kakadiadarpan** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub issues, we have to clean some of the old issues as many of them have already been resolved with the latest updates.

Please make sure to update to the latest Gatsby version and check if that solves the issue. Let us know if that works for you by adding a comment 👍

**Comment by kakadiadarpan** [comment]
This issue is being closed because there hasn't been any activity for at least 30 days. Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem 👍
