### ISSUE TITLE
[v2] - Tree shaking not working correctly with some libraries (react-icons)

### ISSUE THREAD

**Issue by pzenger** [gatsbyjs/gatsby#7581]
## Description

Using `react-icons` with a few imported icons, results in the full library being imported.  The project (react-icons) seems to be setup correctly and working with other frameworks, so I believe this is an issue with the webpack configuration/defaults. 

Relevant discussion
https://github.com/react-icons/react-icons/issues/154

### Steps to reproduce
`import { FaBeer } from 'react-icons/fa'`
`use <FaBeer /> in a component`
`npm run build`
`=> Results in a bloated webapp`

**Comment by cpboyd** [comment]
@pzenger I think tree-shaking primarily seems to work for ES6 modules whereas react-icons is using CommonJS: https://cdn.jsdelivr.net/npm/react-icons@3.0.5/fa/index.js

For tree-shaking with `lodash`, I had to switch to importing from `lodash-es` instead.

Perhaps it's worth checking out webpack's [sideEffects](https://github.com/webpack/webpack/tree/master/examples/side-effects) flag per [this issue](https://github.com/webpack/webpack/issues/1750#issuecomment-388638028)

**Comment by pzenger** [comment]
@cpboyd Hmm interesting, I'll need to dig more into this.  
Seems odd that tree-shaking would only work with one convention.  The same `react-icons` library has tree shaking working fine with Create React App 🤔

**Comment by andykais** [comment]
according to the ongoing discussion over at `react-icons` react-icons/react-icons#154, to get tree shaking to work in `v3`, you need to import from the `.mjs` files. The gist of it is that we need to change webpack's `resolve.extensions` to include `.mjs` files. However, from my naiive messing around with `gatsby-node.js` I was not able to get this to work

**Comment by andykais** [comment]
update: I have found a workaround to get `.mjs` files to play nicely with gatsby.
```javascript
// gastby-node.js
exports.onCreateWebpackConfig = () => {
  actions.setWebpackConfig({
    resolve: {
      extensions: ['.mjs', '.js'],
    },
    module: {
      rules: [
        {
          test: /\.mjs$/,
          include: /node_modules/,
          type: 'javascript/auto',
        },
      ],
    },
  })
}
```
```javascript
// src/pages/index.js
// it is necessary to specify index.mjs or webpack will choose index.js by default.
import { FaBeer } from 'react-icons/fa/index.mjs';
const IndexPage = () => (
  <FaBeer/>
)
export default IndexPage
```
tree shaking does work with this method, my bundle size is much smaller than if I use `index.js`

using
- `gatsby@2.0.0`
- `react-icons@3.0.5`

**Comment by abdullahe** [comment]
I have the latest version of react-icons and gatsby, but still having this issue. I am very new to this, so I might be missing something. Is it just me, or something is broken with this lib?

Here is webpack bundle analyzer result:
![image](https://user-images.githubusercontent.com/699010/94954764-3dc74b80-04f2-11eb-9559-f6c09c5cfc43.png)

I load icons like this:

`import { FaChevronDown } from "react-icons/fa";  
import {IconContext}  from "react-icons";`

but tried this as well: 

`import { FaChevronDown } from "react-icons/fa/index";  
import {IconContext}  from "react-icons";`

packages: 
` 
	"bulma": "^0.9.0", 
	"gatsby": "^2.23.3", 
	"gatsby-background-image": "^1.1.1", 
	"gatsby-cli": "^2.12.46", 
	"gatsby-image": "^2.4.7", 
	"gatsby-plugin-brotli": "^1.3.1", 
	"gatsby-plugin-manifest": "^2.4.11", 
	"gatsby-plugin-netlify": "^2.3.5", 
	"gatsby-plugin-netlify-cms": "^4.3.5", 
	"gatsby-plugin-offline": "^3.2.9", 
	"gatsby-plugin-purgecss": "^5.0.0", 
	"gatsby-plugin-react-helmet": "^3.3.4", 
	"gatsby-plugin-sass": "^2.3.4", 
	"gatsby-plugin-sharp": "^2.6.11", 
	"gatsby-plugin-smoothscroll": "^1.1.0", 
	"gatsby-remark-copy-linked-files": "^2.3.5", 
	"gatsby-remark-images": "^3.3.10", 
	"gatsby-remark-relative-images": "^0.3.0", 
	"gatsby-source-filesystem": "^2.3.11", 
	"gatsby-transformer-remark": "^2.8.15", 
	"gatsby-transformer-sharp": "^2.5.5",
	"lodash": "^4.17.15",
	"lodash-webpack-plugin": "^0.11.4",
	"netlify-cms-app": "^2.12.14",
	"node-sass": "^4.14.1",
	"prop-types": "^15.6.0",
	"react": "^16.8.4",
	"react-dom": "^16.8.4",
	"react-helmet": "^6.1.0",
	"react-icons": "^3.10.0",
	"uuid": "^8.1.0"
`
