### ISSUE TITLE
When I modified the backend then i need to restart the gatsby server every time.which is very tedious during development and cannot possible when the site live.so, is there any way to resolve this issue?

### ISSUE THREAD

**Issue by amit-deligence** [gatsbyjs/gatsby#7588]
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LeKoArts** [comment]
See https://github.com/gatsbyjs/gatsby/issues/7575
