### ISSUE TITLE
Expose default babel config

### ISSUE THREAD

**Issue by alexandernanberg** [gatsbyjs/gatsby#7589]
## Summary

I'd like to default babel config to be exposed so that you just can extend it if you only need to add a plugin etc. Just like [next.js handles it ](https://github.com/zeit/next.js/#customizing-babel-config).

### Basic example

```json
{
  "extends": "gatsby/babel",
  "plugins": []
}
```

### Motivation

We don't need to copy the default config to the project as described [here](https://next.gatsbyjs.org/docs/babel/#how-to-use-a-custom-babelrc-file). This could cause issues if we later make adjustments to the babel config, then users config might be out-of-date. It also makes it easier and more straight forward to customize the default config.

**Comment by alexandernanberg** [comment]
Solved with #8724

**Comment by igorpupkinable** [comment]
It does not work for `plugins`. You can override `target`, but setting `plugins` has no effect.

**Comment by DSchau** [comment]
@igorpupkinable would you be able to reproduce that and open a separate issue?

We'd prefer you didn't reply to multiple issues with similar feedback if you're able--opening a new one lets us focus on the issue, at hand!
