### ISSUE TITLE
when data is not exist at backend graphql throw error of undefined how to handle it in gatsby when data not exist at backend?

### ISSUE THREAD

**Issue by amit-deligence** [gatsbyjs/gatsby#7594]
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by cezarneaga** [comment]
Hi Amit,

your description of the problem is very vague.
could you give more details or give a link to the repository where you are working on this?

thanks,
Cezar

**Comment by amit-deligence** [comment]
@cezarneaga i am using strapi as backend and Gatsby as front-end. In Gatsby I am using graphql query to fetch data from strapi content type. If content type have the data then no problem occur and if data not exist on strapi content type then Gatsby graphql throw error and down the page.

**Comment by Chuloo** [comment]
could you set a condition to only display the page or component where the data is required if there is any data fetched? and probably display a default message if there isn't anything to display.

**Comment by amit-deligence** [comment]
@Chuloo That things what i want to asked beacause before the page render graphql throw error at compile time if strapi content type not exist.like i was created the product content type on strapi if there is no field in product content type then graphql throw error of undefined at compile time.

**Comment by Chuloo** [comment]
Can this help? https://graphql.org/learn/queries/#directives

**Comment by kakadiadarpan** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub issues, we have to clean some of the old issues as many of them have already been resolved with the latest updates.

Please make sure to update to the latest Gatsby version and check if that solves the issue. Let us know if that works for you by adding a comment 👍

**Comment by kakadiadarpan** [comment]
This issue is being closed because there hasn't been any activity for at least 30 days. Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem 👍
