### ISSUE TITLE
Clean up livestream video

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#7595]
- [x] Cut the video into distinct talks
- [ ] Add titles and descriptions
- [ ] Cross-post to the blog
- [ ] Add to the relevant sections of the docs, if applicable

Video is here: https://youtu.be/7M-7GlQGeGc

**Comment by garytube** [comment]
Need help?

**Comment by jlengstorf** [comment]
@garytube I'd LOVE to have help. I have no idea what I'm doing with video. 😅

**Comment by garytube** [comment]
Haha, perfect ;)
