### ISSUE TITLE
[v2@rc.0] hastReparseRaw fails on get htmlAST

### ISSUE THREAD

**Issue by valse** [gatsbyjs/gatsby#7596]
Hi,
   in my site I need to make a post preview for the editors and I made a "client-path" page.

In this page a fetch my draft post and, to use the same components based on MD, I recreate "manually" the remark node like this:

```
remark: {
   htmlAst: getAST(result.body)
}
```
where getAST is taken from the `gatsby-transformer-remark` source code:

```
function getAST(markdown) {
  const remark = new Remark().data(`settings`, {
    commonmark: true,
    footnotes: true,
    pedantic: true
  });

  const markdownAST = remark.parse(markdown);
  const ast = toHAST(markdownAST, { allowDangerousHTML: true });
  const strippedAst = stripPosition(_.clone(ast), true);

  return hastReparseRaw(strippedAst);
}
```

All worked great until the gatsby@2.0.0-beta.111... with the latest rc.0 the `hastReparseRaw` give me an error:
```
Uncaught (in promise) TypeError: Cannot read property '0' of undefined
```
and I can't understand why :-\

Thanks
Marco

**Comment by Chuloo** [comment]
hi @valse can you create a demo reproduction repo showing this error? Would be really helpful.

**Comment by valse** [comment]
Hi,
   I made this repo extracted from my project: 
https://github.com/valse/hastReparseRaw

You can check the page at url like: 
http://localhost:8000/preview/1/

after `gatsby develop` command.

If you try to change the version to latest gatsby@beta (version 111) it works.

Thanks
valse

**Comment by kakadiadarpan** [comment]
Hi @valse, I cloned the repository but running into a very weird issue:

<img width="1429" alt="screen shot 2018-09-10 at 4 22 22 pm" src="https://user-images.githubusercontent.com/10805593/45293459-e2465180-b515-11e8-8423-3eafcc5fa607.png">

Tried installing `@babel/runtime`. but it didn't work.

**Comment by kakadiadarpan** [comment]
Still running into the same issue.

**Comment by valse** [comment]
mmm why in my local env is working?
Did you deleted `node_modules` and `.cache` folders?

**Comment by kakadiadarpan** [comment]
Yes, I had removed them.
