### ISSUE TITLE
gatsby-plugin-sharp doesn't work (v2.0rc0)

### ISSUE THREAD

**Issue by jfrolich** [gatsbyjs/gatsby#7597]
## Description

```
GraphQL Error Unknown field `childImageSharp` on type `File`
```
The imageSharp attributes are not showing up in my schema even though the plugin is defined in `gatsby-config.js` and is loaded, this query shows the plugin:

```
query {
  allSitePlugin {
    edges {
    	node {
        id
        name
      } 
    }
  }
}
```

### Steps to reproduce

Created a new project with v2.0rc0 and the 2.0 starter.

### Environment

  System:
    OS: macOS 10.14
    CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 2.3.1 - /usr/local/bin/fish
  Binaries:
    Node: 10.3.0 - /usr/local/bin/node
    Yarn: 1.9.4 - ~/.yarn/bin/yarn
    npm: 6.3.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 62.0
    Safari: 12.0
  npmPackages:
    gatsby: 2.0.0-rc.0 => 2.0.0-rc.0 
    gatsby-image: next => 2.0.0-rc.0 
    gatsby-mdx: ../gatsby-mdx/packages/gatsby-mdx => 0.0.11 
    gatsby-plugin-emotion: next => 2.0.0-rc.0 
    gatsby-plugin-flow: ^1.0.1-beta.0 => 1.0.1-beta.0 
    gatsby-plugin-manifest: next => 2.0.2-rc.0 
    gatsby-plugin-offline: next => 2.0.0-rc.0 
    gatsby-plugin-react-helmet: next => 3.0.0-rc.0 
    gatsby-plugin-sharp: 2.0.0-rc.0 => 2.0.0-rc.0 
    gatsby-source-filesystem: next => 2.0.1-rc.0 
    gatsby-transformer-sharp: next => 2.1.1-rc.0 
  npmGlobalPackages:
    gatsby-cli: 1.1.10

### File contents (if changed)

`gatsby-config.js`: 
```
module.exports = {
  siteMetadata: {
    title: 'Family Five',
  },
  plugins: [
    `gatsby-plugin-flow`,
    'gatsby-plugin-react-helmet',
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: 'Family Five',
        short_name: 'Family5',
        start_url: '/',
        background_color: '#FFFFFF',
        theme_color: '#C569D6',
        display: 'minimal-ui',
        icon: 'src/images/icon.png', // This path is relative to the root of the site.
      },
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/pages/`,
        name: 'pages',
      },
    },
    'gatsby-plugin-offline',
    {
      resolve: `gatsby-mdx`,
      options: {
        extensions: ['.mdx', '.md'],
        defaultLayout: require.resolve('./src/components/Page.js'),
      },
    },
    {
      resolve: `gatsby-plugin-emotion`,
      options: {
        // Accepts all options defined by `babel-plugin-emotion` plugin.
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
  ],
}

```

`package.json`: 
```
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "@mdx-js/mdx": "^0.15.0",
    "@mdx-js/tag": "^0.15.0",
    "color": "^3.0.0",
    "emotion": "^9.2.6",
    "emotion-server": "^9.2.6",
    "eslint-config-react-app": "^2.1.0",
    "gatsby": "2.0.0-rc.0",
    "gatsby-image": "next",
    "gatsby-mdx": "../gatsby-mdx/packages/gatsby-mdx",
    "gatsby-plugin-emotion": "next",
    "gatsby-plugin-flow": "^1.0.1-beta.0",
    "gatsby-plugin-manifest": "next",
    "gatsby-plugin-offline": "next",
    "gatsby-plugin-react-helmet": "next",
    "gatsby-plugin-sharp": "2.0.0-rc.0",
    "gatsby-source-filesystem": "next",
    "gatsby-transformer-sharp": "next",
    "lodash-es": "^4.17.10",
    "react": "^16.4.2",
    "react-dom": "^16.4.2",
    "react-emotion": "^9.2.6",
    "react-helmet": "^5.2.0",
    "react-portal": "^4.1.5",
    "svgo": "^0.7.0",
    "svgo-loader": "^1.2.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write '**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "prettier": "^1.14.2"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  }
}

```

`gatsby-node.js`:
```
/**
 * Implement Gatsby's Node APIs in this file.
 *
 * See: https://www.gatsbyjs.org/docs/node-apis/
 */
const path = require('path')

exports.createPages = ({ graphql, actions }) => {
  const { createPage } = actions

  return new Promise((resolve, reject) => {
    resolve(
      graphql(`
        {
          allMdx {
            edges {
              node {
                fileAbsolutePath
                fileNode {
                  name
                }
              }
            }
          }
        }
      `).then(result => {
        if (result.errors) {
          console.log(result.errors)
          reject(result.errors)
        }

        result.data.allMdx.edges.forEach(edge => {
          createPage({
            path: edge.node.fileNode.name,
            component: edge.node.fileAbsolutePath,
            context: {
              frontmatter: edge.node.frontmatter,
              absPath: edge.node.fileAbsolutePath,
            },
          })
        })
      })
    )
  })
}

const svgoConfig = JSON.stringify({
  plugins: [],
})

exports.onCreateWebpackConfig = ({ actions, stage, loaders }) => {
  actions.setWebpackConfig({
    module: {
      rules: [
        // optimize SVG images using SVGO, before loading them
        {
          test: /.*\.svg$/,
          enforce: 'pre',
          use: [{ loader: 'svgo-loader', options: svgoConfig }],
        },
      ],
    },
  })
}

```

`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by Chuloo** [comment]
Could you state the expected and actual results? Couldn't reproduce your error. Better still you could create a minimal reproduction showing this error. 👍

**Comment by jfrolich** [comment]
Yeah pretty strange, don't really have time to create a minimal example, but I was pretty puzzled by this so wanted to report it. I just created a gatsby site from the starter, and tried to add `gatsby-plugin-sharp`. It does not show up in the schema at at all.

I could however share the source code privately.

**Comment by Chuloo** [comment]
yes @jfrolich please you can share so the issue would be better understood.

**Comment by akoolenbourke** [comment]
My issue may or not be related (I"m on v2RC as well) to this but I was trying to use the example (Slightly modified to be a StaticQuery) query from the plugins page and I get a similar error. Here's a snippet.

```const Hero = () => (
  <StaticQuery
    query={graphql`
      query GetBGImage {
        file(relativePath: { eq: "images/homepage-test.jpg" }) {
          childImageSharp {
            resolutions {
              ...GatsbyImageSharpResolutions
            }
          }
        }      
      }
    `}

This is the error I get:
`20:9  error    Cannot query field "file" on type "Query". Did you mean "site"?  graphql/template-strings```

As far as I can tell it's all standard stuff that should work.

**Comment by stefanprobst** [comment]
@jfrolich Sorry if this is too obvious - but do you actually have images in your `pages` folder? If no image can be found in the folders you set up with `gatsby-source-filesystem`, you will not be able to query them, i.e. `allImageSharp` and `childImageSharp` won't show up.

**Comment by stefanprobst** [comment]
@akoolenbourke It seems you are trying to use v1 of `gatsby-image` with v2 of gatsby. Try installing `yarn add gatsby-image@next gatsby-plugin-sharp@next gatsby-transformer-sharp@next`. `resolutions`/`sizes` are now `fixed`/`fluid`.

**Comment by jfrolich** [comment]
> @jfrolich Sorry if this is too obvious - but do you actually have images in your `pages` folder? If no image can be found in the folders you set up with `gatsby-source-filesystem`, you will not be able to query them, i.e. `allImageSharp` and `childImageSharp` won't show up.

Ah that actually might be the problem. Let me check!

**Comment by kakadiadarpan** [comment]
@jfrolich any updates on this issue?

Also, can you try upgrading gatsby and dependencies to their latest stable versions? We released version 2 recently, that might solve the issue for you.

**Comment by kakadiadarpan** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub issues, we have to clean some of the old issues as many of them have already been resolved with the latest updates.

Please make sure to update to the latest Gatsby version and check if that solves the issue. Let us know if that works for you by adding a comment 👍

**Comment by kakadiadarpan** [comment]
This issue is being closed because there hasn't been any activity for at least 30 days. Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem 👍
