### ISSUE TITLE
Gatsby v2 gatsby-transformer-sharp error (can't find module)

### ISSUE THREAD

**Issue by nodroglegin** [gatsbyjs/gatsby#7600]
## Description
v2 of starter-blog gives error when running `gatsby develop` related to gatsby-transformer-sharp

### Steps to reproduce

After running v2 of:
`gatsby new my-blog https://github.com/gatsbyjs/gatsby-starter-blog#v2`

`gatsby develop` gives the following error:

```
error Plugin gatsby-transformer-sharp returned an error
Error: Cannot find module '../build/Release/sharp.node'

```
### Expected result

Should start server normally.

### Actual result

`error Plugin gatsby-transformer-sharp returned an error

  Error: Cannot find module '../build/Release/sharp.node'
  
  - v8-compile-cache.js:159 require
    [starter-blog]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - constructor.js:10 Object.<anonymous>
    [starter-blog]/[sharp]/lib/constructor.js:10:15
  
  - v8-compile-cache.js:178 Module._compile
    [starter-blog]/[v8-compile-cache]/v8-compile-cache.js:178:30
  
  - v8-compile-cache.js:159 require
    [starter-blog]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - index.js:3 Object.<anonymous>
    [starter-blog]/[sharp]/lib/index.js:3:15
  
  - v8-compile-cache.js:178 Module._compile
    [starter-blog]/[v8-compile-cache]/v8-compile-cache.js:178:30
  
  - v8-compile-cache.js:159 require
    [starter-blog]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - index.js:7 Object.<anonymous>
    [starter-blog]/[gatsby-plugin-sharp]/index.js:7:15
  
  - v8-compile-cache.js:178 Module._compile
    [starter-blog]/[v8-compile-cache]/v8-compile-cache.js:178:30
  

error UNHANDLED REJECTION

  TypeError: Cannot read property 'filter' of undefined
  
  - api-runner-node.js:274 Promise.mapSeries.catch.then.results
    [starter-blog]/[gatsby]/dist/utils/api-runner-node.js:274:42
  
  - util.js:16 tryCatcher
    [starter-blog]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [starter-blog]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [starter-blog]/[bluebird]/js/release/promise.js:569:18
  
  - promise.js:614 Promise._settlePromise0
    [starter-blog]/[bluebird]/js/release/promise.js:614:10
  
  - promise.js:693 Promise._settlePromises
    [starter-blog]/[bluebird]/js/release/promise.js:693:18
  
  - async.js:133 Async._drainQueue
    [starter-blog]/[bluebird]/js/release/async.js:133:16
  
  - async.js:143 Async._drainQueues
    [starter-blog]/[bluebird]/js/release/async.js:143:10
  
  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [starter-blog]/[bluebird]/js/release/async.js:17:14
  
`

### Environment

 System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 9.4.0 - /usr/local/bin/node
    Yarn: yarn install v0.24.6
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 43.46s. - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-rc.0 
    gatsby-plugin-feed: next => 2.0.0-rc.0 
    gatsby-plugin-google-analytics: next => 2.0.0-rc.0 
    gatsby-plugin-manifest: next => 2.0.2-rc.0 
    gatsby-plugin-offline: next => 2.0.0-rc.0 
    gatsby-plugin-react-helmet: next => 3.0.0-rc.0 
    gatsby-plugin-sharp: next => 2.0.0-rc.0 
    gatsby-plugin-typography: next => 2.2.0-rc.0 
    gatsby-remark-copy-linked-files: next => 2.0.0-rc.0 
    gatsby-remark-images: next => 2.0.1-rc.0 
    gatsby-remark-prismjs: next => 3.0.0-rc.0 
    gatsby-remark-responsive-iframe: next => 2.0.0-rc.0 
    gatsby-remark-smartypants: next => 2.0.0-rc.0 
    gatsby-source-filesystem: next => 2.0.1-rc.0 
    gatsby-transformer-remark: next => 2.1.1-rc.0 
    gatsby-transformer-sharp: next => 2.1.1-rc.0 
  npmGlobalPackages:
    gatsby-cli: 2.0.0-rc.0

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by KyleAMathews** [comment]
This is unfortunately a common problem. The solution is to delete node_modules and try reinstalling.
