### ISSUE TITLE
gatsby-link for external links

### ISSUE THREAD

**Issue by mittalyashu** [gatsbyjs/gatsby#7601]
## Summary

Currently `gatsby-link` doesn't work properly with external links. Instead of showing the url, it append the url with the current url, it shows: `http://localhost:8000/https:/mittalyashu.now.sh`

### Basic example

![2018-08-24_19-53-04](https://user-images.githubusercontent.com/29014463/44589888-68a12a80-a7d7-11e8-909e-572b6a19c91d.gif)

It should have redirected to `https://mittalyashu.now.sh`

### How it can be achieved?

By passing a parameter `external`.

`<Link external to="https://mittalyashu.now.sh">External page</Link>`

**Comment by LeKoArts** [comment]
Gatsby‘s Link component shouldn’t be used for external links:
https://next.gatsbyjs.org/docs/gatsby-link/#use-link-only-for-internal-links

**Comment by maisonm** [comment]
Based on the Gatsby docs linked, any external link appears to be just a simple `<a>` tag with an href as usual. However in my Gatsby application, when I follow this, I can not get the external links to work. My external href's are added to localhost:8000 and I get a 404 page not found. Am I missing something here?

`   <a href="www.github.com/maisonm" target="_blank" rel="noopener norefferer">
      <img src={Github} alt="github logo" />
    </a>`

**Comment by ryanmargheriti** [comment]
> you must use `https://` or `http://` in the href tag for an external link to work.

This should really be in the docs

**Comment by pdxbmw** [comment]
> target="_blank" rel="noopener norefferer"

@maisonm Thanks for this. Just quick note that it should be `noreferrer` (small typo).
