### ISSUE TITLE
[EPIC] v2.0 Plugin library

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#7612]
### Who will own this?

_What Area of Responsibility does this fall into? Who will own the work, and who needs to be aware of the work?_

**Area of Responsibility:**

_Select the Area of Responsibility *most impacted* by this Epic_

- [ ] Community
- [ ] Learning
- [x] Ecosystem
- [ ] Gatsby Core
- [ ] Enterprise
- [ ] Design
- [ ] Marketing
- [ ] Company/Admin
- [ ] Sales

     |                 |       |
     | --------------- | ----- |
     | AoR owner       | @amberleyromo |
     | Domain owner   | @name |
     | Project manager | @name |
     | Tech lead       | @name |
     | Contributors    | @name |

### Summary

This epic organizes enhanced sorting and filters for the plugin library.

### How will this impact Gatsby?

**Domains**

Plugin Library

**Components**

_List the impacted Components here_

### Goals

_What are the top 3 goals you want to accomplish with this epic? All goals should be specific, measurable, actionable, realistic, and timebound._

1. Increase usage of official plugins
2. Measure baseline usability of library and improve baseline measurements (for example, on basic tasks like searching for a particular plugin). I'm guessing what we'll want to improve is the following: how easy it is to find a few official plugins, find more obscure plugins, choose between similar plugins, and author a plugin.
3. Increase number of submitted plugins
4. Decrease the number of incomplete READme files

### How will we know this epic is a success?

Reaching the goals above!

**User Can Statement**

- User can find the plugins they are looking for with fewer clicks than before
- User can find installation instructions for any plugin
- User can evaluate between similar plugins and choose one

**Metrics to Measure Success**

- Same as goals above

### Additional Description

We already did this work on the plugin library:
- [v1.0](https://github.com/gatsbyjs/gatsby/issues/3003)
- [v1.5](https://github.com/gatsbyjs/gatsby/issues/4394)

### What are the risks to the epic?

The only things we give up are time devoted to the project. I can't think of any downsides yet.

### What questions do we still need to answer, or what resources do we need?

We need to do 5 usability tests on the current plugin library to see how easy it is to find a few official plugins, find more obscure plugins, choose between similar plugins, and author a plugin.

### How will we complete the epic?

Finish the issues and PR's in this epic.

### How else could we accomplish the same goal?

Probably can't accomplish this any other way.

**Comment by calcsam** [comment]
@shannonbux what issues should fall under here?

**Comment by shannonbux** [comment]
@calcsam updated with 3 issues that have been open for a long time, but not more than a stub still.

This isn't a high priority so I haven't taken the time to fill it out completely yet. Happy to do that if that's important.
