### ISSUE TITLE
Gatsby OSS Issue Dashboard

### ISSUE THREAD

**Issue by calcsam** [gatsbyjs/gatsby#7622]
## Summary

* A diagram of all stages in the issue flow
* Dashboard of all issues at each stage & how long they've been there
* Overall granular tracking of time-to-response and time-to-resolution, a CFD diagram, etc.

**Comment by marisamorby** [comment]
@jlengstorf: I believe this epic should be connected with the [EPIC] OSS Process #7583

**Comment by jlengstorf** [comment]
@marisamorby Connected. I'll clean this up into issues that match our current and future scope shortly.

**Comment by jlengstorf** [comment]
This is closely related to #8418. This is the page that will display those links once they're created.
