### ISSUE TITLE
Update using-page-transitions example

### ISSUE THREAD

**Issue by merelinguist** [gatsbyjs/gatsby#7630]
The page transition example no longer works since the move to reach router. I tried migrating it myself, but could’t piece together the Gatsby  + reach docs well enough.

**Comment by Chuloo** [comment]
is this similar to #7603? can you give more info as to *how* it doesn't work?

**Comment by merelinguist** [comment]
It looks the same as #7603, yep. The `history` package doesn’t seem to be installed, and `gatsby-browser` uses a now deprecated API.

**Comment by Chuloo** [comment]
Okay, thanks for pointing that out @merelinguist 👍. Will close this as a duplicate so we can keep tidy track of the issue in #7603. 

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you experience something different. 👍 😄
