### ISSUE TITLE
Is there a way to cache "blur-up" process of gatsby-image

### ISSUE THREAD

**Issue by btk** [gatsbyjs/gatsby#7636]
## Summary

I have started migrating our fairly big wordpress site to gatsby. We have around 5k pages, and most of them use gatsby-image, and blur-up effect is a really adds a lot for our UX, but I noticed that it takes so much resources and time during the build process.

## Relevant information

A page has around 7 gatsby-image objects with various sizes (between 300 and 700 w)

Here is the time difference of the build with using blur-up effect and not using it.
~~~
<Img resolutions={image.childImageSharp.resolutions} key={image.childImageSharp.resolutions.src} className="thumbnail"/>
//...
featured_media {
            localFile {
              childImageSharp {
                resolutions(width: 300, height: 150, quality: 80, cropFocus: CENTER) {
                  ...GatsbyImageSharpResolutions_withWebp
                }
              }
            }
          }
~~~

Build output; 

~~~
$ ./node_modules/.bin/gatsby build --prefix-paths
success open and validate gatsby-config — 0.006 s
success load plugins — 0.335 s
success onPreInit — 0.553 s
success delete html and css files from previous builds — 0.006 s
success initialize cache — 0.068 s
success copy gatsby files — 0.009 s
success onPreBootstrap — 0.006 s

success source and transform nodes — 27.438 s
success building schema — 1.263 s
success createPages — 0.593 s
success createPagesStatefully — 0.152 s
success onPreExtractQueries — 0.005 s
success update schema — 0.961 s
success extract queries from components — 0.387 s

success run graphql queries — 133.426 s — 387/387 2.90 queries/second
success write out page data — 0.043 s
success write out redirect data — 0.003 s
success onPostBootstrap — 0.042 s

info bootstrap finished - 1112.911 s

success Building production JavaScript and CSS bundles — 25.423 s
success Building static HTML for pages — 8.631 s — 387/387 51.08 pages/second
info Done building in 1147.332 sec
~~~

But if I stop using base64 here is the result;

~~~
<Img resolutions={image.childImageSharp.resolutions} key={image.childImageSharp.resolutions.src} className="thumbnail"/>
//...
featured_media {
            localFile {
              childImageSharp {
                resolutions(width: 300, height: 150, quality: 80, cropFocus: CENTER) {
                  ...GatsbyImageSharpResolutions_withWebp_noBase64
                }
              }
            }
          }
~~~

~~~
$ ./node_modules/.bin/gatsby build --prefix-paths
success open and validate gatsby-config — 0.022 s
success load plugins — 0.322 s
success onPreInit — 0.815 s
success delete html and css files from previous builds — 2.142 s
success initialize cache — 0.191 s
success copy gatsby files — 0.008 s
success onPreBootstrap — 0.005 s

success source and transform nodes — 28.796 s
success building schema — 1.247 s
success createPages — 0.591 s
success createPagesStatefully — 0.157 s
success onPreExtractQueries — 0.005 s
success update schema — 1.013 s
success extract queries from components — 0.398 s

success run graphql queries — 78.231 s — 387/387 4.95 queries/second
success write out page data — 0.005 s
success write out redirect data — 0.000 s
success onPostBootstrap — 0.043 s

info bootstrap finished - 118.02 s

success Building production JavaScript and CSS bundles — 9.725 s
success Building static HTML for pages — 7.729 s — 387/387 60.05 pages/second
info Done building in 136.196 sec
~~~

### Environment (if relevant)

I use Gitlab CI, but here is my local env.

~~~
  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 5.8.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Safari: 11.1
  npmPackages:
    gatsby: ^2.0.0-rc.0 => 2.0.0-rc.0 
    gatsby-image: ^2.0.0-rc.0 => 2.0.0-rc.0 
    gatsby-plugin-glamor: ^2.0.0-rc.0 => 2.0.0-rc.0 
    gatsby-plugin-google-fonts: ^0.0.4 => 0.0.4 
    gatsby-plugin-netlify-cache: ^0.1.0 => 0.1.0 
    gatsby-plugin-nprogress: ^1.0.14 => 1.0.14 
    gatsby-plugin-react-helmet: ^3.0.0-rc.0 => 3.0.0-rc.0 
    gatsby-plugin-sharp: ^2.0.0-rc.0 => 2.0.0-rc.0 
    gatsby-source-wordpress: ^3.0.0-rc.0 => 3.0.0-rc.0 
    gatsby-transformer-sharp: ^2.1.1-rc.0 => 2.1.1-rc.0 
  npmGlobalPackages:
    gatsby: 1.9.277

~~~

As you can see it is a really big difference, and this is just a sample part of the pages that I build to demo the time difference (387 pages) and normally have 5k pages. Even 387 pages takes over **22 mins** of build time without base64 it takes just 2-3 mins, I don't even want to talk about 5k pages.

**My questions are:** 
- I don't want to give up on the blur-up effect, is there any way I can manually optimise this?
- Do you think this time difference comes from the generation of base64 string as I suspect? Or a combination of it being embeded into HTML files?
- Can we implement a way that we can cache the base64 string, so we don't have to render it all over between builds?
- Is it a good practice to have blur-up effect as default, since most of the developers will use it without knowing and have a really high build time? (maybe we can add a warning in the documentation of gatsby-image)

Also I would love to add a PR if you think caching blurred-up version of the images somehow in `.cache`, to avoid the regeneration of the images between builds would get around this long build time.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`:  
~~~
Changed a lot but it is too long and not relevant
~~~
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by Chuloo** [comment]
@btk could you send in a PR to plugin-sharp?

**Comment by oorestisime** [comment]
Hello,

plugin sharp got cache for base64 calculations recently. https://github.com/gatsbyjs/gatsby/pull/9059
do you mind verifying if this solved your issue and whether subsequent builds are faster?

**Comment by btk** [comment]
@oorestisime Thanks, great work, it works like a charm!

```
[0]: info Done building in 1147.332 sec
[1]: info Done building in 169.196 sec
[2]: info Done building in 172.113 sec
[3]: info Done building in 142.844 sec
```

I can use blur-up on the production now, this is great! Closing this issue

**Comment by erodrig** [comment]
I see you refer to featured images, and we have control over them, but what about markdown content images, when using gatsby-remark-images, my build time for a 600 pages blog goes into 1 h. I see 50193 thumbnails being created. I don't have a way to remove blur-up to test if that helps or not

**Comment by yashvekaria** [comment]
I am facing a similar kind of issue, where I am using gatsby-plugin-sharp and gatsby-transform-sharp for the image blur up and transform the process and all images being cached initially in the **.cache** folder. When I do subsequent build (incremental build), those plugins will again process all the images from scratch even though it's in the cache. Is there any way to stop reprocessing all images, what is being done by plugins in every build?
