### ISSUE TITLE
Best Practice for Creating a Gatsby Source Plugin that May Need to Make Multiple API Calls?

### ISSUE THREAD

**Issue by marcaaron** [gatsbyjs/gatsby#7639]
Followed the awesome tutorial on creating a gatsby source plugin [here](https://www.gatsbyjs.org/docs/source-plugin-tutorial/), but wondering if there's a preferred way that people are making multiple API calls within the main sourceNodes async function? e.g. if you only want to query/transform nodes for n number of fields. This is maybe more of a general JS / Node question, but figured y'all probably have run into this before. (And maybe it would be a good thing to advise people on in the docs ? ).

Basically have things set up so a user can add the separate fields they want queried from a REST API as strings in an array within the plugin configOptions. I set up another async function that will loop over the array of strings fetch the nodes and then process them after. But I'm wondering if this can be further optimized?

```javascript
  const { fields } = configOptions;

  // Fetch Node and turn our response to JSON
  const fetchNodes = async (fieldName) => {
    const res = await WooCommerce.getAsync(fieldName);
    return JSON.parse(res.toJSON().body);
  };

  // Loop over each field set in configOptions and process/create nodes
  async function fetchNodesAndCreate (array) {
    for (const field of array) {
      const nodes = await fetchNodes(field);
      nodes.forEach(n=>createNode(processNode(createNodeId, n, field)));
    }
  }
  
  // Leh go...
  await fetchNodesAndCreate(fields);
```

**Comment by KyleAMathews** [comment]
It would be faster to do the API calls in parallel. What you have now is making serial calls. 

https://stackoverflow.com/questions/35612428/call-async-await-functions-in-parallel
