### ISSUE TITLE
Disable IntersectionObserver on Link

### ISSUE THREAD

**Issue by tekmaven** [gatsbyjs/gatsby#7644]
## Summary

It would be great to have a way to disable the `IntersectionObserver` functionality on the `<Link />` component.  

### Basic example
Adding an additional boolean prop to `<Link />`.  I'm very open to suggestions on naming!  It should default to `true`, to be backwards compatible with the existing API.

```
import { Link } from 'gatsby'

<Link enableIntersectionObserver={false} to={node.fields.slug}>{title}</Link>
```

### Motivation

My personal use case is a blog list page, which is just article titles in a list.  Since 10 links appear in the viewport, the prefeching kicks in and downloads a lot of pages.  I would only like the first N links to be prefeched, and the rest to benefit from the other great behavior of `<Link />` - the on-hover prefetching.  Many other use cases that contain a dense amount of links could benefit.

If this idea is accepted, I can submit a PR.

**Comment by KyleAMathews** [comment]
Perhaps instead you could try using guess.js? https://www.npmjs.com/package/gatsby-plugin-guess-js

Manually fiddling with prefetching isn't very easy or accurate so we'd prefer to push forward on automated ways of optimizing prefetching based on analytics.
