### ISSUE TITLE
Tests on Windows fail - reasons and ways to fix

### ISSUE THREAD

**Issue by vtenfys** [gatsbyjs/gatsby#7652]
cc @calcsam re: https://github.com/orgs/gatsbyjs/teams/maintainers/discussions/30/comments/7

Tests on Windows are broken due to two specific issues, which only affect a single package (gatsby-codemods). Both of these are technically upstream issues, rather than issues with Gatsby itself.

TL;DR we need to update @babel/core to at least 7.0.0-rc.3 (the hard part) and change one line in a single file.

---

Global GraphQL transforms (generated by `gatsby-codemods/global-graphql-calls`) output with the native system line-endings, rather than always using `\n`. This causes its jscodeshift tests to fail, since unlike Jest's built-in snapshot testing, jscodeshift's fixture tests don't normalise line endings.

To fix this, change the following line in `gatsby-codemods/src/global-graphql-calls.js` from:

```js
return root.toSource({ quote: `single` })
```

to:

```js
return root.toSource({ quote: `single`, lineTerminator: `\n` })
```

...so that the generated files match the snapshots, which use `\n` endings, rather than `\r\n` on Windows. Alternatively, to fix the root cause of the issue, a PR could be sent to jscodeshift so that it normalises line endings when performing fixture tests.

---

Babel's `--ignore **/__tests__` option is buggy on Windows with version 7.0.0-beta.52. Basically Babel converts globs to a regex, and then matches all files against this regex - internally this works a bit differently between Babel 7.0.0-beta.52 (which Gatsby is currently using) and 7.0.0-rc.3 (the latest version) - previously Babel used minimatch to do the conversion, but with the latest RC, it's been rewritten so that [it does the conversion itself](https://github.com/babel/babel/blob/master/packages/babel-core/src/config/pattern-to-regex.js). So basically, to fix this issue we just need to update Babel to at least 7.0.0-rc.3.

*Sidenote: the following line in `.babel-preset.js` needs to be changed to upgrade to Babel 7 rc3:*

![image](https://user-images.githubusercontent.com/4248177/44628027-8df57c00-a930-11e8-9660-c6463ac6c2fe.png)

*Various other problems occur but these are package-specific, whereas ALL builds will fail without this change.*

**Comment by davidbailey00** [comment]
I'm currently working on upgrading Gatsby to the latest version of Babel (mostly just fixing config options / tests which have changed).
