### ISSUE TITLE
gatsby-remark-images-contentful not visible on plugins page

### ISSUE THREAD

**Issue by sedubois** [gatsbyjs/gatsby#7653]
It's not visible on https://www.gatsbyjs.org/plugins/ although e.g. gatsby-remark-images is found.

<img width="499" alt="screen shot 2018-08-26 at 15 41 04" src="https://user-images.githubusercontent.com/4217871/44628350-8c36b300-a946-11e8-9764-0e403a99118e.png">

**Comment by LeKoArts** [comment]
I created a PR to fix it 👍
