### ISSUE TITLE
How to manipulate HTML with conditional statements

### ISSUE THREAD

**Issue by GiraffeCoding** [gatsbyjs/gatsby#7656]
Hi,

I'm trying to find a way to check to see if a value returned from a GraphQL query is null and use a different HTML layout if null is returned. The code below is used load in a list of blog posts from a GraphQL query. But a few items may not have a value which means different html needs to be loaded.

```
const PostLink = ({ post }) => (
  <div>
    <Link to={post.frontmatter.path} class="post">
      <div className="post-holder">
        <div className="post-img">
            <img src={post.frontmatter.image} alt="gatsby" />
        </div>
        <div className="post-content">
            <span className="post-title">{post.frontmatter.title}</span>
            <span className="post-date">{post.frontmatter.date}</span>
            <span className="post-preview">{post.frontmatter.preview}</span>
        </div>
      </div>
       
    </Link>
  </div>)
```
Now I want to check to see if the an item such as `{post.frontmatter.image}` is null. I've tried to use an If statement but its not letting me use one in this situation. How would I go about manipulating this function?

Thanks in advance for any help and advice

**Comment by geekysneaks** [comment]
Hey, did you solve this?
