### ISSUE TITLE
[gatsby-plugin-sharp] Not setting width throws an exception

### ISSUE THREAD

**Issue by NindroidX** [gatsbyjs/gatsby#7664]
## Description

[This commit](https://github.com/gatsbyjs/gatsby/commit/7cda59b359f4281e67030c777a985c05c6943b92) removed the default values for the width / maxWidth. However, if you do leave it empty sharp will throw an error because of [this code](https://github.com/gatsbyjs/gatsby/blob/4b135ded715b6649518bc57fd8bb48a430b09d95/packages/gatsby-plugin-sharp/src/index.js#L136). `width` can now be undefined so it should be checked there as well. At the moment this returns NaN, which makes sharp throw an [exception](https://github.com/lovell/sharp/blob/5bed3a7d52434451316e9479c5b5e54fa66ffccb/lib/resize.js#L82).

It's a simple fix, but I'm new to Gatsby so I'm not really sure how to contribute.

### Steps to reproduce

Use fixed without setting a width 

### Expected result

The image should be resized based on its height

### Actual result

Sharp throws an invalidParameterError

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.2.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 61.0.2
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.0.0-rc.0 => 2.0.0-rc.0
    gatsby-image: ^1.0.55 => 1.0.55
    gatsby-plugin-emotion: ^2.0.0-rc.0 => 2.0.0-rc.0
    gatsby-plugin-google-fonts: ^0.0.4 => 0.0.4
    gatsby-plugin-react-helmet: ^3.0.0-rc.0 => 3.0.0-rc.0
    gatsby-plugin-sharp: ^2.0.0-rc.0 => 2.0.0-rc.0
    gatsby-source-filesystem: ^2.0.1-rc.0 => 2.0.1-rc.0
    gatsby-transformer-remark: ^2.1.1-rc.0 => 2.1.1-rc.0
    gatsby-transformer-sharp: ^2.1.1-rc.0 => 2.1.1-rc.0
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LeKoArts** [comment]
Here’s everything you need to know to get started with contributing:
https://next.gatsbyjs.org/docs/how-to-contribute/

**Comment by fk** [comment]
Hey @NindroidX! 👋 
Yep, `topic` is fine for bugfixes, too!

**Comment by NindroidX** [comment]
Sorry, I already created a branch under the `fix/` prefix, but I can rename if needed.

I just added a simple check similar to the height one, but I'm wondering if those checks are needed there? Personally I'm more a fan of 'garbage in garbage out' but even if you would want to add checks, I don't think the `processFile` function is the best place to add them?
