### ISSUE TITLE
New starter based on HTML5 UP template 'Directive'

### ISSUE THREAD

**Issue by gregtillbrook** [gatsbyjs/gatsby#7669]
Hiya Ive just created a gatsby starter - based on the HTML5 UP template called 'Directive'

https://github.com/gregtillbrook/gatsby-starter-directive

This is similar to the existing HTML5 UP starters mentioned in the docs. Just mentioning here incase it's of use to anyone.

**Comment by LeKoArts** [comment]
Cool!
You can add it to the list with a PR (at the bottom „Edit this file“)
https://next.gatsbyjs.org/docs/gatsby-starters/

**Comment by gregtillbrook** [comment]
Cool, thanks. PR created https://github.com/gatsbyjs/gatsby/pull/7683
