### ISSUE TITLE
Need some advice on handling sessions (to PHP backend) in Gatsby?

### ISSUE THREAD

**Issue by akoolenbourke** [gatsbyjs/gatsby#7674]
## Summary

Hi all. First I want to say that our website is coming along really well and I am quite impressed with Gatsby so far.

We have a PHP back end (We can't change) and now have a requirement to handle a few scenarios regarding sessions. I'm after some guidance on how to approach this topic within Gatsby.

A bit of background;
When a user visits our site we will establish a session, initially anonymous. They can browse and add items to the cart, all without logging in. We have a nav bar at the top that has a button that can be clicked to generate a drop down showing the cart items and any non-private user info (Like name). We would like this information to be available throughout the site, without having to continually query for "current session data" on every page; incurring yet another roundtrip.

Is there some place in a Gatsby site where it's guaranteed I can have a single, created-once  instance of my "session" object and just access it from my pages. The "session" object could then just manage any requirement it has to keep data "fresh" or check back with the server for expiry etc.

Secondly, is this a good idea and if not what it typically recommended?

Note, I'm not talking so much about gating pages based on auth, although I will need that at some point. 

Thanks
Aaron

**Comment by kayandrae07** [comment]
I think during the initial phase when you establish an anonymous connection, you should return a token from the server and save that to `localstorage` (it is available across every tab). That token should act as your beacon to phone home.

**Comment by KyleAMathews** [comment]
Using something like Redux or Mobx is pretty common for storing global state like this https://github.com/gatsbyjs/gatsby/blob/master/examples/using-redux/README.md
