### ISSUE TITLE
ACF Options Page not showing up in graphql

### ISSUE THREAD

**Issue by iamkratos** [gatsbyjs/gatsby#7678]
## Description

I'm trying to get acf fields from my options page, but the path is not coming up in the graphql explorer.

### Steps to reproduce

Setup a Gatsby WP build, and add an options page, and add custom fields to it:

`if( function_exists('acf_add_options_page') ) {
	acf_add_options_page();
}`

### Expected result

I should be able to see the custom fields of my options page in the GraphQL explorer

### Actual result

It's not showing any path to the options page

### Environment

  ```
System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 9.2.0 - ~/.nvm/versions/node/v9.2.0/bin/node
    Yarn: 1.3.2 - /usr/local/bin/yarn
    npm: 5.5.1 - ~/.nvm/versions/node/v9.2.0/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 61.0.1
    Safari: 11.1.2
  npmPackages:
    gatsby: ^1.9.139 => 1.9.277 
    gatsby-image: ^1.0.55 => 1.0.55 
    gatsby-link: ^1.6.32 => 1.6.46 
    gatsby-plugin-react-helmet: ^2.0.6 => 2.0.11 
    gatsby-plugin-react-next: ^1.0.11 => 1.0.11 
    gatsby-plugin-sharp: ^1.6.48 => 1.6.48 
    gatsby-plugin-styled-components: ^2.0.9 => 2.0.11 
    gatsby-source-filesystem: ^1.5.26 => 1.5.39 
    gatsby-source-wordpress: ^2.0.93 => 2.0.93 
    gatsby-transformer-remark: ^1.7.34 => 1.7.44 
    gatsby-transformer-sharp: ^1.6.27 => 1.6.27 
  npmGlobalPackages:
    gatsby-cli: 1.1.58
    gatsby: 1.9.76

```

### File contents (if changed)

`gatsby-config.js`: 

```
module.exports = {
	siteMetadata: {
		title: 'Superstylin',
		description: 'A Gatsby Starter with styled-components'
	},
	plugins: [
		'gatsby-plugin-styled-components',
		{
			resolve: 'gatsby-source-filesystem',
			options: {
				path: `${__dirname}/src/posts`,
				name: 'posts'
			}
		},
		'gatsby-transformer-remark',
		'gatsby-plugin-react-helmet',
		`gatsby-transformer-sharp`,
		`gatsby-plugin-sharp`,
		`gatsby-plugin-react-next`,
		{
			resolve: 'gatsby-source-filesystem',
			options: {
				name: 'img',
				path: `${__dirname}/src/assets/images`
			}
		},
		{
			resolve: 'gatsby-source-wordpress',
			options: {
				baseUrl: 'sjs.wmgdev001.com',
				protocol: 'http',
				hostingWPCOM: false,
				useACF: true
			}
		}
	]
};

```

**Comment by Khristophor** [comment]
@iamkratos are you able to view the options page content from the WordPress REST API endpoint? If you're using the v3 endpoint for the ACF to REST plugin it would live at `wp-json/acf/v3/options/options`, otherwise if you're using v2 it would be at `wp-json/acf/v2/options`

**Comment by iamkratos** [comment]
@Khristophor it's currently on v3. I just switched it to v2 and now it's showing up. Thanks.

**Comment by Blumed** [comment]
@iamkratos How did you change it from v3 to v2?

**Comment by Blumed** [comment]
nm I figured it out. If anyone else is new to this plugin here:
<img width="865" alt="Screen Shot 2019-03-25 at 10 16 25 PM" src="https://user-images.githubusercontent.com/2773888/54969374-d10de100-4f4b-11e9-81e3-660b8165815b.png">
