### ISSUE TITLE
Prismjs doesn't work on gatsby site that fetches wordpress posts

### ISSUE THREAD

**Issue by Radzam** [gatsbyjs/gatsby#7681]
I have prismjs installed and imported like this 

```
import Prism from 'prismjs'
require('prismjs/themes/prism-solarizedlight.css')
```

And have also tried doing this in the component that is displaying the content:
```
componentDidMount() {
    Prism.highlightAll()
  }
```

But it doesnt format my posts. I am using gatsby and fetching post content from wordpress using the gatsby-source-wordpress plugin. Any ideas? Cant it be because the content is inserted like this:

```
<div
  dangerouslySetInnerHTML={{
    __html: data.wp.content,
  }}
/>
```

**Comment by octalmage** [comment]
This is how I handle syntax highlighting: https://github.com/octalmage/jason.stallin.gs/blob/master/src/components/BlogContent.js#L11

**Comment by DSchau** [comment]
@Radzam I'm not sure I'd _expect_ Gatsby to handle this here.

I'm not really sure what the Wordpress API is returning for code snippets (as HTML), but I'm thinking that it's probably not in a format that PrismJS can highlight. If I recall correctly, Prism expects something like this

```html
<pre><code class="language-css">p { color: red }</code></pre>
```

so if the Wordpress content doesn't match that, Prism won't be able to highlight it.

Would you be able to share what a sample post looks like (as HTML)?

**Comment by wardpeet** [comment]
I'm closing as I think the issue can be fixed as @DSchau explained.

Feel free to reopen if needed
