### ISSUE TITLE
[gatsby-transformer-remark] Custom carousel component with optimised images using plugin-sharp

### ISSUE THREAD

**Issue by oorestisime** [gatsbyjs/gatsby#7686]
## Summary

In the blog post about custom components you suggest a carousel component. I think that building this would require support for using plugin-sharp from the props of custom components so that one could optimize those images as well.

### Motivation

A way for building an optimized carousel component, and possibly opening doors for much more

**Comment by agarrharr** [comment]
Is this the blog post? https://using-remark.gatsbyjs.org/custom-components/

**Comment by oorestisime** [comment]
yes sorry i forgot to add the link

**Comment by alacret** [comment]
No news on this? i'm trying to do it, i created a component <carousel></carousel>, the problem is that i can't find a way to send the img path into the component, passing them as props or childs, they are not changed by the gatsby engine, so, when i pass for example: `./media/picture-1.png` even using an <img> in the component, they won't get changed to be served

**Comment by alacret** [comment]
I test this: https://prestonrichey.com/blog/react-in-markdown/
But it does not work with gatsby v2

**Comment by maximetouroute** [comment]
Thank you oorestisime for your workaround. I've been struggling with the same issue (passing the image path or markdown folder path in the component). Will follow up on this

**Comment by maximetouroute** [comment]
I've tried a few things but couldn't come with a cleaner solution than your workaround. I'm currently using it on my personal website to generate a photo grid that can toggle a lightbox on click.

In my opinion the best solution to solve this would be to have access to the $path variable in graphQL queries made in custom components. Thus we could access all kind of assets related to a specific markdown page. I'm just a gatsby user and haven't really got time to check what happens under the hood yet so I don't know if this would make sense for a feature request.

In any case, it seems quite close of what gatsby-mdx is trying to offer https://github.com/ChristopherBiscardi/gatsby-mdx

**Comment by oorestisime** [comment]
right yes! i ll try and look if i can come up with something and get back here soon!

**Comment by oorestisime** [comment]
So thanks to pieh i ve managed to put in place https://github.com/oorestisime/gatsby-remark-rehype-images
it parses custom components uses plugin sharp on them and then passes the necessary props to the react component so that you can use gatsby-image on that.
i ve built an example site with it as well https://gatsby-remark-rehype-images.netlify.com/custom-component/

would love to hear comments from anyone interested

**Comment by oorestisime** [comment]
The plugin seems to do what is needed. i ll close this issue since its "fixed"

**Comment by snawbel** [comment]
Nice. I'm looking for something similar for `gatsby-mdx`: https://github.com/ChristopherBiscardi/gatsby-mdx/issues/218
