### ISSUE TITLE
Pages as pure functions

### ISSUE THREAD

**Issue by oliverbenns** [gatsbyjs/gatsby#769]
Decided to go through my site and update from extending React components to using pure functions. 

It's working well but nested pages are giving me this error: 
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in.
```

However I'm exporting it correctly and can't see any issues. See here: https://github.com/oliverbenns/oliverbenns.com/blob/remove-component-clutter/pages/work/chadstone/index.jsx

I updated to the latest version `0.12.39` to ensure it's not that.

PR here if it helps: https://github.com/oliverbenns/oliverbenns.com/pull/1

**Comment by KyleAMathews** [comment]
Hmmm dunno. Looks right to me as well. What happens if you change it back
to es6 class?

**Comment by oliverbenns** [comment]
Fixed it. [Sigh](https://github.com/oliverbenns/oliverbenns.com/commit/5d1106f2f7672ffffb1481ca6fa79265706c8954)
