### ISSUE TITLE
Unexpected String - commons.js when adding tiny-slider library

### ISSUE THREAD

**Issue by Bobeta** [gatsbyjs/gatsby#7695]
Tried with a clean install using create react app and no problems doing the following after adding the `tiny-slider` library:

```
import { tns } from 'tiny-slider/src/tiny-slider'
```

However when importing it to a clean Gatsbyjs install, I get the following error:

```
Uncaught SyntaxError: Unexpected token { commons.js:47211
```
which refers to:
```
import { raf } from './helpers/raf.js';
```

Any ideas on why the issue occurs and how to solve it?

**Comment by kakadiadarpan** [comment]
Hi @Bobeta, can you also provide the relevant environment information by running `gatsby info --clipboard`?

**Comment by Bobeta** [comment]
Sure @kakadiadarpan 
```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.5.0 - /usr/local/bin/node
    Yarn: 1.2.1 - /usr/local/bin/yarn
    npm: 6.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-rc.15
    gatsby-plugin-manifest: next => 2.0.2-rc.1
    gatsby-plugin-offline: next => 2.0.0-rc.6
    gatsby-plugin-react-helmet: next => 3.0.0-rc.1
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```

It seems to work fine using Gatsby v2 beta, but I'm having the issue above using latest Gatsby v1.

**Comment by kakadiadarpan** [comment]
Reproduction repo -> https://github.com/kakadiadarpan/gatsby-issue-7695

**Comment by m-allanson** [comment]
Gatsby v1 uses webpack v1, I'd guess that the way this library is packaged isn't compatible with webpack v1. 

Your best bet here is probably to update to Gatsby v2. Note that as the library depends on the `window` variable you'll need to load it in componentDidMount, something like:

```js
componentDidMount() {
    if (typeof window !== `undefined`) {
      const { tns } = require('tiny-slider/src/tiny-slider')
      this.slider = tns({
        container: '.my-slider',
        items: 3,
        slideBy: 'page',
        autoplay: true,
      })
    }
  }
```
