### ISSUE TITLE
Using single redux provider for head and pages

### ISSUE THREAD

**Issue by outofthisworld** [gatsbyjs/gatsby#7696]
## Summary

Pretty new to SSR and Gatsby, came straight from create-react-app, so excuse my negligence if this is a silly question. I have looked through the docs and done my best but can't seem to figure out a way to do this...

So essentially the question is about hooking up redux to gatsby, and having access to properties in the store from within the head section of a page so that I can render a different typography based upon the stores state.

The two things I have found in the docs are wrapping the root component in gatsby-browser.js (to hook up redux) and calling setHeadComponent (to add the typography to the head section) from within gatsby-ssr.js onRenderBody.

If you look at both the gatsby-browser.js and gatsby-ssr files below, it might be clearer what I am trying to achieve.  When any descendent component of `wrapRootComponent` dispatches an action to update state, it doesn't fire a re-render on the head component, I'm assuming because the components are rendered statically?

How can I make this work?

Thanks! 

### File contents (if changed)
`gatsby-config.js`: 
```
 siteMetadata: {
    title: 'Gatsby Default Starter',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    `gatsby-plugin-react-next`
  ]
```
`gatsby-browser.js`: 
```
import store from './src/utils/store';
import {Provider} from 'react-redux';
import React from 'react';

export const wrapRootComponent = ({Root}) => {
    return (props) =>{
        return (
            <Provider store={store}>
                <Root {...props}/>
            </Provider>
        );
    };
}
```
`gatsby-ssr.js`: 
```
import { TypographyStyle, GoogleFont } from 'react-typography';
import Typography from "typography";
import React from 'react';

import {themes} from './src/utils/theme';
import {Provider} from 'react-redux';
import store from './src/utils/store';
import {connect} from 'react-redux';

const Connected = connect(state=>({theme:state.theme}),null)((props)=>{
    console.log('re rendering typography')
    return <TypographyStyle typography={new Typography(themes[props.theme].typography)} />
})

export const onRenderBody = ({
    pathname,
    setHeadComponents
}) => {
    setHeadComponents([
        <Provider store={store}><Connected/></Provider>
    ])
}

```

**Comment by agarrharr** [comment]
You might be able to use [React Helmet](https://github.com/nfl/react-helmet) for this.

**Comment by outofthisworld** [comment]
@agarrharr Thanks for the pointer! Got it working with react-helmet.

**Comment by KyleAMathews** [comment]
Check out the using-redux example site as well https://github.com/gatsbyjs/gatsby/blob/master/examples/using-redux/README.md
