### ISSUE TITLE
Remove outdated section from CONTRIBUTING_ES.md

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#7697]
## Summary

Remove the _Herramientas de desarrollo_ section from https://github.com/gatsbyjs/gatsby/blob/master/translations/es/CONTRIBUTING_ES.md

Delete the following images:

- docs/docs/images/open-remote-dev-tools.png
- docs/docs/images/remote-dev-settings.png
- docs/docs/images/running-redux-devtools.png

### Basic example

The redux devtools were removed from Gatsby, with the English version of the docs being updated too. The Spanish translation of the docs should also be updated, and the images should be removed as they're no longer referenced anywhere.

### Motivation

Keep docs up to date. Remove unused files.

**Comment by Dipeshwagle** [comment]
I'll take care of it :)

**Comment by m-allanson** [comment]
@Dipeshwagle it looks like @k3rn31p4nic got there before you!

**Comment by k3rn31p4nic** [comment]
Oh, sorry @Dipeshwagle. I didn't saw the comments. Otherwise, I won't have made the PR. Thanks, anyways!
