### ISSUE TITLE
Is there possible to override getResourcesForPathname in loader.js?  

### ISSUE THREAD

**Issue by ichenzhifan** [gatsbyjs/gatsby#7698]
I want to format the url.  for example： the current url is "https://xxxx/abc.html", i hope it access the page: "https://xxxx/abc/index.html"

**Comment by pieh** [comment]
I don't think `getResourcesForPathname` here is what You want.

If you wan't change paths check https://next.gatsbyjs.org/docs/creating-and-modifying-pages/#modifying-pages-created-by-core-or-plugins - you will need to adjust for your needs.
