### ISSUE TITLE
[v2] CSS imported in one page is being applied globally.

### ISSUE THREAD

**Issue by morleytatro** [gatsbyjs/gatsby#7702]
Importing a stylesheet into one page component leads to those styles being applied globally. Please see the following repo for a quick example:
https://github.com/morleytatro/gatsby-2-css-test

**Comment by KyleAMathews** [comment]
Perhaps you want CSS modules? https://github.com/gatsbyjs/gatsby/tree/master/examples/using-css-modules 

This is how css works though by default. Gatsby with CSS modules will automatically scope your styles but otherwise, CSS is global by default.
