### ISSUE TITLE
How to write graphql queries to update data in strapi?

### ISSUE THREAD

**Issue by Mike-Van** [gatsbyjs/gatsby#7711]
I currently have a page on my gatsby site that query data from strapi backend to display. However, now i want gatsby to make update request back to strapi whenever it renders a template.
My situation here is that, this template will generate a page for each job record on strapi, and i want gatsby to update just one "is_published" boolean field everytime it renders one job page. Im new to gatsby, strapi, and graphql. So, im sorry if i write the query wrong or sth here. Please correct me. 
Here's the query that i write at the bottom of each job template. the query worked fine, but the mutation doesnt, mayb its the syntax or sth. I tried looking thru graphql documentation, but barely understand anything.

```
export const query = graphql`  
  query JobTemplate($id: String!) {
    strapiJob(id: {eq: $id}) {
      title
      What_we_are_looking_for
      What_you_will_do
    },
    strapiAboutus{
      title
      description
    }
  },
  mutation JobUpdate($id: String!) {
    updateJob(id: {eq: $id}, input: {
      is_published: "true"
    })
  }
`
```

**Comment by pieh** [comment]
Gatsby doesn't support mutation in build time graphql. You would need to hook into `onPostBuild` API hooke in `gatsby-node.js` and create graphql request manually there using any of Node.js graphql libraries (not through gatsby graphql)
