### ISSUE TITLE
[1.0] Use process.env with webpack define

### ISSUE THREAD

**Issue by tonyxiao** [gatsbyjs/gatsby#772]
Gatsby defines `process.env` via webpack plugin

https://github.com/gatsbyjs/gatsby/blob/1.0/packages/gatsby/lib/utils/webpack.config.js#L123

Seems that the value of this is fixed and cannot be overriden by user via `modifyWebpackConfig`?

**Comment by KyleAMathews** [comment]
I'm not 100% sure if this is how `DefinePlugin` works but I think if you define another plugin that overrides `process.env` it should work.

**Comment by tonyxiao** [comment]
It didn't, which is ok since I can just use a different name. But it should probably be documented to avoid confusion.

**Comment by KyleAMathews** [comment]
Probably just as well since if you override `process.env.NODE_ENV` wrong then a bunch of optimizations will break.

I want to copy create-react-app and automatically pull into webpack `GATSBY_*` env vars https://github.com/gatsbyjs/gatsby/issues/660#issuecomment-280184453
