### ISSUE TITLE
How to switch theme from child to parent?

### ISSUE THREAD

**Issue by pizza0502** [gatsbyjs/gatsby#7721]
## Summary
Hi, I want to implement theme switching for my gatsby v1 website. For some reason, my Header component is not sit inside layout/index.js. And the switching button is in the Header component.

How do I onclick the header and pass the states to layout/index.js?

In my component/Header:
`<ThemeSwitcher onClick={this.props.onClick}>{this.props.isModeToggle ? '🌙' : '☀️'}</ThemeSwitcher>`

In my page/Homepage:
```js
state = {
    isModeToggle: false,
    theme: themes.isLight
}
handleModeClick = () => {
    this.setState({
        isModeToggle: !this.state.isModeToggle,
        theme: this.state.isModeToggle ? themes.isLight : themes.isDark,
    });
  }
<Wrapper>
<Header onClick={this.handleModeClick} isModeToggle={this.state.isModeToggle} />
</Wrapper>
```

Can I pass the props and states to the layout/index.js children()?

**Comment by kakadiadarpan** [comment]
Hi @pizza0502

In your layout file, instead of this:

```jsx
export default ({ children }) // ... etc
```

do this:

```jsx
export default (defaultProps) {
  const myOwnProperties = { own: true };

  return (
    {props.children({ ...defaultProps, ...myOwnProperties })}
  );
}
```

This will solve your issue of passing data from layout to children, so we'll be closing this issue. Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem 👍
