### ISSUE TITLE
Add "waitForRouteChange" browser API

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#7734]
## Summary

It'd be handy for testing/UI code to be able to get a promise that's called when the next route change happens (or a route change to a particular page).

E.g. currently in the Cypress Gatsbygram test, we wait 200ms on page changes because we don't know how long it'll take for that page to change — which is inherently flaky + slows down running tests in fast environments e.g. locally.

Instead, tests should be able to write:

```js
import { waitForRouteChange } from "gatsby"

await waitForRouteChange()
```
and Gatsby would call the promise once that route had happened.

The API could also (maybe?) work like this:

```js
await waitForRouteChange(`/about`)
```

Though not sure that's necessary.

A common place this would be helpful in UIs is if you have some sort of menu/overlay/dropdown that you open to navigate somewhere. Currently most people just close the component on click but that's awkward as the thing will close immediately and there'll be a slight gap until the next page renders.

Much better if you could listen for the click, then immediately listen for the route change, and only close then.

### Motivation

This will make Cypress tests work better + offer way for components and other UI code to sync work to route changes.

/cc @davidbailey00 @m-allanson @pieh

**Comment by pieh** [comment]
I'm not sure about reliability of that for actual UI code - route change would often result in unmounting of all components (if page template component is changed on navigation), so it has potential for creating issues and confusion in this use case - maybe very simple non-cypress example would help with getting better grasp of how this could be used there.

For cypress tests it definitely would be great and that alone makes it fine to implement with focus on adding more cypress testing soon.

**Comment by KyleAMathews** [comment]
👍 cool yeah, adding this just for Cypress will be easy and good way to try out feature

**Comment by m-allanson** [comment]
It might be possible to work around this in Cypress. Their docs say that assertions _will automatically block, wait, and retry until it reaches that state_. 

https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Assertions
https://docs.cypress.io/guides/references/configuration.html#Timeouts
https://docs.cypress.io/guides/references/best-practices.html#Unnecessary-wait-for-cy-get

See #7746 for a trial

**Comment by davidbailey00** [comment]
@m-allanson I think the problem is that sometimes Cypress succeeds in finding the element but it gets clicked too soon, when the page is still in a different state. Also, sometimes it finds an element but refuses to click it because its styles haven't been applied, making it unclickable - it doesn't wait for the element to become visible in that situation.
