### ISSUE TITLE
Link's activeClassName not applied when linking to headers

### ISSUE THREAD

**Issue by chasemccoy** [gatsbyjs/gatsby#7737]
## Description

I use the `activeClassName` prop on the `Link` component to style the sidebar on my site and highlight the page the user is currently using. 

If I visit a link that ends in a hash (such as `/page#heading-within-page`), the `activeClassName` is not applied to the link. I would expect for it to be applied because the user is still on the same page and the link is still "active". 

### Environment

```

  System:
    OS: macOS 10.14
    CPU: x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.9.0 - ~/.nvm/versions/node/v8.9.0/bin/node
    Yarn: 1.9.4 - ~/.yarn/bin/yarn
    npm: 6.1.0 - ~/.nvm/versions/node/v8.9.0/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 61.0.2
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.0-rc.3 => 2.0.0-rc.3 
    gatsby-plugin-catch-links: ^2.0.2-beta.10 => 2.0.2-beta.10 
    gatsby-plugin-favicon: ^3.1.2 => 3.1.2 
    gatsby-plugin-google-analytics: next => 2.0.0-beta.5 
    gatsby-plugin-react-helmet: next => 3.0.0-beta.4 
    gatsby-plugin-sass: next => 2.0.0-beta.10 
    gatsby-plugin-sharp: ^1.6.48 => 1.6.48 
    gatsby-plugin-styled-components: next => 3.0.0-beta.3 
    gatsby-plugin-typography: next => 2.2.0-beta.3 
    gatsby-remark-autolink-headers: ^1.4.18 => 1.4.19 
    gatsby-remark-component: ^1.1.3 => 1.1.3 
    gatsby-remark-copy-linked-files: next => 2.0.0-beta.3 
    gatsby-remark-external-links: ^0.0.4 => 0.0.4 
    gatsby-remark-images: ^1.5.67 => 1.5.67 
    gatsby-remark-smartypants: next => 2.0.0-beta.3 
    gatsby-source-filesystem: next => 2.0.1-beta.10 
    gatsby-transformer-remark: next => 2.1.1-beta.6 
  npmGlobalPackages:
    gatsby-cli: 2.0.0-beta.13
```

**Comment by chasemccoy** [comment]
@m-allanson the fix that went out earlier for the double slash problem fixed one of my issues, but this still remains

**Comment by chasemccoy** [comment]
Btw, this is happening both in dev and prod

**Comment by imshuffling** [comment]
I think I'm having a similar issue on nested Links.

```
...
        <Link className="logo" to="/"><img src={logo} alt="Logo" /></Link>
          <ul id="mainnav">
            {data.map((item, i) =>
              <li key={i} className={item.childPages ? 'has-child-wrap' : null}>
                <Link activeClassName="active top hello" className={item.childPages ? 'has-child' : null} to={'/' + item.slug}>{item.menuTitle}</Link>
                {item.childPages !== null &&
                  <Nav nav={item.childPages} />
                }
              </li>
            )}
          </ul>
          <ul id="sub-menu">
            <li><Link activeClassName="active" className="icon resources" to='/resources'>RESOURCES</Link></li>
            <li><Link activeClassName="active" className="icon mail" to='/contact'>CONTACT</Link></li>
            <li><Link className="icon welcome" to='/'>WELCOME</Link></li>
          </ul>
      </Menu>
    )
  }
}

const Nav = ({ nav }) => {
    return (
      <ul className="children">
        {nav.map((node) => (
          <li key={node.id}>
            <Link exact activeClassName="active child" to={'/' + node.slug}>{node.menuTitle}</Link>
          </li>
        ))}
      </ul>
    )
}


```


activeClassName="active top hello" is not being applied anymore since upgrading to the latest v2.

is activeClassName not supporting in reach router?

**Comment by imshuffling** [comment]
Manage to solved this in the end.

```
...
const isPartiallyActive = ({
  isPartiallyCurrent
}) => {
  return isPartiallyCurrent
    ? { className: "has-child active top" }
    : null
}
...
```

```
...
          <ul id="mainnav">
            {data.map((item, i) =>
              <li key={i} className={item.childPages ? 'has-child-wrap' : null}>
                <Link getProps={isPartiallyActive} className={item.childPages ? 'has-child' : null} to={'/' + item.slug}>{item.menuTitle}</Link>
                {item.childPages !== null &&
                  <Nav nav={item.childPages} />
                }
              </li>
            )}
          </ul>
...

```

**Comment by kakadiadarpan** [comment]
Hi, @chasemccoy @imshuffling would it be possible for you to provide a repository we can reproduce this?

**Comment by stefanprobst** [comment]
Would this be resolved by explicitly mentioning reach-router `Link`'s `getProps` in the `gatsby-link` docs and showing how to use it?

**Comment by intelligence** [comment]
Seeing this issue aswell. While browsing the site, activeClassName will get applied. But loading any page (besides index) directly and it will append "/" to the slug and activeClassName won't get applied.

**Comment by sylvhama** [comment]
@intelligence are you using `gatsby-plugin-offline`? I've noticed that removing it would not reproduce the issue in my project.

**Comment by sylvhama** [comment]
Sorry my previous comment was incomplete. When combining Link's `avtiveStyle` or `activeClassName` with `gatsby-plugin-offline` and with `wrapPageElement` from gatsby-browser / gatsby-ssr then the active style won't be shown when refreshing the page. I guess it's related to the fact the Service Worker will cache the nav bar when all links are inactive. 

Demo: https://gatsby-link-active-test.netlify.com/
Repo: https://github.com/sylvhama/gatsby-link-active-test

**Comment by macandcheese** [comment]
This does seem like a regression, previously 'gatsby-link' handled these cases very easily with the 'exact' attribute. Now extra logic is needed to check for match between, for instance, window.location and anchor link href props. Additionally handling partial URL matches, and trailing #header sections, also needs additional custom logic in addition to detection on page load.

**Comment by macandcheese** [comment]
This does seem like a regression from `gatsby-link`'s 'exact' attribute, as neither 'isPartiallyCurrent' nor 'isCurrent' completely match the functionality. 

For instance, take a URL structure of `url.com/this`, that can have child pages that reside at `url.com/this/something`

Using 'isPartiallyCurrent' while on `url.com/this/something` will assign an active class to both my current page, and the parent `url.com/this` link, because of the partial match.

Using 'isCurrent' will not allow me to handle both `url.com/this` and `url.com/this/` because the trailing slash causes an incomplete match.

Obviously this is solvable with additional custom logic but seems like a step backwards in "out of the box" functionality of <Link />

**Comment by MikSDigital** [comment]
Hello @sylvhama !
Did you manage applying active class to direct visiting page?
https://gatsby-link-active-test.netlify.com/page-2/

**Comment by sylvhama** [comment]
@MikSDigital My dirty fix: https://github.com/sylvhama/shamann-gatsby/blob/master/src/components/Layout.js#L72

**Comment by MikSDigital** [comment]
@sylvhama , thanks for quick reply!

I have used 
    <Link to="/contact"
    **partiallyActive={true}**
    className={HeaderStyles.navItem}
    activeStyle={activeStyles}>
    Contact
    </Link>
And now all active links is "active" even if visited directly
