### ISSUE TITLE
Out-of-date tutorial files in /docs/tutorial

### ISSUE THREAD

**Issue by robinmetral** [gatsbyjs/gatsby#7742]
## Description

I've found a broken link in the Gatsby tutorials (Part 0) and I wanted to fix it.

I clicked on the "edit this page on GitHub" link at the bottom of the page, but found that [the Github repo version](https://github.com/gatsbyjs/gatsby/blob/master/docs/tutorial/part-zero/index.md) isn't the same as [the live version](https://www.gatsbyjs.org/tutorial/part-zero/).

### Expected result

It would be great to update these files so that I and others can contribute! :slightly_smiling_face:

**Comment by robinmetral** [comment]
Thanks, sorry I didn't see this! So would it still make sense to make a PR for the v1 docs?

**Comment by LeKoArts** [comment]
No problem! Uhmmm, I don’t know but I'd just create the PR and see what happens 😅

**Comment by LeKoArts** [comment]
👍🏻
