### ISSUE TITLE
Is there a way to access Heroku config vars

### ISSUE THREAD

**Issue by alenkis** [gatsbyjs/gatsby#7751]
I'm deploying gatsby site to Heroku and I'm trying not to version control my dotenv files. I have followed instructions in https://www.gatsbyjs.org/docs/deploy-gatsby/#heroku

Adding environment variables in .env.production works as expected, I can access variables through `process.env` inside my front end code, but is there a way to access environment variables that were set with Heroku CLI (e.g. heroku config:set FOO=bar) so I can avoid committing .env.production?

Thank you

**Comment by kayandrae07** [comment]
When you set environment variables on Heroku, you should be able to access them using `process.env`. It's not a Gatsby thing, it's a node thing. the env files serve as a friendlier approach for systems where setting env variables can be painful. So, it should work

**Comment by KyleAMathews** [comment]
Checkout https://www.gatsbyjs.org/docs/environment-variables/
