### ISSUE TITLE
Starter showcase - add a submit to starter showcase button that links to instructions

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#7753]
@fk thought you might want to address this before @amberleyromo gets to #7731

Edit from the future: Oh wait, nevermind. #7731 is about the detail page. So this can be done regardless of that issues's status.

**Comment by shannonbux** [comment]
Hi @amberleyromo an update here based on discussion between @fk and myself!

For the design of this button, we can just imitate the "submit to site showcase" button.

**Comment by amberleyromo** [comment]
Closed via #8602
