### ISSUE TITLE
Starter showcase - tweak title

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#7754]
@fk probably ought to be addressed before @amberleyromo starts #7731.

Edit from the future: Oh wait, nevermind. #7731 is about the detail page. So this can be done regardless of that issues's status.

**Comment by fk** [comment]
Hey Shannon, could you add an issue description here? 🙏

**Comment by fk** [comment]
![image](https://user-images.githubusercontent.com/21834/44910305-02f6f600-ad23-11e8-9295-9f71b4f00bdf.png)

^ I'm guessing you're not refering to this, right?

**Comment by shannonbux** [comment]
@fk correct. I think the number of starter doesn't need to be the biggest phrase on the page.

Also, I showed the site showcase and starter showcase to my mentor yesterday and they advised that people might have trouble distinguishing between the two. They suggested maybe calling these a Theme Library so the name is really different too (because site showcase and starter showcase are semantically similar).

I think the yellow color and a title would be enough to distinguish between the two for now and then we can address later if there are more problems people have with recognizing the difference. (Someone also just submitted their starter to the site showcase, so I'll need to figure out how to make sure those kinds of submissions don't get merged, which is another matter, but a little related).

**Comment by KyleAMathews** [comment]
Perhaps the title could just be "Gatsby Starters"?

**Comment by shannonbux** [comment]
Ok, here's the decision based off of a combination of @KyleAMathews' suggestion and conversation btw @fk and myself today:

Let's change "All 60 Starters" to “Gatsby Starters (60)”

And we'll wait until [EPIC] v2.0 starter showcase to come back to removing filter & refine rectangular box on desktop and doing global title redesigns

**Comment by fk** [comment]
👍
