### ISSUE TITLE
Unable to change node relations without de-creating and re-creating nodes

### ISSUE THREAD

**Issue by isabellachen** [gatsbyjs/gatsby#7755]
###Summary

I am creating an eventbrite-source-plugin and I want to form relations between an event and the event's venue, following (this helpful thread)[https://github.com/gatsbyjs/gatsby/issues/3793]. 

After I create my relations, I recompile the app expecting to see the new relations. Unfortunately, the old relations are retained.

###Relevant information

I made a screen cap to demo the problem...
https://youtu.be/HpwVtZXenpQ

I have some code in sourceNodes(). I want to add on every event node the 'venueNODE' prop. I set it to 'foo' the first time, compile the app, eventNode[venueNODE] is foo when I query it. However, if I set it to 'bar' and recompile, the prop is still set to 'foo'. I have to comment out the line that calls createNode(), recompile to de-create the nodes, and then compile again so now the venue__NODE prop is set to 'bar'.

Is this an expected behaviour or was it documented somewhere? Seems a bit unintuitive... I was stuck for hours trying to figure out why I wasn't able to alter the relations. 

      await Promise.all(processedEntries).then(() => {
        Object.keys(nodes).forEach(entity => {
          if (entity === 'events') {
            nodes[entity].forEach(node => {
              node['venue__NODE'] = 'foo'
            })
          }
          nodes[entity].forEach(entry => createNode(entry))
        })
      })

###Environment (if relevant)

System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.1.0 - ~/.nvm/versions/node/v10.1.0/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 6.0.1 - ~/.nvm/versions/node/v10.1.0/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Safari: 11.1.2
  npmPackages:
    gatsby-plugin-sharp: ^2.0.0-beta.7 => 2.0.0-rc.2
  npmGlobalPackages:
    gatsby-cli: 1.1.58

###File contents (if changed)

gatsby-config.js: N/A 
package.json: N/A 
gatsby-node.js: 

    const fetch = require(`./fetch`)
    const _ = require('lodash')
    const { defaultEntities } = require('./defaultEntities')
    const { linkEventWithVenue } = require('./createNodeRelations')
    const processEntry = require('./processEntry')
    
    // Add prefix for Eventbrite
    const typePrefix = `Eventbrite`
    const makeTypeName = type => _.upperFirst(_.camelCase(`${typePrefix} ${type}`))
    
    exports.sourceNodes = async (
      { actions, getNode, store, cache, createNodeId },
      options
    ) => {
      const { createNode } = actions
      const { organizationId, accessToken, entities = [] } = options
    
      // Merge default entities with configured ones
      const entitiesToFetch = [...new Set([...defaultEntities, ...entities])]
    
      // Fetch all defined entities and create nodes
      const nodes = {}
    
      const processedEntries = entitiesToFetch.map(entity => {
        return fetch({ organizationId, accessToken, entity })
          .then(entries =>
            entries[entity].map(entry => processEntry(entry, entity, createNodeId))
          )
          .then(entries => (nodes[entity] = entries))
      })
    
      await Promise.all(processedEntries).then(() => {
        Object.keys(nodes).forEach(entity => {
          if (entity === 'events') {
            nodes[entity].forEach(node => {          
              linkEventWithVenue(nodes, entity)
            })
          }
          nodes[entity].forEach(entry => createNode(entry))
        })
      })
    }
    

gatsby-browser.js: N/A 
gatsby-ssr.js: N/A

**Comment by isabellachen** [comment]
@pieh How would I go about updating the `node.internal.contentDigest`? 

```
const fetch = require(`./fetch`)
const _ = require('lodash')
const { defaultEntities } = require('./defaultEntities')
const { linkEventWithVenue } = require('./createNodeRelations')
const processEntry = require('./processEntry')

exports.sourceNodes = async (
  { actions, getNode, store, cache, createNodeId },
  options
) => {
  const { createNode } = actions
  const { organizationId, accessToken, entities = [] } = options

  // Merge default entities with configured ones
  const entitiesToFetch = [...new Set([...defaultEntities, ...entities])]

  // Fetch all defined entities and create nodes
  const nodes = {}

  const processedEntries = entitiesToFetch.map(entity => {
    return fetch({ organizationId, accessToken, entity })
      .then(entries =>
        entries[entity].map(entry => processEntry(entry, entity, createNodeId))
      )
      .then(entries => (nodes[entity] = entries))
  })

  await Promise.all(processedEntries).then(() => {
    Object.keys(nodes).forEach(entity => {
      if (entity === 'events') {
        nodes[entity].forEach(node => {
          linkEventWithVenue(nodes, entity)
        })
      }
      nodes[entity].forEach(entry => createNode(entry))
    })
  })
}
```

**Comment by KyleAMathews** [comment]
@isabellachen when you create the new version of the node, you re-calculate the content digest. Gatsby will then detect that the node has changed.

**Comment by isabellachen** [comment]
I realised all I had to do was delete the .cache ....

**Comment by KyleAMathews** [comment]
Clearing the cache works but it's a blunt way to do things. If your plugin updates old things properly, clearing the cache isn't necessary.
