### ISSUE TITLE
[v2] Gatsby loading same styles twice

### ISSUE THREAD

**Issue by outofthisworld** [gatsbyjs/gatsby#7765]
In gatsby I have two pages (index and page2) which share a common layout this layout imports a layout.css file.

When visiting the index page for the first time I see that the styles from the layout.css file are inlined 
`<style data-href="/component---src-pages-index-js.464c799ae291bbeb7632.css">...styles</style>`

But also that page2 has its own stylesheet generated and is included as a link tag on the index page also.
`<link rel="stylesheet" type="text/css" href="/component---src-pages-page-2-js.464c799ae291bbeb7632.css">`

When inspecting the dom, both these files are exactly the same (same content hashes) and also override styles of each other.

I'm new to gatsby and trying to understand how everything is being built and what's happening in this circumstance, so this may very well be intentional.. but could someone explain what's happening here and why this is necessary?

Thanks!

### File contents (if changed)
`gatsby-config.js`:
```
module.exports = {
  siteMetadata: {
    title: 'Gatsby Default Starter',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    {
      resolve:'gatsby-source-filesystem',
      options:{
        path:`${__dirname}/src`
      }
    },
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: 'gatsby-starter-default',
        short_name: 'starter',
        start_url: '/',
        background_color: '#663399',
        theme_color: '#663399',
        display: 'minimal-ui',
        icon: 'src/images/gatsby-icon.png', // This path is relative to the root of the site.
      },
    },
    `gatsby-transformer-remark`,
    'gatsby-plugin-offline',
  ],
}

```

**Comment by azdanov** [comment]
Similar issue to https://github.com/gatsbyjs/gatsby/issues/7517.

**Comment by l0co** [comment]
@azdanov It doesn't seem to be similar to #7517, which is about duplicating the same css classes on single page, while this one is about forcefully embedding the same (potentially large) stylesheets on each website page.

**Comment by pringshia** [comment]
@l0co - ever figure out a solution to this?

**Comment by l0co** [comment]
@pringshia It was some time ago so I don't remember exactly but AFAIR I completely disabled embedding stylesheets in HTML because it looks a bit like a nonsense.

See here https://github.com/gatsbyjs/gatsby/issues/1526#issuecomment-433347822
