### ISSUE TITLE
[v2] GraphQL results sorting

### ISSUE THREAD

**Issue by oltodo** [gatsbyjs/gatsby#7769]
When I've migrated to the v2 of Gatsby, I get some troubles. The project I'm working on is deployed on a pool of multiple load-balancing servers. So it's builded as many times as there are servers. But I realized that each of this builds wasn't exactly the same. One of the `public`'s folder generated files didn't have the same hash from one server to another.

So by seeing a diff on this files — supposed to be the same — I realized they contain the page list which were not in the same order.

Rummaging a little I came to understand that my GraphQL query, executed into the `createPages` function of the `gatsby-node.js` file, didn't return the data in the same order from once to another. So I had to add a `sort` filter into the query to ensure always getting the same order.

I wonder if it seems to be normal that the same query, with the same data, result with a different order for each execution when the `sort` filter is not specified.

__Edit:__

Actually adding a `sort` filter on my GraphQL query didn't totally fix the problem. It correctly fixed the order into `pages` reducer but not into the `jsonDataPaths`. After investigating it seems to be due to async execution of the `queueRunner` tasks into the [query-queue.js](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/internal-plugins/query-runner/query-queue.js#L45) file. How do you think it can be resolved?

**Comment by pieh** [comment]
If sort isn't specified, data order will be same as node created by plugins. It can differ between independent builds if:
- source plugin pull data and create data nodes in parallel
- you already have cache in one of build servers in one of your server

What source plugin do you use?

**Comment by oltodo** [comment]
Closed in favor of https://github.com/gatsbyjs/gatsby/issues/7836
