### ISSUE TITLE
[1.0] Use Redux for managing Gatsby's internal server state

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#777]
I've been prototyping using Redux for managing Gatsby's internal server/cli state to replace the somewhat ad-hoc data management code.

I needed to refactor this code anyways to get data hot reloading working (#1 requested feature for people experimenting with Gatsby v1) and figured I'd try this out.

I'm about 1/2 way through ripping out the old code and replacing it with Redux but I've very positive about the direction. The data flows are much simpler, much more testable, and it's suggesting very positive changes to a few Gatsby APIs.

And the nice thing about Redux is since the community is huge, like with GraphQL, we'll get freebies by adopting Redux.

E.g. built-in devtools support.

This screenshot is the Redux devtools looking at an action from my Gatsby blog where I opened a markdown file, made a small change, and saved it and this is the resulting state diff.

<img width="1070" alt="screen shot 2017-04-03 at 11 56 48 pm" src="https://cloud.githubusercontent.com/assets/71047/24640982/805e696a-18c9-11e7-893a-7bc6bea8d906.png">

In addition to the nice code improvements plus our now built-in supercharged debugger, using Redux will make Gatsby's code base feel very approachable to many of its users who will have experience using Redux on client-side apps.

**Comment by jthiesse** [comment]
Would the GraphQL plugins populate the store and the components receive data via react-redux or would GraphQL data continue to be part of each component?

**Comment by KyleAMathews** [comment]
@jthiesse redux is only being used on the server piece not in the browser. It'll be invisible to users unless you're working on core code or some types of plugins.

**Comment by rogovdm** [comment]
Check redux-query lib — it's so awesome. 

https://github.com/amplitude/redux-query

**Comment by KyleAMathews** [comment]
PR is up! Would love some reviews from people more familiar with Redux https://github.com/gatsbyjs/gatsby/pull/788

**Comment by danielo515** [comment]
Why don't you want to include redux as part of the generated app? There are situations where it makes a lot of sense

**Comment by KyleAMathews** [comment]
@danielo515 you're free to add Redux if it's needed for your site... why would we want to always include it?

**Comment by KyleAMathews** [comment]
Ah gotcha! Yeah, that would be cool. This would be perfect for a Gatsby v1 plugin https://www.gatsbyjs.org/docs/plugins/

**Comment by danielo515** [comment]
Nice to hear that ! Are you going to open an specific issue for that ? I would like to subscribe to it

**Comment by KyleAMathews** [comment]
It's not something I'm going to work on anytime soon but this would be an
excellent community plugin to get going! If you want to take it on, open an
issue and I can point out the APIs you need and help with any roadblocks
you hit.

**Comment by KyleAMathews** [comment]
This is now merged
