### ISSUE TITLE
Upgrading to v2 - stuck at ImageSharp

### ISSUE THREAD

**Issue by b0gd4n** [gatsbyjs/gatsby#7770]
I am in the process of upgrading a website from Gatsby v1 to v2 and I am stuck at getting the `imageSharp` queries to work.
Can someone please let me know what I need to do to the following piece of code to make it work (I've changed `sizes` to `fluid` and `GatsbyImageSharpSizes_withWebp_tracedSVG` to `GatsbyImageSharpFluid_withWebp_tracedSVG` already):

```
imageone: imageSharp(id: { regex: "/imageone/" }) {
  fluid(maxWidth: 2000, quality: 100, traceSVG: {
    color: "#2E4CD7"
  }) {
    ...GatsbyImageSharpFluid_withWebp_tracedSVG
  }
}
imagetwo: imageSharp(id: { regex: "/imagetwo/" }) {
  fluid(maxWidth: 2000, quality: 100, traceSVG: {
    color: "#2E4CD7"
  }) {
    ...GatsbyImageSharpFluid_withWebp_tracedSVG
  }
}
```
These are used in `Img` elements: 
```
<Img fluid={data.imageone.fluid} title={`imageone`} />
<Img fluid={data.imagetwo.fluid} title={`imagetwo`} />
```

**Comment by pieh** [comment]
https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#dont-query-nodes-by-id
