### ISSUE TITLE
Source maps not working 

### ISSUE THREAD

**Issue by 0x80** [gatsbyjs/gatsby#778]
If I set a breakpoint, the Chrome devtools show me the transpiled source. Are source maps not enabled by default? 

I've created a default starter en run `gatsby develop`.

**Comment by KyleAMathews** [comment]
Yes they're enabled in the webpack config so should be working.

**Comment by 0x80** [comment]
I don't get it. I tried running `gatsby develop` on the master branch of gatsby-starter-blog. Putting a `debugger` statement at the start of the _template render function gives me the following output in the devtools:

<img width="488" alt="screenshot 2017-04-06 09 58 44" src="https://cloud.githubusercontent.com/assets/1193520/24743824/fe7a52ea-1aaf-11e7-8249-593ce9f3541d.png">

**Comment by KyleAMathews** [comment]
Apparently we should be using cheap-module-source-map https://github.com/webpack/webpack/issues/2145#issuecomment-294361203

Could you test changing the webpack config to see if that solves your problems?

**Comment by 0x80** [comment]
How do I change it from my project?

I tried the code below in gatsby-node.js, but that doesn't work and also prints `devtool was undefined` so I guess that's not the way to go.

```javascript
exports.modifyWebpackConfig = function (config, stage) {
  console.log('devtool was', config.devtool)
  config.devtool = 'cheap-module-source-map'
  return config
}
```

**Comment by 0x80** [comment]
Ah I see the config was in config._config. 

```javascript
config._config.devtool = 'cheap-module-source-map'
```

This works for me. Chrome is now showing the original source.

**Comment by KyleAMathews** [comment]
Out in 0.12.45!

**Comment by mdotasia** [comment]
@0x80 How did you attach debugger to `gatsby develop`?

**Comment by m-allanson** [comment]
@mdotasia it looks like he's using Chrome built in [client-side debugging tools](https://developers.google.com/web/tools/chrome-devtools/javascript/).

If you use Visual Studio Code, you can use the following debug config to attach a debugger to the `gatsby develop` Node process: https://gist.github.com/pieh/c6a57b53bb4648344be53ea8b37add82

**Comment by joebentaylor1995** [comment]
Still seeing this issue

using `gatsby": "^3.13.0"`
