### ISSUE TITLE
Starter showcase - indicate v1 / v2 compatibility

### ISSUE THREAD

**Issue by ductiletoaster** [gatsbyjs/gatsby#7785]
## Summary
After reviewing some of the community starters I found that many of them are specific to gatsby v1. As a result of this I had two questions.

1) Should we not specify in [https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/gatsby-starters.md](gatsby-starters) that many of the below starts are for version 1 only? 

2) Also is there a formal process for submitting version 2 starters?
https://next.gatsbyjs.org/docs/submit-to-starter-showcase/

Let me know how I can contribute if this isn't already planned. Thank you!

**Comment by LeKoArts** [comment]
I commented somewhere else that I'd propose to use a filter for v1 and v2 on the sidebar and set v2 by default. This way people could upgrade by themselves and the creators have some time to upgrade. After some time the v1 starters would be removed + the filter option.

**Comment by shannonbux** [comment]
In [EPIC] v2.0 Starter Showcase, we have planned to use Peril to automate
some of the process of evaluating submissions to the Starter Showcase. I
wonder if we can just verify whether or not a starter is using Gatsby v2.

@fk, do you remember why we took out the v2 / v1 little pills on the index
page? We discussed this and this was the conclusion:
notes from Kyle:
I think just putting a little grey indicator showing v1 or v2 is fine
I agree making it red is heavy handed since v1 isn’t broken per se

**Comment by shannonbux** [comment]
Ok final decision on this: 

- Index page to include a “Gatsby v1” “Gatsby v2” pill
- Detail page to include the same pill  (@fk I guess we do need an update to the Figma design to include this)


@amberleyromo Is there a way to check v2/v1 compatibility along with dependencies? Gatsby version is in package.json along with other dependencies, which we’re already checking for. 

@KyleAMathews is there a reason anyone would need granular version info on the starter detail page (aka v1.98.12 or something)

**Comment by riencoertjens** [comment]
coming from #7998 while changing the layout of the showcase items I added a v2 label in the new layout. Adding the label to the bottom row adds a bit too much clutter down there for my liking and both the starter name and description occasionally take up too much space to fit the label. so unless the author has an unreasonably long name this seemed the best place to put it. I'll make a pr if this is ok?
![screen shot 2018-09-13 at 15 09 36](https://user-images.githubusercontent.com/36336875/45490485-84a94380-b767-11e8-8d27-b1216517fd77.png)
/cc @fk

**Comment by shannonbux** [comment]
I'm ok with that as long as @fk is!

**Comment by kakadiadarpan** [comment]
@fk would you be okay with the suggestions provided by @riencoertjens?
