### ISSUE TITLE
Update gatsby-transformer-excel's default options

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#7790]
## Summary

gatsby-transformer-excel is essentially a wrapper around the excellent js-xlsx library. Currently one of the default transformer options is the opposite of the equivalent option in js-xlsx. This seems confusing, so it should probably be changed.

Refs: https://github.com/gatsbyjs/gatsby/pull/7780

### Basic example

If you don't specify the `raw` or `rawOutput` option, a value of `true` will be used in the underlying js-xlsx function. This is opposite the library's default value of `false`.

### Motivation

Reverting the default option is a breaking change, but means that the transformer plugin matches the underlying library defaults.

**Comment by mikelax** [comment]
As I was going through the js-xlsx lib and the gatsby plugin I actually felt the default for the `raw` option **should have been** `true`, glad to hear it will be fixed in the underlying lib.

Sounds like once that change is in we'll just need to update to the newest version.

**Comment by SheetJSDev** [comment]
@mikelax @m-allanson `xlsx` version 0.14.0 flipped the default.

**Comment by mikelax** [comment]
great, thanks @SheetJSDev . @m-allanson I'll take this ticket and create a quick PR for this.
