### ISSUE TITLE
Try using CircleCI

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#7792]
With https://github.com/gatsbyjs/gatsby/pull/7433 and https://github.com/gatsbyjs/gatsby/pull/7784, CI runs on Travis are getting longer and longer.

CircleCI lets open source use more containers I believe so tests should be faster. I'll try setting it up as well so we can check this out.

**Comment by KyleAMathews** [comment]
A community member on discord pointed out their circleci config https://github.com/axe312ger/gatsby-starter-collaborative-app/blob/master/.circleci/config.yml#L87-L94

**Comment by m-allanson** [comment]
I took a run at updating the existing Travis config. WIP but looks like it could work out: https://github.com/m-allanson/gatsby/pull/17

**Comment by humphreybc** [comment]
If it's any help, we use CircleCI too. [Here's our config](https://github.com/heydovetail/website/blob/master/.circleci/config.yml).
