### ISSUE TITLE
Error for EmitFile when importing files

### ISSUE THREAD

**Issue by sparklesam** [gatsbyjs/gatsby#7794]
## Description

I have `Module build failed: Error: File Loader emitFile is required from module system` error when `gatsby-develop` I was only trying to import static image file to my Gatsby index page.

### Steps to reproduce

Error mainly pointed to two npm plugin I installed, file-loader and url-loader for loading files and parsing url. 

### Expected result

Able to import static image from my src/images folder.

### Actual result

Module build failed: Error: File Loader emitFile is required from module system
at Object.loader (/node_modules/file-loader/dist/index.js:31:29)
    at Object.loader (/node_modules/url-loader/dist/index.js:76:19)

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.8.0 - /usr/local/bin/node
    npm: 6.2.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 62.0
    Safari: 11.1.2
  npmPackages:
    gatsby: ^1.9.277 => 1.9.277 
    gatsby-image: ^1.0.55 => 1.0.55 
    gatsby-link: ^1.6.46 => 1.6.46 
    gatsby-plugin-catch-links: ^1.0.24 => 1.0.24 
    gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11 
    gatsby-plugin-resolve-src: ^1.1.4 => 1.1.4 
    gatsby-plugin-sharp: ^1.6.48 => 1.6.48 
    gatsby-plugin-typography: ^1.7.19 => 1.7.19 
    gatsby-remark-attr: 0.0.1 => 0.0.1 
    gatsby-remark-copy-linked-files: ^1.5.37 => 1.5.37 
    gatsby-remark-emoji: 0.0.2 => 0.0.2 
    gatsby-remark-images: ^1.5.67 => 1.5.67 
    gatsby-source-filesystem: ^1.5.39 => 1.5.39 
    gatsby-transformer-remark: ^1.7.44 => 1.7.44 
    gatsby-transformer-sharp: ^1.6.27 => 1.6.27 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

**Comment by kakadiadarpan** [comment]
Hi @sparklesam, it would be great if you can go through the guide of how to [Add Images, Fonts, and Files](https://www.gatsbyjs.org/docs/adding-images-fonts-files/). Let us know if that works for you by adding a comment 👍

**Comment by Jamsek-m** [comment]
Hello,
I am having the same problem - I looked at your link, but this is what I have already tried to do without success.

Altough I am using typescript, if that makes a difference.

**Comment by KyleAMathews** [comment]
@Jamsek-m this sounds potentially like an NPM install error. Could you try removing `node_modules` and any lock file and reinstalling?

**Comment by Jamsek-m** [comment]
@KyleAMathews I have tried that - just now I also tried to replace typescript with javascript (and again deleting node_modules and lock file) and I get the same error

**Comment by KyleAMathews** [comment]
Can you reproduce this with a new sure built from a starter?

**Comment by faahim** [comment]
I have the same issue. I get the same error every time I try to import images. But I've noticed something interesting. If you pass your image through an optimizer like TinyPng and then try to import, it works just fine! It's almost as if a certain type of image importing works and others doesn't. A little weird, haha!

**Comment by faahim** [comment]
One more thing, Looking at my log of `npm install`, I found this: `url-loader@1.1.1 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.`

Could missing dependency of url-loader be the reason of the issue? :thinking:

**Comment by KyleAMathews** [comment]
@faahim that's a good theory! It could be yeah that url-loader can't find a module to import from webpack. Can you create a reproduction of this issue that we can look at?

**Comment by faahim** [comment]
I just tried installing the peer dependencies manually, and messed up the whole thing! Now my `gatsby develop` cammand exits with 
```
error There was a problem loading the local develop command. Gatsby may not be installed. Perhaps you need to run "npm install"?

Error: Cannot find module 'webpack/lib/removeAndDo'
```

I'm going to try and fix this. I can create a repo where the issue is reproducible once I can get it running. :slightly_smiling_face: @KyleAMathews

**Comment by faahim** [comment]
Hi @KyleAMathews ,

I've created this repo [here](https://github.com/faahim/image-import-issue). Try importing and rendering some image anywhere, you should get the error. Sorry for the scary cats! :slightly_smiling_face:

**Comment by dkataiev** [comment]
Having the same problem. 
Tried cleaning my node_modules several times.

**Comment by sparklesam** [comment]
Some update: I think this issue is quite weird, i have a SVG that could be successfully imported in a css file using url(), but switching to another svg would result in the  error. 

Currently my workaround is to directly put the image files in Public folder, commit it to the github & netlify and directly import the image with a absolute path.

**Comment by Jamsek-m** [comment]
@KyleAMathews Without changing my project at all, I created new gatsby project from default starter, run 'gatsby develop', closed it, then tried to run my project again and it worked. I don't know whether you can find this information useful, but in my case this solved the problem.

**Comment by linardsb** [comment]
Do I need to really need to add every single image (i have 8) like so `import logo from`? 
I get the error `Module build failed: Error: emitFile is required from module system` when including image as so `<img src={require('../img/logo-figma.png')} width="50"/>`

**Comment by johntiger1** [comment]
having this issue, but i think i should have some type of fix in a few days, and i'll report back
