### ISSUE TITLE
How to not expose API Keys on the client side?

### ISSUE THREAD

**Issue by rehat101** [gatsbyjs/gatsby#7796]
I have keys which I use to make API calls to AWS. How can I utilize the keys without exposing on the client side? Also, I'll also be hosting my site on a private GH repo with all that in mind I was thinking to store it on a vault and just asynchronously call it.

**Comment by KyleAMathews** [comment]
Generally you'd want a server API that the client can call to do things which then makes the calls to AWS. Good luck!

**Comment by rehat101** [comment]
Can I load the keys as environment variables instead?
