### ISSUE TITLE
Develop failing with module dependency resolution errors

### ISSUE THREAD

**Issue by lloydh** [gatsbyjs/gatsby#7798]
## Description

I'm seeing the following error when running `develop` after upgrading from the beta to the latest RC:
```
These dependencies were not found:

* @babel/runtime/helpers/builtin/es6/assertThisInitialized in ./node_modules/react-powerplug/dist/react-powerplug.esm.js
* @babel/runtime/helpers/builtin/es6/defineProperty in ./node_modules/react-powerplug/dist/react-powerplug.esm.js
* @babel/runtime/helpers/builtin/es6/inheritsLoose in ./node_modules/react-powerplug/dist/react-powerplug.esm.js
* @babel/runtime/helpers/builtin/es6/objectSpread in ./node_modules/react-powerplug/dist/react-powerplug.esm.js
* @babel/runtime/helpers/builtin/es6/objectWithoutProperties in ./node_modules/react-powerplug/dist/react-powerplug.esm.js
```

We've looked at the issue in renatorib/react-powerplug#166 and can't see a reason why the dependencies shouldn't be resolving.

### Steps to reproduce

Add a `react-powerplug 1.0.0-rc.1` component, e.g. `{ Toggle }`, into a Gatsby `2.0.0-rc.7` project.
Run `develop` script.

### Expected result

Development compilation succeeds.

### Actual result

Development compilation fails with error above.

### Environment

  Binaries:
    Node: 9.11.1 - ~/.nvm/versions/node/v9.11.1/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v9.11.1/bin/npm
  npmPackages:
    gatsby: ^2.0.0-rc.7 => 2.0.0-rc.7 
    gatsby-plugin-emotion: next => 2.0.0-rc.1 
    gatsby-plugin-react-helmet: next => 3.0.0-rc.1 
    gatsby-plugin-remove-trailing-slashes: next => 2.0.0-rc.1 
    gatsby-plugin-sharp: next => 2.0.0-rc.3 
    gatsby-source-filesystem: next => 2.0.1-rc.1 
    gatsby-transformer-sharp: next => 2.1.1-rc.2 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

**Comment by KyleAMathews** [comment]
Looks like this is the problem https://github.com/renatorib/react-powerplug/issues/166#issuecomment-417783881

The latest Gatsby RC updated Babel to the stable Babel release.
