### ISSUE TITLE
Allow customizing generated file paths for non-HTML files

### ISSUE THREAD

**Issue by nakedible** [gatsbyjs/gatsby#7808]
## Summary

Allow customizing the file paths Gatsby generates for JavaScript, CSS and JSON files.

### Basic example

Currently, all non-HTML generated files end up at fixed paths in the built directory.

- JavaScript libraries end up in files like `2-b3d43945f6c7a50aa89b.js`
- JavaScript for pages end up in files like `component---src-pages-index-js-d21e28ef0022ceb7ca2f.js`
- CSS for pages end up in files like `component---src-pages-index-js.13f388f2be065d96ed97.css`
- Webpack runtime ends up in a file like `webpack-runtime-d38689d008fd7c177cbf.js`
- Webpack stats is named `webpack.stats.json`
- JSON data ends up in files like `static/d/173/path---index-6a9-NZuapzHg3X9TaN1iIixfv1W23E.json`

It should be possible to customize these paths, or atleast specify a subdirectory to place these paths in (that is separate from `pathPrefix` which affects the entire site and not just the non-HTML files).

### Motivation

Having the paths fixed makes it difficult to separate paths generated by Gatsby from other paths that might have to co-exist in the same domain. Compare this with WordPress, for example, where all data (for better or worse) is in `wp-content` or `wp-includes`.

Using path prefix works if there is only a single subdirectory which should be served by Gatsby, but for example if both `/dev/` and `/doc/` should be served by Gatsby, and everything else by something different, then the only solution for now would be to make two separate Gatsby sites with different path prefixes, which is quite non-optimal.

**Comment by nakedible** [comment]
Since generating paths seems to happen all over the place in Gatsby, and path generation method is mostly hardcoded, fixing this to be fully customizable would seem to be quite a large rework.

However, since all places *should* respect `pathPrefix`, a simple and stupid solution would be to just break that in to two - `pathPrefix` and `dataPathPrefix`. Normally setting `pathPrefix` would also set `dataPathPrefix` to the same value, but `dataPathPrefix` could be overridden invidually. Then it would be simply a case of passing both values to all places and using either `__PATH_PREFIX__` or `__DATA_PATH_PREFIX__` as appropriate.

**Comment by mtsbank** [comment]
Hello! What about this feature?
