### ISSUE TITLE
React-navigation project gastby v2 router  with react-native-web

### ISSUE THREAD

**Issue by simonjoom** [gatsbyjs/gatsby#7809]
Hello, i'm new from yesterday and i like already gatsby ))

I want to know if somebody can resolve my situation
I would like to use the gastby v2 router on my react-navigation (yes gastby run with react-native)
 
Here my project (run ssr+gastby+react-native-web)
https://github.com/simonjoom/gatsby

Due to the architecture of react-navigation who use stack of component.. how i can plug the both together? 
If somebody already did that, thanks to give me some thought.

Regards
Simon

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by kakadiadarpan** [comment]
Hi @simonjoom, if I understand it correctly you are trying to use Gatsby with `react-native-web` and `react-navigation`. Right?

**Comment by simonjoom** [comment]
i'm doing it already
Just i m guessing how i can plug the router of gatsby to react-navigation

**Comment by simonjoom** [comment]
pull https://github.com/simonjoom/gatsby i try if you want have an idea

**Comment by kakadiadarpan** [comment]
Hi @simonjoom, from your repository I understand that you are trying to create a Gatsby starter pack for react-native. However, at the moment we are supporting Gatsby only for web applications.

**Comment by simonjoom** [comment]
amax it's a web application too.. react-native-web do the job
