### ISSUE TITLE
Top Level Component in Gatsby V2?

### ISSUE THREAD

**Issue by benwis** [gatsbyjs/gatsby#7817]
I'm integrating Apollo Client into Gatsby v2 beta, but I was curious if there was a root component. For example, in create-react-app, you can have an App component that all the other ones run out of.

I want to add ApolloProvider so that its context can be accessed throughout all the pages and components being served.  Here's the section of the getting started that introduces [it](https://www.apollographql.com/docs/react/essentials/get-started.html#creating-provider). Where do you think it should go?

**Comment by sbugert** [comment]
I think what you need is [wrapRootElement](https://next.gatsbyjs.org/docs/browser-apis/#wrapRootElement). It exists both for `gatsby-browser.js` and `gatsby-ssr.js`.

**Comment by benwis** [comment]
THat's exactly it, didn't know that existed. Thanks!
