### ISSUE TITLE
window is not defined in gatsby.js when build

### ISSUE THREAD

**Issue by amit-deligence** [gatsbyjs/gatsby#7830]
## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here. Not working? You may need to update your global gatsby-cli - `npm install -g gatsby-cli`

**Comment by LeKoArts** [comment]
Please create a proper issue with filled out categoried
