### ISSUE TITLE
v2 `actions.setBabelOptions` doesn't do anything.

### ISSUE THREAD

**Issue by jquense** [gatsbyjs/gatsby#7837]
There is helpfully an API for changing the babel-loader options but it doesn't actually do anything. The options are saved in babelState.json, but not ever read out during the custom loader process.

**Comment by KyleAMathews** [comment]
Oh hmm. Yeah, I missed adding back support for this in the recent PR. Though I also don't remember the use case for the api 😅

**Comment by jquense** [comment]
in my case i want to set: http://babeljs.io/docs/en/options#babelrcroots so it works with webpack alias's to fiules outside the gatsby root, e.g. i have a `www` folder  for docs that's a gatsby site but it reads the library src files from ./src a sibling to www
