### ISSUE TITLE
Doucmentation Issue, Tutorial 4th step v2

### ISSUE THREAD

**Issue by Inopo** [gatsbyjs/gatsby#7840]
This is a documentation issue. 
## Description

While doing the 4th step in the tutorial for v2 (Your First GrapghQL Querry. ) If you copy paste the 

export const query = graphql`
  query {
    site {
      siteMetadata {
        title
      }
    }
  }

Then there is a error. "Unterminated template literal."

If you put a ` to the end. Then it works. 

PS: My JS and Coding knowledge is close to zero. I am not expressing my self in technical terms. Sorry for that.

**Comment by mikelax** [comment]
Hey @Inopo Are you talking about the query on [this page](https://next.gatsbyjs.org/tutorial/part-four/)? 
If so I think there is already on a ` on a line by itself, so I think this is just a copy-paste issue.

**Comment by Inopo** [comment]
Yes @mikelax I now see that in the next line. Thanks.
