### ISSUE TITLE
 Create a boilerplate to create a consistent Gatsby plugin README experience

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#7843]

**Comment by ekoeryanto** [comment]
just done with https://github.com/ekoeryanto/gatsby-plugin-boilerplate

**Comment by shannonbux** [comment]
@jlengstorf I think this was your original idea, so wanted to loop you in
here!

**Comment by jlengstorf** [comment]
@ekoeryanto I think we may have crossed wires — this issue is to track creating a README template.

I think our ultimate goal is to add a plugin creation command to our CLI.

In the meantime, simply having a clean README that plugin authors can start with will be good enough.

**Comment by ekoeryanto** [comment]
@jlengstorf never mind, I just created the boilerplate to help my self easily creating gatsby plugins.
anyway, having a plugin creation feature  in `gatsby-cli` is the best way.

**Comment by shannonbux** [comment]
Hi @ekoeryanto, we're closing this issue for now, since we do have a plugin READme template here: https://www.gatsbyjs.org/docs/templates/#plugin-readme-template

Thanks for sharing your repo; perhaps you could blog about it, tweet about it. We love it when contributors share what they're building!
