### ISSUE TITLE
Can't get WordPress plugin to get past createPage when using Gatsby version 2 (v2)

### ISSUE THREAD

**Issue by SimonIMG** [gatsbyjs/gatsby#7853]
## Description

I've set up a fresh install of the Gatsby Starter with version 2. My package.json file says...
```
"dependencies": {
    "gatsby": "next",
```
I have set up the `gatsby-node.js` file as per the docs, and also as per [Level Up Tutorials](https://www.leveluptutorials.com/tutorials/headless-wordpress/building-pages-in-gatsby). I'm just trying to get it to output pages for all the WordPress pages in my site (a local Lando instance of the latest WordPress 4.9.8 - I also tried another live WP site ).

I've quadruple checked my code but I cannot find any issues (and my linter is going to work, checking my code).

The `gatsby develop` process won't get past createPages.

I've googled and searched extensively, but I can't find any solution for my version 2 Gatsby setup.

**Can anyone confirm that they have gotten Gatsby v2 working in a headless WordPress setup?**m I can't figure out why I'm not able to get it to compile.

### Steps to reproduce

1. Installed a fresh install of v2 gatsby with `gatsby new my-default-project https://github.com/gatsbyjs/gatsby-starter-default#v2`
2. Add WordPress plugin with `npm install --save gatsby-source-wordpress`
3. Update `gatsby-config.js` with local/live WordPress config
4. Update `gatsby-node.js` with the following config.

```
const path = require('path');

exports.createPages = ({ graphql, boundActionCreators }) => {
  const { createPage } = boundActionCreators;
  return new Promise((resolve, reject) => {
    graphql(`
      {
        allWordpressPage {
          edges {
            node {
              id
              slug
              title
            }
          }
        }
      }
    `).then((result) => {
      if (result.errors) {
        console.log(result.errors);
        reject(result.errors);
      }

      result.data.allWordPressPage.edges.forEach(({ node }) => {
        createPage({
          path: node.slug,
          component: path.resolve('./src/pages/page-2.js'),
        });
      });

      resolve();
    });
  });
};
```

I also tried `_.each(result.data.allWordpressPost.edges, edge => {` instead of `result.data.allWordPressPage.edges.forEach(({ node }) => {` as per the [gatsby-node.js example on the plugin page](https://next.gatsbyjs.org/packages/gatsby-source-wordpress/?=wordpress#sites-gatsby-nodejs-example).

### Expected result

`gatsby develop` should run and, after completion, I should be able to enter http://localhost:8001/slug-of-a-page and see the _Page-2_ page of the starter site.

### Actual result

Terminal gets stuck at createPages.

```
success source and transform nodes — 6.061 s
success building schema — 0.598 s
⠠ createPages  // Get's stuck here, ticking over forever
```

### Environment

  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i7-3840QM CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.8.0 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.2.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 61.0.2
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-rc.5 
    gatsby-plugin-manifest: next => 2.0.2-rc.1 
    gatsby-plugin-offline: next => 2.0.0-rc.1 
    gatsby-plugin-react-helmet: next => 3.0.0-rc.1 
    gatsby-source-filesystem: ^1.5.39 => 1.5.39 
    gatsby-source-wordpress: ^2.0.93 => 2.0.93 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

**Comment by kakadiadarpan** [comment]
Hi @SimonIMG, did you had a chance to look at the example of [using-wordpress](https://github.com/gatsbyjs/gatsby/blob/master/examples/using-wordpress)?

**Comment by SimonIMG** [comment]
Thanks very much @kakadiadarpan. I didn't find that WordPress/Gatsby v2 example in my searches.

I knew that `boundActionCreators` had been deprecated, but I didn't realise I could literally swap them out.

I installed the _lodash_ and _bluebird_ packages and updated my gatsby-node.js file to mimic most of what I saw in the [gatsby-node.js file in the WordPress example](https://github.com/gatsbyjs/gatsby/blob/master/examples/using-wordpress/gatsby-node.js).

I also had to run `npm install` again as I was getting errors like...
```
Error: Unable to find plugin "gatsby-plugin-react-helmet".
```
...even though they were definitely installed.

I then updated my `gatsby-node.js` to the following...
```
const _ = require('lodash');
const Promise = require('bluebird');
const path = require('path');

exports.createPages = ({ graphql, actions }) => {
  const { createPage } = actions;
  return new Promise((resolve, reject) => {
    graphql(`
      {
        allWordpressPage {
          edges {
            node {
              id
              slug
              title
            }
          }
        }
      }
    `).then((result) => {
      if (result.errors) {
        console.log(result.errors);
        reject(result.errors);
      }

      _.each(result.data.allWordpressPage.edges, (edge) => {
        createPage({
          path: `/${edge.node.slug}/`,
          component: path.resolve('./src/pages/page-2.js'),
          context: {
            id: edge.node.id,
            slug: edge.node.slug,
          },
        });
      });

      resolve();
    });
  });
};
```
We're compiling correctly and, when I visit any slug, I'm seeing the page-2.js page in Gatsby.

**Comment by loremipson** [comment]
Nope. I actually don't have anything set in my `gatsby-node.js` file yet. We've just been trying to get our data in the graphiql interface so far, but have run into this road block.

I'm doing something wrong on my end, because I've done this with gatsby v1 already, and when I tried switching to V1 to see if it was just V2 causing the issue, it was still throwing this error at me. I just can't pinpoint it. Our config has everything it's supposed to.

**Comment by loremipson** [comment]
Oof.. I wish I would have noticed the `verboseOutput` option earlier. Just set that to true and realized our baseURL is returning undefined. Why? I don't know, but this might point me in the right direction.

**Comment by SimonIMG** [comment]
This sounds like a separate issue to my `createPages` issue. Perhaps you want to start a new thread, or search for issues with the `gatsby-config.js` file?

Hard to tell what your issue is without seeing your `gatsby-config.js` file.

And before that, [check out the gatsby-config.js file](https://github.com/gatsbyjs/gatsby/blob/master/examples/using-wordpress/gatsby-config.js) in the WordPress and Gatsby V2 example. Compare it to your `gatsby-config.js`.

Hope this helps.

**Comment by loremipson** [comment]
It totally is a separate issue, I'm sorry for hijacking this one.

This is _really_ embarrassing, but it's been a long week... pointing to `baseURL` instead of `baseUrl`.. That was the problem. :| I'm going to go quit development now.

**Comment by SimonIMG** [comment]
HA! We all have days like that. Don't quit, just learn.
