### ISSUE TITLE
Firebase auth doesn't work in Gatsby V2 app deployed on Firebase Hosting

### ISSUE THREAD

**Issue by nikhilag** [gatsbyjs/gatsby#7856]
## Description
In my Gatsby V2 web app, I am using firebase auth to login with google. It is working properly on my machine but when I deploy to Firebase Hosting it doesn't work. Please see console log in attached screenshot. <img width="1425" alt="screen shot 2018-09-04 at 1 58 07 pm" src="https://user-images.githubusercontent.com/5186055/45019881-0fdd5780-b04b-11e8-8b77-031135a30483.png">

I have already checked that the correct URLs are allowed for localhost and for deployed site for google login in Firebase admin panel. My guess is that it has something to do with gatsby-plugin-manifest or gatsby-plugin-offline. As per https://firebase.google.com/docs/hosting/reserved-urls , I added the whitelist url for gatsby-plugin-offline in the following way while keeping the existing whitelist url (as per https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-offline) :-
```
{
      resolve: `gatsby-plugin-offline`,
      options: {
        navigateFallbackWhitelist: [/^[^?]*([^.?]{5}|\.html)(\?.*)?$/, /^(?!\/__).*/]
      }
}
```
I deployed the site again but it still didn't work.

### Steps to reproduce
Deploy a GatsbyJS site on Firebase Hosting which makes use of Firebase Google Auth. The following plugins were used:-
```
plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-shopify`,
      options: {
        shopName: `...`,
        accessToken: `...`,
        verbose: true,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/pages`,
        name: 'pages',
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/asset/img`,
        name: `images`,
      }
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/asset/font`,
        name: `fonts`,
      }
    },
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: '...',
        short_name: '...,
        start_url: '/',
        background_color: '#f2efec',
        theme_color: '#f2efec',
        display: 'minimal-ui',
        icon: '...'
      }
    },
    {
      resolve: `gatsby-plugin-offline`,
      options: {
        navigateFallbackWhitelist: [/^[^?]*([^.?]{5}|\.html)(\?.*)?$/, /^(?!\/__).*/]
      }
    },
    `gatsby-plugin-netlify-cms`,
    `gatsby-plugin-netlify`,
  ]
```

### Expected result
On clicking Google Login Button, the popup should open asking for google credentials.

### Actual result
The google login popup stays blank and then closes. I have attached the error logs shown in console.

### Environment
Google Firebase

**Comment by kakadiadarpan** [comment]
Hi @nikhilag, can you remove the `gatsby-plugin-offline` and check if that solves the problem for you?

**Comment by nikhilag** [comment]
@kakadiadarpan It works properly on removing gatsby-plugin-offline. Any idea on how I can keep the plugin and still deploy to firebase?
