### ISSUE TITLE
How can I implement a back to previous location after login?

### ISSUE THREAD

**Issue by akoolenbourke** [gatsbyjs/gatsby#7858]
## Summary

Hi all. I'm struggling to find any docs on how to implement a back() style operation in Gatsby V2. That is, I have some client side routes for gating against auth and they render my `<Login>` component if auth is required. however, once auth is successful I want to throw them back to the page that caused them to get to `<Login>`

How can I do this? I don't have to wrap every component/page I have in reach-router's `<Location>` tags do I and pass props.location down all around?

Thanks

**Comment by akoolenbourke** [comment]
Thanks. Unfortunately Gatsby now uses @reach-router and it doesn't seem to work the same. For instance, in a component there doesn't seem to be props.location that I could pass to <Login> for instance.

**Comment by KyleAMathews** [comment]
Check out the docs for programmatic navigation

https://next.gatsbyjs.org/docs/gatsby-link/#programmatic-navigation

This example site might help as well

https://github.com/gatsbyjs/gatsby/tree/master/examples/simple-auth
