### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by emilbruckner** [gatsbyjs/gatsby#786]
When building, the program prints 'Done' and then gets stuck. (This also results in failing netlify deploys)

**Comment by bntzio** [comment]
That happened to me some days ago, it's a webpack error, maybe with some of your installed dependencies, for me it was generating the error due [gsap](https://www.npmjs.com/package/gsap) ([see issue](https://github.com/greensock/GreenSock-JS/issues/168))

I uninstalled gsap and load it in the header with a script tag and it worked fine both on netlify and locally when `gatsby build`

**Comment by KyleAMathews** [comment]
@emilbruckner is there anything else you could add about your site? What extra modules you've added? Any webpack modifications? You have any custom code touching `window`?

**Comment by emilbruckner** [comment]
@KyleAMathews 
No webpack modifications
I added react-slick, react-icons and react-lazyload
I use window in componentDidMount

**Comment by KyleAMathews** [comment]
Perhaps react-lazyload is the problem. At least it doesn't support server rendering https://github.com/jasonslyvia/react-lazyload/issues/76

**Comment by emilbruckner** [comment]
I had an interval running in my code, causing the build to run infinitely. Haven't found a solution yet, but that should be possible. React-lazyload works fine.
@KyleAMathews Anything to add from your side?

**Comment by KyleAMathews** [comment]
Ah cool! Glad you found it. Gatsby could help mitigate stuff like this, e.g. perhaps detect if some subsystem is taking unusual amounts of time to finish and throwing out a warning in the terminal.

**Comment by emilbruckner** [comment]
That would be great for cases like this

**Comment by cesarvarela** [comment]
This is happening to me now! How can I find what is causing this?

**Comment by KyleAMathews** [comment]
@cesarvarela I would just start commenting stuff out until the build succeeds and then use that to isolate the source of the trouble and proceed from there.

**Comment by cesarvarela** [comment]
From @emilbruckner comment I guess I should focus on async stuff right?

**Comment by cesarvarela** [comment]
It was an Observable:

```
        this.directLine = new DirectLine({
            secret: 'y3254'
        });

        this.directLine.activity$
            .filter(activity => activity.type === 'message')
            .subscribe(message => {

                if (message.from.id != this.state.user.id) {

                    this.setState({ messages: this.state.messages.concat([new ChatMessage({ from: message.from.id, id: message.id, text: message.text, sent: true, attachments: message.attachments })]) });
                }
            });
```

Is there some other place where I can put this code that gatsby will like? Right now is on the constructor of the main components (`SiteIndex` from the `Gatstrap` starter).

**Comment by KyleAMathews** [comment]
componentDidMount is the place to put client only code so it won't run
during server rendering

**Comment by cesarvarela** [comment]
Thanks! Did just that!
