### ISSUE TITLE
Blink of content

### ISSUE THREAD

**Issue by rehat101** [gatsbyjs/gatsby#7870]
I see a weird blink of unstyled content to styled content — I'm using styled-components to style and also have `gatsby-plugin-styled-components` in my config file. 

I only see this issue in the build version of the site.

**Comment by KyleAMathews** [comment]
Can you create a site that reproduces this issue that we could look at?

**Comment by rehat101** [comment]
taherand.co - here you go

**Comment by DSchau** [comment]
@rehat101 I am pretty certain this is not an issue with Gatsby.

It's hard to debug without the original source code, but do you by chance have some type of animation you're applying on content? I see this in the element inspector on your `PageWrapper` component?

```
opacity: 1;
transform: matrix(1, 0, 0, 1, 0, 0);
```

if you simulate loading on a slow 3G connection and disable cache, you can see that component animate in. I believe it's this animation in that is causing the "blink" effect you're seeing.


![Example](https://gfycat.com/EsteemedFrequentAcornweevil)

**Comment by merelinguist** [comment]
@rehat101 Does @DSchau’s comment help? If not, is there any way you could provide some reproduction code?

**Comment by rehat101** [comment]
The issue is more related to the unstyled content being loaded at first and styles being applied instantly causing flash/blink or whatever. I do have a fade in transition on `componentDidMount()`

**Comment by merelinguist** [comment]
@rehat101 If the issue is with the `styled-components` plugin, could you provide your `package.json` and `gatsby-config.js` (or excerpts of them)?

**Comment by rehat101** [comment]
@merelinguist I don't happen to see the flash anymore. I wonder why

**Comment by pieh** [comment]
In v2 we recently merged https://github.com/gatsbyjs/gatsby/pull/7912 which should fix this issue in case if any of you use gatsby v2 - please try to update `gatsby-plugin-styled-components` and check if it works

**Comment by rehat101** [comment]
The update fixed the problem, thanks!
