### ISSUE TITLE
[Gatsby Store] Order placed, money went out ... no confirmation email or delivery

### ISSUE THREAD

**Issue by endymion1818** [gatsbyjs/gatsby#7875]
Hi

I placed an order on store.gatsbyjs.org and used my coupon as a contributor to get me some snazzy socks ... I paid a little extra for some stickers too, and money went out of my account to "SP * Gatsby INC" on 20 July 2018.

However ... fabled socks did not arrive. I just checked and it turns out I didn't get a confirmation email either.

I don't mind losing the 1.54 GBP but I am missing a significant sticker on my laptop and my toes are getting slightly chilly.

**Comment by KyleAMathews** [comment]
@jlengstorf

**Comment by jlengstorf** [comment]
@endymion1818 sorry about that! Can you please email me at jason@gatsbyjs.com with the email address you used to make the order? If you don't mind forwarding the payment receipt as well, that'll help me track things down and get this sorted.

Thanks!

**Comment by endymion1818** [comment]
Swag has arrived! My toes and I are eternally grateful!
