### ISSUE TITLE
Reach Router Extremely slow changing route.

### ISSUE THREAD

**Issue by benadam11** [gatsbyjs/gatsby#7876]
## Description

After converting from V1 -> V2 - the route changes are very slow. 
https://github.com/gatsbyjs/gatsby/issues/7068 documents the same issue which was supposedly solved, but I am still struggling with the 

### Steps to reproduce

https://www.dayofthedead.holiday

Click on the nav Link (Home -> Sugar Skull) 

### Expected result

Expected: Url changes and page change immediately

### Actual result

Actual: Url changes but page does not change for 3+ seconds

### Environment

  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.0 - ~/.nvm/versions/node/v8.9.4/bin/npm
  Browsers:
    Chrome: 69.0.3497.81
    Firefox: 52.9.0
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.0.0-rc.10 => 2.0.0-rc.10 
    gatsby-image: next => 2.0.0-rc.1 
    gatsby-link: ^2.0.0-rc.1 => 2.0.0-rc.1 
    gatsby-plugin-eslint: ^2.0.1 => 2.0.1 
    gatsby-plugin-google-analytics: next => 2.0.0-rc.1 
    gatsby-plugin-react-helmet: next => 3.0.0-rc.1 
    gatsby-plugin-react-next: next => 2.0.1-13 
    gatsby-plugin-sharp: next => 2.0.0-rc.3 
    gatsby-plugin-sitemap: next => 2.0.0-rc.1 
    gatsby-remark-copy-linked-files: next => 2.0.0-rc.1 
    gatsby-remark-images: next => 2.0.1-rc.1 
    gatsby-source-filesystem: next => 2.0.1-rc.1 
    gatsby-transformer-remark: next => 2.1.1-rc.1 
    gatsby-transformer-sharp: next => 2.1.1-rc.2 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

**Comment by KyleAMathews** [comment]
The previous issue was for development. You're seeing a problem with the production build?

FWIW, I just went to the site and clicked on the link and it changed instantly. Perhaps do a performance audit while clicking to see what's going on?

**Comment by benadam11** [comment]
Yeah this issue is also there on the production build. When you said you clicked the link and the page changed immediately? Was that the URL or the actual page content? The issue I am seeing  - is you click a link and there is a noticable delay between when the url is update (happens immediately) and when the page content changes (sometimes delayed up to 3 seconds)

**Comment by benadam11** [comment]
Did some more investigation and its something related to lottie-web - have a temporary fix but its interesting that it surfaced when upgrading to V2 (not sure why)

**Comment by mishoboss** [comment]
Hi, I experience the same issue with Lottie and Gatsby. The first time a page is loaded all is fine. The issue is when user clicks on a link and the router routes to a new page. There is a 5-6 seconds delay, the whole thing becomes slow and Lottie animations become extremely buggy. Anyone having any ideas?
