### ISSUE TITLE
For gatsbygram + production-runtime cypress testing, do build of packages & copy over with gatsby-dev so we're testing latest code

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#7879]
/cc @m-allanson @pieh @davidbailey00

**Comment by KyleAMathews** [comment]
@m-allanson no that's different. Right now we're not even doing the normal thing of using gatsby-dev so they don't actually test the current PR, they just test the last released version of the code. The issue you linked to is about adding support for properly testing things when there's dependency changes. But since 95% of PRs don't have dependency changes, fixing this issue is also very important and in any case is needed for #4948 to take effect :-)

**Comment by pieh** [comment]
This was done in https://github.com/gatsbyjs/gatsby/pull/7936
