### ISSUE TITLE
Creators Page General Issue

### ISSUE THREAD

**Issue by berraknil** [gatsbyjs/gatsby#7895]
An overall issue to track steps to wrap up creators page

- [x] Code review, currently going on https://github.com/gatsbyjs/gatsby/pull/7874#pullrequestreview-152302415

- [ ] Mobile layout implementation, started today, need to think of a clever way to wrap the navigation. 
       
       Individual page layout changes from row to column on mobile, see below

      
![mobilelayout](https://user-images.githubusercontent.com/6593585/45092239-7c288b80-b11d-11e8-80ad-da82cfeabca6.gif)

      will probably center the badge on mobile and make it wider (?)

- [x] Finish writing the docs and link to them from the page, tracking on https://github.com/gatsbyjs/gatsby/pull/7873

**Comment by berraknil** [comment]
@fk for any suggestions regarding mobile navigation? How can we integrate the Creators sub-navigation to the overall mobile navigation, any suggestions, advice etc?

**Comment by berraknil** [comment]
- [ ] Disable filters on individual pages (this will be fixed if we use a a different header there w breadcrumbs)

**Comment by fk** [comment]
Hey Berrak, sorry for not getting back to you last week as promised, and for not having anything to show even after today! 🙏 

> I will try to prototype it a bit today, which means we can also use person/company etc icons as well that we talked about before. Do we have icons like that already?

Sounds good! No, unfortunately no icons yet, but maybe you could use placeholders from http://react-icons.github.io/react-icons/ for now?

**Comment by berraknil** [comment]
@fk no problem at all, as for icons, using a Person icon from those collections is easy but how do we differ agency/company or even All selection with icons? Maybe we can just use first letters capitalized, like A | P | A | C etc? I don't know :)

**Comment by berraknil** [comment]
- [ ] Change the text in Become a Creator depending on the page

- [ ] Responsive Design elements like wrap grid items (also give them margin bottom) alongside mobile layout
