### ISSUE TITLE
Environment variables when calling gatsby on the command line

### ISSUE THREAD

**Issue by christoferolaison** [gatsbyjs/gatsby#7896]
## Summary
First of all great work with Gatsby! 

I have something I want to report regarding envoiroment variables. When running `SOME_TOKEN=123456789 yarn build` the variable is only set in `gatsby-config.js` and `gatsby-node.js`. Is this a bug or by design?

The problem is that when I build the application with Heroku I want to be able to use the variables I set there to be present in `gatsby-ssr.js`. I have read the docs and but I don't want to  store the variables in `.env.production` and add them to the repo. 

## Relevant information
 
I have created an [repo](https://github.com/christoferolaison/gatsby-environment-variables) to reproduce. Run `SOME_TOKEN=123456789 yarn build`. 

### Environment (if relevant)

 System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 5.4.2 - /usr/local/bin/zsh
  Binaries:
    Node: 9.5.0 - ~/.nvm/versions/node/v9.5.0/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.1.0 - ~/.nvm/versions/node/v9.5.0/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 61.0.2
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-rc.10
    gatsby-plugin-manifest: next => 2.0.2-rc.1
    gatsby-plugin-offline: next => 2.0.0-rc.2
    gatsby-plugin-react-helmet: next => 3.0.0-rc.1
  npmGlobalPackages:
    gatsby-cli: 1.1.58

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by DSchau** [comment]
Hi Christopher 👋 

Let's walk through this!

> When running SOME_TOKEN=123456789 yarn build the variable is only set in gatsby-config.js and gatsby-node.js

You're exposing an environment variable outside of Gatsby, so it won't be available to Gatsby source files. Basically you're tying into a _system_ environment variable.

Gatsby followed create-react-app's lead here (e.g. REACT_APP_SOMETHING is exposed), so you need to prefix variables you _want_ to be exposed to Gatsby with `GATSBY_VARIABLE_NAME_HERE`, e.g. `GATSBY_SOME_TOKEN=1234`.

I've just validated this works locally, so if you'd like to try for yourself, please do let me know!

[Read more here](https://www.gatsbyjs.org/docs/environment-variables/)

Thanks for the question!

**Comment by christoferolaison** [comment]
Thanks for the fast answer! :) 

Ohh sorry about the noise I missed that one..
