### ISSUE TITLE
next/v2 website: all text comes at once instead of animated

### ISSUE THREAD

**Issue by Haroenv** [gatsbyjs/gatsby#7903]
## Description

All text of the "blazing fast" animation comes at once

### Steps to reproduce

- open Safari
- go to https://next.gatsbyjs.org
- wait ±1s
- see text come all at once

### Expected result

Text to come one by one

### Actual result

<img width="482" alt="screen shot 2018-09-05 at 11 33 42" src="https://user-images.githubusercontent.com/6270048/45113623-b8e58a00-b0ff-11e8-8d77-271055dc1753.png">

### Environment

I was trying this in Safari

**Comment by DSchau** [comment]
@Haroenv I can't replicate this! What version of Safari/Mac OS/etc?

![Example](https://thumbs.gfycat.com/DelectableFlimsyCottonmouth-size_restricted.gif)

**Comment by Haroenv** [comment]
I was using the tech preview `Release 63 (Safari 12.1, WebKit 13607.1.2.1)` (maybe the issue is just there?). I have the web animations feature enabled, are you using that? 

![2018-09-05 13-07-42 2018-09-05 13_08_23](https://user-images.githubusercontent.com/6270048/45118262-e422a600-b10c-11e8-82cf-83fd4fa395d9.gif)

**Comment by DSchau** [comment]
Definitely an issue with Safari Tech. Preview. Able to replicate as soon as I switched to it!

I'm not sure there's a _ton_ of value tracing this down, because it's very possible it's some bug in Safari and will be ironed out in a future release.

For what it's worth, here's the [animation source](https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/slider.css)

(it's just CSS!)

**Comment by Haroenv** [comment]
it's rdar://44151416 (their bugs are internal), and I confirm it goes away when I remove "web animations & css integration"

**Comment by graouts** [comment]
@Haroenv For future reference, you can also use bugs.webkit.org to file rendering bugs in Safari Technology Preview like this one.

**Comment by Haroenv** [comment]
Thanks for verifying and reducing this test case, I'll use the bugzilla in the future, always a bit confused where to file things for Safair
