### ISSUE TITLE
Evaluate featured sites & ordering of them for v2 launch

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#7908]
We'll be launching Gatsby v2 soon and in the process moving next.gatsbyjs.org to gatsbyjs.org which means the site showcase will then be live-er!

Before we do that, let's look over site showcase sites and tweak which ones are featured and the ordering of the featured sites to ensure we have our best feet forward.

**Comment by shannonbux** [comment]
We also ought to clean up the list of tags, like @pieh mentioned. I'm happy to do that, although I only know how to do it manually by CTRL+f in the `.yml` file!

**Comment by shannonbux** [comment]
Also does it make any sense to also track this in [EPIC] Starter Showcase v1.5?

**Comment by KyleAMathews** [comment]
That's all anyone would do :-) assign it to yourself if you'd like! Actually, let's assign it to both of ourselves and we can schedule 30 minutes in the next few days to review sites.

And need really to have them in both eoics.

**Comment by pieh** [comment]
Can this be closed after https://github.com/gatsbyjs/gatsby/pull/8133 was merged?

**Comment by shannonbux** [comment]
Closed by #8133
