### ISSUE TITLE
[1.0] Improve json parsing

### ISSUE THREAD

**Issue by fabien0102** [gatsbyjs/gatsby#791]
Hello, I'm trying to update gatsbygram with more data (real avatar picture, likes details…) and I've finded many issues this json parsing.

My test json => https://www.instagram.com/kyle__mathews/media/ (`items` key only)

### Json with isolate failing case (`/data/instragram.json`)
```json
[
  {
    "id": "1486495736706552111_31593318",
    "code": "BShF_8qhtEv",
    "issue1": null,
    "issue2": {
      "foo": {
        "bar": 1
      }
    },
    "issue3": []
  }
]
```
### Issue 1: `null` case

 `UNHANDLED REJECTION TypeError: Cannot read property 'hasOwnProperty' of null`

### Issue 2: neasted object (2+ levels)

 `UNHANDLED REJECTION Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "issue2___foo.
bar" does not.`

### Issue 3: empty array

 `UNHANDLED REJECTION Error: Can only create List of a GraphQLType but got: undefined.`

**Comment by KyleAMathews** [comment]
Oh cool! It'd be great to make the Gatsbygram site even more robust.

Yeah, the JSON parsing is quite simplistic atm and needs "robustified". Once the Redux refactor lands, parsers will be pretty easy to test so we can start creating test suites to cover existing use cases and start adding support for more.

**Comment by fabien0102** [comment]
Test suites will very appreciable for this!

**Comment by KyleAMathews** [comment]
Added some basic tests for the existing JSON transformation (new name) https://github.com/gatsbyjs/gatsby/pull/818/commits/a3f6c147d3bbc6092f718725db8dfb46dd7544db

**Comment by KyleAMathews** [comment]
Issues 1 and 3 are now both handled by ignoring these sorts of fields :-) if there's no data, there's no need to create a graphql field.

Issue 2 is solved by https://github.com/gatsbyjs/gatsby/pull/897 which I'll merge in a bit.

Thanks for the great very actionable issue!
