### ISSUE TITLE
Redirect to other domain

### ISSUE THREAD

**Issue by SachaG** [gatsbyjs/gatsby#7911]
In `createRedirect`, can I specify a different domain? I would like to do something like:

```
createRedirect({
    fromPath: `/2017/foo`,
    redirectInBrowser: true,
    isPermanent: true,
    toPath: `https://2017.stateofjs.com/2017/foo`,
})
```

**Comment by SachaG** [comment]
Closed as duplicate of #3782

**Comment by SachaG** [comment]
I'm reopening this since #3782 was closed.

**Comment by kakadiadarpan** [comment]
@SachaG would you like to look into creating a PR with a fix?

**Comment by SachaG** [comment]
Sorry I'm a bit busy with my own open-source projects so I probably won't have time to submit a fix…
