### ISSUE TITLE
[v2] Creating a new page during develop session via sourceNodes() is not working

### ISSUE THREAD

**Issue by Greegko** [gatsbyjs/gatsby#7916]
## Description

Creating new pages by plugins and refreshed via sourceNodes() is not working as expected. It only refreshes contents but cannot load the newly created pages.

The newly created page entry can be found in the Gatsby redux state, but the updated pages dictionary object is not transferred to the client side.

### Steps to reproduce

I used contentful as an external source here, but I would expect it can be reproduced with any other external source page generator.

Example repo: https://github.com/Greegko/gatsby-issue-7916

1. run `ENABLE_GATSBY_REFRESH_ENDPOINT=true gatsby develop`
2. add a new page to the external source
3. refresh gatsby sources `curl -X POST http://localhost:8000/__refresh`
4. try to load the new page 

### Expected result

See the new page

### Actual result

Not see the new page

### Environment

All info can be found in the repository.

**Comment by Greegko** [comment]
I think #5037 can be related.

**Comment by Greegko** [comment]
System:
    OS: macOS High Sierra 10.13.4
    CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.8.0 - /usr/local/bin/node
    npm: 6.2.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.81
    Firefox: 61.0.2
    Safari: 11.1
  npmPackages:
    gatsby: ^2.0.0-rc.13 => 2.0.0-rc.13
    gatsby-source-contentful: ^2.0.1-rc.4 => 2.0.1-rc.4

**Comment by m-allanson** [comment]
Hey @Greegko can you try updating your repo to the latest version of Gatsby? It looks like this will have been fixed by https://github.com/gatsbyjs/gatsby/pull/8570

**Comment by Greegko** [comment]
Thank you, the issue has been fixed!
