### ISSUE TITLE
[v2] [develop] Tries to prefetch undefined.json

### ISSUE THREAD

**Issue by oltodo** [gatsbyjs/gatsby#7932]
Under `develop` mode I get the following error into my Chrome's console:

![image](https://user-images.githubusercontent.com/483842/45170546-68a22100-b200-11e8-8108-4f1dde6b2f94.png)

I made a very basic research into `gatsby` package and it seems the `cache-dir/loader.js` file tries to prefetch resource based on the `jsonDataPaths` object (located in the `data.json` file) which is never loaded.

https://github.com/gatsbyjs/gatsby/blob/2383e104849458366b999f1a65b77d591644735f/packages/gatsby/cache-dir/loader.js#L116-L117

The function who's supposed to load the `jsonDataPaths` object but seems never called:

https://github.com/gatsbyjs/gatsby/blob/2383e104849458366b999f1a65b77d591644735f/packages/gatsby/cache-dir/loader.js#L33-L48

Is that normal?

__My `gatsby info`:__

```
  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.2 - /bin/zsh
  Binaries:
    Node: 10.7.0 - ~/.nvm/versions/node/v10.7.0/bin/node
    Yarn: 1.9.4 - ~/.nvm/versions/node/v10.7.0/bin/yarn
    npm: 6.4.0 - ~/.nvm/versions/node/v10.7.0/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 59.0.2
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-rc.13
    gatsby-plugin-feed: next => 2.0.0-rc.2
    gatsby-plugin-google-analytics: next => 2.0.0-rc.1
    gatsby-plugin-manifest: next => 2.0.2-rc.1
    gatsby-plugin-offline: next => 2.0.0-rc.4
    gatsby-plugin-react-helmet: next => 3.0.0-rc.1
    gatsby-plugin-sharp: next => 2.0.0-rc.3
    gatsby-plugin-typography: next => 2.2.0-rc.3
    gatsby-remark-copy-linked-files: next => 2.0.0-rc.1
    gatsby-remark-images: next => 2.0.1-rc.1
    gatsby-remark-prismjs: next => 3.0.0-rc.2
    gatsby-remark-responsive-iframe: next => 2.0.0-rc.1
    gatsby-remark-smartypants: next => 2.0.0-rc.1
    gatsby-source-filesystem: next => 2.0.1-rc.1
    gatsby-transformer-remark: next => 2.1.1-rc.1
    gatsby-transformer-sharp: next => 2.1.1-rc.2
  npmGlobalPackages:
    gatsby-cli: 1.1.58
    gatsby-dev-cli: 2.0.0-alpha.80a21f04
```

**Comment by pieh** [comment]
We shouldn't try to prefetch files for development - https://github.com/gatsbyjs/gatsby/blob/2383e104849458366b999f1a65b77d591644735f/packages/gatsby/cache-dir/loader.js#L231-L235 prefetching json should be inside `if (process.env.NODE_ENV === `production`) {` (data in development is handled by `devGetPageData(page.path)` few lines above)

**Comment by davidbailey00** [comment]
I can confirm this with my tutorial project used for testing

![image](https://user-images.githubusercontent.com/4248177/45177686-8cb72f80-b20b-11e8-959a-08482e0d3e0b.png)
