### ISSUE TITLE
gatsby-source-wordpress: Has anyone started integrating Wordpress's Gutenberg with gatsby?

### ISSUE THREAD

**Issue by qoby** [gatsbyjs/gatsby#7935]
## Summary

Just a question: is anyone trying to integrate Wordpress's new editor [Gutenberg](https://wordpress.org/gutenberg/) with Gatsby?

Specifically, it would be amazing if blocks of React content could be placed into content visually.

Blocks can be defined: https://wordpress.org/gutenberg/handbook/blocks/writing-your-first-block-type/

and then placed:

![image](https://wordpress.org/gutenberg/files/2018/07/Insert-Block-2-1.gif)

**Comment by octalmage** [comment]
The two work great together already! I use Gutenberg on my website to write posts then display them on Gatsby. What other functionality would you like?

**Comment by qoby** [comment]
@octalmage: you're using custom layout blocks?

**Comment by jameskhamil** [comment]
I would like to know this too. It look like so much work to get custom blocks working with gatsby and wordpress. Probably not worth the effort at this point.

**Comment by octalmage** [comment]
I'm not sure what you mean by custom layout blocks. I use Gutenberg to write by blog posts and display them on my site. I have also created custom Gutenberg blocks that are displayed on my Gatsby site. The REST API just returns the generated HTML, then you just display that.
