### ISSUE TITLE
[1.0] Include REDUX store if there are store files under store folder

### ISSUE THREAD

**Issue by danielo515** [gatsbyjs/gatsby#794]
It would be ideal to provide a mechanism to easily include REDUX.
An example workflow would be look for the store directory, if it exists, Gatsby will:

- Import Redux
- import react-redux
- Add required modules in the bundle (not sure how gatsby handles this)
- Build an store from the files under the store folder
- Add the store option to the root React instance using react-redux

This is similar to what NUXT does: https://nuxtjs.org/guide/vuex-store

Optional additions would be to use REDUX sagas.

I'm not sure if I have described the flow in a technically correct manner, I not sure about the correct terminology. Hope it is clear enough to get the idea.

**Comment by danielo515** [comment]
This was originally proposed at #777

**Comment by danielo515** [comment]
Interesting piece of information: https://github.com/gatsbyjs/gatsby/releases/tag/v0.12.34

**Comment by 0x80** [comment]
Redux is pretty cool, but you don't have to shout it 😉

**Comment by KyleAMathews** [comment]
Hey @danielo515! Thanks for kicking off this discussion!

So this is an ideal use case for a Gatsby plugin. It could automatically import Redux files and wrap the root render with the `<Provider>` component, etc.

Gatsby v1 has similar APIs as to what's been added to 0.x. If you go to this file and search for `apiRunner` you'll see the various APIs your plugin can use. https://github.com/gatsbyjs/gatsby/blob/1.0/packages/gatsby/lib/intermediate-representation-dir/production-app.js

Here's two official plugins that are using some of these APIs:

* https://github.com/gatsbyjs/gatsby/blob/1.0/packages/gatsby-plugin-google-analytics/src/gatsby-browser.js
*https://github.com/gatsbyjs/gatsby/blob/1.0/packages/gatsby-typegen-remark-autolink-headers/src/gatsby-browser.js

**Comment by KyleAMathews** [comment]
Would love to see a plugin for this but closing this now as it's not a core concern.
