### ISSUE TITLE
[v2] [unconfirmed] Gatsby doesn't properly delete files on build

### ISSUE THREAD

**Issue by davidbailey00** [gatsbyjs/gatsby#7942]
@Dfmarulanda has [pointed out](https://github.com/gatsbyjs/gatsby/pull/7355#issuecomment-419225564) that `gatsby build` doesn't work reliably without first deleting the `public` folder - we should guarantee that running `gatsby build` over an existing build results in a working website.

**Comment by davidbailey00** [comment]
Just checked this on the latest commit of [crowdswap/landing](https://github.com/crowdswap/landing) - I cloned, ran `yarn install` and `gatsby serve` and upon visiting localhost:9000, there were no problems.

@Dfmarulanda I'm assuming this is a problem with how Azure is caching certain resources, since it's working perfectly for me - closing. Please let me know if you have any further issues, but I think this is an issue with your deployment rather than with Gatsby.

**Comment by KyleAMathews** [comment]
This sounds like a bad npm/yarn install problem. The only possible issue with files in `public` is if you remove a page and then don't delete the html for that page. But we take care of that by deleting all HTML files at the start of a build.

**Comment by Dfmarulanda** [comment]
I deleted everything, indeed it worked perfectly for weeks. I changed my build process and now it's working perfectly. I decided to use Azure Blob Storage instead of Azure Web App. Working like a charm.

**Comment by hackhat** [comment]
I don't know but I just looked into my public folder and was huge of .map and .js.map files. I don't think they get wiped all the time properly.

**Comment by pieh** [comment]
@hackhat that's very good point, we should expand globs used in https://github.com/gatsbyjs/gatsby/blob/42a2d07ad0a48be6e1a910dda0a371104986c3af/packages/gatsby/src/bootstrap/index.js#L133-L148
to cover map files
