### ISSUE TITLE
Prefetch css chunks (along side js)

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#7948]
Currently we prefetch js chunks but don't prefetch css chunks until webpack decides we need them. This obviously slows down Gatsby some if a page transition is blocked by a required css chunk.

To implement this, we'd need [to add css paths to the chunkMapping object](https://github.com/gatsbyjs/gatsby/blob/4efe8f97d9992c60c66ea27de6b5acfeb8212bf6/packages/gatsby/src/utils/webpack.config.js#L229) we add to our generated HTML files  and then make the prefetching logic in https://github.com/gatsbyjs/gatsby/blob/4efe8f97d9992c60c66ea27de6b5acfeb8212bf6/packages/gatsby/cache-dir/loader.js#L233-L234 smart enough to also figure out which css chunks are required.

**Comment by davidbailey00** [comment]
I'll give this a go!

**Comment by KyleAMathews** [comment]
Sorry — my notes in the description were pretty cryptic 😅 

I'll expand a bit.

When we save out page data during the build, we save the `componentChunkName` for the page. We use that in `loader.js` to do prefetching by using the "chunk mapper" to get the actual file name from the component chunk name. In Gatsby v1 we only worried about prefetching js chunks because webpack didn't add support for css chunks until v2. I created this issue as I realized we hadn't support for prefetching them.

We get access to the file names webpack generates by hooking into their post build step and then writing out a file in the public directory which then our runtime can use (we inline the chunk names into the end of the HTML files because it's pretty small).

You can see that here: https://github.com/gatsbyjs/gatsby/blob/2a93b851ea620f3c8a8012724321beced179cb8a/packages/gatsby/src/utils/webpack.config.js#L229-L252

So the changes needed are:

1. Add to chunk-map.json css chunks (if any) for page components
2. Also prefetch them in the frontend.

Hope that helps! And thanks for jumping on this!
