### ISSUE TITLE
[Site showcase] we should make the column width for sites flexible so that we fill all the space at different screen widths

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#7950]
Currently there's often odd amounts of white space to the right and some computers only have two columns when three would easily fit.

**Comment by fk** [comment]
We want to do the same for the starter showcase, right? :P

**Comment by riencoertjens** [comment]
Just looking for something easy as a first ever open source contribution here.
can I suggest something like this with fluid images to fix the whitespace on the right issue?

![showcase resize](https://user-images.githubusercontent.com/36336875/45255633-9b2b5580-b389-11e8-9b45-3d645387c4f3.gif)

I also noticed the starter-showcase doesn't always use the shared styles so I'll add those if that's ok. (or should there be a separate issue/pr for that?)

**Comment by fk** [comment]
Hey @riencoertjens! 👋 

Woahh, this is looking exactly like what we (well, I 😉— but I'm quite sure @KyleAMathews agrees) were thinking of! This looks almost ready to get merged in!? 😍🎉 

Want to get a PR up with what you've got?

> I also noticed the starter-showcase doesn't always use the shared styles so I'll add those if that's ok. (or should there be a separate issue/pr for that?)

Def. would be great to have what we need to make this happen for both showcases consolidated; no need to split that up into two separate PRs IMO! Looking forward to review this! 🤗

**Comment by kakadiadarpan** [comment]
@fk @KyleAMathews we have fixed the site showcase. But what about starters showcase?

**Comment by fk** [comment]
@kakadiadarpan Both are fixed! 👍 

Forgot to close this, this was fixed via #7998.
