### ISSUE TITLE
loading {StaticQuery} shown forever error

### ISSUE THREAD

**Issue by samlazrak** [gatsbyjs/gatsby#7959]
## Description

Loading {StaticQuery} on generated slug pages. What's going on here? I'm unsure on how to correct the error I get due to the syntax of StaticQuery being different from normal.

### Steps to reproduce

https://github.com/samlazrak/gatsby-hello-world-v2

`yarn install` and `yarn dev`

Navigate to `http://localhost:8000/HelloWorld/helloworld/`

### Expected result

Be shown the blog post in content/helloworld/helloworld.md:

```
---
title: "Hello world!"
date: "2018-09-06"
---

Hello world! First test blog post!

Here's a video of some pandas: 

<iframe width="560" height="315" src="https://www.youtube.com/embed/4n0xNbfJLR8" frameborder="0" allowfullscreen></iframe>

```
### Actual result

`loading {StaticQuery}` in browser

and this error console: ( Which is shown not on page load but on script start making me think this is the root of the issue but the syntax of StaticQuery is giving me issues. )

```
The GraphQL query from /Users/samlazrak/Sites/gatsby-blog/src/templates/post.js failed.

Errors:
  Variable "$slug" is not defined by operation "usersSamlazrakSitesGatsbyBlogSrcTemplatesPostJs44930641".

  GraphQL request (2:38)
  1: query usersSamlazrakSitesGatsbyBlogSrcTemplatesPostJs44930641 {
  2:   markdownRemark(fields: {slug: {eq: $slug}}) {
                                          ^
  3:     html

  GraphQL request (1:1)
  1: query usersSamlazrakSitesGatsbyBlogSrcTemplatesPostJs44930641 {
     ^
  2:   markdownRemark(fields: {slug: {eq: $slug}}) {

Plugin:
  none
Query:
  query usersSamlazrakSitesGatsbyBlogSrcTemplatesPostJs44930641 {
    markdownRemark(fields: {slug: {eq: $slug}}) {
      html
      frontmatter {
        title
      }
    }
  }
```

### Environment

```
  System:
    OS: macOS 10.14
    CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 2.7.1 - /usr/local/bin/fish
  Binaries:
    Node: 8.11.4 - ~/.config/fnm/bin/node
    Yarn: 1.9.4 - ~/.config/fnm/bin/yarn
    npm: 6.4.1 - ~/.config/fnm/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 61.0.2
    Safari: 12.0
  npmPackages:
    gatsby: next => 2.0.0-rc.13
    gatsby-image: next => 2.0.0-rc.1
    gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11
    gatsby-plugin-sharp: next => 2.0.0-rc.3
    gatsby-plugin-styled-components: ^2.0.11 => 2.0.11
    gatsby-plugin-typography: ^1.7.19 => 1.7.19
    gatsby-source-filesystem: ^1.5.39 => 1.5.39
    gatsby-transformer-remark: ^1.7.44 => 1.7.44
  npmGlobalPackages:
```
Also here's some screenshots for clarity:

https://imgur.com/a/tOzNXUh

**Comment by pieh** [comment]
Please check https://next.gatsbyjs.org/docs/static-query/#how-staticquery-differs-from-page-query

StaticQuery is not replacement for page queries and does not receive any variables - you should use "traditional" page query in your page components. We will be looking in future to create `PageQuery` component but we aren't there yet.

**Comment by samlazrak** [comment]
Okay that makes sense. What exactly do I need to change and how?

**Comment by pieh** [comment]
check https://github.com/gatsbyjs/gatsby-starter-blog/blob/v2/src/templates/blog-post.js for how page queries are implemented (named export at the bottom of file) gatsby at build time will catch that and insert `data` prop to your template component - see https://github.com/gatsbyjs/gatsby-starter-blog/blob/2e5d8547462374304241a88b8e51dde2ab2fac70/src/templates/blog-post.js#L12 how it is being used

**Comment by samlazrak** [comment]
Thank you, that helped.
