### ISSUE TITLE
[gatsbyjs-store] Inconsistent OG Tags for store.gatsbyjs.org

### ISSUE THREAD

**Issue by mikelax** [gatsbyjs/gatsby#7961]
## Description

When viewing the gatsbyjs store through something that lints the page, ie. the Facebook Debugger the OG tags and thus rendered display are not correct. The current values are a mix of values from both the black t-shirt and socks. They should be more general and apply to a storefront, not a single item (that would make sense if each item had its own URL). 

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

The OG tags should be consistent and make sense for a general store homepage. 

### Actual result

Here is the result of what I am seeing in the Facebook debugger. 
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fstore.gatsbyjs.org%2F

| og:url | https://store.gatsbyjs.org/ |
| ------------- | ------------- |
og:type | website
og:title | Gatsby Store
og:image | https://store.gatsbyjs.org/static/d8979cd87644af7316a8554e83511d5d-a3a6c096c4ab226d2c24cce771e5463a-63db5.jpg
og:description | Get your feet into these black socks with a Gatsby purple border and heel. The bright pops of color keep it fun while keeping you warm.
og:updated_time | 1536327762
ia:markup_url |  
ia:markup_url_dev |  
ia:rules_url |  
ia:rules_url_dev |  
| og:image:alt | Dark Deploy Tee |

### Environment

Visit https://store.gatsbyjs.org and view the OG tags, or run the URL through the [Facebook Debugger](https://developers.facebook.com/tools/debug/).

**Comment by cometkim** [comment]
:hand: I'd like to work on this

**Comment by pieh** [comment]
Hey @mikelax, could you move this issue to https://github.com/gatsbyjs/store.gatsbyjs.org repo (which is where actual store site code is)?

**Comment by mikelax** [comment]
@pieh  sure, sorry I didn't realize the store had a separate repo. will move now.

**Comment by pieh** [comment]
@mikelax that's all right! It's great that you raised that issue! And as far as I can tell - most of it already got implemented and merged ( https://github.com/gatsbyjs/store.gatsbyjs.org/pull/135 ) so huge thanks for that! ❤️
