### ISSUE TITLE
Integrate eslint on www/ 

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#7963]
## Summary

We should run eslint on www/ as part of the Travis build, and additionally we should fix any issues that eslint identifies.

(Also we could run this as a git commit hook, but I'm less opinionated on that!)

### Motivation

Linting is generally valuable at catching some helpful code quality errors, and introducing linting as a git hook or as part of Travis will catch those errors early before something happens in a later phase (e.g. build phase).

In general, getting ESLint passing without any failures signifies that for at least code quality things that can be automated, we have a quality product :)

cc @berraknil if you're curious!

**Comment by LekoArts** [comment]
Global `eslint` is now also running the `/www` code 👍
