### ISSUE TITLE
Integrate prettier on www/

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#7964]
## Summary

We should use some automated tooling to ensure that our code in www/ gets prettified as part of the pull request. I've seen us use a prettier bot on other repos, so that could be a technique, or we could use a git hook with something like husky.

(Also there's no reason this approach couldn't be applied to all JS files, e.g. those outside of www/)

### Motivation

Running prettier (through automated processes) lessens the significance of any code style nits, bceause we'll be using a unified style via automated processes in the PR/commit itself.

The expected outcome is that our code will be pretty, and in a unified style.

### More Detail

If we go the git hook route, I've had a lot of success with the following combo:

- `husky`
  - gives us git lifecycle hooks as package scripts (e.g. precommit will be run before commit)
- `pretty-quick`
  - Tool that can apply prettier only on staged files as part of a lifecycle hook
- `prettier`
  - The engine of all of this

So wiring it all up would look like this

#### Install

```bash
yarn add prettier pretty-quick husky
```

*package.json*

```json
{
  "scripts": {
    "precommit": "pretty-quick --staged"
  }
}
```

cc @berraknil if you're interested!

**Comment by LekoArts** [comment]
Prettier and husky and all that kind of stuff was added in the meantime, so close this as resolved!
