### ISSUE TITLE
export GATSBY_CONTENTFUL_OFFLINE=true 

### ISSUE THREAD

**Issue by iammatthias** [gatsbyjs/gatsby#7973]
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/README.md#offline

## Summary

The gatsby-source-contentful documentation says `If you don't have internet connection you can add export GATSBY_CONTENTFUL_OFFLINE=true to tell the plugin to fallback to the cached data, if there is any.`

Where should the `export GATSBY_CONTENTFUL_OFFLINE=true` be added?

**Comment by DSchau** [comment]
That could probably be clarified!

For now, I believe that just means we'll make a network request if that environment variable isn't set (https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/src/gatsby-node.js#L46)

There's a few ways to set environment variables. In Gatsby, you could try adding `GATSBY_CONTENTFUL_OFFLINE=true` to .env.development, and then see if that works out for you!

Thanks; let us know if we can help further!

**Comment by iammatthias** [comment]
Got it, thanks!
