### ISSUE TITLE
[www] Inconsistent accordion behavior in docs sidebar

### ISSUE THREAD

**Issue by kkemple** [gatsbyjs/gatsby#7975]
The title and button in sidebar sections behave differently when clicked. The title will collapse all other sections while the button keeps surrounding sections open. This causes inconsistency and in the case of title, some jumping of the sidebar. @KyleAMathews and I discussed this and have a fix I can implement.

**Comment by fk** [comment]
> The title will collapse all other sections while the button keeps surrounding sections open.

Wow, this is weird…and def. not what I intended to do here.
Thanks for catching! 🙏
