### ISSUE TITLE
Site Showcase - "Top categories" and "All categories"

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#7980]
## Summary

Because there is a growing number of categories (tags) in the Site Showcase, I thought it would make sense to prioritize a certain number of categories in a new block called "Top Categories" including these (also to be sorted by popularity of the category):
- eCommerce (100)
- Blogs (70)
- Documentation (57)
- Portfolios (55)
- Marketing (43)
- Apps (20)

Then, we also thought it would be useful to retitle the current "Categories" as "All Categories" and sort it by popularity.

### Motivation

The expected outcome is to further emphasize the kinds of Gatsby sites that show that Gatsby can do more than small static sites and can do beautiful sites.

**Comment by riencoertjens** [comment]
why would there be lists of categories if you sort them both by popularity?

**Comment by riencoertjens** [comment]
I think it just dawned on me you're suggesting a 'featured categories' and 'all categories'

**Comment by shannonbux** [comment]
Yes, "Featured Categories" is a much more accurate name! Thanks
@riencoertjens!
