### ISSUE TITLE
[www] twitter ios nav bar overlaps ours

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#7986]
- https://twitter.com/rchrdnsh/status/1038260112467484672
- https://twitter.com/rchrdnsh/status/1038260324174970881

![dmikqocu0aawp3k](https://user-images.githubusercontent.com/71047/45249933-ca848880-b2dd-11e8-87c2-d88eb417be80.jpg)

**Comment by rchrdnsh** [comment]
Yay! I made a good first issue :-)

I’ve noticed this behavior in iOS Safari in general on other sites as well, although Gatsbyjs.org seems to be ok there, at least for me. Might be a WebKit bug?

**Comment by 07Gond** [comment]
Maybe we can specify the version and model of iPhone and iOS?
I tried this on iPhone 7 & 8 and everything is ok.

**Comment by dantesolis** [comment]
I could take this issue, if no one is working on it :)

**Comment by 07Gond** [comment]
@dantesolis Did you reproduce the bug? I can't.

**Comment by rchrdnsh** [comment]
apologies, it’s an iPhone X running iOS 11.4.1.

**Comment by dantesolis** [comment]
@07Gond I hadn’t I just saw the issue was open and wanted to give it a try.  I’ll try to reproduce the issue.  Thanks @rchrdnsh.

**Comment by fk** [comment]
That'd be great @dantesolis! 🙏

**Comment by dantesolis** [comment]
hey guys, quick update. I'm currently working on this issue.

**Comment by 07Gond** [comment]
Post here any update or if you need help 💪

**Comment by hamiltondanielb** [comment]
I will take this.

**Comment by dantesolis** [comment]
@07Gond I actually had a question, how could I "force" that  twitter navigation bar? should I mock another component or something like that? Thanks

**Comment by 07Gond** [comment]
Hi! @dantesolis 
I was thinking about doing some simple swift code to run on a WKWebView that URL.
I just tried that but with the iOS 12 simulator.

- The fixed position of that bar is not respected:
![image](https://user-images.githubusercontent.com/2708687/46457732-042f9e80-c779-11e8-81ab-6dc470b4311d.png)
- If you scroll down to the bottom you can see the bar:
![image](https://user-images.githubusercontent.com/2708687/46457782-2fb28900-c779-11e8-8ab1-9ad9130bb323.png)

I don't have an iPhone X so, I don't know if the device with iOS12 has the same behavior.
About the replication of the error in this issue maybe you can try the same but with an iOS 11.4 simulator. Maybe that issue is only visible on that version or maybe we have to do more for the replication.

**Comment by dantesolis** [comment]
Hey guys, question. Is this still open? I was working on it. But then got sidetracked 🙃 , but don't know if it's still open and not solved ? If so I'll take (again) if possible 😄

**Comment by fk** [comment]
Hey @dantesolis! I _think_ this is still open, but I don't have the things needed to test myself right now. :( Could you do that?

I'll remove the `stale` label from the issue for now.

**Comment by dantesolis** [comment]
@fk will do. Thanks man ;)

**Comment by fk** [comment]
@dantesolis Yay! Thank _you_! 🤗

**Comment by dantesolis** [comment]
not stale working on it 😄

**Comment by dantesolis** [comment]
not stale, fuudge why does time passes so quickly ??? gonna push tis weekend or latest end of next week. Have been hammered at work
Thanks and sorry for the delay

**Comment by laurosilvacom** [comment]
@dantesolis any progress on this? If you're not working on it. I would like to help out!

**Comment by dantesolis** [comment]
@laurosilvacom to tell you the truth I have been hammered 🔨 at work lately so haven't had time to look at it, was about to start working on it, but help is always welcome.  Have you made any progress thus far ?

**Comment by PatrickResponsive** [comment]
Hey Guys,

Can I grab this issue?  @dantesolis did you make any progress?

**Comment by PatrickLambert1101** [comment]
Hey guys can I grab this issue?

@dantesolis did you make any progress?

**Comment by dantesolis** [comment]
@PatrickLambert1101 feel free to take it, cause I've been hammered at work lately and now is just sitting here.  Sorry for the not following through folks.

**Comment by PatrickResponsive** [comment]
Awesome! Thanks, could someone please assign it to me 👍

**Comment by PatrickLambert1101** [comment]
Awesome! Thanks, could someone please assign it to me

**Comment by lannonbr** [comment]
@PatrickLambert1101 So I can't assign you using GitHub's assign feature, but I can mark that this issue has been assigned and they can read through this that you wish to work on this.

**Comment by michaelneu** [comment]
@PatrickLambert1101 are you still working on this? I did some research and there are two issues with the current tab bar:

1) [`padding-bottom: env(safe-area-inset-bottom)`](https://github.com/gatsbyjs/gatsby/blob/1288c23400a5a3321cad5761f4807369dd258fe6/www/src/components/navigation-mobile.js#L82) is overwritten by setting the `height` to a [fixed value](https://github.com/gatsbyjs/gatsby/blob/1288c23400a5a3321cad5761f4807369dd258fe6/www/src/components/navigation-mobile.js#L80). The safe area on the iPhone X (or newer) isn't respected, thus the tab bar is put straight to the bottom.

Removing the `height` using the Safari devtools seems to work on my iPhone XR. Adding `transition: padding-bottom 0.2s` smooths the transition a bit on Safari.

2) Twitter's WKWebView apparently doesn't update `safe-area-inset-bottom` and generally overlaps the viewport. I used this test page:

```html
<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>
  <body>
    <div style="position: fixed; bottom: 0px; left: 0px; right: 0px;">
      <div style="height: 34px; background-color: red;"></div>
      <div id="bottom-spacer" style="height: env(safe-area-inset-bottom); background-color: black;"></div>
    </div>
  
    <div class="size"></div>
    <div style="height: 1000px;"></div>
    <div class="size"></div>
    <div style="height: 1000px;"></div>

    <script type="text/javascript">
      function updateSizeLabel() {
        const spacer = document.querySelector("#bottom-spacer");

        document
          .querySelectorAll(".size")
          .forEach((x) => x.innerHTML = `
            inner window height: ${window.innerWidth}x${window.innerHeight}
            <br />
            outer window height: ${window.outerWidth}x${window.outerHeight}
            <br />
            spacer height: ${spacer.getBoundingClientRect().height}px
          `);

        spacer.innerHTML = `height`;
      }

      updateSizeLabel();
      window.addEventListener("resize", updateSizeLabel);
    </script>
  </body>
</html>
```

When scrolling in Safari, the spacer height updates to 34px whenever the tab bar is hidden. However, in Twitter's browser it stays at 0px. As far as my test goes, it seems like those 34px padding are required to not be hidden by Twitter's tab bar, as I suspect this is happening:

![gatsby-twitter-overlap](https://user-images.githubusercontent.com/5105833/62660607-cab65980-b96e-11e9-94e8-5c019867082d.jpg)

Detecting and correctly calculating the padding for Twitter's browser could be difficult, as the viewport doesn't know it's behind something else. The only "solution" I can think of is always having `padding-bottom: 34px`, so the overlap can safely be ignored. I don't really like this, as it steals screen space, but it would at least prevent Twitter's UI hiding the tab bar.

Also, hard-coding this for Twitter wouldn't be a good idea IMO. The only way (I tried) to find out whether the page was opened in the Twitter browser is to check the `document.referrer`, which could be `t.co` - but this is also the case when opening the page in the browser using the bottom right button. Furthermore, listening for the window resize event doesn't feel right either, even if you _could_ detect the Twitter browser this way.

So, as far as my research goes, there are two ways to solve this at the moment (unless Twitter decides to fix this themselves):

- ignore it for the Twitter browser and just use `env(safe-area-inset-bottom)` to fix it in Safari
- always add a padding of >= 34px to the bottom

If you're not working on this @PatrickLambert1101, I'd like to take over and implement whatever the consensus will be.

**Comment by sidharthachatterjee** [comment]
This doesn't seem to be an issue anymore, as evidenced on my iPhone 11 Pro Max in both Safari as well as the Twitter web view 

Closing this as a result! Thank you everyone 💪

**Comment by fk** [comment]
Ahh nice, thanks @sidharthachatterjee! 🙏 
This made me realize I now have such a phone, too, so I got curious — minor problems remain:

![IMG_9196](https://user-images.githubusercontent.com/21834/74541801-984f6f80-4f42-11ea-9544-0f9ac4a0866d.PNG)

(^ Opening a link to gatsbyjs.org from within the Twitter app, opening the sidebar navigation with the Twitter navbar hidden; if the Twitter navbar is visible, things are fine)
