### ISSUE TITLE
Gatsby Development server not outputting code

### ISSUE THREAD

**Issue by MayerMediaCo** [gatsbyjs/gatsby#7991]
## Description
Upon running Gatsby Develop, the server launches and compiles without a problem.  When going to visit site on local host, nothing renders on the page.

Visiting /admin/ for NetlifyCMS works as expected.

Upon deploying site to Netlify, build fails and produces the following output:

9:37:43 AM:   Error: ./node_modules/gatsby-link/index.js
9:37:43 AM:   Module not found: Error: Can't resolve 'react-router-dom' in '/opt/build/repo/  node_modules/gatsby-link'
9:37:43 AM:   resolve 'react-router-dom' in '/opt/build/repo/node_modules/gatsby-link'
9:37:43 AM:     Parsed request is a module
9:37:43 AM:     using description file: /opt/build/repo/node_modules/gatsby-link/package.jso  n (relative path: .)
9:37:43 AM:       Field 'browser' doesn't contain a valid alias configuration
9:37:43 AM:       resolve as module
9:37:43 AM:         looking for modules in /opt/build/repo/node_modules
9:37:43 AM:           using description file: /opt/build/repo/package.json (relative path: .  /node_modules)
9:37:43 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:43 AM:             using description file: /opt/build/repo/package.json (relative path:   ./node_modules/react-router-dom)
9:37:43 AM:               no extension
9:37:43 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:43 AM:                 /opt/build/repo/node_modules/react-router-dom doesn't exist
9:37:43 AM:               .js
9:37:43 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:43 AM:                 /opt/build/repo/node_modules/react-router-dom.js doesn't exist
9:37:43 AM:               .jsx
9:37:43 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:43 AM:                 /opt/build/repo/node_modules/react-router-dom.jsx doesn't exist
9:37:43 AM:               as directory
9:37:43 AM:                 /opt/build/repo/node_modules/react-router-dom doesn't exist
9:37:43 AM:         /opt/build/repo/node_modules/gatsby-link/node_modules doesn't exist or i  s not a directory
9:37:43 AM:         /opt/build/repo/node_modules/node_modules doesn't exist or is not a dire  ctory
9:37:43 AM:         /opt/build/node_modules doesn't exist or is not a directory
9:37:43 AM:         /opt/node_modules doesn't exist or is not a directory
9:37:43 AM:         /node_modules doesn't exist or is not a directory
9:37:43 AM:         looking for modules in /opt/build/repo/node_modules/gatsby-link/
9:37:43 AM:           using description file: /opt/build/repo/node_modules/gatsby-link/packa  ge.json (relative path: .)
9:37:43 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:43 AM:         looking for modules in /opt/build/repo/
9:37:43 AM:           using description file: /opt/build/repo/package.json (relative path: .  )
9:37:43 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:43 AM:         looking for modules in /
9:37:43 AM:           No description file found
9:37:43 AM:           Field 'browser' doesn't contain a valid alias configuration
9:37:43 AM:         looking for modules in /opt/build/repo/node_modules
9:37:43 AM:           using description file: /opt/build/repo/package.json (relative path: .  /node_modules)
9:37:43 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:43 AM:             using description file: /opt/build/repo/node_modules/gatsby-link/pac  kage.json (relative path: ./react-router-dom)
9:37:43 AM:               no extension
9:37:43 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:43 AM:         looking for modules in /opt/build/repo/node_modules/
9:37:43 AM:           using description file: /opt/build/repo/package.json (relative path: .  /node_modules/)
9:37:44 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:44 AM:             using description file: /opt/build/repo/package.json (relative path:   ./react-router-dom)
9:37:44 AM:               no extension
9:37:44 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:44 AM:         looking for modules in /opt/
9:37:44 AM:           No description file found
9:37:44 AM:           Field 'browser' doesn't contain a valid alias configuration
9:37:44 AM:           No description file found
9:37:44 AM:           no extension
9:37:44 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:44 AM:         looking for modules in /opt/build/
9:37:44 AM:           No description file found
9:37:44 AM:           Field 'browser' doesn't contain a valid alias configuration
9:37:44 AM:                 /opt/build/repo/node_modules/gatsby-link/react-router-dom doesn'  t exist
9:37:44 AM:               .js
9:37:44 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:44 AM:             using description file: /opt/build/repo/package.json (relative path:   ./node_modules/react-router-dom)
9:37:44 AM:               no extension
9:37:44 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:44 AM:                 /opt/build/repo/react-router-dom doesn't exist
9:37:44 AM:               .js
9:37:44 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:44 AM:             /react-router-dom doesn't exist
9:37:44 AM:           .js
9:37:44 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:44 AM:             using description file: /opt/build/repo/package.json (relative path:   ./node_modules/react-router-dom)
9:37:44 AM:               no extension
9:37:44 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:44 AM:           No description file found
9:37:44 AM:           no extension
9:37:44 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:44 AM:                 /opt/build/repo/node_modules/gatsby-link/react-router-dom.js doe  sn't exist
9:37:44 AM:               .jsx
9:37:44 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:44 AM:                 /opt/build/repo/node_modules/react-router-dom doesn't exist
9:37:44 AM:               .js
9:37:44 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:44 AM:                 /opt/build/repo/react-router-dom.js doesn't exist
9:37:44 AM:               .jsx
9:37:44 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:44 AM:             /react-router-dom.js doesn't exist
9:37:44 AM:           .jsx
9:37:44 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:44 AM:                 /opt/build/repo/node_modules/react-router-dom doesn't exist
9:37:44 AM:               .js
9:37:44 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:44 AM:           No description file found
9:37:44 AM:           no extension
9:37:44 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:44 AM:             /opt/react-router-dom doesn't exist
9:37:44 AM:           .js
9:37:44 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:44 AM:                 /opt/build/repo/node_modules/gatsby-link/react-router-dom.jsx do  esn't exist
9:37:44 AM:                 /opt/build/repo/node_modules/react-router-dom.js doesn't exist
9:37:44 AM:               .jsx
9:37:44 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:44 AM:                 /opt/build/repo/react-router-dom.jsx doesn't exist
9:37:44 AM:             /react-router-dom.jsx doesn't exist
9:37:44 AM:               as directory
9:37:44 AM:                 /opt/build/repo/node_modules/gatsby-link/react-router-dom doesn'  t exist
9:37:44 AM:                 /opt/build/repo/node_modules/react-router-dom.js doesn't exist
9:37:44 AM:               .jsx
9:37:44 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:44 AM:               as directory
9:37:44 AM:                 /opt/build/repo/react-router-dom doesn't exist
9:37:44 AM:             /opt/build/react-router-dom doesn't exist
9:37:45 AM:           .js
9:37:45 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:45 AM:             /opt/react-router-dom.js doesn't exist
9:37:45 AM:           .jsx
9:37:45 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:45 AM:           as directory
9:37:45 AM:             /react-router-dom doesn't exist
9:37:45 AM:                 /opt/build/repo/node_modules/react-router-dom.jsx doesn't exist
9:37:45 AM:                 /opt/build/repo/node_modules/react-router-dom.jsx doesn't exist
9:37:45 AM:               as directory
9:37:45 AM:                 /opt/build/repo/node_modules/react-router-dom doesn't exist
9:37:45 AM:             /opt/build/react-router-dom.js doesn't exist
9:37:45 AM:           .jsx
9:37:45 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:45 AM:             /opt/react-router-dom.jsx doesn't exist
9:37:45 AM:               as directory
9:37:45 AM:                 /opt/build/repo/node_modules/react-router-dom doesn't exist
9:37:45 AM:           as directory
9:37:45 AM:             /opt/react-router-dom doesn't exist
9:37:45 AM:             /opt/build/react-router-dom.jsx doesn't exist
9:37:45 AM:           as directory
9:37:45 AM:             /opt/build/react-router-dom doesn't exist
9:37:45 AM:   [/opt/build/repo/node_modules/react-router-dom]
9:37:45 AM:   [/opt/build/repo/node_modules/react-router-dom.js]
9:37:45 AM:   [/opt/build/repo/node_modules/react-router-dom.jsx]
9:37:45 AM:   [/opt/build/repo/node_modules/gatsby-link/node_modules]
9:37:45 AM:   [/opt/build/repo/node_modules/node_modules]
9:37:45 AM:   [/opt/build/node_modules]
9:37:45 AM:   [/opt/node_modules]
9:37:45 AM:   [/node_modules]
9:37:45 AM:   [/package.json]
9:37:45 AM:   [/opt/package.json]
9:37:45 AM:   [/react-router-dom/package.json]
9:37:45 AM:   [/opt/build/package.json]
9:37:45 AM:   [/opt/build/repo/node_modules/gatsby-link/react-router-dom]
9:37:45 AM:   [/opt/build/repo/react-router-dom]
9:37:45 AM:   [/react-router-dom]
9:37:45 AM:   [/opt/react-router-dom/package.json]
9:37:45 AM:   [/opt/build/repo/node_modules/gatsby-link/react-router-dom.js]
9:37:45 AM:   [/opt/build/repo/react-router-dom.js]
9:37:45 AM:   [/react-router-dom.js]
9:37:45 AM:   [/opt/build/react-router-dom/package.json]
9:37:45 AM:   [/opt/react-router-dom]
9:37:45 AM:   [/opt/build/repo/node_modules/gatsby-link/react-router-dom.jsx]
9:37:45 AM:   [/opt/build/repo/react-router-dom.jsx]
9:37:45 AM:   [/react-router-dom.jsx]
9:37:45 AM:   [/opt/build/react-router-dom]
9:37:45 AM:   [/opt/react-router-dom.js]
9:37:45 AM:   [/opt/build/react-router-dom.js]
9:37:45 AM:   [/opt/react-router-dom.jsx]
9:37:45 AM:   [/opt/build/react-router-dom.jsx]
9:37:45 AM:    @ ./node_modules/gatsby-link/index.js 36:22-49
9:37:45 AM:    @ ./src/pages/about.js
9:37:45 AM:    @ ./.cache/async-requires.js
9:37:45 AM:    @ ./.cache/production-app.js
9:37:45 AM: 
9:37:45 AM: 
9:37:45 AM:   Error: ./node_modules/gatsby-react-router-scroll/ScrollBehaviorContext.js
9:37:45 AM:   Module not found: Error: Can't resolve 'react-router-dom' in '/opt/build/repo/  node_modules/gatsby-react-router-scroll'
9:37:45 AM:   resolve 'react-router-dom' in '/opt/build/repo/node_modules/gatsby-react-route  r-scroll'
9:37:46 AM:     Parsed request is a module
9:37:46 AM:     using description file: /opt/build/repo/node_modules/gatsby-react-router-scr  oll/package.json (relative path: .)
9:37:46 AM:       Field 'browser' doesn't contain a valid alias configuration
9:37:46 AM:       resolve as module
9:37:46 AM:         looking for modules in /opt/build/repo/node_modules
9:37:46 AM:           using description file: /opt/build/repo/package.json (relative path: .  /node_modules)
9:37:46 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:46 AM:             using description file: /opt/build/repo/package.json (relative path:   ./node_modules/react-router-dom)
9:37:46 AM:               no extension
9:37:46 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:46 AM:                 /opt/build/repo/node_modules/react-router-dom doesn't exist
9:37:46 AM:               .js
9:37:46 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:46 AM:                 /opt/build/repo/node_modules/react-router-dom.js doesn't exist
9:37:46 AM:               .jsx
9:37:46 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:46 AM:                 /opt/build/repo/node_modules/react-router-dom.jsx doesn't exist
9:37:46 AM:               as directory
9:37:46 AM:                 /opt/build/repo/node_modules/react-router-dom doesn't exist
9:37:46 AM:         /opt/build/repo/node_modules/gatsby-react-router-scroll/node_modules doe  sn't exist or is not a directory
9:37:46 AM:         /opt/build/repo/node_modules/node_modules doesn't exist or is not a dire  ctory
9:37:46 AM:         /opt/build/node_modules doesn't exist or is not a directory
9:37:46 AM:         /opt/node_modules doesn't exist or is not a directory
9:37:46 AM:         /node_modules doesn't exist or is not a directory
9:37:46 AM:         looking for modules in /opt/build/repo/node_modules/gatsby-react-router-  scroll/
9:37:46 AM:           using description file: /opt/build/repo/node_modules/gatsby-react-rout  er-scroll/package.json (relative path: .)
9:37:46 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:46 AM:         looking for modules in /opt/build/repo/
9:37:46 AM:           using description file: /opt/build/repo/package.json (relative path: .  )
9:37:46 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:46 AM:         looking for modules in /
9:37:46 AM:           No description file found
9:37:46 AM:           Field 'browser' doesn't contain a valid alias configuration
9:37:46 AM:         looking for modules in /opt/build/repo/node_modules
9:37:46 AM:           using description file: /opt/build/repo/package.json (relative path: .  /node_modules)
9:37:46 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:46 AM:             using description file: /opt/build/repo/node_modules/gatsby-react-ro  uter-scroll/package.json (relative path: ./react-router-dom)
9:37:46 AM:               no extension
9:37:46 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:46 AM:         looking for modules in /opt/build/repo/node_modules/
9:37:46 AM:           using description file: /opt/build/repo/package.json (relative path: .  /node_modules/)
9:37:46 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:46 AM:             using description file: /opt/build/repo/package.json (relative path:   ./react-router-dom)
9:37:46 AM:               no extension
9:37:46 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:46 AM:         looking for modules in /opt/
9:37:46 AM:           No description file found
9:37:46 AM:           Field 'browser' doesn't contain a valid alias configuration
9:37:46 AM:           No description file found
9:37:46 AM:           no extension
9:37:46 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:46 AM:         looking for modules in /opt/build/
9:37:46 AM:           No description file found
9:37:46 AM:           Field 'browser' doesn't contain a valid alias configuration
9:37:46 AM:                 /opt/build/repo/node_modules/gatsby-react-router-scroll/react-ro  uter-dom doesn't exist
9:37:46 AM:               .js
9:37:46 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:46 AM:             using description file: /opt/build/repo/package.json (relative path:   ./node_modules/react-router-dom)
9:37:46 AM:               no extension
9:37:46 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:46 AM:                 /opt/build/repo/react-router-dom doesn't exist
9:37:46 AM:               .js
9:37:46 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:46 AM:             /react-router-dom doesn't exist
9:37:46 AM:           .js
9:37:47 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:47 AM:             using description file: /opt/build/repo/package.json (relative path:   ./node_modules/react-router-dom)
9:37:47 AM:               no extension
9:37:47 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:47 AM:           No description file found
9:37:47 AM:           no extension
9:37:47 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:47 AM:                 /opt/build/repo/node_modules/gatsby-react-router-scroll/react-ro  uter-dom.js doesn't exist
9:37:47 AM:               .jsx
9:37:47 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:47 AM:                 /opt/build/repo/node_modules/react-router-dom doesn't exist
9:37:47 AM:               .js
9:37:47 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:47 AM:                 /opt/build/repo/react-router-dom.js doesn't exist
9:37:47 AM:               .jsx
9:37:47 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:47 AM:             /react-router-dom.js doesn't exist
9:37:47 AM:           .jsx
9:37:47 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:47 AM:                 /opt/build/repo/node_modules/react-router-dom doesn't exist
9:37:47 AM:               .js
9:37:47 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:47 AM:           No description file found
9:37:47 AM:           no extension
9:37:47 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:47 AM:             /opt/react-router-dom doesn't exist
9:37:47 AM:           .js
9:37:47 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:47 AM:                 /opt/build/repo/node_modules/gatsby-react-router-scroll/react-ro  uter-dom.jsx doesn't exist
9:37:47 AM:                 /opt/build/repo/node_modules/react-router-dom.js doesn't exist
9:37:47 AM:               .jsx
9:37:47 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:47 AM:                 /opt/build/repo/react-router-dom.jsx doesn't exist
9:37:47 AM:             /react-router-dom.jsx doesn't exist
9:37:47 AM:               as directory
9:37:47 AM:                 /opt/build/repo/node_modules/gatsby-react-router-scroll/react-ro  uter-dom doesn't exist
9:37:47 AM:                 /opt/build/repo/node_modules/react-router-dom.js doesn't exist
9:37:47 AM:               .jsx
9:37:47 AM:                 Field 'browser' doesn't contain a valid alias configuration
9:37:47 AM:               as directory
9:37:47 AM:                 /opt/build/repo/react-router-dom doesn't exist
9:37:47 AM:             /opt/build/react-router-dom doesn't exist
9:37:47 AM:           .js
9:37:47 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:47 AM:             /opt/react-router-dom.js doesn't exist
9:37:47 AM:           .jsx
9:37:47 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:47 AM:           as directory
9:37:47 AM:             /react-router-dom doesn't exist
9:37:47 AM:                 /opt/build/repo/node_modules/react-router-dom.jsx doesn't exist
9:37:47 AM:                 /opt/build/repo/node_modules/react-router-dom.jsx doesn't exist
9:37:47 AM:               as directory
9:37:47 AM:                 /opt/build/repo/node_modules/react-router-dom doesn't exist
9:37:47 AM:             /opt/build/react-router-dom.js doesn't exist
9:37:47 AM:           .jsx
9:37:47 AM:             Field 'browser' doesn't contain a valid alias configuration
9:37:47 AM:             /opt/react-router-dom.jsx doesn't exist
9:37:47 AM:               as directory
9:37:47 AM:                 /opt/build/repo/node_modules/react-router-dom doesn't exist
9:37:47 AM:           as directory
9:37:47 AM:             /opt/react-router-dom doesn't exist
9:37:47 AM:             /opt/build/react-router-dom.jsx doesn't exist
9:37:48 AM:           as directory
9:37:48 AM:             /opt/build/react-router-dom doesn't exist
9:37:48 AM:   [/opt/build/repo/node_modules/react-router-dom]
9:37:48 AM:   [/opt/build/repo/node_modules/react-router-dom.js]
9:37:48 AM:   [/opt/build/repo/node_modules/react-router-dom.jsx]
9:37:48 AM:   [/opt/build/repo/node_modules/gatsby-react-router-scroll/node_modules]
9:37:48 AM:   [/opt/build/repo/node_modules/node_modules]
9:37:48 AM:   [/opt/build/node_modules]
9:37:48 AM:   [/opt/node_modules]
9:37:48 AM:   [/node_modules]
9:37:48 AM:   [/package.json]
9:37:48 AM:   [/opt/package.json]
9:37:48 AM:   [/react-router-dom/package.json]
9:37:48 AM:   [/opt/build/package.json]
9:37:48 AM:   [/opt/build/repo/node_modules/gatsby-react-router-scroll/react-router-dom]
9:37:48 AM:   [/opt/build/repo/react-router-dom]
9:37:48 AM:   [/react-router-dom]
9:37:48 AM:   [/opt/react-router-dom/package.json]
9:37:48 AM:   [/opt/build/repo/node_modules/gatsby-react-router-scroll/react-router-dom.js]
9:37:48 AM:   [/opt/build/repo/react-router-dom.js]
9:37:48 AM:   [/react-router-dom.js]
9:37:48 AM:   [/opt/build/react-router-dom/package.json]
9:37:48 AM:   [/opt/react-router-dom]
9:37:48 AM:   [/opt/build/repo/node_modules/gatsby-react-router-scroll/react-router-dom.jsx]  [/opt/build/repo/react-router-dom.jsx]
9:37:48 AM:   [/react-router-dom.jsx]
9:37:48 AM:   [/opt/build/react-router-dom]
9:37:48 AM:   [/opt/react-router-dom.js]
9:37:48 AM:   [/opt/build/react-router-dom.js]
9:37:48 AM:   [/opt/react-router-dom.jsx]
9:37:48 AM:   [/opt/build/react-router-dom.jsx]
9:37:48 AM:    @ ./node_modules/gatsby-react-router-scroll/ScrollBehaviorContext.js 21:22-49   @ ./node_modules/gatsby-react-router-scroll/index.js
9:37:48 AM:    @ ./.cache/production-app.js

### Steps to reproduce

1. Run Gatsby Develop
2. Visit localhost 8000
3. Page renders no content

 [Link to repo](https://github.com/MayerMediaCo/mayermediaco)

### Expected result

Dev environment should be loading content as expected

### Actual result

Dev server loads properly but does not render code

### Environment

`System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.3 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.0.0-rc.14 => 2.0.0-rc.14
    gatsby-link: ^1.6.46 => 1.6.46
    gatsby-plugin-favicon: ^3.1.4 => 3.1.4
    gatsby-plugin-google-analytics: ^1.0.31 => 1.0.31
    gatsby-plugin-google-fonts: 0.0.4 => 0.0.4
    gatsby-plugin-mailchimp: ^2.2.3 => 2.2.3
    gatsby-plugin-netlify-cms: ^3.0.0-rc.1 => 3.0.0-rc.1
    gatsby-plugin-react-helmet: next => 3.0.0-rc.1
    gatsby-plugin-remove-trailing-slashes: ^1.0.9 => 1.0.9
    gatsby-plugin-sass: ^2.0.0-rc.2 => 2.0.0-rc.2
    gatsby-react-router-scroll: ^1.0.18 => 1.0.18
    gatsby-source-filesystem: ^1.5.39 => 1.5.39
    gatsby-transformer-remark: ^1.7.44 => 1.7.44
  npmGlobalPackages:
    gatsby-cli: 1.1.58
`

**Comment by davidbailey00** [comment]
You've got some mismatching plugin versions. To fix your issues, upgrade the following packages with Yarn:

```
yarn add gatsby-link@next gatsby-plugin-google-analytics@next gatsby-react-router-scroll@next gatsby-source-filesystem@next gatsby-transformer-remark@next
```

Also, it's not recommended to use `package-lock.json` and `yarn.lock` at the same time due to possible mismatching package versions, so I'd suggest you remove one of these (probably `package-lock.json` if you normally use Yarn).

Hope that helps! Let me know if you're still having problems
