### ISSUE TITLE
replaceComponentRenderer not passing component argument?

### ISSUE THREAD

**Issue by kmcaloon** [gatsbyjs/gatsby#7994]
I'm sure I am missing something here.  I am trying to wrap my pages within a layout as well as context provider. After reading up on this, I found the best way to accomplish this in v2 is either to use a plugin or modify the component renderer by implementing replaceComponentRenderer within gatsby-browser.js. I am not using the plugin both because of preference and also the plugin didn't seem to work for me either.

Here is what my gatsby-browser.js looks like:

```
import React, { createElement } from 'react';
import Base from 'components/layouts/Base';
import { AppProvider } from 'stores/AppContext';
import { Router } from 'react-router-dom';

export const replaceComponentRenderer = ({ props, component }) => {

  return(

    <AppProvider>
      <Base>{ createElement(component, props) }</Base>
    </AppProvider>

  )

}
```

Here is what console is giving me:

```
Applications/MAMP/htdocs/bridge-cms/node_modules/react-error-overlay/lib/index.js:2172 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `PageRenderer`.
    in PageRenderer (created by JSONStore)
    in JSONStore (created by Route)
    in Route (created by Root)
    in ScrollContext (created by Route)
    in Route (created by withRouter(ScrollContext))
    in withRouter(ScrollContext) (created by Root)
    in Router (created by Root)
    in Root (created by HotExportedRoot)
    in AppContainer (created by HotExportedRoot)
    in HotExportedRoot
```

Am I doing something wrong here or is this a bug with v2? 

### Environment

  System:
    OS: OS X El Capitan 10.11.6
    CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 9.5.0 - /usr/local/bin/node
    Yarn: 1.3.2 - ~/.yarn/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 61.0.1
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.0.0-beta.29 => 2.0.0-beta.34 
    gatsby-image: ^2.0.0-beta.6 => 2.0.0-beta.6 
    gatsby-link: ^2.0.0-beta.4 => 2.0.0-beta.4 
    gatsby-plugin-babel: ^1.0.0 => 1.0.0 
    gatsby-plugin-catch-links: ^2.0.2-beta.2 => 2.0.2-beta.2 
    gatsby-plugin-manifest: ^2.0.2-beta.2 => 2.0.2-beta.2 
    gatsby-plugin-offline: ^2.0.0-beta.3 => 2.0.0-beta.3 
    gatsby-plugin-preact: ^2.0.0-rc.1 => 2.0.0-rc.1 
    gatsby-plugin-react-helmet: v2 => 2.0.11 
    gatsby-plugin-sass: ^2.0.0-beta.5 => 2.0.0-beta.5 
    gatsby-plugin-sharp: ^2.0.0-beta.3 => 2.0.0-beta.5 
    gatsby-plugin-sitemap: ^2.0.0-beta.2 => 2.0.0-beta.2 
    gatsby-remark-images: ^2.0.1-beta.4 => 2.0.1-beta.6 
    gatsby-source-filesystem: ^2.0.1-beta.3 => 2.0.1-beta.3 
    gatsby-transformer-remark: ^2.1.1-beta.3 => 2.1.1-beta.3 
    gatsby-transformer-sharp: ^2.1.1-beta.3 => 2.1.1-beta.3 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

**Comment by kakadiadarpan** [comment]
Hi @kmcaloon, you are expecting component as props as per the code above. But the actual API and usage is a little different.

Documentation: [replaceComponentRenderer](https://next.gatsbyjs.org/docs/browser-apis/#replaceComponentRenderer)
Check [this file](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/bootstrap/__tests__/resolve-module-exports.js#L38) for usage (Lines 38-102).
