### ISSUE TITLE
[1.0] Add a precommit hook for auto-formatting

### ISSUE THREAD

**Issue by fabien0102** [gatsbyjs/gatsby#800]
For now, it's a bit painful to do `yarn format` on each commit if we want have beautiful commit (and avoid an ugly final commit for format all forgotten stuffs).

The idea is to add [Hunsky](https://github.com/typicode/husky) & [lint-staged](https://github.com/okonet/lint-staged) for auto-fix each staged file. (example on my wip [gatsby-starter](https://github.com/fabien0102/gatsby-starter/blob/master/package.json#L75))

**Comment by KyleAMathews** [comment]
Great idea! Been thinking about looking into this. Would you like to put together a PR? Until this issue is resolved (https://github.com/okonet/lint-staged/issues/62) using Husky won't work for me as I do a lot of `git add -p`. How about instead we just use this precommit script from the Prettier readme?

```sh
#!/bin/sh
jsfiles=$(git diff --cached --name-only --diff-filter=ACM | grep '\.js$' | tr '\n' ' ')
[ -z "$jsfiles" ] && exit 0

diffs=$(node_modules/.bin/prettier -l $jsfiles)
[ -z "$diffs" ] && exit 0

echo "here"
echo >&2 "Javascript files must be formatted with prettier. Please run:"
echo >&2 "node_modules/.bin/prettier --write "$diffs""

exit 1
```

**Comment by KyleAMathews** [comment]
This is another guide that probably says the same thing as ^^^ https://medium.com/@brindelle/format-your-javascript-with-prettier-before-committing-177079ec356a

**Comment by fabien0102** [comment]
The main problem as than we don't use only prettier (it don't deal with semi-columns…)

I'm on my typescript starter, but I can deal with this issue after :wink: (I've just created this issue to not forgot and have your opinion)

**Comment by KyleAMathews** [comment]
Ahem ;-) http://jlongster.com/prettier-1.0 and https://github.com/gatsbyjs/gatsby/pull/797

**Comment by KyleAMathews** [comment]
Hmm I guess "fixes" doesn't auto close issues. Closing manually. Lemme know @fabien0102 (and others) if this is working! Haven't setup something like this before.
