### ISSUE TITLE
Generate filenames based on hash of the contents, not UUIDs

### ISSUE THREAD

**Issue by wizzard0** [gatsbyjs/gatsby#8000]
## Summary
Generate filenames based on hash (e.g. SHA1) of the file contents, not random UUIDs.

This issue might be viewed as a specific case of #7808, but it can't be solved by specifying a file prefix.

Also, I believe it belongs in the core Gatsby, not into particular plugin, because it's equally useful to all parts of the pipeline

### Basic example

Before:
> /static/idea-62ff5bce87443f91d99221d5aa6f6323-bc327.jpg
> /static/[NAME]-[UUID]-[random-short-uuid].jpg

After:
> /static/[NAME]-[SHA1].jpg

As far as I understand, this change does not cause any backwards compatibility issues.

### Motivation

 - Avoid creating lots of identical files with different names; 
 - Avoid re-uploading identical content;
 - Make sure incoming links to files still work after cleaning obsolete files;
 - Reduce changes to HTML files referencing the same assets;
 - Prepare/simplify emission of subresource integrity tags for future CDN support

**Comment by KyleAMathews** [comment]
Generate filenames for what type of files?
