### ISSUE TITLE
How do i use babel-plugin-transform-decorators-legacy?

### ISSUE THREAD

**Issue by saturnite** [gatsbyjs/gatsby#801]
@KyleAMathews @iansu How `do` i configure gatsby to use babel-plugin-transform-decorators-legacy? included it in `.babelrc`.

Kindly, Help.

**Comment by KyleAMathews** [comment]
Why do you think it doesn't work? What have you tried?

**Comment by saturnite** [comment]
got this cli error......
`.node_modules\gatsby\dist\utils\babel-config.js:161
    babelrc.presets.unshift('react-hmre');
                   ^

TypeError: Cannot read property 'unshift' of undefined
    at babelConfig `

**Comment by saturnite** [comment]
@KyleAMathews tried connecting redux store to a react component. 

` @connect((store)=> {
return {
    me :  store.me,
     first: store.first
   };
})
 export default class Root extends React.Component {
  doSomething(){`
