### ISSUE TITLE
"Loading (StaticQuery)" in react-test-renderer snapshots -- makes automated testing awkward

### ISSUE THREAD

**Issue by DavidSabine** [gatsbyjs/gatsby#8012]
Hi,  I have not been successful writing automated tests around code which uses StaticQuery.  Well, I'm partially successful.

(I'm sorry this is a private repo for now... I'd like to share a file or two, but can't at the moment.  And this input field isn't cooperating with code syntax.)

**I Expect**

I should be able to write tests, requiring 'react-test-renderer' and/or 'react-testing-library', for a Component which uses StaticQuery.  **I cannot.**

Caveat: note that react-helmet is also involved in my case. (But that shouldn't make a difference, should it?)

Example:
In "htmlhead.js"

`import React from "react"
import { StaticQuery, graphql } from "gatsby"
import Helmet from "react-helmet"
export default () => (
	<StaticQuery query={graphql `query HelmetDataQuery {site {siteMetadata {title	}}}`}
		render={data => (<Helmet><html lang="en" /><title>{data.site.siteMetadata.defaultTitle}</title></Helmet>)}/>)`

(Note: the quotes in the graphql query are altered for display here.)

**in Gatsby.config.js**

siteMetadata: {title: 'My title'}

**in htmlhead.test.js**

import React from 'react'
import renderer from 'react-test-renderer'
import HtmlHead from '../htmlhead'

`
describe('HtmlHead', () =>
  it('renders correctly', () => {
    const tree = renderer.create(<HtmlHead />).toJSON()
    expect(tree).toMatchSnapshot()
  })
)
`

**And.... the snapshot  :(  **
`
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports['HtmlHead renders correctly 1'] = '
<div>
  Loading (StaticQuery)
</div>
';
`

****

I *have* successfully written Cypress tests for this same component, and the page loads fine in a browser.

If anyone knows how to overcome this issue, or if I shouldn't expect to be able to test the components in this way, please contribute.

Otherwise, It may be an issue worth investigating.

**Comment by LeKoArts** [comment]
Did you follow these instructions?
https://next.gatsbyjs.org/docs/testing-components-with-graphql/#testing-staticquery

**Comment by DavidSabine** [comment]
Oh my. I did not.

(；一_一)
