### ISSUE TITLE
[Question v2] Gatsby script loader in external file

### ISSUE THREAD

**Issue by outofthisworld** [gatsbyjs/gatsby#8025]
Is there a way that I can have Gatsby load`<script id="gatsby-script-loader">` from an external script file (without manually moving it) ? I would like to set `content-security-policy` headers to not allow inline scripts for security and since this is the only inline script generated for most of my pages I thought it was worth asking. Thanks!

Update: This script also doesn't show up during onPreRenderHTML, is there a way to obtain a reference to the component or is it injected by webpack into the page output ?

**Comment by kakadiadarpan** [comment]
@pieh any inputs on this?

**Comment by outofthisworld** [comment]
For clarification there is two ways I that would work for me, one is that the script loader is loaded from an external script. I think this would mean the script loader would have to be generated for each page. The other idea I had was in pre-render HTML generate a content hash of the script because I want to dynamically create a <meta> tag for the Content-Security-Policy, something like the following:

`export const onPreRenderHTML = ({
    getHeadComponents,
    getPreBodyComponents,
    getPostBodyComponents,
    replaceHeadComponents }) => {

    const allowed = {
        scriptHashes: [],
        styleHashes: []
    }

    getHeadComponents()
        .concat(getPreBodyComponents())
        .concat(getPostBodyComponents())
        .forEach((component) => {
            if (component.type === 'style') {
                const [originalMatch, strippedMatch] = renderToString(component).match(/^<style .*>(.*)<\/style>$/mi)
                const contentHash = `'sha256-${crypto.createHash('sha256').update(strippedMatch).digest('base64')}'`;
                                console.log(component);
                component['props']['data-style-hash'] = contentHash;
                allowed.styleHashes[allowed.styleHashes.length] = contentHash;
            } else if (component.type === 'script') {
                //If it doesn't reference an external script
                if (component.href) return;

                const [originalMatch, strippedMatch] = renderToString(component).match(/^<script .*>(.*)<\/script>$/mi)
                console.log(component)
                const contentHash = `'sha256-${crypto.createHash('sha256').update(strippedMatch).digest('base64')}'`;
                component['props']['data-script-hash'] = contentHash;
                allowed.scriptHashes[allowed.styleHashes.length] = contentHash;
            }
        })
    
    const meta =  <meta http-equiv="Content-Security-Policy" 
    content={`default-src 'self'; connect-src 'self';  script-src 'self' ${allowed.scriptHashes.join(' ').trim()}; style-src 'self' ${allowed.styleHashes.join(' ').trim()}; img-src 'self'`}/>

    replaceHeadComponents([meta].concat(getHeadComponents()))
}`

**Comment by outofthisworld** [comment]
@pieh sure thing, would it be valid to move the `gatsby-chunk-mapping` script in the same PR?

**Comment by pieh** [comment]
yeah, I think moving
```js
apiRunner(`onPreRenderHTML`, {
    getHeadComponents,
    replaceHeadComponents,
    getPreBodyComponents,
    replacePreBodyComponents,
    getPostBodyComponents,
    replacePostBodyComponents,
  })
```

to right before 

```
const html = `<!DOCTYPE html>${renderToStaticMarkup(
    <Html
      {...bodyProps}
      headComponents={headComponents}
      htmlAttributes={htmlAttributes}
      bodyAttributes={bodyAttributes}
      preBodyComponents={preBodyComponents}
      postBodyComponents={postBodyComponents}
      body={bodyHtml}
      path={pagePath}
    />
  )}`
```
makes sense
