### ISSUE TITLE
Move all eslint related dependencies to devDependencies

### ISSUE THREAD

**Issue by jorgegonzalez** [gatsbyjs/gatsby#8033]
## Description

Several ESLint-related dependencies are listed as `dependencies` instead of `devDependencies` and thus are being included in all Gatsby projects.

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/package.json#L50

### Steps to reproduce

`gatsby new project`

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.10.0 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.81
    Firefox: 62.0
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.0.0-rc.7 => 2.0.0-rc.15
    gatsby-plugin-emotion: ^2.0.0-rc.1 => 2.0.0-rc.1
    gatsby-plugin-manifest: ^2.0.2-rc.1 => 2.0.2-rc.1
    gatsby-plugin-netlify: ^2.0.0-rc.1 => 2.0.0-rc.2
    gatsby-plugin-netlify-cache: 0.1.0 => 0.1.0
    gatsby-plugin-offline: ^2.0.0-rc.2 => 2.0.0-rc.6
    gatsby-plugin-react-helmet: ^3.0.0-rc.1 => 3.0.0-rc.1
    gatsby-plugin-sass: 2.0.0-rc.2 => 2.0.0-rc.2
    gatsby-remark-prismjs: ^3.0.0-rc.2 => 3.0.0-rc.2
    gatsby-source-filesystem: ^2.0.1-rc.1 => 2.0.1-rc.2
    gatsby-transformer-remark: ^2.1.1-rc.1 => 2.1.1-rc.1

**Comment by jorgegonzalez** [comment]
I'll happily create a PR for this if the maintainers agree with this change.

**Comment by mikelax** [comment]
Great, thanks. Can you also go through and remove the duplicate packages that in both dependencies and devDependencies? I noticed at least two of the babel packages.

**Comment by mikelax** [comment]
I see all the other *-loader packages listed in the `dependencies`, but [according to the docs eslint-loader](https://github.com/webpack-contrib/eslint-loader) can also be a dev dependency.

I admit though I might not yet understand how gatsby is doing the file loading during the build process?

**Comment by KyleAMathews** [comment]
It has to be a dependency as otherwise it won't be included when users install it. Or in other words, it's a dependency because Gatsby is a tool that others use so we ship tools with it.

**Comment by KyleAMathews** [comment]
If it we're a dev dependency, it wouldn't get installed.

**Comment by jorgegonzalez** [comment]
If you’re going to keep eslint can it at least be updated to the latest version then?

**Comment by mikelax** [comment]
thanks @KyleAMathews . one final question, I know there is the plugin [gatsby-plugin-eslint](https://next.gatsbyjs.org/packages/gatsby-plugin-eslint/), but I don't see the source in the `packages` folder. Is this because the plugin is "built-in" to gatsby package? 

I am trying to figure out the relationship of the eslint libs in `gatsby` package vs. this plugin usage. Thanks.

**Comment by pieh** [comment]
@mikelax this seems to be plugin created elsewhere - https://github.com/mongkuen/gatsby-plugin-eslint - not all gatsby plugins are in this repository

**Comment by jorgegonzalez** [comment]
Sure but my issue (and original reason for creating this issue) was that Gatsby includes `eslint@4.19.1` and I had an issue installing [`zoe`](https://github.com/jorgegonzalez/zoe), as the required `eslint` versions were conflicting.
