### ISSUE TITLE
I am not clear about how to submit my website to gatsby showcase.Below is  my package.json 

### ISSUE THREAD

**Issue by amit-deligence** [gatsbyjs/gatsby#8039]
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "bootstrap": "^4.0.0-beta.2",
    "dropzone": "^5.5.1",
    "font-awesome": "^4.7.0",
    "gatsby": "^1.9.277",
    "gatsby-image": "^1.0.55",
    "gatsby-link": "^1.6.46",
    "gatsby-paginate": "^1.0.16",
    "gatsby-plugin-nprogress": "^1.0.14",
    "gatsby-plugin-react-helmet": "^2.0.11",
    "gatsby-plugin-react-next": "^1.0.11",
    "gatsby-source-strapi": "0.0.3",
    "jquery": "^3.3.1",
    "ndx": "^0.4.1",
    "preact-cli": "^2.2.1",
    "react": "^16.4.2",
    "react-bootstrap-4": "^0.29.1",
    "react-bootstrap-carousel": "^3.2.0",
    "react-dom": "^16.4.2",
    "react-dropzone": "^5.0.1",
    "react-fontawesome": "^1.6.1",
    "react-helmet": "^5.2.0",
    "react-router-dom": "^4.3.1",
    "react-scripts": "1.1.4",
    "react-star-rating-component": "^1.4.1",
    "reactstrap": "^6.4.0",
    "regenerator-runtime": "^0.12.1",
    "serve": "^10.0.0",
    "strapi-sdk-javascript": "^0.2.1",
    "sweetalert-react": "^0.4.11"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write 'src/**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1",
    "heroku-postbuild": "gatsby build",
    "start": "serve public/"
  },
  "devDependencies": {
    "bootstrap-scss": "^4.1.3",
    "gatsby-plugin-sass": "^1.0.26",
    "prettier": "^1.13.7",
    "babel-core": "^6.0.20",
    "babel-polyfill": "^6.0.16",
    "babel-preset-es2015": "^6.0.15",
    "babel-preset-stage-0": "^6.0.15"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  }
}

**Comment by kakadiadarpan** [comment]
Please go through this link and follow the steps given there to submit your website for [showcase submission](https://next.gatsbyjs.org/docs/site-showcase-submissions/)
