### ISSUE TITLE
[v2] Reach router doesn't do element type checks compatible with react hot loader

### ISSUE THREAD

**Issue by jquense** [gatsbyjs/gatsby#8047]
There are a few places where reach/router checks for element types e.g. https://github.com/reach/router/blob/master/src/index.js#L476 This is broken when using RHL which wraps all elements. They need to do this: https://github.com/gaearon/react-hot-loader#checking-element-types at the moment using `<Redirect>` is broken in dev completely it seems

**Comment by jquense** [comment]
I think this is relevant to gatby as it enables RHL and while there are some workarounds it doesn't feel very polished for the router to API to basically not work, even if it is a dependency. A user isn't going to care who's library it is when upgrading.

**Comment by pieh** [comment]
@ryanflorence Any thoughts on this?

**Comment by tpolovyi** [comment]
[This](https://github.com/gaearon/react-hot-loader/tree/master/examples/hotCold) example may be useful as a temporary solution with no need to make the workaround mentioned above.

**Comment by HriBB** [comment]
Just updated to v2. Congrats to all devs :)

I'm having issues with hot reload as well. I'm using `material-ui@3.1.0`. If I wrap my root with a Layout component, hot reload doesn't work for styles. It works for components though, so I suspect I'm doing something wrong.

**Comment by jedrichards** [comment]
Sounds like nothing is going to happen with https://github.com/reach/router/issues/153, so isn't the ideal solution here to update Gatsby's webpack config to exclude node_modules from HRM as in https://github.com/gaearon/react-hot-loader/blob/master/examples/hotCold/webpack.config.babel.js#L20? Does this have any drawbacks?

**Comment by alexlafroscia** [comment]
Definitely not stale -- I ran into this exact issue right now. You currently cannot define a client-side `Redirect` through `@reach/router` because the proxy around the element breaks the `element.type` check that `@reach/router` does.

**Comment by aaw5017** [comment]
Still seeing this behavior with **@reach/router 1.3.1** and **gatsby 2.19.17**. Client-only routing where I'm trying to place a `<Redirect />` component directly inside a `<Router />` component.
