### ISSUE TITLE
[v2] Reach router doesn't handle null or falsy children in a Router

### ISSUE THREAD

**Issue by jquense** [gatsbyjs/gatsby#8048]
```js
<Router>
  <OtherRoute />
  {someConditionThatsFalsyOrNull && <MyRoute />
</Router>
```

Conditionally adding routes doesn't work

**Comment by DSchau** [comment]
Not sure this _belongs_ here, but I get that it's probably a regression from v1 behavior with react-router.

For now, how about we close this and follow along at reach/router#115?

(If you disagree, feel free to re-open 😄 and we can look further)

**Comment by jquense** [comment]
Ya i'm putting them here so ya'll are aware of the big/breaking bugs a v2 user will face. And maybe so @KyleAMathews can pester Ryan to fix it ;)
