### ISSUE TITLE
[V2] compiling css variables to be ie11 compatible

### ISSUE THREAD

**Issue by Lakston** [gatsbyjs/gatsby#8052]
V2 version : @next 

I'm trying to find a way to compile css variables (in .css files not in js) to plain css values so that our website is ie11 ready.

### Environment (if relevant)

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.2 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-rc.15
    gatsby-plugin-postcss: ^1.0.0 => 1.0.0
    gatsby-plugin-react-helmet: next => 3.0.0-rc.1
    gatsby-plugin-robots-txt: ^1.3.0 => 1.3.0
    gatsby-plugin-sitemap: ^1.2.25 => 1.2.25
  npmGlobalPackages:
    gatsby-cli: 1.1.58

### File contents (if changed)

`gatsby-config.js`: 
```
const cssvariables = require('postcss-css-variables')

module.exports = {
  plugins: [
    {
      resolve: `gatsby-plugin-postcss`,
      options: {
        postCssPlugins: [cssvariables()],
      },
    },
  ],
}
```

I've tried importing my css files in my `layout.jsx` file and also tried importing them as regular css `@import` in a master css files, I always end up with a compiled css with `undefied` values instead of a compiled version of the variable.

How can I compile the css variables to plain css values with the V2 ?

Thanks for your help

**Comment by kakadiadarpan** [comment]
Hi @Lakston, can you provide a reproduction repo where we can reproduce this? That would make it much easier to diagnose this issue.

**Comment by Lakston** [comment]
I fixed my issue so I'll post a solution here in case someone faces the same problem:

I remove the options for `gatsby-plugin-postcss` in `gatsby-config.js` and just declare the plugin there:
```
module.exports = {
  plugins: [
    'gatsby-plugin-postcss',
     ... your other plugins,
  ],
}
```

and created a `postcss.config.js` file at the root of my project where I handle the css processing:
```
const cssvariables = require('postcss-css-variables')
const atimport = require('postcss-import')

module.exports = () => ({
  plugins: [atimport(), cssvariables()],
})
```

Last step is to just `@import './variables.css';` the variables file in every css files that uses the variables

This results in a single css file where the variables are swapped for their values.

I'm not sure if this is the easiest way to do this or the best practice but it works for now, hope that helps :)

**Comment by kakadiadarpan** [comment]
@Lakston I think this would be the best way to handle it is the simplest way of handling it. Also, it is mentioned in the documentation of [gatsby-plugin-postcss](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-postcss) that the configuration can be done in using `postcss.config.js`as well.
