### ISSUE TITLE
code line highlighting buggy

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#8058]
https://twitter.com/rchrdnsh/status/1039529095372009472

**Comment by fk** [comment]
Sigh…
![image](https://user-images.githubusercontent.com/21834/45372950-7388f700-b5ee-11e8-97d0-b852f6e73081.png)

**Comment by fk** [comment]
Before actually looking closer at _anything_, I decided to throw the failing code block/highlighted lines in `examples/using-remark`…and it looks like this was working fine until `gatsby-remark-prismjs@3.0.0-beta.6`:

![image](https://user-images.githubusercontent.com/21834/45391215-6dad0900-b622-11e8-8714-157c6ed7961f.png)

Using `beta.7` (https://github.com/gatsbyjs/gatsby/pull/7342):

![image](https://user-images.githubusercontent.com/21834/45391205-638b0a80-b622-11e8-934b-d20f112078e2.png)

**Comment by DSchau** [comment]
@fk nice work debugging this! I can take a look at this tomorrow morning or maybe tomororw afternoon unless anyone else grabs it.

**Comment by fk** [comment]
@DSchau Oh I'd love that! Left another comment over at https://github.com/gatsbyjs/gatsby/pull/7342#issuecomment-420477709 a few minutes ago.

**Comment by fk** [comment]
Yay! 🎉 Let's unpin `gatsby-remark-prismjs` for `www` https://github.com/gatsbyjs/gatsby/blob/aa9bc1b353c2f83dad7d39d07f5a7c1b8ac092a0/www/package.json#L39
