### ISSUE TITLE
[Question] Pass state as props from main index.js layout to /templates/*.js

### ISSUE THREAD

**Issue by h0rhay** [gatsbyjs/gatsby#8059]
## Summary
Referencing this [issue](https://github.com/gatsbyjs/gatsby/issues/2112)..

I wondered if anyone could elaborate on [Kyles](@KyleAMathews ) solution.

---
You could pass a prop to the pages that you could call from them e.g.
```jsx
render () {
  return <div>
    { this.props.children({...this.props, updateLayoutFunction }) }
  </div>
}
```
You'd then update the layout state and re-render. ???

---

I have a main index file which is pumping blog posts into here
`{children()}`
in the main render function.

In the `blog-post.js` file I need to be able to access state passed as props to it from the parent index.js..

**Comment by kakadiadarpan** [comment]
Hi @h0rhay, like suggested in this [comment](https://github.com/gatsbyjs/gatsby/issues/2112#issuecomment-338591323), did you try to pass it using `key`?

**Comment by DavidTheSimon** [comment]
Does anyone have a solution yet?
