### ISSUE TITLE
gatsby-transformer-json: Inconsistent return of values

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#8062]
## Description

I'm seeing null values returned from queries using  gatsby-transformer-json's API, arbitrarily and unpredictably.

### Steps to reproduce

[Repo in next comment]

I have a `settings` directory of files that I have made Gatsby aware of using `gatsby-source-filesystem`. The directory contains several `.json` files. They are all valid JSON and utf-8 encoded.

The files look like this:

### src/settings/contact.json`
```json
{
  "contactDetails": {
    "email": "-------",
    "telephone": "------",
  }
}
```
### src/settings/envs.json
```json
{ "branch": "development" }
```
### src/settings/media.json
```json
{
  "images": {
    "maxWidth": 1200,
    "quality": 60
  }
}
```

All of the fields are available in the graphQL viewer at `http://localhost:8000/___graphql`, and autocomplete. However If I run the query, only one of the three files will return a value. The other two will return `null`. The file from which data _is_ returned varies between builds. Sometimes valid data will be returned from `contacts.json`, sometimes form `media.json` and sometimes from `envs.json`, however only ever from one file. The values from the other two will always be `null`.

```graphql
{
  settingsJson {
    contactDetails {
      email
      telephone
    }
   branch
   images {
     maxWidth
     quality
   }
  }
}
```

If I try an `allSettingsJson` query instead:

```graphql
{
  allSettingsJson {
    edges {
      node {
        id
        branch
        images {
          maxWidth
          quality
        }
        contactDetails {
          email
          telephone
        }
      }
    }
  }
}
```

I get the following result:

```graphql
{
  "data": {
    "allSettingsJson": {
      "edges": [
        {
          "node": {
            "id": "02e484e9-75d7-5130-9759-ce7882a281f7",
            "branch": "development",
            "images": null,
            "contactDetails": null
          }
        },
        {
          "node": {
            "id": "2b07bf9c-7d8f-5794-84c5-7ee1e3b9b189",
            "branch": null,
            "images": null,
            "contactDetails": {
              "email": "info@sleepstation.org.uk",
              "telephone": "0333 800 9404"
            }
          }
        },
        {
          "node": {
            "id": "d9b296d6-97cb-51de-8d3c-d6b09adcc5a3",
            "branch": null,
            "images": {
              "maxWidth": 1200,
              "quality": 60
            },
            "contactDetails": null
          }
        }
      ]
    }
  }
}
```

So the data is definitely there. It just isn't returned consistently from the `settingsJson` query.

### Expected result

The query should return the data from all of the files.

### Environment

```
  Browsers:
    Chrome: 68.0.3440.106
    Safari: 11.1.2
  npmPackages:
    gatsby: 2.0.0-rc.5 => 2.0.0-rc.5
    gatsby-cli: 2.0.0-rc.1 => 2.0.0-rc.1
    gatsby-image: ^2.0.0-rc.1 => 2.0.0-rc.1
    gatsby-plugin-catch-links: ^2.0.2-rc.1 => 2.0.2-rc.1
    gatsby-plugin-favicon: ^3.1.2 => 3.1.4
    gatsby-plugin-manifest: 2.0.2-rc.1 => 2.0.2-rc.1
    gatsby-plugin-netlify-cms: 3.0.0-rc.1 => 3.0.0-rc.1
    gatsby-plugin-node-fields: ^1.0.0 => 1.0.0
    gatsby-plugin-offline: 2.0.0-rc.1 => 2.0.0-rc.1
    gatsby-plugin-page-creator: ^2.0.0-rc.1 => 2.0.0-rc.1
    gatsby-plugin-react-helmet: 3.0.0-rc.1 => 3.0.0-rc.1
    gatsby-plugin-remove-trailing-slashes: ^2.0.0-rc.1 => 2.0.0-rc.1
    gatsby-plugin-sharp: ^2.0.0-rc.2 => 2.0.0-rc.3
    gatsby-plugin-styled-components: 3.0.0-rc.1 => 3.0.0-rc.1
    gatsby-remark-copy-linked-files: ^2.0.0-rc.1 => 2.0.0-rc.1
    gatsby-remark-embed-video: ^1.4.0 => 1.4.0
    gatsby-remark-images: ^2.0.1-rc.1 => 2.0.1-rc.1
    gatsby-remark-responsive-iframe: ^2.0.0-rc.1 => 2.0.0-rc.1
    gatsby-remark-smartypants: ^2.0.0-rc.1 => 2.0.0-rc.1
    gatsby-source-filesystem: ^2.0.1-rc.1 => 2.0.1-rc.1
    gatsby-transformer-json: ^2.1.1-rc.6 => 2.1.1-rc.6
    gatsby-transformer-remark: ^2.1.1-rc.1 => 2.1.1-rc.1
    gatsby-transformer-sharp: ^2.1.1-rc.2 => 2.1.1-rc.2
  npmGlobalPackages:
    gatsby-cli: 2.0.0-beta.13
```

**Comment by Undistraction** [comment]
@kakadiadarpan There is a repo [here](https://github.com/Undistraction/gatsby-transformer-json-bug) that clearly shows the problem. It's based on the default starter with very minimal changes. 

I just added:

```javascript
 {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `src`,
        path: `./src/content/settings`,
      },
    },
    `gatsby-transformer-json`,
```

And some json files. 

Full instructions for install and a link to the live graphql query that shows the problem are included in the README. Let me know if you need anything else.

**Comment by Undistraction** [comment]
I'm up for taking a run at this, but I need to know that what I think is the correct behaviour is the correct behaviour. @KyleAMathews or @pieh please can you confirm that this transformer _should_ work with multiple JSON files where each has multiple keys.

**Comment by pieh** [comment]
I don't think I understand here - `settingsJson` should return values from single node so it should be
```
            "id": "02e484e9-75d7-5130-9759-ce7882a281f7",
            "branch": "development",
            "images": null,
            "contactDetails": null
```
if this is what you are getting then that's correct behaviour

**Comment by Undistraction** [comment]
@pieh So assuming I have multiple JSON files, there is no way to query more than one of those files in a single query?

So assuming I have three files:

src/settings/contact.json
```
{
  "contactDetails": {
    "email": "-------",
    "telephone": "------",
  }
}
```

src/settings/envs.json
```
{ "branch": "development" }
```

src/settings/media.json
```
{
  "images": {
    "maxWidth": 1200,
    "quality": 60
  }
}
```

Are you saying there is no way for me to get `contactDetails`, `branches` _and_ `images` in a query? This makes it impossible to split configuration across multiple files.

**Comment by Undistraction** [comment]
The problem is that each file doesn't contain the same keys, so `allSettingsJson` doesn't make sense as it will return multiple nodes with an amalgamation of all keys. Multiple calls to `settingsJson` also fail:

```graphql
{
  settingsJson {
   	alpha1
  }
  settingsJson {
   	bravo1
  }
  settingsJson {
   	charlie1
  } 
}
```

Result:

```graphql
{
  "data": {
    "settingsJson": {
      "alpha1": "alpha1",
      "bravo1": null,
      "charlie1": null
    }
  }
}
```

So it appears there is no way to get the data from multiple nodes using their names in the same query.

**Comment by pieh** [comment]
how about something like:
```
{
  alpha:settingsJson(alpha1: {ne: null}) {
     alpha1
  }
  bravo:settingsJson(bravo1: {ne: null}) {
     bravo1
  }
  charlie:settingsJson(charlie1: {ne: null}) {
    charlie1
  } 
}
```

`settingsJson` will always return first node that matches filters (if you don't use any filters it will just return simply first node)

**Comment by pieh** [comment]
This is more about usefulness of `filesystem` plugin and `json` transformer in this use case. Transformer will create one (or more) nodes from every file, but you can't configure it to create one node from multiple files - I think that you would need to create some custom logic for things you want to do - so in `gatsby-node` read all json files and create single node from merged object

**Comment by Undistraction** [comment]
@pieh Thanks. I also just thought of another workaround. If each JSON file is located in its own directory, a different query is generated for each, e.g.
```
- settings
  - a
    - alpha.json
  - b
    - bravo.json
  - c
    - charlie.json
```
Then You can query all using:
```graphql
{
  aJson {
    alpha1
  }
  bJson {
    bravo2
  }
  cJson {
    charlie2
  }
   
}
```

Result
```graphql
{
  "data": {
    "alpJson": {
      "alpha1": "alpha1"
    },
    "braJson": {
      "bravo2": "bravo2"
    },
    "chaJson": {
      "charlie2": "charlie2"
    }
  }
}
```
