### ISSUE TITLE
WWW showcase page: after closing show detail modal, it will rerender list page, lose all "more load" data and scroll back to top

### ISSUE THREAD

**Issue by sivagao** [gatsbyjs/gatsby#8069]
## Description

https://next.gatsbyjs.org/showcase. browse this page, and load more showcases, and then click a card to view showcase detail as modal window. after closing the modal. the showcase list page is rerendering, losing all the before status.
I think this experience can be improved. 

### Steps to reproduce

1. Oen https://next.gatsbyjs.org/showcase
2. Select a `category`, for example `app`.
3. Click on any site card. The site modal opens up.
4. Close the modal by clicking on close button.
5. Check the selected categories and the site list.

### Expected result
Selected filter should be maintained.

### Actual result
Selcted filters are cleared, and the site is rendered as the initial page launch.

### Environment
N/A

**Comment by kakadiadarpan** [comment]
Hi @sivagao, would you like to work on this?

[This](https://github.com/gatsbyjs/gatsby/blob/master/www/src/views/showcase/index.js) should be the place you should be looking into for fixing this issue.

**Comment by sivagao** [comment]
> Hi @sivagao, would you like to work on this?
> 
> [This](https://github.com/gatsbyjs/gatsby/blob/master/www/src/views/showcase/index.js) should be the place you should be looking into for fixing this issue.

yes. I will investigate more if my similar project need fix this issue.  However i think this will modify the modal implementation probably

**Comment by andrew-anguiano** [comment]
@kakadiadarpan I can take a look at this if @sivagao hasn't had a change 🙂

**Comment by andrew-anguiano** [comment]
@kakadiadarpan do you have any more pointers on how to achieve this? I've poked around and haven't really found a good way to preserve the filters. I thought perhaps passing `modalBackgroundPath` with the filter params included would work, but I can't seem to figure out how to pass them down to the modal properly.
