### ISSUE TITLE
WARN deprecated gulp-util@3.0.8 gatsby-plugin-sharp@2.0.0-rc.7

### ISSUE THREAD

**Issue by sa3idatol** [gatsbyjs/gatsby#8071]
## Description

deprecated gulp-util@3.0.8

### Steps to reproduce

I get this issue after having installed  this starter https://github.com/Vagr9K/gatsby-material-starter

### Expected result

solution

### Actual result

nothing happened.I just report the issue as suggested in https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here. Not working? You may need to update your global gatsby-cli - `npm install -g gatsby-cli`

**Comment by kakadiadarpan** [comment]
Hi @sa3idatol, can you please provide more details on the issue you are facing? Also, please provide the environment information by running `gatsby info --clipboard`?

**Comment by tyocca** [comment]
I am running into the same issue so I figured I would add my `gatsby info` results.


```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.4 - /usr/local/bin/node
    npm: 6.2.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 61.0.1
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-rc.10 
    gatsby-plugin-manifest: ^2.0.2-rc.1 => 2.0.2-rc.1 
    gatsby-plugin-offline: next => 2.0.0-rc.2 
    gatsby-plugin-react-helmet: next => 3.0.0-rc.1 
    gatsby-plugin-sharp: ^1.6.48 => 1.6.48 
    gatsby-plugin-styled-components: ^3.0.0-rc.1 => 3.0.0-rc.1 
    gatsby-source-contentful: ^1.3.54 => 1.3.54 
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```

### [Suggested API Replacements](https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5)
- gutil.File => https://www.npmjs.com/package/vinyl
- gutil.replaceExtension => The .extname property on Vinyl objects or https://www.npmjs.com/package/replace-ext
- gutil.colors => https://www.npmjs.com/package/ansi-colors
- gutil.date => https://www.npmjs.com/package/date-format
- gutil.log => https://www.npmjs.com/package/fancy-log
- gutil.template => https://www.npmjs.com/package/lodash.template
- gutil.env => https://www.npmjs.com/package/minimist
- gutil.beep => https://www.npmjs.com/package/beeper
- gutil.noop => https://www.npmjs.com/package/through2
- gutil.isStream => Use the .isStream() method on Vinyl objects
- gutil.isBuffer => Use the .isBuffer() method on Vinyl objects
- gutil.isNull => Use the .isNull() method on Vinyl objects
- gutil.linefeed => Use the string '\n' in your code
- gutil.combine => https://www.npmjs.com/package/multipipe
- gutil.buffer => https://www.npmjs.com/package/list-stream
- gutil.PluginError => https://www.npmjs.com/package/plugin-error

### Steps to reproduce
**Run** `npm install gatsby-plugin-sharp `
**Error message** 
```
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5 npm install gatsby-plugin-sharp

npm WARN gatsby-plugin-sharp@1.6.48 requires a peer of gatsby@^1.0.0 but none is installed. You must install peer dependencies yourself.
```

Thank you

**Comment by zauni** [comment]
Unfortunately this is a subdependency of imagemin-pngquant, even in the latest version.

This is the `npm ls gulp-util` output:

```
gatsby-plugin-sharp@2.0.0-rc.7
  └─┬ imagemin-pngquant@6.0.0
    └─┬ pngquant-bin@5.0.0
      └─┬ bin-wrapper@3.0.2
        └─┬ download@4.4.3
          └─┬ gulp-decompress@1.2.0
            └── gulp-util@3.0.8
```

So we have to wait until gulp-decompress is not using gulp-util anymore.

**Comment by mrhut10** [comment]
i'm having this same issue might be why my build brakes as soon as i'm including sharp plugin in config. :(

**Comment by DSchau** [comment]
@mrhut10 as best as I can tell, this shouldn't be breaking builds. It's a warning, not an error.

**Comment by mrhut10** [comment]
mmm only brakes after i add sharp to config


package.json lists them as
"gatsby-plugin-sharp": "^2.0.11",
"gatsby-transformer-sharp": "^2.1.7",

gatsby-config.js   has then included as
'gatsby-transformer-sharp',
'gatsby-plugin-sharp',

when run "gatsby develop"
.....
error Plugin gatsby-transformer-sharp returned an error
  Error: The specified procedure could not be found.
  \\?\C:\Users\drhut10\Documents\_projects\futuresFineFuniture\node_modules\gatsby-plugin-sharp\node_modules\sharp\build\Release\sharp.node

...
