### ISSUE TITLE
[gatsby-tranformer-remark] Extend node test is working properly

### ISSUE THREAD

**Issue by oorestisime** [gatsbyjs/gatsby#8074]
## Description

In the extend node tests https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/src/__tests__/extend-node.js#L88 `result.data.listNode.excerpt` is undefined since listNode is in fact a list. To the very least we should use `listNode[0].excerpt`.

But the issue is deeper than this. The test seems to pass without running the assertion and the excerpt even if it is a string it is an empty one

### Steps to reproduce

Log the excerpt value in the test

### Expected result

The test should test to have an actual excerpt value and the current test should fail

### Actual result

Test passes silently

**Comment by kakadiadarpan** [comment]
Hey @oorestisime! Thank you for opening a PR to fix this issue.
