### ISSUE TITLE
[v2 rc]Typography not injected into head correctly when serving production build

### ISSUE THREAD

**Issue by koreyboone** [gatsbyjs/gatsby#8079]
## Description

When serving gatsby from static build, typography gets injected into the head as 
`<style id="typography.js">[object Object]</style>`
but when using gatsby develop, the css is injected properly within the style tag.

### Steps to reproduce

Create typography.js file containing:
```
import Typography from 'typography'
const typography = new Typography({
  baseFontSize: '18px',
  baseLineHeight: 1.666,
  headerFontFamily: [
    'SFProText-Regular',
    'Avenir Next',
    'Helvetica Neue',
    'Segoe UI',
    'Helvetica',
    'Arial',
    'sans-serif',
  ],
  bodyFontFamily: ['SFProText-Regular',
  'Avenir Next',
  'Helvetica Neue',
  'Segoe UI',
  'Helvetica',
  'Arial',
  'sans-serif',],
  // See below for the full list of options.
})

export default typography
```

Follow remaining set-up instructions for typography.js and gatsby-plugin-typography.
Run gatsby build && gatsby serve

### Expected result

typography is injected properly into the head when serving static site

### Actual result

`<style id="typography.js">[object Object]</style>` appears in the head and typography is not applied

### Environment

System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.3.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-rc.19
    gatsby-plugin-manifest: next => 2.0.2-rc.1
    gatsby-plugin-offline: next => 2.0.0-rc.6
    gatsby-plugin-react-helmet: next => 3.0.0-rc.1
    gatsby-plugin-typography: next => 2.2.0-rc.3
  npmGlobalPackages:
    gatsby-cli: 1.1.58

**Comment by kakadiadarpan** [comment]
@koreyboone, can you please provide a reproduction repo for this? That would make it much simpler to diagnose this issue.

**Comment by koreyboone** [comment]
> @koreyboone, can you please provide a reproduction repo for this? That would make it much simpler to diagnose this issue.

No I cannot. It is a company project and the source code is not public. I can provide whatever snippets are needed though. I'll try creating a brand new project with the same versions and see if this is happening.

**Comment by koreyboone** [comment]
I figured it out. Seems to be a bug with typography@1.0.0-alpha.4, when I go back to typography@0.16.17 It works fine. Is this still considered a bug?

**Comment by kakadiadarpan** [comment]
@koreyboone Yes, that would still be considered as a bug. Would you like to submit a minimal reproduction repo for this issue? It may just have `gatsby` and `gatsby-plugin-typography`
