### ISSUE TITLE
[v2] `gatsby serve`bugs

### ISSUE THREAD

**Issue by jquense** [gatsbyjs/gatsby#8080]
Running the latest v2 rc:

- ~~`ctrl +c` doesn't exit the server~~ this seems to be just me
- client paths aren't handled and result in a 404, might need the history fallback middleware
- keeps trying to send a non-existent 404 page on any client route'

maaaybe more, still checking

**Comment by kakadiadarpan** [comment]
Hi @jquense, can you please provide more information on this? Also, I'm able to successfully exit the server using `ctrl + c`.

**Comment by jquense** [comment]
@kakadiadarpan you're right it seems like something is funky in my env that it's not exiting. The other two issues are still relevant tho. I can hopefully throw a fix together for it

**Comment by jquense** [comment]
Still relevant I believe

**Comment by DSchau** [comment]
```
Successfully published:
 - gatsby@2.0.116
```
