### ISSUE TITLE
Transformed nodes don't update when queried by ID

### ISSUE THREAD

**Issue by avigoldman** [gatsbyjs/gatsby#8086]
## Description

When querying for transformed nodes by ID, the content initially loads correctly but doesn't receive any updates made to the file, even after refreshing the page. If the node is queried for by any other field, it works correctly.

This was originally reported in https://github.com/ChristopherBiscardi/gatsby-mdx/issues/89

### Steps to reproduce

1. Clone https://github.com/ChristopherBiscardi/gatsby-mdx
1. Run `yarn`
1. Run `yarn workspace gatsby-mdx-docs develop` to start the Gatsby dev server for the `examples/docs` package.
1. Visit `http://localhost:8000/docs/api-reference`.
1. Change some content in `examples/docs/content/docs/api-reference.mdx` and save the file.

### Expected result

The node's content should update with changes to the transformed file.

### Actual result

The content doesn't change until the dev process is restarted.

### Environment

```
  System:
    OS: macOS High Sierra 10.13.3
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.0.0 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 46.0.1
    Safari: 11.0.3
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```

**Comment by Yomguithereal** [comment]
This one just bit me very hard :).

**Comment by vladar** [comment]
@avigoldman Do you experience this issue on the latest version of Gatsby? I suspect it was addressed already. At least the referenced issue https://github.com/ChristopherBiscardi/gatsby-mdx/issues/89 is closed a while ago.
