### ISSUE TITLE
starter showcase - change the index page URL from /starter-showcase/ to /starters/

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#8087]

**Comment by fk** [comment]
Thanks for opening this, Shannon! 🙏 

FWIW here's my reasoning from an internal discussion:

>Currently individual starter pages are at e.g. https://next.gatsbyjs.org/starters/gatsby-starter-bootstrap
>while the index of the starter showcase is at https://next.gatsbyjs.org/starter-showcase/ …
>
>My gut (and probably OCD) has been telling me to suggest changing the latter URL to https://next.gatsbyjs.org/starters/ for some time now, which I hereby give in to 😺 … arguments pro:
>
>- keep important base URLs easy to type out
>- makes me stop asking "But why isn't it https://next.gatsbyjs.org/site-showcase/ then?" 😉 
>- match detail page URL structure

and one more from Shannon:

>And it keeps the confusion down. Having the word "showcase" all over the place is a bit confusing
