### ISSUE TITLE
Titles aren't rendered when opening pages in the background using plugin-offline

### ISSUE THREAD

**Issue by antonmedv** [gatsbyjs/gatsby#8089]
## Description

No title if Gatsby app is opened in the background.

### Steps to reproduce

1. Install next Gatsby
2. `gatsby new title` && `cd title`
3. `gatsby develop`
4. Open link in the background
5. Check for the title in the tab

### Expected result

title is set.

### Actual result

no title

### Environment

<details>
  <summary>gatsby info --clipboard</summary>
  
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 4.4.19 - /usr/local/bin/bash
  Binaries:
    Node: 10.8.0 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.92
    Firefox: 59.0.1
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-rc.15 
    gatsby-plugin-feed: next => 2.0.0-rc.2 
    gatsby-plugin-google-analytics: next => 2.0.0-rc.2 
    gatsby-plugin-google-fonts: 0.0.4 => 0.0.4 
    gatsby-plugin-manifest: next => 2.0.2-rc.1 
    gatsby-plugin-offline: next => 2.0.0-rc.6 
    gatsby-plugin-react-helmet: next => 3.0.0-rc.1 
    gatsby-plugin-sass: next => 2.0.0-rc.2 
    gatsby-plugin-sharp: next => 2.0.0-rc.3 
    gatsby-remark-copy-linked-files: next => 2.0.0-rc.1 
    gatsby-remark-images: next => 2.0.1-rc.1 
    gatsby-remark-prismjs: next => 3.0.0-rc.2 
    gatsby-remark-responsive-iframe: next => 2.0.0-rc.1 
    gatsby-remark-smartypants: next => 2.0.0-rc.1 
    gatsby-source-filesystem: next => 2.0.1-rc.2 
    gatsby-source-github-api: 0.0.3 => 0.0.3 
    gatsby-transformer-remark: next => 2.1.1-rc.1 
    gatsby-transformer-sharp: next => 2.1.1-rc.3 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

</details>

**Comment by kakadiadarpan** [comment]
Hi @antonmedv, this happens only in `develop` mode, not for the production build. Correct?

**Comment by antonmedv** [comment]
Here is my production: https://medv.io
Same results.

**Comment by antonmedv** [comment]
Code https://github.com/antonmedv/medv.io

**Comment by kakadiadarpan** [comment]
@antonmedv I don't see the issue here

![8089](https://user-images.githubusercontent.com/10805593/45607635-62673c80-ba6b-11e8-9163-a484cc629dec.gif)

**Comment by antonmedv** [comment]
Open another link in background from my site.

**Comment by kakadiadarpan** [comment]
Opened multiple links in the background, cannot reproduce. Am I missing something?

![8091](https://user-images.githubusercontent.com/10805593/45612957-48852400-ba82-11e8-98f8-1366b70a210d.gif)

**Comment by fk** [comment]
@antonmedv @kakadiadarpan 

![image](https://user-images.githubusercontent.com/21834/45617484-cd684180-ba72-11e8-8b09-de42a36408fc.png)

Seems there's no `<title>` set until the browser tab becomes active:

![image](https://user-images.githubusercontent.com/21834/45617543-f2f54b00-ba72-11e8-8611-73c6c66b5ef8.png)

The same happens on e.g. next.gatsbyjs.org/blog:

![image](https://user-images.githubusercontent.com/21834/45617627-318b0580-ba73-11e8-8893-ac75c65cdef0.png)

gatsbyjs.org behaves fine though:

![image](https://user-images.githubusercontent.com/21834/45617642-3c459a80-ba73-11e8-8854-ec2f2da0fc99.png)

OT: Love your site @antonmedv!

**Comment by pieh** [comment]
It seems like service worker takes over there and using appshell (empty page) until tab is foces and react update DOM - if you unregister service worker, and then open link in background, Title shows up as expected.

/cc @davidbailey00

**Comment by davidbailey00** [comment]
There's a chance this is an upstream bug with React Helmet, since I've found that all other content is rendered while in the background. Just investigating this now

**Comment by davidbailey00** [comment]
I've checked this out and it definitely seems like an upstream bug with React Helmet - it might be hard to work around since we can't use `Helmet.renderStatic()` in the browser, so we'll probably have to wait until it gets fixed upstream / submit our own PR to Helmet (although unfortunately it seems abandoned). See https://github.com/nfl/react-helmet/issues/401

**Comment by deebov** [comment]
> @fk I wonder why that is not happening for me 😕

go to the site and open an another link in the new tab. 
the same issue with me. but i use create-react-app.

**Comment by antonmedv** [comment]
@gatsbybot not fixed

**Comment by davidbailey00** [comment]
As per nfl/react-helmet#314, as a workaround, you can use the prop `defer={false}` in your `<Helmet>` component to set/update the title as soon as possible. (Thanks @beaugunderson for pointing me to the right place!)

**Comment by davidbailey00** [comment]
Going to keep this open because it's not really well documented at the moment (or maybe we could apply the given workaround automatically)

**Comment by hkr86** [comment]
This is not fixing the issue for me. If I run gatsby build all the index.html files have an empty title tag (<title></title>). On client side it gets rendered. Looks like ssr is not working. Any solutions?

**Comment by hkr86** [comment]
#13737 pointed me into the right direction!

**Comment by albertofortes** [comment]
Still happening to me
