### ISSUE TITLE
Showcase Gatsby starters the same way as Gatsby showcase site

### ISSUE THREAD

**Issue by Mokkapps** [gatsbyjs/gatsby#8090]
## Summary

I often use the [Gatsby starter page](https://next.gatsbyjs.org/docs/gatsby-starters/) to search for new and interesting starter projects.

Unfortunately, it is a pain to search for projects. I would love to see a similar view like in the [showcase site](https://next.gatsbyjs.org/showcase/) where I see a preview and can filter by category.

### Motivation
I hope this will help many people to faster find their starter project

**Comment by pieh** [comment]
It's being actively worked on - it's just not quite ready yet (automatisation needed to grab all the data is not quite working yet) but you can check preview - https://next.gatsbyjs.org/starter-showcase ;)
