### ISSUE TITLE
Can I use gatsby-remark-responsive-iframe in gatsby-node.js?

### ISSUE THREAD

**Issue by agarrharr** [gatsbyjs/gatsby#8091]
I'm getting some markdown data from Contentful, and then transforming some of it with remarkable in `gatsby-node.js`:

```js
const Remarkable = require('remarkable');
const markdown = new Remarkable({ html: true });
```

```js
createNodeField({
  node,
  name: 'descriptionFormatted',
  value: markdown.render(description.internal.content),
});
```

Sometimes the `description` contains an iframe, such as an embedded YouTube video. I would like to make this responsive automatically. Can I use `gatsby-remark-responsive-iframe` to do this?

**Comment by KyleAMathews** [comment]
Yup! Remark plugins will work on markdown from any source including contentful so not just files.
