### ISSUE TITLE
Crash when createPage context contains Symbol

### ISSUE THREAD

**Issue by stefanprobst** [gatsbyjs/gatsby#8093]
## Description

Gatsby crashes when `context` in `createPage` contains a `Symbol` (e.g. when trying to pass a React element via `context`).
This happens [when `inferGraphQLType` calls `DateType.shouldInfer`](https://github.com/gatsbyjs/gatsby/blob/ef33c88d949c9829bd93e7900bcda590b45a529c/packages/gatsby/src/schema/infer-graphql-type.js#L96). The actual crash is because momentjs tries to concatenate string and Symbol.
While it would be simple enough to add a check here, a follow-up problem then is that [this switch hits the default: null](https://github.com/gatsbyjs/gatsby/blob/ef33c88d949c9829bd93e7900bcda590b45a529c/packages/gatsby/src/schema/infer-graphql-type.js#L124) case and AFAIU therefore the prop is omitted from inferred fields, and thus also missing from `pageContext`.

### Steps to reproduce

See https://github.com/stefanprobst/gatsby-graphql-symbol

### Expected result

No crash, Symbol passed to `pageContext`

### Actual result

Unhandled rejection

**Comment by pieh** [comment]
Hmm, it's not great that it crashes - but even if it didn't crash - context gets serialized and saved to .json file so I'm not sure if you actually would be able to use that in your component even if it didn't crash

**Comment by pieh** [comment]
Also just to be clear here - it crashes during graphql schema construction - so crash definitely need to be fixed. But `pageContext` prop that is available in page componets is separate issue (graphql schema construction stuff isn't involved there) related to serializing pageContext objects and saving it to json file - I don't think you can serialize and deserialize Symbols?
