### ISSUE TITLE
Hot Reloading not working on Hello World starter

### ISSUE THREAD

**Issue by eallencreighton** [gatsbyjs/gatsby#8096]
## Description

Hot Reloading not working on Hello World starter

### Steps to reproduce
Command line:
gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world#v2
cd hello-world
gatsby develop

Change content in src/pages/index.js

### Expected result

Content change appears in browser

### Actual result

Change does not appear, must manually refresh the page to see changes.

### Environment
  System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 41.16299.371.0
  npmPackages:
    gatsby: next => 2.0.0-rc.21

error The system cannot find the path specified.

  Error: The system cannot find the path specified.

  - envinfo.js:1 Function.e.exports.sync
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:7778

  - envinfo.js:1 Object.copySync
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:104976

  - envinfo.js:1 Object.t.writeSync.e [as writeSync]
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:123499

  - envinfo.js:1
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:124274

  - envinfo.js:1 Promise.all.then.e
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:124289

  - util.js:16 tryCatcher
    [npm]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

  - promise.js:638 Promise._fulfill
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

error UNHANDLED REJECTION

  Error: The system cannot find the path specified.

  - envinfo.js:1 Function.e.exports.sync
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:7778

  - envinfo.js:1 Object.copySync
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:104976

  - envinfo.js:1 Object.t.writeSync.e [as writeSync]
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:123499

  - envinfo.js:1
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:124274

  - envinfo.js:1 Promise.all.then.e
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:124289

  - util.js:16 tryCatcher
    [npm]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

  - promise.js:638 Promise._fulfill
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

**Comment by elebumm** [comment]
Is this not working in just the hello-world starter?

**Comment by eallencreighton** [comment]
That's all I've tired so far.  Started with the older version tutorial, then switched after comments here said it was fixed in v2.

**Comment by kakadiadarpan** [comment]
I'm not able to reproduce this issue in Mac OS. Is this issue specific to windows?

@eallencreighton would it be possible for you to check this on any other OS? Unfortunately, I don't have any other OS with me.

**Comment by eallencreighton** [comment]
That's right.  I just tried it on my Mac at home--no problem!  But it's not working on my Windows 10 machine at work.

**Comment by miguelmota** [comment]
hot reloading is not working for me either

**Comment by AGreenObject** [comment]
I'm having trouble with hot reloading as well.

**Comment by ibjorn** [comment]
Even I.

**Comment by sinkingrowboats** [comment]
Having Same issue on Windows 10

**Comment by borisyordanov** [comment]
Hot reloading not working on Windows 10 for me either

**Comment by Yaygr** [comment]
Hot Reloading also fails for me on Windows 10 with the Hello World starter.

> System:
>     OS: Linux 4.4 Debian GNU/Linux 10 (buster) 10 (buster)
>     CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
>     Shell: 5.0.3 - /bin/bash
>   Binaries:
>     Node: 12.10.0 - /home/linuxbrew/.linuxbrew/bin/node
>     npm: 6.11.3 - /home/linuxbrew/.linuxbrew/bin/npm
>   npmGlobalPackages:
>     gatsby-cli: 2.7.47

**Comment by kattow88** [comment]
Hot reloading not working for me either.
Windows 10
Node v. 10.16
npm v. 6.9
gatsby-cli v. 2.7.53
gatsby v. 2.13.50

**Comment by BALAJIRAO676** [comment]
Please refer https://github.com/gatsbyjs/gatsby/issues/13918

The discussion is around it only . Hope you find it useful and figure out.
