### ISSUE TITLE
Getting error on Gatsby Build

### ISSUE THREAD

**Issue by emman24** [gatsbyjs/gatsby#8114]
I'm having issue on gatsby build it throws Module not found ...

![screenshot from 2018-09-13 17-07-07](https://user-images.githubusercontent.com/25625894/45478878-8b3fb700-b777-11e8-852d-4b97cfa5b2f4.png)

but when I run gatsby develop its working smooth. 

I Tried the debugging it as what on the docs  https://www.gatsbyjs.org/docs/debugging-html-builds/

but no luck at all ...

**Comment by kakadiadarpan** [comment]
Hi @emman24, from the screenshot the only thing I can infer is that a module is missing: [`tween`](https://www.npmjs.com/package/tween). Please try installing that and check if that works.

If it doesn't work please provide a reproduction repo and relevant environment info by running `gatsby info --clipboard`.

**Comment by emman24** [comment]
@kakadiadarpan Thanks this code helps me :+1: 


`exports.modifyWebpackConfig = ({ config, stage }) => {
  if (stage === 'build-html') {
    config.loader('null', {
      test: /scroll-to/,
      loader: 'null-loader',
    });
  }
};`

**Comment by pieh** [comment]
@kakadiadarpan this follow this guide https://next.gatsbyjs.org/docs/debugging-html-builds/ - using `null-loader` for `build-html` makes that package is not actually loaded during static html generation (which prevent any crashes caused by using browser APIs in Node.js context)

**Comment by kakadiadarpan** [comment]
Thanks, @pieh!
