### ISSUE TITLE
Plan for PageRenderer

### ISSUE THREAD

**Issue by Kadrian** [gatsbyjs/gatsby#8115]
I'm building something similar to the Gatsbygram example, using a modal with a URL that renders the page below.

I'm wondering: Will `PageRenderer` be the way to go in the future? How to use it then? I couldn't find any documentation for it in the v2 API reference.

**Comment by pieh** [comment]
Would you be interested in creating docs for it? This is component publicly exported from `gatsby` package - so at least for v2, it's ok to use it.
