### ISSUE TITLE
[gatsby-source-wordpress] localFile field null on images in ACF fields on netlify deploy

### ISSUE THREAD

**Issue by garethgd** [gatsbyjs/gatsby#8116]
I'm using the gatsby wordpress plugin to retrieve my posts from my hosted WP site. Locally, gatsby build works fine and all my ACF fields are retrieved. However, on my Netlify deploy the property local file seems to be null. With other fields ACF fields being retrieved correctly.

Here is my GraphQL query:

```
{
  allWordpressPost {
            edges {
              node {
                id
                wordpress_id
                date
                guid
                modified
                slug
                status
                type
                link
                title
                content  
                acf {
                  description
                  title
                  icon
                  link
                image{             
                    slug
                    title
                    localFile{
                     childImageSharp{
                      sizes{
                        sizes
                      }
                      resolutions{
                        srcSet
                        src
                      }
                    }
                    }
                    source_url
                    link
                  }
                  
                }
              }
            }
          }
        }
```

I have already implemented the nullify function in my Wordpress function file referred to in this [ticket](https://github.com/gatsbyjs/gatsby/issues/4461)

```
function nullify_empty($value, $post_id, $field)
{
    if (empty($value)) {
        return null;
    }

    return $value;
}

add_filter('acf/format_value_for_api/type=text', 'nullify_empty', 100, 3);
add_filter('acf/format_value_for_api/type=image', 'nullify_empty', 100, 3);
add_filter('acf/format_value_for_api/type=repeater', 'nullify_empty', 100, 3);

```

I have spotted where the build logs differ on Netlify when compared to my local log. This is where I think the issue lies:

<img width="1131" alt="screen shot 2018-09-13 at 12 28 02" src="https://user-images.githubusercontent.com/10565239/45486329-992f1100-b752-11e8-95d2-2a39c64c10e2.png">

Whereas locally it only show the following:

<img width="1091" alt="screen shot 2018-09-13 at 12 42 31" src="https://user-images.githubusercontent.com/10565239/45486356-b49a1c00-b752-11e8-9986-e165062a0092.png">

And here an example of the ACF fields being logged on Netlify build log. Notice the **localfile** property:

<img width="1180" alt="screen shot 2018-09-13 at 12 41 04" src="https://user-images.githubusercontent.com/10565239/45486494-38540880-b753-11e8-9994-d1a26f4803f3.png">

Really not sure how I can debug this further but happy to provide more detail if required.

```
System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.8.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 59.0
    Safari: 11.1.2
  npmPackages:
    gatsby: ^1.9.167 => 1.9.277
    gatsby-image: ^1.0.55 => 1.0.55
    gatsby-link: ^1.6.31 => 1.6.32
    gatsby-pagination: ^1.1.0 => 1.1.0
    gatsby-plugin-catch-links: ^1.0.14 => 1.0.14
    gatsby-plugin-feed: ^1.3.15 => 1.3.15
    gatsby-plugin-google-analytics: ^1.0.14 => 1.0.15
    gatsby-plugin-manifest: ^1.0.10 => 1.0.12
    gatsby-plugin-netlify: ^1.0.21 => 1.0.21
    gatsby-plugin-netlify-cms: ^2.0.1 => 2.0.1
    gatsby-plugin-nprogress: ^1.0.9 => 1.0.9
    gatsby-plugin-offline: ^1.0.12 => 1.0.12
    gatsby-plugin-react-helmet: ^1.0.2 => 1.0.8
    gatsby-plugin-sharp: ^1.6.48 => 1.6.48
    gatsby-plugin-sitemap: ^1.2.7 => 1.2.9
    gatsby-plugin-twitter: ^1.0.14 => 1.0.14
    gatsby-remark-autolink-headers: ^1.4.10 => 1.4.11
    gatsby-remark-copy-linked-files: ^1.5.23 => 1.5.25
    gatsby-remark-images: ^1.5.34 => 1.5.36
    gatsby-remark-prismjs: ^1.2.24 => 1.2.24
    gatsby-remark-responsive-iframe: ^1.4.16 => 1.4.16
    gatsby-source-filesystem: ^1.5.10 => 1.5.11
    gatsby-source-wordpress: ^2.0.93 => 2.0.93
    gatsby-transformer-json: ^1.0.14 => 1.0.14
    gatsby-transformer-remark: ^1.7.44 => 1.7.44
    gatsby-transformer-sharp: ^1.6.27 => 1.6.27
  npmGlobalPackages:
    gatsby-cli: 1.1.58

```

**Comment by kakadiadarpan** [comment]
Hi @garethgd, it would be great if you could provide a reproduction repo for this. That would make it much simpler to diagnose this issue.

**Comment by kakadiadarpan** [comment]
@garethgd on executing `gatsby build` I can see the below log in my local:

<img width="843" alt="screen shot 2018-09-18 at 10 06 20 am" src="https://user-images.githubusercontent.com/10805593/45664674-b71dbc80-bb2a-11e8-85ef-f5addad79ed0.png">

**Comment by omaidog** [comment]
I'm having a similar issue on build (develop works ok, nullify functions implemented, etc.)

<img width="458" alt="captura de pantalla 2018-09-23 a la s 01 33 58" src="https://user-images.githubusercontent.com/501116/45924217-d6bd3800-bed0-11e8-9e2c-a3bb8691139e.png">

Maybe it's a noobish question, but is there a way to know exactly which file is returning null values? 

Thanks!
