### ISSUE TITLE
Are there page change handlers?

### ISSUE THREAD

**Issue by hassanshaikley** [gatsbyjs/gatsby#8128]
If not, how could I go about setting these up?

Just want to execute arbitrary code upon page load - for every page.

**Comment by fabe** [comment]
You can do this inside `gatsby-browser.js` with [`onRouteUpdate`](https://www.gatsbyjs.org/docs/browser-apis/#onRouteUpdate):

###### gatsby-browser.js
```js
exports.onRouteUpdate = ({ location }) => {
  console.log('new pathname', location.pathname)
}
```

**Comment by hassanshaikley** [comment]
Wow. That's nifty.

Thanks
