### ISSUE TITLE
gatsby-plugin-manifest add .ico format

### ISSUE THREAD

**Issue by sarahannnicholson** [gatsbyjs/gatsby#8132]
## Summary

Since many favicons are in .ico formats, it would be cool for gatsby-plugin-manifest to support .ico formats too. 

### Basic example
In `gatsby-config.js` 
<pre>
{
        resolve: `gatsby-plugin-manifest`,
        options: {
          name: siteName,
          short_name: siteName,
          start_url: '/',
          display: 'standalone',
          background_color: '#ffffff',
          theme_color: '#ffffff',
          icon: 'src/assets/favicon.ico',
        },
} </pre>

### Motivation

From my understanding, this is how to set a favicon with this plugin. So I think it makes sense to support favicon's usual format.

**Comment by kakadiadarpan** [comment]
Hi @sarahannnicholson, we are currently using `sharp` to process all the images and unfortunately it doesn't have the support for `.ico` files. You can check lovell/sharp#1118 for more details.

Would you be interested in working on this which will enable the support for `.ico` files?

**Comment by sarahannnicholson** [comment]
Yeah I can give it a shot!
