### ISSUE TITLE
Can i upload a Gatsby netlify site into a shared hosting LAMP?

### ISSUE THREAD

**Issue by fmorar** [gatsbyjs/gatsby#8135]
When i try to do that all img and links are broken
![screen shot 2018-09-13 at 5 14 39 pm](https://user-images.githubusercontent.com/10426338/45520856-8b8c8200-b778-11e8-9b3a-d4b38792049b.png)

**Comment by m-allanson** [comment]
Does the site work as expected when running locally? e.g. if you do `gatsby build` and then `gatsby serve`? 

It's difficult to say without more information on your setup, but generally if your shared hosting is configured to serve static html sites that should be enough. You'll need to upload the contents of your `public` directory to your shared hosting.

**Comment by LekoArts** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
