### ISSUE TITLE
SSR Broken. Only the index/404.js has actual html

### ISSUE THREAD

**Issue by magicspon** [gatsbyjs/gatsby#8136]
## Description

On build, HTML is only being generated for index.js and 404.js
Example..

Go to https://next.gatsbyjs.org and click on any link.
Turn off js, refresh, boom!
or just view source:
view-source:https://next.gatsbyjs.org/docs/gatsby-link/

`<div id="___gatsby"><div style="outline:none" tabindex="-1" role="group"></div></div>`

### Steps to reproduce

gatsby new my-blog https://github.com/gatsbyjs/gatsby-starter-blog#v2
cd my-blog
npm run build
gatsby serve
view-source:http://localhost:9000/hi-folks/

### Expected result

Each page should have all the correct html

### Actual result

Only the home page and 404 have the correct html

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.7.0 - ~/.nvm/versions/node/v10.7.0/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.1.0 - ~/.nvm/versions/node/v10.7.0/bin/npm
  Browsers:
    Chrome: 69.0.3497.92
    Firefox: 60.0.1
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-rc.24
    gatsby-plugin-feed: next => 2.0.0-rc.2
    gatsby-plugin-google-analytics: next => 2.0.0-rc.2
    gatsby-plugin-manifest: next => 2.0.2-rc.1
    gatsby-plugin-offline: next => 2.0.0-rc.7
    gatsby-plugin-react-helmet: next => 3.0.0-rc.1
    gatsby-plugin-sharp: next => 2.0.0-rc.7
    gatsby-plugin-typography: next => 2.2.0-rc.3
    gatsby-remark-copy-linked-files: next => 2.0.0-rc.5
    gatsby-remark-images: next => 2.0.1-rc.5
    gatsby-remark-prismjs: next => 3.0.0-rc.2
    gatsby-remark-responsive-iframe: next => 2.0.0-rc.5
    gatsby-remark-smartypants: next => 2.0.0-rc.1
    gatsby-source-filesystem: next => 2.0.1-rc.6
    gatsby-transformer-remark: next => 2.1.1-rc.5
    gatsby-transformer-sharp: next => 2.1.1-rc.3
  npmGlobalPackages:
    gatsby-cli: 2.0.0-beta.8
```

**Comment by magicspon** [comment]
ignore... hopefully.... possible user error... cache or something... waaa!

**Comment by magicspon** [comment]
Getting different results in firefox and chrome... something strange is happening!

**Comment by kakadiadarpan** [comment]
Hi @magicspon, I'm not able to reproduce this. After following the steps that you provided, when I view the page source for [`http://localhost:9000/hi-folks/`](http://localhost:9000/hi-folks/) I see the following HTML content there:

<img width="1680" alt="screen shot 2018-09-14 at 12 08 48 pm" src="https://user-images.githubusercontent.com/10805593/45534003-36ec1400-b817-11e8-8aa1-52fd30f8f6ce.png">

**Comment by magicspon** [comment]
@sktt... Tried removing the offline plugin. No difference.

@kakadiadarpan, so strange, I'll see if i can replicate it on my work machine.

**Comment by magicspon** [comment]
I might be going mad! 

is this right...in chrome... 
view-source:https://next.gatsbyjs.org/docs/gatsby-link/
i don't see any of the rendered content..

open incognito mode:
view-source:https://next.gatsbyjs.org/docs/gatsby-link/
i do see html... 

muy confused!

**Comment by magicspon** [comment]
Possibly going mad... gonna close!

**Comment by sktt** [comment]
@magicspon the sw is still there if even if you remove the plugin. I usually go to the application tab in devtools and remove data and sw from there!
