### ISSUE TITLE
Installing gatsby-cli with yarn does not work

### ISSUE THREAD

**Issue by palerdot** [gatsbyjs/gatsby#8138]
`yarn global add gatsby-cli`

The above command does not work. I have to use npm (`npm install -g gatsby-cli`) to make it work. Not sure if this issue is consistent across systems. 

### Environment (if relevant)
System Details:

System:
    OS: Linux 4.4 Ubuntu 16.04.1 LTS (Xenial Xerus)
    CPU: x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Shell: 4.3.46 - /bin/bash
  Binaries:
    Node: 8.11.4 - ~/.nvm/versions/node/v8.11.4/bin/node
    Yarn: 1.9.4 - /usr/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.4/bin/npm
  npmGlobalPackages:
    gatsby-cli: 1.1.58

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by stefanprobst** [comment]
Have you added yarn's global dir to your PATH? `yarn global bin` will list the directory, you should export it in your `.bashrc`, e.g.: `export PATH=$PATH:~/.yarn/bin`

**Comment by kakadiadarpan** [comment]
Hi @palerdot, any updates on the suggestions provided by @stefanprobst?

**Comment by palerdot** [comment]
@kakadiadarpan @stefanprobst For now, I have already installed with `npm`. Maybe, I will update in this thread after trying uninstalling existing and reinstalling with yarn.

**Comment by kakadiadarpan** [comment]
Sure. For now, we'll be closing this. Please reopen if you still face this issue.

**Comment by muescha** [comment]
"The above command does not work" is not enough for search. 

Could you add the error message for this command?

**Comment by DanielRuf** [comment]
> adding yarn bin to path works. This should be mentioned somewhere in the docs, just in case.

This is a known issue with Yarn and not directly related to Gatsby.

**Comment by portothree** [comment]
> "The above command does not work" is not enough for search.
> 
> Could you add the error message for this command?

Well, with me what happens is

```
warning "gatsby-cli > ink@2.6.0" has unmet peer dependency "@types/react@>=16.8.0".
[4/4] Building fresh packages...
success Installed "gatsby-cli@2.8.21" with binaries:
      - gatsby
Done in 3.65s.
```

**Comment by Ri2parna** [comment]
Forgot to check that, Fixed My issue! Thanks!

**Comment by muescha** [comment]
@ri2parna 
What was your issue exactly and how you solved it?

**Comment by Ri2parna** [comment]
> This was the issue I've been facing
> The packages seem to get installed but didn't show up when i try to run the terminal :
> The terminal gave an output that said : `command not found`
> ```
> yarn global v1.22.0
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> [3/4] Linking dependencies...
> [4/4] Building fresh packages...
> success Installed "gatsby-cli@2.11.5" with binaries:
>       - gatsby
> Done in 3.43s.
> ```

I forgot to add the yarn path to my $PATH, so i found out the directory which is why the installed packages were not showing in my terminal. I found the yarn directory to be added to the path by using `yarn global bin` and then i added it to the path using the command as stated in 
https://github.com/gatsbyjs/gatsby/issues/8138#issuecomment-421248540 and added to my bashrc file ( in my case it was the .zshrc file) and it solved my problem.
