### ISSUE TITLE
[v2] Extremely slow routing

### ISSUE THREAD

**Issue by Kadrian** [gatsbyjs/gatsby#8143]
When I'm navigating through gatsby's `<Link>` or through `navigate` to one of my created pages, the template is rendered several hundred times.

Maybe similar issue: [#7876](https://github.com/gatsbyjs/gatsby/issues/7876).

Observations:

- The site I'm navigating to is a site generated with `createPage`
- The render function of its template component is called up to 300 times until the page actually comes up. But it does come up eventually.
- When I pause the render with a debugger statement, wait a few seconds and then continue, the page comes up immediately, the render function is only called once – as if some task is running and finishing in the background.

Here's an audit that shows
- Around 6 seconds time until the navigation is finally complete
- A large series of `renderRoot` calls.
- `react-helmet` seems to be taking a lot of the time doing `reducePropsToState`
<img width="945" alt="audit" src="https://user-images.githubusercontent.com/1403093/45542418-1bcad580-b812-11e8-9cec-e32730c76b25.png">

Wondering how to find the answers to the questions: 
- What leads to the continuing render cycles? 
- Why does it eventually stop?

### Steps to reproduce

Still working on the tiniest reproducing example.

### Expected result

Navigating to a generated page renders the template once.

### Actual result

The template's render function is called several hundred times before it finishes (successfully though).

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 9.5.0 - ~/.nvm/versions/node/v9.5.0/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v9.5.0/bin/npm
  Browsers:
    Chrome: 69.0.3497.92
    Firefox: 61.0.2
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.0.0-rc.15 => 2.0.0-rc.15 
    gatsby-plugin-flow: ^1.0.1-rc.1 => 1.0.1-rc.1 
    gatsby-plugin-react-helmet: ^3.0.0-rc.1 => 3.0.0-rc.1 
    gatsby-plugin-styled-components: ^3.0.0-rc.5 => 3.0.0-rc.5 
    gatsby-source-filesystem: ^2.0.1-rc.6 => 2.0.1-rc.6 
    gatsby-transformer-json: ^2.1.1-rc.6 => 2.1.1-rc.6 
```

**Comment by kakadiadarpan** [comment]
@Kadrian Is this happening in development or production build?

**Comment by Kadrian** [comment]
In both. Now I think I've narrowed it down to the use of `react-progressive-bg-image` down the line somewhere in the created page.

Removing any use this fixed the problem for me. (was using their `ProgressiveImage` component)

Will have to replace it with `gatsby-image` I guess. Closing this, unless I still find another problem. Really weird stuff though.
