### ISSUE TITLE
Offline plugin sometimes has a fetch error

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#8145]
## Description

Some combinations of plugins can cause console errors in the browser when first visiting a site.

Using `gatsby-plugin-offline` with `gatsby-plugin-google-analytics` and a plugin that does something like:

```js
exports.onRenderBody = ({ setHeadComponents }) => {
    setHeadComponents([<script />])
}
```

will trigger the following browser error when first visiting the site:

```
Access to fetch at 'https://www.google-analytics.com/analytics.js' from origin 'http://localhost:9001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
(index):1 Uncaught (in promise) TypeError: Failed to fetch
```

Reloading the page will load the page without errors. Removing the service worker and reloading the page will display the error again.

In short: 

- offline plugin + analytics plugin = no error
- offline plugin + analytics plugin + another script = analytics fetch error

### Steps to reproduce

Repo: https://github.com/m-allanson/offline-analytics
Demo video: https://www.youtube.com/watch?v=zPzEq7aMGfA

- clone the repo
- `yarn`
- `yarn run build`
- `gatsby serve`
- browse to `http://localhost:9000`
- in Chrome open the application tab of the developer tools
- ensure _unregister service workers_ is checked
- click _clear site data_
- reload the page
- see console errors in the browser

### Expected result

No console error

### Actual result

Console error on first visit

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.9.0 - ~/.nvm/versions/node/v10.9.0/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.2.0 - ~/.nvm/versions/node/v10.9.0/bin/npm
  Browsers:
    Firefox: 62.0
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-rc.24
    gatsby-plugin-google-analytics: next => 2.0.0-rc.2
    gatsby-plugin-offline: next => 2.0.0-rc.7
  npmGlobalPackages:
    gatsby-dev-cli: 2.0.0-rc.5
    gatsby: 2.0.0-rc.24
```

**Comment by m-allanson** [comment]
Note that this will cause a _Best Practics_ warning in Lighthouse audits, e.g. for next.gatsbyjs.org this error is triggered by using `gatsby-plugin-glamor` with the offline plugin and google analytics plugin:

<img width="408" alt="screen shot 2018-09-14 at 11 54 59" src="https://user-images.githubusercontent.com/381801/45546417-1cb13680-b815-11e8-9a3d-328ecbe16478.png">

**Comment by haroldangenent** [comment]
@m-allanson / @davidbailey00: I still see the first error (in Chrome) when it tries to fetch an external resource (like Analytics).

Currently it [does catch the TypeError](https://github.com/davidbailey00/gatsby/blob/master/packages/gatsby-plugin-offline/src/sw-append.js#L16), but (at least) Chrome also throws an error from the promise itself:

```
Failed to load https://www.google-analytics.com/analytics.js: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Would it be a good approach to combine https://github.com/gatsbyjs/gatsby/pull/8183 and https://github.com/gatsbyjs/gatsby/pull/8158 to only try to fetch internal resources? Something like this:

```
resources.filter(isInternal).map(resource =>
  cache.add(resource)
)
```

Where `isInternal` would check if the URL is an internal URL. I'm not too familiar with the SW in `gatsby-plugin-offline`, but if you think this approach is valid I'm happy to prepare a PR.

**Comment by davidbailey00** [comment]
@haroldangenent actually we don't do this because some URLs (e.g. web fonts) allow CORS, which means they *can* be cached. If we only cache internal resources then we miss out on caching stuff like fonts and CSS. This does come with the downside of occasional console errors, but on the whole it's better to try to cache external resources rather than ignore all of them.

**Comment by haroldangenent** [comment]
@davidbailey00 Thanks for your response. That makes sense. Maybe it would still be an idea to use the `no-cors` mode as done in #8158 (https://github.com/gatsbyjs/gatsby/pull/8158/files) for external resources? Also found [this StackOverflow topic](https://stackoverflow.com/a/36303436) on the subject.

**Comment by davidbailey00** [comment]
@haroldangenent If I remember correctly, using `no-cors` means the response is opaque, i.e. we can't see the response body, so we wouldn't be able to cache any external resources using that option unfortunately. I remember trying this before and it didn't work, so that's actually why I left it without using `no-cors`.

**Comment by davidbailey00** [comment]
@haroldangenent Thanks for looking into this, your findings are super helpful :+1:

I'll create a PR today since this is a fairly simple change and I'm not working on tons of other things at the moment, but I'll let you know when once I've done that so you can have a look!

**Comment by haroldangenent** [comment]
@davidbailey00 PR is looking good, thanks for your work on this!
