### ISSUE TITLE
Make errors more specific

### ISSUE THREAD

**Issue by Kadrian** [gatsbyjs/gatsby#8147]
## Description

Compile error not specific enough

### Steps to reproduce

- Put a syntax error inside `gatsby-node.js`
- Execute `gatsby develop`

### Expected result

Syntax error in the `gatsby-node.js` file is pointed out.

### Actual result

Syntax error in the "gatsby config" pointed out, while there's no error in `gatsby-config.js`.
<img width="385" alt="bildschirmfoto 2018-09-14 um 13 41 52" src="https://user-images.githubusercontent.com/1403093/45548364-5f2e3f80-b824-11e8-8295-ba42aeb1c20a.png">

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 9.5.0 - ~/.nvm/versions/node/v9.5.0/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v9.5.0/bin/npm
  Browsers:
    Chrome: 69.0.3497.92
    Firefox: 61.0.2
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.0.0-rc.15 => 2.0.0-rc.15 
    gatsby-image: ^2.0.0-rc.2 => 2.0.0-rc.2 
    gatsby-plugin-flow: ^1.0.1-rc.1 => 1.0.1-rc.1 
    gatsby-plugin-react-helmet: ^3.0.0-rc.1 => 3.0.0-rc.1 
    gatsby-plugin-sharp: ^2.0.0-rc.7 => 2.0.0-rc.7 
    gatsby-plugin-styled-components: ^3.0.0-rc.5 => 3.0.0-rc.5 
    gatsby-source-filesystem: ^2.0.1-rc.6 => 2.0.1-rc.6 
    gatsby-transformer-json: ^2.1.1-rc.6 => 2.1.1-rc.6 
    gatsby-transformer-sharp: ^2.1.1-rc.3 => 2.1.1-rc.3 
```

**Comment by kakadiadarpan** [comment]
@Kadrian, can you also provide the content of `gatsby-node.js` which gave you this error?
