### ISSUE TITLE
Gatsby source airtable - regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by devrchancay** [gatsbyjs/gatsby#8175]
Hello, I am trying to implement https://github.com/jbolda/gatsby-source-airtable and I am faced with the following problem.

![image](https://user-images.githubusercontent.com/4138285/45575005-880c0000-b837-11e8-8b40-a4b7dbf71dea.png)

create the file .babelrc in the root of the project and add the necessary "presets".
![image](https://user-images.githubusercontent.com/4138285/45575164-1da78f80-b838-11e8-8fb7-2991d81cee10.png)

 also change the file gatsby-node.js in the following way.

![image](https://user-images.githubusercontent.com/4138285/45575087-e2a55c00-b837-11e8-941a-8d85c4b4d9c7.png)

and it still does not work.

**Comment by devrchancay** [comment]
Finally I could solve adding this line to the start of gatsby-config.js

```javascript
require('regenerator-runtime/runtime');
```

I still can not find how to support ES6-7-8 to gatsby, probably looking in the wrong place.

**Comment by KyleAMathews** [comment]
That plugin isn't maintained here btw. You should file an issue in its repo.
