### ISSUE TITLE
Document use of gatsby-image with gatsby-source-filesystem

### ISSUE THREAD

**Issue by Kadrian** [gatsbyjs/gatsby#8185]
I've just understood that my images couldn't be found by the whole array of:

- gatsby-transformer-sharp
- gatsby-plugin-sharp
- gatsby-image

because I didn't set up `gatsby-source-filesystem` correctly, to resolve with the images I was loading.

My suggestion: Document within `gatsby-image` that the images need to be **loaded first**, for example by using `gatsby-source-filesystem`

**Comment by kakadiadarpan** [comment]
Thanks for the quick PR @stefanprobst!
