### ISSUE TITLE
Gatsby develop fail 

### ISSUE THREAD

**Issue by jerembardon** [gatsbyjs/gatsby#8189]
## Summary
Hi,

I have install gatsby globaly and creating my app with gatsby new "app" but when I want to launch developement environnement an error occured

> error There was an error compiling the html.js component for the development server.

and ...
```
C:\Users\Jérémie\Desktop\Projects\agenda_rose\app\node_modules\gatsby\node_modules\C:UsersJérémieDesktopProjec  tsagenda_roseapp
  ode_modulesgatsby-plugin-react-helmetgatsby-ssr.js doesn't exist
          C:\Users\Jérémie\Desktop\Projects\agenda_rose\app\node_modules\gatsby\node_modules\C:UsersJérémieDesktopProjec  tsagenda_roseapp
  ode_modulesgatsby-plugin-react-helmetgatsby-ssr.jsx doesn't exist
    looking for modules in C:\Users\Jérémie\Desktop\Projects\agenda_rose\app\node_modules\gatsby\node_modules
          C:\Users\Jérémie\Desktop\Projects\agenda_rose\app\node_modules\gatsby\node_modules\C:UsersJérémieDesktopProjec  tsagenda_roseapp
  ode_modulesgatsby-plugin-react-helmetgatsby-ssr.js doesn't exist
          C:\Users\Jérémie\Desktop\Projects\agenda_rose\app\node_modules\gatsby\node_modules\C:UsersJérémieDesktopProjec  tsagenda_roseapp
  ode_modulesgatsby-plugin-react-helmetgatsby-ssr.jsx doesn't exist
    looking for modules in C:\Users\Jérémie\Desktop\Projects\agenda_rose\app\node_modules\gatsby\node_modules
      
  [C:\Users\Jérémie\Desktop\Projects\agenda_rose\app\node_modules\C:UsersJérémieDesktopProjectsagenda_roseapp
  ode_modulesgatsby-plugin-react-helmetgatsby-ssr.js]
  
[C:\Users\Jérémie\Desktop\Projects\agenda_rose\app\node_modules\gatsby\node_modules\C:UsersJérémieDesktopProjectsagend  a_roseapp
  ode_modulesgatsby-plugin-react-helmetgatsby-ssr.jsx]
   @ ./.cache/api-runner-ssr.js 4:10-119

```

I have try lumen starter,  I have  the same message:
> error There was an error compiling the html.js component for the development server.

but two plugins fails "gatsby-plugin-feed" and always "gatsby-ssr"

## Relevant information
Message above is really much much much longer (with a lot of repetition ahah). He talk about "gatsby-plugin-react-helmet" and "gatsby-ssr", but I don't really see the problem's in these fil and plugin ...

gatsby-plugin-react-helmet is correctly installed in packages.json and I have install microsoft-build-tool with npm too.

### Environment

**System:**
    -  OS: Windows 10
    -  CPU: x64 Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz

**Binaries:**
    - npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD

**npmPackages:**
    -     gatsby: ^1.9.277 => 1.9.277
    -     gatsby-link: ^1.6.46 => 1.6.46
    -     gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11

**Comment by stefanprobst** [comment]
Could you add steps how to reproduce this? Thanks.

**Comment by stefanprobst** [comment]
I am unable to reproduce this. Did steps 1 and 2 work without error?

**Comment by jerembardon** [comment]
Yep I can installing gatsby and create a new project, just `gatsby develop` command don't want to work correctly
