### ISSUE TITLE
(HELP!!) style-loader cannot be used in a non-browser environment 

### ISSUE THREAD

**Issue by xblue-light** [gatsbyjs/gatsby#8190]
Hi there, I have been trying to implement this [react-modular-audio-player](https://github.com/retrofuturejosh/react-modular-audio-player) into my Gatsby project, however webpack keeps complaining about the **style-loader** not being able to use it in a non-browser environment.

If anyone would be kind enough as to give me a hint or a guide as to how I could possibly get this to work I would be so glad Ive been pulling my hair for the past few hours with no luck.

**gatsby-config.js**

```js
module.exports = {
  siteMetadata: {
    title: "--------.ie | Latest music releases | Ireland ",
    author: "Hunter Chang",
    description: "-----.ie offers news about the latest music releases that Ireland has to offer. Having searched for the best new artists and songs in Ireland, they are bought here for you to enjoy."
  },
  pathPrefix: '/',
  
  plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `build`,
        
        filename: 'index.html',
        path: `${__dirname}/build`,
        libraryTarget: 'commonjs2',
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/assets/images`,
      },
    },
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 630,
            },
          },
          "gatsby-remark-copy-linked-files",
        ],
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-sass`,
  ],
}
```
=================================

**gatsby-node.js**
```js
exports.modifyWebpackConfig = ({ config, env }) => {
  if (env === 'develop') {
    config.removeLoader('css-loader')
    config.loader('css-loader', function(cfg) {
      cfg.test = /\.css$/
      cfg.loader = 'style!css?modules'
      return cfg
    })
  }
};

module.exports = function(config, env) {
  if (env === 'develop') {
    config.removeLoader('scss-loader')
    config.loader('scss-loader', function(cfg) {
      cfg.test = /\.scss$/
      cfg.loader = 'style!scss?modules'
      return cfg
    })
  }
}

module.exports = function(config, env) {
  if (env === 'develop') {
    config.removeLoader('sass-loader')
    config.loader('sass-loader', function(cfg) {
      cfg.test = /\.sass$/
      cfg.loader = 'style!sass?modules'
      return cfg
    })
  }
}

exports.modifyWebpackConfig = ({ config, env }) => {
  if (env === 'develop') {
    config.removeLoader('url-loader')
    config.loader('url-loader', function(cfg) {
      cfg.test = /\.(png)$/
      cfg.loader = 'url'
      return cfg
    })
  }
};

exports.modifyWebpackConfig = ({ config, env }) => {
  if (env !== 'develop') {
    config.removeLoader('babel-loader')
    config.loader('url-loader', function(cfg) {
      cfg.test = /\.jsx?$/
      cfg.exclude = /node_modules/
      cfg.loader = 'babel-loader'
      return cfg
    })
  }
};
```
==========================

index.js
```jsx
import...
import...

class Index extends React.Component............
render(
     ..........................

      let rearrangedPlayer = [
      {
        innerComponents: [
          {
            type: "play"
          }
        ]
      }
    ];

    return (
       <AudioPlayer
                  audioFiles={[
                    {
                      src: "https://my-react-testing-bed2.000webhostapp.com/sound-test.mp3",
                      title: "Wut U Do",
                      artist: "Azealia Banks"
                    }
                  ]}
                  rearrange={rearrangedPlayer}
                  playerWidth=""
                  iconSize=""
                  playIcon=""
                  playHoverIcon=""
                  pauseIcon=""
                  pauseHoverIcon=""
                />
                <AudioPlayer
                  audioFiles={[
                    {
                      src: "https://my-react-testing-bed2.000webhostapp.com/david-guetta.mp3",
                      title: "Blame It On Love",
                      artist: "David Guetta"
                    }
                  ]}
                  rearrange={rearrangedPlayer}
                  playerWidth=""
                  iconSize=""
                  playIcon=""
                  playHoverIcon=""
                  pauseIcon={album2}
                  pauseHoverIcon=""
                />
                <AudioPlayer
                  audioFiles={[
                    {
                      src: "https://my-react-testing-bed2.000webhostapp.com/my-one-and-only.mp3",
                      title: "My One And Only",
                      artist: "Tony Bennett, Diana Krall"
                    }
                  ]}
                  rearrange={rearrangedPlayer}
                  playerWidth=""
                  iconSize=""
                  playIcon=""
                  playHoverIcon=""
                  pauseIcon=""
                  pauseHoverIcon=""
                />
                <AudioPlayer
                  audioFiles={[
                    {
                      src: "https://my-react-testing-bed2.000webhostapp.com/say-lou-lou-ana.mp3",
                      title: "Ana",
                      artist: "Say Lou Lou"
                    }
                  ]}
                  rearrange={rearrangedPlayer}
                  playerWidth=""
                  iconSize=""
                  playIcon=""
                  playHoverIcon=""
                  pauseIcon=""
                  pauseHoverIcon=""
                />
    )
)

.......................
.......................
.......................
}

Index.propTypes = {
  route: React.PropTypes.object,
}

export default Index

export const pageQuery = graphql`
  query IndexQuery {
    site {
      siteMetadata {
        title
      }
    }
  }
`
```
=================================================

   Error Building static HTML for pages failed

   WebpackError: The style-loader cannot be used in a non-browser environment

  - index.js:3261 module.exports.module.exports [as exports]
    ~/react-modular-audio-player/build/index.js:3261:1

  - index.js:3159 Object.module.exports.stylesInDom
    ~/react-modular-audio-player/build/index.js:3159:1

  - index.js:21 __webpack_require__
    ~/react-modular-audio-player/build/index.js:21:1

  - index.js:664 Object.module.exports.Object.defineProperty.value
    ~/react-modular-audio-player/build/index.js:664:1

  - index.js:21 __webpack_require__
    ~/react-modular-audio-player/build/index.js:21:1

  - index.js:1456 Object.module.exports.Object.defineProperty.value
    ~/react-modular-audio-player/build/index.js:1456:1

  - index.js:21 __webpack_require__
    ~/react-modular-audio-player/build/index.js:21:1

  - index.js:67
    ~/react-modular-audio-player/build/index.js:67:1

  - index.js:70 Object.module.exports
    ~/react-modular-audio-player/build/index.js:70:1

===========================================

I also tried using this [isomorphic-style-loader](https://github.com/retrofuturejosh/react-modular-audio-player). I don't know if my gatsby-node.js is even setup accordingly since all the examples are mostly for webpack config file.

This is my other alt gatsby-node.js attempting to use the **isomorphic style loader**
```js
// webpack config example

// module.exports = {
//   module: {
//     rules: [
//       {
//         test: /\.css$/,
//         use: [
//           'isomorphic-style-loader',
//           {
//             loader: 'css-loader',
//             options: {
//               importLoaders: 1
//             }
//           },
//           'postcss-loader'
//         ]
//       }
//     ]
//   }
// };

exports.modifyWebpackConfig = ({ config, stage }) => {
  config.loader("isomorphic-style-loader", {
    test: /\.scss$/,
    loaders: [
    'style-loader',
    'css-loader',
    'sass-loader'
    ]
  });
};
```
==============================================
###

**Comment by kakadiadarpan** [comment]
@xblue-light, can you provide relevant environment information by running `gatsby info --clipboard`?

Also, when you are using `gatsby-plugin-sass`, you don't need to modify the webpack configuration for handling styles. Please try removing the changes of `gatsby-node.js`  related to webpack config modifications and check if that works for you.

**Comment by xblue-light** [comment]
System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
  Binaries:
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^1.9.235 => 1.9.277
    gatsby-image: ^1.0.42 => 1.0.55
    gatsby-link: ^1.6.39 => 1.6.46
    gatsby-plugin-google-analytics: ^1.0.24 => 1.0.31
    gatsby-plugin-react-helmet: ^1.0.8 => 1.0.8
    gatsby-plugin-sass: ^1.0.23 => 1.0.26
    gatsby-plugin-sharp: ^1.6.41 => 1.6.48
    gatsby-plugin-sitemap: ^1.2.25 => 1.2.25
    gatsby-remark-copy-linked-files: ^1.5.30 => 1.5.37
    gatsby-remark-images: ^1.5.56 => 1.5.67
    gatsby-source-filesystem: ^1.5.27 => 1.5.39
    gatsby-transformer-remark: ^1.7.37 => 1.7.44
    gatsby-transformer-sharp: ^1.6.22 => 1.6.27

**Comment by xblue-light** [comment]
I deleted the gatsby-node.js, but same error occurs when I run gatsby build it tries to export this index.js from the third party module I cant understand how can I exclude/ignore this error..

 WebpackError: The style-loader cannot be used in a non-browser environment

  - index.js:3261 module.exports.module.exports [as exports]
    ~/react-modular-audio-player/build/index.js:3261:1

  - index.js:3159 Object.module.exports.stylesInDom
    ~/react-modular-audio-player/build/index.js:3159:1

  - index.js:21 __webpack_require__
    ~/react-modular-audio-player/build/index.js:21:1

  - index.js:664 Object.module.exports.Object.defineProperty.value
    ~/react-modular-audio-player/build/index.js:664:1

  - index.js:21 __webpack_require__
    ~/react-modular-audio-player/build/index.js:21:1

  - index.js:1456 Object.module.exports.Object.defineProperty.value
    ~/react-modular-audio-player/build/index.js:1456:1

  - index.js:21 __webpack_require__
    ~/react-modular-audio-player/build/index.js:21:1

  - index.js:67
    ~/react-modular-audio-player/build/index.js:67:1

  - index.js:70 Object.exports.__esModule
    ~/react-modular-audio-player/build/index.js:70:1

**Comment by kakadiadarpan** [comment]
@xblue-light can you provide a reproduction repo for this? That would make it much easier to diagnose this issue.

**Comment by xblue-light** [comment]
@kakadiadarpan https://bitbucket.org/perfomalis/harmlessnoise.ie/

**Comment by kakadiadarpan** [comment]
@xblue-light I'm unable to reproduce this issue. Am I doing anything wrong?

Please check this [video](https://vimeo.com/290236523) for screen recording of the steps followed.

**Comment by xblue-light** [comment]
Everything is smooth, but what happens if you attempt to **gatsby build**

**Comment by kakadiadarpan** [comment]
Running `gatsby build` breaks it for me as well, `react-modular-audio-player` is using `style-loader` and it is throwing this particular error.

@pieh any suggestions on how to fix this?

**Comment by pieh** [comment]
`react-modular-audio-player` seems to be client only component and won't work when rendering static html - so you will need to disable it for that - check https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules and in your component code you will need to check if `AudioPlayer` is defined before using it

**Comment by xblue-light** [comment]
@pieh I have tried, and still results in the same error any thoughts?

exports.modifyWebpackConfig = ({ config, stage }) => {
  if (stage === "build-html") {
    config.loader("null", {
      test: /react-modular-audio-player/,
      loader: "null-loader",
    });
  }
};

**Comment by kakadiadarpan** [comment]
@pieh It throws `Invariant Violation` error.

```
Element type is invalid: expected a string (for built-in components) or a
class/function (for composite components) but got: object. Check the render method
of `Index`.
```

**Comment by pieh** [comment]
hmm, hard for me to check this out - repo points to https://bitbucket.org/ which defenitely isn't repo for this site :)

**Comment by xblue-light** [comment]
@pieh you can reproduce easily is basically gatsby starter and the third party module due to privacy related policies at work I cannot share the repo

1. https://github.com/codebushi/gatsby-starter-stellar
2. https://github.com/retrofuturejosh/react-modular-audio-player

**Quick setup in /pages/index.js**

`
import AudioPlayer from 'react-modular-audio-player';

let playlist = [
{ src: "/music.mp3",
title: "Song",
artist: "Singer" },
{ src: "/moreMusic.mp3",
title: "Another Song",
artist: "Another Singer" }
];

Inside render() function
.<AudioPlayer
audioFiles={playlist}
./>`

**Comment by xblue-light** [comment]
You can close this issue clearly it cant be resolved, I will seek different alternative solutions. Thank you.
