### ISSUE TITLE
[HELP] iOS Safari renders strangely when it navigates back by using edge swipe gesture

### ISSUE THREAD

**Issue by cdnil** [gatsbyjs/gatsby#8202]
## Description

iOS Safari renders strangely when it navigates back by using edge swipe gesture.
the popped up page will appear briefly after it disappears.

![](https://j.gifs.com/Jq52Nv.gif)

recording: https://www.youtube.com/watch?v=itXnPp2sSIs

I reproduced this issue by https://bugs--lin-am.netlify.com

and this is the repo: https://github.com/cdnil/lin.am/tree/bugs

### Steps to reproduce

1. visit the demo site using iOS Safari: https://bugs--lin-am.netlify.com
2. click the first post
3. navigate back by edge swiping gesture

### Environment

iPhone 8, iOS 12

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.9.1 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.2.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.92
    Firefox: 61.0.1
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.0.0-rc.25 => 2.0.0-rc.13 
    gatsby-image: ^2.0.0-rc.2 => 2.0.0-rc.2 
    gatsby-plugin-manifest: next => 2.0.2-rc.1 
    gatsby-plugin-offline: ^2.0.0-rc.8 => 2.0.0-rc.8 
    gatsby-plugin-react-helmet: ^3.0.0-rc.1 => 3.0.0-rc.1 
    gatsby-plugin-sharp: ^2.0.0-rc.3 => 2.0.0-rc.3 
    gatsby-plugin-styled-components: ^3.0.0-rc.5 => 3.0.0-rc.5 
    gatsby-plugin-typography: ^2.2.0-rc.3 => 2.2.0-rc.3 
    gatsby-source-filesystem: ^2.0.1-rc.1 => 2.0.1-rc.1 
    gatsby-transformer-remark: ^2.1.1-rc.5 => 2.1.1-rc.5 
    gatsby-transformer-sharp: ^2.1.1-rc.3 => 2.1.1-rc.3 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

---

Thank you.

**Comment by kakadiadarpan** [comment]
This is happening for MacOS Safari as well.
