### ISSUE TITLE
[www] API docs: return values not rendered

### ISSUE THREAD

**Issue by stefanprobst** [gatsbyjs/gatsby#8203]
The API documentation does not show the function's return values, even though they have jsdoc `@returns`. See e.g. [here](http://localhost:8002/docs/node-apis/#resolvableExtensions).

This is because the returns don't get rendered in [`function-list.js`]( gatsby/www/src/components/function-list.js )

**Comment by KyleAMathews** [comment]
Hmm this seems like an oversight. Could you look into a PR for this?

**Comment by stefanprobst** [comment]
Sure.

**Comment by KyleAMathews** [comment]
Thanks!
