### ISSUE TITLE
Question: feasibility of using Gutenberg blocks in both WordPress source and Gatsby front-end

### ISSUE THREAD

**Issue by ataylorme** [gatsbyjs/gatsby#8207]
## Summary
WordPress has a new editing experience, codenamed [Gutenberg](https://wordpress.org/gutenberg/), in development scheduled to be released with WordPress `5.0`.

The new editing experience is built on React and has the concept of blocks. I would like to use WordPress as a source for Gatsby. Ideally, the React components used in Gutenberg blocks can be reused in Gatsby so that the visual representation of what is shown in the WordPress editor is accurate to what the Gatsby built front-end will look like.

Gutenberg, by default, saves block and attribute data as JSON in HTML comments. My initial concept is to read the content from WordPress and repopulate the blocks and their attributes at build time in Gatsby.

I've built a simple site on Gatsby 1 with Markdown as a source. I have also built custom Gutenberg blocks and have a decent grasp of React.  I'm curious if this is possible/worth attempting before digging in deeper.

**Comment by helmutgranda** [comment]
Here is a similar thread: https://github.com/gatsbyjs/gatsby/issues/7465

**Comment by kakadiadarpan** [comment]
@ataylorme How about we keep the discussion about Gutenberg blocks in the thread pointed out by @helmutgranda?

Closing in favor of #7465

(Please feel free to reopen if you disagree 🙂)
