### ISSUE TITLE
[1.0] Duplicate node when on markdown file update

### ISSUE THREAD

**Issue by fabien0102** [gatsbyjs/gatsby#821]
## Repro step

1. `cd www && yarn develop`
1. Modify a markdown file - for example add `tag: 'toto'` into `docs\blog\gatsbygram-case-study\index.md`
1. Observe the bug

![image](https://cloud.githubusercontent.com/assets/1761469/25178233/3c779918-2505-11e7-9369-d7ce77d9d489.png)

Note: This bug is permanent after server restart (due to cache on `.cache/node-data.json`)

**Comment by KyleAMathews** [comment]
Fixed by #822 thanks!
