### ISSUE TITLE
Scroll to top on push not working as expected

### ISSUE THREAD

**Issue by zslabs** [gatsbyjs/gatsby#8217]
## Description

This issue was discussed quite a bit in https://github.com/gatsbyjs/gatsby/issues/3249 and fixed in https://github.com/gatsbyjs/gatsby/pull/3775 but I realized leaving a comment there probably wasn't the best; so opening up an issue here to see if this needs a bit more investigation. As described in the PR comment, I'm not not consistently getting "scroll to top" behavior.

### Steps to reproduce

 If you scrunch up the [deploy preview](https://deploy-preview-3775--gatsbygram.netlify.com/) (so there's scrollable content in the about page) when I go to the homepage, scroll down just a bit in the nav and click "About", the page scroll is not at the top.

### Expected result

Scroll to top

### Actual result

Not scrolling to top 😢

### Environment

Demo server provided by repo

**Comment by kakadiadarpan** [comment]
@zslabs I'm unable to reproduce this on latest versions of `Chrome` or `Safari`. I'm getting "scroll to top" behavior consistently (tried 10 times). It would be great if you could provide a screen capture of this issue.

**Comment by zslabs** [comment]
Hey @kakadiadarpan thanks for the reply! Here's a gif of what I was talking about (sorry - would have been more helpful if I added that to begin with):

![kapture 2018-09-18 at 10 43 01](https://user-images.githubusercontent.com/1018402/45695594-bc313a80-bb2f-11e8-8b1c-c90fa4db4740.gif)

Let me know if that helps better explain things.

**Comment by williamtstanley** [comment]
I am also having an issue with scrollToTop not working as expected.

**Comment by zslabs** [comment]
![Yuh](https://i.imgur.com/n2nZPRH.gif)

**Comment by zslabs** [comment]
Thanks! Saw this was released in `2.0.7`!

**Comment by mfix22** [comment]
I am still seeing this issue on `2.0.8`. Are there other steps I need to take when upgrading?

**Comment by pieh** [comment]
Maybe there is different issue @mfix22 - can you provide more info - reproduction repo / site etc?

**Comment by mfix22** [comment]
Unfortunately I can't provide a reproduction site at the moment /: but basically we have a footer that I equivalent on every page, so when we are scrolled to the very bottom, clicking any of the links in the footer changes the page contents correctly above the fold, but the page is still positioned on the footer itself.

**Comment by mfix22** [comment]
@pieh it ended up being the same issue as here: https://github.com/gatsbyjs/gatsby/issues/631
Sorry about that!
