### ISSUE TITLE
personalize development 404 page

### ISSUE THREAD

**Issue by abumalick** [gatsbyjs/gatsby#8234]
## Summary
Is there a way to customize the development 404 page ?

## Relevant information
We have an use case where it would be very useful that the 404 page displays specific content according to the browser url. I think that it is very easy to do that in production mode (edit 404.js), but I want to make it work also in development mode so it is easier for devs.

Is it possible to replace 404 development page ?

Thanks

### Environment (if relevant)
gatsby v1 (a v2 solution is good too, I think we will migrate quickly 🚀 

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by KyleAMathews** [comment]
Not atm! But yeah, that'd be great. Perhaps if there's a `src/pages/development-404.js` we use that?

**Comment by davidbailey00** [comment]
Hmm, 404.js should appear in development if it exists, rather than the default 404 page - can you create a reproduction repo?

**Comment by davidbailey00** [comment]
Never mind, I can see this isn't working in my main testing project.

**Comment by abumalick** [comment]
@KyleAMathews @davidbailey00 Why not use the 404.js page for development too ? I think keeping the same behavior for development and production is better.

We could display the urls that we currently see in the 404 development page in a modal so we don't lose that functionality. 

What do you think ?

**Comment by davidbailey00** [comment]
@abumalick Sounds good - I think this is meant to be the behaviour (display the custom 404 page, and fallback to the development page if one doesn't exist) but some recent PR might've changed it unintentionally.

**Comment by abumalick** [comment]
If you would accept a PR for this, I could work on it. But I will need some instructions on how to do it.

I don't really understand how are server the files for development, you are using express ?

**Comment by davidbailey00** [comment]
@abumalick I think this would probably require changes to the cache-dir code (`packages/gatsby/cache-dir`), rather than the server itself - I recall that it was working properly at some point in the past. Feel free to have a go if you'd like, otherwise I'll try to fix it next week :)

**Comment by krabbypattified** [comment]
Is there an option to disable gatsby's development 404 page? Or is there a hook to add custom code to it? I have code that needs to redirect from the 404 depending on the URL and need to test it in development mode. The newer versions of Gatsby break this functionality.

**Comment by abumalick** [comment]
There is a small button on the 404 development page that you can press to see your custom 404.js.

We use this a lot.

**Comment by Schmerb** [comment]
I could be silly, I am facing this exact thing and hot-reloading isn't reliable...but I am about to try some vanilla dom API stuff and click the button lol This might actually be a decent dev only (of course) work around. Will update soon...this is just my initial reaction when I basically read "we have to click the button"
