### ISSUE TITLE
[v2] Example "using-page-transitions" is broken

### ISSUE THREAD

**Issue by ljfranklin** [gatsbyjs/gatsby#8250]
## Description

The [using-page-transitions](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-page-transitions) example seems to be broken after today's Gatsby 2.0 release. It was correctly fading as a page transition before today but after updating the deps to go from the gatsby rcs to 2.0 releases it no longer fades.

### Steps to reproduce

1. `cd examples/using-page-transitions`
1. `npm install`
1. `gatsby develop`

### Expected result

Clicking links in the dev app should fade in and out between pages.

### Actual result

The transition happens immediately rather than fading.

### Environment

Running on Arch Linux install. Running `gatsby info --clipboard` shows "error Cannot read property '1' of null"...

**Comment by fabe** [comment]
Seems like `gatsby@2.0.0-rc.27` broke the example, `gatsby@2.0.0-rc.25` still works.
