### ISSUE TITLE
[v2] Homepage served from Contentful and not index.js

### ISSUE THREAD

**Issue by imshuffling** [gatsbyjs/gatsby#8257]
Having a hard time to work out how to render the homepage in gatsby generated from content Contentful.

I have got template/page.js template which is populated with posts from contentful, I would like to have the homepage in contentful.

As default index.js is the current homepage.

Is there a straight forward way to do this?

Thanks.

**Comment by pieh** [comment]
you can query contentful data in your index.js - alternatively you can remove index.js from `src/pages` and use `createPage` in gatsby-node to create your index page (with path set to `/`)

**Comment by imshuffling** [comment]
Thanks @pieh, have you seen any examples of this?

My current gatsby-node.js

```
const path = require(`path`)

exports.createPages = ({ graphql, actions }) => {
  const { createPage } = actions


  // Page
  const loadPage = new Promise((resolve, reject) => {
    graphql(`
      {
        allContentfulPage {
          edges {
            node {
              slug
            }
          }
        }
      }
    `).then(result => {
      result.data.allContentfulPage.edges.map(({ node }) => {
        createPage({
          path: `/${node.slug}`,
          component: path.resolve(`./src/templates/page.js`),
          context: {
            slug: node.slug,
          },
        })
      })
      resolve()
    })
  })
  return Promise.all([loadPage])
}
```

How would I go about setting the index page in the above? Thanks

**Comment by pieh** [comment]
Did you check `using-contentful` example? it has `src/pages/index.js` which query contentful for some data - https://github.com/gatsbyjs/gatsby/blob/master/examples/using-contentful/src/pages/index.js#L82-L115

**Comment by imshuffling** [comment]
Thanks @pieh, I'll check it out.

**Comment by LekoArts** [comment]
Closing this issue as answered. If you need more help, please reach out to us!
