### ISSUE TITLE
[www/plugins] Descriptions in results show unrendered Markdown code

### ISSUE THREAD

**Issue by papascott** [gatsbyjs/gatsby#8260]
(I hope this is the correct way to report bugs in the website! 😄 )

## Description

At https://www.gatsbyjs.org/plugins the descriptions show unrendered Markdown code, for example https://www.gatsbyjs.org/plugins/?=font

<hr />

![screenshot_673](https://user-images.githubusercontent.com/8681117/45681054-d4f41d00-bb3c-11e8-891d-aabd0896a819.png)

<hr />

### Steps to reproduce

Open https://www.gatsbyjs.org/plugins/?=font in a browser
### Expected result

I would expect to see rendered text in the description

### Actual result

The description shows unrendered Markdown code

**Comment by jacobherrington** [comment]
Going to take a look at this!

**Comment by kakadiadarpan** [comment]
Will be fixed by #8310
