### ISSUE TITLE
Can't complete tutorial part 4: 'rhythm' is not defined

### ISSUE THREAD

**Issue by johnjelinek** [gatsbyjs/gatsby#8267]
## Description

I'm getting an error from typography.js that it doesn't have an export for `rhythm`.

### Steps to reproduce
Follow instructions here: https://www.gatsbyjs.org/tutorial/part-four/

### Expected result

page should load
![Pandas Eating Lots](https://www.gatsbyjs.org/static/start-9a136a7536d2f4b315d446f6a1a83725-acb38.png)

### Actual result

```
src/components/layout.js
   5:10  warning  'rhytym' is defined but never used  no-unused-vars
  12:20  error    'rhythm' is not defined             no-undef
  13:24  error    'rhythm' is not defined             no-undef
  19:38  error    'rhythm' is not defined             no-undef

✖ 4 problems (3 errors, 1 warning
```

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7 CPU         870  @ 2.93GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.4 - /usr/local/opt/asdf/shims/node
    Yarn: 1.9.4 - /usr/local/opt/asdf/shims/yarn
    npm: 5.6.0 - /usr/local/opt/asdf/shims/npm
  Browsers:
    Chrome: 68.0.3440.106
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.0 => 2.0.1
    gatsby-plugin-emotion: ^2.0.5 => 2.0.5
    gatsby-plugin-typography: ^2.2.0 => 2.2.0
```

**Comment by DSchau** [comment]
Looks like you misspelled the import--happens to the best of us!

You'll need to swap `rhytym` for `rhythm`.

The ESLint warnings were super helpful in diagnosing that problem, so thanks for posting them!

Closing, but please let us know if you need anything else!

**Comment by johnjelinek** [comment]
Blast! That's the word that defeated me in the first grade spelling bee and it still defeats me today.
