### ISSUE TITLE
[www] Improve CSS breakpoint constant naming

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#8270]
I hereby propose detaching breakpoint constant names from device/screen types, changing

https://github.com/gatsbyjs/gatsby/blob/d19192cdb5902f0835373e67262ffa81f8c85b8e/www/src/utils/presets.js#L5-L16

to

- `Mobile` -> `Xs`
- `Phablet` -> `Sm`
- `Tablet` -> `Md`
- `Desktop` -> `Lg`
- `Hd` -> `Xl`
-  `VHd` -> `xxl`

If possible without too much effort, I also think we should consolidate `VHd` and `VVHd`.

While we're at that, we could also look into refactoring the homepage layout to get rid of as much of https://github.com/gatsbyjs/gatsby/blob/21221ed0ad3157aba9c06ec17186a40cc7eb7baf/www/src/components/gutters.js#L4-L7 as possible.

**Comment by DSchau** [comment]
@fk I obviously love this idea :)
