### ISSUE TITLE
[www]: Insecure mixed content detected

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#8271]
On Netlify deploy, we get e-mail(s) about insecure mixed content, basically http content links served over https.

It's _just_ two http badges as far as I can tell, so it should be a fairly doable fix.

Here's the warning direct from Netlify:

> 6:07:31 AM: Mixed content detected in: /packages/gatsby-plugin-ipfs/index.html
> 6:07:31 AM: --> insecure img urls:
> 6:07:31 AM:   - http://img.shields.io/npm/v/gatsby-plugin-ipfs.svg
> 6:07:31 AM:   - http://img.shields.io/npm/dm/gatsby-plugin-ipfs.svg
> 6:08:07 AM: Mixed content detected in: /packages/gatsby-source-trello/index.html
> 6:08:07 AM: --> insecure img urls:
> 6:08:07 AM:   - http://img.shields.io/badge/license-MIT-brightgreen.svg

**Comment by m-allanson** [comment]
See https://github.com/Necmttn/gatsby-source-trello/pull/4

**Comment by DSchau** [comment]
You beat me! Thanks!!

**Comment by m-allanson** [comment]
I can't work out the ipfs plugin though, that looks like it _has_ been published?

**Comment by DSchau** [comment]
@m-allanson I just installed it, and it looks like it still has some `http` links!

```md
[npm-image]:http://img.shields.io/npm/v/gatsby-plugin-ipfs.svg
[downloads-image]:http://img.shields.io/npm/dm/gatsby-plugin-ipfs.svg
```
