### ISSUE TITLE
'source and transform nodes' runs slowly, and every time.

### ISSUE THREAD

**Issue by dotist** [gatsbyjs/gatsby#8274]
## Description

Every time that I run **gatsby develop**, 'source and transform nodes' runs for a long time (30+ seconds). It's connecting to a Drupal Json-endpoint, where there are no more than 15 Drupal-nodes. 30 seconds for 15 pieces of content seems like a long time to me. Also, this behavior happens every time i run **gatsby develop**, but shouldn't the imported nodes be cached, making this step much quicker? 

This happens regardless of whether i'm processing the nodes in gatsby-node.js or not. 

```
System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.9.0 - /usr/local/bin/node
    Yarn: 1.9.4 - ~/.yarn/bin/yarn
    npm: 6.2.0 - /usr/local/bin/npm
  Browsers:
    Firefox: 62.0
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.0 => 2.0.1
    gatsby-plugin-manifest: ^2.0.2 => 2.0.2
    gatsby-plugin-offline: ^2.0.5 => 2.0.5
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-source-drupal: ^2.0.44 => 2.0.44
  npmGlobalPackages:
    gatsby-cli: 1.1.58
    gatsby-image: 1.0.55
    gatsby-plugin-netlify-cms: 2.0.1
    gatsby-plugin-sharp: 1.6.48
    gatsby-source-drupal: 2.0.41
    gatsby-source-filesystem: 1.5.39
    gatsby-starter-default: 1.0.0
    gatsby-transformer-sharp: 1.6.27
    gatsby: 2.0.0-rc.0
```

**Comment by kakadiadarpan** [comment]
I think this is same issue as in #6654, if anyone want to try to work on this please check  https://github.com/gatsbyjs/gatsby/issues/6654#issuecomment-417151538 for context where exactly this could be fixed

We'll be closing this issue in favor of #6654

**Comment by dotist** [comment]
Thanks for your reply, i'll follow the other issue.

**Comment by KyleAMathews** [comment]
@dotist is your site one that we could run locally? I'd love to understand better why it's happening.

**Comment by dotist** [comment]
@KyleAMathews i'll put it together in a way so that you can test it also.

**Comment by KyleAMathews** [comment]
Thanks!
