### ISSUE TITLE
[gatsby-remark-autolink-headers] Option to disable icon and customize class

### ISSUE THREAD

**Issue by jonsuh** [gatsbyjs/gatsby#8288]
## Summary

Hi! 👋 I’d like to propose 2 features for `gatsby-remark-autolink-headers`:

1. Disable the icon/anchor
2. Customize the class

### Basic example

```
plugins: [
  {
    resolve: "gatsby-remark-autolink-headers",
    options: {
      className: "custom-class",
      icon: false,
    }
  }
]
```

### Motivation

I thought these two options would help when someone wanted (1) heading `id`s without the anchor icon/link or (2) to change the icon anchor’s class name if it clashed with any existing CSS.

### Details

I opened a PR for this feature: https://github.com/gatsbyjs/gatsby/pull/8245

Open to any feedback—thanks!

**Comment by kakadiadarpan** [comment]
Fixed by #8245
