### ISSUE TITLE
How to use componentDidMount() in Gatsby Application?

### ISSUE THREAD

**Issue by reeversedev** [gatsbyjs/gatsby#8306]
```
import React, { Component } from 'react'
import ReactGA from 'react-ga'

export const initGA = () => {
  console.log('GA Init')
  ReactGA.initialize()
}
export const logPageView = () => {
  ReactGA.set({ page: window.location.pathname })
  ReactGA.pageview(window.location.pathname)
}
class App extends Component {
  componentDidMount() {
    console.log('Check 101')
    initGA()
    logPageView()
  }
  render() {
    console.log('Check 102')
    return (
      <div>Hello! This website is going to launch real soon. I am serious.</div>
    )
  }
}
export default App
```

**Comment by reeversedev** [comment]
I am unable to get any kind of output from componentDidMount() method. What can be the reason?

**Comment by kakadiadarpan** [comment]
@reeversedev can you provide a reproduction repo where we can see this? I'm unable to reproduce this issue. Please check the gif below:

![8093](https://user-images.githubusercontent.com/10805593/45733006-827a3580-bbfc-11e8-8481-7f092c5e21a8.gif)

Also, run `gatsby info --clipboard` in your project directory and paste the output here. Not working? You may need to update your global gatsby-cli - `npm install -g gatsby-cli`

**Comment by reeversedev** [comment]
@kakadiadarpan The repo where I am having this problem is:
https://github.com/reeversedev/reeversedev.github.io

**Comment by kakadiadarpan** [comment]
@reeversedev your `App` component isn't being used anywhere and that's why you don't see `componentDidMount` being executed.
