### ISSUE TITLE
Markdown Styling Seems Inconsistent

### ISSUE THREAD

**Issue by mihail911** [gatsbyjs/gatsby#8309]
## Description

I'm currently looking at [https://using-remark.gatsbyjs.org/hello-world-kitchen-sink/#h1](https://using-remark.gatsbyjs.org/hello-world-kitchen-sink/#h1) for how to include certain elements in the Markdown on the page I'm working on. In particular, I've been trying to add tables. 

However, I'm running into some inconsistencies whereby my Gatsby tables don't include any horizontal lines, compared to the original reference which has well-defined horizontal lines that span the page. 

I'm not sure if this is just a styling issue or an actual problem with Markdown support/gatsby-transformer-remark plugin. Is there a place within Gatsby where we can determine the exact styling of the Markdown being rendered? 
If anybody has any thoughts they would be greatly appreciated!

### Steps to reproduce

I am basically bootstrapping off of this starter template for my site: [https://github.com/alxshelepenok/gatsby-starter-lumen](https://github.com/alxshelepenok/gatsby-starter-lumen)

### Expected result

I expect to see lines in the case of tables. For the following code: 
```
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
```

I see this:

<img width="293" alt="screen shot 2018-09-18 at 9 52 09 pm" src="https://user-images.githubusercontent.com/2789441/45731728-d1d54d00-bb8d-11e8-9d95-95ef0c6f252a.png">

### Actual result

There are no horizontal lines. 

### Environment
```
System:
    OS: macOS High Sierra 10.13.2
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.9.0 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.2.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 47.0
    Safari: 11.0.2
  npmPackages:
    gatsby: ^1.9.164 => 1.9.277
    gatsby-link: ^1.6.34 => 1.6.46
    gatsby-plugin-catch-links: ^1.0.14 => 1.0.24
    gatsby-plugin-feed: ^1.3.15 => 1.3.25
    gatsby-plugin-google-analytics: ^1.0.15 => 1.0.31
    gatsby-plugin-google-fonts: latest => 0.0.4
    gatsby-plugin-offline: ^1.0.12 => 1.0.18
    gatsby-plugin-postcss-sass: ^1.0.15 => 1.0.22
    gatsby-plugin-react-helmet: ^2.0.3 => 2.0.11
    gatsby-plugin-sharp: ^1.6.25 => 1.6.48
    gatsby-plugin-sitemap: ^1.2.10 => 1.2.25
    gatsby-remark-copy-linked-files: ^1.5.25 => 1.5.37
    gatsby-remark-images: ^1.5.37 => 1.5.67
    gatsby-remark-prismjs: ^1.2.12 => 1.2.24
    gatsby-remark-responsive-iframe: ^1.4.16 => 1.4.20
    gatsby-remark-smartypants: ^1.4.10 => 1.4.12
    gatsby-source-filesystem: ^1.5.11 => 1.5.39
    gatsby-transformer-remark: ^1.7.28 => 1.7.44
    gatsby-transformer-sharp: ^1.6.16 => 1.6.27
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```

**Comment by fk** [comment]
Hey @mihail911!

The `using-remark` example uses [gatsby-plugin-typography](https://www.gatsbyjs.org/packages/gatsby-plugin-typography/) under the hood, which includes the table styles you saw at [using-remark.gatsbyjs.org/hello-world-kitchen-sink/#tables](https://using-remark.gatsbyjs.org/hello-world-kitchen-sink/#tables).

If you want to see how those styles are set up, take a look at https://github.com/KyleAMathews/typography.js/blob/34a98113ac6117ca74a8641adab9be8994abfe9f/packages/typography/src/utils/createStyles.js#L212-L238 or inspect the source of [using-remark.gatsbyjs.org/hello-world-kitchen-sink/#tables](https://using-remark.gatsbyjs.org/hello-world-kitchen-sink/#tables)

![image](https://user-images.githubusercontent.com/21834/45734914-74211f00-bbe6-11e8-9cb4-039242f8e55f.png)

Part two of the Gatsby Tutorial has a detailed look at using typography.js/gatsby-plugin-typography: https://www.gatsbyjs.org/tutorial/part-two/

If you don't want to use typography.js, peep https://www.gatsbyjs.org/tutorial/part-two/#other-css-options, or how we include the CSS for the webfonts we use on https://www.gatsbyjs.org in https://github.com/gatsbyjs/gatsby/blob/4d96dc5b2643d15d3b8d691111916180d4f05037/www/src/components/layout.js#L14-L18

Ah — sorry! 😺— just remembered you're using a particular starter — for `gatsby-starter-lumen`, you could add the table CSS somewhere here https://github.com/alxshelepenok/gatsby-starter-lumen/tree/master/src/assets/scss

**Comment by mihail911** [comment]
Thanks for the prompt and helpful response @fk !
