### ISSUE TITLE
Question: Gatsby's dependency on Python

### ISSUE THREAD

**Issue by NMinhNguyen** [gatsbyjs/gatsby#831]
Hey @KyleAMathews, could you please elaborate on why exactly Gatsby needs Python? I've only been able to find some info in [#623 (comment)](https://github.com/gatsbyjs/gatsby/issues/623#issuecomment-270695502). In your email reply to my query you said

> NPM requires Python to build native packages sometimes.

However, I have just checked out a project on a colleague's machine (who does not have Python installed), did `npm install` and `node_modules/.bin/gatsby develop` and `build` and it all worked fine. The reason I'm so interested in knowing why Python is required is so that I can either tell people in my team to install Python or not. And similarly for the CI server :)

Perhaps a slightly more direct question - what native packages exactly does Gatsby depend on?

**Comment by KyleAMathews** [comment]
Not every configuration of Gatsby will need Python. If your project installs without Python currently then don't worry about this until you add a dependency which does need it.

**Comment by NMinhNguyen** [comment]
Could you give an example of such dependencies? I'm happy to submit a PR to clarify the note about Python in the README file, if you wish.

**Comment by KyleAMathews** [comment]
Here's a list https://github.com/nodejs/node-gyp/wiki/%22binding.gyp%22-files-out-in-the-wild

It looks like the main one people would run into is node-sass.

**Comment by devdigital** [comment]
Also `gatsby-remark-images`->`gatsby-plugin-sharp`->`sharp`->`node-gyp`

See https://github.com/nodejs/node-gyp#installation
