### ISSUE TITLE
[v2][question] Use of no-cache logic inside app-xxx.js file

### ISSUE THREAD

**Issue by rtm619** [gatsbyjs/gatsby#8311]
```
if (!this.state.pageResources || !this.state.pageResources.json) {
                        var e = new URL(window.location);
                        return e.search ? e.search += "&no-cache=1" : e.search = "?no-cache=1", window.location.replace(e), null
}
```

Can I know for what reason its being used? Because when I use web.config to handle http errors, the urls that aren't present get concatenated with no-cache=1 and go in a refresh loop. I am executing the 404 page when the user inputs a wrong url, keeping the wrong url intact.

Thanks in advance.

**Comment by kakadiadarpan** [comment]
When a URL is appended with `?no-cache=1`, it bypasses the `service-worker` and fetches the resource from the actual server. This makes sure that the user is not served with stale data.

Closing in favour of #8297
