### ISSUE TITLE
Failed to load settings from /.netlify/identity

### ISSUE THREAD

**Issue by alexgmuir** [gatsbyjs/gatsby#8318]
## Summary

Hi, 

I've installed gatsby new netlifycms2 https://github.com/netlify-templates/gatsby-starter-netlify-cms without error. 

However when I visit /admin and click 'login with netlify' I get the message 

Failed to load settings from /.netlify/identity

I assume I need this file but haven't found any instructions as how to install it.

## Relevant information

I manually added .netlify/identity in  static/admin/.netlify/identity
then ran gatsby build and gatsby serve
however the error message persists

**Comment by alexgmuir** [comment]
I've done some reading on this blog

https://www.netlify.com/blog/2017/09/07/introducing-built-in-identity-service-to-streamline-user-management/

“Once you enable Identity services, a managed version of the GoTrue microservice lets you add user registration and management under /.netlify/identity for any Netlify site.”

I note the gotrue js is installed in the admin directory and a few others

./public/admin/cms.js
./node_modules/netlify-cms/dist/cms.js
./node_modules/gatsby-plugin-netlify-cms/cms.js
./src/cms/cms.js

I'm wondering then If I manually need to create this file and it there is a bug with the netlify identity plugin?

**Comment by kakadiadarpan** [comment]
@alexgmuir Please refer to this issue netlify/netlify-cms#1234.

/cc @erquhart 

Also, can you provide the relevant environment information by running `gatsby info --clipboard`?

**Comment by alexgmuir** [comment]
HI Darpan,

Here is the information

 System:
    OS: Linux 4.4 Ubuntu 16.04.5 LTS (Xenial Xerus)
    CPU: x64 Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 10.10.0 - /usr/bin/node
    Yarn: 1.9.4 - /usr/bin/yarn
    npm: 6.4.1 - /usr/bin/npm
  npmPackages:
    gatsby: ^2.0.0 => 2.0.1
    gatsby-plugin-netlify: ^2.0.0 => 2.0.0
    gatsby-plugin-netlify-cms: ^3.0.0 => 3.0.1
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-plugin-sass: ^2.0.1 => 2.0.1
    gatsby-plugin-sharp: ^2.0.5 => 2.0.5
    gatsby-remark-images: ^2.0.1 => 2.0.1
    gatsby-source-filesystem: ^2.0.1 => 2.0.1
    gatsby-transformer-remark: ^2.1.1 => 2.1.2
    gatsby-transformer-sharp: ^2.1.1 => 2.1.1
  npmGlobalPackages:
    gatsby-cli: 2.4.1


Regards
Alex
*https://www.linkedin.com/in/alexgmuir/
<https://www.linkedin.com/in/alexgmuir/>*

**Comment by erquhart** [comment]
@alexgmuir this isn't specific to Gatsby, and more of a question - chat with us in the [Netlify CMS community chat](https://gitter.im/netlify/netlifycms) and we'll get you sorted.

**Comment by alexgmuir** [comment]
Thanks Shawn,

You know what I've posted the question twice on the netlify community chat
and no response. I'm not really sure how that chat works effectively as a
means of asking a question.

I posted on stackoverflow however

https://stackoverflow.com/questions/52410225/gatsby-cms-failed-to-load-settings-from-netlify-identity

Could someone post an answer there?





Regards
Alex
*https://www.linkedin.com/in/alexgmuir/
<https://www.linkedin.com/in/alexgmuir/>*

**Comment by erquhart** [comment]
Sorry we didn't answer in chat! It generally does work, we have a few maintainers who field questions regularly - the guy that answered your question on stackoverflow is one of them (thanks @talves!).

If you run into anything else feel free to give the chat another shot. (Be sure to hit us in the Netlify CMS chat and not Netlify community, ours is https://gitter.im/netlify/netlifycms.)

**Comment by talves** [comment]
@erquhart sorry I missed this here. I try to remember to check here for duplicates. 😳

Reference Answer: https://stackoverflow.com/questions/52410225/gatsby-cms-failed-to-load-settings-from-netlify-identity/52431776#52431776

**Comment by alexgmuir** [comment]
No problem,, thanks very much again @talves for the post on stackoverflow..

Regards
Alex
*https://www.linkedin.com/in/alexgmuir/
<https://www.linkedin.com/in/alexgmuir/>*
