### ISSUE TITLE
Adding 'gatsby-source-filesystem' to gatsby-config.js breaks build

### ISSUE THREAD

**Issue by h0rhay** [gatsbyjs/gatsby#8319]
## Summary

When using basic gatsby starter kits, I am repeatedly encountering problems when trying to query markdown files. 

I am following the basic tutorials on the gatsby site here:
https://www.gatsbyjs.org/tutorial/part-four/#your-first-graphql-query

As soon as I install the gatsby-source-filesystem plugin and add this:

```
{
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `src`,
        path: `${__dirname}/src/`,
      },
    }
```
To my gatsby-config.js..

Then the build no longer works and I get this error every time:

<img width="647" alt="screen shot 2018-09-19 at 14 16 08" src="https://user-images.githubusercontent.com/2151724/45755543-a21e5780-bc16-11e8-96f3-73e03a29b2c5.png">

I have then removed all node_modules and reinstalled, but that still doesn't work.

Can anyone help with this most basic issue?

**Comment by stefanprobst** [comment]
Could you post your complete `gatsby-config.js` and/or link to a repo where this happens?

**Comment by CanRau** [comment]
Might this happen because you add the whole `src` directory instead of `src/pages` or similar? Haven't tried it myself but I could imagine it making problems?

**Comment by chriswingler** [comment]
Are you able to install `gatsby-source-filesystem`?  Not sure if it's related, but I have not been able to install the package and use markdown because of these errors:

```
 Couldn't find package "got@^7.1.0" required by "gatsby-source-filesystem" on the "npm" registry.
> info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
> Error: Couldn't find package "valid-url@^1.0.9" required by "gatsby-source-filesystem" on the "npm" registry.
```

**Comment by CanRau** [comment]
@chriswingler seems to be a different situation?! Yesterday I installed 2.0.1 multiple times without any problems maybe a problem with npm, or perhaps yarn proxy/mirror? have you tried once? have you tried deleting node_modules then reinstalling everything?

And anyways imho it seems more related to yarn/npm than gatsby
maybe helpful issues https://github.com/yarnpkg/yarn/issues/6029, https://github.com/yarnpkg/yarn/issues/2611, https://github.com/yarnpkg/yarn/issues/5508, [and more](https://www.google.com/search?q=yarn+add+couldn%27t+find+package)

**Comment by chriswingler** [comment]
thanks @CanRau will look into the yarn issues

**Comment by kakadiadarpan** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub issues, we have to clean some of the old issues as many of them have already been resolved with the latest updates.

Please make sure to update to the latest Gatsby version and check if that solves the issue. Let us know if that works for you by adding a comment 👍

**Comment by kakadiadarpan** [comment]
This issue is being closed because there hasn't been any activity for at least 30 days. Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem 👍
