### ISSUE TITLE
v2 incompatible plugins are shown in plugin library

### ISSUE THREAD

**Issue by jh45** [gatsbyjs/gatsby#8326]
## Description

When searching for plugins both [next.gatsbyjs.org/plugins/](https://next.gatsbyjs.org/plugins/) and [v1.gatsbyjs.org/plugins/](https://v1.gatsbyjs.org/plugins/) returns the same list so when searching for a plugin like mdx you get the plugin that is only compatible with V1 when in the V2 docs.

Note: the `edit this page on GitHub` on the [mdx page](https://next.gatsbyjs.org/packages/gatsby-plugin-mdx/?=mdx) doesn't appear to go to the right place.

### Steps to reproduce

go to [next.gatsbyjs.org/plugins/](https://next.gatsbyjs.org/plugins/)
search `mdx`
go to [v1.gatsbyjs.org/plugins/](https://v1.gatsbyjs.org/plugins/)
search `mdx`
compare results.

### Expected result

Either the search looks up based on the version, or a version number is assigned to each plugin to make it clearer.

### Actual result

The same result is returned with no way to tell which version it is for.

**Comment by pieh** [comment]
Right now we don't have automatic way of testing compatibility of plugins with gatsby versions. There are some plans to do this ( https://github.com/gatsbyjs/gatsby/issues/7143 would be part of that), but it's not there yet. 

For now it's up to plugin maintainers to add any context regarding v1/v2 compatibility in README we display.
