### ISSUE TITLE
The "gatsby develop" command throws the "There are no available GQL nodes" error

### ISSUE THREAD

**Issue by SergeyAlexeev** [gatsbyjs/gatsby#8335]
## Description

The "gatsby develop" command throws the "There are no available GQL nodes" error

### Steps to reproduce

Just follow steps from the [Getting Started](https://www.gatsbyjs.org/docs/) guide.

`npm install --global gatsby-cli`
`gatsby new gatsby-site https://github.com/gatsbyjs/gatsby-starter-default`
`cd gatsby-site`
`gatsby develop`

### Expected result

Should work.

### Actual result

Throws the error.

### Environment

  System:
    OS: Linux 4.13 Ubuntu 17.10 (Artful Aardvark)
    CPU: x64 Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 10.6.0 - /usr/bin/node
    Yarn: 1.9.4 - /usr/bin/yarn
    npm: 6.1.0 - /usr/bin/npm
  Browsers:
    Chrome: 69.0.3497.92
    Firefox: 61.0.1
  npmPackages:
    gatsby: ^2.0.0 => 2.0.4 
  npmGlobalPackages:
    gatsby-cli: 2.4.1

**Comment by kakadiadarpan** [comment]
@SergeyAlexeev can you share the complete error? I'm unable to reproduce this issue.

**Comment by SergeyAlexeev** [comment]
Sure, I'll provide a call stack later. Today evening.

**Comment by SergeyAlexeev** [comment]
The callstack:

success open and validate gatsby-config — 0.007 s
success load plugins — 0.182 s
success onPreInit — 0.006 s
success delete html and css files from previous builds — 0.005 s
success initialize cache — 0.008 s
success copy gatsby files — 0.033 s
success onPreBootstrap — 0.000 s
warning The internal-data-bridge plugin has generated no Gatsby nodes. Do you need it?
success source and transform nodes — 0.001 s
error There are no available GQL nodes

Error: Invariant Violation: There are no available GQL nodes  
  - invariant.js:40 invariant
    [gatsby-site]/[invariant]/invariant.js:40:15
  - index.js:38 
    [gatsby-site]/[gatsby]/dist/schema/index.js:38:5
  - Generator.next
  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23
  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31
  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18
  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10
  - promise.js:694 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18
  - async.js:138 _drainQueueStep
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:138:12
  - async.js:131 _drainQueue
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:131:9
  - async.js:147 Async._drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:147:5
  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:17:14
  
error UNHANDLED REJECTION

**Comment by NathanLawrence** [comment]
@SergeyAlexeev Are you able to post your versions for Node, gatsby-cli, and gatsby (from `gatsby-site/package-lock`)?

I just tried a bunch of variations on starter versions, Node versions and the like, but I still could not recreate this specific error. I got through bootstrap every time.

**Comment by SergeyAlexeev** [comment]
Node v10.6.0
gatsby-cli 2.4.1
gatsby 2.0.2

**Comment by Manoz** [comment]
Same issue...

```
> gatsby develop

Something is already running at port 8000 
Would you like to run the app at another port instead? [Y/n] y
success open and validate gatsby-config — 0.005 s
success load plugins — 0.188 s
success onPreInit — 0.010 s
success delete html and css files from previous builds — 0.006 s
success initialize cache — 0.006 s
success copy gatsby files — 0.008 s
success onPreBootstrap — 0.000 s
warning The internal-data-bridge plugin has generated no Gatsby nodes. Do you need it?
warning The gatsby-source-filesystem plugin has generated no Gatsby nodes. Do you need it?
success source and transform nodes — 0.001 s
error There are no available GQL nodes


  Error: Invariant Violation: There are no available GQL nodes
```

**Comment by kakadiadarpan** [comment]
@Manoz can you provide relevant environment info by running `gatsby info --clipboard`?

**Comment by Manoz** [comment]
> @Manoz can you provide relevant environment info by running `gatsby info --clipboard`?

Everything looks ok on Windows or Mac. Just have the issue on my working computer.
Will share the stack tomorrow morning :)

**Comment by Manoz** [comment]
@kakadiadarpan here's the env infos:
```
  System:
    OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
    CPU: x64 Intel(R) Pentium(R) Silver N5000 CPU @ 1.10GHz
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 11.0.0 - /usr/local/bin/node
    Yarn: 1.12.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.77
    Firefox: 63.0
  npmPackages:
    gatsby: ^2.0.22 => 2.0.22 
    gatsby-plugin-catch-links: ^2.0.4 => 2.0.4 
    gatsby-plugin-eslint: ^2.0.1 => 2.0.1 
    gatsby-plugin-feed: ^2.0.8 => 2.0.8 
    gatsby-plugin-google-analytics: ^2.0.6 => 2.0.6 
    gatsby-plugin-google-fonts: ^0.0.4 => 0.0.4 
    gatsby-plugin-lodash: ^3.0.1 => 3.0.1 
    gatsby-plugin-manifest: ^2.0.5 => 2.0.5 
    gatsby-plugin-netlify: ^2.0.1 => 2.0.1 
    gatsby-plugin-nprogress: ^2.0.5 => 2.0.5 
    gatsby-plugin-offline: ^2.0.6 => 2.0.6 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-sharp: ^2.0.6 => 2.0.6 
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.1 
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.0 
    gatsby-plugin-twitter: ^2.0.6 => 2.0.6 
    gatsby-remark-autolink-headers: ^2.0.6 => 2.0.6 
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.0.5 
    gatsby-remark-images: ^2.0.4 => 2.0.4 
    gatsby-remark-prismjs: ^3.0.2 => 3.0.2 
    gatsby-remark-responsive-iframe: ^2.0.5 => 2.0.5 
    gatsby-source-filesystem: ^2.0.3 => 2.0.3 
    gatsby-transformer-remark: ^2.1.7 => 2.1.7 
    gatsby-transformer-sharp: ^2.1.3 => 2.1.3 
  npmGlobalPackages:
    gatsby-cli: 2.4.4
```

**Comment by jonniebigodes** [comment]
Can you provide a repo if possible? Because i'm not being able to reproduce the issue also

**Comment by Manoz** [comment]
I have the same issue everywhere actually but you can try on this repo https://github.com/Manoz/k-legrand.com

**Comment by jonniebigodes** [comment]
@Manoz on the pc i'm using for development currently 
with the following output from gatsby info
```zsh
 System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  Binaries:
    Yarn: 1.10.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.0.40 => 2.0.48
    gatsby-plugin-catch-links: ^2.0.6 => 2.0.8
    gatsby-plugin-eslint: ^2.0.1 => 2.0.1
    gatsby-plugin-feed: ^2.0.9 => 2.0.9
    gatsby-plugin-google-analytics: ^2.0.7 => 2.0.7
    gatsby-plugin-google-fonts: ^0.0.4 => 0.0.4
    gatsby-plugin-lodash: ^3.0.2 => 3.0.2
    gatsby-plugin-manifest: ^2.0.7 => 2.0.9
    gatsby-plugin-netlify: ^2.0.3 => 2.0.4
    gatsby-plugin-nprogress: ^2.0.6 => 2.0.6
    gatsby-plugin-offline: ^2.0.12 => 2.0.14
    gatsby-plugin-react-helmet: ^3.0.1 => 3.0.2
    gatsby-plugin-sharp: ^2.0.12 => 2.0.12
    gatsby-plugin-sitemap: ^2.0.2 => 2.0.2
    gatsby-plugin-styled-components: ^3.0.1 => 3.0.1
    gatsby-plugin-twitter: ^2.0.7 => 2.0.7
    gatsby-remark-autolink-headers: ^2.0.10 => 2.0.11
    gatsby-remark-copy-linked-files: ^2.0.6 => 2.0.6
    gatsby-remark-images: ^2.0.6 => 2.0.6
    gatsby-remark-prismjs: ^3.0.3 => 3.0.3
    gatsby-remark-responsive-iframe: ^2.0.6 => 2.0.6
    gatsby-source-filesystem: ^2.0.7 => 2.0.8
    gatsby-transformer-remark: ^2.1.11 => 2.1.12
    gatsby-transformer-sharp: ^2.1.8 => 2.1.8
```
i get the following when running `gatsby develop`
```zsh
success open and validate gatsby-configs — 0.010 s
    success load plugins — 0.359 s
    success onPreInit — 3.155 s
    success delete html and css files from previous builds — 0.075 s
    success initialize cache — 0.009 s
    success copy gatsby files — 0.224 s
    success onPreBootstrap — 0.016 s
    success source and transform nodes — 0.196 s
    success building schema — 0.549 s
    success createPages — 0.108 s
    success createPagesStatefully — 0.100 s
    success onPreExtractQueries — 0.007 s
    success update schema — 0.295 s
    success extract queries from components — 0.249 s
    success run graphql queries — 0.202 s — 9/9 44.76 queries/second
    success write out page data — 0.041 s
    success write out redirect data — 0.005 s
    success onPostBootstrap — 0.003 s

info bootstrap finished - 15.431 s

 DONE  Compiled successfully in 9836ms
 
You can now view k-legrand.com in the browser.

  http://localhost:8000/

View GraphiQL, an in-browser IDE, to explore your site's data and schema

  http://localhost:8000/___graphql

Note that the development build is not optimized.
To create a production build, use gatsby build

i ｢wdm｣:
i ｢wdm｣: Compiled successfully.
```

i'm currenty updating yarn and node to the latest stable releases and see if anything changes and report back to you

**Comment by jonniebigodes** [comment]
@Manoz re-ran it same output. It compiled without issues, booted a vm running ubuntu 18.04 same result, no issues reported. Sorry that i could not help out more

**Comment by Manoz** [comment]
Hum sounds fun :D 
I tried on another laptop with a fresh install of Ubuntu. Same issue :/ 

I’ll dig more tonight. I saw some weird stuff inside npm logs. It’s like if MarkdownRemark doesn’t have everything to build the content. I copy/paste the log in few hours.

**Comment by SAGGameDeveloper** [comment]
I got this exact problem on a fresh gatsby install:

- Ubuntu 18.04.1 LTS.
- gatsby 2.4.8
- npm 6.7.0
- node 11.8.0

I initially got this error with older versions, then updated everything to the last stable release. After an hour trying to find the problem, I found it was the name of the folder, which contained `[` and `]`. This seems to cause an error with the way gatsby parses the paths. I don't know if this is a bug or it is intended not to allow the user to use those characters. In any case, this behaviour is quite annoying if you have no idea whatsoever what's causing it.

**Comment by jonniebigodes** [comment]
@SAGGameDeveloper if that's the case, then @Manoz for instance which has the content inside a folder with the following way ``dd-mm-yyy` also doesn't work for him, but for me it does, on either case, i.e: linux on wsl and win 10. Also if that's the case, the library not allowing special characters of combinations of characters, then the plugin should throw the appropriate message in the error not a generic one.
