### ISSUE TITLE
plugin-netlify-cms: No redirect after re-login

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#8352]
## Description

Netlify CMS doesn't handle redirect after re-logging in. I'm opening this issue to pair with a PR I'm about to submit. 

See #8286

### Steps to reproduce

1. Login to Netlify CMS
2. Reload Page (redirects to Admin)
3. Logout 
4. Login again

### Expected result

Redirect to Admin.

### Actual result

No redirect.

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i5-5575R CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.3 => 2.0.3
    gatsby-cli: 2.0.0-rc.1 => 2.0.0-rc.1
    gatsby-image: ^2.0.0-rc.1 => 2.0.0-rc.1
    gatsby-plugin-catch-links: ^2.0.2-rc.1 => 2.0.2-rc.1
    gatsby-plugin-favicon: ^3.1.2 => 3.1.4
    gatsby-plugin-manifest: 2.0.2-rc.1 => 2.0.2-rc.1
    gatsby-plugin-netlify-cms: ^3.0.2 => 3.0.2
    gatsby-plugin-node-fields: ^1.0.0 => 1.0.0
    gatsby-plugin-offline: 2.0.0-rc.1 => 2.0.0-rc.1
    gatsby-plugin-page-creator: ^2.0.0-rc.1 => 2.0.0-rc.1
    gatsby-plugin-react-helmet: 3.0.0-rc.1 => 3.0.0-rc.1
    gatsby-plugin-remove-trailing-slashes: ^2.0.0-rc.1 => 2.0.0-rc.1
    gatsby-plugin-sharp: ^2.0.0-rc.2 => 2.0.0-rc.3
    gatsby-plugin-styled-components: 3.0.0-rc.1 => 3.0.0-rc.1
    gatsby-remark-copy-linked-files: ^2.0.0-rc.1 => 2.0.0-rc.1
    gatsby-remark-embed-video: ^1.4.0 => 1.4.0
    gatsby-remark-images: ^2.0.1-rc.1 => 2.0.1-rc.1
    gatsby-remark-responsive-iframe: ^2.0.0-rc.1 => 2.0.0-rc.1
    gatsby-remark-smartypants: ^2.0.0-rc.1 => 2.0.0-rc.1
    gatsby-source-filesystem: ^2.0.1-rc.1 => 2.0.1-rc.1
    gatsby-transformer-json: ^2.1.1-rc.6 => 2.1.1-rc.6
    gatsby-transformer-remark: ^2.1.1-rc.1 => 2.1.1-rc.1
    gatsby-transformer-sharp: ^2.1.1-rc.2 => 2.1.1-rc.2
  npmGlobalPackages:
    gatsby-cli: 2.0.0-beta.13

Run `gatsby info --clipboard` in your project directory and paste the output here. Not working? You may need to update your global gatsby-cli - `npm install -g gatsby-cli`

**Comment by kakadiadarpan** [comment]
Thanks for the PR @Undistraction!
