### ISSUE TITLE
[v2][gatsby-source-contentful] Alternative for responsiveResolution?

### ISSUE THREAD

**Issue by rtm619** [gatsbyjs/gatsby#8360]
## Summary

Was responsiveResolution deprecated? If so, what is the alternative for responsiveResolution in gatsby v2?

### Environment (if relevant)

System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 41.16299.611.0
  npmPackages:
    gatsby: ^2.0.6 => 2.0.6
    gatsby-image: ^2.0.6 => 2.0.6
    gatsby-link: ^2.0.1 => 2.0.1
    gatsby-plugin-google-analytics: ^2.0.6 => 2.0.6
    gatsby-plugin-purify-css: ^2.2.1 => 2.2.1
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-plugin-remove-trailing-slashes: ^2.0.0 => 2.0.0
    gatsby-plugin-robots-txt: ^1.3.0 => 1.3.0
    gatsby-plugin-sass: ^2.0.0-rc.2 => 2.0.1
    gatsby-plugin-sharp: ^2.0.5 => 2.0.5
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.1
    gatsby-source-contentful: ^1.3.48 => 1.3.48
    gatsby-transformer-remark: ^2.1.3 => 2.1.3
    gatsby-transformer-sharp: ^2.1.1 => 2.1.1

**Comment by LeKoArts** [comment]
`sizes => fluid` and `resolutions => fixed`.

See:
https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/#rename-responsive-image-queries
https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-image#gatsby-source-contentful
