### ISSUE TITLE
Tutorial/docs: Mention/add favicon.ico

### ISSUE THREAD

**Issue by amberleyromo** [gatsbyjs/gatsby#8366]
- [ ] /tutorial/part-eight/
- [ ] /docs/add-a-manifest-file

https://twitter.com/jlengstorf/status/1042537527544963073

**Comment by nclandrei** [comment]
Hi @amberleyromo! Can I take this one on? 😄

**Comment by LuisPaGarcia** [comment]
Hi, @amberleyromo! 
Can i take this one?

**Comment by amberleyromo** [comment]
@nclandrei -- go for it, thank you!

@LuisPaGarcia ^another contributor commented first! You might be interested in checking out the other hacktoberfest issues 😄

**Comment by hemakshis** [comment]
Hi @amberleyromo, can I take this up? This would be my first issue to gatsbyjs. Also, it would be helpful if you could provide a little more detail on what needs to be done as the description is not much clear to me. Thank you :)

**Comment by hemakshis** [comment]
Hi @LekoArts, I have submitted a PR #11071. Please let me know if any changes are required :smiley: 

Thank you!
