### ISSUE TITLE
Error: Cannot find module 'webpack/lib/removeAndDo'

### ISSUE THREAD

**Issue by aesign** [gatsbyjs/gatsby#8368]
Hey can you please help? I get this every time I try to launch "gatsby build".

Here's the complete terminal log:

error There was a problem loading the local build command. Gatsby may not be installed. Perhaps you need to run "npm install"?

  Error: Cannot find module 'webpack/lib/removeAndDo'
  
  - module.js:11 require
    internal/module.js:11:18
  
  - ExtractedModule.js:30 Object.<anonymous>
    [Tweakbox]/[extract-text-webpack-plugin]/ExtractedModule.js:30:42
  
  - module.js:11 require
    internal/module.js:11:18
  
  - index.js:7 Object.<anonymous>
    [Tweakbox]/[extract-text-webpack-plugin]/index.js:7:23
  
  - module.js:11 require
    internal/module.js:11:18
  
  - index.js:3 Object.<anonymous>
    [Tweakbox]/[gatsby-1-config-extract-plugin]/index.js:3:33

**Comment by kakadiadarpan** [comment]
@aesign can you provide relevant environment information by running `gatsby info --clipboard`?

**Comment by aesign** [comment]
Sure! Here is it:

  System:
    OS: macOS High Sierra 10.13.5
    CPU: x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.4 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Safari: 11.1.1
  npmPackages:
    gatsby: ^1.9.277 => 1.9.277 
    gatsby-link: ^1.6.46 => 1.6.46 
    gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

**Comment by nicomfe** [comment]
Having same issue here.

System:
    OS: OS X El Capitan 10.11.3
    CPU: x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 9.11.2 - ~/.nvm/versions/node/v9.11.2/bin/node
    Yarn: 1.9.4 - ~/.nvm/versions/node/v9.11.2/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v9.11.2/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 62.0
    Safari: 9.0.3
  npmPackages:
    gatsby: 2.0.21 => 2.0.21
    gatsby-link: 2.0.4 => 2.0.4
    gatsby-plugin-postcss-sass: 1.0.22 => 1.0.22
    gatsby-plugin-react-helmet: 3.0.0 => 3.0.0
    gatsby-plugin-sitemap: 2.0.1 => 2.0.1
    gatsby-source-contentful: 2.0.3 => 2.0.3
  npmGlobalPackages:
    gatsby: 1.9.277

**Comment by maaz93** [comment]
I faced a similar errors while trying to migrate to gatsby@v2. I figured it was because of a plugin that was not compatible with v2. In my case, it was `gatsby-plugin-postcss-sass` which has been deleted in v2 itself.

**Comment by benjaminhoffman** [comment]
@maaz93 same.  what did you do instead of using `gatsby-plugin-postcss-sass`?

**Comment by benjaminhoffman** [comment]
this issue is related to https://github.com/gatsbyjs/gatsby/issues/5774 and can thus likely be closed.  

feel free to re-open if you are still experiencing an issue.  thx!

**Comment by maaz93** [comment]
> @maaz93 same. what did you do instead of using `gatsby-plugin-postcss-sass`?

@benjaminhoffman The starter I used is using both `sass` and `postcss`, so I used `gatsby-plugin-sass` and passed the `postcss` plugins in the `postCssPlugins` option. That did the job for me.
