### ISSUE TITLE
Gatsby's .eslintignore being ignored

### ISSUE THREAD

**Issue by NMinhNguyen** [gatsbyjs/gatsby#837]
Gatsby version: 0.12.45

Hi, I noticed that `npm test` on master fails due to some linting problems in `interfaces` folder, however this folder is actually specified in `.eslintignore`. But because linting is configured with `--ignore-path .gitignore` in `package.json`, `.eslintignore` is ignored in favour of `.gitignore`.

```json
{
  "scripts": {
    "lint": "eslint --ext .js,.jsx --ignore-path .gitignore ."
  }
}
```

From [ESLint docs](http://eslint.org/docs/user-guide/configuring#using-an-alternate-file):

> Keep in mind that specifying `--ignore-path` means that any existing `.eslintignore` file will not be used.

Short of copying the contents of `.gitignore` into `.eslintignore`, I'm not sure what the best way to combine `.eslintignore` and `.gitignore` is.

You can scroll to the bottom of this recent [build log](https://travis-ci.org/gatsbyjs/gatsby/jobs/223654835) to see the exact error

**Comment by KyleAMathews** [comment]
So it turns out you can add multiple `--ignore-path`! https://github.com/gatsbyjs/gatsby/commit/bd068fde91dedb74fa0e863a9000900c50fce61e :-)

https://travis-ci.org/gatsbyjs/gatsby/builds/224775750

Thanks for doing the background research on this!

**Comment by NMinhNguyen** [comment]
I'm afraid that's not true 😔 I had a `dist` folder on my machine, and it tried to lint it. I think the last `--ignore-path` wins - try swapping `.eslintignore` and `.gitignore`, and you'll see that the `interfaces` folder isn't being ignored again.

**Comment by KyleAMathews** [comment]
Oh hmmm...

**Comment by NMinhNguyen** [comment]
An easy (but not very scalable/optimal) solution would be to perhaps use `--ignore-pattern interfaces`?

**Comment by KyleAMathews** [comment]
I guess we could just ignore the interfaces directory directly in the command. Trying that https://github.com/gatsbyjs/gatsby/commit/06a4b452ec8a46a22ad265a76c06c69d89994eaa

**Comment by KyleAMathews** [comment]
Heh, our brain waves connected!

**Comment by NMinhNguyen** [comment]
It [worked](https://travis-ci.org/gatsbyjs/gatsby/builds/224803995)! Works locally as well, with an existing dist folder :)

**Comment by KyleAMathews** [comment]
💯
