### ISSUE TITLE
Can I use a custom 404 in development? Can I get route information in my custom 404 page?

### ISSUE THREAD

**Issue by jwietelmann** [gatsbyjs/gatsby#8380]
The 404 page is critical to what I'm doing, which is creating a Wiki-like site where landing on a missing page gives you a placeholder with a "create page" link that goes to GitHub. Therefore, testing its behavior during development is very important.

1. Is there something I can do to be able to test it in `gatsby develop`, or am I stuck doing a full build and browsing the static output?
1. Will I be able to receive and use the requested route on my 404 page? (I want to map this to a GitHub URL for creating the page in Markdown.)

**Comment by kakadiadarpan** [comment]
Hi @jwietelmann, we already have an issue open regarding custom 404 in development.

We'll be closing this issue in favor of that, please follow issue #8234 for updates/discussions on this.
