### ISSUE TITLE
[ci]: gatsby-dev-cli in CircleCI sometimes copies over 0 files

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#8381]
## Description

CircleCI sometimes copies over 0 files from the packages/ directory, which causes the e2e builds to (usually) fail 

### Steps to reproduce

Check out [this CircleCI build](https://circleci.com/gh/gatsbyjs/gatsby/1686?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). The failures are intermittent, sometimes files copy over, sometimes they don't 🤷‍♂️ Really weird error.

### Expected result

gatsby-dev-cli should deterministically copy over all the contents of packages/ with the --copy-all flag.

### Actual result

It didn't.

### Environment

N/A

**Comment by DSchau** [comment]
My best guess at this right now is that the attach_to_workspace command isn't quite working like I'd expect. So it's saving the results of packages/* but it's not correctly attaching them. Will investigate!

**Comment by m-allanson** [comment]
I see occasional failures that seem similar to this: https://circleci.com/gh/gatsbyjs/gatsby/167949

It seems to be node 10 and node 12 unit tests that fail. Node 8 unit tests will be fine. I can't replicate the problem locally.

Checking in the container the `dist` directories were missing, which could be an `attach_workspace` problem?
