### ISSUE TITLE
Convert config back to JS

### ISSUE THREAD

**Issue by aendrew** [gatsbyjs/gatsby#839]
See comment [here][1].

[1]: https://github.com/gatsbyjs/gatsby/pull/581#issuecomment-296398532

**Comment by KyleAMathews** [comment]
You're in luck! We already converted the config in 1.0 to straight JS. So no TOML unless you want TOML. Check out the WIP gatsby site config https://github.com/gatsbyjs/gatsby/blob/1.0/www/gatsby-config.js

**Comment by KyleAMathews** [comment]
Let us know if you have any thoughts on how the 1.0 config is structured. We're still in alpha so plenty of time to make breaking changes (though hoping to release the first beta soon at which point I'll be much more hesitant to make breaking changes).

**Comment by aendrew** [comment]
Ah, cheers, thanks!
