### ISSUE TITLE
Implement file name emphasis in docs

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#8393]
## Summary

At the top of code snippets, the file name where they ought to be pasted should be emphasized.

### Basic example

Here is the PR that implemented the functionality: #7867
Now we just need to go through the docs and the tutorial (and possibly official plugin and starter READmes?) and use the functionality wherever there is a code snippet that is meant to be pasted into a specific file.

### Motivation

In a workshop last May, I noticed that many people paste code snippets into the incorrect file. This way of emphasizing file names will hopefully help everyone paste code into the correct place.

### Next steps
If anyone wants to also tackle #5030, that would be an ideal companion issue to tackle along with this one.

**Comment by shannonbux** [comment]
@DSchau @kakadiadarpan

**Comment by DSchau** [comment]
@shannonbux 🎉 I'll see if I can find some time to get the copy snippet stuff working. Could be kinda fun to work on!
