### ISSUE TITLE
Broken link in migration Documentation

### ISSUE THREAD

**Issue by kingluddite** [gatsbyjs/gatsby#8396]
This link is broken:

https://github.com/gatsbyjs/gatsby/blob/master/tutorial

Here is where the link is: https://i.imgur.com/mywhA71.png

**Comment by ReesesSnickers** [comment]
I went to [https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#starting-a-new-project-with-v2](https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#starting-a-new-project-with-v2) to where this Imgur link is stating there is an issue. 

When I click this link I get sent to [https://next.gatsbyjs.org/tutorial/](https://next.gatsbyjs.org/tutorial/)

When I inspected the link using Chrome Dev Tool Kit the code is:

`<a href="/tutorial/">follow the tutorial</a>`

when I hovered over the href code in the Tool Kit, it states the URL for this would be:
[https://next.gatsby.org/tutorial](https://next.gatsby.org/tutorial) which did send me to the v2 "Tutorial (Step-by-Step)" instructions.

This worked on both my Mac and Windows laptop. I feel this issue has already been corrected. #

**Comment by kakadiadarpan** [comment]
@kingluddite From the screenshot you provided, I understand that you clicked on that link from the GitHub repository. However, the `docs` folder in the repository is used to power the Gatsby website. The desired URL here is [`https://gatsbyjs.org/tutorial/`](https://gatsbyjs.org/tutorial/) and not [`https://github.com/gatsbyjs/gatsby/blob/master/tutorial`](https://github.com/gatsbyjs/gatsby/blob/master/tutorial).

Please use [`https://gatsbyjs.org/`](https://gatsbyjs.org/) for documentation on Gatsby to get the proper experience.

**Comment by kingluddite** [comment]
Will do. Thx 4 heads up
