### ISSUE TITLE
Redirect next.gatsbyjs.org to gatsbyjs.org

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#8398]
We're not deploying new stuff there and we should redirect any links to pages there back to gatsbyjs.org

**Comment by CanRau** [comment]
A `next` branch with a simplest noop website and a _redirects file or what do you have in mind?
That's at least the only one I could help with as far as I know

**Comment by calcsam** [comment]
I've set up subdomain forwarding through our DNS provider, with path forwarding, SSL included. Forwarding is 301 (permanent) so our Google juice should transfer. This _should_ work. If anyone sees examples where it doesn't, please comment here!

**Comment by kakadiadarpan** [comment]
@calcsam I'm still able to visit [https://next.gatsbyjs.org/](https://next.gatsbyjs.org/), I'm not sure why. If I hit `next.gatsbyjs.org`, it redirects me to `https://www.gatsbyjs.org/` as expected.

But if I hit `https://next.gatsbyjs.org/`, I don't get redirected to `https://www.gatsbyjs.org/`.

Author of #8464 is also landing on `https://next.gatsbyjs.org/`

**Comment by calcsam** [comment]
@kakadiadarpan Try checking in an incognito tab -- your result is being cached. Or click around until you get to a link you've never hit before -- you should redirect then. I'm not sure how long our cache gets stored for.
