### ISSUE TITLE
Type in a link on the website

### ISSUE THREAD

**Issue by kiyutink** [gatsbyjs/gatsby#8410]
https://www.gatsbyjs.org/packages/gatsby-source-storyblok/?=story

the link to storyblok website has a typo: htts instead of https

**Comment by jonsuh** [comment]
@kiyutink Thanks for mentioning this!

Looks like the typo exists in another repo—I’ve created a PR to fix this issue https://github.com/storyblok/gatsby-source-storyblok/pull/2

**Comment by fk** [comment]
Thanks @jonsuh! 🙏
