### ISSUE TITLE
Create decision flowchart for PR review steps

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#8414]
Excerpt from https://github.com/gatsbyjs/gatsby/issues/7583#issuecomment-420441954:

## What is our PR review process?

![img_20180911_134759](https://user-images.githubusercontent.com/163561/45388319-78897e80-b5cd-11e8-948b-cc3e76a65598.jpg)

> **NOTE:** This is written as pseudo-code-ish flow charts. Please ask if this is confusing.

1. Did the tests pass?
	- Yes
		- Continue to step 2
	- No
		- Post a comment letting the author know
		- Label as `status: blocked`
		- Exit the flow
2. Is this PR from a first-time contributor?
	- Yes
		- Add the label `review first`
		- Continue to step 3
	- No
		- Continue to step 3
3. Is this PR small? (<= 20 lines changed)
	- Yes
		- Add the label `review first`
	- No
		- Post a comment with tips for:
			- Getting faster reviews by submitting smaller PRs
			- How to break large PRs into smaller ones
4. Assign the PR to its author
	- I forgot to add this in the original photo

**Comment by marisamorby** [comment]
Whimsical link: https://whimsical.co/55WMhe5r2FvAg4AnfADMVj

**Comment by jlengstorf** [comment]
@marisamorby I'm unable to edit/comment on this. Can you add me, please?

**Comment by marisamorby** [comment]
@jlengstorf I had it in the wrong folder, my bad. Should work now! Here's the link: https://whimsical.co/55WMhe5r2FvAg4AnfADMVj

**Comment by marisamorby** [comment]
Flowchart was created, closing this issue.
