### ISSUE TITLE
Create decision flowchart for stale issue review steps

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#8415]
Excerpt from https://github.com/gatsbyjs/gatsby/issues/7583#issuecomment-420441954:

## How do we handle stale issues?

![img_20180911_133448](https://user-images.githubusercontent.com/163561/45388308-69a2cc00-b5cd-11e8-9f7a-8b869d384f49.jpg)

### Daily check on all issues

1. Has it been >= 20 days since the issue was updated?
	- Yes
		- Continue to step 2
	- No
		- Take no action; exit the flow
2. Is there an open PR attached to this issue (using ZenHub's "connected issue" feature)?
	- Yes
		- Take no action; exit the flow
	- No
		- Continue to step 3
3. Is the issue labeled with `not stale`?
	- Yes
		- Take no action; exit the flow
	- No
		- Add the label `stale?`
		- Post a comment requesting additional info, asking the author to validate their bug against the latest versions of Gatsby, etc.

### Daily check on `stale?` issues

1. Has the issue been updated since the follow-up comment?
	- Yes
		- Remove the `stale?` label
		- Exit the flow
	- No
		- Continue to step 2
2. Has it been >= 10 days since the issue was updated?
	- Yes
		- Continue to step 3
	- No
		- Exit the flow
3. Is the issue labeled with `not stale`?
	- Yes
		- Exit the flow
	- No
		- Close the issue
		- Post a comment explaining why stale issues are closed and how to create a new issue later if necessary

**Comment by marisamorby** [comment]
@jlengstorf: Here's the initial flowchart for this process. We can review and I'll make any changes or updates before we solidify this flow. Thanks!

OSS Automation Flowchart for Stale Issues: https://whimsical.co/5bsueDnUNG2K7qQDZKYTGQ

**Comment by marisamorby** [comment]
Add Stales Issues workflow separate from the stale issues check.

**Comment by marisamorby** [comment]
This has been updated, and can be removed as a blocker.

**Comment by m-allanson** [comment]
I've posted the whimsical link to #6785, closing. Thanks!
