### ISSUE TITLE
Create decision flowchart for verifying bug reproductions

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#8416]
Excerpt from https://github.com/gatsbyjs/gatsby/issues/7583#issuecomment-420441954:

## How do we validate bug issues?

![img_20180911_140730](https://user-images.githubusercontent.com/163561/45388344-8a6b2180-b5cd-11e8-8f7b-fccad3723d00.jpg)

On all new issues:

1. Was the bug template used to create this issue?
	- Yes
		- Continue to step 2
	- No
		- Do nothing; exit the flow
2. Is a reproduction link provided in the "please post a link to a reproduction" section?
	- Yes
		- Continue to step 3
	- No
		- Post a comment requesting a reproduction
		- Add the label `status: needs reproduction`
		- Continue to step 3
3. Is environment info posted?
	- Yes
		- Add the label `type: bug`
	- No
		- Post a comment requesting envinfo and explaining how to get it
		- Add the label `status: needs more info`
		- Add the label `type: bug`

**Comment by marisamorby** [comment]
@jlengstorf: Here is the link to the flowchart for this https://whimsical.co/FWmLPZEZR9f5GBmoSoCkJz

**Comment by jlengstorf** [comment]
@marisamorby I don't have access to edit/comment on that. Can you add me, please?

**Comment by marisamorby** [comment]
@jlengstorf It should work now. Here's the link: https://whimsical.co/FWmLPZEZR9f5GBmoSoCkJz

**Comment by jlengstorf** [comment]
@marisamorby one piece of feedback posted. Overall this looks great!

@m-allanson This relates to #6783

**Comment by marisamorby** [comment]
Flowchart already exists, closing the issue.
