### ISSUE TITLE
Define workflow for matching labels to ZenHub status that can be automated via Peril

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#8417]
We use the [ZenHub browser extension](https://www.zenhub.com/extension) to manage issues, but we don't want to make that a requirement for all contributors.

This means finding a solution for organizing issues that isn't completely restricted to ZenHub.

We need to think this through, and it'll require input from all maintainers, but as a starting point, here's what I'm thinking will work:

The primary benefits of ZenHub are:

1. "Swim lanes" for issues in the board view 
2. Epics for grouping issues together

We can mimic this filtering via labels.

### Swim Lanes

Using ZenHub, we have a board view that splits issues into different columns for easy visual grouping.

<img width="1280" alt="screen shot 2018-09-21 at 2 25 17 pm" src="https://user-images.githubusercontent.com/163561/45906786-497fc380-bdaa-11e8-956d-abcea2f10442.png">

If we had corresponding labels for those swim lanes, it would be possible to create filtered views of issues that appear in each swim lane. These labels could follow a format like:

```
zh: <lane name>
```

This would put the labels at the bottom of the label list, avoiding visual clutter for maintainers, and would give us the ability to filter for e.g. `zh: backlog` to see only issues that have been moved to the backlog for active work.

### Epics

This would be messier, because it would require adding a new label for every epic. However, if we did it, we could do something like this:

```
zh epic: <epic #>
```

The bot would create this label whenever we add an issue to the epic, and would auto-add/remove it on issues that are grouped within the epic.

## Questions to Answer

1. Does this provide enough benefit to be worth the effort?
2. Would it make more sense to add epics and all their issues to a given milestone for native GitHub filtering?
	- For example, we might create a milestone for "2018 Q3" and add several epics and their issues to it. This shows what we've committed to complete in Q3, and makes it obvious what we've prioritized.

@gatsbyjs/inkteam can I get initial thoughts on this? I'm 100% sure that ZenHub makes our internal processes easier, but I'm not sure how much value that internal organization adds for anyone else.

**Comment by shannonbux** [comment]
How much work would it take? Any guesses?

I think the milestone idea is a great idea regardless of how we organize
labels; it could force us to prioritize epics more.

**Comment by amberleyromo** [comment]
I'm not convinced of the value add for contributors. (Question #1) If they're picking up issues, how important is it that they understand the full context (unless they are interested/motivated, and then they'd probably just look into ZenHub)? The point is for issues to be well-written and contained to the point where someone could pick it up and run with it.

I do agree with Shannon that organizing Epics into GitHub milestones could be helpful

**Comment by jlengstorf** [comment]
@amberleyromo yeah, I think that's a good point. Issues _should_ be standalone enough that the broader context should never be required.

@shannonbux I'd estimate the effort at medium/high.

That means this is probably high effort, low impact. Probably not worth it.

If anyone has ideas to the contrary, please post them! However, I think there's a good enough argument against this to close the issue.
