### ISSUE TITLE
Create list of filtered issue links to make triage and issue discovery easier

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#8418]
We need to make it easier for people to find issues that are relevant to them. Filtering in GitHub makes this possible, but it's a pain to have to set your filters every time you open the repo.

Let's make this easy by creating a page with shortcuts to the most common filters.

This list will evolve over time, but for now:

- Issues for beginners
- Issues that need first-touch review (e.g. untriaged issues)
- Issues that need core maintainer review
- Unanswered questions
- Bugs with confirmed reproductions that are ready for work
- Issues that are good candidates for community contributions
	- Good first issue
	- Maybe: split by effort level (e.g. small fixes, medium effort issues, or large, involved projects)
	- Maybe: split by the components they touch (e.g. Gatsby core, plugins, the website)

Many of these can be created now. Others would require labels, which would affect the triage process.

@kakadiadarpan @pieh @m-allanson @DSchau would love to get your input here.

**Comment by m-allanson** [comment]
Here's links to a lot of those categories:

- [Issues for beginners - filter on `good first issue`](https://github.com/gatsbyjs/gatsby/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)
- [Untriaged issues - filter on issues without any labels](https://github.com/gatsbyjs/gatsby/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+no%3Alabel+)
- [Issues that need core maintainer review - filter on `status: inkteam to review`](https://github.com/gatsbyjs/gatsby/labels/status%3A%20inkteam%20to%20review)
- [Unanswered questions - filter on `type: question or discussion` with no comments](https://github.com/gatsbyjs/gatsby/issues?q=is%3Aopen+comments%3A0+label%3A%22type%3A+question+or+discussion%22)
- [Bugs with confirmed repros - filter on `type: bug` and `status: confirmed`](https://github.com/gatsbyjs/gatsby/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22status%3A+confirmed%22+label%3A%22type%3A+bug%22+)
 
Assorted thoughts...

This is a good list! Where do you see these filters being published? I guess in the contributing docs and on the (upcoming) contributor dashboard? Or somewhere else?

Issues labelled `good first issue` tend to get picked up pretty quickly, which is great 👍 But often means there's not a lot of those issues up for grabs.

That's all the thoughts I have for now.

**Comment by jlengstorf** [comment]
@marisamorby We need to do contributing docs onboarding planning to figure out where this lives.

**Comment by thorn0** [comment]
The `status: confirmed` label has two conflicting descriptions:

1) In the [label list](https://github.com/gatsbyjs/gatsby/labels):

> Validated by the Gatsby Inkteam as an item that should be worked on

2) In '[How to label an issue](https://www.gatsbyjs.org/docs/how-to-label-an-issue/)':

> ### Choose a `status:` label (optional)
> Check through the `status:` labels (and their descriptions), if any apply to this issue add them as necessary.
> 
> Examples of applying `status:` labels might be:
> **[...]**
> * An issue describing a bug where there’s steps to reproduce the bug and you’ve run the code locally and seen the error yourself can be labelled `status: confirmed`

So is this label supposed to be added only by the Inkteam or by anyone from the Maintainers team? 

Which one of these two descriptions should be corrected?

**Comment by jlengstorf** [comment]
Oh, this is a good catch @thorn0! I would lean toward the "how to label an issue" description being the one we want to stick to (so anyone who confirms an issue can apply it), but I'll defer to @pieh @DSchau @m-allanson on this.

**Comment by pieh** [comment]
I think we should invite maintainers to apply `confirmed` label. Only restriction that I would like is that issue author shouldn't apply that label on his/her own issues (so the issue is confirmed by at least 2 people)
