### ISSUE TITLE
Write documentation explaining where to find/how to use the OSS process resources

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#8419]
All of this work will be for nothing if contributors don't have a clear path to find it.

@marisamorby is going to own deciding where these docs live and coming up with a strategy for making them easy to find for contributors.

**Comment by marisamorby** [comment]
I think we should talk about this on the OSS automation meeting this week to get some initial ideas set out.

**Comment by jlengstorf** [comment]
This is blocked until we know more about the final scope.
