### ISSUE TITLE
export gatsby page props typescript types

### ISSUE THREAD

**Issue by dontsave** [gatsbyjs/gatsby#8431]
It would be cool if Gatsby exported some more types to make working with page props more type safe. Ideally we could import the props that gatsby passes to page components. Something like:

```

import * as React from "react";
import {PageProps} from 'gatsby';

export class MyPage extends React.PureComponent<PageProps, {}> {
	render() {
		return (
			this.props.location
		);
	}
}



```

**Comment by eknowles** [comment]
this would be nice

**Comment by dontsave** [comment]
i agree this would be nice. someone should reopen this and/or add the types

**Comment by xiel** [comment]
this still does not exist right?

**Comment by HenryCharlesAnderson** [comment]
import { PageRendererProps } from 'gatsby'

**Comment by apollocoder** [comment]
Please re-open!

**Comment by cypcz** [comment]
I went through gatsby and reach router exported types and interfaces but there is none that would cover the real type of page props, which is: 

![image](https://user-images.githubusercontent.com/29678037/70372816-40621000-18e4-11ea-87d0-853031273ee4.png)
 
It would be cool to have it typed..

**Comment by saitodisse** [comment]
Try to use this type: `ReplaceComponentRendererArgs['props']`

**Comment by seaneking** [comment]
Agree that this would be v nice 👌
Can it be reopened and investigated?

**Comment by seaneking** [comment]
Oh, nevermind. Appears gatsby exports `PageProps` which covers it? Reclosing.

**Comment by dandv** [comment]
@seaneking: nice find, but is this documented somewhere? I don't see it at https://www.gatsbyjs.org/docs/location-data-from-props/ for example.

**Comment by seaneking** [comment]
AFAIK Gatsby’s typescript types aren’t documented anywhere? I just discovered it by playing around with VSCode’s intellisense importing
