### ISSUE TITLE
String interpolation in StaticQuery's query

### ISSUE THREAD

**Issue by janosh** [gatsbyjs/gatsby#8434]
## Summary

It would be cool if `StaticQuery` accepted functions as its `query` argument. That way you could use props passed to the component to fetch data specific to the component's call site. For instance, I might want a page title that grabs a different background image for every page its called on.

### Basic example

```js
import React from 'react'
import { StaticQuery, graphql } from 'gatsby'

import { Title, Background } from './styles'

const PageTitle = ({ children, file }) => (
  <Title>
    <Background fluid={file.img.fluid} />
    {children}
  </Title>
)

const query = path => graphql`
  {
   file(relativePath: {eq: "${path}/background.jpg"}) {
      img: childImageSharp {
        fluid {
          ...GatsbyImageSharpFixed_withWebp
        }
      }
    }
  }
`

export default props => (
  <StaticQuery
    query={query(props.path)}
    render={data => <PageTitle {...data} />}
  />
)
```

### Motivation

This would really take `StaticQuery` to the next level and make it much more versatile. Come to think of it, this might merit dropping the `Static` part from `StaticQuery`. 😄

**Comment by KyleAMathews** [comment]
The problem is that we don't know the props to the component at build time. That isn't known until runtime.

We are considering consolidating page queries & StaticQuery but for now, you'll need to use page queries for changing queries per page.

https://github.com/gatsbyjs/gatsby/issues/6596
