### ISSUE TITLE
[gatsby-source-wordpress] Each page has the same content

### ISSUE THREAD

**Issue by braco** [gatsbyjs/gatsby#8437]
## Description

For some reason my instance of Gatsby with Wordpress is producing pages that all have the same content, as if the first template compilation is being cached across all pages/slugs.

### Steps to reproduce

`npm run build` and `npm run develop` both produce this result

### Expected result

Each page should have the correct / different content

### Actual result

Every page has the same content. It always seems to be the first page that was rendered by gatsby-node.js.

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.8.0 - ~/.nvm/versions/node/v10.8.0/bin/node
    Yarn: 1.9.4 - ~/.nvm/versions/node/v10.8.0/bin/yarn
    npm: 6.2.0 - ~/.nvm/versions/node/v10.8.0/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 60.0.1
    Safari: 12.0

```
$ grep gatsby package.json
    "gatsby": "^2.0.1",
    "gatsby-link": "^2.0.1",
    "gatsby-plugin-catch-links": "^1.0.14",
    "gatsby-plugin-emotion": "^2.0.5",
    "gatsby-plugin-feed": "^1.3.15",
    "gatsby-plugin-google-analytics": "^1.0.31",
    "gatsby-plugin-manifest": "^1.0.12",
    "gatsby-plugin-netlify-cms": "^2.0.1",
    "gatsby-plugin-nprogress": "^1.0.9",
    "gatsby-plugin-offline": "^1.0.12",
    "gatsby-plugin-react-helmet": "^3.0.0",
    "gatsby-plugin-sharp": "^1.6.24",
    "gatsby-plugin-sitemap": "^1.2.9",
    "gatsby-plugin-twitter": "^1.0.14",
    "gatsby-remark-autolink-headers": "^1.4.11",
    "gatsby-remark-copy-linked-files": "^1.5.25",
    "gatsby-remark-images": "^1.5.36",
    "gatsby-remark-prismjs": "^2.0.5",
    "gatsby-remark-responsive-iframe": "^1.4.16",
    "gatsby-source-filesystem": "^1.5.11",
    "gatsby-source-wordpress": "3.x",
    "gatsby-transformer-remark": "^1.7.26",
```

As of now, `gatsby-node.js` is identical to the example in the docs.

Not sure what other debug info to send over, let me know if there's something I can do.

**Comment by braco** [comment]
Fixed by changing the query in the page template to use $id instead of $slug, which seems to have been a mistake by the gatsby wordpress starter.

```
export const pageQuery = graphql`
  query WordpressPage($id: String) {
    wordpressPage(id: { eq: $id }) {
      id
      wordpress_id
      slug
      title
      template
      content
    }
  }
```

**Comment by zvitez** [comment]
Thanks so much @braco. Hope you didn't waste too much time figuring this out. You definitely saved me some!
