### ISSUE TITLE
[1.0] gatsby-plugin-sass available

### ISSUE THREAD

**Issue by danielfarrell** [gatsbyjs/gatsby#845]
Not sure what the best way to share this was, but I packaged up some code to handle sass/scss in 1.0 released it:

https://github.com/danielfarrell/gatsby-plugin-sass

`npm install gatsby-plugin-sass`

If that helps you, have at it.  If you want to incorporate it into this repo, let me know.

**Comment by KyleAMathews** [comment]
Hey this is fantastic! Thanks for putting this together!

I'm not entirely sure what's the best way to differentiate between core and non-core plugins. There'll be 1000s of Gatsby plugins eventually, the vast majority of which won't belong in core (nor could we handle that quantity).

The basic heuristic I've been using is whether the plugin is a) easy to write/maintain and 30%+ of sites would use it b) is it necessary for an example site (example sites dog food the latest changes to core as well as their plugins so all plugins for example sites have to be in this repo) or c) the plugin is a critical for bootstrapping the community early on e.g. all the Markdown plugins I've written.

This Sass plugin does kinda feel like it falls under A. It'll be easy to maintain as the Webpack plugin does 95% of the work and it will be widely used. That being said, if you feel like you'll be committed to maintaining it going forward e.g. quickly tracking core changes, fixing bugs, answering support questions, etc. then I think it'd be fine keeping it outside core. But if not (and there'll actually be a number of [breaking changes to the webpack integration soon](https://github.com/gatsbyjs/gatsby/issues/796#issuecomment-294114007) feel free to PR it here as a package and share the maintenance load with others here).

**Comment by vishalniit** [comment]
@danielfarrell Thanks for Plugin, our team was looking for similar stuff. It would be great if you can provide sample implementation of your plugin in use at your documentation. Best Practice you aware of while using SaSS in gatsby world if it differs from usual react world.

**Comment by danielfarrell** [comment]
Merged into this repo
