### ISSUE TITLE
Creating PDF thumbnails

### ISSUE THREAD

**Issue by janosh** [gatsbyjs/gatsby#8456]
I'm trying to display a list of PDfs with thumbnail icons of their first page linking to the actual file. Should look somewhat like this:

![pdfs](https://user-images.githubusercontent.com/30958850/45924972-85329e80-bf0c-11e8-85a8-170374602275.jpg)

Could [`gatsby-transformer-screenshot`](https://www.gatsbyjs.org/packages/gatsby-transformer-screenshot/?=gatsby-transformer-screenshot) be extended/adapted to work with PDFs instead of URLs?

**Comment by janosh** [comment]
Not stale!

**Comment by actual-size** [comment]
Is there a reason this was closed?

**Comment by janosh** [comment]
@actual-size Lack of interest I guess.
