### ISSUE TITLE
[packaging] Don't include source tars

### ISSUE THREAD

**Issue by stefanprobst** [gatsbyjs/gatsby#8458]
## Description

Currently, every package includes source tars (`.tgz`), which themselves nest the source folder multiple times. This takes up quite a bit of space.

### Steps to reproduce

* `gatsby new testing`
* `cd testing`
* `ls node_modules/**/*.tgz`

### Expected result

No *.tgz files

### Actual result

```sh
node_modules/babel-plugin-remove-graphql-queries/babel-plugin-remove-graphql-queries-2.2.2.tgz
node_modules/babel-plugin-remove-graphql-queries/babel-plugin-remove-graphql-queries-2.3.0.tgz
node_modules/gatsby-link/gatsby-link-2.0.0.tgz
node_modules/gatsby-plugin-manifest/gatsby-plugin-manifest-2.0.2.tgz
node_modules/gatsby-plugin-offline/gatsby-plugin-offline-2.0.0-rc.9.tgz
node_modules/gatsby-plugin-offline/gatsby-plugin-offline-2.0.0.tgz
node_modules/gatsby-plugin-page-creator/gatsby-plugin-page-creator-2.0.0.tgz
node_modules/gatsby-plugin-react-helmet/gatsby-plugin-react-helmet-3.0.0.tgz
node_modules/gatsby-react-router-scroll/gatsby-react-router-scroll-2.0.0.tgz
node_modules/graphql-skip-limit/graphql-skip-limit-2.0.0.tgz
```

**Comment by stefanprobst** [comment]
If someone could point me in the right direction. Are we calling `npm pack` somewhere?

**Comment by KyleAMathews** [comment]
I can't reproduce. This sounds like an error with whatever you're using to install packages either NPM or Yarn. They do download a tgz but generally delete them after unpacking. Which is what happening on my machine and presumably most other machines.

We just run `npm publish` like normal to publish things so doesn't seem like there's anything to fix on our end. Please let us know if you discover differently!

**Comment by pieh** [comment]
I think this is valid - at least this one https://registry.npmjs.org/gatsby-plugin-page-creator/-/gatsby-plugin-page-creator-2.0.0.tgz for sure contains additional tarball inside tarball (taballception anyone?). I think this is result of our publishing problems - tarballs were created before publishing, publish errored out midway and tarballs stayed in package directories

**Comment by pieh** [comment]
I think we need to update `.npmignore` files to not pack tarballs.

> Are we calling `npm pack` somewhere?

Not directly, `lerna` is doing this for us, but yeah - it does use `npm pack`

**Comment by kakadiadarpan** [comment]
I'm able to see tgz file for many packages:
- gatsby-link
- gatsby-plugin-offline
- gatsby-plugin-page-creator
- gatsby-plugin-sharp
- gatsby-plugin-typography
- gatsby-react-router-scroll
- gatsby-source-filesystem
- gatsby-transformer-sharp
- gatsby-plugin-remove-trailing-slashes
- gatsby-plugin-catch-links
- gatsby-plugin-glamor
- gatsby-remark-copy-linked-files
- gatsby-remark-images
- gatsby-remark-katex
- gatsby-remark-prismjs
- gatsby-remark-smartypants
- gatsby-transformer-yaml

<img width="1042" alt="screen shot 2018-09-25 at 9 32 04 am" src="https://user-images.githubusercontent.com/10805593/45992333-e7270b80-c0a6-11e8-9fcd-6033e3ed4bfe.png">

**Comment by stefanprobst** [comment]
I also can consistently reproduce on two different machines with both npm and yarn.
