### ISSUE TITLE
encodeURI and filenames

### ISSUE THREAD

**Issue by millette** [gatsbyjs/gatsby#8461]
## Description

I was generating pages based on programming language names (c, c++, c#) and hit a problem encoding paths and/or file names.

I searched for other relevant issues (with the words encodeURI or encodeURIComponent) but found nothing current or relevant.

### Steps to reproduce

Using ```encodeURIComponent(primaryLanguage)``` in ```createPage()``` results in 404 in dev and prod.

## Temporary fix

Instead, I'm using this for now. It only handles ```#``` but it solves the problem.

```js
createPage({
      path: `/by/lng/${(primaryLanguage || 'unspecified')
        .toLowerCase()
        .replace('#', '-sharp')}/`
})
```

## Expected results

```encodeURIComponent()``` should be enough to fix troubling paths but it seems to fail on the file system side.

### Environment

Using gatsby 2.0.7.

**Comment by kakadiadarpan** [comment]
@millette Can you provide relevant environment information by running `gatsby info --clipboard`? Also, can you provide a reproduction repo for this? That would make it much simpler to diagnose this issue.

**Comment by millette** [comment]
In other words, can we have urls with special caracters in them (#, +, etc.) and what's the best way to deal with this in URLs and filenames.

Here's my gatsby info:
Note that I'm not using the global packages (I should uninstall both of those).

```
  System:
    OS: Linux 3.16 Debian GNU/Linux 8 (jessie) 8 (jessie)
    CPU: x64 Intel(R) Celeron(R) CPU  J1900  @ 1.99GHz
    Shell: 4.3.30 - /bin/bash
  Binaries:
    Node: 8.12.0 - ~/n/bin/node
    Yarn: 1.9.4 - /usr/bin/yarn
    npm: 6.4.1 - ~/n/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 62.0
  npmPackages:
    gatsby: ^2.0.8 => 2.0.8 
    gatsby-plugin-manifest: ^2.0.3 => 2.0.3 
    gatsby-plugin-offline: ^2.0.5 => 2.0.5 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-source-filesystem: ^2.0.1 => 2.0.1 
    gatsby-transformer-json: ^2.1.1 => 2.1.1 
  npmGlobalPackages:
    gatsby-cli: 2.0.0-beta.8
    gatsby: 0.12.47
```

**Comment by millette** [comment]
Here's my current example, dealing with programming language names (c#, c++):
https://millette.github.io/gpqc/by/lng/

For now, I'm replacing "#" with "-sharp" but it's obviously not a very generic solution for these cases.

Not sure if it's just a docs issue, to establish best practice, or if there's any code that would alleviate this.
