### ISSUE TITLE
Missing `--https` option for `gatsby serve`?

### ISSUE THREAD

**Issue by stephanschubert** [gatsbyjs/gatsby#8463]
Just wondered if there's a rationale behind having no `--https` option for `gatsby serve` analog to `gatsby develop`?

**Comment by kakadiadarpan** [comment]
@jazen `gatsby serve` is a wrapper over [`serve`](https://github.com/zeit/serve), it gives all the options that `serve` gives.

And in my opinion it makes sense not to provide `--https` option. As generally web application are hosted on a port like 3000 or 9000 or any other available port and then port `443` requests (where all https requests go) are forwarded to that port.

**Comment by wconnorwalsh** [comment]
@kakadiadarpan I don't believe `gatsby serve` is intended for actually publicly serving the site – it's for _locally_ serving it after it has been built (i.e., for previewing, or testing). Right @KyleAMathews?

If `--https` is a useful feature for `develop` (and I think it really is), then it is also a useful feature for `serve`.

This should be reopened.

**Comment by KyleAMathews** [comment]
It's a bit cumbersome to get a local https server setup and also not entirely necessary as most https-only browser features like service workers are active on localhost over http.

Perhaps a compromise would be documenting a good way to run a local https web server?

**Comment by Undistraction** [comment]
What about running end-to-end tests? I have tests that check that secure cookies are written. It would be really useful to be able build and serve locally to run tests against.

**Comment by CanRau** [comment]
I agree, I think it would be useful. Maybe along the note "..only intended for preview purposes and not for production.."
I reuse the same tab and address often when switching between `dev` and `serve` always forgetting to switch to `http` as well 🤦‍♂️

**Comment by lucavallin** [comment]
Why has this been closed?
We want to run cypress tests in the pipeline against the production build (because apparently the behaviour sometimes is different than development) and not being able to serve over https makes it impossible, we have some secure cookies that just won't work.
Do you need help implementing the feature maybe?

**Comment by Undistraction** [comment]
Not stale. Still important in regards to testing.

**Comment by blainekasten** [comment]
@Undistraction / @lucavallin - why do you need https to run the production mode locally for tests? `gatsby serve` still uses localhost which enables most ssl specific browser APIs. Just curious what situation prevents this from working out.

If this is something ya'll are going to want, would you be willing to contribute a change?

**Comment by cranberyxl** [comment]
Have a draft version of this here https://github.com/gatsbyjs/gatsby/pull/26110

**Comment by rubeonline** [comment]
Hey i´m also missing --https in gatsby serve. Any news here?

**Comment by cranberyxl** [comment]
#26110 is still open if someone wants to look into getting the tests to run

**Comment by ChrisSargent** [comment]
> @Undistraction / @lucavallin - why do you need https to run the production mode locally for tests? `gatsby serve` still uses localhost which enables most ssl specific browser APIs. Just curious what situation prevents this from working out.
> 
> If this is something ya'll are going to want, would you be willing to contribute a change?

Our situation is that our app uses an Auth provider that requires us not to use localhost in redirect urls etc. Can't run in dev mode because building and loading pages is too slow.
