### ISSUE TITLE
v2 Migration Guide and Gatsby Image should mention change to gatsby-image-wrapper

### ISSUE THREAD

**Issue by brandonkal** [gatsbyjs/gatsby#8469]
## Summary

The v2 Migration guide docs (and the gatsby-image page) should mention the change from a class of "gatsby-image-outer-wrapper" to "gatsby-image-wrapper" as this resulted in layout issues when upgrading my site to v2.

### Motivation
This would help speed up migration for those who use CSS on gatsby image wrappers.

**Comment by stefanprobst** [comment]
It actually [is in the migration guide](https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/#gatsby-images-outerwrapperclassname-was-removed), but apparently not in the TOC. Will have a look, thanks.

**Comment by brandonkal** [comment]
Oh that is interesting. I wasn't aware of that prop in Gatsby v1.
I was just using
```
.read-next-story .gatsby-image-wrapper {...}
```
in my wrapper class. Thanks.
