### ISSUE TITLE
yarn develop -o fails when not able to open a browser

### ISSUE THREAD

**Issue by lbogdan** [gatsbyjs/gatsby#8470]
## Description

Running `gatsby develop -o` on a machine without a web browser fails with
```
error UNHANDLED REJECTION
  Error: Exited with code 3
  - index.js:84 ChildProcess.cp.once.code
    [sandbox]/[opn]/index.js:84:13
  - child_process.js:925 maybeClose
    internal/child_process.js:925:16
  - child_process.js:346 Socket.stream.socket.on
    internal/child_process.js:346:11
```

Note: Ran into this while trying to run https://github.com/LeKoArts/gatsby-starter-minimal-blog in Codesandbox, because it defines the `dev` script as `gatsby develop -o`.

### Steps to reproduce

Run `gatsby develop -o` on a machine without a web browser.

### Expected result

`gatsby develop -o` ignores that there's no browser and continues working (and maybe shows a warning).

### Actual result

`gatsby develop -o` failes with above error.

### Environment

```
$ /sandbox/node_modules/.bin/gatsby info --clipboard

  System:
    OS: Linux 4.17 Debian GNU/Linux 8 (jessie) 8 (jessie)
    CPU: x64 Intel Xeon Processor (Skylake, IBRS)
    Shell: Unknown - /bin/sh
  Binaries:
    Node: 8.11.2 - /usr/local/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  npmPackages:
    gatsby: ^2.0.0 => 2.0.0
    gatsby-plugin-catch-links: ^2.0.2 => 2.0.2
    gatsby-plugin-lodash: ^3.0.1 => 3.0.1
    gatsby-plugin-manifest: ^2.0.2 => 2.0.2
    gatsby-plugin-netlify: ^2.0.0 => 2.0.0
    gatsby-plugin-offline: ^2.0.5 => 2.0.5
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.1
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.0
    gatsby-plugin-typography: ^2.2.0 => 2.2.0
    gatsby-remark-autolink-headers: ^2.0.5 => 2.0.5
    gatsby-remark-external-links: 0.0.4 => 0.0.4
    gatsby-remark-prismjs: ^3.0.0 => 3.0.0
    gatsby-source-filesystem: ^2.0.1 => 2.0.1
    gatsby-transformer-remark: ^2.1.1 => 2.1.1

Done in 1.90s.
```

**Comment by kakadiadarpan** [comment]
I'm not sure if it's possible to detect if a browser has been installed or not. Maybe wrap it in `try/catch`?

https://github.com/gatsbyjs/gatsby/blob/680618bcac5abbfee27c9924fc56d368acc20dfe/packages/gatsby/src/commands/develop.js#L427-L429

**Comment by lbogdan** [comment]
Yes, I think the solution should be to wrap `opn()` in `try...catch` and just ignore the error (or show a warning). I can make a PR for this later today.

**Comment by kakadiadarpan** [comment]
In my opinion showing a warning would be better.
