### ISSUE TITLE
gatsby develop calls all scripts in pages even if not the loaded page.

### ISSUE THREAD

**Issue by joshball** [gatsbyjs/gatsby#8472]
## Description

I posted this to SO: https://stackoverflow.com/questions/52467849/understanding-gatsby-2-pages-dependency-tree/52470090#52470090

Since the original question, I believe this is an issue with `gatsby develop` but not with `gatsby build`.
This is for (but not limited to) `gatsby 2.0.7`,

Given the following structure:

    /components/header.tsx  // console.log('header.tsx')
    /components/home.tsx  // console.log('home.tsx') consumes header.tsx
    /components/test.tsx  // console.log('test.tsx') consumes header.tsx
    
    /pages/404.tsx		// console.log('404.tsx') consumes home.tsx
    /pages/index.tsx  	// console.log('INDEX.tsx') consumes home.tsx
    /pages/test.tsx		// console.log('TEST.tsx') consumes test.tsx

Run `gatsby develop`
Open dev tools: Regardless of which page I load in the browser (`/` or `/test`)
The browser always logs all of the pages and components

    header.tsx
    home.tsx
    404.tsx
    INDEX.tsx
    test.tsx
    TEST.tsx

Run `gatsby build` and server the static directory, and load `/test` and you will get:

    header.tsx
    test.tsx
    TEST.tsx

### Steps to reproduce

1. Create a new V2 gatsby site (using the cli)
2. simply add console.log statements to each page and component. 
3. run `gatsby develop`
4. view in the dev tools console

### Expected result

If loading `/page`, only the logs from page and its dependencies should be seen.

### Actual result

All pages and dependent components logs are seen, regardless of 

### Environment
System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Yarn: 1.9.4 - C:\Program Files\nodejs\yarn.CMD
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.0.0 => 2.0.7
    gatsby-plugin-manifest: ^2.0.2 => 2.0.2
    gatsby-plugin-offline: ^2.0.5 => 2.0.5
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-plugin-typescript: ^2.0.0 => 2.0.0

**Comment by kakadiadarpan** [comment]
@joshball where did you place the comments in the files? Inside a component or outside it?

**Comment by joshball** [comment]
@kakadiadarpan I placed the console.log statements at the top of each file, before imports. But again, if I am loading the `/pages/test.tsx`, I should (imho) not be seeing `/pages/index.tsx` being sourced (which in the built version, is not the case).

**Comment by kakadiadarpan** [comment]
In development build, we don't have `code splitting` yet, while it is there in the production build. There's an issue which is already open for fixing the code splitting in the development build. Once that issue is fixed, this will also be fixed along with that.

Closing this in favor of #8342

**Comment by joshball** [comment]
OK, I will move to #8342 for further questions. Thanks.
