### ISSUE TITLE
v2 Regression: CSS Selector styles removed for children of styled-components

### ISSUE THREAD

**Issue by brandonkal** [gatsbyjs/gatsby#8477]
## Description

I'm experiencing layout issues because CSS selectors are not applied to child elements of a styled component acting as a wrapper. They do exist for gatsby develop but are forgotten by gatsby build.

EDIT: After a lot of insanity, it appears the issue is mostly caused by comments in the styled components CSS. These comments can be for anything, even classes that do not exist in the DOM. Removing the comments fixed the bug.

But I would prefer to keep my code documented. Comments in Styled components was not an issue with Gatsby v1.

I'm also experiencing other strange issues with styled components such as:

- injectGlobal not injecting selectors
- react-data props missing

### Steps to reproduce

Integrate this example component:

```
import React from 'react'
import styled from 'styled-components'

const CenterWrapper = styled.div`
  position: absolute;
  width: 100%;
  height: 550px;

  .vCard {
    width: 100%;
    max-width: 777px;
    color: red;
  }

  /* Any comment */
  .applePie {
    color: green;
  }

`

const MyCard = () => {
  return (
    <CenterWrapper>
      <section className="vCard">This should remain red</section>
    </CenterWrapper>
  )
}

export default MyCard
```
```
gatsby build && gatsby serve
```
### Expected result

No change in style for CSS selectors wrapped with styled-components.
In the example above, the text should remain red.

### Actual result

The style changes and parent styles remain:
```
  position: absolute;
  width: 100%;
  height: 550px;
```
The text switches back to black. Sometimes elements lose their styles after 200ms. Other times it seems fine but 30 seconds later the styles disappear.

### Environment

Before migration:
```
"@raygesualdo/gatsby-plugin-babel-styled-components": "^1.0.1"
"styled-components": "^3.4.4",
"gatsby-plugin-styled-components": "^2.0.11",
```

With Gatsby v2:

```

  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
    Shell: 4.4.23 - /usr/local/bin/bash
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 62.0.2
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.0.7 => 2.0.7 
    gatsby-image: ^2.0.8 => 2.0.8 
    gatsby-plugin-canonical-urls: ^2.0.5 => 2.0.5 
    gatsby-plugin-catch-links: ^2.0.2 => 2.0.2 
    gatsby-plugin-feed: ^2.0.5 => 2.0.5 
    gatsby-plugin-google-analytics: ^2.0.6 => 2.0.6 
    gatsby-plugin-manifest: ^2.0.2 => 2.0.2 
    gatsby-plugin-netlify: ^2.0.0 => 2.0.0 
    gatsby-plugin-nprogress: ^2.0.5 => 2.0.5 
    gatsby-plugin-offline: ^2.0.5 => 2.0.5 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.1 
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.0 
    gatsby-remark-autolink-headers: ^2.0.6 => 2.0.6 
    gatsby-remark-embed-video: ^1.4.0 => 1.4.0 
    gatsby-remark-images-contentful: ^2.0.0 => 2.0.0 
    gatsby-remark-prismjs: ^3.0.0 => 3.0.0 
    gatsby-remark-responsive-iframe: ^2.0.5 => 2.0.5 
    gatsby-source-contentful: ^2.0.1 => 2.0.1 
    gatsby-source-filesystem: ^2.0.1 => 2.0.1 
    gatsby-transformer-remark: ^2.1.3 => 2.1.3 
  npmGlobalPackages:
    gatsby-cli: 2.4.1
```

**Comment by brandonkal** [comment]
I'm also experiencing other strange issues with styled components such as:
- injectGlobal not injecting selectors
- inconsistant behaviour. E.g. the example above now seems to work. But other similar components do not see their styles applied.

**Comment by kakadiadarpan** [comment]
@brandonkal can you also provide the versions of `styled-components` and  `babel-plugin-styled-components`?

Also, can you can provide a reproduction repo for this? That would make it much simpler to diagnose this issue.

**Comment by brandonkal** [comment]
Oops, I thought it was included in the Gatsby info dump. The styled components version is 3.3.9. The Babel plugin is the latest version. I am swamped right now but the component example above should be reproducible. Thanks.

**Comment by kakadiadarpan** [comment]
@brandonkal with Gatsby v2, you'll need to use `styled-components` >4(it's in beta), as Gatsby uses babel 7 and styled-components 3 is on babel 6

**Comment by kakadiadarpan** [comment]
@brandonkal any updates on this issue?

**Comment by brandonkal** [comment]
Yes, I haven't had a chance to test with styled components v4 beta. It would be worth mentioning this requirement in the migration guide. Other than that, this can be closed
