### ISSUE TITLE
Cannot find module 'gatsby/graphql`

### ISSUE THREAD

**Issue by anderskitson** [gatsbyjs/gatsby#8478]
I am following the Transform Plugins part 6 of the tutorials on the Gatsby website. After I install `npm install --save gatsby-transformer-remark` and then add it to my gatsby-config.js file As seen below. Only when I add the `gatsby-transformer-remark` and I stop gatsby and run gatsby develop I get the following error `Error: Cannot find module 'gatsby/graphql'` However if I delete the line from my gatsby-config and run `gatsby develop` everything works again

```
module.exports = {
    siteMetadata: {
        title: `Panda Panda Panda`,
    },
    plugins: [
        {
            resolve: `gatsby-source-filesystem`,
            options: {
                name: `src`,
                path: `${__dirname}/src/`,
            },
        },
      `gatsby-transformer-remark`,
      `gatsby-plugin-glamor`,
      {
        resolve: `gatsby-plugin-typography`,
        options: {
          pathToConfigModule: `src/utils/typography`,
        },
      },
    ],
  };
```

**Comment by kakadiadarpan** [comment]
@anderskitson can you provide the relevant environment information by running `gatsby info --clipboard` in your project?

**Comment by anderskitson** [comment]
hmm, when I run that command Gatsby complains and gives me the command options, basically saying it does not recognize that command, I tried just `gatsby info` on its own and got the same response

**Comment by kakadiadarpan** [comment]
What is the `gatsby-cli` version that you are using currently? You can check that using `gatsby -v`.

**Comment by anderskitson** [comment]
1.1.50

**Comment by kakadiadarpan** [comment]
@anderskitson  can you try updating your `gatsby-cli` version to the latest?

**Comment by nicolasrouanne** [comment]
As it was a test project, I **got it working** restarting from _scratch_ with the most basic setup I could using `gatsby-image` and `gatsby-transformer-sharp`. 

I put everything to 2.x (including `gatsby` itself) and up and it works like a charm. 👌 
> `gatsby-source-prismic` is still in 1.x but somehow still works. I should update it too probably.

Here is the ouput of `gatsby info` once more
```
[...]
  npmPackages:
    gatsby: ^2.0.0 => 2.0.17
    gatsby-image: ^2.0.13 => 2.0.13
    gatsby-plugin-manifest: ^2.0.2 => 2.0.4
    gatsby-plugin-offline: ^2.0.5 => 2.0.5
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^2.0.6 => 2.0.6
    gatsby-source-prismic: ^1.2.0 => 1.2.0
    gatsby-transformer-sharp: ^2.1.3 => 2.1.3
  npmGlobalPackages:
    gatsby-cli: 2.4.2
```

**Comment by olavea** [comment]
This was useful. Thanks @mikelax 😺 . Thanks @nicolasrouanne 😺. Thanks @anderskitson 😺
