### ISSUE TITLE
Links to static remain unprefixed even with --prefix-paths flag enabled (gatsby-image?)

### ISSUE THREAD

**Issue by NathanLawrence** [gatsbyjs/gatsby#8479]
## Description

Discovered this one the hard way tonight - it looks like `pathPrefix` is not honored for links to files in the `static` directory as of v2.0.6. 

I'm happy to work on a fix to this myself, but contributing an issue seems like a good place to start.

### Steps to reproduce

1. New project.
2. In this case, I was using gatsby-image to send things to that directory
3. Add `pathPrefix` to `gatsby-config.json`
4. Build with `--prefix-paths` flag enabled.

### Expected result

Paths to static directory should be prefixed.

### Actual result

There are not. Instead, you get 404 errors unless you add static at the unprefixed destination as well.

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.10.0 - ~/.nvm/versions/node/v10.10.0/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v10.10.0/bin/npm
  Browsers:
    Chrome: 70.0.3538.22
    Firefox: 60.0.2
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.6 => 2.0.6 
    gatsby-image: ^2.0.5 => 2.0.5 
    gatsby-link: ^2.0.1 => 2.0.1 
    gatsby-plugin-feed: ^2.0.5 => 2.0.5 
    gatsby-plugin-google-analytics: ^2.0.6 => 2.0.6 
    gatsby-plugin-layout: ^1.0.1 => 1.0.1 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-sass: ^2.0.1 => 2.0.1 
    gatsby-plugin-sharp: ^2.0.5 => 2.0.5 
    gatsby-remark-images: ^2.0.1 => 2.0.1 
    gatsby-source-filesystem: ^2.0.1 => 2.0.1 
    gatsby-transformer-remark: ^2.1.3 => 2.1.3 
    gatsby-transformer-sharp: ^2.1.1 => 2.1.1 
  npmGlobalPackages:
    gatsby-cli: 2.4.1
```

**Comment by kakadiadarpan** [comment]
@NathanLawrence can you provide a reproduction repo for this? That would make it much simpler to diagnose this issue.

**Comment by NathanLawrence** [comment]
It's unclear why, but it looks like 2.0.11 or 2.0.12 may have fixed this.

**Comment by jonnybot0** [comment]
I'm still having this issue on 2.0.89... lemme see if I can scare up a quick repro repo.

**Comment by jonnybot0** [comment]
Here's my reproduction: https://github.com/jonnybot0/gatsby-static-image-bug-demo
@NathanLawrence @kakadiadarpan - should I open a new issue?

**Comment by ajkasliwal** [comment]
I am also facing this issue on gatsby v2.3.5 
Can someone provide a fix for it?

**Comment by jonnybot0** [comment]
I think we're going to need to open a new issue to get attention on this.

**Comment by jonnybot0** [comment]
See https://github.com/gatsbyjs/gatsby/issues/14067

**Comment by rochabianca** [comment]
same issue on gatsby v2.13.82, it's already driving me crazy

**Comment by 8ctopotamus** [comment]
Same issue here! Any suggestions?

**Comment by zteric** [comment]
Same Issue here.

**Comment by zteric** [comment]
For those who are facing the same issues:
In my case, I am following the official guideline to put all my static files inside static folder so I can easily set the absolute path to use them.And this is working properly on development environment.
```
<LogoImg src={'/images/logo.png'} alt="Logo"/>
```
But the thing is, when it comes to production, we need to setup the prefix for the whole application, then this kind of paths are not working because it still trying to look for files from the root.

But this is not a Gatsby issue actually, and you have few options to solve it.
1) use import or require to access static files.
2) use relative path if your project is a single page application.
3) put all your static files inside one folder under static folder and setup proxy(nginx) for this folder.
```
http://localhost:8000/assets/ => http://localhost:8000/yourPrefix/assets/
```
4) use a global pathPrefix from a json file.
```
//src/static/settings.json
{ "pathPrefix": "/sitbizportalreskin" }

//gatsby-config.js
let settings = require(`${__dirname}/static/settings.json`);
module.exports = {
  pathPrefix: settings.pathPrefix
}

//helpers.js
import settings from 'static/settings.json';
export const SYSTEM_PATH_PREFIX = isDevelopment() ? '' : settings.pathPrefix;

//Logo.js
import { SYSTEM_PATH_PREFIX } from '@/utils/helpers';
<LogoImg src={SYSTEM_PATH_PREFIX + '/images/logo.png'} alt="Singtel Logo"/>
```

**Comment by eralpkaraduman** [comment]
Based on @zteric 's solution
I made a slightly simpler single file utility.

This requires `pathPrefix: '/theprefix'` to be set in `gatsby-config.js`

```es6
// src/getPrefixedPath.js

import path from "path"
import config from "../gatsby-config"
const { pathPrefix } = config

const activeEnv =
  process.env.GATSBY_ACTIVE_ENV || process.env.NODE_ENV || "development"
const isDevelopment = activeEnv === "development"

const getPrefixedPath = url => {
  return isDevelopment ? url : path.join(pathPrefix, url)
}
export default getPrefixedPath
```
usage;

```es6
// at any component js

import getPrefixedPath from "../../getPrefixedPath"
const modelUrl = getPrefixedPath("/models/skull/scene.gltf")

// in development mode 
// modelUrl = /models/skull/scene.gltf

// in deployed bundle 
// modelUrl = /thePrefix/models/skull/scene.gltf

```

**Comment by brootle** [comment]
run into same issue with urls to images located in static folder in the root of the project after deploying to gh-pages
