### ISSUE TITLE
Add to tutorial + recipes + docs page about building sites with "unstructured data"

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#8482]
A persistent criticism of Gatsby is that you _have_ to use source plugins + GraphQL to build sites e.g. https://twitter.com/thekitze/status/1043532445742784515

The criticism is that this can complicate things unnecessarily for smaller sites.

The criticism is 100% correct! But it's also incorrect as you can write the exact same code in the above tweet using the node `createPages` API.

We should make this more clear to give people trying out Gatsby and easier onboarding to using the product.

We should add a brief section to the tutorial about building a small site from data queried from a simple REST api e.g. https://jsonplaceholder.typicode.com/

Also a docs page + prominent mention in the recipes page.

We should also mention the tradeoffs to this approach e.g. no gatsby-image or other transforms + more difficult time w/ medium+ complex sites, etc.

/cc @shannonbux @amberleyromo  

Amberley:
- [x] initial stub (thanks Shannon!)
- [ ] blog post (PR: #9188)
- [ ] update docs page (drawing from blog content)
- [ ] add prominent mention in recipes page

**Comment by amberleyromo** [comment]
@shannonbux weirdly it closed it. Reopening.

**Comment by shannonbux** [comment]
huh, that's funny! I guess I said in a comment that my PR "partially closes
[insert issue #]," so I won't do that again lol

**Comment by fk** [comment]
> I guess I said in a comment that my PR "partially closes [insert issue #]"

Yep, that was it (see https://help.github.com/articles/closing-issues-using-keywords/).

If you want to reference an issue from a pull request or commit, just referencing the issue number there should result in a reference showing up on GitHub.
For example I'm mentioning issue 7754 in [this PR](https://github.com/gatsbyjs/gatsby/pull/8411) and also in a [commit message](https://github.com/gatsbyjs/gatsby/pull/8411/commits/be8c4914f65ea600a5c70a39a4336f03523a9c9c), and they both show up in the [issue](https://github.com/gatsbyjs/gatsby/issues/7754):

![image](https://user-images.githubusercontent.com/21834/46015336-582fe880-c0d2-11e8-85f0-c62f0fefc058.png)

**Comment by amberleyromo** [comment]
I tend to pattern all my commit messages prefixed with an issue number, so it 1) does what @fk was mentioning^ and 2) easily tracked later

**Comment by shannonbux** [comment]
ah nice! I love learning best practices! Thanks @fk and @amberleyromo!

**Comment by amberleyromo** [comment]
Closed in #9188 and #9307
