### ISSUE TITLE
Community: Remove filters

### ISSUE THREAD

**Issue by amberleyromo** [gatsbyjs/gatsby#8484]
- [x] remove the filters at the top of the landing page
- [ ] add a "back to all Creators" button to the detail pages

@fk:
![image](https://user-images.githubusercontent.com/3461087/45935584-754da580-bf72-11e8-99a3-8fb3e988e9a0.png)

**Comment by berraknil** [comment]
@amberleyromo @fk 

May I ask what led to the decision to remove the filters?
