### ISSUE TITLE
Gatsby vs. HTML pages (header/footer/etc. split with PHP)

### ISSUE THREAD

**Issue by stoberov** [gatsbyjs/gatsby#8492]
Gatsby looks fantastic and I am looking for a side-project to give it a try. As such, I found myself surprisingly confused as to whether the below scenario would be **a good fit, or an overkill**, for Gatsby. Would you please share your thoughts?

I need to create a straightforward static web-site for a local business. 
- the "design" comes from a purchased HTML template, nothing fancy. 
- the "content" is predicted to be about 20 simple pages (like About, Services, etc.) , with a few having submit forms (Contact) - but nothing dynamic like blog posts. 
- the business may at some point decide to add new simple pages, or edit sentences on existing pages - the developer (me) should ideally not be needed for these simple tasks. 

I don't have experience with PHP per se, but I'm thinking that the most suitable (and traditional) approach would be to split the HTML template into php sections (header.php, footer.php, etc.) and then proceed to create the individual pages. The business owner can then makes simple changes himself (in Notepad), or copy an existing page + rename the file + change the content (to get a new page).

As a developer, I'm super excited about all the nice features that come with Gatsby. 
Practically speaking, however, I wonder if those features (such as pre-fetching pages) will really bring noticeable improvements for the business owner (e.g. loading the page in 500ms, instead of 100ms). In addition, I am also worried the business owner would find it very difficult to make changes, let alone run builds himself.

Given the above, would you recommend Gatsby for such a project?

**Comment by mikelax** [comment]
Hi @stoberov , I think that gatsby could be a great framework to use on your upcoming site. 
I would first suggest that you walk through the [current tutorial](https://www.gatsbyjs.org/tutorial/) as it will give you a good introduction to the major concepts of gatsby, and get you up and running with a (very simple) example site. 

As for the content, there are a number of ways to make that process easy to mange. You can have the content within the code itself, for example using [markdown files](https://www.gatsbyjs.org/packages/gatsby-transformer-remark/?=markdown). Given your third requirements, a [CMS](https://www.gatsbyjs.org/docs/headless-cms/) would make more sense so business owners can update the content. There are [several examples](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-contentful) that already exist that you can review and start with.
