### ISSUE TITLE
Unable to use array of paths with gatsby-remark-images and gatsby-plugin-netlify-cms-paths

### ISSUE THREAD

**Issue by tbaustin** [gatsbyjs/gatsby#8498]
Everything is hooked up correctly so I can do this in my markdown files:

```
image: /uploads/image.png
```

And then in my `graphql` query I can query the image like so: 

```
image {
 childImageSharp {
  sizes(maxWidth: 1000, quality: 100) { 
   ...GatsbyImageSharpSizes
  } 
 }
}
```

This all above works just fine, but when I try to do multiple paths like in an array it does not work.

```
images: 
 - /uploads/image1.png
 - /uploads/image2.png
```

I just get the strings and no paths returned. Is this not possible or am I doing this incorrectly ?

**Comment by graysonhicks** [comment]
Could you share the repo so it can be reproduced and debugged?

**Comment by oorestisime** [comment]
Hi,

i have some md templates with something similar, here is my graphql query
```
photos {
          childImageSharp{
            fluid(maxWidth: 1200, quality: 100) {
              ...GatsbyImageSharpFluid
            }
          }
        },
```
and in .md

```
photos: ['one.png', 'second.jpg']
```

This works for me so it should be working for you as well.

**Comment by graysonhicks** [comment]
I noticed that the two examples are different in how they are defining the array of images (one with bullets, one in brackets with commas).  Also in @tbaustin example, when you change the markdown field to `images` are you also changing the query to `images`?  I noticed the query still says `image`.

**Comment by tbaustin** [comment]
@graysonhicks Yes I am changing the query it just returns the strings. I will try the brackets and see if that works!

**Comment by tbaustin** [comment]
Here is the repo I am working from: https://github.com/escaladesports/rocketbroadheads.com/tree/gatsby

**Comment by tbaustin** [comment]
I couldn't get the brackets to work. I am still just getting the strings back:
<img width="988" alt="screen shot 2018-09-25 at 10 55 46 am" src="https://user-images.githubusercontent.com/14001400/46026702-a41e6580-c0b1-11e8-8a2f-7122124992d4.png">

**Comment by tbaustin** [comment]
> Hi,
> 
> i have some md templates with something similar, here is my graphql query
> 
> ```
> photos {
>           childImageSharp{
>             fluid(maxWidth: 1200, quality: 100) {
>               ...GatsbyImageSharpFluid
>             }
>           }
>         },
> ```
> and in .md
> 
> ```
> photos: ['one.png', 'second.jpg']
> ```
> This works for me so it should be working for you as well.

@oorestisime 
Do you have a repo of this? So I can compare?

**Comment by oorestisime** [comment]
@tbaustin here it is https://github.com/oorestisime/oasome it is a mess right now. i change many things constantly.
but i guess you could fire up develop and query in the graphql server

```
{
  allMarkdownRemark {
    edges {
      node {
        frontmatter {
           photos {
          childImageSharp{
            fluid(maxWidth: 1200, quality: 100) {
              src
              srcSet
            }
          }
        },
        }
      }
    }
  }
}
```

**Comment by tbaustin** [comment]
I was just going to look how you set up your `gatsby-config` , make sure mine is set up correctly!

**Comment by oorestisime** [comment]
The link to your repo doesnt work so i can't have a look for helping :/

**Comment by tbaustin** [comment]
Let me repush up what I have. You should just have to `yarn` and then `yarn dev`. Give it a couple of min so I can push what I have up.

**Comment by tbaustin** [comment]
@oorestisime I'm not really sure what I'm doing different lol. If you want to just look at the repo and look at my `gatsby-config` and then the markdown products under `images` property and see if that all looks correct to you?

**Comment by oorestisime** [comment]
Sure but you need to give me a link ;)

**Comment by tbaustin** [comment]
https://github.com/escaladesports/rocketbroadheads.com/tree/gatsby
sorry about that

**Comment by oorestisime** [comment]
404 :/ probably a private repo

**Comment by tbaustin** [comment]
You're right. Here is a different repo same code: https://github.com/tbaustin/test-images-rocket/tree/gatsby

**Comment by oorestisime** [comment]
i played around but couldn't find anything weird on the images .

**Comment by tbaustin** [comment]
Yeah that is why I'm having a hard time figuring out what's wrong haha. I can't really find anything obvious that I'm doing wrong.

**Comment by tbaustin** [comment]
@oorestisime  I found out that I am using `gatsby-plugin-netlify-cms-paths` and you are not so this could be affecting something with arrays? It works fine on strings however.

**Comment by tbaustin** [comment]
This was related too https://github.com/escaladesports/gatsby-plugin-netlify-cms-paths/issues/3
and not gatsby. Going to close this.
