### ISSUE TITLE
CLI Utils for Gatsby devs/admins?

### ISSUE THREAD

**Issue by mchandleraz** [gatsbyjs/gatsby#850]
I've been using Gatsby to build out my new blog and one of the first things I felt was missing was an easy way to create a new post. I created [gatsby-utils](https://github.com/mchandleraz/gatsby-utils) to address this, but I realized this might be something worth rolling into the gatsby cli itself. I also found [gatsby-dev-cli](https://www.npmjs.com/package/gatsby-dev-cli) but couldn't find a repo or anything for it.

Any thoughts?

**Comment by KyleAMathews** [comment]
I think CLI tools to generate posts (markdown files I'm assuming you mean) make a ton of sense. I just wrote a little script for my Gatsby journal (closed source sorry 😛) which asks me what the title of the post is and then creates the file with yaml frontmatter, a sluggified pathname, etc.

One problem with having a universal tool like what you're suggesting is that it's not... universal. There are lots of potential filename schemes plus also Gatsby can and is used for all sorts of things other than simple markdown blogs.

One potential future that makes sense is if 1.0 plugins/themes could add commands to the CLI. Then a blog markdown theme with a set directory/file structure, etc. could add a command for creating new markdown files within the constraints they've setup.

Thoughts?

**Comment by fabien0102** [comment]
You can use [plop](https://github.com/amwmedia/plop), it's really quick/easy to use ;)

Example => https://github.com/fabien0102/gatsby-starter/commit/e122fb201c0129e719d378cd19107240c5aa0846 (I will add a blog post generator when my starter will have blog post 😄 )

So I got same opinion as @KyleAMathews, it's not really universal and prefer to have my generators into my source code (so you can have very personnalize generator in function of yours needs)

**Comment by Helw150** [comment]
@mchandleraz I just use a simple little python script, like @KyleAMathews said the file structure isn't universal, but this should make it simple enough to modify into your own.

https://gist.github.com/Helw150/0a2bfb6eba288e568f07bb722e7e3177

**Comment by mchandleraz** [comment]
Awesome input, guys! I had considered the fact that it wouldn't be universal, and my gatsby-utils project actually looks for a .gatsby file in the working directory. Currently, it's just used for configuring the path where you want your markdown files generated. I noticed that my projet has `.gatsby-context.js` file which is actually what got me thinking about having this part of the actual cli.

One way to make this universal would be to allow the user to define their own frontmatter generator but at that point it feels like I'm just making a more narrowly focused plop from my quick glance at their repo.

I may continue working on my utils project, depending on what I learn about plop. If my project ends up being a universal way to create posts (or anything else valuable) from the cli I'll update this issue.

**Comment by jbolda** [comment]
This was also mentioned in #263. Linking these together.
