### ISSUE TITLE
How do I reset/change state from location.state?

### ISSUE THREAD

**Issue by ivorpad** [gatsbyjs/gatsby#8511]
I have this Link component

```javascript
<Link to={`/work/${node.slug}`} state={ {isInModal: true} } >
  {node.title.title}
</Link>
```

And I have access to this state through `this.props.location.state` but I want to reset the state after opening the modal, so I have this `react-modal` method:

```javascript
afterOpenModal = () => {
  //navigate(this.props.location.pathname, { state: { isInModal: false }})
}
```

I tried using Gatsby's `navigate()` but I don't think this is the intended usage and of course it doesn't work.

>You can also pass state to pages when you navigate e.g. `navigate("/a-path/", { state: { pleasant: "reasonably" }}` — https://www.gatsbyjs.org/docs/gatsby-link/

It was working with `push()` but I get this notice in v2: `push() method is now deprecated and will be removed in Gatsby v3. Please use "navigate" instead.`:

```javascript
push({
  ...this.props.location,
  state: {}
})
```

Any ideas?

**Comment by mikelax** [comment]
This sounds related to #5937, which in that case happened to be an implementation error. 
Are you using the most recent version of v2, currently 2.0.7?

**Comment by graysonhicks** [comment]
Do you have a repo so it can be reproduced and debugged?

**Comment by ivorpad** [comment]
@mikelax Yes, v2.0.7

@graysonhicks Sure Grayson, here's my `modal.js` file https://github.com/ivorpad/ivorpad_com/blob/master/src/components/modal.js#L29

I'm using Contentful, let me know if you need a quick Contentful demo to debug.

**Comment by mikelax** [comment]
I haven’t used that Modal component before, but after reviewing the readme I think you may want to use use the function “onRequestClose” in the Modal. In this function you can call the “navigate” function to get back to the “main page”. I don’t even think you would need to worry about resetting state as it would be a fresh render.

**Comment by ivorpad** [comment]
@mikelax Thanks Mike,

I need to reset the state `onAfterOpen` because I'm trying to replicate Instagram's functionality, that is, open the modal `onClick` and if the page is refreshed or opened from a URL then a single page is displayed.

**Comment by ivorpad** [comment]
The issue was solved with a bit of logic similar to [post-page.js#L14](https://github.com/gatsbyjs/gatsby/blob/master/examples/gatsbygram/src/templates/post-page.js#L14)

**Comment by dbismut** [comment]
I'm sorry if I'm missing something here and commenting on a closed issue, but the logic with a Modal on top of `<PageRenderer location={url} />` component is just a hack right? As you have to store the state of the `url` page so that it stays the same between different mounts. Let's say that you have infinite loading with incremental ajax requests I don't think that would work (yes I've looked at the Gatsbygram example).

**Comment by trickydisco78** [comment]
I've tried the approach from the gatsby gram example by adding
gatsby-browser
```
export const onInitialClientRender = () => {
  window.___GATSBYGRAM_INITIAL_RENDER_COMPLETE = true
}
`
```

```
 let isDirectURL = false
 

  if (typeof window !== `undefined` && window.___GATSBYGRAM_INITIAL_RENDER_COMPLETE) {
    isDirectURL = true
   
  }
```\

I want to detect if a user has goner directly to a page. In which case load from a URL. If not get data thats been passed in by state in props.location.state
