### ISSUE TITLE
Handle github token

### ISSUE THREAD

**Issue by amberleyromo** [gatsbyjs/gatsby#8517]
Blocks #7730.

**Comment by DSchau** [comment]
@amberleyromo is this basically sourcing/passing environment variables from the Publish container or something different? If it is... I ran into this the last time I used Publish, so this would be great to get fixed!

**Comment by amberleyromo** [comment]
@DSchau yeah, we're needing to pass an env variable for .org builds-- i'm not familiar with our deploy process, so yep, just need some help on it from Andrew.

**Comment by amberleyromo** [comment]
Handling afk with @thebigredgeek
