### ISSUE TITLE
[v2][IE11] Gatsby develop doesn't work properly in IE11.

### ISSUE THREAD

**Issue by rtm619** [gatsbyjs/gatsby#8522]
## Description

Gatsby develop doesn't work properly in IE 11. I tried to include polyfills, but its throwing errors like "Promise is undefined", "Objects are not supported as react children", etc. I have added the .babelrc configuration from gatsby docs.

### Steps to reproduce

https://github.com/rtm619/gatsby-IE-demo

Please clone the above repo and check in IE11.

### Expected result

Gatsby develop should work in IE11.

### Actual result

Gatsby develop throws an error.

**Comment by rtm619** [comment]
@kakadiadarpan Tried it, doesn't work.

**Comment by sarahannnicholson** [comment]
@rtm619 is it similar to this issue? https://github.com/gatsbyjs/gatsby/issues/7003 

I believe its being worked on by the Gatsby team

**Comment by rtm619** [comment]
@sarahannnicholson  Yeah, same issue. I added Babel Polyfill in gatsby-browser and changed preset-env's builtIns to "entry" and then, IE 11 works in develop. But in my actual project, I get the same "promise is undefined" or Expected ":" or other errors in IE11 after gatsby build. I'll close this one.

**Comment by rtm619** [comment]
@KyleAMathews Based on the comments of original issue #7003 , `--no-uglify` resolves the IE11 build issue. Can you take a look at it once?

**Comment by lfurzewaddock** [comment]
This resolved my production issues **(not development)** for IE11: https://github.com/gatsbyjs/gatsby/issues/7003#issuecomment-426739031

**Comment by abumalick** [comment]
@rtm619  I think this issue was fixed for you with https://github.com/gatsbyjs/gatsby/issues/7003#issuecomment-430218645 right ?

**Comment by rtm619** [comment]
@abumalick Yes. i'll close it now

**Comment by AhmadJafari2019** [comment]
@rtm619 hey man i am now facing with that issue. Could tell how did you solve your issue?. The Gatsby project in IE11 rendered as a blank page. May you help to come up with it. Thanks.
