### ISSUE TITLE
Some component doesn't render properly in prod build.

### ISSUE THREAD

**Issue by kossel** [gatsbyjs/gatsby#8531]
I'm using the [react-custom-scrollbar](https://github.com/malte-wessel/react-custom-scrollbars) inside of Gatsby.js. in development mode it works fine, however when it's bundler for prod, it doesn't render properly.

In prod mode, looks like the component cannot get the proper scrollHeight and width, but whenever I click any thing, it will work as expected after that, any idea what can I do to either fix or force a render?

you can see it in this demo side

this is a demo site [demo](https://kossel.github.io/)

I'm using Gatsby 2 beta

**Comment by kakadiadarpan** [comment]
@kossel can you try upgrading gatsby and dependencies to their latest stable versions? We released version 2 recently, that might solve the issue for you.

If upgrading doesn't solve your problem, can you provide a screen recording of the issue you are facing? Also, can you provide relevant environment information by running `gatsby info --clipboard`?

**Comment by kossel** [comment]
Sorry if I missed, where I can find instruction to upgrade to v2 from beta? If I use the official blog starter does that mean I have to manually diff from the repo?

**Comment by kakadiadarpan** [comment]
You can just run `yarn upgrade-interactive` and you'll be able to update the packages to the latest stable versions. Let me know if you need more help.

**Comment by kakadiadarpan** [comment]
Thanks for the update @kossel

**Comment by kossel** [comment]
Sorry, can I reopen this issue, I just tested again, actually it's not working :(  you can see [source branch](https://github.com/kossel/kossel.github.io/tree/source) for the source. 

demo site [kossel.github.io](kossel.github.io)

**Comment by kakadiadarpan** [comment]
Sure @kossel

**Comment by gradam** [comment]
@kossel I am facing the same issue. Did you find a way to fix it?

**Comment by kossel** [comment]
@gradam no... I tried to update still not working, I may revert to just use native scroll bar...
