### ISSUE TITLE
Media Query not working!

### ISSUE THREAD

**Issue by emman24** [gatsbyjs/gatsby#8540]
Good day I have problem using media query on my gatsby project its not working on the actual device i  put it on my main.scss when i tested on my chrome seems working but need to refresh couple times and when i use Responsinator its seems broken see picture below

Chrome Results :
![3](https://user-images.githubusercontent.com/25625894/46047806-5d456580-c0db-11e8-9df5-bbbef8af9382.PNG)

[responsinator](http://www.responsinator.com/?url=indigomelody.netlify.com%2F) Results: 
![1](https://user-images.githubusercontent.com/25625894/46047825-6fbf9f00-c0db-11e8-90bf-67b703171427.PNG)

I just made this on my .scss file and put it some styles on it
![capture](https://user-images.githubusercontent.com/25625894/46047855-91b92180-c0db-11e8-9c8e-3d6038641491.PNG)

Environment
 System:
    OS: Windows 7
    CPU: x64 AMD A6-5400K APU with Radeon(tm) HD Graphics
  Binaries:
    Yarn: 1.6.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.2.0 - C:\Program Files\nodejs\npm.CMD

npmPackages:
gatsby": "^1.9.277"
gatsby-plugin-sass": "^1.0.26",

**Comment by coreyward** [comment]
What leads you to believe this is Gatsby related?

**Comment by emman24** [comment]
Need help @coreyward

**Comment by kakadiadarpan** [comment]
@emman24 can you provide a reproduction repo for this?

**Comment by emman24** [comment]
https://github.com/emman24/gatsbyprojects  hope you can help 
@kakadiadarpan
