### ISSUE TITLE
Gatsby websites with available source code?

### ISSUE THREAD

**Issue by voordev** [gatsbyjs/gatsby#8541]
Is there a way to Gatsby showcase, add filter to show sites that are opensourced with repo, github icon
I still find it a bit hard to get started with Gatsby and learn how to implement stuff like navigation components.

**Comment by kakadiadarpan** [comment]
@voordev you can head to [Tutorial](https://www.gatsbyjs.org/tutorial/) section to learn more about Gatsby. If you want to see some example sites built with Gatsby, you can go to [examples](https://github.com/gatsbyjs/gatsby/tree/master/examples) folder in our repository showing the usage of different plugins of Gatsby.

(Feel free to reopen the issue if you need more help 🙂)

**Comment by kakadiadarpan** [comment]
@voordev You can also go to [`www`](https://github.com/gatsbyjs/gatsby/tree/master/www) folder to check out the source code of Gatsby website.
