### ISSUE TITLE
[v2] [develop] Directly visiting /dev-404-page/ fails and shows console errors

### ISSUE THREAD

**Issue by davidbailey00** [gatsbyjs/gatsby#8549]
## Description

When using `gatsby develop`, trying to directly visit `/dev-404-page/` fails.

### Steps to reproduce

1. Create a project
2. Run `gatsby develop`
3. Visit http://localhost:8000/dev-404-page/

### Expected result

The page should appear as normal

### Actual result

Console errors appear due to missing props, since the page is loaded directly rather than via 404 handling

![image](https://user-images.githubusercontent.com/4248177/46068848-03dc4580-c172-11e8-8004-1b679ade0da3.png)
![image](https://user-images.githubusercontent.com/4248177/46068840-ff179180-c171-11e8-8e63-00339062c63d.png)

### Environment

    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      CPU: x64 Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.10.0 - /home/linuxbrew/.linuxbrew/bin/node
      Yarn: 1.9.4 - /home/linuxbrew/.linuxbrew/bin/yarn
      npm: 6.4.1 - /home/linuxbrew/.linuxbrew/bin/npm
    Browsers:
      Chrome: 69.0.3497.100
      Firefox: 62.0

**Comment by pieh** [comment]
If we want this behaviour (which I'm not sure if really critical) we would need to change RouteHandler in `root.js` to test against same `dev-404-page` regex

**Comment by davidbailey00** [comment]
Yeah this definitely isn't something essential to fix, just a problem I noticed while adding the "preview custom 404" button

**Comment by LekoArts** [comment]
@davidbailey00 Should be fixed now, right?

**Comment by interglobalmedia** [comment]
FYI: I found out in my case that it was a Chrome browser issue. Gatsby works in Firefox and Safari for me but not Chrome. Hope this helps others who might be having similar issues.
