### ISSUE TITLE
perfixLink should add any required trailing slashes

### ISSUE THREAD

**Issue by danielo515** [gatsbyjs/gatsby#855]
Hello,

I expect the helper function `prefixLink` to generate valid links, no matter what I throw to it.

For example, I expect the following to work

```jsx
 <Link to={prefixLink('somesection')}>
                           BlaBLa
   </Link>
```

But it does not. I'm forced to do it like this:

```jsx
 <Link to={prefixLink('somesection/')}>
                           BlaBLa
   </Link>
```

Please note the trailinig `/` at the end of `somesection`
Not a big deal, but a bit annoying. I didn't noticed this before because 99% of my links are generated automatically from gatsby metadata.

**Comment by KyleAMathews** [comment]
What does it create that's invalid?

The code is pretty simple, feel free to make a PR to fix up things! https://github.com/gatsbyjs/gatsby/blob/master/lib/isomorphic/gatsby-helpers.js#L33

**Comment by emilyaviva** [comment]
I actually think this should stay the way it is. Outside of webpack-dev-server, postfixing a `/` to a link may not actually be what you want in a production environment .

**Comment by KyleAMathews** [comment]
Oh good point. Yeah, trailing slashes aren't required. Technically you could have pages at both the slashless and with-it versions (though that'd be really confusing). Perhaps what prefixLink could do though is tell you when you try linking to a page that doesn't exist.

**Comment by KyleAMathews** [comment]
Closed as not support v0 anymore
