### ISSUE TITLE
gatsby-source-wordpress returning error

### ISSUE THREAD

**Issue by brandonferrer** [gatsbyjs/gatsby#8550]
## Description

There appears to have been breaking changes to the gatsby-source-wordpress plugin. You can't even run the basic queries from the demo. My query was working fine a few weeks ago. 

Describe the issue that you're seeing.

error Plugin gatsby-source-wordpress returned an error

  TypeError: Cannot read property 'createNode' of undefined

Also the schema is all different in graphiql. or was. I attempted to install the plugin again and now my app won't build. 

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
    Yarn: 1.6.0 - ~/.nvm/versions/node/v8.9.4/bin/yarn
    npm: 4.6.1 - ~/.nvm/versions/node/v8.9.4/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 62.0.2
    Safari: 12.0
  npmPackages:
    gatsby: ^1.9.277 => 1.9.277 
    gatsby-link: ^1.6.46 => 1.6.46 
    gatsby-plugin-google-fonts: 0.0.4 => 0.0.4 
    gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11 
    gatsby-source-wordpress: ^3.0.1 => 3.0.1 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

**Comment by kakadiadarpan** [comment]
@brandonferrer With Gatsby v1 you will need to use `gatsby-source-wordpress` version `2.x.x`. `3.x.x` is for Gatsby v2.
