### ISSUE TITLE
Install flow-typed types using gatsby-plugin-flow

### ISSUE THREAD

**Issue by PolGuixe** [gatsbyjs/gatsby#8551]
## Summary

I have tried to install types using `flow-typed` cli and it fails to detect a flow project. I am using the `gatsby-plugin-flow`. I guess that it fails to find a flow.config file or similar.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by kakadiadarpan** [comment]
@PolGuixe can you provide relevant environment information by running `gatsby info --clipboard`? Also, can you provide a reproduction repo for this? That would make it much simpler to diagnose this issue.

**Comment by PolGuixe** [comment]
Gatsby Info:
```

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.3.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.4 => 2.0.4 
    gatsby-image: ^2.0.7 => 2.0.7 
    gatsby-plugin-flow: ^1.0.1 => 1.0.1 
    gatsby-plugin-manifest: ^2.0.2 => 2.0.2 
    gatsby-plugin-offline: ^2.0.5 => 2.0.5 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-sharp: ^2.0.5 => 2.0.5 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-source-filesystem: ^2.0.1 => 2.0.1 
    gatsby-transformer-sharp: ^2.1.1 => 2.1.1 
  npmGlobalPackages:
    gatsby-cli: 2.4.1
```

To reproduce:
1. Create new Gatsby project
2. Install `gatsby-flow-plugin`
3. Install `flow-typed`, [instructions here](https://github.com/flow-typed/flow-typed) 
4. Add a package e.g. `flow-typed install @material-ui/core`, then this error:

`Error: Unable to find a flow project in the current dir or any of it's parent dirs!`

What I can see is that `flow-typed` does not recognise the project as a flow project.

**Comment by CarlRosell** [comment]
I'm using flow as well and have no problem with flow-typed. I believe that the issue comes from you not having a `.flowconfig` file.
