### ISSUE TITLE
Calling "touchNode" with a nodeId is deprecated. Please pass an object containing a nodeId instead: touchNode({ nodeId: 'a-node-id' }) "touchNode" was called by gatsby-source-wordpress

### ISSUE THREAD

**Issue by SimonIMG** [gatsbyjs/gatsby#8553]
## Description

When I run `gatsby develop`, I get a long list of the following, repeated notice:

```
Calling "touchNode" with a nodeId is deprecated. Please pass an object containing a nodeId instead: touchNode({ nodeId: 'a-node-id' })
"touchNode" was called by gatsby-source-wordpress
```

Am I the only one getting these? I have googled it extensively, but I don't know how to resolve the issue that is causing this notice.

I have a feeling they are due to images in the WYSIWYG fields of the attached WordPress site.

### Steps to reproduce

1. Create a gatsby v2 site set up for creating data from a WordPress site.
2. It seems the more images I add to the WP backend, the more of these notices I get after a `gatsby develop`. But I'm not 100% sure it's being caused by images added inline in WP post WYSIWYG fields.

### Expected result

Not see this notice

### Actual result

Stacks of these. I'd say around 100 of them are in my terminal window.

### Environment

```
  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i7-3840QM CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.8.0 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.2.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 62.0
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.3 => 2.0.3 
    gatsby-image: ^2.0.7 => 2.0.7 
    gatsby-plugin-manifest: ^2.0.2 => 2.0.2 
    gatsby-plugin-offline: ^2.0.5 => 2.0.5 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-sharp: ^2.0.5 => 2.0.5 
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.0 
    gatsby-plugin-typography: ^2.2.0 => 2.2.0 
    gatsby-source-filesystem: ^1.5.39 => 1.5.39 
    gatsby-source-wordpress: ^2.0.93 => 2.0.93 
    gatsby-transformer-sharp: ^2.1.1 => 2.1.1 
  npmGlobalPackages:
    gatsby-cli: 2.4.1
```

**Comment by LeKoArts** [comment]
Update `gatsby-source-filesystem` to v2

**Comment by SimonIMG** [comment]
Success! Thanks very much for your help @kakadiadarpan  and @LeKoArts .

For anyone else with this issue, I updated my package.json with the following (replacing the previous ^1.5.39 and ^2.0.93 )...
```
"gatsby-source-filesystem": "^2.0.0",
"gatsby-source-wordpress": "^3.0.0",
```
Then I ran `npm update`. This updated all my dependencies, of course.

All the notices are gone (and my `gatsby develop` process is WAY faster).

**Comment by AttilaTheHen** [comment]
Was running into this myself just now - thanks!
