### ISSUE TITLE
Add a MozJPEG option to gatsby-transformer-sharp

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#8556]
## Summary

[MozJPEG](https://github.com/mozilla/mozjpeg) provides better image compression at the cost of longer processing time. 

It should be possible to opt-in to using MozJPEG for generating image thumbnails with gatsby-transformer-sharp.

@Fetten implemented an 'always-on' version of this at https://github.com/gatsbyjs/gatsby/pull/5682

### Basic example

How should this option be implemented? As an env var like `GATSBY_ENABLE_MOZJPEG`? Some other way?

### Motivation

Better image compression is 😄, longer builds times are 😭. Providing this as an option means people can choose to enable it when appropriate.

**Comment by Fetten** [comment]
Finally had the chance to finish this up :-)
Using an env var seems to be the best option for now, so I added `GATSBY_JPEG_ENCODER=MOZJPEG`.
