### ISSUE TITLE
In V2 is it possible to have the same "Layout"

### ISSUE THREAD

**Issue by PolGuixe** [gatsbyjs/gatsby#8558]
## Summary
Is it possible to have Layout for each page? The new approach is fine and I have nothing against repeating the Layout for each page. However, when I change page the component is unmounted and any Layout animations are dismissed. 

e.g. Imagine you have a drawer menu component for navigation which is normally hidden. You have this component in the Layout and its state is managed by the Layout component class. If the drawer is open and you click on a navigation link the router will load a new page with a new layout dismissing the drawer menu close animation. 

I hope is clear. 😄 

## Relevant information

I am using https://material-ui-layout.origen.studio

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LeKoArts** [comment]
Yeah, that's possible!
https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-layout
