### ISSUE TITLE
How to get markdown data in public build

### ISSUE THREAD

**Issue by dabedoc** [gatsbyjs/gatsby#8566]
So I am using markdown pages as a data source and I want to get the json data after the build. Is there any way to get that data ?

**Comment by dabedoc** [comment]
Well, I think I might have been a little vague. So what I want to do is that I want to fetch the markdown data  from the public build. Gatsby fetches data from the markdown files and use it to generate the pages. It also generates json file with the data from the markdown right? I want to get that data.

**Comment by CanRau** [comment]
Sorry but still don't really get it^^
That's, in my understanding what you do using graphql…
But you want to fetch it dynamically from the browser? From the same or another page?
Does not include frontmatter but maybe
```
{
  markdownRemark {
    rawMarkdownBody
  }
}
```
helps?

You mean like
```
fetch(`/static/d/920/path---de-4-f-4-0ac-Bkf1o9f649sK7HCWrlTVZ6vyyA8.json`)
```
So you want to know the filename?

**Comment by dabedoc** [comment]
The graphql option is only available during the development. Not for when you have built static pages for your site. I want to get data from the static pages built from gatsby. So yeah, I would wanna know the name of the json files that contains that data.

**Comment by CanRau** [comment]
don't know how to do that right now as I didn't had the need so far, sorry…
still curious why one would need to get them later, but you don't have to share your use case of course^^

One thing which came to my mind would be using them on a non gatsby page, but how to provide the names to them? easier could be creating some kind of api endpoint or expose the needed info in an rss feed or maybe more useful [json feed](https://jsonfeed.org)

hopefully someone else can help, or you can find another solution

**Comment by CanRau** [comment]
how about the json feed idea? but yeah I guess you would still have to do a lot of property mapping manually, if that's what you try to avoid…

**Comment by pieh** [comment]
You can run queries in `gatsby-node` `onPostBuild` and then use whatever you like with it - you will have raw js objects with data

**Comment by CanRau** [comment]
@dabedoc To build on @pieh's comment you could generate pages based on the filename, sounds almost exactly like what you requested?! Kind of an automatic API..

**Comment by dabedoc** [comment]
Thanks @pieh @CanRau 
Sorry, took me a while to reply.
