### ISSUE TITLE
[www] Search stops working after first usage.

### ISSUE THREAD

**Issue by NickyMeuleman** [gatsbyjs/gatsby#8567]
## Description
Search function on https://www.gatsbyjs.org/ stops working after your first search.

### Steps to reproduce

1. Visit https://www.gatsbyjs.org/
2. Search for something (in the docs?) and click it
3. try to search again using the searchbar in the header

### Expected result

New search term gets picked up, does it's thing and Algolia populates the results.

### Actual result

Only autosuggestions of previous searches appear (also, not lined up with the searchbox vertically)

![2018-09-26_21-30-32](https://user-images.githubusercontent.com/30179461/46104707-59e1d500-c1d4-11e8-9bde-d5ef54c45299.gif)

### Environment
Windows 10 Home build 1803
Google Chrome Versie 69.0.3497.100 (Officiële build) (64-bits)

**Comment by NickyMeuleman** [comment]
Same results for Firefox 62.0.2 (64-bits)

**Comment by oorestisime** [comment]
Can't reproduce this on Firefox 62.0.2. Do you get an error in console ?

**Comment by NickyMeuleman** [comment]
Only thing in the console is a few GET requests the first time I hover over the searchbox and then one (that gets sent to Algolia) per letter I type.

The second time, nothing gets printed to the console.

**Comment by kakadiadarpan** [comment]
I think this breaks after a client-side routing happens.

Steps:
1. Visit https://www.gatsbyjs.org/
2. Click on `Docs` link.
3. Try to search for something using the search bar in the header.

It doesn't work.
