### ISSUE TITLE
[1.0] Add support for removing nodes

### ISSUE THREAD

**Issue by MarcCoet** [gatsbyjs/gatsby#857]
If I delete a page I have to manually delete the .cache folder (Alpha13)

**Comment by KyleAMathews** [comment]
Ooooo... you're right, I forgot about this TODO https://github.com/gatsbyjs/gatsby/blob/0124901cf6bf532b2b2744e0958c52fb19219935/packages/gatsby-source-filesystem/src/gatsby-node.js#L98

There needs to be a new `DELETE_NODE` redux action created which handles this and have the filesystem plugin implement that... if this is something you could take on, that'd be really helpful!

**Comment by KyleAMathews** [comment]
Working on this now

**Comment by KyleAMathews** [comment]
Fixed now. Will release another alpha after https://github.com/gatsbyjs/gatsby/issues/862 is fixed. In the meantime, I published a canary with this PR (just change the version of gatsby packages in your package.json to "canary").

**Comment by justinfriebel** [comment]
I just ran into this trying out the blog starter. If there is a way for me to help out and implement it there and I can try a PR.
