### ISSUE TITLE
[www] gatsby-plugin-google-analytics doc stuck in redirect loop.

### ISSUE THREAD

**Issue by vanthiyathevan** [gatsbyjs/gatsby#8571]
## Description

going to https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/?=google goes into redirect loop with `no-cache=1` query param appended.

### Steps to reproduce

navigate to https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/?=google

I've also experienced this issue. on my site. Only happens when serving pre build page.

**Comment by kakadiadarpan** [comment]
@vanthiyathevan Thank you for reporting this issue! We'll take a look at this soon.

**Comment by DSchau** [comment]
@vanthiyathevan I can't replicate this! Could you provide some more context re: browser, and/or just try again? We've been making some changes to the offline plugin so it's possible that this has (very) recently been fixed.

**Comment by vanthiyathevan** [comment]
This issue seem to have been resolved with the last build

**Comment by kakadiadarpan** [comment]
Thanks for the update @vanthiyathevan
