### ISSUE TITLE
Wordpress schema change with gatsby-source-wordpress

### ISSUE THREAD

**Issue by brandonferrer** [gatsbyjs/gatsby#8576]
## Description

Unable to query Wordpress blog post via GraphiQL or in app.

### Steps to reproduce

Query in GraphiQL 
```gql
{
  allWordpressPost {
    edges {
      node {
        id
        slug
        title
        content
        excerpt
        date
        modified
      }
    }
  }
}
```
### Expected result

Return query data

### Actual result
```json
{
  "errors": [
    {
      "message": "Cannot query field \"allWordpressPage\" on type \"Query\". Did you mean \"allSitePage\" or \"allWordpressAcfOptions\"?",
      "locations": [
        {
          "line": 2,
          "column": 5
        }
      ]
    }
  ]
}
```
### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
    Yarn: 1.6.0 - ~/.nvm/versions/node/v8.9.4/bin/yarn
    npm: 4.6.1 - ~/.nvm/versions/node/v8.9.4/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 62.0.2
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.9 => 2.0.9 
    gatsby-plugin-google-fonts: 0.0.4 => 0.0.4 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-source-wordpress: ^3.0.1 => 3.0.1 
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```

**Comment by kakadiadarpan** [comment]
@brandonferrer can you provide a reproduction repo for this? That would make it much simpler to diagnose this issue.

Also, did you had a chance to look at [`using-wordpress`](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-wordpress) example?

**Comment by brandonferrer** [comment]
As far as reproduction, I'm just trying to query any of the queries in the gatsby/wordpress docs. 

This is my gatsby-config.js

{
      resolve: 'gatsby-source-wordpress',
      options: {
        // your wordpress source
        baseUrl: 'brandonferrer.blog',
        protocol: 'http',
        // is it hosted on wordpress.com, or self-hosted?
        hostingWPCOM: false,
        // does your site use the Advanced Custom Fields Plugin?
        useACF: false,
      },
    }

**Comment by seanngpack** [comment]
Same exact problem, upgraded Gatsby to V2 and it resulted in this exact same error.

**Comment by pieh** [comment]
@brandonferrer it seems like your wordpress installation have some problems - non of the links works: trying to click on post details result in:
```
Not Found
The requested URL /2018/09/26/hello-world/ was not found on this server.

Apache/2.4.29 (Ubuntu) Server at brandonferrer.blog Port 80
```
and same when trying to hit REST endpoint - http://brandonferrer.blog/wp-json

**Comment by pieh** [comment]
[`using-wordpress`](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-wordpress) example works, so I can't really tell what's wrong without more details

**Comment by brandonferrer** [comment]
> @brandonferrer it seems like your wordpress installation have some problems - non of the links works: trying to click on post details result in:
> 
> ```
> Not Found
> The requested URL /2018/09/26/hello-world/ was not found on this server.
> 
> Apache/2.4.29 (Ubuntu) Server at brandonferrer.blog Port 80
> ```
> and same when trying to hit REST endpoint - http://brandonferrer.blog/wp-json

Thanks, I was thinking that may be this issue as well, but I'm able to hit their V2 endpoint:

brandonferrer.blog/index.php/wp-json/wp/v2/posts

**Comment by brandonferrer** [comment]
Ah, just noticed I'm having to include index.php. Why would this affect the graphql schema though? I'd expect to be able to query still, then either return nothing or see some kind of graphql error.

**Comment by chmac** [comment]
@brandonferrer Can you fix your WP install to support permalinks? (That means links without `index.php` in the URL)

The WordPress source plugin automatically appends `/wp-json` to the `baseUrl` you provide [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/fetch.js#L36).

You might try adding the `/index.php` to your `baseUrl` value in `gatsby-config.js`. That might fix the issue. Otherwise I guess there's an unwritten hard requirement that your WP must support "pretty permalinks" (to use the WordPress parlance).

**Comment by brandonferrer** [comment]
@chmac thanks. I tried adding /index.php to my baseUrl with no luck. It definitely was a Wordpress implementation issue on my end though, and I ended up starting fresh with a new Wordpress. It worked as expected even after the plugin and V2 updates. Now I'm able to fetch post from brandonferrer.blog/wp-json/wp/v2/posts rather than needing /index.php in the baseUrl.

My issue was that I attempted to host multiple Wordpress implementations on a single Apache instance, along with issuing ssl certificates. I got a little crazy... and it coincidentally occurred the same time my gatsby-wordpress-plugin updated and I migrated to V2.

**Comment by mediamaker** [comment]
I am going to get a little crazy with multiple Wordpress implementations on a single Apache droplet. Here's a guide I found in case that's helpful.
[How to Set Up Let’s Encrypt Certificates for Multiple Apache Virtual Hosts on Ubuntu](https://www.digitalocean.com/community/tutorials/how-to-set-up-let-s-encrypt-certificates-for-multiple-apache-virtual-hosts-on-ubuntu-14-04)
