### ISSUE TITLE
Can I embed the presentation of SpeakerDeck with gatsby-transformer-remark?

### ISSUE THREAD

**Issue by muukii** [gatsbyjs/gatsby#8578]
## Summary

Can I embed the presentation of SpeakerDeck?

I tried to embed the presentation of SepeakerDeck to my article.
Just like this

```md

# Title

## My Presentation

<script async class="speakerdeck-embed" data-id="543c9b62d7a44aa3a048fcad02dee422" data-ratio="1.77777777777778" src="https://speakerdeck.com/assets/embed.js"></script>
```

But, this approach was not working. The script did not run.
How to run some scripts in generated article?
Please tell me, if you know some solutions.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by kakadiadarpan** [comment]
@muukii can you provide relevant environment information by running `gatsby info --clipboard`?

Also, can you provide a reproduction repo for this? That would make it much simpler to diagnose this issue.

**Comment by muukii** [comment]
@kakadiadarpan 
Sorry, I tried this command `gatsby info --clipboard`. But command not found.
I'm still using Gatsby v1.
In usually, Does it run the scripts written in markdown file?

Okay, I will try to reproduce on a simple project.

**Comment by muukii** [comment]
I've created a reproduction project.

Added script tag for SpeakerDeck in `src/pages/hello-world/index.md`
Just like followings.

Could you check this? @kakadiadarpan 

```md
---
title: Hello World
date: "2015-05-01T22:12:03.284Z"
---

BEGIN::My Presentation

<script async class="speakerdeck-embed" data-id="543c9b62d7a44aa3a048fcad02dee422" data-ratio="1.77777777777778" src="//speakerdeck.com/assets/embed.js"></script>

END::My Presentation
```

[Archive.zip](https://github.com/gatsbyjs/gatsby/files/2426241/Archive.zip)

**Comment by kakadiadarpan** [comment]
@muukii have you installed `gatsby-cli` in your machine? If not, can you please install it globally and then run `gatsby info --clipboard`?

Also in the [comment](https://github.com/gatsbyjs/gatsby/issues/8578#issuecomment-425276414) above, you mentioned that you are using in Gatsby v1, but the repo you provided is with Gatsby v2?

When I ran the project using `yarn develop` I got this error:

> /Archive/src/components/layout.js
>  9:25  error  '__PATH_PREFIX__' is not defined  no-undef

**Comment by muukii** [comment]
@kakadiadarpan 

The reproduction project was made from a template. 
It seems using Gatsby v1.

You can create the following command.
`gatsby new reproduction https://github.com/gatsbyjs/gatsby-starter-blog`

Then, add following script to `src/pages/hello-world/index.md`

```md
<script async class="speakerdeck-embed" data-id="543c9b62d7a44aa3a048fcad02dee422" data-ratio="1.77777777777778" src="//speakerdeck.com/assets/embed.js"></script>
```

If you have time, please try it.
