### ISSUE TITLE
Scaling Gatsby with thousands pages

### ISSUE THREAD

**Issue by olivierpascal** [gatsbyjs/gatsby#8582]
## Relevant information

I use Gatsby to generate a website with a lot of pages in multiple languages. Let's say something like 1k pages in 5 languages, ~5k pages.

In production (not sure if this is the case in development mode), Gatsby prefetch a file named in my case `10-[hash].js` which exports a JSON object that looks like this:

```js
{  
   "pages": [
      {  
         "componentChunkName": "...",
         "jsonName": "...",
         "path": "..."
      },
      // ... thousands of objects, one for each page
   ],
   "dataPaths": {
      "...": "...",
      // ... thousands of objects, one for each path
   }
}
```

My pages are very lightweight but this file can weight several hundreds of ko depending of the number of pages.

Let's say I use Gatsby for a Wikipedia-like website. If I am correct, it means that every client will have to download (prefetch) a huge JSON file with millions of entries just to see one page?

**My question is: what is this JSON object, and in which extent can Gatsby be considered scalable if this file size increase proportionally with the number of pages?**

Thanks.

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.10.0/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 62.0
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.8 => 2.0.8 
    gatsby-image: ^2.0.9 => 2.0.9 
    gatsby-source-filesystem: ^2.0.1 => 2.0.1 
  npmGlobalPackages:
    gatsby-cli: 2.4.1
```

### File contents

N/A

**Comment by m-allanson** [comment]
Hey @olivierpascal the aim is for Gatsby to be a great choice for big sites, but as you've seen the page metadata bundle can get quite large when dealing with 000's of pages. 

This is a known issue at the moment - there's discussion at https://github.com/gatsbyjs/gatsby/issues/4746 and @KyleAMathews initial work on resolving this is at https://github.com/gatsbyjs/gatsby/pull/6651.

**Comment by olivierpascal** [comment]
Awesome, thanks for pointing me to the right discussion and the work in progress.
