### ISSUE TITLE
Sass support?

### ISSUE THREAD

**Issue by jeberly** [gatsbyjs/gatsby#86]
Hello, I know how to support sass files using webpack, but I am little confused if/how that is supported in gatsbyjs as webpack config seems buried in source of gatsby.

Thanks in advance for help.

**Comment by KyleAMathews** [comment]
I think @ChristopherBiscardi is working on making it possible to define loaders outside of the internal Gatsby Webpack config. Perhaps he can update us what's happening?

In the meantime, it's easiest to fork Gatsby and modify the loaders locally. Not an ideal situation at all I know :-(

**Comment by ChristopherBiscardi** [comment]
I've created a PR with the approach that I think has been working the best so far: https://github.com/gatsbyjs/gatsby/pull/87

**Comment by KyleAMathews** [comment]
Hi @jeberly as of 0.7.1 you can add config for sass https://github.com/gatsbyjs/gatsby/releases/tag/v0.7.1
