### ISSUE TITLE
Port v1 `gatsby-plugin-catch-links` to v2

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#8610]
## Summary

@jdfm recently updated v1 of `gatsby-plugin-catch-links` to cover more edge cases and added tests 🎉 We should port these updates over to v2 of `gatsby-plugin-catch-links`

### Basic example

View the changes in @jdfm's pull request: https://github.com/gatsbyjs/gatsby/pull/7779/files.

Import the changes in the following files to the current version of Gatsby:

- packages/gatsby-plugin-catch-links/package.json
- packages/gatsby-plugin-catch-links/src/__tests__/catch-links.js
- packages/gatsby-plugin-catch-links/src/__tests__/gatsby-browser.js
- packages/gatsby-plugin-catch-links/src/catch-links.js

Note that the change to `jest.config.js` is not needed for Gatsby v2.

Check that the tests all pass with `yarn run test`.

The [v2 migration guide may be useful if you run into errors](https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/).

### Motivation

More edge cases handled + corresponding tests should make for a more robust plugin.

**Comment by rscott** [comment]
I took a shot at this in PR #8646, hope it works out OK.

**Comment by chadfawcett** [comment]
Resolved in #8646
