### ISSUE TITLE
gatsby-plugin-layout stopped working (in dev mode) after beta

### ISSUE THREAD

**Issue by loudmouth** [gatsbyjs/gatsby#8616]
## Description

Hello 👋 since upgrading from the beta versions of the main Gatsby dependency and plugins to the release v2 versions, I have noticed that `gatsby-plugin-layout` is no longer working as expected (it worked in beta). I have a music player that should be present on each page without reloading, but now when I change pages on my site, I see the entire site reload instead of just the are where the page should be contained.

I have rolled back to the commit just before I upgraded to the official `v2` release and can confirm it worked then: at that point I had the following versions:

npmPackages:
    gatsby: ^2.0.0-rc.10 => 2.0.0-rc.10
    gatsby-image: ^2.0.0-rc.1 => 2.0.0-rc.1
    gatsby-plugin-catch-links: ^2.0.2-rc.1 => 2.0.2-rc.1
    gatsby-plugin-layout: ^1.0.0-rc.3 => 1.0.0-rc.3
    gatsby-plugin-netlify-cache: 0.0.2 => 0.0.2
    gatsby-plugin-offline: ^2.0.0-rc.2 => 2.0.0-rc.2
    gatsby-plugin-react-helmet: ^3.0.0-rc.1 => 3.0.0-rc.1
    gatsby-plugin-sharp: ^2.0.0-rc.3 => 2.0.0-rc.3
    gatsby-plugin-styled-components: ^3.0.0-rc.1 => 3.0.0-rc.1
    gatsby-plugin-typography: ^2.2.0-rc.3 => 2.2.0-rc.3
    gatsby-source-contentful: ^2.0.1-rc.3 => 2.0.1-rc.3
    gatsby-transformer-remark: ^2.1.1-rc.1 => 2.1.1-rc.1
    gatsby-transformer-sharp: ^2.1.1-rc.2 => 2.1.1-rc.2
    gatsby-transformer-sqip: ^2.0.0-rc.3 => 2.0.0-rc.3
  npmGlobalPackages:
    gatsby-cli: 2.4.2
    gatsby: 1.9.261

### Steps to reproduce

Create a site with `gatsby-plugin-layout` with a few pages and one or more components that should be static across all pages. Run the project and switch pages. 

*Edit:* I just spent time forking this and publishing for the purposes of this issue, and now can confirm that the issue is only prevelant during local development, and is not observable in production.

I've forked my repo and open-sourced it: https://github.com/loudmouth/gatsby-layout-demo
Deployed site on Netlify: https://festive-austin-a26edc.netlify.com/

### Expected result

Components that are a part of my layout should not unmount/remount when switching pages.

### Actual result

All components remounted when switching pages.

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Shell: 2.3.1 - /usr/local/bin/fish
  Binaries:
    Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 47.0
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.1 => 2.0.1
    gatsby-image: ^2.0.5 => 2.0.5
    gatsby-plugin-catch-links: ^2.0.2 => 2.0.2
    gatsby-plugin-layout: ^1.0.1 => 1.0.1
    gatsby-plugin-netlify-cache: 0.0.2 => 0.0.2
    gatsby-plugin-offline: ^2.0.5 => 2.0.5
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^2.0.5 => 2.0.5
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.0
    gatsby-plugin-typography: ^2.2.0 => 2.2.0
    gatsby-source-contentful: ^2.0.1 => 2.0.1
    gatsby-transformer-remark: ^2.1.2 => 2.1.2
    gatsby-transformer-sharp: ^2.1.1 => 2.1.1
    gatsby-transformer-sqip: ^2.0.0 => 2.0.0
  npmGlobalPackages:
    gatsby-cli: 2.4.2
    gatsby: 1.9.261

**Comment by simonjoom** [comment]
hello i'm using the last gatsby, using gatsby-plugin-layout, i have to say that it's totally work for me.

Of course the components who contain your pages in /pages will unmount 

just put a WillUnmount in your Layout component.
  componentWillUnmount() {
    console.log("unmountLayout") 
  }

if you don't see unmountLayout then it's totally fine.
The component should to not unmount like sidebar just put them in Layout. 

But the different page who is contained in props.children will be unmount when you change of page that is totally normal in my sense

**Comment by loudmouth** [comment]
Hmm, running one more `npm update` has fixed the issue. My new environment looks as follows:


  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Shell: 2.3.1 - /usr/local/bin/fish
  Binaries:
    Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 47.0
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.12 => 2.0.12 
    gatsby-image: ^2.0.12 => 2.0.12 
    gatsby-plugin-catch-links: ^2.0.3 => 2.0.3 
    gatsby-plugin-layout: ^1.0.2 => 1.0.2 
    gatsby-plugin-netlify-cache: 0.0.2 => 0.0.2 
    gatsby-plugin-offline: ^2.0.5 => 2.0.5 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-sharp: ^2.0.5 => 2.0.5 
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.0 
    gatsby-plugin-typography: ^2.2.0 => 2.2.0 
    gatsby-source-contentful: ^2.0.1 => 2.0.1 
    gatsby-transformer-remark: ^2.1.4 => 2.1.4 
    gatsby-transformer-sharp: ^2.1.3 => 2.1.3 
    gatsby-transformer-sqip: ^2.0.0 => 2.0.0 
  npmGlobalPackages:
    gatsby-cli: 2.4.2
    gatsby: 2.0.12
