### ISSUE TITLE
Page Block/Section Components ( Library )

### ISSUE THREAD

**Issue by voordev** [gatsbyjs/gatsby#8636]
Im looking for component library but not components like 'button', 'slider' but components like
'hero', 'pricing table', 'footer', etc.

Blocks of page elements needed in every website. 
Something like bootstrap themes but then for react/gatsby so you can say, import a pricing table into your project.

Is there/ are there any solutions in this regard? 
I already did extensive searching but only found "Bit" and component libraries for web applications like buttons and bootstrap-react and material-react

**Comment by voordev** [comment]
What I look for is something like this:

https://www.froala.com/design-blocks/webpage-builder

But then with gatsby compatible, react components/ blocks.
_my goal is to minimise the time required to testdrive a certain page block like pricing table and not have to reimplement each html part to a react / gatsby component _

**Comment by kakadiadarpan** [comment]
@voordev I'm not sure if this issue belongs here.

You can use any opensource React UI library which suits your needs, but most of the libraries that you will find will provide just basic stuff. Everyone's design/content/idea would differ for `pricing table` or any other special component. It's always better to use something that provides you with basic components and then building the components you need on top of that.

Most of the `React UI Library's` will provide you with a `header`, `footer`, `table`, etc. and you'll need to provide it with data. Just google for `React UI library` and you'll get a lot of options to choose out of.
