### ISSUE TITLE
clients-only-path Feature mods with example attached

### ISSUE THREAD

**Issue by simonjoom** [gatsbyjs/gatsby#8640]
## Relevant information

Using clients-only-path with last gatsby v2 work only if we define one page/one component for one route.
The use case for me it was to create a little tchat with client-only-page to avoid page generations for the tchat routes.

As clients-only-path is not related about generate pages for a real route it should be available for any page and fully customisable with gatsby-node

https://github.com/gatsbyjs/gatsby/tree/master/examples/client-only-paths
 
I was deeper in the gatsby-core here the description to help to understand what i did.
In fact gatsby use page.path only in his code to attach the information of one route with one page

But it should to attach matchPath if it exists before else we need to separate all routes even the "clients route" for different page.path

it's can begin little not convenient because the boilerplate begin bigger 
like for a tchat application 
So for the current working gatsby we have
/pages/index.js ->generate real page
/pages/page-2.js ->generate real page
/pages/chat/index.js -> do not generate page ->client-only-path
/pages/chat/create.js -> do not generate page ->client-only-path
/pages/chat/chats.js  -> do not generate page ->client-only-path

I would like to have only this 
/pages/index.js ->generate real page (inside check for location and attach properly the route to the component)
/pages/page-2.js ->generate real page

and in pages/index.js i would like to render all client-only-path route to compare the location.

what i did is to change all match  'page.path' in the code of gatsby to
 **page.matchPath?page.matchPath:page.path**

then i can use all my route/component in only one page 

So after this modifications i can do in gatsby-node onCreatePage
```
 if (page.path == "/" && !page.matchPath) {
    let newPage = { component: page.component, path: "/" };
    let newPage1 = Object.assign({}, newPage, { matchPath: `/create` });
    createPage(newPage1);
    let newPage2 = Object.assign({}, newPage, { matchPath: `/api` });
    createPage(newPage2);
    let newPage3 = Object.assign({}, newPage, { matchPath: `/post/:id` });
    createPage(newPage3);
    let newPage4 = Object.assign({}, newPage, { matchPath: `/drafts` });
    createPage(newPage4);
    let newPage5 = Object.assign({}, newPage, { matchPath: `/chats` });
    createPage(newPage5);
    let newPage6 = Object.assign({}, newPage, { matchPath: `/car/:id` });
    createPage(newPage6);
    let newPage7 = Object.assign({}, newPage, { matchPath: `/cars` });
    createPage(newPage7);
    let newPage8 = Object.assign({}, newPage, { matchPath: `/users` });
    createPage(newPage8);
    let newPage9 = Object.assign({}, newPage, { matchPath: `/user/:id` });
    createPage(newPage9);
    let newPage10 = Object.assign({}, newPage, {
      matchPath: `/forgetPassword`
    });
}
```

As you can see all client page are linked to the route "/"  with matchPath as a single source of information. 

 **Call createPage multiple time for the same route "/" will create only one node internally  for the route "/" with the current working gatsby so all others route won't work**

but just change  all match  'page.path' in the code to
 **page.matchPath?page.matchPath:page.path**  give us much more power.

```
In pages/index.js

import UsersPage from "../components/user/UsersPage";
import UserPageCreate from "../components/user/UserPageCreate";
import UserPage from "../components/user/UserPage"; 
import LoginPage from "../components/user/auth/Login"; 

export default props => { 
  const { location } = props; 
  const Comp =
    location.pathname == "/user/create"
      ? UserPageCreate
      : location.pathname == "/users"
        ? UsersPage
        : location.pathname.indexOf("/user/") == !-1 //:id
          ? UserPage
           :LoginPage
 return <Comp {...props} />;
};
```

Now you can see all related component of the tchat are located in the same page (so same bundle) but it's remain that we have differents routes for the same destination.

So i really thing will be great to change the code of gatsby to support this feature.

### File contents (if changed)
 The full example is in
https://github.com/simonjoom/Gatsby-apollo-chatkiller

It can be shared for the community as this repo is a nice boilerplate use case
 with gatsby / apollo, clients-only-path, plugin-layout for gatsby

**Comment by pieh** [comment]
You can still use same component for different pages / paths - you just need unique paths - I probably don't understand why this is a problem.

Also you can just create single "catch-all" matchPath with `/*` and handle routes directly in that component. If there is "static" path existing (for example `/page-2` in your example) gatsby will use that over any `matchPath` it will find

**Comment by simonjoom** [comment]
hmm i tried many times to avoid to change the code of gatsby but it's not working. 
Yes the problem to have unique paths that you have to create a new file for each 'client only path' so a new file for each component who define one route.
The problem is i should to add the layout on each file so lot of duplicate code (i use the structure of plugin layout)..
 i think test if match path exist and use it instead paths in the core is better:

page.matchPath?page.matchPath:page.path
