### ISSUE TITLE
plugin-offline - Response served by service worker has redirections

### ISSUE THREAD

**Issue by Coriou** [gatsbyjs/gatsby#8651]
## Summary

I am using the `gatsby-plugin-offline` in it's default configuration. On my iPhone, when I try to access the site (previously accessed just fine) I'm getting this error "**Response served by service worker has redirections**". And that's it.

I don't have anything in the console other than this message. I have no idea how to debug this. I didn't want to clear my device's cache or anything, because I also don't know how to reproduce so I'd like to leave it in this state until I find a solution to this problem.

I'm sorry I have nothing else to add, the configuration is 100% vanilla and I have no other debug messages...

### Environment

```

  System:
    OS: macOS 10.14
    CPU: x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 9.4.0 - ~/.nvm/versions/node/v9.4.0/bin/node
    Yarn: 1.10.1 - ~/.nvm/versions/node/v9.4.0/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v9.4.0/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 62.0.2
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.12 => 2.0.12 
    gatsby-image: ^2.0.12 => 2.0.12 
    gatsby-link: ^2.0.2 => 2.0.2 
    gatsby-plugin-mailchimp: https://github.com/benjaminhoffman/gatsby-plugin-mailchimp.git#gatsby-v2 => 3.3.0 
    gatsby-plugin-manifest: ^2.0.4 => 2.0.4 
    gatsby-plugin-offline: ^2.0.5 => 2.0.5 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-sass: ^2.0.1 => 2.0.1 
    gatsby-plugin-sharp: ^2.0.5 => 2.0.5 
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.3 => 1.0.3 
    gatsby-source-filesystem: ^2.0.1 => 2.0.1 
    gatsby-source-prismic: ^2.0.0-alpha.5 => 2.0.0-alpha.5 
    gatsby-transformer-sharp: ^2.1.3 => 2.1.3 
    gatsby-transformer-sqip: 2.0.0 => 2.0.0 
  npmGlobalPackages:
    gatsby-cli: 2.4.2
```

**Comment by kakadiadarpan** [comment]
@Coriou can you provide a reproduction repo for this? That would make it much easier to diagnose this issue.

**Comment by Coriou** [comment]
Well, no, not really. This kinda was a one off problem, as I was trying to say. I have no other debug info whatsoever, I have no idea what went wrong and thus I don't know how to reproduce it. I have the gatsby-plugin-offline actived with it's default settings.

I can not put my whole app on Github for this purpose. I'll try to figure it out myself. Thanks

**Comment by Coriou** [comment]
@natew I figured that 404 on .map files were causing a lot of redirection problems. I removed source map generation on the production build and significantly reduced this error.

A problem I'm still having though, but haven't been able to debug yet, is once I update the site, I'll always land on the fallback page when trying to reach the site for the first time. I need to manually edit the URL myself and reload, then no issues.

Still very much a work in progress here, but for now this plugin is not going on production for me as it seems unreliable and I don't know exactly what's wrong with it. 

What I'm gonna explore next time I have some free time on my hands is the installation / uninstallation of the SW as it's quite likely that the bug I'm experiencing lies there (could be due to the old SW not being uninstalled upon update) - that's just a theory at this point though.

**Comment by kakadiadarpan** [comment]
@natew It would be great if we could take a look at your repo

**Comment by liorbrauer** [comment]
I'm getting this as well, usually after deploying an updated version of my site, both on chrome and safari.

**Comment by joelhooks** [comment]
This happens to us occasionally as well.
