### ISSUE TITLE
dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by dumblole** [gatsbyjs/gatsby#8658]
## Summary
I was reading the react docs and found that `dangerouslySetInnerHTML` is not safe and is vulnerable to https://en.wikipedia.org/wiki/Cross-site_scripting . Should I be worried?

## Relevant information

This is just a question about how markdown is put into react templates.

**Comment by tsriram** [comment]
In general, inserting any HTML to your webpage is not safe especially when the HTML comes from user input. If you're talking specifically about using `dangerouslySetInnerHTML` with `gatsby-transform-remark`, I'd say you need not be worried if you're sure that the markdown files don't contain any malicious JavaScript.
