### ISSUE TITLE
v2 migration: can't see export statement from another .js

### ISSUE THREAD

**Issue by larryPersonal** [gatsbyjs/gatsby#8661]
## Summary

My project has problems finding exports from some .js files; the structure worked back in v1. The migration docs seem to say nothing about this. 

## Relevant information

One example of such a file is my i18n.js, located in /data/i18n.js, which has the content 

```
import { addLocaleData } from 'react-intl'
// Require specific locale data for locales in use
import en from 'react-intl/locale-data/en'
import 'intl/locale-data/jsonp/en'
import de from 'react-intl/locale-data/de'
import 'intl/locale-data/jsonp/de'

const locales = ['en', 'de'] // Current locales in use


// Add concatenated locale data
addLocaleData([...en, ...de])

export default {
	locales,
	defaultLocale: 'en',
}

```

In any other .js file, for example,  ./src/components/deskHeader.js, The import line is simply 

`
import { locales } from '../data/i18n'
`

This used to work in v1; however v2 instead gives a Warning

`export 'locales' was not found in '../data/i18n'`

Message during the compile process. Compile completes successfully, but the site shows nothing except multiple "missing object" in the console. i18n.js isn't the only file this happens; its happening for any class with an export, all of which have a similar layout.

Adding a .js qualifier to the import statement doesn't help; the export statement simply cannot be seen.

Is there something I missed?

### Environment (if relevant)

  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 9.5.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 61.0.1
    Safari: 11.1.1
  npmPackages:
    gatsby: ^2.0.12 => 2.0.12 
    gatsby-image: ^2.0.12 => 2.0.12 
    gatsby-plugin-google-analytics: ^2.0.6 => 2.0.6 
    gatsby-plugin-layout: ^1.0.2 => 1.0.2 
    gatsby-plugin-netlify: ^2.0.0 => 2.0.0 
    gatsby-plugin-netlify-headers: ^1.0.1 => 1.0.1 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-sharp: ^2.0.5 => 2.0.5 
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.1 
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.0 
    gatsby-source-contentful: ^2.0.1 => 2.0.1 
    gatsby-source-filesystem: ^2.0.1 => 2.0.1 
    gatsby-source-workable: ^1.1.1 => 1.1.1 
    gatsby-transformer-remark: ^2.1.4 => 2.1.4 
    gatsby-transformer-sharp: ^2.1.3 => 2.1.3 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by kakadiadarpan** [comment]
@larryPersonal could you provide a reproduction repo for this? That would make it much easier to diagnose this issue.

**Comment by larryPersonal** [comment]
Have created a quick and dirty example based on the hello-world project here. 

https://github.com/larryPersonal/gatsby-helloworld-fork

In this example, src/pages/index.js has no problems seeing the 'locales' export from src/data/i18n.js from the directory, but src/components/deskHeader.js cannot see the same export with the same import statement.
 
```
ℹ ｢wdm｣: Compiling...
 WARNING  Compiled with 3 warnings                                                                                                  18:34:15

Module Warning (from ./node_modules/eslint-loader/index.js):

/Users/cluk/tenx_clone/quick-clone/src/components/deskHeader.js
  2:10  warning  'Link' is defined but never used  no-unused-vars
  7:2   warning  Useless constructor               no-useless-constructor

✖ 2 problems (0 errors, 2 warnings)

Module Warning (from ./node_modules/eslint-loader/index.js):

/Users/cluk/tenx_clone/quick-clone/src/pages/index.js
  2:10  warning  'Link' is defined but never used        no-unused-vars
  3:10  warning  'locales' is defined but never used     no-unused-vars
  4:8   warning  'DeskHeader' is defined but never used  no-unused-vars

✖ 3 problems (0 errors, 3 warnings)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
 warning  in ./src/components/deskHeader.js

"export 'locales' was not found in '../data/i18n'
```

This project has warnings due to unused variables and empty constructors, the goal was to isolate the problem.

Clipboard as follows

```
  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 9.5.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 61.0.1
    Safari: 11.1.1
  npmPackages:
    gatsby: ^2.0.0 => 2.0.0 
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```

**Comment by kakadiadarpan** [comment]
@larryPersonal I'm not sure following is a good way of exporting data:
```js
export default {
	locales,
	defaultLocale: 'en',
}
```

In my opinion the proper way of exporting it would be:
```js
export const locales = `value`;
export const defaultLocale = `another-value`
```

Could you try that and check if that works for you?

**Comment by larryPersonal** [comment]
Thanks, exporting each variable separately worked - and as it turns out in the main project, the affected classes are the only ones that appeared as

```
const valueCollection = { var1: value, var2: value ... } 
export default valueCollection
```

Anything that looked like 

```
class aClass extends React.Component {
   ...
}
export default aClass
```

Does not seem to be affected.

I'm not entirely sure why its more advisable to export each and every non-class object separately - but I'll refactor accordingly.
