### ISSUE TITLE
Using Bootstrap-Loader to load relevant components from Bootstrap

### ISSUE THREAD

**Issue by wongsynee** [gatsbyjs/gatsby#8663]
## Summary
In our current project, we have Gatsby working alongside Bootstrap. The requirement is to use [Bootstrap-Loader](https://github.com/shakacode/bootstrap-loader) to only include the grid component from Bootstrap. 

## Relevant information
As per Bootstrap-Loader's documentation we are able to configure the loader as part of the Webpack configuration under the entry, example:
```
module.exports = function(env) {
  const publicPath = (() => {
    return '/'
  })()
  return {
    mode: devMode ? 'development' : 'production',
    entry: {
      'project-name': [
        `bootstrap-loader/lib/bootstrap.loader?extractStyles&configFilePath=${__dirname}/.bootstraprc!bootstrap-loader/no-op.js`,
        '@babel/polyfill',
        './src/project-name/index.tsx',
      ],
...
```

As per my understanding in order to modify the webpack configuration for Gatsby, it will be done through the `gatsby-node.js` file. However, I am unsure of how to **edit the entry** of the webpack configuration under `gatsby-node.js`.

Will that be done as part of `actions.setWebpackConfig` in `gatsby-node.js`?

Any guidance will be greatly appreciated. Thank you.

**Comment by kakadiadarpan** [comment]
@wongsynee Yes, you'll need to use `actions.setWebpackConfig` in `gatsby-node.js`

```
actions.setWebpackConfig({
    entry:{
        main: a.js,
        optional: b.js
    }
})
```

But it might not be a good idea to change the entry as the entry generated by `Gatsby` will be affected by that.

https://github.com/gatsbyjs/gatsby/blob/4be5cfdf5d6925f26f914518dfc51d53f979cd6d/packages/gatsby/src/utils/webpack.config.js#L142-L169

@pieh any suggestions?

**Comment by pieh** [comment]
What `bootstrap-loader` actually do? I'm honestly not sure how to fit this into gatsby

**Comment by wongsynee** [comment]
@pieh [bootstrap-loader](https://github.com/shakacode/bootstrap-loader) lets us configure which parts of Bootstrap to be loaded into the project via webpack, and that gives us a custom built of Bootstrap.

**Comment by pieh** [comment]
Right, but why does it need to modify webpack entry?
