### ISSUE TITLE
how to use variable Quary in Component

### ISSUE THREAD

**Issue by NavidGoalpure** [gatsbyjs/gatsby#8669]
hello i need use variable query in my component this is my query: 

```
.
.
.
> export default props => {
>   console.log('**props', props.match.team1);
>   return (
>     <StaticQuery
>       query={graphql`
>         query getTeam1Logo ($t: String) {
>           team1Logo: file(relativePath: { eq:${props.match.team1}}) {
>             ...fluidImage
>           }
>         }
>       `}
>       render={data => <MatchItem data={data} {...props} />}
>     />
>   );
> };
```

 i know that is wrong syntax and must use context in creapePage for variable query but my problem is that this is a simple component not a page. can you help me
 (i know that my english is trible . sorry)

**Comment by LeKoArts** [comment]
You need to make the query in your template (because you have access to context there) and then pass the result as a prop to your component.
