### ISSUE TITLE
How to Contribute to docs/www not consistent between website and readme

### ISSUE THREAD

**Issue by siakaramalegos** [gatsbyjs/gatsby#8676]
## Summary

Direct all contributing.md files to https://www.gatsbyjs.org/docs/how-to-contribute/ so that there is only one source of truth. This allows for both easier maintenance and fewer incorrect instructions. 

### Basic example

For example, https://www.gatsbyjs.org/docs/how-to-contribute/ says to run `gatsby develop` when contributing to documentation, but if the user has a globally installed version of the `gatsby-cli`, they will unintentionally be using the wrong version. The [readme in the `www`](https://github.com/gatsbyjs/gatsby/blob/master/www/README.md) folder states to run `yarn develop` instead, which is more correct.

### Motivation

One source of truth means both easier maintenance and fewer problems for contributors.

I can take a first pass at this for the docs/www portion.

**Comment by KyleAMathews** [comment]
>but if the user has a globally installed version of the gatsby-cli, they will unintentionally be using the wrong version

Not sure what you mean here?

**Comment by siakaramalegos** [comment]
@KyleAMathews if I run `gatsby develop`, it uses my globally installed version, but if I run `yarn develop`, it uses the project version

**Comment by mikelax** [comment]
@KyleAMathews using the `yarn develop` command will always ensure the command is run with the `gatsby` script installed in node_modules. This is compared to running `gatsby develop` which will use the gatsby script found in the user path. 

I think only two changes are needed for this issue:
1. Update the [command on this line in how to contribute](https://github.com/gatsbyjs/gatsby/blame/master/docs/docs/how-to-contribute.md#L79) to `yarn develop`
1. Add link in [www readme](https://github.com/gatsbyjs/gatsby-starter-hello-world) to point to the [contributing to the documentation](https://www.gatsbyjs.org/docs/how-to-contribute/#contributing-to-the-documentation) section for how to get started
