### ISSUE TITLE
[docs] Explain why we use Yarn in the contributing docs

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#8702]
We use Yarn for contributing to the Gatsby repo. We should write an explanation of why in "How to Contribute".

**Comment by sharynneazhar** [comment]
I can take a stab at this! 🙂 

Is there anything specific you want to add besides an explanation of Yarn is?

**Comment by pieh** [comment]
We use yarn [workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) feature that comes really handy for monorepos:
https://github.com/gatsbyjs/gatsby/blob/99e237ad3841872d8f879b6bba3ce27bf259b51f/package.json#L80-L82

**Comment by mikelax** [comment]
There are a few sections in the [tutorial part 0, from this section down](https://www.gatsbyjs.org/tutorial/part-zero/#-check-your-nodejs-installation) that discuss getting set up with npm. This should be updated to use yarn instead.

**Comment by DSchau** [comment]
@mikelax I think we want that to remain that way! This issue is rather with the "Contributing" section, in that we recommend yarn from a contributing back to Gatsby perspective.
