### ISSUE TITLE
[docs]: Clarify usage of gatsby-plugin-remove-trailing-slashes

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#8706]
## Description

In re: to #4836, there is some fair confusion as to _what_ gatsby-plugin-remove-trailing-slashes actually does. I think (most?) people tend to think it's used for rendering routes without a slash on the _server_ when in fact, it's primary use case is for tweaking routes client side and handling things like the `activeClassName` and `<Link to="/page-2">Page two</Link>` functionality re: trailing slashes.

## Further Detail

- Ideally, a PR to `gatsby-plugin-remove-trailing-slashes/README.md` clarifying the behavior of this plugin. See [this comment](https://github.com/gatsbyjs/gatsby/issues/4836#issuecomment-423739213) for more detail
- Additionally, consider adding info on "pretty URLs" e.g. [with Netlify](https://www.netlify.com/docs/redirects/#trailing-slash)

**Comment by dakebl** [comment]
I've attempted to address this via PR 8720. I hope it helps!

**Comment by DSchau** [comment]
@dakebl it definitely does :) Left you a comment over there!

**Comment by dakebl** [comment]
Hey @DSchau, I've updated the docs to mention both the Pretty URL feature and Netlify's default URL normalisation on redirects.

**Comment by dakebl** [comment]
Closing, as this has now been merged.
