### ISSUE TITLE
[feat]: add gatsby-plugin-cxs

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#8710]
## Summary

[CXS](https://github.com/cxs-css/cxs) is a great library for CSS in JS w/ React. Let's create a plugin so that others can get some SSR benefits and CSS hydration with Gatsby.

### Motivation

- We have a number of other plugins which implement similar functionality, e.g. [gatsby-plugin-emotion](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-emotion), [gatsby-plugin-styled-components](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-styled-components), etc.
- We don't want to prohibit anyone from using Gatsby because _their_ preferred styling solution isn't supported, and Gatsby is extremely pluggable to enable this :)

### General Approach

- Create `packages/gatsby-plugin-cxs` (see previously mentioned CSS in JS libraries for more info/boilerplate)
- Implement the [SSR API](https://github.com/cxs-css/cxs#staticserver-side-rendering) from Aphrodite
- PR and experience the ❤️ from all of those who use and like Cxs

**Comment by ctxhou** [comment]
Is this issue taken? If not, I would like to work on this 😄

**Comment by DSchau** [comment]
@ctxhou we'd love for you to take it if you're able! Looking forward to the PR, and let any of us @gatsbyjs/core know if we can help!

**Comment by tbaustin** [comment]
@ctxhou have you completed this or do you need help?

**Comment by amberleyromo** [comment]
Hi @ctxhou! Still working on this?

**Comment by ctxhou** [comment]
hey @amberleyromo, I've send the PR and wait for review 😄

**Comment by DSchau** [comment]
This was done in #8878. Thanks @ctxhou!
