### ISSUE TITLE
[feat]: add gatsby-transformer-asciidoc

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#8712]
## Summary

Gatsby is all about "bring your own content," and PDF is certainly a means of embedding useful data and content. Let's create a gatsby-transformer-asciidoc transformer plugin to enable usage of asciidoc files as a content source, and make them queryable with Gatsby's GraphQL layer.

### Motivation

- Lots of people like Markdown, but lots of people also like [asciidoc](http://asciidoc.org/), so let's make Gatsby as flexible as possible!
- We'll want to transform Asciidoc to something that GraphQL can query against (e.g. HTML) so a package like [asciidoctor](https://asciidoctor.org/docs/asciidoctor.js/) will be _really_ helpful!

### Further Detail

Consider looking at existing transformer plugins for inspiration, e.g. [gatsby-transformer-json](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-json), [gatsby-transformer-csv](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-csv), [gatsby-transformer-remark](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-remark) etc.

**Comment by garetmckinley** [comment]
Is it cool if I claim this? Not sure if I'll have time today to work on it, but I can definitely get it knocked out before the weekend.

**Comment by DSchau** [comment]
@garetmckinley of course! We can assign it to you for now, but if anything changes, feel free to remove yourself!

**Comment by garetmckinley** [comment]
So I just found out that I'm starting a new job tomorrow, so I'm not sure how much time I'll have to work on this. If somebody else wants to take this issue, have at it. I'll have some time to work on it next weekend, so if nobody else claims it, I'll try and get it done then

**Comment by DSchau** [comment]
@garetmckinley not a problem at all. Congrats!

**Comment by derekkramer** [comment]
@DSchau Alright if I take this one?

**Comment by DSchau** [comment]
@derekkramer that'd be great!

**Comment by DSchau** [comment]
If it helps, looks like we already have the start of a plugin in [this repo](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-asciidoc)

**Comment by derekkramer** [comment]
@DSchau Excellent, thanks! I'll get working on it tonight.

**Comment by amberleyromo** [comment]
Hey @derekkramer! Still interested in working on this?

**Comment by derekkramer** [comment]
@amberleyromo Yes I'm actually finished, just testing the final plugin with NPM tonight then submitting my pull request

**Comment by derekkramer** [comment]
I've been running into some bizarre errors when trying to use my newly created `gatsby-transformer-asciidoc` plugin in a development environment. Been trying to debug for a couple days. If someone else wants to take a stab at it while I try to work out the compile error, I'd say go ahead.

**Comment by DSchau** [comment]
@derekkramer is the error anything we can help with? We'd love to assist while you're able! Feel free to open a PR and mark it WIP so we can collaborate on it, as well!

**Comment by RedHoodJT1988** [comment]
I would like to try to take a stab at this if it is still open.

**Comment by LekoArts** [comment]
@RedHoodJT1988 https://github.com/gatsbyjs/gatsby/pull/8885
You can finish the PR if you want 👍

**Comment by jtanguy** [comment]
The PR #8885 has been merged, I think this issue can be closed

**Comment by LekoArts** [comment]
Yeah!
