### ISSUE TITLE
[feat]: add gatsby-source-sql

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#8714]
## Summary

It'd be awesome to be able to (at build time!) inject content from a SQL database, just like we do for other source types, e.g. filesystem, Contentful, etc.

### Motivation

- People may have useful data stored away in SQL that could be exposed to enable helpful things, e.g. documentation, useful data, etc.
- The plugin will need to connect to a SQL database, and then pre-load queries (e.g. pass the SQL queries directly to the plugin?)

### Further Detail

The general idea is that the source plugin will need to be able to connect to a SQL database (MySQL, MSSQL, ... ?; happy to start small and grow it in the future!) and query that data to inject into the GraphQL content layer for further processing via Gatsby.

Consider [mysql](https://github.com/mysqljs/mysql), [mssql](https://www.npmjs.com/package/mssql) for various means to inject data

See other source plugins for more info on how to build this out, e.g. [gatsby-source-contentful](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-contentful), [gatsby-source-wordpress](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-wordpress), etc.

**Comment by daubaris** [comment]
me me me! Could you also direct on where to start? :)

**Comment by DSchau** [comment]
@daubaris 👋 Absolutely! So I'd recommend checking out one of the source plugins I linked, and kinda re-tracing from there!

So high level, this is what this will look like:

- Create/copy a directory in packages/gatsby-source-sql
- Implement the appropriate Node APIs (probably `sourceNodes`)
- Open up a PR (early/WIP is fine, just mark it as such!) and we'll be happy to give some feedback

If you're interested, we'd love to help out with a pairing session, as well. Sign up for those [here](https://calendly.com/gatsbyjs/pair-programming)

And let me know if I can help with this further :)

**Comment by garetmckinley** [comment]
If I were to suggest sqlite support as well, would that be lumped into this plugin or it's own thing?

**Comment by DSchau** [comment]
@garetmckinley good question! I'm not sure how to best resolve that complexity to be honest with you.

_Ideally_ there'd be one shared sql plugin, but the more I think about it, I'm not sure how tenable that is because the _engine_ will have to change between MySQL, mssql, SQLLite, etc.

So we may be able to introduce some shared helpers, but I think this plugin may take additional plugins, and those plugins should implement some API perhaps?

**Comment by DSchau** [comment]
(very similar to gatsby-transformer-remark if you're familiar!)

**Comment by DSchau** [comment]
@garetmckinley that would be so great! Stay tuned 👀

**Comment by oorestisime** [comment]
Once this progresses i d like to look for some postgres integration as well.

**Comment by koreyboone** [comment]
Is this claimed?

**Comment by mrfunnyshoes** [comment]
Is this open? If so I would like to work on it if someone's not doing it already.

**Comment by DSchau** [comment]
@mrfunnyshoes yep! Feel free to tackle this, we'd love to see this!

**Comment by mrfunnyshoes** [comment]
Thanks! Do you guys think using [knex](https://knexjs.org/) be overkill for this task?

**Comment by DSchau** [comment]
@mrfunnyshoes. Whoa, I’ve never heard of that! That seems like a nice, flexible option!

All for it!

**Comment by malcolm-kee** [comment]
I just implemented something similar, but for mysql only. It is just a thin wrapper around the library `mysql`. See https://github.com/malcolm-kee/gatsby-source-mysql

**Comment by DSchau** [comment]
@malcolm-kee great! I think there's still some value in what @mrfunnyshoes proposed, so perhaps we can work on integrating `gatsby-source-sql` into _this_ repo whereas yours can live under your own name!

Looks great, though - happy to see more plugins relating to this! Nice work!

**Comment by malcolm-kee** [comment]
@dschau agree! That is much useful than only support mysql. Just share as another  reference 😁

**Comment by mrfunnyshoes** [comment]
Hey guys! I've got a working version [here](https://github.com/mrfunnyshoes/gatsby-source-sql). Let me know what you think. I'm actually new to contributing to a FOSS project.

PS: I think It would be nice to nest the resulting data inside the `fieldName` for the query, much in the way [`gatsby-source-graphql`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-graphql) does.

**Comment by mrfunnyshoes** [comment]
Thanks @malcolm-kee, will look into your suggestions!

**Comment by LekoArts** [comment]
https://github.com/gatsbyjs/gatsby/pull/8875

There’s is already this PR

**Comment by DSchau** [comment]
@malcolm-kee we'd love to have this plugin in the official Gatsby repository. I haven't taken a super close look at the code, but the functionality you're able to build in (in a database agnostic way) looks _perfect_.

Perhaps we schedule some time next week, and I can walk you through how we'd get this PR'd up to the official Gatsby monorepo? Feel free to [use my Calendly](https://calendly.com/dschau) and we can get this up and running.

Again--thank you! This looks great!

**Comment by malcolm-kee** [comment]
@DSchau are you intends to message @mrfunnyshoes for `gatsby-source-sql`?

**Comment by mrfunnyshoes** [comment]
Hey guys @DSchau, @malcolm-kee! Yes, I think we could start working on the PR. Should I publish this to npm already, or will that be part of adding it to the monorepo?

**Comment by LekoArts** [comment]
@mrfunnyshoes Hi! So is your plugin ready to go for a PR against Gatsby's repo? If so we should close this PR https://github.com/gatsbyjs/gatsby/pull/8875 and you can open up yours. Please let us know if you need help with the PR.

I don't think you need to publish to npm as the monorepo will handle this once your PR is merged 👍

**Comment by mrfunnyshoes** [comment]
Thanks @LekoArts! I _think_ the plugin is ready for PR, I'm not completely sure how to proceed with it though. I'll start by following [these instructions](https://www.gatsbyjs.org/docs/how-to-contribute/) and come here with any doubts.

**Comment by LekoArts** [comment]
If you have problems you can also join our Discord (https://discord.gg/jUFVxtB) and ask there 👍 (Or open the PR and we'll talk in the PR)

**Comment by mrfunnyshoes** [comment]
Thanks @LekoArts, I submitted a PR

**Comment by m-allanson** [comment]
Reopening as there is a related PR open for this.

**Comment by sidharthachatterjee** [comment]
Closing this since https://github.com/gatsbyjs/gatsby/pull/11100#issuecomment-486755549

Keep an eye out for @mrfunnyshoes's fantastic plugin that will enable this!

**Comment by muescha** [comment]
FYI:
if someone search for this - the plugin is here available:

https://github.com/edgarrmondragon/gatsby-source-sql
