### ISSUE TITLE
Content migration - fill out "Gatsby i18n" stub article

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#8716]
## Issue Context

This issue is part of the content migration project (#8103), which is meant to take existing content and repurpose it so it's easier to find in the docs.

### Motivation

We are doing this because many people have written excellent content that we want to canonize and maintain so more people can find it and benefit from it.

## Steps to resolve this issue

1. Read the Style Guide and follow it in order for your PR to be accepted. Pay special attention to the templates. 
- Style Guide: https://www.gatsbyjs.org/docs/gatsby-style-guide/
- Docs Templates: https://www.gatsbyjs.org/docs/templates/
- Example of a guide to imitate: https://www.gatsbyjs.org/docs/deploying-to-s3-cloudfront

2. Create a guide titled "Gatsby i18n" and copy and paste this section of a blog into the doc: https://www.gatsbyjs.org/blog/2017-10-17-building-i18n-with-gatsby/#choosing-a-package

3. Make sure you describe 3 options for doing i18n:
gatsby-plugin-i18n: https://github.com/angeloocana/gatsby-plugin-i18n
react-intl: https://github.com/yahoo/react-intl
react-i18next: https://github.com/i18next/react-i18next/

4. Include these references in the "Other Resources" section at the bottom:
https://www.gatsbyjs.org/blog/2017-10-17-building-i18n-with-gatsby/
https://www.gatsbyjs.org/blog/2018-04-27-building-eviction-free-nyc-with-gatsbyjs-and-contentful/
https://www.gatsbyjs.org/packages/gatsby-plugin-i18n/?=i18
https://www.gatsbyjs.org/blog/tags/i-18-n/

**Comment by audoralc** [comment]
I'd be happy to work on this. 👍

**Comment by shannonbux** [comment]
@audoralc great! Once you create the PR, just mention in the first comment that it "closes #8716" :)

Also, I think the title "Gatsby i18n" isn't necessarily the best title. Any ideas for how to improve that are welcome!

**Comment by audoralc** [comment]
@shannonbux How about something like "International content support"?

Also which subheading would be most appropriate? "Adding website functionality"?

**Comment by shannonbux** [comment]
Ok, how about "Internationalization" as the title. This is common in other docs, like Drupal (just did a google search). And since i18n will be in the body of the guide, google searches for i18n will still find the doc.

And can you clarify your question about the subheading? Thanks!

**Comment by amberleyromo** [comment]
Hi @audoralc! Are you still interested in working on this?

**Comment by amberleyromo** [comment]
Awesome, thanks @audoralc! (And thanks for the username spelling correction, lol!)

**Comment by LekoArts** [comment]
@audoralc Hi 👋 Did you PR your document? 😊

**Comment by audoralc** [comment]
@LekoArts I have a draft that is complete, but I'm not sure is detailed enough. Should I go ahead and PR it anyway?

**Comment by LekoArts** [comment]
@audoralc Sure, go ahead. We can work with the draft then and help you finish it.

**Comment by audoralc** [comment]
Hi all, sorry this took so long - I've made a PR #10902
