### ISSUE TITLE
Where to place Sitemap?

### ISSUE THREAD

**Issue by vianneylancres** [gatsbyjs/gatsby#872]
Hey Guys!

First off - thank you for gatsbyJs! I joined a project where they are using gatsby and I got used to it pretty fast.

Now I was trying to make use of a sitemap. I already created a sitemap.xml file, that is stored in /pages. When I go to Google's Search Console and try to add the sitemap to my entity, I can't seem to find the right path.

I tried:
xyz.com/sitemap.xml
xyz.com/pages/sitemap.xml
xyz.com/public/sitemap.xml

I even created a "public" folder manually and added the sitemap to that folder which did not work either. Am I missing some permissions or settings somewhere?

Can you please help a not-so-much-of-a-developer-guy out?
Thank you

**Comment by KyleAMathews** [comment]
How do you build and deploy your site to production right now?

**Comment by emilyaviva** [comment]
The way I do this kind of thing, as a data point, is to copy the file to its destination in `/public` as part of a post-build script in my `gatsby-node.js`. As an example, here's that file from [a Gatsby starter](https://github.com/emilyaviva/gatsby-starter-blog-multiple-authors) I made:

```
var fs = require('fs-extra')
var path = require('path')
var buildFeed = require('./scripts/buildFeed')

exports.postBuild = (pages, callback) => {
  console.log('Building Atom feed')
  // Build RSS feed.
  buildFeed(pages, callback)
  // Copy favicon.
  fs.copySync(path.join(__dirname, '/favicon'), path.join(__dirname, '/public/favicon'))
  // Next callback.
  callback()
}
```

**Comment by hugmanrique** [comment]
It would be neat to have a `static` directory inside of `src` which autocopies everything, a webpack filter could be used to do this automatically.

**Comment by jbolda** [comment]
@vianneylancres, looks like you have a few solutions. This will also be easier in the 1.0 branch. Closing for now unless you have other questions.
