### ISSUE TITLE
Content migration - fill out "Component CSS" stub article in the docs

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#8726]
## Issue Context

This issue is part of the content migration project (#8103), which is meant to take existing content and repurpose it so it's easier to find in the docs.

### Motivation

We are doing this because many people have written excellent content that we want to canonize and maintain so more people can find it and benefit from it.

## Steps to resolve this issue

1. Read the Style Guide and follow it in order for your PR to be accepted. Pay special attention to the templates. 
- Style Guide: https://www.gatsbyjs.org/docs/gatsby-style-guide/
- Docs Templates: https://www.gatsbyjs.org/docs/templates/
- Example of a guide to imitate: https://www.gatsbyjs.org/docs/deploying-to-s3-cloudfront

2. Edit the "Component CSS" stub article by copying and pasting this section of a tutorial into the doc: https://www.gatsbyjs.org/tutorial/part-two/#component-css

3. Make sure you adjust the content to follow the format listed in these resources:
- Docs Templates: https://www.gatsbyjs.org/docs/templates/
- Example of a guide to imitate: https://www.gatsbyjs.org/docs/deploying-to-s3-cloudfront

**Comment by dumblole** [comment]
Currently working on this.

**Comment by amberleyromo** [comment]
Closed in #8734
