### ISSUE TITLE
Content migration - fill out "Creating slugs for pages" stub article

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#8727]
## Issue Context

This issue is part of the content migration project (#8103), which is meant to take existing content and repurpose it so it's easier to find in the docs.

### Motivation

We are doing this because many people have written excellent content that we want to canonize and maintain so more people can find it and benefit from it.

## Steps to resolve this issue

1. Read the Style Guide and follow it in order for your PR to be accepted. Pay special attention to the templates. 
- Style Guide: https://www.gatsbyjs.org/docs/gatsby-style-guide/
- Docs Templates: https://www.gatsbyjs.org/docs/templates/
- Example of a guide to imitate: https://www.gatsbyjs.org/docs/deploying-to-s3-cloudfront

2. Edit the "Creating slugs for pages" stub article by copying and pasting this section of a tutorial into the doc: https://www.gatsbyjs.org/tutorial/part-seven/#creating-slugs-for-pages

3. Make sure you adjust the content to follow the format listed in these resources:
- Docs Templates: https://www.gatsbyjs.org/docs/templates/
- Example of a guide to imitate: https://www.gatsbyjs.org/docs/deploying-to-s3-cloudfront

**Comment by dumblole** [comment]
Sorry, but which tutorial?

**Comment by dumblole** [comment]
Oh! My bad. I see it now

**Comment by shannonbux** [comment]
oh man @dumblole thanks for volunteering! We just started using a `hacktoberfest - claimed` label for issues so it ought to make it easier to tell if an issue is available or not!

**Comment by rahulkumaran** [comment]
@shannonbux I'd like to take this up if the person who has claimed this hasn't made a PR

**Comment by shannonbux** [comment]
@rahulkumaran Hi! The PR got merged and this issue didn't get closed until now! Apologies and thanks for offering to help! Have you checked #8103 to see if there is anything else you'd like to contribute to there?
