### ISSUE TITLE
Content migration - fill out "Sourcing from the filesystem" stub article

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#8730]
## Issue Context

This issue is part of the content migration project (#8103), which is meant to take existing content and repurpose it so it's easier to find in the docs.

### Motivation

We are doing this because many people have written excellent content that we want to canonize and maintain so more people can find it and benefit from it.

## Steps to resolve this issue

1. Read the Style Guide and follow it in order for your PR to be accepted. Pay special attention to the templates. 
- Style Guide: https://www.gatsbyjs.org/docs/gatsby-style-guide/
- Docs Templates: https://www.gatsbyjs.org/docs/templates/
- Example of a guide to imitate: https://www.gatsbyjs.org/docs/deploying-to-s3-cloudfront

2. Edit the "Sourcing from the Filesystem" stub article and and paste relevant sections of this tutorial into the doc: https://www.gatsbyjs.org/tutorial/part-five/#source-plugins

Make sure you adjust the content to follow the format listed in these resources:
- Docs Templates: https://www.gatsbyjs.org/docs/templates/
- Example of a guide to imitate: https://www.gatsbyjs.org/docs/deploying-to-s3-cloudfront

(Use the resources listed below to write more if needed!)

3. Include these references in the "Other Resources" section at the bottom:
https://www.gatsbyjs.org/packages/gatsby-source-filesystem/?=gatsby-source-
https://www.gatsbyjs.org/starter-showcase/?d=gatsby-source-filesystem
https://www.gatsbyjs.org/packages/gatsby-source-filesystem/?=gatsby-source-

**Comment by caseychien** [comment]
Hi! Can I work on this?

**Comment by shannonbux** [comment]
Closed by #8777
