### ISSUE TITLE
Content migration - fill out "Sourcing from Contentful" stub article

### ISSUE THREAD

**Issue by amberleyromo** [gatsbyjs/gatsby#8741]
## Issue Context

This issue is part of the content migration project (#8103), which is meant to take existing content and repurpose it so it's easier to find in the docs.

### Motivation

We are doing this because many people have written excellent content that we want to canonize and maintain so more people can find it and benefit from it.

## Steps to resolve this issue

1. Read the Style Guide and follow it in order for your PR to be accepted. Pay special attention to the templates. 
- Style Guide: https://www.gatsbyjs.org/docs/gatsby-style-guide/
- Docs Templates: https://www.gatsbyjs.org/docs/templates/
- Example of a guide to imitate: https://www.gatsbyjs.org/docs/deploying-to-s3-cloudfront

2. Edit the "Sourcing from Contentful" stub article by copying and pasting the relevant parts of this blog post: https://www.gatsbyjs.org/blog/2018-1-25-building-a-site-with-react-and-contentful/#what-is-contentful-why-choose-it

3. Make sure you adjust the content to follow the format listed in these resources:
- Docs Templates: https://www.gatsbyjs.org/docs/templates/
- Example of a guide to imitate: https://www.gatsbyjs.org/docs/deploying-to-s3-cloudfront

4. Use these references to write more if needed:
- https://github.com/gatsbyjs/gatsby/tree/master/examples/using-contentful
- https://www.gatsbyjs.org/packages/gatsby-source-drupal/?=contentful
- https://www.gatsbyjs.org/starters/?s=contentful
- https://www.gatsbyjs.org/blog/tags/contentful/
- LevelUp Pro Tuts: https://www.leveluptutorials.com/tutorials/pro-gatsby
  - #21 Contentful with Gatsby
  - #22 Generating Pages from Contentful
  - #23 Auto-updating with Contentful and Netlify

5. Remove the asterisk from the "Sourcing from Contentful" link in the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) (showing that it's no longer a stub).

**Comment by alejandronanez** [comment]
Hello!

I'd like to give this a shot!

Let me know if that would be possible, thanks a lot! :)

**Comment by amberleyromo** [comment]
@alejandronanez go for it!

If you want a model for this type of content, Sourcing from WordPress and Sourcing from Drupal were just merged recently:
- https://www.gatsbyjs.org/docs/sourcing-from-wordpress/
- https://www.gatsbyjs.org/docs/sourcing-from-drupal/

**Comment by alejandronanez** [comment]
Awesome, I’ll take a look to those resources and will ping you if I need any more help!
