### ISSUE TITLE
Content migration - fill out "Sourcing from WordPress" stub article

### ISSUE THREAD

**Issue by amberleyromo** [gatsbyjs/gatsby#8742]
## Issue Context

This issue is part of the content migration project (#8103), which is meant to take existing content and repurpose it so it's easier to find in the docs.

### Motivation

We are doing this because many people have written excellent content that we want to canonize and maintain so more people can find it and benefit from it.

## Steps to resolve this issue

1. Read the Style Guide and follow it in order for your PR to be accepted. Pay special attention to the templates. 
- Style Guide: https://www.gatsbyjs.org/docs/gatsby-style-guide/
- Docs Templates: https://www.gatsbyjs.org/docs/templates/
- Example of a guide to imitate: https://www.gatsbyjs.org/docs/deploying-to-s3-cloudfront

2. Edit the "Sourcing from WordPress" stub article by copying and pasting the relevant parts of this blog post: https://www.gatsbyjs.org/blog/2018-01-22-getting-started-gatsby-and-wordpress/

3. Make sure you adjust the content to follow the format listed in these resources:
- Docs Templates: https://www.gatsbyjs.org/docs/templates/
- Example of a guide to imitate: https://www.gatsbyjs.org/docs/deploying-to-s3-cloudfront

4. Use these references to write more if needed (please link to credit any external references):
- https://github.com/gatsbyjs/gatsby/tree/master/examples/using-wordpress
- https://www.gatsbyjs.org/packages/gatsby-source-drupal/?=wordpress
- https://www.gatsbyjs.org/packages/gatsby-source-wordpress/?=wordpress
- https://www.gatsbyjs.org/starters/?s=wordpress
- https://www.gatsbyjs.org/blog/tags/wordpress/
- Watch & Learn Tutorials GatsbyJS + WordPress: https://www.youtube.com/watch?v=etii9yp1J6s&list=PLUBR53Dw-Ef8fe-8xJXtMpd1-uhgd2Qa6
- https://jeremey.blog/gatsby-photo/
- https://codebushi.com/wordpress-to-gatsbyjs/
- https://medium.freecodecamp.org/how-to-build-a-react-and-gatsby-powered-blog-in-about-10-minutes-625c35c06481

5. Remove the asterisk from the "Sourcing from WordPress" link in the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) (showing that it's no longer a stub).

**Comment by amberleyromo** [comment]
@d-ivashchuk great! thank you!

**Comment by shannonbux** [comment]
@amberleyromo any idea why this issue didn't automatically close when the PR got merged?

**Comment by amberleyromo** [comment]
@shannonbux Because it either wasn't connected on Zenhub, or it didn't include "closes #8742". Closing now!
