### ISSUE TITLE
Extend markdown plugin to enable MathJax support.

### ISSUE THREAD

**Issue by Piyush3dB** [gatsbyjs/gatsby#875]
The [extending-markdown-syntax-with-plugins](https://github.com/gatsbyjs/gatsby#extending-markdown-syntax-with-plugins) section describes how one can extend the markdown loader to parse, say, MathJax.

I quote part of the section...

> If you want to do this you will need to use a custom markdown loader. You can copy the one provided in the default starter [here](https://github.com/gatsbyjs/gatsby-starter-default/blob/master/loaders/markdown-loader/index.js). Add the relevant packages to your dependencies, including the markdown-it plugins that you want to use and enable them with md.use(require('markdown-it-plugin-name')) within the markdown loader file.

But the link pointed to by 'here' i.e.

https://github.com/gatsbyjs/gatsby-starter-default/blob/master/loaders/markdown-loader/index.js

is broken.

Which is the best example I can follow to extend markdown plugins so that I can enable MathJax support?

I have looked at issue #134 which seems to be a hack and not currently the recommended way of doing it.  Also, I'd like to be able to just follow the instructions on the [README](https://github.com/gatsbyjs/gatsby) page to achieve this.  I'm a C++ dev and this JS stack is very foreign to me so any guidance would be very much appreciated!

**Comment by KyleAMathews** [comment]
Hey so sorry! The old default starter got moved recently to one named "kitchen sink" and I forgot 
to update that link. https ://github.com/gatsbyjs/gatsby-starter-kitchen-sink/blob/master/loaders/markdown-loader/index.js

Could you edit that link in the markdown to point to the new location.

**Comment by Piyush3dB** [comment]
Awesome thanks! I have a partially working solution at [https://github.com/gatsbyjs/gatsby-starter-kitchen-sink/pull/1](https://github.com/gatsbyjs/gatsby-starter-kitchen-sink/pull/1).  I'm intending to get this fixed and submit it to the kitchen sink demo.
