### ISSUE TITLE
[gatsby-offline-plugin] Variable lost the value in prod, but has in dev

### ISSUE THREAD

**Issue by podabed** [gatsbyjs/gatsby#8751]
## Description

The variable has value on dev (gatsby develop) and undefined on prod (gatsby build). This error only with enabled offline plugin.
This message while build:
```
error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND


  53 |     location: { pathname },
  54 |     i18nMessages,
> 55 |     i18nMessages: { pageNames }
     |                     ^
  56 |   } = props;
  57 |   const langKey = getCurrentLangKey(langs, defaultLangKey, pathname);
  58 |   const homeLink = `/${langKey}/`;


  WebpackError: Cannot read property 'pageNames' of undefined
  
  - index.tsx:55 IndexLayout
    src/layouts/index.tsx:55:21
  
  - react-dom-server.node.production.min.js:28 d
    ~/react-dom/cjs/react-dom-server.node.production.min.js:28:482
  
  - react-dom-server.node.production.min.js:30 ua
    ~/react-dom/cjs/react-dom-server.node.production.min.js:30:494
  
  - react-dom-server.node.production.min.js:35 a.render
    ~/react-dom/cjs/react-dom-server.node.production.min.js:35:46
  
  - react-dom-server.node.production.min.js:34 a.read
    ~/react-dom/cjs/react-dom-server.node.production.min.js:34:246
  
  - react-dom-server.node.production.min.js:45 renderToString
    ~/react-dom/cjs/react-dom-server.node.production.min.js:45:1
  
  - static-entry.js:126 module.exports
    .cache/static-entry.js:126:31
  
  - static-entry.js:99 Function.Promise.fromNode.Promise.fromCallback
    .cache/static-entry.js:99:20
```
And this while debugging html build:
```
Error: Module build failed: SyntaxError: Unexpected token / in JSON at positio  n 0
  
  - JSON.parse
  
  - index.js:4 Object.module.exports
    [caddysmellsliketrees.github.io]/[json-loader]/index.js:4:49
  
  - @ ./.cache/sync-requires.js 79:44-151
```

### Steps to reproduce
1. Clone this repo: https://github.com/podabed/caddysmellsliketrees.github.io/tree/new
2. Install deps.
3. Run start script. Everything's good. Run startProd - pageNames is undefined.

### Expected result

Correct building on prod.

### Actual result

pageNames variable is undefined while prod building.

### Environment

  System:
    OS: Linux 4.15 Ubuntu 16.04.5 LTS (Xenial Xerus)
    CPU: x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 8.11.4 - ~/.nvm/versions/node/v8.11.4/bin/node
    Yarn: 1.10.1 - ~/.nvm/versions/node/v8.11.4/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.11.4/bin/npm
  Browsers:
    Firefox: 62.0
  npmPackages:
    gatsby: ^1.9.278 => 1.9.278 
    gatsby-link: ^1.6.46 => 1.6.46 
    gatsby-plugin-i18n: ^0.4.2 => 0.4.2 
    gatsby-plugin-manifest: ^1.0.27 => 1.0.27 
    gatsby-plugin-offline: ^1.0.18 => 1.0.18 
    gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11 
    gatsby-plugin-sass: ^1.0.26 => 1.0.26 
    gatsby-plugin-sitemap: ^1.2.25 => 1.2.25 
    gatsby-plugin-svgr: ^1.0.1 => 1.0.1 
    gatsby-plugin-typescript: ^1.4.20 => 1.4.20 
    gatsby-source-filesystem: ^1.5.39 => 1.5.39 
    gatsby-transformer-remark: ^1.7.44 => 1.7.44 
  npmGlobalPackages:
    gatsby-cli: 2.4.2

**Comment by pieh** [comment]
Where is i18nMessages prop coming from?

**Comment by podabed** [comment]
From localized layouts, like https://github.com/podabed/caddysmellsliketrees.github.io/blob/new/src/layouts/en.tsx or https://github.com/podabed/caddysmellsliketrees.github.io/blob/new/src/layouts/ru.tsx

**Comment by podabed** [comment]
I've resolved this problem. Just check option 'useLangKeyLayout: false' in gatsby-plugin-i18n options and start using one layout for every language. So, using one layout resolve this problem. But the reason is unknown.
