### ISSUE TITLE
[starter library] Gatsby starter page crashes on site

### ISSUE THREAD

**Issue by rgbkrk** [gatsbyjs/gatsby#8757]
## Description

Loading everything on the Gatsby starter page listing (https://www.gatsbyjs.org/starters/) crashes, ends up with a white screen.

![load more and crash](https://user-images.githubusercontent.com/836375/46416657-dd238f00-c6dc-11e8-952c-45891dafcd78.gif)

### Steps to reproduce

1. Open https://www.gatsbyjs.org/starters/
2. Scroll to bottom, click "Load More"
3. Repeat Step 2 until crash (~4 times)

### Expected result

All content to be loaded (and no more ability to load more content). At the very least though, an error boundary implemented at the page level that would make reporting this easier.

### Actual result

![screen shot 2018-10-03 at 7 11 13 am](https://user-images.githubusercontent.com/836375/46416307-19a2bb00-c6dc-11e8-90de-daf79f73371c.png)

**Comment by rgbkrk** [comment]
Ran devtools again and pre-emptively caught the exception. Looks like this is the bad data:

```
starter = {id: "7494ca33-38f1-5185-9cd3-3d9d3e9d5cee", fields: null, url: "http://gatsbyjs.github.io/gatsby-starter-default/", repo: "https://github.com/gatsbyjs/gatsby-starter-default", description: "official default", …}
```

![screen shot 2018-10-03 at 7 37 13 am](https://user-images.githubusercontent.com/836375/46417751-2bd22880-c6df-11e8-8e1b-36efd6f126e9.png)

**Comment by chmac** [comment]
It looks like this is a slightly inconsistent problem. In the [current starter list](https://www.gatsbyjs.org/static/d/304/path---starters-a-58-958-ap6IwuUtyp53vIlEVBGEoX6MgqA.json) every starter except the last one in the list has a `starterShowcase` value.

Reading the code that generates these fields, it looks like the field should always be created. It's not clear to me how a starter gets into the list without having the `starterShowcase` field added.

https://github.com/gatsbyjs/gatsby/blob/b5cb862f686dca3cf261ce72ede453ae800efc5c/www/gatsby-node.js#L447-L561

**Comment by amberleyromo** [comment]
Hi @chmac -- it's not clear to me either. If you want to take a look at the current PR to address this issue, feel free -- #8763

I'm not sure why it's happening, part of that PR is just a stopgap for the problem.
