### ISSUE TITLE
Gatsby Component Library

### ISSUE THREAD

**Issue by cardiv** [gatsbyjs/gatsby#8760]
There are plenty of open source component libraries 📚for React. But in using them, I have some concerns about performance and Gatsby-related stuff:

1. Most of these components are packed with features which could result in performance issues.
2. Gatsby provides some features that could be difficult to use with these libraries – like the `Link` and `Img` components.

Also, not all libraries are good for web design. Some specialize for mobile 📱, some for desktop 💻 apps. I rarely see a mobile first approach.

**Conclusion:** I would love to see a component library that is designed with Gatsby in mind. Performant, minimal, mobile first (responsive) components that are using the full blown power 💪of Gatsby.

I think the Gatsby community is capable of producing one of the best web-centric component libraries. Just like the best static site generator out there. 😉And this library could lead to a rapid growth of Gatsby and it's members. _What do you think?_ 🤔

**Comment by cardiv** [comment]
@LeKoArts I think of components every website needs. This can be a simple button or a Carousel like Slick – but with support for Gatsby-related features.

This could increase the adoption of Gatsby since new developers could easily start building their site without deciding which library to use (mental friction) or building their own components.

**Comment by DSchau** [comment]
@cardiv I like what you're thinking! But that said, I think one of the _key_ benefits of Gatsby is that it's _just_ React! So by making something Gatsby specific, we've kinda lessened on the promise of that original value statement. So you mention carousel--I think we want to leverage the community here which is so crucial in React. [Nuka Carousel](https://github.com/FormidableLabs/nuka-carousel) is one I've reached for regularly. Components that require Gatsby specific enhancements (e.g. let's imagine passing a Gatsby-image in here) should _just_ work if they're composable and provide a solid API!

As far as Gatsby specific components (you mention Link, Image, etc.) we're all for those! Components that benefit _every_ Gatsby site and that we can include in core or make easily available--and that tie into Gatsby things (image processing, routing, etc.) make perfect sense. If there are more examples of areas we could be missing on that, let us know and we'll happily accept PRs.

**Comment by cardiv** [comment]
I will try the [Antd](https://github.com/ant-design/ant-design) route now.
Looks like a really cool component library.

Let's see how it goes. Thanks for the answers.

**Comment by liliedelamotte** [comment]
@cardiv, did Antd seem to work out for you? I'm wondering the same as your initial question.
