### ISSUE TITLE
styled-components and gatsby-plugin-layout together causes weird behaviours

### ISSUE THREAD

**Issue by marcneander** [gatsbyjs/gatsby#8771]
## Description

I've been sitting for a couple of hours now trying to wrap my head around this bug I'm experiencing. I'm using `styled-components` and `gatsby-plugin-layout`. In my Layout component I have my global styles where I load my fonts.

However when building and serving my gatsby app, my fonts and index page chunk is loaded twice. Causing a flicker.

Removing `gatsby-plugin-layout` solved the problem but I need it for routing animation and performance when using `styled-components`.

Downgrading `styled-components` to v3 prevents fonts for being loaded twice onload. But when hovering over "View Profile" button, fonts are loaded again and causes same flickering.

Seems to only happen on index route weirdly enough.

### Steps to reproduce
Clone https://github.com/marcneander/marcneander.se
`yarn install && yarn build && yarn serve`

See my fonts and index chunk being loaded twice.

### Environment
```
System:
    OS: macOS 10.14.1
    CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.10.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 62.0
    Safari: 12.0.1
  npmPackages:
    gatsby: 2.0.18 => 2.0.18
    gatsby-plugin-layout: 1.0.3 => 1.0.3
    gatsby-plugin-offline: 2.0.5 => 2.0.5
    gatsby-plugin-react-helmet: 3.0.0 => 3.0.0
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.0
```

**Comment by kakadiadarpan** [comment]
@marcneander I followed the steps that you provided. But couldn't find fonts or index page chunk loading twice. Please refer screenshots below:

Fonts:
<img width="1581" alt="screen shot 2018-10-04 at 12 58 00 pm" src="https://user-images.githubusercontent.com/10805593/46459034-5a322f80-c7d5-11e8-985f-893290fe5c8b.png">

JS:
<img width="1586" alt="screen shot 2018-10-04 at 12 58 22 pm" src="https://user-images.githubusercontent.com/10805593/46459046-60c0a700-c7d5-11e8-8650-4e0c75591cbc.png">

I saw a flicker when the site is loaded, but that might be because of the fonts being loaded later.

**Comment by marcneander** [comment]
@kakadiadarpan Hmm, thats weird. I cleared node_modules, .cache and public dirs and reinstalled and rebuilt everything. Still get the same problems in both Firefox and Chrome.

Firefox:
<img width="1276" alt="screenshot 2018-10-04 at 10 00 37" src="https://user-images.githubusercontent.com/2528612/46460646-dd935700-c7bc-11e8-8197-e0ee65455b5d.png">

Chrome:
<img width="1277" alt="screenshot 2018-10-04 at 10 01 40" src="https://user-images.githubusercontent.com/2528612/46460653-e552fb80-c7bc-11e8-83f7-bedd9ebc0316.png">

Disabling javascript will prevent the problems I'm having so something is going on when the app is being hydrated. See screenshots from `6-01ff99c6b2bb09dc769a.js` and onwards.

**Comment by marcneander** [comment]
https://github.com/gatsbyjs/gatsby/issues/3067 seems like the same issue I'm having? Tried all possible solutions in that thread without any success

**Comment by kakadiadarpan** [comment]
@marcneander can you try clearing your browser cache and try?

**Comment by marcneander** [comment]
@kakadiadarpan It's not that. If you see screenshots I have "Disable cache" and you can see resources being fetched (not from cache)

**Comment by marcneander** [comment]
@kakadiadarpan You're serving my site with `gatsby serve` right? The issue I'm having is not present during `gatsby develop`

**Comment by marcneander** [comment]
Turns out that the `Layout` component rerenders on route changes even if I use `gatsby-plugin-layout`. That's probably why I'm getting this behaviour.

Any suggestions on how to add global styles with `styled-components` 
v4 in Gatsby? My solution obviously don't work.

**Comment by good3n** [comment]
+1 :(
