### ISSUE TITLE
Is there a way to pass huge objects once?

### ISSUE THREAD

**Issue by oobidin** [gatsbyjs/gatsby#8784]
## Summary

I use GatsbyJS for creating the website with 22k+ pages in total. For some reasons, I have to GraphQL data from huge JSONs on some pages.

As a result, the size of the prod version is about 15 Gb and JSONs with the pageContext for those pages are about 600 kb each.

So, the question is: is there a way not to GraphQL that data and load it once somehow to reduce the size of the prod version or is there a way to place those objects to redux store from `gatsby-node` maybe?

**Comment by KyleAMathews** [comment]
One way of doing this is to query it with StaticQuery in a component which you then use to wrap all the pages that need the data. This way the data is only loaded once.

**Comment by oobidin** [comment]
@KyleAMathews cool man! Thanks so much!

**Comment by DSchau** [comment]
@oobidin glad to hear that worked! Closing this out.
