### ISSUE TITLE
How can I get the current url (or path) in a page in v2

### ISSUE THREAD

**Issue by amingilani** [gatsbyjs/gatsby#8787]
## Summary

Hi there, I'm trying to create an `og:url` property, which requires the current page URL in the head tag. I have everything wired up, except the part where I can determine the current location of the page itself.

## Relevant information

> @skjorrface `location` is passed to the layout as a prop (the pages will receive it in V2), so if you're using it from a component you'd need to pass it down:
> 
> ```
> const Layout = ({ location }) => (
>   <MyComponent location={location} />
> );
> ```
> Does that make sense?
> — @jlengstorf, https://github.com/gatsbyjs/gatsby/issues/1875#issuecomment-420811319

Unfortunately, calling `this.props.location.pathname` in my `index.js` file didn't help and it stopped. I'm wondering if something before the stable release and wasn't documented?

**Comment by KyleAMathews** [comment]
What data is on this.props?

**Comment by amingilani** [comment]
> Hmmm not sure what that means. Are you using a class component?
@KyleAMathews, no, I'm using a functional component.

Sighhh, update, I peeked through React Developer Tools.

<img width="778" alt="screen shot 2018-10-04 at 9 25 26 pm" src="https://user-images.githubusercontent.com/1188552/46488432-131b5d00-c81c-11e8-9b15-2c57f43e9ba6.png">

I should be getting props, but for some reason calling `this.props` makes the whole thing hang. For example, the page renders fine with this code:

## This works

**Note:** The footer is rendered by the Layout component

```
const IndexPage = () => (
  <Layout location="/" noHeader="true">
    <p>This works fine</p>
  </Layout>
)
```

<img width="774" alt="screen shot 2018-10-04 at 9 29 53 pm" src="https://user-images.githubusercontent.com/1188552/46488657-b9fff900-c81c-11e8-87c7-310236ebd4cf.png">

## This doesn't work

```
const IndexPage = () => (
  <Layout location="/" noHeader="true">
    <p>This won't work at all {this.props.location.pathname}</p>
  </Layout>
)
```

<img width="774" alt="screen shot 2018-10-04 at 9 32 38 pm" src="https://user-images.githubusercontent.com/1188552/46488786-20851700-c81d-11e8-8c45-853e9dc58e2a.png">

**Comment by jlengstorf** [comment]
@amingilani functional components don't have a `this` prop, so you'd need to do this instead:

```jsx
const IndexPage = (props) => (
  <Layout location="/" noHeader="true">
    <p>This won't work at all {props.location.pathname}</p>
  </Layout>
)
```

Another option is to use the `Location` import from `@reach/router`. I put together a [CodeSandbox example to show how that works](https://codesandbox.io/s/v82ol26w9l).

Let me know if that doesn't get you up and running.

**Comment by amingilani** [comment]
Thanks @jlengstorf, this works perfectly!

**Comment by dandv** [comment]
@jlengstorf: thanks for that example! To clarify, `location` is passed to the `SecondPage` component [by the Gatsby `Link` component in the `to` attribute](https://www.gatsbyjs.org/docs/gatsby-link/#pass-state-as-props-to-the-linked-page).

PS: `page-2.js` has an unused `import { Location } from '@reach/router'`.
