### ISSUE TITLE
Documentation Dark Theme

### ISSUE THREAD

**Issue by josefaidt** [gatsbyjs/gatsby#8789]
## Summary

Dark Theme toggle for Gatsby documentation.

### Basic examples

[Docker Documentation](https://docs.docker.com/) - toggle on right
[Some of MS documentation](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-overview-introduction?view=azure-bot-service-4.0) - toggle on top right
[DevDocs.io](https://devdocs.io/settings) - toggle in `preferences`

### Motivation

- **Why are we doing this?** - provide users with a toggle to view documentation comfortably in low-light environments
- **What use cases does it support?** - users viewing documentation in low-light environments, users that prefer darker pages
- **What is the expected outcome?** - toggle on the top-right of the documentation pages to enable dark theme

### Final Thoughts

This is by no means an easy task, and this is just my opinion. I can get by with standard black-on-white, however it is super appealing to me when documentation pages have the dark theme toggle.

**Comment by DSchau** [comment]
@josefaidt I like the idea! I think it would be fairly challenging (albeit manageable) to implement this functionality though. We're using glamor on the www/ (gatsbyjs.org) side of things, which doesn't seem to have as great of a theming story as something like emotion, styled-components, etc. so there'd most likely be some rewrite required there, as well.

So high level, this would involve the following steps:

1. Swapping glamor for emotion
1. Implementing a ThemeProvider component, and adjusting the theme object to have dark/light variants
1. Implementing dark/light state and passing to ThemeProvider in top level (layout?) component; adding a toggle to implement this state change
1. In _every_ component accessing this theme object, swap the color depending on the current theme (dark or light)

Totally doable, but like you said, a fair amount of work :) Sound like something you're interested in?

Also cc @fk is this something we'd want to do?

**Comment by josefaidt** [comment]
I'd be happy to work on this! I actually work mostly in the evenings/nights and the dark mode is really the only thing I believe its missing. Feeling dedicated to making this happen. I'll fork and see what I can come up with

**Comment by DSchau** [comment]
@josefaidt want to start (as @fk noted) with adding emotion to the current gatsbyjs.org site?

Should be relatively simple, as emotion _also_ supports the `css` prop that we use so heavily with glamor!

**Comment by DSchau** [comment]
See #8816 for more info re: glamor -> emotion.

**Comment by ryanditjia** [comment]
If I’m not mistaken, `props.theme` will only be available to `styled` and not `css` prop.

A method I often see for theming is using CSS custom properties and changing the variables on toggle.

**Comment by Maistho** [comment]
Hi, I started looking into this and managed to [get themes working somewhat](https://github.com/Maistho/gatsby/tree/emotion-theming), but some of the styling is done by Typography.js and not in emotion.

Is there a good way to change themes in Typography.js?

Otherwise it might be nice to move the relevant styles (text colors and such) into emotion to make theming easier.

**Comment by NickyMeuleman** [comment]
> ... but some of the styling is done by Typography.js and not in emotion.
> 
> Is there a good way to change themes in Typography.js?

Tried to implement Dark mode for a blog and also wondering this.

**Comment by fk** [comment]
Winter is coming (🙄🤐) … dark mode is already here: https://www.gatsbyjs.org

Fixed in #18027 ✌️ 🤗
