### ISSUE TITLE
Querying by id prevents page updates in development

### ISSUE THREAD

**Issue by ojeytonwilliams** [gatsbyjs/gatsby#8795]
## Description

When a `pageQuery` only searches by `id` then changes to the source for those pages do not appear in the browser (tested with Firefox and Chrome).  I've taken a look at this myself and it seems to be because the pages aren't getting added to the `component-data-dependencies`.  PR to follow!

### Steps to reproduce

I've changed the example for Remark, so that it queries by `id` rather than `slug`.  In [this demo](https://github.com/ojeytonwilliams/gatsby-id-bug) , all you need to do is edit some of the blog markdown and see the (lack of) change in the browser.

### Expected result

The browser mirrors the source changes.

### Actual result

It does not.

### Environment

  System:
    OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
    CPU: x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 8.12.0 - /usr/bin/node
    Yarn: 1.10.1 - /usr/bin/yarn
    npm: 6.4.1 - /usr/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 62.0.3
  npmPackages:
    gatsby: ^2.0.0 => 2.0.18 
    gatsby-image: ^2.0.5 => 2.0.13 
    gatsby-plugin-catch-links: ^2.0.2 => 2.0.3 
    gatsby-plugin-glamor: ^2.0.5 => 2.0.5 
    gatsby-plugin-sharp: ^2.0.5 => 2.0.6 
    gatsby-plugin-typography: ^2.2.0 => 2.2.0 
    gatsby-remark-autolink-headers: ^2.0.5 => 2.0.6 
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.0.5 
    gatsby-remark-images: ^2.0.1 => 2.0.3 
    gatsby-remark-katex: ^2.0.5 => 2.0.5 
    gatsby-remark-prismjs: ^3.0.0 => 3.0.1 
    gatsby-remark-responsive-iframe: ^2.0.5 => 2.0.5 
    gatsby-remark-smartypants: ^2.0.5 => 2.0.5 
    gatsby-source-filesystem: ^2.0.1 => 2.0.1 
    gatsby-transformer-remark: ^2.1.1 => 2.1.6 
    gatsby-transformer-sharp: ^2.1.1 => 2.1.3 
    gatsby-transformer-yaml: ^2.1.1 => 2.1.1 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

**Comment by kakadiadarpan** [comment]
Thanks for the quick PR @ojeytonwilliams

**Comment by ojeytonwilliams** [comment]
@kakadiadarpan You're very welcome.  I hope it helps!
