### ISSUE TITLE
Replace "gatsby serve" with "gatsby develop"

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#88]
Better match for intent of message. Deprecate old command and print depreciation notice and actually remove at 1.0

**Comment by BerkeleyTrue** [comment]
Maybe also add an alias `gatbsy dev`?

**Comment by KyleAMathews** [comment]
👍🏻

**Comment by KyleAMathews** [comment]
Boo, look's like Commander.js doesn't support aliases right now with git style sub-commands https://github.com/tj/commander.js/issues/419
