### ISSUE TITLE
feat: update gatsby plugins to use new createContentDigest helper

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#8805]
## Summary

We [recently added](https://github.com/gatsbyjs/gatsby/pull/8687) a `createContentDigest` helper which is exposed to any gatsby plugin. This internalizes the unique key creation, which changes based on changing content.

We've added this to several packages, and we should now add it to any/all packages.

### Basic example

Any plugin that implements the following code snippet (or close to it) can be refactored with this new helper:

```js
const crypto = require(`crypto`)

module.exports = ({ createNode }) => {
  const obj = { whatever: true }

  // this is the key one!
  const contentDigest = crypto
  .createHash(`md5`)
  .update(JSON.stringify(obj))
  .digest(`hex`)

  createNode() // use content digest
}
```

can be replaced with

```js
const { createContentDigest } = require('gatsby-core-utils');


module.exports = ({ createNode }) => {
  const obj = { whatever: true }

  // this is the key one!
  const contentDigest = createContentDigest(obj)

  createNode() // use content digest
}
```

### Motivation

Cleaning up code and keeping it DRY 💪

### Additional Info

Any plugin that implements this new API should also bump it's `peerDependency` on gatsby, e.g.

```json
{
  "peerDependencies": {
    "gatsby": ">2.0.15"
  }
}
```

**Comment by samscha** [comment]
Thank you for the reference. I'll do some testing on my own for some of the most popular plugins and report back / open a pr!

**Comment by amberleyromo** [comment]
@DSchau Maybe it would be useful to break this apart into different issues for the different plugins? Or at least a listing of todos in this issue description?

**Comment by frinyvonnick** [comment]
Here is the list of plugins that seems not using `createContentDigest` as suggested @amberleyromo :

- [ ] [gatsby-source-hacker-news](https://github.com/gatsbyjs/gatsby/blob/eeef674e03c6e9fbdda0fea4821914a1861584fa/packages/gatsby-source-hacker-news/src/gatsby-node.js)
- [ ] [gatsby-transformer-excel](https://github.com/gatsbyjs/gatsby/blob/95c1eac260007a145e7c306bfb672a1e1e67c39c/packages/gatsby-transformer-excel/src/gatsby-node.js)
- [ ] [gatsby-source-wikipedia](https://github.com/gatsbyjs/gatsby/blob/445f5ff7508ab613967e18b32490e3feffd7730c/packages/gatsby-source-wikipedia/src/gatsby-node.js)
- [ ] gatsby-source-mongodb [1](https://github.com/gatsbyjs/gatsby/blob/0f14e52491a0e84b79b8654765b9e07cc9cc126b/packages/gatsby-source-mongodb/src/mapping.js), [2](https://github.com/gatsbyjs/gatsby/blob/f61e437e55effd918fca135f47f9c29df2219e22/packages/gatsby-source-mongodb/src/gatsby-node.js)
- [ ] gatsby-source-filesystem [1](https://github.com/gatsbyjs/gatsby/blob/cac37a93402af3b88a37fefce1878be470df1781/packages/gatsby-source-filesystem/src/create-remote-file-node.js), [2](https://github.com/gatsbyjs/gatsby/blob/ac2a54ae6795636d9088a06ac8c26bd1519e3728/packages/gatsby-source-filesystem/src/create-file-node.js)
- [ ] gatsby-source-contentful [1](https://github.com/gatsbyjs/gatsby/blob/445f5ff7508ab613967e18b32490e3feffd7730c/packages/gatsby-source-contentful/src/cache-image.js), [2](https://github.com/gatsbyjs/gatsby/blob/afa0f1e9c1ca0af106d9e9520aaf4950b0430dc7/packages/gatsby-source-contentful/src/normalize.js)
- [ ] [gatsby-transformer-hjson](https://github.com/gatsbyjs/gatsby/blob/445f5ff7508ab613967e18b32490e3feffd7730c/packages/gatsby-transformer-hjson/src/gatsby-node.js)
- [ ] [gatsby-transformer-sqip](https://github.com/gatsbyjs/gatsby/blob/445f5ff7508ab613967e18b32490e3feffd7730c/packages/gatsby-transformer-sqip/src/generate-sqip.js)
- [ ] [gatsby-source-npm-package-search](https://github.com/gatsbyjs/gatsby/blob/445f5ff7508ab613967e18b32490e3feffd7730c/packages/gatsby-source-npm-package-search/src/gatsby-node.js)
- [ ] [gatsby-transformer-toml](https://github.com/gatsbyjs/gatsby/blob/a8124b07abeb488db66fdb5975363708c58f39e4/packages/gatsby-transformer-toml/src/gatsby-node.js)
- [ ] [gatsby-transformer-remark](https://github.com/gatsbyjs/gatsby/blob/e28dd81d8c53ceacfce39a8109f5f05ea8beb30c/packages/gatsby-transformer-remark/src/on-node-create.js)
- [ ] [gatsby-source-lever](https://github.com/gatsbyjs/gatsby/blob/1e57aee22292e379a58207b11e08e5c91082a55e/packages/gatsby-source-lever/src/normalize.js)
- [ ] [gatsby-transformer-javascript-static-exports](https://github.com/gatsbyjs/gatsby/blob/a42d0de654e70be1b25697848529e118e6bf92c6/packages/gatsby-transformer-javascript-static-exports/src/gatsby-node.js)
- [ ] [gatsby-source-graphql](https://github.com/gatsbyjs/gatsby/blob/082cd89443cf1d293e0242e1384d66ce38fab961/packages/gatsby-source-graphql/src/gatsby-node.js)
- [ ] [gatsby-source-medium](https://github.com/gatsbyjs/gatsby/blob/b750400e4ad4ebb9d3bf7b4b1437232e5d7331e4/packages/gatsby-source-medium/src/gatsby-node.js)
- [ ] [gatsby-transformer-react-docgen](https://github.com/gatsbyjs/gatsby/blob/8830d47dd72e049e007ffeaeb966ec1632afd857/packages/gatsby-transformer-react-docgen/src/on-node-create.js)
- [ ] [gatsby-transformer-javascript-frontmatter](https://github.com/gatsbyjs/gatsby/blob/7faf8f7248ac27c35b1cb094d692545d0ae28e2e/packages/gatsby-transformer-javascript-frontmatter/src/gatsby-node.js)
- [ ] [gatsby-transformer-screenshot](https://github.com/gatsbyjs/gatsby/blob/51a8c985b64dd6c19b93c0c623ad306b1dee4113/packages/gatsby-transformer-screenshot/lambda/index.js)
- [ ] [gatsby-remark-images-contentful](https://github.com/gatsbyjs/gatsby/blob/6866e76c4f0b02221e6eac93a0582939cae49103/packages/gatsby-remark-images-contentful/src/index.js)
- [ ] [gatsby-source-drupal](https://github.com/gatsbyjs/gatsby/blob/a2267694b2c1380fdbee4e4d22ac74990cf8f9f7/packages/gatsby-source-drupal/src/gatsby-node.js)
- [ ] gatsby-plugin-sharp [1](https://github.com/gatsbyjs/gatsby/blob/da0b6221bb7fde93f4586e0db23e08eab4dcc2d3/packages/gatsby-plugin-sharp/src/process-file.js), [2](https://github.com/gatsbyjs/gatsby/blob/da0b6221bb7fde93f4586e0db23e08eab4dcc2d3/packages/gatsby-plugin-sharp/src/index.js)
- [ ] [gatsby-source-wordpress](https://github.com/gatsbyjs/gatsby/blob/925a655c17495373f56bee8da7dd0f59f7979fd4/packages/gatsby-source-wordpress/src/normalize.js)

I didn't list occurences in `gatsby` package. Could someone confirm this list ?

**Comment by wardpeet** [comment]
@frinyvonnick feel free to already start on them ;) no need to wait for validation

**Comment by frinyvonnick** [comment]
@DSchau I don't know how to handle it in a `setFieldsOnGraphQLNodeType` function like in [gatsby-transformer-sqip](https://github.com/gatsbyjs/gatsby/blob/445f5ff7508ab613967e18b32490e3feffd7730c/packages/gatsby-transformer-sqip/src/generate-sqip.js). Do you have any advices ?

**Comment by romulomachado** [comment]
`gatsby-source-mongodb` has been handled on #13293

**Comment by gmertk** [comment]
Hi gatsby folks,
I'm jumping in to fix the remaining ones here. 

- `gatsby-source-contentful` has 2 references to crypto:
  1- [cache-image.js](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/src/cache-image.js#L1) which is called by extend-node-type.js used as setFieldsOnGraphQLNodeType. However, setFieldsOnGraphQLNodeType doesn’t have createContentDigest as sourceNodes does. 
2 - normalize.js which is called by sourceNodes. Fixing this one in #14567.

- `gatsby-transformer-sqip` is similar to 1st issue of gatsby-source-contentful. crypto is used within setFieldsOnGraphQLNodeType.

- `gatsby-transformer-screenshot` already uses createContentDigest [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-screenshot/src/gatsby-node.js#L121)
However [its lambda function](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-screenshot/lambda/index.js) still uses crypto. That is ok I guess, as it isn’t a plugin?


How should we handle this in setFieldsOnGraphQLNodeType?

**Comment by wardpeet** [comment]
Sorry for keeping you waiting.

we want to hold off gatsby-source-contentful changes for now, as we have some big PRs open.

transformer-sqip should be able to use `createContentDigest` as it's passed down as args so it would be nice to use that one.

In gatsby-transformer-screenshot should use crypto as we don't want any deps on that function.

**Comment by jbutz** [comment]
There hasn't been any recent activity here, so I am going to try and jump in and take care of `gastby-transformer-sqip` and `gastby-plugin-sharp`.

**Comment by muescha** [comment]
Hi @DSchau can you please update the example in your issue with this hint:

https://github.com/gatsbyjs/gatsby/pull/18139#pullrequestreview-299211154 from @wardpeet 

> Hey @jbutz, thanks for the effort on this one. We currently have a more simplified snippet to replace contentDigest.
> 
> You can do the following
> 
> ```js
> import { createContentDigest } from 'gatsby-core-utils';
> ```

**Comment by DSchau** [comment]
@muescha sure. done!

**Comment by muescha** [comment]
👍🏻

**Comment by muescha** [comment]
@DSchau 

the implementation is now simplified by importing from `gatsby-core-utils`

Q: is it ok also refactor the "old style" usage to the simplified usage? so that always the code is the same?

**Comment by muescha** [comment]
i found this dead code:

  - [src/utils/get-hash-fn.js](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/get-hash-fn.js#L9-L11)

it is an not used function `getHashFn` 
-> can this be removed?

**Comment by kindavishal** [comment]
Thanks for the great session @sidharthachatterjee :sparkling_heart: 
But for some reason I am unable to switch branches. The following command was suppose to do the job
```git fetch origin && git checkout fix/content-digest```
but it's not fetching the other branches, only two from remote:
```
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
```
My remote is set to this project's url, I however tried forking it to my account and then cloning it, but forking forks only the master branch, so no luck with that either! :/

**Comment by muescha** [comment]
@kindavishal maybe the PR #20239 is related

**Comment by kindavishal** [comment]
Maybe, I am unable to figure out why this is happening! Even if the PR is related, I should be able to switch branches right?

**Comment by muescha** [comment]
you are right, 

but your question not relates to the title of the current issue, thats why i fear your question get lost here. 

Sithartha mentioned  in the linked PR the session with you, and the branchname is also `fix/content-digest` in the linked PR, so i guess the other issue is somehow better for asking.

**Comment by kindavishal** [comment]
Oh okay! Yes, that makes sense! I'll carry future conversations over there :slightly_smiling_face:

**Comment by muescha** [comment]
@sidharthachatterjee i updated the list in https://github.com/gatsbyjs/gatsby/issues/8805#issuecomment-477590874

but there are still left some places for the `createContentDigest`
