### ISSUE TITLE
Popular Animation Library (GSAP) doesn't work after site is built

### ISSUE THREAD

**Issue by orshick** [gatsbyjs/gatsby#8810]
## Summary
Using GSAP on my [gatsby site](https://clever-wiles-b95d3a.netlify.com/other-page "site") works fine during development, but does not work in the built version.
I'm guessing this has something to do with me using it only in componentDidMount, and therefore being ignored from the server rendering or something of that sort. Either way, I'm not sure how I'd work around this. Any ideas would be greatly appreciated!

## Relevant information

Using the latest GSAP, and the latest gatsby (v2).
Using gatsby-starter-blog
Win10

### Environment (if relevant)

Ran gatsby info --clipboard but it did not work, despite being on the latest gatsby-cli

### File contents (if changed)

`gatsby-config.js`:  
```JS
module.exports = {
  siteMetadata: {
    title: 'Gatsby Starter Blog',
    author: 'Kyle Mathews',
    description: 'A starter blog demonstrating what Gatsby can do.',
    siteUrl: 'https://gatsbyjs.github.io/gatsby-starter-blog/',
  },
  pathPrefix: '/gatsby-starter-blog',
  plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/pages`,
        name: 'pages',
      },
    },
    {
      resolve: `gatsby-plugin-emotion`,
      options: {
        // Accepts all options defined by `babel-plugin-emotion` plugin.
      },
    },
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 590,
            },
          },
          {
            resolve: `gatsby-remark-responsive-iframe`,
            options: {
              wrapperStyle: `margin-bottom: 1.0725rem`,
            },
          },
          'gatsby-remark-prismjs',
          'gatsby-remark-copy-linked-files',
          'gatsby-remark-smartypants',
        ],
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-google-analytics`,
      options: {
        //trackingId: `ADD YOUR TRACKING ID HERE`,
      },
    },
    `gatsby-plugin-feed`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `Gatsby Starter Blog`,
        short_name: `GatsbyJS`,
        start_url: `/`,
        background_color: `#ffffff`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/assets/gatsby-icon.png`,
      },
    },
    `gatsby-plugin-offline`,
    `gatsby-plugin-react-helmet`,
    {
      resolve: 'gatsby-plugin-typography',
      options: {
        pathToConfigModule: 'src/utils/typography',
      },
    },
  ],
}
```

`package.json`:  
```JS
{
  "name": "gatsby-starter-blog",
  "description": "Starter Gatsby Blog",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby-starter-blog/issues"
  },
  "dependencies": {
    "emotion": "^9.2.12",
    "emotion-server": "^9.2.12",
    "gatsby": "^2.0.0",
    "gatsby-plugin-emotion": "^2.0.5",
    "gatsby-plugin-feed": "^2.0.5",
    "gatsby-plugin-google-analytics": "^2.0.5",
    "gatsby-plugin-manifest": "^2.0.2",
    "gatsby-plugin-offline": "^2.0.5",
    "gatsby-plugin-react-helmet": "^3.0.0",
    "gatsby-plugin-sharp": "^2.0.5",
    "gatsby-plugin-typography": "^2.2.0",
    "gatsby-remark-copy-linked-files": "^2.0.5",
    "gatsby-remark-images": "^2.0.1",
    "gatsby-remark-prismjs": "^3.0.0",
    "gatsby-remark-responsive-iframe": "^2.0.5",
    "gatsby-remark-smartypants": "^2.0.5",
    "gatsby-source-filesystem": "^2.0.1",
    "gatsby-transformer-remark": "^2.1.1",
    "gatsby-transformer-sharp": "^2.1.1",
    "gsap": "^2.0.2",
    "lodash": "^4.17.11",
    "lodash-es": "^4.17.11",
    "prismjs": "^1.15.0",
    "react": "^16.5.1",
    "react-dom": "^16.5.1",
    "react-emotion": "^9.2.12",
    "react-helmet": "^5.2.0",
    "react-typography": "^0.16.13",
    "typeface-merriweather": "0.0.43",
    "typeface-montserrat": "0.0.43",
    "typography": "^0.16.17",
    "typography-theme-wordpress-2016": "^0.15.10"
  },
  "devDependencies": {
    "eslint": "^4.19.1",
    "eslint-plugin-react": "^7.11.1",
    "gh-pages": "^1.2.0",
    "prettier": "^1.14.2"
  },
  "homepage": "https://github.com/gatsbyjs/gatsby-starter-blog#readme",
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "main": "n/a",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/gatsbyjs/gatsby-starter-blog.git"
  },
  "scripts": {
    "dev": "gatsby develop",
    "lint": "./node_modules/.bin/eslint --ext .js,.jsx --ignore-pattern public .",
    "test": "echo \"Error: no test specified\" && exit 1",
    "format": "prettier --trailing-comma es5 --no-semi --single-quote --write 'src/**/*.js' 'src/**/*.md'",
    "develop": "gatsby develop",
    "build": "gatsby build",
    "deploy": "gatsby build --prefix-paths && gh-pages -d public",
    "fix-semi": "eslint --quiet --ignore-pattern node_modules --ignore-pattern public --parser babel-eslint --no-eslintrc --rule '{\"semi\": [2, \"never\"], \"no-extra-semi\": [2]}' --fix gatsby-node.js"
  }
}
```

`gatsby-node.js`: 
```JS
const _ = require('lodash')
const Promise = require('bluebird')
const path = require('path')
const { createFilePath } = require('gatsby-source-filesystem')

exports.createPages = ({ graphql, actions }) => {
  const { createPage } = actions

  return new Promise((resolve, reject) => {
    const blogPost = path.resolve('./src/templates/blog-post.js')
    resolve(
      graphql(
        `
          {
            allMarkdownRemark(sort: { fields: [frontmatter___date], order: DESC }, limit: 1000) {
              edges {
                node {
                  fields {
                    slug
                  }
                  frontmatter {
                    title
                  }
                }
              }
            }
          }
        `
      ).then(result => {
        if (result.errors) {
          console.log(result.errors)
          reject(result.errors)
        }

        // Create blog posts pages.
        const posts = result.data.allMarkdownRemark.edges;

        _.each(posts, (post, index) => {
          const previous = index === posts.length - 1 ? null : posts[index + 1].node;
          const next = index === 0 ? null : posts[index - 1].node;

          createPage({
            path: post.node.fields.slug,
            component: blogPost,
            context: {
              slug: post.node.fields.slug,
              previous,
              next,
            },
          })
        })
      })
    )
  })
}

exports.onCreateNode = ({ node, actions, getNode }) => {
  const { createNodeField } = actions

  if (node.internal.type === `MarkdownRemark`) {
    const value = createFilePath({ node, getNode })
    createNodeField({
      name: `slug`,
      node,
      value,
    })
  }
}
```

`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by orshick** [comment]
Thanks a lot for your reply Kyle!

Nope, no console errors unfortunately. Considering the page is only 39kb (when inspecting network tab) I doubt that GSAP is getting loaded at all. 

The page i linked above (https://clever-wiles-b95d3a.netlify.com/other-page) is literally the page I was practicing with GSAP on. I'm not sure if it's gatsby per se, maybe it's more of a general SSR thing. However, it does work properly while I have it in ```gatsby develop``` mode

Here is the github link to the relevant page: https://github.com/orshick/chancelor/blob/master/src/pages/other-page.js

**Comment by endymion1818** [comment]
How are you loading GSAP Orshick? Where are you putting the <script> tag? It doesn't look like it made it into the built site to me.

**Comment by orshick** [comment]
Thanks for inquiring @endymion1818! I'm importing it from node_modules like so

```js
import { TweenLite, TimelineLite, Elastic, Back, Power2 } from 'gsap/all'
```

To reitterate, it does work during development, so I'm guessing this is an SSR issue. Do you know of some special way I have to import the library to have it not trip up during the SSR step?

Any help is appreciated!

**Comment by endymion1818** [comment]
No worries Orshick! I'd be interested in investigating this a bit further. But as it's not an issue with GatsbyJS itself, would you mind opening a discussion on https://spectrum.chat/? You can @ me with the same username over there.

That will open up the discussion to other community members who may be interested. It will also let the team here focus on working on Gatsby itself.

Thanks!

**Comment by orshick** [comment]
Thanks again. I assumed that something working in development but not in production builds would be categorized as related to GatsbyJS itself, but fair enough, i'll take it to the spectrum chat.

**Comment by endymion1818** [comment]
No worries! It is confusing, but running "gatsby develop" is very different from building the site. It's a visual preview, but there's a lot more that happens. When I'm looking at other people's code I ask others to test it under "gatsby build" too, because of these differences.

**Comment by orshick** [comment]
OK, figured out what was wrong. Turns out I had to import the GSAP libraries from "gsap" rather than "gsap/all", even though that is the path they suggest in the docs. Go figure.

Thanks for the offer to help @endymion1818. Unfortunately I wasn't fully able to figure out how to post on Spectrum. I'll have to learn that one of these days :)

**Comment by TylerBarnes** [comment]
If anyone else comes here with the same problem, @orshick's solution solved it for me but I didn't realize it at first because I had to disable gatsby-plugin-offline and get a chrome extension to clear the service worker.

**Comment by konstantina89f** [comment]
Hello. 
I do have the same problem. 
I am not sure what to do. 
"I had to disable gatsby-plugin-offline and get a chrome extension to clear the service worker. "??
import { TimelineLite, TweenLite, Power0, Power1 } from 'gsap'
I am importing it well etc, in dev. everything is working exceptionally nice but in pro is totally broken without to give an error. 
is just not working.
Please help me out asap, as this problem is bothering my colleague and me for more than 2 days.... 
Thank you.

**Comment by TylerBarnes** [comment]
@konstantina89f [this is the extension](https://chrome.google.com/webstore/detail/clear-service-worker/kkbncldhbdallogkalmfgijpinjggboh?hl=en) to clear your service worker.

Make sure you put all your gsap code inside componentdidmount. If you put any of it in your constructor your build will silently fail. I found initializing gsap code in the constructor and controlling it elsewhere worked fine and built fine locally but it caused infinite build times on netlify with no errors.

You could also try using `import TimelineMax from 'gsap'`. This is what I usually use and it works great.

**Comment by konstantina89f** [comment]
Dear both, 
Thank you so much for the quick responses. 
First, let me say that i am on Vue js not react. 
So, after trying what is suggested by u, the new situation is as following: 
1. npm install gatsby-plugin-remove-serviceworker installed. 
2. the chrome extension Clear Service Worker installed and used.
3. replace: import { TimelineLite, TweenLite, Power0, Power1 } from 'gsap'
with: import { TimelineMax, Power0, Power1 } from 'gsap'  and
import TweenLite from 'gsap/TweenLite'
3. All the functions/methods are called within  mounted () { }  (also event Listener for btn)
4. in dev is totally fine the functionality, 
     in prod i have still nothing moving. nothing working, nothing at all. WITHOUT erros.

p.s. i have console.log everthing and they really look good.  I cannot think of anything more, please try to think why we cannot make it in production with me :) 
p.s.2 I seriously in need of a solution. 
Thanks a lot of all of u guys.
Regards,
Dina

**Comment by AshfaqKabir** [comment]
@TylerBarnes @endymion1818  I'm having the same Issue. Everything works fine in development but when pushed to production the animations are not rendered and do not throw any console errors.
I tried the above solutions but still no luck. I uninstalled `gatsby-plugin-offline` but couldn't find the extension mentioned above. Here is my code.
![Screenshot (2)](https://user-images.githubusercontent.com/45657135/71545903-166bad00-29bb-11ea-8545-679e00124cde.png)

**Comment by konstantina89f** [comment]
Hey let me know if you receive my email.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by konstantina89f** [comment]
Hey. So I have found the solution back then.
I don't remember it exactly right now but there is a bug at the import.
First of all dont import Everything if you don't need them all. I will send you the import I replaced them with just in 5 min :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by AshfaqKabir** [comment]
Thanks, @konstantina89f  the problem was with import after all. Anyone else who is having the problem here is the solution `import { gsap, TweenMax, TimelineMax, Power2 } from "gsap/dist/gsap";` for gsap v3. Gsap do have a detailed [article](https://greensock.com/docs/v2/NPMUsage) about it. I found the solution [here](https://greensock.com/docs/v3/Installation?checked=core,gsap2,TweenMax,TimelineMax,Power2#umd)

**Comment by konstantina89f** [comment]
Yes that was all. Is what I meant with the import !

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by maviarebo** [comment]
Hi everyone,

I added gsap scrollsmoother in my website and its working properly, but its not working in bootstrap modal popup
when i open modal popup its default scrolling not working and show this error
![image](https://github.com/gatsbyjs/gatsby/assets/135246637/1d209099-7960-4576-a43c-f29b5326b0c1)

when i close the modal popup showing this error

ScrollSmoother.min.js:13 Uncaught TypeError: _ is not a function
    at Ya (ScrollSmoother.min.js:13:6625)
    at HTMLDivElement.<anonymous> (bootstrap.bundle.min.js:6:55373)
    at HTMLDivElement.i (bootstrap.bundle.min.js:6:4356)
    at Object.trigger (bootstrap.bundle.min.js:6:5502)
    at bootstrap.bundle.min.js:6:53994
    at g (bootstrap.bundle.min.js:6:2108)
    at bootstrap.bundle.min.js:6:47903
    at g (bootstrap.bundle.min.js:6:2108)
    at HTMLDivElement.a (bootstrap.bundle.min.js:6:2486)
