### ISSUE TITLE
Incoherent behavior when visiting uncached page while offline

### ISSUE THREAD

**Issue by sedubois** [gatsbyjs/gatsby#8823]
## Description

I observe an error message and there is an incoherent handling of offline behavior for pages which haven't been pre-fetched before going offline (both in terms of visual feedback shown to user and of the browser URL).

### Steps to reproduce

- visit http://gatsbyjs.github.io/gatsby-starter-blog/
- turn network off
- click the "Hello world" post

### Expected result

As the browser is offline and the page hadn't been pre-fetched yet:
1. The user should be shown some kind of feedback that the link can't be opened because of unavailable network and it hadn't been pre-fetched. Ideally I would expect a notification popup, toast etc.
2. Whether clicking the link results in staying on the same page or even if letting the browser change to a "not found" page, the URL displayed in the URL bar should remain coherent with this choice.
3. No errors in the console

### Actual result

1. There is no visual feedback to the user. The page stays the same (i.e. still shows the blog index).
2. However the URL changes to the URL of the clicked post, which is incoherent with the fact that the content displayed is still the blog index.
3. On Firefox there is an error in the console "The operation is insecure" (not on Chrome)

Firefox:

<img width="1434" alt="screen shot 2018-10-05 at 10 15 06" src="https://user-images.githubusercontent.com/4217871/46521334-ed2ba200-c887-11e8-8799-c5bdb0aae929.png">

Chrome:

<img width="1234" alt="screen shot 2018-10-05 at 10 23 20" src="https://user-images.githubusercontent.com/4217871/46521669-f49f7b00-c888-11e8-9170-f97a170b0d99.png">

### Environment

macOS Firefox 62.0.2. 
macOS Chrome 69.0.3497.100.

**Comment by kakadiadarpan** [comment]
@sedubois Thank you for providing a detailed description.

- `"The operation is insecure"` is a Firefox [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1429714). The issue status says `RESOLVED` but it hasn't been fixed yet, check the last comment on that issue.

- I'm not sure if showing a visual feedback to the user should be handled by `gatsby-plugin-offline` as it's only a service worker implementation. It doesn't control any user interaction.

- User interactions when a user is offline/online can be handled using the [NavigatorOnLine events](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/Online_and_offline_events) separately.

**Comment by sedubois** [comment]
@kakadiadarpan I don't know where the issue should be fixed but I would suggest that if nothing else can take care of it, the offline-plugin should be transparent when clicking a link to a non-cached page, and let the browser render "not found" as if the plugin was not there. Currently the demos which make use of offline-plugin look broken in this regard. At least the incoherent URL should be fixed.

**Comment by pieh** [comment]
Actually I just realized - http://gatsbyjs.github.io/gatsby-starter-blog/ is using gatsby v1 - seems like I've missed updating starter showcase data. https://gatsby-starter-blog-demo.netlify.com/ this is using v2 and it might already be fixed

**Comment by davidbailey00** [comment]
This is actually because you're not using HTTPS - service workers only work over secure connections (and insecure localhost for testing)

**Comment by davidbailey00** [comment]
On second thoughts I'll reopen because we should at least display an error in the console explaining the problem

**Comment by sedubois** [comment]
Thanks @davidbailey00, yes that would be helpful. I would suggest that the deployed example site should also be configured to redirect http to https.

**Comment by sedubois** [comment]
In my browser I never specified the protocol. It just somehow defaulted to http.

**Comment by davidbailey00** [comment]
@sedubois Actually the configuration is due to the server (i.e. GitHub Pages config) - it's possible to implement a client-side redirect but it might break some websites, so I think just doing a console log is the best idea.

**Comment by sedubois** [comment]
Thanks @davidbailey00.

@pieh sorry, can't remember which link I followed. I think I just typed "gatsby-starter-blog" in my phone's search bar.
