### ISSUE TITLE
Content migration - create "Using fragments" article

### ISSUE THREAD

**Issue by amberleyromo** [gatsbyjs/gatsby#8834]
(Thanks @jkjustjoshing for volunteering to work on this! Creating an issue to track this separately, branching off #8103).

## Draft the doc

Primary content identified as source material to repurpose (please cite!): https://www.gatsbycentral.com/reusable-graphql-queries-in-gatsby

Additional identified references that may be useful:
- https://stackoverflow.com/questions/49347775/how-to-share-graphql-fragments-between-node-and-gatsby-pages?rq=1
- https://stackoverflow.com/questions/50441219/gatsby-js-fragment-query-into-component-with-datocms
- https://whttps://yaobin.me/blog/gatsby-component-graphql/ww.unicornsfartpixels.com/quicktips/2018-04-01graphql-fragments/
- https://www.apollographql.com/docs/react/advanced/fragments.html
- https://graphql.org/learn/queries/

## Add to the docs navigation sidebar:

- Link the new doc in the "Querying data with GraphQL" section: https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml#L93

```
- title: Using fragments
  link: /docs/using-fragments/
```

**Comment by amberleyromo** [comment]
@shannonbux did you have thoughts on where this would live in the docs IA?

**Comment by amberleyromo** [comment]
Yep I think that's perfect. I'll modify the issue description.

**Comment by jkjustjoshing** [comment]
Would it be useful to also throw a GraphiQL code sample on the "API Reference -> GraphQL reference" page?

**Comment by amberleyromo** [comment]
@jkjustjoshing Yep, that's an awesome idea. Thanks!

**Comment by amberleyromo** [comment]
Closed in #8902
