### ISSUE TITLE
Not able to render page upon redirect

### ISSUE THREAD

**Issue by bluefig99** [gatsbyjs/gatsby#8838]
When the user is not logged in , the home page should be redirected to Login page. In the nav bar , i can clearly see that the url is http://localhost:3000/login but the login page is not rendered.

I have no issue with the same code in development environment. The issue is happening only when i try to run as a production build using gatsby serve command.

Is there any known issue with Gatsby navigate command? Kindly, please let me know if this is a known issue and any known workaround for the same.

**Expected result**
    Url in nav bar updates and the page is shown

**Actual result**
    blank page is shown until refresh occurs

  System:
    OS: macOS 10.14
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.10.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 62.0.3
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.0 => 2.0.2 
    gatsby-plugin-create-client-paths: ^2.0.0 => 2.0.0 
    gatsby-plugin-eslint: ^2.0.1 => 2.0.1 
    gatsby-plugin-manifest: ^2.0.2 => 2.0.2 
    gatsby-plugin-offline: ^2.0.5 => 2.0.5 
    gatsby-plugin-page-creator: ^2.0.0 => 2.0.0 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
  npmGlobalPackages:
    gatsby-cli: 2.4.1

**Comment by KyleAMathews** [comment]
Can you build a site that reproduces this issue?

**Comment by bluefig99** [comment]
Hello Kyle , Thanks for your attention. Please find the attached code that reproduces the issue.
[navigate_issue_Aravind.zip](https://github.com/gatsbyjs/gatsby/files/2452583/navigate_issue_Aravind.zip)

**Comment by bluefig99** [comment]
Kyle , did you get a chance to look in to this issue.

Thanks
Aravind

**Comment by KyleAMathews** [comment]
No not yet. @kakadiadarpan can you validate @bluefig99's reproduction?

**Comment by kakadiadarpan** [comment]
@KyleAMathews I'm able to reproduce the issue reported by @bluefig99. When you load the build for the first time, you get a blank page. When you load it again, we get to see the login screen as expected.

The first load fails to load the redirected screen, the second load is successful.

**Comment by bluefig99** [comment]
@KyleAMathews can you please check whether this is an issue here?

**Comment by ng-hai** [comment]
I have found a workaround
![image](https://user-images.githubusercontent.com/19520278/47695682-c9187200-dc35-11e8-86ef-8049325adf71.png)
