### ISSUE TITLE
eslint-loader is disabled when specifying a custom .eslintrc

### ISSUE THREAD

**Issue by jkjustjoshing** [gatsbyjs/gatsby#8840]
## Description

When I run the default Gatsby project, I'm alerted to ESLint errors in my terminal, and in the browser console, whenever I save a file. 
However, when I add a custom .eslintrc file to the root of my project, those errors stop appearing. My code editor still warns me about linting errors based on my custom rules, but the Gatsby server doesn't tell me, and they are not logged to the browser console.

### Steps to reproduce

1. Open a Gatsby project with no custom ESLint rules, and start the Gatsby server
2. Make an ESLint error (for example, create an unused variable `let unusedVar = 'foo';`. Notice that when you save the file a warning appears in the terminal where the Gatsby server is running
3. Create a new .eslintrc.json file in the root of the project with the following content:
```
{
    "rules": {
        "no-unused-vars": "error"
    }
}
```
4. Restart the Gatsby server.
5. Re-save the file with the linting error.

### Expected result

The `no-unused-vars` error should display in the Gatsby server terminal and in the browser console

### Actual result

Compilation completes successfully with no warnings displayed

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.4 - /usr/local/bin/node
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 61.0.2
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.0 => 2.0.11 
    gatsby-link: ^2.0.0 => 2.0.2 
    gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11 
    gatsby-plugin-sass: ^2.0.1 => 2.0.1 
    gatsby-source-directus: 0.0.44 => 0.0.44

**Comment by pieh** [comment]
This is by design - https://github.com/gatsbyjs/gatsby/blob/2181126f144f51e6d0ef77e6c35f18006a6e6369/packages/gatsby/src/utils/webpack.config.js#L301-L304

Rationale behind it - add very basic eslint setup, but if user provide his own config - disable any builtin stuff and let user be in charge of it. You can use something like https://www.gatsbyjs.org/packages/gatsby-plugin-eslint/ to re-add your custom config to dev server
