### ISSUE TITLE
Content migration - fill out "Programmatically create pages from data" stub article in the docs

### ISSUE THREAD

**Issue by amberleyromo** [gatsbyjs/gatsby#8841]
## Issue Context

This issue is part of the content migration project (#8103), which is meant to take existing content and *repurpose* it so it's easier to find in the docs.

### Motivation

We are doing this because many people have written excellent content that we want to canonize and maintain so more people can find it and benefit from it.

### Review the Gatsby docs approach

- [ ] Read the Style Guide and follow it in order for your PR to be accepted. Pay special attention to the templates. 
  - Style Guide: https://www.gatsbyjs.org/docs/gatsby-style-guide/
  - Docs Templates: https://www.gatsbyjs.org/docs/templates/
  - Example of a similar article: [Adding Markdown Pages
](https://www.gatsbyjs.org/docs/adding-markdown-pages/)

### Draft the doc

- [ ] Add to the [Programmatically create pages from data](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/programmatically-create-pages-from-data.md) stub article.
- [ ] Use the following reference material as a primary starting point to draft the new doc: https://www.gatsbyjs.org/tutorial/part-seven/ Make sure you rewrite and adjust the content to follow the format listed in these resources:
  - Docs Templates: https://www.gatsbyjs.org/docs/templates/
  - Example of a guide to imitate: https://www.gatsbyjs.org/docs/deploying-to-s3-cloudfront
- [ ] Find the stub in the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml), and remove the asterisk next to the title, (which will indicate that the doc is no longer a stub).

### Open a pull request
- [ ] Open a pull request with your work, including the words "closes #8841"

**Comment by jbranchaud** [comment]
I'd love to work on this.

**Comment by jbranchaud** [comment]
@Soundug Pending some feedback, I've basically finished it -- #9069
