### ISSUE TITLE
[Docs/tutorials] internationalization

### ISSUE THREAD

**Issue by shmesa22** [gatsbyjs/gatsby#8842]
## Summary

I noticed that there are only two parts of the docs/tutorials translated to Spanish and I couldn't find any issue related to that. If nobody is working on those I would like to help with that task 😄. Let me know, I can start right away.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Closing this issue as it's not planned to provide languages other than english (too much overhead with keeping them in sync, we can't proofread the translations)
