### ISSUE TITLE
Content migration - create "Submit to Plugin Library" article in the docs

### ISSUE THREAD

**Issue by amberleyromo** [gatsbyjs/gatsby#8843]
## Issue Context

This issue is part of the content migration project (#8103), which is meant to take existing content and *repurpose* it so it's easier to find in the docs.

### Motivation

We are doing this because many people have written excellent content that we want to canonize and maintain so more people can find it and benefit from it.

### Review the Gatsby docs approach

- [ ] Read the Style Guide and follow it in order for your PR to be accepted. Pay special attention to the templates. 
  - Style Guide: https://www.gatsbyjs.org/docs/gatsby-style-guide/
  - Docs Templates: https://www.gatsbyjs.org/docs/templates/

### Draft the doc

- [x] Create a new file named `submit-to-plugin-library.md` in the [docs source directory](https://github.com/gatsbyjs/gatsby/tree/master/docs/docs).
- [x] Begin the newly-created markdown file with the following frontmatter:

```
---
title: Submit to Plugin Library
---
```

- [x] Use the text of this section of the "Plugin Authoring" doc: https://www.gatsbyjs.org/docs/plugin-authoring/#publishing-a-plugin-to-the-library
- [x] Change the section of the "Plugin Authoring" doc to link to the new page (so the content isn't duplicated, it's moved over)
- [x] Change [this section of the Source Plugin Tutorial](https://www.gatsbyjs.org/docs/source-plugin-tutorial/#publishing-a-plugin) to link to the new page, instead of the "Plugin Authoring" doc.

### Add the page to the sidebar

- [x] [Add the new page to the sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml#L383) under "Submit to Starter Library"

```
- title: Submit to Plugin Library
  link: /docs/submit-to-plugin-library/
```

### Open a pull request
- [x] Open a pull request with your work. In the PR description, include the words "closes #8843"

**Comment by avneet14027** [comment]
I attempted to work on this and created a pull request for this issue here: https://github.com/gatsbyjs/gatsby/pull/8862 , please let me know if  changes are required . Thanks.
