### ISSUE TITLE
Content migration - create Hosting on Netlify doc

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#8844]
## Issue Context

This issue is part of the content migration project (#8103), which is meant to take existing content and *repurpose* it so it's easier to find in the docs.

### Motivation

We are doing this because many people have written excellent content that we want to canonize and maintain so more people can find it and benefit from it.

### Review the Gatsby docs approach

- [ ] Read the Style Guide and follow it in order for your PR to be accepted. Pay special attention to the templates. 
  - Style Guide: https://www.gatsbyjs.org/docs/gatsby-style-guide/
  - Docs Templates: https://www.gatsbyjs.org/docs/templates/

### Draft the doc

- [ ] Create a new file named `hosting-on-netlify.md` in the [docs source directory](https://github.com/gatsbyjs/gatsby/tree/master/docs/docs).
- [ ] Begin the newly-created markdown file with the following frontmatter:

```
---
title: Hosting on Netlify
---
```

- [ ] Use the following reference material as a primary starting point to draft the new doc:
https://www.gatsbyjs.org/blog/2017-11-09-why-i-created-my-blog-with-gatsby-and-contentful/#hosting-with-netlify
https://www.gatsbyjs.org/blog/2017-12-06-gatsby-plus-contentful-plus-netlify/#solution-netlify--gatsby 

Make sure you rewrite and adjust the content to follow the format listed in these resources:
  - Docs Templates: https://www.gatsbyjs.org/docs/templates/
  - Example of a guide to imitate: https://www.gatsbyjs.org/docs/deploying-to-s3-cloudfront
- [ ] Add a link to the [`doc-links.yml`](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml)file so your newly created doc shows up in the sidebar navigation of the .org site!

### Open a pull request
- [ ] Open a pull request with your work, including the words "closes #8844"

**Comment by thakkaryash94** [comment]
I would like to work on this issue.

**Comment by shannonbux** [comment]
Hi @thakkaryash94 sounds great! Go ahead and add the label `hacktober - claimed` and then mention that your PR closes this issue (see last checkbox on list in this issue).

**Comment by thakkaryash94** [comment]
Hey @shannonbux I have one doubt. Should I only need to write about how to host public folder on netlify or I need to write how to configure github with netlify, build and deploy using netlify?
