### ISSUE TITLE
Content migration - create Layout Components doc

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#8845]
## Issue Context

This issue is part of the content migration project (#8103), which is meant to take existing content and *repurpose* it so it's easier to find in the docs.

### Motivation

We are doing this because many people have written excellent content that we want to canonize and maintain so more people can find it and benefit from it.

### Review the Gatsby docs approach

- [ ] Read the Style Guide and follow it in order for your PR to be accepted. Pay special attention to the templates. 
  - Style Guide: https://www.gatsbyjs.org/docs/gatsby-style-guide/
  - Docs Templates: https://www.gatsbyjs.org/docs/templates/
  - Example of a similar article: **[todo: find and link to appropriate article for new issue]**

### Draft the doc

- [ ] Create a new file named `layout-components.md` in the [docs source directory](https://github.com/gatsbyjs/gatsby/tree/master/docs/docs).
- [ ] Begin the newly-created markdown file with the following frontmatter:

```
---
title: Layout components
---
```

- [ ] Use the following reference material as a primary starting point to draft the new doc: 
https://www.gatsbyjs.org/tutorial/part-three/

 Make sure you rewrite and adjust the content to follow the format listed in these resources:
  - Docs Templates: https://www.gatsbyjs.org/docs/templates/
  - Example of a guide to imitate: https://www.gatsbyjs.org/docs/deploying-to-s3-cloudfront
- [ ] Review the following additional reference materials, and integrate any additional detail, if helpful:
- https://www.gatsbyjs.org/blog/2018-06-08-life-after-layouts/
- [ ] Add a link to the [`doc-links.yml`](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml)file so your newly created doc shows up in the sidebar navigation of the .org site!

### Open a pull request
- [ ] Open a pull request with your work. In the description, include the words "closes #8845"

**Comment by eunicode** [comment]
Hi, can I take a stab (Halloween pun intended) at this?

**Comment by shannonbux** [comment]
Yes, just label it with `Hacktoberfest - claimed` and then mention this issue in your PR! Thanks @eunicode!
