### ISSUE TITLE
Content migration - create Optimizing site performance with Guess.js doc

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#8846]
## Issue Context

This issue is part of the content migration project (#8103), which is meant to take existing content and *repurpose* it so it's easier to find in the docs.

### Motivation

We are doing this because many people have written excellent content that we want to canonize and maintain so more people can find it and benefit from it.

### Review the Gatsby docs approach

- [ ] Read the Style Guide and follow it in order for your PR to be accepted. Pay special attention to the templates. 
  - Style Guide: https://www.gatsbyjs.org/docs/gatsby-style-guide/
  - Docs Templates: https://www.gatsbyjs.org/docs/templates/

### Draft the doc

- [ ] Create a new file named `optimizing-site-performance-with-guessjs.md` in the [docs source directory](https://github.com/gatsbyjs/gatsby/tree/master/docs/docs).
- [ ] Begin the newly-created markdown file with the following frontmatter:

```
---
title: Optimizing site performance with Guess.js
---
```

- [ ] Use the following reference material as a primary starting point to draft the new doc: 
"Framework-based static sites" https://blog.mgechev.com/2018/05/09/introducing-guess-js-data-driven-user-experiences-web/
https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-guess-js
https://www.contentful.com/blog/2018/06/13/journey-cutting-edge-static-sites-gatsbyjs-v2/

 Make sure you rewrite and adjust the content to follow the format listed in these resources:
  - Docs Templates: https://www.gatsbyjs.org/docs/templates/
  - Example of a guide to imitate: https://www.gatsbyjs.org/docs/deploying-to-s3-cloudfront
- [ ] Review the following additional reference materials, and integrate any additional detail, if helpful:
  - References:
https://guess-gatsby-wikipedia.firebaseapp.com/
https://twitter.com/gatsbyjs/status/994277394147000320?lang=en
https://itnext.io/increase-performance-of-your-angular-react-and-gatsby-apps-with-guess-js-2214d4be0871
https://github.com/guess-js/gatsby-guess
https://syndicode.com/2018/07/18/guess-js-libraries-and-tools-for-enabling-data-driven-user-experience-on-the-web/
- [ ] Add a link to the [`doc-links.yml`](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml)file so your newly created doc shows up in the sidebar navigation of the .org site!

### Open a pull request
- [ ] Open a pull request with your work, including the words "closes #8846"

**Comment by dlaub3** [comment]
I'll work on this.
