### ISSUE TITLE
[1.0] Creating Interfaces/Unions on sourcing/transforming/typegen?

### ISSUE THREAD

**Issue by danielfarrell** [gatsbyjs/gatsby#885]
Is there a way to add Union types of Interfaces from plugins?

**Comment by KyleAMathews** [comment]
So currently there's an API for extending the graphql types that Gatsby creates. You can see implementations in gatsby-typegen-remark and gatsby-typegen-sharp.

A simplified implementation looks like:

```javascript
exports.extendNodeType = ({
  type,
}) => {
  if (type.name !== `TypeToModify`) {
    return {}
  }

  return {
    greeter: {
      type: GraphQLString,
      args: {
        name: {
          type: GraphQLString,
          defaultValue: "Bob",
        },
      },
      resolve(node, { name }) {
        return `Hi ${name}!`
      },
    },
  }
}
```

What this *doesn't* let you do is create entirely new types. Is that what you'd need? We could easily add a new API hook at https://github.com/gatsbyjs/gatsby/blob/77b15a947be84d24660a88fb30f7dce4aa2329cc/packages/gatsby/lib/schema/index.js#L17 that'd let you mutate things however you want before the schema is created.

**Comment by danielfarrell** [comment]
I think I would need to create new types for union/interface types, yeah.  I could probably change things to live without them if it's not something of interest to others, but that API hook would interest me.

**Comment by KyleAMathews** [comment]
>Should I take a stab at implementing it in a PR?

Yes please!

New API hooks are a one liner to add.

**Comment by KyleAMathews** [comment]
Open PR for this @ https://github.com/gatsbyjs/gatsby/pull/2990

**Comment by cvharris** [comment]
Is `extendNodeType` deprecated? Is the alternative recommended solution for this problem to use `setFieldsOnGraphQLNodeType`?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
