### ISSUE TITLE
Add IBM, McDonalds, Mozilla, FastCompany to site showcase

### ISSUE THREAD

**Issue by calcsam** [gatsbyjs/gatsby#8850]
Several prominent sites recently launched on Gatsby and should be added to the site showcase!

http://www.carbondesignsystem.com/
https://retirementcommunity.fastcompany.com
https://design.mcdonalds.com/
mixedreality.mozilla.org
uniform.hudl.com

**Comment by ajisilva** [comment]
Hi, I'd love to take this on. New to the project. Where would these be added?

**Comment by Janice0218** [comment]
can i take this?
