### ISSUE TITLE
Inferno v6 build succeed with gatsby

### ISSUE THREAD

**Issue by simonjoom** [gatsbyjs/gatsby#8858]
Hello this is not an issue but an experience,
Just to say i succeed to make working gatsby and inferno together.

The only thing in dev inferno cannot use hot-reload but everything work well with some little hack in core. (just some alias and turn around hot-reload in webpack.conf)
the react16 context work well, just fragment is still not well supported
I can share my experience.
:)

**Comment by KyleAMathews** [comment]
Hey nifty! You want to create and share a repo with all this working? That'd be fun to see!

**Comment by simonjoom** [comment]
i can share sure. The thing is my repo is little big, i need to do one light type hello-world inferno

**Comment by simonjoom** [comment]
Just done here. I made as simple as possible
https://github.com/simonjoom/gatsby-starter-inferno-master
Description to install and use in readme.
"npm run inferno" to start running inferno mode development
"npm run develop" run normal gatsby mode
"npm run build" build with inferno (no react)

**Comment by simonjoom** [comment]
Hello now Fragment is supported in last release of inferno-v6-rc3

**Comment by simonjoom** [comment]
Hello , ok now the stable version inferno-v6 is out )) correctly tested 
it's live with my gatsby repo published here: https://www.ski-courchevel.deals  ))
