### ISSUE TITLE
Question: Gatsby recommended method for creating multiple pages of a type, with custom content. 

### ISSUE THREAD

**Issue by lswest** [gatsbyjs/gatsby#8865]
## Summary

I'm in the process of creating a blog in Gatsby. To do this, I want to have a separate blog list page for each category of post (so far there are 4 categories, but it will increase over time). I'm not sure what the recommended approach is for Gatsby. I realize I could probably use React to create a filterable list of all the articles that way, but I want the option to be there statically for visitors who may not have JS activated.

I have seen some similar questions in the bugtracker, but they (so far) haven't really indicated to me what the recommended approach would be.

I don't need working code or step by step instructions, a simple outline of the general approach would probably be sufficient for me to implement it. My goal here is more so to learn the "right" manner of thinking for this sort of task in Gatsby than to find a working system.

## Relevant information

In traditional CMS or other static site generators I'd create a single template for a list page, and then pass the category (as well as title and description paragraph) in as a variable, which is used to fetch the content and populate the page. 

### Progress so far

In Gatsby and graphql, I seem to be able to do something similar (following the tutorials and reading the docs) by writing my query like this: 
```
query($category: String!){
allMarkdownRemark(filter: { frontmatter: { categories: { in: [$category} }}}, sort: { order: DESC, fields: [frontmatter___date] }) {
...
}
}
```

The graphql query itself is working when I run it on a single page without the variable.

However, this query parameter seems to only be usable through the CreatePage function in gatsby-node.js. I'm not sure how I'd pass in the title and description paragraph to the CreatePage function (or, indeed, how I would run CreatePage for each possible category). Perhaps I'd have to create and manage a JSON data listing for each category and page? Or Markdown pages?

### Alternative Ideas

1. I've also pondered creating a component for the blog list, but I don't think I can combine this with a query (as denoted above). Which means this would lead to a minimal reduction in repetition.
2. Run CreatePage manually from the category listing page instead of gatsby-node (i.e. book-reviews.js for the Book Reviews category).
3. Create a page template and tie it into a JS page not using CreatePage (i.e. listTemplate.js called and used from book-reviews.js). Not sure if this is possible.
4. Least interesting (to me): manually create each page, and use a named exported graphql query to reduce some of the duplication.

## Bonus question

Very simple yes/no question: does Gatsby (or JS) have some sort of slugify method, so I can generate page slugs from the titles instead of manually writing a path into the markdown frontmatter?

**Comment by NickyMeuleman** [comment]
are you getting the information you pass here? https://gist.github.com/lswest/2593a6da3064be7e88418d6bbeef892a#file-gatsby-node-js-L111

Try querying for that information in the graphql query above if you are not.

**Comment by lswest** [comment]
Ha, now I feel silly. I added the category frontmatter to the query and now everything works. Thanks!
