### ISSUE TITLE
Unable to remove undereline feature in a <Link > component

### ISSUE THREAD

**Issue by transluciddata** [gatsbyjs/gatsby#8869]
I am facing a problem when I tried to remove the underline from a <link > component. So far I am able to easily grab the <link activeClassName= "myClassName"> class name property from the sass style sheet and change any other property excepting the underline. I am not sure what I am missing. Can anyone point me out where is my mistake?

Thanks in advance

  System:
    OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
    CPU: x64 Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz
    Shell: 2.7.1 - /usr/bin/fish
  Binaries:
    Node: 8.12.0 - /usr/bin/node
    npm: 6.4.1 - /usr/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 62.0.3
  npmPackages:
    gatsby: ^2.0.0 => 2.0.0 
    gatsby-image: ^2.0.9 => 2.0.9 
    gatsby-plugin-feed: ^2.0.5 => 2.0.5 
    gatsby-plugin-google-analytics: ^2.0.5 => 2.0.5 
    gatsby-plugin-manifest: ^2.0.2 => 2.0.2 
    gatsby-plugin-offline: ^2.0.5 => 2.0.5 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-sass: ^2.0.1 => 2.0.1 
    gatsby-plugin-sharp: ^2.0.5 => 2.0.5 
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.0 
    gatsby-plugin-typography: ^2.2.0 => 2.2.0 
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.0.5 
    gatsby-remark-images: ^2.0.1 => 2.0.1 
    gatsby-remark-prismjs: ^3.0.0 => 3.0.0 
    gatsby-remark-responsive-iframe: ^2.0.5 => 2.0.5 
    gatsby-remark-smartypants: ^2.0.5 => 2.0.5 
    gatsby-source-filesystem: ^2.0.1 => 2.0.1 
    gatsby-transformer-remark: ^2.1.1 => 2.1.1 
    gatsby-transformer-sharp: ^2.1.2 => 2.1.2 
  npmGlobalPackages:
    gatsby-cli: 2.4.2

**Comment by edykim** [comment]
Did you check`box-shadow` as well? Some of styles apply underline using `box-shadow` for better styling.

**Comment by transluciddata** [comment]
thanks for that @edykim ! Your answer solved my problem!

**Comment by edykim** [comment]
Awesome! Let’s having fun with Gatsby!

**Comment by transluciddata** [comment]
I am sorry for reopening this question, but I am facing some similar problems with icons from react-icons. I tried to change the underline aesthetic using 'text-decoration: none', but that time adding 'text-shadow: none', but didn't remove the underline. Anything that I am missing? There is any way to avoid this underline aesthetic in a global way? Thanks in advance!
