### ISSUE TITLE
tests fail on fresh clone of gatsby repo

### ISSUE THREAD

**Issue by NickyMeuleman** [gatsbyjs/gatsby#8872]
## Description

I freshly cloned this repo and followed the [docs on how to contribute to the repo](https://www.gatsbyjs.org/docs/how-to-contribute/#contributing-to-the-repo)
However, some tests fail when running `yarn test` in the root of this repo.

![code_2018-10-06_19-29-46](https://user-images.githubusercontent.com/30179461/46574126-2440a700-c99f-11e8-9dc4-0193b8f2cbb1.png)

Upon visual comparison of the `expected` and `received` outputs, I see no difference.
This leads me to believe there are LF / CRLF shennanigans at play. (I'm on Windows10)

### Steps to reproduce

- Fork this repo
- Clone that fork
- `yarn run bootstrap`
- `yarn run test`

### Expected result

Tests pass

### Actual result

SOME tests fail, comparing `expected` and `received` logs in the console shows no difference.

### Environment

  System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
  Binaries:
    Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD

**Comment by lmcjt37** [comment]
@NickyMeuleman I had issues with failing tests due to my version of Yarn being slightly too old?

Would try updating and running the tests again 😇

**Comment by maysanchez** [comment]
Hi @NickyMeuleman, I followed the steps to reproduce the issue but everything works fine for me on macOS ... 
<img width="814" alt="captura de pantalla 2018-10-06 a la s 14 19 34" src="https://user-images.githubusercontent.com/7445850/46575073-f5f9a200-c973-11e8-8cf5-58eaf06c3d1b.png">  

But what about trying the  yarn stable version for windows

**Comment by edykim** [comment]
![capture](https://user-images.githubusercontent.com/33057457/46593911-6ee81f00-ca84-11e8-8001-476ac025030d.png)

I'm using Windows 10, Yarn windows nightly build and the newest version of node. I followed how to contribute page. I think Your Yarn is quite a low version for the build.

FYI, Failed tests are from `gatsby-plugin-feed` which I tried to fix with https://github.com/gatsbyjs/gatsby/pull/8906.

**Comment by pieh** [comment]
There were couple of just straight broken tests for windows (snapshot containing unix style paths) - that should be fixed in master now. But there is CRLF/LF issue - which we currently have when running tests on Azure Pipelines.

We will probably use https://help.github.com/articles/dealing-with-line-endings/#per-repository-settings to force LF line endings when people checkout code (i've been using git user setting to that on windows)

**Comment by pieh** [comment]
(that setting about forcing LF - probably just for .snap files for now)

**Comment by pieh** [comment]
Ok, so this seems to work https://github.com/gatsbyjs/gatsby/pull/8922

**Comment by NickyMeuleman** [comment]
- Upgraded Yarn
- Deleted `node_modules`
- added `.gitattributes` file from #8922 to root of project
- `git pull upstream master`
- `yarn run bootstrap`
- `yarn run test`

Test failures dropped to
```
Test Suites: 5 failed, 93 passed, 98 total
Tests:       19 failed, 693 passed, 712 total
Snapshots:   1 failed, 323 passed, 324 total
```

Will freshly clone and try again later today.

**Comment by DSchau** [comment]
@NickyMeuleman Windows, Mac, or something else? I would have expected only the snapshots to fail (if anything) not everything!

**Comment by NickyMeuleman** [comment]
@DSchau Windows

Just tried again on a fresh up-to-date clone.

![image](https://user-images.githubusercontent.com/30179461/46687399-1dae6b80-cbfb-11e8-99cc-1fe533c25a9b.png)

GREAT SUCCESS 🎉
