### ISSUE TITLE
Add featured sites to front page of gatsbyjs.org

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#8882]
Our site showcase is a great illustration of what you can do with Gatsby!

We should show everyone the awesome sites built with Gatsby and add to the front page a section of sites from the showcase that's similar to the top row of the site showcase.

Thoughts @gatsbyjs/admin?

**Comment by jlengstorf** [comment]
It'd be especially cool if the featured sites component was reusable enough to just get dropped onto the front page. 😎

**Comment by lmcjt37** [comment]
I would be willing to pick this up, if it's going?

**Comment by amberleyromo** [comment]
Hey @lmcjt37! Thanks for offering! This is still in early stages of discussion, so I'm not 100% sure it's going to happen (though it looks likely).

Despite that uncertainty, if you wanted to take a shot at it so we can see what it looks like, that would be awesome! Regardless, tacking on to @jlengstorf's comment, there's a lot of opportunity to improve and modularize this section of the codebase, so regardless of homepage decision, efforts on that front would be valuable and much appreciated! How does that sound?

**Comment by lmcjt37** [comment]
@amberleyromo Sounds good to me! I will knock a PR together and link in this issue when I’m done. Thanks
