### ISSUE TITLE
What are "client-paths" & "client-only routes"? 🤔

### ISSUE THREAD

**Issue by amingilani** [gatsbyjs/gatsby#8894]
## Summary

I was just reading the docs on [Building Apps with Gatsby](https://www.gatsbyjs.org/docs/building-apps-with-gatsby/). I'm trying to build a GraphQL server, that'll be consumed by a Gatsby powered front-end.

>A classic example would be a site that has a landing page, various marketing pages, a login page, and then an app section for logged-in users. The logged-in section doesn't need to be server rendered as all data will be loaded live from your API after the user logs in. So it makes sense to make this portion of your site client-only.

That's actually exactly what I'm building. A front-end page that's static, and then a logged-in area that fetches its information from GraphQL queries on the API. However, what are "client-paths" & "client-only routes"? I've heard this term before.

> These paths exist on the client only and do not correspond to index.html files in an app's built assets.

And this in the world does this ⬆️mean?

**Comment by coreyward** [comment]
Client = web browser, in this case. A “client-only” path or route is one that is not reflected in your statically rendered files. For example, you may wish for your client-side app to allow navigating to a page at `/messages`. You would need to add the appropriate route to your Gatsby app (via Reach Router if you're using v2) and setup the component that will handle the request, but you wouldn't have Gatsby generate a separate page at `/messages.html` or `/message/index.html`.

**Comment by amingilani** [comment]
Hrm, I suppose this needs an example to become comprehensive. But, thank you for explaining it.
