### ISSUE TITLE
gatsby-source-wikipedia missing axios dependency 

### ISSUE THREAD

**Issue by i001962** [gatsbyjs/gatsby#8900]
After adding gatsby-source-wikipedia gatsby develop puked with missing axios module.

Steps to reproduce
````
yarn add gatsby-source-wikipedia 
gatsby develop
````
error Plugin gatsby-source-wikipedia returned an error
  Error: Cannot find module 'axios'
  - loader.js:581 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:581:15

I got around the issue by adding axios with
````
yarn add axios
```` 
i.e. in package.json

"axios": "^0.18.0",

**Comment by tbaustin** [comment]
I'll make a PR for this if you haven't

**Comment by i001962** [comment]
@tbaustin I’ll do it later today. Will be fun to have contributed.

**Comment by phacks** [comment]
This issue seems to be resolved, can it be closed @pieh? Happy to do it myself (on this one and possible others) but wanted to check with you if I could.

**Comment by DSchau** [comment]
@phacks good call!


Thank you @fhavrlent for the fix!
