### ISSUE TITLE
Docs: Broken link on "GraphQL reference" page

### ISSUE THREAD

**Issue by jkjustjoshing** [gatsbyjs/gatsby#8903]
## Description

Broken link on https://www.gatsbyjs.org/docs/graphql-reference/#query-variables

Current link is to https://deploy-preview-4795--gatsbyjs.netlify.com/docs/creating-and-modifying-pages/#creating-pages-in-gatsby-nodejs, should be to https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#creating-pages-in-gatsby-nodejs

**Comment by jkjustjoshing** [comment]
Quick fix, I've submitted a PR to fix it.

**Comment by pieh** [comment]
Closed by #8904, thanks!
