### ISSUE TITLE
options of minifyJs should to be reviewed 

### ISSUE THREAD

**Issue by simonjoom** [gatsbyjs/gatsby#8905]
use correct option of minifyJs
related to 
https://github.com/facebook/create-react-app/pull/4234
to get the "why" Please read this thread upper
 
specify ecma: 5 like described in create-react-app to support ie11 and to avoid some bug on some browser.

**Comment by pieh** [comment]
This is interesting. Will need to some research

@jquense do You have any thoughts on that?

**Comment by jquense** [comment]
seems reasonable tho i'm not sure what it means in terms of output. at the point to which uglify is run the code is already compiled to the desired ecma, i'm not sure if uglify will go out of it's way to upscale syntax unless it's told not too?

in other word's i can see uglify turning multiple `let` declarations into `let  foo, bar, baz` but i don't think it will decide to use `let` in the output if the input is already `var`.

**Comment by simonjoom** [comment]
i think that just take and copy things without think too much from create-react-app is reasonable as it's a very used and debugged repo from Facebook!

**Comment by KyleAMathews** [comment]
@jquense perhaps it generates different syntax for newer versions? E.g. some new JS syntax produces smaller output so they opt into that if they can 🤷‍♂️

**Comment by shanekenney** [comment]
@KyleAMathews correct. Terser does take opportunities to use more compact syntax if the ecma version allows it. E.g. Shorthand object properties raised in issue #9034 

Here's the test documenting it:
https://github.com/terser-js/terser/blob/master/test/compress/object.js#L111

```
use_shorthand_opportunity: {
    beautify = {
        ecma: 6
    }
    input: {
        var foo = 123;
        var obj = {foo: foo};
    }
    expect_exact: "var foo=123;var obj={foo};"
}
```

**Comment by KyleAMathews** [comment]
Cool! Great to know. Could someone PR a fix?
