### ISSUE TITLE
How do I remove the underline aesthetic from react-icons? 

### ISSUE THREAD

**Issue by transluciddata** [gatsbyjs/gatsby#8908]
I am having some problems removing the underline of icons  coming from react-icons. I tried to remove it using 'text-decoration: none', adding 'text-shadow: none', but didn't remove the underline. My confusion came because I can change other features like size or color, but not the underline. Anything that I'am missing? There is any way to avoid this underline aesthetic in a global way? Thanks in advance!

**Comment by dustinhorton** [comment]
Did you mean to post this to https://github.com/react-icons/react-icons/issues perhaps? Either way, I'd create a reduced test case to try to better illustrate your issue, and allow people to help you. It doesn't like you're possibly targeting the wrong elements with your selectors, or possibly changing the wrong properties—it'd be best to first nail down the latter (is it a text decoration, shadow, border, etc.).

**Comment by transluciddata** [comment]
Here a small example! I just discovered that is the <a> tag where the underline aesthetic is being applied. So, this behaviour has nothing to do with the react-icons itself.

`import React from 'react'
import { FaFacebook, FaInstagram} from 'react-icons/fa'
import '../styles/style.scss'

const SocialLinks = () => (
  <ul className='social'>
    <a className='socialIcon' id='foo' href='https://www.facebook.com/carlos.ledesma.9210'>
      <FaFacebook />
    </a>
 
    <a className='socialIcon' href='https://www.instagram.com/ledesmamosquera/'>
      <FaInstagram  />
    </a>

  </ul>
)

export default SocialLinks
`
This is my sass style.scss sheet looks like.

`
.social {
        display: flex;
        justify-content: space-around;
        align-items: center;
        .socialIcon {
            
            font-size: 2.5vw; // That works!
            color: black; // That works!
            text-decoration: none; // That doesn't work!
        }
}
`

**Comment by tbaustin** [comment]
Maybe try targeting the `ul a.socialIcon`?

**Comment by coreyward** [comment]
This does not appear to be related to Gatsby. You may wish to re-post to the appropriate project.
