### ISSUE TITLE
npm audit security vulnerabilities

### ISSUE THREAD

**Issue by huythieugia1996** [gatsbyjs/gatsby#8909]
After install I was warned by npm of many security issues. Here is what I am seeing
These are all (except for a few) dependencies of gatsby

=== npm audit security report ===

# Run  npm update macaddress --depth 5  to resolve 2 vulnerabilities

  Critical        Command Injection

  Package         macaddress

  Dependency of   css-loader [dev]

  Path            css-loader > cssnano > postcss-filter-plugins > uniqid >
                  macaddress

  More info       https://nodesecurity.io/advisories/654

  Critical        Command Injection

  Package         macaddress

  Dependency of   cssnano [dev]

  Path            cssnano > postcss-filter-plugins > uniqid > macaddress

  More info       https://nodesecurity.io/advisories/654

# Run  npm update fill-range --depth 5  to resolve 1 vulnerability

  Low             Cryptographically Weak PRNG

  Package         randomatic

  Dependency of   http-proxy-middleware [dev]

  Path            http-proxy-middleware > micromatch > braces > expand-range >
                  fill-range > randomatic

  More info       https://nodesecurity.io/advisories/157<!--

**Comment by sidharthachatterjee** [comment]
Closing this since a new `gatsby` install now has no vulnerabilities
