### ISSUE TITLE
How to updated deployed gh-pages website on github

### ISSUE THREAD

**Issue by Kay2dan** [gatsbyjs/gatsby#8915]
I am trying to update a deployed gatsby website on github-pages.
I followed the guide as per [Gatsby docs](https://v1.gatsbyjs.org/docs/deploy-gatsby/#github-pages). Everything worked well until I made changes to master branch & want to update the deployed 'gh-pages' branch. 

However, everytime I run `npm run deploy` (as per above docs), it doesn't catch the latest changes within `master` branch & seem to be publishing the same website previously deployed again and again. 
 
I am confused about how to update `gh-pages` branch.

I tried deleting the `gh-pages` branch & rerunning the 'deploy' script, however, it still uploads the previous version. 

![screenshot from 2018-10-08 15-54-22](https://user-images.githubusercontent.com/6276091/46616469-8837ac80-cb12-11e8-843c-164289942ca5.png)

My site is a single-page website. 

I went through the search & reviewed the first couple of pages, however, didn't find any question relevent to my case. I posted this question on [SO here](https://stackoverflow.com/questions/52702184/how-to-deploy-latest-changes-to-github-pages-from-gatsby).

### Environment (if relevant)

Gatsby V1

System:
    OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
    CPU: x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 10.3.0 - ~/.nvm/versions/node/v10.3.0/bin/node
    npm: 6.1.0 - ~/.nvm/versions/node/v10.3.0/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 62.0.3
  npmPackages:
    gatsby: ^1.9.241 => 1.9.241 
    gatsby-link: ^1.6.39 => 1.6.39 
    gatsby-plugin-react-helmet: ^2.0.8 => 2.0.8 
    gatsby-plugin-sass: 1.0.19 => 1.0.19 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

error Couldn't find the required `xsel` binary. On Debian/Ubuntu you can install it with: sudo apt install xsel

  Error: Couldn't find the required `xsel` binary. On Debian/Ubuntu you can install it with: su  do apt install xsel
  
  - envinfo.js:1 i
    [lib]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:105475
  
  - envinfo.js:1 Object.copySync
    [lib]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:106001
  
  - envinfo.js:1 Object.t.writeSync.e [as writeSync]
    [lib]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:123499
  
  - envinfo.js:1 
    [lib]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:124274
  
  - envinfo.js:1 Promise.all.then.e
    [lib]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:124289
  
  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18
  
  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10
  
  - promise.js:693 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:693:18
  
  - promise.js:638 Promise._fulfill
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18
  
  - promise_array.js:126 PromiseArray._resolve
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19
  
  - promise_array.js:144 PromiseArray._promiseFulfilled
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14
  
  - promise.js:574 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26
  
  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10
  
  - promise.js:693 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:693:18
  

error UNHANDLED REJECTION

  Error: Couldn't find the required `xsel` binary. On Debian/Ubuntu you can install it with: su  do apt install xsel
  
  - envinfo.js:1 i
    [lib]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:105475
  
  - envinfo.js:1 Object.copySync
    [lib]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:106001
  
  - envinfo.js:1 Object.t.writeSync.e [as writeSync]
    [lib]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:123499
  
  - envinfo.js:1 
    [lib]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:124274
  
  - envinfo.js:1 Promise.all.then.e
    [lib]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:124289
  
  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18
  
  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10
  
  - promise.js:693 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:693:18
  
  - promise.js:638 Promise._fulfill
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18
  
  - promise_array.js:126 PromiseArray._resolve
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19
  
  - promise_array.js:144 PromiseArray._promiseFulfilled
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14
  
  - promise.js:574 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26
  
  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10
  
  - promise.js:693 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:693:18

### File contents (if changed)

`gatsby-config.js`: 

```
module.exports = {
  siteMetadata: {
    title: 'phlo - Crypto wave',
  },
  plugins: ['gatsby-plugin-react-helmet', 'gatsby-plugin-sass'],
  pathPrefix: '/phlo_website',
  //   pathPrefix: '/',
};
```

`package.json`: 
```
{
  "name": "synonymes-app",
  "description": "Synonymes App",
  "version": "0.1.0",
  "author": "Cethy <charles-elie@cethyworks.com>",
  "dependencies": {
    "bloomer": "^0.6.3",
    "bulma": "^0.6.2",
    "font-awesome": "^4.7.0",
    "gatsby": "^1.9.241",
    "gatsby-link": "^1.6.39",
    "gatsby-plugin-react-helmet": "^2.0.8",
    "gatsby-plugin-sass": "1.0.19",
    "nuka-carousel": "^4.4.0",
    "react-helmet": "^5.2.0",
    "react-responsive": "^5.0.0"
  },
  "keywords": ["gatsby"],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "dev": "gatsby develop -o",
    "deploy": "gatsby build --prefix-paths && gh-pages -d public",
    "format": "prettier --write 'src/**/*.js'"
  },
  "devDependencies": {
    "gh-pages": "^2.0.0",
    "prettier": "^1.11.1"
  }
}

```

`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by oorestisime** [comment]
Did you specify which branch you want to use for the gh-pages? when you run `npm run deploy` do you get any errors? And did you check that after you deploy the branch gh-pages has changes? Maybe a cache problem, you could try hard reloading the page (ctrl-shift-r usually)

**Comment by Kay2dan** [comment]
apologies, in the end, the issue was not related to the above, it was related to SASS config. Resolved.
