### ISSUE TITLE
[gatsby-image] add placeholderClass prop to gatsby-image

### ISSUE THREAD

**Issue by baukevanderlaan** [gatsbyjs/gatsby#8916]
## Summary

Inspired by #5745, I think a class prop on the placeholder image would be a useful addition. Would you welcome a PR for this feature?

### Basic example

```
<Img
  fluid={data.childImageSharp.fluid}
  placeholderClass="placeholder"
/>
```

### Motivation

Instead of directly setting styles on the placeholder image using `placeholderStyles`, this offers the possibility to set styles based on class using old school stylesheets.

**Comment by kakadiadarpan** [comment]
@baukevanderlaan Sure! You will need to make change [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-image/src/index.js) and [README.md](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-image/README.md)

**Comment by baukevanderlaan** [comment]
Thanks for the lead, I plan to do this next week. I suspect it's a minor thing to implement but I need to get to grips with the gatsby-dev-cli first.

**Comment by kakadiadarpan** [comment]
@baukevanderlaan I forgot to provide the link for [Contribution guide](https://www.gatsbyjs.org/docs/how-to-contribute/) earlier.

Please reach out to us if you need any help. 🙂

**Comment by baukevanderlaan** [comment]
Added in #9187
