### ISSUE TITLE
Add https://developer.bitcoin.com/ to the Site Showcase

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#8924]
Lovely new Gatsby site that recently launched!

https://developer.bitcoin.com/

**Comment by jacobc1204** [comment]
I would like to try to do this.

**Comment by KyleAMathews** [comment]
@jacobc1204 thanks, go ahead and take it! The submission instructions are @ https://www.gatsbyjs.org/docs/site-showcase-submissions/

**Comment by KyleAMathews** [comment]
Fixed in https://github.com/gatsbyjs/gatsby/pull/8931
