### ISSUE TITLE
Using gatsby-image with CSS grids

### ISSUE THREAD

**Issue by seanngpack** [gatsbyjs/gatsby#8935]
Hi, I am having trouble getting gatsby-image fluid to play nice with CSS grids. So here's my question:

I'm putting gatsby-image <Img /> components with fluid images set with 'maxHeight' and 'maxWidth'.

              childImageSharp {

                fluid(maxWidth: 1000, maxHeight: 700) {

                  ...GatsbyImageSharpFluid

                }

      }

If I set the grid row to a pixel height < pixel height of the image, the image will overflow. **Basically the fluid image is not resizing to the CSS grid**. Shouldn't the fluid image resize to fit its container? How can I fix this?

<img width="898" alt="screen shot 2018-10-08 at 6 07 44 pm" src="https://user-images.githubusercontent.com/35155526/46641200-2cc2ea00-cb25-11e8-96b3-f71cafa5eaa6.png">

Look at the bottom two images how they extend vertically past their grid containers.

Thanks!

**Comment by seanngpack** [comment]
Thanks for the link, it's pretty insightful but I was already applying his techniques (explicit minimum dimensions).

Still can't seem to get the <Img> to fit the container properly, I might just go with fixed <img> and manually define their dimensions and make several media queries which is pretty painful and not responsive

**Comment by jordyvg** [comment]
I'm pretty sure it have to do with your css and nothing with gatsby-image. 
If the row height has the same pixel size of the image, the text above will push the image down.

Do you have a link so we can inspect it?

**Comment by c0b41** [comment]
Try [object-fit ](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) property, also nice [video](https://www.youtube.com/watch?v=5CZyxnCdXuk)  explain

**Comment by stefanprobst** [comment]
`gatsby-image` *does* set `object-fit`:
https://github.com/gatsbyjs/gatsby/blob/a1d3d7043179ebd07386a8852eafe0b5d336766c/packages/gatsby-image/src/index.js#L102

**Comment by seanngpack** [comment]
Got it working! Thanks for the helps and resources guys!

Basically what I did is choose what aspect ratio I wanted to query by selecting a maxWidth and maxHeight to fit that aspect ratio. Then in my CSS grid I set the row heights appropriately to the correct fractions and in an 'oh shoot' situation, I have overflow:hidden activated to contain any overflow(which shouldn't happen)
