### ISSUE TITLE
about site deploying using now

### ISSUE THREAD

**Issue by XHMM** [gatsbyjs/gatsby#8943]
I tried following the doc [deploying to now](https://www.gatsbyjs.org/docs/deploying-to-now/#deploying-to-now) to deploy my site . After several times , I find it's really time-wasting and cumbersome .

Because every time I run `now` in my root folder, `now-cli` will do  `upload files -->npm install(waste time) --> npm run build(waste time) --> ... --> finished/error report(crazy)` .

But if I do like this: `gatsby build` in local and `cd public `and run `now`,  `now-cli will`  just do `upload-files --> finished` . and you don't need additional `serve` module and `serve public/` script. It's redundant, because now will do that for you already.  This way is really simple and time-saving.

Another reason I write above is that I always get an `error Generating JavaScript bundles failed` when using now  but noting wrong when build locally.

So I advice change the doc as above ~

**Comment by kakadiadarpan** [comment]
@XHMM when your project size is huge and there are a lot of pages, uploading all of them would actually take a lot of time.

But we should mention the alternative approach as well. Would you like to work on this and raise a PR?

**Comment by siddhant1** [comment]
I am working on this one

**Comment by XHMM** [comment]
@siddhant1 I think the should doc focus on not whether using node-server as your commit say, but the appropriate deploying way which user should choose 🤔
