### ISSUE TITLE
gatsby-transformer-json returning error on startup

### ISSUE THREAD

**Issue by Vazerthon** [gatsbyjs/gatsby#8961]
## Description

`gatsby develop` fails when `gatsby-transformer-json` is included in `gatsby-config.js`

Possibly related to #8804 and #8794 

### Steps to reproduce

Reproduction repo here - https://github.com/Vazerthon/gatsby-test
To reproduce error: 
- Clone repo
- Run `npm run develop` or `npm start`

Commenting out 

```
{
  resolve: 'gatsby-transformer-json',
  options: {
    typeName: 'Json',
  },
},
```
From gatsby-config gets rid of the error as does removing all `.json` files from the `data/` directory

### Expected result

Gatsby develop should run to completion and a page that says `test` should be available at localhost:8000

### Actual result

Gatsby develop crashes out with an error

```
success onPreBootstrap — 0.003 s
error Plugin gatsby-transformer-json returned an error


  TypeError: createContentDigest is not a function

  - gatsby-node.js:51 transformObject
    [gatsby-test]/[gatsby-transformer-json]/gatsby-node.js:51:26

  - gatsby-node.js:81 Object.<anonymous>
    [gatsby-test]/[gatsby-transformer-json]/gatsby-node.js:81:7

# Many similar errors trimmed

error Cannot read property 'filter' of undefined

# Many similar errors trimmed

  TypeError: Cannot read property 'filter' of undefined

  - api-runner-node.js:274 Promise.mapSeries.catch.then.results
    [gatsby-test]/[gatsby]/dist/utils/api-runner-node.js:274:42

error UNHANDLED REJECTION


  TypeError: Cannot read property 'filter' of undefined

  - api-runner-node.js:274 Promise.mapSeries.catch.then.results
    [gatsby-test]/[gatsby]/dist/utils/api-runner-node.js:274:42


npm ERR! code ELIFECYCLE
npm ERR! errno 1

```

### Environment

  System:
    OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
    CPU: x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 10.11.0 - ~/.nvm/versions/node/v10.11.0/bin/node
    Yarn: 1.10.1 - /usr/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.11.0/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 62.0.3
  npmPackages:
    gatsby: next => 2.0.0-rc.28 
    gatsby-plugin-manifest: next => 2.0.2-rc.1 
    gatsby-plugin-offline: next => 2.0.0-rc.9 
    gatsby-plugin-react-helmet: next => 3.0.0-rc.1 
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.0 
    gatsby-source-filesystem: ^2.0.2 => 2.0.2 
    gatsby-transformer-json: ^2.1.4 => 2.1.4 
  npmGlobalPackages:
    gatsby-cli: 2.4.2

**Comment by mikelax** [comment]
hello @Vazerthon I think the issue is that the `gatsby` is pinned to `next`, which is *not* pulling the latest version. If you update your package.json file and replace the next values with `^2.0.0` and then do a yarn (or npm) install I think things will work for you. `gatsby-plugin-react-helmet` can be `3.0.0`

Out of curiosity, did you clone or use a gatsby starter for this test? I am asking because if so then I think we should update the starter to be sure it's using published 2.x versions of the libraries.

**Comment by Vazerthon** [comment]
Thank you so much @mikelax, that's sorted it.

> Out of curiosity, did you clone or use a gatsby starter for this test?

Yes I did, I used this one - https://github.com/nareshbhatia/gatsby-starter-material-ui - which I don't think is official but was linked from the official docs. It looks like the author has updated it in the last month and removed all the `next`s.

Thanks again for your help.
