### ISSUE TITLE
gatsby-remark-images doesn't remove base64 background-image after image loading

### ISSUE THREAD

**Issue by ThiagoMiranda** [gatsbyjs/gatsby#8970]
## Description

I'm using gatsby-remark-images v2.0.4 with gatsby-plugin-sharp v2.06 and I'm seeing a blurry effect on my images. Seems like the background-image is not removed from the `span.gatsby-resp-image-background-image` . I have a Gatbsy v1 site that the plugin remove its property and replaces it to 
background-image: url("data:image/png");

### Steps to reproduce

Just use gatsby-remark-images and add a image in your .md file using <img>

### Expected result

The background-image of `span.gatsby-resp-image-background-image` property should be replaced like the old version:

<img width="1490" alt="captura de tela 2018-10-09 as 18 21 03" src="https://user-images.githubusercontent.com/141922/46699411-1c2b7600-cbf0-11e8-8626-ab6de92e72fb.png">

### Actual result

The background-image property remains with the base64 image. Producing this:
<img width="1497" alt="captura de tela 2018-10-09 as 18 21 29" src="https://user-images.githubusercontent.com/141922/46699435-2c435580-cbf0-11e8-9f30-839a67ed937d.png">

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.3 - /usr/local/bin/node
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 52.9.0
    Safari: 12.0
  npmPackages:
    gatsby: 2.0.10 => 2.0.10 
    gatsby-image: ^2.0.13 => 2.0.13 
    gatsby-plugin-google-analytics: ^2.0.6 => 2.0.6 
    gatsby-plugin-manifest: ^2.0.3 => 2.0.4 
    gatsby-plugin-offline: ^2.0.5 => 2.0.5 
    gatsby-plugin-postcss: ^2.0.0 => 2.0.0 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-sass: ^2.0.1 => 2.0.1 
    gatsby-plugin-sharp: ^2.0.6 => 2.0.6 
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.1 
    gatsby-remark-component: ^1.1.3 => 1.1.3 
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.0.5 
    gatsby-remark-images: ^2.0.4 => 2.0.4 
    gatsby-remark-prismjs: ^3.0.0 => 3.0.1 
    gatsby-remark-responsive-iframe: ^2.0.5 => 2.0.5 
    gatsby-remark-smartypants: ^2.0.5 => 2.0.5 
    gatsby-source-filesystem: ^2.0.1 => 2.0.2 
    gatsby-source-thirdparty: ^1.0.6 => 1.0.6 
    gatsby-transformer-remark: ^2.1.5 => 2.1.6 
    gatsby-transformer-sharp: ^2.1.3 => 2.1.3 
  npmGlobalPackages:
    gatsby-cli: 2.4.1

**Comment by kakadiadarpan** [comment]
@ThiagoMiranda can you provide a reproduction repo for this? That would make it much easier to diagnose this issue.

**Comment by ThiagoMiranda** [comment]
@kakadiadarpan Basically I have a .md that I use `gatsby-transformer-remark` to create a page from it with a img tag:
`<img class="pb-3" src="../../../assets/images/temps/o-que-e-interpag.png" alt="Informação Interpag" />`

With the old version of `gatsby-remark-images@1.5.67` it worked nicely. Now it doesn't with the 2.0.4 version. I'm having a little difficult to identify which plugin listens to the scroll event to apply the "blur up" behavior but I think that the problem is on the `gatsby-remark-images` itself. I'm using `gatsby-images` "directly" in other templates ( calling the image with an graphql ) and it works nicely.

**Comment by ThiagoMiranda** [comment]
One thing that I've noticed is that the images are loaded always ( even if the "browser viewport" is on it or not ). The blurup effect isn't working at all.

**Comment by hackhat** [comment]
I get the same thing as well, just comes out of the box. You need to put these settings:

    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              // It's important to specify the maxWidth (in pixels) of
              // the content container as this plugin uses this as the
              // base for generating different widths of each image.
              maxWidth: 1200,
              linkImagesToOriginal: false,
              backgroundColor: 'transparent',
              withWebp: true,
            },
          },
        ],
      },
    },


with     "gatsby-remark-images": "^2.0.4",

**Comment by jedrichards** [comment]
Are you using Safari by any chance? If so this could be due to `gatsby-image` not fully supporting that browser yet. There's an incoming PR to fix.

https://github.com/gatsbyjs/gatsby/pull/9451

**Comment by hackhat** [comment]
@jedrichards  using chrome. Happens all the time.

**Comment by jamesadarich** [comment]
I have a PR open which should resolve this one :) #7800

**Comment by valse** [comment]
I have the same problem with gatsby-image with blur effect on Safari only using filesystem source... the base64 opacity keeps to 1.

**Comment by iljapanic** [comment]
Any updates on this issue and when it will it be resolved?

I'm having the same problem in all the major browsers.

**Comment by iljapanic** [comment]
I would say this one is resolved. You just need to update the packages.

@valse , @ThiagoMiranda can you confirm?

**Comment by valse** [comment]
Hi @iljapanic, I can confirm that the issue is resolved. Thanks
