### ISSUE TITLE
Blank localhost page

### ISSUE THREAD

**Issue by linardsb** [gatsbyjs/gatsby#8976]
## Description

When adding styled components to an index.js localhost is completely blank, no errors. 

### Steps to reproduce

https://we.tl/t-8wYPU8CRus 

- Add `Section.js` in  `components` folder
- update `index.js` in `pages` folder

Note: 
This issue happened only after I added `Section.js` in  `components` folder AND updated 
`index.js` in `pages` folder

Note2:
Same result when I remove `Section.js` and remove `<Section/>` components from `index.js`

### Expected result

render pages

### Actual result

blank localhost page

### Environment

  System:
    OS: macOS High Sierra 10.13.3
    CPU: x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.3 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 61.0.1
  npmPackages:
    gatsby: ^1.9.277 => 1.9.277
    gatsby-link: ^1.6.46 => 1.6.46
    gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11
  npmGlobalPackages:
    gatsby-cli: 2.4.3

**Comment by kakadiadarpan** [comment]
@linardsb did you had a chance to go through [styled-components](https://v1.gatsbyjs.org/docs/styled-components/#styled-components) documentation for `Gatsby`?

**Comment by linardsb** [comment]
Thank you @kakadiadarpan I updated my styled components in `gatsby-config`  however still no luck. 
The problem is, that I cannot see any error, neither in browser or terminal. 
Just this: 
![console output](https://user-images.githubusercontent.com/9683093/46762163-4eaba080-ccce-11e8-947d-ba2ec3d44c3d.png)

**Comment by linardsb** [comment]
Ha, got another error tho: 
`Section(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.`

Thanks for checking this, will have to see whats wrong now.

**Comment by linardsb** [comment]
Thank you @lovenick, its sorted now.
