### ISSUE TITLE
Add FCFCU, ATTN.com, Swapcard to Site Showcase

### ISSUE THREAD

**Issue by calcsam** [gatsbyjs/gatsby#8978]
Add the following sites to the Site Showcase:

https://fcfcu.com/
https://www.attn.com/
https://www.swapcard.com/

**Comment by siddhant1** [comment]
@calcsam I will work on this one

**Comment by siddhant1** [comment]
Can you tell me where should I add these websites ? (At the bottom or randomly in the middle)

**Comment by kakadiadarpan** [comment]
@siddhant1 you can add them at the bottom. You can check this [link](https://www.gatsbyjs.org/docs/site-showcase-submissions/#steps) for additional information.

**Comment by siddhant1** [comment]
Sure, working

**Comment by siddhant1** [comment]
@kakadiadarpan can you tell me where should I look for the relevant information about these sites, Is there any document that they have filled or should I add them by going through the websites.

**Comment by kakadiadarpan** [comment]
@siddhant1 Yes, you'll need to visit the sites to get relevant information about them. If you can't find information about them, let us know 🙂
