### ISSUE TITLE
[remark] Table of contents doesn't sanitize HTML elements correctly

### ISSUE THREAD

**Issue by resir014** [gatsbyjs/gatsby#8982]
## Description

I'm not sure when this issue started appearing, but I can remember this to not be an issue not long ago. It seems that on the generated table of contents, any headings with any additional HTML elements attached to it (e.g. code) is not sanitised properly.

### Steps to reproduce

* Create a page template that consumes `markdownRemark.tableOfContents` [(e.g.)](https://github.com/kata-ai/kata-platform-docs/blob/master/src/templates/page.tsx#L84-L90)
* Create a Markdown page with one or more headings [(e.g.)](https://github.com/kata-ai/kata-platform-docs/blob/e803cbaa3098adbf7085a17f474d495dc0e99a60/docs/tutorial/nl-studio.md)
* Add an inline code block on one of the headings

### Expected result

Table of contents should be free from any HTML elements.

### Actual result

Table of contents include some unsanitised HTML. (see below)

![image](https://user-images.githubusercontent.com/5663877/46724687-c06ef480-cca4-11e8-93d0-618d4f218a11.png)

### Environment

```
  System:
    OS: macOS 10.14
    CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.6.2 - /usr/local/bin/zsh
  Binaries:
    Node: 10.11.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.17 => 2.0.17 
    gatsby-plugin-canonical-urls: ^2.0.6 => 2.0.6 
    gatsby-plugin-catch-links: ^2.0.3 => 2.0.3 
    gatsby-plugin-google-analytics: ^2.0.6 => 2.0.6 
    gatsby-plugin-layout: ^1.0.3 => 1.0.3 
    gatsby-plugin-manifest: ^2.0.4 => 2.0.4 
    gatsby-plugin-netlify: ^2.0.1 => 2.0.1 
    gatsby-plugin-netlify-cache: ^0.1.0 => 0.1.0 
    gatsby-plugin-nprogress: ^2.0.5 => 2.0.5 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-resolve-src: ^1.1.4 => 1.1.4 
    gatsby-plugin-sharp: ^2.0.5 => 2.0.5 
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.0 
    gatsby-plugin-typescript: ^2.0.0 => 2.0.0 
    gatsby-remark-autolink-headers: ^2.0.6 => 2.0.6 
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.0.5 
    gatsby-remark-images: ^2.0.3 => 2.0.3 
    gatsby-remark-prismjs: ^3.0.1 => 3.0.1 
    gatsby-remark-responsive-iframe: ^2.0.5 => 2.0.5 
    gatsby-remark-smartypants: ^2.0.5 => 2.0.5 
    gatsby-source-filesystem: ^2.0.1 => 2.0.1 
    gatsby-transformer-json: ^2.1.3 => 2.1.3 
    gatsby-transformer-remark: ^2.1.6 => 2.1.6 
    gatsby-transformer-sharp: ^2.1.3 => 2.1.3 
  npmGlobalPackages:
    gatsby-cli: 2.4.1
    gatsby-dev-cli: 1.2.12
```

**Comment by kevjin** [comment]
Any update on this issue? It seems like only the `<` character for any additional HTML tags gets replaced with its hex value `&#x3C;` instead. Tested this with the latest 2.3.14 Gatsby version

example:
`<li><a href="/the-nodejs-http-module/#httpcreateserver">&#x3C;code class="language-text">http.createServer()&#x3C;/code></a></li>`

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
