### ISSUE TITLE
moduleNameMapper key missing from config in Typescript section of the unit testing docs

### ISSUE THREAD

**Issue by jedrichards** [gatsbyjs/gatsby#8985]
## Description

An erratum in the documentation.

The key `moduleNameMapper` and associated value is missing in the example `package.json` config in the Typescript section of the unit testing docs here: https://www.gatsbyjs.org/docs/unit-testing/#using-typescript

It's correctly included in the vanilla version of the recommended config near the start of the page here: https://www.gatsbyjs.org/docs/unit-testing/#setting-up-your-environment

### Steps to reproduce

Run through the unit testing guide, including the TypeScript section at the end. Copy and paste the config verbatim from the docs.

### Expected result

Jest unit tests run without error.

### Actual result

Tests fall over as soon as a non-ts/js file is imported.

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    Yarn: 1.13.0-20181004.1524 - ~/.yarn/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 61.0.2
    Safari: 12.0
  npmPackages:
    gatsby: 2.0.19 => 2.0.19 
    gatsby-plugin-manifest: 2.0.2 => 2.0.2 
    gatsby-plugin-offline: 2.0.5 => 2.0.5 
    gatsby-plugin-postcss: 2.0.0 => 2.0.0 
    gatsby-plugin-react-helmet: 3.0.0 => 3.0.0 
    gatsby-plugin-typescript: 2.0.0 => 2.0.0 
```

Happy to PR for this 🙇

**Comment by kakadiadarpan** [comment]
@jedrichards It would be great if you could raise a PR for this 🙂

**Comment by jedrichards** [comment]
👉 https://github.com/gatsbyjs/gatsby/pull/8988
