### ISSUE TITLE
replace NODE_ENV checks when checking build / develop to something else

### ISSUE THREAD

**Issue by pieh** [gatsbyjs/gatsby#8986]
We are using `process.env.NODE_ENV` to determine if we are running develop or build all across code base which causing a lot of weird and unexpected problems. We shouldn't use that to determine different code paths. 

We should switch to `process.env.gatsby_executing_command` like in here: https://github.com/gatsbyjs/gatsby/blob/00eeef0781c0910b9beb4ca6b3ea60626e45c3b0/packages/gatsby/src/internal-plugins/query-runner/query-queue.js#L39 
where it make sense

Currently running `NODE_ENV=production gatsby develop` will start dev server without errors, but runtime will throw errors about missing bundles because of difference in how we load page resources in production and development (that's the behaviour for gatsby v1, didn't check v2 but it for sure will have problems too)

**Comment by monsieurnebo** [comment]
It would be great!
