### ISSUE TITLE
Content migration - Importing assets programmatically with gatsby-source-filesystem

### ISSUE THREAD

**Issue by dakebl** [gatsbyjs/gatsby#9018]
## Issue Context
This issue is part of the content migration project (#8103), which is meant to take existing content and repurpose it so it's easier to find in the docs.

## Motivation
We are doing this because many people have written excellent content that we want to canonize and maintain so more people can find it and benefit from it.

## Steps to resolve this issue
Read the Style Guide and follow it in order for your PR to be accepted. Pay special attention to the templates.
Style Guide: https://www.gatsbyjs.org/docs/gatsby-style-guide/
Docs Templates: https://www.gatsbyjs.org/docs/templates/
Example of a guide to imitate: https://www.gatsbyjs.org/docs/deploying-to-s3-cloudfront
Edit the [gatsby-source-filesystem programmatic import stub article](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/gatsby-source-filesystem-programmatic-import.md).

Include these references in the "Other Resources" section at the bottom:
https://www.gatsbyjs.org/packages/gatsby-source-filesystem/?=gatsby-source-
https://www.gatsbyjs.org/starter-showcase/?d=gatsby-source-filesystem
https://www.gatsbyjs.org/packages/gatsby-source-filesystem/?=gatsby-source-
https://www.gatsbyjs.org/docs/adding-images-fonts-files/#query-for-file-in-graphql-queries-using-gatsby-source-filesystem

**Comment by dakebl** [comment]
@shannonbux Are you happy with the spec I've supplied above?

**Comment by marcysutton** [comment]
@dakebl that sounds great to me! If you're still interested in working on this, we'd love to have your contribution.

**Comment by marcysutton** [comment]
I believe this is actually covered now with the Working with Images in Markdown doc, and the Image recipes. i'm going to close the issue as such, but if anyone feels otherwise we can reopen it.
