### ISSUE TITLE
gatsby-transformer-sharp returned an error Error: The specified module could not be found.  on windows 10 64bit

### ISSUE THREAD

**Issue by hackhat** [gatsbyjs/gatsby#9020]
## Description

![image](https://user-images.githubusercontent.com/11173732/46793937-5d9b5d00-cd79-11e8-8cf5-ab7e3a98cecf.png)

Getting this error: `error Plugin gatsby-transformer-sharp returned an error Error: The specified module could not be found. 
  \\?\E:\dev\xxx\node_modules\sharp\build\Release\sharp.node`

when running `yarn dev`. Notice the strange prefix `\\?\` as well.

### Steps to reproduce

 - Clone https://github.com/reactjs/reactjs.org
 - Run `yarn`
 - Run `yarn dev`

Now you get the error.

### Expected result

No error.

### Actual result

Getting this error: `error Plugin gatsby-transformer-sharp returned an error Error: The specified module could not be found. 
  \\?\E:\dev\xxx\node_modules\sharp\build\Release\sharp.node`

### Environment

I get an error when I run this command as well `gatsby info --clipboard`, see the last line.

![image](https://user-images.githubusercontent.com/11173732/46793893-4b212380-cd79-11e8-8210-4d74857bdeb7.png)

Win 10 64bit pro. Node 8.9.0, but happens the same for 8.4.0, 9.11, 10.11...

```

  System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
  Binaries:
    Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 5.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.0.0 => 2.0.0
    gatsby-plugin-catch-links: ^2.0.0 => 2.0.2
    gatsby-plugin-feed: ^2.0.0 => 2.0.5
    gatsby-plugin-glamor: ^2.0.0 => 2.0.5
    gatsby-plugin-google-analytics: ^2.0.0 => 2.0.5
    gatsby-plugin-manifest: ^2.0.0 => 2.0.2
    gatsby-plugin-netlify: ^2.0.0 => 2.0.0
    gatsby-plugin-nprogress: ^2.0.0 => 2.0.5
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^2.0.0 => 2.0.5
    gatsby-plugin-twitter: ^2.0.0 => 2.0.5
    gatsby-remark-autolink-headers: ^2.0.0 => 2.0.5
    gatsby-remark-code-repls: ^2.0.0 => 2.0.0
    gatsby-remark-copy-linked-files: ^2.0.0 => 2.0.5
    gatsby-remark-embed-snippet: ^3.0.0 => 3.0.0
    gatsby-remark-images: ^2.0.0 => 2.0.1
    gatsby-remark-prismjs: 3.0.0-beta.6 => 3.0.0-beta.6
    gatsby-remark-responsive-iframe: ^2.0.0 => 2.0.5
    gatsby-remark-smartypants: ^2.0.0 => 2.0.5
    gatsby-source-filesystem: ^2.0.0 => 2.0.1
    gatsby-transformer-remark: ^2.0.0 => 2.1.1
    gatsby-transformer-sharp: ^2.1.3 => 2.1.3

error The system cannot find the path specified.

```

**Comment by kakadiadarpan** [comment]
@hackhat This is an installation issue of `sharp` module on windows. Please check #8546
