### ISSUE TITLE
Invalid cookie header on localhost

### ISSUE THREAD

**Issue by ryandeussing** [gatsbyjs/gatsby#903]
When I try `gatsby develop --host localhost` things look fine in the terminal but I get a browser error:

```
"statusCode": 400,
"error": "Bad Request",
"message": "Invalid cookie header"
``` 

I'm playing with a component that uses getUserMedia(), which only works over https, which should be accessible on `localhost` if I can get it working...

**Comment by KyleAMathews** [comment]
What is the network request for?

**Comment by KyleAMathews** [comment]
Like nothing is loading?

**Comment by ryandeussing** [comment]
I just solved my own issue with ngrok, which lets me tunnel an https request to my local machine, but before I tried that nothing was loading but the error when I tried loading a `react-webcam` component (which uses getUserMedia()).

Thanks!

**Comment by KyleAMathews** [comment]
Huh... weird issue. But probably isn't Gatsby related so closing it.
