### ISSUE TITLE
gatsby-plugin-sitemap returned an error ==> Error: Protocol is required

### ISSUE THREAD

**Issue by karthikbalajikb** [gatsbyjs/gatsby#9036]
## Description

executing gatsby build command fails after adding , gatsby-plugin-sitemap . 

### Steps to reproduce
![image](https://user-images.githubusercontent.com/8594076/46831730-d1615800-cdc1-11e8-8a28-dd72e089718e.png)

### Expected result

Build must be successful with sitemap.xml file created

### Actual result

Getting Error

error Plugin gatsby-plugin-sitemap returned an error
Error: Protocol is required

### Environment
System:
    OS: Windows 8
    CPU: x64 Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz
  Binaries:
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    gatsby: ^2.0.17 => 2.0.17
    gatsby-image: ^2.0.13 => 2.0.13
    gatsby-link: ^2.0.3 => 2.0.3
    gatsby-plugin-google-analytics: ^2.0.6 => 2.0.6
    gatsby-plugin-manifest: ^2.0.4 => 2.0.4
    gatsby-plugin-offline: ^2.0.5 => 2.0.5
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-plugin-sass: ^2.0.1 => 2.0.1
    gatsby-plugin-sharp: ^2.0.5 => 2.0.5
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.1
    gatsby-plugin-typography: ^2.2.0 => 2.2.0
    gatsby-remark-prismjs: ^3.0.1 => 3.0.1
    gatsby-source-filesystem: ^2.0.1 => 2.0.1
    gatsby-transformer-json: ^2.1.3 => 2.1.3
    gatsby-transformer-remark: ^2.1.6 => 2.1.6
    gatsby-transformer-sharp: ^2.1.3 => 2.1.3

**Comment by GaelS** [comment]
I encountered the same issue and I realized that the property `siteURL` of my `gatsby-config.json` file wasn't started with neither `https` or `http`. I guess you have to do the same here : Replace `KB TechSpace` by a correct url for `siteURL`.

**Comment by jonniebigodes** [comment]
@karthikbalajikb as you can see the [docs](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sitemap#how-to-use), the actual siteUrl property on your `gatsby-config.json` will have to always point to the exact url where the site will be hosted, not the name/title of the site.
And from skimming the code that same property name should be respected.
