### ISSUE TITLE
Plugin to optimize remote image loading from Uploadcare

### ISSUE THREAD

**Issue by stjepangolemac** [gatsbyjs/gatsby#9039]
## Summary

When using Netlify CMS there is an option to upload images to Uploadcare. It enables you to query for images of different sizes. I was not able to find a plugin that uses that for lazy/progressive remote image loading. There are plugins that optimize local images and this could work in a very similar fashion.

### Basic example

I don't have enough experience with Gatsby or it's plugins but I suppose you could use 90% of the code from gatsby-remark-responsive-image and just build proper img or picture tags with srcsets that point to Uploadcare.

### Motivation

This would increase the performance of image loading from remote sources, in this case Uploadcare. (maybe this could be done in a way that supports multiple image hosting services)

**Comment by pieh** [comment]
Can you show how example markdown file that reference Uploadcare looks like?

I think we could make at least inline images work with remote sources in `gatsby-remark-images`:
in here https://github.com/gatsbyjs/gatsby/blob/eb7648c9e6716772608358e534b0267239c0d1dc/packages/gatsby-remark-images/src/index.js#L226 we skip checking if it's relative path and move that check to `generateImagesAndUpdateNode` function and in there we would need 2 code paths - one for local paths and one for remote paths (remote paths will need to download image - possibly using `createRemoteFileNode` function imported from `gatsby-source-filesystem` and from there generation of responsive images would be the same for both local and remote files).

paths to image in frontmatter would be more challenging at this point (we don't have way to transform them right now :/)

**Comment by stjepangolemac** [comment]
Here is the example image from the markdown that is uploaded with Uploadcare widget from the netlifycms admin panel.

``` md
![](https://ucarecdn.com/0efc717f-9067-48f9-8cbc-45f44674b0bb/-/preview/-/enhance/47/)
```

Did I paste the right thing or you need something else?

**Comment by jhlabs** [comment]
@pieh I am having the exact same user case as @stjepangolemac describes. An example of a Netlify CMS markdown created page with links to Uploadcare looks like this:

```markdown
---
date: 2018-12-07T10:31:19.256Z
title: New Blog Title
thumbnail: 'https://ucarecdn.com/84e07501-2e46-44b4-9f55-415d9fbe91ae/'
---
Article content with inline image:
![](https://ucarecdn.com/a0a47592-ebf2-470e-9f47-872324aad39a/)
```

**Comment by treb0r** [comment]
Bump!
