### ISSUE TITLE
Props not being passed to components that use { props.children }

### ISSUE THREAD

**Issue by Notches** [gatsbyjs/gatsby#9041]
## Description
When a component makes use of {props.children} for a styled wrapping component, you are unable to adapt the component based on props you passed in. 

### Steps to reproduce

https://codesandbox.io/s/m54pk58q59

### Expected result

Passed props should be available to adapt the component in its definition for components which use {props.children}.

### Actual result

Passed props are ignored when trying to use them to adapt the style of a component which makes use of {props.children}.

**Comment by LeKoArts** [comment]
You have to pass the prop:
https://codesandbox.io/s/0p2rj79xwv
