### ISSUE TITLE
[site-showcase] filters should cause scroll-down

### ISSUE THREAD

**Issue by calcsam** [gatsbyjs/gatsby#9048]
## Summary

URLs (and possibly interactions with filters) should cause the Site Showcase to scroll down past the "Featured" header 

### Basic example

Eg: https://www.gatsbyjs.org/showcase/?filters%5B0%5D=Bank should load here:

![image](https://user-images.githubusercontent.com/4388699/46857635-31ee9600-cdbe-11e8-9f7c-e03fe3b5a4bc.png)

instead of here:

![image](https://user-images.githubusercontent.com/4388699/46857654-3b77fe00-cdbe-11e8-8b95-cc16b9c53b23.png)

### Motivation

This will allow filter settings such as personal sites, blogs, e-commerce, etc, to be more easily linkable and usable from other parts of the site and externally.

cc @gatsbyjs/ecosystem

**Comment by MikeBudimon** [comment]
I would like to work on this issue.

**Comment by fk** [comment]
👌🙏 Go for it Mike!

**Comment by amberleyromo** [comment]
@MikeBudimon any interest in still working on this?

**Comment by MikeBudimon** [comment]
@amberleyromo yeah I am still intrested. 
Next week I could work on issue #11001 to unblock this issue and then work on this one.

**Comment by wardpeet** [comment]
It would be really great if this can get fixed :smile:. For anyone who wants to here are some pointers that I think, need to be done. Feel free to ignore and do it differently 😄.

**What needs to be done?**:
We should not trigger the scrollToAnchor code when the list of items is empty

** What I think needs to be done:**
We load the filtered-list in
https://github.com/gatsbyjs/gatsby/blob/c591eb774ba355543a2be7d529701cfa5bb56b5f/www/src/views/showcase/index.js#L65-L69

The data here is the unfiltered list and filtering is done inside the filtered-list component. The filtering is done here:
https://github.com/gatsbyjs/gatsby/blob/c591eb774ba355543a2be7d529701cfa5bb56b5f/www/src/views/showcase/filtered-showcase.js#L80-L82

We need to lift this code out of the filtered-showcase component into the showcase/index.js file. When the filtering logic is inside the index.js file we can use it to trigger or not trigger the scrolling behavior defined in:
https://github.com/gatsbyjs/gatsby/blob/c591eb774ba355543a2be7d529701cfa5bb56b5f/www/src/views/showcase/index.js#L44

**Comment by rbelow** [comment]
Hello everyone! Thanks for the cool work at Gatsby. I checked the behavior of the _Showcase_ filter with: https://www.gatsbyjs.org/showcase/?filters%5B0%5D=Design - and it seems to scroll to the correct position (it shows the _Design_ cases). Maybe I have misinterpreted the description. Is this still an Issue, @wardpeet ? Are you working on it, @MikeBudimon ?

**Comment by LekoArts** [comment]
Yeah, seems to be fixed!
