### ISSUE TITLE
Client only SPA using Gatsby, but at the root level

### ISSUE THREAD

**Issue by i8ramin** [gatsbyjs/gatsby#9065]
Hi, I've read the [post about using Gatsby for client-only routing and apps](https://www.gatsbyjs.org/docs/building-apps-with-gatsby/), with all the examples assuming that your "app" will be under a subfolder (ie, /app). Wondering if its possible to have your app run under the "root" of the application vs a subfolder

**Comment by pieh** [comment]
You definitely can - in fact our example is using root path and not subfolder: https://github.com/gatsbyjs/gatsby/tree/master/examples/client-only-paths
