### ISSUE TITLE
[develop] Building large volumes of basic pages is slow

### ISSUE THREAD

**Issue by Ehesp** [gatsbyjs/gatsby#9089]
## Description

Using the basic Gatsby starter project, I'm experimenting the performance of creating a large number of pages from mock data (10,000) with nothing else. This will come from an external API at some point if performance is quick enough.

The actual creation of the pages is quick, however there's always a 70-80s (local) period of `run graphql queries`. My component/page is a simple React component, with no queries.

I'm not sure if this is normal, but I'm not exactly sure what is being queried?

Performance is fine using `gatsby build`, even on a cold start. I thought it could be to do with `context` on the `createPage` but removing it causes the same result.

> My `gatsby-config` and `pages/` are empty.

### Steps to reproduce

```js
// gatsby-node.js
const data = require('./data');

exports.createPages = ({ actions }) => {
  console.log(`Creating ${data.length} pages`); // Creating 10000 pages

  for (let i = 0, len = data.length; i < len; i++) {
    const item = data[i];

    actions.createPage({
      path: `/${item.username.toLowerCase()}`,
      component: require.resolve('./src/templates/test.js'),
      context: item,
    });
  }

  return;
};
```

```js
// ./src/templates/test.js
import React from 'react';

export default function Test() {
  return (
    <div>
      Test Page
    </div>
  );
}
```

### Expected result

I was hoping it'd skip, or not have to query anything as I've got nothing graphql related going on, causing a very quick build time.

### Actual result

Gatsby spends 70-80s running graphql queries which don't exist.

```
$ gatsby develop
success open and validate gatsby-config — 0.026 s
success load plugins — 0.193 s
success onPreInit — 0.398 s
success delete html and css files from previous builds — 1.295 s
success initialize cache — 0.009 s
success copy gatsby files — 0.066 s
success onPreBootstrap — 0.007 s
success source and transform nodes — 0.148 s
success building schema — 0.185 s
Creating 10000 pages
success createPages — 3.470 s
success createPagesStatefully — 0.014 s
success onPreExtractQueries — 0.000 s
success update schema — 0.885 s
success extract queries from components — 0.033 s
success run graphql queries — 71.411 s — 9982/9982 139.79 queries/second
success write out page data — 0.183 s
success write out redirect data — 0.003 s
success onPostBootstrap — 0.028 s
```

### Environment

```
  System:
    OS: macOS 10.14
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.7.0 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 43.0.4
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.19 => 2.0.19 
    gatsby-plugin-manifest: ^2.0.5 => 2.0.5 
    gatsby-plugin-offline: ^2.0.5 => 2.0.5 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
  npmGlobalPackages:
    gatsby-cli: 2.4.3
```

**Comment by KyleAMathews** [comment]
Gatsby is writing out the data you add via context during the graphql stage as we combine the data from context and any graphql query at that time and write it out.

Could you compare your site to our create-pages benchmark as it seems like your site is a bit slower than I'd expect though the exact speed of different operations depend a lot of hardware and the site itself.

https://github.com/gatsbyjs/gatsby/tree/master/benchmarks/create-pages

**Comment by Ehesp** [comment]
Hey @KyleAMathews ,

The results are sub 20s (see below) for `build` on the create-pages benchmarking, however the same results also show when running `develop`. Even removing `context` from the `createPage` function causes the same issue.

Results are below for full build on `create-pages`:

build:
5000 - 14.624s
10000 - 17.442

develop:
5000 - 21.337s
10000 - 72.408s

**Comment by KyleAMathews** [comment]
Ah ok. So the reason for the difference is simply we've spent more time optimizing the data layer for builds as the intention is that you don't run all queries up front during development so their speed isnt as important. @pieh is working on a PR to do this actually.

**Comment by Ehesp** [comment]
Thanks - makes sense, it's only the initial boot time on dev which is a pain.

@pieh do you have a PR link?

Cheers guys

**Comment by pieh** [comment]
@Ehesp I didn't create PR yet - check this comment to see status https://github.com/gatsbyjs/gatsby/issues/7348#issuecomment-427793635 and demo of how it would work

**Comment by Ehesp** [comment]
Nice one - I'll keep track over there. Thanks for the help.

**Comment by jackblackCH** [comment]
I checked  #7348 but it seems not to solve the issue.

I am dealing with the same problem. I create 1000 pages with `createPage()` and for performance reasons I removed all page queries from the template.

So the data comes prepared as pageContext into the template, but Gatsby needs so much time while `running page queries`, like 1s per page. but there are no page queries!

**Comment by KyleAMathews** [comment]
@jackblackCH can you share with us a reproduction of your site so we can look at it?

**Comment by jackblackCH** [comment]
Sure, I'll prepare it.
