### ISSUE TITLE
State not passed between pages when using "navigate" or "<Link>"

### ISSUE THREAD

**Issue by lemon-31** [gatsbyjs/gatsby#9091]
Hi all,

I have been unsuccessful in my attempts to pass the state between pages in my Gatsby v2 application.

Here is my attempt using the "Link" component:

```javascript
<Link to="/text-editor/" state={{docId: "123"}}>Edit</Link>
```
On my "text-editor" page I run:
```javascript
componentDidMount(){
  console.log(this.props);
}
```
Unfortunately the object logged to the console is a blank object.

I then tried to use the "navigate" method instead:
```javascript
actionMenuEditHandler(){
    navigate('/text-editor/',
      {
        state: {
          docId: "123",
        },
      }
    );
  }
```
But unfortunately the object logged to the console is a blank object again.

Is anyone else experiencing this issue? I'm using: gatsby@2.0.22

Cheers,

Alex

**Comment by lemon-31** [comment]
Update:

I just found the state data located at:
``` javascript
window.history.state
```
I will close the issue in a few days to give anyone time to correct me if I'm doing this wrong.

Cheers,

Alex

**Comment by lemon-31** [comment]
Thanks for the response. 

I just tested by logging the `window.location` object to my console but I did not find the state data in it. I think that in the pull request linked below by "nsimonson" passed the location state data into the history object.

https://github.com/gatsbyjs/gatsby/pull/3802

So perhaps accessing the state data via `window.history.state` is the correct way for Gatsby.

Cheers,

Alex

**Comment by yepstien1** [comment]
Alec,
thanks for this post it was very helpful- It's just odd to me that on their gatsby documentation it just uses plain 'location' and not window.history.state.

**Comment by tkim90** [comment]
Just spent hours trying to get this working 😅 Glad I found this

**Comment by sgnl** [comment]
https://www.gatsbyjs.org/docs/gatsby-link/#how-to-use-the-navigate-helper-function This page needs to be updated

**Comment by sgnl** [comment]
I was able to access my data through the page's props `location.state` 🤷‍♂️

**Comment by brootle** [comment]
it's funny that I ended up here after example from Gatsby documentation didn't work https://www.gatsbyjs.com/docs/gatsby-link/#how-to-use-the-navigate-helper-function

**Comment by mikessc** [comment]
> It's funny that I ended up here after example from Gatsby documentation didn't work https://www.gatsbyjs.com/docs/gatsby-link/#how-to-use-the-navigate-helper-function
> Just keep in mind that your gatsby build will fail because there is no **window** during server side rendering, unless you do some checks

componentDidMount solves it

**Comment by Redskinsjo** [comment]
In my case, neither in window.history.state nor location (trying with both reach router and gatsby) the state is to be found. Someone have the same problem ?

**Comment by feedm3** [comment]
I'm having mostly the same problem. Regardless of passing the state via `GatbsyLink` or `navigate()`, on the production build _sometimes_ a wrong state gets passed. The wrong state looks like this:

```
{
	"key": "1614097608725"
}
``` 

It's more or less 50% of the time I have the correct state in the `location.state` or the wrong one :( 
In development mode I haven't seen this error.

**Comment by YashKumarVerma** [comment]
> I'm having mostly the same problem. Regardless of passing the state via `GatbsyLink` or `navigate()`, on the production build _sometimes_ a wrong state gets passed. The wrong state looks like this:
> 
> ```
> {
> 	"key": "1614097608725"
> }
> ```
> 
> It's more or less 50% of the time I have the correct state in the `location.state` or the wrong one :(
> In development mode I haven't seen this error.

I get a similar output

**Comment by nickgrealy** [comment]
I had a similar issue e.g. I got the `"key": "1614097608725"`, and the state only worked first time. (like @YashKumarVerma)

I was using an onClick event on an Anchor - turns out the problem was the `href="#"` part.

```javascript
<a href="#" onClick={ () => navigate('/here', { state: { foo: 'bar' } } ) }>Forgot Password?</a>
```

Removing that, fixed the issue.

```javascript
<a className="link" onClick={ () => navigate('/here', { state: { foo: 'bar' } } ) }>Forgot Password?</a>
```

**Comment by djaramilloj** [comment]
In my case, the problem was that I was trying to navigate to a subroute (Ex. '/app/home').
props.location.state started to show data only after I changed the navigation to single routes (Ex. '/home').

**Comment by abeMedia** [comment]
I have the same issue. I moved a page into a subdirectory and the state stopped working. Moving it back has fixed this.
