### ISSUE TITLE
Changes to Typography.js aren't applied without server restart

### ISSUE THREAD

**Issue by talolard** [gatsbyjs/gatsby#9095]
## Description

When following tutorial 2, [line 240](https://github.com/gatsbyjs/gatsby/blame/master/docs/tutorial/part-two/index.md#L240) implies we should be able to make a change to typography.js configuration and see the changes immediately. 

This has not been working for us when following tutorial 2. 

Additioanlly, we've tried "gatsby new " with the default starter, disabling layout.css and then configuring typography.js but the problem persists. 

If we restart the gatsby server the new changes take effect. 

Notably, if we look at the console output of the development server, nothing is emmited when we alter typography.js (where we configure typography). Perhaps it is being ignored by some watcher ? 
Also, if we hotswap themes instead of hand crafted styled, the changes **do** take effect

### Steps to reproduce
Follow the [second part of the tutorial](https://www.gatsbyjs.org/tutorial/part-two) upto [here](https://www.gatsbyjs.org/tutorial/part-two/#component-css). 

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

When changing
```js
src/utils/typography.js
import Typography from "typography"

const typography = new Typography({ baseFontSize: "18px" })

export default typography
```
to 

```js
src/utils/typography.js
import Typography from "typography"

const typography = new Typography({ baseFontSize: "24px" })

export default typography
```

Fonts should get bigger
### Actual result
Everything stays the same

### Environment

  System:
    OS: Linux 4.15 Ubuntu 16.04.3 LTS (Xenial Xerus)
    CPU: x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 10.10.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 62.0.3202.94
    Firefox: 62.0.3
  npmPackages:
    gatsby: ^2.0.19 => 2.0.19 
    gatsby-plugin-manifest: ^2.0.5 => 2.0.5 
    gatsby-plugin-offline: ^2.0.5 => 2.0.5 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-typography: ^2.2.0 => 2.2.0 
  npmGlobalPackages:
    gatsby-cli: 2.4.2

**Comment by ammarbinfaisal** [comment]
The same is happening with me when I am using plain css/sass
And I am have Ubuntu 18.04, browser is chrome 69 and node version is 10.8.0

**Comment by ammarbinfaisal** [comment]
So will this(not reloading when imported css is changed and not displaying the changes even after reloading manually) not be considered a bug? is this a part of gatsbyv2?

**Comment by matteocarpi** [comment]
Hello!

I'm reproducing the same issue but no luck even adding that line of code. 

any idea of what I might be getting wrong?

https://github.com/matteocarpi/tutorial-part-two

thanks in advance
