### ISSUE TITLE
Error while using "gatsby develop" command for starters

### ISSUE THREAD

**Issue by Luke93dev** [gatsbyjs/gatsby#9115]
## Description

Hello :) I'm new to GatsbyJS and I wanted to use some starter to begin with, but each time I get the same error while using "gatsby develop" command after creating new project using starter.

### Steps to reproduce

Error below comes from gatsby-starter-default. I installed Gatsby CLI globally, then created project using "gatsby new project_name" command and got an error while using "gatsby develop".

### Actual result

Error: ./.cache/api-runner-ssr.js
  Module not found: Error: Can't resolve 'C:UsersŁukaszDesktopgatsby_test
  ode_modulesgatsby-plugin-manifestgatsby-ssr' in 'C:\Users\Łukasz\Desktop\gatsby_test\.cache'
  resolve 'C:UsersŁukaszDesktopgatsby_test
  ode_modulesgatsby-plugin-manifestgatsby-ssr' in 'C:\Users\Łukasz\Desktop\gatsby_test\.cache'
    Parsed request is a module
    using description file: C:\Users\Łukasz\Desktop\gatsby_test\package.json (relative path: ./.cache)
      resolve as module
        looking for modules in C:\\Users\\Łukasz\\Desktop\\gatsby_test\\node_modules
          using description file: C:\Users\Łukasz\Desktop\gatsby_test\package.json (relative path: ./node_modules)
            using description file: C:\Users\Łukasz\Desktop\gatsby_test\package.json (relative path: ./node_modules/C:Us  ersŁukaszDesktopgatsby_test
  ode_modulesgatsby-plugin-manifestgatsby-ssr)
              no extension
                C:\Users\Łukasz\Desktop\gatsby_test\node_modules\C:UsersŁukaszDesktopgatsby_test
  ode_modulesgatsby-plugin-manifestgatsby-ssr doesn't exist
              .mjs
                C:\Users\Łukasz\Desktop\gatsby_test\node_modules\C:UsersŁukaszDesktopgatsby_test
  ode_modulesgatsby-plugin-manifestgatsby-ssr.mjs doesn't exist
              .js
                C:\Users\Łukasz\Desktop\gatsby_test\node_modules\C:UsersŁukaszDesktopgatsby_test
  ode_modulesgatsby-plugin-manifestgatsby-ssr.js doesn't exist
              .jsx
                C:\Users\Łukasz\Desktop\gatsby_test\node_modules\C:UsersŁukaszDesktopgatsby_test
  ode_modulesgatsby-plugin-manifestgatsby-ssr.jsx doesn't exist
              .wasm
                C:\Users\Łukasz\Desktop\gatsby_test\node_modules\C:UsersŁukaszDesktopgatsby_test
  ode_modulesgatsby-plugin-manifestgatsby-ssr.wasm doesn't exist
              .json
                C:\Users\Łukasz\Desktop\gatsby_test\node_modules\C:UsersŁukaszDesktopgatsby_test
  ode_modulesgatsby-plugin-manifestgatsby-ssr.json doesn't exist
              as directory
                C:\Users\Łukasz\Desktop\gatsby_test\node_modules\C:UsersŁukaszDesktopgatsby_test
  ode_modulesgatsby-plugin-manifestgatsby-ssr doesn't exist
        C:\Users\Łukasz\Desktop\gatsby_test\.cache\node_modules doesn't exist or is not a directory
        C:\Users\Łukasz\Desktop\node_modules doesn't exist or is not a directory
        C:\Users\Łukasz\node_modules doesn't exist or is not a directory
        C:\Users\node_modules doesn't exist or is not a directory
        C:\node_modules doesn't exist or is not a directory
        looking for modules in C:\Users\Łukasz\Desktop\gatsby_test\node_modules
          using description file: C:\Users\Łukasz\Desktop\gatsby_test\package.json (relative path: ./node_modules)
            using description file: C:\Users\Łukasz\Desktop\gatsby_test\package.json (relative path: ./node_modules/C:Us  ersŁukaszDesktopgatsby_test
  ode_modulesgatsby-plugin-manifestgatsby-ssr)
              no extension
                C:\Users\Łukasz\Desktop\gatsby_test\node_modules\C:UsersŁukaszDesktopgatsby_test
  ode_modulesgatsby-plugin-manifestgatsby-ssr doesn't exist
              .mjs
                C:\Users\Łukasz\Desktop\gatsby_test\node_modules\C:UsersŁukaszDesktopgatsby_test
  ode_modulesgatsby-plugin-manifestgatsby-ssr.mjs doesn't exist
              .js
                C:\Users\Łukasz\Desktop\gatsby_test\node_modules\C:UsersŁukaszDesktopgatsby_test
  ode_modulesgatsby-plugin-manifestgatsby-ssr.js doesn't exist
              .jsx
                C:\Users\Łukasz\Desktop\gatsby_test\node_modules\C:UsersŁukaszDesktopgatsby_test
  ode_modulesgatsby-plugin-manifestgatsby-ssr.jsx doesn't exist
              .wasm
                C:\Users\Łukasz\Desktop\gatsby_test\node_modules\C:UsersŁukaszDesktopgatsby_test
  ode_modulesgatsby-plugin-manifestgatsby-ssr.wasm doesn't exist
              .json
                C:\Users\Łukasz\Desktop\gatsby_test\node_modules\C:UsersŁukaszDesktopgatsby_test
  ode_modulesgatsby-plugin-manifestgatsby-ssr.json doesn't exist
              as directory
                C:\Users\Łukasz\Desktop\gatsby_test\node_modules\C:UsersŁukaszDesktopgatsby_test
  ode_modulesgatsby-plugin-manifestgatsby-ssr doesn't exist
  [C:\Users\Łukasz\Desktop\gatsby_test\node_modules\C:UsersŁukaszDesktopgatsby_test
  ode_modulesgatsby-plugin-manifestgatsby-ssr]
  [C:\Users\Łukasz\Desktop\gatsby_test\node_modules\C:UsersŁukaszDesktopgatsby_test
  ode_modulesgatsby-plugin-manifestgatsby-ssr.mjs]
  [C:\Users\Łukasz\Desktop\gatsby_test\node_modules\C:UsersŁukaszDesktopgatsby_test
  ode_modulesgatsby-plugin-manifestgatsby-ssr.js]
  [C:\Users\Łukasz\Desktop\gatsby_test\node_modules\C:UsersŁukaszDesktopgatsby_test
  ode_modulesgatsby-plugin-manifestgatsby-ssr.jsx]
  [C:\Users\Łukasz\Desktop\gatsby_test\node_modules\C:UsersŁukaszDesktopgatsby_test
  ode_modulesgatsby-plugin-manifestgatsby-ssr.wasm]
  [C:\Users\Łukasz\Desktop\gatsby_test\node_modules\C:UsersŁukaszDesktopgatsby_test
  ode_modulesgatsby-plugin-manifestgatsby-ssr.json]
  [C:\Users\Łukasz\Desktop\gatsby_test\.cache\node_modules]
  [C:\Users\Łukasz\Desktop\node_modules]
  [C:\Users\Łukasz\node_modules]
  [C:\Users\node_modules]
  [C:\node_modules]
   @ ./.cache/api-runner-ssr.js 11:10-102
   @ ./.cache/develop-static-entry.js

### Environment

package.json file:

{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "gatsby": "^2.0.19",
    "gatsby-plugin-manifest": "^2.0.5",
    "gatsby-plugin-offline": "^2.0.5",
    "gatsby-plugin-react-helmet": "^3.0.0",
    "react": "^16.5.1",
    "react-dom": "^16.5.1",
    "react-helmet": "^5.2.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write '**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "prettier": "^1.14.2"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  }
}

Any ideas how I can fix it?

**Comment by aslafy-z** [comment]
For reference:
- https://github.com/gatsbyjs/gatsby/issues/8189 
- https://github.com/gatsbyjs/gatsby-starter-default/issues/46

**Comment by Luke93dev** [comment]
I created project in different location and it works :) This may be the reason, path which don't include non-latin characters. Thanks for reply
