### ISSUE TITLE
Allow class instances to be passed onto Gatsby

### ISSUE THREAD

**Issue by JanLenoch** [gatsbyjs/gatsby#9117]
## Summary

Currently, only plain JavaScript objects can be passed onto Gatsby's `createNode` API method. When a class instance is passed, Gatsby build will fail with an "Unknown field … on type …" GraphQL error (#8053).

### Motivation

Our [headless CMS](https://kenticocloud.com) has a solid [JS SDK](https://github.com/Enngage/kentico-cloud-js) that works with class instances by default. We'd like to utilize it to its full potential in Gatsby. We can't ATM.

**Comment by pieh** [comment]
Some context for this - this check https://github.com/gatsbyjs/gatsby/blob/eb7648c9e6716772608358e534b0267239c0d1dc/packages/gatsby/src/schema/data-tree-utils.js#L174 would need to be changed to be smart enough to allow class instances, but blacklist at least some of them (like Date, Number, Array, Map, Set, WeakMap, WeakSet, Promise, ArrayBuffer)

**Comment by JanLenoch** [comment]
Hi @pieh , just to get an idea: Is this issue somewhere higher in the priority list (if any)? We're currently thinking of doing other plugin development and if the class instance support is on the horizon of say weeks then we'd wait for you to implement it. It would be better than writing code that we'd probably throw away after the class instance support comes. Thanks!

**Comment by pieh** [comment]
Right now I can't invest any time into doing any development on this, but I'd like to encourage You (or anyone else) to try to implement support for that and open PR (even if it's work-in-progress).

**Comment by arobida** [comment]
> Hi @pieh , just to get an idea: Is this issue somewhere higher in the priority list (if any)? We're currently thinking of doing other plugin development and if the class instance support is on the horizon of say weeks then we'd wait for you to implement it. It would be better than writing code that we'd probably throw away after the class instance support comes. Thanks!

Out of pure curiosity do you want to use classes for the purpose of using state?

**Comment by JanLenoch** [comment]
Hi @arobida , I'm not sure what you mean by saying "for the purpose of using state". Anyways, we'd like to use classes as our HCMS already has a robust JavaScript SDK that provides content as class instances. Simply put, our source plugin does not talk directly to our Delivery/Preview API endpoints. It uses the SDK to do that and consumes the data as class instances.
Did that answer your question?
