### ISSUE TITLE
Serving site from a sub directory

### ISSUE THREAD

**Issue by chasemccoy** [gatsbyjs/gatsby#9137]
I have a general question about Gatsbg relating to a bug that I’m running into. 

I would like to serve a Gatsby site from a Netlify deployment at a URL like `site.netlify.com/subdirectory`. I’ve configured Gatsby to use a path prefix of `subdirectory` and I’m building the site with prefix paths enabled. 

I’m my postbuild script I am moving the files in `public` to `public/subdirectory`. The site is now available at the correct URL. However, when I click on links within the site, Gatsby seems to be added an extra path prefix, so the URL in the address bar ends up looking like `site.netlify.com/subdirectory/subdirectory/*` which is a 404. 

What’s weird is that right clicking on a link and opening it in a new tab works fine and the extra path prefix is not added. 

Any idea what could be going on here?

**Comment by pieh** [comment]
Do you perhaps use `gatsby-plugin-catch-links`? There is issue with pathPrefix right now ( https://github.com/gatsbyjs/gatsby/issues/8907 with this plugin)

**Comment by chasemccoy** [comment]
Yes, I am using that plugin. This is most likely a duplicate of #8907
