### ISSUE TITLE
[Gatsby-plugin-less]Support override the default options of css loader

### ISSUE THREAD

**Issue by xyy94813** [gatsbyjs/gatsby#9142]
## Summary

Gatsby-plugin-less support override the default options of css loader. Such as `localIdentName` and `camelCase`.

### Basic example

in `gatsby-config.js`:
```
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-plugin-less',
      options: {
        overrideCssLoaderOpts: {
           camelCase: false,
           // ... other css loader configuration
        }
      },
    },
  ],
}
```
### Motivation

The default css loader options provided by Gatsby will set camelCase is `true`.
But the third-party lib we reference does not use `camelCase` and we need to reference its `less` file.

For example, use `antd` and `babel-plugin-import` same time.

**Comment by pieh** [comment]
Would You be interested in opening PR that adds that option? Here's walkthrough what's needed:
https://github.com/gatsbyjs/gatsby/blob/341034f9fae5b375ddfac2d273d145160ecf3e68/packages/gatsby-plugin-less/src/gatsby-node.js#L5
add something like `cssLoaderOptions` which defaults to empty object `cssLoaderOptions = {}`,
And then apply those option when we specify css loader for less rules:
https://github.com/gatsbyjs/gatsby/blob/341034f9fae5b375ddfac2d273d145160ecf3e68/packages/gatsby-plugin-less/src/gatsby-node.js#L25
`loaders.css({ ...cssLoaderOptions, importLoaders: 2 }),`
and same in https://github.com/gatsbyjs/gatsby/blob/341034f9fae5b375ddfac2d273d145160ecf3e68/packages/gatsby-plugin-less/src/gatsby-node.js#L34

**Comment by romulomachado** [comment]
I'd like to work on this if @xyy94813 can't.

**Comment by xyy94813** [comment]
It is great if @romulomachado are interested.
