### ISSUE TITLE
[Gatsby v2] In TypeScriprt, module keyword can't compile.

### ISSUE THREAD

**Issue by muukii** [gatsbyjs/gatsby#9143]
## Summary

[Gatsby v2] In TypeScriprt, module keyword can't compile.

I know `namespace` are not supported with `babel-plugin-transform-typescript`.
So, I've changed `namespace` to `module`, but build has still failed.
How to fix this?

```
SyntaxError: /path/to/site/src/templates/MemberDetailPage.tsx: Namespaces are not supported.
  157 | }
  158 |
> 159 | module MemberView 
```

### Environment (if relevant)

  System:
    OS: macOS 10.14
    CPU: x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Shell: 5.5.1 - /usr/local/bin/zsh
  Binaries:
    Node: 10.4.1 - ~/.nvm/versions/node/v10.4.1/bin/node
    Yarn: 1.7.0 - ~/.nvm/versions/node/v10.4.1/bin/yarn
    npm: 6.1.0 - ~/.nvm/versions/node/v10.4.1/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 61.0.2
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.0 => 2.0.22 
    gatsby-image: ^2.0.0 => 2.0.14 
    gatsby-plugin-google-analytics: ^2.0.0 => 2.0.6 
    gatsby-plugin-less: ^2.0.0 => 2.0.5 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-sass: ^2.0.0 => 2.0.1 
    gatsby-plugin-sharp: ^2.0.6 => 2.0.6 
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.0 
    gatsby-plugin-typescript: ^2.0.0 => 2.0.0 
    gatsby-remark-copy-linked-files: ^2.0.0 => 2.0.5 
    gatsby-remark-images: ^2.0.0 => 2.0.4 
    gatsby-remark-prismjs: ^3.0.0 => 3.0.2 
    gatsby-source-filesystem: ^2.0.3 => 2.0.3 
    gatsby-transformer-json: ^2.1.4 => 2.1.4 
    gatsby-transformer-remark: ^2.1.7 => 2.1.7 
    gatsby-transformer-sharp: ^2.1.3 => 2.1.3 
    gatsby-transformer-yaml: ^2.1.3 => 2.1.3 
  npmGlobalPackages:
    gatsby-cli: 2.4.2

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by pieh** [comment]
@resir014 Do you have any suggestions for this issue?

**Comment by resir014** [comment]
@muukii @pieh `module`s and `namespace`s cannot be compiled, as it's a limitation to the babel compiler that we use. See: https://babeljs.io/docs/en/babel-plugin-transform-typescript#caveats

I'd suggest refactoring them to use ES6 modules.

**Comment by resir014** [comment]
Nevermind, I lied. Normally I'd say both modules and namespaces behave the same and therefor should normally work, but I didn't see that `module { }` was the recommended path in the babel doc.

I'll take a closer look when I'm back home.

**Comment by resir014** [comment]
@muukii @pieh Alright, I found it: https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html

> A note about terminology: It’s important to note that in TypeScript 1.5, the nomenclature has changed. “Internal modules” are now “namespaces”. “External modules” are now simply “modules”, as to align with ECMAScript 2015’s terminology, **(namely that module X { is equivalent to the now-preferred namespace X {)**.

So I was kind of right. Both `module` and `namespace` behave similarly in modern TS, therefore it cannot be transpiled with Babel. I'm not even sure why the Babel doc recommends `module { }` anyway.

The only case that `module` will work is when you use it in the context of an ambient declaration (e.g. `declare module '*.css'`)

So unfortunately, the only viable solution is to refactor your module to use ES6 modules.

**Comment by muukii** [comment]
@resir014 
Oh, I see. I understand.
Thank you.
