### ISSUE TITLE
Documentation about caching javascripts assets needs an update

### ISSUE THREAD

**Issue by abumalick** [gatsbyjs/gatsby#9151]
## Description
Documentation about caching javascript is outdated:

https://www.gatsbyjs.org/docs/caching/#javascript

> Other files e.g. JavaScript files are not (yet) cachable. Gatsby v1 is using webpack 1 which doesn’t make it possible to produce paths tied directly to the content of the file. Gatsby v2 will ship with webpack 4 which will make possible long-term caching of our JavaScript files.

> The cache-control header should be cache-control: public, max-age=0, must-revalidate

### Steps to reproduce

mmmh, visit the documentation link https://www.gatsbyjs.org/docs/caching/#javascript

### Expected result

have the documentation about caching javascript assets for gastsby v2

### Actual result

The documentation describe what to do for gatsby v1

### Environment

/

Thanks !

**Comment by gjurgens** [comment]
I think this wasn't fixed on v2 and we still need to avoid using cache on JavaScript files.

**Comment by DSchau** [comment]
Agreed! I've added the hacktoberfest labels so hopefully someone will claim this one 💪

**Comment by tanvibhakta** [comment]
Hello I think I can work on this one!

**Comment by amberleyromo** [comment]
Awesome, thanks @tanvibhakta! Adding the "claimed" label.

**Comment by KyleAMathews** [comment]
We also need to update gatsby-plugin-netlify as part of this change https://github.com/gatsbyjs/gatsby/blob/6951db0864190015d05d763980e34424db9fbc39/packages/gatsby-plugin-netlify/src/constants.js#L28

**Comment by abumalick** [comment]
Thank you very much 👍
