### ISSUE TITLE
Union type not created properly

### ISSUE THREAD

**Issue by JanLenoch** [gatsbyjs/gatsby#9154]
## Summary

The docs ([here](https://www.gatsbyjs.org/docs/create-source-plugin/#union-types) and [here](https://www.gatsbyjs.org/docs/schema-gql-type/#foreign-key-reference-___node)) say that Gatsby creates union types of all types of nodes that appear in a foreign key relationship. Apparently there's no manual creation of GraphQLUnionType needed by the source plugin developer (as was in case of #2587).

## Relevant information

After we've [rewritten our source plugin](https://github.com/Kentico/gatsby-source-kentico-cloud/pull/10) to supply plain JS objects to `createNode` instead of class instances, we noticed that when we put IDs of nodes of **various** types into the `___NODE` field, then there's just the `__typename` property available in the GraphiQL environment. Nothing else.

### Environment (if relevant)

  System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  Binaries:
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.0.22 => 2.0.22
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-source-kentico-cloud: ^2.0.0-beta => 2.0.0-beta

error The system cannot find the path specified.

  Error: The system cannot find the path specified.

  - envinfo.js:1 Function.e.exports.sync
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:7778

  - envinfo.js:1 Object.copySync
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:104976

  - envinfo.js:1 Object.t.writeSync.e [as writeSync]
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:123499

  - envinfo.js:1
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:124274

  - envinfo.js:1 Promise.all.then.e
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:124289

  - util.js:16 tryCatcher
    [npm]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

  - promise.js:638 Promise._fulfill
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

error UNHANDLED REJECTION

  Error: The system cannot find the path specified.

  - envinfo.js:1 Function.e.exports.sync
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:7778

  - envinfo.js:1 Object.copySync
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:104976

  - envinfo.js:1 Object.t.writeSync.e [as writeSync]
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:123499

  - envinfo.js:1
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:124274

  - envinfo.js:1 Promise.all.then.e
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:124289

  - util.js:16 tryCatcher
    [npm]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

  - promise.js:638 Promise._fulfill
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

### File contents

Please check the respective files in our [source plugin repo](https://github.com/Kentico/gatsby-source-kentico-cloud) and our [starter site repo](https://github.com/Kentico/gatsby-starter-kentico-cloud).

### Repro steps

1) Clone our [new starter site](https://github.com/Kentico/gatsby-starter-kentico-cloud) and trigger `npm install`.
1) Run it via `gatsby develop`
1) Navigate to http://localhost:8000/___graphql
1) Use the following query:

    `{
      allKenticoCloudItemProjectReference {
        edges {
          node {
            elements {
              related_project_references {
                value
              }
              related_project_references_nodes {
                __typename
              }
            }
          }
        }
      }
    }`

1) Notice that only `__typename` is available under `related_project_references_nodes`

### Expected results

The `related_project_references_nodes` property should be a union type of all types included in the relationship.

**Comment by pieh** [comment]
So this is just graphql thing - when unions are used people need to use something called "Inline fragments" to get to the data - check https://graphql.org/learn/queries/#inline-fragments for general graphql docs

`gatsby-source-wordpress` also make use of unions and here's part that explain how to use them https://www.gatsbyjs.org/packages/gatsby-source-wordpress/#query-with-acf-flexible-content

**Comment by JanLenoch** [comment]
Hi @pieh , thanks!

For the future readers of this issue:

A query:

    {
      allKenticoCloudItemProjectReference {
        edges {
          node {
            elements {
              related_project_references {
                value
              }
              related_project_references_nodes {
                __typename
                ... on KenticoCloudItemBlogpostReference {
                  elements {
                    name___teaser_image__name {
                      value
                    }
                  }
                }
                ... on KenticoCloudItemProjectReference {
                  elements {
                    name___teaser_image__name {
                      value
                    }
                  }
                }
              }
            }
          }
        }
      }
    }

will produce:

    {
      "data": {
        "allKenticoCloudItemProjectReference": {
          "edges": [
            {
              "node": {
                "elements": {
                  "related_project_references": {
                    "value": [
                      "project_reference_2",
                      "clearing_obsolete_cache_entries_with_webhooks"
                    ]
                  },
                  "related_project_references_nodes": [
                    {
                      "__typename": "KenticoCloudItemBlogpostReference",
                      "elements": {
                        "name___teaser_image__name": {
                          "value": "Clearing Obsolete Cache Entries with Webhooks"
                        }
                      }
                    },
                    {
                      "__typename": "KenticoCloudItemProjectReference",
                      "elements": {
                        "name___teaser_image__name": {
                          "value": "Project reference 2"
                        }
                      }
                    }
                  ]
                }
              }
            },
            …
          }
        }
      }
    }
