### ISSUE TITLE
Search is broken on v1 documentation site

### ISSUE THREAD

**Issue by dj** [gatsbyjs/gatsby#9159]
## Description

When I search the v1 docs site, I get results for pages that only exist on v2. If I click them I get taken to an error page.

### Steps to reproduce

1. Visit https://v1.gatsbyjs.org/docs/
2. Focus search input, type in `createPage`, click first result
<img width="749" alt="screen shot 2018-10-16 at 11 55 20 am" src="https://user-images.githubusercontent.com/2610172/47029849-81c0ba80-d13a-11e8-9e04-a356f84ca96a.png">
3. You are taken to this page: https://v1.gatsbyjs.org/docs/page-creation/#oncreatepage-api

### Expected result

Results for v2 site should not show up when searching on v1 site.

### Actual result

New page loads in weird state, loading icon never goes away and my macbook pro's fans turn on. Can't immediately tell what is going on by looking at network tab.

### Environment

Able to reproduce here:
https://v1.gatsbyjs.org/docs/

Firefox 62.0.3 (64-bit)
macOS High Sierra Version 10.13.6

**Comment by siddhant1** [comment]
Should we redirect them to the v2 docs or should we block these searches?

**Comment by Yurickh** [comment]
I would say that searching from within the v1 docs should only yield results from the v1 docs, and vice-versa.

**Comment by Yurickh** [comment]
My guess here is that we'll need to create a new index in [docsearch](https://community.algolia.com/docsearch/) for the v1 docs, but I'm not sure on how to.

**Comment by fk** [comment]
@pieh I guess I know as much about this as you (probably less ;-)), but what @Yurickh commented makes sense to me.

I think adding a new config file for v1.gatsbyjs.org with the config file from https://github.com/algolia/docsearch-configs/blob/b0c02ab108e53d1e8fe7d17ba26a6546b466104e/configs/gatsbyjs.json — which should have the correct setup/selectors for v1 should work.

👋@s-pace I saw you did the last updates to `[gatsbyjs.json](https://github.com/algolia/docsearch-configs/commits/master/configs/gatsbyjs.json)`, maybe you can help us? 🙏

**Comment by s-pace** [comment]
👋 
We can continue to use the same index and add a `facetFilter` in order to reduce the scope of the search to either v1 or v2. Your analytics will be more relevant.

Could you add a meta tag within your website in order to highlight the version of your documenation? It should looks this way:

```html
<meta name="docsearch:version" content="1.0">
```

Then ping me and I will update your index

**Comment by pieh** [comment]
@s-pace thanks for info! I just have a question: v1 and v2 sites are completely separate (`www.gatsbyjs.org` vs `v1.gatsbyjs.org`) and have separate sitemaps - will that cause problems with using same index? If not we will add meta tags to v1 and v2 sites :)

**Comment by s-pace** [comment]
We can handle both sitemap normally. Let's give it a try

**Comment by Yurickh** [comment]
If it is a matter of adding the meta tags, I can look into it.

**Comment by pieh** [comment]
Thanks for offer @Yurickh - I was just doing that when you commented ;)

**Comment by Yurickh** [comment]
Looks like I wasn't fast enough XD

**Comment by fk** [comment]
💜🙏🤗🙌 @s-pace, @Yurickh and @pieh!

**Comment by fk** [comment]
And @dj, of course, and @siddhant1!
Sorry about forgetting you! 💜🙏🤗🙌
;-)

**Comment by dj** [comment]
@fk no worries!

Is this deployed / ready to be tested? I can still reproduce right now

**Comment by pieh** [comment]
Sorry for delay - it should be deployed on both v1 and v2 sites now (v1 site had problems with rebuilding but it's fixed now)

**Comment by s-pace** [comment]
I have done a crawl of your website in order to let you know what we need from our side.

Please have a look to [the requirements exposed in this PR](https://github.com/algolia/docsearch-configs/pull/603)

Quickly, we will need you to:
- update the sitemap of the v1
- update the DocSearch javascript snippet in order to filter on the proper part of your documenation.

**Comment by pieh** [comment]
So sitemap update for v1 obviously need to go in first. What about changes for client side `docSearch` init options change? If we update that before index is updated it will break our current search, right? So we would need to sync it somehow

**Comment by s-pace** [comment]
@pieh you are right.

You can update your website first and we will merge the PR asap. if you do not want the search to be stopped, you can update your client without the filters:
`algoliaOptions: { 'facetFilters': ["version:$VERSION", "tags:$TAGS"] },`
It will introduce duplicates but the search will not be broken.

We can agree on a precise date for the merge and behaves depending on your move.
