### ISSUE TITLE
Add shopflamingo.com to showcase

### ISSUE THREAD

**Issue by calcsam** [gatsbyjs/gatsby#9168]
* We should add shopflamingo.com to the showcase (https://www.gatsbyjs.org/showcase/). 
* It should be featured on top and #3 between Stitch Fix and Airbnb Data Engineering. 
* We should remove cajunbowfishing.com from the featured section (but keep in showcase, just not in featured section)

**Comment by openmedi** [comment]
I would like to try that. 😄

**Comment by pixzels** [comment]
I'd also like to try this.

**Comment by KyleAMathews** [comment]
Fixed by @openmedi in #9170 thanks!
