### ISSUE TITLE
Markdown images not showing up

### ISSUE THREAD

**Issue by josekhon** [gatsbyjs/gatsby#9172]
So I'm using the image remark plugin and I'm not able to display images from my mark down. 
This is my config settings. 
```
 `gatsby-plugin-sharp`,

    {
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: [
          'gatsby-remark-prismjs',
          'gatsby-remark-copy-linked-files',
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 800,
              linkImagesToOriginal: false
            },
          }
        ]
      }
    },
```

This is how my markdown looks. I've tried both moving the images into a separate images folder within the same folder as the markdown files, as well as just having them in the same folder as the markdown. Nothing is working. This is how my markdown looks

```
---

title: "Image "
path: "/image-dfdsf"
description: >
 Image
---
# Image

fgdgfdgfdgfdgfdgfdgffdgf
fgfdgfdg

![hm1](./images/hm1.png)
```

**Comment by pieh** [comment]
Can you create minimal reproduction repository?

**Comment by josekhon** [comment]
> Can you create minimal reproduction repository?

hi @pieh I've created a Mrepo 
https://github.com/josekhon/mrepo-gatsby

**Comment by pieh** [comment]
It seems like you were using outdated versions of packages - after updating them things works - https://github.com/josekhon/mrepo-gatsby/pull/1 .

I think we need to implement some checks and display warnings about that

**Comment by aarondack** [comment]
@pieh 

I'm curious as to what versions you updated to. I'm seeing some discrepancies with images in markdown files. FWIW, these are the package versions I'm using.

```
"gatsby-plugin-sharp": "next",
"gatsby-remark-images": "^2.0.4",
"gatsby-source-filesystem": "^2.0.4",
"gatsby-transformer-remark": "^2.1.7",
"gatsby-transformer-sharp": "latest",
```
