### ISSUE TITLE
V2: debugging, no src folder in browser dev tools

### ISSUE THREAD

**Issue by mtzfactory** [gatsbyjs/gatsby#9177]
Hi,

I'm used to work with __Gatsby V1__ and debugging there was very simple, I could see all my files inside `src` folder, see [1].

I've just created a new project in **V2** for curiosity, but I don't know how to debug my code, I can't see the `src` folder anymore.

[1] Project with Gastby V1
![screen shot 2018-10-17 at 11 17 27](https://user-images.githubusercontent.com/200234/47076275-a5e5cf80-d1fe-11e8-9ee1-12a4afa577ff.png)

[2] Project with Gatsby V2
![screen shot 2018-10-17 at 11 09 06](https://user-images.githubusercontent.com/200234/47075644-4509c780-d1fd-11e8-9b89-be75787ad3da.png)

**Comment by pieh** [comment]
Can you try adding this to your `gatsby-node.js`:

```js
exports.onCreateWebpackConfig = ({ stage, actions }) => {
  if (stage === `develop`) {
    actions.setWebpackConfig({
      devtool: `cheap-module-source-map`,
    })
  }
}
```

It should restore v1 behaviour. Seems like `devtool` setting was changed in v2 - it does seem like this definitely impact build/rebuild speed ( https://webpack.js.org/configuration/devtool/ ) so not sure if we want to restore default behaviour, but maybe we could document it
