### ISSUE TITLE
Content is not sized correctly for the viewport

### ISSUE THREAD

**Issue by sarahannnicholson** [gatsbyjs/gatsby#9190]
## Description

I ran a Lighthouse audit on my site and on the Gatsby site. I noticed the same note appearing in the "Progressive Web App" section.  Content is not oversized for the viewport. 
![image](https://user-images.githubusercontent.com/10520771/47102750-61eccd80-d1f2-11e8-943b-e9ec3fc7f545.png)

### Steps to reproduce

1. Go to the Gatsby website https://www.gatsbyjs.org/docs/ 
2. Open the chrome dev tools
3. Run a Lighthouse audit. 
4. Notice "Content is not sized correctly for the viewport" in the progressive web app section

### Expected result

Viewport size shouldn't appear in the Lighthouse  audit

### Actual result

Notice "Content is not sized correctly for the viewport" in the progressive web app section

### Investigation

The Lighthouse audit docs state `The audit passes if window.innerWidth === window.outerWidth.` [docs](https://developers.google.com/web/tools/lighthouse/audits/content-sized-correctly-for-viewport)
I went into the source of the Gatbsy site in the dev tools and put a breakpoint in the layout.js on line 63
```let isModal = false```
When i refreshed the page, my breakpoint was hit. In the console I was able to type
`window.innerWidth` and `window.outerWidth`
![image](https://user-images.githubusercontent.com/10520771/47106597-dc6e1b00-d1fb-11e8-820c-05d3af348fc5.png)

Moving to the HTML tab (with my breakpoint still hit), you can see that none of the page content has loaded yet. So the problem isn't my website or the Gatsby website is doing, content wise.
![image](https://user-images.githubusercontent.com/10520771/47106717-35d64a00-d1fc-11e8-874c-914e45a2cf47.png)

**Comment by pieh** [comment]
@fk Any clues? I'm not really familiar with gatsbyjs.org code so not even sure where to look

**Comment by fk** [comment]
No clues yet, but will take a look! 🔍

Thanks so much @sarahannnicholson for my "today I learned" 🙏 — I have to admit I _never ever_ saw "Content is not sized correctly for the viewport" anywhere yet.
Apparently it's been some time since I did a Lighthouse audit on `www`. :-/ 

Also 👍🙏 for the super detailed issue description and investigation!

**Comment by fk** [comment]
Ah, hold on. Clearly not able to multitask today/night.

> I ran a Lighthouse audit on **_my site_** and on the Gatsby site. I noticed **_the same note appearing_** in the "Progressive Web App" section. Content is not oversized for the viewport.

Do I understand this correctly and you are seeing the same warning for your website, too?

**Comment by sarahannnicholson** [comment]
Hey @fk Im glad to have been some help!

Yes I am seeing it on my website as well as the Gatsby website. Which makes me believe its a Gatsby issue. So to test that theory I added a breakpoint in the layout.js before the content had loaded, but after window had been initialized. That way I could test and confirm that the `window.innerWidth` and `window.outerWidth` were in fact not the same, and that the issue is somewhere in Gatsby's init.

**Comment by fk** [comment]
Whoa that was fast @sarahannnicholson! Thanks for the clarification/validating that I _can_ still read/process if I take a little more time. ;-)

> Im glad to have been some help!

💯!

Hmmmm. (My guts) Thinking out loud — maybe it's something that happens in relation to reach router handling focus?

**Comment by fk** [comment]
Hey @sarahannnicholson — I tried to reproduce your findings but fail to do so. Screenshot is taken at ~1600px viewport width though:

![image](https://user-images.githubusercontent.com/21834/47120787-432d1c00-d270-11e8-97e9-41e031e7b7dc.png)

Am I missing something? @pieh did you try reproducing?

**Comment by pieh** [comment]
I didn't check it yet - I don't really understand how/why `window.innerWidth` and `window.outerWidth` would not match :)

**Comment by sarahannnicholson** [comment]
@fk  I ran it again to double check :/ got the same 
![image](https://user-images.githubusercontent.com/10520771/47170624-5addc200-d2bb-11e8-999f-d1ff308f0407.png)

### Audit settings
Device: Desktop
Audits: All
Throttling: Simulated Fast 3G, 4x CPU Slowdown
Clear storage: checked

**Comment by craftedsystems** [comment]
Lighthouse 3.0.3 (Chrome Stable 70.0.3538.77) seems to have the following bug:
When you dock the Dev Tools to the right, you get the false viewport width alert. Detaching or docking the Dev Tools to the bottom solves this for me.

Desktop or mobile does not matter because the PWA test will always test for _mobile-friendy_.

**Comment by GuskiS** [comment]
Just noticed this in my page. Weirdly that it happens only when `gatsby build && gatsby serve`, cause when I'm doing `gatsby develop` everything is fine.
I also noticed that when I turn on mobile view within chrome, I can scroll x/y, however if I do manual screen resize everything is fine.

**Comment by fk** [comment]
@sarahannnicholson Maybe the comments by @craftedsystems and @GuskiS could help?

**Comment by GuskiS** [comment]
Could this be related to
```
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
```
having the `shrink-to-fit=no` part? Here is some description of what it does - https://stackoverflow.com/questions/33767533/what-does-the-shrink-to-fit-viewport-meta-attribute-do

I have always used only these `width=device-width, initial-scale=1`.

**Comment by piotrekwitkowski** [comment]
This is solved in Chrome 78 (currently in Beta)! https://github.com/GoogleChrome/lighthouse/issues/5558

**Comment by fk** [comment]
Whoa! Thanks @piotrekwitkowski! 🙏 
@sarahannnicholson, are you still with us? ;-)

**Comment by sarahannnicholson** [comment]
Hey @fk, I'm still here! :P 

Thanks @piotrekwitkowski! Looks like it wasn't Gatsby after all! Thanks everyone for the investigations :)

**Comment by fk** [comment]
Hey @sarahannnicholson! 🎉
Good to see you around! 🤗

It took us a looong time, but thanks to @piotrekwitkowski 🙏, the mystery is solved! 😉
