### ISSUE TITLE
[General GraphQL/Image question] Trouble querying for images in a component

### ISSUE THREAD

**Issue by seanngpack** [gatsbyjs/gatsby#9198]
Hi, my issue is that I cannot query my images located in `src/images` when I'm inside a component. In my index file `src/pages/index` I can query for images perfectly. 
```
imageOne: file(relativePath: { eq: "LENGJAI-black.jpg" }) {
      childImageSharp {
        fluid(maxWidth: 1000) {
          ...GatsbyImageSharpFluid
        }
      }
    }
```

Then I'd pass it to my Navbar

`
<Navbar data = {data} /> `

Now I'm working with a layout component and templates so I'd like the navbar to query for images inside its own component located in `src/components`

I'm using the exact same query in my Navbar component now and I'm getting the error that I cannot get the info from 'undefined' which means the query is not working.

So I guess I have three questions that need to be answered:
* And I just writing my relative path wrong because I'm in a component now?
* Is there some sort of weird under the hood mechanism that I cannot use GraphQL in components?
* Can I query in the template file? If I can query in the template file then I can structure my data flow so it looks like this: Query data in Template File --> Layout component --> Navbar

Thanks so much!

**Comment by jonathancary** [comment]
@seanngpack Were you able to get this to work? I'm trying to do something similar where I query the main page image in the page.js and then import that into my mainbg.js component so the main image is different on every page, but have not been able to get it working after a long time trying to figure it out.

**Comment by seanngpack** [comment]
@jonathancary Yup, I figured it out! You have to use a [Static Query](https://www.gatsbyjs.org/docs/static-query/). You cannot use GraphQL in components without this black-box component.

**Comment by jonathancary** [comment]
@seanngpack nice, I'll take a look. Thanks!
