### ISSUE TITLE
Infinite &no-cache=1 redirect loop 

### ISSUE THREAD

**Issue by TylerBarnes** [gatsbyjs/gatsby#9199]
## Description

Some pages are redirecting infinitely with &no-cache=1 being appended to the end of the url over and over.

### Steps to reproduce

The issue only happens in build, everything works fine in develop.

You can see the issue at 
https://baread.netlify.com/featured-projects
https://baread.netlify.com/team
https://baread.netlify.com/contact

oddly it doesn't happen at 
https://baread.netlify.com/what-we-do/
https://baread.netlify.com/

Example project at https://github.com/TylerBarnes/infinite-redirect-no-cache-loop

I'm using gatsby-source-wordpress and I used the same set up that I have here in another project recently and didn't have this issue. I can't figure out what's different between the two though, everything looks the same to me.

I spent 8 hours today commenting out components, removing pages, removing parts of graphql queries while running `yarn run clean && gatsby build && gatsby serve` with almost no luck.
On a branch I was able to get it to build and not infinitely redirect after I removed almost every component and all my childimagesharp queries but I really couldn't figure out what specifically is causing the issue. 

### Expected result

Pages don't redirect infinitely in the production build

### Actual result

Pages redirect infinitely.

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.4 - /usr/local/bin/node
    Yarn: 1.2.1 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  npmGlobalPackages:
    gatsby-cli: 2.4.3

**Comment by KyleAMathews** [comment]
Can you confirm please you're on the latest version of all gatsby packages?

**Comment by TylerBarnes** [comment]
Wow, I should've asked the pros before beating my head against the computer all day. Noob mistake. That solved it immediately. Thanks Kyle! You're a saviour!
