### ISSUE TITLE
Gatsby works with material-ui?

### ISSUE THREAD

**Issue by hackhat** [gatsbyjs/gatsby#9200]
So I added material ui v3 to gatsby and the modals are broken. See more here https://github.com/mui-org/material-ui/issues/13288

I wonder if is a problem with gatsby or material ui?

**Comment by c0b41** [comment]
probably duplicate #8237

**Comment by hackhat** [comment]
Looks like the main problem is the inline styles by material ui are not added.

**Comment by hackhat** [comment]
I need to add the position myself now.

**Comment by oliviertassinari** [comment]
@hackhat Do you have an example? It should be working! At least, it's working with our official example: https://github.com/mui-org/material-ui/tree/master/examples/gatsby.

**Comment by hackhat** [comment]
Yes is working all fine.
