### ISSUE TITLE
Caching files Gatsby V2 ?

### ISSUE THREAD

**Issue by RobinHerzog** [gatsbyjs/gatsby#9206]
The documentation about caching javascript is still about v1.

https://www.gatsbyjs.org/docs/caching/

Is it possible to cache javascript files now ?

**Comment by pieh** [comment]
Ah yeah - you can long term cache now ( https://github.com/gatsbyjs/gatsby/pull/6905 ). Would you be interested in updating that doc page - https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/caching.md ?

**Comment by siddhant1** [comment]
i think someone is already working on this #9151
