### ISSUE TITLE
Page scroll height of a rendered markdown page shows a lesser value on the first load

### ISSUE THREAD

**Issue by aswinckr** [gatsbyjs/gatsby#9208]
## Description

Page scroll height of a rendered markdown page shows a lesser value on the first load. On navigating back to the page the scroll height shows the right value again.

### Steps to reproduce

1. Install [ScrollProgress plugin](https://github.com/jeremenichelli/scrollProgress) on a rendered markdown page, preferably a long one with images. 

2. Now try printing the `scrollHeight` on `componentDidMount()` function with the code - 
```
this.progressObserver = new ScrollProgress((x, y) => {
      this.setState({ progress: y * 100 })
    })
console.log('Page height is ', this.progressObserver._viewportHeight)
```
 
### Expected result

Check the scrollHeight on the first load and consecutive loads. They are different. Perhaps this is because of lazy loading issue? If so how can I calculate the total viewport height on the first load?

### Actual result

scrollHeights should be the same even on the first load.

**Comment by kakadiadarpan** [comment]
@aswinckr can you provide a reproduction repo for this issue?
