### ISSUE TITLE
Integration of Gatsby into larger site 

### ISSUE THREAD

**Issue by josekhon** [gatsbyjs/gatsby#9210]
Has anyone integrated gatsby into a large project in which only one part of the web app will be using gatsby? I was curious about any experiences people here have had integrating gatsby as opposed to all the examples in which the entire site seems to be generated by gatsby. I'm trying to integrate gatsby into a larger client repo that uses react as well. I'd appreciate any pluses or limitations in trying to do this. I'm basically only using gatsby for generating documentation pages. Any tips on how I could even try to integrate would be appreciated.

**Comment by josekhon** [comment]
@pieh I was wondering if you have any experience with this. or any insight you could provide for me.

**Comment by DSchau** [comment]
@josekhon it depends, and there's a few considerations here.

Probably the easiest would be to deploy your documentation site at a route (e.g. /docs), which you can do [super easily with `pathPrefix`](https://www.gatsbyjs.org/docs/path-prefix/). This would let other routes (e.g. /whatever, /this, /other, etc.) pass through to existing content, but then Gatsby should pick up at /docs. It's possible you may need to add in some Apache/Nginx routing to ensure this works and the static content is routed to appropriately.

Would that work for your use case, or are there additional considerations we should factor in?

**Comment by josekhon** [comment]
@DSchau Hi Sorry, could you clarify this. I don't have experience with Apache/Nginx routing. I built a gatsby test site which I've put into a subdirectory of the larger client repo which is also using react and webpack. My subdirectory opens up on its own port. But I'd like to integrate it into the site so that yes the gatsby site runs at like you said something like 127.0.0.1/docs of the site and not localhost/8000.  But I'm not sure how to go about this.

**Comment by josekhon** [comment]
> @josekhon it depends, and there's a few considerations here.
> 
> Probably the easiest would be to deploy your documentation site at a route (e.g. /docs), which you can do [super easily with `pathPrefix`](https://www.gatsbyjs.org/docs/path-prefix/). This would let other routes (e.g. /whatever, /this, /other, etc.) pass through to existing content, but then Gatsby should pick up at /docs. It's possible you may need to add in some Apache/Nginx routing to ensure this works and the static content is routed to appropriately.
> 
> Would that work for your use case, or are there additional considerations we should factor in?

@DSchau Hi Sorry, could you clarify this. I don't have experience with Apache/Nginx routing. I built a gatsby test site which I've put into a subdirectory of the larger client repo which is also using react and webpack. My subdirectory opens up on its own port. But I'd like to integrate it into the site so that yes the gatsby site runs at like you said something like 127.0.0.1/docs of the site and not localhost/8000. But I'm not sure how to go about this.

**Comment by DSchau** [comment]
@josekhon are you referring to the hosted site, or running locally?

**Comment by josekhon** [comment]
@DSchau running locally on my machine. I'd like to integrate the gatsby project into one part of the larger site. But I'm not exactly sure where to start or how to think in terms of integration. I have experience just building sites from scratch using one framework, and now I need to look into integrating the project(using gatsby in this case) into a larger site.

**Comment by josekhon** [comment]
@DSchau Never mind, I kind of understand what I need to do now. Thank you!

**Comment by DSchau** [comment]
@josekhon OK! Let us know if you have any other questions, and we'll be happy to help!

**Comment by thomasnordlund** [comment]
Following up on a similar question. Would it be possible to use Gatsby to generate bundle files (js, css, etc) that could then be loaded on a page that's part of a larger site and have the js app bootstrap itself?

**Comment by FabriceReynolds** [comment]
I have a slightly different issue. I would like to integrate a static blog within a larger site structure  by injecting it into a container.  I have tried reading the static index.html file and inserting it into a container and that mostly works however I then have two sets of html and body tags and the react-helmet plugin doesn't work. 

I can edit the html.js file and remove the html and body tags but as the docs specify, they are required. 

Is there any way around this or another approach to integrating Gatsby into a container?

**Comment by santoshgistto** [comment]
@FabriceReynolds  found any solution . ?
