### ISSUE TITLE
CSS Delay

### ISSUE THREAD

**Issue by RobinHerzog** [gatsbyjs/gatsby#9212]
## Description

I just migrated to gatsby 2.

I use Prismic, Styled Components, last version of everything.

On gatsby serve, when I first load my webpage, the css is not loaded. After 2sec, the website looks fine.

### Steps to reproduce

Go here : http://swapcard.com/

### Expected result

A clean website on first load

### Actual result

First load of website have no css

### Environment

Build

**Comment by shansmith01** [comment]
You may want to share your repository to help diagnose but the first thing which stands out is rather than loading your fonts via google you can host them yourself. See this library https://github.com/KyleAMathews/typefaces. This will stop your font load flicker and speed up the site
