### ISSUE TITLE
[gatsby-transformer-json] - Can we have multiple type names?

### ISSUE THREAD

**Issue by smakosh** [gatsbyjs/gatsby#9213]
I'm struggling to provide a secondary type name to the options object to the `gatsby-transformer-json` and I couldn't find anything that answers my question on the docs, so is it actually possible to do something like this:

```
{
    resolve: 'gatsby-transformer-json',
        options: {
            typeName: [ 'People', 'Animals' ]
        }
}
```

**Comment by kakadiadarpan** [comment]
@smakosh As per the documentation `typeName` can either be a `string` or a `function`.

Please refer the [documentation](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-json#configuration-options) for more details on configuration options for `gatsby-transformer-json`.
