### ISSUE TITLE
[1.0] Warn for invalid `pageQuery` export

### ISSUE THREAD

**Issue by 0x80** [gatsbyjs/gatsby#922]
I was having a bit of a struggle trying to get the new graphql queries to work. Partially because I overlooked the fact that `pageQuery` should now be the result of a `graphql` call. 

If you do not wrap the query in a function call, like before, there is no error but `props.data` is just missing. It took me a while to figure out what was going on because I was sure the data was there and the query was correct in terms of format. 

I think it'd be useful if there is some sort of warning to catch stupid mistakes like this.

**Comment by jquense** [comment]
There isn't honestly a good way of catching or determining such an error without actually trying to parse all exported strings as queries, even still you miss some. I also was making this silly mistake but I think it's probably a thing specific to the few of us who used the plain string approach, presumably folks jumping into v1 right now probably won't make that mistake having no habit of writing them like that

**Comment by KyleAMathews** [comment]
I think some sort of linting approach would be helpful. I remember when I first started with GraphQL & Relay I'd have trouble remember stuff like this too. This GraphQL piece is both super critical to using Gatsby successfully and what will be the newest tech for most people adopting it so investing in making the UX really smooth is important.

**Comment by jquense** [comment]
definatelly 👍  i am just not sure _how_ to do it in this case :/

**Comment by KyleAMathews** [comment]
Perhaps just some custom babylon script which runs when we do the query parsing?

**Comment by jquense** [comment]
you could, tho the tradeoff is you'd have parse and traverse every file twice (webpack and here) as it is the file-parser does a cheap regex check for `graphql` on files before parsing them. Even then tho you'd have to visit strings, and try and parse them as graphql to see if they are, you'd still miss invalid queries tho. I dunno. i may just be thinking about it wrong

**Comment by KyleAMathews** [comment]
The cost doesn't seem that high, maybe. The previous graphql parser I wrote just parsed component files every time so we could do something similar. This could be an eslint plugin as well. I want to copy create-react-app and have our own errors-focused eslint configuration.

On invalid queries, the Relay Compiler would handle that correct? Though it'd be cool to have IDE integration as well that'd validate queries. There's also https://github.com/apollographql/eslint-plugin-graphql

**Comment by KyleAMathews** [comment]
Relay Modern solves a lot of these problems 👌
