### ISSUE TITLE
Change language of graphql output

### ISSUE THREAD

**Issue by omattman** [gatsbyjs/gatsby#9223]
I'm currently developing a site and I wish to change the language of the data output to my locale language. Currently my days are displayed as:

```
Sunday Monday ... Friday Saturday
```

And my graphql is:

```graphql
allposts: allWordpressPost {
  edges {
    node {
      title
      featured_media {
      source_url
      alt_text
        localFile {
          childImageSharp {
            resolutions(width: 370, height: 400, cropFocus: CENTER, quality: 100) {
              src
              width
              height
            }
          }
        }
      }
      path
      date(formatString: "dddd")
      categories {
        name
      }
      excerpt
    }
  }
}
```

How do I change this to my locale language?

Using Wordpress as a backend and set everything to locale language and timezone.

I am also aware of moment.js playing a role, but I am unware of how I approach this.

**Comment by stefanprobst** [comment]
Date fields take a `locale` argument, e.g.
```graphql
{
  allWordpressPost {
    edges {
      node {
        date(formatString: "dddd, DD MM YYYY", locale: "de")
      }
    }
  }
}
```
Tip: You can explore the GraphQL schema in the GraphiQL console at http://localhost:8000/___graphql (The Docs button on the right), which will list all Fields and Types.

**Comment by omattman** [comment]
@stefanprobst Thanks, it works like a charm!

Closing this for now.
