### ISSUE TITLE
[CI]: e2e path prefix test seems to intermittently fail

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#9233]
## Description

In CircleCI, the e2e path prefix test seems to fail intermittently. Let's fix it!

### Steps to reproduce

Check out a PR, e.g. https://github.com/gatsbyjs/gatsby/pull/9227

### Expected result

The e2e tests should _all_ pass unless actual regression was introduced in current PR

### Actual result

```
CypressError: Timed out retrying: expected 'blank' to equal '/blog/'
```

**Comment by m-allanson** [comment]
Not stale gatsbot, not stale.
