### ISSUE TITLE
Question, where do I have to load a theme for Office UI Fabric in Gatsby V2?

### ISSUE THREAD

**Issue by magdielikari** [gatsbyjs/gatsby#9236]
Hi,
I try to use a theme for Office UI Fabric but I can't. The documentation oficial say: 
"an application must call loadTheme() immediately at app startup before any app code executes."

But, I don't know where I have to load the theme. I try to call the function in several parts (the components, the pages, gatsby-node) of the app but it don't work. I use gatsby version 2

Thanks...

**Comment by pieh** [comment]
Did you check https://www.gatsbyjs.org/docs/creating-global-styles/#how-to-add-global-styles-in-gatsby-using-css-in-js - it should cover this in css-in-jss section

**Comment by LekoArts** [comment]
Closing this issue as answered. If you need more help, please reach out to us!
