### ISSUE TITLE
Query regarding gatsbygram graphql integration

### ISSUE THREAD

**Issue by aje4u2i** [gatsbyjs/gatsby#924]
Could you please explain the use of the 'posts.json' and 'image' folder inside 'gatsby-1.0/gatsby-1.0/examples/gatsbygram/data' and how this is inetgrated with graphql.

**Comment by 0x80** [comment]
@aje4u2i For the 1.0 release there is a lot of documentation that has to be written still. Maybe this helps https://www.gatsbyjs.org/blog/gatsbygram-case-study/

These are the unfinished docs for 1.0 https://www.gatsbyjs.org/docs/

**Comment by jbolda** [comment]
I'm going to go ahead and close this. Feel free to ask if you have any other questions that went answered above.
