### ISSUE TITLE
[starter-library] Starter slugs are not unique

### ISSUE THREAD

**Issue by chmac** [gatsbyjs/gatsby#9249]
## Description

The slug for each starter is the GitHub repo stub (the part after the username). There are currently 2 starters in the list called `gatsby-starter`. Those two starters have the same URL on the starter showcase.

### Steps to reproduce

* Filter starters by "Cosmic JS" https://www.gatsbyjs.org/starters/?c=Cosmic%20JS
* Click on the `cosmicjs/gatsby-starter` starter (the first in the list)

### Expected result

You should now see the cosmicjs starter.

### Actual result

You're looking at the  fabien0102 starter instead.

The problem lies here:

https://github.com/gatsbyjs/gatsby/blob/b5cb862f686dca3cf261ce72ede453ae800efc5c/www/gatsby-node.js#L447-L453

Using `repoStub` as the slug is not unique.

**Comment by pieh** [comment]
Seems like adding `owner` to `slug` does make sense - but it will mess existing links - so we would need to create redirects as well

@amberleyromo do you have other ideas that we could use (busy day today for starter showcase :) )

**Comment by jbranchaud** [comment]
I'd be happy to work on this.

My first thought would be to include the `owner` as part of the slug (as @pieh suggested). If, for any reason, you didn't want to have the `owner` name in the URL, another possibility is to use an md5 hash of the `owner` and `repoStub`.

**Comment by amberleyromo** [comment]
@pieh @jbranchaud I agree that the most straightforward way would be to add owner to slug.

@jbranchaud thanks for offering to take this up!

**Comment by jbranchaud** [comment]
I've submitted a PR to add `owner` to the slug. Does something also need to be done about redirecting what will now be broken URLs?

**Comment by amberleyromo** [comment]
Closed in #9304 (+ subsequent fix  #10539)
