### ISSUE TITLE
TypeError when submitting feedback on remote plugin.

### ISSUE THREAD

**Issue by sbardian** [gatsbyjs/gatsby#9258]
## Description
Getting `TypeError: t.props.page is null` when attempting to thumbs up or down a remote plugin.

### Steps to reproduce
Open plugins page and thumbs up or down at the bottom of a remote plugin page readme.
(example: https://www.gatsbyjs.org/packages/@sbardian/gatsby-source-amazon-wishlist/)

### Expected result
Expected result is `Thank you` like sending feedback for a local plugin.

### Actual result
`TypeError: t.props.page is null`

The 'page' property being sent to MarkdownPageFooter component is null, and it is unable to get parent.relativePath because the remote plugin does not have a readme file within the gatsby project?

It appears to be null because of the query in DocsRemotePackagesTemplate passing markdownRemark (null) to PackageReadme. 

Might be able to send the npm package URL using the npmPackage instead of markdownRemark here, but I'm not sure what the mutation in the sendReview function of MarkdownPageFooter is doing/expecting? Maybe thumbs up/down should be hidden when `page` is null?
 
### Environment
N/A

**Comment by kakadiadarpan** [comment]
I'm able to reproduce this error when clikcing on thumbs up or down:

<img width="585" alt="screenshot 2018-10-23 at 10 11 20 am" src="https://user-images.githubusercontent.com/10805593/47336118-0a47d980-d6ac-11e8-8702-69c8049a3d4d.png">

**Comment by LekoArts** [comment]
The Thumbs up/Thumbs down feature has been replaced for some time now with a feedback widget hence this issue can be closed. (The feedback widget isn't activated on plugins pages)
