### ISSUE TITLE
Combine two docs into one and add redirects

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#9259]
There are two docs that basically cover the same topic.

The goal here is to combine these two docs into one titled: “Add offline support with a Service Worker”
1. https://www.gatsbyjs.org/docs/add-offline-support/
2. https://www.gatsbyjs.org/docs/add-a-service-worker/

Process:
Read both docs thoroughly and make sure the final doc covers all the necessary information to help someone "add offline support with a service worker."

## Motivation

We want to reduce redundancy in the docs, which improves clarity.

**Comment by rfbotto** [comment]
I will gladly take this one @shannonbux :)

**Comment by siddhant1** [comment]
Adding claimed
