### ISSUE TITLE
WebpackError: TypeError: Cannot read property 'frontmatter' of null

### ISSUE THREAD

**Issue by jpomykala** [gatsbyjs/gatsby#9267]
## Description

Cannot build a working webpage using markdown. With ``npm develop`` is ok

### Steps to reproduce

Create gatsby page with ``gatsby new my-page https://github.com/gatsbyjs/gatsby-starter-default``

and follow the tutorial: https://www.gatsbyjs.org/docs/adding-markdown-pages/

``npm run build``

### Expected result

Build successfully

### Actual result
```
success Building production JavaScript and CSS bundles — 3.348 s
{ allMarkdownRemark: { edges: [ [Object], [Object], [Object] ] } }

error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  18 |   return (
  19 |     <Layout>
> 20 |       <Helmet title={`${post.frontmatter.title}`}/>
     |                                             ^
  21 |       <div className="back-top-container sticky-top">
  22 |         <Link to={'/'}>


  WebpackError: TypeError: Cannot read property 'frontmatter' of null
```

Project: https://github.com/jpomykala/gatsby-issue 

### Environment

```
  System:
    OS: macOS 10.14
    CPU: x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.12.0 - /usr/local/opt/node@8/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 62.0.3
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.19 => 2.0.26 
    gatsby-image: ^2.0.15 => 2.0.15 
    gatsby-plugin-catch-links: ^2.0.5 => 2.0.5 
    gatsby-plugin-manifest: ^2.0.5 => 2.0.5 
    gatsby-plugin-offline: ^2.0.5 => 2.0.7 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-sass: ^2.0.1 => 2.0.1 
    gatsby-plugin-sharp: ^2.0.7 => 2.0.7 
    gatsby-remark-copy-images: ^0.2.1 => 0.2.1 
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.0.5 
    gatsby-remark-images: ^2.0.4 => 2.0.4 
    gatsby-remark-prismjs: ^3.0.2 => 3.0.2 
    gatsby-source-filesystem: ^2.0.5 => 2.0.5 
    gatsby-transformer-remark: ^2.1.8 => 2.1.8 
    gatsby-transformer-sharp: ^2.1.4 => 2.1.4 
  npmGlobalPackages:
    gatsby-cli: 2.4.3

```

**Comment by LekoArts** [comment]
You need to put the post-page.js file into the folder „templates“ - the tutorial mentions that. The reason behind that is that every js file in the pages folder gets processed to a page and it won’t have access to this query

**Comment by jpomykala** [comment]
Weird, I was thinking that if I set my own path to template it will still work. I think it's worth mention that in tutorial.

**Comment by ainneo** [comment]
Thanks for this - this was my issue! I thought I could create my own folders but I guess you have to keep things separate!

**Comment by Behinder** [comment]
> You need to put the post-page.js file into the folder „templates“ - the tutorial mentions that. The reason behind that is that every js file in the pages folder gets processed to a page and it won’t have access to the context

This is not the solution. I have template in folder "templates" and frontmatter is still not detected. Rebuilt site twice and no effect.

**Comment by jonniebigodes** [comment]
@Behinder could you make a reproduction with your code and packages you're using, following [these steps](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) so that it can be better looked at? I'm more than happy to take a look at it.

**Comment by Behinder** [comment]
Nah, it's too much effort. I'll stop the project and wait if bug goes away
in 2.1
