### ISSUE TITLE
[www] Graphviz elements not responsive

### ISSUE THREAD

**Issue by c0b41** [gatsbyjs/gatsby#9271]
example docs url: https://www.gatsbyjs.org/docs/schema-generation/ 

![www gatsbyjs org_docs_schema-generation_](https://user-images.githubusercontent.com/2834954/47257518-9503bb00-d497-11e8-964a-58b2ca684719.png)

**Comment by hasparus** [comment]
I think that `width` and `height` attributes being set are the problem, so I'd like to propose what I believe is a simpler solution than #9480. Instead of overriding these sizes, we can just remove them.

video: https://vimeo.com/298156594
jsfiddle with the concept: https://jsfiddle.net/u7wv9tkq/1/
