### ISSUE TITLE
[gatsby-plugin-react-helmet]: <title> isn't rendered server-side

### ISSUE THREAD

**Issue by niklasravnsborg** [gatsbyjs/gatsby#9272]
## Description

gatsby-plugin-react-helmet doesn't prerender the title tag as expected for pages other than /. Example on view-source:https://www.gatsbyjs.org/features/. Title should be `Features | GatsbyJS` but it is just an empty tag:

<img width="637" alt="screenshot 2018-10-20 at 18 13 03" src="https://user-images.githubusercontent.com/6717303/47257870-d2fee000-d493-11e8-85d4-039af908efcf.png">

This problem affects several of my sites also and could be pretty suboptimal for SEO. Here is how to repro:

### Steps to reproduce

Using Gatsby 2:

- `gatsby new test`
- `cd test`
- `npm i gatsby-plugin-react-helmet react-helmet`
- Add `plugins: ['gatsby-plugin-react-helmet']` to `gatsby-config.js`
- Replace page-2.js with the following:

```jsx
import React from 'react'
import Helmet from 'react-helmet'

export default () => (
  <>
    <Helmet title="This title should be rendered with gatsby-plugin-react-helmet."/>
    <h1>Page 2!</h1>
  </>
)
```

Run `gatsby build && gatsby serve`

Navigate to `http://localhost:9000/page-2`

### Expected result

The <title> tag should be rendered with `This title should be rendered with gatsby-plugin-react-helmet.`

### Actual result

View the page source. When searching for the title tag you will find: `<title data-react-helmet="true"></title>`

### Environment

```
  System:
    OS: macOS 10.14
    CPU: x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.1 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.67
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.19 => 2.0.19 
    gatsby-plugin-manifest: ^2.0.5 => 2.0.5 
    gatsby-plugin-offline: ^2.0.5 => 2.0.5 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
  npmGlobalPackages:
    gatsby-cli: 2.4.2
```

**Comment by Seldszar** [comment]
After some investigation, it seems a service worker (provided by `gatsby-plugin-offline`) is still registered, serving the wrong assets.
Unregister the said service worker and the page should be back to normal.

**Comment by KyleAMathews** [comment]
When you view source with a sw you're I'm guessing serving the source for the empty app shell page the SW serves. This loads the js for the page and then renders it. Is the title being set in the browser? Also for seo, it's what's in the html that matters.

**Comment by niklasravnsborg** [comment]
@Seldszar @KyleAMathews Thanks ☺️. Didn't figure out it could be the service worker. Thought I'm viewing the html in fact. So SEO is fine! 

Anyway, is this the expected behavior or can I close this issue?
