### ISSUE TITLE
Remark Bulleted List Output In Single `p` Tag

### ISSUE THREAD

**Issue by rjhilgefort** [gatsbyjs/gatsby#9280]
## Summary

My markdown is being rendered in HTML, but my unordered lists are presenting all in one line in a single `p` tag. I was expecting them to present on separate lines. How can I adjust/fix this?

I'm expecting something like

- one
- two
- three

But I'm seeing something more like

```md
- one - two - three
```

**Comment by KyleAMathews** [comment]
Can you create and share a site which reproduces this?

**Comment by rjhilgefort** [comment]
I'm sorry, it looks like it was my fault, I was using a list I copy and pasted out of another page and it was using `• ` instead of `-`.
