### ISSUE TITLE
Incorrect picture when sharing Gatsby's site

### ISSUE THREAD

**Issue by yeskunall** [gatsbyjs/gatsby#9288]
## Description

This issue might be specific to Facebook Messenger, but might be a larger issues: if you share [Gatsby's website](https://gatsbyjs.org) in Facebook Messenger, you see what I believe is @calcsam's face! 😆

### Steps to reproduce

Just share [this](https://gatsbyjs.org) link in Facebook Messenger.

### Expected result

What should happen?

Should have seen Gatsby's logo, or something other than @calcsam (no offence, Sam! 😅)

### Actual result

![image](https://user-images.githubusercontent.com/14703164/47279486-61ac5380-d59f-11e8-9f91-7074c43eefd5.png)

### Environment

I'm running Chrome 69.0.3497.100, if that helps!

**Comment by Seldszar** [comment]
The `og:image` metadata seems to be missing in the HTML for some reason. My guess is to add it and the image should be fixed.

**Comment by mikelax** [comment]
nice @Seldszar . for completeness you may want to add a few additional meta tags to get better sharing support on other sites. 
I made a similar PR in the gatsby store repo a little while ago. 

gatsbyjs/store.gatsbyjs.org#142

**Comment by Seldszar** [comment]
Will do! :)

**Comment by oorestisime** [comment]
closing this as PR was merged and problem seems fixed
