### ISSUE TITLE
gatsby-transformer-remark: information is not a function

### ISSUE THREAD

**Issue by zslabs** [gatsbyjs/gatsby#9293]
## Description

I think [this PR](https://github.com/gatsbyjs/gatsby/pull/9219) may be causing some issues on `gatsby build` for me:

```
106 | /* Stringify one attribute. */
107 | function attribute(ctx, key, value) {
> 108 |   var info = information(key) || {};
    | ^
109 |   var name;
110 |
111 |   if (


WebpackError: TypeError: information is not a function
```

As soon as I upgrade to `2.1.8` it's throwing this error.

### Steps to reproduce

1. Upgrade `gatsby-transformer-remark` to `2.1.8` (I was on `2.1.7`)

### Expected result

Successful build.

### Actual result

🚫 

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here. Not working? You may need to update your global gatsby-cli - `npm install -g gatsby-cli`

```
 System:
    OS: macOS 10.14
    CPU: x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 2.7.1 - /usr/local/bin/fish
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    Yarn: 1.10.1 - ~/.yarn/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.67
    Firefox: 62.0.3
    Safari: 12.0
  npmPackages:
    gatsby: 2.0.28 => 2.0.28
    gatsby-image: 2.0.15 => 2.0.15
    gatsby-plugin-canonical-urls: 2.0.6 => 2.0.6
    gatsby-plugin-catch-links: 2.0.5 => 2.0.5
    gatsby-plugin-feed: 2.0.8 => 2.0.8
    gatsby-plugin-google-tagmanager: 2.0.5 => 2.0.5
    gatsby-plugin-manifest: 2.0.5 => 2.0.5
    gatsby-plugin-netlify: 2.0.1 => 2.0.1
    gatsby-plugin-netlify-cms: 3.0.4 => 3.0.4
    gatsby-plugin-node-fields: 1.0.0 => 1.0.0
    gatsby-plugin-react-helmet: 3.0.0 => 3.0.0
    gatsby-plugin-sass: 2.0.1 => 2.0.1
    gatsby-plugin-sharp: 2.0.7 => 2.0.7
    gatsby-plugin-sitemap: 2.0.1 => 2.0.1
    gatsby-plugin-twitter: 2.0.6 => 2.0.6
    gatsby-remark-autolink-headers: 2.0.7 => 2.0.7
    gatsby-remark-copy-linked-files: 2.0.5 => 2.0.5
    gatsby-remark-custom-blocks: 2.0.0 => 2.0.0
    gatsby-remark-embed-video: 1.4.0 => 1.4.0
    gatsby-remark-images: 2.0.4 => 2.0.4
    gatsby-remark-prismjs: 3.0.2 => 3.0.2
    gatsby-remark-relative-images-v2: 0.1.5 => 0.1.5
    gatsby-remark-responsive-iframe: 2.0.5 => 2.0.5
    gatsby-source-filesystem: 2.0.5 => 2.0.5
    gatsby-transformer-remark: 2.1.8 => 2.1.8
    gatsby-transformer-sharp: 2.1.4 => 2.1.4
    gatsby-transformer-yaml: 2.1.3 => 2.1.3
  npmGlobalPackages:
    gatsby-cli: 2.4.3
```

**Comment by stefanprobst** [comment]
> I think [this PR](https://github.com/gatsbyjs/gatsby/pull/9219) may be causing some issues

Probably because of an [outdated `property-information`](https://github.com/gatsbyjs/gatsby/blob/69fd92b85c3b212f81bbe2f5b36ab933ba729c3c/yarn.lock#L15040) package.

**Comment by pieh** [comment]
@zslabs Can you share repo so I can check if fix from @stefanprobst will work or we need to dig deeper

**Comment by zslabs** [comment]
Unfortunately I won't be able to; internal website.

**Comment by pieh** [comment]
Let's try other way around then.
If you use `yarn` you can try adding to package.json [`resolutions`](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) entry:
```
{
  "resolutions": {
    "hast-util-to-html": "4.0.1"
  }
}
```
and run `yarn` to install deps (that will force to use newer version of package) - so it will do same thing that mentioned PR is doing.

If you could try and let us know if it fixes the problem (with `gatsby-transformer-remark@2.1.8`) it would be great.

**Comment by oskareke** [comment]
@pieh What would be the equivalent of the resolutions fix for npm users?

**Comment by pieh** [comment]
@oskareke I'm not aware of `npm` equiavalent. The `resolutions` suggestions is just to try locally if upgrading that package is fixing the issue - if it does we will merge PR from @stefanprobst so this isn't needed to do in your code, but currently I don't have way to reproduce this problem

**Comment by pieh** [comment]
If you are hitting same problem and can share your repository (or create minimal reproduction repository) then I could test it locally without asking You to test that change

**Comment by zslabs** [comment]
@pieh Yessir, adding that `resolutions` entry in along with the remark upgrade did fix the issue for me.
