### ISSUE TITLE
Static query and Gatsby Lunr Autocomplete Search

### ISSUE THREAD

**Issue by jodays** [gatsbyjs/gatsby#9299]
I have a stateful component in which I want to do a static query for all the titles of my markdown. Store them in an array to use for an autocomplete search. I'm not sure I understand the syntax for a static query in a react component like this for example. I'd appreciate any direction. I'm trying to use the react autosuggest library, for that I need to store an array of options. 

```
class Search extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      query: '',
      results: [],
    }
render() {

    const { classes } = this.props;
    return (
  }
    )
  }
}
```

**Comment by kakadiadarpan** [comment]
@jodays Please refer this [documentation](https://www.gatsbyjs.org/docs/static-query/) for `StaticQuery`. Please go through `How to use StaticQuery in components` and `Basic example`.
