### ISSUE TITLE
Intercept clicks @ top level so markdown links and other links not using React Router don't force reload

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#93]
This module would make this a very easy PR https://github.com/substack/catch-links

**Comment by thangngoc89** [comment]
Wow. Never heard of this. Statinamic has this issue too https://github.com/MoOx/statinamic/issues/67

**Comment by fson** [comment]
If implemented, maybe this should be configurable? I'm currently (ab)using this to force a page reload for some pages by using `<a>` instead of `<Link>`.

[![](https://imgs.xkcd.com/comics/workflow.png)](https://xkcd.com/1172/)

**Comment by KyleAMathews** [comment]
@fson noted :D that's a pretty valid reason.

So a thought. With #100, reloading a Gatsby site should be near instantaneous making page reloads this link catcher is intended to catch matter a lot less. I vote we wait and see how Service Workers change the experience.

Thoughts?

**Comment by KyleAMathews** [comment]
Gonna close this because there's valid reasons for not intercepting clicks, service workers will solve reload latency problem, and it's easy enough to add this to individual site projects if someone wants it (and could be abstracted into an NPM module too which would be cool).
