### ISSUE TITLE
build silently failed when prefix-links is enabled

### ISSUE THREAD

**Issue by breeswish** [gatsbyjs/gatsby#930]
Any ideas?

```bash
$ gatsby build --prefix-links

Generating CSS
Generating Static HTML
```

You could review at our source code as well: https://github.com/vijos/about-vijos

Update: We added some [workarounds](https://github.com/vijos/about-vijos/commit/4c2bddf99b0f7d4d6106c310cb381e3c011f82f0) so you may need to view [this commit](https://github.com/vijos/about-vijos/tree/5240ad469e8a9a97d33d1f003498c2939b7aa3cb) instead.

**Comment by KyleAMathews** [comment]
Hmmm silent build errors are bad...

Have you seen https://github.com/gatsbyjs/gatsby#deploying-to-github-pages-and-other-hosts-where-your-sites-links-need-prefixes?

Your config.toml entry should just look like `linkPrefix = "/about-vijos"`

**Comment by breeswish** [comment]
Oh great! Thanks for your help. Leaving this issue open to keep track on fixing the silent failure :P

**Comment by jbolda** [comment]
@KyleAMathews I presume this will be superceded by v1?

**Comment by KyleAMathews** [comment]
I'm not going to be putting much time into fixing v0 bugs. But it shouldn't be a problem in v1 as I've spent a bunch of time on making sure Gatsby builds fail properly there.

**Comment by KyleAMathews** [comment]
Not supporting v0 anymore
