### ISSUE TITLE
Multiple installations of Google Tag Manager detected

### ISSUE THREAD

**Issue by jeremylynch** [gatsbyjs/gatsby#9310]
When using [Gatsby-plugin-google-tagmanager](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-google-tagmanager), I am getting the following error only after I navigate to the 2nd page: 
```
Multiple installations of Google Tag Manager detected
```
Is this expected?

**Comment by kakadiadarpan** [comment]
@jeremylynch I've found Google Tag Assistant to be a little buggy. To confirm it is being installed multiple times, can you copy the GA ID, view the page source, and search, (cmd+F) for the ID in the code. If you find it's occurance more than once, that would mean that there is an issue. If your website is live somewhere, I can take a look at this an verify.

Can you also provide relevant environment information by running `gatsby info --clipboard`?

**Comment by jeremylynch** [comment]
Thanks so much @kakadiadarpan 
Is there any chance you could take a look at [this site](https://www.orangemotorgroup.com.au/ )?

**Comment by DustinChecketts** [comment]
I'm currently troubleshooting this exact issue on https://mousedining.com. I get a single instance and everything looks good, then I browse the main nav and blog and it starts telling me there are multiple instances of GTM installed, and tags within GTM are firing multiple times (Google Publisher Tag, Google Analytics, etc.)

Mind having a look at https://mousedining.com?

**Comment by aamorozov** [comment]
It is an existing issue 
```
System:
    OS: macOS 10.14
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.9.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 72.0.3626.109
    Firefox: 65.0
    Safari: 12.0
  npmPackages:
    gatsby: 2.1.2 => 2.0.98
    gatsby-image: 2.0.29 => 2.0.28
    gatsby-plugin-favicon: 3.1.5 => 3.1.5
    gatsby-plugin-flow: 1.0.2 => 1.0.2
    gatsby-plugin-force-trailing-slashes: 1.0.4 => 1.0.4
    gatsby-plugin-google-analytics: 2.0.13 => 2.0.10
    gatsby-plugin-google-tagmanager: 2.0.9 => 2.0.8
    gatsby-plugin-jsxstyle: 0.0.5 => 0.0.4
    gatsby-plugin-manifest: 2.0.17 => 2.0.13
    gatsby-plugin-offline: 2.0.23 => 2.0.21
    gatsby-plugin-react-helmet: 3.0.6 => 3.0.5
    gatsby-plugin-sharp: 2.0.20 => 2.0.18
    gatsby-plugin-sitemap: 2.0.5 => 2.0.4
    gatsby-plugin-transition-link: 1.4.7 => 1.4.7
    gatsby-source-filesystem: 2.0.20 => 2.0.17
    gatsby-source-graphql: 2.0.10 => 2.0.8
    gatsby-transformer-json: 2.1.8 => 2.1.7
    gatsby-transformer-sharp: 2.1.13 => 2.1.12
  npmGlobalPackages:
    gatsby-cli: 2.4.6
    gatsby: 2.0.67
```

**Comment by zslabs** [comment]
I'm also seeing the same error as noted above using the Google Tag Assistant, but I'm wondering if the extension may be getting tripped up with the site using pushState? Because while I am seeing two inclusions:

```

<script>(function(w,d,s,l,i){w[l]=w[l]\|\|[];w[l].push({'gtm.start':
--
  | new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  | j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  | 'https://www.googletagmanager.com/gtm.js?id='+i+dl+'';f.parentNode.insertBefore(j,f);
  | })(window,document,'script','dataLayer', 'GTM-123');</script>
```

```
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-123" height="0" width="0" style="display: none; visibility: hidden"></iframe></noscript>
```

They look like distinctive calls and have only one inclusion of each snippet.

**Comment by jonathancary** [comment]
Did anyone ever find a solution to this or was able to confirm it was just a bug with the chrome extension? Having the same issue where on the initial page load it only show one, but when you navigate to another page it shows the duplicate. Using it on this website for reference: https://www.mohragency.com/.

**Comment by firewaller** [comment]
+1 FYI I get the same issue without gatsby, so it seems to be a react issue

**Comment by jimmed** [comment]
+1 to this issue. So far as I can see:

 - The GTM script is included exactly once.
 - The GTM tags are loaded exactly once.
 - The Google Tag Assistant extension detects the *same* GTM installation on each page navigation, but erroneously detects these as separate installations.

**Comment by tejovanthWork** [comment]
Hey, I have the same issue, with navigation with React Router. Was there any resolution for this?

**Comment by jimmed** [comment]
@tejovanthWork As far as I can tell, it's a bug in Google Tag Assistant. Of all of the above reports, every single site is including GTM's tracking code **once only**.

**Comment by pjg** [comment]
On my end, I'm getting this error when GA (UA) is being included on subsequent navigation events via GTM pageview trigger. You can verify yourself how many GTM instances are being created by executing: `ga.getAll()`. It should return only one.

**Comment by krzysiekhum** [comment]
We have the same issue. Two instances :( 
![image](https://user-images.githubusercontent.com/13885484/69537806-2c7feb00-0f81-11ea-821f-022c49e7fcfe.png)

**Comment by Deykun** [comment]
Google Tag Manager is trigger multiple times because it is added to the page static template with param:
```
gtag('config', 'ID', {"send_page_view":false});
```
Page view action is incited by the plug-in later, so in theory is should work fine.
