### ISSUE TITLE
Add https://www.landr.com/ to the site showcase

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#9315]
landr.com just relaunched on Gatsby and it's a beautiful site that should be added to site showcase!

**Comment by StuffBySpencer** [comment]
I'll do this for ya :)

**Comment by KyleAMathews** [comment]
@StuffBySpencer thanks! Looking forward to your PR!

**Comment by KyleAMathews** [comment]
Fixed
