### ISSUE TITLE
Followed the v2 upgrade guide. Site builds, but is just blank (with no errors?)

### ISSUE THREAD

**Issue by WebD00D** [gatsbyjs/gatsby#9324]
## Summary

Upgraded to Gatsby v2. After following the guide I'm stuck with a blank screen, with no console / terminal errors to point me in even the slightest direction. I wish I had more to go off, but posting here incase maybe someone has already dealt with this before. Am I missing something obvious?

### Environment (if relevant)

System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.12.0 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.67
    Firefox: 62.0.2
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.0.29 => 2.0.29
    gatsby-link: next => 2.0.0-rc.4
    gatsby-plugin-layout: ^1.0.4 => 1.0.4
    gatsby-plugin-react-helmet: ^1.0.5 => 1.0.8
  npmGlobalPackages:
    gatsby-cli: 1.1.58

### File contents (if changed)

`gatsby-config.js`: 

``` module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`
  },
  plugins: [`gatsby-plugin-react-helmet`, `gatsby-plugin-layout` ]
};
 ```
`package.json`: 

```
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "antd": "^3.7.0",
    "dotenv": "^4.0.0",
    "firebase": "^4.3.1",
    "gatsby": "^2.0.29",
    "gatsby-link": "next",
    "gatsby-plugin-layout": "^1.0.4",
    "gatsby-plugin-react-helmet": "^1.0.5",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "moment-timezone": "^0.5.13",
    "pluralize": "^7.0.0",
    "react": "^16.5.2",
    "react-big-calendar": "^0.17.0",
    "react-color": "^2.14.1",
    "react-disqus-comments": "^1.1.1",
    "react-dom": "^16.5.2",
    "react-firebase": "^2.2.7-4",
    "react-firebase-file-uploader": "^2.4.1",
    "react-google-maps": "^9.4.5",
    "react-intl": "^2.4.0",
    "react-map-gl": "^3.1.1",
    "react-moment": "^0.6.5",
    "react-redux": "^5.0.6",
    "react-router-redux": "^4.0.8",
    "redux": "^3.7.2",
    "reselect": "^3.0.1",
    "styled-components": "^3.4.5",
    "whatwg-fetch": "^2.0.3"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "main": "n/a",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --trailing-comma es5 --no-semi --single-quote --write 'src/**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "@helpscout/blue": "^0.5.9",
    "classnames": "^2.2.5",
    "eslint": "^5.7.0",
    "prettier": "^1.6.1"
  }
}

```
`gatsby-node.js`: N/A 

`gatsby-browser.js`: 

```
import React from 'react'
import { Provider } from 'react-redux'

import createStore from './src/state/createStore';

export const wrapRootElement = ({ history }) => {
  const store = createStore();

  const ConnectedRootElement = ({ element }) => (
    <Provider store={store}>
      {element}
    </Provider>
  );

  return ConnectedRootElement;
};

 ```

`gatsby-ssr.js`: 

``` import React from 'react';
import { Provider } from 'react-redux';
import { renderToString } from 'react-dom/server'

import createStore from './src/state/createStore'

export const replaceRenderer = ({ bodyComponent, replaceBodyHTMLString }) => {
  const store  = createStore()
  const ConnectedBody = () => (
    <Provider store={store}>
      {bodyComponent}
    </Provider>
  )

  replaceBodyHTMLString(renderToString(<ConnectedBody />))

}

 ```

**Comment by LekoArts** [comment]
As the upgrade guide can't cover every use case it has general statements as something like:
- Upgrade your packages to v2
- Install peerDependencies or new dependencies these plugins now need

So, e.g.
- remove gatsby-link
- add `gatsby-plugin-styled-components` and add it other dependencies
- Your missing the `react-helmet` dependency as said [here](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-react-helmet#install)

So have a look at the packages

**Comment by WebD00D** [comment]
@LekoArts - Thanks for the insight. Gave those all a go, however still running into the same issue.

**Comment by WebD00D** [comment]
For the hell of it, decided to run `gatsby build` and got a little bit more of heading possibly.

` WebpackError: Invariant Violation: You should not use <Redirect> outside a <Router>`

Not much after that though, as far as where it could be coming from inside my app.

**Comment by maecapozzi** [comment]
@WebD00D, have you taken a look at #8344?

**Comment by WebD00D** [comment]
Hey @maecapozzi , I don't get any errors, just linter warnings is all. I thought the same about CommonJS / ES6, and I did have some of those, but fixed, and still the same issue.

**Comment by JoshBowdenConcepts** [comment]
I am still running into these issues and haven't seen anything actionable yet on these threads any updates here?
