### ISSUE TITLE
:target selector not re-running

### ISSUE THREAD

**Issue by jkjustjoshing** [gatsbyjs/gatsby#9325]
## Description
When linking directly to a fragment within a page, the `:target` pseudo-selector isn't getting triggered. It gets triggered on page load and on `hashchange` events, neither of which fire when you change routes using `<Link>`.

### Steps to reproduce
1. Create a page (let's say `pages/test.js` with an element `<p id="foo">The linked paragraph</p>` and CSS `#foo:target { background: yellow; }`
2. From a different page, link to this page with the hash in the URL: `<Link to="/test#foo">Test -> Foo</Link>`

When running `npm run develop` the `<p id="foo">` element does not get the `:target` styling. However, if you run `npm run build` and access the compiled output *with JavaScript disabled* (triggering default browser routing behavior), the `<p id="foo">` element *does* get the `:target` styling.

### Expected result

`:target` selector should work when using `<Link />`

### Actual result

`:target` selector does not work when using `<Link />`

### Explanation

When updating the page URL with `history.pushState()`, some of the things that usually happen on a navigation don't. One of those is scrolling to the top of the page (or an anchor/id if included). Gatsby handles this for us, and allows us to customize the behavior using `shouldUpdateScroll` in `gatsby-browser.js`. But for "default" behavior (that matches the browser), no customization is needed.

Another thing that usually happens on navigation is updating which elements get `:target` styling. This happens 1) On page load, and 2) On `hashchange`. However, [`history.pushState` does not trigger a `hashchange` event](https://bugs.webkit.org/show_bug.cgi?id=83490). Therefore, to re-enable this functionality, I've added the following to my `shouldUpdateScroll` function (in addition to copy/pasting [this code](https://github.com/gatsbyjs/gatsby/blob/2605aa0ec74a79fa56bc0eae8d101356c25c38de/packages/gatsby/cache-dir/navigation.js#L113) to keep the default Gatsby behavior):

```javascript
let hash = routerProps.location.hash
let oldHash = prevRouterProps && prevRouterProps.location && prevRouterProps.location.hash

if (hash !== oldHash) {
    // When using pushState/popState, the browser doesn't re-compute :target CSS pseudo selectors
    setTimeout(() => {
        window.location.hash = '';
        window.location.hash = routerProps.location.hash
    })
}
```
Should this be part of Gatsby's default behavior?

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.4 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.67
    Firefox: 62.0.3
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.0 => 2.0.11 
    gatsby-link: ^2.0.0 => 2.0.2 
    gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11 
    gatsby-plugin-sass: ^2.0.1 => 2.0.1 
    gatsby-source-directus: 0.0.44 => 0.0.44 
    gatsby-source-filesystem: ^2.0.2 => 2.0.2 
    gatsby-transformer-remark: ^2.1.6 => 2.1.6

**Comment by jkjustjoshing** [comment]
One thing I've discovered about my fix: it breaks the back button when hash changes occur. I believe it double-adds items to the history. So if my fix is being considered for use we'll need to make sure that issue is fixed first. If I come up with a solution I'll be sure to update this issue.

**Comment by jkjustjoshing** [comment]
I think this issue is still a good one to explore

**Comment by rootlinux2** [comment]
Hi guys, I have this Issue too
 "gatsby": "^2.24.49"
