### ISSUE TITLE
Docs: Clarify that when using `gatsby-plugin-layout` you can't refactor any components to the new `<Layout />`

### ISSUE THREAD

**Issue by maecapozzi** [gatsbyjs/gatsby#9330]
## Summary

Originally when I was upgrading to Gatsby v2, I thought I could refactor some components to use the new `<Layout />`, and use `gatsby-plugin-layout` for the others. It would've saved me a lot of time if there had been a sentence saying that it's all-or-nothing.  

I'd be happy to add this to the docs myself! I just want to get a sense of whether other people agree this would be a relevant addition. 

### Basic example

If you are using `gatsby-plugin-layout`, do not refactor any of your components to use the new `<Layout />` component provided by Gatsby v2.

### Motivation

I think this might save other developers some time.

**Comment by kakadiadarpan** [comment]
@maecapozzi As far as I know, Gatsby doesn't provide `<Layout />` component. Can you share more information on this?

**Comment by maecapozzi** [comment]
Hi @kakadiadarpan, I'll clarify! 

In Gatsby v2, the `<Layout />` component is no longer at the top level like it used to be in Gatsby v1. 

In v1, layouts looked like this: 

```js
<Root>
  <Layout>
    {/* layout is not affected when the page template changes */}
    <PageElement>{/* page content here */}</PageElement>
  </Layout>
</Root>
``` 

In v2, they look like this: 

```js
<Root>
  <PageElement>
    {/* layout will rerender each time the page template changes */}
    <Layout>{/* page content here */}</Layout>
  </PageElement>
</Root>
```

I'd like to clarify in the docs that you can't have it both ways in a project. You can either use `gatsby-plugin-layout`, and have layouts always at the top-level, or you can just use regular Gatsby v2, and <Layout /> will not be at the top-level. 

So if even one of your components needs <Layout /> to work the old way, you'll have to set up all of your components that way.

**Comment by kakadiadarpan** [comment]
@maecapozzi Thanks for the clarification. Currently in the `gatsby-plugin-layout` the only relevant information I can find about this is:
> This plugin implements those APIs for you, which reimplements the behavior of Gatsby V1.

It would be great to add your suggestions there. Would you be open to work on this and raise a PR to update the docs accordingly?

**Comment by maecapozzi** [comment]
I'd be happy to! Thanks @kakadiadarpan

**Comment by LekoArts** [comment]
Closing this issue due to https://github.com/gatsbyjs/gatsby/pull/9378
