### ISSUE TITLE
Update `gatsby-core-philosophy.md`

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#9332]
Would be nice to update gatsby-core-philosophy.md with some of these possible ideas:

https://www.gatsbyjs.org/docs/gatsby-core-philosophy/

- Core values
- OSS goals
- What do we believe is good or bad?
- What are we committed to working on? What are we not trying to do?

## Motivation
Helps us make unified decisions as an OSS community.

@jdemieville

**Comment by marcysutton** [comment]
Reopening this one as we need to write it! @KyleAMathews you mentioned this one being higher than some others on your priority list.

**Comment by marcysutton** [comment]
@rizchelwood I just noticed you had expressed interest in working on this issue, if you're still interested I know we could use help (and some internal knowledge to make sure the messaging is accurate)!

**Comment by lannonbr** [comment]
Hey @marcysutton and @shannonbux. Would you say this is resolved as @calcsam seems to have fleshed this page out back in May.

**Comment by marcysutton** [comment]
Yes, I'd say so! Thanks @lannonbr!
