### ISSUE TITLE
Documentation for adding Gatsby to an existing repo/project

### ISSUE THREAD

**Issue by ewolfe** [gatsbyjs/gatsby#9340]
## Summary

It would be nice to add documentation for adding Gatsby to an existing repo/project. Even if it means creating a new project via `gatsby new my-blazing-fast-site` and manually plucking the contents over to your existing project -- Since it would make it clear there no better alternatives (like `gatsby new .`).

### Motivation

Why are we doing this?

_To make clear the suggested process for adding Gatsby to an existing repo/project._

What use cases does it support?

_Use cases where people aren't starting from scratch._

What is the expected outcome?

_A short blurb added somewhere to the documentation._

**Comment by ewolfe** [comment]
Bump (to remove the stale label) since there are 13 👍

**Comment by reyanshmishra** [comment]
not stale

**Comment by emplums** [comment]
Would love these docs!

**Comment by lannonbr** [comment]
@gillkyle is currently working on doing this for sites built with Create-React-App here: https://github.com/gatsbyjs/gatsby/pull/14626

**Comment by gillkyle** [comment]
The PR for porting from Create React App is about ready to be merged (https://github.com/gatsbyjs/gatsby/pull/14626)

Are there particular frameworks or configurations that would be helpful to have guides written for? (@emplums, @reyanshmishra, et al.) It was mentioned in the conversation for the above-linked PR that having some stubs for additional guides would be beneficial.
