### ISSUE TITLE
Add two sites to the site showcase

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#9341]
- https://wideeye.co/
- http://guster.com/

https://www.gatsbyjs.org/docs/site-showcase-submissions/

**Comment by Dipeshwagle** [comment]
I'll work on this one :)

**Comment by KyleAMathews** [comment]
@tomanistor already jumped on it https://github.com/gatsbyjs/gatsby/pull/9343 but thanks for offering!
