### ISSUE TITLE
White page on some devices randomly

### ISSUE THREAD

**Issue by hackhat** [gatsbyjs/gatsby#9346]
Hi!

I recently deployed a gatsby website and I get reports of users seeing white screen. I see it myself on my device and I don't know why?

I have it on my android/chrome and a user from safari on mobile. I think has to do with service workers being messed up, but not sure how it can happen and how to fix it now for all users?

I managed to clear my android/chrome, there was 252MB of data... not sure why so much as this is just a basic app. Does it keep all previous versions?

Thank you

## Description

I recently deployed a gatsby website and I get reports of users seeing white screen. I see it myself on my device and I don't know why?

### Steps to reproduce

-

### Expected result

-

### Actual result

-

### Environment
  System:
        OS: Windows 10
        CPU: x64 Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
      Binaries:
        Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
        npm: 5.5.1 - C:\Program Files\nodejs\npm.CMD
      Browsers:
        Edge: 42.17134.1.0
      npmPackages:
        gatsby: ^2.0.19 => 2.0.21
        gatsby-plugin-catch-links: ^2.0.4 => 2.0.4
        gatsby-plugin-emotion: ^2.0.5 => 2.0.5
        gatsby-plugin-google-analytics: ^2.0.6 => 2.0.6
        gatsby-plugin-manifest: ^2.0.5 => 2.0.5
        gatsby-plugin-offline: ^2.0.5 => 2.0.6
        gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
        gatsby-plugin-sharp: ^2.0.6 => 2.0.6
        gatsby-plugin-typescript: ^2.0.0 => 2.0.0
        gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
        gatsby-remark-images: ^2.0.4 => 2.0.4
        gatsby-source-filesystem: ^2.0.3 => 2.0.3
        gatsby-transformer-remark: ^2.1.7 => 2.1.7

**Comment by kakadiadarpan** [comment]
@hackhat can you share the link to your website or repo for us to look at what's wrong?

> I managed to clear my android/chrome, there was 252MB of data

I assume you are talking about the data size which you get to know in app information. This size is the total data(stored locally) size for the browser and it's completely normal to have it that huge. (I have data size of 2 GB, doesn't cause any problem)

**Comment by hackhat** [comment]
I'm talking about my website specific data only, not the Android app data. 

I can't share the website I'm sorry.

I also can't reproduce it on all devices. After you clean the data works fine.

Sometimes gets messed up.

Also check the other issue https://github.com/gatsbyjs/gatsby/issues/9355 might be related to this, I don't know

**Comment by cardiv** [comment]
I see this happening from time to time on [gatsbyjs.org](gatsbyjs.org). Very unpredictable.

Made some screenshots with a bunch of JavaScript errors and the white screen. After a reload, the website is working again without errors in console.

**System:**
MacBook Pro 13" (mid 2014)
MacOS Mojave 10.14
Always up-to-date Chrome.

_Side note:_ When I reload the Gatsby site, the browser loads a second, finishes loading but screen remains white and after another second, Chrome renders the page. This happens every time, but not within incognito tab.

Hope that helps.

<img width="1280" alt="console-errors" src="https://user-images.githubusercontent.com/43521823/49038552-907ca180-f1bd-11e8-83fc-0bb44a45c1a0.png">
<img width="682" alt="white-screen" src="https://user-images.githubusercontent.com/43521823/49038553-91153800-f1bd-11e8-8864-86ee5083c431.png">
