### ISSUE TITLE
gatsby new site from template don't work on ie 10 

### ISSUE THREAD

**Issue by abumalick** [gatsbyjs/gatsby#9348]
## Description
A fresh new site crashes on ie 10 because 'Set' (used in react-dom) is not polyfilled.

### Steps to reproduce
open https://gatsby-freshinstall.netlify.com with ie10

(source: https://github.com/abumalick/gatsby-freshinstall )

or:
- create a new site with gatsby-cli
- deploy to netlify
- test deploy link with ie10

### Expected result
javascript should load without error

(a polyfill should be included automatically by babel-env ?)

### Actual result

'Set is undefined': 
![image](https://user-images.githubusercontent.com/8377185/47420470-cd98e280-d77e-11e8-9337-1ff1ef667e3a.png)

this is a screenshot of sentry from another project, tested with ie10 windows 7 on browserstack:
![image](https://user-images.githubusercontent.com/8377185/47421153-4ea4a980-d780-11e8-9042-85a044c3cc02.png)

### Other notes

I had a similar problem with `redux-form` including a polyfill for string.prototype.startsWith fixed the problem. ref: https://github.com/erikras/redux-form/issues/4126

I will add a polyfill for `Set` to my projects until this is fixed in gatsby.

### Environment
(I am testing with browserstack)

```
gatsby info --clipboard

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
  Browsers:
    Chrome: 70.0.3538.67
    Firefox: 62.0.3
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.19 => 2.0.29
    gatsby-image: ^2.0.15 => 2.0.16
    gatsby-plugin-manifest: ^2.0.5 => 2.0.5
    gatsby-plugin-offline: ^2.0.5 => 2.0.8
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^2.0.7 => 2.0.7
    gatsby-source-filesystem: ^2.0.4 => 2.0.5
    gatsby-transformer-sharp: ^2.1.4 => 2.1.4
```

**Comment by abumalick** [comment]
ie 9 and ie 10 are in the supported browser by default right ? https://github.com/gatsbyjs/gatsby/blob/master/.babel-preset.js#L13

**Comment by swashata** [comment]
Hi,

I don't know if gatsby and/or the babel preset provides polyfills by default. But this is surely a polyfill issue. Maybe you can try with https://polyfill.io/v2/docs/

**Comment by stefanprobst** [comment]
Do we need to set `corejs: true` option for `babel-transform-runtime`? Babel7 does not include those by default.
https://github.com/gatsbyjs/gatsby/blob/4d5c5e0d26c231b9ea1396a8c58432dc100411c0/packages/babel-preset-gatsby/src/index.js#L64-L68

**Comment by stefanprobst** [comment]
@DSchau Could you take a look at this? By default we target `["last 4 versions", "safari >= 7", "ie >= 9"]` but don't include the corejs polyfills with the babel runtime.

**Comment by DSchau** [comment]
@stefanprobst sure; I'll take a look here in a bit. We've heard similar issues tangentially about the browserslist not being picked up, so want to investigate that!

**Comment by yuriMalakhov** [comment]
@DSchau, any updates on this issue so far? If you provide more info and share any new ideas on how we can fix this, I would probably provide you with the PR. Because IE10 issues are very critical for our company. Thanks in advance!

**Comment by abumalick** [comment]
I think adding this line at the beginning of `gatsby-browser.js` fixes this error.

  `import 'core-js/modules/es6.set';`

**Comment by yuriMalakhov** [comment]
@abumalick @DSchau Manually adding `import 'core-js/modules/es6.set';` polyfills to `gatsby-browser.js` is a workaround, but not real solution. As stated in [gatsby docs on browser support](https://www.gatsbyjs.org/docs/browser-support/) it should have IE9+ available with `browserslist`.
> Gatsby supports the same browsers as the current stable version of React.js which is currently IE9+ as well as the most recent versions of other popular browsers.

I think it should be fixed the way that `core-js/modules/es6.set` and other polyfills added automatically with respect to `browserslist` as it was designed.

**Comment by thebarty** [comment]
This issue still exists with current versions

**Comment by cbetta** [comment]
Could someone explain to me how this can be solved with the mentioned workaround?

I added `import 'core-js/modules/es6.set';` to `gatbsy-browser.js` but I'm still having issues.

**Comment by abumalick** [comment]
what is the first error message ?

**Comment by cbetta** [comment]
Still getting the same issue. The 'Set' one.

**Comment by abumalick** [comment]
Strange, for us it is working

Make sure the polyfills imports are in first position in gatsby-browser

We use these polyfills in our app:
```
import 'core-js/modules/es6.set'; // react-dom
import 'core-js/modules/es6.map'; // react-dom
import 'core-js/modules/es6.string.starts-with'; // redux-form
import 'raf/polyfill';
```

**Comment by MariuszDabrowski** [comment]
Having the same issue, has there been any other developments in regards to fixing this issue?

**Comment by cbetta** [comment]
Still running into issues with this. It seems like nothing from `gatsby-browser-js` is actually getting loaded into the browser. Not sure what might be causing this.
