### ISSUE TITLE
Update documentation for Build Sequence and Client Sequence 

### ISSUE THREAD

**Issue by tanvibhakta** [gatsbyjs/gatsby#9350]
The documentation on this page https://www.gatsbyjs.org/docs/gatsby-lifecycle-apis/#build-sequence
detailing how the build-sequence and client-sequence works is missing (and I don't see an open issue for this available already.)

I think this might take some reading of the code, to understand how the things work before writing them in a simplified manner? Not sure if there are already other resources available that we can then integrate into this.

**Comment by kakadiadarpan** [comment]
@tanvibhakta Thanks for raising this issue. I agree that it'll involve a good amount of code reading to understand how things work in Gatsby. Would you be open to work on this?

**Comment by kakadiadarpan** [comment]
This might be of help to you: [Behind the Scenes](https://www.gatsbyjs.org/docs/behind-the-scenes/)

**Comment by marcysutton** [comment]
Hi there! In feedback on gatsbyjs.org, this page resurfaced as needing an update. Specifically:

> "Is there an ETA on the Client sequence?" 
> "Does onInitialClientRender happen before or after wrapRootElement?"

Behind the Scenes, now called [Gatsby Internals](https://www.gatsbyjs.org/docs/gatsby-internals/), that would be a good resource in writing this doc. The docs on [Gatsby Node APIs](https://www.gatsbyjs.org/docs/node-apis/), [Gatsby SSR APIs](https://www.gatsbyjs.org/docs/ssr-apis/), [Gatsby Browser APIs](https://www.gatsbyjs.org/docs/browser-apis/) would likely be useful as well.

I've also opened #14937 for "Life and Times of a Gatsby Build", which would include similar information as this Lifecycle APIs page: it's currently in the same "Conceptual Guide" section, but would be more high-level whereas this would be about API details. I'd argue that this Lifecycle APIs doc could move into [Gatsby APIs](https://www.gatsbyjs.org/docs/api-reference/) to differentiate a bit. It could be a conceptual parent of the Node/SSR/Browser API pages, that instead talks about how they work together. I'm open to ideas, and this is up for someone to take on!

**Comment by sidharthachatterjee** [comment]
@alexlbr and I just got off a call discussing this. Alex will be picking this up!

**Comment by alexlbr** [comment]
@sidharthachatterjee thanks for taking the time to walk me through the code. Yes, I'll give work on this in the next days 💪

**Comment by marcysutton** [comment]
Hey @alexlbr, how's it going on this? Anything we can help with?

**Comment by alexlbr** [comment]
@marcysutton I spoke with @sidharthachatterjee last week to schedule some pair programming cause I needed some help. Sid is on holiday so we scheduled it for next week. I didn't think it was relevant so I didn't update it here. Sorry about that, and thanks checking if I need help :)

**Comment by sidharthachatterjee** [comment]
@alexlbr That was a fantastic chat! Thank you so much for setting this up and taking the time to work on this, Alex. 

@marcysutton We've discussed Bootstrap and Build Sequence so far which Alex is going to be writing up and will set up another call for the Client Sequence once these are in! 

(Will link to the recording of our call from today once it is ready)

**Comment by sidharthachatterjee** [comment]
Topic: Alex Lobera: 30 Minute Meeting
Start Time : Nov 19, 2019 02:38 PM

Meeting Recording:
https://zoom.us/recording/share/PYXroQdvUpTXC7AdrqzAjyNDcsZV51np-3_-6IQlWJ2wIumekTziMw

**Comment by alexlbr** [comment]
@marcysutton as discussed with @sidharthachatterjee:
✅ Update bootstrap sequence. https://github.com/gatsbyjs/gatsby/pull/19775
🗸   Update build sequence. I plan to do it this week based on https://zoom.us/recording/share/PYXroQdvUpTXC7AdrqzAjyNDcsZV51np-3_-6IQlWJ2wIumekTziMw
🗸   Update client sequence. I'll schedule another meeting with Sid to discuss this next wee.

**Comment by alexlbr** [comment]
@sidharthachatterjee I followed these instructions for the pull request https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/#gatsby-repo-install-instructions but [CircleCI gave this error "Out of them, 1 sites were not a Gatsby site"](https://github.com/reactgraphqlacademy/gatsby/runs/318505291). Did I do something wrong? How can I help to fix it?

**Comment by marcysutton** [comment]
@alexlbr how's it going with this issue? Are you still working on a PR? You can typically ignore most of the CI checks when working on a docs PR (aside from linting).

**Comment by alexlbr** [comment]
Hi @marcysutton, I was waiting for the [first part to be merged](https://github.com/gatsbyjs/gatsby/pull/19775) to continue with the rest. I plan to work on the build sequence next week.

**Comment by marcysutton** [comment]
Hey @alexlbr, looks like that PR was merged so you should be good to go now! Do you need anything from us to get started?

**Comment by marcysutton** [comment]
Hey @alexlbr, checking up on this issue–are you still able to work on this, or should we open it back up for someone else to take on?

**Comment by alexlbr** [comment]
@marcysutton sorry for being slow finishing this. I would like to work on it. Unfortunately, I won't be able to allocate any time in the next 2 or 3 weeks. If this issue is very urgent then go ahead and open it back, otherwise thanks for your patience :)
