### ISSUE TITLE
Using a Gatsby app as a package within a monorepo works

### ISSUE THREAD

**Issue by jedrichards** [gatsbyjs/gatsby#9352]
## Summary

I was surprised to discover that Gatsby is able to operate normally as a package within a monorepo, while importing and transpiling source code from other packages in the monorepo with its Webpack config.

Example repo: https://github.com/jedrichards/monorepo-test

## Relevant information

My assumption was that Gatsby would treat monorepo packages as it does everything from `node_modules` and exclude from compilation. Indeed, create-react-app recently [backed off](https://github.com/facebook/create-react-app/issues/5024) this sort of feature for its v2:

> We're going to revert monorepo support in favor of consuming library packages via nwb and provide excellent documentation on how to do so.

My example repo above is the simplest case, but I've tested more advanced setups (TypeScript, CSS Modules) and it seems like Gatsby is happily compiling these features found in code in the `@monorepo-test/components` package (which is resolved via a symlink in the monorepo's root node_modules).

I think it's rather good this just works, but was keen to find out more and whether this is a expected/supported use case before I base a whole set of projects on it. I couldn't find anything about it in the documentation.

### Environment

```
gatsby info --clipboard

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    Yarn: 1.13.0-20181004.1524 - ~/.yarn/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 61.0.2
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.19 => 2.0.29
  npmGlobalPackages:
    gatsby-cli: 2.4.3
```

**Comment by jedrichards** [comment]
Is this stale, or has the inkteam not reviewed yet? I'd be keen to shed some light on this, although not critical. Feel free to close otherwise.

**Comment by johntran** [comment]
I'm evaluating Gatsby in a monorepo environment. I found this issue through a Google search. Thank you for doing a writeup on it :).

**Comment by johntran** [comment]
I did find this Gatsby blog entry about monorepos on Lerna. I am thinking that if its on the official blog, it means its officially supported.

https://www.gatsbyjs.org/blog/2019-01-01-publish-multiple-gatsby-sites/

**Comment by jedrichards** [comment]
@johntran Oh interesting, ty for the blog link! 👀

**Comment by josefaidt** [comment]
Hi I just found this issue after updating my own issue regarding Gatsby in a monorepo with lerna. The way I got gatsby to work was to add it as a dependency in the project root! 

See #11780 

Unfortunately I'm having issues with a small handful of plugins, but other than that Gatsby *does* work in a monorepo

**Comment by jedrichards** [comment]
@josefaidt Have a look at my working example repo. You might need to use `nohoist` on Gatsby:

https://github.com/jedrichards/monorepo-test/blob/master/gatsby-app/package.json#L38-L40

**Comment by josefaidt** [comment]
Yes I just jumped into that repo and saw that `"workspaces": { "nohoist": ["gatsby"] }` line. That's really clever, I didn't realize you could do that. I'm going to try this with those other plugins I'm having issues with and see if that resolves it.

**Comment by josefaidt** [comment]
@jedrichards how are you able to get this to work?

```json
"workspaces": {
    "packages": ["*"]
  }
```

I tried adding this to my workspace and then yarn wouldn't pick anything up until I made it back to an array. I was originally following this piece from the [yarn documentation](https://yarnpkg.com/lang/en/docs/workspaces/#toc-how-to-use-it) where it claims workspaces should be an array.

That being said I cloned your repo and installed the dependencies (including the ones I was having trouble with) and do not have a single issue.

**Comment by jedrichards** [comment]
@josefaidt I think just `["*"]` means yarn will treat any folder in the root as a workspace, i.e. using the `*` wildcard. So the packages in my example repo are at the top level `/gatsby-app` and `/components`. I think you're packages _need_ to be at the top level for that to work.
