### ISSUE TITLE
Help with using UIKit

### ISSUE THREAD

**Issue by paulclifford** [gatsbyjs/gatsby#9354]
## Summary
I'd like some help using UIkit with Gatsby. Using the current Gatsby default starter I've:

1. NPM installed uikit, node-sass, and gatsby-plugin-sass
2. created a style.scss with:
@import 'node_modules/uikit/src/scss/variables-theme.scss';
@import 'node_modules/uikit/src/scss/mixins-theme.scss';
@import 'node_modules/uikit/src/scss/uikit-theme.scss';
and called this style.scss from the layout component
3. tried using the following code in the layout component:
import UIkit from 'uikit'
import Icons from 'uikit/dist/js/uikit-icons';
if (typeof UIkit.use === 'function') UIkit.use(Icons);

The UIkit styling is showing up, but the JS is not working. Any tips?

**Comment by kakadiadarpan** [comment]
@paulclifford can you provide a reproduction repo for this? That would make it much easier to help you out.

Also, can you please provide environment info by running `gatsby info --clipboard`?

**Comment by paulclifford** [comment]
Thanks, I figured it out. Magic happens here:

https://github.com/qulib/qul-gatsby-starter/blob/master/src/components/Layout.jsx

**Comment by mifantwan** [comment]
```
if (typeof window !== 'undefined') {
  const UIkit = require("uikit/dist/js/uikit.min")
  const icons = require("uikit/dist/js/uikit-icons.min")
  const flowType = require("flowtype-js")

  UIkit.use(icons)
}
```

add this to layout.js.
I don't know if this is a good way ... it's just working on the latest version of Gatsby.
