### ISSUE TITLE
alias `develop` script to `start` in all starters and gatsby applications

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#9369]
## Summary

It's pretty expected in frontend for a `start` script to exist that will launch a local development server that will watch for file changes and reload--hot or otherwise. See create-react-app, angular-cli, etc. for prior art, here.

Similarly, we should expose a `start` script that aliases the `develop` script in our Gatsby projects. Minimally, it should be done in the following projects:

- gatsbyjs/gatsby-starter-hello-world
- gatsbyjs/gatsby-starter-default
- gatsbyjs/gatsby-starter-blog
- gatsbyjs/gatsby (www/ folder)
- gatsbyjs/examples/* (all the examples)

### Basic example

```diff
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write \"src/**/*.js\"",
+   "start": "npm run develop",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```

### Motivation

Users (myself included) tend to naturally assume `npm start` or `yarn start` will work in most frontend projects, and this matches that mental model.

**Comment by merelinguist** [comment]
Can I take this?

**Comment by DSchau** [comment]
@merelinguist you better believe it! Marking it as claimed, thank you 💪 💜

**Comment by Optarion** [comment]
Hi there.
Can I take this one ?
10hours to make 5 copy/past seems a bit too long to me.

**Comment by merelinguist** [comment]
Adrien, go ahead :).
On 25 Oct 2018, 07:46 +0100, Adrien Rousselet <notifications@github.com>, wrote:

Hi there.
Can I take this one ?
10hours to make 5 copy/past seems a bit too long to me.

**Comment by qnoox** [comment]
I this still up for grabs? ready to start right away.

**Comment by anjaliannahuja** [comment]
Is this issue resolved?

**Comment by DSchau** [comment]
@anabellaspinelli doesn't look like it was added to the following packages:

- https://github.com/gatsbyjs/gatsby-starter-blog/blob/master/package.json#L53
- any of the examples (https://github.com/gatsbyjs/gatsby/tree/master/examples)

So there's still more to do, I think!

**Comment by iamnishantmishra** [comment]
Can I take this?

**Comment by DSchau** [comment]
@iamnishantmishra sure, maybe handle the gatsby-starter-blog and then if you have the bandwidth, the examples would be great too! Sound like a plan?

**Comment by iamnishantmishra** [comment]
I have already created a pull request for gatsby-starter-blog. Working on examples. Thanks for the guidance :)

**Comment by iamnishantmishra** [comment]
Created pull request for gatsby/examples/*

**Comment by iamnishantmishra** [comment]
@DSchau can I close this issue?

**Comment by DSchau** [comment]
Sure thing; thank you!
