### ISSUE TITLE
Tutorial: add `gatsby-image`

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#9374]
## Summary

We want to create a new tutorial for `gatsby-image` for intermediate users. This learning resource should show how to create responsive images step-by-step. It would fit best as the first item on the [Additional Tutorials](https://www.gatsbyjs.org/tutorial/advanced-tutorials/) page. 

Here's some information on creating tutorials: https://www.gatsbyjs.org/contributing/docs-templates/#tutorials

### Motivation

Many Gatsby users don't know about `gatsby-image` and it's one of the most noticeable benefits to Gatsby site visitors. 

@jlengstorf continuing the discussion from https://github.com/gatsbyjs/gatsby/issues/9158#issuecomment-432853609

**Comment by siddhant1** [comment]
On it !

**Comment by jlengstorf** [comment]
All yours, @siddhant1!

@shannonbux Where do you think this should go? My thought is that it might be its own new section after Part 4 that could be called "Using Images in Gatsby".

Things to cover:

- Gatsby _can_ use regular images, just like any other web framework (show a small example)
- Gatsby has tools to automatically optimize images that have been packaged up in `gatsby-image`
- Show how to install `gatsby-image` and it's peer dependencies
- Configure the peer deps to load images from a folder
- Write a query to load the image data for `gatsby-image`
- Discuss the different options (e.g. traced SVG, WebP)
- Link to using-gatsby-image.gatsbyjs.org

Anything I'm missing here?

**Comment by treb0r** [comment]
It would be great to see some documentation on how to leverage an external service such as [imgix](https://www.imgix.com/) with gatsby-image, possibly using [react-imgix](https://github.com/imgix/react-imgix).

**Comment by justinformentin** [comment]
siddhant1 are you still working on this? Just wondering, because if not, I have it ready to go.

**Comment by justinformentin** [comment]
@siddhant1 are you still working on this? Just wondering, because if not, I have it ready to go.

**Comment by lvrbrtsn** [comment]
Can I take this?

**Comment by siddhant1** [comment]
@Ivrbrtsn sure !

**Comment by shannonbux** [comment]
@lvrbrtsn thanks! See @jlengstorf's comment above. https://github.com/gatsbyjs/gatsby/issues/9374#issuecomment-433088391

The idea is basically a standalone tutorial on how to put images in a Gatsby site and we can point people to this tutorial *after* they finish part eight of the current main tutorial. We consider `gatsby-image` a best practice, but like Jason said, it's important to also teach people the most fundamental and common ways of putting images in Gatsby sites (see the [Style Guide](https://www.gatsbyjs.org/docs/gatsby-style-guide/#share-best-practices-whenever-possible) for clear reasoning on why we do this).

**Comment by harshil1712** [comment]
Is anyone working on this? I would like to take this one

**Comment by lvrbrtsn** [comment]
@harshil1712 Feel free! I have not made much progress and have a lot coming up this next month.

**Comment by KyleAMathews** [comment]
Updated the description to make clear this issue is for a separate tutorial, not to amend the main tutorial.

**Comment by harshil1712** [comment]
Just to be on the right track, this file should be in the docs folder, right?

**Comment by KyleAMathews** [comment]
Yup!

**Comment by shannonbux** [comment]
Yes. It could go under the `Advanced Tutorials` section in the
`doc-links.yml` file or potentially under `Images and Files`. The tutorial
should assume that the reader has at least gone through the Main Tutorial,
or already knows how to do the tasks covered in the Main Tutorial.

Thanks!

**Comment by shannonbux** [comment]
Don't close!

**Comment by Harshithpabbati** [comment]
Was this still there?? Can I work on this ??

**Comment by harshil1712** [comment]
@Harshithpabbati I you want we can work on this together!

**Comment by Harshithpabbati** [comment]
sure @harshil1712 where were you struck???

**Comment by marcysutton** [comment]
Hey folks, let us know if you need any help starting the new image tutorial! It would be great to move this forward.

**Comment by siddhant1** [comment]
I was busy with some work earlier. Will work and close this one in a few days

**Comment by polarathene** [comment]
There is some changes I contributed to `gatsby-image` recently but didn't get around to documenting yet. Just saw this issue and it might be relevant to mention them. 

It was placeholder base64 related, for being able to set a custom width(instead of the default 20px), which can be useful when 20px doesn't "blur-up" well, or if you want to apply an actual CSS blur filter where a little more detail smooths that out nicely. You can find the related PR [here](https://github.com/gatsbyjs/gatsby/pull/10944). 

The other features were less likely to be useful, just like how the base64 width could be global or per image, you could force a base64 image format or use webp(smaller filesize) which works for Chrome/Firefox while using a bgcolor as a fallback for those not supporting webp.

**Comment by laurosilvacom** [comment]
@marcysutton I can help with the image tutorial?

**Comment by co16353sidak** [comment]
Hey, Seems like a lot of people have been attempting to work on this, If no one is currently working on the at the moment, I would love to take this up and make this my first contribution here.
@marcysutton @siddhant1 @shannonbux ?

**Comment by siddhant1** [comment]
Yeah ! Go for it!

**Comment by marcysutton** [comment]
We would definitely love for someone to take this on! If you're interested in working on it, go for it. Submitting a PR is the best way to move this forward.

The location for this in the docs may move as I'm proposing some changes to the Tutorial section (grouping the main tutorial + advanced tutorials) but that shouldn't impact the content. For ideas on what an image tutorial should cover, you can reference the previous comments from @shannonbux and @jlengstorf:

- https://github.com/gatsbyjs/gatsby/issues/9374#issuecomment-433088391
- https://github.com/gatsbyjs/gatsby/issues/9374#issuecomment-451484814

**Comment by polarathene** [comment]
[A PR for another feature to `gatsby-image` is currently in development/review](https://github.com/gatsbyjs/gatsby/pull/13395). It adds support for art-direction by supplying an array of fluid/fixed image data, allowing an image to represent multiple variants based on their matching media query condition.

Would be good to include that too, or an update if these docs are finished before the PR is merged.

**Comment by harshil1712** [comment]
I found three different articles which cover almost everything. [Artilce 1](https://www.gatsbyjs.org/packages/gatsby-image/), [Article 2](https://www.gatsbyjs.org/docs/working-with-images/), [Article 3](https://www.gatsbyjs.org/docs/using-gatsby-image/). Since there's documentation do we need to have a new one? We can give reference to them? If we still need to write a tutorial, will it be fine if I use those?

**Comment by marcysutton** [comment]
There would likely be some overlap in a gatsby-image tutorial, but it's worth keeping in mind the purpose of tutorials:

> Tutorials provide step-by-step guidance for Gatsby workflows, listing all pre-requisites and not assuming knowledge or skipping steps.

A tutorial could guide a user through setting all of this up without the limiting pressure of a reference guide to not be too lengthy. Maybe it would help to think of a tutorial as the written-version of a how-to video. You can certainly start by looking at the content that already exists, but make sure the steps all work in order.

**Comment by lstar19** [comment]
I'd be happy to take this on. I'd probably pull a lot from this post if that works?
https://dev.to/laurieontech/rewriting-a-static-website-using-gatsby-and-graphql---part-3-4ho9

**Comment by marcysutton** [comment]
That sounds great, @lstar19! If you can make it a standalone piece, that would be awesome. I would also recommend using the `useStaticQuery` hook if possible since it's a little bit simpler to read. Thanks again for offering to work on this!

**Comment by marcysutton** [comment]
Closed with #15027. Thanks so much for all the input here!
