### ISSUE TITLE
[site showcase] change initial load from 9 sites to 12

### ISSUE THREAD

**Issue by amberleyromo** [gatsbyjs/gatsby#9393]
Currently on first load of [`/showcase/`](https://www.gatsbyjs.org/showcase) we load nine sites. This produces empty space at some resolutions. Changing the initial number loaded to 12 will be smoother at more resolutions.

**Comment by outofgamut** [comment]
also had a PR in progress for this

**Comment by amberleyromo** [comment]
Yep, marking as claimed. Thanks @abilash13!

**Comment by amberleyromo** [comment]
Ah, ok @outofgamut.

@abilash13 could you check out the rest of the hacktoberfest issues? I'll be adding new Ecosystem ones periodically as well.

Apologies, I'll make it more clear that the issue should be claimed before a PR is opened. Y'all are too quick on the draw..!

**Comment by abilash13** [comment]
Ah no worries. Thanks!

**Comment by amberleyromo** [comment]
Thank you @abilash13! 🙏🏼

**Comment by amberleyromo** [comment]
Closed in #9395
