### ISSUE TITLE
Gatsby-plugin-page-transitions not allowing to build app in V2

### ISSUE THREAD

**Issue by d-ivashchuk** [gatsbyjs/gatsby#9396]
## Description

I am trying to use `gatsby-plugin-page-transitions` and everything works in the development mode, but when I try to build an app the following error pops up: `The plugin "gatsby-plugin-page-transitions@1.0.7" is exporting a variable named "replaceHistory" which isn't an API.`

That's probably because of deprecation of `replaceHistory` as an API in V2

### Steps to reproduce

Use plugin as explained in [](https://www.gatsbyjs.org/packages/gatsby-plugin-page-transitions/)

### Expected result

No errors when running `gatsby build`

### Actual result

Error stating `Replace history is not API`

### Environment
  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 6.10.1 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 56.0.2
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.19 => 2.0.19 
    gatsby-image: ^2.0.15 => 2.0.15 
    gatsby-plugin-feed: ^2.0.8 => 2.0.8 
    gatsby-plugin-google-analytics: ^2.0.5 => 2.0.5 
    gatsby-plugin-hotjar: ^1.0.1 => 1.0.1 
    gatsby-plugin-manifest: ^2.0.5 => 2.0.5 
    gatsby-plugin-offline: ^2.0.5 => 2.0.5 
    gatsby-plugin-page-transitions: ^1.0.7 => 1.0.7 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-sharp: ^2.0.6 => 2.0.6 
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.0 
    gatsby-plugin-typography: ^2.2.0 => 2.2.0 
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.0.5 
    gatsby-remark-images: ^2.0.4 => 2.0.4 
    gatsby-remark-prismjs: ^3.0.0 => 3.0.0 
    gatsby-remark-responsive-iframe: ^2.0.5 => 2.0.5 
    gatsby-remark-smartypants: ^2.0.5 => 2.0.5 
    gatsby-source-filesystem: ^2.0.2 => 2.0.2 
    gatsby-source-graphcms: ^1.0.0-alpha.3 => 1.0.0-alpha.3 
    gatsby-transformer-remark: ^2.1.6 => 2.1.6 
    gatsby-transformer-sharp: ^2.1.3 => 2.1.3 
  npmGlobalPackages:
    gatsby-cli: 2.4.3

I would really appreciate if someone suggested a viable workaround as the issue doesn't seem like resolving in the nearest future. `From the words of creator of the plugin`

**Comment by kakadiadarpan** [comment]
@d-ivashchuk `gatsby-plugin-page-transitions` is not compatible with Gatsby v2 currently. It uses `replaceHistory` API which was removed during the Gatsby major version upgrade. Please refer to [Migration documentation](https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#browser-api-replacehistory-was-removed).

**Comment by Codigo-Fuentes** [comment]
quick question: does anyone know why the plugin works in development mode given that the api is deprecated?

**Comment by jonniebigodes** [comment]
@Codigo-Fuentes Gatsby in development mode is more permissive, it will let you get away with some situations like this case. Only when you issue a production build through `gatsby build`,  that you might run into some issues. So with that in mind. Be mindfull of the plugins you use. And also the packages you add to your project, there are some that "play nice" and let you get a good experience, others not so much, or not at all.
