### ISSUE TITLE
How to persist state with 'navigateTo'

### ISSUE THREAD

**Issue by h0rhay** [gatsbyjs/gatsby#9398]
Hi does anyone have tips on how to persist state using 'navigateTo'?

(Context wise, I have a list of links in a ul, and I'm trying to keep the ul open in an accordion style, as its default state is closed.)

I have a react class component that sets state in the constructor.

Whenever a link is clicked to load in another markdown file, i change the view with:
```
navigate (e, path) {
    e.preventDefault()
    this.handleLinkChange()
    navigateTo(path)
  }
```
the 'handleLinkChange' is just a straightforward state method:
```
handleLinkChange () {
    this.setState(prevState => ({
      toggleNavOpen: !prevState.toggleNavOpen
    }))
  }
```

When the navigateTo fires, it switches the content nicely but seems to obliterate the entire state object with a freshly rendered one meaning the values I'm counting on are back to their default (false) state.

Any help would be massively appreciated, I've being trying to solve this for ages.

Trying to avoid localStorage or Redux for now.. but I guess if its the only way to get this done, I may have to go down that route..

Thanks

George

**Comment by maecapozzi** [comment]
Hey @h0rhay, are you on Gatsby v1 or Gatsby v2?

**Comment by h0rhay** [comment]
Hi @maecapozzi I'm on V1 at the moment, thanks for having a look :)

**Comment by henrych4** [comment]
Try to log ```window.history.state```. This should work for V2, not sure for V1.
Ref: #9091

**Comment by h0rhay** [comment]
Is there any documentation I can refer to for this issue?

I am essentially trying to pass some toggled state between 2 pages when a navigation occurs.

So you click a link.. this toggles some state, then the page you arrive on would have access to this toggled state.

I'm trying with Gatsby v2 like this:

```
class IndexPage extends React.Component {
  constructor (props) {
    super (props)
    this.state = {
      toggle: false
    }
    this.handleClick = this.handleClick.bind(this)
  }

  handleClick () {
    this.setState(prevState => ({ 
      toggle: !prevState.toggle
    }))
    console.log('click',this.state.toggle)
  }

  render () {
    const props = this.props
    return (
      <Layout>
        <h1>Hi people</h1>
        <p>Welcome to your new Gatsby site.</p>
        <p>Now go build something great.</p>
        <div style={{ maxWidth: '300px', marginBottom: '1.45rem' }}>
          <Image />
        </div>
        <Link to="/page-2/" state={{
            toggle: this.handleClick,
          }}>Go to page 2</Link>
      </Layout>
    )
  }
}

export default IndexPage
```

I guess I need redux or similar for this right?

**Comment by jonniebigodes** [comment]
@h0rhay, one thing that caught my eye when looking at your code.
Why are you passing the function to the state and not the state value itself?

You have: 

```javascript
handleClick () {
    this.setState(prevState => ({ 
      toggle: !prevState.toggle
    }))
    console.log('click',this.state.toggle)
  }
render () {
    const props = this.props
    return (
      <Layout>
        <h1>Hi people</h1>
        <p>Welcome to your new Gatsby site.</p>
        <p>Now go build something great.</p>
        <div style={{ maxWidth: '300px', marginBottom: '1.45rem' }}>
          <Image />
        </div>
        <Link to="/page-2/" state={{
            toggle: this.handleClick, //function call not value
          }}>Go to page 2</Link>
      </Layout>
    )
  }
```
When you should probably should have this:
```javascript
render () {
    const props = this.props
   const {toggle}= this.state
    return (
      <Layout>
        <h1>Hi people</h1>
        <p>Welcome to your new Gatsby site.</p>
        <p>Now go build something great.</p>
        <div style={{ maxWidth: '300px', marginBottom: '1.45rem' }}>
          <Image />
        </div>
        <Link to="/page-2/" state={{
            toggle:toggle  // from state destructuring
          }}>Go to page 2</Link>
      </Layout>
    )
  }
```
then when you "land" on the page you want you can set the state on that page accordingly and push it back to the previous one using the same strategy.
As per [docs](https://www.gatsbyjs.org/docs/gatsby-link/)

**Comment by h0rhay** [comment]
Finally figured out a way to achieve this 👍 
Its all in here:
props.location.state

```
import React from 'react'
import { Link } from 'gatsby'

import Layout from '../components/layout'
import Image from '../components/image'


class IndexPage extends React.Component {
  render () {
    const props = this.props
    return (
      <Layout>
        {console.log('index page', props.location.state)}
        <h1>Hi people</h1>
        <p>Welcome to your new Gatsby site.</p>
        <p>Now go build something great.</p>
        <div style={{ maxWidth: '300px', marginBottom: '1.45rem' }}>
          <Image />
        </div>
        <Link
          to="/page-2/"
          activeStyle={{
            color: "red",
          }}
          innerRef={el => {
            this.myLink = el
          }}
          state={{
            toggle: props.location.state.toggle === null ? props.location.state.toggle = true : !props.location.state.toggle,
          }}
        >
          Page 2
        </Link>
      </Layout>
    )
  }
}

export default IndexPage
```

**Comment by dcorb** [comment]
I'm having the same issue, probably because in my case the destination page is a dynamic page created with `createPages` hook
In this case, what component should receive the  `props.location.state`?  The template `tpl.js` file  ?

Btw, notice that don't follow the docs from  https://reach.tech/router/api/navigate. They are wrong https://github.com/reach/router/issues/96 ,  but Gatsby docs are correct
