### ISSUE TITLE
Array of dynamic images

### ISSUE THREAD

**Issue by dwehrmann** [gatsbyjs/gatsby#9403]
What's the approach of querying for an array of images to use with gatsby-image, e.g. for a slider or a gallery?

I've seen examples by @melissamcewen in #3380 but as far as I understood, these were queried by their filename. In my case the filenames are not known and rather cryptic because they come from the strapi-api, so I cannot filter for their filenames.

Any help would be greatly appreciated.
Thanks!

**Comment by oorestisime** [comment]
Would you receive only images from the api? You could use the gatsby-image fragment on every node maybe? Something along the following:

```
allFile {
    edges {
      node {
	childImageSharp {
          fluid(maxWidth: 600) {
            ...
          }
        }
      }
    }
  }
```

If the file is not an image then actually then `childImageSharp` would be null.

I am not sure this is what you are searching. otherwise you would need to provide some more information on the structure of your queries

**Comment by dwehrmann** [comment]
Thanks @oorestisime,

the api returns a complex set of items, like

```
query ReferenzDetail($id: String!) {
    strapiReferenz(id: { eq: $id }) {
      Title
      Ref_Description_Intro
      Ref_Description_Fulltext
      Ref_Leistungen
      Ref_Kunde
      Ref_Fakten
      Ref_Category
      lat
      lon
      zoom
      Ref_Images {
        url           
      }
    }
```

whereas 'Ref_Images' is where a flexible amount of images are stored. 
In the frontend, this resembles a project page with an image slider at the top and different text fields below.
Displaying the images the `Ref_Images.url` way works locally/in dev mode but of course not when deploying as I'm not making use of gatsby-image. But with gatsby-image, I don't know how to load the images associated with the  entry.

**Comment by dwehrmann** [comment]
Ah, that explains a lot. Just for my understanding: Isn't that what the gatsby-strapi plugin already does? https://github.com/strapi/gatsby-source-strapi

**Comment by oorestisime** [comment]
i have never used that source plugin. out of a quick search it seems that it is using that yes but you should probably check with them on how to query those. generally a way to use it on a single node is something like the following:

```
node {
  localFile {
    childImageSharp {
      fixed(width: 150, height:150) {
        ...GatsbyImageSharpFixed
      }
    }
  }
}
```

**Comment by oorestisime** [comment]
Feel free to close this issue :)
