### ISSUE TITLE
how could I build the article for diffrent Directory？

### ISSUE THREAD

**Issue by posebear1990** [gatsbyjs/gatsby#941]
Hello, I have followed this project for so long, there are some ting puzzling me is that how could I build the article for diffrent Directory on my disk). And then I colud access my article like www.myblog.com/blog/category1/someArticles and www.myblog.com/blog/category2/someOtherArticles etc... And if the freamwork could not support by origin. How colud I write my own code for support it?In gatsby-node.js file or in the other stage?THX again ^_^

**Comment by KyleAMathews** [comment]
Hi! Gatsby v1 is designed explicitly for this sort of thing!

Documentation is still limited (Finshing up remaining work in alphas) but checkout this case study https://www.gatsbyjs.org/blog/gatsbygram-case-study/ and my blog's code https://github.com/kyleamathews/blog

**Comment by KyleAMathews** [comment]
This is the source code for gatsbyjs.org https://github.com/gatsbyjs/gatsby/tree/1.0/www and here are the example sites https://github.com/gatsbyjs/gatsby/tree/1.0/examples
