### ISSUE TITLE
Traced SVG for gatsby-remark-images

### ISSUE THREAD

**Issue by hackhat** [gatsbyjs/gatsby#9414]
Reopen https://github.com/gatsbyjs/gatsby/issues/4624

I am using Traced SVG option from gatsby-image for my non-article images and I love it.

However for my markdown images, there is only available blur-up effect, which means image loading is inconsistent. It would be nice to have traced svg also for gatsby-remark-ima

**Comment by kakadiadarpan** [comment]
@hackhat would you be open to work on this and raise a PR?

You can get the required information from #4624, if you need more support we can help you.

**Comment by hackhat** [comment]
@kakadiadarpan I can't do it at the moment, sorry. I took a look at the code and is a huge function that does everything (for the image), anyone is considering to refactor that in something more digestable?

**Comment by tlent** [comment]
I have started working on this and made some good progress. I will be opening a pull request soon.
