### ISSUE TITLE
[1.0] Gracefully handle relay compiler errors

### ISSUE THREAD

**Issue by 0x80** [gatsbyjs/gatsby#942]
It seems that if you now query a data field that is not available, gatsby can't start at all and fails with an error like:

```
UNHANDLED REJECTION Invariant Violation: RelayParser: Unknown field `body` on type `PostsJson`. Source: document `PostPage` file: `GraphQL`.
    at invariant (/Users/somepath/node_modules/fbjs/lib/invariant.js:44:15)
    at RelayParser._transformField (/Users/somepath/node_modules/relay-compiler/lib/RelayParser.js:341:34)
    at /Users/somepath/node_modules/relay-compiler/lib/RelayParser.js:268:23
    at Array.map (native)
    at RelayParser._transformSelections (/Users/somepath/node_modules/relay-compiler/lib/RelayParser.js:265:36)
    ...
    ...
```

It would be nice if these errors were caught, so that the server can start and you can inspect the data with the graphiql interface. I believe it worked like that before the relay-compiler refactoring.

**Comment by jquense** [comment]
I was hoping to do this in a more general "better cli logging" PR Yeah

**Comment by KyleAMathews** [comment]
👍  to not dying immediately on graphql errors.

**Comment by revolunet** [comment]
not sure if related but for me, commenting [this line](https://github.com/gatsbyjs/gatsby/blob/9f9c005b08f4946c0f224218faf7e0da0f861349/packages/gatsby/src/internal-plugins/query-runner/query-watcher.js#L86) and adding a check in the following `if` for `components[id]` fixes the problem : `gatsby develop` doesnt crash

**Comment by KyleAMathews** [comment]
@revolunet oh this issue should be closed. We don't crash gatsby develop on graphql errors. If you're having troubles with that invariant that's a different issue (which we'd love to discuss in another issue!).
