### ISSUE TITLE
add html comments to gatsby

### ISSUE THREAD

**Issue by cahhvoy** [gatsbyjs/gatsby#9424]
## Summary

sometimes you just want to temporarily disable a section in a HTML page or component see the results and continue but gatsby creates a syntax error.

### Basic example

`<!-- this a comment -->`
but when i do this the error i get
_SyntaxError: A:\_gatsby\bcksitetwo\src\pages\index.js: Unexpected token (**pageline here**)_

### Motivation

i need to be able to test different outcomes of changing the a HTML element without the need to delete it and paste it back.

**Comment by kakadiadarpan** [comment]
@cahhvoy Adding HTML comments in React is a little different compared to how you do it in regular HTML as you are writing JSX now.

Please check this link to see how to add [comments in JSX](https://wesbos.com/react-jsx-comments/).
