### ISSUE TITLE
How to don't wrap a custom component with a `<p>` tag? gatsby-transformer-remark 

### ISSUE THREAD

**Issue by hackhat** [gatsbyjs/gatsby#9425]
How to don't wrap a custom component with a `<p>` tag? gatsby-transformer-remark 

I have a custom component which is a div, therefore div inside p is invalid html. Any solutions?

See demo here: https://using-remark.gatsbyjs.org/custom-components/

>If your Gatsby site is for vacation photos, you might write a component that allows you to show a carousel of pictures, and perhaps a map that shows where each photo was taken.

Their usage implies that you can have complex components, so I don't think is good to put them in a p tag.

**Comment by hackhat** [comment]
I managed to create a custom P component that will check if the children are "special" and don't render the p tag. Is very hacky so another solution should be find.

**Comment by hackhat** [comment]
just put in production and this solution doesn't work, resulted in adding the p back: https://github.com/gatsbyjs/gatsby/issues/9463

**Comment by alisonjoseph** [comment]
You should be able to add this to fix the p tag wrapping for your custom components. https://www.gatsbyjs.org/packages/gatsby-remark-component/

**Comment by hackhat** [comment]
Great thanks
