### ISSUE TITLE
How to use React-Visibility-Sensor in a gatsby website?

### ISSUE THREAD

**Issue by ammarbinfaisal** [gatsbyjs/gatsby#9427]
how can I use [React-VisibilitySensor](https://www.npmjs.com/package/react-visibility-sensor) in a gatsby website?  
building (`gatsby build`) shows error window not defined.
I am checking whether window is undefined(gatbsy is building pages) and rendering it without visibilityCheck component if it is otherwise with VisibilityCheck component.
how to prevent this?

**Comment by kakadiadarpan** [comment]
@ammarbinfaisal can you share more information about the error that you are getting?

**Comment by ammarbinfaisal** [comment]
error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

   8 | 	else
   9 | 		root["react-visibility-sensor"] = factory(root["React"], root["ReactDOM"]);
> 10 | })(window, function(__WEBPACK_EXTERNAL_MODULE__1__, __WEBPACK_EXTERNAL_MODULE__2__) {
     |  ^
  11 | return /******/ (function(modules) { // webpackBootstrap
  12 | /******/ 	// The module cache
  13 | /******/ 	var installedModules = {};


  WebpackError: ReferenceError: window is not defined
  
  - visibility-sensor.js:10 Object../node_modules/react-visibility-sensor/dist/visibility-sensor.js
    [lib]/[react-visibility-sensor]/dist/visibility-sensor.js:10:2
  
  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1
  
  - Message.jsx:1 Module../src/components/Message.jsx
    lib/src/components/Message.jsx:1:1
  
  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1
  
  - index.js:1 Module../src/pages/index.js
    lib/src/pages/index.js:1:1
  
  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1
  
  - sync-requires.js:6 Object../.cache/sync-requires.js
    lib/.cache/sync-requires.js:6:51
  
  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1
  
  - static-entry.js:9 Module../.cache/static-entry.js
    lib/.cache/static-entry.js:9:22
  
  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1
  
  - bootstrap:83 
    lib/webpack/bootstrap:83:1
  
  
  - universalModuleDefinition:3 webpackUniversalModuleDefinition
    lib/webpack/universalModuleDefinition:3:1
  
  - universalModuleDefinition:10 Object.<anonymous>
    lib/webpack/universalModuleDefinition:10:2
  
  - static-entry.js:115 Module._compile
    lib/.cache/static-entry.js:115:29
  
  - static-entry.js:131 Object.Module._extensions..js
    lib/.cache/static-entry.js:131:9
  

I think this would suffice.

**Comment by ammarbinfaisal** [comment]
sorry for being so foolish and not writing the error in the first place.
see the updated issue

**Comment by kakadiadarpan** [comment]
@ammarbinfaisal You shouldn't be so hard on yourself. Please check the documentation for [Debugging HTML Builds](https://www.gatsbyjs.org/docs/debugging-html-builds/), I think what you will need to is documented in **Fixing third-party modules** there.

We'll be closing this issue, please feel free to reopen if it doesn't solve your problem.

**Comment by ammarbinfaisal** [comment]
> @ammarbinfaisal You shouldn't be so hard on yourself.

Sorry, I dont get this? :confused:

**Comment by ACC-Ricky** [comment]
I wrapped the script within the "componentDidMount() {}" in the component and I have produced a successful build.
