### ISSUE TITLE
[1.0] Navigation is broken after reload on child route

### ISSUE THREAD

**Issue by fabien0102** [gatsbyjs/gatsby#943]
# Reproduction steps

1. Go to [Gatsby website](https://www.gatsbyjs.org)
1. Click on `blog`
1. Reload page with cache cleaning (ctrl+shift+R on chrome)
1. Click on any link

**Comment by fabien0102** [comment]
Manual bisect with netlify preview:
 - [x] https://github.com/gatsbyjs/gatsby/pull/911
 - [x] https://github.com/gatsbyjs/gatsby/pull/912
 - [x] https://github.com/gatsbyjs/gatsby/pull/934
 - [x] https://github.com/gatsbyjs/gatsby/pull/936
 - [x] https://github.com/gatsbyjs/gatsby/pull/929
 - [x] https://github.com/gatsbyjs/gatsby/pull/935
 - [x] https://github.com/gatsbyjs/gatsby/pull/936
 - [ ] https://github.com/gatsbyjs/gatsby/pull/939 (broken)

**Comment by KyleAMathews** [comment]
Thanks for the fine `bisect` work! That made it really easy to track down the problem!

**Comment by KyleAMathews** [comment]
Fixed in #944 thanks!
