### ISSUE TITLE
Links to non-existent hashes jump window scroll to the top of the page

### ISSUE THREAD

**Issue by richsilv** [gatsbyjs/gatsby#9434]
## Description

Gatsby v2's use of the *gatsby-react-router-scroll* package results in a jump to the top of the page if the location hash is changed to something which has no matching element on the page. This is inconsistent with normal browser behaviour.

### Steps to reproduce

* Navigate to https://www.gatsbyjs.org/docs.
* Scroll to the bottom of the page.
* Put `window.location.hash = "#foobar"` in the console __or__
  Manually add an anchor tag `<a href="#foobar">Click me</a>` at the bottom of the body and then click on it.

### Expected result

The address bar should update, but no scrolling should occur.

Here's a very simple, pure HTML example of this: http://hash-link-example.surge.sh

If you scroll to the bottom of the page and click on the anchor tag, which has a hash that doesn't appear in the page, the address bar is updated but the page doesn't scroll.

### Actual result

The browser scrolls back to the top of the page.

The reason is these lines in the `shouldUpdateScroll` function passed down to *gatsby-react-router-scroll* and then *scroll-behavior*:

https://github.com/gatsbyjs/gatsby/blob/e98ee672ed864aaa0a615124459c407f554d255d/packages/gatsby/cache-dir/navigation.js#L118-L120

I am happy to PR to simplify this logic, but I can only imagine there was a reason that it was added in the first place, so I'll hold off until advised.

### Environment

```console
  System:
    OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
    CPU: x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 8.10.0 - /usr/bin/node
    Yarn: 1.10.1 - ~/.npm-global/bin/yarn
    npm: 6.4.1 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
  npmPackages:
    gatsby: ^2.0.31 => 2.0.31 
    gatsby-image: ^2.0.17 => 2.0.17 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-sass: ^2.0.1 => 2.0.1 
    gatsby-plugin-sharp: ^2.0.8 => 2.0.8 
    gatsby-plugin-typescript: ^2.0.0 => 2.0.0 
    gatsby-source-filesystem: ^2.0.5 => 2.0.5 
    gatsby-transformer-json: ^2.1.4 => 2.1.4 
    gatsby-transformer-sharp: ^2.1.5 => 2.1.5 
  npmGlobalPackages:
    gatsby-cli: 2.4.3
```

**Comment by richsilv** [comment]
Thinking about this a bit more, is this to enforce scroll-to-top when there's a page transition including a hash which doesn't appear in the new page? That would make more sense, and the solution would be to suppress this behaviour whenever the link only involves changing the current `hash` and not the `pathname`.

**Comment by stefanprobst** [comment]
This seems to be `scroll-behavior`'s default intended behavior:

https://github.com/taion/scroll-behavior/blob/de09e3b1dd614818aff0fec93a9dc9956b4d1e88/src/index.js#L298

**Comment by richsilv** [comment]
I take your point, but in `scroll-behavior` this is configurable, whereas in `gatsby` it isn't as `shouldUpdateScroll` is hard-coded and passed into the root `ScrollContext`: https://github.com/gatsbyjs/gatsby/blob/0658f0bbec8f5fbfb770dc5bd368165116e5b7db/packages/gatsby/cache-dir/root.js#L63-L65

Is this something that could be changed in `onCreatePage`? Or otherwise, could a `shouldUpdateScroll` be passed in as a configuration option? Again, I'd happily implement the latter in a PR if necessary, but it seems that the user should at least have the option of mimicking the standard browser behaviour.
