### ISSUE TITLE
Gtag plugin doesn't work in dev (Probably just need to document so explicitly) 

### ISSUE THREAD

**Issue by talolard** [gatsbyjs/gatsby#9436]
Hi, 
We just installed the new gtag plugin and were a bit flustered until we realized it doesn't work in development. I assume it is expected behavior, it certainly feels correct in retrospect. However, it would be great to mention it in the docs. 
@tylerbuchea, can you confirm it is expected behavior ? If so, I'm happy to update docs accordingly. 
Cheers

**Comment by tylerbuchea** [comment]
Right it is the expected behavior. But mentioning that in the docs would save some frustration.

Thanks for your help 👊

**Comment by tylerbuchea** [comment]
This issue was resolved by ac9cbb7
