### ISSUE TITLE
Ability to rerender whole App

### ISSUE THREAD

**Issue by pungggi** [gatsbyjs/gatsby#9437]
## Summary

Ability to rerender whole App by extending the Browser API.

### Basic example

![grafik](https://user-images.githubusercontent.com/5635709/47571427-cae1ed00-d938-11e8-8d7b-388bd25a9b91.png)

### Motivation
Use with https://github.com/gunn/pure-store#subscribecallback

**Comment by kakadiadarpan** [comment]
@pungggi can you provide more information about this? Are you facing any issues currently in Gatsby(at present store is managed using redux)?

**Comment by pungggi** [comment]
sorry for the delay, I wanted to be sure I really need that.
meanwhile i realized/found what I really needed  > https://www.gatsbyjs.org/docs/browser-apis/#replaceHydrateFunction
