### ISSUE TITLE
Improve sourceNodes doc and tutorial page explanation about promise return

### ISSUE THREAD

**Issue by lexishanson** [gatsbyjs/gatsby#9459]
## Summary

Documentation for using `sourceNodes` could be improved to more clearly state returning a promise (or callback) to the function and the "why" behind it. 

We had a teammate that assumed they just needed to call `createNode()` within `sourceNodes` and that would be all that's needed. They were following the [Source Plugin Tutorial](https://www.gatsbyjs.org/docs/source-plugin-tutorial/). Turns out, when Gatsby was building, the nodes weren't finished being sourced and our workers were still returning results after the app had already compiled.

The [Source Plugin Tutorial](https://www.gatsbyjs.org/docs/source-plugin-tutorial/) has a code comment that says "// Gatsby expects sourceNodes to return a promise" in the snippet, but this is very hidden. It's not explained anywhere else in the tutorial text that this is important, and specifically why it's important.

In the [Create Source Plugin](https://www.gatsbyjs.org/docs/create-source-plugin/) doc page, it's mentioned that a promise or callback should be returned, but this could probably be re-written to be more clear.

### Basic example
I would propose adding/updating the explanations on both the tutorial page and the plugin doc page. Here are examples for each:

**Source Plugin Tutorial**

I'm open to feedback on the best place to add additional language. One option is to add additional explanation under the [Step by step through your gatsby-node.js file](https://www.gatsbyjs.org/docs/source-plugin-tutorial/#step-by-step-through-your-gatsby-nodejs-file) section.

> ...Then you implemented Gatsby’s sourceNodes API which Gatsby will run as part of its bootstrap process. _Gatsby expects `sourceNodes` to return either a promise or a callback (3rd parameter). This is important as it tells Gatsby to wait to move on to next stages until your nodes are sourced, ensuring your nodes are created before the schema is generated._

**Create Source Plugin**

Currently the language on this page says:

> Return either a promise or use the callback (3rd parameter) to report back to Gatsby when you’re done sourcing nodes. Otherwise either Gatsby will continue on before you’re done sourcing or hang while waiting for you to indicate you’re finished.

We could add more emphasis with this statement:

> You must return either a promise or use the callback (3rd parameter) to report back to Gatsby when `sourceNodes` is fully executed. 
> 
> Otherwise, Gatsby will continue on in the build process before nodes are finished being created. Your nodes might not end up in the generated schema at compilation, or the process will hang while waiting for an indication that it's finished.

### Motivation

Clearer explanations. Better developer experience. Avoid hidden build issues.

**Comment by lexishanson** [comment]
If this gets the green light I can go ahead and make these changes.

**Comment by jlengstorf** [comment]
@lexishanson both of these changes are great! Thanks for suggesting them!

I'm also working on a plugin course that will go in-depth on this. I hope to finish it reasonably soon. At that point, we'll be looking at a fairly comprehensive rewrite of the plugin docs.

In the meantime, it would be _wonderful_ if you wanted to add these changes. Thank you!
