### ISSUE TITLE
Production build rendering strong tags in places it should not

### ISSUE THREAD

**Issue by alalfakawma** [gatsbyjs/gatsby#9472]
## Description
I am uploading my gatsby app to Netlify but some of my components are not rendering data properly, as they were rendering in the development mode, the production mode is causing something that is putting <strong></strong> tags in between some of my dynamic data, also, dangerouslySetInnerHTML is not showing in some components but can be seen using the react dev tools\

### Steps to reproduce

You can check it out here: https://nostalgic-lalande-8fa09d.netlify.com/

### Expected result

There should not be double strong tags surrounding some of my descriptions, like in the portfolio section, it should be `THE <strong>BMM PORTFOLIO</strong>`.

### Actual result

The 'THE BMM PORTFOLIO' text is coming from a markdown file as `title`, I access it using `{ data.title }` in my component, but something is getting added in production mode which is adding strong tags around `{ data.title }`, which should not be happening.

### Environment

System:
    OS: Linux 4.13 elementary OS 0.4.1 Loki
    CPU: x64 Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
    Shell: 5.1.1 - /usr/bin/zsh
  Binaries:
    Node: 8.12.0 - /usr/bin/node
    npm: 6.4.1 - /usr/bin/npm
  Browsers:
    Chrome: 70.0.3538.67
  npmPackages:
    gatsby: ^2.0.0 => 2.0.7 
    gatsby-plugin-netlify: ^2.0.0 => 2.0.0 
    gatsby-plugin-netlify-cms: ^3.0.0 => 3.0.2 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-sass: ^2.0.1 => 2.0.1 
    gatsby-plugin-sharp: ^2.0.5 => 2.0.5 
    gatsby-remark-images: ^2.0.1 => 2.0.1 
    gatsby-source-filesystem: ^2.0.1 => 2.0.1 
    gatsby-transformer-remark: ^2.1.1 => 2.1.3 
    gatsby-transformer-sharp: ^2.1.1 => 2.1.1

**Comment by thorn0** [comment]
The steps to reproduce you've provided aren't really useful without any access to the source code. Could you try to isolate the issue and make a minimal example repo where the erroneous behavior would reproduce stably?

**Comment by alalfakawma** [comment]
Here is the git repo - https://github.com/alalfakawma/gatsbyissuerepo where I have reproduced this issue.

**Note** - This only happens on the build version, check the index.html of the build and inspect the text.

**Comment by thorn0** [comment]
What should be looked for in index.html? Double `strong` tags? There are none. I'm on Windows however, that's why our results might differ.

Are you using yarn or npm? Did you try updating the Gatsby packages?

**Comment by alalfakawma** [comment]
Looks weird indeed. I am using npm and deploying in netlify. Can you see the strong tags in the netlify link which I posted above? I have checked on different browsers but got the same result. And only on the build version, the dev version has no problems, the build version doesn't even render some content like on the carousel. Is there anything else I can tell you to troubleshoot this problem?

On Oct 30, 2018 23:12, Georgii Dolzhykov <notifications@github.com> wrote:

What should be looked for in index.html? Double strong tags? There are none. I'm on Windows however, that's why our results might differ.

Are you using yarn or npm? Did you try updating the Gatsby packages?

**Comment by thorn0** [comment]
Did you try updating the Gatsby packages to the latest versions, especially those having to do with markdown? If not, please try, it might be some issue that has already been fixed.

**Comment by thorn0** [comment]
Also please commit the `public` dir to your example repo so that we could what you get there.

**Comment by alalfakawma** [comment]
I have added the public file which was output after the build to the repo. I will try to update the Gatsby packages and see if that changes anything.

- https://github.com/alalfakawma/gatsbyissuerepo

**Comment by alalfakawma** [comment]
I just did an npm update and it updated some packages, including the gatsby-transformer-remark, I pushed it to Netlify and built in on the same link which I have up there, but the strong tags issue still persists.

**Comment by thorn0** [comment]
Now I see it. I was looking for double `strong` tags in the markup, but in fact there is just another opening tag instead of the closing one. And it comes directly from your frontmatter:
```
title: "Lorem ipsum dolor <strong>lorem<strong>"
```
See it? You didn't close the tag properly. Do you have the same situation in your original project? If so, seems like this issue can be closed.

**Comment by alalfakawma** [comment]
Wow, something that trivial caused such a problem, thank you so much for your time spent figuring it out. This was indeed the fix, as soon as I closed the strong tag. I will close this thread now.
