### ISSUE TITLE
gatsby-plugin-offline doesn't seem to work with Gatsby v2.0.19

### ISSUE THREAD

**Issue by jhackett1** [gatsbyjs/gatsby#9479]
## Description

Does gatsby-plugin-offline work with recent versions of Gatsby?

When I run `gatsby develop` I get the message `The plugin "gatsby-plugin-offline@2.0.9" is exporting a variable named "onPostPrefetchPathname" which isn't an API.`

This causes builds to fail too.

### Steps to reproduce

Install these deps and try building, I guess?

```
  "dependencies": {
    "gatsby": "^2.0.19",
    "gatsby-cli": "^2.4.3",
    "gatsby-plugin-offline": "^2.0.9",
  },
```

### Expected result

Site builds successfully and registers a service worker

### Actual result

Failed build and no service worker registered.

### Environment

System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i5-4590
CPU @ 3.30GHz
  Binaries:
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.0.19 => 2.0.19
    gatsby-cli: ^2.4.3 => 2.4.3
    gatsby-plugin-favicon: ^3.1.4 => 3.1.4
    gatsby-plugin-google-analytics: ^2.0.6 => 2.0.6
    gatsby-plugin-google-fonts: 0.0.4 => 0.0.4
    gatsby-plugin-intercom-spa: 0.0.5 => 0.0.5
    gatsby-plugin-manifest: ^2.0.6 => 2.0.6
    gatsby-plugin-netlify-cms: ^3.0.4 => 3.0.4
    gatsby-plugin-offline: ^2.0.9 => 2.0.9
    gatsby-plugin-react-helmet: ^3.0.0
=> 3.0.0
    gatsby-plugin-sass: ^2.0.1 => 2.0.1
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.1
    gatsby-remark-external-links: 0.0.4 => 0.0.4
    gatsby-source-filesystem: ^2.0.3 => 2.0.3
    gatsby-transformer-remark: ^2.1.7 => 2.1.7

**Comment by KyleAMathews** [comment]
Can you upgrade to the latest version of every package and try again?

**Comment by habibmustofa** [comment]
Hi, I faced the same problem when I tried `gatsby-plugin-offline`, I saw a warning when installing the plugin:
`npm WARN gatsby-plugin-offline@2.0.9 requires a peer of gatsby@>=2.0.20 but none is installed. You must install peer dependencies yourself.`
then I updated gatsby to version `" ^ 2.0.20 "`, the problem was solved.

sorry my bad.
Love Gatsby.

**Comment by LekoArts** [comment]
Updating Gatsby and the offline plugin to the latest version should resolve your issue. Please let us know if you have other problems, thanks!
Closing this issue as resolved for now.
