### ISSUE TITLE
  Error: Schema must contain unique named types but contains multiple types   named "String".

### ISSUE THREAD

**Issue by Khaledgarbaya** [gatsbyjs/gatsby#9488]
## Summary

I am working on a contentful rich text transformer plugin which will be very similar to the transformer remark.
I am getting 

```
Error: Schema must contain unique named types but contains multiple types   named "String".
```

When appending the field html to the richtext node

## Relevant information

Here is a PR with the plugin https://github.com/contentful/gatsby-transformer-contentful-richtext/pull/1

I am defining the field [here](https://github.com/contentful/gatsby-transformer-contentful-richtext/pull/1/files#diff-3268e184fa9321a32bf3799508bd288dR39)

Which is somehow conflicting with another schema that I couldn't find

### Environment (if relevant)

All environment

Any help will be appreciated.

**Comment by Khaledgarbaya** [comment]
cc @pieh

**Comment by pieh** [comment]
If you are using `yarn` - could you do `yarn why graphql` in your test site directory?

This error happens when the `GraphQLString` (or any other builtin graphql type) is imported from multiple instances of graphql package - but this really shouldn't happen when importing from `gatsby/graphql` :/

**Comment by Khaledgarbaya** [comment]
Hey @pieh here's the log

```
➜ yarn why graphql
yarn why v1.10.1
[1/4] 🤔  Why do we have the module "graphql"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "graphql@0.13.2"
info Reasons this module exists
   - "gatsby" depends on it
   - Hoisted from "gatsby#graphql"
   - Hoisted from "gatsby#relay-compiler#graphql"
info Disk size without dependencies: "2.26MB"
info Disk size with unique dependencies: "2.36MB"
info Disk size with transitive dependencies: "2.36MB"
info Number of shared dependencies: 1
✨  Done in 0.88s.
```

**Comment by pieh** [comment]
I have no clues - does it happen with `gatsby-transformer-remark` or `gatsby-transformer-sharp` (which use same thing in same way)?

**Comment by Khaledgarbaya** [comment]
This is the first time I encountered this issue it could be related to a recent release I will try to investigate that a bit

**Comment by Khaledgarbaya** [comment]
Hey @pieh,

After debugging a bit further it looks like `type instanceof GraphQLScalarType` here does return false.
which is weird

**Comment by Khaledgarbaya** [comment]
Ok after more investigation, I think this may be the issue why `instanceof` returns false 

Javascript is mind-bending: 

https://stackoverflow.com/questions/15502415/instanceof-operator-returns-false-on-subsequent-change-to-inheritance-chain

cc @pieh

**Comment by Khaledgarbaya** [comment]
This is from my debugging session

<img width="517" alt="screenshot 2018-11-21 at 10 33 30" src="https://user-images.githubusercontent.com/1156093/48833219-2c03b180-ed7b-11e8-8fd6-0e9f9c0e3b70.png">

**Comment by pieh** [comment]
@Khaledgarbaya I didn't try it locally but something worth checking - in `package.json` in your transformer https://github.com/contentful/gatsby-transformer-contentful-richtext/pull/1/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R44 you specify `gatsby` as dependency - this will potentially install extra `gatsby` package in `node_modules` - if you need `gatsby` to run test, this should be in `devDependencies` - this might be causing duplicated `gatsby` or `graphql` packages?

**Comment by loudmouth** [comment]
@Khaledgarbaya given the suggestion from @pieh 
I just pulled down https://github.com/contentful/gatsby-transformer-contentful-richtext/, checked out the `develop` branch and then moved the dependency on gatsby to `devDependencies` (i also had to comment out a line from the `.babelrc` since `babel-preset.js` isn't actually included in the working branch)...anyway, his suggestion works!

was successfully able to render rich text with the plugin this way. I think that would solve the issue.

**Comment by loudmouth** [comment]
It turns out that there is a disclaimer about this exact error message right in the [Gatsby docs for `setFieldsOnGraphQLNodeType`](https://www.gatsbyjs.org/docs/node-apis/#setFieldsOnGraphQLNodeType)

```
Note: Import GraphQL types from gatsby/graphql and don’t add the graphql package to your project/plugin dependencies to avoid Schema must contain unique named types but contains multiple types named errors. gatsby/graphql exports all builtin GraphQL types as well as the graphQLJSON type.
```

**Comment by pieh** [comment]
Yeah, but Khaled is importing properly already. Problem is there might be multiple gatsby or graphql packages in node_modules, so module resolution might point to different packages. We should propably add to not add gatsby as dependency (along with graphql package)

**Comment by loudmouth** [comment]
Yeah, I think amended the note I posted above with info that `gatsby` should not be in `dependencies` could help avoid others running into this.

**Comment by Khaledgarbaya** [comment]
I am closing this issue, for now, the main issue was I had multiple graphql dependencies

**Comment by janosh** [comment]
@Khaledgarbaya Any news regarding [gatsby-transformer-contentful-richtext](https://github.com/contentful/gatsby-transformer-contentful-richtext)? How come the repo was archived? Would be really to cool to use that!

**Comment by Khaledgarbaya** [comment]
@janosh it was moved [here](https://github.com/contentful/rich-text/tree/master/packages/gatsby-transformer-contentful-richtext) as I mentioned in the README

**Comment by janosh** [comment]
@Khaledgarbaya Sorry, I missed that. Regarding the features of `gatsby-transformer-contentful-richtext`, is it possible to render block and inline entries using React components?

**Comment by vlad-elagin** [comment]
For anyone who is struggling with this issue and tried above recipes with no luck: try to implicitly give a name to your types. My issue was solved with following
`
@ObjectType('user')
export class User {
`
