### ISSUE TITLE
utf 8,chinese markdown autolink is not workking in v2 

### ISSUE THREAD

**Issue by ethluz** [gatsbyjs/gatsby#9495]
** package.json :** "gatsby": "next"  is can work .
but  if  "gatsby": "2.0.0" is not workking

**Comment by kakadiadarpan** [comment]
@ethluz can you share more detailed information regarding this issue? Also, please provide relevant environment information by running `gatsby info --clipboard`.

**Comment by ethluz** [comment]
when my gatsby version is next or 1.0+ ，it is can work。
but  gatsby version is 2.0+ ，it is not work：
![](https://blockluz-1253389096.cos.ap-beijing.myqcloud.com/blockman/Jietu20181204-144130-HD.gif)

System:
    OS: macOS 10.14.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.4 - ~/.nvm/versions/node/v8.11.4/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.11.4/bin/npm
  Browsers:
    Chrome: 70.0.3538.110
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.61 => 2.0.61
    gatsby-plugin-layout: ^1.0.4 => 1.0.4
    gatsby-plugin-manifest: ^2.0.5 => 2.0.5
    gatsby-plugin-offline: ^2.0.5 => 2.0.7
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-plugin-sass: ^2.0.1 => 2.0.1
    gatsby-plugin-styled-components: ^1.0.5 => 1.0.5
    gatsby-remark-autolink-headers: ^1.4.7 => 1.4.19
    gatsby-remark-prismjs: ^1.2.8 => 1.2.24
    gatsby-source-filesystem: ^2.0.5 => 2.0.5
    gatsby-transformer-remark: ^2.1.9 => 2.1.9
  npmGlobalPackages:
    gatsby-cli: 2.4.6

**Comment by jonniebigodes** [comment]
@ethluz i did a bit of searchng and it looks like there's someone else with a related issue like you're experiencing. See this issue #10058 and if the workaround solves your issue, otherwise i would like for you to be a little more patient and wait and see if it's corrected.
