### ISSUE TITLE
Gatsby Starter Personal Blog - Search not showing search field

### ISSUE THREAD

**Issue by StarAzure** [gatsbyjs/gatsby#9512]
## Description

Starter page does not show any search field and does not load any results.

### Steps to reproduce

This same page when cloned on local shows the problem:
https://gatsby-starter-personal-blog.greglobinski.com/search/

### Expected result

Search form and results should display

### Actual result

No search form or results are displayed.

### Environment

  System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-6820HK CPU @ 2.70GHz
  Binaries:
    Node: 10.7.0 - D:\WORK\HTDOCS\NODE\node.EXE
    Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.1.0 - D:\WORK\HTDOCS\NODE\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^1.9.274 => 1.9.279
    gatsby-image: ^1.0.55 => 1.0.55
    gatsby-link: ^1.6.46 => 1.6.46
    gatsby-plugin-algolia: ^0.0.4 => 0.0.4
    gatsby-plugin-catch-links: ^1.0.24 => 1.0.26
    gatsby-plugin-feed: ^1.3.25 => 1.3.25
    gatsby-plugin-google-analytics: ^1.0.31 => 1.0.31
    gatsby-plugin-jss: ^1.5.14 => 1.5.14
    gatsby-plugin-manifest: ^1.0.27 => 1.0.27
    gatsby-plugin-netlify: ^1.0.21 => 1.0.21
    gatsby-plugin-offline: ^1.0.18 => 1.0.18
    gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11
    gatsby-plugin-react-next: ^1.0.11 => 1.0.11
    gatsby-plugin-react-svg: ^1.1.1 => 1.1.1
    gatsby-plugin-sharp: ^1.6.48 => 1.6.48
    gatsby-plugin-sitemap: ^1.2.25 => 1.2.25
    gatsby-remark-component: ^1.1.3 => 1.1.3
    gatsby-remark-copy-linked-files: ^1.5.37 => 1.5.37
    gatsby-remark-external-links: ^0.0.4 => 0.0.4
    gatsby-remark-images: ^1.5.67 => 1.5.67
    gatsby-remark-prismjs: ^2.0.5 => 2.0.5
    gatsby-remark-responsive-iframe: ^1.4.20 => 1.4.20
    gatsby-remark-smartypants: ^1.4.10 => 1.4.12
    gatsby-source-filesystem: ^1.5.39 => 1.5.39
    gatsby-transformer-remark: ^1.7.44 => 1.7.44
    gatsby-transformer-sharp: ^1.6.27 => 1.6.27

**Comment by kakadiadarpan** [comment]
@StarAzure did you follow all the steps listed in [Getting started](https://github.com/greglobinski/gatsby-starter-personal-blog#getting-started)?

**Comment by LekoArts** [comment]
Please open an issue in the appropriate repository:
https://github.com/greglobinski/gatsby-starter-personal-blog
