### ISSUE TITLE
Docs: Issues with links on recipes page

### ISSUE THREAD

**Issue by erikthered** [gatsbyjs/gatsby#9523]
## Description

On the [recipes page]() of the live docs, the "full docs" link in the top paragraph is using the url: https://www.gatsbyjs.org/docs/recipes/(/tutorial/). Additionally, the ToC seems be out of order, "Gatsby Project Structure" should be the second link but it's appearing at the end.

### Steps to reproduce

Visit the recipes page of the docs: https://www.gatsbyjs.org/docs/recipes

### Expected result

The "full docs" link should resolve to a valid page (not 100% sure if it should just be https://www.gatsbyjs.org/docs/ or another page. "Gatsby Project Structure" should be the second link in the ToC.

### Actual result

The "full docs" link resolves to a non-existent page: https://www.gatsbyjs.org/docs/recipes/(/tutorial/)

"Gatsby Project Structure" is the last link in the ToC.

### Environment

N/A

**Comment by rajasekarm** [comment]
I can pick this.

**Comment by oorestisime** [comment]
I am closing this since the PR was merged!
