### ISSUE TITLE
Passing Gatsby Image Query to a Component

### ISSUE THREAD

**Issue by jonathancary** [gatsbyjs/gatsby#9527]
I'm trying to use Gatsby Image where I query an image in a page component and it is passed to my Main Image component. The use case is having a unique image for each page as the hero image.

Nothing pops up in the terminal but in the console I get `Uncaught ReferenceError: props is not defined` however I'm unsure of how to fix this. Everything queries fine and works if I'm just using the image on that page but not when I'm trying to use it in the component.

This is what I have:

### File Structure
```
components
- mainImage.js
pages
- index.js
```

### index.js
```
import React from 'react'
import { Link, graphql } from 'gatsby'
import Img from 'gatsby-image'
import get from 'lodash/get'
import Helmet from 'react-helmet'

import Layout from '../components/layout'
import Main from '../components/mainImage'

class Design extends React.Component {
  render() {
    const siteTitle = get(this, 'props.data.site.siteMetadata.title')
    const siteDescription = get(
      this,
      'props.data.site.siteMetadata.description'
    )
    const posts = get(this, 'props.data.allMarkdownRemark.edges')

    return (
      <Layout location={this.props.location}>
        <Helmet
          htmlAttributes={{ lang: 'en' }}
          meta={[{ name: 'description', content: siteDescription }]}
          title={siteTitle}
        />
        <div className="site-body">
          <Main mainImage={this.props.data.mainImage} />
          <div className="grid grid-gutters">
            <div className="grid-cell u-med-2of3">
              <div className="">
                <h1>Design</h1>
              </div>
            </div>
          </div>
        </div>
      </Layout>
    )
  }
}

export default Design

export const pageQuery = graphql`
  query MainImageQuery {
    mainImage: file(relativePath: { eq: "design-bg.jpg" }) {
      childImageSharp {
        fluid(maxWidth: 1500) {
          ...GatsbyImageSharpFluid
        }
      }
    }
  }
`
```

### mainImage.js
```
import React from 'react'
import Img from 'gatsby-image'
import styles from './mainImage.module.css'

class MainImage extends React.Component {
  render() {
    return (
      <div className={styles.main}>
        <div className="grid grid-gutters">
          <div className="grid-cell u-small-hide">
          </div>
          <div className="grid-cell u-med-2of3">
            <Img fluid={props.mainImage.childImageSharp.fluid} />
            <p>Testing</p>
          </div>
        </div>
      </div>
    )
  }
}

export default MainImage
```

I'm new to Gatsby/React and have tried to figure this out a bunch of different ways, but haven't been able to. Was using the blog [Image Optimization Made Easy with Gatsby.js](https://medium.com/@kyle.robert.gill/ridiculously-easy-image-optimization-with-gatsby-js-59d48e15db6e), but it seems to be based on V1. Also, if you have a better solution for what I'm trying to accomplish please let me know. Thanks for the help!

**Comment by LekoArts** [comment]
## First part: Your error

> Uncaught ReferenceError: props is not defined

May sound like an obvious thing (no offense) but learn to understand the errors you get. It probably also gave you a filename/path or even the line number. So what's the error telling you? `props` is unknown to the component.

You use `props.mainImage.childImageSharp.fluid` in `mainImage.js`. Do you see the error comparing, e.g. with your index file? You're referencing `props`, not `this.props`.

## Second part: Your workflow

> The use case is having a unique image for each page as the hero image.

Do the pages have the same layout/structure and only the image and/or text is different? Then use page templates. If not you could define a GraphQL fragment in your component and use it in your page queries. Then you don't have to repeat the same query over and over.

**Comment by jonathancary** [comment]
Thanks for the help. Changing it to `this.props` worked. Figured it was something obvious, but was staring at it too long I guess.

The pages have different layouts/structure, but how the image is displayed is the same, so that's why I was opting for a component over page templates. And yes I was using a fragment, but removed it for the code above. Thanks for your input!
