### ISSUE TITLE
Provide better translations for documentation

### ISSUE THREAD

**Issue by jamezrin** [gatsbyjs/gatsby#9531]
## Summary
Provide better translations for the documentation available. As of now, only spanish is translated and only partly, and I'm pretty sure it has outdated information. 

In my opinion, it's better to not have translations that are incomplete and outdated. Also having only spanish is a bit strange.

I'm willing to translate everything (will take some time but I'll do it) to spanish, but I don't know if and where it is actually displayed (if displayed at all); but I think it should be translated to other languages as well.

If there are not going to be translations for other languages, or the current ones are not used; why don't we drop them?

**Comment by oorestisime** [comment]
i am willing to help translate in greek/french as well. probably there is the need to have docs hosted somewhere and have a source plugin pulling them or something similar? so that translations are always  up to date? 
i am willing to work on something like that (maybe start with a prototype) if docs team is willing. 
@gatsbyjs/docs

**Comment by LekoArts** [comment]
> As of now, only spanish is translated and only partly, and I'm pretty sure it has outdated information.

The "outdated" part is important. It always be outdated sooner or later.

> In my opinion, it's better to not have translations that are incomplete and outdated. Also having only spanish is a bit strange.

Since the Gatsby team rejected some translations PRs recently I feel certain that no further translations are wanted. Therefore the current spanish translations should be removed completely.

**Comment by jonniebigodes** [comment]
ok...thanks for the update @pieh . i was going to start working on some portuguese translations and reach out to aid in french translations, but after what you said gonna get me another cup of coffee and refresh the issues  thanks once again 🙏

**Comment by LekoArts** [comment]
Closing this issue as resolved then.
