### ISSUE TITLE
Is there a documented way to get full TypeScript support for Gatsby sites?

### ISSUE THREAD

**Issue by akoolenbourke** [gatsbyjs/gatsby#9536]
## Summary

Does anyone know if a documented way to get fully compiled and type-checked Typescript into a Gatsby site? As someone from C++ and new to JS I have to say that my experience with the latter is been less that comfortable, primarily due to the dynamic typing. I've lost count of the number of hours I've wasted tracking down type related defects.

So, I want to make things more sane but it seems the Gatsby plugin really just supports syntactic sugar. Anyone successfully done this?

Thanks

**Comment by pieh** [comment]
I don't have much context on typescript plugin :/ Did you check https://www.gatsbyjs.org/packages/gatsby-plugin-typescript docs about caveats and type checking? From what I understand plugin only really strips out ts features, so it's on users to use 3rd party tools to actually get benefits from using typescript (most likely using IDE support).

@resir014 Is that correct?

**Comment by resir014** [comment]
@pieh @akoolenbourke yes. `gatsby-plugin-typescript` utilises the TypeScript Babel preset, which only strips the type annotations without running a type check.

You will have to set up `tsc` to run typechecking separately. I can write some docs on getting started with TS if needed, but for now you can follow [my starter](https://github.com/resir014/gatsby-starter-typescript-plus) which includes the basics to get going w/ Gatsby + TS.

**Comment by akoolenbourke** [comment]
Thanks. Does that starter use real TS, as in, with compilation? If not, some docs would be wonderful

**Comment by resir014** [comment]
> Does that starter use real TS, as in, with compilation?

The starter uses the [TypeScript plugin](https://www.gatsbyjs.org/packages/gatsby-plugin-typescript/) which uses babel to compile the TS code. But I've included the `type-check` script to run the TS compiler separately in `--noEmit` mode, which you can run after making any changes.

Both the TS compiler and Babel shouldn't be that different though.

**Comment by akoolenbourke** [comment]
Thanks. Whilst my JS skills are growing, TS and how it all works together still needs a lot of work.

I had a play with the starter and I see that I get intellisense for TS which is great, but as expected it still compiles in gatsby and error's inside the browser if there's a problem. I saw script-check does the test which is great, so I wonder if there's a way to automatically run that as part of hotloading?

Cheers

**Comment by resir014** [comment]
> [...] would it be best to eventually get TS native, without Babel?

This *was* the behaviour on Gatsby v1 with Webpack, but with Gatsby 2 running on Babel 7, and TS transpiling being natively supported with it, we decided to use it to better integrate with our pipeline. If running `type-check` every time you save gets tedious, you can include it as a CI process (which I do on my own website).

I'm not sure how much you *really* need the TS compiler over Babel, but the v1 TS plugin might be a good starting point for anyone wanting to create a strictly-`tsc` Typescript plugin.

**Comment by jedrichards** [comment]
It helps to use an editor like VS Code, you can set it up to tightly integrate with your per-project local Typescript config. You'll get type problems listed out, red squiggles underneath code and of course intellisense. Whether it still "compiles" with Gatsby and runs in the browser with those problems seems useful to me. BUt naturally its up to your to do an automated full type check before you build/release etc.
