### ISSUE TITLE
[gatsby-source-filesystem] createRemoteFileNode: Keep original name

### ISSUE THREAD

**Issue by LekoArts** [gatsbyjs/gatsby#9539]
## Summary

Since this issue (https://github.com/gatsbyjs/gatsby/issues/6232) was fixed by @Sekhmet only one thing is left: Also keep the original file name in the downloaded image (as per old issue https://github.com/gatsbyjs/gatsby/issues/3132). Other requests: https://github.com/angeloashmore/gatsby-source-prismic/issues/40

@Sekhmet do you want to tackle that issue, too?

A result should be, e.g.:
- filepath: 
`/static/f28264fbe0c2cf6d02c3b8adc54b717b/18b00/e10dce13ec246d93bf6e57ede0d98ce8.jpg`
- new filepath: 
`/static/f28264fbe0c2cf6d02c3b8adc54b717b/18b00/e10dce13ec246d93bf6e57ede0d98ce8/this-is-the-super-name-here.jpg`

**Comment by hbish** [comment]
I'll have a go at this.

**Comment by jkjustjoshing** [comment]
What's the practicality of allowing the hash to be customizable too (or fully remove for non-duplicate filenames?)?

I'm moving a site over that has a bunch of PDFs on it. I'm using [gatsby-source-directus](https://www.gatsbyjs.org/packages/gatsby-source-directus/) to pull down the PDFs from my Directus server, which uses `createRemoteFileNode()` to add the files to Gatsby. 

Our current PDF urls look something like this - https://www.example.com/static/Financial_Disclosure_Form.pdf - and the users frequently will ⌘+S to save the PDFs. Right now, this causes the default filename to be the MD5 hash of the file, not `Financial_Disclosure_Form.pdf`. 

It looks like PR #9777 will make it so the filename is `79054025255fb1a26e4bc422aef54eb4-Financial_Disclosure_Form.pdf`, which is also not acceptable to me. Would it be possible to do one (or all) of the following?
1. Put the hash at the end - `Financial_Disclosure_Form-79054025255fb1a26e4bc422aef54eb4.pdf`
2. Allow for a shorter hash length (and throw an exception if there is a conflict) - `Financial_Disclosure_Form-79054.pdf`
3. Allow for no hash if there is no filename conflict (how easy will it be to detect filename conflicts vs one file requested twice?)
4. Allow for `createRemoteFileNode` to accept an optional callback that takes the name and the hash (and potentially a list of all other defined files, to avoid duplicates?) as the parameters and returns the filename to be used.

Do any of those ideas seam feasible?

**Comment by hbish** [comment]
Hey @jkjustjoshing 

I think what you've proposed for (1) is reasonable and makes total sense to have the filename first. 

With regards to (2) & (3), I think there are different use cases based on the source. For images, the filename may not mean as much compared to downloadable content like documents. So we could add an optional parameter to `createRemoteFileNode` toggle between hash and no hash and let plugin implementer choose. 

As to (4), I'm a little unclear by this one, could you please elaborate a bit more on what you mean a list of all other defined file? and maybe provide an example of what you envision?

Keen to hear what others think.

**Comment by pieh** [comment]
I think we could keep original filename and just put file in directory with hash.

@jkjustjoshing How are you referencing files when constructing download links - using query and `publicURL`?

**Comment by jkjustjoshing** [comment]
#4 would be a way to fully customize the filename while still avoiding collisions - if the callback is passed a list of all other files the plugin implementer could check for duplicates and ensure any potential collisions are avoided. 

I really like your suggestion @pieh, putting a file in a folder with the hash (potentially doing so only when a flag is passed to `createRemoteFileNode()`). I am referencing the files using query and `publicURL`, so any change will work for me. This fully solves my filename problem and the problem of potential collisions

Are there any performance implications for projects with a very large number of files to having 1 folder per file?

**Comment by hbish** [comment]
Sorry just got back from an overseas holiday, I've updated the PR so that files are stored in directories of the hash. e.g. `hash/filename.ext`. Original filename and extensions are maintained.

**Comment by jkjustjoshing** [comment]
Awesome! Thanks for your work on this!

**Comment by LekoArts** [comment]
Fixed with https://github.com/gatsbyjs/gatsby/pull/9777
