### ISSUE TITLE
Gatsby Limit?

### ISSUE THREAD

**Issue by ahansson89** [gatsbyjs/gatsby#9542]
I wonder what the limit for Gatsby is? I know I can make sites with 10,000 pages. But what if I have sites that have 1,000.000+ pages? Will Gatsby be able to handle that?

What limits have you guys hit with v2?

**Comment by luukdv** [comment]
Related: https://github.com/gatsbyjs/gatsby/issues/9362

**Comment by kakadiadarpan** [comment]
@ahansson89 The aim for Gatsby is to work for million page sites, but it’s not there yet. We have been working to make Gatsby great for larger scale sites. For that, we have been focusing on improving the performance and build times for large sites. Following are the PRs which have made a lot of difference:

#6226
#9370
#9338 (this is WIP, also focussed on larger site performance)

You can also take a look at the benchmark sites for testing bigger sites https://github.com/gatsbyjs/gatsby/tree/master/benchmarks

**Comment by pieh** [comment]
Page count limit is really fluid - it depends on how content heavy your site is and what is being used for your site. We have some benchmarks https://github.com/gatsbyjs/gatsby/tree/master/benchmarks/create-pages and https://github.com/gatsbyjs/gatsby/tree/master/benchmarks/markdown that stress test different parts of gatsby - but results of those benchmark won't be the same as for real production sites.

As @kakadiadarpan mentioned - there is continuous progress on optimizing bottlenecks that limit size of websites

**Comment by kmorf** [comment]
@pieh not sure if related to this thread but I noticed this:

Gatsby version | Queries/second
------------ | -------------
< 2.0.32 | 5 q/s
= 2.0.32 | 10 q/s
2.0.32 | 2.5 q/s

(without changing queries/content/etc..) 

<details><summary>gatsby info</summary>
<p>

```
System:
  OS: macOS 10.14
  CPU: x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
  Shell: 5.3 - /bin/zsh
Binaries:
  Node: 11.0.0 - /usr/local/bin/node
  npm: 6.4.1 - /usr/local/bin/npm
Browsers:
  Chrome: 70.0.3538.77
  Firefox: 63.0
npmPackages:
  gatsby: ^2.0.34 => 2.0.34 
  gatsby-image: ^2.0.18 => 2.0.18 
  gatsby-plugin-canonical-urls: ^2.0.7 => 2.0.7 
  gatsby-plugin-create-client-paths: ^2.0.2 => 2.0.2 
  gatsby-plugin-feed: ^2.0.9 => 2.0.9 
  gatsby-plugin-gtag: ^1.0.4 => 1.0.4 
  gatsby-plugin-lunr: ^1.2.0 => 1.2.0 
  gatsby-plugin-manifest: ^2.0.7 => 2.0.7 
  gatsby-plugin-netlify: ^2.0.3 => 2.0.3 
  gatsby-plugin-netlify-cache: ^1.0.0 => 1.0.0 
  gatsby-plugin-netlify-cms: ^3.0.5 => 3.0.5 
  gatsby-plugin-offline: ^2.0.10 => 2.0.10 
  gatsby-plugin-react-helmet: ^3.0.1 => 3.0.1 
  gatsby-plugin-robots-txt: ^1.3.0 => 1.3.0 
  gatsby-plugin-sharp: ^2.0.10 => 2.0.10 
  gatsby-plugin-sitemap: ^2.0.2 => 2.0.2 
  gatsby-plugin-styled-components: ^3.0.1 => 3.0.1 
  gatsby-remark-images: ^2.0.5 => 2.0.5 
  gatsby-source-filesystem: ^2.0.6 => 2.0.6 
  gatsby-transformer-remark: ^2.1.11 => 2.1.11 
  gatsby-transformer-sharp: ^2.1.7 => 2.1.7 
npmGlobalPackages:
  gatsby-cli: 2.4.4
```

</p>
</details>

**Comment by ahansson89** [comment]
> Page count limit is really fluid - it depends on how content heavy your site is and what is being used for your site. We have some benchmarks https://github.com/gatsbyjs/gatsby/tree/master/benchmarks/create-pages and https://github.com/gatsbyjs/gatsby/tree/master/benchmarks/markdown that stress test different parts of gatsby - but results of those benchmark won't be the same as for real production sites.
> 
> As @kakadiadarpan mentioned - there is continuous progress on optimizing bottlenecks that limit size of websites

Of course. Let's say it's a news/blog type of sites with blog posts 800 words on average, just to define a standard for the discussion. 

Will I be able to deploy a 1,000,000+ pages site with Gatsby as of right now? If not, where are the bottlenecks?
