### ISSUE TITLE
TypeError: Cannot read property 'internal' of null

### ISSUE THREAD

**Issue by JanLenoch** [gatsbyjs/gatsby#9560]
## Summary

When a Kentico Cloud Gatsby starter is connected to a Kentico Cloud official reference content project, the above error message appears after the "source and transform nodes" build step was successfully finished.

Debugging revealed neither any malformed input data nor any hints. The question is therefore: What might have caused this issue?

## Relevant information

Up until now, we've been developing both our source plugin and our starter with a simple content project that has the least amount of data to showcase the capabilities of Kentico Cloud and Gatsby. The project data can be accessed via our Delivery API at https://deliver.kenticocloud.com/5ac93d1e-567d-01e6-e3b7-ac435f77b907/items .

The next step was to test the plugin with a bare-bone Gatsby site and the Kentico Cloud reference content project at https://deliver.kenticocloud.com/c461ba35-fd9d-000f-17ed-2054c3a4cbf1/items .

During each build, the above error message appears, very similar to the one of #8345. The full stack trace is:

   TypeError: Cannot read property 'internal' of null

  - infer-graphql-input-fields.js:344 _.each
    [gatsby-starter-kentico-cloud]/[gatsby]/dist/schema/infer-graphql-input-fields.js:344:38

  - lodash.js:4911
    [gatsby-starter-kentico-cloud]/[lodash]/lodash.js:4911:15

  - lodash.js:2996 baseForOwn
    [gatsby-starter-kentico-cloud]/[lodash]/lodash.js:2996:24

  - lodash.js:4880
    [gatsby-starter-kentico-cloud]/[lodash]/lodash.js:4880:18

  - lodash.js:9344 Function.forEach
    [gatsby-starter-kentico-cloud]/[lodash]/lodash.js:9344:14

  - infer-graphql-input-fields.js:332 inferInputObjectStructureFromNodes
    [gatsby-starter-kentico-cloud]/[gatsby]/dist/schema/infer-graphql-input-fields.js:332:5

  - build-node-types.js:186
    [gatsby-starter-kentico-cloud]/[gatsby]/dist/schema/build-node-types.js:186:36

  - Generator.next

  - next_tick.js:132 _combinedTickCallback
    internal/process/next_tick.js:132:7

  - next_tick.js:181 process._tickCallback
    internal/process/next_tick.js:181:9

error UNHANDLED REJECTION

  TypeError: Cannot read property 'internal' of null

  - infer-graphql-input-fields.js:344 _.each
    [gatsby-starter-kentico-cloud]/[gatsby]/dist/schema/infer-graphql-input-fields.js:344:38

  - lodash.js:4911
    [gatsby-starter-kentico-cloud]/[lodash]/lodash.js:4911:15

  - lodash.js:2996 baseForOwn
    [gatsby-starter-kentico-cloud]/[lodash]/lodash.js:2996:24

  - lodash.js:4880
    [gatsby-starter-kentico-cloud]/[lodash]/lodash.js:4880:18

  - lodash.js:9344 Function.forEach
    [gatsby-starter-kentico-cloud]/[lodash]/lodash.js:9344:14

  - infer-graphql-input-fields.js:332 inferInputObjectStructureFromNodes
    [gatsby-starter-kentico-cloud]/[gatsby]/dist/schema/infer-graphql-input-fields.js:332:5

  - build-node-types.js:186
    [gatsby-starter-kentico-cloud]/[gatsby]/dist/schema/build-node-types.js:186:36

  - Generator.next

  - next_tick.js:132 _combinedTickCallback
    internal/process/next_tick.js:132:7

  - next_tick.js:181 process._tickCallback
    internal/process/next_tick.js:181:9

### Repro steps

1) Clone https://github.com/Kentico/gatsby-starter-kentico-cloud/tree/dancing-goat-troubleshooting and run `gatsby develop`.

### Remarks

When diagnosing, I noticed that the issue does not appear when I fetch only content items of type `about_us`. With other types, it fails. You can repro this by replacing both occurrences of `.items()` with `.items().type('about_us')` in plugin's [gatsby-node.js](https://github.com/Kentico/gatsby-source-kentico-cloud/blob/v2.0.0-beta2/src/gatsby-node.js). What is really interesting is that when that `about_us` filtering is applied, the `about_us` item is still retrieved with its three child `fact_about_us` linked items (and the build still goes fine, even with the three child nodes being sent to `createNode`). But, when you apply the `.items().type('fact_about_us')` filtering, the build fails.

My suspicion is that the issue might be related to the way we [deal with circular references](https://github.com/Kentico/gatsby-source-kentico-cloud/blob/master/src/normalize.js#L247) in the node's `internal` -> `content` property. Might that be the case?

### Environment (if relevant)

  System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  Binaries:
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.0.22 => 2.0.22
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-source-kentico-cloud: ^2.0.0-beta1 => 2.0.0-beta2

error The system cannot find the path specified.

  Error: The system cannot find the path specified.

  - envinfo.js:1 Function.e.exports.sync
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:7778

  - envinfo.js:1 Object.copySync
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:104976

  - envinfo.js:1 Object.t.writeSync.e [as writeSync]
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:123499

  - envinfo.js:1
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:124274

  - envinfo.js:1 Promise.all.then.e
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:124289

  - util.js:16 tryCatcher
    [npm]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:693 Promise._settlePromises
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:693:18

  - promise.js:638 Promise._fulfill
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:693 Promise._settlePromises
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:693:18

error UNHANDLED REJECTION

  Error: The system cannot find the path specified.

  - envinfo.js:1 Function.e.exports.sync
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:7778

  - envinfo.js:1 Object.copySync
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:104976

  - envinfo.js:1 Object.t.writeSync.e [as writeSync]
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:123499

  - envinfo.js:1
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:124274

  - envinfo.js:1 Promise.all.then.e
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:124289

  - util.js:16 tryCatcher
    [npm]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:693 Promise._settlePromises
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:693:18

  - promise.js:638 Promise._fulfill
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:693 Promise._settlePromises
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:693:18

### File contents (if changed)

[gatsby-config.js](https://github.com/Kentico/gatsby-starter-kentico-cloud/blob/dancing-goat-troubleshooting/gatsby-config.js)
[package.json](https://github.com/Kentico/gatsby-starter-kentico-cloud/blob/dancing-goat-troubleshooting/package.json)
[gatsby-node.js](https://github.com/Kentico/gatsby-starter-kentico-cloud/blob/dancing-goat-troubleshooting/gatsby-node.js)

**Comment by pieh** [comment]
I will be looking more in depth, but just quick note - please update to `gatsby@2.0.35` - it will not fix the issue, but it should provide more meaningful error message. (we recently published changes from this PR https://github.com/gatsbyjs/gatsby/pull/9487 )

**Comment by pieh** [comment]
Ah it seems we have another problem with arrays, so updating won't help much - but this would be actual problem:
`Encountered an error trying to infer a GraphQL type for: "elements.facts_nodes___NODE". There is no corresponding node with the id field matching: "a7f67024-52bc-55c3-9b5d-87d39a52555a"`

there is `___NODE` link that links to non-existing node

**Comment by pieh** [comment]
> My suspicion is that the issue might be related to the way we [deal with circular references](https://github.com/Kentico/gatsby-source-kentico-cloud/blob/master/src/normalize.js#L247) in the node's `internal` -> `content` property. Might that be the case?

Finally got to root cause and yes - there is circular reference somewhere that is causing `createNode` to throw error and not actually create node. I will keep digging

**Comment by pieh** [comment]
In here https://github.com/Kentico/gatsby-source-kentico-cloud/blob/v2.0.0-beta2/src/normalize.js#L69 you are creating circular references. Instead of inserting object you would need to use `___NODE` to reference other node.

When gatsby tries to traverse node object it will keep getting looped and either react callstack maximum or eventually go out of memory - here's example of gatsby trying to examine object like that:
![screen shot 2018-10-31 at 16 39 27](https://user-images.githubusercontent.com/419821/47806108-382abf00-dd39-11e8-98bb-8f54eacee52b.png)

**Comment by JanLenoch** [comment]
Hi @pieh ,

Thanks for digging into the root cause! It is now much easier for me to fight the error.

**Comment by JanLenoch** [comment]
Thanks @pieh again for help. I've handled it in an [aggregated PR](https://github.com/Kentico/gatsby-source-kentico-cloud/pull/26).

**Comment by mathieucaroff** [comment]
With Gatsby 2.5.12, I get the below error each time I run `yarn develop` without deleting `.cache`.

```
mc@WSLinux/1 17h58 /mnt/c/dg/dam b$ yarn develop
yarn run v1.15.2
$ gatsby develop
success open and validate gatsby-configs — 0.011 s
success load plugins — 1.971 s
success onPreInit — 0.012 s
success initialize cache — 0.095 s
success copy gatsby files — 0.178 s
success onPreBootstrap — 0.020 s

success source and transform nodes — 2.364 s
error UNHANDLED REJECTION


  TypeError: Cannot read property 'internal' of undefined

  - schema.js:658 _.flatMap.groupBy.node
    [dam]/[gatsby]/dist/schema/schema.js:658:102

  - lodash.js:497 arrayAggregator
    [dam]/[lodash]/lodash.js:497:34

  - lodash.js:4829 Function.groupBy
    [dam]/[lodash]/lodash.js:4829:16

  - lodash.js:4374 
    [dam]/[lodash]/lodash.js:4374:28

  - lodash.js:683 arrayReduce
    [dam]/[lodash]/lodash.js:683:21

  - lodash.js:4373 baseWrapperValue
    [dam]/[lodash]/lodash.js:4373:14

  - lodash.js:9052 LodashWrapper.wrapperValue
    [dam]/[lodash]/lodash.js:9052:14

  - schema.js:658 groupChildNodesByType
    [dam]/[gatsby]/dist/schema/schema.js:658:145

  - schema.js:591 addConvenienceChildrenFields
    [dam]/[gatsby]/dist/schema/schema.js:591:28

  - schema.js:193 
    [dam]/[gatsby]/dist/schema/schema.js:193:13

  - Generator.next

error Command failed with exit code 1.
```

It's not a real bother, I just have to use `rm -r .cache; yarn develop` instead. Given how one my transformer plugin works, I wouldn't be surprised that this is caused by a circular reference among Gatsby nodes. What's weird is that the problem only occur es when the cache already exists.

If it keeps bothering me, I may open a proper issue, but given the project's current situation, this is rather unlikely.
