### ISSUE TITLE
Is there a reason why gatsby-source-contentful uses content type Names in graphql instead of IDs?

### ISSUE THREAD

**Issue by aofolts** [gatsbyjs/gatsby#9568]
For example, if I have a content type called `seo`, I would expect the resulting graphql type to be `ContentfulSeo`.

Instead, the `Name` is used. "SEO (Search Engine Optimization)" becomes `ContentfulSeoSearchEngineOptimization`. This doesn't make sense to me because Names can change and they are often more verbose, as they might provide additional information for editors.

Why aren't content type names used?

__EDIT__

I see this issue was already raised once [here](https://github.com/gatsbyjs/gatsby/issues/6169). It really needs to be changed because Names are superficial in Contentful and they should not be used as identifiers.

**Comment by nayres** [comment]
Hello aofolts! If I understand your concern correctly, you are hoping to use the ```content model```'s naming convention instead of the 'customer facing' naming conventions in the ```entry``` space. 

While the ```name``` is customer facing within Contentful, it is still a value in the underlying JSON. Not using the ```name``` in your specific case may seem more logical, but in the case where you will use a ```content type``` for multiple ```entries```, it creates a more logical JSON structure.

Being that there are infinite ways to model your Contentful data, each circumstance may be different from another. Seeing an example of how you modeled your data would be helpful in order for me to avoid making assumptions.

**Comment by aofolts** [comment]
Hey @nayres! If you don't mind could you give an example of why using the `Name` instead of the `Content ID` would create a more logic structure for content types that are used for multiple entries?

**Comment by nayres** [comment]
@aofolts, do to Contentful’s flexibility there are different ways to set up the data that will be communicated to the API. Typically the best practices depend on your specific need. In my typical need, let’s say for an Ecommerce site; I will try to organize my data in a way that is reusable across the site. 

In the case that I want to shape my data to display a business’s address, I would create a content type that would call for a single entry. BUT, In the case that I create an employee bio page that provides information for a specific employee, I would create a content type that would service each of those pages. 

allContentfulEmployeeBio {
    title
    name
    image {
        file {
            url
        }
    copy
}

If I were to create a content type per employee, I would be repeating the same shape let’s say 10 times

**Comment by aofolts** [comment]
@nayres Maybe I'm being really dense, but I don't see what that has to do with gatsby-source-contentful using the `content type Name` instead of the `content type ID` in graphql.

I understand the concept of reusable content types.

For example, I reference the content type `seo` (named "SEO Search Engine Optimization) in my `page` and `blogPost` content types.

But to clarify, what I'm asking is why a `graphql Type` of **ContentfulSeoSearchEngineOptimization** is created and not **ContentfulSeo**.

It seems to me that the purpose of the `content type Name` is to provide editors with a title that makes sense to them—which may occasionally be longer and more descriptive.

The `content type ID` is meant to stay consistent, and be meaningful to developers, which is why it seems like a better choice to generate the `graphql Type`.

Is it clear, what I'm asking? Thanks for bearing with me!

**Comment by aofolts** [comment]
@Khaledgarbaya Got it. Weird that they have that option—I can't picture a scenario where I would want a random content type ID instead of a custom one. Thanks for the explanation!

**Comment by silviopaganini** [comment]
Hi there

Just to way in in this conversation @Khaledgarbaya you have a fair point about the readable IDs, but at the same time, makes the whole system a bit fragile when you have the CMS on an enterprise level changing names according to their needs (naming convention, translation, etc etc)... any chance of this being re-opened and discussed?

**Comment by olapersson** [comment]
+1 on reopening this. It's surprising behavior depending on a mutable value for structure. Builds start breaking suddenly when changing a display value, I've noticed it before and just got bitten by it when a client changed names of a few content types to make more sense to them.

It also differs from how individual fields behave.

Seems to me that defining an id in case you're working with the API would be a better compromise, if this is common maybe add an alias configuration option to the plugin?

**Comment by aleksitaipale** [comment]
+1 from me also. 

> when a client changed names of a few content types to make more sense to them.

I have to agree with @olapersson and others above, relying on names seems quite fragile. Needing to do a find-and-replace every time the name of a field is changed does not seem very sustainable, especially if the client is able to change the names (which in many cases they should, imo, to make the site fit their mental model).

Besides, in situations where the client site is not in English, defining content types in the site's language would make more sense to me. Nevertheless, I'd want to keep my code in English. So if it's possible to add this as an option at least in the plugin config, that would be great. People programmatically generating base64 ids could then decide if they want to continue with the Names :)

**Comment by peabnuts123** [comment]
I would like this change to be considered. This is almost un-maintainably fragile and not a good separation of concerns. As stated before this thread, the user-facing name is not fit-for-purpose as an identifier, and may be subject to any level of change e.g. we tweak the name of content types for UX purposes and this causes several knock-on effects in the code:

  1. GraphQL queries need to be rewritten
  1. All code referencing that field needs to be rewritten
  1. References to TypeScript definitions generated from the GraphQL queries need to be rewritten

This means a display name tweak in Contentful could result in hours of refactoring, bugs/crashes landing in production, or worse - somebody changing a name in Contentful without realising they have to follow this process (it is, after all, a human process that "must be followed"). 

I think a change needs to be considered here. I understand the motivation outlined above - that the Content Type ID might not be a natural language string, but IMO that is a better problem to have on average than this one. Only a subset of users would be affected by unfriendly IDs, but right now _everybody_ is affected by this fragility. 

If a change is to be made, backwards compatibility will need to be considered, as we can't push out a change that requires everybody to rewrite all of their GraphQL queries. I suggest we introduce a config flag for `gatsby-source-contentful` to opt into using the content type IDs as the field name. Eventually this could become the default (and the flag changed to an opt _out_). This would also allow for people whose processes are resulting in lots of machine-defined base62 IDs to opt to use field name instead.

I'm only somewhat familiar with the code but I believe I have seen where this field name generation occurs, and it might not be a big change to introduce this option. If anybody is keen, I could try to put together a PR together for a change like this?

**Comment by aofolts** [comment]
@peabnuts123 Config flag sounds perfectly reasonable to me. 👍

**Comment by peabnuts123** [comment]
I've created a PR for the change described above in #20265
