### ISSUE TITLE
Regression in the Guess.js plugin for Gatsby

### ISSUE THREAD

**Issue by mgechev** [gatsbyjs/gatsby#9572]
## Description

Currently, the Guess.js plugin for Gatsby does not prefetch the resources associated with the pages. It only invokes `getResourcesForPathname` but does not perform any actions.

It looks like the regression was introduced by [this PR](https://github.com/gatsbyjs/gatsby/commit/2605aa0ec74a79fa56bc0eae8d101356c25c38de#diff-79243c75f482266054a48c78b300dc5b).

Downgrading the Guess.js plugin to 1.0.0 resolves the issue.

### Steps to reproduce

Install the Guess.js plugin version 1.0.2 and introduce the plugin in `gatsby-config.js`.

### Expected result

The plugin should prefetch assets associated with pages predicted from Guess.js

### Environment

Gatsby version 2.0.31
Guess.js plugin version 1.0.2

**Comment by kakadiadarpan** [comment]
@mgechev can you provide a reproduction repo for this?

**Comment by mgechev** [comment]
You can reproduce the issue by unpinning the plugin version in this project https://github.com/guess-js/guess-js.github.io. Alternatively, you can introduce the latest version of the Guess.js plugin to Gatsby.com and you should get the same behavior.
