### ISSUE TITLE
no-cache=1 being added to all createPages on Netlify

### ISSUE THREAD

**Issue by shansmith01** [gatsbyjs/gatsby#9575]
After a recent update, all of my pages which have been made using createPages have no-cache=1 added to the URLs when navigating to a page from another. This is only happening in a production environment on Netlify and does not happen on my local install. 

_Possible symptom of same issue_
I am also unable to get forms working with netlify using forms which are working on a gatsby v1 install. I also notice for a second that when a form is submitted, I will briefly see a 404 page page before seeing a success page (but the form never makes it to netlify)

So all up it's seems there may be some funk cache stuff going on.

Thanks for the help

Related files:
Repo - https://github.com/shansmith01/basebackpackers

### Steps to reproduce

- Go here https://beta.stayatbase.com/hostels/ and then try to navigate to a sub page. Note the URL.
- Navigating directly to to a url will not at no-cache e.g https://beta.stayatbase.com/hostels/base-backpackers-sydney
- Additionally submitting a form will show the brief 404

### Expected result

I should see a url without no-cache

### Actual result

I see a url with no-cache=1

### Environment

  System:
    OS: macOS 10.14
    CPU: x64 Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 62.0
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.34 => 2.0.34
    gatsby-image: ^2.0.18 => 2.0.18
    gatsby-plugin-eslint: ^1.0.3 => 1.0.3
    gatsby-plugin-google-tagmanager: ^2.0.6 => 2.0.6
    gatsby-plugin-manifest: ^2.0.7 => 2.0.7
    gatsby-plugin-netlify: ^2.0.3 => 2.0.3
    gatsby-plugin-offline: ^2.0.10 => 2.0.10
    gatsby-plugin-react-helmet: ^3.0.1 => 3.0.1
    gatsby-plugin-react-svg: ^2.0.0 => 2.0.0
    gatsby-plugin-sentry: ^0.1.0 => 0.1.0
    gatsby-plugin-sharp: ^2.0.10 => 2.0.10
    gatsby-plugin-sitemap: ^2.0.2 => 2.0.2
    gatsby-plugin-styled-components: ^3.0.1 => 3.0.1
    gatsby-plugin-twitter: ^2.0.7 => 2.0.7
    gatsby-source-datocms: ^2.0.0 => 2.0.0
    gatsby-source-filesystem: ^2.0.6 => 2.0.6
    gatsby-transformer-remark: ^2.1.11 => 2.1.11
    gatsby-transformer-sharp: ^2.1.7 => 2.1.7
  npmGlobalPackages:
    gatsby-cli: 2.4.4

**Comment by DSchau** [comment]
You have an extra space in `src/pages/hostels.js` :)

I've [PRed the fix here](https://github.com/shansmith01/basebackpackers/pull/19) so closing this out!

Thanks for using Gatsby 💪 Site looks great!

**Comment by DSchau** [comment]
Oh whoops, and got a little hasty on closing out! Didn't catch the second part of your question:

> I am also unable to get forms working with netlify using forms which are working on a gatsby v1 install. I also notice for a second that when a form is submitted, I will briefly see a 404 page page before seeing a success page (but the form never makes it to netlify)

We'd need more detail on this one, so maybe open a separate issue? It could be related to #7997

**Comment by shansmith01** [comment]
Thanks for the help!. Was racking my brain on that simple issue for ages!

**Comment by shansmith01** [comment]
@DSchau Yeah I will open a sperate issue if the fix for  #7997 does not solve. Thanks again
