### ISSUE TITLE
Netlify /admin redirect broken

### ISSUE THREAD

**Issue by zslabs** [gatsbyjs/gatsby#9584]
## Description

`3.0.5` (or more specifically https://github.com/gatsbyjs/gatsby/pull/9269) introduced a redirect for `/admin` that is breaking production Netlify environments. Our page was showing `Too many redirects` until I downgraded to `3.0.4`

### Steps to reproduce

☝️ 

### Expected result

Admin should load using `config.yml`

### Actual result

`Too many redirects` browser error.

**Comment by zslabs** [comment]
@c0b41 Unfortunately it’s a private repo. Could this have something to do with netlify’s pretty url options? https://www.netlify.com/docs/redirects/

I think the redirect might be a bit too descriptive for the options available over there, but let me know if I can help clarify at all. Thanks!

**Comment by erquhart** [comment]
Issues like this are the reason we never attempted to force a trailing slash from the CMS itself, we can't know what's going on outside. Netlify redirects is only one example of a potential redirect conflict.

I've generally found the redirect to only be necessary in local development, never in production. @c0b41 can you confirm whether this has been a production requirement for you? If not maybe we can roll out a fix specifically for the dev environment (although it still may cause unexpected issues).

**Comment by pieh** [comment]
Change was reverted and `gatsby-plugin-netlify-cms@3.0.6` was published - please update and if it fixes the problem closes the issue or let us know if there is still problem
