### ISSUE TITLE
Question: Replace JS loader with TS loader for TypeScript

### ISSUE THREAD

**Issue by berwyn** [gatsbyjs/gatsby#9585]
## Summary
In the TypeScript plugin, the Webpack config [uses the JavaScript loader](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-typescript/src/gatsby-node.js#L9-L26) to parse TypeScript files. Wouldn't it make more sense to use [ts-loader](https://github.com/TypeStrong/ts-loader) and therefore leverage `tsc`'s typechecking and plugin framework? Is there a particular reason the JS loader was re-used for this config?

## Relevant information

If we look at the [caveats](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-typescript#caveats) for the plugin, we see that leveraging TypeScript's features with Gatsby is entirely dependent on the IDE the developer is using. This really seems like it's invalidating the usefulness of TypeScript's compiler.

It seems really odd to me that my site has a compile phase, but I can't leverage TypeScript's biggest feature :/

**Comment by wgolledge** [comment]
Is this still relevant? I'm currently thinking of a possible way to block the code compiling/transpiling if there are `type-check` errors. 

It would be useful to have an option to select which loader we would like to use.
