### ISSUE TITLE
Add Princeton Asian Art Museum to showcase

### ISSUE THREAD

**Issue by calcsam** [gatsbyjs/gatsby#9586]
Beautiful site: http://artmuseum.princeton.edu/asian-art/

**Comment by calpa** [comment]
Thank you, but just some question to verify this is using GatsbyJS.
@calcsam where is the source code? Is that an open source project?

**Comment by calcsam** [comment]
Ctrl-F through "View Source" and you'll see "___gatsby"

**Comment by pieh** [comment]
You can also use https://chrome.google.com/webstore/detail/is-gatsby/jgaejkhmgkpagdmapahohjennkhbpgfj (there is also firefox version of it), that will highlight little gatsby icon in your extension icon list
