### ISSUE TITLE
[1.0] File type inference is too fragile

### ISSUE THREAD

**Issue by 0x80** [gatsbyjs/gatsby#959]
This was already discussed in #950 with a possible [solution]( https://github.com/gatsbyjs/gatsby/issues/950#issuecomment-300607873), but I'm creating a separate issue because it's easier to track.

Any string in json data that looks like it might be a file, gets turned into a graphql `File` type. My CMS has content like this.

```javascript
{ 
   toolTags: [{
        name: 'some tag',
        description: 'what is it'
   }]
}
```
I filled in `node.js` and  💥 all of sudden name becomes a File and all queries break. You get an error like `UNHANDLED REJECTION Error: You supplied a GraphQL document with validation errors:
Field "name" of type "File" must have a selection of subfields. Did you mean "name { ... }"?` which only gives you the hint of a `name` field, which might be quite common, and you sift through the data trying to figure out where there is a value that might have caused this. Luckily my dataset is not huge and the memory of this error was still fresh from #950, but this clearly makes importing data very fragile.

**Comment by KyleAMathews** [comment]
I think the way to fix this is to just check that what looks like a relative file link points to actual files. So check that the node has an ancestor that's of type File and then using that File + the field, creates a path to another known File node.

**Comment by 0x80** [comment]
@KyleAMathews If I remember correctly this has been solved in a recent PR.

I can now use `node.js` as a tag without it being interpreted as a file.

**Comment by KyleAMathews** [comment]
Oh it was, thanks for closing. Yeah, I implemented the algorithm I described above. Glad to hear its working!
