### ISSUE TITLE
gatsby.org starter website template has weird css on it's share button

### ISSUE THREAD

**Issue by tanvibhakta** [gatsbyjs/gatsby#9591]
## Description

The share button on top of every starter should be algned with the rest of the buttons, and the drop-down should go away on clicking outside the drop-down area. 

### Steps to reproduce

Visit [any](https://www.gatsbyjs.org/starters/gatsby-starter-default-i18n) website starter pack url, and click the yellow share button on the right, above the website screenshot. 

### Expected result
1. The share button's style should align with the 'View demo' button.
2. The drop down should close if you click outside the drop down area.

### Actual result

The share button is not aligned.
The drop down only goes away if you click the share button again.

### Environment

Production. This behavior is visible on the website.

**Comment by dyllper** [comment]
Mind if I take a look at this?

**Comment by RedHoodJT1988** [comment]
Has this been fixed? If not I would like to take it on.

**Comment by fk** [comment]
@RedHoodJT1988 Yes, there's a PR for this #9620 that needs review.

**Comment by fk** [comment]
Fixed via #9620, thanks everybody! 🙏 🤗
