### ISSUE TITLE
gatsby.org starter-pack sidebar doesn't have a scroll bar (in Firefox)

### ISSUE THREAD

**Issue by tanvibhakta** [gatsbyjs/gatsby#9592]
## Description

The starter pack website, once filtered, doesn't have a scroll bar to allow me to scroll though the filters. This means that only after I reach the bottom of the main content does the sidebar content scroll. 

### Steps to reproduce

Go to [this link](https://www.gatsbyjs.org/starters?c=i18n) and scroll on the sidebar. 

### Expected result

When my cursor is above the sidebar, and I turn the wheel on my mouse the sidebar should scroll. Alternatively, I should be shown a scrollbar so I can drag my mouse to where i want it to be.

### Actual result

There is no scrollbar in the sidebar. When it is active and I am scrolling, the bottom of the content is reached before the sidebar starts scrolling.

### Environment

I looked at the website on a Macbook Pro on Chrome and Firefox, this bug is only present on all Firefox browsers (Regular, dev edition, nightly)

**Comment by hasparus** [comment]
Hi. I think I can do this pretty quickly.
Is this the expected result? https://vimeo.com/user91213058/review/298112464/dd3e01bc01

**Comment by iamnishantmishra** [comment]
@hasparus it looks good! Have you tested it on Firefox browser?

**Comment by hasparus** [comment]
Yup, that's Firefox on the video.

**Comment by iamnishantmishra** [comment]
Then go ahead create a PR!

**Comment by psnaik** [comment]
Ok

**Comment by fk** [comment]
Ay no — poor Firefox users. :/
Thanks so much for catching this, @tanvibhakta!
