### ISSUE TITLE
Image as link has horizontal line in background

### ISSUE THREAD

**Issue by ygd** [gatsbyjs/gatsby#9593]
## Description

The authors image in a blogpost is a link. It inherits link tag stylings which draws a border in the background. 

### Steps to reproduce

Open a [blogpost](https://www.gatsbyjs.org/blog/2018-10-16-why-mobile-performance-is-crucial/) and hover over the authors image.

This is how it looks.
<img width="146" alt="bildschirmfoto 2018-10-31 um 08 45 28" src="https://user-images.githubusercontent.com/1052456/47773291-e27af600-dce9-11e8-848d-c28b1cad022e.png">

### Expected result

No borders in background for images in link tags.

### Actual result

Border in background.

### Environment

production.

**Comment by aravindballa** [comment]
Can I grab this?
