### ISSUE TITLE
Only home page (path: "/") has html in the build

### ISSUE THREAD

**Issue by hackhat** [gatsbyjs/gatsby#9594]
All my pages have empty content: `<body><div id="___gatsby"><div style="outline:none" tabindex="-1" role="group"></div></div>...`

Only my homepage has the content. Do you know why is happening?

### Environment

System:
OS: Windows 10
CPU: x64 Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
Binaries:
Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
npm: 5.5.1 - C:\Program Files\nodejs\npm.CMD
Browsers:
Edge: 42.17134.1.0
npmPackages:
gatsby: ^2.0.19 => 2.0.21
gatsby-image: ^2.0.17 => 2.0.17
gatsby-plugin-catch-links: ^2.0.4 => 2.0.4
gatsby-plugin-emotion: ^2.0.5 => 2.0.5
gatsby-plugin-google-analytics: ^2.0.6 => 2.0.6
gatsby-plugin-manifest: ^2.0.6 => 2.0.6
gatsby-plugin-offline: ^2.0.5 => 2.0.6
gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
gatsby-plugin-sharp: ^2.0.8 => 2.0.8
gatsby-plugin-sitemap: ^2.0.1 => 2.0.1
gatsby-plugin-typescript: ^2.0.0 => 2.0.0
gatsby-plugin-typography: ^2.2.0 => 2.2.0
gatsby-remark-images: ^2.0.4 => 2.0.4
gatsby-source-filesystem: ^2.0.3 => 2.0.3
gatsby-transformer-remark: ^2.1.7 => 2.1.7
gatsby-transformer-sharp: ^2.1.5 => 2.1.5

**Comment by kakadiadarpan** [comment]
@hackhat can you share more information regarding this issue?
- Did this issue start coming after you added a certain plugin?
- All the HTML files(in build) have empty content, what happens when you serve the site? Does anything gets rendered there?

**Comment by hackhat** [comment]
@kakadiadarpan when I serve, it will take the empty html and build the html at runtime with react.

> Did this issue start coming after you added a certain plugin?

I didn't notice

**Comment by hackhat** [comment]
Oh just noticed is actually working, but takes a bit to figure out. I basically can't trust my browser anymore at this point for what is the source of the page :)

Steps:

 - Load first page
 - Go to the 2nd page
 - ctrl+u: you will see an empty HTML
 - ok, refresh the page
 - ctrl+u: still see empty HTML

Now go to incognito to the 2nd page directly:

 - ctrl+u
 - you will see the HTML there
