### ISSUE TITLE
Troubles adding tags to the blog

### ISSUE THREAD

**Issue by d-ivashchuk** [gatsbyjs/gatsby#9607]
## Summary
I am trying to add tags to my blog as in the following [tutorial](https://www.gatsbyjs.org/docs/adding-tags-and-categories-to-blog-posts/) but the path is not there in frontmatter. As far as I understand I shall add it manually to each blog, if so then tutorial lacks that in the example `.md` file.

Please correct me if I am wrong!

Thanks for help!

**Comment by nayres** [comment]
Hey! What I would do at this point is make sure you are restarting your local server ```gatsby develop``` in order for those fields to be updated. Could you add some context to your request by showing the code involved?

**Comment by d-ivashchuk** [comment]
Yeah I have some experience with Gatsby and I can pick up everything by using graphql. The main questions is about `path`, shall it be added to `frontmatter` manually or its something going behind the scenes in Gatsby. 
And the main thing that concerns me now is the example page, where there is following content of `.md`:

```
---
title: "A Trip To the Zoo"
tags: ["animals", "Chicago", "zoos"]
---

I went to the zoo today. It was terrible.
```
So you can see there is clearly no `path` in frontmatter here. I was able to manually put the path there and everything works, but less experienced people might assume its something that is there by default. If that's not a case and I am just not getting it, that's cool. Otherwise I would suggest updating example.
