### ISSUE TITLE
Site not loading in Safari (Response served by service worker has redirections)

### ISSUE THREAD

**Issue by darknoon** [gatsbyjs/gatsby#9611]
## Description

Here is the site I'm trying to deploy with Gatsby:
https://github.com/darknoon/darknoon-web

Everything was working fine initially, but then I started getting service worker errors with Safari browser (no pages load on my site)

I tried removing the Service worker by removing `gatsby-plugin-offline` from the `gatsby-config.js` but I learned later that it's much more complicated to just make it work again (see https://github.com/gatsbyjs/gatsby/issues/2880)

When I removed it, I think that might have caused its own kind of 

I now reverted the change to remove it and it seems to be working at least temporarily, but there is definitely an issue with the offline plugin here or safari's implementation of service workers.

Possibly related:
I aliased https://pouliot.codes to redirect to https://darknoon.com around the time it started happening

### Steps to reproduce

- Create site with default template (includes `gatsby-plugin-offline`)
- Deploy site with a Zeit `now` static build
- Come back to site later
- Site refuses to load (Error is "Response served by service worker has redirections")
- I reproduced this issue on both my iPhone (iOS 12.1.0) and Mac (macOS 10.14.0)

### Expected result

- Site loads
- If service workers are broken, removing `gatsby-plugin-offline` is a temporary fix

### Actual result

- Blank page with "Response served by service worker has redirections"
- Removing offline plugin makes problem worse

### Environment

Site is built using `Dockerfile` in my repo following the static site tutorial on zeit's webpage.

**Comment by sandeepone** [comment]
For me On Safari, if you have service worker registered, when you "Empty Cache" and refresh page, you get this error.

**Comment by cardiv** [comment]
Could be related: #10036 

I have updated all packages but clearing the iOS browser data does not remove the service worker, it seems. Will test this removal plugin and the new `gatsby-plugin-offline` version.
