### ISSUE TITLE
How to update ButterCMS Package Reference?

### ISSUE THREAD

**Issue by jakelumetta** [gatsbyjs/gatsby#9612]
## Summary
I'd like to update this page: https://www.gatsbyjs.org/packages/gatsby-source-buttercms/  It references an old repo and I want to update it to https://github.com/ButterCMS/gatsby-source-buttercms

## Relevant information
When I click the "Edit this page" on Github, I'm taken here: https://github.com/gatsbyjs/gatsby/tree/master/packages

But the ButterCMS page is not shown in that directory. How can I update this page?

**Comment by LekoArts** [comment]
You're mixing some things up here:

1) The text/content you see on the plugins page is directly from the README of the respective package. In this case: https://github.com/youfoundron/gatsby-source-buttercms
2) Why do you want to change the repository? It's a fork of the "original" source plugin without any changes
3) Gatsby searches for npm packages with "gatsby-plugin" keyword, therefore this plugin (from youfoundron) is indexed. He most probably also publishes the npm package --> The fork doesn't change anything on the npm package

**Comment by jakelumetta** [comment]
Thanks @LekoArts that helps.  We'd like to have our official Gatsby plugin belong to the ButterCMS org so that we can ensure it's high quality and responsive to the community in case the current maintainer is busy or no longer interested.

Do you think the best path for us would be to ask the repo owner to transfer the original to ButterCMS?

**Comment by LekoArts** [comment]
I even would say that it's the only way if you want to keep the npm package name. He'll need to transfer the npm package to you and/or add your accounts for publishing.

**Comment by jakelumetta** [comment]
Ok I think we're all set on this one. Thanks!
