### ISSUE TITLE
Delete merged branches

### ISSUE THREAD

**Issue by gurtjun** [gatsbyjs/gatsby#9624]
## Summary

There are a lot of branches that are already merged into master. Shouldn't we do a clean-up of these branches?

<img width="980" alt="image" src="https://user-images.githubusercontent.com/13830735/47841974-9bf5cc00-ddbb-11e8-90cb-cb2390bdad03.png">

**Comment by pieh** [comment]
Thanks @gurtjun, just did deleting spree (just merged branches), so for now at least it should be cleaner.
