### ISSUE TITLE
Docker with Gatsby on Windows issue: Hot module reloading not working

### ISSUE THREAD

**Issue by somnathghadge** [gatsbyjs/gatsby#9625]
## Summary
We are using Gatsby v 2.0.0 with docker on windows 10.
Whenever I try to run following command my project is run properly  but it serves doesnt find an images because those are served from 0.0.0.0 instead of localhost. 

We tried to this as well but no luck.
gatsby develop --host localhost --port 8000

Here is the command we are using :
"dev:docker": "gatsby develop -H 0.0.0.0"

## Relevant information
Dockerfile:
```
FROM node:9.4.0

RUN curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.2

WORKDIR /usr/app

COPY .yarnrc package.json yarn.lock ./

ENV NPM_CONFIG_LOGLEVEL warn
RUN yarn --silent --pure-lockfile
RUN yarn global add gatsby-cli
RUN rm -f .yarnrc

COPY . .

CMD npm run dev:docker & npm run storybook

EXPOSE 8000
EXPOSE 9001
EXPOSE 8888
```

Note: Everything is working fine on Mac.
### Environment (if relevant)
Windows 10.
Node version: 8.11.3
Docker Version 18.06.1-ce-win73 (19507)

and 

`gatsby`: "^2.0.0",
`gatsby-image`: "^2.0.13",
`gatsby-plugin-create-client-paths`: "^2.0.0",
`gatsby-plugin-emotion`: "^2.0.5",
`gatsby-plugin-manifest`: "^2.0.2",
`gatsby-plugin-offline`: "^2.0.5",
`gatsby-plugin-react-helmet`: "^3.0.0",
`gatsby-plugin-sharp`: "^2.0.5",
`gatsby-source-filesystem`: "^2.0.1",
`gatsby-transformer-sharp`: "^2.1.3",

**Comment by aamorozov** [comment]
@somnathghadge Have you tried providing both port&host?
`gatsby develop --port 5000 --host 0.0.0.0` 
Also do you use docker-compose alongside or just a docker image?

**Comment by somnathghadge** [comment]
@aamorozov, Yes we tried both. Provided host and port as well and we are using docker-compose.

**Comment by drubin** [comment]
Maybe try setting `GATSBY_WEBPACK_PUBLICPATH=/` as an env variable? 

see https://github.com/gatsbyjs/gatsby/pull/9734 and https://github.com/gatsbyjs/gatsby/issues/8348 

Also what docker command are you using to run it?
