### ISSUE TITLE
GraphQL query for the directory tree

### ISSUE THREAD

**Issue by jodays** [gatsbyjs/gatsby#9630]
Hi, I'm trying to build a programmatic sidenav that is updated based on the directory tree structure of files and folders. How can I query my directory so that it can give me back nested data of folder names and file names based on the directory tree. Should I create a yaml file? and how would I be able to integrate that into gatsby.  So how can I use the gatsby source filesystem to give me a javascript object like this to use to map onto my sidenav programatically. 
```
data = 
{
  "type": "directory",
  "name": "hello",
  "children": [
    {
      "type": "directory",
      "name": "world",
      "children": [
        {
          "type": "file",
          "name": "one.txt"
        },
        {
          "type": "file",
          "name": "two.txt"
        }
      ]
    },
    {
      "type": "file",
      "name": "blahblah"
    }
  ]
}
```

**Comment by LekoArts** [comment]
Have a look at Meetup's design system:
https://github.com/meetup/swarm-design-system

They have their data in `src/content` and pull that and modify it in gatsby-node: https://github.com/meetup/swarm-design-system/blob/master/gatsby-node.js#L5-L35

`createFilePath` gives you the path to every file in your folder you specify (README: https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-filesystem). Use JS to read the current directory, upper directory etc. to generate your directory tree.
