### ISSUE TITLE
Custom Host and HTTPS

### ISSUE THREAD

**Issue by nikbelikov** [gatsbyjs/gatsby#9637]
Hi!

Is there any way to make an https session with custom host name?

For example, I've started developing with `gatsby develop --https` which gives me `https://localhost:8000/` and it's work well.

But when I configure hosts file on my macos with:
127.0.0.1	somename.de
, `https://somename.de:8000` doesn't work.

Please, help me.

**Comment by yogeshkotadiya** [comment]
You can use -H flag to use a custom hostname

`gatsby develop -H hostname -p PORT -S`

In your case, you can use something like this

`gatsby develop -H somename.de -S`

Check docs for more Info: [Gatsby-Cli Docs](https://www.gatsbyjs.org/docs/gatsby-cli/)

**Comment by nikbelikov** [comment]
@yogeshkotadiya I've already tried that and had insecure page though http://take.ms/OsSPP

**Comment by yogeshkotadiya** [comment]
You have to generate an SSL certificate for your local environment.
