### ISSUE TITLE
Not able to start dev server in /www 

### ISSUE THREAD

**Issue by pranshuchittora** [gatsbyjs/gatsby#9640]
Today I tried to run the instance of gatsby website locally.
It stucks at `source and transform nodes` :disappointed: 
Pls refer this screenshot :point_down: 
![screenshot from 2018-11-02 01-25-09](https://user-images.githubusercontent.com/32242596/47877617-516b6280-de42-11e8-8d64-a77d6fde7781.png)

**Comment by DSchau** [comment]
@pranshuchittora yeah, it's a little unfortunate. In general, the site showcase (and taking screenshots) is the bulk of the time spent there. It'd eventually complete, just takes quite a while.

Can you [try this setting](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-screenshot#placeholder-image)? The general idea is you'd create `.env.development` and then add `GATSBY_SCREENSHOT_PLACEHOLDER=true`

**Comment by DSchau** [comment]
Sounds like that worked, so closing out!

**Comment by pranshuchittora** [comment]
Thanks @DSchau it working :+1: 
![screenshot from 2018-11-02 02-30-19](https://user-images.githubusercontent.com/32242596/47880466-5849a380-de49-11e8-811b-36d2d6b247d9.png)

**Comment by pranshuchittora** [comment]
Consider these updates in the docs #9643  :+1:
