### ISSUE TITLE
gatsby-plugin-remove-trailing-slashes iOS 7 issue

### ISSUE THREAD

**Issue by dial3x** [gatsbyjs/gatsby#9648]
This plugin is causing the error
`TypeError: 'undefined' is not an object (evaluating 't.split')`
When active it prevents the load of the site.

Steps to reproduce
install the plugin  `gatsby-plugin-remove-trailing-slashes ` v2.0.4

Expected result
Site should load.

Environment
Production. Tested using iPhone 5S and iPhone 5.

  System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Binaries:
    Yarn: 1.10.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 41.16299.611.0
  npmPackages:
    gatsby: ^2.0.37 => 2.0.37
    gatsby-image: ^2.0.19 => 2.0.19
    gatsby-link: ^2.0.6 => 2.0.6
    gatsby-plugin-google-tagmanager: ^2.0.6 => 2.0.6
    gatsby-plugin-manifest: ^2.0.7 => 2.0.7
    gatsby-plugin-offline: ^2.0.11 => 2.0.11
    gatsby-plugin-polyfill-io: ^1.0.5 => 1.0.5
    gatsby-plugin-react-helmet: ^3.0.1 => 3.0.1
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-remove-trailing-slashes: ^2.0.4 => 2.0.4
    gatsby-plugin-robots-txt: ^1.3.0 => 1.3.0
    gatsby-plugin-sass: ^2.0.3 => 2.0.3
    gatsby-plugin-sharp: ^2.0.11 => 2.0.11
    gatsby-plugin-sitemap: ^2.0.2 => 2.0.2
    gatsby-remark-images: ^2.0.5 => 2.0.5
    gatsby-source-contentful: ^2.0.10 => 2.0.10
    gatsby-transformer-remark: ^2.1.11 => 2.1.11
    gatsby-transformer-sharp: ^2.1.7 => 2.1.7

**Comment by dial3x** [comment]
This was an issue with `gatsby-plugin-polyfill-io` not `gatsby-plugin-remove-trailing-slashes`

**Comment by b4stien** [comment]
Hey, @dial3x, I'm having the same issue, can you be more specific on what was happening, what bugged and how you fixed it? Thanks a lot.
