### ISSUE TITLE
Update tutorial one to use the cute gatsby illustration

### ISSUE THREAD

**Issue by tanvibhakta** [gatsbyjs/gatsby#9655]
#9412 updates the default starter to use a cool illustration of an astronaut holding a tasty treat! Let's update the tutorial one to use the same image, instead of a random image from unsplash. 
The tutorial is here:
https://www.gatsbyjs.org/tutorial/part-one/
The file to edit is here:
https://github.com/gatsbyjs/gatsby/blob/master/docs/tutorial/part-one/index.md

You will also need to update the relevant screenshots.

Let's spread the purple love!

**Comment by ebello** [comment]
Hi @tanvibhakta I'd be happy to take this one on.

**Comment by tanvibhakta** [comment]
Hey @ebello go ahead and create the PR!

Hey @barrymcgee! Welcome to Gatsby! To be honest I'm pretty new here too - how about we wait for a day or two and come back again? Meanwhile, I encourage you to check out more issues labelled 'good-first-issue' and see if there's something you can find to work on? Happy to help either way. :)

**Comment by ebello** [comment]
Hi all, I hope I'm not making this more complicated than it should be, but for purposes of the tutorial I think we should use a pre-hosted image to keep things as easy as possible. I'm looking for a URL of where the Gatsby astronaut image would be, and thought to look at the [demo site](https://gatsby-starter-default-demo.netlify.com) for the default starter, but it looks like it's using an old version. Is it possible to update the Netlify site with the latest default starter? Or is that image hosted elsewhere already?

**Comment by barrymcgee** [comment]
@ebello The risk with using an image hosted elsewhere is that we can't guarantee it will always be available.

If for some reason, the image was pulled offline, users working through the "Hello World" tutorial would be left wondering why their code is broken already.

The ideal solution is that the image would be available as a relative link in their project folder already as part of the `gatsby-starter-hello-world` - I've proposed a PR above to (I think) do that.

**Comment by lexishanson** [comment]
Is this the image you're looking for? https://github.com/gatsbyjs/gatsby-starter-default/blob/master/src/images/gatsby-astronaut.png

**Comment by ebello** [comment]
@barrymcgee Thanks I agree that copying the image over to the starter project and making a relative link is a better solution. Will merge your edit in.

**Comment by ebello** [comment]
Ah, @barrymcgee I didn't realize they were separate repos. I made a note that my PR should be contingent upon yours.

**Comment by shannonbux** [comment]
Closing this now; it ought to have been closed when #9698 was closed.
