### ISSUE TITLE
SCSS : How to set-up cross-browser processing ?

### ISSUE THREAD

**Issue by HeikoMueller** [gatsbyjs/gatsby#9658]
Hi, 

I am new to Gatsby and the React environment. I am currently playing around with a template written in SCSS: 

https://github.com/codebushi/gatsby-starter-forty

...and I realized that the processing of the SCSS does output CSS that does not work in older browsers. For instance, the background image is not sticky in Safari, and the main content is not visible at all in IE. 

Is there a recommended way to automatically adjust the SCSS processing so that the output addresses older browsers as well ? I was trying around setting up some plugins such as 'gatsby-spon-scss-postcss' or 'babel-plugin-styled-components', but non of them worked. 

Thank you very much for any help ! 

Best
Heiko

**Comment by kakadiadarpan** [comment]
@HeikoMueller you need to use `gatsby-plugin-postcss` with `autoprefixer` to get cross-browser support for css generated from your sass.

**Comment by HeikoMueller** [comment]
Thank you @kakadiadarpan ! I now realized gatsby-plugin-postcss is included in gatsby-plugin-sass, so I can adjust the postcss plugins inside of gatsby-plugin-sass config section. Great!
