### ISSUE TITLE
Full-featured documentation theme

### ISSUE THREAD

**Issue by korylus** [gatsbyjs/gatsby#9662]
I am looking into using Gatsby as the CMS for our documentation.

Is there an out-of-the-box documentation theme that we could use? The one documentation starter is very bare bones. It would be great to have a theme similar to your own documentation available.

**Comment by pieh** [comment]
Hey @korylus. We don't have proper theme system yet (see not yet published blog post on work being done on this front: https://github.com/gatsbyjs/gatsby/blob/bff64cff17aff346ce917bdea74f3188443960dd/docs/blog/2018-10-26-introducing-gatsby-themes/index.md )

This also explains limitations with using starters as theming tool - they are one use only (scaffolding), so it is also difficult and time consuming to extract and maintain existing site (in this case our docs) "theme" into starter. Once we have theming support, refactoring our site theme into separate reusable package (or multiple packages for multiple parts of site) would be much more maintainable.
