### ISSUE TITLE
yarn develop gets stuck at ? Source and transform nodes

### ISSUE THREAD

**Issue by Aboumicho** [gatsbyjs/gatsby#9666]
Hello! 

The problem with our gatsby project is that it gets stuck at the same line. Everything seems to work fine but it doesn't.. 

Here is what appears on the command line: 

`> gatsby develop
success open and validate gatsby-config - 0.004 s
success load plugins - 0.195 s
success onPreInit - 0.605 s
success delete html and css files from previous builds - 0.368 s
success initialize cache - 3.565 s
success copy gatsby files - 0.267 s
success onPreBootstrap - 0.008 s
? source and transform nodes
=START PLUGIN=====================================

Site URL: https://somecorpsite.com
Site hosted on Wordpress.com: false
Using ACF: false
Using Auth: undefined undefined
Verbose output: true

Mama Route URL: https://somecorpsite.com/wp-json

? source and transform nodesRoute discovered : /
Invalid route.
Route discovered : /wp/v2
Invalid route.
Route discovered : /wp/v2/posts
Valid route found. Will try to fetch.
Route discovered : /wp/v2/posts/(?P<id>[\d]+)
Invalid route.
Route discovered : /wp/v2/posts/(?P<parent>[\d]+)/revisions
Invalid route.
Route discovered : /wp/v2/posts/(?P<parent>[\d]+)/revisions/(?P<id>[\d]+)
Invalid route.
Route discovered : /wp/v2/pages
Excluded route from excludedRoutes pattern.
Route discovered : /wp/v2/pages/(?P<id>[\d]+)
Invalid route.
Route discovered : /wp/v2/pages/(?P<parent>[\d]+)/revisions
Invalid route.
Route discovered : /wp/v2/pages/(?P<parent>[\d]+)/revisions/(?P<id>[\d]+)
Invalid route.
Route discovered : /wp/v2/media
Valid route found. Will try to fetch.
Route discovered : /wp/v2/media/(?P<id>[\d]+)
Invalid route.
Route discovered : /wp/v2/types
Valid route found. Will try to fetch.
Route discovered : /wp/v2/types/(?P<type>[\w-]+)
Invalid route.
Route discovered : /wp/v2/statuses
Valid route found. Will try to fetch.
Route discovered : /wp/v2/statuses/(?P<status>[\w-]+)
Invalid route.
Route discovered : /wp/v2/taxonomies
Valid route found. Will try to fetch.
Route discovered : /wp/v2/taxonomies/(?P<taxonomy>[\w-]+)
Invalid route.
Route discovered : /wp/v2/categories
Valid route found. Will try to fetch.
Route discovered : /wp/v2/categories/(?P<id>[\d]+)
Invalid route.
Route discovered : /wp/v2/tags
Excluded route from excludedRoutes pattern.
Route discovered : /wp/v2/tags/(?P<id>[\d]+)
Invalid route.
Route discovered : /wp/v2/yst_prominent_words
Excluded route from excludedRoutes pattern.
Route discovered : /wp/v2/yst_prominent_words/(?P<id>[\d]+)
Invalid route.
Route discovered : /wp/v2/users
Valid route found. Will try to fetch.
Route discovered : /wp/v2/users/(?P<id>[\d]+)
Invalid route.
Route discovered : /wp/v2/users/me
Excluded route from excludedRoutes pattern.
Route discovered : /wp/v2/comments
Excluded route from excludedRoutes pattern.
Route discovered : /wp/v2/comments/(?P<id>[\d]+)
Invalid route.
Route discovered : /wp/v2/settings
Excluded route from excludedRoutes pattern.
Route discovered : /oembed/1.0
Invalid route.
Route discovered : /oembed/1.0/embed
Invalid route.
Route discovered : /oembed/1.0/proxy
Invalid route.
Route discovered : /yoast/v1
Excluded route from excludedRoutes pattern.
Route discovered : /yoast/v1/configurator
Excluded route from excludedRoutes pattern.
Route discovered : /yoast/v1/reindex_posts
Excluded route from excludedRoutes pattern.
Route discovered : /yoast/v1/ryte
Excluded route from excludedRoutes pattern.
Route discovered : /yoast/v1/indexables/(?P<object_type>.*)/(?P<object_id>\d+)
Invalid route.
Route discovered : /yoast/v1/statistics
Excluded route from excludedRoutes pattern.
Route discovered : /acf/v3
Invalid route.
Route discovered : /acf/v3/posts/(?P<id>[\d]+)/?(?P<field>[\w\-\_]+)?
Invalid route.
Route discovered : /acf/v3/posts
Valid route found. Will try to fetch.
Route discovered : /acf/v3/pages/(?P<id>[\d]+)/?(?P<field>[\w\-\_]+)?
Invalid route.
Route discovered : /acf/v3/pages
Excluded route from excludedRoutes pattern.
Route discovered : /acf/v3/media/(?P<id>[\d]+)/?(?P<field>[\w\-\_]+)?
Invalid route.
Route discovered : /acf/v3/media
Valid route found. Will try to fetch.
Route discovered : /acf/v3/categories/(?P<id>[\d]+)/?(?P<field>[\w\-\_]+)?
Invalid route.
Route discovered : /acf/v3/categories
Excluded route from excludedRoutes pattern.
Route discovered : /acf/v3/tags/(?P<id>[\d]+)/?(?P<field>[\w\-\_]+)?
Invalid route.
Route discovered : /acf/v3/tags
Excluded route from excludedRoutes pattern.
Route discovered : /acf/v3/yst_prominent_words/(?P<id>[\d]+)/?(?P<field>[\w\-\_]+)?
Invalid route.
Route discovered : /acf/v3/yst_prominent_words
Excluded route from excludedRoutes pattern.
Route discovered : /acf/v3/comments/(?P<id>[\d]+)/?(?P<field>[\w\-\_]+)?
Invalid route.
Route discovered : /acf/v3/comments
Excluded route from excludedRoutes pattern.
Route discovered : /acf/v3/options/(?P<id>[\w\-\_]+)/?(?P<field>[\w\-\_]+)?
Invalid route.
Route discovered : /acf/v3/users/(?P<id>[\d]+)/?(?P<field>[\w\-\_]+)?
Invalid route.
Route discovered : /acf/v3/users
Valid route found. Will try to fetch.
Route discovered : /yoast/v1/prominent_words
Excluded route from excludedRoutes pattern.
Route discovered : /yoast/v1/prominent_words_link/(?P<id>[\d]+)
Invalid route.
Route discovered : /yoast/v1/complete_recalculation
Excluded route from excludedRoutes pattern.
Route discovered : /yoast/v1/link_suggestions
Excluded route from excludedRoutes pattern.
Route discovered : /yoast/v1/redirects
Excluded route from excludedRoutes pattern.

Fetching the JSON data from 10 valid API Routes...

=== [ Fetching wordpress__POST ] === https://somecorpsite.com/wp-json/wp/v2/posts
? source and transform nodes
Total entities : 235
Pages to be requested : 3
? source and transform nodes -> wordpress__POST fetched : 235
Fetching the wordpress__POST took: 17352.127ms

=== [ Fetching wordpress__wp_media ] === https://somecorpsite.com/wp-json/wp/v2/media
? source and transform nodes
Total entities : 4638
Pages to be requested : 47
? source and transform nodes -> wordpress__wp_media fetched : 3212
Fetching the wordpress__wp_media took: 73903.345ms

=== [ Fetching wordpress__wp_types ] === https://somecorpsite.com/wp-json/wp/v2/types
? source and transform nodes -> wordpress__wp_types fetched : 1
Fetching the wordpress__wp_types took: 875.090ms

=== [ Fetching wordpress__wp_statuses ] === https://somecorpsite.com/wp-json/wp/v2/statuses
? source and transform nodes -> wordpress__wp_statuses fetched : 1
Fetching the wordpress__wp_statuses took: 852.903ms

=== [ Fetching wordpress__wp_taxonomies ] === https://somecorpsite.com/wp-json/wp/v2/taxonomies
? source and transform nodes -> wordpress__wp_taxonomies fetched : 1
Fetching the wordpress__wp_taxonomies took: 1083.236ms

=== [ Fetching wordpress__CATEGORY ] === https://somecorpsite.com/wp-json/wp/v2/categories
? source and transform nodes -> wordpress__CATEGORY fetched : 9
Fetching the wordpress__CATEGORY took: 1433.496ms

=== [ Fetching wordpress__wp_users ] === https://somecorpsite.com/wp-json/wp/v2/users
? source and transform nodes -> wordpress__wp_users fetched : 14
Fetching the wordpress__wp_users took: 1790.912ms

=== [ Fetching wordpress__acf_posts ] === https://somecorpsite.com/wp-json/acf/v3/posts
? source and transform nodes -> wordpress__acf_posts fetched : 100
Fetching the wordpress__acf_posts took: 5476.182ms

=== [ Fetching wordpress__acf_media ] === https://somecorpsite.com/wp-json/acf/v3/media
? source and transform nodes -> wordpress__acf_media fetched : 95
Fetching the wordpress__acf_media took: 6159.952ms

=== [ Fetching wordpress__acf_users ] === https://somecorpsite.com/wp-json/acf/v3/users
? source and transform nodes -> wordpress__acf_users fetched : 14
Fetching the wordpress__acf_users took: 16257.418ms

=END PLUGIN=====================================: 126446.712ms
? source and transform nodes`

Sometimes it works, but 99% of the time it doesn't. After maybe 50 clear cache -> restart server -> repeat, it might work, and I really have no clue why.

Help anyone? :)

**Comment by btk** [comment]
Hey,

So there might be few reasons why your site sometimes gets stuck at there. Your wordpress is pretty big, more than 200 posts and 3212 images. You might be at the same boat with some people in #6654

You might have a slow internet connection, and the image sourcing from the source might get timeout. And everytime you clear the cache, you start downloading all that 3212 image all over again. So letting it do its job for once and not touching cache is your best bet. But if you have slow internet connection. I would recommend using a CI tool to see if it is caused by your slow internet. 

But keep in mind your website is pretty bulky. Gatsby is currently working on better support for websites at this size.

**Comment by kakadiadarpan** [comment]
Closed in favor of #6654

**Comment by btk** [comment]
@Aboumicho can you share the Image(s) you used on that mentioned post. Or can you confirm that your build takes 5min when you remove that post?

The image might be faulty?

**Comment by Aboumicho** [comment]
> @Aboumicho can you share the Image(s) you used on that mentioned post. Or can you confirm that your build takes 5min when you remove that post?
> 
> The image might be faulty?

I can't really show you because it's a company website and I can't simply take off the post. I know this error started happening after one post. I don't think this is the cause might be a coincidence I don't know..

**Comment by Aboumicho** [comment]
There is nothing special in this post, there are as many images. But if you need to see it, here is the [**blog**](https://broadsign.com/blog/) section of the wordpress website

here is the most recent [**post**](https://broadsign.com/blog/dooh-metrics/?blog-origin=blog)

**Comment by sidharthachatterjee** [comment]
@Aboumicho Closing this for now since it seems stale but please feel free to reopen if you're still seeing this or if there is anything else we can help you with
