### ISSUE TITLE
Make cacheable files have a pattern matchable file name

### ISSUE THREAD

**Issue by fantapop** [gatsbyjs/gatsby#9667]
## Summary

  It would be great add some distinct pattern to a file if its cacheable.  Either by using a hash with a consistent number of characters or by adding something ```-hashed-``` to the filename.  ie.  ```public/component---src-templates-index-js-hashed-f87c2329f00ff2a28311.js```.

### Motivation

I'm setting up caching for our gatsby site in cloudfront.  In order to match all cacheable files I need to create a behavior for each extension.  This can be error prone if I miss a file I didn't know I had and means adding new types of files needs to update this as well.

**Comment by btk** [comment]
Oh I think this sounds really good. I have struggled with deciding which files should I let the CDN cache.

**Comment by fantapop** [comment]
Is there any chance this would make it in the roadmap?

**Comment by KyleAMathews** [comment]
You can read about how to setup caching for Gatsby sites @ https://www.gatsbyjs.org/docs/caching/
