### ISSUE TITLE
Windows path problem in .cache/child-routes.js

### ISSUE THREAD

**Issue by mdotasia** [gatsbyjs/gatsby#967]
Gatsby: v1.0.0-alpha14 on Windows 7:

I get

```
ERROR in ./.cache/child-routes.js
Module not found: Error: Cannot resolve module 'C:Users	hilo.maierProjectscoding-blogsrc	emplates	emplate-blog-post.js' in C:\Users\thilo.maier\Projects\coding-blog\.cache
 @ ./.cache/child-routes.js 62:36-120 88:36-120
```
In `child-routes.js` I see non-escaped Windows paths like this one:

```
class Component20150528HiFolks extends React.Component {
          render () {
            const Component = preferDefault(require('C:\Users\thilo.maier\Projects\coding-blog\src\templates\template-blog-post.js'))
            const data = require('./json/2015-05-28-hi-folks.json')
            return <Component {...this.props} {...data} />
          }
        }
```
and all `\t` in the string are interpreted as tabs.

Further down path uses Unix style `/`:

```
class ComponentIndex extends React.Component {
          render () {
            const Component = preferDefault(require('C:/Users/thilo.maier/Projects/coding-blog/src/pages/index.js'))
            const data = require('./json/index.json')
            return <Component {...this.props} {...data} />
          }
        }
```

I guess this needs a `path.normalize` somewhere.

---
- `gatsby-node.js`: https://github.com/mdotasia/coding-blog/blob/conversion/gatsby-node.js (unchanged from https://github.com/gatsbyjs/gatsby-starter-blog/tree/1.0)
- `gatsby-browser.js`: none

**Comment by KyleAMathews** [comment]
I'm going to release alpha 15 soon as in today or tomorrow. It'll have a big refactor that eliminates child-routes. You want to try cloning the gatsby repo and see if things work for you from the 1.0 branch? This doc page can help get you up to speed https://www.gatsbyjs.org/docs/how-to-contribute/

**Comment by jbolda** [comment]
@mdotasia there have been a few releases as of late and we added a windows CI. Give it a try again!

**Comment by mdotasia** [comment]
No problems on Windows any more.
