### ISSUE TITLE
Sometimes the images from markdown are not emitted. Both in build and develop.

### ISSUE THREAD

**Issue by hackhat** [gatsbyjs/gatsby#9675]
My app tries to make a request to /static/someLongId.jpg but fails, in the public folder there is no file like that.

This started since I started deleting my public folder because Gatsby doesn't clean it properly I guess?

There is only one image in the /static/ folder (with probably 10 different sizes). This image is from a component not from markdown.

I added typescript as a dependency and set the version to 2.9.1 in tsconfig and I think this broke something. After removing it, looks like it works fine again.

### Environment

  System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
  Binaries:
    Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 5.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.0.19 => 2.0.21
    gatsby-image: ^2.0.17 => 2.0.17
    gatsby-plugin-catch-links: ^2.0.4 => 2.0.4
    gatsby-plugin-emotion: ^2.0.5 => 2.0.5
    gatsby-plugin-google-analytics: ^2.0.6 => 2.0.6
    gatsby-plugin-manifest: ^2.0.6 => 2.0.6
    gatsby-plugin-offline: ^2.0.5 => 2.0.6
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^2.0.8 => 2.0.8
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.1
    gatsby-plugin-typescript: ^2.0.0 => 2.0.0
    gatsby-plugin-typography: ^2.2.0 => 2.2.0
    gatsby-remark-images: ^2.0.4 => 2.0.4
    gatsby-source-filesystem: ^2.0.3 => 2.0.3
    gatsby-transformer-remark: ^2.1.7 => 2.1.7
    gatsby-transformer-sharp: ^2.1.5 => 2.1.5

**Comment by KyleAMathews** [comment]
Gatsby assumes you don't delete the public folder yes. To get it to regenerate the thumbnails, delete the .cache folder as well.
