### ISSUE TITLE
Images SEO. How do you handle images for SEO? If on every build the image can have a different id.

### ISSUE THREAD

**Issue by hackhat** [gatsbyjs/gatsby#9676]
Images SEO. How do you handle images for SEO? If on every build the image can have a different id.

**Comment by KyleAMathews** [comment]
Image names are based on the name and contents of the image. If you don't change the original image, on every build, the generated image names will be identical.

**Comment by hackhat** [comment]
Ok, that's good, but if you don't check in your public folder (as you said here https://github.com/gatsbyjs/gatsby/issues/9649 ) and you clone a fresh project you lost all the old images.

I'd suggest to open this issue because what you said can't be a solution.

**Comment by DSchau** [comment]
@hackhat want to clarify on your point there?

If we take the following statement as true (it is -> see gatsbyjs/gatsby#8808, and the original functionality as evidence):

> Image names are based on the name and contents of the image. If you don't change the original image, on every build, the generated image names will be identical

this means that images will be re-generated, named identically and deterministic on file contents, in the public folder. I'm not sure I see the issue, but please let me know if you think I'm off base or missing something!

A re-production showing that images have different names or paths after re-build would be highly appreciated here, as well!

**Comment by hackhat** [comment]
So there is a major problem:

 - I check out the repo
 - I add "imageA" in the source code
 - CI will add "imageA" to the "public" and will be all fine
 - Now we clean the cache of the CI or we move CI to another provider
 - Now I delete the "imageA" in my source code
 - CI will build, but will be no "imageA" in the public folder because we moved CI or cleaned cache

Now how will you get the "imageA" back?

**Comment by DSchau** [comment]
>  will build, but will be no "imageA" in the public folder because we moved CI or cleaned cache

Can you explain this? It will re-build the public folder contents (that need re-building). Since it doesn't exist between CI re-builds regardless, that's clearly proof that it's working as intended?

**Comment by DSchau** [comment]
> Another problem is if I just change a single pixel on the image, it will create a new hash and lose the history, check it out below:

I think most _want_ this. The image changed, it's fair that the hash changes? It wouldn't really make sense for us to implement some type of % changed algorithm and keep the same file name, nor do I think it's _safe_ to re-use the same image name (or lose the hash) to prevent the inverse, e.g. we have an image that we _want_ to change, but it's being cached too aggressively.

**Comment by hackhat** [comment]
> Misunderstood your point, for a second. If you're no longer referencing imageA in your source code--and you shouldn't be, because the query/reference/etc. will fail because imageA doesn't exist--

We are talking about SEO for images, not about graphql.

> you don't want it in your public folder? Right?

I don't know if I want or not, but @KyleAMathews suggested to don't wipe the public folder. So I guess it will remain there unless you delete that folder. 

So if you delete the folder you don't have it, if you keep the folder you have it. Do you think is a good practice? I personally think is not, but that's my opinion.

> Another problem is if I just change a single pixel on the image, it will create a new hash and lose the history, check it out below:

Maybe. If I change a single pixel on my image I want people to find it on google images.

> It wouldn't really make sense for us to implement some type of % changed algorithm and keep the same file name, nor do I think it's safe to re-use the same image name (or lose the hash) to prevent the inverse, e.g. we have an image that we want to change, but it's being cached too aggressively.

I'm not suggesting this at all. I'm just asking some questions about how to handle images for SEO with Gatsby.

**Comment by DSchau** [comment]
> We are talking about SEO for images, not about graphql.

If you delete the image, it's likely queried with GraphQL (or some other mechanism, even a relative link), which would break in that scenario, regardless. We use GraphQL for images + SEO in gatsbyjs.org, as do many people, e.g. to request an image of a certain size from our file system.

> I don't know if I want or not, but @KyleAMathews suggested to don't wipe the public folder. So I guess it will remain there unless you delete that folder.

If we're talking the deletion scenario, e.g. an image in src/, that has since been deleted, it wouldn't _matter_ whether public was deleted/modified/etc. That image would be non-existent and any links to it (whether queried with GraphQL, relative link, etc.) would be broken anyways, right?

> Maybe. If I change a single pixel on my image I want people to find it on google images.

Whether changed or not, the image is still a valid reference and has a file name of its content (and valid metadata/title/etc.) it should be fine?

One thing we could maybe investigate here is keeping the image _filename_ the same, but appending a query string with the content hash. I believe we do similar things in certain places, but honestly, I'm not an SEO expert and don't know whether this adequately solves the caching problem.

**Comment by DSchau** [comment]
If you want images where the file name never changes, I would recommend checking out the [static folder](https://www.gatsbyjs.org/docs/adding-images-fonts-files/). This effectively short circuits some build process stuff, so if you create `static/some-image.png` it will always be copied to `public/some-image.png` and available as a relative link, e.g. `<meta property="og:image" content="https://your-site.com/some-image.png" />`

That could be a good solution to your SEO needs. Note that this precludes the build process, so if you do change that image, it's possible there's some delay until the browser's cache (or Googlebot's cache) picks it up?

**Comment by hackhat** [comment]
@DSchau

> If you delete the image, it's likely queried with GraphQL (or some other mechanism, even a relative link), which would break in that scenario, regardless. We use GraphQL for images + SEO in gatsbyjs.org, as do many people, e.g. to request an image of a certain size from our file system.

I'm not sure how to explain it, but I'm not talking about graphql at all.

Let me put the scenario again more clearly:

 - I check out the repo
 - I add "imageA" in the source code and **graphql will import that image**
 - CI will add "imageA" to the "public" and will be all fine
 - Now we clean the cache of the CI or we move CI to another provider
 - Now I delete the "imageA" in my source code and **graphql will not import that image anymore**
 - CI will build, but will be no "imageA" in the public folder because we moved CI or cleaned cache

You mention that graphql will break, but that's not even what I'm talking here about.

> You should never rely on something in public from a previous build remaining for anything except general build performance (e.g. won't re-generate if no changes) if that helps!

Well, that's what I'd expect, but @KyleAMathews said here https://github.com/gatsbyjs/gatsby/issues/9649:

> This is by design as if you deploy often and delete old job files then those people who might have opened the site on a previous deploy will now get 404s for resources that got deleted.

when I said that not all files are wiped by default.

So IMO, this looks like we expect to keep the public folder without wiping, otherwise will break when you deploy. But then you tell me we should not rely on the public folder. Do you see the contradiction?

Let me put more clear: 

 - public folder needs to keep previous build files to don't have 404s for users that opened the previous deploy - @KyleAMathews
 - You should never rely on something in public from a previous build remaining for anything except general build performance (e.g. won't re-generate if no changes) if that helps! - @DSchau 


Also if we take just what @KyleAMathews said and we do this scenario again:

 - I check out the repo
 - I add "imageA" in the source code and **graphql will import that image**
 - CI will add "imageA" to the "public" and will be all fine
 - Now we clean the cache of the CI or we move CI to another provider
 - Now I delete the "imageA" in my source code and **graphql will not import that image anymore**
 - CI will build, but will be no "imageA" in the public folder because we moved CI or cleaned cache

Users running the previous build will have 404s for the "imageA", do you see any problem here or no problem again? Can you please tell me how would you handle this scenario? 

So the question remains how do you solve it? 

> If you want images where the file name never changes, I would recommend checking out the static folder. This effectively short circuits some build process stuff, so if you create static/some-image.png it will always be copied to public/some-image.png and available as a relative link, e.g. <meta property="og:image" content="https://your-site.com/some-image.png" />

> That could be a good solution to your SEO needs. Note that this precludes the build process, so if you do change that image, it's possible there's some delay until the browser's cache (or Googlebot's cache) picks it up?

Well, not really. I don't think is maintainable to have all the posts' images manually added as `<meta/>` tags and then in the static folder as well. Probably the image from markdown should do that, I don't know.

**Comment by KyleAMathews** [comment]
You're discussing a pretty obscure scenario (changing CIs or providers) and in this sorts of radical changes (combined with simultaneous design changes) site breakage is inevitable.

Our advice is to not change hosts or CIs very often ;-)

**Comment by hackhat** [comment]
> You're discussing a pretty obscure scenario (changing CIs or providers) and in this sorts of radical changes (combined with simultaneous design changes) site breakage is inevitable.

But what if you build on your own machine? and you have 2 developers, is not a mess?

I don't think is obscure, is a normal case that should be handled. I understand that for you don't need a robust application, and if this is the case, I think is important to put a note on the project that it might break to some people randomly if you delete the public folder.

> Our advice is to not change hosts or CIs very often ;-)

I think at this point the best thing to do is to check it in, and delete old files every now and then. I can't have something that relies on having my code on my pc (like in your case). I'm amazed that many companies relies on temporary cache for their own website build with gatsby.

**Comment by DSchau** [comment]
Alright - let's take a step back here, I think there's some reasonable confusion on both of our parts.

How are you referencing images in your Gatsby application? Relative links with an `img` tag? A meta tag pointing to a reference? Are you `require`ing the images? You made a reference to Markdown, so are you using relative links in your Markdown content? Something else?

Knowing that will help us better answer some of your questions. As it stands now, it seems _reasonable_ that you would lose a reference to the image in public/ because you've _deleted_ the image. On a subsequent re-build, the image is no longer required.

**Comment by hackhat** [comment]
> How are you referencing images in your Gatsby application? Relative links with an img tag? A meta tag pointing to a reference? Are you requireing the images? You made a reference to Markdown, so are you using relative links in your Markdown content? Something else?

I use images in my markdown, so the plugin creates the img tag under the hood. Yes, relateive images from markdown. gatsby-remark-images I guess everybody is using this.

> Knowing that will help us better answer some of your questions. As it stands now, it seems reasonable that you would lose a reference to the image in public/ because you've deleted the image. On a subsequent re-build, the image (should) no longer be required, otherwise you've created a broken image reference.

What I think is the main problem is that somebody says you need to keep those files otherwise it will break the app for users of old apps. But then you tell me that those files don't matter. I think they are crucial, you can't just be ok if 10% of your users will have a broken app because they got an old cache edge html file.

For me I want to have as many as possible users happy. I don't want to hope that they get the latest version. Also I don't want to hope that nobody cleans the cache of the CI server. I think is crazy to develop apps based on hope.

I bet this is a problem, but not many people notice yet, no tracking... maybe the images are not changed and removed that often, but still it will break.
