### ISSUE TITLE
How to deal with pagination and gatsby-source-graphql?

### ISSUE THREAD

**Issue by marcaaron** [gatsbyjs/gatsby#9682]
I'd like to use `gatsby-source-graphql` to pull repository information from the Github GraphQL API for use with gatsby. Only problem is the Github GraphQL API places a limit of 100 on how many list items are returned from list fields e.g. PullRequests, Comments, etc. Is there any existing strategy for queries that are limited by the number of results they can return? 

_Example:_ 
1. get the last 100 pull requests in a repository
2. using the cursor returned by the previous query get the last 100 starting from the cursor
3. and so on until there are no PRs left to fetch
4. use gatsby to query the entire data set without such limit restrictions set

I'm thinking another strategy would be to just set up a node server to run a script that performs a similar process (write to JSON or something) and then pass that into gatsby. But wondering if there's a built in way?

**Comment by rrathbone** [comment]
Hi marcaaron. Were you able to find a solution to this problem? I just ran into the same issue.

**Comment by freiksenet** [comment]
Hi! There isn't any existing strategy for that. From the size limited result, you should check if there is next page and then continue until there is no next page. For example with github, assuming you are using `gatsby-source-graphql`.

```js
const QUERY = `    
  query($after: String) {
      github {
        viewer {
	  repositories(first:100, after: $after) {
            nodes {
              id
            }
            pageInfo {
             endCursor
             hasNextPage
           }
        }
      }
    }`

let { data } = await graphql(QUERY)
const repos = data.viewer.repositories.nodes
while (data.viewer.repositories.pageInfo.hasNextPage) {
  data = await graphql(QUERY, {
    after: data.viewer.repositories.pageInfo.endCursor
  })
  repos.push(...data.viewer.repositories.nodes)
}

// create pages
```

**Comment by eric-hc** [comment]
Does anyone know if there is a more elegant solution to this yet?

**Comment by timomayer** [comment]
We are also searching for a solution for that
