### ISSUE TITLE
GraphQL GatsbyImage fragment inside fragment returns zero results

### ISSUE THREAD

**Issue by dubcanada** [gatsbyjs/gatsby#9693]
## Description

If you have a fragment and inside your fragment you use gatsby image fragment say

    {
        blocks {
            __typename
            ...imageLeftTextRightBlockFragment
        }
    }

and

    fragment imageLeftTextRightBlockFragment on ImageLextTextRightBlock {
        image {
            childImageSharp {
                fluid(maxWidth: 400) {
                    ...GatsbyImageSharpFluid_withWebp_noBase64
                }
        }
    }

image even though it exists contains no results. Running a query against that ImageLeftTextRightBlock returns an array of images.

I suspect this is because graphql seems to have a lot of issues with fragments inside fragments.

### Steps to reproduce

See above

### Expected result

Should return results the exact same as if it was just one level of fragments.

### Actual result

Returns nothing

### Environment

  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Shell: 5.2 - /bin/zsh
  Binaries:
    Node: 11.0.0 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  npmPackages:
    gatsby: ^2.0.0 => 2.0.19 
    gatsby-image: ^2.0.13 => 2.0.13 
    gatsby-plugin-algolia: ^0.2.0 => 0.2.0 
    gatsby-plugin-create-client-paths: ^2.0.0 => 2.0.0 
    gatsby-plugin-emotion: ^2.0.5 => 2.0.5 
    gatsby-plugin-eslint: ^2.0.1 => 2.0.1 
    gatsby-plugin-google-analytics: ^2.0.6 => 2.0.6 
    gatsby-plugin-manifest: ^2.0.2 => 2.0.4 
    gatsby-plugin-netlify: ^2.0.1 => 2.0.1 
    gatsby-plugin-nprogress: ^2.0.5 => 2.0.5 
    gatsby-plugin-offline: ^2.0.5 => 2.0.5 
    gatsby-plugin-prefetch-google-fonts: ^1.0.11 => 1.0.11 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-sharp: ^2.0.6 => 2.0.6 
    gatsby-plugin-tailwindcss: ^1.0.3 => 1.0.3 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-source-filesystem: ^2.0.5 => 2.0.5 
    gatsby-transformer-sharp: ^2.1.3 => 2.1.3 
  npmGlobalPackages:
    gatsby-cli: 2.4.2

**Comment by pilniczek** [comment]
Hi! Any changes? I am facing the same issue now.
