### ISSUE TITLE
Search bar not showing full placeholder!

### ISSUE THREAD

**Issue by aesthytik** [gatsbyjs/gatsby#9694]
## Description

I noticed a little CSS padding problem on placeholder text at search bar

### Steps to reproduce

Open the homepage of gatsby.

### Expected result

Search placeholder should be visible fully
![gatsbyjs](https://user-images.githubusercontent.com/26917061/47968225-d0ec7200-e08c-11e8-8f74-6a818525d090.png)

### Actual result

Placeholder not fully shown.

### Environment

I am using Ubnuntu 16.04 on google chrome browser

Run `gatsby info --clipboard` in your project directory and paste the output here. Not working? You may need to update your global gatsby-cli - `npm install -g gatsby-cli`

**Comment by kakadiadarpan** [comment]
@aesthytik I'm unable to reproduce this in my machine. This might be different for screens with different resolutions. Would you be interested in fixing this issue and raise a PR for it?

**Comment by aesthytik** [comment]
sure i will do a PR, after fixing it @kakadiadarpan

**Comment by tvthatsme** [comment]
I am seeing this using Chrome on Mac.

![image](https://user-images.githubusercontent.com/3386714/50047455-d8546180-00b5-11e9-88af-a43e0b3bb37b.png)

@aesthytik have you been able to find the fix for this? I'm guessing that these are related.

**Comment by aesthytik** [comment]
@tvthatsme yeah that's the same issue! Its not fixed yet

**Comment by nikosolihin** [comment]
I can't seem to reproduce the issue too. Strange!

**Comment by mperrien** [comment]
I have exact same thing as @aesthytik, but only for a short moment, probably the time for the font (FuturaPT) to load (FOUT). Maybe those of you who have the persistent problem are blocking custom fonts?

**Comment by parammittal16** [comment]
@aesthytik I want to work on this issue as this is my first contribution here. May I?

**Comment by parammittal16** [comment]
![capture2](https://user-images.githubusercontent.com/31361983/52911998-58bf5a80-32d1-11e9-80a4-88d4be58466a.PNG)
![capture](https://user-images.githubusercontent.com/31361983/52912001-607eff00-32d1-11e9-9d08-16aec5b74da3.PNG)

Looks there is a problem in home page as well as other pages too.
Plz can I try to solve it ?

**Comment by yogeshkotadiya** [comment]
Seems like a padding issue on chrome.
**Chrome 72:**
![chrome](https://user-images.githubusercontent.com/9676379/52915891-583db880-32ff-11e9-9e86-8fd4580af1f9.png)

**Firefox 65:**
![firefox](https://user-images.githubusercontent.com/9676379/52915894-5b38a900-32ff-11e9-9c27-7eefb3295847.png)

I can land a PR if no one has picked up yet.

**Comment by parammittal16** [comment]
@yogeshkotadiya I am doing it before and will be opening a PR once @aesthytik replies. You can find more issues.

**Comment by yogeshkotadiya** [comment]
Then go for it, You don't have to wait for such a small PR.
