### ISSUE TITLE
gatsby-source-wordpress title field includes "&nbsp; " in titles of certain length

### ISSUE THREAD

**Issue by foggy1** [gatsbyjs/gatsby#9702]
## Description

(Note: the following applies to wordpress.com source. This has not been tested with a self-hosted .org).

When the `gatsby-source-wordpress` plugin sources the `title` field from `posts`, if the post is beyond a certain number of characters, then eventually its final space will be replaced with `&nbsp;`

### Steps to reproduce

1. Spin up a vanilla gatsby project that uses `gatsby-source-wordpress` (preferably a .com site).
2. Make some test posts. The default post in a WP instance is "The Journey Begins". Make another one called "Testing an Open Letter."
3. Build your site.
4. Go to the GraphiQL interface and check the following query:
```
 allWordpressPost {
    edges {
      node {
        title
      }
    }
  }
```
5. Note that "The Journey Begins" is fine but that "Testing an Open Letter" appears in the interface as `Testing an Open&nbsp;Letter`

### Expected result

`&nbsp;` should not be appearing in something meant to be fed into the front-end (this is a Wordpress opinion and should be abstracted away).

### Actual result

There was an `&nbsp;` in the title field of titles of a certain length (I haven't nailed down the exact length).

### Environment

  System:
    OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: x64 Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 9.11.2 - /usr/bin/node
    Yarn: 1.12.1 - /usr/bin/yarn
    npm: 6.4.1 - /usr/bin/npm
  Browsers:
    Firefox: 60.3.0
  npmPackages:
    gatsby: ^2.0.0 => 2.0.31 
    gatsby-image: ^2.0.17 => 2.0.17 
    gatsby-link: ^2.0.5 => 2.0.5 
    gatsby-plugin-favicon: ^3.1.4 => 3.1.4 
    gatsby-plugin-manifest: ^2.0.6 => 2.0.6 
    gatsby-plugin-offline: ^2.0.9 => 2.0.9 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-sharp: ^2.0.8 => 2.0.8 
    gatsby-plugin-sitemap: ^2.0.2 => 2.0.2 
    gatsby-remark-images: ^2.0.4 => 2.0.4 
    gatsby-source-filesystem: ^2.0.5 => 2.0.5 
    gatsby-source-wordpress: ^3.0.9 => 3.0.9 
    gatsby-transformer-remark: ^2.1.9 => 2.1.9 
    gatsby-transformer-sharp: ^2.1.5 => 2.1.5 
  npmGlobalPackages:
    gatsby-cli: 2.4.4

**Comment by btk** [comment]
I'm not sure why this happens but if you check the starter projects, you will see wordpress titles always inserted into elements as HTML like;

```HTML
<h1 dangerouslySetInnerHTML={{ __html: post.title }} />
```

The intended use of the titles is probably this. Can you check and confirm?

**Comment by omerg** [comment]
I think it's a WordPress issue. I have the same problem and when I try the query on developer.wordpress.com, completely isolated from gatsby, nbsp is visible there also.

**Comment by zakirsajib** [comment]
it can be fixed using this:
`<div dangerouslySetInnerHTML={{ __html: post.title}}/>`

Live example: https://nirvana.netlify.com/

Its pulling data from Wordpress.com.
