### ISSUE TITLE
source and transform nodes never ends

### ISSUE THREAD

**Issue by RobinHerzog** [gatsbyjs/gatsby#9706]
## Description

On GatsbyV2 with Prismic CMS the "source and transform nodes" never ends. When I check "gatsby-source-filesystem" in cache directory, two files are still in tmp. 

Here is a screenshot
https://www.dropbox.com/s/1yjpelji7kb12pa/Capture%20d%27%C3%A9cran%202018-11-05%2012.15.33.png?dl=0

### Steps to reproduce

Run gatsby develop

### Expected result

Continue to build.

### Actual result

Stop to build

### Environment

  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.0.0 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.77
    Firefox: 61.0.1
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.25 => 2.0.25
    gatsby-cli: ^2.4.3 => 2.4.3
    gatsby-image: ^2.0.15 => 2.0.15
    gatsby-plugin-canonical-urls: ^2.0.6 => 2.0.6
    gatsby-plugin-favicon: ^3.1.4 => 3.1.4
    gatsby-plugin-google-analytics: ^2.0.6 => 2.0.6
    gatsby-plugin-google-fonts: 0.0.4 => 0.0.4
    gatsby-plugin-google-tagmanager: ^2.0.5 => 2.0.5
    gatsby-plugin-nprogress: ^2.0.5 => 2.0.5
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^2.0.7 => 2.0.7
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.1
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.0
    gatsby-source-filesystem: ^2.0.4 => 2.0.4
    gatsby-source-prismic: ^2.0.0 => 2.0.0
    gatsby-transformer-sharp: ^2.1.4 => 2.1.4
  npmGlobalPackages:
    gatsby-cli: 2.4.4

**Comment by kakadiadarpan** [comment]
@RobinHerzog this issue has been observed by more people. Please follow #6654 for updates regarding this.

**Comment by r1q** [comment]
I know its closed but In my case when i tried all solutions and nothing seems to fix it .. the only thing that worked was:

**Resizing the Terminal window !!** when it gets stuck.

**Comment by lewislbr** [comment]
@r1q that works for me too 😐

**Comment by RashaMou** [comment]
I got stuck there and can't believe this solution worked.

**Comment by soosgyul** [comment]
> I know its closed but In my case when i tried all solutions and nothing seems to fix it .. the only thing that worked was:
> 
> **Resizing the Terminal window !!** when it gets stuck.

Thank you! :)

**Comment by s-kris** [comment]
> I know its closed but In my case when i tried all solutions and nothing seems to fix it .. the only thing that worked was:
> 
> **Resizing the Terminal window !!** when it gets stuck.

This is weird but actually works. Yes, resizing the terminal window worked! Thank you :)

**Comment by tolumide-ng** [comment]
> I know its closed but In my case when i tried all solutions and nothing seems to fix it .. the only thing that worked was:
> 
> **Resizing the Terminal window !!** when it gets stuck.

such a weird solution 😆 Who would have thought
