### ISSUE TITLE
Building Static HTML - WebpackError: Invariant Violation: Minified React error #152

### ISSUE THREAD

**Issue by pedrotavaresgoncalves** [gatsbyjs/gatsby#9707]
## Description

---
**During build on building static HTML get error:**

```
8 |  else
   9 |          root["lib"] = factory(root["@reach/router"], root["core-js/modules/es6.array.sort"], root["fs"], root["lodash"], root["path"], root["react"], root["react-dom/server"], root["react-helmet"]);
> 10 | })(this, function(__WEBPACK_EXTERNAL_MODULE__reach_router__, __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_array_sort__, __WEBPACK_EXTERNAL_MODULE_fs__, __WEBPACK_EXTERNAL_MODULE_lodash__, __WEBPACK_EXTERNAL_MODULE_path__, __WEBPACK_EXTERNAL_MODULE_react__, __WEBPACK_EXTERNAL_MODULE_react_dom_server__, __WEBPACK_EXTERNAL_MODULE_react_helmet__) {
     |  ^
  11 | return


  WebpackError: Invariant Violation: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=Component for the f  ull message or use the non-minified dev environment for full errors and additional helpful warnings.
```

---
Tried to update versions of react-helmet and react-plugin-helmet. Didn't work. Erased all the traces of react-helmet and the error was gone, but appeared a similar error with lodash ( Invariant Violation: Minified React error #152) right after that only was referenced in package-lock.json. Tried install in package.json lodash and gatsby-plugin lodash with no success. In develop mode, as expected, everything works.

### Steps to reproduce

**My package.json**
```json
// package.json
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "firebase": "^5.5.3",
    "gatsby": "2.0.19",
    "gatsby-image": "^2.0.19",
    "gatsby-plugin-lodash": "^3.0.2",
    "gatsby-plugin-manifest": "2.0.2",
    "gatsby-plugin-offline": "2.0.5",
    "gatsby-plugin-react-helmet": "^3.0.1",
    "gatsby-plugin-sass": "2.0.1",
    "gatsby-plugin-sharp": "2.0.6",
    "gatsby-plugin-typography": "^2.2.0",
    "gatsby-source-filesystem": "2.0.1",
    "gatsby-transformer-json": "2.1.2",
    "gatsby-transformer-remark": "2.1.3",
    "gatsby-transformer-sharp": "2.1.3",
    "lodash": "^4.17.11",
    "node-sass": "4.9.3",
    "react": "16.5.1",
    "react-dom": "16.5.1",
    "react-helmet": "^5.2.0",
    "react-typography": "^0.16.13",
    "typography": "0.16.17",
    "typography-theme-bootstrap": "0.16.7",
    "typography-theme-lawton": "0.15.10"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write '**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "prettier": "^1.14.2"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  }
}
```
**My gatsby-config:**
```js
// gatsby-config.js
module.exports = {
  siteMetadata: {
    title: 'alive vision',
  },
  plugins: [
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: 'gatsby-starter-default',
        short_name: 'starter',
        start_url: '/',
        background_color: '#663399',
        theme_color: '#663399',
        display: 'minimal-ui',
        icon: 'src/images/gatsby-icon.png', 
      },
    },
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-lodash',
    'gatsby-plugin-offline',
    'gatsby-plugin-sharp',
    'gatsby-transformer-sharp',
    `gatsby-plugin-sass`,
    `gatsby-transformer-remark`,
    `gatsby-transformer-json`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `src`,
        path: `${__dirname}/src/`,
      },
    },
    {
      resolve: `gatsby-plugin-typography`,
      options: {
        pathToConfigModule: `src/utils/typography.js`,
      },
    },



  ],
}
```
**My gatsby-node:**

```js
// gatsby-node.js
const locales = require ('./src/utils/constants/locales');
const path = require (`path`);

exports.createPages = ({graphql, actions}) => {
  const {createPage} = actions;
  return new Promise ((resolve, reject) => {
    graphql (
      `
      {
  allMarkdownRemark{
    edges{
      node{
        id
        frontmatter {
          title,
          path,
          folderName
        }
      }
    }
  }
}
    `
    ).then (result => {
      result.data.allMarkdownRemark.edges.forEach (({node}) => {
        Object.keys (locales).map (lang => {
          const localizedPath = locales[lang].default
            ? node.frontmatter.path
            : locales[lang].path + node.frontmatter.path;

          return createPage ({
            path: localizedPath,

            //TODO: dynamic loading of template according to frontmatter

            component: path.resolve (`./src/templates/case.js`),
            context: {
              locale: lang,
              folderName: node.frontmatter.folderName,
            },
          });
        });
      });
      resolve ();
    });
  });
};

exports.onCreatePage = ({page, actions}) => {
  const {createPage, deletePage} = actions;

  return new Promise (resolve => {
    deletePage (page);

    Object.keys (locales).map (lang => {
      const localizedPath = locales[lang].default
        ? page.path
        : locales[lang].path + page.path;

      return createPage ({
        ...page,
        path: localizedPath,
        context: {
          locale: lang,
        },
      });
    });

    resolve ();
  });
};

exports.onCreateWebpackConfig = ({actions, stage}) => {
  if (stage === 'build-html') {
    actions.setWebpackConfig ({
      module: {
        rules: [
          {
            test: /firebase/,
            use: ['null-loader'],
          },
        ],
      },
    });
  }
};
```

### Expected result

Project should build 

### Actual result

Project build fails on building static HTML - WebpackError: Invariant Violation: Minified React error #152
### Environment

  System:
    OS: macOS 10.14
    CPU: x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.0.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.77
    Firefox: 60.0.2
    Safari: 12.0
  npmPackages:
    gatsby: 2.0.19 => 2.0.19
    gatsby-image: ^2.0.19 => 2.0.19
    gatsby-plugin-lodash: ^3.0.2 => 3.0.2
    gatsby-plugin-manifest: 2.0.2 => 2.0.2
    gatsby-plugin-offline: 2.0.5 => 2.0.5
    gatsby-plugin-react-helmet: ^3.0.1 => 3.0.1
    gatsby-plugin-sass: 2.0.1 => 2.0.1
    gatsby-plugin-sharp: 2.0.6 => 2.0.6
    gatsby-plugin-typography: ^2.2.0 => 2.2.0
    gatsby-source-filesystem: 2.0.1 => 2.0.1
    gatsby-transformer-json: 2.1.2 => 2.1.2
    gatsby-transformer-remark: 2.1.3 => 2.1.3
    gatsby-transformer-sharp: 2.1.3 => 2.1.3
  npmGlobalPackages:
    gatsby-cli: 2.4.4

**Comment by kakadiadarpan** [comment]
@pedrotavaresgoncalves React error `#152` says the following:
```
Component(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
```

Can you once check if no component is returning nothing from render? It would be great if you could share a reproduction repository for this issue.

**Comment by pedrotavaresgoncalves** [comment]
@kakadiadarpan I checked every component before. Now I went even further, abandoned implicit return and made all returns in React explicit.

Still no work 


Here's the repo

https://github.com/pedrotavaresgoncalves/gatsby-debug

**Comment by pedrotavaresgoncalves** [comment]
install instructions:
1)npm install --save firebase --build-from-source
2)npm install --save gatsby@2.0.19
3)npm install --save gatsby-plugin-sharp@2.0.6 --build-from-source
4)npm install --save gatsby-transformer-sharp@2.1.3
5) npm install

**Comment by pedrotavaresgoncalves** [comment]
Just to let you know. 
npm install problems disappear with downgrading to older versions os Node (tested with 10 and 8).

build problems don't disappear with downgrading node or updating gatsby and react to latest versions.

  System:
    OS: macOS 10.14
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
  Browsers:
    Chrome: 70.0.3538.77
    Firefox: 60.0.2
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.40 => 2.0.40 
    gatsby-cli: ^2.4.4 => 2.4.4 
    gatsby-image: ^2.0.19 => 2.0.19 
    gatsby-plugin-lodash: ^3.0.2 => 3.0.2 
    gatsby-plugin-manifest: 2.0.2 => 2.0.2 
    gatsby-plugin-offline: 2.0.5 => 2.0.5 
    gatsby-plugin-react-helmet: ^3.0.1 => 3.0.1 
    gatsby-plugin-sass: 2.0.1 => 2.0.1 
    gatsby-plugin-sharp: ^2.0.6 => 2.0.6 
    gatsby-plugin-typography: ^2.2.0 => 2.2.0 
    gatsby-source-filesystem: 2.0.1 => 2.0.1 
    gatsby-transformer-json: 2.1.2 => 2.1.2 
    gatsby-transformer-remark: 2.1.3 => 2.1.3 
    gatsby-transformer-sharp: ^2.1.3 => 2.1.3 
  npmGlobalPackages:
    gatsby-cli: 2.4.4

With this specs I can build in dev but still not for production

**Comment by pedrotavaresgoncalves** [comment]
In my repo took firebase credentials out for privacy reasons . To develop,  a firebase test account is needed.

**Comment by pedrotavaresgoncalves** [comment]
Solved it. 

if (typeof window !== `undefined`) {
  const module = require("module")
}

badly formulated was messing the return statement of a template.  

Thanks for the help guys

**Comment by talves** [comment]
Reference: [StackOverflow Answer](https://stackoverflow.com/questions/53192688/building-static-html-webpackerror-invariant-violation-minified-react-error/53193338#53193338)

I am wondering if there is a way to expose the culprit when running `gatsby build`, because in some cases (not this case), the error could have been caused by environment issues that would not show up during `gatsby develop`. I know this is more an issue with the static building of pages.

**Comment by arnauguadall** [comment]
> Solved it.
> 
> if (typeof window !== `undefined`) {
> const module = require("module")
> }
> 
> badly formulated was messing the return statement of a template.
> 
> Thanks for the help guys

Where did you include this piece of code?
Thanks!

**Comment by cedricwang28** [comment]
I removed all comments within my JSX section and everything is fine now
