### ISSUE TITLE
.org redesign: homepage "ecosystem" section design

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#9709]
Create designs teasing the new "Ecosystem" section on the gatsbyjs.org homepage.

**Comment by fk** [comment]
Desktop:
<img width="1280" alt="desktop_ homepage_ ecosystem" src="https://user-images.githubusercontent.com/21834/48003994-451c2980-e110-11e8-8ac6-9eef98fd8468.png">

Tablet (WIP, we have to figure out how cards should behave here):
<img width="1024" alt="tablet_ homepage_ ecosystem" src="https://user-images.githubusercontent.com/21834/48004214-dc817c80-e110-11e8-87df-823aed950278.png">

Mobile:
<img width="360" alt="mobile_ homepage_ ecosystem" src="https://user-images.githubusercontent.com/21834/48004211-d8edf580-e110-11e8-9d50-45200df89588.png">

**Comment by amberleyromo** [comment]
Considering design closed -- PR for review in https://github.com/gatsbyjs/gatsby/pull/9783
