### ISSUE TITLE
Gatsby Contentful Source Plugin Issue

### ISSUE THREAD

**Issue by SamFrampton01** [gatsbyjs/gatsby#9712]
Hi, 

I have run into an issue when trying to build a contentful-gatsby the website. 

** Apologise if this has been answered before / I am new to Node.JS and a Gatsby novice. 

I added the gatsby plug to the config.js file and post inserting space ID and access token Gatsby build did not launch my website. I tried looking at previous documentation but can't quite see a solution at the moment. 

Gatsby Version: 2.4.4
OS version: 10.13.6
Node Version: v10.13.0

- I installed Gatsby with sudo npm install --global gatsby-cli.
- new gatsby-site.
- npm -i S gatsby-source-contentful.
- I then went to the gatsby-config.js file to insert my contentful space ID and auth-token. 
- I then tried to run gatsby develop and ran into the following problem. 

I have attached the contents of relevant files as a zip file below. 

When I run `gatsby develop` I get the following traceback `TypeError: entryItemFields[foreignReference.name].push is not a function`

```
TypeError: entryItemFields[foreignReference.name].push is not a function
  
  - normalize.js:331 foreignReferences.forEach.foreignReference
    [blog-frontend]/[gatsby-source-contentful]/normalize.js:331:52
  
  - Array.forEach
  
  - normalize.js:327 entries.map.entryItem
    [blog-frontend]/[gatsby-source-contentful]/normalize.js:327:27
  
  - Array.map
  
  - normalize.js:274 locales.forEach.locale
    [blog-frontend]/[gatsby-source-contentful]/normalize.js:274:32
  
  - Array.forEach
  
  - normalize.js:251 Object.exports.createContentTypeNodes
    [blog-frontend]/[gatsby-source-contentful]/normalize.js:251:11
  
  - gatsby-node.js:163 contentTypeItems.forEach
    [blog-frontend]/[gatsby-source-contentful]/gatsby-node.js:163:17
  
  - Array.forEach
  
  - gatsby-node.js:162 Object.<anonymous>
    [blog-frontend]/[gatsby-source-contentful]/gatsby-node.js:162:22
  
  - Generator.next
  
  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18
  
  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10
  
  - promise.js:694 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18
  
  - async.js:138 _drainQueueStep
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:138:12
  
  - async.js:131 _drainQueue
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:131:9
  
  - async.js:147 Async._drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:147:5
  
  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:17:14
  

error UNHANDLED REJECTION


  TypeError: Cannot read property 'filter' of undefined
  
  - api-runner-node.js:287 Promise.mapSeries.catch.then.results
    [blog-frontend]/[gatsby]/dist/utils/api-runner-node.js:287:42
  
  - util.js:16 tryCatcher
    [blog-frontend]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [blog-frontend]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [blog-frontend]/[bluebird]/js/release/promise.js:569:18
  
  - promise.js:614 Promise._settlePromise0
    [blog-frontend]/[bluebird]/js/release/promise.js:614:10
  
  - promise.js:694 Promise._settlePromises
    [blog-frontend]/[bluebird]/js/release/promise.js:694:18
  
  - async.js:138 _drainQueueStep
    [blog-frontend]/[bluebird]/js/release/async.js:138:12
  
  - async.js:131 _drainQueue
    [blog-frontend]/[bluebird]/js/release/async.js:131:9
  
  - async.js:147 Async._drainQueues
    [blog-frontend]/[bluebird]/js/release/async.js:147:5
  
  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [blog-frontend]/[bluebird]/js/release/async.js:17:14
```

[Archive.zip](https://github.com/gatsbyjs/gatsby/files/2549239/Archive.zip)

**Comment by btk** [comment]
Hey there, welcome.

You have an "ls" at 16th line of your `gatsby-config.js` file. You probably tried to do `ls` command in your commandline and ended up typing and saving the file. That is probably the problem?

**Comment by SamFrampton01** [comment]
Hi, 

I removed `ls` command from `Gatsby-config.js`, but I still have the same issue unfortunately.

**Comment by btk** [comment]
Would you be able to pull the gatsby contentful starter and just plug your own credentials to see if your problem is caused by misconfiguration of your contentful, or some kind of syntax bug from your current implementation?

https://github.com/gatsbyjs/gatsby/tree/master/examples/using-contentful

**Comment by SamFrampton01** [comment]
Sure I'll try that now

**Comment by SamFrampton01** [comment]
Ok so I think you're right and it is a misconfiguration with my Contentful. 

This is what I got returned on my terminal. I've attached my config file in a zip file. 

![screen shot 2018-11-05 at 16 48 37](https://user-images.githubusercontent.com/40734207/48012778-b2cd5300-e11a-11e8-9973-0825a0845088.png)

[gatsby-config.js.zip](https://github.com/gatsbyjs/gatsby/files/2549674/gatsby-config.js.zip)

**Comment by btk** [comment]
Yeah, maybe you can follow up on this quick tutorial to see what you are missing: https://www.contentful.com/r/knowledgebase/gatsbyjs-and-contentful-in-five-minutes/

Maybe your space is empty, don't have any nodes?

**Comment by SamFrampton01** [comment]
Ok, thanks for the help. I will give this a try.

**Comment by andrezimpel** [comment]
> Hey there, welcome.
> 
> You have an "ls" at 16th line of your `gatsby-config.js` file. You probably tried to do `ls` command in your commandline and ended up typing and saving the file. That is probably the problem?

I just did that and still got the same error.

`TypeError: entryItemFields[foreignReference.name].push is not a function`

`normalize.js:331 foreignReferences.forEach.foreignReference
    [using-contentful]/[gatsby-source-contentful]/normalize.js:331:52`

**Comment by ryudice** [comment]
I'm having the same problem as well, after doing some changes to contentful schema, however the error message is not very helpful

**Comment by julessaysrawr** [comment]
I also has this issue, but I resolved it by changing the nested content model in contentful.  I was trying to figure out how to to a 'join' and my mistake was referencing a model like a foreign key while in a nested section of that model

simplified example:

employer
|
- people
     - name
     - { ... other details }
     - employer ❌ this is what broke it for me

by removing that reference, it worked fine.  i guess i shouldn't try to think about foreign keys or doing that kind of modeling because it is handled for me behind graphql.
