### ISSUE TITLE
External CSS is always imported in dev server app

### ISSUE THREAD

**Issue by valse** [gatsbyjs/gatsby#9713]
Hi,
   I'm adding a new page to my site that has a different layout.

It's easy with Gatsby v2 to do it but even if I'm using a different layout, the new imported CSS is included also in the other pages' header and not only in the new one.

```
import 'semantic-ui-css/semantic.min.css';
```

If I build the site all works fine but developing with this strange behavior is quite annoying.

A workaround is to include the new CSS by Helmet using a CDN url instead importing it.

Thanks
valse

**Comment by kakadiadarpan** [comment]
@valse I assume you are including the CSS in one specific layout and it is being loaded in the other as well?

**Comment by valse** [comment]
Yes exactly. I added a summary stat page using semantic UI for react but its CSS import is applied to other pages too...

**Comment by kakadiadarpan** [comment]
Currently, in dev mode, split chunk plugin is not enabled. Fixing that should resolve this issue. Please follow issue #8342 for more updates regarding this.

Closed in favor of #8342
