### ISSUE TITLE
Specific value in graphql query is undefined with gatsby-link or hot reload, but fine on manual reload

### ISSUE THREAD

**Issue by aofolts** [gatsbyjs/gatsby#9714]
## Description

When I visit the Home page, everything loads fine.

However, when I make a change to any files (which kicks off hot reload) or click a `gatsby-link`, a certain value in my query (via gatsby-source-contentful) becomes undefined.

### Steps to reproduce

Making file changes or clicking a `gatsby-link`.

* Changes to `.less` files do not cause an issue.

### Expected result

The `Index` component should receive `this.props.data.page.layout`.

### Actual result

The `Index` component receives all the expected values inside `this.props.data.page`, except for `layout`, which is undefined.

### Environment

  System:
    OS: macOS High Sierra 10.13.3
    CPU: x64 Intel(R) Core(TM) i7-3770S CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.12.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.77
    Firefox: 63.0.1
    Safari: 11.0.3
  npmPackages:
    gatsby: ^2.0.33 => 2.0.38 
    gatsby-image: ^2.0.18 => 2.0.19 
    gatsby-plugin-less: ^2.0.7 => 2.0.7 
    gatsby-plugin-manifest: ^2.0.7 => 2.0.7 
    gatsby-plugin-offline: ^2.0.10 => 2.0.11 
    gatsby-plugin-react-helmet: ^3.0.1 => 3.0.1 
    gatsby-plugin-sharp: ^2.0.10 => 2.0.11 
    gatsby-source-contentful: ^2.0.9 => 2.0.10 
    gatsby-transformer-remark: ^2.1.11 => 2.1.11 
    gatsby-transformer-sharp: ^2.1.7 => 2.1.7 
  npmGlobalPackages:
    gatsby-cli: 2.4.4

### Index.js

```
class Index extends Component {

  render() {
    const {
      data
    } = this.props

    const {
      page,
      testimonials
    } = data

    const {
      introHeadline,
      introParagraph,
      introHeadshot,
      services
    } = page.layout

    return (
      <Fragment>
        <Intro
          headline={introHeadline}
          paragraph={introParagraph}
          headshot={introHeadshot}
        />
        <ServicesSection services={services} />
        <Testimonials entries={testimonials.edges.map(entry => entry.node)}/>
      </Fragment>
    )
  }
}

export default withLayout(Index)

export const query = graphql`
  {
    page: contentfulPage(slug: {eq: "home"}) {
      ...pageInfo
      ...pageFeaturedImage
      ...homePageLayout
    }
    testimonials: allContentfulTestimonial(limit: 3) {
      edges {
        node {
          ...testimonial
        }
      }
    }
  }
`

export const homePageLayoutFragment = graphql`
  fragment homePageLayout on ContentfulPage {
    layout {
      introHeadline
      introParagraph
      introHeadshot {
        ...imageMeta
        sizes: fluid(maxWidth: 1000) {
          ...imageSizes
        }
      }
      services {
        ...serviceInfo
        content {
          childMarkdownRemark {
            excerpt(pruneLength: 160)
          }
        }
      }
    }
  }
`
```

**Comment by aofolts** [comment]
**Update**

So I've traced the problem back to the use of "layout" in the fragment.

If I change this to `layout2: layout`, the data is passed properly. Not sure what the exact problem is, but I'll continue to investigate.

**Comment by pieh** [comment]
The `layout` find is pretty weird (I couldn't find any code that would have special handling for `layout` field) - would you be able to provide reproduction repository for this problem?

**Comment by aofolts** [comment]
@pieh Here's the repo: [aofolts/connecting-core](https://github.com/aofolts/connecting-core)

Maybe there's something super-obvious, but if not and you want to run it, let me know and I'll create a Contentful access token for you.

**Comment by aofolts** [comment]
I solved the problem. I was using a HOC named "withLayout" which was mutating the layout property in `data` then passing it to `Layout` and then `Index`.

For whatever reason, this was causing the layout property to become undefined on hot reload or when I clicked a `gatsby-link`.

**Comment by aofolts** [comment]
I solved the problem. I was using a HOC named "withLayout" which was mutating the layout property in data then passing it to Layout and then Index.

For whatever reason, this was causing the layout property to become undefined on hot reload or when I clicked a gatsby-link.
