### ISSUE TITLE
gatsby-plugin-lodash with gatsby v2 not working

### ISSUE THREAD

**Issue by yjacobowitz** [gatsbyjs/gatsby#9715]
## Description

When trying to migrate gatsby from v1 to v2 and running `gatsby build`  I receive an error in lodash. When running `gatsby develop` I do not have this issue.
### Steps to reproduce

Following the instructions from gatsby-plugin-lodash README and running `gatsby build`.

### Expected result

Should be able to use lodash everywhere in the app without having to import it.

### Actual result

> WebpackError: ReferenceError: _ is not defined

### Environment

System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.12.0 - ~/.nvm/versions/node/v10.12.0/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v10.12.0/bin/npm
  Browsers:
    Chrome: 70.0.3538.77
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.38 => 2.0.38
    gatsby-image: ^2.0.19 => 2.0.19
    gatsby-link: ^2.0.6 => 2.0.6
    gatsby-plugin-compression: 0.0.1 => 0.0.1
    gatsby-plugin-emotion: ^2.0.6 => 2.0.6
    gatsby-plugin-fastclick: ^1.0.1 => 1.0.1
    gatsby-plugin-fullstory: ^2.0.1 => 2.0.1
    gatsby-plugin-google-fonts: 0.0.4 => 0.0.4
    gatsby-plugin-lodash: ^3.0.2 => 3.0.2
    gatsby-plugin-nprogress: ^2.0.6 => 2.0.6
    gatsby-plugin-offline: ^2.0.11 => 2.0.11
    gatsby-plugin-react-css-modules: ^2.0.3 => 2.0.3
    gatsby-plugin-react-helmet: ^3.0.1 => 3.0.1
    gatsby-plugin-react-svg: ^2.0.0-beta1 => 2.0.0
    gatsby-plugin-sass: ^2.0.3 => 2.0.3
    gatsby-plugin-sharp: ^2.0.11 => 2.0.11
    gatsby-plugin-typography: ^2.2.1 => 2.2.1
    gatsby-react-router-scroll: ^2.0.1 => 2.0.1
    gatsby-source-filesystem: ^2.0.7 => 2.0.7
    gatsby-transformer-sharp: ^2.1.7 => 2.1.7

**Comment by kakadiadarpan** [comment]
@yjacobowitz can you share the reproduction repo for this issue?

**Comment by yjacobowitz** [comment]
I just took one of the examples from the gatsby repository (using-sass) and added the plugin:
https://github.com/yjacobowitz/GatsbyWithLodash

**Comment by kmorf** [comment]
In your index.js you are not importing lodash, hence the failing

`import _ from 'lodash'`

**Comment by yjacobowitz** [comment]
@kmorf In v1 of the plugin, there was no need to import lodash, is this a new change in v2? If so, what is the difference between using the plugin and just importing lodash?

**Comment by yjacobowitz** [comment]
Got it! In v1 there was no need to import lodash, is this a change that will be added to v2?

**Comment by yjacobowitz** [comment]
Got it! In v1 there was no need to import lodash, will this be added to v2?

**Comment by kmorf** [comment]
Not sure I understand your question. It doesn't have to be added to v2 since it is a separate utility library, but users can add it manually.

**Comment by yjacobowitz** [comment]
In v1 there was no need to manually import lodash in every js file, you were able to use it seamlessly without adding the line `import _ from ‘lodash’`. This change requires me to add the line to every js file in my code, while before it was not required.

**Comment by kakadiadarpan** [comment]
@yjacobowitz I hope your question is answered. Feel free to reopen if you need more help.
