### ISSUE TITLE
 Error: Cannot find module '@reach/router'

### ISSUE THREAD

**Issue by muhammadnaveel** [gatsbyjs/gatsby#9722]
my gatsby was running perfectly. I add some npm packages and removed the node_modules folder and reinstall npm install. I am facing errror while run gatsby build.  

```
D:\Project Data\Development\webpack-starter\gulf-coast\gulf-coast-site>gatsby develop
success open and validate gatsby-configs - 0.022 s
success load plugins - 0.708 s
success onPreInit - 2.325 s
success delete html and css files from previous builds - 0.024 s
success initialize cache - 0.081 s
success copy gatsby files - 0.233 s
success onPreBootstrap - 0.036 s
success source and transform nodes - 0.910 s
success building schema - 1.046 s
success createPages - 0.004 s
success createPagesStatefully - 0.260 s
success onPreExtractQueries - 0.020 s
success update schema - 0.737 s
error There was a problem parsing "D:/Project Data/Development/webpack-starter/gulf-coast/gulf-coast-site/src/components/layout.js"; any GraphQL
fragments or queries in this file were not processed.
This may indicate a syntax error in the code, or it may be a file type that Gatsby does not know how to parse.
success extract queries from components - 0.563 s
success run graphql queries - 0.777 s - 13/13 16.80 queries/second
success write out page data - 0.102 s
success write out redirect data - 0.003 s
Generating image thumbnails [==============================] 6/6 0.9 secs 100%

info bootstrap finished - 20.607 s

? onPostBootstrapdone generating icons for manifest
success onPostBootstrap - 0.286 s
error UNHANDLED REJECTION


  Error: Cannot find module '@reach/router'

  - module.js:11 require
    internal/module.js:11:18

  - render-page.js:3 webpackUniversalModuleDefinition
    D:/Project Data/Development/webpack-starter/gulf-coast/gulf-coast-site/public/render-page.js:3:28

  - render-page.js:10 Object.<anonymous>
    D:/Project Data/Development/webpack-starter/gulf-coast/gulf-coast-site/public/render-page.js:10:3

  - module.js:11 require
    internal/module.js:11:18

  - worker.js:32 Promise
    [gulf-coast-site]/[gatsby]/dist/utils/worker.js:32:35

  - debuggability.js:313 Promise._execute
    [gulf-coast-site]/[bluebird]/js/release/debuggability.js:313:9

  - promise.js:483 Promise._resolveFromExecutor
    [gulf-coast-site]/[bluebird]/js/release/promise.js:483:18

```

### Environment

I updated npm install -g gatsby-cli` and facing problem on this too.

  System:
    OS: Windows 7
    CPU: x64 Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz
  Binaries:
    npm: 5.2.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    gatsby: ^2.0.19 => 2.0.38
    gatsby-image: ^2.0.15 => 2.0.19
    gatsby-link: ^2.0.6 => 2.0.6
    gatsby-plugin-manifest: ^2.0.5 => 2.0.7
    gatsby-plugin-offline: ^2.0.5 => 2.0.11
    gatsby-plugin-react-helmet: ^3.0.1 => 3.0.1
    gatsby-plugin-sharp: ^2.0.7 => 2.0.11
    gatsby-source-filesystem: ^2.0.4 => 2.0.7
    gatsby-transformer-sharp: ^2.1.4 => 2.1.7

error The system cannot find the path specified.

  Error: The system cannot find the path specified.

  - envinfo.js:1 Function.e.exports.sync
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:7796

  - envinfo.js:1 Object.copySync
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:114275

  - envinfo.js:1 Object.t.writeSync.e [as writeSync]
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:132801

  - envinfo.js:1
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:133568

  - envinfo.js:1 Promise.all.then.e
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:133583

  - util.js:16 tryCatcher
    [npm]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

  - promise.js:638 Promise._fulfill
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

error UNHANDLED REJECTION

  Error: The system cannot find the path specified.

  - envinfo.js:1 Function.e.exports.sync
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:7796

  - envinfo.js:1 Object.copySync
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:114275

  - envinfo.js:1 Object.t.writeSync.e [as writeSync]
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:132801

  - envinfo.js:1
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:133568

  - envinfo.js:1 Promise.all.then.e
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:133583

  - util.js:16 tryCatcher
    [npm]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

  - promise.js:638 Promise._fulfill
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

**Comment by muhammadnaveel** [comment]
@kakadiadarpan did as per your instructions. same error coming..

**Comment by choihomeboy** [comment]
If anyone has same issue, do

yarn add @reach/router

**Comment by Emmanuel96** [comment]
Thank @choihomeboy . For anyone using nom, you could just do 

npm install @reach/router --legacy-peer-deps

If it gives any more error, keep repeating this for the missing packages. 

It worked for me, I hope it it works for you.
