### ISSUE TITLE
dunno how to use 'gatsby-plugin-layout'...

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#9723]
I have made a site using Gatsby V2 and have gotten to the point of adding view transitions and now I'm running up against the 'pages' wall, where everything re-renders due to Gatsby V2 being page based, rather than view based.

So, I'm trying to use 'gatsby-plugin-layout' but I really don't know how to use it at all and the documentation for the plugin is really minimal, rather than being a full tutorial on how to use it properly.

A few questions:

1. I'm supposed to make an `index.js` file inside of a folder named `layouts`, but then I also have to have a file named `index.js` in my `pages` folder?
2. Why do I have to use this name twice? That seems a little...odd? I changed the name of the `index.js` file in the `pages` folder to `home.js` and the compiler yelled at me, so I changed it back, but then I'm running into a new issue with graphql, where I get this error:

```bash
GraphQL Error There was an error while compiling your site's GraphQL queries.
  Invariant Violation: GraphQLCompilerContext: Duplicate document named `SiteTitleQuery`. GraphQL fragments and roots must have unique names.
    t: Duplicate document named `SiteTitleQuery`. GraphQL fragments and roots must have unique names.
```
Dunno what this means really, but in my layout file I have a staticQuery, which I was under the impression could be used anywhere, no?

3. Is this when I'm supposed to use react context?
4. Can I put a graphql query inside of a context provider?
5. Is this the right approach?
6. Can I use a StaticQuery inside of the `index.js` layout file, which, for some reason, is not called `layout.js` or `app.js`?

I'm just really lost as to how to handle putting the is together and re-factoring this app using gatsby-plugin-layout.

@jlengstorf has been valiently trying to help me on the twitter, but I'm thinking more minds on this could certainly help, hence the GitHub issue.

Anyways, if anybody has some thoughts they would be much appreciated.

Thank you in advance XD

**Comment by DSchau** [comment]
> I'm supposed to make an index.js file inside of a folder named layouts, but then I also have to have a file named index.js in my pages folder?

layouts/index.js is a layout component, i.e. it will be a parent to any files/routes in pages. They're separate because pages are used for _routing_ whereas layouts/index.js wraps a page component, if that makes sense?

> index.js file in the pages folder to home.js

The name of the .js files in pages directly correspond to a route, so what you've created now is a route at /home. Probably want to keep it index, which follows the convention most familiar to people, I'd think!

> GraphQL Error There was an error while compiling your site's GraphQL queries

Sounds like you just need to rename the query. When you do something like the below

```graphql
query WhateverQuery {
  # your data
}
```

`WhateverQuery` needs to be unique in your Gatsby application. A convention I follow is naming by the route/type of thing, e.g. if using a static query in a component, `SomeComponentSiteMetadataQuery`, or if in a route, `IndexQuery`, `AboutQuery`, etc.


> Is this when I'm supposed to use react context?

I'd need more info here as to what you're trying to accomplish? Also I don't know what "this" refers to, exactly!

> Can I put a graphql query inside of a context provider?

What are you trying to do?

> Can I use a StaticQuery inside of the index.js layout file

Yep! StaticQuery is actually valid pretty much anywhere in src/, so feel free to use it where it makes most sense. In effect, StaticQuery is useful anywhere, wheras page queries (src/pages/about.js, src/pages/index.js) don't _have_ to use a StaticQuery, but they certainly can! Does that make sense?

Hopefully I answered most of them; thanks for opening the issue!

**Comment by rchrdnsh** [comment]
hmmmm...I'm prolly asking the wrong questions.

The thing is, I don't even know where to start...

I installed the `gatsby-plugin-layout` and added it to the config file, but from there I really have no idea how to refactor my V2 site to properly use the plugin. My site's architecture basically follows the V2 tutorial where I have a layout component and every page is wrapped with it, but when finally trying to add animations from one page to the next, the navigation in the layout component is animating as well, which should certainly not be happening. I then read that this is because the layout component is re-rendered on every route change, which is so so so not what I want to happen, so I found gatsby-plugin-layout, which supposedly makes persistent UI elements actually persist, rather then mess everything up. So now I'm trying to re-factor this V2 app into a V1 app basically? but I just don't know how to do that and every time I try something out I get a plethora of errors, without really having any clue what to do next, unfortunately.

This is where I'm at now, and really don't even know what step 1 is supposed to be.

Does that make sense?

**Comment by DSchau** [comment]
> I installed the gatsby-plugin-layout and added it to the config file, but from there I really have no idea how to refactor my V2 site to properly use the plugin

The general idea with that plugin is that you don't _have_ to refactor your layout component or page components to accommodate. It's generally used for some of the reasons you listed (e.g. keep page context, animations, etc.), but it's also provided to ease the migration path.

> So now I'm trying to re-factor this V2 app into a V1 app basically

Really, nothing needs to be re-factored! Generally, just keep things as is, follow the [migration guide](https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/) for upgrading breaking changes in v1 -> v2--although don't follow the layout change if you're using gatsby-plugin-layout--and you should be good to go!

I am guessing your issues are unrelated to layout plugin specifically. Do you have a reproduction or repo you could share? Or more specific errors would help, as well!

**Comment by rchrdnsh** [comment]
ah, crap buckets! The config file is not in the src folder...Im so dumb! Thank you @DSchau XD

Although, now I have two nav menus, which should not be happening...

<img width="1440" alt="screenshot 2018-11-05 15 36 54" src="https://user-images.githubusercontent.com/7884263/48033622-df7c6d00-e110-11e8-9648-4eb2e5a18fb2.png">

any thoughts as to why that might be? You have been very helpful so far, thank you! I've been wrapping my brain around this for days...

**Comment by DSchau** [comment]
@rchrdnsh are you kind of following a hybrid approach? My guess is you have imported the Layout component into various pages, when if you use gatsby-plugin-layout, you explicitly shouldn't wrap any pages!

**Comment by rchrdnsh** [comment]
ok, so liiiiiittle bit of refactoring then ;-P

k, so I replaced the `<Layout>` with `<div>` and this happened...

<img width="1440" alt="screenshot 2018-11-05 16 47 53" src="https://user-images.githubusercontent.com/7884263/48035914-df816a80-e11a-11e8-9363-434d95094464.png">

so that's no bueno, but then I was like...what about a fragment, like this `<>`...

then this happened:

<img width="1440" alt="screenshot 2018-11-05 16 52 14" src="https://user-images.githubusercontent.com/7884263/48035992-325b2200-e11b-11e8-95a8-972f79640d38.png">

Woo hoo!!!!!!

k, gonna try and work with this and see what happens, but that really was a whole bunch simpler then I thought it would be!

I'm thinking of doing a PR to make the docs better for that plugin, no?

and thank you again @DSchau and @jlengstorf!

**Comment by rchrdnsh** [comment]
I'll close this for now, hoping to not run into any more issues :-)

**Comment by jlengstorf** [comment]
Great news, @rchrdnsh — we'd love to get the docs updates to help people understand how all this works a bit better. Glad you got it worked out!

**Comment by rchrdnsh** [comment]
I need up deleting the node_modules folder manually and then running `npm install` in the project to re-install the goodies and it seems to be working again now...

Is this something that people do often? Is it a good idea? Is it safe to do?

**Comment by tretyakov-d** [comment]
Had the same issue. Solved.

by default gatsby-plugin-layout requires takes a component which is default export from  src/layouts/index

you can also specify location (still must be default export) but seems like there is an error in doc.

doc example: 
``` 
plugins: [
    {
      resolve: `gatsby-plugin-layout`,
      options: {
        component: require.resolve(`./relative/path/to/layout/component`),
      },
    },
  ],
```

the correct version (uses path.resolve, not require resolve) 

```
plugins: [
    {
      resolve: `gatsby-plugin-layout`,
      options: {
        component: require.resolve(`./relative/path/to/layout/component`),
      },
    },
  ],
```

ps obviously path is `import path from "path";`
