### ISSUE TITLE
.org redesign: ecosystem [content/copy]

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/gatsby#9724]
## Goal

As we're going through the .org redesign, we'll be updating the copy on each of the pages. We want to make sure that the right copy is listed for our community, and that the copy also fulfills our marketing goals.

The ecosystems landing page will be the starting place for people who are on gatsbyjs.org to learn more about Gatsby. We are featuring plugins, starters, and external resources on the ecosystem landing page. 

## Next steps
- @shannonbux: are there specific questions you've heard that we should be addressing in the copy for plugins, starters, and external resources (like tutorials, podcasts, articles, or the [Awesome Gatsby](https://www.gatsbyjs.org/docs/awesome-gatsby) page)?
- @lindaleebumblebee: is there specific marketing copy you'd like to highlight for plugins, starters, or external resources on the Ecosystems page?

**Comment by amberleyromo** [comment]
I took first stab at this independently, before we got a content/copy process going. Closing this via #9747.
