### ISSUE TITLE
.org redesign: homepage [content/copy] overview issue

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/gatsby#9725]
## Goal

As we're going through the .org redesign, we'll be updating the copy on each of the pages. We want to make sure that the right copy is listed for our community, and that the copy also fulfills our marketing goals.

The sections for the homepage will be: 
**Gatsby Explanation**
<img width="1969" alt="screenshot 2018-11-05 16 15 31" src="https://user-images.githubusercontent.com/13393126/48034890-0d17e500-e116-11e8-9cc1-70086b678ad5.png">

(diagram will be updated)

**Ecosystem section**
- [ ] Design: https://github.com/gatsbyjs/gatsby/issues/9709
- [ ] Content: https://github.com/gatsbyjs/gatsby/issues/9747
- [ ] Implementation: 

**Blog/Newsletter section**
- [ ] Design: https://github.com/gatsbyjs/gatsby/issues/9711
- [ ] Content: https://github.com/gatsbyjs/gatsby/issues/9744
- [ ] Implementation: 

## Next steps
- @shannonbux: are there specific questions you've heard that we should be addressing in the copy on the homepage? I'm guessing we'll get some ideas from the usability studies that you're currently running.
- @lindaleebumblebee: is there specific marketing copy we should highlight on the homepage that we don't currently have

**Comment by lindaleebumblebee** [comment]
Thanks @marisamorby We have the main points covered here but I'd like to talk through the messaging on this. Is there a meeting on the books to review the content/messaging for the .org homepage? Also, I've seen some comments go around about the image so I assume that's changing?

**Comment by fk** [comment]
@Linda First shot at a new diagram design and discussion here: https://github.com/gatsbyjs/gatsby/issues/9525

**Comment by marisamorby** [comment]
@lindaleebumblebee: There's not a meeting on the books for this yet. There's a separate issue for the diagram specifically on issue #9525. I thought I added you, but will do so now. We can log messaging, goals, and requirements for the diagram there. Thanks!

**Comment by lindaleebumblebee** [comment]
ok- I'm not sure if this is the latest discussion on this homepage image but I have a few comments:
- I'd like to add 'Bring your content from anywhere' in the 'data sources' section (can just replace it)
- isn't the GraphQL section before the build or at least powering the build? 
- I'd then list the build step via Gatsby with the output being static HTML
- Deploy should have some language around 'deploy to the edge/CDN' so it's clear it's not 'traditional hosting'
- I think all of this is best to discuss over a quick call. thanks!
