### ISSUE TITLE
.org redesign: docs [content/copy]

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/gatsby#9727]
## Goal

As we're going through the .org redesign, we'll be updating the copy on each of the pages. We want to make sure that the right copy is listed for our docs landing page, as a way to guide people and introduce them to the docs we have.

## Next steps
- @shannonbux: are there specific questions you've heard about general docs copy that we should consider as we're building out the docs page?
- @lindaleebumblebee: is there specific marketing copy we should highlight on the docs page?

**Comment by lindaleebumblebee** [comment]
I'll defer to Shannon on this as she does the research with the target audience for this page. The only thing we might want to add is a bit more of a description of what Gatsby is in case someone hits that page and doesn't know. But, leaving that final call up to @shannonbux  . If more description is needed, I suggest the following: 
Gatsby is a blazing fast modern site generator for React. Build performance into every website by leveraging the latest web technologies such as React, GraphQL, and modern Javascript.
