### ISSUE TITLE
CSS order messed up after build 

### ISSUE THREAD

**Issue by nzwnabdulwahid** [gatsbyjs/gatsby#9733]
Hi everyone, I have an issue where my css is either missing or order is messed up after I build. 
For example: 

This is the development one.
<img width="386" alt="screen shot 2018-11-06 at 12 26 42 pm" src="https://user-images.githubusercontent.com/15116775/48043042-65ef8800-e1bf-11e8-8e25-929c1e65c60d.png">

And this is one after I build
<img width="387" alt="screen shot 2018-11-06 at 12 26 56 pm" src="https://user-images.githubusercontent.com/15116775/48043050-743da400-e1bf-11e8-974d-f38d556b2912.png">

My way of working is I use traditional way of writing in CSS file and import './index.css' into my component.

Is there anything I can do to fix this? Thank you!

**Comment by kakadiadarpan** [comment]
@nzwnabdulwahid There are a couple of issues similar to this one #1836 & #6302. Also, #6302 has an open PR(#8092) which once merged should resolve this issue.

@DSchau @pieh should we merge these issues as they all are related to the ordering of the imported CSS(or SASS)?

**Comment by ExSoax** [comment]
Same here! In development i see everything right but after build all styles are messed...

**Comment by nzwnabdulwahid** [comment]
The only workaround I did for now is I make sure in my css I code to be more specific :

`.custom-button {
    background-color: green;
}`

 to 

`button.custom-button {
    background-color: green;
}`

just to make sure its sorted highest in css precedence level.

**Comment by maxlapides** [comment]
As far as I know, this issue still exists.

**Comment by ruipfreis** [comment]
Yes, still having the same issue.

**Comment by berkeleycole** [comment]
I am seeing this issue as well. I would have thought using CSS modules would protect from this, but there must be something I'm not understanding

**Comment by KyleAMathews** [comment]
I published a fix for this where we're not code splitting CSS which should solve the problems y'all are facing. Please update to gatsby@2.1.3 and lemme know if you're still having troubles!

https://github.com/gatsbyjs/gatsby/issues/11072

**Comment by lucasmarcelli** [comment]
Still have this issue in April 2019.

**Comment by rstacruz** [comment]
Same here with Gatsby 2.4

**Comment by rstacruz** [comment]
Some debugging notes:

I've encountered this too. I tried to do `gatsby build`, which generated `/public/webpack.stats.json`. I checked it out and found some warnings (not actual screenshot, sorry, I didn't take a screenshot when I encountered it):

![](https://user-images.githubusercontent.com/19804652/45082402-eaf7eb80-b101-11e8-9a6f-9eb60868fb05.png)

I found that whenever I was doing `import 'some-stylesheet.css'` (in my components or in `gatsby-browser.js`, [Gatsby's docs has some info on this](https://www.gatsbyjs.org/docs/creating-global-styles/)), they showed up there.

Related:

- https://www.gatsbyjs.org/docs/creating-global-styles/
- https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250

**Comment by rstacruz** [comment]
I've found another issue in my project: these CSS loader warnings are happening because there are pages that don't use the "global" layout, and I was importing CSS from the "global" layout. This will result in a different CSS order per page, depending on what page is used as the entry point.

**Comment by jketcham** [comment]
I was running into this issue on gatsby@2.3.5, but I'm pretty sure my cause was because I had followed the [instructions here](https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules) for replacing third party modules at build time with `null` effectively.

Well that module I was replacing includes it's own styles. In development everything worked great, I had my own styles that were overriding that modules styles. But in production, since that module gets skipped effectively, when it loads up in the browser, _then_ it's styles get imported (after all my other styles), so overriding wasn't working.

My current workaround isn't great but it works, I'm just adding `!important` to all of my overriding styles.

**Comment by joshuabaker** [comment]
@rstacruz _Thank you!_ 🙏

The import order was what was causing this for us.
