### ISSUE TITLE
Add Content / Copy for .org Homepage - Ecosystem section

### ISSUE THREAD

**Issue by amberleyromo** [gatsbyjs/gatsby#9747]
## Goal

As we're going through the .org redesign, we'll be updating the copy on each of the pages. We want to make sure that we have input and agreement on all sections of homepage copy.

## Next steps

We need to finalize the copy for the Ecosystem homepage section: https://github.com/gatsbyjs/gatsby/issues/9709

@shannonbux @lindaleebumblebee notable questions/needs include:
- The intro under "Plugins & Starters" doesn't exist yet
- The plugins / starters / external resources blurbs mirror https://www.gatsbyjs.org/ecosystem -- is there any reason you'd want them to be different, or is that fine.

### Needed copy
- [x] Main intro copy
  - With over 527 plugins, 86 starters, guides on how to build your own plugins and starters, and dozens of external tutorials and podcasts, the Gatsby ecosystem has tools to help you build your Gatsby projects.

### Approvals
- [x] @lindaleebumblebee 
- [ ] @shannonbux

**Comment by shannonbux** [comment]
I think the copy looks great. 

One question:
Upon first glance, I couldn't remember the difference between "plugin docs" and "plugin authoring." 

For the homepage overall intro, what about:

With over 527 plugins, 86 starters, guides on how to build your *own* plugins and starters, and dozens of external tutorials and podcasts, the Gatsby ecosystem has tools to help you build your Gatsby projects.

**Comment by amberleyromo** [comment]
What about "Using plugins" and "Creating plugins" instead? 

Moving the intro description to the top-level comment.

**Comment by shannonbux** [comment]
oh yeah, I like that!

**Comment by lindaleebumblebee** [comment]
Let's see how the text looks when it's in context (in the design). It might be a bit long. If so, I suggest this:
With over 527 plugins, 86 starters, and dozens of tutorials, the Gatsby ecosystem has tools to help you build your Gatsby projects.

**Comment by amberleyromo** [comment]
Thanks to you both! 

I'm going to mark this issue closed / consider copy final for the initial homepage PR.

**Comment by fk** [comment]
🙏
