### ISSUE TITLE
.org redesign: homepage [design] "hero/above the fold" section

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#9748]
<img width="1180" alt="hero" src="https://user-images.githubusercontent.com/21834/48087795-8a1f8900-e200-11e8-899d-d8c6546424df.png">

- claim with "rotating words" ("Build ______ apps and websites with React") remains
- "Get Started" CTA button stays
  - would like to suggest adding a secondary CTA button "Take the Tutorial" (similar to https://reactjs.org/)
- add a "Gatsby Preview" product teaser
- add newsletter signup form
- thinking about moving the "Used by" section out of the header; def. want to update the logos we show here, and add the possibility of showing more logos

I also want to suggest moving away from the current homepage background design—the 45° roated "Gatsby/rebeccapurple" background shapes.

**Comment by marisamorby** [comment]
@fk: 
Blocked until we decide on messaging. We need to create a new plan after we complete messaging and prototype research. 

We will create a new issue once the research is completed and we can work on prototyping.
