### ISSUE TITLE
[1.0] make babel-preset-env the default babel setup instead of stage presets

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#975]
Also remove the `.babelrc` files from the example sites.

Also document how to override the default config for babel-preset-env e.g. support older browsers.

https://github.com/babel/babel-preset-env

**Comment by jquense** [comment]
for reference i'm quite happy with this babel-env setup: https://github.com/jquense/babel-preset-jason/blob/master/index.js

**Comment by KyleAMathews** [comment]
@jquense looks nice!

**Comment by KyleAMathews** [comment]
We switched to babel-preset-env (mostly) so closing this
