### ISSUE TITLE
.org redesign: homepage [design] community/creators section

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#9753]
We want to feature the recently added "[Community/Creators](https://www.gatsbyjs.org/community)" section of gatsbyjs.org on the homepage and need a design for that.

**Comment by marisamorby** [comment]
Putting this on the backburner until after the .org redesign.

**Comment by marisamorby** [comment]
@fk: This requires research to validate whether this is important to people and we want to move forward with any design. I've reassigned to @shannonbux, but we aren't prioritizing this for now.
