### ISSUE TITLE
.org redesign: homepage [design] features section

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#9755]
Design a section that provides an overview over Gatsby's core features, similar to what we currently have with these six content blocks:

![image](https://user-images.githubusercontent.com/21834/48090851-46c91880-e208-11e8-81f1-d0a402f70af4.png)

- I'm somewhat hoping that we can reduce the space that this section currently occupies.
- One way to do so is by including that information in the "explanatory diagram" (#9525).
- Another possibility is to expand https://www.gatsbyjs.org/features/

**Comment by marisamorby** [comment]
Closing this until messaging and prototype research is completed. We will create a new issue once we have direction on next steps.
