### ISSUE TITLE
Can I contribute Blog Example?

### ISSUE THREAD

**Issue by jakelumetta** [gatsbyjs/gatsby#9756]
## Summary

I'd like to contribute a comprehensive blog example to https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/building-a-blog.md

It would use https://www.gatsbyjs.org/packages/gatsby-source-buttercms/ for the blog backend.

### Motivation

ButterCMS has developers using it's blog engine API to power their own personal Gatsby websites and many of them ask for better docs to support this scenario. We think the community would find a nice guide on how they can quickly create their own personal blog on Gatsby helpful. ButterCMS is SaaS service and is free for personal use.

I want to help improve the docs for Gatsby.  https://www.gatsbyjs.org/docs/building-a-blog/ is currently a stub. I'd like to help the docs cover a core use case of building a blog on Gatsby..

Also - who doesn't want some free swag? 😄  https://www.gatsbyjs.org/docs/contributor-swag/  (not sure if this would qualify?)

**Comment by DSchau** [comment]
@jakelumetta since that stub seems (to me!) to be more general purpose, I'd probably recommend an example and a guide, rather than a general documentation article! Take a look at this page for what I mean -> https://www.gatsbyjs.org/docs/headless-cms/

But we'd happily take any type of content you're willing to contribute! We ❤️ PRs adding examples, improving documentation, and in general, just making people more aware of the varied, growing, and excellent options for CMSes!

**Comment by jakelumetta** [comment]
Thanks @DSchau  - yeah I saw that page so I opened https://github.com/gatsbyjs/gatsby/issues/9757 ; so will definitely want to move forward with that one.

For this blog page, what do you mean by more general purpose? Can you provide an example?

**Comment by DSchau** [comment]
Definitely! I can certainly be wrong here, too, just my opinion :)

By general purpose, I mean non-opinionated. We certainly could highlight any CMS here, e.g. Wordpress, Contentful, ButterCMS, etc. but I think that approach has two disadvantages:

1. It asserts an opinion, e.g. "Use this CMS for blogs!", and
1. There's a precedent of _not_ having an opinion and using a guide for CMSes

So those two concerns lead me to think that that doc should be non-opinionated and more generally applicable. This isn't to say that ButterCMS isn't a great choice for blogs, but rather, that there are content areas better suited to showing how ButterCMS is great for blogs/content/etc.

I think my post a year or so ago--which would need to be updated--is more in line with what I'd think that document _should_ show -> https://www.gatsbyjs.org/blog/2017-07-19-creating-a-blog-with-gatsby/, specifically showing how Markdown files, plugins, etc. can be used to create a compelling blog experience with Gatsby.

**Comment by jakelumetta** [comment]
@DSchau Thanks - very helpful!  I agree. I'll close this issue and continue with https://github.com/gatsbyjs/gatsby/issues/9757
