### ISSUE TITLE
ButterCMS Headless CMS Guide

### ISSUE THREAD

**Issue by jakelumetta** [gatsbyjs/gatsby#9757]
## Summary

I'd like to add ButterCMS to the list here: https://www.gatsbyjs.org/docs/headless-cms/

I'd also like to work with @LekoArts to write a full ButterCMS guide akin to:  https://www.gatsbyjs.org/docs/sourcing-from-prismic/  - those videos a very well done!

**Comment by LekoArts** [comment]
You can find my email on my profile 😀

**Comment by jakelumetta** [comment]
See https://github.com/gatsbyjs/gatsby/pull/9784

@LekoArts sounds good.
