### ISSUE TITLE
FOUC when using typeface- package

### ISSUE THREAD

**Issue by zvinless** [gatsbyjs/gatsby#9760]
## Description

There is a quick flicker of unstyled content on initial page load when using a font from a [typeface package](https://github.com/KyleAMathews/typefaces).

I'm guessing it's [this issue](https://spectrum.chat/thread/8177276a-15a7-41c8-96c3-82d382d17609).

### Steps to reproduce

1. Install a typeface package, e.g. `yarn add typeface-pattaya`
1. Use it as a font in some css
1. Import the font and css in a page
1. Start gatsby dev server
1. Visit the dev server address in Chrome
1. Observe quick flicker of unstyled text before the styled font appears
1. Refresh a bunch and observe the flicker each time

It's also visible in a deployed production build (can be hard to see sometimes but definitely happening):
[Demo repo](https://github.com/zvinless/font-fouc)
[Demo site](https://zvinless.github.io/font-fouc/)

### Expected result

No default font should be visible at all before the styled font

### Actual result

The default font is visible in place of the styled font for a split second

### Environment
```
  System:
    OS: macOS 10.14
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.1.0 - /usr/local/bin/node
    Yarn: 1.12.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.77
    Firefox: 63.0.1
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.33 => 2.0.40 
```

**Comment by LekoArts** [comment]
It’s working as expected. Using typefaces doesn’t mean that you won’t have FOUC out of the box. Moreover `font-display: swap` exactly does that. If you don’t want FOUC you have to preload your fonts.

**Comment by zvinless** [comment]
@LekoArts thanks for the clarification!
