### ISSUE TITLE
Broken link to Crator Showcase in gatsbyjs/docs

### ISSUE THREAD

**Issue by laszlogulasz** [gatsbyjs/gatsby#9761]
Link to Creator Showcase at https://www.gatsbyjs.org/docs/submit-to-creator-showcase/ under the title drives to "Page not found". In submit-to-creator-showcase.md I found following: [Creator Showcase](link TBA)?
Maybe link should be inactive until Creator Showcase is ready?

**Comment by kakadiadarpan** [comment]
@laszlogulasz Thank you for pointing this out. The href for that link is actually supposed to be this: https://www.gatsbyjs.org/showcase/

Would you like to fix this?

**Comment by Dipeshwagle** [comment]
I'll handle it.

**Comment by laszlogulasz** [comment]
@kakadiadarpan I'd like to, if @Dipeshwagle gives me the green light 😊
