### ISSUE TITLE
README of Unit Testing section refers to something that doesn't exist

### ISSUE THREAD

**Issue by mjkrause** [gatsbyjs/gatsby#9766]
## Description

Check line _Back to the Jest config, you can see the next option is testRegex. This is the pattern telling Jest which files contain tests. The pattern above matches any .js file inside a `__tests__` directory,..._ in gatsby/docs/docs/unit-testing.md.
There is no variable named `testRegex` in the above example of `jest.config.js`. I have seen somewhere below in that file, though. In any case, that reference doesn't seem to be correct.

### Steps to reproduce

see description

### Expected result

Remove that reference, or put `testRegex = ...` into the example.

**Comment by kakadiadarpan** [comment]
@mjkrause the best way of going through the Gatsby documentation would be through www.gatsbyjs.org, the links would not work as expected in the Github's README.md

For unit testing, please check the following link on gatsbyjs.org: https://www.gatsbyjs.org/docs/unit-testing/

**Comment by LekoArts** [comment]
No, you’re misunderstanding something here @kakadiadarpan
The text mentions a testRegex that was there before but @dschau removed that from the config file with his last commit

**Comment by kakadiadarpan** [comment]
I can see the `testRegex` in the jest config file. Please check the attached screenshot below:

<img width="835" alt="screenshot 2018-11-07 at 1 15 18 pm" src="https://user-images.githubusercontent.com/10805593/48117477-5ccdec00-e28f-11e8-9c07-ac5b30642bfd.png">

**Comment by DSchau** [comment]
Yeah, whoops! Easy fix to remove and re-arrange that paragraph. I did remove it because it wasn't necessary for JS files, but is still necessary for Typescript.

Someone want to tackle this? If not, one of us will get to it as soon as we can!

**Comment by RobinCsl** [comment]
I believe this issue can be closed now, since my PR was merged.
cc @DSchau @LekoArts @shannonbux
