### ISSUE TITLE
Why does Gatsby unregister all service workers in development?

### ISSUE THREAD

**Issue by OrKoN** [gatsbyjs/gatsby#9770]
I have realized that after spending some hours debugging a not working service worker used for push notifications. This service worker is a feature of the website, and it's not just for caching/offline mode. So I was wondering why does Gatsby unregister all service workers in development? In my opinion, it should only unregister service workers it has installed itself. Otherwise, the behavior is quite harmful, and it's breaking service worker implementations not related to the Gatsby itself making it hard to debug and develop service workers.

Related code: https://github.com/gatsbyjs/gatsby/blob/2605aa0ec74a79fa56bc0eae8d101356c25c38de/packages/gatsby/cache-dir/app.js#L37

**Comment by btk** [comment]
I think you are right, gatsby should tag the service workers that registered by itself or its plugins and unregister these ones on the development, leaving developer the chance to debug their registered service workers.

But keep in mind the development version is not a static output, a javascript application that mimics the output. So it would be tricky to debug service workers on that environment. 

I'm not really educated on how that would go on. I think you should work on a PR if you have time. (I would start with tagging the sw `gatsby-plugin-offline` is registering)

**Comment by OrKoN** [comment]
@btk the interesting part is that I am not using `gatsby-plugin-offline` but it seems that the code to unregister service workers belongs to Gatbsy project itself. Are there any other service workers installed by GatsbyJS? is it possible to move the unregister code to `gatsby-plugin-offline`?

**Comment by btk** [comment]
@OrKoN Afaik there is not, but let's tag inkteam to see if unregister service worker should be moved to the offline plugin.

**Comment by KyleAMathews** [comment]
Hmm yeah — we definitely shouldn't unregister all service workers, just ones from gatsby-plugin-offline. Or perhaps make it configurable.

The reason the code was added is because people will frequently have SWs hanging around which can be super confusing as it blocks your development environment with no clear way to fix it.

**Comment by prajapati-parth** [comment]
This issue makes working on web notifications difficult. Does the same issue exist in Gatsby v2?

**Comment by KyleAMathews** [comment]
@prajapati-parth it does. Would you like to create a PR removing the code that does the unregistration?

**Comment by prajapati-parth** [comment]
Sure. I removed some code from the file mentioned by the author of this issue and seems like many tests are failing. I tried setting up in development by cloning and doing `yarn`. For testing I did `npm test`. Did I miss anything or do we have a getting started for development link?

**Comment by wardpeet** [comment]
We have stopped unregistering service workers and show a warning in console instead so this one should be fixed.
