### ISSUE TITLE
Contentful ID is not the same in the GraphQL query, why?

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#9774]
Hi, 

I just started Gatsby with Contentful and GraphQL.

I playing with GraphQL and I'm wondering why ID is not the same in GraphQuery and Contentful dashboard?

There is a `c` before the ID, if I remove it (exactly as the Contentful dasboard) I doesn't work anymore.

Contentful dashboard : `15jwOBqpxqSAOy2eOO4S0m`

- GraphQL query : 15jwOBqpxqSAOy2eOO4S0m >> **doesn't work** 
- GraphQL query : **c**15jwOBqpxqSAOy2eOO4S0m >> **work**

Why?

<img width="1440" alt="capture d ecran 2018-11-07 a 10 57 28" src="https://user-images.githubusercontent.com/814410/48124332-5aae6200-e27c-11e8-947d-f13cf156beeb.png">

<img width="1440" alt="capture d ecran 2018-11-07 a 10 57 08" src="https://user-images.githubusercontent.com/814410/48124341-5da95280-e27c-11e8-998c-9fee82c17709.png">

<img width="1439" alt="capture d ecran 2018-11-07 a 10 57 17" src="https://user-images.githubusercontent.com/814410/48124442-934e3b80-e27c-11e8-821e-c2e401566798.png">

**Comment by pieh** [comment]
There are some graphql restriction that ID fields can't start with number so we prefix them with `c`. Contentful entries should have `contentful_id` field which does not have that restriction that you can filter by (instead of `id`)

**Comment by Steffi3rd** [comment]
> There are some graphql restriction that ID fields can't start with number so we prefix them with `c`. Contentful entries should have `contentful_id` field which does not have that restriction that you can filter by (instead of `id`)

Thanks for your answer. 

I tried contentful_id so, then it seems to work. 

But I just found that the edges returns "two nodes" instead one.

Why?

### Before (with cid)
![capture d ecran 2018-11-07 a 12 08 54](https://user-images.githubusercontent.com/814410/48128310-5ab35f80-e286-11e8-8bca-f5239175b4b2.png)

After with contentful_id
![capture d ecran 2018-11-07 a 12 08 37](https://user-images.githubusercontent.com/814410/48128332-6e5ec600-e286-11e8-922f-e0beaef08afb.png)

**Comment by pieh** [comment]
That is interesting - do you use multiple locale/languages? can you add locale and actual id to query results?

**Comment by Steffi3rd** [comment]
> That is interesting - do you use multiple locale/languages? can you add locale and actual id to query results?

Yeah, I add a local : "French", so I have 2 locals in my Contentful.

Can you show me how to query with locale, please? I don't find any documentation about this.

**Comment by pieh** [comment]
There should be field like `locale`, `node_locale`, `lang` or something like that available to query (and to filter by)

**Comment by Steffi3rd** [comment]
> There should be field like `locale`, `node_locale`, `lang` or something like that available to query (and to filter by)

Yeah! Thanks, got it!

### With Local 
![capture d ecran 2018-11-07 a 12 36 35](https://user-images.githubusercontent.com/814410/48129461-d5ca4500-e289-11e8-9a2c-f4650aaa13ab.png)

### Without local
![capture d ecran 2018-11-07 a 12 08 37](https://user-images.githubusercontent.com/814410/48129478-eaa6d880-e289-11e8-8a7f-d7c8cb5e61d2.png)


### Final question to close this thread please.

Where I can translate my post on Contentful? I add the local but what's next?

<img width="1435" alt="capture d ecran 2018-11-07 a 12 35 40" src="https://user-images.githubusercontent.com/814410/48129522-1033e200-e28a-11e8-8483-92de37a1dafa.png">

**Comment by pieh** [comment]
Check https://www.contentful.com/developers/docs/tutorials/general/setting-locales/ - this is more about Contentful than Gatsby and I don't know enough about it to explain properly ;)

**Comment by pieh** [comment]
@Khaledgarbaya Do you think it's worth adding localization section to gatsby-source-contentful docs?

**Comment by Steffi3rd** [comment]
> Check https://www.contentful.com/developers/docs/tutorials/general/setting-locales/ - this is more about Contentful than Gatsby and I don't know enough about it to explain properly ;)

Thank you very much! Found to enable fields for locale : In the paragraph : **Enabling on fields**
