### ISSUE TITLE
Unpublished content from Contentful, directory is now empty but not removed, why?

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#9776]
Hi, 

I try to unpublish a blog post named "hello-world" from Contentful, it works well. 
But I still have some files about the post I just unpublished as  `hello-world-_____.js`, `hello-world-_____.js.map`
And the directory `hello-world` is still there but **empty**.

Why, how can clean everything?

Thanks

### Hello world post unpublished

<img width="1431" alt="capture d ecran 2018-11-07 a 11 46 11" src="https://user-images.githubusercontent.com/814410/48126920-bed42480-e282-11e8-84c6-9bcee0f66fe7.png">

### Hello world directory empty, but not removed.

<img width="916" alt="capture d ecran 2018-11-07 a 11 42 38" src="https://user-images.githubusercontent.com/814410/48127093-2f7b4100-e283-11e8-93f0-5b2ea6588063.png">

### Hello world files still there...

<img width="891" alt="capture d ecran 2018-11-07 a 11 42 19" src="https://user-images.githubusercontent.com/814410/48127102-3609b880-e283-11e8-9b38-ed19bf2103ae.png">

**Comment by kakadiadarpan** [comment]
@Steffi3rd did you create a new build after unpublishing your blog post?

**Comment by Steffi3rd** [comment]
> @Steffi3rd did you create a new build after unpublishing your blog post?

Yes I did.

Step 1 : unpublished
Step 2 : npm run dev
Step 3 : npm run build
Step 4 : npm run serve

And that's the result.

**Comment by kakadiadarpan** [comment]
I think on new builds, the existing files in public folder aren't cleared. Is that correct @pieh?

**Comment by pieh** [comment]
Hmm, correct - we only delete .html files.

**Comment by Steffi3rd** [comment]
> Hmm, correct - we only delete .html files.

Why???? :( 
Even .js and .js.map are not delete?

**Comment by pieh** [comment]
I'm not 100% sure now, but I would think this edge case scenario might be the reason - consider scenario:
Someone visits your page and our runtime that fetches those files is loaded. While user is on the page you deploy new build (which deletes those .js files that our runtime depend on). Now when user tries to navigate to page you deleted (without refreshing), gatsby would try to fetch files that were deleted in meantime and it would fail with cryptic error (probably just in console - not visible to user) and what happens is page just doesn't load. So keeping old .js files is a way to not break site for people that that started navigating your site before you deployed new version with deleted page

**Comment by kakadiadarpan** [comment]
@Steffi3rd I hope @pieh answered your question. It would be great if you can remove the content of your public folder and then build your website again.

@pieh In my opinion, we should have this in our documentation so that it's not a surprise for everyone. Or do we have it there already?

**Comment by Steffi3rd** [comment]
For example: 

I only have 1 page index and 1 page blog. 
Now look my tree... Start to become a mess... 6 `path---index` (3 `.js` and` .js.map`)

It's okay about one of each... but 3 of each, I don't understand why, even with the explanation of @pieh.

![capture d ecran 2018-11-08 a 09 40 44](https://user-images.githubusercontent.com/814410/48187129-75dfa700-e33a-11e8-88d2-d04e614ab66a.png)
