### ISSUE TITLE
Why GraphQL returns empty and null when local is not set in an entry?

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#9778]
Hi, 

I just found how to query with locale and how to enable it in the Contentful WebApp.
But I don't understand why it returns null and "" for some fields whereas I don't enable it on the webapp.

### Settings of locale

<img width="720" alt="capture d ecran 2018-11-07 a 14 10 54" src="https://user-images.githubusercontent.com/814410/48133572-8d198880-e297-11e8-8c46-d89749d672c3.png">

### Content Type with one field locale 
<img width="1439" alt="capture d ecran 2018-11-07 a 14 10 21" src="https://user-images.githubusercontent.com/814410/48133525-5d6a8080-e297-11e8-8852-7f8da0235591.png">

### Expected result
Expected result is to give me "the fallback" in US when I don't I set any translation.

```json
{
   "data": {
     "allContentfulPerson": {
       "edges": [
         {
           "node": {
             "name": "John Doe", // default value en-US
             "shortBio": {
               "shortBio": "Research and recommendations for modern stack websites."  // default value en-US
             },
             "title": "Développeur web"  // new value fr-FR
           }
         }
       ]
     }
   }
 }
```

### Actual result 
![capture d ecran 2018-11-07 a 14 10 13](https://user-images.githubusercontent.com/814410/48133508-49bf1a00-e297-11e8-9e2a-ff9e8784c5f7.png)

**Comment by kakadiadarpan** [comment]
`gatsby-source-contentful` plugin offers full support for Contentful's localization features. I'm not sure why this could be happening.

@pieh any idea regarding this?

**Comment by Steffi3rd** [comment]
> `gatsby-source-contentful` plugin offers full support for Contentful's localization features. I'm not sure why this could be happening.
> 
> @pieh any idea regarding this?

I already have it 

```
 "dependencies": {
    "gatsby": "^1.9.277",
    "gatsby-source-contentful": "^1.3.54",
  },
```

**Comment by kakadiadarpan** [comment]
@Steffi3rd can you provide complete environment information by running `gatsby info --clipboard`?

**Comment by kodemi** [comment]
@Steffi3rd try to delete .cache folder and rerun `gatsby develop`

**Comment by adityasingh773** [comment]
Open this please. Attaching screenshot for reference. My en content always shows null in the graphiql interface
<img width="670" alt="Screenshot 2021-08-18 at 5 36 28 PM" src="https://user-images.githubusercontent.com/11049213/129927928-0109066b-2116-4d86-ae9b-4bf1ca117a00.png">
<img width="637" alt="Screenshot 2021-08-18 at 5 36 45 PM" src="https://user-images.githubusercontent.com/11049213/129927983-96e0c828-ffed-4d78-9c01-965890b9f1e6.png">
<img width="468" alt="Screenshot 2021-08-18 at 5 37 12 PM" src="https://user-images.githubusercontent.com/11049213/129928055-4a7c2ba1-9a0d-4fc5-ad4e-208d35f29874.png">
<img width="474" alt="Screenshot 2021-08-18 at 5 37 34 PM" src="https://user-images.githubusercontent.com/11049213/129928111-942f8daa-7db7-4acf-8255-a202b4f15ef0.png">
