### ISSUE TITLE
[docs] Content request - Dynamic sidebar documentation

### ISSUE THREAD

**Issue by eivindflobak** [gatsbyjs/gatsby#9779]
Hi, this has been a stub for some months: https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/rendering-sidebar-navigation-dynamically.md

Would love to see a guide if anyone could write one. 

Best regards

**Comment by kakadiadarpan** [comment]
Does someone want to tackle this? If not, one of us will get to it as soon as we can.

**Comment by justinformentin** [comment]
@kakadiadarpan I'll do this!

**Comment by gormed** [comment]
> @kakadiadarpan I'll do this!

@justinformentin any progress on this? i wonder if there are some other resources on this topic? We wanted to create a dynamic navigation from Markdown Metadata and would stick to the common practice.

**Comment by marcysutton** [comment]
Hi folks! Thanks for your interest in working on this doc! We are definitely still looking for help. (The entire [routing section of the docs](https://www.gatsbyjs.org/docs/routing/) could use some work!)

**Comment by mahaveer0496** [comment]
If someone can help outline points that need to be covered, I could do it over the weekends.

**Comment by ZeninZenin** [comment]
Hi everyone! I tried to do it. But so far it only works with markdown files.
[Plugin on GitHub](https://github.com/ZeninZenin/gatsby-dynamical-navigation)
[Example of page with navigation](https://learn.webpurple.net/dictionaries/html/1_html_introduction/) (left side of page)
[This site on GitHub](https://github.com/ZeninZenin/WebPurple-learn)

So far it requires a specific file structure in `src/pages`.

**Comment by hirenoble** [comment]
Hi @ZeninZenin awesome stuff! But how will that work with markdowns coming from gatsby-source-git, because they do not land in src/pages.

**Comment by ZeninZenin** [comment]
Hi, @hirenoble! Actually, I haven't worked with `gatsby-source-git`. Next week I will see what can be done with this.

**Comment by laurieontech** [comment]
After further review this stub is covered in another document https://www.gatsbyjs.org/docs/creating-dynamic-navigation/.

So going to close this issue.
