### ISSUE TITLE
gatsby and styleguidist

### ISSUE THREAD

**Issue by kevinfoerster** [gatsbyjs/gatsby#978]
I tried to get Gatsby and styleguidist to work, without any luck. 

running `npm run styleguide` will exit with a missing *webpackConfig* and pointing to `node_modules/gatsby/dist/utils/webpack.config.js` throws the following error:

> Path must be a string. Received undefined

I guess this is caused by not having webpackconfig available within styleguidist

**Comment by KyleAMathews** [comment]
Gatsby's webpack config is a function which generates the webpack config as there's multiple environments we target + there's logic there for changing the config based on command line flags, etc.

You might want to check out what people did to get Storybook and Gatsby working together. Search the issues for that.

**Comment by kevinfoerster** [comment]
already tried loading the config like menthioend in #633, this give a different error

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'postcss'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           postcss: ...
         }
       })
     ]
 - configuration.resolve has an unknown property 'modulesDirectories'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }
 - configuration.resolve.extensions[3] should not be empty.
 - configuration.resolveLoader has an unknown property 'root'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }

**Comment by kevinfoerster** [comment]
running gatsby 0.12.46

**Comment by jbolda** [comment]
@kevinfoerster were you able to figure it out?

**Comment by kevinfoerster** [comment]
i basically copied the neccessary loaders into `styleguide.config.js`

**Comment by jbolda** [comment]
Cool, sounds like you are set. Feel free to reopen if you aren't.

**Comment by valdelama** [comment]
@kevinfoerster Any chance you could expand on this or show some code:

> i basically copied the neccessary loaders into `styleguide.config.js`

much appreciated

**Comment by Mindaugas-Jacionis** [comment]
@kevinfoerster would be awesome if you could open a gist or add a comment with code snippet that helped. 
Thanks in advance. 🙂
