### ISSUE TITLE
Just wondering why I have an error "cannot query field Metadata on Type Site"

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#9788]
Hi,

I'm new to GatsbyJS and GraphQL and Contentful

I'm wondering  why I have an error cannot query field `Metadata` on Type `Site`
whereas the query returns the good result.

Thanks

![capture d ecran 2018-11-07 a 18 21 49](https://user-images.githubusercontent.com/814410/48148450-0b872200-e2ba-11e8-8e4e-70419aa81ace.png)

![capture d ecran 2018-11-07 a 18 19 53](https://user-images.githubusercontent.com/814410/48148438-00cc8d00-e2ba-11e8-9530-ff8d65089d6a.png)

**Comment by LekoArts** [comment]
duplicate: 
https://github.com/gatsbyjs/gatsby/issues/9789

**Comment by Steffi3rd** [comment]
> duplicate:
> #9789

Hi, why did you close it?
Same topic yeah, but not the same question. 

My question is about GraphiQL and the other one about merge queries...
