### ISSUE TITLE
Getting gatsby to work with bootstrap via webpack 

### ISSUE THREAD

**Issue by liorix** [gatsbyjs/gatsby#979]
Hi,

I'm trying to figure out how to get bootstrap to work with gatsby through webpack configuration. I tried the following, and I'm wondering what am I doing wrong:

in gatsby-node.js:

```
var webpack = require('webpack');

exports.modifyWebpackConfig = function(config, stage) {
    if (!config.plugins) config.plugins = [];
    config.plugins.push(
        new webpack.ProvidePlugin({   
            jQuery: 'jquery',
            $: 'jquery',
            jquery: 'jquery',
    }));
  // edit loaders here
  return config
}
```

in html.js

```
import jquery from 'jquery'
import bootstrap from 'bootstrap'
```

when I run ./node_modules/.bin/gatsby develop I'm getting the following error message:

> Error: Bootstrap's JavaScript requires jQuery. jQuery must be included before Bootstrap's JavaScript.

I know that I can just include the bootstrap and jquery directly in the HTML template, but I'm trying to do it the webpack way if possible.

Any help is much appreciated!
Lior

**Comment by KyleAMathews** [comment]
Have you looked at using react-bootstrap? That might be easier to get going

**Comment by liorix** [comment]
Thanks for the super quick reply Kyle!,You've done an amazing job with gatsby. I love it!

I thought about it, but I wasn't sure if I want to use it or not and I was kinda curious about how to get bootstrap to work with webpack and gatsby together. Any ideas? If not I might just try the react-bootstrap approach. 
Thanks!

**Comment by KyleAMathews** [comment]
Apparently it's a process. I've never done it but there's docs in
create-react-app and the process should be similar for Gatsby.

**Comment by liorix** [comment]
Thanks Kyle. Will check it out! 
Lior

**Comment by I-NOZex** [comment]
@liorix did you make it?

**Comment by liorix** [comment]
Hi @I-NOZex , Eventually I went with @KyleAMathews's recommendation and used react-bootstrap. It worked very well and I'm actually happy that I used it instead of going directly with bootstrap.
