### ISSUE TITLE
Why assets called from CSS is not found on production Github Pages? (404)

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#9791]
In local, it works. url is `http://localhost/`

In production, I have a `pathPrefix: /steffi` so the Gatsby is located to : `http://blabla.com/steffi`

### CSS 
![capture d ecran 2018-11-07 a 19 07 49](https://user-images.githubusercontent.com/814410/48151041-923efd80-e2c0-11e8-80a0-ccd4624f90b2.png)

### Result 
<img width="552" alt="capture d ecran 2018-11-07 a 19 10 12" src="https://user-images.githubusercontent.com/814410/48151121-c5818c80-e2c0-11e8-8761-6458ee731c16.png">

**Comment by oorestisime** [comment]
did you put the font in your static folder? is it getting copied in your public one? did you try to hard-refresh maybe a cache issue?

**Comment by Steffi3rd** [comment]
Yes I do. It's in `/static` folder.

On production, It's in `/public` but the `public/static` is empty... 


### /static 

![capture d ecran 2018-11-08 a 09 29 21](https://user-images.githubusercontent.com/814410/48186681-02896580-e339-11e8-8893-47a5e49917d7.png)

### /public but /public/static is empty
![capture d ecran 2018-11-08 a 09 29 12](https://user-images.githubusercontent.com/814410/48186677-fdc4b180-e338-11e8-9895-64c4395e8812.png)

**Comment by oorestisime** [comment]
Have a look here https://www.gatsbyjs.org/docs/adding-images-fonts-files/?no-cache=1#using-the-static-folder

**Comment by Steffi3rd** [comment]
> Have a look here https://www.gatsbyjs.org/docs/adding-images-fonts-files/?no-cache=1#using-the-static-folder

Yeah! I think I found the solution thanks to your link.

It seems I have to use `withPrefix()`. But how can do that inside a `.css`? 

![capture d ecran 2018-11-08 a 11 58 47](https://user-images.githubusercontent.com/814410/48194619-cad8e880-e34d-11e8-9728-a433f7a3a76e.png)

**Comment by oorestisime** [comment]
Maybe you should look on using a css-in-js library for your styling. If you don't want that then maybe you need a plugin that copies files around or do that on your own in gatsby-node
