### ISSUE TITLE
[gatsby-plugin-google-analytics] Log events when running `gatsby develop`

### ISSUE THREAD

**Issue by jkjustjoshing** [gatsbyjs/gatsby#9796]
### Summary
Allow Analytics tracking in development mode, behind a gatsby-config.js flag

### Basic example
One possible solution would be adding a flag in the plugin config called `enabled`. If true, log analytics events. If false, do not log them. The default value could be `process.env.NODE_ENV === 'production'` to not change the default behavior.
Another solution could be a config flag called `onlyInProduction`, with a default of `true`. If the user sets it to `false` then analytics get logged in development mode.

### Motivation
Right now, `gatsby-plugin-google-analytics` only tracks when `env.NODE_ENV === 'production'`. However, I want to test out some analytics stuff while developing, and it's a pain to run `gatsby build` and start a static file server every time I make a change. 
I'm filtering all `localhost` entries out of my analytics already, so extra noise coming from my development environment isn't a problem.

**Comment by kakadiadarpan** [comment]
@jkjustjoshing This makes a lot of sense. Would you like to work on this and raise a PR?

**Comment by jkjustjoshing** [comment]
Yeah definitely. Any thoughts on which solution might work better and have better developer ergonomics? I'm leaning toward the `enabled` flag, with 3 values, `true`, `false`, or `'auto'`, where `'auto'` is default and checks for `process.env.NODE_ENV === 'production'`

**Comment by DZuz14** [comment]
Why not an option called, `enableLogging`? If its missing from the config or does not have a value of true then it just doesn't log anything.

**Comment by jkjustjoshing** [comment]
@DZuz14 that would be a breaking change. Current behavior is: dev mode no log, prod mode yes log. If you wanted to keep that behavior you would need to reimplement `enableLogging: mode === 'production'`. 

Any change should avoid changing functionality unless a developer explicitly opts in.

**Comment by DZuz14** [comment]
Got ya. I prob should have read up on the plugin a little bit more before posting that. I guess I don't really use GA that much to know exactly how you're using it, but your second option seems okay. 

The only thing that I see being a problem is the naming of the option flag. Personally, I don't think `enabled` is really descriptive enough. I think it would be cool if the option name was quite blatant about what it was doing. ie: something like, `enableInDevMode`.

**Comment by DZuz14** [comment]
That's cool. Doesn't seem like a huge deal either way. I'm just trying to get involved so I can learn more about Gatsbys internals in order to contribute.

Interested to see what you come up with.
