### ISSUE TITLE
Fields missing for fluid image data

### ISSUE THREAD

**Issue by jackyho112** [gatsbyjs/gatsby#9799]
## Summary

I tried to retrieve the fluid object of a Media field, but pretty much all the attributes in that object are missing. I'm not sure if this has to do with Contentful or this package. Thanks in advance for all the help!

## Relevant information

My query:

<img width="861" alt="screen shot 2018-11-07 at 5 08 29 pm" src="https://user-images.githubusercontent.com/25375401/48171219-c65df280-e2af-11e8-9860-89fe9945f2ee.png">

What I got back:

![screen shot 2018-11-07 at 5 06 12 pm](https://user-images.githubusercontent.com/25375401/48171162-73843b00-e2af-11e8-830a-aaaf07a8ab72.png)

**Comment by pieh** [comment]
It would be great if you provided more details - as what version of plugins you are using (please paste output of `gatsby info` command)
