### ISSUE TITLE
gatsby -v not working

### ISSUE THREAD

**Issue by kevinsimper** [gatsbyjs/gatsby#98]
```
$ gatsby -v

  error: unknown option `-v'

$ gatsby --version
0.7.3
```

**Comment by KyleAMathews** [comment]
PRs accepted :-)

**Comment by kevinsimper** [comment]
Looked at it, but it seems to be built into commander so don't know why it is not working.

**Comment by KyleAMathews** [comment]
Oh, the built-in is a capital v so `gatsby -V` which works.

**Comment by kevinsimper** [comment]
But the docs says otherwise?
