### ISSUE TITLE
Regarding gatsby URL formatting

### ISSUE THREAD

**Issue by aje4u2i** [gatsbyjs/gatsby#980]
Consider a Product detail page

Can we restructure the URL in such a way that,
hostname/categoryname/productname

Is this type of URL formatting is possible using gatsby

**Comment by KyleAMathews** [comment]
URLs come from the position of the file so if you want that URL just put a file at `pages/hostname/categoryname/productname`. It could be a JSON file for example with information about the product. I'm assuming you're using Gatsby v0?

**Comment by aje4u2i** [comment]
I am using version Gatsbay 1.0 alpha 13.

**Comment by aje4u2i** [comment]
Could you please explain how you are using config.toml file to display blog title etc in index.js and bio.js files in gatsby starter-blog app.

**Comment by KyleAMathews** [comment]
"config.toml" isn't used any longer in v1. Check out the 1.0 branch of
gatsby-starter-blog

**Comment by aje4u2i** [comment]
i need to place the following swift type code snippet inside gatsby body tag.Is it possible to accomplish this.I placed this inside body tag within barces{} but it shows window and document undefined error. 
<script type="text/javascript">
  (function(w,d,t,u,n,s,e){w['SwiftypeObject']=n;w[n]=w[n]||function(){
  (w[n].q=w[n].q||[]).push(arguments);};s=d.createElement(t);
  e=d.getElementsByTagName(t)[0];s.async=1;s.src=u;e.parentNode.insertBefore(s,e);
  })(window,document,'script','//s.swiftypecdn.com/install/v2/st.js','_st');
  
  _st('install','KWy4xTDSnsLvfYABNKnD','2.0.0');
</script>
