### ISSUE TITLE
[gatsby-source-contentful] 'TypeError: createNodeId is not a function' when environment variable GATSBY_CONTENTFUL_RICH_TEXT is set to 'enabled'

### ISSUE THREAD

**Issue by julian009** [gatsbyjs/gatsby#9801]
## Description

According to the docs at [https://www.gatsbyjs.org/packages/gatsby-source-contentful/](url) in order to use the new Rich Text feature we need to set the following environment variable:

`export GATSBY_CONTENTFUL_RICH_TEXT='enabled'`

After setting that, we try running `gatsby develop`, but this fails with the following error:

`error Plugin gatsby-source-contentful returned an error`
  `TypeError: createNodeId is not a function`
  `- normalize.js:204 prepareStructuredTextNode`
    `[gatsby-contentful]/[gatsby-source-contentful]/normalize.js:204:9`

I was able to fix this locally/temporarily by removing the unused `createNode` parameter from the `prepareStructuredTextNode` function definition on line 201 of my node_modules/gatsby-source-contentful/normalize.js file. This way the function no longer receives the undefined `createNodeId` parameter that was causing the error. The root of the issue seems to be that the `prepareStructuredTextNode` function is defined with 5 parameters, like so:

`function prepareStructuredTextNode(node, key, content, createNode, createNodeId)`

However it is called with 4 parameters, as follows:

`const richTextNode = prepareStructuredTextNode(entryNode, entryItemFieldKey, entryItemFields[entryItemFieldKey], createNodeId);`

So the `prepareStructuredTextNode` function receives an undefined createNodeId parameter and attemps to call it as a function.

### Steps to reproduce

1. I followed this guide ([https://itnext.io/jamstack-basics-how-to-create-a-gatsby-starter-with-contentful-and-deploy-to-netlify-846354cc74bc](url)) to get started with Gatsby and Contentful (ignoring the Netlify parts). Generally, you'll need to set up any basic Gatsby project, `npm install gatsby-source-contentful` in the project root, create a Contentful account and space with at least one ContentType with a field of type Rich Text, and configure the gatsby-config.js file to resolve the gatsby-source-contentful plugin with your Contentful spaceId and accessToken.
2. In your project root, run 
`rm -rf .cache`
followed by
`export GATSBY_CONTENTFUL_RICH_TEXT='enabled' && gatsby develop`
Note: If you run `gatsby develop` successfully before setting the GATSBY_CONTENTFUL_RICH_TEXT environment variable to 'enabled', you will need to run `rm -rf .cache` before your next attempt at running `gatsby develop` in order to reproduce the error.

### Expected result
Gatsby should run the development server without errors.

### Actual result
The `gatsby develop` command errors out:
<img width="570" alt="gatsby-source-contentful-richtext-error" src="https://user-images.githubusercontent.com/10556424/48171295-9109d280-e2b8-11e8-8c7c-c47e3f1169b1.png">

### Environment

System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 9.2.0 - /usr/local/bin/node
    Yarn: 1.9.4 - ~/.yarn/bin/yarn
    npm: 6.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.77
    Firefox: 60.0.2
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.40 => 2.0.40 
    gatsby-plugin-sass: ^2.0.3 => 2.0.3 
    gatsby-source-contentful: 2.0.5 => 2.0.5 
    gatsby-transformer-remark: ^2.1.11 => 2.1.11 
  npmGlobalPackages:
    gatsby-cli: 2.4.4

**Comment by kakadiadarpan** [comment]
@julian009 This issue has already been fixed. Can you update the `gatsby-source-contentful` plugin to latest version `2.0.13`?

https://github.com/gatsbyjs/gatsby/blob/90b0ea74915dbeaaaefd17df828831fa5b85bed7/packages/gatsby-source-contentful/src/normalize.js#L196

Feel free to reopen if you still experience this problem 👍
