### ISSUE TITLE
[gatsby-image] Images not being displayed iphone 5S

### ISSUE THREAD

**Issue by dial3x** [gatsbyjs/gatsby#9805]
## Description
Images are not being displayed correctly:

Gatsby Image seems to be incompatible with older iOS devices:

![image](https://user-images.githubusercontent.com/29848406/48181333-c4a93300-e372-11e8-9862-1656c46632d4.png)

I've been experiencing other issues with my site and Gatsby not correctly polyfilling `Set` on iphone 5S but I'm unsure if this is related. 

`Uncaught ReferenceError: Set is not defined`

### Steps to reproduce

Use browserstack to view gatsby site.

https://www.gatsbyjs.org/showcase/

### Expected result

Images should display.

### Actual result

Images are not displaying on my (and gatsby's site). 

### Environment

iPhone 5S

**Comment by kakadiadarpan** [comment]
Might be related to #9348

/cc @DSchau

**Comment by dial3x** [comment]
@kakadiadarpan This is on iOS 7.

**Comment by jonniebigodes** [comment]
@dial3x i've just opened the gatsby site on a old iphone 4s running version 9.3.5. And aside from the images taking a bit to load and the grid showcase layout not being applied correctly all is working correctly.
Did some navigation, went back and forward on the gatsby site and the images were loading as they are supposed.
Still i'm going to clone a starter template, add some pictures and deploy it somewhere and i'll come back with some more feedback

**Comment by tulsileathers** [comment]
@dial3x I've had a similar issue where a client was using an older ios version and couldnt see images. What ended up being the problem was the images had spaces in the filename. Just something to check

**Comment by dial3x** [comment]
@jslyonnais I'm still waiting for the issue to be resolved. Though I've added a babel polyfill which has resolved my a few react-dom issues. 
Try adding 
`require('babel-polyfill');`  to `gatsby-browser.js`

**Comment by jonniebigodes** [comment]
@jslyonnais and @dial3x i'm positive that this issue is being looked at by the team, but as this issue is a concern, there are other more pressing ones, tangible bugs that need some more attention and fixing. I ask you that you be a little more patient with the team and give them some more time.
