### ISSUE TITLE
where the layout is used?

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#9806]
Hi,

I'm using the starter `gatsby-contentful-starter` and I'm trying to understand the project.
I came to this question. Where the **layout** is called?
I have a layout folder with index.js.

I think the **main page** is `pages/index.js`, right? So it's the main entry?
But in this page, `layout` is not called anywhere.

So where is it call?

In fact, I would like to add a `lang` attribute to the layout.

![capture d ecran 2018-11-08 a 10 46 07](https://user-images.githubusercontent.com/814410/48190693-a37d1e00-e343-11e8-971c-bd08a5434741.png)

**Comment by kakadiadarpan** [comment]
@Steffi3rd `gatsby-contentful-starter` uses Gatsby v1. The layout component is wrapped around the outside of the page component, which, in pseudo-code, looks something like this:

```jsx
<Root>
  <Layout>
    {/* layout is not affected when the page template changes */}
    <PageElement>{/* page content here */}</PageElement>
  </Layout>
</Root>
```

On a side note, please always provide environment information by running `gatsby info --clipboard`. That makes it easier for us to help you out in figuring out issues or answering your questions.

**Comment by jonniebigodes** [comment]
@Steffi3rd as the starter was created with v1 of gatsby, here are some [docs ](https://v1.gatsbyjs.org/docs/)to help you figuring out the library. These are outdated as the way layouts are used in the current released version. But nonetheless will point you in the right direction on how everything is wired up and get you started on learning how to develop using gatsby.

**Comment by Steffi3rd** [comment]
Thanks! So I switched to Gatsby V2 ^^
