### ISSUE TITLE
custom webpack config fails / how to mini-css-extract?

### ISSUE THREAD

**Issue by gswirrl** [gatsbyjs/gatsby#9807]
Hi

I need to reuse the css Gatsby is building and would like to output it to a separate css file. In the past I've used the mini-css-extract plugin with webpack, but adding this to Gatsby doesnt work as I'd hoped, i think because Gatsby already uses it internally. Any ideas how i can get my css output to a file?

**Comment by kakadiadarpan** [comment]
@gswirrl can you please provide environment information for your project by running `gatsby info --clipboard`?

**Comment by gswirrl** [comment]
System:
    OS: macOS 10.14
    CPU: x64 Intel(R) Core(TM) m3-7Y32 CPU @ 1.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.0.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  npmPackages:
    gatsby: ^2.0.19 => 2.0.40 
    gatsby-image: ^2.0.15 => 2.0.19 
    gatsby-plugin-manifest: ^2.0.5 => 2.0.7 
    gatsby-plugin-offline: ^2.0.11 => 2.0.12 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.1 
    gatsby-plugin-sharp: ^2.0.7 => 2.0.12 
    gatsby-source-filesystem: ^2.0.4 => 2.0.7 
    gatsby-transformer-sharp: ^2.1.4 => 2.1.8 
  npmGlobalPackages:
    gatsby-cli: 2.4.1

**Comment by gswirrl** [comment]
thanks!

**Comment by gswirrl** [comment]
I _thought_ that I'd be able to do something like the approach at https://www.gatsbyjs.org/docs/add-custom-webpack-config/ (though not with LESS) but (1) that example doesn't work for me anyway

```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader
  .js):
  ModuleBuildError: Module build failed (from ./node_modules/mini-css-extract-
  plugin/dist/loader.js):
  Error: Didn't get a result from child compiler
      at childCompiler.runAsChild (~/node
  _modules/mini-css-extract-plugin/dist/loader.js:121:23)
```

(2) i cant figure out an alternative.

So... how can I output a css file?

**Comment by gswirrl** [comment]
For anybody having similar problems, you may be able to get away with this awful wretched bodge by hardcoding a name in your `gatsby-node.js`

```
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

exports.onCreateWebpackConfig = ({
  actions,
}) => {
  actions.setWebpackConfig({
    plugins: [new MiniCssExtractPlugin({
      chunkFilename: "my.css"
    })]})}
```

it's really unsatisfactory - i really wanted to extract several css into several files but its better than nothing. Would be very grateful if anybody can come up with a way to have eg

`src/basic.css` -> `basic.css`
`src/other.css` -> `other.css`

**Comment by kakadiadarpan** [comment]
@gswirrl `mini-css-extract-plugin` should support extracting several files, I'll check this.

**Comment by gswirrl** [comment]
@kakadiadarpan that would be fantastic - thank you so much!

g

**Comment by gswirrl** [comment]
update: the solution above doesn't work after all :-( it builds the stylesheet, it names it correctly and... it also inlines all the css into the head of every html page as well. dammit.

to recap -  i'm trying to do is build two stylesheets with predefined names and include them on every built html page. I can do this successfully with mini-css-extract in a vanilla webpack project but not in gatsby. am i just not understanding how to make a new entry point that just renders the css?

**Comment by gswirrl** [comment]
https://github.com/gatsbyjs/gatsby/blob/7ce60b5a34f23828ca673776bab7e4a5356cb0af/docs/docs/building-with-components.md in the section `HTML component` also to my eye says that it ought to be possible to intervene in the writing of css into the head, but the current `html.js` just looks like

```
        <head>
          <meta charSet="utf-8" />
          <meta httpEquiv="x-ua-compatible" content="ie=edge" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
          />
          {this.props.headComponents}
        </head>
```

and my styles are passed in in `props.headComponents` as objects like

```
{ '$$typeof': Symbol(react.element),
    type: 'style',
    key: null,
    ref: null,
    props:
     { 'data-href': '/app.fe9d7236be808ee46283.css',
       dangerouslySetInnerHTML:
        { __html:
           '(css here)`

```

has this changed? does this no longer work?

**Comment by gswirrl** [comment]
This works but is awful - surely this cant be the way to do it?

```
export default class HTML extends React.Component {
  render() {
    let headComponents = this.props.headComponents
    let css
    if (process.env.NODE_ENV == `production`) {
      headComponents = headComponents.filter(component => component.type !== 'style')
      css = (<link rel="stylesheet" href="/styles.css"/>)
    }
    return (
      <html {...this.props.htmlAttributes}>
        <head>
          <meta charSet="utf-8" />
          <meta httpEquiv="x-ua-compatible" content="ie=edge" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
          />
          {headComponents}
          {css}
        </head>
```

**Comment by gswirrl** [comment]
So the problem now seems to be: how can I get Gatsby to build multiple css files with known names.

In WebPack this is as easy as adding an array of css files to the config `entry:` and outputting to 

```
    new MiniCssExtractPlugin({
      filename: "css/[name].css"
    }),
```

but i can't find a way to do this with Gatsby

**Comment by gswirrl** [comment]
A partial solution - this will build stylesheets named foo.css and bar.css from their respective source files. The solution above can then be applied to include these files in the built html.

gatsby-node.js
```
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

exports.onCreateWebpackConfig = ({
  actions,
  stage,
  getConfig
}) => {
  // needed to output correctly-named css
  actions.setWebpackConfig({
    plugins: [new MiniCssExtractPlugin({})],
  })
   // needed to bodge in new css entry points
  if (stage.includes('javascript')) {
    let config = getConfig()
    config.entry["foo"] = './src/css/entry-points/foo.css'
    config.entry["bar"] = './src/css/entry-points/bar.css'
    actions.replaceWebpackConfig(config)
  }
}

```

**Comment by gswirrl** [comment]
Ok so for the record, here's how to get Gatsby to build multiple named stylesheets and use them instead of inlining the css into the head of the html.

There are 3 things you need to do:

1) modify `html.js`to hard link to the built files

```
import React from "react"
import PropTypes from "prop-types"

export default class HTML extends React.Component {
  render() {
    let headComponents = this.props.headComponents
    let css
    if (process.env.NODE_ENV == `production`) {
      headComponents = headComponents.filter(component => component.type !== 'style')
      css = (<><link rel="stylesheet" href="/foo.css"/><link rel="stylesheet" href="/bar.css"/></>)
    }
    return (
      <html {...this.props.htmlAttributes}>
        <head>
          <meta charSet="utf-8" />
          <meta httpEquiv="x-ua-compatible" content="ie=edge" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
          />
          {headComponents}
          {css}
        </head>
        <body {...this.props.bodyAttributes}>
          {this.props.preBodyComponents}
          <div
            key={`body`}
            id="___gatsby"
            dangerouslySetInnerHTML={{ __html: this.props.body }}
          />
          {this.props.postBodyComponents}
        </body>
      </html>
    )
  }
}

HTML.propTypes = {
  htmlAttributes: PropTypes.object,
  headComponents: PropTypes.array,
  bodyAttributes: PropTypes.object,
  preBodyComponents: PropTypes.array,
  body: PropTypes.string,
  postBodyComponents: PropTypes.array,
}
```

2) modify `gatsby-node.js` to add new entry points

```
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

exports.onCreateWebpackConfig = ({
  actions,
  stage,
  getConfig
}) => {
  // needed to output correctly-named css
  actions.setWebpackConfig({
    plugins: [new MiniCssExtractPlugin({})],
  })
   // needed to bodge in new css entry points
  if (stage.includes('javascript')) {
    let config = getConfig()
    config.entry["foo"] = './src/css/entry-points/foo.css'
    config.entry["bar"] = './src/css/entry-points/bar.css'
    actions.replaceWebpackConfig(config)
  }
}
```

3) make HMR / `gatsby develop` work by modifying `gatsby-develop.js` to include the entry points. this is a bit unsatisfactory but it works for my case. ymmv

```
import "./src/css/entry-points/foo.css"
import "./src/css/entry-points/bar.css"
```

**Comment by gswirrl** [comment]
(so this issue can be closed :-)
