### ISSUE TITLE
How to run gatsby build from Contentful webhoooks with Github Pages?

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#9808]
Hi 

I would like to re-build my static blog when new content is found from Contentful without I run manually a `gatsby build`...

The project lives in Github Pages.

Is there a way to do that please?

**Comment by oorestisime** [comment]
again this is not directly related to gatsby. it is more of a general question on how to re-trigger deploys and it depends on your deployment platform.
anyway I dont know if contentful allows webhooks or can have some sort of mechanism to have side-effects on new publication.
To give you an example, i use this on netlify https://www.netlify.com/docs/webhooks/#incoming-webhooks to rebuild every day the site to refresh some things. i basically have a hook and a crob-tab.
hope this helps

**Comment by kakadiadarpan** [comment]
@Steffi3rd Netlify has better hook support to achieve what you want to. Please take a look at this guide on [Deploying to GitLab pages](https://www.gatsbyjs.org/docs/deploying-to-gitlab-pages/), it is similar to what you are looking for. GitLab Pages are very similar to GitHub Pages.

**Comment by KyleAMathews** [comment]
You can also use a ci server like circle ci to run the build and push to GitHub pages.
