### ISSUE TITLE
Spotify for Artists website, is it done in Gatsby?

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#9811]
Blazing fast website using Contentful. But is it with Gatsby?

https://artists.spotify.com/

**Comment by kakadiadarpan** [comment]
I don't think that they Gatsby. If it would have been built using Gatsby you can find `__gatsby` ID of a div in the elements list. Refer the screenshot below:

<img width="488" alt="screenshot 2018-11-08 at 5 04 03 pm" src="https://user-images.githubusercontent.com/10805593/48196321-51a2bb00-e378-11e8-8dca-3ec5bfb495fd.png">
