### ISSUE TITLE
Contentful vs Prismic.io for a huge blog using Gatsby? 

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#9812]
I tried Contentful right now, but I want a to publish a lot of post and I see the limit of 5000 entries/assets without paying a lot... I'm not a company.

What do you think?

**Comment by kmorf** [comment]
You can check all the CMSs here https://headlesscms.org/. Some are free and some are not. Just make sure before you start your project that the CMS covers all your needs i.e gatsby source plugins, gatsby images, search index etc.

Personally I'm using netlify-cms but there are a lot other free promising ones like Strapi.

**Comment by oorestisime** [comment]
You should probably close this issue since it is not related to gatsby. maybe stackoverflow is better for this kind of questions.

**Comment by LekoArts** [comment]
> You should probably close this issue since it is not related to gatsby. maybe stackoverflow is better for this kind of questions.

Agree with that. The issues here are mainly for bugs/questions/feature requests regarding Gatsby directly. You also can ask on Spectrum: https://spectrum.chat/gatsby-js
