### ISSUE TITLE
`gatsby --help` lists wrong commands, e.g. `index.js serve`

### ISSUE THREAD

**Issue by chhh** [gatsbyjs/gatsby#9833]
## Description

This has already been bought up and the issue was closed. I see that with the most recent gatsby () and node.

### Steps to reproduce

Just install gatsby and `gatsby --help`.

### Expected result

Usage displayed with `gatsby` as the command name.

### Actual result

Usage displayed, but the command name is `index.js`.

### Environment
```
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 11.1.0
    Yarn: 1.12.3
    npm: 6.4.1
```

**Comment by btk** [comment]
Reproduced on node v11.1.0, but not with node v8.10.0, maybe this is about node/upstream?

**Comment by kakadiadarpan** [comment]
@chhh Thanks for filing this issue! I'm having trouble reproducing, though. Is there any other information you can provide that would help me out? I'm unable to reproduce this on `Node 11` or `Node 10`. Can you also provide the version of `gatsby-cli` that you are using?

<img width="1679" alt="screenshot 2018-11-09 at 6 40 54 pm" src="https://user-images.githubusercontent.com/10805593/48264366-41a9da80-e44f-11e8-925b-1d7d679abc3b.png">

**Comment by chhh** [comment]
@kakadiadarpan 
```
$ node --version
v11.1.0
```
```
$ gatsby --version
2.4.5
```
```
$ npm -g ls gatsby-cli
...\nodejs\bin
`-- gatsby-cli@2.4.5
```

**Comment by jonniebigodes** [comment]
This issue traces back to earlier versions. I've ran `gatsby --h` on a old windows 7 machine running i had laying around running gatsby version 1.1.58 and node 8  and it throws out the same output.

**Comment by jonniebigodes** [comment]
i've been doing some detective work and it looks like this issue is applied to the windows cli versions. On a mac and a ubuntu 18.10 or even a wsl it shows the correct output but natively on windows it shows the mentioned output. The image bellow shows side by side this. on the left is the windows output of gatsby -h with version 2.4.5 and on the left the same output but on a wsl.
![gatsby-cli_win10_wsl](https://user-images.githubusercontent.com/22988955/48862673-f5e82100-edbe-11e8-8910-bb8b8df7a837.png)

**Comment by justjavac** [comment]
The problem happened on my windows 10 too, and I found this https://github.com/yargs/yargs/pull/1143. Maybe consider upgrading yargs and using `.scriptName` to set `$0` to `"gatsby"`.

**Comment by jonniebigodes** [comment]
@justjavac while searching for something similar recently i stumbled upon that also, i'm currently testing it to see if it will work locally before making a pull request. But if you want to give it a go i don't mind, make the changes and make a pull request and close this issue. I'll leave to your discretion.

**Comment by jonniebigodes** [comment]
@justjavac ok, glad that you made some more progress on the issue, like i said before if you're willing make a pull request and submit it and don't forget to reference this issue. Sounds good?

**Comment by justjavac** [comment]
good

**Comment by jonniebigodes** [comment]
still present as of gatsby cli version 2.4.11 in windows.
Screenshot for demonstrational purposes:
![gatsby_cli](https://user-images.githubusercontent.com/22988955/53192707-0e0e4d00-3607-11e9-8cb7-116edd90bc12.png)
