### ISSUE TITLE
[1.0] Getting travisci back in shape

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#984]
We have a growing collection of tests for 1.0 but TravisCI isn't successfully completing the test suite. The problem it seems has something to do with our use of Lerna as the tests that fail all complain of missing dependencies. Which suggests also that it comes from using `lerna --hoist` which "hoists" package dependencies into the root `node_modules` directory.

There seems two ways to fix this. Fix Jest's module resolution so it works with hoisting or just don't hoist when running tests. The latter isn't the preferred solution as then installing modules takes quite a bit longer.

**Comment by jquense** [comment]
We be great to get Travis up and green again :) I don't think that hoisting should be the issue here, we have a fairly large Lerna repo and jest tests that work in CI without issue at work. In my experience you actually run into way more issues with Dependencies and duplicates when not hoisting, since each package will also install its devDeps to run tests.

**Comment by KyleAMathews** [comment]
Looking at a recent test run, anything jump out to you why there's failures?

**Comment by jquense** [comment]
I think it might be the version of npm on travis? it looks like it might be 2.x.x which will do a hard error on missing peer deps, even if they aren't an issue...perhaps add a pre command to `npm i -g npm` and see if that changes anything?

**Comment by hawkrives** [comment]
I took a stab at cleaning up the 1.0 `.travis.yml`, and (if I install npm@5 first, which becomes stable tomorrow afternoon) everything passes properly.

I re-enabled mac builds, and put node@4 back in, too. (Here's an [example build](https://travis-ci.org/hawkrives/gatsby/builds/237372618), along with the [config](https://github.com/hawkrives/gatsby/blob/1.0/.travis.yml).)

If you're interested, I'll make a PR for it tomorrow.

**Comment by KyleAMathews** [comment]
Hey nifty! Yeah would love a PR!

**Comment by KyleAMathews** [comment]
And maybe swap in 8 for 7 since it's supposed to be out tomorrow?

**Comment by hawkrives** [comment]
Sure, Kk make the PR after 8 comes out - I think in the afternoon sometime.
