### ISSUE TITLE
Why Helmet attribute is not generated on build?

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#9841]
Hi

I want to have a lang attribute on my page.  So I have` <Helmet><html lang="fr" /></Helmet>`

And when I load the static page from Gatsby, it applies the lang after the rendering.
![capture d ecran 2018-11-09 a 12 14 18](https://user-images.githubusercontent.com/814410/48259694-0ab8d200-e419-11e8-94c4-831f0d4e36d4.png)

And when I check the source code, it's not there.
![capture d ecran 2018-11-09 a 12 14 14](https://user-images.githubusercontent.com/814410/48259686-07254b00-e419-11e8-917d-aeccdd71677a.png)

Someone can help please? What's missing?

**Comment by zslabs** [comment]
Do you have https://www.gatsbyjs.org/packages/gatsby-plugin-react-helmet/ installed? That will allow those attributes to be available server-side.

**Comment by Steffi3rd** [comment]
In fact, 

When you try to **Validate by URI** you don't have the `lang` problem.
But if you copy/paste the source code to **Validate by Direct Input**, the `lang` problems appears.

**Comment by LekoArts** [comment]
You're probably using the offline plugin (can't tell without the `gatsby info --clipboard`) so this is most probably related to this: https://github.com/gatsbyjs/gatsby/issues/10017#issuecomment-439946657

**Comment by miller-productions** [comment]
@zslabs mentioned...

> Do you have https://www.gatsbyjs.org/packages/gatsby-plugin-react-helmet/ installed? That will allow those attributes to be available server-side.

---
For anyone reading this issue later... this has happened to me. 

On a scratch site I was playing around with, in my haste I installed [`react-helmet`](https://www.npmjs.com/package/react-helmet), however...

I had completely forgotten to install and configure [`gatsby-plugin-react-helmet`](https://www.npmjs.com/package/gatsby-plugin-react-helmet).

This meant that all the attributes and tags generated by helmet were visible on the client side (i.e. through the 'inspect' function in Chrome dev tools for example), but they were not there when you simply viewed the raw source (i.e. the output generated from build time).

This might be something worth checking if you are encountering a similar issue yourself with missing helmet tags.

The following pages are relevant...

- https://www.gatsbyjs.org/docs/add-page-metadata/
- https://www.gatsbyjs.org/packages/gatsby-plugin-react-helmet/
- https://www.gatsbyjs.org/docs/overview-of-the-gatsby-build-process/
