### ISSUE TITLE
[Feature Request] Unification and simplification of Gatsby data query

### ISSUE THREAD

**Issue by ryanditjia** [gatsbyjs/gatsby#9843]
## Summary

Hey 👋. I thought I’d write about the thing that’s been [on my mind](https://github.com/gatsbyjs/gatsby/issues/7284) for a while. That’s to unify Gatsby’s idiomatic method for querying for data. I’m not familiar with the inner workings of Gatsby, and thus I have no knowledge of whether or not this API is possible. Purely coming from a user perspective.

### Basic example

I imagine Gatsby’s data as if coming from a Context up higher in the tree. If so, `useQuery` here can be imagined as a custom hook that calls `useContext`.

#### Without variables (a la StaticQuery)

`src/components/Layout.js`

```jsx
import React from 'react'
import { useQuery, gql } from 'gatsby'

const query = gql`
  {
    site {
      siteMetadata {
        title
      }
    }
  }
`

function Layout({ children }) {
  const data = useQuery({ query }) // accepts object
  // function useQuery({ query, variables }) { ... }

  // const data = useQuery(query)
  // alternative implementation, accepts multiple arguments instead
  // function useQuery(query, variables) { ... }

  return (
    <div>
      <header>
        <h1>{data.site.siteMetadata.title}</h1>
      </header>

      <main>{children}</main>

      <footer>Copyright</footer>
    </div>
  )
}

export default Layout
```

#### With variables (a la page query)

`src/templates/Post.js`

```jsx
import React from 'react'
import { useQuery, gql } from 'gatsby'

import Layout from '../components/Layout'

const query = gql`
  query($slug: String!) {
    markdownRemark(fields: { slug: { eq: $slug } }) {
      html
      frontmatter {
        title
      }
    }
  }
`

function Post({ pageContext }) {
  const data = useQuery({
    query,
    variables: {
      slug: pageContext.slug,
    },
  })

  // const data = useQuery(query, { slug: pageContext.slug })
  // alternative implementation mentioned above
  // variables always come with query, so this API makes sense

  const post = data.markdownRemark

  return (
    <Layout>
      <div>
        <h1>{post.frontmatter.title}</h1>
        <div dangerouslySetInnerHTML={{ __html: post.html }} />
      </div>
    </Layout>
  )
}

export default Post
```

### Motivation

Gatsby’s multiple ways of querying for data could be confusing for beginners, and likely annoying for non-beginners. With React Hooks on the horizon, render props will see fewer and fewer uses, rendering StaticQuery “obsolete”. `export const query` of page query always feels too magical for me. So does translation of `pageContext` to query variables.

I’d love to know what you guys think. Thanks for reading.

**Comment by KyleAMathews** [comment]
This is very cool! It probably would be doable and something we should evaluate more once React Hooks get closer to prime-time.

And yeah, unification of query syntax would be great.

Though as @jgierer12 points out, variables have to be known at build-time so the syntax as-is will confuse a lot of people to think they can pass in run-time data.

**Comment by muescha** [comment]
@KyleAMathews react hooks are now released ... should reopened?

**Comment by muescha** [comment]
i see its duplicate of #10482
