### ISSUE TITLE
gatsby-link hover Style

### ISSUE THREAD

**Issue by mrhut10** [gatsbyjs/gatsby#9844]
## Summary
Currently a lot of work for users to set hover styling on Links
I'm wondering if anyone would appreciate a hoverStyle option on gatsby-links ??
or if we need a more generic solution that covers things that aren't links.

### Basic example

```
  import { Link } from 'gatsby'
  const Item = ({ url }) => (
    <Link style={{ /*normal styling*/}} hoverstyle={{/*override style on over*/}} to={url} />
  )
```

### Motivation

Hoping to get feedback if anyone else would like this solution or do we need a more generic solution that covers hover state on more than just links.

If feedback is positive in this regard I'd loved to submit a PR for it.

**Comment by LekoArts** [comment]
Sorry, but I don't see the need here. Styling `gatsby-link` is not different from styling normal links. It may also collide with the CSS solution the user is using (e.g. CSS-in-JS). Last but not least you can create your own Link component if you want that property.

**Comment by mrhut10** [comment]
yeah i think a generic solution would be better anyway so you can do hover on any element
