### ISSUE TITLE
Regarding the usage of toml files

### ISSUE THREAD

**Issue by aje4u2i** [gatsbyjs/gatsby#985]
Could you please explain how you are using config.toml file to display blog title etc in index.js and bio.js files in gatsby starter-blog app.

**Comment by jbolda** [comment]
@aje4u2i can I assume this is on version 0.12.X?

**Comment by jbolda** [comment]
Oh, @KyleAMathews posted in the other issues accidentally.

"config.toml" isn't used any longer in v1. Check out the 1.0 branch of
gatsby-starter-blog
