### ISSUE TITLE
gatsby-plugin-sitemap exclude not working properly

### ISSUE THREAD

**Issue by hackhat** [gatsbyjs/gatsby#9861]
So if the path is "/internal/a/b" it will not be excluded, but if is "/internal/c" will be excluded. Is it a feature or a bug? Excluding "/internal/*"

**Comment by hackhat** [comment]
Fixed with `/internal/**`.

**Comment by dial3x** [comment]
This should be in the documentation.

**Comment by DSchau** [comment]
@dial3x we'd love a PR!

**Comment by DSchau** [comment]
Also I'd be interested to see whether this is actually the case. Per the documentation:

> // The example below will exclude the single `path/to/page` and all routes beginning with `category`

We use minimatch and our exclusion code is [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sitemap/src/internals.js#L19-L21).

Here is what that code _should_ render for filtering routes -> https://runkit.com/dschau/5c6b3fbe8d95840014ce75cd
