### ISSUE TITLE
[gatsby-plugin-offline] html not building on netlify

### ISSUE THREAD

**Issue by kristojorg** [gatsbyjs/gatsby#9867]
## Description

I serve my site using netlify. When I use `gatsby-plugin-offline`, the html does not build. It only produces an html shell. I check by turning off javascript. 

Here is a branch deploy with `gatsby-plugin-offline`:  https://5be8701ce5cd1642c9029441--spine.netlify.com/

Here is one without (that's the only change): https://5be871c3ec8a89588503358e--spine.netlify.com/

Check both by disabling javascript and reloading the page. One has server-rendered html. The other does not. Interestingly, when I build my site locally and check index.html, it is properly rendered. So I'm not sure if this is a netlify issue or what.

### Steps to reproduce

1. Install gatsby-plugin-offline
2. Deploy to netlify
3. Disable javascript
4. Reload page
5. Page is blank, html is just a shell.

I will provide a minimal repro if needed. Want to see if I'm missing something simple first.

### Expected result

HTML should include full SSR page.

### Environment

  System:
    OS: macOS 10.14
    CPU: x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.12.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.77
    Firefox: 57.0.1
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.45 => 2.0.45 
    gatsby-codemods: ^1.0.7 => 1.0.7 
    gatsby-image: ^2.0.20 => 2.0.20 
    gatsby-plugin-flow: ^1.0.2 => 1.0.2 
    gatsby-plugin-google-analytics: ^2.0.7 => 2.0.7 
    gatsby-plugin-manifest: ^2.0.8 => 2.0.8 
    gatsby-plugin-netlify: ^2.0.4 => 2.0.4 
    gatsby-plugin-netlify-cache: ^1.0.0 => 1.0.0 
    gatsby-plugin-offline: ^2.0.13 => 2.0.13 
    gatsby-plugin-react-helmet: ^3.0.1 => 3.0.1 
    gatsby-plugin-sharp: ^2.0.12 => 2.0.12 
    gatsby-plugin-sitemap: ^2.0.2 => 2.0.2 
    gatsby-plugin-styled-components: ^3.0.1 => 3.0.1 
    gatsby-source-contentful: ^2.0.13 => 2.0.13 
    gatsby-source-filesystem: ^2.0.8 => 2.0.8 
    gatsby-transformer-remark: ^2.1.12 => 2.1.12 
    gatsby-transformer-sharp: ^2.1.8 => 2.1.8 
  npmGlobalPackages:
    gatsby-cli: 2.4.3

**Comment by KyleAMathews** [comment]
Try opening up an incognito window with js disabled and then browsing around the site.

Disabling js in the devtools doesn't actually disable the SW. You can also verify that the html is being created by curling files.

**Comment by kristojorg** [comment]
Ah interesting, so it's the service worker causing issues when JS is disabled but the SW is not. Okay, well I'll add it back in then, thanks!
