### ISSUE TITLE
[WIP] Move issues from ichabod/cranes into the gatsbyjs/gatsby repo

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/gatsby#9872]
## Goal
Now that we can easily move over issues from one repo to another, we should start moving issues that were in ichabod/cranes but should be in the public gatsbyjs/gatsby repo.

## Plan
- Review slack messages to finish plan for moving issues over.

**Comment by sidharthachatterjee** [comment]
Not stale

**Comment by sidharthachatterjee** [comment]
This doesn't seem to be necessary anymore. Let's close!
