### ISSUE TITLE
Using React Plugin with Gatsby

### ISSUE THREAD

**Issue by AbhimanyuAryan** [gatsbyjs/gatsby#9874]
I want to use AFrame for VR blog. There's a plugin for React but I don't know how to use this plugin with https://github.com/ngokevin/aframe-react Gatsby

Thanks

**Comment by kakadiadarpan** [comment]
@AbhimanyuAryan Gatsby is powered by React, so you can use it the same way you would use it in a React project.

**Comment by AbhimanyuAryan** [comment]
Thanks got it

**Comment by AbhimanyuAryan** [comment]
Also if I want to turn the markup into an aframe react code. Do I need to
implement a plugin? If yes how to implement a plugin guide would help
