### ISSUE TITLE
gatsby-offline-plugin add as="fetch" to Link, cause W3C error

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#9878]
### Bad value `fetch` for attribute `as` on element `link`.

![capture d ecran 2018-11-12 a 10 55 43](https://user-images.githubusercontent.com/814410/48339908-87da8600-e669-11e8-83af-4b7089fc90f3.png)

### `package.json`
<img width="315" alt="capture d ecran 2018-11-12 a 10 56 10" src="https://user-images.githubusercontent.com/814410/48339933-9628a200-e669-11e8-82a8-a7b3633c9746.png">

**Comment by kakadiadarpan** [comment]
@Steffi3rd I'm not sure why that is happening. As per the [Mozilla standard](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content#What_types_of_content_can_be_preloaded), fetch is a correct value for "as" in case of a JSON file.

**Comment by LekoArts** [comment]
Is W3C even relevant? The times are over when people had W3C banners on their site 😂

**Comment by LakesGeek** [comment]
I'd still like a better answer to this than laughing at the notion of HTML validity.

Is W3C really not relevant these days?  Seems it to me - the only way to ensure all browsers correctly render given HTML is surely to all work to the same agreed standard.  Anyone old enough to remember Internet Explorer 6 ought to remember the absolute chaos that came from everyone ignoring standards and only developing to a method of "well it works for me in my browser".  Do we really want to run the risk of having, say, Chrome becoming the next IE6 in terms of breaking the web for other browsers such as Firefox?

AFAIK, valid code is also a requirement for the A level of WCAG which can be required by accessibility laws in some countries.

**Comment by kapilgorve** [comment]
I also ran into this issue.  I have created an issue on `validator`. 
https://github.com/validator/validator/issues/960

**Comment by kapilgorve** [comment]
@LakesGeek It's fixed now. Validator wont show error for this.

**Comment by LakesGeek** [comment]
Brilliant - never occurred to me that the validator itself was wrong! Thanks for passing it on to the right place.

**Comment by nikant25** [comment]
@kapilgorve _It's fixed now. Validator wont show error for this._

However, the validator test today 2020-11-10 shows this error: 
![valide](https://user-images.githubusercontent.com/22560424/98660829-07c58480-2346-11eb-89f1-4d6719f0d261.jpg)

Is there a way to win?

**Comment by kapilgorve** [comment]
Not sure how html attributes work. I can see that your values are not in quotes. Maybe that's an issue  ? @nikant25

**Comment by nikant25** [comment]
@kapilgorve The same result with quotes: 
_Error: Bad value fetch for attribute as on element link.

From line 12, column 1; to line 12, column 195

th:30em)>↩`<link rel=preload href=https://eutourdata.com/fortif/germ/data/arlfort/arlfortanno.jsonld type='application/ld+json;profile="http://www.w3.org/ns/anno.jsonld"' as="fetch" crossorigin="anonymous">`↩<link

Error: Bad value fetch for attribute as on element link.

From line 13, column 1; to line 13, column 151

onymous">↩<link rel=preload href=https://eutourdata.com/fortif/germ/data/arlfort/csv-metadata.json type=application/csvm+json as="fetch" crossorigin="anonymous">↩<meta_

**Comment by kapilgorve** [comment]
@nikant25 I can see your rel attribute is not enclosed in quotes.

**Comment by nikant25** [comment]
@kapilgorve There are many unquoted elements in the meta preload that are valid. However, for clarification, I have set the quotes, but the result is the same: 
Error: Bad value fetch for attribute as on element link.

From line 12, column 1; to line 12, column 199

th:30em)>↩<link rel="preload" href="https://eutourdata.com/fortif/germ/data/arlfort/arlfortanno.jsonld" type='application/ld+json;profile="http://www.w3.org/ns/anno.jsonld"' as="fetch" crossorigin="anonymous">↩<link

Error: Bad value fetch for attribute as on element link.

From line 13, column 1; to line 13, column 155

onymous">↩<link rel="preload" href="https://eutourdata.com/fortif/germ/data/arlfort/csv-metadata.json" type=application/csvm+json as="fetch" crossorigin="anonymous">↩<meta

**Comment by smismailalam** [comment]
i am also facing same issue
