### ISSUE TITLE
[1.0] Preloader script prefixes not acting as intended when sourcemaps are disabled

### ISSUE THREAD

**Issue by scottyeck** [gatsbyjs/gatsby#988]
Current version: (latest canary at time of writing)
`1.0.0-alpha15-alpha.7211d781`

When I run `gatsby build`, the preloader script prefixes do not match up with the scripts in `/public` - instead, they're just `/x` where `x` is just a single character. Top of `index.html` reads as follows:

```html
<head>
    <link rel="preload" href="/p" as="script" />
    <link rel="preload" href="/p" as="script" />
    <link rel="preload" href="/l" as="script" />
    <link rel="preload" href="/a" as="script" />
    <link rel="preload" href="/c" as="script" />
```

All the while, the assets output to public read as follows:

```
app-58579413a27c41b952ee.js
chunk-manifest.json
commons-97a5dea1afd5fc29d501.js
layout-component---index-249467b39ee2266b325d.js
page-component---src-pages-404-jsx-e1d6c2e05b728281adb2.js
page-component---src-pages-about-jsx-ad9f47b75e2e15931b48.js
page-component---src-pages-app-js-1c46b1e6c9cb8804f709.js
```

(etc.)

Looks like the preloader-link generating mechanism in `static-entry.js` is just slicing off the first character via the `fetchKey` that gets passed to `_.get`.

```js
const fetchKey = `assetsByChunkName[${script}][0]`
```

This gets resolved when I remove the 0-index at the end of the `fetchKey` which makes sense. Will PR, though I wanted to make sure that this was outlined. In the event that this is a use-case specific to us, I'd like to know why.

_(Edit - forgot to actually include the example output)_

**Comment by KyleAMathews** [comment]
This doesn't seem right — the "fetchKey" is for pulling info off the stats.json. The [0] is for getting the first value off the array. Perhaps there's something goofy about the stats.json file your build is producing? Looking at the core example sites, they don't have this problem.

**Comment by scottyeck** [comment]
@KyleAMathews Yeah currently returning a string - any thoughts why this might be happening?

**Comment by KyleAMathews** [comment]
Look at the stats.json file in your public folder.

**Comment by scottyeck** [comment]
@KyleAMathews Looks like there are a few other funky things going on and they all point back to `stats.json` - going to run some comparisons against the examples in core like you suggested.

**Comment by scottyeck** [comment]
@KyleAMathews We disable sourcemaps in production. When I enable them, this goes away. Perhaps the check should be conditional?

**Comment by KyleAMathews** [comment]
Ooo that would do it. Yeah just add a check if its an array and that should
do it.

**Comment by KyleAMathews** [comment]
Haha and just saw your PR doing that :-) will merge and release a bit later.

**Comment by scottyeck** [comment]
@KyleAMathews thanks!

**Comment by KyleAMathews** [comment]
Merged and published new canary
