### ISSUE TITLE
Add an `auto-config` section to the debugging doc

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#9880]
## Summary

Add a new section to the [debugging the build process doc](https://www.gatsbyjs.org/docs/debugging-the-build-process/).

Maybe also restructure the document so the sections go from 'simplest' to 'most complex', like this:

- VS Code debugger (automatic config) _<-- this is the new section_
- VS Code debugger (manual config)
- Chrome DevTools for Node

### Basic example

If you use VS Code and its integrated terminal, you can configure it to automatically create the debug config for you:

- Enable the VS Code setting `Debug > Node: Auto Attach`
- Using VS Code's integrated terminal run `node --inspect node_modules/.bin/gatsby develop` instead of `gatsby develop`
- debug!

These steps are based on the following article: https://itnext.io/the-absolute-easiest-way-to-debug-node-js-with-vscode-2e02ef5b1bad

### Motivation

This reduces the friction of setting up a debug environment, which can make it easier to track down build process errors.

**Comment by axhon** [comment]
I've taken a stab at this. I will make a PR momentarily.

**Comment by axhon** [comment]
The fix to this has been merge #9937
