### ISSUE TITLE
react-hot-loader error on IE11

### ISSUE THREAD

**Issue by rgllm** [gatsbyjs/gatsby#9881]
## Description

react-hot-loader is broken on IE because of Polyfills import. The issue is related with these: [4.3.12 breaks polyfills for IE11](https://github.com/gaearon/react-hot-loader/issues/1099).

### Environment

npmPackages:
    gatsby: ^2.0.31 => 2.0.45
    gatsby-image: ^2.0.17 => 2.0.19
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.1
    gatsby-plugin-sass: ^2.0.1 => 2.0.3
    gatsby-plugin-sharp: ^2.0.8 => 2.0.12
    gatsby-plugin-typescript: ^2.0.0 => 2.0.1
    gatsby-source-filesystem: ^2.0.5 => 2.0.7
    gatsby-transformer-json: ^2.1.4 => 2.1.5
    gatsby-transformer-sharp: ^2.1.5 => 2.1.8

  npmGlobalPackages:
    gatsby-cli: 2.4.0

**Comment by rgllm** [comment]
@kakadiadarpan the problem seems solved on `react-hot-loader` side. I think Gatsby should update the dependency.

**Comment by DSchau** [comment]
Seems like the fix! To fix this we need to upgrade our react-hot-loader dep, and then validate no regressions.

See: gaearon/react-hot-loader#1099 for the fix

**Comment by DSchau** [comment]
Also we'd (apparently!) get React Hooks support by updating to at least 4.4.2 ❤️ https://github.com/gaearon/react-hot-loader/blob/7c0f9a04bce89801d387b277251c2b00da525534/README.md#-hot-labs-
