### ISSUE TITLE
Why ...GatsbyImageSharpFixed is unknown fragment in GraphiQL?

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#9882]
![capture d ecran 2018-11-12 a 12 22 23](https://user-images.githubusercontent.com/814410/48344545-afcfe680-e675-11e8-8934-6c525bc2a1fc.png)

### `package.json`
<img width="318" alt="capture d ecran 2018-11-12 a 12 23 37" src="https://user-images.githubusercontent.com/814410/48344589-d2fa9600-e675-11e8-9183-2da7111e27b9.png">

**Comment by Steffi3rd** [comment]
Found the answer : **Due to some limitations**

![capture d ecran 2018-11-12 a 13 14 31](https://user-images.githubusercontent.com/814410/48348211-f2e38700-e680-11e8-8c5e-c8f18f0d1bb4.png)

**Comment by djm** [comment]
For those hitting this or similar fragment errors in GraphQL, a quick work-around is to just look up the fragments yourself and use them manually.

For the example above, this would be:

1) Remove ...GatsbyImageSharpFixed.
2) Put the fields instead:

```   
    fixed() {
        base64
        width
        height
        src
        srcSet
    }
```

Other Image-related fragments can be [found here](https://github.com/gatsbyjs/gatsby/blob/26582d31ab14f7bac6d5738e4245ceca2e6d411d/packages/gatsby-transformer-sharp/src/fragments.js#L6).

**Comment by luisramirez7** [comment]
@djm you sir saved my ass. thank you so much!

**Comment by sreeharshrajan** [comment]
> For those hitting this or similar fragment errors in GraphQL, a quick work-around is to just look up the fragments yourself and use them manually.
> 
> For the example above, this would be:
> 
> 1. Remove `...GatsbyImageSharpFixed`.
> 2. Put the fields instead:
> 
> ```
> fixed(width: 400) {
>     base64
>     width
>     height
>     src
>     srcSet
> }
> ```
> 
> Other Image-related fragments can be [found here](https://github.com/gatsbyjs/gatsby/blob/26582d31ab14f7bac6d5738e4245ceca2e6d411d/packages/gatsby-transformer-sharp/src/fragments.js#L6).

Further more, If you are trying to retrieve the image, then make sure you did the following right,

1. Added the `gatsby-transformer-sharp` plugin and `gatsby-image`
2. Importing the graphql-image; import Img from "gatsby-image"
3. Retrieving the link from graphql 
            export const pageQuery = graphql`
            query IndexQuery {
                  allStrapiPost {
                     edges {
                           node {
                               image {
                                 childImageSharp {
                                    fixed(width: 200, height: 125) {
                                       src
                                     }
                                 }
                              }
                        }
                    }
               }
            }
         `
4.  Passing the link into js part
       const IndexPage = ({ data }) => (
        <div>
                 {data.allStrapiPost.edges.map(document => (
                      {document.node.image && (
                         <Img
                              fixed={document.node.image.childImageSharp.fixed}
                               imgStyle={{ position: "static", borderRadius: "50%" }} //css
                         />
                      )}
                  ))}
        </div>
)
