### ISSUE TITLE
Why graphql returns undefined whereas GraphiQL returns something?

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#9884]
### console.log(data) returns undefined

<img width="454" alt="capture d ecran 2018-11-12 a 13 53 41" src="https://user-images.githubusercontent.com/814410/48348751-7e114c80-e682-11e8-831e-9516b0ad3aa4.png">

### GraphiQL

![capture d ecran 2018-11-12 a 13 54 11](https://user-images.githubusercontent.com/814410/48348766-8b2e3b80-e682-11e8-93cd-02f8f7ff8418.png)

**Comment by Steffi3rd** [comment]
I tried alternative with `StaticQuery` and it worked.

I don't know why it doesn't work without `StaticQuery`

Someone can help please?

**Comment by LekoArts** [comment]
Please open an issue following the issue template (as I already told you). Otherwise we cannot help you. The issue template exists for a reason.
