### ISSUE TITLE
Cannot resolve ../public/styles.css

### ISSUE THREAD

**Issue by emilbruckner** [gatsbyjs/gatsby#990]
I haven't changed anything in my `html.js` and got this error:

```
Error: ./html.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./public/styles.css in /opt/build/repo
resolve file
```

I tried `!raw-loader!../public/styles.css`, `!raw!../public/styles.css`, `!raw-loader!./public/styles.css` and `!raw!./public/styles.css` but no success so far …

Can anyone help?
Thanks

**Comment by KyleAMathews** [comment]
What version of Gatsby are you using?

Is there a `styles.css` in your public directory?

**Comment by emilbruckner** [comment]
No, there is only `render-page.js` in there

Do you think it actually fails at some other point?

**Comment by KyleAMathews** [comment]
Do you import any css? If not, there won't be a styles.css created. Is the
requiring of the styles.css inside a try/catch?

**Comment by emilbruckner** [comment]
I have some css inside the `css` folder if that's what you're asking for
My project is based on the default-starter and now just stopped working, I have no idea why …

**Comment by emilbruckner** [comment]
I used a new starter, had to clean up anyway, obviously works now
 
Still haven't found out what caused the problem, but closing this

**Comment by eyar** [comment]
I'm getting the following error:

{ Error: Cannot find module "!raw-loader!../public/styles.css"
    at webpackMissingModule (render-page.js:38544:82)
    at Object.<anonymous> (render-page.js:38544:191)
    at __webpack_require__ (render-page.js:30:30)
    at Object.<anonymous> (render-page.js:84:13)
    at __webpack_require__ (render-page.js:30:30)
    at Object.assign.i (render-page.js:50:18)
    at render-page.js:53:10
    at webpackUniversalModuleDefinition (render-page.js:3:20)
    at render-page.js:10:3
    at ContextifyScript.Script.runInContext (vm.js:35:29) code: 'MODULE_NOT_FOUND' }

Using windows, with and without starter, version 1.9.238
