### ISSUE TITLE
How to use gatsby-image with data from GraphQuery?

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#9905]
## Summary

I have this as a GraphQL:

```
              portrait_author {
                url
                alt
                dimensions {
                  width
                  height
                }
              }
```

And I would like to use fluid of Gatsby-image : `...GatsbyImageSharpFluid` 

```
    childImageSharp {
      fluid(maxWidth: 1000) {
        ...GatsbyImageSharpFluid
      }
    }
```

So the idea is to replace `dimensions` with Gatsby-Image. But it doesn't work.

```
              portrait_author {
                url
                alt
                childImageSharp {
                    fluid(maxWidth: 1000) {
                       ...GatsbyImageSharpFluid
                    }
                 }
              }
```

The final result is to use it with something like this : `<Img fluid={props.data.portrait_author.childImageSharp.fluid} />`

**How can I do this please?**

### Environment 

```
  System:
    OS: macOS 10.14
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.77
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.24 => 2.0.43 
    gatsby-image: ^2.0.15 => 2.0.20 
    gatsby-plugin-lodash: ^3.0.1 => 3.0.2 
    gatsby-plugin-manifest: ^2.0.5 => 2.0.8 
    gatsby-plugin-offline: ^2.0.6 => 2.0.13 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.1 
    gatsby-plugin-sharp: ^2.0.7 => 2.0.12 
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.2 
    gatsby-source-prismic: ^2.0.0 => 2.1.0 
    gatsby-transformer-sharp: ^2.1.4 => 2.1.8 
  npmGlobalPackages:
    gatsby-cli: 2.4.5
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by kakadiadarpan** [comment]
@Steffi3rd did you had a chance to go through the example of [using-gatsby-image](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-gatsby-image)?

**Comment by kakadiadarpan** [comment]
Also, you can check this example query in the documentation of [gatsby-image](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-image#query-1) which uses `GatsbyImageSharpFluid_noBase64`

**Comment by oorestisime** [comment]
if i understand correctly what you are trying to do: the image you have is not available locally? because gatsby-image only works with local images. providing a url can not work

**Comment by Steffi3rd** [comment]
> if i understand correctly what you are trying to do: the image you have is not available locally? because gatsby-image only works with local images. providing a url can not work

Yeah! This is exactly what I wanted to do
