### ISSUE TITLE
[1.0] Add testing for the Gatsby runtime

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#991]
Gatsby renders itself in three different places.

* Development
* Static builds
* Production

Each has their own special case of requirements based on their environment but each needs to support all the same features and appear to the user to work the same.

Currently I test this by me manually making them work the same 😅 Since this is one of the most critical parts of Gatsby we need to make this part of the code base a lot more robust.

Ideally we'd extract out the common parts into a common module(s) which we make well tested.

**Comment by jlengstorf** [comment]
Related: #7620

**Comment by LekoArts** [comment]
Can this issue be closed?

**Comment by sidharthachatterjee** [comment]
Closing this since we now have end to end tests for the development and production runtime. Please reopen if necessary.
