### ISSUE TITLE
Force remove service worker?

### ISSUE THREAD

**Issue by hamishtaplin** [gatsbyjs/gatsby#9913]
## Summary

I have a website in development and I initially started with `gatsby-plugin-offline` enabled but decided I don't want to use it anymore. The problem is that the service worker is already registered so pushing updates for client to look at just result in it loading an old version. I don't really want to have to explain how to unregister the sw to them. Is there a way I can force its removal?

**Comment by DSchau** [comment]
Yup!

[`gatsby-plugin-remove-serviceworker`](https://www.npmjs.com/package/gatsby-plugin-remove-serviceworker)

Going to close this out as answered, but please feel free to re-open if we can assist further. Thanks!

**Comment by flaviolivolsi** [comment]
This is priceless and I think it should be added somehow in the `gatsby-plugin-offline` documentation.
