### ISSUE TITLE
Programatically adding a prefix from a plugin

### ISSUE THREAD

**Issue by TylerBarnes** [gatsbyjs/gatsby#9915]
Is it possible to programatically add a site prefix or can it only be done from gatsby-config.js?

**Comment by kakadiadarpan** [comment]
@TylerBarnes At the moment it can only be done from `gatsby-config.js`

**Comment by TylerBarnes** [comment]
@kakadiadarpan thanks for the quick response! That's what I suspected. Thanks for the confirmation. My plugin is running partially outside of gatsby. Maybe I'll have it temporarily rewrite the config file and then put the old one back. 🤣
