### ISSUE TITLE
On build WebpackError: TypeError: Cannot read property 'childImageSharp' of null

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#9917]
<img width="854" alt="capture d ecran 2018-11-13 a 19 40 32" src="https://user-images.githubusercontent.com/814410/48469005-cdc05700-e7ed-11e8-94e9-8f80fa99a6db.png">

## Summary

It works perfectly on develop but when I `gatsby build` I have this error.

### Environment 

```
  System:
    OS: macOS 10.14
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.77
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.24 => 2.0.43 
    gatsby-image: ^2.0.15 => 2.0.20 
    gatsby-plugin-lodash: ^3.0.1 => 3.0.2 
    gatsby-plugin-manifest: ^2.0.5 => 2.0.8 
    gatsby-plugin-offline: ^2.0.6 => 2.0.13 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.1 
    gatsby-plugin-sharp: ^2.0.7 => 2.0.12 
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.2 
    gatsby-source-prismic: ^2.0.0 => 2.1.0 
    gatsby-transformer-sharp: ^2.1.4 => 2.1.8 
  npmGlobalPackages:
    gatsby-cli: 2.4.5
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by oorestisime** [comment]
Hello can you please provide a minimal reproduction repo?

**Comment by Steffi3rd** [comment]
I found why...

With `gatsby develop`, Gatsby doesn't execute **each** post.
With` gatsby build`, Gatsby does.

In fact, I had post which has the field `image`, I didn't see it on develop.

So I just had a condition to display this `<Img ... />`

**Comment by laradevitt** [comment]
I came across this error and just wanted to clarify for others what @Steffi3rd is saying above:

From Kyle Mathews' https://github.com/gatsbyjs/gatsby/issues/8481#issuecomment-424143867:

> Yeah, develop doesn't try to render every page on your site like a build will so errors can creep into pages you're not actively looking at and not get discovered until a build happens. 

It should be obvious but, I confess, I sometimes forget this.

So if you see the error it's likely there is an item (page or post or whatever the image should be attached to) that's missing an image. 

Fixed by adding condition:

```javascript
{data.image.localFile
  && (
    <Image
      fluid={data.image.localFile.childImageSharp.fluid}
    />
  )
}
```

**Comment by SudhirKaushik** [comment]
Was stuck from 3 days and I followed the advice
`gatsby clean`
`gatsby build`
`gatsby develop`

Caching is quite a problem with emerging JavaScript technologies

**Comment by Rickyhobbs** [comment]
I had this issue and it was caused by removing some necessary images from the src/content/img directory. 
I put those files (images) back and it builds correctly now.

**Comment by LincMitch** [comment]
I  did this:
`gatsby clean`
`gatsby build`
`gatsby develop`
But didn't work. So I removed the image from the directory and put it back. But didn't work. 
I **renamed** the file and it worked. So a caching issue of sorts it seems.

**Comment by marcolivierarcand** [comment]
> Was stuck from 3 days and I followed the advice
> `gatsby clean`
> `gatsby build`
> `gatsby develop`
> 
> Caching is quite a problem with emerging JavaScript technologies

God... thank you ! You saved my life !
