### ISSUE TITLE
React deprecation warnings

### ISSUE THREAD

**Issue by sillyslux** [gatsbyjs/gatsby#992]
with gatsby@0.12.46 i still get deprecation warnings from some dependencies, so i ran
```
$ npm i -S history@^3.3.0 react-router@^3.0.5 react-router-scroll@^0.4.2 scroll-behavior@^0.9.3
```
and got rid of them, i didn't run gatsby's tests though...

**Comment by KyleAMathews** [comment]
Want to make a PR so tests run? RR v3 should be an easy upgrade from v2.

**Comment by sillyslux** [comment]
okay... that means i'll first look how react-router is tied into gatsby and try to identify any side-effects resulting from that upgrade, so give me some time.
