### ISSUE TITLE
Using StaticQuery in html.js

### ISSUE THREAD

**Issue by k3rn31p4nic** [gatsbyjs/gatsby#9921]
## Summary
I'm overriding `html.js` to add some data dynamically which I'm trying to get using GraphQL (using `StaticQuery`). Turns out it doesn't work, it compiles successfully and website opens up, but all it shows is this: `Loading (StaticQuery)`. Is this a bug or `html.js` doesn't support `StaticQuery`?

Since `StaticQuery` is (or rather, should be) supported by *any* component (as mentioned [here](https://www.gatsbyjs.org/docs/static-query/#how-staticquery-differs-from-page-query)) and as `html.js` is a React component after all, can I know why `html.js` doesn't support it?

## Relevant information
If you need any more relevant details, lemme know and I'll add them.

**Comment by LekoArts** [comment]
Why are you modifying the file? 
And no, I most certainly think that GraphQL in general doesn’t work there. You can do everything with Gatsby’s APIs, there should be no need to modify this file.

**Comment by k3rn31p4nic** [comment]
Yeah. I'm just experimenting with it, to find its limits. Like, `StaticQuery`, does it not support it or is it a bug that's preventing it from working?

**Comment by kakadiadarpan** [comment]
@k3rn31p4nic `html.js` doesn't support `StaticQuery`. Check the documentation for [customizing html.js](https://www.gatsbyjs.org/docs/custom-html/), it only does things mentioned there.

**Comment by LekoArts** [comment]
I'd just advise not to modify this file unless you absolutely have to.

**Comment by k3rn31p4nic** [comment]
@kakadiadarpan The docs doesn't say anywhere that the `html.js` doesn't support `StaticQuery`. Since the `html.js` is a React Component after all, it should be supporting `StaticQuery` as stated [here](https://www.gatsbyjs.org/docs/static-query/#how-staticquery-differs-from-page-query):
![image](https://user-images.githubusercontent.com/19631364/48542072-20654600-e8b6-11e8-804b-8fa30a058cc9.png)

Therefore, my original question still stands and I'd like this issue to be reopened.
