### ISSUE TITLE
StaticQuery with React.createElement returns loading state

### ISSUE THREAD

**Issue by Siilwyn** [gatsbyjs/gatsby#9927]
## Description
Calling `StaticQuery` with `React.createElement` instead of JSX causes the output of `gatsby build` to be "Loading (StaticQuery)". Interestingly enough I see multiple closed issues around `StaticQuery` hanging and found that I get mixed results when using `gatsby develop`.

I made a repository to reproduce the issue, took the default gatsby starter and changed [layout](https://github.com/Siilwyn/gatsby-static-query-no-jsx/blob/master/src/components/layout.js) to contain:
```js
const Layout = ({ children }) => React.createElement(
  StaticQuery,
  {
    // to shorten this example I took out the actual query and handler
    query: graphql``,
    render: handler
  }
)
```

### Steps to reproduce
1. `git clone https://github.com/Siilwyn/gatsby-static-query-no-jsx.git`
2. `cd gatsby-static-query-no-jsx; npm ci`
3. `npm run build; npm run serve`

### Expected result
See the default gatsby starter output including the queried data.

### Actual result
A blank page with "Loading (StaticQuery)".

### Environment
```
  System:
    OS: Linux 4.18 Solus 3.9999
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 2.7.1 - /usr/bin/fish
  Binaries:
    Node: 10.13.0 - /usr/bin/node
    Yarn: 1.10.1 - ~/.local/bin/yarn
    npm: 6.4.1 - /usr/bin/npm
  Browsers:
    Firefox: 63.0.1
  npmPackages:
    gatsby: ^2.0.19 => 2.0.19 
    gatsby-image: ^2.0.15 => 2.0.15 
    gatsby-plugin-manifest: ^2.0.5 => 2.0.5 
    gatsby-plugin-offline: ^2.0.11 => 2.0.11 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-sharp: ^2.0.7 => 2.0.7 
    gatsby-source-filesystem: ^2.0.4 => 2.0.4 
    gatsby-transformer-sharp: ^2.1.4 => 2.1.4 
```

**Comment by kakadiadarpan** [comment]
This is strange.

@pieh this should have worked, right?

**Comment by Siilwyn** [comment]
Let me know if I can help and/or provide more info.

**Comment by pieh** [comment]
During builds we do some transformation on code for StaticQuery and for now we handle just JSX there: https://github.com/gatsbyjs/gatsby/blob/8c90c50109e320fe4c2cc0f2999a69c5edf58b02/packages/gatsby/src/internal-plugins/query-runner/file-parser.js#L128-L133

So this isn't strictly a bug - it's limitation - it might be worth adding note about it to documentation (or add support for `React.createElement` when parsing AST)

**Comment by Siilwyn** [comment]
Ouch, that is a bit more magic than I anticipated. I thought `StaticQuery` is just a react component. :(

@pieh this makes me wonder why does it sometimes work with `gatsby develop`? I actually use it with https://github.com/choojs/hyperx which in turn calls react ,also wonder if supporting `React.createElement` will make `hyperx` usable too...

**Comment by DSchau** [comment]
> I thought StaticQuery is just a react component. :(

It is :) [See here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/gatsby-browser-entry.js#L13-L37)

The magic is parsing the graphql prop/template literal that's _within_ the StaticQuery component (and in a page query!).

**Comment by DSchau** [comment]
@Siilwyn exactly!

> Sorry for going offtopic here but do you know why this is done? I would think (naively?) that all queries can be retrieved by letting them get passed to StaticQuery and save them globally in some sort of collection.

Remember that this is at build time. The idea is that we _need_ to parse (and grab!) the results of that query with a build process rather than a runtime process, and this works really well and is one of the core ideas behind Gatsby! So the build process will grab the graphql tag, grab the query, run and parse that query, and then inject your component with that resultant data. Pretty neat stuff!

As far as the original question, I'm going to close this as "solved" (i.e. use JSX instead of React.createElement) but I do think there could be some value in documenting this short coming or _fixing_ the underlying issue by traversing the AST and doing a similar process for React.createElement.

Thanks for the question!

**Comment by Siilwyn** [comment]
So should I create a new issue about supporting `React.createElement`?

**Comment by DSchau** [comment]
@Siilwyn is there a reason you want to use React.createElement rather than `<StaticQuery />`?

**Comment by DSchau** [comment]
But yeah - feel free. This should either be documented (easier!) or fixed.

**Comment by Siilwyn** [comment]
Well mainly because I don't like JSX that much and prefer templating with `hyperx` or `hyperscript`.
