### ISSUE TITLE
Automated gatsby docker images

### ISSUE THREAD

**Issue by ghost** [gatsbyjs/gatsby#993]
I created the automated `gatsby` docker images to simplify the overall working experience.

- [github](https://github.com/g8tguy/gatsby-docker)
- [docker hub](https://hub.docker.com/r/g8tguy/gatsby/)

So, now it requires zero configuration to start working on your project. No need to install `nodejs`, `python`, `git` etc on your local machine - the `docker` will handle it for you. The images are extremely compact and include latest nodejs, yarn and preinstalled global gatsby. Actually, it takes less than two minutes to start working on your project!

As a start point I automated the basic images, from which we can inherit more complex behaviors.

There are multiple precompiled gatsby images:

- legacy 0.x, (for each release starting from v0.12.44)
- next 1.x (for each release starting from v1.0.0-alpha14)
- dev canary with lerna and dev-cli embedded. (rebuild once a day)

Right now I'm working on detailed tutorials, explaining a more streamlined experience using `docker compose`.

What I need from you guys is feedback in the form of suggestions/criticism/remarks/whatever in order to improve the gatsby-docker functionality to it's best.

**Comment by KyleAMathews** [comment]
Woah! This sounds fantastic! So you'd just run the docker image instead of running Gatsby directly?

**Comment by thetwosents** [comment]
+1 love dis. dc up all the things. great for deployment also.

**Comment by akadop** [comment]
@KyleAMathews 

sounds about right. since it's linux based you don't need to worry about the multiple errors windows throws out when it comes to dealing with nodegyp / python / the sharper plugin, or even the page building process ( i know it was worked around by using the slash dependency )

**Comment by cmrn** [comment]
OP has deleted their account so sadly this docker image is no longer available. Maybe the Gatsby project could start publishing images themselves?

**Comment by KyleAMathews** [comment]
@cmrn would you like to take this on?

**Comment by KyleAMathews** [comment]
https://github.com/gatsbyjs/gatsby-docker is already largely there.

**Comment by rafaelrpbelo** [comment]
The links are broken.

**Comment by loganpowell** [comment]
Having some issues on Windows deploying gatsby to a static site host  (e.g., Netlify, github pages). Something like this would be handy. Sorry to ping on a closed issue...

**Comment by m-allanson** [comment]
@loganpowell There's a new Gatsby-Docker tool that might be useful - see #4085
