### ISSUE TITLE
[gatsby-source-wordpress] How to safe query images from ACF in case if image is not set

### ISSUE THREAD

**Issue by ikhudo** [gatsbyjs/gatsby#9936]
## Summary

How to handle situations when ACF image field is not required field and some posts has it set and other not? Build crashes with error `error GraphQL Error Field "general_post_icon" must not have a selection since type "String" has no subfields.`

```
143 |           post_excerpt
  144 |           acf {
> 145 |             general_post_icon {
      |                               ^
  146 |               localFile {
  147 |                 childImageSharp {
  148 |                   fixed(width: 150) {
  149 |                     ...GatsbyImageSharpFixed
  150 |                   }
  151 |                 }
  152 |               }
  153 |             }
  154 |           }
```

**Comment by pieh** [comment]
@ikhudo did you check https://www.gatsbyjs.org/packages/gatsby-source-wordpress/#troubleshooting ?
