### ISSUE TITLE
Gatsby kill CLI command

### ISSUE THREAD

**Issue by ChariseWalraven** [gatsbyjs/gatsby#9940]
## Summary

Hi there! I've noticed that when running gatsby serve, sometimes when I want to stop serving, hitting `ctrl` + `c` doesn't work, so I've had to manually kill port processes from another tab. It would be nice if you could write some cli command to forcibly kill the process on the port that Gatsby is running on.

### Motivation

It would make life easier by a long shot. If you don't choose to make the feature, at leat fix the issue of the process not being able to be quit. 😄

**Comment by DSchau** [comment]
I don't necessarily think this makes sense to integrate into gatsby itself. Perhaps utilize something like [`fkill-cli`](https://github.com/sindresorhus/fkill-cli) which is more general purpose

Also I'd be interested to hear more about _why_ Ctrl + C doesn't work! Could you run `gatsby info` (or `npx gatsby info`) and paste some details?

Going to close this out for now, but please re-open if we can assist further!

**Comment by jonniebigodes** [comment]
@ChariseWalraven that happens often with me when using either vscode with the terminal embedded, or the actual console itself. It's not actually a gatsby issue, but the terminal, from my research the constant updates to the console tend to fill the console buffers and that leads to that behaviour. I have to wait up to a minute sometimes to see the actual prompt on the console to terminate what i'm doing.
