### ISSUE TITLE
[gatsby-source-drupal] [documentation] Document how to handle field relationships to different entities' bundles - taxonomy, ct, paragraphs

### ISSUE THREAD

**Issue by hanoii** [gatsbyjs/gatsby#9945]
## Description

I am not able to query [paragraphs](https://www.drupal.org/project/paragraphs) content through graphQL

### Steps to reproduce

Hope that the following jsonapi output serves as an example.

https://master-7rqtwti-ykkhux5z34wve.us-2.platformsh.site/jsonapi/node/metadata

`field_sites` is a multiple core taxonomy term reference field, and `filed_content` is a multiple paragraphs field that holds different items.

I believe the JSONAPI looks OK in the sense that the information is there and properly formatted (following the links for `field_sites` and `field_content` provide a very similar output, the only difference is the `meta` property on `field_content`

I am working with the following graphQL as an example: 

```
{
 allNodeMetadata {
   edges {
     node {
    	relationships {
        field_sites {
          name          
        }
        field_content {
          __typename
        }
      }
     }
   }
 }
}
```

### Expected result

I should be able to get relationship fields from the related paragraphs entities.

### Actual result

`field_sites` properly work in the sense that I get the referenced fields information, however for `field_content` the only thing I can query is `__typename`.

### Environment

```
  System:
    OS: macOS 10.14.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 2.7.1 - /usr/local/bin/fish
  Binaries:
    Node: 8.11.4 - ~/.nvm/versions/node/v8.11.4/bin/node
    Yarn: 1.12.1 - ~/.nvm/versions/node/v8.11.4/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.11.4/bin/npm
  Browsers:
    Firefox: 63.0.1
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.49 => 2.0.49 
    gatsby-image: ^2.0.20 => 2.0.20 
    gatsby-plugin-manifest: ^2.0.9 => 2.0.9 
    gatsby-plugin-offline: ^2.0.15 => 2.0.15 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.2 
    gatsby-plugin-sharp: ^2.0.12 => 2.0.12 
    gatsby-source-drupal: ^3.0.9 => 3.0.9 
    gatsby-source-filesystem: ^2.0.8 => 2.0.8 
    gatsby-transformer-sharp: ^2.1.8 => 2.1.8 
  npmGlobalPackages:
    gatsby-cli: 2.4.5
```

**Comment by dcorb** [comment]
I'm glad to see more Drupal people taking this approach using paragraphs + Gatsby. We found this exact same issue some weeks ago

`field_content` represents a GraphQL Union type with all the paragraph types available for the field

You can keep exploring inside this field using this type of queries:
```
     field_content {
          __typename
          ... on paragraph__images {
               field_paragraph_id
               relationships {
                    more_interesting_fields_here
              }
            }
            ... on paragraph__text {
               field_paragraph_id
            }
      }
          
```

**Comment by hanoii** [comment]
@dcorb so thanks! As I mentioned to you on Slack I did find out about this earlier in the day.

Here are some related links:
- https://github.com/gatsbyjs/gatsby/issues/2307#issuecomment-333619174 
- https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-wordpress#query-with-acf-flexible-content

And this is actually happening for any reference that holds two different types of relationships. 

So paragraphs ARE working, I would close this issue but I will  change it to a document task for the drupal plugin to address this information, kind of the wordpress one.

**Comment by apmsooner** [comment]
I'm not able to see paragraph fields at all in the graphql query builder. I do see them in the jsonapi output. What am i missing here?

**Comment by hanoii** [comment]
@apmsooner are you using the paragraphs fragments as per https://github.com/gatsbyjs/gatsby/issues/9945#issuecomment-441115895 ?

Can you post your graphql?

**Comment by apmsooner** [comment]
@hanoii, I think my problem was that I didn't have the paragraph type enabled in the jsonapi settings. Once I enabled it and reran gatsby develop, i can see the field available in relationships. Coincidentally, the paragraph fields are also available without the extra joins as depicted in #9945. I did just recently update jsonapi and jsonapi_extras modules. I didn't really want to enable the paragraph type in jsonapi though because there are 43,000+ of those entities on my site and wanted a faster build. That might make sense why my images weren't showing as fields either cause i had the file entity excluded from json api as well. I really thought all of these items would be exclusive to the node type itself...

**Comment by DhillonN** [comment]
@hanoii  is this feature broken in new builds? I can't seem to get Paragraph fields only field I get is 
target_revision_id nothing else :/ 
I have a Paragraph type Called willdelete which Contains two Fields 
1.) field_check_it. 
2.)field_image_check
Paragraph Type is Part of ContentType called tobedeleted
this content type contains field_tre which is Paragraph reference type

now when i Run Following Graphql Query
```
{
  allNodeTobedeleted{
    edges{
      node{
       field_tre{
        target_revision_id
        __typename
      }
      }
    }
  }
}
```
I don't see willdelete typename in result 
following is the output of query
`{
  "data": {
    "allNodeTobedeleted": {
      "edges": [
        {
          "node": {
            "field_tre": [
              {
                "target_revision_id": 2,
                "__typename": "node__tobedeletedField_tre"
              },
              {
                "target_revision_id": 3,
                "__typename": "node__tobedeletedField_tre"
              }
            ]
          }
        }
      ]
    }
  }
}`
any ideas what I am doing wrong here.
any help will be much appreciated

**Comment by ascorbic** [comment]
Hi @DhillonN 
I think you'll find the data under `relationships`, so your example should be:

```graphql
{
  allNodeTobedeleted {
    edges {
      node {
        relationships {
          field_tre {
            field_check_it
            field_image_check
          }
        }
      }
    }
  }
}

```

**Comment by DhillonN** [comment]
@ascorbic thanks for your reply, when i don't see those fields under relationships only available options are 
```
node_type
 revision_uid
  uid
```

**Comment by wesleyduff** [comment]
I can see the data, however, when choosing to run a build / update on drupal w/ paragraphs, I get an error saying drupal replace is not working
