### ISSUE TITLE
"Awesome Gatsby" missing in sidebar?

### ISSUE THREAD

**Issue by LekoArts** [gatsbyjs/gatsby#9947]
## Description

I couldn't find this site on the sidebar on the docs:
https://www.gatsbyjs.org/docs/awesome-gatsby/

@shannonbux & @amberleyromo 
Am I'm just blind or did someone accidentally remove this site? 😆

**Comment by amberleyromo** [comment]
Yep, it looks like you're right... I could swear it was linked before, but maybe not / maybe removed somewhere along the line.

@shannonbux would know better!

**Comment by shannonbux** [comment]
Yeah, actually making sure we don't lose docs from the sidebar has been a manual process (and a tricky one at that!) so I'll add this back in and also--do ya'll have any ideas on how to make sure we don't forget to add any docs to the sidebar? 

I assume this just has to be done manually (by looking at docs and making sure none of them are missing). Just wanted to be aware in case there is a faster way to do this!

**Comment by LekoArts** [comment]
The sidebar contains links to the files, the files have the exact same name as the links (obviously) so one could write a script that compares all links in the sidebar file with the filenames of the docs.

**Comment by shannonbux** [comment]
Cool. It's not a high priority, but would be a great part of a long-term
docs maintenance plan. I will add that idea to my long-term planning doc :)
