### ISSUE TITLE
[gatsby-source-drupal] Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.

### ISSUE THREAD

**Issue by phonoman** [gatsbyjs/gatsby#9950]
## Description

We have a private source Drupal 8.6.2 server that we can access fine and could get data from, but recently (after a content update) the `gatsby develop` started to fail.
We're getting a lot of  `Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "6E0F4D382F504Ac5837DF8B7C8618485_2" does not.` kind of errors _(string differs on each one)_ after recently updating our source server with the most recent production content.. 

### Steps to reproduce

I'm afraid there isn't really much to the issue and how to reproduce since it happened to us suddenly after a good while of working on it..

Add plugin to the list and install it, 
Try to launch gatsby develop.
```
{
      resolve: `gatsby-source-drupal`,
      options: {
        baseUrl: `oursite.io`,
        apiBase: `jsonapi`,
      },
},
```

### Expected result

Gatsby environment should get built and have access to the content on Drupal 8.6.2 site.

### Actual result

The environment didn't launch. 
Instead we get a lot of `Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "6E0F4D382F504Ac5837DF8B7C8618485_2" does not.` messages. 
I already checked the database dump and none of those uuid looking strings (they're same length as drupal uuid's) exist in the dump and cannot be found anywhere. 
So this is even more of a mystery since `gatsby-source-drupal` plugin is throwing out errors.. About **names** that don't even exist in the source? 
I'm convinced that this plugin is somehow flawed as removing `gatsby-source-drupal` gets rid of these errors and allows the launch of `gatsby develop` environment.
Also below the multiple lines of these errors console throws out:

```
  - query-compiler.js:145 
    [oursite]/[gatsby]/dist/internal-plugins/query-runner/query-compiler.js:145:44
  - Generator.next
  - debuggability.js:313 Promise._execute
    [lib]/[gatsby-cli]/[bluebird]/js/release/debuggability.js:313:9
  - promise.js:483 Promise._resolveFromExecutor
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:483:18
  - promise.js:79 new Promise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:79:10
  - query-compiler.js:213 Runner.write
    [oursite]/[gatsby]/dist/internal-plugins/query-runner/query-compiler.js:213:7
  - query-compiler.js:89 
    [oursite]/[gatsby]/dist/internal-plugins/query-runner/query-compiler.js:89:26
```

### Environment

> System
>     OS: macOS Sierra 10.12.6
>     CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
>     Shell: 3.2.57 - /bin/bash
> Binaries:
>     Node: 9.9.0 - /usr/local/bin/node
>     npm: 6.4.1 - /usr/local/bin/npm
>   Browsers:
>     Firefox: 62.0.3
>     Safari: 12.0.1
>   npmPackages:
>     gatsby: ^2.0.50 => 2.0.50 
>     gatsby-image: ^2.0.20 => 2.0.20 
>     gatsby-plugin-favicon: ^3.1.4 => 3.1.4 
>     gatsby-plugin-manifest: ^2.0.9 => 2.0.9 
>     gatsby-plugin-offline: ^2.0.13 => 2.0.13 
>     gatsby-plugin-react-helmet: ^3.0.2 => 3.0.2 
>     gatsby-plugin-sharp: ^2.0.12 => 2.0.12 
>     gatsby-plugin-styled-components: ^3.0.1 => 3.0.1 
>     gatsby-plugin-typography: ^2.2.1 => 2.2.1 
>     gatsby-source-drupal: ^3.0.9 => 3.0.9 
>     gatsby-source-filesystem: ^2.0.8 => 2.0.8 
>     gatsby-transformer-remark: ^2.1.11 => 2.1.12 
>     gatsby-transformer-sharp: ^2.1.8 => 2.1.8 
>   npmGlobalPackages:
>     gatsby-cli: 2.4.5
>     gatsby: 2.0.50

**Comment by pieh** [comment]
Are you able to share `url` to your rest endpoint? If not publicly here, maybe privately - you can DM me on twitter @mipiechowiak

**Comment by phonoman** [comment]
Data access to the source for reproduction shared over twitter.

**Comment by ezenko** [comment]
@phonoman 
If you still have a problem, try to disable 
imageapi_optimize_pipeline--imageapi_optimize_pipeline
in jsonapi
