### ISSUE TITLE
Add Gatsby websites to the showcase

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#9956]
https://www.gatsbyjs.org/docs/site-showcase-submissions/

- https://www.narcan.com
- https://ritual.com
- https://www.truebill.com
- https://www.smartling.com
- https://www.clearme.com

**Comment by mikeriley131** [comment]
Can we add our own Gatsby sites or are these curated by the core team?

**Comment by DSchau** [comment]
You can definitely add your own sites! Feel free to open a PR and follow [this process](https://www.gatsbyjs.org/docs/site-showcase-submissions/)

Thanks for using Gatsby 💪

**Comment by mikeriley131** [comment]
Thanks, deleted my question because right after posting it I read the link posted in the OP. :)

**Comment by KyleAMathews** [comment]
@btk https://trends.builtwith.com/cms/Gatsby-JS

And hmm automating this could be cool! You interested in trying it? Anything automatically done would probably need manual validation but it'd be great to ensure all larger gatsby sites get added.

**Comment by KyleAMathews** [comment]
We have a paid account so can use their API 

https://api.builtwith.com

**Comment by btk** [comment]
@KyleAMathews  oh maybe I can build a github bot, that crawls this data weekly to create pull requests in the current showcase website adding format, than humans can validate it.

**Comment by GregBorrelly** [comment]
@KyleAMathews hey is this still open ?  I would like to contribute by adding the above sites to the showcase.

**Comment by KyleAMathews** [comment]
@gregborrelly yup! That'd be appreciated!

**Comment by GregBorrelly** [comment]
Perfect, I'll start work on it.

**Comment by GregBorrelly** [comment]
@KyleAMathews https://github.com/gatsbyjs/gatsby/pull/10018

**Comment by prasadseth** [comment]
https://learn.freecodecamp.org

**Comment by LekoArts** [comment]
Done in https://github.com/gatsbyjs/gatsby/pull/10018
