### ISSUE TITLE
gatsby serve doesn't work after running  gatsby build

### ISSUE THREAD

**Issue by Dogtiti** [gatsbyjs/gatsby#9964]
* Node.js version:10.13.0
* Gatsby version :2.4.5
* Operation system : MacOS 10.14.1

`gatsby build`

```success open and validate gatsby-configs — 0.007 s 
success load plugins — 0.173 s
success onPreInit — 0.974 s
success delete html and css files from previous builds — 0.019 s
success initialize cache — 0.006 s
success copy gatsby files — 0.113 s
success onPreBootstrap — 0.011 s
⠂ source and transform nodesStarting to fetch data from Strapi (editors)
Starting to fetch data from Strapi (imgs)
Starting to fetch data from Strapi (articles)
⠄ source and transform nodesFetch Strapi data: 105.772ms
(node:33333) Warning: No such label 'Fetch Strapi data' for console.timeEnd()
(node:33333) Warning: No such label 'Fetch Strapi data' for console.timeEnd()
success source and transform nodes — 0.275 s
success building schema — 0.384 s
```

and then running `gatsby serve`
```info gatsby serve running at: http://localhost:9000/```

the page throw the error as follow image

![image](https://user-images.githubusercontent.com/38354472/48595004-f41cf880-e98d-11e8-9c8c-9b394d1b781c.png)

however，the command `gatsby develop` work well

**Comment by jonniebigodes** [comment]
Can you provide extra information, namely a repository url, if the work you're doing is not private or protected? Also the result of `gatsby info --clipboard`, this so that we can look into the issue and try to help you better.

**Comment by Dogtiti** [comment]
@jonniebigodes  
thanks a lot !
here I create an repo `https://github.com/Dogtiti/gatsby-test.git`
And the result of `gatsby info --clipboard`
```System:
    OS: macOS 10.14.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.12.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.102
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.19 => 2.0.48
    gatsby-image: ^2.0.15 => 2.0.20
    gatsby-plugin-manifest: ^2.0.5 => 2.0.9
    gatsby-plugin-offline: ^2.0.11 => 2.0.14
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.2
    gatsby-plugin-sharp: ^2.0.7 => 2.0.12
    gatsby-source-filesystem: ^2.0.4 => 2.0.8
    gatsby-source-strapi: ^0.0.5 => 0.0.5
    gatsby-transformer-sharp: ^2.1.4 => 2.1.8

```
 
maybe you have to comment some `graphql` to run it well

**Comment by kakadiadarpan** [comment]
@Dogtiti can you provide the version of `gatsby-cli` that you are using?

**Comment by Dogtiti** [comment]
@kakadiadarpan  
v 2.4.5

**Comment by jonniebigodes** [comment]
@Dogtiti sorry for the late response. But i had to do some digging to reproduce your issue.
I installed strapi and generated a new dummy cms to test your code.
Filled it with some dummy content and tried issuing `gatsby build` and it kept throwing errors, namely 

> TypeError: Cannot read property 'data' of undefined

So i went on and did some more digging and for what i've seen of your code you used [this](https://blog.strapi.io/building-a-static-website-using-gatsby-and-strapi/) as a source for your code right?
After comparing both of them i saw that you had some errors in your code.
On your gatsby-node.js file you had:
```javascript
const makeRequest = (graphql, request) => new Promise((resolve, reject) => {
    
    resolve(
        graphql(request).then(result => {
           
            if (result.errors) {
               reject.errors
            }
        })
    )
    return result;
})
```
With that piece of code you had the build will always fail.
With the following change on your code you can build it successfully and issue `gatsby serve` to see your app running:

```javascript
const makeRequest = (graphql, request) => new Promise((resolve, reject) => {
    
    resolve(
        graphql(request).then(result => {
            
            if (result.errors) {
               reject(reject.errors)
            }
            return result
        })
    )
})
```

**Comment by jonniebigodes** [comment]
@Dogtiti did you manage to solve your issue? if so close this one or let me know so i can close it sounds good?

**Comment by Dogtiti** [comment]
@jonniebigodes  I am sorry that I have not responded for so long，yeah，you can close it ,I have soved it

**Comment by jonniebigodes** [comment]
Glad you resolved your issue. I'm closing this as of now. Thanks for using Gatsby 👍

**Comment by sasivarnakumar** [comment]
I was following the gatsby tutorial part 9. I also had the same issue @Dogtiti reported.

Like jonniebigodes advised, I reviewed the `gatsby-node.js` file

In my case, I had a `console.log()` statement. I removed the console log statement and tried to build and serve. Was successful.
