### ISSUE TITLE
Why object is not merged? Something missing in gatsby?

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#9976]
The merged `const articles` displays only the last object... why?

![capture d ecran 2018-11-16 a 15 27 14](https://user-images.githubusercontent.com/814410/48627196-3ce7a800-e9b4-11e8-870e-97d7ef33d109.png)

![capture d ecran 2018-11-16 a 15 27 07](https://user-images.githubusercontent.com/814410/48627200-3fe29880-e9b4-11e8-813e-8c9bbea8ce5f.png)

### Environment (if relevant)
```

  System:
    OS: macOS 10.14
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.102
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.24 => 2.0.43 
    gatsby-image: ^2.0.15 => 2.0.20 
    gatsby-plugin-lodash: ^3.0.1 => 3.0.2 
    gatsby-plugin-manifest: ^2.0.5 => 2.0.8 
    gatsby-plugin-offline: ^2.0.6 => 2.0.13 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.1 
    gatsby-plugin-sharp: ^2.0.7 => 2.0.12 
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.2 
    gatsby-plugin-styled-components: ^3.0.1 => 3.0.1 
    gatsby-source-prismic: ^2.0.0 => 2.1.0 
    gatsby-transformer-sharp: ^2.1.4 => 2.1.8 
  npmGlobalPackages:
    gatsby-cli: 2.4.5
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by DSchau** [comment]
You can't spread an array like that. Because _each_ object contains a property `edges` the last one spread wins out, in this case, pulses.

Here's an example of how you'd fix -> https://runkit.com/dschau/5beed548d565ba0012039100

Closing as answered, but please feel free to re-open if we can help further!

**Comment by Steffi3rd** [comment]
Thank you @DSchau
