### ISSUE TITLE
Why GraphQL returns an error when field is empty?

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#9978]
### CMS from Prismic
![capture d ecran 2018-11-16 a 16 10 02](https://user-images.githubusercontent.com/814410/48629818-f0ec3180-e9ba-11e8-8888-7669c115af46.png)

### GraphQL with description : 👎 
![capture d ecran 2018-11-16 a 16 08 44](https://user-images.githubusercontent.com/814410/48629492-07de5400-e9ba-11e8-9ded-3911853e3ac0.png)

### GraphQL without description : 👍 
![capture d ecran 2018-11-16 a 16 15 58](https://user-images.githubusercontent.com/814410/48629827-f77aa900-e9ba-11e8-82ae-ae43289e4088.png)

## Environnement 

 ```
System:
    OS: macOS 10.14
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.102
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.24 => 2.0.43 
    gatsby-image: ^2.0.15 => 2.0.20 
    gatsby-plugin-lodash: ^3.0.1 => 3.0.2 
    gatsby-plugin-manifest: ^2.0.5 => 2.0.8 
    gatsby-plugin-offline: ^2.0.6 => 2.0.13 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.1 
    gatsby-plugin-sharp: ^2.0.7 => 2.0.12 
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.2 
    gatsby-plugin-styled-components: ^3.0.1 => 3.0.1 
    gatsby-source-prismic: ^2.0.0 => 2.1.0 
    gatsby-transformer-sharp: ^2.1.4 => 2.1.8 
  npmGlobalPackages:
    gatsby-cli: 2.4.5


```

**Comment by LekoArts** [comment]
GraphQL can't return anything if the value is not given. Moreover this is an issue that came up a couple of times now. Please see the issue https://github.com/gatsbyjs/gatsby/issues/2392 and all other linked issues there.
