### ISSUE TITLE
Horizontal scroll site - dynamically set width of #___gatsby

### ISSUE THREAD

**Issue by TaraOShea** [gatsbyjs/gatsby#9981]
Im trying to create a horizontal scroll site, I need to set the width of #___gatsby I have the resize event working, but I need to set this on #___gatsby, any ideas?

**Comment by TaraOShea** [comment]
Thanks! 

Is there also a way to remove the tabindex div? I know it’s for accessibility but would prefer to remove it

**Comment by btk** [comment]
@TaraOShea not sure but, I wouldn't remove that div. You can incorporate the tabindex div by selecting it in your CSS maybe?

```css
#__gatsby > div {
   ...
}
```
Selects only the first div after that parent.
